### ISSUE TITLE
internal compiler error : imgproc : arm-linux-gnueabi

### ISSUE THREAD

**Issue by dewagter** [opencv/opencv#10006]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => Linux 64 Bit
- Compiler => /usr/bin/arm-linux-gnueabi-g++  (ver 4.7.3)

##### Detailed description

internal compiler error:

[ 58%] Building CXX object modules/world/CMakeFiles/opencv_world.dir/__/imgproc/src/connectedcomponents.cpp.o
/home/travis/build/tudelft/opencv_bebop/opencv/modules/imgproc/src/connectedcomponents.cpp: In member function ‘LabelT cv::connectedcomponents::LabelingWu<LabelT, PixelT, StatsOp>::operator()(const cv::Mat&, cv::Mat&, int, StatsOp&) [with LabelT = short unsigned int; PixelT = unsigned char; StatsOp = cv::connectedcomponents::NoOp]’:
/home/travis/build/tudelft/opencv_bebop/opencv/modules/imgproc/src/connectedcomponents.cpp:820:9: internal compiler error: in gen_thumb_movhi_clobber, at config/arm/arm.md:6453

##### Steps to reproduce

cross compile on ubuntu 14.04 or 16.04 for arm-linux-gnueabi

OR:

clone: https://github.com/tudelft/opencv_bebop/tree/opencv3_3_1
make

**Comment by alalek** [comment]
We don't [observe](http://pullrequest.opencv.org/buildbot/builders/master_ARMv7-lin/builds/10268) build issues with `/usr/bin/arm-linux-gnueabihf-g++  (ver 4.8.4)`.
Consider to upgrade used compiler.

BTW, Internal compiler error (ICE) bugs should be filled into compiler bug trackers, somewhere here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44557
