### ISSUE TITLE
DNN face detector

### ISSUE THREAD

**Issue by caocuong0306** [opencv/opencv#10012]
Hi everyone,

I tried to test **face detector** sample code using **dnn**.

However, I cannot find **res10_300x300_ssd_iter_140000**.caffemodel to load.

Hope anyone could help.

Thank you.

**Comment by berak** [comment]
currently, there is no pretrained model for this, you have to train your own, please [have a look here](https://github.com/opencv/opencv/blob/master/samples/dnn/face_detector/how_to_train_face_detector.txt)

**Comment by caocuong0306** [comment]
I haven't read all the .txt files.

Hope to reproduce soon.  Thanks a lot.

**Comment by alalek** [comment]
It is downloaded in this CMake [script](https://github.com/opencv/opencv/blob/3.3.1/samples/dnn/CMakeLists.txt#L20) (required `BUILD_EXAMPLES=ON`). Sample model file is available [here](https://github.com/opencv/opencv_3rdparty/tree/dnn_samples_face_detector_20170830).

**Comment by caocuong0306** [comment]
Thank you @alalek, I run this successfully. Awesome.

**Comment by zhanglaplace** [comment]
@alalek i test the facedetect only 1fps, is normal ?

**Comment by lyp-deeplearning** [comment]
@caocuong0306 can you tell me which prototxt did you use?
