### ISSUE TITLE
UI elements not rendering correctly.

### ISSUE THREAD

**Issue by ghltshubh** [opencv/opencv#10019]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => macOS 10.13(High Sierra)
- Compiler => Anaconda Spyder 3.2.4 (Python 3.6)

##### Detailed description

I am doing the "trackbar as the color palette" [example](https://docs.opencv.org/master/d9/dc8/tutorial_py_trackbar.html) from the documentation.

But [UI](https://i.stack.imgur.com/6GQ7l.png) elements are cropped and rendered in wrong order whereas they are supposed to render like [this](https://i.stack.imgur.com/5cw30.png).
##### Steps to reproduce

```
import cv2
import numpy as np
# Trackbar as the color palette
def nothing(x):
    pass
# Create a black image, a window
img = np.zeros((300,512,3), np.uint8)
cv2.namedWindow('image', cv2.WND_PROP_AUTOSIZE)
# Create trackbars for color change
cv2.createTrackbar('R','image',0,255,nothing)
cv2.createTrackbar('G','image',0,255,nothing)
cv2.createTrackbar('B','image',0,255,nothing)
# Create switch for ON/OFF functionality
switch = '0 : OFF \n1 : ON'
cv2.createTrackbar(switch, 'image',0,1,nothing)
while(1):
    cv2.imshow('image',img)
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
    # Get current positions of four trackbars
    r = cv2.getTrackbarPos('R','image')
    g = cv2.getTrackbarPos('G','image')
    b = cv2.getTrackbarPos('B','image')
    s = cv2.getTrackbarPos(switch,'image')
    if s == 0:
        img[:] = 0
    else:
        img[:] = [b,g,r]
        
cv2.destroyAllWindows()
```

[steps_to_reproduce_error.txt](https://github.com/opencv/opencv/files/1441894/steps_to_reproduce_error.txt)

**Comment by alkasm** [comment]
Issue #5056 has already brought this up. Please add your system specs to that thread to keep it all in one place.
