### ISSUE TITLE
"Opencv_java331.dll: Can't find dependent libraries" 

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#10017]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

I have compiled the OpenCV from source with GStreamer support for Java, everything was OK. 
**But** in below two cases I got this problem:

1. When I copy the generated JAR and DLL files to the other machine (although I have everything installed in both of machines, such as GStreamer, and all necessary libs and software).
2. When the build process finished and the JAR and DLL files were generated successfully, an also tested all works well, but when restarted the computer this problem is happening, the same as when I used the JAR and DLL files on the other machine.

Before (compiling without GStreamer) I did not get the problem. But now why this problem is going to happen, I have all in the classpath and system path and environment path. GStreamer can found anywhere in the machine because I have added all the path (DLL, and Libs) to the system path.

Any suggestion!!

**Comment by alalek** [comment]
This tracker is for issues and bugs that needs fix in OpenCV.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Bahramudin** [comment]
@alalek  Thanks! I think it can belong to OpenCV.
