### ISSUE TITLE
Weird behaviour when linking libtensorflow_framework with opencv

### ISSUE THREAD

**Issue by stereomatchingkiss** [opencv/opencv#10027]
- os : ubuntu16.04.1 
- compiler : g++ 5.4.0 20160609 opencv 3.3.1 

Create an app with tensorflow(version 1.4) c++ library and opencv, there are weird behaviour when I link opencv with libtensorflow_framework.so.

1. imshow, protobuf version conflict

   

>  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.4.0). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)

2. imwrite, the program suddenly end, no error messages at all

3. imread, cannot read image(every image are empty)

        //cannot read the image, always empty
        cv::Mat input_mat = cv::imread(argv[1], cv::IMREAD_COLOR);
        std::cout<<argv[1]<<", size:"<<input_mat.size()<<std::endl;
    
        cv::VideoCapture cap("video.mp4");
        if(!cap.isOpened()){
            std::cerr<<"cannot open video"<<std::endl;
            return -1;
        }
    
        cv::Mat frame;
        int index = 0;
        while(1){
            cap>>frame;
            if(frame.empty()){
                break;
            }
    
            //complain protobuf version imcompatible
            cv::imshow("frame", frame);
            cv::waitKey(30);        
            std::cout<<index++<<","<<frame.size()<<std::endl;
            //crash after calling imwrite
            cv::imwrite("imgs/img_" + std::to_string(index++) + ".jpg", frame);
        }

**Comment by stereomatchingkiss** [comment]
Looks like this is a bug of tensorflow, a quick fix is change the link order,
I should link to -lprotobuf -ltensorflow_framework -ltensorflow_cc before the library of opencv

Please close this issue

**Comment by kxhit** [comment]
I am using tensorflow r1.4 and opencv3.1 in ubuntu14.04.
When I include #include <tensorflow/core/public/session.h> or
#include "tensorflow/cc/ops/standard_ops.h" I cannot read images from cv::VideoCapture adn I got empty mat. When I didn't include these tensorflow headers, I can read frame successfully. Anyone could help me? Thanks a lot!!! Could you tell me your solution  specifically?  @stereomatchingkiss

Here is my cpp file:
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include "tensorflow/cc/ops/standard_ops.h"
#include <opencv2/opencv.hpp>
#include
using namespace std;
using namespace tensorflow;

int main()
{
cv::VideoCapture cap;
if(!cap.open("/home/kx/project/RM-dataset/01.avi")){
std::cout<<"cannot open video "<<std::endl;
}
cv::Mat frame;
while(1){
cap>>frame;
if(frame.empty()){
std::cout<<"no frame"<<std::endl;
continue;
}
cv::imshow("frame",frame);
cv::waitKey(0);
}
return 0;
}

my cmake file:

cmake_minimum_required (VERSION 2.8)
project (tf_example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++11 -W")
find_package(OpenCV 3.1.0 REQUIRED)
include_directories(
/home/kx/something/tensorflow-r1.4
/home/kx/something/tensorflow-r1.4/tensorflow/bazel-genfiles
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/protobuf/include
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/host_obj
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/proto
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/nsync/public
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/eigen
/home/kx/something/tensorflow-r1.4/bazel-out/local-py3-opt/genfiles
${OPENCV_INCLUDE_DIRS}
)

add_executable(tf_test tf_test.cpp)
target_link_libraries(tf_test
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_cc.so
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_framework.so
${OpenCV_LIBS}
)

The results:
no frame

**Comment by mrlzla** [comment]
I have got the problem too
