### ISSUE TITLE
cv2.videocapture of a h.264/mp4 not working (FFMPEG)

### ISSUE THREAD

**Issue by Guilmort** [opencv/opencv#10026]
**System information:**
- OpenCV 3.3.1 + opencv_contrib 3.3.1
- Ubuntu Zesty + Gnome 3
- Python 3.5.3
- cmake 3.7.2
- gcc Ubuntu 6.3.0-12ubuntu2
- FFMPEG 3.4.git

**Detailed description:**

**FFMPEG information :**
ffmpeg version 3.4.git Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Ubuntu 6.3.0-12ubuntu2) 20170406
  configuration: --prefix=/home/guilmort/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/guilmort/ffmpeg_build/include --extra-ldflags=-L/home/guilmort/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/guilmort/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.102 / 58.  0.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100

**cmake command :**
`
cmake -D CMAKE_BUILD_TYPE=RELEASE     -D CMAKE_INSTALL_PREFIX=/usr/local     -D INSTALL_PYTHON_EXAMPLES=ON     -D INSTALL_C_EXAMPLES=OFF     -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.1/modules     -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python     -D BUILD_EXAMPLES=ON ..
`

**cmake partial result:**
`

--   Video I/O:
--     DC1394 1.x:                  NO 
--     DC1394 2.x:                  NO
--     FFMPEG:                      **NO** ---> FFMPEG always to NO !
--       avcodec:                   YES (ver 57.28.103)
--       avformat:                  YES (ver 57.28.101)
--       avutil:                    YES (ver 55.19.100)
--       swscale:                   YES (ver 4.0.100)
--       avresample:                **NO**
--     GStreamer:                   NO`

**Basic code:**
`cap = cv2.VideoCapture(<an mp4 file with absolute (right) path)
if cap.isOpened():
    print("cap is opened")
else:
    print("cap is not")
    exit(1)`
**---> Cap is not opened**

**Comment by alalek** [comment]
> -- FFMPEG: NO ---> FFMPEG always to NO !

You should resolve this problem in your build configuration.
Check for this warning at first: "WARNING: Can't build ffmpeg test code"

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Guilmort** [comment]
Hello Alalek, believe me I tried all I can

By removing comment cmake/OpenCVFindLibsVideo.cmake in order to check for FATALS
I  got:
```
/usr/bin/ld: /usr/local/lib/libavformat.a(utils.o): relocation R_X86_64_32
  against `.rodata.str1.1' can not be used when making a shared object;
  recompile with -fPIC

  /usr/bin/ld: /usr/local/lib/libavformat.a(avio.o): relocation R_X86_64_32
  against `.rodata.str1.1' can not be used when making a shared object;
  recompile with -fPIC

  /usr/bin/ld: /usr/local/lib/libavformat.a(aviobuf.o): relocation
  R_X86_64_32 against symbol `ffurl_context_class' can not be used when
  making a shared object; recompile with -fPIC 
.........   
```
**and so on...**

Is it still a usage question ? (I asked one there)
Thanks for your help

**Comment by alalek** [comment]
>  recompile with -fPIC

recompile ffmpeg with fpic flag (`./configure --enable-pic ...`): https://askubuntu.com/a/527877

**Comment by alalek** [comment]
Yes, this is still usage question.
This tracker is for issues and bugs that needs fix in OpenCV (currently there is no appropriate OpenCV fix for this).

**Comment by AgFlores** [comment]
Hello all!
Anybody knows if there's currently an issue to solve this problem?

**Comment by pati-rosa** [comment]
not solved!
