### ISSUE TITLE
OpenCV4Android Tutorial3 takePicture Camera: Error -2147483648

### ISSUE THREAD

**Issue by heaton0308** [opencv/opencv#10029]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Android 7.1.1 MIUI 9 7.11.2
- Compiler => Android Studio 2.3

##### Detailed description

Tutorial3View takePicture got error.

`11-06 11:30:28.978 5004-5004/org.opencv.samples.tutorial3 I/OCVSample::Activity: onTouch event
11-06 11:30:28.984 5004-5004/org.opencv.samples.tutorial3 I/Sample::Tutorial3View: Taking picture
11-06 11:30:28.994 5004-5004/org.opencv.samples.tutorial3 D/Sample::Tutorial3View: pictureSize = 176x144
11-06 11:30:33.157 5004-5004/org.opencv.samples.tutorial3 W/MIUI-BLOCK-MONITOR: The input: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=1605.0, y[0]=628.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=75215685, downTime=75215685, deviceId=3, source=0x1002 } took 4179ms.
11-06 11:30:33.159 5004-5004/org.opencv.samples.tutorial3 E/Camera: Error 1
11-06 11:30:33.171 5004-5004/org.opencv.samples.tutorial3 I/Toast: Show toast from OpPackageName:org.opencv.samples.tutorial3, PackageName:org.opencv.samples.tutorial3, content:OCV T3 Camera Control：/storage/emulated/0/sample_picture_2017-11-06_11-30-28.jpg saved
11-06 11:30:33.173 5004-5004/org.opencv.samples.tutorial3 E/Camera: Error -2147483648`
##### Steps to reproduce
Device : XIAOMI 6 ,XIAOMI MIX , HUAWEI HONOR 7 touch screen.

**Comment by asmorkalov** [comment]
Fixed in https://github.com/opencv/opencv/pull/24622
