### ISSUE TITLE
 cv::fisheye::stereoCalibrate errors

### ISSUE THREAD

**Issue by ansonlym** [opencv/opencv#10034]
Log:  
OpenCV Error: Assertion failed (!objectPoints.empty() && objectPoints.type() == CV_64FC3) in projectPoints, file /home/ai/Downloads/opencv31/opencv/modules/calib3d/src/fisheye.cpp, line 1166
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/ai/Downloads/opencv31/opencv/modules/calib3d/src/fisheye.cpp:1166: error: (-215) !objectPoints.empty() && objectPoints.type() == CV_64FC3 in function projectPoints

code:
```
	cv::Matx33d K1,K2, theR;
	cv::Vec3d theT;
	cv::Vec4d D1, D2;

	int flag = 0;
	flag |= cv::fisheye::CALIB_RECOMPUTE_EXTRINSIC;
	flag |= cv::fisheye::CALIB_CHECK_COND;
	flag |= cv::fisheye::CALIB_FIX_SKEW;
	double rms = cv::fisheye::stereoCalibrate(objectPoints,imagePoints[0], imagePoints[1], K1, D1,
			K2, D2, imageSize, theR, theT, flag, cv::TermCriteria(3, 12, 0));
```

Does anyone encounter this problem?

**Comment by alalek** [comment]
This message is related to invalid usage of OpenCV function (invalid/unsupported parameters).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
