### ISSUE TITLE
cv::dnn::Net::forward returns the same box as the previous detection

### ISSUE THREAD

**Issue by didulle** [opencv/opencv#10049]
Hi

While using MobilenetSSD or Squeezenet the same bounding boxes as the previous image are predicted while the network didn't find any object. If I use those images as a first image it returns no objects.

Thanks

**Comment by alalek** [comment]
What OpenCV version is used?
Do you have this patch: #9959 ?

**Comment by didulle** [comment]
I use OpenCV 3.3.0. I don't have this patch. i have downloaded the binary files from OpenCV websites directly. May be it make sense to get 3.3.1 that may be fix that issue

**Comment by alalek** [comment]
This patch is not available in 3.3.1 too (there are no releases with this patch yet).
