### ISSUE TITLE
Opencv pkg-config config file is unusable, Opencv 3.3.1 Homebrew OSX

### ISSUE THREAD

**Issue by staviq** [opencv/opencv#10046]
File `/usr/local/lib/pkgconfig/opencv.pc` has all the linker flags wrong, and it makes pkg-config unusable for opencv.

example:

it is:
`-llibopencv_stitching.3.3.1.dylib`

it should be:
`-lopencv_stitching`

etc.

Fresh install OSX 10.13 High Sierra.

`$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ade735b9e95352f1731445bad505d920c9521969
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11`

`$ brew info opencv
opencv: stable 3.3.1 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/3.3.1_1 (519 files, 95.8MB) *
  Built from source on 2017-11-08 at 11:53:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: eigen ✔, ffmpeg ✔, jpeg ✔, libpng ✔, libtiff ✔, openexr ✔, numpy ✔, tbb ✔
==> Requirements
Required: python ✔, python3 ✔`

Also reported in Homebrew bug tracker: https://github.com/Homebrew/homebrew-core/issues/20406

**Comment by alalek** [comment]
Try to add `dylib` suffix here: https://github.com/opencv/opencv/blob/3.3.1/cmake/OpenCVUtils.cmake#L1028

**Comment by ilovezfs** [comment]
.dylib goes after the numbers, not before them

**Comment by alalek** [comment]
@ilovezfs This should not be a problem (numbers are optional)

test.cmake:
```
set(__libname "libopencv_stitching.3.3.1.dylib")
string(REGEX REPLACE "^lib(.+).(a|so|dylib)(.[.0-9]+)?$" "\\1" __libname "${__libname}")
message(STATUS "${__libname}")
```
Result (`cmake -P test.cmake`):
```
-- opencv_stitching.3.3.1
```

Or we should drop numbers too?

**Comment by ilovezfs** [comment]
numbers need to go too

**Comment by ilovezfs** [comment]
As a reference, in 3.3.0 the file was
```
iMac-TMP:3.3.0_3 joe$ cat lib/pkgconfig/opencv.pc 
# Package Information for pkg-config

prefix=/usr/local/Cellar/opencv/3.3.0_3
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir_old=${prefix}/include/opencv
includedir_new=${prefix}/include

Name: OpenCV
Description: Open Source Computer Vision Library
Version: 3.3.0
Libs: -L${exec_prefix}/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_photo -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_fuzzy -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
Libs.private: -framework OpenCL -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -lAccelerate -L/usr/local/lib -lpng -ltiff -lImath -lIlmImf -lIex -lHalf -lIlmThread -lavcodec -lavformat -lavutil -lswscale -lavresample -L/usr/lib -lz -framework VideoDecodeAcceleration -lbz2 -framework Cocoa -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore
Cflags: -I${includedir_old} -I${includedir_new}
iMac-TMP:3.3.0_3 joe$ 
```
