### ISSUE TITLE
No instructions in the tutorials for which libraries to link

### ISSUE THREAD

**Issue by melvyniandrag** [opencv/opencv#10042]
I'm working through the tutorials and I'm having to search all over google when I compile an example to see which libraries I need to link. Since I quickly find answers, it seems like lots of people are hitting the same issue, which could be easily solved. I would like to add a comment to the top of tutorials about which libraries to link. 

For example, to the top of https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/objectDetection/objectDetection.cpp I would add something like:

```
/*
Sample compile command on ubuntu:
g++ main.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_videoio -lopencv_objdetect
*/
```

I have added this to the top of all the tutorials I've done so if I revisit it I don't have to search headers to see which function is where in the opencv stack.

Ill submit a PR if you think this is a good idea. I've only used opencv2, I suspect the library names have changed slightly between versions so multiple comments like the one I mention should be there. I'll build opencv3 too and verify that the instructions are correct.

**Comment by alalek** [comment]
Such "linker" string just not exits, it is very specific for build configuration (take a look on opencv_world).
Also it doesn't cover non-Linux platforms (Windows, Android.mk, Apple frameworks)

Official way is to use CMake to build with OpenCV (via `find_package()`).
Other approaches are very restricted - support limited number of configurations (pkg-config) and/or platform specific (Android.mk / Apple frameworks).

**Comment by mshabunin** [comment]
The best way to build all OpenCV tutorials and examples is to provide `-DBUILD_EXAMPLES=ON` option to cmake when configuring OpenCV and to build corresponding target: `cmake --build . --target tutorial_objectDetection`

If you want to build custom application which uses OpenCV, you should use cmake-way as @alalek wrote. Template can be found here: https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake
