### ISSUE TITLE
Calibration simulation gives wrong answer

### ISSUE THREAD

**Issue by yrzhanov** [opencv/opencv#10054]
- OpenCV => 3.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2012

Hello,
I'm investigating influence of calibration target on accuracy of calibration. When points are organized in a 3D pattern, calib3d uses DLT method for initial estimation of extrinsics. Without noise (in projection of calibration target features) estimation works fine. With small random Gaussian noise, occasionally the estimate is wrong and result is very different from true values. With increasing noise percentage of "bad" results grows. This never happens when all target points are planar, but then calib3d does not use DLT...
The issue is not repeatable, as it depends on the randomizing seed, but typical ratio of "bad" estimates is:
Noise   Percentage
0.01     0.0
0.03    3.6
0.05    6.3
0.07   10.6
0.1     15.4

Any ideas why DLT may fail?

Thanks,
    Yuri

**Comment by yrzhanov** [comment]
My apologies for asking question without any code. It had dependencies on some third party libraries. Just hoped that somebody came across this issue before. Apparently not. So, here is the code, without any non-OpenCV dependencies, so anyone can reproduce the error. Convergence to correct or incorrect output depends on the random seed. At the top of main, there are two "bad" seeds, leading to wrong output and one "good" one. I think that this indicates a bug in calib3d.

Thanks,
    Yuri
[CalibrationAccuracyTrimmed.zip](https://github.com/opencv/opencv/files/1467956/CalibrationAccuracyTrimmed.zip)

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by yrzhanov** [comment]
I believe that the described problem requires fixes in DLT implementation, in calib3d module of OpenCV. It’s not “Please explain how…”

 

Cheers,

    Yuri

 

===============================================================================

Yuri Rzhanov

Center for Coastal and Ocean Mapping/Joint Hydrographic Center

University of New Hampshire

Tel: 1-603-8620075

 

Let go all your heartaches, it's as easy as being free 
You don't have to wait a while
