### ISSUE TITLE
Git command typo in contributing guidelines wiki

### ISSUE THREAD

**Issue by akhilesh-k** [opencv/opencv#10067]
In contributing guidelines git there is a typo in git command. It is :
```
git diff -check
```
but it should be:
```
git diff --check
```
It is about fixing whitespace error. Check the wiki page [here](https://github.com/opencv/opencv/wiki/How_to_contribute)

**Comment by akhilesh-k** [comment]
It might be but when one actually copies, single dash symbol gets copied.

**Comment by mshabunin** [comment]
Converted the mentioned page to Markdown.

**Comment by akhilesh-k** [comment]
Great. Please look at the Pull Request 10056. It needs to be merged. Please find [here](https://github.com/opencv/opencv/pull/10056)
