### ISSUE TITLE
Unable to use opencl 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10071]
##### Detailed description

Hi, 

I posted a question on [answers.opencv.org](http://answers.opencv.org/question/177929/unable-to-use-opencl-with-user-right-on-win10/) without answer. Problem is how to use opencl with user privilege on windows 10. 
My program is only one line
    ocl::setUseOpenCL(true);
    if (ocl::haveOpenCl())
        cout<<"Opencl is activated\n";

In september no problem but now there is an exception at 
`OpenCV Error: Unknown error code -220 (OpenCL error Unknown OpenCL error (999) during call: clCreateContext) in cv::ocl::Context::Impl::setDefault, file G:\Lib\opencv\modules\core\src\ocl.cpp, line 1327
`

There is no exception in release mode because exception are disabled but code run fine. 

problem is [here ](https://github.com/opencv/opencv/blob/master/modules/core/src/ocl.cpp#L1326-L1327)
```
        handle = clCreateContext(prop, nd, &d, 0, 0, &status);
        CV_OCL_DBG_CHECK_RESULT(status, "clCreateContext");

```
After clcreatecontext status value is 999 in debug and in release and handle is NULL. Exception is thrown in debug, but there in no need to throw it. If I change status value to 0 and  keep handle to NULL then ok is false and I can see in my program is activited. Error code for glcreatecontext are negative and not positive,  may be CV_OCL_DBG_CHECK_RESULT(status<0, "clCreateContext"); will solve my problem.

**Comment by alalek** [comment]
0. Mentioned patch goal is to catch most part of OpenCL API errors instead of silently eating them. Especially in the Debug mode.

1. Code snippet doesn't look valid:
    - 1st call should be `ocl::haveOpenCl()` (checks that OpenCL support is compiled and OpenCL 1.2+ runtime is found) with checking of return value. Calling `ocv::setUseOpenCL(true)` without this check is programming error.
It is usually used to initialize OpenCL context in a custom way (D3D/OpenGL sharing).

    - 2nd call should be `ocl::setUseOpenCL()`. Mostly used to disable/enable (in this order) OpenCL optimizations in the current thread.. Not needed to call at all in normal programs (allow users to configure OpenCV-OpenCL externally). This function raises an error, because you explicitly asks to enable OpenCL support, but it can't do it, so you got proper answer about this via exception.
Why it still eats problem in Release mode? I believe this will be fixed in the next major OpenCV update.

    - 3rd call should be `ocl::useOpenCL()` - checks that OpenCL is activated successfully. It is enough to have this call only to check OpenCL final activation. This function should not raise any exceptions.

    - so your snippet code should be:
        `if (ocl::useOpenCl()) cout << "OpenCL is activated\n";`

2. Installed OpenCL runtime seems broken/non-conformant to OpenCL specification.
Refer to documentation of mentioned OpenCL API call: https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clCreateContext.html
There is no expected results above zero (`CL_SUCCESS` is `0`), so I have no idea that 999 mean.
OpenCV team can't fix this, but we have workaround to disable malfunction runtimes - add empty environment variable "OPENCV_OPENCL_RUNTIME" with empty value or just 'xxx'.

**Comment by LaurentBerger** [comment]
> 1 and 2 
doesn't solve my problem
> Installed OpenCL runtime seems broken/non-conformant to OpenCL specification.
Agree running exactly same program as admin there is no exception opencl is activated : 
```
Platform Name: NVIDIA CUDA
 GPU device
getNumberOfCPUs =12      getNumThreads = 13
Without opencl umat      with opencl umat        with opencl mat         without opencl mat for cvtColor(0),Blur(1),Canny(2)
cvtColor = (2.92173 +/-0.562221)false           (0.134852 +/-0.00943858)true
        (1.21265 +/-0.415252)false              (1.06319 +/-0.0955676true

gaussianblur = (354.168 +/-5.1451)false         (7.72648 +/-38.2405)true                (349.043 +/-5.11878)false               (351.208 +/-8.592)true

```

I close this issue and try to solve my install problem  (same problem [here](https://github.com/gcp/leela-zero/issues/26)).

**Comment by alalek** [comment]
@LaurentBerger Try to run clinfo (from [here](https://github.com/Oblomov/clinfo) or from Ubuntu packages).

> as admin

Linux guide:
```
$ ls -al /dev/dri/
... <grab group name from files>
$ usermod -G <group name> -a <your login>
```
something like this:
```
sudo usermod -G video -a $USER
```

After that, re-login and check:
```
$ id
or
$ groups
```

**Comment by LaurentBerger** [comment]
@alalek thanks for your help. I use windows I download clinfo [here](https://boinc.berkeley.edu/dl/clinfo.zip)
I ran this program using [admin privilige](https://gist.github.com/LaurentBerger/4df47c0fa6ce2e7ba3fb88e5fac913a1) and[ user privilige](https://gist.github.com/LaurentBerger/4b9d3af370ec1e0c85826bdbec88c3c2) only difference is : 
fiel                 admin         user
Platform ID: | 003BE430 | 013D2AE0 | FAUX

**Comment by LaurentBerger** [comment]
back to driver 21.21.13.7653 and opencl is OK
