### ISSUE TITLE
opencl wrong colors on cv::cvtColor(dstm, dstm, CV_YUV2BGR_NV12);

### ISSUE THREAD

**Issue by arpu** [opencv/opencv#10088]
##### System information (version)
- OpenCV =>  master fcdd83305974ce8870a7ed961a1e1d426bfe46a5
- Operating System / Platform => Fedora 26 64bit
- Compiler => gcc

using the gstreamer pipeline to get NV12 image and convert to BGR  for opencv 
using cv::cvtColor(dstm, dstm, CV_YUV2BGR_NV12); with opencl enabled 

i get wrong colors see image included 
![result_bug_nv12_bgr](https://user-images.githubusercontent.com/14173/32794359-ec1f6294-c968-11e7-813a-a3c7d377cacc.png)

**Comment by alalek** [comment]
Could you please capture this [image](https://en.wikipedia.org/wiki/RGB_color_model#/media/File:AdditiveColor.svg) instead.

There is [test](https://github.com/opencv/opencv/blob/3.3.1/modules/imgproc/test/ocl/test_color.cpp#L372) for this color conversion.

Also VideoCapture doesn't support formats well other than BGR. How do you get NV12 image?

**Comment by arpu** [comment]
i use gstreamer videopipe 
 QString gst_pipe0 =
          "v4l2src io-mode=dmabuf device=/dev/video" + QString::number(device_id) +
          " extra-controls=\"c,exposure_auto=0,gain=0\" ! image/jpeg, framerate=60/1, width=1920, height=1080  "
          "! "
          " vaapijpegdec ! appsink";
m_cvCapture.open(gst_pipe0.toStdString())
the output of vaapijpegdec is NV12  and since some commits this works fine with the gstreamer pipe
https://github.com/opencv/opencv/commit/96a3c7954d1678aa8e8be2743f5c3373fa25f205#diff-a87d65dfc2271376e017988c93d9a286

i will try with your test images

**Comment by arpu** [comment]
ok looks like a vaapijpegdec bug 
works with ... vaajpegdec ! videoconvert ! video/x-raw,format=NV12 ! appsink

**Comment by arpu** [comment]
![resultme_bug](https://user-images.githubusercontent.com/14173/32806074-ab67be5e-c98b-11e7-94fd-bc36b62ecdda.png)

but maybe its more a header problem?

**Comment by alalek** [comment]
> opencl

To be sure, disable OpenCL in OpenCV via "export OPENCV_OPENCL_DEVICE=disabled"

**Comment by alalek** [comment]
> NV12

BTW, OpenCV doesn't expect any gap between Y and UV planes. Looks like you have one.
