### ISSUE TITLE
IMREAD_LOAD_GDAL does not correctly handle color table gif or color jpeg files

### ISSUE THREAD

**Issue by gdkessler** [opencv/opencv#10089]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
##### Detailed description

The GDAL decoder in imgcodecs/src/grfmt_gdal.cpp does not correctly handle gif files that use a color table. The image created will be greyscale. In addition, color images of other formats, for example jpeg, may have their color components mixed up, as the GDAL decoder does not respect the color interpretation of the bands, as given by GDAL. In fact, the colors are taken to be blue, green, red, when they are usually red, green, blue (resulting in the problem described in issue #9809).

These problem can be reproduced using program code below and the attached images.

I have code fixes to suggest that I will create a pull request for.

![colorchips](https://user-images.githubusercontent.com/22819979/32806641-3c876780-c95b-11e7-9147-b4e70c70fdc3.png)
![colorchips](https://user-images.githubusercontent.com/22819979/32806642-3d642166-c95b-11e7-9897-9c292030371c.gif)
![colorchips](https://user-images.githubusercontent.com/22819979/32806643-3d8cfa00-c95b-11e7-9e0b-9284cbdbf7f7.jpg)

##### Steps to reproduce

```.cpp
/*
 * Test GDAL image read
 */

#include <iostream>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>

void printUsage(char *progName)
{
    std::cout << "Usage: " << progName << " [option(s)] image1 ...\n";
    std::cout << "Options:\n"
              << "  -h   Help\n";
}

int main( int argc, char** argv )
{
  int firstArg = 1;
  
  if (argc > 1)
  {
    if (strcmp(argv[1], "-h") == 0)
    {
      printUsage(argv[0]);
      return -1;
    }
  }

  if((argc-firstArg) == 0)
  {
    printUsage(argv[0]);
    return -1;
  }

  // Create a window for display.
  cv::namedWindow( "Display window", cv::WINDOW_AUTOSIZE );

  for (size_t i=firstArg; i < argc; i++)
  {
    std::cout << "Loading image file " << argv[i] << "...\n";

    cv::Mat image;

    // Read the file
    int readFlags = CV_LOAD_IMAGE_COLOR | cv::IMREAD_LOAD_GDAL;
    image = cv::imread(argv[i], readFlags);

    // Check for invalid input
    if(image.empty())
    {
      std::cerr <<  "Could not open or find the image\n";
    }
    else
    {
      std::cout << "Read " << image.cols << " x " << image.rows << " x "
                << image.elemSize() << " image\n";

      // Show our image inside it.
      cv::imshow( "Display window", image );
    }

    // Wait for a keystroke in the window
    cv::waitKey(0);
  }
  return 0;
}
```

**Comment by alalek** [comment]
> the colors are taken to be blue, green, red

OpenCV uses BGR format (in this order) for color images.


Could you attach `.zip` archive with used image files (use link under comments text area)?

**Comment by gdkessler** [comment]
Images in a zip
[GdalTestImages.zip](https://github.com/opencv/opencv/files/1472975/GdalTestImages.zip)

**Comment by gdkessler** [comment]
The color issue is that the GDAL library usually (but not always) provides the color as red, green, blue, and therefore if they are taken in order, as the OpenCV GDAL decoder does for 3 and 4 component color images, then the order is wrong.
