### ISSUE TITLE
Possible bug for cv::FindHomography with custom MyAllocator : public cv::MatAllocator

### ISSUE THREAD

**Issue by ShaharSarShalom** [opencv/opencv#10098]
Hey 

I created my own opencv  intel - Ippi based allocator, my allocator class inherent from cv::MatAllocator 
and and uses ippiMalloc_8u(...) for every memory allocation. 

My allocator allocate memory with stride, which means that the data is not continues, even though when I  create a 3x3 cv::Mat matrix .

The problem start when I use cv::findHomography function,  this function used to work excellent with the cv::Mat::DefaultAllocator.
However when I use ippi based allocator the function return an empty matrix (e.g for error). 

I dive into opencv code -  calib3d\src\fundam.cpp, line 116, 

`cout = m1.checkVector()`

cout  returns -1, (instead of 4 by  default allocator)

The question is why cv:::FindHomograpy  doesn't work with using my allocator ? Is that a possible bug? 
I assumed opencv should work with any allocator given.

Thanks for your help 

S 

##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Steps to reproduce

I can send my allocator function if needed

**Comment by alalek** [comment]
`cv::Mat` can be [created on pre-allocated memory](https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a5fafc033e089143062fd31015b5d0f40).
Could you provide reproducer via this constructor?

**Comment by ShaharSarShalom** [comment]
no, I can't
