### ISSUE TITLE
the comment of rotatingCalipers function

### ISSUE THREAD

**Issue by suijingfeng** [opencv/opencv#10096]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu16.04
- Compiler => GCC

##### Detailed description
what is the meaning of following comment on rotateCalipers function in https://github.com/opencv/opencv/blob/3.3.1/modules/imgproc/src/rotcalipers.cpp?
```
	 ((CvPoint2D32f*)out)[0] - corner
	 ((CvPoint2D32f*)out)[1] - vector1
	 ((CvPoint2D32f*)out)[0] - corner2
```

**Comment by paroj** [comment]
probably a type. from the code it should be:
`((CvPoint2D32f*)out)[2] - vector2`

**Comment by victor-ludorum** [comment]
@paroj @suijingfeng  Hello I am new to OpenCV . I want to work on this issue . Please guide me how to start .

**Comment by victor-ludorum** [comment]
I have made [PR](https://github.com/opencv/opencv/pull/10470) , by updating the comment section .
Kindly review it .
