### ISSUE TITLE
When the OpenCV will relaese the Java bindings with GPU support?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#10119]
##### System information (version)

- OpenCV =>3.3.1
- Operating System / Platform => Windows 64 Bit
- Compiler =>Visual Studio 2017

##### Detailed description

It is for a long time that I am waiting for the OpenCV to support CUDA module in Java bindings, but till now there is no any support to CUDA module from Java bindings. But the question is: then how can we access the CUDA module from Java because we want to perform some task with OpenCV in Java that really needs GPU functionality, but still we not have access to CUDA module from Java bindings. I hope that the OpenCV organization take care to this point. It can be a great news to the Java developers.

Note: Yes I know there is a JavaCV framework that maybe support the GPU, but I am still interested in OpenCV. 

Thanks!!!

**Comment by alalek** [comment]
There are no such plans from OpenCV dev team.
Only community contribution may help with this problem - we just can review properly prepared patch.

Lets keep these discussion in single place: #8560
