### ISSUE TITLE
Using `cv::cuda::spli`t results in SEGFAULT

### ISSUE THREAD

**Issue by alexge233** [opencv/opencv#10117]
Hi,

I've posted this issue in the [help forums](http://answers.opencv.org/question/178208/using-cvcudasplit-ends-in-segfault/) as well.

When I use `cv::cuda::split` with an `std::vector<cv::cuda::GpuMat>` it appears to work fine.
My 3 channel float matrix is split as expected; however when I try the other function overload which uses a single `cv::cuda::GpuMat` I get a segmentation fault.

I'm basically trying to split a float matrix into a 3 channel BGR matrix:

    // mfloat has the float data
    cv::cuda::GpuMat mfloat; // <-- this has already been populated with data
    cv::cuda::GpuMat input_matrix;
    cv::cuda::split(mfloat, &input_matrix);

This SEGFAULTs with:

```
Thread 1 "test_computer_v" received signal SIGSEGV, Segmentation fault.
0x00007fffead6844d in cv::cuda::GpuMat::create(int, int, int) () from /usr/local/lib/libopencv_core.so.3.3
```

I've tried setting the matrix size and allocating it, although the documentation does not make it clear what is expected, by setting each row to contain a full-sized matrix `cv::cuda::GpuMat input_matrix(3, 224 * 224, CV_32FC1);` but the same error still persists. Same with `cv::cuda::GpuMat input_matrix(224 * 224, 3, CV_32FC1);`.

When I allocate and pass pointers (std::unique_ptr or a raw pointer) I then get a SEGFAULT from a different line:

    cv::cuda::GpuMat * input_matrix = new cv::cuda::GpuMat(224, 224, CV_32FC1);
    cv::cuda::split(mfloat, input_matrix);

The error:

```
Thread 1 "test_computer_v" received signal SIGSEGV, Segmentation fault.
0x00007fffead6833d in cv::cuda::GpuMat::release() () from /usr/local/lib/libopencv_core.so.3.3
```

Can somebody explain **how** is the version of `split` supposed to be called? 
How is `dst` to be allocated and sized?

    void cv::cuda::split(InputArray 	src,
                         GpuMat * 	dst,
                         Stream & 	stream = Stream::Null() 
                        )

Many thanks!

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

For 3 channel BGR matrix you should have 3 pre-allocated matrixes.
```.diff
-cv::cuda::GpuMat mfloat;
+cv::cuda::GpuMat mfloat[3];
```
or better to use API with `std::vector<cv::GpuMat>`.

**Comment by alalek** [comment]
No, you must pass pointer on three GpuMat's (one per channel), because this is expected by API of this 
function.
See similar `cv::split` [documentation](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga0547c7fed86152d7e9d0096029c8518a).
