### ISSUE TITLE
DNN_TARGET_OPENCL for MobileNet-SSD

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#10125]
##### System information (version)

- OpenCV => 3.3.1-dev
- Operating System / Platform => Ubuntu 16.04
- Compiler => /usr/bin/c++  (ver 5.4.0)

##### Detailed description
OpenCL target for MobileNet-SSD object detection model produces an assertion.

##### Steps to reproduce

Add
```cpp
net.setPreferableTarget(DNN_TARGET_OPENCL);
```
into [samples/dnn/ssd_mobilenet_object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_mobilenet_object_detection.cpp):

```
OpenCV Error: Assertion failed (u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive") in deallocate, file /home/dkurtaev/opencv/modules/core/src/ocl.cpp, line 3619
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/dkurtaev/opencv/modules/core/src/ocl.cpp:3619: error: (-215) u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive" in function deallocate
```

**Comment by 411506656** [comment]
Add to the previous note;

platform: centos
g++ (GCC): 4.8.5 20150623 (Red Hat 4.8.5-16)
opencv ver: 4.0.0-pre
