### ISSUE TITLE
Access violation when creating Ptr<> on Windows from Golang

### ISSUE THREAD

**Issue by deadprogram** [opencv/opencv#10129]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => MinGW-W64/Golang 1.9.2

##### Detailed description

I am the maintainer of GoCV, a wrapper for the Go programming language around the latest
OpenCV 3.3. Thanks very much for all of the work on OpenCV, and for helping us with our
language wrapper.

We have generally been very successful running GoCV on Linux, OS X, and on Windows using
our wrapper library. The way that GoCV works is it uses a C wrapper written around the 
OpenCV 3.3 C++ classes. This C wrapper is then called from Go using CGo (part of Go), 
which compiles the C/C++ code right into the same executable.

We have a test suite that exercises each of the wrappers that we have wrapped thus far.
This allows us to verify that the wrapper functions work as we expect with 98% text coverage.

We have a TravisCI build that runs the tests on Linux:

https://travis-ci.org/hybridgroup/gocv

We also have an Appveyor build for testing on Windows:

https://ci.appveyor.com/project/deadprogram/gocv/history

This setup has allowed us to recently discover some code that we added that works as 
expected on Linux, however causes an immediate "Access Violation" on Windows.

This is the test that triggers the failure:

https://github.com/hybridgroup/gocv/blob/master/video_nowindows_test.go#L11

In fact, when I try to instantiate any class that uses a Ptr<> such as any based 
on "Algorithm" then I get an immediate exit of the program with an access violation, 
with no further output other than:

```
exit status 3221225477
```
https://ci.appveyor.com/project/deadprogram/gocv/build/126#L146

In our code the BackgroundSubtractorMOG2 class triggers this problem. 
Our wrapper around BackgroundSubtractorKNN also has this same problem. 
And our SimpleBlobDetector class wrapper, same problem.

So each of these returns a Ptr<>. 

The way that GoCV handles Ptr<> works fine on Linux and OS X but appears 
to fail on Windows.

I am using MingW-W64 on Windows, which I know is not "officially" supported. However, this 
is required by the Go compiler's CGo toolchain under Windows.

Despite that the MingW-W64 compile/link settings for the Windows OpenCV build/install itself 
appear to be fine. I am able to test this, by compiling and running the CPP sample applications. 

I am able to run several different cpp samples without any apparent error.
The "cpp-example-bgfg_segm.exe" application runs correctly without any error. 
This sample also uses the same BackgroundSubtractorMOG2 class as the Go code that 
in our GoCV code results in the access violation.

So it would appear to be something related to the Windows compile/link configuration for our
project itself, or else how the Go runtime or CGo compiler works on Windows. 

Because as I mentioned originally, the exact same Go/C/C++ code works as expected in Linux
and on OS X.

How can I go about tracking this down in Windows?

Thank you very much for any help!

##### Steps to reproduce

- compile OpenCV 3.3 for Windows using MinGW-W64 as documented here:
https://github.com/hybridgroup/gocv#windows

- follow these instuctions to install/run GoCV:
https://github.com/hybridgroup/gocv#windows-1

- run the motion-detect sample from within the GoCV directory:
```
go run cmd\motion-detect\main.go 0
```

This should result in the following output:

```
C:\Users\ron\go\src\gocv.io\x\gocv>go run cmd\motion-detect\main.go 0
exit status 3221225477
```

**Comment by deadprogram** [comment]
What would be a proper C type to use in that case?

**Comment by alalek** [comment]
It is structure, so perhaps you should use pointer of `cv::Ptr`.

**Comment by deadprogram** [comment]
I feel like I should be using a static_cast to a void* and then back somehow, but not sure how to apply to a cv::Ptr.

**Comment by alalek** [comment]
> using a static_cast to a void*

Static casts exists, but you should keep `cv::Ptr` alive (or object would be destroyed). `cv::Ptr` is smart ptr implementation, like `std::shared_ptr`.

As I said above it should be pointer on cv::Ptr:
```
typedef cv::Ptr<cv::BackgroundSubtractor>* BackgroundSubtractor;
```

You already use this approach for cv::Mat::
```
typedef cv::Mat* Mat;
```

**Comment by deadprogram** [comment]
Thanks for all the quick responses and assistance @alalek 

So, if I change the typedef as you suggest to:

```
#ifdef __cplusplus
typedef cv::Ptr<cv::BackgroundSubtractorMOG2>* BackgroundSubtractorMOG2;
#else
typedef void* BackgroundSubtractorMOG2;
#endif
```

Then how should I return the Ptr, since this code:

```
BackgroundSubtractorMOG2 BackgroundSubtractorMOG2_Create() {
    return cv::createBackgroundSubtractorMOG2();
}

void BackgroundSubtractorMOG2_Apply(BackgroundSubtractorMOG2 b, Mat src, Mat dst) {
    b->apply(*src, *dst);
}
```

Now results in the following compiler errors:
```
video.cpp: In function ‘cv::Ptr<cv::BackgroundSubtractorMOG2>* BackgroundSubtractorMOG2_Create()’:
video.cpp:4:47: error: cannot convert ‘cv::Ptr<cv::BackgroundSubtractorMOG2>’ to ‘BackgroundSubtractorMOG2 {aka cv::Ptr<cv::BackgroundSubtractorMOG2>*}’ in return
     return cv::createBackgroundSubtractorMOG2();

video.cpp: In function ‘void BackgroundSubtractorMOG2_Apply(BackgroundSubtractorMOG2, Mat, Mat)’:
video.cpp:16:8: error: ‘struct cv::Ptr<cv::BackgroundSubtractorMOG2>’ has no member named ‘apply’
     b->apply(*src, *dst);
```

Thanks for helping out, it is greatly appreciated.

**Comment by alalek** [comment]
Definitely implementation should be changed too.

**Comment by deadprogram** [comment]
Sorry that I don't understand. Can you please show me what you mean?

**Comment by alalek** [comment]
I mean wrapper implementation should be changed too, to return `cv::Ptr<>*`. Like code [here](https://github.com/hybridgroup/gocv/blob/master/core.cpp#L5-L12):

```
BackgroundSubtractorMOG2 BackgroundSubtractorMOG2_Create() {
    return new cv::Ptr<cv::BackgroundSubtractor>(BackgroundSubtractorMOG2 cv::createBackgroundSubtractorMOG2());
}

void BackgroundSubtractorMOG2_Apply(BackgroundSubtractorMOG2 b, Mat src, Mat dst) {
    (*b)->apply(*src, *dst);
}
```

**Comment by deadprogram** [comment]
Aha, that explains it perfectly, thank you. Indeed, I was using it wrong. The usual question applies "how was it even working on Linux/OSX?". I suppose the smart Ptr reference counting rules saved me from myself, but Windows is perhaps somewhat less robust, or has different rules.

In any case, that was my problem. Thank you again for the assistance and the very quick response!
