### ISSUE TITLE
Horizontal breaking line on putText()

### ISSUE THREAD

**Issue by SuperCortex** [opencv/opencv#10127]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Linux (Ubuntu 16.04) 64 Bit
- Compiler => Eclipse/gcc

##### Detailed description
After calling **cv :: putText** (cv :: Mat, cv :: String, ....), there is horizontal line that strikes the displayed text string. This line appears ONLY if this text starts with the "2" symbol and only in Run mode (even if compiled in Debug configuration). During Debug steps this bug not appears.

##### Steps to reproduce

int main(int argc, char* argv[])
{

	uint FrameH = 1024, FrameW = 1280;
	cv::HersheyFonts cvFont = FONT_HERSHEY_SIMPLEX;
	cv::Scalar TextColor(128,255,128);

	cv::Mat Frame(FrameH, FrameW,CV_8UC3);

	while (1)
	{
		//Clear image
		Frame = cv::Scalar(0,0,0);

		cv::putText(Frame, "21", cv::Point(50,50), cvFont, 0.5, TextColor, 2); //Striked line blinks
		//cv::putText(Frame, "12", cv::Point(50,50), cvFont, 0.5, TextColor, 2); //No bugs

		imshow("MyVideo", Frame); //show the frames in "MyVideo" window

		if (waitKey(1) == 27)
			break;

	}
 	return 0;
}

**Comment by alalek** [comment]
> 3.2

Try latest master or 3.3.1.

**Comment by SuperCortex** [comment]
It's impossible now, we are under common project. Is it only version 3.2.0 bug?

**Comment by alalek** [comment]
We don't maintain already released versions.
Fix probably here: #7959

**Comment by SuperCortex** [comment]
Well, I'll try it later, thanx.

**Comment by LukeAI** [comment]
Is there some workaround? unfortunately I'm stuck with this version.
