### ISSUE TITLE
Multiple conditions with commas at CV_Assert

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#10168]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => /usr/bin/c++ (ver 5.4.0)

CV_Assert with multiple conditions defined as separate code lines.

##### Steps to reproduce

```cpp
if (true)
  CV_Assert(1 != 2);
else
  CV_Assert(1 == 2, 2 == 3);
```
produces
```
error: (-215) 2 == 3
```

**Comment by alalek** [comment]
Try to add more `{}`:
```
if (true) {
  CV_Assert(1 != 2);
} else {
  CV_Assert(1 == 2, 2 == 3);
}
```

**Comment by csukuangfj** [comment]
I think the modified version `CV_Assert` is not intuitive since it expands to multiple statements instead
of only one.

I would like to suggest wrapping it inside
```.cpp
do {....} while (0);
```

Refer to <https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/base.hpp#L443>
