### ISSUE TITLE
Build fails when option "opencv_dnn_BUILD_TORCH_IMPORTER" is disabled

### ISSUE THREAD

**Issue by cmastudios** [opencv/opencv#10161]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => OS X 10.13.1
- Compiler => Apple LLVM version 9.0.0 (clang-900.0.38)

##### Detailed description

Compiling OpenCV fails with the error below when the option opencv_dnn_BUILD_TORCH_IMPORTER is explicitly disabled. This is the only error: when the function is re-enabled, the build completes successfully.

##### Steps to reproduce

1. Download OpenCV 3.3.1 source code from opencv.org.
2. Configure build using CMake - set opencv_dnn_BUILD_TORCH_IMPORTER to OFF.
3. Run `make` in the build directory.

The error below is the output of `make`:
```
/Users/$USER/Downloads/opencv-3.3.1/modules/dnn/src/torch/torch_importer.cpp:1177:5: error: 
      unknown type name 'TorchImporter'
    TorchImporter importer(model, isBinary);
    ^
1 error generated.
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o] Error 1
```

**Comment by dkurt** [comment]
@cmastudios, fixed at https://github.com/opencv/opencv/pull/10061.
