### ISSUE TITLE
why haarcascade_mcs_nose.xml and haarcascade_mcs_mouth.xml in opencv-contrib using C++  is   Out of commission

### ISSUE THREAD

**Issue by h-acker** [opencv/opencv#10169]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by h-acker** [comment]
OpenCV => 3.1.1
Operating System=> windows 
Compiler=>VS2015

**Comment by sturkmen72** [comment]
could we close this
