### ISSUE TITLE
ml::ANN_MLP::load return non NULL ptr when file does not exist

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10166]
- OpenCV => 3.3.1-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

When I want to load an ANN_MLP file and file does not exist, there is two different behaviours.
First one : 
`Ptr<ml::ANN_MLP> y = Algorithm::load<ml::ANN_MLP>("nonexistfile.yml");
`
y is NULL

and 

`Ptr<ml::ANN_MLP> z = ml::ANN_MLP::load("nonexistfile.yml");`

z is not null : -		
```
z	{owner=0x000002c1913ddef0 {owned=0x000002c1913d8600 {layer_sizes={ size=0 } weights={ size=2 } f_param1=...} ...} ...}	cv::Ptr<cv::ml::ANN_MLP>
+		owner	0x000002c1913ddef0 {owned=0x000002c1913d8600 {layer_sizes={ size=0 } weights={ size=2 } f_param1=1.0000000000000000 ...} ...}	cv::detail::PtrOwner * {opencv_ml331d.dll!cv::detail::PtrOwnerImpl<cv::ml::ANN_MLPImpl,cv::DefaultDeleter<cv::ml::ANN_MLPImpl> >}
+		stored	0x000002c1913d8600 {layer_sizes={ size=0 } weights={ size=2 } f_param1=1.0000000000000000 ...}	cv::ml::ANN_MLP * {opencv_ml331d.dll!cv::ml::ANN_MLPImpl}
```
Is it expected behaviour ?

##### Steps to reproduce

    Ptr<ml::ANN_MLP> z = ml::ANN_MLP::load("nonexistfile.yml");
    Ptr<ml::ANN_MLP> y = Algorithm::load<ml::ANN_MLP>("nonexistfile.yml");
-->

**Comment by alalek** [comment]
@LaurentBerger Thank you for report! This should be fixed.
Moreover, I believe exception is more convenient here, because it contains description message of the error.

**Comment by LaurentBerger** [comment]
You mean insertCV_Assert(fs.isOpened()); [here ](https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L1332) and [here](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L3137) ( and same problem in [loadfromstring](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L3156)?

**Comment by alalek** [comment]
Yes, something like this (`loadfromstring()` reads from memory, only parse stage may fail).
