### ISSUE TITLE
PermissionError after using cv2.imread on certain files

### ISSUE THREAD

**Issue by orbancedric** [opencv/opencv#10162]
##### System information (version)
- OpenCV => 3.1.0
- Operating System / Platform => Windows 10 64 Bit
- Python 3.6

##### Detailed description

An image file is kept open after reading it in using cv2.imread, leading to file system errors when manipulating the file. This happens rarely; I've seen it a handful of times in a couple hundred thousand images. As far as I can tell, the images that trigger the bug are not corrupt/invalid.

##### Steps to reproduce
 [Example image that triggers the bug.](https://pbs.twimg.com/media/B2QjKr6IAAAX0kf.jpg)
```
#.py
import os
import cv2

cv2.imread("B2QjKr6IAAAX0kf.jpg")
os.rename("./B2QjKr6IAAAX0kf.jpg", "./sub/B2QjKr6IAAAX0kf.jpg")
```

Running the above leads to:

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process`

**Comment by alalek** [comment]
> 3.1.0

Try latest master.

**Comment by orbancedric** [comment]
That fixed it.

**Comment by KolGuy80** [comment]
I'm facing the same issue. And couldn't follow what you mean by "Try latest master"!

I've already pip ugraded opencv to it's latest version.
