### ISSUE TITLE
cv::dnn::readNetFromDarknet() error in reading configutaion files

### ISSUE THREAD

**Issue by DGKmaster** [opencv/opencv#10160]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Ubuntu MATE 16.04.3 LTS (Xenial Xerus) (on Oracle VM for Windows, version 5.1.24 r117012 (Qt5.6.2)) 
- Compiler => GCC (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

##### Detailed description
I use sample code to load YOLO model and classify objects and it failes on reading net configuration.

Exact output:
OpenCV Error: Parsing error (Failed to parse NetParameter file: ~/Documents/HunterCV/pyway/cfg/yolo.cfg) in ReadNetParamsFromCfgFileOrDie, file /home/dgk/Pictures/opencv/modules/dnn/src/darknet/darknet_io.cpp, line 612
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/dgk/Pictures/opencv/modules/dnn/src/darknet/darknet_io.cpp:612: error: (-212) Failed to parse NetParameter file: ~/Documents/HunterCV/pyway/cfg/yolo.cfg in function ReadNetParamsFromCfgFileOrDie

##### Steps to reproduce
1. Download sample for YOLO use
https://github.com/opencv/opencv/blob/master/samples/dnn/yolo_object_detection.cpp
2. Download darknet from official site and install it
https://pjreddie.com/darknet/install/
3. Download YOLO model and its configuration
4. Set yolo.cfg as net cfg
5. Set yolo.weights as net model

**Comment by dkurt** [comment]
@DGKmaster, please try to use absolute paths to files.

**Comment by DGKmaster** [comment]
@dkurt Thank you! I tried this before but in incorrect way I think.

**Comment by jbeale1** [comment]
I have this "ReadNetParamsFromCfgFileOrDie" problem, even with an absolute path to the .cfg file, maybe it's the wrong file?

 ./example_dnn-yolo_object_detection --cfg /home/pi/OCV/darknet/cfg/tiny-yolo.cfg --model /home/pi/dn/tiny-yolo.weights --class_names /home/pi/OCV/darknet/data/coco.names --source space_shuttle.jpg
OpenCV Error: Parsing error (Failed to parse NetParameter file: true) in ReadNetParamsFromCfgFileOrDie, file /home/pi/OCV/opencv-3.4.0/modules/dnn/src/darknet/darknet_io.cpp, line 612
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/pi/OCV/opencv-3.4.0/modules/dnn/src/darknet/darknet_io.cpp:612: error: (-212) Failed to parse NetParameter file: true in function ReadNetParamsFromCfgFileOrDie

ll /home/pi/OCV/darknet/cfg/tiny-yolo.cfg
-rw-r--r-- 1 pi pi 1488 Feb 24 16:49 /home/pi/OCV/darknet/cfg/tiny-yolo.cfg

**Comment by dkurt** [comment]
@jbeale1, try the same without spaces between command line keys and values
```
./example_dnn-yolo_object_detection --cfg=/home/pi/OCV/darknet/cfg/tiny-yolo.cfg --model=/home/pi/dn/tiny-yolo.weights --class_names=/home/pi/OCV/darknet/data/coco.names --source=space_shuttle.jpg
```
Otherwise they are interpreted as boolean flags: 

what(): /home/pi/OCV/opencv-3.4.0/modules/dnn/src/darknet/darknet_io.cpp:612: error: (-212) Failed to parse NetParameter file: **true** in function ReadNetParamsFromCfgFileOrDie

**Comment by kakri** [comment]
> I have this "ReadNetParamsFromCfgFileOrDie" problem, even with an absolute path to the .cfg file, maybe it's the wrong file?
> 
> ./example_dnn-yolo_object_detection --cfg /home/pi/OCV/darknet/cfg/tiny-yolo.cfg --model /home/pi/dn/tiny-yolo.weights --class_names /home/pi/OCV/darknet/data/coco.names --source space_shuttle.jpg
> OpenCV Error: Parsing error (Failed to parse NetParameter file: true) in ReadNetParamsFromCfgFileOrDie, file /home/pi/OCV/opencv-3.4.0/modules/dnn/src/darknet/darknet_io.cpp, line 612
> terminate called after throwing an instance of 'cv::Exception'
> what(): /home/pi/OCV/opencv-3.4.0/modules/dnn/src/darknet/darknet_io.cpp:612: error: (-212) Failed to parse NetParameter file: true in function ReadNetParamsFromCfgFileOrDie
> 
> ll /home/pi/OCV/darknet/cfg/tiny-yolo.cfg
> -rw-r--r-- 1 pi pi 1488 Feb 24 16:49 /home/pi/OCV/darknet/cfg/tiny-yolo.cfg

Did you find the solution to your problem? i am also facing the same problem. Can you help me out in solving the problem.

**Comment by Vellimakhlooq** [comment]
> @DGKmaster, please try to use absolute paths to files.

kindly explain what is absolute path how to use it am aslo getting this error

**Comment by DGKmaster** [comment]
@Vellimakhlooq you need set path from root catalogue, not from current directory:
**Wrong way:**
`_net_cfg_path = "cfg/yolo.cfg";`
`_net_cfg_path = "yolo.cfg";`

**Right way:**
`_net_cfg_path = "/home/user/yolo/cfg/yolo.cfg";`

**Comment by UsmanMasood21** [comment]
hello,
I was hoping I could get some help regarding the same issue. I set absolute paths to the yolov3.cfg and yolov3.weights in the python script. However, I am still getting the following error:

`cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolo//home/usman/catkin_ws/src/yolo-object-detection/yolo-coco/yolov3.cfg in function 'readNetFromDarknet'`

I would be really grateful for any help. 

Thanks

**Comment by DGKmaster** [comment]
@UsmanMasood21 I think that your problem is quite different and can have multiple causes:
1. OpenCV 4 can be incompatible with yolo3.
2. Python script uses not right function.
3. Path "yolo//home/usman/catkin_ws/src/yolo-object-detection/yolo-coco/yolov3.cfg" I think possibly is incorrect: what is "yolo/" in the beginning?

**Comment by dkurt** [comment]
@DGKmaster, 

> OpenCV 4 can be incompatible with yolo3.

What do you mean by that?

**Comment by TWhidden** [comment]
Not sure if this helps, but make sure you use Linux line endings, not windows.  That was a gotcha while developing for this.  I use opencv 4 with yolo3 no problem.

**Comment by MrAhmadRaza** [comment]
> hello,
> I was hoping I could get some help regarding the same issue. I set absolute paths to the yolov3.cfg and yolov3.weights in the python script. However, I am still getting the following error:
> 
> `cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolo//home/usman/catkin_ws/src/yolo-object-detection/yolo-coco/yolov3.cfg in function 'readNetFromDarknet'`
> 
> I would be really grateful for any help.
> 
> Thanks


Try with some other .weight file. it is possible that your weight file is broken.

**Comment by Glitch0000** [comment]
I think you should add the address but make sure to double the slashes,
instead of lets say"E:\YOLO1\cfg"  you should write "E:\\YOLO1\\cfg"

**Comment by fatima598** [comment]
> hello,
> I was hoping I could get some help regarding the same issue. I set absolute paths to the yolov3.cfg and yolov3.weights in the python script. However, I am still getting the following error:
> 
> `cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolo//home/usman/catkin_ws/src/yolo-object-detection/yolo-coco/yolov3.cfg in function 'readNetFromDarknet'`
> 
> I would be really grateful for any help.
> 
> Thanks

If you solve this peoblem PLEASE HELP ME

**Comment by MrAhmadRaza** [comment]
My .config file was corrupted  I download it from another source and it
works fine.

**Comment by fatima598** [comment]
thank you so much 😊

**Comment by MrAhmadRaza** [comment]
My pleasure... :)

**Comment by fatima598** [comment]
Thank you very much, the problem is solved :)

**Comment by fatima598** [comment]
I have another problem  😞  can you help me
when i run this code :

import cv2
import numpy as np

# Load Yolo
net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")
classes = []
with open ("coco.names", "r") as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getlayerNames()
outputlayers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

    # Loading image
img = cv2.imread("room_ser.jpg")
img = cv2.resize(img, None, fx=0.4, fy=0.4)

cv2.imshow("Image", img)
cv2.waitkey(0)
cv2.destroyAllWindows()

i have this error :

C:\Users\HP\PycharmProjects\PUPI\venv\Scripts\python.exe
C:/Users/HP/PycharmProjects/PUPI/RIMI.py
Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/PUPI/RIMI.py", line 9, in <module>
    layer_names = net.getlayerNames()
AttributeError: 'cv2.dnn_Net' object has no attribute 'getlayerNames'

Process finished with exit code 1

**Comment by MrAhmadRaza** [comment]
I think the function name  is getLayerNames().

**Comment by fatima598** [comment]
Hello ahmad
You know how convert code for yolo object detection in image to yolo object
detection in video ?

**Comment by MrAhmadRaza** [comment]
Every frame of video is an image itself, So, iterate over frames of video
and apply detection on each frame.
There is a simple two lines of code to open a video and read its frames
using opencv. Do search for it.
