### ISSUE TITLE
when run Mat output = net.forward() with  OpenCV =3.3.1 load tensorflow model error  0x000007FED45C4A29 (igdrcl64.dll)处(位于 MobeileNet_SSD.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000003A47000 时发生访问冲突。

### ISSUE THREAD

**Issue by Suning-liuhaiyang** [opencv/opencv#10165]
when run Mat output = net.forward() with  OpenCV =3.3.1 load tensorflow model error  0x000007FED45C4A29 (igdrcl64.dll)处(位于 MobeileNet_SSD.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000003A47000 时发生访问冲突。

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Try to updrade your display driver or disabled OpenCL in OpenCV.
Also it is good practice to run OpenCV tests before filling issues.
