### ISSUE TITLE
matrix division: div_SIMD has incorrect division by zero handling in template specialization for double

### ISSUE THREAD

**Issue by romanc** [opencv/opencv#10181]
The specialization for double precision floating point types of `div_SIMD` in `artihm_simd.hpp` [1] has an inconsistent handling of the special case division by zero. It is supposed to check the denominator to not be zero, but the nominator is checked instead.

https://github.com/opencv/opencv/blob/bc547c42908c5932a6cc95f2bfdc08a1dfe172e0/modules/core/src/arithm_simd.hpp#L1727
https://github.com/opencv/opencv/blob/bc547c42908c5932a6cc95f2bfdc08a1dfe172e0/modules/core/src/arithm_simd.hpp#L1728

**Comment by romanc** [comment]
@alalek I only added a PR for the master branch. Can you port this back to the 2.4 branch or do I have to add another PR for that?

**Comment by alalek** [comment]
@romanc Thank you!
PR for the master branch is enough. There is no similar SIMD optimization in the 2.4 branch.

**Comment by romanc** [comment]
@alalek I have also indication that matrix division for 8SC3 and 8UC3 (mapping to `schar` and `uchar`) might be inconsistent when it comes to division by zero. Looking at code, I could not find an error. Are there testcases in the testsuite that will run matrix division with, say, an all-0-matrix for all possible datatypes in OpenCV? This helps me to rule out another bug in OpenCV.

**Comment by alalek** [comment]
We have no special tests for division by zero.

> all-0-matrix for all possible datatypes

Actually the hard problem here is optimization backends, like IPP, HAL, OpenCL (probably not run in your case), SIMD and generic non-optimized implementation.

BTW, perhaps your patch resolves this issue #8413 too

**Comment by romanc** [comment]
> Actually the hard problem here is optimization backends, like IPP, HAL, OpenCL (probably not run in your case), SIMD and generic non-optimized implementation.

I see, this can get pretty ugly, if you want to check all possible versions of the code with that many optimization backends. I am most probably running the SIMD version of the code. It's also the one I check when looking for another bug in these cases. If I have time, I will try to run the generic non-optimized version to check, if there is a difference. Anyway, thanks for the quick answer. If I find something, I will open another issue. I don't want to clutter this issue any more than necessary.

> BTW, perhaps your patch resolves this issue #8413 too

Indeed, this looks very similar to the behavior I get ;)
