### ISSUE TITLE
I use VS2013 and Cmake the X64 lib, I build .\samples\dnn yolo_object_detection.cpp to detect objects,but it cant' open the video and image,I don't know why .... 

### ISSUE THREAD

**Issue by Silencesss** [opencv/opencv#10196]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
Please stop your spam. 
This tracker is for issues and bugs that needs fix in OpenCV. OpenCV developers would not answer on usage questions here.
