### ISSUE TITLE
A typo in the get_duration_sec method is possible

### ISSUE THREAD

**Issue by Landgraf132** [opencv/opencv#10209]
- OpenCV => master

##### Detailed description

A typo in the get_duration_sec method is possible - two times the same condition is written.

https://github.com/opencv/opencv/blob/3.3.1/modules/videoio/src/cap_ffmpeg_impl.hpp#L1103
 
 
```
  double CvCapture_FFMPEG::get_duration_sec() const
{
    double sec = (double)ic->duration / (double)AV_TIME_BASE;

   if (sec < eps_zero)  
    {
        sec = (double)ic->streams[video_stream]->duration * r2d(ic->streams[video_stream]->time_base);
    }

    if (sec < eps_zero) // repeat?
    {
        sec = (double)ic->streams[video_stream]->duration * r2d(ic->streams[video_stream]->time_base);
    } 

    return sec;
}
```

**Comment by Riyuzakii** [comment]
@Landgraf132 I'm a newbie, and I would like to get the assignment of this issue. I'll just remove the extra set of if statement, that's all there is to this issue, right?

**Comment by seiko2plus** [comment]
@Riyuzakii I think the extra set of if statement supposed to return the product of AVStream::duration, AVCodecContext::time_base
```
sec = (double)ic->streams[video_stream]->duration * r2d(ic->streams[video_stream]->codec->time_base);
```

**Comment by Landgraf132** [comment]
@Riyuzakii on line 1136 there is a similar point, I hope this helps
https://github.com/opencv/opencv/blob/3.3.1/modules/videoio/src/cap_ffmpeg_impl.hpp#L1136

**Comment by Riyuzakii** [comment]
@seiko2plus But why has it been repeated? Does it not return the product in the first instance itself?
@Landgraf132  the one on line 1136 doesn't seem to be a repetition, there's a difference between line 1139 and 1145. Are you talking about something else?

**Comment by kevin-coder** [comment]
I think Landgraf132 is talking about following piece of code:
#if LIBAVFORMAT_BUILD >= CALC_FFMPEG_VERSION(52, 111, 0)
    **if (fps < eps_zero)**
    {
        fps = r2d(ic->streams[video_stream]->avg_frame_rate);
    }
#endif

    **if (fps < eps_zero)**
    {
        fps = 1.0 / r2d(ic->streams[video_stream]->codec->time_base);
    }
#endif

**Comment by Riyuzakii** [comment]
@kevin-coder thanks. they are both calculating fps but with different methods, so we can remove one. 
Also I asked this above but no one answered so i'll ask it again: this particular change in code doesn't change any functionality. But if in some other case my addition did affect some functionality, how would I check if the whole thing is working properly?

**Comment by Landgraf132** [comment]
@Riyuzakii In my opinion, the mistake is that the second repetition was forgotten to change. It is necessary to find a file that will not contain a time_base in the stream, but it will contain in the codec.

**Comment by alalek** [comment]
There is no forgotten change in `get_duration_sec()` (at least this change is not needed at all for last 7 years).
Lets just remove the second duplicated code block: https://github.com/opencv/opencv/blame/3.3.1/modules/videoio/src/cap_ffmpeg_impl.hpp#L1111-L1115
