### ISSUE TITLE
solvePnPRansac bug ? 

### ISSUE THREAD

**Issue by liujiabin20810** [opencv/opencv#10202]
##### System information (version)

- OpenCV => :3.1:
- Operating System / Platform => :Windows 8 64 Bit:
- Compiler => 🆚 2013:

##### Detailed description

when I used solvePnPRansac , I found some unusual problem.  I have image points in 2d , denoted by V2d , and  corresponding  scence points in 3d, denoted by V3d , camera matrix K and the true P.  So, V2d = K*P*V3d.    But the solvePnPRansac result  R&T is not same with P .

Here we go!

![solvepnpransac](https://user-images.githubusercontent.com/5511723/33427634-ed343fd4-d600-11e7-881b-cef8d8d839fe.jpg)

When using  points  by random creating , the solvePnPRansac can give the correct answer. the result  R matrinx & T vector is the same with I used before.
When Load my own data , the result 's inliers is only 165 ,while  the data size is 654.  And the re-projection mean error is larger than 400.  To prove the true P matrix I have and the relation between 2d and 3d points , I also calculated the re-projection mean error with the true P matrix  and  the result is just 
0.709 .

Anyone Knows is it a bug in the old version 3,1.0 ? 

##### Steps to reproduce
Here is the code  and the datas.
```.cpp
 // C++ code example
#include <opencv2/core/core.hpp>
#include <opencv2/calib3d/calib3d.hpp>

#include <iostream>
#include <algorithm>
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <fstream>
#include <stdlib.h>

#ifdef _DEBUG
	#pragma comment(lib,"opencv_world310d.lib")
#else
	#pragma comment(lib,"opencv_world310.lib")

#endif // _DEBUG


using namespace std;
using namespace cv;

//for test
const double uc = 320;
const double vc = 240;
const double fu = 800;
const double fv = 800;
const int n = 200;
const double noise = 3.0;

double rand(double min, double max)
{
	return min + (max - min) * double(rand()) / RAND_MAX;
}

void random_pose(double R[3][3], double t[3])
{
	const double range = 1;

	double phi = rand(0, range * 3.14159 * 2);
	double theta = rand(0, range * 3.14159);
	double psi = rand(0, range * 3.14159 * 2);

	R[0][0] = cos(psi) * cos(phi) - cos(theta) * sin(phi) * sin(psi);
	R[0][1] = cos(psi) * sin(phi) + cos(theta) * cos(phi) * sin(psi);
	R[0][2] = sin(psi) * sin(theta);

	R[1][0] = -sin(psi) * cos(phi) - cos(theta) * sin(phi) * cos(psi);
	R[1][1] = -sin(psi) * sin(phi) + cos(theta) * cos(phi) * cos(psi);
	R[1][2] = cos(psi) * sin(theta);

	R[2][0] = sin(theta) * sin(phi);
	R[2][1] = -sin(theta) * cos(phi);
	R[2][2] = cos(theta);

	t[0] = 0.0f;
	t[1] = 0.0f;
	t[2] = 6.0f;
}

void random_point(double & Xw, double & Yw, double & Zw)
{
	double theta = rand(0, 3.14159), phi = rand(0, 2 * 3.14159), R = rand(0, +20);

	Xw = sin(theta) * sin(phi) * R;
	Yw = -sin(theta) * cos(phi) * R;
	Zw = cos(theta) * R;
}

void project_with_noise(double R[3][3], double t[3],
	double Xw, double Yw, double Zw,
	double & u, double & v)
{

	double Xc = R[0][0] * Xw + R[0][1] * Yw + R[0][2] * Zw + t[0];
	double Yc = R[1][0] * Xw + R[1][1] * Yw + R[1][2] * Zw + t[1];
	double Zc = R[2][0] * Xw + R[2][1] * Yw + R[2][2] * Zw + t[2];

	double nu = rand(-noise, +noise);
	double nv = rand(-noise, +noise);
	u = uc + fu * Xc / Zc + nu;
	v = vc + fv* Yc / Zc + nv;
}

int main()
{
	std::cout << "================= Create matched 2d-3d points =======================" << std::endl;
	
	std::vector<cv::Point3f> list_points3d(n);
	std::vector<cv::Point2f> list_points2d(n);
	cv::Mat points_3d(n, 3, CV_64FC1);
	cv::Mat points_2d(n, 2, CV_64FC1);

	cv::Matx33d K;
	K(0, 0) = fu;   K(0, 1) = 0.0;  K(0, 2) = uc;
	K(1, 0) = 0.0;  K(1, 1) = fu;   K(1, 2) = vc;
	K(2, 0) = 0.0;  K(2, 1) = 0.0;  K(2, 2) = 1.0;

	srand(time(0));
	double R_true[3][3], t_true[3];
	random_pose(R_true, t_true);
	int i = 0 ;
	while ( i < n) {
		double Xw, Yw, Zw, u, v;
		random_point(Xw, Yw, Zw);
		project_with_noise(R_true, t_true, Xw, Yw, Zw, u, v);

		if(u < 0 || u > 640 || v <0 || v > 480)
			continue;

		points_2d.ptr<double>(i)[0] = u;
		points_2d.ptr<double>(i)[1] = v;
		points_3d.ptr<double>(i)[0] = Xw;
		points_3d.ptr<double>(i)[1] = Yw;
		points_3d.ptr<double>(i)[2] = Zw;

		list_points2d[i] = cv::Point2f(u, v);
		list_points3d[i] = cv::Point3f(Xw, Yw, Zw);
		i++;
	}

	std::cout<<"True R:"<<std::endl;
	double *R_ptr = R_true[0];
	for(int i =0; i < 9 ;i++)
	{
		std::cout<<*R_ptr<<" ";
		if(i > 0 && i % 3 == 0)
			std::cout<<endl;
		R_ptr++;
	}
	std::cout<<std::endl;


	std::cout<<"True T:"<<std::endl;
	std::cout<<t_true[0]<<" "<<t_true[1]<<" "<<t_true[2]<<std::endl;

	cv::Mat distCoeffs = cv::Mat::zeros(1, 4, CV_64FC1);
	cv::Mat_<double> Rmat ;
	cv::Mat_<double> Rvec ;
	cv::Mat_<double> Tvec ;
	
	cv::Mat inliers;
	std::cout<<list_points3d[0]<< " "<<list_points2d[0]<<std::endl;
	std::cout<<list_points3d[100]<< " "<<list_points2d[100]<<std::endl;
	std::cout<< cv::norm(list_points3d[0])<<" "<<cv::norm(list_points3d[100])<< std::endl;

	//use std::vector<cv::Point3f> and std::vector<cv::Point2f> then it works. 
	cv::solvePnPRansac(list_points3d, list_points2d, K, distCoeffs, Rvec, Tvec, false, 4000, 10.0, 0.99, inliers, CV_P3P);

	//use cv::mat type then it report error. while the the OpenCV function notes say it should be okay.
	//cv::solvePnPRansac(points_3d, points_2d, K, distCoeffs, Rvec, Tvec, false, 4000, 10.0, 0.99, inliers, CV_P3P);
	cv::Rodrigues(Rvec, Rmat);

	std::cout << "solvePnPRansac inlier: " << inliers.rows << std::endl;
	std::cout << "R: " << std::endl << Rmat << std::endl;
	std::cout << "T: " << std::endl << Tvec << std::endl;


	//////////////////////////////////////////////////////////////////////////
	
	//New data
	FileStorage fs("point2d3d.txt",FileStorage::READ);

	if(!fs.isOpened())
		return -1;

	Mat Ks,R,T;
	fs["cam"] >> Ks;
	fs["R"] >> R;
	fs["T"] >> T;


	std::cout<<"================= Load matched 2d-3d points ======================="<<std::endl;
	
	std::cout << "Ks: " << std::endl<< Ks << std::endl;
	Mat point2d,point3d;

	fs["point_2d"] >> point2d;
	fs["point_3d"] >> point3d;

	std::vector<Point2f> vec_2d;
	std::vector<Point3f> vec_3d;

	int n = point3d.cols;
	vec_2d.resize(n);
	vec_3d.resize(n);

	cv::MatIterator_<float> iter = point2d.begin<float>();
	i = 0;
	for (; iter != point2d.end<float>(); iter++)
	{
		vec_2d[i].x = *iter;
		iter++;
		vec_2d[i].y = *iter;
		i++;
	}

	iter = point3d.begin<float>();
	i = 0;
	for (; iter != point3d.end<float>(); iter++)
	{
		vec_3d[i].x = *iter;
		iter++;
		vec_3d[i].y = *iter;
		iter++;
		vec_3d[i].z = *iter;
		i++;
	}
	

	std::cout<<std::endl<<"Calculate relationship between 2d and 3d:"<<std::endl;
	std::vector<Point2f> proj_point;
	projectPoints(vec_3d,R,T,Ks,Mat(),proj_point);
	
	float reprj_err = 0.0; 
	for(int i = 0; i < n; i++)
		reprj_err += norm(proj_point[i] - vec_2d[i]);

	reprj_err /= n;

	std::cout<<"3d re_project to 2d: "<<proj_point[0]<<" "<<proj_point[100]<<std::endl;
	std::cout<<"2D point: " <<vec_2d[0]<<" "<<vec_2d[100]<<std::endl;

	std::cout<< "Init project error: "<<reprj_err<<std::endl;

	cv::Mat _distCoeffs = cv::Mat::zeros(4, 1, CV_64FC1);

	cv::Mat rVec = cv::Mat::zeros(3, 1, CV_64FC1);
	cv::Mat tVec = cv::Mat::zeros(3, 1, CV_64FC1);
	cv::Mat inlier;
	cv::solvePnPRansac(vec_3d, vec_2d, Ks, _distCoeffs, rVec, tVec, false, 500, 2.0, 0.95, inlier, CV_ITERATIVE);

	cv::Rodrigues(rVec, Rmat);

	std::cout << "solvePnPRansac inlier: " << inlier.rows << std::endl;
	std::cout<<"solvePnP result: "<<std::endl;
	std::cout << "R: " << std::endl << rVec.t() << std::endl;
	std::cout << "T: " << std::endl << tVec.t() << std::endl;

	std::cout<<"true R & T"<<std::endl;
	std::cout << "R: " << std::endl << R.t() << std::endl;
	std::cout << "T: " << std::endl << T << std::endl;

	proj_point.clear();
	projectPoints(vec_3d, Rmat, tVec, Ks, _distCoeffs, proj_point);
	reprj_err = 0.0;
	for (int i = 0; i < n; i++)
		reprj_err += norm(proj_point[i] - vec_2d[i]);

	reprj_err /= n;

	std::cout << "solvePnPRansac : project error: " << reprj_err << std::endl;

	return 0;
}


```

[point2d3d.txt](https://github.com/opencv/opencv/files/1517405/point2d3d.txt)

**Comment by alalek** [comment]
> 3.1

Try latest master - we doesn't maintain/fix previous releases.

**Comment by liujiabin20810** [comment]
@alalek  Thank you at first, I have got the master both 2.4.13 and  3.3.1. I have no VS2015, to save my time , I found the the epnp source code epnp.h & epnp.cpp . Using EPNP method like this:
`//epnp
	{
		cv::Mat undistortedPoints;
		cv::undistortPoints(list_points2d, undistortedPoints, K, distCoeffs);
		cv::Mat cameraMatrix = cv::Mat_<double>(K);
		epnp PnP(cameraMatrix, points_3d, undistortedPoints);

		Mat R;
		PnP.compute_pose(R, Tvec);
		Rodrigues(R, Rvec);
	}
`
The re-projection error also is not correct.
![epnp](https://user-images.githubusercontent.com/5511723/33473801-cfac6da8-d6b2-11e7-87e5-5ac52552cee3.jpg)

Beside, the image points add some noise.(rand(-noise, +noise) ，noise = 1.0 )

**Comment by liujiabin20810** [comment]
Test the usage of epnp with random 2d&3d points  , It is correct!

**Comment by alalek** [comment]
`rand()` - avoid using this to have reproducible results across different runtimes (MSVC / glibc) and in multi-threaded programs. Use `cv::RNG` instead.

There is no sense to check re-projecttion error with outliers. You should use "inliers" points only.

BTW, Please avoid posting screenshots with tests - just copy this text from console.

**Comment by liujiabin20810** [comment]
Thanks,  I 'll try the cv::RNG. 

But my data was calculated with traingulation , There is no sense exist outliers, 

With 2d image points pair, camera matrix and projection matrx P , I get the 3d points using  method triangulatePoints.

With the same 2d points , 3d points and camera matrix, why the projection matrix was different  by using
solvePnP?

**Comment by alalek** [comment]
> With 2d image points pair

Outliers may be here.


> projection matrix was different

It is possible in some special cases, like all points are on the same line.

**Comment by liujiabin20810** [comment]
At last , I solved  the problem with another  method.  This is the workflow.
1 . Solve for a 3x4 projection matrix P using RANSAC 
2 . Compute an RQ factorization of P. 
3.  fix up the intrinsic matrix  as the intrinsics  have a certain form
4 . find inliers and outliners.

Here is the console output: 
================= Load matched 2d-3d points =======================
True R:
[0.9783248866332616, 0.02990334382278402, 0.2049053591837762;
  -0.0264223837460927, 0.9994566607307608, -0.01970383105112333;
  -0.2053832364902019, 0.01386266024734647, 0.9785834419300566]
True T:
0.959017 -0.0873588 -0.269547
re_projection err:1.03154
[FindAndVerifyCamera] find projection matrix
[FindAndVerifyCamera] Compute an RQ factorization of the projection matr
[FindAndVerifyCamera] Checking consistency...

Solved result:
K: [895.1813350159595, 0.3657001706657138, 511.7925217590075;
  0, 894.8536985322917, 384.1383971810177;
  0, 0, 1]
R: [0.9782608434671413, 0.02961364834169552, 0.2052529024663274;
  -0.02604491565554026, 0.9994593324106021, -0.02006751668366635;
  -0.2057362012564954, 0.01428547126446396, 0.978503214508414]
T: [0.9594470566179238, -0.08810442234440984, -0.265226815467418]

**Comment by catree** [comment]
@liujiabin20810 

With OpenCV 3.3 at fc9e031, the behaviour should be correct:

> ================= Create matched 2d-3d points =======================
> True R:
> 0.229762 0.972209 -0.0449278 -0.969873
> 0.232562 0.0725354 0.080968
> 0.0269083 0.996353
> True T:
> 0 0 6
> [1.30727, 1.21924, -1.58669] [593.353, 44.0716]
> [2.44018, 0.734239, 2.95916] [422.194, 68.1852]
> 2.39021 3.90515
> solvePnPRansac inlier: 196
> R:
> [0.2320832211601539, 0.9716634127278337, -0.04480614714552697;
>  -0.9692905319554771, 0.2348763566562143, 0.07286262241623585;
>  0.0813218489546029, 0.02651998208902717, 0.9963350076317716]
> T:
> [0.003554840334739406;
>  0.003766690257088368;
>  6.012312523844869]
> ================= Load matched 2d-3d points =======================
> Ks:
> [896.0000000000001, 0, 512;
>  0, 896.0000000000001, 384;
>  0, 0, 1]
> 
> Calculate relationship between 2d and 3d:
> 3d re_project to 2d: [535.291, 31.4273] [401.047, 540.063]
> 2D point: [535.601, 32.8681] [401.059, 540.324]
> Init project error: 0.709259
> solvePnPRansac inlier: 101
> solvePnP result:
> R:
> [0.01453536661544652, 0.2076613672535027, -0.02848514561203301]
> T:
> [0.9619885684772798, -0.08207602490571878, -0.2789826354243608]
> true R & T
> R:
> [0.01690637707514779, 0.2066493529638988, -0.02836948255461208]
> T:
> [0.9590167124000095, -0.08735878211059593, -0.26954663515917]
> solvePnPRansac : project error: 0.425882

**Comment by liujiabin20810** [comment]
@catree Thank you for your help.
