### ISSUE TITLE
Error Compiling on CentOS-- “recompile with -fPIC”

### ISSUE THREAD

**Issue by davenso** [opencv/opencv#10206]
I get the following error when installing on CentOS 7. I have tried to add fPIC in cmake-gui (as suggested be the error below) but problem persists. In cmake-gui, I created a new name-value entry: CXX_FLAG -fPIC -- not exactly sure if this would be the right way to do it.

`make -j
`
```
Linking CXX shared library ../../lib/libopencv_java331.so
/usr/bin/ld: CMakeFiles/opencv_java.dir/generator/src/cpp/listconverters.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/opencv_java.dir/generator/src/cpp/listconverters.cpp.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_java331.so] Error 1
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by davenso** [comment]
OK. Here's what worked for me. 

```
export JAVA_HOME=/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64
mkdir build
cd build
cmake -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=. ..
make -j
```

I;m closing this issue now.

**Comment by alalek** [comment]
> CXX_FLAG

Should be CMAKE_CXX_FLAGS

> -D CMAKE_INSTALL_PREFIX=.

It is very bad practice to write directly into build directory. Consider to use `-D CMAKE_INSTALL_PREFIX=$(pwd)/install` instead.
