### ISSUE TITLE
Very large image not supported (area > 2^32)

### ISSUE THREAD

**Issue by FlorentTomi** [opencv/opencv#10211]
- OpenCV => 3.3.1
- Operating system => Windows 10 Pro (64bit)

**Related forum link**
[http://answers.opencv.org/question/178840/very-very-large-image-causes-issues-with-function-int-type-related/](http://answers.opencv.org/question/178840/very-very-large-image-causes-issues-with-function-int-type-related/)

**Detailed description**
Large images with an area greater than 2^32 cause crashes or do not work in some functions.
A simple example is the cv::threshold method with Triangle method flag:
The operation `size.width *= size.height;` is done (in file imgproc/src/thresh.cpp, line 1099), but in the case of large images, this overflows the "small" integer `int`.

Moreover, images with area greater than 2^30 cannot be opened (see imgcodecs/src/loadsave.cpp, line 65). As a workaround, I just modified the mentioned line with `#define CV_IO_MAX_IMAGE_PIXELS((uint64)1 << 40`, but this can't be a long term fix.

**Suggestions**
Maybe using other types (like int64 or size_t) for size-related (or maybe index-related) code may be a good idea.
Maybe this can be activated via a preprocessor directive.

**Comment by FlorentTomi** [comment]
I'm planning to "fix" this issue for my job (as it is an urgent matter).
What should be the good "OpenCV-way" of doing this ?

**Comment by kinchungwong** [comment]
It will be impossible to fix across the entire OpenCV library.

OpenCV can be seen as having several layers of "business value".

Among them, one of the layer is the definition of `cv::Mat` and `cv::Mat_<T>` (and also the related `cv::Matx_<T, M, N>`). This specifies a common multi-dimensional array type for in-memory objects, and is used for all communication purposes between the API functions of OpenCV.

Another of the layer is the vast collection of image processing functions. All of them operate on `cv::Mat` or `cv::Mat_<T>`.

The issue of assuming that memory address operations don't involve offsets (sizes, lengths, differences) more than 32-bit affects all layers. So, even if you fix the issue in `cv::Mat_<T>` and `cv::Mat`, all of the image processing functions will still fail. Therefore you will have to fix the image processing functions one by one. 

Thus, if it is a job necessity, then the first priority is to identify a minimum subset of OpenCV API that needs to be fixed, and then reimplement those functionalities by taking the code from OpenCV and modify it, or to completely reimplement the functionalities.

A typical approach is to use tiling. This involve defining your own large matrix data type, say `your_cv::BigMat_<T>` which mirrors `cv::Mat_<T>` except that large matrix dimensions and pointer offsets are supported. Then, define functions which perform copying and pasting sub-rectangles between your `BigMat` and OpenCV `Mat`. These copy and paste operations can only operate sub-rectangles smaller than the OpenCV size limit.

Years ago I had implemented a tiling approach to workaround a limitation in OpenCV function called `cv::remap` which is used for image rotation. That API function contains SSE2 instructions which had a limit of 32768 bytes per row of pixel. The approach involves copying and pasting sub-rectangles while staying within OpenCV limit. The code is https://gist.github.com/kinchungwong/141bfa2d996cb5ae8f42 

OpenCV has not yet adopted a library-wide framework for very large matrices or tiled matrices yet. Usually, it is up to the users of OpenCV to implement such framework.

**Comment by ihhub** [comment]
I faced the same problem long time ago (my images were 10+ GB). @K-Shinotsuka is correct about tiling idea if you face such limitation in size. Moreover you can enhance his idea by just assigning pointers from your big image/class into cv::mat objects without copy pasting your large memory area. But then you have to write a wrapper/framework to perform the same operation on multiple tiles.

**Comment by FlorentTomi** [comment]
I think tiling may be a good idea, but will this idea still work on "whole-image" algorithm (like the ones who needs the full histogram of the image, ie. automatic thresholding) ?

Even if I implement this idea for myself, I honestly think others will fall in the same "trap" as me. I don't remember seeing any clue that OpenCV could not handle such images. 
Maybe more documentation is needed ?

**Comment by ntomita** [comment]
As far as I know any version above (or equal to) 3.3.1 doesn't load very large image. I downgraded to 3.3.0.10 and it works.

**Comment by ntomita** [comment]
@FlorentTomi I see, that's why newer version has assertion statements to void the unintentional crash. Definitely the data type need to be updated so it can handle large images, which are "large" at this time but for next 5 years I believe people, including scientists, wouldn't think those are large as technology updates.

**Comment by hrnr** [comment]
Is there a plan to address this in OpenCV 4.0, @vpisarev ? IHMO this could go as evolution proposal too.

Starting with converting cv::Mat to use size_t everywhere and then we could fix bug-by-bug all the other places using ints.

**Comment by vpisarev** [comment]
done! see #11505

**Comment by jxu** [comment]
Is it done? I tried to open a 49800 x 39401 image and these restrictions are still here 
https://github.com/opencv/opencv/blob/ea64e860deaab633d2f992066b1da26e31811432/modules/imgcodecs/src/loadsave.cpp#L66

**Comment by jxu** [comment]
To work with large files (at your own risk) you can modify environment variables CV_IO_MAX_IMAGE_WIDTH, CV_IO_MAX_IMAGE_HEIGHT, OPENCV_IO_MAX_IMAGE_PIXELS by doing for example 

    export CV_IO_MAX_IMAGE_PIXELS=1099511627776

Thaks to @alalek for pointing this out to me.

**Comment by egorpugin** [comment]
What about an ability to change this from inside the program?
Those vars are globals and adding putenv in main does not help (only in global var).

**Comment by jtoa2** [comment]
i'm also trying to modify these variables from within a jupyter notebook running on a remote server, i've tried  

%env os.environ["OPENCV_IO_MAX_IMAGE_PIXELS"] = pow(2,90).__str__()
import cv2

without success

**Comment by egorpugin** [comment]
@jtoa2 
There must be strange format like 10000MB, 50KB.
And also there's a bug with such formats.
https://github.com/opencv/opencv/pull/17352

**Comment by valuat** [comment]
@jtoa2 Didn't work for me either. Neither did setting the environment variable directly on Linux.
