### ISSUE TITLE
Specify version of MobileNet-SSD from TensorFlow

### ISSUE THREAD

**Issue by Suning-liuhaiyang** [opencv/opencv#10219]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

 0x000007FED46A4A29 (igdrcl64.dll) Throws exception: 0xC0000005: An access violation occurred while reading location 0x000000000494C000.
If applicable to this exception handler, the program can safely continue to run.

**Comment by dkurt** [comment]
@Suning-liuhaiyang, please rewrite it in English.

**Comment by alalek** [comment]
#10220
