### ISSUE TITLE
Specify version of MobileNet-SSD from TensorFlow 

### ISSUE THREAD

**Issue by Suning-liuhaiyang** [opencv/opencv#10220]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

0x000007FED46A4A29 (igdrcl64.dll) Throws exception: 0xC0000005: An access violation occurred while reading location 0x000000000494C000.
If applicable to this exception handler, the program can safely continue to run.

**Comment by alalek** [comment]
Provided information is not enough to understand the reason of the problem.
- try to build OpenCV without OpenCL (cmake -DWITH_OPENCL=OFF) or disable it in runtime (`OPENCV_OPENCL_RUNTIME=disabled` environment variable).
- result of OpenCV tests on your machine
- crash stack trace
- display driver version (+ try to update to latest)
