### ISSUE TITLE
OpenCV doesn't link on Android x86/x86_64 with ndk 16.0.4442984 with R_386_GOTOFF error.

### ISSUE THREAD

**Issue by erikman** [opencv/opencv#10229]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Android x86/x86_64
- Compiler => Android toolchain (OpenCV binaries downloaded from github 3.3.0/3.3.1 release, My binary built from Android Studio, ndk-bundle-16.0.4442984 darwin-x86_64-gcc-i686-linux-android-4.9.x)

##### Detailed description
Can no longer link application for x86 or x86_64, get `relocation R_386_GOTOFF against preemptible symbol` in symbols from `libippiw.a` and `libippicw.a`. Rebuilding OpenCV for Android without IPP support fixes the problem. IPP are only used on x86/x86_64 so this is not a problem for arm builds, but the x86 builds are useful for debugging on HAX accelerated emulator.

Problem appeared after Android ndk upgrade (don't know my old version). The IPP binaries seems to be a binary only release compiled by Intel so I can't test rebuilding those libraries, otherwise searching the net suggests that the binaries should be compiled with `-fPIC` to fix this issue.

**Comment by airman00** [comment]
I experienced the same issue when I upgraded Android Studio on MacOSX.

Downgrading from NDK16 to NDK14 temporarily solved the issue for me

To downgrade:
1. Download the older NDK (use 14) from here:
https://developer.android.com/ndk/downloads/older_releases.html
2. Unzip and rename entire NDK folder to "ndk-bundle"
3. Replace NDK 16 with NDK 14 by replacing the "ndk-bundle" in your Android home folder (for me it was /Library/Android/sdk) with the "ndk-bundle" folder from Step 2

**Comment by hederguerreiro** [comment]
I had the same issue and your solution @airman00 solved my problem. Thanks!

**Comment by sergiomarquesmoura** [comment]
Any update on this? Have the same issue and downgrading is not really an option because I'm building on an external server with the latest NDK (v16) installed

**Comment by alalek** [comment]
Current workaround is disabling IPP (affects x86/x86_64 platforms): add "-DWITH_IPP=OFF" CMake option into build script.

**Comment by sergiomarquesmoura** [comment]
@alalek I see, but in practice we currently have to remove the x86 and x86_64 ABIs right?

**Comment by alalek** [comment]
> OpenCV binaries downloaded

This package built with Android NDK r10e, so it may just not work with NDK 16 (we don't test this). You need to rebuilt this package yourself with your target NDK 16 instead.

Mentioned flag doesn't disable x86/x86_64 libraries (it disables IPP optimizations for x86 only - code may work slower on some workloads).

**Comment by barzto** [comment]
@alalek I've got same error while linking against OpenCV binaries I've built with recent NDK (16.1.4479499). So I don't think this is related to old NDK version.

Doning small google search before encoutering this thread, I've found this NDK issue which may be related:

https://github.com/android-ndk/ndk/issues/556

**Comment by sergiomarquesmoura** [comment]
Hey @erikman , I tried to build OpenCV using NDK r16b, with the changes you added on the PR for open CV to be able to build with that version, and still getting some issues. To build, I followed these instructions: http://yangchao.me/post/build-opencv-android-sdk/ 

Basically I'm getting `Specified toolchain "arm-linux-androideabi-4.8" is missing in your NDK or
  broken.  Please verify that your NDK is working or select another compiler
  toolchain.` . Is there anything else I should change?

**Comment by hannesa2** [comment]
To the maintainer of OpenCV: You do a awesome job, but Android platform needs some modernization, please merge any improvement PR to reduce such issues and let the devs concentrate to awesome project they do

**Comment by sergiomarquesmoura** [comment]
Also, @erikman did you rebuild OpenCV using your previous NDK but with the `"-DWITH_IPP=OFF"` on the buildscript or using the newer r16 NDK?

**Comment by alalek** [comment]
@erikman 

> Can no longer link application for x86 or x86_64, get relocation R_386_GOTOFF against preemptible symbol in symbols from libippiw.a and libippicw.a

How did you build your application? (ndk-build / cmake from gradle / something else)
Do you use OpenCV Java API in you application?

**Comment by erikman** [comment]
@sergiomarquesmoura: my patches for building with r16 are here: #10288, @alalek's solution is nicer though :)

**Comment by alexandrucaraus** [comment]
I could build OpenCV only with NDK 15c, the two versions after that 16.0... and 16.1... to current date do not work. Is this an NDK or OpenCV issue?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Posts "don't work" with lack of required information are completely useless, consider doing minor investigations and providing related details (including version which you get and what you are doing with samples of exact commands).

P.S. You should use [ndk-16.config](https://github.com/opencv/opencv/blob/c89ae6e5378e2a502709728d6711931f50ee2318/platforms/android/ndk-16.config.py) with NDK16.

**Comment by alexandrucaraus** [comment]
Thanks for the config!
 
P.S. "don't work" is short for "I am getting the issue described in the subject", since we already in this context. I sure can go to OpenCV forum, but I want to talk about this issue :D.

**Comment by alalek** [comment]
This issue is closed with the link on the patch with fix. It is merged into OpenCV "master" branch, so this issue is resolved.
It is still unclear that you trying to do (your exact steps). You should understand that we are not able to help (even not to fix, - many problems are related to "configuration issues") if we can't reproduce the issue.

**Comment by alexandrucaraus** [comment]
Yep, I saw it's closed.
So to explain you what I am doing. I was building my application which is using OpenCV for android with NDK15c and all was good and pretty, till I updated to NDK16.0..., after that I got the same error this post was made for, and the version after (NDK16.1...) had the same issue. To solve I downgraded to NDK15c.

So my question was really easy :), is this related to NDK or to OpenCV, as I was thinking this is an NDK issue. It's okay, you replied to it in the second time, don't need to answer that.

So next really easy question, all I have to do is to update this file

/Users/alex/Projects/Android/DocSign/opencv/src/sdk/native/jni/android.toolchain.cmake

with this changes?

https://github.com/opencv/opencv/commit/90cc3f67079a454a302a31b2f2e3ccd1cf8be9bf

**Comment by alalek** [comment]
> I could build OpenCV
> I was building my application which is using OpenCV for android

They are a different things really.

You probably have prebuilt OpenCV package without the fix (no releases yet with the fix). So you need to apply some workaronds to hack it. These workarounds depends on how you build your app:
- do you use modern Android Studio with gradle?
- is there JNI part of your app? do you use CMake or ndk-build (with `.mk` files)?

It is better to use `android.toolchain.cmake` from Android NDK (instead of OpenCV - like Android Studio does), but it doesn't resolve error from this issue.
Take a look on workarounds from this comment: https://github.com/opencv/opencv/issues/10229#issuecomment-355291293 or from this commit https://github.com/opencv/opencv/pull/10515/commits/5f9bb6249efd6171d29098e6f2fdf6f3f4ffce21 .

**Comment by alexandrucaraus** [comment]
Yes, I use the prebuilt package for Android (v 3.3.0).
- Android Studio with gradle ( v 3.0.1).
- OpenCV only through JNI, don't use the OpenCV java classes.
- CMake,

The contents of CMakeLists.txt:

`cmake_minimum_required(VERSION 3.4.1)

set( OpenCV_DIR "../opencv/src/sdk/native/jni" )

set( CMAKE_VERBOSE_MAKEFILE on )

find_library( log-lib log )
find_package( OpenCV REQUIRED )

add_library(
            docscan-lib
            SHARED
            src/main/cpp/docscan_java.cpp
            src/main/cpp/docscan.cpp
            src/main/cpp/scanner.cpp
           )

target_link_libraries( docscan-lib ${OpenCV_LIBS} ${log-lib} -ljnigraphics)`

**Comment by alalek** [comment]
Try adding this before "add_library()" (from the [comment](https://github.com/opencv/opencv/issues/10229#issuecomment-355291293) with workarounds):

> set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a")

**Comment by alexandrucaraus** [comment]
Yep, works like a charm.
Thanks a ton!

**Comment by milly1228** [comment]
**airman00**  you save my time , thanks a lot
