### ISSUE TITLE
copyTo() function missing in Python bindings but available in Java bindings

### ISSUE THREAD

**Issue by ukalwa** [opencv/opencv#10225]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

copyTo() function binding is missing in Python but it is available in Java. I have a contour mask image and would like to copy only the contour object which is possible with the copyTo() function. As a workaround, I created a function in C++ and wrapped it with Python bindings.

**Comment by alalek** [comment]
There is no Python "cv::Mat" - numpy array reused for that. Consider using Python copy/deepcopy or related numpy alternatives.

**Comment by LaurentBerger** [comment]
@alalek But there is  no binding for [copyTo](https://docs.opencv.org/trunk/d3/d63/classcv_1_1Mat.html#a626fe5f96d02525e2604d2ad46dd574f)(OutputArray m,InputArray mask).
I find an [answer ](https://stackoverflow.com/questions/41572887/equivalent-of-copyto-in-python-opencv-bindings)here but it is not really easy.

I have done 
`void CV_EXPORTS_W copyTo(InputArray _src, OutputArray _dst, InputArray _mask);`
and 
```
void cv::copyTo(InputArray _src, OutputArray _dst, InputArray _mask)
{
    _src.copyTo(_dst, _mask);
}

```
and it seems good.
Is it reasonable to start a PR ?

**Comment by alalek** [comment]
I believe we can add `copyTo()` with mask if there is no Python/numpy alternative.

**Comment by LaurentBerger** [comment]
I'm not a python expert. I give my answer using new binding and numpy function

```
import numpy as np 
import cv2 as cv 

img = cv.imread("g:/lib/opencv/samples/data/baboon.jpg")
if img is None:
    print ( "Check path\n")
    exit()
cv.imshow("Image originale",img)
cv.waitKey(30)
valeurBGRinf = np.array([0,0,100])
valeurBGRSup = np.array([70, 70,255])
maskBleu = cv.inRange(img, valeurBGRinf, valeurBGRSup)
#***************************
#New binding
dst  = cv.copyTo(img,maskBleu)
cv.imshow("Bleu",dst)
#***************************
#using numpy
mBleu=cv.merge((maskBleu,maskBleu,maskBleu))
mask=mBleu.astype(bool)
dst2 = np.zeros(img.shape, dtype=np.uint8)
np.copyto(dst2,img,casting='unsafe',where=mask)
cv.imshow("Bleu2",dst2)
#***************************
#That's all
cv.waitKey(0)
cv.destroyAllWindows()

```
