### ISSUE TITLE
Reading ANN_MLP in base64

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10237]
Hi,

I'm trying to save ANN_MLP in base64 : 
I saved ANN_MLP in base64 : 
```
fs.open(dataname + "_init_weight.yml", FileStorage::WRITE + FileStorage::BASE64);
xx->write(fs); 
fs.release();

```
then trying to load I have got  an exception

` Ptr<ml::ANN_MLP> x = Algorithm::load<ANN_MLP>(dataname + "_init_weight.yml");
`
```
unknown file: error: C++ exception with description "G:\Lib\opencv\modules\core\src\persistence.cpp:891: error: (-2) The node is neither a map nor an empty collection in function cvGetFileNodeByName
" thrown in the test body.
```
I think opencv_ml_ann_mlp: is missing in yml hearder files

File saved is not empty.

Opencv 3.3-dev VS 2015 windows 10

**Comment by berak** [comment]
`Algorithm::write()` would add an additional `opencv_ml_ann_mlp:` toplevel node, and `Algorithm::load<ANN_MLP>()` now expects to find this.

if you save your model using `ANN_MLP::write()`, you have to use the resp. read() method, like:

```
   Ptr<ml::ANN_MLP> y = ANN_MLP::create();
   FileStorage fs2(dataname + "_init_weight.yml", FileStorage::READ);
   y->read(fs2.root());
```

**Comment by LaurentBerger** [comment]
@berak thanks
@alalek may be issue can be closed.
