### ISSUE TITLE
dnn: getFLOPS() returns negative value

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10239]
With SSD model.

Reproducer from dnn tests:
```
const string proto = findDataFile("dnn/ssd_vgg16.prototxt", false);
const string model = findDataFile("dnn/VGG_ILSVRC2016_SSD_300x300_iter_440000.caffemodel", false);
net = readNetFromCaffe(proto, model);
std::cout << net.getFLOPS(shape(1, 3, 300, 300)) << std::endl;
```

Actual output:
```
-5148659636
```

**Comment by xinguanxi** [comment]
hello, i have a problem about your code，which is as follows,    
             std::cout << net.getFLOPS(shape(1, 3, 300, 300)) << std::endl;
what is shape?   it is not belong to opencv
