### ISSUE TITLE
Opencv3.3 supports caffe model of multi-task learning with multiple outputs?

### ISSUE THREAD

**Issue by simon5u** [opencv/opencv#10234]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I have trained a caffe model with multi-task learning and I can read this model in python for testing purpose. However, I faced a problem when executing this line "output = net.forward("layername"); " of the same caffe model in Opencv3.3. Does this version support a caffe model of multi-task learning? Multi-task learning model refers to a model with multiple losses during training and this model can produces multiple outputs during testing.

##### Steps to reproduce

Prior to a multi-task learning model, I have tried a single-task caffe model and it works fine in Opencv3.3. After I change to a multi-task caffe model, the program stopped at 'output = net.forward("layername")' and the program shows the following error:-

Unhandled exception at 0x000007FE3AA9EAC3 (opencv_world330d.dll) in FaceProject.exe: 0xC0000094: Integer division by zero. 

When I debugging opencv, the program stopped at this file "convolution_layer.cpp" and the following line:-

    bool getMemoryShapes(const std::vector<MatShape> &inputs,
                         const int requiredOutputs,
                         std::vector<MatShape> &outputs,
                         std::vector<MatShape> &internals) const
    {
        CV_Assert(blobs.size() != 0);
        CV_Assert(!hasBias() || blobs[1].total() == (size_t)blobs[0].size[0]);
        CV_Assert(inputs.size() == (size_t)1);

        internals.clear();

        int inpCn = inputs[0][1];
        int inpH = inputs[0][2];
        int inpW = inputs[0][3];

        int outCn = blobs[0].size[0];
        Size out;

        if (padMode.empty())
        {
            out.height = (inpH + 2 * pad.height - (dilation.height * (kernel.height - 1) + 1)) / stride.height + 1;
            out.width = (inpW + 2 * pad.width - (dilation.width * (kernel.width - 1) + 1)) / stride.width + 1;
        }
        else
        {
            getConvPoolOutParams(Size(inpW, inpH), kernel, stride, padMode, out);
        }

        int ngroups = inpCn / blobs[0].size[1];
        **CV_Assert(inpCn % ngroups == 0 && outCn % ngroups == 0);**

Please help. Thanks.

**Comment by dkurt** [comment]
@simon5u, we need to know at least a model configuration to find a problem. Can you share `.prototxt`? Also you may try to use the latest master branch of OpenCV.

**Comment by simon5u** [comment]
@dkurt , thanks for the reply. 

Here you go, https://github.com/qiexing/face-landmark-localization/blob/master/model/deploy.prototxt

I will try later the latest master branch of Opencv.

**Comment by dkurt** [comment]
@simon5u, Am I right that you asked how to obtain several outputs from the model by single forward pass?  You can just call `outs = net.forward(['68point', 'poselayer'])`.

Please use http://answers.opencv.org for asking questions but issues tracker only for reproducible bug reports or feature requests. Thanks!

**Comment by simon5u** [comment]
@dkurt, you are right. I have tried your way for multiple outputs. It worked fine for the above link.

However, I still faced the same error for my prototxt as following:-

        int ngroups = inpCn / blobs[0].size[1]; >> 0
	printf("blobs[0].size[1]: %d", blobs[0].size[1]); >> 3
	printf("inpCn % ngroups: %d", inpCn % ngroups); >> 0, integer division by zero, program break
	printf("outCn % ngroups: %d", outCn % ngroups);
        CV_Assert(inpCn % ngroups == 0 && outCn % ngroups == 0);

For your information, my input channel is 1 which is greyscale only.
I think Opencv expected inpCn = 3, but for my case is 1.
Is this supported by Opencv? Or is this a bug?

Thanks.

**Comment by simon5u** [comment]
@dkurt, thanks. I will post the question in http://answers.opencv.org.
