### ISSUE TITLE
#opencv on freenode has no ops and an AWOL founder

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#10245]
(asking again here because admin@opencv.org hasn't responded in 11 days)

A user named vIkSiT registered the channel in 2005. that person hasn't been on IRC in 12 weeks and I'm not sure I've ever seen them in #opencv for longer than that, if ever. currently, nobody has op or is on the access list for the channel.

freenode staff member ilbelkyr said:
> https://freenode.net/groupreg outlines the procedure but basically, someone who represents the openCV project would contact us and we'd probably be happy to hand #opencv over to them

currently, the most present/active people answering questions on #opencv are myself (cracki), mcclintic, KicStart, StevenPuttemans.

I'd like to ask you to authorize the freenode staff to hand the channel over to some active people.

Cheers,
Chris

**Comment by mshabunin** [comment]
We don't mind if _cracki_, _mcclintic_, _KicStart_ and _StevenPuttemans_ will be granted operator rights for `#opencv` channel. How should we contact freenode staff? Maybe this message would be enough.

**Comment by berak** [comment]
taken [from here](https://freenode.net/groupreg)

> Once you have discussed your project with a staff member, you'll be asked to email projects@freenode.net with the details of your request, including any formal verification information that might be required.

@mshabunin  yes, i think all they wanted is a note from someone "official". (and thanks for caring !)

**Comment by crackwitz** [comment]
It would be good if someone could "officially" contact projects@freenode.net and let them know it's ok.

**Comment by christeld** [comment]
Thank you -- I am transferring the #opencv channel on @freenode to cracki as per the above -- he will have the ability to add operator privileges to the other nicknames mentioned above. In the event that the project should wish to change this in the future, please e-mail projects@freenode.net and reference this issue. 

Cheers,
Christel

**Comment by alalek** [comment]
@christeld Thank you!

I believe this can be closed for now.

**Comment by crackwitz** [comment]
since freenode is under new management, may I request changing the IRC link/button in [opencv.org](https://opencv.org/)'s footer to https://web.libera.chat/#opencv

**Comment by crackwitz** [comment]
some references:

https://isfreenodedeadyet.com/

netsplit.de:
[![image](https://user-images.githubusercontent.com/7065108/122115674-051f9600-ce25-11eb-95b9-af05db91f05f.png)](https://netsplit.de/networks/top10.php)

**Comment by vikasgupta-github** [comment]
> since freenode is under new management, may I request changing the IRC link/button in [opencv.org](https://opencv.org/)'s footer to https://web.libera.chat/#opencv

This has been changed. @crackwitz @alalek
