### ISSUE TITLE
opencv3.3  #include "opencv2/optflow/motempl.hpp" error：LNK1120 and Link2019

### ISSUE THREAD

**Issue by qiaoyunhao** [opencv/opencv#10247]
##### System information (version)
-- Example
- OpenCV =3.3
- Operating System / Platform =Windows10 64 Bit
- Compiler = Visual Studio 2015

##### Detailed description

-- error LNK2019: 无法解析的外部符号 cvCalcMotionGradient，该符号在函数 "void __cdecl update_mhi(struct _IplImage *,struct _IplImage *,int)" (?update_mhi@@YAXPEAU_IplImage@@0H@Z) 中被引用 --

**Comment by berak** [comment]
opencv does no more have a C implementation for this, please use the [corresponding c++ functions](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/include/opencv2/optflow/motempl.hpp) instead.
