### ISSUE TITLE
make command failed at 14% "Linking CXX shared library ../../lib/libopencv_imgproc.so"

### ISSUE THREAD

**Issue by jpcf** [opencv/opencv#10259]
##### System information (version)
- OpenCV => 3.1.1
- Operating System / Platform => Ubuntu Mate 16.04 LTS
 Compiler => gcc

##### Detailed description
After running the following CMAKE command without errors,
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..
```
I then run 'make' and I get the following errors:

[ 14%] Linking CXX shared library ../../lib/libopencv_imgproc.so
/usr/bin/ld: .eh_frame_hdr refers to overlapping FDEs.
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/imgproc/CMakeFiles/opencv_imgproc.dir/build.make:1759: recipe for target 'lib/libopencv_imgproc.so.3.3.1' failed
make[2]: *** [lib/libopencv_imgproc.so.3.3.1] Error 1
CMakeFiles/Makefile2:3158: recipe for target 'modules/imgproc/CMakeFiles/opencv_imgproc.dir/all' failed
make[1]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas on what this might be??

Thanks in advance!

**Comment by alalek** [comment]
Check this: https://sourceware.org/bugzilla/show_bug.cgi?id=20537
