### ISSUE TITLE
Bad python binding

### ISSUE THREAD

**Issue by krishraghuram** [opencv/opencv#10250]
##### System information (version)
OpenCV master
All platforms and compilers

##### Detailed description
Ref #6487 and #7059
Since a long time(I think since 3.0), cv2.drawKeypoints requires a compulsory third argument 'outImg'. However, there is no purpose to this argument, and one can simply pass None. 

This leads to situations like, 
User supplies outImg, and expects keypoints to be drawn, as follows.
`cv2.drawKeypoints(im,kp,key)`
But keypoints are not drawn, and the third argument, although compulsory, is silently dropped. 

This is bad binding, and needs to be fixed.

Suggested solution :
1. 'outImg' must be made a optional argument
2. If it is supplied, it must be used
3. In any case, outImg must be returned by the cv2.drawKeypoints function

**Comment by alalek** [comment]
Please provide complete example with expected and actual result.

> But keypoints are not drawn

What do you mean?

This code works well:
```
img = cv2.drawKeypoints(frame, keypoints, None)
```

`img` contains copy of `frame` with drawn `keypoints`. `frame` is not modified.

**Comment by krishraghuram** [comment]
```
import cv2
import numpy as np

im = cv2.imread("balloons.jpg", cv2.IMREAD_GRAYSCALE)

sift = cv2.xfeatures2d.SIFT_create()
kp, des = sift.detectAndCompute(im, None)

im_kp = np.zeros(im.shape, dtype=np.uint8)
###This does not work
cv2.drawKeypoints(im, kp, im_kp)

cv2.namedWindow("Key", cv2.WINDOW_NORMAL)
cv2.imshow("Key", im_kp)
cv2.waitKey(0)
```

The above code fails silently, and does not indicate what the error is... 

The third argument is basically irrelevant to the function.

**Comment by krishraghuram** [comment]
![Expected Result](https://user-images.githubusercontent.com/10024339/33715337-244f2b4c-db78-11e7-8681-73b73a6d9d5e.png)


![Actual Result](https://user-images.githubusercontent.com/10024339/33715307-17a8f940-db78-11e7-8c59-4ad5889a4523.png)

**Comment by alalek** [comment]
All "results" should be of the left side from `=` sign.

So,

> cv2.drawKeypoints(im, kp, im_kp)

Should be:

```
im_kp = cv2.drawKeypoints(im, kp, im_kp)
```

or

```
im_kp = cv2.drawKeypoints(im, kp, None)
```
without `im_kp = np.zeros` initialization.


There are several control flags, so removal of this parameter (or making it CV_OUT instead of CV_IN_OUT) can't be done without dropping of these flags.

**Comment by dkurt** [comment]
From [3.4.5](https://docs.opencv.org/3.4.5/d4/d5d/group__features2d__draw.html#gab958f8900dd10f14316521c149a60433) and [4.0.1](https://docs.opencv.org/4.0.1/d4/d5d/group__features2d__draw.html#ga5d2bafe8c1c45289bc3403a40fb88920) docs:

```
outImage = cv.drawKeypoints(image, keypoints, outImage[, color[, flags]])
outImg	 = cv.drawMatches(img1, keypoints1, img2, keypoints2, matches1to2, outImg[, matchColor[, singlePointColor[, matchesMask[, flags]]]])
outImg   = cv.drawMatchesKnn(img1, keypoints1, img2, keypoints2, matches1to2, outImg[, matchColor[, singlePointColor[, matchesMask[, flags]]]])
```

`outImg` and `outImage` are marked as required.

Let me close this issue.
