### ISSUE TITLE
createsamples: reproducible results

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10267]
Currently there is no way to reproduce results of createsamples tool. Launching with the same parameters doesn't return the same results.

- This tool uses `srand((unsigned int)time(0));`. Need to add command-line option to specify seed with some fixed default (like 12345).
- This tool uses `rand()`. It is not a thread-safe call. Need to replace these calls on `cv::RNG` API.

**Comment by sturkmen72** [comment]
i can work on this issue.
