### ISSUE TITLE
Issue with trained Cascade

### ISSUE THREAD

**Issue by ZixingLin** [opencv/opencv#10279]
Hi, I have recently trained my own cascade classifier using the opencv traincascade application, following all the relevant steps beforehand to create the required vector files and text files. After the training, I took the generated cascade.xml file and put it in my code. The code seems to be stuck at the "detectMultiScale" function when it is called using the trained cascade (Using a video). Testing with other online cascades seemed to work, however the one that I trained was stuck and I was unable to figure out what went wrong. The format of the xml file seems to be correct. Any form of help would be appreciated

##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Windows 64 Bit
- Python 2.7

I have attached the cascade file as well as the detection script in this post as txt files, since github does not support these files uploaded as their original formats.

Edit: After waiting for an extremely long period of time, the first frame of the video was finally processed, however it goes back to being stuck at the detectMultiScale function for another long period of time.

[cascade.txt](https://github.com/opencv/opencv/files/1546456/cascade.txt)

[detection.txt](https://github.com/opencv/opencv/files/1546457/detection.txt)

**Comment by alalek** [comment]
It is better to ask usage questions on Users OpenCV Q/A forum: http://answers.opencv.org

Before that, try disabling of OpenCL support in OpenCV: via environment variable `OPENCV_OPENCL_RUNTIME=disabled`
