### ISSUE TITLE
I am getting the following error while trying to make opencv form source on Linux CentOS

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#10275]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform =>Centos 64 Bit
- Compiler => Unix Makefiles

##### Detailed description

I want to try to make OpenCV from source on Linux CentOS for Java, with GStreamer support (for reading the stream from RTSP and write it back to RTMP stream), so I have already installed` gstreamer-1.12.4` and it's all dependencies and installed `ffmpeg `and it's dependencies. So everything goes well during configuring cmake, and while trying to make, then it throws the following error in 97%:

> [ 97%] Linking CXX shared library ../../lib/libopencv_java331.so
> /usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libavformat.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [lib/libopencv_java331.so] Error 1
> gmake[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
> gmake: *** [all] Error 2

**So** what is the reason, how can I solve this error?

**Comment by alalek** [comment]
> /usr/local/lib/libavformat.a

Your custom ffmpeg build is not supported.
You could try disabling builds of all shared libraries (Java/Python bindings).

See #10026

**Comment by Bahramudin** [comment]
@alalek Thanks for the reply! How can I disable the shared libraries? In `CMake `configuration I have already turned off the` BUILD_SHARED_LIBS=OFF`

**Comment by alalek** [comment]
Java/Python bindings are always shared libraries, so you need to disable them completely:
- `-DBUILD_opencv_python2=OFF`
- `-DBUILD_opencv_python3=OFF`
- `-DBUILD_opencv_java=OFF`

Also you could try rebuilding ffmpeg with proper flags (with -fPIC).

**Comment by Bahramudin** [comment]
@alalek I already mentioned that I try to build OpenCV for java bindings, so I cannot turn off the Java building.

**Comment by Bahramudin** [comment]
@alalek I tried to configure the FFmpeg as below: but not working
```
[ffmpeg-3.4]$ ./configure -fPIC
Unknown option "-fPIC".
```

**Comment by alalek** [comment]
Check comments from issue #10026 mentioned above.

BTW, Why are you installing custom versions of ffmpeg? I believe, CentOS has well prepared system packages for this.

**Comment by Bahramudin** [comment]
@alalek I am also wondering why CenOS does not have ffmpeg package to install in its repositories, so when I try to make OpenCV, CMake configuration, there is no ffmpeg found, so when I try the following commands, then is the result:
```
[root@localhost lib]# yum install ffmpeg
Loaded plugins: fastestmirror, langpacks
base                                                                                                                      | 3.6 kB  00:00:00     
epel/x86_64/metalink                                                                                                      | 6.8 kB  00:00:00     
extras                                                                                                                    | 3.4 kB  00:00:00     
updates                                                                                                                   | 3.4 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.sohu.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No package ffmpeg available.
Error: Nothing to do
[root@localhost lib]# yum install ffmpeg-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.ustc.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No package ffmpeg-devel available.
Error: Nothing to do
[root@localhost lib]# yum install ffmpeg*
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.tongji.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No package ffmpeg* available.
Error: Nothing to do
[root@localhost lib]#
```

**Comment by Bahramudin** [comment]
@alalek Before I tried a lot to build opencv from source on Linux CentOS, tried huge examples on the internet and so on, some time everything goes will even building and installng, but when tried to use in the project, it says [this ](http://answers.opencv.org/question/179424/gstreamer-unable-to-open-rtsp-stream-on-centos-opencv/)problem, and after that I found one [site ](http://linuxfromscratch.org/blfs/view/svn/general/opencv.html) which is a guid to install OpenCV on linux centos.
