### ISSUE TITLE
Segmentation fault while running OpenCV with TBB Support on Raspberry pi

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#10271]
##### System information (version)
- OpenCV => 3.3.1-dev
- Operating System / Platform => Raspbian Stretch 
- Compiler => gcc
- TBB (Threading Building Blocks) => libtbb-dev_4.5-1_armhf (self compiled)
- Python => 2.7.13
##### Detailed description

Hello , i successfully compiled and installed my OpenCV with (`TBB` + `NEON` + `VFPV3`) on my raspberry pi 3 with latest raspbian OS with no errors :) . But now the OpenCV fails to run properly and ending up with `Segmentation fault`  . 

##### Steps to reproduce
i ran this demo code:
Demo Code: (in python)

[Image.zip](https://github.com/opencv/opencv/files/1544714/Image.zip)
```
import cv2
cap = cv2.VideoCapture(0)
while True:
    ret,frame = cap.read() 
    cv2.imshow('img1',frame) #display the captured image
     if cv2.waitKey(1) & 0xFF == ord('q'):
		break
cap.release()
cv2.destroyAllWindows()
```

when i ran this code , i immediately encountered `Segmentation fault ` error .....different debug files are attached below ,may help in identifying problem easily .

##### Trace of error (Strace):
using `strace` command [https://linux.die.net/man/1/strace](url) ,
output file : 
[strace_output.txt](https://github.com/opencv/opencv/files/1544720/strace_output.txt)

##### Debug file (GDB):
using `GDB` compiler [https://www.gnu.org/software/gdb/documentation/](url)
output file:
[gdb_output.txt](https://github.com/opencv/opencv/files/1544710/gdb_output.txt)

**Comment by abhiTronix** [comment]
####Here how i compiled my OpenCV : 
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_NEON=ON -DENABLE_VFPV3=ON -DBUILD_TESTS=OFF -DINSTALL_PYTHON_EXAMPLES=OFF -DBUILD_EXAMPLES=OFF -DOPENCV_EXTRA_MODULES_PATH=/home/pi/opencv_contrib-master/modules -DWITH_TBB=ON -DCMAKE_CXXFLAGS=”-D__TBB_64BIT_ATOMICS=0 -DTBB_USE_GCC_BUILTINS=1″ -DWITH_LIBV4L=0N -DWITH_V4L=ON .. `
`make -j3`
`sudo make install`
`sudo ldconfig`
and i updated my post :)

**Comment by alalek** [comment]
BTW, There is no `CMAKE_CXXFLAGS`, only `CMAKE_CXX_FLAGS`

Problem is very hardware/software specific, so we can't help here. You need to investigate reason of the problem itself. Start from building OpenCV without TBB.

**Comment by abhiTronix** [comment]
Yes i previously using it without TBB without any problem ,but i want to optimize it to add parallelism too, in order to achieve maximum speed. As TBB is running with no problem and we have possibility to add it to OpenCV ,is there any workaround for this? or `pthread` is only option?

**Comment by abhiTronix** [comment]
@alalek Firstly thanks so much for your support 👍  ....i was able to create stable openCV with (TBB+NEON+VFPV3) with latest TBB and openCV ,after 5 days of debugging and coding .
 Today,I self-compiled latest TBB(2018-Update 2) from source and compiled with latest openCV(3.3.1 -dev) and everything is just awesome with significant #30% increase in performance :)
Anyone who want all precompiled .deb Latest `OpenCV` with (`TBB`+`NEON`+`VFPV3`) Support can email me at [abhi.una12@gmail.com](url)
