### ISSUE TITLE
Color changed when using bitmapToMat in android

### ISSUE THREAD

**Issue by titanseason** [opencv/opencv#10281]
I copied the convert code from [Here](https://github.com/opencv/opencv/blob/master/modules/java/generator/src/cpp/utils.cpp) and using the method **nBitmapToMat2**. But I found the color changed after the conversion at the same pixel.
For example:
I log the color at (0, 0) in Java code: The result is **181 178 165**
`Log.d(TAG,  Color.red(bitmap.getPixel(0, 0)) + " " + Color.green(bitmap.getPixel(0, 0)) + " " + Color.blue(bitmap.getPixel(0, 0)))`
But when I log the color at the same pixel in OpenCV, the color changed to **176 176 160**
```
int r = (int) img->at<cv::Vec4b>(0, 0)[0];
int g = (int) img->at<cv::Vec4b>(0, 0)[1]; 
int b = (int) img->at<cv::Vec4b>(0, 0)[2];
 __android_log_print(ANDROID_LOG_DEBUG, "OpenCV", "point color: %d %d %d", r, g,b);
```

##### System information (version)
OpenCV => 2.4.13.4
Operating System / Platform => Android
Compiler => NDK-Bundle

**Comment by alalek** [comment]
Try experiments with `bitmap.eraseColor(Color.RED)`

**Comment by wuyajun19900627** [comment]
Does opencv only support two types of format(ANDROID_BITMAP_FORMAT_RGB_565 and ANDROID_BITMAP_FORMAT_RGBA_8888) of Bitmap when call Utils.bitmapToMat() ? I got a CvException, here is the log:
CvException [org.opencv.core.CvException: /Volumes/Linux/builds/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:33: error: (-215) info.format == ANDROID_BITMAP_FORMAT_RGBA_8888 || info.format == ANDROID_BITMAP_FORMAT_RGB_565 in function void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean)
]

please help me with this. @alalek
