### ISSUE TITLE
Add support for new type of reduce(): REDUCE_MAX_IND

### ISSUE THREAD

**Issue by adishavit** [opencv/opencv#10286]
When working with DNNs, one often gets a vector, matrix or tensor of values where one needs to find the _index_ of the maximal (or minimal) element.
The function `cv::reduce()` seems perfect for this and should be able to do it, given 2 new `ReduceTypes`: `cv::REDUCE_MAX_IND` and `cv::REDUCE_MIN_IND`. As opposed to `cv::REDUCE_MAX` which reduces to the max value, `cv::REDUCE_MAX_IND` will reduce the the _index_ of the max value (`cv::REDUCE_MIN_IND` will work similarly).

(An alternative name might be `cv::REDUCE_MAX_ELEM` which is consistent with the C++ `std::max_element())`

In the [`fcn_semsegm.cpp` example,](https://github.com/opencv/opencv/blob/master/samples/dnn/fcn_semsegm.cpp#L47)  the whole `colorizeSegmentation()` function could be ***_reduced_*** to a `reduce(...REDUCE_MAX_IND)` and `remap()`. The function is copied and used again in [torch_enet.cpp](https://github.com/opencv/opencv/blob/9665dde678a3c505a5643de727c80267f19d6daf/samples/dnn/torch_enet.cpp).

Before running off to implement this, I'd like some comments and suggestions on this idea.
Thoughts?

**Comment by alalek** [comment]
I think, this should be a separate call (`reduceMaxElement(InputArray src, OutputArray idx/*CV_32S*/, int dim)`) instead of new flag of `cv::reduce()` to avoid creation of monster functions like `cv::cvtColor()`.

**Comment by adishavit** [comment]
But then you'll also need `reduceMinElement()`.  
Besides, `reduce()` is already supporting sum, avg, min and max. It seems like a natural fit.

Are you concerned about the returned output types?

**Comment by hrnr** [comment]
Doesn't `minMaxIdx()` and `minMaxLoc()` solve this already?

The interface is not very nice and they don't support multi channel matrices, but they do the job in most of the cases.

It would be nice, however, to have some convenient overloads like `cv::max(InputArray)` `cv::maxIdx()` and the same for min, which would be easier to use in simple case when you need the index or value.

**Comment by alalek** [comment]
`minMaxIdx`/`minMaxLoc` performs global scan instead of dimension reduction.

**Comment by hrnr** [comment]
oh I now I see what you want to achieve. Sorry for the noise.

**Comment by adishavit** [comment]
Seems like there are many different implementations of `reduce()` - "regular", OpenCL, CUDA, HAL etc.  
I can probably to the regular C version, but not the rest.
Any suggestions?

**Comment by alalek** [comment]
ArgMin/ArgMax is implemented here: #20733
DNN support is here: #21208
