### ISSUE TITLE
[Q] Why is Halide_Backend slower?

### ISSUE THREAD

**Issue by chamcham115** [opencv/opencv#10311]
Hi, I wonder about halide backend.

I compiled the opencv code using halide  library. 
the halide library is downloaded in halide-website.

And then, I tested using yolo sample program. 

the normal source code is runing at 350ms. 
but, modified code applied halide_backend is ruuing at 450ms.

what is problem?

my computer's gpu is k5200.

Thanx.

**Comment by dkurt** [comment]
Duplicate, see https://github.com/opencv/opencv/issues/10261.
