### ISSUE TITLE
Please add support to CUDA 9.1

### ISSUE THREAD

**Issue by soaph** [opencv/opencv#10310]
##### System information (version)

- OpenCV => 3.3.1:
- Operating System / Platform => Arch Linux:
- Compiler => gcc 7.2.1:

##### Detailed description

I compiled OpenCV 3.3.1 with CUDA 9.0, and it worked well.

Today the Arch Linux package manager updates the new CUDA 9.1, and OpenCV 3.3.1 still requires CUDA 9.0 shared objects. Therefore linking error prompting `.so.9.0 not found`.

Wish you to update the support for CUDA 9.1 soon.

Thank you~~

##### Steps to reproduce

Use OpenCV 3.3.1 and update CUDA to 9.1, then try compiling any program using OpenCV.

**Comment by alalek** [comment]
There is nothing to fix in OpenCV. You should rebuild OpenCV on dependencies changes (CUDA 9.0 -> 9.1). The same rule is for any other software (with different dependencies list).

I have no idea how you got OpenCV. In case of manual builds try this:
- Uninstall installed OpenCV files (perhaps you should run `make uninstall` from build folder - it contains list of installed files).
- Re-build OpenCV from **clean** build directory (CMake caches found dependencies).

In case of AUR package you need to rebuild package itself and install its update on your system.

This tracker is for issues and bugs that needs fix in OpenCV.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
