### ISSUE TITLE
opencv\src\modules\core\src\ocl.cpp 3663 line compile error

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#10322]
##### System information (version)

- OpenCV => new
- Operating System / Platform =>WIN10X64
- Compiler =>VS2015

##### Detailed description
opencv\src\modules\core\src\ocl.cpp
3663 line:
        CV_INSTRUMENT_REGION_OPENCL_COMPILE(cv::format("Build OpenCL program: %s/%s %" PRIx64 " options: %s",
                sourceModule_.c_str(), sourceName_.c_str(),
                src.hash(), buildflags.c_str()).c_str());

compiler error.

**Comment by alalek** [comment]
What is the message?

**Comment by dbyoung720** [comment]
clean rebuild is ok

**Comment by dbyoung720** [comment]
opencv\src\modules\core\src\ocl.cpp  compile error.
