### ISSUE TITLE
RelWithDebInfo and MinSizeRel build types only work if opencv_world exists (patch included)

### ISSUE THREAD

**Issue by Earthwings** [opencv/opencv#10321]
##### System information (version)
- OpenCV => 3.3.1 (3.3.1-0xenial-20171106-101742-0800)
- Operating System / Platform => Ubuntu 16.04.3 LTS 64 bit
- Compiler => gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

##### Detailed description

When using cmake and RelWithDebInfo as build type, I get errors like this:
```
make[2]: *** No rule to make target 'opencv_calib3d-NOTFOUND', needed by '...'.  Stop.
```

The reason seems to be that MAP_IMPORTED_CONFIG_RELWITHDEBINFO is set even if the previous target properties IMPORTED_LOCATION_RELEASE is not evaluated (no opencv_world here). Moving the scope of the MAP_IMPORTED_CONFIG_RELWITHDEBINFO in the upper section fixes it.

```
--- /opt/ros/kinetic/share/OpenCV-3.3.1/OpenCVConfig.cmake	2017-12-15 15:42:16.134636914 +0100
+++ OpenCVConfig.cmake	2017-12-15 15:39:03.629682333 +0100
@@ -198,14 +198,14 @@
         IMPORTED_LOCATION_RELEASE "${__location_release}"
       )
     endif()
-    # OpenCV supports Debug and Release only.
-    # RelWithDebInfo and MinSizeRel are mapped to Release
-    if(TARGET ${__cvcomponent})
-        set_target_properties(${__cvcomponent} PROPERTIES
-            MAP_IMPORTED_CONFIG_MINSIZEREL "Release"
-            MAP_IMPORTED_CONFIG_RELWITHDEBINFO "Release"
-        )
-    endif()
+  endif()
+  # OpenCV supports Debug and Release only.
[OpenCVConfig.cmake.diff.txt](https://github.com/opencv/opencv/files/1563073/OpenCVConfig.cmake.diff.txt)

+  # RelWithDebInfo and MinSizeRel are mapped to Release
+  if(TARGET ${__cvcomponent})
+      set_target_properties(${__cvcomponent} PROPERTIES
+          MAP_IMPORTED_CONFIG_MINSIZEREL "Release"
+          MAP_IMPORTED_CONFIG_RELWITHDEBINFO "Release"
+      )
   endif()
 endforeach()
```

##### Steps to reproduce

CMakeLists.txt that uses OpenCV like so:
```
find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})
target_link_libraries(my_awesome_library ${OpenCV_LIBRARIES})
```
and build it like this:
```
catkin init --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
catkin build
```
Not setting a build type or using Debug or Release does not trigger the problem

**Comment by alalek** [comment]
Try latest master

**Comment by Earthwings** [comment]
Thanks, I guess you refer to https://github.com/opencv/opencv/commit/f39ee9c6a1ddd81c293bb8d2378d90eda0ddf1fc. Will try it when a new package arrives, the workaround is fine for me in the meantime.
