### ISSUE TITLE
opencv\src\3rdparty\protobuf\src\google\protobuf\text_format.cc 400 line is right?

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#10323]
##### System information (version)

- OpenCV =>new
- Operating System / Platform => WIN10X64
- Compiler => VS2015

##### Detailed description
opencv\src\3rdparty\protobuf\src\google\protobuf\text_format.cc
400 line:
      if (singular_overwrite_policy_ == FORBID_SINGULAR_OVERWRITES) {
        // Fail if any_type_url_field has already been specified.
        if ((!any_type_url_field->is_repeated() &&
             reflection->HasField(*message, any_type_url_field)) ||
            (!any_value_field->is_repeated() &&
             reflection->HasField(*message, any_value_field)) {
          ReportError("Non-repeated Any specified multiple times.");
          return false;
        }

 !any_value_field->is_repeated()  is right?

242 line:
 tokenizer_error_collector_(this),
is right?

**Comment by alalek** [comment]
> "3rdparty\protobuf"

This library is not developed here.

**Comment by dbyoung720** [comment]
ok, thank.
