### ISSUE TITLE
build: too long path on Windows 10

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10332]
> 173>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "tutorial_tutorial_homography_ex3_homography_from_camera_displacement.dir\Release\(TUTORIA.7238BB8A.tlog\(TUTORIAL) tutorial_homography_ex3_homography_from_camera_displacement.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\build\master_winpack-test-win64-vc14-static\build\samples_build\cpp\tutorial_tutorial_homography_ex3_homography_from_camera_displacement.vcxproj]

**Comment by sturkmen72** [comment]
probably #10333 will solve it.
