### ISSUE TITLE
build opencv_dnn340

### ISSUE THREAD

**Issue by OmarHamdoun** [opencv/opencv#10336]
opencv_340
visual studio_2015
windows7_64 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2504	'LPNormalizeLayer': base class undefined	opencv_dnn	F:\opencv\opencv\modules\dnn\src\layers\lp_normalize_layer.cpp	14	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'pnorm': undeclared identifier	opencv_dnn	F:\opencv\opencv\modules\dnn\src\layers\lp_normalize_layer.cpp	20	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2352	'cv::dnn::experimental_dnn_v3::Layer::getMemoryShapes': illegal call of non-static member function	opencv_dnn	F:\opencv\opencv\modules\dnn\src\layers\lp_normalize_layer.cpp	30

**Comment by dkurt** [comment]
@OmarHamdoun, there is no `LPNormalizeLayer` since https://github.com/opencv/opencv/pull/9636. Clean your build directory.
