### ISSUE TITLE
Build error: "cmd.exe" exited with code 1

### ISSUE THREAD

**Issue by Bodeeen** [opencv/opencv#10355]
##### System information (version)

- OpenCV => lastest from github
- Operating System / Platform => Windows 7 64 bit
- Compiler => Visual Studio 2017

##### Detailed description

Hi,

I'm trying to build the OpenCV libraries from source following these instructions https://docs.opencv.org/3.2.0/d3/d52/tutorial_windows_install.html. When I get to the point of actually building the solution in VS2017 a very large number of projects do not compile correctly and give the error in the title. Am I missing something stupidly obvious? The reason I'm not using the pre-built libraries is that I wanted to use the CUDA modules which, from what I understand, are not included in the pre-built version.

Thankful for any and all tips :)

**Comment by catree** [comment]
I have successfully built OpenCV with CUDA9 recently and with VS2017 community. See this related [post](https://stackoverflow.com/q/45918446).

What you should have to change:

- in CMake, change the value of `CUDA_HOST_COMPILER` (should be by default `$(VCInstallDir)/bin`) by the path to `cl.exe`, something like: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe` (**check this path on your computer**)
- in CMake, set `CUDA_NVCC_FLAGS` to `--cl-version=2017` (I don't remember if it is really needed or not)
- disable tests or perf_tests if you have some errors in these files or post the related errors here

**Comment by Bodeeen** [comment]
Hi again,
thank you for your suggestions. Now the previous error is gone and the compilations seems to progess much better thatn earlier (though I didn't find the CUDA_NVCC_FLAGS in the CMake configuration?). Still though I'm having issues. When buiding the ALL_BUILD project, I get errors as shown in the attached screen-dumps.

![debug_x64](https://user-images.githubusercontent.com/14180271/34297527-e6710af0-e718-11e7-8bc6-bce1ee175f79.png)

If I still try to built the INSTALL project afterwards I get the same type of error. The "install" folder is created though and contains many seemengly correctly built libraries. But if I try to run the example programs, it complains that "The program can't start because cudart64_90.dll is missing from your computer." I'm guessing that many of the projects fail to build and that these libraries (eg. cudart64_90) are missing giving this final error,

Again thankful for any suggestions! :)

**Comment by catree** [comment]
See also [here](https://github.com/opencv/opencv/issues/6716#issuecomment-323074308).

To recap, I have successfully built OpenCV (`3.4.0-rc-74-geba176c29`) with CUDA v9.0 (`V9.0.176`) and Visual Studio Community 2017 version 15.4.5 with the following changes:

- in CMake GUI, set the `CUDA_HOST_COMPILER` to the path to `cl.exe` (mine is `C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe`) (previously was `$(VCInstallDir)/bin`)
- either disable in CMake GUI `BUILD_PERF_TESTS` 
- or try to fix somehow the errors ; for the following files: 
    - `modules\cudaarithm\perf\perf_element_operations.cpp`
    - `modules\cudaarithm\perf\perf_reductions.cpp`
    - `modules\cudaimgproc\perf\perf_blend.cpp`
    - `modules\cudawarping\perf\perf_warping.cpp`
add at the top of the files:
```
DEF_PARAM_TEST(Sz_Depth, cv::Size, MatDepth);
DEF_PARAM_TEST(Sz_Depth_Cn, cv::Size, MatDepth, MatCn);
```
- for the following file, add at the top of the file: `DEF_PARAM_TEST(Sz_Depth_Cn, cv::Size, MatDepth, MatCn);`
  - `modules\cudaarithm\perf\perf_core.cpp`

- for the following files, add at the top of the file: `DEF_PARAM_TEST(Sz_Depth, cv::Size, MatDepth);`
  - `modules\cudaimgproc\perf\perf_histogram.cpp`
  - `modules\cudastereo\perf\perf_stereo.cpp`

**Comment by catree** [comment]
Related #10497 and https://gitlab.kitware.com/cmake/cmake/merge_requests/1631
