### ISSUE TITLE
aarch64: too many warnings about 'fpic'

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#10350]
When building recent OpenCV (including 3.4-rc), hundreds of warning ( ```cc1plus: warning: /home/firefly/opencv-fork/build/modules/ts/precomp.hpp.gch/opencv_ts_Release.gch: created and used with different settings of -fpic``` ) appears when using **gcc 5.4.0** on **Aarch64**

##### System information (version)
- OpenCV => 3.4-rc (after #8198)
- Operating System / Platform => Jetson TX1, Jetson TX2, FireFly RK3399, PINE64, ODROID-C2 (All aarch64)
- Compiler => All **gcc 5.4.0**

##### Detailed description
The warning is just a warning, but it happens a lot during the build, for example more than 400 warnings during the build on Jetson TX1.

```
$ grep warning:.*fpic arm-jetson-tx1-build.txt  | wc -l
411
```

I'm not sure which to go, either
* disable the warning
* find out which compiler option is making this warning

Any suggestion, please ?

##### Extra information
Looking on my local machines, it seems it only happens on GCC 5.4.0 on ARM64bit
I confirmed this doesn't happen on GCC 6.3.0, 4.9.2 (both on ARM64bit)
Unfortunately, I don't have other platform(x86, amd64) which uses gcc 5.4.0, so I'm not sure either the version or platform is causing this problem.

**Comment by mshabunin** [comment]
@tomoaki0705 , try to disable precompiled headers: `-DENABLE_PRECOMPILED_HEADERS=OFF`.

**Comment by mshabunin** [comment]
The root cause of this problem is incomplete implementation of PCH generation in cmake scripts - header compilation flags are not in sync with sources compilation flags in some configurations.

Related issue: #5944
