### ISSUE TITLE
cv::VideoCapture::read cannot read any frame at all

### ISSUE THREAD

**Issue by teongleng** [opencv/opencv#10378]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015

**Comment by teongleng** [comment]
Just to make it clear:
1) My PATH (OPENCV_DIR aka C:\opencv\build\x64\vc14) is pointing to the directory %OPENCV_DIR%\bin where opencv_ffmpeg330_64.dll is located.
2) I have also make a copy of opencv_ffmpeg330_64.dll & place it next to app EXE file.
3) I have added cap.isOpened() for checking.
But the result still the same.

Below is my updated code (cap.isOpened() added) & the result it produced:
#include "opencv2\highgui\highgui.hpp"
#include "opencv2\imgproc\imgproc.hpp"

int main()
{
	cv::namedWindow("Example 3", cv::WINDOW_AUTOSIZE);
	cv::VideoCapture cap;

	cap.open("movie.avi");

	/***** Newly Added *****/
	if (!cap.isOpened())
	{
		std::cout << "Cannot open file...\n";
		return -1;
	}

	cv::Mat frame;
	double dWidth = cap.get(CV_CAP_PROP_FRAME_WIDTH);
	double dHeight = cap.get(CV_CAP_PROP_FRAME_HEIGHT);
	std::cout << "Frame size : " << dWidth << " x " << dHeight << std::endl;
	for (;;)
	{
		cap.read(frame);
		if (frame.empty());
		{
			std::cout << "Frame empty...\n";
			break;
		}
		cv::imshow("Example 3", frame);
	}
	cv::waitKey(0);
    return 0;
}

Result (Same as before):
Frame size : 1920 x 1080
Frame empty...
Press any key to continue . . .

**Comment by alalek** [comment]
Try to run with `OPENCV_VIDEOCAPTURE_DEBUG=1` environment variable.
Could you try OpenCV's video file (vtest.avi from samples/data) or share your file (or part of this file) somehow?

**Comment by teongleng** [comment]
Hi Sir,

- Can you please provide me the step to run with OPENCV_VIDEOCAPTURE_DEBUG=1 environment variable?
Is it go to Control Panel > System > Advanced system settings > Advanced Tab > Environment Variables... > System variables > Path > Edit... > New > Type "OPENCV_VIDEOCAPTURE_DEBUG=1" ?

- I have uploaded the entire Example 2-3.cpp file, all code is similar to the previous comment.
[Example 2-3.zip](https://github.com/opencv/opencv/files/1581244/Example.2-3.zip)


- If you need the entire project directory you can download from below link:
[https://1drv.ms/f/s!AnE7WULnZpCwjxM9eDEpK0WU90nC](url)

Thank you.

**Comment by teongleng** [comment]
Hi Sir,
I've tried to run the program again, this time with OPENCV_VIDEOCAPTURE_DEBUG=1 included inside VS2015 IDE (Project > Properties... > Configuration Properties > Debugging > Environment).

Code:
#include "stdafx.h"
#include <iostream>
#include "opencv2\highgui\highgui.hpp"
#include "opencv2\imgproc\imgproc.hpp"

int main()
{
	cv::namedWindow("Example 3", cv::WINDOW_AUTOSIZE);
	cv::VideoCapture cap;

	cap.open("vtest.avi");

	/***** Newly Added *****/
	if (!cap.isOpened())
	{
		std::cout << "Cannot open file...\n";
		return -1;
	}

	cv::Mat frame;
	double dWidth = cap.get(CV_CAP_PROP_FRAME_WIDTH);
	double dHeight = cap.get(CV_CAP_PROP_FRAME_HEIGHT);
	std::cout << "Frame size : " << dWidth << " x " << dHeight << std::endl;
	for (;;)
	{
		cap.read(frame);
		if (frame.empty());
		{
			std::cout << "Frame empty...\n";
			break;
		}
		cv::imshow("Example 3", frame);
	}
	cv::waitKey(0);
    return 0;
}


Result:
VIDEOIO(cvCreateFileCapture_FFMPEG_proxy (filename)): trying ...
VIDEOIO(cvCreateFileCapture_FFMPEG_proxy (filename)): result=000002A75A90D060 ...
Frame size : 768 x 576
Frame empty...
Press any key to continue . . .

Thank you.

**Comment by alalek** [comment]
> VIDEOIO(cvCreateFileCapture_FFMPEG_proxy (filename)): result=000002A75A90D060

This mean that ffmpeg backend is selected and opencv_ffmpeg330_64.dll is loaded successfully.

**Comment by alalek** [comment]
In next time you should start from using samples from OpenCV.
You sample have several issues:
- invalid semicolon in this line:
```.diff
+std::cout << frame.size() << std::endl;
-if (frame.empty());
+if (frame.empty())
{
```
- "cv::waitKey(0);" must be placed right after "cv::imshow()" with some non-zero delay:
```
cv::imshow("Example 3", frame);
cv::waitKey(30); // ~30 fps
```

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Only confirmed issues should be reported here. This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by teongleng** [comment]
Hi Sir,

Thanks for your help and it's really a great experience learning from you.

Thank you and have a wonderful Merry Christmas.

Your sincerely,
Teongleng

On Dec 22, 2017 6:33 PM, Alexander Alekhin <notifications@github.com> wrote:

In next time you should start from using samples from OpenCV.
You sample have several issues:

  *   invalid semicolon in this line:

+std::cout << frame.size() << std::endl;
-if (frame.empty());
+if (frame.empty())
{

  *   "cv::waitKey(0);" must be placed right after "cv::imshow()" with some non-zero delay:

cv::imshow("Example 3", frame);
cv::waitKey(30); // ~30 fps


Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Only confirmed issues should be reported here. This tracker is for issues and bugs that needs fix in OpenCV.
