### ISSUE TITLE
SVMSGD classifier not working

### ISSUE THREAD

**Issue by ale93111** [opencv/opencv#10379]
#####  System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Ubuntu 16.04

##### Detailed description
I'm trying to use the SVMSGD classifier in OpenCV  but I'm struggling to get any kind of result. Below there is an excerpt of the relevant code I am using right now. Even when I change the SVMSGD parameters the training is always almost instantaneous and the weights saved in the xml files are always all zeros. (and of course i get poor accuracy results) The other classifiers like the SVM work fine so there shouldn't be any problems with the data.

##### Code example
```
cv::Ptr<cv::ml::SVMSGD> svm = cv::ml::SVMSGD::create();
svm->setOptimalParameters();

cv::Ptr<cv::ml::TrainData> tdata = cv::ml::TrainData::create(train_data, cv::ml::ROW_SAMPLE, truth_data);
svm->train(tdata);

svm->save("svmsgd.xml");
```

**Comment by berak** [comment]
you need [-1,1] labels to use this.

if all your truth_data labels are > 0 , there is [no need to train anything](https://github.com/opencv/opencv/blob/master/modules/ml/src/svmsgd.cpp#L245), because your samples are all of the same class.

**Comment by ale93111** [comment]
Thank you, that was the problem and now it works.  I guess this means it doesn't support multi-label classification.

**Comment by berak** [comment]
@ale93111 

>  I guess this means it doesn't support multi-label classification.

yes, exactly, it is a binary classifier only.
