### ISSUE TITLE
cuda_compile_generated_gpu_mat.cu.obj link error

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#10384]
##### System information (version)

- OpenCV => 2017-12-22
- Operating System / Platform =>Windows 10 X64
- Compiler => Visual Studio 2015
- Cuda => CUDA9.0

##### Detailed description
cuda_compile_generated_gpu_mat.cu.obj : error LNK2001: unresolved external symbol __cudaRegisterLinkedBinary_54_tmpxft_00003920_00000000_17_gpu_mat_compute_70_cpp1_ii_71482d89

Is it a Cuda 9.0 nvcc bug ?
Which version of CUDA is officially recommended?

**Comment by mprevot** [comment]
Seems that your gpu_mat_compute binary path is not given.

Cuda 9 and 9.1 work fine with OpenCV HEAD, but the toolset must be 14.11.xxx, not 14.12.xxx (you can have one or both and others with VS2017).

In  general you should give a more detailed configuration for your cmake build. I'm not seeing your 'steps to reproduce'.
