### ISSUE TITLE
after #10338 repair bug #10322， link ocl.obj err.

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#10383]
##### System information (version)

- OpenCV => 2017-12-22
- Operating System / Platform => Windows 10 X64
- Compiler =>Visual Studio 2015

##### Detailed description

after #10338 repair bug #10322, link ocl.cpp err:

ocl.obj : error LNK2001: unresolved external symbol "void __cdecl cv::utils::logging::internal::writeLogMessage(enum cv::utils::logging::LogLevel,char const *)" (?writeLogMessage@internal@logging@utils@cv@@YAXW4LogLevel@234@PEBD@Z)
ocl.obj : error LNK2001: unresolved external symbol "enum cv::utils::logging::LogLevel __cdecl cv::utils::logging::getLogLevel(void)" (?getLogLevel@logging@utils@cv@@YA?AW4LogLevel@123@XZ)

**Comment by alalek** [comment]
You must re-run CMake after code update
