### ISSUE TITLE
DNN scale_layer issue

### ISSUE THREAD

**Issue by BAILOOL** [opencv/opencv#10382]
##### System information (version)

- OpenCV => 3.3.1-dev
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 5.4.0

##### Detailed description

When using Caffe [implementation of Squeeze-and-Excitation](https://github.com/shicai/SENet-Caffe) getting the following issue:
```
OpenCV Error: Assertion failed (blobs.size() == 1 + hasBias) in forward, file opencv/modules/dnn/src/layers/scale_layer.cpp, line 51
```
Seems like Scale layer with no bias in dnn module has an issue. Scale layer for batch normalization (with bias) works well though. I believe this is the layer that causes the problem:
```
layer {
  name: "scale2_1"
  type: "Scale"
  bottom: "conv2_1/x3"
  bottom: "fc2_1/exc"
  top: "scale2_1"
  scale_param {
    axis: 0
    bias_term: false
  }
}
```

##### Steps to reproduce
1. Download prototxt and caffemodel from [this repo](https://github.com/shicai/SENet-Caffe).
2. Set relevant paths to model from Step 1 in [opencv/samples/dnn/caffe_googlenet.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/caffe_googlenet.cpp).
3. Change image input to 225x225x3 in caffe_googlenet.cpp like this:
```
Mat inputBlob = blobFromImage(img, 1.0f, Size(225, 225), Scalar(104, 117, 123), false);  
```

**Comment by dkurt** [comment]
@BAILOOL, thanks! I see the problem. It's a scale of the first `bottom` by values from the second one. Details at http://caffe.berkeleyvision.org/tutorial/layers/scale.html.

**Comment by victor-ludorum** [comment]
Hello @BAILOOL  and @dkurt  I want to work on this issue . Kindly guide me .
@BAILOOL , I have understood your 3rd point .  But 

> Set relevant paths to model from Step 1 in opencv/samples/dnn/caffe_googlenet.cpp.

> 
I don't understand this part . Please elaborate it more .

**Comment by victor-ludorum** [comment]
Hello @BAILOOL and @dkurt  I want to work on this issue . Kindly guide me about this issue .
What should be done to resolve this issue and what are the resources(file) used ?

**Comment by dkurt** [comment]
@victor-ludorum, thanks for your response! Currently OpenCV's [scale layer](https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/scale_layer.cpp) works with a single input and 1 or 2 set of parameters (weights or weights+bias). We need to make it work with two inputs only. This way the second one is used as weights.
Following Caffe's documentation add tests with simple models (2 input layers and a single scale layer).
Finally, test that OpenCV gives the same output as Caffe framework using the model from issue (Caffe is required so you can just open PR and me to check it).

**Comment by victor-ludorum** [comment]
Thanks @dkurt  for your response !! As you have suggested that OpenCV's scale layer is working with single input , Is this line 
`    ScaleLayerImpl(const LayerParams& params)`
Do I have to do modification with this line in [link](https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/scale_layer.cpp#L25) so that it may work with 2 inputs . 

> Following Caffe's documentation add tests with simple models (2 input layers and a single scale layer).
>
 I have also not understood this line . Can you please elaborate it more ..  I have understood what should be done but I need your guidance to do this ..  I need little bit more info .

**Comment by dkurt** [comment]
@victor-ludorum, we need to modify `forward` method. Now it takes a single input blob, weights and optionally biases. In case of 4D input, `output(n, c, h, w) = w(c) * input(b, c, h, w) + b(c)`. In case of 2D input, `output(n, c) = w(c) * input (b, c) + b(c)`. Caffe framework can work with two inputs. There is no weights and biases this way but `output(n, c, h, w) = input2(c) * input1(b, c, h, w)` (or `input1(c) * input2(b, c, h, w)` that we also have to check).

Usage is simple so we can add automatic tests that build `Net` with two inputs and a single `Scale` layer to compare Net's output with an expected one. Like this one: https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_layers.cpp#L275. I mean it isn't necessary to build Caffe to generate reference outputs for this test cases.

Finally we have to check that issue author's model works in OpenCV the same way as using Caffe.

**Comment by victor-ludorum** [comment]
Thanks @dkurt for your response . As **forward** method should be modified . 
In this method we have one parameter **Internals** which I think should be removed so that It has one input parameter and one weight bias . In the method 
```
void forward(std::vector<Mat*> &inputs, std::vector<Mat> &outputs, std::vector<Mat> &internals)
{
        CV_TRACE_FUNCTION();
        CV_TRACE_ARG_VALUE(name, "name", name.c_str());

        for (size_t ii = 0; ii < outputs.size(); ii++)
        {
            Mat &inpBlob = *inputs[ii];
            Mat &outBlob = outputs[ii];

            CV_Assert(inpBlob.size[1] == blobs[0].total());
            if (hasBias)
                CV_Assert(inpBlob.size[1] == blobs[1].total());

            CV_Assert(inpBlob.type() == CV_32F && outBlob.type() == CV_32F);

            for( int cn = 0; cn < inpBlob.size[0]; cn++ )
            {
                for (int n = 0; n < inpBlob.size[1]; n++)
                {
                    float w = blobs[0].at<float>(n);
                    float b = hasBias ? blobs[1].at<float>(n) : 0;
                    Mat outBlobPlane = slice(outBlob, cn, n);
                    Mat inpBlobPlane = slice(inpBlob, cn, n);
                    inpBlobPlane.convertTo(outBlobPlane, CV_32F, w, b);
                }
            }
        }
    }`
```

we have not used **Internals** in this method , so I think it can be removed without having any effect .
By doing this we will make it work with two parameter . Am I correct ??

**Comment by alalek** [comment]
Nope, this method must be implemented with exact this signature (this class is inherited from class with this virtual method).

My suggestion is to start from some appropriate test, which would reproduce failure mentioned in this issue.

**Comment by victor-ludorum** [comment]
Okay @alalek I will do as you have suggested .

**Comment by dkurt** [comment]
@victor-ludorum, `std::vector<Mat*> &inputs` contains any number of inputs.

**Comment by victor-ludorum** [comment]
Oh.. sorry @dkurt I understand , thanks for clarifying .

**Comment by victor-ludorum** [comment]
@dkurt If you don't have any problem,  can you provide your **nickname** of IRC channel or **name** in _Slack-OpenCV_ so that we can discuss there .

**Comment by dkurt** [comment]
@BAILOOL, May I ask you to check the following changes: https://github.com/opencv/opencv/pull/10585? Thank you!

**Comment by dkurt** [comment]
@BAILOOL,
1. Go to OpenCV source folder (assuming that git is initialized)
2. Add a new one remote repository: `git remote add dkurt https://github.com/dkurt/opencv.git`
3. Fetch a branch `git fetch dkurt dnn_weightless_scale`
4. Checkout to it: `git checkout dnn_weightless_scale`
5. Build

**Comment by BAILOOL** [comment]
@dkurt I have checked this modification with several different networks where "Squeeze-and-Excitation" module (i.e. scale_layer as matrix multiplication in opencv) is used. It works perfectly fine.
