### ISSUE TITLE
OpenCV Error: Assertion failed (vc_.isOpened()) in reset

### ISSUE THREAD

**Issue by elhoussine** [opencv/opencv#10380]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => Ubunutu Mate 64Bit
- Compiler => CMake

##### Detailed description

I compiled [super_resolution.cpp](https://github.com/opencv/opencv/blob/master/samples/gpu/super_resolution.cpp), when I run it I issue in opening video file. 

Command: 
`./super_resolution vid.mp4`

Error message: 
`OpenCV Error: Assertion failed (vc_.isOpened()) in reset, file /home/hat/Downloads/opencv-3.3.1/modules/superres/src/frame_source.cpp, line 153
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/hat/Downloads/opencv-3.3.1/modules/superres/src/frame_source.cpp:153: error: (-215) vc_.isOpened() in function reset`

CMakeLists.txt:
`
cmake_minimum_required(VERSION 2.8)
project( super_resolution ) # change this 
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( super_resolution super_resolution.cpp ) # change this
target_link_libraries( super_resolution ${OpenCV_LIBS} )
`

**Comment by berak** [comment]
this sample is using cv::CommandLineParser, so you'll have to call it like:

    ./super_resolution --video=vid.mp4

however, since the inputVideo argument is mandatory, there should be a check for this.
