### ISSUE TITLE
blank screen after login after installing opencv

### ISSUE THREAD

**Issue by elhoussine** [opencv/opencv#10409]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform =>Ubuntu Mate 64 Bit - Kernel 4.14 and 4.10
- Compiler => CMake

##### Detailed description

After installing opencv in my OS using the following steps: 

`sudo apt-get install build-essential
sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt install libopencv-dev`

`git clone https://github.com/opencv/opencv.git
cd opencv
mkdir build 
cd build
sudo cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local 
make -j7
sudo make install 
`

After install, I reboot. After that I get login GUI, I put my credentials and then everything freezes

##### Steps to reproduce

Reinstalled OS, performed opencv installation on fresh OS. Same issue.

**Comment by alalek** [comment]
> sudo apt-get install libopencv-dev

and

>  sudo make install

are not compatible. No idea which tutorial suggests this - it is just wrong to use both.

We don't support remote debugging of issues on custom user platforms, so you need to investigate reason of the problem yourself.
