### ISSUE TITLE
build opencv spend much time

### ISSUE THREAD

**Issue by zhanglaplace** [opencv/opencv#10403]
##### System information (version)

- OpenCV => 3.3.1:
- Operating System / Platform => Windows10 64 Bits:
- Compiler => Visual Studio 2013:
- CUDA => 7.5

##### Detailed description
  Opencv build takes much time .  i using cmake to build the opencv with contrib. but when i using command:
```
  cmake.exe --build . --config Release --target INSTALL
```
  it build takes average 8h, much time cost in build cu.  i build caffe-gpu only 1h,is there any error or overlap step in install ?

**Comment by catree** [comment]
@zhanglaplace 
See here: [Why OpenCV building is so slow with CUDA?](http://answers.opencv.org/question/5090/why-opencv-building-is-so-slow-with-cuda/?answer=5095#post-id-5095).

**Comment by zhanglaplace** [comment]
@catree thanks.
