### ISSUE TITLE
OPENCV_DNN COMPILE ERROR

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#10408]
##### System information (version)

- OpenCV =>2017-12-23
- Operating System / Platform => WINDOWS10 X64
- Compiler => VS2015

##### Detailed description
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'cv::dnn::experimental_dnn_v3::LSTMLayer::setUseTimstampsDim': was declared deprecated	opencv_dnn	modules\dnn\src\layers\recurrent_layers.cpp	140	
Error	C4996	'cv::dnn::experimental_dnn_v3::LSTMLayer::setProduceCellOutput': was declared deprecated	opencv_dnn	modules\dnn\src\layers\recurrent_layers.cpp	146	
Error	C4996	'cv::dnn::experimental_dnn_v3::LSTMLayer::setWeights': was declared deprecated	opencv_dnn	modules\dnn\src\layers\recurrent_layers.cpp	158

**Comment by alalek** [comment]
> deprecated 

These calls should not be used.

To avoid this warning (to hack) try defining CV_DEPRECATED to empty value in your app (via compiler command line or via "#define CV_DEPRECATED" before any OpenCV header include).

**Comment by dbyoung720** [comment]
It is error, not warning. link opencv_dnn error.
It is compile opencv source, not my app.

**Comment by alalek** [comment]
Can't reproduce.
Check these steps of OpenCV build: http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10317

**Comment by dbyoung720** [comment]
CMake VS2017 x64, The problem remains.

**Comment by alalek** [comment]
Our VS2017 build is [here](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc15/builds/5)

You need to investigate the reason of this problem itself (we don't perform "remote" investigation of build problems on custom user systems).

I believe you turn on somewhere threat "warnings as error" option, because C4996 is [warning](https://msdn.microsoft.com/en-us/library/ttcz0bys.aspx) initially.

**Comment by dbyoung720** [comment]
ENABLE_LTO and ENABLE_NOISY_WARNINGS, Cannot be elected.
Compile success.

**Comment by alalek** [comment]
What is about `OPENCV_WARNINGS_ARE_ERRORS` flag?

**Comment by dbyoung720** [comment]
It has nothing to do with this. 
I've never picked this up.
