### ISSUE TITLE
Compiling failiure using C APIs in C program caused by cvdef.h

### ISSUE THREAD

**Issue by qingswu** [opencv/opencv#10405]
I am compiling a C program using opencv's C API, while the problem is caused by
```.cpp
namespace cv { namespace debug_build_guard { } using namespace debug_build_guard; }
```
in cvdef.h introduced in revision f448d75

Some guard is required for C code.

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
> C API

It is not supported anymore, OpenCV is C++ library with classes / exception / etc: #10246

> debug_build_guard

see #9161
