### ISSUE TITLE
cpp-example-stitching fails with very basic images

### ISSUE THREAD

**Issue by eugaz** [opencv/opencv#10415]
Trying to stich these pictures just fails:
```
opencv_version 
3.4.0-dev
```
```
uname
Linux
```
```
wget -O test1.png http://oi64.tinypic.com/atkacg.jpg
wget -O test2.png http://oi65.tinypic.com/ejcvh0.jpg
./cpp-example-stitching --mode scans test*.png --output result.png
[ INFO:0] Initialize OpenCL runtime...
Can't stitch images, error code = 1
```

**Comment by catree** [comment]
Your images do not overlap enough (30% is recommended). Even [Microsoft Ice](https://www.microsoft.com/en-us/research/product/computational-photography-applications/image-composite-editor/) fails on these images.

**Comment by eugaz** [comment]
@catree you are right, after obtaining images with bigger overlap they work perfectly. In any case the images are so perfect that a match should be obtained.
