### ISSUE TITLE
cpp-example-stitching fails to stitch while Adobe Photoshop does it perfectly

### ISSUE THREAD

**Issue by eugaz** [opencv/opencv#10417]
cpp-example-stitching is unable to stitch these two images.
Adobe Photoshop does it perfectly using File -> Scripts -> Load files into stack -> add files -> select all layers -> Edit -> Auto-align layers.

```
wget -O red1.png http://oi64.tinypic.com/i5akc7.jpg
wget -O red2.png http://oi64.tinypic.com/dmpmp1.jpg
```
```
./cpp-example-stitching --mode scans red1.png red2.png --output result.png
[ INFO:0] Initialize OpenCL runtime...
Can't stitch images, error code = 1
```
This is how Adobe Photoshop does the stitching:
http://oi67.tinypic.com/6h1atd.jpg

And this the final image by Photoshop:
http://oi66.tinypic.com/dce8wp.jpg

**Comment by alalek** [comment]
Please avoid reopening issues with similar topics: #10415
Stitching implements some basic algorithms and them may not work on some specific datasets (or on specific cases like yours with scanned documents).

There are no plans to replace this algorithm and/or add features - at least in the form "don't work" without providing enough clear information about wanted changes / algorithms (public article for example).

Usage questions about current algorithm limitations and selection of better algorithm parameters (like AffineBasedEstimator) should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by eugaz** [comment]
That is no excuse. Provided examples are so obvious and good that it should work flawlessly.
