### ISSUE TITLE
[PATCH] Allow IPP IW compiled with manylinux pthread.h

### ISSUE THREAD

**Issue by native-api** [opencv/opencv#10411]
- OpenCV => 3.1
- Operating System / Platform => manylinux 64 Bit
- Compiler => gcc 4.8.2

##### Detailed description

In manylinux environment, compiling IPP IW produces the following error:

    /io/_skbuild/cmake-build/3rdparty/ippicv/ippiw_lnx/src/iw_own.c:136:45: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function)
         if(pthread_mutexattr_settype(&mutAttib, PTHREAD_MUTEX_RECURSIVE) != 0)

The attached patch fixes this the same way as `3rdparty/ittnotify/src/ittnotify/ittnotify_config.h`.

[0001-Defines-needed-for-manylinux-pthread.patch.zip](https://github.com/opencv/opencv/files/1584994/0001-Defines-needed-for-manylinux-pthread.patch.zip)

##### Steps to reproduce

See https://travis-ci.org/native-api/opencv-python/builds/321053239 for build log.

**Comment by mshabunin** [comment]
CC @lupustr3

**Comment by lupustr3** [comment]
@native-api thanks! I will include this fix into the next package update;

**Comment by alalek** [comment]
Resolved by #11541
