### ISSUE TITLE
Can't create layer "data" of type "Input" in function getLayerInstance in dnn.cpp

### ISSUE THREAD

**Issue by prabhundps** [opencv/opencv#10420]
I've trained the GoogleNet model on custom datasets and trying to deploy in raspberry pi for image classification.
Following code for image predictions:
import cv2
net = cv2.dnn.readNetFromCaffe(
'deploy.prototxt',
'cyrrup_googlenet_iter_1110.caffemodel')
frame = cv2.imread('frame.jpg', cv2.IMREAD_GRAYSCALE)
image=cv2.resize(frame, (224, 224))
blob = cv2.dnn.blobFromImage(image,1, (224, 224), (104, 117, 123))
net.setInput(blob)
detections = net.forward()
print(detections)

The following error I'm getting.
_______________________________________________________________________________
OpenCV Error: Unspecified error (Can't create layer "data" of type "Input") in getLayerInstance, file /home/pi/opencv-3.3.0/modules/dnn/src/dnn.cpp, line 365
Traceback (most recent call last):
File "image_detection.py", line 9, in
detections = net.forward()
cv2.error: /home/pi/opencv-3.3.0/modules/dnn/src/dnn.cpp:365: error: (-2) Can't create layer "data" of type "Input" in function getLayerInstance

Will anyone please help me to debug? If required more information I would like to discuss.

Thanks.

**Comment by dkurt** [comment]
Answer is `opencv-3.3.0`. Update your OpenCV or follow https://github.com/opencv/opencv/issues/9651.

**Comment by prabhundps** [comment]
I'm using the following system/ software configuration:
    OpenCV => 3.3.0
    Operating System / Platform => Ubuntu 17.04 LTS
    GCC Compiler =gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0

But still, I'm not able to deploy the model. Please, help me, If you need more information, Please let me know. I'm happy to discuss more.

Thanks.

**Comment by dkurt** [comment]
@prabhundps, Please use http://answers.opencv.org to asking usage questions. Use issues tracker only for reporting bugs ans feature requests.
