### ISSUE TITLE
Dnn blob error

### ISSUE THREAD

**Issue by progfiles** [opencv/opencv#10422]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Android 7
- Compiler => Android Studio

##### Detailed description

After update  to opencv 3.4 I have blob error:
cv::Exception: /build/master_pack-android/opencv/modules/dnn/src/layers/convolution_layer.cpp:907: error: (-215) inputs.size() == (size_t)1 && inputs[0]->size[1] % blobs[0].size[1] == 0 in function virtual void cv::dnn::ConvolutionLayerImpl::forward(std::vector<cv::Mat*>&, std::vector<cv::Mat>&, std::vector<cv::Mat>&)

It is ssd_mobilenet_v1 architecture

**Comment by dkurt** [comment]
@progfiles, Please tell us how to reproduce it. Is https://github.com/opencv/opencv/tree/master/samples/android/mobilenet-objdetect a source of sample? Have you tried to log frame's width and height?

**Comment by progfiles** [comment]
I use the same code.
`Mat blob = Dnn.blobFromImage(frame, IN_SCALE_FACTOR,
                new Size(IN_WIDTH, IN_HEIGHT),
                new Scalar(MEAN_VAL, MEAN_VAL, MEAN_VAL),true,false);     
        net.setInput(blob);
        Mat detections = net.forward();`
After run `net.forward()` I caught cv::Exception. But in opencv 3.1 it was without exception.

frame is not empty.

**Comment by vdurrmann** [comment]
I caught the same exception on Windows 64bits.
Frame isn't empty and every thing's fine with opencv 3.1 too.

**Comment by Msmhasani** [comment]
I too have the problem with dnn::blobFromImage of opencv 3.4 in c++.  It takes the input image and return a Mat with row=-1 and col=-1 !!! :( 
Is it a bug in opencv 3.4 ???

**Comment by dkurt** [comment]
@progfiles, I can't reproduce it neither with MobileNet-SSD from Caffe nor with MobileNet-SSD from TensorFlow (see references at [mobilenet_ssd_python.py](https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py)). OpenCV 3.4, Android Studio 3.0

BTW Dnn was replaced from opencv_contrib repository only at OpenCV 3.3

**Comment by dkurt** [comment]
I'm closing this issue due no response.
