### ISSUE TITLE
Build for Android with a Mac

### ISSUE THREAD

**Issue by hannesa2** [opencv/opencv#10434]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Mac OS 10.13.2 / Android
- Compiler => cmake
##### Build Android

I use on most recent stable Android environment
```
export ANDROID_NDK=~/Development/android-ndk-r10b
cd ~/opencv
mkdir build && cd build
cmake .. 
```
... this works, fine !

```
cd ~/opencv/platform
./scripts/cmake_android_arm.sh
```
it deliveres

> CMake Error at platforms/android/android.toolchain.cmake:813 (message):
>   Specified Android native API level 'android-9' is not supported by your
>   NDK/toolchain.
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CMakeDetermineSystem.cmake:91 (include)
>   CMakeLists.txt:117 (project)

ok, I set this

```
export ANDROID_NATIVE_API_LEVEL=14
./scripts/cmake_android_arm.sh
```

and now I see
> CMake Error at platforms/android/android.toolchain.cmake:813 (message):
>   Specified Android native API level 'android-14' is not supported by your
>   NDK/toolchain.

I hope someone has a hint for me, how to solve this

**Comment by alalek** [comment]
Almost all of these scripts from "platform/scripts" sub-directory are outdated (and has very specific requirements, perhaps NDK 8 or something like that).

For Android build try these [steps](http://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack) instead.

**Comment by hannesa2** [comment]
### Thank you for the fast response
My main goal, is to build and run Android examples, and I see there is a lot of outdated stuff there, eg Eclipse projects, now I know scripts are not working ... and yes, I want to provide a PR to show it running with Android Studio

I spent three days without any success, because of that much noise and time consuming, wrong-promising build steps. 
To be honest, the project is in my point of view in a bad condition for Android

### Your recommended way to search for a solution
To see it positive, with this link http://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack I assume you are able to build (maybe ?). But I don't understand and don't see how do you build it, **no command is found**. 

But eg. this [step](http://pullrequest.opencv.org/buildbot/builders/master-contrib_ARMv7-lin/builds/10317) is green but when you look into [logs](http://pullrequest.opencv.org/buildbot/builders/master-contrib_ARMv7-lin/builds/10317/steps/cmake/logs/CMakeError) is has **tons of errors**. wtf 👎  

### I want to make it work
I want to make it build for Android with PR's, but someone has to help me.

Anyway, what I miss here, is something like Travis, and I want to help, but I can't build it on my machine. This should be the first step

**Comment by alalek** [comment]
CMakeError's errors are just failed checks. CMake scripts uses his information to reconfigure build settings.

Build command and log example is [here](http://pullrequest.opencv.org/buildbot/builders/master-contrib_pack-contrib-android/builds/10317/steps/build%20sdk/logs/stdio).

Android Studio support discussion is here: #5003

Usage / build questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
