### ISSUE TITLE
Unknown layer type Cast in op ToFloat in function populateNet(Tensorflow detection api ssd+mobilenet)

### ISSUE THREAD

**Issue by kdouc** [opencv/opencv#10431]
I'm training a object detection model use tensorflow detection api. Now i want to use it in opencv 3.4.0(3.3.1).
I have test the https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md and use https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt 
this well work well. But in my model, i have changed the size and others,my config is:https://github.com/kdouc/example/blob/master/pipeline.config
So,when i run my model,got 👍 
ToFloat:Cast(image_tensor)
DstT:[ ]
SrcT:[ ]
the same problem like https://github.com/opencv/opencv/issues/9830,
and i have try to use ssd_mobilent_v1_coco.pbtxt which from frozen.pb,but the same problems.
So is there any way to got a "pbtxt" like https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt . Which don't include ToFloat node?
waiting for your help!

**Comment by dkurt** [comment]
@kdouc, please share a model. It's hard to solve without ways to reproduce.

**Comment by kdouc** [comment]
@dkurt Thanks,this is my model and files
https://www.dropbox.com/s/86h7vqgrx6arhx6/Dropbox%20%E4%BD%BF%E7%94%A8%E5%85%A5%E9%97%A8.pdf?dl=0

**Comment by dkurt** [comment]
@kdouc, there is no problem for me:
```python
import cv2 as cv
net = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb',
                                   'ssd_mobilenet_v1_coco.pbtxt')
```
Model is imported fine. One and only issue is an updated aspect ratios. We need to match them to Caffe-like `PriorBox` layer attributes. I guess it's better to use http://answers.opencv.org for it and close this issue.

**Comment by dkurt** [comment]
@kdouc, May I ask you to test your model with PR https://github.com/opencv/opencv/pull/10676?

Please use the following text graph for it: [ssd_mobilenet_v1_issue_10431.txt](https://github.com/opencv/opencv/files/1659830/ssd_mobilenet_v1_issue_10431.txt)

Proposals' widths and heights received by the following script:
```python
from math import sqrt

min_scale = 0.08
max_scale = 0.95
num_layers = 6
aspect_ratios = [1.0, 2.0, 0.5]

scales = [min_scale + (max_scale - min_scale) * i / (num_layers - 1) for i in range(num_layers)] + [1.0]

print 'Layer PriorBox:'
print min_scale * 0.5, min_scale * 0.5
print min_scale * sqrt(2.0), min_scale / sqrt(2.0)
print min_scale * sqrt(0.5), min_scale / sqrt(0.5)

for i in range(len(scales) - 1):
    print ''
    print 'Layer PriorBox_%d:' % (i + 1)
    for ar in aspect_ratios:
        print scales[i] * sqrt(ar), scales[i] / sqrt(ar)
    print sqrt(scales[i] * scales[i + 1]), \
          sqrt(scales[i] * scales[i + 1])
```

Unfortunately I don't know what objects were in training dataset. If you told me I could attach a test image.
