### ISSUE TITLE
pyopencv_custom_headers.h: pyopencv_dnn in opencv, not opencv_contrib

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#10430]
Hi!
I was just building OpenCV v3.4 with contrib and my build couldn't find an include file.

in `build/modules/python3/pyopencv_custom_headers.h`, there was this line:

`#include "P:/opencv_contrib/modules/dnn/misc/python/pyopencv_dnn.hpp"`

what should be there is

`#include "P:/opencv/modules/dnn/misc/python/pyopencv_dnn.hpp"`

I couldn't determine how that line is generated exactly. I've narrowed it down to `opencv/modules/python/bindings/CMakeLists.txt`

I hope that's not an artefact of my just git pulling and rebuilding...

**Comment by dkurt** [comment]
@crackwitz, keep the same states of OpenCV and opencv_contrib. Use master branches of both repositories or the same release tags.
In the future use http://answers.opencv.org to asking build/install/usage questions. Any issue should has steps to reproduce if it's a bug report.
