### ISSUE TITLE
Explaination for build_sdk.py

### ISSUE THREAD

**Issue by hannesa2** [opencv/opencv#10448]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Mac

##### Detailed description

I try to build OpenCV for Android by my own on my Mac, inspired by this [log](http://pullrequest.opencv.org/buildbot/builders/master-contrib_pack-contrib-android/builds/10317/steps/build%20sdk/logs/stdio) I installed the exact NDK `android-ndk-r10e` 

and I was forced to install `ninja` by `brew install ninja`
but currently I see 

> CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set

But I need some explanation for 
`buildenv  python ../opencv/platforms/android/build_sdk.py --build_doc --extra_pack 2.4.13:/opt/android/pack_2.4/ . ../opencv`

What is
* `buildenv` how does it looks like ?
* `--extra_pack` what is the content of `/opt/android/pack_2.4/` ?
* how to get rid of  `CMAKE_MAKE_PROGRAM is not set` ?

**Comment by alalek** [comment]
- buildenv: standard ANDROID_SDK / ANDROID_NDK / NDKROOT / Java env variables
- ignore `--extra-pack`: it is for bundling OpenCV 2.4 into OpenCV Manager for Android package (deprecated component)
- try cleaning build directory, check that "ninja" command works from terminal (adjust PATH env variable if required)

**Comment by hannesa2** [comment]
Thank you for the clarification. I only works on command line, and `ninja` works on any directory which contains a `build.ninja`file.
With `python ../opencv/platforms/android/build_sdk.py . ../opencv` I get 

> Executing: ['cmake', '-GNinja', "-DCMAKE_TOOLCHAIN_FILE='/Users/hannes/git/openCV/opencv/platforms/android/android.toolchain.cmake'", '-DWITH_OPENCL=OFF', '-DWITH_CUDA=OFF', '-DWITH_IPP=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DBUILD_ANDROID_EXAMPLES=ON', '-DINSTALL_ANDROID_EXAMPLES=ON', '-DANDROID_STL=gnustl_static', '-DANDROID_NATIVE_API_LEVEL=9', "-DANDROID_ABI='armeabi-v7a with NEON'", '-DWITH_TBB=ON', '-DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.8', '/Users/hannes/git/openCV/opencv', '-DNDK_CCACHE=ccache', '-DBUILD_TESTS=ON', '-DINSTALL_TESTS=ON']
> CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

Any help is welcome !

**Comment by alalek** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Ninja". 

Problem is here. CMake is not able to find it.

Does "ninja --version" command work? (without any additional paths)

BTW, Also you could try removing option "-GNinja" from the build script (CMake should use "make" tool instead)

**Comment by hannesa2** [comment]
`ninja --version` works properly.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3314607/34418997-9b0d9036-ec01-11e7-8a6e-b234fffe20f5.png">

As suggested, I removed both lines `-GNinja` from `./opencv/platforms/android/build_sdk.py`

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3314607/34419154-952cb222-ec02-11e7-8b7e-e646233e6eec.png">

.. yes it starts ! But after 30 seconds, I see after configuring and generation this now

> --   Install to:                    /Users/hannes/git/openCV/build/o4a/install
> -- -----------------------------------------------------------------
> -- 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/hannes/git/openCV/build/o4a
> Executing: ['ninja']
> ninja: error: loading 'build.ninja': No such file or directory
> Traceback (most recent call last):
>   File "../opencv/platforms/android/build_sdk.py", line 303, in <module>
>     builder.build_library(abi, do_install)
>   File "../opencv/platforms/android/build_sdk.py", line 149, in build_library
>     execute(["ninja"])
>   File "../opencv/platforms/android/build_sdk.py", line 20, in execute
>     raise Fail("Child returned: %s" % retcode)
> __main__.Fail: Child returned: 1

Why is there `ninja` used, when it build without (more) too ?  It adds more complexity, and as I see OpenCV has enough of it

**Comment by hannesa2** [comment]
after the next change
<img width="448" alt="image" src="https://user-images.githubusercontent.com/3314607/34419309-54955182-ec03-11e7-80fa-210b43509c22.png">

I run into this

> -- Installing: /Users/hannes/git/openCV/build/o4a/install/sdk/etc/valgrind_3rdparty.supp
> CMake Error at 3rdparty/cpufeatures/cmake_install.cmake:41 (file):
>   file INSTALL cannot find
>   "/Users/hannes/git/openCV/build/o4a/3rdparty/lib/armeabi-v7a/libcpufeatures.a".
> Call Stack (most recent call first):
>   cmake_install.cmake:110 (include)
> 
> 
> Traceback (most recent call last):
>   File "../opencv/platforms/android/build_sdk.py", line 303, in <module>
>     builder.build_library(abi, do_install)
>   File "../opencv/platforms/android/build_sdk.py", line 151, in build_library
>     execute(["cmake", "-DCOMPONENT=%s" % c, "-P", "cmake_install.cmake"])
>   File "../opencv/platforms/android/build_sdk.py", line 20, in execute
>     raise Fail("Child returned: %s" % retcode)
> __main__.Fail: Child returned: 1

Any ideas ?

**Comment by alalek** [comment]
"next" change with "ninja" should be "make" (or "cmake --build .")

**Comment by hannesa2** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/3314607/34419742-e12323a2-ec05-11e7-881a-cb5140a337cd.png">

Yes ! It builds now. 👍 
Make it sense to make a PR with my changes, or is it just for "private purpose" ?

**Comment by alalek** [comment]
"ninja" is faster than "make", so we prefer to use it. Usually there are no problems to properly install "ninja".

**Comment by hannesa2** [comment]
Next issue is how to specify `lib_target_sdk_target` ?

> [ 91%] Generating OpenCV Android library project. SDK target: lib_target_sdk_target-NOTFOUND
> *************************************************************************
> The "android" command is deprecated.
> For manual SDK, AVD, and project management, please use Android Studio.
> For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
> *************************************************************************
> Invalid or unsupported command "--silent create lib-project --path /Users/hannes/git/openCV/build/o4a --target lib_target_sdk_target-NOTFOUND --name OpenCV --package org.opencv"
> 
> Supported commands are:
> android list target
> android list avd
> android list device
> android create avd
> android move avd
> android delete avd
> android list sdk
> android update sdk
> make[2]: *** [build.xml] Error 2
> make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "../opencv/platforms/android/build_sdk.py", line 303, in <module>
>     builder.build_library(abi, do_install)
>   File "../opencv/platforms/android/build_sdk.py", line 149, in build_library
>     execute(["make"])
>   File "../opencv/platforms/android/build_sdk.py", line 20, in execute
>     raise Fail("Child returned: %s" %

**Comment by alalek** [comment]
I believe this can be fixed with old Android SDK only (we using some snapshot from 2015/2016 year):
- try checking "Get just the command line tools" on this page: https://developer.android.com/studio/index.html#downloads

BTW, modern version of "build tools" component requires Java 8.

Also you could try these changes: #10288

**Comment by hannesa2** [comment]
My motivation/vision is to make is usable out of the box with Android Studio 3 without copy anything somewhere. (or at least to help to go in this direction)

But when I see the spirit in #10288 I've no chance to do so, so there is no need anymore to understand exactly the current build process and help to improve it.

Currently I'm a copy-guy as all other does. -sad-

If there is any change in this spirit, I hope I will mention it and I will help to improve it.
What should be done here for Android
* any commit should be tested **prior** merge for all platforms with eg Travis, like in Tensorflow
* build an Android lib and deploy to jcenter or similar
* Android sample project with Android Studio
* no delivery with zip, just jcenter or similar to have something like `implements "com.opencv.lib:3.4.0"` in _build.gradle_
* no generation of *.java files

**Comment by mshabunin** [comment]
@hannesa2 , please check this issue: #5003

**Comment by sergiomarquesmoura** [comment]
@hannesa2 could you build it in the end?

**Comment by hannesa2** [comment]
sorry no, even fork https://github.com/10imaging/opencv with command `build.sh` shows me

> [ 98%] Generating src/org/opencv/engine/OpenCVEngineInterface.aidl
> [ 98%] Generating OpenCV Android library project. SDK target: lib_target_sdk_target-NOTFOUND
> *************************************************************************
> The "android" command is deprecated.
> For manual SDK, AVD, and project management, please use Android Studio.
> For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
> *************************************************************************
> Invalid or unsupported command "--silent create lib-project --path /Users/hannes/git/openCV/opencv/build/android/debug/arm7 --target lib_target_sdk_target-NOTFOUND --name OpenCV --package org.opencv"

**Comment by mshabunin** [comment]
@hannesa2 , make sure you have set `ANDROID_SDK` and `ANDROID_NDK` environment variables correctly. Please attach the output of your script here so that someone could take a look at the details.

**Comment by victorv** [comment]
@hannesa2 I fixed this by always using older tools but that is a hassel so I am writing a custom script to handle creating the library on the command line.
