### ISSUE TITLE
Make a OCR with KNN. Error

### ISSUE THREAD

**Issue by a9336** [opencv/opencv#10440]
Hello

I'm implementing an OCR with a KNN, and it's popping up - and the following error:

Assertion failed (test_samples.type() == 5 && test_samples.cols == samples.cols) in findNearest, file C:\opencv_src\modules\ml\src\knearest.cpp, line 325

What could be the problem?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
