### ISSUE TITLE
cv::StereoBM compute error when use fixed type: float?

### ISSUE THREAD

**Issue by iamyuiwong** [opencv/opencv#10451]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => ubuntu 16.04
- Compiler => gcc

##### Steps to reproduce

```cpp
cv::Mat_<float> disparity32f;
blockMatcher->compute(leftRect, rightRect, disparity32f);

/*then error:
OpenCV Error: Assertion failed (type == (((0) & ((1 << 3) - 1)) + (((1)-1) << 3)) || type == (((3) & ((1 << 3) - 1)) + (((1)-1) << 3))) in filterSpeckles, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/calib3d/src/stereosgbm.cpp, line 2432*/
```
And I tried below lines and solved:
> <https://github.com/opencv/opencv/blob/3542c98d4524e3db268efeb8a15c56f76a4f2add/modules/calib3d/src/stereobm.cpp#L1101>: `int const disp_shift = DISPARITY_SHIFT_16S;`
> <https://github.com/opencv/opencv/blob/3542c98d4524e3db268efeb8a15c56f76a4f2add/modules/calib3d/src/stereobm.cpp#L1157>: `CV_32S` -> `CV_16S`

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

This message means that current type (float?) is not supported (by design).
