### ISSUE TITLE
A question for the release of cv::Mat

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#10462]
does the following code delete[] the original data?

uchar *data = new uchar[4];
for (int i = 0; i < 4; ++i)	data[i] = i;
cv::Mat img(2, 2, CV_8UC1, data);
img.release();

**Comment by alalek** [comment]
No.
It is developer responsibility to control lifetime of passed "void*" data, `cv::Mat` here is just a "view" on it.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
