### ISSUE TITLE
cpp-example-stitching newline missing when the command exits

### ISSUE THREAD

**Issue by eugaz** [opencv/opencv#10461]
After running a command, the shell prompt is at the same line than the ended command, instead of being on a new line. Example:

```
linux@linux:~/opencv$ ./build/bin/cpp-example-stitching
Images stitcher.

Usage :
/home/linux/opencv/build/bin/cpp-example-stitching [Flags] img1 img2 [...imgN]

Flags:
  --d3
      internally creates three chunks of each image to increase stitching success  --try_use_gpu (yes|no)
      Try to use GPU. The default value is 'no'. All default values
      are for CPU mode.
  --mode (panorama|scans)
      Determines configuration of stitcher. The default is 'panorama',
      mode suitable for creating photo panoramas. Option 'scans' is suitable
      for stitching materials under affine transformation, such as scans.
  --output <result_img>
      The default is 'result.jpg'.

Example usage :
/home/linux/opencv/build/bin/cpp-example-stitching --d3 --try_use_gpu yes --mode scans img1.jpg img2.jpglinux@linux:~/opencv$
```
"linux@linux:~/opencv$" should be in a newline.

**Comment by alalek** [comment]
Perhaps this patch could help:

```.diff
          "  --d3\n"
-         "      internally creates three chunks of each image to increase stitching success"
+         "      internally creates three chunks of each image to increase stitching success" << std::endl <<
          "  --try_use_gpu (yes|no)\n"
...
-         "Example usage :\n" << argv[0] << " --d3 --try_use_gpu yes --mode scans img1.jpg img2.jpg";
+         "Example usage :" << std::endl <<
+         argv[0] << " --d3 --try_use_gpu yes --mode scans img1.jpg img2.jpg" << std::endl;
}

**Comment by victor-ludorum** [comment]
Hello @eugaz  and @alalek  I am new to OpenCV . I want to work on this issue . Please guide me how to start .

**Comment by eugaz** [comment]
cpp-example-stitching_detailed works as intended, just copy from it. Couldn't check all the examples or opencv commands, but it's work checking.

**Comment by victor-ludorum** [comment]
Hello @eugaz thanks :blush: for your reply . But sorry to say I didn't get much idea . Can you please provide me the module on which I have to work . And the things which I have to do to solve the issue . As you have suggested I have read [cpp-example-stiching-detailed.cpp](https://github.com/opencv/opencv/blob/master/samples/cpp/stitching_detailed.cpp) . Is it what I have to study for solving this issue . You have also mentioned 

> just copy from it. Couldn't check all the examples or opencv commands, but it's work checking.

> 
I didn't understand much about this . Please elaborate .
Sorry for bothering you again .
>

**Comment by eugaz** [comment]
@victor-ludorum here
https://github.com/opencv/opencv/blob/master/samples/cpp/stitching.cpp#L57

replace

`img2.jpg"`

with

`img2.jpg\n"`

**Comment by victor-ludorum** [comment]
Okay @eugaz  Thank you very much 😊

**Comment by eugaz** [comment]
Also here
https://github.com/opencv/opencv/blob/master/samples/cpp/stitching.cpp#L47

replace

`success"`

with

`success\n"`

**Comment by victor-ludorum** [comment]
@eugaz  Okay I will commit this change too . Thanks 😊
