### ISSUE TITLE
Find Solution...I can Change cross-bar Video Input in Capture Video By Writing multi Line Code And Rebuild the Videoio Dll.

### ISSUE THREAD

**Issue by Ehsan61** [opencv/opencv#10471]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 32 Bit 7
- Compiler => Visual Studio 2012

- OpenCV => :grey_question: I found Solution...
- Operating System / Platform => :grey_question: Win 7
- Compiler => :grey_question: Visual Studio 2012

##### Detailed description

I Modify Coding of videoio library for Access to Crossbar of VideoInput for Change Input pin Correctly.
i write some line of code to send index of input pin to lower layer of videoio library and Rebiuld it to capable of feature.
by this feature you can change video input pin of capture card very nice & simply correctly in windows and Directshow backend.

**Comment by wanghanmin** [comment]
Yes.  I added one prop and some code and it runs ok on my cv710 capture card.

**Comment by Ehsan61** [comment]
Ok.tanx...it should be in new version of opencv...for example 3.5 or 3.6
release.
