### ISSUE TITLE
bg_subtraction documentation needs update

### ISSUE THREAD

**Issue by cameronbergh** [opencv/opencv#10475]
##### System information (version)

ubuntu 17.10
opencv 3.1.0

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

the documentation page : https://docs.opencv.org/3.3.0/db/d5c/tutorial_py_bg_subtraction.html
shows an example that doesnt work but can be easily fixed:

`import numpy as np
import cv2
cap = cv2.VideoCapture('vtest.avi')
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3))
fgbg = cv2.createBackgroundSubtractorGMG()
while(1):
    ret, frame = cap.read()
    fgmask = fgbg.apply(frame)
    fgmask = cv2.morphologyEx(fgmask, cv2.MORPH_OPEN, kernel)
    cv2.imshow('frame',fgmask)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()`

##### Steps to reproduce

by running the above script i get an error

>     fgbg = cv2.createBackgroundSubtractorGMG()
AttributeError: module 'cv2' has no attribute 'createBackgroundSubtractorGMG'

but by changing that line to
`fgbg = cv2.bgsegm.createBackgroundSubtractorGMG()`
the error is fixed

**Comment by berak** [comment]
this is already corrected [in the master docs](https://docs.opencv.org/master/db/d5c/tutorial_py_bg_subtraction.html), however, [the c++ version](https://docs.opencv.org/master/d1/dc5/tutorial_background_subtraction.html) still has it wrong

**Comment by clockwiser** [comment]
Need to install opencv-contrib-python.

1.remove all opencv related packages installed.
2.pip install opencv-contrib-python

See below link.
https://pypi.org/project/opencv-contrib-python/
