### ISSUE TITLE
Faster RCNN in Python

### ISSUE THREAD

**Issue by PhoenixDai** [opencv/opencv#10476]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 10 x64
- Compiler => VS2015

##### Detailed description

I'm trying to reimplement the Faster RCNN example (https://github.com/opencv/opencv/blob/master/samples/dnn/faster_rcnn.cpp) in Python but got a bug in the net.forward() function call. Can someone take a look and help me out? Thanks much!

##### Steps to reproduce
 ```.py
from __future__ import print_function
import numpy as np
import cv2 as cv
from cv2 import dnn
import timeit

classNames = [ "__background__", "aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
kInpWidth = 800
kInpHeight = 600

protoPath = "faster_rcnn_vgg16.prototxt"
modelPath = "VGG16_faster_rcnn_final.caffemodel"
imagePath = "street.jpg"
confThreshold = 0.8

net = dnn.readNetFromCaffe(protoPath, modelPath)
img = cv.imread(imagePath)
img = cv.resize(img, (kInpWidth, kInpHeight))

blob = dnn.blobFromImages(img, 1.0, None, (102.9801, 115.9465, 122.7717), False, False)
print("Input:", blob.shape, blob.dtype)
# Input: (1L, 3L, 600L, 800L) float32
imInfo = np.array([600, 800, 1.6])
net.setInput(blob,"data")
net.setInput(imInfo, "im_info")

detections = net.forward()
 ```
When it runs to the last line, I got this: 
**error: C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\layers\detection_output_layer.cpp:413: error: (-215) inputs[3]->dims == 4 in function cv::dnn::DetectionOutputLayerImpl::forward**

**Comment by dkurt** [comment]
@PhoenixDai, `imInfo` should be a matrix with 1 row and 3 columns of type `np.float32`.

**Comment by PhoenixDai** [comment]
@dkurt Thanks a lot for your reply! It works! Here is the updated imInfo:
``` .py
imInfo = np.array([600, 800, 1.6]).reshape([1,3]).astype('float32')
```

**Comment by PhoenixDai** [comment]
For those who may have interest on the Python version, here is the code: https://github.com/PhoenixDai/Faster_RCNN_OpenCV_Python

**Comment by huazai-1994** [comment]
hello，I have met  the same problem with you .Have you got the ways to handle it .
