### ISSUE TITLE
No rule to make target 'modules/dnn/attr_value.pb.cc'

### ISSUE THREAD

**Issue by basvandijk** [opencv/opencv#10474]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => NixOS / x86_64
- Compiler => GCC-6.4.0

##### Detailed description

I would like to use my system installed protobuf compiler. However if I enable the following cmake flags:

```
-DBUILD_PROTOBUF=OFF
-DPROTOBUF_UPDATE_FILES=ON
```

the build fails with:

```
Scanning dependencies of target gen_opencv_python_source
make[2]: *** No rule to make target 'modules/dnn/attr_value.pb.cc', needed by 'modules/python_bindings_generator/pyopencv_generated_include.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:15869: modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all] Error 2
```

If I remove those flags the build succeeds.

**Comment by alalek** [comment]
Workaround: run separate build of "opencv_dnn" first (before 'all' target).

**Comment by basvandijk** [comment]
Thanks!
