### ISSUE TITLE
SIFT float option

### ISSUE THREAD

**Issue by varunagrawal** [opencv/opencv#10472]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => All

##### Detailed description

Can we add an option to SIFT to return float values similar to how VLFeat's SIFT implementation does?

**Comment by alalek** [comment]
SIFT descriptor is already [32F float type](https://github.com/opencv/opencv_contrib/blob/3.4.0/modules/xfeatures2d/src/sift.cpp#L1191).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by varunagrawal** [comment]
Thanks @alalek
