### ISSUE TITLE
OpenCV flagged by Windows Defender and on VIrus Total before it finished downloading.

### ISSUE THREAD

**Issue by d3m3ntia** [opencv/opencv#10484]
I downloaded OpenCV from https://github.com/opencv/opencv/archive/master.zip.
As the file was downloading it got flagged by windows defender.

Here's the virus total:
https://www.virustotal.com/#/file/709f84981468c8f5e458bcd4b1e960b3bbb3a177f2bcb9093e707133d0c89e3b/detection

The download didn't finish as WD quarantined it before it could.
The non-.part exe file didn't get flagged

I don't believe the program is a virus, and this may just be a false positive. Perhaps someone could provide some insight?

**Comment by alalek** [comment]
The first link is not corresponding to analyzed file report (it is "opencv-3.4.0-vc14_vc15.exe" from [here](https://github.com/opencv/opencv/releases/tag/3.4.0))

**Comment by d3m3ntia** [comment]
Maybe I made a mistake, I thought I downloaded it from the Main page. I'll check my browser history and get back to you.

**Comment by alalek** [comment]
This file is archive with attached 7-Zip SFX "self-extracted executable" (with embedded OpenCV icon).

SFX file has no detections: https://www.virustotal.com/#/file/c1191b56081a31b2d1e75982ac59909f82b6a3bd7f6e92e96304c7fc8a50e6a9/detection
```
$ dd bs=166400 count=1 if=opencv-3.4.0-vc14_vc15.exe of=7z_opencv.sfx
$ sha256sum 7z_opencv.sfx 
c1191b56081a31b2d1e75982ac59909f82b6a3bd7f6e92e96304c7fc8a50e6a9  7z_opencv.sfx
```

"Clean" archive has no detections too: https://www.virustotal.com/#/file/cd00c6858e2016806b70094693f781272b1722adae044a90da48e942c8fc8b60/detection
(remove 166400 bytes from beginning of file, result file should start from "7z" signature)

BTW, You can avoid running of this executable by using [7-Zip tools](http://www.7-zip.org/download.html) and open this ".exe" as regular archive (But there are several inner binaries of OpenCV library)

**Comment by d3m3ntia** [comment]
I re-downloaded it from the link and it got flagged by windows defender again.

Here's a detailed report:
http://www.geekstogo.com/forum/topic/369773-opencv-windows-defender-flags-opencv-340-vc14-vc15exepart-as-malware-virus-total-has-2-flags/

**Comment by alalek** [comment]
I have added "opencv-3.4.0-vc14_vc15.7z" file to [3.4.0 release](https://github.com/opencv/opencv/releases/tag/3.4.0).
To open this archive you can use 7-Zip from [here](http://www.7-zip.org/download.html) or other archive tools with 7-Zip extraction support.

**Comment by d3m3ntia** [comment]
The issue is that it is being flagged by Virus Total and Windows Defender. 
If you feel like it's not an issue and just a false positive feel free to close the thread. I can find numerous workarounds to get it installed. I just want to confirm a false positive through trusted sources first.

**Comment by jimfcarroll** [comment]
I just got the same thing. Windows Defender scanned `opencv-3.4.0-vc14_vc15.exe`

![image](https://user-images.githubusercontent.com/372696/34675722-7a8d3a0a-f458-11e7-9f64-3922f972723b.png)

**Comment by jimfcarroll** [comment]
I just got the same thing. If anyone is interested. You can open the .exe file with 7zip, which is what I do anyway, but I'm not sure how to tell if this is a false positive.

![image](https://user-images.githubusercontent.com/372696/34675808-b87e59f2-f458-11e7-82c7-e80971486b7c.png)

**Comment by anotherlizwong** [comment]
Do we have any follow up if this is a false positive?

**Comment by iBicha** [comment]
I'm getting `modules/ts/src/ts_gtest.cpp` flagged by avast for some reason.

**Comment by daxtron2** [comment]
Just ran into this issue downloading from opencv.org, flagged as malicious by my company's antivirus. 
[virus total report here](https://www.virustotal.com/gui/file/c473dad05d49570b11584bed7b1f1ef4743d64bacb03f5e5f9b384aaa18512d2/details
)

**Comment by alalek** [comment]
> File size
> 15.75 KB

Downloaded file is corrupted.
The real size of `opencv-3.4.1-vc14_vc15.exe` is about 180Mb.
Please provide direct link URL ("opencv.org" at this moment doesn't host archive files, it just redirects on SF.net).

**Comment by minekid58** [comment]
opencv.org/releases
