### ISSUE TITLE
Comment of Read Method in core.hpp file

### ISSUE THREAD

**Issue by victor-ludorum** [opencv/opencv#10487]
In this [file](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp) ,  the method 
     CV_WRAP virtual void read(const FileNode& fn) { (void)fn; }
here , the comment says that  _Reads algorithm parameters from a file storage_ in [line](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L3101) but in the function parameter it has mentioned as **FileNode** . Can anyone explain how it is reading from file storage ??

**Comment by csukuangfj** [comment]
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L3103

This member function is virtual and its implementation is nearly empty, so it should be implemented by its subclasses.

It is YOUR responsibility to implement this function according to your algorithm.

**Comment by victor-ludorum** [comment]
Thank you very much @csukuangfj for your great explanation . I have understood how it is reading from file storage . But one thing I want to ask shouldn't the comment be _Reads algorithm parameters from a **file node**_ as in [this](https://github.com/opencv/opencv/blob/master/modules/features2d/include/opencv2/features2d.hpp#L1134) and [this](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L2509) . May be I am wrong , but I just want to ask to clarify my doubt

**Comment by csukuangfj** [comment]
@victor-ludorum 

Yes, you are right. Maybe the original author just copied and pasted the comment.

**Comment by alalek** [comment]
FileNode is an iterator of FileStorage class. So I don't see a big problem here.

**Comment by victor-ludorum** [comment]
Okay @alalek and @csukuangfj I have thought comment should be updated. But as it's not a big issue so I will close it without any modification. Thank you very much for your great explanation.
