### ISSUE TITLE
Retrained Mobilenet-SSD model that can get right results in caffe can't detect any object in OPENCV3.4

### ISSUE THREAD

**Issue by yiran-THU** [opencv/opencv#10482]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- Cmake => 3.9.6

##### Detailed description
I retrained Mobilenet-SSD with my own data strictly follow this [guidance](https://github.com/chuanqi305/MobileNet-SSD),  
Then I test my retrained model with python and caffe in ubuntu ,get the right detection result.   
 
![detectin](https://user-images.githubusercontent.com/16274710/34469970-1269859a-ef63-11e7-9e56-4e4694bd4564.jpg)
  
However, when I use the retrained model in OPENCV3.4(windows 10,vs2015), it can't detect any object.  

![test](https://user-images.githubusercontent.com/16274710/34470117-a9e49d86-ef65-11e7-8edc-cc684e6fccf1.jpg)

##### Steps to reproduce

This is my python [script](https://github.com/chuanqi305/MobileNet-SSD/blob/master/demo.py) used in caffe test.  

This is the C++ [script](https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_mobilenet_object_detection.cpp) used in opencv test.

What do I have to solve this problem?

I am looking forward to your reply.
Thank you!
I have tested with different inScaleFactor 、meanVal 、RGB/grayscale 、 resize method , none of them can detect any object.

**Comment by dkurt** [comment]
@yiran-THU, it's just a sample issue. You can use a newer [python script](https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py) or apply changes from https://github.com/opencv/opencv/pull/10483. Thanks!

**Comment by yiran-THU** [comment]
@dkurt 
I have apply changes from [#10483](https://github.com/opencv/opencv/pull/10483)， it is working now.  
Thanks again!
