### ISSUE TITLE
Unable to configure OpenCV to use FFmpeg on Windows

### ISSUE THREAD

**Issue by sergiud** [opencv/opencv#10496]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 15 2017

##### Detailed description

FFmpeg can be natively compiled using MSVC and MSYS. However, OpenCV does not allow FFmpeg to be used directly as under Linux. Instead, it requires the `opencv_ffmpeg*.dll` wrappers to be built first. These wrappers are also downloaded and used unconditionally under Windows.

##### Steps to reproduce

* Compile FFmpeg [using the MSVC toolchain](https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC)
* Configure OpenCV with previously compiled and installed FFmpeg in `CMAKE_PREFIX_PATH`

OpenCV will not use the compiled FFmpeg package. Instead, it will download prebuilt binaries.

**Comment by alalek** [comment]
The first reason for this is license conflict:
- FFmpeg is LGPL (or even GPL, but we don't use such components like x264 encoder)
- OpenCV is BSD
So OpenCV can't be linked FFmpeg library directly.

Second reason: "external" FFmpeg API is not very stable and there is no way to guarantee work with custom FFmpeg prebuilt versions (OpenCV's FFmpeg wrapper has fixed FFmpeg version and it is tested before integration into OpenCV).

You can built your own OpenCV FFmpeg wrapper via Docker (Ubuntu 16.04) from scripts here: https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/master (whole repository is large, consider cloning only required branches/commits: `-b ffmpeg/master --depth=1`)

Current OpenCV wrapper build process also resolves this:
- control FFmpeg build flags, don't allow GPL-only components
- building of FFmpeg extra codecs, like libvpx
- "smooth" integration of [OpenH264](http://www.openh264.org/faq.html)

Anyway, you can try adding some "experimental" build option (like `OPENCV_FFMPEG_WIN32_NATIVE`) to allow `find_package(FFMPEG)` or similar (but perhaps we would not try testing this, so this workaround should not be large to prevent dropping of them).

**Comment by sergiud** [comment]
Even though I do understand the issues with regard to licensing and distribution, don't they apply to platforms other than Windows as well? Just curious.

In any case, I believe the support for components should be symmetric for different platforms. I'll see if I can provide a patch.

**Comment by alalek** [comment]
> other than Windows

Current package set has FFmpeg in Windows package only (Android / iOS - no FFmpeg, Mac/Linux - no packages at all).

**Comment by sergiud** [comment]
I see, thanks!

**Comment by cenit** [comment]
@sergiud did you manage to work on this? I would like to re-use some of your work for the vcpkg’s opencv port, which has some problems as of now and which I would like to build all dependencies if possible (avoiding downloading these prebuilt ffmpeg dlls) 
https://github.com/Microsoft/vcpkg/pull/2764

**Comment by cenit** [comment]
we have a working port of OpenCV linking to external ffmpeg in a [dev branch](https://github.com/Microsoft/vcpkg/tree/dev/roschuma/opencv-use-external-ffmpeg) of `vcpkg`

**Comment by alalek** [comment]
@sergiud @patrikhuber @cenit Could you please take a look on #11636 ?

/cc @peters
