### ISSUE TITLE
Importing cv2 and mxnet with python

### ISSUE THREAD

**Issue by A-Ghosh13** [opencv/opencv#10491]
##### System information (version)

- OpenCV => 3.4.0 - installed using `sudo pip install opencv-python` in Terminal
- Operating System / Platform => OSX 10.13

I've been trying to run a program that imports both mxnet and cv2 with python. However, I can only import mxnet with python, and cv2 only with python2 and python3. I've already looked at this thread(#8039), and it does seem to be a very similar problem, but none of the given solutions are working. Anyone know why I keep getting these error messages?

##### Output:
$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cv2
>>> quit()

$ python2
Python 2.7.14 (default, Sep 25 2017, 09:54:19) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mxnet
>>> quit()

$ python3
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mxnet'

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org , but add some words how OpenCV was installed on your machine.

**Comment by A-Ghosh13** [comment]
Ah, sorry about that! I updated my original question.

**Comment by alalek** [comment]
> pip install opencv-python

We don't maintain/support this package. Check for contacts here: https://pypi.python.org/pypi/opencv-python.

Before trying asking anything else, investigate what python is used by your "pip" command. You have some mess of Python installations.
