### ISSUE TITLE
python FileStorage cannot write integer values

### ISSUE THREAD

**Issue by berak** [opencv/opencv#10506]
- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => vs2008 (opencv-python-contrib from PIP)

```
>>> fs = cv2.FileStorage("my.yml", 1)
>>> a = 3
>>> type(a)
<class 'int'>
>>> fs.write("a",a)
>>> fs.release()

%YAML:1.0
---
a: 3.
```

as of now, only double, String and InputArray are supported from the wrappers, an int will get silently converted to double, which will lead to interesting problems like [this one](https://github.com/opencv/opencv_contrib/issues/1504)

**Comment by Sherlock-hh** [comment]
hi  i 'm trying to use cv2.FileStorage to read the yaml file ,but i just can read the toplevelfile, if i want to read the secondlevel imformation or third level, how should i use the the function?
`f=cv2.FileStorage(path, cv2.FILE_STORAGE_READ)
x=f.getNode("world").mat()
print(x)` 

and here is my yaml file
`%YAML:1.0
---
cameras:
   -
      serial: "814412072248"
      rgb_sensor:
         -
            resolution: !!opencv-Size
               width: 320
               height: 240
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 3.0850497436523438e+02, 0.,
                   1.5880313110351563e+02, 0., 3.0852740478515625e+02,
                   1.1884312438964844e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 640
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1700994873046875e+02, 0.,
                   3.1760626220703125e+02, 0., 6.1705480957031250e+02,
                   2.3768624877929688e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 848
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1700988769531250e+02, 0.,
                   4.2160626220703125e+02, 0., 6.1705480957031250e+02,
                   2.3768624877929688e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 1280
               height: 720
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 9.2551489257812500e+02, 0.,
                   6.3640942382812500e+02, 0., 9.2558215332031250e+02,
                   3.5652935791015625e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
      extrinsics: !!opencv-matrix
         rows: 3
         cols: 4
         dt: d
         data: [ 7.9983204187213397e-01, 4.0108258551824577e-01,
             -4.4654391092999141e-01, 2.1099381913261910e+00,
             -3.7221816099496191e-01, 9.1507540551810185e-01,
             1.5521160665816924e-01, -5.0980956117776877e-01,
             4.7087402287680052e-01, 4.2068537054201452e-02,
             8.8119685245122037e-01, 5.6754999861993582e-01 ]
      depth_intrinsics: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.2469882202148438e+02, 0., 4.2893356323242188e+02, 0.,
             4.2469882202148438e+02, 2.4313613891601563e+02, 0., 0., 1. ]
      depth_units: 1.0000000474974513e-03
      depth_baseline: 5.0041172027587891e+01
   -
      serial: "836612070766"
      rgb_sensor:
         -
            resolution: !!opencv-Size
               width: 320
               height: 240
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 3.0845202636718750e+02, 0.,
                   1.6108213806152344e+02, 0., 3.0847650146484375e+02,
                   1.2156582641601563e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 640
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1690405273437500e+02, 0.,
                   3.2216427612304688e+02, 0., 6.1695300292968750e+02,
                   2.4313165283203125e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 848
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1690399169921875e+02, 0.,
                   4.2616427612304688e+02, 0., 6.1695300292968750e+02,
                   2.4313165283203125e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 1280
               height: 720
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 9.2535607910156250e+02, 0.,
                   6.4324639892578125e+02, 0., 9.2542950439453125e+02,
                   3.6469747924804688e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
      extrinsics: !!opencv-matrix
         rows: 3
         cols: 4
         dt: d
         data: [ 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0. ]
      depth_intrinsics: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.2475683593750000e+02, 0., 4.1967648315429688e+02, 0.,
             4.2475683593750000e+02, 2.4225650024414063e+02, 0., 0., 1. ]
      depth_units: 1.0000000474974513e-03
      depth_baseline: 4.9860118865966797e+01
   -
      serial: "836612071274"
      rgb_sensor:
         -
            resolution: !!opencv-Size
               width: 320
               height: 240
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 3.0896734619140625e+02, 0.,
                   1.5905531311035156e+02, 0., 3.0924566650390625e+02,
                   1.2350983428955078e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 640
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1793469238281250e+02, 0.,
                   3.1811062622070313e+02, 0., 6.1849133300781250e+02,
                   2.4701966857910156e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 848
               height: 480
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 6.1793463134765625e+02, 0.,
                   4.2211062622070313e+02, 0., 6.1849133300781250e+02,
                   2.4701966857910156e+02, 0., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
         -
            resolution: !!opencv-Size
               width: 1280
               height: 720
            intrinsics: !!opencv-matrix
               rows: 3
               cols: 3
               dt: d
               data: [ 9.2690197753906250e+02, 0.,
                   6.3716595458984375e+02, 0., 9.2773693847656250e+02,
                   3.7052947998046875e+02, ., 0., 1. ]
            distortion: !!opencv-matrix
               rows: 5
               cols: 1
               dt: d
               data: [ 0., 0., 0., 0., 0. ]
      extrinsics: !!opencv-matrix
         rows: 3
         cols: 4
         dt: d
         data: [ 9.3029344535778369e-01, 2.6467662241996759e-01,
             -2.5396927189859470e-01, 9.1448983901947212e-01,
             -2.4619202470724713e-01, 9.6377498187327770e-01,
             1.0260249161550350e-01, -1.0412492574655335e-01,
             2.7192571135310212e-01, -3.2925216165139513e-02,
             9.6175482200277440e-01, 5.9432314279661620e-02 ]
      depth_intrinsics: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.2408349609375000e+02, 0., 4.2474038696289063e+02, 0.,
             4.2408349609375000e+02, 2.4232350158691406e+02, 0., 0., 1. ]
      depth_units: 1.0000000474974513e-03
      depth_baseline: 4.9898914337158203e+01
world: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ -9.4322551573318891e-01, -1.9799296647079079e-01,
       2.6669160410098453e-01, -1.0375203966483777e+00,
       2.0763539309947551e-02, 7.6620040531732525e-01,
       6.4226615536465170e-01, -2.5866038425733073e+00,
       -3.3150339652133914e-01, 6.1133928723717978e-01,
       -7.1858873771800302e-01, 3.3395423939400506e+00 ]
reproject: !!reproject-error
   average: 1.6560141492348307e-01
   min: 2.5362843680985473e-07`

I want to get the imformation of "depth_intrinsics" .
I will be very appreciate if you can help me，thanks！
