### ISSUE TITLE
Error  2 while making opencv 3.4

### ISSUE THREAD

**Issue by avinashsingh2** [opencv/opencv#10503]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => ubuntu 14.04
- Compiler => g++

##### Detailed description
hello everyone,

while make operation of opencv 3.4 I am getting error 2:

''
In file included from /home/XXXX/opencv/modules/videoio/src/cap_ffmpeg.cpp:47:0:
/home/XXXX/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In function ‘AVStream* icv_add_video_stream_FFMPEG(AVFormatContext*, AVCodecID, int, int, int, double, int)’:
/home/XXXX/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:1575:21: error: ‘AV_CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope
         c->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
                     ^
/home/XXXX/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In static member function ‘static AVStream* OutputMediaStream_FFMPEG::addVideoStream(AVFormatContext*, AVCodecID, int, int, int, double, AVPixelFormat)’:
/home/XXXX/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:2403:29: error: ‘AV_CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope
                 c->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
                             ^
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

"
this is the error I am getting. what could be wrong?

**Comment by alalek** [comment]
Can't reproduce on our Ubuntu 14.04 builds:
```
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 54.35.1)
--       avformat:                  YES (ver 54.20.4)
--       avutil:                    YES (ver 52.3.0)
--       swscale:                   YES (ver 2.1.1)
--       avresample:                NO
```

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

At first try running from the clean build directory and provide CMake output (see above) / log files. Also run "make VERBOSE=1" to provide complete compiler command line options.
