### ISSUE TITLE
protobuf: build issue

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10510]
Problem is fixed in protobuf upstream (3.2.0+).

With Android NDK 16.1 (gcc):

> FAILED: 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o 
<ndk-bundle>/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++ --sysroot=<ndk-bundle>/sysroot  -DHAVE_PTHREAD=1 -D__OPENCV_BUILD=1 -I3rdparty/protobuf/src -I3rdparty/ippicv/ippicv_lnx/include -I3rdparty/ippicv/ippiw_lnx/include -I. -isystem <ndk-bundle>/sources/cxx-stl/llvm-libc++/include -isystem <ndk-bundle>/sources/android/support/include -isystem <ndk-bundle>/sources/cxx-stl/llvm-libc++abi/include -isystem <ndk-bundle>/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fno-strict-aliasing    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security   -Winit-self -Wpointer-arith   -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -march=i686 -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-sign-compare -Wno-sign-promo -Wno-undef -Wno-ignored-qualifiers -Wno-extra -Wno-unused-function -O2 -DNDEBUG   -DNDEBUG -fPIC -MD -MT 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o -MF 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o.d -o 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o -c 3rdparty/protobuf/src/google/protobuf/util/internal/type_info.cc

```
3rdparty/protobuf/src/google/protobuf/util/internal/type_info.cc:126:33: error: reference to 'map' is ambiguous
   static void DeleteCachedTypes(map<StringPiece, T>* cached_types) {
                                 ^
```

**Comment by oqtvs** [comment]
Alalek can we also update protobuf?

**Comment by alalek** [comment]
>  update protobuf

update protobuf + update all compiled files

> USE_PROTOBUF

There is BUILD_PROTOBUF (defaults to ON) option to switch on system-installed protobuf (need to re-run "protoc" too)

> Can we build dnn module without using protobuf

Currently we can't, but there is some attempts to replace this dependency (see #9106 ).

**Comment by oqtvs** [comment]
Made an attempt to update protobuf to 3.5.1 it is on https://github.com/oqtvs/opencv/tree/updateProtobuf still have to test it, i've only changed protobuf files to newer ones and updated protobuf messages using the locally builded protoc.

**Comment by alalek** [comment]
@oqtvs Looks good to me. Could you create Pull Request with your patch to test it on OpenCV testing infrastructure?
