### ISSUE TITLE
How to increase maximum number of feature detected by ORB

### ISSUE THREAD

**Issue by zouh520sdo** [opencv/opencv#10533]
##### System information (version)

- OpenCV => 3.0.0:grey_question:
- Operating System / Platform => Android:grey_question:
- Compiler => :grey_question:

##### Detailed description

I'm using Android opencv (3.0.0). I found ORB can only detect maximum 500 features. I want to know if there is anyway to detect more features.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
