### ISSUE TITLE
Assertion failure occurs in jas_image.c when processing crafted image file

### ISSUE THREAD

**Issue by Epeius** [opencv/opencv#10539]
## System information (version)

- OpenCV 3.3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => clang++

## Detailed description

An assertion failure is triggered when parsing crafted image file in function `jas_image_chclrspc` in file jas_image.c:1344.

The crash details as follows:

=================================================================

warning: not enough tile data (80 bytes)
warning: component data type mismatch
opencv_afl-test: jas_image.c:1344: jas_image_chclrspc: Assertion `inprof' failed.
Aborted (core dumped)

=================================================================

## Steps to reproduce

Please refer to the following url for the testcases:
https://github.com/Epeius/NBPOC/tree/master/jas_image_chclrspc_assertion_fail

**Comment by alalek** [comment]
see #5849
