### ISSUE TITLE
Allow defining CVAPI_EXPORTS even when BUILD_SHARED_LIBS is OFF

### ISSUE THREAD

**Issue by jimfcarroll** [opencv/opencv#10535]
I would like to submit a change that will allow the optional building of a distribution that with  CVAPI_EXPORTS defined even when not BUILD(ing)_SHARED_LIBS. This will allow the building of a single  artifact that can be used in a polyglot development environment.

In my case, I'm building the Java wrappers with the JNI library statically linked to the rest of OpenCV with the intention of distributing it with (actually inside of) a jar file. This artifact is also supposed to be able to have C/C++ and additional JNI code written against it. Currently it's impossible to do this because compiling statically hides the main APIs visibility from the resulting JNI jar file.

See also http://answers.opencv.org/question/181751/java-jni-symbol-lookup-error-from-custom-native-extension-using-opencv-c/

I can submit a PR with the appropriate change if it's something the team would be interested in.

Thanks

**Comment by alalek** [comment]
Check for `BUILD_FAT_JAVA_LIB=ON` option.

**Comment by jimfcarroll** [comment]
Thanks alalek. That doesn't seem to do anything more than what building the java wrappers with BUILD_SHARED_LIBS turned off did. 

On windows I get:

```
--     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP12  /MT /O2 /Ob2 /DNDEBUG  /Zi
--     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP12  /MTd /Zi /Ob0 /Od /RTC1 
```

CVAPI_EXPORTS isn't defined, although looking at the latest OpenCVModule.cmake, I'm not sure why.

**Comment by alalek** [comment]
These compiler flags are global. Target-specific flags are not shown here.

You could try to force this definition via CMAKE_CXX_FLAGS="/D CVAPI_EXPORTS=1" via CMake command line.

Your scenario is widely used with Android builds. So BUILD_FAT_JAVA_LIB is ANDROID-specific for now.
You could try removing "ANDROID" part of [this condition](https://github.com/opencv/opencv/blob/3.4.0/cmake/OpenCVModule.cmake#L889).
(and fix Java module script, because it doesn't expect MSVC compiler/linker there)

**Comment by jimfcarroll** [comment]
Forcing `target_compile_definitions(${the_module} PRIVATE CVAPI_EXPORTS)` fixed the problem (although, under Windows, I had to manually move the import lib into the install directory (CMAKE_INSTALL_PREFIX) - is there an option for creating a `dev` installation?).

I didn't make any changed to the java module so I'm not sure what you where expecting to happen.

Let me know if this is worthy of a PR.

Thanks for your help.

**Comment by jimfcarroll** [comment]
If it helps, this is what I have working: https://github.com/jimfcarroll/opencv/commit/5fea4753b26ffc30b271daa3e390cdf52da3a1bc

Obviously I'd remove the `status` call that I just put in so I could see that it was set.

I still need to:
1) Verify it works the same way it used to when you don't set it
2) Verify it fixes the problem on Linux which I haven't tried yet.

I don' t have access to a Mac and I don't have an android or IOS environment set up. Let me know if that works and once I'm finished I can add a PR.

**Comment by alalek** [comment]
@jimfcarroll Could you take a look on #10544 ?

On Linux system I got this numbers:
```
cmake ../../dev -DBUILD_SHARED_LIBS=OFF -DBUILD_FAT_JAVA_LIB=OFF
...
$ ll lib/libopencv_java340.so 
-rwxrwxr-x 1 alalek alalek 68166200 Jan  7 18:02 lib/libopencv_java340.so
$ nm -g lib/libopencv_java340.so | wc -l
16274

cmake ../../dev -DBUILD_SHARED_LIBS=OFF -DBUILD_FAT_JAVA_LIB=ON
...
$ ll lib/libopencv_java340.so 
-rwxrwxr-x 1 alalek alalek 70432600 Jan  7 18:06 lib/libopencv_java340.so
$ nm -g lib/libopencv_java340.so | wc -l
20418
```

I didn't verify "install" and "find_package(OpenCV)" functionality.

**Comment by jimfcarroll** [comment]
In my first attempt to build it I applied your PR to 3.4.0. I got 100s of "unresolved externals." I'm trying to build your change applied to master now.

In case it helps, this is my cmake line:
```"/c/Program Files/CMake/bin/cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/c/utils/opencv-working/opencv/installed" -DOPENCV_EXTRA_MODULES_PATH=../sources/opencv_contrib/modules -DBUILD_SHARED_LIBS=OFF -DBUILD_FAT_JAVA_LIB=ON -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_bindings_generator=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DOPENCV_SKIP_VISIBILITY_HIDDEN=ON -Ax64 -G "Visual Studio 14 2015" ../sources/opencv```

**Comment by jimfcarroll** [comment]
Still failed. This is the end of the output of the build:

```
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\Lib.exe /OUT:"C:\utils\opencv-working\opencv\build\lib\Release\opencv_face340.lib" /NOLOGO /MACHINE:X64  /machine:x64 /IGNORE:4221 opencv_face.dir\Release\bif.obj

         opencv_face.dir\Release\eigen_faces.obj

         opencv_face.dir\Release\face_alignment.obj

         opencv_face.dir\Release\face_basic.obj

         opencv_face.dir\Release\facemark.obj

         opencv_face.dir\Release\facemarkAAM.obj

         opencv_face.dir\Release\facemarkLBF.obj

         opencv_face.dir\Release\facerec.obj

         opencv_face.dir\Release\fisher_faces.obj

         opencv_face.dir\Release\getlandmarks.obj

         opencv_face.dir\Release\lbph_faces.obj

         opencv_face.dir\Release\predict_collector.obj

         opencv_face.dir\Release\regtree.obj

         opencv_face.dir\Release\trainFacemark.obj

         opencv_face.vcxproj -> C:\utils\opencv-working\opencv\build\lib\Release\opencv_face340.lib

       FinalizeBuildStatus:

         Deleting file "opencv_face.dir\Release\opencv_face.tlog\unsuccessfulbuild".

         Touching "opencv_face.dir\Release\opencv_face.tlog\opencv_face.lastbuildstate".

    43>Done Building Project "C:\utils\opencv-working\opencv\build\modules\face\opencv_face.vcxproj" (default targets).

    48>Link:

         opencv_interactive-calibration.vcxproj -> C:\utils\opencv-working\opencv\build\bin\Release\opencv_interactive-calibration.exe

       FinalizeBuildStatus:

         Deleting file "opencv_interactive-calibration.dir\Release\opencv_i.E6A9FF6E.tlog\unsuccessfulbuild".

         Touching "opencv_interactive-calibration.dir\Release\opencv_i.E6A9FF6E.tlog\opencv_interactive-calibration.lastbuildstate".

    48>Done Building Project "C:\utils\opencv-working\opencv\build\apps\interactive-calibration\opencv_interactive-calibration.vcxproj" (default targets).

     3>Done Building Project "C:\utils\opencv-working\opencv\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

     1>Done Building Project "C:\utils\opencv-working\opencv\build\INSTALL.vcxproj" (default targets) -- FAILED.



Build FAILED.



       "C:\utils\opencv-working\opencv\build\INSTALL.vcxproj" (default target) (1) ->

       "C:\utils\opencv-working\opencv\build\ALL_BUILD.vcxproj" (default target) (3) ->

       "C:\utils\opencv-working\opencv\build\modules\java\opencv_java.vcxproj" (default target) (62) ->

       (Link target) -> 

         xfeatures2d.obj : error LNK2001: unresolved external symbol "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z) [C:\utils\opencv-working\opencv\build\modules\java\opencv_java.vcxproj]

         ximgproc.obj : error LNK2001: unresolved external symbol "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z) [C:\utils\opencv-working\opencv\build\modules\java\opencv_java.vcxproj]

         aruco.obj : error LNK2001: unresolved external symbol "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z) [C:\utils\opencv-working\opencv\build\modules\java\opencv_java.vcxproj]

         face.obj : error LNK2001: unresolved external symbol "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z) [C:\utils\opencv-working\opencv\build\modules\java\opencv_java.vcxproj]
```

**Comment by alalek** [comment]
I see these errors on Windows: http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/14153/steps/compile%20release/logs/stdio
Will take a look.

**Comment by jimfcarroll** [comment]
Yup. Same thing. 5000+ unresolved externals on windows.

**Comment by alalek** [comment]
Updated patch should works (typo: "${deps}" -> "${__deps}" in java/CMakeLists.txt)

**Comment by jimfcarroll** [comment]
That worked. Thanks. I'll look for it to be merged. I'm guessing it will make 3.4.1?

Thanks again.

**Comment by jimfcarroll** [comment]
Actually. Something went wrong. The build finished without error but the install directory didn't contain the .dll.

**Comment by jimfcarroll** [comment]
It looks like the install directory now contains the IMPLIB but doesn't contain the actual .dll anymore.

**Comment by alalek** [comment]
Added this to BUILD_FAT_JAVA_LIB install rule:
```
RUNTIME DESTINATION ${OPENCV_BIN_INSTALL_PATH} COMPONENT java
```

**Comment by jimfcarroll** [comment]
Looks good. It just worked and my code linked against it. The .dll and the .lib are both in the install location.

**Comment by jimfcarroll** [comment]
This worked for me on Linux although the linking requirements there are much looser so I can't say I wont run into problems when I start using it. As far as I can tell this works. What else do you need to merge it? Thanks again.

**Comment by jimfcarroll** [comment]
Thanks again!
