### ISSUE TITLE
dnn result is low accuracy

### ISSUE THREAD

**Issue by zhanglaplace** [opencv/opencv#10547]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

Hi , i test the faster-rcnn using ZFmodel. but the result is not satisfied.
![qq 20180108170857](https://user-images.githubusercontent.com/12178974/34664432-d7833d66-f496-11e7-87ce-b7be3cea713f.jpg)

the cow should be a dog 
and the mismake in car on the right-top region in the picture.

and i also test the mobileNetSSD300x300, threshold_confidence is 0.6.
![mobilessd](https://user-images.githubusercontent.com/12178974/34664841-c26c3dfe-f498-11e7-9906-272ad357531b.jpg)

if confidence_th is higher than 0.7 ,the dog is missing.

**Comment by dkurt** [comment]
@zhanglaplace, have you tried to run the model using [origin framework](https://github.com/rbgirshick/py-faster-rcnn)?

<img src="https://user-images.githubusercontent.com/25801568/34669184-9e1b3c46-f481-11e7-9aec-a1877ccf6ac5.png" width="256"> <img src="https://user-images.githubusercontent.com/25801568/34669185-9e37a9b2-f481-11e7-917a-6f5e259f629b.png" width="256">
<img src="https://user-images.githubusercontent.com/25801568/34669186-9e5d99ce-f481-11e7-9459-fea9ccaf4d6d.png" width="256"> <img src="https://user-images.githubusercontent.com/25801568/34669187-9e791f14-f481-11e7-8445-4e5ac61aeb3c.png" width="256">
That is why we use confidence threshold to prevent false positives. Try to use origin `0.8` as in [demo](https://github.com/rbgirshick/py-faster-rcnn/blob/028dc406b97559ce79b8b875a78ae510d39bed4b/tools/demo.py#L88).

**Comment by zhanglaplace** [comment]
@dkurt is any problems ?
```cpp
	static const int kInpWidth = 800;
	static const int kInpHeight = 600;
	std::string imagePath, modelPath;
	float confThreshold = 0.8;
	Net net = readNetFromCaffe("../model/faster-rcnn/faster-rcnn.prototxt", "../model/faster-rcnn/ZF_faster_rcnn_final.caffemodel");
	m_detectImg = m_img.clone();
	resize(m_detectImg, m_detectImg, Size(kInpWidth, kInpHeight));
	Mat blob = blobFromImage(m_detectImg ,1.0, Size(), Scalar(102.9801, 115.9465, 122.7717), false, false);
	Mat imInfo = (Mat_<float>(1, 3) << m_detectImg.rows, m_detectImg.cols, 1., 0.6f);

	net.setInput(blob, "data");
	net.setInput(imInfo, "im_info");

	// Draw detections.
	Mat detections = net.forward();
	const float* data = (float*)detections.data;
	for (size_t i = 0; i < detections.total(); i += 7)
	{
		// An every detection is a vector [id, classId, confidence, left, top, right, bottom]
		float confidence = data[i + 2];
		if (confidence > confThreshold)
		{
			int classId = (int)data[i + 1];
			int left = max(0, min((int)data[i + 3], m_detectImg.cols - 1));
			int top = max(0, min((int)data[i + 4], m_detectImg.rows - 1));
			int right = max(0, min((int)data[i + 5], m_detectImg.cols - 1));
			int bottom = max(0, min((int)data[i + 6], m_detectImg.rows - 1));

			// Draw a bounding box.
			rectangle(m_detectImg, Point(left, top), Point(right, bottom), Scalar(0, 255, 0));

			// Put a label with a class name and confidence.
			String label = cv::format("%s, %.3f", faster_classNames[classId], confidence);
			int baseLine;
			Size labelSize = cv::getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, &baseLine);

			top = max(top, labelSize.height);
			rectangle(m_detectImg, Point(left, top - labelSize.height),
			Point(left + labelSize.width, top + baseLine),
			Scalar(255, 255, 255), FILLED);
			putText(m_detectImg ,label, Point(left, top), FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 0, 0));
		}
	}
	imshow("detect_img", m_detectImg);
	waitKey(0);
```
i get the result ： 
![qq 20180108200204](https://user-images.githubusercontent.com/12178974/34669873-d5ff40d0-f4ae-11e7-9150-4f7634c071c4.png)

in face i also test faster-rcnn using c++ interface in caffe like this:https://github.com/zhanglaplace/faster-rcnn-cplusplus2 
so what should i do to correct the result cow  to  dog using opencv interface.
