### ISSUE TITLE
cap_v4l.cpp does not support added video source

### ISSUE THREAD

**Issue by duanegi** [opencv/opencv#10546]
##### System information (version)

- OpenCV => 3.4.4
- Operating System / Platform => all
- Compiler => all

##### Detailed description

 if a web cam is plugged in after opencv is initialized, this new webcam is not recognized.
This mainly a problem in linux.  In linux, if one unplugs and replugs in the camera while
opencv is running, the camera is given a new /dev/video<x> number.  opencv does not
allow one to open this new camera up without first shutting down opencv.

##### Steps to reproduce

The error seems to be in videoio/cap_v4l.cpp

```.diff
 bool CvCaptureCAM_V4L::open(int _index)
 {
    int autoindex = 0;
    char _deviceName[MAX_DEVICE_DRIVER_NAME];

    if (!numCameras)
       icvInitCapture_V4L(); /* Havent called icvInitCapture yet - do it now! */
    if (!numCameras)
      return false; /* Are there any /dev/video input sources? */

   //search index in indexList
    if ( (_index>-1) && ! ((1 << _index) & indexList) )
    {
-     fprintf( stderr, "VIDEOIO ERROR: V4L: index %d is not correct!\n",_index);
-     return false; /* Did someone ask for not correct video source number? */
+     icvInitCapture_V4L();    // see if new video source added
+     if ( (_index>-1) && ! ((1 << _index) & indexList) ){
+         fprintf( stderr, "VIDEOIO ERROR: V4L: index %d is not correct!\n",_index);
+         return false; /* Did someone ask for not correct video source number? */
+     }
    }
```

**Comment by alalek** [comment]
Workaround: use direct path to video device ('/dev/video0') instead of 'index'.
Fix: #11633
