### ISSUE TITLE
Import model with flatten or reshape layer in OpenCV

### ISSUE THREAD

**Issue by macc-n** [opencv/opencv#10543]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Ubuntu 64 bit
- Compiler => g++

##### Detailed description

I have created a CNN with Keras. The code of the net is:

```.py
model = Sequential()

model.add(Conv2D(32, (3,3), data_format='channels_last', input_shape=(48, 32, 3), name='data'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid', name='result_class'))
```
Then, using [this script](https://github.com/amir-abdi/keras_to_tensorflow), I have converted the .h5 file, created by Keras, in .pb.

Now I want to import the model using OpenCV, but when I execute the following code
```.cpp
Net net;
try {
    net = dnn::readNetFromTensorflow(model_path);
}
catch (cv::Exception& e) {
    cerr << "Exception: " << e.what() << endl;
    if (net.empty()) {
        cerr << "Can't load the model" << endl;
    }
}
```
I get this error:
```
OpenCV Error: Unspecified error (Unknown layer type Shape in op flatten_1/Shape) in populateNet, file /home/nicola/Scrivania/opencv-3.4.0/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487
Exception: /home/nicola/Scrivania/opencv-3.4.0/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:1487: error: (-2) Unknown layer type Shape in op flatten_1/Shape in function populateNet
Can't load the model
```
It seems that OpenCV can't handle flatten layer, so I changed the layer in reshape, like this:
```
model.add(Reshape((-1,)))
```
But I get the same error
```
OpenCV Error: Unspecified error (Unknown layer type Shape in op reshape_1/Shape) in populateNet, file /home/nicola/Scrivania/opencv-3.4.0/opencv-3.4.0/modules/dnn‌​/src/tensorflow/tf_i‌​mporter.cpp, line 1487 Exception: /home/nicola/Scrivania/opencv-3.4.0/opencv-3.4.0/modules/dnn‌​/src/tensorflow/tf_i‌​mporter.cpp:1487: error: (-2) Unknown layer type Shape in op reshape_1/Shape in function populateNet
```
[This issue](https://github.com/opencv/opencv_contrib/issues/1241) suggests to use the reshape function with hard-coded dimensions, but I'm not sure what dimensions I have to use in my case. How can I fix this problem?

Thanks for your help.

**Comment by dkurt** [comment]
> This issue suggests to use the reshape function with hard-coded dimensions, but I'm not sure what dimensions I have to use in my case. How can I fix this problem?

@macc-n, it's a kind of developer's responsibility to know an every layer's output sizes. See https://github.com/opencv/opencv/issues/10135.
