### ISSUE TITLE
is facemark .dat file trained enough?

### ISSUE THREAD

**Issue by cfoch** [opencv/opencv#10558]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

Model of landmark is created very inaccurate.

##### Steps to reproduce
1. Build opencv_contrib/modules/face/samples/sampleDetectLandmarksvideo.cpp
2. Exeute the program.
```$ ./sampleDetectLandmarksvideo --face_cascade=/home/cfoch/Documents/git/opencv/data/lbpcascades/lbpcascade_frontalface.xml --model_filename=/home/cfoch/Documents/git/opencv/build/share/OpenCV/testdata/cv/face/face_landmark_model.dat --video=/home/cfoch/Videos/people.ogv```
3. The landmark (or facemark) is pretty inaccurate.
![screenshot from 2018-01-08 22-59-29](https://user-images.githubusercontent.com/1060056/34704630-71737c66-f4c8-11e7-9889-5a63e8e80423.png)
![screenshot from 2018-01-08 22-59-09](https://user-images.githubusercontent.com/1060056/34704631-7196ec00-f4c8-11e7-9c13-cd8d767bc90a.png)

What is the facemark feature very inaccurate or does it just training data?

**Comment by StevenPuttemans** [comment]
@sukhad-app can you elaborate on your work? It might be due too the fact that the model was not trained with Asian faces?

**Comment by sukhad-app** [comment]
@cfoch , it is giving inaccurate results as face is not detected properly as it is evident in the first image as you are getting two rectangles, inner one and and an outer rectangle. As landmark detection depends on the bounding box of the face detected. Try changing parameters of detectMultiScale function in the sample file.  Give values to min-size and max-size in the function and also try reducing the scale factor. You would get better results.
