### ISSUE TITLE
iOS - force 3rdParty build of libwebp 

### ISSUE THREAD

**Issue by foundry** [opencv/opencv#10564]
##### System information (version)
- OpenCV => master
- Platform =>  OSX 10.12 (target: iOS)
- Tools =>  CMake 3.4-3.10.1 XCode 8.3-9.2
- Compiler => AppleClang 8.1.0.8020042

##### Detailed description
OpenCV fails to compile using `platforms/ios/build_framework.py`, unless `--without imgcodecs`

I have isolated the issue to a local (homebrew) installed version of `libwebp`. If I use the local `libwebp.dylib`, the build fails. On the other hand if I force openCV to build `libwebp` from the `3rdParty` distribution, the build succeeds.

When I configure CMake to use my system `libwebp`:  
`--     WEBP:   /usr/local/lib/libwebp.dylib (ver encoder: 0x020e)`  
Build fails

When I coax CMake to build from the OpenCV 3rdParty distribution:  
`--     WEBP:                        build (ver encoder: 0x020e)`   
Build succeeds

To force a build of `libwebp`, I have hacked `OpenCVFindLibsGrfmt.make` to ignore `WEBP_FOUND` - but I'm sure that's not the right way to do this.

<img width="573" alt="screen shot 2018-01-09 at 11 31 45" src="https://user-images.githubusercontent.com/341731/34720969-be64cf00-f538-11e7-83a2-1bc6d6d1bc99.png">

So I am wondering: what is the cleanest way to force opencv to build `libwebp` and ignore any locally installed version?

**Comment by mshabunin** [comment]
Maybe passing `-DBUILD_WEBP=ON` option to cmake will help. Or you can turn it off: `-DWITH_WEBP=OFF`. 

And what is the problem with preinstalled libwebp?

**Comment by foundry** [comment]
Both options do the trick - i can add them in `build_framework.py`. As to why the pre-installed `libwepp` is not behaving, i'm still investigating.

**Comment by alalek** [comment]
> pre-installed

This is MacOS binary for x86. It can't be used within iOS framework (at least there are no binaries for ARMv7/AARCH64).

**Comment by foundry** [comment]
It seems it's only an issue with older versions of CMake:  
 
_CMake 3.4.1_  
tries to use `/usr/local/libwebp.dylib` which breaks the build process.   
Using `-DBUILD_WEBP=ON` or `-DWITH_WEBP=OFF` fixes the issue.

_CMake 3.10.1_  
correctly builds using `3rdParty`, no changes to build settings required.

**Comment by alalek** [comment]
@foundry Could you try this [patch](https://github.com/alalek/opencv/commit/issue_10564)?

**Comment by foundry** [comment]
No change..

CMake 3.10.1:
```
   Media I/O:
--     ZLib:                        build (ver 1.2.11)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         build (ver 1.6.34)
```

CMake 3.4.1:
```
-- Found WebP: /usr/local/lib/libwebp.dylib

-   Media I/O:
--     ZLib:                        build (ver 1.2.11)
--     JPEG:                        build (ver 90)
--     WEBP:                        /usr/local/lib/libwebp.dylib (ver encoder: 0x020e)
--     PNG:                         build (ver 1.6.34)
```
