### ISSUE TITLE
Python: Grayscale shows strange background

### ISSUE THREAD

**Issue by renatobellotti** [opencv/opencv#10587]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Fedora 26
- Compiler => Happens in Python

##### Detailed description

When loading an image in grayscale or converting an image to grayscale, the output has a strange yellow background (instead of white)
Original image:
![test_scan-2](https://user-images.githubusercontent.com/10884299/34906321-9bf8472c-f86b-11e7-8245-2e9f4fea473e.jpg)
How it is shown (aliasing comes from low resolution when displaying the entire image... SHould this also be considered a Matplotlib bug?):
![bildschirmfoto von 2018-01-13 14-11-59](https://user-images.githubusercontent.com/10884299/34906333-c6bb5634-f86b-11e7-98d0-ad4f70602cf3.png)

##### Steps to reproduce

```import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('test_scan-2.jpg', cv2.IMREAD_GRAYSCALE)

plt.clf()
plt.imshow(img)
plt.show()```

**Comment by sergiud** [comment]
This is not a bug. By default, matplotlib use a colormap which maps intensities to colors. To avoid this, use:
```python
plt.imshow(img, cmap='Grey_r')
```

**Comment by TalentedSD19** [comment]
plt.imshow(img, 'gray')
