### ISSUE TITLE
performance of opencv-dnn-yolo

### ISSUE THREAD

**Issue by anguoyang** [opencv/opencv#10590]
I have tested the yolo-object-detection with video, it seems that the performance is only 1/5 of cuda version(the original source code), I compiled and linked with Intel MKL(no improvement ),  is there any special configuration on OPENCL? thank you.

**Comment by anguoyang** [comment]
I suppose that the version 3.40 has built in OPENCL support and I also checked the OPENCL related options.

**Comment by dkurt** [comment]
@anguoyang, please use http://answers.opencv.org for questions but issues tracker only to report reproducible bugs and propose enhancement requests.
