### ISSUE TITLE
opencv2/dnn.hpp is not in opencv2/opencv.hpp

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10594]
- OpenCV => 3.4-dev even with master and opencv release 3.4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015-17 cmake 3.10.1

##### Detailed description

Hi,

I want yo use dnn module. I think that I can include only  :  
`#include<opencv2/opencv.hpp>`
but that's not enough because there is  no #include "opencv2/dnn.hpp" in include\opencv2\opencv.hpp.
I check this in my build configuration and in https://github.com/opencv/opencv/releases/download/3.4.0/opencv-3.4.0-vc14_vc15.7z

Is it expected behaviour ?

**Comment by alalek** [comment]
DNN API is still experimental, including source API level (including RGB/BGR hell in blobFromImage()).
So adding it into "opencv.hpp" should be avoided for compatibility reasons.
