### ISSUE TITLE
FindCUDA - CMake vs OpenCV version

### ISSUE THREAD

**Issue by claudiofantacci** [opencv/opencv#10592]
Following up PR #10497, I would like to ask why OpenCV keeps a version of FindCUDA.cmake that differs from the one provided by CMake?
Is it for backward compatibility with older CMake versions?
The two versions of the file are very similar, but they diverged at some point.

**Comment by alalek** [comment]
There are a set of reasons:
- Intensive CUDA development (3-5 years ago) required modern features which are missing in CMake at all or missing in some older CMake versions. So own module was a good choice.
- Modern CMake's FindCUDA module requires modern CMake version. It would not run with old CMake (syntax changes)
- CUDA-related issues has low priority at this moment (no active development). PRs has the same priority like others PRs. So patch contribution is the best choice to make CUDA support better in OpenCV.

Please provide concrete details about what is wrong.

See also #9505

**Comment by claudiofantacci** [comment]
> There are a set of reasons:
> 
>     Intensive CUDA development (3-5 years ago) required modern features which are missing in CMake at all or missing in some older CMake versions. So own module was a good choice.
>     Modern CMake's FindCUDA module requires modern CMake version. It would not run with old CMake (syntax changes)
>     CUDA-related issues has low priority at this moment (no active development). PRs has the same priority like others PRs. So patch contribution is the best choice to make CUDA support better in OpenCV.

Ok thanks!

> Please provide concrete details about what is wrong.

Nothing really wrong 😄! I was patching OpenCV's FindCUDA and going to open a PR for it and while doing it I made a comparison with CMake's FindCUDA. At that point I was wondering the meaning of the two different, yet similar, version of the file and came here to ask.
Now it is clear that if I find any issue related to FindCUDA using OpenCV it is better to open a PR here and possibly bringing it back to CMake in a later moment.

The problems I had have been fixed with #10497.

I close the isse 👍
