### ISSUE TITLE
DNN module readNetFromTensorflow() - How to obtain text graph definition for retrained network?

### ISSUE THREAD

**Issue by HenrikPetersen** [opencv/opencv#10601]
- OpenCV => 3.4
- Operating System / Platform => Mac OS X
- Compiler => Python

I am trying to load a tensorflow MobileNet SSD model that was retrained using the Tensorflow Object Detection API. However, I am not able to find any documentation on how to create the text graph defintion that is supposed to be given to readNetFromTensorflow  together with the frozen graph weights. 

The example given [here](https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py) works with the text graph definition given [here](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt), but not with my retrained model (I changed the number of classes to number of retrained classes). The output is a bunch of random bboxes on top of each other.

I tried to use older config files for the training, but that gives the same result.  I searched the web for methods to convert .pb files to .pbtxt files, but none of them give the required  structure.

I also tried to only supply readNetFromTensorflow with  the frozen graph weights, but that resulted in an error.

I would be nice to have some documentation on how to produce the text graph definitions, or at least provided a link to the config file that was used to create the [one](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt) provided in the example. 

Thanks in advance,
Henrik

**Comment by dkurt** [comment]
@HenrikPetersen, May I ask you to test PR https://github.com/opencv/opencv/pull/10676 using this graph definition: https://gist.github.com/dkurt/fb324b48d1c6230febd1718ee52f7291 . Change line `attr { key: "num_classes" value { i: 2 } }` appropriately (number of classes + 1 for background).

**Comment by xbcReally** [comment]
I want to know the answer too...And I note that you @dkurt commit a new pbtxt file for ssd-mobilenet,adn I tried the new one but result in showing lots of bboxes with confidence 0.99...

**Comment by dkurt** [comment]
@xbcReally, please use http://answers.opencv.org. Specify a config file used for training (see https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs). Or follow recommendations from issues related at https://github.com/opencv/opencv/pull/10676.
