### ISSUE TITLE
Error : OpenCV: Couldn't read video stream from file

### ISSUE THREAD

**Issue by Fujitus** [opencv/opencv#10618]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Mac OS High Sierra 10.13.2 
- Compiler => Apple LLVM version 9.0.0  (clang-900.0.39.2)

##### Detailed description

Hey, I made this issues because I always add an error when I want to load images to make a video.
Error :  OpenCV: Couldn't read video stream from file "./img/video_image/scene_%d.png"
This code works on Linux ubuntu with g++ 5.4. 
If someone got a issues.
let me now.

##### Steps to reproduce
[example.zip](https://github.com/opencv/opencv/files/1639132/example.zip)

**Comment by sturkmen72** [comment]
cv::VideoCapture in_capture("./video_image/scene_1.png"); works for me

**Comment by Fujitus** [comment]
On Mac OS ? 
with dependency did you install or how did you install the opencv ?

**Comment by MDOBreno** [comment]
On MacOS you need to put the entire path of the capture, for exemple:

cv::VideoCapture in_capture("**/Users/myuser/Downloads/video.mkv**");
