### ISSUE TITLE
Vidoe 

### ISSUE THREAD

**Issue by mdagraca** [opencv/opencv#10610]
Hi,
I need your help with this error.
Thanks in advantage
[hs_err_pid13503.log](https://github.com/opencv/opencv/files/1636910/hs_err_pid13503.log)

##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => OS X 10.11.6
- Compiler => Eclipse Oxygen.2 Release (4.7.2)
- Java => 1.8.0_51 

##### Detailed description

Java crash and generate a log file (attached) when Video capture object is release

##### Steps to reproduce
This is my code.
The start method works fine, the error happens in stopAcquisition:  videoCapture.release
Both methods are called when a button is clicked in the JavaFX Screen.
```
private VideoCapture videoCapture = new VideoCapture();
...
 @FXML
protected void start() 
	{
		if (this.videoCapture.isOpened()) 
		{
			this.videoCapture.release();
		}

		// start the video capture
		this.videoCapture.open(0);

		// is the video stream available?
		if (this.videoCapture.isOpened()) 
		{
			processFrame();
		} else 
		{
			showMessage("System can not connect to the camera");
		}
	}
       
       @FXML
	private void stopAcquisition() 
	{
		if (this.videoCapture.isOpened()) 
		{
			// release the camera
			this.videoCapture.release();
		}
	}
```

**Comment by alalek** [comment]
1. Try OpenCV's C++ VideoCapture samples.
2. Did "release()" called from the same thread as "open()" or another?

**Comment by mdagraca** [comment]
Thanks alalek. 
I think there is something wrong with the threads.  
The videoCapture is opened when the user clicks on the start button (JavaFX) and released when the user clicks on the stop button.
