### ISSUE TITLE
Unable to build OpenCV 3.4 with CUDA 9.1 support

### ISSUE THREAD

**Issue by jorditg** [opencv/opencv#10620]

**Comment by Guilmort** [comment]
The problem is probably due to CMakeCache.txt file which is pointing on older Cuda version.
Check also that LD_LIBRARY_PATH env variable is pointing on cuda-9.1 library folder.
Clear CMakeCache.txt or checkout from github opencv 3.4.0 before launching cmake. 
It works perfectly on my side.

**Comment by callemein** [comment]
I'm currently experiencing this build error:

```
 nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:208 (message):
  Error generating
 ~/Lib/opencv/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o
```
My setup:

Ubuntu 17.10 
NVIDIA GTX 1080 Ti 
Cuda 9.1

Used this CMAKE
```
cmake \
-D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_TBB=ON \
-D WITH_V4L=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D WITH_OPENGL=ON \
-D INSTALL_C_EXAMPLES=ON \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D OPENCV_EXTRA_MODULES_PATH=/home/timothy/Lib/opencv_contrib/modules \
-D CUDA_NVCC_FLAGS=‘-ccbin gcc-5’ \
-D CUDA_CUDA_LIBRARY='/usr/local/cuda' \
-D WITH_CUDA=ON \
-D CUDA_INCLUDE_DIRS='/usr/local/cuda/include' \
-D BUILD_EXAMPLES=ON ..
```

**Comment by struers-cge** [comment]
Additionally i can confirm OpenCV 3.4.1 and CUDA 9.1 is able to build without errors (CXX 11 enabled)

**Comment by erichfrazer** [comment]
No, it doesn't work, not with the latest VS 2017, it doesn't. Has nothing to do with cmake pointing to old cuda version, it has to do with VS 2017 being incompat w/ Cuda 9.1
