### ISSUE TITLE
crash while building with ffmpeg and contrib in raspberry pi 3 model B(debian)

### ISSUE THREAD

**Issue by deekshithmr95** [opencv/opencv#10626]
- OpenCV => 3.3.0
- Operating System / Platform => raspberry pi 3 model B(debian)
- Compiler => UNIX Makefiles
- Cmake-GUI => 3.6.2

https://pastebin.com/5VGHA92m (build output from terminal)

[ 39%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/local/lib/libx264.a(common.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libx264.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:228: recipe for target 'lib/libopencv_videoio.so.3.3.0' failed
make[2]: *** [lib/libopencv_videoio.so.3.3.0] Error 1
CMakeFiles/Makefile2:4311: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

using opencv=3.3.0
opencv_contrib=3.3.0

before building I Unchecked:
BUILD_opencv_world,
BUILD_TBB,
WITH_TBB,
BUILD_opencv_python2,
BUILD_opencv_python3, 
WITH_MATLAB,
WITH_CUDA,
BUILD_opencv_dnn,
WITH_OPENGL,
WITH_QT

and Checked:
WITH_FFMPEG(Default)

I installed all libraries (mentioned in below link)
https://pastebin.com/vFkYzQ08 (prerequisite libraries before building)

I also tried remove all those libraries and building opencv source with ffmpeg and contrib (yet build crashes at 23% for opencv 3.4    and 39% for opencv 3.3)

**Comment by alalek** [comment]
> recompile with -fPIC

This is configuration issue and can't be resolved in OpenCV.

Build/usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
