### ISSUE TITLE
VideoWriter support for 16-bit depth images and color-alpha color imags

### ISSUE THREAD

**Issue by eruffaldi** [opencv/opencv#10623]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Any
- Compiler => Gcc

##### Detailed description

Allow VideoWriter to accept RGBA or 16-bit grayscale, in particular with ffmpeg backend. This requires changes in the VideoWriter constructor. 

Issue #10583 and associate PR address only the lossless aspect

**Comment by jveitchmichaelis** [comment]
@shawndfernandes Thanks for looking into this. I'm interested in improving support for raw data in OpenCV and currently saving 16-bit video is quite difficult.

It seems like your PR is basically ready and the builds passed, although some were skipped for some reason. Is there anything remaining that's stopping this from being merged?

**Comment by shawndfernandes** [comment]
Hi @Josh,

Please check with Alexander Alekhin for more details on merging with existing opencv Code.

**Comment by jveitchmichaelis** [comment]
Ok, @alalek?

**Comment by alalek** [comment]
Feel free to evaluate mentioned patches.

> builds passed

There is no 100% guarantee that this code works.
VideoWriter is not FFmpeg **only**.

**Comment by jveitchmichaelis** [comment]
Sure, that's fine. I was just curious if there was a reason it hadn't been merged and if I could do anything to help on that front (for example, if more rigorous test cases are required).

**Comment by alalek** [comment]
There is merged PR about GStreamer with similar functionality (common parts can be reused): #18535

**Comment by benknight135** [comment]
I am looking at this same functionality and wanted to see if this was resolved. Looking at the GStreamer PR that was merged it has 16-bit Video Writer but is missing 16-bit Video Capture.

**Comment by bobluoluo** [comment]
Any update on this feature?

**Comment by TangToy** [comment]
Has this been solved?
