### ISSUE TITLE
The 7-point algorithm is not normalized

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#10643]
##### System information (version)

- OpenCV => master

##### Detailed description

The [7-point algorithm][1] is not normalized.

According to [Richard I. Hartley. 1997. In Defense of the Eight-Point Algorithm. IEEE Trans. Pattern Anal. Mach. Intell. 19, 6 (June 1997), 580-593. ][2], the performance of the unnormalized version is **much worse** than the normalized version, though the paper talks about the [8-point algorithm][3], it applies also to the 7-point algorithm.

[3]: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L533
[2]: https://www.cse.unr.edu/~bebis/CS485/Handouts/hartley.pdf

[1]: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L424

**Comment by csukuangfj** [comment]
Since both [RANSAC][1] and [LMedS][2] call the 7-point algorithm in
[cv::findFundamentalMat][3], it has a large impact on the accuracy of the computed
fundamental matrix.

[3]: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L692
[2]: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L748
[1]: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L746

**Comment by csukuangfj** [comment]
Refer to the implementation in OpenMVG

https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/openMVG/multiview/solver_fundamental_kernel.hpp#L116-L128

**Comment by yongduek** [comment]
@csukuangfj 
I am having the same idea as you have, but do not have any practical experience, and looking for some reference. Have you had any real happening or experience related to data normalization for 7 point algorithm? Any related web link or paper specific on data normalization for 7p algorithm is welcome if you have any.

**Comment by csukuangfj** [comment]
@yongduek
You can refer to this book:

> Multiple View Geometry in Computer Vision 

https://www.amazon.com/Multiple-View-Geometry-Computer-Vision/dp/0521540518/ref=sr_1_1?crid=291J5UZH42CUE&keywords=multiple+view+geometry+in+computer+vision&qid=1581078014&sprefix=computer+vision+ge%2Caps%2C459&sr=8-1
---
you can find a pdf version by Google.
