### ISSUE TITLE
jpg's RGB value changed using different opencv versions (3.3 v.s. 3.4)

### ISSUE THREAD

**Issue by Marco-LIU** [opencv/opencv#10641]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => linux
- Compiler => gcc

##### Detailed description

The jpg's RGB value decoded by imread (in 3.4) is different with 3.3

##### Steps to reproduce
![001](https://user-images.githubusercontent.com/1195343/35141846-5fe8f6fc-fd37-11e7-9c16-4f0ce070a90f.jpg)
For this jpg, using python cv2.imread, fetch RGB value img[207,0]
3.3 will return [115, 52, 226]
3.4 will return [111, 54, 223]

**Comment by alalek** [comment]
OpenCV uses libjpeg to read JPEG images. Check used versions via `cv::getBuildInformation()`.
OpenCV can use system libjpeg (preferred way, you need to install "dev" package via system package manager) or it uses builtin sources of libjpeg from 3rdparty directory (code is updated between 3.3 / 3.4).

JPEG is lossless format in general, so don't expect bit-exact values on different platforms / different software versions.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by Marco-LIU** [comment]
Thanks for your reply, @alalek 
It seems come from the change of Libjpeg.

Just make a mark for this pit:
"If you get different result with same model and same input file in different platform, CHECK the opencv VERSION"

Hope can help others

**Comment by sturkmen72** [comment]
@alalek i think a typo here "JPEG is lossless"

**Comment by Marco-LIU** [comment]
This problem comes form opencv-python building. For opencv-python 3.4, it use libjpeg-turbo instead of libjpeg for better performance. These two jpeg libs will give different results for the same jpg file.

Thanks all.
