### ISSUE TITLE
OpenCV_DIR wrong in documentation?

### ISSUE THREAD

**Issue by cjamin** [opencv/opencv#10645]
I'm using OpenCV 2.4.13.5.

The [installation documentation for Windows](https://docs.opencv.org/master/d3/d52/tutorial_windows_install.html) says to set OPENCV_DIR to D:\OpenCV\Build\[arch]\[compiler], but for find_package to work, CMake looks for OpenCVConfig.cmake in OPENCV_DIR.

Setting OPENCV_DIR to D:\OpenCV\Build works on my machine.
Note that [node-opencv](https://github.com/peterbraden/node-opencv) expects OPENCV_DIR to be set according to the documentation to work, which is a pain when using both.

**Comment by csukuangfj** [comment]
You may use
```
set("OpenCV_DIR" "/your/path/to/opencv/installation/dir")
```
inside your `CMakeLists.txt` instead of setting the environment variable.

**Comment by cjamin** [comment]
Ok, but the documentation problem remains.

**Comment by alalek** [comment]
Documentation is created for very old OpenCV 2.3 (see screenshots). So it may not be usable with modern OpenCV versions (OpenCV is able to detect MSVS version / arch).

Perhaps documentation should say to specify directory with `OpenCVConfig.cmake` (like CMake's `find_package()` message).

**Comment by cjamin** [comment]
I agree.

**Comment by akhandait** [comment]
@alalek I would like to correct the documentation.
Can you tell me what specifically needs to mentioned and should it replace the older method or go along it.

**Comment by guyo13** [comment]
I have a similar issue, right now I use `set("OpenCV_DIR" "/your/path/to/opencv/installation/dir")`
inside CMakeLists.txt and it works fine.

**Comment by talha3111997** [comment]
Can anyone guide me please that how can I contribute to the documentation

**Comment by NikkiPriya** [comment]
Hi, I would like to work on this issue, can you help me ways to get started?

**Comment by alalek** [comment]
2.4 branch is EOL. Closing

Feel free to review installation tutorials updates here: #18195
