### ISSUE TITLE
Will opencv support C compiler after 3.4.0?

### ISSUE THREAD

**Issue by springkim** [opencv/opencv#10658]
- OpenCV => 3.4
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015 , MinGW64(7.2.0)

Hi. 
I have a simple question.
opencv3.3.1 not support C compiler(e.g MinGW64, MSVC TC). 
But now i can compile without problem with 3.4.0.
Will opencv support C interface which means support C compiler after 3.4.0?

**Comment by alalek** [comment]
#6585
