### ISSUE TITLE
real_time_pose_estimation tutorial is broken (registration step produces output incompatible with detection step)

### ISSUE THREAD

**Issue by maj-tom** [opencv/opencv#10650]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

After building opencv and the tutorial code in `opencv\sources\samples\cpp\tutorial_code\calib3d\real_time_pose_estimation`, I note that running the detection executable with the pre-generated `cookies_ORB.yml` included with the source package results in the expected output (it shows the box being tracked in the video). However, running the registration executable results in a `cookies_ORB.yml` written out that then causes the detection executable to immediately crash with

`OpenCV Error: Assertion failed (npoints >= 4 && npoints == std::max(ipoints.checkVector(2, 5), ipoints.checkVector(2, 6))) in cv::solvePnPRansac, file E:\opencv\sources\modules\calib3d\src\solvepnp.cpp, line 253`

In case it matters, when I run the executables, it tells me it's initializing OpenCL. Executables were run with default settings (no command line arguments).

##### Steps to reproduce

- Build everything on system as in the header
- Run `cpp-tutorial-pnp_detection.exe` without arguments so it uses the example data and pre-generated `cookies_ORB.yml`
- Observe expected output
- Run `cpp-tutorial-pnp_registration.exe`
- Select box corners as appropriate (bottom face first, near, left, right, and far corners in that order; likewise for top face)
- Press enter and observe most points being green (few red outliers if previous step was done correctly with points selected just barely outside the corners so edges in the image are included)
- Press enter again to complete
- Run `cpp-tutorial-pnp_detection.exe`
- Observe assertion failure

**Comment by mshabunin** [comment]
In  #9086 minimal number of points accepted by solvePnP have been increased to 4:
https://github.com/opencv/opencv/blob/56bcdfd7d94233ef8e0bd3d8049352a3bb6afe44/modules/calib3d/src/solvepnp.cpp#L253
But in tutorial application there is a check:
https://github.com/opencv/opencv/blob/56bcdfd7d94233ef8e0bd3d8049352a3bb6afe44/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_detection.cpp#L225
These two checks should be consistent.
