### ISSUE TITLE
Use vs2013 to compile opencv3.4, darknet_io.cpp file appears int32_t, uint64_t undefined problem

### ISSUE THREAD

**Issue by studyCheng** [opencv/opencv#10656]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

**Comment by KangLin** [comment]
Error See: https://ci.appveyor.com/project/KangLin/rabbitthirdlibrary/build/v0.0.3.64/job/ncqons9ss4xd4mbn
Suggest add automation complie test(ci).

**Comment by alalek** [comment]
Fixed in master #10521
