### ISSUE TITLE
Potential Memory Leak in Microsoft Media Foundation VideoIO CvVideoWriter

### ISSUE THREAD

**Issue by pot8oe** [opencv/opencv#10666]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 10 64Bit
- Compiler => Visual Studio 2013

I'm building OpenCV from the release 3.2.0 ZIP and have enabled Microsoft Media Foundation in my build.

##### Detailed description

When saving H.264 videos using VideoWriter the open() function will allocate a considerable chunk of ram ~(50MB) which will not be released when calling release(). I've tracked the allocation down to:

_cap_msmf.cpp Line 4190_
`hr = sinkWriter->SetInputMediaType(streamIndex, mediaTypeIn.Get(), NULL);`

sinkWriter is finalized during CvVideoWriter_MSMF::close() however that does not clear the allocated memory. I've added a line setting sinkWriter = NULL after it's finalize is called and now the memory does appear to get released.

_cap_msmf.cpp Line 4063_
`sinkWriter = NULL;`

I'm not sure if this is the appropriate fix but it does seem to work in my case.

**Comment by pwnorbitals** [comment]
@pot8oe still reproducible recently ?

**Comment by pot8oe** [comment]
No, this looks to have been fixed in commit [2bb5d1b](https://github.com/opencv/opencv/commit/2bb5d1bca3c42cc45be6917e5b5abf1cf71dbdba)
