### ISSUE TITLE
Python tutorial not correct 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10670]
In this tutorial https://docs.opencv.org/master/d0/d86/tutorial_py_image_arithmetics.html (-> bitwise operation.) image sizes are not correct.

 I have got an error :
cv2.error: C:\Lib\opencv\modules\core\src\arithm.cpp:241: error: (-215) (mtype == 0 || mtype == 1) && _mask.sameSize(*psrc1) in function cv::binary_op

if I write :

```
img2 = cv.imread('c:/lib/opencv/samples/data/opencv-logo.png')
img2=cv.resize(img2,None,fx=0.25,fy=0.25)
```

there is no error but I don't understand how can i get this [image](https://docs.opencv.org/master/overlay.jpg) with add function (with copyto and a mask I can get this result).

**Comment by alalek** [comment]
Check that `imread()` reads image really (it should not be empty)

**Comment by LaurentBerger** [comment]
@alalek Yes I'm noobs in python but I have checked  this using imshow and with resize it works. 
Ok I have found the origin it is not opencv-logo.png but opencv-logo-white.png : no need of copyto because background in this logo  is black
