### ISSUE TITLE
Can't set Buffersize in opencv 3

### ISSUE THREAD

**Issue by devesh1508** [opencv/opencv#10671]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04
-  Python

##### Detailed description

I tried to set the buffersize to minimize the delay in frames (there seems to be a delay of 100 ms in getting any frame) by using the following command in a python code:

cap = cv2.VideoCapture(0)

a=cap.get(cv2.CAP_PROP_BUFFERSIZE) # CV_CAP_PROP_BUFFERSIZE

print 'Buffersize', a

cap.set(cv2.CAP_PROP_BUFFERSIZE,1)

a=cap.get(cv2.CAP_PROP_BUFFERSIZE) # CV_CAP_PROP_BUFFERSIZE

But get the following error-- and then the code ignores the error and moves ahead with the processing. 

```
VIDEOIO ERROR: V4L2: setting property #38 is not supported
```

The main issue is to get rid of the 100 ms delay.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
