### ISSUE TITLE
FCN_semsegm.cpp fails with DNN_TARGET_OPENCL

### ISSUE THREAD

**Issue by jules70** [opencv/opencv#10682]
- OpenCV => 3.4
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- Intel Core i5-7500 (Kaby Lake) (opencl runtime from: intel_sdk_for_opencl_2017_7.0.0.2567)

This OpenCV sample:
https://github.com/opencv/opencv/blob/master/samples/dnn/fcn_semsegm.cpp

crashes when I set the net target to OpenCL by adding the line:
```net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);```
before net.forward in the sample. Runs fine and produces correct result when setting CPU target using:
```net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);```

DNN_TARGET_OPENCL error is:
OpenCV Error: Bad argument (invalid crop parameters or blob sizes) in cv::dnn::CropLayerImpl::finalize, file opencv\sources\modules\dnn\src\layers\crop_layer.cpp, line 116

Fails at:
opencv_dnn340d.dll!cv::dnn::CropLayerImpl::finalize(const std::vector<cv::Mat *,std::allocator<cv::Mat *> > & inputs, std::vector<cv::Mat,std::allocator<cv::Mat> > & outputs) Line 116	C++	Symbols loaded.

On line:
Line: 116 opencv\sources\modules\dnn\src\layers\crop_layer.cpp

```
if (offset_final[i] < 0 || offset_final[i] + inpSzBlob.size[i] > inpBlob.size[i])
                CV_Error(Error::StsBadArg, "invalid crop parameters or blob sizes");
```

**Comment by dkurt** [comment]
@jules70, works fine for me

<img src="https://user-images.githubusercontent.com/25801568/35376879-0b1b867c-01be-11e8-9c99-9275dcea2016.png" width="500"> <img src="https://user-images.githubusercontent.com/25801568/35376878-0af6fa0a-01be-11e8-8eea-cd95f36ff53e.png" height="512">

Please check OpenCV version.

**Comment by jules70** [comment]
Thanks @dkurt - I downloaded OpenCV 3.4.0 windows pack from the OpenCV release page and built using cmake & Visual Studio 2017.

Should I get master branch from github instead?

**Comment by dkurt** [comment]
@jules70, Please try it if it's not too much trouble for you.

**Comment by jules70** [comment]
@dkurt - I git cloned master and recompiled VS2017 and got the same issue. 

I think you are running a different sample: the fcn_semsegm.cpp sample does not show a legend. I think you are running the torch_enet.cpp sample, which does show a legend. I was able to successfully run the enet sample successfully in OpenCL aswell. But I specifically wanted to run the FCN network so I can directly compare the performance of Intel's CLDNN against OpenCV's DNN module on the same network & data (sorry, I may have confused you with the other conversation we had on linkedin, which was about the enet sample). 

Can you check the fcn_semsegm.cpp sample with the target set to DNN_TARGET_OPENCL to see if you get the same crash?

Thanks

**Comment by dkurt** [comment]
@jules70, I just printed it out using `showLegend` function from torch_enet.cpp, https://github.com/opencv/opencv/blob/be4fa03face10d29d0a36a7d252493c265ad1cbc/samples/dnn/torch_enet.cpp#L125
Can you try to update OpenCL? That solved an issue https://github.com/opencv/opencv/issues/10465.

**Comment by jules70** [comment]
I upgraded my intel graphics driver to 23_20_16_4901 as per resolution to [#10465](https://github.com/opencv/opencv/issues/10465), rebooted and still got the same error unfortunately. Here is my opencl hdr information from opencv_perf_dnn (which passes all tests):
[opencl-hdr.txt](https://github.com/opencv/opencv/files/1666056/opencl-hdr.txt).

**Comment by dkurt** [comment]
@jules70, opencv_perf_dnn is a performance test. Can you try to run opencv_test_dnn?
