### ISSUE TITLE
FFMPEG and opencv imread

### ISSUE THREAD

**Issue by srikanthsridar** [opencv/opencv#10686]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => ubuntu 16.04

##### Detailed description
I extracted frames from a video using ffmpeg.The image format is jpg.The folder containing the image files was 92MB.When I read it in a python list using opencv's imread the size in RAM is close to 3GB.Is this a bug in imread or what am i missing here.I could not find a solution in opencv answers as well.

**Comment by dkurt** [comment]
> I could not find a solution in opencv answers as well.

@srikanthsridar, if you can't find a solution at http://answers.opencv.org, please ask a question at http://answers.opencv.org. This is issues tracker for bugs and feature requests but it's not for build/install/usage questions.
