### ISSUE TITLE
Bug report about dnn

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10699]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Ubuntu
- Compiler => cmake 3.8

build without opencv_contribe, make and make install successfully. build my own example successfully.
but when i add:
#include <opencv2/dnn.hpp>
compile error:

In file included from /opt/local/include/opencv2/dnn/dnn.hpp:57:0,
                 from /opt/local/include/opencv2/dnn.hpp:62,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dict.hpp:63:21: error: expected ‘)’ before ‘i’
     DictValue(int64 i = 0)      : type(Param::INT), pi(new AutoBuffer<int64,1>) { (*pi)[0] = i; }       //!< Constructs integer scalar
                     ^
In file included from /opt/local/include/opencv2/dnn/dnn.hpp:57:0,
                 from /opt/local/include/opencv2/dnn.hpp:62,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dict.hpp:102:28: error: template argument 1 is invalid
         AutoBuffer<int64, 1> *pi;
                            ^
/opt/local/include/opencv2/dnn/dict.hpp:102:28: error: template argument 2 is invalid
/opt/local/include/opencv2/dnn/dict.hpp: In constructor ‘cv::dnn::experimental_dnn_v3::DictValue::DictValue(int)’:
/opt/local/include/opencv2/dnn/dict.hpp:64:86: error: template argument 1 is invalid
     CV_WRAP DictValue(int i)            : type(Param::INT), pi(new AutoBuffer<int64,1>) { (*pi)[0] = i; }       //!< Constructs integer scalar
                                                                                      ^
/opt/local/include/opencv2/dnn/dict.hpp:64:86: error: template argument 2 is invalid
/opt/local/include/opencv2/dnn/dict.hpp:64:98: error: invalid types ‘int[int]’ for array subscript
     CV_WRAP DictValue(int i)            : type(Param::INT), pi(new AutoBuffer<int64,1>) { (*pi)[0] = i; }       //!< Constructs integer scalar
                                                                                                  ^
/opt/local/include/opencv2/dnn/dict.hpp: In constructor ‘cv::dnn::experimental_dnn_v3::DictValue::DictValue(unsigned int)’:
/opt/local/include/opencv2/dnn/dict.hpp:65:78: error: template argument 1 is invalid
     DictValue(unsigned p)       : type(Param::INT), pi(new AutoBuffer<int64,1>) { (*pi)[0] = p; }       //!< Constructs integer scalar
                                                                              ^
/opt/local/include/opencv2/dnn/dict.hpp:65:78: error: template argument 2 is invalid
/opt/local/include/opencv2/dnn/dict.hpp:65:90: error: invalid types ‘int[int]’ for array subscript
     DictValue(unsigned p)       : type(Param::INT), pi(new AutoBuffer<int64,1>) { (*pi)[0] = p; }       //!< Constructs integer scalar
                                                                                          ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp: At global scope:
/opt/local/include/opencv2/dnn/dnn.hpp:305:17: error: reference to ‘int64’ is ambiguous
         virtual int64 getFLOPS(const std::vector<MatShape> &inputs,
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:305:17: error: ‘int64’ does not name a type
         virtual int64 getFLOPS(const std::vector<MatShape> &inputs,
                 ^
/opt/local/include/opencv2/dnn/dnn.hpp:527:17: error: reference to ‘int64’ is ambiguous
         CV_WRAP int64 getFLOPS(const std::vector<MatShape>& netInputShapes) const;
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:527:17: error: ‘int64’ does not name a type
         CV_WRAP int64 getFLOPS(const std::vector<MatShape>& netInputShapes) const;
                 ^
/opt/local/include/opencv2/dnn/dnn.hpp:529:17: error: reference to ‘int64’ is ambiguous
         CV_WRAP int64 getFLOPS(const MatShape& netInputShape) const;
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:529:17: error: ‘int64’ does not name a type
         CV_WRAP int64 getFLOPS(const MatShape& netInputShape) const;
                 ^
/opt/local/include/opencv2/dnn/dnn.hpp:531:17: error: reference to ‘int64’ is ambiguous
         CV_WRAP int64 getFLOPS(const int layerId,
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:531:17: error: ‘int64’ does not name a type
         CV_WRAP int64 getFLOPS(const int layerId,
                 ^
/opt/local/include/opencv2/dnn/dnn.hpp:534:17: error: reference to ‘int64’ is ambiguous
         CV_WRAP int64 getFLOPS(const int layerId,
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:534:17: error: ‘int64’ does not name a type
         CV_WRAP int64 getFLOPS(const int layerId,
                 ^
/opt/local/include/opencv2/dnn/dnn.hpp:596:17: error: reference to ‘int64’ is ambiguous
         CV_WRAP int64 getPerfProfile(CV_OUT std::vector<double>& timings);
                 ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;
                    ^
In file included from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../algs.h:87:0,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/frontal_face_detector.h:7,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:3:
/home/zero/Code/dlib/dlib-2/dlib/../dlib/image_processing/../image_processing/../geometry/../uintn.h:27:23: note:                 typedef long long int dlib::int64
     typedef long long int64;
                       ^
In file included from /opt/local/include/opencv2/dnn.hpp:62:0,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.hpp:596:17: error: ‘int64’ does not name a type
         CV_WRAP int64 getPerfProfile(CV_OUT std::vector<double>& timings);
                 ^
In file included from /opt/local/include/opencv2/dnn/dnn.hpp:755:0,
                 from /opt/local/include/opencv2/dnn.hpp:62,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:23:
/opt/local/include/opencv2/dnn/dnn.inl.hpp: In static member function ‘static cv::dnn::experimental_dnn_v3::DictValue cv::dnn::experimental_dnn_v3::DictValue::arrayInt(TypeIter, int)’:
/opt/local/include/opencv2/dnn/dnn.inl.hpp:54:54: error: template argument 1 is invalid
     DictValue res(Param::INT, new AutoBuffer<int64, 1>(size));
                                                      ^
/opt/local/include/opencv2/dnn/dnn.inl.hpp:54:54: error: template argument 2 is invalid
/opt/local/include/opencv2/dnn/dnn.inl.hpp:56:20: error: invalid types ‘int[int]’ for array subscript
         (*res.pi)[j] = *begin;
                    ^
/opt/local/include/opencv2/dnn/dnn.inl.hpp: At global scope:
/opt/local/include/opencv2/dnn/dnn.inl.hpp:86:8: error: reference to ‘int64’ is ambiguous
 inline int64 DictValue::get<int64>(int idx) const
        ^
In file included from /opt/local/include/opencv2/core/cvdef.h:91:0,
                 from /opt/local/include/opencv2/core.hpp:52,
                 from /opt/local/include/opencv2/core/core.hpp:48,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv/cv_image.h:6,
                 from /home/zero/Code/dlib/dlib-2/dlib/../dlib/opencv.h:10,
                 from /home/zero/Code/dlib/dlib-2/examples/face.cpp:6:
/opt/local/include/opencv2/core/hal/interface.h:61:20: note: candidates are: typedef int64_t int64
    typedef int64_t int64;

**Comment by BKZero** [comment]
i am not sure if i must install with opencv_contribe to use dnn feature?
but i cannot understanding this error.

**Comment by alalek** [comment]
Looks like your compiler doesn't know `int64_t` .

Your report missing information about:
- OpenCV version
- CMake output (with exact compiler version / build flags)

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org/
We don't observe similar problems on our public build farm: http://pullrequest.opencv.org/

We don't help with remote investigation of problems (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by BKZero** [comment]
i have write version information in the templet, but i do not know why it does not show.
OpenCV => 3.4.0
Operating System / Platform => Ubuntu
Compiler => cmake 3.8

i have turn off the cuda flag because my computer only has cpu.
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/opt/local/ \
    -D WITH_CUDA=OFF \
    -D WITH_CUFFT=OFF \
    -D WITH_CUBLAS=OFF \
    -D BUILD_EXAMPLES=ON ..

**Comment by alalek** [comment]
> why it does not show

Because `<!-- comment -->` is just a **HTML** comment block. Removed.

We have builds with Ubuntu 17.10 and doesn't observe build issues.

Please add "CMake output" (stdout) - you provides CMake command-line (it may be useful too).

Try to add `#include <cstdint>` into example file before OpenCV includes.

**Comment by BKZero** [comment]
-- Looking for ccache - not found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.8", minimum required is "1.2.3") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.23
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.40.2
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-video-1.0'
--   No package 'gstreamer-video-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'gstreamer-base-0.10'
--   No package 'gstreamer-base-0.10' found
-- Checking for module 'gstreamer-video-0.10'
--   No package 'gstreamer-video-0.10' found
-- Checking for module 'gstreamer-app-0.10'
--   No package 'gstreamer-app-0.10' found
-- Checking for module 'gstreamer-riff-0.10'
--   No package 'gstreamer-riff-0.10' found
-- Checking for module 'gstreamer-pbutils-0.10'
--   No package 'gstreamer-pbutils-0.10' found
-- Checking for module 'libdc1394-2'
--   Found libdc1394-2, version 2.2.1
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- Checking for module 'libavresample'
--   No package 'libavresample' found
-- Checking for module 'libgphoto2'
--   No package 'libgphoto2' found
-- IPPICV: Download: ippicv_2017u3_lnx_intel64_general_20170822.tgz
-- found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
-- at: /home/zero/Program/opencv-3.4.0/build/3rdparty/ippicv/ippicv_lnx
-- found Intel IPP IW sources: 2017.0.3
-- at: /home/zero/Program/opencv-3.4.0/build/3rdparty/ippicv/ippiw_lnx
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /opt/OpenBLAS/lib/libopenblas.so
-- LAPACK(OpenBLAS): Support is enabled.
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find Pylint (missing:  PYLINT_EXECUTABLE) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- Excluding from source files list: /home/zero/Program/opencv-3.4.0/build/modules/imgproc/accum.neon.cpp
-- DNN_FACE_DETECTOR: Download: res10_300x300_ssd_iter_140000.caffemodel
-- 
-- General configuration for OpenCV 3.4.0 =====================================
--   Version control:               unknown
-- 
--   Platform:
--     Timestamp:                   2018-01-26T09:54:12Z
--     Host:                        Linux 4.2.0-27-generic x86_64
--     CMake:                       3.8.0-rc2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               RELEASE
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
--       SSE4_1 (3 files):          + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/c++  (ver 4.8.4)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         YES
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc ml objdetect photo python2 python3 python_bindings_generator shape stitching superres ts video videoio videostab
--     Disabled:                    js world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java viz
--     Applications:                tests perf_tests examples apps
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   GUI: 
--     GTK+:                        YES (ver 2.24.23)
--       GThread :                  YES (ver 2.40.2)
--       GtkGlExt:                  NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.2.54)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.3)
--     JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 1.6.1)
-- 
--   Video I/O:
--     DC1394:                      YES (ver 2.2.1)
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 54.35.1)
--       avformat:                  YES (ver 54.20.4)
--       avutil:                    YES (ver 52.3.0)
--       swscale:                   YES (ver 2.1.1)
--       avresample:                NO
--     GStreamer:                   NO
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
--     gPhoto2:                     NO
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Intel IPP:                   2017.0.3 [2017.0.3]
--            at:                   /home/zero/Program/opencv-3.4.0/build/3rdparty/ippicv/ippicv_lnx
--     Intel IPP IW:                sources (2017.0.3)
--               at:                /home/zero/Program/opencv-3.4.0/build/3rdparty/ippicv/ippiw_lnx
--     Lapack:                      YES (/opt/OpenBLAS/lib/libopenblas.so)
--     Eigen:                       YES (ver 3.2.0)
--     Custom HAL:                  NO
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/zero/Program/opencv-3.4.0/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--     numpy:                       /usr/local/lib/python2.7/dist-packages/numpy/core/include (ver 1.13.3)
--     packages path:               lib/python2.7/dist-packages
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.4m.so (ver 3.4.3)
--     numpy:                       /usr/local/lib/python3.4/dist-packages/numpy/core/include (ver 1.13.0)
--     packages path:               lib/python3.4/dist-packages
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:
--     ant:                         NO
--     JNI:                         /home/zero/Downloads/jdk1.8.0_101/include /home/zero/Downloads/jdk1.8.0_101/include/linux /home/zero/Downloads/jdk1.8.0_101/include
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:                        YES
--     mex:                         /usr/local/MATLAB/R2014a/bin/mex
--     Compiler/generator:          Not working (bindings will not be generated)
-- 
--   Install to:                    /opt/local
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zero/Program/opencv-3.4.0/build

**Comment by dkurt** [comment]
@BKZero, can we close it?

**Comment by BKZero** [comment]
sorry, it is caused by another lib who also define int64 with a different data type, so they conflict. i have fixed it.
