### ISSUE TITLE
meanStdDev bug

### ISSUE THREAD

**Issue by hn-88** [opencv/opencv#10694]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Linux Mint 18.1
- Compiler => gcc version 5.4.0

##### Detailed description

meanStdDev seems to give wrong results for large data sets. 

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
  
10000.5 500.032
 
    ```
 or attach as .txt or .zip file
-->

```
Mat m(960,1280,CV_16U);
randn(m,10000, 500);
Scalar M,D;
meanStdDev(m,M,D);
cout << M(0) << " " << D(0) << endl;
Mat m2 = m.reshape(0,1);
meanStdDev(m2,M,D);
cout << M(0) << " " << D(0);
gives
10000.5 500.032
-485.257 24231.6

Instead of 
10000.5 500.032
10000.5 500.032
```

**Comment by hn-88** [comment]
Additional info - found the bug in opencv ver 3.3.1. Tried upgrading to remove the bug. Still has the bug in 3.4.0. Downgraded to 2.4.9.1+dfsg-1.5ubuntu1 and found that the bug is not present for this 2.4.9 version.

**Comment by csukuangfj** [comment]
How `m` is defined and initialized?

**Comment by hn-88** [comment]
Sorry, missed that line in the copy-paste.
`Mat m(960,1280,CV_16U);`

**Comment by terfendail** [comment]
@hn-88 Could you please check the latest master?
Could you please provide your configurtion for cmake?

**Comment by hn-88** [comment]
Cmake configuration for building opencv was 
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.1/modules \
    -D PYTHON_EXECUTABLE=/home/mac/anaconda2/bin/python \
    -D BUILD_EXAMPLES=ON ..
```

Sorry, I have wasted enough time in building and checking for 3.3.1 and 3.4.0 :) Just try running it with the latest master, and if it is fine, you can mark it as not confirmed :)

**Comment by akhandait** [comment]
I ran it with the latest master, it's working fine.
I got this output.
10000.5 500.032
10000.5 500.032

**Comment by hn-88** [comment]
Thanks. So I will close the issue.

**Comment by LaurentBerger** [comment]
Using opencv 4.0-dev : 
```
10000.5 500.032
10000.5 500.032
```

**Comment by Patataman** [comment]
Cool, right now I'm compiling 3.4.4 to see if it still there, if it is, I'll pass to the 4.0.

Thanks!

**Comment by asitjain** [comment]
I am using 4.8.1, bug is still there.

**Comment by LaurentBerger** [comment]
> I am using 4.8.1, bug is still there.

Sorry but I cannot reproduce using code given : 
```
        Mat m(960, 1280, CV_16U);
        randn(m, 10000, 500);
        Scalar M, D;
        meanStdDev(m, M, D);
        cout << M(0) << " " << D(0) << endl;
        Mat m2 = m.reshape(0, 1);
        meanStdDev(m2, M, D);
        cout << M(0) << " " << D(0);

```

Can you post result of getBuildInformation()?
try with  setNumThreads(1 )
try with  ocl::setUseOpenCL(false )

**Comment by hn-88** [comment]
@asitjain , I tested using OpenCV 4.3.0 using the pre-built binaries on Windows, and did not find the bug. My testing workflow is at https://github.com/hn-88/OpenCV-bug-testing/blob/master/.github/workflows/msbuild.yml and the test code is at https://github.com/hn-88/OpenCV-bug-testing/blob/master/OpenCV-bug-testing1.cpp

**Comment by hn-88** [comment]
If @asitjain can confirm which platform gave the error on, for v4.8.1 , I could try and write a test workflow for that platform to test.

**Comment by asitjain** [comment]
@hn-88, I'm currently working with **OpenCV 4.8.1** and **C++** in **Visual Studio 2022 (64-bit) - Version 17.11.0 Preview 1.0**.

I encountered an issue while applying `meanStdDev` to a dataset comprising approximately one million 1x1024D vectors. The dataset is normalized within the 0-255 range, and I've verified that all values fall within this spectrum. However, the computed mean is unexpectedly high at 781.3, and the standard deviation (stddev) is calculated as 0. Conversely, OpenCV's `mean` function yields a mean value of `[1.1466459885007669e+02, 0., 0., 0.]`.

Below is the code snippet that illustrates the process:

```cpp
// Calculate the mean
cv::Scalar mean = cv::mean(floatDataMat);

// Calculate the standard deviation
cv::Mat stdmat = floatDataMat - mean[0];
cv::Mat sqmat;
cv::multiply(stdmat, stdmat, sqmat);

// Sum the squared differences
cv::Scalar sum = cv::sum(sqmat);
double dSum = sum[0];
double stdDev = dSum / (static_cast<double>(floatDataMat.rows) * floatDataMat.cols);
stdDev = sqrt(stdDev);

std::cout << "Mean: " << mean[0] << " StdDev: " << stdDev << std::endl;
```

To troubleshoot, I experimented with smaller subsets of the data. Preliminary tests indicate that when processing only a quarter of the data (around 250,000 vectors), the results appear accurate—yielding a reasonable mean and a non-zero standard deviation. However, these findings are yet to be thoroughly validated.

I hope this information proves useful.

For reference, here are my system specifications:

```plaintext
OS Name: Microsoft Windows 11 Pro
Version: 10.0.22631 Build 22631
System Manufacturer: Dell Inc.
System Model: Precision 3660
Processor: 13th Gen Intel(R) Core(TM) i9-13900K, 3000 Mhz, 24 Core(s), 32 Logical Processor(s)
Installed Physical Memory (RAM): 128 GB
Graphics Card: nVidia RTX4090 24GB
```

**Comment by hn-88** [comment]
Hi @asitjain - please see my test code below - 
```
// generate the data
	Mat floatDataMat(1,1000000,CV_64F);
	randn(floatDataMat,128, 10);
	std::cout << "randn(floatDataMat,128, 10); --> generated data has a mean of 128 and stddev of 10" << std::endl;	

	// Calculate the mean
	cv::Scalar mean = cv::mean(floatDataMat);
	
	// Calculate the standard deviation
	cv::Mat stdmat = floatDataMat - mean[0];
	cv::Mat sqmat;
	cv::multiply(stdmat, stdmat, sqmat);
	
	// Sum the squared differences
	cv::Scalar sum = cv::sum(sqmat);
	double dSum = sum[0];
	double stdDev = dSum / (static_cast<double>(floatDataMat.rows) * floatDataMat.cols);
	stdDev = sqrt(stdDev);
	
	std::cout << "Mean: " << mean[0] << " StdDev: " << stdDev << std::endl;
	std::cout << "The above mean and std dev were as calculated using cv::sum, using static_cast<double> etc." << std::endl;

	meanStdDev(floatDataMat,M,D);
	std::cout << M(0) << " " << D(0) << " This is using meanStdDev(floatDataMat,M,D);" << std::endl;
	Mat fdm2 = floatDataMat.reshape(0,1);
	meanStdDev(fdm2,M,D);
	std::cout << M(0) << " " << D(0) << " This is using meanStdDev(floatDataMat.reshape(0,1),M,D);" << std::endl;

```
With the precompiled binaries of opencv v4.3.1, the meanStdDev() gave the correct answers. 
```
Mean: 128.005 StdDev: 9.98733
The above mean and std dev were as calculated using cv::sum, using static_cast<double> etc.
128.005 9.98733 This is using meanStdDev(floatDataMat,M,D);
128.005 9.98733 This is using meanStdDev(floatDataMat.reshape(0,1),M,D);
```
Will check for v4.8.1 also next. Meanwhile, please let me know if the above test reasonably approximates your data, and whether you have also used the pre-compiled binaries from https://github.com/opencv/opencv/releases or whether you have compiled v4.8.1 yourself.

**Comment by hn-88** [comment]
@asitjain - maybe the data should have been `Mat floatDataMat(1024,1000000,CV_64F);` and not `Mat floatDataMat(1,1000000,CV_64F);` for my testing? With `(1,1000000)`, testing with v4.8.1, no errors. But I get an out of memory error if I try `(1024,1000000)` - so, sorry, I can't test for this case. 

The github workflow to make this test build is at
https://github.com/hn-88/OpenCV-bug-testing/blob/vTesting1.0/.github/workflows/msbuild481.yml

I've put the built exe here,
https://github.com/hn-88/OpenCV-bug-testing/releases/tag/vTesting1.0

**Comment by hn-88** [comment]
```
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.8.1) Error: Insufficient memory (Failed to allocate 8192000000 bytes) in cv::OutOfMemoryError, file C:\GHA-OCV-2\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp, line 73
```
is the error I get. My computer has only 8 GB RAM.

**Comment by asitjain** [comment]
@hn-88, I've tested the code you shared, and it aligns perfectly with all three methods. I've also adapted the code for my specific data type `CV_32F` and the vector dimensions:

```cpp
cv::Mat floatDataMat(1024, 1000000, CV_32FC1);
```

The results were impeccable. Interestingly, when I reverted to using `meanStdDev` with my original dataset, it functioned correctly, which is unexpected since I cannot seem to replicate the previously reported error. The only notable change since then is an update to the Visual Studio preview that occurred yesterday.

**Comment by hn-88** [comment]
Thanks for clarifying, @asitjain . Will close this issue again.

**Comment by asitjain** [comment]
I tested again with my full data. The function indeed has bug. 

Here is how I call it

`cv::meanStdDev(tempU8, s_mean, cv::noArray());`


details of tempU8 Mat

<img width="626" alt="image" src="https://github.com/opencv/opencv/assets/31441485/bdf6f637-5563-466e-85b5-d4245ac3287f">




I tried to dig down the opencv code, but I am not familiar with it. Here is a screengrab of the offending(?) function :

<img width="1467" alt="vs2022 opencv" src="https://github.com/opencv/opencv/assets/31441485/bf465344-8874-412c-b9b6-ac72ad68b7f1">



As you can see, it never enters the for loop because x is 1024, so variable i is being initializing to 1024 and len is also 1024. 

@hn-88 if you need any other info, I will be happy to provide it and run tests.

**Comment by hn-88** [comment]
@asitjain - is the tempU8 Mat an unsigned char? How have you defined tempU8? What is the opencv data type for it?

**Comment by asitjain** [comment]
@hn-88 Sorry for incomplete info. 

`cv::Mat tempU8(FullDictDataU8.size() / BlockArea, BlockArea, CV_8UC1, FullDataU8.data());`

and the vector is

`std::vector<uint8_t> FullDataU8;`

The vector is read from a file. The vector elements are 'uchar' type so the values can only be in the 0-255 range.

**Comment by hn-88** [comment]
@asitjain  - can you please check if casting the Mat to CV64F before calling meanStdDev solves the problem?

**Comment by asitjain** [comment]
@hn-88 Well, I do not have enough memory to convert the data to double, or even float.

**Comment by hn-88** [comment]
Ok. I'll try to create a simple test similar to the first post of this thread. (Or you can do that, and post it as a separate bug report.)

**Comment by asitjain** [comment]
@hn-88 one more interesting observation. Documentation for isContinuous says:

> Matrices created with [Mat::create] are always continuous

[https://docs.opencv.org/4.8.0/d3/d63/classcv_1_1Mat.html#a55ced2c8d844d683ea9a725c60037ad0](url) 

But my testing says otherwise. 

`cv::Mat floatDataMat(1,10000000*512, CV_32FC1);` is continuous.

But `cv::Mat floatDataMat(10000000,512, CV_32FC1);` is not. 

And `cv::Mat floatDataMat(512, 10000000, CV_32FC1);` is also not continous!

Also, could it be an alignment issue?

**Comment by hn-88** [comment]
> @hn-88 one more interesting observation. Documentation for isContinuous says:
> 
> > Matrices created with [Mat::create] are always continuous
> 
> [https://docs.opencv.org/4.8.0/d3/d63/classcv_1_1Mat.html#a55ced2c8d844d683ea9a725c60037ad0](url)
> 
> But my testing says otherwise.
> 
> `cv::Mat floatDataMat(1,10000000*512, CV_32FC1);` is continuous.
> 
> But `cv::Mat floatDataMat(10000000,512, CV_32FC1);` is not.
> 
> And `cv::Mat floatDataMat(512, 10000000, CV_32FC1);` is also not continous!
> 
> Also, could it be an alignment issue?

@asitjain - I'm not an opencv maintainer, just a user like yourself. Also, this continuous/non-continuous issue is most probably not related to this thread about meanStdDev(). It may be better if you create a  new thread to post this continuous/non-continuous issue.

**Comment by hn-88** [comment]
> Ok. I'll try to create a simple test similar to the first post of this thread. (Or you can do that, and post it as a separate bug report.)

@asitjain - please see my test code at https://github.com/hn-88/OpenCV-bug-testing/blob/4e8dac53e1fafd2964aec6b9dbc4a2b4541ca7c2/OpenCV-bug-testing1.cpp#L63

The main difference seems to be that you have used cv::noArray() and I have not.

This code compiles and runs and seems to return the correct answer:
```
v481x64Win10
10000.5 500.032
10000.5 500.032
The above was for randn(m,10000,500)
Now testing for 1,000,000 with the bug report code from asitjain
a dataset comprising approximately one million 1x1024D vectors. The dataset is normalized within the 0-255 range ...
randn(u8DataMat,128, 10); --> generated data has a mean of 128 and stddev of 10
Mean: 128 StdDev: 6.38714
The above mean and std dev were as calculated using cv::sum, using static_cast<double> etc.
128 10.0042 This is using meanStdDev(u8DataMat,M,D);
128 10.0042 This is using meanStdDev(u8DataMat.reshape(0,1),M,D);
```

**Comment by asitjain** [comment]
@hn-88 I will check that out and report. One more thing I noticed that the cv::Mat::rows and columns are int type, and creating a large cv::Mat sets them to negative. This could be related.

I am now using this code which is performing accurate and fast : 

```

// Helper function to calculate sum and sum of squares using SIMD intrinsics
void update_stats_avx(const uint8_t* data, size_t size, double& sum, double& sum_of_squares, long long& count) {
    __m256i v_sum = _mm256_setzero_si256();
    __m256i v_sum_of_squares = _mm256_setzero_si256();

    for (size_t i = 0; i < size; i += 32) {
        __m256i v_data = _mm256_load_si256(reinterpret_cast<const __m256i*>(data + i));

        __m128i v_low = _mm256_castsi256_si128(v_data);
        __m128i v_high = _mm256_extracti128_si256(v_data, 1);

        __m256i v_low16 = _mm256_cvtepu8_epi16(v_low);
        __m256i v_high16 = _mm256_cvtepu8_epi16(v_high);

        __m256i v_low_low = _mm256_cvtepu16_epi32(_mm256_castsi256_si128(v_low16));
        __m256i v_low_high = _mm256_cvtepu16_epi32(_mm256_extracti128_si256(v_low16, 1));
        __m256i v_high_low = _mm256_cvtepu16_epi32(_mm256_castsi256_si128(v_high16));
        __m256i v_high_high = _mm256_cvtepu16_epi32(_mm256_extracti128_si256(v_high16, 1));

        __m256i v_x[4] = { v_low_low, v_low_high, v_high_low, v_high_high };

        for (int j = 0; j < 4; ++j) {
            v_sum = _mm256_add_epi32(v_sum, v_x[j]);
            v_sum_of_squares = _mm256_add_epi32(v_sum_of_squares, _mm256_mullo_epi32(v_x[j], v_x[j]));
        }

        count += 32;
    }

    alignas(my_alignment) int sum_array[8];
    alignas(my_alignment) int sum_of_squares_array[8];

    _mm256_store_si256(reinterpret_cast<__m256i*>(sum_array), v_sum);
    _mm256_store_si256(reinterpret_cast<__m256i*>(sum_of_squares_array), v_sum_of_squares);

    sum+= std::accumulate(sum_array, sum_array + 8, 0.0);
    sum_of_squares += std::accumulate(sum_of_squares_array, sum_of_squares_array + 8, 0.0);
}

void process_chunk(const std::vector<uint8_t>& DataU8, std::atomic<double>& global_sum, std::atomic<double>& global_sum_of_squares, std::atomic<long long>& global_count) {
    using namespace std;

    int max_threads = omp_get_max_threads();
    vector<double> local_sums(max_threads, 0.0);
    vector<double> local_sums_of_squares(max_threads, 0.0);
    vector<long long> local_counts(max_threads, 0);

#pragma omp parallel
    {
        int tid = omp_get_thread_num();
        double& local_sum = local_sums[tid];
        double& local_sum_of_squares = local_sums_of_squares[tid];
        long long& local_count = local_counts[tid];

#pragma omp for
        for (long long i = 0; i < DataU8.size(); i += 32) {
            size_t chunk_size = std::min(32LL, static_cast<long long>(DataU8.size() - i));
            update_stats_avx(&DataU8[i], chunk_size, local_sum, local_sum_of_squares, local_count);
        }
    }

    // Combine local stats into global stats
    double total_sum = 0.0;
    double total_sum_of_squares = 0.0;
    long long total_count = 0;

    for (int i = 0; i < max_threads; ++i) {
        total_sum += local_sums[i];
        total_sum_of_squares += local_sums_of_squares[i];
        total_count += local_counts[i];
    }

    global_sum += total_sum;
    global_sum_of_squares += total_sum_of_squares;
    global_count += total_count;
}

```

To use it you need your data to be aligned:

```
alignas(32) std::vector<uint8_t> FullDataU8;
//Fill your large U8 data, tested with 37 Billion elements!
.....
.....
std::atomic<double> sum = 0.0;
std::atomic<double> sum_of_squares = 0.0;
std::atomic<long long> count = 0;

process_chunk(FullDataU8, sum, sum_of_squares, count);

double calc_mean = sum / count;
double variance = (sum_of_squares / count) - (calc_mean * calc_mean);
double stddev = sqrt(variance);

std::cout << "Mean: " << calc_mean << "\n";
std::cout << "Standard Deviation: " << stddev << "\n";
```

It takes around 10 Seconds on my machine for 37 Billion elements.
