### ISSUE TITLE
Problem with convexityDefects

### ISSUE THREAD

**Issue by FredOleary** [opencv/opencv#10704]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

#####  Hello, I'm trying to develop a shape detection app and while it is working as expected on most images, some images appear to fail with an incorrect number of defects from method convexityDefects

In the attached image:

1. The red lines show the contours found. There are four. The smallest 3 are ignored. (These contours look OK)
2. The light blue line shows the approximated polygon for the largest contour using approxPolyDP(). This also looks correct
3. The dark blue line shows hull covering approximated polygon. This also looks correct.

The problem is that convexityDefects() returns only two defects between the hull and polygon and the "distance" value in each result is far too low.(From inspection there should be about 8-10 defects)

The algorithm used is:
1. Color filter the image shown to a monochrome image, (MI) using "inRange" . 
2. Dilate MI using "morphologyEx" to remove noise
3. use "Canny" against MI to produce a black background with white 'edges/contours'

4. Use "findContours" to detect the contour set. (There are four) Ignore the 3 smallest
5. Use "approxPolyDP()" to produce an approximated contour. (AC)
6. Use "convexHull" against AC to get the hull
7. Use "convexityDefects" the retrieve the defect list. (Only two defects are yielded!!)

-->
![screenshot_thermalimage](https://user-images.githubusercontent.com/3505461/35466391-4961b050-02b8-11e8-9450-e6c3e385a3ae.png)

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by sturkmen72** [comment]
"The problem is that convexityDefects() returns only two defects between the hull and polygon"

i see only two defects

**Comment by sturkmen72** [comment]
please close down this issue
