### ISSUE TITLE
 undefined reference to `cv::ocl::initializeContextFromHandle(cv::ocl::Context&, void*, void*, void*)'

### ISSUE THREAD

**Issue by arpu** [opencv/opencv#10714]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => ubuntu lts 16.04  64 Bit
- Compiler => g++ 5.4.0

##### Detailed description
on linking i get 
undefined reference to `cv::ocl::initializeContextFromHandle(cv::ocl::Context&, void*, void*, void*)'
##### Steps to reproduce
 g++   -std=c++11   -std=gnu++11 -Wall -std=c++11 test.cpp    -I/usr/local/include -I/opt/rocm/include/   -lOpenCL  -lopencv_core -lopencv_imgproc -lopencv_imgcodecs 

anything i missing?

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
We don't help with remote investigation of problems (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by arpu** [comment]
ok i have add this to snwers.opencv.org at http://answers.opencv.org/question/183434/undefined-reference-to-cvoclinitializecontextfromhandlecvoclcontext-void-void-void/
for me the cv::ocl::initializeContextFromHandle should be in the -lopencv_core libs

**Comment by alalek** [comment]
Actually `cv::ocl::initializeContextFromHandle()` symbol is not in the exported list. It should not be used outside of opencv_core.

**Comment by arpu** [comment]
is it possible to add this to the exported list? 

the idea is to use this as a bridge for https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules

code sample
http://lpaste.net/7612914576807428096

any suggestion what we should use?

**Comment by arpu** [comment]
the idea is to use the same opencl context for opencv and loom

**Comment by alalek** [comment]
Check for `cv::ocl::attachContext()` function.

**Comment by arpu** [comment]
thx perfect! this works fine
