### ISSUE TITLE
DNN: OpenCL build warning on Mac

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10710]
Issues:
- Malformed build options ("multiple spaces" problem on Apple OpenCL)
- T-API fallback failure?

Related: #10672

[Log example](http://pullrequest.opencv.org/buildbot/builders/master-mac/builds/10353/steps/test_dnn-ippicv-opencl/logs/stdio):
```
[ RUN      ] OCL_Torch_Importer.FastNeuralStyle_accuracy
OpenCL program build log: dnn/mvn
Status -43: CL_INVALID_BUILD_OPTIONS
-DNUM=8 -DNORM_VARIANCE -DFUSE_BATCH_NORM   -D INTEL_DEVICE

/build/master-mac/opencv/modules/dnn/test/test_common.hpp:54: Failure
Expected: (normL1) <= (l1), actual: 40.2811 vs 0.5
/build/master-mac/opencv/modules/dnn/test/test_common.hpp:57: Failure
Expected: (normInf) <= (lInf), actual: 227.748 vs 1.1
[  FAILED  ] OCL_Torch_Importer.FastNeuralStyle_accuracy (3898 ms)
```

**Comment by pengli** [comment]
in PR https://github.com/opencv/opencv/pull/10717 , it include a patch that should fix the extra spaces in the build option.
