### ISSUE TITLE
function requirement about tf model read: StridedSlice support

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10716]
opencv 3.4.0, tensorflow model under version 1.2.1
I use tensorflow-slim to define my network and in the definition include the operator like:
net = net[:,1:-1,1:-1,:]
and freeze the model to pb file it include the layer:
fastnet_v2/strided_slice_1
but now the version of opencv seems not support this operator when Initialize network, it gives the error:
OpenCV Error: Unspecified error (Unknown layer type StridedSlice in op fastnet_v2/strided_slice_1) in populateNet, file opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487
terminate called after throwing an instance of 'cv::Exception'
  what():  opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:1487: error: (-2) Unknown layer type StridedSlice in op fastnet_v2/strided_slice_1 in function populateNet

so can you please consider to add support in future?

**Comment by dkurt** [comment]
@BKZero, please use http://answers.opencv.org for usage question. Provide a minimal working example to understand what kind of network is used.

**Comment by dkurt** [comment]
@BKZero, it still require a minimal working example to build a model using TensorFlow. We need to know a topology of network to understand what operation need to be implemented or it could be easily replaced in your graph.

**Comment by BKZero** [comment]
one can change to tf.slice when define a network

**Comment by GPhilo** [comment]
@BKZero no, one can't if you need to do a _strided_ slice. Say I have a 1D tensor `t`, of which I want every other element. The only way to do this is via `StridedeSlice`: `t[::2]`, which as of now cannot be imported in opencv.
