### ISSUE TITLE
 OpenCV Error: Insufficient memory (Failed to allocate 3686400 bytes) in void* cv::OutOfMemoryError

### ISSUE THREAD

**Issue by tsingjinyun** [opencv/opencv#10725]
i have use opencv3.4' dnn module, and porting to android, run the app after about 8-9hours, then the app break down,and the log :: 
01-29 14:13:18.886 985-1454/? E/cv::error(): OpenCV Error: Insufficient memory (Failed to allocate 3686400 bytes) in void* cv::OutOfMemoryError(size_t), file /export/tmp/myOpencv/opencv/modules/core/src/alloc.cpp, line 55
01-29 14:13:18.886 985-1454/? E/cv::error(): OpenCV Error: Assertion failed (u != 0) in void cv::Mat::create(int, const int*, int), file
 /export/tmp/myOpencv/opencv/modules/core/src/matrix.cpp, line 436
                                             
                                             --------- beginning of crash

@alalek,@foundry, any advices? or do you run the programm come across this problem

**Comment by alalek** [comment]
Take a look on discussion about issues of memory management in Java here: #4019

**Comment by tsingjinyun** [comment]
ok ,thanks @alalek

**Comment by sailokeshgoud** [comment]
I am new to this can anyone give me code snippet or something to solve this error

**Comment by SamarFatima** [comment]
If you are using python then using 32 bit version can result in this error. Try using 64 bit version and allowing it the memory permission it ask for in the installation. I am not sure about the permission but 32 bit version could be the main cause.
