### ISSUE TITLE
TensorFlow Object Detection API wiki lacks some links! 

### ISSUE THREAD

**Issue by mahsaayi** [opencv/opencv#10729]
Hello,
Tensorflow object detection api [wiki](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) written by @dkurt lacks the ssd inception config file and the tf_text_graph_ssd.py script links! the links return not found page. 
Thanks for great wiki but the links are so needed!

**Comment by dkurt** [comment]
@mahsaayi, see PRs https://github.com/opencv/opencv/pull/10701 and https://github.com/opencv/opencv_extra/pull/433 and https://github.com/opencv/opencv/pull/10723. Links will be correct after merging. Can we close an issue?
