### ISSUE TITLE
OpenCV Error: Assertion failed (type2 == 6 && (sz2.height == 1 || sz2.height == 4)) in arithm_op

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10726]
opencv3.4.0
run dnn and got the error:
OpenCV Error: Assertion failed (type2 == 6 && (sz2.height == 1 || sz2.height == 4)) in arithm_op, file /home/zero/Program/opencv-3.4.0/modules/core/src/arithm.cpp, line 662
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/zero/Program/opencv-3.4.0/modules/core/src/arithm.cpp:662: error: (-215) type2 == 6 && (sz2.height == 1 || sz2.height == 4) in function arithm_op

print the log and i see type2 has the value 5. i do not know what happen.
i use the code with tensorflow dnn model, tf_inception.cpp, the detail of definition of network is in #10720

**Comment by dkurt** [comment]
@BKZero, please make it possible to reproduce an issue for everyone. Attach a minimal working example. Attach the model or it's references. Let contributors spend more time to solve an issue rather to reproduce it. Thanks!

**Comment by BKZero** [comment]
i am sorry.
the model file and name file is:
[2.pb.zip](https://github.com/opencv/opencv/files/1676878/2.pb.zip)
[layerlist.txt](https://github.com/opencv/opencv/files/1676874/layerlist.txt)
i modify the tf_inception.cpp as:
int main(int argc, char **argv)
{
    cv::CommandLineParser parser(argc, argv, keys);

    if (parser.has("help"))
    {
        parser.printMessage();
        return 0;
    }

    String modelFile = "2.pb";
    String imageFile = "foo-002.jpeg";
    String inBlobName = "opencv_v1/InputPlaceholder";
    String outBlobName = "opencv_v1/Output";

    if (!parser.check())
    {
        parser.printErrors();
        return 0;
    }

    String classNamesFile = "layerlist.txt"; //parser.get<String>("c_names");
    String resultFile = "result.txt"; //parser.get<String>("result");

    //! [Initialize network]
    dnn::Net net = readNetFromTensorflow(modelFile);
    //! [Initialize network]

    if (net.empty())
    {
        std::cerr << "Can't load network by using the mode file: " << std::endl;
        std::cerr << modelFile << std::endl;
        exit(-1);
    }

    //! [Prepare blob]
    Mat img = imread(imageFile);
    if (img.empty())
    {
        std::cerr << "Can't read image from the file: " << imageFile << std::endl;
        exit(-1);
    }

    cv::Mat img_gray;
    std::cout<<"after read img"<<std::endl;
    cv::cvtColor(img, img_gray, cv::COLOR_BGR2GRAY);

    Mat inputBlob = blobFromImage(img_gray, 1.0f, Size(39, 39), Scalar(), true, false);   //Convert Mat to batch of images
    //! [Prepare blob]
    inputBlob -= 117.0;

    std::cout<<"blobFromImage"<<std::endl;
    //! [Set input blob]
    net.setInput(inputBlob, inBlobName);        //set the network input
    //! [Set input blob]

    std::cout<<"setInput"<<std::endl;

    cv::TickMeter tm;
    tm.start();

    //! [Make forward pass]
    Mat result = net.forward(outBlobName);                          //compute output
    //! [Make forward pass]

    std::cout<<"forward"<<std::endl;

    tm.stop();

    if (!resultFile.empty()) {
        CV_Assert(result.isContinuous());

        ofstream fout(resultFile.c_str(), ios::out | ios::binary);
        fout.write((char*)result.data, result.total() * sizeof(float));
        fout.close();
    }

    std::cout << "Output blob shape " << result.size[0] << " x " << result.size[1] << " x " << result.size[2] << " x " << result.size[3] << std::endl;
    std::cout << "Inference time, ms: " << tm.getTimeMilli()  << std::endl;

    if (!classNamesFile.empty()) {
        std::vector<String> classNames = readClassNames(classNamesFile.c_str());

        int classId;
        double classProb;
        getMaxClass(result, &classId, &classProb);//find the best class

        //! [Print results]
        std::cout << "Best class: #" << classId << " '" << classNames.at(classId) << "'" << std::endl;
        std::cout << "Probability: " << classProb * 100 << "%" << std::endl;
    }
    return 0;
} //main

**Comment by BKZero** [comment]
the network definition file:
[opencv_v1.py.zip](https://github.com/opencv/opencv/files/1676937/opencv_v1.py.zip)

**Comment by dkurt** [comment]
@BKZero, `reshape` layer produces output of shape `[-1, 10]` but then we try to add zeros of shape `[1, 1]`. Perhaps, TensorFlow can manage it broadcasting a single value. Does it expected behavior or you want to use a single variable?

**Comment by BKZero** [comment]
@dkurt i want a output of length 10, but if i make a zero vector of shape [1, 10] or [10], after getConstBlob(layer, value_id), the size of the tensor became 1, in  #10720 i describe the problem. so to solve that problem, i have to change the zero vector to a shape [1,1].
in this issue, i follow the code and get the type2 value 5, but it is expected 6.
