### ISSUE TITLE
opencv dnn import tf model error

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10720]
Here is my net definition:
  with tf.variable_scope(scope, 'opencv_v1', [images, num_classes]):

    image_gray = images[:,:,:,0:1]
    images_input = tf.placeholder_with_default(image_gray, shape=[None, 39, 39, 1], name='InputPlaceholder')

    net = slim.conv2d(images_input, 16, [4, 4], padding='VALID', scope='conv1')
    end_points['conv1'] = net

    net = slim.max_pool2d(net, [2, 2], 2, scope='pool1')
    end_points['pool1'] = net

    net = slim.conv2d(net, 32, [3, 3], padding='VALID', scope='conv2')
    end_points['conv2'] = net

    net = slim.max_pool2d(net, [2, 2], 2, scope='pool2')
    end_points['pool2'] = net

    print('net')
    print(net)

    net = slim.conv2d(net, 10, [8, 8], padding='VALID', scope='conv3')
    end_points['conv2'] = net

    net = tf.reshape(net,[-1, 10])
    # net = tf.concat([net], 1)

    zero = tf.zeros([1, num_classes], name="zero")
    # output = tf.identity(net, name="Output")
    output = tf.add(net, zero, name="Output")
    end_points['Output'] = output

and when i use the tf_inception.cpp sample file to test the pb file, i got:
layersize 22
Conv2D
float
size (int)dstBlob.total() 16 16
Conv2D
float
size (int)dstBlob.total() 32 32
Conv2D
float
size (int)dstBlob.total() 10 10
reshape
add 21 opencv_v1/Output
float
size (int)dstBlob.total() 1 10
OpenCV Error: Assertion failed (size == (int)dstBlob.total()) in parseTensor, file /home/zero/Program/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 179
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/zero/Program/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:179: error: (-215) size == (int)dstBlob.total() in function parseTensor

the above is my log in tf_importer.cpp
the error occurs when it comes "output = tf.add(net, zero, name="Output")" in model definition. and in the code block
else if (type == "BiasAdd" || type == "Add"){} in tf_importer.cpp
i find where it crashes, but i do not know why after getConstBlob(layer, value_id), the size comes to 1.

here is my pb file name list:
opencv_v1/InputPlaceholder
opencv_v1/conv1/weights
opencv_v1/conv1/biases
opencv_v1/conv1/convolution
opencv_v1/conv1/BiasAdd
opencv_v1/conv1/Relu
opencv_v1/pool1/MaxPool
opencv_v1/conv2/weights
opencv_v1/conv2/biases
opencv_v1/conv2/convolution
opencv_v1/conv2/BiasAdd
opencv_v1/conv2/Relu
opencv_v1/pool2/MaxPool
opencv_v1/conv3/weights
opencv_v1/conv3/biases
opencv_v1/conv3/convolution
opencv_v1/conv3/BiasAdd
opencv_v1/conv3/Relu
opencv_v1/Reshape/shape
opencv_v1/Reshape
opencv_v1/zeros
opencv_v1/Output

i am not sure if it is a bug, but the pb file works well under tensorflow.

**Comment by BKZero** [comment]
i am not sure if the problem is in getTensorContent or in getConstBlob

**Comment by dkurt** [comment]
@BKZero, Please keep all the details in a single issue. This one or https://github.com/opencv/opencv/issues/10716 can be closed.

**Comment by BKZero** [comment]
@dkurt
but they are different problems. if one must be closed, please close the other one.

**Comment by BKZero** [comment]
@dkurt i will give an example about the slice problem later

**Comment by dkurt** [comment]
@BKZero, I'm sorry. I see. Just issue's description looks inaccurate so it's hard to see it's topic.

**Comment by BKZero** [comment]
@dkurt 
if i replace the conv2 layer to a slice operation and a conv, the network becomes like follow:
  with tf.variable_scope(scope, 'opencv_v1', [images, num_classes]):

    image_gray = images[:,:,:,0:1]
    images_input = tf.placeholder_with_default(image_gray, shape=[None, 39, 39, 1], name='InputPlaceholder')

    net = slim.conv2d(images_input, 16, [4, 4], padding='VALID', scope='conv1')
    end_points['conv1'] = net

    net = slim.max_pool2d(net, [2, 2], 2, scope='pool1')
    end_points['pool1'] = net

    # net = slim.conv2d(net, 32, [3, 3], padding='VALID', scope='conv2')
    net = net[:,1:-1,1:-1,:]
    net = slim.conv2d(net, 32, [3, 3], padding='SAME', scope='conv2')
    end_points['conv2'] = net

    net = slim.max_pool2d(net, [2, 2], 2, scope='pool2')
    end_points['pool2'] = net

    print('net')
    print(net)

    net = slim.conv2d(net, 10, [8, 8], padding='VALID', scope='conv3')
    end_points['conv2'] = net

    net = tf.reshape(net,[-1, 10])
    # net = tf.concat([net], 1)

    zero = tf.zeros([1, num_classes], name="zero")
    # output = tf.identity(net, name="Output")
    output = tf.add(net, zero, name="Output")
    end_points['Output'] = output

And the layer list in the pb file is:
opencv_v1/InputPlaceholder
opencv_v1/conv1/weights
opencv_v1/conv1/biases
opencv_v1/conv1/convolution
opencv_v1/conv1/BiasAdd
opencv_v1/conv1/Relu
opencv_v1/pool1/MaxPool
opencv_v1/strided_slice_1/stack
opencv_v1/strided_slice_1/stack_1
opencv_v1/strided_slice_1/stack_2
opencv_v1/strided_slice_1
opencv_v1/conv2/weights
opencv_v1/conv2/biases
opencv_v1/conv2/convolution
opencv_v1/conv2/BiasAdd
opencv_v1/conv2/Relu
opencv_v1/pool2/MaxPool
opencv_v1/conv3/weights
opencv_v1/conv3/biases
opencv_v1/conv3/convolution
opencv_v1/conv3/BiasAdd
opencv_v1/conv3/Relu
opencv_v1/Reshape/shape
opencv_v1/Reshape
opencv_v1/zero
opencv_v1/Output

Then run the opencv demo, i got:
layersize 26
Conv2D
float
size 16 16

opencv_v1/strided_slice_1:StridedSlice(opencv_v1/pool1/MaxPool)(opencv_v1/strided_slice_1/stack)(opencv_v1/strided_slice_1/stack_1)(opencv_v1/strided_slice_1/stack_2)
shrink_axis_mask:[ ]
_output_shapes:[ ]
end_mask:[ ]
new_axis_mask:[ ]
ellipsis_mask:[ ]
begin_mask:[ ]
T:0
Index:[ ]
OpenCV Error: Unspecified error (Unknown layer type StridedSlice in op opencv_v1/strided_slice_1) in populateNet, file /home/zero/Program/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 1491
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/zero/Program/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:1491: error: (-2) Unknown layer type StridedSlice in op opencv_v1/strided_slice_1 in function populateNet

Aborted (core dumped)

**Comment by BKZero** [comment]
make a brief summery, there are two problem i encountered:
first is about the add operation, i got an assertion failed error:
OpenCV Error: Assertion failed (size == (int)dstBlob.total()) in parseTensor
i have looked up the code, and the problem may be occured in the getConstBlob(layer, value_id) function in 850 line or around in the file tf_importer.cpp. i did not debug it further, maybe you can have a look why the size are different.
the second problem is simple, opencv do not support strided slice layer now.
the python code is simple, i made a list slice operation: net = net[:,1:-1,1:-1,:]
but the tensorflow convert it to a slice layer, opencv does not support it right now.
i am not sure if there are any operation can replace it.
thank you

**Comment by BKZero** [comment]
i have found the problem. it is the zero vector.
when i write zero = tf.zeros([1, num_classes], name="zero") or zero = tf.zeros([num_classes], name="zero") in python code, the (int)dstBlob.total() is remain size 10(my num class is 10), but after getConstBlob(layer, value_id), the size of the tensor became 1.

**Comment by tsvetiko** [comment]
Upgrading OpenCV to version `3.4.2` solved my issue. So do `pip install opencv-python==3.4.2`.
