### ISSUE TITLE
OpenCV3 possible bug of normalize function

### ISSUE THREAD

**Issue by antran89** [opencv/opencv#10728]
Hi all,
I see a behavior of cv2.normalize() function in OpenCV3 which is different with OpenCV2.

##### System information (version)

- OpenCV => 3 (latest version)
- Operating System / Platform => Ubuntu 64bit
- Compiler => GCC (it does not matter)

##### Detailed description
Current output array `dst` is `InputOutputArray`. It is inconvenient, which we need to pass one more input in Python interface.
```
CV_EXPORTS_W void normalize( InputArray src, InputOutputArray dst, double alpha = 1, double beta = 0, int norm_type = NORM_L2, int dtype = -1, InputArray mask = noArray());
```
For example, in Python OpenCV3, I need to write
```
test_hist = cv2.normalize(test_hist, np.array([]))
```
which is troublesome and error-prone.

While in OpenCV2, I only need to simply write
```
test_hist = cv2.normalize(test_hist)
```

If the core developers agree with me this is an bug, I can make a PR. We only need to change `InputOutputArray` to `OutputArray`.

Thanks.

**Comment by alalek** [comment]
> output array

Because it is not "output" only. Depends on "flags".

BTW, Anyway this interface itself is not good. Making "GOD" interfaces is not a good idea in general. Also there is no problem in C++ to make overload or additional function with slightly alternative name.

**Comment by antran89** [comment]
Agree, making a "GOD" interfaces is not a good idea. 👍 

> Because it is not "output" only

Can you elaborate on this point? Which flags do we use it as an Input array?
