### ISSUE TITLE
opencv dnn import error keras vgg16

### ISSUE THREAD

**Issue by MennoK** [opencv/opencv#10722]
Hi,

I'm trying to export the keras VGG16 model to a tensorflow model and then I  import the tensorflow model into opencv. To do this, I got the following python code:

```python
from keras import applications
from keras import backend as K
import cv2 as cv
import tensorflow as tf
from tensorflow.python.framework import graph_util
from tensorflow.python.framework import graph_io

model = applications.VGG16(input_shape=(224, 224, 3), weights='imagenet', include_top=True)
K.set_learning_phase(0)

pred_node_names = [None]
pred = [None]
for i in range(1):
    pred_node_names[i] = "output_node"+str(i)
    pred[i] = tf.identity(model.outputs[i], name=pred_node_names[i])

sess = K.get_session()
constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), pred_node_names)
graph_io.write_graph(constant_graph, ".", "model.pb", as_text=False)

net = cv.dnn.readNetFromTensorflow('model.pb')
```

Executing this code, gives following error (same in C++):
```
cv2.error: C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1487: error: (-2) Unknown layer type Shape in op flatten/Shape in function cv::dnn::experimental_dnn_v3::`anonymous-namespace'::TFImporter::populateNet
```

When I'm not including the top, I don't receive this error message.

Do you have any suggestions? I tried the suggestion in [issue #1214](https://github.com/opencv/opencv_contrib/issues/1241). However I'm not able to implement this for the imported model.

**Comment by dkurt** [comment]
@MennoK, please run the following script https://gist.github.com/dkurt/ff1b2dd272e544e6873c54d3a571662a for you model. I suggest you to open a question at http://answers.opencv.org and attach a received file there.

**Comment by dkurt** [comment]
@MennoK, it looks like we can close an issue?

see http://answers.opencv.org/question/183507/opencv-dnn-import-error-for-keras-pretrained-vgg16-model/

**Comment by MennoK** [comment]
Yes. Thanks again
