### ISSUE TITLE
OpenCV Error: Incorrect size of input array (Inconsitent shape for ConcatLayer) in getMemoryShapes, file opencv-3.4.0/modules/dnn/src/layers/concat_layer.cpp, line 91 terminate called after throwing an instance of 'cv::Exception'   what():  opencv-3.4.0/modules/dnn/src/layers/concat_layer.cpp:91: error: (-201) Inconsitent shape for ConcatLayer in function getMemoryShapes

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10739]
opencv 3.4.0
ubuntu 14.04
tensorflow 1.1
the example file
[2.pb.zip](https://github.com/opencv/opencv/files/1681424/2.pb.zip)
[opencv_v1.py.zip](https://github.com/opencv/opencv/files/1681425/opencv_v1.py.zip)
[layerlist.txt](https://github.com/opencv/opencv/files/1681426/layerlist.txt)

the error:
OpenCV Error: Incorrect size of input array (Inconsitent shape for ConcatLayer) in getMemoryShapes, file opencv-3.4.0/modules/dnn/src/layers/concat_layer.cpp, line 91
terminate called after throwing an instance of 'cv::Exception'
  what():  opencv-3.4.0/modules/dnn/src/layers/concat_layer.cpp:91: error: (-201) Inconsitent shape for ConcatLayer in function getMemoryShapes

Aborted (core dumped)

i add log in concat_layer.cpp like:

                CV_Assert(curShape.size() == outputs[0].size()); std::cout<<"concat before for "<<outputs[0].size()<<std::endl;
                for (int curAxis = 0; curAxis < outputs[0].size(); curAxis++)
                {
                    std::cout<<"concat "<<curAxis<<" "<<cAxis<<" "<<outputs[0][curAxis]<<" "<<curShape[curAxis]<<std::endl;
                    if (curAxis != cAxis && outputs[0][curAxis] != curShape[curAxis])
                        CV_Error(Error::StsBadSize, "Inconsitent shape for ConcatLayer");
                }
and got log:
concat before for 4
concat 0 3 1 1
concat 1 3 15 15
concat 2 3 16 16
concat 3 3 18 18
concat before for 4
concat 0 3 1 1
concat 1 3 15 32

my code:
  int main(int argc, char **argv)
  {
    cv::CommandLineParser parser(argc, argv, keys);

    if (parser.has("help"))
    {
        parser.printMessage();
        return 0;
    }

    String modelFile = "2.pb";
    String imageFile = "foo-002.jpeg";
    String inBlobName = "opencv_v1/InputPlaceholder";
    String outBlobName = "opencv_v1/Output";

    if (!parser.check())
    {
        parser.printErrors();
        return 0;
    }

    String classNamesFile = "layerlist.txt"; //parser.get<String>("c_names");
    String resultFile = "result.txt"; //parser.get<String>("result");

    //! [Initialize network]
    dnn::Net net = readNetFromTensorflow(modelFile);
    //! [Initialize network]

    if (net.empty())
    {
        std::cerr << "Can't load network by using the mode file: " << std::endl;
        std::cerr << modelFile << std::endl;
        exit(-1);
    }

    //! [Prepare blob]
    Mat img = imread(imageFile);
    if (img.empty())
    {
        std::cerr << "Can't read image from the file: " << imageFile << std::endl;
        exit(-1);
    }

    cv::Mat img_gray;
    std::cout<<"after read img"<<std::endl;
    cv::cvtColor(img, img_gray, cv::COLOR_BGR2GRAY);

    Mat inputBlob = blobFromImage(img_gray, 1.0f, Size(39, 39), Scalar(), true, false);   //Convert Mat to batch of images
    //! [Prepare blob]
    inputBlob -= 117.0;

    std::cout<<"blobFromImage"<<std::endl;
    //! [Set input blob]
    net.setInput(inputBlob, inBlobName);        //set the network input
    //! [Set input blob]

    std::cout<<"setInput"<<std::endl;

    cv::TickMeter tm;
    tm.start();

    //! [Make forward pass]
    Mat result = net.forward(outBlobName);                          //compute output
    //! [Make forward pass]

    std::cout<<"forward"<<std::endl;

    tm.stop();

    if (!resultFile.empty()) {
        CV_Assert(result.isContinuous());

        ofstream fout(resultFile.c_str(), ios::out | ios::binary);
        fout.write((char*)result.data, result.total() * sizeof(float));
        fout.close();
    }

    std::cout << "Output blob shape " << result.size[0] << " x " << result.size[1] << " x " << result.size[2] << " x " << result.size[3] << std::endl;
    std::cout << "Inference time, ms: " << tm.getTimeMilli()  << std::endl;

    if (!classNamesFile.empty()) {
        std::vector<String> classNames = readClassNames(classNamesFile.c_str());

        int classId;
        double classProb;
        getMaxClass(result, &classId, &classProb);//find the best class

        //! [Print results]
        std::cout << "Best class: #" << classId << " '" << classNames.at(classId) << "'" << std::endl;
        std::cout << "Probability: " << classProb * 100 << "%" << std::endl;
    }
    return 0;
  } //main

**Comment by BKZero** [comment]
i have tried net = tf.concat([preceding, net], -1) in python code, still error with opencv, but different error.

**Comment by dkurt** [comment]
@BKZero, thanks! I reproduced it. A PR https://github.com/opencv/opencv/pull/10748 fixes a error in slice layer but to run your model you need to set concat's axis to 3 because OpenCV could map it correctly from NHWC to NCHW data layout. Is it possible?

```python
 tf.concat([preceding, net], 3)
```

**Comment by BKZero** [comment]
the same error if i change 
net = tf.concat([preceding, net], -1)
to
tf.concat([preceding, net], 3)
but the log is different:
concat before for 4
concat 0 1 1 1
concat 1 1 15 15
concat 2 1 16 16
concat 3 1 18 18
concat before for 4
concat 0 1 1 1
concat 1 1 15 32
concat 2 1 16 16
concat 3 1 18 16
actually, i am looking the source code but i do not understand what the number of the log means. because the shape of preceding and net is [batch_size, 16, 16, 16] and [batch_size, 16, 16, 32], so where did 15 and 18 came from?

**Comment by BKZero** [comment]
and thank you for your effort to fix the slice bug.

**Comment by BKZero** [comment]
i add log in the get memory funcition:

CV_Assert(inputs.size() > 0); std::cout<<"input size "<<inputs.size()<<"outputs size"<<outputs.size()<<std::endl;
        outputs.resize(1, inputs[0]); std::cout<<"inputs[0] "<<inputs[0].size()<<" "<<"axis "<<axis<<std::endl;
        for(int i = 0; i < inputs.size(); i++)
            for(int j = 0; j < inputs[i].size(); j++)
                std::cout<<inputs[i][j]<<std::endl;
and got log:
input size 2outputs size0
inputs[0] 4 axis 1
1
15
16
18
1
32
16
16
i guess the inputs[0] got a wrong shape?

**Comment by BKZero** [comment]
oh! i am sorry, i understand what you mean, it is about the slice bug.
i merge your code, and it is right now.

**Comment by xudh1991** [comment]
opencv 4.1.0
I installed Opecv  through pip python_opencv.whl
cv2.error: OpenCV(4.1.0) D:\Build\OpenCV\opencv-4.1.0\modules\dnn\src\layers\concat_layer.cpp:95: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'

I encountered this error while running the maskrcnn models
and I've tried other opencv versions, but that error still exists.
I tried other models (such as ssd models, faster models) and the error disappeared.
I have change the file of .pb according to https://github.com/opencv/opencv/issues/11560

**Comment by HumamHelfawi** [comment]
@xudh1991  did you manage to solve it?

**Comment by florinmarcus** [comment]
I am getting the same problem:
OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\layers\concat_layer.cpp:95: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'

**Comment by neFAST** [comment]
Same here, any tips or PR to link into?

**Comment by llsouder** [comment]
I found this https://github.com/opencv/opencv/issues/13462#issuecomment-447861731

 it stops the error.
