### ISSUE TITLE
This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.1.0).

### ISSUE THREAD

**Issue by AFIDclan** [opencv/opencv#10747]
##### System information (version)
- Operating System / Platform => Jetson TX1

##### Detailed description

OpenCV works fine until I attempt to use the <opencv2/dnn.hpp> library, then it throws this error (Below). I have updated the protobuf files in /usr/include/google/protobuf and recompiled opencv with no result. I then set DENABLE_PRECOMPILED_HEADERS=OFF and recompiled with no result. I'm not sure on what is the next step to troubleshoot.

Also, is what is the default setting for DENABLE_PRECOMPILED_HEADERS?

Thank you!

  ```
 [libprotobuf FATAL /mnt/opencv/3rdparty/protobuf/src/google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.1.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-k3D1Zt/mir-0.26.3+16.04.20170605/obj-aarch64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.1.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-k3D1Zt/mir-0.26.3+16.04.20170605/obj-aarch64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
```

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

> src/protobuf/mir_protobuf.pb.cc

This is not a part of OpenCV.

> OpenCV 3.1

This version is too old ( >2 years ) and not supported anymore. You should upgrade to the latest release or try master branch.

**Comment by AFIDclan** [comment]
Apologies, I don't have opencv 3.1. I was wrong. I have the latest version of opencv.

> This is not a part of OpenCV.

So this means I should be able to resolve the issue without rebuilding opencv?

**Comment by nhubbard** [comment]
@AFIDclan Ah, another Jetson TX1 user. You will need to build Protobuf from source to fix your issue permanently. The stock system software ships with development libraries that are very old (Ubuntu 14.04 LTS).

**Comment by IamTechknow** [comment]
Hi, a few days ago I complied OpenCV into a Jetson TX1, after having done so to a desktop PC multiple times. For comparison I used the latest stable version of Jetpack (3.1) to flash my TX1, then I had to, in order to compile Caffe, compile Protobuf (downloading didn't work), then compile OpenCV 3.4. The key is to **have enough disk space and use the same GCC version, preferably 5.x.**

**Comment by AFIDclan** [comment]
Thank you! The key was to compile -DWITH_QT=ON and -DWITH_GTK=OFF

**Comment by jesen8** [comment]
@AFIDclan it works for me!,thank you for much
