### ISSUE TITLE
Opencl implementation of canny edge algorithm on java.awt.image.BufferedImage

### ISSUE THREAD

**Issue by zcaudate** [opencv/opencv#10752]
I've asked on http://answers.opencv.org/question/183634/opencl-implementation-of-canny-edge-algorithm-on-javaawtimagebufferedimage/#post-id-183641 already but this is a little bit specific, relating to https://github.com/opencv/opencv/blob/master/modules/imgproc/src/opencl/canny.cl so I'm hoping that the contributors can help me answer this question.

I’m getting stripped outputs for the stage1 canny (with sobel)? I’m not sure if it’s a jvm problem or an algorithm thing.

@mshabunin, @alalek, @ilya-lavrenov, @gongzg, @akarsakov

**Comment by alalek** [comment]
IMHO, You should start your experiments with some more simple OpenCL kernels (like elementwise 'add' and debug them before).

This is not related to current OpenCV goals/approach (out of scope), so closing this.
