### ISSUE TITLE
OpenCV 3.4.0 build does not seem to include HighGui.

### ISSUE THREAD

**Issue by clplaneguy** [opencv/opencv#10750]
##### Detailed description

I am trying to run the sample program "Smoothing Images" in java.  But get an error on HighGui.
HighGui seems to be in the source code but not in the build.  I will have to compile my own build.

**Comment by alalek** [comment]
Should be fixed in "master" branch (by this large patch: #10495).
You can get missed files here (rename them and put into the right directory near your sample): https://github.com/opencv/opencv/tree/3.4.0/modules/highgui/misc/java/src/java
