### ISSUE TITLE
Build failure on Power8 when enable Eigen for OpenCV 3.4

### ISSUE THREAD

**Issue by cometyang** [opencv/opencv#10753]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

It reports error and complain vec_cts only take one argument while eign3' matrixfunction try to call with two arguments

##### Steps to reproduce

Switch EIgen support on

**Comment by seiko2plus** [comment]
@cometyang Could try #10761? it should fix this issue.

**Comment by alalek** [comment]
BTW, Eigen detection in case of cross-compilation is quite buggy - It may try reusing "host" files. Is this issue about native PowerPC compilation?

**Comment by seiko2plus** [comment]
@alalek actually it's about both, we made so many changes on [vsx_utils.hpp](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/vsx_utils.hpp) in order to be able to support wide range of compilers which has effect on Eigen, please check out following trace
````
src/precomp.hpp
-> opencv2/core/private.hpp
-> Eigen/Core	
-> src/Core/arch/AltiVec/MathFunctions.h

Eigen::internal::plog<Packet4f>(const Packet4f& _x)
114 -> Packet4f e = padd(**vec_ctf**(emm0, 0), p4f_1);

Eigen::internal::pexp<Packet4f>(const Packet4f& _x)
188 -> emm0 = **vec_cts**(fx, 0);

Eigen::internal::ConvertToPacket2l(const Packet2d& x)
237 -> return **vec_cts**(x, 0);
````

**Comment by cometyang** [comment]
I tried, it indeed fix the issue.
Thanks
