### ISSUE TITLE
make error with can't find core hpp file

### ISSUE THREAD

**Issue by rainfalj** [opencv/opencv#10762]
When I make after cmake, meet the error:
[  0%] Generate opencv.pc
Scanning dependencies of target libprotobuf
[  0%] Building CXX object modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o
[  0%] Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/ittnotify_static.c.o
opencv/modules/cudev/src/stub.cpp:1:32: fatal error: opencv2/core/cvdef.h: No such file or directory。How can I solve it ?

**Comment by mshabunin** [comment]
Fixed in #10767
