### ISSUE TITLE
Android can't load library

### ISSUE THREAD

**Issue by Allansk2** [opencv/opencv#10772]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Mac 10.13.1
- Compiler => Android Studio 3.0 
 
##### Device information 
Processor	: ARMv7 Processor rev 1 (v7l)
processor	: 0
BogoMIPS	: 38.40

processor	: 1
BogoMIPS	: 38.40

processor	: 2
BogoMIPS	: 38.40

processor	: 3
BogoMIPS	: 38.40

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x51
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x06f
CPU revision	: 1

Hardware	: Qualcomm MSM8974PRO-AC
Revision	: 000e
Serial		: 00007d190000965b

##### Detailed description
I am trying to convert a RGB image to gray image, it run well with simulator, but it crash on my real device. 

##### Steps to reproduce
1. Download the opencv 3.4 and unzip 
2. In my app build.gradle, make sure all CPUs are supported and add library directory 
externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions"
                abiFilters 'x86','x86_64','armeabi','arm64-v8a','armeabi-v7a','mips','mips64'
            }
        }

sourceSets{
        main{
            jniLibs.srcDirs = ['/Users/xxxxx/Desktop/NDK/OpenCV-android-sdk/sdk/native/libs']
        }
    }

3. CMakeList, add library
set(CMAKE_VERBOSE_MAKEFILE on)
// add .so library path
set(ocvlibs "/Users/xxxxx/Desktop/NDK/OpenCV-android-sdk/sdk/native/libs")
// add header path
include_directories(/Users/xxxxx/Desktop/NDK/OpenCV-android-sdk/sdk/native/jni/include)
// add opencv library
add_library(libopencv_java3 SHARED IMPORTED )
set_target_properties(libopencv_java3 PROPERTIES
                      IMPORTED_LOCATION "${ocvlibs}/${ANDROID_ABI}/libopencv_java3.so")

target_link_libraries( # Specifies the target library.
                       native-lib libopencv_java3 android log

                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )

4. my native-lib.cpp
#include <jni.h>
#include <string>
#include <opencv2/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>

using namespace std;
using namespace cv;
  
extern "C"
JNIEXPORT jintArray JNICALL
Java_com_allan_opencv1_MainActivity_grayP(JNIEnv *env, jclass type, jintArray pixels_, jint w,
                                          jint h) {
    jint *pixels = env->GetIntArrayElements(pixels_, NULL);

    if (pixels == NULL) {
        return 0;
    }

    // RGBA
    Mat imgData(h, w, CV_8UC4, (unsigned char*)pixels);    // crash here
 
    uchar* ptr = imgData.ptr(0);

    for (int i = 0; i < w * h; i++) {
        // gray compute = R * 0.299 + G * 0.587 + B * 0.114
        uchar gray = (uchar) (ptr[4 * i + 2] * 0.299 + ptr[4 * i + 1] * 0.587 + ptr[4 * i + 0] * 0.114);
        ptr[4 * i + 0] = gray;
        ptr[4 * i + 1] = gray;
        ptr[4 * i + 2] = gray;
    }

    int size = w * h;
    jintArray result = env->NewIntArray(size);
    env->SetIntArrayRegion(result, 0, size, pixels);

    env->ReleaseIntArrayElements(pixels_, pixels, 0);

    return result;
}

5. error message
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.allan.opencv.gray-1/lib/arm/libnative-lib.so"...
![screen shot 2018-02-03 at 11 41 20 am](https://user-images.githubusercontent.com/6540316/35771107-0740f128-08ed-11e8-8d6b-64d91f7333f1.png)

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

1. Where is `adb logcat` output?

2. Missing `System.loadLibrary()` arguments.

3. Android version? Old devices requires `loadLibrary()` for all dependencies (usually non-system).

4. OpenCV provides CMake's `find_package()` functionality, your way is not supported:
> add_library(libopencv_java3 SHARED IMPORTED )

5. Looks like this can't fixed in OpenCV: https://github.com/android-ndk/ndk/issues/126


BTW, OpenCV's Android SDK package is built with NDK 10
