### ISSUE TITLE
image is none type

### ISSUE THREAD

**Issue by Gaurav1302** [opencv/opencv#10770]
>>> import cv2
>>> print cv2.imread('/Users/gauravjain/Desktop/Computer\ Vision/Edge\ Detection/download.jpg ')
None
>>> 

**Also i cannot import cv2 in spyder, anaconda.**

using python 2.7.13
opencv - 3.4.0
mac os high sierra 10.13.3 64bit

**Comment by mshabunin** [comment]
@Gaurav1302 , it is better to ask questions about library usage on the forum: http://answers.opencv.org.
