### ISSUE TITLE
Mobilenet-SSD cannot initialize opencl

### ISSUE THREAD

**Issue by zrbzrb1106** [opencv/opencv#10778]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017 C++
- iGPU =>Inter(R) HD Graphics 620

##### Detailed description

Running without opencl everything works fine. But when running using opencl, the same problem occurs [https://github.com/opencv/opencv/issues/10731](url). So I update the iGPU  to the latest version but opencv could not initialize opencl then.  It just displays:
```
[ INFO:0] Initialize OpenCL runtime...
```
and then the goes to the recognition without acceleration.

##### Steps to reproduce

I have tried the code to print the opencl devices info.

```
void checkOpenCL() {

	if (!cv::ocl::haveOpenCL())
	{
		cout << "OpenCL is not available..." << endl;
		//return;
	}

	cv::ocl::Context context;
	if (!context.create(cv::ocl::Device::TYPE_ALL))
	{
		cout << "Failed creating the context..." << endl;
		//return;
	}

	cout << context.ndevices() << " CPU devices are detected." << endl; //This bit provides an overview of the OpenCL devices you have in your computer
	for (int i = 0; i < context.ndevices(); i++)
	{
		cv::ocl::Device device = context.device(i);
		cout << "name:              " << device.name() << endl;
		cout << "available:         " << device.available() << endl;
		cout << "imageSupport:      " << device.imageSupport() << endl;
		cout << "OpenCL_C_Version:  " << device.OpenCL_C_Version() << endl;
		cout << endl;
	}

	cv::ocl::Device(context.device(0)); //Here is where you change which GPU to use (e.g. 0 or 1)

}
```
Ant it could only detect one device now, the output is:
```
1 CPU devices are detected.                                                                                           
name:       GeForce 940MX                                                                                        
available:         1                 
imageSupport:      1                                                                                                    
OpenCL_C_Version:  OpenCL C 1.2                                                                                                                          
```
It should detect my iGPU, am I right?

Could someone please give me suggestions about how it works and how to fix it? Any reply will be appreciated!

**Comment by alalek** [comment]
The most part of DNN kernels are optimized for iGPU with Intel extensions. GeForce can't run these kernels.
Read [this](https://github.com/opencv/opencv/wiki/OpenCL-optimizations#opencv-opencl-configuration-options) how to switch OpenCL device.

**Comment by zrbzrb1106** [comment]
@alalek Thank you for your reply. I have checked my iGPU. After the driver upgrading, the OpenCL version goes to 2.1. Is this version supported by opencv dnn?

**Comment by alalek** [comment]
We tested this with these versions of Windows OpenCL display drivers: 22.x / 23.x. See these [build/test](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10361/steps/test_dnn-ippicv-opencl/logs/stdio) [logs](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10352/steps/test_dnn-ippicv-opencl/logs/stdio).

**Comment by zrbzrb1106** [comment]
@alalek Thank you and everything works well! It's just because that opencv points to my CUDA by default. When I change that to iGPU, everything goes well! Thanks!
