### ISSUE TITLE
Feature: Add matrix size argument to initializer_list Mat constructor

### ISSUE THREAD

**Issue by aslze** [opencv/opencv#10792]
OpenCV 3.3 introduced C++11 **initializer_list** constructors for `Mat`, a very welcome feature. However, these constructors have no size information (i.e. rows and columns), so new matrices need to call `reshape()` like this:

```.cpp
Mat_<double> A = Mat_<double>({1, 0, 0, 0, 1, 0, 0, 0, 1}).reshape(1, 3);
```

**Proposal**

I propose to add matrix **size** (rows, cols) to the constructor along with the initializer list so that matrices are fully initialized in the constructor. Construction would look like this: (compare with the above)

```.cpp
Mat_<double> A(3, 3, {1, 0, 0, 0, 1, 0, 0, 0, 1});
```

Alternatively, you could require **only the number of rows**, because columns will be known (`cols = list.size() / rows`):

```.cpp
Mat_<double> A(3, {1, 0, 0, 0, 1, 0, 0, 0, 1});
```

This syntax matches the *old* constructor taking a size and a pointer to an array `Mat(int rows, int cols, double* data)`).

**Possible implementation** (for the rows-only case)

```.cpp
template<typename _Tp, typename> inline
Mat::Mat(int rows, const std::initializer_list<_Tp> list)
    : flags(MAGIC_VAL | traits::Type<_Tp>::value | CV_MAT_CONT_FLAG), dims(2), rows((int)list.size()),
      cols(1), data(0), datastart(0), dataend(0), datalimit(0), allocator(0), u(0), size(&rows), step(0)
{
    if(list.size() == 0)
        return;
    Mat(rows, (int)list.size() / rows, traits::Type<_Tp>::value, (uchar*)list.begin()).copyTo(*this);
}
```

**Vectors** do not have this problem and are fine with the existing constructor.

**Comment by akhandait** [comment]
@aslze Are you working on this issue?
If not I would like to work on it.

**Comment by alalek** [comment]
Don't forget to add tests for new functionality somewhere [here](https://github.com/opencv/opencv/blob/3.4.0/modules/core/test/test_mat.cpp#L1719-L1734).

**Comment by aslze** [comment]
@akhandait No, I'm just a user of OpenCV.

**Comment by akhandait** [comment]
@alalek Can you give some initial direction as to where the Mat_ class is defined so that I can make the changes. I am new to open source.

**Comment by take1014** [comment]
@alalek I would like to work on it.  aslze's code looks like fine, so I add tests and create PR.

**Comment by alalek** [comment]
Please use this Mat signature:
```.diff
-Mat(int rows, const std::initializer_list<_Tp> list)
+Mat(const std::initializer_list<int> sizes, const std::initializer_list<_Tp> values)
```

Just "rows" is not consistent with the current Mat design.
