### ISSUE TITLE
Get different output of tensorflow model from pc and android

### ISSUE THREAD

**Issue by BKZero** [opencv/opencv#10794]
opencv 3.4.0
pc: Ubuntu 14.04
android: RedMi Note3, 6.0.1
[2.pb.zip](https://github.com/opencv/opencv/files/1697560/2.pb.zip)
[layerlist.txt](https://github.com/opencv/opencv/files/1697561/layerlist.txt)
![foo-002](https://user-images.githubusercontent.com/18680778/35839358-f27688da-0b2a-11e8-902d-276b34f62987.jpeg)
the test code:
  void testopencvdnn()
    {
        cv::String modelFile = "/storage/emulated/0/DCIM/2.pb";
        cv::String imageFile = "/storage/emulated/0/DCIM/foo-002.jpeg";
        cv::String inBlobName = "opencv_v2/InputPlaceholder";
        cv::String outBlobName = "opencv_v2/Output";

        cv::String classNamesFile = "/storage/emulated/0/layerlist.txt";

        cv::dnn::Net net = cv::dnn::readNetFromTensorflow(modelFile);

        //! [Prepare blob]
        cv::Mat img = cv::imread(imageFile);
        cv::Mat img_gray;
        std::cout<<"after read img"<<std::endl;
        cv::cvtColor(img, img_gray, cv::COLOR_BGR2GRAY);

        std::cout<<"img gray "<<img_gray.cols<<" "<<img_gray.rows<<std::endl;
        cv::Mat inputBlob = cv::dnn::blobFromImage(img_gray, 1.0f, cv::Size(39, 39), cv::Scalar(), true, false);   //Convert Mat to batch of images
        std::cout<<inputBlob.size[0]<<" "<<inputBlob.size[1]<<" "<<inputBlob.size[2]<<" "<<inputBlob.size[3]<<std::endl;
        //! [Prepare blob]
        inputBlob -= 128.0;
        inputBlob = inputBlob / 64.0;

        std::cout<<"inputblob "<<inputBlob.size()<<" "<<inputBlob.rows<<std::endl;

        std::cout<<"blobFromImage"<<std::endl;
        //! [Set input blob]
        net.setInput(inputBlob, inBlobName);        //set the network input
        //! [Set input blob]

        std::cout<<"setInput"<<std::endl;

        cv::Mat result = net.forward(outBlobName);                          //compute output
        //! [Make forward pass]

        std::cout<<"forward"<<std::endl;

        std::cout<<"result: "<<result.cols<<" "<<result.rows<<std::endl;
        for(int i = 0; i < result.cols; i++)
        {
            std::cout<<result.at<float>(i)<<endl;
            LOG(INFO) << "bkzero jni result 2: " << result.at<float>(i);
        }
    }

but i got result in pc:
result: 10 1
0.218175
0.768095
0.487576
0.263633
0.754258
0.204182
0.193998
0.546406
0.796031
0.77856
while i got from android:
bkzero jni result 2: 0.218137
bkzero jni result 2: 0.768189
bkzero jni result 2: 0.487637
bkzero jni result 2: 0.263613
bkzero jni result 2: 0.754274
bkzero jni result 2: 0.204205
bkzero jni result 2: 0.194084
bkzero jni result 2: 0.546483
bkzero jni result 2: 0.79603
bkzero jni result 2: 0.778563
it is almost the same result, but not exactly. the .a file i used for android is built from source.
so i guess there is something wrong with neon code or something like that?

**Comment by BKZero** [comment]
@alalek why sign a question invalid flag? i think this may be a bug of the foundation math lib of opencv of android edition.

**Comment by alalek** [comment]
Because there is no action item.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

---

Don't expect bit-exact results from DNN models.
Consider learning about numerical error of floating point calculations.
Convolution is usually a large sum operation - see this article about summation issues: http://www.drdobbs.com/floating-point-summation/184403224
Max polling (and unpooling) are much worst (integer indexes are used).

Main assumption here: DNN models are well designed and trained and provide "stable" results for noised inputs (camera noise, or numerical errors of intermediate layers). Small epsilon error should not explode into unpredictable results on output. But...

P.S. On x86 PC you may get "different" results with SSE3 / AVX / AVX2 code (in default build try using `OPENCV_CPU_DISABLE=AVX2,AVX` to run SSE code only).

**Comment by BKZero** [comment]
@alalek 
i have test a simple multiply code and get exactly same result 3.39193e-05( has 6 bit accuarcy):
        float testnum = 0.99;
        for(int i = 0; i < 10; i++)
        {
            testnum *= testnum;
        }
        std::cout<<"testnum "<<testnum<<std::endl;
        LOG(INFO) << "bkzero jni testnum: " << testnum;
maybe you are right, on differet platform, the result may not be exactly same, but the accuary is too low, you can see carefully of my two result and will find the accuary is lower than 4 bit.
ps, there is nothing to do with the dnn model, i use the same input and same model. when you say stable it means the classification result does not affected by the input noise, but the probability score may change.

**Comment by dkurt** [comment]
@BKZero, as @alalek mentioned you can obtain this kind of computational errors  even on PC just changing set of CPU optimizations. If you sure that one of results is wrong you need to know which one is correct. I'm closing an issue.
