### ISSUE TITLE
Dnn.blobFromImage() produces an invalid Mat in Android

### ISSUE THREAD

**Issue by IamTechknow** [opencv/opencv#10802]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Android 8.1 (arm64) (Google Pixel)
- Compiler => Android Studio 3.0.1

##### Detailed description

I tried to get the DNN SSD Caffe example to work on Android with no success so far. This may be related to #10422 but I'm not sure because I get no CvException, instead I just get an invalid Mat object. This first happens when calling Dnn.blobFromImage(), then calling Dnn.setInput() and Dnn.forward() yielded no exception or response. I can verify that the DNN is successfully loaded, and the image to be object detected is also load successfully by Imgcodecs.imread(), but the Dnn.forward() call will yield an invalid Mat object.

What should happen instead is if there really is an error an exception is thrown, or there is no error and the detection succeeds and a Mat object with the classification probabilities is available.
##### Steps to reproduce
[Here is a repository](https://github.com/IamTechknow/MyVision) which may be built and deployed onto an Android 5.1+ device to reproduce the problem. For my repository I used the native libraries from the downloadable Android SDK from the releases page. To avoid slow APK loading and large repository size, I decided to make a symlink to the JNI libraries and also require the files to be added to the device ahead of time.

Make a breakpoint at MainActivity.java:74 in Android Studio:
```
Mat detection = dnn.forward("detection_out");
```
When the breakpoint is reached, evaluate the following statements:
```
Imgcodecs.imread(getPath(IMAGE_FILE))
```
```
Dnn.blobFromImage(Imgcodecs.imread(getPath(IMAGE_FILE)), 1.0, new Size(WIDTH, HEIGHT), MEAN, false, false)
```
Verify the imread() returns a Mat object with dimensions 480 * 720 * CV_32F, but the Mat object from Dnn.blobFromImage() returns a Mat object with dimensions -1 * -1 * CV_32F.

**Comment by dkurt** [comment]
@IamTechknow, description of an issue does not contain any bug reports or feature requests. Please use http://answers.opencv.org/ to ask usage questions.

**Comment by luciancioroga** [comment]
@IamTechknow, have you found any solutions to this? I'm experiencing the exact same issue.

**Comment by GajjarMihir** [comment]
@IamTechknow @luciancioroga @dkurt I got the same error. Is this opencv3.4.1's problem?

**Comment by dkurt** [comment]
@luciancioroga, @GajjarMihir, Please clarify the problem. There is [a tutorial](https://docs.opencv.org/master/d2/d58/tutorial_table_of_content_dnn.html) for MobileNet-SSD object detection model on Android. May I ask you to try it?

**Comment by IamTechknow** [comment]
I didn't know the tutorial existed when I post the issue two months ago. I deleted my repository because I was no longer concerned with this issue but AFAIK it uses the same API calls to the Dnn class. 

@luciancioroga, @GajjarMihir I suggest you try the tutorial and if the same problem described here comes up let us know

**Comment by berak** [comment]
@GajjarMihir , can you please ask again on http://answers.opencv.org ?

(i think, i have a solution for you, but it should not go here, because this is the *bugtracker*)

**Comment by GajjarMihir** [comment]
Sure I will explain it there. Thanks :)

**Comment by MuhammadHadiofficial** [comment]
Did you find solution to this im facing same issue?

**Comment by MuhammadHadiofficial** [comment]
Did you find solution to this im facing same issue?

**Comment by myulz** [comment]
Also wondering if anyone has found a solution for this issue?
