### ISSUE TITLE
error: redundant redeclaration of 'cv::String cv::format(const char*, ...)'

### ISSUE THREAD

**Issue by uartie** [opencv/opencv#10815]
##### System information (version)

- OpenCV => (master) heads/master-0-g090ee46
- Operating System / Platform => Linux
- Compiler => GCC/G++

##### Detailed description

Programs fail to compile when `-Werror -Wredundant-decls` GCC compile options are used and when including `<opencv2/core.hpp>`

##### Steps to reproduce

```.cpp
// file test.cpp
#include <opencv2/core.hpp>

int main(int argc, char** argv)
{
  return 0;
}
```
```
$ g++ -Wredundant-decls -Werror `pkg-config --cflags --libs opencv` test.cpp

In file included from /opt/media/install/include/opencv2/core.hpp:3261:0,
                 from test.cpp:1:
/opt/media/install/include/opencv2/core/utility.hpp:191:48: error: redundant redeclaration of 'cv::String cv::format(const char*, ...)' in same scope [-Werror=redundant-decls]
 CV_EXPORTS String format( const char* fmt, ... );
                                                ^
In file included from /opt/media/install/include/opencv2/core.hpp:3259:0,
                 from test.cpp:1:
/opt/media/install/include/opencv2/core/operations.hpp:368:19: error: previous declaration of 'cv::String cv::format(const char*, ...)' [-Werror=redundant-decls]
 CV_EXPORTS String format( const char* fmt, ... );
                   ^
cc1plus: all warnings being treated as errors
```

**Comment by dasdipanjan04** [comment]
Hello @uartie,

I tried to reproduce the same on Ubuntu 17.10 but cannot. Please see the attached picture and let me know if I have missed anything.

![10815_notreproduced](https://user-images.githubusercontent.com/12770322/36125825-f306057a-1055-11e8-9e2b-0f2fdaee5db2.png)

Thanks and Regards
Dipanjan Das

**Comment by uartie** [comment]
I just tried in a Ubuntu Artful (17.10) Docker container which has `g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0` and still see this issue.  I also get this issue in Fedora 27 host installation which has `g++ (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)`.

Are you testing with latest opencv master branch?  Can you try in a clean environment to ensure pkg-config is not picking up some other version of opencv installed on your system (e.g. try inside a Docker container)?

**Comment by dasdipanjan04** [comment]
@uartie I tried with the latest opencv master branch. 
I didn't try using Docker. I will try inside a Docker container. I am also new to linux world, so I will have to dig up a bit more. Thanks a lot for the details. I will let you know tomorrow.

**Comment by uartie** [comment]
Interesting... I just discovered that when I install opencv into the default cmake install prefix (i.e. `/usr/local`), the test program compiles fine.

But when I install opencv into a custom prefix (e.g. `/opt/media/install`), the test program fails to compile:

```
$ sudo apt remove libopencv-core-dev
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/opt/media/install <path to opencv source>/.
  <snip>
$ make -j8
  <snip>
$ make install
  <snip>
$ export PKG_CONFIG_PATH=/opt/media/install/lib/pkgconfig
$ pkg-config --cflags --libs opencv
  -I/opt/media/install/include/opencv -I/opt/media/install/include -L/opt/media/install/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core
$ g++ -Wredundant-decls -Werror `pkg-config --cflags --libs opencv` test.cpp
  <see reported compile errors in issue description>
```

NOTE: I did both scenarios in separate Ubuntu Artful Docker containers to ensure one does not affect the other and removed libopencv-core-dev system package first to ensure it was not affecting the result.

**Comment by alalek** [comment]
Try using GCC "-H" option to check list of included headers. Perhaps there is some mess with system headers.

**Comment by uartie** [comment]
The include headers list is the same for both scenarios that I described above (except for opencv install prefix obviously).

The difference becomes obvious if you compare the preprocessor output (g++ -E) for both scenarios.  That is, the opencv headers are treated differently by the preprocessor depending on the install location (see filename flag `3` at https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html)

If I add `-isystem` to the g++ compiler command when compiling the test program with opencv installed in custom prefix, the problem disappears.  The `-isystem` option tells the preprocessor to treat headers as system headers.  The preprocessor suppresses certain warnings when headers are treated as system headers (in this case, redundant-decls is suppressed).

Therefore, when opencv is installed into /usr/local, the headers are treated as system headers by default and the preprocessor suppresses the warnings automatically.

Clearly, the problem is that both `opencv2/core/operations.hpp` and `opencv2/core/utility.hpp` declare the same `String format(...)` method.  This is a bad idea.  One fix could be to place this in it's own header and just include it from operations.hpp and utility.hpp to avoid redefinition.

**Comment by alalek** [comment]
Thank you for the clarification!

> the problem is that both opencv2/core/operations.hpp and opencv2/core/utility.hpp declare the same String format(...) method

Agreed. I will provide fix for this.
