### ISSUE TITLE
GaussianBlur except a circle

### ISSUE THREAD

**Issue by DlmuZQ** [opencv/opencv#10816]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
find a way to do this, and have a better way to do this work?

##### Steps to reproduce

void fun()
{
        Mat srcImg, resImg, roi;
	srcImg = imread("lenna.jpg");
	resImg = Mat(srcImg.size(),srcImg.type());
	roi = Mat::zeros(srcImg.size(), CV_8UC1);
	circle(roi, Point(130, 100), 50, CV_RGB(255, 255, 255), -1);
	cv::subtract(srcImg, srcImg, resImg, roi);
	srcImg.copyTo(resImg, roi);
	GaussianBlur(srcImg, srcImg, Size(5, 5), 0);
	resImg.copyTo(srcImg, roi);		
	imshow("src", srcImg);
	imshow("res", resImg);
}

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
