### ISSUE TITLE
when opencv >=3.3.1,ubs camera shows not correctly in tinkerboard(something like Raspberry Pi)

### ISSUE THREAD

**Issue by xbcReal** [opencv/opencv#10817]
hello every one ,I met a problem and stack here for almost two weeks.Here is how's the things going on:
I trained a detection model using tensorflow detecion api,and the model is based on mobilenet-ssd,then I want to deploy it on a tinkerboard device,which is very like the Raspberry Pi but with more powerful computation ability.
Firstly I install a opencv3.3.0 on tinkerboard,but found that  this version does not support  mobilenet-ssd model implemented by tensorflow but support caffe models.But this version can read usb camera correctly.Then after following some guide,I know that opencv 3.3.1 and newer version can make it work ,so I first tried newer version on my computer,and it works well using usb camera.So I started to do it on the tinkerboard device,but when I install a opencv 3.3.1 or newer version,it works good when detecting using input from images or videos,but when using usb camera input ,it can not read the picture correctly,just like the following picture:
![pciture](https://user-images.githubusercontent.com/24933730/36020552-1b9ee79e-0dbe-11e8-9f2a-abac082db720.jpeg)
Does anybody know that wrong with this problem?
Thanks,
xbc.

**Comment by alalek** [comment]
Try to revert this patch #9479

**Comment by xbcReal** [comment]
Thanks,it works to using the code:cap.set(CAP_PROP_FOURCC, CV_FOURCC('M', 'J', 'P', 'G'))

**Comment by xbcReal** [comment]
@sushant1727 sorry I have no ideas on how to solve this issue.

**Comment by pwnorbitals** [comment]
@xbcReal Is your problem fixed now ?
