### ISSUE TITLE
face_landmark_model.dat download timeout! (need a download link for manually download)

### ISSUE THREAD

**Issue by thyeun** [opencv/opencv#10825]
Anyone can provided me a download link for face_landmark_model.dat?
i'm keep on getting download timeout, want to manually download it using wget -c .

thanks in advanced!

**Comment by csukuangfj** [comment]
See here

https://github.com/opencv/opencv_3rdparty/tree/contrib_face_alignment_20170818

**Comment by thyeun** [comment]
thank you so much

**Comment by chetanlondhe1112** [comment]
> See here
> 
> https://github.com/opencv/opencv_3rdparty/tree/contrib_face_alignment_20170818

thanks
