### ISSUE TITLE
OpenCV python result window show without waitKey(1)

### ISSUE THREAD

**Issue by lijiansong** [opencv/opencv#10828]
In some real time CV app, `cv2.waitKey(1)` will be intolerant, when I add a counter for `cv2.waitKey(1)`, this function doesn't work and the whole program will be crashed seconds later. e.g:
```
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np

vs = VideoStream(src=0).start()
count = 0
while True:
        # read data from webcam
	frame = vs.read()
	
	# do some processing
        # ......
	
	# show the output frame
        cv2.namedWindow("frame", cv2.WND_PROP_FULLSCREEN)
        cv2.setWindowProperty("frame",cv2.WND_PROP_FULLSCREEN,cv2.WINDOW_FULLSCREEN)
	cv2.imshow("frame", frame)

        count += 1
        if not(count % 100):
	    if cv2.waitKey(1) & 0xFF == ord('q'):
                break

	# update the FPS
	fps.update()

# stop the timer and display FPS information
fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))

cv2.destroyAllWindows()
vs.stop()
```
The above code snip will dump following err msg:
```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```
Here the function `waitKey(1)` is too time-consuming for me， I wonder is there any efficient method for result window showing?

**Comment by csukuangfj** [comment]
You may use

 (1) The Viz3d module. See an example here https://github.com/opencv/opencv/issues/9976

or (2) If your application uses some framework (e.g., Qt), you can use the graphics system provided
by the framework to display the image.

**Comment by StevenPuttemans** [comment]
Knowing that OpenCV was never intended to be used as a GUI or visualisation backend, I kind of support @csukuangfj in the fact that you should simply use the library for what it is, being a framework for computer vision algorithms, ... and use other frameworks for their purpose.
