### ISSUE TITLE
IMREAD_GRAYSCALE and CV_BGR2GRAY

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#10824]
- OpenCV => 3.4.0-dev
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

Hi,
Weird results : reading an image in grayscale or reading in color and convert in grayscale is not the same things : 
my program is : 
```
       {
        Mat imgbgr = imread("g:/lib/opencv/samples/data/fruits.jpg", IMREAD_COLOR);
        Mat imggray = imread("g:/lib/opencv/samples/data/fruits.jpg", IMREAD_GRAYSCALE);
        Mat imgbgr2gray;
        cvtColor(imgbgr, imgbgr2gray, CV_BGR2GRAY);

        float hrange[] = { 0,256 };
        int bins = 256;
        int histSize[] = { bins };
        const float* lhranges[] = { hrange};
        int channels[] = { 0 };
        Mat hist1,hist2;
        calcHist(&imggray, 1, channels, noArray(), hist1, 1, histSize, lhranges);
        calcHist(&imgbgr2gray, 1, channels, noArray(), hist2, 1, histSize, lhranges);
        for (int i = 0; i < 256; i++)
        {
            cout << i<<" hist : " << hist1.at<float>(i, 0) << "\t";
            cout << hist2.at<float>(i, 0) << endl;

        }

``````

0 hist : 80     17
1 hist : 367    198
2 hist : 730    770
3 hist : 1064   1011
4 hist : 1336   1367
5 hist : 1805   1838
6 hist : 2172   2191
7 hist : 1994   2028
8 hist : 1688   1714
9 hist : 1476   1483
10 hist : 1378  1390
11 hist : 1404  1430
12 hist : 1405  1401
13 hist : 1370  1374
14 hist : 1285  1286
15 hist : 1285  1300
16 hist : 1265  1268
17 hist : 1152  1160
18 hist : 1065  1073
19 hist : 1021  1026
20 hist : 963   965
21 hist : 974   971
22 hist : 920   918
23 hist : 1031  1033
.....
```
 
It seems that jpeg color images are in Y′CBCR, color space
Using png image I have got same problem (rubberwhale2.png)

May be this behaviour should be wrote in doc

**Comment by StevenPuttemans** [comment]
@LaurentBerger I just checked the following code, given a random colour image

```
#include <iostream>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main()
{
    Mat img = imread("/home/spu/Desktop/net.png", IMREAD_GRAYSCALE);
    Mat img2 = imread("/home/spu/Desktop/net.png", IMREAD_COLOR);

    Mat img3;
    cvtColor(img2,img3,COLOR_BGR2GRAY);

    Mat result = abs(img3 - img);
    normalize(result,result);

    imshow("test", result); waitKey(0);

    return 0;
}
```

The resulting window is completely black, thus in my opinion proving that both approaches do the same thing right? Just pulled latest master for this.

**Comment by LaurentBerger** [comment]
Not agree. You can add after normalize cout << sum(result); and it is not 0 with samples/data/fruits.jpg. 

Now when you set IMREAD_GRAYSCALE for a jpg image cvtColor is not [called ](https://www4.cs.fau.de/Services/Doc/graphics/doc/jpeg/libjpeg.html): 
```
 J_COLOR_SPACE out_color_space

        Output color space. jpeg_read_header() sets an appropriate default
        based on jpeg_color_space; typically it will be RGB or grayscale.
        The application can change this field to request output in a different
        colorspace. For example, set it to JCS_GRAYSCALE to get grayscale
        output from a color file. (This is useful for previewing: grayscale
        output is faster than full color since the color components need not
        be processed.) Note that not all possible color space transforms are
        currently implemented; you may need to extend jdcolor.c if you want an
        unusual conversion.

```
For a png file conversion is [here ](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_png.cpp#L276) and using [cvtcolor ](https://docs.opencv.org/trunk/de/d25/imgproc_color_conversions.html)

**Comment by StevenPuttemans** [comment]
@LaurentBerger wait wait, this is very weird. So I adapted the code to

```
#include <iostream>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main()
{
    Mat img = imread("/home/spu/Desktop/fruits.jpg", IMREAD_GRAYSCALE);
    Mat img2 = imread("/home/spu/Desktop/fruits.jpg", IMREAD_COLOR);

    Mat img3;
    cvtColor(img2,img3,COLOR_BGR2GRAY);

    Mat result = abs(img3 - img);
    normalize(result,result, 255, 0);

    cerr << cv::sum(result) << endl;
    imshow("test", result); waitKey(0);

    return 0;
}
```

Then ran it both on `fruits.jpg` and `ml.png` to see the difference in file and compression. By those I get the following result

- for `fruits.jpg` we get [11097, 0, 0, 0]
- for `ml.png` we get [56222, 0, 0, 0]

But what I do not understand, is why that the imshow still returns two completely black images for both, so in principle no difference pixel wise?

**Comment by StevenPuttemans** [comment]
Did a small further investigation, using the `minMaxLoc` function.
It seems that using the different approaches
- using a png file the values for the difference are min 0 max 1
- using a jpg file the values for the difference are min 0 max 4

So indeed, there is a very small detail, which leads to different results if you do for example histogram binning.

**Comment by LaurentBerger** [comment]
Yes with a random color mat difference are visible 
        cout << sum(result );
        Mat lutRND(256, 1, CV_8UC3);
        randu(lutRND, Scalar(0, 0, 0), Scalar(255, 255, 255));
        applyColorMap(result , result lutRND);
        imshow("absddiff", result );

**Comment by LaurentBerger** [comment]
May be a sentence, in a good english, can be add in IMREAD_GRAYSCALE doc : 

> When IMREAD_GRAYSCALE is set, codecs method are called to convert image in gray scale
