### ISSUE TITLE
I can't import cv2 in python3 in ubuntu 17.10 after installing opencv 3.4.0.

### ISSUE THREAD

**Issue by theunknownguy** [opencv/opencv#10837]
ujjwal@ujjwal-HP-245-G5-Notebook-PC:~$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
>>> 

ujjwal@ujjwal-HP-245-G5-Notebook-PC:~$ python2
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.1.0'
>>> 

ujjwal@ujjwal-HP-245-G5-Notebook-PC:~$ pkg-config --modversion opencv 
3.4.0

**Comment by Sameeranjoshi** [comment]
did you just download the openCV library or installed it completely until **sudo make install**?
you may try installing the library again from here:
[here:](http://docs.opencv.org/doc/tutorials/introduction/table_of_content_introduction/table_of_content_introduction.html#table-of-content-introduction)

**Comment by FlorianFranzen** [comment]
This can have a variety of reasons.

It would be important to know how you installed opencv and if the version you installed was build with python bindings. It would also be important to know what versions of opencv you installed previously.

There are also unofficial python only versions available via pip, which might get in your way.

As a first step, please run the following:
```
python2 -c "import cv2; print cv2.__file__"
```
If you build opencv yourself, please also supply the output of the step where you run ```cmake```.

**Comment by wolterlw** [comment]
Built opencv 3.4.1 myself    
```
cmake -D CMAKE_BUILD_TYPE=Release 
      -D CMAKE_INSTALL_PREFIX=/usr/local  
      -D BUILD_opencv_python3=yes 
      -D PYTHON_LIBRARIES=/home/user/miniconda3/lib/libpython3.6m.so 
      -D PYTHON3_LIBRARY=/home/user/miniconda3/lib/libpython3.6m.so 
      -D PYTHON3_INCLUDE_DIR=/home/user/miniconda3/include/python3.6m 
      -D BUILD_opencv_python2=yes ..
```
Here is the [CMake log](https://gist.github.com/wolterlw/ad5e9f1f77dcdfdcd71473b3c5c8fd1b)    
Still can't import cv2 from neither python3 not python2
