### ISSUE TITLE
The parameters of cv::viz::Viz3d::VizImpl::addLight are not const references

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#10831]
##### System information (version)

- OpenCV => master

##### Detailed description
See the code below:

https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/viz/src/vizimpl.cpp#L206

The parameters are not of type `const &`

The same problem exists for
https://github.com/opencv/opencv/blob/e2a99d24ec8f48ca56ead3a6beb7fe38fc067a12/modules/viz/src/viz3d.cpp#L105-L106

**Comment by dasdipanjan04** [comment]
Hi,
I am totally new to open-source contribution, so please don't mind if my question sounds silly. 
 
Does the issue mean that simply const ClassName &param needs to be added? Do we also need to check the usages of addLight in other classes and passed parameters to the addLight method? 
Thanks and Regards
Dipanjan Das

**Comment by csukuangfj** [comment]
@dasdipanjan04 

Since the passed parameters are not modified inside the function,  passing
`const &` can avoid unnecessary copies.

**Comment by dasdipanjan04** [comment]
@csukuangfj 
Yes.
Thanks for the information. Can I work on this?

**Comment by csukuangfj** [comment]
Sure, you are very welcome.

But changing the signature causes API incompatibility. I am not sure if this is OK.
@alalek

**Comment by alalek** [comment]
Right. Sorry - I thought that this is .cpp only change.
This can't be fixed right now.

**Comment by dasdipanjan04** [comment]
Okay then I will work on this in future. Thanks for the update @alalek
