### ISSUE TITLE
Make Viz3d::getViewerPose const (API side)

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10847]
##### System information (version)
- OpenCV => 3.4.0 and master
- Operating System / Platform => -
- Compiler => g++ 5.4.0 (does not really matter)

##### Detailed description

#9393 has made `cv::viz::Viz3d::VizImpl::getViewerPose()` `const`, but not `cv::viz::Viz3d::getViewerPose()`. Thus, on the API side, calling the latter (which is not yet `const`) on a `const Viz3d` instance still yields a compiler error.

##### Steps to reproduce

See above. Please make `cv::viz::Viz3d::getViewerPose()` `const` as well.

**Comment by catree** [comment]
Should be solved with #11643
