### ISSUE TITLE
Abort(32) error on running the sample from https://docs.opencv.org/trunk/dd/d00/tutorial_js_video_display.html

### ISSUE THREAD

**Issue by Rampradeep** [opencv/opencv#10848]
I compiled opencv.js on macosX via the link https://docs.opencv.org/trunk/d4/da1/tutorial_js_setup.html. On loading the opencv.js in a browser app, following error happens on cv.cvtColor(src, dst, cv.COLOR_RGBA2GRAY). Any help is appreciated. I am new to opencv and excuse any obvious things being raised.

Build Info:
General configuration for OpenCV 3.4.0-dev =====================================
  Version control:               3.4.0-345-ge2a99d24e

  Platform:
    Timestamp:                   2018-02-11T12:25:04Z
    Host:                        Darwin 17.4.0 x86_64
    Target:                      Emscripten 1 x86
    CMake:                       3.10.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                /Users/rampradeepk/Rekonix/code/opencv/emsdk/emsdk-portable/emscripten/1.37.33/em++  (ver 5.0.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -Qunused-arguments -fomit-frame-pointer -ffunction-sections -fdata-sections -g  -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O2  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -Qunused-arguments -fomit-frame-pointer -ffunction-sections -fdata-sections -g  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /Users/rampradeepk/Rekonix/code/opencv/emsdk/emsdk-portable/emscripten/1.37.33/emcc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -Qunused-arguments -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O2  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -Qunused-arguments -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -O2
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:
    3rdparty dependencies:       zlib libprotobuf

  OpenCV modules:
    To be built:                 core dnn imgproc java_bindings_generator js objdetect python_bindings_generator video
    Disabled:                    calib3d features2d flann highgui imgcodecs ml photo shape stitching superres videoio videostab world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3 ts viz
    Applications:                -
    Documentation:               js
    Non-free algorithms:         NO

  GUI: 

  Media I/O: 
    ZLib:                        build (ver 1.2.11)

  Video I/O:

  Parallel framework:            none

  Other third-party libraries:
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  Python (for build):            /usr/local/bin/python2.7

  Install to:                    /Users/rampradeepk/Rekonix/code/opencv/emsdk/opencv/build_js/install

**Comment by alalek** [comment]
Does sample work directly from OpenCV documentation site?
You could compare build logs from this builder: http://pullrequest.opencv.org/buildbot/builders/master-contrib_docs-lin64/builds/10379
(start from compiler version - they are different)

It is better questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by Rampradeep** [comment]
Yes. The sample from opencv works. I will close this issue and continue the discussion on the forum.  One thing though, it would be good to have a detailed documentation on errors. Thanks.
