### ISSUE TITLE
Possibility to disable all modules when building

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10841]
##### System information (version)
- OpenCV => 3.4.0 (but also master)
- Operating System / Platform => Ubuntu 16.04 (might not matter)
- Compiler => g++ 5.4.0 (might not matter)

##### Detailed description

Right now, there is no possibility to disable all modules when building OpenCV. It is necessary to manually disable each module that is undesired individually before building. This requires tremendous effort, especially since there is practically no related documentation and each version (even minor ones) introduce new modules and dependencies between modules.

##### Steps to reproduce

Consider the following `cmake` configuration that I needed to figure out (from the Makefiles, the configuration output and re-testing all my programs) to build OpenCV with the following configuration:

> --   OpenCV modules:
> --     To be built:                 calib3d core features2d flann highgui imgcodecs imgproc ml objdetect sfm stereo video videoio viz xfeatures2d

`cmake -D BUILD_IPP_IW=OFF -D BUILD_ITT=OFF -D WITH_1394=OFF -D WITH_CUDA=OFF -D WITH_CUFFT=OFF -D WITH_GSTREAMER=OFF -D WITH_IPP=OFF -D WITH_JASPER=OFF -D WITH_WEBP=OFF -D WITH_OPENEXR=OFF -D WITH_PVAPI=OFF -D WITH_GIGEAPI=OFF -D WITH_QT=ON -D WITH_TIFF=OFF -D WITH_V4L=OFF -D WITH_LIBV4L=OFF -D WITH_OPENCL=OFF -D WITH_OPENCLAMDFFT=OFF -D WITH_OPENCLAMDBLAS=OFF -D WITH_MATLAB=OFF -D WITH_GPHOTO2=OFF -D WITH_LAPACK=OFF -D BUILD_opencv_apps=OFF -D BUILD_ANDROID_EXAMPLES=OFF -D BUILD_DOCS=OFF -D BUILD_PACKAGE=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_FAT_JAVA_LIB=OFF -D ENABLE_PRECOMPILED_HEADERS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_opencv_dnn=OFF -D BUILD_opencv_photo=OFF -D BUILD_opencv_stitching=OFF -D BUILD_opencv_superres=OFF -D BUILD_opencv_ts=OFF -D BUILD_opencv_videostab=OFF -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-3.4.0/modules -D BUILD_opencv_aruco=OFF -D BUILD_opencv_bgsegm=OFF -D BUILD_opencv_bioinspired=OFF -D BUILD_opencv_ccalib=OFF -D BUILD_opencv_cnn_3dobj=OFF -D BUILD_opencv_contrib_world=OFF -D BUILD_opencv_cvv=OFF -D BUILD_opencv_datasets=OFF -D BUILD_opencv_dnns_easily_fooled=OFF -D BUILD_opencv_dnn_modern=OFF -D BUILD_opencv_dpm=OFF -D BUILD_opencv_face=OFF -D BUILD_opencv_freetype=OFF -D BUILD_opencv_fuzzy=OFF -D BUILD_opencv_hdf=OFF -D BUILD_opencv_img_hash=OFF -D BUILD_opencv_shape=OFF -D BUILD_opencv_line_descriptor=OFF -D BUILD_opencv_matlab=OFF -D BUILD_opencv_optflow=OFF -D BUILD_opencv_phase_unwrapping=OFF -D BUILD_opencv_plot=OFF -D BUILD_opencv_python_bindings_generator=OFF -D BUILD_opencv_reg=OFF -D BUILD_opencv_rgbd=OFF -D BUILD_opencv_saliency=OFF -D BUILD_opencv_structured_light=OFF -D BUILD_opencv_surface_matching=OFF -D BUILD_opencv_text=OFF -D BUILD_opencv_tracking=OFF -D BUILD_opencv_ximgproc=OFF -D BUILD_opencv_xobjdetect=OFF -D BUILD_opencv_xphoto=OFF ../opencv-3.4.0/`

Even though OpenCV 3.4.0 is relatively recent, this `cmake` call will not produce the desired result for the master branch as of today, because new modules and dependencies have apparently been introduced. I would sincerely hope for an option to disable all modules to re-enable only those which are needed explicitly, like this:

`cmake -D DISABLE_EVERYTHING -D ENABLE_ONLY="calib3d core features2d flann highgui imgcodecs imgproc ml objdetect sfm stereo video videoio viz xfeatures2d" -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-3.4.0/modules ../opencv-3.4.0/`

Furthermore, an (up to date) document with all modules, their dependencies and the corresponding `cmake` flag names would be highly desirable. `opencv_contrib` has an outdated list in its `modules` directory, but several flags can currently only be guessed from the output of `cmake`, which is a very frustrating trial-and-error process.

**Comment by alalek** [comment]
This feature was already implemented by @mshabunin a few months ago: #9893
(included in OpenCV 3.4.0 release)
