### ISSUE TITLE
Error when compile Openface code

### ISSUE THREAD

**Issue by EhsanOthman** [opencv/opencv#10857]
I applied the code of OpenFace for feature extraction. There was an error when I compiled ("FaceAnalysis" has no member "PDM"). In fact, the included headers for PAW and PDM in FaceAnalyser and LandmarkDetector are included in the same directory "OpenFace". Thus, the PAW and PDM in LandmarkDetector overwrite the PAW and PDM in FaceAnalyser. How we can solve this problem. 

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by dkurt** [comment]
@EhsanOthman please use http://answers.opencv.org for build/install/usage questions and put some references to mentioned project and error message.
