### ISSUE TITLE
opencv2.framework for iOS is huge: 2GB

### ISSUE THREAD

**Issue by francoisbecker** [opencv/opencv#10866]
##### System information (version)

- OpenCV => master branch of today (post-3.4.0)
- OS => macOS 10.13.3
- Compiler => Xcode 9.2
- cmake version 3.10.2

##### Detailed description

Trying to use OpenCV as a framework for iOS, I've noticed that opencv2.framework is huge: 2GB. I can't envision (anyone) to deploy an app that big (as of 2018). I can remember that some time in the past the framework size was more reasonable (<300MB). According to the build options (see build command below), the build should be a release build.

##### Steps to reproduce

With the above system configuration and OpenCV source version, compile the OpenCV iOS framework using the following command: `python opencv/platforms/ios/build_framework.py opencv-ios`

**Comment by alalek** [comment]
Should be fixed here: #10864
