### ISSUE TITLE
GSoC2018

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#10877]
Just noticed in the OpenCV meeting notes (https://github.com/opencv/opencv/wiki/2018) that we did not get in this year as an organisation. Might be good to 

- Add a notice about this at the OpenCV main Wiki page: https://github.com/opencv/opencv/wiki
- Add a not accepted notice at https://github.com/opencv/opencv/wiki/GSoC_2018#2018-project-ideas
- Add a formal notice at the ideas list https://groups.google.com/forum/#!forum/opencv-gsoc-2018

At least we make sure that student do not put in efforts that will never be rewarded.

Too bad we did not get in, nevertheless I quite sure several people from the community are willing to help out in continuing the effort next year.

**Comment by alalek** [comment]
OpenCV Wiki was updated.
