### ISSUE TITLE
No proper error message in eigen.hpp if Eigen type declarations are not present in the project

### ISSUE THREAD

**Issue by SebNag** [opencv/opencv#10884]
##### System information (version)
- OpenCV => 3.4
- OS => 16.04.1-_Ubuntu_ SMP 4.13.0-32-generic _x86_64_
- Compiler => gcc 5.4.0

##### Detailed description

Including `opencv2/core/eigen.hpp` header _before_ including any Eigen headers in your project will lead to verbose compiler errors instead of issuing a _proper_ error description.  

##### Steps to reproduce

Assume you want to use the `eigen2cv` conversion template function to, obviously, convert an Eigen Matrix to an OpenCV matrix. You thus include: 

```cpp
#include <opencv2/core/eigen.hpp>
#include <eigen3/Eigen/Dense>
```
which however will lead to a bunch of errors similar to:

```gcc
error: ‘Eigen’ does not name a type

 void eigen2cv( const Eigen::Matrix<_Tp, _rows, _cols, _options, _maxRows, _maxCols>& src, Mat& dst) 

                          ^  
```

OpenCV fails to issue a proper error message to resolve this error. Reversing the include order and providing the required type declarations solves the problem. Thus, 

```cpp
#include <eigen3/Eigen/Dense>
#include <opencv2/core/eigen.hpp>
```

compiles .

**Comment by alalek** [comment]
> eigen3/Eigen/Dense

What is about "eigen2" ?

There is no way to detect installed eigen version on this stage, so proposed change is not valid.

"opencv2/core/eigen.hpp" is not included by default, so it is developer responsibility to use it properly (including required predefined types, includes).
