### ISSUE TITLE
Wrong Code Example in OpenCV-Python Tutorials

### ISSUE THREAD

**Issue by yasinguzel** [opencv/opencv#10886]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

I found the wrong code in [Changing Colorspaces
](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html) page, Object Tracking episode. 

Wrong Code: 

`mask = cv2.inRange(hsv, lower_green, upper_green)`

True Code:
`mask = cv2.inRange(hsv,lower_blue,upper_blue)`

**Comment by sturkmen72** [comment]
https://docs.opencv.org/master/df/d9d/tutorial_py_colorspaces.html

**Comment by alalek** [comment]
> Last updated on Nov 10, 2014

Don't use old documentation.

**Comment by yasinguzel** [comment]
Okey, thank you!
