### ISSUE TITLE
imread and imwrite cause differences in image pixels

### ISSUE THREAD

**Issue by sergiud** [opencv/opencv#10887]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Arch Linux
- Compiler => gcc 7.3

##### Detailed description

I noticed that images passed through ImageMagick's `convert` yield different results in some of my applications opposed to directly reading them using OpenCV's `imread`.

Specifically, I have a lossy JPG image that I convert to PNG. Since the conversion is lossless, I would expect no differences between both of the images. However, ImageMagick's `compare` tool reports differences between the original JPG image and the PNG version of the original written using `imwrite`.

##### Steps to reproduce

The following Python script illustrates the problem.

```.py
#!/bin/env python3

import cv2
import numpy as np
import subprocess

# Names of generated images
jpg_fname = 'whitenoise.jpg'
png_fname = 'whitenoise.png'

np.random.seed(42)

# Generate a 100x100 white noise image.
image = np.rint(np.random.rand(100, 100) * 255).astype(np.uint8)

# Convert the image to RGB and store it.
cv2.imwrite(jpg_fname, np.dstack((image, ) * 3))

# Convert JPEG to PNG losslessly
cv2.imwrite(png_fname, cv2.imread(jpg_fname, cv2.IMREAD_UNCHANGED))

compare = subprocess.Popen(['compare', '-metric', 'ae', jpg_fname, png_fname,
                            'diff.png'], stderr=subprocess.PIPE)

out, err = compare.communicate()
diff = err.decode('utf-8')

assert int(diff) == 0, 'expected 0 difference but got {}'.format(diff)
```
If I convert `whitenoise.jpg` to `whitenoise.png` using ImageMagick, there are no differences between the two.

**Comment by sergiud** [comment]
@alalek ???

**Comment by catree** [comment]
There is no difference in OpenCV on my computer:
```
img_jpg = cv2.imread(jpg_fname)
img_png = cv2.imread(png_fname)
diff = cv2.norm(img_jpg - img_png)
print("diff: ", diff) #print 0
```

There is no difference between OpenCV and PIL jpeg decoding on my computer:
```
def decode_jpeg_PIL(image_file):
  from PIL import Image
  im = Image.open(image_file)
  data = np.array(im)
  return data

img_jpg_PIL = decode_jpeg_PIL(jpg_fname)

diff_manual = 0.0
for i in range(img_jpg_PIL.shape[0]):
  for j in range(img_jpg_PIL.shape[1]):
    for c in range(img_jpg_PIL.shape[2]):
      diff_manual += np.sqrt((np.float(img_jpg[i,j,c]) - np.float(img_jpg_PIL[i,j,c]))**2)

print("diff_manual jpeg OpenCV PIL: ", diff_manual)
```

Probably that ImageMagick and OpenCV use different versions of libjpeg for jpeg decoding:
`ldd cv2.cpython-35m-x86_64-linux-gnu.so | grep jpeg`

	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fcfa2198000)
	libopenjpeg.so.5 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5 (0x00007fcf98057000)

`ldd /usr/bin/compare | grep jpeg` returns nothing. Also `convert -version` returns some delegate libraries?
```
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-31 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```
But I am not an expert in ImageMagick nor in Linux.

**Comment by sergiud** [comment]
What's the output of the above script?

**Comment by sergiud** [comment]
The same.

**Comment by alalek** [comment]
Reading of JPEG images is not bit-exact operation. It depends on used library (libjpeg/libjpeg-turbo) and or versions, platforms (x86/ARM), compiler options.
Related: #10641 #5871

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by sergiud** [comment]
I see, thanks.
