### ISSUE TITLE
feature request: add SELU activation function

### ISSUE THREAD

**Issue by lakshayg** [opencv/opencv#10888]
OpenCV supports ReLU, ELU, and several other activation functions. I would like to implement a relatively recently published activation function called SELU (Scaled Exponential Linear Unit, https://arxiv.org/abs/1706.02515) which has been shown to have several nice properties leading to better learning networks.

**Comment by dkurt** [comment]
@lakshayg, Is there any published trained networks with `selu` activation layers?

**Comment by lakshayg** [comment]
I am not aware of any published nets which use SELU (I have been out of
touch with deep learning for quite some time now). A quick Google scholar
search shows 46 citations for the SELU paper. I looked at some of the
results and found that they use SELU activation.

Personally, I have used SELU in simple architectures and it has good
results.

**Comment by dkurt** [comment]
Please look at custom layers registration: https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html.
