### ISSUE TITLE
DNN(OpenCL): test verification failed

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10897]
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/10377/steps/perf_dnn-ippicv-opencl/logs/stdio):
```
[ RUN      ] DNNTestNetwork.Inception_v2_SSD_TensorFlow/1, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
test verification failed @ image 0 group 0out_ch 0 h 0 w 1 got 3.18069 expected 2.58723
test verification failed @ image 0 group 0out_ch 0 h 0 w 1 got 3.18069 expected 2.58723
```

**Comment by alalek** [comment]
@pengli Could you take a look on this?
I see this message for both Linux SRB5.0 and new OpenCL [NEO](https://github.com/intel/compute-runtime) runtime.

**Comment by pengli** [comment]
yeah，i will take a look at this issue
