### ISSUE TITLE
error: (-215) !_aspectRatios.empty() in function PriorBoxLayerImpl Tensorflow MobileNet SSD DNN Module

### ISSUE THREAD

**Issue by miketsao** [opencv/opencv#10917]
- OpenCV => 3.4
- Operating System / Platform => Ubuntu 16.04
- Compiler => Python 3.5

## Detailed description
Error running net.forward() when using tensorflow mobilenet SSD model trained in tensorflow object detection API

[INFO] loading model...
OpenCV Error: Assertion failed (!_aspectRatios.empty()) in PriorBoxLayerImpl, file /root/opencv/modules/dnn/src/layers/prior_box_layer.cpp, line 207
[ INFO:0] Initialize OpenCL runtime...
Traceback (most recent call last):
  File "/opt/PyCharm/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/PyCharm/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/PyCharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dl_docker_user/opencv_dnn_wrapper/main.py", line 48, in <module>
    detections = net.forward()
cv2.error: /root/opencv/modules/dnn/src/layers/prior_box_layer.cpp:207: error: (-215) !_aspectRatios.empty() in function PriorBoxLayerImpl

## Steps to reproduce
Followed these steps to produce a tensorflow model to import into opencv with readNetFromTensorflow
- Train an SSD MobileNet  network with tensorflow object detection API
- Export the tensorflow checkpoint using the following command
python object_detection/export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path ${PIPELINE_CONFIG_PATH} \
    --trained_checkpoint_prefix ${TRAIN_PATH} \
    --output_directory output_inference_graph.pb

- Used optimize that frozen graph aka the .pb file with:
python ~/tensorflow/tensorflow/python/tools/optimize_for_inference.py \
  --input frozen_inference_graph.pb \
  --output opt_graph.pb \
  --input_names image_tensor \
  --output_names "num_detections,detection_scores,detection_boxes,detection_classes" \
  --placeholder_type_enum 4 \
  --frozen_graph

- Used the  tf_text_graph_ssd.py to convert that optimized graph into a .pbtxt
- Then ran following code
 ```python
# import the necessary packages
import numpy as np
import argparse
import cv2

# initialize the list of class labels MobileNet SSD was trained to
# detect, then generate a set of bounding box colors for each class
inWidth = 224
inHeight = 224
WHRatio = inWidth / float(inHeight)
inScaleFactor = 0.007843
meanVal = 127.5
swapRB = True
classNames = { 0: 'background',
    1: 'person', 2: 'bicycle', 3: 'car', 4: 'motorcycle', 5: 'airplane', 6: 'bus',
    7: 'train', 8: 'truck', 9: 'boat', 10: 'traffic light', 11: 'fire hydrant',
    13: 'stop sign', 14: 'parking meter', 15: 'bench', 16: 'bird', 17: 'cat',
    18: 'dog', 19: 'horse', 20: 'sheep', 21: 'cow', 22: 'elephant', 23: 'bear',
    24: 'zebra', 25: 'giraffe', 27: 'backpack', 28: 'umbrella', 31: 'handbag',
    32: 'tie', 33: 'suitcase', 34: 'frisbee', 35: 'skis', 36: 'snowboard',
    37: 'sports ball', 38: 'kite', 39: 'baseball bat', 40: 'baseball glove',
    41: 'skateboard', 42: 'surfboard', 43: 'tennis racket', 44: 'bottle',
    46: 'wine glass', 47: 'cup', 48: 'fork', 49: 'knife', 50: 'spoon',
    51: 'bowl', 52: 'banana', 53: 'apple', 54: 'sandwich', 55: 'orange',
    56: 'broccoli', 57: 'carrot', 58: 'hot dog', 59: 'pizza', 60: 'donut',
    61: 'cake', 62: 'chair', 63: 'couch', 64: 'potted plant', 65: 'bed',
    67: 'dining table', 70: 'toilet', 72: 'tv', 73: 'laptop', 74: 'mouse',
    75: 'remote', 76: 'keyboard', 77: 'cell phone', 78: 'microwave', 79: 'oven',
    80: 'toaster', 81: 'sink', 82: 'refrigerator', 84: 'book', 85: 'clock',
86: 'vase', 87: 'scissors', 88: 'teddy bear', 89: 'hair drier', 90: 'toothbrush' }
COLORS = np.random.uniform(0, 255, size=(len(classNames), 3))

# load our serialized model from disk
print("[INFO] loading model...")
pb_path = r"opt_model.pb"
pbtxt_path = r"opt_model.pbtxt"
video_path = "city.mp4"
net = cv2.dnn.readNetFromTensorflow(pb_path, pbtxt_path)
cap = cv2.VideoCapture(video_path)
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    if not ret:
        break
    blob = cv2.dnn.blobFromImage(frame, inScaleFactor, (inWidth, inHeight), (meanVal, meanVal, meanVal), swapRB)
    net.setInput(blob)
    detections = net.forward()
```
[opt_model.pb.txt](https://github.com/opencv/opencv/files/1746102/opt_model.pb.txt)
[opt_model.pbtxt.txt](https://github.com/opencv/opencv/files/1746104/opt_model.pbtxt.txt)

Any ideas would be great. I essentially followed
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by dkurt** [comment]
@miketsao, Could you please try to use master branch and update a `.pbtxt` with the latest version of script?

**Comment by miketsao** [comment]
Yes I did and now it seems to be working! Thanks @dkurt

**Comment by rdeepc** [comment]
Hi, I am facing the same problem, even with the link given in opencv tensorflow od API config

**Comment by dkurt** [comment]
@rdeepc, Please do not use closed issues because they are hard to track. Ask a question at http://answers.opencv.org/questions/ including OpenCV version, model name and all the links and references to make it easier to reproduce. Thanks!

**Comment by aleafboat** [comment]
is not pass
