### ISSUE TITLE
Calling "opencv_createsamples" with a "-img" and a "-bg" argument results in an memory access error

### ISSUE THREAD

**Issue by sgrossberndt** [opencv/opencv#10910]
##### System information (version)

- OpenCV => master (as of Feb 20 14:14)
- Operating System / Platform => Linux / Debian
- Compiler => cmake

##### Detailed description

Although the issue reported in #10551 has been merged on 10 Jan in https://github.com/opencv/opencv/pull/10567 to master when compiling from master I still have the same issue:
Calling `opencv_createsamples` with a `-img` and a `-bg` argument results in an memory access error

##### Steps to reproduce

`opencv_createsamples -w 21 -h 30 -vec positive.vec -img sign.png -bg bg.txt -num 3`
using the files from the attached [createsamples.zip](https://github.com/opencv/opencv/files/1740615/createsamples.zip) work without problems in OpenCV 3.3.0 but fails in OpenCV 3.4.0 and in master as well

3.3.0:
```
user@host:/training# opencv_createsamples -w 21 -h 30 -vec positive.vec -img sign.png -bg bg.txt -num 3
Info file name: (NULL)
Img file name: sign.png
Vec file name: positive.vec
BG  file name: bg.txt
Num: 3
BG color: 0
BG threshold: 80
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 21
Height: 30
Max Scale: -1
Create training samples from single image applying distortions...
Open background image: bg.jpg
Done
```

master:
```
user@host:/training# opencv_createsamples -w 21 -h 30 -vec positive.vec -img sign.png -bg bg.txt -num 3
Info file name: (NULL)
Img file name: sign.png
Vec file name: positive.vec
BG  file name: bg.txt
Num: 3
BG color: 0
BG threshold: 80
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 21
Height: 30
Max Scale: -1
RNG Seed: 12345
Create training samples from single image applying distortions...
Speicherzugriffsfehler
```

OpenCV was in downloaded for master with
`wget https://github.com/opencv/opencv/archive/master.zip && unzip master.zip && cd opencv-master`

for 3.4.0 with
`wget https://github.com/opencv/opencv/archive/3.4.0.zip && unzip 3.4.0.zip && cd opencv-3.4.0`

for 3.3.0 with
`wget https://github.com/opencv/opencv/archive/3.3.0.zip && unzip 3.3.0.zip && cd opencv-3.3.0`

OpenCV was compiled in all versions using
```.sh
mkdir build && cd build
cmake -DBUILD_opencv_java=OFF -DBUILD_opencv_python3=OFF \
-DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_OPENGL=ON -DWITH_TBB=ON -DWITH_GDAL=ON \
-DENABLE_PRECOMPILED_HEADERS=OFF -DCMAKE_INSTALL_PREFIX="/usr/local/" -DBUILD_WITH_DEBUG_INFO=OFF -Wno-dev ..
make && make install && ldconfig
```

**Comment by Kekushke** [comment]
I see **exact** same issue in 3.4.2.
