### ISSUE TITLE
videoio: Videoio_Bunny.read_position fails with GStreamer backend

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#10932]
##### System information (version)

- OpenCV => recent master ( c729fbd )
- Operating System / Platform => Ubuuntu 14.04, ODROID-X2
- Compiler => 4.8.4
- GStreamer => 1.3.1.1

- Full cmake configuration pasted [here](https://gist.github.com/tomoaki0705/5932a36e0933bf1728048bac1136ae6e)

##### Detailed description
- The test ```videoio/Videoio_Bunny.read_position/12``` fails when using GStreamer as backend
```
[ RUN      ] videoio/Videoio_Bunny.read_position/12, where GetParam() = ("avi", 1800)
ENTERED doTest (82)
VIDEOIO(cvCreateCapture_GStreamer (CV_CAP_GSTREAMER_FILE, filename)): trying ...

(opencv_test_videoio:11132): GStreamer-CRITICAL **: gst_query_set_position: assertion 'format == g_value_get_enum (gst_structure_id_get_value (s, GST_QUARK (FORMAT)))' failed
VIDEOIO(cvCreateCapture_GStreamer (CV_CAP_GSTREAMER_FILE, filename)): result=0x1dfe30 ...
/home/odroid/opencv-fork/modules/videoio/test/test_video_io.cpp:65: Failure
Value of: img.empty()
  Actual: true
Expected: false
idx=124
Google Test trace:
/home/odroid/opencv-fork/modules/videoio/test/test_video_io.cpp:115: consecutive read
Seek to frame '20' is not supported. SKIP.
Seek to frame '40' is not supported. SKIP.
Seek to frame '60' is not supported. SKIP.
Seek to frame '80' is not supported. SKIP.
Seek to frame '100' is not supported. SKIP.
Seek to frame '120' is not supported. SKIP.
Seek to frame '49' is not supported. SKIP.
Seek to frame '62' is not supported. SKIP.
Seek to frame '120' is not supported. SKIP.
Seek to frame '106' is not supported. SKIP.
Seek to frame '27' is not supported. SKIP.
Seek to frame '43' is not supported. SKIP.
Seek to frame '7' is not supported. SKIP.
Seek to frame '104' is not supported. SKIP.
Seek to frame '88' is not supported. SKIP.
Seek to frame '38' is not supported. SKIP.
[  FAILED  ] videoio/Videoio_Bunny.read_position/12, where GetParam() = ("avi", 1800) (5411 ms)
```
- This test is loading image from same video sequence, but stored in different codec/format.
- Though, this test didn't fail totally, it's just failing to read the end of the file
- The idx is the frame number and it's supposed to read up to 124, but it fails at the end.
```
idx=124
```
- Looking on other platforms, the same tests passes when using 1.8.3 and 1.10.4
- The test log using [1.8.3 is here ](https://gist.github.com/tomoaki0705/1187a4e7f3c364b552b3653e77d5a8b0) and [1.10.4 is here](https://gist.github.com/tomoaki0705/f96cbb2ea5eb071b7ee6fa8f2d078854)
```
[ RUN      ] videoio/Videoio_Synthetic.write_read_position/12, where GetParam() = (976x768, ("mkv", "MJPG", 30, 1800))
VIDEOIO(cvCreateVideoWriter_GStreamer (filename, fourcc, fps, frameSize, is_color)): trying ...

(opencv_test_videoio:7772): GStreamer-CRITICAL **: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
VIDEOIO(cvCreateVideoWriter_GStreamer (filename, fourcc, fps, frameSize, is_color)): result=0x558de6e2f0 ...
VIDEOIO(cvCreateCapture_GStreamer (CV_CAP_GSTREAMER_FILE, filename)): trying ...
VIDEOIO(cvCreateCapture_GStreamer (CV_CAP_GSTREAMER_FILE, filename)): result=0x558de708e0 ...
Seek to frame '20' is not supported. SKIP.
Seek to frame '40' is not supported. SKIP.
Seek to frame '60' is not supported. SKIP.
Seek to frame '80' is not supported. SKIP.
Seek to frame '98' is not supported. SKIP.
Seek to frame '93' is not supported. SKIP.
Seek to frame '89' is not supported. SKIP.
Seek to frame '60' is not supported. SKIP.
Seek to frame '62' is not supported. SKIP.
Seek to frame '49' is not supported. SKIP.
Seek to frame '47' is not supported. SKIP.
Seek to frame '58' is not supported. SKIP.
Seek to frame '85' is not supported. SKIP.
Seek to frame '12' is not supported. SKIP.
[       OK ] videoio/Videoio_Synthetic.write_read_position/12 (7887 ms)
```
- I also pasted the cmake log [here](https://gist.github.com/tomoaki0705/17a8e0c2100a9a1aacaea01e94347cd1) and [here](https://gist.github.com/tomoaki0705/d54915e1ee0ad9175c3e08df9c9a1167). You can see that different version of GStreamer is used as backend
- 1.8.3 (Jetson TX1)
```
--     GStreamer:                   
--       base:                      YES (ver 1.8.3)
--       video:                     YES (ver 1.8.3)
--       app:                       YES (ver 1.8.3)
--       riff:                      YES (ver 1.8.3)
-- pbutils: YES (ver 1.8.3)
```
- 1.10.4 (ROCK64)
```
--     GStreamer:                   
--       base:                      YES (ver 1.10.4)
--       video:                     YES (ver 1.10.4)
--       app:                       YES (ver 1.10.4)
--       riff:                      YES (ver 1.10.4)
-- pbutils: YES (ver 1.10.4)
```
- Still, there are some questions to fill, but so far, it looks like this is a bug is that 
  - When usin gGSreamer 1.3.1.1 as backend
  - The avi contents get read from one frame later than it should
  - As aresult, the image run outs at the end of the sequence
- The OS is 14.04 and GStreamer is 1.3.1.1 which are relatively old, and I don't think it's a good idea to throw a patch for GStreamer 1.3.1.1
- I think the correct way is to just ignore this test

##### Current plan for fix
- I'm trying to fix this in [```test_video_io.cpp```](https://github.com/opencv/opencv/blob/c729fbd652b1ebfbb205ac90c303160573f40dd1/modules/videoio/test/test_video_io.cpp#L113-L119), but this test_video_io.cpp doesn't have access to GStreamer, and I think it's a messy way to include gstreamer here.
- Alternative was to rely CMake to detect this, and passing the version number via cvconfig.h

##### Question
- Is this correct way to go ?
- I mean, the effort looks too much compared to relatively old platform.
  - Ubuntu 14.04's EOL is about 1 year from now
  - Usually, GStreamer is not in mandatory package, so very few people will see this test failure
- Before twisting CMake, I'd like to discuss on this point.

##### Steps to reproduce
- Install GStreamer related package (1.3.1.1 or older) on Ubuntu 14.04
- run opencv_test_videoio

**Comment by mshabunin** [comment]
@tomoaki0705 , there was an old hack in the test for this case: https://github.com/opencv/opencv/commit/a419b6434729bffff4c59c01c9acbad76ba92b37#diff-e6ea07760774c10cc231eb0a1f2f130f

I think we can restore it:
```.cpp
{
    SCOPED_TRACE("consecutive read");
    int n_frames_to_read = n_frames;
    if (apiPref == CAP_GSTREAMER)
        n_frames_to_read--;
    for (int k = 0; k < n_frames_to_read; ++k)
    {
        checkFrameRead(k, cap);
    }
}
```

**Comment by tomoaki0705** [comment]
Thank you @mshabunin !
I created a PR by following your comment

Best.
