### ISSUE TITLE
embedded_ssd_mobilenet_v1 using in opencv c++ version

### ISSUE THREAD

**Issue by xbcReal** [opencv/opencv#10939]
I want to use the embedded_ssd_mobilenet_v1 model by opencv c++ version ,which is trained in tensorflow python,I ever tried the same thing but the model is ssd_mobilenet instead of the embedded version,although I met some problem but finally solved with the help of other people.But because it's too time consuming on my platform(tinkerboard),so I want to use the embedded version to get detection faster,but when I use this model in c++ opencv,it failed and report the following errors:

OpenCV Error: Unspecified error (Const input blob for weights not found) in getConstBlob, file /home/xbc/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 579
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/xbc/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:579: error: (-2) Const input blob for weights not found in function getConstBlob

I thinks this is caused by the incorrect pbtxt file using in the following code:

String weights = "/data/frozen_inference_graph.pb";                                                                                             
String prototxt = "../pbtxt/ssd_mobilenet_hat.pbtxt";
dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);

but I didn't find the correct one.So did you met the same problem? And how did you solve this?

Thanks .

**Comment by dkurt** [comment]
@xbcReal, Please follow a guide of how to work with SSD models from TensorFlow in OpenCV: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. If it does not work make an issue more simple to reproduce: attach a `.pb` model, specify version of OpenCV.

**Comment by Alvintang6** [comment]
@xbcReal 
Hi have you solve the problem yet? I got the same problem with you
Thanks

**Comment by xbcReal** [comment]
@Alvintang6  I'm trying to do this by the web site provided by dkurt,I 'will reply you later whether it works.

**Comment by xbcReal** [comment]
@Alvintang6  it won't report error using the .pbtxt file produced by the tool provided by @dkurt ,but the detect result seems not correct.

**Comment by xbcReal** [comment]
@dkurt  Hi,thanks for you help,and it doesn't report error anymore,but the model used by python tf code detect objects well,but using c++ opencv code it seems does't output correct bbox.I guess the reason is the code I used is for mobile-ssd instead for embedded-mobile-ssd model.Do you have a sample code for how to get the detect bbox result from the embedded-mobile-ssd model? Thanks.

**Comment by xbcReal** [comment]
I output the bbox produced by tf python code and opencv c++ code.I found that the python tf code output bbox as following:
boxes: [[[0.48616847 0.32456273 0.5719043  0.36506736]
  [0.48817295 0.39137262 0.57161564 0.4317271 ]
  [0.17184295 0.31928855 0.27021247 0.36755735]
  [0.17288518 0.38449278 0.27023977 0.43242595]
  [0.49070644 0.45021996 0.5716888  0.48942813]
  [0.48250633 0.26584074 0.5715775  0.3070542 ]
and the opencv c++ code output bbox as following:
[0, 1, 0.39883164, -87.42878, -119.55261, 99.473885, 114.22792;
 0, 1, 0.13128266, -67.32534, -174.75551, 72.507866, 175.54341;
 0, 1, 0.072781183, -157.07892, -94.051201, 156.91415, 93.795418;
 0, 1, 0.054214109, -207.14185, -68.914009, 213.63901, 69.790916;
the fourth to seventh col is the bbox,it output bbox coordinate out of range [0,1] and even get negative coordinate.What's the reason for this? Could you please have a look at this ?Thanks.
@dkurt

**Comment by dkurt** [comment]
@xbcReal please use http://answers.opencv.org for usage questions including model references if it is possible and paste code you use. Thanks!

**Comment by xbcReal** [comment]
ok,i will do this ,thanks so much.

**Comment by xbcReal** [comment]
@dkurt  hi, i put the question on the http://answers.opencv.org/question/185628/embedded_ssd_mobilenet_v1-using-in-opencv-c-version/,could you please have a look at it?Thanks.

**Comment by xbcReal** [comment]
@dkurt  hi i have put my question in http://answers.opencv.org/question/185628/embedded_ssd_mobilenet_v1-using-in-opencv-c-version/
could you please have a look at it?
Thanks.

**Comment by xbcReal** [comment]
@dkurt hi i have put my question in http://answers.opencv.org/question/185627/embedded_ssd_mobilenet_v1-using-in-opencv-c-version/
could you please have a look at it?
Thanks.

**Comment by Alvintang6** [comment]
@xbcReal thank you so much, I will try it later.

**Comment by seefun** [comment]
I changed the SSD+Mobilnet network structure. I only have the model.pb file after I train the network. How can I get the .pbtxt file?

**Comment by dkurt** [comment]
I close an issue because of no references to mentioned network.
