### ISSUE TITLE
OpenCV(3.4.0-dev) Error: Assertion failed (inputs[0]->size[1] % blobs[0].size[1] == 0)

### ISSUE THREAD

**Issue by praneethshub** [opencv/opencv#10937]
System information is:
- OpenCV => 3.4.0 (built from source master)
- Operating System / Platform = Ubuntu 16.04
-Python 2.7 & 3.5
##### Detailed description
I have issue while running dnn modules using stereocamera, while model & prototxt used runs well on webcamera device.

I am processing left frame from the stereocamera using opencv functions for tensorflow/caffe models. 

##### Error window
I have encountered below errors
```
Loading model...
 (Init) >> Video mode: VGA@720
[INFO] computing object detections...
[ INFO:0] Initialize OpenCL runtime...
OpenCV(3.4.0-dev) Error: Assertion failed (inputs[0]->size[1] % blobs[0].size[1] == 0) in forward, file /home/user/opencv/modules/dnn/src/layers/convolution_layer.cpp, line 962
Traceback (most recent call last):
  File "objectdetect.py", line 103, in <module>
    main()
  File "objectdetect.py", line 61, in main
    detections = net.forward()
cv2.error: OpenCV(3.4.0-dev) /home/user/opencv/modules/dnn/src/layers/convolution_layer.cpp:962: error: (-215) inputs[0]->size[1] % blobs[0].size[1] == 0 in function forward

```

**Comment by Siddhant24** [comment]
How did you solve this issue @praneethshub
