### ISSUE TITLE
Dependency on Eigen missing in pkg-config file

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10942]
##### System information (version)

- OpenCV => master
- Operating System / Platform => Ubuntu 16.04
- Compiler => g++ 5.4.0

##### Detailed description

Enabling OpenCV modules which require the Eigen library result in a pkg-config file for OpenCV which does not include Eigen as a dependency, thus making the compiler fail for programs that use any of these OpenCV modules.

##### Steps to reproduce

Consider the following OpenCV build options:

`cmake -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-3.4.0/modules -D BUILD_LIST=calib3d,features2d,flann,highgui,imgcodecs,imgproc,ml,objdetect,sfm,stereo,video,videoio,viz,xfeatures2 -D BUILD_ITT=OFF -D WITH_1394=OFF -D WITH_GSTREAMER=OFF -D WITH_IPP=OFF -D WITH_JASPER=OFF -D WITH_WEBP=OFF -D WITH_OPENEXR=OFF -D WITH_PVAPI=OFF -D WITH_GIGEAPI=OFF -D WITH_QT=ON -D WITH_TIFF=OFF -D WITH_OPENCL=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PACKAGE=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_FAT_JAVA_LIB=OFF -D ENABLE_PRECOMPILED_HEADERS=OFF -D CMAKE_BUILD_TYPE=RELEASE ../opencv-3.4.0/`

Note that this requires installing libeigen on my system beforehands like this:

`sudo apt-get install libeigen3-dev`

Building an OpenCV-based program (that makes use of any OpenCV modules requiring Eigen) with `make` and `pkg-config` fails due to libeigen not being listed in the pkg-config file. `pkg-config --cflags opencv` yields

`-I/usr/local/include/opencv -I/usr/local/include`

Note that `-I/usr/include/eigen3` is missing. It would be helpful if Eigen was added to the pkg-config file so that it does not have to be included manually. My current workaround is to use `pkg-config --cflags opencv eigen3` instead of `pkg-config --cflags opencv`.

**Comment by alalek** [comment]
Eigen is headers only library.
OpenCV doesn't require eigen headers by default. Also eigen objects is not used in OpenCV interfaces.
There is "core/eigen.hpp" header with **helper** templates. It is not required to use other OpenCV functionality.

It is you (developer) responsibility to configure Eigen include directory for your application. Eigen2 or Eigen3 as you wish: `pkg-config --cflags eigen`

BTW, pkg-config will not be supported anymore in OpenCV. Consider using CMake instead via `find_package(Eigen)` statement.


> Enabling OpenCV modules which require the Eigen

What modules? Eigen support should be optional in the main OpenCV modules, and should disable modules itself in opencv_contrib if eigen is required (like sfm).

**Comment by dustsigns** [comment]
Consider the following minimum example:

```
#include <opencv2/sfm.hpp>

int main()
{
  return 0;
}
```

Trying to compile this with `g++ test.cpp $(pkg-config --cflags opencv) -o test.o` yields the following error:

```
In file included from /usr/local/include/opencv2/sfm.hpp:42:0,
                 from test.cpp:1:
/usr/local/include/opencv2/sfm/numeric.hpp:41:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
```

Compilation succeeds with `g++ test.cpp $(pkg-config --cflags opencv eigen3) -o test.o`.

If a library (like OpenCV with additional modules from contrib) requires these headers, I would expect them to be required as a dependency.

I would greatly appreciate if `pkg-config` would continue to be supported.

**Comment by dustsigns** [comment]
It seems that this issue has been resolved. It does no longer occur with the OpenCV 4.4.
