### ISSUE TITLE
WImage3D not visible since OpenCV 3.4.1

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10945]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04 with VTK 6.2
- Compiler => g++ 5.4.0

##### Detailed description

Images visualized with `cv::viz::WImage3D` are not visible in `cv::viz::Viz3d` windows in OpenCV 3.4.1, even though they were in 3.4.0.

##### Steps to reproduce

Consider the following minimum example:

```
#include <iostream>
#include <opencv2/viz.hpp>
#include <opencv2/highgui.hpp>

using namespace std;
using namespace cv;
using namespace viz;

int main(const int argc, const char * const argv[])
{
  if (argc != 2)
  {
    cerr << "Usage: " << argv[0] << " <input image>" << endl;
    return 1;
  }
  const Mat image = imread(argv[1]);
  assert(!image.empty());
  Viz3d visualization("Test");
  WImage3D viz_image(image, Size2d(1, 1), Vec3d(0, 0, 0), Vec3d(0, 0, -1), Vec3d(0, 1, 0));
  visualization.showWidget("Image", viz_image);
  visualization.spin();
}
```

This shows the image in version 3.4.0, but shows an empty window in 3.4.1. Note that the `WImage3D` constructor which only takes the image and a size as arguments works in both versions, so this might be related to the widget's position and thus the translation bug (#10944).

**Comment by dustsigns** [comment]
Could this be categorized as a bug? The issue is also reproducible with 3.4.2 (the current master is affected by an issue that I will create shortly). It is also reproducible with newer versions of Ubuntu (18.04), VTK (7.1.1) and g++ (7.3.0), which strongly hints at it being an OpenCV issue (it works with OpenCV 3.4.0 in all setups).

**Comment by alalek** [comment]
> it works with OpenCV 3.4.0

Try to run "git bisect" to detect commit which introduces problem.

**Comment by dustsigns** [comment]
I think commit 28a78003f0b49336b8736b0ae131bcd0d3500b7e introduced this issue.

For others to reproduce:

Build command (minimum number of modules to build the sample program): `cmake -D BUILD_LIST=highgui,viz -D BUILD_ITT=OFF -D WITH_1394=OFF -D WITH_GSTREAMER=OFF -D WITH_IPP=OFF -D WITH_JASPER=OFF -D WITH_WEBP=OFF -D WITH_OPENEXR=OFF -D WITH_PVAPI=OFF -D WITH_GIGEAPI=OFF -D WITH_QT=ON -D WITH_TIFF=OFF -D WITH_OPENCL=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PACKAGE=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_FAT_JAVA_LIB=OFF -D ENABLE_PRECOMPILED_HEADERS=OFF -D CMAKE_BUILD_TYPE=RELEASE ../opencv/ && make clean && make -j2 && sudo make install`

````
git checkout 6d4f66472e14b29b8e1623859cfebfdc67f677c3
git bisect start
git bisect good
git checkout 6ffc48769ac60d53c4bd1913eac15117c9b1c9f7
git bisect bad
Bisecting: 240 revisions left to test after this (roughly 8 steps)
[f57630d92ba959ff77bf33023fdc51d60c2635a9] Merge pull request #10691 from alalek:parallel_for_2018
git bisect good
Bisecting: 120 revisions left to test after this (roughly 7 steps)
[5a791e6e0646d9d4f4bf5352913943623d200f6a] cmake: update reporting of excluded dispatching files (#10711)
git bisect bad
Bisecting: 59 revisions left to test after this (roughly 6 steps)
[e801e336ede0d43cb8e7be698424b7320925b700] Merge pull request #10769 from mshabunin:add-tbb-cmake-support
git bisect good
Bisecting: 30 revisions left to test after this (roughly 5 steps)
[f8b03d4a4bdf8b74d9c1825a15ae55bcbfba7a8d] Merge pull request #10806 from alalek:build_cxx17
git bisect good
Bisecting: 14 revisions left to test after this (roughly 4 steps)
[e2a99d24ec8f48ca56ead3a6beb7fe38fc067a12] Merge pull request #10813 from alalek:cmake_cxx_flags
git bisect good
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[b7ad95beaa6efa5035ce48b742e0be8bf79ba953] Merge pull request #10836 from csukuangfj:fix-10826
git bisect bad
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[efd3fafa25349f000cc8c2825848c69d3820ccb3] Merge pull request #10834 from csukuangfj:fix-issue-9387
git bisect good
Bisecting: 1 revision left to test after this (roughly 1 step)
[2c8da29f3a9716a181fc10897257c724c68dc084] Merge pull request #10835 from csukuangfj:fix-10827
git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[28a78003f0b49336b8736b0ae131bcd0d3500b7e] Fix issue 10827.
git bisect reset HEAD
git rev-parse HEAD
28a78003f0b49336b8736b0ae131bcd0d3500b7e
````

**Comment by alalek** [comment]
@dustsigns Could you check this patch: #12274 ?
