### ISSUE TITLE
Use of fisheye::distortPoints always yields extremely distorted image

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10947]
##### System information (version)
- OpenCV => 3.4.0 (but also affects earlier and later versions)
- Operating System / Platform => Ubuntu 16.04
- Compiler => g++ 5.4.0

##### Detailed description

`cv::fisheye::distortPoints`, according to its [documentation](https://docs.opencv.org/3.4.1/db/d58/group__calib3d__fisheye.html#ga75d8877a98e38d0b29b6892c5f8d7765), can be used to distort undistorted points of an image using the fisheye model.

I am trying to find any further documentation on how to use this function to deliberately distort an image, i.e., to do the opposite of `cv::fisheye::undistortImage`. However, all attempts to get a distorted version of an image failed, even those with an all-zero distortion vector. Since there are no examples or further documentation, I suspect that this is either a bug or needs an example/more documentation.

##### Steps to reproduce

I wrote this program to try and get a slightly distorted version of the input image by passing a list of all pixel positions to `distortPoints` and then remapping them:

```
#include <iostream>

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/calib3d.hpp>

using namespace std;

using namespace cv;
using namespace cv::fisheye;

static Mat_<Point2f> GetDistortionMapping(const Size2i &image_size, const array<float, 4> &distortion_vector)
{
  Mat_<float> empty_camera_matrix = Mat::eye(3, 3, CV_32F);
  empty_camera_matrix(2, 0) = image_size.width / 2.f;
  empty_camera_matrix(2, 1) = image_size.height / 2.f;
  Mat_<Point2f> image_points(image_size);
  for (int y = 0; y < image_size.height; y++)
    for (int x = 0; x < image_size.width; x++)
      image_points(x, y) = Point2f(y, x);
  Mat_<Point2f> distorted_points(image_size);
  distortPoints(image_points, distorted_points, empty_camera_matrix, distortion_vector);
  return distorted_points;
}

static void ShowImage(const Mat &image)
{
  namedWindow("Distorted");
  const array<float, 4> distortion_vector { 1.f, 0.f, 0.f, 0.f }; //Even an all-zero vector yields an extremely distorted image
  const Mat distortion_mapping = GetDistortionMapping(image.size(), distortion_vector);
  Mat distorted_image;
  remap(image, distorted_image, distortion_mapping, noArray(), INTER_LANCZOS4);
  imshow("Distorted", distorted_image);
}

int main(const int argc, const char * const argv[])
{
  if (argc != 2)
  {
    cout << "Illustrates the effect of the distortion vector on a camera." << endl;
    cout << "Usage: " << argv[0] << " <camera image>" << endl;
    return 1;
  }
  const auto filename = argv[1];
  const Mat image = imread(filename);
  if (image.empty())
  {
    cerr << "Could not read input image '" << filename << "'" << endl;
    return 2;
  }
  ShowImage(image);
  waitKey(0);
  return 0;
}
```

All my attempts lead to an extremely distorted image like this, even with an all-zero distortion vector:

![15035778566029332](https://user-images.githubusercontent.com/11800082/36689968-eda39d1e-1afe-11e8-8660-a46051b08ce1.png)

Note: I asked this question more than half a year ago at [answers.opencv.org](http://answers.opencv.org/question/172922/correct-use-of-fisheyedistortpoints/), but did even not get a single comment, let alone an answer.

**Comment by dustsigns** [comment]
To clarify: Even with an all-zero distortion vector, i.e., no distortion, `distortPoints` yielding an extremely distorted image is considered a question and not a bug?

**Comment by dustsigns** [comment]
Are there any updates on this? This issue is still flagged as a question.

**Comment by alalek** [comment]
You can take a look on [tests code](https://github.com/opencv/opencv/blob/4.1.1/modules/calib3d/test/test_fisheye.cpp#L97).

**Comment by dustsigns** [comment]
Is there any documentation where the values of [K and D](https://github.com/opencv/opencv/blob/ddbd10c0019f3ee5f43b7902d47e7fc4303a6574/modules/calib3d/test/test_fisheye.cpp#L664) come from? My issue above is related to "identity" camera matrix still distorting the image.

**Comment by dustsigns** [comment]
I tried a test image with the exact size from the test code (1280x800) and the exact values of K and D from the test code. The resulting image is black:

```
#include <iostream>

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/calib3d.hpp>

using namespace std;

using namespace cv;
using namespace cv::fisheye;

static Mat_<Point2f> GetDistortionMapping(const Size2i &image_size)
{
  const Matx33d K(558.478087865323,               0, 620.458515360843,
                              0, 560.506767351568, 381.939424848348,
                              0,               0,                1);
  const Vec4d D(-0.0014613319981768, -0.00329861110580401, 0.00605760088590183, -0.00374209380722371);
  Mat_<Point2f> image_points(image_size);
  for (int y = 0; y < image_size.height; y++)
    for (int x = 0; x < image_size.width; x++)
      image_points(y, x) = Point2f(y, x);
  Mat_<Point2f> distorted_points(image_size);
  distortPoints(image_points, distorted_points, K, D);
  return distorted_points;
}

static void ShowImage(const Mat &image)
{
  namedWindow("Distorted");
  const Mat distortion_mapping = GetDistortionMapping(image.size());
  Mat distorted_image;
  remap(image, distorted_image, distortion_mapping, noArray(), INTER_LANCZOS4);
  imshow("Distorted", distorted_image);
}

int main(const int argc, const char * const argv[])
{
  if (argc != 2)
  {
    cout << "Illustrates the effect of the distortion vector on a camera." << endl;
    cout << "Usage: " << argv[0] << " <camera image>" << endl;
    return 1;
  }
  const auto filename = argv[1];
  const Mat image = imread(filename);
  if (image.empty())
  {
    cerr << "Could not read input image '" << filename << "'" << endl;
    return 2;
  }
  ShowImage(image);
  waitKey(0);
  return 0;
}
```

As a test image, I just resized Lenna. It might be that the test code correctly maps pixel positions somewhere and then maps them back, but at least the calculated distorted points do not seem to make an image.

![Distorted_screenshot_13 08 2019](https://user-images.githubusercontent.com/11800082/62920581-7bc15780-bda6-11e9-9715-ce685cb2cf32.png)

**Comment by slitcch** [comment]
I have this issue too

**Comment by asmorkalov** [comment]
Incomplete. No unswers for along time.

**Comment by dustsigns** [comment]
@asmorkalov What exactly is incomplete here? I even provided a code example. Me and others are still waiting for an answer, so I cannot understand why not having answers is a valid reason to close this issue.

**Comment by asmorkalov** [comment]
I appologize. wrong browser tab.

**Comment by victor1234** [comment]
@dustsigns 
From [documentation](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html#ga75d8877a98e38d0b29b6892c5f8d7765):
> Note that the function assumes the camera intrinsic matrix of the undistorted points to be identity. This means if you want to transform back points undistorted with [fisheye::undistortPoints](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html#gab738cdf90ceee97b2b52b0d0e7511541) you have to multiply them with P−1. 

So you need:
1. Add `K.inv()` multiplication
2. Swap `x`, `y` in Point2d() constructor, since it's a image point, not a matrix element

``` c++
for (int y = 0; y < image_size.height; y++) {
    for (int x = 0; x < image_size.width; x++) {
        Matx31d p(x, y, 1);
        p = K.inv() * p;
        image_points(y, x) = Point2f(p(0), p(1)); // no need p(0)/p(2), since p(2) = 1
   }
}
```

If you think the documentation is unclear and you have a suggestion on how to improve it, tell us.

**Comment by dustsigns** [comment]
@victor1234 Thank you very much, this now works nicely.

Regarding the documentation, I thought that the second sentence about `undistortPoints` that you quoted is not relevant for my use case since I am not undistorting any points. Here is my suggestion for clarifying the documentation:

> Note that the function assumes the camera intrinsic matrix of the undistorted points to be identity. This means that you have to multiply all points (point coordinates) by K^-1 before calling this function. This is the case if, for example, you want to transform back points undistorted with [fisheye::undistortPoints](https://docs.opencv.org/4.5.5/db/d58/group__calib3d__fisheye.html#gab738cdf90ceee97b2b52b0d0e7511541).

I think that the most important change would be to refer to the camera matrix as K in all parts of the function documentation. Neither P nor P^-1 are defined in this part of the documentation and it could mean the (pseudo-)inverse of a given point or any other matrix P that needs to be provided, computed etc.

**Comment by victor1234** [comment]
@dustsigns 
This non-obvious behavior was done for historical reasons.
PR with your recommendation for documentation was created.

**Comment by korroktheslavemaster** [comment]
I think `P^-1` is more correct since on this page https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html#ga75d8877a98e38d0b29b6892c5f8d7765 both `P` and `K` are referenced in different functions, and `P` is the correct one for this function. Just need to mention that the multiplication with `P^-1` needs to happen before calling this function.

**Comment by byfron** [comment]
You may have to provide a new camera matrix K to your undistort function to get a result that is properly scaled and centered. Try to simply scale your focal length with 0.5 and see if you get something better. You can also try to estimate the matrix using [cv::fisheye::estimateNewCameraMatrixForUndistortRectify](https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html#ga384940fdf04c03e362e94b6eb9b673c9)
