### ISSUE TITLE
protobuf is built even when the modules needing it are turned off

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#10950]
##### System information (version)
- OpenCV => 3.4.1 and master
- Operating System / Platform => Ubuntu 16.04
- Compiler => g++ 5.4.0

##### Detailed description

Since OpenCV 3.4.1, protobuf is built even when there are no modules enabled which require it. In 3.4.0, protobuf was not built if not needed.

##### Steps to reproduce

Consider the following build configuration on a system that does not have libprotobuf installed:

`cmake -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-3.4.1/modules -D BUILD_LIST=calib3d,features2d,flann,highgui,imgcodecs,imgproc,ml,objdetect,sfm,stereo,video,videoio,viz,xfeatures2 -D BUILD_ITT=OFF -D WITH_1394=OFF -D WITH_GSTREAMER=OFF -D WITH_IPP=OFF -D WITH_JASPER=OFF -D WITH_WEBP=OFF -D WITH_OPENEXR=OFF -D WITH_PVAPI=OFF -D WITH_GIGEAPI=OFF -D WITH_QT=ON -D WITH_TIFF=OFF -D WITH_OPENCL=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PACKAGE=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_FAT_JAVA_LIB=OFF -D ENABLE_PRECOMPILED_HEADERS=OFF -D CMAKE_BUILD_TYPE=RELEASE ../opencv-3.4.1/`

The output after configuration in OpenCV 3.4.1 is:
```
[..]
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   YES
[..]
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- The protocol buffer compiler is not found (PROTOBUF_PROTOC_EXECUTABLE='')
-- Module opencv_ovis disabled because OGRE3D was not found
[..]
--   Other third-party libraries:
--     Lapack:                      NO
--     Eigen:                       YES (ver 3.2.92)
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
[..]
```

Note that protobuf is not found and forced to be built, even though it is not needed.

Trying to use the same configuration in OpenCV 3.4.0 gives the desired output, i.e., protobuf is not built:

```
[..]
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   YES
[..]
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- The protocol buffer compiler is not found (PROTOBUF_PROTOC_EXECUTABLE='')
-- Checking for one of the modules 'freetype2'
[..]
--   Other third-party libraries:
--     Lapack:                      NO
--     Eigen:                       YES (ver 3.2.92)
--     Custom HAL:                  NO
[..]
```

**Comment by patrikhuber** [comment]
This would be quite an upgrade-blocker if true! Please don't have us build protobuf if we don't need & want it.

**Comment by mshabunin** [comment]
I tried to fix it in #10689, but unfortunately it does not help. At least you can use `-DWITH_PROTOBUF=OFF` cmake option to disable it. The problem is some sort of circular dependency: "to build dnn module we need to build protobuf" or "to build protobuf we have to enable dnn module". Adding here the fact that protobuf is built from sources _by default_ we realize that this relation differs from other 3rdparty libraries dependencies.

**Comment by patrikhuber** [comment]
> At least you can use -DWITH_PROTOBUF=OFF cmake option to disable it

Oh okay, I misunderstood the bug report then! It's not an issue in that case :-) 👍

**Comment by dustsigns** [comment]
I can confirm that adding `-D WITH_PROTOBUF=OFF` in my above example disables libprotobuf. Maybe this should be added to the build documentation until a fix is available that resolves the circular-dependency issue.
