### ISSUE TITLE
Compiling OpenCV3.4.1 with Java module failed (attached workaround)

### ISSUE THREAD

**Issue by songday** [opencv/opencv#10956]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => CentOS 7 64 Bit
- Compiler => GCC 4.8.5

##### Detailed description

Compiling OpenCV 3.4.1 from source with Java module

Occurred:
Traceback (most recent call last):
  File "/root/opencv/sources/modules/java/generator/../generator/gen_java.py", line 1094, in <module>
    copy_java_files(java_files_dir, target_path)
  File "/root/opencv/sources/modules/java/generator/../generator/gen_java.py", line 1043, in copy_java_files
    package_path = 'org/opencv/' + module
NameError: global name 'module' is not defined
make[2]: *** [CMakeFiles/dephelper/gen_opencv_java_source] Error 1
make[1]: *** [modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all] Error 2
make: *** [all] Error 2

Workaround:
edit /root/opencv/sources/modules/java/generator/../generator/gen_java.py
change line 1029 from:
re_package = re.compile(r'^package +(.+);$')
to
re_package = re.compile(r'^package +(.+);')

**Comment by songday** [comment]
Python version is: 2.7.5

**Comment by Bahramudin** [comment]
@alalek When this bug can be fixed, it wasted me a lot of time, I hope to be fixed as soon as possible.

**Comment by alalek** [comment]
@songday @Bahramudin
Could you grab additional info:
```.diff
         else:
+            print(java_file)
+            print(pformat(package_line))
             package_path = 'org/opencv/' + module
```

We need to understand reason of this problem.

**Comment by Bahramudin** [comment]
@alalek It is the result of adding the lines you mentioned:

> /home/bahramudin-adil/Desktop/opencv/opencv/modules/java/generator/src/java/org/opencv/utils/Converters.java
> 'package org.opencv.utils;\r\n'
> Traceback (most recent call last):
>   File "/home/bahramudin-adil/Desktop/opencv/opencv/modules/java/generator/../generator/gen_java.py", line 1095, in <module>
>     copy_java_files(java_files_dir, target_path)
>   File "/home/bahramudin-adil/Desktop/opencv/opencv/modules/java/generator/../generator/gen_java.py", line 1044, in copy_java_files
>     package_path = 'org/opencv/' + module
> NameError: global name 'module' is not defined
> modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/build.make:430: recipe for target 'CMakeFiles/dephelper/gen_opencv_java_source' failed
> make[2]: *** [CMakeFiles/dephelper/gen_opencv_java_source] Error 1
> CMakeFiles/Makefile2:2661: recipe for target 'modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all' failed
> make[1]: *** [modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

**Comment by alalek** [comment]
Thank you for update!

> '\r\n'

There is strange '\r' symbol:

Please check this:
```
$ hexdump -C -n32 modules/java/generator/src/java/org/opencv/utils/Converters.java 
00000000  70 61 63 6b 61 67 65 20  6f 72 67 2e 6f 70 65 6e  |package org.open|
00000010  63 76 2e 75 74 69 6c 73  3b 0a 0a 69 6d 70 6f 72  |cv.utils;..impor|
```
(`0a 0a` without any '0d'('\r') symbols)

And this:
```
$ python -c 'import re; print(re.compile(r"123$").match("123\n"))'
<_sre.SRE_Match object at 0xb73370>
$ python -c 'import re; print(re.compile(r"123$").match("123\r\n"))'
None
```

**Comment by Bahramudin** [comment]
@alalek  You are welcome! So what should I do now, because I cannot wait for the OpenCV team to update the source code, so where I can modify in the source? 
Thanks!!

**Comment by songday** [comment]
I guess that's the reason, regex has '$' symbol and \n makes package string cannot match the regex

**Comment by songday** [comment]
@Bahramudin have you tried my workaround in the first post?

**Comment by alalek** [comment]
@Bahramudin You can try to apply patch from the issue description (remove '$' symbol).

@songday For some reason Python '$' regex consumes '\n' normally (but this doesn't work for '\r' symbol).

Could you run one more checks from my comment above?

**Comment by Bahramudin** [comment]
@songday Sorry, I just saw the sulotion you mentioned, I will try it. I think alalek has already modified the file, I am going to re compile the source, hope the issue to be solved!! 
Thanks everyone!!

**Comment by songday** [comment]
@alalek Sorry, alalek. I cannot rerun at this moment, will do tomorrow my time.

**Comment by Bahramudin** [comment]
Hi Guys! Issue has ben gone.

**Comment by songday** [comment]
@alalek Hi alalek, added those 2 prints and got
/root/opencv/sources/modules/java/generator/src/java/org/opencv/osgi/OpenCVInterface.java
'package org.opencv.osgi;\r\n'

**Comment by alalek** [comment]
Thanks!

How did you get OpenCV sources?
If you using git, did you setup ['core.autocrlf'](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) configuration option (git config -l)?

**Comment by songday** [comment]
Downloaded opencv-3.4.1-vc14_vc15.exe on releases pages manually.

**Comment by alalek** [comment]
Well, I understand now. This is Windows package (with "CRLF"(`\r\n`) EOL markers in source code).

BTW, On Unix systems consider using "Source code (tar.gz)" link from release pages.

**Comment by songday** [comment]
I see, thanks for your explanation.
Since I need cross platform and opencv-3.4.1-vc14_vc15.exe has compiled dll, will download source code separately for Unix systems next time.
Thanks again.
