### ISSUE TITLE
opencv.js: Face detection using DNN fails

### ISSUE THREAD

**Issue by otmb** [opencv/opencv#10965]
- OpenCV => 3.4.1
- Operating System / Platform => Mac 10.13
- Emscripten-1.37.34

try [samples/dnn/js_face_recognition.html](https://github.com/opencv/opencv/blob/master/samples/dnn/js_face_recognition.html)
reference [dnn_javascript.markdown](https://github.com/opencv/opencv/blob/master/doc/tutorials/dnn/dnn_javascript/dnn_javascript.markdown)

I changed the model because I can not detect the face.
change model from res10_300x300_ssd_iter_140000_fp16.caffemodel to res10_300x300_ssd_iter_140000.caffemodel.

I would like to recommend using this model.
https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel

thank.

**Comment by dkurt** [comment]
@otmb, thank you! Perhaps, we need to replace a URL to a redirected one. Do you want to propose a PR?
![screenshot from 2018-03-01 08-14-29](https://user-images.githubusercontent.com/25801568/36828106-af38b650-1d28-11e8-9729-86533dfa2c7f.png)

**Comment by otmb** [comment]
It is attractive.
But the problem is not there.
When redirecting is changed, no error occurs, but face detection is 0 count and my face is not detected.
res10_300x300_ssd_iter_140000.caffemodel can detect my face.
But it may be another problem.

thank.

**Comment by dkurt** [comment]
@otmb, May I ask you to try these two models using a python script [resnet_ssd_face_python.py](https://github.com/opencv/opencv/blob/master/samples/dnn/resnet_ssd_face_python.py) or a C++ sample [resnet_ssd_face.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/resnet_ssd_face.cpp)? Please replace input sizes from 300x300 to `inWidth = 128`, `inHeight = 96` as it used in JavaScript sample.

**Comment by otmb** [comment]
I tried it.
I confirmed normal operation at resnet_ssd_face_python.py of fp16 model.

Returning to js and outputting the inference result to the trial, confidence was confirmed to be returned 0.5 x 62.
I do not have any details about this.

**Comment by dkurt** [comment]
@otmb, I've fixed it locally by https://github.com/opencv/opencv/pull/11259. The problem was in `CV_16SC1` -> `CV_32FC1` conversion.

**Comment by otmb** [comment]
Thank. @dkurt 
I tried #11259.
Manually rewrote modules/core/src/convert.cpp.
However, the same result as before.

**Comment by dkurt** [comment]
@otmb, let's wait for the documentation rebuild. I'll reopen an issue if it won't work again. Thank you!

**Comment by alalek** [comment]
Fix is deployed [here](https://docs.opencv.org/master/d5/d86/tutorial_dnn_javascript.html).

**Comment by dkurt** [comment]
@alalek, thanks! That works for me. @otmb, please note that due performance limitations it resizes an input frame to `128x96` instead of `300x300` (size of training images). So small faces likely won't be detected.
