### ISSUE TITLE
CUDA: Drop samples which using "NVIDIA CUDA Driver API" (libcuda.so)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10967]
- driver_api_multi.cpp
- driver_api_stereo_multi.cpp

OpenCV itself (except CUVID module) and other samples use "NVIDIA CUDA Runtime API" (libcudart.so) only.

http://docs.nvidia.com/cuda/cuda-driver-api/driver-vs-runtime-api.html#driver-vs-runtime-api

Also these samples requires TBB which is disabled in default builds.

**Comment by whizzzkid** [comment]
@alalek can you assign this to me?
