### ISSUE TITLE
Wrong output when using DNN_TARGET_OPENCL with blobFromImages

### ISSUE THREAD

**Issue by jstumpin** [opencv/opencv#10970]
**System information (version)**

- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 (x64)
- Compiler => Visual Studio 2017 (v140)
- iGPU => Intel Iris Plus Graphics 650 (23.20.16.4901)

**Detailed description**

DNN's _net.forward("softmax")_ (using GoogleNet as a test case) produces wrong classification label and unbounded probability (i.e. >1) when _DNN_TARGET_OPENCL_ is paired with _blobFromImages_. I'm uncertain whether or not it is a driver issue as pointed out [here](https://github.com/01org/caffe/issues/63#issuecomment-325092900) because either _DNN_TARGET_OPENCL_ or _blobFromImages_ works fine in solitary (e.g. _DNN_TARGET_OPENCL_ + _blobFromImage_ or _DNN_TARGET_CPU_ + _blobFromImages_). Since Intel's CaffeCL doesn't have a problem with batch processing, it's highly unlikely that driver is the issue.

**Steps to reproduce**

Code:
```
...
//using fine-tuned GoogleNet with 6 classes.
...
net.setPreferableTarget(DNN_TARGET_OPENCL);
inputBlob = blobFromImages(imgs, 1.0f, Size(), Scalar(), false); 
net.setInput(inputBlob, "data"); 
prob = net.forward("softmax");
for (int i = 0; i < imgs.size(); ++i)
{
   int classId;
   double classProb;
   getMaxClass(prob.row(i), &classId, &classProb);
   std::vector<String> classNames = readClassNames();
   std::cout << "---------- Prediction for " << labels[i] << " ----------" << std::endl;
   std::cout << "Best class: #" << classId << " '" << classNames.at(classId) << "'" << std::endl;
   std::cout << "Probability: " << classProb * 100 << "%" << std::endl;
}
...
```

Output:
**//using _DNN_TARGET_OPENCL_** 
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 99.9999%
---------- Prediction for c6.jpg ----------
Best class: #3 'c4'
Probability: 297.147%
---------- Prediction for c6.jpg ----------
Best class: #0 'c1'
Probability: 214.173%
---------- Prediction for c6.jpg ----------
Best class: #3 'c4'
Probability: 246.445%
---------- Prediction for c6.jpg ----------
Best class: #4 'c5'
Probability: 377.985%
---------- Prediction for c6.jpg ----------
Best class: #0 'c1'
Probability: 131.051%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 150.404%
---------- Prediction for c6.jpg ----------
Best class: #2 'c3'
Probability: 177.241%
---------- Prediction for c6.jpg ----------
Best class: #4 'c5'
Probability: 81.1507%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6 '
Probability: 409.997%

**//using _DNN_TARGET_CPU_**
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 99.9998%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 99.9999%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%
---------- Prediction for c6.jpg ----------
Best class: #5 'c6'
Probability: 100%

**Comment by dkurt** [comment]
@jstumpin, Thank you! If I'm right this bug could be reproduced only if you run the same `Net` object using blobs with different batch sizes. In example,  
```python
np.random.seed(2701)
img = np.random.standard_normal([224, 224, 3]).astype(np.float32)

net = cv.dnn.readNetFromCaffe('bvlc_googlenet.prototxt', 'bvlc_googlenet.caffemodel')
net.setPreferableTarget(cv.dnn.DNN_TARGET_OPENCL)

blob = cv.dnn.blobFromImage(img, 1.0, (224, 224), (0, 0, 0), False, False)
net.setInput(blob)
out = net.forward()
print out[:, 0:5]
```

produces `[[ 0.00046398  0.00062906  0.00050327  0.0016055   0.00496788]]` and that's OK. Then let's try to run network on batch size 2 from the beginning.

```python
np.random.seed(2701)
img = np.random.standard_normal([224, 224, 3]).astype(np.float32)

net = cv.dnn.readNetFromCaffe('bvlc_googlenet.prototxt', 'bvlc_googlenet.caffemodel')
net.setPreferableTarget(cv.dnn.DNN_TARGET_OPENCL)

blob = cv.dnn.blobFromImages([img, img], 1.0, (224, 224), (0, 0, 0), False, False)
net.setInput(blob)
out = net.forward()
print out[:, 0:5]
```
output:
```
[[ 0.00046398  0.00062906  0.00050327  0.0016055   0.00496788]
 [ 0.00046398  0.00062906  0.00050327  0.0016055   0.00496788]]
```
But if we change a batch size after the first `forward` pass,
```python
np.random.seed(2701)
img = np.random.standard_normal([224, 224, 3]).astype(np.float32)

net = cv.dnn.readNetFromCaffe('bvlc_googlenet.prototxt', 'bvlc_googlenet.caffemodel')
net.setPreferableTarget(cv.dnn.DNN_TARGET_OPENCL)

blob = cv.dnn.blobFromImage(img, 1.0, (224, 224), (0, 0, 0), False, False)
net.setInput(blob)
out = net.forward()

blob = cv.dnn.blobFromImages([img, img], 1.0, (224, 224), (0, 0, 0), False, False)
net.setInput(blob)
out = net.forward()
print out[:, 0:5]
```
Number of correct samples equals batch size from the first run (batch size 1 here):
```
[[ 0.00014901  0.00034072  0.00020369  0.00052105  0.00425998]
 [ 0.01349979  0.          0.          0.          0.        ]]
```

So the problem is that at the first `forward` pass network was initialized correctly but when input shape changed and network reinitialized some of layers still works for batch size 1. There are two possible solutions: work with the same batch size all the time or apply small changes to SoftMax layer that can fix it: https://github.com/opencv/opencv/pull/10992/files#diff-acc9c5de67036cf516ae66327919caf6R96 .

**Comment by jstumpin** [comment]
My bad for not elaborating on the code snippets. Indeed, I have a warm-up session prior to the actual forward pass which only consumed a single image. Wouldn't have known it to cause the problem since I did not face it with CaffeCL, albeit sharing the procedure. Although the first possible solution instantly fixed the issue, I can't say the same for the latter. The patch produces a constant pair of (mis)classification label and probability (e.g. "_c2_" & "_16.9916%_"). Varying batch sizes should be a norm for real-time query-based applications.

**Comment by dkurt** [comment]
@jstumpin, Let me disagree with you. You need to store output of each layer somewhere and varying batch size you change shapes of layers' outputs. In example, with batch size = 1 network produces output `1x1000` but for batch size 2 it produces `2x1000`. Even with advanced memory management reallocations may happen. Moreover you need to reinitialize backends or recompile computation kernels if they depends on shape.

**Comment by dkurt** [comment]
@jstumpin, Please check updated PR https://github.com/opencv/opencv/pull/10992. Now that works correct. Thank you!

**Comment by dkurt** [comment]
@jstumpin, can you share a code that measure efficiency to reproduce?

**Comment by jstumpin** [comment]
Prior to the PR, there is no latency regardless using fixed or varied batch sizes. Do note that the latency only occurs when varied batch sizes is in place. Here's the code for measurement:

```
long long milliseconds_now() {
	static LARGE_INTEGER s_frequency;
	static BOOL s_use_qpc = QueryPerformanceFrequency(&s_frequency);
	if (s_use_qpc) {
		LARGE_INTEGER now;
		QueryPerformanceCounter(&now);
		return (1000LL * now.QuadPart) / s_frequency.QuadPart;
	}
	else {
		return GetTickCount();
	}
}
...
start = milliseconds_now();
prob = net.forward("softmax");
elapsed = milliseconds_now() - start;
```

Average forward pass for 220 images on GoogleNet:
1. Fixed batch size (10 for warmup, 10 for actual): ~0.010041s
2. Varied batch size (1 for warmup, 10 for actual): ~0.015214s
