### ISSUE TITLE
opencv compile error

### ISSUE THREAD

**Issue by sktewary** [opencv/opencv#10976]
Hi 

I am  trying to compile opencv using scipion. I am getting errors. Any suggestions would be great.

Skipping command: wget -nv -c -O software/tmp/opencv-2.4.13.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/external/opencv-2.4.13.tgz
mv -v software/tmp/opencv-2.4.13.tgz.part software/tmp/opencv-2.4.13.tgz
  All targets exist.
  Skipping command: tar -xzf opencv-2.4.13.tgz
  All targets exist.
cd software/tmp/opencv-2.4.13
cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/sunil/software/scipion/software . > /home/sunil/software/scipion/software/log/opencv_cmake.log 2>&1
Error: target 'software/tmp/opencv-2.4.13/Makefile' not built (after running 'cmake -DWITH_FFMPEG=OFF -DWITH_CUDA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/sunil/software/scipion/software . > /home/sunil/software/scipion/software/log/opencv_cmake.log 2>&1')

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Current information is not enough to determine reason of this build failure. You should attach build logs at least.
