### ISSUE TITLE
External libraries without full path

### ISSUE THREAD

**Issue by cenit** [opencv/opencv#10977]
- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 64 Bit build 16299
- Compiler => Visual Studio 2017 (VS 15.5.7)

If I enable for example the following modules: `ovis, vtk, sfm, gdcm`, their respective dependencies are not exported with their full path, creating a linking error in downstream projects.
I am building OpenCV from sources, using `vcpkg`, and I am curating the port upgrade to v3.4.1 (https://github.com/Microsoft/vcpkg/pull/2906). Previously I am not even sure all the modules were even tested, so I think the issue is not just with latest version.

With those modules explicitly turned off, everything works fine.

With those modules enabled, OpenCV builds fine, but then if I try to link to it from a downstream project, I get some errors because some libraries (the newly added dependencies) are not found. For examples all the vtk libraries don't have their full path passed to the linker, only their name. So, if I enable the vtk module in OpenCV, they are passed to the linker without the library dir and without the full path. This would be fixed by adding a `find_package(VTK)` in the downstream project, but this is unreasonable if the downstream project does not require it (I should not ask downstream project to add a call to fix my problem...)

Something strange is going on, because for example many other libraries (zlib, jpeg, jasper, webp, ...) don't have any problem and their absolute path is correctly passed to the linker in the downstream projects. It seems that if a library is found through a `find_package()` call in `MODULE` option it works ok, while if the library is found through a `find_package()` call in `CONFIG` option it doesn't.

**Comment by alalek** [comment]
Do you build static binaries? This do not work due described problems - you must specify all dependencies during build (and redistribute them).
Consider using shared libraries (.dlls) instead (only redistribution is required in this case).

Perhaps CMake team can share some BKMs for this problem.

**Comment by cenit** [comment]
Yes static build. I will ask on the CMake repository (since I am also contributing some modules there)
