### ISSUE TITLE
Assertion failed in "getMemoryShapes" when using OpenCV dnn forward() by python

### ISSUE THREAD

**Issue by ChiFang** [opencv/opencv#10973]
##### System information (version)
- OpenCV => 3.4 by pip install "opencv_python-3.4.0.12-cp35-cp35m-manylinux1_x86_64.whl" 
- Operating System / Platform =>Ubuntu 16.04
- Compiler => python3
- Deep Learning framework = > Tensorflow 1.5 GPU version

##### Detailed description
I have trained a simple model into .pb file and want to test in python with OpenCV dnn but fail wehn I
call "detections = net.forward()"
error msg is as follow:

> [ INFO:0] Initialize OpenCL runtime...
OpenCV Error: Assertion failed (ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0) in getMemoryShapes, file /io/opencv/modules/dnn/src/layers/convolution_layer.cpp, line 217
Traceback (most recent call last):
  File "TestPB.py", line 15, in <module>
    detections = net.forward()
cv2.error: /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:217: error: (-215) ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0 in function getMemoryShapes

##### Steps to reproduce
step1: git clone https://github.com/ChiFang/TensorFlow_XO_example.git
step2: cd TensorFlow_XO_example
step3: unzip training_data_sm
step4: python3 TensorFlow_xo_predict.py >> soon
step5: python3 TestPB.py
or just download [.pb](https://drive.google.com/file/d/12-7TI7EGLuN8JgcafGPJKeugp263gVYD/view?usp=sharing) file and jump to step5

[TestPB.py](https://github.com/ChiFang/TensorFlow_XO_example/blob/master/TestPB.py):

> import cv2
ModelFile = "OX_Predict_frozen.pb"
print("Start...")
net = cv2.dnn.readNetFromTensorflow(ModelFile)
print("Load \'" + ModelFile + "\' Pass~~")
frame = cv2.imread("ci1.bmp")
inScaleFactor = 1 / 255
print("Read image Pass~~")
blob = cv2.dnn.blobFromImage(frame, inScaleFactor, (116, 116))
print("blobFromImage Pass~~")
net.setInput(blob)
print("setInput Pass~~")
detections = net.forward()
print(detections)

**Comment by dkurt** [comment]
@ChiFang, it's looks like an issue with `ci1.bmp`. Is it a black-n-white image with a single channel or RGB? In the first case you need to read it as grayscale by `cv2.imread("ci1.bmp", cv.IMREAD_GRAYSCALE)`.

**Comment by ChiFang** [comment]
Thanks @dkurt    it work~~~
I thought "imread" will automatically fit my .bmp channel without set parameter....

**Comment by dkurt** [comment]
@ChiFang, no, it loads images in BGR format by default. See https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56 . Can we close an issue?

**Comment by xiao-keeplearning** [comment]
> @ChiFang, it looks like an issue with `ci1.bmp`. Is it a black-n-white image with a single channel or RGB? In the first case you need to read it as grayscale by `cv2.imread("ci1.bmp", cv.IMREAD_GRAYSCALE)`.

This not help for me

**Comment by abhi-freebird** [comment]
Description:
I have defined a function that takes frame and processes it. But ,when the frame is passed through Network layer it gives the error as mentioned above:
**Error:**
File "Receive_Process_0.6.py", line 54, in frameProcessor
    detections = net.forward()
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\dnn\src\layers\convolution_layer.cpp:236:
error: (-215:Assertion failed) ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0 in function 'cv::dnn::ConvolutionLayerImpl::getMemoryShapes'


``def frameProcessor(self,frame):

        frame = cv2.imread(frame,0)

        (h, w) = frame.shape[:2]

        print(h,w)
        blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 1.0, (300, 300), (104.0, 177.0, 123.0))
        # pass the blob through the network and obtain the detections and
        # predictions
        net.setInput(blob)
        detections = net.forward()
        print(detections)``

Kindly help.
