### ISSUE TITLE
VideoWriter work in C++, but VideoWriter is null in C

### ISSUE THREAD

**Issue by renzhendian** [opencv/opencv#10991]
- OpenCV => 2.4.13.6
- Operating System => Ubuntu 16.04

VideoWriter work in C++, but VideoWriter is null in C, the parameters are the same 

// C++ code
cv::VideoWriter output_video;
output_video.open(out_videofile, CV_FOURCC('D', 'I', 'V', 'X'), 25, size, true);

// C code
CvVideoWriter* output_video_writer = NULL;   
output_video_writer = cvCreateVideoWriter(out_videofile, CV_FOURCC('D', 'I', 'V', 'X'), 25, size, 1);

**Comment by berak** [comment]
please understand, that the c-api was abandoned in 2010 already, 

there'll be no bug fixes for any problems related to that. you probably should not use any code containing Cv* or cv* functions or IPLImage* today

**Comment by alalek** [comment]
There are no way to use GStreamer/FFmpeg backends via legacy C-API anymore (after OpenCV 3.4.2 release).
