### ISSUE TITLE
OE-12 "Bring Lapack back" discussion

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#11007]
the feature request about evolution proposal [OE-12](https://github.com/opencv/opencv/wiki/OE-12.-Lapack)

**Comment by garybradski** [comment]
Should we instead depend on the (almost standard usage now) Ceres solver? (New BSD license):
http://ceres-solver.org/index.html

**Comment by vpisarev** [comment]
@garybradski, Ceres should definitely be considered, but not as alternative, but rather an addition to Lapack. It's solver, as you said, not a library of matrix algorithms.

**Comment by vpisarev** [comment]
done with https://github.com/opencv/opencv/pull/18571
