### ISSUE TITLE
Proper Usage of Memcpy - Security Issue

### ISSUE THREAD

**Issue by AnanthaRaja** [opencv/opencv#11028]
I need some help in proper usage of the following line 

 CvMat(const CvMat& m) { memcpy(this, &m, sizeof(CvMat));}

Is it correct to update the memcpy_s instead of memcpy

**Comment by alalek** [comment]
`memcpy_s` is C11, which is not enabled by default.
Using memcpy for classes is not a good idea anyway.

What is the problem? (message of code analyzer?)

**Comment by veyron95** [comment]
OpenCV 3.4.0 
`CvMat(const CvMat& m) { memcpy(this, &m, sizeof(CvMat));} ` will trigger a compilation warning，Is this line of code considered incorrect? How should it be modified?
