### ISSUE TITLE
open cv Installations issue

### ISSUE THREAD

**Issue by eng-tech1993** [opencv/opencv#11037]
hey friends, i have a proplem when i want  to install opencv using make -j4 or make commands

if anyone have an idea how to fix this proplem can help me please , thanx alot ,Best Regards..

im using raspbian stretch desktop..
------------------------------------------------------
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dkurt** [comment]
@eng-tech1993, Issue tracker is not the best place to ask build/install/usage questions. Please use a forum instead http://answers.opencv.org.
