### ISSUE TITLE
import cv2 segmentation fault

### ISSUE THREAD

**Issue by waschbaer00** [opencv/opencv#11045]
##### System information (version)
System Enviroment
- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04

Virtual enviroment myenv

- OpenCV => 3.2.0

##### Detailed description
I installed OpenCV 3.4.1 correctly using cmake command, I verify this by `import cv2` and `cv2.__version__`

However when I create conda virtual environment by:
`conda env create -n myenv -f env.yml`

I have conflict and segmentation fault: 

**Under the conda virtual env**, I have to always first

`cd PATH_TO_VIRTUAL_ENV/lib/python3.5/site_packages`
such that import cv2 is correctly using the 3.2.0 version of opencv,without this step, 3.4.1 will be used.

**Under the conda base environment** , if the PATH in ~/.bashrc is added to anaconda3, then I will under conda base enviroment by default. import cv2 will use opencv 3.4.1 version.

**Under the system enviroment**, i.e first delete the PATH to anaconda3, then import cv2 will lead to segmentation fault.

How could I solve this?

#Update: env.yml file#
```
name: myenv
channels:
- menpo
- defaults
dependencies:
- cairo=1.14.8=0
- certifi=2016.2.28=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.20=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=2
- icu=54.1=0
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np111py35_0
- mkl=2017.0.3=0
- numpy=1.11.3=py35_0
- openssl=1.0.2l=0
- pandas=0.20.1=np111py35_0
- patsy=0.4.1=py35_0
- pcre=8.39=1
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=5
- readline=6.2=2
- scipy=0.19.0=np111py35_0
- seaborn=0.8=py35_0
- setuptools=36.4.0=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np111py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- opencv3=3.2.0=np111py35_0
- pip:
  - bleach==1.5.0
  - enum34==1.1.6
  - html5lib==0.9999999
  - markdown==2.6.11
  - protobuf==3.5.1
  - tensorflow==1.4.1
  - tensorflow-tensorboard==0.4.0
  - werkzeug==0.14.1


```

**Comment by alalek** [comment]
Please stop creation of similar issues.

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Vanilla OpenCV installation works fine, so it is better to ask conda users/maintainers for help with your configuration (we doesn't provide opencv conda package).
