### ISSUE TITLE
opencv.org https certificate expired

### ISSUE THREAD

**Issue by vadimkantorov** [opencv/opencv#11040]
![opencv](https://user-images.githubusercontent.com/1041752/37186057-c01efe36-2343-11e8-9dc1-f280507f77c3.png)

**Comment by mshabunin** [comment]
Fixed, thank you!

**Comment by i-am-david-fernandez** [comment]
Certificate has expired again (and Firefox is presenting a "website is not secure" warning). Firefox reports an end-validity timestamp of Friday, 9 November 2018, 23:23:12 GMT.

**Comment by AndreaBaretta** [comment]
Same with me, although I don't get the security warning for opencv.org, only docs.opencv.org. When I press to continue regardless, the majority of the documentation is not available and I get the message 

`The webpage at https://docs.opencv.org/java/3.0.0/overview-summary.html might be temporarily down or it may have moved permanently to a new web address.`

**Comment by hrnr** [comment]
Yep, I can confirm too. The certificate expired yesterday.

```
Processed 121 CA certificate(s).
Resolving 'docs.opencv.org:443'...
Connecting to '2605:de00:1:1:4a:39:0:7:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=docs.opencv.org', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x0393bd4907806f9c6ca95368227b0f6d9fd8, RSA key 2048 bits, signed using RSA-SHA256, activated `2018-08-11 23:23:12 UTC', expires `2018-11-09 23:23:12 UTC', pin-sha256="PgQ85uemSQCz6j/2I9PnexPYobXaGL2WhYdUwausDN8="
        Public Key ID:
                sha1:3f1fd51959ba3ab6f852045b53978c17f3565427
                sha256:3e043ce6e7a64900b3ea3ff623d3e77b13d8a1b5da18bd96858754c1abac0cdf
        Public Key PIN:
                pin-sha256:PgQ85uemSQCz6j/2I9PnexPYobXaGL2WhYdUwausDN8=
        Public key's random art:
                +--[ RSA 2048]----+
                |             .E+@|
                |          . o. BB|
                |           + .ooo|
                |          . .  +o|
                |        S  .  o..|
                |         .  .o   |
                |          o.=    |
                |          .= +   |
                |          .o+    |
                +-----------------+

- Certificate[1] info:
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
- Status: The certificate is NOT trusted. The certificate chain uses expired certificate. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** handshake has failed: Error in the certificate.
```

**Comment by i-am-david-fernandez** [comment]
> 
> 
> Same with me, although I don't get the security warning for opencv.org, only docs.opencv.org. When I press to continue regardless, the majority of the documentation is not available and I get the message
> 
> `The webpage at https://docs.opencv.org/java/3.0.0/overview-summary.html might be temporarily down or it may have moved permanently to a new web address.`

Note that I'm still able to access the site(s), including the specific page you note above. I have, however, created a (temporary/unsaved) certificate exception in Firefox to allow access (though I don't think certificate-based denial would produce the message you quote).

**Comment by LaurentBerger** [comment]
Now I haven't got no problem to access https://docs.opencv.org. 
@i-am-david-fernandez may be some problem with cache browser. try in private navigation

**Comment by mshabunin** [comment]
Our hosting provider now supports Let's Encrypt certificates, so we've switched from previous semi-manual renewal process. I hope this problem will not occur anymore.
Thanks!
