### ISSUE TITLE
core.hpp hershey-font URL is broken

### ISSUE THREAD

**Issue by collenjones** [opencv/opencv#11054]
In OpenCV 3.4's `core.hpp`, the link to [http://sources.isc.org/utils/misc/hershey-font.txt](http://sources.isc.org/utils/misc/hershey-font.txt) above the `HersheyFonts` enum appears to be broken.

Is [this](https://github.com/kamalmostafa/hershey-fonts/blob/master/hershey-fonts/hershey.txt) the documentation that was intended? Does anyone know a stable home for this documentation? I can put in a PR.

**Comment by alalek** [comment]
No, proposed link is not related to original.
Original link contains some archive from December 1986: [web archive](https://www.web.archive.org/web/19981202040357/http://sources.isc.org/utils/misc/hershey-font.txt)

**Comment by collenjones** [comment]
I sent an email to ISC.org about this two weeks ago but no response yet.
Any thoughts on how we should update this?

**Comment by alalek** [comment]
I believe we could add **Wiki** link https://en.wikipedia.org/wiki/Hershey_fonts
