### ISSUE TITLE
cudaarithm: async call to NPP fails

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#11063]
##### System information (version)

- OpenCV => master 
- Operating System / Platform => Windows 10 Pro 64bit / CUDA 8.0
- Compiler => Visual Studio 2015 Win64
- Operating System / Platform => Ubuntu 64bit  / Jetson TX1 / CUDA 8.0
- Compiler => GCC 5.4.0

##### Detailed description
- test from ```opencv_test_cudaarithm``` fails
```
[==========] 10629 tests from 65 test cases ran. (34990 ms total)
[  PASSED  ] 10625 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] CUDA_Arithm/MeanStdDev.Async/0, where GetParam() = (NVIDIA Tegra X1, 128x128, whole matrix)
[  FAILED  ] CUDA_Arithm/MeanStdDev.Async/1, where GetParam() = (NVIDIA Tegra X1, 128x128, sub matrix)
[  FAILED  ] CUDA_Arithm/MeanStdDev.Async/2, where GetParam() = (NVIDIA Tegra X1, 113x113, whole matrix)
[  FAILED  ] CUDA_Arithm/MeanStdDev.Async/3, where GetParam() = (NVIDIA Tegra X1, 113x113, sub matrix)

 4 FAILED TESTS
```
- Also confirmed with Jetson TX2, Geforce GTX 650M, Geforce GTX 1060
- I cut out the minimum code from OpenCV and then the crash didn't reproduce.
- I googled up with the message "Microsoft C++ exception: NppStatus at memory location" which appeared on Visual Studio, and found [this post](https://devtalk.nvidia.com/default/topic/895161/gpu-accelerated-libraries/npp-row-and-column-filters/post/4746520/#4746520) from a nVidia person

> It seems that any time you issue a nppSetStream() call that in fact changes the underlying stream, you will need to issue a cudaDeviceSynchronize() call (first), before issuing the nppSetStream() call.

- This is exactly what is [happening inside OpenCV](https://github.com/opencv/opencv/blob/7e9578789b8f01cabf92d2c57691dbe65d6ee5df/modules/core/include/opencv2/core/private.cuda.hpp#L142)
- I added a macro to call ```cudaStreamSynchronize``` before ```nppSetStream``` and this solved the issue
- References
   - [Same situation still happens on CUDA 8.0](https://devtalk.nvidia.com/default/topic/999910/gpu-accelerated-libraries/npp-stream-crash/)
   - [Same explanation on NPP 9.1](http://docs.nvidia.com/cuda/npp/index.html)
> For this reason it is recommended that cudaDeviceSynchronize (or at least cudaStreamSynchronize) be called before making an nppSetStream call to change to a new stream ID. This will insure that any internal function calls that have not yet occurred will be completed using the current stream ID before it changes to a new ID.
   - [cudaStreamSynchronize](https://www.cs.cmu.edu/afs/cs/academic/class/15668-s11/www/cuda-doc/html/group__CUDART__STREAM_geb3b2f88b7c1cff8b67a998a3a41c179.html)

- I'll send a PR later

##### Steps to reproduce
- run ```opencv_test_cudaarithm --gtest_filter=*MeanStdDev*Async*```

**Comment by nglee** [comment]
I was also looking into this issue. In my case, using `cudaStreamSynchronize` nor `cudaDeviceSynchronize` solved the issue.

My testing environment is:
- Operating System / Platform => Windows 10 Pro 64bit / CUDA 8.0, 9.1
- Compiler => Visual Studio 2015
- GPU => GTX1080 with driver version 388.19

The error message on my machine is:
```
unknown file: error: C++ exception with description "OpenCV(3.4.1-dev) C:\Users\lee.namgoo\Repos\opencv_dev\opencv\modules\cudaarithm\src\reductions.cpp:162: error: (-217) Gpu API call: NPP_RANGE_ERROR [Code = -7] in function cv::cuda::meanStdDev" thrown in the test body.
```
The error message is identical before and after adding the synchronizing API.

**Comment by tomoaki0705** [comment]
Thank you @nglee , indeed, this issue still happens on my environment, too.
It passed once, and that made me believe that this fix works, but it's run time error happening inside, once was not enough.

Your feedback was very useful.  It encouraged me that I'm not the only one facing this issue.

I think I need to throw this issue to nvidia forum, and ask for feedback.

**Comment by nglee** [comment]
Thank you @tomoaki0705 for your comment.

In my case, after commenting out [this line](https://github.com/opencv/opencv/blob/d68466bb6a855efd3b7540740bb89ea43be1aef4/modules/cudaarithm/src/reductions.cpp#L160), the `MeanStdDev.Async` tests did not fail.

Could this be an indication that there's an internal issue in NPP?

About two weeks ago, I've opened a [topic](https://devtalk.nvidia.com/default/topic/1030559/gpu-accelerated-libraries/using-nppimean_stddev_8u_c1r-after-setnppstream-returns-npp_range_error/) at nvidia forum, and someone else opend a [similar topic](https://devtalk.nvidia.com/default/topic/1030832/gpu-accelerated-libraries/nppicountinrange-returns-npp_range_error-when-called-from-multiple-threads-cuda-9-1-/) recently. Both topic reports some NPP APIs returning `NPP_RANGE_ERROR` when `nppSetStream` is used, and both reports that the error is gone when `nppSetStream` is removed.

**Comment by tomoaki0705** [comment]
Thank you @nglee, following your suggestion, things are now moving forward.
Thank you for the report to nvidia !

Now, the situation is getting complicated.
[The line ](https://github.com/opencv/opencv/blob/d68466bb6a855efd3b7540740bb89ea43be1aef4/modules/cudaarithm/src/reductions.cpp#L160) that @nglee pointed is calling ```nppSetStream```.
Removing this call, it works but we have a ```cv::cuda::Stream``` which is created but never passed to driver.

At the end function,  [there is ```syncOutput``` ](https://github.com/opencv/opencv/blob/d68466bb6a855efd3b7540740bb89ea43be1aef4/modules/cudaarithm/src/reductions.cpp#L164) which is passing a stream which never actually passed to driver to wait.

I'm bit afraid that there might be a data corruption at the end.

Still, getting back to the original goal "execute a npp function asynchronously" may be it's no problem to keep using default stream (=0), or may be removing ```nppSetStream``` is the correct way.
I just need more time to investigate
