### ISSUE TITLE
Large JSON can't be loaded while smaller ones can

### ISSUE THREAD

**Issue by 326623** [opencv/opencv#11061]
- OpenCV => :grey_question: 3.4.1-dev
- Operating System / Platform => :grey_question: Ubuntu16.04.4lts
- Compiler => :grey_question: g++ 5.4.0

##### Detailed description

# The FileStorage could not handle large JSON file. 

OpenCV(3.4.1-dev) Error: Parsing error (../models/svm_0.json(0): Unexpected character) in icvJSONParseSeq, file /home/king-kong/my-repo/action_detect/opencv/modules/core/src/persistence_json.cpp, line 460
error: OpenCV(3.4.1-dev) /home/king-kong/my-repo/action_detect/opencv/modules/core/src/persistence_json.cpp:460: error: (-212) Parsing error: ../models/svm_0.json(0): Unexpected character in function icvJSONParseSeq

OpenCV(3.4.1-dev) Error: Unknown error code -49 (Input file is empty) in cvOpenFileStorage, file /home/king-kong/my-repo/action_detect/opencv/modules/core/src/persistence_c.cpp, line 384
error: OpenCV(3.4.1-dev) /home/king-kong/my-repo/action_detect/opencv/modules/core/src/persistence_c.cpp:384: error: (-49) Unknown error code -49: Input file is empty in function cvOpenFileStorage

And Interestingly, after I split the json file into smaller pieces, the FileStorage is able to handle the json file. 

##### Steps to reproduce

I have the json file and the code here, https://github.com/326623/test/tree/3884c5cd0231abbdc953d10361a0453f4ab4b8f2

Thanks in adanced!

**Comment by alalek** [comment]
Problem exists in all OpenCV parsers: XML, YAML, JSON. Observed on data with very long lines which exceeds internal buffer size (1Mb).
In this case they are not able to properly read/parse numbers which are truncated in the end of current buffer. They just ignore next part of data with second part of processing number. Only the contents of current buffer is scanned.

**Comment by terfendail** [comment]
Could #8735 be related to the issue?
