### ISSUE TITLE
Warp image with optical flow to produce a new image

### ISSUE THREAD

**Issue by juliohm** [opencv/opencv#11068]
I tried asking in the forum, but it seems pretty much inactive. I am not sure what I am doing wrong, but the code below doesn't generate the expected output. I have `im1` and `im2` (attached below) for which I compute the optical flow. Then I want to apply the flow to `im1` to double check that it produces `im2`:

![0001](https://user-images.githubusercontent.com/3345261/37369136-79851124-26c5-11e8-9820-685d6a636caf.png)
![0002](https://user-images.githubusercontent.com/3345261/37369145-7cdaf9c4-26c5-11e8-9d87-c2048be99267.png)

```python
import cv2
import numpy as np
from imageio import imread

im1 = np.asarray(imread("0001.png"))
im2 = np.asarray(imread("0002.png"))
im1 = np.float64(im1 / 255)
im2 = np.float64(im2 / 255)

flow = cv2.calcOpticalFlowFarneback(im1, im2, None, 0.5, 3, 15, 3, 5, 1.2, 0)

def draw_hsv(flow):
    h, w = flow.shape[:2]
    fx, fy = flow[:,:,0], flow[:,:,1]
    ang = np.arctan2(fy, fx) + np.pi
    v = np.sqrt(fx*fx+fy*fy)
    hsv = np.zeros((h, w, 3), np.uint8)
    hsv[...,0] = ang*(180/np.pi/2)
    hsv[...,1] = 255
    hsv[...,2] = cv2.normalize(v, None, 0, 255, cv2.NORM_MINMAX)
    bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
    return bgr

def warp_flow(img, flow):
    h, w = flow.shape[:2]
    flow = -flow
    flow[:,:,0] += np.arange(w)
    flow[:,:,1] += np.arange(h)[:,np.newaxis]
    res = cv2.remap(img, flow, None, cv2.INTER_LINEAR)
    return res

hsv = draw_hsv(flow)
im2w = warp_flow(im1*255, flow)
cv2.imwrite("/tmp/flow.jpg",hsv)
cv2.imwrite("/tmp/im1.jpg", im1*255)
cv2.imwrite("/tmp/im2.jpg", im2*255)
cv2.imwrite("/tmp/im2w.jpg", im2w)
```

The printed images do not look correct. Could you please provide some help on how to fix this use case?

**Comment by juliohm** [comment]
The code works fine if we don't normalize the images and leave the values between [0,255]. It is an issue of scale.

**Comment by CJEQ** [comment]
hi @juliohm , you said that "The code works fine if we don't normalize the images and leave the values between [0,255]". Which means that change the "im1 = np.float64(im1 / 255) and im2 = np.float64(im2 / 255)" to "im1 = np.float64(im1) im2 = np.float64(im2)" works fine for you? It seems doesn't work for me only change this settings.

**Comment by juliohm** [comment]
Yes, that is what I remember doing at that time, and it worked for me. I
can try find the code again when I have access to my laptop.

**Comment by amritanjali123** [comment]
@juliohm I am getting mean square error 302 is it fine?

**Comment by sandeshbhusal** [comment]
> @juliohm I am getting mean square error 302 is it fine?

Should I be using SSIM or MSE for image error computation?

**Comment by sazidabintaislam** [comment]
I am getting below error after running the code -"OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\video\src\optflowgf.cpp:1114: error: (-215:Assertion failed) prev0.size() == next0.size() && prev0.channels() == next0.channels() && prev0.channels() == 1 && pyrScale_ < 1 in function 'cv::`anonymous-namespace'::FarnebackOpticalFlowImpl::calc"

**Comment by sazidabintaislam** [comment]
@juliohm I am getting below error after running the code -"OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\video\src\optflowgf.cpp:1114: error: (-215:Assertion failed) prev0.size() == next0.size() && prev0.channels() == next0.channels() && prev0.channels() == 1 && pyrScale_ < 1 in function 'cv::`anonymous-namespace'::FarnebackOpticalFlowImpl::calc"

**Comment by DaddyWesker** [comment]
Could anyone tell me what is the meaning of this? 
```
flow[:,:,0] += np.arange(w)
flow[:,:,1] += np.arange(h)[:,np.newaxis]
```

I've tried to apply this code to wrap image and i'm getting some results. At the first, it seems rather correct, but images looks like more of distorted input image than really wrapped. Truth is, if you'll pass mat with zeros instead of real flow to this warp_flow you'll see exactly the same picture, as with real flow data. Which means, that these 2 lines mixes things up. Actually, it is enough just to call 
`res = cv2.remap(img, flow, None, cv2.INTER_CUBIC)`
to wrap image using optical flow, which we could get from LK or RLOF methods in opencv. 
maybe i'm wrong. If so - please anyone explain meaning of those lines.

**Comment by amritanjali123** [comment]
I am also not getting expected output image

**Comment by jhadida** [comment]
Looking at the [documentation](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#gab75ef31ce5cdfb5c44b6da5f3b908ea4) for `remap`, it seems the following should work?

```py
def apply_warp(frame, field):
    """
    Apply (u,v) warp-field to input frame using linear interpolation.
    """
    h, w = frame.shape[:2]
    xmap = field[..., 0] + np.arange(w)
    ymap = field[..., 1] + np.arange(h)[:,None]
    return cv.remap(frame, xmap, ymap, cv.INTER_LINEAR)
```

Obviously the field unit should be in pixels/frame.
