### ISSUE TITLE
how to fixed error "OpenCV is not ready"

### ISSUE THREAD

**Issue by morteza2m** [opencv/opencv#11067]
Hi,I developed the app with opencv in Android Studio, now please help me fix this error on installing app in Android:
"OpenCV is not ready
Installation is in progress. wait or exit?"

**Comment by huangpeiyan** [comment]
I found even though I have installed the OpenCV manager, it's still unuseful.

**Comment by J-free** [comment]
I think you need to add the permission to your app in setting in your android device, for example if you will use camera, you should turn on the permission for using camera
