### ISSUE TITLE
Failed to build if CMAKE_SYSTEM_NAME is Generic

### ISSUE THREAD

**Issue by lordnn** [opencv/opencv#11079]
In case of building for non windows platform common.cc from protobuf library expected HAVE_PTHREAD to be defined. But CMakeLists.txt from OpenCV root looks for pthread.h only if UNIX variable is set. But UNIX is not set for Generic platform.

##### System information (version)
- OpenCV => 3.4.1
- CMake => 3.10.2

**Comment by alalek** [comment]
What is "Generic" platform?

**Comment by lordnn** [comment]
Did you try google or CMake manual before the question?

**Comment by lordnn** [comment]
I see the difference in logic of setting HAVE_PTHREAD macro and its using.
