### ISSUE TITLE
where is the jni wrapper

### ISSUE THREAD

**Issue by eugenelyj** [opencv/opencv#11086]
As well known, porting c/c++ library to android need two step, cross compile to achieve shared/static library and then write jni wrapper, which allow us to call c/c++ function with java code.

However, i could not find the jni code and native java function declaration in this repository, expect a little about mat in module/java/generator and also the python script gen_java.py.

So where is the jni wrapper code? is it generated by gen_java.py and then directly link to library ?

**Comment by berak** [comment]
[answered here](http://answers.opencv.org/question/186862/where-is-the-jni-wrapper/)

**Comment by alalek** [comment]
There is build target to generate OpenCV JNI/Java API code: "gen_opencv_java_source" (you need properly configured "build directory"). Hand-written code for some modules exists in "misc/java" sub-directories (example, [highgui](https://github.com/opencv/opencv/tree/3.4.1/modules/highgui/misc/java))
