### ISSUE TITLE
Any plan to upgrade OpenCV in Android Open Source Project?

### ISSUE THREAD

**Issue by windyuan** [opencv/opencv#11087]
We now have an opensource project libxcam upstreamed to AOSP(Android Open Source Project) (https://android.googlesource.com/platform/external/libxcam/). The problem is that libxcam depends on AOSP's feature-detection and optical-flow.  and the generic OpenCV version in AOSP is very antiquated (1.1, where does this version come from?). The link is https://android.googlesource.com/platform/external/opencv/. This version doesn't support multi-thread and blocked libxcam's performance tuning.

Is there any plan to upgrade the antiquated version to latest OpenCV or 3.0+? I see there's OpenCV binary for Android build (https://opencv.org/platforms/android/).  but why not support generic build in AOSP?

##### System information (version)
- OpenCV => 1.1
- Operating System / Platform => Andorid
- Compiler => Android build

##### Detailed description
When to upgrade OpenCV in AOSP

**Comment by alalek** [comment]
Perhaps this is not the right repository for this issue. We are not involved in AOSP development/maintaining.

BTW, OpenCV 1.1 supports C API, but OpenCV 2.4.x/3.x - doesn't. This is very critical for pure "C" libraries.
