### ISSUE TITLE
ImportError: libImath-2_2.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thyeun** [opencv/opencv#11090]
OS : Arch Linux 2018.2.18
Opencv : 3.4.0

i'm getting this error

```
Traceback (most recent call last):
  File "/home/thyeun/Projects/Opencv/RTDS/RTDS.py", line 7, in <module>
    import cv2
ImportError: libImath-2_2.so.12: cannot open shared object file: No such file or directory 
```

i got the files 

```
/usr/lib/libImath-2_2.so.23
/usr/lib/libImath-2_2.so.23.0.0
 ```

but opencv only looking for ```libImath-2_2.so.12```, so how do i change it to make opencv work again?

**Comment by alalek** [comment]
This is a build configuration issue and can't be fixed in OpenCV directly.
You need to rebuild OpenCV again (from clean build directory because dependencies are changed/updated).

**Comment by thyeun** [comment]
@alalek ok, thanks!!! i still hope that it can have an alternative way!!! =.=
