### ISSUE TITLE
opencv  -- import cv2 --- SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by doaa90** [opencv/opencv#11097]
Hello every one .. 
I use Win10 64 bit,  Python 3.6 64 bit, pycharm
I download OpenCV using pip and everything is good and the version is 3.4.0.12.
 but when I import it, it shows me this error : 
import cv2
         ^
SyntaxError: invalid syntax

I try a lot to solve this problem but no way.
I hope someone can help me

**Comment by nithinbharadwaj** [comment]
Hi,
I am receiving the same error. I did a clean installation of OpenCV 3.4 on Raspberry Pi 3. After the installation, I went into the Python3 virtualenv and checked for OpenCV installation by doing, "import CV2" and then a "cv2.__version__". It worked, when I was inside the OpenCV build folder. Now, I came out of it and am in the home directory, and I get a syntax error for "Import cv2". Please help.

**Comment by alalek** [comment]
> using pip

We don't package any 'pip' packages - this is out of scope of this repository.
Use proper resources to fill issues/questions.

**Comment by superbelll** [comment]
> Hi,
> I am receiving the same error. I did a clean installation of OpenCV 3.4 on Raspberry Pi 3. After the installation, I went into the Python3 virtualenv and checked for OpenCV installation by doing, "import CV2" and then a "cv2.**version**". It worked when I was inside the OpenCV build folder. Now, I came out of it and am in the home directory, and I get a syntax error for "Import cv2". Please help.
> 
> ![image](https://user-images.githubusercontent.com/31043384/39838386-44e42d2e-53a7-11e8-81ca-0ae93a325f8c.png)

try this
>>import cv2 
>>print(cv2.__version__)

**Comment by joe5644** [comment]
? any solution

**Comment by anafarhangi54-dot** [comment]
این ورژن رو ریستارت کنید ،احتمالا بعدش درست بشه ،خودم هم این مشکل رو تجربه کردم به اینکه با حرف بزرگ نوشتید یا کوچیک هم دقت کنید

**Comment by anafarhangi54-dot** [comment]
<img width="958" height="539" alt="Image" src="https://github.com/user-attachments/assets/d283c192-d327-4341-b902-80add3ac083c" />
این روش درسته
