### ISSUE TITLE
cpp:4044: error: (-215)

### ISSUE THREAD

**Issue by MuhammedBuyukkinaci** [opencv/opencv#11106]
I have a problem while resizing. Opencv isn't resizing the images whose dimensions are like this:(800,800). However, if a photo is in a format of (800,800,3), it is resizing without problem.  This is the whole problem description:

C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

The code that I wrote is below:

```
        path = TRAIN_DIR + '\\' + img
        img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
```

Python: 3.6
Opencv: 3.4.0.12
OS: Windows 10 home

**Comment by alalek** [comment]
> I have a problem while resizing

Warning says that you pass empty source image into resize, so you have problem with `imread()`.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by khan958** [comment]
@alalek  Have your solve this issue ?

**Comment by MayankShahria** [comment]
have you found the solution
