### ISSUE TITLE
example_cmake does not work on Windows

### ISSUE THREAD

**Issue by sobkulir** [opencv/opencv#11109]
## System information (version)
- OpenCV => 3.4.1
- CMake => 3.8
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

## Detailed description

Hello, I tried to set up an OpenCV project with CMake. I followed the sample source code found here: [opencv/samples/cpp/example_cmake/](https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake).

The file `CMakeLists.txt` contains this line for including OpenCv: `find_package(OpenCV REQUIRED)`
However, standard installation puts _cmake module files_ to folder `opencv\build\x64\vc15\lib`, but suggests to set environment variable `OPENCV_DIR` to path `opencv\build\x64\vc15`. This means that `find_package` will not look for the _cmake module files_ in the `lib` subdirectory of  `OPENCV_DIR` as described in the [reference page of find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html).

I fixed this by providing **HINTS** to the `find_package` command:
`find_package(OpenCV REQUIRED HINTS $ENV{OpenCV_DIR}/lib)`

Please make some changes so that other people won't have to go through the same.

## Steps to reproduce

Install OpenCv 3.4.1 on Windows using the "Win Pack". Try running the [opencv/samples/cpp/example_cmake/](https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake) example.

**Comment by LaurentBerger** [comment]
give only path to opencv. You don't need to give path to a lib : cmake will do the job
