### ISSUE TITLE
How do I compile cascade.xml into  C++ program to hide the XML file?

### ISSUE THREAD

**Issue by hipitt** [opencv/opencv#11111]
#### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => windows
- Compiler => vs2015

#### Detailed description

The opencv_traincascade trains and outputs XML files, and the C++ program needs to load the XML file from the outside (read the file). How do I compile this XML file into  C++ program to hide the XML file?

#### Steps to reproduce

Find a solution.
No step

**Comment by hipitt** [comment]
@alalek Is that ok?

**Comment by alalek** [comment]
This tracker is for issues and bugs that needs fix in OpenCV. Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

OpenCV is able to load data from "memory" - check `FileStorage::MEMORY` flag.
"How to pack/compile file into C++ buffer" - refer to StackOverflow - there are a lot of solutions, select one for your build scripts/environment.
