### ISSUE TITLE
Reading Mean Binary Proto in OpenCV 

### ISSUE THREAD

**Issue by ZeroCool11000** [opencv/opencv#11121]
##### System information (version)

- OpenCV => : 3.4.1
- Operating System / Platform =>Windows 8 / Visual Studio 2015 
- Compiler => Visual Studio 2015

##### Detailed description

I am trying to read mean binary protobuf files for getting the mean matrix and mean vector, i compiled opencv 3.4.1 and tried to rebuild reading mean binary proto like in https://stackoverflow.com/questions/42239431/how-to-read-mean-file-proto-into-opencv-mat-in-order-to-subtract-image-from-me but after it i am getting following linker errors : 

>------ Build started: Project: DNN_Image_Classificator_OpenCV, Configuration: Release (READ_PROTO_FROM_BIN_FILE) x64 ------
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (__imp_??0CheckOpMessageBuilder@base@google@@QEAA@PEBD@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (__imp_??1CheckOpMessageBuilder@base@google@@QEAA@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl google::base::CheckOpMessageBuilder::ForVar2(void)" (__imp_?ForVar2@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::base::CheckOpMessageBuilder::NewString(void)" (__imp_?NewString@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z) referenced in function "class cv::Mat __cdecl caffe::DecodeDatumToCVMat(class caffe::Datum const &,bool)" (?DecodeDatumToCVMat@caffe@@YA?AVMat@cv@@AEBVDatum@1@_N@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ) referenced in function "class cv::Mat __cdecl caffe::DecodeDatumToCVMat(class caffe::Datum const &,bool)" (?DecodeDatumToCVMat@caffe@@YA?AVMat@cv@@AEBVDatum@1@_N@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "void __cdecl caffe::CVMatToDatum(class cv::Mat const &,class caffe::Datum *)" (?CVMatToDatum@caffe@@YAXAEBVMat@cv@@PEAVDatum@1@@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z) referenced in function "void __cdecl caffe::CVMatToDatum(class cv::Mat const &,class caffe::Datum *)" (?CVMatToDatum@caffe@@YAXAEBVMat@cv@@PEAVDatum@1@@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int,struct google::CheckOpString const &)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDHAEBUCheckOpString@1@@Z) referenced in function "bool __cdecl caffe::ReadProtoFromBinaryFile(char const *,class google::protobuf::Message *)" (?ReadProtoFromBinaryFile@caffe@@YA_NPEBDPEAVMessage@protobuf@google@@@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ) referenced in function "void __cdecl caffe::CVMatToDatum(class cv::Mat const &,class caffe::Datum *)" (?CVMatToDatum@caffe@@YAXAEBVMat@cv@@PEAVDatum@1@@Z)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
1>DNN_Loader_OpenCV_Caffe.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>D:\Build\DNN_Image_Classificator_OpenCV\Release (READ_PROTO_FROM_BIN_FILE)\DNN_Image_Classificator_OpenCV.exe : fatal error LNK1120: 12 unresolved externals

Are there any functions to do this or muss i do this by my own ?

Best Regards

**Comment by alalek** [comment]
> DNN_Loader_OpenCV_Caffe

This is not OpenCV code, so we can't fix this.

Take a look on existed OpenCV DNN samples.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by dkurt** [comment]
@ZeroCool11000, take a look at http://answers.opencv.org/question/178680/how-to-use-meanbinaryproto-with-blobfromimages/.
