### ISSUE TITLE
Assembler messages error

### ISSUE THREAD

**Issue by daoluan** [opencv/opencv#11120]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => CentOS release 6.8 (Final)
- Compiler => g++ (GCC) 6.3.0 (**reinstalled gcc**)

##### Detailed description
make error:
```
[  0%] Built target gen-pkgconfig
[  3%] Built target libtiff
[ 12%] Built target libwebp
[ 14%] Built target libjasper
[ 16%] Built target libpng
[ 21%] Built target IlmImf
[ 26%] Built target libprotobuf
[ 27%] Built target ittnotify
[ 27%] Built target opencv_core_pch_dephelp
[ 27%] Built target pch_Generate_opencv_core
[ 27%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/convert.avx2.cpp.o
/tmp/cclHoR4a.s: Assembler messages:
/tmp/cclHoR4a.s:11: Error: suffix or operands invalid for `vbroadcastss'
/tmp/cclHoR4a.s:12: Error: suffix or operands invalid for `vbroadcastss'
/tmp/cclHoR4a.s:24: Error: no such instruction: `vpermq $216,(%rcx),%ymm2'
/tmp/cclHoR4a.s:27: Error: suffix or operands invalid for `vpunpcklwd'
/tmp/cclHoR4a.s:28: Error: suffix or operands invalid for `vpunpckhwd'
/tmp/cclHoR4a.s:29: Error: suffix or operands invalid for `vpsrad'
/tmp/cclHoR4a.s:32: Error: suffix or operands invalid for `vpsrad'
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/nvert.avx2.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2
```

##### Steps to reproduce
mkdir build && cd build && cmake .. && make

**Comment by alalek** [comment]
> CentOS release 6.8
> g++ (GCC) 6.3.0

Default CentOS 6.8 GCC version is 4.7. How did you install GCC 6.3? Are you sure that you didn't have mess with headers / tools?

Please provide Dockerfile with environment setup to have reproducible results.

**Comment by daoluan** [comment]
I reinstall gcc with new version for some business.

**Comment by kinchungwong** [comment]
The following suggestions come from completely unrelated projects, but the main advice might still apply. Check the GCC build flags.

https://github.com/Theano/Theano/issues/3780#issuecomment-164843114

https://stackoverflow.com/questions/15576817/what-is-the-proper-architecture-specific-options-m-for-sandy-bridge-based-pen

Pay attention to three kinds of GCC flags:

 * ```-march*```
 * ```-mtune*```
 * ```-mno-*``` , which can cause some instructions to be rejected, ***even if*** ```-march``` specifies a more advanced instruction set (technically a superset of those instructions being rejected).

**Comment by sealinger** [comment]
Your version of binutils is too old to support AVX/AVX2 instructions, which have been detected as available on your processor. You need binutils 2.22 or newer for AVX support.

**Comment by AndreiCostinescu** [comment]
Running `ld -v` on my ubuntu 14.04 with compiler gcc 8.1 gives me: 
GNU ld (GNU Binutils for Ubuntu) 2.24

But still these are the error messages I receive:
/tmp/cc6LkQaZ.s: Assembler messages:
/tmp/cc6LkQaZ.s:143: Error: invalid register operand for `vbroadcastss'
/tmp/cc6LkQaZ.s:144: Error: invalid register operand for `vbroadcastss'
/tmp/cc6LkQaZ.s:145: Error: invalid register operand for `vbroadcastss'
/tmp/cc6LkQaZ.s:150: Error: invalid register operand for `vbroadcastss'
/tmp/cc6LkQaZ.s:152: Error: invalid register operand for `vbroadcastss'
/tmp/cc6LkQaZ.s:163: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:166: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:167: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:168: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:170: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:171: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:172: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:179: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:184: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:185: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:186: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:187: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:188: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:189: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:190: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:191: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:192: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:193: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:194: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:195: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:196: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:197: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:198: Error: invalid register operand for `vfmadd231ps'
/tmp/cc6LkQaZ.s:202: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:203: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:207: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:208: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:210: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:212: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:216: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:235: Error: invalid register operand for `vmulps'
/tmp/cc6LkQaZ.s:239: Error: invalid register operand for `vxorps'
/tmp/cc6LkQaZ.s:240: Error: invalid register operand for `vandnps'
/tmp/cc6LkQaZ.s:301: Error: no such instruction: `vextractf32x8 $0x1,%zmm0,%ymm0'
/tmp/cc6LkQaZ.s:334: Error: no such instruction: `vextractf32x8 $0x1,%zmm0,%ymm0'
/tmp/cc6LkQaZ.s:368: Error: no such instruction: `vextractf32x8 $0x1,%zmm1,%ymm1'
/tmp/cc6LkQaZ.s:593: Error: invalid register operand for `vxorps'
/tmp/cc6LkQaZ.s:632: Error: no such instruction: `vextractf32x8 $0x1,%zmm1,%ymm2'
/tmp/cc6LkQaZ.s:635: Error: no such instruction: `vextractf32x8 $0x1,%zmm24,%ymm25'
/tmp/cc6LkQaZ.s:637: Error: no such instruction: `vextractf32x8 $0x1,%zmm26,%ymm1'
/tmp/cc6LkQaZ.s:638: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:639: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:640: Error: no such instruction: `vextractf32x8 $0x1,%zmm21,%ymm26'
/tmp/cc6LkQaZ.s:641: Error: no such instruction: `vextractf32x8 $0x1,%zmm20,%ymm24'
/tmp/cc6LkQaZ.s:642: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:643: Error: no such instruction: `vextractf32x8 $0x1,%zmm22,%ymm21'
/tmp/cc6LkQaZ.s:644: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:645: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:646: Error: no such instruction: `vextractf32x8 $0x1,%zmm5,%ymm21'
/tmp/cc6LkQaZ.s:647: Error: no such instruction: `vextractf32x8 $0x1,%zmm3,%ymm20'
/tmp/cc6LkQaZ.s:648: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:649: Error: no such instruction: `vextractf32x8 $0x1,%zmm4,%ymm5'
/tmp/cc6LkQaZ.s:650: Error: no such instruction: `vextractf32x8 $0x1,%zmm28,%ymm25'
/tmp/cc6LkQaZ.s:651: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:652: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:653: Error: no such instruction: `vextractf32x8 $0x1,%zmm23,%ymm3'
/tmp/cc6LkQaZ.s:654: Error: no such instruction: `vextractf32x8 $0x1,%zmm31,%ymm4'
/tmp/cc6LkQaZ.s:656: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:658: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:659: Error: invalid register operand for `vaddps'
/tmp/cc6LkQaZ.s:866: Error: invalid register operand for `vmovaps'
/tmp/cc6LkQaZ.s:867: Error: invalid register operand for `vfmadd231ps'
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o] Error 1
make[1]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

What is the problem?

**Comment by xhzzhang** [comment]
OpenCV => 3.4.3
Operating System / Platform => Ubuntu 14.04 64bit
Compiler => g++ (GCC) 5.4.0

I got same issue? Is anybody have fix it?

**Comment by alalek** [comment]
Mentioned system configuration doesn't support AVX properly. We can't fix that from OpenCV side (install newer "binutils" on your systems as suggested).

Workaround is to [disable AVX2 in OpenCV](https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options):
```
cmake -DCPU_BASELINE=SSE4_2 -DCPU_DISPATCH= ...
```
