### ISSUE TITLE
dnn, python3 tf1.5 cv3, object_detection.py error

### ISSUE THREAD

**Issue by zkl99999** [opencv/opencv#11128]
https://github.com/opencv/opencv/blob/9fd32ca5ac25ff26f260c059c498b347c044ae78/samples/dnn/object_detection.py#L152
    if net.getLayer(0).outputNameToIndex('im_info') != -1:  # Faster-RCNN or R-FCN
AttributeError: 'cv2.dnn_Layer' object has no attribute 'outputNameToIndex'

**Comment by dkurt** [comment]
@zkl99999, you need to update your OpenCV because `outputNameToIndex` wraps for python only since https://github.com/opencv/opencv/pull/10979 .
