### ISSUE TITLE
cv2.normalize can't work without the 'dst' parameter

### ISSUE THREAD

**Issue by screamff** [opencv/opencv#11127]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform =>windows(ipython)
- Compiler => 

##### Detailed description
next function
```
cv2.normalize(src[, dst[, alpha[, beta[, norm_type[, dtype[, mask]]]]]]) → dst
```
It required me  to specify a dst input parameter,but in most functions,we do not need to do that.

**Comment by gaurav3210** [comment]
Assigned this issue to me

**Comment by alalek** [comment]
Use parameters names and skip 'dst' instead.
