### ISSUE TITLE
samples/dnn/classification.cpp#L47  ......:core\utility.hpp(869): error C2039: 'type': is not a member of 'cv::ParamType<T>'

### ISSUE THREAD

**Issue by zkl99999** [opencv/opencv#11122]
##### System information (version)

- OpenCV => :3.4.1:
- Operating System / Platform => : Windows 64 Bit:
- Compiler => : Visual Studio 2015:

##### Detailed description
when i run this example:
https://docs.opencv.org/master/d5/de7/tutorial_dnn_googlenet.html
https://github.com/opencv/opencv/blob/9fd32ca5ac25ff26f260c059c498b347c044ae78/samples/dnn/classification.cpp#L47

occor error
```
opencv341\include\opencv2\core\utility.hpp(869): error C2039: 'type': is not a member of 'cv::ParamType<T>'
          with
          [
              T=cv::Scalar
          ]
  \opencv341\include\opencv2\core\utility.hpp(869): note: see declaration of 'cv::ParamType<T>'
          with
          [
              T=cv::Scalar
          ]
  \image_classification_caffe.h(45): note: see reference to function template instantiation 'T cv::CommandLineParser::get<cv::Scalar>(const cv::String &,bool) const' being compiled
          with
          [
              T=cv::Scalar
          ]
\opencv341\include\opencv2\core\utility.hpp(869): error C2065: 'type': undeclared identifier
```

##### Steps to reproduce

`line44	float scale = parser.get<float>("scale");
line45	cv::Scalar mean = parser.get<Scalar>("mean");
line46	bool swapRB = parser.get<bool>("rgb");`

**Comment by dkurt** [comment]
@zkl99999, Looks like you try to use a sample code from newer state of OpenCV without an update of library. It's dated by March, 14 (https://github.com/opencv/opencv/pull/10979).

**Comment by zkl99999** [comment]
yes, classification.cpp  exactly opencv library version,occor bug
but  classification.py, run well, no bug

**Comment by aimhabo** [comment]
@zkl99999 have you solve the .cpp's problem? I face the relative problem. But my error log is 'segmentation fault', and after change header file, it shows 'malloc: memory corruption' with
 '/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f66aca83184]
/usr/lib/nvidia-390/tls/libnvidia-tls.so.390.48(+0x24c0)[0x7f667480e4c0'
