### ISSUE TITLE
vs15 opencv341 classification.cpp，，error 

### ISSUE THREAD

**Issue by zkl99999** [opencv/opencv#11123]
https://github.com/opencv/opencv/blob/9fd32ca5ac25ff26f260c059c498b347c044ae78/samples/dnn/classification.cpp#L47

**x**
core\utility.hpp(869): error C2039: 'type': is not a member of 'cv::ParamType<T>'
template instantiation 'T cv::CommandLineParser::get<cv::Scalar>(const cv::String &,bool) const' being compiled
\opencv2\core\utility.hpp(869): error C2065: 'type': undeclared identifier

**Comment by dkurt** [comment]
see https://github.com/opencv/opencv/issues/11122
