### ISSUE TITLE
iOS signing failed.

### ISSUE THREAD

**Issue by txyugood** [opencv/opencv#11133]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => iOS
- Compiler => Xcode 9.2

##### Detailed description

I have successfully get the opencv2.framework and added it to my project.
When I compiled my project, there was an error.
```.cpp
CodeSign /Users/alex/Library/Developer/Xcode/DerivedData/test-ascuvwruohomopbmkhxslzcvcjfi/Build/Products/Debug-iphonesimulator/test.app/Frameworks/opencv2.framework
    cd /Users/alex/test/test
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/alex/Library/Developer/Xcode/DerivedData/test-ascuvwruohomopbmkhxslzcvcjfi/Build/Products/Debug-iphonesimulator/test.app/Frameworks/opencv2.framework

/Users/alex/Library/Developer/Xcode/DerivedData/test-ascuvwruohomopbmkhxslzcvcjfi/Build/Products/Debug-iphonesimulator/test.app/Frameworks/opencv2.framework: code object is not signed at all
In subcomponent: /Users/alex/Library/Developer/Xcode/DerivedData/test-ascuvwruohomopbmkhxslzcvcjfi/Build/Products/Debug-iphonesimulator/test.app/Frameworks/opencv2.framework/Versions/Current/opencv2
Command /usr/bin/codesign failed with exit code 1
```

**Comment by julianboyce** [comment]
I had the same problem.  What solved it for me was clicked my project target and ensuring that the opencv2.framework was ONLY added to the Linked Frameworks and Libraries and REMOVED from the Embedded Binaries section.

I am also using Xcode 9.2

**Comment by masterchef8** [comment]
I had the same problem : @julianboyce' solution worked perfectly! Just one thing ! The section that Julian mentioned doesn't exists or at least not anymore in Xcode 11. it is now "Link Binary with Librairies" in the Build Phases section.

**Comment by liuxuan30** [comment]
met this issue today with Xcode 11.2.1.  Have to choose not embed, and do clean & rebuild.

**Comment by Ochasovskiy** [comment]
The solution doesn't work for me. It loads but the app crushes every time I'm trying to lunch it.

**Comment by IARI** [comment]
Same Problem - but the XCode Project is generated by Unity3D for us.
It never happened on local builds, but now does happen on a server (where we try to get ci running using fastlane)

**Comment by longnc100500** [comment]
i disabled "embedded and sign" and it work
