### ISSUE TITLE
cv2.resize() with interpolation=cv2.INTER_AREA only works on images with at most 4 channels.

### ISSUE THREAD

**Issue by nimroha** [opencv/opencv#11138]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.04
- Compiler => Python 3.5

##### Detailed description

`cv2.resize()` with `interpolation=cv2.INTER_AREA` only works on images with at most 4 channels.

Other interpolation schemes work OK with ndarrays

I don't see a reason why resize should be limited with area average interpolation.

##### Steps to reproduce

Try to resize an ndarray, get:
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:3881: error: (-215) func != 0 && cn <= 4 in function resize

**Comment by kinchungwong** [comment]
This request might be considered as part of [OE-17: New Filter Engine](https://github.com/opencv/opencv/wiki/OE-17.-New-Filter-Engine). Note that there is no guarantee whether this will be implemented or not.

For your immediate needs, use ```cv::split```. [Documentation here](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga0547c7fed86152d7e9d0096029c8518a). After processing channels individually, use ```cv::merge``` to combine them into a multi-channel result matrix.

If performance is critical, and you wish to process 4 channels on each call to ```cv::resize```, then you might want to use ```cv::mixChannels```. [Documentation here](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga51d768c270a1cdd3497255017c4504be)

**Comment by ebrahimebrahim** [comment]
I am having this issue in 4.5.5.

This should be re-opened.

**Comment by vishwassathish** [comment]
Also facing the same issue in 4.9.0. Seems like the issue occurs when the old_size is not an integer multiple of new_size.
