### ISSUE TITLE
Python Multiprocessing Hangs with OpenCv ARUCO

### ISSUE THREAD

**Issue by tkoch96** [opencv/opencv#11145]
I am using multiprocessing to speed up ARUCO target detection on a raspberry pi.
(Keep in mind I have gotten this working using no multiprocessing.)

Using this code:
``
workers = []
for i in range(num_workers):
workers.append(Worker_Bee(tasks,results,i))

for worker in workers:
    worker.start()  

for i in range(20):
    tasks.put(Image_Processor(vs.read()))
    time.sleep(.5)

``
The Image_Processor looks at the frame vs.read() which is an image. The image processor tries to find targets in the image.
The worker process Image_Processor hangs on the following line:
corners, ids, rejectedImgPoints = aruco.detectMarkers(gray, self.aruco_dict, parameters=self.parameters)
where gray is the image vs.read()
I've check the arguments to aruco.detectMarkers and they seem to be correct (and as I've said before, I've ran this before without multiprocessing fine).
There is no error message, and looking at top, I see the python process spawning but then quickly going to a <defunct> state. The parent process stays.

I've seen similar problems with openCV hanging on cvtColor or resize, but all of their problems are fixed for me (compiling with TBB options and such).

Any advice on how to get this working?

**Comment by tomoaki0705** [comment]
Really, you're asking at a wrong place
If you need a help, please ask to http://answers.opencv.org/questions/
