### ISSUE TITLE
Process Hangs with OpenCV ARUCO using MultiProcessing

### ISSUE THREAD

**Issue by tkoch96** [opencv/opencv#11140]
I am using multiprocessing to speed up ARUCO target detection on a raspberry pi.

I have gotten this working using no multiprocessing. 

Using this code:

**Comment by tkoch96** [comment]
Why did you close this?

**Comment by tkoch96** [comment]
Could you please explain how this is a duplicate?

**Comment by alalek** [comment]
Fresh one similar duplicate: #11115
Main thread of this problem: #5150

**Comment by tkoch96** [comment]
I've been looking at that problem because it is somewhat similar to mine and it is not a duplicate. Their 'problems' are not problems for me. The code they are having problems with runs fine for me.

Also - I am only using this function in a single process at once. I wanted to start there before moving onto multiple processing calling this function.
In #5150 , they use the same function in both the parent and child processes.
