### ISSUE TITLE
cv2.createLBPHFaceRecognizer() missing

### ISSUE THREAD

**Issue by regostar** [opencv/opencv#11148]
##### System information (version)

Traceback (most recent call last):
  File "f.py", line 13, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: 'module' object has no attribute 'face'

- OpenCV => :grey_question:
- Operating System / Platform => :+1: deepin:
- Compiler => :grey_question:

##### Detailed description

Traceback (most recent call last):
  File "f.py", line 13, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: 'module' object has no attribute 'face'

**Comment by regostar** [comment]
cv2.createLBPHFaceRecognizer()  
or 
cv2.face.LBPHFaceRecognizer_create()
both are not working

**Comment by berak** [comment]
@regostar , whatever you installed. it probably does not have it.

this is not a library bug (and the wrong tracker anyway) so please kindly close this issue, and ask again on
http://answers.opencv.org/ , where we can help you better with your question.

**Comment by regostar** [comment]
Ohk
