### ISSUE TITLE
imdecode(): feature request

### ISSUE THREAD

**Issue by skramm** [opencv/opencv#11152]
Currently, it is not possible to get the size of the memory chunk used by cv::imdecode().
```
std::vector<BYTE> buff( /* very large */ )
cv::Mat m = cv::imdecode( buff, flags ); // <- how much of buff was used?
```
This is a missing feature in the following situation:
Consider a network data transmission that needs to transmit several images at once (say, using boost::asio for example). We have a reception buffer stuffed with chunks of binary data, that we need to decode as images.
If we had a way to get the size of decode image, it would be possible to do:

```
size_t nbBytes; 
std::vector<BYTE> rx_buff( /* very large */ );
...       // receive binary data, store it in rx_buff, and store in nbBytes the number of bytes received
cv::Mat m1 = cv::imdecode( rx_buff, flags ); // first image
size_t size_im1 = ???
std::vector<BYTE> buff2( /* large enough */ );
std::memcpy( buff2.data(), rx_buff.data()+size_im1, nbBytes - size_im1 );
cv::Mat m2 = cv::imdecode( buff2, flags ); // second image
```
Does that sound like something that can be implemented? Maybe through a third optional argument, a pointer on some data structure, so it won't break the API ?

[reference](https://docs.opencv.org/3.4.1/d4/da8/group__imgcodecs.html#ga26a67788faa58ade337f8d28ba0eb19e):(3.4.1)

**Comment by alalek** [comment]
`imdecode()` `buff` must contain all data, which is necessary to decode image at once.
OpenCV is computer vision library, not Media I/O library - so we would like to avoid very specific features.
Perhaps you should handle size of image data on application/network level.

**Comment by kinchungwong** [comment]
@skramm Easiest solution is to transmit the size of each image as a 4-byte or 8-byte value in the beginning, before the compressed image data. Alternatively, consider using Protobuf.

While JPEG and PNG contains definite encoding of end-of-file (JPEG via "FF D9", remember not to be fooled by thumbnail; PNG via IEND chunk, BMP via precalculated file size based on header and image dimensions), some formats such as TIFF allows arbitrary data ("wasteland") after the end of pixel data.

**Comment by skramm** [comment]
@alalek @kinchungwong Thanks for your comments. True, one solution could be to first send size of buffer as established by `cv::imencode()`. This appears to be the best solution, compared to sending raw size of image (as compression will greatly vary between images), or searching for EOF marker, as suggested by @kinchungwong .
