### ISSUE TITLE
(Android) update from 3.4.0 to 3.4.1 causes a NDK issue only on Linux

### ISSUE THREAD

**Issue by hannesa2** [opencv/opencv#11150]
- OpenCV => 3.4.1
- Operating System / Platform =>  Ubuntu 16.04
- Compiler => Android NDK **17.0.4640043-beta1**

##### Detailed description

I have a Android app with OpenCV, after update from 3.4.0 to 3.4.1 I can run on macOS
`./gradlew clean build`  --> all is fine 👍 

============================

but on Ubuntu 16.04 (my CI server) I run first into 
> ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].

👎 

ok I remove `armeabi` from here
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3314607/37873188-483e9198-3017-11e8-910c-7d7d4af59602.png">

Then I run into 
> Execution failed for task ':openCVLibrary:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command '/opt/android-sdk-linux/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/bin/mips64el-linux-android-strip''

👎 

##### Steps to reproduce

`./gradlew clean build` on Ubuntu 16.04

##### Question

Is this known issue ?
Does someone understand what's wrong here or has an idea how to get rid of it ?

**Comment by hannesa2** [comment]
switch to `android-ndk-r16b`solved it

**Comment by alalek** [comment]
`armeabi` (not `armeabi-v7a`) is legacy configuration. Looks like it is dropped with fresh Android NDK 17.
Support for ARM5 (armeabi), MIPS, and MIPS64 are deprecated since 16b.
