### ISSUE TITLE
Running custom trained TensorFlow model in OpenCV

### ISSUE THREAD

**Issue by emusk775** [opencv/opencv#11163]
I want to run custom trained TensorFlow models in OpenCV. I am able to run pre-trained models, as demonstrated [here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) and also on `mobilenet_ssd_python.py`. 

When I tried to run custom trained models, I got the following error:

`
[libprotobuf ERROR /home/the_name/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 1:6: Message type "tensorflow.GraphDef" has no field named "item".
OpenCV(3.4.1) Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: /home/the_name/testing_zone/object-detection.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file /home/the_name/opencv/modules/dnn/src/tensorflow/tf_io.cpp, line 54
Traceback (most recent call last):
  File "tf_trial.py", line 3, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('/home/the_name/testing_zone/frozen_inference_graph3.pb', '/home/the_name/testing_zone/object-detection.pbtxt')
cv2.error: OpenCV(3.4.1) /home/the_name/opencv/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: /home/the_name/testing_zone/object-detection.pbtxt in function ReadTFNetParamsFromTextFileOrDie
`

I then followed the troubleshooting steps suggested in the above link, and used [optimize_for_inference.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py) and [tf_text_graph_ssd.py
](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py). On the running the files with the new files, the following error came up:

`[ INFO:0] Initialize OpenCL runtime...
OpenCV(3.4.1) Error: Assertion failed (int(numPriors * _numClasses) == inputs[1][1]) in getMemoryShapes, file /home/the_name/opencv/modules/dnn/src/layers/detection_output_layer.cpp, line 209
Traceback (most recent call last):
  File "tf_trial.py", line 10, in <module>
    cvOut = cvNet.forward()
cv2.error: OpenCV(3.4.1) /home/the_name/opencv/modules/dnn/src/layers/detection_output_layer.cpp:209: error: (-215) int(numPriors * _numClasses) == inputs[1][1] in function getMemoryShapes
`
Kindly, help me out. After this runs on the python code, I plan to write a C++ program to do the same.

I am using OpenCV 3.4.1 on Ubuntu 17.10 on a 64-bit system. It has an Intel® Core™ i3 CPU M 370 @ 2.40GHz × 4 processor with 6GB of RAM.

**Comment by dkurt** [comment]
@emusk775, Only reproducible issues could be solved. Please add a reference to model.

**Comment by emusk775** [comment]
I found out my mistake and resolved the problem. I had entered wrong num_classes parameter while running the tf_text_graph_ssd.py file.
Thanks for the support though.
