### ISSUE TITLE
Segmentation fault when save UMat by cv::imwrite

### ISSUE THREAD

**Issue by haydenhsieh** [opencv/opencv#11165]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04.4 LTS(4.4.0-116-generic)
- Compiler => g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

##### Detailed description

Segmentation fault when save UMat by cv::imwrite.
The `img_vec` is 0 size when argument `_img` is UMat type.
```
    std::vector<Mat> img_vec;
    //Did we get a Mat or a vector of Mats?
    if (_img.isMat())
        img_vec.push_back(_img.getMat());
    else if (_img.isMatVector())
        _img.getMatVector(img_vec);

    return imwrite_(filename, img_vec, params, false);
```

##### Steps to reproduce

```
Mat img = imread(argv[1]);
UMat umat_img = img.getUMat(ACCESS_RW);
imwrite("output.png", umat_img);
```

**Comment by saskatchewancatch** [comment]
The problem is that that bit of code was ignorant of UMat's and its vectors. I created a PR that addresses this: #11176 . This is a touchy area of image loading and saving and I would appreciate someone's kind review to see if the proposed solution is fine. :)
