### ISSUE TITLE
Build failed: arithm_core.hpp: No such file or directory

### ISSUE THREAD

**Issue by francoisbecker** [opencv/opencv#11172]
```
[ 31%] Generating precomp.hpp.gch/opencv_core_DEBUG.gch
/[…]/modules/core/precomp.hpp:89:27: fatal error: arithm_core.hpp: No such file or directory
compilation terminated.
modules/core/CmakeFiles/pch_Generate_opencv_core.dir/build.make:62: recipe for target 'modules/core/precomp.hpp.gch/opencv_core_DEBUG.ghc' failed
```

##### System information (version)
- OpenCV => 3.4.1-dev
- Operating System / Platform => Ubuntu 16.04, amd64
- gcc 5.4.0

##### Detailed description
Commit 9e0dee12598273c974c482643b1bb9436e879d7a and later exhibit this issue.
Commit 6e13ffe162b1e6ec79bcbea0dd609f33aef23051 and earlier build fine.

**Comment by alalek** [comment]
Current workaround is to disable precompiled headers:
```
cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...
```

I will take a look on this.

**Comment by francoisbecker** [comment]
(in the meantime, workaround by disabling the precompiled headers: confirmed working)

**Comment by baqwas** [comment]
Same issue on Raspberry Pi Zero W and Raspberry Pi B; running workaround on both, will take a "few" hours! Thanks for the quick response. Rgds.

**Comment by francoisbecker** [comment]
@baqwas actually the build issue has been fixed, no need for the workaround anymore on the git tip.

**Comment by baqwas** [comment]
@francoisbecker My apologies for the erroneous/redundant comment. I did a clone earlier and encountered the issue. Perhaps my GitHub inexperience is showing - still learning. The workaround, however, is working on two the RPi boards - **make** at 20% right now as I write. :( - my problem, I know. Gaining the experience with baby steps is invaluable for me, of course.
