### ISSUE TITLE
Possible leaks in pycvSetMouseCallback, pycvCreateTrackbar, and pycvCreateButton

### ISSUE THREAD

**Issue by dan-masek** [opencv/opencv#11206]
Continuing from #11205 ... I'm reading through `modules/python/src2/cv2.cpp` and another thing struck me. The functions in question ([`pycvSetMouseCallback`](https://github.com/opencv/opencv/blob/3.4.1/modules/python/src2/cv2.cpp#L1572), [`pycvCreateTrackbar`](https://github.com/opencv/opencv/blob/3.4.1/modules/python/src2/cv2.cpp#L1592), and [`pycvCreateButton`](https://github.com/opencv/opencv/blob/3.4.1/modules/python/src2/cv2.cpp#L1633)) follow the same pattern, so I'll use `pycvSetMouseCallback` since it uses the fewest parameters.

The actual call of the C++ API function to set the callback looks like this:

    ERRWRAP2(setMouseCallback(name, OnMouse, Py_BuildValue("OO", on_mouse, param)));

In that statement, we call `Py_BuildValue` which allocates a new `PyObject*` -- now, what happens, when the user calls the function again? Aren't we leaking memory, since we never `DECREF` the previously allocated `PyObject`?

i.e. shouldn't there be something such as the following?

    static PyObject* last_mouse_cb_param = NULL;

    static PyObject *pycvSetMouseCallback(PyObject*, PyObject *args, PyObject *kw)
    {
        // ....
        if (last_mouse_cb_param) {
            Py_DECREF(last_mouse_cb_param);
            last_mouse_cb_param = NULL;
        }
        last_mouse_cb_param = Py_BuildValue("OO", on_mouse, param);
        ERRWRAP2(setMouseCallback(name, OnMouse, last_mouse_cb_param));
        Py_RETURN_NONE;
    }

**Comment by alalek** [comment]
Looks good.

Please put "global" variable into the function itself. No need to keep it in global space.

**Comment by dan-masek** [comment]
@alalek I wrote patches for this and #11205. Should I make new pull requests for those two branches?

**Comment by alalek** [comment]
@dan-masek Yes, please create new Pull request.

**Comment by dan-masek** [comment]
OK. Added oull request #11217 to solve this.
