### ISSUE TITLE
Warpers.hpp compiling errors OpenCV 3.4.1

### ISSUE THREAD

**Issue by raulqf** [opencv/opencv#11209]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04 
- Compiler => GNU MAKE 4.1

##### Detailed description
I am migrating to OpenCV 3.4.1 and compiler throw errors in warpers.hpp from the stitching module. It seems that the WarperCreator inheritance is not working properly in my environment.

_/usr/local/include/opencv2/stitching/warpers.hpp:127:132: error: no matching function for call to ‘makePtr(float&, const float&, const float&)’
     Ptr<detail::RotationWarper> create(float scale) const { return makePtr<detail::CompressedRectilinearPortraitWarper>(scale, a, b); }_

##### Steps to reproduce
Compile a hello world example including opencv core module.

**Comment by pwnorbitals** [comment]
@raulqf Is this still a problem for you on latest releases ?

**Comment by raulqf** [comment]
Yes, it's solved with latest release. Thanks!

**Comment by pwnorbitals** [comment]
Perfect ! This issue can be closed now, then :)
