### ISSUE TITLE
Android Studio CascadeClassifier load issue

### ISSUE THREAD

**Issue by mazend** [opencv/opencv#11238]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Android Studio 3.1.0

##### Detailed description

Hi everyone.
I think I found some issue about `CascadeClassifier`.
Even though `mCascaseFile` points correct existing file
`mJavaDetector.empty()` always return `true`(means loading failed).

```
mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());
if (mJavaDetector.empty()) {
    Log.e(TAG, "Failed to load cascade classifier1");
    mJavaDetector = null;
} else
    Log.i(TAG, "Loaded cascade classifier from " + mCascadeFile.getAbsolutePath());
```

To fix this issue I had to add `mJavaDetector.load(mCascadeFile.getAbsolutePath());` like below.

```
mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());
mJavaDetector.load(mCascadeFile.getAbsolutePath());
if (mJavaDetector.empty()) {
    Log.e(TAG, "Failed to load cascade classifier1");
    mJavaDetector = null;
} else
    Log.i(TAG, "Loaded cascade classifier from " + mCascadeFile.getAbsolutePath());
```

However If I give an empty argument in `CascadeClassifier` like below
The issue isn't fixed.
(Please note that `mJavaDetector.load(mCascadeFile.getAbsolutePath()) `code exist in below code)

```
mJavaDetector = new CascadeClassifier();
mJavaDetector.load(mCascadeFile.getAbsolutePath());
if (mJavaDetector.empty()) {
    Log.e(TAG, "Failed to load cascade classifier1");
    mJavaDetector = null;
} else
    Log.i(TAG, "Loaded cascade classifier from " + mCascadeFile.getAbsolutePath());
```

Could you please look at this issue?

**Comment by alalek** [comment]
Please check that you didn't have mess with OpenCV versions (at least you should remove "OpenCV Manager" from device). OpenCV Java API and OpenCV JNI code must have the same version.
Check `adb logcat` logs.

See also this issue: #7223

**Comment by mazend** [comment]
Thank you for the quick response.

However I don't understand completely what you said.
How can I run my application with out "OpenCV Manager"?
You mean I have to develop with static initialization(https://docs.opencv.org/3.1.0/d5/df8/tutorial_dev_with_OCV_on_Android.html)?

If not I don't understand what you said, sorry.
Could you please tell me in detail about how to check OpenCV Java API version and OpenCV JNI version?
I think I'm developing with OpenCV Java v3.4.1.
In addition OpenCV Manager in Google play store says :
-contains libraries for both OpenCV 2.4.x and 3.x
-support 64-bit platforms(only 3.0)

Was I using OpenCV JNI 3.0?

**Comment by alalek** [comment]
Your OpenCV Java API version is probably 3.4.1.
Question is about OpenCV JNI API version (native code).
Run "adb logcat" in terminal and launch your app. During OpenCV loading, you should see dumped build information. Search for strings like these:
```
-- General configuration for OpenCV 3.4.1-dev =====================================
--   Version control:               3.4.1-228-gb60328c
```

These versions should match to "3.4.1".


> develop with static initialization

Yes. This is preferable way for now. You control your OpenCV version in your APK file.
Do not use OpenCV Manager anymore. There are many issues with versions mess, which is very hard to debug.

**Comment by mazend** [comment]
My OpenCV JNI API version(native code) is 3.0.0.

```
    General configuration for OpenCV 3.0.0 =====================================
      Version control:               3.0.0-6-gc1f114b-dirty
```

So you mean below description that made me confused is deprecated.

`release package is recommended to communicate with OpenCV Manager`
(from https://docs.opencv.org/3.1.0/d5/df8/tutorial_dev_with_OCV_on_Android.html)

Thnak you so much.
I will study about the static initialization.
