### ISSUE TITLE
cv2.waitKey(0) doesn't return any value to take a decision based on the value. 

### ISSUE THREAD

**Issue by NoSkillGuy** [opencv/opencv#11232]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => macOS Sierra 10.12.6

##### Detailed description
Wrote a script to read the image and show it and on any key press destroyAllWindows(). 
**_Issue_**: 
key press is not detected. Even after i press 'q' key, the script doesn't come out of the loop

```python
import cv2
greyscale_image = cv2.imread('my_image.jpg',0)
cv2.imshow('greyscale image', greyscale_image)
while True:
    if cv2.waitKey(0)&0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
```

##### Steps to reproduce

Run the above script in macOS 10.12.6 and keep some random image with name my_image.jpg in the directory where script is being run.

**Comment by alalek** [comment]
Please provide build information about used UI backend:
- [cv::getBuildInformation()](https://docs.opencv.org/3.4.1/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5)
- or https://www.learnopencv.com/get-opencv-build-information-getbuildinformation/
- or run `opencv_version` app with `-v` option

**Comment by NoSkillGuy** [comment]
General configuration for OpenCV 3.4.1 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /tmp/opencv-20180307-19209-1d8dn7a/opencv-3.4.1/opencv_contrib/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2018-03-07T08:15:08Z
    Host:                        Darwin 16.7.0 x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/local/Homebrew/Library/Homebrew/shims/super/gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
      disabled:                  SSE4_1 SSE4_2 AVX AVX2
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (3 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (1 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++11:                       YES
    C++ Compiler:                /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  (ver 9.0.0.9000039)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/local/Homebrew/Library/Homebrew/shims/super/clang
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          /usr/local/lib/libtbb.dylib
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 python3 python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    js world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv dnn_modern freetype hdf java matlab ovis sfm ts viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         YES

  GUI:
    Cocoa:                       YES

  Media I/O:
    ZLib:                        /usr/lib/libz.dylib (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         /usr/local/lib/libpng.dylib (ver 1.6.34)
    TIFF:                        /usr/local/lib/libtiff.dylib (ver 42 / 4.0.9)
    OpenEXR:                     /usr/local/lib/libImath.dylib /usr/local/lib/libIlmImf.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib (ver 2.2.0)

  Video I/O:
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.107.100)
      avformat:                  YES (ver 57.83.100)
      avutil:                    YES (ver 55.78.100)
      swscale:                   YES (ver 4.8.100)
      avresample:                YES (ver 3.7.0)
    AVFoundation:                YES

  Parallel framework:            TBB (ver 2018.0 interface 10002)

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   /tmp/opencv-20180307-19209-1d8dn7a/opencv-3.4.1/build/3rdparty/ippicv/ippicv_mac
    Intel IPP IW:                sources (2017.0.3)
              at:                /tmp/opencv-20180307-19209-1d8dn7a/opencv-3.4.1/build/3rdparty/ippicv/ippiw_mac
    Lapack:                      YES (/System/Library/Frameworks/Accelerate.framework /System/Library/Frameworks/Accelerate.framework)
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (no extra features)
    Include path:                NO
    Link libraries:              -framework OpenCL

  Python 2:
    Interpreter:                 /usr/local/opt/python@2/libexec/bin/python (ver 2.7.14)
    Libraries:                   /usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (ver 2.7.14)
    numpy:                       /usr/local/lib/python2.7/site-packages/numpy/core/include (ver 1.14.1)
    packages path:               lib/python2.7/site-packages

  Python 3:
    Interpreter:                 /usr/local/opt/python/bin/python3 (ver 3.6.4)
    Libraries:                   /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib (ver 3.6.4)
    numpy:                       /usr/local/lib/python3.6/site-packages/numpy/core/include (ver 1.14.1)
    packages path:               lib/python3.6/site-packages

  Python (for build):            /usr/local/opt/python@2/libexec/bin/python

  Java:
    ant:                         NO
    JNI:                         /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include/darwin /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/include
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Install to:                    /usr/local/Cellar/opencv/3.4.1_2
-----------------------------------------------------------------

**Comment by alalek** [comment]
> Cocoa:                       YES

Cocoa is native UI backend for Mac OS X - it is good (not QT or something else).
So it should work.

Common error here is enabled Caps Lock mode ('Q' / 'q' mess) or non-EN layout.
Try to debug this (also press other keys too: for example, `Esc` - 27):
```.diff
-if cv2.waitKey(0)&0xFF == ord('q'):
key = cv2.waitKey(0)
print(key)
if key == ord('q'):
```

**Comment by NoSkillGuy** [comment]
Tried debugging the code with print statements, but no key is getting detected.

```zsh
[~/mysites/2018/openCV]$ python3 testWaitKey.py                            [ruby-2.5.0]
j
d
a
de
^[
;
```

**Comment by alalek** [comment]
You must select (make active) OpenCV window with image. Do not try to type into terminal window.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by andrewlnyland** [comment]
I'm also having this issue, in
macOS Sonoma 14.3
python 3.9 (also tried in 3.12)
opencv 4.9.0
Any workarounds?
