### ISSUE TITLE
NVCC fatal error.

### ISSUE THREAD

**Issue by R1234A** [opencv/opencv#11239]
OS-Ubuntu-16.04
GPU - NVIDIA-GTX 1060(GB)
CUDA -9.0 and CUDnn -7

Installing Opencv 3.1.0 and while "make -j8" I am getting errors about the architecture 

nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:208 (message):
  Error generating
  /root/opencv-3.1.0/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

modules/core/CMakeFiles/opencv_core.dir/build.make:63: recipe for target 'modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o' failed
make[2]: *** [modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o] Error 1
CMakeFiles/Makefile2:2310: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I have to comment the line for architecture and if yes where is that file to comment that line??

Please reply asap.

**Comment by alalek** [comment]
> 3.1.0

This is very old release and it may not support CUDA 9.0 properly (OpenCV 3.1.0 was released before CUDA 9.0) - at least auto-detection doesn't work.

> nvcc fatal : Unsupported gpu architecture 'compute_20'

You should specify CMake `CUDA_ARCH` [options](https://docs.opencv.org/3.4/d6/d15/tutorial_building_tegra_cuda.html).

**Comment by RoboEvangelist** [comment]
How to I specify the CUDA_ARCH? Which file do I modify? Where is that file located?

**Comment by HusterRC** [comment]
sudo apt install gcc-5 g++-5
