### ISSUE TITLE
getOptimalNewCameraMatrix should not change aspect ratio

### ISSUE THREAD

**Issue by nalt** [opencv/opencv#11234]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Ubuntu
- Compiler => gcc

##### Detailed description

getOptimalNewCameraMatrix() ignores the aspect ratio when it creates the optimal matrix. This mainly affects cameras with a wide angle lens and a strong distortion. Many pixel-baed algorithms (SIFT, KLT, etc.) cannot cope with large changes in the aspect ratio.

There should be an option to leave the aspect ratio unchanged.

##### Steps to reproduce

Calibrate a wide-angle camera with strong distortion. Effect is most pronounced with alpha=0.

**Comment by javierBarandiaran** [comment]
When the parameter centerPrincipalPoint is set to true the aspect ratio is not changed.

**Comment by victor1234** [comment]
According to @javierBarandiaran answer, I close issue

**Comment by siilats** [comment]
Hey I just tested it even with centerPrincipalPoint its still streched
