### ISSUE TITLE
The method putText(Mat, String, Point, int, int, Scaler) is undefined for the type Imgproc

### ISSUE THREAD

**Issue by clplaneguy** [opencv/opencv#11241]
OpenCV 3.4.1
Windows 7 64 Bit
Eclipse IDE for Java Developers     Oxygen.3 Release (4.7.3)
 
### The method putText(Mat, String, Point, int, int, Scaler) is undefined for the type Imgproc

I have finally gotten my test snippet script to work.

Now it is broken again. I have upgraded to OpenCV 3.4.1 and Intelli-sense gives the same old error message. It is a generic error message that does not point to the real problem. The script is proven. I do know that . . . It seems that putText is in the OpenCV Native library so, if the Native library in not installed properly this error message pops up. I have installed the Native library in Eclipse, the project and the script.

Anyone have a clue as to what I have not done or done wrong??

PS: This script has run in the past. The execution error does not provide any useful new information

The test script follows:

```
package openCV_341_PACKAGE;

import org.opencv.core.*;
import org.opencv.highgui.HighGui;
import org.opencv.imgproc.Imgproc;

public class Smoothing_Images_Test_Case {

    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        Mat src;
        src = new Mat(400,400,16,Scalar.all(127));
        Imgproc.putText(src ,
                    "This Image" ,
                    new Point( src.cols()/4 , src.rows()/2 ) ,
                    Core.FONT_HERSHEY_COMPLEX ,
                    1 ,
                    new Scalar(255, 255, 255)) ;
        HighGui.imshow( "This Frame", src );
        }
}
```

**Comment by alalek** [comment]
OpenCV Java `putText()` [tests](https://github.com/opencv/opencv/blob/3.4.1/modules/imgproc/misc/java/test/ImgprocTest.java#L2156-L2197) works well.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
