### ISSUE TITLE
Conflict between the libraries of OpenCV and LEGO EV3 at NATIVE_LIBRARY_NAME

### ISSUE THREAD

**Issue by clplaneguy** [opencv/opencv#11246]
OpenCV 3.4.1
Windows 7 64 bit
Eclipse IDE for Java Developers   Oxygen.3 Release (4.7.3)

 SOLVED
I am trying to use OpenCV on the LEGO EV3. If my PROJECT FILE includes the LEGO library (LeJOS EV3 EV3 Runtime) there is a conflict with the OpenCV Native library, even if a script does not import the LEGO Library.

`import lejos.hardware.*;`

Line 10 is

`System.loadLibrary(Core.NATIVE_LIBRARY_NAME);`

and the associated error is:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java2411 in java.library.path
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.loadLibrary0(Unknown Source)
    at java.lang.System.loadLibrary(Unknown Source)
    at openCV_341_PACKAGE.Smoothing_Images_Test_Case.main(Smoothing_Images_Test_Case.java:10)
```

**My sample Java OpenCV script is valid. The problem is the conflict between the two libraries**

![image](https://user-images.githubusercontent.com/23004042/38387762-86d249ca-38de-11e8-84a3-b88ae3a46a05.png)

Reference:
http://answers.opencv.org/question/188732/opencv-341-breaks-imgprocputtextmat-string-point-int-int-scaler/

**Comment by alalek** [comment]
This is configuration problem (different versions of OpenCV in single Java project).
No chance to fix this in OpenCV (except whole library massive renaming including Java package names, C++ symbols, etc - won't fix).

**Comment by clplaneguy** [comment]
**SOLVED**

leJOS 0.9.1 implements OpenCV 2.4.11 The Eclipse project must also use OpenCV 2.4.11 or this conflict will occur.
