### ISSUE TITLE
cv::cvtColor() does't work in ROS call-back function.

### ISSUE THREAD

**Issue by ZhengPan2014** [opencv/opencv#11266]
detail of call-back function is as follow.  Once I uncommeted `cv::cvtColor()`, program was stuck there, any ideal?
```
void imageGraper::callBack(const sensor_msgs::ImageConstPtr image0, 
                           const sensor_msgs::ImageConstPtr image1, 
                           const sensor_msgs::ImageConstPtr image2)
{
    cv_bridge::CvImagePtr cv_ptr;
    cv::Mat GrayImage, dst;
    cv_ptr = cv_bridge::toCvCopy(image0, sensor_msgs::image_encodings::BGR8);
    if(cv_ptr)
    {
        dst = cv_ptr->image;
        //cv::cvtColor(dst, GrayImage, CV_BGR2GRAY);
        cv::imshow("SLAM", dst);
        cv::waitKey(1);
    }else{
    }
}
```

**Comment by csukuangfj** [comment]
Check that whether `dst` is empty or not before calling `cv::cvtColor`.

If the problem remains unsovled, please paste your debug information here.

**Comment by ZhengPan2014** [comment]
thank you for your reply. For better illustrating my problem, I revise my program as follow:

`cv_ptr = cv_bridge::toCvCopy(image0, sensor_msgs::image_encodings::BGR8);`
 `       if(cv_ptr)`
  `      {`
   `         dst = cv_ptr->image;`
    `        if(!dst.empty()){`
     `           std::cout<<"dst not empty"<<std::endl<<std::flush;`
      `          cv::cvtColor(dst, GrayImage, CV_BGR2GRAY);`
       `         std::cout<<"convert to gray good!"<<std::endl<<std::flush;`
        `        cv::imshow("SLAM", GrayImage);`
         `       cv::waitKey(1);`
          `  }else{`
           `     std::cout<<"dst empty!"<<std::endl<<std::flush;`
            `} `
      `}else{`
`}`
    
compiling is good, but when I run the program, it was stuck at line cv::cvtColor(). the snapshot of the output is as follow  :
![image](https://user-images.githubusercontent.com/15884732/38464025-2c42f8b2-3b39-11e8-9fc3-33cef29621b5.png)
and "ctrl+c" make no sense to kill the program in terminal.

**Comment by csukuangfj** [comment]
One more thing you may perform:
  1. compile your program with debug information, i.e., CMAKE_BUILD_TYPE=Debug
  2. Use gdb to step into `cv::cvtColor` (you have to compile OpenCV with debug information)
  3. Check what happens inside `cv::cvtColor`

**Comment by ZhengPan2014** [comment]
It's a problem of OpenCV environment.
