### ISSUE TITLE
OpenCV 3.4.1 fails building with Intel Compiler 2018 on Windows

### ISSUE THREAD

**Issue by emmenlau** [opencv/opencv#11263]
##### System information (version)

- OpenCV = 3.4.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Intel Compiler XE 2018 with Visual Studio Community Edition 2015

##### Detailed description

I build OpenCV with the Intel Compiler XE 2018 and Visual Studio 2015 on Windows 7 64 bit. I set the CPU_BASELINE to SSE3. The compile goes on for a while, but eventually fails with a linker error about two unresolved symbols `_mm256_cvtps_ph` and `_mm256_cvtph_ps`:
```
[...]
Creating library ..\..\lib\opencv_core341d.lib and object ..\..\lib\opencv_core341d.exp
convert.fp16.cpp.obj : error LNK2019: unresolved external symbol _mm256_cvtps_ph referenced in function "void __cdecl cv::opt_FP16::cvtScaleHalf_SIMD32f16f(float const *,unsigned __int64,short *,unsigned __int64,class cv::Size_<int>)" (?cvtScaleHalf_SIMD32f16f@opt_FP16@cv@@YAXPEBM_KPEAF1V?$Size_@H@2@@Z)
convert.fp16.cpp.obj : error LNK2019: unresolved external symbol _mm256_cvtph_ps referenced in function "void __cdecl cv::opt_FP16::cvtScaleHalf_SIMD16f32f(short const *,unsigned __int64,float *,unsigned __int64,class cv::Size_<int>)" (?cvtScaleHalf_SIMD16f32f@opt_FP16@cv@@YAXPEBF_KPEAM1V?$Size_@H@2@@Z)
..\..\bin\opencv_core341d.dll : fatal error LNK1120: 2 unresolved externals
jom: D:\tmp\Debug\Shared\opencv-3.4.1-x64\modules\core\CMakeFiles\opencv_core.dir\build.make [bin\opencv_core341d.dll] Error 2
jom: D:\tmp\Debug\Shared\opencv-3.4.1-x64\CMakeFiles\Makefile2 [modules\core\CMakeFiles\opencv_core.dir\all] Error 2
```

##### Steps to reproduce

Here are my cmake instructions:
```
cmake ../opencv-3.4.1 \
    -G"NMake Makefiles JOM" \
    -DCMAKE_VERBOSE_MAKEFILE="ON" \
    -DCMAKE_PREFIX_PATH="D:/artifacts/Debug/Shared;D:/artifacts/Debug/Shared/lib/cmake" \
    -DCMAKE_INSTALL_PREFIX="D:/artifacts/Debug/Shared" \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_DATADIR="lib" \
    -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY="ON" \
    -DCMAKE_BUILD_TYPE="Debug" \
    -DCMAKE_POSITION_INDEPENDENT_CODE="ON" \
    -DCMAKE_C_COMPILER="icl" \
    -DCMAKE_CXX_COMPILER="icl" \
    -DCMAKE_ASM_COMPILER="nasm" \
    -DOpenCV_DISABLE_ARCH_PATH="ON" \
    -DINSTALL_FORCE_UNIX_PATHS="ON" \
    -DBUILD_WITH_DEBUG_INFO="OFF" \
    -DBUILD_opencv_java="OFF" \
    -DBUILD_opencv_python="OFF" \
    -DBUILD_opencv_python2="OFF" \
    -DBUILD_opencv_bioinspired="OFF" \
    -DBUILD_PERF_TESTS="OFF" \
    -DBUILD_TESTS="OFF" \
    -DBUILD_DOCS="OFF" \
    -DWITH_WEBP="OFF" \
    -DBUILD_ZLIB="OFF" \
    -DBUILD_TIFF="OFF" \
    -DWITH_TIFF="OFF" \
    -DBUILD_JPEG="OFF" \
    -DWITH_JPEG="OFF" \
    -DBUILD_PNG="OFF" \
    -DWITH_PNG="OFF" \
    -DWITH_GDCM="OFF" \
    -DBUILD_JASPER="OFF" \
    -DWITH_JASPER="OFF" \
    -DBUILD_OPENEXR="OFF" \
    -DWITH_OPENEXR="OFF" \
    -DBUILD_TBB="OFF" \
    -DWITH_TBB="OFF" \
    -DBUILD_IPP_IW="OFF" \
    -DWITH_IPP="OFF" \
    -DENABLE_CCACHE="OFF" \
    -DWITH_GTK_2_X="OFF" \
    -DWITH_GTK="OFF" \
    -DWITH_VTK="OFF" \
    -DWITH_V4L="OFF" \
    -DWITH_QTKIT="OFF" \
    -DWITH_QT="OFF" \
    -DWITH_LIBV4L="OFF" \
    -DWITH_1394="OFF" \
    -DWITH_XINE="OFF" \
    -DWITH_XIMEA="OFF" \
    -DWITH_GPHOTO2="OFF" \
    -DWITH_FFMPEG="OFF" \
    -DWITH_GSTREAMER="OFF" \
    -DWITH_GSTREAMER_0_10="OFF" \
    -DWITH_MATLAB="OFF" \
    -DWITH_LAPACK="OFF" \
    -DWITH_EIGEN="ON" \
    -DCPU_BASELINE=SSE3 \
    -DENABLE_FAST_MATH="ON" \
    -DENABLE_CXX11="ON"
```

**Comment by tomoaki0705** [comment]
If you could provide the full output of CMake, I might be able to help you.

You're specifying ```CPU_BASELINE``` as ```SSE3``` and ```_mm256_cvtps_ph``` is in AVX.
The availability of this intrinsic depends on what's the result in ```CPU_DISPATCH```.  Was it empty, or the default value which includes ```AVX``` ?
That could be a clue.

**Comment by emmenlau** [comment]
Dear @tomoaki0705 and @alalek , thanks a lot for your very quick responses! You got me on the right track, I was indeed confusing CPU_DISPATCH and CPU_BASELINE. Furthermore I was having an environment variable defined (CFLAGS)  that specified the architecture, and that was picked up during the configuration but not during the build. So it was only a confusion on my side! Thanks a lot for yur help!

**Comment by RoyiAvital** [comment]
Is there a guide how to build OpenCV using Intel Compiler on Windows and macOS?

**Comment by emmenlau** [comment]
@RoyiAvital I did not follow a specific guide for Windows but after a bit of fiddeling it was quite easy. For me the trick was to start the build from the Intel Compiler build shell **and** add the cmake flags `-DCMAKE_C_COMPILER="icl" -DCMAKE_CXX_COMPILER="icl"`. For some packages, it was additionally required to have an asembler compiler on the path, and I chose `nasm` from Cygwin. To enable `nasm` I used `-DCMAKE_ASM_COMPILER="nasm"`. With this combination, quite a number of source packages build fine on Windows.
Note that `OpenCV` is a bit picky with the Intel compiler name, I think setting `icl.exe` may not work while `icl` (without the `.exe` suffix) works.

**Comment by RoyiAvital** [comment]
When you build with Intel Compiler does the project use Intel IPP, MKL and TBB automatically?
Did you compile it under Cygwin or straight under Windows?

Thank You.

**Comment by emmenlau** [comment]
I did not compile under Cygwin, and this part is a bit tricky. It may be easier to just download a standalone assembler for Windows and add it to the path.

Using the Intel Compiler has not directly anything to do with Intel IPP, MKL and TBB. You do not need to have those installed to build with the Intel Compiler, and I do not have them installed. If you want to use those, you may need to check about this topic yourself.
