### ISSUE TITLE
The build fails on i386 systems with no __SSE__ due to missing _mm_pause()

### ISSUE THREAD

**Issue by shlomif** [opencv/opencv#11274]
Hi!

On the mageia i586 build system I am getting this:

```
 /home/iurt/rpmbuild/BUILD/opencv-3.4.1/modules/core/src/parallel_impl.cpp:396:21: note: in expansion of macro 'CV_PAUSE' CV_PAUSE(16); ^~~~~~~~ /home/iurt/rpmbuild/BUILD/opencv-3.4.1/modules/core/src/parallel_impl.cpp: In member function 'void cv::ThreadPool::run(const cv::Range&, const cv::ParallelLoopBody&, double)': /home/iurt/rpmbuild/BUILD/opencv-3.4.1/modules/core/src/parallel_impl.cpp:53:79: error: '_mm_pause' was not declared in this scope # define CV_PAUSE(v) do { for (int __delay = (v); __delay > 0; --__delay) { _mm_pause(); } } while (0) ^ /home/iurt/rpmbuild/BUILD/opencv-3.4.1/modules/core/src/parallel_impl.cpp:673:33: note: in expansion of macro 'CV_PAUSE' CV_PAUSE(16);
```

Please look into fixing it.

**Comment by shlomif** [comment]
Also see http://debian.2.n7.nabble.com/Bug-735627-yrmcds-FTBFS-on-i386-mm-pause-was-not-declared-in-this-scope-td3153524.html

**Comment by alalek** [comment]
Workaround is to specify custom `CV_PAUSE(v)` macro with empty body via CXXFLAGS / CMAKE_CXX_FLAGS / `OPENCV_EXTRA_CXX_FLAGS`.

**Comment by alalek** [comment]
@shlomif Could you try this patch: #11275 ?

**Comment by shlomif** [comment]
@alalek : thanks! Trying now on http://pkgsubmit.mageia.org/ .

**Comment by vsyrjala** [comment]
_mm_pause is actually SSE2 only. I have a P3 machine with SSE but no SSE2 where the build still fails. A simple `s/__SSE__/__SSE2__/` on top of #11275 is enough to fix it.

**Comment by alalek** [comment]
@vsyrjala Feel free to prepare Pull Request (for 3.4 branch).

**Comment by vsyrjala** [comment]
Too lazy to fork for a oneliner.
