### ISSUE TITLE
IMWRITE_TIFF_XDPI imwrite params dpi

### ISSUE THREAD

**Issue by KFPA** [opencv/opencv#11287]
opencv 3.4.1-dev function imwrite params IMWRITE_TIFF_XDPI,IMWRITE_TIFF_YDPI do not work？

       Mat img = imread("C:\\Ursers\\r\\Desktop\\1.tif");
	vector<int> vec;
	vec.push_back(IMWRITE_TIFF_XDPI);
	vec.push_back(300);
	vec.push_back(IMWRITE_TIFF_YDPI);
	vec.push_back(300);
	imwrite("C:\\Users\\KFPA\\r\\4.tif", img, vec);

it does not work，why？
![default](https://user-images.githubusercontent.com/16286927/38594019-fe104734-3d76-11e8-86fe-43726631d021.PNG)

**Comment by saskatchewancatch** [comment]
It seems to work fine for me, with the baboon.tiff image that's in the opencv_extra repo's test data folder. I checked the written image with a TIFF tag viewer (Aware Systems TIFF Tag viewer) and with Windows' own file examiner and I see the DPIs I set.

Would you be able to upload your test image (1.tif) and the result image (4.tif)? It would help reproduce the issue so someone can debug.

**Comment by KFPA** [comment]
it is my fault,i forgot to update opencv dll.it can work now!thanks!!
