### ISSUE TITLE
Chakra failed with error C3861 C2061 C4430 C2143 when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [opencv/opencv#11281]
OpenCV failed with error C3861 C2061 C4430 C2143 when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this?

**You can repro this issue as the steps below:**
1.	git clone https://github.com/opencv/opencv D:\OpenCV\src
2.	git clone https://github.com/opencv/opencv_extra  D:\OpenCV\src\extra
3.	Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\OpenCV\src
4.	Set _CL_=/permissive-
5.	msbuild /p:Configuration=Release;Platform=Win32 build_x86\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true

**Error info:**
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2106): error C2061: syntax error: identifier 'Node'
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2175): note: see reference to class template instantiation '`anonymous-namespace'::ComPtrList<T,NULLABLE>' being compiled
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2127): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2127): error C2143: syntax error: missing ',' before '*'
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2146): error C2061: syntax error: identifier 'Node'
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2119): error C3861: 'pBefore': identifier not found
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2133): error C3861: 'pNode': identifier not found
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2139): error C3861: 'ppItem': identifier not found
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(2140): error C3861: 'ppItem': identifier not found

**Comment by alalek** [comment]
> unreleased vctoolset

We unlikely can fix all of these errors (we can't even check our fixes).

Perhaps some part of these error are related to templated base class. Please try something like this:
```.diff
 class ComPtrList : public List<T*>
 {
 public:
+    typedef typename List<T*>::Node Node;
     typedef T* Ptr;
     ...
     HRESULT InsertAfter(Ptr item, Node *pBefore)
     ...
     HRESULT GetItem(const Node *pNode, Ptr* ppItem)
     ...
     HRESULT RemoveItem(Node *pNode, Ptr *ppItem)
```

**Comment by alalek** [comment]
Well, `set CL=/permissive-` did the trick to reproduce errors (with MSVS 2017).
I will prepare patch for observed problems.

**Comment by QuellaZhang** [comment]
Thanks alalek!  The toolset should release recently, sorry for the mistakes!
