### ISSUE TITLE
Unable to compile OpenCV 3.4.1 on windows.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [opencv/opencv#11288]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => mingw7.3.0

##### Detailed description

below is configure detail:
![image](https://user-images.githubusercontent.com/10345361/38595636-8855830c-3d7f-11e8-869e-5b3007fdd515.png)
![image](https://user-images.githubusercontent.com/10345361/38595650-94d167d6-3d7f-11e8-863e-c202991c60e7.png)
![image](https://user-images.githubusercontent.com/10345361/38595660-9f418822-3d7f-11e8-90cd-4b7495d9a978.png)
![image](https://user-images.githubusercontent.com/10345361/38595670-a644689c-3d7f-11e8-9cef-9aeb552b9ed9.png)
![image](https://user-images.githubusercontent.com/10345361/38595683-aff8a90c-3d7f-11e8-89e5-1ef2e83d96c9.png)
![image](https://user-images.githubusercontent.com/10345361/38595688-b2fb5ca8-3d7f-11e8-8781-5c5f658ed45b.png)
below is make error:
![image](https://user-images.githubusercontent.com/10345361/38595716-d077a962-3d7f-11e8-9e5a-043a1a1f8f02.png)

**Comment by alalek** [comment]
Respect others and never don't use screenshots for posing text messages (first one must be replaced with CMakeCache.txt/CMakeVars.txt files attachments).
At least this blocks search engines to find similar reports.

Also you should use them at first - this is duplicate report about mingw bugs about AVX512 code generation.
