### ISSUE TITLE
Build error with VTK

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#11299]
##### System information (version)

- OpenCV =>new
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I use VS2015 build OpenCV static library. with MT.
on WITH_VTK=TURE, vtk_test.cpp compiler error.

 vtk_test.cpp default compiler use /MDd.

(I VTK static library is MT, MTd)

**Comment by saskatchewancatch** [comment]
Tried building OpenCV master with viz module and with 8.1.0 and it built just fine using VS2017.

Which branch/tag OpenCV and VTK did you build on?
