### ISSUE TITLE
bug in MemoryReturn in cuda module

### ISSUE THREAD

**Issue by bigdimboom** [opencv/opencv#11298]
##### Detailed description

cv::cuda::BufferPool can not handle certain size. 
it triggers assertions when I allocate 512 x 424 CV_16U data
![image](https://user-images.githubusercontent.com/6119906/38647265-5f78250e-3db9-11e8-83cd-5bc8ba5921da.png)

The error is at the pointer "tip - ptr" it does not return correct size
434176, which is the the allocations is correct(512 * 424 * 2 bytes).
4857856 is the result of pointer arithmetic, which is wrong.
Any ideas?
BTW, cv::cuda::GPUMat::create(424, 512, CV_16U) works fine.

##### Steps to reproduce
allocating a cv::GpuMat with cv::cuda::BufferPool(Stream)::getBuffer(params) with the above params
when refcounting calls "release", it riggers above assertion.

**Comment by nglee** [comment]
@bigdimboom Cannot reproduce with this minimal example:

```c++
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace cv::cuda;

int main()
{
	setBufferPoolUsage(true);
	Stream stream;
	BufferPool pool(stream);

	{
		GpuMat mat = pool.getBuffer(424, 512, CV_16UC1);
		mat.setTo(Scalar(5), stream);
	}
}
```

When allocating GpuMat's with BufferPool, release order is important. Please have a look at this [documentation for BufferPool](https://docs.opencv.org/master/d5/d08/classcv_1_1cuda_1_1BufferPool.html). The release order should be like a stack, that is, most recently BufferPool allocated GpuMat must be unallocated first. It is described with sample code in the documentation. You might be in a situation where you violate this rule.

**Comment by bigdimboom** [comment]
Yes, I can see the impl. of default allocation is like a stack. This does not make sense to me though. Shouldn't the order be FIFO since tasks in a steam are executed in a sequential order?

**Comment by nglee** [comment]
In my opinion, memory allocation order could be distinguished from task execution order in a stream. Although tasks that are invoked to same stream are executed in the order they are invoked, the memories used by the tasks can be allocated and de-allocated any time you want.

What I was trying to say was that if you wish to use memory allocated via `BufferPool` with `setBufferPoolUsage(true)`, then for those memories, de-allocation order is LIFO.

If you still get errors, please post an example code that reproduces your issue.
