### ISSUE TITLE
DNN: Test Test_Caffe.FasterRCNN_and_RFCN fails with enabled AVX512

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#11293]
```
[ RUN      ] Test_Caffe.FasterRCNN_and_RFCN
/build/precommit_linux64/opencv/modules/dnn/test/test_common.hpp:54: Failure
Expected: (normL1) <= (l1), actual: 0.000201613 vs 0.0002
model name: resnet50_rfcn_final.caffemodel
[  FAILED  ] Test_Caffe.FasterRCNN_and_RFCN (6500 ms)
```

Basically AVX512 convolution code is more accurate, because it uses 16 intermediate accumulators (which allows to avoid some floating-point issues with large/small numbers).
BTW, "double" type would be more accurate, but perhaps we don't want use this as gold reference result. Because model was trained in the other conditions anyway (with FP32 rounding errors, probably on GPU).

Issue can be reproduced with [Intel SDE](https://software.intel.com/en-us/articles/intel-software-development-emulator) tool (~2 min for this test run on i7-6700):
```
/opt/intel-tools/sde-external-8.16.0-2018-01-30-lin/sde64 -skx -- ./bin/opencv_test_dnn --gtest_filter=*RCNN*
```

**Comment by dkurt** [comment]
@alalek, can we close this issue?
