### ISSUE TITLE
https://opencv.org/releases.html page 2.4.13.6 download link points to 3.4.1 download page.

### ISSUE THREAD

**Issue by tingleshao** [opencv/opencv#11307]
https://opencv.org/releases.html page 2.4.13.6 download link points to 3.4.1 download page.

**Comment by tingleshao** [comment]
Clarification: this is about the Android pack 2.4.13.6 download link.

**Comment by alalek** [comment]
Link on opencv.org is [correct](https://github.com/opencv-infrastructure/opencv.org/blob/3c8ea5049cb526513eab2f96304d6b14e09308f2/_data/releases.yml#L524-L532).
But binary releases for 2.4.13.6 were not uploaded due sf.net servers down/malfunction.
Use 2.4.13.5 instead from sf.net or get release files from [GitHub](https://github.com/opencv/opencv/releases/tag/2.4.13.6).

**Comment by alalek** [comment]
Should be fine now.
