### ISSUE TITLE
(Possible) bug in openCV sample tutorial code.

### ISSUE THREAD

**Issue by malharjajoo** [opencv/opencv#11313]
##### System information (version)

- OpenCV => : 3.3.1
- Operating System / Platform => Ubuntu 16.04 (Xenial)
- Compiler => g++ 5.4.0

##### Detailed description

Hi,

I was trying out the real time pose estimation tutorial from OpenCV ( [this tutorial](https://docs.opencv.org/3.3.0/dc/d2c/tutorial_real_time_pose.html) ), and while looking into the source code, I may have found a (possible) bug - 

The functions for converting between Rotation Matrix and Euler Angles ( please see [euler2rot](https://github.com/opencv/opencv/blob/3.4.1/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Utils.cpp#L229) and [rot2euler](https://github.com/opencv/opencv/blob/3.4.1/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Utils.cpp#L189) from the C++ source code for the tutorial).

**Issue:**
 - The source code in the functions seems to correspond to the Y-Z-X Tait bryan angles, **but with the pitch and yaw interchanged.**  (Does this have something to do with the fact that the camera's coordinate axes has z-facing forward, y-facing downward and x-facing right ?)

**Comment by alalek** [comment]
> 3.3.1

Try latest code from master/3.4 branch at first.
Previous releases from the same major version are not supported.

**Comment by malharjajoo** [comment]
Hi,  

The same issue exists for version 3.4.

**Comment by catree** [comment]
> How can it assume that Rodrigues provides the 3x3 rotation matrix in Y-Z-X convention ?

[Euler–Rodrigues formula](https://en.wikipedia.org/wiki/Euler%E2%80%93Rodrigues_formula) is a **different formalism** to represent rotation than Euler angles. Another formalism is [quaternion](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation).

> A visualization of a rotation represented by an Euler axis and angle. (By DF Malan [Public domain], from Wikimedia Commons)

<a title="By DF Malan [Public domain], from Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Euler_AxisAngle.png"><img width="512" alt="Euler AxisAngle" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Euler_AxisAngle.png/512px-Euler_AxisAngle.png"></a>

You can convert:

- rotation matrix <--> Euler–Rodrigues formula
- rotation matrix <--> Euler angles
- rotation matrix <--> quaternion
- Euler–Rodrigues formula <--> Euler angles
- ...

> The code doesn't seem to match up with the Y-Z-X convention.

I don't understand your issue. 

- heading is angle for Y1
- attitude is angle for Z2
- bank is angle for X3

The are stored in the same order/index in a vector in `rot2euler` and `euler2rot`, this is the only requirement and they have the same meaning, that is:

- index 0 is bank
- index 1 is attitude
- index 2 is heading

The only purpose of these functions in the tutorial is to be able to filter the Euler angles in a Kalman filter .

**Comment by votecoffee** [comment]
I ran into the same issue.  The translation from pnp_detection.get_t_matrix() assumes z is forward, but for pnp_detection.get_R_matrix() z is up because of the convention they are using.  It's not wrong, but it is confusing because the xyz reference is not the same between the euler angles and the translation results.

If you do this, it will have the same reference:
```
	// Get the measured translation
	cv::Mat translation_measured = pnp_detection.get_t_matrix();
	// Get the measured rotation
	cv::Mat rotation_measured = pnp_detection.get_R_matrix();
	// Convert rotation matrix to euler angles
	cv::Mat measured_eulers(3, 1, CV_64F);
	measured_eulers = rot2euler(rotation_measured);

	// Set measurement to predict
	PoseResults.xTranslation = translation_measured.at<double>(0) / 1000.0; // x meters
	PoseResults.yTranslation = translation_measured.at<double>(2) / 1000.0; // y meters
	PoseResults.zTranslation = translation_measured.at<double>(1) / 1000.0; // z meters
	PoseResults.xScale = 1;
	PoseResults.yScale = 1;
	PoseResults.zScale = 1;
	PoseResults.rollAngle = measured_eulers.at<double>(0); // roll radians
	PoseResults.pitchAngle = -measured_eulers.at<double>(2); // pitch radians
	PoseResults.yawAngle = measured_eulers.at<double>(1); // yaw radians
	printf("Panel Pose\r\n");
	printf("     x: %.3fmm\r\n", PoseResults.xTranslation * 1000); // x mm
	printf("     y: %.3fmm\r\n", PoseResults.yTranslation * 1000); // y mm
	printf("     z: %.3fmm\r\n", PoseResults.zTranslation * 1000); // z mm
	printf("  Roll: %.3fdeg\r\n", PoseResults.rollAngle * 180.0 / 3.1416);      // roll degrees
	printf(" Pitch: %.3fdeg\r\n", PoseResults.pitchAngle * 180.0 / 3.1416);      // pitch degrees
	printf("   Yaw: %.3fdeg\r\n", PoseResults.yawAngle * 180.0 / 3.1416);      // yaw degrees
```
