### ISSUE TITLE
YOLOv3 in Opencv

### ISSUE THREAD

**Issue by SoullessStone** [opencv/opencv#11310]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio v15.4.3

##### Detailed description
I tried to do the opencv-tutorial on yolo (https://docs.opencv.org/3.4.1/da/d9d/tutorial_dnn_yolo.html), which works perfectly on yolov2 weights and config. I also tried to use yolov3 weights and configs, which  gave me an error when calling "readNetFromDarknet(modelConfiguration, modelBinary);". I used the "official" files (more detail in the reproduce section), and first tried them out successfully in a "not-opencv"-yolo environment on ubuntu (see tutorial located here: https://pjreddie.com/darknet/yolo/).
I posted a question on SO (https://stackoverflow.com/questions/49777632/opencv-using-yolov3), on which I got an answer telling me yolov3 is currently not supported in opencv and telling me to create an issue here.

This is my first github-ticket. If there's something missing, just ask.

##### Steps to reproduce
The full code is at the bottom of the issue or here: https://docs.opencv.org/3.4.1/da/d9d/tutorial_dnn_yolo.html (I just added the stdafx.h-include for it to work on my setup).

Run this with the following files:
- cfg from: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg
- model from: https://pjreddie.com/media/files/yolov3.weights
- class_names from: https://github.com/pjreddie/darknet/blob/master/data/coco.names
referenced like this in the params:
-source=some.MP4  -cfg=yolov3.cfg -model=yolov3.weights   -class_names=coco.names
the source can also be an image.

```
// Brief Sample of using OpenCV dnn module in real time with device capture, video and image.
// VIDEO DEMO: https://www.youtube.com/watch?v=NHtRlndE2cg
#include "stdafx.h";
#include <opencv2/dnn.hpp>
#include <opencv2/dnn/shape_utils.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <fstream>
#include <iostream>
using namespace std;
using namespace cv;
using namespace cv::dnn;
static const char* about =
"This sample uses You only look once (YOLO)-Detector (https://arxiv.org/abs/1612.08242) to detect objects on camera/video/image.\n"
"Models can be downloaded here: https://pjreddie.com/darknet/yolo/\n"
"Default network is 416x416.\n"
"Class names can be downloaded here: https://github.com/pjreddie/darknet/tree/master/data\n";
static const char* params =
"{ help           | false | print usage         }"
"{ cfg            |       | model configuration }"
"{ model          |       | model weights       }"
"{ camera_device  | 0     | camera device number}"
"{ source         |       | video or image for detection}"
"{ out            |       | path to output video file}"
"{ fps            | 3     | frame per second }"
"{ style          | box   | box or line style draw }"
"{ min_confidence | 0.24  | min confidence      }"
"{ class_names    |       | File with class names, [PATH-TO-DARKNET]/data/coco.names }";
int main(int argc, char** argv)
{
	CommandLineParser parser(argc, argv, params);
	if (parser.get<bool>("help"))
	{
		cout << about << endl;
		parser.printMessage();
		return 0;
	}
	String modelConfiguration = parser.get<String>("cfg");
	String modelBinary = parser.get<String>("model");
	dnn::Net net = readNetFromDarknet(modelConfiguration, modelBinary);
	if (net.empty())
	{
		cerr << "Can't load network by using the following files: " << endl;
		cerr << "cfg-file:     " << modelConfiguration << endl;
		cerr << "weights-file: " << modelBinary << endl;
		cerr << "Models can be downloaded here:" << endl;
		cerr << "https://pjreddie.com/darknet/yolo/" << endl;
		exit(-1);
	}
	VideoCapture cap;
	VideoWriter writer;
	int codec = CV_FOURCC('M', 'J', 'P', 'G');
	double fps = parser.get<float>("fps");
	if (parser.get<String>("source").empty())
	{
		int cameraDevice = parser.get<int>("camera_device");
		cap = VideoCapture(cameraDevice);
		if (!cap.isOpened())
		{
			cout << "Couldn't find camera: " << cameraDevice << endl;
			return -1;
		}
	}
	else
	{
		cap.open(parser.get<String>("source"));
		if (!cap.isOpened())
		{
			cout << "Couldn't open image or video: " << parser.get<String>("video") << endl;
			return -1;
		}
	}
	if (!parser.get<String>("out").empty())
	{
		writer.open(parser.get<String>("out"), codec, fps, Size((int)cap.get(CAP_PROP_FRAME_WIDTH), (int)cap.get(CAP_PROP_FRAME_HEIGHT)), 1);
	}
	vector<String> classNamesVec;
	ifstream classNamesFile(parser.get<String>("class_names").c_str());
	if (classNamesFile.is_open())
	{
		string className = "";
		while (std::getline(classNamesFile, className))
			classNamesVec.push_back(className);
	}
	String object_roi_style = parser.get<String>("style");
	for (;;)
	{
		Mat frame;
		cap >> frame; // get a new frame from camera/video or read image
		if (frame.empty())
		{
			waitKey();
			break;
		}
		if (frame.channels() == 4)
			cvtColor(frame, frame, COLOR_BGRA2BGR);
		Mat inputBlob = blobFromImage(frame, 1 / 255.F, Size(416, 416), Scalar(), true, false); //Convert Mat to batch of images
		net.setInput(inputBlob, "data");                   //set the network input
		Mat detectionMat = net.forward("detection_out");   //compute output
		vector<double> layersTimings;
		double tick_freq = getTickFrequency();
		double time_ms = net.getPerfProfile(layersTimings) / tick_freq * 1000;
		putText(frame, format("FPS: %.2f ; time: %.2f ms", 1000.f / time_ms, time_ms),
			Point(20, 20), 0, 0.5, Scalar(0, 0, 255));
		float confidenceThreshold = parser.get<float>("min_confidence");
		for (int i = 0; i < detectionMat.rows; i++)
		{
			const int probability_index = 5;
			const int probability_size = detectionMat.cols - probability_index;
			float *prob_array_ptr = &detectionMat.at<float>(i, probability_index);
			size_t objectClass = max_element(prob_array_ptr, prob_array_ptr + probability_size) - prob_array_ptr;
			float confidence = detectionMat.at<float>(i, (int)objectClass + probability_index);
			if (confidence > confidenceThreshold)
			{
				float x_center = detectionMat.at<float>(i, 0) * frame.cols;
				float y_center = detectionMat.at<float>(i, 1) * frame.rows;
				float width = detectionMat.at<float>(i, 2) * frame.cols;
				float height = detectionMat.at<float>(i, 3) * frame.rows;
				Point p1(cvRound(x_center - width / 2), cvRound(y_center - height / 2));
				Point p2(cvRound(x_center + width / 2), cvRound(y_center + height / 2));
				Rect object(p1, p2);
				Scalar object_roi_color(0, 255, 0);
				if (object_roi_style == "box")
				{
					rectangle(frame, object, object_roi_color);
				}
				else
				{
					Point p_center(cvRound(x_center), cvRound(y_center));
					line(frame, object.tl(), p_center, object_roi_color, 1);
				}
				String className = objectClass < classNamesVec.size() ? classNamesVec[objectClass] : cv::format("unknown(%d)", objectClass);
				String label = format("%s: %.2f", className.c_str(), confidence);
				int baseLine = 0;
				Size labelSize = getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, &baseLine);
				rectangle(frame, Rect(p1, Size(labelSize.width, labelSize.height + baseLine)),
					object_roi_color, FILLED);
				putText(frame, label, p1 + Point(0, labelSize.height),
					FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 0, 0));
			}
		}
		if (writer.isOpened())
		{
			writer.write(frame);
		}
		imshow("YOLO: Detections", frame);
		if (waitKey(1) >= 0) break;
	}
	return 0;
} // main
```

**Comment by dkurt** [comment]
@SoullessStone, May I ask you to test a PR https://github.com/opencv/opencv/pull/11322?

**Comment by SoullessStone** [comment]
@dkurt Yes, I will try to do it tomorrow!

**Comment by dkurt** [comment]
@SoullessStone, please note that YOLOv3 architecture has three layers that produce object detection predictions with different scales. So you need to collect them all and do final non-maximum suppression. You may also try to use an updated `object_detection.cpp` or `object_detection.py`.

**Comment by SoullessStone** [comment]
@dkurt, I tried, but it didn't work. Probably more because of me than because of your work (I'm a Java developer and C++ is a new world for me).

First I installed (hopefully) the right version of opencv (see history)
```
26  sudo apt-get install build-essential
   27  sudo apt-get update
   28  sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
   29  sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
   30  git clone https://github.com/dkurt/opencv.git
   31  ls
   32  cd opencv
   33  git status
   34  git checkout dnn_yolo3
   35  git branch
   36  git branch -r
   37  git checkout dnn_yolov3
   38  git status
   39  git pull
   40  mkdir build
   41  cd build
   42  cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
   43  make -j7
   44  sudo make install
   45  history
```
Then I copied https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp into a local file ObjectDetection.cpp. Next to the cpp, I created the CMakeLists.txt with this content:
```
cmake_minimum_required(VERSION 2.8)
project( ObjectDetection )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( ObjectDetection ObjectDetection.cpp )
target_link_libraries( ObjectDetection ${OpenCV_LIBS} )
```
I copied the yolov2.weights, yolov3.weights, yolov2.cfg, yolov3.cfg, coco.names to the directory
Then I did a "cmake ." and after that a "make"
This gave me an executable which I used this way:
`yolo@ubuntu:~/Documents/testing/testfiles/ObjectDetection$ ./ObjectDetection -i=game.png -c=yolov2.cfg -classes=coco.names -m=yolov2.weights`
This shows an image with the detection.
When I try to use 
`yolo@ubuntu:~/Documents/testing/testfiles/ObjectDetection$ ./ObjectDetection -i=game.png -c=yolov3.cfg -classes=coco.names -m=yolov3.weights`
I get the error:
```
[ INFO:0] Initialize OpenCL runtime...
OpenCV(3.4.1-dev) Error: Incorrect size of input array (Inconsistent shape for ConcatLayer) in getMemoryShapes, file /home/yolo/Documents/testing/opencv/modules/dnn/src/layers/concat_layer.cpp, line 94
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) /home/yolo/Documents/testing/opencv/modules/dnn/src/layers/concat_layer.cpp:94: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'getMemoryShapes'

Aborted (core dumped)
```

Is there something I have done wrong?

Thanks for your effort!
Michel

**Comment by dkurt** [comment]
@SoullessStone, Firstly you need to use an **updated** samples as mentioned above. You may find them at the same PR https://github.com/opencv/opencv/pull/11322/files. The one more thing is that you need to set an appropriate pre-processing parameters like scale and mean subtraction. According to a table from https://github.com/opencv/opencv/tree/master/samples/dnn#object-detection and a tutorial https://docs.opencv.org/master/da/d9d/tutorial_dnn_yolo.html all the YOLO models work with images with values in range [0, 1] so you need to normalize it by `--scale=0.00392`.

**Comment by SoullessStone** [comment]
@dkurt I tried it again before work. Now I am not able to "make" the updated sample (https://github.com/opencv/opencv/blob/97fec07d9630e3c3010210490dd73bb8d3008ae5/samples/dnn/object_detection.cpp):
```
yolo@ubuntu:~/Documents/testing/testfiles/ObjectDetection$ make
[ 50%] Linking CXX executable ObjectDetection
//usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56: undefined reference to `x265_api_get_79'
collect2: error: ld returned 1 exit status
CMakeFiles/ObjectDetection.dir/build.make:111: recipe for target 'ObjectDetection' failed
make[2]: *** [ObjectDetection] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ObjectDetection.dir/all' failed
make[1]: *** [CMakeFiles/ObjectDetection.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I get the same error for the "old" ObjectDetection.cpp, even tough it is the same file that I could "make" yesterday and I have just shut down the VM yesterday and started it right now without changing anything.

I only had 15min to look into it today. I will probably redo the test on a new VM tomorrow or friday.

But in general, I think I now understood what to do.
Thanks for your patience and have a nice day!

**Comment by SoullessStone** [comment]
Hi @dkurt 
I was now able to test it with the same setup as mentioned above.
Like you said, I just needed to add the scale-parameter. Further, I had to decrease the size (resolution) of the image (game_mini.png).
So, yolov2 still works:
`yolo3@ubuntu:~/Documents/yololololo/test$ ./ObjectDetection -i=game_mini.png -c=yolov2.cfg -classes=coco.names -m=yolov2.weights  --scale=0.00392`
![opencv_yolov2](https://user-images.githubusercontent.com/10846282/39065576-868392b2-44d2-11e8-9c21-0aef18fbd272.PNG)

And yolov3 is also working fine:
`yolo3@ubuntu:~/Documents/yololololo/test$ ./ObjectDetection -i=game_mini.png -c=yolov3.cfg -m=yolov3.weights -classes=coco.names --scale=0.00392`
The results are way better than they where with yolov2! 
![Uploading opencv_yolov3.PNG…]()

When running yolov3 on a FullHD GoPro-MP4, I still get an error:
```
[ INFO:0] Initialize OpenCL runtime...
OpenCV(3.4.1-dev) Error: Incorrect size of input array (Inconsistent shape for ConcatLayer) in getMemoryShapes, file /home/yolo/Documents/testing/opencv/modules/dnn/src/layers/concat_layer.cpp, line 94
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) /home/yolo/Documents/testing/opencv/modules/dnn/src/layers/concat_layer.cpp:94: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'getMemoryShapes'

Aborted (core dumped)
```
But I think I'll have to play with the parameters a little...

This will help my study-project very much!
Thanks for including me in this process and all the best for the future!
Greetings,
Michel

**Comment by dkurt** [comment]
@SoullessStone, look at `weight` and `height` arguments.

**Comment by SoullessStone** [comment]
@dkurt Just came to my mind also.
`yolo3@ubuntu:~/Documents/yololololo/test$ ./ObjectDetection -i=GP060151.MP4 -c=yolov3.cfg -m=yolov3.weights -classes=coco.names --scale=0.00392 --width=416 --height=416
`
This works!
Thank you!

**Comment by SoullessStone** [comment]
PR merged: https://github.com/opencv/opencv/pull/11322
issue is done and @dkurt a hero 😄

**Comment by wait1988** [comment]
why so much memory used with yolo models?

**Comment by dkurt** [comment]
@wait1988, you're right. Please see a pull request https://github.com/opencv/opencv/pull/11461 which reduces maximal memory usage for deep learning networks. In example, it optimizes YOLOv3 model to use only 553MB instead of 1GB.

**Comment by dkurt** [comment]
@IgMart, there are three output layers. All of them can be found by [getUnconnectedOutLayers](https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#ae62a73984f62c49fd3e8e689405b056a).

**Comment by IgMart** [comment]
Thanks for your answer @dkurt , 
Which format is necesary to pass the parameter to net.forward? 
I have tried with net.forward("200") and net.forward("yolo_200")
It still does not work

**Comment by dkurt** [comment]
@IgMart, please check [object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) or [object_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py) samples. Both can work with YOLO models.

**Comment by dkurt** [comment]
@FreeKingofNature, You need to specify input dimensions. See https://github.com/opencv/opencv/issues/11310#issuecomment-383174181.
Please do not use closed issues and PRs to ask questions because we can miss it. Use a forum http://answers.opencv.org instead.

**Comment by FreeKingofNature** [comment]
@dkurt ok , It worked ,thanks.

**Comment by ASShusharin** [comment]
Hi, I try to run dnn/object_detection.cpp with params: -c=yolov3.cfg -m=yolov3.weights -classes=coco.names --scale=0.00392 --width=416 --height=416 and it works, but  time it takes for one image is about 4 seconds. Function: net.forward(outs, getOutputsNames(net)) takes the most time.
Although on the image (https://drive.google.com/open?id=1kZIUS5Dct3sPRZrMKsixFCWLgizbKnzd) on top is written about 745 ms. I run in release and use opencv4.
Also in this link (https://github.com/opencv/opencv/pull/11322) developers writes that median time per 416x416 image is 216.11ms.
What may be the reason of this time difference?
I have Ubuntu OS: https://drive.google.com/open?id=1MvbLah4gNFB-P2JvW5P5MZ7znhlX5u8Y
