### ISSUE TITLE
How to use opencv VideoCapture with django frameworks

### ISSUE THREAD

**Issue by IAmVinnnn** [opencv/opencv#11311]
I have created a script in python using opencv library which capture the faces, create the training data and then detect the faces. Everything is working well. 
But now I want to integrate it in my web application, I got a python framework called django which help to create web application using python. But I am not able to integrate this face capture / detection script in this framework. 
Is any one here who can help me to integrate face detection in the web application using django framework or separately.

**Comment by cftang0827** [comment]
What do you mean "integrate this face capture / detection script in this framework" ?

In my opinion, I think the task you want to do is 

1. Upload a video by using Django
2. Do face detection and cap the face
3. Show it on web

is that right?

If so, I think you can do it separately, first, use Django to upload your video, and then save it on your server's disk, S3 or whatever you want. Seconds, implement a small function that can read video by using VideoCapture API. Third, use opencv hog face detection or haar or dlib...etc to do face detection and capture the face image,  save the image in disk and then show it on your website by using html img tag. 

Finally, clear the cache data including the video you uploaded and the image you saved. 

If there's any better solution, please feel free to judge me. 

Thanks :)

**Comment by itslemcy** [comment]
hey @IAmVinnnn could you share your solution? trying to do almost the same thing, would be happy to contribute

**Comment by IAmVinnnn** [comment]
@cftang0827 thanks for the response, But I don't want what you explained above. I want to capture the realtime faces. Like when I can click on a button it will open the web cam. And for detection purpose I will click a button it will open the web cam and if any face matched in the captured faces then It will update into database.
Please let me know if still not cleared to you.

**Comment by IAmVinnnn** [comment]
Sure, I am going to close it....

**Comment by IAmVinnnn** [comment]
Sure, I am going to close it....
