### ISSUE TITLE
dynamicCast<Boost> returns Segmentation fault

### ISSUE THREAD

**Issue by fragolka** [opencv/opencv#11328]
Hi,

I'm using OpenCV 3.3 running on Linux and bumped into following error:
    ```
   Ptr<StatModel> create_model()
   {
      Ptr<Boost> model = Boost::create();
      model->setBoostType(Boost::DISCRETE);
   }

   int main()
   {
      Ptr<Boost> model = create_model().dynamicCast<Boost>();
   }
    ```

I've used dynamicCast successfully with other classes (SVM, trees, logistic regression), however, casting to boost returns Segmentation fault. Backtracking is not very helpful either:
    ```
    #0  0x0000ffffb6c625d4 in __dynamic_cast () from /usr/lib/libstdc++.so.6
    #1  0x00000000004066e8 in cv::Ptr<cv::ml::Boost> cv::Ptr<cv::ml::StatModel>::dynamicCast<cv::ml::Boost>() const ()
    ```

Is it a bug?

Thanks,
Lucie

**Comment by berak** [comment]
this is [solved](http://answers.opencv.org/question/189540/dynamiccastboost-returns-segmentation-fault/) , btw (function is missing a return value), 

and can be closed.
