### ISSUE TITLE
Unable to compile OpenCV with CUDA9 and gcc6

### ISSUE THREAD

**Issue by yxchng** [opencv/opencv#11346]
My system:
```
CUDA 9.0
cudnn 7.1
gcc6/g++6
```

Encounter the following error:
```
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:206 (message):
  Error generating
  /home/yxchng/git/release/opencv-3.3.1/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

```

Cmake command:

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/bin/g++-6 -DBUILD_opencv_python2=ON -DBUILD_opencv_python3=ON -DWITH_CUDA=YES -DWITH_CUBLAS=YES -DCUDA_GENERATION=Pascal -DWITH_IPP=OFF -DCMAKE_INSTALL_PREFIX=install -DWITH_GSTREAMER=OFF -DCUDA_NVCC_FLAGS="-ccbin /opt/cuda/bin/gcc-6" ..`

**Comment by alalek** [comment]
Build/usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by yxchng** [comment]
Does opencv support gcc6 and cuda9? If not it belongs to here and not QA forum

**Comment by paul-mesnilgrente** [comment]
For people interested (like me), @yxchng has reported the issue [here](http://answers.opencv.org/question/189712/unable-to-compile-opencv-with-cuda9-and-gcc6/)

And apparently, it is clearly a bug from OpenCV as I try compile the last version (3.4.1) with a classic configuration (same as @yxchng, CUDA 9.0/gcc-6) but is it is not compiling, the error comes from the OpenCV files.

**Comment by paul-mesnilgrente** [comment]
For people interested (like me), @yxchng has reported the issue [here](http://answers.opencv.org/question/189712/unable-to-compile-opencv-with-cuda9-and-gcc6/)

And apparently, it is clearly a bug from OpenCV as I try compile the last version (3.4.1) with a classic configuration (same as @yxchng, CUDA 9.0/gcc-6) but is it is not compiling, the error comes from the OpenCV files. Maybe you can write in your documentation that gcc-6 is not supported.

**Comment by marcelogdeandrade** [comment]
I tried adding -D CUDA_NVCC_FLAGS=--expt-relaxed-constexpr to cmake, but it still doesn't work. Has someone found a solution?
