### ISSUE TITLE
core: inRange does not check for empty input Mat 

### ISSUE THREAD

**Issue by berak** [opencv/opencv#11345]
##### System information (version)
- OpenCV => 3.4.1 (master)
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64

##### Detailed description
lower and upper bounds are checked, but not the input Mat, resulting in a low level crash
(no msg with mingw,  "Floating point exception" on linux/gcc)

##### Steps to reproduce
    Mat img; // empty.
    Mat outRED;
    Scalar redDebut(20,28,112);
    Scalar redFin(28,28,112);
    inRange(img,redDebut,redFin,outRED);

**Comment by LaurentBerger** [comment]
@berak  Will you make a PR?

**Comment by alalek** [comment]
Related issue about handling of such cases: #8300

**Comment by berak** [comment]
since pr's now go into 3.4 , but issues are on master branch, this won't get closed automatically anymore
