### ISSUE TITLE
C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\corecrt_malloc.h(63): error : unknown attribute "guard"

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#11368]
##### System information (version)

- OpenCV =>NEW
- Operating System / Platform => WINDOWS10 X64
- Compiler =>VS2015 CUDA9.1

##### Detailed description
OPENCV_CORE build error : 
C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\corecrt_malloc.h(63): error : unknown attribute "guard"

**Comment by alalek** [comment]
Are you sure that CUDA supports your MSVS version?

Anyway I have no idea what should be fixed in OpenCV to resolve similar problems.

**Comment by dbyoung720** [comment]
You mean, VS2017 can be compiled successfully?

**Comment by dbyoung720** [comment]
I try vs2017
cuda9.1\sdk\include\crt/host_config.h(135): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
cuda9.1 is not support vs2017 

To sum up, should be I use CUDA9.0?

**Comment by LaurentBerger** [comment]
@dbyoung720 problem is not opencv but cuda and microsoft :https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/1

**Comment by dbyoung720** [comment]
I see thank.
