### ISSUE TITLE
question about kalman impl

### ISSUE THREAD

**Issue by wxcstc** [opencv/opencv#11365]
It seemed that there are some problems with kalman's implementation in opencv.
The source file is modules/video/src/compat_video.cpp, in function cvKalmanCorrect.
Code is below:
`   /* temp2 = H*P'(k) */`
`    cvMatMulAdd( kalman->measurement_matrix, kalman->error_cov_pre, 0, kalman->temp2 );`
`    /* temp3 = temp2*Ht + R */`
`    cvGEMM( kalman->temp2, kalman->measurement_matrix, 1,
            kalman->measurement_noise_cov, 1, kalman->temp3, CV_GEMM_B_T );`
`    /* temp4 = inv(temp3)*temp2 = Kt(k) */`
`    cvSolve( kalman->temp3, kalman->temp2, kalman->temp4, CV_SVD );`
`    /* K(k) */`
`    cvTranspose( kalman->temp4, kalman->gain );`

This code caculate K，it uses the formula K = （(H*P'(k)*Ht + R) ^-1* H * P'(K)）t，but  standard formula is K = P'(K) * Ht * (H*P'(k)*Ht + R) ^-1 , that is obviously different.
So，opencv use a different formula or it is just a bug？

**Comment by catree** [comment]
Corresponding code (C-API):
https://github.com/opencv/opencv/blob/4b2d1aaeea52e07dff6e925a86313bd3c2f66e8b/modules/video/src/compat_video.cpp#L236-L246

C++ API (more readable):
https://github.com/opencv/opencv/blob/4b2d1aaeea52e07dff6e925a86313bd3c2f66e8b/modules/video/src/kalman.cpp#L110-L120

---

**_This is what looks like to happen for me._**

Using this reference: [Chapter 11 - Tutorial: The Kalman Filter, Tony Lacey](http://web.mit.edu/kirtley/kirtley/binlustuff/literature/control/Kalman%20filter.pdf)

Relevant equations extracted, we have:

![image](https://user-images.githubusercontent.com/8229425/39084396-8dcd5d48-4575-11e8-8938-d8a203b0fddd.png)

(11.26):
![eq1](https://user-images.githubusercontent.com/8229425/39084439-64ba767e-4576-11e8-8a40-96963f799309.png)

Can be rewritten alternatively as (see [Properties of Transpose Matrices](https://math.nyu.edu/~neylon/linalgfall04/project1/dj/proptranspose.htm)):
![eq2](https://user-images.githubusercontent.com/8229425/39084544-03b4b284-4578-11e8-9089-e185c4a99e0a.png)

Covariance matrices `P'_k` and `R` are symmetric ([Properties of the Covariance Matrix](http://www.robots.ox.ac.uk/~davidc/pubs/tt2015_dac1.pdf)):

![image](https://user-images.githubusercontent.com/8229425/39084609-cb29cdf4-4578-11e8-94e0-441fa2947213.png)
![image](https://user-images.githubusercontent.com/8229425/39084604-b254e624-4578-11e8-93c3-1d497fdb9316.png)

So this can be finally written as:

![eq3](https://user-images.githubusercontent.com/8229425/39084680-7a9f329c-4579-11e8-9a46-d42dc33bdc0a.png)

This is solved as a least squares problem using [`cv::solve()`](https://docs.opencv.org/3.4.1/d2/de8/group__core__array.html#ga12b43690dbd31fed96f213eefead2373):

https://github.com/opencv/opencv/blob/4b2d1aaeea52e07dff6e925a86313bd3c2f66e8b/modules/video/src/kalman.cpp#L117

Finally the Kalman gain is obtained:

https://github.com/opencv/opencv/blob/4b2d1aaeea52e07dff6e925a86313bd3c2f66e8b/modules/video/src/kalman.cpp#L119-L120

---

Why this is done this way? 
My guess is that maybe this approach is numerically more stable? Or maybe as it is treated as a least squares problem, Kalman gain `K` is minimized and avoid (numerical or noise) issues with matrix inversion?

**Comment by wxcstc** [comment]
THX~I think I need to supplement some knowledge of mathematics and read some papers...
