### ISSUE TITLE
OpenCV with YOLO V3

### ISSUE THREAD

**Issue by austinmw** [opencv/opencv#11378]
I'm trying to get OpenCV to work with Darknet YOLO V3. I was told that Darknet doesn't support OpenCV 3.4.1, and I need to use 3.4.0. However, it looks like a fix for YOLO V3 in DNN layers was just very recently pushed to the `samples/dnn/object_detection*` files in branch 3.4. So what I'm wondering is, can I apply this fix easily to version 3.4.0 of OpenCV? 

Any help is greatly appreciated, thanks! Also if I'm over-complicating or misunderstanding the issue and there's an easier way to run Yolo V3 config files on video please let me know!

**Comment by dkurt** [comment]
@austinmw, you may use [branch 3.4](https://github.com/opencv/opencv/tree/3.4) or [master branch](https://github.com/opencv/opencv/tree/master). Both of them already have necessary changes from a pull request https://github.com/opencv/opencv/pull/11322.

Can we close an issue?
