### ISSUE TITLE
Strange bug in opencv C++ when accessing pixel value of a Mat near edges

### ISSUE THREAD

**Issue by kafan1986** [opencv/opencv#11370]
System information (version)
OpenCV => 3.4.1 release (installed via homebrew)
Operating System / Platform => OSX 10.13.3
Compiler => Apple LLVM version 9.1.0 (clang-902.0.39.1)

Detailed description
I am getting a very strange Segmentation fault error in one of my project and after 1 full day of my debugging, I have narrowed it down to this part. Below sample code throws same error, when accessing pixel value at row higher than 476 but it should work till 479, given height of matrix is 480.

Steps to reproduce
Here is an example code that may reproduce an issue.
    
    #include <stdio.h>
    #include <opencv2/opencv.hpp>
    #include <opencv2/highgui/highgui_c.h>
    #include <chrono>
    #include <thread>
    using namespace cv;
    using namespace std;
    
    int main( int argc, char** argv )
    {
      Mat image = Mat::zeros(480,640,CV_8UC1);
    
      while (true){
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        cout << image.at<int>(476,638)<< endl; // No Error
        cout << image.at<int>(477,638)<< endl; // Error is HERE
      }
    
      return 0;
    }

**Comment by kinchungwong** [comment]
Given that the matrix type is ```CV_8UC1```, can you change the pixel-reading code to ```image.at<uchar>(row, col)``` (i.e. change from ```int``` to ```uchar``` when calling the ```at<T>()``` function), and see if the issue still occurs?

Also, was the image created that way (with width = 640, height = 480), or was it transposed at some point?

**Comment by kafan1986** [comment]
@kinchungwong  I have updated the question description in the required format. No transpose nothing was done. using uchar does not throw the error at edges but it is not same as a int and why would using image.at<int> throw any error in the first place?

**Comment by kinchungwong** [comment]
I have posted the full write-up here. 

https://github.com/kinchungwong/kinchungwong.github.io/blob/master/opencv_issues_11370/explain_opencv_non_issue_11370.md

----

@alalek 
1. Firstly it is a user issue. 
2. Secondly the issue involves a potential behavior difference between the ```at<T>(i0, i1)``` and ```ptr<T>(i0, i1)```, 
3. ```at<T>``` implicitly multiplies by ```sizeof(T)``` as a matter of C++ pointer arithmetic. This multiplicand is compile-time constant, and relies on user specifying ```T``` correctly. Using a wrong type would shift memory address down one or more rows (number of rows correspond to the ratio between ```sizeof(wrong_type) / sizeof(correct_type)```
4. ```ptr<T>``` multiplies by ```step.p[1]``` . This requires a multiplication at run time. Using a wrong type would read up to a few bytes past the proper end of memory. 
5. That behavior difference only occurs when user causes the method to make the wrong assumption, by specifying a template type different from the matrix's type. 
6. A debug build would have thrown ```CV_DbgAssert```. 
7. OpenCV can choose to remove the potential behavior difference by rearranging the order of pointer type casts.

**Comment by kinchungwong** [comment]
Related #11125 (closed), where user found and fixed the same problem in user's own code through self-discovery. I'm mentioning it here so that other users can read about it. Perhaps online or header inline documentation can be improved for ```at``` and ```ptr```. (Nowadays a lot of editors support showing header inline docs at the cursor / mouse tip.)
