### ISSUE TITLE
OpenCV hangs on exit in exit_handler for 1394

### ISSUE THREAD

**Issue by damonmaria** [opencv/opencv#11371]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Ubuntu 16.04.3 LTS
- Compiler => Whatever `make` uses on Ubuntu

##### Detailed description

My app connects to 15 different RTSP streams when it starts up. If it fails to connect to any (e.g. camera offline) then it exits and `systemd` starts it again. That way it keeps trying until all the cameras are up. This works most of the time but occasionally it doesn't exit properly and hangs. Logs from the Python part of the app seem to show my Python main thread and `atexit` functions have all finished. If I connect `gdb` and show the backtrace of the main thread it shows: 
```
#0  0x00007f7a846e051d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f7a6fcbfcaa in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007f7a6fcc4036 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#3  0x00007f7a6fcc4b53 in libusb_handle_events_timeout_completed () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#4  0x00007f7a6fcc1007 in libusb_exit () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#5  0x00007f7a7504d531 in ?? () from /usr/lib/x86_64-linux-gnu/libdc1394.so.22
#6  0x00007f7a75039a93 in dc1394_free () from /usr/lib/x86_64-linux-gnu/libdc1394.so.22
#7  0x00007f7a83c2fff8 in __run_exit_handlers (status=0, listp=0x7f7a83fba5f8 <__exit_funcs>, 
run_list_atexit=run_list_atexit@entry=true)
    at exit.c:82
#8  0x00007f7a83c30045 in __GI_exit (status=<optimized out>) at exit.c:104
#9  0x00007f7a83c16837 in __libc_start_main (main=0x41dbe0 <main>, argc=2, argv=0x7ffeb5a7b798, init=<optimized out>, fini=<optimized out>, 
rtld_fini=<optimized out>, stack_end=0x7ffeb5a7b788) at ../csu/libc-start.c:325
#10 0x000000000041de19 in _start ()
```

This gave me a hint that it was something to do with 1394. I recompiled OpenCV using `-D WITH_1394=OFF` and now the problem never happens. So I suspect something about the exit handler for 1394 is not working. I'm not sure if this is a problem with OpenCV or some external library (`libdc1394` or `libusb`). 

##### Steps to reproduce

Difficult to reproduce because it only happens occasionally.

**Comment by alalek** [comment]
Please try patch from #13447
