### ISSUE TITLE
regression: CV_FILLED no longer #defined by #including "opencv2/imgproc.hpp"

### ISSUE THREAD

**Issue by seanm** [opencv/opencv#11387]
A recent change in master (vs 3.4.1) broke my build.

I have code like:

```
#import "opencv2/imgproc.hpp"
cv::circle(..., CV_FILLED);
```

It now doesn't compile because CV_FILLED is no longer defined by including imgproc.hpp because this was removed from the end of the file:

```
#ifndef DISABLE_OPENCV_24_COMPATIBILITY
#include "opencv2/imgproc/imgproc_c.h"
#endif
```

The header docs for cv::circle even talk about passing CV_FILLED, so it's odd that some other header should be needed, especially when it didn't used to be.

**Comment by alalek** [comment]
`CV_FILLED` is a part of legacy C-API which is disabled in master (upcoming OpenCV 4.x) and would be removed completely.

**Comment by alalek** [comment]
It is better to check [documentation](https://docs.opencv.org/3.4.1/d6/d6e/group__imgproc__draw.html#gaf10604b069374903dbd0f0488cb43670) for links.

Constant is [here](https://github.com/opencv/opencv/blob/3.4.1/modules/core/include/opencv2/core.hpp#L216). Use it via `cv::FILLED` or `FILLED` (with `using namespace cv;`)

**Comment by seanm** [comment]
Aaahhhhhh.  Thanks!
