### ISSUE TITLE
AV1 support 

### ISSUE THREAD

**Issue by peters** [opencv/opencv#11389]
@alalek FFMPEG 4 now supports libaom enabling encoding of AV1 videos. I'm thinking of adding support for it in opencv_thirdparty. If the final binary `opencv_ffmpeg.dll` does not increase that much in size would this be something that could considered to be included in the official build?

**Comment by alalek** [comment]
What is license of libaom? (we can't build with other GPL libraries; LGPL is fine)

It would be nice to have AV1 support. +1-2Mb size increase should not be a huge issue.

**Comment by peters** [comment]
Binary size for ffmpeg x64 build is roughly 24m libaom included.

**Comment by alalek** [comment]
Thank you! Could you please open PR to ffmpeg/master? I will check it and necessary updates.

**Comment by alalek** [comment]
Great news: [libaom 1.0 release](https://aomedia.googlesource.com/aom/+/v1.0.0)

**Comment by peters** [comment]
@alalek I'm upgrading to v1.0.0 now. Going to run it in our staging environment for a few days. If everything works out I'll submit a PR.

We should probably also consider adding support for their new image format [https://aomediacodec.github.io/av1-avif/](AV1-AVIF).

**Comment by peters** [comment]
@alalek rav1e support just landed in https://github.com/FFmpeg/FFmpeg/commit/d8bf24459b694338de4ceb2a2e6d4d2949d6658d. Once available in the next release of ffmpeg I will submit a PR.

**Comment by asmorkalov** [comment]
@peters Do you plan to work on the patch in mean time?

**Comment by peters** [comment]
@asmorkalov Unfortunately, no.

**Comment by peters** [comment]
Alternative codec to rav1e: https://github.com/OpenVisualCloud/SVT-AV1

**Comment by pwuertz** [comment]
What is the preferred path forward for this? FFMPEG seems to support various backends now, including [rav1e](https://github.com/xiph/rav1e/) and [dav1d](https://code.videolan.org/videolan/dav1d) Does OpenCV automatically gain AV1 support if built against an AV1 enabled FFMPEG?

**Comment by peters** [comment]
@pwuertz In my opinion the best way forward is to modify the docker build script in [opencv_3rdparty](https://github.com/opencv/opencv_3rdparty/blob/ffmpeg/master_20200311/ffmpeg/make_mingw.sh)

> Does OpenCV automatically gain AV1 support if built against an AV1 enabled FFMPEG?

That is correct.

@alalek Maybe you could provide @pwuertz some guidance? :) Maybe we should consider using github actions as it supports build matrixes.

**Comment by peters** [comment]
AV1 encoding support using just rav1e landed in ffmpeg 4.3 release: https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L28

**Comment by peters** [comment]
libaom v2.0.0 has been released: https://aomedia.googlesource.com/aom/+/refs/tags/v2.0.0/CHANGELOG.

**Comment by peters** [comment]
I have a working build for `rav1e` based on this [workflow](https://github.com/xiph/rav1e/blob/master/.github/workflows/rav1e.yml). The problem is that it will add about `34 MB` to the ffmpeg wrapper. `libaom` adds around `7 MB`. @alalek What do you think? If you want I could submit a PR that uses GitHub Actions to the https://github.com/opencv/opencv_3rdparty repository. Then we could attach the `rav1e` enabled ffmpeg wrapper to the GitHub Release and consumers could choose which binary to download during build via CMAKE flag? 

There is also the case of decoding support. The library that looks the most promising right now is https://github.com/videolan/dav1d. I have not tried building it yet because we do not require decoding support atm. But if we choose to enable decoding support in the future the build pipeline should IMHO be improved upon :)

**Comment by alalek** [comment]
@peters Thank you for updates!
Yes, feel free to create PR with necessary changes.
Meantime we will discuss how to properly support multiple FFmpeg wrapper (or still keep single one by default with providing build flag)

**Comment by Tsubajashi** [comment]
is there any news regarding this? AV1 Support would be awesome!

**Comment by piwawa** [comment]
Did AV1 support added?  I download a '.mkv' video from youtube, when i use ''cap = cv2.VideoCapture('2.mkv')" it errored, as follows:
[av1 @ 0000028a88053c40] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0000028a88053c40] Failed to get pixel format.
