### ISSUE TITLE
Can not set `CAP_PROP_CONVERT_RGB` to `false` in VideoCapture When use the Web camera.

### ISSUE THREAD

**Issue by liqiang311** [opencv/opencv#11398]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

My camera's name is "Logitech Webcam C925e".  And I get the infomation of this camera by the ffmepg as below:
```
[dshow @ 00000238fda624a0] DirectShow video device options (from video devices)
[dshow @ 00000238fda624a0]  Pin "Capture" (alternative pin name "0")
[dshow @ 00000238fda624a0]   pixel_format=yuyv422  min s=640x480 fps=5 max s=640x480 fps=30
[dshow @ 00000238fda624a0]   pixel_format=yuyv422  min s=640x480 fps=5 max s=640x480 fps=30
......
[dshow @ 00000238fda624a0]   pixel_format=yuyv422  min s=2304x1536 fps=2 max s=2304x1536 fps=2
[dshow @ 00000238fda624a0]   pixel_format=yuyv422  min s=2304x1536 fps=2 max s=2304x1536 fps=2
[dshow @ 00000238fda624a0]   vcodec=mjpeg  min s=640x480 fps=5 max s=640x480 fps=30
[dshow @ 00000238fda624a0]   vcodec=mjpeg  min s=640x480 fps=5 max s=640x480 fps=30
......
[dshow @ 00000238fda624a0]   vcodec=mjpeg  min s=1920x1080 fps=5 max s=1920x1080 fps=30
[dshow @ 00000238fda624a0]   vcodec=mjpeg  min s=1920x1080 fps=5 max s=1920x1080 fps=30
video=Logitech Webcam C925e: Immediate exit requested
```
And it mean the raw data of camera is yuv format.

Now my algorithm need to process YUV data, but the VideoCapture class get the BGR data by default. And I need to convert which is unneccessary.

I read the document of opencv and find a property named "CAP_PROP_CONVERT_RGB", Its explanation is “Boolean flags indicating whether images should be converted to RGB.”.

I use the following code, but False.

```
VideoCapture cap(0);
cout << cap.get(CAP_PROP_CONVERT_RGB) << endl;
cout << cap.set(CAP_PROP_CONVERT_RGB, false) << endl;
```

And the output is

```
-1
0
```

Also, I try to `cap.set(CAP_PROP_CONVERT_RGB, 0)`, `cap.set(CAP_PROP_CONVERT_RGB, '0')`. All of these are false.

**So I want to get the yuv data by OpenCV, How I do?**

Thank you.

**Comment by alalek** [comment]
> CAP_PROP_CONVERT_RGB

This is optional property, so video backends may not support it.

> .set(..., false)

This method doesn't support 'bool' input values, only doubles. Also result '0' means that this setting of property is failed or this property is not supported.


BTW, DirectShow would be replaced with Microsoft Foundation framework (so new DirectShow features implementation is highly unlikely). Work on MSMF camera support is ongoing in this patch: #11314

**Comment by yuriy-kozlov** [comment]
It's possible to get the raw data from the MSMF or FFMPEG backends, but there are some bugs and it's not documented. Don't know about DirectShow. See my comments here: Issue #16940

That's not the same as YUV data, but then you can convert yourself if the backend won't do it right.

**Comment by alalek** [comment]
Property is added for DirectShow backend here: #14592

This property may work with DirectShow on some devices: #19370 (perhaps with proper FOURCC value)

**Comment by NEUPanXiatong** [comment]
I meet  this problem  too. 
My camera is an infrared one, which output video is YUV2. 
`cap.set(cv2.CAP_PROP_CONVERT_RGB))`
I got the result "0.0" by using above code,  but the final result was not changed comparing with noting to do. What should i do next to get frames from my camera.
