### ISSUE TITLE
Documentation tabs and numbers need to be updated

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#11407]
Looking at https://docs.opencv.org/

- Nightly master branch is now 4.x, so shouldn't the number be changed there?
- Same goes for https://docs.opencv.org/master/, once you click nightly master build, that is still stuck on 3.4.1-dev

Might be good to change this, to make people aware that master is a complete new step forward.

@mshabunin

**Comment by alalek** [comment]
Should work now.

**Comment by catree** [comment]
Just for the record, only Javadoc up to 3.0.0 is listed on the main documentation page [https://docs.opencv.org/](https://docs.opencv.org/):

![image](https://user-images.githubusercontent.com/8229425/40115540-20ecf09e-5911-11e8-842e-959dc70f5497.png)

But it is possible to access up-to-date Javadoc documentation when browsing the C++ documentation by clicking on the Java documentation button:

![image](https://user-images.githubusercontent.com/8229425/40115638-614cdeb0-5911-11e8-88fc-bba480c5a3cd.png)

For 3.4.1: [https://docs.opencv.org/3.4.1/javadoc/index.html](https://docs.opencv.org/3.4.1/javadoc/index.html)

**Comment by alalek** [comment]
Fixed initial docs page.
