### ISSUE TITLE
OpenCV DFT Function - Size Wrong in C++

### ISSUE THREAD

**Issue by soulslicer** [opencv/opencv#11405]
##### System information (version)
- OpenCV => :2.4
- Operating System / Platform => :16.04
- Compiler => :5.4

##### Detailed description

Running the following function yields the wrong size is the 3rd element: The data gets populated correctly but the size is never set

```
    cv::Mat G;
    cv::Mat g = cv::Mat(cv::Size(68,273),CV_32FC1,cv::Scalar(0.));
    cv::dft(g,G,cv::DFT_COMPLEX_OUTPUT);
    std::cout << G.size[0] << " " << G.size[1] << " " << G.size[2] << std::endl;
    exit(-1);
```

`273 68 -823885792`

The last size should have been 2. This works in Python but not in C++.

The same problem extends to the cv::mulSpectrums function.

I can't manually change the size either because if I do that I get a segfault:

`G.size[2] = 2;`

**Comment by soulslicer** [comment]
Why is this considered invalid?

**Comment by berak** [comment]
@soulslicer, late, but an attempt to explain:

you probably expected it to behave like numpy's shape, but it does not.

it's also not related to dft, mulSpectrums or such, *any* 2d Mat in opencv (mat.dims==2) will only allocate & fill the 1st 2 size elements. trying to read or set size[2] is thus out of bounds, undefined behaviour.
