### ISSUE TITLE
Compiler Extra Modules with Matlab, CMake Error.

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#11413]
##### System information (version)

- OpenCV => New
- Operating System / Platform =>Windows10X64
- Compiler => CMake

##### Detailed description
Compiler Ext Modules with Matlab, CMake Generate Error.
Prompt:
CMake Error at E:/Source/OpenCV/opencv_contrib/modules/matlab/CMakeLists.txt:290 (add_dependencies):
  The dependency target "opencv_calib3d" of target "opencv_matlab" does not  exist.

CMake Error at E:/Source/OpenCV/opencv_contrib/modules/matlab/CMakeLists.txt:290 (add_dependencies):
  The dependency target "opencv_core" of target "opencv_matlab" does not  exist.
..................................................
..................................................
..................................................

Opencv_world and MATLAB is not coexistence ?

**Comment by alalek** [comment]
https://github.com/opencv/opencv_contrib/issues
