### ISSUE TITLE
condition at RGB2HLS_f()

### ISSUE THREAD

**Issue by K-Shinotsuka** [opencv/opencv#11414]
Is below code right in RGB2HLS_f()?

>if( diff > FLT_EPSILON)

I think that below code is right.

>if( diff >= FLT_EPSILON)

**Comment by alalek** [comment]
What is the problem? Please provide some complete sample to reproduce problem or reference links (wiki/articles) to confirm the problem.

**Comment by K-Shinotsuka** [comment]
@alalek 
Sorry. I have misunderstood.
