### ISSUE TITLE
Broken links in tutorials

### ISSUE THREAD

**Issue by zgoey** [opencv/opencv#11424]
##### System information (version)

- OpenCV => 3.4.1

##### Detailed description

There is a broken link to https://github.com/opencv/opencv/blob/master/samples/dnn/caffe_googlenet.cpp in https://docs.opencv.org/3.4.1/d5/de7/tutorial_dnn_googlenet.html and a broken link to https://github.com/opencv/opencv/blob/master/samples/dnn/yolo_object_detection.cpp in https://docs.opencv.org/3.4.1/da/d9d/tutorial_dnn_yolo.html.

**Comment by alalek** [comment]
Unfortunately, documentation for release can't be updated (we usually don't updated already released code/documentation).
Replace master to 3.4.1 in these links. Also you could try "3.4.1-dev" to see current maintenance branch.

**Comment by StevenPuttemans** [comment]
Just confirmed that it is still broken in 3.4.1-dev!

**Comment by alalek** [comment]
These pages (from June 5: "3.4.1-dev") should have updated links (to 3.4 branch):
https://docs.opencv.org/3.4/d5/de7/tutorial_dnn_googlenet.html
https://docs.opencv.org/3.4/da/d9d/tutorial_dnn_yolo.html

Related patches: #11638 #11644
