### ISSUE TITLE
Where should I raise the documentation spelling errors?

### ISSUE THREAD

**Issue by abhi-infrrd** [opencv/opencv#11429]
Ex :

1. You need to figure out when it is safe to release your unused objects and make sure you do so before the program finishes or you could have troublesome memory `leeks`.

Link :  https://docs.opencv.org/3.3.0/df/de5/tutorial_interoperability_with_OpenCV_1.html

2. Luckily OpenCV `threats` these two in the same manner, with the same C++ class. So here's what you'll learn in this tutorial:

Link : https://docs.opencv.org/3.3.0/d5/dc4/tutorial_video_input_psnr_ssim.html

I have found spelling issues(and some grammatical mistakes) in other parts for the documentation as well.

**Comment by alalek** [comment]
> 3.3.0

This can't be fixed (we don't amend already released code).

You can check and fix documentation in the latest 3.4 branch:
- https://docs.opencv.org/3.4/df/de5/tutorial_interoperability_with_OpenCV_1.html
- https://docs.opencv.org/3.4/d5/dc4/tutorial_video_input_psnr_ssim.html

Source code for these files are here:
- https://github.com/opencv/opencv/tree/3.4/doc/tutorials/core/interoperability_with_OpenCV_1
- https://github.com/opencv/opencv/tree/3.4/doc/tutorials/videoio/video-input-psnr-ssim

**Comment by abhi-infrrd** [comment]
Thanks. I will start working on it.
