### ISSUE TITLE
Opencv swaps color channel while converting Bayer RG8 image to RGB image.

### ISSUE THREAD

**Issue by ArumugamG** [opencv/opencv#11422]
##### System information (version)
- OpenCV => 3.0
- Operating System / Platform => Windows 7, 64 bit
- Compiler => Visual Studio 2010
##### Detailed description

While converting bayer RG8 images into RGB image using cvtColor() API. Opencv swaps the color channel from RGB to BGR. If it is an expected behavior then the ENUM should be changed so that it will be meaningful and does not make any confusion. By default imshow() expects images should be in BGR format but if we want to consume buffer inside application it will be a problem or user may not be aware of flipping.
##### Steps to reproduce

Mat bayerImg = Mat(1200,1600, CV_8UC1, bayerBuffer); 
Mat rgbImg = Mat(1200,1600, CV_8UC3); 
cvtColor(bayerImg, rgbImg, COLOR_BayerRG2RGB_EA);

Result: rgbImg will have Blue channel first and Red channel last.

**Comment by ArumugamG** [comment]
#4857
[http://answers.opencv.org/question/190229/why-does-opencv-swap-color-channel-when-we-explicitly-mention-cv_bayerrg2rgb/?comment=190417#post-id-190417](url)

**Comment by alalek** [comment]
> 3.0

Try the latest code from 3.4 branch. Some fixes were applied for bayer conversions.
