### ISSUE TITLE
cv.putText() print   ??  for    special characters

### ISSUE THREAD

**Issue by EhabMedhat** [opencv/opencv#11427]
<!-

##### Detailed description
cv.putText() print   ""??"  for    special characters
 in french and german as

étiez arrêté à      cv.put()   function will put   ?tiez arr?t? ?    to the image 

i am currently working on project to translate scanned image from one language to another but the problem  is   special characters in french and german  as étiez arrêté à appear to be as  ?tiez arr?t? ?   
there is a  work around   as
 text = "étiez arrêté à"
text=text.encode('ascii','ignore')
after 
cv2.putText(image,text.decode('ascii','ignore'),(150, 300),cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,255),4)

but it appear as  tiez arrte   

##### Steps to reproduce

  
    // python code example

reading simple image and putting text into it 
image = cv2.imread("text.jpg",1)
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY) # grayscale
showImage(image,"output")
cv2.putText(image,"étiez arrêté à ",(150, 300),cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,255),4)
showImage(image,"output",1)

-->

**Comment by berak** [comment]
the hershey font used here only has a limited subset of ascii. it's a known limitation, it won't show accents, circonflex or any "special" characters like that.

if you *really* need that, you can try to rebuild your cv2 with the [freetype module](https://github.com/opencv/opencv_contrib/tree/master/modules/freetype) from opencv_contrib.

**Comment by EhabMedhat** [comment]
thank you for your response
