### ISSUE TITLE
OpenCv 3.4.1 for Android: Face detection failure with strong backlight.

### ISSUE THREAD

**Issue by kulong51** [opencv/opencv#11435]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by StevenPuttemans** [comment]
Although you question is harsly broken and does not contain the correct and desired information, that is perfectly normal. The training data never contained highly backlighted faces, and thus the trained cascade of boosted trees has not selected features that are invariant to that.
