### ISSUE TITLE
ubuntu install opencv3 meet errors about zlib.a

### ISSUE THREAD

**Issue by xugangtongji** [opencv/opencv#11439]
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libz.a(gzlib.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

**Comment by alalek** [comment]
This is configuration problem and can't be fixed in OpenCV.
You need to install / specify path to libz.so path. Or use BUILD_ZLIB=ON option.

Build/usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
