### ISSUE TITLE
Memory leak in GaussianBlur

### ISSUE THREAD

**Issue by petersupan** [opencv/opencv#11449]
- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
-->

- OpenCV => opencv 3.4.1 pulled today (May 3rd 2018)
The issue was already present in an older build from End of March

##### Detailed description

When running cv::GaussianBlur memory is leaked. visible in the visual studio Diagnostic tools as well as the leakdump.
The leaked memory is allocated in chunks of 2336 bytes and is allocated in **iw_image_filter_gaussian.c**, line 383 ( `pTmpBuffer = (Ipp8u*)ownSharedMalloc(tmpBufferSize);` ).

##### Steps to reproduce, this sample leaks about 35mb

 ```.cpp
void test(const cv::Mat& input, cv::Mat& result)
{
	cv::GaussianBlur(input, result, cv::Size(), 2.0, 2.0);
}

int main(int argc, char** argv)
{
	// if you use visual studio 2017
	//_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
	cv::Mat tmp(256, 256, CV_32FC4);
	for (int i = 0; i < 10000; i++) {
		cv::Mat result(256, 256, CV_32FC4);
		test(tmp, result);
	}
	return 0;
}
```

If you replace the GaussianBlur with 
```.cpp
cv::blur(input, result, cv::Size(3, 3));
```
no leaks are reported and memory usage stays constant.

**Comment by ndvbd** [comment]
Any news here?
