### ISSUE TITLE
opencv-3.3.0 Stops compiling at 58%

### ISSUE THREAD

**Issue by netrosec** [opencv/opencv#11446]
I'm compilling opencv for Rasbian Stretch, running on the Pi 3b.
It compiled all the way to 58% before outputting this error.
Anybody familiar with the error and how to correct it?

##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Rasbian/Raspberry pi 3b
- Compiler => cmake
-->

##### Detailed description

[58%]Linking CXX shared library ../../lib/libopencv_datasets.so
CMakeFiles/opencv_datasets.dir/src/gr_chalearn.cpp.o: file not recognized: File truncated
collect2: error: id returned 1 exit status
modules/datasets/CMakeFiles/opencv_datasets.dir/build.make:858: recipe for target 'lib/libopencv_datasets.so.3.3.0' failed
make[2]: *** [lib/libopencv_datasets.so.3.3.] Error 1
CMakeFiles/Makefile2:14481: recipe for target 'modules/datasets/CmakeFiles/opencv_datasets.dir/all' failed
make[1]: *** [modules/datasets/CMakeFiles/opencv_datasets.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make *** [all] Error 2

##### Steps to reproduce

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.0/modules \
    -D BUILD_EXAMPLES=ON ..
    ```

**Comment by nithinbharadwaj** [comment]
Hi,
I am facing a similar problem with my OpenCV installation as well. Can anybody please help?

**Comment by alalek** [comment]
`make -j1` (or `-j2`) is your choice to build on embedded systems (due memory usage, up to 2Gb+ for 4 build threads).
