### ISSUE TITLE
tf_text_graph_ssd.py  ssdmobilenet v2

### ISSUE THREAD

**Issue by zuoshaobo** [opencv/opencv#11455]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

tf_text_graph_ssd.py  seems that not support ssd-mobilenet v2: the erros below:
(python36) D:\softwares\opencv-3.4.1\opencv-3.4.1\samples\dnn>python tf_text_graph_ssd.py -
-input v2_frozen_inference_graph.pb --output v2.pbtxt
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 131, in <module>
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError

**Comment by dkurt** [comment]
@zuoshaobo, thank you! Could you please test this PR: https://github.com/opencv/opencv/pull/11459?

**Comment by zuoshaobo** [comment]
@dkurt，yeah，it's work
