### ISSUE TITLE
Error Loading .pb model from readNetFromTensorflow

### ISSUE THREAD

**Issue by khaledelmadawi** [opencv/opencv#11452]
- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I am making a simple TF model, and it gives me this error:
python test.py
OpenCV Error: Assertion failed (const_layers.insert(std::make_pair(name, li)).se
cond) in cv::dnn::experimental_dnn_v3::`anonymous-namespace'::addConstNodes, fil
e C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, l
ine 663
Traceback (most recent call last):
  File "dnn_test.py", line 4, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('frozen_graph.pb', 'frozen_graph.pbtxt'
)
cv2.error: C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_import
er.cpp:663: error: (-215) const_layers.insert(std::make_pair(name, li)).second i
n function cv::dnn::experimental_dnn_v3::`anonymous-namespace'::addConstNodes

---------------------------------------------------------------------------------------------------------------
the graph as shown below:
---------------------------------------------------------------------------------------------------------------
        self.x_pl = tf.placeholder(tf.float32, [None,
                                                    self.config.img_height,
                                                    self.config.img_width,
                                                    self.config.num_channels])
        with tf.variable_scope('output') as scope:
            stride = [1, 1, 1, 1]
            kernel_shape = [1,1, self.x_pl.get_shape()[-1], self.config.num_classes]
            w = tf.get_variable('w_conv', kernel_shape, tf.float32,
                                initializer=tf.zeros_initializer())
            self.y_out_unnormal = tf.nn.conv2d(self.x_pl, w, stride, 'SAME')
---------------------------------------------------------------------------------------------------------------
and I am saving the model as shown below:
---------------------------------------------------------------------------------------------------------------
            self.best_saver.save(self.sess, self.config.best_checkpoint_dir, self.model.global_step_tensor)
            tf.train.write_graph(self.sess.graph_def, self.config.best_checkpoint_dir, 'graph.pbtxt', as_text=True)
            tf.train.write_graph(self.sess.graph, self.config.best_checkpoint_dir, 'graph.pb', as_text=False)
---------------------------------------------------------------------------------------------------------------
then I frozen the by this command:
---------------------------------------------------------------------------------------------------------------
            python -m tensorflow.python.tools.freeze_graph --input_binary --input_graph Binary_Protobuf.pb --input_checkpoint mnist_cnn.ckpt --output_graph frozen_graph.pb --output_node_names output/Conv2D
---------------------------------------------------------------------------------------------------------------
Then generated the .pbtxt file:
---------------------------------------------------------------------------------------------------------------
            import tensorflow as tf
            import numpy as np
            graph_filename = "./freez_test/frozen_graph.pb"
            with tf.gfile.GFile(graph_filename, "rb") as f:
                graph_def = tf.GraphDef()
                graph_def.ParseFromString(f.read())
                tf.train.write_graph(graph_def, './', 'frozen_graph.pbtxt', True)
---------------------------------------------------------------------------------------------------------------
Then I loaded it to cv python script to see if it is compatible with the library or not:
---------------------------------------------------------------------------------------------------------------
            import cv2 as cv
            import numpy as np

            cvNet = cv.dnn.readNetFromTensorflow('frozen_graph.pb', 'frozen_graph.pbtxt')
---------------------------------------------------------------------------------------------------------------

and it gave me the mentioned error
cv::dnn::experimental_dnn_v3::`anonymous-namespace'::addConstNodes

I tested it with much out=x*x graph, and it worked , and this is a simple convolution graph, any one know how to solve this problem?

**Comment by dkurt** [comment]
@khaledelmadawi, `*.pbtxt` is optional and it's used to modify TensorFlow's graph in text. Here you just generate it from an origin `.pb` file. Have you tried to load a model using only `frozen_graph.pb`?

**Comment by zuoshaobo** [comment]
@dkurt i use tensorflow  objection_detection api 
python object_detection/export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path ${PIPELINE_CONFIG_PATH} \
    --trained_checkpoint_prefix ${TRAIN_PATH} \
    --output_directory output_inference_graph.pb
use only "output_inference_graph.pb（mobilenetv2-ssd） " but not work，error:
Exception: OpenCV(4.0.0-pre) D:\softwares\o\opencv\modules\dnn\src\tensorflow\tf
_importer.cpp:444: error: (-2:Unspecified error) Input layer not found: Postproc
essor/BatchMultiClassNonMaxSuppression/map/while/NextIteration in function 'cv::
dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::connect'

it is seems that pbtxt file  just point out  the layer which opencv need to use?

**Comment by khaledelmadawi** [comment]
@dkurt  I got another error when i add concatenate layer, it gives me this error:
Traceback (most recent call last):
  File "dnn_test.py", line 4, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('frozen_graph.pb')
cv2.error: C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_import
er.cpp:1487: error: (-2) Unknown layer type ResizeBilinear in op upsample_concat
1/ResizeBilinear in function cv::dnn::experimental_dnn_v3::`anonymous-namespace'
::TFImporter::populateNet

**Comment by aceveggie** [comment]
I'm facing the same problem.

**Comment by vvkv** [comment]
Anybody resolve this yet?

**Comment by dkurt** [comment]
@aceveggie, @vvkv, please clarify the problem.

**Comment by maxwillzq** [comment]
I met similar problem

cv2.error: OpenCV(3.4.3) /opencv-3.4.3/modules/dnn/src/tensorflow/tf_importer.cpp:614: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'

**Comment by aiynmm** [comment]
+1！
cv::Exception: OpenCV(3.4.3) /Volumes/build-storage/build/3_4_iOS-mac/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:614: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'

**Comment by anilknayak** [comment]
+1

**Comment by dkurt** [comment]
Guys, please do not use closed issues. Open a new one following our guides (see issue template). Provide minimal working example including reference to used model. Thank!

**Comment by dlml** [comment]
i face the same problem，how to solve ？

**Comment by nadavb** [comment]
@dkurt, please reopen the issue. I have the same problem. Simple convolutional model, with Flatten(), Conv2D, etc, failed to loaded with OpenCV. The assertion at addConstNodes fails

**Comment by febeks** [comment]
same here, exactly same problem.... @dkurt  please reopen...no point closing this since the original question problem is not solved in this thread since we do not know how to fix it...thank you

**Comment by dkurt** [comment]
@febeks, provide a reproducer please! We also cannorlt debug your model remotely.

If it's not possible to share - provide a graph with obfuscated weights in example.

**Comment by angyee** [comment]
@dkurt @khaledelmadawi @zuoshaobo @vvkv @aceveggie  python3 mask_rcnn.py --mask-rcnn mask-rcnn-coco --image /home/deepedge/mask_rcnn-master/mask-rcnn-bottle-training-master/dataset/val/car39.jpg

[INFO] loading Mask R-CNN from disk...
[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 60540:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
Traceback (most recent call last):
File "mask_rcnn.py", line 48, in
net = cv2.dnn.readNetFromTensorflow(weightsPath, configPath)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: mask-rcnn-coco/dent.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'

tried to implement mask rcnn with my own generated .pb and .pbtxt same below then error ours

How to solve ?

https://www.pyimagesearch.com/2018/11/19/mask-r-cnn-with-opencv/

**Comment by zhoujinhai** [comment]
> @dkurt Thanks it worked in python and passed in the c++, but didn't check if it is correct or not, do you think it will work fine like the Tensorflow model?

Hello, I have the same problem, can you tell me that how you to solved it?

**Comment by jimmykdunn** [comment]
+1 to the original problem - I have it with python however.  Somewhat more complicated net that the OP's, but same issue with the failure happening here: "error: (-215) const_layers.insert(std::make_pair(name, li)).second"

Looking at the cv2 source code that throws this error (https://github.com/opencv/opencv/blob/master/modules/dnn/src/tensorflow/tf_importer.cpp), the assertion in question fails in a block that seems to do nothing of value:

        if (layer.attr().find("value") != layer.attr().end())
        {
            CV_Assert(const_layers.insert(std::make_pair(name, li)).second);
        }

This seems to be looking at the layer in question and if "value" is not the last attribute in the layer, then it attempts to stick in a new const_layer? Why? What sort of problem even causes this if statement to trip in the first place?

Any previous posters - how did you resolve this?  I've been scratching my head at this one for hours and the internet does not seem to have found a solution.

**Comment by hanyanghyhyhy** [comment]
+1 same here, tried both c++ and python.

It seems it is not possible to reduce the dependency of tensorflow. lol

**Comment by AmanGoyalNayan** [comment]
Hry guys. Whenever I load with .pb and .pbtxt , I always get this error:
 cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:613: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'

Whenever I just load using .pb , I get this error : 
    net = cv2.dnn.readNetFromTensorflow('/home/aman/Downloads/optimized_enetworks.pb')#, '/home/aman/Downloads/optimized_enetworks.pbtxt')
cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: batch_normalization_247/FusedBatchNorm in function 'connect'

[optimized_enetworks.txt](https://github.com/opencv/opencv/files/4514255/optimized_enetworks.txt)

**Comment by AmanGoyalNayan** [comment]
Above I have attached the .pbtxt file in text format also

**Comment by dkurt** [comment]
I'm muting this thread. Please keep single issue for a single problem. If you want to report bug - open a new issue and add all the necessary details to reproduce it. We can see notifications from closed threads but after reading we can simply miss it.

Please again note that issue should re reproducible with all the necessary files to run! @AmanGoyalNayan, 3.4.2 is an old release, try only the latest release before opening new bug report.
