### ISSUE TITLE
setAlgorithmType in KNearest unsets all parameters

### ISSUE THREAD

**Issue by tjom** [opencv/opencv#11450]
##### System information (version)
- OpenCV => 3.2 / 3.4
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => gcc 5.4.0

##### Detailed description

It took me some time to figure out why my trained kNN classifier seemed to forget all parameters I set until I saw that `setAlgorithmType` calls `initImpl` which instantiates the corresponding implementation with default parameters. In my opinion this should not be hidden in a setter function, so this should either happen on `create()` (which requires refactoring of the whole `Algorithm` interface) or simply when `train()` is called.

In any case this behaviour should be explicitly specified in the documantation!

##### Steps to reproduce

```.cpp

Ptr<KNearest> knn = KNearest::create();
knn->setDefaultK(3);
knn->setIsClassifier(false);
knn->setAlgorithmType(KNearest::Types::BRUTE_FORCE)

std::cout << knn->getDefaultK() << std::endl; // will print 10 -- should print 3
std::cout << knn->getIsClassifier() << std::endl; // will print 1 -- should print 0

// train knn with some data ...
```

**Comment by berak** [comment]
would there be any objection against moving the `initImpl()` [here, into the train() method](https://github.com/opencv/opencv/blob/master/modules/ml/src/knearest.cpp#L486) ?

read() already does it this way
