### ISSUE TITLE
poor documentation

### ISSUE THREAD

**Issue by fishworx** [opencv/opencv#11466]
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.html

^^ this site has poor examples. The example images are not easy obtained, why cant i just copy and paste and execute... FAIL!!!!!

**Comment by dkurt** [comment]
@fishworx, You may find OpenCV's documentation at https://docs.opencv.org/. Your feedback should go to https://github.com/abidrahmank/OpenCV2-Python-Tutorials.

**Comment by fishworx** [comment]
close it all you want.... the examples still dont work

From python2 IDE.

>>>img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)

OpenCV Error: Assertion failed (mask.size == src1.size) in binary_op, file
/build/opencv-U1UwfN/opencv-2.4.9.1+dfsg1/modules/core/src/arithm.cpp, line
1036
Traceback (most recent call last):
  File "OpenCV73.py", line 18, in <module>
    img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
cv2.error:
/build/opencv-U1UwfN/opencv-2.4.9.1+dfsg1/modules/core/src/arithm.cpp:1036:
error: (-215) mask.size == src1.size in function binary_op


https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.html
