### ISSUE TITLE
cv2 import error

### ISSUE THREAD

**Issue by premsompura** [opencv/opencv#11472]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => RHEL 7.3
- Compiler => gcc 4.8.5
- Python => 2.7.5

##### Detailed description
I have created opencv-python rpm package following [this](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_setup_in_fedora/py_setup_in_fedora.html#installing-opencv-from-source) tutorial. However it works fine on google cloud rhel server but when I try to install it on on-premise server I get this error.

```
>>> import cv2
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
Import Error: /lib64/libgdk-3.so.0: undefined symbol: g_log_structured
```

**Comment by saskatchewancatch** [comment]
@premsompura this sounds like a package configuration issue on the on-premise server more than it is an OpenCV source issue.

**Comment by alalek** [comment]
This binaries migration is out of scope of OpenCV build process - we can't fix custom cases.
