### ISSUE TITLE
android studio 3.1.2 with ndk 17     undefined reference to `cv::DescriptorMatcher::knnMatch

### ISSUE THREAD

**Issue by avfounder** [opencv/opencv#11488]
- OpenCV == 3.4.1
- Operating System / Platform == Windows 64 Bit
- Compiler => Android Studio 3.1.2 with NDK 17

when i compile cppmt with as，then the problem come out.

**Comment by avfounder** [comment]
oh, the problem is opencv-3.4.1 was built by ndk 16, not 17.

**Comment by xuefer** [comment]
but there should be a prebuilt version compiled against ndk r17, since std namespace changed into std::__ndk1
