### ISSUE TITLE
Error: 'nullptr' was not declared in this scope, because of header file of Tesseract

### ISSUE THREAD

**Issue by tlimkim** [opencv/opencv#11486]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Linux Ubuntu 16.04
- Compiler => gcc 5.4.0

##### Detailed description

Hello.

When I build the OpenCV, there is a compile error that is "error: ‘nullptr’ was not declared in this scope" (see below for details). I think there is a problem with 'tesseract' that is support c++11.

```.cpp
/usr/local/include/tesseract/tesscallback.h: In member function 'virtual R _ConstTessMemberResultCallback_1_5<del, R, T, P1, A1, A2, A3, A4, A5>::Run(A1, A2, A3, A4, A5)':
/usr/local/include/tesseract/tesscallback.h:8369:17: error: 'nullptr' was not declared in this scope
       member_ = nullptr;
```

##### Steps to reproduce

I tried ```ENABLE_CXX11=ON``` on CMake Flag, but it didn't work.
Instead of doing that, I added a line of code that enable to compile c++11 in CMakeLists.txt
``` 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

When I added this line and compile the OpenCV, there was no problem while compiling the headerfile of Tesseract that supported by c++11.

I hope this solution would be helpful who wants to build OpenCV and Tesseract together.

**Comment by alalek** [comment]
Lets keep this in the proper place: https://github.com/opencv/opencv_contrib/issues/1636
