### ISSUE TITLE
MSER transition from 2.4 to 3.* parameter setting problem

### ISSUE THREAD

**Issue by mahsaayi** [opencv/opencv#11487]
Hello, 
We are using opencv's **MSER** class to extract stable regions in our project object detection stage for years, but we have some problems **in transition from opencv version 2.4 to 3.*** as MSER class has some changes. Due to the facts that default parameters value have not changed in this transition we expect to not get different regions with our previous parameters setting but we get absolutely different and wrong regions with those parameters in opencv3 version and finding the reason and new parameter setting wasn't straight forward at all. 
As we reviewed logs of changes in these transition, we found that there were some bug fixes so we expect to get better results in version 3 but it was vice versa. 
Another problem is about the Mask parameter; as I realized the mask parameter in opencv 2.4 was applied in the main procedure to not process the part of image which is not in the mask but in opencv 3 the detect function just omit the MSER regions obtained from detectregions which are not in the mask location after processing whole image and this makes the whole procedure slower especially in embedded systems with limited processing resources. 

I would be so thankful for your help. 
@gylns 

##### System information (version)
- OpenCV => 3.1 3.3 2.4
- Operating System / Platform => Ubuntu, Embedded linux

**Comment by mahsaayi** [comment]
I realized that there are huge modifications in updateTree function as it use the delta parameter in a different way. The question is how should we change the parameters to get exact results as 2.4 function and why the description of delta in opencv [docs](https://docs.opencv.org/3.4/d3/d28/classcv_1_1MSER.html) has no changes?

**Comment by mahsaayi** [comment]
closed this as I posted another better one [here](https://github.com/opencv/opencv/issues/11510)!

**Comment by GuanRainy** [comment]
how to use mask parameter in MSER::detectRegions method in opencv 3 and above ?
