### ISSUE TITLE
dnn: OCL implementation only works on Intel GPU

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#11493]
##### System information (version)

- OpenCV => recent master ( 9dc200525 )
- Operating System / Platform => Windows 10 64bit / Arm 32bit (Tinkerboard, ODROID-XU4)  / Arm 64bit (Firefly RK3399)
- Compiler => Visual Studio 2015 / GCC 6.3.0 / 5.4.0
- Device => Intel Core i7 8650U, NVIDIA GTX 1060, Arm Mali T860, Mali T760, Mali T628

##### Detailed description
- Two tests from ```opencv_test_dnn``` fail 
```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Test_TensorFlow_layers.batch_norm/1, where GetParam() = DNN_TARGET_OPENCL
[  FAILED  ] Test_TensorFlow_layers.pooling/1, where GetParam() = DNN_TARGET_OPENCL

 2 FAILED TESTS
```
- The list of device and the test result is as following (device was chosen by environment variable ```OPENCV_OPENCL_DEVICE```)

|Device|OPENCV_OPENCL_DEVICE|Test result|
|---|:-:|:-:|
|Intel UHD Graphics 620|```:igpu```|PASS|
|Intel Corei7 8650U|```:cpu```|FAILURE|
|NVIDIA GTX 1060|```:dgpu```|FAILURE|
|Arm Mali T***|```:igpu```|FAILURE|

- I looked in the [source code](https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/dnn.cpp), and there [are](https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/layers/pooling_layer.cpp#L193) [lots](https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/layers/mvn_layer.cpp#L253) [of](https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/layers/elementwise_layers.cpp#L180) ```isIntel``` call in dnn module
https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/layers/pooling_layer.cpp#L192-L194

- On the other hand, in [dnn.cpp](https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/dnn.cpp), ```isIntel``` is not utilized correctly
https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/dnn.cpp#L725
https://github.com/opencv/opencv/blob/9dc20052517ac580b8b0e079191442e8929f022e/modules/dnn/src/dnn.cpp#L1493
- Also, recent Corei7 series are capable of OpenCL, not on the iGPU, but on the CPU itself.
- In both Corei7 and HD graphics, ```isIntel()``` become true, but it seems that something wrong is happening when cpu version of OpenCL is triggered.
- I once tried removing all the ```isIntel``` but still, the result of OpenCL version didn't match with CPU version.
- As a result, OpenCL version implementation exists, but is only available on Intel HD graphics.
- I'll send a PR by inserting a ```isIntel``` every where, so that OpenCL implementation of dnn module will only correctly triggered on Intel GPU
- Probably, the correct way to go is to **remove** the ```isIntel```, but that was a mess, at least for now.
- I'll send a PR later

##### Steps to reproduce
- Build recent master with OpenCL activated
- Run ```opencv_test_dnn``` on NVIDIA GPU/Intel CPU/Arm GPU.

**Comment by tomoaki0705** [comment]
For reference, I pasted the failure log [here](https://gist.github.com/tomoaki0705/3ea050a1ce63bfa26a2de38578611487) and the log with my PR [here](https://gist.github.com/tomoaki0705/d16780d00e5663b12a6356b73d093423)

**Comment by tomoaki0705** [comment]
Solved by #11494 and #11557

**Comment by GArik** [comment]
One DNN test is still failing for me:
```
$ ./opencv_test_dnn --gtest_filter='DNNTestNetwork.MobileNet_SSD_v2_TensorFlow*'
[ INFO:0] global /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp (891) haveOpenCL Initialize OpenCL runtime...
CTEST_FULL_OUTPUT
OpenCV version: 4.1.2-dev
OpenCV VCS version: 4.1.2-122-g86db0328c2-dirty
Build type: Debug
Compiler: /usr/bin/g++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2019.0.0 Gold (-) Jul 24 2018
OpenCL Platforms: 
    AMD Accelerated Parallel Processing
    Portable Computing Language
        CPU: pthread-AMD Ryzen 7 2700X Eight-Core Processor (OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-znver1)
    NVIDIA CUDA
        dGPU: GeForce GTX 1080 (OpenCL 1.2 CUDA)
Current OpenCL device: 
    Type = dGPU
    Name = GeForce GTX 1080
    Version = OpenCL 1.2 CUDA
    Driver version = 430.26
    Address bits = 64
    Compute units = 20
    Max work group size = 1024
    Local memory size = 48 KB
    Max memory allocation size = 1 GB 1005 MB 112 KB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_fp64
        cl_khr_byte_addressable_store
        cl_khr_icd
        cl_khr_gl_sharing
        cl_nv_compiler_options
        cl_nv_device_attribute_query
        cl_nv_pragma_unroll
        cl_nv_copy_opts
        cl_nv_create_buffer
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
TEST: Skip tests with tags: 'mem_6gb', 'verylong', 'debug_verylong', 'dnn_skip_halide', 'dnn_skip_ocl', 'dnn_skip_ocl_fp16', 'dnn_skip_ie_ocl', 'dnn_skip_ie_ocl_fp16'
Note: Google Test filter = DNNTestNetwork.MobileNet_SSD_v2_TensorFlow*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from DNNTestNetwork
[ RUN      ] DNNTestNetwork.MobileNet_SSD_v2_TensorFlow/0, where GetParam() = OCV/OCL
TEST ERROR: Don't use 'optional' findData() for dnn/ssd_mobilenet_v2_coco_2018_03_29.pb
[ INFO:0] global /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp (433) OpenCLBinaryCacheConfigurator Successfully initialized OpenCL cache directory: /home/lxuser/.cache/opencv/4.1-dev/opencl_cache/
[ INFO:0] global /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp (457) prepareCacheDirectoryForContext Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_1080--430_26
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory 
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-dev) /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp:5025: error: (-220:Unknown error code -220) OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueReadBuffer(q, handle=0x564fb5854b50, CL_TRUE, 0, sz=2880000, data=0x564fb3b3cec0, 0, 0, 0) in function 'map'
" thrown in the test body.
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.2-dev) /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp:4754: error: (-215:Assertion failed) u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive" in function 'deallocate'

Aborted (core dumped)
```

**Comment by alalek** [comment]
> C++ exception with description "OpenCV(4.1.2-dev) /home/lxuser/Projects/opencv/repos/opencv/modules/core/src/ocl.cpp:5025: error: (-220:Unknown error code -220) OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueReadBuffer(q, handle=0x564fb5854b50, CL_TRUE, 0, sz=2880000, data=0x564fb3b3cec0, 0, 0, 0) in function 'map'

Unfortunately, this OpenCL error is not recoverable.
Need to investigate and find workaround for NVIDIA OpenCL runtime (if its possible).
(perhaps as a separate issue.)
