### ISSUE TITLE
dnn layer error

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#11509]
OpenCV Error: Unspecified error (Can't create layer "Axpy1" of type "Axpy") in cv::dnn::experimental_dnn_v3::LayerData::getLayerInstance, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\dnn.cpp, line 257

**Comment by tomoaki0705** [comment]
Too less information (no compiler version, no OS detail, no version of OpenCV, nothing about WHAT you want to do)
If you are **asking for help**, the best place to post is [answers.opencv.org](http://answers.opencv.org/questions/), not here
