### ISSUE TITLE
Converting YUB to RGB turns out green.

### ISSUE THREAD

**Issue by zeshaoaaa** [opencv/opencv#11508]
### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Android
- Compiler => Android Studio

#### Detailed description

The image below not exactly the image displaying on my phone, but they're the same.

The java code in the bottom might not familiar to you, but its simple.

All it does just create a Mat using the data from the raw image, and the real job it hands the Imgproc.

The difference between a sample code and my code is I change the getOutputSizes(ImageReader.class) 

to getOutputSizes(ImageFormat.JPEG), the method is in the JavaCamera2View.

I am not familiar with C++, I don't know how to find out the source code of the Imgproc.hpp.

If you know how it works or my description missing the info you need, please tell me. Thanks in advance.

[stackoverflow](https://stackoverflow.com/questions/7954416/converting-yuv-into-bgr-or-rgb-in-opencv)
[answer.opencv](http://answers.opencv.org/question/61628/android-camera2-yuv-to-rgb-conversion-turns-out-green/)

![image](https://user-images.githubusercontent.com/13615002/39957362-3e129dbc-5624-11e8-9cf6-9aba2f7e2023.png)

#### JavaCode

ByteBuffer y_plane = Y.getBuffer().get(data, 0, Yb);
ByteBuffer uv_plane = U.getBuffer().get(data, Yb, Ub);
Mat y_mat = new Mat(h, w, CvType.CV_8UC1, y_plane);
Mat uv_mat = new Mat(h / 2, w / 2, CvType.CV_8UC2, uv_plane);
JavaCamera2Frame tempFrame = new JavaCamera2Frame(y_mat, uv_mat, w, h);`

#### C++ Code
CV_EXPORTS_W void cvtColorTwoPlane( InputArray src1, InputArray src2, OutputArray dst, int code ); #

**Comment by tomoaki0705** [comment]
Is the YUV image correct ?
I know that if the YUV image is corrupt, it tends to appear as green pixel in RGB color space
In your code you are using ```data```, ```Y``` and ```U``` which neither of them are explained.

And, more over, stop posting simultaneously on all the post.
If you are **asking for help**, I suggest you to ask on answer.opencv.org, not here.
