### ISSUE TITLE
OpenCV causes memory leak on Android without any operation

### ISSUE THREAD

**Issue by paatz04** [opencv/opencv#11507]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Android OnePlus 5T API 27 
- Compiler => Android Studio

##### Detailed description
Running an activity with CvCameraViewListener2 causes a memory leak and crashes my application. 

When I'm calling the function blobFromImage it crashes because of a memory leak in no time.
I'm loading a tensorflow network, and it works, forward works. But the memory just keeps growing. If I comment out everything except the blobFromImage the leak still persists.
I'm using the default mobilenet coco pre-trained set with pbtxt that I created with the openCV python transformation script, but that shouldn't matter right?

##### Steps to reproduce
onCameraViewStarted calls:

```
 String config = getPath("ssd_mobilenet_v1_coco_2017_11_17.pbtxt", this);
        String model = getPath("frozen_inference_graph.pb", this);
        net = Dnn.readNetFromTensorflow(model, config);

```
onCameraFrame calls:

```
Mat blob = Dnn.blobFromImage(frame, IN_SCALE_FACTOR,
                new Size(IN_WIDTH, IN_HEIGHT),
                new Scalar(MEAN_VAL, MEAN_VAL, MEAN_VAL), false,true);
```

**Comment by paatz04** [comment]
<img width="2527" alt="screen shot 2018-05-12 at 12 36 38" src="https://user-images.githubusercontent.com/8363908/39956674-944fd5a8-55e5-11e8-8199-8390ba59794e.png">

**Comment by paatz04** [comment]
```
Dnn.blobFromImage(frame, IN_SCALE_FACTOR,
                new Size(IN_WIDTH, IN_HEIGHT),
                new Scalar(MEAN_VAL, MEAN_VAL, MEAN_VAL), false,true);

```
this call no matter what always completely blows up my memory

**Comment by zeshaoaaa** [comment]
Hello @paatz04 ,
Are you using Camera2? Is it work? I just asked a [YUV problem](https://github.com/opencv/opencv/issues/11508l). 
Have you encountered the problem?

**Comment by paatz04** [comment]
Hi @zeshaoaaa , I tried Camera2 and normal Camera - both work until they run out of memory. 
The link you shared doesn't work "404 not found"

**Comment by zeshaoaaa** [comment]
@paatz04 
Sorry, my bad. I changed the URL, you can access now. 
After I found out the speed of MyJavaCameraView is too slow on my phone, I change to Camera2, 
But it's not working. Could you publish some code that works?

**Comment by paatz04** [comment]
The performance with Camera2 is actually much worse for me. I have 4.7 fps with Camera and 2.7 fps with Camera2. In my setup I can simply swap camera out for camera2. But I'm not too sure I understand your question. 

I'm using an Activity very similar to this one : 
https://github.com/opencv/opencv/blob/master/samples/android/mobilenet-objdetect/src/org/opencv/samples/opencv_mobilenet/MainActivity.java

**Comment by zeshaoaaa** [comment]
Thanks for your help @paatz04 . 

At first, the problem is the operation getOutputSizes(ImageReader.class) in Jave2CameraView returns null. 

Then I change the format to Image.JPEG, then the image turns out green. 

Do you know what problem it will causes?

**Comment by paatz04** [comment]
Hei @zeshaoaaa . Sorry I'm beginner in OpenCV too, and am not sure how to help you. I hope you found a solution in the meantime.

For everyone else having OOM issues with the opencv sample code, the blob created from Dnn.... needs to be manually released and same goes for all the other Mat's created.

I'm monitoring memory usage now and it looks good. Will report if something changes
Thanks

**Comment by kira5865** [comment]
Hi @paatz04, may i know how you manually release the blob from Dnn? I tried to use blob.release(), but the memory leak still persist. Please help. FYI, I am working on opencv C++.
