### ISSUE TITLE
What  checks button in pr is for?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#11513]
Hi,

may be my memory is not good but checks button in PR is new?

What is for?
![image](https://user-images.githubusercontent.com/3591626/39985404-d0ca547a-575e-11e8-9a41-c184fa88c8da.png)

**Comment by tomoaki0705** [comment]
That's not a topic about OpenCV, it' about each repository in the entire Github.

**Comment by catree** [comment]
See directly in the Github help page: [About status checks](https://help.github.com/articles/about-status-checks/).

**Comment by LaurentBerger** [comment]
Ok no problem I follow instruction in https://github.com/opencv/opencv/wiki/How_to_contribute : ignore button
