### ISSUE TITLE
checkHardwareSupport does not do bounds checking in release

### ISSUE THREAD

**Issue by tzickel** [opencv/opencv#11540]
##### System information (version)
OpenCV Master

##### Detailed description

checkHardwareSupport in release does not check if feature is valid, and access arbitrary memory.

##### Steps to reproduce
```python
>>> import cv2
>>> cv2.checkHardwareSupport(1001211112)
Segmentation fault: 11
```

**Comment by alalek** [comment]
It is application's developer responsibility to pass valid input values here.
Input of this function is not classified as direct user input. Values must be fully defined by application code and contains valid values only.
