### ISSUE TITLE
#Unknown layer type Shape in op conv2d_transpose/Shape in function populateNet

### ISSUE THREAD

**Issue by naserpiltan** [opencv/opencv#11549]
##### System information (version)

- OpenCV => :3.4.1:
- Operating System / Platform => :ubuntu 16.04:
- Compiler => : gcc:
- tensorflow 1.8.1

##### Detailed description
I am trying to import a denoising autoencoder model created in tensorflow with opencv++ dnn module.
I freeze graph and weights with freeze_graph.py and create frozen_graph.pb .
so I import that with readNetFromTensorflow but it appears following problem .
I think conv2d_transpose layer does not supported in OpenCV dnn module.
 ```
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Shape in op decoder/upsample1/Shape) in populateNet, file /home/naser/opencv/opencv-3.4.1/modules/dnn/src/tensorflow/tf_importer.cpp, line 1582
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /home/naser/opencv/opencv-3.4.1/modules/dnn/src/tensorflow/tf_importer.cpp:1582: error: (-2) Unknown layer type Shape in op decoder/upsample1/Shape in function populateNet
 ```
I read the issue explained in  #10065 and changed  my opencv version to 3.4 but my problem doesn't solved.
can anybody help to solve my problem ??
thank you

This is decoder part of my code
 
   ```
with tf.name_scope('decoder'):
     conv3 = tf.layers.conv2d(encoded,filters=32,kernel_size=(3,3),strides=   (1,1),name='conv3',padding='SAME',use_bias=True,activation=lrelu)
     
     upsample1 = tf.layers.conv2d_transpose(conv3,filters=32,kernel_size=3,padding='same',strides=2,name='upsample1')

     upsample2 = tf.layers.conv2d_transpose(upsample1,filters=32,kernel_size=3,padding='same',strides=2,name='upsample2')

     logits = tf.layers.conv2d(upsample2,filters=1,kernel_size=(3,3),strides=(1,1),name='logits',padding='SAME',use_bias=True)

     decoded = tf.sigmoid(logits,name='recon')
``` 
this is my model and weights and output frozen_graph.pb in tensorflow.
[model&&output.zip](https://github.com/opencv/opencv/files/2020093/model.output.zip)

**Comment by naserpiltan** [comment]
@dkurt thank 
thank you for your speedy response sir.
i'll test yor workround soon.

**Comment by naserpiltan** [comment]
@dkurt  
I installed OpenCV 3.4.x.
and want to deploy my graph. but when i run tensorflow code that you saied above , appears following problem 
````
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 57: invalid start byte

````
what is problem ??
I am using python 3.6 and tensorflow 1.8 and jupyternotebook 6.3.1
thank you

**Comment by dkurt** [comment]
@naserpiltan, oh, yeah, I'm sorry. Please replace 
```python
with tf.gfile.FastGFile('frozen_graph.pb') as f:
```
onto
```python
with tf.gfile.FastGFile('frozen_graph.pb', 'rb') as f:
```

**Comment by naserpiltan** [comment]
@dkurt  
thank you sir.
i fixed that . sorry for beginner.
now i have  inference_graph.pb and can use it in opencv, but have an other issue.
i am using this code in opencv to  import   inference_graph.pb .
````
 Net net = dnn::readNetFromTensorflow("inference_graph.pb");
    vector<String> lays=net.getLayerNames();
    for (int i = 0; i < lays.size(); ++i) {
        cout<<lays[i]<<endl;
    }

    Mat bbb ;
    int ss[]={28,28};
    Mat image(2,ss,CV_32F);
    for (int i = 0; i < image.dims; ++i) {
        cout<<"dimension "<<i<<" is of size="<<image.size[i]<<endl;
    }

    blobFromImage(image,bbb,1.0f/255,Size(28,28));
    net.setInput(bbb);
    Mat out=net.forward("decoder/logits/Conv2D");
    cout<<out.size()<<endl;
````
i am testing a zero initialized image on  my model. because of my training dataset is mnist, the output size must to be 28by28 , but i have 1by1 for output size.
what is my mistake ?
this is my inference_graph.pb file.
[inference_graph.pb.zip](https://github.com/opencv/opencv/files/2022344/inference_graph.pb.zip)

**Comment by naserpiltan** [comment]
@dkurt  
please give me an idea .I tried a lot but coudn't solve this problem

**Comment by dkurt** [comment]
@naserpiltan, `out.size()` returns number of rows and columns of `cv::Mat`. Even for images with several channels (i.e. RGB) it doesn't contain number of channels. You need to call `.channels()` this way. Moreover for `cv::Mat` with more than 2 dimensions, `rows` and `cols` are `-1`. See the docs: https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#abed816466c45234254d25bc59c31245e.
Please try `cout<<out.size<<endl;` instead.

**Comment by naserpiltan** [comment]
@dkurt
Thank you so much sir.
You made my day.
I fixed the problem.

**Comment by dkurt** [comment]
@naserpiltan, you're welcome! Good luck!
