### ISSUE TITLE
compiling cuda with gcc failed at option -Wimplicit-fallthrough=3

### ISSUE THREAD

**Issue by breadbread1984** [opencv/opencv#11552]
I compile the latest OpenCV on ubuntu 18.04 with cuda 9.1 and gcc-6 as CUDA_HOST_COMPILER, gcc-7 as CMAKE_CXX_COMPILER. but always fails at compiling cuda. The error message is 

> gcc-6: error: unrecognized command line option ‘-Wimplicit-fallthrough=3’; did you mean ‘-Wno-fallthrough’?                                                                                         CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:206 (message):                             Error generating                                                                                  /home/xieyi/tmp/opencv/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

It seems cmake pass unsupport parameters to CUDA_HOST_COMPILER. How to deal with the problem. thx

**Comment by alalek** [comment]
Workaround is using of the same compiler for CMake and CUDA - something like this:
`CC=gcc-6 CXX=g++-6 cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-6 ...`

Also you could try this patch: #11558

**Comment by breadbread1984** [comment]
thanks it works
