### ISSUE TITLE
opencv shufflenet

### ISSUE THREAD

**Issue by zuoshaobo** [opencv/opencv#11561]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

will opencv support shuffnet in the feature?,i see it depends on the mkl-dnn,if i use intel cpu,so dose the inter inference engine

**Comment by dkurt** [comment]
@zuoshaobo, please provide necessary references to mentioned network.

**Comment by StevenPuttemans** [comment]
hello @dkurt 
The paper: https://arxiv.org/pdf/1707.01083.pdf
A Tensorflow implementation: https://github.com/MG2033/ShuffleNet
A Caffe implementation: https://github.com/farmingyard/ShuffleNet
There is even an ONX standard model: https://github.com/onnx/models/tree/master/shufflenet

**Comment by dkurt** [comment]
Layer implementation has been merged
