### ISSUE TITLE
tf_text_graph_ssd.py

### ISSUE THREAD

**Issue by herunyu** [opencv/opencv#11560]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Mac OS , Ubuntu 16.04
- Compiler => cmake

##### Detailed description

When I use the newest version of tf_text_graph_ssd.py to generate graph txt file for my own tensorflow model, I keep getting this error:

Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 138, in <module>
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError

I have trained two models using ssd_mobilenet_v1 and ssd_mobilenet_v2.
I notice that the newest tf_text_graph_ssd.py should support ssd_mobilenet_v2 but it does not work so I went back to train using ssd_mobilenet_v1. And still, the tf_text_graph_ssd.py showed the same error. 
After that, I went back to the previous version of tf_text_graph_ssd.py and it successfully generate the pbtxt for ssd_mobilenet_v1 model. 
Please take a look to the new version, I honestly don't know why it does not work while the other Issue post says it worked. Thank you!

**Comment by dkurt** [comment]
@herunyu, please share your models or at least a single iteration state.

**Comment by herunyu** [comment]
@dkurt  I did that but it gave me the same AssertionError.

**Comment by dkurt** [comment]
@herunyu, May I ask you to comment a line 
https://github.com/opencv/opencv/blob/d381948cee5d6e2365693a5d90d328d2b2b7e170/samples/dnn/tf_text_graph_ssd.py#L52
and try again?

**Comment by herunyu** [comment]
Alright it finally works now. Thank you! Are we going to always do the transformation first before we use the tf_text_graph_ssd.py? Or you may add this into the next commit?

**Comment by dkurt** [comment]
@herunyu, no, this is not necessary. This PR is going to fix it: https://github.com/opencv/opencv/pull/11580.

**Comment by proximadata** [comment]
Can you guys explain how to use this fix or what to do to make it work? I face the same problem. Thanks.

**Comment by dkurt** [comment]
@proximadata, we merged necessary changes to the script. Please try to update OpenCV locally.

**Comment by stq054188** [comment]
https://github.com/opencv/opencv/issues/11560#issuecomment-391047037 

@dkurt  When I use your code, I can successfully generate pbtxt file, but when I use opencv call it the following error occurs,

[libprotobuf ERROR c:\build\master_winpack-build-win64-vc15\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 45167:5: Unknown enumeration value of "20" for field "type".
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.0) Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: ./model_fpn/graph.pbtxt) in cv::dnn::ReadTFNetParamsFromTextFileOrDie, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\tensorflow\tf_io.cpp, line 54

`String weights = "./model_fpn/frozen_inference_graph.pb";
String prototxt = "./model_fpn/graph.pbtxt";
dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);`

Please help me, thanks

**Comment by dkurt** [comment]
@stq054188, do not use closed issues please. There is http://answers.opencv.org/.

**Comment by stq054188** [comment]
> @stq054188, do not use closed issues please. There is a forum http://answers.opencv.org/.

I am sorry, i will change to a new issue.

**Comment by LUOBO123LUOBO123** [comment]
tf_text_graph_ssd.py don't generate pbtxt.
File "tf_text_graph_ssd.py", line 138, in
assert(graph_def.node[0].op == 'Placeholder')
AssertionError

**Comment by zcunyi** [comment]
> @herunyu, please share your models or at least a single iteration state.

### System information (version)
OpenCV => 4.0.0
Operating System / Platform => Ubuntu 16.04 LTS
Compiler => cmake

### Detailed description
When I use the newest version of tf_text_graph_ssd.py to generate graph txt file for my own tensorflow model, I keep getting this error:

```
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 368, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 232, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError
```

Please take a look to the new version, I honestly don't know why it does not work while the other Issue post says it worked. Thank you!

**Comment by SourceCodeCat** [comment]
I'm running opencv version '4.1.0' with tensorflow 1.13.1 and still need the above script with my re-trained  SSD mobile v1 graph

**Comment by fuatka** [comment]
> @herunyu, Please do the following transformation:
> 
> ```python
> import tensorflow as tf
> from tensorflow.tools.graph_transforms import TransformGraph
> 
> with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
>     graph_def = tf.GraphDef()
>     graph_def.ParseFromString(f.read())
>     graph_def = TransformGraph(graph_def, ['image_tensor'], ['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'], ['sort_by_execution_order'])
>     with tf.gfile.FastGFile('sorted_inference_graph.pb', 'wb') as f:
>         f.write(graph_def.SerializeToString())
> ```
> 
> It sorts all the nodes in a suitable order.

This error is still avaliable at 4.5.2 version with custom trained ssd_resnet50_v1 models. It seems we need to sort graph nodes in any case. Thanks Dmitry :)
