### ISSUE TITLE
Export and convert Tensorflow1.8 model to Opencv dnn

### ISSUE THREAD

**Issue by julesd16** [opencv/opencv#11570]
##### System information (version)

- OpenCV Python =>3.4.0
- Operating System / Platform =>  Ubuntu 16.04
- Tensorflow 1.8

##### Detailed description

Hello,
I have follow this tutorial to train my own model ["TensorFlow Object Detection API Tutorial"](https://www.youtube.com/watch?v=srPndLNMMpk). Everything work fine if I use tensorflow API. I am able to detect my object whitin my image but as soon as I used my frozen inference graph in Opencv Dnn I keep getting an out of memory error. 
So I try to follow [this](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) tutorial to convert my frozen graph. Then I get this error:

cvNet = cv.dnn.readNetFromTensorflow('opt_graph.pb')
cv2.error: /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1487: error: (-2) Unknown layer type Enter in op Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Enter in function populateNet

This [tutorial ](http://answers.opencv.org/question/175699/readnetfromtensorflow-fails-on-retrained-nn/)give me another error.

cvNet = cv.dnn.readNetFromTensorflow('final_graph.pb')
cv2.error: /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1487: error: (-2) Unknown layer type Enter in op Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Enter in function populateNet

I have test everything with opencv 3.4.0 and 3.4.1 and I got different error message with OpenCV 3.4.1
Please. Can someone just redirect me to a good/recent tutorial or tell me how to convert this file so it will be compatible with Opencv Dnn.  

Thanks in advance.

##### Steps to reproduce
 cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb') 
or
 cv.dnn.readNetFromTensorflow('final_graph.pb')
[exported_model.zip](https://drive.google.com/open?id=1Fk-y0NZ6nZvBr7S_3I58xniJ370S5tcW)

**Comment by dkurt** [comment]
@julesd16, mentioned [wiki page](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) contains instructions of how to generate a text file with an extension `.pbtxt` required as a second argument of `readNetFromTensorflow`.

**Comment by dkurt** [comment]
@julesd16, please specify which [config file](https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs) did you use to train this model?

**Comment by julesd16** [comment]
@dkurt I used ssd_mobilenet_v1_pets.config 
[ssd_mobilenet_v1_pets.zip](https://github.com/opencv/opencv/files/2032088/ssd_mobilenet_v1_pets.zip)

**Comment by dkurt** [comment]
@julesd16, Can you please share a piece of code of how to serialize a graph? I afraid that for now batch normalization layers are serialized in training mode but not in evaluation one (they have `tf.nn.moments` nodes).
![screenshot from 2018-05-29 16-50-48](https://user-images.githubusercontent.com/25801568/40663004-75d8af4a-6360-11e8-8038-1c54cdb9680c.png)

**Comment by dkurt** [comment]
@julesd16, May I ask you experiment with a `train: true` field of `batch_norm` at your config file? I think we need to turn it to `train: false` if we wanted to create an inference graph. The thing is that all the [published mobilenet ssd models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models-coco-models) have batch normalization with accumulated mean and variance.

**Comment by julesd16** [comment]
@dkurt Ok, I will train it again with `batch_norm` to false and tell you if it has change something.

**Comment by dkurt** [comment]
@julesd16, No no. Just replace train to test and call export_inference_graph.py

**Comment by julesd16** [comment]
@dkurt I got the same error 
```
cvNet = cv.dnn.readNetFromTensorflow('exported_model_Graph_NoBatchNorm/frozen_inference_graph.pb', 'exported_model_Graph_NoBatchNorm/graph.pbtxt')
cv2.error: OpenCV(4.0.0-pre) /home/usr/Opencv3.4.1/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1195: error: (-213:The function/feature is not implemented) Expected gamma, beta, mean and std in function 'populateNet'
```

**Comment by dkurt** [comment]
@julesd16, thanks! I'll try to figure out why it differs from the rest of models.

**Comment by dkurt** [comment]
@julesd16, may I ask you to attach a serialized model with `train: false` to see the difference?

**Comment by julesd16** [comment]
@dkurt Yes I have change them both. In this [zip](https://drive.google.com/open?id=1W7sESz6PPQvbJAIg20j2wvZGT6DI9ii3) file I add the two model one with `train:false` and the other with `train: true`. I add as well the training checkpoint which I convert later to a frozen inference graph. The config file is include as well.  Thanks for the support

**Comment by wildpig22** [comment]
I believe that I've met the same problem before..it was a bug in tensorflow object detection API, I can't remember the issue # though...

Anyway @julesd16 can you confim your tensorflow and tensorflow-mobels version please?

When I met this problem, a temporary fix was to change
`      with slim.arg_scope(
          mobilenet_v1.mobilenet_v1_arg_scope(
              is_training=None, regularize_depthwise=True)):`
to 
`      with slim.arg_scope(
          mobilenet_v1.mobilenet_v1_arg_scope(
              is_training=False, regularize_depthwise=True)):`
(line 107 in tensorflow-models\research\object_detection\models\ssd_mobilenet_v1_feature_extractor.py)
while running export_inference_graph.py, and change to is_training=True while training. I was using pip installed tensorflow-gpu 1.8.0 and tensorflow-model was around Feburary.

Or the simpler way is to pull the latest repo for both of them and run export_inference_graph.py again, it worked for me.

**Comment by julesd16** [comment]
@wildpig22  Thanks to you I am able to pass the first step readNetFromTensorflow, But I got another error in the foward phase. 
`OpenCV(4.0.0-pre) /home/usr/Opencv3.4.1/opencv/modules/dnn/src/layers/detection_output_layer.cpp:212: error: (-215:Assertion failed) int(numPriors * _numClasses) == inputs[1][1] in function 'getMemoryShapes'`

I have update everything (tensorflow 1.8 and models folder) today before testing I also try with the optimize_for_inference function and the transform_graph. I tested and recreated the .pbtxt file for each test as mentioned in the opencv [tutorial](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API). I will try to look more into it tomorrow and I will let you know if I manage to make it work.

**Comment by wildpig22** [comment]
@julesd16 glad to hear that :)

Regarding the new error, have you specified `--num_classes` option while running tf_text_graph_ssd.py? The default value is 90 and your config file is 1.

**Comment by julesd16** [comment]
@wildpig22  You were right. WHOUHOU. It works now.

So just to summarize the process after training your model: 
1. Be sure everything is up to date Model folder and use Opencv 3.4.1
2. You need to put all `batch_norm` to false in your config file
3. Change `with slim.arg_scope( mobilenet_v1.mobilenet_v1_arg_scope( is_training=False, regularize_depthwise=True)):`  in line 107 in tensorflow-models\research\object_detection\models\ssd_mobilenet_v1_feature_extractor.py
4. Export export_inference_graph to get the frozen graph
5. Follow OpenCV [tutorial](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API)

@dkurt and @wildpig22 Thank you very much for the help!

**Comment by wildpig22** [comment]
@julesd16 you are welcome, actually I've stumbled into similiar problems just last month, so I'm very glad to save you (and @dkurt ) a few minutes :-D

Actually regarding (3), with latest TF and TF model repo, the default `is_training=None` param works for me, can you test that? Just to remind, if you train the same network again and forget to change it, you will waste many hours...don't ask me how I know XD

**Comment by julesd16** [comment]
@wildpig22  I tried with `is_training=None` and I can't create the inference graph. I got a lot of error with that. For my case it need to be true or false

**Comment by dkurt** [comment]
@julesd16, can we close an issue?
