### ISSUE TITLE
When using different versions of opencv, the image is rotated

### ISSUE THREAD

**Issue by GuanRainy** [opencv/opencv#11586]
when I use opencv(2.4.10) and opencv(2.4.13) to imread a image(as follow), the image size is (width=720, height=540), and the actual size of the picture is (720, 540). but when I us opencv(3.2.0) and opencv(3.4.1) imread it too, it size is (540, 720), the image has been rotated 90 degree(clock-wise).  When I use python  opencv, this problem still exists.
System information (version)
- OpenCV => 2.4.10, 2.4.13, 3.2.0 and 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

![005580_1](https://user-images.githubusercontent.com/20217397/40484783-5351fa0a-5f8f-11e8-8cfb-324a7bfe4807.jpg)

**Comment by berak** [comment]
it's not a bug, the orientation is taken from the exif information in the image (introduced in opencv3)

please use [cv.IMREAD_IGNORE_ORIENTATION](https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#gga61d9b0126a3e57d9277ac48327799c80a34f91a514cd95127d8ba900840af548e) to disable this "feature"

**Comment by GuanRainy** [comment]
thanks

**Comment by GuanRainy** [comment]
thanks
