### ISSUE TITLE
Release tarballs of 3.2.0 and 3.1.0 changed

### ISSUE THREAD

**Issue by jkelling** [opencv/opencv#11585]
I am not sure whether this is the right place to report this. It is however the best fit I found.

The tarballs of the releses 3.2.0 and 3.1.0 here on GitHub changed sometime between 2017-10-25 and last week. Are you aware of this and can you tell us why this happened?

##### System information (version)

- OpenCV = 3.1
- OpenCV = 3.2

##### Detailed description

Please see [this](https://github.com/spack/spack/pull/8241) pull request against the spack package.

##### Steps to reproduce

Download 3.2.0 source tar.gz from [here](https://github.com/opencv/opencv/releases?after=3.3.0) and get a copy of the previous version and compare. Alternatively compare md5sum with the one listed [here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/opencv/package.py) ( a43b65488124ba33dde195fea9041b70 ).

Same thing for 3.1.0.

**Comment by alalek** [comment]
We don't control packaging of these archives. It is related to GitHub changes and affects many GitHub projects.
