### ISSUE TITLE
Convert numpy array elements into images

### ISSUE THREAD

**Issue by KafeelBasha** [opencv/opencv#11615]
Hello
Consider the object 'train_x' is a numpy array with dimension (10,28,28), can you please help me in converting these 10 array elements into 10 different images using opencv and name accordingly and store in a location, say "E:\\Images".

Any reference or example will be helpful.

**Comment by berak** [comment]
helo @KafeelBasha , this is the opencv *bugtracker*, and the wrong place to ask your question.

so please kindly close this issue, and ask again on http://answers.opencv.org, we can help you much better from there.

**Comment by KafeelBasha** [comment]
Okay.
