### ISSUE TITLE
OpenCV failed to run 33 tests in opencv_test_imgproc.exe

### ISSUE THREAD

**Issue by shanshan0309** [opencv/opencv#11613]
Hi All,

OpenCV failed to run 33 tests in opencv_test_imgproc.exe on Windows with VS2017 Update 7. Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/opencv/opencv D:\OpenCV\src
2. git clone https://github.com/opencv/opencv_extra  D:\OpenCV\src\extra
3. Open a VS 2017 x86 prompt  and browse to D:\OpenCV
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6. msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
7. .\bin\Release\opencv_test_imgproc.exe

**Error info:**
The whole log file please see attachment.
[opencv_log_x86_test.log](https://github.com/opencv/opencv/files/2047070/opencv_log_x86_test.log)
[==========] 422 tests from 134 test cases ran. (95156 ms total)
[  PASSED  ] 389 tests.
[  FAILED  ] 33 tests, listed below:
[  FAILED  ] ImgProc/HoughCirclesTestFixture.regression4f/0, where GetParam() = ("imgproc/stuff.jpg", 20, 20, 30, 20, 200)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/0, where GetParam() = ("shared/pic5.png", 1, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/1, where GetParam() = ("shared/pic5.png", 1, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/2, where GetParam() = ("shared/pic5.png", 1, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/3, where GetParam() = ("shared/pic5.png", 1, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/4, where GetParam() = ("shared/pic5.png", 10, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/5, where GetParam() = ("shared/pic5.png", 10, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/6, where GetParam() = ("shared/pic5.png", 10, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/7, where GetParam() = ("shared/pic5.png", 10, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/8, where GetParam() = ("../stitching/a1.png", 1, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/9, where GetParam() = ("../stitching/a1.png", 1, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/10, where GetParam() = ("../stitching/a1.png", 1, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/11, where GetParam() = ("../stitching/a1.png", 1, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/12, where GetParam() = ("../stitching/a1.png", 10, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/13, where GetParam() = ("../stitching/a1.png", 10, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/14, where GetParam() = ("../stitching/a1.png", 10, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec2f/15, where GetParam() = ("../stitching/a1.png", 10, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/0, where GetParam() = ("shared/pic5.png", 1, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/1, where GetParam() = ("shared/pic5.png", 1, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/2, where GetParam() = ("shared/pic5.png", 1, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/3, where GetParam() = ("shared/pic5.png", 1, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/4, where GetParam() = ("shared/pic5.png", 10, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/5, where GetParam() = ("shared/pic5.png", 10, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/6, where GetParam() = ("shared/pic5.png", 10, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/7, where GetParam() = ("shared/pic5.png", 10, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/8, where GetParam() = ("../stitching/a1.png", 1, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/9, where GetParam() = ("../stitching/a1.png", 1, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/10, where GetParam() = ("../stitching/a1.png", 1, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/11, where GetParam() = ("../stitching/a1.png", 1, 0.1, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/12, where GetParam() = ("../stitching/a1.png", 10, 0.05, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/13, where GetParam() = ("../stitching/a1.png", 10, 0.05, 150)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/14, where GetParam() = ("../stitching/a1.png", 10, 0.1, 80)
[  FAILED  ] ImgProc/StandartHoughLinesTest.regression_Vec3f/15, where GetParam() = ("../stitching/a1.png", 10, 0.1, 150)

**Comment by alalek** [comment]
1. Missing test data image (or disabled JPEG codec in your build):

> d:\opencv\src\modules\imgproc\test\test_houghcircles.cpp(120): error: Value of: src.empty()
  Actual: true
Expected: false

2. Missing test data files:

> d:\opencv\src\modules\imgproc\test\test_houghlines.cpp(210): error: Value of: node.empty()
  Actual: true
Expected: false
Missing test data: lines_shared_pic5_png_1_0_05_80_0_0
XML: D:\OpenCV\src\extra\testdata/cv/imgproc/HoughLines2f.xml

**Comment by shanshan0309** [comment]
Thank you Alexander. This issue has been solved. OpenCV works well now.
