### ISSUE TITLE
Question: How does a cv::ogl::Texture2D(DEPTH COMPONET) map to glsl sampler object

### ISSUE THREAD

**Issue by bigdimboom** [opencv/opencv#11611]
I need  pass a type CV_16U cv::cuda::GpuMat to a texture sampler in glsl. So I did the following:

cv::cuda::GpuMat depthmap; // 16bit UINT map
cv::ogl::Texture2D cvTexobj;
cvTexobj.copyFrom(depthmap);
cvTexobj.bind(); // then do things in glsl shader

Due to lack of documentations of cv::ogl::Texture and glsl Samplers. I have no idea what internal type of this texture is. As result, I could not choose which sampler type I should use. Does any one know how do I sample a cv::ogl::Texture which type is "DEPTH_COMPONENT"?

Thanks

**Comment by panmengjia** [comment]
I want to know how to use gpumat and ogl to speedup imshow,Thanks anyone for fixing this problem!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
