### ISSUE TITLE
FaceRecognizer

### ISSUE THREAD

**Issue by WaleedJubeh** [opencv/opencv#11629]
hello ...
before show my issue this is my system information
- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => java netbeans 8.2
********************************
i'm trying to make live face recognition  so i do face detection after that i start to make trainer .
Trainer use FaceRecognizer class or one of its sub-classes  to train and predict .
Unfortunately  openCV don't contain these classes so how can i get it in java ?

**Comment by berak** [comment]
hello @WaleedJubeh , this is the opencv *bugtracker* , and the wrong place to ask questions like yours.

so, please kindly *close* this issue, and ask again on http://answers.opencv.org , we can help you much better from there !
