### ISSUE TITLE
cv::Size buggy behaviour when switching image orientation?

### ISSUE THREAD

**Issue by MarviB16** [opencv/opencv#11624]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => macOS High Sierra
- Compiler => Apple Clang++

##### Detailed description

When i use the size function on Images (Mat), i don't always get the right height/width of the image.
**To be more specific:** 
When i load an image with landscape orientation and afterwards load a image with portrait orientation, the width and height values aren't right, but switched. 
I think this could be a bug, but maybe im just missing something.

##### Steps to reproduce

```
int main(int argc, char** argv)
{
    String path = "/Picutres/test/*.jpg";
    vector<String> fn;
    glob(path, fn, true); // recursive, if you want
    
    for (size_t i=0; i<fn.size(); i++)
    {
        uninitializeVariables();
        printf("%zu\n",i);
        runSegmentation(fn[i]);
    }
    
    return 0;
}
int runSegmentation(String filename) {
    InImg = imread(filename);
 
    if(! InImg.data )  // Check for invalid input
    {
        cout <<  "Could not open or find the image" << std::endl ;
        return -1;
    }
    static Size ImSize = InImg.size();
    printf("Height: %i, Width: %i\n", ImSize.height, ImSize.width);
    //DO SOMETHING
}
```

**Comment by alalek** [comment]
Try search with "EXIF" keyword.
