### ISSUE TITLE
CUDA Median filter tests fail with CUDA 9.1 but pass with CUDA 8.0

### ISSUE THREAD

**Issue by nglee** [opencv/opencv#11622]
##### System information (version)

- OpenCV => lates 3.4 branch 44572fac44f7b7c4636313d60b01d89466972713
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

In `opencv_test_cudafilters` test, `CUDA_Filters/Median.Accuracy` tests fail when compiled with CUDA 9.1, but the tests pass when compiled with CUDA 8.0.

May be related: https://github.com/opencv/opencv/issues/10414

**Comment by jcdutton** [comment]
The cause might be similar to the cause in #11621 
https://github.com/opencv/opencv/issues/11621

**Comment by nglee** [comment]
Fixed by https://github.com/opencv/opencv/pull/12722
