### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'python36_d.lib' [G:\Lib\build\opencv\modules\python3\opencv_python3.vcxproj]

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#11645]
- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

When I build opencv I have got one error : 
"G:\Lib\build\opencv\ALL_BUILD.vcxproj" (cible par d▒faut) (1) ->
"G:\Lib\build\opencv\modules\python3\opencv_python3.vcxproj" (cible par d▒faut) (420) ->
(Link cible) ->
  LINK : fatal error LNK1104: cannot open file  'python36_d.lib' [G:\Lib\build\opencv\modules\python3\opencv_python3.vcxproj]

    366 Avertissement(s)
    1 Erreur(s)

Problem when I opencv debug version of opencv_python3 project, command line is : 
`/OUT:"G:\Lib\build\opencv\lib\python3\Debug\cv2.cp36-win_amd64.pyd" /MANIFEST /NXCOMPAT /PDB:"G:/Lib/build/opencv/lib/python3/Debug/cv2.pdb" /DYNAMICBASE "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\libs\python36.lib" "..\..\lib\Debug\opencv_reg400d.lib" "..\..\lib\Debug\opencv_surface_matching400d.lib" "..\..\lib\Debug\opencv_xphoto400d.lib" "..\..\lib\Debug\opencv_face400d.lib" "..\..\lib\Debug\opencv_fuzzy400d.lib" "..\..\lib\Debug\opencv_hfs400d.lib" "..\..\lib\Debug\opencv_img_hash400d.lib" "..\..\lib\Debug\opencv_xobjdetect400d.lib" "..\..\lib\Debug\opencv_superres400d.lib" "..\..\lib\Debug\opencv_bioinspired400d.lib" "..\..\lib\Debug\opencv_dpm400d.lib" "..\..\lib\Debug\opencv_line_descriptor400d.lib" "..\..\lib\Debug\opencv_saliency400d.lib" "..\..\lib\Debug\opencv_ccalib400d.lib" "..\..\lib\Debug\opencv_rgbd400d.lib" "..\..\lib\Debug\opencv_structured_light400d.lib" "..\..\lib\Debug\opencv_tracking400d.lib" "..\..\lib\Debug\opencv_videostab400d.lib" "..\..\lib\Debug\opencv_aruco400d.lib" "..\..\lib\Debug\opencv_bgsegm400d.lib" "..\..\lib\Debug\opencv_optflow400d.lib" "..\..\lib\Debug\opencv_sfm400d.lib" "..\..\lib\Debug\opencv_stitching400d.lib" "..\..\lib\Debug\opencv_objdetect400d.lib" "..\..\lib\Debug\opencv_phase_unwrapping400d.lib" "..\..\lib\Debug\opencv_viz400d.lib" "..\..\lib\Debug\opencv_plot400d.lib" "..\..\lib\Debug\opencv_datasets400d.lib" "..\..\lib\Debug\opencv_text400d.lib" "..\..\lib\Debug\opencv_dnn400d.lib" "..\..\lib\Debug\opencv_photo400d.lib" "..\..\lib\Debug\opencv_ximgproc400d.lib" "..\..\lib\Debug\opencv_xfeatures2d400d.lib" "..\..\lib\Debug\opencv_ml400d.lib" "..\..\lib\Debug\opencv_shape400d.lib" "..\..\lib\Debug\opencv_video400d.lib" "..\..\lib\Debug\opencv_calib3d400d.lib" "..\..\lib\Debug\opencv_features2d400d.lib" "..\..\lib\Debug\opencv_flann400d.lib" "..\..\lib\Debug\opencv_highgui400d.lib" "..\..\lib\Debug\opencv_videoio400d.lib" "..\..\lib\Debug\opencv_imgcodecs400d.lib" "..\..\lib\Debug\opencv_imgproc400d.lib" "..\..\lib\Debug\opencv_core400d.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" /IMPLIB:"G:/Lib/build/opencv/lib/Debug/opencv_python3.lib" /DEBUG /DLL /MACHINE:X64 /INCREMENTAL /PGD:"G:\Lib\build\opencv\lib\python3\Debug\cv2.cp36-win_amd64.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"opencv_python3.dir\Debug\cv2.cp36-win_amd64.pyd.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /TLBID:1 `

python library is  "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\libs\python36.lib" and it should be  "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\libs\python36_d.lib". When I replace python36.lib by python36_d .lib I can buidl opencv_python3 in debug 

my script to build opencv is 
```

myRepo=$(pwd)
CMAKE_CONFIG_GENERATOR="Visual Studio 15 2017 Win64"
RepoSource=opencv
cd Build/$RepoSource
CMAKE_OPTIONS='-DBUILD_opencv_world:BOOL=OFF -DBUILD_PERF_TESTS:BOOL=OFF -DBUILD_TESTS:BOOL=ON -DBUILD_DOCS:BOOL=OFF -DWITH_CUDA:BOOL=OFF -DBUILD_EXAMPLES:BOOL=ON -DWITH_LAPACK:BOOL=ON -DCV_TRACE:BOOL=OFF'
cmake -G"$CMAKE_CONFIG_GENERATOR"   \
-DTesseract_INCLUDE_DIR:PATH="${myRepo}"/Install/tesseract/include -DTesseract_LIBRARY="${myRepo}"/Install/tesseract/lib/tesseract400.lib -DLept_LIBRARY="${myRepo}"/Install/leptonica/lib/leptonica-1.74.4.lib \
-DEIGEN_DIR:PATH="$myRepo"/eigen -DEIGEN_INCLUDE_DIR="$myRepo"/eigen -DEIGEN_INCLUDE_PATH="$myRepo"/eigen \
-DCeres_DIR="$myRepo"/install/ceres-solver/cmake -Dglog_DIR:PATH="$myRepo"/install/glog/lib/cmake/glog -Dgflags_DIR:PATH="$myRepo"/install/gflags/lib/cmake/gflags \
-DLAPACK_IMPL=MKL -DMKL_ROOT_DIR:PATH="C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl" \
-DMKL_INCLUDE_DIRS:PATH="C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/include" \
-DBLAS_mkl_intel_lp64_LIBRARY:FILEPATH="C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_intel_lp64.lib" \
-DBLAS_mkl_sequential_LIBRARY:FILEPATH="C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_rt.lib" \
-DBLAS_mkl_intel_c_LIBRARY:FILEPATH="C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_core.lib" \
-DPYTHON_EXECUTABLE="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe" \
-DPYTHON3_LIBRARY="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36.lib" \
-DPYTHON3_LIBRARY_DEBUG="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36_d.lib" \
-DPYTHON3_NUMPY_INCLUDE_DIRS="C:/Users/Laurent/AppData/Roaming/Python/Python36/site-packages/numpy/core/include" \
-DPYTHON3_PACKAGES_PATH="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/Lib/site-packages" \
$CMAKE_OPTIONS -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
-DVTK_DIR:PATH="$myRepo"/install/vtk/lib/cmake/vtk-8.1 -DINSTALL_CREATE_DISTRIB=ON -DCMAKE_INSTALL_PREFIX=../../install/"$RepoSource"  ../../"$RepoSource"

cd ..

echo "************************* $Source_DIR -->devenv debug"
cmake --build $RepoSource  --config release 
echo "************************* $Source_DIR -->devenv release"
cmake --build $RepoSource  --target install --config release 
echo "************************* $Source_DIR -->devenv debug"
cmake --build $RepoSource  --config debug 
echo "************************* $Source_DIR -->devenv release"
cmake --build $RepoSource  --target install --config debug 
cd ..

```

**Comment by alalek** [comment]
> python36_d.lib

You should enable checkbox with debug library during Python installation (at least it exists for Python 3.5 installer).
CMake expects exactly that name, OpenCV is not able to control that.

**Comment by LaurentBerger** [comment]
Right problem was in my script to build opencv I remove 
```
-DPYTHON3_LIBRARY="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36.lib" \
-DPYTHON3_LIBRARY_DEBUG="C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/libs/python36_d.lib" \
```
and now I have got : 
```
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Pyt                                                                                                                            hon36_64/python.exe (found suitable version "3.6.3", minimum required is "2.7")
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Pyt                                                                                                                            hon36_64/python.exe (found suitable version "3.6.3", minimum required is "3.4")
-- Found PythonLibs: optimized;C:/Program Files (x86)/Microsoft Visual Studio/Sh                                                                                                                            ared/Python36_64/libs/python36.lib;debug;C:/Program Files (x86)/Microsoft Visual                                                                                                                             Studio/Shared/Python36_64/libs/python36_d.lib (found suitable exact version "3.                                                                                                                            6.3")

```
debug  and release project for opencv_python3 are goods
Thanks
