### ISSUE TITLE
CommandLineParser parse string arguments as literally "true" in 3.4.1

### ISSUE THREAD

**Issue by y0umu** [opencv/opencv#11658]
##### System information (version)
I can confirm this problem on both the platforms:
Linux
- OpenCV => 3.4.1
- Operating System / Platform => Fedora 28 64 Bit
- Compiler => gcc (GCC) 8.1.1 20180502 (Red Hat 8.1.1-1)

Windows
- OpenCV => 3.4.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

In short, CommandLineParser cannot parse string on the command line correctly. 
I think the "Steps to reproduce" would have a clear description on this.

BTW: **I believe this is the cause that the OpenCV apps like opencv_createsamples, opencv_annotation, opencv_traincascade will not work out of box**

##### Steps to reproduce
Minimal working file:
```
// demo.cpp
#include <opencv2/opencv.hpp>
#include <iostream>

int main(int argc, char** argv) {
    const cv::String keys = "{path p         |/the/default/path     | path to file         }";
    cv::CommandLineParser parser(argc, argv, keys);
    std::string str_path = parser.get<std::string>("path");
    std::cout << "path is " << str_path << std::endl;
    return 0;
}
```

I use this CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8)
project( demo )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( demo demo.cpp)
target_link_libraries( demo ${OpenCV_LIBS} )
```

Make:
```
cmake .
make
```

Run (demonstrating on my Linux host):
```
$ ./demo
path is /the/default/path
```
The default value is correct, but it won't parse the string I pass it through the command line at all!
```
$ ./demo -p "/home/user/images"
path is true
```
`path is true`? But `path is /home/user/images` is expected!

**Comment by alalek** [comment]
You should use '=':
```
./demo -p=/home/user/images
```

**Comment by y0umu** [comment]
My fault, sorry for that. I should have checked the documents more carefully. @alalek thank you!
