### ISSUE TITLE
imread(argv[1]) and imread(argv[1],CV_LOAD_IMAGE_ANYDEPTH) gives different channel result

### ISSUE THREAD

**Issue by kennykarnama** [opencv/opencv#11665]
##### Detailed description

channels give different result when use imread without CV_LOAD_IMAGE_ANYDEPTH option and with CV_LOAD_IMAGE_ANYDEPTH option.

##### Steps to reproduce

Mat im = imread("g:/lib/opencv/samples/data/fruits.jpg");
Mat imd = imread("g:/lib/opencv/samples/data/fruits.jpg", IMREAD_ANYDEPTH);
cout << "default value : " << im.channels();
cout << "\nIMREAD_ANYDEPTH : " << imd.channels();

where in first, give 3 channels
and the last is 1 channel

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by kennykarnama** [comment]
I have already post the question in OpenCV Q/A. But they told me to post an issue here. @alalek

**Comment by alalek** [comment]
Default imread `flags` value is IMREAD_COLOR - check [documentation](https://docs.opencv.org/3.4/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56).

This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by berak** [comment]
i still think, there's a bug here. though IMREAD_COLOR  should have been used in the 1st place, look e.g. here (same problem in imreadmulti and imdecode):
https://github.com/opencv/opencv/blob/0f298a42032798d2d83017030621fcba885a3372/modules/imgcodecs/src/loadsave.cpp#L463-L470

* it should have been: `(flags & CV_LOAD_IMAGE_ANYDEPTH) == 0`  in L463
* there is an `else` missing in L465, so whatever happens above will get overwriten.

**Comment by alalek** [comment]
"ANY_DEPTH" is 8U / 16S / 32F, it is not number of channels.

**Comment by LaurentBerger** [comment]
@alalek (Sorry for my bad english) I think label  question (invalid)  is wrong.  User @kennykarnama ask a question on http://answers.opencv.org/question/192816/imreadargv1-and-imreadargv1cv_load_image_anydepth-gives-different-channel/ @berak and me try to help user.  I think something is wrong in doc or in code. May be I'm wrong

> Default imread flags value is IMREAD_COLOR

When CV_LOAD_IMAGE_ANYDEPTH is set then imread  result is an image with only one channel

I think label should be "category: documentation"

**Comment by alalek** [comment]
`imread()` baseline is `IMREAD_GRAYSCALE=0`. Not sure that we can change this without breaking compatibility.
Did `IMREAD_COLOR | IMREAD_ANYDEPTH` work?

**Comment by LaurentBerger** [comment]
> Did IMREAD_COLOR | IMREAD_ANYDEPTH work?
Yes it works for 8 bits (fruits.jpg) results is CV_8UC3. But I 'm looking for 48bits image file to test it too.

**Comment by alalek** [comment]
> 48bits

Probably this is not supported in OpenCV at all.
Start checks from 10/16-bit TIFF images.

**Comment by LaurentBerger** [comment]
Test with 48 bits is OK: 
```
    Mat im = imread("g:/lib/opencv/samples/data/fruits.jpg");
    Mat im24;
    im.convertTo(im24, CV_16UC3, 256);
    imwrite("test.tif", im24);
    Mat im16Color = imread("test.tif", IMREAD_ANYDEPTH | IMREAD_COLOR);
    Mat im16Gray = imread("test.tif", IMREAD_ANYDEPTH);
    Mat imDefault = imread("test.tif");
    cout << "\nIMREAD_ANYDEPTH default channel : " << im16Gray.channels()<< " and Depth = "<< im16Gray.depth();
    cout << "\nIMREAD_ANYDEPTH color channel : " << im16Color.channels() << " and Depth = " << im16Color.depth();
    cout << "\nIMREAD default flag channel : " << imDefault.channels() << " and Depth = " << imDefault.depth();

```

results


```
IMREAD_ANYDEPTH default channel : 1 and Depth = 2
IMREAD_ANYDEPTH color channel : 3 and Depth = 2
IMREAD default flag channel : 3 and Depth = 0
```
