### ISSUE TITLE
The environment variable OPENCV_DOWNLOAD_PATH is ignored even when it is set

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#11663]
##### System information (version)

- OpenCV => master

##### Detailed description

See the code
https://github.com/opencv/opencv/blob/0f298a42032798d2d83017030621fcba885a3372/cmake/OpenCVDownload.cmake#L18-L21

`OPENCV_DOWNLOAD_PATH` is overwritten even if it is set in the environment variable.

**Comment by alalek** [comment]
Override doesn't work for CMake "CACHE" variables without FORCE / INTERNAL (implies FORCE) flags.
Please provide complete steps to reproduce problem.

**Comment by csukuangfj** [comment]
@alalek 
Yes, you are right.
After some test, I find that inside `CMakeVars.txt` `OPENCV_DOWNLOAD_PATH` takes
the value from the environment variable, though the current code is somehow confusing.

**Comment by alalek** [comment]
There are 3 ways to specify `OPENCV_DOWNLOAD_PATH` (prioritized in this order):
- command line: `cmake -DOPENCV_DOWNLOAD_PATH=xxx ...`
- environment: `OPENCV_DOWNLOAD_PATH=xxx cmake ...`
- default value `.cache` from script: `cmake ...`

Using environment variable should be done during the first launch of CMake only. After that, value is written into CMake's cache and will not be updated from environment anymore. Only "command line" parameter would work.

All these cases work fine as expected with correct non empty values.
