### ISSUE TITLE
copy cv::cuda::GpuMat to cv::ogl::Buffer has no effect

### ISSUE THREAD

**Issue by bigdimboom** [opencv/opencv#11660]
Opencv version: 3.4

First, the version that works:
cv::Mat cpuData(32, 32, CV32F);
populate(cpuData);
cv::ogl::Buffer vertexBuffer;
vertexBuffer.copyFrom(cpuData);
// bind vao etc...and draw, it draws vertices correctly

Next version does not work and no error/assertion avaiable
cv::Mat cpuData(32, 32, CV32F);
populate(cpuData);
cv::cuda::GpuMat gpuData;
gpuData.upload(cpuData);
cv::ogl::Buffer vertexBuffer;
vertexBuffer.copyFrom(gpuData);
// bind vao etc...and draw, opengl does not get data

// I'm also attaching with render doc
// the gpu version, vertexattribute is enabled
![image](https://user-images.githubusercontent.com/6119906/40848183-727261ba-658c-11e8-89eb-860a251e92fa.png)
// but no valid data
![image](https://user-images.githubusercontent.com/6119906/40848231-94c7801a-658c-11e8-9d5d-d8d00688e8f7.png)

// the one uploaded from cpu:
![image](https://user-images.githubusercontent.com/6119906/40848301-cc5a2988-658c-11e8-9fc6-072d8736bc22.png)

// my code screen shot:
![image](https://user-images.githubusercontent.com/6119906/40848343-e9d5c242-658c-11e8-821d-b2f3a58918a0.png)

**Comment by bigdimboom** [comment]
as it turned out opencv does not have issue in opengl/cuda module. RenderDoc has issue of interpolating Cuda code, thus giving me garbage data.

**Comment by panmengjia** [comment]
I have the same problem , don't know how to solve this issue,
    Mat dst;
    cv::ogl::Texture2D tex;
    cuda::GpuMat gpuMat;
    Mat arr = imread("/home/nvidia/Downloads/6f8473fc82bf264517fcb55e9e46ccd4.jpg");
    imshow("show",arr);
    waitKey(0);



    gpuMat.upload(arr);


    cv::namedWindow("tex",WINDOW_OPENGL);
    setOpenGlContext("tex");
    tex.bind();
    tex.copyFrom(gpuMat,true);

    imshow("tex",tex);
    waitKey(0);
//-------------------------------------------------------------------------
first imshow is normal , the effect is very well ,but second imhow which is blackj all

**Comment by panmengjia** [comment]
I have the same problem , by followed:   

    Mat dst;
    cv::ogl::Texture2D tex;
    cuda::GpuMat gpuMat;
    Mat arr = imread("/home/nvidia/Downloads/6f8473fc82bf264517fcb55e9e46ccd4.jpg");
    imshow("show",arr);
    waitKey(0);


    // 上传到gpuMat(若gpuMat不为空，会先释放原来的数据，再把新的数据上传上去)
    gpuMat.upload(arr);


    cv::namedWindow("tex",WINDOW_OPENGL);
    setOpenGlContext("tex");
    tex.bind();
    tex.copyFrom(gpuMat,true);

    imshow("tex",tex);
    waitKey(0);

the first imshow is normal which can display picture very well ,but the second imshow is black enywhere,
how to solve this problem
