### ISSUE TITLE
Directory Location of face_landmark_model.dat file ?

### ISSUE THREAD

**Issue by uday60** [opencv/opencv#11672]
I have downloaded face_landmark_model.dat file separately as i received timeout while running cmake.
Where i need to now put this file ? What is the default location of this file in terms of the directory location ?

**Comment by alalek** [comment]
Check CMakeDownloadLog.txt from build folder.

**Comment by csukuangfj** [comment]
@uday60 
See here https://github.com/opencv/opencv/issues/10825

**Comment by r734** [comment]
In my case, it downloaded to `opencv-4.2.0/build/share/opencv4/testdata/cv/face/`.
