### ISSUE TITLE
error in cv2.dnn.readNetFromTensorflow

### ISSUE THREAD

**Issue by morozovsk** [opencv/opencv#11697]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => ubuntu 17.10
- Compiler => python

##### Detailed description
I'trying to load [TF-models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) and I have errors:

ssd_mobilenet_v1_coco, ssd_mobilenet_v2_coco:
> OpenCV Error: Unspecified error (Unknown layer type Enter in op Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Enter) in populateNet, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487

ssdlite_mobilenet_v2_coco, ssd_inception_v2_coco:
>OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat) in populateNet, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487

faster_rcnn_inception_v2_coco:
>OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat_3) in populateNet, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487

##### Steps to reproduce

```python
import cv2

net = cv2.dnn.readNetFromTensorflow("ssd_mobilenet_v2_coco/frozen_inference_graph.pb")
```

**Comment by dkurt** [comment]
@morozovsk, please follow a guide https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API.

**Comment by morozovsk** [comment]
@dkurt, than you.
I used **ssd_mobilenet_v1_coco** and tested it on that image:
![objects](https://user-images.githubusercontent.com/1822063/41373643-8e6c8072-6f59-11e8-9bc2-75111c0ca8e2.jpg)
But it detects the dog as dog and as person:
![_detect_objects_by_dnn_mobilenet](https://user-images.githubusercontent.com/1822063/41373702-c28ad3d6-6f59-11e8-9b84-56460c8b01c6.png)
So I started to use **ssdlite_mobilenet_v2_coco**. I generated [a config file](https://github.com/php-opencv/php-opencv-examples/blob/master/models/ssdlite_mobilenet_v2_coco/ssdlite_mobilenet_v2_coco.pbtxt) by tf_text_graph_ssd.py and now it's working fine:
![detect_objects_by_dnn_mobilenet.png](https://raw.githubusercontent.com/php-opencv/php-opencv-examples/master/results/detect_objects_by_dnn_mobilenet.png)
Also I implemented it on [php](https://github.com/php-opencv/php-opencv-examples/blob/master/detect_objects_by_dnn_mobilenet.php).

One more time thanks for your instruction.
