### ISSUE TITLE
Missing std header

### ISSUE THREAD

**Issue by ernestmc** [opencv/opencv#11699]
https://github.com/opencv/opencv/blob/f1c5d8364f83c693a631f7b6ed659faebd85d155/modules/androidcamera/src/camera_activity.cpp#L182

`std::greater` is defined in `functionals` which is not included in this file.

Reference: http://en.cppreference.com/w/cpp/utility/functional/greater

**Comment by alalek** [comment]
"androidcamera" module support has been deprecated ~5 years ago. So it doesn't support modern Android versions.

**Comment by ernestmc** [comment]
Thanks @alalek . I'm compiling some old legacy code with the new Android Clang toolchain and found that error.

**Comment by asmorkalov** [comment]
androidcamera module has been removed from OpenCV many years ago. Closed as non-relevant.
