### ISSUE TITLE
Forward propagating tensor flow model on GPU

### ISSUE THREAD

**Issue by khaledelmadawi** [opencv/opencv#11694]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I am running my DNN on Open cv by using the "readNetFromTensorflow" module:
	tensorflow = cv::dnn::readNetFromTensorflow(model);
I set the Input by:
			tensorflow.setInput(inputTensor);
and get the inference by using  :
			cv::Mat DnnOut =tensorflow.forward();
the inference time due the size of the DNN is 60ms on CPU.
I re-compiled opencv with CUDA and OPENCL and it gives me the same inference time 60 ms, can I use OPENCL to use the resources of GPU in the inference time?

my target is 5 ms

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
