### ISSUE TITLE
OpenCV fails to compile on armeabi-v7a architechture with neon

### ISSUE THREAD

**Issue by arghyasur1991** [opencv/opencv#11693]
##### System information (version)

- OpenCV => master
- Operating System / Platform => Android armeabi-v7a
- Compiler => NDK 16.1.4479499 clang

##### Detailed description

On building opencv with the following command line options using cmake, I get build errors. I am using  armeabi-v7a as the abi_target and ANDROID_ARM_NEON as on.
```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=ON -DINSTALL_ANDROID_EXAMPLES=OFF -DANDROID_EXAMPLES_WITH_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DENABLE_CXX11=ON -DANDROID_SDK_TARGET=23 -DANDROID_NATIVE_API_LEVEL=23 -DANDROID_SDK=${ANDROID_SDK} -DANDROID_NDK=${ANDROID_NDK} -DBUILD_ANDROID_PROJECTS=OFF ..
```
This is the build error - 
```
../modules/core/include/opencv2/core/hal/intrin_neon.hpp:1325:24: error: use of undeclared identifier 'vcvt_f32_f16'
    return v_float32x4(vcvt_f32_f16(a.val));
                       ^
../modules/core/include/opencv2/core/hal/intrin_neon.hpp:1334:24: error: use of undeclared identifier 'vcvt_f16_f32'
    return v_float16x4(vcvt_f16_f32(a.val));
```

On investigation and looking into the <arm_neon.h> file at location <ndk>/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/5.0.300080/include/arm_neon.h, I see these methods are defined in the following #if block 

```
#if (__ARM_FP & 2)
#ifdef __LITTLE_ENDIAN__
__ai float16x4_t vcvt_f16_f32(float32x4_t __p0) {
  float16x4_t __ret;
  __ret = (float16x4_t) __builtin_neon_vcvt_f16_f32((int8x16_t)__p0, 8);
  return __ret;
}
#endif
#endif
```

##### Steps to reproduce
Prerequisites -
NDK v16.1.4479499

```
$ cd <opencv repo>
$ mkdir build
$ cd build
$ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=ON -DINSTALL_ANDROID_EXAMPLES=OFF -DANDROID_EXAMPLES_WITH_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DENABLE_CXX11=ON -DANDROID_SDK_TARGET=23 -DANDROID_NATIVE_API_LEVEL=23 -DANDROID_SDK=${ANDROID_SDK} -DANDROID_NDK=${ANDROID_NDK} -DBUILD_ANDROID_PROJECTS=OFF ..
$ cmake --build .
```

On documentation provided in arm website, http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0774g/chr1383660321827.html, I can see that __ARM_FP has bit 2 if single precision (32-bit) float is supported, which probably isn't the case for armeabi-v7a architechture.

**Comment by tomoaki0705** [comment]
If you are asking for help, this is not the correct place to post.
[answers.opencv.org](http://answers.opencv.org/questions/) is the place to post.
I suggest you to close this issue and post it on http://answers.opencv.org/questions/

BTW, it seems your information is missing a hyphen and having a blank in wrong place
```
-DANDROID_ABI= armeabi-v7a DANDROID_ARM_NEON=ON 
              ^ blank     ^ hyphen?
```
Are you aware of this ?

**Comment by alalek** [comment]
We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

This report has missing information about:
- cmake output (stdout) - lines about NEON and selected compiler/flags
- compiler command line flags (use `make VERBOSE=1`)
- used compiler defines like `c++ -dM -E - < /dev/null`

**Comment by arghyasur1991** [comment]
@tomoaki0705 The spaces were introduced due to copy pasting the terminal commands and I updated the post. Thanks for pointing them out

**Comment by arghyasur1991** [comment]
@alalek [cmake_op.txt](https://github.com/opencv/opencv/files/2071988/cmake_op.txt)
This is the cmake stdout output.

**Comment by alalek** [comment]
Problem 1: aarch != armv7a

> --     Target:                      Android 1 aarch64
> ...
> --     Android ABI:                 armeabi-v7a

Problem 2: Different clang versions.

> C++ Compiler:                /Users/sur/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  **(ver 3.8)**

> On investigation and looking into the <arm_neon.h> file at location /toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/**5.0.300080**/include/arm_neon.h

Where did you get this file?


I can't reproduce problem:

<details>

<summary>Linux with NDK16b</summary>

> $ cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=${NDKROOT}/build/cmake/android.toolchain.cmake ../../dev -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_ABI=armeabi-v7a -DANDROID_ARM_NEON=ON  -DINSTALL_ANDROID_EXAMPLES=ON -DANDROID_EXAMPLES_WITH_LIBS=ON

TBD via GitHub to avoid e-mail spam

</details>

**Comment by arghyasur1991** [comment]
It seems the actual issue was that I built the armeabi-v7a target over already existing arm64-v8a build folder without clearing CMakeCache.txt. Clearing it and rebuilding resolved the issue. Same build folder cannot be used for multiple targets simultaneously.

**Comment by simonprovost** [comment]
@arghyasur1991 Could you enumerate the step that you have taken for compile Opencv for ARM with NEON. Because I have met a lot of errors..

Thanks a lot advance !
