### ISSUE TITLE
stale URL for tiny-yolo-voc.weights

### ISSUE THREAD

**Issue by dzung-hoang** [opencv/opencv#11698]
##### System information (version)

- opencv_extra => master
- Operating System / Platform => All
- Compiler => All

##### Detailed description

In the file opencv_extra/testdata/dnn/download_models.py, the URL for the file tiny-yolo-voc.weights is stale. The correct URL is https://pjreddie.com/media/files/yolov2-tiny-voc.weights.

##### Steps to reproduce

```
$ cd opencv_extra/testdata/dnn
$ python download_models.py
```

**Comment by dkurt** [comment]
@dzung-hoang, Thank you! Feel free to open a pull request at https://github.com/opencv/opencv_extra.
