### ISSUE TITLE
Android build instructions appear to be out of date

### ISSUE THREAD

**Issue by mickod** [opencv/opencv#11701]
The instructions on the wiki (https://github.com/opencv/opencv/wiki/Building_OpenCV4Android_from_trunk) refer to a file cmake_android_arm.sh which does not appear to exist in the latest master.

Looking in the comment in in the code it appears the build instructions should now be:

 Android CMake toolchain file, for use with the Android NDK r5-r10d
```
#  Requires cmake 2.6.3 or newer (2.8.9 or newer is recommended).
#  See home page: https://github.com/taka-no-me/android-cmake
#
#  Usage Linux:
#   $ export ANDROID_NDK=/absolute/path/to/the/android-ndk
#   $ mkdir build && cd build
#   $ cmake -DCMAKE_TOOLCHAIN_FILE=path/to/the/android.toolchain.cmake ..
#   $ make -j8
```

Is this correct or is there something missing in my understanding?

**Comment by mickod** [comment]
@alalek - thanks for responding.

I looked at the link, which I can see is a nightly CI build 'bot'. Some quick questions on this:

- could you tell me where the build steps themselves are - I searched through various links there but could not see them?

- is there a release Android build including contrib, built as part of this CI build bot also?

Also, I didn't follow the comment about fresh information being available in "Android" issues - do you mean in the issues for openCV git repository (i.e. here) or some other place?

Once we have some answers here it would probably be worth updating the wiki above with a note that the instructions are out of date.

**Comment by alalek** [comment]
Check step "build sdk" log on [this build page](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_pack-contrib-android/builds/25).
Please note, our CI still uses very old Android NDK 10e and old Android SDK tools - due compatibility requirements and lack of free resources.
Additionally you need CMake + ninja (ninja-build) + Java SDK.

It is possible to build OpenCV with fresh Android NDK 16b, but perhaps you should switch to builtin CMake [Android toolchain file](https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake) (just reference for available options, file itself is shipped with NDK 15+).

There are no any official packages from OpenCV team with included opencv_contrib.
Nightly CI builds artifacts exist, see "upload artifacts" step (for testing purposes only, for development it is better to build binaries yourself).

"Android" issues are [here](https://github.com/opencv/opencv/labels/category%3A%20android).


Wiki page will be deprecated (probably we heed to add some header note for that pages).
