### ISSUE TITLE
Cannot read video, neither camera nor file

### ISSUE THREAD

**Issue by aimhabo** [opencv/opencv#11708]
while reading file

> Failed to query video capabilities: Inappropriate ioctl for device
> libv4l2: error getting capabilities: Inappropriate ioctl for device
> VIDEOIO ERROR: V4L: device /home/aimhabo/bilibili_download/201806-2.mp4: Unable to query number of channels

while reading camera, it exits on `cvGetCaptureProperty`

cmake with 

> General configuration for OpenCV 3.4.0 =====================================
>   Version control:               unknown
> 
>   Platform:
>     Timestamp:                   2018-04-20T13:07:46Z
>     Host:                        Linux 3.13.0-144-generic x86_64
>     CMake:                       3.5.1
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               Release
> 
>   CPU/HW features:
>     Baseline:                    SSE SSE2 SSE3
>       requested:                 SSE3
>     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
>       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
>       SSE4_1 (3 files):          + SSSE3 SSE4_1
>       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
>       FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
>       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
>       AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++ Compiler:                /usr/bin/c++  (ver 4.8.4)
>     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
>     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
>     C Compiler:                  /usr/bin/cc
>     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
>     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
>     Linker flags (Release):      
>     Linker flags (Debug):        
>     ccache:                      NO
>     Precompiled headers:         NO
>     Extra dependencies:          dl m pthread rt cudart nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/local/cuda/lib64
>     3rdparty dependencies:
> 
>   OpenCV modules:
>     To be built:                 calib3d core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev dnn features2d flann highgui imgcodecs imgproc ml objdetect photo python_bindings_generator shape stitching superres ts video videoio videostab world
>     Disabled:                    js
>     Disabled by dependency:      -
>     Unavailable:                 java python2 python3 viz
>     Applications:                tests perf_tests apps
>     Documentation:               NO
>     Non-free algorithms:         NO
> 
>   GUI: 
>     GTK+:                        YES (ver 2.24.23)
>       GThread :                  YES (ver 2.40.2)
>       GtkGlExt:                  NO
>     VTK support:                 NO
> 
>   Media I/O: 
>     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
>     JPEG:                        libjpeg (ver 90)
>     WEBP:                        build (ver encoder: 0x020e)
>     PNG:                         build (ver 1.6.34)
>     TIFF:                        build (ver 42 - 4.0.9)
>     JPEG 2000:                   build (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
> 
>   Video I/O:
>     DC1394:                      NO
>     FFMPEG:                      NO
>       avcodec:                   NO
>       avformat:                  NO
>       avutil:                    NO
>       swscale:                   NO
>       avresample:                NO
>     GStreamer:                   NO
>     libv4l/libv4l2:              1.0.1 / 1.0.1
>     v4l/v4l2:                    linux/videodev2.h
>     gPhoto2:                     NO
> 
>   Parallel framework:            pthreads
> 
>   Trace:                         YES (with Intel ITT)
> 
>   Other third-party libraries:
>     Intel IPP:                   2017.0.3 [2017.0.3]
>            at:                   /home/aimhabo/opencv-3.4.0/build/3rdparty/ippicv/ippicv_lnx
>     Intel IPP IW:                sources (2017.0.3)
>               at:                /home/aimhabo/opencv-3.4.0/build/3rdparty/ippicv/ippiw_lnx
>     Lapack:                      NO
>     Eigen:                       NO
>     Custom HAL:                  NO
> 
>   NVIDIA CUDA:                   YES (ver 9.0, CUFFT CUBLAS NVCUVID FAST_MATH)
>     NVIDIA GPU arch:             50 52
>     NVIDIA PTX archs:
> 
>   OpenCL:                        YES (no extra features)
>     Include path:                /home/aimhabo/opencv-3.4.0/3rdparty/include/opencl/1.2
>     Link libraries:              Dynamic load
> 
>   Python (for build):            /usr/bin/python2.7
> 
>   Java:
>     ant:                         NO
>     JNI:                         NO
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Matlab:                        NO
> 
>   Install to:                    /usr/local

ubuntu 14.04, opencv 3.4.0, only C program

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Also we don't provide any support for legacy C API anymore (deprecated more than 5 years ago). We have no tests for them, so more and more things would become broken.
