### ISSUE TITLE
fatal error: numpy/ndarrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#11709]
What's wrong with **numpy**?

> .../opencv/modules/python/src2/cv2.cpp:14:10: fatal error: numpy/ndarrayobject.h: No such file or directory
>  #include <numpy/ndarrayobject.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> modules/python3/CMakeFiles/opencv_python3.dir/build.make:65: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o' failed
> make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
> make[2]: Leaving directory '.../opencv/build'
> CMakeFiles/Makefile2:6364: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
> make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
> make[1]: Leaving directory '.../opencv/build'
> Makefile:165: recipe for target 'all' failed
> make: *** [all] Error 2

Cheers
Pei

**Comment by CpuID** [comment]
Same issue here, OpenCV 2.4.13.6, Ubuntu 18.04

**Comment by dkurt** [comment]
Let me close this issue. Proper bug report should contain at least CMake summary with more details about found dependencies.

BTW, try `sudo apt-get install python-numpy` as well.

**Comment by omercevdet3842** [comment]
i try it also with sudo apt-get install pyhton-numpy ,installed 1.16.3 version .
but i keep getting the same error "/home/omar/opencv-master/modules/python/src2/cv2.cpp:33:10: fatal error: numpy/ndarrayobject.h: No such file or directory
 #include <numpy/ndarrayobject.h> "
my system properties : UBUNTU 18.04 |OpenCV 4.5.2

**Comment by qiang92** [comment]
“sudo apt-get install python-numpy” solve this issue.
