### ISSUE TITLE
Missing constants from python bindings CV_HAAR_DO_CANNY_PRUNING, CV_HAAR_SCALE_IMAGE, ...

### ISSUE THREAD

**Issue by mjscosta** [opencv/opencv#11716]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => ubuntu 16.04, via conda.
- Compiler => gcc

##### Detailed description

Porting an application from opencv 2.4 to 3.4, and the constants 

cv2.cv.CV_HAAR_DO_CANNY_PRUNING
cv2.cv.CV_HAAR_SCALE_IMAGE
cv2.cv.CV_HAAR_FIND_BIGGEST_OBJECT
cv2.cv.CV_HAAR_DO_ROUGH_SEARCH

seem to be missing from opencv3.
##### Steps to reproduce

start python interpreter:
```
>>> import cv2
>>> cv2.CV_HAAR_DO_CANNY_PRUNING
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'CV_HAAR_DO_CANNY_PRUNING'

```

This issue addressed this same question #4603 , but was closed with no answer or with the wrong answer, not addressing the mentioned constants.

The constants are present in the C++ API:
https://docs.opencv.org/3.4.1/d9/d31/group__objdetect__c.html

**Comment by mjscosta** [comment]
Thanks for the reply, so the response would be the constants from 2.4 were replaced in 3.x by:

cv2.cv.CV_HAAR_DO_CANNY_PRUNING,  replace by cv2.CASCADE_DO_CANNY_PRUNING
cv2.cv.CV_HAAR_SCALE_IMAGE, by cv2.CASCADE_SCALE_IMAGE
cv2.cv.CV_HAAR_FIND_BIGGEST_OBJECT,  by cv2.CASCADE_FIND_BIGGEST_OBJECT
cv2.cv.CV_HAAR_DO_ROUGH_SEARCH, by cv2.CASCADE_DO_ROUGH_SEARCH

**Comment by HerreraAlegria** [comment]
Thank you. It works for me:  cv2.CV_HAAR_DO_CANNY_PRUNING, replace by cv2.CASCADE_DO_CANNY_PRUNING
In RaspBerry pi 4 ( Rasbian)
