### ISSUE TITLE
Assertion failed in opencv resize

### ISSUE THREAD

**Issue by gnthibault** [opencv/opencv#11712]
##### System information (version)
- Python => Python 3.5.2
- OpenCV => 3.1
- bindings: opencv-python-3.4.1.15
- Operating System / Platform => Ubuntun 16.04

##### Detailed description
I use python bindings, and for large sizes, cv2.resize has a failed assertion.
It appeared that opencv crashed if the product of the x and y output size is greater that 2**31. Probably an int 32 that overflows and turns into a negative number.

The bug existed for input size, and has been fixed a while ago, but the same kind of bugs remains for the output size. Indeed, if I specify a ratio of 0.5 for instance, it does not crash

OpenCV(3.4.1) Error: Assertion failed (dsize.area() > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4050
Traceback (most recent call last):
  File "./testcv2.py", line 6, in <module>
    image = cv2.resize(img, (0,0), fx=1, fy=1, interpolation=cv2.INTER_CUBIC)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/resize.cpp:4050: error: (-215) dsize.area() > 0 in function resize

##### Steps to reproduce

```
import cv2
import numpy as np
img = np.zeros((46341,46341))
image = cv2.resize(img, (0,0), fx=1, fy=1, interpolation=cv2.INTER_CUBIC)
```

**Comment by gnthibault** [comment]
The previous bug was here:
https://github.com/opencv/opencv/issues/5191

And it was fixed here:
https://github.com/opencv/opencv/pull/6883/commits/5bc10ef796c29563e8916ff31b5c1a262422a93f

But one can see that the dsize.area() has not been fixed as it should have, in order to be consistent with the ssize.area()

**Comment by alalek** [comment]
Feel free to prepare PR to 3.4 branch (bug fix patch should go to current maintenance branch).

Also it is better to avoid `dst.area() > 0` conditions - `!dst.empty()` method should work fine for that.

**Comment by gnthibault** [comment]
PR: https://github.com/opencv/opencv/pull/11722
I ran the tests on my computer, one test did not ran:

[----------] 1 test from Core_globbing
[ RUN      ] Core_globbing.accuracy
/home/gnthibault/projects/opencv/modules/core/test/test_io.cpp:552: Failure
Expected: (lenas.size()) > (pngLenas.size()), actual: 0 vs 0
[  FAILED  ] Core_globbing.accuracy (57 ms)

But it was not running on the previous commit either (1187a7fa345b98b49d366fb6f8857486168f636f) so I think the PR is ok

**Comment by alalek** [comment]
Test data is required from opencv_extra repository - specify environment variable before test launch:
```
OPENCV_TEST_DATA_PATH=<opencv_extra>/testdata
```

**Comment by gnthibault** [comment]
Ok, I am going to test that as soon as possible

**Comment by berak** [comment]
@gnthibault , note, that you can run tests selectively, like:

    test_core --gtest_filter=Core_globbing.accuracy

and you probably do not need the *whole* opencv_extra repository (which is a huge download), just the resp. folder with the images you need (in the right place, ofc., so it can find it)

**Comment by cagridz** [comment]
If there are any different type of files like .xml and .jpg, It will be happen . Use  just same type extension in file
