### ISSUE TITLE
Opencv 4.0 - can not load file created by opencv 3.X

### ISSUE THREAD

**Issue by pi-null-mezon** [opencv/opencv#11724]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Windows 64 Bit

##### Detailed description

I have found incompatibility of FileStorage output between Opencv 4 and 3. Pictures attached below will be more verbose than thousand of words.

##### Steps to reproduce

This piece of code:
```.cpp
    // Writes the a list of given items to a cv::FileStorage.
template<typename _Tp>
inline void writeFileNodeList(cv::FileStorage& fs, const cv::String& name,
                              const std::vector<_Tp>& items) {
    // typedefs
    typedef typename std::vector<_Tp>::const_iterator constVecIterator;
    // write the elements in item to fs
    fs << name << "[";
    for (constVecIterator it = items.begin(); it != items.end(); ++it) {
        fs << *it;
    }
    fs << "]";
}
```
in opencv versions 3.X produces:
![3](https://user-images.githubusercontent.com/5991537/41159376-0523a1a6-6b35-11e8-9263-fb28f69b44fb.png)

but in new prerelease opencv 4.0.0 (last snapshot of master branch at 08.06.2018) produces:
![4](https://user-images.githubusercontent.com/5991537/41159389-0dd460d8-6b35-11e8-85c5-a9a923048679.png)

So, this "my_object:" is not necessary and looks pretty ugly in my humble opinion. But most necessary is that this "my_object" brakes all attempts to load resources that has been created in v.3.x.

**Comment by alalek** [comment]
"my_object" is an algorithm name (by default).

Probably it was changed during 3.x series. Try the latest 3.4 code.

There are no guidelines/support for versioning of storage files, so don't try to migrate these files between OpenCV versions.
