### ISSUE TITLE
NormalBayesClassifier save/load problems (solved)

### ISSUE THREAD

**Issue by L-Simmon** [opencv/opencv#11744]
##### System information (version)

- OpenCV => :3.3
- Operating System / Platform => :win7 64 bit
- Compiler => :VS 2013

##### Detailed description

I trained a  NormalBayesClassifier and use "save()" to save the classfiler to a "xml"/"yml" file, then I used the "load()” to load the file and used "predict()" to get an error.
If I did not save the files, just train and predict, It works.
I think the "load()" function has a bug.

##### Steps to reproduce
    ```.cpp
    // C++ code example
	float trainingData[8][3] = { { 6, 180, 12 }, { 5.92, 190, 11 }, { 5.58, 170, 12 }, { 5.92, 165, 10 },
	{ 5, 100, 6 }, { 5.5, 150, 8 }, { 5.42, 130, 7 }, { 5.75, 150, 9 } };
	Mat trainingDataMat(8, 3, CV_32FC1, trainingData);

	float responses[8] = { 1,1,1,1,-1,-1,-1,-1 };
	Mat responsesMat(8, 1, CV_32SC1, responses);

	Ptr<ml::NormalBayesClassifier> bayes = ml::NormalBayesClassifier::create();
	Ptr<ml::TrainData> traindata = ml::TrainData::create(trainingDataMat, ml::ROW_SAMPLE, responsesMat);
	cout << "start training..." << endl;
	bayes->train(traindata);
	cout << "end" << endl;
	bayes->save("little_bayes.yml");

	float testData[1][3] = { { 5, 175, 11 } };
	Mat testDataMat(1, 3, CV_32FC1, testData);
	cout << bayes->predict(testDataMat) << endl;


	Ptr<ml::NormalBayesClassifier> bayes2 = ml::NormalBayesClassifier::create();
	bayes2->load("little_bayes.yml");
	cout << bayes2->getVarCount() << endl;
	cout << bayes2->predict(testDataMat) << endl;
    ```

**Comment by berak** [comment]
no, not a bug, but a usage error.

     Ptr<ml::NormalBayesClassifier> bayes2 = ml::NormalBayesClassifier::create();
     bayes2->load("little_bayes.yml");

[load()](https://docs.opencv.org/master/d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html#a147a2579967d89637f0434c261bfb1e0) is a *static* function, which will return a *new* object. it won't initialize the one you called it on.

you'll have to use:

    Ptr<ml::NormalBayesClassifier> bayes2 = ml::NormalBayesClassifier::load("little_bayes.yml");

**Comment by L-Simmon** [comment]
@berak , Thank you for your detailed answer，It is a usage error. I do not know how to close the issue, so I changed the title.
