### ISSUE TITLE
dnn (yolo) detection not accurate as original Yolo

### ISSUE THREAD

**Issue by 1901453301** [opencv/opencv#11741]
Hi:
   The new version 3.4.1 is awesome for the fast dnn speed.  

   However when I use the dnn(and load yolo weight and cfg). It's not as accurate as original Yolo version.  I doubt it's due to the optimization dnn has made.  The yolo I am using is tiny yolo.  I test on a video, and save the detection frame. In some frame the result is just missing. 

  Could anyone help?

**Comment by dkurt** [comment]
@1901453301, please use http://answers.opencv.org for questions or provide ways to reproduce: OpenCV version, references to files, code to run a model, resulting images from OpenCV/Darknet.
