### ISSUE TITLE
Android ABI Issue

### ISSUE THREAD

**Issue by aboozaid** [opencv/opencv#11750]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 64BIT
- Compiler => Ming

##### Detailed description

Hello,
I'm wondering if anyone uses OpenCV with android and tries to add an extra module from OpenCV Contrib library, Do you face a problem with ABI Supported (X86 - X86_64 - arm64 are not found )

##### Result

![opencv](https://user-images.githubusercontent.com/30879096/41296739-dc315e74-6e5d-11e8-88af-31e8f6c84fb9.png)

**Comment by alalek** [comment]
These values are just a hints for cmake-gui. Use command line cmake to specify required values.

**Comment by asmorkalov** [comment]
OpenCV contains out-of-date instance of android.toolchain.cmake. It's recommended to use the corresponding toolchain file provided by NDK in `/ndk/<version>/build/cmake`
