### ISSUE TITLE
Using Facemark Python API 4.0.0 - pre, bad allocation while fitting the model.

### ISSUE THREAD

**Issue by krshrimali** [opencv/opencv#11752]
##### System information (version)

- OpenCV => 4.0.0 - pre
- Operating System / Platform => Ubuntu 18.04

##### Detailed description

I'm trying to implement FacemarkLBF testing version in Python (OpenCV Version : 4.0.0 - pre), but there is not enough documentation on it. Addition to that, when am trying to run, it shows _std::bad alloc error_. 

Gist of the functions am using:

`code = cv2.face.createFacemarkLBF()`
`cv2.face_Facemark.loadModel(obj, <model_name>)`
`retVal, landmarks = cv2.face_Facemark.fit(obj, img, faces)`

While trying to debug, the problem is mainly with roi.getObj() line in fit function definition (https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/facemarkLBF.cpp : 376 line), which doesn't work because of which when faces[i] is accessed, there's an error of bad allocation.

Any solutions / comments on this, please?

**Comment by alalek** [comment]
This is wrong place for opencv_contrib issues.
Link: https://github.com/opencv/opencv_contrib/issues

**Comment by krshrimali** [comment]
Sorry, picked the wrong place by fault. Thanks!
