### ISSUE TITLE
Opencv 4, new build, imshow crashes with error.

### ISSUE THREAD

**Issue by antithing** [opencv/opencv#11753]
##### System information (version)

OpenCX 4, built yesterday from latest branch 
Windows 10, Cuda 9.1

##### Detailed description

In a brand new project, this code:

```
cv::Mat img = cv::imread("D:/filmBack.jpg");
	cout << img.rows << endl;
	cv::imshow("efef", img);
	cv::waitKey(1);
```

Crashes with the error:

1080
```
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.0-pre) Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file D:\thirdParty\opencv_340\opencv-master\opencv-master\modules\highgui\src\window.cpp, line 632

```

If I comment out the imshow, it runs fine.

in cmake, GTK seems to be missing as an option.

Has the build requirements changed with the 4 release?

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

This is not a crash, this is a regular C++ exception that your application missed to catch.
Message states that your OpenCV build doesn't support GUI functionality.

On Windows you should have these status lines in CMake:
```
--   GUI: 
--     Win32 UI:                    YES
```

Cleanup your build directory and try again. Win32 GUI is enabled by default on Windows.
