### ISSUE TITLE
contourArea does not produce a correct number

### ISSUE THREAD

**Issue by wagenrace** [opencv/opencv#11765]
##### System information (version)

- OpenCV => 3.3.1 (python)
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

I had created 2 boxes both with an area of 500.000 pixels but with different dimensions. Using OpenCV findContours I got the contours, but calculating the area of these boxes resulted in 49551 and 49401.
The contours where correctly detected.

The first contour is 200 by 250 and gives a result of 49.551 (199 * 249?).

The second contour is 100 by 500 and gives a result of 49.401 (99 * 499?)

My hypothesis is the (upper or bottom) and (left  or right) border is not taken in to account.

##### Steps to reproduce
`import cv2
import numpy as np

contour1 = np.array([[[  0,   0]],
                     [[  0, 199]],
                     [[249, 199]],
                     [[249,   0]]], dtype=np.int32)

contour2 = np.array([[[  0,   0]],
                     [[  0, 99]],
                     [[499, 99]],
                     [[499,   0]]], dtype=np.int32)

print("contour 1, 200 by 250 has size", cv2.contourArea(contour1))
print("contour 2, 100 by 500 has size", cv2.contourArea(contour2))`

###### PS
- I do not know if the problem is also present in C++
- The number is close to the correct answer but becomes a problem with smaller contours (a 10x10 square is off by 19%)

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

BTW, how do you want to represent rectangle 1x1 as input ?

**Comment by wagenrace** [comment]
Why isn't this a bug? An outcome of a function what is not correct is a bug not a question, right?

represent a rectangle 1x1 should be a single pixels. What for some reason gives a correct output of 1

**Comment by alalek** [comment]
Next rectangle is 0.5x0.5 . Contour points are ... ?

**Comment by wagenrace** [comment]
0.25, it can not be drawn

**Comment by wagenrace** [comment]
Sorry, I get know why this is a question. My mistake, was not counting correctly

**Comment by wagenrace** [comment]
Sorry my mistake. I interpreted the contour incorrectly:

It is not point A TILL point B. But all pixels IN BETWEEN point A and B
