### ISSUE TITLE
Make error with opencv-master and opencv_contrib on windows 10

### ISSUE THREAD

**Issue by Korel** [opencv/opencv#11769]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Win10 64bit
- Compiler => Qt - mingw32

##### Detailed description

Hello,

I am relatively a new user of opencv and for SIFT function I tried to recompile with opencv_contrib. I used cmake gui for generating. I unmarked WITH_CUDA since it gave a warning. Below is the error I get from the compiler. I am uploading the cmd output and I also pasted it to pastebin. I hope someone can help with the error.  Thank you everybody.

https://pastebin.com/wpPhFFES
[cmdcopy.txt](https://github.com/opencv/opencv/files/2102885/cmdcopy.txt)

##### Steps to reproduce
C:\opencv-build>mingw32-make -j

**Comment by alalek** [comment]
> mingw32

We don't support MinGW on Windows. Recommended way is using MSVC compiler.

Try to ask this build / usage questions on Users OpenCV Q/A forum: http://answers.opencv.org
