### ISSUE TITLE
wrong seamlessClone assertion？

### ISSUE THREAD

**Issue by grantlj** [opencv/opencv#11771]
In the seamless_cloning.cpp (https://github.com/opencv/opencv/blob/master/modules/photo/src/seamless_cloning.cpp) 
the line 94 asserts: 
 **CV_Assert(minxd >= 0 && minyd >= 0 && maxxd <= dest.rows && maxyd <= dest.cols);**
Why the maxxd is compared with dest.rows instead of dest.cols? (Also, the maxyd is compared with dest.cols). 
I think the maxxd is on the width (col) direction, while the maxyd is on the height direction (row) direction.

Hence, it should be changed into:
CV_Assert(minxd >= 0 && minyd >= 0 && maxxd <= dest.cols && maxyd <= dest.rows);

**Comment by alalek** [comment]
Right!

PR #11208 changed meaning of variables, but doesn't update check condition.

Perhaps this check can be removed at all, because it is redundant - `dest(roi_d)` operation has similar check inside.
