### ISSUE TITLE
error  VideoCapture read()  is None 

### ISSUE THREAD

**Issue by zxfzqf** [opencv/opencv#11782]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Windows 10  64 Bit 
- Compiler => opencv for python 3.6, not know Compiler 

##### Detailed description
 I use VideoCapture.get(cv2.CAP_PROP_FRAME_COUNT) get frame count is 89,
but use VideoCapture.read()  Can only read frame number is 84, when read index is 85 frame is False.
[The input file is here](https://raw.githubusercontent.com/zxfzqf/file_repository/master/094053180618b22e81e37551.mp4) 
##### Steps to reproduce
 ```
    import cv2
    video_path = 'test.mp4'
    capture = cv2.VideoCapture(video_path)
    if not capture.isOpened():  
        raise IOError('cant parser video file!')
    frame_count = capture.get(cv2.CAP_PROP_FRAME_COUNT)
    print(frame_count) # frame_count is 99
    count = 0
    while True:
        flag = count
        r, im = capture.read()
        if not r:
            print(count) # count is 94
            break
        count += 1
    capture.release()
 ```

**Comment by alalek** [comment]
Provided information is not enough (no input file, no OpenCV build information - including enabled video APIs).

> OpenCV => 3.6
> opencv for python

Wrong version. Unknown build configurations. No luck to reproduce this.

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by zxfzqf** [comment]
First, thank you
The version error has been corrected. But input file may not be available because it can not be uploaded to the Internet. Can only see if there are people who have encountered the same problem
I tried to create user http://answers.opencv.org, but after filling it up, I still showed: This field is required., unable to create user.
so ......

**Comment by zxfzqf** [comment]
The company is not allowed to upload，I try to create some data that can reproduce the problem and upload it to this
 thx

**Comment by alalek** [comment]
FFmpeg shows warning that file is corrupted:
> Invalid data found when processing input

Details are on GitHub (to prevent email spam).

**Comment by zxfzqf** [comment]
I thought the file was good.
Sorry I didn't find the file was corrupt, wasting your time
@alalek  This is very helpful to me， thx

**Comment by zxfzqf** [comment]
@bit1002lst  python? ，If you want to try to get all the frames，you can try the package sk-video.I am doing this for the time being.

**Comment by bit1002lst** [comment]
yes, python
sk-video will load all frames to a matrix, but the memory is limited.
