### ISSUE TITLE
Issue with VideoCapture when open an unavailable camera by index, the isOpen() funtction return true

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#11780]
##### System information (version)

- OpenCV =>4.00
- Operating System / Platform =>Windows 64 Bit
- Compiler =>Visual Studio 2017

##### Detailed description

I have compiled the OpenCV from source, but when I want to check how many USB or integrated cameras are available in the current machine. Before the `isOpen()` function returns `false ` when this index camera is not present so we I can stop the loop, but now `isOpen()` function still returns `true` even the camera is not present in the machine.

**Comment by LaurentBerger** [comment]
I canot reproduce your issue with this code (in debug or release ) : 
```

    {
        int n = 28;
        VideoCapture v(n);
        if (v.isOpened())
            cout << n << " is opened\n";
        else
            cout << n << " cannot be opened\n";

    }

```
> [ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); MSMF(990); VFW(980); DSHOW(970); CV_IMAGES(960); CV_MJPEG(950)
> 28 cannot be opened
> 

VS 2017 opencv 4.0-pre windows 10 64 bits

**Comment by alalek** [comment]
Try to run app with `OPENCV_VIDEOIO_DEBUG=1 OPENCV_LOG_LEVEL=INFO` environment variables to collect more information about this case.

**Comment by Bahramudin** [comment]
@LaurentBerger   when I want to run this code:

int idx = 0;
int total = 0;
cv::VideoCapture capture;
while (true)  {
    capture.open(idx++);
    if(capture.isOpen())  {
        capture.release(); 
        total++;
    } else {
        break; // never break
    }
}

The loop never ends, before it was OK.

**Comment by Bleach665** [comment]
Also cant reproduce this.
opencv - 64f2b1b  + contrib modules
Windows 10 Enterprise N 2016 LTSB 10.0.14393 Build 14393
VS 2017 15.7.3
CMake - 3.11.4.

**Comment by LaurentBerger** [comment]
@Bahramudin No problem for me with     

    int idx = 0;
    int total = 0;
    cv::VideoCapture capture;
    while (true) {
        capture.open(idx++);
        if (capture.isOpened()) { // NOT isOpen
            capture.release();
            total++;
        }
        else {
            break; // never break
        }
    }

**Comment by terfendail** [comment]
@Bahramudin Could you please check whether #11836 will fix your issue?

**Comment by Bahramudin** [comment]
@terfendail The problem still exists in the previous build, but I am waiting for next build after few days to check whether the problem has been gone.

**Comment by tovornik** [comment]
Hello. 
This my be a little off topic but anyway.
Although my code is working, I've been getting similar infos/warnings and I just want to know if there's a way to stop them from displaying in the console. 
Thanks
