### ISSUE TITLE
OpenCL target is not supported with current OpenCL device

### ISSUE THREAD

**Issue by scp-sjrim** [opencv/opencv#11786]
Hello I have a problem.

[ INFO:0] Initialize OpenCL runtime...
OpenCL is enabled
[ INFO:1] VIDEOIO: Enabled backends(5, sorted by priority): FFMPEG(1000); GSTREAMER(990); V4L2(980); CV_IMAGES(970); CV_MJPEG(960)
[ INFO:1] Successfully initialized OpenCL cache directory: /home/sj/.cache/opencv/4.0.0-pre/opencl_cache/
[ INFO:1] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_1050--384_130
[ WARN:1] DNN: OpenCL target is not supported with current OpenCL device (tested with Intel GPUs only), switching to CPU.

I don't know why Opencl can't use.

Nvidia doesn't supported opencl???

Opencv 4.0.0-pre
ubuntu 16.04
 NVIDIA_Corporation--GeForce_GTX_1050

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
