### ISSUE TITLE
Caffe models run faster then Tensorflow ?? 

### ISSUE THREAD

**Issue by LORANDITSUM** [opencv/opencv#11783]
I am trying to run different object detection models using the sample "example_dnn_object_detection" provided by the OpenCV 3.4 git hub. Using the readNet() function to load and read both caffe and Tensorflow models. 

Are caffe based network implementation faster then tensorflow?  while running the caffe implementation from https://github.com/chuanqi305/MobileNet-SSD i get and average inference time of 20 ms. 

while running their tensorflow counter part (https://github.com/tensorflow/models/tree/master/research/object_detection)  runs 30 ms. 

Also there seem to be no difference between mobile net V1 and V2 although they report V2 should be 30% faster. Is there any reason why caffe models be faster than tensorflow ones? 

- OpenCV => 3.4
- Operating System / Platform => Ubuntu 16.4

**Comment by dkurt** [comment]
> I am trying to run different object detection models

This is an answer. They are different networks which even solve different problems. MobileNet-SSD from Caffe detects objects from 20 classes but MobileNet-SSDs from TenosrFlow for 90 classes.

> Also there seem to be no difference between mobile net V1 and V2 although they report V2 should be 30% faster.

Please provide sources of such kind of information. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md shows that speeds of `ssd_mobilenet_v1_coco` and `ssd_mobilenet_v2_coco` are pretty similar (30ms vs 31ms). Do you mean `ssdlite_mobilenet_v2_coco` (27ms)?

**Comment by LORANDITSUM** [comment]
Yes, thank you so much!
