### ISSUE TITLE
Got an error when tried to capture from Usb camera

### ISSUE THREAD

**Issue by nvnnghia** [opencv/opencv#11796]
##### System information (version)

- OpenCV => 3.4.1.14
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Python 3.6

##### Detailed description
I run this code to test the usb camera:
`cap = cv2.VideoCapture(0)

while True:

    ret, image = cap.read()

    if not ret:

        break

    cv2.imshow("test", image)

    cv2.waitKey(1)`

When I run this code, It can only capture the first frame from the camera, but the frame is black. It can not capture from the second frame. This code worked perfectly if I use a video file instead.

**Comment by alalek** [comment]
> 3.4.1.14

There is no such version in this repository.
You are using non-official package, so please use proper place to report issue and provide more details - at least getBuildInformation() and information about your camera.
