### ISSUE TITLE
module 'cv2.dnn' has no attribute 'DNN_BACKEND_OPENCV'

### ISSUE THREAD

**Issue by aaronchen98** [opencv/opencv#11803]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Mac

##### Detailed description

I want to try YOLOv3 with opencv in python, and i copy https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py to my mac and run it, but

```
AttributeError: module 'cv2.dnn' has no attribute 'DNN_BACKEND_OPENCV'
```

```
 ~  pkg-config --modversion opencv
3.4.1
 ~  pip list
opencv-python   3.4.1.15
```

So what should i do?

BTW, I'm a rookie. 😭

**Comment by alalek** [comment]
> 3.4.1
> master/samples

You have incompatible code bases. There is nothing to fix in OpenCV.

**Comment by Mundanee** [comment]
Try to uninstall opencv-python
pip uninstall opencv-python
