### ISSUE TITLE
loading Tensorflow pretrained model with openCV

### ISSUE THREAD

**Issue by ArezooNazer** [opencv/opencv#11805]
I trained Inception V3  on 

- ubuntu 16.04
- openCV 3.3.1
- python 3.5 

and as a result I have these 3 output files :

1. classify_image_graph_def.pb (the trained model)
2. imagenet_2012_challenge_label_map_proto.pbtxt
3. imagenet_synset_to_human_label_map.txt

I'm using the exact code of [this post](https://www.pyimagesearch.com/2017/09/18/real-time-object-detection-with-deep-learning-and-opencv/) but instead of Cafe model I used Tensorflow like this:

`net = cv2.dnn.readNetFromTensorflow( classify_image_graph_def.pb , imagenet_2012_challenge_label_map_proto.pbtxt )`
But it gave this error :

> [INFO] loading model...
> [libprotobuf ERROR /home/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 3:7: Message type "tensorflow.GraphDef" has no field named "entry".
> OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: /media/imagenet/imagenet_2012_challenge_label_map_proto.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file /home/opencv/modules/dnn/src/tensorflow/tf_io.cpp, line 72
> Traceback (most recent call last):
>   File "real_time_object_detection.py", line 38, in <module>
>     net = cv2.dnn.readNetFromTensorflow( args["model"],args["prototxt"])
> cv2.error: /home/opencv/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: /media/imagenet/imagenet_2012_challenge_label_map_proto.pbtxt in function ReadTFNetParamsFromTextFileOrDie
> 

any ideas to resolve this error or how deploy my Tensorflow model for detecting objects on video?
this is my code:
[real_time_object_detection.zip](https://github.com/opencv/opencv/files/2124182/real_time_object_detection.zip)

**Comment by berak** [comment]
* 3.3.1 is *very* old.

* if your pbtxt file [looks like this](https://github.com/atong01/Imagenet-Tensorflow/blob/master/model/imagenet_2012_challenge_label_map_proto.pbtxt) , then, it's for sure the wrong one.

* `classify_image_graph_def.pb` sounds more like a classification, not a detection network (while you're trying to use *detection* code)

**Comment by dkurt** [comment]
@ArezooNazer, `.pbtxt` is optional. Have you tried to load a model without it? And please use the latest OpenCV state.

**Comment by berak** [comment]
the correct *detection* pbtxt file [would look similar to this](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_inception_v2_coco_2017_11_17.pbtxt) (coco, not imagenet, but you get the idea. it's a textual graph description, while yours has class labels only)

**Comment by dkurt** [comment]
@ArezooNazer, this issue was solved many times. In example, try this solution: http://answers.opencv.org/question/175699/readnetfromtensorflow-fails-on-retrained-nn/. In short words, you need to remove DecodeJpeg from your graph.

**Comment by ArezooNazer** [comment]
Thanks, it really helped!

**Comment by giorgiomondauto** [comment]
> @ArezooNazer, `.pbtxt` is optional. Have you tried to load a model without it? And please use the latest OpenCV state.
> 
> Also it may help you: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

But in the link you provided, the config file does not seem to be optional
