### ISSUE TITLE
NMSBoxes for rotated rectangles in Python

### ISSUE THREAD

**Issue by vishwesh5** [opencv/opencv#11800]
Hi!

This is regarding the `NMSBoxes` implementation in C++ and in Python. I noticed that there are two different implementations of `NMSBoxes` in C++ : one for rectangles and one for rotated rectangles (reference: [nms.cpp](https://github.com/opencv/opencv/blob/db88cd1b255ddf21034f18f6488b0b599c59bf9a/modules/dnn/src/nms.cpp)), whereas in Python there is only one implementation available for `NMSBoxes` (it only takes bounding boxes as input argument).

When I try to replicate the `text_detection.cpp` sample available in **`samples/dnn/`** in Python, I am getting a very low number of indices maybe because I am passing a simple rectangle instead of a rotated rectangle. Similarly, when I find the bounding box of the rotated rectangle and pass it to `NMSBoxes` function, the results are worse than earlier. The scripts and the results using C++ and Python script (with simple rectangles) are available [here](https://github.com/vishwesh5/Text-Detection-DNN).

Is there any specific reason why rotated rectangles are not available in Python? And am I right in assuming that this is the reason because of high variation in results? 

I am using the latest OpenCV, opencv_contrib (using git) and Python 3.6.

Thanks

Vishwesh

**Comment by berak** [comment]
hi @vishwesh5 

> Is there any specific reason why rotated rectangles are not available in Python? 

current cv2 knows about `RotatedRect`, but not about `vector<RotatedRect>` (which is needed here)

while this would be [easy to patch for python](https://github.com/opencv/opencv/compare/3.4...berak:python_vec_rotated_rect?expand=1)  (given, you use the latest 3.4 branch) , unfortunately, doing the same for java would require significantly more work (like writing a `MatOfRotatedRect` class from scratch), i'm a bit hesitant to do this (looks like adding a lot of clutter for a rarely used thing).

**Comment by vishwesh5** [comment]
Hi berak!
First of all, thanks for taking out time to reply to the post. Can I request you to take a look at [this github repository](https://github.com/vishwesh5/Text-Detection-DNN)? I have tried to create a rotated rectangle class similar to the one that is being used in C++ in the similar code. I can understand that this is not the best solution, but am I on the correct path?
Thanks

**Comment by berak** [comment]
the current python wrapper for NMSBoxes only accepts a list of `Rect` in the form `[x,y,w,h]`
but you can try the mentioned patch, which adds support for `vector<RotatedRect>` 
(needs a rebuild from src, though)

**Comment by vishwesh5** [comment]
Ahh! Thanks I will look into it. I will close the thread :) Thank you for the help @berak

**Comment by mhaghighat** [comment]
@vishwesh5:
Do you mean `[ [top, left, width, height] ]` ? Because both `left` and `right` are on **x** axis and the box will be ambigous on the **y**.

**Comment by vishwesh5** [comment]
Hi @mhaghighat 
I agree with you and I can't understand why I wrote that :stuck_out_tongue:
Let me check and get back to you
