### ISSUE TITLE
Videocapture error while reading from camera using backend  (i.e. Ffmpeg, Gstreamer, Direct Show)

### ISSUE THREAD

**Issue by rashikcs** [opencv/opencv#11806]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Ubutu 64bit
- Compiler => g++ -std=c++11

##### Detailed description
**compile with GDB.**

(process:24917): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
ERROR! Unable to open camera
[Thread 0x7fffc5ec2700 (LWP 24921) exited]
[Inferior 1 (process 24917) exited with code 0377]

**compile the videocapture_basic.cpp file using the following command.**

`OPENCV_LOG_LEVEL=DEBUG OPENCV_VIDEOIO_DEBUG=1 ./output`

[ INFO:0] VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); V4L2(980); CV_IMAGES(970); CV_MJPEG(960); FIREWIRE(950); GPHOTO2(940)
[ WARN:0] VIDEOIO(createGStreamerCapture(filename)): trying ...

(video_stream:17022): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
[ WARN:0] VIDEOIO(createGStreamerCapture(filename)): result=(nil) isOpened=-1 ...

terminate called after throwing an instance of 'char const*'
Aborted (core dumped)

##### Steps to reproduce

**After compiling the sample code in file opencv/samples/cpp/videocapture_basic.cpp changing line 28 and executing the output file getting the error**

`int apiID = cv::CAP_GSTREAMER`

**Comment by alalek** [comment]
Run your program under gdb:
```
OPENCV_LOG_LEVEL=DEBUG OPENCV_VIDEOIO_DEBUG=1 gdb --args ./output
```

Here is how to capture stack traces on exceptions throwing via GDB: https://stackoverflow.com/a/26695274
We need the last one list before "terminate called after throwing an instance of 'char const*'"

**Comment by rashikcs** [comment]
Here is the output of **"OPENCV_LOG_LEVEL=DEBUG OPENCV_VIDEOIO_DEBUG=1 gdb --args ./output"**

```
Reading symbols from ./output...(no debugging symbols found)...done.
(gdb) set pagination off
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>backtrace
>continue
>end
(gdb) run
Starting program: /home/codemen/Documents/CPU/videocapture_basic_custom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffc5ec2700 (LWP 29606)]
[ INFO:0] VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); V4L2(980); CV_IMAGES(970); CV_MJPEG(960); FIREWIRE(950); GPHOTO2(940)
[ WARN:0] VIDEOIO(cvCreateFileCapture_FFMPEG_proxy(filename)): trying ...

Invalid UE golomb code
Invalid UE golomb code
Invalid UE golomb code
[New Thread 0x7fffc56c1700 (LWP 29608)]
[New Thread 0x7fffc4ec0700 (LWP 29609)]
[New Thread 0x7fffc46bf700 (LWP 29610)]
[New Thread 0x7fffc3ebe700 (LWP 29611)]
[New Thread 0x7fffc36bd700 (LWP 29612)]
[New Thread 0x7fffc2ebc700 (LWP 29613)]
[New Thread 0x7fffc26bb700 (LWP 29614)]
[New Thread 0x7fffc1eba700 (LWP 29615)]
[New Thread 0x7fffc16b9700 (LWP 29616)]
[New Thread 0x7fffc0eb8700 (LWP 29617)]
[New Thread 0x7fffc06b7700 (LWP 29618)]
[New Thread 0x7fffbfeb6700 (LWP 29619)]
[ WARN:0] VIDEOIO(cvCreateFileCapture_FFMPEG_proxy(filename)): result=0x61ac50 isOpened=1 ...

[Thread 0x7fffc56c1700 (LWP 29608) exited]
[Thread 0x7fffc4ec0700 (LWP 29609) exited]
[Thread 0x7fffc3ebe700 (LWP 29611) exited]
[Thread 0x7fffc36bd700 (LWP 29612) exited]
[Thread 0x7fffc46bf700 (LWP 29610) exited]
[Thread 0x7fffc2ebc700 (LWP 29613) exited]
[Thread 0x7fffc1eba700 (LWP 29615) exited]
[Thread 0x7fffc26bb700 (LWP 29614) exited]
[Thread 0x7fffc16b9700 (LWP 29616) exited]
[Thread 0x7fffc0eb8700 (LWP 29617) exited]
[Thread 0x7fffc06b7700 (LWP 29618) exited]
[Thread 0x7fffbfeb6700 (LWP 29619) exited]
[ WARN:0] VIDEOIO(createGStreamerCapture(index)): trying ...


(process:29602): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
[ WARN:0] VIDEOIO(createGStreamerCapture(index)): result=(nil) isOpened=-1 ...

[ WARN:0] VIDEOIO(cvCreateCameraCapture_V4L(index)): trying ...

VIDEOIO ERROR: V4L: can't open camera by index 0
[ WARN:0] VIDEOIO(cvCreateCameraCapture_V4L(index)): result=(nil) ...

[ WARN:0] VIDEOIO(cvCreateCameraCapture_DC1394_2(index)): trying ...

[ WARN:0] VIDEOIO(cvCreateCameraCapture_DC1394_2(index)): result=(nil) ...

[ WARN:0] VIDEOIO(createGPhoto2Capture(index)): trying ...

[ WARN:0] VIDEOIO(createGPhoto2Capture(index)): result=(nil) isOpened=-1 ...

ERROR! Unable to open camera
[Thread 0x7fffc5ec2700 (LWP 29606) exited]
[Inferior 1 (process 29602) exited with code 0377]
(gdb) 

```

**Comment by alalek** [comment]
There are two completely different outputs (from issue description and "under gdb"). It is hart to say that is wrong, but looks like OpenCV V4L backend can't open your camera.

Try to do these checks:
- your Linux user has proper rights to `/dev/video<N>` nodes (`video` group or similar): `id`. Also you may check this by running test from the root user.
- camera is properly detected: `v4l2-ctl --list-devices`
- other software is able to work with camera
    * Google Chrome:  camera settings or some site with using of your web camera
    * VLC: `vlc -vvv v4l2:///dev/video0`
    * FFmpeg via V4L: `ffmpeg -f video4linux2 -s 1280x720 -i /dev/video0 -r 15 -vcodec libx264 -y cam.mkv` (or ffplay)

**Comment by rashikcs** [comment]
**Okay, Can access the camera now after updating "libv4l" lib using following command.**

`sudo apt-get install libv4l-dev`

**Working perfectly if the following line doesn't change. However  API ID is changed to any specific one this following error occurs.**

`int apiID = cv::CAP_ANY;`


```
(gdb) set pagination off
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>backtrace
>continue
>end
(gdb) run
Starting program: /home/codemen/Documents/CPU/videocapture_basic_custom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffc5ec2700 (LWP 30190)]
[ INFO:0] VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); V4L2(980); CV_IMAGES(970); CV_MJPEG(960); FIREWIRE(950); GPHOTO2(940)

Thread 1 "videocapture_ba" received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
```
**Thank you for the co-operation.**

**Comment by azkahariz** [comment]
I think because your camera device input not in there. Just try in terminal `ls /dev'. There is a `video0` or `video1` etc. Use your option.

**Comment by alalek** [comment]
> received signal SIGSEGV, Segmentation fault

Run gdb's "bt" command after that to dump stack trace.

> apt-get install libv4l-dev

Support for libv4l has been removed in OpenCV 4.x (using V4L2 API directly through `ioctl()`). So these changes are ignored.
