### ISSUE TITLE
opencv-3.3.1 install error in centos7 

### ISSUE THREAD

**Issue by hulin12138** [opencv/opencv#11802]
##### System information (version)

- OpenCV => :3.3.1
- Operating System / Platform => :CentOS 7
- Compiler => :gcc

##### Detailed description

when I make the project, there are errors as follows:
/home/opencv-3.3.1/modules/videoio/src/cap_dc1394_v2.cpp:58:27: fatel error：dc1394/dc1394.h：No that file or directory.

**Comment by alalek** [comment]
Try to build from scratch (clean build directory) - looks like it is configuration error.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
