### ISSUE TITLE
test opencl failed when loop 

### ISSUE THREAD

**Issue by hujunyao** [opencv/opencv#11818]
I using following test code:

```
int test_canny_opencl()
{

   ocl::Device default_device = ocl::Device::getDefault();
   cout << "Used device: " << default_device.name() << "\n";

    double t1, t2;
    Mat image;
    image = imread("F:/testOpenCL/IMG_0003.JPG",IMREAD_GRAYSCALE);   // Read the file
   
    UMat u = image.getUMat(ACCESS_FAST);
    UMat v;

    // calculating time with OpenCL
    cv::ocl::setUseOpenCL(true);
    t1 = (double)getTickCount();
    for (int i = 0; i < 100; i++)
    {
        cv::Canny(u, v, 100, 50);
    }

    t2 = ((double)getTickCount() - t1)/getTickFrequency();

    cout << "Running time with OpenCL: " << t2 << endl;
}
```
when the loop ( i< 100) is too big ( >37, maybe related to gpu memory), the code will hang.
Is it a bug , or I use the wrong code? 
I think the loop exhaust gpu memories.
the system is: Win10
gpu: intel graphics hd 630 
cpu:  i7-7700HQ
compiler:  mingw64  i686-7.3.0-release-posix-sjlj-rt_v5-rev0

**Comment by alalek** [comment]
Most of OpenCL calls are asynchronous - job is queued and processed in "background" mode.
So provided code sample doesn't look valid - it just queue tasks, but doesn't fetch results (it least this make no sense to measure time for performance metrics).

Refer to OpenCV performance tests code.
