### ISSUE TITLE
Opencv Can invoked the LSTM network model ?

### ISSUE THREAD

**Issue by wuyiwywy** [opencv/opencv#11823]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
cv2.error: OpenCV(3.4.1) D:\Build\OpenCV\opencv-3.4.1\modules\dnn\src\dnn.cpp:417: error: (-215) inputs.size() == requiredOutputs in function cv::dnn::experimental_dnn_v4::DataLayer::getMemoryShapes

##### Steps to reproduce
I tried to call the LSTM model using the opencv.dnn module, and the above error occurred.This model is used for Minst data set classification. I changed the category to 28 to ensure that the input and output sizes are consistent

import cv2 as cv
import numpy as np

net = cv.dnn.readNetFromTensorflow("./lstm.pb")

img = cv.imread("test.png")
n_img = cv.cvtColor(img, cv.COLOR_BGRA2GRAY)
n_img = cv.resize(n_img,(28, 28))
n_img = np.reshape(n_img, [1, 28, 28])
net.setInput(n_img)
out = net.forward("output")

**Comment by dkurt** [comment]
@wuyiwywy, provide information which is enough to reproduce your problem. For usage questions please use http://answers.opencv.org
