### ISSUE TITLE
calcHist() threw an assert. It seems false.

### ISSUE THREAD

**Issue by neppie66** [opencv/opencv#11821]
When I tried calcHist() such as following,

```
	const Mat images[]{ image };
	Mat histogram = Mat::zeros(Size(width * height, 1), CV_16U);
	const int channelsArray[]{ image.channels() };
	const int histSize[]{ height * width };
	const float range[]{ 0, 65535 };
	const float* ranges[]{ range };

	// Create histogram
	calcHist(images, 1, channelsArray, noArray(), histogram, 1, histSize, ranges);

```
Then I caught an exception.

I tried to analyze and found that "histPrepareImages", which is invoked from calcHist, has the following implementation.

```
            for( j = 0; j < nimages; c -= images[j].channels(), j++ )
                if( c < images[j].channels() )
                    break;
            CV_Assert( j < nimages );

```
(lines 149 - 152 in histogram.cpp)
If nimages is 1, at least j is incremented once then j=1 on CV_Assert.

I think CV_Assert should be (j <= nimages)...

**Comment by tomoaki0705** [comment]
Usually, usage question should go to http://answers.opencv.org/questions/
BTW, looking at the code, ```CV_Assert``` looks fine for me.
The code MUST arrive to ```break``` and since you didn't, assertion was raised.

**Comment by neppie66** [comment]
On my case, the code did not arrive to `break` because initially `c` equals to `image[0].channels()` and `nimage` is 1.
I am getting afraid I might use wrong argument. I will look at the reference again. Even if it does not help to solve the problem, I will visit the Q&A site.
Once close this issue. Thanks.
