### ISSUE TITLE
shufflenet 

### ISSUE THREAD

**Issue by huang229** [opencv/opencv#11838]
When shufflenet is tested, an interruption is produced(forward("prob");). Hope to get your help.

cv::Mat faceBigImg = vecFaceImg[kk];
cv::Mat prob;
Mat inputBlob = cv::dnn::blobFromImage(faceBigImg, 1.0f, Size(), Scalar(), false);
CV_TRACE_REGION("forward");
net.setInput(inputBlob, "data");
prob = net.forward("prob");

**Comment by dkurt** [comment]
@huang229, Please use http://answers.opencv.org to ask questions. This is a bugs and issues tracker.
