### ISSUE TITLE
`DESTDIR=/abspath make install` installs to wrong directory

### ISSUE THREAD

**Issue by timotheecour** [opencv/opencv#11833]
```
git clone https://github.com/opencv/opencv
cd opencv
mkdir build
cd build
pwd
#prints: /Users/username/opencv/build
python ../platforms/js/build_js.py . --build_wasm
DESTDIR=/tmp/build make install
```
this builds under /tmp/build/Users/username/opencv/build/install/{lib,include,...}
instead of /tmp/build/usr/local/{lib,include,...}
(eg that'd be the behavior of other software like libjpeg)

NOTE: this is independent building via ../platforms/js/build_js.py, would've been same with standard build followed by `DESTDIR=/tmp/build make install`

**Comment by tomoaki0705** [comment]
If you are asking for help, this is not the correct place to post.
[answers.opencv.org](http://answers.opencv.org/questions/) is the place to post.
I suggest you to close this issue and post it on http://answers.opencv.org/questions/

**Comment by tomoaki0705** [comment]
Well, if you consider as a bug, the information is tooooo few.

Your environment (compiler, OS, etc..), build Log, and more.

From my point of view, OpenCV install location is decided on ```CMake``` stage, not on ```make``` stage, so what you are expecting will not happen, and this seems an expected behavior.
Are there any documents about ```DESTDIR``` you are specifying?

**Comment by timotheecour** [comment]
> From my point of view, OpenCV install location is decided on CMake stage, not on make stage, so what you are expecting will not happen, and this seems an expected behavior.
> Are there any documents about DESTDIR you are specifying?

https://www.gnu.org/prep/standards/html_node/DESTDIR.html 7.2.4 DESTDIR: Support for Staged Installs
> make DESTDIR=/tmp/stage install
> If your installation step would normally install /usr/local/bin/foo and /usr/local/lib/libfoo.a, then an installation invoked as in the example above would install /tmp/stage/usr/local/bin/foo and /tmp/stage/usr/local/lib/libfoo.a instead.

See also https://stackoverflow.com/questions/11307465/destdir-and-prefix-of-make
> make install DESTDIR=/usr/local/stow/foo
> would install binaries in /usr/local/stow/foo/usr/local/bin

I'm on OSX 10.13.5 but shouldn't matter.

**Comment by tomoaki0705** [comment]
@timotheecour , I'm asking for a document **from** OpenCV which describes ```DESTDIR```, not stackoverflow nor GNU page.
A.F.A.I.K., ```DESTDIR``` approach is not supported in OpenCV

**Comment by timotheecour** [comment]
feel free to close it as WONTFIX but it's too bad opencv doesn't support DESTDIR; most software building via `make` (whether via cmake or autotools etc) support DESTDIR.

**Comment by tomoaki0705** [comment]
You are welcome to write a PR to support the ```DESTDIR```
BTW, I cannot close the issue. Please close it by your self.

**Comment by alalek** [comment]
Please don't make duplicates of the same/similar problems.
Lets track "install" problem of JavaScript here: #11832

**Comment by timotheecour** [comment]
@alalek : some additional piece of info: I was under impression this bug was not specific to javascript build but it is:

```
mkdir build && cd build
cmake ..
make -j8
DESTDIR=/tmp/d20_opencv make install
```
gives:
....

`-- Installing: /tmp/d20_opencv/usr/local/bin/opencv_version`

which is correct. So the bug only affects build_js.py

**Comment by alalek** [comment]
Please refer to CMake documentation about `DESTDIR` support via "make" files.
Usually it is done via `CMAKE_INSTALL_PREFIX` variable.

**Comment by timotheecour** [comment]
I know that, but the point of DESTDIR is to allow flexibility by splitting install (fast) from building (slow), so we can build once (slow) and install in more than one location, especially useful for staged installs or install to a temp location (eg to see what will get installed or experiment on produced bin/lib outputs before actually installing to default locations, without having to re-run slow build).

CMAKE_INSTALL_PREFIX doesn't allow that flexibility, as it ties destination location before build.

**Comment by alalek** [comment]
> to allow flexibility by splitting install (fast) from building (slow)

CMake rerun with new `CMAKE_INSTALL_PREFIX` and run `make install` is quite fast with minimal rebuilds from the same `build` folder.

Again, refer to CMake documentation. It has "tools" to solve your problem with minimal time penalty (your way just don't work with CMake - native `install` tool is almost not used):
```
cmake -DCMAKE_INSTALL_PREFIX=/tmp/test1 -P cmake_install.cmake
cmake -DCMAKE_INSTALL_PREFIX=/tmp/test2 -P cmake_install.cmake
```
These commands are showed during `VERBOSE=1 make install` execution.

**Comment by timotheecour** [comment]
Thanks! `cmake -DCMAKE_INSTALL_PREFIX=/tmp/test1 -P cmake_install.cmake` solved my problem

> Again, refer to CMake documentation

hmmm, that led to https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html which points to DESTDIR, not where you saw `CMAKE_INSTALL_PREFIX` mentioned within the context of reusing an existing build directory 
https://stackoverflow.com/questions/25669919/what-is-cmake-install-cmake says "You don't use cmake_install.cmake directly" so looks like it's meant to be an internal command launched by make install.

In any case, your solution works, so thanks :)
