### ISSUE TITLE
org.opencv.core.CvException

### ISSUE THREAD

**Issue by qinhongfei** [opencv/opencv#11845]
CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/imgproc/src/imgwarp.cpp:3484: error: (-215) dsize.area() > 0 || (inv_scale_x > 0 && inv_scale_y > 0) in function void cv::resize(cv::InputArray, cv::OutputArray, cv::Size, double, double, int)
]

**Comment by qinhongfei** [comment]
I This bug doesn't appear all the time, it will appear random

**Comment by alalek** [comment]
This message says that you call `cv::resize()` with incorrect input parameters.
It is not OpenCV bug, you need to debug your program.
