### ISSUE TITLE
access weights for ANN MLP in opencv 3.x

### ISSUE THREAD

**Issue by gwuillou** [opencv/opencv#11843]
- OpenCV => 3.4
- Operating System / Platform => mac os
- Language => c++ 
- Compiler => clang

##### Detailed description

We have upgrated our opencv from version 2 to 3 (finally). We are using ANN_MLP classe. In the version 2, there was the possibility to set the weight of the different layers: weights[0]= ...
In the version 3.4, we did not find the way to set the weights. Is there however a way to set the weights?

**Comment by berak** [comment]
it may not be obvious, but you can retrieve the weights like:

    Mat w = mdl->getWeights(1); // 1st hidden layer

and, since cv::Mat is basically a smartpointer (this is a shallow copy, only the Mat header is copied here), 
you can change the content:

    w.at<double>(1,1) = 1.2;
