### ISSUE TITLE
OpenCV 3.4.1 with CUDA 8.0.44 ld issue

### ISSUE THREAD

**Issue by Papipone** [opencv/opencv#11864]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Debian Stretch
- Compiler => GCC 6.3.0 and GCC 4.9.2

##### Detailed description

I am unable to compile `opencv_test_cudev`. I am using `GCC 4.9.2` as `CUDA_HOST_COMPILER` since `NVCC 8.0.44` does not support `GCC 6`. I am also setting the `CUDA_NVCC_FLAGS` to `-ccbin gcc-4.9` without any success. The linker complains.

##### Steps to reproduce

Here is my configuration :

> Looking for ccache - not found
> Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.8", minimum required is "1.2.3") 
> Could NOT find Jasper (missing:  JASPER_LIBRARIES JASPER_INCLUDE_DIR) 
> Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
> Looking for linux/videodev.h
> Looking for linux/videodev.h - not found
> Looking for linux/videodev2.h
> Looking for linux/videodev2.h - found
> Looking for sys/videoio.h
> Looking for sys/videoio.h - not found
> Checking for module 'libavresample'
>   No package 'libavresample' found
> Checking for module 'libgphoto2'
>   No package 'libgphoto2' found
> Found TBB (env): /usr/lib/x86_64-linux-gnu/libtbb.so
> found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
> at: /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/build/3rdparty/ippicv/ippicv_lnx
> found Intel IPP IW sources: 2017.0.3
> at: /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/build/3rdparty/ippicv/ippiw_lnx
> CUDA detected: 8.0
> CUDA NVCC target flags: -ccbin gcc-4.9;-gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-D_FORCE_INLINES
> Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
> Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
> Could NOT find Atlas (missing:  Atlas_CBLAS_INCLUDE_DIR Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY) 
> A library with BLAS API not found. Please specify library location.
> LAPACK requires BLAS
> A library with LAPACK API not found. Please specify library location.
> Found apache ant: /usr/bin/ant (1.9.9)
> Could NOT find JNI (missing:  JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
> VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
> Caffe:   NO
> Protobuf:   NO
> Glog:   NO
> Looking for tiny_dnn.h
> Looking for tiny_dnn.h - found
> Found tiny-dnn in: /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/build/3rdparty/tinydnn/tiny-dnn-1.0.0a3
> The protocol buffer compiler is not found (PROTOBUF_PROTOC_EXECUTABLE='')
> freetype2:   YES
> harfbuzz:    YES
> Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
> CMake Warning at /home/hadi/Desktop/opencv-3.4.1/opencv_contrib-3.4.1/opencv_contrib-3.4.1/modules/matlab/CMakeLists.txt:54 (message):
>   A required dependency of the matlab module (Python Jinja2 package) was not
>   found (installation command: "pip install jinja2").  Disabling Matlab
>   bindings...
> 
> 
> Module opencv_ovis disabled because OGRE3D was not found
> No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
> Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
> Failed to find gflags - Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
> Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
> Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
> Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
> freetype2:   YES
> harfbuzz:    YES
> Checking for modules 'tesseract;lept'
>   No package 'tesseract' found
>   No package 'lept' found
> Tesseract:   NO
> 
> General configuration for OpenCV 3.4.1 =====================================
>   Version control:               unknown
> 
>   Extra modules:
>     Location (extra):            /home/hadi/Desktop/opencv-3.4.1/opencv_contrib-3.4.1/opencv_contrib-3.4.1/modules
>     Version control (extra):     unknown
> 
>   Platform:
>     Timestamp:                   2018-07-01T18:09:10Z
>     Host:                        Linux 4.9.0-6-amd64 x86_64
>     CMake:                       3.7.2
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               Release
> 
>   CPU/HW features:
>     Baseline:                    SSE SSE2 SSE3
>       requested:                 SSE3
>     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
>       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
>       SSE4_1 (3 files):          + SSSE3 SSE4_1
>       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
>       FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
>       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
>       AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
>       AVX512_SKX (1 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_SKX
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++11:                       YES
>     C++ Compiler:                /usr/bin/c++  (ver 6.3.0)
>     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
>     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
>     C Compiler:                  /usr/bin/cc
>     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
>     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
>     Linker flags (Release):      
>     Linker flags (Debug):        
>     ccache:                      NO
>     Precompiled headers:         YES
>     Extra dependencies:          dl m pthread rt /usr/lib/x86_64-linux-gnu/libtbb.so cudart nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/lib/x86_64-linux-gnu
>     3rdparty dependencies:
> 
>   OpenCV modules:
>     To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv datasets dnn dnn_objdetect dpm face features2d flann freetype fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 python3 python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
>     Disabled:                    js world
>     Disabled by dependency:      -
>     Unavailable:                 cnn_3dobj dnn_modern hdf java matlab ovis sfm viz
>     Applications:                tests perf_tests apps
>     Documentation:               NO
>     Non-free algorithms:         NO
> 
>   GUI: 
>     QT:                          YES (ver 5.9.5)
>       QT OpenGL support:         NO
>     GTK+:                        NO
>     VTK support:                 NO
> 
>   Media I/O: 
>     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
>     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
>     WEBP:                        build (ver encoder: 0x020e)
>     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.28)
>     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.8)
>     JPEG 2000:                   build (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
> 
>   Video I/O:
>     DC1394:                      YES (ver 2.2.5)
>     FFMPEG:                      YES
>       avcodec:                   YES (ver 57.64.101)
>       avformat:                  YES (ver 57.56.101)
>       avutil:                    YES (ver 55.34.101)
>       swscale:                   YES (ver 4.2.100)
>       avresample:                NO
>     GStreamer:                   
>       base:                      YES (ver 1.10.4)
>       video:                     YES (ver 1.10.4)
>       app:                       YES (ver 1.10.4)
>       riff:                      YES (ver 1.10.4)
>       pbutils:                   YES (ver 1.10.4)
>     libv4l/libv4l2:              NO
>     v4l/v4l2:                    linux/videodev2.h
>     gPhoto2:                     NO
> 
>   Parallel framework:            TBB (ver 4.3 interface 8006)
> 
>   Trace:                         YES (with Intel ITT)
> 
>   Other third-party libraries:
>     Intel IPP:                   2017.0.3 [2017.0.3]
>            at:                   /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/build/3rdparty/ippicv/ippicv_lnx
>     Intel IPP IW:                sources (2017.0.3)
>               at:                /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/build/3rdparty/ippicv/ippiw_lnx
>     Lapack:                      NO
>     Eigen:                       NO
>     Custom HAL:                  NO
>     Protobuf:                    build (3.5.1)
> 
>   NVIDIA CUDA:                   YES (ver 8.0, CUFFT CUBLAS NVCUVID)
>     NVIDIA GPU arch:             20 30 35 37 50 52 60 61
>     NVIDIA PTX archs:
> 
>   OpenCL:                        YES (no extra features)
>     Include path:                /home/hadi/Desktop/opencv-3.4.1/opencv-3.4.1/3rdparty/include/opencl/1.2
>     Link libraries:              Dynamic load
> 
>   Python 2:
>     Interpreter:                 /usr/bin/python2.7 (ver 2.7.13)
>     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.13)
>     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.12.1)
>     packages path:               lib/python2.7/dist-packages
> 
>   Python 3:
>     Interpreter:                 /usr/bin/python3 (ver 3.5.3)
>     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.5m.so (ver 3.5.3)
>     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.12.1)
>     packages path:               lib/python3.5/dist-packages
> 
>   Python (for build):            /usr/bin/python2.7
> 
>   Java:                          
>     ant:                         /usr/bin/ant (ver 1.9.9)
>     JNI:                         NO
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Matlab:       
> 
>                  YES
>     mex:                         /usr/local/MATLAB/R2017b/bin/mex
>     Compiler/generator:          Not working (bindings will not be generated)
> 
>   Install to:                    /usr/local

> -----------------------------------------------------------------

Here is my configuration script (cmake-gui):

[CMakeCache.txt](https://github.com/opencv/opencv/files/2153340/CMakeCache.txt)

And the error produced: 

> hadi@debian:~/Desktop/opencv-3.4.1/opencv-3.4.1/build$ make
> [  0%] Built target gen-pkgconfig
> [  5%] Built target libwebp
> [  6%] Built target libjasper
> [  9%] Built target IlmImf
> [ 10%] Built target ippiw
> [ 13%] Built target libprotobuf
> [ 13%] Built target ittnotify
> [ 13%] Built target opencv_cudev
> [ 13%] Built target opencv_ts_pch_dephelp
> [ 13%] Built target pch_Generate_opencv_ts
> [ 13%] Built target opencv_core_pch_dephelp
> [ 13%] Built target pch_Generate_opencv_core
> [ 13%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
> [ 13%] Linking CXX shared library ../../lib/libopencv_core.so
> [ 16%] Built target opencv_core
> [ 16%] Built target opencv_imgproc_pch_dephelp
> [ 16%] Built target pch_Generate_opencv_imgproc
> [ 16%] Linking CXX shared library ../../lib/libopencv_imgproc.so
> [ 19%] Built target opencv_imgproc
> [ 19%] Built target opencv_imgcodecs_pch_dephelp
> [ 19%] Built target pch_Generate_opencv_imgcodecs
> [ 19%] Linking CXX shared library ../../lib/libopencv_imgcodecs.so
> [ 20%] Built target opencv_imgcodecs
> [ 20%] Built target opencv_videoio_pch_dephelp
> [ 20%] Built target pch_Generate_opencv_videoio
> [ 20%] Linking CXX shared library ../../lib/libopencv_videoio.so
> [ 20%] Built target opencv_videoio
> [ 20%] Built target opencv_highgui_pch_dephelp
> [ 20%] Built target pch_Generate_opencv_highgui
> [ 20%] Linking CXX shared library ../../lib/libopencv_highgui.so
> [ 20%] Built target opencv_highgui
> [ 21%] Built target opencv_ts
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_transpose.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_arithm_func.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_arithm_op.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_bitwize_op.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_cmp_op.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_color_cvt.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_cvt.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_deriv.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_integral.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_lut.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_pyramids.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_reduction.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_split_merge.cu.o
> [ 21%] Building NVCC (Device) object modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_warp.cu.o
> [ 21%] Linking CXX executable ../../../bin/opencv_test_cudev
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_arithm_func.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_arithm_op.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_bitwize_op.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_cmp_op.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_color_cvt.cu.o: relocation R_X86_64_32 against `.rodata._ZZN24CvtColor_BGR_to_RGB_Test8TestBodyEvE24__cv_trace_location_fn85' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_cvt.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_deriv.cu.o: relocation R_X86_64_32 against `.rodata._ZZN19Sobel_Accuracy_Test8TestBodyEvE24__cv_trace_location_fn51' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_integral.cu.o: relocation R_X86_64_32 against `.rodata._ZZN17Integral__8u_Test8TestBodyEvE24__cv_trace_location_fn51' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_lut.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_pyramids.cu.o: relocation R_X86_64_32 against `.rodata._ZZN18PyrDown__8uc1_Test8TestBodyEvE24__cv_trace_location_fn51' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_reduction.cu.o: relocation R_X86_64_32 against `.rodata._ZZN15Sum_GpuMat_Test8TestBodyEvE24__cv_trace_location_fn51' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_split_merge.cu.o: relocation R_X86_64_32S against `.bss._ZL20__cudaFatCubinHandle' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_test_warp.cu.o: relocation R_X86_64_32 against `.rodata._ZZN19Resize_Upscale_Test8TestBodyEvE25__cv_trace_location_fn136' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: CMakeFiles/opencv_test_cudev.dir/opencv_test_cudev_generated_transpose.cu.o: relocation R_X86_64_32 against `.rodata._ZZN20Transpose__8uc1_Test8TestBodyEvE24__cv_trace_location_fn51' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/build.make:5760: recipe for target 'bin/opencv_test_cudev' failed
> make[2]: *** [bin/opencv_test_cudev] Error 1
> CMakeFiles/Makefile2:2582: recipe for target 'modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/all' failed
> make[1]: *** [modules/cudev/test/CMakeFiles/opencv_test_cudev.dir/all] Error 2
> Makefile:160: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by xugaoxiang** [comment]
Same error while building 3.4.1 with CUDA 9.0.

**Comment by Papipone** [comment]
@xugaoxiang I think the only option for us is to use an older version of GCC for building the whole thing.

**Comment by alalek** [comment]
Closing this because it can't be fixed in OpenCV.

You need to install and specify compatible compiler for your CUDA SDK via `CUDA_HOST_COMPILER` CMake variable (like gcc-5 for CUDA 8.0).
