### ISSUE TITLE
https certificate for answers.opencv.org Q&A site?

### ISSUE THREAD

**Issue by rob3c** [opencv/opencv#11863]
I'm trying to connect to https://answers.opencv.org for a secure login, but it only seems to be available via http. I see the docs site supports https as well as opencv.org more generally, but it's not clear how the Q&A site subdomain fits into the project overall.

Is this just a misconfiguration that should be tracked here, or is that site handled separately somewhere else?

**Comment by mshabunin** [comment]
Implemented
