### ISSUE TITLE
Error in building OpenCV 

### ISSUE THREAD

**Issue by Rasoul20sh** [opencv/opencv#11870]
Hi, 
I am trying to build OpenCV  (with contribe modules and cuda enabled) from scratch. I do this job more than ten times and I used it successfully but this time there is an error I do not recognize it. 
In the building section with visual studio I see **about 100 errors like this one**:

**>LINK : fatal error LNK1104: cannot open file '..\..\lib\Debug\opencv_imgproc330d.lib'**

the steps of my building are:
1- Download OpenCV source files.
2- Download OpenCV_Contrib
3- Copy contrib modules to the source one.
4- Config and generate with CMake GUI.
5- Build with Visual studio 2015

I try it with different OpenCV versions, but there is no difference...
Thanks a lot

##### System information (version)
- OpenCV =>  3.0 , 3.3 , 3.41
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Rasoul20sh** [comment]
Please help me alalek, I build it several times before and there were non of these errors. Is there any problem with cuda version (cuda_9.0.176_win10) or Operating system (win 10)?
