### ISSUE TITLE
Error in "Mul" layer when loading TF model

### ISSUE THREAD

**Issue by AMotyko** [opencv/opencv#11886]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I saved TF model in pb file and can successfully load it with tensorflow.

I try to load that model with DNN module:
`Net net = dnn::readNetFromTensorflow(model_pb,model_pbtxt)` 
And get the following error 
OpenCV(3.4.1-dev) Error: Assertion failed (scaleMat.type() == (((5) & ((1 << 3)
- 1)) + (((1)-1) << 3))) in cv::dnn::experimental_dnn_v4::`anonymous-namespace':
:TFImporter::populateNet, file E:\opencv-3.4\modules\dnn\src\tensorfl
ow\tf_importer.cpp, line 1231

I understand, that this errors appears when parsing this layer 

node {
  name: "up_sampling2d_3/mul"
  op: "Mul"
  input: "up_sampling2d_3/strided_slice"
  input: "up_sampling2d_3/Const"
}
I attach the pbtxt file.
Thank you for helping!
[model_1.txt](https://github.com/opencv/opencv/files/2160406/model_1.txt)

**Comment by dkurt** [comment]
@AMotyko, May I ask you to show how you define a `tf.resize_nearest_neighbor` layer? Especially output shape.

**Comment by AMotyko** [comment]
Actually the code is written in Keras and I have model.h5 file of trained model. I can load this model in Keras and get prediction. Then I convert this h5 file to pb with standart script. And then try to load it in OpenCV.

**Comment by dkurt** [comment]
@AMotyko, No, thanks. I just wanted to see the code. I think I can reproduce it in Keras, thanks!

**Comment by AMotyko** [comment]
OK, thank you! This is two files with the net architecture (i changed .py to .txt). I got them from repository: https://github.com/huoyijie/AdvancedEAST

[advanced_east.txt](https://github.com/opencv/opencv/files/2160857/advanced_east.txt)
[network.txt](https://github.com/opencv/opencv/files/2160858/network.txt)

**Comment by AMotyko** [comment]
As I understand, the problem is in UpSampling2D layer. If I'll simply change it to ZeroPadding2D - the model will pass through loader. But is it possible to somehow manage with UpSampling2D layer?

**Comment by dkurt** [comment]
@AMotyko, please check a PR https://github.com/opencv/opencv/pull/11890.

**Comment by AMotyko** [comment]
Thank you very much! Now everything is fine!

**Comment by wulouzhu** [comment]
@AMotyko 
Hi, I am doing the same thing as you. Could you please show me how to transform the h5 file to pb file and how to load the pb file with opencv? Thank you very very very much!

**Comment by wulouzhu** [comment]
I haved solved it.
