### ISSUE TITLE
Linking CXX executable ../../bin/opencv_test_videostab collect2: error:

### ISSUE THREAD

**Issue by shan4224** [opencv/opencv#11887]
In opencv installation, while executing make -j1 , I am getting the following error . Please advise

deeplearning@deep-learning-virtual-machine:~/opencv/build$ make -j1
Built target gen-pkgconfig
Built target libwebp
Built target IlmImf
Built target ippiw
Built target ittnotify
Built target libprotobuf
Built target opencv_core_pch_dephelp
Built target pch_Generate_opencv_core
Built target opencv_core
Built target opencv_perf_core_pch_dephelp
Built target opencv_test_core_pch_dephelp
Built target opencv_ts_pch_dephelp
Built target pch_Generate_opencv_ts
Built target opencv_imgproc_pch_dephelp
Built target pch_Generate_opencv_imgproc
Built target opencv_imgproc
Built target opencv_imgcodecs_pch_dephelp
Built target pch_Generate_opencv_imgcodecs
Built target opencv_imgcodecs
Built target opencv_videoio_pch_dephelp
Built target pch_Generate_opencv_videoio
Built target opencv_videoio
Built target opencv_highgui_pch_dephelp
Built target pch_Generate_opencv_highgui
Built target opencv_highgui
Built target opencv_ts
Built target pch_Generate_opencv_test_core
Built target opencv_test_core
Built target pch_Generate_opencv_perf_core
Built target opencv_perf_core
Built target opencv_flann_pch_dephelp
Built target pch_Generate_opencv_flann
Built target opencv_flann
Built target opencv_test_flann_pch_dephelp
Built target pch_Generate_opencv_test_flann
Built target opencv_test_flann
Built target opencv_test_imgproc_pch_dephelp
Built target pch_Generate_opencv_test_imgproc
Built target opencv_test_imgproc
Built target opencv_perf_imgproc_pch_dephelp
Built target pch_Generate_opencv_perf_imgproc
Built target opencv_perf_imgproc
Built target opencv_ml_pch_dephelp
Built target pch_Generate_opencv_ml
Built target opencv_ml
Built target opencv_test_ml_pch_dephelp
Built target pch_Generate_opencv_test_ml
Built target opencv_test_ml
Built target opencv_objdetect_pch_dephelp
Built target pch_Generate_opencv_objdetect
Built target opencv_objdetect
Built target opencv_test_objdetect_pch_dephelp
Built target pch_Generate_opencv_test_objdetect
Built target opencv_test_objdetect
Built target opencv_perf_objdetect_pch_dephelp
Built target pch_Generate_opencv_perf_objdetect
Built target opencv_perf_objdetect
Built target opencv_phase_unwrapping_pch_dephelp
Built target pch_Generate_opencv_phase_unwrapping
Built target opencv_phase_unwrapping
Built target opencv_test_phase_unwrapping_pch_dephelp
Built target pch_Generate_opencv_test_phase_unwrapping
Built target opencv_test_phase_unwrapping
Built target example_phase_unwrapping_unwrap
Built target opencv_photo_pch_dephelp
Built target pch_Generate_opencv_photo
Built target opencv_photo
Built target opencv_test_photo_pch_dephelp
Built target pch_Generate_opencv_test_photo
Built target opencv_test_photo
Built target opencv_perf_photo_pch_dephelp
Built target pch_Generate_opencv_perf_photo
Built target opencv_perf_photo
Built target opencv_plot_pch_dephelp
Built target pch_Generate_opencv_plot
Built target opencv_plot
Built target example_plot_plot_demo
Built target opencv_test_reg_pch_dephelp
Built target pch_Generate_opencv_test_reg
Built target opencv_reg_pch_dephelp
Built target pch_Generate_opencv_reg
Built target opencv_reg
Built target opencv_test_reg
Built target opencv_perf_reg_pch_dephelp
Built target example_reg_map_test
Built target pch_Generate_opencv_perf_reg
Built target opencv_perf_reg
Built target opencv_surface_matching_pch_dephelp
Built target pch_Generate_opencv_surface_matching
Built target opencv_surface_matching
Built target example_surface_matching_ppf_normal_computation
Built target example_surface_matching_ppf_load_match
Built target opencv_video_pch_dephelp
Built target pch_Generate_opencv_video
Built target opencv_video
Built target opencv_test_video_pch_dephelp
Built target pch_Generate_opencv_test_video
Built target opencv_test_video
Built target opencv_perf_video_pch_dephelp
Built target pch_Generate_opencv_perf_video
Built target opencv_perf_video
Built target opencv_xphoto
Built target example_xphoto_dct_image_denoising
Built target opencv_test_xphoto_pch_dephelp
Built target opencv_perf_xphoto_pch_dephelp
Built target example_xphoto_color_balance
Built target example_xphoto_inpainting
Built target pch_Generate_opencv_test_xphoto
Built target opencv_test_xphoto
Built target pch_Generate_opencv_perf_xphoto
Built target opencv_perf_xphoto
Built target example_xphoto_bm3d_image_denoising
Built target opencv_test_bgsegm_pch_dephelp
Built target opencv_bgsegm_pch_dephelp
Built target pch_Generate_opencv_bgsegm
Built target opencv_bgsegm
Built target pch_Generate_opencv_test_bgsegm
Built target opencv_test_bgsegm
Built target example_bgsegm_bgfg
Built target opencv_dnn_pch_dephelp
Built target pch_Generate_opencv_dnn
Built target opencv_dnn
Built target opencv_test_dnn_pch_dephelp
Built target pch_Generate_opencv_test_dnn
Built target opencv_test_dnn
Built target opencv_perf_dnn_pch_dephelp
Built target pch_Generate_opencv_perf_dnn
Built target opencv_perf_dnn
Built target opencv_face_pch_dephelp
Built target pch_Generate_opencv_face
Built target opencv_face
Built target example_face_facerec_eigenfaces
Built target example_face_facerec_demo
Built target example_face_facerec_fisherfaces
Built target opencv_test_face_pch_dephelp
Built target pch_Generate_opencv_test_face
Built target opencv_test_face
Built target example_face_facerec_lbph
Built target example_face_facerec_video
Built target example_face_facerec_save_load
Built target opencv_freetype_pch_dephelp
Built target pch_Generate_opencv_freetype
Built target opencv_freetype
Built target opencv_fuzzy_pch_dephelp
Built target opencv_test_fuzzy_pch_dephelp
Built target pch_Generate_opencv_test_fuzzy
Built target pch_Generate_opencv_fuzzy
Built target opencv_fuzzy
Built target opencv_test_fuzzy
Built target example_fuzzy_fuzzy_filtering
Built target example_fuzzy_fuzzy_inpainting
Built target opencv_img_hash_pch_dephelp
Built target pch_Generate_opencv_img_hash
Built target opencv_img_hash
Built target opencv_test_img_hash_pch_dephelp
Built target pch_Generate_opencv_test_img_hash
Built target opencv_test_img_hash
Built target example_img_hash_hash_samples
Built target opencv_test_imgcodecs_pch_dephelp
Built target pch_Generate_opencv_test_imgcodecs
Built target opencv_test_imgcodecs
Built target opencv_perf_imgcodecs_pch_dephelp
Built target pch_Generate_opencv_perf_imgcodecs
Built target opencv_perf_imgcodecs
Built target opencv_shape_pch_dephelp
Built target pch_Generate_opencv_shape
Built target opencv_shape
Built target opencv_test_shape_pch_dephelp
Built target pch_Generate_opencv_test_shape
Built target opencv_test_shape
Built target opencv_test_videoio_pch_dephelp
Built target pch_Generate_opencv_test_videoio
Built target opencv_test_videoio
Built target opencv_perf_videoio_pch_dephelp
Built target pch_Generate_opencv_perf_videoio
Built target opencv_perf_videoio
Built target opencv_xobjdetect_pch_dephelp
Built target pch_Generate_opencv_xobjdetect
Built target opencv_xobjdetect
Built target opencv_waldboost_detector
Built target opencv_test_highgui_pch_dephelp
Built target pch_Generate_opencv_test_highgui
Built target opencv_test_highgui
Built target opencv_superres_pch_dephelp
Built target pch_Generate_opencv_superres
Built target opencv_superres
Built target opencv_test_superres_pch_dephelp
Built target pch_Generate_opencv_test_superres
Built target opencv_test_superres
Built target opencv_perf_superres_pch_dephelp
Built target pch_Generate_opencv_perf_superres
Built target opencv_perf_superres
Built target opencv_bioinspired_pch_dephelp
Built target pch_Generate_opencv_bioinspired
Built target opencv_bioinspired
Built target example_bioinspired_OpenEXRimages_HDR_Retina_toneMapping
Built target opencv_test_bioinspired_pch_dephelp
Built target pch_Generate_opencv_test_bioinspired
Built target opencv_test_bioinspired
Built target example_bioinspired_retinaDemo
Built target opencv_perf_bioinspired_pch_dephelp
Built target pch_Generate_opencv_perf_bioinspired
Built target opencv_perf_bioinspired
Built target opencv_dpm_pch_dephelp
Built target pch_Generate_opencv_dpm
Built target opencv_dpm
Built target example_dpm_cascade_detect_camera
Built target example_dpm_cascade_detect_sequence
Built target opencv_test_features2d_pch_dephelp
Built target pch_Generate_opencv_test_features2d
Built target opencv_features2d_pch_dephelp
Built target pch_Generate_opencv_features2d
Built target opencv_features2d
Built target opencv_test_features2d
Built target opencv_perf_features2d_pch_dephelp
Built target pch_Generate_opencv_perf_features2d
Built target opencv_perf_features2d
Built target opencv_test_line_descriptor_pch_dephelp
Built target opencv_line_descriptor_pch_dephelp
Built target pch_Generate_opencv_line_descriptor
Built target opencv_line_descriptor
Built target example_line_descriptor_knn_matching
Built target example_line_descriptor_lsd_lines_extraction
Built target pch_Generate_opencv_test_line_descriptor
Built target opencv_test_line_descriptor
Built target example_line_descriptor_compute_descriptors
Built target opencv_perf_line_descriptor_pch_dephelp
Built target pch_Generate_opencv_perf_line_descriptor
Built target opencv_perf_line_descriptor
Built target example_line_descriptor_matching
Built target example_line_descriptor_lines_extraction
Built target example_line_descriptor_radius_matching
Built target opencv_saliency_pch_dephelp
Built target pch_Generate_opencv_saliency
Built target opencv_saliency
Built target example_saliency_computeSaliency
Built target opencv_text_pch_dephelp
Built target pch_Generate_opencv_text
Built target opencv_text
Built target example_text_textdetection
Built target example_text_end_to_end_recognition
Built target opencv_test_text_pch_dephelp
Built target pch_Generate_opencv_test_text
Built target opencv_test_text
Built target example_text_cropped_word_recognition
Built target example_text_segmented_word_recognition
Built target example_text_character_recognition
Built target example_text_dictnet_demo
Built target example_text_webcam_demo
Built target opencv_test_calib3d_pch_dephelp
Built target pch_Generate_opencv_test_calib3d
Built target opencv_calib3d_pch_dephelp
Built target pch_Generate_opencv_calib3d
Built target opencv_calib3d
Built target opencv_test_calib3d
Built target opencv_perf_calib3d_pch_dephelp
Built target pch_Generate_opencv_perf_calib3d
Built target opencv_perf_calib3d
Built target opencv_ccalib_pch_dephelp
Built target pch_Generate_opencv_ccalib
Built target opencv_ccalib
Built target example_ccalib_multi_cameras_calibration
Built target example_ccalib_omni_calibration
Built target example_ccalib_random_pattern_calibration
Built target example_ccalib_random_pattern_generator
Built target example_ccalib_omni_stereo_calibration
Built target opencv_datasets
Built target example_datasets_ar_hmdb_benchmark
Built target example_datasets_tr_chars_benchmark
Built target example_datasets_tr_icdar_benchmark
Built target example_datasets_slam_kitti
Built target example_datasets_ar_sports
Built target example_datasets_or_pascal
Built target example_datasets_msm_middlebury
Built target example_datasets_pd_caltech
Built target example_datasets_tr_icdar
Built target example_datasets_fr_lfw_benchmark
Built target example_datasets_fr_lfw
Built target example_datasets_is_bsds
Built target example_datasets_or_sun
Built target example_datasets_slam_tumindoor
Built target example_datasets_ir_affine
Built target example_datasets_or_mnist
Built target example_datasets_tr_chars
Built target example_datasets_is_weizmann
Built target example_datasets_track_vot
Built target example_datasets_msm_epfl
Built target example_datasets_gr_chalearn
Built target example_datasets_pd_inria
Built target example_datasets_ar_hmdb
Built target example_datasets_hpe_parse
Built target example_datasets_gr_skig
Built target example_datasets_tr_svt
Built target example_datasets_ir_robot
Built target example_datasets_fr_adience
Built target example_datasets_or_imagenet
Built target example_datasets_hpe_humaneva
Built target example_datasets_tr_svt_benchmark
Built target opencv_rgbd_pch_dephelp
Built target opencv_test_rgbd_pch_dephelp
Built target pch_Generate_opencv_test_rgbd
Built target pch_Generate_opencv_rgbd
Built target opencv_rgbd
Built target opencv_test_rgbd
Built target example_rgbd_odometry_evaluation
Built target example_rgbd_linemod
Built target opencv_perf_stereo_pch_dephelp
Built target opencv_stereo_pch_dephelp
Built target opencv_test_stereo_pch_dephelp
Built target pch_Generate_opencv_test_stereo
Built target pch_Generate_opencv_stereo
Built target opencv_stereo
Built target opencv_test_stereo
Built target pch_Generate_opencv_perf_stereo
Built target opencv_perf_stereo
Built target example_stereo_sample
Built target opencv_test_structured_light_pch_dephelp
Built target pch_Generate_opencv_test_structured_light
Built target opencv_structured_light_pch_dephelp
Built target pch_Generate_opencv_structured_light
Built target opencv_structured_light
Built target opencv_test_structured_light
Built target example_structured_light_cap_pattern
Built target example_structured_light_capsinpattern
Built target example_structured_light_projectorcalibration
Built target example_structured_light_pointcloud
Built target opencv_tracking_pch_dephelp
Built target pch_Generate_opencv_tracking
Built target opencv_tracking
Built target opencv_perf_tracking_pch_dephelp
Built target pch_Generate_opencv_perf_tracking
Built target opencv_perf_tracking
Built target example_tracking_tutorial_introduction_to_tracker
Built target example_tracking_benchmark
Built target example_tracking_multiTracker_dataset
Built target opencv_test_tracking_pch_dephelp
Built target pch_Generate_opencv_test_tracking
Built target opencv_test_tracking
Built target example_tracking_goturnTracker
Built target example_tracking_tracker_dataset
Built target example_tracking_tracker
Built target example_tracking_tutorial_customizing_cn_tracker
Built target example_tracking_kcf
Built target example_tracking_tutorial_multitracker
Built target example_tracking_multitracker
Built target opencv_videostab_pch_dephelp
Built target pch_Generate_opencv_videostab
Built target opencv_videostab
Built target opencv_test_videostab_pch_dephelp
Built target pch_Generate_opencv_test_videostab
Linking CXX executable ../../bin/opencv_test_videostab
collect2: error: ld returned 1 exit status
modules/videostab/CMakeFiles/opencv_test_videostab.dir/build.make:136: recipe for target 'bin/opencv_test_videostab' failed
make[2]: *** [bin/opencv_test_videostab] Error 1
CMakeFiles/Makefile2:17076: recipe for target 'modules/videostab/CMakeFiles/opencv_test_videostab.dir/all' failed
make[1]: *** [modules/videostab/CMakeFiles/opencv_test_videostab.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by csukuangfj** [comment]
The error log
```
Linking CXX executable ../../bin/opencv_test_videostab
collect2: error: ld returned 1 exit status
modules/videostab/CMakeFiles/opencv_test_videostab.dir/build.make:136: recipe for target 'bin/opencv_test_videostab' failed
```
is not **informative**.

**Comment by shan4224** [comment]
I have put the error output as is :  You may also visit [Error Log.docx](https://github.com/opencv/opencv/files/2163889/Error.Log.docx)](url)

I am using Ubuntu 16.04 . Please suggest if any other info is required. I am stuck at this for couple of weeks.

**Comment by pwnorbitals** [comment]
Does this still happen on latest releases ?
