### ISSUE TITLE
Error in Matx::solve for non-square matrices

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#11888]
##### System information (version)

- OpenCV => latest

##### Detailed description
See the following code

https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/matx.hpp#L183

`solve` is supported for non-square `matx`, i.e., `m!=n`.

Its implementation is

https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/operations.hpp#L208-L222

Pay attention to the line
https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/operations.hpp#L214

`Matx_FastSolveOp` is defined as

https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/operations.hpp#L121-L133

which requires a square matrix `const Matx<_Tp, m, m>& a`

##### Steps to reproduce

The following code will result in a compilation error

```.cpp
    cv::Matx<float, 3, 2> A(
            2, 1,
            3, 1,
            9, 1
    );
    cv::Vec<float, 3> b(4, 5, 7);

    auto x = A.solve(b, cv::DecompTypes::DECOMP_QR);
```

Error log is as follows:

```
........../include/opencv2/core/operations.hpp: In instantiation of ‘cv::Matx<_Tp, n, l> cv::Matx<_Tp, m, n>::solve(const cv::Matx<_Tp, m, l>&, int) const [with int l = 1; _Tp = float; int m = 3; int n = 2]’:
........../include/opencv2/core/matx.hpp:895:30:   required from ‘cv::Vec<_Tp, n> cv::Matx<_Tp, m, n>::solve(const cv::Vec<_Tp, m>&, int) const [with _Tp = float; int m = 3; int n = 2]’

........../include/opencv2/core/operations.hpp:214:57: error: no match for call to ‘(cv::internal::Matx_FastSolveOp<float, 3, 1>) (const cv::Matx<float, 3, 2>&, const cv::Matx<float, 3, 1>&, cv::Matx<float, 2, 1>&, int&)’
         ok = cv::internal::Matx_FastSolveOp<_Tp, m, l>()(*this, rhs, x, method);
                                                         ^
........../include/opencv2/core/operations.hpp:152:10: note: candidate: bool cv::internal::Matx_FastSolveOp<_Tp, 3, 1>::operator()(const cv::Matx<_Tp, 3, 3>&, const cv::Matx<T2, 3, 1>&, cv::Matx<T2, 3, 1>&, int) const [with _Tp = float]
     bool operator()(const Matx<_Tp, 3, 3>& a, const Matx<_Tp, 3, 1>& b,
          ^
........../include/opencv2/core/operations.hpp:152:10: note:   no known conversion for argument 1 from ‘const cv::Matx<float, 3, 2>’ to ‘const cv::Matx<float, 3, 3>&’
```

A workaround is to use
https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/operations.hpp#L215-L219

**Comment by terfendail** [comment]
As stated in `cv::solve` description it doesn't return correct solution for the case of singular matrix if `DECOMP_LU` or `DECOMP_CHOLESKY` methods selected(since such system could not be solved). However `cv::solve` could mark the solution as incorrect by proper return value while `Matx::solve` produce solution as return value so the only way to indicate incorrect solution is exception.
Also Matx size is defined at compile time. Therefore it looks like a mistake to try to find solution of almost definitely singular system.

**Comment by csukuangfj** [comment]
@terfendail 
I was expecting that `Matx::solve` can be used to solve overdetermined systems, say least square solutions.

From its signature
https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core/matx.hpp#L183
you cannot tell that it supports only square non-signular matrices.

As an alternative,
https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core.hpp#L1851-L1852

was used.

By the way, it is possible to find a solution for singular matrices using `cv:solve`
https://github.com/opencv/opencv/blob/3165baa1f152878b49c984384aa61c430a686768/modules/core/include/opencv2/core.hpp#L1838-L1839

**Comment by terfendail** [comment]
@csukuangfj Could you please check whether PR #11904 fix the issue?
