### ISSUE TITLE
core: invalid cast in opengl.cpp

### ISSUE THREAD

**Issue by berak** [opencv/opencv#11910]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64

##### Detailed description
```
C:\p\opencv\modules\core\src\opengl.cpp: In function 'cv::ocl::Context& cv::ogl::ocl::initializeContextFromGL()':
C:\p\opencv\modules\core\src\opengl.cpp:1627:104: error: invalid cast from type 'cv::AutoBuffer<char>' to type 'char*'
                 status = clGetPlatformInfo(platforms[i], CL_PLATFORM_EXTENSIONS, extensionSize, (char*)extensionStr, NULL);
                                                                                                        ^~~~~~~~~~~~
C:\p\opencv\modules\core\src\opengl.cpp:1632:38: error: invalid cast from type 'cv::AutoBuffer<char>' to type 'const char*'
             if (!strstr((const char*)extensionStr, "cl_khr_gl_sharing"))
                                      ^~~~~~~~~~~~
```

probably overlooked, because the buildbots don't have opengl enabled.

**Comment by saurabheights** [comment]
I am not familiar with AutoBuffer enough, but facing similar issue in building odometry module. 
https://github.com/opencv/opencv_contrib/blob/master/modules/rgbd/src/odometry.cpp#L445 and 3 more as shown in screenshots.

[screenshot from 2018-07-08 15-15-17](https://user-images.githubusercontent.com/11634769/42420165-cd1ec1ba-82c1-11e8-9f8b-d53fdea61141.png)

**Comment by berak** [comment]
@saurabheights please update your opencv_contrib repo then (use the latest 3.4 branch), [where it is already fixed](https://github.com/opencv/opencv_contrib/blame/3.4/modules/rgbd/src/odometry.cpp#L650)

**Comment by saurabheights** [comment]
@berak I am using 3.4 branch - commit 
bcddb16  Thu Jul 5 10:00:48 2018 +0000 Alexander Alekhin (HEAD -> 3.4, origin/3.4) Merge pull request #1662 from alalek:update_autobuffer_api

It is in screenshot at bottom as well. gs is git status

**Comment by alalek** [comment]
@saurabheights You using:
- opencv from "3.4" branch
- opencv_contrib from "master" branch.

This configuration is wrong. Both branches must be the same. You should switch opencv_contrib to 3.4 too.

**Comment by saurabheights** [comment]
@alalek  I am not using master branch. Both opencv and opencv_contrib branch are on 3.4. The commit id where I am says HEAD -> 3.4, origin/3.4 and this is same for both opencv and opencv_contrib. Please correct me if I'm wrong.

**Comment by saurabheights** [comment]
@alalek Sorry, I think my issue should be resolved. The branch was correct but after doing git pull, I see the 3.4 code has AutoBuffer .data() methods.

**Comment by berak** [comment]
pr got merged, @saurabheights issue got resolved, too. great !
