### ISSUE TITLE
OpenCV 3.4.1 with CLR

### ISSUE THREAD

**Issue by OnurErtugral** [opencv/opencv#11912]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

I can not compile quite simple OpenCV project with CLR on Visual Studio 2017. It gives me "< mutex > is not supported when compiling with /clr or /clr:pure." error.

##### Steps to reproduce

- Start a new empty C++ project on Visual Studio 2017. 
- Try to read and show an image.
- Go to project properties -> Configuration Properties -> General -> Common Language Runtime Support -> Select Common Language Runtime Support (/CLR)
- Try to build.

**Comment by alalek** [comment]
OpenCV 4.x requires C++11 features.
`std::mutex` is one of them.
`CLR` is `.NET` thing, declared to be compatible with C++. But it really don't.

**Comment by kinchungwong** [comment]
The C++ code base for OpenCV cannot be built with C++ CLR enabled.

To link OpenCV to a C++ CLR project, use the following approach. First, build OpenCV library as-is (in the C++ project that is configured and generated by CMake). Then, create a C++ (non CLR) project that contains your code and application logic, which calls the OpenCV API to do useful work. However, your code needs to expose (wrap) an API that doesn't depend on OpenCV type definitions at all. In other words, your application logic API needs to be usable by another project without requiring that other project to include any OpenCV headers. Finally, create a C++ CLR shim project that calls your code.

Though cumbersome, there is really no other way round.

**Comment by jsxyhelu** [comment]
> Though cumbersome, there is really no other way round.

is there a simple example?that will be great for this

**Comment by alalek** [comment]
Try to find reliable .NET CLR macro and try something like this:
```.diff
+#ifndef DOTNET_BUILD
 #include <mutex>
+#endif

...

+#ifndef DOTNET_BUILD
 typedef std::recursive_mutex Mutex;
 typedef std::lock_guard<cv::Mutex> AutoLock;
+#endif
```

/cc @chacha21
