### ISSUE TITLE
Memory issue in imread function

### ISSUE THREAD

**Issue by purvadepani** [opencv/opencv#11937]
During flushing of 45 to 50 images in sequence, opencv imread function is giving error of "**OpenCV Error: Insufficient memory (Failed to allocate memory)** in OutOfMemoryError. Please provide the solution to this problem, that how to release memory of opencv imread during cancellation of one imread function in between.

The scenario is as follow:

There is a large image of about 10MB and I am reading it using imread in thread. After reading another processing is carried out using resize, grayscale and other functions of opencv. Now suppose while reading that 10MB image we want to cancel that process and directly read the next image. I am able to cancel the previous reading process by keeping it in a thread, but after doing so for 45 to 50 images opencv shows the memory error.

Here I do not want the previous image in memory only the present input image is required. Also I have used Mat.release function to release the mat objects used in the software at every cancel of thread.

**Comment by mshabunin** [comment]
As I understand you are using Java, please provide more details such as OS, platform, OpenCV version and build configuration.

Please consider that 10 Mb JPEG file can take about 120 Mb in memory. Looks like you do not release resources correctly. It is hard to say without reproducing application.

**Comment by purvadepani** [comment]
I am using Linux OS based on ARM based processor, Open-CV version 3.2.0 cross compiled with arm-linux-gnueabihf compiler.

As i am using **Input_Image.release();** function to release memory, but it is not releasing memory.
Is there any solution for this?

**Comment by mshabunin** [comment]
> I am able to cancel the previous reading process by keeping it in a thread

With threads you can not be sure when your method has been called.

>After reading another processing is carried out using resize, grayscale and other functions of opencv

It means more copies of the image can be created, make sure you release them all correctly.

>Linux OS based on ARM based processor

I assume it is 32-bit, so you can use only ~3 Gb of memory in the application. Probably the board itself contain less memory (RPI 3 has 1 Gb) and if you have no swap file (check output of `free -h` command), you will be limited with this 1 Gb for all applications.

**Comment by purvadepani** [comment]
So, do you mean it is not possible to cancel imread process?

I am trying to explain again if it is not clear.

Pseudo code:
1.	Create a Thread
2.	Open 10MB BMP image in mat form using imread(image name and CV_LOAD_IMAGE_COLOR)
3.	While reading above image if there is a new image then I am killing above thread and releasing 
        memory using image.release API.
4.	Now create new thread and try to read image as explain in above steps.

So ultimately, I want to process new image immediately and cancel the processing of previous image but we need your help to understand whether above method is correct or not.

Here, it seems image.release API is not clearing all memory and after processing of 45-50 images open CV is giving error:  Insufficient memory (Failed to allocate memory) otherwise things are working fine.

So, I would like to know what best practice is to cancel the process running in imread function.

**Comment by mshabunin** [comment]
@purvadepani , please attach actual code snippet reproducing this issue.

**Comment by purvadepani** [comment]
Please refer the attached code, here i am using matrix keypad input as interrupt. Thread cancels OpenCV function process in between, but it works for 50 images after that it throws OpenCV Error: Insufficient memory.

`#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <cv.h>
#include <highgui.h>
#include <iostream>
#include <gif_lib.h>
#include <pthread.h>
#include <string.h>

using namespace cv;
pthread_attr_t threadattr;
int Processing_Thread_Cancel(void);
pthread_t ImageProcessing;
void *Processing(void* unused);
unsigned char Processing_status=0;
cv::Mat Input_Image, Output_Image;// Mat Input_Image,Output_Image;
char path[255];
int i=0;
char *command;
int main()
{
	if(interrupt==1)    //Here I am using matrix keypad input as interrupt
	{
			i++;
			if(i>=100) i=1;              
			sprintf(path, "/home/root/%d.jpg", i);    //Read image from path
			Processing_Thread_Cancel();               //Cancel image processing thread if it is running
			if(Processing_status==0)                     
			{
				pthread_create(&ImageProcessing, &threadattr, &Processing, NULL);  //cancel thread
			}		
	}
	return 0;
}

void *Processing(void* unused)   
{	
	Processing_status=1;	
	Input_Image = imread(path,1); //Read image  	
	resize(Input_Image,Output_Image,Size(60,40),0.5,0.5,INTER_AREA);      //resize image		
	imwrite("/home/root/Output.png",Output_Image);	                     //Write image as Output.png	
	Processing_status=0;         //flag reset 	
	Input_Image.release();	  //Release memory 
	Output_Image.release();    //Release memory 
}

int Processing_Thread_Cancel(void)
{
	if(Processing_status ==1)    //if thread is running then cancel thread for Processing next image
	{
		pthread_cancel(ImageProcessing);    //cancel thread		
		Input_Image.release();  //Release memory 
		Output_Image.release();  //Release memory		
		Processing_status=0;
	}
}`

**Comment by alalek** [comment]
[`pthread_cancel()`](http://man7.org/linux/man-pages/man3/pthread_cancel.3.html) is not properly supported in OpenCV (no cleanup handlers).
Additionally OpenCV doesn't expect high pressure of threads creation/deletion. Some memory is allocated or each thread (and not freed until process termination). Use thread pools (number of threads are limited), or dedicated "worker" processes.
