### ISSUE TITLE
How to initialize cv::dnn::Net to be null as a default parameter?

### ISSUE THREAD

**Issue by kr0920** [opencv/opencv#11945]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => g++

##### Detailed description

I want to use cv::dnn::Net as a default parameter, but i do not know how to initialize it to be null. Does someone know how to do it?

**Comment by dkurt** [comment]
@kr0920, this is a tracker for bug reports and feature requests. Usage questions should go to a forum: http://answers.opencv.org
