### ISSUE TITLE
failing build opencv and opencv_contrib on Jetson TX2

### ISSUE THREAD

**Issue by smafaith** [opencv/opencv#11946]
I'm trying to install OpenKAI on TX2, and install opencv like this : 
`git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git

cd ~/opencv

mkdir build

cd build

cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ..

make -j3

sudo make install`
But I failed 'make -j3' with output and error shown in attach logs. 
[CMakeError.log](https://github.com/opencv/opencv/files/2186901/CMakeError.log)
[CMakeOutput.log](https://github.com/opencv/opencv/files/2186903/CMakeOutput.log)

I do appreciate any of your help!

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Provided information is not enough. More details are required:
- CMake stdout from console terminal (from clean build)
- failed command line via `make VERBOSE=1` (without any `-j` option)
