### ISSUE TITLE
openCV not installing!

### ISSUE THREAD

**Issue by mtareiling** [opencv/opencv#11958]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
OpenCV is not installing and is giving errors, i don;t know how to fix these and i think i have tried anything. please help!
[help.txt](https://github.com/opencv/opencv/files/2189784/help.txt)

**Comment by berak** [comment]
'opencv4nodejs' -- you're asking in the wrong place, opencv does not maintain any of this.

maybe [here](https://github.com/justadudewhohacks/opencv4nodejs) ?

again, please kindly close this issue, it's not an opencv bug.
