### ISSUE TITLE
cv::Matx33f tmp = true compiles

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#11956]
##### System information (version)

- OpenCV =>3.20
- Operating System / Platform =>Windows 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

```
cv::Matx33f tmp = true
```
compiles because it uses the single-parameter constructor ```Matx(_Tp v0); //!< 1x1 matrix```.
This is especially a problem here:

```
bool foo(std::string, cv::Matx33f bar, bool foobar = true) {}

foo("awesome", true); // You are not warned that you forgot a parameter
```

**Comment by alalek** [comment]
@PhilLab Could you check #11957 ?

**Comment by PhilLab** [comment]
@alalek Thank you, this worked.
Maybe we need the same for ``Scalar_`` as well? https://github.com/opencv/opencv/blob/43f821afb91330958d4723f6300a5ec0bfa2185e/modules/core/include/opencv2/core/types.hpp#L642

**Comment by alalek** [comment]
It would be nice to have, but it breaks code like this:
```
cv::Mat(cv::Size(10,10), CV_32FC1, 0.0f);
```

Please note about "0.0f" instead of "0", because `cv::Mat(cv::Size(10,10), CV_32FC1, 0);` calls this overload:
```
Mat(Size size, int type, void* data, size_t step=AUTO_STEP);
```

So currently I'm always using this safe form:
```
cv::Mat(cv::Size(10,10), CV_32FC1, cv::Scalar::all(0));
```
