### ISSUE TITLE
Opencv installation in linux

### ISSUE THREAD

**Issue by codeShaurya** [opencv/opencv#11954]
Sometime user feels a lot of problem while installing opencv package. This issue is about solving problem of installing opencv in linux operating system.
Should I work on it??

**Comment by alalek** [comment]
Feel free to validate OpenCV's "Installation" [tutorials](https://docs.opencv.org/3.4.2/df/d65/tutorial_table_of_content_introduction.html).

**Comment by codeShaurya** [comment]
I was thinking about to create a ".sh". After  validating opencv installation  tutorial that you have mentioned , I will creating a .sh file. user don't  need to run each command itself.  User have to  download the file and just ececute this file in bash.
This will run all the command that is specified  in opencv installation  tutorial.

**Comment by csukuangfj** [comment]
The default configuration described in the [tutorial](https://docs.opencv.org/3.4.2/d7/d9f/tutorial_linux_install.html) may be enough for average users.
But many installation options are largely undocumented and one has to dig into the `CMakeLists.txt` to find out which option should be enabled or disabled according to his own needs.

It would be very helpful to document the options supported by OpenCV while building. For example, the recently added option `BUILD_LIST`.

**Comment by Manas-kashyap** [comment]
how about creating a .deb file of this module using debian packaging . I have experience in it and would like to package it .

**Comment by mshabunin** [comment]
>It would be very helpful to document the options supported by OpenCV while building.

Most of variables are documented in cmake: `cd <build> && cmake -LH <path-to-opencv>`

**Comment by hrnr** [comment]
@Manas-kashyap OpenCV is packaged in debian. https://tracker.debian.org/pkg/opencv
