### ISSUE TITLE
There is wrong with running faster_rcnn_inception_v2 model(tensorflow) configured opencl target.

### ISSUE THREAD

**Issue by wanglan0804** [opencv/opencv#11961]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => Windows  10 64 Bit
- Compiler => Visual Studio 2015
--CPU => Intel i7-6700
--GPU => intel HD graphics 530

##### Detailed description
The file "frozen_inference_graph.pbtxt" is same as the opencv_extra github's file "faster_rcnn_inception_v2_coco_2018_01_28.pbtxt".
when I used the code like this:
	String model = "G:\\faster_rcnn_inception_v2\\frozen_inference_graph.pb";
	String pbtxt = "G:\\faster_rcnn_inception_v2\\frozen_inference_graph.pbtxt";
	dnn::Net net = cv::dnn::readNetFromTensorflow(model, pbtxt);
......
	net.setPreferableBackend(DNN_BACKEND_OPENCV);
	net.setPreferableTarget(DNN_TARGET_CPU);
......
everything is ok,the car and person in picture is regconized correctly.

but when I change the code using Opencl(net.setPreferableTarget(DNN_TARGET_OPENCL),I get the wrong message:
Error: Assertion failed (i >= 0) in cv::MatSize::operator [], file D:\opencv\modules\core\include\opencv2/core/mat.inl.hpp, line 1416
The progroam stoped at the line:
	net.forward(outs, getOutputsNames(net));

##### Steps to reproduce
The sample code is changed according to opencv\samples\dnn\object_detection.cpp.
[obj_detect.zip](https://github.com/opencv/opencv/files/2191971/obj_detect.zip)

**Comment by dkurt** [comment]
@wanglan0804, thank you! Could you please test the changes from a PR https://github.com/opencv/opencv/pull/11970?

**Comment by wanglan0804** [comment]
The bug still exists(I have updated the source code and rebuild it). This lets me fuzzy!
![debug](https://user-images.githubusercontent.com/17560286/42743622-291b092e-88f8-11e8-8252-9d4e762cd1d3.jpg)
![error](https://user-images.githubusercontent.com/17560286/42743623-2963e572-88f8-11e8-8cd2-2ebd6580ba09.jpg)

**Comment by wanglan0804** [comment]
first I think the code is updated in branch 'master',then I update the code in my PC.the bug is still existed,I totally is in fuzzy.I read your PR many times,finally I understand the code is just updated in tree you have established.I copyed the three code files and re-test it.passed!thanks.

**Comment by wanglan0804** [comment]
and I have another question,after enanle the OPENCL target,the dnn uses more time than just only cpu.OPENCL time use
