### ISSUE TITLE
Stop support VS2013?

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#11979]
Start using `noexcept` in commit 43f821afb91330958d4723f6300a5ec0bfa2185e makes it impossible to use VS2013.

**Comment by Bleach665** [comment]
> BTW, MSVS2013 has no updates for the last 3 years.
But before this https://github.com/opencv/opencv/commit/43f821afb91330958d4723f6300a5ec0bfa2185e VS2013 could be used.

**Comment by cv3d** [comment]
Although OpenCV dev team does not support MSVC 2013, external contributions are mostly welcome as long as it does not reduce the code quality or limit functionality.

> Start using `noexcept`

You can push a PR with `CV_NOEXCEPT` instead, and VS2013 would not complain anymore 😉
