### ISSUE TITLE
OPENCV 3.4.0 Make Error on Ubuntu 17.10

### ISSUE THREAD

**Issue by ritika890** [opencv/opencv#11981]
![terminalscrnshot](https://user-images.githubusercontent.com/25774736/42747864-aaecfe6e-88fb-11e8-84d8-78d59578fb56.png)
Ubuntu Version : 17.10
Cuda Version : 9.1 (Deb Network file)
Opencv Version : 3.4.0
GCC version : 7.2
Nvidia Drivers : 390.67

I have treated this error by :
changing the default gcc to 5.4 before installation of cuda 
Explicitly setting CXX and C compiler to 5.4 in bashrc 
Trying various options in CMake 
But still not getting this error resolved

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
