### ISSUE TITLE
opencv 3.4.2 compile error

### ISSUE THREAD

**Issue by liushuanpeng** [opencv/opencv#11992]
cmake command is:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/opencv_dnn/bin -DWITH_INF_ENGINE=ON -DINTEL_CVSDK_DIR=$HOME/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools -DIE_PLUGINS_PATH=$HOME/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/lib/centos_7.3/intel64 -DOPENCV_EXTRA_MODULES_PATH=/home/liushuanpeng/opencv_dnn/opencv_contrib-3.4.2/modules -DBUILD_opencv_legacy=ON -DBUILD_opencv_contib=ON -DENABLE_CXX11=ON -DWITH_TBB=ON -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_gpu=OFF -D BUILD_opencv_stitching=OFF -D BUILD_opencv_xfeatures2d=OFF -D BUILD_opencv_face=OFF -D BUILD_opencv_java=OFF ..

when compile opencv3.4.2，the error is next

In file included from /home/liushuanpeng/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/include/inference_engine.hpp:28:0,
                 from /home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/op_inf_engine.hpp:16,
                 from /home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/dnn.cpp:44:
/home/liushuanpeng/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/include/ie_layers.h: 在构造函数‘InferenceEngine::DeconvolutionLayer::DeconvolutionLayer(const InferenceEngine::LayerParams&)’中:
/home/liushuanpeng/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/include/ie_layers.h:360:18: 警告：‘InferenceEngine::DeconvolutionLayer::_group’将在 [-Wreorder]
     unsigned int _group;
                  ^
/home/liushuanpeng/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/include/ie_layers.h:352:18: 警告：‘unsigned int InferenceEngine::DeconvolutionLayer::_dilation_x’ [-Wreorder]
     unsigned int _dilation_x;
                  ^
/home/liushuanpeng/intel/deeplearning_deploymenttoolkit_2017.1.0.5855/deployment_tools/inference_engine/include/ie_layers.h:366:14: 警告：在此处初始化后被初始化 [-Wreorder]
     explicit DeconvolutionLayer(const LayerParams &prms) : WeightableLayer(prms), _kernel_x(0), _kernel_y(0),
              ^
In file included from /home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/dnn.cpp:44:0:
/home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/op_inf_engine.hpp: 在全局域：
/home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/op_inf_engine.hpp:94:22: 错误：‘ExecutableNetwork’不是命名空间‘InferenceEngine’中的一个类型名
     InferenceEngine::ExecutableNetwork netExec;
                      ^
/home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/op_inf_engine.hpp:95:22: 错误：‘InferRequest’不是命名空间‘InferenceEngine’中的一个类型名
     InferenceEngine::InferRequest infRequest;
                      ^
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/nms.cpp.o
[ 71%] Linking CXX shared library ../../lib/libopencv_imgcodecs.so
/home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/dnn.cpp: 在静态成员函数‘static cv::dnn::experimental_dnn_v5::Net cv::dnn::experimental_dnn_v5::Net::readFromModelOptimizer(const cv::String&, const cv::String&)’中:
/home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/dnn.cpp:1997:54: 错误：‘class InferenceEngine::CNNNetwork’没有名为‘getLayerByName’的成员
         InferenceEngine::CNNLayerPtr ieLayer = ieNet.getLayerByName(it.first.c_str());
                                                      ^

**Comment by alalek** [comment]
You should update your DL IE (CVSDK -> OpenVINO) setup (2018 R2, package version 2018.2.300).

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by mshabunin** [comment]
@liushuanpeng , check this link https://software.intel.com/openvino-toolkit
