### ISSUE TITLE
OpenCV master build fails on Visual Studio 2013 and earlier

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#11999]
##### System information (version)

- OpenCV => recent master (technically 43f821afb / #11899  and after )
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2013  64bit (and probably earlier)

##### Detailed description
We get dozens of error about ```noexcept``` when building with Visual Studio 2013 and earlier.
```
  D:\Jenkins\workspace\OpenCV-MSBuild\modules\core\include\opencv2/core/types.hpp(166): error C3646: 'noexcept' : unknown override specifier (D:\Jenkins\workspace\OpenCV-MSBuild\modules\imgproc\src\resize.sse4_1.cpp) [D:\Jenkins\workspace\OpenCV-MSBuild\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
```

I googled a bit and figured out that ```noexcept``` is supported only from Visual Studio 2015 and later. 
[answer on StackOverflow](https://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio/33298731#33298731)
[commnet on StackOverflow](https://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio#comment27004724_18387764) 
[MSDN](https://msdn.microsoft.com/en-us/library/wfa0edys.aspx)

I'll throw a workaround patch later.

##### Steps to reproduce

Build recent master using Visual Studio 2013 or earlier

Update: my mistake.  Only happens on master, not on 3.4

**Comment by dkurt** [comment]
related https://github.com/opencv/opencv/issues/11979

**Comment by tomoaki0705** [comment]
Thank you for noticing me @dkurt . I haven't read that issue.
Probably I should withdraw the PR.
