### ISSUE TITLE
Compile opencv ,opencv extra lib error!

### ISSUE THREAD

**Issue by MRYangY** [opencv/opencv#11997]
- OpenCV => last
- Operating System / Platform => ubuntu  14
- Compiler => cmake

1.cmake -DOPENCV_EXTRA_MODULES_PATH=/home/tvu/AndroidProject/opencv_contrib/modules -DBUILD_opencv_xfeatures2d=OFF /home/tvu/AndroidProject/opencv/

2.and i execute  make -j5

than error occur!

log below:

/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::computeCorresps(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, float, cv::Mat&)’:
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp:446:30: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float *KRK_inv0_u1 = buf.data();
                              ^
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::calcRgbdLsmMatrices(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, double, double, double, cv::Mat&, cv::Mat&, cv::rgbd::CalcRgbdEquationCoeffsPtr, int)’:
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp:624:30: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float* diffs_ptr = diffs.data();
                              ^
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::calcICPLsmMatrices(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, cv::Mat&, cv::Mat&, cv::rgbd::CalcICPEquationCoeffsPtr, int)’:
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp:697:31: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float * diffs_ptr = diffs.data();
                               ^
/home/tvu/AndroidProject/opencv_contrib/modules/rgbd/src/odometry.cpp:700:45: error: ‘class cv::AutoBuffer<cv::Point3_<float> >’ has no member named ‘data’
     Point3f * tps0_ptr = transformedPoints0.data();
                                             ^
make[2]: *** [modules/rgbd/CMakeFiles/opencv_rgbd.dir/src/odometry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_reproject_image_to_3d.cpp.o
Scanning dependencies of target opencv_structured_light
[ 84%] Building CXX object modules/structured_light/CMakeFiles/opencv_structured_light.dir/src/graycodepattern.cpp.o
make[1]: *** [modules/rgbd/CMakeFiles/opencv_rgbd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Building CXX object modules/structured_light/CMakeFiles/opencv_structured_light.dir/src/sinusoidalpattern.cpp.o
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/src/stitcher.cpp.o
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/src/timelapsers.cpp.o
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_solvepnp_ransac.cpp.o
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/src/util.cpp.o
[ 84%] Linking CXX shared library ../../lib/libopencv_structured_light.so
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/src/warpers.cpp.o
[ 84%] Built target opencv_structured_light
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_stereomatching.cpp.o
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_undistort.cpp.o
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/src/warpers_cuda.cpp.o
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching.dir/opencl_kernels_stitching.cpp.o
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_undistort_badarg.cpp.o
[ 84%] Building CXX object modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/test_undistort_points.cpp.o
[ 84%] Linking CXX shared library ../../lib/libopencv_stitching.so
[ 84%] Built target opencv_stitching
[ 84%] Linking CXX executable ../../bin/opencv_test_calib3d
[ 84%] Built target opencv_test_calib3d
make: *** [all] Error 2

**Comment by alalek** [comment]
You should update code of **both** opencv/opencv_contrib repositories.

**Comment by MRYangY** [comment]
thanks ,but now i find new issue.
1.how to compile opencv_contrib lib for Android platform?(Major)
2.the result compiled success by  method that README.md give  is adapter to Android platform?
3.[http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk](url)  the Tutorial link can not open .

**Comment by alalek** [comment]
Check our CI [Android builds](http://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack). But they doesn't cover prerequisites installation (fresh Android SDK doesn't work with OpenCV from "the box").
You could take a look on similar [Android issues](https://github.com/opencv/opencv/issues?utf8=%E2%9C%93&q=label%3A%22category%3A+android%22+label%3A%22category%3A+build%2Finstall%22+).

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by 7ganam** [comment]
I face the same problem..and I'm not sure how you solved it..could you please tell the cause of this problem?

**Comment by dortizg** [comment]
Hi, I have the same problem this is my settings:

Centos 7.5
opencv_contrib 3.4
opencv 3.4.2
cmake 2.8.12.2
cuda 9.2
gcc 4.8.5

cmake -D CMAKE_BUILD_TYPE=RELEASE       -D CMAKE_INSTALL_PREFIX=/usr/local       -D INSTALL_C_EXAMPLES=ON   -D WITH_CUDA=ON     -D INSTALL_PYTHON_EXAMPLES=ON       -D WITH_TBB=ON       -D WITH_V4L=ON       -D WITH_QT=ON       -D WITH_OPENGL=ON       -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules/       -D BUILD_EXAMPLES=ON -D CUDA_GENERATION=Auto -D CMAKE_CXX_FLAGS=-std=gnu++11 -D CUDA_NVCC_FLAGS='-std=c++11 --expt-relaxed-constexpr' .. 


/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::computeCorresps(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, float, cv::Mat&)’:
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp:472:30: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float *KRK_inv0_u1 = buf.data();
                              ^
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::calcRgbdLsmMatrices(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, double, double, double, cv::Mat&, cv::Mat&, cv::rgbd::CalcRgbdEquationCoeffsPtr, int)’:
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp:650:30: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float* diffs_ptr = diffs.data();
                              ^
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp: In function ‘void cv::rgbd::calcICPLsmMatrices(const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, cv::Mat&, cv::Mat&, cv::rgbd::CalcICPEquationCoeffsPtr, int)’:
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp:723:31: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’
     float * diffs_ptr = diffs.data();
                               ^
/root/opencv-3.4.2/opencv_contrib/modules/rgbd/src/odometry.cpp:726:45: error: ‘class cv::AutoBuffer<cv::Point3_<float> >’ has no member named ‘data’

**Comment by afsyaw** [comment]
@dortizg Like @alalek  mentioned, clone the opencv repo instead of downloading it from the downloads page and recompile. Also ensure that your opencv_contrib repo is updated by cloning it too.

The change causing the error is from this [commit](https://github.com/opencv/opencv_contrib/commit/fc69aa57bc021422d825a4331f7ddf7d9f7534e7#diff-4d28ac2cbe908148fecef1e59313093b) from Jun 10, so I believe the related updates are not yet available in the downloadable source archive.

**Comment by MRYangY** [comment]
@7ganam  Opencv_contrib repository checkout 3.4 branch and updated to the latest.

**Comment by MRYangY** [comment]
@dortizg  What platform is your compiled library used for?Linux or mobile platform?

**Comment by 7ganam** [comment]
@MRYangY  the solution worked for me .. once I cloned and built the git repo rather than downloading from the site as you mentioned..I just didn't get what is meant by "update" in your answer the first time since I used the latest version on the site. Thank you very much for your help
