### ISSUE TITLE
A bug in cv::cuda::compare

### ISSUE THREAD

**Issue by huaweiping** [opencv/opencv#12015]
I find a bug in cv::cuda::Compare. The description for the function said:

> @brief Compares elements of two matrices (or of a matrix and scalar).
> ......
> @param dst Destination matrix that has the same size and type as the input array(s).
> ........

but it performs extremely slow in GPU, so I look at the source code and find:
https://github.com/opencv/opencv/blob/3d141280aa05a6543e98438166aff25970e8ff8f/modules/cudaarithm/src/element_operations.cpp#L286-L295
Actually, the type of the dst is set as CV_8U but not as same as the src.
Compared with the other functions like Add or Subtract:
https://github.com/opencv/opencv/blob/3d141280aa05a6543e98438166aff25970e8ff8f/modules/cudaarithm/src/element_operations.cpp#L176-L185
https://github.com/opencv/opencv/blob/3d141280aa05a6543e98438166aff25970e8ff8f/modules/cudaarithm/src/element_operations.cpp#L164-L173

I'm not sure if it will make the code slow, but I think it's a bug.

**Comment by alalek** [comment]
Result has type `CV_8U` (with final values 0 or `0xff` (255)). Documentation should be fixed.

**Comment by huaweiping** [comment]
More questions @alalek . If I use the compare() to compare two CV_32F by this function, will it be extremely slow as the result is a CV_8U? It costs me half of the computation time which is far beyond my imagination.

Besides, when I use cv::cuda::GpuMat::convertTo() to convert a CV_32F to a CV_8U like this:
```
	cuda::Stream stream;
	buffer.input.upload(input, stream);
	buffer.output.upload(input, stream);
	buffer.input.convertTo(buffer.input, CV_8UC1);
        buffer.output.setTo(Scalar(0),stream);
```
it shows an error:

> OpenCV Error: Gpu API call (unspecified launch failure) in cv::cudev::grid_transform_detail::TransformDispatcher<true, Policy>::call, file d:\opencv\opencv\sources\modules\cudev\include\opencv2\cudev\grid\detail/transform.hpp, line 321

When I use cv::cuda::Stream like this, the error will disappear:



```
	cuda::Stream stream;
	buffer.input.upload(input, stream);
	buffer.output.upload(input, stream);
	buffer.input.convertTo(buffer.input, CV_8UC1, stream);
        buffer.output.setTo(Scalar(0),stream);
```
However, no matter what the next function is , it will always show an error(setTo() as an example):
> OpenCV Error: Gpu API call (unspecified launch failure) in cv::cuda::GpuMat::setTo, file D:/OpenCV/opencv/sources/modules/core/src/cuda/gpu_mat.cu, line 387

Thanks!

**Comment by huaweiping** [comment]
I mean when I use convertTo() to convert a 

> CV_32F

 type GpuMat to a 

> CV_8U

 type, there always be an error.
`buffer.input.convertTo(buffer.input, CV_8UC1); `
The 

> buffer.input

 is a 

> CV_32F

 type. I just upload it from CPU and use convertTo() without any more operation, then the error shows up.
The reason why I use convertTo() is because I want to know if 

> CV_8U

 will perform better than 

> CV_32

 in compare().
BTW, thanks for the advice of tests. But I can't CMake with 

> BUILD_PERF_TESTS

 and 

> BUILD_TESTS
options from this problem https://github.com/opencv/opencv/issues/6716. Appearantly somehthing wrong in the code.

**Comment by dolphinking** [comment]
I met the same problem, opencv3.4 + cuda 8.0 + VS 2015 without BUILD_PERF_TESTS & BUILD_TESTs
