### ISSUE TITLE
built with libpng-1.2.54 but running with ...

### ISSUE THREAD

**Issue by fishcu** [opencv/opencv#12017]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc
- Build system => OpenCV built with CMake, but pulling it into another application that is built using *Bazel*
- Some relevant non-default CMake flags: `BUILD_PNG=ON`, `WITH_OPENGL=ON`, `WITH_QT=ON`, `WITH_GTK=ON`

##### Detailed description
I'm running into the following error when running the application:
`libpng warning: Application built with libpng-1.2.54 but running with 1.6.34`

This ONLY happens when I use a GUI function like:
`cv::namedWindow("image", WINDOW_NORMAL);`

Which leads me to believe that somehow one of the GUI libraries is pulling in an old version of libpng. I am still investigating the issue, and will update once I learn more about it.

**Comment by alalek** [comment]
Probably it is configuration bug that can't be fixed in OpenCV. You should not use 2 instances of the same library (libpng) in application.
Start from disabling own copy of libpng  from OpenCV: remove "BUILD_PNG=ON"

This will show that files are loaded during application run:
```
LD_DEBUG=file <your application path + parameters>
```

Also try to add this flag `-Wl,-Bsymbolic` into linker options (something like `OPENCV_EXTRA_SHARED_LINKER_FLAGS`) during OpenCV build. This forces build-time symbols linking for local known symbols (case of `BUILD_PNG=ON`).

**Comment by nnmm** [comment]
Are you using tensorflow in your project as well, by any chance? I have a similar problem, but I'm not sure how to resolve it. See also https://github.com/tensorflow/tensorflow/issues/1924.

**Comment by fishcu** [comment]
> You should not use 2 instances of the same library (libpng) in application.

This is clear to me, and I know that it is causing hangs/crashes/weirdness when using GUI functions in my setup. I want `BUILD_PNG=ON` in order to have direct control over the libpng version that OpenCV uses.

I have concluded that this problem is indeed related to GTK / QT, both of which use libpng 1.2 (`libpng12.so`). It would require re-compiling these libraries with libpng 1.6 to achieve a consistent version throughout.

> Are you using tensorflow in your project as well, by any chance? I have a similar problem, but I'm not sure how to resolve it. See also tensorflow/tensorflow#1924.
I'm using TensorRT, but I think it's not related. The project does have its own dependency on libpng, however, as it does some image loading itself.

@nnmm, are you, by chance, also using bazel in one form or another?

**Comment by nnmm** [comment]
Yep, bazel too.
