### ISSUE TITLE
opencv3.4.2 dnn problem

### ISSUE THREAD

**Issue by liushuanpeng** [opencv/opencv#12014]
opencv3.4.2 problem：
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/opencv_dnn/bin -DWITH_INF_ENGINE=ON -DINTEL_CVSDK_DIR=$HOME/intel/computer_vision_sdk_2018.2.300/deployment_tools -DIE_PLUGINS_PATH=$HOME/intel/computer_vision_sdk_2018.2.300/deployment_tools/inference_engine/lib/centos_7.3/intel64/ -DOPENCV_EXTRA_MODULES_PATH=/home/liushuanpeng/opencv_dnn/opencv_contrib-3.4.2/modules/ -DENABLE_CXX11=ON -DBUILD_opencv_legacy=ON -DBUILD_opencv_contib=ON -DWITH_TBB=ON -D WITH_IPP=ON -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_gpu=OFF -D BUILD_opencv_stitching=OFF -D BUILD_opencv_xfeatures2d=OFF -D BUILD_opencv_face=OFF -D BUILD_opencv_java=OFF ..

cmake command above，but when i used，the problem is next：

I0719 11:27:05.444959  4491 thread-process.cc:90] [ERROR] obj=predict-handler	requestId=1531970823855923534	event=exception	msg=OpenCV(3.4.2) /home/liushuanpeng/opencv_dnn/opencv-3.4.2/modules/dnn/src/op_inf_engine.cpp:416: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Output blob size is not equal network output size (4!=2). in function 'initPlugin'

**Comment by dkurt** [comment]
@liushuanpeng, please use a forum http://answers.opencv.org for build/install and usage questions.

**Comment by alalek** [comment]
Provided information is not enough.
To help we need reproduce an issue, so description/link about used model is required.

> Failed to initialize

Be sure that you properly run "setupvars.sh" from OpenVINO location.
