### ISSUE TITLE
Inpaint return black image

### ISSUE THREAD

**Issue by kk143g** [opencv/opencv#12011]
i have tried Inpaint by following function

-(UIImage*)messi:(UIImage*)image :(UIImage*)mask
{
    cv::Mat input =  [OpenCVWrapper CVMat3ChannelFromImage:image];
    cv::Mat maskMat =  [OpenCVWrapper CVMat1ChannelFromImage:mask];    
    cv::Mat inpainted;
    inpaint(input, maskMat, inpainted, 3, cv::INPAINT_TELEA);
    UIImage * result = [OpenCVWrapper ImageFromCVMat:inpainted];
    return result;
}

But the result is only black image...i have checked both input image and mask, they are fine, 
Input and mask images are these
![mask](https://user-images.githubusercontent.com/25244255/42891001-aea79712-8ac7-11e8-947f-cdfeae23de40.png)
![mess](https://user-images.githubusercontent.com/25244255/42891003-af147bfc-8ac7-11e8-8440-29835a361782.png)

Updated:

Am using OPencv2 in Swift iOS project by making seperate classes of opencv (C++). 
So am using C++ for OPenCV
I have debugged the problem and the problem is actually 3 channel vs 4 channel cv::Mat.
When i convert UIImage to 3 channel cv::Mat and then convert that 3 channel cv::Mat back to UIImage the image is black always, 
however when i convert my UIImage to 4 channel cv::Mat and then convert that 4 channel cv::Mat back to UIImage the image is fine,

As inpaint function requires 3 channel or 1 channel cv::Mat so i can't use 4 channel cv::Mat,
Any solution for this?

**Comment by mshabunin** [comment]
Please add more information about your configuration: OpenCV version, OS/platform...
It can be output of cmake command or the string returned by `cv::getBuildInformation()` (C++ function) or `cv.getBuildInformation()` (Python function).

**Comment by alalek** [comment]
> As inpaint function requires 3 channel or 1 channel cv::Mat so i can't use 4 channel cv::Mat

`cvtColor()` with `COLOR_BGRA2BGR`.

**Comment by kk143g** [comment]
When should i use this?

**Comment by kk143g** [comment]
Hurrayyy Thanks, it worked, i have used before calling inpaint function..

**Comment by HamzaRehman811** [comment]
Hey @kk143g  are you there?
I am having the same issue I need your help
