### ISSUE TITLE
input layer not found :image_batch in function 'connect'

### ISSUE THREAD

**Issue by zhcroman** [opencv/opencv#12026]
- OpenCV => 4.0
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => g++ 5.4
-->

- modle:  FaceNet  https://drive.google.com/open?id=1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-
  

- dnn::Net net = cv::dnn::readNetFromTensorflow(weights);

 
1. terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-pre) /home/cis/soft/cv/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: image_batch in function 'connect'

**Comment by dkurt** [comment]
@zhcroman, please serialize a graph with `phase_train` turned to false.

**Comment by jaiatncson7** [comment]
Hi, May i know how did you fix this issue? I am also getting this error when i load facenet model as below,
detector = cv2.dnn.readNetFromTensorflow(20180402-114759.pb)

Traceback (most recent call last):
  File "extract_embeddings.py", line 37, in <module>
    detector = cv2.dnn.readNetFromTensorflow(ts_modelPath)
cv2.error: OpenCV(4.1.0-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: image_batch in function 'connect'

can you please tell me how to fix it?
