### ISSUE TITLE
AttributeError: module 'cv2.dnn' has no attribute 'DNN_BACKEND_OPENCV'

### ISSUE THREAD

**Issue by bhomass** [opencv/opencv#12023]
I built opencv 3.4.1 on my mac. tried to run samples/dnn/object_detection.py, and got

AttributeError: module 'cv2.dnn' has no attribute 'DNN_BACKEND_OPENCV'

can't find any help by googling. What could be wrong with my setup?

**Comment by dkurt** [comment]
> 3.4.1

`samples/dnn/object_detection.py` was introduces only in OpenCV 3.4.2 (https://github.com/opencv/opencv/pull/10979). Please update your library or use samples from the same version: https://github.com/opencv/opencv/tree/3.4.1/samples/dnn.
