### ISSUE TITLE
Build fails on Arm GCC 4.8.4

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#12027]
##### System information (version)

- OpenCV => recent master ( 7198b9e )
- Operating System / Platform => Ubuntu 14.04 Arm 32bit / ODROID-X2
- Compiler => GCC 4.8.4

##### Detailed description
I'm building OpenCV with following CMake option
```
cmake -DCPU_BASELINE=FP16 -DNEON=ON ..
```
Building fails with message ``` error: 'float16x8_t' was not declared in this scope```
```
In file included from /home/odroid/opencv-fork/modules/core/include/opencv2/core/hal/intrin.hpp:137:0,
                 from /home/odroid/opencv-fork/modules/core/src/precomp.hpp:85,
                 from /home/odroid/opencv-fork/modules/core/src/matrix_operations.cpp:9:
/home/odroid/opencv-fork/modules/core/include/opencv2/core/hal/intrin_neon.hpp:283:47: error: 'cv::hal_baseline::vreinterpretq_s16_f16' declared as an 'inline' variable
 static inline int16x8_t vreinterpretq_s16_f16(float16x8_t a) { return (int16x8_t)a; }
                                               ^
/home/odroid/opencv-fork/modules/core/include/opencv2/core/hal/intrin_neon.hpp:283:47: error: 'float16x8_t' was not declared in this scope
```
Entire log is available [here](https://gist.github.com/tomoaki0705/14b0e044cdfccb2d9f4855604d0f4b62)

Looking in the ```arm_neon.h```, in GCC 4.8.4, ```float16x8_t``` is not defined.
Looking in the ```arm_neon.h```, in GCC 4.9.2, ```float16x8_t``` is defined.

The current implementation (after #11953) is treating ```CV_FP16``` flag that the compiler also accepts ```float16x8_t```, which is not equal condition.

https://github.com/opencv/opencv/blob/ad51b1579d252c28999bdda85cdbb8bfbf82ab4c/modules/core/include/opencv2/core/hal/intrin.hpp#L278-L279

##### Discussion
There is always the discussion about which way to go 
1. Fix by ifdef (Keep 4.8.4 in the support list)
2. Workaround by ifdef (Keep 4.8.4 in the support list)
3. Ignore (remove 4.8.4 from the support list)

My current approach is to add new ```define```, ```CV_HAVE_FP16x8``` and define it as 0 if 
  * the compiler is GCC and
  * the compiler is 4 series or earlier and
  * the compiler is for Arm (32bit)
otherwise, define ```CV_HAVE_FP16x8``` as 1
Then we can have a workaround.

Still, ODROID-X2 is a relatively old platform, Ubuntu 14.04 is EOL next in next April.
So, ignoring this issue is something reasonable choice.

**Comment by mshabunin** [comment]
We can also add usage of this type to the cmake check: https://github.com/opencv/opencv/blob/master/cmake/checks/cpu_fp16.cpp

**Comment by tomoaki0705** [comment]
True.  I think that's the cleanest way.  I'm not sure about the behavior of gcc4.9, and it's another reason to use cmake to avoid this situation.

**Comment by alalek** [comment]
Problem code should be guarded by `CV_FP16` or `CV_FP16_TYPE` (for exact `__fp16` type) macro.

**Comment by tomoaki0705** [comment]
@alalek, I looked the log.
The Arm builder is not activating the FP16 feature.
```
--   CPU/HW features:
--     Baseline:                    VFPV3 NEON
--       requested:                 DETECT
--       required:                  VFPV3 NEON
```
This can be confirmed from the [test log](http://pullrequest.opencv.org/buildbot/builders/master_ARMv7-lin/builds/10520/steps/distributed%20test/logs/log_1.txt), too
```
CTEST_FULL_OUTPUT
OpenCV version: 4.0.0-pre
OpenCV VCS version: 3.4.2-170-g7e9b5d9
Build type: release
Parallel framework: pthreads
CPU features: neon
```

On the other hand, on ODROID-X2, I'm using FP16 as a baseline.
```
--   CPU/HW features:
--     Baseline:                    NEON FP16
--       requested:                 FP16
--       required:                  NEON
--       disabled: VFPV3
```

So, my guess is, if we add ```-DCPU_BASELINE=FP16 ``` option to the cmake configuration, the same issue will raise.


```CV_FP16``` is doing the right thing, but some compiler doesn't accept ```float16x8_t``` so we need something more fine flag.

**Comment by alalek** [comment]
@tomoaki0705 Thank you!

I'm able to reproduce issue on [our CI ARM builder](http://pullrequest.opencv.org/buildbot/builders/precommit_armv7/builds/10915).

Looks like compiler:
- supports `float16x4_t`
- but it doesn't support `float16x8_t`

So existed set of defines (`CV_FP16_TYPE`) doesn't help, perhaps we need new one (we will take a look on this).

**Comment by alalek** [comment]
@tomoaki0705 Could you please take a look on #12256 ?
