### ISSUE TITLE
Imgproc.rectangle Method not work in Android

### ISSUE THREAD

**Issue by MRYangY** [opencv/opencv#12039]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform =>Ubuntu/Android studio
- Compiler => cmake

##### Detailed description

i find execute Imgproc.rectangle no any response in Android.
The specific code is as follows:
      
    onPreviewFrame(byte[] data, Camera camera){
     mSrcMat = new Mat(CameraHelper.getInstance().getPreviewSize().getHeight(),CameraHelper.getInstance().getPreview 
     Size().getWidth(), CvType.CV_8UC1);
        mSrcMat.put(0,0,data);
        if (!isTrackerInit) isTrackerInit = mTracker.init(mSrcMat,mSelectArea);
        isUpdate = mTracker.update(mSrcMat,mSelectArea);
        Imgproc.rectangle(mSrcMat,mSelectArea.tl(),mSelectArea.br(),new Scalar(255,0,0),5);}
##### Steps to reproduce

please help me,thanks

**Comment by MRYangY** [comment]
No rectangle is displayed on the screen  when execute Imgproc.rectangle(mSrcMat,mSelectArea.tl(),mSelectArea.br(),new Scalar(255,0,0),5);

**Comment by MRYangY** [comment]
Did you close the question without responding?

**Comment by MRYangY** [comment]
@alalek

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by sturkmen72** [comment]
outdated common question can be closed down.
