### ISSUE TITLE
Opencv fails to read Caffe frozen graph with dnn module

### ISSUE THREAD

**Issue by mttakai** [opencv/opencv#12030]
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 14.04, 18.04 / Win10
- Compiler => gcc4.8, gcc 7

##### Detailed description

I am trying to load a frozen model in Caffe into Opencv, but the following error persists.
Seems like that is a parsing error, getting wrong identifier (I could not trace where). It happens for different frozen models (different sources - from authors, etc).

##### Steps to reproduce
Loading the frozen graphs
```.python
 net = cv.dnn.readNetFromCaffe('pose_deploy_linevec.prototxt','pose_iter_160000.caffemodel')
```

I get the error (even in different OS):
```
[libprotobuf ERROR D:\Build\OpenCV\opencv-3.4.2\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 1:1: Expected identifier, got: <
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(3.4.2) D:\Build\OpenCV\opencv-3.4.2\modules\dnn\src\caffe\caffe_io.cpp:1147: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: pose_deploy_linevec.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'
```

**Comment by dkurt** [comment]
@mttakai, it looks like a duplicate comparing to https://github.com/opencv/opencv/issues/11432. Check that you have valid files.

**Comment by mttakai** [comment]
@dkurt, thank you!
