### ISSUE TITLE
Opencv 4.0.0-pre Large image error

### ISSUE THREAD

**Issue by abenchaaben** [opencv/opencv#12049]
Hi,

I'm trying to pass a huge Mat image (98304x51968) between openCV (4.0.0-pre) and itk using the ITK to openCV Bridge. I have an error :

Insufficient memory (OverFlow for imageSize) in cvIniyImageHeader, file opencv\modules\core\src\array.cpp line 2961.

Is that mean that opencv have a limit on the size of images?

Thank's in advanced.

**Comment by alalek** [comment]
> 4.0.0
> cvInitImageHeader

Avoid using old legacy API from OpenCV 1.0 with modern OpenCV.
Huge images are not supported by old API and will not be get fixed due compatibility reasons.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
