### ISSUE TITLE
OpenCV failed to run 9 tests in opencv_test_objdetect.exe

### ISSUE THREAD

**Issue by shanshan0309** [opencv/opencv#12045]
Hi All,

OpenCV failed to run 9 tests in opencv_test_objdetect.exe on Windows with VS2017 Update 7. Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/opencv/opencv D:\OpenCV\src
2. git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
3. Open a VS 2017 x86 prompt and browse to D:\OpenCV
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6. msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
7. .\bin\Release\opencv_test_objdetect.exe

**Error info:**
The whole log file please see attachment.
[opencv_test.log](https://github.com/opencv/opencv/files/2222804/opencv_test.log)
[----------] 9 tests from objdetect/Objdetect_QRCode
[ RUN      ] objdetect/Objdetect_QRCode.regression/0, where GetParam() = "20110817_030.jpg"
unknown file: error: C++ exception with description "OpenCV(3.4.2-dev) d:\opencv\src\modules\objdetect\src\qrcode.cpp:788: error: (-215:Assertion failed) !inarr.empty() in function 'cv::QRCodeDetector::detect'
" thrown in the test body.
[  FAILED  ] objdetect/Objdetect_QRCode.regression/0, where GetParam() = "20110817_030.jpg" (0 ms)

…

[ RUN      ] objdetect/Objdetect_QRCode.regression/8, where GetParam() = "qr_test_030.jpg"
unknown file: error: C++ exception with description "OpenCV(3.4.2-dev) d:\opencv\src\modules\objdetect\src\qrcode.cpp:788: error: (-215:Assertion failed) !inarr.empty() in function 'cv::QRCodeDetector::detect'
" thrown in the test body.
[  FAILED  ] objdetect/Objdetect_QRCode.regression/8, where GetParam() = "qr_test_030.jpg" (0 ms)
[----------] 9 tests from objdetect/Objdetect_QRCode (2 ms total)

**Comment by alalek** [comment]
Current error message is very unclear.
Perhaps it is related to missing tests data, or missing image codec to read data file.
Try to update code of both repositories (opencv/opencv_extra) to the same date of the **same branch**.

Messages for these tests are improved here: #12047.

**Comment by shanshan0309** [comment]
Hi @alalek,
Thanks for looking into this issue.  Opencv works well on the latest master revision after I updated the code of both repositories (opencv/opencv_extra). 
Thanks,
Shanshan
