### ISSUE TITLE
cv2.seamlessClone automaticly change mask without warning

### ISSUE THREAD

**Issue by betterze** [opencv/opencv#12053]
##### System information (version)
- OpenCV => 3.4.1 & 3.4.2
- Operating System / Platform => Windows 10 64 Bit & Linux
- Compiler => pip install

##### Detailed description
The cv2.seamlessClone function asks users to input a mask, and changes the mask automatically without warning users. 

##### Steps to reproduce
just call 
```python
plt.figure()
ps_image=cv2.seamlessClone(source_rgb,dest_rgb,mask,p,cv2.MIXED_CLONE)
plt.subplot(121)
plt.imshow(mask)
ps_image=cv2.seamlessClone(source_rgb,dest_rgb,mask,p,cv2.MIXED_CLONE)
plt.subplot(122)
plt.imshow(mask)
```
you will find the result are different. Thank you for your help.
![mask](https://scontent.flhr5-1.fna.fbcdn.net/v/t1.0-9/37712747_1061751780639473_2443950242417082368_n.jpg?_nc_cat=0&oh=b187d0034ca302a08150f19e9e22cfd2&oe=5BCFBB10)

**Comment by sturkmen72** [comment]
https://github.com/opencv/opencv/blob/master/modules/photo/src/seamless_cloning_impl.cpp#L330

**Comment by alalek** [comment]
Try to change [this](https://github.com/opencv/opencv/blame/3.4.2/modules/photo/src/seamless_cloning.cpp#L70) :
```.diff
-gray = mask;
+mask.copyTo(gray);
```
