### ISSUE TITLE
SSD-mobilenet is working in object detection, but opencv is giving error while reading mobilenet trained model for classification.

### ISSUE THREAD

**Issue by amaresh943** [opencv/opencv#12066]
##### System information (version)
<!-- Example
- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
The SSD-Mobilenet is working successfully in opencv dnn (object detection), but tensorflow trained mobilenet model is not working for classification. Please help!!! thanks

**Comment by dkurt** [comment]
@amaresh943, please provide references to mentioned models.

**Comment by amaresh943** [comment]
@dkurt  firstly, I used the pretrained model ckpt from here https://github.com/tensorflow/models/tree/master/research/slim#freezing-the-exported-graph 
and generated .pb and .pbtxt, but it is not working in opencv.
secondly, I also tried to use .pb and .pbtxt file from here 
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md
but it is also not working.

**Comment by dkurt** [comment]
@amaresh943, thank you. As a workaround, you can do the following:

Generate a text graph representation:
```python
import tensorflow as tf

# Read the graph.
with tf.gfile.FastGFile('mobilenet_v1_1.0_224_frozen.pb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# Remove Const nodes.
for i in reversed(range(len(graph_def.node))):
    if graph_def.node[i].op == 'Const':
        del graph_def.node[i]
    for attr in ['T', 'data_format', 'Tshape', 'N', 'Tidx', 'Tdim',
                 'use_cudnn_on_gpu', 'Index', 'Tperm', 'is_training',
                 'Tpaddings']:
        if attr in graph_def.node[i].attr:
            del graph_def.node[i].attr[attr]

# Save as text.
tf.train.write_graph(graph_def, "", "text_graph.pbtxt", as_text=True)
```

Then open `text_graph.pbtxt` and comment the last two layers:
```yaml
# node {
#   name: "MobilenetV1/Predictions/Shape"
#   op: "Shape"
#   input: "MobilenetV1/Logits/SpatialSqueeze"
#   attr {
#     key: "out_type"
#     value {
#       type: DT_INT32
#     }
#   }
# }
# node {
#   name: "MobilenetV1/Predictions/Reshape_1"
#   op: "Reshape"
#   input: "MobilenetV1/Predictions/Softmax"
#   input: "MobilenetV1/Predictions/Shape"
# }
```
Use `text_graph.pbtxt` as a second argument of `cv::readNet`.

We'll propose a PR which will solve that problem.

**Comment by dkurt** [comment]
@amaresh943, please test the changes from a PR https://github.com/opencv/opencv/pull/12128. I've tested it with `mobilenet_v1_1.0_224` from https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md#pre-trained-models.

**Comment by amaresh943** [comment]
@dkurt sorry for not replying these days. I tried your first way to solve this problem, but while I am generating text_graph.pbtxt, I am getting an error at this line "" graph_def.ParseFromString(f.read()) 
""
the error is "" UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 38: invalid start byte""
I tried to solve this problem by using this link https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in
but still, I am facing the problem with this line in your code.

**Comment by dkurt** [comment]
@amaresh943, I'm sorry. Please replace the line
```python
with tf.gfile.FastGFile('mobilenet_v1_1.0_224_frozen.pb') as f:
```
to
```python
with tf.gfile.FastGFile('mobilenet_v1_1.0_224_frozen.pb', 'rb') as f:
```

**Comment by amaresh943** [comment]
@dkurt thanks for your reply.  I generated the .pbtxt file successfully, but it is still not working in opencv.
It is giving the following error given below.

MobilenetV1/Logits/SpatialSqueeze:Squeeze(MobilenetV1/Logits/Conv2d_1c_1x1/Conv2D)
squeeze_dims:[ ]
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Squeeze in op MobilenetV1/Logits/SpatialSqueeze) in cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1582

**Comment by xinyuabcd** [comment]
@dkurt How dose MobilenetV2 generate text_graph.pbtxt？  I tried your way on the MobilenetV2model, it still got error “ Unspecified error (Input layer not found: MobilenetV2/Conv/
BatchNorm/FusedBatchNorm) in cv::dnn::experimental_dnn_v5”

**Comment by amaresh943** [comment]
@xinyuabcd is MobilenetV1 model is working in opencv c++ for classification task??

**Comment by xinyuabcd** [comment]
@amaresh943 Yes, MobilenetV1 model can work in opencv c++ well.

**Comment by amaresh943** [comment]
@xinyuabcd can you please send me mobilenet .pbtxt file, c++ source code of opencv c++ at amaresh1808@gmail.com
thanks.

**Comment by xinyuabcd** [comment]
@amaresh943  The c++ source code is just the source code of opencv3.4.2, called "classification.cpp".
The .pbtxt file is generated by dkurt's way, and it  is only applied to the  pretrained model , cann't be applied to finetuning mobileNetV1

**Comment by amaresh943** [comment]
@dkurt @xinyuabcd thanks to all... now its working

**Comment by gaolaowai** [comment]
Hi, is there any plan at all to support retrained networks, such as from this [tensorflow tutorial](https://www.tensorflow.org/hub/tutorials/image_retraining)?

It uses a script located [here](https://github.com/tensorflow/hub/raw/master/examples/image_retraining/retrain.py).

It seems like doing so would greatly increase the rate of adoption and popularity of this module.
