### ISSUE TITLE
ainer_avi.cpp:error:(-215) pos < (1u<<31) in function patchInt

### ISSUE THREAD

**Issue by wait1988** [opencv/opencv#12076]
##### System information (version)
OpenCV 3.4.1
Ubuntu16.04
Cmake

##### Error Msg
Failed to save video,the error msg is :ainer_avi.cpp:error:(-215) pos < (1u<<31) in function patchInt
Anyone knows how to fix it?

**Comment by alalek** [comment]
Don't create duplicate issues: #11841 (always use search before adding new).

> OpenCV 3.4.1

You should upgrade OpenCV - problem should be fixed in the latest code.
