### ISSUE TITLE
Integrate gPb edge detection for OpenCV 4.0

### ISSUE THREAD

**Issue by vadimkantorov** [opencv/opencv#12072]
as implemented during GSoC in https://github.com/hiDiYANG/gPb-GSoC/ and https://github.com/vrabaud/gPb/tree/master/grouping/source/opencv_gpb

https://github.com/opencv/opencv/issues/4494 mentions that there had been licensing issues, but @vrabaud said that they were resolved.

**Comment by alalek** [comment]
No need to create duplicate issues. Just update existed one about this: #4494
