### ISSUE TITLE
CAP_PROP_FRAME_COUNT &  CAP_PROP_POS_FRAMES do not work

### ISSUE THREAD

**Issue by kanehekili** [opencv/opencv#12091]
Beginning with the latest version, no access to frame size or positioning is possible.
Setter methods will return False, getter will return 0.0. 
CAP_PROP_FRAME_COUNT returns -1
Version 3.4.1 runs perfectly

##### System information (version)

- OpenCV = 3.4.2-1
- Operating System / Platform => arch Linux
- Compiler => gcc

##### Detailed description
The errors occured using opencv with python (2.7 and 3.6)

**Comment by kanehekili** [comment]
How to reproduce:
Either write each line in the python console or create a file...

> import cv2
> cap=cv2.VideoCapture("XXX.mp4") 
> w = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
> cnt = cap.get(cv2.CAP_PROP_FRAME_COUNT)
> print("Opencv width %d frames %d"%(w,cnt))
> cap.release()

**Expected output:** 
_Opencv width 720 frames 9000_
**Current Result:**
_Opencv width 720 frames -1_

Hopefully this clears things up. In cv2 version 3.4.1 everything works

**Comment by alexriss** [comment]
I have the same problem. opencv 3.4.3 under manjaro,

this type of file gives -1.0 as the total number of frames (CAP_PROP_FRAME_COUNT):
H264 - MPEG-4 AVC (part 10) (avc1)

this type of file seems to behave correctly:
Motion JPEG Video (MJPG)

**Comment by kanehekili** [comment]
The problem seems to be related to the gstreamer bindings. Previous versions of opencv were compiled with ffmpeg, the Version 3.4.3 is compiled with gstreamer. So possibly setting of the stream via frame number might not work. Still we would need at least either a working CAP_PROP_FRAME_COUNT or some a new "CAP_PROP_TOTAL_TIME".

**Comment by alalek** [comment]
Please refer to documentation how to specify wanted Video I/O backend, because "defaults" doesn't work for you.

**Comment by kanehekili** [comment]
@alalek ,thank you for your response. The documentation says, that i can read the number of frames using CAP_PROP_FRAME_COUNT. So it should work on all streams & underlying libraries. Currently my application is broken, which has run for over 4 years using opencv and its documented API. Same applies to setting a frame using the CAP_PROP_POS_FRAMES, which doesn't work, whereas CV_CAP_PROP_POS_MSEC still works.

**Comment by alalek** [comment]
Actually this code is here for years too. But build flags are changed on your side, enabling new backends.

The documentation says:

> **Note**: Each backend supports devices properties (cv::VideoCaptureProperties) in a different way or might not support any property at all.

https://docs.opencv.org/3.4/d0/da7/videoio_overview.html

"-1" value is a special value, which means that this property is not supported by current backend, or it is not supported for current stream.

P.S. Suggestion to hold wanted backend is above.

**Comment by kanehekili** [comment]
I concur. The backend has changed in Arch (for whatever reasons), and functionality has dropped. Compiling opencv with the ffmpeg flags leads to the desired results. 
From my point of view the issue is solved. Thanks for your help and this great piece of software!
