### ISSUE TITLE
Philips SPC900NC is not recognized

### ISSUE THREAD

**Issue by siliconsensor** [opencv/opencv#12107]
##### System information (version)
- OpenCV => 3.4.2 (compiled)
- Operating System / Platform => Ubuntu Studio 16.04 64 Bit
- Python3 => 3.5.2

##### Detailed description

The Philips SPC900NC webcam is not recognized. Error message: VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Available video modes: v4l2-ctl -d /dev/video0 --list-formats
Gives:

ioctl: VIDIOC_ENUM_FMT

	Index       : 0
	Type        : Video Capture
	Pixel Format: 'PWC2' (compressed)
	Name        : Raw Philips Webcam Type (New)

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YU12'
	Name        : Planar YUV 4:2:0

However, the SPC900NC works well with VLC:

Stream 0

	Type: video
	Codec: Planar 4:2:0 YUV (I420)
	Resolution: 640x480
	Display Resolution: 640x480
	Frame rate: 15
	Location: v4l2:///dev/video0

Looks like there is a confusion with opencv between YU12 and I420. A workaround had been found a long time ago (http://nuigroup.com/forums/viewthread/291/) so it should be possible to adapt opencv for the camera to be recognized.

##### Steps to reproduce

import numpy as np
import cv2

cap = cv2.VideoCapture(0)

##### Note: successfully tested with another webcam (Logitech C525 HD).

**Comment by mshabunin** [comment]
Did you try the proposed patch? If it works you can submit pull request with the fix.

To gather more information try to build OpenCV in Debug mode (`-DCMAKE_BUILD_TYPE=Debug` cmake parameter) and check messages printed by [these lines](https://github.com/opencv/opencv/blob/57bead3a5e385d62068f4197001ca7e28b28d6e8/modules/videoio/src/cap_v4l.cpp#L389-L419).

**Comment by siliconsensor** [comment]
Hi,
No, I did not try this patch because it is old (2007) and it does not seem to match the current cap_v4l.cpp file.  For example:
-int  PALETTE_BGR24 = 0,
+int  PALETTE_YUV420P = 0,

I can't find PALETTE... definition in the current file. And there are many other differences like that.

After building opencv in Debug mode, here is the output from Terminal:

[ INFO:0] VIDEOIO: Enabled backends(3, sorted by priority): V4L2(1000); CV_IMAGES(990); CV_MJPEG(980)
(DEBUG) V4L: opening /dev/video0
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
(DEBUG) V4L: opening /dev/video0
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

I don't see any "(DEBUG) try_init_v4l2 VIDIOC..." message.

**Comment by mshabunin** [comment]
Yes, this patch looks obsolete.

You can try adding your camera format (V4L2_PIX_FMT_Y**U**V420 -> YU12) to [this list](https://github.com/opencv/opencv/blob/57bead3a5e385d62068f4197001ca7e28b28d6e8/modules/videoio/src/cap_v4l.cpp#L433) and several other places (same as V4L2_PIX_FMT_Y**V**U420). And convert the frame using function similar to [this one](https://github.com/opencv/opencv/blob/57bead3a5e385d62068f4197001ca7e28b28d6e8/modules/videoio/src/cap_v4l.cpp#L1023-L1028) but using `COLOR_YUV2BGR_IYUV` mode of cvtColor.

**Comment by siliconsensor** [comment]
Awesome! That seems to work perfectly.
Here's my test script:

```
import sys
sys.path.append('/home/christophe/.local/lib/python3.5/dist-packages')
import numpy as np
import cv2

#print(cv2.__version__) # 3.4.2
cap = cv2.VideoCapture("/dev/video0") # or 0

cap.open("/dev/video0")
if (cap.isOpened()):
    print("cap.isOpened() = True")
else:
    print("cap.isOpened() = False")

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
	
    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # works with Philips SPC900NC as well as Logitech HD C525
    
    #height, width, channels = frame.shape
    #print(height, width, channels)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

And here is the output from Terminal:

[ INFO:0] VIDEOIO: Enabled backends(3, sorted by priority): V4L2(1000); CV_IMAGES(990); CV_MJPEG(980)
(DEBUG) V4L: opening /dev/video0
(DEBUG) V4L: opening /dev/video0
cap.isOpened() = True

** (frame:18198): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-FwKJusjdmx: Connexion refusée

Despite this Warning, everything seems fine.

In attachment: the modified cap_v4l.cpp file and a list of changes (unfortunately, I really don't know how to write a patch).
Thanks a lot for your help.
[cap_v4l.cpp.txt](https://github.com/opencv/opencv/files/2246331/cap_v4l.cpp.txt)
[List_of_changes.txt](https://github.com/opencv/opencv/files/2246341/List_of_changes.txt)

**Comment by CJSmith-0141** [comment]
If you can test the result (I do not own this camera), I can make a pull request with this change. Or, just follow the [Contribution Guide.](https://github.com/opencv/opencv/wiki/How_to_contribute)

In your case, the basic steps are as follows. 

1. Fork the main repository and clone your forked repo to your local machine. 
2. Make a new branch (something like AddsPhilipsSPC900NC) and commit your changes. 
3. Make sure it builds locally and recognizes the camera. 
4. Draft and submit a Pull Request. 

I just did this for the first time and it wasn't too hard! I just followed the guide.

**Comment by mshabunin** [comment]
@siliconsensor , I've ported your patch in more compact form. Please check whether the fix in PR #12134 still works for you.

**Comment by siliconsensor** [comment]
As I'm new to GitHub, I don't understand how to apply your patch. What I have done is:
```
git clone https://github.com/siliconsensor/opencv.git
cd opencv
git checkout -b AddsPhilipsSPC900NC
```

`git branch` gives me:
```
* AddsPhilipsSPC900NC
  master
```

That's OK until here, but #12134 is not listed when asking:
`git log --pretty=oneline -100` or `git log`

So, I can't use something like `git am --signoff -k < <name>.patch`
Is there another way ? How to get the .patch file ?
(Sorry for theses newbie questions)

**Comment by siliconsensor** [comment]
Thanks! I just wrote a comment about #12134. The capture is only in B&W but in my case it is not an issue because this webcam will only used for polar alignment for astrophotography (see an old software I wrote for OSX: https://www.macupdate.com/app/mac/31111/mise-en-station). I plan to develop a similar software in Python3 on Ubuntu.
I can perform further tests if needed.

**Comment by jeanfrancois42pin** [comment]
hello
I am new in this use of github...
Can you help please !!

I read that you say and I am very interested by your solution about SPC900NC.
But I don't understand how use the file cap_v4l.cpp .
I don't finded this file on my raspberry. I don't understand how install that.

in my machine:
>>> cv2.__version__
'3.4.4'

python3 -V
Python 3.5.3

lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

Many thanks
