### ISSUE TITLE
Rect operator- is missing from types.hpp

### ISSUE THREAD

**Issue by kevinra** [opencv/opencv#12108]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => macOS 10.13.6
- Compiler => LLVM 9.1.0

##### Detailed description
According to the documentation, both + and - operators are supported on Rect:
𝚛𝚎𝚌𝚝=𝚛𝚎𝚌𝚝±𝚜𝚒𝚣𝚎 
However, types.hpp doesn't contain operator -. Is this to prevent size from being negative? Whether it's a feature or not, either documentation or the header file must be updated.

**Comment by alalek** [comment]
1. `operator -` should validate (via CV_Check/CV_DbgAssert) correctness of the result (negative `.width` / `.height` must be forbidden).
2. Add tests with valid and invalid input
3. Prepare patch onto 3.4 branch

Operator `-=` exists (but there is no checks):
```
template<typename _Tp> static inline
Rect_<_Tp>& operator -= ( Rect_<_Tp>& a, const Size_<_Tp>& b )
{
    a.width -= b.width;
    a.height -= b.height;
    return a;
}
```
