### ISSUE TITLE
Update libjpeg-turbo to v2.0.0

### ISSUE THREAD

**Issue by peters** [opencv/opencv#12115]
A new stable release for `libjpeg-turbo` has been released. https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.0

@alalek Is there a reason why SIMD support has been omitted in the cmake file? I'd like to get rid of my custom libjpeg-turbo build in favor of opencv official sources and SIMD support is critical to us.

Would you accept a PR where SIMD support is at least opt-in, e.g. `OPENCV_LIBJPEG_TURBO_WITH_SIMD` ?

**Comment by jazozaya** [comment]
Hello,

I know this a pretty old post.  Just wondering if the turbo optimizations are still disabled by default. 

Installing OpenCV on a Jetson Nano, it was defaulting to the libjpeg library, using the build flags WITH_JPEG=ON and BUILD_JPEG=ON I was able to force it to use libjpeg-turbo  (confirmed with the buildInformation)... However my encoding time actually increased (by 3x) when using libjpeg-turbo.

Is there any way to force it use the SIMD optimizations when building?  Or is it better to build libjpeg-turbo from source and somehow point OpenCV to the library?

**Comment by catree** [comment]
On Linux, you should be able to install `libjpeg-turbo` from your distribution package management.
For instance on Ubuntu: https://packages.ubuntu.com/impish/libjpeg-turbo8-dev

**Comment by sturkmen72** [comment]
This can be closed as completed.
