### ISSUE TITLE
readNetFromTensorflow fails to load new SSD-based architectures

### ISSUE THREAD

**Issue by mnnejati** [opencv/opencv#12114]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Hi,
Currently, I have been trying to load two new SSD-based object detection models from [Tensorflow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) including **ssd_mobilenet_v1_ppn_coco** and **ssd_mobilenet_v1_fpn_coco**, but readNetFromTensorflow method cannot load the net and I got the following error:

```
Exception: OpenCV(3.4.2) C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dn
n\src\tensorflow\tf_importer.cpp:495: error: (-2:Unspecified error) Input layer
not found: BoxPredictor_0/ClassPredictor/BiasAdd in function 'cv::dnn::experimen
tal_dnn_v5::`anonymous-namespace'::TFImporter::connect'
```

**Comment by mnnejati** [comment]
@dkurt, I don't know how to do test the changes you have mentioned. Should I build the opencv with extra modules from source? Another problem I have is that tf_text_graph_ssd.py does not take the following argument: --not_reduce_boxes_in_lowest_layer ,  --box_predictor

Could you please give me a more detailed explanation of your solution?
regards

**Comment by dkurt** [comment]
@mnnejati, The PR has been merged. Please update your local version of library.
