### ISSUE TITLE
Problems with cv.data file that has to be with cv.js

### ISSUE THREAD

**Issue by ferjif** [opencv/opencv#12122]
##### System information (version)

- OpenCV => 3.4 (js)
- Operating System / Platform => linux 64 bit
- Compiler => javascript (no compiler)

##### Detailed description

I have been trying to use opencv.js with an electron project that I have been working on. At first i ran into some issues of importing it. it was so large that webpack would break. so i included it in my index.html file as a script tag and put it in the static folder then added a new CopyWebpackPlugin line to the webpack config that copied the files in the static folder to the dev server's static folder and the build static folder. the xmlHttpRequest in the cv.js file tried to get cv.data so i put it beside that. no it works fine in dev mode. but in build mode it cannot locate the cv.data file. I think it is because of the file access restrictions of the xmlHttpRequest object. is there any way to replace this protocol with the fs module in js or remove the dependency that opencv.js has to cv.data completely? I have been working on it but no luck so far.

##### Steps to reproduce

go to the http://vuetifyjs.com in the get started tab find the electron boilerplate. follow the steps and create the project then add the cv.js and cv.data file to the static folder in the project folder then add the line new CopyWebpackPlugin([{from: path.join(__dirname,'../static')}]) to the webpack.renderer.config.js file under the adjust rendererconfig for development settings comment in the if(process.env.NODE_ENV !== 'production') scope. then run npm run dev and in the dev tools see that it says runtime ready
for production build first add the line mainWindow.webContents.openDevTools(); to the index.js file in src/main folder then run the script npm run build in the terminal then go into the build folder created in the project folder then go there and open the app you will see in the devtools that it won't load cv.data and will have an error err::FILE_NOT_FOUND

**Comment by berak** [comment]
i'm no webdev, and i can't follow you through the webpack/vuetify/node dungeon, 
but to my knowledge, to use opencv's js bindings, one would need [opencv.js](https://docs.opencv.org/master/opencv.js) and [utils.js](https://docs.opencv.org/master/utils.js)

it neither has a `cv.js` nor a `cv.data` there.
