### ISSUE TITLE
cornerSubPix crashes with RGB input image.

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#12132]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015 64 bit

##### Detailed description

cv::cornerSubPix crashes when input image is RGB 

##### Steps to reproduce
std::vector<cv::Point2f> camera1ImagePoints;

cv::Mat src1; //rgb image with 1920*1200*3 pixels

cv::Size boardSize(8, 6);

cv::findChessboardCorners(src1, boardSize, camera1ImagePoints);

cv::cornerSubPix( src1, camera1ImagePoints, cv::Size(11,11), cv::Size(-1,-1),
                          cv::TermCriteria( CV_TERMCRIT_EPS+CV_TERMCRIT_ITER, 30, 0.1 ));

**Comment by alalek** [comment]
> CV_Assert( src.channels() == 1 );

RGB images are not supported.
Please read crash reports carefully.

**Comment by berak** [comment]
documentation problem, i guess. but looking at it, there's also this:

https://github.com/opencv/opencv/blob/da41ac9e601a11b503753d4ebe9e20930ecf0f30/modules/imgproc/src/cornersubpix.cpp#L58-L62

(if there's an assert already, the return statement is redundant, right ?)

**Comment by tompollok** [comment]
Sorry i did not see the assertion when debugging.

Can i create a pullrequest that adds the information that only grayscale is supported as an input image?

Does it make sense to also add such an assert to findChessboardCorners?

**Comment by tompollok** [comment]
thanks @berak  you were faster ;-)

**Comment by berak** [comment]
oh, @tompollok , if you want to do this, i'll just close mine ! 

(you found it, your honour here :)
