### ISSUE TITLE
Tests fails (missing files?)

### ISSUE THREAD

**Issue by extrowerk** [opencv/opencv#12148]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Haiku
- Compiler => GCC 7.3.0

##### Detailed description

Testlogs:
```
[----------] 1 test from Core_globbing
[ RUN      ] Core_globbing.accuracy
/sources/opencv-3.4.2/modules/core/test/test_io.cpp:552: Failure
Expected: (lenas.size()) > (pngLenas.size()), actual: 0 vs 0
[  FAILED  ] Core_globbing.accuracy (0 ms)
[----------] 1 test from Core_globbing (0 ms total)
```
This is not the only failing test.

Current recipe: https://github.com/haikuports/haikuports/pull/2891

##### Steps to reproduce

I did an out of tree build. As far as i can see, the testcases cannot find the assets file, thus fails. (But unsure)

```
mkdir build_haiku && cd build_haiku
cmake ..
make test
```

**Comment by alalek** [comment]
Test data is here: https://github.com/opencv/opencv_extra/tree/3.4.2/testdata (use proper tag/branch/commit).
Specify `OPENCV_TEST_DATA_PATH` environment variable before launching test.
