### ISSUE TITLE
slack link is wrong on opencv.org

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#12158]
I give slack link(https://join.slack.com/t/open-cv/shared_invite/MjE1NTkxMDkzMzUwLTE1MDA0NTYxODMtYTc0NjE1NjI5OQ opencv.org page )  to @ardashir66 (https://gitter.im/opencv-infrastructure/answers.opencv.org)  but there is a problem with this link : link is unvailable

**Comment by mshabunin** [comment]
I've moved this issue here: opencv-infrastructure/opencv.org#30
