### ISSUE TITLE
Not working  in Android phone the play store version 

### ISSUE THREAD

**Issue by SailiMukadam** [opencv/opencv#12153]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by SailiMukadam** [comment]
Bad app

**Comment by alalek** [comment]
Application in Google App store is outdated and doesn't support modern devices. Do not use it anymore.

**Comment by hannesa2** [comment]
please remove non-working versions from Playstore
