### ISSUE TITLE
TypeERROR: no matching UMat constructor found/supported

### ISSUE THREAD

**Issue by masterchop** [opencv/opencv#12152]
I build opencv with opencl support, i am able to use opencl code and works but when i try the:

 frame = cv2.UMat(vs.read()) #opencl

fails, the code reports its enable:

print(cv2.ocl.haveOpenCL())#True
cv2.ocl.setUseOpenCL(True)
print(cv2.ocl.useOpenCL())#True

Do you know what am i missing?

**Comment by masterchop** [comment]
why invalid what am i missing? please educate me

**Comment by masterchop** [comment]
Thanks, for the info. I think i found out that the UMat class can only be use on images if i use video it fails.

**Comment by berak** [comment]
@masterchop, if your `vs.read()` really means, you're trying to read an image from a VideoCapture, --

it returns an `(retval, image)` tuple, and you only forgot to split the image from it, like:

     frame = cv2.UMat(vs.read()[1])

(there probably is no bug here)

**Comment by masterchop** [comment]
I just want to thank you for real, i have spend quit a lot of time trying to figure it out.
