### ISSUE TITLE
Error in contrast_preserve.hpp (photo module)

### ISSUE THREAD

**Issue by gdemarcq** [opencv/opencv#12165]
Hello everyone,
I had an issue with the decolor function and after looking at the code, here are my suggestions:
1) In function Decolor::weak_order => remove const reference (const Mat& img) because we need to modify it with the resize function.
2) The same happens to the function Decolor::grad_system

Best regards,
Guillaume

#### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Archlinux 64bits
- Compiler => gcc

**Comment by alalek** [comment]
This is not a part of public API, so mentioned changes can be applied to 3.4 branch:
```.diff
-const Mat& img
+Mat& img
```

**Comment by gdemarcq** [comment]
Thanks for your fast reply.
But I think that you must pass by value and not by reference.

Otherwise, I have another issue with the decolor function, can I post here or do I create an other issue?
