### ISSUE TITLE
fatal error: cvconfig.h: No such file or directory

### ISSUE THREAD

**Issue by Roinoss** [opencv/opencv#12168]
Guide:
http://www.wiki.xilinx.com/OpenCV%20Installation
Installation for Windows 8
Bug in step 4.

Bug log:

`[ 19%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathVec.cpp.obj
[ 19%] Linking CXX static library ../lib/libIlmImf.a
[ 19%] Built target IlmImf
[ 19%] Generating opencv_core_pch_dephelp.cxx

Scanning dependencies of target opencv_core_pch_dephelp
[ 19%] Building CXX object modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.obj
[ 19%] Linking CXX static library ../../lib/libopencv_core_pch_dephelp.a
[ 19%] Built target opencv_core_pch_dephelp
Scanning dependencies of target pch_Generate_opencv_core
[ 19%] Generating precomp.hpp
[ 19%] Generating precomp.hpp.gch/opencv_core_Release.gch
C:/<some_dirs>/opencv/opencv-2.4.13.5/release/modules/core/precomp.hpp:46:22: fatal error: cvconfig.h: N
o such file or directory
 #include "cvconfig.h"
                      ^
compilation terminated.
modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:62: recipe for target 'modules/core/precomp.hpp.gch/open
cv_core_Release.gch' failed
make.EXE[2]: *** [modules/core/precomp.hpp.gch/opencv_core_Release.gch] Error 1
CMakeFiles/Makefile2:1411: recipe for target 'modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all' failed
make.EXE[1]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make.EXE: *** [all] Error 2
vivado_hls>`

**Comment by Roinoss** [comment]
It is from VivadoHLS from Xilinx.
(High-level synthesis for FPGA).
What is PCH?

**Comment by alalek** [comment]
PCH means pre-compiled headers. Use `cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`
Do you trying to run whole OpenCV on FPGA?

**Comment by Roinoss** [comment]
Vivado HLS have its own library based on OpenCV that work on FPGA, but i want to use another library based on OpenCV that wasn't designed for FPGA (for example in ARM board part) and in test bench on PC.
