### ISSUE TITLE
Decolor - weird behaviour with large portrait images

### ISSUE THREAD

**Issue by gdemarcq** [opencv/opencv#12170]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Archlinux 64 Bit
- Compiler => GCC

##### Detailed description
When we apply the decolor function on large portrait images (width+height>800) it crashes in Decolor::gradvector. So here are my suggestions:
1) In Decolor::grad_system and Decolor::weak_order change 
`resize(img, img, Size(cvRound(h*sizefactor), cvRound(w*sizefactor)));`
with
`resize(img, img, Size(cvRound(w*sizefactor), cvRound(h*sizefactor)));`
in order to keep image aspect ratio...
2) In Decolor::gradvector change
`grad[i*height + j] = d_trans.at<float>(i, j);` 
with
`grad[i*width + j] = d_trans.at<float>(i, j);`
and 
`grad[offset + i * height + j] = d1_trans.at<float>(i, j);`
with
`grad[offset + i * width + j] = d1_trans.at<float>(i, j);`

**Comment by alalek** [comment]
Feel free to create Pull request with proposed changes into 3.4 branch.
