### ISSUE TITLE
I have made a pullrequest to find “ The maximum inner circle of the contour”

### ISSUE THREAD

**Issue by jsxyhelu** [opencv/opencv#12183]
as we all known ,opencv do not have a function to find “ The maximum inner circle of the contour”, but we can do this work by using pointPolygonTest
actuall,I have made a pull request about this,have a look at https://github.com/opencv/opencv/pull/12187

the result  picture is:

---

**Link is broken and removed**
@jsxyhelu Attach image directly to this issue (via GitHub)

---

do you have a better way to fine "The maximum inner circle ",any suggestion would be welcomed.

**Comment by iwaynee** [comment]
"You do not have permission to get URL '/blog/508489/201807/508489-20180720231406498-899701832.jpg' from this server."

**Comment by jsxyhelu** [comment]
sorry,the right picture 
![43351171-099574ca-9241-11e8-9bb5-5f48f349ae11](https://user-images.githubusercontent.com/16490259/43873535-7c3b4a64-9bb9-11e8-9f07-25155bde8b96.jpg)
