### ISSUE TITLE
OpenCV does not correctly load image in "LA" mode

### ISSUE THREAD

**Issue by achalddave** [opencv/opencv#12185]
##### System information (version)
- OpenCV = 3.1
- Operating System / Platform => CentOS 7.0
- Compiler => gcc 4.8.5

##### Detailed description

OpenCV does not correctly load image in "LA" mode.

##### Steps to reproduce

1. Download the attached image: ![la_image](https://user-images.githubusercontent.com/1168881/43843667-16a287c6-9af6-11e8-81c7-e1b65a4de821.png)
2. Run the following script. Replace 'strange-image.png' with the path to the above image.
```
import numpy as np

import cv2
import PIL.Image

path = 'strange-image.png'
pil_image_original = PIL.Image.open(path)
pil_image = np.array(PIL.Image.open(path))
cv2_image = cv2.imread(path)[:, :, ::-1]

# Expected and saw: "Mode: LA"
print('Mode: %s' % pil_image_original.mode)

print('===')
print('PIL Image shape:')
# Expected and saw: (480, 854, 2)
print(pil_image.shape)

print('CV2 Image shape:')
# Expected: (480, 854, 2)
# Saw: (480, 854, 3)
print(cv2_image.shape)

print('===')
print('PIL Image range:')
# Expected: (0, 255)
# Saw: (0, 255)
print(pil_image.min(), pil_image.max())

print('CV2 Image range:')
# Expected: (0, 255)
# Saw: (97, 112)
print(cv2_image.min(), cv2_image.max())

pil_channels_equal = np.all(pil_image[:, :, 0] == pil_image[:, :, 1])
cv2_channels_equal = (np.all(cv2_image[:, :, 0] == cv2_image[:, :, 1]) and
                      np.all(cv2_image[:, :, 1] == cv2_image[:, :, 2]))

print('===')
print('PIL channels are equal?')
# Expected: False
# Saw: False
print(str(pil_channels_equal))
print('CV2 channels are equal?')
# Expected: False
# Saw: True
print(str(cv2_channels_equal))
```

OpenCV returns an image with range (97, 112), instead of the expected (0, 255), and all the channels seem to contain the same information. It seems OpenCV discards the A channel, and just replicates the L channel into the R, G, and B channels.

**Comment by berak** [comment]
opencv does  not have an "LA" mode. and the way you call `imread()` (without any flags), you force it into 24bit 3channel mode, and *discard* the alpha channel. (and it is indeed a strange image, e.g. irfanview reports a single 16bit channel here). the correct way would have been:

    im = cv2.imread("strange-image.png", cv2.IMREAD_UNCHANGED)

which would result in a shape of `(480, 854, 4)`  (gray replicated 3 times, + alpha) and the correct min / max values.

**Comment by achalddave** [comment]
Fair enough. Discarding the alpha channel is understandable, as that's the behavior for 4 channel images as well, but it's strange that the first channel gets replicated three times instead of imread simply returning a single channel image. Trying to load a 4 channel PNG and accessing the 4th channel would give an out-of-bounds indexing error, but trying to load this 2 channel PNG and accessing the 2nd channel would actually give the incorrect result.
