### ISSUE TITLE
Minor issue in wiki

### ISSUE THREAD

**Issue by mohdomama** [opencv/opencv#12199]
##### Detailed description

The wiki [here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) provides sample code to run a pre-trained TF model. 
It reads the graph as:
 `with tf.gfile.FastGFile('frozen_inference_graph.pb') as f:`
which throws the following error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 58: invalid start byte`

This is because its trying to read a binary in `utf-8` format. 
Solution:
 `with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:`

**Comment by mshabunin** [comment]
Fixed, thank you!
