### ISSUE TITLE
OpenCV Memory Leak within C++ threads

### ISSUE THREAD

**Issue by arthurarj** [opencv/opencv#12194]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2017

##### Detailed description

Hello there! I'm experiencing some **memory leak** on OpenCV when working with C++ threads. I've seen some similar problems around but not quite the same. Also, the ones I've found were not solved.

I've reduced my code down to the simplest test one can make in which the problem persists. 

What it does: 1000 threads are spawned and each one of them will:
- Create a 300x300 Mat image filled with zeros;
- Add the image with itself and store in a new Mat. This is done 100 times within the each thread.

Memory leaks as shown below:
<img src="https://user-images.githubusercontent.com/13644591/43962014-e1a76a80-9c8c-11e8-8886-f6ac6009c7d2.png" width="50%">

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    ``` or attach as .txt or .zip file
-->

```
void static thread_call(int id, int n_threads) {
    cv::Mat teste = cv::Mat(300, 300, CV_32FC1, cv::Scalar(0));	
    for (int i = 0; i < 100; i++) {
        cv::Mat result;
	cv::add(teste, teste, result);
    }
}

void static test() {
    int n_threads = 1000;
    for (int i = 0; i < 1000; i++) {
	//Fork
	std::thread *t = new std::thread[n_threads];
	for (int i = 0; i < n_threads; ++i)
		t[i] = std::thread(thread_call, i, n_threads);
	//Join
	for (int i = 0; i < n_threads; ++i)
		t[i].join();
	delete[] t;
    }
    return;
}

int main()
{
    test();
    return 0;
}

```
Any insights are welcome :)

**Comment by alalek** [comment]
> 1000 threads

Avoid this if you want to use OpenCV. Consider using ThreadPool for async tasks.
At least, because massive thread creation / destruction is heavy task.

**Comment by catree** [comment]
Should be related I think #9745 (for cross reference and additional information).
