### ISSUE TITLE
seamlessClone bug

### ISSUE THREAD

**Issue by RenaiBi** [opencv/opencv#12196]
I got cv::Exception when I call seamlessClone(), and I found there is a bug in seamless_cloning.cpp line 94.
it should be 
CV_Assert(minxd >= 0 && minyd >= 0 && maxxd <= dest.cols && maxyd <= dest.rows);

**Comment by berak** [comment]
helo, @RenaiBi which opencv version do you use ? ([line 94](https://github.com/opencv/opencv/blob/master/modules/photo/src/seamless_cloning.cpp#L94) is a blank one)

which Exception is thrown there, exactly ?
also, it would be very useful, if you could add some minimal code to reproduce it, and the problematic image.

**Comment by sturkmen72** [comment]
mentioned line is removed by https://github.com/opencv/opencv/commit/5e2c112697889f06fad1d16a2244f29e707572d6#diff-9a54bcb18a9bc8ffa27dbc0c127828b2
