### ISSUE TITLE
Ubuntu 18.04 OpenCV 3.4.1 not recognizing GTK on cmake

### ISSUE THREAD

**Issue by lgmventura** [opencv/opencv#12195]
Ubuntu 18.04. OpenCV 3.4.1 not recognizing GTK on running cmake with the flag WITH_GTK=ON. After installing libraries `gtk2.0-dev` `gtk-3-dev`, OpenCV still does not recognize them and shows `GTK+: NO` on the list after running cmake. Qt is installed and was successfully recognized. Maybe if Qt is marked as YES, Gtk is not needed?!

**Comment by alalek** [comment]
Can't [reproduce](http://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/765/steps/cmake/logs/stdio):
```
--   GUI: 
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.56.0)
--       GtkGlExt:                  NO
```

QT replaces GTK. Closing.
