### ISSUE TITLE
Documentation for 3.4.0 missing?

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#12201]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => -
- Compiler => -

##### Detailed description

The documentation page (https://docs.opencv.org/3.4/index.html) has no option to show the documentation for OpenCV 3.4.0. Other versions like 3.4.1, 3.4.2 etc. are there, but 3.4.0 is missing.

##### Steps to reproduce

https://docs.opencv.org/3.4 (linked from https://docs.opencv.org/) shows "3.4.2-dev" in the version selection combobox, but there is no option for version 3.4.0.

**Comment by alalek** [comment]
Thank you for the report!

Documentation is in [place](https://docs.opencv.org/3.4.0/), it is just bug in versions switcher.

It should work now (press Ctrl+F5 to force reload files from the server).
