### ISSUE TITLE
OpenCV edited my public comments, effectively using my account and public image to make statements

### ISSUE THREAD

**Issue by TechnikEmpire** [opencv/opencv#12208]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

See this comment:
https://github.com/opencv/opencv/issues/12198#issuecomment-412564451

It's absolutely inappropriate to hijack my account to make statements using my name and public image, my company name no less. I've sent emails to about everyone I can about this already and the immediate next step in the process is a lawsuit against Intel.

Fix it now.

**Comment by TechnikEmpire** [comment]
@vpisarev Contact HR at your work. They and the legal team want to have a discussion with you.

**Comment by alalek** [comment]
Please stop "spam".
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by TechnikEmpire** [comment]
@alalek It's not spam it's now a legal issue and I'm not kidding I've spoken to Intel corporate and HR and the legal team need to have a discussion over what your people have done here. I'm still waiting for it to be fixed.

**Comment by alalek** [comment]
Posting on GitHub you agree with its terms. Or you skip its license too?
Owners of repositories can do anything with your comments, including complete removal of them. You must know this.
Harassment comments are not acceptable here. They will be removed, like other useless / non-constructive.

**Comment by TechnikEmpire** [comment]
@alalek So now it's harassment to ask Intel employees to not edit my comments and use my account and public image to make statements and remarks? You sure got a messed up idea of morality, legal issues aside.

You must think I'm making things up. I've already received word back that the issue is escalated at Intel. The case number is HR0862920 if you feel like calling in to confirm yourself. I look forward to having an apology forced out of the offenders here. Then we'll see who was in the wrong.

**Comment by TechnikEmpire** [comment]
Also thanks for the dig about skipping licenses. I didn't skip any license. What I found by not skipping licenses was Intel deeply embedding itself in this project. So, you really need to work harder at trying to insult with me fake facts.

Also GitHub licenses are above the law now? Lmao impersonal generally is illefal everywhere in the world, at least everywhere that isn't garbage. Anyway you just hush now and wait, Intel corporate is reviewing these threads and your corporate masters will do what is right because they know it's illegal. Stick to writing very bad code here, your legal skills and sense of ethics are woefully lacking.

**Comment by alalek** [comment]
Fell free to contact GitHub support with asking to remove your comments here. Really.

Again, this tracker is for issues and bugs that needs fix in OpenCV. Other comments will be edited / removed. This has been done before, and this will be done in the future. The rule is quite simple.

**Comment by TechnikEmpire** [comment]
The original issue was a request for comment about development and in fact my hijacked response clearly indicated a bug (backend doesn't work on non-intel hardware in my tests) and also had remarks about me contributing a new back end as well as enhancements to the convolution layer code. So your implications here, your arguments and reasonings are completely contrary to fact.

Keep talking though. Its making my point even stronger.

**Comment by alalek** [comment]
Your current result here is just a wasting time of OpenCV developers.
Do you understand that your comments here doesn't help this project? That is a time waste from the beginning:
- fake "default" backend, however it is not even enabled by default. It is developer responsibility for enabled flags.
- "swimming in legal documents using scary terms" - this is a bad place to find legal office or layer school.
- ending with "doesn't work on non-intel hardware in my tests". What tests? Where are details? What is statement declare that it should even work?
- why are you trying to blame on developers of project under BSD license? Including posting of personal information (under account without a real name).

**Comment by TechnikEmpire** [comment]
@alalek Sorry, your project owner and corporate overlord shut down the conversation before I even had a chance to contribute my tests showing that the intel back end doesn't function on at least one set of standard, non-intel hardware. I'm not contributing anything further, and you can shove your remarks trying to pin this on me. This is now a legal issue. Please stop further wasting my time, and everyone elses time with these responses. I opened this issue for Intel folks to review everything. Now sit quietly and wait for instructions.

**Comment by alalek** [comment]
Why do you think that moderation rights is a legal issue?
