### ISSUE TITLE
cv::distanceTransform() fail on a large image

### ISSUE THREAD

**Issue by hovnatan** [opencv/opencv#12218]
- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 8

Run
```.cpp

int main() {
  cv::Mat non_valid = cv::imread("surfaces_nonvalid.tif", cv::IMREAD_ANYDEPTH);
  cv::Mat dst;
  cv::Mat labels;
  cv::distanceTransform(non_valid, dst, labels, cv::DIST_L2, cv::DIST_MASK_3,
                        cv::DIST_LABEL_PIXEL);
  std::cout << labels.at<int>(0, 0) << std::endl; // <-- Error here: 0
  std::cout << labels.at<int>(50, 50) << std::endl; // <-- Error here: 0
  std::cout << labels.at<int>(5000, 5000) << std::endl; // Looks reasonable
  return 0;
}

```
on `non_valid` image from [surfaces_nonvalid.zip](https://github.com/opencv/opencv/files/2290343/surfaces_nonvalid.zip). The labels output has a lot of erroneous zero label values on the left part of the output as seen on this screenshot (left image: input non_valid image, right image: output labels image. black pixels `= 0`): 
![screenshot from 2018-08-15 15-11-38](https://user-images.githubusercontent.com/8426582/44145688-9ab5d80e-a09d-11e8-9850-6534955b7aec.png)

**Comment by hovnatan** [comment]
@alalek I found that the root of the problem is the large size of the input image: temporary integer distances calculated are larger than the max int value. If OpenCV supported `cv::Mat_<long int>`s this can be easily solved. Is there a plan in the future to support this? Or can I try adding this myself?

**Comment by alalek** [comment]
`cv::Mat_<long int>` is not supported. Only int = int32_t.

**Comment by hovnatan** [comment]
I have a solution using `cv::Mat1d` memory as a `cv::Mat` with `long int` (in Linux, at least, `long int` and `double` have the same size). If you think this is an acceptable solution I can commit the fix to OpenCV.
