### ISSUE TITLE
AKAZE keypoint output differs between 3.2 and 3.3

### ISSUE THREAD

**Issue by shimat** [opencv/opencv#12217]
## System information (version)
- OpenCV => 3.1.0 / 3.2.0 / 3.3.0 / 3.4.2
- Operating System / Platform => `Linux 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Compiler => gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)

## Detailed description

AKAZE keypoint results from the `detectAndCompute` function are different between the version 3.2.0 and 3.3.0.
The cause of this issue may be some patches to optimize AKAZE (#8951, #9249, ...).

For your information, KAZE keypoints from 3.1.0 to 3.4.2 are same.

### Test code
Python 2.7
```python
import cv2

image = cv2.imread("lena.png")
model = cv2.AKAZE_create()

keypoints, descriptors = model.detectAndCompute(image, None)

print('keypoints length = %d' % len(keypoints))
```

### Test image
http://optipng.sourceforge.net/pngtech/img/lena.html

### Result
```
3.1.0: keypoints length = 686 
3.2.0: keypoints length = 685
3.3.0: keypoints length = 575
3.4.2: keypoints length = 575
```

There is also a difference between 3.1.0 and 3.2.0. The cause may be arithmetic error.

**Comment by alalek** [comment]
Keypoins are used for matching regions of images.
Some of these keypoints / descriptors are usually outliers (in terms of matching, and < 30% is a very good number for outlier keypoints).

If keypoints are strong, algorithms is able to match rotated / scaled pictures, then algorithm is considered working (check OpenCV tests).

Just don't expect "bit-exact" results in CV apps. At least because any camera has noise and the final algorithm should be reliable to that noise, outlier keypoints, etc.
Another possible reason is a numeric error in floating point computations.

Please provide more details if you are sure that algorithm doesn't really work.

**Comment by shimat** [comment]
As far as I tried, the number of AKAZE keypoints for all images were decreased by about 20%. I could not find examples where the number of keypoints has increased.
I am not familiar with AKAZE algorithm and implementation but I can not believe that all decreased keypoints are outlier.

Since I am verifying this issue using same image files, noise does not affect keypoint result. 
As you say, numeric error is one possible reason. I think the difference between 3.1.0 and 3.2.0 is caused by it. I found some diffs about rounding process.
The 20% decrease between 3.2.0 and 3.3.0 is too big to explain by it.

I do not believe the AKAZE implementation of 3.1.0 is absolutely correct, but I do not know any reason to believe the latest implementation. If the number of keypoints decreases due to bug fix of AKAZE algorithm, I can be satisfied.

I am using AKAZE to match two very similar text images. I want to detect if there are minor differences between two images. By decreasing keypoints, 
I am afraid that some detailed features of letters lack and then matching fails (false-negative). I want to avoid false-negative matching. Sorry for my poor English. Thanks.

**Comment by alalek** [comment]
> I want to detect if there are minor differences between two images.

Not sure that using keypoints is suitable for that. Keypoints can't be very accurate, because they are used for matching of rotated / scaled images.

IMHO, "minor differences" should be validated by using of other approaches. Keypoints can be used here to "normalize" images by using of perspective transformation (`cv::findHomography()` + `cv::warpPerspective()`). Additionally you may normalize light intensity before aggressive check of minor differences on normalized images.

P.S.
You can find exact commit with changes by using of `git bisect`.

**Comment by hrnr** [comment]
Hi @shimat,

I have authored the changes in AKAZE. As already noted comparing the number of keypoints may be misleading.

The change in a number of keypoints comes from changes in Find_Scale_Space_Extrema, which uses a more efficient and also more correct approach. It is able to filter the keypoints more efficiently, removing the keypoints with lower response close to keypoints with higher response. This leads to lower number of keypoints. Similar more efficient modifications to Find_Scale_Space_Extrema has been used by other AKAZE implementations (https://github.com/h2suzuki/fast_akaze, https://github.com/nbergst/akaze, https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/akaze/AKAZE.cpp). 

I have looked for the regressions for this very extensively. Although the lower number of keypoints looks scary, the modified method worked in my tests really well. It keeps the good keypoints, while reducing the overall number of keypoints, making the matching faster and increasing the inlier ratio.

For testing the performance of the features it is not enough to look on the number of detected keypoints (then the best method would be to report all the pixels), but instead look on the number of inliers in the RANSAC estimate. That is far more significant for features performance. The number of inliers might still be slightly misleading. Imagine a situation where the detector reports 2 keypoints very close together marking the same corner and both get used as an inliers. We would prefer having just 1 keypoint nicely centered on the corner, but if we improve the detector, that leads to lower number of inliers.

Visual inspection of the produced keypoints and matches is therefore a must.

I believe that I and @alalek have fixed many bugs in the implementation and that the new implementation of AKAZE is much better, but of course some bugs may still be there.

If you find that there are some areas in the image that used to have inliers, but now they don't have any, it should be inspected. Please let us know the image and affected areas. I couldn't find any problems with attached Lena.

Cheers,
Jiri

See also related discussion under https://github.com/pablofdezalc/akaze/issues/30, https://github.com/pablofdezalc/akaze/issues/24, https://github.com/pablofdezalc/akaze/issues/32

**Comment by shimat** [comment]
Thank you so much for your detailed information and many contributions for AKAZE. I understand I mislead the meaning of keypoints somewhat.

I have hoped the AKAZE keypoint to grab features of all letters in an image, but it is out of the way AKAZE should be. I would like to research about a better way for our purpose. Since our target images are confidential, it is difficult to give an appropriate example.
