### ISSUE TITLE
cudafeatures2d cannot be wrapped for Python

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12230]
##### System information (version)
- OpenCV => 4.0.0-pre (master branch)
- Operating System / Platform => Independent
- Compiler => Independent

##### Detailed description
Both classes of `cuda::ORB` and `cuda::FastFeatureDetector` utilizes multiple inheritance, thus it impossible to wrap them into Python, and perhaps other languages.

**Comment by alalek** [comment]
Perhaps we should allow bindings generator to wrap final class only without any of base classes, or specify which one base class should be used.

**Comment by cv3d** [comment]
Currently, bindings generator utilizes the first base, but that is still insufficient because some needed functionalities stems from the second base. Furthermore, limiting the generator to final classes will not enforce any good practice, and would not solve the problem.

If, however, `CV_EXPORTS` would be allowed only on final classes, then that would be a perfect solution.
