### ISSUE TITLE
No UMat support in functions split() and merge()

### ISSUE THREAD

**Issue by MoMurkel** [opencv/opencv#12231]
Unlike many other functions, the two functions split() and merge() do not support the use of the UMat class.

It is not possible to split a three channel UMat into an array (or vector) of three UMat directly without using the method getMat().

The output (second argument) can't be an array of UMat.

Same applies to mixChannels()

**Comment by MoMurkel** [comment]
It is not a question how to solve it.

The split() and the merge() functions should be expanded to support UMat class in accordance to other image functions.

**Comment by alalek** [comment]
Raw arrays (pointers) are unsafe and these interfaces should be deprecated / dropped / removed.

UMat has support via `std::vector<UMat>` as `cv::InputArrayOfArrays` (and probably via `std::array<UMat>` in C++11).

**Comment by buni-rock** [comment]
@alalek : what that really means? How can I get my way around using the split and merge with UMat?

**Comment by mshabunin** [comment]
Using these overloads: https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga61f2f2bde4a0a0154b2333ea504fab1d and https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga8027f9deee1e42716be8039e5863fbd9

**Comment by MoMurkel** [comment]
Maybe the documentation is unclear. The accepted "dst output array" parameter does not mean plain "array" ( UMat m[3]; ) but vector ( std::vector<UMat> m ).

**Comment by alalek** [comment]
There are different overloads for these functions. Mentioned one doesn't work, but other works - check existed tests.

**Comment by neFAST** [comment]
@alalek May I ask what is the recommended way to merge 2 UMat into a single 2-channels UMat?

**Comment by zachlowry** [comment]
Is there still no way to split/merge a UMat in Python?

**Comment by tyler274** [comment]
Are python users still left up a creek without a paddle here?

**Comment by Huud** [comment]
Since this is the first result in google, you can use mixChannels with UMat, but instead of writing it like this:

	cv::mixChannels(&mat1, 1, &mat2, 1, from_to, 3);

do it like this:

	cv::mixChannels(mat1, mat2,  from_to, 3);
