### ISSUE TITLE
SimpleBlobDetector radius sorting bug (possible)

### ISSUE THREAD

**Issue by lilo00** [opencv/opencv#12244]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => any
- Compiler => any

##### Detailed description
Hi,
If it is intended to accumulate blob radiuses in a sorted way ( I believe it is because `centers[j].size() / 2` then have a sence of a median radius) at [SimpleBlobDetectorImpl::detect](https://github.com/opencv/opencv/blob/76eb38976103c86610f73d87e46b7cb5a74f0017/modules/features2d/src/blobdetector.cpp#L341), then bubble sort insert is broken. 
Current code:
```
                    centers[j].push_back(curCenters[i]);

                    size_t k = centers[j].size() - 1;
                    while( k > 0 && centers[j][k].radius < centers[j][k-1].radius )
                    {
                        centers[j][k] = centers[j][k-1];
                        k--;
                    }
                    centers[j][k] = curCenters[i];
```

Suggested substitute:

```
                    centers[j].push_back(curCenters[i]);

                    size_t k = centers[j].size() - 1;
                    while( k > 0 && centers[j][k].radius < centers[j][k-1].radius )
                    {
                        centers[j][k] = centers[j][k-1];
                        k--;
                        centers[j][k] = curCenters[i];
                    }
```

**Comment by mshabunin** [comment]
Could you please provide minimal reproducer illustrating the issue?
