### ISSUE TITLE
The shape of outputs of the RegionLayer is not right

### ISSUE THREAD

**Issue by gylns** [opencv/opencv#12247]
##### System information (version)

- OpenCV =>3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
the shape of outputs of `RegionLayer` is computed as following:
https://github.com/opencv/opencv/blob/76eb38976103c86610f73d87e46b7cb5a74f0017/modules/dnn/src/layers/region_layer.cpp#L94

that's does not matter if we input only one image using `blobFromImage`, but if we input multiple images using `blobFromImages` then the shape of outputs is not right, and it should changed to
```c++
outputs = std::vector<MatShape>(1, shape(inputs[0][0], inputs[0][1] * inputs[0][2] * anchors, inputs[0][3] / anchors));
```
when forward this layer, we should also forward all inputs:
https://github.com/opencv/opencv/blob/76eb38976103c86610f73d87e46b7cb5a74f0017/modules/dnn/src/layers/region_layer.cpp#L218-L222

should change to
```c++
           const float *srcData = inpBlob.ptr<float>();
           float *dstData = outBlob.ptr<float>();
           CV_Assert(inpBlob.size[0] == outBlob.size[0]);

           for (int n = 0; n < inpBlob.size[0]; n++)
           {
               // logistic activation for t0, for each grid cell (X x Y x Anchor-index)
               for (int i = 0; i < rows * cols * anchors; ++i) {
               ......
               srcData += inpBlob.step1(0);
               dstData += outBlob.step1(0);
           }
```

**Comment by kopytjuk** [comment]
#12249

**Comment by dkurt** [comment]
@gylns, @kopytjuk merged a pull request which fixes that.
