### ISSUE TITLE
MobileSSD-v2-DNN

### ISSUE THREAD

**Issue by xiangdeyizhang** [opencv/opencv#12253]
when i use MobilessdV2 BY DNN ,there is an error:

OpenCV Error: Assertion failed (fracpart == 0.0) in get<long int>, file /home/bearzhang/opencv-3.3.0/modules/dnn/include/opencv2/dnn/dnn.inl.hpp, line 101
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/bearzhang/opencv-3.3.0/modules/dnn/include/opencv2/dnn/dnn.inl.hpp:101: error: (-215) fracpart == 0.0 in function get<long int>

Aborted (core dumped)

how could it happened?

**Comment by dkurt** [comment]
@xiangdeyizhang, please update your OpenCV. This problem has been already fixed.

http://answers.opencv.org/question/176756/error-with-custom-trained-ssd/
http://answers.opencv.org/question/177381/error-doing-forward-pass-with-opencv-33/

**Comment by xiangdeyizhang** [comment]
thank you ! I will try it
