### ISSUE TITLE
Feature Request "World Library"

### ISSUE THREAD

**Issue by duaneellissd** [opencv/opencv#12252]
OpenCV => Git Head, checked out yesterday, hash: 76eb38976103c86610f73d87e46b7cb5a74f0017
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2017

Windows Developer documentation, link here:

https://docs.opencv.org/master/dd/d6e/tutorial_windows_visual_studio_opencv.html

Suggests there is a "World" library that is a combination of all libraries, specifically the phrase used is:

> Alternatively, your OpenCV download may have been built into one large .lib file. Check by looking in OpenCV\build\architecture\vc14\lib.

Observation: Current CMAKE configuration does not produce anything like a "world library"

My request is to create a "world library" as suggested in the documentation.

Or please remove this suggestion from the documentation.

**Comment by mshabunin** [comment]
Building OpenCV is out of scope of this tutorial. However this information can be added to the "Building OpenCV" tutorial.

There are no documentation page for all cmake-options, but most of available options are documented in cmake itself, so you can find the checkbox in cmake-gui (hover your mouse over the option to see the description):

![image](https://user-images.githubusercontent.com/3304494/44332963-1928ca80-a476-11e8-8d0f-15f120e61afd.png)

Or via command-line: `cmake -LH | grep -i world`

**Comment by HarshDolhare** [comment]
Hey!
I am a beginner and want to start contributing. Can you please brief on what exactly needs to be done?

**Comment by mshabunin** [comment]
@HarshDolhare , a note describing `BUILD_opencv_world` cmake option should be added to the corresponding section of the [Installation in Windows tutorial](https://github.com/opencv/opencv/blame/3.4/doc/tutorials/introduction/windows_install/windows_install.markdown#L300) on branch **3.4**.
