### ISSUE TITLE
/usr/lib32/libz.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by anpdas** [opencv/opencv#12265]
[  0%] Built target gen-pkgconfig
[  4%] Built target libtiff
[ 13%] Built target libwebp
[ 16%] Built target libjasper
[ 22%] Built target IlmImf
[ 25%] Built target ippiw
[ 31%] Built target libprotobuf
[ 31%] Built target ittnotify
[ 31%] Linking CXX shared library ../../lib/libopencv_core.so
/usr/lib32/libz.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_core.so.4.0.0] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

##### System information (version)

- OpenCV => git cloned from this branch
- Operating System / Platform => Ubuntu 14.04
- Compiler => gcc 4.8.4

##### Detailed description

I've followed steps from "https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html"  
Below step is successful 
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..

after running "make" I see below error
[  0%] Built target gen-pkgconfig
[  4%] Built target libtiff
[ 13%] Built target libwebp
[ 16%] Built target libjasper
[ 22%] Built target IlmImf
[ 25%] Built target ippiw
[ 31%] Built target libprotobuf
[ 31%] Built target ittnotify
[ 31%] Linking CXX shared library ../../lib/libopencv_core.so
/usr/lib32/libz.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_core.so.4.0.0] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

##### Steps to reproduce
run make command to reproduce this issue

**Comment by zchrissirhcz** [comment]
I'm with same error and finally figured out that I added `-m32` in my CMakeLists.txt ... Remove that flag resolves my problem.

**Comment by jackiezhang11** [comment]
sudo cmake gui .
select zlib-build in configuration interface.
next generate.
anew make,
There would be no problem.

**Comment by zchrissirhcz** [comment]
The actual cause is that cmake provided FindZLIB.cmake but it failed to find static lib if not specifying that lib's path.
