### ISSUE TITLE
Access camera by cv2.VideoCapture(-1), rather then cv2.VideoCapture(-1)

### ISSUE THREAD

**Issue by Licmeth** [opencv/opencv#12260]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Python => Python 3.6 (64-bit)

[BuildInformation.txt](https://github.com/opencv/opencv/files/2303118/bi.txt)

##### Detailed description

I have only one camera connected to my pc. When I try to connect to it and grab a frame (code example 1), I end up with an error after a 10 second time out. Coincidentally, I found, that I am able to connect to my camera by using index -1 for cv2.VideoCapture(index), see code example 2.

As cv2.VideoCapture(index) is initilized by an index, I'd suppose this index would start with 0.

##### Steps to reproduce

Python Code example 1 (returns error)
    
    import cv2
    
    cap = cv2.VideoCapture(0)
    _, frame = cap.read()

returning output:
    
    [ WARN:0] videoio(MSMF): can't grab frame. Error: -2147483638
    Traceback (most recent call last): File "D:\...\Test1.py", line 10, in <module> hsvFrame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV) cv2.error: OpenCV(3.4.2) c:\projects\opencv-python\opencv\modules\imgproc\src\color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<3,-1,-1>,struct cv::Set<0,5,-1>,2>::CvtHelper'

Python Code example 2 (works)
    
    import cv2
    
    cap = cv2.VideoCapture(-1)
    _, frame = cap.read()

**Comment by alalek** [comment]
MSMF doesn't support "-1" index properly (see #11880 , not merged ), so probably other backend is used.

Add camera device name into description.

Run both cases with `OPENCV_VIDEOIO_DEBUG=1` environment to capture more information.

> 3.4.2

Try the latest code of OpenCV from branch 3.4 too.

**Comment by sarthakforwet** [comment]
Still the index of -1 isn't working.I am getting the same error as before..

**Comment by alalek** [comment]
> the same error

This message doesn't help with investigation of the problem.
We need logs from debug dump at least (see comment above).
