### ISSUE TITLE
Template Matching Multiple Objects Filter result

### ISSUE THREAD

**Issue by lucaspojo** [opencv/opencv#12277]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

Hello, I'm trying to find all the coins as in this example: 
https://docs.opencv.org/3.4/res_mario.jpg
(https://docs.opencv.org/3.4/d4/dc6/tutorial_py_template_matching.html)

It's working. The problem is that opencv returns several times the same coin positions to me. ( X and Y position) almost identical to a few pixels near.

Example : `(900, 349)   
(964, 349)   
(1028, 349)  
(1092, 349)  
(900, 350)   
(964, 350)   
(1028, 350)  
(1092, 350)  
(899, 351)   
(900, 351)   
(901, 351)   
(963, 351)   
(964, 351)   
(965, 351)   
(1027, 351)  
(1028, 351)  
(1029, 351)  
(1091, 351)  `

Do you have a technique to avoid duplicates? Thanks to you!

( ps: I'm new to Python, I'm from Nodejs..)

My code : 
https://gist.github.com/lucaspojo/b2724722d9a720aa966411a5e0cff914

**Comment by catree** [comment]
Look at [Non-Maximum Suppression](https://www.pyimagesearch.com/2015/02/16/faster-non-maximum-suppression-python/).
This is not an issue and you should rather ask your question here [http://answers.opencv.org](http://answers.opencv.org) for OpenCV related questions and here [https://stackoverflow.com/](https://stackoverflow.com/) for general programming questions.
