### ISSUE TITLE
Data types for cv.calcOpticalFlowPyrLK

### ISSUE THREAD

**Issue by InternDan** [opencv/opencv#12285]
I'd like to use cv.calcOpticalFlowPyrLK to track points clicked on by a user in an image, and I can identify the coordinates of the click on an image no problem. I generate a cv.Point(x,y) with the values, but how can I convert this to what's needed for the current position input? I've seen the box tracking example but have no idea what data type the p0 is there or how to convert to it from a point in Javascript. I'm using the most recent master build of OpenCV.js

Thanks!

**Comment by berak** [comment]
@InternDan , since this is the opencv bug tracker, and you don't have a library bug to present, --
could you move your question to http://answers.opencv.org/questions/ ? 
(re-ask there, and kindly close this issue.)

we can help you much better from there.

**Comment by InternDan** [comment]
Sure thing, thanks!
