### ISSUE TITLE
OpenCV.js max function fails test on Mac OS X 10.13.6 High Sierra

### ISSUE THREAD

**Issue by TerribleNews** [opencv/opencv#12292]
<img width="552" alt="screen shot 2018-08-23 at 1 06 28 pm" src="https://user-images.githubusercontent.com/1923071/44537505-62c32080-a6d5-11e8-8913-483e7be4c6be.png">

After building opencv.js from scratch, I get this one error. I can't for the life of me figure out why this would be happening. I have tried fiddling around with the values and order of variable definitions and function calls in the test file but it still fails.  I am running the test in Firefox on OS X, but it also fails in the same way in Safari on IOS and chrome on Windows.

It appears to be something to do with how it's accessing the memory inside the call, but the cpp code appears completely the same as the min code, which passes the tests.  Please let me know if I can provide any other information to get this sorted.

**Comment by TerribleNews** [comment]
`Detected OpenCV version: 4.0.0-pre
Detected emcc version: 1.38.11
`

Test passes with that opencv.js. The only reason I'm trying to build from source is that the video module can't grab the webcam on IOS because of constraints and I'd like to figure out how to fix that. I tried a lot of googling and couldn't come up with any way to change the video config that seems to be causing the issue. Is there a different way I can get webcam on IOS Safari without having to recompile opencv.js?

**Comment by alalek** [comment]
We use [emscipten 1.37.21 on our CI](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_docs-lin64/builds/100/steps/build_js/logs/stdio).

Video camera is not handled via OpenCV videoio module. It grabs pictures via HTML canvas.
Check [this documentation page](https://docs.opencv.org/3.4/dd/d00/tutorial_js_video_display.html) and provided "online" demo.
Related code is [here](https://github.com/opencv/opencv/blob/3.4.2/modules/js/src/helpers.js#L114-L146).

Google Chrome requires properly configured HTTPS web-server for camera access. It doesn't work via HTTP insecure connections. Unfortunately I can't help with Safari, may be community can share some useful information.

**Comment by TerribleNews** [comment]
Okay, I switched to version 1.37.21 and the test passes now. The bug seems to be related to emscripten 1.38.11

**Comment by alalek** [comment]
I have tried 1.38.12 and it works well on Linux: #12799

**Comment by dkurt** [comment]
@TerribleNews, please try emsdk with emscripten `1.38.21`. I tried it locally and all the tests are passed now.
