### ISSUE TITLE
Webcam light still on after cam.release()

### ISSUE THREAD

**Issue by gabycperezdias** [opencv/opencv#12301]
Expected behaviour
When releasing webcam, not only the webcam should be released but also the webcam light indicator should be turned off.

Actual behaviour
The webcam light keeps on even though the webcam is, in fact, released.

I am doing:

    webcam = cv2.VideoCapture(0)
    webcam.release()

After the release command, if I try to read the cam I get: `(False, None)` but the webcam itself is still `<VideoCapture 0EE62DC0>`. I don't know if this is the issue, but the light keeps on until I kill all python script or python terminal responsible to turn it on.

I am on a Windows 10, python 3.5, opencv 4.0.1. According to comments on my stackoverflow question (https://stackoverflow.com/questions/51974632/webcam-light-still-on-after-cam-release) other version also shows the issue (python 3.6 and opencv 3.4.2)

It seems that it was introduced in an earlier version because version 3.4.0.14 works fine.

I first opened the issue directly to `opencv-python` but according to its mantainer: "This repository is just an unofficial wrapper which generates python bindings automatically from OpenCV sources."

**Comment by alalek** [comment]
Attach logs with `OPENCV_VIDEOIO_DEBUG=1` environment variable.

Also try `OPENCV_VIDEOIO_PRIORITY_MSMF=0` to disable MSMF.

**Comment by nerdfever** [comment]
Same here. Win10 x64, Python 3.6 x64, OpenCV 3.4.2.

Code:

    import cv2
       
    window = "OpenCV_window"
    cam = cv2.VideoCapture(0)
    print(cam, "is open:", cam.isOpened())

    cv2.namedWindow(window)
    ready, frame = cam.read()
    print("Frame ready:", ready)

    cv2.imshow(window, frame)
    cv2.waitKey(1)
    input("Press ENTER to close window and camera.") 

    cv2.destroyAllWindows()
    cam.release()

    # light on Logitech C922 webcam remains on at this point

    input("Press ENTER to exit Python.")  

    # light on webcam goes off only after Python exits

Output:

    C:\Users\Dave\data\Code\Python\VideoCapture>python3 test.py
    <VideoCapture 0000023C055CDEF0> is open: True
    Frame ready: True
    Press ENTER to close window and camera.
    Press ENTER to exit Python.
    
    C:\Users\Dave\data\Code\Python\VideoCapture>

> Also try OPENCV_VIDEOIO_PRIORITY_MSMF=0 to disable MSMF.

That does fix it.

> Attach logs with OPENCV_VIDEOIO_DEBUG=1 environment variable.

Not sure what you mean by "logs" (where are they?) but here's the output:

    C:\Users\Dave\data\Code\Python\VideoCapture>set OPENCV_VIDEOIO_DEBUG=1

    C:\Users\Dave\data\Code\Python\VideoCapture>python3 test.py
    [ WARN:0] VIDEOIO(cvCreateCapture_MSMF(index)): trying ...

    [ WARN:0] VIDEOIO(cvCreateCapture_MSMF(index)): result=000001FC77543C50 isOpened=1 ...

    <VideoCapture 000001FC7736DEF0> is open: True
    Frame ready: True
    Press ENTER to close window and camera.
    Press ENTER to exit Python.

    C:\Users\Dave\data\Code\Python\VideoCapture>

Tell me where to find the logs and I'll post them. Or, just try it yourself.

**Comment by rollly00** [comment]
OPENCV_VIDEOIO_PRIORITY_MSMF = 0, it worked for me, but when I compile the program, will it work on other computers?

**Comment by nerdfever** [comment]
@rollly00 It will work only if your program sets that environment variable. Try os.environ["OPENCV_VIDEOIO_PRIORITY_MSMF"] = "0" (I haven't tested it).

We were trying that only to narrow down the source of the problem (not as a workaround, but you may find it works well enough for you).

**Comment by rollly00** [comment]
This does not work. The path is added to the running process. The path is not added globally.

**Comment by peterjozsa** [comment]
Same for me. I tracked it down to some refcounting issues in the MSMF capture backend, which I tried to fix. I'll submit a PR soon.

**Comment by skycreeper2000** [comment]
I checked and it is due to the fact the kernel is still active. Close the kernel and light will go off!

**Comment by Aashima-Gupta** [comment]
Hi, i have encountered the same problem in python 2.7 and openCV 3.4.2. There are 2 different scripts executed one after the other and both require camera source for individual purposes but since the light doesn't turn off after first script is executed the second script shows error while reading the camera.
**Error
[ WARN:0] videoio(MSMF): OnReadSample() is called with error status: -1072875772
[ WARN:0] videoio(MSMF): async ReadSample() call is failed with error status: -1072875772
[ WARN:1] videoio(MSMF): can't grab frame. Error: -1072875772
Traceback (most recent call last):**

**pls tell me what all is to be set and do the variables to be set in the starting of script??**

**Comment by Aashima-Gupta** [comment]
@rollly00 
Hi i have set the environment variables to my system as 
OPENCV_VIDEOIO_DEBUG 1
OPENCV_VIDEOIO_PRIORITY_MSMF 0

Now anything else is to be added to the scripts using webcam

**Comment by dheeraj3737** [comment]
Open cmd and type :
setx OPENCV_VIDEOIO_PRIORITY_MSMF 0

**Comment by DheerajNomula** [comment]
Open cmd and type:
setx OPENCV_VIDEOIO_PRIORITY_MSMF 0

**Comment by refigh** [comment]
I have same issue in ubuntu, and above solution (OPENCV_VIDEOIO_PRIORITY_MSMF=0) did not work for me. Is there any plan to fix this bug?

**Comment by rsokl** [comment]
> Open cmd and type: setx OPENCV_VIDEOIO_PRIORITY_MSMF 0

On some devices, setting `OPENCV_VIDEOIO_PRIORITY_MSMF` to `0` can produce severely distorted images.  This is not a robust fix.

This seems to still be a problem

**Comment by ismailalhajosman** [comment]
I had the same problem and I was able to turn off the light by _Restarting the Kernel_.

**Comment by nerdfever** [comment]
@noorulhudaajmal This is a solved problem in the latest OpenCV (that's why the issue is closed).
