### ISSUE TITLE
OpenCV is not able to find/configure CUDA SDK Windows 10 Cmake

### ISSUE THREAD

**Issue by pouya1991** [opencv/opencv#12300]
System information (version)
- OpenCV => latest
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Mingw32 (5.3.0)
- CUDA=> 9.2.148
- CMake => 3.12.1

I'm trying to compile opencv with cuda support but opencv couldn't find CUDA SDK and I got this warning:
I've already set CUDA_PATH and CUDA_TOOLKIT_ROOT_DIR in environment variables.

`CMake Warning at cmake/OpenCVFindLibsPerf.cmake:46 (message):
OpenCV is not able to find/configure CUDA SDK (required by WITH_CUDA).

CUDA support will be disabled in OpenCV build.

To eliminate this warning remove WITH_CUDA=ON CMake configuration option.

Call Stack (most recent call first):
    CMakeLists.txt:634 (include)`

**Comment by xsacha** [comment]
This bug could be caused by the BUILD_SHARED_LIBS issue fixed in https://github.com/opencv/opencv/pull/13063
Otherwise there's not enough information

**Comment by alalek** [comment]
I believe main problem here is:
- CUDA
- MinGW

I don't know success stories of this configuration. And we definitely don't want to support this one.

**Comment by xsacha** [comment]
Not using CUDA or MingW. It was MSVC non-CUDA.
