### ISSUE TITLE
"Could not find any instance of visual studio" error in installOCV.sh

### ISSUE THREAD

**Issue by willstout** [opencv/opencv#12302]
##### System information (version)

- OpenCV => :3.4:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Visual Studio 2017:

##### Detailed description

I'm trying to install OpenCV with Git Bash and I'm having trouble making the installOCV.sh file. Everything seems fine except that when I run ./InstallOCV.sh the CMAKE_CONFIG_GENERATOR doesn't seem to like when I set it equal to "Visual Studio 15 2017 Win64". Which is odd because that's the version of Visual Studio I have. Anything I can do to fix this?

##### Steps to reproduce

```
nano installOCV.sh

#!/bin/bash -e
myRepo=$(pwd)
CMAKE_CONFIG_GENERATOR="Visual Studio 15 2017 Win64"
if [ ! -d "$myRepo/opencv" ]; then
        echo "cloning opencv"
        git clone https://github.com/opencv/opencv.git
        mkdir Build
        mkdir Build/opencv
        mkdir Install
        mkdir Install/opencv
else
        cd opencv
        git pull --rebase
        cd ..
fi
if [ ! -d  "$myRepo/opencv_contrib" ]; then
        echo "cloning opencv_contrib"
        git clone https://github.com/opencv/opencv_contrib.git

        mkdir Build/opencv_contrib
else
        cd opencv_contrib
        git pull --rebase
        cd ..
fi
RepoSource=opencv
pushd Build/$RepoSource
CMAKE_OPTIONS='-DBUILD_PERF_TESTS:BOOL=OFF -DBUILD_TESTS:BOOL=OFF -DBUILD_DOCS:$
cmake -G"$CMAKE_CONFIG_GENERATOR" $CMAKE_OPTIONS -DOPENCV_EXTRA_MODULES_PATH="$$
echo "************************************ $Source_DIR -->Debug"
cmake --build .  --config debug
echo "************************************ $Source_DIR -->Debug"
cmake --build .  --config release
cmake --build .  --target install --config release
cmake --build .  --target install --config debug
popd


./installOCV.sh

$ ./installOCV.sh
Already up to date.
Current branch master is up to date.
Already up to date.
Current branch master is up to date.
/c/lib/Build/opencv /c/lib
CMake Error at CMakeLists.txt:127 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/lib/Build/opencv/CMakeFiles/CMakeOutput.log".
```

The CMakeOutput.log just has "The system is: Windows - 10.0.17134 - AMD64" in it.
-->

**Comment by willstout** [comment]
I tried this with my other computer that has the same setup and it worked, weird.

**Comment by LaurentBerger** [comment]
In git-bash windows type export . what is declare -x ORIGINAL_PATH= in your config ? can you see path to vs studio ?

**Comment by willstout** [comment]
declare -x ORIGINAL_PATH="/mingw64/bin:/usr/bin:/c/Users/willstout/bin:/c/Progra m Files/Docker/Docker/Resources/bin:/c/Program Files (x86)/Common Files/Oracle/J ava/javapath:/c/Python36/Scripts:/c/Python36:/c/WINDOWS/system32:/c/WINDOWS:/c/W INDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/ProgramData/c hocolatey/bin:/c/HashiCorp/Vagrant/bin:/c/WINDOWS/System32/OpenSSH:/c/Program Fi les/dotnet:/cmd:/c/Program Files/CMake/bin:/c/Users/willstout/AppData/Local/Micr osoft/WindowsApps"

No path to visual studio, does that mean that git doesn't see visual studio?
