### ISSUE TITLE
The title row of build farm status does not stick at the top while scrolling down

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12311]
While the page scrolls down, the title row disappears, thus one fails to recognize which column is which. The title column shall stick at the top of the page despite scrolling down or not.
Interestingly, in case of contrib repo, the title row is sticky, but that is not the case with the main repo.

I know this is minor, but it is quite annoying!

**Comment by alalek** [comment]
Can't reproduce. Scrolling works well on Google Chrome, try to reload page.

**Comment by cv3d** [comment]
@alalek Perhaps it is my language, thus allow me to emphasize.
The page do scroll, but the title row disappears, thus one fails to recognize which column is which. The title column needs to stick at the top of the page despite scrolling down or not.

**Comment by alalek** [comment]
Table header "stick" approach is tricky (no native support from HTML), so it doesn't work properly for all browsers (IE has bugs with cell widths, Firefox doesn't work).
Try Google Chrome / Chromium / modern Opera (similar engine like Chrome).

**Comment by cv3d** [comment]
I am in using Google Chrome 68, and there is no problem while using the status page of the contrib page.
However, which I switch to the main-repo status page, the following error appears in the console:

```
angular.js:10126 Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <float16, ...> still ignores scale and bias.<br><!-- Please describe what your pullrequest is changing --></p>

http://errors.angularjs.org/1.2.28/$sanitize/badparse?p0=%3Cfloat16%2C%20...%3E%20still%20ignores%20scale%20and%20bias.%3Cbr%3E%3C!--%20Please%20describe%20what%20your%20pullrequest%20is%20changing%20--%3E%3C%2Fp%3E%0A
    at angular.js:78
    at htmlParser (angular-sanitize.js:326)
    at angular-sanitize.js:144
    at getTrusted (angular.js:13595)
    at Object.sce.(/anonymous function) [as getTrustedHtml] (http://pullrequest.opencv.org/3rdparty/angular/angular.js:14275:16)
    at Object.ngBindHtmlWatchAction [as fn] (angular.js:18488)
    at Scope.$digest (angular.js:12650)
    at Scope.$apply (angular.js:12915)
    at done (angular.js:8450)
    at completeRequest (angular.js:8664)
(anonymous) @ angular.js:10126
(anonymous) @ angular.js:7398
$digest @ angular.js:12669
$apply @ angular.js:12915
done @ angular.js:8450
completeRequest @ angular.js:8664
xhr.onreadystatechange @ angular.js:8603
XMLHttpRequest.send (async)
(anonymous) @ angular.js:8632
sendReq @ angular.js:8426
serverRequest @ angular.js:8146
wrappedCallback @ angular.js:11682
wrappedCallback @ angular.js:11682
(anonymous) @ angular.js:11768
$eval @ angular.js:12811
$digest @ angular.js:12623
$apply @ angular.js:12915
done @ angular.js:8450
completeRequest @ angular.js:8664
xhr.onreadystatechange @ angular.js:8603
XMLHttpRequest.send (async)
(anonymous) @ angular.js:8632
sendReq @ angular.js:8426
serverRequest @ angular.js:8146
wrappedCallback @ angular.js:11682
wrappedCallback @ angular.js:11682
(anonymous) @ angular.js:11768
$eval @ angular.js:12811
$digest @ angular.js:12623
$apply @ angular.js:12915
(anonymous) @ angular.js:9913
dispatch @ jquery.js:5095
elemData.handle @ jquery.js:4766
```
which suggests that the problem is not in my browser, but rather in the description of one of the PRs.
In fact the problem is more serious, as it seems that HTML tags (and perhaps scripts) are not escaped, thus a malicious PR can do a lot of scary things, including admin session hijacking, planting worms, etc.

**Comment by alalek** [comment]
I added sticky table header implementation via modern CSS features: https://caniuse.com/#feat=css-sticky
It is still buggy (doesn't work on whole row in Chrome, only table cells), but can work without JavaScript tricks.

Please try again.

**Comment by cv3d** [comment]
@alalek It is now working great! Thank you.
