### ISSUE TITLE
Build farm regression as Win64 OpenCL is failing to compile

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12312]
It is happening so frequently ([[1]](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/16823), [[2]](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/16825), [[3]](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/16827), [[4]](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/16828)) with the following meaningless error:

```
     7>LINK : fatal error LNK1104: cannot open file 'C:\build\precommit_opencl\build\bin\Release\opencv_core400.dll' [C:\build\precommit_opencl\build\modules\core\opencv_core.vcxproj]
```

**Comment by alalek** [comment]
Fixed (java test process hugs and didn't terminate properly).
