### ISSUE TITLE
Errors buliding libwebp on NVIDIA TX2 with Linaro gcc-5.4.0 using flags 

### ISSUE THREAD

**Issue by HoneyPatouceul** [opencv/opencv#12322]
Sorry if it is ot the right place for posting, please let me know:

##### System information (version)
```
- OpenCV => 4.0.0-pre (today's github-master)
- Operating System / Platform => NVIDIA L4T TX2 R28.2-DP2  arm 64 Bit
- Compiler =>c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 

```
##### Detailed description

Compiling opencv-4.0.0-pre on Jetson TX2 with 
`set (CMAKE_C_FLAGS             "-ffast-math -march=armv8-a+simd+crypto -mcpu=cortex-a57+simd+crypto" CACHE STRING "")` 
(also enabling LTO) leads to error : 
`[ 76%] Linking CXX shared library ../../lib/libopencv_imgcodecs.so
cd /media/nvidia/Data/opencv/github/build/TX2-R28.2-DP2-Flags+lto/modules/imgcodecs && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_imgcodecs.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC -ffast-math -march=armv8-a+simd+crypto -mcpu=cortex-a57+simd+crypto   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections -flto    -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fPIC -fopenmp -Wno-deprecated-declarations -O2 -DNDEBUG  -DNDEBUG -D_FORTIFY_SOURCE=2    -z noexecstack -z relro -z now   -shared -Wl,-soname,libopencv_imgcodecs.so.4.0 -o ../../lib/libopencv_imgcodecs.so.4.0.0 CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/utils.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdal.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_hdr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pxm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pfm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_base.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_exr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdcm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_tiff.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_bmp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_png.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pam.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_sunras.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/bitstrm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/rgbe.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/exif.cpp.o  -L/usr/local/cuda-9.0/lib64 ../../lib/libopencv_imgproc.so.4.0.0 -ldl -lm -lpthread -lrt /usr/lib/aarch64-linux-gnu/libGLU.so /usr/lib/aarch64-linux-gnu/libGL.so -lcudart -lnppc -lnppial -lnppicc -lnppicom -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcufft -L/usr/local/cuda-9.0/lib64 ../../3rdparty/lib/libtegra_hal.a ../../3rdparty/lib/libzlib.a ../../3rdparty/lib/liblibjpeg-turbo.a ../../3rdparty/lib/liblibwebp.a ../../3rdparty/lib/liblibpng.a ../../3rdparty/lib/liblibtiff.a ../../3rdparty/lib/liblibjasper.a ../../3rdparty/lib/libIlmImf.a -lcudart -lnppc -lnppial -lnppicc -lnppicom -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps ../../lib/libopencv_core.so.4.0.0 ../../lib/libopencv_cudev.so.4.0.0 -ldl -lm -lpthread -lrt /usr/lib/aarch64-linux-gnu/libGLU.so /usr/lib/aarch64-linux-gnu/libGL.so -lcudart -lnppc -lnppial -lnppicc -lnppicom -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcufft -lcudart -lnppc -lnppial -lnppicc -lnppicom -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcufft ../../3rdparty/lib/libzlib.a -Wl,-rpath,/usr/local/cuda-9.0/lib64:/media/nvidia/Data/opencv/github/build/TX2-R28.2-DP2-Flags+lto/lib: -Wl,-rpath-link,/media/nvidia/Data/opencv/github/build/TX2-R28.2-DP2-Flags+lto/lib 
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/enc_neon.c: In function ‘QuantizeBlock_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11344:7: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
   __o = __builtin_aarch64_set_qregoiv16qi (__o,
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11341:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_oi __o;
                             ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11344:7: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
   __o = __builtin_aarch64_set_qregoiv16qi (__o,
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11341:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_oi __o;
                             ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11344:7: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
   __o = __builtin_aarch64_set_qregoiv16qi (__o,
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11341:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_oi __o;
                             ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11344:7: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
   __o = __builtin_aarch64_set_qregoiv16qi (__o,
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:11341:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_oi __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/alpha_processing_neon.c: In function ‘DispatchAlphaToGreen_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23831:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregxiv16qi (__o, (int8x16_t) temp.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23825:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_xi __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/alpha_processing_neon.c: In function ‘DispatchAlpha_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23831:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregxiv16qi (__o, (int8x16_t) temp.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23825:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_xi __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/alpha_processing_neon.c: In function ‘ApplyAlphaMultiply_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23831:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregxiv16qi (__o, (int8x16_t) temp.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23825:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_xi __o;
                             ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23831:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregxiv16qi (__o, (int8x16_t) temp.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23825:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_xi __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/lossless_neon.c: In function ‘ConvertBGRAToRGB_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23628:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregciv16qi (__o, (int8x16_t) val.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23627:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_ci __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/lossless_neon.c: In function ‘ConvertBGRAToBGR_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23628:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregciv16qi (__o, (int8x16_t) val.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23627:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_ci __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/lossless_neon.c: In function ‘ConvertBGRAToRGBA_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23972:7: warning: ‘__o’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __o = __builtin_aarch64_set_qregxiv16qi (__o, (int8x16_t) val.val[0], 0);
       ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:23971:29: note: ‘__o’ was declared here
   __builtin_aarch64_simd_xi __o;
                             ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/dec_neon.c: In function ‘SimpleHFilter16_NEON’:
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:438: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:17848:176: note: ‘__o’ was declared here
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:334: warning: ‘__o’ is used uninitialized in this function [-Wuninitialized]
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:10356:0: note: ‘__o’ was declared here
 __ST2_LANE_FUNC (uint8x8x2_t, uint8x16x2_t, uint8_t, v8qi, v16qi, qi, u8,
 ^
/media/nvidia/Data/opencv/github/opencv/3rdparty/libwebp/src/dsp/dec_neon.c:531:1: internal compiler error: in record_operand_use, at regrename.c:220
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:604: recipe for target 'lib/libopencv_imgcodecs.so.4.0.0' failed
make[2]: *** [lib/libopencv_imgcodecs.so.4.0.0] Error 1
make[2]: Leaving directory '/media/nvidia/Data/opencv/github/build/TX2-R28.2-DP2-Flags+lto'
CMakeFiles/Makefile2:2526: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[1]: Leaving directory '/media/nvidia/Data/opencv/github/build/TX2-R28.2-DP2-Flags+lto'
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    Clone opencv4.0.0-pre from github
 build on TX2 configuring with :
`set (CMAKE_C_FLAGS             "-ffast-math -march=armv8-a+simd+crypto -mcpu=cortex-a57+simd+crypto" CACHE STRING "")
set (ENABLE_LTO                ON  CACHE BOOL "")`

**Comment by alalek** [comment]
> internal compiler error

We can't fix that.
Also we can't reproduce this, so you need to find some workaround by yourself.

**Comment by HoneyPatouceul** [comment]
Seems it is related to libwebp. I can use :
`set (CMAKE_ASM_FLAGS           "-ffast-math -march=armv8-a+simd+crypto -mcpu=cortex-a57+simd+crypto" CACHE STRING "")
set (CMAKE_CXX_FLAGS           "-ffast-math -march=armv8-a+simd+crypto -mcpu=cortex-a57+simd+crypto" CACHE STRING "")
`
but as soon as I enable this for CMAKE_C_FLAGS it issues many previous warnings about this __o being used initialized and finally leads this error.

Not sure if it is Linaro gcc-5.4.0 or libwebp bug...Please let me know if you know.

**Comment by alalek** [comment]
You can try to disable `libwebp` in your builds as a workaround: `cmake -DWITH_WEBP=OFF ...`

**Comment by tomoaki0705** [comment]
I just came over this issue, where I know the detour.
@HoneyPatouceul , you are running out of memory, and OOM killer is killing GCC.
That's what happening.

First, try with no ```-j``` option in ```make```.
```-j``` runs many compile in parallel, which consumes a lot of memory.
It might help you to kill the entire Gnome Desktop while you are building.

Anyway, I don't think this issue comes from OpenCV
