### ISSUE TITLE
The light does not turn off after sending photos #570

### ISSUE THREAD

**Issue by rollly00** [opencv/opencv#12338]
I use pytelegram bot for send photo.
When I run this code without a bot, the bulb is turned off, for its shutdown, it answers cap.release(), but I run this code through the bot, the bulb does not turn off.
`		cap = cv2.VideoCapture(0)
		ret, frame = cap.read()
		cv2.imwrite('1.jpg',frame)
		doc = open('1.jpg','rb')
		bot.send_document(message.chat.id,doc)
		cap.release(1)`

**Comment by alalek** [comment]
Duplicate of #12301

**Comment by rollly00** [comment]
It dont work for me. When I just run the script, the light turns off. When I call the script via bot telegrams, the bulb does not turn off

**Comment by rollly00** [comment]
OPENCV_VIDEOIO_PRIORITY_MSMF = 0, it worked for me, but when I compile the program, will it work on other computers?
