### ISSUE TITLE
Python3 samples/dnn/object_detection.py. OpenCV-tutorial on YOLOv3 does not work

### ISSUE THREAD

**Issue by NobuoTsukamoto** [opencv/opencv#12349]
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Fedora 28
- Compiler => GCC 8.1
- Python3 => 3.6.6

##### Detailed description
I tried to do the Python3 OpenCV-Sample on [yolov3](https://docs.opencv.org/3.4.2/da/d9d/tutorial_dnn_yolo.html).
I executed opencv/samples/dnn/object_detection.py. (https://github.com/opencv/opencv/blob/3.4.2/samples/dnn/object_detection.py)
But it did not work with errors(TypeError: integer argument expected, got float).

I executed the following command.
"""python3 object_detection.py --input=./test.jpg --model=./yolov3.weights --config=./yolov3.cfg --classes=./object_detection_classes_coco.txt --scale=0.00392 --width=416 --height=416
"""

All errors are below.
'''Traceback (most recent call last):
  File "object_detection.py", line 196, in <module>
    postprocess(frame, outs)
  File "object_detection.py", line 162, in postprocess
    drawPred(classIds[i], confidences[i], left, top, left + width, top + height)
  File "object_detection.py", line 73, in drawPred
    cv.rectangle(frame, (left, top), (right, bottom), (0, 255, 0))
TypeError: integer argument expected, got float
'''

I guess that in Python 3 the following operation result is a floating point number, not an integer.
https://github.com/opencv/opencv/blob/3.4.2/samples/dnn/object_detection.py#L145-L146

**Comment by alalek** [comment]
Perhaps this should work:
`cv.rectangle(frame, (int(left), int(top)), (int(right), int(bottom)), (0, 255, 0))`

**Comment by dkurt** [comment]
Or these two lines:
```python
left = int(center_x - width / 2)
top = int(center_y - height / 2)
```
