### ISSUE TITLE
Number of neighbors in knn classification

### ISSUE THREAD

**Issue by hrasti** [opencv/opencv#12347]
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
Python: 3.6.5

In KNN classification usually number of neighbors is considered to be less than the number of samples. However, if you use all samples as neighborhood size (k >= number of patterns) the function will always return the first class as the label for new patterns.
```
#import needed libraries'
import cv2.cv2 as cv
import numpy as np
from matplotlib import pyplot as plt

#Feature Vectors: Class 1
trainSample1 = np.random.randint(10,100,(100,2))
trainSample1 = np.float32(trainSample1)
x = trainSample1[:,0]
y = trainSample1[:,1]
plt.scatter(x, y, 7, 'b','o')

#Feature Vectors: Class 2
trainSample2 = np.random.randint(60,150,(100,2))
trainSample2 = np.float32(trainSample2)
x = trainSample2[:,0]
y = trainSample2[:,1]
plt.scatter(x, y, 7, 'r','^')

#Feature Vectors: Class 3
trainSample3 = np.random.randint(100,200,(100,2))
trainSample3 = np.float32(trainSample3)
x = trainSample3[:,0]
y = trainSample3[:,1]
plt.scatter(x, y, 7, 'm','+')

#Append Samples
allSamplesFeatures = trainSample1
allSamplesFeatures = np.append(allSamplesFeatures,trainSample2,axis=0)
allSamplesFeatures = np.append(allSamplesFeatures,trainSample3,axis=0)

#Targets of All Classes
allTargetFeatures = np.ones((100,1))
allTargetFeatures = np.append(allTargetFeatures, np.ones((100,1))*2,axis=0)
allTargetFeatures = np.append(allTargetFeatures, np.ones((100,1))*3,axis=0)
allTargetFeatures = np.float32(allTargetFeatures)

#Generate New Commers
newPoints = np.float32(np.random.randint(10,200,(50,2)))
plt.scatter(newPoints[:,0], newPoints[:,1], 15, 'g','*')

#Create KNN Classification Model
knn = cv.ml.KNearest_create()
knn.train(allSamplesFeatures, cv.ml.ROW_SAMPLE, allTargetFeatures)

#Classifying New Commers
NeighborSize = 300
ret, results, neighbours, dist = knn.findNearest(newPoints, NeighborSize)

#Plot and Print the Results
plt.show()
print("  ---->>>>>" , results , '\n')
```

I tested using different class numbers and features. The result was always the same for K>=#samples

I think the number of neighborhoods should be limited smaller than the "len(patterns)" and adding a simple condition at the beginning of "findNearest" function is necessary.

**Comment by berak** [comment]
i could reproduce your problem (from c++):
```
    Mat xTrainData = (Mat_<float>(5,2) << 1, 1.1, 1.1, 1, 2, 2, 2.1, 2, 2.1, 2.1);
    Mat yTrainLabels = (Mat_<float>(5,1) << 1, 1, 2, 2, 2);
    Ptr<KNearest> knnKdt = KNearest::create();
    knnKdt->train(xTrainData, ml::ROW_SAMPLE, yTrainLabels);

    Mat xTestData = (Mat_<float>(2,2) << 1.1, 1.1, 2, 2.2);
    Mat zBestLabels, neighbours, dist;
    int K = 16;
    knnKdt->findNearest(xTestData, K, zBestLabels, neighbours, dist);
    cout << zBestLabels << endl;
    cout << neighbours << endl;
    cout << dist << endl;

[0;
 0]
[1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0.010000004, 0.010000004, 1.6199999, 1.8099997, 1.9999995, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+0
38, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038;
 0.020000011, 0.040000018, 0.049999997, 2.21, 2.25, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038, 3.40
28235e+038, 3.4028235e+038, 3.4028235e+038, 3.4028235e+038]
```
and you can imagine, what the majority vote of the neighbours results into ...

> I think the number of neighborhoods should be limited smaller than the "len(patterns)" and adding a simple condition at the beginning of "findNearest" function is necessary.

there already is a condition like this here:
https://github.com/opencv/opencv/blob/90f47eb952749b73c28ca7149fdd0c0cfd2b202d/modules/ml/src/knearest.cpp#L149
but it's applied far too late, the neighbours and dists are already allocated with wrong sizes.

if we move the check here:
https://github.com/opencv/opencv/blob/master/modules/ml/src/knearest.cpp#L309
(and add one for the (still broken!!) kdtree), 

we get correct results (still with K=16, and the code above):
```
[2;
 2]
[1, 1, 2, 2, 2;
 2, 2, 2, 1, 1]
[0.010000004, 0.010000004, 1.6199999, 1.8099997, 1.9999995;
 0.020000011, 0.040000018, 0.049999997, 2.21, 2.25]
```

**Comment by hrasti** [comment]
Thank you @berak for answering. However, I am using python 3.6.5 and opencv 3.4.2. I checked the KNN classification using different Ks, and in the cases which k was bigger than or equal to the number of samples, the function always returned the first class as the label.

**Comment by berak** [comment]
@hrasti, this pr went into 3.4.3, so you will need to update the opencv src and recompile your cv2
(or wait for the next 3.4.4 release, if you're using PIP).

apart from that: this pr only changed correct "clamping" of K to the number of train samples available, so no more bogus values go into the calculation.

however, you can only expect it to return a correct result as long as K is smaller than the average sample count per class (100 in your example), 
else, (even if all works correctly) there *have to be* samples of other classes in the majority voting.
