### ISSUE TITLE
`cv::String` has no member named `assign`

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12352]
Currently, the farm suffers a regression with an error:
```
/build/precommit_custom_linux/opencv_contrib/modules/hdf/src/hdf5.cpp: In member function 'virtual void cv::hdf::HDF5Impl::atread(cv::String*, const cv::String&)':
/build/precommit_custom_linux/opencv_contrib/modules/hdf/src/hdf5.cpp:450:12: error: 'class cv::String' has no member named 'assign'
     value->assign(buf.data(), size);
            ^
make[2]: *** [modules/hdf/CMakeFiles/opencv_hdf.dir/src/hdf5.cpp.o] Erro
```
Please refer to the builds [[1]](http://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/932), [[2]](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/17416), [[3]](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl_linux/builds/17018), or [[4]](http://pullrequest.opencv.org/buildbot/builders/precommit_macosx/builds/16793) for details

**Comment by alalek** [comment]
Missing merge of #12293. Should be fixed now, builds are restarted.
