### ISSUE TITLE
C++ NDK cv::VideoCapture.open(http_url) return false on iOS

### ISSUE THREAD

**Issue by omatrot** [opencv/opencv#12378]
##### System information (version)

- OpenCV => 3.4.2 from OpenCV2 Cocoa Pod
- Operating System / Platform => Mac OSX
- Compiler => XCode 9.4.1

##### Detailed description

I've already asked about that in the Q/A Forum with no answer.
http://answers.opencv.org/question/197907/c-ndk-cvvideocaptureopenhttp_url-return-false-on-ios/

I'm using the OpenCV2 POD version 3.4.2 to build an app on iOS. I know that there are restrictions imposed by the underlying system for security reason. 

I've configured my app to allow exceptions. 

The problem seems to be related to OpenCV. How could I know the real problem here ? Returning just a boolean falls short

##### Steps to reproduce

    ```.cpp
    cv::VideoCapture cap;
    // This call returns false on iOS
    cap.open("http://210.232.19.233/cgi-bin/camera?resolution=640&amp;quality=1");
    ```

You can try the URL in a browser to see that an image is returned.

Thanks in advance.

**Comment by alalek** [comment]
OpenCV uses AVFoundation on iOS. So, try to read video via AVFoundation API before trying to fix OpenCV directly.

**Comment by Tsingkai** [comment]
I meet this problem ,too.
VideoCapture.open(url) always return false value……
Someone think the error is opencv  don't call ffmpeg……

Do you solve the problem?

**Comment by omatrot** [comment]
Nope I switched to other projects since then.

**Comment by Tsingkai** [comment]
today, I install x264 and ffmpeg on ubuntu 20.04,solved!
