### ISSUE TITLE
wiki - Contributors page

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#12375]
- Dalal, Navneet home page link must be updated ([actual link](http://www.navneetdalal.com/) is unrelated). May be [this link](https://scholar.google.com/citations?user=C6UAIHEAAAAJ&hl=en)
   - it will be nice if the Individual Contributors list would be updated.

See [wiki/Contributors](https://github.com/opencv/opencv/wiki/Contributors)

**Comment by csukuangfj** [comment]
@alalek 
Why not make the wiki pages public editable? For example, please refer to this page
https://github.com/ros2/ros2/wiki

**Comment by alalek** [comment]
For anyone without any review - we definitely don't want this.
For a list of contributors - there is no GitHub option to grant Wiki access without full write access to code repository.
