### ISSUE TITLE
vs2017 opencv3.2 Function "drawContours()" error

### ISSUE THREAD

**Issue by sicilyuu** [opencv/opencv#12381]
- OpenCV => 3.2
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2017

I used the function "findContours()" to obtain the contours.
And then ,I want to draw them on the image by function "drawContours()",but there is a exception described as below:
**OpenCV Error: Assertion failed (i < 0) in cv::_InputArray::getMat_, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\matrix.cpp, line 1215**

I had search many sites to deal with it . But no works.
Any help will be appreciated.
——————————update 13/9/2018
Sorry for the invalid question.
I know that "drawContours()" funciton could not accept a single input contour parameter now .It can only deal with contours vector.
I fixed the code, and it worked.

**Comment by sturkmen72** [comment]
@sicilyuu please close the issue.
