### ISSUE TITLE
Retrained on tensorflow faster RCNN inceptionv2  for my dataset without result

### ISSUE THREAD

**Issue by bleedingfight** [opencv/opencv#12390]
# The Problem
I used tensorflow object detecttion models train my model detect my data（chess）。I have Only one class。my models can detect object with tensorflow but can't do it with opencv.
## Environment
```
python 3.5.2
tensorflow 1.10.0
opencv 3.4.2(pip install python-opencv)

```
## Detail of my repo
My model is `faster_rcnn_inception_v2_coco_2018_01_28`
- `python tf_text_graph_faster_rcnn.py` is from [Here](https://github.com/opencv/opencv/tree/master/samples/dnn)
- ` frozen_inference_graph_coco.pb` is original trained model on coco from Google(I have renamed it).
- ` frozen_inference_graph.pb` is my model).

I was trained my models with `faster_rcnn_inception_v2_coco_2018_01_28`,and try to use it detect person.you can get the code from [here](https://github.com/bleedingfight/tf_obj/blob/master/inceptionv2_coco.png)(you can clone my repo and run `python test_coco.py`)

the result is:
![my](https://github.com/bleedingfight/tf_obj/blob/master/use_tensorflow.png?raw=true)
but I use `python tf_text_graph_faster_rcnn.py  --input frozen_inference_graph_coco.pb(I had renamed it) --output graph_coco.pbtxt`.
![re](https://github.com/bleedingfight/tf_obj/blob/master/inceptionv2_coco.png?raw=true)
but I used the same method `python tf_text_graph_faster_rcnn.py  --input frozen_inference_graph.pb(I had renamed it) --output graph.pbtxt --num_classes 1` and then `python test.py`,the result is like that:
![Origin](https://github.com/bleedingfight/tf_obj/blob/master/examples.png?raw=true)
Had I get something wrong?I'm looking forward your help,thanks very much.

**Comment by dkurt** [comment]
@bleedingfight, we cannot determine if it's a bug or incorrect usage until you provide steps to reproduce. Please add a code snippet with networks usage or put a reference to mentioned models if it's possible.

**Comment by bleedingfight** [comment]
@dkurt Thanks for your help,I add my process code on my article,I don't know what else I need post.If you need some other code you can reply me under the article.Thanks for you kindness.

**Comment by dkurt** [comment]
@bleedingfight, there are only references to .png images. Do you use OpenCV's [object_detection samples](https://github.com/opencv/opencv/tree/master/samples/dnn) or a custom code?

**Comment by dkurt** [comment]
@bleedingfight, this information is not enough to help you. Please use http://answers.opencv.org to figure out if the problem is in your code or in OpenCV. No one can even reproduce results mentioned in the issue because there is no model or code.

**Comment by bleedingfight** [comment]
@dkurt thanks for your reply.My all code in [My Repo](https://github.com/bleedingfight/tf_obj).I don't know what's wrong my uploaded image can;t be show.You can get all picture or code from my repo.

**Comment by dkurt** [comment]
@bleedingfight, The thing is that TensorFlow resizes input image inside a graph. In example, your model works fine with 800x800 input size:
```
python object_detection.py --model frozen_inference_graph.pb --config graph.pbtxt --width 800 --height 800 --rgb --input examples.png
```
![out](https://user-images.githubusercontent.com/25801568/44985972-f1b02280-af8a-11e8-9a67-4bcf33dd5777.png)

**Comment by bleedingfight** [comment]
@dkurt Maybe my opencv have some problem.I reinstall it but i can't see the same result as your show.
my resuls is like:[](https://github.com/bleedingfight/tf_obj/blob/master/Deep%20learning%20object%20detection%20in%20OpenCV_screenshot_04.09.2018.png)

**Comment by bleedingfight** [comment]
@dkurt I try to run this command `ptyhon tf_text_graph_faster_rcnn.py --input frozen_inference_graph.pb --output graph.pbtxt --num_classes 1`
and then I use your command:
`python object_detection.py --model frozen_inference_graph.pb --config graph.pbtxt --width 800 --height 800 --rgb --input examples.png`
but I can't get any result,I don't know what's wrong.Can you send me your code?I want to know what difference of our code.my email is`bleedingfight@126.com`.Thanks for your help again.

**Comment by dkurt** [comment]
@bleedingfight, can we close an issue?

**Comment by bleedingfight** [comment]
yes，thanks！



来自 魅族 PRO 5



-------- 原始邮件 --------
发件人：Dmitry Kurtaev <notifications@github.com>
时间：周二 9月4日 18:08
收件人：opencv/opencv <opencv@noreply.github.com>
抄送：bleedingfight <bleedingfight@hotmail.com>,Mention <mention@noreply.github.com>
主题：Re: [opencv/opencv] Retrained on tensorflow faster RCNN inceptionv2 for my dataset without result (#12390)


@bleedingfight<https://github.com/bleedingfight>, can we close an issue?
