### ISSUE TITLE
cv.Mat() wasm binding issue

### ISSUE THREAD

**Issue by mash-graz** [opencv/opencv#12417]
##### System information (version)
- OpenCV => git master
- Operating System / Platform => linux, wasm
- Compiler => emscripten

##### Detailed description

while using the wasm binding of opencv in [pyodide notebooks](https://github.com/iodide-project/pyodide), i stumbled over issues utilizing the cv.Mat() constructor. i always get error messages in the browser console.  
Firefox reports:

    TypeError: cv.Mat is not a constructor

 and Chromium  advises to use the java script 'new' keyword:

    "BindingError", message: "Use 'new' to construct Mat"

this solution is unfortunately not possible, because this keyword resp. language feature isn't available, if you use opencvjs resp. the wasm bindings from python. i had to workaround by cloning another Mat instance, which was created via cv.imread()...

the cause of this issue seems to be the same, which has already affected efforts to build opencv rust bindings: https://github.com/rust-lang-nursery/rust-bindgen/issues/348
 
unfortunately i couldn't figure out any emscripten compile time options, which would eliminate this nasty side effects of the **inline** constructor in the resulting wasm bindings.

##### Steps to reproduce

[here]( http://users.mur.at/ms/attachments/pyodide-opencv-issue/opencv.html) you'll find a very simple pyodide notebook to reproduce the bug.

**Comment by electronicwhisper** [comment]
I was googling this error (had it as well) and I found [this reference](https://dev.to/kjunichi/requireopencvjs-is-not-enough-for-using-opencvjs-8ff) which fixed it for me.

Relevant code:

```
const cv = require("./opencv.js");
cv['onRuntimeInitialized']=()=>{
          let mat = new cv.Mat();
          console.log(mat.size());
          mat.delete();
};
```

**Comment by dkurt** [comment]
As @skmbr noticed in https://github.com/opencv/opencv/issues/13356, it looks like wasm compilation is inside opencv.js now.

@electronicwhisper, For HTML pages we can also emit `require` as follows:

```html
<script src="./opencv.js" type="text/javascript"></script>
```
```js
cv['onRuntimeInitialized']=()=>{
  var m = new cv.Mat(4, 5, cv.CV_8UC3);
}
```

Let me close this issue.
