### ISSUE TITLE
Unable to load tensorflow .pb model with readNetFromTensorflow: Tensor's datatype is not supported in function 'getTensorContent'

### ISSUE THREAD

**Issue by ricardo-0x07** [opencv/opencv#12416]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => macOS High Sierra v 10.13.6
- Compiler => Visual Studio code Cmake g++

##### Detailed description

Unable to load tensorflow model with readNetFromTensorflow.

I'm attempting to use a custom model built in python in a C++ opencv project and got the following error while trying to import the model: 
```error: (-2:Unspecified error) Tensor's datatype is not supported in function 'getTensorContent'```

##### Steps to reproduce

Extracted the tensorflow model as a .pb file with 
python
```def export_model(saver, model, input_node_names, output_node_name):
    tf.train.write_graph(K.get_session().graph_def, 'out', \
                         MODEL_NAME + '_graph.pbtxt')

    saver.save(K.get_session(), 'out/' + MODEL_NAME + '.chkp')

    freeze_graph.freeze_graph('out/' + MODEL_NAME + '_graph.pbtxt', None, \
                              False, 'out/' + MODEL_NAME + '.chkp', output_node_name, \
                              "save/restore_all", "save/Const:0", \
                              'out/frozen_' + MODEL_NAME + '.pb', True, "")

    input_graph_def = tf.GraphDef()
    with tf.gfile.Open('out/frozen_' + MODEL_NAME + '.pb', "rb") as f:
        input_graph_def.ParseFromString(f.read())

    output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        input_graph_def, input_node_names, [output_node_name],
        tf.float32.as_datatype_enum)

    with tf.gfile.FastGFile('out/opt_' + MODEL_NAME + '.pb', "wb") as f:
        f.write(output_graph_def.SerializeToString())

    print("graph saved!")

    return``` 

imported attempted to import it opencv c++ with: 
```Net net = readNetFromTensorflow(weights);``` 

and got the following error:
```ibc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.2) /tmp/opencv-20180704-99354-1kt9ska/opencv-3.4.2/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:712: error: (-2:Unspecified error) Tensor's datatype is not supported in function 'getTensorContent'```

**Comment by dkurt** [comment]
@ricardo-0x07, provide model configuration or attach mentioned `.pb` file. Otherwise it's impossible to reproduce.

**Comment by ricardo-0x07** [comment]
here is a link to mentioned .pb file: https://drive.google.com/open?id=1e_NVBjRK2rI-oTp00sohIJlYDmu7PfnH

**Comment by ricardo-0x07** [comment]
@dkurt kindly see a link to the file .pb file

**Comment by ricardo-0x07** [comment]
@dkurt i getting this error when i don't pass the .pbtxt file: error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:532: error: (-2:Unspecified error) Const kernel input not found in function 'getConstBlob'

**Comment by ricardo-0x07** [comment]
Solved the issue replaces the only flatten layer with a GlobalAveragePooling2D which gave even better performance

**Comment by dkurt** [comment]
@ricardo-0x07, this model has a subgraph with two inputs:
![screenshot from 2018-09-19 18-46-08](https://user-images.githubusercontent.com/25801568/45764900-6bf3ce80-bc3c-11e8-8499-7e867b0f3e19.png)
Could you please clarify the difference between `norm_input_input_5` and `input` placeholders?

**Comment by dkurt** [comment]
Closing it due no response from author.
