### ISSUE TITLE
iOS Framework build failure with Xcode 10 beta 6, related to NEON

### ISSUE THREAD

**Issue by amrox** [opencv/opencv#12418]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform = macOS 10.13.6
- Compiler = Xcode Version 10.0 beta 6 (10L232m)

##### Detailed description

OpenCV iOS framework build fails against most recent Xcode 10 beta. The following error occurs:

```
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:458 (message):
  Required baseline optimization is not supported: NEON
  (CPU_BASELINE_REQUIRE=;NEON)
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:259 (include)
  CMakeLists.txt:555 (include)


-- Performing Test HAVE_CPU_BASELINE_FLAGS
-- Performing Test HAVE_CPU_BASELINE_FLAGS - Failed
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:505 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:261 (ocv_compiler_optimization_options)
  CMakeLists.txt:555 (include)
```

I realize that this is a *beta* version of Xcode, but the final version is expected to be released next week, and I was hoping someone else may have seen this issue. Full log is here: https://gist.github.com/amrox/522e7968c5badbb2fdd168068843e808

This seems very similar to 
https://github.com/opencv/opencv/issues/10363 https://github.com/opencv/opencv/issues/8945 but this issue is said to be fixed in 3.4.1, and I'm still seeing it in 3.4.2 and 3.4.3.

Finally this *only* happens when using the Xcode beta toolchain. If I switch back to Xcode 9.4.1 (9F2000) it builds fine.

##### Steps to reproduce

1. Checkout opencv, tested against `3.4.3` `3.4.2` and `d74b98c3d9264f9623b27a8d4e0fc92ac97b71d0`
2. build iOS framework with: `python platforms/ios/build_framework.py build/ios`

Edit:

It appears the real problem is due to the fact that libstdc++ is deprecated in Xcode 10 / iOS 12 toolchain and Apple wants you to move to libc++

CMakeError.log: [CMakeError.log](https://github.com/opencv/opencv/files/2352853/CMakeError.log)

**Comment by alalek** [comment]
Please attach contents of `CMakeFiles/CMakeError.log` file.

**Comment by alalek** [comment]
Try to change/drop `libc++` option [here](https://github.com/opencv/opencv/blob/3.4.3/platforms/ios/cmake/Modules/Platform/iOS.cmake#L52).

**Comment by bommo1** [comment]
Changing everywhere the deployment target to 8.0 (7.0 will probably also work) solved it for me.

https://github.com/opencv/opencv/blob/master/platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake#L113

https://github.com/opencv/opencv/blob/master/platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake#L130

https://github.com/opencv/opencv/blob/master/platforms/ios/build_framework.py#L164

**Comment by amrox** [comment]
@bommo1 thanks that worked for me too!

I found that the change on line https://github.com/opencv/opencv/blob/master/platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake#L130 was not necessary for me though

 I opened a PR https://github.com/opencv/opencv/pull/12586

**Comment by jacobg** [comment]
Will this fix be backported to older versions of OpenCV, e.g., version 2?
