### ISSUE TITLE
OpenCV Can not detect the Car, but the darknet.exe can. Why?

### ISSUE THREAD

**Issue by leekwunfung817** [opencv/opencv#12413]
My Development Environment
1. Windows 10
2. Java 1.8.0_171
3. Netbeans 8.2
4. OpenCV 3.4.2

`blobFromImage(image, scalefactor, size, mean, swapRB, crop)`
`org.opencv.dnn.Dnn`

I test a photo with two different environment
### Situation
I want to detect two object, **Car** and **License Plate**.
I use the same model to detect a photo in two different setting.
I want to know the parameter that darknet are using, for correct detection result.

same
1. I use the same model
2. I use the same (.cfg) file and structure

different
1. used in Java or Python OpenCV
2. Unknown (scalefactor, mean, swapRB, crop) parameter

### I cannot detect the **Car** using
`blobFromImage(image, (1.0F / 127.5F), (416, 416), Scalar(0), false, false)`
![h_20180512140207_45437358](https://user-images.githubusercontent.com/18736700/44955167-b4dc2100-aee1-11e8-9636-c7054641bfa0.jpg)

### But darknet application result are able to detect the **Car**:
`darknet.exe detector test ...`
![predictions](https://user-images.githubusercontent.com/18736700/44955181-dccb8480-aee1-11e8-8c99-52b6fbeb5413.jpg)

-  yolov3-tiny.cfg
- I am using Java OpenCV Library, (blobFromImage) perhaps is the only function I can call

**My difficult is not able to detect Car, I want to find the solution.**

The follow is my Java code for loading Darknet CNN model and Detect Image
```
        net = Dnn.readNetFromDarknet(cfg, weights);
        if (net.empty()) {
            System.out.println("Reading Net error");
        }

        Mat im = Imgcodecs.imread(full_path, Imgcodecs.IMREAD_COLOR);
        if (im.empty()) {
            System.out.println("Reading Image error: " + full_path);
        }

        Mat frame = new Mat();
        Size sz1 = new Size(im.cols(), im.rows());
        Imgproc.resize(im, frame, sz1);

        Mat resized = new Mat();
        Size sz = new Size(416, 416);
        Imgproc.resize(im, resized, sz);

        float scale = 1.0F / 127.5F;
        Mat inputBlob = Dnn.blobFromImage(frame, scale, sz, new Scalar(0), false, false);

        net.setInput(inputBlob, "data");

        Mat detectionMat = net.forward("yolo_23");
        if (detectionMat.empty()) {
            System.out.println("No result");
        }
```

The yolo_23 is the yolov3-tiny last layer name

**Why my program cannot detect the Car, but Darknet.exe are able to detect?**

**Comment by alalek** [comment]
Attach origin image in PNG format (or other lossless format).

**Comment by alalek** [comment]
Also try existed OpenCV samples (there is object detection samples on Python / C++).

**Comment by dkurt** [comment]
Yeah, YOLOv3 has three output detection branches. You need to take outputs from all of them and apply non-maximum suppression. Each of branches is responsible for different size detections (small, medium and large). It looks like using OpenCV you draw predictions only from branch with small detections. Car is a big object.
As @alalek said, try to use [object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) or [object_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py).
