### ISSUE TITLE
 cmake failed when compiling opencv 3.3.0 on Respbian Stretch

### ISSUE THREAD

**Issue by xyG67** [opencv/opencv#12425]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Rapbian Stretch
- Compiler => gcc 6.3

##### Detailed description

I try to install opencv3 on Raspberry Pi. I download opencv-3.3.0 and opencv-contribe-3.3.0 then try to compile it. Configuration failed using cmake command: 

`cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.0/modules \
    -D BUILD_EXAMPLES=ON ..`

output:

-- Configuring incomplete, errors occurred!

Part of the error.log

`
Build output check failed:
    Regex: 'command line option .* is valid for .* but not for C\+\+'
    Output line: 'cc1plus: warning: command line option Wstrict-prototypes is valid for C/ObjC but not for C++'
Compilation failed:
    source file: '/home/pi/Desktop/opencv-3.3.0/build/CMakeFiles/CMakeTmp/src.cxx'
    check option: ' -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations  -Wstrict-prototypes'
`

**Comment by alalek** [comment]
> Part of the error.log

It is not related to CMake error. This file just contains results of checks.
