### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Tockra** [opencv/opencv#12427]
##### System information (version)
- OpenCV =>master branch
- Operating System / Platform => Linux 9bfa02303e1e 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 20:00:40 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
- Compiler => gcc 5.4 ? (I'm using the Makefile)

##### Detailed description

**When I build cmake, I get the following error after 100%  (It's new, before 7 days it worked correct):**

/usr/bin/ld: CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o: In function `pyopencv_cv_cuda_cuda_DeviceInfo_computeMode(_object*, _object*, _object*)':
cv2.cpp:(.text._ZL44pyopencv_cv_cuda_cuda_DeviceInfo_computeModeP7_objectS0_S0_+0x10c): call to `_object* pyopencv_from<unsigned int>(unsigned int const&)' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/python3/CMakeFiles/opencv_python3.dir/build.make:111: recipe for target 'lib/python3/cv2.cpython-35m-powerpc64le-linux-gnu.so' failed
make[2]: *** [lib/python3/cv2.cpython-35m-powerpc64le-linux-gnu.so] Error 1
CMakeFiles/Makefile2:7500: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

##### Steps to reproduce
git clone https://github.com/opencv/opencv.git
cd opencv/
mkdir build
cd build/
cmake -D CMAKE_BUILD_TYPE=RELEASE ..
make -j5

**Comment by Tockra** [comment]
Okay sorry, I think the best idea is not to use the master branch 🤦‍♂️

**Comment by alalek** [comment]
Probably related: #12234
Master branch should be able to compile successfully too.

Mentioned symbol should be handled by this [line](https://github.com/opencv/opencv/pull/12234/files#diff-89d22c654c2f89080be8b4f570671affR28).

Unfortunately, we doesn't have native PowerPC build environment (only cross-compilation is checked), so we can't help here really.

As a workaround you can disable Python bindings: `cmake -DBUILD_opencv_python3=OFF ...`

/cc @seiko2plus Could you take a look on this?

**Comment by Tockra** [comment]
So I don't have this problem anymore with the 3.4 branch. 

But I can test the commits of the last few days and tell you which commit broke it

**Comment by seiko2plus** [comment]
@alalek, Yes exactly error caused after merge #12234, you can check following builds for more clarification.
[gcc4.9](https://ocv-power.imavr.com/#/builders/3/builds/66),  [gcc5.5](https://ocv-power.imavr.com/#/builders/2/builds/2), [gcc6.4](https://ocv-power.imavr.com/#/builders/7/builds/2),
[clang-4.0.1](https://ocv-power.imavr.com/#/builders/1/builds/2), [clang-5.0.2](https://ocv-power.imavr.com/#/builders/5/builds/1), [clang-6.0.1](https://ocv-power.imavr.com/#/builders/4/builds/1)

@Tockra, Please could you try #12452? it should resolve this issue.
