### ISSUE TITLE
how to implement pixellink ?

### ISSUE THREAD

**Issue by gds101054108** [opencv/opencv#12422]
Hello,I have use pixellink (https://github.com/ZJULearning/pixel_link) did some text detect experiments,the result show that pixellink is quit good.But I can't  implement the postprocessing called disjoint-set method to get the text instance from scoremap and linkmap.Please implement it as soon as possible?

**Comment by alalek** [comment]
Linked repository is without any license - strong blocker.
Also new experimental algorithms should go into contrib repository first: https://github.com/opencv/opencv_contrib
