### ISSUE TITLE
DNN convolution_layer.cpp Assertion fails using  `resnet_ssd_face_python.py` from samples

### ISSUE THREAD

**Issue by ngageorange** [opencv/opencv#12430]
##### System information (version)

- OpenCV => 3.3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC

##### Detailed description

Assertion at line convolutional_layer.cpp:78:
`CV_Assert(input.dims == 4 && (input.type() == CV_32F || input.type() == CV_64F));`

 fails when running the `resnet_ssd_face_python.py` face detector sample. The assertion combines the assertion of dimensionality and type and i'm not exactly sure why it fails. I'm pretty sure it's not the dimensions that are a problem as I've tried also adding an alpha channel (to ensure that dims=4) and the assertion still return false. 
Interestingly, this worked fine using 3.2 before the DNN module was moved from opencv_contrib to the main lib.

##### Steps to reproduce
Run this python script:

[https://github.com/opencv/opencv/blob/3.3.1/samples/dnn/resnet_ssd_face_python.py](https://github.com/opencv/opencv/blob/3.3.1/samples/dnn/resnet_ssd_face_python.py)

**Comment by alalek** [comment]
> 3.3.1

Try the latest code from 3.4 branch. We don't work on previous releases.

**Comment by ngageorange** [comment]
Thank you for your prompt response. 
Unfortunately this is part of a larger robotics platform and upgrading to the latest version of OpenCV is a big undertaking. 
The changes that have occurred in `convolutional_layer.cpp` are minimal between 3.3.1 and 3.4 and thus shouldn't affect the outcome of this. 
I understand that this is not ideal but your help is appreciated

**Comment by dkurt** [comment]
@ngageorange, please show a shape of input `blob`:
```
blob = dnn.blobFromImage(frame, 1.0, (inWidth, inHeight), (104.0, 177.0, 123.0), False, False)
print(blob.shape)
```

**Comment by ngageorange** [comment]
It's [1, 3, 300, 300]. I tried adding an alpha channel as the assertion
requires a dimension of 4 so that the shape is [1, 4, 300, 300] but the
assertion also fails.

**Comment by dkurt** [comment]
@ngageorange, `dims` is a number of dimensions. It should be 1, 3, 300, 300 (4 in total).
Does `.prototxt` and `.caffemodel` is from the same version of OpenCV? (3.3.1)

**Comment by ngageorange** [comment]
Ah right - I presumed that the `Mat &input = *inputs [0]` which the
assertion is done on refers to the "dimensions" of the image hence the
tinkering...

Yes, the caffe parameters and weights is from the 3.3.1 tag.

Have you managed to run it? Thanks for your help with this!

**Comment by dkurt** [comment]
@ngageorange, did you use files from this locations?
https://github.com/opencv/opencv/blob/3.3.1/samples/dnn/face_detector/deploy.prototxt
https://github.com/opencv/opencv_3rdparty/blob/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel

**Comment by ngageorange** [comment]
@dkurt apologies for the late reply- I couldn't get to my computer to be absolutely sure but yes, they are from the exact location.
Thanks again for helping out! Any further thoughts?

**Comment by dkurt** [comment]
@ngageorange, cannot reproduce your problem.
commit: a871f9e4f7d83dc5851f965bdba5cd01bb7527fe
command line:
```
cd /path/to/opencv/samples/dnn
python resnet_ssd_face_python.py
```

**Comment by dkurt** [comment]
@ngageorange, Does the problem has been solved?

**Comment by ngageorange** [comment]
@dkurt thank you for your help. You're correct - the 3.3.1 branch of OpenCV works perfectly when I've recompiled ; it must be the way I've installed opencv prior to this.

Thank you for your kind help.
