### ISSUE TITLE
Compilation error WITH_OPENMP

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv#12447]
OpenCV => master
 Operating System / Platform => Windows 64 Bit
 Compiler => Visual Studio 2017
CMake option WITH_OPENMP=ON

Here: https://github.com/opencv/opencv/blob/master/modules/core/src/parallel.cpp#L553
pbody need integer value: https://github.com/opencv/opencv/blob/master/modules/core/src/parallel.cpp#L428

**Comment by alalek** [comment]
Duplicate of #11998
