### ISSUE TITLE
run faster rcnn detection

### ISSUE THREAD

**Issue by lvpchen** [opencv/opencv#12457]
Hello:
    when I run faster rcnn detection demo, encount this error.
Error: Assertion failed <<numPriors * _numLocClasses * 4> == inputs[0][1]> in cv::dnn::DetectionOutputLayerImpl::getMemoryShapes

Help me, please.
thank you.

**Comment by dkurt** [comment]
@lvpchen, this is not enough to help you. Provide references to used model, add some code snippet.
