### ISSUE TITLE
Why there is no package 'org.opencv.img_hash' in opencv-343.jar？

### ISSUE THREAD

**Issue by lzx2005** [opencv/opencv#12456]
Why there is no package 'org.opencv.img_hash' in opencv-343.jar？

![image](https://user-images.githubusercontent.com/10736437/45198055-16600f00-b297-11e8-8bd1-22e4cd917a8e.png)

but the Java Documentation has

![image](https://user-images.githubusercontent.com/10736437/45198109-5de69b00-b297-11e8-9032-35006a18fc3a.png)

**Comment by berak** [comment]
this is not a bug.

the prebuilt opencv libs only contain modules from the main opencv repo

you need to rebuild the sdk with https://github.com/opencv/opencv_contrib/

[build instructions are here](https://github.com/opencv/opencv/tree/master/platforms/android)

**Comment by lzx2005** [comment]
thx
