### ISSUE TITLE
opencv 4.0.0 cv2.so: undefined symbol: _Z11pyopencv_toIjEbP7_objectRT_PKc

### ISSUE THREAD

**Issue by cafrank** [opencv/opencv#12468]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 18.04.1, ARM processor. 
- Compiler => gcc/g++

##### Detailed description

When python imports cv2, it references an undefined symbol: 

ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _Z11pyopencv_toIjEbP7_objectRT_PKc

##### Steps to reproduce

    cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/git/opencv_contrib/modules \
    -D BUILD_opencv_python3=ON \
    -D BUILD_opencv_python2=ON \
    -D BUILD_EXAMPLES=ON ..
make install
python3
>>> import cv2
ImportError: /usr/local/lib/python3.6/dist-packages/cv2.cpython-36m-aarch64-linux-gnu.so: undefined symbol: _Z11pyopencv_toIjEbP7_objectRT_PKc

**Comment by alalek** [comment]
ARMv8  64-bit?

Probably similar issue: #12427

**Comment by cafrank** [comment]
Yes. Using 64bit Cortex-A72, Cortex-A53

**Comment by alalek** [comment]
@cafrank Could you try this patch: #12478 ?
