### ISSUE TITLE
Darknet tests - NMS is done layer-wise not global

### ISSUE THREAD

**Issue by kopytjuk** [opencv/opencv#12474]
In darknet tests in `test_darknet_importer.cpp` we itarate over output layers and collect boxes. Each output layer performed NMS on its bounding boxes while inference. We should also do NMS on a network level AFTER we collected all bboxes. It looks like that we will need a custom "dnn.forward" function which returns NMS filtered bounding boxes on a global (network) level.

The original darknet C-implementation seems to do that...

**Comment by dkurt** [comment]
@kopytjuk, yeah, you're right. You may use [object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) for reference implementation of described procedure.

**Comment by dkurt** [comment]
fixed at https://github.com/opencv/opencv/pull/12249
