### ISSUE TITLE
Wrong Memory management

### ISSUE THREAD

**Issue by pkr97** [opencv/opencv#12470]
Hello All,
        I have followed the guide and implemented the usage of tensorflow model .pb file along with .pbtxt config file.

This is the case where I'm supplying an image just to test the functionality. 
Below is the code that I'm using for it.

"
import cv2 as cv

cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'ssd_mobilenet_v1_coco_hat.pbtxt')

img = cv.imread('495.jpg')
rows = img.shape[0]
cols = img.shape[1]
cvNet.setInput(cv.dnn.blobFromImage(img, 1.0/127.5, (300, 300), (127.5, 127.5, 127.5), swapRB=True, crop=False))
cvOut = cvNet.forward()

for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    print(score)
    if score > 0.75:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        print(left)
        print(top)
        print(right)
        print(bottom)
        cv.rectangle(img, (int(left)-50, int(top)-50), (int(right)+50, int(bottom)+50), (23, 230, 210), thickness=2)

cv.imshow('img', img)
cv.waitKey()
"
and it works fine and detects the object.

When I tried to implement the same thing but with a life feed from camera it eats up all CPU. It runs with 550-650% of CPU Usage. My PC has 8 cores and 6MB cache with 8GB RAM and a i7 one.

Below is the code that I'm using for live webcam feed test.

"
import cv2

cvNet = cv2.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'ssd_mobilenet_v1_coco_hat.pbtxt')

video = cv2.VideoCapture(1)
ret = video.set(3,640)
ret = video.set(4,480)

while(True):
	
	ret, img = video.read()
	rows = img.shape[0]
	cols = img.shape[1]
	cvNet.setInput(cv2.dnn.blobFromImage(img, 1.0/127.5, (300, 300), (127.5, 127.5, 127.5), swapRB=True, crop=False))
	cvOut = cvNet.forward()
	
	for detection in cvOut[0,0,:,:]:
	    score = float(detection[2])
	    if score > 0.75:
	        left = detection[3] * cols
	        top = detection[4] * rows
	        right = detection[5] * cols
	        bottom = detection[6] * rows
	        cv2.rectangle(img, (int(left)-50, int(top)-50), (int(right)+50, int(bottom)+50), (23, 230, 210), thickness=2)
	cv2.imshow('img', img)
	cv2.waitKey(1)
	if cv2.waitKey(1) == ord('q'):
		break

# Clean up
video.release()
cv2.destroyAllWindows()
"

What could be the reason that it eats up so much CPU ? 

Thanks...

**Comment by alalek** [comment]
Why do you expect 5% CPU load?
(in meaning, the CPU uses 5% available power only, and 95% CPU just sleeps without useful work).

```.diff
-cv2.waitKey(1)
+cv2.waitKey(1000)
```

will reduce CPU load, but your app would become non-responsible.

**Comment by pkr97** [comment]
@alalek what is the use of the application? I have a PC with decent configuration. I want the develop the app so that It can run @30 FPS and with 20% CPU. The suggestion you have given is absolutely not acceptable. How can I wait for 1000 ms when I want a FPS of 30 or more?

Or is it a sarcasm?   

If this small piece of code uses 95% then how can I be able to run the complete application that is 10 times bigger in length and processing? Should I use a super computer?

I was expecting some useful and sensible advice and not sarcasm.

Thanks..

**Comment by dkurt** [comment]
@pkr97, Could you please create an application which will use 80% of CPU and measure an efficiency of object detection using OpenCV (in frames per second)? I think it could solve your doubts.

**Comment by pkr97** [comment]
Hi @dkurt , I did not understand what you wanted to convey. 

But this is the problem I'm facing. 

With this small script I have a CPU usage way way higher than any application I have ever developed.

![screenshot from 2018-09-02 09-23-30](https://user-images.githubusercontent.com/15801327/45254784-8fe12580-b39b-11e8-8b96-b19307fb1316.png)

I just want a solution to this problem because this way I cannot use the Tensorflow model for object detection.

I was asking that what can be done with the code or what could be the bug that is making the process so heavy?

Thanks..

**Comment by alalek** [comment]
> I was asking that what can be done with the code?

- change DL model architecture
- reduce frame size

> what could be the bug

Used DL model. There are models that work >1sec per frame on i7 (for example, OpenPose).

If you are sure that there is a bug, then try to add some real evidences: try using original framework (TensorFlow) to inference DL and compare results.
Please note that TensorFlow may use accelerators like CUDA, OpenCL - but you are not enable them in OpenCV code (currently OpenCL on Intel GPU is supported only).

Also I see a lot of Python processes. This is weird and buggy in general. Try to disable "forking" multiprocessing in Python code - use native threading instead. Details: #5150

---
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by dkurt** [comment]
@pkr97, can we close an issue or your problem should be investigated deeper? How much FPS your application runs with `cv::waitKey(1)`? Have you tried to replace it to something like `cv::waitKey(20)`?

**Comment by dkurt** [comment]
Let's close it. @pkr97, feel free to reopen if you still have a problem.
