### ISSUE TITLE
seamlessClone Bug for OpenCV > ver-3.3

### ISSUE THREAD

**Issue by vikasguptaiisc** [opencv/opencv#12496]
OpenCV => 3.3.1

There is a difference in the output of seamlessClone function between OpenCV 3.3 and higher versions. **The output was correct for OpenCV <= 3.3**

Please find below the code used and the results I'm getting.

### Images used: 
![wood-texture.jpg](https://raw.githubusercontent.com/spmallick/learnopencv/master/SeamlessCloning/images/wood-texture.jpg) - wood-texture.jpg

![ticket](https://raw.githubusercontent.com/spmallick/learnopencv/master/SeamlessCloning/images/iloveyouticket.jpg) - iloveyouticket.jpg

### Code:

```python
  im = cv2.imread("wood-texture.jpg")
  obj= cv2.imread("iloveyouticket.jpg")
  # Create an all white mask
  mask = 255 * np.ones(obj.shape, obj.dtype)

  # The location of the center of the src in the dst
  width, height, channels = im.shape
  center = (int(height/2), int(width/2))

  # Seamlessly clone src into dst using two different methods
  normalClone = cv2.seamlessClone(obj, im, mask, center, cv2.NORMAL_CLONE)
  mixedClone = cv2.seamlessClone(obj, im, mask, center, cv2.MIXED_CLONE)

  cv2.imwrite("opencv-normal-clone-example.jpg", normalClone)
  cv2.imwrite("opencv-mixed-clone-example.jpg", mixedClone)

```

### Results for OpenCV <= 3.3
![](https://files.fm/thumb_show.php?i=pwp542fz) -- Normal Clone

![](https://files.fm/thumb_show.php?i=6fcsns5n) -- Mixed Clone
### Results for OpenCV > 3.3

![](https://files.fm/thumb_show.php?i=uez2x4kv) -- Normal Clone

![](https://files.fm/thumb_show.php?i=duzffp4c) -- Mixed Clone

**Comment by LaurentBerger** [comment]
@vikasguptaiisc There is some black pixels in patch if I remove it there is no problem
![iloveyouticket](https://user-images.githubusercontent.com/3591626/45410149-55180f80-b671-11e8-90bd-3430df4c32e8.jpg)

Can you check again that you can reproduce bug with opencv 3.4 and not with 3.3?

There is some change in imread in 3.4.x libjpegturbo is used now. Can you try with png image ?

**Comment by vikasguptaiisc** [comment]
The result is ok with the new image you shared. But the result with < 3.3 was much better.

![opencv-normal-clone-example](https://user-images.githubusercontent.com/7848248/45411034-d3d07500-b690-11e8-86b1-2d819700ed8d.jpg)
Normal Clone

![opencv-mixed-clone-example](https://user-images.githubusercontent.com/7848248/45411033-d337de80-b690-11e8-9dda-75c87d9b28e8.jpg)
Mixed Clone

I still wonder why the borders were not causing any issues in the lower version.

**Comment by vikasguptaiisc** [comment]
changing it to png gives the same output with the borders.

**Comment by LaurentBerger** [comment]
@vikasguptaiisc Do you mean there is no bug with PNG format?

**Comment by vikasguptaiisc** [comment]
I meant there is no difference in the output for jpg and png format

**Comment by sturkmen72** [comment]
let me try to fix the problem.

**Comment by vikasguptaiisc** [comment]
The version I was talking about is 3.3.0. So the discrepancy is between 3.3.0 an 3.3.1 onwards

**Comment by sturkmen72** [comment]
@LaurentBerger do you have time to try proposed solution in #12512

**Comment by LaurentBerger** [comment]
![image](https://user-images.githubusercontent.com/3591626/45534591-f6cb6800-b7fb-11e8-9b86-7a22e98d547c.png)
ok it works
