### ISSUE TITLE
Problem of making my own model and importing it to opencv

### ISSUE THREAD

**Issue by a41888936** [opencv/opencv#12491]
I tried to my own EAST(An Efficient and Accurate Scene Text Detector) model and import it to opencv

There are some already trained EAST model (https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py)

The model above is works well.

To make my own frozen graph, I add my code in EAST repo(https://github.com/argman/EAST/blob/master/eval.py#L148)

`output_graph = "frozen_model.pb"`

`output_graph_def = tf.graph_util.convert_variables_to_constants(`
`    sess, `
`    tf.get_default_graph().as_graph_def(), `
`    ["feature_fusion/Conv_7/Sigmoid", "feature_fusion/concat_3"])`

`with tf.gfile.GFile(output_graph, "wb") as f:`
`     f.write(output_graph_def.SerializeToString())`

Like this I made my own frozen graph. But when I import  my own model to opencv 

Error occur like this:

Traceback (most recent call last):

File "text_detection_video.py", line 159, in <module>

(scores, geometry) = net.forward(layerNames)

cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/dnn.cpp:401: error: (-2:Unspecified error) Can't create layer "feature_fusion/truediv" of type "RealDiv" in function 'getLayerInstance'

Codes importing my own model to opencv Like this
(https://www.pyimagesearch.com/2018/08/20/opencv-text-detection-east-text-detector/)

**Comment by dkurt** [comment]
@a41888936, may I ask you to save a graph modifying the following lines:
1. model.py:
```python
images = mean_image_subtraction(images)
```
to
```python
# images = mean_image_subtraction(images)
```

2. model.py:
```python
c1_1 = slim.conv2d(tf.concat([g[i-1], f[i]], axis=-1), num_outputs[i], 1)
```
to
```python
c1_1 = slim.conv2d(tf.concat([g[i-1], f[i]], axis=3), num_outputs[i], 1)
```

3. model.py:
```python
angle_map = (slim.conv2d(g[3], 1, 1, activation_fn=tf.nn.sigmoid, normalizer_fn=None) - 0.5) * np.pi/2 # angle is between [-45, 45]
F_geometry = tf.concat([geo_map, angle_map], axis=-1)
```
to
```python
pi2 = 0.5 * np.pi
angle_map = (slim.conv2d(g[3], 1, 1, activation_fn=tf.nn.sigmoid, normalizer_fn=None) - 0.5) * pi2 # angle is between [-45, 45]
F_geometry = tf.concat([geo_map, angle_map], axis=3)
```

**Comment by sushilmax93** [comment]
hey @a41888936 can i have you frozen binary module??

**Comment by ccnankai** [comment]
hi, @dkurt   
I used the following code to generate the .pb file, 

**import tensorflow as tf
import os
from tensorflow.python.tools import freeze_graph

import model
model_path  = ""
def main():
    tf.reset_default_graph()

    input_node = tf.placeholder(tf.float32, shape=(320, 320, 3)) 
    input_node = tf.expand_dims(input_node, 0)
    flow,b = model.model(input_node)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, model_path)
        tf.train.write_graph(sess.graph_def, 'output_model/pb_model', 'model.pb')

        freeze_graph.freeze_graph('output_model/pb_model/model.pb', '', False, model_path, "feature_fusion/Conv_7/Sigmoid,feature_fusion/concat_3",'save/restore_all', 'save/Const:0', 'output_model/pb_model/frozen_model.pb', False, "")

if __name__ == '__main__':
    main()**

but the following error occurred during the run.  I don't know much about tensorflow. which step leads to this error.
**terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-alpha) /home/swd/soft/opencv/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1380: error: (-215:Assertion failed) scaleMat.type() == CV_32FC1 in function 'populateNet'**

**Comment by a41888936** [comment]
@caoyangcr7 No just  commented

**Comment by ccnankai** [comment]
@dkurt 
@a41888936   
Thank you very much

**Comment by eborovenskiy** [comment]
Hello. I've solved this error error: (-215:Assertion failed) scaleMat.type() == CV_32FC1 in function 'populateNet' by replace 
up8 = UpSampling2D(size=(2, 2), interpolation='bilinear')(conv7)
to
up8 = UpSampling2D(size=(2, 2))(conv7)
It looks like my opencv(version 3.4.6) is not supported bilinear interpolatin in UpSampling2D layer.

**Comment by jayjiyani** [comment]
@dkurt, I got this error
 net = cv2.dnn.readNetFromTensorflow('yolov3_coco3_try.pb')
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6uw63ony\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1564: error: (-215:Assertion
 failed) scaleMat.type() == CV_32FC1 in function 'cv::dnn::dnn4_v20201117::`anonymous-namespace'::TFImporter::populateNet'.

I want to implement yolo in opencv with .pb file but  I got this error. And I dont have also upsamplin2D stuff in my code. I generated .pb file from this repo https://github.com/YunYang1994/tensorflow-yolov3

Can you please help me to solve this out ASAP??
