### ISSUE TITLE
[Linux] [patch]  Absolute zoom with Logitech Webcams (C920, C922, Brio 4K stream edition)

### ISSUE THREAD

**Issue by ebachard** [opencv/opencv#12498]
Hello,

I wanted to use the hardware zoom from my logitech webcams, to make it work in my own software (see https://github.com/ebachard/miniDart on my repo). And it was broken ... so I investigated, and I finally found a way to make it work on Linux only for the moment (I'll give it a try on Windows later).

Since I didn't want to create a fork, and PR, a simple patch is attached (under.txt extension name, since github is stupid and does not accept .diff directly),  and you can consider the sources under **MIT or BSD license** if you are interested (don't hesitate to ask me if you need another license).

Not tested with master, but maybe it should apply without too much of problems.

The fix is tested successfull with : 
- **Logitech Brio 4K** (zoom from 100 to 500), 
- **Logitech C922** (zoom from 100 to 200 only),
- **Logitech C920** (zoom from 100 to 200 only).
 
**It does not work with Microsoft LifeCam 3000**. But maybe the feature is simply missing in this webcam.

Important information :

OS : Linux (Intel i7 x86_64, 16GB RAM + SSD, LinuxMint 18.3)
OpenCV version :  3.4.0  (tar.gz from releases), compiled by myself (g++-7.1.0 )

CMake command line to make the build :
````
cmake  -DCMAKE_INSTALL_PREFIX=/usr/local  -DBUILD_SHARED_LIBS=YES -DBUILD_EXAMPLES=OFF  -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.0/modules/  -DBUILD_NEW_PYTHON_SUPPORT=ON  -DWITH_TBB=OFF  -DWITH_V4L=ON  -DWITH_QT=OFF  -DWITH_OPENGL=ON  -DHAVE_FFMPEG_RESAMPLE=YES -DHAVE_GTK3=NO ..
````
IMPORTANT : **HAVE_VIDEOIO is unset** (but libopencv_videoio.3.4.0 is built ? ), so only cap_libv4l.cpp is concerned in the diff (not cap_v4l2.cpp e.g.).

The patch : 

[absolute_zoom_linux_ericb.diff.txt](https://github.com/opencv/opencv/files/2370847/absolute_zoom_linux_ericb.diff.txt)

Last but not least, the patch contains:

````
static double icvGetZoomLimitsCAM_V4L (CvCaptureCAM_V4L* capture,
+                                     int property_id, int aValue )
````
As you can see, it is not complete and a part is still missing (the idea is to retrieve min/max from the webcam in runtime, and we need a getter() for that)

Thanks in advance for any feedback, your comments and/or your suggestions to improve the changes ... just in case.

TODO : windows version (maybe it works already ... somebody knows ?)

**EDIT : answering to myself. After some tests, it works perfectly on Windows :-)  (exactly the same behavior than the one seen on Linux for all the webcams mentioned above)**

**Comment by ebachard** [comment]
Edit : changed the license, because I wrongly thought OpenCV was using MIT license.

Now : choose one between MIT and BSD. Should work ...

**Comment by ebachard** [comment]
Going further with this issue.

In meantime, I fixed Pan + Tilt and Zoom the same way.

Tests in progress : 
- works very well on Linux
- zoom only tested on Windows, but other properties should work out of the box (sorry, no windows close to me at the moment)

Just don't forget to provide a clean initialization for all parameters, to avoid putting the webcam in some undefined state.

**The full diff is available on my repo, branch 3.4 (NOT MASTER)**

Please have a look at : https://github.com/ebachard/opencv/tree/3.4 if you want to test and provide feedback. All the code is provided under the same license : MIT or BSD (up to you)

Still missing: 
- a complete getter() to return min and max values being visible from VideoCapture instance, e.g. to automagicaly use the limits linked to the current used device.
- code cleanup (maybe use an enum instead of #defines, and so on)

Any comment is very welcome.

**Comment by mshabunin** [comment]
@ebachard , feel free to provide pull request.

Please, note that `cap_libv4l` is less common backend which needs additional development package installed (_lib4l-dev_ in Ubuntu), while `cap_v4l` relies on kernel headers available on most systems (I think). For example, there is only _v4l_ backend on my machine and on our CI machines:
```
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
```
See #4563 and #6859 for more details.

**Comment by ebachard** [comment]
@mshabunin 

Thanks a lot for your answer and the links (I'll check them asap), and apologies for the delay.

To answer you: 
- you are right : looks like I'm not using v4l2 as expected, and I'll have to investigate (my idea was to use the most universal solution.
- I didn't create a PR yet, because some code is missing : if I'm not too wrong, we need a getter() in VideoCpature interface, to retrieve min / max values, and I only partially solved the issue. Once done, I'll probably create a PR, just for the people who will need the diff (not sure integrate that in 3.4 is a good idea imho).

Now, to be more precise, I remember I used both in my CMakefile.txt. If I understand corectly what you mean, I got WITH_V4L and WITH_LIBV4L set to ON (please correct me if I'm wrong. 

What I propose, as TODO for this issue : 
- read #4563 and #6859 to understand what happens
- try to rebuild a full opencv set, without cap_libv4l (  WITH_LIBV4L = OFF  IIRC, right ?)
- check whether other changes are needed to use Pan + Tilt + Zoom when available using v4l2 only.

Last but not least, just in case you are interested, I created a repo (my_libuvc). Everything is around UVC 1.5. on Linux (only the beginning, but seems to work).

For further information, please have a look at : https://github.com/ebachard/my_libuvc/tree/master/documentation/uvc1.5

Last but not least : please be patient, days are 24h only ;-)

To be continued

**Comment by ebachard** [comment]
Just for say I tested with OpenCV 3.4.5 + contribs 3.4.5 + options very close to the previous one

Lot of issues:  
- the webcam is broken /dev/video0 on Linux no longer works (never broken before), likely, /dev/video1 is found, but I wonder who implemented such behaviour ?
- more unstabilities
- the zoom, pan and tilt are broken 
- CMakeLists.txt options are strange : with the same script, with the same -D... ,  it was very difficult to use OpenGL (tested on Linux mint 18.3 and Ubuntu 18.04), and the 3.4.5 build was less stable than the 3.4.0 (why oh why ?)

Looks like someone removed (broke ?) a lot of things in videoio, and I didn't find the time to investigate further. Waiting, I decided to keep the 3.4.0 for a long while.

Congratulation for the one who broke something working very well. Of course, you can close the issue and forget my patch, completely useless now.

**Comment by radimspetlik** [comment]
Hi @ebachard, my question is not related to this issue. I work with the BRIO camera in Linux with v4l. The BRIO cam seems to randomly set a "field of view" parameter (which is something that is controlled in mac & windows through the Logitech Capture software and is either 65, 78 and 90 degrees). Since you tried to get the zoom feature to work, is there any chance that you know how to set (or access) the FOV property in Linux? I tried a brute-force search after the V4L2_CID_PRIVATE_BASE parameter id, but I found nothing... Thanks...

**Comment by mshabunin** [comment]
@ebachard , the `/dev/video1` is created by OS, OpenCV does not affect it. I guess you are using auto backend detection in VideoCapture and in later versions GStreamer backend priority has been increased and it has been enabled by default in the build. So, probably, you are using wrong backend. You can choose backend explicitly by the second constructor argument: `VideoCapture(0, CAP_V4L2)`.
OpenGL problem can be related to your flags: usually `HAVE_` flags should not be set from command line. All dependencies are controlled by `WITH_` options. GTK 3 and V4L2 are enabled by default in OpenCV 4, so you don't need to set anything to enable them. Also, Qt, TBB are disabled by default, so you don't need to turn them off explicitly.

@radimspetlik , I think it is controlled by zoom parameter:
```
zoom_absolute 0x009a090d (int)    : min=100 max=500 step=1 default=100 value=100
```

**Comment by mshabunin** [comment]
BTW, I figured out that Zoom, Tilt and Pan already work in V4L2 backend. Added following processing to the `samples/cpp/videocapture_camera.cpp` sample and it worked (**with CAP_V4L2 backend**):
```.cpp
auto tune = [&](int prop, double step, const std::string &name)
{
    const double val = capture.get(prop);
    if (!capture.set(prop, val + step))
        cout << name << ": set failed! (was " << val << ")" << endl;
    else
        cout << name << ": " << val << " -> " << capture.get(prop) << endl;
};

switch (key)
{
case ']': tune(CAP_PROP_ZOOM, 10, "Zoom"); break;
case '[': tune(CAP_PROP_ZOOM, -10, "Zoom"); break;
case 'w': tune(CAP_PROP_TILT, 3600, "Tilt"); break;
case 's': tune(CAP_PROP_TILT, -3600, "Tilt"); break;
case 'a': tune(CAP_PROP_PAN, -3600, "Pan"); break;
case 'd': tune(CAP_PROP_PAN, 3600, "Pan"); break;
}
```
Since CAP_LIBV4L2 is deprecated and has been removed in 4.0, I guess this patch is not relevant anymore.

**Comment by radimspetlik** [comment]
@ebachard Thanks for a hint. However, the zoom parameter does not affect this setting... It is some kind of "internal cropping" parameter or what...

**Comment by matanster** [comment]
@radimspetlik I just wonder if you have found a solution for controlling the field of view (viewing angle) setting via any utility or code. I could not spot a way to control it via e.g. the v4l2 linux configuration utility.

**Comment by radimspetlik** [comment]
@matanster Did not. I also contacted Logitech support. However, this seems to be a problem of 0.001% of customers, so they simply don't care.

**Comment by Anton3** [comment]
> @matanster Did not. I also contacted Logitech support. However, this seems to be a problem of 0.001% of customers, so they simply don't care.

I worked around the problem by tweaking the settings on a different PC with Windows. All the settings are stored in the webcam.

**Comment by argoncloud** [comment]
@Anton3 which (of the many) Logitech settings programs did you use to save the settings in the webcam? I tried Logitech Camera Settings, but the angle setting didn't move around with the camera as far as I could see. Was it something like Logitech Capture or LogiTune?

**Comment by mghadam** [comment]
> Hi @ebachard, my question is not related to this issue. I work with the BRIO camera in Linux with v4l. The BRIO cam seems to randomly set a "field of view" parameter (which is something that is controlled in mac & windows through the Logitech Capture software and is either 65, 78, or 90 degrees). Since you tried to get the zoom feature to work, is there any chance that you know how to set (or access) the FOV property in Linux? I tried a brute-force search after the V4L2_CID_PRIVATE_BASE parameter id, but I found nothing... Thanks...

I have the same issue on linux and libv4l v1.20 , there is no option to change the FOV propery in v4l2-utils. 

On windows with Logitech Capture, I can switch between these three FOVs, however on Linux there is no such option in --list-ctrls .
