### ISSUE TITLE
stitching/src/precomp.hpp includes imgproc's gcgraph.hpp breaking module boundary 

### ISSUE THREAD

**Issue by nikhedonia** [opencv/opencv#12500]
In order to optimize, modularize(for packaging) and create a real port of OpenCV to Skylark based build systems (Buck/Bazel) I stumbled across this issue:

`stitching/precomp.hpp` includes `imgproc/src/gcgraph.hpp`.

This is suboptimal because:
- it makes two modules inseparable on a filesystem level and makes packaging individual modules of OpenCV impossible (and incompatible with eg. BuckBuild).
- from a software engineering perspective `stitching` uses an implementation detail of `imgproc`.

GCGraph is used in `modules/imgproc/src/grabcut.cpp` and `modules/stitching/src/seam_finders.cpp`.
Wouldn't it be more appropriate to move GCGraph into a separate module or move it to `modules/imgproc/include/opencv2/imgproc/detail` ?

**Comment by nikhedonia** [comment]
related #12445

**Comment by alalek** [comment]
> packaging individual modules

Current level of packaging separation is opencv / opencv_contrib repository.

But even this doesn't work (check Ubuntu's `opencv_modules.hpp` - it contains all modules event if there is no opencv_contrib installed).

Moving some code into "include" folder requires some minimal quality of code.
It should be refactored (`create()` method is misnamed) and added tests.

Also there are other cases similar to this (for example, xfeatures2d tests reuses code from features2d tests).

Currently we don't want supporting more detailed separation (at least on file-system level). Separation on build-level works fine (it allows to disable/enable modules).
So current repository level separation is enough for us.

**Comment by njlr** [comment]
I see this as a code-quality issue. There is a file in the `src` folder of `imageproc` that is being used as if it is a public header by the `stitching` module. If the file is used by another module then it is part of that module's API; hence it belongs in `include`. To discourage direct use, `include/detail` is appropriate. 

This is already being done for `imgproc/detail/distortion_model.hpp`, so this change simply makes things consistent.

**Comment by nikhedonia** [comment]
> Current level of packaging separation is opencv / opencv_contrib repository.

The level of granularity is not sufficient for some use cases.

> But even this doesn't work

I would like to improve on that and this is the first step.

> Also there are other cases similar to this (for example, xfeatures2d tests reuses code from features2d tests).

This case is different.
`xfeature2d`'s `precomp.hpp` does not include a relative path that relies on the filesystem structure as `imgproc` does.

Furthermore it's even worse. Because  `GCGraph.hpp` is not public, it has been copyied into [xphoto](https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/src/gcgraph.hpp).
