### ISSUE TITLE
Opencv failed to build on x86 when build with MSVC

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#12506]
Hi All,

OpenCV failed to build on x86 when build with MSVC on Windows with VS2017 Update 7. This issue can be reproduced from the master revision commit https://github.com/opencv/opencv/commit/b01f63835eae6f4b6ba2842b12f8ddf419695145. This should be OpenCV source issue,Could you please help take a look at this? Thank you!

You can repro this issue as the steps below:
1.git clone https://github.com/opencv/opencv D:\OpenCV\src
2.git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
3.Open a VS 2017 x86 prompt and browse to D:\OpenCV
4.mkdir build_x86 && pushd build_x86
5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6.msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true

The whole log file please see attachment.
[log_x86_build.log](https://github.com/opencv/opencv/files/2373538/log_x86_build.log)

Error info:
303>opencv_core400.lib(persistence_cpp.obj) : error LNK2019: unresolved external symbol "public: void __thiscall cv::DefaultDeleter<struct CvFileStorage>::operator()(struct CvFileStorage *)const " (??R?$DefaultDeleter@UCvFileStorage@@@cv@@QBEXPAUCvFileStorage@@@Z) referenced in function __catch$??$_Setpd@PAUCvFileStorage@@U?$DefaultDeleter@UCvFileStorage@@@cv@@@?$shared_ptr@UCvFileStorage@@@std@@AAEXPAUCvFileStorage@@U?$DefaultDeleter@UCvFileStorage@@@cv@@@Z$0 [D:\OpenCV\build_x86\apps\version\opencv_version.vcxproj]
303>opencv_core400.lib(persistence_cpp.obj) : error LNK2019: unresolved external symbol "public: void __thiscall cv::DefaultDeleter<struct CvSparseMat>::operator()(struct CvSparseMat *)const " (??R?$DefaultDeleter@UCvSparseMat@@@cv@@QBEXPAUCvSparseMat@@@Z) referenced in function __catch$??$_Setpd@PAUCvSparseMat@@U?$DefaultDeleter@UCvSparseMat@@@cv@@@?$shared_ptr@UCvSparseMat@@@std@@AAEXPAUCvSparseMat@@U?$DefaultDeleter@UCvSparseMat@@@cv@@@Z$0 [D:\OpenCV\build_x86\apps\version\opencv_version.vcxproj]
303>D:\OpenCV\build_x86\bin\Release\opencv_version.exe : fatal error LNK1120: 2 unresolved externals [D:\OpenCV\build_x86\apps\version\opencv_version.vcxproj]

**Comment by LaurentBerger** [comment]
BUILD_SHARED_LIBS=OFF : duplicate issue #12489 ?

**Comment by spacelg** [comment]
Opencv build pass on the master revision commit a024593, the issue can close.
