### ISSUE TITLE
Error with dnn.readNetFromTensorFlow in python for opencv example - mobilenet models

### ISSUE THREAD

**Issue by TBondat** [opencv/opencv#12518]
##### System information (version)

- OpenCV => 3.4.1.15
- Operating System / Platform => Windows 7 64 Bit
- TensorFlow=>  1.8

##### Detailed description
I try to import tensorflow model example mobilenet v1 or v2 (same problem) as it is done in the example in the doc https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API using dnn.readNetFromTensorflow: 
`cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'graph_mobile_v1.pbtxt')`
I took the model file and corresponding config graph .pbtxt file and run the provided command lines example on the same page to import TF model. I didn't tune the models, it is exactly the base model.

But i get the following error Traceback:
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1582: error: (-2) Unknown layer type Sub in op Preprocessor/sub in function cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet

I already use tensorflow models for predictions outside opencv. i don't have any errors. In the tuto page, the first script where we just use TF without opencv for prediction worked well too.
I used also successfully examples with readNetFromCaffe.

##### Steps to reproduce
Just follow tutorial page to use a TF model.
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

Thanks for the help.

**Comment by dkurt** [comment]
@TBondat, use mentioned scripts [from the same version of library](https://github.com/opencv/opencv/blob/3.4.1/samples/dnn/tf_text_graph_ssd.py) which perform network deployment. It looks like you tried to use a script from the latest state of 3.4 or master branch but your OpenCV is only 3.4.1.

**Comment by TBondat** [comment]
oh ok, you are right, current opencv release is already 3.4.3. I thought i was up-to-date already. After an upgrade of the lib, it worked perfectly. Thanks a lot!

**Comment by lalawatchitra30** [comment]
Hii TBondat- 
Did u update Opencv library to get out of this error?
How did u update Opencv???
