### ISSUE TITLE
build error with static opencv lib build for ARM

### ISSUE THREAD

**Issue by heweiSing** [opencv/opencv#12517]
Dear,

I have linked all the opencv static libs on ARM core:

OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_imgproc.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_imgcodecs.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_core.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libpng.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libzlib.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_genericio.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_objdetect.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_highgui.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_ml.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_shape.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_features2d.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_flann.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_photo.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_stitching.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_superres.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_calib3d.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_ts.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_video.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_videoio.a
OPENCV_LIBS +=  $(OpenCV_PREBUILD_PATH)/libs_linux/libopencv_videostab.a

Then but got error when using the object detection API:
cvHaarDetectObjects
libs_linux/libopencv_objdetect.a(haar.cpp.o): In function `cvHaarDetectObjectsForROC(void const*, CvHaarClassifierCascade*, CvMemStorage*, std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, double, int, int, CvSize, CvSize, bool)':
haar.cpp:(.text._Z25cvHaarDetectObjectsForROCPKvP23CvHaarClassifierCascadeP12CvMemStorageRSt6vectorIiSaIiEERS5_IdSaIdEEdii6CvSizeSC_b+0x4ca): undefined reference to `cvResize'
haar.cpp:(.text._Z25cvHaarDetectObjectsForROCPKvP23CvHaarClassifierCascadeP12CvMemStorageRSt6vectorIiSaIiEERS5_IdSaIdEEdii6CvSizeSC_b+0x1506): undefined reference to `cvCanny'
/home/cheepeng/PROCESSOR_SDK_VISION_03_04_00_00/ti_components/open_compute/opencv/opencv-3.1.0/libs_linux/libopencv_objdetect.a(cascadedetect.cpp.o): In function `cv::BaseCascadeClassifier::~BaseCascadeClassifier()':
cascadedetect.cpp:(.text._ZN2cv21BaseCascadeClassifierD2Ev+0x14): undefined reference to `cv::Algorithm::~Algorithm()'
/home/cheepeng/PROCESSOR_SDK_VISION_03_04_00_00/ti_components/open_compute/opencv/opencv-3.1.0/libs_linux/libopencv_objdetect.a(cascadedetect.cpp.o): In function `cv::CascadeClassifierImpl::CascadeClassifierImpl()':
cascadedetect.cpp:(.text._ZN2cv21CascadeClassifierImplC2Ev+0x26): undefined reference to `cv::Algorithm::Algorithm()'

Any suggestion?

Thanks and best regards

**Comment by alalek** [comment]
Build and usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

1. Lost symbol is here:
> $ nm -g OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_imgproc.a | grep cvResize
00000001 T cvResize

No idea what is **cvHaarDetectObjectsForROC**.

2. It is important to **preserve order** of static libraries for Linux-based tools.

3. No idea where you get this approach, but existed OpenCV Andoid samples/tests use OpenCV.mk from SDK ([check Android.mk file in samples](https://github.com/opencv/opencv/blob/3.4.3/samples/android/face-detection/jni/Android.mk)).
Consider using official recipes for building and using of OpenCV. We really have not spare time to dig into custom scripts that just don't work.

4. Mentioned OpenCV version had been released ~3 years ago:
> opencv-3.1.0

We don't support old releases. Use the latest from 3.4 branch.
