### ISSUE TITLE
Dnn.BlobFromImage returns (-1 * -1) Mat

### ISSUE THREAD

**Issue by peterbence3** [opencv/opencv#12520]
I'm using **OpenCV** 3.4.3 in java in order to import and use a convolutional neural network built with **Caffe**. However the function **BlobFromImage** is returning an empty **Mat**, and i'm getting the following error when calling the **net.forward()**:

**Code:**

```
 import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.Size;
import org.opencv.dnn.Dnn;
import org.opencv.dnn.Net;
import org.opencv.imgcodecs.Imgcodecs;

public class OpenCVTests {

	public static void main(String[] args) {

		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

		System.out.println("Loading caffe model...");
		Net net = Dnn.readNetFromCaffe("C:\\Program Files\\Docker\\volumes\\vol1\\model.prototxt");

		Mat image = Imgcodecs.imread("C:\\Users\\Administrator\\Desktop\\cat.jpg");
		System.out.println(image);

		Mat blob = Dnn.blobFromImage(image, 1.0f, new Size(224, 224));
		System.out.println(blob);

		net.setInput(blob);
		Mat result = net.forward();
		System.out.println(result);

	}
}
```

**Output:**

```
Loading caffe model...
Mat [ 224*224*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0x19659e40, dataAddr=0x19678ac0 ]
Mat [ -1*-1*CV_32FC1, isCont=true, isSubmat=false, nativeObj=0x1965a070, dataAddr=0x197a3100 ]
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) Z:\Karbala\build tools\opencv-3.4.3\modules\dnn\src\layers\convolution_layer.cpp:233: error: (-215:Assertion failed) blobs.size() != 0 in function 'cv::dnn::ConvolutionLayerImpl::getMemoryShapes'
]
	at org.opencv.dnn.Net.forward_1(Native Method)
	at org.opencv.dnn.Net.forward(Net.java:62)
	at test.OpenCVTests.main(OpenCVTests.java:31)
```

**Prototxt:**

[model.prototxt](https://www.dropbox.com/s/36vip19fnei16ho/Get%20Started%20with%20Dropbox%20Paper.url?dl=0)

Any help would be highly appreciated, thanks in advance!

**Comment by alalek** [comment]
`blobFromImage()` returns 4 dimensional Mat.
Java dumper supports 2D Mat only.

**Comment by dkurt** [comment]
@peterbence3, https://github.com/opencv/opencv/issues/10802

**Comment by peterbence3** [comment]
@alalek than this won't work in java?

**Comment by peterbence3** [comment]
@dkurt i followed the issue #10802 but it ended up by a request to post the question on `http://answers.opencv.org/` where i couldn't find the question there, do you have a link for it please, thanks!!

**Comment by epinnock** [comment]
Hi I'm having issues with running the example at https://docs.opencv.org/3.4/d0/d6c/tutorial_dnn_android.html

and I'm getting this error:

2019-05-26 19:36:02.333 23779-23862/com.example.dnntutorial E/cv::error(): OpenCV(3.4.6) Error: Unspecified error (> Blob depth should be CV_32F or CV_8U:
    >     'ddepth == CV_32F || ddepth == CV_8U'
    > where
    >     'ddepth' is 62 (CV_64FC8)
    ) in void cv::dnn::experimental_dnn_34_v11::blobFromImages(cv::InputArrayOfArrays, cv::OutputArray, double, cv::Size, const Scalar&, bool, bool, int), file /build/3_4_pack-android/opencv/modules/dnn/src/dnn.cpp, line 240
2019-05-26 19:36:02.336 23779-23862/com.example.dnntutorial E/org.opencv.dnn: dnn::blobFromImage_10() caught cv::Exception: OpenCV(3.4.6) /build/3_4_pack-android/opencv/modules/dnn/src/dnn.cpp:240: error: (-2:Unspecified error) in function 'void cv::dnn::experimental_dnn_34_v11::blobFromImages(cv::InputArrayOfArrays, cv::OutputArray, double, cv::Size, const Scalar&, bool, bool, int)'
    > Blob depth should be CV_32F or CV_8U:
    >     'ddepth == CV_32F || ddepth == CV_8U'
    > where
    >     'ddepth' is 62 (CV_64FC8)
2019-05-26 19:36:02.343 23779-23862/com.example.dnntutorial E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.dnntutorial, PID: 23779
    CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.6) /build/3_4_pack-android/opencv/modules/dnn/src/dnn.cpp:240: error: (-2:Unspecified error) in function 'void cv::dnn::experimental_dnn_34_v11::blobFromImages(cv::InputArrayOfArrays, cv::OutputArray, double, cv::Size, const Scalar&, bool, bool, int)'
    > Blob depth should be CV_32F or CV_8U:
    >     'ddepth == CV_32F || ddepth == CV_8U'
    > where
    >     'ddepth' is 62 (CV_64FC8)
    ]
        at org.opencv.dnn.Dnn.blobFromImage_0(Native Method)
        at org.opencv.dnn.Dnn.blobFromImage(Dnn.java:38)
        at com.example.dnntutorial.MainActivity.onCameraFrame(MainActivity.java:76)
        at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:392)
        at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:373)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Cogito2012** [comment]
@peterbence3 @alalek @dkurt 
I have the same issue! The problem of method call Dnn.blobFromImage() should not be related with  the missing `.caffemodel` weight file since the weight file is not used here. But the problem that returns empty blob still exists.

Take the following as an example:

` Java
import org.opencv.core.*;
import org.opencv.dnn.*;
import org.opencv.imgcodecs.Imgcodecs;

public class OpenCVTests {

	public static void main(String[] args) {

		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

		Mat image = Imgcodecs.imread("C:\\Users\\Administrator\\Desktop\\cat.jpg");
		System.out.println(image);

		Mat blob = Dnn.blobFromImage(image, 1.0f, new Size(224, 224));
		System.out.println(blob);
	}
}`

The printed results:

`
Mat [ 1080*1616*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0xa8dbe0, dataAddr=0x1748b080 ]
Mat [ -1*-1*CV_32FC1, isCont=true, isSubmat=false, nativeObj=0xaa2fd0, dataAddr=0x18d93080 ]
`

I don't know why this problem occurs...

**Comment by alalek** [comment]
There is no problem with `blobFromImage()`.

Problem is on this line: `System.out.println(blob);`.

[Again](https://github.com/opencv/opencv/issues/12520#issuecomment-420939965), `toString()` supports 2D matrices only. `blobFromImage()` returns 4D matrix (there is no definition for rows/cols values, so these values are -1).

**Comment by Cogito2012** [comment]
@alalek 
Thanks! The problem is exactly what you explained.

I have just figured out it...

**Comment by epinnock** [comment]
@Cogito2012 would you be able to post a gist for getting the dnn working on android?

**Comment by Cogito2012** [comment]
@epinnock 
I am a beginner to use the dnn on android. And I am also struggling to get this working since there are barely internet resources for this task.  

My current problem is that I don't know how to parse the inference results from the net.forward().

```Java
String protofile = "../weights/deploy.prototxt";
String modelfile = "../weights/res10_300x300_ssd_iter_140000_fp16.caffemodel";
Net net = Dnn.readNetFromCaffe(protofile, modelfile);

Mat blob = Dnn.blobFromImage(padded_image, 1.0, new Size(300, 300), new Scalar(104.0, 177.0, 123.0));
net.setInput(blob);
Mat detections = net.forward();

// Then, how can I get the detection results?? 
// I printed the size of the detections as the followings:
System.out.println(detections.size(0));  // 1
System.out.println(detections.size(1));  // 1
System.out.println(detections.size(2));  // 123 
System.out.println(detections.size(3));  // 7

// But what's the meaning of the result detections with size 1x1x123x7?

// I use the get() method to transform the Mat into Array like this:
float[] result = new float[detections.size(2)*detections.size(3)];
detections.get(0, 0, result);
System.out.println(Arrays.toString(result));

// But the printed results are all zero values.


```

Could you help me to this end?

**Comment by epinnock** [comment]
Here I actually began working on this problem a few weeks ago, after
speaking to one of the maintaining developers on the project it looks like
our best choice is to use the jni and write the code in c++, I also found
an example that uses the android java sdk. I have not tested it but, you
can give it a try

https://github.com/LiuXTao/opencv_dnn_android

**Comment by Cogito2012** [comment]
@epinnock 
Thank you for this information. I just found the javacv project [(https://github.com/bytedeco/javacv)](https://github.com/bytedeco/javacv)

I will also have a try with your given example.

**Comment by dkurt** [comment]
@epinnock, @Cogito2012, please use the sample from the documentation as a reference: https://docs.opencv.org/master/d0/d6c/tutorial_dnn_android.html

**Comment by Cogito2012** [comment]
@dkurt 
Great thanks to your valuable reference link! I have successfully parsed the detection results as bounding boxes. 

However, when the number of input images is larger than 1, such as 4 images with blob size (4, 3, 256, 256), the net.forward() seems to still return a tensor with size (1, 1, N, 7). That's to say, the detected bounding boxes are messed up and bounding boxes cannot be assigned to their correct image...

The followings are my problematic case:
```Java
String protofile = "../weights/deploy.prototxt";
String modelfile = "../weights/res10_300x300_ssd_iter_140000_fp16.caffemodel";
Net net = Dnn.readNetFromCaffe(protofile, modelfile);

// Here, we call the blobFromImages() to support for more than 1 image as input.
// The input var all_images is a List<Mat> object, and the output blob has the size (4, 3, 256, 256)
Mat blob = Dnn.blobFromImages(all_images, 1.0, new Size(300, 300), new Scalar(104.0, 177.0, 123.0));
net.setInput(blob);
Mat detections = net.forward();

//Then, how can I parse the detections into bounding boxes for each image?
//The example in the provided link by dkurt use the following method.
detections = detections.reshape(1, (int)detections.total() / 7);  // size=(647, 7)

```
The `reshape` method is definitely problematic here since the number of boxes for each image is not the same.

Is there any way to get this case working?

**Comment by dkurt** [comment]
@Cogito2012, From the specification of DetectionOutput layer (probably we need to move it from [samples](https://github.com/opencv/opencv/blob/132253c9f3c20a2902b3dc9481c45a0f4a71f739/samples/dnn/object_detection.cpp#L332-L334) to the [source code](https://github.com/opencv/opencv/blob/132253c9f3c20a2902b3dc9481c45a0f4a71f739/modules/dnn/include/opencv2/dnn/all_layers.hpp#L559-L563) as @LaurentBerger noted in https://github.com/opencv/opencv/issues/14645), there is `batchId` number which is used to check image id.

**Comment by Cogito2012** [comment]
@dkurt 
That's right. I missed the  `image_id` item which already exists in the reshaped results. When the results are shaped as Nx7, the first column contains the image ID for each box. So the multiple images as input are also supported now. 

Thank you again!

**Comment by pedroteixeira** [comment]
@Cogito2012  Did you find a solution / understand why return of `Dnn.blobFromImage` seems to contain only zeros? 
Experiencing the same output here.
