### ISSUE TITLE
Set brightness failed with OpenCV 3.4.3

### ISSUE THREAD

**Issue by ravi0103** [opencv/opencv#12525]
I just updated the OpenCV to version 3.4.3 and I have a simple program that streams camera. I am setting maximum brightness at the 10th frame. Find below the sample program code

```.cpp
#include "opencv2/opencv.hpp"

using namespace cv;

int main(int, char**)
{
    VideoCapture cap(0); // open the default camera
    if(!cap.isOpened())  // check if we succeeded
        return -1;

        Mat frame;
        int count = 0;
    namedWindow("edges",1);
    for(;;)
    {
        if (count == 10)
            cap.set(CV_CAP_PROP_BRIGHTNESS, 1.0);
        count++;
        cap >> frame; // get a new frame from camera
        imshow("edges", frame);
        if(waitKey(10) >= 0) break;
    }
    // the camera will be deinitialized automatically in VideoCapture destructor
    return 0;
}
```
The program crashes with the following error

> libv4l2: error setting pixformat: Device or resource busy

PS: 
* Earlier I was working with the same code with OpenCV 3.4.1. It seems to be working fine.
* I am streaming Y16 format.

**Comment by alalek** [comment]
Perhaps VideoCapture selects another backend: V4L -> GStreamer.
If you rely on specific backend only (especially if you are using "optional" properties) then you should specify it in VideoCapture constructor.
