### ISSUE TITLE
Feature Request: cv::dnn::readNetFromONNX does not support parsing LSTM layer

### ISSUE THREAD

**Issue by zjchuyp** [opencv/opencv#12533]
##### System information (version)
- OpenCV => Latest 3.4.3
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

 When I load the onnx model containing the LSTM layer using cv::dnn::readNetFromONNX, it will get the "Unhandled exception at 0x76BAC54F in libUse.exe: Microsoft C++ exception: cv::Exception at memory location 0x002EE300." 

##### Steps to reproduce

 The onnx model and code can be downloaded from https://github.com/zjchuyp/ocr.pytorch.

**Comment by cuixing158** [comment]
@zjchuyp  have you solved? I meet same exception

**Comment by dkurt** [comment]
Hi! LSTM from ONNX (also bidirectional one) is now supported: https://github.com/opencv/opencv/pull/16817. Thanks for feature request!
