### ISSUE TITLE
IPP tries to use AVX512VL instructions on a CPU that doesn't support it

### ISSUE THREAD

**Issue by Draghtnod** [opencv/opencv#12536]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Windows 7 / x64
- Compiler => vc15.8.2

##### Detailed description

I compiled with the untouched default setup with

BUILD_IPP_IW=YES
BUILD_WITH_DYNAMIC_IPP=NO
WITH_IPP=YES

giving me 
```
  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (5 files):          + SSSE3 SSE4_1
      SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (6 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (11 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   D:/opencv/build/3rdparty/ippicv/ippicv_win
    Intel IPP IW:                sources (2017.0.3)
              at:                D:/opencv/build/3rdparty/ippicv/ippiw_win
```
Then testing with opencv_test_core i got
```
[ RUN      ] Core_CountNonZero.accuracy
d:\opencv\modules\ts\src\ts.cpp(567): error: Failed

        failure reason: Hardware/OS exception
        test case #-1
        seed: ffffffffffffffff
-----------------------------------
        LOG:
General failure:
        Hardware/OS exception (-4)

-----------------------------------
```
Digging deeper i found out that the exception was caused at count_non_zero.cpp on line 316:
```
            status = CV_INSTRUMENT_FUN_IPP(ippiCountInRange_8u_C1R, (const Ipp8u *)src.ptr(), (int)src.step, size, &count, 0, 0);
```
to be precise within the statically linked code of `ippicvmt.lib` at
```
icv_k0_ownpi_CountInRange_8u_C1R:
[...]
000007FED27422AE  vpxord      ymm18,ymm18,ymm18  
```
vpxord on ymmXX registers requires the AVX512VL extension. My CPU only has AVX512F. 

I have an Intel Core i9 7900X.
Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES, AVX, AVX2, AVX512F, FMA3, TSX

Seems to be a bug in the utilized `ippicv_2017u3_win_intel64_general_20180518.zip`. I don't know how to solve this. There seems to be no newer version or source code available.

##### Steps to reproduce

Try to use IPP with an Intel Core i9 7900X.

**Comment by alalek** [comment]
We have i9-7900X under Linux (not Win7): tests works [well](http://pullrequest.opencv.org/buildbot/builders/3_4-skx-lin64/builds/155) and IPP reports this:
> Intel(R) IPP version: ippIP AVX-512F/CD/BW/DQ/VL (k0) 2017.0.3 (-) Jul 29 2017

Do you use 32-bit builds on Windows? Like issue here: #12532

Could you run OpenCV app (not sample): "opencv_version --hw" and attach output here?

Current workaround:
- force AVX2 IPP via `OPENCV_IPP=AVX2` environment variable

CPU i9-7900X should support AVX512VL, but looks like OS Win7 doesn't (numbers of context registers are larger, so this mode is not enabled via control flags) - so there may be a features detection issue:
- https://en.wikipedia.org/wiki/AVX-512#Instruction_set
- https://en.wikichip.org/wiki/intel/core_i9/i9-7900x#Features


/cc @lupustr3

**Comment by Draghtnod** [comment]
Meanwhile, i found out the same thing. My CPU and Visual Studio 2017 do support AVX512VL, but Windows 7 doesn't. The CPU Features described in your link match my CPU flags, but the required control registers (CR4.OSXSAVE and XCR0[7:5]) are not set by the OS. F$§"# Microsoft! I don't want their tile shaped spyware!

Nevertheless, IPP should check if AVX512 is available before using its instructions.

I used only 64-bit builds yet. The `OPENCV_IPP=AVX2` workaround works fine, thank you.
```
opencv_versiond.exe --hw
3.4.3
OpenCV's HW features list:
    ID=  1 (MMX) -> ON
    ID=  2 (SSE) -> ON
    ID=  3 (SSE2) -> ON
    ID=  4 (SSE3) -> ON
    ID=  5 (SSSE3) -> ON
    ID=  6 (SSE4.1) -> ON
    ID=  7 (SSE4.2) -> ON
    ID=  8 (POPCNT) -> ON
    ID=  9 (FP16) -> ON
    ID= 10 (AVX) -> ON
    ID= 11 (AVX2) -> ON
    ID= 12 (FMA3) -> ON
    ID= 13 (AVX512F) -> N/A
    ID= 14 (AVX512BW) -> N/A
    ID= 15 (AVX512CD) -> N/A
    ID= 16 (AVX512DQ) -> N/A
    ID= 17 (AVX512ER) -> N/A
    ID= 18 (AVX512IFMA) -> N/A
    ID= 19 (AVX512PF) -> N/A
    ID= 20 (AVX512VBMI) -> N/A
    ID= 21 (AVX512VL) -> N/A
    ID=100 (NEON) -> N/A
    ID=200 (VSX) -> N/A
    ID=256 (AVX512-SKX) -> N/A
Total available: 12
```
What a bummer being forced to waste all these registers and instructions..

**Comment by crackwitz** [comment]
what to do?
* add OS detection to CPU capability detection and special-case OSes that won't save those registers?
* modify cmake files to detect some OSes and explicitly disable/limit HW features?

**Comment by alalek** [comment]
IPPICV package has been updated: #16639
If this problem is still actual (Win7 is EOL), then please try latest code from "3.4" or "master" branches.

**Comment by Draghtnod** [comment]
I am not able to test this anymore since i have moved on to Linux on my i9 system. Feel free to close this issue.
