### ISSUE TITLE
Opencv failed to run Core_globbing.accuracy and Core_MeanStdDev/ElemWiseTest.accuracy/0 case with release configuration and debug configuration

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#12532]
Environment:
 Windows Server 2016 + VS2017 Update 5 + opencv master branch latest srouce code

Opencv failed to run Core_MeanStdDev/ElemWiseTest.accuracy/0 case  with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance!

 1.git clone https://github.com/opencv/opencv D:\OpenCV\src
 2.git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
 3.Open a VS 2017 x86 prompt and browse to D:\OpenCV
 4.mkdir build_x86 && pushd build_x86
 5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
 6.msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
7.pushd build_x86\bin\Release
8.opencv_test_core.exe --gtest_filter=Core_MeanStdDev/ElemWiseTest.accuracy/0
  
The whole log file please see attachment.
[log_x86_test_14.log](https://github.com/opencv/opencv/files/2382245/log_x86_test_14.log)

TestErrorMessage:
[==========] 3888 tests from 161 test cases ran. (121995 ms total)
[  PASSED  ] 3887 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Core_MeanStdDev/ElemWiseTest.accuracy/0, where GetParam() = 8-byte object <58-26 16-01 50-E6 1B-01>

**Comment by alalek** [comment]
1.
> Core_globbing.accuracy

Usually this means that there is missing `OPENCV_TEST_DATA_PATH` env variable (must point to `<opencv_extra>/testdata`).

2.
```
[ RUN      ] Core_MeanStdDev/ElemWiseTest.accuracy/0, where GetParam() = 8-byte object <58-26 16-01 50-E6 1B-01>
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] Core_MeanStdDev/ElemWiseTest.accuracy/0, where GetParam() = 8-byte object <58-26 16-01 50-E6 1B-01> (681 ms)
```

Please run tests under debugger and capture stack trace, disassembled code (3-10 instructions) and registers.


We have [**64-bit** Windows static build](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14-static) and don't observe similar errors.
