### ISSUE TITLE
opencv3.4.3-caffe-error

### ISSUE THREAD

**Issue by xiangdeyizhang** [opencv/opencv#12556]
what():  OpenCV(3.4.3) /home/xz/opencv-3.4.3/modules/dnn/src/layers/eltwise_layer.cpp:115: error: (-215:Assertion failed) inputs[0] == inputs[i] in function 'getMemoryShapes'

**Comment by dkurt** [comment]
@xiangdeyizhang, please use http://answers.opencv.org if you faced a usage issue. This is a bug tracker and all the issues should meet appropriate requirements such ways to reproduce.

**Comment by xiangdeyizhang** [comment]
Hi, dkurt ,Thank you for your advice I will submit the question as your guidance

**Comment by dkurt** [comment]
@xiangdeyizhang, please close an issue or follow [a guide](https://raw.githubusercontent.com/opencv/opencv/master/.github/ISSUE_TEMPLATE.md) providing steps to reproduce.
