### ISSUE TITLE
Depth values ordering is broken

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12569]
##### System information (version)
- OpenCV => 4.0.0-pre
- Operating System / Platform => All
- Compiler => All

##### Detailed description
After introducing `CV_16F`, assertions like `CV_Assert(CV_16F < CV_32F)` fails miserably...

##### Steps to reproduce
```C++
    vector<???> order { CV_8U, CV_8S, CV_16U, CV_16S, CV_16F, CV_32S, CV_32F, CV_64F };

    for (int i = 0; i < order.size(); ++i)
    {
        for (int j = 0; j < order.size(); ++j)
        {
            ASSERT_EQ(order[i] <  order[j], i <  j);
            ASSERT_EQ(order[i] <= order[j], i <= j);
            ASSERT_EQ(order[i] >  order[j], i >  j);
            ASSERT_EQ(order[i] >= order[j], i >= j);
        }
    }
```
At least among IEEE floats, in which `CV_16F < CV_32F` now returns false 😕

**Comment by cv3d** [comment]
The current magic register is designed as:
```
FEDCBA9876543210
----------------
             ddd	depth
    nnnnnnnnn   	channels - 1
  r             	reserved (unset)
 c              	continuous flag
s               	submatrix flag
```

However, it is slightly inefficient, so allow me to redesign it as:
```
FEDCBA9876543210
----------------
            dddd	depth
        nnnn    	channels base - 1
     mmm        	channels shift
   r             	reserved (unset)
  1             	CV4 flag (set)
 c              	continuous flag
s               	submatrix flag
```
As you can see, we utilized the reserved bit 13 to differentiate the old and new formats.
Therefore, we will not break any user code, and we can ensure OpenCV to serve any future CV_128F possibilities as well

### Depth
16 different depth types are allowed, and the order is recovered again. Furthermore, we allow some discontinuity for future extensions, as:
```
CV_8U       = 0,
CV_8S       = 1,
CV_16U      = 3,
CV_16S      = 4,
CV_16F      = 5,
CV_32U      = 6,
CV_32S      = 7,
CV_32F      = 8,
CV_64F      = 11,
CV_USRTYPE1 = 15,
```

### Channels
By utilizing `channels = (nnnn + 1) << mmm`, we can have the following channels:
1-16,18,20,22,24,26,28,30,32,36,40,44,48,52,56,60,64,72,80,88,96,104,112,120,128,144,160,176,192,208,224,240,256,288,320,352,384,416,448,480,512,576,640,704,768,832,896,960,1024,1152,1280,1408,1536,1664,1792,1920,2048
which is believe is a reasonable way of division

There are some channels that can be formed in multi-ways, which are:
- 2 ways: 2, 6, 10, 14, 20, 28, 40, 56, 80, 112, 160, 224, 320, 448, 640, 768, 896, 1024
- 3 ways: 4, 12, 24, 48, 96, 192, 384, 512
- 4 ways: 8, 256
- 5 ways: 16, 32, 64, 128
These are in some sense a waste of valuable encoding space, but since we want to have the first 1-16 all available channels, it cannot be helped!

### Future extensions
bit 12 in the new design is reserved for any future extensions

**Comment by cv3d** [comment]
@alalek @vpisarev @mshabunin Introducing half-precision float is great, but it should not have higher value that its flat and double sisters. This would unnecessarily complicate the system.

I suggest swapping CV_32S (or CV_16U) and CV_16F values. Side effects should be be minimal and tolerable for the following reasons:
- It is rare to hard-code 2 or 4 instead of using CV_16U or CV_32S
- CV_16U and CV_32S are among the least famous compared to other depth values (e.g. CV_8U or CV_32F)
- CV_16F is just introduced recently

I wonder though which is less famous, CV_16U or CV_32S

**Comment by vpisarev** [comment]
it's impossible. Just do not direct comparison of depths.
