### ISSUE TITLE
Uniform interface for image shapes

### ISSUE THREAD

**Issue by csbrown** [opencv/opencv#12567]
It seems that the interface for doing things with image shapes is all over the place.

For example, `imread` returns an image for which `y` is the first coordinate and `x` is the second.  However, `resize` takes an argument `dsize` in which `x` is the first coordinate and `y` is the second.
Could we make this so that the tuple order for image shapes is uniform across opencv?

**Comment by alalek** [comment]
`cv::Mat` is multidimensional array.

You want this `cv::Mat` method (via `cv::Point`):
```
template<typename _Tp> _Tp& at(Point pt);
```
