### ISSUE TITLE
After cv2.event: newline symbol (“\n”) prevents rest of string from printing

### ISSUE THREAD

**Issue by mluerig** [opencv/opencv#12562]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Windows 10 64
- Compiler => Spyder 3.3.1

##### Detailed description
I have an extensive function that is supposed to print a longer message between a series of interactive mouse events that get triggered in a while loop. My problem is that any line-break symbols \n I use to break up the longer string will stop the rest of the string from printing. The rest of the message gets printed only after the next mouse event, which is rather silly because the message is containing info about what to do next.

I have not encountered such behavior before, don't know whether it is to be expected or what I can do to stop it. All of the string gets printed when I take out the line breaks, but then the returned text becomes unstructured and unintuitive.

I tried `sys.stdout.write()` with `sys.stdout.flush()`, as wel as linebreaks in `""" """` without success.
##### Steps to reproduce

    
```
import cv2
import numpy as np

class click_action_func(object):
    def __init__(self):
        print("\nstart program\n")
        self.done_step1 = False
        self.done_step2 = False

    def mouse_step1(self, event, x, y, buttons, user_param):
        if event == cv2.EVENT_LBUTTONDOWN:
            print("mouse action for step 1")
        if event == cv2.EVENT_RBUTTONDOWN:
            self.done_step1 = True
            print("end step 1\n---instructions for step 2---(this should be printed together with end step 1, but wont until the next leftclick)")

    def mouse_step2(self, event, x, y, buttons, user_param):
        if event == cv2.EVENT_LBUTTONDOWN:
            print("mouse action step 2")
        if event == cv2.EVENT_RBUTTONDOWN:
            print("end step 2 \nlong text over \nmultiple lines explaining what you just did")
            self.done_step2 = True

    def run(self, image):
        print("instructions\nleft button: do something in image\nright button: finish step 1, receive instructions for next step\nright button again: end program")
        cv2.namedWindow("window", flags=cv2.WINDOW_NORMAL)
        cv2.setMouseCallback("window", self.mouse_step1)

        while(not self.done_step1):
            cv2.imshow("window", image)
            cv2.waitKey(50)

        cv2.namedWindow("window", flags=cv2.WINDOW_NORMAL)
        cv2.setMouseCallback("window", self.mouse_step2)

        while(not self.done_step2):
            cv2.imshow("window", image)
            cv2.waitKey(50)

        cv2.destroyAllWindows()
        print("\nend program")

img = np.zeros((500, 500))
c = click_action_func()
c.run(img)
```

**Comment by mluerig** [comment]
why is the question invalid?

**Comment by alalek** [comment]
Because any questions on this **bugtracker** are invalid.
There is OpenCV Q/A forum for usage questions: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

To prove that this Python "print" issue is related to OpenCV you should have both reproducers with and **without** OpenCV.

Can't reproduce on Fedora 28 (Python 3.6.6).

Probably related: https://bugs.python.org/issue13119

**Comment by mluerig** [comment]
ok thanks
