### ISSUE TITLE
 /usr/bin/ld: cannot find -lopencv_dep_nppitc 

### ISSUE THREAD

**Issue by oftenliu** [opencv/opencv#12575]
- OpenCV => 2.4.13
- Operating System / Platform => Ubuntu16.04
- Compiler => gcc

hello， i build OpenCV 2 with cuda9 successfully,when i use opencv, i meet a problem like that:
/usr/bin/ld: cannot find -lopencv_dep_nppial
/usr/bin/ld: cannot find -lopencv_dep_nppicc
/usr/bin/ld: cannot find -lopencv_dep_nppicom
/usr/bin/ld: cannot find -lopencv_dep_nppidei
/usr/bin/ld: cannot find -lopencv_dep_nppif
/usr/bin/ld: cannot find -lopencv_dep_nppig
/usr/bin/ld: cannot find -lopencv_dep_nppim
/usr/bin/ld: cannot find -lopencv_dep_nppist
/usr/bin/ld: cannot find -lopencv_dep_nppisu
/usr/bin/ld: cannot find -lopencv_dep_nppitc
would appreciate it very much if you
could help me with my problem.

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

> OpenCV 2 with cuda9

OpenCV 2.4 is tested with CUDA SDK 6.5 (may be 7.5). CUDA 8 / 9 is not validated with OpenCV 2.4 by OpenCV team.
2.4 branch is almost under freeze (only critical bugfixes are accepted). Try OpenCV 3.x instead.
