### ISSUE TITLE
Incorrect iterator in KeyPointsFilter::retainBest 

### ISSUE THREAD

**Issue by davep412** [opencv/opencv#12594]
OpenCV => Source code on master
In modules/features2d/src/keypoint.cpp, function `KeyPointsFilter::retainBest` at line 80:
`  std::nth_element(keypoints.begin(), keypoints.begin() + n_points, keypoints.end(), ...
`

This will rearrange the list such that the first `n_points + 1` elements are greater than or equal to the subsequent points, ie `keypoints[0]` through `keypoints[n_points]`. However, the ambiguous response is taken from element `n_points - 1` and there is no guarantee of ordering within this region, so it may actually be quite different from the true ambiguous value at `keypoints[n_points]`.

When called on keypoint vectors that are identical but for ordering (as may happen when switching feature detector implementation from CPU to GPU), the results of `retainBest` may vary.

This only potentially affects the lowest valued keypoints that would otherwise be retained so probably not a big deal performance-wise, but it does manifest when testing different implementations of keypoint generators that return their values in different orders.

**Comment by alalek** [comment]
Could you please provide some minimal reproducer with expected/actual results?

**Comment by davep412** [comment]
Sure - may take a little while to get to.

**Comment by davep412** [comment]
[main.cc.gz](https://github.com/opencv/opencv/files/2399191/main.cc.gz)

Here is a reproducer. Includes a version of retainBest with a proposed fix.

**Comment by alalek** [comment]
Thank you!
Please take a look on #13467
