### ISSUE TITLE
Error when compiling openCV with prebuild ffmpeg for Android

### ISSUE THREAD

**Issue by DmitryMelnyk** [opencv/opencv#12600]
- OpenCV => 3.1.0
- Operating System / Platform => openSUSE Leap 42.3 64-bit
- Compiler => arm-linux-androideabi-g++  (ver 4.9)
- FFMPEG compiled from sources for armeabi-v7a

##### Detailed description
After enabling ffmpeg in CMakeLists.txt and [OpenCVFindLibsVideo.cmake](https://gist.github.com/xuchong/31426c624bffd8802ecf17a830bfef53) cmake-gui after configurations shows next info:

> Looking for /home/d264/Android/android-ndk-r14b/sources/ffmpeg/android/armeabi-v7a/include/libavformat/avformat.h - not found

> Video I/O:
    FFMPEG:                      YES (prebuilt binaries)
      codec:                     NO
      format:                    NO
      util:                      NO
      swscale:                   NO
      resample:                  NO
      gentoo-style:              YES

 
But actually 'libavformat/avformat.h' [exists (ffmpeg folder structure)](https://gist.github.com/DmitryMelnyk/a33c7dbbbe4e2a06d30a621c3ac5c820#file-ffmpeg-folder-structure) under that path.

_Additional information_

> Platform:
    Host:                        Linux 4.4.114-42-default x86_64
    Target:                      Android 1 armv7-a
    CMake:                       3.12.0
    CMake generator:             Ninja
    CMake build tool:            /home/d264/Programs/nanja/ninja
    Configuration:               Release

 >  Android: 
    Android ABI:                 armeabi-v7a
    STL type:                    gnustl_static
    Native API level:            android-19
    SDK target:                  android-19
    Android NDK:                 /home/d264/Android/android-ndk-r14b (toolchain: arm-linux-androideabi-4.9)
    android tool:                /home/d264/Android/Sdk/tools/android (Android SDK Tools, revision 25.2.5.)
    Google Play manager:         NO
    Android examples:            YES

Full [cmake-config-output.txt](https://gist.github.com/DmitryMelnyk/a33c7dbbbe4e2a06d30a621c3ac5c820#file-cmake-gui-config-output) [CMakeLists.txt](https://gist.github.com/DmitryMelnyk/a33c7dbbbe4e2a06d30a621c3ac5c820#file-cmakelists-txt) [ OpenCVFindLibsVideo.cmake](https://gist.github.com/DmitryMelnyk/a33c7dbbbe4e2a06d30a621c3ac5c820#file-opencvfindlibsvideo-cmake)

##### Steps to reproduce
cmake-gui, select source and build, add ANDROID_NDK, ANDROID_NATIVE_API_LEVEL, ANDROID_SDK_ROOT, FFMPEG_INCLUDE_DIR, PKG_CONFIG_PATH, PKG_CONFIG_LIBDIR, choose make instrument (ninja, etc.), specify toolchain file for cross-compiling (platforms/android/android.toolchain.cmake). Click configure.
it is obvious that the project won't compile because of missed ffmpeg files.

What I'm doing wrong?

**Comment by alalek** [comment]
> Android
> ffmpeg

This configuration is not supported.

`cmake --trace-expand` can help to you.

**Comment by DmitryMelnyk** [comment]
> This configuration is not supported.
Thanks for reply.
What do you mean? There are a lot of instructions where people do this, could you be so kind to clarify question. I want to read rtsp stream with videoio. There is no possibility to solve this problem in android even with prebuild ffmpeg libraries?
