### ISSUE TITLE
 after upgrading to opencv 3.4.2 to run a programme the camera release( capture.release() ) function not working can u give me a solution to release the camera 

### ISSUE THREAD

**Issue by lochanafer1995** [opencv/opencv#12616]
- OpenCV => 3.4.2
- Operating System / Platform => windows
- Compiler => python

Dear sir  Earlier i had opencv 3.2.0 where camera release function perfectly but after upgrading to opencv 3.4.2 to run a programme the camera release( capture.release() ) function not working can u give me a solution to release the camera  Thank you

**Comment by yanchao12122** [comment]
the opencv4.0 alpha release has fixed the bug .

**Comment by lochanafer1995** [comment]
im using python how to install opencv4.0 alpha in anaconda env
