### ISSUE TITLE
OpenCV OpenGL failed to build against Cuda 10.0?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#12617]
Deprecated OpenGL code? Anyway, I prefer building OpenGL module with OpenCV...
Any suggestions?

> In file included from ....../opencv/modules/core/include/opencv2/core/private.cuda.hpp:73:0,
>                  from ....../opencv/modules/core/src/precomp.hpp:56,
>                  from ....../opencv/modules/core/src/opengl.cpp:43:
> ....../opencv/modules/core/src/opengl.cpp: In function ‘void cv::cuda::setGlDevice(int)’:
> ....../opencv/modules/core/src/opengl.cpp:118:47: warning: ‘cudaError_t cudaGLSetGLDevice(int)’ is deprecated [-Wdeprecated-declarations]
>          cudaSafeCall( cudaGLSetGLDevice(device) );
>                                                ^
> ....../opencv/modules/core/include/opencv2/core/cuda/common.hpp:74:58: note: in definition of macro ‘cudaSafeCall’
>      #define cudaSafeCall(expr)  cv::cuda::checkCudaError(expr, __FILE__, __LINE__, CV_Func)
>                                                           ^~~~
> In file included from ....../opencv/modules/core/src/opengl.cpp:48:0:
> /usr/local/cuda/include/cuda_gl_interop.h:305:57: note: declared here
>  extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaGLSetGLDevice(int device);
>                                                          ^~~~~~~~~~~~~~~~~
> ....../opencv/modules/core/src/opengl.cpp: In function ‘cv::UMat cv::ogl::mapGLBuffer(const cv::ogl::Buffer&, cv::AccessFlag)’:
> ....../opencv/modules/core/src/opengl.cpp:1827:21: error: call to non-constexpr function ‘cv::AccessFlag cv::operator|(const cv::AccessFlag&, const cv::AccessFlag&)’
>      case ACCESS_READ|ACCESS_WRITE:
>           ~~~~~~~~~~~^~~~~~~~~~~~~
> ....../opencv/modules/core/src/opengl.cpp:1827:21: error: call to non-constexpr function ‘cv::AccessFlag cv::operator|(const cv::AccessFlag&, const cv::AccessFlag&)’
> modules/core/CMakeFiles/opencv_core.dir/build.make:1752: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o' failed
> make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '....../opencv/build'
> CMakeFiles/Makefile2:2587: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
> make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
> make[1]: Leaving directory '....../opencv/build'
> Makefile:165: recipe for target 'all' failed
> make: *** [all] Error 2
> 

Cheers
Pei

**Comment by alalek** [comment]
Error is not related to CUDA SDK: #12618
