### ISSUE TITLE
OpenCV documentation mistake for print(img) when the path is wrong

### ISSUE THREAD

**Issue by Nasrin-Shiraly** [opencv/opencv#12624]
##### System information (version)

- OpenCV => '3.4.3'
- Operating System / Platform => Windows 10 64 Bit
- Compiler => PyCharm

##### Steps to reproduce

Please update the documentation on [this page](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_image_display/py_image_display.html)
It says 

> Warning Even if the image path is wrong, it won’t throw any error, but print img will give you None

However, if the path is **correct** print(img) will return None and we can test against it so below code enters into the if condition. 

```.py
    
import cv2

img_path = "E:\data\Licence.png"
retval = cv2.imread(img_path)

if print(retval) is None:
        cv2.imshow('image', retval)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

else:
        print(retval)

```

**Comment by ananthadiga** [comment]
System information (version)

OpenCV => '4.2'
Operating System / Platform => Mac OS 10.15.3 64 Bit
Compiler => PyCharm

@Nasrin-Shiraly 
print(img) when give a wrong path will give you None but when given right path it returns image in a matrix format. 
Something like this 
[ 77  77  93]
  [ 72  75  83]
  [ 69  74  73]
Unless you use cv2.imshow it won't display an image and more over "if print(retval) is None:" throws a syntax error for print. you can't use print like that. 
Moreover if the value is None it won't be having anything to display. 

if print(retval) is None:
        cv2.imshow('image', retval)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
Thank you. 

@alalek can you close this issue?

**Comment by alalek** [comment]
```.diff
-if print(retval) is None:
+if retval is not None:
```
