### ISSUE TITLE
OpenCV 4.0.0 alpha, <mutex> and /clr

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#12635]
OpenCV 4.0.0 alpha cannot be easily included in a /clr or /clr:pure Visual Studio project, because of the new native use of `<mutex>`, which is forbidden in that case.
It would be easy to fix it, using a cv::Mutex wrapper around std::recursive_mutex (instead of straight typedef), with an opaque implementation that would only include `<mutex>` in the cpp file.
But would such a patch be accepted ?

**Comment by alalek** [comment]
duplicate of #11912
