### ISSUE TITLE
Fixed-point encoding in the ElemType register

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12643]
In case of Q fixed-point floats, there are two families:
- signed
- unsigned
and four underlying types:
- 8-bit
- 16-bit
- 32-bit
- 64-bit
In which all of these reserves 3-bits in the ElemType register, and they can be labeled as:
CV_8Q, CV_8UQ, CV_16Q, CV_16UQ, CV_32Q, CV_32UQ, CV_64Q, CV_64UQ

However, there are various types of fixed-point formats, and we have two options:

#### Proposal one: define the most common ones
- CV_8Q for Q1.6 format
- CV_8UQ for Q1.7 format
- CV_16Q for Q7.8 format
- CV_16UQ for Q8.8 format
- CV_32Q for Q15.16 format
- CV_32UQ for Q16.16 format

Which is already implemented (to some extent) as:
```C++
template <typename baseT, uchar _m, uchar _n, bool _is_signed = true>
class q_t
{
 // some code goes here
};
class q8_t   :  q_t< char    ,  1,  6> {};
class uq8_t  : uq_t<uchar    ,  1,  7> {};
class q16_t  :  q_t< short   ,  7,  8> {};
class uq16_t : uq_t<ushort   ,  8,  8> {};
class q32_t  :  q_t< int     , 15, 16> {};
class uq32_t : uq_t<uint     , 16, 16> {};
class q64_t  :  q_t< int64_t , 31, 32> {};
class uq64_t : uq_t<uint64_t , 32, 32> {};
```

Pros:
- Full channels support (up to 2048)
- Works without any extra design effort

Cons:
- Not all Q-formats supported

#### Proposal two: user-defined precision
User can choose any Q depth (CV_8Q, CV_8UQ, CV_16Q, CV_16UQ, CV_32Q, CV_32UQ, CV_64Q, CV_64UQ), and provide the integral length `m` of the Qm.n, while n is inferred.
- CV_8Q & CV_8UQ
  - `m={0,1,2,3}` (-1 in signed case)
- CV_16Q & CV_16UQ
  - `m={0,2,4,8}` (-1 in signed case)
- CV_32Q & CV_32UQ
  - `m={0,4,8,16}` (-1 in signed case)
- CV_64Q & CV_64UQ
  - `m={0,8,16,32}` (-1 in signed case)

Pros:
- More flexibility in Q-formats supported

Cons:
- Requires slightly additional design effort
 - Limit of only 32 channels

**Comment by alalek** [comment]
Lets discuss similar topics in a single place: #12584

**Comment by cv3d** [comment]
Ok!
