### ISSUE TITLE
Unable to build framework for iOS

### ISSUE THREAD

**Issue by anuragajwani** [opencv/opencv#12646]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => MacOS 10.13.6
- Compiler => XCode 10.0.0

##### Detailed description

I am unable to successfully build OpenCV for an project iOS using the build_framework.py script under platforms/ios. I am trying to extract the ar file to link it within a static library. I have tried using multiple versions of opencv and none seem to work. I have also checked the closed issues and attempted many of the fixes suggested but none worked either. Am I missing something?

##### Steps to reproduce

Command:
```
python platforms/ios/build_framework.py ios
```

Log:

```
error: Build input file cannot be found: '/Users/anurag.ajwani/workspace/opencv/ios/build/armv7-iPhoneOS/modules/world/opencl_kernels_video.cpp'

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/anurag.ajwani/workspace/opencv/ios/build/armv7-iPhoneOS/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7/opencl_kernels_video.o /Users/anurag.ajwani/workspace/opencv/ios/build/armv7-iPhoneOS/modules/world/opencl_kernels_video.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
```

**Comment by sixten-hilborn** [comment]
I believe this is an issue with CMake and Xcode 10 (see [this CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/18099)). I encountered this problem too both when building OpenCV with CMake 3.10.2 as well as my own project where I generate .cpp files with `add_custom_command`.

Upgrading to CMake 3.12+ fixed the issues for me.

**Comment by anuragajwani** [comment]
thanks @sixten-hilborn I was able to overcome the issue with an alternative, I was looking for the archive form and was able to extract from the current `opencv.framework` using `lipo -thin`. i.e. 
```
lipo -thin x86_64 opencv.framework/opencv -o opencv_x86_64.a
```

not sure if to close this issue as I haven't tried the above solution.

**Comment by duchengyao** [comment]
> I believe this is an issue with CMake and Xcode 10 (see [this CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/18099)). I encountered this problem too both when building OpenCV with CMake 3.10.2 as well as my own project where I generate .cpp files with `add_custom_command`.
> 
> Upgrading to CMake 3.12+ fixed the issues for me.

The same issue with `cmake version 3.12.3`

**Comment by Brzhang** [comment]
it works for me  after the cmake  upgraded  to version 3.12.4
