### ISSUE TITLE
Can't use cvCreateButton

### ISSUE THREAD

**Issue by ranbit123** [opencv/opencv#12654]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform =>windows 7
- Compiler => vs c/c++ compiler

##### Detailed description
Hellow!
I am trying to make an interface with a button to load an image.
I am writing in C and and i tried to use **cvCreateButton** as described [here](https://docs.opencv.org/3.4.0/d0/d28/group__highgui__c.html#gad00fc9d8e67c595dcfff75aab7fd4046).
But after building I am getting this error: 
Severity	Code	Description	Project	File	Line	Suppression State Error	LNK2001	unresolved external symbol cvCreateButton

**I wrote this :** 
void ButtonCall(int state, void *userdata) {
	printf("ok");
}
**And this in another function :** 
cvCreateButton("button", ButtonCall, NULL, CV_PUSH_BUTTON, 1);

**Comment by berak** [comment]
you can only use [createButton](https://docs.opencv.org/3.4/dc/d46/group__highgui__qt.html#ga938dc3ab0a9f115156439bd380816e2c) IF you build the opencv libs from src, with support for Qt5 (WITH_QT=ON, you'll also need the Qt dev libs). if you're trying with the prebuilt libs from sourceforge -- they don't have this feature builtin.

> I am writing in C 

please don't. opencv moved to C++ in 2010 already, the remaining C functions are no more maintained, and may vanish in the near future.

**Comment by ranbit123** [comment]
After I will build the opencv libs from src, with support for Qt, will I be able to use it in visual studio ?

**Comment by berak** [comment]
> will I be able to use it in visual studio ?

yes. you will actually need visual studio (or, at least the cl/link toolchain from there) to build the libs.

**Comment by ranbit123** [comment]
Thank you very much!!
> build the opencv libs from src, with support for Qt5 

Do you have good guide for that ? I can't find one.

**Comment by ranbit123** [comment]
I can't find the Qt source code (.zip), the link is not working.
Do you know where can I find it ?

**Comment by ranbit123** [comment]
> however, could you kindly close this issue ? it's not a library bug.
> 
> and further posts about this should rather go to http://answers.opencv.org/questions/
> (instead of cluttering the bugtracker)

I am sorry, I did not know. last question (: 
Thank you very mach!!

**Comment by alalek** [comment]
Try this: http://doc.qt.io/qt-5/windows-support.html
