### ISSUE TITLE
last commit on core/src/va_intel.cpp for  opencv-3.4.3 breaks build on i686 (call of overloaded is ambiguous)

### ISSUE THREAD

**Issue by sergiomb2** [opencv/opencv#12662]
https://github.com/opencv/opencv/commit/4910f16f16a0a0c2b456b14cbc3429c86f96a5f5

##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Fedora 27 , 28 , 29 and rawhide 
- Compiler => gcc 7.3.1 and gcc 8.2.1

##### Detailed description
opencv-3.4.3 fails to build on i686 see above link 
https://copr.fedorainfracloud.org/coprs/sergiomb/opencv/build/803024/

##### Steps to reproduce

reverting the mention patch , don't fail to build 
 ```
/builddir/build/BUILD/opencv-3.4.3/modules/core/include/opencv2/core/check.hpp:95:85: error: call of overloaded 'check_failed_auto(const uint32_t&, int, const cv::detail::CheckContext&)' is ambiguous
[error.txt](https://github.com/opencv/opencv/files/2421967/error.txt)

BUILDSTDERR:          cv::detail::check_failed_ ## type((v1), (v2), CV__CHECK_LOCATION_VARNAME(id));
```

**Comment by sergiomb2** [comment]
[error.txt](https://github.com/opencv/opencv/files/2421968/error.txt)

**Comment by sergiomb2** [comment]
also fails to build on armv7

**Comment by sergiomb2** [comment]
https://github.com/opencv/opencv/commit/4910f16f16a0a0c2b456b14cbc3429c86f96a5f5 breaks build on i686 and arm (32 bits processors) 
I have to revert this commit to build successfully on i686 and arm , ppc64le and x86_64 are not affected

**Comment by sergiomb2** [comment]
[fix_support_YV12_too.patch.txt](https://github.com/opencv/opencv/files/2637140/fix_support_YV12_too.patch.txt)

It is not the right fix but could give us a clue . Build fail in CV_CheckEQ . I found it after understand better the build error message.

**Comment by mshabunin** [comment]
I've successfully built OpenCV _master_ and _3.4.3_ in Ubuntu 18 using i686 toolchain:
```
cmake -GNinja \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=i686 \
    -DCMAKE_CXX_COMPILER=i686-linux-gnu-g++-7 \
    -DCMAKE_C_COMPILER=i686-linux-gnu-gcc-7 \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
    ../opencv
```
Our [linux32/master](https://pullrequest.opencv.org/buildbot/builders/master-contrib_noOCL-lin32) and [armv7/master](https://pullrequest.opencv.org/buildbot/builders/master-contrib_ARMv7-lin) builds pass too. [armv7/3.4](https://pullrequest.opencv.org/buildbot/builders/3_4-contrib_ARMv7-lin) build passes (python test fails) and [linux32/3.4](https://pullrequest.opencv.org/buildbot/builders/3_4-contrib_noOCL-lin32) build passes.

Could you please add more details about your build to help us reproduce the issue and fix it properly?

**Comment by sergiomb2** [comment]
https://src.fedoraproject.org/rpms/opencv/tree/master
I'm building it now without fix_support_YV12_too.patch , here https://copr.fedorainfracloud.org/coprs/sergiomb/opencv/build/832793/

**Comment by sergiomb2** [comment]
Looks good ;) I check it soon .
Many thanks.

**Comment by sergiomb2** [comment]
checked, it fixed with https://github.com/opencv/opencv/pull/13351
