### ISSUE TITLE
Help to build only selected modules for android

### ISSUE THREAD

**Issue by Rajeshr34** [opencv/opencv#12689]
I am trying to build *.so files for android modules which iam looking are core,imgproc and java files.

Below code works fine it generates java wrapper files which here is "libopencv_java400.so"

`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_LIST=${OPEN_CV_BUILD_MODULES} -D BUILD_ANDROID_PROJECTS=OFF -D WITH_FFMPEG=OFF -D WITH_IPP=OFF -D WITH_OPENEXR=OFF -D BUILD_EXAMPLES=OFF -D BUILD_ANDROID_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_DOCS=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D BUILD_SHARED_LIBS=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF .. && make -j8`

But when i run to generate for arm64 it doesnt generate java files and libopencv_java400.so file

```
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D ANDROID=ON \
        -D ANDROID_ABI="arm64-v8a" \
        -D BUILD_LIST="imgproc,java" \
        -D BUILD_ANDROID_PROJECTS=OFF \
        -D BUILD_SHARED_LIBS=ON \
        -D CMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake \
        -D ANDROID_NATIVE_API_LEVEL=19 \
        -D ANDROID_FORCE_ARM_BUILD=OFF \
        -D ANDROID_STL_FORCE_FEATURES=OFF \
        .. &&\
        make -j$NUM_CORES && \
        make install
```

Can any one share working cmake code to geneate.

Thank you

here is my dockerfile code

https://gist.githubusercontent.com/Rajeshr34/43fc08179bcb8c787d6630e0dd926a74/raw/788c41f4699ba72ee0c31eea025d2852d2c720bd/DockerFile

**Comment by berak** [comment]
helo, @Rajeshr34 , -- may i ask you to move your question to http://answers.opencv.org/questions/ ?

(this is the opencv library *bugtracker* , it's the wrong place, and we can help you with your problem much better from there, so kindly close this issue, and re-ask there, thank you !)

**Comment by alalek** [comment]
Android build scripts generates ".a" files instead of ".so" files for OpenCV modules.
