### ISSUE TITLE
readFromONNX Failed

### ISSUE THREAD

**Issue by dendisuhubdy** [opencv/opencv#12694]
I made some changes to the samples to load a .onnx file instead, but an exception was thrown but not for any other frameworks.

```
Throw exception: OpenCV(4.0.0-pre) /Users/grokmachine/dev/libs/opencv/modules/core/src/matrix.cpp:321: error: (-215:Assertion failed) 0 <= d && d <= CV_MAX_DIM && _sizes in function 'create'
```

**Comment by dendisuhubdy** [comment]
@alalek as `incomplete` do you mean the issue is incomplete or the code is? If the later, how can I help

**Comment by alalek** [comment]
Minimal complete reproducer is required (as stated in issue template which you are ignored).

**Comment by dendisuhubdy** [comment]
I ran the https://github.com/opencv/opencv/blob/master/samples/dnn/classification.cpp with the modification that I removed config from the command line, and replaced https://github.com/opencv/opencv/blob/master/samples/dnn/classification.cpp#L82 with 

```
Net net = readNetfromONNX(model);
``` 

and let most of the rest within a try exception block.

**Comment by dendisuhubdy** [comment]
I tried my own Onnx file which is a modification of the resnet101

**Comment by dendisuhubdy** [comment]
You guys support really fucking sucks
