### ISSUE TITLE
Incorrect Y coordinates in mouse callback on Mac 

### ISSUE THREAD

**Issue by sjmgarnier** [opencv/opencv#12699]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => macOS High Sierra (10.13.6)
- Compiler => Apple LLVM version 10.0.0 (clang-1000.10.44.2)

##### Detailed description

I'm using a mouse callback on a window created with HighGUI in order to retrieve the X/Y coordinates of the mouse pointer when the user click inside the image. The returned coordinates are correct along the X axis, but off along the Y axis. In particular, if I click at the top of the image (where the Y coordinates should be 0), nothing happens. I have to click several pixels below the top of the image (maybe 15-20 pixels) to get a response (0 instead of 15-20). If I click at the very bottom of the image (where the Y coordinates should be the height of the image), I get the correct response. It is like the active part of the image (that is the one in which a click generates a response) is compressed along the Y axis relative to the actual height occupied by the image. 

Note that this bug might be similar to #7485, but I wasn't certain of it. 

##### Steps to reproduce

Below is the code I used.  

```.cpp
struct ClickData {
  int x;
  int y;
  int button;
};

void onMouse(int event, int x, int y, int flags, void* data) {
  ClickData* p = (ClickData*) data;

  if  (event == cv::EVENT_LBUTTONDOWN) {
    p->x = x;
    p->y = y;
    p->button = 0;
  } else if (event == cv::EVENT_RBUTTONDOWN) {
    p->x = x;
    p->y = y;
    p->button = 1;
  }
}

ClickData _click(std::string window_name) {
  ClickData d;
  d.button = -1;
  cv::setMouseCallback(window_name, onMouse, &d);

  while (d.button == -1) {
    cv::waitKey(10);
  }
  return d;
}
```

**Comment by alalek** [comment]
Lets keep similar problems in single place.

**Comment by sjmgarnier** [comment]
@alalek Sounds good. Should I copy the text of this issue over to #7485?
