### ISSUE TITLE
Error in cuda videoreader sample program

### ISSUE THREAD

**Issue by sam09** [opencv/opencv#12692]
##### System information (version)
- OpenCV => 3.4
- Cuda - 9.2
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => g++ 4.9

##### Detailed description
The videoreader example has both the cpu and gpu reading of video frames in the same for loop. This should be moved to for loops as the GPU decoded video could have more number of frames.

I am not sure if this is a bug in cuda videoreader code or in the sample program.
##### Steps to reproduce

Moving the vVideoCapture  to different loop and adding a frame counter gives different results

`Sample Output`

```
Results:
CPU : Avg : 4.82522 ms FPS : 207.245 1794

GPU : Avg : 0.549416 ms FPS : 1820.11 3572

```

**Comment by sam09** [comment]
Can I pick this up?

**Comment by alalek** [comment]
Sure.
