### ISSUE TITLE
Error in ORB.detect function , unbound type error

### ISSUE THREAD

**Issue by rishantagarwal** [opencv/opencv#12706]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Mac OS X ( Related to JS version of Open CV)
- JS has been built using branch 3.4

##### Detailed description

Was trying to use orb.detect() function in JS but it throws errors: 

`Cannot call Feature2D.detect due to unbound types: NSt3__26vectorIN2cv8KeyPointENS_9allocatorIS2_EEEE↵ at UnboundTypeError`

##### Steps to reproduce

Use the steps as mentioned in the tutorial to include JS file in your code
and then when opencv has been loaded into Browser memory run this code

```js
console.log(cv);
let imgMat = cv.imread(imgElement);
let orb = new cv.ORB();
let kp = orb.detect(imgMat,"");
console.log("kp",kp);
// let result = orb.compute(imgMat,kp);
// console.log("result",result);
mat.delete();
```

**Comment by rishantagarwal** [comment]
Related to this issue here : https://github.com/opencv/opencv/issues/11300

**Comment by dkurt** [comment]
@rishantagarwal, Thank you for your report! Please test the changes from https://github.com/opencv/opencv/pull/12767 replacing
```js
let kp = orb.detect(imgMat,"");
```
to the following code:
```js
let kp = new cv.KeyPointVector();
orb.detect(imgMat, kp);
```

**Comment by rishantagarwal** [comment]
Thanks for the changes, will check and get back asap. Appreciate your efforts

**Comment by alalek** [comment]
It would be nice to have:
- [ ] `DMatch` wrapper
- [ ] corresponding JavaScript tests

**Comment by nestarz** [comment]
I second @alalek, can we have DMatch wrapper ?
