### ISSUE TITLE
Unable to build opencv4 alpha

### ISSUE THREAD

**Issue by zhouhao27** [opencv/opencv#12712]
##### System information (version)

- OpenCV => :4.0:
- Operating System / Platform => :Mac OSX 10.13.6:
- Compiler => :Xcode 8.33 and Xcode 10:

##### Detailed description

Here is my cmake command:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=~/Public \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=OFF \
    -D INSTALL_C_EXAMPLES=OFF \
    -D BUILD_EXAMPLES=OFF ..
```

Then I got the follow error message:

```
-- Configuring incomplete, errors occurred!
See also "/Users/a635219/Public/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/Users/a635219/Public/opencv/build/CMakeFiles/CMakeError.log".
```

Here are the errors in CMakeError.log:

```
Compilation failed:
    source file: '/Users/a635219/Public/opencv/cmake/checks/cpu_popcnt.cpp'
    check option: ' -msse -msse2 -msse3 -mssse3 -msse4.1'
===== BUILD LOG =====
Change Dir: /Users/a635219/Public/opencv/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_abbd3/fast"
/Applications/Xcode-10.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_abbd3.dir/build.make CMakeFiles/cmTC_abbd3.dir/build
Building CXX object CMakeFiles/cmTC_abbd3.dir/cpu_popcnt.cpp.o
/Applications/Xcode-10.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -O3 -DNDEBUG -fPIE   -msse -msse2 -msse3 -mssse3 -msse4.1 -std=c++11 -o CMakeFiles/cmTC_abbd3.dir/cpu_popcnt.cpp.o -c /Users/a635219/Public/opencv/cmake/checks/cpu_popcnt.cpp
/Users/a635219/Public/opencv/cmake/checks/cpu_popcnt.cpp:14:4: error: "__POPCNT__ is not defined by compiler"
#  error "__POPCNT__ is not defined by compiler"
   ^
/Users/a635219/Public/opencv/cmake/checks/cpu_popcnt.cpp:22:13: error: use of undeclared identifier 'CV_POPCNT_U32'
    int j = CV_POPCNT_U32(1);
            ^
2 errors generated.
make[1]: *** [CMakeFiles/cmTC_abbd3.dir/cpu_popcnt.cpp.o] Error 1
make: *** [cmTC_abbd3/fast] Error 2

===== END =====
```

Any suggestion? Thanks.

**Comment by sriki77** [comment]
Use the `gcc` binary from for OSX mojave.

https://github.com/sol-prog/macos-gcc-binary

pass additional argument to cmake `-D CMAKE_CXX_COMPILER=/usr/local/gcc-8.2/bin/g++-8.2 `

**Comment by zhouhao27** [comment]
@sriki77 Thanks. Actually I managed to compile it by using CMake GUI.

**Comment by Kirow** [comment]
got same error, installed gcc via homebrew `brew install gcc`

**Comment by Kirow** [comment]
ok, I've finally managed to make it work...`g++-8.2` did not help, just added another errors

`error "__POPCNT__ is not defined by compiler"` appeared only if I run cmake with `OPENCV_EXTRA_MODULES_PATH`
So I run w/o it, and then added `OPENCV_EXTRA_MODULES_PATH` from cmake GUI.

Frankly speaking, I did not understand what the problem...

**Comment by alalek** [comment]
Please don't discuss "__POPCNT__ is not defined by compiler" message anymore.
It is just result of configuration feature check from file cmake/checks/cpu_popcnt.cpp. There is no error at all.
Dig into other direction, start from CMake stdout/stderr.

**Comment by allahbaksh** [comment]
> ok, I've finally managed to make it work...`g++-8.2` did not help, just added another errors
> 
> `error "__POPCNT__ is not defined by compiler"` appeared only if I run cmake with `OPENCV_EXTRA_MODULES_PATH`
> So I run w/o it, and then added `OPENCV_EXTRA_MODULES_PATH` from cmake GUI.
> 
> Frankly speaking, I did not understand what the problem...

Can you just point out how to run cmake GUI. So your trick of remove the the extra module worked.

**Comment by javadba** [comment]
> just result of configuration feature check
Well it kills the build. If it's not needed pls describe how to remove it.

**Comment by javadba** [comment]
> Use the `gcc` binary from for OSX mojave.
> 
> https://github.com/sol-prog/macos-gcc-binary
> 

I just used g++-9.1 and it worked

Add the following flag:
`-DCMAKE_CXX_COMPILER=/usr/local/gcc-9.1/bin/g++-9.1`

> pass additional argument to cmake `-D CMAKE_CXX_COMPILER=/usr/local/gcc-8.2/bin/g++-8.2 `
