### ISSUE TITLE
Error - ReadProtoFromBinaryFile

### ISSUE THREAD

**Issue by hassaanseeker** [opencv/opencv#12724]
Hi,
Although this a basic issue. But still can anyone help me regarding this.

This is the error i am getting when i try to load model-weights & text-graph.

Opencv Version: '3.4.3'
Ubuntu : 18.04

```net = cv.dnn.readNetFromTensorflow("/home/mask_rcnn_inception_v2_coco_2018_01_28/mask_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb", "/home/mask_rcnn_inception_v2_coco_2018_01_28/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt")```
```cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/home/mask_rcnn_inception_v2_coco_2018_01_28/mask_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb" in function 'ReadProtoFromBinaryFile```

**Comment by alalek** [comment]
> Can't open

Dig into this direction. `strace`, `gdb` tools can help you... to see wrong path.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by davidsonlima** [comment]
Solution: https://github.com/vjgpt/Object-Detection/issues/1
