### ISSUE TITLE
Error while running the program : "program has stopped working"

### ISSUE THREAD

**Issue by vivkv** [opencv/opencv#12720]
##### System information (version)
- OpenCV =>  4.0.0-pre
- Operating System / Platform => Windows 64 Bit
- Compiler => MinGW g++ (tdm-1) 5.1.0 from codeblocks

##### Detailed description

I built OpenCV from source using MinGW which was shipped along with codeblocks. 
My build and install was successful. 
[https://imgur.com/a/IWFrXc7](https://imgur.com/a/IWFrXc7)

Now, to check my built library I ran a sample program

**OpenCVTest.cpp**
----------------------------
```
#include <iostream>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

using namespace cv;
using namespace std;

int main( )
{    
  // Create black empty images
  Mat image = Mat::zeros( 400, 400, CV_8UC3 );

  // Draw a line 
  line( image, Point( 15, 20 ), Point( 70, 50), Scalar( 110, 220, 0 ),  2, 8 );
  imshow("Image",image);
  cout<<"******************";
  waitKey( 0 );
  return(0);
} 

```
using cmd -

`g++ -std=c++11 OpenCVTest.cpp -llibopencv_core400 -llibopencv_highgui400 -llibopencv_imgproc400`

I am able to compile to source code, but on running the program, I am getting a window pop up with **program has stopped working** message

[https://imgur.com/a/fXihGc8](https://imgur.com/a/fXihGc8)

##### Steps to reproduce

1. Downloaded the source code from github.
2. Using CMake, pointed the source code directory and the build directory.
3. Ran CMake and it generated some file and folders in build directory.
4. Ran **mingw32-make** command in build directory.
5. Ran **mingw32-make install**.
6. Copied the folder `opencv2` in `D:\Programs\OpenCV-Source\build\install\include`  to  `C:\Program Files (x86)\CodeBlocks\MinGW\include`
7. Copied the files (.dll)  from `D:\Programs\OpenCV-Source\build\install\x86\mingw\bin`   to  `C:\Windows\SysWOW64`
8. Copied the files (.a files) from `D:\Programs\OpenCV-Source\build\install\x86\mingw\lib`  to  `C:\Program Files (x86)\CodeBlocks\MinGW\lib`  
9. Wrote the above program on FAR Manager.
10.  compiled on cmd using `g++ -std=c++11 OpenCVTest.cpp -llibopencv_core400 -llibopencv_highgui400 -llibopencv_imgproc400`
11. produced `a.exe`. Ran it and got the error.

**Comment by alalek** [comment]
> MinGW

We don't support any of these configurations.

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
