### ISSUE TITLE
undeclared identifier 'CV__ErrorNoReturn' under clang-tidy 7.0

### ISSUE THREAD

**Issue by nedrebo** [opencv/opencv#12736]
##### System information (version)
- OpenCV => 3.4.3-3
- Operating System / Platform => Arch Linux
- Compiler => clang++7.0 / clang-tidy-7.0

##### Detailed description
Starting from this commit (https://reviews.llvm.org/D44906) `clang-tidy` defines `__clang_analyzer__`. This triggers the definition of `CV_STATIC_ANALYSIS` in core/cvdef.h. This in turn causes `CV_ErrorNoReturn` to not be defined in `core/base.hpp` but it is still used in `dnn/dnn.inl.hpp`

##### The error message is this:
```
/usr/include/opencv2/dnn/dnn.inl.hpp:280:5: error: use of undeclared identifier 'CV__ErrorNoReturn' [clang-diagnostic-error]
    CV_ErrorNoReturn(Error::StsInternal, "");
```
Regular builds using clang++7 works just fine.

##### Workaround / fix
To work around this I pass -DCV_STATIC_ANALYSIS=0 to clang++7 when using clang-tidy. This solves my immediate problem. However, I still think this is a bug that should be fixed.

**Comment by alalek** [comment]
@nedrebo Please check this patch: #12744
