### ISSUE TITLE
I have OpenCV 4.0.0-pre I get the following error when I am trying to run the YOLO DNN tutorial

### ISSUE THREAD

**Issue by Con-Mi** [opencv/opencv#12747]
I get the following error when I am running the binary:

what():  OpenCV(4.0.0-pre) /home/kourtinesble/GithubBuild/opencv/modules/dnn/src/dnn.cpp:1151: error: (-2:Unspecified error) Requested layer "detection_out" not found in function 'getLayerData'

Aborted (core dumped)

**Comment by dkurt** [comment]
@Con-Mi, make it more reproducible.
Please provide references to used models. Put command line arguments and specify a sample. Is it [object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) or [object_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py) or a custom one?

**Comment by Con-Mi** [comment]
@dkurt I fixed it the problem. I was the tutorial on yolo dnn in Opencv C++ which seems that has been removed from the website. I did not use the object_detection.cpp because I guess it was added later. In any way I fixed it and it runs ok. Thanks

**Comment by thakoreneelabh** [comment]
@Con-Mi 
Hi,
Can you please highlight on how it got fixed?
We are using C++ with open CV 3.1 and planing to move from TinlyYOLO 2 to 3. For 2 the C++ code works fine however it gives below error for 3.
'cv::Exception'
  what():  OpenCV(3.4.3) /home/.../.../.../opencv3.4.3/opencv/modules/dnn/src/dnn.cpp:1151: error: (-2:Unspecified error) Requested layer "detection_out" not found in function 'getLayerData'

Will be really helpful if you can suggest any solution.

Regards
Neelabh
