### ISSUE TITLE
getConvertScaleFunc(): equal treatment of underlying convertors

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12743]
`cv::cvtScale32s()` is defined as:
```
DEF_CVT_SCALE_FUNC(32s, cvt_64f, int, int, double)
```
which makes sense to achieve high accurcy (to pass `Core_Transform*` tests?).

But why only `cvtScale32s()` uses `double`, while the rest conversion functions utilizes `float`? From equal-treatment point of view, I expect `cvtScale32s()` to utilize `float`, or all rest convertors `cvtScale*()` to utilize `double` as well.

What do you think?

**Comment by alalek** [comment]
All is right here.

**Comment by cv3d** [comment]
> All is right here

Does that mean I shall push a PR which utilizes `double` in the conversion of `char` and `short` as well?
