### ISSUE TITLE
OpenCv failed to run object_detection.cpp with OPENCL option.

### ISSUE THREAD

**Issue by farshadopencv** [opencv/opencv#12756]
I use object_detection.cpp script with ssd model of tensorflow. By default, the value of `--target` in the argument parser is `0`. I want to use OpenCl rather than only CPU so I changed `--target = 1` . But visual studio crashes and it can not run script with opencl. How can I modify my code or functions for using opencl option? do I need to install something on my device? 

##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

**Comment by alalek** [comment]
> crashes

Please add stacktrace dump.

> OpenCL

Add dump of OpenCL information via "clinfo" or via "opencv_version --opencl".

Did you try to run OpenCV DNN tests on your machine?

**Comment by dkurt** [comment]
@farshadopencv, Can you please provide steps to reproduce? At least add references to used models.
If there is no issue anymore please close an issue.
