### ISSUE TITLE
Cuda build broken: gpu_mat.cu refers to inexisting CUDEV

### ISSUE THREAD

**Issue by mratsim** [opencv/opencv#12768]
##### System information (version)

- OpenCV => master
- Operating System / Platform => Linux
- Compiler => GCC 7 with NVCC

##### Detailed description

Compilation failure with 

<path/to/opencv>/modules/core/src/cuda/gpu_mat.cu:47:2: error: #error "opencv_cudev is required"

The origin is there

https://github.com/opencv/opencv/blob/e340ff9c3aef8554bb0a7eb599a9afb4f3ec2f57/modules/core/src/cuda/gpu_mat.cu#L43-L57

The Cudev module doesn't exist anymore and used to be here: https://github.com/opencv/opencv/tree/e340ff9c3aef8554bb0a7eb599a9afb4f3ec2f57/modules/cudev/include/opencv2

I suppose it was the module which was supposed to define HAVE_OPENCV_CUDEV

##### Steps to reproduce

Compile with CUDA

**Comment by alalek** [comment]
You should build with opencv_contrib for using CUDA functionality: #12585

**Comment by wuqingshan2010** [comment]
i have the same problem, how can i do it?

**Comment by rkachach** [comment]
Facing the same issue. I'm getting this error even when contrib is part of the build. Any ideas on how it can be solved?

**Comment by tomrunia** [comment]
Same problem with OpenCV 4.0.1 (no contrib) with CUDA 9.2 on CentOS.

**Comment by vahidajalluian** [comment]
@tomrunia  even mere including opencv_contrib doesn't solve the problem. It doesnt matter how hard I have tried to build opencv 4.0.1 or 4.1.0 with cuda there was no success using cmake itself.  what really solved the problem was using cmake-gui. I don't know how it had worked, but it did solve my problem.

**Comment by akhalili** [comment]
Solution: 
make sure "OPENCV_EXTRA_MODULES_PATH" is set to:
 <address to opencv_contribute>/modules

i.e:
-DOPENCV_EXTRA_MODULES_PATH=<address to opencv_contribute>/modules

**Comment by vahidajalluian** [comment]
@akhalili even setting the directory doesnt do the job.  I'm sure cmake gui use some extra features that solves problem.

**Comment by linqingfan** [comment]
> Solution:
> make sure "OPENCV_EXTRA_MODULES_PATH" is set to:
> 
> /modules
> i.e:
> -DOPENCV_EXTRA_MODULES_PATH=
> 
> /modules

Thanks
