### ISSUE TITLE
Linking to multithreaded MKL is an exercise in frustration

### ISSUE THREAD

**Issue by mratsim** [opencv/opencv#12771]
This is a followup to #12766 (Linking to intel OpenMP).

Instead of doing computer vision, I spent my day fixing CMake build scripts :/.

Here are the issues I encountered:

1. As mentioned in https://github.com/opencv/opencv/issues/11383 the TBB detector in MKL is wrong: https://github.com/opencv/opencv/blob/a9c8a526cf5009711939c529717b185fd1645c98/cmake/OpenCVFindMKL.cmake#L97-L100. Changing that to `TBB_ENV_LIB` doesn't work, I have to explicit replace the path in that file.

2. Linking to Intel OpenMP, see #12766.

3. Trying to link OpenCV with MKL built with Intel TBB doesn't work, I always get linked to mkl_sequential or mkl_gnu_threads whatever ON/OFF combinations of flags `WITH_MKL` `MKL_USE_MULTITHREAD` `MKL_WITH_TBB` `MKL_WITH_OPEN` `WITH_OPENMP` `WITH_TBB`. In the end to solve that I had to basically nuke the logic in that file to solve points 1 and 3 with the following patch file:
    ```patch
    --- OpenCVFindMKL.cmake 2018-10-07 22:42:46.618955024 +0000
    +++ new_OpenCVFindMKL.cmake     2018-10-07 23:12:36.267540713 +0000
    @@ -97,22 +97,11 @@
    if(${MKL_VERSION_STR} VERSION_GREATER "11.3.0" OR ${MKL_VERSION_STR} VERSION_EQUAL "11.3.0")
        set(mkl_lib_find_paths
            ${MKL_ROOT_DIR}/lib
    -        ${MKL_ROOT_DIR}/lib/${MKL_ARCH} ${MKL_ROOT_DIR}/../tbb/lib/${MKL_ARCH})
    +        ${MKL_ROOT_DIR}/lib/${MKL_ARCH} /opt/intel/composerxe/linux/tbb/lib/intel64/gcc4.7/) # We should use ${TBB_ENV_LIB} instead

        set(mkl_lib_list "mkl_intel_${MKL_ARCH_SUFFIX}")

    -    if(MKL_WITH_TBB)
    -        list(APPEND mkl_lib_list mkl_tbb_thread tbb)
    -    elseif(MKL_WITH_OPENMP)
    -        if(MSVC)
    -            list(APPEND mkl_lib_list mkl_intel_thread libiomp5md)
    -        else()
    -            list(APPEND mkl_lib_list mkl_gnu_thread)
    -        endif()
    -    else()
    -        list(APPEND mkl_lib_list mkl_sequential)
    -    endif()
    -
    +    list(APPEND mkl_lib_list mkl_tbb_thread tbb)
        list(APPEND mkl_lib_list mkl_core)
    else()
        message(STATUS "MKL version ${MKL_VERSION_STR} is not supported")
    ```
4. Where is MKL used? As mentioned here https://github.com/opencv/opencv/issues/11383, BLAS library are not needed anymore for DNN in [OpenCV 3.3](https://github.com/opencv/opencv/wiki/ChangeLog#version33) but I would expect that LAPACK functionality is still needed given that the option `WITH_LAPACK` is still there but even the [PCA](https://github.com/opencv/opencv/blob/808ba552c532408bddd5fe51784cf4209296448a/modules/core/src/pca.cpp) is not using LAPACK for either SVD or covariance matrix + eigenvecs computation. Checking the linked libraries/dependencies yields "Unused shared library":

![2018-10-08_03-13-38](https://user-images.githubusercontent.com/22738317/46589292-3ce8b400-caa8-11e8-9b74-2c0d239b9dd7.png)

Full build script is available here: https://github.com/mratsim/Arch-Data-Science/blob/5e79e4ca1b8b5e676d5f2bbfe51d8fcbbbbb55d8/opencv-cuda-mkl-ffmpeg-git/PKGBUILD

**Comment by alalek** [comment]
Lets keeps similar topic in a single thread: #12766
