### ISSUE TITLE
make -j2 build fails at [%41] : Error1 Error2

### ISSUE THREAD

**Issue by paglino-t** [opencv/opencv#12778]
##### System information (version)

- OpenCV => : 3.4.1:
- Operating System / Platform => :MacOS High Sierra 10.13.6:
- Compiler => :Xcode 10.0:

##### Detailed description

command prompt : make -j2

Scanning dependencies of target opencv_ximgproc
[ 41%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/adaptive_manifold_filter_n.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/reshape_layer.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/resize_nearest_neighbor_layer.cpp.o
[ 41%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/domain_transform.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/scale_layer.cpp.o
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/domain_transform.cpp:38:
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.hpp:292:
/Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.inl.hpp:473:44: error: no member named 'type' in
      'cv::Vec<float, 1>'; did you mean 'time'?
    dst.create(guide.rows, guide.cols + 1, IDistVec::type);
                                           ^~~~~~~~~~~~~~
                                           time
/usr/include/time.h:117:8: note: 'time' declared here
time_t time(time_t *);
       ^
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/domain_transform.cpp:38:
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.hpp:292:
/Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.inl.hpp:500:52: error: no member named 'type' in
      'cv::Vec<float, 1>'; did you mean 'time'?
    dist = getWExtendedMat(guide.rows, guide.cols, IDistVec::type, 1, 1);
                                                   ^~~~~~~~~~~~~~
                                                   time
/usr/include/time.h:117:8: note: 'time' declared here
time_t time(time_t *);
       ^
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/domain_transform.cpp:38:
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.hpp:292:
/Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.inl.hpp:501:57: error: no member named 'type' in
      'cv::Vec<float, 1>'; did you mean 'time'?
    idist = getWExtendedMat(guide.rows, guide.cols + 1, IDistVec::type);
                                                        ^~~~~~~~~~~~~~
                                                        time
/usr/include/time.h:117:8: note: 'time' declared here
time_t time(time_t *);
       ^
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/domain_transform.cpp:38:
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.hpp:292:
/Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.inl.hpp:538:54: error: no member named 'type' in
      'cv::Vec<float, 1>'; did you mean 'time'?
    dtf.a0distHor.create(guide.rows, guide.cols - 1, DistVec::type);
                                                     ^~~~~~~~~~~~~
                                                     time
/usr/include/time.h:117:8: note: 'time' declared here
time_t time(time_t *);
       ^
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/domain_transform.cpp:38:
In file included from /Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.hpp:292:
/Users/tarapaglino/opencv_contrib/modules/ximgproc/src/dtfilter_cpu.inl.hpp:568:55: error: no member named 'type' in
      'cv::Vec<float, 1>'; did you mean 'time'?
    dtf.a0distVert.create(guide.rows - 1, guide.cols, DistVec::type);
                                                      ^~~~~~~~~~~~~
                                                      time
/usr/include/time.h:117:8: note: 'time' declared here
time_t time(time_t *);
       ^
5 errors generated.
make[2]: *** [modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/domain_transform.cpp.o] Error 1
make[1]: *** [modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/shift_layer.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/slice_layer.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/softmax_layer.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/split_layer.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/nms.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/common.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/math_functions.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp.o
[ 41%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_inner_product.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_lrn.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_pool.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_softmax.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/op_halide.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/op_inf_engine.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_importer.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_io.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THDiskFile.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THFile.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THGeneral.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o
[ 42%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o
[ 42%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
[ 42%] Built target opencv_dnn
make: *** [all] Error 2

- Any ideas?
-->

**Comment by alalek** [comment]
Your opencv_contrib code is outdated.
Keep both opencv & opencv_contrib repositories synchronized (same tag, branch, date).

Build and usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by paglino-t** [comment]
Thank you!
