### ISSUE TITLE
Build fails for 3.3 on cuda-10

### ISSUE THREAD

**Issue by abhinavkulkarni** [opencv/opencv#12786]
Hi all,

I have a fresh installation of **Ubuntu 16.04** with **cuda 10.0** that I have trouble building OpenCV on. I tried building versions `3.3.0`, `3.4.0` and `4.0.0-alpha`, but no success.

I have recorded the terminal session for the build process and you can find it here: [script-1539117722.log](https://github.com/opencv/opencv/files/2462187/script-1539117722.log)

As you can see, I have latest versions of `cuda`, `g++` and `C++11` support is enabled. OpenCV is able to detect the graphics card (NVIDIA GTX 1060). I am not quite sure why the `make` command fails.

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Please let me know. I would be happy to try out suggestions and upload terminal sessions.

Thanks.

**Comment by alalek** [comment]
> --     NVIDIA GPU arch:             20 30 35 37 50 52 60 61

> nvcc fatal   : Unsupported gpu architecture 'compute_20'

This is configuration issue:
```
cmake -DCUDA_ARCH_BIN=6.1 ...
```

**Comment by abhinavkulkarni** [comment]
Hi @alalek,

Thanks for the response. Can you please explain what exactly wrong I was doing?

Your suggestion is to keep the `cmake` command the same, but add an additional option `-DCUDA_ARCH_BIN=6.1`? How did you find out `6.1` value?

Appreciate the quick response.

Thanks.

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

You may start digging from here:
https://devtalk.nvidia.com/default/topic/988317/jetson-tx1/what-should-be-the-value-of-cuda_arch_bin/

**Comment by abhinavkulkarni** [comment]
Hi,

I figured out how @alalek came up with the revision number of `6.1`. To find out the revisino number for your NVIDIA GPU, as explained here [this link](https://devtalk.nvidia.com/default/topic/988317/what-should-be-the-value-of-cuda_arch_bin/), I ran `/usr/local/cuda-10.0/samples/1_Utilities/deviceQuery/deviceQuery` to obtain `CUDA Capability Major/Minor version number:    6.1`.

Thanks!
