### ISSUE TITLE
iOS Stitcher PlaneWarper OrbFeaturesFinder

### ISSUE THREAD

**Issue by mark-bragg** [opencv/opencv#12782]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => iOS 10.0
- Compiler => XCode 9.4.1

##### Detailed description

Using Stitcher, I can create panoramas, but I want to use certain classes within the stitching pipeline to produce better results. I am creating a feature to take planar panoramas of shelves. Using the following initialization: ```Ptr<Stitcher> stitcher = Stitcher::create(Stitcher::SCANS, try_use_gpu);``` provides somewhat decent photos sometimes. I have researched a bit and found that using a plane warper and an ORB features finder would work well, and I tested it out on my Mac, and the results were far better. I have tried implementing the same on the iOS build, but it just crashes as soon as it tries to stitch.
Error: 7F6F621C-E950-426E-826C-516EB5B58213 (1): EXC_BAD_ACCESS (code=1, address=0x0)
So, there is a nil value somewhere in there breaking the implementation. I don't know where to go from here.

##### Steps to reproduce

    Ptr<Stitcher> stitcher = Stitcher::create(Stitcher::SCANS, try_use_gpu);
    stitcher->setFeaturesFinder(Ptr<cv::detail::OrbFeaturesFinder>());
    Stitcher::Status status = stitcher->stitch(imgs, pano); // crash with error from above

**Comment by mark-bragg** [comment]
@alalek, what does incomplete tag mean? Also, are there certain aspects of OpenCV that are just broken in iOS?

**Comment by mark-bragg** [comment]
@alalek, this should be a bug; using a basic feature causes a crash in iOS. Is there any estimate on this?

**Comment by hrnr** [comment]
When reporting crashes you should provide at least basic debug info, backtrace etc.

From the code snippet you provided it seems to me that you are passing nullptr to Stitcher as featuresFinder. Why? FeaturesFinder can't be disabled this way, it is a necessary step in the pipeline The crash is then expected when Stitcher tries to call FeaturesFinder, but it has been set to nullptr by you.

We could add check for nullptr, but I think it is better to crash when user explicitly passes nullptr to Stitcher to avoid silent errors.
