### ISSUE TITLE
SystemError: <built-in function NMSBoxes> returned NULL without setting an error

### ISSUE THREAD

**Issue by LZQthePlane** [opencv/opencv#12789]
- OpenCV => 3.4.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I am trying test [object_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py),   
the bug happens when I run `indices = cv.dnn.NMSBoxes(boxes, confidences, confThreshold, nmsThreshold)`

the params are like:
 - **boxes**:  <class 'list'>: [[267, 43, 244, 161], [219, 63, 198, 204], [197, 56, 38, 89], [41, 71, 60, 175], [-3, 130, 62, 206], [177, 163, 101, 181]]
 - **confidences**: <class 'list'>: [0.876075, 0.7604607, 0.9908975, 0.99148935, 0.6421119, 0.98622924]
 - **confThreshold** = 0.5  
 - **nmsThreshold** = 0.4 

Then I get the error: `SystemError: <built-in function NMSBoxes> returned NULL without setting an error`, so can anyone help me out ?

**Comment by mhaghighat** [comment]
Please make sure the data type of the boxes is _int_ and the type of the confidences is _float_.
I had the same error because the types of my confidences were _numpy.float32_.

**Comment by EricThomson** [comment]
> I had the same error because my confidences were of type _numpy.float32_.

This should be fixed, given that numpy arrays are pretty much baked into opencv in python from the ground up.
