### ISSUE TITLE
decolor example in cpp/tutorial, still crash at grad_system

### ISSUE THREAD

**Issue by fcyella** [opencv/opencv#12790]
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => ARM 64
- Compiler => GCC

##### Detailed description

I passed the input image with lena.jpg, got the following error.
 error: (-215:Assertion failed) !fixedSize() || ((Mat*)obj)->size.operator()() == _sz in function 'create'

##### Steps to reproduce
compile the sample/cpp/tutorial_code/decolorization/decolor.cpp
run the binary.

**Comment by berak** [comment]
hello, @fcyella , there were some "issue template" bullet points to fill in, like opencv version, os, compiler used. could kindly add those to your issue ?

(can't reproduce the problem with current master branch)

oh, btw, it's `samples/cpp/tutorial_code/photo/decolorization/decolor.cpp`

**Comment by fcyella** [comment]
I cross compile opencv 4.0 alpha for arm 64 platform,  got this failure. 
I will try the same binary on ubuntu. Thanks for your feedback. Will update this ticket later.

**Comment by berak** [comment]
@fcyella , can you take a look, if you have [this patch](https://github.com/opencv/opencv/pull/12169/files) ? 

it was added august 7. and probably merged into master 2 weeks later.

**Comment by fcyella** [comment]
I have a double check, with master branch, the case run well on my 64bit ubuntu. I suspect it's related to the GCC version (7.3.0) on my embedded board.  I am trying to find out the root cause.

**Comment by fcyella** [comment]
and @berak , I have this patch in the source code.

**Comment by fcyella** [comment]
I made a mistake during compiling the case on my embedded board.  Thanks a lot for paying attention and quick response.
