### ISSUE TITLE
OpenCV build configuration of released prebuild binaries

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#12801]
In every release you provide prebuild binaries at https://github.com/opencv/opencv/releases

Is there a configuration file where i can see the cmake configuration that was used to build a specific opencv binary? Do you always just build the default configuration or do you change parameters like 
CPU_BASELINE=AVX2 etc? To me it is not clear.

Would it make sense to provide the log of the cmake generator/configurator to it can be easily seen what configuration the prebuild binaries have?

**Comment by alalek** [comment]
All release builds are prepared by OpenCV CI. Builds for winpack 3.4.3 and its logs are [here](http://pullrequest.opencv.org/buildbot/builders/3_4_winpack_controller/builds/142).

Also there is `getBuildInformation()` function and `opencv_version` utility in the package.
