### ISSUE TITLE
opencv 3.4.3 can't use cvsaveimage API

### ISSUE THREAD

**Issue by laizewei** [opencv/opencv#12818]
- OpenCV => 3.4.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
opencv 3.4.3, 3.4.1, 4.0 can't use cvsaveimage API
example:
  IplImage* imgSrc = cvLoadImage("F:/123.png", CV_LOAD_IMAGE_COLOR);
	cvSaveImage("F:/222.jpg", imgSrc);

**Comment by hawkWei07** [comment]
@alalek I meet the trouble too;
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.3) /tmp/opencv-20181001-83194-s618mv/opencv-3.4.3/modules/core/src/matrix_wrap.cpp:800: error: (-215:Assertion failed) (flags & FIXED_TYPE) != 0 in function 'type'

How can I fix it ?

I installed the opencv by brew and compile my project in Xcode.

**Comment by hawkWei07** [comment]
@laizewei Have you fixed this problem ?
