### ISSUE TITLE
4D Mat/blob for dnn

### ISSUE THREAD

**Issue by Siddhant24** [opencv/opencv#12821]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => Android Studio

##### Detailed description

I am using DNN module of OpenCV JAVA for android to run a Caffe model.
My prototxt file has this input layer
input: "facegrid"
input_dim: 256 (batch size)
input_dim: 625
input_dim: 1
input_dim: 1

So basicall I have to create a blob with 625 channels.
How do I create a 4D blob to pass it as an input? Also how do I see the dimensions of the blov that blobFromImages outputs?

**Comment by dkurt** [comment]
@Siddhant24, to determine shapes, you can compute it by steps:
```java
(i > 0 ? step1(i - 1) : total()) / step1(i);
```
To workaround blob creation, you may prepare a List of 256 Mat objects where an every Mat has 1x1 size (rows x cols) and 625 channels. Then call `blobFromImages`. However it make sense to make it easier.

**Comment by Siddhant24** [comment]
I solved this problem by editing the prototxt file. This layer was followed by a 'Flatten' layer so 1x625x1x1 and 1x1x625x1 doesn't make any difference. But yeah it should be possible to create a blob of any channels.

**Comment by dkurt** [comment]
@Siddhant24, You may also try the changes from https://github.com/opencv/opencv/pull/12938
