### ISSUE TITLE
Video capture resolution stuck in Windows MSMF backend

### ISSUE THREAD

**Issue by nerdfever** [opencv/opencv#12822]
Open CV 3.4.2
Windows 64 Bit
Python 3.6

See http://answers.opencv.org/question/195388/video-capture-resolution-issue-on-windows/

The poster found the problem on a Logitech HD Webcam C615; I'm seeing the same thing on a Logitech QuickCam Pro 9000.

On Windows 10 x64 with the MSMF backend, if you change video resolution like so:

```
camera.set(cv2.CAP_PROP_FRAME_WIDTH, x)
camera.set(cv2.CAP_PROP_FRAME_HEIGHT, y)
```

The result is that you'll get a frame of size x,y pixels (if x,y is one of the resolutions supported by the webcam), but that image is in fact a 640x480 image rescaled to size x,y.

The poster at answers.opencv.org above claims that on the DirectShow backend it appears to work correctly (I've only tried the MSMF backend so far).

For example, below are 3 images captured identically at 640x480, 960x720, and 1600x1200 resolution with the MSMF backend from a Logitech QuickCam Pro 9000 (all those are reported by the camera as supported modes). It's pretty obvious they were all captured at the same resolution, then scaled.

![20181013_143012_1 640x480](https://user-images.githubusercontent.com/9833299/46908971-00c6b080-cef9-11e8-887c-e0f7610e8684.png)

![20181013_142952_1 960x720](https://user-images.githubusercontent.com/9833299/46908973-04f2ce00-cef9-11e8-989a-e2bad3263952.png)

![20181013_143219_1 1600x1200](https://user-images.githubusercontent.com/9833299/46908980-18059e00-cef9-11e8-9c0e-b2ff118403dc.png)

**Comment by nerdfever** [comment]
I confirm that switching to the DirectShow backend fixes this.

It's the MSMF backend that has this problem.

**Comment by PhilLab** [comment]
I am experiencing the same with `OpenCV 3.4.3`. The default `cv::VideoCapture::open() ` selects MSMF backend and is not able to change the resolution.

```
Video I/O:
  Video for Windows:           YES
  DC1394:                      NO
  FFMPEG:                      YES (prebuilt binaries)
    avcodec:                   YES (ver 57.107.100)
    avformat:                  YES (ver 57.83.100)
    avutil:                    YES (ver 55.78.100)
    swscale:                   YES (ver 4.8.100)
    avresample:                YES (ver 3.7.0)
  GStreamer:                   NO
  DirectShow:                  YES
  Media Foundation:            YES
```

**Comment by Python-Regius** [comment]
I can confirm that this is still an issue using OpenCV 4.1.2 and that switching to the DirectShow back-end resolves the issue.

Also if you try using a non 4:3 aspect ratio width and height you will get black boarders.

**Comment by dmardanbeigi** [comment]
This issue has not been resolved and it still exists with MSMF backend.

**Comment by mshabunin** [comment]
@dmardanbeigi , please provide more details: platform, OpenCV version, camera model, reproducer code.

Please note that the fix for this issue is available only on _master_ and _3.4_ branches and has not been released yet.

**Comment by dmardanbeigi** [comment]
Isn't 3.4 branch already included in opencv-python 4.0?

It only works with DSHOW backend and not MSMF.
Python 3.7.4 (64 bit)
Windows 10 
opencv-python==4.0.0.21
opencv-contrib-python==4.0.0.21

Camera: I tried on both a Quanta UVC camera and the webcam on my HP Spectre x360 (I don't know the details). The resolutions is supported by both cameras.

Here is the code I use:
```python
import cv2
_capture = cv2.VideoCapture(0)# cv2.CAP_DSHOW)
print(_capture.getBackendName())
size=(1920, 1080)
print(_capture.set(cv2.CAP_PROP_FRAME_WIDTH, size[0]))
print(_capture.set(cv2.CAP_PROP_FRAME_HEIGHT, size[1]))
_ret, img = _capture.read()
_ret = True
cv2.namedWindow("img")
cv2.resizeWindow('img', size[0],size[1])
cv2.imshow("img", img)
while _ret:
    _ret, img = _capture.read()
    key_code = cv2.waitKey(1)
    if (key_code == 27) or (key_code == ord('q')):
        break
    cv2.imshow("calibration", img)
```

**Comment by alalek** [comment]
> Isn't 3.4 branch already included in opencv-python 4.0?

Not exactly.
See release dates instead: https://github.com/opencv/opencv/releases

---

Order of changing capturing parameters should be:
- width
- height
- fps
- [optional] native backend modes / formats.

You have missed fps.
For MSMF mode responds for H/W acceleration.

**Comment by mshabunin** [comment]
`opencv-python==4.0.0.21` is an old version, latest version in pip is [4.2.0.34](https://pypi.org/project/opencv-python/) The fix for this issue have not been included there yet. You should either build OpenCV for python by yourself (tag 4.3.0) either wait until new version will be available on pip.

**Comment by dmardanbeigi** [comment]
Thanks!
