### ISSUE TITLE
Opencv failed to run 26 tests with release configuration and debug configuration

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#12833]
Environment:
 Windows Server 2016 + VS2017 opencv master branch latest srouce code

Opencv failed to run 26 tests with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance!

 1.git clone https://github.com/opencv/opencv D:\OpenCV\src
 2.git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
 3.Open a VS 2017 x86 prompt and browse to D:\OpenCV
 4.mkdir build_x86 && pushd build_x86
 5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
 6.msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
 7.pushd build_x86\bin\Release
 8. opencv_test_objdetect.exe --gtest_filter=-Objdetect_HOGDetector_Strict.accuracy:Objdetect_QRCode.regression/0:Objdetect_QRCode.regression/1:Objdetect_QRCode.regression/5:Objdetect_QRCode.regression/4

Note:
 OPENCV_TEST_DATA_PATH env variable has been set and point to <opencv_extra>/testdata.

The whole log file please see attachment.
[log_x86_test_7.log](https://github.com/opencv/opencv/files/2477808/log_x86_test_7.log)

TestErrorMessage:
[----------] Global test environment tear-down
[==========] 31 tests from 5 test cases ran. (7078 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 26 tests, listed below:
[  FAILED  ] Objdetect_QRCode.regression/2, where GetParam() = "version_1_right.jpg"
[  FAILED  ] Objdetect_QRCode.regression/3, where GetParam() = "version_1_up.jpg"
[  FAILED  ] Objdetect_QRCode.regression/6, where GetParam() = "version_2_left.jpg"
[  FAILED  ] Objdetect_QRCode.regression/7, where GetParam() = "version_2_right.jpg"
[  FAILED  ] Objdetect_QRCode.regression/8, where GetParam() = "version_2_up.jpg"
[  FAILED  ] Objdetect_QRCode.regression/9, where GetParam() = "version_2_top.jpg"
[  FAILED  ] Objdetect_QRCode.regression/10, where GetParam() = "version_3_down.jpg"
[  FAILED  ] Objdetect_QRCode.regression/11, where GetParam() = "version_3_left.jpg"
[  FAILED  ] Objdetect_QRCode.regression/12, where GetParam() = "version_3_right.jpg"
[  FAILED  ] Objdetect_QRCode.regression/13, where GetParam() = "version_3_up.jpg"
[  FAILED  ] Objdetect_QRCode.regression/14, where GetParam() = "version_3_top.jpg"
[  FAILED  ] Objdetect_QRCode.regression/15, where GetParam() = "version_4_down.jpg"
[  FAILED  ] Objdetect_QRCode.regression/16, where GetParam() = "version_4_left.jpg"
[  FAILED  ] Objdetect_QRCode.regression/17, where GetParam() = "version_4_right.jpg"
[  FAILED  ] Objdetect_QRCode.regression/18, where GetParam() = "version_4_up.jpg"
[  FAILED  ] Objdetect_QRCode.regression/19, where GetParam() = "version_4_top.jpg"
[  FAILED  ] Objdetect_QRCode.regression/20, where GetParam() = "version_5_down.jpg"
[  FAILED  ] Objdetect_QRCode.regression/21, where GetParam() = "version_5_left.jpg"
[  FAILED  ] Objdetect_QRCode.regression/22, where GetParam() = "version_5_right.jpg"
[  FAILED  ] Objdetect_QRCode.regression/23, where GetParam() = "version_5_up.jpg"
[  FAILED  ] Objdetect_QRCode.regression/24, where GetParam() = "version_5_top.jpg"
[  FAILED  ] Objdetect_QRCode.regression/25, where GetParam() = "russian.jpg"
[  FAILED  ] Objdetect_QRCode.regression/26, where GetParam() = "kanji.jpg"
[  FAILED  ] Objdetect_QRCode.regression/27, where GetParam() = "link_github_ocv.jpg"
[  FAILED  ] Objdetect_QRCode.regression/28, where GetParam() = "link_ocv.jpg"
[  FAILED  ] Objdetect_QRCode.regression/29, where GetParam() = "link_wiki_cv.jpg"

26 FAILED TESTS

**Comment by alalek** [comment]
> OpenCV tests: Can't find required data file: qrcode/version_2_up.jpg

You must use up-to-date and synchronized `opencv_extra` repository.
