### ISSUE TITLE
Should be return false

### ISSUE THREAD

**Issue by aleksey-nikolaev** [opencv/opencv#12834]
https://github.com/opencv/opencv/blob/5115e5decbef657ceb234d21ad8e8e33a6c96ca4/modules/videoio/src/cap_v4l.cpp#L1746

**Comment by alalek** [comment]
Nice catch!

Feel free to provide Pull Request onto 3.4 branch. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).
