### ISSUE TITLE
Unable to Generate a config file for ssd_mobilenet_v1_fpn_coco tensorflow model

### ISSUE THREAD

**Issue by Lahirevinod** [opencv/opencv#12835]
##### System information (version)

- OpenCV => :3..4.3 / tried 4.0 alpha as well
- Operating System / Platform => :ubuntu 16

##### Detailed description

 I successfully transported some of  ssd model trained in tensorflow and listed [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) as per instruction given [here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API). I tried generating config file for ssd_mobilenet_v1_fpn_coco model.I am getting error 
```
  File "/home/admin-pc/object_detection_eval/obj_det/tf_text_graph_ssd.py", line 30, in createSSDGraph
    ssd_anchor_generator = config['anchor_generator'][0]['ssd_anchor_generator'][0]
KeyError: 'ssd_anchor_generator'
```
when i checked there is multiple_anchor_generator rather than ssd_anchor_generator with different hyper param . Should i have to modify tf_text_graph_ssd.py , will this serve purpose?. Any specific suggestions or help appreciated . Thanks in advance 
 
##### Steps to reproduce

 ```
python tf_text_graph_ssd.py --input /path/to/model.pb --config /path/to/pipeline.config  --output 'graph.pbtxt' 


```
-->

**Comment by abhiTronix** [comment]
@Lahirevinod Yup similar error with "_ssd_resnet_50_fpn_coco_". Any ideas how to solve it?
