### ISSUE TITLE
Dataset used for res10_300x300_ssd_iter_140000_fp16.caffemodel

### ISSUE THREAD

**Issue by vikasguptaiisc** [opencv/opencv#12840]
I would like to know the source of the dataset used for the DNN based Face Detector corresponding to  the model - res10_300x300_ssd_iter_140000_fp16.caffemodel.

**Comment by alalek** [comment]
Some description is [here](https://github.com/opencv/opencv/blob/3.4.3/samples/dnn/face_detector/how_to_train_face_detector.txt).
FP16 is just quantinized version of FP32 model.

**Comment by vikasguptaiisc** [comment]
I had read that, its not very clear about the source of the dataset. Did it use any standard dataset like LFW / Face Scrub / COCO etc? How did they find the annotations?

**Comment by bbudescu** [comment]
it would be kinda useful to at least know some performance metrics on some relevant dataset before downloading it (e.g. WIDER Face)
