### ISSUE TITLE
disable ADE Framework

### ISSUE THREAD

**Issue by ebyaa** [opencv/opencv#12856]
Currently trying to cross compile master-branch, with g++-4.8-arm-linux-gnueabihf

But tool-chain doesn't support ADE,

> [24%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1c/sources/ade/source/alloc.cpp.o
In file included from /home/atmark/opencv/platforms/linux/build/3rdparty/ade/ade-0.1.1c/sources/ade/include/ade/util/math.hpp:14:0,
                from /home/atmark/opencv/platforms/linux/build/3rdparty/ade/ade-0.1.1c/sources/ade/source/alloc.cpp:16:
/home/atmark/opencv/platforms/linux/build/3rdparty/ade/ade-0.1.1c/sources/ade/include/ade/util/assert.hpp:27:1: error: expected unqualified-id before ‘[’ token
/home/atmark/opencv/platforms/linux/build/3rdparty/ade/ade-0.1.1c/sources/ade/include/ade/util/assert.hpp:29:1: error: expected unqualified-id before ‘[’ token
/home/atmark/opencv/platforms/linux/build/3rdparty/ade/ade-0.1.1c/sources/ade/include/ade/util/assert.hpp:86:1: error: expected unqualified-id before ‘[’ token
make[2]: *** [modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1c/sources/ade/source/alloc.cpp.o]

Editing ADE source to remove [[noreturn]] is far from enough.
I dug the cmakelist but couldn't find an ADE related flag, is there anyway to build opencv4 without ADE ?

**Comment by alalek** [comment]
There is [build](http://pullrequest.opencv.org/buildbot/builders/master_ARMv7-lin/builds/10609) with Ubuntu 14.04 cross-compilation via GCC 4.8.4.

Try this:
```
cmake -DBUILD_opencv_gapi=OFF ...
```

**Comment by ebyaa** [comment]
> cmake -DBUILD_opencv_gapi=OFF -DWITH_PROTOBUF=OFF -DWITH_CUDA=OFF -DENABLE_PRECOMPILED_HEADER=NO -DBUILD_TEST=OFF -DENABLE_NEON=YES -DBUILD_PERF_TEST=OFF -DBUILD_EXAMPLE=OFF -DCMAKE_TOOLCHAIN_FILE=../arm-gnueabi.toolchain.cmake ../../..
-- Could NOT find PythonInterp: Found unsuitable version "2.7.3", but required is at least "3.2" (found /usr/bin/python)
-- Looking for ccache - not found
-- FP16 is not supported by C++ compiler
-- OpenCV disables pkg-config to avoid using of host libraries. Consider using PKG_CONFIG_LIBDIR to specify target SYSROOT
-- Found ZLIB: /usr/arm-linux-gnueabihf/lib/libz.so (found suitable version "1.2.7", minimum required is "1.2.3")
-- Found ZLIB: /usr/arm-linux-gnueabihf/lib/libz.so (found version "1.2.7")
-- Found OpenEXR: /usr/arm-linux-gnueabihf/lib/libIlmImf.so
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- Can't find ffmpeg - 'pkg-config' utility is missing
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find Atlas (missing:  Atlas_CBLAS_INCLUDE_DIR Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY)
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse3.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.ssse3.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse4_1.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse4_2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.avx.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.fp16.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.avx2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin256.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/corner.avx.cpp
-- Excluding from source files list: modules/imgproc/src/filter.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/imgwarp.sse4_1.cpp
-- Excluding from source files list: modules/imgproc/src/resize.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/resize.sse4_1.cpp
-- Excluding from source files list: modules/features2d/src/fast.avx2.cpp
-- Excluding from source files list: modules/calib3d/src/undistort.avx2.cpp
-- Excluding from source files list: modules/objdetect/src/haar.avx.cpp
--
-- General configuration for OpenCV 4.0.0-pre =====================================
--   Version control:               3.4.3-595-g5339ef3
--
--   Platform:
--     Timestamp:                   2018-10-17T01:38:31Z
--     Host:                        Linux 3.2.0-6-amd64 x86_64
--     Target:                      Linux 1 arm
--     CMake:                       3.6.3
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
--
--   CPU/HW features:
--     Baseline:                    NEON
--       requested:                 DETECT
--       required:                  NEON
--       disabled:                  VFPV3
--
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/arm-linux-gnueabihf-g++  (ver 4.6.3)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/arm-linux-gnueabihf-gcc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfpu=neon -mfp16-format=ieee -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
--
--   OpenCV modules:
--     To be built:                 calib3d core features2d flann highgui imgcodecs imgproc java_bindings_generator ml objdetect photo python_bindings_generator shape stitching superres ts video videoio videostab
--     Disabled:                    gapi world
--     Disabled by dependency:      -
--     Unavailable:                 dnn java js python2 python3 viz
--     Applications:                tests perf_tests apps
--     Documentation:               NO
--     Non-free algorithms:         NO
--
--   GUI:
--     GTK+:                        NO
--
--   Media I/O:
--     ZLib:                        /usr/arm-linux-gnueabihf/lib/libz.so (ver 1.2.7)
--     JPEG:                        /usr/arm-linux-gnueabihf/lib/libjpeg.so (ver 80)
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         /usr/arm-linux-gnueabihf/lib/libpng.so (ver 1.2.49)
--     TIFF:                        /usr/arm-linux-gnueabihf/lib/libtiff.so (ver 42 / 3.9.6)
--     JPEG 2000:                   /usr/arm-linux-gnueabihf/lib/libjasper.so (ver 1.900.1)
--     OpenEXR:                     /usr/arm-linux-gnueabihf/lib/libImath.so /usr/arm-linux-gnueabihf/lib/libIlmImf.so /usr/arm-linux-gnueabihf/lib/libIex.so /usr/arm-linux-gnueabihf/lib/libHalf.so /usr/arm-linux-gnueabihf/lib/libIlmThread.so (ver Unknown)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
--
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   NO
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
--
--   Parallel framework:            pthreads
--
--   Trace:                         YES (built-in)
--
--   Other third-party libraries:
--     Lapack:                      NO
--     Custom HAL:                  YES (carotene (ver 0.0.1))
--
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/atmark/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
--
--   Python (for build):            /usr/bin/python2.7
--
--   Install to:                    /home/atmark/opencv/platforms/linux/build/install
-- -----------------------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /home/atmark/opencv/platforms/linux/build

still block on the [[noreturn]] in 3rdparty/ade/ade-0.1.1c/sources/ade/include/ade/util/assert.hpp

**Comment by zhjc** [comment]
cmake -DWITH_ADE=OFF...
