### ISSUE TITLE
why the theta_d caculate like this?

### ISSUE THREAD

**Issue by somehower** [opencv/opencv#12862]
https://github.com/opencv/opencv/blob/5339ef3004e5005f5ff3dadb96b2dc3642bcbd3e/modules/calib3d/src/fisheye.cpp#L381

Is there any formula for it?
In my understanding, theta_d = atan(sqrt(pw[0]*pw[0] + pw[1]*pw[1])). 
I don't know which one is right. I'm glad if anyone can answer this question.

**Comment by alalek** [comment]
There is link on related article: #9742
