### ISSUE TITLE
Is there a pip/conda package of OpenCv with Cuda enabled ?

### ISSUE THREAD

**Issue by gautamkmr** [opencv/opencv#12861]
Is there a pip/conda package of OpenCv with Cuda enabled ?

**Comment by alalek** [comment]
CUDA bindings are not supported in OpenCV 3.x. Some work is done by @cv3d for OpenCV 4.x (master branch).
There is no official package for this (and no plans to do / support this).

**Comment by cv3d** [comment]
@gautamkmr If you are eager enough, then I suggest you make and maintain such package(s) yourself.
Eventually, you would gain some momentum and good team to help.

CUDA is a proprietary language with limited devices supported, therefore, OpenCV team decided to focus on OpenCL and moved CUDA modules to the contrib repo.

**Comment by gautamkmr** [comment]
@cv3d  Thanks for the reply. AFAIK building OpenCV from source still has an option to use CUDA for it. Correct me if I am wrong.

**Comment by cv3d** [comment]
Sure it does, you just need setting CMake variables to something like `-DOPENCV_EXTRA_MODULES_PATH=/path/to/opencv_contrib/modules` and `-DWITH_CUDA=ON`.
And as @alalek pointed out, if you compile the master branch, you would be able to utilize several CUDA functionalities from within Python.

**Comment by gautamkmr** [comment]
@cv3d  Thank you again.

I am already using 'with_cuda=on' functionality and works well but If I use frameworks like caffe2 or something along with TensorFlow then it becomes challenging to have opencv system wide installation. 

I have separate conda environment for TF and Caffe2 frameworks. Having an opencv package with Cuda support will be very useful for user like me who uses multiple conda environment. 

I already see 4.0.0-beta out, once 4.0.0 gets release will I have cuda supported opencv conda package in opencv channel  https://anaconda.org/anaconda/opencv ?

**Comment by alalek** [comment]
> opencv conda package
> https://anaconda.org/anaconda/opencv

We don't maintain this.

> cuda supported

Definitely 'No' due:
- dependency on CUDA runtime (including licensing/legal issues)
- size of binaries (due unknown compute capability target)

> to have opencv system wide installation

Just not use system wide OpenCV installation - it is not required to run OpenCV.

**Comment by gautamkmr** [comment]
@alalek  I am little confuse here.  

**Just not use system wide OpenCV installation - it is not required to run OpenCV.**
What do you mean by that ?  If my program uses OpenCV then it will be faster if I run it on GPU. You also have benchmark here https://opencv.org/platforms/cuda.html

So what do you suggest in that case.

**Comment by gautamkmr** [comment]
> OpenCV supports multiple installations, including installations for different Python virtual environments.  

Are you saying I should go inside each environment and run below command? 

```
cmake -D BUILD_opencv_gpu=OFF -D WITH_EIGEN=ON -D WITH_TBB=ON \
 -D WITH_CUDA=ON -D WITH_1394=OFF \
 -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
 -D CMAKE_INSTALL_PREFIX=/usr/local ..
make -j $(($(nproc) + 1))
make installa
```
?

**Comment by gautamkmr** [comment]
@cv3d 
"CUDA is a proprietary language with limited devices supported, therefore, OpenCV team decided to focus on OpenCL and moved CUDA modules to the contrib repo."

Is there a OpenCV on OpenCL  pip /conda package available?

**Comment by cv3d** [comment]
Related #6078
You do not need that, as OpenCL support (T-API) is enabled by default.
Just use `UMat` as a wrapper for your NumPy arrays, and OpenCL shall tick in whenever possible.

Kindly stop asking questions here, and direct any further ones to: http://answers.opencv.org/
