### ISSUE TITLE
Opencv 4.0.0-beta - Add Android pack to release page

### ISSUE THREAD

**Issue by crazyhappygame** [opencv/opencv#12872]
Opencv 4.0.0-beta - Please add Android pack to release page.

In the latest ndk 18 there is no gcc - only clang. 
I think that for opencv 4.0 release two Android packs should be provided: clang and gcc.

**Comment by alalek** [comment]
1. GCC -> Clang: incompatible changes (try [this config](https://github.com/opencv/opencv/blob/4.0.0-beta/platforms/android/ndk-17.config.py) to build OpenCV binaries).
2. Need to migrate on latest Android SDK too (completely different build tools and build process): #8460

There are no Android releases expected until that.

**Comment by crazyhappygame** [comment]
@alalek I see that 3.4.4 is 4.0.0 released. Congratulation!
Could you provide steps how build properly opencv 3.4.4 with clang and ndk16?
I need only to build "core and imgproc".

p.s.
Could you add information on https://opencv.org about used gcc compiler and ndk vor for Android 3.4.4 release?
Latest ndk18b removed gcc https://github.com/android-ndk/ndk/wiki/Changelog-r18
clang and gcc binary are incompatible...

**Comment by alalek** [comment]
Try to build with configuration file from this PR: #12323 

> used gcc compiler and ndk vor for Android 3.4.4 

Take a look on this [build](http://pullrequest.opencv.org/buildbot/builders/3_4_pack-android/builds/212) (logs of step 4).

> clang and gcc binary are incompatible

You need to build SDK yourself with NDK16 (at least native libopencv_java.so, other parts require old Android build system) to use with modern Android Studio.

**Comment by ofirkris** [comment]
is V4.0.0 planned to be released to Android soon?
