### ISSUE TITLE
Parse error at 97 while configuring in CMake 3.12.3

### ISSUE THREAD

**Issue by zitgost** [opencv/opencv#12883]
##### System information (version)

- OpenCV => 3.4.3
- CMake => 3.12.3
- Operating System / Platform => OSX 10.13.6
- Compiler => clang(?)

##### Detailed description

When configuring my OpenCV project, I get the following error:
`CMake Error at /Library/Frameworks/opencv2.framework/OpenCVConfig.cmake:96:
  Parse error.  Expected a command name, got unquoted argument with text
  "@CUDA_CONFIGCMAKE@".
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)`

##### Steps to reproduce
I downloaded the OpenCV ios pack and dragged the framework to my User Library. I installed CMake using the .dmg. My most recent error was that there was no OpenCVConfig.cmake file in my OpenCV_DIR path, so I added the one I found here on GitHub (without the ".in" suffix) to the folder Library/Frameworks/opencv2.framework.

my project directory:
`/OpenCV_Setup`
`----/OpenCV_Setup`
`--------/main.cpp`
`----/OpenCV_Setup.xcodeproj`
`----/CMakeLists.txt`

Here is my CMakeLists.txt:
`cmake_minimum_required(VERSION 3.0)`
`project( DisplayImage )`
`find_package( OpenCV REQUIRED )`
`target_link_libraries(MY_TARGET_NAME ${OpenCV_LIBS})`
`add_executable( DisplayImage DisplayImage.cpp)`
`target_link_libraries( DisplayImage ${OpenCV_LIBS})`

I have tried it with minimum required version as 3.12 as well, with the same result.

I've seen that some people solved similar errors by detecting non-printing characters using a hex editor, and while I can see the hex version of this code in Sublime Text... understanding it is beyond me at the moment.

I'm looking forward to starting to study OpenCV as soon as possible. I'll keep trying to figure this out on my own as well, but any help would be greatly appreciated.

**Comment by alalek** [comment]
> added the one I found here on GitHub (without the ".in" suffix)

This will not work.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
