### ISSUE TITLE
imread much slower to read JPEG when migrating from 3.1 to 3.4.3

### ISSUE THREAD

**Issue by guillaume-tgl** [opencv/opencv#12898]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Android ARMv7
- Compiler => Using official binaries

##### Detailed description

I previously used OpenCV 3.1 that I manually compiled to use libjpeg-turbo. When I switched to OpenCV 3.4.3, I saw that libjpeg-turbo was now used instead of libjpeg so I used the official Android binaries for both OpenCV and 3rd party libraries.

However, reading a JPEG image from disk went from 360ms to 800ms (with `IMREAD_COLOR`) and from 160ms to 300ms (with `IMREAD_GRAYSCALE`). These images don't have any exif orientation.

##### Steps to reproduce

```.cpp
cv::imread(path, IMREAD_COLOR)
```

**Comment by alalek** [comment]
SIMD is disabled for now in builtin libjpeg-turbo code.
See #12115
