### ISSUE TITLE
setMouseCallback doc in python

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#12899]
There is no doc for [setmousecallback ](https://docs.opencv.org/master/d7/dfc/group__highgui.html#ga89e7806b0a616f6f1d502bd8c183ad3e)in python. I think that the reason is  setMousecallback python wrapper is in cv2.cpp. Is it possible to add a note in c++ doc?

same for [createTrackBar](https://docs.opencv.org/trunk/d7/dfc/group__highgui.html#gaf78d2155d30b728fc413803745b67a9b)

**Comment by LaurentBerger** [comment]
Is it possible to give an answer to this issue ? May be add a reference in doc to a python sample could sove it
@sturkmen72  @berak

**Comment by berak** [comment]
oh, btw, imho we need to change all those in highui.hpp:

    [__Qt Backend Only__] winname can be empty (or NULL) if the trackbar is attached to the control

for 4.0, since it's using std::string now, which must not be 0
