### ISSUE TITLE
Can not release Webcam properly with cap.release()

### ISSUE THREAD

**Issue by yiyunluo07** [opencv/opencv#12900]
Hello, my OpenCV version is 3.4.3 and platform is Linux Ubuntu 16.04, using C++.
I'm trying to write a program which can control the camera on or off while the program is running.
In order to make the camera off, I used the function cap.release(). When the camera should be on, then use cap.open() with gstreamer.
The problem is, sometimes it works well, the camera can be well controlled for on or off. But sometimes the camera can not be properly released after using cap.release(). When I try to reopen the camera again, it shows:

GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy

And the camera cannot be opened again...
I have tried with both camera HD Pro Webcam C920 and RealSence 435, either of them can be controlled in the right way sometimes....

How can I solve the problem?

**Comment by yjfncu** [comment]
I also meet this problem

**Comment by alalek** [comment]
Try to:
- disable GStreamer backend
- use `CAP_V4L2` in `.open()` call

**Comment by yiyunluo07** [comment]
> Try to:
> 
>     * disable GStreamer backend
> 
>     * use `CAP_V4L2` in `.open()` call

Did you mean cap.open("...", cv::CAP_V4L2")?
I have tried with it, the complete code is: 
cap.open("v4l2src device=/dev/video0 ! video/x-raw, format=(fourcc)YUYV, width=1280, height=720, framerate=30/1 ! appsink", cv::CAP_V4L2)
But this code cannot open the camera at all....

**Comment by yiyunluo07** [comment]
> `cap.open("/dev/video0", CAP_V4L2);`

But our program must use GStreamer to open capture....... there's no other solution any more?

**Comment by alalek** [comment]
At first we need to determine where is problem comes from.
GStreamer itself uses V4L internally: `v4l2src`

**Comment by alalek** [comment]
In other words, we need complete minimal reproducer.

**Comment by yiyunluo07** [comment]
well, with cap.open("/dev/video0", CAP_V4L2) the camera can be opened and closed rightly... but I still wanna open the camera with gstreamer string in cap.open() instead of /dev/video0, any suggestion?
