### ISSUE TITLE
MJPG format as input in videocapture results in segmentation fault in OpenCV.

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#12917]
##### System information (version)

- OpenCV => 4.0.0 - pre(Latest - master) compiled with GSTREAMER support.
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Gstreamer =>  GStreamer 1.14.1
- Libv4L/Libv4L2 => 1.14.2
- Compiler => gcc version 7.3.0 with python 2.7.15rc1
- Programming Language => Python

##### Detailed description
**My UVC camera displayed as `/dev/video1` below:**

``` 
v4l2-ctl --list-devices 

HP Truevision HD: HP Truevision (usb-0000:00:10.0-1):
	/dev/video0
USB2.0 PC CAMERA (usb-0000:00:10.0-3):
	/dev/video1
```

**have only one valid format i.e. _MJPG_ :** 

```
v4l2-ctl -d /dev/video1 --list-formats-ext

ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
		Size: Discrete 640x480
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.017s (60.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
```

 **I'm trying to open its output in OpenCV through Gstreamer pipeline using python as:**
``` 
import cv2

print cv2.__version__
camera = cv2.VideoCapture('v4l2src device=/dev/video1 ! jpegdec ! videoconvert ! appsink', cv2.CAP_GSTREAMER )
while(1):
    retval, im = camera.read()
    cv2.imshow("image", im)
    k = cv2.waitKey(1) & 0xff
    if k == 27:
        break
camera.release() 
```
**When executed, this results in :** 
```
4.0.0-pre
Segmentation fault (core dumped)

```

**But on the other hand when executed in terminal directly. This executed successfully (with proper display output):**

```
gst-launch-1.0  v4l2src device=/dev/video1 ! jpegdec  ! videoconvert ! autovideosink -v


Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
/GstPipeline:pipeline0/GstV4l2Src:v4l2src0.GstPad:src: caps = image/jpeg, width=(int)640, height=(int)480, framerate=(fraction)60/1, pixel-aspect-ratio=(fraction)1/1, colorimetry=(string)NULL, interlace-mode=(string)progressive
/GstPipeline:pipeline0/GstJpegDec:jpegdec0.GstPad:sink: caps = image/jpeg, width=(int)640, height=(int)480, framerate=(fraction)60/1, pixel-aspect-ratio=(fraction)1/1, colorimetry=(string)NULL, interlace-mode=(string)progressive
/GstPipeline:pipeline0/GstJpegDec:jpegdec0.GstPad:src: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
/GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:src: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
/GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0.GstGhostPad:sink.GstProxyPad:proxypad0: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
/GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage.GstPad:sink: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
/GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0.GstGhostPad:sink: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
/GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:sink: caps = video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)1:4:0:0, framerate=(fraction)60/1
ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage: Output window was closed
Additional debug info:
xvimagesink.c(555): gst_xv_image_sink_handle_xevents (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage
Execution ended after 0:00:07.060640506
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```
**Also Working smoothly on Guvcview :** 
_Verbose Output_ : 
[guvcview_verbose.txt](https://github.com/opencv/opencv/files/2509885/guvcview_verbose.txt)

#### Error Debugged output:
Strace output log:
[strace.txt](https://github.com/opencv/opencv/files/2509752/strace.txt)

GDB output log:
[gdb_log.txt](https://github.com/opencv/opencv/files/2509777/gdb_log.txt)

I need to run Computer Vision algorithm on this camera output on this machine, Any kind of help is appreciated. Thankyou .

### Update:
Working in windows 10 even without gstreamer support. But not in Ubuntu :(

**Comment by alalek** [comment]
Please capture back trace ('bt' command) in gdb log.

**Comment by abhiTronix** [comment]
@alalek 

> Please capture back trace ('bt' command) in gdb log.

Here is the complete GDB Output:
[gdb_log_updated.txt](https://github.com/opencv/opencv/files/2510167/gdb_log_updated.txt)

#### Moreover, I tried all possible flags:
- **CAP_OPENCV_MJPEG =>** results in no frame. `(-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'`
```
import cv2

print cv2.__version__
camera = cv2.VideoCapture('/dev/video1',cv2.CAP_OPENCV_MJPEG )
while(1):
    retval, im = camera.read()
    cv2.imshow("image", im)
    k = cv2.waitKey(1) & 0xff
    if k == 27:
        break
camera.release() 
```
- **CAP_V4L/CAP_V4L2  =>** results in no output window with code compiles infinitely.
```
import cv2

print cv2.__version__
camera = cv2.VideoCapture('/dev/video1',cv2.CAP_V4L ) #or CAP_V4L2
while(1):
    retval, im = camera.read()
    cv2.imshow("image", im)
    k = cv2.waitKey(1) & 0xff
    if k == 27:
        break
camera.release() 
```
Thankyou.

**Comment by alalek** [comment]
Please dump `cv.getBuildInformation()`

**Comment by abhiTronix** [comment]
@alalek 
> Please dump cv.getBuildInformation()

Here is the Build Information: 
[build_info.txt](https://github.com/opencv/opencv/files/2510339/build_info.txt)

**Note:** I've used LibJPEGTurbo Library in my OpenCV instead of standard JPEG Library.

**Comment by alalek** [comment]
There is JPEG symbols mess:

>      JPEG:                        /opt/libjpeg-turbo/lib64/libjpeg.a (ver 62)

GStreamer uses system libjpeg, OpenCV provides own JPEG symbols from this .a file.

Please try to rebuild OpenCV with this linker flag:

```
cmake -DOPENCV_EXTRA_SHARED_LINKER_FLAGS="-Wl,--exclude-libs,/opt/libjpeg-turbo/lib64/libjpeg.a" ...
```

or

```
cmake -DOPENCV_EXTRA_SHARED_LINKER_FLAGS="-Wl,-Bsymbolic" ...
```


P.S. Ensure that all symbols from .a file have applied `visibility(hidden)` attribute (`visibility(default)` will not work).

**Comment by abhiTronix** [comment]
Thank you so much @alalek , I was stuck on this nearly 10 days. You saved my Humanoid project. Cheers :1st_place_medal: 

## Detailed Solution: [Neverever mix JPEG Libraries]

#### What was Happening?
I previously installed two JPEG Turbo Library namely,
- Provided by Official Site: i.e `libjpeg-turbo-official` (version 2.0.0) as `libjpeg.a`
- Provided by Ubuntu Repo: i.e `libjpeg-turbo8` as `libjpeg.so`

So, what was happening is that **OpenCV was using  libjpeg-turbo-official Library**(_Explicity added by me during its build_), whereas **Gstreamer/v4L2/v4L was using libjpeg-turbo8 Library**, which created the conflict and video source failed to open on my machine.

#### Solution:
Removed libjpeg-turbo-official Library, by: 

`sudo dpkg --purge libjpeg-turbo-official`

 and rebuild & installed my OpenCV with default libjpeg-turbo8 Library with flags `-DOPENCV_EXTRA_SHARED_LINKER_FLAGS="-Wl,-Bsymbolic"`, and voila it worked :100: 

_Also, never trust internet sources. :/_
