### ISSUE TITLE
Cross-compilation on Windows for Raspberry Pi Gives an Undeclared Error

### ISSUE THREAD

**Issue by fifothekid** [opencv/opencv#12932]
Right on this line:
https://github.com/opencv/opencv/blob/e959f449ae53272f29bcfcb4121a861291045703/modules/core/include/opencv2/core/fast_math.hpp#L78

Replacing it with the definition (void)temp compiles and works perfectly.
I'm compiling with contrib and GTK

Windows 10
Visual Studio 2017
CMake 3.7
VisualGDB
Latest RPi Toolchain

**Comment by alalek** [comment]
We don't support this build configuration, so please check this patch on your side: #12934

**Comment by fifothekid** [comment]
worked like a charm! thank you
