### ISSUE TITLE
How to get all the bounding box values for a give value in a single image?

### ISSUE THREAD

**Issue by Deepak3994** [opencv/opencv#12940]
I am trying to fetch all the bounnding boxes values for a given segmented-image for a particular value.

For example: I have a single semantic-segmented image which contains pedestrians, van, car, traffic light etc. The class value for traffic light is 81 in that image. But the challenging is that in that image there are nearly 6 traffic light and I want to extract all the 6 bounding box values for that image.

What i have tried so far,
I used regionprops from skimage and filtered the labels values equal to 81 and retrieved the bbox (bounding box) value for that image. But i could retrieve only 1 bounding box value. 

I want to retrieve all the 6 bounding box value for a single image.

I am writing in python language. It would be very great if anyone can help or suggest me here..

**Comment by dkurt** [comment]
@Deepak3994, This is a tracker for bugs and feature proposals. Please use a forum for questions: http://answers.opencv.org.
