### ISSUE TITLE
Noncontinuous cv::Mat is created

### ISSUE THREAD

**Issue by drspam1991** [opencv/opencv#12942]
Noncontinuous cv::Mat is created when the matrix needed memory is bigger than 3 GB (while create or clone the mat), although in the create() function doc, its says 'Matrices created with Mat::create() are always continuous'.

https://github.com/opencv/opencv/blob/e959f449ae53272f29bcfcb4121a861291045703/modules/core/src/matrix.cpp#L318

**Comment by alalek** [comment]
duplicate of #12018
