### ISSUE TITLE
Correction in OpenCV's default CMAKE search Path for OpenBLAS Library on Ubuntu-64bit Machines

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#12957]
##### System information (version)

- OpenCV => 4.0.0 - pre(Latest - master)
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => GCC 7.3.0 (Default)

##### Detailed description

Hello there,

I found a simple & straightforward solution to the problems of OpenBLAS Library not being identified properly on Ubuntu machine (64-bit) in CMAKE configuring step, also may work on other Linux Distros :)

**Completely Solves:** #9953

### Installation:

OpenBLAS can installed from respected default repository with the following command:

`sudo apt install libopenblas-dev, libopenblas-base`

Whereas LAPACK Library is little trickier to install,  as OpenBLAS doesn't provide Lapacke header file(_i cannot find the **lapacke.h** header fie_ ), Therefore I ought to install LAPACK Library instead, which works absolutely fine:
````
sudo apt install liblapacke-dev

sudo ln -s /usr/include/lapacke.h /usr/include/x86_64-linux-gnu # corrected path for the library 
````

### Setting Correct Path:

So, The only thing left is setting Correct Default Search Path for Include and Libs Directory of OpenBLAS Library which is as below : 

- Open_BLAS_INCLUDE_SEARCH_PATHS path: ` /usr/include/x86_64-linux-gnu`
- Open_BLAS_LIB_SEARCH_PATHS path: `/usr/lib/x86_64-linux-gnu`

Appending these respective additional Paths in **OpenCVFindOpenBLAS.cmake** : 
https://github.com/opencv/opencv/blob/eb981cc7d7011f60a7a8dd03b9db9cd2dcdd8596/cmake/OpenCVFindOpenBLAS.cmake#L46
and
https://github.com/opencv/opencv/blob/eb981cc7d7011f60a7a8dd03b9db9cd2dcdd8596/cmake/OpenCVFindOpenBLAS.cmake#L58

Completely solves the issue without altering any additional file in OpenCV. **Kindly Add these additional paths to the above-mentioned file :)**

#### Before appending path:
````
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find Atlas (missing: Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY) 
.
.
-- LAPACK(LAPACK/Generic): LAPACK_LIBRARIES: /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so
-- LAPACK(LAPACK/Generic): Support is enabled.
````
#### After appending path:
````
-- Found OpenBLAS libraries: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- Found OpenBLAS include: /usr/include/x86_64-linux-gnu
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- LAPACK(OpenBLAS): Support is enabled.
````
After Correction, OpenBLAS library configured correctly with OpenCV on my system, Cheers.

**Comment by alalek** [comment]
Such workarounds should be added as a comment into original issue.

**Comment by abhiTronix** [comment]
@alalek Actually the solution is **Altering OpenCVFindOpenBLAS.cmake in the source and adding additional paths**. That's why I opened it as an issue. Can you please add them and crosscheck the results?
