### ISSUE TITLE
Features2d.NOT_DRAW_SINGLE_POINTS in Java is missing in OpenCV 4

### ISSUE THREAD

**Issue by catree** [opencv/opencv#12963]
##### System information (version)

- OpenCV => 4.0.0-alpha, 4.0.0-beta
- Operating System / Platform => Ubuntu 16.04

##### Detailed description
Since OpenCV 4.0.0-alpha, I cannot use anymore `Features2d.NOT_DRAW_SINGLE_POINTS` with Java binding.

Is this intended since it looks like it is no more possible to call `drawMatches` with this flag parameter?

In [3.4.3](https://docs.opencv.org/3.4.3/javadoc/org/opencv/features2d/Features2d.html), there is:
`drawMatches(Mat img1, MatOfKeyPoint keypoints1, Mat img2, MatOfKeyPoint keypoints2, MatOfDMatch matches1to2, Mat outImg, Scalar matchColor, Scalar singlePointColor, MatOfByte matchesMask, int flags)`

But in [4.0.0-beta](https://docs.opencv.org/4.0.0-beta/javadoc/org/opencv/features2d/Features2d.html) there is only:
`drawMatches(Mat img1, MatOfKeyPoint keypoints1, Mat img2, MatOfKeyPoint keypoints2, MatOfDMatch matches1to2, Mat outImg, Scalar matchColor, Scalar singlePointColor, MatOfByte matchesMask)`

**Comment by alalek** [comment]
Perhaps Java bindings are broken due "enum" changes.

**Comment by catree** [comment]
For what it's worth, I tried bisecting and it gave me this commit:
`6ddef3b7a9a0d94ff85cd8dd6abb5f38adf8b97e is the first bad commit`

Which seems to correspond to #11516

**Comment by berak** [comment]
hello, @catree, you probably meant the removal of this:

https://github.com/opencv/opencv/blob/9e1b1e5389237c2b9f6c7b9d7715d9836c0a5de1/modules/features2d/misc/java/src/cpp/features2d_manual.hpp#L297-L314

(along with the whole features2d_manual.hpp) ?

i don't think, this is the cause. the commit was from may, and 3.4.3 release (which still had working flags) was in august.

it's probably more from [here](https://github.com/opencv/opencv/pull/12310/files#diff-17a1c50caf639a7abe392c3dfb1a1fdbR1185) , where "named" enums were introduced. attempts were made for [python](https://github.com/opencv/opencv/pull/12678/files) and [js](https://github.com/opencv/opencv/pull/12622/files) wrappers to handle this, but i don't see anything similar for java.

**Comment by catree** [comment]
Hello @berak 
Pull request #11516 is only merged into master. 3.4.3 still has [features2d_manual.hpp](https://github.com/opencv/opencv/blob/3.4.3/modules/features2d/misc/java/src/cpp/features2d_manual.hpp).

I can confirm that `NOT_DRAW_SINGLE_POINTS` flag is ok with commit hash 68c92908d57f074c9e301c8f8f2419aaa0a3fe93 and not ok with commit hash 4378b4d03d8415a132b6675883957243f95d75ee.

I don't know why this block was needed. Reintroducing this block does not solve the issue with the current Java wrapper and this `enum struct`. Tested quickly with something like:

`features2d_manual.hpp`:
```
#ifndef __OPENCV_FEATURES_2D_MANUAL_HPP__
#define __OPENCV_FEATURES_2D_MANUAL_HPP__

#include "opencv2/opencv_modules.hpp"

#ifdef HAVE_OPENCV_FEATURES2D
#include "opencv2/features2d.hpp"

#undef SIMPLEBLOB // to solve conflict with wincrypt.h on windows

namespace cv
{
#if 0
//DO NOT REMOVE! The block is required for sources parser
enum struct DrawMatchesFlags
{
  DEFAULT = 0, //!< Output image matrix will be created (Mat::create),
               //!< i.e. existing memory of output image may be reused.
               //!< Two source image, matches and single keypoints will be drawn.
               //!< For each keypoint only the center point will be drawn (without
               //!< the circle around keypoint with keypoint size and orientation).
  DRAW_OVER_OUTIMG = 1, //!< Output image matrix will not be created (Mat::create).
                        //!< Matches will be drawn on existing content of output image.
  NOT_DRAW_SINGLE_POINTS = 2, //!< Single keypoints will not be drawn.
  DRAW_RICH_KEYPOINTS = 4 //!< For each keypoint the circle around keypoint with keypoint size and
                          //!< orientation will be drawn.
};
CV_ENUM_FLAGS(DrawMatchesFlags);

CV_EXPORTS_AS(drawMatches2) void drawMatches( const Mat& img1, const std::vector<KeyPoint>& keypoints1,
                             const Mat& img2, const std::vector<KeyPoint>& keypoints2,
                             const std::vector<std::vector<DMatch> >& matches1to2, Mat& outImg,
                             const Scalar& matchColor=Scalar::all(-1), const Scalar& singlePointColor=Scalar::all(-1),
                             const std::vector<std::vector<char> >& matchesMask=std::vector<std::vector<char> >(), DrawMatchesFlags flags=DrawMatchesFlags::DEFAULT);

#endif

} //cv

#endif // HAVE_OPENCV_FEATURES2D

#endif // __OPENCV_FEATURES_2D_MANUAL_HPP__
```

And `filelist`:
```
misc/java/src/cpp/features2d_manual.hpp
include/opencv2/features2d.hpp
```

**Comment by alalek** [comment]
Please try this patch: #13415 

Names of these constants are changed, something like:
- `cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS`
- `cv.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS`

**Comment by catree** [comment]
@alalek 
In Java, the issue is still there.

**Comment by dkurt** [comment]
@catree, please test the changes which have been merged with https://github.com/opencv/opencv/pull/13471.

**Comment by catree** [comment]
@dkurt 
Yes, it solves the issue. Thanks.
