### ISSUE TITLE
tf_text_graph_faster_rcnn

### ISSUE THREAD

**Issue by nardaweissman** [opencv/opencv#12996]
[pipeline.zip](https://github.com/opencv/opencv/files/2534312/pipeline.zip)
I trained an object detection example model of pets by tensorflow (ubuntu 16.04 python 3.5 tensorflow 1.11.0).
I am trying to convert is to opencv.
I get the error
Scales:            [0.25, 0.5, 1.0, 2.0]
Aspect ratios:     [0.5, 1.0, 2.0]
Width stride:      16.000000
Height stride:     16.000000
Features stride:   16.000000
2018-10-31 12:34:02.608202: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying sort_by_execution_order
Traceback (most recent call last):
  File "D:\TFS\LPR\IP\MAIN\SRC\PythonProjects\TensorFlow\UseModelZoo\tf_text_graph_faster_rcnn.py", line 228, in <module>
    createFasterRCNNGraph(args.input, args.config, args.output)
  File "D:\TFS\LPR\IP\MAIN\SRC\PythonProjects\TensorFlow\UseModelZoo\tf_text_graph_faster_rcnn.py", line 56, in createFasterRCNNGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError

 
[faster_rcnn_resnet50_pets_shay.zip](https://github.com/opencv/opencv/files/2534318/faster_rcnn_resnet50_pets_shay.zip)

**Comment by nardaweissman** [comment]
I am doing the pbtxt on windows 10 python 3.6.5
opencv 3.4.3
[UseModelZoo.zip](https://github.com/opencv/opencv/files/2534355/UseModelZoo.zip)
I succeeded transform the faster_rcnn_resnet50_coco_2018_01_28 example from model zoo.

**Comment by dkurt** [comment]
@nardaweissman, Please follow the guide in issue's template and provide steps to reproduce. Add a reference to `.pb` file so we can run a script locally. If you are not able to share it - initialize weights randomly.

**Comment by nardaweissman** [comment]
Hi,
I do not find the template guide
How do I add reference to my .pb?
Thanks.

**Comment by dkurt** [comment]
@nardaweissman, There is during issue creation:
```
<!--
If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.
If you need further assistance please read [How To Contribute](https://github.com/opencv/opencv/wiki/How_to_contribute).

Please:

* Read the documentation to test with the latest developer build.
* Check if other person has already created the same issue to avoid duplicates. You can comment on it if there already is an issue.
* Try to be as detailed as possible in your report.
* Report only one problem per created issue.


This is a template helping you to create an issue which can be processed as quickly as possible. This is the bug reporting section for the OpenCV library.
-->

##### System information (version)
<!-- Example
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
-->

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

<!-- your description -->

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    ```
 or attach as .txt or .zip file
-->
```

Do you have a `.pb` file? Upload it to some files hosting and put a link to download it. Your issue should be reproducible.

**Comment by nardaweissman** [comment]
!--
This is a template helping you to create an issue which can be processed as quickly as possible. This is the bug reporting section for the OpenCV library.
-->

##### System information (version)
<!-
- OpenCV => 3.4.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- Python 3.6.5 
- tensorflow-gpu 1.11.0
-->

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

I trained a model from object_detection samples faster_rcnn_resnet50 on oxford pets database. I got a pb file.
I want to do inference by opencv.
I am trying to get the pbtxt using tf_text_graph_faster_rcnn.py
I get 
createFasterRCNNGraph(args.input, args.config, args.output)
File "D:\TFS\LPR\IP\MAIN\SRC\PythonProjects\TensorFlow\UseModelZoo\tf_text_graph_faster_rcnn.py", line 56, in createFasterRCNNGraph
assert(graph_def.node[0].op == 'Placeholder')
AssertionError

##### Steps to reproduce
run tf_text_graph_faster_rcnn  on the pb and config in the below link

   ``
Link to my pb config and py files.
https://www.dropbox.com/sh/dh1c325m0t22qsn/AAAJRfedjbF0uMsTLWyS6uVYa?dl=0

**Comment by dkurt** [comment]
@nardaweissman, it looks like that you serialized model in a wrong way. There are training only nodes:

`ShuffleDataset` ???
![screenshot from 2018-11-01 13-17-17](https://user-images.githubusercontent.com/25801568/47846319-7d51fe00-ddd8-11e8-91ab-62964ad36c12.png)

`RandomHorizontalFlip` ???
![screenshot from 2018-11-01 13-17-17](https://user-images.githubusercontent.com/25801568/47846338-90fd6480-ddd8-11e8-85e4-b719a3dbd9db.png)

**Comment by nardaweissman** [comment]
Thanks
I uploaded to Dropbox my checkpoints and FreezeGraphDogsCats.py which I use to create the pb file.
Can you tell what is wrong?

**Comment by nardaweissman** [comment]
Hi I also tried:
1. exporting the graph using export_inference_graph.py (part of the object_detection package).
2. creating the pbtxt using tf_text_graph_faster_rcnn.
3. When trying the opencv inference. I get C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: CropAndResize/Reshape/shape in function 'cv::dnn::experimental_dnn_34_v7::`anonymous-namespace'::TFImporter::connect'
I uploaded the frozen_inference_graph.pb and faster_rcnn_resnet50_pets_shay.pbtxt to the Dropbox link.
I tested the pb file - inferencing using python and tensorflow and it works.

**Comment by dkurt** [comment]
@nardaweissman, can you please specify version of TensorFlow and try approach from https://github.com/opencv/opencv/issues/13050#issuecomment-436221057?

**Comment by nardaweissman** [comment]
tensorfow-gpu 1.11 
I will try.
Many Thanks

**Comment by nardaweissman** [comment]
#13050 is working - many many thanks.
