### ISSUE TITLE
Compilation Error during opencv install + QT

### ISSUE THREAD

**Issue by Jaydeepgambhava** [opencv/opencv#12998]
##### System information (version)

- OpenCV => 3.2,0
- Operating System / Platform =>Windows 64 Bit
- Compiler => mingw32

##### Detailed description

Hello I am installing opencv in QT as mention below link :
https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows

During below step :
 d:
 cd d:\
 cd opencv-build  
 mingw32-make -j 8
 mingw32-make install
 
Brief part

collect2.exe: error: ld returned 1 exit status
modules\highgui\CMakeFiles\opencv_highgui.dir\build.make:202: recipe for target 'bin/libopencv_highgui320.dll' failed
mingw32-make[2]: *** [bin/libopencv_highgui320.dll] Error 1
CMakeFiles\Makefile2:4399: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
mingw32-make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
collect2.exe: error: ld returned 1 exit status
modules\highgui\CMakeFiles\opencv_highgui.dir\build.make:202: recipe for target 'bin/libopencv_highgui320.dll' failed
mingw32-make[2]: *** [bin/libopencv_highgui320.dll] Error 1
CMakeFiles\Makefile2:4399: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
mingw32-make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

i am getting compilation as mentioned in attached file
[Opencv_QT.txt](https://github.com/opencv/opencv/files/2534790/Opencv_QT.txt)

**Comment by alalek** [comment]
> mingw32

We don't support that. You should investigate and propose fix by yourself.

**Comment by Jaydeepgambhava** [comment]
@alalek  : Thank you for the quick response ! 
Just for information.
As of now i just disable BUILD_opencv_highgui from CMake 3,7,2

Now its compiling successfully.
