### ISSUE TITLE
Does building a new javascript file creates any problem? Cause when I try to build mine, the bash show that some specifics files cant be found

### ISSUE THREAD

**Issue by reisvictor1** [opencv/opencv#12992]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by tomoaki0705** [comment]
If you are **asking for help**, you're asking at the wrong place.
This is **NOT** a place to ask for help, this is a place to discuss about fixing OpenCV it selfs.

I suggest you to close this issue and post it on http://answers.opencv.org/questions/ 
That's where you can ask questions.
