### ISSUE TITLE
drawFrameAxes missing from calib3d.hpp?

### ISSUE THREAD

**Issue by jnre** [opencv/opencv#13009]
using opencv 3.4.3, i cant seem to find drawFrameAxes in calib3d.hpp even though its in the documentation.

**Comment by berak** [comment]
@jnre , it's in the 3.4.3-dev branch (you have to checkout 3.4) ,not in the older 3.4.3 *release*

**Comment by jnre** [comment]
yup i just figured it out, thanks

**Comment by mrgransky** [comment]
I faced the same probelm.
In my CMakeLists, I have the following line for opencv:
```
find_package(OpenCV 3.0 QUIET)
if(NOT OpenCV_FOUND)
   find_package(OpenCV 2.4.3 QUIET)
   if(NOT OpenCV_FOUND)
      message(FATAL_ERROR "OpenCV > 2.4.3 not found.")
   endif()
endif()
```
but I get the error:
`error: ‘drawFrameAxes’ was not declared in this scope`.
