### ISSUE TITLE
cv::resize memory leak

### ISSUE THREAD

**Issue by haohuachang** [opencv/opencv#13015]
##### System information (version)

- OpenCV => :2.4.9:
- Operating System / Platform => :Windows 64 Bit
- Compiler => :Visual Studio 2015 Professional

##### Detailed description
![image](https://user-images.githubusercontent.com/20737540/47890106-55ba6e80-de88-11e8-9240-cd2160a1826e.png)
Call Stack show:
![image](https://user-images.githubusercontent.com/20737540/47890125-74206a00-de88-11e8-8fef-fc4c5a37302e.png)

the program always crash on here:
	cv::resize(*srcImg, mat2bitmap_img, cv::Size(draw_rect.Width(), draw_rect.Height()));
I think this problem is memory leak, resize function too many memory allocation, resulting in memory fragmentation and management problems.
##### Steps to reproduce
the program always run on loop,for example:
while(1) {
cv::resize...
}

```

/*! display Mat on Picture Control in MFC
*! Mat  img: the image that to display
*! UINT nID: the ID of control
*! support BGR(Mat default),BGRA,GARY
*! other type need use cvtColor to convert
*/
void ImageDlg::DrawMat(cv::Mat *srcImg, UINT nID)
{
	if (srcImg->empty() || srcImg->data == nullptr) {
		return;
	}

	CDC *pDC = nullptr;
	CWnd *pWnd = GetDlgItem(nID);
	pWnd->GetClientRect(&draw_rect);
	pDC = pWnd->GetDC();
	cv::resize(*srcImg, mat2bitmap_img, cv::Size(draw_rect.Width(), draw_rect.Height()));
	switch (srcImg->channels())
	{
	case 1:
		cv::cvtColor(mat2bitmap_img, mat2bitmap_img, CV_GRAY2BGRA); // GRAY --> BGRA(CV_8UC4)
		break;
	case 3:
		cv::cvtColor(mat2bitmap_img, mat2bitmap_img, CV_BGR2BGRA);  // BGR --> BGRA(CV_8UC4)
		break;
	default:
		break;
	}

	// why convert to CV_8UC4
	// because windows need 4-byte aligned in a row
	// if there are 3 pixels in a row,
	// CV_8UC3: 3 pixel = 9 bytes,   9 % 4 = 1(no alignment)
	// CV_8UC4: 3 pixel = 12 bytes, 12 % 4 = 0(it's ok)

	// calculate how many bytes a pixel
	int  pixelBytes = mat2bitmap_img.channels()*(mat2bitmap_img.depth() + 1);

	// create a header by using BITMAPINFO structure
	draw_bitmapInfo.bmiHeader.biBitCount = 8 * pixelBytes;
	draw_bitmapInfo.bmiHeader.biWidth = mat2bitmap_img.cols;
	draw_bitmapInfo.bmiHeader.biHeight = -mat2bitmap_img.rows;

	// display Mat
	// Mat data + BITMAPINFO --> MFC DigItem
	::StretchDIBits(
		pDC->GetSafeHdc(),
		draw_rect.left, draw_rect.top, draw_rect.Width(), draw_rect.Height(),
		0, 0, draw_rect.Width(), draw_rect.Height(),
		mat2bitmap_img.data,
		&draw_bitmapInfo,
		DIB_RGB_COLORS,
		SRCCOPY
	);
	ReleaseDC(pDC);
	pDC = nullptr;
	pWnd = nullptr;
}

```

**my idea:**
I think resize function input params is piont,it will not need memory allocation
original:
 void cv::resize( InputArray _src, OutputArray _dst, Size dsize,
                 double inv_scale_x, double inv_scale_y, int interpolation )
maybe fixed:
 void cv::resize( InputArray *_src, OutputArray *_dst, Size dsize,
                 double inv_scale_x, double inv_scale_y, int interpolation )
@peters @eruffaldi

**Comment by alalek** [comment]
> memory leak

By definition, "memory leak" is related to non-freed resources.
This is not your case.

> InputArray *_src

Definitely NO.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by haohuachang** [comment]
@alalek Thanks for your replay,I will find this problem.
> By definition, "memory leak" is related to non-freed resources.
This is not your case.
I use Mat or other variable is global variables,so is not need freed resources.
when the program crash: the code stop in resize function :+1: 
```
inline Mat::Mat(const Mat& m)
    : flags(m.flags), dims(m.dims), rows(m.rows), cols(m.cols), data(m.data),
    refcount(m.refcount), datastart(m.datastart), dataend(m.dataend),
    datalimit(m.datalimit), allocator(m.allocator), size(&rows)
{
    if( refcount )
        CV_XADD(refcount, 1);
    if( m.dims <= 2 )
    {
        step[0] = m.step[0]; step[1] = m.step[1];
    }
```
the refcount  is invalid
