### ISSUE TITLE
Replace the use of non-portable strcpy_s, strcat_s functions from window_w32.cpp

### ISSUE THREAD

**Issue by ijean** [opencv/opencv#13016]
Hello,

##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 10 64 bit
- Compiler => mingw-w64 GCC 8.1.0

##### Detailed description

The use of *strcpy_s* and *strcat_s* in *window_w32.cpp* makes OpenCV impossible to build with GCC (on Windows) which doesn't have the optional *_s* functions from C11. I'm not an expert in C/C++ so I would suggest to replace the use of the above with *strncpy* and *strncat* which should be present in all compilers (MSVC, GCC, Clang).

##### Steps to reproduce

Try to build OpenCV 4.0 beta with mingw-w64 GCC 8.1 on Windows.

Thanks.

**Comment by ijean** [comment]
Seems that the change from strcpy, strcat to currently MSVC only functions strcpy_s, strcat_s was done at this commit https://github.com/opencv/opencv/commit/e031bada7d0a474787411f05b6ce7a1b74d0b5e4#diff-baec79d9f6cf2a8b605a5d9aad326540

**Comment by alalek** [comment]
We don't support MinGW build configuration. So we can't help with fixing/validation of this issue.

`strcpy_s` is here: https://en.cppreference.com/w/c/string/byte/strcpy

Reverting back to non "_s" function is not an option (our Windows MSVC builds must conform security requirements).

You can try to reuse `strncpy()` (bu it has NULL-termination issues).

Feel free to wrap these "_s" calls via macro:
```
#if (defined(__MINGW__) || defined(__MINGW32__)) \
    && !defined(OPENCV_DONT_REDEFINE_STR_S_FUNCTIONS)
static inline mingw_strcpy_s(...) { .... }
#define strcpy_s mingw_strcpy_s
#define strcat_s ...
#endif
```

and prepare PR onto 3.4 branch.

**Comment by ijean** [comment]
@alalek Sorry but your link to https://en.cppreference.com/w/c/string/byte/strcpy just proves my point. *strcpy_s* is not even in the C++17 standard, true it is in the C11 standard and marked as optional to implement by the compiler.
