### ISSUE TITLE
How to read image from database(sqlite Django) not local file?

### ISSUE THREAD

**Issue by rakibulislam01** [opencv/opencv#13031]
- OpenCV => 3.4
- Operating System / Platform =>  Ubuntu18.4
- Compiler => Pycharm2018

image = cv2.imread(imagefile)
cv2.imshow('image',obama_image)

**Comment by berak** [comment]
hello, @rakibulislam01 ,this is the opencv **bug tracker** (and the wrong place for your question)

please be so kind to close this issue, and re-ask on http://answers.opencv.org, we can help you much better from there , thank you !

**Comment by berak** [comment]
hello, @rakibulislam01 , this is the opencv **bug tracker** (and the wrong place for your question)

please be so kind to **close** this issue, and **ask again** on http://answers.opencv.org/questions/ 
we can help you much better from there, thank you !
