### ISSUE TITLE
FDA and LDA classification 

### ISSUE THREAD

**Issue by manef1994** [opencv/opencv#13038]
Hey Guys , I'm development an app for my master degree and I'm facing an issue, I need to use the FDA classifier "fisher's discriminant analysis" (FDA) on android, but using opencv I only found the LDA " linear discriminant analysis", can some one explain the different between them and it's possible to get the same result with classifier FDA by applying the LDA classifier  ?!

**Comment by berak** [comment]
hello, @manef1994 , unfortunately, you're asking in the wrong place, this is the opencv **bug tracker**.
kindly close this issue, and ask again on http://answers.opencv.org , we can help you much better from there, thank you !

**Comment by manef1994** [comment]
ahh ok thanks a lot and sory for this ;)
