### ISSUE TITLE
Opencv failed to run Objdetect_CascadeDetector.regression test with release and debug configuration

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#13051]
Environment:
 Windows Server 2016 + VS2017 opencv master branch latest srouce code

Opencv failed to run Objdetect_CascadeDetector.regression test with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance

1.git clone https://github.com/opencv/opencv D:\OpenCV\src
2.git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
3.Open a VS 2017 x86 prompt and browse to D:\OpenCV
4.mkdir build_x86 && pushd build_x86
5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6.msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
7.pushd build_x86\bin\Release
8.opencv_test_objdetect.exe --gtest_filter=Objdetect_CascadeDetector.regression

Note:
 OPENCV_TEST_DATA_PATH env variable has been set and point to <opencv_extra>/testdata.

The whole log file please see attachment.
[log_x86_test_7.log](https://github.com/opencv/opencv/files/2551499/log_x86_test_7.log)

TestErrorMessage:
[----------] Global test environment tear-down
[==========] 31 tests from 5 test cases ran. (19734 ms total)
[  PASSED  ] 30 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Objdetect_CascadeDetector.regression

 1 FAILED TEST

**Comment by alalek** [comment]
Like #13046 you don't have up-to-date testdata from opencv_extra. Check your scripts.

**Comment by LaurentBerger** [comment]
I don't think that's the problem :  

```
[ RUN      ] Objdetect_CascadeDetector.regression
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/haarcascade_frontalface_alt_old.xml
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/haarcascade_frontalface_alt2_old.xml
D:\OpenCV\src\modules\objdetect\test\test_cascadeandhog.cpp(381): error: Expected: (noPair) <= (cvRound(valRects.size()*eps.noPair)+1), actual: 3 vs 2
detector haarold2 has overrated count of rectangles without pair on cascadeandhog/images/er.png image
D:\OpenCV\src\modules\objdetect\test\test_cascadeandhog.cpp(389): error: Expected: (totalNoPair) <= (cvRound(totalValRectCount*eps. noPair)+1), actual: 9 vs 8
In total, detector haarold2 has overrated count of rectangles without pair on the whole image set
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/haarcascade_frontalface_default_old.xml
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/haarcascade_1.xml
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/haarcascade_3.xml
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/lbpcascade_frontalface.xml
detector D:\OpenCV\src\extra\testdata/cv/cascadeandhog/cascades/lbpcascade_frontalface_alt3.xml
D:\OpenCV\src\modules\ts\src\ts.cpp(567): error: Failed

	failure reason: Bad accuracy
	test case #-1
	seed: ffffffffffffffff
-----------------------------------
	CONSOLE: ......
-----------------------------------

```
