### ISSUE TITLE
Error loading faster rcnn using opencv

### ISSUE THREAD

**Issue by plin24** [opencv/opencv#13050]
**System information (version)**
OpenCV =>  3.4.3.18
Operating System / Platform => Windows 10 64 Bit
TensorFlow=> 1.11.0
**Detailed description**
I trained a faster_rcnn_resnet50 model with 1 class (using the faster_rcnn_resnet50_coco.config) and when I tried to load the network using `readnetfromtensorflow`, I got the following error: 

> cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: CropAndResize/Reshape/shape in function 'cv::dnn::experimental_dnn_34_v7::`anonymous-namespace'::TFImporter::connect'

[My pbtxt file](https://github.com/opencv/opencv/files/2551994/frozen_inference_graph.zip)
[My pb file](https://drive.google.com/file/d/1YZ5m2fQOJKNtLl_QdSwJzRAJGB1Gb7zf/view?usp=sharing)

I generated the pbtxt file through `tf_text_graph_faster_rcnn.py` and also tried generating one after `optimize_for_inference.py`, but none of them worked out. Need help to fix this! Thanks in advance.

**Comment by dkurt** [comment]
@plin24, please check correctness of your link. It references to https://drive.google.com/drive/u/0/my-drive

**Comment by dkurt** [comment]
@plin24, please also specify all the changes made in a config file `faster_rcnn_resnet50_coco.config` besides `num_classes: 1` if you did. Thanks!

**Comment by plin24** [comment]
I only made changes to`num_classes: 1` and `num_examples: 170`. Everything else remains the same. 
[pipeline.zip](https://github.com/opencv/opencv/files/2552072/pipeline.zip)

**Comment by dkurt** [comment]
@plin24, which tools was used to train the model? An official https://github.com/tensorflow/models/tree/master/research/object_detection or one of it's forks? May be you can specify a specific scripts?

**Comment by plin24** [comment]
@dkurt I used the tensorflow object detection API to train the model

**Comment by plin24** [comment]
@dkurt Thanks you so much for your help! It is working now. However, I got the missing object like you mentioned. 
1. Detection using tensorflow
![image using tensorflow](https://user-images.githubusercontent.com/41752004/48080125-d687ac00-e1a1-11e8-8c38-938b12af7fd6.png)
2. Detection using opencv
![image using opencv](https://user-images.githubusercontent.com/41752004/48080141-ddaeba00-e1a1-11e8-8f2c-eeab99c91733.png)
(And btw the object I trained on the model is lesion)

**Comment by plin24** [comment]
@dkurt I'm so sorry that I made a huge mistake here. The example I gave that has no detection on image is the only test image that has different size than the others. After inputting the right image size it gives the correct result. So so sorry for this silly mistake.

**Comment by dkurt** [comment]
@plin24, Never mind. Anyway we'll try to fix it to achieve exactly the same output.

**Comment by plin24** [comment]
@dkurt Thank you so much for solving this issue and good luck on fixing the error!

**Comment by dont32** [comment]
@dkurt I have same error with mask rcnn using opencv dnn 
 OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: CropAndResize/Reshape/shape in function 'connect'
I try like with faster rcnn but error 
can you help me solve this problem

**Comment by dkurt** [comment]
@dont32, try to follow recommendations from https://github.com/opencv/opencv/issues/13050#issuecomment-436221057. However please note that work is currently in progress and corresponding PR will fix `tf_text_graph_faster_rcnn.py` script to reduce these extra steps.

**Comment by dont32** [comment]
@dkurt I try to follow #13050 with tf_text_graph_mask_rcnn.py but when run i have a error 
File "tf_text_graph_mask_rcnn.py", line 73, in <module>
    node = graph_def.node.pop()
IndexError: pop from empty list

**Comment by dkurt** [comment]
`tf_text_graph_mask_rcnn.py`?

**Comment by dont32** [comment]
yes , i retrain mask rcnn with tensorflow api

**Comment by dont32** [comment]
@dkurt This is my test model and config file for train 
https://drive.google.com/open?id=1N6-_aIIu6CfBnzqr5Sw7sOn8_ValvUHD

**Comment by plin24** [comment]
@dkurt I see. Thank you so much!

**Comment by dkurt** [comment]
@dont32, Can you please show how you run this Mask-RCNN model using TensorFlow? For me, `num_detections` equals 100 (number of detected bounding boxes) but `detection_masks` has a shape `(1, 300, 15, 15)` which is a bit strange.

**Comment by dont32** [comment]
@dkurt 
I try to follow this link https://towardsdatascience.com/building-a-custom-mask-rcnn-model-with-tensorflow-object-detection-952f5b0c7ab4
I using this code for detection :
https://github.com/priya-dwivedi/Deep-Learning/blob/master/Custom_Mask_RCNN/mask_rcnn_custom_images.ipynb

**Comment by dkurt** [comment]
@dont32, pleas provide a test image (it'd be better in `.png` format) and a desired result (received using TensorFlow and mentioned tutorial).

**Comment by dont32** [comment]
@dkurt  this is a test image https://github.com/priya-dwivedi/Deep-Learning/blob/master/Custom_Mask_RCNN/test_images/image1.jpg

**Comment by hardiktechnoplanet** [comment]
@dkurt Hello. I am able to generate the graph.pbtxt file using the changes that you have mentioned above and used your code to import the tensorflow model using opencv. In the output image, I can see the boxes around the objects. Can you please tell me how can I display class name and the score percentage for objects?
![detector1](https://user-images.githubusercontent.com/7738407/59795027-4a497580-92a8-11e9-84ea-e93b4f81e21b.jpg)
I want to get the results like the attached image. Right now, I can see the boxes but not the class name and score? Please tell me what I need to add in your code to get the desired result?
I have used the faster rcnn model.
