### ISSUE TITLE
Opencv failed to run Calib3d_CirclesPatternDetectorWithClustering.accuracy test with release and debug configuration

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#13075]
Environment:
 Windows Server 2016 + VS2017 opencv master branch latest srouce code

Opencv failed to run Calib3d_CirclesPatternDetectorWithClustering.accuracy test with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance

 1. git clone https://github.com/opencv/opencv D:\OpenCV\src
 2. git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
 3. Open a VS 2017 x86 prompt and browse to D:\OpenCV
 4. mkdir build_x86 && pushd build_x86
 5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
 6. msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
 7. pushd build_x86\bin\Release
 8. opencv_test_calib3d.exe --gtest_filter=Calib3d_CirclesPatternDetectorWithClustering.accuracy

The whole log file please see attachment.
[log_x86_test_13.log](https://github.com/opencv/opencv/files/2560130/log_x86_test_13.log)

TestErrorMessage:
[----------] 1 test from Calib3d_CirclesPatternDetectorWithClustering
[ RUN      ] Calib3d_CirclesPatternDetectorWithClustering.accuracy
D:\OpenCV\src\modules\calib3d\test\test_chesscorners.cpp(643): error: Expected: (error) <= (precise_success_error_level), actual: -nan(ind) vs 2
[  FAILED  ] Calib3d_CirclesPatternDetectorWithClustering.accuracy (0 ms)
[----------] 1 test from Calib3d_CirclesPatternDetectorWithClustering (0 ms total)

[----------] Global test environment tear-down
[==========] 68 tests from 40 test cases ran. (48543 ms total)
[  PASSED  ] 67 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Calib3d_CirclesPatternDetectorWithClustering.accuracy

**Comment by alalek** [comment]
@spacelg Please stop filling of similar invalid reports. Your opencv_extra is stalled (and others too).
Re-check twice your setup before reporting. Reproduce problem from scratch (clean build environment).
Then check [OpenCV CI builds](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master).
And after that you may fill some report about failed test.
