### ISSUE TITLE
OpenCV DNN throws exception with Mask RCNN (Resnet101) model

### ISSUE THREAD

**Issue by baranorbert** [opencv/opencv#13071]
System information (version)

    OpenCV => OpenCV 3.4 and OpenCV (master - latest version from GitHub repository)
    Operating System / Platform => Linux 64bit Ubuntu 16.04
    Compiler => gcc (7.3.0)
    Tensorflow => 1.12.0-rc1
    Cuda 9.0.176
    CUDNN: 7.3.1.20

Detailed description

I trained a Mask RCNN model (with Resnet101 backbone) by using a Tensorflow object detection API.
I try to test the model with a C++ (OpenCV DNN) application and a Python OpenCV script (mask_rcnn.py) but the readNetFromTensorflow always drop this exception:

OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:997: error: (-215:Assertion failed) values.type() == CV_32FC1 in function 'populateNet'

The training command was the following:
python object_detection/model_main.py --pipeline_config_path=mask_rcnn_resnet101_pets_cl2m.config --model_dir . --alsologtostderr

All necessary files are accessible here:
https://drive.google.com/drive/folders/1RdxRqlKjU-qXU6O0kT5p8iVHJ9Bvh0ZD?usp=sharing

Steps to reproduce

1. Export inference graph from checkpoint
python tensorflow-models/research/object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt-200000 --output_directory .

Result: frozen_inference_graph.pb

2. Execute transform_graph.py script to sort order of nodes

Result: frozen_inference_graph_sort.pb

3. Extract proto txt

python opencv/samples/dnn/tf_text_graph_mask_rcnn.py --input frozen_inference_graph_sort.pb --config pipeline.config --output frozen_inference_graph_sort.pbtxt

Result: frozen_inference_graph_sort.pbtxt

4. Apply Mask RCNN test script

python opencv/samples/dnn/mask_rcnn.py --input set03_images124.png --model frozen_inference_graph_sort.pb --config frozen_inference_graph_sort.pbtxt --classes mscoco_labels.names --colors colors.txt --width 224 --height 224 --thr 0.2

**Comment by baranorbert** [comment]
Hi,
I modified my transform_graph.py script, I added "remove_nodes(op=Assert)" to the TransformGraph function. But the result is the same. Did you think of this?

The full line is:
graph_def = TransformGraph(graph_def, inp_node, out_node, ['remove_nodes(op=Assert) sort_by_execution_order'])

**Comment by baranorbert** [comment]
I tested the Mask RCNN (Resnet50 backbone) with OpenCV 3.4.4 and I have got the same result.
Here is my inference graph after sorting nodes and exporting pbtxt (dnn/tf_text_graph_mask_rcnn.py).
![frozen_inference_graph_sort](https://user-images.githubusercontent.com/26465525/48698361-25dccc00-ebe7-11e8-94bd-b22cab0c430d.png)

**Comment by dkurt** [comment]
@baranorbert, please do not mention models without it's origin. We need to have ways to reproduce it.

**Comment by baranorbert** [comment]
Sorry. @dkurt, the models  are from here:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
* mask_rcnn_resnet50_atrous_coco
* mask_rcnn_resnet101_atrous_coco

Checkpoints and configs:
--------------------------------
* Mask RCNN Resnet50
https://drive.google.com/drive/folders/1nB0qJkYoHb7gwtemz9q8Uf7mPeUmYJFI?usp=sharing

*Mask RCNN Resnet101
https://drive.google.com/drive/folders/1RdxRqlKjU-qXU6O0kT5p8iVHJ9Bvh0ZD?usp=sharing

**Comment by dkurt** [comment]
@baranorbert, Please check this PR: https://github.com/opencv/opencv/pull/13766 (`mask_rcnn_inception_resnet_v2_atrous_coco` still doesn't work but `mask_rcnn_resnet50_atrous_coco` and `mask_rcnn_resnet101_atrous_coco` were fixed).

**Comment by baranorbert** [comment]
@dkurt, thanks for the fixes, I will try it as soon as possible.
