### ISSUE TITLE
Mat::convertTo  error

### ISSUE THREAD

**Issue by huangqinjin** [opencv/opencv#13078]
##### System information (version)
- OpenCV => 3.4.3
- Operating System / Platform => OpenSUSE Tumbleweed 20181105
- Compiler => gcc 8.2.1

##### Steps to reproduce
 ```.cpp
std::vector<float> floats = {1, 2, 3, 4, 5, 6, 7, 8};
std::vector<int> ints(floats.size() / 2);

cv::Mat(ints.size(), 1, CV_32FC1, floats.data(), sizeof(floats[0]) * 2)
            .convertTo(ints, CV_32S);
```

The code may cause segmentation fault or get error result `ints == [1, 0, 0, 0]`. But if I use
`std::array<int, 4>` for `ints`, then correct result `ints == [1, 3, 5, 7]` gets.

**Comment by alalek** [comment]
> segmentation fault 

Please add stacktrace.

**Comment by alalek** [comment]
Workaround: use `Mat(ints)`
```
    .convertTo(Mat(ints), CV_32S);
```

Fix will be later.
