### ISSUE TITLE
Net setInput failed for new input in opencv 4.0 , net loaded from Onnx, the net just can not successfully update input data from setInput. 

### ISSUE THREAD

**Issue by CaptainEven** [opencv/opencv#13090]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by CaptainEven** [comment]
Hi, test code is as follows(invalid when call function setInput for second blob(blob_2)):

#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>
#include <iostream>
#include <fstream>

using namespace std;
using namespace cv;
using namespace cv::dnn;

const bool is_rgb = true;
//printf("=> is_rgb: %d\n", is_rgb);

unsigned int IMG_DIM = is_rgb ? 224 : 128;
String model_path = is_rgb ? "../car_matchRGB.onnx" : "../car_match.onnx";
double TH = is_rgb ? 0.85 : 0.55;

int test_onnx()
{
	Net net_1 = readNetFromONNX(model_path);

	if (net_1.empty() || net_2.empty())
	{
		printf("=> net load failed.\n");
		return -1;
	}
	printf("=> net weights loaded done.\n");

	const String img_1_path = "../img_1.jpg";
	const String img_2_path = "../img_3.jpg";
	Mat img_1, img_2;
	if (is_rgb)
	{
		img_1 = imread(img_1_path, IMREAD_COLOR);
		img_2 = imread(img_2_path, IMREAD_COLOR);
	}
	else
	{
		img_1 = imread(img_1_path, IMREAD_GRAYSCALE);
		img_2 = imread(img_2_path, IMREAD_GRAYSCALE);
	}
	if (img_1.empty() || img_2.empty())
	{
		printf("[Err]: empty dir.\n");
		return -1;
	}
	img_1.convertTo(img_1, CV_32F);
	img_2.convertTo(img_2, CV_32F);
	assert(img_1.cols == img_2.cols && img_1.rows == img_2.rows);
	printf("=> %s and %s loaded.\n", img_1_path.c_str(), img_2_path.c_str());

	// padding
	int H = img_1.rows;
	int W = img_1.cols;
	int dim_diff = std::abs(H - W);
	int top, bottom, left, right;
	if (H <= W)
	{
		top = dim_diff / 2;
		bottom = dim_diff - top;
		left = 0;
		right = 0;
	}
	else
	{
		left = dim_diff / 2;
		right = dim_diff - left;
		top = 0;
		bottom = 0;
	}

	Mat img_1_pad, img_2_pad;
	copyMakeBorder(img_1, img_1_pad,
		top, bottom, left, right, BORDER_CONSTANT, 127.5);
	copyMakeBorder(img_2, img_2_pad,
		top, bottom, left, right, BORDER_CONSTANT, 127.5);
	//printf("=>padded img_w: %d, img_h: %d\n", img_1_pad.cols, img_1_pad.rows);
	printf("=> channles: [%d, %d]\n", img_1_pad.channels(), img_2_pad.channels());

	// construct blob
	Mat blob_1, blob_2;
	blob_1 = blobFromImage(
		img_1_pad,
		1.0 / 127.5f,
		Size(IMG_DIM, IMG_DIM), 
		127.5,
		true
	);
	blob_2 = blobFromImage(
		img_2_pad,
		1.0 / 127.5f,
		Size(IMG_DIM, IMG_DIM),
		127.5,
		true
	);
	
        // inference: get features
	net_1.setInput(blob_1);
	Mat feature_1 = net_1.forward();
	net_1.setInput(blob_2);  // invalid here...
	Mat feature_2 = net_1.forward();
	printf("=> features extracted.\n");

	// vector dot
	double dot = feature_1.dot(feature_2);
	//printf("dot: %.3f", dot);

	// L2 norm
	double feature_1_norm = norm(feature_1, NORM_L2);
	double feature_2_norm = norm(feature_2, NORM_L2);

	// cosine similarity
	double sim = dot / (feature_1_norm * feature_2_norm);
	printf("\n=> similarity: %.5f\n", sim);

	return 0;
}

**Comment by CaptainEven** [comment]
The network is Resnet-18. I have tested blobFromImages and use setIput only once, the result is correct. So i suspect the problem is caused by setInput() which failed when called twice.

**Comment by dkurt** [comment]
@CaptainEven, You can help us to solve your problem much faster uploaded mentioned model to some files storage.

**Comment by CaptainEven** [comment]
@dkurt The whole test VS project link is as follows:
https://pan.baidu.com/s/1OI7BHdL32ZRTlHXaYlo5Ww
including test code and all models.
