### ISSUE TITLE
Using cv::kmeans with flag cv::KMEANS_USE_INITIAL_LABELS produces exception

### ISSUE THREAD

**Issue by bielu000** [opencv/opencv#13109]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => GNU/Linux Debian 9 
- Compiler => gcc

##### Detailed description

Using cv::kmeans with flag cv::KMEANS_USE_INITIAL_LABELS produces exception:

```
(-215:Assertion failed) (unsigned)_labels.at<int>(i) < (unsigned)K
```

in path: opencv/opencv/modules/core/src/kmeans.cpp:257:

The asset instruction below produces exception:

>             CV_Assert((unsigned)_labels.at<int>(i) < (unsigned)K);

But if I make the same assertion before calling kmeans it does not produce exception.

```
    cv::Mat in(200, 100, CV_32F);

    cv::Mat labels(10, 1, CV_32S);

    cv::Mat centers;

    for (int i = 0; i < 10; ++i) {
        labels.at<int>(i) = i + 2;
    }`  



    int N = 10;
    int K = 100;

    cv::InputOutputArray _bestLabels(labels);

    _bestLabels.create(N, 1, CV_32S, -1, true);

    cv::Mat _labels, best_labels = _bestLabels.getMat();

        CV_Assert( (best_labels.cols == 1 || best_labels.rows == 1) &&
                   best_labels.cols*best_labels.rows == N &&
                   best_labels.type() == CV_32S &&
                   best_labels.isContinuous());
        best_labels.reshape(1, N).copyTo(_labels);
        for (int i = 0; i < N; i++)
        {
            CV_Assert((unsigned)_labels.at<int>(i) < (unsigned)K); // the same assert as in cv::kmeans.cpp 
        }// Any exceptions here


    cv::kmeans(in, 100, _labels, cv::TermCriteria(cv::TermCriteria::MAX_ITER + cv::TermCriteria::EPS, 300, 0.0001), 20, cv::KMEANS_USE_INITIAL_LABELS, centers);

// the exception has been thrown

```

This behavior is not pretty understable. 

###Steps to reproduce 
 
If it is not bug, please add an example of using KMEANS_INITIAL_LABELS in documentantion, to be clear enough.

**Comment by alalek** [comment]
Refer to OpenCV tests.

**Comment by bielu000** [comment]
> Refer to OpenCV tests.

I can't find any test case where you tests kmeans with KMEANS_USE_INITIAL_LABELS.

**Comment by catree** [comment]
@bielu000 Looks like there is this [test file](https://github.com/opencv/opencv/blob/master/modules/ml/test/test_emknearestkmeans.cpp)?

**Comment by bielu000** [comment]
@catree yep you're right. I was looking in another directory (https://github.com/opencv/opencv/tree/master/modules/core/test), because my error was from there. 

I have one more question.

Is there any possibility to "predict" labels using centers computed before?

Something like in sklearn:
kmeans.fit_predict - compute centers, and labels
kmeans.predict -> compute labels, based on centers computed above

**Comment by alalek** [comment]
> cv::Mat in(200, 100, CV_32F);
> int N = 10;

You don't have 10 samples only.
Input has 200 samples.

> _bestLabels.create(N, 1, CV_32S, -1, true);

Resized with garbage inside.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
