### ISSUE TITLE
Assertion failed of blob data-type when import caffe model in opencv 4.0 beta

### ISSUE THREAD

**Issue by CaptainEven** [opencv/opencv#13119]
##### System information (version)

- OpenCV => :4.0beta:
- Operating System / Platform => :Windows 10 64 bit:
- Compiler => :Visual studio 2017:

##### Detailed description
Assertion failed when import caffe model, the message is as follws:

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.0-beta) Error: Assertion failed (pbBlob.raw_data_type() == caffe::FLOAT16) in cv::dnn::dnn4_v20180917::`anonymous-namespace'::CaffeImporter::blobFromProto, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\caffe\caffe_importer.cpp, line 264

##### Steps to reproduce
const String model_desc = "../resnet18.prototxt";
const String model_binary = "../resnet18.caffemodel";

int test_caffe()
{

	// init model
	Net net = readNetFromCaffe(model_desc, model_binary);
	if (net.empty())
	{
		printf("=> load net failed.\n");
		return -1;
	}

	return 0;
}

int main()
{
	//test_onnx();
	test_caffe();
	printf("=> Test done.\n");
	system("pause");

	return 0;
}

**Comment by dkurt** [comment]
@CaptainEven, Please provide source of `resnet18.prototxt` and `resnet18.caffemodel` files. This is a bug tracker and an every report should be reproducible.

**Comment by CaptainEven** [comment]
@dkurt Thank you for replying,  The zip file of caffe model was uploaded.

[resnet18_caffe_model.zip](https://github.com/opencv/opencv/files/2570799/resnet18_caffe_model.zip)

**Comment by dkurt** [comment]
@CaptainEven, Just for experiment, try to run this model in Caffe and check an output from the first Convolution layer named `103` for the same input. It looks to me that you'll get different outputs because this layer has no weights in `.caffemodel` so Caffe will generate it randomly.

**Comment by CaptainEven** [comment]
@dkurt Thank you for your suggestion. I' ll have a try.

**Comment by dkurt** [comment]
@CaptainEven, I'm not able to run this model even in Caffe. Please fix it first and then try to load in into OpenCV.

It looks to me there is no issue related with OpenCV right now. Please close an issue if so.

**Comment by CaptainEven** [comment]
@dkurt Hi, I 'v tested it myself for in caffe with python interface and the result is correct as onnx model. My test code is as follows:

# coding=utf-8

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import time

import caffe


# cosine similarity
def cosin_metric(x1, x2):
    return np.dot(x1, x2) / (np.linalg.norm(x1) * np.linalg.norm(x2))


check_root = '/mnt/diskc/even/Car_DR/ArcFace_pytorch/checkpoints/'
model_desc = check_root + 'resnet18-pytorch2caffe.prototxt'
model_binary = check_root + 'resnet18-pytorch2caffe.caffemodel'

imgs_dir = '/mnt/diskc/even/test_car_match_imgs'
img_1 = imgs_dir + '/' + 'img_1.jpg'
img_2 = imgs_dir + '/' + 'img_5.jpg'

if not os.path.isfile(img_1) or \
        not os.path.isfile(img_2):
    print('=> invalid file.')
    sys.exit()

# cpu mode
caffe.set_mode_cpu()
net = caffe.Classifier(model_desc, model_binary)

# load img data
print('=> sim between %s and %s' % (img_1, img_2))
inp_1 = caffe.io.load_image(img_1)
inp_2 = caffe.io.load_image(img_2)

# predict features
feature_1 = net.predict([inp_1], oversample=False)
feature_2 = net.predict([inp_2], oversample=False)
feature_1 = feature_1[0]
feature_2 = feature_2[0]

# calculate feature similarity
sim = cosin_metric(feature_1, feature_2)
print(sim)

Test results are as follws:
=> sim between /mnt/diskc/even/test_car_match_imgs/img_1.jpg and /mnt/diskc/even/test_car_match_imgs/img_5.jpg
0.061114438  (for img_1.jpg and img_5.jpg)

=> sim between /mnt/diskc/even/test_car_match_imgs/img_1.jpg and /mnt/diskc/even/test_car_match_imgs/img_2.jpg
0.9437494  (for img_1.jpg and img_2.jpg)

**Comment by dkurt** [comment]
@CaptainEven. which version of Caffe is used?

**Comment by dkurt** [comment]
Closing it due no response from author
