### ISSUE TITLE
Memory out of bound in dist.h

### ISSUE THREAD

**Issue by kaijung** [opencv/opencv#13129]
##### System information (version)

- OpenCV => Any version:
- Operating System / Platform => Windows 64 Bit and Windows 32 Bit
- Compiler =>  Visual Studio 2015

##### Detailed description

dist.h compile without NEON or GNUC

It will cause Memory out of bound Error!!
Because size * sizeof(pop_t), larger than original size

https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/flann/include/opencv2/flann/dist.h#L468

**Comment by alalek** [comment]
Could you share minimal reproducer for this?

BTW, You can report this to upstream repository too: https://github.com/mariusmuja/flann/blob/ad352b7f42aa768d55dc8133f60d395c6dc156db/src/cpp/flann/algorithms/dist.h#L522

**Comment by kaijung** [comment]
minimal reproducer is here

https://github.com/kaijung/testHamming

Please, trace into the code

https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/flann/include/opencv2/flann/dist.h#L389

The size is 40, larger than original size 5

https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/flann/include/opencv2/flann/dist.h#L403

For loop will let i from 0 to 40

https://github.com/kaijung/testHamming/blob/master/testHamming.cpp#L10

But the original array size is 5

https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/flann/include/opencv2/flann/dist.h#L468

The reason is because sizeof(pop_t) is 8, 5*8=40

The Attachment is my visual studio 2015's screenshot 

![2018-11-13 12 27 03](https://user-images.githubusercontent.com/8910115/48391135-37822780-e740-11e8-95c8-39c78b396bdf.png)
