### ISSUE TITLE
CAP_PROP_WHITE_BALANCE_BLUE_U

### ISSUE THREAD

**Issue by gheogoijfdgfjlkfd** [opencv/opencv#13130]
CAP_PROP_WHITE_BALANCE_BLUE_U 

is still unsupported. can this PLEASE be supported?

and also a way to disable AUTO CAP_PROP_WHITE_BALANCE_BLUE_U 

now i manually use every time i start the computer:

myVideoCapture.set(CV_CAP_PROP_SETTINGS, 1)

but i need a way to do it programmatically.

thanks!

**Comment by JordanWa** [comment]
Is there any documentation that explains why CV_CAP_PROP_WHITE_BALANCE_BLUE_U is not supported?

I've been playing with this and surprisingly I can read this setting with cv::VideoCapture.get(), but I'm still unable to set it (using the DShow backend). In noticing this odd behavior I decided to take a peek at code for the opencv DShow backend and found that the setting is implemented both in the [get](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_dshow.cpp#L3387) and [set](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_dshow.cpp#L3527) methods.

I'll probably keep playing with this, but it seems like there is either a disconnect between opencv and dshow (IAMVideoProcAmp, really) [here](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_dshow.cpp#L1786-L1877) or there is a deeper issue that may or may not be machine specific.

**Comment by gheogoijfdgfjlkfd** [comment]
Thanks JordanWa! Yes eventually i also used DShow and it works, but it took a lot of struggling to find out how. Hope OpenCV fixes this.

**Comment by TIS-Stefan** [comment]
It seems, that in cap_dshow.cpp in line 1949
`
hr = pIAMCameraControl->Set(Property, lValue, Flags);
`
Flags is always 0, which does not seem to be a valid value. Drivers validate this valued will return an error in hr.

The function using that is defined as

`bool setVideoSettingFilter(int deviceID, long Property, long lValue, long **Flags = 0,** bool useDefaultValue = false);
`
Where flags is 0 by default. Setting that to 2 could do the job, but does not sound for a read good idea. However, these functions are marked as experimental for now.
(For testing we disabled the validation of Flags in our driver and thus are able to set white balance successfully.)
