### ISSUE TITLE
With openpose.cpp nparts is not 19 but 57

### ISSUE THREAD

**Issue by defaulTomo** [opencv/opencv#13141]
## Contents

openpose.cppの問題について書きます．COCOデータセットを用いた場合npartsは19になると書かれていますが57になりました．そのため148行目でエラーが発生します．原因としてはcoco bodyにPAF mapsが加わっているためです(19+2*19)．私は105行目から110行目を次のように書き替えるとopenposeは正常に動作しました．

I will write about the issue of openpose.cpp. When using the COCO dataset nparts is written to be 19 but it has become 57. Therefore, an error occurs at line 148. This is because PAF maps are added to coco body (19 + 2 * 19). I changed the 105th line to 110th line as follows, openpose worked normally.
-------------------------------------------------------------------------
		if (nparts == 19 || nparts==57)
		{   // COCO body
			nparts = 19;
			midx = 0;
			npairs = 17;
			nparts = 18; // skip background
		}
-------------------------------------------------------------------------

## Execution environment

Windows 10 pro
Visual Studio 2017
OpenCV 4.0.0 beta
GPU unused

## Reproduction procedure

新規プロジェクトを作成しopencv.cppの内容をコピー．CommandLineParserは使わないようにプログラムを変更．使用したcaffeのネットワークは"pose/coco/pose_deploy_linevec.prototxt"と"pose/coco/pose_iter_440000.caffemodel"．

Create a new project and copy the contents of opencv.cpp. Change the program so that CommandLineParser does not use it. The network of caffe used is "pose / coco / pose_deploy_linevec.prototxt" and "pose / coco / pose_iter _ 440000.caffemodel".

## Expected results

エラーが発生して止まる．上に書いた変更を行うとエラーは発生しなくなる．

An error occurs and it stops. If you make the changes you made above, no error will occur.

**Comment by berak** [comment]
you should use the https://raw.githubusercontent.com/opencv/opencv_extra/master/testdata/dnn/openpose_pose_coco.prototxt  (which is reduced / optimized to a single person) , not the (original) pose_deploy_linevec.prototxt, which indeed tries to read the PAF maps.

**Comment by dkurt** [comment]
@defaulTomo, We've merged a PR which fixes it: https://github.com/opencv/opencv/pull/13486. Thank you!
