### ISSUE TITLE
In place matrix conversion with IPP: Error

### ISSUE THREAD

**Issue by mgopshtein** [opencv/opencv#13149]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

Some functions (e.g. `calcHist`) write the following line to the output log in Debugger:
`Exception thrown at 0x00007FFE85AFA388 in EWSDKAppCon.exe: Microsoft C++ exception: ipp::IwException at memory location 0x000000B72ECF09D8.`

The code apparently continues to run (see also issue #9718), but:

- Exceptions may introduce performance hit
- Please see more details below - not sure the code always does the correct thing

The last command of `cv::calcHist` is:
`ihist.convertTo(hist, CV_32F);`
Note that in this case the `ihist.data` is same as `hist.data`

Next the code reaches `ipp_convertTo` and calls:
`CV_INSTRUMENT_FUN_IPP(::ipp::iwiScale, iwSrc, iwDst, alpha, beta, ::ipp::IwiScaleParams(mode));`

`iwiScale` method of IPP library returns an error in the following lines:

    if((pSrcImage->m_ptrConst == pDstImage->m_ptrConst) && (pSrcImage->m_dataType != pDstImage->m_dataType))
        return ippStsInplaceModeNotSupportedErr;

Because the `m_ptrConst` pointers are the same - **in place** conversion.

That causes an exception to be throws, printed to Debug log, and caught.

Eventually `ipp_convertTo` returns _false_ but this status seems to be ignored inside
`cv::Mat::convertTo(OutputArray _dst, int _type, double alpha, double beta)`
this is a reason I'm suspicious that in some cases this behavior is incorrect, it changes the type of the destination matrix without actually modifying the data.

##### Steps to reproduce

Simple use of `calcHist`:

    int hbins = 64;
    int histSize[] = { hbins };
    float hranges[] = { 0,255 };
    const float* ranges[] = { hranges };
    Mat hist;
    int channels[] = { 0 };
    calcHist(&smallImage, 1, channels, Mat(), // do not use mask
        hist, 1, histSize, ranges,
        true, // the histogram is uniform
        false);

Thanks

**Comment by alalek** [comment]
> 3.4.3

Avoid using of outdated releases.

> printed to Debug log

It is MSVS debugger stuff.

> may introduce performance hit

Mentioned hit is not measured yet.

---

If you want to report a bug then please provide complete minimal reproducer with actual and expected results.
Raised and handled internal exception doesn't mean to lead for invalid results.
