### ISSUE TITLE
trace_profiler.py    parentLocation = self.locations[parentTask.locationID]

### ISSUE THREAD

**Issue by peter-zigo-nxp** [opencv/opencv#13161]
Hi,

I found problem in 
parentLocation = self.locations[parentTask.locationID]

In python script:
https://github.com/opencv/opencv/blob/master/modules/ts/misc/trace_profiler.py

* Read the documentation to test with the latest developer build.
* Check if other person has already created the same issue to avoid duplicates. You can comment on it if there already is an issue.
* Try to be as detailed as possible in your report.
* Report only one problem per created issue.

##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform =linux 64 Bit
- Compiler =GCC
-->

##### Detailed description
I found problem in 
parentLocation = self.locations[parentTask.locationID]

In python script:
https://github.com/opencv/opencv/blob/master/modules/ts/misc/trace_profiler.py

first I found problem in read file string
https://github.com/opencv/opencv/blob/3.4.1/modules/ts/misc/trace_profiler.py#L164
This I fix by put whole name in variable: 
filename = 'OpenCVTrace-000.txt'; before was '/OpenCVTrace-000.txt'
But after that I still get error 
Traceback (most recent call last):
  File "trace_profiler.py", line 442, in <module>
    trace.process()
  File "trace_profiler.py", line 287, in process
    parentLocation = self.locations[parentTask.locationID]
KeyError: 1

It show that dict is empty.
Test report file can by find in attachment.

-->

used command:
python trace_profiler.py /home/root/opencv_dnn_bench/trace/OpenCVTrace.txt
[OpenCVTrace.txt](https://github.com/opencv/opencv/files/2580605/OpenCVTrace.txt)
[OpenCVTrace-000.txt](https://github.com/opencv/opencv/files/2580606/OpenCVTrace-000.txt)

**Comment by peter-zigo-nxp** [comment]
Hi Alexander,

I have found that it is absolute path and I removed OpenCVTrace-000.txt
But I have problem to measure time in opencl function.
I set environmental var.
OPENCV_TRACE_DEPTH_OPENCV - specify trace depth of OpenCV functions
0 - limit is disabled
and OPENCV_TRACE_SYNC_OPENCL to 1

Can you help me with this problem ?
Thank for answer.

Peter Z.

**Comment by alalek** [comment]
OpenCL kernels are asynchronous. Time measurement of them is not reliable for now (forced synchronous mode via clFinish() calls has significant overhead).
