### ISSUE TITLE
Build errors from C interface removal

### ISSUE THREAD

**Issue by melrobin** [opencv/opencv#13172]
##### System information (version)

- OpenCV => :grey_question: 4.0.0
- Operating System / Platform => :grey_question: Fedora 27
- Compiler => :grey_question: gcc 7.3

##### Detailed description
There was a change less than a week ago where the C interface for some modules were removed.  This has caused some build errors that you should be aware.  There are many errors of this sort and the build fails.

/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h:96:28: error: redeclaration of ‘CV_IMWRITE_PXM_BINARY’
     CV_IMWRITE_PXM_BINARY =32,
                            ^~

##### Steps to reproduce

Build from developer sources.

**Comment by alalek** [comment]
> imgcodecs_c.h

There is no such file anymore on "master" branch. C API is gone (almost). Do not use these files in your code.
`imgcodecs_c.h` is grabbed from another installation of OpenCV.
Perhaps uncontrolled "sudo make install" leaves garbage in your system and you need to cleanup.

**Comment by melrobin** [comment]
I can build now.  I needed to update opencv_contrib as well.  Closing
