### ISSUE TITLE
filter2D crashes when using ROI and kernel size > 11

### ISSUE THREAD

**Issue by jpsml** [opencv/opencv#13179]
##### System information (version)
- OpenCV 3.4.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

The code below is crashing for kernel sizes > 11, if kernel size is <= 11 it works.

##### Steps to reproduce

```.cpp
    #include <opencv2/opencv.hpp>
    
    int main()
    {
	cv::Mat image = cv::imread("lena.jpg");

	cv::Mat kernel = cv::getGaborKernel(cv::Size(13, 13), 8, 0, 3, 0.25);  // if changed to cv::Size(11, 11), it works

	cv::Mat roi(image, cv::Rect(0, 0, 128, 128));

	cv::Mat filtered(128, 128, roi.type());
	cv::filter2D(roi, filtered, -1, kernel);

	cv::imshow("image", image);
	cv::imshow("filtered", filtered);

	cv::waitKey();

	return 0;
    }
```

**Comment by alalek** [comment]
Thank you for the report!

regression after #11551

**Comment by csggnn** [comment]
I am having the same problem on Linux Ubuntu 18.04, on opencv 4.1.0 in python, installed via `conda install -c conda-forge opencv=4.1.0`

**Comment by mshabunin** [comment]
@csggnn , the fix has not been released yet. You should wait until next official release (4.1.1).

**Comment by CBaiz** [comment]
@mshabunin 
As a side note, this happended to me with CV_8U and filter sizes >= 9.
OpenCV version: 4.1.0.
Might be relevant since the original issue specifically described kernel sizes > 11.

**Comment by Raghavendra-Srinivas** [comment]
I observed same error on OpenCV  4.1.1 as well..Anybody knows the fix please..I am suing Ubuntu 18.04.3 LTS and filter > 11 fails with segmentation fault with cv2.filter2D.
