### ISSUE TITLE
cv2.copyMakeBorder segmentation fault

### ISSUE THREAD

**Issue by snk4tr** [opencv/opencv#13180]
##### System information (version)
- operating system:
Ubuntu 16.04 (64-bit) in Docker 18.09.0.

- architecture (e.g. x86):
Intel® Core™ i5-7500 CPU @ 3.40GHz × 4.

- opencv-python version:
opencv-python==3.4.3.18

##### Detailed description

- Expected behavior:
`ValueError: passed image has wrong shape. Expected to have 3 dimensions, has 4.`
(or any other type of error with the similar description)

- Actual behavior:
`31807 segmentation fault (core dumped)`

- Description:
This issue was first opened in [opencv-python repository](https://github.com/skvark/opencv-python/issues/143). Since input data checks neither performed  on Python-level  nor on C-level usage of 4-D and greater tensors causes uninformative errors.

##### Steps to reproduce

```python
import cv2
import numpy as np

# Example image. 
# May also be an image loaded with opencv-python with np.expand_dims(img, 0) or similar.
img = np.zeros((1, 256, 256, 3), dtype=np.uint8)
cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=[0, 0, 0])
```

**Comment by muyuuuu** [comment]
same problem:

```
cv::Mat img_ref101(
    cv::Size(IMAGE_WIDTH + LEFT + RIGHT, IMAGE_HEIGHT + TOP + BOTTOM),
    CV_8UC1);

cv::copyMakeBorder(img_origin, img_ref101, 1, 1, 1, 1, cv::BORDER_REFLECT_101);

// Segmentation fault (core dumped)
```
