### ISSUE TITLE
OpenCv 2.4.13.2 resize CV_16UC3 image will shuffle channels

### ISSUE THREAD

**Issue by derek99401** [opencv/opencv#13190]
##### System information (version)
- OpenCV => 2.4.13.2
- Operating System / Platform => Ubuntu 14.04 64-bit
- Compiler => g++ (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5

##### Detailed description

When resize CV_16UC3 image of a constant color with INTER_LINEAR, the resized image had shuffled channel values. 

original image with size 8x4
[10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000]

resized image with size 16x8
[10000, 20000, 30000, **10000, 30000, 10000,** 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 10000, 20000, 30000, 10000, 30000, 10000, 20000, 30000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000]

Notice how the bolded pixel is not [10000, 20000, 30000], as it should have been.

Resize does not have this problem when interpolation is set to INTER_NEAREST. Or when image type is CV_8UC3, or CV_16UC4.

##### Steps to reproduce
```
int main(int argc, char** argv) {
  int width = 8;
  int height = 4;
  constexpr int kBlueVal = 30000, kGreenVal = 20000, kRedVal = 10000;
  cv::Vec<uint16_t, 3>* multi_channel_row_ptr;
  cv::Mat image(height, width, CV_16UC3);
  for (int row = 0; row < height; ++row) {
    multi_channel_row_ptr = image.ptr<cv::Vec<uint16_t, 3> >(row);
    for (int col = 0; col < width; ++col) {
      multi_channel_row_ptr[col] = cv::Vec<uint16_t, 3>(kRedVal, kGreenVal, kBlueVal);
    }   
  }
  cv::Mat big_image(2*height, 2*width, image.type());
  std::cout << image << std::endl;
  cv::resize(image, big_image, big_image.size(), 0, 0, cv::INTER_LINEAR);
  std::cout << big_image << std::endl;
  cv::imshow("image", image);
  cv::imshow("big_image", big_image);
  cv::waitKey(0);

  return 0;
}
```

**Comment by dkurt** [comment]
Cannot reproduce it with the latest state of 2.4 branch (6ed571b3c69ee5a91b3bb4e99ec358b45a74f71e).

```
[10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000]

[10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000;
  10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000, 10000, 20000, 30000]
```
