### ISSUE TITLE
Contours2 doesn't work

### ISSUE THREAD

**Issue by Aquatica1000** [opencv/opencv#13198]
- OpenCV => 4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Dev-C++ 5.11

##### Detailed description

I've been working on using OpenCV with regards to a school project.  I've downloaded and installed it onto my computer, set it up to work with Dev-C++, and tried to run the contours2 cpp sample to make sure I had everything working as planned.  Unfortunately, I have received the error "'Mat' in namespace 'cv' does not name a type," originating in the "types" header.  While I am somewhat knowledgeable in C++, I am new to OpenCV and not entirely sure how to fix this without inadvertently messing things up further.  Does anyone have suggestions?

##### Steps to reproduce

[Program and headers used.zip](https://github.com/opencv/opencv/files/2592377/Program.and.headers.used.zip)

**Comment by alalek** [comment]
Build/Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by Aquatica1000** [comment]
Oh dear.  Sorry about that, then.
