### ISSUE TITLE
multiple C1083 (cannot find source file)

### ISSUE THREAD

**Issue by mprevot** [opencv/opencv#13204]
I'm having multiple 1083 errors, such as:

c1xx : fatal error C1083: Cannot open source file: 'I:\opencv-master\opencv\3rdparty\openexr\Imath\ImathFun.cpp': No such file or directory [I:\opencv-master\build\3rdparty\openexr\IlmImf.vcxproj]

even though the file cpp is present. I managed to build opencv 4 (head/trunk) multiple times until recently with this configuration.

##### System information (version)
- OpenCV => 4.0.0-dev (4.0.0-1-g59e2ca16d)
- Operating System / Platform => Windows 10 64 enterprise (17.134 / 1803)
- Compiler => Visual Studio 2017 15.9.1 (vcvars64.bat -vcvars_ver=14.16.27023)

- cmake configuration:

`cmake -G $target -T v141, host=x64 -j8 -DBUILD_JAVA=0 -DWITH_MATLAB=0 -DBUILD_DOC=0 -DBUILD_PERF_TESTS=0 -DBUILD_TESTS=0 -DBUILD_opencv_world=0 -DOPENCV_ENABLE_NONFREE=1 -DBUILD_opencv-apps=0 -DENABLE_PYLINT=0 -DENABLE_CXX11=0 -DWITH_VTK=1 -DCUDA_SDK_ROOT_DIR="$env:CUDA_PATH" -DCUDA_ARCH_BIN="5.2" -DCUDA_VERBOSE_BUILD=0 -DBUILD_CUDA_STUBS=0 -DWITH_OPENCL=1 -DWITH_CUDA=1 -DMKL_WITH_OPENMP=0 -DMKL_WITH_TBB=0 -DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules"
-DINSTALL_CREATE_DISTRIB=1 -DCPACK_BINARY_ZIP=1 -DCPACK_SOURCE_ZIP=1 -DCMAKE_VERBOSE_MAKEFILE=0 ../opencv | Tee-Object -Variable RESULT`

- build command:

`msbuild.exe OpenCV.sln /verbosity:m /m`

**Comment by mprevot** [comment]
It might be a VS issue, or actually a cmake one (https://stackoverflow.com/questions/16422883/error-c1083-cannot-open-source-file-shouldnt-be-looking-for-the-file-at-all)

**Comment by alalek** [comment]
What is CMake version?
Could you try without `-DWITH_CUDA=1` (with `-DWITH_CUDA=0`) ?

**Comment by mprevot** [comment]
I got same symptoms with cmake 3.12, 3.13, and `-DWITH_CUDA=0` (cuda 9.2 and 10).

_Before_ Build was succeeding with cmake 3.12 and cuda 9.2.

**Comment by alalek** [comment]
Can't reproduce on our CI with CMake 3.12.4: http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/10648/steps/cmake/logs/stdio

(try to remove "-T" option)

**Comment by mprevot** [comment]
It might be a VS issue, or actually a cmake one (https://stackoverflow.com/questions/16422883/error-c1083-cannot-open-source-file-shouldnt-be-looking-for-the-file-at-all)

I'll check the case per forlder issue, since I'm getting sources with git from WSL (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1083?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C1083)%26rd%3Dtrue&view=vs-2017#additional-causes)

**Comment by mprevot** [comment]
I think it is resolved. I downloaded the zip and did everything without going through the linux sub system of windows (WSL) and did not experienced the error; it was the "case sensitivity" introduced by WSL; even though the case of the path was correct. There is womething wrong happening there.

Two ways to resolve this:
- avoid case sensitivity in Windows if we use a mix of WSL programs (such as git) and Windows programs (msbuild, cmake)
- avoid any WSL world and do everything in Windows
