### ISSUE TITLE
OpenCV 4 with OpenMP

### ISSUE THREAD

**Issue by huangqinjin** [opencv/opencv#13207]
##### System information (version)
- OpenCV => 3.4.4 and 4.0.0
- Operating System / Platform => Ubuntu 16.04 and openSUSE Tumbleweed 20181116
- Compiler => gcc 5.4.0 and gcc 8.2.1

##### Detailed description
I built opencv with openmp support,  then call `remap` in a thread, and got an error
```
libgomp: Out of memory allocating 927712937064 bytes
```

No error if I built opencv without openmp or call `remap` in main thread.

##### Steps to reproduce
build opencv with openmp:
```cmake
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_LIST=imgproc -DBUILD_PROTOBUF=OFF -DWITH_IPP=OFF -DWITH_OPENMP=ON
```

test program:
```cpp
#include <thread>
#include <opencv2/imgproc.hpp>

void test()
{
    using namespace cv;
    Mat img(400, 640, CV_8UC1);
    Mat map(img.size(), CV_32FC2);
    remap(img, img, map, Mat(), INTER_LINEAR);
}

int main()
{
    std::thread t(test);
    t.join();
}
```

**Comment by huangqinjin** [comment]
@alalek `doc/acircles_pattern.png` in opencv repositority.

**Comment by huangqinjin** [comment]
Same error with 3.4.4.

**Comment by alalek** [comment]
Can't reproduce on Fedora 28 with GCC 8.2.1 on both 3.4.4 / 4.0.0.

"time" result is 42Mb of memory usage in peak:
```
0.09user 0.01system 0:00.08elapsed 129%CPU (0avgtext+0avgdata 42320maxresident)k
```

**Comment by huangqinjin** [comment]
OK. I will do more tests soon.

**Comment by huangqinjin** [comment]
@alalek , same error with Fedora 29 / gcc 8.2.1 on VMWare and Ubuntu 18.04 / gcc 7.3.0 on MacBook.
