### ISSUE TITLE
error LNK2019 unresolved external symbol (opencv_cudev_main.obj) out of the box

### ISSUE THREAD

**Issue by mprevot** [opencv/opencv#13208]
Out of the box I'm having a link error.

##### System information (version)
- OpenCV: 4.0.0-dev
- Operating System / Platform: Windows 10 x64 enteprise
- Compiler:
   - Visual Studio 2017 15.9.1
   - vcvars64.bat -vcvars_ver=14.16.27023
   - cmake 3.13.0rc3
   - cuda 10.0

##### Detailed description

opencv_cudev_main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) bool cv::__termination" (__imp
_?__termination@cv@@3_NA) referenced in function DllMain [I:\opencv-master\build\modules\cudev\opencv_cudev.vcxproj]
I:\opencv-master\build\bin\Release\opencv_cudev400.dll : fatal error LNK1120: 1 unresolved externals [I:\opencv-master\
build\modules\cudev\opencv_cudev.vcxproj]

##### Steps to reproduce
`
$target = "Visual Studio 15 2017 Win64"; 
cmake -G $target -T v141, host=x64 -j8 -DBUILD_JAVA=0 -DWITH_MATLAB=0 -DBUILD_DOC=0 -DBUILD_PERF_TESTS=0 -DBUILD_TESTS=0 -DBUILD_opencv_world=0 -DOPENCV_ENABLE_NONFREE=1 -DBUILD_opencv-apps=0 -DENABLE_PYLINT=0 -DENABLE_CXX11=0 -DWITH_VTK=1 -DCUDA_SDK_ROOT_DIR="$env:CUDA_PATH" -DCUDA_ARCH_BIN="5.2" -DCUDA_VERBOSE_BUILD=0 -DBUILD_CUDA_STUBS=0 -DWITH_OPENCL=1 -DWITH_CUDA=1 -DMKL_WITH_OPENMP=0 -DMKL_WITH_TBB=0 -DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" 	-DINSTALL_CREATE_DISTRIB=1 -DCPACK_BINARY_ZIP=1 -DCPACK_SOURCE_ZIP=1 -DCMAKE_VERBOSE_MAKEFILE=0 ../opencv | Tee-Object -Variable RESULT
`

**Comment by Bleach665** [comment]
@mprevot, with #12865
