### ISSUE TITLE
imgcodecs/legacy/constants_c.h header is not installed

### ISSUE THREAD

**Issue by antonio-rojas** [opencv/opencv#13201]
#### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Linux x86_64
- Compiler => GCC

##### Detailed description

imgcodecs/imgcodecs_c.h states: "This header with legacy C API declarations has been removed from OpenCV. Legacy contants are available from legacy/constants_c.h file." However, this file is not being installed.

**Comment by berak** [comment]
similar problem for videoio and photo, none of the `opencv2/module/legacy/constants_c.h` files are copied

(master / win10 / mingw64)

**Comment by sakthigeek** [comment]
I'm getting the same error for the latest master. I'm trying to build darknet and this error prevents it from building successfully. Any other solution for this?

**Comment by miaotsi** [comment]
Same problem.

**Comment by cjds** [comment]
me too

**Comment by myboyhood** [comment]
The 3.4.10 version has no `legacy/constants_c.h` file, I change to this
```c
// #include <opencv2/imgcodecs/legacy/constants_c.h> // origin
#include <opencv2/imgcodecs/imgcodecs_c.h> // change this will work
```
