### ISSUE TITLE
cv::CommandLineParser cannot parse int values

### ISSUE THREAD

**Issue by pzoltowski** [opencv/opencv#13212]
-->

##### System information (version)
- OpenCV => 4.0 rc1
- Operating System / Platform => MacOS 10.13.6 (high sierra)
- Compiler => default macos compiler (build according to instructions on https://github.com/opencv/opencv_contrib)
##### Detailed description

cv::CommandLineParser cannot parse [int] values and treat them as [boolean]

I've tested on the following examples from aruco:
./example_aruco_create_marker
./example_aruco_create_diamond

Couldn't find fast any example in non contrib repo that takes required [int] parameter and doesn't have default values to test on examples on main opencv repo.

##### Steps to reproduce

	
MacBook-Pro:bin pzo$ ./example_aruco_create_marker -d 0 --id id1 --ms 150 --si

ERRORS:
Parameter 'd': can not convert: [true] to [int]
Parameter 'id': can not convert: [true] to [int]
Parameter 'ms': can not convert: [true] to [int]

MacBook-Pro:bin pzo$ ./example_aruco_create_marker -d 0.0 --id id1 --ms 150.0 --si

ERRORS:
Parameter 'd': can not convert: [true] to [int]
Parameter 'id': can not convert: [true] to [int]
Parameter 'ms': can not convert: [true] to [int]

MacBook-Pro:bin pzo$ ./example_aruco_create_diamond -d 0.0 --ml 140.0 --si --sl 140.0 out.png --ids id1,id2,id3,id4

ERRORS:
Parameter 'sl': can not convert: [true] to [int]
Parameter 'ml': can not convert: [true] to [int]
Parameter 'd': can not convert: [true] to [int]

MacBook-Pro:bin pzo$ ./example_aruco_create_diamond -d 0 --ml 140 --si --sl 140 out.png --ids id1,id2,id3,id4

ERRORS:
Parameter 'sl': can not convert: [true] to [int]
Parameter 'ml': can not convert: [true] to [int]
Parameter 'd': can not convert: [true] to [int]

**Comment by alalek** [comment]
Missing equal sign: `-d=0`
