### ISSUE TITLE
DISOpticalFlow results bad

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#13225]
I tested the DISOpticalFlow example code provided by OpenCV 4.0.0
The results look very uninterpretable. Like some noisy colorful pattern, but northing that is interpretable as an optical flow result. The results from the paper look very promising but i cannot reproduce them at all.

Here a test result where i moved the camera a bit sideways:
![grafik](https://user-images.githubusercontent.com/4457821/48791566-48a7d700-ecf2-11e8-9eb6-7399924cb7ea.png)

I used the preset parameters which should be fine as described in the documentation:
https://docs.opencv.org/4.0.0/de/d4f/classcv_1_1DISOpticalFlow.html

It seems buggy to me. I tested multiple times with different image resolutions. Does this algorithm work for anybody at all?

**Comment by vikasguptaiisc** [comment]
It would be better if you post the code as well

**Comment by tompollok** [comment]
https://github.com/opencv/opencv/blob/master/samples/cpp/dis_opticalflow.cpp

**Comment by tompollok** [comment]
I am using OpenCV 4.0.0 on Windows 10

I copied it into my image processing framework so i am not running the binary that you are running, but i just have copied the code. The only extra code that i do is memcopying my image data into the cv::Mat image data. 
Are you using 4.0.0?

**Comment by tompollok** [comment]
unsigned char* data = image->data();
const int width = image->width();
const int height = image->height();
const int channels = image->channels();

if(!image->empty())
{
    //convert image data to cv::Mat
    cv::Mat mat(height, width, channels==3?CV_8UC3:CV_8UC1);
    memcpy(mat.data, data, image->size());


    if(mat.channels()==3)
    {
        cv::cvtColor(mat, gray, cv::COLOR_RGB2GRAY);
    }
    else if(mat.channels()==1)
    {
        gray = mat.clone();
    }
    else
    {
        throw std::runtime_error("image channels != 1 && != 3");
    }


    if (!prevgray.empty())
    {
        algorithm->calc(prevgray, gray, flow);
        cv::split(flow, flow_uv);
        cv::multiply(flow_uv[1], -1, flow_uv[1]);
        cv::cartToPolar(flow_uv[0], flow_uv[1], mag, ang, true);
        cv::normalize(mag, mag, 0, 1, cv::NORM_MINMAX);
        hsv_split[0] = ang;
        hsv_split[1] = mag;
        hsv_split[2] = cv::Mat::ones(ang.size(), ang.type());
        cv::merge(hsv_split, 3, hsv);
        cv::cvtColor(hsv, rgb, cv::COLOR_HSV2BGR);
    }

    mOutputImage.resize(rgb.cols, rgb.rows, rgb.channels());
    memcpy(mOutputImage.data(), rgb.data, mOutputImage.size());

    std::swap(prevgray, gray);

}

**Comment by mshabunin** [comment]
You can not memcpy one image to another. Use copyTo and ROI for this or, better, vconcat function.

**Comment by tompollok** [comment]
Why not? I have done this for years and i never had any problems with that at all - at least in opencv 3.x

**Comment by tompollok** [comment]
Also my image is not an opencv image, its a custom image type that has a pointer to an unsigned char with the same size as the image (width*height*channels).

**Comment by mshabunin** [comment]
@tompollok , there are some reports pointing to unstable behavior on smaller image sizes: opencv/opencv_contrib#1507 Maybe this is your case?

**Comment by tompollok** [comment]
I tried it with various image sizes. 1920*1200 and smaller sizes. The results for all resolutions looked similarly weird.

I think my image was misleading to you. What you see there is actually two images. the input image and the rgb flow image. Both have the resolution that is shown below the images. But it has nothing to do with concatenation of two images. It just looks in the viewer as if they are concatenated.

Did you use master or 4.0.0? I will try the original example soon, but i wonder how you have seen any outputs from cv::imshow(...) because it does not work for rgb images in 4.0.0 - see https://github.com/opencv/opencv/issues/13216

**Comment by mshabunin** [comment]
@tompollok , I ran it on _master_, that issue has been fixed there already.

**Comment by tompollok** [comment]
I tested it on master.
Example works perfectly.
So i checked the rgb data type:

cv::cvtColor(hsv, rgb, cv::COLOR_HSV2RGB); creates a cv::Mat with type 21 which is CV_32FC3

My problem was that i expected it to be CV_8UC3

cv::imshow automatically converts it to CV_8UC3

Sorry for reporting this issue, but its not intuitive to me that cv::cvtColor(hsv, rgb, cv::COLOR_HSV2BGR) leads to a non 8bit image. But I guess it makes sense that it supports those conversions for float and double etc aswell
