### ISSUE TITLE
Import error cv2.so: undefined symbol: _ZN2cv8Stitcher17estimateTransformERKNS_11_InputArrayE

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#13226]
##### System information (version)

- OpenCV => Latest 4.0.0 (Master Branch) 
- Operating System / Platform => Ubuntu 18.04.1 LTS
- Compiler => GCC 7.3.0

##### Detailed description

All Python Bindings Seems Broken:(See below)

Python 2.7.15rc1:
```
abhishek@abhishek-HP-Pavilion-Notebook:~/Downloads/opencv-master/build_tbb$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _ZN2cv8Stitcher17estimateTransformERKNS_11_InputArrayE
>>> 
```
Python 3.6.6:
```
abhishek@abhishek-HP-Pavilion-Notebook:~/Downloads/opencv-master/build_tbb$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.6/dist-packages/cv2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv8Stitcher17estimateTransformERKNS_11_InputArrayE
>>> 
```

##### Debug Files:
Strace: 
[python2.txt](https://github.com/opencv/opencv/files/2601226/python2.txt)
[python3.txt](https://github.com/opencv/opencv/files/2601227/python3.txt)

**Comment by alalek** [comment]
How did you get these bindings?

**Comment by abhiTronix** [comment]
@alalek Solved it myself. 

 **Wrong installation path for `cv2.so`**(Screenshot Below) lib for **python** in OpenCV [must be`/usr/local/lib/python2.7/dist-packages\cv2.so instead`], **Kindly correct this bug**. Thankyou

![screenshot from 2018-11-22 11-07-41](https://user-images.githubusercontent.com/34266896/48883851-b285c500-ee47-11e8-9423-f2ed93073ba9.png)

**Comment by alalek** [comment]
Be careful with multiple calls of "make install" - they didn't uninstall previous versions so your system become inconsistent.
For development it is enough to use build directory. Please leave "make install" for package maintainers.

Python path changes are here: #13202

**Comment by abhiTronix** [comment]
@alalek 

> Be careful with multiple calls of "make install" - they didn't uninstall previous versions so your system become inconsistent.

Yes, that was the problem indeed. I uninstalled any previous file related to OpenCV and built the latest commit successfully today. The new features like Vulkan backend DNN are awesome!!!!

> Python path changes are here: #13202

Yes, I made Python path changes as suggested in #13202 and used the default(old) configuration by commands as below:
```
OPENCV_SKIP_PYTHON_LOADER=ON
OPENCV_PYTHON_INSTALL_PATH=...site/dist-packages location...
```
**But still the Python 2.7 binding lib[cv2.so] was installed at the wrong destination(as seen in my screenshot), whereas Python 3.6 bindings where installed at the correct place(i.e. _/usr/local/lib/python2.7/dist-packages/cv2.cpython-36m-x86_64-linux-gnu.so_). There is still a bug or something wrong with python 2.7 path. I moved the file[cv2.so] manually as a workaround and everything is ok now**

**Comment by harinduravin** [comment]
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ace/anaconda3/envs/tf1/lib/python3.7/site-packages/cv2/__init__.py", line 129, in <module>
    bootstrap()
  File "/home/ace/anaconda3/envs/tf1/lib/python3.7/site-packages/cv2/__init__.py", line 112, in bootstrap
    import cv2
ImportError: /home/ace/anaconda3/envs/tf1/lib/libopencv_text.so.4.5: undefined symbol: _ZGVbN2v___log_finite




Getting a similar type of error. Unable to figure out.
