### ISSUE TITLE
Opencv (3.2.0) Compile Android with NEON provide a lot of errors (3.4.4 Works)

### ISSUE THREAD

**Issue by simonprovost** [opencv/opencv#13220]
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Linux Ubuntu 16.04 / Android - 7 , ARM (armeabiv7-a)
- Compiler => Clang 5.0
- Opti => NEON (if possible) 

- Android STL => c++_static
- NDK VERSION => NDK 15c
- API LEVEL => 24
#####

Hello, recently I have compiled Opencv 3.2.0 for Android, ARM with Android StandAlone Toolchain and not the toolchain provide with Opencv source.

It works perfectly, excepted one thing, the optimization is disable and when I want to use opencv it's too slower, then I have chosen the NEON optimization with the correct Toolchain (provide from Opencv 3.2.0 source /platform/android/)

To that, I have launched cmake-GUI, and create a build with Opencv Android Toolchain, but we encountered a lot of errors, only in "configure cmakelists" for beginning, like: 

> CMAKE_MAKE_PROGRAMM: NOT FOUND.
> CMAKE_C(And CXX)_COMPILER: NOT FOUND.

And I can say that, a lot of other error like this type, that I have solved by hand added in the cmakelists or with "entry" button in cmake-GUI.

After first "make" of generating project, I have met a lot of errors which said that a file was not found like: 

```
[  0%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_aux.c.o
In file included from opencv-3.2.0/3rdparty/libtiff/tif_aux.c:32:
/3rdparty/libtiff/tiffiop.h:56:48: error: unknown type name 'size_t'
extern void *lfind(const void *, const void *, size_t *, size_t,
                                               ^
opencv-3.2.0/3rdparty/libtiff/tiffiop.h:56:58: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
extern void *lfind(const void *, const void *, size_t *, size_t,
                                                         ^
In file included from opencv-3.2.0/3rdparty/libtiff/tif_aux.c:32:
In file included from opencv-3.2.0/3rdparty/libtiff/tiffiop.h:60:
opencv-3.2.0/3rdparty/libtiff/tiffio.h:67:9: error: unknown type name 'size_t'
typedef TIFF_SSIZE_T tmsize_t;
        ^
opencv-3.2.0/build_test_16_nov/3rdparty/libtiff/tif_config.h:121:22: note: expanded from macro 'TIFF_SSIZE_T'
#define TIFF_SSIZE_T size_t
                     ^
opencv-3.2.0/3rdparty/libtiff/tif_aux.c:32:
opencv-3.2.0/3rdparty/libtiff/tiffiop.h:60:
opencv-3.2.0/3rdparty/libtiff/tiffio.h:258:
Android/Sdk/ndk-bundle/platforms/android-24/arch-arm/usr/include/stdio.h:50:
Android/Sdk/ndk-bundle/platforms/android-24/arch-arm/usr/include/sys/types.h:31:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 warning and 3 errors generated.
```

My question is, We can compile opencv 3.2.0 with NEON with Opencv Android Toolchain ? 

I didn't know if the toolchain provide with this opencv works well or not ? I didn't know anything like how to solve it ? 

If someone has an idea? or method plan to compile that, I will be very grateful.
Thanks a lot guys advance. Have a good day !

**Comment by alalek** [comment]
> 3.2.0

This release is very old.

You should try to use some fresh version from 3.4 branch.

**Comment by simonprovost** [comment]
@alalek 

Right, i agree with you but, i can't use another branch, i use 3.2.0 only this version..

Regards.

**Comment by simonprovost** [comment]
@alalek  

Ok, I was test to built it.

But I have met first three errors : 

> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  >CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
>CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
>CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

I can handle these errors but could you tell me if it's normal errors or not ?

Regards.

**Comment by alalek** [comment]
Build logs for 3.4.4 is [here](http://pullrequest.opencv.org/buildbot/builders/3_4_pack-android/builds/212).
Dockerfile (with list of packages) for build container is [here](https://github.com/opencv-infrastructure/opencv-worker-config/blob/linux/images/android--14.04/docker/Dockerfile).

**Comment by simonprovost** [comment]
@alalek Your build Logs says nothing, or I assume that I probably not found the output log of the build, I have a lot of green lines but they says nothing.

Could you tell me more ?
Thank you !

**Comment by simonprovost** [comment]
Great, Thank you !! 
i'll check it.

**Comment by simonprovost** [comment]
@Alalek 

Thanks for that, it was very helpful to check and understand.
However, I've met a problem : 

With your config : 

> cmake -DCMAKE_TOOLCHAIN_FILE=/home/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/Android/Sdk/ndk-bundle/ -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON" -DBUILD_JAVA=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_EXAMPLES=OFF -DENABLE_NEON=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_CXX_COMPILER=/home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -DCMAKE_C_COMPILER=/home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  ..

I've met these errors : 
```
-- The CXX compiler identification is GNU 4.9.0
-- The C compiler identification is GNU 4.9.0
-- Check for working CXX compiler: /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
-- Check for working CXX compiler: /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -- broken
CMake Error at /usr/local/share/cmake-3.11/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/Documents/opencv-3.4.4/build_01/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_eadb7/fast"
    /usr/bin/make -f CMakeFiles/cmTC_eadb7.dir/build.make CMakeFiles/cmTC_eadb7.dir/build
    make[1]: Entering directory '/home/Documents/opencv-3.4.4/build_01/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_eadb7.dir/testCXXCompiler.cxx.o
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++    -fPIE   -o CMakeFiles/cmTC_eadb7.dir/testCXXCompiler.cxx.o -c /home/Documents/opencv-3.4.4/build_01/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_eadb7
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_eadb7.dir/link.txt --verbose=1
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++       -rdynamic CMakeFiles/cmTC_eadb7.dir/testCXXCompiler.cxx.o  -o cmTC_eadb7 
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lstdc++
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
    /home/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_eadb7.dir/build.make:86: recipe for target 'cmTC_eadb7' failed
    make[1]: *** [cmTC_eadb7] Error 1
    make[1]: Leaving directory '/home/Documents/opencv-3.4.4/build_01/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_eadb7/fast' failed
    make: *** [cmTC_eadb7/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:131 (project)
```


With Clang compiler : 

> cmake -DCMAKE_TOOLCHAIN_FILE=/home/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/Android/Sdk/ndk-bundle/ -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON" -DBUILD_JAVA=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_EXAMPLES=OFF -DENABLE_NEON=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_CXX_COMPILER=/home/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -DCMAKE_C_COMPILER=/home/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang   ..

```
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:460 (message):
  Required baseline optimization is not supported: NEON
  (CPU_BASELINE_REQUIRE=;NEON)
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:266 (include)
  CMakeLists.txt:565 (include)
```


What do you think with that ? 

Thanks !

**Comment by alalek** [comment]
These options should not be used normally:
- `CMAKE_MAKE_PROGRAM` (specified via CMake generator)
- `CMAKE_C_COMPILER` / `CMAKE_CXX_COMPILER` (just settings of these two is not enough, toolchain must perform extra work - like switch "sysroot" to selected ARM platform)

Also verify your local files: CMakeFiles/CMakeOutput.log CMakeFiles/CMakeError.log for details.

**Comment by simonprovost** [comment]
@alalek 

That's solved, I'm tired with these error, I've delete the cache and set CMAKE_MAKE_PROGRAM=[...] etc ;)

But we can see my problem above.

**Comment by simonprovost** [comment]
@alalek  The compile of the library is successful !! Thank you for the tips.

However, i've meet a few undefined reference, such as : 

```
  error: undefined reference to 'cv::read(cv::FileNode const&, std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&)'
  error: undefined reference to 'cv::write(cv::FileStorage&, cv::String const&, std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> > const&)'
  error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&, int)'
  error: undefined reference to 'cv::read(cv::FileNode const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
  error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&, int)'
  error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&, int)'
  error: undefined reference to 'cv::DescriptorMatcher::knnMatch(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> >, std::__ndk1::allocator<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> > > >&, int, cv::_InputArray const&, bool) const'
  error: undefined reference to 'cv::DescriptorMatcher::knnMatch(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> >, std::__ndk1::allocator<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> > > >&, int, cv::_InputArray const&, bool) const'
  error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&, int)'
  error: undefined reference to 'cv::DescriptorMatcher::knnMatch(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> >, std::__ndk1::allocator<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> > > >&, int, cv::_InputArray const&, bool) const'
  error: undefined reference to 'cv::DescriptorMatcher::knnMatch(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> >, std::__ndk1::allocator<std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> > > >&, int, cv::_InputArray const&, bool) const'
  error: undefined reference to 'cv::drawKeypoints(cv::_InputArray const&, std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> > const&, cv::_InputOutputArray const&, cv::Scalar_<double> const&, int)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

With OPENCV 4.0.0 with NEON and OPENCV 3.4.4 with NEON.
Do you have an idea ?

**Comment by simonprovost** [comment]
Thanks for all @alalek 

The answer for this "post" is no more no less than in 3.2.0 it's too hard to compile with NEON.

However in 3.4.4 it works with this command line : 

`cmake -G "Unix Makefiles" -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DWITH_NEON=ON -DWITH_EIGEN=ON -DWITH_OPENCL=ON -DBUILD_opencv_gpu=OFF -DCMAKE_TOOLCHAIN_FILE=/home/Documents/opencv-3.4.4/platforms/android/android.toolchain.cmake  -DCMAKE_MAKE_PROGRAM=/home//Android/Sdk/ndk-bundle/prebuilt/linux-x86_64/bin/make -DANDROID_AdBI="armeabi-v7a with NEON" -DOPENCV_EXTRA_MODULES_PATH=/home/Documents/opencv_contrib-3.4.4/modules/ -DBUILD_opencv_features2d=ON -DBUILD_opencv_ximgproc=ON -DBUILD_opencv_java=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCXXFLAGS="-Wall -fpu=neon -O3" -DBUILD_JAVA=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DEIGEN_INCLUDE_PATH=/home/Android/Dependencies/Android/Eigen_3.3.4/include/eigen3/ -DANDROID_NATIVE_API_LEVEL=24 -DCMAKE_ANDROID_API_MIN=24 .. `

Thanks for help and have a good day.
