### ISSUE TITLE
OpenCV4 createsamples and traincascade are missing from build/apps

### ISSUE THREAD

**Issue by ChernyshovYuriy** [opencv/opencv#13231]
Hey,
I built opencv 4.0.0 with

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D BUILD_opencv_apps=ON \
    -D OPENCV_EXTRA_MODULES_PATH=<path_to...>/modules ..

However, in "build/app" there are no createsamples and traincascade. There are annotation, interractive-calibration, version and visualisation only.
These folders are present in <opencv_src>/apps.
OS - Ubuntu 16.06 LTS

Versions 3.4.X worked fine.

Is this changed recently?

**Comment by ChernyshovYuriy** [comment]
Thanks a lot for quick response!
I am going to close this ticket, however, would be good to have some kind of text document placed in "build/apps" with the same explanation, so people like me will not be confused in future :-)

**Comment by StevenPuttemans** [comment]
@alalek 

> Also modern approaches via DNN provides much better results - just compare OpenCV face detector with CascadeClassifier and DNN.
> So these apps are candidates to removal.

I agree that these algorithms are old, and not up to date, but removing them? Cascade Classifiers have nowadays still several implementations and applications in tons of fields. Yes DL is a valid alternative, but removing them from OpenCV, seeing how much documentation out there (books, courses, ...) use it as a base for classic CV, this will generate a shitload of similar discussions ...

**Comment by tow70** [comment]
If opencv_createsamples and opencv_traincascade are obsolete, how can I train a classifier? Or are CascadeClassifier and detectMultiScale also obsolete?

**Comment by StevenPuttemans** [comment]
@tow70 
- You can revert back to version 3.4, which does contain the functionality
- You can pick up the GSoC2019 proposal for reintegrating this functionality in an updated manner :)

**Comment by tow70** [comment]
@StevenPuttemans 

Thanks for the quick reply! For testing purposes I will keep my 3.4 installation. I'm not a programmer, so it will be better to keep my hands off the GSoC 2019 proposal.

One intention of my request was to find an alternative tool to opencv_traincascade to generate the cascade.xml. Perhaps someone has a hint or a weblink.

**Comment by StevenPuttemans** [comment]
If you want the cascade to be used by an opencv software package, then 3.4 is the only solution.

**Comment by vpisarev** [comment]
If there are volunteers for that, opencv_createsamples and opencv_traincascade can be updated to compile with OpenCV 4. For now, it's perfectly fine to download and build OpenCV 3.4 side by side with OpenCV 4.0, take opencv_createsamples and opencv_traincascade from OpenCV 3.4 to create the  models. Those models can then be used with OpenCV 3.x and OpenCV 4.x - no problem!

**Comment by iruriksl** [comment]
> opencv_createsamples

opencv_createsamples is building perfect with vision 4.2 master. Only problems in opencv_traincascades is there to work voluntarily as this seems important.
Hopethis information helps many others. 
I will try to volunteer for the fixing opencv_traincascade apps of opencv

**Comment by makingglitches** [comment]
So... haar cascaders are still there and the trained models.. sort of working.
but... the way of training the cascader is no longer there ?
there was mention of other methods that more up to date ?

bit behind the curve so i'm confused how to utilize this lib if a pretty big part of it is no longer valid.

what tool combinations should i be using to create specific search models for specific types of objects ?

**Comment by Kreijstal** [comment]
how do I train a cascade classifier in opencv without mixing versions?

**Comment by berak** [comment]
@Kreijstal 
* git checkout the 3.4  branch
* cmake && make (just do NOT run 'make install')
* run the cascade tools from `build/bin` to train your cascade
* throw away the build folder & checkout some 4.x branch again

**Comment by Kreijstal** [comment]
> @Kreijstal
> 
>     * git checkout the 3.4  branch
> 
>     * cmake && make (just do NOT run 'make install')
> 
>     * run the cascade tools from `build/bin` to train your cascade
> 
>     * throw away the build folder & checkout some 4.x branch again

I think this is precisely what I was trying to avoid, I guess there is no way to not mix the versions, aka no way to train cascade with a current modern version, shame.

**Comment by schardong** [comment]
@Kreijstal 
Well, the `traincascade` binary did not compile for me as per version 4.5.5, only `createsamples` did without errors. I just checked-out the 4.5.5 branch and uncommented line 57 in the `apps/CMakeLists.txt` file, built opencv using `cmake && make`, as per @berak and that was it actually. The binary is inside the `build/bin` directory.

If you want to use the `traincascade` binary, I'm afraid you will have to revert to version 3.4, just don't install it after the build, so it won't pollute your setup.

**Comment by fdivitto** [comment]
Hello,
I've just added a Pull Request to fix traincascade application.


#23393

**Comment by 71walceli** [comment]
Would you recommend this one for Docker? https://stackoverflow.com/a/36864891

 Is there a more recent one for Python 3?

**Comment by 71walceli** [comment]
Unsurprisingly for me, build failed on step 5 because one of those packages was missing:

```
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Package 'libav-tools' has no installation candidate
E: Unable to locate package libjasper-dev
The command '/bin/sh -c apt-get update && apt-get install -y     wget     build-essential     cmake     git     unzip     pkg-config     python-dev     python-opencv     libopencv-dev     libav-tools      libjpeg-dev     libpng-dev     libtiff-dev     libjasper-dev     libgtk2.0-dev     python-numpy     python-pycurl     libatlas-base-dev     gfortran     webp     python-opencv     qt5-default     libvtk6-dev     zlib1g-dev' returned a non-zero code: 100
```
