### ISSUE TITLE
Canny()--memory leak

### ISSUE THREAD

**Issue by AIHEKUKAFEIDEXIAOAFEI** [opencv/opencv#13234]
- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu16.04 64 Bit

##### Detailed description
I have used the function --Canny(), but it brings me the problem of mem leak.
How do I know the mem leak? I have used the tool--Valgrind to test.

##### Steps to reproduce

    canny_test.cpp
    // C++ code example
    #include <iostream>
    #include <opencv2/opencv.hpp>

   int main()
  {
     cv::Mat src = imread("test.png", 0);
     cv::Mat canny;
     cv::Canny(src, canny, 0, 255);
     return 0;
 }

srcreen capture

![mem_leak_canny](https://user-images.githubusercontent.com/36781570/48829569-87e72e00-edad-11e8-9887-d29806fd0512.PNG)

**Comment by alalek** [comment]
You should suppress these warnings.
