### ISSUE TITLE
deeplabv3+mv2 in opencv4.0

### ISSUE THREAD

**Issue by gwang92** [opencv/opencv#13247]
opencv version: 4.0.0
model :deeplab3+ mv2
Operating System : Linux 64bit Ubuntu 16.04

Detailed description
I tried to apply tensorflow deeplab v3+mv2 official model with the OpenCV DNN in C++,the test code is
`
#include <opencv2/opencv.hpp>
#include "opencv2/dnn.hpp"
#include "iostream"
#include "opencv2/dnn/layer.details.hpp"
using namespace cv;
using namespace dnn;
using namespace std;
int main(){
    string model = "/home/crwon/snow/MobileNetV2/frozen_inference_graph_transf.pb";
    string pbtxt = "/home/crwon/snow/MobileNetV2/frozen_inference_graph_transf.pbtxt";

    // Read image
    Mat imgOrig = imread("/home/crwon/program/segment/7.jpg");
    imgOrig.convertTo(imgOrig, CV_8UC3);
    // Resize image
    Mat img;
    resize(imgOrig, img, Size(513, 513));

    // Read model
    // Net net = readNet(model, config, framework);
    Net graph = readNet(model,pbtxt);
    
    // Get blob from image
    Mat blob = blobFromImage(img, 4.0, Size(513, 513), Scalar(), true, false);
    
    // Set the input tensor
    std::string inBlobName = "ImageTensor";
    std::string outBlobName = "SemanticPredictions";
    graph.setInput(blob,ImageTensor);
   
    Mat detectionOut = graph.forward();

    imwrite("result.jpg",detectionOut);
   
    return 0;
}`
but I always got this error:
what(): OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:773: error: (-2:Unspecified error) Tensor's data type is not supported in function 'getTensorContent'

before this , I optimize for inference.pb like this:
opencv/opencv#12715
According to dkurt commented, I use the optimization code,but still have this question:
what(): OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:773: error: (-2:Unspecified error) Tensor's data type is not supported in function 'getTensorContent'
 can you help me ?

**Comment by dkurt** [comment]
@gwang92, Please make your report reproducible. Put references to all the files are used in your code sample. At least `frozen_inference_graph_transf.pb` and `frozen_inference_graph_transf.pbtxt`.

**Comment by gwang92** [comment]
@dkurt 
Firstly I try use the official model, export pbtxt 
```
    import tensorflow as tf
    with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
      for i in reversed(range(len(graph_def.node))):
        if graph_def.node[i].op == 'Const':
            del graph_def.node[i]

       for attr in ['T', 'data_format', 'Tshape', 'N', 'Tidx', 'Tdim',
                 'use_cudnn_on_gpu', 'Index', 'Tperm', 'is_training',
                 'Tpaddings']:
           if attr in graph_def.node[i].attr:
               del graph_def.node[i].attr[attr]
    tf.train.write_graph(graph_def, "", "frozen_inference_graph.pbtxt", as_text=True)
```
there was error:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_importer.cpp:1153: error: (-213:The function/feature is not implemented) Unsupported squeeze configuration in function 'populateNet'

then I transformed the pb model use tensorflow 's code
tensorflow/tensorflow/tools/graph_transforms/transform_graph.cc
with command line and export the transform pbtxt
`bazel run tensorflow/tools/graph_transforms:transform_graph -- --in_graph="frozen_inference_graph_opt.pb" --out_graph="frozen_inference_graph_transf.pb" --inputs="ImageTensor" --outputs="SemanticPredictions" --transforms="fold_constants sort_by_execution_order remove_nodes(op=Squeeze)"`
there was error:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:773: error: (-2:Unspecified error) Tensor's data type is not supported in function 'getTensorContent'
and when I use your optimization code in official model or transform model  and export the optimization pbtxt:
```
graph = 'frozen_inference_graph_trasf.pb'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.summary.FileWriter('logs', graph_def)
    inp_node = 'ImageTensor'
    out_node = 'SemanticPredictions'
    graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def, [inp_node], [out_node], tf.float32.as_datatype_enum)
    graph_def = TransformGraph(graph_def, [inp_node], [out_node])
 
with tf.gfile.FastGFile('frozen_inference_graph_trasf_opt.pb', 'wb') as f:
    f.write(graph_def.SerializeToString())
```
it was the same error:
Tensor's data type is not supported in function 'getTensorContent'
can you help me?

**Comment by dkurt** [comment]
@gwang92, What means official model? Your issue should follow our guidelines and should be reproducible. Please attach `frozen_inference_graph_trasf.pb'` mentioned in the code snippet.

**Comment by dkurt** [comment]
Closing it due no response from author.
