### ISSUE TITLE
tf_text_graph_ssd.py fail on tensorflow trained ssd_mobilenet model

### ISSUE THREAD

**Issue by nardaweissman** [opencv/opencv#13249]
##### Detailed description

I try to create pbtxt out of pb.

##### Steps to reproduce
I run tf_text_graph_ssd.py on frozen_inference_graph.pb pipeline.config 

I get
Traceback (most recent call last):
  File "D:\TFS\LPR\IP\MAIN\SRC\PythonProjects\TensorFlow\UseModelZoo\tf_text_graph_ssd.py", line 276, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "D:\TFS\LPR\IP\MAIN\SRC\PythonProjects\TensorFlow\UseModelZoo\tf_text_graph_ssd.py", line 27, in createSSDGraph
    config = config['model'][0]['ssd'][0]
KeyError: 'ssd'

This is a link to my files:
https://www.dropbox.com/sh/dh1c325m0t22qsn/AAAJRfedjbF0uMsTLWyS6uVYa?dl=0

**Comment by dkurt** [comment]
For Faster-RCNN object models use Faster-RCNN [tf_text_graph_faster_rcnn.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_faster_rcnn.py).

[tf_text_graph_ssd.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py) is for SSD models.
