### ISSUE TITLE
error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'

### ISSUE THREAD

**Issue by YashHatekar** [opencv/opencv#13250]
##### System information (version)

- OpenCV => 3.4.1 Android SDK
- Operating System / Platform => Windows 64 Bit (for coding), arm64-v8a for trying out the app
- Compiler =>  Android studio 3.2.1

##### Detailed description

I am trying to make an app for face detection and eye detection on android using opencv.
but every time i try to build the project using ndk-build it is giving me error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'

i have attached the files along with the issue

##### Steps to reproduce
just start a new project and add the code

[OpencvClass.txt](https://github.com/opencv/opencv/files/2608100/OpencvClass.txt)
[MainActivity .txt](https://github.com/opencv/opencv/files/2608101/MainActivity.txt)
[jni.zip](https://github.com/opencv/opencv/files/2608106/jni.zip)

-->
My NDK is configured properly because i can run simple programs.

**Comment by alalek** [comment]
> build the project

Used NDKs should be compatible for OpenCV build itself and for application build too.

**Comment by YashHatekar** [comment]
I am using the latest NDK i.e r18b

**Comment by alalek** [comment]
OpenCV Android package has been [built](http://pullrequest.opencv.org/buildbot/builders/3_4_pack-android/builds/212) with GCC (GCC is dropped from NDK 18) and with NDK10e.

You can try to built SDK (native part only) yourself with NDK18 using of these scripts: https://github.com/opencv/opencv/tree/master/platforms/android (specify `ndk-17.config.py`, it should be compatible with NDK18).
Also you need CMake and "ninija-build".

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by MaryAnnZ** [comment]
If it is not necessary to have the newest NDK you could downgrade it. I had the same problem and a simple downgrade solved it, I can build without error now.
