### ISSUE TITLE
with cuda10.0 #warning message to remove device_functions.h.

### ISSUE THREAD

**Issue by Moore123** [opencv/opencv#13262]
##### System information (version)

- OpenCV => :4.0.0-alpha:
- Operating System / Platform => :Ubuntu18.04.1 LTS / x64:
- Compiler => :g++-5.5.0-12ubuntu1 20171010:
- Cuda => :release 10.0, V10.0.130:

##### Steps to reproduce
make 

with #warning message : 

In file included from /usr/local/src/opencv/modules/core/include/opencv2/core/cuda/functional.hpp:50:0,
                 from /usr/local/src/opencv_contrib/modules/cudaoptflow/src/cuda/pyrlk.cu:47:
/usr/local/cuda/include/device_functions.h:54:2: warning: #warning "device_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "device_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."

**Comment by coral26** [comment]
I received the same problem

**Comment by kajla** [comment]
Same here.

**Comment by wenrouruwanlian** [comment]
so，what should we do to solve the problem? help

**Comment by SamNew1** [comment]
same here, help!

**Comment by gridley** [comment]
pls halp nvidia
