### ISSUE TITLE
compile error with vulkan

### ISSUE THREAD

**Issue by dccho** [opencv/opencv#13277]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => clang++

##### Detailed description

I try to compile opencv 4.0 with vulkan for android. When I compile them, there is an error related to vulkan.

../modules/dnn/src/vkcom/src/op_base.cpp:48:43: error: variable-sized object may not be initialized
    VkDescriptorSetLayoutBinding bindings[buffer_num] = {};
                                          ^~~~~~~~~~

build script is 
[28/144] Building CXX object modules/d...cv_dnn.dir/src/vkcom/src/op_base.cpp.o
FAILED: /home/chan/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16 --gcc-toolchain=/home/chan/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/chan/Android/Sdk/ndk-bundle/sysroot  -DCVAPI_EXPORTS -DDISABLE_POSIX_MEMALIGN -DHAVE_PROTOBUF=1 -DTH_DISABLE_HEAP_TRACKING -DVK_NO_PROTOTYPES -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I. -I../3rdparty/include -I../modules/dnn/include -Imodules/dnn -I../modules/core/include -I../modules/imgproc/include -I../modules/dnn/misc/caffe -I../modules/dnn/misc/tensorflow -I../modules/dnn/misc/onnx -isystem ../3rdparty/protobuf/src -isystem /home/chan/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /home/chan/Android/Sdk/ndk-bundle/sources/android/support/include -isystem /home/chan/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /home/chan/Android/Sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security   -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith  -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -Oz -DNDEBUG   -DNDEBUG -fPIC   -std=c++11 -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_base.cpp.o -MF modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_base.cpp.o.d -o modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_base.cpp.o -c ../modules/dnn/src/vkcom/src/op_base.cpp

**Comment by dkurt** [comment]
@dccho, just for experiment, can you please replace
```cpp
void createDescriptorSetLayout(int buffer_num);
```
at https://github.com/opencv/opencv/blob/master/modules/dnn/src/vkcom/include/op_base.hpp

and
```cpp
void OpBase::createDescriptorSetLayout(int buffer_num)
```
from https://github.com/opencv/opencv/blob/master/modules/dnn/src/vkcom/src/op_base.cpp

to the following lines correspondingly.
```cpp
void createDescriptorSetLayout(const int buffer_num);
void OpBase::createDescriptorSetLayout(const int buffer_num)
```
Can it help to prevent compiler error?

**Comment by dccho** [comment]
@dkurt Unfortunately, No. Still same error

**Comment by pas-ipi** [comment]
Try to replace this string with 
auto bindings = new VkDescriptorSetLayoutBinding[buffer_num];

**Comment by dccho** [comment]
@pas-ipi  it works! but when allocated bindings should be deleted?

**Comment by dccho** [comment]
@alalek It looks better and no compile error. Thanks. I'll test vulkan for android more.
