### ISSUE TITLE
How to install opencv3 on ubuntu 16.04?

### ISSUE THREAD

**Issue by wyfSunflower** [opencv/opencv#13274]
I want to use yolo library on ubuntu 16.04 64bit, it depends on opencv,
how to install opencv is very sophisticated.
I  install the python version.
now in the virtual environment of python3.5 ,the following command can work
import cv2 as cv
but when I compile opencv cpp program demo with g++,it throw such error:
opencv2/core/core.hpp : No such file or directory

**Comment by dkurt** [comment]
@wyfSunflower, this is not a right place for questions. Please use a forum http://answers.opencv.org/.

Please note that we use GitHub issues for bugs reports and feature requests.
