### ISSUE TITLE
dnn::Net.forward() cause memory leak

### ISSUE THREAD

**Issue by LJXLJXLJX** [opencv/opencv#13284]
##### System information (version)
- OpenCV => 3.4.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

I am developing an program for character recognition.
I used CNN and trained my own model (.pb file) , and it worked well.

But when I compiled my program into a dll file, and call it in another program

```
typedef char*(*lpOcr)(char*, int, char*, char*); 

while (1)
	{
		HINSTANCE hDllOcr; 
		lpOcr ocrFun; 
		hDllOcr = LoadLibrary(TEXT("../Release/charRecognition.dll"));
		ocrFun = (lpOcr)GetProcAddress(hDllOcr, "mrzOcrAPI");
		ocrFun((char*)"../mrzImg.bmp", 0, (char*)"../models/mrz32.pb", (char*)"../mrz.txt");
		FreeLibrary(hDllOcr);
	}

```
some memory leaks happend. 

I have been debugging for a long time and found the problem statement.

```
Mat input;
resize(charImg, input, Size(32, 32));
Mat blob;
blobFromImage(input, blob, 1.0, Size(32, 32));
m_net.setInput(blob);
Mat logit = m_net.forward();   // m_net is a dnn::Net which have been initialized by readNet already.
```
If I comment out the last line of the statement , no memory leak will happen. 
But if I don't the memory leak will occur.
So I am sure the forward() cause the memory leak.

**Comment by alalek** [comment]
Some resources are not cleaned due OpenCV library unloading. It is not critical in normal usage (single .dll load per app).

Consider using singleton which holds loaded library handle.

**Comment by alalek** [comment]
You should load .DLL once. There is no real reason to load/unload it multiple times.

**Comment by kaanaykutkabakci** [comment]
Hello @LJXLJXLJX , did you find the solution?

**Comment by ndvbd** [comment]
Any solution to dnn::Net.forward() memory leak problems?

**Comment by sseeadsf** [comment]
Load in multi thread having same problem. 
@alalek having any idea ?

**Comment by maazullah96** [comment]
@alalek  Any solution regarding this issue I am facing the same problem.
