### ISSUE TITLE
Non-helpful Python references

### ISSUE THREAD

**Issue by hazarek** [opencv/opencv#13287]
OpenCV => 4.0.0 Python

There is no information about argument types, return types, optional arguments. For example;
![gaussian](https://user-images.githubusercontent.com/36481442/49037823-5070eb00-f1cc-11e8-9369-5a36fd81d7d6.png)

**Comment by duurkak** [comment]
Invalid Github issue tag. <img width="116" alt="tag" src="https://user-images.githubusercontent.com/36481442/49040332-51594b00-f1d3-11e8-9d20-d7ecac047ee0.png"> I have not asked a question. 

I have reported a serious problem.

**Comment by dkurt** [comment]
@duurkak, please share your vision of how it could looks like. In example, another python help message with argument types.

Optional arguments are marked by `[ ]`.
