### ISSUE TITLE
Ssh X Forwarding does not work

### ISSUE THREAD

**Issue by Kaju-Bubanja** [opencv/opencv#13286]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Ubuntu 16.04
- Compiler => Downloaded via: pip install opencv-python

##### Detailed description

Trying to view an image over ssh -x does not work. The script:
```
import cv2  
from PIL import Image  
img = cv2.imread("test.png", 1)
img2 = Image.fromarray(img, 'RGB')
cv2.imshow("Image", img)
img2.show()
```
cv2.imshow results in:
![cv2_bug](https://user-images.githubusercontent.com/6259829/49030423-8f407a00-f1a7-11e8-83a9-15d713fb840e.png)
but img2.show() results in:
![image](https://user-images.githubusercontent.com/6259829/49030450-a2534a00-f1a7-11e8-8bd6-b4be1625441d.png)

##### Steps to reproduce
Running this script over a ssh -X or -Y <"name">@<"host"> session
```
import cv2  
from PIL import Image  
img = cv2.imread("test.png", 1)
img2 = Image.fromarray(img, 'RGB')
cv2.imshow("Image", img)
img2.show()
```

**Comment by Viliami** [comment]
This might be fixed by adding `cv2.waitKey(1)` after the `cv2.imshow("Image", img)`
