### ISSUE TITLE
OpenCL kernel does not support access to isInProgress member

### ISSUE THREAD

**Issue by SteffenEhrle** [opencv/opencv#13295]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
OpenCL Kernel::Impl has a boolean member isInProgress, which is private.
When running custom Kernels, there is no way to check, if the Kernel object is still running from a last call (besides trying to run it. Inside the implementation it checks the isInProgress parameter and returns false if isInProgress is set). 
It would be very helpful to provide accessibility to the isInProgress parameter.

##### Steps to reproduce
Any custom Kernel run twice (so that it is still running while called) will fail with kernel.run() responding false.

**Comment by alalek** [comment]
For next `.run()` call create new one Kernel object.
Or call kernel in synchronous mode (not recommended).
Pooling value of isInProgress variable is a bad design solution, so it will not be added.
