### ISSUE TITLE
CHECK failed: (index) < (current_size_)

### ISSUE THREAD

**Issue by PinkyDemon** [opencv/opencv#13305]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.3.0

##### Detailed description
tf_importer.cpp line 1094 (if (value_id.find(layer.input(1)) != value_id.end())) fails with the error message "CHECK failed: (index) < (current_size_)"
at repeated_field.h line 1522 (GOOGLE_DCHECK_LT(index, current_size_);)
index and current_size_ are both 1
during loading a retrained inception_v2 mask RCNN

##### Steps to reproduce
Used the 2018 kaggle nucleus data to retrain the tensorflow inception_v2 mask RCNN model. Modified the pipeline.config file to a larger image size (min 512, max 1024), 1 class instead of 90, ROI proposals to max 2000 and some minor tweaks for less memory usage during training.
Trained and froze the model, sorted and generated pbtxt succesfully.
Loading to opencv fails.

**Comment by dkurt** [comment]
@PinkyDemon, please specify a config file which is used for training. Please note that none of the *_atrous models are not supported for now.

**Comment by PinkyDemon** [comment]
@dkurt, thanks for your reply. 
I was able to reproduce the error, here is the step by step process:
Downloaded the Mask-RCNN Inception v2 from here:
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

Retrained (2000 steps) with the attached config.
`python ~/dnn/models/research/object_detection/model_main.py --pipeline_config_path=${HOME}/dnn/train2/pipeline.config --model_dir ${HOME}/dnn/train2/output/ --alsologtostderr
`

exported the graph:
`python models/research/object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path train2/pipeline.config --trained_checkpoint_prefix train2/output/model.ckpt-2000 --output_directory train2/export/
`

generated text graph:
`python ~/dev/opencv-4.0.0/samples/dnn/tf_text_graph_mask_rcnn.py --input train2/export/frozen_inference_graph.pb --config train2/export/pipeline.config --output train2/export/graph.pbtxt`

on `cv::dnn::readNetFromTensorflow` call `tf_importer.cpp` fails with the above error on line 1094 with li==187


[config.zip](https://github.com/opencv/opencv/files/2624392/config.zip)

**Comment by dkurt** [comment]
@PinkyDemon, Is it possible to share a binary model `.pb`? If not, please initialize it's weights randomly.

**Comment by PinkyDemon** [comment]
@dkurt
You can find all files in the following folder, the final model is in the export directory
https://mega.nz/#F!jkojVQAA!FZ2dsDAu9DTqxs1kaAa5Xg

**Comment by dkurt** [comment]
@PinkyDemon, it looks like you need to follow this guide: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

Briefly:

1. Run `tf_text_graph_mask_rcnn.py` script from samples/dnn directory to generate a `.pbtxt` file
```
python tf_text_graph_mask_rcnn.py --input frozen_inference_graph.pb --output graph.pbtxt --config pipeline.config
```

2. Try OpenCV's sample for Mask-RCNN network: `mask_rcnn.py`
```
python mask_rcnn.py --input /path/to/image --model frozen_inference_graph.pb --config graph.pbtxt
```

output:
![out](https://user-images.githubusercontent.com/25801568/49786235-2410af00-fd34-11e8-8dcd-a9ea61daa1f3.png)


Please let me close this issue.
