### ISSUE TITLE
Support for Squeeze & Gather operations in DNN

### ISSUE THREAD

**Issue by BloodAxe** [opencv/opencv#13303]
When trying to import ONNX model that has `Squeeze` or `Gather` ops, application crashes with exception:
```
OpenCV(4.0.0) Error: Requested object was not found (Blob 3 not found in const blobs) in cv::dnn::dnn4_v20180917::ONNXImporter::getBlob, file D:\Develop\opencv\opencv\sources\modules\dnn\src\onnx\onnx_importer.cpp, line 272
```

##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- Pytorch 0.4.1 / Pytorch 1.0 RC / ONNX 0.1.13

##### Detailed description

A model exported in ONNX format from PyTorch cannot be imported in OpenCV. After digging, it seems that the problem caused by operations like `onnx::Squeeze` or `onnx::Gather` which are not supported by OpenCV. 

##### Steps to reproduce

```.python
from __future__ import print_function

import torch
from torch import nn
from torch.autograd import Variable


class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, image):
        batch_size = image.size(0)
        channels = image.size(1)
        image = image.permute(0, 2, 3, 1).contiguous().view(batch_size, -1, channels)
        return image


input_names = ['image']
output_names = ['pixels']

model = SimpleNet()
dummy_input = Variable(torch.randn(1, 3, 512, 512))

if torch.cuda.is_available():
    dummy_input = dummy_input.cuda()
    model = model.cuda()

torch.onnx.export(model, dummy_input, 'export/test.onnx',
                  verbose=True,
                  input_names=input_names,
                  output_names=output_names,
                  export_params=True)
```

This produces a following ONNX graph:

```.txt
graph(%image : Float(1, 3, 512, 512)) {
  %1 : Dynamic = onnx::Shape(%image), scope: SimpleNet
  %2 : Dynamic = onnx::Slice[axes=[0], ends=[1], starts=[0]](%1), scope: SimpleNet
  %3 : Long() = onnx::Squeeze[axes=[0]](%2), scope: SimpleNet
  %4 : Dynamic = onnx::Shape(%image), scope: SimpleNet
  %5 : Dynamic = onnx::Slice[axes=[0], ends=[2], starts=[1]](%4), scope: SimpleNet
  %6 : Long() = onnx::Squeeze[axes=[0]](%5), scope: SimpleNet
  %7 : Float(1, 512, 512, 3) = onnx::Transpose[perm=[0, 2, 3, 1]](%image), scope: SimpleNet
  %8 : Long() = onnx::Constant[value={-1}](), scope: SimpleNet
  %9 : Dynamic = onnx::Unsqueeze[axes=[0]](%3), scope: SimpleNet
  %10 : Dynamic = onnx::Unsqueeze[axes=[0]](%8), scope: SimpleNet
  %11 : Dynamic = onnx::Unsqueeze[axes=[0]](%6), scope: SimpleNet
  %12 : Dynamic = onnx::Concat[axis=0](%9, %10, %11), scope: SimpleNet
  %pixels : Float(1, 262144, 3) = onnx::Reshape(%7, %12), scope: SimpleNet
  return (%pixels);
}
```

Next line will trigger an exception in ONNXImporter:
```.cpp
auto net = cv::dnn::readNetFromONNX("export/test.onnx");
```

```
OpenCV(4.0.0) Error: Requested object was not found (Blob 3 not found in const blobs) in cv::dnn::dnn4_v20180917::ONNXImporter::getBlob, file D:\Develop\opencv\opencv\sources\modules\dnn\src\onnx\onnx_importer.cpp, line 272
```

This issue has been reproduced using models exported with PyTorch 0.4.1 (Emits Squeeze op) and on PyTorch 1.0RC (Emits Gather op). Both fails with same exception message.

**Comment by dkurt** [comment]
related: https://github.com/opencv/opencv/issues/12869

The thing is that Squeeze and Gather are not deep learning layers in terms of OpenCV (or Caffe, in example). However some of frameworks use this operations for different internal computations (in example, operations on shapes). We already had an experience with enabling such kind of graphs from TensorFlow and there are two approaches: graph transformations replacing most common subgraph patterns to single DL layer and creating text graph representation (as .caffemodel and .prototxt pair in Caffe) which users can modify to match OpenCV's expectations.

**Comment by dkurt** [comment]
We need to know if resulting graph is correct and there is no bug in Pytorch's ONNX exporter.

As for me it's a kind of strange when all the shapes are determined but ONNX graph includes nodes which do the same computations every time. Is there a way to fuse constant operations in Pytorch before export?

It'd be nice to have something like this:
```
graph(%image : Float(1, 3, 512, 512)) {
  %1 : Float(1, 512, 512, 3) = onnx::Transpose[perm=[0, 2, 3, 1]](%image), scope: SimpleNet
  %2 : Dynamic = onnx::Constant[value= 1 -1  3 [ CPULongType{3} ]](), scope: SimpleNet
  %pixels : Float(1, 262144, 3) = onnx::Reshape(%1, %2), scope: SimpleNet
  return (%pixels);
}
```
(received by using `batch_size = int(image.size(0))` and `channels = int(image.size(1))`)

**Comment by dkurt** [comment]
@BloodAxe, This PR fixes your example: https://github.com/opencv/opencv/pull/13427, thank you!

Do you mind if we add your network in our tests? (see https://github.com/opencv/opencv_extra/pull/558)

**Comment by BloodAxe** [comment]
Thanks a lot for your fix! I will definitely try it. Sure, feel free to use it for tests.

**Comment by raviv** [comment]
Still getting this error (Blob xxx not found in const blobs in function 'getBlob') using latest release (4.0.1)
It's a Gather operation.

**Comment by zhenglilei** [comment]
> Still getting this error:
> Blob 178 not found in const blobs in function 'getBlob'
> 
> The relevant operation is:
> 
> ```
> %178 : Long() = onnx::Gather[axis=0](%177, %176), scope: SSD
> ```
> opencv-contrib-python==4.0.0.21
> opencv-python==4.0.0.21
> torch==1.0.0
> 
> Using an ONNX model exported from PyTorch (https://github.com/amdegroot/ssd.pytorch)

Upgrading opencv to 4.1.0 can solved this problem.
