### ISSUE TITLE
cv::Mat16w not supported by qt5 highgui

### ISSUE THREAD

**Issue by midjji** [opencv/opencv#13304]
##### System information (version)

- OpenCV => 4 pre
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC  7.3.0
 -DWITH_QT=ON -DWITH_OPENGL=ON 

##### Detailed description
following code 
int main(){
    cv::Mat1f img = cv::Mat1f::zeros(100,100);
    cv::imshow("img",img);
    cv::waitKey(0);
    return 0;
}
will crash with the following exception: 
opencv/modules/highgui/src/window_QT.cpp:2561: error: (-215:Assertion failed) dst.data == image2Draw_mat->data.ptr in function 'updateImage'

Note the image type cv::Mat1w will also crash. Actualy given the error almost everything except rgb8 and grey8 will crash.

**Comment by alalek** [comment]
> you'll have to convert your image manually to CV_8U, before using imshow()

This is more accurate way. Implicit conversions are tricky anyway.

**Comment by midjji** [comment]
The thing is, I did not want it to do the conversion, and it didnt always
do that automatically in the past.

There are two features which allow me to directly see the values of a more
than 8 bit image.
First i have a 9-10 bit screen, second, when I zoom in enough the pixel
grid shows the actual values.





Den tis 27 nov. 2018 kl 17:16 skrev Alexander Alekhin <
notifications@github.com>:
