### ISSUE TITLE
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /home/build-dep/opencv-3.4.0/modules/imgproc/src/imgwarp.cpp, line 662

### ISSUE THREAD

**Issue by monajalal** [opencv/opencv#13309]
Running OpenFace 2.0 Docker from this link on videos of people in front of a camera I don't get any error. All videos are captured with same camera and same setting, in some of the videos the person suddenly goes out of the video of the camera and we get the following error. 

```
OpenCV Error:
Assertion failed (ssize.area() > 0) in remapBilinear, file /home/build-dep/opencv-3.4.0/modules/imgproc/src/imgwarp.cpp, line 662

terminate
called after throwing an instance of 'cv::Exception'

 what():
 /home/build-dep/opencv-3.4.0/modules/imgproc/src/imgwarp.cpp:662: error: (-215) ssize.area() > 0 in function remapBilinear
```

I would like to know what this error represents and how I can fix it?

**Comment by alalek** [comment]
Try latest code from 3.4 branch.

> ssize.area() > 0

This means that source/input image is empty. Need to check the caller code.
