### ISSUE TITLE
h264 @ 0x8f915e0] error while decoding MB 53 20, bytestream -7

### ISSUE THREAD

**Issue by Akhtar303nu** [opencv/opencv#13302]
Hello

I have ip camera and want to read stream from it using opencv.

till now I am able to read frame and display it but suddenly video is stoped/freeze because of pocket loss

Error

h264 @ 0x8f915e0] error while decoding MB 53 20, bytestream -7

My configuration:

ubuntu 16.04
opencv 3.4.1
GPU GTX 1080

code 
video_capture = cv2.VideoCapture("rtsp://user:userhik1@192.168.23.114")

System information (version)
- OpenCV => 3.4.3
- Operating System => ubuntu 16.0.4
- Python version =>3.5
please any help 

Thanks

**Comment by alalek** [comment]
OpenCV doesn't decode H264 directly. It uses some 3rdparty backends. Perhaps FFmpeg is used in your case.
Please try ffmpeg / ffplay utilities on your stream without OpenCV first and check for similar messages.
Also provide information about used IP camera - some firmware versions can be buggy.

> pocket loss

We really can't help with fixing of networking issues. OpenCV doesn't work on this level.

**Comment by TranVanLy107** [comment]
hi Akhtar303nu,
i have the same issue.  Did you have already fixed it.? help me

**Comment by madhusudan-j** [comment]
hi guys, im newbiee to opencv im getting the same error while decoding, please drag me out of the error if u solved it

**Comment by madhusudan-j** [comment]
> > OpenCV doesn't decode H264 directly. It uses some 3rdparty backends. Perhaps FFmpeg is used in your case.
> > Please try ffmpeg / ffplay utilities on your stream without OpenCV first and check for similar messages.
> > Also provide information about used IP camera - some firmware versions can be buggy.
> > > pocket loss
> > 
> > 
> > We really can't help with fixing of networking issues. OpenCV doesn't work on this level.
> 
> Thanks fro reply @alalek
> camera HIK Vision IR Network camera
> model :DS-2CD2420F-IW
> I/P: 12V == 0.5A,5.5W

i have same camera configs and same error, please help me

**Comment by zoldaten** [comment]
https://stackoverflow.com/questions/49233433/opencv-read-errorh264-0x8f915e0-error-while-decoding-mb-53-20-bytestream
