### ISSUE TITLE
OpenCV Cmake error make -j4

### ISSUE THREAD

**Issue by buzdarbalooch** [opencv/opencv#13308]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by zteffi** [comment]
Hello,
what cuda version are you using? If you're unsure run
`$ nvcc --version`

**Comment by tolysz** [comment]
As mentioned your cuda compiler does not understand the cuda compute capabilities you are requesting. [Cuda on Wiki](https://en.wikipedia.org/wiki/CUDA)

> CUDA SDK 1.0 support for compute capability 1.0 – 1.1 (Tesla)[20]
> CUDA SDK 1.1 support for compute capability 1.0 – 1.1+x (Tesla)
> CUDA SDK 2.0 support for compute capability 1.0 – 1.1+x (Tesla)
> CUDA SDK 2.1 – 2.3.1 support for compute capability 1.0 – 1.3 (Tesla)[21][22][23][24]
> CUDA SDK 3.0 – 3.1 support for compute capability 1.0 – 2.0 (Tesla, Fermi)[25][26]
> CUDA SDK 3.2 support for compute capability 1.0 – 2.1 (Tesla, Fermi)[27]
> CUDA SDK 4.0 – 4.2 support for compute capability 1.0 – 2.1+x (Tesla, Fermi, more?)
> CUDA SDK 5.0 – 5.5 support for compute capability 1.0 – 2.1+x (Tesla, Fermi, more?)
> CUDA SDK 6.0 support for compute capability 1.0 – 3.5 (Tesla, Fermi, Kepler)
> CUDA SDK 6.5 support for compute capability 1.1 – 5.x (Tesla, Fermi, Kepler, Maxwell). Last version with support for compute capability 1.x (Tesla)
> CUDA SDK 7.0 – 7.5 support for compute capability 2.0 – 5.x (Fermi, Kepler, Maxwell)
> CUDA SDK 8.0 support for compute capability 2.0 – 6.x (Fermi, Kepler, Maxwell, Pascal). Last version with support for compute capability 2.x (Fermi)
> CUDA SDK 9.0 – 9.2 support for compute capability 3.0 – 7.2 (Kepler, Maxwell, Pascal, Volta)
> CUDA SDK 10.0 – 10.1 support for compute capability 3.0 – 7.5 (Kepler, Maxwell, Pascal, Volta, Turing) 

Thus your CUDA version is 7.5 at the most, but you need to use one higher!
