### ISSUE TITLE
VideoWriter with apiPreference CAP_INTEL_MFX  fourcc('H','2','6','4') don't compress video

### ISSUE THREAD

**Issue by yiyunluo07** [opencv/opencv#13306]
##### System information (version)

- OpenCV => 3.4.3-openvino
- Operating System / Platform => Linux Ubuntu 16.04

##### Detailed description
Hello, I'm using Intel Up-Board Squared to develop a programm which needs to compress video by using INTEL_MFX apiPreference to speed up the process.
I've compiled OpenCV with Intel Media SDK backend, and the compiler didn't give any errors to my code. 
 `int fourcc = cv::VideoWriter::fourcc('H','2','6','4');`
 `cv::VideoWriter writer("filename.mp4", cv::INTEL_MFX, fourcc, 30, cv::Size(1280,720), true);`
What interesting is,  when I run the code, it will show a line with `MFX: unsupported extension: /dev/video0`, but the video could be written in a new file.
The video file which was written is very large. A video about 30 seconds can be 70 MB large. I think that the video has been written without compressing with H264. 

I also installed Intel Quick Sync Video for ffmpeg.
```bash
up-board@upboard-UP-APL01:~$ ffmpeg -codecs | grep 'qsv'ffmpeg version n3.4-dev-2711-g587fada Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_vdpau h264_cuvid ) (encoders: h264_nvenc h264_qsv h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_cuvid ) (encoders: nvenc_hevc hevc_nvenc hevc_qsv hevc_vaapi )
 DEV.L. mpeg2video           MPEG-2 video (decoders: mpeg2video mpegvideo mpegvideo_vdpau mpeg2_v4l2m2m mpeg2_qsv mpeg2_cuvid ) (encoders: mpeg2video mpeg2_qsv mpeg2_vaapi )
 D.V.L. vc1                  SMPTE VC-1 (decoders: vc1 vc1_vdpau vc1_qsv vc1_v4l2m2m vc1_cuvid )
 DEV.L. vp8                  On2 VP8 (decoders: vp8 vp8_v4l2m2m vp8_cuvid vp8_qsv ) (encoders: vp8_v4l2m2m vp8_vaapi )
```
I think that it's correctly installed.
Is there anyone who has experience with Media SDK backend for OpenCV? Hope someone can help me.

Greetings,
Yiyun

Xref: https://github.com/Intel-Media-SDK/MediaSDK/issues/944

**Comment by TimoK93** [comment]
Hi,
H.264 can be parametrized. In GStreamer i know how to do it. Maybe it is possible with Intel API?
Greetings

**Comment by mshabunin** [comment]
Please, verify that MediaSDK support has been actually enabled in your build, check cmake output. Also check output of `vainfo` command.

`MFX: unsupported extension` is a warning from `cv::VideoCapture` as there is no support for decoding camera stream in the MFX backend.

It is hard to say more without reproducer code.

**Comment by yiyunluo07** [comment]
Hi, I have enabled MediaSDK in my build, and cmake output shows also with Yes for Intel Media SDK.
My `vainfo` command shows:
```bash
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0.pre1)
vainfo: Driver version: Intel iHD driver - 1.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
```

**Comment by yiyunluo07** [comment]
Hello, I have solved the problem by changing a file of opencv for mfx_writer: `/modules/videoio/src/cap_mfx_writer.cpp`

After I changed the code `params.mfx.TargetKbps = (mfxU16)cvRound(frameSize.area() * fps / 500);` to  `params.mfx.TargetKbps = (mfxU16)cvRound(**4000000**);`, the video file which was written by the VideoWriter has now only **15 MB** large for 1 min instead of **300 MB** large for 1 min. (The resolution is Full HD.)

I also tested with other bit rates and I post the results here: (with Full HD)
With 10000      for  1 min  70MB
With 1000000  for  1 min  118MB
With 4000000  for  1 min  15,2MB
With 8000000  for  1 min  36MB
