### ISSUE TITLE
Error during make  error: ‘samples’ has not been declared

### ISSUE THREAD

**Issue by nikhiljaiswal** [opencv/opencv#13314]
I want to run real_time_pose_estimation code in calib3d folder.
For that, I have to first build it.
I am going in opencv-master/samples directory.
then, mkdir build, cd build, cmake .., make
while running make, I am getting error as samples has not been declared.
See the screenshot for reference. Kindly help.

![error](https://user-images.githubusercontent.com/21051117/49131986-5d8ef680-f300-11e8-8044-ab49ea97727f.png)

**Comment by alalek** [comment]
Build / Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

You should use compatible version of samples and OpenCV itself.
