### ISSUE TITLE
Internal error using DNN module with multiple Nets

### ISSUE THREAD

**Issue by sathibault** [opencv/opencv#13312]
##### System information (version)
- OpenCV => 3.3.4
- Operating System / Platform => Ubuntu 16
- Compiler => gnu

##### Detailed description

When alternating between two different deep nets, the DNN module throws this internal error:
```
OpenCV(3.4.4) /opt/vision/opencv/modules/dnn/src/dnn.cpp:672: error: (-215:Assertion failed) mapIt != reuseMap.end() in function 'numReferences'
```

##### Steps to reproduce

Create two Net objects and load from files.  Alternately, call forward on the two modules.

**Comment by dkurt** [comment]
@sathibault, Please add minimal working example. Or we can try to reproduce it with any pair of networks?

**Comment by sathibault** [comment]
If you don't have any initial thoughts, I'll see if I can work up a small example to repro.

**Comment by sathibault** [comment]
This is not what I initially thought.  It looks more like it has to do with the input blob being under some minimum size.  I'll try to narrow it down further.

**Comment by sathibault** [comment]
Here's what's happening.  In `allocateBlobsForLayer`, the `if (total(shapes[index])) ...` causes empty blobs to get ignored and thus have no entry in `reuseMap`.

**Comment by dkurt** [comment]
@sathibault, please clarify this problem. Provide a minimal working example. If you're not able to share private networks - try to create a reproducer with public ones.

**Comment by sathibault** [comment]
Sorry I was unable to reproduce with a small example; feel free to close.

**Comment by lsy17096535** [comment]
@sathibault  Hi, We met same problem. We run face recognition cnn with dnn, more than one user access our web app,  it will show :
error: (-215:Assertion failed) mapIt != reuseMap.end() in function 'numReferences'

System information 
OpenCV => 3.4.6
Operating System  => Cent OS 7.0
Compiler => CPU

**Comment by dkurt** [comment]
@lsy17096535, Please provide code reproducer.

**Comment by lsy17096535** [comment]
blob = dnn.blobFromImage(cv2.imread(fn), 1, (224, 224), (104, 117, 123))
    print("Input:", blob.shape, blob.dtype)
    net = dnn.readNetFromCaffe(cm_path+'face.prototxt', cm_path+'face.caffemodel')
    net.setInput(blob)
    prob = net.forward()
    print("Output:", prob.shape, prob.dtype)

more than one thread access this web app, it will crash.

the same code has no problem on my mac os. but appear on two of my centos server.

**Comment by alalek** [comment]
Almost all objects in OpenCV are not thread-safe in general (except storage containers).
Each thread should have own object instance.

**Comment by lsy17096535** [comment]
@alalek  but this problem not occur on MAC OS. very confused.

**Comment by dkurt** [comment]
@lsy17096535, Perhaps you need to call `readNet` for an every queue and use local net but not share it between requests.
