### ISSUE TITLE
QRCodeDetector: detect multiple codes

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#13311]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

current implementation refuses to find _any_ QR code when presented with an image that contains more than one.

it would be nice if it could do that.

##### Steps to reproduce
```.py
import cv2 as cv
import numpy as np
im = cv.imread("qrcode.png")
det = cv.QRCodeDetector()
rv, pts = det.detect(im)
print("single:", rv) # True
rv, pts = det.detect(np.hstack([im, im])) # duplicate side by side
print("multiple:", rv) # False
```

**Comment by pietz** [comment]
It not only "refuses" but actually crashes the application. This seems very half baked.

**Comment by allnes** [comment]
@crackwitz, already preparing to change the algorithm in this request [https://github.com/opencv/opencv/pull/15338](https://github.com/opencv/opencv/pull/15338)
Thank you for writing!

**Comment by alalek** [comment]
@crackwitz It would be nice to attach input image to have complete reproducer (without reproducer there is no strong validation criteria of this issue).

**Comment by crackwitz** [comment]
this is suitable to reproduce: https://commons.wikimedia.org/wiki/File:MM_QRcode.png
![qrcode](https://user-images.githubusercontent.com/7065108/68480623-8d938900-0235-11ea-914c-166f171ca2a5.png)

**Comment by dkurt** [comment]
I think that we can lose it as resolved.

**Comment by rayonnant14** [comment]
@crackwitz Hi, use the latest OpenCV version that contains new functionality for multiple QR-code detection.
For example:
`import cv2 as cv
import numpy as np
im = cv.imread("qrcode.png")
det = cv.QRCodeDetector()
rv, pts = det.detectMulti(np.hstack([im, im])) 
print("multiple:", rv) # True`

**Comment by rayonnant14** [comment]
@crackwitz Hi, use the latest OpenCV version that contains new functionality for multiple QR-code detection.
For example:

```python code

import cv2 as cv 
import numpy as np
im = cv.imread("qrcode.png")
det = cv.QRCodeDetector()
rv, pts = det.detectMulti(np.hstack([im, im])) 
print("multiple:", rv) # True
```

**Comment by crackwitz** [comment]
quick question: what's the behavior for detect (non-multi) and multiple markers in view? will it pick anything, or nothing?

**Comment by OmriTreidel** [comment]
@rayonnant14 which version of openCV are you using? I've tried both latest versions opencv-python-4.2.0.34 and opencv-python-3.4.9.33 but I wasn't able to find `detectMulti` method.

**Comment by crackwitz** [comment]
`detectMulti` code is from ~01/26/2020. both your stated versions are from december 2019.

**Comment by rayonnant14** [comment]
@OmriTreidel did you use pip to install opencv-python?

**Comment by OmriTreidel** [comment]
@rayonnant14. yes

**Comment by rayonnant14** [comment]
@OmriTreidel so, download the latest version from  OpenCV repository and build it with python parameters. 
More information about building OpenCV from source: https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

**Comment by llxxhm** [comment]
There is no problem with ZBar
