### ISSUE TITLE
Build for iOS failure

### ISSUE THREAD

**Issue by qmint** [opencv/opencv#13324]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => macOS Mojave 10.14.1
- Compiler => Xcode 10.1

##### Detailed description

I'm tried to build it for iOS, but failed. Here is the error log:

> error: Build input file cannot be found: '/Users/vincent/Desktop/opencv/ios/build/build-arm64-iphoneos/modules/world/opencl_kernels_video.cpp'
>
> ** BUILD FAILED **
>
>
> The following build commands failed:
	CompileC /Users/vincent/Desktop/opencv/ios/build/build-arm64-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/arm64/opencl_kernels_video.o /Users/vincent/Desktop/opencv/ios/build/build-arm64-iphoneos/modules/world/opencl_kernels_video.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '8', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "platforms/ios/build_framework.py", line 116, in build
    self._build(outdir)
  File "platforms/ios/build_framework.py", line 108, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "platforms/ios/build_framework.py", line 202, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "platforms/ios/build_framework.py", line 39, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '8', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65

##### Steps to reproduce

> git clone https://github.com/opencv/opencv.git

> git checkout tags/4.0.0 4.0.0

> sudo ln -s /Applications/Xcode.app/Contents/Developer Developer

> python opencv/platforms/ios/build_framework.py ios

**Comment by 0xa6a** [comment]
When I run `cmake --version` the result is`3.11.0`.  

When I run `/Applications/CMake.app/Contents/bin/cmake-gui --version` or `/Applications/CMake.app/Contents/bin/cmake --version` the result is `3.12.4`.

**Comment by alalek** [comment]
@Dschee Please try this patch: #13352

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/waterfall?tag=ios_pack) after migration on MacOSX Mojave + Xcode 10.1

**Comment by WO-ZT** [comment]
这个报错最后怎么解决的
