### ISSUE TITLE
cv2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN2cv3dnn14dnn4_v201809175LayerE

### ISSUE THREAD

**Issue by MaeThird** [opencv/opencv#13325]
##### System information (version)
- OpenCV => 4.0.0-dev
- Operating System / Platform => Linux  4.15.0-42-generic 45-Ubuntu SMP
- Compiler => gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
##### Detailed description
can not import cv2 with python3.6
##### Steps to reproduce
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.6/dist-packages/cv2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN2cv3dnn14dnn4_v201809175LayerE

####
Can help ?

**Comment by alalek** [comment]
https://github.com/opencv/opencv/issues/13226#issuecomment-440972107

Solution is here: #13202

**Comment by santo4ul** [comment]
@MaeThird did the solution at  #132012  help ?

I'm facing exact same error.

**Comment by jaafar95** [comment]
@santo4ul Did you solve this problem yet? The solution above is not clear for me.

**Comment by santo4ul** [comment]
Hi @jaafar95 , yes, I solved the issue. Details below, hope this helps.

I followed the instructions from [here](https://www.pyimagesearch.com/2018/08/15/how-to-install-opencv-4-on-ubuntu/) 

My cmake (of OpenCV 4.0.1) was showing up both the versions of python (python 2 and python 3). 

Despite specifying python3 using " PYTHON_EXECUTABLE=~/.virtualenvs/py3cv4/bin/python", for some reason the cv2.so was getting installed at /usr/local/python/cv2/python-2.7/cv2.so. This was the problem.

Then I disabled python2 using BUILD_opencv_python2=Off and symlinked /usr/local/lib/python3.5/site-packages/cv2/python-3.5/cv2.cpython-35m-x86_64-linux-gnu.so to my virtualenv ()

Given below is my cmake that helped fixing the issue. 

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.0.1/modules \
	-D BUILD_TIFF=ON  \
	-D PYTHON_EXECUTABLE=~/.virtualenvs/py3cv4/bin/python \
	-D BUILD_opencv_python2=Off \
	-D BUILD_opencv_dnn=ON ..

**Comment by kanik9** [comment]
> Hi @jaafar95 , yes, I solved the issue. Details below, hope this helps.
> 
> I followed the instructions from [here](https://www.pyimagesearch.com/2018/08/15/how-to-install-opencv-4-on-ubuntu/)
> 
> My cmake (of OpenCV 4.0.1) was showing up both the versions of python (python 2 and python 3).
> 
> Despite specifying python3 using `"-DPYTHON_EXECUTABLE=~/.virtualenvs/py3cv4/bin/python"`, for some reason the cv2.so was getting installed at /usr/local/python/cv2/python-2.7/cv2.so. This was the problem.
> 
> Then I disabled python2 using `-DBUILD_opencv_python2=Off` and symlinked `/usr/local/lib/python3.5/site-packages/cv2/python-3.5/cv2.cpython-35m-x86_64-linux-gnu.so` to my virtualenv.
> 
> Given below is my cmake that helped fixing the issue.
> 
> ```
> cmake -D CMAKE_BUILD_TYPE=RELEASE \
> 	-D CMAKE_INSTALL_PREFIX=/usr/local \
> 	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.0.1/modules \
> 	-D BUILD_TIFF=ON  \
> 	-D PYTHON_EXECUTABLE=~/.virtualenvs/py3cv4/bin/python \
> 	-D BUILD_opencv_python2=Off \
> 	-D BUILD_opencv_dnn=ON ..
> ```

I face this after following all the steps in a sequence


CMake Error: The source directory "/home" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
