### ISSUE TITLE
QrCodeDetector: out of  bounds error 

### ISSUE THREAD

**Issue by berak** [opencv/opencv#13326]
- OpenCV => 4.0-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64

using the attached image, `k` exceeds the ` listFrequencyElem` vector size (and segfaults) here:

https://github.com/opencv/opencv/blob/4fb9bce79f50495b69a025b0923e1ce124580148/modules/objdetect/src/qrcode.cpp#L972

code to reproduce:
```
	Mat m = imread("qr_ages.png", 0);
	QRCodeDetector qr;
	vector<Point> pts;
	bool ok = qr.detect(m,pts);
	std::string msg = qr.decode(m,pts);
```
![qr_ages](https://user-images.githubusercontent.com/854416/49210258-eb301c00-f3bc-11e8-895d-0f7a0ca8d251.png)

**Comment by allnes** [comment]
@berak Good day! I made some corrections, you can see them in pull request.

**Comment by berak** [comment]
@allness, thanks for the quick fix ! original problem solved.

it still does not return any text (quirc_decode() returns  QUIRC_ERROR_FORMAT_ECC) 
but that might be "expected" (it's really a bad, blurry img)

**Comment by allnes** [comment]
Yes, it's expected, because I have observed that 3rd-party library quirc is sensitive to distortion and blurring.

**Comment by berak** [comment]
yes, [quirc problem](https://github.com/dlbeer/quirc/issues/49) not "ours" ;)

cool thing, though !
