### ISSUE TITLE
i have tried it but this doesn't work too.

### ISSUE THREAD

**Issue by gautam10sep** [opencv/opencv#13321]
still giving the same error

recoginizer = cv2.createLBPHFaceRecognizer()
AttributeError: 'module' object has no attribute 'createLBPHFaceRecognizer'

recoginizer = cv2.face.createLBPHFaceRecognizer()
AttributeError: 'module' object has no attribute 'createLBPHFaceRecognizer'

_Originally posted by @sidd5sci in https://github.com/opencv/opencv/issues/10516#issuecomment-369395019_

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
