### ISSUE TITLE
open4.0 imshow issue.

### ISSUE THREAD

**Issue by folgerwang** [opencv/opencv#13339]
I  have imshow issue when I call imshow within a thread from fiber, which the imshow doesn't update.

I wrote a small ray tracer program that use fiber as multi-thread lib, for each thread I update a block of screen and call imshow to update the final image(with lock), it worked fine with opencv 3.41, but show nothing with 4.00.

**Comment by alalek** [comment]
Use UI functions from the Main thread only.
Not all UI backends support rendering from other threads.

**Comment by folgerwang** [comment]
but it does work well in opencv 3.41 by accident :-) well, kind of miss this feature.
