### ISSUE TITLE
Opencv 3.4.4 dependency on V4L2_CID_ISO_SENSITIVITY only available in kernel >= 3.5

### ISSUE THREAD

**Issue by washley** [opencv/opencv#13335]
Pull request https://github.com/opencv/opencv/pull/12893 added support for newer V4L camera properties, but these are only available on newer kernel versions (see https://www.kernel.org/doc/html/v4.14/media/uapi/v4l/hist-v4l2.html for, as an example, V4L2_CID_ISO_SENSITIVITY being introduced in 3.5).

I am not familiar with how Opencv typically handles this kind of scenario. Should these kinds of changes be behind preprocessor checks?

**Comment by alalek** [comment]
Build issues should be workarounded via preprocessor checks or extra defines for missing constants.
Feel free to prepare patch for this onto 3.4 branch.
