### ISSUE TITLE
Unable to find “..\..\lib\Debug\opencv_core344d.lib” in new 3.4.4 build

### ISSUE THREAD

**Issue by evansf** [opencv/opencv#13340]
This issue is also listed for the build of 4.0.0.  My solution worked...
1) in project opencv_cudev > properties > linker > input > additional Dependancies,  insert “..\..\lib\Debug\opencv_core344d.lib”
2) in project opencv_cudev > properties > linker > input > additional Dependancies,  insert “..\..\lib\Release\opencv_core344.lib”
Circular dependancies may require two make passes but it does make eventually with no errors.
My environment is Win10, VC2015, CMake3.13.1

**Comment by Ctrl96** [comment]
I meet this problem,too.And I can't solve it.
