### ISSUE TITLE
Could not generate .wasm file when building opencv.js

### ISSUE THREAD

**Issue by arszero** [opencv/opencv#13356]
##### System information (version)

- OpenCV => 4.0.0 / 3.4.4
- Operating System / Platform => Ubuntu 16.04
- Compiler => Emscripten 1.38.20

##### Detailed description
I was trying to build the opencv.js with the wasm output. I just followed the steps on the opencv.js tutorial and the build was completed with no error (some warnings), but I could not find the .wasm output in the bin folder, there were only two files opencv.js and opencv_js.js. I want to use the feature2d module so I tried the latest versions 4.0.0 and 3.4.4, both of them did not output the wasm file. Below is the output in the terminal console for your reference:
[log.txt](https://github.com/opencv/opencv/files/2642471/log.txt)

Then I also tried 3.4.3 version, and this time I was able to get the opencv_js.wasm file together with opencv.js and opencv_js.js. But it seems that 3.4.3 version does not include features2d in the js binding.

##### Steps to reproduce
cd opencv
python ./platforms/js/build_js.py build_wasm --build_wasm

**Comment by skmbr** [comment]
I found this post as I had the same problem, but it looks like the wasm binary is now within the .js file!

`var wasmBinaryFile="data:application/octet-stream;base64,AGFzbQEAAAABiB/6AmAEf39/fwBgAn99AGAFf39/f38AYAN/f38AYAJ/fwBgA39/fwF/YAp/f39/fH9/fHx/AGAEf39/fABg ... etc`

**Comment by dkurt** [comment]
Closing it. See https://github.com/opencv/opencv/issues/12417 for ways to load opencv.js.

**Comment by TedaLIEz** [comment]
What if I want the `wasmBinaryFile` to be a separate wasm binary file? Does build tool provide such option now?

**Comment by LanceXJH** [comment]
> What if I want the `wasmBinaryFile` to be a separate wasm binary file? Does build tool provide such option now

Did you find out how to get the seperate wasm file? I need it too.

**Comment by TedaLIEz** [comment]
@LanceXJH No. I think there would be some parameters for me in build config, but I haven't found yet.

**Comment by corbin-c** [comment]
@LanceXJH I couldn't figure out the correct build options, but I found a workaround. Here's how to extract the WASM binary :

1. open the `opencv.js` file

2. locate the `var wasmBinaryFile="data:application/octet-stream;base64,` part

3. select the following base64 string, it ends before the next `";` (which you mustn't select)

4. copy-paste to a new file, eg. `opencv_wasm`

5. convert to binary with this command line : `base64 -d opencv_wasm > opencv.wasm`

6. delete the base64 string from the `wasmBinaryFile` variable declaration, replace with the path to `opencv.wasm`

**Comment by cancerberoSgx** [comment]
Another way is to remove  `SINGLE_FILE` flag from modules/js/CMakeLists.txt (about line 95):

```
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s MODULARIZE=1")
```

That will generate two files as usual, .js and .wasm

**Comment by mimers** [comment]
> Another way is to remove `SINGLE_FILE` flag from modules/js/CMakeLists.txt (about line 95):
> 
> ```
> set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s MODULARIZE=1")
> ```
> 
> That will generate two files as usual, .js and .wasm

after set SINGLE_FILE=0, i found that the separated binary .wasm file was 10 times larger than opencv_js.js, is that right?

**Comment by sgang007** [comment]
A much simpler solution is to just pass the flag `--disable_single_file` when building.
This works when building with build_js.py
