### ISSUE TITLE
OpenCV 3.4.4 - Raspberry Pi NEON not detected

### ISSUE THREAD

**Issue by spaf94** [opencv/opencv#13374]
I'm compiling OpenCV 3.4.4 in Raspberry Pi with NEON enabled, but is compiled without NEON.
With version 3.4.2 works.

My compilation script:
make -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D BUILD_WITH_DEBUG_INFO=OFF \
-D BUILD_DOCS=OFF \
-D BUILD_EXAMPLES=OFF \
-D BUILD_TESTS=OFF \
-D BUILD_opencv_ts=OFF \
-D BUILD_PERF_TESTS=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D ENABLE_NEON=ON \
-D WITH_LIBV4L=ON \
../opencv-3.4

make -j4
sudo make install
sudo ldconfig

**I detected this problem changing the hog.cpp file of objdetect module. Inside a "#elif CV_NEON" I put cout "NEON" and in the "#else" I put a cout "NORMAL". 
When the code runs only is printed in the console the "NORMAL" string.**

**Comment by alalek** [comment]
Try this patch: #13316 or use `-DCPU_BASELINE=NEON`

**Comment by spaf94** [comment]
I add "-D CPU_BASELINE=NEON" and it's working now.
Thank you.
