### ISSUE TITLE
Failing to compile after updating from python 3.6.5 to python 3.6.7

### ISSUE THREAD

**Issue by olicht** [opencv/opencv#13378]
##### System information (version)

- OpenCV => 4.0.0 (git) + extras 4.0.0 (git)
- Operating System / Platform => Ubuntu 18.04.1 LTS / gnu-linux. 64-bit (Intel® Core™ I7-8550U, 8GiB RAM)
- Compiler => gcc 8.2.0

##### Detailed description

After updating from python 3.6.5 to 3.6.7, Cmake is insisting that the libpython3.[...].so is python3.6.5 instead of 3.6.7 and won't compile with py3 support.

I've checked using 
```bash
strings /usr/lib/x86_64-linux-gnu/libpython3.6m.so | grep "3\.6\."
```
and it says "3.6.7"

##### Steps to reproduce
Update from py 3.6.5 to 3.6.7 and try yourself.

**Comment by alalek** [comment]
You must run **clean** build (from scratch) after dependencies changes/updates/etc.

**Comment by olicht** [comment]
I did

**Comment by olicht** [comment]
I even `rm`ed the directories and cloned it again

**Comment by olicht** [comment]
@alalek Please reopen
