### ISSUE TITLE
Sobel() and Scharr() do not work correctly with UMat when delta != 0

### ISSUE THREAD

**Issue by Daniel-Alievsky** [opencv/opencv#13375]
Hello! I detected a little problem while using UMat version of Sobel and Scarr filters. It seems that they ignore "delta" argument.

I detected this in Java test, based on Javacpp, but it seems that it is a problem of OpenCV C++ code, not a bug of Javacpp bridge (see https://github.com/bytedeco/javacpp-presets/issues/645 )

The Java test is very simple:

```
public class UMatSobelBug {
    public static void main(String[] args) {
        opencv_core.setUseOpenCL(true);
        if (args.length < 3) {
            System.out.printf("Usage: %s source_image target_mat target_umat%n", UMatSobelBug.class);
            return;
        }
        final String sourceFile = args[0];
        final String targetMat = args[1];
        final String targetUMat = args[2];
        final opencv_core.Mat source = opencv_imgcodecs.imread(sourceFile);
        opencv_imgproc.GaussianBlur(source, source, new opencv_core.Size(55, 55), 0.0);

        opencv_core.Mat mat = new opencv_core.Mat();
        opencv_imgproc.Sobel(source, mat, opencv_core.CV_8U,
                1, 1, 3, 10.0, 128, opencv_core.BORDER_DEFAULT);
        opencv_imgcodecs.imwrite(targetMat, mat);

        opencv_core.UMat uMat = new opencv_core.UMat();
        opencv_imgproc.Sobel(source.getUMat(opencv_core.ACCESS_RW), uMat, opencv_core.CV_8U,
                1, 1, 3, 10.0, 128, opencv_core.BORDER_DEFAULT);
        opencv_imgcodecs.imwrite(targetUMat, uMat);
    }
}
```
Please run it (or equivalent C++ test) for any simple RGB image (I tried with some JPEG photo).
Mat version works correctly: the results are near delta=128 - gray picture.
UMat version just ignores delta, as if it delta=0 - almost black picture.

And the same problem will be with non-zero "delta" argument for Scharr function, for example, if I'll use the calls
```
        opencv_imgproc.Scharr(source, mat, opencv_core.CV_8U,
                1, 0, 1.0, 128, opencv_core.BORDER_DEFAULT);
...
        opencv_imgproc.Scharr(source.getUMat(opencv_core.ACCESS_RW), uMat, opencv_core.CV_8U,
                1, 0, 1.0, 128, opencv_core.BORDER_DEFAULT);

```

**Comment by vishwesh5** [comment]
It looks like for `cv::Sobel` and `cv::Scharr` functions, `delta` value has been hardcoded to `0` (but only for 2D case- [reference](https://github.com/opencv/opencv/blob/3.4/modules/imgproc/src/deriv.cpp#L443))

```CV_OCL_RUN(ocl::isOpenCLActivated() && _dst.isUMat() && _src.dims() <= 2 && (size_t)_src.rows() > kx.total() && (size_t)_src.cols() > kx.total(),ocl_sepFilter2D(_src, _dst, ddepth, kx, ky, Point(-1, -1), 0, borderType))```

Notice the argument just before `borderType` which is 0, is the argument for `delta` in `ocl_sepFilter2D` ([reference](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/filter.cpp#L4925)).

Is this the issue?

**Comment by alalek** [comment]
@vishwesh5 Right! Please create PR for 3.4 branch with replacing `0` -> `delta` in deriv.cpp
