### ISSUE TITLE
Define a custom layer in C++/OpenCV using the Caffe definition

### ISSUE THREAD

**Issue by didulle** [opencv/opencv#13371]
System information (version)

    OpenCV => 4.0
    Operating System / Platform => Windows 10 / 64 Bit
    Compiler => Visual Studio 2015

Detailed description
Hi,
I have found a reliable model (https://github.com/lyxok1/Tiny-DSOD) that runs perfectly using Caffe on Ubuntu (Training and inference).

However, when I try to run it using OpenCV, I get the following error: OpenCV(4.0.0) Error: Unspecified error (Can't create layer "Upsample1" of type "Upsample") in LayerData::getLayerInstance. This error happens since the Upsample layer is not defined in the layers of OpenCV 4.0.

There is a webpage on OpenCv Support to add a custom layer: https://docs.opencv.org/4.0.0/dc/db1/tutorial_dnn_custom_layers.html

However, it's not automatic to switch from a caffe implementation to an OpenCV/C++.
Since, the caffe implementation is available (see below). Is it possible to have the procedure that allows to create our own Upsample layer:
https://github.com/lyxok1/Tiny-DSOD/blob/master/src/caffe/layers/upsample_layer.cpp
https://github.com/lyxok1/Tiny-DSOD/blob/master/src/caffe/layers/upsample_layer.cu
https://github.com/lyxok1/Tiny-DSOD/blob/master/include/caffe/layers/upsample_layer.hpp

Thanks!!!

**Comment by dkurt** [comment]
>Is it possible to have the procedure that allows to create our own Upsample layer:

@didulle, Have you tried one described in mentioned tutorial?

### Example: custom layer from Caffe

**Comment by didulle** [comment]
Yes. But the upsample layer works differently without parameters but using the attribute propagate_down. So I didn't succeed in transforming the original code from caffe to a code that could be read by OpenCV. The example provided by OpenCV didn't show all the steps if you have something different than a specific operation that is applied

**Comment by dkurt** [comment]
@didulle, So the meaning of custom layers is to allow user to define undefined layers or override existing ones. If your layer differs somehow from Upsample described in the tutorial - you don't need to copy it but implement it by yourself.

This issue still is not clear for me. If you want to report a bug that OpenCV's custom layers mechanic doesn't allow you to define this layer - please provide a reproducer. If you're looking for help to implement it - this is not the right place. Please visit a forum this way: http://answers.opencv.org/.

**Comment by didulle** [comment]
Hi. It's not a bug. But just a missing information from OpenCV on how we can create a custom layer from its original implementation in Caffe or Tensorflow. It will be so useful since hundred of new layers of the latest dnn models are not supported by OpenCV

**Comment by dkurt** [comment]
@didulle, Excuse me but such kind of tutorial will look like "How to write in C++".

**Comment by alalek** [comment]
@didulle Feel free to prepare Pull request with tutorial which would clarify missing points of migration from Caffe/TF.
