### ISSUE TITLE
Reason for size limit on imread

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#13381]
opencv 4.0
windows 10 64 bits visual 2017

[My test program](http://answers.opencv.org/question/203793) : 
```
    RNG r;
    Mat m(60000, 40000, CV_8UC3);
    r.fill(m, RNG::UNIFORM, 0, 255);
    imwrite("test.png", m);
    Mat p = imread("test.png", IMREAD_UNCHANGED),d;
    cout << p.rows << " " << p.cols;
    absdiff(m, p, d);
    Scalar v = mean(d);
    cout << " mean=" << v << "\n";

```
and an exception is thrown (opencv 4.0.0 windows 10 visual 2017 win64) Now I changed in source code

#define CV_IO_MAX_IMAGE_PIXELS (1<<30) // 1 Gigapixel

in

#define CV_IO_MAX_IMAGE_PIXELS (1ull<<32ull) // 1 Gigapixel

and no exception is thrown (after opencv rebuild)

**Comment by alalek** [comment]
Problem is DDOS (memory) attacks. So defaults should stay the same.
