### ISSUE TITLE
Program crashes while running CascadeClassifier::detectMultiScale() as a c++ nodejs addon on separate thread

### ISSUE THREAD

**Issue by joao-carvalheira** [opencv/opencv#13391]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => macOS High Sierra
- Compiler => Clang (mac's default gcc)

##### Detailed description

I think I read somewhere clang wasn't supported, but I can't find it again so hopefully I was wrong. I compiled it from source from the 3.4 tag, there were no errors.  

I'm running opencv as a [nodejs addon](https://nodejs.org/api/addons.html#addons_n_api) in [c++](https://github.com/nodejs/node-addon-api), it is running on a separate thread and every once in a while (one or two loops), when it gets to the detectMultiScale function it crashes.  
When I run it without the node addon api library as a separate program (still in a separate thread) it doesn't crash, it just keeps the capture loop going as it is supposed to. But because it crashes on an opencv function I think it makes sense to put the issue here.

Piece of code where is crashes:  

```.cpp
// Gray has 1 channel, 2 dims, cols = 1280, rows = 720
// found_bodies is an empty std::vector<Rect>
body_cascade.detectMultiScale(gray, found_bodies, 1.01, 4, 0, cv::Size());
```
Error I get after a while: 

```.sh
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.4-dev) 
/usr/local/include/opencv2/core/mat.inl.hpp:1179: error: (-215:Assertion failed) (unsigned)(i1 * 
DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels()) in function 'at'
```

##### Steps to reproduce

I'm not sure how you can help me with this as I'm not allowed to share this code. :/  

It's basically this code [here](https://nodejs.org/api/addons.html#addons_n_api) (below), with a normal opencv capture loop from a video, running in a separate thread and doing detectMultiScale every loop.

Thank you in advance, anything you need, just ask.

**Comment by alalek** [comment]
> crashes
> terminating with uncaught exception

Bindings must wrap C++ exceptions into Node.JS exceptions.


> Assertion failed

Stacktrace from gdb is required with dumped cv::Mat values (put breakpoint via "b cv::error" and run).
Probably you need to recompile OpenCV with `-DCMAKE_CXX_FLAGS="-g"` (debug information).

**Comment by joao-carvalheira** [comment]
> > crashes
> > terminating with uncaught exception
> 
> Bindings must wrap C++ exceptions into Node.JS exceptions.

I'm still learning, but for now it's just a test. Thank you though, I will do that after I get this working.  

> 
> > Assertion failed
> 
> Stacktrace from gdb is required with dumped cv::Mat values (put breakpoint via "b cv::error" and run).
> Probably you need to recompile OpenCV with `-DCMAKE_CXX_FLAGS="-g"` (debug information).

Alright, I don't have much time today but I'll do that on monday if that's okay (please don't close this). Thank you.

**Comment by joao-carvalheira** [comment]
@alalek You can close this now, sorry, I couldn't get lldb to capture that breakpoint so I ended up doing the same thing in python and it works now. It was probably because sometimes the classifier didn't find anyone and my code was expecting to always find someone, I had a similar problem in Python. Thank you for your help though.
