### ISSUE TITLE
Have you carefully tested whether OpenCV 3.4.2 or higher can use the FFMPEG library (cross-compilation)?

### ISSUE THREAD

**Issue by polooloo** [opencv/opencv#13396]
##### System information (version)

- OpenCV => 3.4.2 or higher
- Operating System / Platform => Linux 64 
- Compiler =>  Unbatu 16.04  gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf   -> arm-linux-gnueabihf-g++

##### Detailed description
I found that in the same environment configuration, cross-compilation after installing ffmpeg-4.1, OpenCV 3.4.2 or later can not use FFMPEG library (but OpenCV 3.2.0 can)

In cmake3.5.1
OpenCV 3.2.0  can recognize FFMPEG:
   Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 56.60.100)
      avformat:                  YES (ver 56.40.101)
      avutil:                    YES (ver 54.31.100)
      swscale:                   YES (ver 3.1.101)
      avresample:                NO
However, OpenCV 3.4.2 does not recognize FFMPEG:

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    libv4l/libv4l2:              NO
    v4l/v4l2:                    linux/videodev2.h
    gPhoto2:                     NO

I carefully compared the code they identified in the FFMPEG module and found that OpenCV 3.4.2 is impossible to use FFMPEG：（OpenCVFindLibsVideo.cmake）

![image](https://user-images.githubusercontent.com/20057578/49685920-dd4e6980-fb27-11e8-9f00-e812333ad900.png)

Look at this variable carefully
${FFMPEG_INCLUDE_DIRS} 
in OpenCV 3.2.0 Can find configuration
![image](https://user-images.githubusercontent.com/20057578/49685963-59e14800-fb28-11e8-9653-e06a0ba8ebe9.png)
but in in OpenCV 3.4.2 Can not find configuration
![image](https://user-images.githubusercontent.com/20057578/49685980-8f863100-fb28-11e8-80b6-3984a5dd39da.png)

OpenCV 3.2.0 is very useful, but it is difficult to use on OpenCV 3.4.x version! I am constantly changing the FFMPEG version and running out of various configurations, but the OpenCV 3.4.x version does not correctly recognize FFMPEG. I don't know what caused this recognition process to be so complicated. Why is it so difficult to use OpenCV 3.4.x???

**Comment by polooloo** [comment]
![image](https://user-images.githubusercontent.com/20057578/49686039-93ff1980-fb29-11e8-9d08-8a236924d339.png)
OpenCV 3.2.0
![image](https://user-images.githubusercontent.com/20057578/49686047-ad07ca80-fb29-11e8-8e3e-31f58ec71bff.png)
OpenCV 3.4.x or higher
![image](https://user-images.githubusercontent.com/20057578/49686052-cf014d00-fb29-11e8-8335-b7bb495b9021.png)
in opencv-3.4.2/cmake/OpenCVFindLibsVideo.cmake
![image](https://user-images.githubusercontent.com/20057578/49686073-34edd480-fb2a-11e8-8af2-9d21da1698a4.png)

**Comment by polooloo** [comment]
This problem has been disgusting for a long time! ! ! I don't know what caused this recognition process to be so complicated? Why is it so difficult to use OpenCV 3.4.x??? Not friendly to programmers! ! ! ! !

**Comment by alexcanepa** [comment]
for what it's worth, I got the same problem as you trying with all of 3.4.5, 3.4.2, 3.3.1, _and_ 3.2.0.
`cmake` definitely can't detect `ffmpeg`.

Interestingly, the versions before 3.4.x recognize my setup as having  DC1394 2.x support, but the newer ones do not. This is on Ubuntu 18.04.2 and FFMPEG 3.4.4

If anyone has tips on setting this up properly, please let me know!
(I just want to encode some H/X264 videos...)

**Comment by alalek** [comment]
You need "-dev" packages and "pkg-config" tool for proper detection of some 3rdparty dependencies on Unix.

**Comment by alalek** [comment]
@polooloo

> cross-compilation

Refer to CMake scripts messages about `pkg-config`.

Define `PKG_CONFIG_LIBDIR` environment variable.
Or use `OPENCV_ENABLE_PKG_CONFIG` CMake variable to fallback to OpenCV 3.2 behavior (dangerous due detection of "host" packages).
