### ISSUE TITLE
solvePnP fails when useExtrinsicGuess is set true?

### ISSUE THREAD

**Issue by hunterlew** [opencv/opencv#13405]
I've tested solvePnP function setting useExtrinsicGuess true because I've already got a similar solution (R|t) and I just wanted to optimize that solution using LM. But it returned totally wrong answer! 
I've checked the source code in solvePnP.cpp and found that when useExtrinsicGuess is set truth, my provided R|t would not serve as input to LM solver.

**Comment by alalek** [comment]
#12334

**Comment by hunterlew** [comment]
@alalek why closed? I don't think it is the same problem as #12334
