### ISSUE TITLE
java调用opencv提取特征点报错

### ISSUE THREAD

**Issue by Night-Elves** [opencv/opencv#13408]
系统信息（版本）
OpenCV => 3.1.0
操作系统/平台=> win7 64位
编译器=> eclipse
详细说明
java代码如下：
> `public void tezhengdian(String img1, String img2){`
> `Mat src_base = Imgcodecs.imread(img1);`
> `Mat src_test = Imgcodecs.imread(img2);`
> `Mat gray_base = new Mat();`
> `Mat gray_test = new Mat();`
> `Imgproc.cvtColor(src_base, gray_base, Imgproc.COLOR_RGB2GRAY);`
> `Imgproc.cvtColor(src_test, gray_test, Imgproc.COLOR_RGB2GRAY);`
> `FeatureDetector featureDetector = FeatureDetector.create(FeatureDetector.ORB);`
> `DescriptorExtractor descriptorExtractor = DescriptorExtractor.create(DescriptorExtractor.ORB);`
> `MatOfKeyPoint keyPoint1 = new MatOfKeyPoint(), keyPoint2 = new MatOfKeyPoint();`
> `Mat descriptorMat1 = new Mat(), descriptorMat2 = new Mat();`
> `featureDetector.detect(gray_base, keyPoint1);`
> `featureDetector.detect(gray_test, keyPoint2);`
> `descriptorExtractor.compute(gray_base, keyPoint1, descriptorMat1);`
> `descriptorExtractor.compute(gray_test, keyPoint2, descriptorMat2);`
> `......`
> `数字运算`
> `......`
> `}`

### 报错代码定位：featureDetector.detect(gray_base, keyPoint1);
错误信息
**OpenCV Error: Assertion failed (clEnqueueWriteBuffer(q, (cl_mem)u->handle, CL_TRUE, dstrawofs, total, alignedPtr.getAlignedPtr(), 0, 0, 0) >= 0) in cv::ocl::OpenCLAllocator::upload, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\core\src\ocl.cpp, line 5114**
问题描述
**多次循环调用上面这个方法后出现以上错误信息，单次调用不会报错。**
重现步骤
**使用for循环多次调用tezhengdian(String img1, String img2)方法，循环第109次的时候出现错误信息。**

**Comment by alalek** [comment]
Mentioned OpenCV version is very old.
ORB OpenCL implementation should be disabled by default in modern OpenCV versions.
Disable OpenCL usage manually in OpenCV, if you don't need it.

There are several issues reported about ORB OpenCL implementation before.
So closing this as duplicate.
