### ISSUE TITLE
Not possible to specify Java version during Java build

### ISSUE THREAD

**Issue by ThadHouse** [opencv/opencv#13434]
With the current setup, it is not possible to set the Java build version from the Cmake build properties. This is something that would be very useful, especially with the quicker release cycle of Java.

The ANT build easily supports it with setting source and target properties in the javac block

An example of this can be found at
https://github.com/wpilibsuite/opencv/commit/5b6ade06e8af0ce7b91147024b4dd5c2d75a554a

Would this be something that would be accepted as a PR (Configurable in the build of course, with the default still being not specifying anything like currently happens).

**Comment by andreygursky** [comment]
It is possible to set path to the desired JDK:

https://docs.opencv.org/4.0.0/d9/d52/tutorial_java_dev_intro.html
> If CMake can't find Java in your system set the JAVA_HOME environment variable with the path to installed JDK before running it

E.g. for Debian GNU/Linux:
```
-DJAVA_HOME="/usr/lib/jvm/default-java"
```

**Comment by ThadHouse** [comment]
Not if you don't have an older jdk installer. Our CI systems and docker images only have 1 version on them.

**Comment by alalek** [comment]
@ThadHouse Please try this patch: #13435
