### ISSUE TITLE
Can't run dis_opt_flow.py

### ISSUE THREAD

**Issue by xdwgood** [opencv/opencv#13437]
Hello all,
Opencv version:4.0.0
ubuntu 16.04
python3.5
cv2.__version__  : '3.4.4'

I can run opt_flow.py
But when I try dis_opt_flow.py ,I got this:
![screenshot from 2018-12-14 14-47-38](https://user-images.githubusercontent.com/24932258/49987696-3e09f600-ffaf-11e8-8ec0-cca1644c0e3f.png)
 :smiley:

**Comment by alalek** [comment]
There is no DISOpticalFlow in 3.x. It is available in OpenCV 4.0.
Or you need to build OpenCV 3.x with opencv_contrib.

BTW, Avoid posting text as screenshots - this is bad practice. Use Ctrl+Shift+C to copy text from terminal.

**Comment by xdwgood** [comment]
@alalek  thank you :smiley: 
but I download zip is opencv-4.4.0. so what should I do?

> BTW, Avoid posting text as screenshots - this is bad practice. Use Ctrl+Shift+C to copy text from terminal.

got it , thanks :+1:

**Comment by alalek** [comment]
Perhaps you using old OpenCL Python module. Check "cv.__version__" value and module build date (`cv.__file__`).

Currently Python module installation path is changed, see #13202
