### ISSUE TITLE
iOS framework size is large

### ISSUE THREAD

**Issue by donie-inhance** [opencv/opencv#13439]
OpenCV 4 on iOS 10
Compiling OpenCV 4 framework for iOS from source using platforms/ios/build_framework.py

I've attempted to reduce the number of modules as I don't require all modules, I have also removed slices from the framework to just leave arm64. 

I'm not including any contrib modules.

But the framework is still nearly 60Mb. Is there any way to reduce this further for inclusion in an app. 
Thanks for any help.

**Comment by donie-inhance** [comment]
Just fyi...

I've summed the total of the object files generated from the build folder and they indeed add up to 50Mbyte approx (On Mac OS)

`
find . -name "*.o" -exec ls -l {} \; | awk '{ sum += $5; } END { print sum; }' "$@"
`

Just taking one example from this: 

`
340240 13 Dec 19:51 ./modules/calib3d/OpenCV.build/Release-iphoneos/opencv_calib3d.build/Objects-normal/arm64/ptsetreg.o
`

The source file at https://github.com/opencv/opencv/blob/master/modules/calib3d/src/ptsetreg.cpp is about 30K. Why is this so large as object file? 340Kbytes?

Just trying to understand and maybe this is outside the scope of the OpenCV project but if anyone has any ideas on how I can reduce this down, please let me know

**Comment by mshabunin** [comment]
Probably it is embedded bitcode: requested here #5319, implemented here #5654. Try option `--disable-bitcode` (introduced here #8009).

**Comment by donie-inhance** [comment]
thank @mshabunin I'm trying that now. Do you know if there is a way to flag to the build script not to build i386 and x86_64. I see it referenced in the python build script but I'm not sure how to turn it off. Would make it faster to build if I didn't have to build those two architectures as well.

**Comment by mshabunin** [comment]
`--iphonesimulator_archs`? Try to pass empty string.

**Comment by donie-inhance** [comment]
Ok, disabling bitcode brings the binary size of the framework down to 20Mbytes.
This is a signifiant improvement

**Comment by donie-inhance** [comment]
Ok, that command line arg does not work. What I did to avoid building for simulator was to edit the build_framework.py at line 299. Bit of a hack but fine for now.

`
        [
            (iphoneos_archs, "iPhoneOS"),
            # (["i386", "x86_64"], "iPhoneSimulator"),
            ([], "iPhoneSimulator"),
        ])
`

Thanks for the help @mshabunin
