### ISSUE TITLE
cascade crashes

### ISSUE THREAD

**Issue by mha-py** [opencv/opencv#13446]
Hi!

When using "cascade.detectMultiScale()" the python kernel dies. The code is:

```
import cv2
facedata = "path_to_file/haarcascade_frontalface_alt.xml"
cascade = cv2.CascadeClassifier(facedata)
img = cv2.imread("faces.jpg")
minisize = (img.shape[1],img.shape[0])
miniframe = cv2.resize(img, minisize)
faces = cascade.detectMultiScale(miniframe)
```

(The path to the xml is right, otherwise it gives a normal error).
I used winpython 3.6.6, (with winpython 3.4 same issue), opencv was on version 3.2 or so before update, after update and reinstall the errors stays the same. OS is Windows 7 64 bit

Has anyone an idea?

**Comment by handersendk** [comment]
Maybe it is related to which version of opencv you are using. I discovered that in some version of opencv the detectMultiScale method causes python to crash. 

Please see this post on stackoverflow for more information and possible solution. 
https://stackoverflow.com/questions/62211684/opencv-with-python-wont-exit-properly-when-using-detectmultiscale-on-cascadeclas/62214774?noredirect=1#comment110032606_62214774
