### ISSUE TITLE
ppc64le: nightly build failure on GCC<=6

### ISSUE THREAD

**Issue by seiko2plus** [opencv/opencv#13442]
##### System information (version)

- OpenCV => after #13334
- Operating System / Platform => ppc64le GNU/Linux
- Compiler => gcc4.9, gcc5, gcc6

##### Detailed description

````
In file included from /worker/buildbot/Power8_Linux_gcc-5__opencv/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:158:0,
                 from /worker/buildbot/Power8_Linux_gcc-5__opencv/opencv/modules/core/src/precomp.hpp:85,
                 from /worker/buildbot/Power8_Linux_gcc-5__opencv/build/modules/core/opencv_core_pch_dephelp.cxx:1:
/worker/buildbot/Power8_Linux_gcc-5__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'double cv::hal_baseline::v_reduce_sum(const cv::hal_baseline::v_float64x2&)':
/worker/buildbot/Power8_Linux_gcc-5__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:721:62: error: invalid parameter combination for AltiVec intrinsic
     return vec_extract(vec_add(a.val, vec_sld(a.val, a.val, 8)), 0);
                                                              ^
/worker/buildbot/Power8_Linux_gcc-5__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:721:67: error: invalid parameter combination for AltiVec intrinsic
     return vec_extract(vec_add(a.val, vec_sld(a.val, a.val, 8)), 0);
                                                                   ^
````
implementation of v_reduce_sum(const cv::hal_baseline::v_float64x2&), vec_sld doesn't support double precision

CI: https://ocv-power.imavr.com/#/builders/9/builds/574
 
##### Steps to reproduce

build OpenCV on ppc64le

**Comment by alalek** [comment]
It is strange, cross-compile builds are [green](http://pullrequest.opencv.org/buildbot/builders/3_4_powerpc-64le-lin64).

**Comment by seiko2plus** [comment]
@alalek, indeed I update it the issue, the bug only exist on gcc4.9, gcc5 and gcc6.
gcc7 and clang >= 4 looks fine but normally vec_sld shouldn't support 64bit operations.

**Comment by seiko2plus** [comment]
@alalek, current build for master branch on pp64le CI are broken due this issue? can I speed up the process and open a pull request for #13443 instead of waiting the next 3.4 merge?

**Comment by alalek** [comment]
I will create "Merge 3.4" PRs soon.

**Comment by seiko2plus** [comment]
@alalek, alright, thank you
