### ISSUE TITLE
Darknet/YoloV3, changing input resolution cause the "Inconsistent shape for ConcatLayer" error

### ISSUE THREAD

**Issue by yuril123** [opencv/opencv#13462]
OpenCV 4.0.0

I have a problem with running Darknet/YoloV3 network with different input resolutions on the same network. If I do not change input resolution I can process images with same resolution without problems.

1) WORKS OK 

cv::dnn::Net net = cv::dnn::readNetFromDarknet(....)

cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(416, 416));
net.setInput(blob);
net.forward(outs, this->net_output_names);

cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(416, 416));
net.setInput(blob);
net.forward(outs, this->net_output_names);

2) WORKS OK

cv::dnn::Net net = cv::dnn::readNetFromDarknet(....)

cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(448, 448));
net.setInput(blob);
net.forward(outs, this->net_output_names);

cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(448, 448));
net.setInput(blob);
net.forward(outs, this->net_output_names);

3) "Inconsistent shape for ConcatLayer" exception

cv::dnn::Net net = cv::dnn::readNetFromDarknet(....)

cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(416, 416)); 
net.setInput(blob);
net.forward(outs, this->net_output_names);

**cv::dnn::blobFromImage(image, blob, 1 / 255.F, cv::Size(448, 448)); // <=== resulution changed**
net.setInput(blob);
**net.forward(outs, this->net_output_names); // <=== "Inconsistent shape for ConcatLayer" exception**

**Comment by dkurt** [comment]
@yuril123, Does it should work with 448x448 input sizes? Have you tried to run Darknet with this resolution?

**Comment by yuril123** [comment]
Yes, it work good on both resolutions 416 and 448. Problem when changing resolution.

**Comment by alalek** [comment]
Create separate "Net" object for different input sizes.

**Comment by yuril123** [comment]
Btw, this works with YoloV2 model. I can change resolution many times without problem.  But no with YoloV3.
May be this related that YoloV3 have 2 outputs?

**Comment by alalek** [comment]
Dynamic changing of input size definitely will cause memory buffers reallocation, processing graph recompilation (for some backends) => very terrible performance.

This can't be fixed without unpredictable performance loss.

**Comment by yuril123** [comment]
May be is possible to somehow to reset Net without calling cv::dnn::readNetFromDarknet, to avoid loading net structure and weights?

**Comment by yuril123** [comment]
I did small fix in clear() function, and now I can change input resolution for network. The incorrect shape comes from previous layer instance. 

void clear()
{
        CV_TRACE_FUNCTION();

        MapIdToLayerData::iterator it;
        for (it = layers.begin(); it != layers.end(); it++)
        {
            if (it->second.id != 0) {
                it->second.inputBlobs.clear();
                it->second.outputBlobs.clear();
                it->second.internals.clear();
               it->second.layerInstance = NULL; // <=== Added
            }
            it->second.skip = false;

**Comment by Asfiya-Baig** [comment]
Hi, Can I take this up?

**Comment by dkurt** [comment]
Please try https://github.com/opencv/opencv/pull/16490

**Comment by JulienMaille** [comment]
@yuril123 has #16490 fixed your issue? Have you found a workaround?
