### ISSUE TITLE
Performance improvement. Loading video streams into AMD GPU. 2x faster!

### ISSUE THREAD

**Issue by jcdutton** [opencv/opencv#13469]
Currently opencv loaded images from a MPEG4 stream into a BGR Mat.
To get this onto the AMD GPU, one coverts this to a BGR UMat.
This then sends the image over the PCI bus to the AMD GPU.
This is slow because of the large quantity of data needing to be transferred.
MPEG4 is natively in YCrCb  in 4:2:0  for most data sources.
If we could send this 4:2:0 image to the GPU, it would halve the quantity of data being transferred across the PCI bus, thus improving the performance by 100% (2x quicker)
I have implemented this method for myself, but wondered if anyone else would be interested if I submitted it for review.
Previous BGR method: 150 FPS,  With 420 method, 300 FPS.
The API is quite simple:
UMat input;
UMat input_bgr;
VideoCapture d_reader("/mnt/tmp/test.mkv");
d_reader.set(CAP_PROP_FRAME_FORMAT, 2);  // New property. (2 for 4:2:0, 0 for default BGR) So, backwards compatible.
d_reader.read(input);   // 4:2:0 image now on the GPU.
cv::cvtColor(input, input_bgr, COLOR_YUV2BGR_I420);  // GPU converts it to BGR 

For BGR, the processing is as follows:
Media File -> 420 on CPU ->(CPU intensive)  BGR on CPU -> PCI bus (expensive) -> BGR on GPU
For 420, the processing is as follows:
Media File -> 420 on CPU -> PCI Bus (less expensive) -> 420 on GPU -> BGR on GPU (less expensive)

As a general comment, it would all be a lot easier if we could introduce a Planar format.
I.e. a Structure that hold 4 pointers to each of the planes, E.g. one for Blue, one for Green, one for Red, one for Alpha. We could then also attach a type to it, e.g. BGRA, or I420.
We could then transfer all the different formats from ffmpeg to GPU without any CPU memcopy.

**Comment by alalek** [comment]
You should take a look in direction of `CAP_PROP_CONVERT_RGB=0` to disable automatic conversion into BGR24.

Note: almost all properties are optional, and their implementations are backend-specific.
