### ISSUE TITLE
Trouble loading opencv in python 3.6 Library "libImath-2_2.12.dylib" not loaded

### ISSUE THREAD

**Issue by bjce** [opencv/opencv#13460]
First of all thank you very much for the development of opencv!

I have `opencv` installed on my mac which was working a few months ago

I tried to reload a `python script` where I used opencv. However, I get the following error message: 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/cv2.so, 2): Library not loaded: /usr/local/opt/ilmbase/lib/libImath-2_2.12.dylib
      Referenced from: /usr/local/Cellar/opencv/3.4.1_4/lib/libopencv_imgcodecs.3.4.dylib
      Reason: image not found

What should I do?

I have the following specificities. 
- OpenCV => 3.4.3.1
- Operating System / Platform => macOS 10.14
- Python 3.6.5

Thanks in advance for your help

**Comment by alalek** [comment]
> /anaconda3
> /Cellar

How did you build OpenCV Python?

Perhaps you have upgraded dependencies, but didn't rebuild OpenCV (rebuild from scratch, because CMake caches external deps).

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by bjce** [comment]
Thank you for your answer @alalek. As you suggested I posted a question on [Q/A forum](http://answers.opencv.org/question/205490/trouble-installing-opencv-on-a-mac-after-opencv-worked-fine-a-few-months-ago/) with more added details. For short: I followed the instruction for installation of [this website](https://www.codingforentrepreneurs.com/blog/install-opencv-3-for-python-on-mac/), which worked fine a few months ago but I still couldn't solve the problem
