### ISSUE TITLE
Opencv3.4.4  use yolov3 dnn model to detect objects

### ISSUE THREAD

**Issue by CuiWeiAI** [opencv/opencv#13476]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by CuiWeiAI** [comment]
When i use  the yolov3.weights training by darknet,it outputs confidence、classID、boxes,but the confidence is 0,boxes is just like 204560,320987....,it is too large,as for the classID,there are many classes when there are only person.
I have tried in several other pcs,however they both work well with the same weights.Is it because of my PC?I really have no idea.Really hope you can help me.

**Comment by dkurt** [comment]
@CuiWeiAI, Have you tried to use [object_detection.py](https://github.com/opencv/opencv/blob/3.4/samples/dnn/object_detection.py) or [object_detection.cpp](https://github.com/opencv/opencv/blob/3.4/samples/dnn/object_detection.cpp)?

```
python object_detection.py yolo --input example.jpg
```
![out](https://user-images.githubusercontent.com/25801568/50204408-c6084b00-0375-11e9-987d-c99da0d48cf6.png)

**Comment by CuiWeiAI** [comment]
@dkurt ,yes,I do,when i use the darknet demo,everything is ok.But when i try to use the dnn in Opencv,it just output something unuseness.By the way,i found my GTX1080ti is broken.Is it because of this reason?I do not know if the Opencv use GPU.

**Comment by dkurt** [comment]
@CuiWeiAI, OpenCV's deep learning module doesn't use GPU if you not specify it explicitly.

What means `unuseness`? Samples show just pictures with detected objects. If it's wrong - attach the following info to this issue:

* Origin image (`png` format  is more preferable)
* Command to process this image
* Resulting image

**Comment by CuiWeiAI** [comment]
@dkurt,yes,what i mean is that for object detection task,it outputs boxes,classes,scores.For boxes,it should be 640,320 for x,y and 240,480 for width and height.But it actually output 207703,0 for x,y and even -203700 and nothing for width and height

**Comment by CuiWeiAI** [comment]
@dkurt,i use the usb camera,it just can not detect anything right in the frame.But when i try other pcs with ubuntu.It is the same data and weights,they all three work well !!!

**Comment by dkurt** [comment]
@CuiWeiAI, Without reproducer we cannot help you solve the problem. If you use a camera - capture a frame and let us test it locally.

Show what means "correct" and what are "wrong" results. Save and attach the output from Draknet as a reference.

If you need help in OpenCV usage you'd rather ask a question at our forum http://answers.opencv.org. Please note that we use GitHub issues only for feature requests and reproducible bug reports.
