### ISSUE TITLE
cuda::createTemplateMatching not work with CUDA10.0 

### ISSUE THREAD

**Issue by dog-fox** [opencv/opencv#13477]
##### System information (version)

```
- OpenCV => 3.3.1,  3.4.4,  4.0.0
- Operating System / Platform => Jetson Xavier (Ubuntu 18.04, CUDA 10)
- Compiler => g++ 7.3.0
```

##### Detailed description

"cuda::createTemplateMatching" not work with CUDA10.0.
Although compiling the program works well, if you execute it, 
the process stops while the process is activated.

```
cv::Ptr<cv::cuda::TemplateMatching> alg;
alg = cv::cuda::createTemplateMatching(templ_h.type(), CV_TM_CCOEFF_NORMED);
alg->match(image_h, templ_h, result);
```

**Comment by mxjxbx** [comment]
I have a similar problem but with cuda::CLAHE.
Seems like stuff from cudaimgproc modules are affected.
the GPU functions from cudaarithm module work just fine.

I use a Windows 10 Machine, with CUDA 10 and VS 2017.

**Comment by nglee** [comment]
With CUDA 10.0 on a Pascal GPU(1080 Ti), the problem is not reproduced with this code.

```
#include <opencv2/opencv.hpp>
#include <cuda_runtime.h>

int main()
{
    cv::cuda::GpuMat image_h(1080, 1920, CV_8UC1);
    cv::cuda::GpuMat templ_h(64, 64, CV_8UC1);
    cv::cuda::GpuMat result(1080-64+1, 1920-64+1, CV_32FC1);

    cv::Ptr<cv::cuda::TemplateMatching> alg;
    alg = cv::cuda::createTemplateMatching(templ_h.type(), CV_TM_CCOEFF_NORMED);
    alg->match(image_h, templ_h, result);

    cudaDeviceSynchronize();
}
```

Since Jetson Xavier includes a Volta GPU, the problem might be reproducible only on Volta and later architecture. I will test with a Turing GPU as soon as possible.

**Comment by nglee** [comment]
Tested with a Turing GPU(2080 Ti) and CUDA 10.0 but the problem is still not reproducible. @dog-fox Could you provide a compilable code that reproduces the behavior?

**Comment by hmzawz2** [comment]
Hi! I have tried templateMatching in opencv3.4.5  on my computer, which is with cuda10.0 and 2080Ti. I found that the input images must be 32F, and of course the matching method must be changed. But it works! However, I am not quite clear why. Hope this can help you and others!
