### ISSUE TITLE
4.0.0 compilation failed on Beaglebone

### ISSUE THREAD

**Issue by ibrencsics** [opencv/opencv#13475]
Compiling 4.0.0 on Beaglebone resulted in the following failure: 

[ 87%] Built target example_tracking_tutorial_multitracker
Scanning dependencies of target gen_opencv_python_source
[ 87%] Generate files for Python bindings and documentation
Note: Class Feature2D has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::Algorithm, cv::class, cv::Feature2D, cv::Algorithm
      Only the first base class will be used
[ 87%] Built target gen_opencv_python_source
Scanning dependencies of target opencv_python3
[ 87%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
modules/python3/CMakeFiles/opencv_python3.dir/build.make:62: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o' failed
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 4
CMakeFiles/Makefile2:24789: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tomoaki0705** [comment]
That's an out of memorry error
This is NOT a bug of OpenCV
Please ask to http://answers.opencv.org/questions/

**Comment by abhiTronix** [comment]
@ibrencsics try with `make -j1` instead.
