### ISSUE TITLE
Fail to do network forward after loading a sub-pixel layer

### ISSUE THREAD

**Issue by JVision** [opencv/opencv#13494]
##### System information (version)
- OpenCV => 3.4.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I've implemented a simple subpixel layer using tensorlayers. However, could not get correct results using opencv dnn. 

The code is given as below:

```python
def test_subpixel():
    import cv2 as cv
    import numpy as np
    import tensorflow as tf

    graph = './_Cache/simple_subpixel.optimized.pb'
    
    inp = np.linspace(1,4, 4).reshape(1, 4, 1, 1)
    output_node_name = 'SUBPIXEL/SUBPIXEL/subpixel_image/Identity'

    # Run TensorFlow
    with tf.gfile.FastGFile(graph, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    with tf.Session() as sess:
        # Restore session
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')
        tfOut = sess.run(sess.graph.get_tensor_by_name(output_node_name+":0"),
                        feed_dict={'input_image:0': inp.transpose(0, 2, 3, 1)}) 
        tfOut_flat = tfOut.transpose(0, 3, 1, 2)[0, 0, :,:]
    # Run OpenCV
    net = cv.dnn.readNet(graph)
    net.setInput(inp)
    cvOut = net.forward(output_node_name)
    d1 = cvOut[0,0,:,:]
    d2 = tfOut_flat
    max_error = np.max(np.abs(d1 - d2))
    print(max_error)
```

An error pops up when running the above piece of code:

`OpenCV(3.4.4-dev) Error: Unspecified error (Can't create layer "SUBPIXEL/SUBPIXEL/subpixel_image/Shape" of type "Shape") in cv::dnn::experimental_dnn_34_v10::LayerData::getLayerInstance, file E:\opencv\modules\dnn\src\dnn.cpp, line 513
`

##### Steps to reproduce
to reproduce the issue, please download and unzip the attached file and put the .pb file into the same folder as the test code and run. 

[pbs.zip](https://github.com/opencv/opencv/files/2701592/pbs.zip)

1. load the pb files as attached. 
2. running the code snippets as given.

**Comment by JVision** [comment]
@dkurt Yes it is. here's the code snippet to generate the graph.

`import os
import tensorflow as tf
import tensorlayer as tl
import numpy

def tf_test_subpixel(reuse = False):
    in_channels = 4
    out_channels = 1
    scale = 2
    w = 1
    h = 1
    inputs = tf.placeholder(tf.float32, shape=[None, w, h, in_channels], name="input_image")
    
    with tf.variable_scope("SUBPIXEL", reuse=reuse) as vs:
        tl.layers.set_name_reuse(reuse)
        inputs_level = InputLayer(inputs, name='input_level')
        net_image = SubpixelConv2d(inputs_level,scale=2 ,n_out_channel=1,  name='subpixel_image')

    output = net_image

    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=False))
    tl.layers.initialize_global_variables(sess)

    
    test_input = numpy.random.randn(1, w, h, in_channels)
    sample_out = sess.run([output.outputs], {inputs:test_input})
`

**Comment by dkurt** [comment]
@JVision, Could you please also add a graph for `w > 1` and `h > 1`? It seems to me it'll look differently.

**Comment by JVision** [comment]
@dkurt, Please find the pb in the attached zip file.
[subpixel2x2.zip](https://github.com/opencv/opencv/files/2701787/subpixel2x2.zip)

**Comment by JVision** [comment]
@dkurt I've test this layer in tensorflow. it looks fine to me.

Here's the code showing how the subpixel layer is implemented.

```
    def _PS(X, r, n_out_channel):
        if n_out_channel >= 1:
            assert int(X.get_shape()[-1]) == (r ** 2) * n_out_channel, _err_log
            bsize, a, b, c = X.get_shape().as_list()
            bsize = tf.shape(X)[0] # Handling Dimension(None) type for undefined batch dim
            #la = tf.shape(X)[1]*r
            #lb = tf.shape(X)[2]*r
            Xs=tf.split(X,r,3) #b*h*w*r*r
            Xr=tf.concat(Xs,2) #b*h*(r*w)*r
            X=tf.reshape(Xr,(bsize,a*r, b*r,n_out_channel)) # b*(r*h)*(r*w)*c
        else:
            print(_err_log)
        return X

```

**Comment by dkurt** [comment]
@JVision, This PR enables the subpixel layer: https://github.com/opencv/opencv/pull/14454.

Please note that if there is no layers which have explicit data layout (NHWC), in example regular convolution - you need to pass an input data in NHWC data order. So for the second model:

```python
net = cv.dnn.readNet(graph)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
inp = np.random.standard_normal([1, 1, 1, 16]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print out.shape
```

But `[1, 16, 1, 1]` for real network (with convolutions, poolings etc.)
