### ISSUE TITLE
Error when building with CUDA. VS 2017, Win10.

### ISSUE THREAD

**Issue by mxjxbx** [opencv/opencv#13491]
##### System information (version)

- OpenCV => 4.0.0-dev
- Operating System / Platform => Windows 10
- Compiler => MS Visual Studio 2017 v 15.9.4
- CUDA v 10

##### Detailed description

Building openCV with contrib, CUDA, MKL, TBB, VTK, Qt, Eigen and Gstreamer. 
VS sln file gets created without a problem using cmake. 
Building the INSTALL project causes some projects to fail and going through the debug information, I found the errors you see below

```
1>c:\software\opencv\opencv\modules\core\include\opencv2\core\cuda\detail/color_detail.hpp(535): error : dynamic initialization is not supported for a __constant__ variable
1>
1>c:\software\opencv\opencv\modules\core\include\opencv2\core\cuda\detail/color_detail.hpp(584): error : dynamic initialization is not supported for a __constant__ variable
1>
1>c:\software\opencv\opencv\modules\core\include\opencv2\core\cuda\detail/color_detail.hpp(674): error : dynamic initialization is not supported for a __constant__ variable
1>
1>c:\software\opencv\opencv\modules\core\include\opencv2\core\cuda\detail/color_detail.hpp(751): error : dynamic initialization is not supported for a __constant__ variable
```

##### Steps to reproduce
CMake generates .sln file without a problem. Everything seemed fine. But building the INSTALL project causes some of the subprokects to fail mostly because of the error you see above.

**Comment by alalek** [comment]
Don't use screenshots with text. This make impossible searching of this issue by error message.

**Comment by mxjxbx** [comment]
@alalek , done. Removed it. THanks!

**Comment by chacha21** [comment]
same exact problem for me.
Removing the __constant__ is a workaround, but it is still strange : the code seems valid and legible to me : it is using constants, not run-time values, thus it should work.
I wonder if it could be a cuda compiler problem.

**Comment by alalek** [comment]
Please ensure that you using **compatible** MSVS and CUDA SDK. Refer to NVIDIA site for details.

**Comment by chacha21** [comment]
This is the latest MSVS (15.9.4) and latest CUDA 10 (there is only one release so far)

**Comment by mxjxbx** [comment]
@chacha21 , thanks for the tip!
I didn't want to chaneg anything in the source thikning it would break something else.
But I will just do as you said, hopefully it gets fixed in the next release.

**Comment by mxjxbx** [comment]
@alalek  CUDA itself works without a problem with the MSVS 15.9.4.
I feel its something to do with the MSVC compiler. This might probably work without a problem with GCC.

**Comment by zhouruikun** [comment]
I meet this problem too

**Comment by aidupl** [comment]
I'm facing the same issue with the same MSVS version 15.9.4 and CUDA 10.

**Comment by aidupl** [comment]
I'm facing the same issue with the same MSVS version 15.9.4 and CUDA 10.

**Comment by nickdademo** [comment]
I'm also experiencing this issue with MSVS 15.9.4, CUDA v10, OpenCV (and contrib) 4.0.1 on Windows 10.

**Comment by chacha21** [comment]
As mentioned by mxjxbx, replacing the const by constexpr is a workaround.
Since OpenCV 4.0.0 requires C++11, it may be a valid fix to deploy.

**Comment by nickdademo** [comment]
Shall a PR be created for this?

**Comment by nglee** [comment]
It is mentioned in the [CUDA C Programming Guide, F.3.13](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#const-variables) that a namespace scope variable with `const` qualifier cannot be directly used in device code if it is a `float` and when Microsoft compiler is used as the host compiler. This seems to be the reason for the build error messages when assigning `const` namespace scope variable to `__constant__ float` device variable.

Also, in the [CUDA C Programming Guide, F.3.16.5](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#constexpr-variables), it can be confirmed that the above restriction is not applied if the namespace scope variable is a `constexpr` qualified type.

Therefore, [the temporary fix by gromton](http://answers.opencv.org/question/205673/building-opencv-with-cuda-win10-vs-2017/) mentioned above seems to be a valid fix. This hazard exists when building the master branch on Windows, and it is not specific to some CUDA version or Visual Studio version.

@alalek May I open a PR that fixes this issue?

**Comment by alalek** [comment]
@nglee Sure!
