### ISSUE TITLE
MacOS build broken for Deployment Target < 10.12, including python build script. (OpenCV 4.0)

### ISSUE THREAD

**Issue by cpsauer** [opencv/opencv#13495]
When the deployment target (CMAKE_OSX_DEPLOYMENT_TARGET or MACOSX_DEPLOYMENT_TARGET) is set below 10.12, OpenCV's build fails with SIMD errors like the following:

```
[ 52%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o
In file included from ~/Downloads/opencv-4.0.0/modules/core/src/arithm.cpp:50:
In file included from ~/Downloads/opencv-4.0.0/modules/core/src/precomp.hpp:85:
In file included from ~/Downloads/opencv4.0.0/modules/core/include/opencv2/core/hal/intrin.hpp:149:
~/Downloads/opencv-4.0.0/modules/core/include/opencv2/core/hal/intrin_sse_em.hpp:151:12: error: 
      always_inline function '_mm_packus_epi32' requires target feature 'sse4.1', but would be
      inlined into function '_v128_packs_epu32' that is compiled without support for 'sse4.1'
    return _mm_packus_epi32(am, bm);
```

I've tested that you get the same erros using cmake -> makefiles for a deployment target of [10.11, 10.10, 10.9]. The error goes away for [10.12, 10.13, 10.14].

Trying to build with the python build script provided with OpenCV (opencv/platforms/osx/build_framework.py) fails with similar issues, since it sets MACOSX_DEPLOYMENT_TARGET=10.9.

**Comment by cpsauer** [comment]
Any idea what causes this issue or how to fix?

**Comment by RayPS** [comment]
Same. Subscribed.

**Comment by muellermartin** [comment]
I was able to overcome this issue by adding the options `-DENABLE_SSE41=ON -DENABLE_SSE42=ON -DENABLE_AVX=ON -DENABLE_AVX2=ON` to cmake. These options seem to be deprecated, but maybe someone smarter than me is able to adapt this to the newer options as mentioned in the wiki: https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options

**Comment by flemingm** [comment]
v4.4.0 still broken for Deployment Target < 10.12

**Comment by alalek** [comment]
Workaround with disabling optimizations is a bad idea anyway.

Try to push `-msse4.1` option through `CXXFLAGS` or `OPENCV_EXTRA_CXX_FLAGS`.
If this doesn't work (check full compiler command line options), then it is a bug in Xcode.

**Comment by hateom** [comment]
> Try to push `-msse4.1` option through `CXXFLAGS` or `OPENCV_EXTRA_CXX_FLAGS`.

This worked for me.
