### ISSUE TITLE
Opencv4.0 FileStorage can not build yml files

### ISSUE THREAD

**Issue by stonel1** [opencv/opencv#13508]
Opencv4.0 FileStorage can not build yml files
 Yourself example
#include "opencv2/opencv.hpp"
#include <time.h>
using namespace cv;
int main(int, char** argv)
{
	FileStorage fs("test.yml", FileStorage::WRITE);
	fs << "frameCount" << 5;
	time_t rawtime; time(&rawtime);
	fs << "calibrationDate" << asctime(localtime(&rawtime));
	Mat cameraMatrix = (Mat_<double>(3, 3) << 1000, 0, 320, 0, 1000, 240, 0, 0, 1);
	Mat distCoeffs = (Mat_<double>(5, 1) << 0.1, 0.01, -0.001, 0, 0);
	fs << "cameraMatrix" << cameraMatrix << "distCoeffs" << distCoeffs;
	fs << "features" << "[";
	for (int i = 0; i < 3; i++)
	{
		int x = rand() % 640;
		int y = rand() % 480;
		uchar lbp = rand() % 256;
		fs << "{:" << "x" << x << "y" << y << "lbp" << "[:";
		for (int j = 0; j < 8; j++)
			fs << ((lbp >> j) & 1);
		fs << "]" << "}";
	}
	fs << "]";
	fs.release();
	return 0;
}

and another BUG
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "public: __cdecl cv::FileNodeIterator::FileNodeIterator(struct CvFileStorage const *,struct CvFileNode const *,unsigned __int64)" (??0FileNodeIterator@cv@@QEAA@PEBUCvFileStorage@@PEBUCvFileNode@@_K@Z)
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "public: class cv::FileNodeIterator & __cdecl cv::FileNodeIterator::readRaw(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char *,unsigned __int64)" (?readRaw@FileNodeIterator@cv@@QEAAAEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAE_K@Z)

**Comment by sturkmen72** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

i think your need to change

    Mat cameraMatrix = (Mat_<int>(3, 3) << 1000, 0, 320, 0, 1000, 240, 0, 0, 1);
    Mat distCoeffs = (Mat_<float>(5, 1) << 0.1, 0.01, -0.001, 0, 0);

**Comment by stonel1** [comment]
Try again youself Plase!
This is your web page  https://docs.opencv.org/4.0.0/d4/da4/group__core__xml.html

#include "opencv2/opencv.hpp"
#include <time.h>
using namespace cv;
int main(int, char** argv)
{
	FileStorage fs("test.yml", FileStorage::WRITE);
	fs << "frameCount" << 5;
	time_t rawtime; time(&rawtime);
	fs << "calibrationDate" << asctime(localtime(&rawtime));
	Mat cameraMatrix = (Mat_<double>(3, 3) << 1000, 0, 320, 0, 1000, 240, 0, 0, 1);
	Mat distCoeffs = (Mat_<double>(5, 1) << 0.1, 0.01, -0.001, 0, 0);
	fs << "cameraMatrix" << cameraMatrix << "distCoeffs" << distCoeffs;
	fs << "features" << "[";
	for (int i = 0; i < 3; i++)
	{
		int x = rand() % 640;
		int y = rand() % 480;
		uchar lbp = rand() % 256;
		fs << "{:" << "x" << x << "y" << y << "lbp" << "[:";
		for (int j = 0; j < 8; j++)
			fs << ((lbp >> j) & 1);
		fs << "]" << "}";
	}
	fs << "]";
	fs.release();
	return 0;
}
The result : test.yml is 0 bytes

**Comment by sturkmen72** [comment]
maybe it is a fixed bug. i am using [latest source](https://github.com/opencv/opencv/blob/21bb17e3ee87293769992227ed534903e4577078/modules/core/include/opencv2/core/persistence.hpp#L127-L157) and everything works good.

**Comment by stonel1** [comment]
I test Version4.0 (Nov 20) is not good, but the beta version is good
