### ISSUE TITLE
All Samples is not run

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#13505]
##### System information (version)

- OpenCV => New
- Operating System / Platform =>WIN7X64
- Compiler => VS2015

##### Detailed description
Compiler static world library is OK.
Compiler samples is OK.
But all samples is not run, Messagebox tip :  CreateEventW API not in api-ms-win-core-synch-l1-2-0.dll.
I don't know why.

**Comment by alalek** [comment]
> WIN7

Try Win10.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
