### ISSUE TITLE
OpenCV Documentation Feature Request

### ISSUE THREAD

**Issue by leimao** [opencv/opencv#13515]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

##### Detailed description

This is actually a feature request instead of a bug report. I was told that I could request features here. Please see http://answers.opencv.org/question/205794/how-do-i-know-which-header-file-i-should-use-for-my-opencv-c-program/?comment=205834#post-id-205834

When I was trying to look for the header files for different OpenCV functions via Google, I really had some troubles as a beginner. I wish the OpenCV manual could be more like what CPP reference website have so that users could know what header files to use immediately. For example, on https://en.cppreference.com/w/cpp/io/basic_stringstream, it specifically tells you the function is "Defined in header <sstream>". While for OpenCV functions, it is very vague. For example, on https://docs.opencv.org/trunk/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56, the module name was hidden in the url, which was not so obvious to the new users.

##### Steps to reproduce

N/A.

**Comment by alalek** [comment]
Perhaps fully automatic processing (by doxygen) is not very helpful.
Only OpenCV module's headers should be suggested (opencv2/core.hpp , opencv2/imgcodecs.hpp, ...)
We should not suggest to include "detail" headers like "opencv2/core/matx.hpp".

Perhaps we should add "include" code blocks into details of documentation groups:
```
/**
@addtogroup imgcodecs
... here ...
@{
*/
```
