### ISSUE TITLE
Android: update samples (camera permissions)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#13514]
Modern Android platforms require **runtime permissions** for Camera.

More info: https://developer.android.com/training/permissions/requesting

**Comment by hannesa2** [comment]
I'm interested to make a PR to open an AndroidStudio project and it compiles out of the box

- C libs (.so and .a)
- samples (.apk)
- libraries ? (.aar)

But I've always issues to find the entry point.
eg https://github.com/opencv/opencv/blob/master/platforms/android/README.android here it points to a absolute old and obsolete webpage

My question: what's the purpose of this .py files ? eg ndk-18.config.py
The answer should reflect in a PR to update this README.android

**Comment by hannesa2** [comment]
Are the files under `samples/android` generated somehow ?
To ask the question different: makes it sense to convert this directory with a PR to an AndroidStudio project ?

**Comment by alalek** [comment]
`.py` files are used to build multi-arch Android SDK package.

You can try to start from using this package itself (it includes current state of samples):
- [opencv-4.0.1-android-sdk.zip](https://github.com/opencv/opencv/releases/download/4.0.1/opencv-4.0.1-android-sdk.zip) from https://github.com/opencv/opencv/releases/tag/4.0.1
- open `OpenCV-android-sdk/samples` in Android Studio

---

Using OpenCV for Android from sources:

1.
Setup environment variables to your Android SDK and NDK, something like that:
```
ANDROID_HOME="/opt/android/android-sdk.studio"
ANDROID_NDK_HOME="/opt/android/android-sdk.studio/ndk-bundle"
```

2. Install [ninja-build](https://ninja-build.org/) (you can try to remove `-GNinja` CMake option if you don't have this tool - but this mode is not tested)

3.
Gradle project is generated via CMake (run in clean "build folder"):
```
cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a with NEON" <opencv_src_path>
```

Specify "ANDROID_ABI" to arch of your test device (emulator may not work) - you may check `ndk-18.config.py` for correct values and/or extra options.

Finally, CMake output should contain these lines:
```
--   Android NDK:                   /opt/android/android-sdk.studio/ndk-bundle (ver 18.1.5063045)
--     Android ABI:                 armeabi-v7a
--     NDK toolchain:               arm-linux-androideabi-clang
--     STL type:                    c++_static
--     Native API level:            16
--   Android SDK:                   /opt/android/android-sdk.studio (tools: 26.1.1 build tools: 28.0.3)
```

4.
Build JNI:
```
cmake --build . --target opencv_java
```

5.
Generated Gradle project is located in: `opencv_android` (open this directory in Android Studio).

**Comment by komakai** [comment]
Created PR #15105

**Comment by asmorkalov** [comment]
@komakai @alalek Could we close the issue?

**Comment by komakai** [comment]
@asmorkalov fine by me
