### ISSUE TITLE
Hardcoded gradle `res.srcDirs` in OpenCV 4.0.1 Android pack

### ISSUE THREAD

**Issue by cuihaoleo** [opencv/opencv#13522]
##### System information (version)

- OpenCV => 4.0.1 (Android Pack)

##### Detailed description

I downloaded `opencv-4.0.1-android-sdk.zip` from official website, imported to my Android Studio project. When compiling app, the compiler complains `Cannot resolve symbol 'styleable'`.

The problem is cause by the wrong settings in `OpenCV-android-sdk/sdk/java/build.gradle`:
```
res.srcDirs = ['/build/master_pack-android/opencv/modules/java/android_sdk/android_gradle_lib/res']
```

After I changed it to `res.srcDirs = ['res']`, I can compile my project.

**Comment by alalek** [comment]
relates #13386

**Comment by alalek** [comment]
Mentioned file is here for mistake, use `build.gradle` from ``sdk` directory:
```.diff
-OpenCV-android-sdk/sdk/java/build.gradle
+OpenCV-android-sdk/sdk/build.gradle
```

**Comment by tiensu** [comment]
I have the same error. I changed to res.srcDirs = ['res'] but when run, error is: OpenCV was not initialised correctly. Application will be shutdown"
Can anyone help me?
