### ISSUE TITLE
OpenCV(4.0.0) /home/liushuanpeng/workspace/opencvcompile/opencv/modules/dnn/src/op_inf_engine.cpp:533: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: The output blob size is not equal to the network output size: got 4 expecting 3 in function 'initPlugin'

### ISSUE THREAD

**Issue by liushuanpeng** [opencv/opencv#13525]
when i used opencv4.0.0，i use openvino for optimized.
the error is:
OpenCV(4.0.0) /home/liushuanpeng/workspace/opencvcompile/opencv/modules/dnn/src/op_inf_engine.cpp:533: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: The output blob size is not equal to the network output size: got 4 expecting 3 in function 'initPlugin'

**Comment by dkurt** [comment]
@liushuanpeng, Please provide a reproducer.

**Comment by Bahramudin** [comment]
@liushuanpeng You should give the same size (width&height) as the network was trained on.  For example, you can get the size of the face detection like this:
Go to here: `C:\Intel\computer_vision_sdk_2018.5.445\deployment_tools\intel_models\face-detection-adas-0001` and open file `face-detection-adas-0001.prototxt` in the first line you will see the size: **name: "mobilenet_ssd_672x384"**

**Comment by dkurt** [comment]
Let me close it for now.
