### ISSUE TITLE
 undefined reference to `cv::cuda::StreamAccessor::getStream(cv::cuda::Stream const&)'

### ISSUE THREAD

**Issue by TouchDeeper** [opencv/opencv#13531]
##### System information (version)

- OpenCV => 3.3.1 with cuda10
- Operating System / Platform => Ubuntu16.04
- Compiler => vim

##### Detailed description
When i process the last steps below, I encounter the make error as the image show
![2018-12-26 23-05-44](https://user-images.githubusercontent.com/39310744/50450019-09f6e380-0966-11e9-94c4-1025b063980a.png)
Can you give me some advice? Thanks a lot!

##### Steps to reproduce

1. clone the [OpenDTAM](https://github.com/alexanderkoumis/OpenDTAM.git)

2. install qtbase5-dev
 ```
sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
sudo apt-get update
sudo apt-get install qtbase5-dev
 ```

3.install boost
`sudo apt-get install libboost-system-dev libboost-thread-dev` 

4.Build OpenDTAM
 ```
cd OpenDTAM
mkdir build
cd build
cmake ../Cpp
make -j4
```

**Comment by alalek** [comment]
Build / Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by code-rat** [comment]
想问下最后你怎么解决这个问题的？
How to solve this problem finally?

**Comment by zkailinzhang** [comment]
same error
