### ISSUE TITLE
input image batch into tensorflow model error

### ISSUE THREAD

**Issue by LearnerZHENG** [opencv/opencv#13540]
##### System information (version)

- OpenCV => :3.4.4
- Operating System / Platform => :ubuntu
- Tensorflow => :1.11

##### Detailed description
The tensorflow model can read and run in opencv when just input one image. In order to run more quick (rather than run one image once), however, I try to input image batch (use cv2.vconcat()) to the tensorflow model, it return the error as follows:

    modules/dnn/src/layers/fully_connected_layer.cpp:154: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'run'

BTY, successfully input image batch and get results in tensorflow (means that the model is correct?)

Thanks a lot.

**Comment by dkurt** [comment]
@LearnerZHENG, The reproducer, please!
