### ISSUE TITLE
hdr header

### ISSUE THREAD

**Issue by kikuchitakuro** [opencv/opencv#13551]
##### System information (version)

- OpenCV => :3.4
- Operating System / Platform => :Windows 64 Bit / python
- Compiler => :(python 3.6) 

##### Detailed description

OpenCV writes a hdr file with header starting with "#?RGBE". But many programs suppose "#?RADIANCE" and don't work on files with "#?RGBE".  Would you change this header line to "#?RADIANCE"?

**Comment by saskatchewancatch** [comment]
It may be just as simple as changing the string const `programtype` in [rbge.cpp](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/rgbe.cpp#L148)'s write header routine from `RGBE` to `RADIANCE`.

I don't know this format well, but it looks like `programtype` is not determine write data routine for this format.

From what I've read, the hdr format should be specifying RADIANCE instead. The `rgbe.cpp` file is just a carry over file from a looong time ago that probably used RGBE when the supplier of `rgbe.cpp` made it.

**Comment by saskatchewancatch** [comment]
@kikuchitakuro Please see PR #16188 . Other projects have made this change and this should help. I haven't tested it within OpenCV. Any chance you'd be able to try it out and see if the image reader you use reads hdr files with this change as a sanity test?
