### ISSUE TITLE
samples namespace is not a thing. OpenCV4.0.0

### ISSUE THREAD

**Issue by FOSSBOSS** [opencv/opencv#13557]
There are 71 instances of a reference to a namespace called "samples" within the src:/samples/cpp directory cpp files.  looking at the code, 
....
string filename = samples::findFile(names[i]);
...
in every instance, this could could be replaced with: 
..
string filename = names[i];
...
which is how it formerly existed in previous versions. 
Here is a list with all the instances of this error, where they occurred:
`./stitching_detailed.cpp:409:        full_img = imread(samples::findFile(img_names[i]));
./stitching_detailed.cpp:730:        full_img = imread(samples::findFile(img_names[img_idx]));
./videocapture_gstreamer_pipeline.cpp:269:    file_name = samples::findFile(file_name);
./buildall.sh:7:#grep -rnw  . -e "samples::findFile"
./falsecolor.cpp:90:        img = imread(samples::findFile(argv[1]), IMREAD_GRAYSCALE);
./stitching.cpp:98:            Mat img = imread(samples::findFile(argv[i]));
./qrcode.cpp:48:        return_code = imageQRCodeDetect(samples::findFile(in_file_name), out_file_name);
./create_mask.cpp:106:    src = imread(samples::findFile(input_image));
./grabcut.cpp:288:    Mat image = imread(samples::findFile(filename), IMREAD_COLOR);
./lsd_lines.cpp:26:    String filename = samples::findFile(parser.get<String>("input"));
./ffilldemo.cpp:85:    image0 = imread(samples::findFile(filename), 1);
./cloning_demo.cpp:56:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:57:        string original_path2 = samples::findFile(folder + "destination1.png");
./cloning_demo.cpp:58:        string original_path3 = samples::findFile(folder + "mask.png");
./cloning_demo.cpp:93:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:94:        string original_path2 = samples::findFile(folder + "destination1.png");
./cloning_demo.cpp:95:        string original_path3 = samples::findFile(folder + "mask.png");
./cloning_demo.cpp:130:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:131:        string original_path2 = samples::findFile(folder + "destination1.png");
./cloning_demo.cpp:132:        string original_path3 = samples::findFile(folder + "mask.png");
./cloning_demo.cpp:167:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:168:        string original_path2 = samples::findFile(folder + "mask.png");
./cloning_demo.cpp:194:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:195:        string original_path2 = samples::findFile(folder + "mask.png");
./cloning_demo.cpp:221:        string original_path1 = samples::findFile(folder + "source1.png");
./cloning_demo.cpp:222:        string original_path2 = samples::findFile(folder + "mask.png");
./fitellipse.cpp:202:    image = imread(samples::findFile(filename), 0);
./image_alignment.cpp:215:    Mat inputImage = imread(samples::findFile(imgFile), IMREAD_GRAYSCALE);
./image_alignment.cpp:227:        template_image = imread(samples::findFile(tempImgFile), IMREAD_GRAYSCALE);
./calibration.cpp:300:            string fpath = samples::findFile(filename.substr(0, dir_pos + 1) + fname, false);
./calibration.cpp:303:                fpath = samples::findFile(fname);
./calibration.cpp:309:            fname = samples::findFile(fname);
./calibration.cpp:449:        if( !videofile && readStringList(samples::findFile(inputFilename), imageList) )
./mask_tmpl.cpp:29:    string filename = samples::findFile(parser.get<string>("i"));
./mask_tmpl.cpp:30:    string tmplname = samples::findFile(parser.get<string>("t"));
./mask_tmpl.cpp:31:    string maskname = samples::findFile(parser.get<string>("m"));
./logistic_regression.cpp:86:    const String filename = samples::findFile("data01.xml");
./inpaint.cpp:53:    string filename = samples::findFile(parser.get<string>("@image"));
./facial_features.cpp:53:    image = imread(samples::findFile(input_image_path));
./facial_features.cpp:101:    face_cascade.load(samples::findFile(cascade_path));
./facial_features.cpp:190:    eyes_cascade.load(samples::findFile(cascade_path, !cascade_path.empty()));
./facial_features.cpp:200:    nose_cascade.load(samples::findFile(cascade_path, !cascade_path.empty()));
./facial_features.cpp:210:    mouth_cascade.load(samples::findFile(cascade_path, !cascade_path.empty()));
./stereo_match.cpp:68:    img1_filename = samples::findFile(parser.get<std::string>(0));
./stereo_match.cpp:69:    img2_filename = samples::findFile(parser.get<std::string>(1));
./smiledetect.cpp:52:    cascadeName = samples::findFile(parser.get<string>("cascade"));
./smiledetect.cpp:53:    nestedCascadeName = samples::findFile(parser.get<string>("smile-cascade"));
./dbt_face_detection.cpp:52:    std::string cascadeFrontalfilename = samples::findFile("data/lbpcascades/lbpcascade_frontalface.xml");
./dft.cpp:35:    Mat img = imread(samples::findFile(filename), IMREAD_GRAYSCALE);
./facedetect.cpp:67:    if (!cascade.load(samples::findFile(cascadeName)))
./facedetect.cpp:96:        image = imread(samples::findFile("lena.jpg"), IMREAD_COLOR);
./distrans.cpp:120:    gray = imread(samples::findFile(filename), 0);
./detect_blob.cpp:81:    Mat img = imread(samples::findFile(fileName), IMREAD_COLOR);
./connected_components.cpp:45:    img = imread(samples::findFile(inputImage), IMREAD_GRAYSCALE);
./npr_demo.cpp:37:    string filename = samples::findFile(parser.get<string>("@image"));
./cloning_gui.cpp:321:        img0 = imread(samples::findFile(src));
./cloning_gui.cpp:323:        img2 = imread(samples::findFile(dest));
./cloning_gui.cpp:371:        img0 = imread(samples::findFile(src));
./cloning_gui.cpp:401:        img0 = imread(samples::findFile(src));
./cloning_gui.cpp:434:        img0 = imread(samples::findFile(src));
./matchmethod_orb_akaze_brisk.cpp:45:    fileName.push_back(samples::findFile(parser.get<string>(0)));
./matchmethod_orb_akaze_brisk.cpp:46:    fileName.push_back(samples::findFile(parser.get<string>(1)));
./letter_recog.cpp:525:    data_filename = samples::findFile(parser.get<string>("data"));
./letter_recog.cpp:529:        filename_to_load = samples::findFile(parser.get<string>("load"));
./demhist.cpp:81:    image = imread(samples::findFile(inputImage), IMREAD_GRAYSCALE);
./detect_mser.cpp:415:        imgOrig = imread(samples::findFile(input), IMREAD_GRAYSCALE);
./warpPerspective_demo.cpp:50:    string filename = samples::findFile(parser.get<string>("@input"));
./edge.cpp:60:    image = imread(samples::findFile(filename), IMREAD_COLOR);
./stereo_calib.cpp:353:    imagelistfn = samples::findFile(parser.get<string>("@input"));
./watershed.cpp:57:    string filename = samples::findFile(parser.get<string>("@input"));
./morphology2.cpp:68:    std::string filename = samples::findFile(parser.get<std::string>("@image"));
`

this was found using `grep -rnw  . -e "samples::findFile" `  after I realized not all the samples compiled while running my build script.  To be fair, I also looked for the namespace in all of these files, which could produce non-erroneous code, if fiindFile were a valid function or object, but none of that is there, samples::findFile() is not a thing, nor is it part of the cv namespace.
The g++ compiler error this generates is:

> error: ‘samples’ has not been declared

Please fix this, sample code is how beginners get interested in new projects

**Comment by FOSSBOSS** [comment]
Invalid son? this makes the source code fail to compile, in a large number of included programs. How exactly is that invalid? @garybradski what is going on here?

**Comment by alalek** [comment]
No idea what is you doing, but it compiles well with **corresponding** OpenCV version.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by ELJEEZY** [comment]
Question - @alalek (or @FOSSBOSS ), you mention that this compiles well with the corresponding OpenCV version. Which version are you using? I'm running into the same issue. I have both OpenCV and OpenCV installed, and also an update to OpenCV 3.4.4 (w/ OpenCV 3.4.4.py also installed). Do I need to direct my #include statements to a different OpenCV version than opencv2?

**Comment by alalek** [comment]
Do not try to use **new** samples with **old** OpenCV builds.
You should **use the same versions**, other cases are not tested.

Replace "master" branch with corresponding your OpenCV version in your URLs.
Or checkout the proper version of sources from opencv cloned repository (for example, `git checkout 3.4.4`).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by dangne** [comment]
I figured out that the samples work well in releases `3.4.3` and earlier.
From releases `3.4.4` onwards, they all produce the same error `error: ‘samples’ has not been declared`
