### ISSUE TITLE
c/op_inf_engine.cpp:533: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: The output blob size is not equal to the network output size: got 3 expecting 4 in function 'initPlugin'

### ISSUE THREAD

**Issue by liushuanpeng** [opencv/opencv#13569]
when i use opencv 4.0.0 and OpenVINO for intel engine opt, the error is:

**c/op_inf_engine.cpp:533: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: The output blob size is not equal to the network output size: got 3 expecting 4 in function 'initPlugin'**

when i use breakpoint, i find the core function is:

**Mat prob = handler_->nets[modelIdx].forward(handler_->output_layer);**

who know the problem, please help!

**Comment by liushuanpeng** [comment]
in opencv dnn,the function forward add mutex,the problem is gone.
eg:
  g_mutex.lock(); 
  Mat prob = handler_->nets[modelIdx].forward(handler_->output_layer);
  g_mutex.unlock();

who can give the certify,the function forward is not thread save?
the docment in opencv4.0.0 not find?
thanks!

**Comment by liushuanpeng** [comment]
i create handler_ in every thread i used, make sure the handler_ is the same in one thread. but the problem is still exists.

**Comment by alalek** [comment]
Need complete minimal reproducer:
- without external dependencies, OpenCV + OpenVINO/DLDT only
- specify exact versions of OpenCV / DLDT

Take a look on DNN module tests as reference for code/models.

**Comment by dkurt** [comment]
@liushuanpeng, Do you still have this problem? If so, please provide minimal working example so we can reproduce it and either fix a bug or suggest some fixes.

**Comment by dkurt** [comment]
Likely this issue similar to https://github.com/opencv/opencv/issues/13715. Both are caused by initialization of IE plugins in different threads (we keep them in the static map). I'll try to reproduce https://github.com/opencv/opencv/issues/13715 and fix it.

**Comment by dkurt** [comment]
@liushuanpeng, please test the changes from https://github.com/opencv/opencv/pull/13738.
