### ISSUE TITLE
Add support of MPEG DASH format to cv::VideoCapture

### ISSUE THREAD

**Issue by ysolovyov** [opencv/opencv#13568]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => mac, linux
- Compiler => clang, gcc

##### Detailed description

Will be good to `cv::VideoCapture` support mpeg dash format - https://www.bento4.com/developers/dash, currently it does not.

http://itmultimedia.ru/sozdanie-kontenta-mpeg-dash-s-pomoshhyu-mp4box-i-ffmpeg/

##### Steps to reproduce

Sample mpd that is playable in vlc 3.0.5 - http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/BigBuckBunny/2sec/BigBuckBunny_2s_onDemand_2014_05_09.mpd

**Comment by alalek** [comment]
Main purpose of OpenCV library is computer vision algorithms. So we don't want to maintain here all possible I/O formats directly.
OpenCV is able to use GStreamer and FFmpeg, so you can try this format via these backends (with proper plugins / custom FFmpeg build).
