### ISSUE TITLE
opencv 3.4.4 android sdk  stitching question. 

### ISSUE THREAD

**Issue by 778627421** [opencv/opencv#13561]
C:\Users\sunbo\Downloads\VideoRecord\VideoRecord-master\app\src\main>ndk-build
Android NDK: WARNING: Rebuilding STLport libraries from sources!
Android NDK: You might want to use $NDK/build/tools/build-cxx-stl.sh --stl=stlport
Android NDK: in order to build prebuilt versions to speed up your builds!
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries
D:/android-ndk-r16b/build//../build/core/build-binary.mk:693: Android NDK: Module Stitcher depends on undefined modules: D:/android-ndk-r16b/build//../sources/cxx-stl/stlport/libs/armeabi/libstlport_static.a
D:/android-ndk-r16b/build//../build/core/build-binary.mk:706: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.

C:\Users\sunbo\Downloads\VideoRecord\VideoRecord-master\app\src\main>ndk-build
Android NDK: WARNING: Rebuilding STLport libraries from sources!
Android NDK: You might want to use $NDK/build/tools/build-cxx-stl.sh --stl=stlport
Android NDK: in order to build prebuilt versions to speed up your builds!
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries
D:/android-ndk-r16b/build//../build/core/build-binary.mk:751: *** extraneous `endif'.  Stop.

C:\Users\sunbo\Downloads\VideoRecord\VideoRecord-master\app\src\main>ndk-build
Android NDK: WARNING: Rebuilding STLport libraries from sources!
Android NDK: You might want to use $NDK/build/tools/build-cxx-stl.sh --stl=stlport
Android NDK: in order to build prebuilt versions to speed up your builds!
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries
[armeabi-v7a] Compile++ thumb: Stitcher <= stitcher.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= dll_main.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= fstream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= strstream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= sstream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= ios.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= stdio_streambuf.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= istream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= ostream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= iostream.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= codecvt.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= collate.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= ctype.cpp
D:/android-ndk-r16b/build//../sources/cxx-stl/stlport/src/ctype.cpp:284:14: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
    return c >= 0 && size_t(c) < upperBound;
           ~ ^  ~
1 warning generated.
[armeabi-v7a] Compile++ thumb: stlport_static <= monetary.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= num_get.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= num_put.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= num_get_float.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= num_put_float.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= numpunct.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= time_facets.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= messages.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= locale.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= locale_impl.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= locale_catalog.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= facets_byname.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= complex.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= complex_io.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= complex_trig.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= string.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= bitset.cpp
[armeabi-v7a] Compile++ thumb: stlport_static <= allocators.cpp
[armeabi-v7a] Compile thumb  : stlport_static <= c_locale.c
[armeabi-v7a] Compile thumb  : stlport_static <= cxa.c
[armeabi-v7a] Compile++ thumb: stlport_static <= array_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= auxilary.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= class_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= cxxabi.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= cxxabi_vec.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= delete.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= dwarf_helper.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= dynamic_cast.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= enum_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= exception.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= fatal_error.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= function_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= fundamental_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= helper_func_internal.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= new.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= one_time_construction.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= pbase_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= personality.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= pointer_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= pointer_to_member_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= call_unexpected.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= si_class_type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= stdexcept.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= terminate.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= type_info.cc
[armeabi-v7a] Compile++ thumb: stlport_static <= vmi_class_type_info.cc
[armeabi-v7a] StaticLibrary  : libstlport_static.a
[armeabi-v7a] SharedLibrary  : libStitcher.so
jni\opencv2/core/mat.inl.hpp:886: error: undefined reference to 'cv::Mat::deallocate()'
jni\opencv2/core/mat.inl.hpp:774: error: undefined reference to 'cv::fastFree(void*)'
jni/stitcher.cpp:36: error: undefined reference to '__android_log_print'
jni\opencv2/core/cvstd.hpp:602: error: undefined reference to 'cv::String::allocate(unsigned int)'
jni/stitcher.cpp:37: error: undefined reference to 'cv::imread(cv::String const&, int)'
jni\opencv2/core/cvstd.hpp:648: error: undefined reference to 'cv::String::deallocate()'
jni\opencv2/core/mat.inl.hpp:886: error: undefined reference to 'cv::Mat::deallocate()'
jni\opencv2/core/mat.inl.hpp:774: error: undefined reference to 'cv::fastFree(void*)'
jni/stitcher.cpp:42: error: undefined reference to '__android_log_print'
jni/stitcher.cpp:43: error: undefined reference to 'cv::Stitcher::createDefault(bool)'
jni/stitcher.cpp:48: error: undefined reference to 'cv::detail::BestOf2NearestMatcher::BestOf2NearestMatcher(bool, float, int, int)'
jni/stitcher.cpp:58: error: undefined reference to 'cv::Stitcher::stitch(cv::_InputArray const&, cv::_OutputArray const&)'
jni/stitcher.cpp:62: error: undefined reference to '__android_log_print'
jni/stitcher.cpp:73: error: undefined reference to '__android_log_print'
jni\opencv2/core/mat.inl.hpp:886: error: undefined reference to 'cv::Mat::deallocate()'
jni\opencv2/core/mat.inl.hpp:774: error: undefined reference to 'cv::fastFree(void*)'
jni\opencv2/core/cvstd.hpp:648: error: undefined reference to 'cv::String::deallocate()'
jni/stitcher.cpp:37: error: undefined reference to 'vtable for cv::detail::FeatherBlender'
D:/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing
its key function
jni\opencv2/core/mat.inl.hpp:569: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni\opencv2/stitching/detail/motion_estimators.hpp:264: error: undefined reference to 'vtable for cv::detail::BundleAdjusterRay'
D:/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing
its key function
jni/opencv2/stitching.hpp:132: error: undefined reference to 'cv::UMat::~UMat()'
jni/opencv2/stitching.hpp:132: error: undefined reference to 'cv::UMat::~UMat()'
jni\opencv2/core/mat.inl.hpp:886: error: undefined reference to 'cv::Mat::deallocate()'
jni\opencv2/core/mat.inl.hpp:774: error: undefined reference to 'cv::fastFree(void*)'
jni\opencv2/stitching/detail/motion_estimators.hpp:157: error: undefined reference to 'cv::Mat::ones(int, int, int)'
jni\opencv2/stitching/detail/motion_estimators.hpp:157: error: undefined reference to 'vtable for cv::detail::BundleAdjusterBase'
D:/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing
its key function
jni\opencv2/core/cvstd.hpp:602: error: undefined reference to 'cv::String::allocate(unsigned int)'
jni\opencv2/stitching/detail/motion_estimators.hpp:135: error: undefined reference to 'cv::error(int, cv::String const&, char const*, char const*, int)'
jni\opencv2/core/cvstd.hpp:648: error: undefined reference to 'cv::String::deallocate()'
jni\opencv2/core/mat.inl.hpp:846: error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
jni\opencv2/core/mat.inl.hpp:795: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni\opencv2/core/cvstd.hpp:648: error: undefined reference to 'cv::String::deallocate()'
jni\opencv2/stitching/warpers.hpp:68: error: undefined reference to 'vtable for cv::detail::PlaneWarper'
D:/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing
its key function
```
**_D:/android-ndk-r16b/build//../sources/cxx-stl/stlport/stlport\stl/_construct.h:57: error: undefined reference to 'cv::UMat::~UMat()'
jni\opencv2/stitching/detail/matchers.hpp:62: error: undefined reference to 'cv::UMat::~UMat()'
jni\opencv2/core/mat.inl.hpp:569: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
jni\opencv2/core/mat.inl.hpp:569: error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libStitcher.so] Error 1_**
```

**Comment by alalek** [comment]
"stitching" module is not available via `libopencv_java`. `libopencv_stiching.a` should be used.

Looks like there are issues with linker dependencies.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by ExileZhu** [comment]
if I wanna use it ,what should I do?

**Comment by ExileZhu** [comment]
> "stitching" module is not available via `libopencv_java`. `libopencv_stiching.a` should be used.
> 
> Looks like there are issues with linker dependencies.
> Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
> This tracker is for issues and bugs that needs fix in OpenCV.

how   slove it
