### ISSUE TITLE
dnn: edge_detection.py throws exception

### ISSUE THREAD

**Issue by berak** [opencv/opencv#13576]
##### System information (version)
- OpenCV => 3.4.5 / 3.4.3 (all from pip)
- Operating System / Platform => ubuntu 18
- Compiler => python3

##### Detailed description

[sample from here](https://github.com/opencv/opencv/blob/master/samples/dnn/edge_detection.py) is crashing in `net.forward()` : 

```
<ipython-input-1-f9cbd62f1c7f> in <module>()
     43 print(inp.shape)
     44 net.setInput(inp)
---> 45 out = net.forward()
     46 out = out[0, 0]
     47 out = cv.resize(out, (frame.shape[1], frame.shape[0]))

error: OpenCV(3.4.3) /io/opencv/modules/dnn/misc/python/pyopencv_dnn.hpp:163: error: (-213:The function/feature is not implemented) Failed to call "forward" method in function 'forward'

```

the error is quite misleading, the `CropLayer` 's forward() method IS implemented, we can even add some `print()`  statements there, to see that it is called. 

but then, something weird happens. whatever i try,  the result is invalid here:

https://github.com/opencv/opencv/blob/79e13be04c7c1f3f6d23b8caaeaa70a4a13947b7/modules/dnn/misc/python/pyopencv_dnn.hpp#L159-L163
##### Steps to reproduce

[similar findings here](http://answers.opencv.org/question/206255/cv2error-failed-to-call-forward-method-in-function-forward/)

data used:
```
wget http://vcl.ucsd.edu/hed/hed_pretrained_bsds.caffemodel
wget https://raw.githubusercontent.com/s9xie/hed/master/examples/hed/deploy.prototxt
wget http://answers.opencv.org/upfiles/15458197561802667.jpg
```

btw, [c++ version here](https://gist.github.com/berak/1c97115b3b343f1e9440bb22cf77fc76) is all fine ;)

**Comment by dkurt** [comment]
@berak, Thank you! The following PR fixes that: https://github.com/opencv/opencv/pull/13600. However it's just a workaround and it'd be better to catch and print some python's error message.

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 6
>>> b = 3
>>> c = a / b
>>> type(a), type(b), type(c)
(<type 'int'>, <type 'int'>, <type 'int'>)
```
but
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 6
>>> b = 3
>>> c = a / b
>>> type(a), type(b), type(c)
(<class 'int'>, <class 'int'>, <class 'float'>)
```

Then we try to slice an array using float indices.

**Comment by berak** [comment]
thanks, pr works nicely for me (on py3) !
