### ISSUE TITLE
Segmentation fault by calling dnn forward

### ISSUE THREAD

**Issue by xonobo** [opencv/opencv#13575]
- OpenCV => 3.4.5 (RelWithDebInfo)
- Operating System / Platform => Ubuntu 18.04

Testing dnn by caffe model of GoogleNet. 

	for (int n=0; n<input_list.size(); ++n)
		cvNet->setInput(*input_list[n], input_names[n]);

	output_mats_.clear();
	//if (output_names.size() == 1)
	//	output_mats_.emplace_back( cvNet->forward() );
	//else
	//{
		vector< vector<Mat> > output_blobs;
		cvNet->forward(output_blobs, output_names);
		for (auto &lst : output_blobs)
			output_mats_.push_back(lst[0]);
	//}

Single output case runs with no problem. But the case supporting multiple output results in segmentation fault. The crash point is 

https://github.com/opencv/opencv/blob/3d44e9ad927f48ef0a44af97a7ed557a4fc3fe10/modules/dnn/src/dnn.cpp#L2562

**Comment by dkurt** [comment]
@xonobo, please provide a minimal working example. Which GoogLeNet is used? What output names are passed?

**Comment by dkurt** [comment]
@xonobo, This is a kind reminder. We need to know if [Caffe's GoogLeNet](http://dl.caffe.berkeleyvision.org/) is used and which outputs are requested.

Please note that we can close incomplete issues which are not reproducible.

**Comment by xonobo** [comment]
Here is the code to reproduce:

```
#include <opencv2/opencv.hpp>

using namespace cv;

int main(int argc, char* argv[])
{
  String modelTxt = "bvlc_googlenet.prototxt";
  String modelBin = "bvlc_googlenet.caffemodel";
  String imageFile = "space_shuttle.jpg";

  std::vector<cv::String> input_names = {"data"};
  std::vector<cv::String> output_names = {"loss3/classifier", "output"};

  cv::dnn::Net cvNet = cv::dnn::readNetFromCaffe(modelTxt, modelBin);

  Mat img = imread(imageFile);
  std::vector<Mat*> input_list = {&img};

  std::vector<Mat> output_mats;
  output_mats.clear();

  for (int n=0; n<input_list.size(); ++n)
    cvNet.setInput(*input_list[n], input_names[n]);

  std::vector< std::vector<Mat> > output_blobs;
  cvNet.forward(output_blobs, output_names);
  for (auto &lst : output_blobs)
    output_mats.push_back(lst[0]);

  return 0;
}
```

Links to files mentioned are:
[https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/bvlc_googlenet.prototxt](url)
[http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel](url)
[https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/space_shuttle.jpg](url)

**Comment by dkurt** [comment]
@xonobo, please check the latest state of 3.4 branch. Corresponding fix has been merged.
