### ISSUE TITLE
build error, 4.0, openvx enabled. "modules/core/include/opencv2/core/hal/interface.h:68:28: error: void value not ignored as it ought to be"

### ISSUE THREAD

**Issue by fcyella** [opencv/opencv#13588]
- OpenCV => 4.0
- Operating System / Platform => ARM 64bit
- Compiler => GCC 7.3.0
script:     cmake -DOPENVX_ROOT=/usr -DWITH_OPENVX=ON -DENABLE_PRECOMPILED_HEADERS=NO -DCMAKE_BUILD_TYPE=Release ../ 

##### Steps to reproduce
[ 27%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/kmeans.cpp.o
[ 27%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lapack.cpp.o
[ 27%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lda.cpp.o
[ 27%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/logger.cpp.o
[ 28%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lpsolver.cpp.o
[ 28%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lut.cpp.o
In file included from /home/root/opencv/modules/core/include/opencv2/core/cvdef.h:165:0,
                 from /home/root/opencv/modules/core/include/opencv2/core.hpp:52,
                 from /home/root/opencv/modules/core/include/opencv2/core/utility.hpp:56,
                 from /home/root/opencv/modules/core/src/precomp.hpp:49,
                 from /home/root/opencv/modules/core/src/lut.cpp:6:
/home/root/opencv/3rdparty/openvx/include/ivx.hpp: In static member function 'static int ivx::Image::formatToMatType(vx_df_image, vx_uint32)':
/home/root/opencv/modules/core/include/opencv2/core/hal/interface.h:68:28: error: void value not ignored as it ought to be
 #define CV_USRTYPE1 (void) "CV_USRTYPE1 support has been dropped in OpenCV 4.0"
                            ^
/home/root/opencv/modules/core/include/opencv2/core/hal/interface.h:68:28: note: in definition of macro 'CV_USRTYPE1'
 #define CV_USRTYPE1 (void) "CV_USRTYPE1 support has been dropped in OpenCV 4.0"
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:506: modules/core/CMakeFiles/opencv_core.dir/src/lut.cpp.o] Error 1

**Comment by fcyella** [comment]
I think it's related to compiler configuration or something. Did anyone meet this error before?

**Comment by Nuzhny007** [comment]
Yes. Reason: https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/interface.h#L67

**Comment by fcyella** [comment]
Hi Nuzhny
Did you make it work?

**Comment by fcyella** [comment]
I think the statement is OK, but somehow the compiler reports an error.  Need change the CMAKE scripts?

**Comment by fcyella** [comment]
upgrade to 4.0.1, this problem disappears. Thanks for you attention.

**Comment by Nuzhny007** [comment]
Hm. Upgrade doesn't help me on Windows + MSVC 2017.

**Comment by fcyella** [comment]
yes, I made a mistake, 4.0.1 doesn't work either.

**Comment by fcyella** [comment]
Anyone else met this error?

**Comment by alalek** [comment]
Try 3.4 branch.
There is no active support for OpenVX build mode.

**Comment by berak** [comment]
`CV_USRTYPE1` does no more exist in 4.0, it's enum value was reused for CV_16F.

so you get the error, where this thing is **used**, not where it's declared, like a simple:

    int t = CV_USRTYPE1; // same error, trying to assign `void` to an `int`

it's coming from here:

https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/3rdparty/openvx/include/ivx.hpp#L1742

and imho, it needs some cleanup, like:
```
        case VX_DF_IMAGE_NV21: return planeIdx == 0 ? CV_8UC1 : CV_8UC2;

        default: 
#ifdef OPENCV_TRAITS_ENABLE_LEGACY_DEFAULTS
               return CV_USRTYPE1;
#else
               CV_Error( some message);
#endif
```

**Comment by fcyella** [comment]
Hi berak,
I think this is a good sulotion, will this change be in the master branch?

**Comment by berak** [comment]
@fcyella , i have to do some tests first. (rebuilding with openvx) .

i'll also have to see, if i run into this [problem reported here](http://answers.opencv.org/question/207067/opencv-401-build-error-if-enabled-openvxskipsmallimagfes-is-not-a-member-of-cvanonymousovx/)
