### ISSUE TITLE
Opencv.js build failed

### ISSUE THREAD

**Issue by Yiwei-Brunhlio** [opencv/opencv#13598]
I saw a lot of questions about the failure of opencv.js build, I tried to build it, after my efforts, it failed, it took me a lot of time. Not very smooth, but it started to compile, but it still failed when linked. Why not provide an already compiled opencv.js?

**Comment by Yiwei-Brunhlio** [comment]
I found its third-party repository, but I would prefer to get the official version.

**Comment by dkurt** [comment]
@Yiwei-Brunhlio, There is a guide of how to build OpenCV.js: https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html
and even nightly build of it: https://docs.opencv.org/master/opencv.js which you can use in your applications.

Just for example, http://dkurtaev.github.io/opencv_canny:
```html
<script src="https://docs.opencv.org/master/opencv.js" type="text/javascript"></script>
```

Let me close this issue.

**Comment by Yiwei-Brunhlio** [comment]
thank!
