### ISSUE TITLE
Kalman filter implementation, small issue in a comment

### ISSUE THREAD

**Issue by laurent-george** [opencv/opencv#13597]
https://github.com/opencv/opencv/blob/808ba552c532408bddd5fe51784cf4209296448a/modules/video/src/kalman.cpp#L99

I think the comment should be:

 // handle the case when there will be no measurement before the next predict.

Is that correct ?

**Comment by csukuangfj** [comment]
yes, I think so.

If there is no measurement before the next predict, `post`s are not updated in [`correct()`](https://github.com/opencv/opencv/blob/808ba552c532408bddd5fe51784cf4209296448a/modules/video/src/kalman.cpp#L126). Therefore, we have to update them in `predict()`. If a measurement comes, the two are overwritten.
