### ISSUE TITLE
An error occurred while setting LIB_SUFFIX=64

### ISSUE THREAD

**Issue by saliven1970** [opencv/opencv#13595]
##### System information (version)

- OpenCV => :3.4
- Operating System / Platform => :CentOS-7.5 64Bit:
- Compiler => :GCC:

##### Detailed description
The RPM installation package under CENTOS was automatically added with LIB_SUFFIX=64 when use cmake. At this time, an error occurred and the shared library file directory became lib6464.
I think there is an error in line 595 of the CMakeLists.txt file, because the new version of cmake will automatically form CMAKE_INSTALL_LIBDIR according to the operating system environment, and the 64 - bit system will form lib64 without adding a LIB_SUFFIX it self

##### Steps to reproduce

cmake -DLIB_SUFFIX=64

**Comment by alalek** [comment]
Workaround:
- override `OPENCV_LIB_INSTALL_PATH` in your build scripts.

**Comment by saliven1970** [comment]
I change CMakeLists.txt begin line 594:

    include(GNUInstallDirs)
    ocv_update(OPENCV_LIB_INSTALL_PATH     ${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX})
    ocv_update(OPENCV_3P_LIB_INSTALL_PATH  share/OpenCV/3rdparty/${OPENCV_LIB_INSTALL_PATH})
    ocv_update(OPENCV_SAMPLES_SRC_INSTALL_PATH    share/OpenCV/samples)
    ocv_update(OPENCV_JAR_INSTALL_PATH share/OpenCV/java)
    ocv_update(OPENCV_OTHER_INSTALL_PATH   share/OpenCV)

    if(NOT DEFINED OPENCV_CONFIG_INSTALL_PATH)
      math(EXPR SIZEOF_VOID_P_BITS "8 * ${CMAKE_SIZEOF_VOID_P}")
      if(LIB_SUFFIX AND NOT SIZEOF_VOID_P_BITS EQUAL LIB_SUFFIX)
        ocv_update(OPENCV_CONFIG_INSTALL_PATH ${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX}/cmake/opencv)
      else()
        ocv_update(OPENCV_CONFIG_INSTALL_PATH share/OpenCV)
      endif()
    endif()

To:

    include(GNUInstallDirs)
    ocv_update(OPENCV_LIB_INSTALL_PATH     ${CMAKE_INSTALL_LIBDIR})
    ocv_update(OPENCV_3P_LIB_INSTALL_PATH  share/OpenCV/3rdparty/${OPENCV_LIB_INSTALL_PATH})
    ocv_update(OPENCV_SAMPLES_SRC_INSTALL_PATH    share/OpenCV/samples)
    ocv_update(OPENCV_JAR_INSTALL_PATH share/OpenCV/java)
    ocv_update(OPENCV_OTHER_INSTALL_PATH   share/OpenCV)

    if(NOT DEFINED OPENCV_CONFIG_INSTALL_PATH)
      math(EXPR SIZEOF_VOID_P_BITS "8 * ${CMAKE_SIZEOF_VOID_P}")
      if(LIB_SUFFIX AND NOT SIZEOF_VOID_P_BITS EQUAL LIB_SUFFIX)
        ocv_update(OPENCV_CONFIG_INSTALL_PATH ${CMAKE_INSTALL_LIBDIR}/cmake/opencv)
      else()
        ocv_update(OPENCV_CONFIG_INSTALL_PATH share/OpenCV)
      endif()
    endif()


It well OK
