### ISSUE TITLE
cv2.imshow Assertion failed error

### ISSUE THREAD

**Issue by Manny224** [opencv/opencv#13590]
This my extremely simple code that I tried to run because my more complex video capture did not work. I get the exact same error listed below. I am running MacOS Mojave. This exact code ran perfectly fine on another system, but on min it crashed. None of the other threads have helped and i have tried everything related to waitKey so I know it is not that. Any help is appreciated!

**My Code**
img = cv2.imread(path)
    print("done1")
    cv2.imshow('test.jpg', img)
    print("done2")
    cv2.waitKey(0)

NOTE: the program crashes after "done 1"

**Error**
2019-01-07 08:43:04.263 Python[56993:2979403] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff2c21b824 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 386
	1   AppKit                              0x00007fff2c218bd0 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
	2   AppKit                              0x00007fff2c2d94ab -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	3   AppKit                              0x00007fff2c2185fa -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	4   AppKit                              0x00007fff2c2d9460 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
	5   QtGui                               0x000000010bd6b028 -[QCocoaPanel initWithContentRect:styleMask:backing:defer:] + 74
	6   QtGui                               0x000000010bd71bbf -[NSWindow(QWidgetIntegration) qt_initWithQWidget:contentRect:styleMask:] + 81
	7   QtGui                               0x000000010bd62e1c _ZL20qt_mac_create_windowP7QWidgetjmRK5QRect + 427
	8   QtGui                               0x000000010bd62aa1 _ZN14QWidgetPrivate18qt_create_root_winEv + 65
	9   QtGui                               0x000000010bd648d3 _ZN14QWidgetPrivate10create_sysElbb + 1079
	10  QtGui                               0x000000010bdfad25 _ZN7QWidget6createElbb + 587
	11  QtGui                               0x000000010bdf99f6 _ZN14QWidgetPrivate4initEP7QWidget6QFlagsIN2Qt10WindowTypeEE + 362
	12  QtGui                               0x000000010bdf97e0 _ZN7QWidgetC2EPS_6QFlagsIN2Qt10WindowTypeEE + 122
	13  QtGui                               0x000000010bd7ccca _ZN14QDesktopWidgetC2Ev + 32
	14  QtGui                               0x000000010bdc0183 _ZN12QApplication7desktopEv + 53
	15  QtGui                               0x000000010bd78a05 _Z9flipPointRK7CGPoint + 32
	16  QtGui                               0x000000010bd58961 _ZN7QCursor3posEv + 47
	17  QtGui                               0x000000010bdd00c5 _ZN11QMouseEventC2EN6QEvent4TypeERK6QPointN2Qt11MouseButtonE6QFlagsIS6_ES7_INS5_16KeyboardModifierEE + 79
	18  QtGui                               0x000000010c2e5426 _ZN20QGraphicsViewPrivateC2Ev + 340
	19  QtGui                               0x000000010c2e89d5 _ZN13QGraphicsViewC2EP7QWidget + 37
	20  cv2.cpython-36m-darwin.so           0x00000001056b16cf _ZN15DefaultViewPortC2EP8CvWindowi + 31
	21  cv2.cpython-36m-darwin.so           0x00000001056acd3d _ZN8CvWindowC2E7QStringi + 397
	22  cv2.cpython-36m-darwin.so           0x00000001056a4d63 _ZN11GuiReceiver12createWindowE7QStringi + 227
	23  cv2.cpython-36m-darwin.so           0x00000001056a4bbc cvNamedWindow + 540
	24  cv2.cpython-36m-darwin.so           0x00000001056a72f1 _ZN11GuiReceiver9showImageE7QStringPv + 161
	25  cv2.cpython-36m-darwin.so           0x00000001056a719c cvShowImage + 572
	26  cv2.cpython-36m-darwin.so           0x000000010569f8bb _ZN2cv6imshowERKNS_6StringERKNS_11_InputArrayE + 475
	27  cv2.cpython-36m-darwin.so           0x0000000104bce3d4 _ZL18pyopencv_cv_imshowP7_objectS0_S0_ + 404
	28  Python                              0x00000001034f712e _PyCFunction_FastCallDict + 463
	29  Python                              0x000000010355d0e6 call_function + 491
	30  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	31  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	32  Python                              0x0000000103554f6b PyEval_EvalCodeEx + 57
	33  Python                              0x00000001034df527 function_call + 339
	34  Python                              0x00000001034be589 PyObject_Call + 101
	35  Python                              0x0000000103555825 _PyEval_EvalFrameDefault + 2175
	36  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	37  Python                              0x000000010355d0bd call_function + 450
	38  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	39  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	40  Python                              0x000000010355d0bd call_function + 450
	41  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	42  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	43  Python                              0x000000010355d0bd call_function + 450
	44  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	45  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	46  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	47  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	48  Python                              0x00000001034be589 PyObject_Call + 101
	49  Python                              0x0000000103509b86 slot_tp_call + 50
	50  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	51  Python                              0x000000010355d0b6 call_function + 443
	52  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	53  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	54  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	55  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	56  Python                              0x00000001034be589 PyObject_Call + 101
	57  Python                              0x0000000103509b86 slot_tp_call + 50
	58  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	59  Python                              0x000000010355d0b6 call_function + 443
	60  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	61  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	62  Python                              0x000000010355df49 fast_function + 218
	63  Python                              0x000000010355d0bd call_function + 450
	64  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	65  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	66  Python                              0x000000010355df49 fast_function + 218
	67  Python                              0x000000010355d0bd call_function + 450
	68  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	69  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	70  Python                              0x000000010355d0bd call_function + 450
	71  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	72  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	73  Python                              0x000000010355d0bd call_function + 450
	74  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	75  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	76  Python                              0x000000010355d0bd call_function + 450
	77  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	78  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	79  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	80  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	81  Python                              0x00000001034be589 PyObject_Call + 101
	82  Python                              0x000000010350a4d8 slot_tp_init + 57
	83  Python                              0x0000000103507439 type_call + 184
	84  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	85  Python                              0x000000010355d0b6 call_function + 443
	86  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	87  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	88  Python                              0x000000010355d0bd call_function + 450
	89  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	90  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	91  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	92  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	93  Python                              0x00000001034be589 PyObject_Call + 101
	94  Python                              0x0000000103555825 _PyEval_EvalFrameDefault + 2175
	95  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	96  Python                              0x000000010355d0bd call_function + 450
	97  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	98  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	99  Python                              0x000000010355d0bd call_function + 450
	100 Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	101 Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	102 Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	103 Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	104 Python                              0x00000001034be589 PyObject_Call + 101
	105 Python                              0x0000000103593ee7 t_bootstrap + 70
	106 libsystem_pthread.dylib             0x00007fff5c014339 _pthread_body + 126
	107 libsystem_pthread.dylib             0x00007fff5c0172a7 _pthread_start + 70
	108 libsystem_pthread.dylib             0x00007fff5c013445 thread_start + 13
)
2019-01-07 08:43:04.301 Python[56993:2979403] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1560.12/Foundation/Misc.subproj/NSUndoManager.m:361
2019-01-07 08:43:04.304 Python[56993:2979403] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2ecfce65 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5ad53720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2ed17ab2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff310bbd1d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff30fec159 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff2c192da2 -[NSApplication run] + 932
	6   QtGui                               0x000000010bd7ec12 _ZN26QEventDispatcherMacPrivate22ensureNSAppInitializedEv + 128
	7   QtGui                               0x000000010bd7e4ad _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 693
	8   QtCore                              0x0000000109fccd9f _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 81
	9   cv2.cpython-36m-darwin.so           0x00000001056a473f cvWaitKey + 207
	10  cv2.cpython-36m-darwin.so           0x00000001056a4d87 _ZN11GuiReceiver12createWindowE7QStringi + 263
	11  cv2.cpython-36m-darwin.so           0x00000001056a4bbc cvNamedWindow + 540
	12  cv2.cpython-36m-darwin.so           0x00000001056a72f1 _ZN11GuiReceiver9showImageE7QStringPv + 161
	13  cv2.cpython-36m-darwin.so           0x00000001056a719c cvShowImage + 572
	14  cv2.cpython-36m-darwin.so           0x000000010569f8bb _ZN2cv6imshowERKNS_6StringERKNS_11_InputArrayE + 475
	15  cv2.cpython-36m-darwin.so           0x0000000104bce3d4 _ZL18pyopencv_cv_imshowP7_objectS0_S0_ + 404
	16  Python                              0x00000001034f712e _PyCFunction_FastCallDict + 463
	17  Python                              0x000000010355d0e6 call_function + 491
	18  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	19  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	20  Python                              0x0000000103554f6b PyEval_EvalCodeEx + 57
	21  Python                              0x00000001034df527 function_call + 339
	22  Python                              0x00000001034be589 PyObject_Call + 101
	23  Python                              0x0000000103555825 _PyEval_EvalFrameDefault + 2175
	24  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	25  Python                              0x000000010355d0bd call_function + 450
	26  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	27  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	28  Python                              0x000000010355d0bd call_function + 450
	29  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	30  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	31  Python                              0x000000010355d0bd call_function + 450
	32  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	33  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	34  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	35  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	36  Python                              0x00000001034be589 PyObject_Call + 101
	37  Python                              0x0000000103509b86 slot_tp_call + 50
	38  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	39  Python                              0x000000010355d0b6 call_function + 443
	40  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	41  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	42  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	43  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	44  Python                              0x00000001034be589 PyObject_Call + 101
	45  Python                              0x0000000103509b86 slot_tp_call + 50
	46  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	47  Python                              0x000000010355d0b6 call_function + 443
	48  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	49  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	50  Python                              0x000000010355df49 fast_function + 218
	51  Python                              0x000000010355d0bd call_function + 450
	52  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	53  Python                              0x000000010355d866 _PyEval_EvalCodeWithName + 1747
	54  Python                              0x000000010355df49 fast_function + 218
	55  Python                              0x000000010355d0bd call_function + 450
	56  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	57  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	58  Python                              0x000000010355d0bd call_function + 450
	59  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	60  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	61  Python                              0x000000010355d0bd call_function + 450
	62  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	63  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	64  Python                              0x000000010355d0bd call_function + 450
	65  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	66  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	67  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	68  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	69  Python                              0x00000001034be589 PyObject_Call + 101
	70  Python                              0x000000010350a4d8 slot_tp_init + 57
	71  Python                              0x0000000103507439 type_call + 184
	72  Python                              0x00000001034be6d3 _PyObject_FastCallDict + 143
	73  Python                              0x000000010355d0b6 call_function + 443
	74  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	75  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	76  Python                              0x000000010355d0bd call_function + 450
	77  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	78  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	79  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	80  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	81  Python                              0x00000001034be589 PyObject_Call + 101
	82  Python                              0x0000000103555825 _PyEval_EvalFrameDefault + 2175
	83  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	84  Python                              0x000000010355d0bd call_function + 450
	85  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	86  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	87  Python                              0x000000010355d0bd call_function + 450
	88  Python                              0x0000000103555621 _PyEval_EvalFrameDefault + 1659
	89  Python                              0x000000010355e1e9 _PyFunction_FastCall + 121
	90  Python                              0x00000001034be708 _PyObject_FastCallDict + 196
	91  Python                              0x00000001034be82b _PyObject_Call_Prepend + 156
	92  Python                              0x00000001034be589 PyObject_Call + 101
	93  Python                              0x0000000103593ee7 t_bootstrap + 70
	94  libsystem_pthread.dylib             0x00007fff5c014339 _pthread_body + 126
	95  libsystem_pthread.dylib             0x00007fff5c0172a7 _pthread_start + 70
	96  libsystem_pthread.dylib             0x00007fff5c013445 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by alalek** [comment]
> Main Thread
> ...
>  _pthread_start

Restriction of used UI API.
For example, this doesn't work well from Python Interactive IDEs (code is called from other threads).
