### ISSUE TITLE
opencv_python3_LIB_DEPENDS points to wrong python

### ISSUE THREAD

**Issue by mfischer-gundlach** [opencv/opencv#13603]
##### System information (version)
- OpenCV => 4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

CMake appears to set the variable `opencv_python3_LIB_DEPENDS` to the root environment and not the environment which I point to by setting the CMake variables.   

##### Steps to reproduce

I use anaconda to manage environments. The root uses python 3.5 and I created *OpenCV-master-py3* which runs python 3.6. I want to compile the python bindings for the *OpenCV-master-py3* environment and set 

```
-DPYTHON3_EXECUTABLE=C:\Users\ME\AppData\Local\Anaconda3\envs\OpenCV-master-py3\python.exe -DPYTHON3_INCLUDE_DIR=C:\Users\ME\AppData\Local\Anaconda3\envs\OpenCV-master-py3\include -DPYTHON3_LIBRARY=C:\Users\ME\AppData\Local\Anaconda3\envs\OpenCV-master-py3\libs\python36.lib -DPYTHON3_NUMPY_INCLUDE_DIRS=C:\Users\ME\AppData\Local\Anaconda3\envs\OpenCV-master-py3\Lib\site-packages\numpy\core\include -DPYTHON3_PACKAGES_PATH=C:\Users\ME\AppData\Local\Anaconda3\envs\OpenCV-master-py3\Lib\site-packages

```
 for generating the project. Looking into the `CMakeCache.txt` file shows:

```
//Path to Python interpretor
PYTHON3_EXECUTABLE:FILEPATH=C:/Users/ME/AppData/Local/Anaconda3/envs/OpenCV-master-py3/python.exe

//Python include dir
PYTHON3_INCLUDE_DIR:PATH=C:/Users/ME/AppData/Local/Anaconda3/envs/OpenCV-master-py3/include

//Path to Python library
PYTHON3_LIBRARY:FILEPATH=C:/Users/ME/AppData/Local/Anaconda3/envs/OpenCV-master-py3/libs/python36.lib

//Path to numpy headers
PYTHON3_NUMPY_INCLUDE_DIRS:PATH=C:/Users/ME/AppData/Local/Anaconda3/envs/OpenCV-master-py3/Lib/site-packages/numpy/core/include

//Where to install the python packages.
PYTHON3_PACKAGES_PATH:PATH=C:/Users/ME/AppData/Local/Anaconda3/envs/OpenCV-master-py3/Lib/site-packages
```

**BUT** also

```
//Dependencies for the target
opencv_python3_LIB_DEPENDS:STATIC=general;C:/Users/ME/AppData/Local/Anaconda3/libs/python35.lib;
```
Eventually, the `3.5` version number shows up a couple of times and the file

`cv2.cp35-win_amd64.pyd` is generated and placed in my `site-package` folder. This will not work, as the versions are incompatible.

**Comment by alalek** [comment]
Build from scratch (clean build directory).
Debug CMake via `--trace` / `--trace-expand`.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
