### ISSUE TITLE
GaussianBlur does not support border type wrap

### ISSUE THREAD

**Issue by illiteratePhD** [opencv/opencv#13602]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => All
- Compiler => All

##### Detailed description

In the documentation for GaussianBlur() it is stated that one should use one of the options in BorderTypes. However, the WRAP option is not supported and will lead to an exception. 

##### Steps to reproduce

Run GaussianBlur with border type WRAP

**Comment by collenjones** [comment]
@alalek this seems like a bug that should be fixed (correctly handle wrap as a border type) -- not documentation that needs to be shored up. What do you think?

**Comment by asmorkalov** [comment]
@alalek what should be done for the ticket: documentation update or border mode support in code?

**Comment by asmorkalov** [comment]
Border mode WRAP does not make sense for GaussianBlur. The only action item: update the function documentation.

**Comment by GautamGottipati** [comment]
If no one is working on this issue , can I take this issue

**Comment by alalek** [comment]
@GautamGottipati Thank you for your interest.
Issue is already "assigned" and fixed (see reference link above your comment).

Issue will be closed then fix becomes available on default "master" branch (it will be done by regular "Merge 3.4" process, so just wait).
