### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by topdev20k** [opencv/opencv#13607]
How are you, everyone?
I am developing image animation using python , opencv 
  for FADEIN in range(0, int(anitime * fps)):
                         fadein = FADEIN / int(anitime * fps)
                         print(fadein)
                         dst = cv2.addWeighted(img, fadein, imgNext, fadein, -1)  # linear $
                         frame_array.append(dst)
but I am getting this error:  Unspecified error (The numpy array of typenum=2, ndims=3 can not be created) in allocate, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/python/src2/cv2.cpp, line 173
How can i fix this memory leak?
Thank you for your time

**Comment by dkurt** [comment]
@topdev20k, Please read issue template carefully. It says:

> * Try to be as detailed as possible in your report.

For now you code snippet is useless. Provide a minimal working example so anybody can just copy it and run.
