### ISSUE TITLE
undefined identifier : virtual void read( CvFileStorage* fs, CvFileNode* node );   in cascade training 

### ISSUE THREAD

**Issue by mahsank0345** [opencv/opencv#13609]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
This tool (traincascade) is not available in OpenCV 4.0. Use it from OpenCV 3.x.

---

BTW, Installation process is wrong - you didn't remove files from previous version.
