### ISSUE TITLE
Issue when storing results from a matrix operation in a matrix of a different type

### ISSUE THREAD

**Issue by jvolante** [opencv/opencv#13611]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => RHEL 7
- Compiler => GCC 6.2.1 20161010 (for GNAT Pro 17.1 20170104)

##### Detailed description

When doing a matrix operation, if the output matrix is of an incompatible type the results will neither be converted to the correct type, nor will any warning/error be thrown.

One of these things should happen because the current behavior leads to some very dangerous and difficult to find bugs.
##### Steps to reproduce
``` c++
cv::Mat testmat1(3,3, CV_16S, cv::Scalar(0));
cv::Mat testmat2(3,3, CV_32F, cv::Scalar(0));

testmat1.at<int16_t>(1,1) = 50;

cv::blur(testmat1, testmat2, cv::Size(3,3));

std::cout << testmat2.at<float>(1,1) << std::endl;
```

This doesn't give the expected output of 5.55555556.

**Comment by berak** [comment]
imho, there is no bug here, more a misunderstanding.

the result Mat from blur() will get reallocated, because it has the wrong type 
(CV_32F, but the input is CV_16S) . see yourself:

    cout << testmat2.type() << endl;
    3 // CV_16S, again.

now, 

    testmat2.at<float>(1,1)

will give you bogus values, because you access a short Mat as if it were float.

again, using the correct datatypes:
```
cv::Mat testmat1(3,3, CV_32F, cv::Scalar(0));
cv::Mat testmat2(3,3, CV_32F, cv::Scalar(0));
testmat1.at<float>(1,1) = 50;
cv::blur(testmat1, testmat2, cv::Size(3,3));
cout << testmat2.type() << endl;
std::cout << testmat2.at<float>(1,1) << std::endl;

5
5.55556
```

**Comment by alalek** [comment]
Debug mode with extra checks should point into buggy code.
Or use "const" for testmat2 to avoid reallocation (error will thrown).
