### ISSUE TITLE
OpenCV 4.0 build fails aurco

### ISSUE THREAD

**Issue by shivared** [opencv/opencv#13618]
Hi, I have been trying to install OpenCV4, following step by step from below link. I always seem to get this error. Can somebody please guide as to what I might be doing wrong here. 
https://www.pyimagesearch.com/2018/08/17/install-opencv-4-on-macos/

[ 13%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/arithm.dispatch.cpp.o
Note: Class Feature2D has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::Algorithm, cv::class, cv::Feature2D, cv::Algorithm
      Only the first base class will be used
[ 13%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/stringprintf.cc.o
[ 13%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1d/sources/ade/source/passes/communications.cpp.o
Error at 163: there are non-valid entries in the current block stack [['file', '/Users/pavanshivareddy/opencv_contrib/modules/aruco/include/opencv2/aruco/dictionary.hpp', True, True, None], [u'namespace', u'cv', True, True, None], [u'namespace', u'aruco', True, True, None], [u'enum CV_EXPORTS_W_SIMPLE', u'PREDEFINED_DICTIONARY_NAME', True, True, None]]
make[2]: *** [modules/python_bindings_generator/pyopencv_generated_include.h] Error 255
make[1]: *** [modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/array.cpp.o
[ 13%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/structurally_valid.cc.o
[ 13%] Building CXX object 3rdparty/protobuf/CMakeF

&&&& 

[ 17%] Linking CXX static library ../lib/liblibprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 17%] Built target libprotobuf
[ 17%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/matrix_sparse.cpp.o
[ 17%] Building CXX object modules/core

**Comment by dkurt** [comment]
@shivared, If you want to report a bug you should provide all the steps to reproduce it including cmake commands and it's summary. If you want to ask a question, please go to our forum: http://answers.opencv.org/.
