### ISSUE TITLE
I want to know that why OpenVINO does not support on Ubuntu 18.4?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#13612]
- OpenCV => : 4.0.1
- Operating System / Platform => :  Linux Ubuntu 18.4
- Compiler => :  GCC 7.3

##### Detailed description

I want to install OpenCV with OpenVINO support on Ubuntu 18.4, but in the API says that now it only supports on Ubuntu 16.4:

> Operating Systems
> Ubuntu* 16.04 long-term support (LTS), 64-bit
> CentOS* 7.4 or higher, 64-bit

I think it is very important that before publishing a new software or lib, it at least must supports the most new operating systems and also some older versions, becuase it is long time that people has already starts using Ubuntu 18.4 instead 16.4. So it will make problem for people who don't want or cannot go back to the previous veriosn for just one function compitablity. 

I really dont know what can be the reason, if it is not ready to support on Ubuntu 18.4, it will be better to do not publish, leave it till can be to use on Ubuntu newer versions.

**Comment by dkurt** [comment]
@Bahramudin,

From the latest OpenVINO release:

```
$ ls /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/lib/
centos_7.4  ubuntu_16.04  ubuntu_18.04
```
It looks like just a documentation bug.

**Comment by dkurt** [comment]
Anyway this is not OpenCV related issue. Let's move it to https://github.com/opencv/dldt.
