### ISSUE TITLE
Bug in SVM sigmoid kernel

### ISSUE THREAD

**Issue by olegb94** [opencv/opencv#13621]
Normally sigmoid kernel used in SVM is:
K(x, y) = tanh(gamma * <x, y> + coef0)

But in this  code different formula is implemented:
K(x, y) = -tanh(gamma * <x, y> + coef0)
https://github.com/opencv/opencv/blob/7d4bb9428b31ad144cfdc8cafe26b5c37258d489/modules/ml/src/svm.cpp#L198-L214

I'm not sure if it is intended, looks like a bug for me.

**Comment by alalek** [comment]
Feel free to to prepare PR with proposed fix.
Unfortunately this code part is [not covered by OpenCV tests](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20190121-011752_273/coverage_html/index.html). It would be nice to add some simple test for this code too.

**Comment by lochsh** [comment]
If @olegb94 isn't already looking at this, I'd love to have a look.  I'm new to contributing to OpenCV but familiar with SVMs and keen to get involved.
