### ISSUE TITLE
How can Android Platform not be packaged into a so？

### ISSUE THREAD

**Issue by tianshaokai** [opencv/opencv#13630]
1. I want each module to be a separate so.
2.In particular, delete JNI from Java.

**Comment by alalek** [comment]
There are no such packaging scripts, but you can try to do this via CMake:
- use `-DBUILD_SHARED_LIBS=ON`
- use `-DBUILD_opencv_java=OFF`

Custom builds / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
