### ISSUE TITLE
OpenCV 4.0.1, invalid namespace scope in median_blur.cpp, no need to include openvx code, 

### ISSUE THREAD

**Issue by fcyella** [opencv/opencv#13634]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => arm64 
- Compiler => GCC 7.3.0
-->

##### Detailed description
at line 476, median_blur.cpp, there is another namespace{}. And OpenVX code below is also in this scope, this will cause openvx build error. Is this scope necessary?  I suppose we can move the OpenVX code out of this namespace scope.

**Comment by berak** [comment]
yes, the namespace gets in the way. problem is here:

https://github.com/opencv/opencv/blob/7e2ebecd52232d02e2d53f3e073c076be73e3470/modules/imgproc/src/median_blur.cpp#L992-L995

it is intended, to write a specialization for `cv::ovx::skipSmallImages` but with the additional anonymous namespace we get:  `cv::{anonymous}::ovx::skipSmallImages` 


[more details here](http://answers.opencv.org/question/207067/opencv-401-build-error-if-enabled-openvxskipsmallimagfes-is-not-a-member-of-cvanonymousovx/)
