### ISSUE TITLE
Bug in OpenCV DNN module

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#13636]
##### System information (version)

- OpenCV => :grey_question: 4.0.1
- Operating System / Platform =>Windows 10 64bit
- Compiler =>Visual Studio 2017

##### Detailed description

There is a bug in OpenCV dnn module, which the program is unable to start which including 
`#include <opencv2/dnn/dnn.hpp>`
when open `opencv2/dnn/dnn.hpp` file in IDE, it shows this error 

Even I tried the precompiled library which comes with OpenVINO Toolkit, also gives the same error.

> Lexical or pre-process issue
> error: untermintaded conditional directive

**Comment by alalek** [comment]
> opencv2/dnn/dnn.hpp

OpenCV modules should be included as `opencv2/<module>.hpp`. Other headers are advanced use, may require specific including order.

> Lexical or pre-process issue

Provide RAW compiler output (without IDE postprocessing - it lost important details), including file names, code lines. Source file (which includes dnn.hpp) can cause such errors.

**General rule**
For bugs complete minimal reproducer is required, including input data and provided output.
