### ISSUE TITLE
Can't read net from modified tensorflow faster rcnn model

### ISSUE THREAD

**Issue by alohec** [opencv/opencv#13633]
As the title states, when trying to use the readNetFromTensorflow command I receive this traceback: 

cv2.error: OpenCV(4.0.0) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:999: error: (-215:Assertion failed) values.type() == CV_32FC1 in function 'populateNet'

Commenters in Issue #11452 also mentioned seeing this same error but this specific error wasn't the reason for that particular issue so it was closed. I can share the frozen graph file if need be.

The frozen graph I'm passing was created using the standard tensorflow command line tool. And the pbtxt file was created using tf_text_graph_faster_rcnn.py. I trained using the Faster-RCNN ResNet-50 model config as a base with the following modifications:
min_dimension = 600
max_dimension = 600
scales = [0.10,0.25, 0.5, 1.0]
aspect_ratios = 1.0
width_stride = 8
height_stride = 8
num_classes = 2

I've tried  using opencv versions ranging from 3.4.3 to 4.0 with corresponding tf_text_graph_faster_rcnn.py and tf_text_graph_common.py files and in all cases the same error occurs.

**Comment by dkurt** [comment]
> I can share the frozen graph file if need be.

Yes, please share it and a config file or at least the same graph with randomly initialized weights. We need them to reproduce an issue.

**Comment by alohec** [comment]
@dkurt thank you for your response.

Here is a link to the frozen graph:
 https://drive.google.com/open?id=1e6VbKqgKTXN-5ODE1sM0SWr8qNGcb6oC

Here is the config file:
[model.config.zip](https://github.com/opencv/opencv/files/2765789/model.config.zip)

**Comment by dkurt** [comment]
Hmm, there are some entries that looks like dilated convolutions. Did you train this model from scratch with this config or some base network has been used?

your model:
![screenshot from 2019-01-17 12-27-57](https://user-images.githubusercontent.com/25801568/51308512-60ca7700-1a53-11e9-8c80-f72224421d33.png)

faster_rcnn_resnet50_coco_2018_01_28 (from Model Zoo):
![screenshot from 2019-01-17 12-29-47](https://user-images.githubusercontent.com/25801568/51308631-a0915e80-1a53-11e9-9333-9500790da81c.png)

**Comment by alohec** [comment]
I used the faster_rcnn_resnet50_coco_2018_01_28 weights as a fine tune checkpoint and made the aforementioned modifications to the example config file. So, I'm honestly not sure why my model differs from the standard version (the change in stride maybe?).

Are there some modifications I could make to the tf_text_graph_faster_rcnn.py to accommodate this difference?

**Comment by alohec** [comment]
FINAL UPDATE: 
After testing with my same pipeline but only with one hyperparameter change at a time I was able to find the source of the problem.

Conclusion: 
changing the feature stride length from 16 to 8 causes the error. Width and height stride can be changed but not feature stride.

I would call this bug as the code seems to imply the user can change the hyperparamteers to fit their use case, but I will close the issue as the source of the problem has been discovered.
