### ISSUE TITLE
Can the official give a concrete step of compiling cmake?

### ISSUE THREAD

**Issue by tianshaokai** [opencv/opencv#13647]
1.  I can't start compiling if I want to.
use -DBUILD_SHARED_LIBS=ON
use -DBUILD_opencv_java=OFF
2. How do the above two commands work?
3. Below is my compilation script, which has been unable to compile successfully.

cmake \ -DCMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake \ -OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.0.1/modules \ -DANDROID_NDK=/Users/xiaopeng/Android/android-ndk-r15c/ \-DCMAKE_BUILD_TYPE=Release  \ -DANDROID_ABI=armeabi-v7a \ -DANDROID_NATIVE_API_LEVEL=19 \ -DANDROID_STL=gnustl_shared ..

**Comment by alalek** [comment]
Try to add `-DBUILD_ANDROID_EXAMPLES=OFF` because normal java build is disabled.

Build / Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
