### ISSUE TITLE
Slowing down UMat.clone after GaussianBlur

### ISSUE THREAD

**Issue by Daniel-Alievsky** [opencv/opencv#13648]
Maybe you can consult me about the following issue. I have some matrix UMat 1024x1024. I process it by GaussianBlur for kernel KxK and then call clone() for resulting UMat.

On my computer (OpenCV 4.0.0), I see a very strange behavior. When K is little, the speed is high; cloning is performed in 1-2 ms. But when I increase K, then time of executing clone() call also increases! I understand increasing the time of GaussianBlur, but why the time of _further cloning_ also grows?

For K=111, the time of clone() method becomes 12 ms - greater than the time of GaussianBlur. What does it mean?

Below is a simple JavaCPP test, illustrating the situation:

```
public class SimpleGaussianPlusCloneSpeed {
    private static final int KERNEL_SIZE = 3;

    public static void main(String[] args) {
        System.out.println("OpenCL existence: " + opencv_core.haveOpenCL());
        System.out.println("OpenCL usage: " + opencv_core.useOpenCL());
        final opencv_core.Size ksize = new opencv_core.Size(KERNEL_SIZE, KERNEL_SIZE);
        for (int testCount = 0; testCount < 16; testCount++) {
            System.out.printf("%nTest #%d%n", testCount);
            final opencv_core.UMat m = new opencv_core.UMat(1024, 1024,
                    opencv_core.CV_8UC3, new opencv_core.Scalar(0.0, 0.0, 0.0, 0.0));
            final opencv_core.UMat result = new opencv_core.UMat();
            long t1 = System.nanoTime();
            opencv_imgproc.GaussianBlur(m, result, ksize, 0.0);
            long t2 = System.nanoTime();
            final opencv_core.UMat clone = m.clone();// - slows down while increasing KERNEL_SIZE
            long t3 = System.nanoTime();
            System.out.printf("GaussianBlur: %.3f ms%nclone: %.3f ms%n", (t2 - t1) * 1e-6, (t3 - t2) * 1e-6);
            clone.close();
            result.close();
            m.close();
        }
    }
}
```
With KERNEL_SIZE = 3, the test prints
...
Test #14
GaussianBlur: 5.588 ms
clone: 1.624 ms

Test #15
GaussianBlur: 5.607 ms
clone: 1.624 ms

With KERNEL_SIZE = 51:
Test #15
GaussianBlur: 7.795 ms
clone: 5.901 ms

With KERNEL_SIZE = 111:
Test #15
GaussianBlur: 10.145 ms
clone: 12.262 ms

And the same problem with simple blur() method. Moreover, if I clone the source "m" instead of "result", behavior is the same!
What does it mean? Any ideas?

**Comment by alalek** [comment]
> JavaCPP

It is not supported here (we don't have configured environment with it).

Original implementation (in C++) via UMat is asynchronous. OpenCV calls just put tasks into OpenCL queue. So, time measurement without OpenCL queue synchronization is wrong. Only "t3-t1" measuremen makes sense.

**Comment by Daniel-Alievsky** [comment]
Thank you!
