### ISSUE TITLE
when i change the `samples\dnn\mask_rcnn.py` a little to detect images in a directory，something wrong with`dnn\src\layers\detection_output_layer.cpp:706: error: (-215:Assertion failed) prior_height > 0 

### ISSUE THREAD

**Issue by yangsenius** [opencv/opencv#13643]
https://github.com/opencv/opencv/blob/2ea46269115c80ba5772676adc27a074f6ec4a97/modules/dnn/src/layers/detection_output_layer.cpp#L706

I make a little change in `samples\dnn\mask_rcnn.py` to detect person from images in a directory, something wrong happens in the process of the cycle.

At the beginning, the model works well and will output correct results. 

However, after some iteration, the model will not output any detection results and  the procedure is broken off with "cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\detection_output_layer.cpp:706: error: (-215:Assertion failed) prior_height > 0 in function 'cv::dnn::DetectionOutputLayerImpl::DecodeBBox'" errors

Do  i need to  change something about the code ??

Here it is! Thanks

```python
import cv2 as cv
import argparse
import numpy as np
import os
from pycocotools.coco import COCO
import time 

parser = argparse.ArgumentParser(description=
        'Use this script to run Mask-RCNN object detection and semantic '
        'segmentation network from TensorFlow Object Detection API.')

parser.add_argument('--input', help='Path to input image or video file. Skip this argument to capture frames from a camera.')
parser.add_argument('--model', required=True, help='Path to a .pb file with weights.')
parser.add_argument('--config', required=True, help='Path to a .pxtxt file contains network configuration.')
parser.add_argument('--classes', help='Optional path to a text file with names of classes.')
parser.add_argument('--colors', help='Optional path to a text file with colors for an every class. '
                                     'An every color is represented with three values from 0 to 255 in BGR channels order.')
parser.add_argument('--width', type=int, default=800,
                    help='Preprocess input image by resizing to a specific width.')
parser.add_argument('--height', type=int, default=800,
                    help='Preprocess input image by resizing to a specific height.')
parser.add_argument('--thr', type=float, default=0.5, help='Confidence threshold')
parser.add_argument('--ann', required=True, help='path to annotation file to get image name')


args = parser.parse_args()

np.random.seed(324)

# Load names of classes
classes = None
if args.classes:
    with open(args.classes, 'rt') as f:
        classes = f.read().rstrip('\n').split('\n')




# Load a network
net = cv.dnn.readNet(cv.samples.findFile(args.model), cv.samples.findFile(args.config))
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)


all_person_samples = []
dirname = args.input

coco=COCO( args.ann)   # train or val test


# get all image ids
index_to_image_id = coco.getImgIds()
print('total number of images',len(index_to_image_id))
for image_id in index_to_image_id:

    filename = '%012d.jpg' % image_id

    
    #print(filename)
    path = os.path.join(dirname,filename)
    if os.path.exists(path)==False:
        continue

    #frame = cv.imread( path )
    cap = cv.VideoCapture(cv.samples.findFileOrKeep(path))
    
    hasFrame, frame = cap.read()
    if not hasFrame:
        cv.waitKey()
        break
    print(path)
    #print(frame)
    
    print('image_id = ',image_id)

    frameH = frame.shape[0]
    frameW = frame.shape[1]

    # Create a 4D blob from a frame. size=(args.width, args.height)
    #blob = cv.dnn.blobFromImage(frame, size=(frameW,  frameH), swapRB=True, crop=False)
    blob = cv.dnn.blobFromImage(frame,size=(frameW,  frameH), swapRB=True, crop=False)
    # Run a model
    net.setInput(blob)

    boxes, masks = net.forward(['detection_out_final', 'detection_masks'])

    numClasses = masks.shape[1]
    numDetections = boxes.shape[2]

    time.sleep(2)
    
    t, _ = net.getPerfProfile()
    boxesToDraw = []
    for i in range(numDetections):
        box = boxes[0, 0, i]
        #print(box)
        classId = int(box[1])
        mask = masks[i]
        score = box[2]

        if score > args.thr and classes[classId]=='person':
            
            left = frameW * box[3]
            top = frameH * box[4]
            right = frameW * box[5]
            bottom = frameH * box[6]

            left = max(0, min(left, frameW - 1))
            top = max(0, min(top, frameH - 1))
            right = max(0, min(right, frameW - 1))
            bottom = max(0, min(bottom, frameH - 1))

            left = round(left,2)
            top = round(top,2)
            width = round(right-left,2)
            height = round(bottom-top,2)
            
            bbox =[left,top,width,height]
            category_id = 1

            person_sample = {
                'bbox' : bbox,
                'image_id': image_id,
                'score': float(score),
                'category_id':category_id,
            }

            print(person_sample)
            all_person_samples.append(person_sample)
```

**Comment by alalek** [comment]
What image is failed?

**Comment by yangsenius** [comment]
> 
> 
> What image is failed?

A very ordinary image . When i feed it alone to the model ， nothing was wrong.

**Comment by alalek** [comment]
Try OpenCV 4.0.1. OpenCV 4.0.0 is not latest release - some bug fixes are landed in next releases including fixing regressions.

Dump image dimensions.

If you want to fill bug report then please provide complete minimal reproducerm including inputs and expected outputs.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by yangsenius** [comment]
@alalek thank you very much. I will try OpenCV4.0.1 and give the feedback

**Comment by dkurt** [comment]
@yangsenius, this is an output I got for this image:
![out](https://user-images.githubusercontent.com/25801568/51476601-099c0d80-1d97-11e9-8a52-7b6da3c6a72b.jpg)

May I ask you to run OpenCV's sample without any changes with this image? Can you show the output of `print(blob.shape)` from your sample?

**Comment by dkurt** [comment]
BTW,
```python
frameH = frame.shape[0]
frameW = frame.shape[1]

blob = cv.dnn.blobFromImage(frame,size=(frameW,  frameH), swapRB=True, crop=False)
```
using frame's sizes is not completely right thing. TensorFlow network has resizing node inside that means it makes fixed shapes for any input. Why did you removed fixed input shapes?

**Comment by yangsenius** [comment]
I run the  OpenCV's sample without any changes with this image and i get the expected results. 
The output of `print(blob.shape)`  is `(1,3, 333, 500)` when 
``` python
blob = cv.dnn.blobFromImage(frame,size=(frameW,  frameH), swapRB=True, crop=False)
```
I change the blob size because i want to obtain the accurate bbox coordinate, but now i find the bug is just caused by this change ! You're right!

It seems that i must keep the fixed shape for any input and recalculate the coordinate. 
@dkurt

**Comment by yangsenius** [comment]
I feed this [image](http://images.cocodataset.org/val2017/000000142238.jpg) with shape = (427, 640, 3) and set  fixed input size with `cv.dnn.blobFromImage(frame, size=(800,800), swapRB=True, crop=False)` ,  then the same error `detection_output_layer.cpp:705: error: (-215:Assertion failed) prior_width > 0 in function 'cv::dnn::DetectionOutputLayerImpl::DecodeBBox'` happens again. 

But there is no bug when i set `cv.dnn.blobFromImage(frame, size=(frame.shape[1],frame.shape[0]), swapRB=True, crop=False)` ! 

Why?

**Comment by yangsenius** [comment]
I change the `size` to solve it

**Comment by sitisofiah** [comment]
i do have same error tried my custom model using tensorflow and try on mask rcnn opencv . Have tried with opencv 4.0.1 still same error ..
OpenCV(4.0.1) D:\Build\OpenCV\opencv-4.0.1\modules\dnn\src\layers\detection_output_layer.cpp:705: error: (-215:Assertion failed) prior_width > 0 in function 'cv::dnn::DetectionOutputLayerImpl::DecodeBBox'

**Comment by LeonardoRez** [comment]
I'm having the same issue. The default values are 800x800? Because I've been running it on different image sequences and it always gives this same error, even with different sequences... all images in the sequences have the same atributes, so I don't know why it would break after one or two hours doing the same steps...
