### ISSUE TITLE
OpenCV 4.0.0 contrib viz module

### ISSUE THREAD

**Issue by ShijianXu** [opencv/opencv#13659]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
I found that `viz` module has been included in the OpenCV 4.0.0 contrib. However, After I finish the compiling of OpenCV and contrib using CMake and regenerate the solution using VS2017, I can not find the `viz.hpp` in build/install. And I cannot include the `viz.hpp` head file in the project.

When I regenerate the solution, there was no error except one: **cannot open `python36_d.lib`**. Also there are some warnings like `This file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss`. But I thought this was not a concern.

I don't know whether it is a bug or just I made something wrong. Thanks a lot.

**Comment by ShijianXu** [comment]
In opencv_contrib-4.0.0, there is a viz module in it. I thought that would be enough for me to compile the viz. But do you mean that even there is viz in the contrib, I still need to download and compile the VTK? I am not very familiar with viz. 

For the python36_d.lib, I am not sure that I installed python with debug lib, I just installed with anaconda. But this will not effect the use of OpenCV, right?

Thanks a lot.

**Comment by LaurentBerger** [comment]
VTK is [necessary ](https://github.com/opencv/opencv_contrib/blob/master/modules/viz/CMakeLists.txt#L1-L3)
You will need Python36_d  to debug python code in C++. Do you want to debug python code in C++?

**Comment by ShijianXu** [comment]
I am sorry that I didn't check the makefile. I do not need to debug python code in C++.

For VTK, do I still need to use cmake to compile the source code or I can just use the binary installation? I thought if I still need to compile the source code there will be no meaning to include the viz in contrib. Could you please give me more guidance? 

Thank you very much.

**Comment by LaurentBerger** [comment]
For vtk I can only say that I use to compile source and install it and I give path to opencv in [cmake](https://gist.github.com/LaurentBerger/dd65f04b846a742c1457dbe5b1aa169d#file-gistfile1-txt-L21).
I think that Viz module is easier to use when you don't know vtk

**Comment by ShijianXu** [comment]
OK, I see. 
Thank you for your help. I think I can close the issue now.
