### ISSUE TITLE
Tab key disables arrow keys

### ISSUE THREAD

**Issue by tpmeyer1** [opencv/opencv#13657]
After imshow(), I use several keyboard keys (through waitKey() ) to manipulate the image.   In version 4.0.0, the tab key now disables the arrow keys.  That is, the arrow keys work fine, put then when I press TAB, the arrow keys stop working.

I noticed that in version 4.0.0, the window that pops up now has a header (with zoom pan buttons) and a footer (with cursor location info).

I suspect that the two issues may be related.   Maybe the TAB is getting consumed by the new functionality and it puts the window is a different state?   If I can't sort this out, I have a lot of code to rewrite.   If that is the culprit, is there anyway I can get rid of the header and footer?

OS:
```
uname -ra
Linux XPS 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Sample Code:
```
import cv2
import numpy as np

kp = -1
blank = np.zeros((704,1104,3),np.uint8)
cv2.imshow("Window",blank)

while kp != 27:
   kp = cv2.waitKeyEx(100)
   if kp != -1:
      print (kp)
```

**Comment by tpmeyer1** [comment]
Problem was I was using the QT GUI and didn't know it (or want it).   I'll compile source instead of using pip.

**Comment by thewoz** [comment]
Regarding the problem with the tab key what I understand is that the following function is no longer called
void CvWindow::keyPressEvent(QKeyEvent *evnt)

Reading the QT documentation what I find is as follows:
[keyPressEvent](https://doc.qt.io/qt-6/qwidget.html#keyPressEvent)() is called whenever a key is pressed, and again when a key has been held down long enough for it to auto-repeat. The Tab and Shift+Tab keys are only passed to the widget if they are not used by the focus-change mechanisms. To force those keys to be processed by your widget, you must reimplement [QWidget::event](https://doc.qt.io/qt-6/qwidget.html#event)().

So the only way to fix the problem would be to overload the bool function QWidget::event(QEvent *event)
