### ISSUE TITLE
type_c.h issue under windows

### ISSUE THREAD

**Issue by kawori** [opencv/opencv#13663]
##### System information (version)

- OpenCV => 2.4.13.6
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

When compiling my project using x86 config,  there were no errors.
When compiling using **x64** config, errors were all about _type_c.h_ in opencv.
It seems an issue about **<emmintrin.h>**, but I don't know what's wrong.
Error message:
![default](https://user-images.githubusercontent.com/11918823/51451244-5e2b9280-1d6f-11e9-9e13-c394786453f7.png)

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl-vc15/builds/333):
- MSVS 2017 (19.16.27023.1)
- CMake 3.12.4

**Comment by kawori** [comment]
Maybe it's my mistake of project configure or something others, and there are too many including factors. Let it solved in the future.
