### ISSUE TITLE
OPENCV_OCL4DNN_DISABLE_AUTO_TUNING 

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13680]
Auto-tuning of OpenCL kernels of OpenCV/DNN module is not working if that macro OPENCV_OCL4DNN_DISABLE_AUTO_TUNING is applied. How to force autotuning to on?

**Comment by alalek** [comment]
It is enough to use `OPENCV_OCL4DNN_CONFIG_PATH`.
OPENCV_OCL4DNN_DISABLE_AUTO_TUNING parameter can disable only
`OPENCV_OCL4DNN_FORCE_AUTO_TUNING` forces tuning re-run (ignores cached values on disk).

**Comment by peter197321** [comment]
how to use OPENCV_OCL4DNN_CONFIG_PATH ?

**Comment by alalek** [comment]
How you did apply OPENCV_OCL4DNN_DISABLE_AUTO_TUNING "macro"?
Currently parameters are passed via environment variables: "export" / "set" commands
