### ISSUE TITLE
opecv 4.0.1 clGetGLContextInfoKHR unresolved external on Windows 10 platform when linking with opencv_core400d.lib. OpenCL is from Intel and the extension is already there.

### ISSUE THREAD

**Issue by jsemeda** [opencv/opencv#13683]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by jsemeda** [comment]
System information (version) 
OpenCV => 4.0.0
Operating System / Platform => windows 10
Compiler => visual studio 2017
Detailed description
Steps to reproduce compile the opencv_annotation application in opencv

**Comment by alalek** [comment]
> Steps to reproduce compile the opencv_annotation application in opencv

Still incomplete (some required important detail is missing).

Successfully compiled and released here: https://github.com/opencv/opencv/releases
You can find our build details here: http://pullrequest.opencv.org/buildbot/builders/master_winpack_controller/builds/10683

**Comment by jsemeda** [comment]
I was compiling opencv 4.0.0 and not 4.0.1 .. it does work in the later. Thank you.
