### ISSUE TITLE
Is there an error in the distance point/plane computation?

### ISSUE THREAD

**Issue by lukkio88** [opencv/opencv#13688]
https://github.com/opencv/opencv/blob/287ee9d0eada120e0da5029206c5438682fe06da/samples/cpp/tutorial_code/features2D/Homography/homography_from_camera_displacement.cpp#L122

Hi,

I cannot write formulas.. but I came across the referenced lines and I was wondering if there's any mistake or redundancy when computing the distance between the origin of an estimated pose and the homography plane.

Shouldn't it be simply `inv_d = 1.0/tvec1.at<double>(0)`?

I might be wrong but I did some computations and it seems to me the formula you've implemented doesn't look right.

Can you confirm or disprove?

Just to clarify what's my understanding of your code, you perform reference frame transformation between the plane reference frame and the pose reference frame and then you compute the distance, which in theory is correct because the metric doesn't change. However you can compute such distance just by getting the projection of the origin of the camera pose in the `xy` plane. I can see why you compute `R1*origin + T` (although since `origin = (0,0,0)` the rotation doesn't actually contribute...). This is still a point in the plane reference frame, you later perform a rotation of the normal (by doing `normal1 = R1*normal`), this bit doesn't seem necessary to me if you just use the `z` coordinate of `tvec1`.

Am I missing anything here?

**Comment by lukkio88** [comment]
Can anyone please reply?

**Comment by catree** [comment]
> Shouldn't it be simply inv_d = 1.0/tvec1.at<double>(0)?

![image](https://user-images.githubusercontent.com/8229425/52172944-7d1c2280-277a-11e9-959c-681a102e5a7f.png)

`d` is the [distance from point to plane](https://mathinsight.org/distance_point_plane). `tz` or `tvec1.at<double>(2)` is the distance in the z-axis camera frame from the camera origin to the plane origin.
The origin of the plane can be anywhere on the plane but `d` is the shortest distance between the camera frame and the plane (the point-to-plane distance). `tz` is usually different from `d` (one case where `tz` is always equal to `d` is when the plane is parallel to the camera plane).

**Comment by LaurentBerger** [comment]
may be it should be 

                  d is the distance from optical center to plane

**Comment by lukkio88** [comment]
> > Shouldn't it be simply inv_d = 1.0/tvec1.at(0)?
> 
> ![image](https://user-images.githubusercontent.com/8229425/52172944-7d1c2280-277a-11e9-959c-681a102e5a7f.png)
> 
> `d` is the [distance from point to plane](https://mathinsight.org/distance_point_plane). `tz` or `tvec1.at<double>(2)` is the distance in the z-axis camera frame from the camera origin to the plane origin.
> The origin of the plane can be anywhere on the plane but `d` is the shortest distance between the camera frame and the plane (the point-to-plane distance). `tz` is usually different from `d` (one case where `tz` is always equal to `d` is when the plane is parallel to the camera plane).

I agree 'd'  is in general different from 'tz', however since 'tz'  is a coordinate expressed wrt the plane reference frame they should be the same.

**Comment by lukkio88** [comment]
> may be it should be
> 
> ```
>               d is the distance from principal point to plane 
> ```

It doesn't seem to me the principal point is used at all.

**Comment by catree** [comment]
It is not directly `tvec1.at<double>(2)` but `(-R1.t() * tvec1).at<double>(2)` that is equal to `d` or to `normal1.dot(origin1)` **but solely because we have defined the chessboard frame this way**:

![image](https://user-images.githubusercontent.com/8229425/52180594-9d82c600-27e8-11e9-8e81-3d92a1d3c25a.png)

This can be seen also with how the plane normal is defined:
```
Mat normal = (Mat_<double>(3,1) << 0, 0, 1);
```

`normal1.dot(origin1)` is the **general formula** to compute the [point-to plane distance](https://mathinsight.org/distance_point_plane).

---

```
Mat origin(3, 1, CV_64FC1, Scalar(0));
Mat origin1 = R1*origin + tvec1;
```

Indeed `R1` could be omitted. **But** the formula works for any points on the plane.
This works also and will produce the same result:

```
Mat origin= (Mat_<double>(3,1) << 0.5, 17, 0);
Mat origin1 = R1*origin + tvec1;
```

---

> d is the distance from principal point to plane 

For me principal point is really the coordinate in pixel in the image.

A better formulation could be:

> d is the point-to-plane distance between the camera frame origin and the plane.

**Comment by lukkio88** [comment]
I think I need to expound a little bit:

**What do I think is correct?**

I agree with all the formula used, the quantities are still source of confusion though. The code estimates a pose `(r_vec1,t_vec1)` w.r.t. the checkerboard reference frame. What we want to find, please correct me if I'm wrong, is the distance between the origin `t_vec1` of the camera from the plane containing the checkerboard.

Such distance can be computed in any reference frame, as long as the transformation is an isometry, such as pose transformation, or the identity. Now if we use the checkerboard reference frame the problem is equivalent to find the distance between the `xy` plane containing the checkerboard and the camera origin `t_vec1`. 

Such distance can be computed using the formula you're saying simply using the `normal = (0,0,1)`, which represents the checkerboard plane normal wrt the checkerboard reference frame and the vector `t_vec1`, whose coordinates are represented already in the checkerboard reference frame.

Putting these together we have the formula `normal.dot(t_vec1)`, but this would trivially return `t_vec1.at<double>(2)` as result.

The question at this point is... am I right?

**Why am I confused?**

In the code I see the `t_vec1` which should what I tried to explain in the previous paragraph, please correct me if I'm wrong. But if this is the case why there's a rotation of the `normal` that produces `normal1` as well?

I understand any point _in the plane_ won't change the result, but rotating the normal of the plane will.

**Comment by catree** [comment]
In the tutorial code, we have:
```
R = Rodrigues(rvec1)
X_cam = (R1 | tvec1) X_plane
```
The point-to-plane distance is computed in the camera frame. So you have to transform the plane normal in the camera frame and transform a point in the plane (for instance the origin) also in the camera frame.

Of course, you can do the same thing in the plane frame but you have to invert `tvec1` as I have written above: `(-R1.t() * tvec1)` since `rvec1` and `tvec1` transform a point expressed in the plane frame to the camera frame and you want now the reverse.

**Comment by lukkio88** [comment]
I don't understand why w.r.t. to the plane we would need to compute `-R1.t() * tvec1`, isn't `tvec1` already expressed in the plane reference frame?

I think that in the camera frame you want to apply `-R1.t() * tvec1` as transformation.
May I please ask in what reference frame is `tvec1` given? I.e. what does

`    solvePnP(objectPoints, corners1, cameraMatrix, distCoeffs, rvec1, tvec1);`

give as `tvec1`?

**Comment by lukkio88** [comment]
And just to clarify to me all the following are correct to compute the distance assuming, `tvec1` is the result I understood `solvePnP` returns, `R = Rodrigues(rvec1)`, `plane_normal = (_Mat<double>() << 0.0, 0.0, 1.0)`

`tvec1.dot(plane_normal) = (-R.t()*tvec1).dot(-R.t()*plane_normal) = (R.t()*tvec_1).dot(R.t()*plane_normal)`.

Again all of this assuming that `plane_normal` and `tvec1` are in the plane reference frame.

**Comment by lukkio88** [comment]
Ok, I read again through the tutorial.
Basically solvePnP returns `rvec` and `tvec` that transform a point in world coordinates in camera coordinates, so these are the inverse of what I thought.

So the discussion I think is solved if I keep in mind that `tvec1` is in camera reference frame while the `normal = 0,0,1` is in the plane reference frame. So in order to compute the distance point plane either we transform `tvec1` and keep the normal or we keep `tvec1` and transform the normal.

The latter is what the example does.

I think is ok now, my apologies for keeping this long.
