### ISSUE TITLE
Problem with cv2.drawKeypoints

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#13689]
Hi, 

It seems that  some users have got some problem with drawKeypoints (http://answers.opencv.org/question/206950/function-drawkeypoints-do-not-work-in-opencv-401/ and  http://answers.opencv.org/question/207758/drawkeypoints-bug/) using this code
```
import cv2
import numpy as np

def draw_keypoints(vis, keypoints, color = (0, 255, 255)):
    for kp in keypoints:
        x, y = kp.pt
        cv2.circle(vis, (int(x), int(y), 2, color))

input_image = cv2.imread('lena.jpg')
if input_image is None:
    print("check file path")
    exit()
gray_image = cv2.cvtColor(input_image, cv2.COLOR_BGR2GRAY)

orb = cv2.ORB_create()

keypoints = orb.detect(gray_image, None)

keypoints, descriptor = orb.compute(gray_image, keypoints)

t= cv2.drawKeypoints(input_image, keypoints, outImage=input_image, color=(0,255,0),
                          flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('ORB keypoints', input_image)
cv2.waitKey()
```

Error is  AttributeError: module 'cv2.cv2' has no attribute 'drawKeypoints'

If i use my own version opencv-python  there is no problem. Something is wrong but what ?

duplicate issue : https://github.com/skvark/opencv-python/issues/168

and may be https://github.com/opencv/opencv/issues/10250

system windows 10 msvc 2017 python 3.6.6

**Comment by alalek** [comment]
> 4.0.1-openvino

Doesn't contain commit with related bindings fix: https://github.com/opencv/opencv/commit/c8f934b5b196c7b11e744f05049f2d3146fed7b2
Need to wait for next release.

**Comment by idow09** [comment]
Hi! I encounter the same issue.
When will be the next release?
And in the meantime, what version should I use instead (until the fix is released)?

**Comment by paapu88** [comment]
Hi! I encounter the same issue.
When will be the next release?
And in the meantime, what version should I use instead (until the fix is released)?

**Comment by LaurentBerger** [comment]
@idow09  @paapu88 problem is solved in opencv. There is problem in mac build https://github.com/skvark/opencv-python/issues/168#issuecomment-460696459

**Comment by paapu88** [comment]
Ok, with downgrading:
> Successfully installed opencv-python-3.4.5.20
I can run:

img2 = cv2.drawKeypoints(srcGray, kp, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imwrite('fast_true.png', img2)

Terveisin, Markus
