### ISSUE TITLE
cv::cuda::Filter in multiple cuda streams/threads writes to same memory -- corrupted output

### ISSUE THREAD

**Issue by flyingfalling** [opencv/opencv#13681]
##### System information (version)
- OpenCV => 3.4 (tried on opencv 3.4.3 and opencv 4.0.1)
- Operating System / Platform => Linux 64 bit (debian based -- ubunut, kubuntu, xubuntu, also tried on arch linux)
- Compiler => gcc-6 g++6

##### Detailed description

This seems to be a similar issue to #6742

If two CUDA streams in two different threads try to simultaneously use apply() to a cv::cuda::Filter created via e.g.  (for doing edge detection with gabor filters):
auto filtptr = cv::cuda::createLinearFilter( CV_32FC1, CV_32FC1, cv::getGaborKernel(cv::Size(ksize_pix, ksize_pix), sig_pix, th, lm_pix, gamma, psi) );

Then it results in corrupted output in one or both of the outputs.

##### Steps to reproduce

See example code in #6742, but this bug behaviour occurs if the filter is a createLinearFilter as well.

**Comment by alalek** [comment]
Classes in OpenCV are not threads safe and there is not plan to do that. Use separate own/cloned objects from different threads simultaneously.
Only storage containers cv::Mat/GpuMat/UMat are thread safe (in memory management scope, data race is still possible).

if it is CUDA-specific issue, then we should track this in #6742 instead.

**Comment by flyingfalling** [comment]
To make it clear, this is *different* filter objects. They are not the same filter object.

**Comment by flyingfalling** [comment]
This is CUDA specific. It works fine in normal filters, only with cuda filters does it corrupt. Everything works if all are run in sequence even under CUDA filters.

**Comment by flyingfalling** [comment]
@alalek  In that case, should we add information to #6742 that this occurs with filters created with createLinearFilter, not just with his example of createGaussianFilter?

**Comment by flyingfalling** [comment]
Furthermore it does not seem to be fixed even as of version 4.0.1
