### ISSUE TITLE
dnn

### ISSUE THREAD

**Issue by simmonchan** [opencv/opencv#13704]
CV_Assert((numPriors * _numLocClasses * 4) == total(inputs[0], 1));
what's the meaning?

**Comment by dkurt** [comment]
@simmonchan, this is an internal assertion that indicates unexpected model usage. Please provide a reproducer and specify version of OpenCV as mentioned in issue's template.

**Comment by dkurt** [comment]
@simmonchan, Please make it fully reproducible providing reference to model and code sample which run it.

This is a bug tracker and there are guidelines to report a bug.
