### ISSUE TITLE
Error logical function (B = A > 0)

### ISSUE THREAD

**Issue by rc-38** [opencv/opencv#13706]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => CodeBlocks (GNU GCC Compiler)

##### Detailed description
I am using OpenCV 4.0.1 and I have an issue with a simple logical operation:

    Mat A = Mat::zeros(1000000, 1, CV_8UC1);
    Mat B = (A > 0);
    int C = countNonZero(B);

It outputs the correct answer "C = 0". But if I switch rows and columns in A: 

    Mat A = Mat::zeros(1, 1000000, CV_8UC1);
    Mat B = (A > 0);
    int C = countNonZero(B);

I get "C = 524288". What could possibly go wrong? I am desperate.

**Comment by dkurt** [comment]
@rc-38, Cannot reproduce it with OpenCV from master branch (fcec053d59a8e30cbac7db571fcd448bfc98dd53) and g++ 5.4.0 (Ubuntu 16.04). Please add more details about compiler and OpenCV configuration.
