### ISSUE TITLE
Android requires native code 64 bit (starting August 1, 2019)

### ISSUE THREAD

**Issue by hannesa2** [opencv/opencv#13712]
Starting August 1, 2019, all new Android apps and app updates that include native code are required to provide 64-bit versions, in addition to 32-bit versions, when publishing to Google Play.
https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

### Question A
Sorry, I'm not that NDK specialist to be able to verify if all 64-bit is provided by OpenCV.
I found following provided by OpenCV. So far it looks good to me, **but please confirm**

  | 
-- |
arm64-v8a
armeabi
armeabi-v7a
mips
mips64
x86 
x86_64 

### Question B
Is OpenCV build able by most recent NDK 19 ?

**Comment by alalek** [comment]
Q1: mips are gone from modern Android NDKs. `armeabi` is dropped (ARMv5) from OpenCV (by default) - see `ndk-18.config.py`.
Q2: OpenCV team using NDK 18b at this moment. No information about NDK 19.

**Comment by bommo1** [comment]
When built with NDK 19 OpenCV crashes in cv::warpAffine() and cv::warpPerspective() but only on **armv7**.
See also https://github.com/opencv/opencv/issues/13676.

**Comment by alalek** [comment]
@boomo1 It is always useful to add minimal details with observed error messages.
At least for others users who searching for similar problems or can suggest something without trying to reproduce whole build environment.

**Comment by bommo1** [comment]
signal 7 (SIGBUS), code 1 (BUS_ADRALN)

I'll test also with NDK 20 beta and file a new issue.

**Comment by bommo1** [comment]
https://github.com/opencv/opencv/issues/14265
