### ISSUE TITLE
OPENCV_OPENCL_PROGRAM_CACHE use

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13717]
OCV has another CACHE environment variable, when set, there is a run-time error. Based on the log, it looks like Caching is not working in the DNN.

OPENCV_OPENCL_PROGRAM_CACHE=/home/root/

OpenCV(3.4.1) Error: Bad argument (Invalid value for OPENCV_OPENCL_PROGRAM_CACHE parameter: /home/root/) in getConfigurationParameterSizeT, file /home/root/opencv/modules/core/src/system.cpp, line 1600

terminate called after throwing an instance of 'cv::Exception'

  what():  OpenCV(3.4.1) /home/root/opencv/modules/core/src/system.cpp:1600: error: (-5) Invalid value for OPENCV_OPENCL_PROGRAM_CACHE parameter: /home/root/ in function getConfigurationParameterSizeT

What OPENCV_OPENCL_PROGRAM_CACHE is for and how to properly set?

**Comment by alalek** [comment]
@peter197321 Please stop issues [spam](https://github.com/opencv/opencv/issues?q=is%3Aissue+author%3Apeter197321+).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

If you really want to fill issue here, then you should fill provided template.
