### ISSUE TITLE
NC_OUT_OF_MEMORY in function 'initPlugin'

### ISSUE THREAD

**Issue by louisZL** [opencv/opencv#13715]
There are some errors when the backend is setted VPU:

E: [ncAPI] [    934946] ncGraphAllocate:1348	The graph file is bigger than the device memory
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:553: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Failed to allocate graph: NC_OUT_OF_MEMORY in function 'initPlugin'

**Comment by dkurt** [comment]
@louisZL, Could you provide a reproducer please or at least specify which model is used?

**Comment by louisZL** [comment]
@dkurt I installed OpenVINO R5.445 today, and my code run multi models at the same time (https://github.com/opencv/open_model_zoo/blob/2018/intel_models/index.md), like face-detection-adas-0001, person-detection-retail-0013, emotions-recognition-retail-0003 and facenet. When I run single model, it's ok.

**Comment by dkurt** [comment]
@louisZL, And what is facenet? How much in bytes it takes?

**Comment by louisZL** [comment]
@dkurt facenet is one face recognition model (https://github.com/davidsandberg/facenet), I use the OpenVINO model optimizer to transfer tf model. The .bin file size is about 46.9MB

**Comment by louisZL** [comment]
@dkurt But when I use facenet model single, it's ok.

**Comment by dkurt** [comment]
@ louisZL, Got it, thank you. Still could you please share some reference to facenet model? At least one with randomly initialized weights. And minimal code example would be also nice.

**Comment by louisZL** [comment]
@dkurt I my code, I use two sub-thread, thread1 is for face detection, I use face-detection-adas-0001 model first, when I get the face rect, I use facenet to do recognition; thread2 is for person detection, I use person-detection-retail-0013 model. When I close each one thread, it runs ok. When I run two thread, got these errors.

And when I use CPU not VPU as the backend, two thread is ok.

**Comment by dkurt** [comment]
> @dkurt I my code, I use two sub-thread, thread1 is for face detection, I use face-detection-adas-0001 model first, when I get the face rect, I use facenet to do recognition; thread2 is for person detection, I use person-detection-retail-0013 model.
> 
> When I close either one thread, it runs ok. When I run two thread, got these errors.
> 
> And when I use CPU not VPU as the backend, two thread is ok.

@louisZL, That's better than nothing but it'll take some time for me to write the code by this definition :smile: 

Is there some example so we can just copy it and run locally?

**Comment by louisZL** [comment]
@dkurt Thanks. and you can use my github code (edge-cv) to run.

**Comment by dkurt** [comment]
@louisZL, it's just a brief guess but try to run all the models once and only then start multiple threads. To initialize them.

**Comment by louisZL** [comment]
@dkurt Thank you. I'm not sure but I found that opencv load the model when the first net.forward() be called, and the first forward() costs more time. And when multi models are loaded at the same time (multiple threads), it will return 'NC_OUT_OF_MEMORY in function 'initPlugin'' error.

When multiple models are loaded not at the same time, it runs ok.

**Comment by dkurt** [comment]
Great, thank you for experiment! We'll fix it.

**Comment by dkurt** [comment]
@louisZL, please test the changes from https://github.com/opencv/opencv/pull/13738.
