### ISSUE TITLE
LUT3D() implementation not available

### ISSUE THREAD

**Issue by bonfiley** [opencv/opencv#13713]
The documentation here mentions LUT3D() but its implementation is not available in the latest code base.
https://docs.opencv.org/4.0.1/d6/d91/group__gapi__transform.html

**Comment by dmatveev** [comment]
Thanks for noticing! Seems the API was introduced, but the kernel itself was dropped from the plan.
Will remove the API entry.

**Comment by dmatveev** [comment]
We just dropped this kernel from the API (no plan to implement it so far - an artifact) so the issue now can be closed. Thanks!
