### ISSUE TITLE
DNN Compilation VS2017 error C2398: conversion requires a narrowing conversion

### ISSUE THREAD

**Issue by lorenzolightsgdwarf** [opencv/opencv#13714]
##### System information (version)

- OpenCV => 4.0.1, master branch e2dbf054ac5c54bd328f648d9d6146c09dfd5484
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

The compilation of the DNN module fails with several error C2398, e.g. due to the narrowing at line 106 in op_inf_engine.cpp
   netBuilder.connect(inpId, {layerId, i}); 
possible fix  
   netBuilder.connect(inpId, { static_cast<InferenceEngine::idx_t>(layerId), static_cast<InferenceEngine::idx_t>(i)});

Affected files are
- convolution_layer.cpp
- pooling_layer.cpp
- op_inf_engine.cpp

**Comment by dkurt** [comment]
@lorenzolightsgdwarf, You're right, thank you! Already fixed in https://github.com/opencv/opencv/pull/13692 :smile:

**Comment by lorenzolightsgdwarf** [comment]
Thanks!

**Comment by dkurt** [comment]
The fix must be merged into master branch this week.
