### ISSUE TITLE
Load Keras custom model with opencv dnn

### ISSUE THREAD

**Issue by WendelHime** [opencv/opencv#13728]
##### System information (version)

- OpenCV => 3.4.2.17 or 4.0.0
- Operating System / Platform => Elementary OS x64 (derivated from Ubuntu)
- Compiler => Python 3 or Golang

##### Detailed description

I'm trying to load a custom model from Keras (which I've converted to tensorflow) using `cv2.dnn.readNetFromTensorflow('saved_model.pb', 'saved_model.pbtxt')` (on python) and `gocv.ReadNetFromTensorflow("saved_model.pb")` (on golang) and it throws the following exception

python:
```
[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/wire_format_lite.cc:629] String field 'tensorflow.FunctionDef.Node.ret' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:44: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: saved_model.pb in function 'ReadTFNetParamsFromBinaryFileOrDie'
```

go:
```
[libprotobuf ERROR /tmp/opencv/opencv-4.0.0/3rdparty/protobuf/src/google/protobuf/wire_format_lite.cc:629] String field 'opencv_tensorflow.FunctionDef.Node.ret' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0) /tmp/opencv/opencv-4.0.0/modules/dnn/src/tensorflow/tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: /home/wotan/Downloads/saved_model.pb in function 'ReadTFNetParamsFromBinaryFileOrDie'
```

##### Steps to reproduce
python:
 ```python3
import cv2

net = cv2.dnn.readNetFromTensorflow('saved_model.pb', 'saved_model.pbtxt')
 ```
go:
```go
import "gocv.io/x/gocv"

func main() {
  var net := gocv.ReadNetFromTensorflow("saved_model.pb")
}
```

**Comment by dkurt** [comment]
@WendelHime, There is something wrong with you `saved_model.pb` file according error message. Check if it's valid.

**Comment by WendelHime** [comment]
Thanks @dkurt , it was something wrong with the model. I've followed [this tutorial](https://towardsdatascience.com/freezing-a-keras-model-c2e26cb84a38) to convert keras model to a freezed graphdef. I didn't test but now it's working when I try to load

**Comment by ibrahimLearning** [comment]
@WendelHime 
have you solved your problem? I have the same problem. Is there any suggestion please?

**Comment by WendelHime** [comment]
Hi @ibrahimLearning, I've freezed the model following [this tutorial](https://towardsdatascience.com/freezing-a-keras-model-c2e26cb84a38). Currently it works on every model that I made with keras

**Comment by ibrahimLearning** [comment]
@WendelHime 
Thank you so much for your commend. I am also try the tutorial. 
I would like to touch with during  conversion of the model.
Thanks

**Comment by Gilf641** [comment]
Actually I can't figure out how to load a pre-trained Keras Model(FaceRecognition) with OpenCV. The thing is that I want to use this model on IOT and Android Devices, so I'd to convert the same to tflite version. Can anyone help me out here? And I'm using TF 2.1, so...
