### ISSUE TITLE
Converting ssd_resnet50_v1_fpn from tensorflow fails

### ISSUE THREAD

**Issue by cwecht** [opencv/opencv#13725]
##### System information (version)
- OpenCV => 4.0.1 (master-branch)
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC 5.5

##### Detailed description

Because #13614 has been merged, I tried to apply  `tf_text_graph_ssd.py` to [ssd_resnet_50_fpn_coco](http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz).
This attempt fails with the following error:

Traceback (most recent call last):
  File "./tf_text_graph_ssd.py", line 366, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "./tf_text_graph_ssd.py", line 219, in createSSDGraph
    fuse_nodes(nodesToKeep)
  File "./tf_text_graph_ssd.py", line 204, in fuse_nodes
    out_height = int(out_height_node.attr['value']['tensor'][0]['int_val'][0])
KeyError: 'value'

**Comment by advanpix** [comment]
I can confirm that conversion of this SSD model also fails on Windows 10 / OpenCV 4.0.1 (release) but with different error message: 

```
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 276, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 30, in createSSDGraph
    ssd_anchor_generator = config['anchor_generator'][0]['ssd_anchor_generator'][0]
KeyError: 'ssd_anchor_generator'
```

**Comment by dkurt** [comment]
Thank you guys! Please check https://github.com/opencv/opencv/pull/13735 for necessary changes.

**Comment by advanpix** [comment]
Thank you for quick fix!

**Comment by advanpix** [comment]
When these changes will make it to the master branch (yet better to next OpenCV 4.X release)?

**Comment by advanpix** [comment]
Well, you are super quick! Will wait for merge, thank you again.

**Comment by advanpix** [comment]
I have compiled OpenCV with all the fixes above. Now everything work perfectly. Thank you very much!

**Comment by dkurt** [comment]
@advanpix, There are only changes in python script. It was not necessary to recompile a library. But anyway thank you!

**Comment by advanpix** [comment]
Yes, I know. But before I used official release 4.0.1 (December 22).
Decided to switch to master branch which has been updated with many improvements since then.
