### ISSUE TITLE
How to Integrate Arm Compute Library with OpenCV?

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13739]
Is there a standard way to interface OpenCV with ACL? I'm trying to understand if there was any effort on interfacing OpenCV with ACL.

**Comment by alalek** [comment]
[OpenCV HAL](https://docs.opencv.org/3.4.5/d6/d19/namespacecv_1_1hal.html) (low level CPU-based functions and classes).

Take a look on "carotene" ARM optimization: https://github.com/opencv/opencv/tree/3.4.5/3rdparty/carotene

**Comment by peter197321** [comment]
what's the suggestion though to reuse it somehow or to be done in similar way for ARM Compute Library aka [carotene](https://github.com/opencv/opencv/tree/3.4.5/3rdparty/carotene)?
Does [carotene](https://github.com/opencv/opencv/tree/3.4.5/3rdparty/carotene) work for OpenCV 4.0.1. as well?

**Comment by mshabunin** [comment]
Yes, Carotene library will be automatically enabled on ARM platforms.

Please take a look at the example: https://github.com/opencv/opencv/tree/master/samples/hal

**Comment by mshabunin** [comment]
Yes, you need to wrap ACL calls to match internal HAL interface ([define macros](https://github.com/opencv/opencv/blob/master/modules/core/src/hal_replacement.hpp)). And create cmake script with several variables to be used by OpenCV (like in examples).

For some functionality you will need to create new HAL entry points and interfaces (like [this](https://github.com/opencv/opencv/blob/50bec53afcf010e425b3f015c71297d46ef78903/modules/core/src/split.cpp#L172)).

**Comment by julled** [comment]
i found a way to import / export acl images in opencv : https://github.com/ARM-software/ComputeLibrary/issues/662
