### ISSUE TITLE
Performance regression in dnn of OpenCV4

### ISSUE THREAD

**Issue by a2bc** [opencv/opencv#13732]
##### System information (version)

- OpenCV => 3.4.3 and 4.0.1
- Operating System / Platform =>Snapdragon 845
- Compiler => Android NDK 18.1.5063045

##### Detailed description

I have a face recognition algorithm running on snapdragon 845 platform. This code was compiled by using the official release OpenCV 3.4.3 Android package (see here https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.4.3/opencv-3.4.3-android-sdk.zip/download). It takes around **500ms** to recognize a face.
I don't specify any PreferableTarget and PreferableBackend then I guess by default, the code runs on CPU of snapdragon 845.

Today, I upgrade to OpenCV 4.0.1 (the official Android package can be found here https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download). I don't change anything in my Android studio. In low level of my C++ code, I have to change only an enum from CV_YUV2RGB_NV21 to cv::COLOR_YUV2RGB_NV21. (I think this change cannot be the cause of the problem). Now, it takes around **650ms** to recognize a face.

Bref: the same Android studio configuration, the same NDK, 99% the same code, the same tested platform but there is a huge regression in terms of processing time between OpenCV 3.4.3 and OpenCV 4.0.1 !!

The network that I use to do face recognition is ArcFace (see here https://github.com/deepinsight/insightface). The authors provide a trained network under Caffe form.

Does anyone observe similar regression ?
Thanks

**Comment by dkurt** [comment]
@a2bc, Let's investigate it. Can you please create separate timers for different parts of your pipeline so we can find if it's really regression in dnn forward or another functions.

**Comment by nicolaerosia** [comment]
@a2bc a bit offtopic, try setting the number of threads to the number of BIG cores that you have
```
    ERR_LOG("cv::getNumThreads: %d", cv::getNumThreads());
    cv::setNumThreads(4);
    ERR_LOG("cv::getNumThreads: %d", cv::getNumThreads());
```

this brought me a big speedup.

**Comment by a2bc** [comment]
@dkurt : 
My use case: I have a list of registered faces. For a given input face, I have to compare it to the list to see if this person is in the list or not. If yes, return his name. For now, my list has only 5 persons. And for the registration list, I save feature (vector of 512 value) (not the face crop image...). These features are loaded only once when the program is launched.

Input image size in my case is 640 x 480, 3 channels.

The workflow in my code is as follows:
1. Convert YUV to RGB (have to do that because Android CameraAPI 2 provides buffer under YUV format)
2. Face detection
   2.1. Compute blob (called cv::dnn::blobFromImage). (blob size 128 x 96, RGB)
   2.2. Do face detection
3. Face recognition (for each detected face bounding box)
   3.1. Compute blob. Its size is 112 x 112, in RGB
   3.2. Compute feature (vector of 512 values) by feed forwarding through the face_recognized_network
4. Compute the score (similarity) between the obtained feature and all other features in the registration list (5 in my cases). Pick the highest score. If it is higher than a predefined threshold, we take the name of the person in the registration list.

So, the 500ms (with OpenCV 3.4.3) and 650ms (with OpenCV 4.0.1) are measured for all these 4 steps above (and there is only 1 face presented in the input image)

If my code, if there is no face detected, I skip step 3 and 4. In this case, I see that the computational time is: ~ 25ms for OpenCV 3.4.3; ~ 30 ms for OpenCV 4.0.1. (Not really clear if there is a regression at this state)

Before I already did a bench march of the step 4 and it is really small compared to the whole process.

Then I have a doubt on the step 3: Face recognition, in particular the step 3.2: feed forward through the face recognition network.
To check that, I hack my code so that instead of doing this feed forward, I directly allocate the feature of 512 values (all values = 0). Then note that I only change the step 3.2, all other steps are unchanged.

The computational time that I get is close to the case of no-face-detection: ~ 25ms for OpenCV 3.4.3 and ~ 30ms for OpenCV 4.01. (So the step 3.1 and step 4 are minor).

All that to say the performance regression mainly resides on the step 3.2: feed forward through the face recognition network !!!

If you want this network, I can upload somewhere and send you the link.

Thanks.

Bao

**Comment by dkurt** [comment]
@a2bc, You have two networks - face detection which detects faces and face recognition which creates embedding vectors for faces. Please measure their performance separately and report the numbers.

**Comment by a2bc** [comment]
@dkurt 

Face detection: ~ 25ms (OpenCV 3.4.3); ~30ms (OpenCV4.0.1)
Face recognition: ~ 475ms (OpenCV 3.4.3); ~ 620ms (OpenCV 4.0.1)

(The network backbone of face recognition is much more complicated & deeper than face detection)

**Comment by dkurt** [comment]
@a2bc, May I ask you to check that you pass the same input blob resolution to face recognition network every forward pass?

**Comment by alalek** [comment]
@a2bc Could you add dumps of cv::getBuildInformation() (to compare them and used flags)? (should be available via `adb logcat` logs)

**Comment by a2bc** [comment]
@dkurt 

My code is as follows:

cv::Mat ExtractVecFromFace(const cv::Mat& face)
{
	constexpr double faceRecogScaling = 1.0 / 255.0;
	constexpr int faceRecogWidth = 112;
	constexpr int faceRecogHeight = 112;
	const cv::Scalar faceRecogMean(127.5, 127.5, 127.5);
	const cv::Mat blob = cv::dnn::blobFromImage(face, faceRecogScaling, {faceRecogWidth, faceRecogHeight}, faceRecogMean, true, false);
	faceRecognitionNetwork->setInput(blob);
	vec = faceRecognitionNetwork->forward();
	const double norm = cv::norm(vec);
	return vec / norm;
}

for each face crop, I call this function to get the embedding. So I'm sure 100% that the blob size is always 112 x 112.

**Comment by a2bc** [comment]
@alalek 

Here is what I get in my logcat when using cv::getBuildInformation()

============
OpenCV3.4.3:

     Version control:               3.4.3    
      Platform:
        Timestamp:                   2018-08-29T10:28:48Z
        Host:                        Linux 4.15.0-33-generic x86_64
        Target:                      Linux 1 aarch64
        CMake:                       2.8.12.2
        CMake generator:             Ninja
        CMake build tool:            /usr/bin/ninja
        Configuration:               Release
    
      CPU/HW features:
        Baseline:                    NEON
          requested:                 NEON FP16
          required:                  NEON
          disabled:                  VFPV3
    
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ (ver 4.9)
        C++ flags (Release):         -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -f

==========

OpenCV4.0.1:

      Version control:               4.0.1    
      Platform:
        Timestamp:                   2018-12-22T07:41:15Z
        Host:                        Linux 4.15.0-42-generic x86_64
        Target:                      Android 1 aarch64
        CMake:                       3.6.0-rc2
        CMake generator:             Ninja
        CMake build tool:            /opt/android/android-sdk.gradle/cmake/3.6.4111459/bin/ninja
        Configuration:               Release
    
      CPU/HW features:
        Baseline:                    NEON FP16
    
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  (ver 7.0)
        C++ flags (Release):         -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -f

=========

And recall that I don't compile these opencv android libs, I download from your official releases (https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.4.3/opencv-3.4.3-android-sdk.zip/download and https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download)

Another information: before, I already tried to compile opencv android 3.4.3 libs (of course from the 3.4.3 code source). However, my compiled lib has a huge regression (2 times) as the official 3.4.3 android libs. I will try to get cv::getBuildInformation() with my 3.4.3 libs later... but do you think that this kind of regression is due to
- missing some flag in cmake
- compilator 
?

**Comment by alalek** [comment]
> 3.4.3

Could you try OpenCV 3.4.5?

**Comment by alalek** [comment]
> compilator

Compiler has been changed:
- NDK10 (outdated) uses GCC 4.9
- NDK18 (and next) uses Clang (LLVM)

**Comment by a2bc** [comment]
> > 3.4.3
> 
> Could you try OpenCV 3.4.5?

BuildInformation of OpenCV3.4.5:

     Version control:               3.4.5   
      Platform:
        Timestamp:                   2018-12-21T18:06:47Z
        Host:                        Linux 4.15.0-42-generic x86_64
        Target:                      Linux 1 aarch64
        CMake:                       2.8.12.2
        CMake generator:             Ninja
        CMake build tool:            /usr/bin/ninja
        Configuration:               Release
    
      CPU/HW features:
        Baseline:                    NEON
          requested:                 NEON FP16
          required:                  NEON
          disabled:                  VFPV3
    
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ (ver 4.9)
        C++ flags (Release):         -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -f

And with this version, I don't observe the regression !!!

**Comment by alalek** [comment]
Optimizations (in meaning of OpenCV source code) are similar between 3.4.5 and 4.0.1 - only compiler (Android NDK) is different.

**Comment by a2bc** [comment]
@alalek 
I will try to use the NDK10 (with GCC 4.9) to compile the code of OpenCV 4.0.1 to test.

I used this cmake command line to generate the project from that we compile to get libopencv_java3.so

`cmake -DCMAKE_TOOLCHAIN_FILE=/home/qbdo/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_STL=c++_static  -DCMAKE_BUILD_TYPE=Release -DANDROID_NATIVE_API_LEVEL=android-24 -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=ON -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_FAT_JAVA_LIB=ON ..`

Is it good ?
(I see different suggestions/propositions to add/remove option(s) in cmake to get better performance in stackoverflow....so I'm a bit lost...)

Can you show me the correct cmake command line to do the job ?

Thanks.

**Comment by alalek** [comment]
Take a look on [OpenCV 3.4 builds](http://pullrequest.opencv.org/buildbot/builders/3_4_pack-android/builds/298) with NDK 10.

You need to add "--config ndk-10.config.py" into options of `build_sdk.py`.

Additionally you probably need to setup these vars:
```
export ANDROID_NDK=/opt/android/android-ndk-r10e/
export ANDROID_SDK=/opt/android/android-sdk-java7/
export NDKROOT=${ANDROID_NDK}
```
(Android SDK related issue: #8460 )

---

We don't test these builds (they are deprecated).

**Comment by advanpix** [comment]
@alalek 

Is there proper guide on how to build OpenCV for Android using Windows? I have been struggling for few hours with no result. 

Can this be done using purely Android NDK & LLVM compiler included in Android Studio? 
Or we must use MinGW?
Do we have to run `build_sdk.py` or do other preparations?
...

I would highly appreciate any help & pointers.

(Usually I build OpenCV on Windows using Visual Studio & CMake - so that I am familiar with the process more or less).

**Comment by advanpix** [comment]
Ok, I got it, `build_sdk.py` did the job after some tweaks.

**Comment by dkurt** [comment]
Can we close this issue?

**Comment by advanpix** [comment]
I didn't start it, but I do not object to close the issue.
