### ISSUE TITLE
multiple error C1083 in OpenEXR compilation (IlmImf...)

### ISSUE THREAD

**Issue by mprevot** [opencv/opencv#13733]
I have 75 errors such as the following one:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: 'I:\opencv-master\opencv\3rdparty\openexr\Half\half.cpp': No such file or directory	IlmImf	I:\opencv-master\build\3rdparty\openexr\c1xx	1	

and 1:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "I:\OPENCV-MASTER\OPENCV\3RDPARTY\OPENEXR\ILMTHREAD\ILMTHREADMUTEX.CPP"	IlmImf		0	

##### System information (version)
- OpenCV => master (obtained from git from WSL)
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2017 (v141)
- cmake 3.13.3 64bit

##### Detailed description

OpenCV configured as following [1] compiles entirely except for the openexr project that throws multiple errors C1083 and E1696. Files do exist, and read/access rights are correct.

Weirdly, when I use the sources from zip I don't have this.

Maybe it's related to the operation where the sources were obtained through a git clone from WSL, unlike the unzip that was used outside WSL (unzipping from powershell). But I checked the rights from WSL, I have 777 for all files.

From I:\opencv-master\build\3rdparty\openexr
[IlmImf.vcxproj.txt](https://github.com/opencv/opencv/files/2814981/IlmImf.vcxproj.txt)

From I:\opencv-master\opencv\3rdparty\openexr
[CMakeLists.txt](https://github.com/opencv/opencv/files/2814985/CMakeLists.txt)

##### Steps to reproduce [1]

	cmake -G $target -T v141, host=x64 -j8 `
		-DBUILD_JAVA=0 -DWITH_MATLAB=0 -DBUILD_DOC=0 -DBUILD_PERF_TESTS=0 -DBUILD_TESTS=0 -DBUILD_opencv_world=0 `
		-DOPENCV_ENABLE_NONFREE=1 -DBUILD_opencv-apps=0 -DENABLE_PYLINT=0 -DENABLE_CXX11=1 -DWITH_VTK=1 `
		-DCUDA_SDK_ROOT_DIR="$env:CUDA_PATH" -DCUDA_ARCH_BIN="5.2" -DCUDA_VERBOSE_BUILD=0 -DBUILD_CUDA_STUBS=0 `
		-DWITH_OPENCL=1 -DWITH_CUDA=1 -DMKL_WITH_OPENMP=1 -DMKL_WITH_TBB=1 `
		-DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" `
		-DINSTALL_CREATE_DISTRIB=1 -DCPACK_BINARY_ZIP=1 -DCPACK_SOURCE_ZIP=1 -DCMAKE_VERBOSE_MAKEFILE=0 `
		../opencv | Tee-Object -Variable RESULT

then 

	"build opencv debug"
	msbuild.exe OpenCV.sln /verbosity:m /m
	"build opencv release"
	msbuild.exe OpenCV.sln /p:Configuration=Release /verbosity:m /m

**Comment by mprevot** [comment]
@alalek Isn't it a bug in the code (cmakelists.txt ?) ?

**Comment by mprevot** [comment]
The issue is happening when I `git pull/clone` with the linux version (WSL), but not with the Windows version (packed with Visual Studio). It might be a unprintable character or something. Ticket can be closed, unless a full investigation could occur and gather final reasons here. For some reason, this was not happening with the linux `git` at the beginning of opencv-master 4.0.0.

**Comment by mshabunin** [comment]
Try to disable OpenEXR: `-DWITH_OPENEXR=OFF`
