### ISSUE TITLE
Compilation failure by turing on verbose logging messages

### ISSUE THREAD

**Issue by taarof** [opencv/opencv#13741]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => CentOS 7
- Compiler => GCC 4.8.5

##### Detailed description
Faced a compilation error when turned on verbose logging message:

**In file included from opencv-3.4.1/modules/core/src/ocl.cpp:57:0:**
**/opencv-3.4.1/modules/core/src/ocl.cpp:** In member function 'bool cv::ocl::Program::Impl::createFromBinary(const cv::ocl::Context&, const unsigned char*, size_t, cv::String&)':
**/opencv-3.4.1/modules/core/src/ocl.cpp:3764:59:** error: 'src_' was not declared in this scope
         CV_LOG_VERBOSE(NULL, 0, "Load from binary... " << src_.getImpl()->module_.c_str() << "/" << src.getImpl()->name_.c_str());

##### Steps to reproduce

Set log strip level higher than verbose in logger.hpp and build openCV: 

`#define CV_LOG_STRIP_LEVEL CV_LOG_LEVEL_VERBOSE + 1`

**Comment by kinchungwong** [comment]
Although I don't know much about this code, just by scanning for similar code within the same source file, it seems the following replacement should fix the compilation issue - although, I don't know whether this will produce the correct behavior at runtime. 

Based on my understanding, the affected function is a member of ```Program::Impl```. Its constructor is given an argument of ```ProgramSource::Impl```, where the fields ```module_``` and ```name_``` could be found, both being strings, having a ```c_str()``` method. The problem stems from the fact that ```Program::Impl``` no longer keeps around a reference to ```ProgramSource::Impl``` after the constructor method finishes. But the constructor appears to have already made a copy of those strings, which are now named ```sourceModule_``` and ```sourceName_```. 

Replace
```cpp
src.getImpl()->module_.c_str()
```

With 
```cpp
sourceModule_.c_str()
```

Also, replace
```cpp
src.getImpl()->name_.c_str()
```

With 
```cpp
sourceName_.c_str()
```

This needs to be patched in branch 3.4 and then ported to master (4.0)

I have to fight my own issue of slow internet connection, so anyone else is welcome to submit a PR.
