### ISSUE TITLE
Understand Android sample build.gradle.in and CMakeLists.txt

### ISSUE THREAD

**Issue by hannesa2** [opencv/opencv#13740]
First of all, thank you for the Gradle project in 4.0.1 !
https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download 

Because I want to improve sample and I don't understand what's the benefit `build.gradle.in` and `CMakeLists.txt` is, I've several questions :
- What's the purpose of `build.gradle.in` and `CMakeLists.txt` ? Why not having it in https://github.com/opencv/opencv ready to use ? Eg `build.gradle` and a `settings.gradle` ? Simply open `/samples/android` with Android Studio and it builds. I need no https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download  I would prefer it ready to use here, then it's much more easier to improve it with a PR
- Why is `mobilenet-objdetect` not in https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download

**Comment by alalek** [comment]
1.
OpenCV CMake scripts handle:
- generation of Java code and JNI code from C++ OpenCV headers
- native code (binaries) compilation rules
- generation of related build.gradle
- handling of packaging rules

2. mobilenet-objdetect - not a part of previous set of android samples. Not tested and requires DNN model (downloading is handled by CMake scripts too).

---

Currently we do not using Android on a regular way, so something can be done here better.

**Comment by hannesa2** [comment]
I see.
`sample` is not that complicated prepared, but `sdk` has fragmented sources, a lot of artifacts from eg
`/modules/videoio`
`/modules/java/generator`
....

Is the reason a multiple usage in different prepared output artifacts, eg for Android ?
Which script assemble the sdk in https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download ?

**Comment by hannesa2** [comment]
Just to share what I do. I made a script to investigate from where the code in the assembled https://sourceforge.net/projects/opencvlibrary/files/4.0.1/opencv-4.0.1-android-sdk.zip/download comes from. You have to run it in extracted zip folder.

```
#!/usr/bin/env sh

# location of https://github.com/opencv/opencv
OPENCV=../opencv

find . -not -path '*/\.*' -type f -not -path '*javadoc*' -not -path '*licenses*' | grep -v '.sh' | while read -r file ; do
    echo $file
    find $OPENCV -name `basename $file` |xargs -n1 echo "    "
done
```

Several files are in git on several places, some files are generated, fine for *.so and *.a but from where does eg. `StereoBM.java` comes from ?

**Comment by alalek** [comment]
Generator of Java files (and JNI code) is here:
https://github.com/opencv/opencv/tree/4.0.1/modules/java/generator

Input for generator is C++ header files.
"Source" for StereoBM is [here](https://github.com/opencv/opencv/blob/4.0.1/modules/calib3d/include/opencv2/calib3d.hpp#L2248-L2296).

Java files of samples are not generated (copied into package).

**Comment by hannesa2** [comment]
I tried to follow you. But I've to come back to you

`python2 gen_java.py -h` deliveres
```
usage: gen_java.py [-h] -p PARSER -c CONFIG

OpenCV Java Wrapper Generator

optional arguments:
  -h, --help            show this help message and exit
  -p PARSER, --parser PARSER
                        OpenCV header parser
  -c CONFIG, --config CONFIG
                        OpenCV modules config
```

nice, but what to specify for `PARSER` and `CONFIG` ?

**Comment by alalek** [comment]
It is not supposed to run this script manually.

Consider using of existed build scripts:
- [build_sdk.py](https://github.com/opencv/opencv/tree/4.0.1/platforms/android) ([builds](http://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack))
- more advanced via [cmake](http://pullrequest.opencv.org/buildbot/builders/precommit_android/builds/18296) (build single Android architecture: armv7 / aarch  / x86 / etc)

In issue #13514 you can edit files in `<package>/samples` directly and then copy back them into `<opencv>/samples/android` (`.java` files are used "as is")

Other Android-specific files are [here](https://github.com/opencv/opencv/tree/4.0.1/modules/java/generator/android/java/org/opencv/android) and [here](https://github.com/opencv/opencv/tree/master/modules/java/generator/android-21/java/org/opencv/android) (OpenCV's JavaCamera interface).
