### ISSUE TITLE
Why the window_name is not const & ?

### ISSUE THREAD

**Issue by universeroc** [opencv/opencv#13747]
https://github.com/opencv/opencv/blob/665408e57f1bc01cd45196d31063d452c0d91abf/samples/directx/winapp.hpp#L15

I read throught the directx sample and find almost all constructor's window_name parameter is a string referrence type.

It's a input parameter and assign to a string member variable, so I'm confused that why it's a referrence type not a const referrence type ?

**Comment by universeroc** [comment]
@mshabunin I'm sorry to disturb you again, but could you tell me how to make a valid question? I looked through the wiki and cannot find a guide. And the const& make it better in my opinion.

**Comment by terfendail** [comment]
The right place for questions is [http://answers.opencv.org](http://answers.opencv.org)
Also OpenCV samples are rather about using OpenCV not about using different technologies or programming best practices, therefore OpenCV unrelated parts aren't paid a lot of attention during creation of samples.

Anyway your suggestion looks reasonable, so it would be great if you could prepare corresponding pull request.

**Comment by universeroc** [comment]
Thank you for your reply, I'll make one :)
