### ISSUE TITLE
is opencv not support the new algorithm's models(freezed_pb&&tf.train.write_graph()->pbtxt) which compiled by tensorflow

### ISSUE THREAD

**Issue by LuWei6896** [opencv/opencv#13742]
freezed.pb;
2.write_graph-------->pbtxt like this:
def convert_pb_2_graph_pbtxt(metaPath,ckptPath):
    sess = tf.Session()
    saver = tf.train.import_meta_graph(metaPath)
    saver.restore(sess,tf.train.latest_checkpoint(ckptPath))
    graph = tf.get_default_graph()
    graph_def = graph.as_graph_def()
    tf.train.write_graph(graph_def,'’）
3.load model by opencv:
       Net net = readNetFromTensorflow(modelBIn,modelTxt);

4. but some error as below:
    [libprotobuf ERROR /home/luwei/ML/opencv3.4.3/opencv-3.4.3/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 10263:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.3) /home/luwei/ML/opencv3.4.3/opencv-3.4.3/modules/dnn/src/tensorflow/tf_io.cpp:56: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: ctpn_graph_def.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'

why?
       I read a message from:https://github.com/opencv/opencv/issues/10312。“Text graph representation you used is just a copy of a binary one. We modify it to resolve different kind of conflicts between TensorFlow nodes and OpenCV layers.”
      Is opencv3.4.3 not support the new algorithm's models(freezed_pb&&tf.train.write_graph()->pbtxt) which compiled by tensorflow?

My mail:wendell_yi@sina.com

Thanks very much!

**Comment by dkurt** [comment]
@LuWei6896, Please don't use GitHub issues to ask questions. We have a forum for it: http://answers.opencv.org/.

If you want to report a bug you need to follow a guide in issue's template so make it reproducible. In case of your code sample, `Net net = readNetFromTensorflow(modelBIn,modelTxt);` provide reference to `modelBIn` and `modelTxt`.

**Comment by WendelHime** [comment]
Hi @LuWei6896 , I've passed into a similar problem when I was trying to use a keras model with opencv dnn (convert keras model to tensorflow -> freeze pb and generate pbtxt -> try to load on opencv dnn)

Take a look at [this tutorial](https://towardsdatascience.com/freezing-a-keras-model-c2e26cb84a38) on section "Freezing the model". The script `freeze_graph_simplified.py` generates a model that I could load with opencv. I've added the following lines on the tail of the file to generate the pbtxt file:

```python3
	with tf.keras.backend.get_session() as sess:
		tf.train.write_graph(sess.graph, args.model_dir, 'saved_model.pbtxt')
```

I don't have any sure if this method is going to work on function `net.forward()` (when I try it throws segmentation fault, but it seams like @dkurt  already solved [this issue](https://github.com/opencv/opencv/issues/13575) and I leave the PC building opencv on branch 3.4 
 from source while there isn't a update at pypi repository) , but to load the model this way will probably work

**Comment by dkurt** [comment]
@WendelHime, If `saved_model.pbtxt` is not modified - you don't need to generate it. Use it only when OpenCV cannot load just a binary graph.

**Comment by WendelHime** [comment]
> Use it only when OpenCV cannot load just a binary graph.

holly shit, so still something wrong on keras conversion to frozen graphdef because it throws:
```
(-2:Unspecified error) More than one input is Const op in function 'getConstBlob'
```
 
> #13575 is not related to TensorFlow importer confused

shiiiit

Sorry, forget what I said before

**Comment by dkurt** [comment]
@LuWei6896, @WendelHime, according issue's template it should be reproducible. Without models we cannot help you. Please fix it or issue would be closed after some time.

**Comment by WendelHime** [comment]
I've fixed my problem removing training nodes, converting variables to constants (freeze model) and writing the graphdef and I've success with the implementation with opencv (without `.pbtxt` as @dkurt recommended)

**Comment by LuWei6896** [comment]
@dkurt @WendelHime i get the model file from here:https://github.com/LuWei6896/faster-CTPN(ctpn.pb)，i generate ctpn.pbtxt likes this:
2.write_graph-------->pbtxt like this:
     def convert_pb_2_graph_pbtxt(metaPath,ckptPath):
           sess = tf.Session()
           saver = tf.train.import_meta_graph(metaPath)
           saver.restore(sess,tf.train.latest_checkpoint(ckptPath))
           graph = tf.get_default_graph()
           graph_def = graph.as_graph_def()
           tf.train.write_graph(graph_def,'’）

Thanks a lot~

**Comment by LuWei6896** [comment]
@dkurt @WendelHime  this repositories :
https://github.com/LuWei6896/faster-CTPN

**Comment by dkurt** [comment]
@LuWei6896, I'm confused a bit. Thre is no `.pb` file in the repo. If you have one - upload it somewhere and  provide a downloadable link. Please do not make us study your scripts trying to generate it.

**Comment by LuWei6896** [comment]
@dkurt here: https://github.com/eragonruan/text-detection-ctpn/releases

**Comment by dkurt** [comment]
This model contains unfused LSTM layer. Only `tf.contrib.rnn.LSTMBlockFusedCell` is supported for now.

**Comment by LuWei6896** [comment]
@dkurt  thanks your mention.
1.   I have try a lot : 
           	python optimize_for_inference.py --input=ctpn.pb --output=opt_graph.pb --input_names=Placeholder --output_names=Reshape_2,rpn_bbox_pred/Reshape_1 --frozen_graph=True

is there the same question that you have mentioned ?  
2. how can i generate myself pbtxt which is used  for readNetFromTensorflow(model_pb,pbtxt) ？

**Comment by LuWei6896** [comment]
@dkurt  thanks your mention.

**1.** I have tried a lot :
   python optimize_for_inference.py --input=ctpn.pb --output=opt_graph.pb --input_names=Placeholder --output_names=Reshape_2,rpn_bbox_pred/Reshape_1 --frozen_graph=True
### error:caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "opt_ctpn.pb" in function 'ReadProtoFromBinaryFile'
          
is there the same question that you have mentioned ?
**2.** how can i generate myself pbtxt which is used for readNetFromTensorflow(model_pb,pbtxt) ？

**Comment by LuWei6896** [comment]
@dkurt  and is the BLSTM  supported for now ?

**Comment by LuWei6896** [comment]
@dkurt  and is the tf.contrib.rnn.LSTMCell supported for now ?
