### ISSUE TITLE
Memory Leak when using LoadLibrary/FreeLibrary on DLL that uses OpenCV

### ISSUE THREAD

**Issue by erichfrazer** [opencv/opencv#13750]
- OpenCV => 3.4.5
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

I'm using this sequence:
1. Call LoadLibrary on my DLL, which import library links to OpenCV 3.4.5's core dll.
2. call a bunch of functions on my DLL, which uses OpenCV
3. Call FreeLibrary on my DLL, which unwinds and calls DllMain on OpenCV w/ PROCESS_DETACH
4. Expecting static objects in OpenCV to be freed at this point, instead the crt whines about a lot of unfreed memory.

**Comment by alalek** [comment]
I believe used tools are smart enough to filter out these cases.
Refer for similar issues for explanation.
