### ISSUE TITLE
Performance degrading with cv::linearpolar in multithreaded application

### ISSUE THREAD

**Issue by ant-Korn** [opencv/opencv#13758]
##### System information (version)
- OpenCV => 3.4.3 (static build)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Processor, RAM => Intel® Xeon® E5-2630 v3 @ 2.40 GHz 2.40 GHz, 128 GB RAM

##### Detailed description

We trying to convert a bunch of different images to polar coordinates space.
For this purpose we used function `cv::linearPolar` in parallel OpenMP threads.
To prevent creating subthreads we executed function `cv::setNumThreads(0)`.
We faced with performance degrading with increasing number of processing threads.
So we cannot achieve increased performance in multithreading application due to some locks.
A similar problem is observed with some other functions (`cv::bilateralFilter` and `cv::integral`).

Using the code presented in section below, we got the following result: 

| Threads number           | Processing time, s |
| ------------------------ | ------------------ |
| Without parallelization  | 141.5              |
| 2                        | 86.2               |
| 5                        | 78.9               |
| 10                       | 89.1               |
| 15                       | 94.5               |
| 20                       | 96.7               |

Our build information is:

```
General configuration for OpenCV 3.4.3 =====================================
  Version control:               3.4.3-dirty

  Platform:
    Timestamp:                   2019-02-04T07:44:59Z
    Host:                        Windows 6.1.7601 AMD64
    CMake:                       3.13.3
    CMake generator:             Visual Studio 15 2017 Win64
    CMake build tool:            D:/Program Files/Visual Studio/MSBuild/15.0/Bin/MSBuild.exe
    MSVC:                        1916

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (3 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (8 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      NO
    C++11:                       YES
    C++ Compiler:                D:/Program Files/Visual Studio/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe  (ver 19.16.27026.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP32   /MT /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP32   /MTd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  D:/Program Files/Visual Studio/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP32    /MT /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP32  /MTd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32
    3rdparty dependencies:       zlib libjpeg-turbo libwebp libpng libtiff libjasper

  OpenCV modules:
    To be built:                 calib3d core features2d flann highgui imgcodecs imgproc ml objdetect photo python_bindings_generator stitching
    Disabled:                    dnn java_bindings_generator js video videoio videostab world
    Disabled by dependency:      shape superres ts
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3 viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI: 
    Win32 UI:                    YES

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.34)
    TIFF:                        build (ver 42 - 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    HDR:                         NO
    SUNRASTER:                   YES
    PXM:                         YES

  Video I/O:
    Video for Windows:           YES
    DC1394:                      NO
    GStreamer:                   NO
    DirectShow:                  YES

  Parallel framework:            Concurrency

  Other third-party libraries:
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  Python 2:
    Interpreter:                 (ver 2.7.12)
    Libraries:                   NO
    numpy:                       NO (Python wrappers can not be generated)
    packages path:               -

  Python (for build):            

  Install to:                    D:/Documents/repos/opencv-static/build/install
-----------------------------------------------------------------
```

To resolve this problem we also tried to comment out the following line in source code and recompile OpenCV, but result is still the same:

https://github.com/opencv/opencv/blob/b38c50b3d0c31e82294315ec44b54b7ef559ef12/modules/core/src/parallel.cpp#L77

The result of threading analysis using Intel® VTune™ Amplifier showed significant waiting time in function `cv::warpPolar`.
Screenshot of threading analysis of code presented in section below:

![test_linearpolar_vtune](https://user-images.githubusercontent.com/26012176/52198957-a5d51280-2875-11e9-8f01-ddb0454f830b.PNG)

##### Steps to reproduce

```.cpp
#include "opencv2/opencv.hpp"
#include <chrono>
#include <omp.h>

cv::Mat create_model_image(cv::Size size)
{
	int img_type = CV_8U;
	const unsigned type_max_val = 255;
	int r = 9 * std::min(size.height / 2, size.width / 2) / 10;
	cv::Mat image = cv::Mat::zeros(size, img_type);
	cv::circle(image, cv::Point(size.width / 2, size.height / 2), r, cv::Scalar(type_max_val), cv::FILLED);
	return image;
}

int main(int argc, char* argv[])
{
	int images_number = 2000;
	
	// Images generation
	cv::Mat sample = create_model_image(cv::Size(2000, 2000));
	std::vector<cv::Mat> images(images_number);
	for (int k = 0; k < images_number; ++k)
	{
		images[k] = sample.clone();
	}

	// Set numbers of threads for testing
	const int tests_num = 5;
	int threads_num[tests_num] = {2, 5, 10, 15, 20};

	// Run tests
	for (int i = 0; i < tests_num; ++i)
	{
		int number_of_threads = threads_num[i];
		std::cout << "Threads number: " << number_of_threads << std::endl;

		cv::setNumThreads(0);

		auto begin = std::chrono::high_resolution_clock::now();

#pragma omp parallel for num_threads(number_of_threads)
		for (int k = 0; k < images_number; ++k)
		{
			cv::Mat & src_img = images[k];
			cv::Mat img;
			src_img.convertTo(img, CV_32FC1);
			cv::Point2f center((float)img.cols / 2, (float)img.rows / 2);
			double maxRadius = std::min(center.y, center.x);
			cv::Mat img_p;
			cv::linearPolar(img, img_p, center, maxRadius, cv::WARP_FILL_OUTLIERS);
		}
		auto elapsed = std::chrono::high_resolution_clock::now() - begin;
		std::chrono::duration<double> time_span = std::chrono::duration_cast<std::chrono::duration<double>>(elapsed);
		std::cout << "Elapsed time: " << time_span.count() << " s" << std::endl << std::endl;
	}
}
```

Thanks

**Comment by alalek** [comment]
> #pragma omp parallel

I believe you catched OpenMP issue with "active wait" of worker threads.
Try "OMP_WAIT_POLICY=passive".

**Comment by ant-Korn** [comment]
We tried set environment variable `OMP_WAIT_POLICY` to `PASSIVE` value but performance degrading still saving.
Result of testing:

| Threads number           | Processing time, s |
| ------------------------ | ------------------ |
| Without parallelization  | 160.1              |
| 2                        | 88.4               |
| 5                        | 77.1               |
| 10                       | 86.4               |
| 15                       | 92.2               |
| 20                       | 93.3               |

The result of threading analysis using Intel® VTune™ Amplifier:

![test_linearpolar_vtune_2](https://user-images.githubusercontent.com/26012176/52209193-33275f80-2894-11e9-8763-3c99a6025568.PNG)

Also, we noticed using Process Hacker tool that threads state of this application constantly changes from `Running` to `Wait:WrPushLock`. Screenshot of this state:

![wrpushlock](https://user-images.githubusercontent.com/26012176/52208965-7208e580-2893-11e9-88f3-31144eaabefb.PNG)

**Comment by alalek** [comment]
Using different parallel frameworks in the same app is not a good practice.
However,
> cv::setNumThreads(0);

should workaround this problem.


> We faced with performance degrading with increasing number of processing threads.

Linear speedup is usually demonstrated for compute bound tasks.
Memory bound tasks don't show linear speedup. Check "memory bandwidth" metric via VTune (some links: [1](https://software.intel.com/en-us/vtune-amplifier-help-memory-access-analysis) [2](https://software.intel.com/en-us/vtune-amplifier-help-memory-usage-view)).

> images_number = 2000;

Looks like this case uses > 64Gb. Ensure that there are no memory swapping activity.

> WrPushLock

More detailed stack trace is required.

**Comment by ant-Korn** [comment]
> Memory bound tasks don't show linear speedup. Check "memory bandwidth" metric via VTune (some links: 1 2).

The result of the VTune Memory Access Analysis is following:
![test_linearpolar_vtune_3](https://user-images.githubusercontent.com/26012176/52217557-bacb9900-28a9-11e9-94e4-dbf980825974.PNG)
![test_linearpolar_vtune_4](https://user-images.githubusercontent.com/26012176/52217563-bdc68980-28a9-11e9-984b-7384271bd33c.PNG)

> Looks like this case uses > 64Gb. Ensure that there are no memory swapping activity.

The size of the memory used does not exceed 10 GB and there is no memory swapping activity.
