### ISSUE TITLE
Memory Leak when using MFC

### ISSUE THREAD

**Issue by erichfrazer** [opencv/opencv#13756]
OpenCV => 3.4.5
Operating System / Platform => Windows 10, 64 bit
Compiler => Visual Studio 2017

Alexander Alekhin closed my last bug with "duplicate", and "won't fix". I would love to know why it's a won't fix...

If you use the dynamically imported OpenCV core DLL, and you link against MFC, when the dll unloads, there are a ton of leaked memory complaints. I do believe these are real. If I repeatedly dynamically load and unload a DLL which itself links to OpenCV's core, this causes some serious termination bugs when attempting to call FreeLibrary( ) on my dll, which has loaded OpenCV. It makes my DLL nearly unusable.

somebody present a solution, workaround, doc, whatever, but the way it exists now is near intolerable.

**Comment by dkurt** [comment]
Provide a reproducer. Bug reports should be accurate. You previous [issue](https://github.com/opencv/opencv/issues/13750) is just a list of statements. Add a minimal working example which can show "some serious termination bugs".

For usage questions use a forum http://answers.opencv.org/ but this is a bug report and it has corresponding guidelines to open a new issue.

**Comment by alalek** [comment]
"Duplicate" means that searching on existed issues is ignored.
It is not hard really: https://github.com/opencv/opencv/issues?utf8=%E2%9C%93&q=is%3Aissue+leak+memory+DLL

You may start from these issues: #6203 #9745

> workaround

Configure memory leak detector tool, like this: https://github.com/opencv/opencv/blob/4.0.1/platforms/scripts/valgrind.supp
