### ISSUE TITLE
TypeError: Incorrect type of self (must be 'StereoMatcher' or its derivative)

### ISSUE THREAD

**Issue by hemangjoshi37a** [opencv/opencv#13752]
Code : 
```
import numpy as np
import cv2
from matplotlib import pyplot as plt

imgL = cv2.imread('tsukuba_l.png',0)
imgR = cv2.imread('tsukuba_r.png',0)

stereo = cv2.StereoBM(numDisparities=16, blockSize=15)
disparity = stereo.compute(imgL,imgR)
plt.imshow(disparity,'gray')
plt.show()
```
Error : 

> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-10-c6204d98dca8> in <module>
>       7 
>       8 stereo = cv2.StereoBM(numDisparities=16, blockSize=15)
> ----> 9 disparity = stereo.compute(imgL,imgR)
>      10 plt.imshow(disparity,'gray')
>      11 plt.show()
> 
> TypeError: Incorrect type of self (must be 'StereoMatcher' or its derivative)

**Comment by LaurentBerger** [comment]
that's not an issue use [doc ](https://docs.opencv.org/master/d9/dba/classcv_1_1StereoBM.html#a04fdf00525f82fe708d556e2cd359004)and [samples](https://github.com/opencv/opencv/blob/master/samples/python/stereo_match.py#L45)

**Comment by yunzhe-tao** [comment]
Hi, did you solve the issue? Thanks.
