### ISSUE TITLE
cudalegacy NCVHaarObjectDetection hangs with RTX 2080 Ti

### ISSUE THREAD

**Issue by logidelic** [opencv/opencv#13761]
##### System information (version)
- OpenCV => 3.4.x (latest)
- Operating System / Platform => Ubuntu 18
- Compiler => GCC

##### Detailed description

GPU-based Haar Classifiers hang when using an Nvidia RTX 2080 Ti (as well as Titan V, and other newer architectures). 

##### Steps to reproduce

Use `cv::cuda::CascadeClassifier::create()` to create a detector and call `detectMultiScale()`.

##### More info

I believe this is exactly (?) the same issue as flagged (and fixed!) in https://github.com/opencv/opencv/issues/13014 . I notice that in `modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu` we also perform a `cv::cuda::device::shfl_up()` and I wonder if that's the problem. I've tried applying the same fix as in #13014, but so far I've failed. Has anyone been able to get this working?

Thanks!

**Comment by nglee** [comment]
I will take a look on this issue.

**Comment by nglee** [comment]
Testing with `samples/gpu/cascadeclassifier.cpp` example code on `cuda-gdb` with `set cuda break_on_launch application` turned on, it was discovered that in addition to unsafe version of block scan function being used in `NCVHaarObjectDetection.cu` (which is pointed out by @logidelic):

https://github.com/opencv/opencv/blob/5f57842575cdb633debc0c1142d7d842c4176b95/modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu#L267

there was another usage of unsafe block scan function in `scanRows()` of `NPP_staging.cu`:

https://github.com/opencv/opencv/blob/5f57842575cdb633debc0c1142d7d842c4176b95/modules/cudalegacy/src/cuda/NPP_staging.cu#L304

The safe block scan function was provided in `cudev` module by opencv/opencv#13658. Using the safe version seems to fix the issue. Will open a PR soon.

The PR will also remove one last remaining usage of unsafe version being used in `removePass1Scan()` of `NPP_staging.cu`:

https://github.com/opencv/opencv/blob/5f57842575cdb633debc0c1142d7d842c4176b95/modules/cudalegacy/src/cuda/NPP_staging.cu#L1308

There are more functions in `cudalegacy` module that hangs on 2080 Ti, and with these fixes, they do not hang.

**Comment by logidelic** [comment]
Thank you @nglee ! I just want to confirm that this fix works for me in my (very limited) testing. I see that merging is blocked currently... Who can approve the merge into the 3.4 branch?

**Comment by nglee** [comment]
Hi @logidelic, since it is merged now, you should be able to do your testing on the latest 3.4 branch. After testing, would you please share your test result?

**Comment by logidelic** [comment]
Just spent a bit of time testing on the latest from 3.4. So far so good! Thanks once again for this great work.
