### ISSUE TITLE
IMEncode & _Cfunc_GoBytes taking lot of memory and not releasing it. Go profiler screenshot  

### ISSUE THREAD

**Issue by anilknayak** [opencv/opencv#13770]
##### System information (version)
- OpenCV => 4
- GoCV => 0.18.0
- Operating System / Platform => Raspberry Pi
- Compiler => GCC

##### Detailed description
1. Installed the OpenCV and GoCV from the source.
After I ran the IMEncode to convert a gocv.Mat type to []byte. Over the time the Go Profiling result shows increasing in alloc_space. 
##### Steps to reproduce
1. Create Go Routine
2. Calls a method accepts a gocv.Mat type and converts Mat to byte 
3. Do that for 5-10 min and same time run the profiler.
4. Below is a screen shot from the go profiler

![issue](https://user-images.githubusercontent.com/4894147/52381829-dbb9f880-2a27-11e9-8e4b-c161f97d7203.jpg)

**Comment by alalek** [comment]
Go OpenCV bindings wrapper is not maintained here.
We can take a look on C++ OpenCV reproducer.
