### ISSUE TITLE
python loader breaks sys.path[0]

### ISSUE THREAD

**Issue by paroj** [opencv/opencv#13779]
- OpenCV => 4.x / 3.4.3+

```py
>>> import sys
>>> sys.path[0]
''
>>> import cv2
>>> sys.path[0]
'/usr/local/lib/python3.6/dist-packages/cv2/python-3.6'
```

https://docs.python.org/3.7/library/sys.html
> As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter.

**Comment by alalek** [comment]
Try to fix it [here](https://github.com/opencv/opencv/blob/3.4.5/modules/python/package/cv2/__init__.py#L68):
```
sys.path.insert(1, p)
```
