### ISSUE TITLE
MatchTemplate() function is given different max matching score in Windows 10

### ISSUE THREAD

**Issue by ebonat** [opencv/opencv#13785]
The MatchTemplate() function results is given different max matching score in Windows 10.

OpenCV => 3.4.1
Operating System / Platform => Windows 10 (64 Bit)
Compiler => Visual Studio 2017

Using the same original and template images in Windows 10 the max matching score is different from Windows 7. Is there library that needs to be updated in Windows 10?

Thank you for your help,

-Ernest

**Comment by LaurentBerger** [comment]
How do you read image ? May be this [issue ](https://github.com/opencv/opencv/issues/12340)can help you

**Comment by ebonat** [comment]
I'm using OpenCVSharp and the tiff type images are read using the Mat() constructor  as:

 Mat imageSource = new Mat(imageFilePathName, ImreadModes.GrayScale);

**Comment by LaurentBerger** [comment]
Wait for official opencv member but here it is opencv in C++ python java node.js. No CSharp. If you want some help here a code in those language (with  data file too) is needed

**Comment by ebonat** [comment]
Thank you very much for your help!
