### ISSUE TITLE
cv2.HOGDescriptor().compute() Abort trap: 6 after cv2.resize()

### ISSUE THREAD

**Issue by mohanpb** [opencv/opencv#13797]
Hello!

I am using:
OpenCV v 4.0.0 (win_amd64)
Python v 2.7.15
Operating platform - MacOS Mojave 10.14.3  

I am getting Abort trap:6 in cv2.HOGDescriptor().compute() after cv2.resize()

```
In [1]: import cv2

In [2]: img = cv2.imread('../MSnakes/templates/template1.png')

In [3]: img2 = cv2.resize(img, (96,96))

In [4]: hog = cv2.HOGDescriptor()

In [5]: fea = hog.compute(img)

In [6]: fea.shape
Out[6]: (41580, 1)

In [7]: fea = hog.compute(img2)
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6
```

I am not sure why this is happening. Any help is appreciated. 

Thank you,
Mohan

**Comment by berak** [comment]
that's not a bug, the error is on your side.

the HogDescriptor has a [default window size of 64x128](https://github.com/opencv/opencv/blob/master/modules/objdetect/include/opencv2/objdetect.hpp#L385)

so you have to either adjust that to your desired image patch size (ONCE!) or resize all your image patches to 64x128
