### ISSUE TITLE
I want to know that why OpenCV not providing multiplying Mat by mask?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#13795]
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => WIndows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
I want to multiply `Mat `by Scalar using `mask`, but in API I could not find a function can do multiplication by `Mask `such as `Addition `or `Subtraction `which has an optional `mask `parameter, `Multiplication `and `Division `do not.

**Comment by Bahramudin** [comment]
@alalek If I want to multiply specific parts of a Mat, then how can I do. The only way is to use mask, something like addition or subtraction and many other OpenCV functions which supports optional mask parameter to operate the specific parts of a Mat for speeding up. Otherwise, I must copy the data, and then multiply and then,... and then. Which cause to work very slow, especially while working in real-time.
Any Idea?

Thanks!

**Comment by kinchungwong** [comment]
Thanks @LaurentBerger for providing a few workarounds in  http://answers.opencv.org/question/66216/how-to-multiply-cvmat-with-mask/

Please re-word this post, so that OpenCV team can mark this as a feature request.

**Comment by Zireael07** [comment]
Why is this closed? Has this been implemented? If not, I'd like to make a feature request myself...
