### ISSUE TITLE
Failure to compile opencv-4.0.1 using mingw-w64

### ISSUE THREAD

**Issue by clim100** [opencv/opencv#13791]
One of the steps to compiling wholebrain includes compiling opencv with mingw-w64. I followed the video tutorial closely, however the rtools/opencv etc all have newer versions for download instead of the old. 

##### System information (version)
Rtools3.4 (Frozen)
OpenCV 4.0.1
Windows 10
CMake3.14.0

##### Detailed description
I went into my Command Prompt and entered the following codes: 
cd c:/opencv/release
mingw32-make
mingw32-make install

This is the error I got: 
[ 35%] Linking CXX shared library ..\..\bin\libopencv_core401.dll
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `CMakeFiles\opencv_core.dir/objects.a(vs_version.rc.obj)' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
modules\core\CMakeFiles\opencv_core.dir\build.make:1480: recipe for target 'bin/libopencv_core401.dll' failed
mingw32-make[2]: *** [bin/libopencv_core401.dll] Error 1
CMakeFiles\Makefile2:1390: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
mingw32-make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
makefile:161: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Would really appreciate your help!

**Comment by clim100** [comment]
I also use R Version 3.5.2

**Comment by alalek** [comment]
> vs_version.rc.obj

There are already two issues about this.
