### ISSUE TITLE
findCirclesGrid can't detect multiple patterns

### ISSUE THREAD

**Issue by alexandrecq** [opencv/opencv#13802]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => g++ 5.4.0

##### Detailed description

`findCirclesGrid` fails to detect a pattern when another is visible. In the example image attached, the right pattern can only be detected if the one on the left is not visible. The left pattern can be detected in both cases. The default blob detector finds all key points to this must be a clustering issue. Without the clustering flag nothing is detected in any case.

##### Steps to reproduce

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.0.0-dev'
>>> img1 = cv2.imread("./1_pattern.png")
>>> img2 = cv2.imread("./2_patterns.png")
>>> ret, fts = cv2.findCirclesGrid(img1, patternSize=(23, 11), flags=(cv2.CALIB_CB_SYMMETRIC_GRID + cv2.CALIB_CB_CLUSTERING))
>>> print(ret)
True
>>> ret, fts = cv2.findCirclesGrid(img2, patternSize=(23, 11), flags=(cv2.CALIB_CB_SYMMETRIC_GRID + cv2.CALIB_CB_CLUSTERING))
>>> print(ret)
False
```

![1_pattern](https://user-images.githubusercontent.com/37152974/52581769-7461c700-2de0-11e9-99fd-edfa761cb708.png)
![2_patterns](https://user-images.githubusercontent.com/37152974/52581770-7461c700-2de0-11e9-9124-7805c29a3e54.png)

**Comment by alalek** [comment]
Multiple patterns are not supported by design.

For multiple patterns consider using aruco (different patterns!).

**Comment by alexandrecq** [comment]
Thanks for the tip about aruco, looks interesting. 

Are multiple patterns supported for `findChessboardCorners`? This design choice isn't mentioned in the documentation.

**Comment by alalek** [comment]
Only one pattern per one call.

You can "mask" found pattern and call `find...()` again. But it is not reliable (multiple patterns may break algorithm and finding of the first pattern can be broken).
