### ISSUE TITLE
is img_hash a standalone module like opencv_world or a bug from cmake?

### ISSUE THREAD

**Issue by blaisexen** [opencv/opencv#13804]
is img_hash a standalone module like opencv_world or a bug from cmake or from opencv makefile?
-
because every time I build "opencv_img_hashXXX.dll" is always with "OpenCv_WorldXXX.dll", 
I think there is a bug inside cmake or opencv makefile that img_hash can't be embedded from opencv_worldxxx

**Comment by blaisexen** [comment]
WHY is it invalid, the question is TRUE, I'm asking question here, because the last time I ask from OpenCv forum they did not believed that Img_hash module can't be embedded from OpenCv_World modules.

**Comment by alalek** [comment]
This tracker is for issues and bugs that needs fix in OpenCV.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
