### ISSUE TITLE
the outputs of net.forward() are different by opencv4.0.0 win-pack and build-from-source

### ISSUE THREAD

**Issue by lunasdejavu** [opencv/opencv#13806]
##### Detailed description
My environment is windows 7 x64 tensorflow 1.12 GPU:GTX1060 visual studio 2015 and the dataset has only 1 class. I trained a faster_rcnn_inception_v2_coco model by tensorflow-object detection api, then I did the inference by the C++ code like:
```
const size_t inWidth = 1024;
const size_t inHeight = 1024;
//const float WHRatio = inWidth / (float)inHeight;
const char* classNames[] = { "rainbow" };
const float WHRatio = inWidth / (float)inHeight;
int main()
{
	String weights = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\frozen_inference_graph.pb";
	String prototxt = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\graph.pbtxt";
	dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);
	Mat frame = cv::imread("C:\\hsir\\build\\bin\\test\\test-c1-1.bmp");
	Size frame_size = frame.size();
	cv::Mat blob = cv::dnn::blobFromImage(frame, 1, Size(inWidth, inHeight), false, true);/
	net.setInput(blob);
	Mat output = net.forward();
	Mat detectionMat(output.size[2], output.size[3], CV_32F, output.ptr<float>());
	float confidenceThreshold = 0.5;
	for (int i = 0; i < detectionMat.rows; i++)
	{
		float confidence = detectionMat.at<float>(i, 2);
		printf("%f\n", detectionMat.at<float>(i, 2));
		printf("%d\n", i);
		if (confidence > confidenceThreshold)
		{	
			size_t objectClass = (size_t)(detectionMat.at<float>(i, 1));
			int xLeftBottom = static_cast<int>(detectionMat.at<float>(i, 3) * frame.cols);
			int yLeftBottom = static_cast<int>(detectionMat.at<float>(i, 4) * frame.rows);
			int xRightTop = static_cast<int>(detectionMat.at<float>(i, 5) * frame.cols);
			int yRightTop = static_cast<int>(detectionMat.at<float>(i, 6) * frame.rows);

			ostringstream ss;
			ss << confidence;
			String conf(ss.str());

			Rect object((int)xLeftBottom, (int)yLeftBottom,
				(int)(xRightTop - xLeftBottom),
				(int)(yRightTop - yLeftBottom));

			rectangle(frame, object, Scalar(0, 255, 0), 2);
			String label = String(classNames[objectClass]) + ": " + conf;
			int baseLine = 0;
			Size labelSize = getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, &baseLine);
			rectangle(frame, Rect(Point(xLeftBottom, yLeftBottom - labelSize.height),
				Size(labelSize.width, labelSize.height + baseLine)),
				Scalar(0, 255, 0), cv::FILLED);
			putText(frame, label, Point(xLeftBottom, yLeftBottom),
				FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 0, 0));
		}
	}
	namedWindow("image", cv::WINDOW_NORMAL);
	imshow("image", frame);
	waitKey(0);
	return 0;
}
```
the graph.pbtxt is[ here](https://drive.google.com/file/d/1drLcaGiPh2qx5jbC85ID_FOrQiS0fwS2/view?usp=sharing)
frozen_inference_graph.pb is [here](https://drive.google.com/file/d/1YO4B0x7eEAx2X93f2ljHjSmFDHwMAXSF/view?usp=sharing)
image is [here](https://drive.google.com/file/d/11SQ3tH3cL8u9QizVkUnTDCwgAfoeaEd_/view?usp=sharing)

	
the outputs of net.forward() are different by opencv4.0.0 win-pack and build-from-source  edit
dnn
objectdetection
4.0.0
opencv
asked 24 hours ago

lunasdejavu gravatar image
lunasdejavu 
1 ●1
updated 3 hours ago

My environment is windows 7 x64 tensorflow 1.12 GPU:GTX1060 visual studio 2015 and the dataset has only 1 class. I trained a faster_rcnn_inception_v2_coco model by tensorflow-object detection api, then I did the inference by the C++ code like:

string weights = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\frozen_inference_graph.pb";
string prototxt = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\graph.pbtxt";
cv::dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);
cv::Mat frame = cv::imread("C:\\hsir\\build\\bin\\test\\test-c1-1.bmp");
cv::Mat blob = cv::dnn::blobFromImage(frame, 1, cv::Size(inWidth, inHeight), false, true);
net.setInput(blob);
cv::Mat outPut = net.forward();
cv::Mat detectionMat = cv::Mat(outPut.size[2], outPut.size[3], CV_32F, outPut.ptr<float>());
it works fine by my code with opencv 4.0.0 and 4.0.1 installed by win-pack, but I tried to put it in a project of my team which seems to use customized opencv from 4.0.0 which was build from source, then the detectionMat is totally wrong. I traced the bug and just copied the same code into a function of the project, but the result was still wrong. There was no error or warning shows up and nothing wrong with reading the model, image and forward(); The correct result should be only one object detected with confidence 1.0 and the others with confidence 0.0. The wrong result has 100 objects detected with 0.5~0.99 confidences but none of them close to the real object.

**Comment by dkurt** [comment]
@lunasdejavu, check the links. They are not sharable (request required).

**Comment by lunasdejavu** [comment]
> @lunasdejavu, check the links. They are not sharable (request required).

it is sharable now.

**Comment by lunasdejavu** [comment]
> @lunasdejavu, check the links. They are not sharable (request required).

I modified and upload the graph files again and it is sharable now.

**Comment by lunasdejavu** [comment]
I found my boss added [opencv_contrib](https://github.com/opencv/opencv_contrib) which has dnn objdetect modules, it seems to overload some functions of dnn. So is there anyway to keep using the function without rebuild opencv excluding this module?

**Comment by lunasdejavu** [comment]
the customized opencv is [here](https://drive.google.com/file/d/1kDQzDRSwxKEAt3qHZnP_dPzKX35mOIDF/view?usp=sharing)

**Comment by alalek** [comment]
Try `cmake -DBUILD_opencv_dnn_objdetect=OFF ...`

**Comment by lunasdejavu** [comment]
> Try `cmake -DBUILD_opencv_dnn_objdetect=OFF ...`
I will try later.
I tried to not include opencv_dnn_objdetect400.lib but the result is the same...

**Comment by lunasdejavu** [comment]
> Try `cmake -DBUILD_opencv_dnn_objdetect=OFF ...`

how to do it by cmake-gui?

**Comment by dkurt** [comment]
@lunasdejavu, Let me ask you one more time to check the links (just try to log out from your account and try to follow them). You need to add permissions for all the users to have an access to it. If you're not able to share a model (if models are private) you can initialize it's weights randomly.
![screenshot from 2019-02-13 15-24-23](https://user-images.githubusercontent.com/25801568/52711749-a66f5680-2fa3-11e9-9948-e8cd00fcbe2d.png)

**Comment by lunasdejavu** [comment]
> @lunasdejavu, Let me ask you one more time to check the links (just try to log out from your account and try to follow them). You need to add permissions for all the users to have an access to it. If you're not able to share a model (if models are private) you can initialize it's weights randomly.
> ![screenshot from 2019-02-13 15-24-23](https://user-images.githubusercontent.com/25801568/52711749-a66f5680-2fa3-11e9-9948-e8cd00fcbe2d.png)
thanks to reply again.
the google drive was for the speicific college, but it is not now. 
Please check again.

**Comment by lunasdejavu** [comment]
and I found the bug is from `Mat output = net.forward();`
blob is the same since I save the mats and check them are the same or not.

**Comment by dkurt** [comment]
@lunasdejavu, try the following steps:

* Build OpenCV from master branch

* Download https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_v2_coco.config and replace `num_classes: 90` to `num_classes: 1` (you didn't attach it to issue so I used a public config).

* Generate a text graph representation:
```
python /path/to/opencv/samples/dnn/tf_text_graph_faster_rcnn.py --input frozen_inference_graph.pb --config faster_rcnn_inception_v2_coco.config --output graph.pbtxt
```

* Run with a sample from https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API with modified path to input image and `size=(1024, 1024)`.

I got the following output image
![out](https://user-images.githubusercontent.com/25801568/52793777-8ad97e00-307f-11e9-92dc-508127fe14db.jpg)

**Comment by lunasdejavu** [comment]
> @lunasdejavu, try the following steps:
> 
> * Build OpenCV from master branch
> * Download https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_v2_coco.config and replace `num_classes: 90` to `num_classes: 1` (you didn't attach it to issue so I used a public config).
> * Generate a text graph representation:
> 
> ```
> python /path/to/opencv/samples/dnn/tf_text_graph_faster_rcnn.py --input frozen_inference_graph.pb --config faster_rcnn_inception_v2_coco.config --output graph.pbtxt
> ```
> * Run with a sample from https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API with modified path to input image and `size=(1024, 1024)`.
> 
> I got the following output image
> ![out](https://user-images.githubusercontent.com/25801568/52793777-8ad97e00-307f-11e9-92dc-508127fe14db.jpg)
Thanks for testing of my model! 
But I did put  it in the link: the graph.pbtxt is[ here](https://drive.google.com/file/d/1drLcaGiPh2qx5jbC85ID_FOrQiS0fwS2/view?usp=sharing)
And I got the correct result.
My problem is I can't get it from this opencv 4.0.0 [library](https://drive.google.com/file/d/1kDQzDRSwxKEAt3qHZnP_dPzKX35mOIDF/view?usp=sharing)
my mentor said he built the opencv library with opencv_contrib, and he doesn't want to rebuild it to get rid of dnn_objdetect...

**Comment by alalek** [comment]
We don't support/fix old releases.

**Comment by lunasdejavu** [comment]
> We don't support/fix old releases.

it is ok,so you mean there won't be any problem if I build 4.0.1 with opencv_contrib?

**Comment by dkurt** [comment]
@lunasdejavu, I get the same output image even with OpenCV compiled with opencv_contrib.

Please try to use our samples at first: [in C++](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) or [in Python](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py). If they work - debug your code. From the first sight at least the following invocation doesn't match proper semantic:

```cpp
cv::Mat blob = cv::dnn::blobFromImage(frame, 1, Size(inWidth, inHeight), false, true);/
```
docs: https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga29f34df9376379a603acd8df581ac8d7

>  My problem is I can't get it from this opencv 4.0.0 [library](https://drive.google.com/file/d/1kDQzDRSwxKEAt3qHZnP_dPzKX35mOIDF/view?usp=sharing)

Please note that we won't debug any custom build or code.

**Comment by lunasdejavu** [comment]
> @lunasdejavu, I get the same output image even with OpenCV compiled with opencv_contrib.
> 
> Please try to use our samples at first: [in C++](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) or [in Python](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py). If they work - debug your code. From the first sight at least the following invocation doesn't match proper semantic:
> 
> ```c++
> cv::Mat blob = cv::dnn::blobFromImage(frame, 1, Size(inWidth, inHeight), false, true);/
> ```
> 
> docs: https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga29f34df9376379a603acd8df581ac8d7
> 
> > My problem is I can't get it from this opencv 4.0.0 [library](https://drive.google.com/file/d/1kDQzDRSwxKEAt3qHZnP_dPzKX35mOIDF/view?usp=sharing)
> 
> Please note that we won't debug any custom build or code.

is the version of  OpenCV compiled with opencv_contrib. is 4.0.0 or 4.0.1?

I said nothing wrong with the code because the results I used the same code and compile with diffrent OpenCV libraries are different.
Here  are the cmake file
```
set(OPENCV_INCLUDE_DIRS
		D:/opencv/build/install/include
	)
set(OPENCV_LINK_DIRS 
		D:/opencv/build/install/x64/vc14/bin
		D:/opencv/build/install/x64/vc14/lib
	)
IF (CMAKE_BUILD_TYPE MATCHES Debug )
	set(OPENCV_LIBS
...
	)
ELSEIF (CMAKE_BUILD_TYPE MATCHES Release)
	set(OPENCV_LIBS
		opencv_world400
	)
ENDIF () 
```
```
set(OPENCV_INCLUDE_DIRS
		C:/opencv-4.0.0/build/include
		C:/opencv-4.0.0/build/include/opencv
	)
set(OPENCV_LINK_DIRS 
		C:/opencv-4.0.0/build/x64/vc14/bin
		C:/opencv-4.0.0/build/x64/vc14/lib
	)
IF (CMAKE_BUILD_TYPE MATCHES Debug )
	set(OPENCV_LIBS
      .....
	)
ELSEIF (CMAKE_BUILD_TYPE MATCHES Release)
	set(OPENCV_LIBS
		opencv_aruco400
		opencv_bgsegm400
		opencv_bioinspired400
		opencv_calib3d400
		opencv_ccalib400
		opencv_core400
		opencv_datasets400
		opencv_dnn400
		opencv_dnn_objdetect400
		opencv_dpm400
		opencv_face400
		opencv_features2d400
		opencv_flann400
		opencv_fuzzy400
		opencv_gapi400
		opencv_hfs400
		opencv_highgui400
		opencv_imgcodecs400
		opencv_imgproc400
		opencv_img_hash400
		opencv_line_descriptor400
		opencv_ml400
		opencv_objdetect400
		opencv_optflow400
		opencv_phase_unwrapping400
		opencv_photo400
		opencv_plot400
		opencv_reg400
		opencv_rgbd400
		opencv_saliency400
		opencv_shape400
		opencv_stereo400
		opencv_stitching400
		opencv_structured_light400
		opencv_superres400
		opencv_surface_matching400
		opencv_text400
		opencv_tracking400
		opencv_video400
		opencv_videoio400
		opencv_videostab400
		opencv_viz400
		opencv_xfeatures2d400
		opencv_ximgproc400
		opencv_xobjdetect400
		opencv_xphoto400
	)
ENDIF () 
```

**Comment by lunasdejavu** [comment]
I tried 4.0.1 with opencv_contrib and the result is correct now, thank you all, you can close this issue.
