### ISSUE TITLE
'Undefined symbol: _ZN2cv6detail17check_failed_autoEmmRKNS0_12CheckContextE" error

### ISSUE THREAD

**Issue by yxchng** [opencv/opencv#13811]
What does this error 

"/home/xxx/git/opencv-3.4.5/build/install/lib/libopencv_imgcodecs.so.3.4: undefined symbol: _ZN2cv6detail17check_failed_autoEmmRKNS0_12CheckContextE."

mean? How should I debug it?

**Comment by WW2401** [comment]
Hi, do you solve it? I met the same problem. my opencv version 3.4.7
