### ISSUE TITLE
Imgcodecs_Image.read_write jp2 test failure (Linux, x86_64, Clang 7.0.1)

### ISSUE THREAD

**Issue by luiscarox** [opencv/opencv#13818]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Linux 64-bit (Ubuntu 18.04)
- Compiler => Clang 7.0.1

##### Detailed description

The following test in `imgcodecs` is failing:
```
[ RUN      ] imgcodecs/Imgcodecs_Image.read_write/3, where GetParam() = "jp2"
warning: empty layer generated
opencv/modules/imgcodecs/test/test_read_write.cpp:75: Failure
Expected: (psnr) > (thresDbell), actual: 13.2068 vs 32
warning: empty layer generated
opencv/modules/imgcodecs/test/test_read_write.cpp:93: Failure
Expected: (psnr) > (thresDbell), actual: 13.2068 vs 32
[  FAILED  ] imgcodecs/Imgcodecs_Image.read_write/3, where GetParam() = "jp2" (303 ms)
```

Other unit tests in that library pass just fine, and there don't seem to be any problems compiling opencv or other tests failing in other modules. 

The particular test does _not_ fail when compiling with GCC 8.2. 

##### Steps to reproduce

* Tested on both 4.0.1 and 3.4.5, same behavior
* Relevant cmake configuration: 
```
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/local/bin/clang++  (ver 7.0.1)
--   Media I/O: 
--     TIFF:                        build (ver 42 - 4.0.9)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
```

**Comment by alalek** [comment]
We can confirm this problem:
- master branch [builds](http://pullrequest.opencv.org/buildbot/builders/master_noICV-lin64-clang)
- 3.4 branch [builds](http://pullrequest.opencv.org/buildbot/builders/3_4_noICV-lin64-clang)

OpenCV uses "Jasper" for reading/writing of JPEG 2000 images. Unfortunately, Jasper project has not been developed/maintained anymore. So its support has been deprecated.

Consider building OpenCV with `-DBUILD_JASPER=OFF` CMake option.

More robust solution is making JPEG 2000 support via another library: [OpenJPEG](https://www.openjpeg.org/).

Relates #5849

**Comment by luiscarox** [comment]
Thanks a lot! 
I'll try those options.

**Comment by mshabunin** [comment]
Can not reproduce on Ubuntu 18.04 with Clang 10.0.0 and OpenCV _master_ branch.
@luiscarox , is this problem still actual?
