### ISSUE TITLE
Alternatives to GTK3-dev

### ISSUE THREAD

**Issue by ChernyshovYuriy** [opencv/opencv#13817]
Dear team,
Is there a way to use other libraries for GUI rather then GTK3-dev. 
For  reason I am not able to install any "dev" versions of GTK3/2, however, I do have GTK on linux:

apt-cache policy libgtk2.0-0 libgtk-3-0
libgtk2.0-0:
  Installed: 2.24.30-1ubuntu1.16.04.2
  Candidate: 2.24.30-1ubuntu1.16.04.2
  Version table:
 *** 2.24.30-1ubuntu1.16.04.2 500
        500 http://ubunturepo.gm.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.24.30-1ubuntu1 500
        500 http://ubunturepo.gm.com/ubuntu xenial/main amd64 Packages
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.3
  Candidate: 3.18.9-1ubuntu3.3
  Version table:
 *** 3.18.9-1ubuntu3.3 500
        500 http://ubunturepo.gm.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://ubunturepo.gm.com/ubuntu xenial/main amd64 Packages

Is there a way to use installed no-dev version or any other GUI framework?

**Comment by alalek** [comment]
Any other library require C/C++ headers, which are distributed via "-dev" packages.
Try to download and unpack "-dev" packages manually if you are not allowed to install them via regular way.
