### ISSUE TITLE
Holistically-Nested Edge Detection pre-trained model 404's

### ISSUE THREAD

**Issue by jrosebr1** [opencv/opencv#13815]
In the [HED example](https://github.com/opencv/opencv/blob/master/samples/dnn/edge_detection.py) there is the following:

```
parser = argparse.ArgumentParser(
        description='This sample shows how to define custom OpenCV deep learning layers in Python. '
                    'Holistically-Nested Edge Detection (https://arxiv.org/abs/1504.06375) neural network '
                    'is used as an example model. Find a pre-trained model at https://github.com/s9xie/hed.')
```

Unfortunately, the pre-trained model on https://github.com/s9xie/hed 404's (the original model link is http://vcl.ucsd.edu/hed/hed_pretrained_bsds.caffemodel). The prototxt files are no longer there as well.

Is there any other way to download the model? Perhaps an OpenCV user can upload their model?

If anyone can share the file with me I'd be happy to host it on the PyImageSearch blog.

**Comment by berak** [comment]
@jrosebr1: if anything else fails, i got a copy of the caffemodel

**Comment by jrosebr1** [comment]
Thank you so much @berak!

**Comment by dkurt** [comment]
It looks like the link is available again. Let me close this issue.

**Comment by CS-savvy** [comment]
where is the proto file??

**Comment by dkurt** [comment]
@CS-savvy, check https://github.com/s9xie/hed/blob/master/examples/hed/deploy.prototxt
