### ISSUE TITLE
Canny wrong detection on simple cases

### ISSUE THREAD

**Issue by alfatave** [opencv/opencv#13813]
##### System information (version)
- OpenCV => 2.4.9.1
- Operating System / Platform =>Ubuntu 16.04 64 bit
- Compiler => Qt Creator

##### Detailed description

By using canny edge detector in a very simple case the top-left corner is not detected properly, there are few differences with the findContours function as reported in the following pictures.

I'm not sure that canny works in the same way on more complicate images since it's dificult to check it.

Thank you!

![mask](https://user-images.githubusercontent.com/5919216/52648432-d278d200-2ee6-11e9-89c7-ce7510c38df3.png)
![find_contours](https://user-images.githubusercontent.com/5919216/52648438-d6a4ef80-2ee6-11e9-87da-07a49cf9feaf.png)
![canny](https://user-images.githubusercontent.com/5919216/52648437-d60c5900-2ee6-11e9-8c33-7ffd0bcb2fd3.png)

##### Steps to reproduce

`
            cv::Mat sourceImage = cv::Mat(20,20,CV_8U,cv::Scalar(128));
            cv::namedWindow("INPUT",CV_WINDOW_KEEPRATIO);
            cv::imshow("INPUT",sourceImage);
            cv::waitKey(100);

    int aa = 10;
    int bb = 15;

    std::vector<std::vector<cv::Point>> contours;

    std::vector<cv::Point> contour;

    cv::Point tmp;
    tmp.x = aa;
    tmp.y = aa;
    contour.push_back(tmp);

    tmp.x = aa;
    tmp.y = bb;
    contour.push_back(tmp);

    tmp.x = bb;
    tmp.y = bb;
    contour.push_back(tmp);

    tmp.x = bb;
    tmp.y = aa;
    contour.push_back(tmp);

    contours.push_back(contour);

    // DRAW COUNTORS
    cv::Mat mask = cv::Mat(sourceImage.rows,sourceImage.cols,CV_8U,cv::Scalar(0));
    cv::drawContours(mask,contours,0,cv::Scalar(255),CV_FILLED);
    std::cout << "MASK" << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    std::cout << mask << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    cv::namedWindow("MASK",CV_WINDOW_KEEPRATIO);
    cv::imshow("MASK",mask);
    cv::waitKey(100);

    // CANNY
    cv::Mat cannyEdges;
    cv::Canny(mask,cannyEdges,0,0);
    std::cout << "cannyEdges" << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    std::cout << cannyEdges << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    cv::namedWindow("CANNY",CV_WINDOW_KEEPRATIO);
    cv::imshow("CANNY",cannyEdges);
    cv::waitKey(100);

    // FIND_CONTOURS
    std::vector<std::vector<cv::Point>> contoursComputed;
    cv::findContours(mask,contoursComputed,CV_RETR_EXTERNAL, CV_CHAIN_APPROX_NONE);
    cv::Mat mask2 = cv::Mat(sourceImage.rows,sourceImage.cols,CV_8U,cv::Scalar(0));
    cv::drawContours(mask2,contoursComputed,0,cv::Scalar(255),1);
    std::cout << "FIND_CONTOURS" << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    std::cout << mask2 << std::endl;
    std::cout << "---------------------------------------------" << std::endl;
    cv::namedWindow("FIND_CONTOURS",CV_WINDOW_KEEPRATIO);
    cv::imshow("FIND_CONTOURS",mask2);
    cv::waitKey(100);
`

**Comment by pdvelez** [comment]
If you increase the sobel aperture to 7 (max value) you will be able to get the top-left corner.
`cv::Canny(mask,cannyEdges,0,0,7);`

**Comment by sturkmen72** [comment]
outdated common question can be closed down.
