### ISSUE TITLE
tf_text_graph_ssd.py have generated pbtxt file but load to test error

### ISSUE THREAD

**Issue by stq054188** [opencv/opencv#13827]
At this issue tf_text_graph_ssd.py #11560 
https://github.com/opencv/opencv/issues/11560

[#11560 (comment)](https://github.com/opencv/opencv/issues/11560#issuecomment-391047037)

@dkurt When I use your code, I can successfully generate pbtxt file, but when I use opencv to call it the following error occurs,

[libprotobuf ERROR c:\build\master_winpack-build-win64-vc15\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 45167:5: Unknown enumeration value of "20" for field "type".
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.0) Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: ./model_fpn/graph.pbtxt) in cv::dnn::ReadTFNetParamsFromTextFileOrDie, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\tensorflow\tf_io.cpp, line 54

`String weights = "./model_fpn/frozen_inference_graph.pb"; String prototxt = "./model_fpn/graph.pbtxt"; dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);`

Please help me, thanks

**Comment by dkurt** [comment]
@stq054188, For any mentioned file you need to add a link so we can download it and reproduce. At least the origin of `frozen_inference_graph.pb`.

**Comment by stq054188** [comment]
> o we can download it and reproduce. At _le




_

Thank you for your reply, my pb file zip is 38M can not be uploaded...

**Comment by stq054188** [comment]
> @stq054188, For any mentioned file you need to add a link so we can download it and reproduce. At least the origin of `frozen_inference_graph.pb`.

Thank you for your reply, but my pb file zip is 39
![00](https://user-images.githubusercontent.com/15775782/52781917-b319aa80-3088-11e9-831e-a0d48d9a81ba.JPG)



M can not be upload...

**Comment by dkurt** [comment]
@stq054188, 

> By the way, I can use my pb file get right result, thanks. @dkurt

Am I right that there is no problem anymore? If so, please close an issue.

**Comment by stq054188** [comment]
@dkurt I am Sorry, I mean that my Pb file can only run normally under Python tensorflow, but the OpenCV DNN module needs pbtxt configuration file. I generated the pbtxt file, but I met above error when using OpenCV DNN to read it.

**Comment by dkurt** [comment]
@stq054188, Please specify which TensorFlow's [config file](https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs) was used to train a network.

**Comment by stq054188** [comment]
@dkurt  I use the config "ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync.config" to train it. 
I also met same problem with issue tf_text_graph_ssd.py #11560 and I use following code to sort nodes 

`import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = TransformGraph(graph_def, ['image_tensor'], ['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'], ['sort_by_execution_order'])
    with tf.gfile.FastGFile('sorted_inference_graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())`

Then I use tf_text_graph_ssd.py to generate pbtxt file successfully, but use opencv dnn to read it error.
My opencv version is v4.0.0, thanks a lot.

**Comment by dkurt** [comment]
@stq054188, You didn't mention that model was trained for number of classes 1 that means you changed a [config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync.config) at least once.

Anyway I was able to generate a text graph adding `MultiscaleGridAnchorGenerator/` and `Concatenate/` to nodes prefixes which should be removed from graph:
```python
# Node with which prefixes should be removed
prefixesToRemove = ('MultiscaleGridAnchorGenerator/', 'Concatenate/', 'MultipleGridAnchorGenerator/', 'Postprocessor/', 'Preprocessor/map')
```
May I ask you to add a config file which was used for training so we can fix a script in the master branch. Thanks!

![out](https://user-images.githubusercontent.com/25801568/52843580-99717500-3113-11e9-9428-8851ee2b36f0.jpg)

**Comment by stq054188** [comment]
@dkurt  Thank you so much! Here is my config file https://github.com/stq054188/zip/blob/master/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync.config.

**Comment by dkurt** [comment]
Try to modify a script from the same version as OpenCV. Or update OpenCV. For now it looks like you just copy-pasted it from master branch.

**Comment by stq054188** [comment]
@dkurt Okay, I Will change to OpenCV4.0.1 and try again. I am using OpenCV 4.0.0 now, is OpenCV 4.0.1 had repaired the issue #11560?

**Comment by stq054188** [comment]
@dkurt 
When I changed to OpenCV4.0.1 and changed it same, it showed previous error,
modify it one by one seemed difficultly to me. Can you upload it to me, thanks.

ssd_anchor_generator = config['anchor_generator'][0]['ssd_anchor_generator'][0]
KeyError: 'ssd_anchor_generator'

**Comment by dkurt** [comment]
@stq054188, there is no such line at the master branch: https://github.com/opencv/opencv/blob/4ae5df550995467384fddd80f8a5955ad026d84c/samples/dnn/tf_text_graph_ssd.py#L83-L84

**Comment by stq054188** [comment]
@dkurt I have Re-Download the master branch and generated pbtxt file, but call it with error again:

C++
OpenCV(4.0.0) Error: Assertion failed (inputs[0] == inputs[i]) in cv::dnn::EltwiseLayerImpl::getMemoryShapes, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\layers\eltwise_layer.cpp, line 115

Python:
   cvOut = cvNet.forward()
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\eltwise_layer.cpp:115: error: (-215:Assertion failed) inputs[0] == inputs[i] in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'

**Comment by dkurt** [comment]
@stq054188, `OpenCV(4.0.0)` shows that your version of OpenCV is not the latest one. You need to do it at the same time:
1. Update OpenCV (pull the latest master branch) and rebuild libraries
2. Modify a python script from the same source code directory which was used for building

**Comment by stq054188** [comment]
@dkurt I have rebuilt opencv with this link:
https://github.com/opencv/opencv/tree/4ae5df550995467384fddd80f8a5955ad026d84c
but，it showed same error again...

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.5-dev) Error: Assertion failed (inputs[0] == inputs[i]) in cv::dnn::EltwiseLayerImpl::getMemoryShapes, file F:\opencv_master\modules\dnn\src\layers\eltwise_layer.cpp, line 116

**Comment by stq054188** [comment]
@dkurt  Please help me see if my OpenCV version is up to date. Thank you.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by stq054188** [comment]
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\layers\eltwise_layer.cpp:116: error: (-215:Assertion failed) inputs[0] == inputs[i] in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'

This problem has been sovled! First, you need to make sure that your opencv version is consistent. Th
I solved it by changing the parameters from 300 to 640 because config is ssd_mobilenet_v1_fpn_shared_box_predictor_**640x640**_coco14_sync.config
