### ISSUE TITLE
Can not import Opencv-android-sdk 4.0.1 into android studio

### ISSUE THREAD

**Issue by tiensu** [opencv/opencv#13829]
I tried to import opencv-android-sdk version 4.0.1 into Android Studio but not successful.
Android Studio can not recognize library name.
I wrote lib name manually, but when build it appeared error: 'Cannot resolve symbol styleable'
I resolved by following the solution: 
https://stackoverflow.com/questions/54206335/android-studio-and-opencv-compilation-error-cannot-resolve-symbol-styleable
But when run again, error is: "OpenCV was not initialised correctly. Application will be shutdown"
Can anyone help me the solution?
Thank you very much!

**Comment by GillianVanhaverbeke** [comment]
Why is this question invalid? I have the same question and non of the other solutions help me out..

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
