### ISSUE TITLE
Any plans on updating types.proto Tensorflow

### ISSUE THREAD

**Issue by balachandarsv** [opencv/opencv#13821]
Do we have any plans to update the types.proto in https://github.com/opencv/opencv/blob/master/modules/dnn/src/tensorflow/types.proto to the latest version as in Tensorflow? 
I am trying to run Resnet18 on DNN.  Facing this issue "Unknown enumeration value of "DT_RESOURCE" for field "type"."  Will changing this fix the issue?

**Comment by alalek** [comment]
What is the meaning of `DT_RESOURCE`?
I believe there is no direct mapping into OpenCV types, so it can't be processed.
Consider changing your model instead with clear set of operations (where is link for model?).

Tensorflow file for reference:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/types.proto

**Comment by dkurt** [comment]
Can we reproduce this error? Please provide a reference to mentioned model.

**Comment by balachandarsv** [comment]
Sorry, I am not able to reproduce the same issue with that model. I made some changes I guess receiving some other error.  But i am able to generate similar issue with this model.
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz
I used the frozen graph and pbtxt which is available in the tar. 

```
[libprotobuf ERROR /opt/opencv4/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 113344:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.0.1) /opt/opencv4/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: /Users/bala/Desktop/ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'
]
```

**Comment by dkurt** [comment]
>  I used the frozen graph and pbtxt which is available in the tar.

@balachandarsv, Please follow a guide https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by balachandarsv** [comment]
Yes. Thanks. But the issue here is, the other model doesn't have the pipeline config file. I generated the pbtxt from the model itself. Which is causing similar issue. Anyways.  I will try to follow the above guide itself. Thanks again.

**Comment by dkurt** [comment]
@balachandarsv, If an archive which you download from TensorFlow Object Detection API's Model Zoo doesn't have a `pipeline.config` file - you may take it from https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs. But it's a good point, thank you! I'll update a wiki page.

**Comment by balachandarsv** [comment]
Thanks. Any guides for using object classification instead of detection? Say i have resnet or imagenet. I would like to classify object instead of detecting. All these configs are for detection. Do we have anything for classification as such?

**Comment by dkurt** [comment]
@balachandarsv, Use classification samples with `.pb` files only: [classification.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/classification.cpp) or [classification.py](https://github.com/opencv/opencv/blob/master/samples/dnn/classification.py). If you found a bug - report if here. For usage questions please got to a forum http://answers.opencv.org/.

**Comment by angyee** [comment]
@balachandarsv @alalek @dkurt  python3 mask_rcnn.py --mask-rcnn mask-rcnn-coco --image /home/deepedge/mask_rcnn-master/mask-rcnn-bottle-training-master/dataset/val/car39.jpg

[INFO] loading Mask R-CNN from disk...
[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 60540:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
Traceback (most recent call last):
File "mask_rcnn.py", line 48, in
net = cv2.dnn.readNetFromTensorflow(weightsPath, configPath)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: mask-rcnn-coco/dent.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'

tried to implement mask rcnn with my own generated .pb and .pbtxt same below then error ours

How to solve ?

https://www.pyimagesearch.com/2018/11/19/mask-r-cnn-with-opencv/
