### ISSUE TITLE
how to compile opencv_ffmpeg.dll

### ISSUE THREAD

**Issue by chinafzc** [opencv/opencv#13826]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

**Comment by chinafzc** [comment]
##System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

**Comment by kinchungwong** [comment]
It is not compiled; the dlls are downloaded to your computer by CMake scripts when you configure the project with CMake.

The reasons are mentioned here: https://github.com/opencv/opencv/blob/master/3rdparty/ffmpeg/readme.txt

Next time, please ask questions on http://answers.opencv.org .

**Comment by alalek** [comment]
Right, it is not compiled during OpenCV build process.
Scripts for building of these wrappers are here (check for other branches too): https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/master

**Comment by chinafzc** [comment]
> Right, it is not compiled during OpenCV build process.
> Scripts for building of these wrappers are here (check for other branches too): https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/master

thanks

**Comment by chinafzc** [comment]
> It is not compiled; the dlls are downloaded to your computer by CMake scripts when you configure the project with CMake.
> 
> The reasons are mentioned here: https://github.com/opencv/opencv/blob/master/3rdparty/ffmpeg/readme.txt
> 
> Next time, please ask questions on http://answers.opencv.org .

thanks for your suggestion，Iim sorry that I ask question first， next time， I will ask question http://answers.opencv.org
