### ISSUE TITLE
G-API: coverage run reaches 1 hour time limit (opencv_test_gapi)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#13828]
Since this [build](http://pullrequest.opencv.org/buildbot/builders/master_coverage-lin64-debug/builds/10720).

**Comment by dmatveev** [comment]
@alalek Recently we reduced our number of accuracy tests by 1/3 (from 30K to ~20K).

Can you please check if the problem still apply?

Also where one can find that coverage results? :)

**Comment by alalek** [comment]
Thank you!
Resolved (14 min + filtering out of 720p test cases - `[ SKIPSTAT ] TAG='size_hd' skip 5684 tests`)
Coverage results are available via URL link under "upload" step.
Last results are [here](http://pullrequest.opencv.org/buildbot/export/opencv_releases/master_coverage-lin64-debug/20190723-234201_10879/coverage_html/index.html) (these results will be purged in 14-30 days).
