### ISSUE TITLE
convertTo alpha and saturate_cast behaviour

### ISSUE THREAD

**Issue by ChristopheBraud** [opencv/opencv#13830]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 18.10 64 Bit
- Compiler => 8.2.0

##### Detailed description
Hi,
I am trying to make a code that convert image from 8U, 16U and 32S to 8U, 16U or 32S
To acheive this goal i use convertTo with an automatic alpha
alpha = (2^output_depth - 1) / (2^input_depth - 1) (if any depth is 32, set it to 31 because it is signed)
it works well but not in any case
I found two strange behaviour :
- It seems that alpha, although it's a double, is converted to a float (I try with a 16U to 32S converstion), (2³¹-1)/(2¹⁶-1) = 32768.49999237 but is rounded to 32768.5 with float format
- This bad ratio make result go over the 32S limit of 2 147 483 647 and saturate_cast (or other things in convertTo code) seems to not works correctly, so negative values appears

if I use 32768.49609375 in place of 32768.49999237 (witch is the "float floor" number) all works well.

##### Steps to reproduce

```cpp
Mat image16 = imread(/*16bits image*/);
Mat image32;
double alpha = (pow(2, 31) - 1) / (pow(2,16) - 1)
image16.convertTo(image32, CV32_S, alpha);
double min, max;
minmaxLoc(image32, &min, &max);
// min should be positive (it is not)
```

**Comment by alalek** [comment]
Are there any **real image processing use case** with requirement of such accuracy?

**Comment by ChristopheBraud** [comment]
For alpha, I undestand that nobody do that (but I think it is bad do ask for a double and make a float conversion after)
But for the saturate_cast problem it can append in other situations so it is more serious

**Comment by alalek** [comment]
> make a code that convert image

Try `normalize()`.

> double

It is done due API / ABI / portable bindings reasons.
For optimization reasons - internal computations can be performed in fp32.

If you want double computations then you can try this scheme:
16S -> convert to 64F -> scale in 64F -> convert to 32S

> saturate_cast problem

Please provide minimal complete reproducer.

**Comment by ChristopheBraud** [comment]
Here is the code :
```c++
#include <iostream>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

int main() {
  Mat input(2, 2, CV_16UC1);
  Mat output(2, 2, CV_32SC1);
  input.at<ushort>(0, 0) = 0;
  input.at<ushort>(0, 1) = 32768;
  input.at<ushort>(1, 0) = 65534;
  input.at<ushort>(1, 1) = 65535;
  double alpha = 32768.5;
  input.convertTo(output, CV_32S, alpha);
  cout << input << endl;
  cout << output << endl;
  return 0;
}
```

And the result:

```
[0, 32768;
 65534, 65535]
[0, 1073758208;
 2147450880, -2147483648]
```

**Comment by alalek** [comment]
Thank you for the code!

Mentioned problem comes from `cvRound()` call (it uses [`_mm_cvt_ss2si`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cvt_ss2si) intrinsic).
Input value is out of destination range, so "integer indefinite" is returned (`-2147483648 = 0x80000000`).

> the Integer Indefinite value is 80000000H (not a floating-point number, but it can be
the result of a conversion instruction from floating-point to integer).

[Intel Software Developer’s Manual's (SDM)](https://software.intel.com/en-us/articles/intel-sdm#combined)


---

For performance reasons we don't properly handle/define overflows/underflows and other out of range cases for CV_32S type.

**Comment by ChristopheBraud** [comment]
"It's not a bug, it's a feature" ... two times in a thread .... it's sad
I've put in place some work arround for my cases
@alalek Thank you for taking the time to read my report
