### ISSUE TITLE
Version Support for Opencl 1.1 Embeded Profile

### ISSUE THREAD

**Issue by pweaver** [opencv/opencv#13846]
Does opencv support Opencl Embedded Profile? This is unclear to me from both the documentation and the source code. I guess the bug would be either adding documentation and/or better cmake error checking.

**Comment by alalek** [comment]
There are no plans support OpenCL before 1.2.
"Full profile" is required (required online OpenCL compiler).

> better cmake error checking

Fell free to suggest patch via PR (we are not going to configure OpenCL 1.1 Embedded Profile to prepare that). But most part of checks are done during runtime (not compile/build-time).

**Comment by mirh** [comment]
There was work for this once upon a time tho #2069
And it doesn't seem to have been dumped.. albeit there's much more nowadays.

After a quick check the only non-1.1 function I could find was clCreateImage, which is pretty easy to adjust tbf. 
In turn, I guess if one's truly lucky the thing [could work](http://streamcomputing.eu/blog/2015-02-05/using-opencl-1-2-with-1-1-devices/) already even without changing headers or whatnot. 
Not sure though if embedded profile couldn't hide some issue in itself.
