### ISSUE TITLE
NEON not making a difference in RP3

### ISSUE THREAD

**Issue by Favi0** [opencv/opencv#13845]
Hello im new to opencv

i have installed opencv 3.4.5 , 4.0.0 in RP3 using this guide

https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/

im trying to run dnn module (yolodarknet) but im getting exactly same results after running with and without NEON and VFPU flags in the makes 

now a person have reached better results without the optimizations 

https://github.com/AlexeyAB/darknet/issues/2093#issuecomment-450171737

what am i doing wrong or how do i check ?

**Comment by Favi0** [comment]
according to this 

http://answers.opencv.org/question/203740/enabling-optimization-options-for-raspberry-pi-3-with-opencv-400/

the version is not picking a GCC option  -mcpu=cortex-a53 -mfpu=neon-fp-armv8

**Comment by mshabunin** [comment]
Duplicate of #13374

**Comment by kejriwalnishant1990** [comment]
@mshabunin : Enable neon is not improving performance of dnn module. I have enabled Neon from cmake.
Target device : aarch64
Opencv : 4.2.0

 CPU/HW features:
   Baseline:                    NEON FP16
    required:                  NEON
     disabled:                  VFPV3


Any suggestions?
