### ISSUE TITLE
Does dnn module support depthwise layer for mobilenet inference?

### ISSUE THREAD

**Issue by jinfagang** [opencv/opencv#13859]
As far as I know, experiments show that using depthwise layer for inference can be 5x faster than normal convolution. 

We can using caffe which contains depthwise layer to speed up, but does opencv dnn module support depthwise layer for now? If so, the inference speed would be faster much more.

Anyone could point me where can I found that layer and how to use it in order to load a caffe model contains mobilenets?

**Comment by dkurt** [comment]
Please do not use GitHub issues for questions. There is a forum for it: http://answers.opencv.org/questions/.

If you want to report a bug - follow an issue template.

**Comment by yiboliu31** [comment]
@jinfagang Hi , have you found the solution about your question?
Thanks.

**Comment by dkurt** [comment]
@yiboliu31, Question is incomplete. If you have a reproducer - please provide it in forum.

**Comment by 1343464520** [comment]
did you solve it? i also want to know how to do it. Thanks!
