### ISSUE TITLE
OpenCV DNN is slower than Tensorflow in object detection with Faster RCNN model

### ISSUE THREAD

**Issue by stq054188** [opencv/opencv#13862]
System information (version):

* OpenCV => 3.4.5-dev
* Python => 3.5.1
* Operating System / Platform => Windows 64 Bit
* Compiler => Visual Studio 2015

Detailed description:
When I do object detection, I use the same model (faster-rcnn) for recognition, Python tensorflow takes hundreds of milliseconds, but opencv DNN takes three seconds. Is it a bug of OpenCV?

![default](https://user-images.githubusercontent.com/15775782/53006587-724ad880-3470-11e9-8934-c13e2705e1f6.png)

@dkurt  The code I use and the test images / models are in the links below, thanks.
https://github.com/stq054188/OpenCV-DNN-and-Tensorflow-With-Faster-RCNN

**Comment by dkurt** [comment]
If it's a bug report it should follow our guidelines. There is no `frozen_inference_graph.pb` in your repo so nobody can reproduce this experiment.

**Comment by stq054188** [comment]
@dkurt  I am sorry, I have uploaded it. Please try it again, thanks. 
https://drive.google.com/file/d/1VM8nb9In2qafGb-IaO8HwVBIVmTufSqd/view?usp=sharing

**Comment by dkurt** [comment]
@stq054188, please provide system system configuration and TensorFlow version. Do you have some NVIDIA GPU which might be used by TensorFlow?

**Comment by stq054188** [comment]
@dkurt My Config is:
Windows10, CPU i7 8750H, 
TF Version=1.8.0(gpu),
GPU GTX 1070

**Comment by dkurt** [comment]
@stq054188, Currently OpenCV's dnn doesn't support NVIDIA GPUs backend (only using OpenCL). This is one of our future GSoC 2019 projects: https://github.com/opencv/opencv/wiki/GSoC_2019#idea-allow-the-opencv-deep-neural-net-module-dnn-to-work-with-gpus (if OpenCV org will be accepted).
