### ISSUE TITLE
cvHoughCircles error in iOS

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [opencv/opencv#13867]
OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /Users/alexandershishkov/dev/opencv2.4.9/opencv/modules/core/src/array.cpp, line 2482
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/alexandershishkov/dev/opencv2.4.9/opencv/modules/core/src/array.cpp:2482: error: (-206) Unrecognized or unsupported array type in function cvGetMat

**Comment by alalek** [comment]
> opencv2.4.9

Very old release.
Won't fix.

Also you report is not complete. There is no reproducer, so it is useless / invalid (follow the template).

**Comment by AlaeddineOuerteni** [comment]
Hello @alalek,

Thank you for your reply.

I can't use the new framework release for problem of architecture.

There's no solution to resolve this bug ?

Thank you

**Comment by alalek** [comment]
OpenCV uses exceptions for errors reporting in general. Message says that some unsupported input has been passed to OpenCV function. Correct this or not - nobody can't know this without reproducer.
