### ISSUE TITLE
SVM weights parameter not set

### ISSUE THREAD

**Issue by Alarty** [opencv/opencv#13863]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Windows
- Python => 3.6

##### Detailed description

For SVM, there is a class_weight parameter to balance the classes during training. It works in C++ but seems to be skipped in python. 

##### Steps to reproduce

http://answers.opencv.org/question/31805/svm-weights-parameter-not-set-through-python/

**Comment by berak** [comment]
you probably simply missed it (class weights are not mandatory, most use cases will work fine without !):

```
svm = cv2.ml.SVM_create()
data = np.eye(5,5)
labels = np.array([0,1,1,0,1],np.int32) # 2 unique classes

svm.setClassWeights(np.array([1.0, .5])) #  2 distinct weights
svm.getClassWeights()
# array([1. , 0.5])

svm.train(data, 0, labels)
```

**Comment by Alarty** [comment]
Hello,

This is what I tried in fact. With weights `[0,0.5]`, `[0,1]`, `[1,0]`... When using `svm.getClassWeights()`

**Comment by pwnorbitals** [comment]
Does it still reproduce on latest versions ? @Alarty
