### ISSUE TITLE
OpenCV dnn Load Quantized Tensorflow model?

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13872]
Is it possible to load quantized models into opencv at the moment?

I can load a model i trained with tensorflow, but once i quantize the weights, i get the following error:

OpenCV Error: Unspecified error (Unknown layer type Dequantize in op conv2d_1/kernel/read/_41__cf__41) in populateNet, file /home/zsolt/Downloads/dockerfile/opencv_complete/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1299

To me it looks like the "Dequantize" layer is not implemented yet (also I have not seen it in the docs). Is support for this planned in the future? Or How do other people deal with this?

**Comment by dkurt** [comment]
@peter197321, which version of TensorFlow is used? There is no "Unknown layer type" error message at TensorFlow importer since we introduced custom layers support: https://github.com/opencv/opencv/pull/11129.

**Comment by chandramoulirajagopalan** [comment]
Can I work on this ? Can someone help me out to contribute ?

**Comment by dkurt** [comment]
@peter197321, please provide a reproducer.

**Comment by dkurt** [comment]
Closing it due no response from author.
