### ISSUE TITLE
(Bug) Slower performance with DNN_TARGET_OPENCL backend as compared to DNN_TARGET_CPU with AMD GPU

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#13870]
##### System information (version)

- OpenCV => 4.0.1-dev(master)
- Operating System / Platform => Ubuntu 18.04.2 LTS
- Compiler => gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

##### Detailed description

Hello, @alalek @dkurt I'm experiencing significantly lower performance with `DNN_TARGET_OPENCL` backend as compared to `DNN_TARGET_CPU`  even on my powerful machine this time, with following CPU configuration:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          21
Model:               96
Model name:          AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
Stepping:            1
CPU MHz:             1596.160
CPU max MHz:         1800.0000
CPU min MHz:         1300.0000
BogoMIPS:            3593.11
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           96K
L2 cache:            1024K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb bpext ptsc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic vgif overflow_recov
```
and GPU configuration(Installed with **Latest AMD 18.20 pro drivers**) and `clinfo` output is:
[clinfo.txt](https://github.com/opencv/opencv/files/2883311/clinfo.txt)

and **Official Vulkan SDK** installed and `vulkinfo` as follows:
[vulk.txt](https://github.com/opencv/opencv/files/2883322/vulk.txt)

and **properly configured in OpenCV(Build Information)**:
[buildinfo.txt](https://github.com/opencv/opencv/files/2883353/buildinfo.txt)

##### Results

I'm experiencing the following results with the code given below:
- YOLOV3 model and config and `DNN_TARGET_OPENCL` backend:
```
abhishek@abhishek-HP-Pavilion-Notebook:~/Documents/yolo$ python3 yolo.py -i 1.jpg --yolo coco
[INFO] loading YOLO from disk...
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory 
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -66: CL_INVALID_COMPILER_OPTIONS
-cl-no-subgroup-ifp -D AMD_DEVICE

[INFO] YOLO took 39.520115 seconds
```
- YOLOV3 model and config and `DNN_TARGET_CPU` backend:
```
abhishek@abhishek-HP-Pavilion-Notebook:~/Documents/yolo$ python3 yolo.py -i 1.jpg --yolo coco
[INFO] loading YOLO from disk...
[INFO] YOLO took 3.267506 seconds
```

##### Steps to reproduce

I'm using `YOLOV3` pretrained model and config available here on there [website](https://pjreddie.com/darknet/yolo/) and code as below: 
[yolo.txt](https://github.com/opencv/opencv/files/2883334/yolo.txt)

I think this is a bug with AMD Drivers, Please Help Asap!

**Comment by dkurt** [comment]
OpenCL kernels are compiled. It's a bad idea to measure performance by a single forward pass. you need a warm-up run. Let me close this issue. Please use a forum instead http://answers.opencv.org/ for usage questions.

BTW, there is a performance tests: https://github.com/opencv/opencv/blob/master/modules/dnn/perf/perf_net.cpp. Try to use it first.

**Comment by abhiTronix** [comment]
@dkurt I understand but, the performance difference is almost 10x between `DNN_TARGET_OPENCL` backend as compared to `DNN_TARGET_CPU` backend, Isn't something is wrong? Also, others experiencing the same issue,  Kindly refer #13873

**Comment by dkurt** [comment]
@abhiTronix, please provide summary from `opencv_perf_dnn`.

**Comment by e9k** [comment]
Having the exact same issue
