### ISSUE TITLE
armv7 build with neon on error, and resize will be too slow

### ISSUE THREAD

**Issue by HaoLiuHust** [opencv/opencv#13886]
I am building opencv 3.4.1 with armv7 compiler, but below error will be occured just same as #10363 
```
-- FP16 is not supported by C++ compiler
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:412 (message):
  Required baseline optimization is not supported: NEON
  (CPU_BASELINE_REQUIRE=;NEON)
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:261 (include)
  CMakeLists.txt:519 (include)


-- Performing Test HAVE_CPU_BASELINE_FLAGS
-- Performing Test HAVE_CPU_BASELINE_FLAGS - Failed
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:459 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:264 (ocv_compiler_optimization_options)
  CMakeLists.txt:519 (include)
```
it will be ok if I set enable neon off, but it will be too slow on hisi3516cv500 chip(it takes seconds when resize an image), I also tried with opencv3.4.5, same error here.  
after some modification in cmakelist files, I opened neon on and build it successfully, but the speed of cv::resize is also very slow, it takes 10+s to resize a 1080p image to 480p. Really confused.

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org


> 3.4.1

You are trying to build old release (~1 year ago).

**Comment by HaoLiuHust** [comment]
I have also tried 3.4.5

**Comment by IvyGongoogle** [comment]
3.4.5 get works
