### ISSUE TITLE
/usr/bin/ld: cannot find -lopencv_gapi

### ISSUE THREAD

**Issue by samuelsandu** [opencv/opencv#13881]
Hi!

I tried the make a .cpp file and I got this error:
 ```
 /usr/bin/ld: cannot find -lopencv_gapi
  collect2: error: ld returned 1 exit status
  CMakeFiles/simpletest_raspicam_cv.dir/build.make:111: recipe for target 'simpletest_raspicam_cv' failed
 ```

- OpenCV => 3.4.5
- Operating System =>NOOBS
- Compiler => CMake

**Comment by berak** [comment]
* OpenCV => 3.4.5

the [gapi module](https://github.com/opencv/opencv/tree/master/modules/gapi) is exclusive to opencv4 / master branch, [the 3.4.5 release](https://github.com/opencv/opencv/tree/3.4.5/modules) does not have it at all !

**Comment by samuelsandu** [comment]
thanks for answer!
