### ISSUE TITLE
perf_test Buildbot report not understood

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#13885]
I don't know if it's the good procedure to open an issue for that but I try.
I have a problem with my pull request #13879
It fails because of perf_test, and I do not understand the error.
Can anyone help by pointing to a doc or some explanations of what I am supposed to do ?

**Comment by alalek** [comment]
PR-related questions should be asked via PR comments.

Wiki page: https://github.com/opencv/opencv/wiki/HowToUsePerfTests#how-to-update-perf-data
