### ISSUE TITLE
Use opencv's dnn(trained with tensorflow) api could decrease detect score?

### ISSUE THREAD

**Issue by bleedingfight** [opencv/opencv#13899]
# I use ssd_inception models trained single target's detection model
## My env:
- tensorflow1.8-gpu
- cuda 9.0
- cudnn 7.3
- CPU:E5
- GPU:GTX 1080x2
- os:Ubuntu16.0.4
## The result show
so I use tensorflow detect my image,I have get very good result and ervey target had been found(thr=0.4).
the image like this:
![tensorflow api](https://github.com/bleedingfight/opencv_test/blob/master/predict_result_tf_ssd_inception.png)
but I use opencv's dnn api detect the same image,the result is like this(thr=0.1):
![opencv](https://github.com/bleedingfight/opencv_test/blob/master/predict_opencvssd_inception.png)
The question is:
- Can the code of tf_text_graph_ssd.py in opencv's github generator graph.pbtxt decrease detect accuracy(some import op was delete?)?
- How to get the same result with use tensorflow?
- Is tf_text_graph_ssd.py operator some optimize op?

more infomation please check ![here](https://github.com/bleedingfight/opencv_test)

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
