### ISSUE TITLE
TFLite deep learning models

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#13918]
https://github.com/opencv/opencv/wiki/OE-35.-TFLite-support

---

##### Detailed description

Do a research how TFLite differs from origin TensorFlow models format. Can we enable it with current tf_importer or prepare a new one?

related: http://answers.opencv.org/question/209280/does-readnetfromtensorflow-support-tflite-format/

**Comment by chandramoulirajagopalan** [comment]
Can I work on this issue to add the feature to add .tflite files ?

**Comment by dkurt** [comment]
@chandramoulirajagopalan, For now there is no pull requests connected with this issue. Feel free to propose your solution.

**Comment by boulabiar** [comment]
is there any news on this feature?

**Comment by dkurt** [comment]
@boulabiar, There is no PR opened which refers to this issue that means you can be the first contributor to solve it.

**Comment by Gilf641** [comment]
Any updates on how to use TFlite models with OpenCV?

**Comment by dkurt** [comment]
@Gilf641, The problem is that TF introduces too much formats recently. Serving model, SavedModel, TFList, TFHub, Keras from TF 2.0 which is not compatible with Keras. Most of them are derived from frozen .pb graphs. So what is the source of your TFLite model?

**Comment by Gilf641** [comment]
Source of TFLite Model?* I didn't get you...

This is my code

`new_model= tf.keras.models.load_model(filepath="VGGFaceRecognition-Keras.h5")
tflite_converter = tf.lite.TFLiteConverter.from_keras_model(new_model)
tflite_model = tflite_converter.convert()
open("VGGFaceRecognition-Keras.tflite", "wb").write(tflite_model)`

**Comment by dkurt** [comment]
Got it. So why not to convert the `.h5` to a frozen `.pb` model?

**Comment by Gilf641** [comment]
@dkurt I've already converted .h5 file to .tflite file. But I'm facing issues while using OpenCV along with Tensorflow Lite model( .tflite file)... 
Are you suggesting this way of conversion( .h5  --> .pb --> .tflite )?

**Comment by dkurt** [comment]
@Gilf641,I mean you can just convert .h5 to .pb and load .pb file into OpenCV.

**Comment by Gilf641** [comment]
But that .pb file cannot be used on IOT Devices right? Specifically on Raspberry pi..
So I converted .h5 file to .tflite file.
But Thanks @dkurt, I mean I got your point!

**Comment by dkurt** [comment]
@Gilf641, That's probably about difference between TensorFlow and TensorFlo-Light. OpenCV has own implementations and does not depend on TensorFlow so you can just load a .pb file.

**Comment by Gilf641** [comment]
Okay then, I'll try that...
Thank you @dkurt!

**Comment by SunAriesCN** [comment]
Mark and trying to help this issue.

**Comment by leavittx** [comment]
Hi there! Any hints on using the following model? 
https://www.tensorflow.org/lite/models/segmentation/overview

**Comment by dkurt** [comment]
Hi!

Please try the following if you have TFLite model:
```
bazel run --config=opt //tensorflow/lite/toco:toco -- --input_file=model.tflite --output_file=graph.pb --input_format=TFLITE --output_format=TENSORFLOW_GRAPHDEF
```
(should be executed from TensorFlow source dir)

**Comment by samuraiexx** [comment]
It didn't work for google's media pipe models like hand landmark :/

**Comment by kurikabocya** [comment]
Please tflite on OpenCV!
GPU vs CPU is 8:1 on speed.
If OpenCV can read tflite, then we can use Edge for note pc

**Comment by dkurt** [comment]
@kurikabocya, have you tried a command from https://github.com/opencv/opencv/issues/13918#issuecomment-652399369?

**Comment by kurikabocya** [comment]
Sorry, not yet.
your mentioned "bazel run.."  ?

**Comment by dkurt** [comment]
@kurikabocya, yes. It's used to convert TFLite to a frozen TensorFlow graph.

**Comment by kurikabocya** [comment]
Excuse me, I have already have a frozen Tensorflow graph.
I want TFLite. 
Can the bazel run.. convert a frozen Tensorflow graph to TFLIte ?

**Comment by dkurt** [comment]
@kurikabocya, this is not OpenCV issue. OpenCV works with frozen graphs only.

**Comment by cansik** [comment]
Thank you @dkurt for guiding us, I am just documenting my findings:

For me the command to convert to model looks like this (bazel 3.7.2) (https://github.com/tensorflow/tensorflow/issues/23613):

```bash
bazel run -c opt //tensorflow/lite/toco:toco -- --input_file=palm_detection.tflite --output_file=graph.pb --input_format=TFLITE --output_format=TENSORFLOW_GRAPHDEF
```

Be aware that `--input_file` may require an absolute path to work!
But as other already found out, it won't just work with the mediapipe models:

```bash
2021-01-20 12:03:30.400421: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 193 operators, 379 arrays (0 quantized)
2021-01-20 12:03:30.403402: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 193 operators, 379 arrays (0 quantized)
2021-01-20 12:03:30.404268: F tensorflow/lite/toco/graph_transformations/resolve_constant_reshape.cc:36] Check failed: op->inputs.size() == 2 (1 vs. 2)
```

**Comment by SunAriesCN** [comment]
Hi all, there is a work, called [bazel-crosstools-compiler](https://github.com/Duan-JM/bazel-crosstools-compiler), here we done recently on raspberry pi for reference. The other choice on desktop is my [image-classifier](https://github.com/SunAriesCN/image-classifier).

**Comment by eltonfernando** [comment]
@dkurt  i'm trying to load the model *.pb file. but all opencv input options have input .pbtxt (file that contains text graph definition in protobuf format).  how can i generate this file?

**Comment by dkurt** [comment]
@eltonfernando, what do you mean by "all opencv input options"? `.pbtxt` is optional, just use `.pb` .

**Comment by eltonfernando** [comment]
@dkurt,   I have this error
model.save("my_mode")
cv2.dnn.readNetFromTensorflow("my_mode/saved_model.pb")

FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: my_mode/saved_model.pb in function 'ReadTFNetParamsFromBinaryFileOrDie'

Thanks for the answer.

**Comment by dkurt** [comment]
@eltonfernando, this is not a frozen model. Please take a look how to create a frozen graph from SavedModel: https://github.com/opencv/opencv/issues/16879#issuecomment-603416876 and https://github.com/opencv/opencv/issues/16582#issuecomment-603819498

**Comment by rossGardiner** [comment]
Addition of tflite inference would be useful! Particularly for inference on edge hardware!

**Comment by y9luiz** [comment]
> Thank you @dkurt for guiding us, I am just documenting my findings:
> 
> For me the command to convert to model looks like this (bazel 3.7.2) ([tensorflow/tensorflow#23613](https://github.com/tensorflow/tensorflow/issues/23613)):
> 
> ```shell
> bazel run -c opt //tensorflow/lite/toco:toco -- --input_file=palm_detection.tflite --output_file=graph.pb --input_format=TFLITE --output_format=TENSORFLOW_GRAPHDEF
> ```
> 
> Be aware that `--input_file` may require an absolute path to work! But as other already found out, it won't just work with the mediapipe models:
> 
> ```shell
> 2021-01-20 12:03:30.400421: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 193 operators, 379 arrays (0 quantized)
> 2021-01-20 12:03:30.403402: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 193 operators, 379 arrays (0 quantized)
> 2021-01-20 12:03:30.404268: F tensorflow/lite/toco/graph_transformations/resolve_constant_reshape.cc:36] Check failed: op->inputs.size() == 2 (1 vs. 2)
> ```

Using this approach I have this following error:

INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorflow/lite/toco/toco '--input_file=/home/luiz/Libraries/tensorflow/model.tflite' '--output_file=graph.pb' '--input_format=TFLITE' '--output_format=TENSORFLOW_GRINFO: Build completed successfully, 1 total action
2021-10-04 11:34:15.521981: F tensorflow/lite/toco/tflite/import.cc:216] Number of subgraphs in tflite should be exactly 1.
Aborted (core dumped)

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/wiki/OE-35.-TFLite-support

**Comment by dkurt** [comment]
Prepared proposal https://github.com/opencv/opencv/pull/23161.

**Comment by alalek** [comment]
Looks like test models from provided URLs are not frozen:

```
Model <Face Mesh (TFLite)>
  expect eb01d1d88c833aaea64c880506da72e4a4f43154
  catch [Errno 2] No such file or directory: 'tflite/face_landmark.tflite'
  creating directory: tflite
  hash check failed - downloading
  get https://storage.googleapis.com/mediapipe-assets/face_landmark.tflite
  200 OK [1.1848430633544922 Mb]
  progress > done
 file tflite/face_landmark.tflite
  expect eb01d1d88c833aaea64c880506da72e4a4f43154
  actual 68ce058d75e19680018be09eb4b08985aa44ded8
  renaming invalid file to tflite/face_landmark.tflite.invalid
Model <Face Detection (TFLite)>
  expect e8f749fafc23bb88daac85bc9f7e0698436f29a0
  catch [Errno 2] No such file or directory: 'tflite/face_detection_short_range.tflite'
  hash check failed - downloading
  get https://storage.googleapis.com/mediapipe-assets/face_detection_short_range.tflite
  200 OK [0.2190723419189453 Mb]
  progress > done
 file tflite/face_detection_short_range.tflite
  expect e8f749fafc23bb88daac85bc9f7e0698436f29a0
  actual ff34459e5dccaaccfff0ea3012f66c4ad44c6d3e
  renaming invalid file to tflite/face_detection_short_range.tflite.invalid
Model <Selfie Segmentation (TFLite)>
  expect 8d497f51bd678fa5fb95c3871be72eb5d722b831
  catch [Errno 2] No such file or directory: 'tflite/selfie_segmentation.tflite'
  hash check failed - downloading
  get https://storage.googleapis.com/mediapipe-assets/selfie_segmentation.tflite
  200 OK [0.23748779296875 Mb]
  progress > done
 file tflite/selfie_segmentation.tflite
  expect 8d497f51bd678fa5fb95c3871be72eb5d722b831
  actual 8d497f51bd678fa5fb95c3871be72eb5d722b831
Model <Hair Segmentation (TFLite)>
  expect bba28400dfc264b1ed7ee95df718fada1879644d
  catch [Errno 2] No such file or directory: 'tflite/hair_segmentation.tflite'
  hash check failed - downloading
  get https://storage.googleapis.com/mediapipe-assets/hair_segmentation.tflite
  200 OK [0.7444267272949219 Mb]
  progress > done
 file tflite/hair_segmentation.tflite
  expect bba28400dfc264b1ed7ee95df718fada1879644d
  actual bba28400dfc264b1ed7ee95df718fada1879644d
Following models have not been downloaded:
* tflite/face_landmark.tflite
* tflite/face_detection_short_range.tflite
```

Need to freeze models using commit SHA or releases tag.

**Comment by dkurt** [comment]
@alalek, thanks! Please take a look: https://github.com/opencv/opencv_extra/pull/1045
