### ISSUE TITLE
test_ml: ML_SVM.trainauto_sigmoid crash (Win64 Debug)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#13914]
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-win64-vc14-debug/builds/284) (Win64 MSVS2015 Debug)

**Comment by alalek** [comment]
Related: #13718

/cc @lochsh

**Comment by lochsh** [comment]
I can try to have a look at why this might be tonight -- it may well be related to my changes in #13718, but I assume these tests have run before now on those changes, so I wonder what might be causing it to go wrong now 🤔

**Comment by alalek** [comment]
Mentioned test has been added by this patch.
