### ISSUE TITLE
clCreateKernel replace with offline compilation

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13916]
Per OpenCV/DNN with OpenCL the clCreateKernel() in our GPU case is taking too long. So I would like to know if there is a way to avoid clCreateKernel() or to have offline cl_kernel compilation to minimize use of clCreateKernel().
Is somehow possible to have program cache where there are pre-compiled cl_kernels?

**Comment by alalek** [comment]
`clCreateKernel()` must be fast (there are no real reasons which make it slow).
`clBuildProgram()` can be slow, but its results are cached (by OpenCV and by some OpenCL implementations).

**Comment by peter197321** [comment]
in my case clCreateKernel() is too slow and as well prefer to use offline
compilation instead of in run-time (online).
What that cache realy means, the pre-compiled kernels are stored in cache
and then used in run-time? Can this contribute to overall speed-up?

**Comment by alalek** [comment]
> in my case clCreateKernel() is too slow

Won't fix. Fill bug for your OpenCL implementation instead.

> What that cache realy means

Closing...
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
