### ISSUE TITLE
dnn readNet fail to load resnet50

### ISSUE THREAD

**Issue by LJXLJXLJX** [opencv/opencv#13915]
- OpenCV == 3.4.3 (python)
- Operating System / Platform => Windows 64 Bit
- Compiler => python3.6

I tried to load the pb file with
 ```python
net=cv2.dnn.readNet 
```
but I failed.

The error message is：

> cv2.error: OpenCV(3.4.3) D:\Build\OpenCV\opencv-3.4.3\modules\dnn\src\tensorflow\tf_importer.cpp:994: error: (-215:Assertion failed) haveConst in function 'cv::dnn::experimental_dnn_34_v7::`anonymous-namespace'::TFImporter::populateNet'

Here is my [pb file](https://suall-my.sharepoint.com/:u:/g/personal/46093_officeent_top/EVjgVf4sEWJOmuIp_2ApXEUB_lWKf5nSVLyn4T1t_b0QIQ?e=smfktb).

Thanks!

**Comment by dkurt** [comment]
@LJXLJXLJX, please retry with newer version of OpenCV. It works for me with master branch:

```python
net = cv.dnn.readNet('out.pb')
inp = np.random.standard_normal([1, 3, 112, 112]).astype(np.float32)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net.setInput(inp)
out = net.forward()
```

**Comment by LJXLJXLJX** [comment]
> @LJXLJXLJX, please retry with newer version of OpenCV. It works for me with master branch:
> 
> ```python
> net = cv.dnn.readNet('out.pb')
> inp = np.random.standard_normal([1, 3, 112, 112]).astype(np.float32)
> net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
> net.setInput(inp)
> out = net.forward()
> ```

Thank you! opencv 4.0.1 works.
