### ISSUE TITLE
error: (-215:Assertion failed) ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0 in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by ArunGARV** [opencv/opencv#13923]
**System information (version)**
* OpenCV => 4.0 by pip install opencv-python
* Operating System / Platform =>Ubuntu 16.04
* Compiler => python2
* Deep Learning framework = > Tensorflow 1.12 GPU version

**Detailed description**
Iam using faster_rcnn_inception_v2_coco_2018_01_28 (pre trained) model and want to test in python with OpenCV dnn.readFromTensorflow but fail when I call "cvOut = cvNet.forward()"
error msg is as follow:

Traceback (most recent call last):
  File "Demo.py", line 23, in <module>
    cvOut = cvNet.forward()
cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:260: error: (-215:Assertion failed) ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0 in function 'getMemoryShapes'

**Code**

import numpy as np
import cv2 as cv

cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'Graph.pbtxt')

img = cv.imread('FaceSample.jpg',cv.IMREAD_GRAYSCALE)
#cvNet.setInput(cv.dnn.blobFromImage(img, 1.0/127.5, (300, 300), (127.5, 127.5, 127.5), swapRB=True, crop=False))
img = cv.resize(img,None,fx=0.5,fy=0.5)
cvNet.setInput(img)

cvOut = cvNet.forward()

for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.5:
        left = detection[3] * img.shape[1]
        top = detection[4] * img.shape[0]
        right = detection[5] * img.shape[1]
        bottom = detection[6] * img.shape[0]
        cv.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (0, 255, 0))

cv.imshow('img', img)
cv.waitKey

**Comment by dkurt** [comment]
```python
 #cvNet.setInput(cv.dnn.blobFromImage(img, 1.0/127.5, (300, 300), (127.5, 127.5, 127.5), swapRB=True, crop=False))
img = cv.resize(img,None,fx=0.5,fy=0.5)
cvNet.setInput(img)
```
network expect a 4D blob but not image

Please follow a sample as a reference: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

**Comment by ArunGARV** [comment]
cvNet.setInput(cv.dnn.blobFromImage(img, 1.0/127.5, (300, 300), (127.5, 127.5, 127.5), swapRB=True, crop=False))

NB:- This was commented by mistake.

 I tried by providing the blob of the image, but still isue persists

**Comment by dkurt** [comment]
@ArunGARV, 

```python
img = cv.imread('FaceSample.jpg',cv.IMREAD_GRAYSCALE)
```
You model works with grayscale images (1 channel) or with RGB?

**Comment by nilanbais** [comment]
I'm also having trouble with the "net.forward()" call.

**Detailed disciption**
I'm playing around with some object detection to get a better understanding of the whole application of DNN. I'm trying to get real-time object detection by using a webcam as video input, as a test signal for now. 

i've trained a NN on the MNIST dataset using keras.Sequential() and saved the fozen model as .pd. I'm using this frozen model to pass the frames through to get a detection. for this script I'm using the following as a reference: https://www.pyimagesearch.com/2017/09/18/real-time-object-detection-with-deep-learning-and-opencv/

**System information (version)**

- OpenCV == 3.4.4 (pip install opencv-python)
- Operating System/OS == Windows 10 x64-based
- Compiler == python3

**Full code**
```
from imutils.video import VideoStream
from imutils.video import FPS

import numpy as np
import argparse
import imutils
import time
import cv2
import os

root_dir = os.path.abspath('path\to\project')
protobuf_model_dir = os.path.join(root_dir, 'frozen_graph.pb')

# Initialize the list of class labels the model was trained to detect, then generate a set of
# bounding box colors each class.
CLASSES = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))

# Load our serialized model
print("[INFO] loading model...")
net = cv2.dnn.readNetFromTensorflow(protobuf_model_dir)

# Initialize the video stream, allow the camera sensor to warm up, and initialize the FPS counter
print("[INFO] starting the video stream...")
# cap = cv2.VideoCapture(0)
stream = VideoStream(scr=0)
stream.start()
time.sleep(2.0)
fps = FPS().start()

# Loop over the frame
while True:
    # grab the frame from the threaded video stream and resize it to have a minimun width of 400 pixels

    frame = stream.read()
    frame = imutils.resize(frame, width=400)
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)

    # grab the frame dimentions and convert ot to a blob

    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 0.007843, (300, 300), 127.5)

    # pass the blob through the network and obtain the detections and predictions
    net.setInput(blob)
    detections = net.forward()

    # loop over the detections
    for i in np.arange(0, detections.shape9[2]):
        # extract the confidence (i.e. probability) associated with the prediction
        confidence = detections[0, 0, i, 2]

        # filter out the weak detections by ensuring the confidence is greater than the minimum confidence
        if confidence > args["confidence"]:
            # extrect the index of the class label from the detections, then compute the
            # (x, y)-coordinates of the bounding box for the object.
            idx = int(detections[0, 0, i, 2])
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (start_x, start_y, end_x, end_y) = box.astype("int")

            # draw predictions on the frame
            label = "{0}: {1}%".format(CLASSES[idx], (confidence*100))
            cv2.rectangle(frame, (start_x, start_y), (end_x, end_y), COLORS[idx], 2)
            y = start_y - 15 if start_y - 15 > 15 else start_y + 15
            cv2.putText(frame, label, (start_x, y), cv2.FONT_HERSHEY_COMPLEX, 0.5, COLORS[idx], 2)

    # show the output
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF

    # if the q key is pressed, break the loop
    if key == ord('q'):
        print('[INFO] stopping the video stream...')
        break

    # update the FPS counter
    fps.update()

fps.stop()
print("[INFO] elapse time: {}".format(fps.elapsed()))
print("[INFO] approx. FPS: {}".format(fps.fps()))

# a bit of cleanup
stream.stop()
cv2.destroyAllWindows()
```

**Running the code gives the following Traceback:**
Traceback (most recent call last):
  File "C:\Users\NBais\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d17ae33c5b3a>", line 1, in <module>
    runfile('C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras/Test.py', wdir='C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras/Test.py", line 58, in <module>
    detections = net.forward()
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\dnn\src\layers\fully_connected_layer.cpp:154: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'cv::dnn::FullyConnectedLayerImpl::FullyConnected::run'

**Comment by yugesh-recursive** [comment]
> I'm also having trouble with the "net.forward()" call.
> 
> **Detailed disciption**
> I'm playing around with some object detection to get a better understanding of the whole application of DNN. I'm trying to get real-time object detection by using a webcam as video input, as a test signal for now.
> 
> i've trained a NN on the MNIST dataset using keras.Sequential() and saved the fozen model as .pd. I'm using this frozen model to pass the frames through to get a detection. for this script I'm using the following as a reference: https://www.pyimagesearch.com/2017/09/18/real-time-object-detection-with-deep-learning-and-opencv/
> 
> **System information (version)**
> 
> * OpenCV == 3.4.4 (pip install opencv-python)
> * Operating System/OS == Windows 10 x64-based
> * Compiler == python3
> 
> **Full code**
> 
> ```
> from imutils.video import VideoStream
> from imutils.video import FPS
> 
> import numpy as np
> import argparse
> import imutils
> import time
> import cv2
> import os
> 
> root_dir = os.path.abspath('path\to\project')
> protobuf_model_dir = os.path.join(root_dir, 'frozen_graph.pb')
> 
> # Initialize the list of class labels the model was trained to detect, then generate a set of
> # bounding box colors each class.
> CLASSES = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
> COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))
> 
> # Load our serialized model
> print("[INFO] loading model...")
> net = cv2.dnn.readNetFromTensorflow(protobuf_model_dir)
> 
> # Initialize the video stream, allow the camera sensor to warm up, and initialize the FPS counter
> print("[INFO] starting the video stream...")
> # cap = cv2.VideoCapture(0)
> stream = VideoStream(scr=0)
> stream.start()
> time.sleep(2.0)
> fps = FPS().start()
> 
> # Loop over the frame
> while True:
>     # grab the frame from the threaded video stream and resize it to have a minimun width of 400 pixels
> 
>     frame = stream.read()
>     frame = imutils.resize(frame, width=400)
>     frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
> 
>     # grab the frame dimentions and convert ot to a blob
> 
>     (h, w) = frame.shape[:2]
>     blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 0.007843, (300, 300), 127.5)
> 
>     # pass the blob through the network and obtain the detections and predictions
>     net.setInput(blob)
>     detections = net.forward()
> 
>     # loop over the detections
>     for i in np.arange(0, detections.shape9[2]):
>         # extract the confidence (i.e. probability) associated with the prediction
>         confidence = detections[0, 0, i, 2]
> 
>         # filter out the weak detections by ensuring the confidence is greater than the minimum confidence
>         if confidence > args["confidence"]:
>             # extrect the index of the class label from the detections, then compute the
>             # (x, y)-coordinates of the bounding box for the object.
>             idx = int(detections[0, 0, i, 2])
>             box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
>             (start_x, start_y, end_x, end_y) = box.astype("int")
> 
>             # draw predictions on the frame
>             label = "{0}: {1}%".format(CLASSES[idx], (confidence*100))
>             cv2.rectangle(frame, (start_x, start_y), (end_x, end_y), COLORS[idx], 2)
>             y = start_y - 15 if start_y - 15 > 15 else start_y + 15
>             cv2.putText(frame, label, (start_x, y), cv2.FONT_HERSHEY_COMPLEX, 0.5, COLORS[idx], 2)
> 
>     # show the output
>     cv2.imshow("Frame", frame)
>     key = cv2.waitKey(1) & 0xFF
> 
>     # if the q key is pressed, break the loop
>     if key == ord('q'):
>         print('[INFO] stopping the video stream...')
>         break
> 
>     # update the FPS counter
>     fps.update()
> 
> fps.stop()
> print("[INFO] elapse time: {}".format(fps.elapsed()))
> print("[INFO] approx. FPS: {}".format(fps.fps()))
> 
> # a bit of cleanup
> stream.stop()
> cv2.destroyAllWindows()
> ```
> 
> **Running the code gives the following Traceback:**
> Traceback (most recent call last):
> File "C:\Users\NBais\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 1, in
> runfile('C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras/Test.py', wdir='C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras')
> File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\plugins\python-ce\helpers\pydev_pydev_bundle\pydev_umd.py", line 197, in runfile
> pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
> File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\plugins\python-ce\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "C:/Users/NBais/Documents/NBais/Pers. documenten/Zelfstudie/Object detection/Keras/Test.py", line 58, in
> detections = net.forward()
> cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\dnn\src\layers\fully_connected_layer.cpp:154: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'cv::dnn::FullyConnectedLayerImpl::FullyConnected::run'

I also have the same problem did you solved it

**Comment by VITEK-THE-BEST** [comment]
did you manage to find a solution to the problem ? I have the same problem

**Comment by myothura2021** [comment]
I have this error!! Please help me.

cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\dnn\src\layers\fully_connected_layer.cpp:181: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'cv::dnn::FullyConnectedLayerImpl::FullyConnected::run'

**Comment by myothura2021** [comment]
I have the same error.@ArunGARV
Please help me.

cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\dnn\src\layers\fully_connected_layer.cpp:181: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'cv::dnn::FullyConnectedLayerImpl::FullyConnected::run'

**Comment by lix19937** [comment]
My valid method: 
```
// pervious 
Mat img = imread(imageFile, 1);

// after 
Mat img = imread(imageFile,0);
```
