### ISSUE TITLE
Compatibility with Cuda 10.1?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#13941]
Hi:

Trying to build the most recent OpenCV against **Cuda 10.1**, but failed with the following **ERROR** messages, which I guess is a **opencv~cuda version** compatibility issue?

```console
...../opencv/3rdparty/include/opencl/1.2
....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(176): error: identifier "shfl_up_sync" is undefined
          detected during instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=int]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(220): here

....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(183): error: identifier "shfl_up_sync" is undefined
          detected during instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=int]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(220): here

....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(189): error: identifier "shfl_up_sync" is undefined
          detected during instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=int]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(220): here

....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(176): error: identifier "shfl_up_sync" is undefined
          detected during:
            instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(458): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(cv::cudev::GlobPtr<T>, int, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(584): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(const cv::cudev::GlobPtr<T> &, int, int, cudaStream_t) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(614): here

....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(183): error: identifier "shfl_up_sync" is undefined
          detected during:
            instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(458): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(cv::cudev::GlobPtr<T>, int, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(584): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(const cv::cudev::GlobPtr<T> &, int, int, cudaStream_t) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(614): here

....../opencv_contrib/modules/cudev/include/opencv2/cudev/warp/detail/../../warp/shuffle.hpp(189): error: identifier "shfl_up_sync" is undefined
          detected during:
            instantiation of "T cv::cudev::compatible_shfl_up(T, uint, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(458): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(cv::cudev::GlobPtr<T>, int, int) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(584): here
            instantiation of "void cv::cudev::integral_detail::vertical_pass(const cv::cudev::GlobPtr<T> &, int, int, cudaStream_t) [with T=uint]" 
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp(614): here

6 errors detected in the compilation of "/tmp/tmpxft_0000180f_00000000-6_gpu_mat.cpp1.ii".
-- Removing ....../opencv/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o
/usr/bin/cmake -E remove ....../opencv/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o
CMake Error at cuda_compile_1_generated_gpu_mat.cu.o.Release.cmake:279 (message):
  Error generating file
  ....../opencv/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o


modules/core/CMakeFiles/opencv_core.dir/build.make:497: recipe for target 'modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.o' failed
make[2]: *** [modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.o] Error 1
make[2]: Leaving directory '....../opencv/build'
CMakeFiles/Makefile2:2147: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: Leaving directory '....../opencv/build'
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Cheers
Pei

**Comment by tompollok** [comment]
Dont know if its the actual problem but here a fix for Cuda 10.1 in pcl
Maybe its related

https://github.com/PointCloudLibrary/pcl/pull/2883

**Comment by jasjuang** [comment]
It's because cublas is missing in 10.1. See https://devtalk.nvidia.com/default/topic/1047981/cuda-setup-and-installation/cublas-for-10-1-is-missing/

**Comment by qc2105** [comment]
Have a look at these, might be helpful: 
1) [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
2) [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)

**Comment by jiapei100** [comment]
@qc2105 

You got the right answer... Thank you ...

**Comment by jasjuang** [comment]
@qc2105 @jiapei100 since you verified that solves it can you submit a PR so everyone can get the fix?

**Comment by nglee** [comment]
This might be a compiler specific issue. It seems that building with Visual Studio 2015 does not have this issue. (Tested with CUDA10.1 and 3.4 branch)

@jiapei100 Could you tell us the version of compiler you've used?

Meanwhile, the patch I've uploaded might be a fix. The patch effectively "moves down" the definition of `compatible_shfl_up` so that it comes after the declaration of `shfl_up_sync`.

[temp.patch.zip](https://github.com/opencv/opencv/files/2921460/temp.patch.zip)

**Comment by jiapei100** [comment]
@jasjuang 
Yes, I should be more responsible... The pull request is at

[https://github.com/opencv/opencv_contrib/pull/2022/commits/3c76ec2dee90f1253c225cbf28c42a97b0c5e73c](https://github.com/opencv/opencv_contrib/pull/2022/commits/3c76ec2dee90f1253c225cbf28c42a97b0c5e73c) ..


I still have another issue right now, as referred by @alalek [https://github.com/opencv/opencv/issues/13952](https://github.com/opencv/opencv/issues/13952) ...

**Comment by qc2105** [comment]
> @qc2105 @jiapei100 since you verified that solves it can you submit a PR so everyone can get the fix?

Well, my changes are messy, but thanks for asking. I hope someday I can submit some some PRs.

**Comment by Adhders** [comment]
> Have a look at these, might be helpful:
> 
> 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
which version opencv_contrib did you use ? I use opencv_contrib-4.0.1, the content is not same as the answers show.

**Comment by qc2105** [comment]
the master branch, dev code

**Comment by Adhders** [comment]
> the master branch, dev code

My opencv is 4.01, why don't use opencv_contrib4.01?

**Comment by Adhders** [comment]
> Have a look at these, might be helpful:
> 
> 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8

> Have a look at these, might be helpful:
> 
> 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)



> the master branch, dev code

![image](https://user-images.githubusercontent.com/33727211/53720105-e33fb680-3e9a-11e9-877a-4f7e5a2121d8.png)
is that the dev code which you used?

**Comment by qc2105** [comment]
> > Have a look at these, might be helpful:
> > 
> > 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> > 2. [cvstd_wrapper.hpp]([qc2105@b32ba55](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
> 
> > Have a look at these, might be helpful:
> > 
> > 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> > 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
> 
> > the master branch, dev code
> 
> ![image](https://user-images.githubusercontent.com/33727211/53720105-e33fb680-3e9a-11e9-877a-4f7e5a2121d8.png)
> is that the dev code which you used?

Yes.

**Comment by Adhders** [comment]
> Have a look at these, might be helpful:
> 
> 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)

![image](https://user-images.githubusercontent.com/33727211/53727779-0161e280-3eac-11e9-976e-0faee2940b5b.png)
I have corrected my script as you say ,but the new issue  still exists.

**Comment by haijun-dgp** [comment]
fixed the scripts as suggested: got this error

![image](https://user-images.githubusercontent.com/33161305/53773070-e3e64600-3eb6-11e9-9111-d8f2cc88a23c.png)

**Comment by Adhders** [comment]
> Have a look at these, might be helpful:
> 
> 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)

can I read your cmake command? thanks ,here is my command
sudo cmake -D CMAKE_BUILD_TYPE=RELEASE \
 -D CMAKE_INSTALL_PREFIX=/u01/package       \
 -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON \
 -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules \
 -D PYTHON3_EXECUTABLE=/u01/anaconda3/bin/python3 \
 -D WITH_OPENMP=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_GTK=ON \
 -D WITH_OPENGL=ON -D BUILD_EXAMPLES=ON  -D WITH_CUDA=ON \
 -D WITH_CUBLAS=ON -D WITH_NVCUVID=ON  \
 -D CPU_BASELINE=AVX2 -D BUILD_TIFF=ON \
 -D INSTALL_PYTHON_EXAMPLES=ON ..\

**Comment by Adhders** [comment]
> > Have a look at these, might be helpful:
> > 
> > 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> > 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
> 
> can I read your cmake command? thanks ,here is my command
> sudo cmake -D CMAKE_BUILD_TYPE=RELEASE 
> -D CMAKE_INSTALL_PREFIX=/u01/package 
> -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON 
> -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules 
> -D PYTHON3_EXECUTABLE=/u01/anaconda3/bin/python3 
> -D WITH_OPENMP=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_GTK=ON 
> -D WITH_OPENGL=ON -D BUILD_EXAMPLES=ON -D WITH_CUDA=ON 
> -D WITH_CUBLAS=ON -D WITH_NVCUVID=ON 
> -D CPU_BASELINE=AVX2 -D BUILD_TIFF=ON 
> -D INSTALL_PYTHON_EXAMPLES=ON ..\

now，all the configure of my opencv is the same with you ,whereas I build unsuccessfully.  I guess maybe my CMake command has problem!

**Comment by Adhders** [comment]
> > > Have a look at these, might be helpful:
> > > 
> > > 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> > > 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
> > 
> > 
> > can I read your cmake command? thanks ,here is my command
> > sudo cmake -D CMAKE_BUILD_TYPE=RELEASE
> > -D CMAKE_INSTALL_PREFIX=/u01/package
> > -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON
> > -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules
> > -D PYTHON3_EXECUTABLE=/u01/anaconda3/bin/python3
> > -D WITH_OPENMP=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_GTK=ON
> > -D WITH_OPENGL=ON -D BUILD_EXAMPLES=ON -D WITH_CUDA=ON
> > -D WITH_CUBLAS=ON -D WITH_NVCUVID=ON
> > -D CPU_BASELINE=AVX2 -D BUILD_TIFF=ON
> > -D INSTALL_PYTHON_EXAMPLES=ON ..\
> 
> now，all the configure of my opencv is the same with you ,whereas I build unsuccessfully. I guess maybe my CMake command has problem!

<img width="941" alt="error" src="https://user-images.githubusercontent.com/33727211/53794634-57498f80-3f6b-11e9-89af-fe47d8d61799.png">

**Comment by qc2105** [comment]
> > > > Have a look at these, might be helpful:
> > > > 
> > > > 1. [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
> > > > 2. [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
> > > 
> > > 
> > > can I read your cmake command? thanks ,here is my command
> > > sudo cmake -D CMAKE_BUILD_TYPE=RELEASE
> > > -D CMAKE_INSTALL_PREFIX=/u01/package
> > > -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON
> > > -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules
> > > -D PYTHON3_EXECUTABLE=/u01/anaconda3/bin/python3
> > > -D WITH_OPENMP=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_GTK=ON
> > > -D WITH_OPENGL=ON -D BUILD_EXAMPLES=ON -D WITH_CUDA=ON
> > > -D WITH_CUBLAS=ON -D WITH_NVCUVID=ON
> > > -D CPU_BASELINE=AVX2 -D BUILD_TIFF=ON
> > > -D INSTALL_PYTHON_EXAMPLES=ON ..\
> > 
> > 
> > now，all the configure of my opencv is the same with you ,whereas I build unsuccessfully. I guess maybe my CMake command has problem!
> 
> <img alt="error" width="941" src="https://user-images.githubusercontent.com/33727211/53794634-57498f80-3f6b-11e9-89af-fe47d8d61799.png">

1) I haven't seen any errors on the picture you've uploaded, instead, I see warnings.
2) You can clone my forked source(both opencv and opencv_contrib) and try to build again. Or, switch back to the 3.4 branch, which runs well on my machine.
3) My environment is: GCC7.3.0/Ubuntu 18.04.2/CUDA 10.1/GeForce RTX 2080 Ti/NVIDIA 418.39.

**Comment by nareshganesan** [comment]
Hi @qc2105 ,

I'm able to compile OpenCV 3.4.6 version based on the above [instructions](https://github.com/opencv/opencv/issues/13941#issuecomment-469613070), from the forked [opencv](https://github.com/qc2105/opencv) [opencv_contrib](https://github.com/qc2105/opencv_contrib), still getting error when I run the gpu samples.

```bash
# Env:
OS: Ubuntu 18.04
CUDA: 10.1
NVIDIA driver: 435.21
GPU: 2080 Ti
GCC 7.4.0
```

Steps to reproduce
1. install CUDA 10.1
2. Copied: libcublas.so, libnvcuvid.so, libnvidia-encode.so and their sym links from **/usr/lib/x86_64-linux-gnu/** to **/usr/local/cuda-10.1/lib64/**
3. clone https://github.com/qc2105/opencv.git
4. clone https://github.com/qc2105/opencv_contrib.git
5. cd opencv && mkdir build && cd build
6. 
```bash
cmake \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=ON \
    -D BUILD_TIFF=ON \
    -D BUILD_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_OPENMP=ON \
    -D WITH_TBB=ON \
    -D WITH_V4L=ON \
    -D WITH_GTK=ON \
    -D WITH_OPENGL=ON \
    -D WITH_CUDA=ON \
    -D WITH_CUBLAS=ON \
    -D WITH_NVCUVID=ON \
    -D CPU_BASELINE=AVX2 \
    -D BUILD_opencv_cudacodec=ON \
    -D BUILD_EXAMPLES=ON \
    -D OPENCV_GENERATE_PKGCONFIG=YES ..
make -j$(nproc)
make install
ldconfig
```
7. cd to opencv/samples/gpu/
```bash
$ g++ -ggdb video_writer.cpp -o video_writer `pkg-config --cflags --libs opencv`

$ ./video_writer BigBuckBunny.mp4

Device 0:  "GeForce RTX 2080 Ti"  11016Mb, sm_75, Driver/Runtime ver.10.10/10.10
Read 1 frame
Frame Size : 1280x720
Open CPU Writer
Open CUDA Writer
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.6-dev) /opencv/modules/core/include/opencv2/core/private.cuda.hpp:113: error: (-213:The function/feature is not implemented) The called functionality is disabled for current build or platform in function 'throw_no_cuda'

Aborted (core dumped)
```  
Any help will be really useful. 
Thanks
Naresh Ganesan

**Comment by qc2105** [comment]
Hi @nareshganesan, my forked code is no longer maintained, please use the official code. I think they should support cuda 10.1 well now, and I don't have a Nvidia card powered computer at hand, sorrry bro.

**Comment by nareshganesan** [comment]
@qc2105 , I'll try the master branch and scout other issues for more details. Thanks for prompt response bro.

**Comment by FrancescoRossi1987** [comment]
> Hi @qc2105 ,
> 
> I'm able to compile OpenCV 3.4.6 version (also 4.1.1) based on the above [instructions](https://github.com/opencv/opencv/issues/13941#issuecomment-469613070), from the forked [opencv](https://github.com/qc2105/opencv) [opencv_contrib](https://github.com/qc2105/opencv_contrib), still getting error when I run the gpu samples.
> 
> ```shell
> # Env:
> OS: Ubuntu 18.04
> CUDA: 10.1
> NVIDIA driver: 435.21
> GPU: 2080 Ti
> GCC 7.4.0
> ```
> 
> ```shell
> # build information
> General configuration for OpenCV 3.4.6-dev =====================================
>   Version control:               3.4.4-788-ga9ab1309b
> 
>   Extra modules:
>     Location (extra):            /opencv_contrib/modules
>     Version control (extra):     3.4.4-67-ga475ef22
> 
>   Platform:
>     Timestamp:                   2019-09-25T12:29:09Z
>     Host:                        Linux 5.0.0-27-generic x86_64
>     CMake:                       3.10.2
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               RELEASE
> 
>   CPU/HW features:
>     Baseline:                    SSE SSE2 SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
>       requested:                 AVX2
>     Dispatched code generation:  AVX512_SKX
>       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
>       AVX512_SKX (2 files):      + AVX_512F AVX512_COMMON AVX512_SKX
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++11:                       YES
>     C++ Compiler:                /usr/bin/c++  (ver 7.4.0)
>     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffast-math -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mf16c -mfma -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -O3 -DNDEBUG  -DNDEBUG
>     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffast-math -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mf16c -mfma -mavx -mavx2 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -g  -O0 -DDEBUG -D_DEBUG
>     C Compiler:                  /usr/bin/cc
>     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffast-math -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mf16c -mfma -mavx -mavx2 -fvisibility=hidden -fopenmp -O3 -DNDEBUG  -DNDEBUG
>     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffast-math -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mf16c -mfma -mavx -mavx2 -fvisibility=hidden -fopenmp -g  -O0 -DDEBUG -D_DEBUG
>     Linker flags (Release):      -Wl,--gc-sections  
>     Linker flags (Debug):        -Wl,--gc-sections  
>     ccache:                      NO
>     Precompiled headers:         YES
>     Extra dependencies:          m pthread cudart_static -lpthread dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
>     3rdparty dependencies:
> 
>   OpenCV modules:
>     To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dpm face features2d flann freetype fuzzy hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
>     Disabled:                    world
>     Disabled by dependency:      -
>     Unavailable:                 cnn_3dobj cvv hdf java js matlab ovis python2 sfm viz
>     Applications:                tests perf_tests examples apps
>     Documentation:               NO
>     Non-free algorithms:         YES
> 
>   GUI: 
>     GTK+:                        YES (ver 3.22.30)
>       GThread :                  YES (ver 2.56.4)
>       GtkGlExt:                  NO
>     OpenGL support:              NO
>     VTK support:                 NO
> 
>   Media I/O: 
>     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
>     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
>     WEBP:                        build (ver encoder: 0x020e)
>     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
>     TIFF:                        build (ver 42 - 4.0.10)
>     JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
>     HDR:                         YES
>     SUNRASTER:                   YES
>     PXM:                         YES
> 
>   Video I/O:
>     DC1394:                      YES (ver 2.2.5)
>     FFMPEG:                      YES
>       avcodec:                   YES (ver 57.107.100)
>       avformat:                  YES (ver 57.83.100)
>       avutil:                    YES (ver 55.78.100)
>       swscale:                   YES (ver 4.8.100)
>       avresample:                NO
>     GStreamer:                   NO
>     libv4l/libv4l2:              NO
>     v4l/v4l2:                    linux/videodev2.h
> 
>   Parallel framework:            TBB (ver 2017.0 interface 9107)
> 
>   Trace:                         YES (with Intel ITT)
> 
>   Other third-party libraries:
>     Intel IPP:                   2019.0.0 Gold [2019.0.0]
>            at:                   /opencv/build/3rdparty/ippicv/ippicv_lnx/icv
>     Intel IPP IW:                sources (2019.0.0)
>               at:                /opencv/build/3rdparty/ippicv/ippicv_lnx/iw
>     Lapack:                      NO
>     Eigen:                       NO
>     Custom HAL:                  NO
>     Protobuf:                    build (3.5.1)
> 
>   NVIDIA CUDA:                   YES (ver 10.1, CUFFT CUBLAS FAST_MATH)
>     NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
>     NVIDIA PTX archs:
> 
>   OpenCL:                        YES (no extra features)
>     Include path:                /opencv/3rdparty/include/opencl/1.2
>     Link libraries:              Dynamic load
> 
>   Python 3:
>     Interpreter:                 /usr/bin/python3 (ver 3.6.8)
>     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.8)
>     numpy:                       /usr/local/lib/python3.6/dist-packages/numpy/core/include (ver 1.17.2)
>     install path:                lib/python3.6/dist-packages/cv2/python-3.6
> 
>   Python (for build):            /usr/bin/python2.7
> 
>   Java:                          
>     ant:                         NO
>     JNI:                         NO
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Install to:                    /usr/local
> -----------------------------------------------------------------
> ```
> 
> ### Steps to reproduce
> 1. install CUDA 10.1
> 2. Copied: libcublas.so, libnvcuvid.so, libnvidia-encode.so and their sym links from **/usr/lib/x86_64-linux-gnu/** to **/usr/local/cuda-10.1/lib64/**
> 3. clone https://github.com/qc2105/opencv.git
> 4. clone https://github.com/qc2105/opencv_contrib.git
> 5. cd opencv && mkdir build && cd build
> 
> ```shell
> cmake \
>     -D CMAKE_BUILD_TYPE=RELEASE \
>     -D CMAKE_INSTALL_PREFIX=/usr/local \
>     -D INSTALL_C_EXAMPLES=ON \
>     -D INSTALL_PYTHON_EXAMPLES=ON \
>     -D BUILD_opencv_python2=OFF \
>     -D BUILD_opencv_python3=ON \
>     -D BUILD_TIFF=ON \
>     -D BUILD_EXAMPLES=ON \
>     -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules \
>     -D OPENCV_ENABLE_NONFREE=ON \
>     -D ENABLE_FAST_MATH=1 \
>     -D CUDA_FAST_MATH=1 \
>     -D WITH_OPENMP=ON \
>     -D WITH_TBB=ON \
>     -D WITH_V4L=ON \
>     -D WITH_GTK=ON \
>     -D WITH_OPENGL=ON \
>     -D WITH_CUDA=ON \
>     -D WITH_CUBLAS=ON \
>     -D WITH_NVCUVID=ON \
>     -D CPU_BASELINE=AVX2 \
>     -D BUILD_opencv_cudacodec=ON \
>     -D BUILD_EXAMPLES=ON \
>     -D OPENCV_GENERATE_PKGCONFIG=YES ..
> make -j$(nproc)
> make install
> ldconfig
> ```
> 
> 1. cd to opencv/samples/gpu/
> 
> ```shell
> $ g++ -ggdb video_writer.cpp -o video_writer `pkg-config --cflags --libs opencv`
> 
> $ ./video_writer BigBuckBunny.mp4
> 
> Device 0:  "GeForce RTX 2080 Ti"  11016Mb, sm_75, Driver/Runtime ver.10.10/10.10
> Read 1 frame
> Frame Size : 1280x720
> Open CPU Writer
> Open CUDA Writer
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(3.4.6-dev) /opencv/modules/core/include/opencv2/core/private.cuda.hpp:113: error: (-213:The function/feature is not implemented) The called functionality is disabled for current build or platform in function 'throw_no_cuda'
> 
> Aborted (core dumped)
> ```
> 
> Any help will be really useful.
> Thanks
> Naresh Ganesan

Did you solved the issue?
I am not sure about this point:
_"Copied: libcublas.so, libnvcuvid.so, libnvidia-encode.so and their sym links from /usr/lib/x86_64-linux-gnu/ to /usr/local/cuda-10.1/lib64/"_
