### ISSUE TITLE
OpenCV-DNN with OpenCL - remove clCreateKernel() to be used for first NN execution only

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#13944]
Is it possible not to have `clCreateKernel()` function with OpenCV-DNN with OpenCL ([ocl.cpp](https://github.com/opencv/opencv/blob/master/modules/core/src/ocl.cpp#L2777)) for each iteration of NN execution is called? 

Actually one to call this `clCreateKernel()` only once as in first iteration only and achieve the [calling the same kernel object multiple times](https://forums.khronos.org/showthread.php/5810-calling-the-same-kernel-object-multiple-times) without `clCreateKernel()`

Is it such modification possible and not to break any other modules dependencies?

**Comment by alalek** [comment]
Keep similar discussions in one place: #13916

**Comment by peter197321** [comment]
What you mean by this? it's causing a significant problem and make DNN not
usebale ... so that's legitimate question?
