### ISSUE TITLE
ANN_MLP TermCriteria::COUNT will still terminate after default epsilon

### ISSUE THREAD

**Issue by WreckItTim** [opencv/opencv#13946]
##### System information (version)
- OpenCV => 3.4.2 and 4.0.1 
- Operating System / Platform => Mac 32 Bit and 64 Bit
- Compiler => Eclipse

##### Detailed description

When training an ANN_MLP, if you specify to terminate training after (cv::TermCriteria::COUNT) it will still terminate with (cv::TermCriteria::COUNT + cv::TermCriteria::EPS) using the default epsilon value.

##### Steps to reproduce

int nEpochs;
double epsilon;
cv::Ptr<<cv::ml::ann_mlp>> network = cv::ml::ANN_MLP::create(); 
network->setTermCriteria(cv::TermCriteria(cv::TermCriteria::COUNT, nEpochs, epsilon)); 
network->train(…);

This should terminate after nEpochs, however if the error drops below the default epsilon value, training will also terminate.

The problem is first found here in source code, when defining epsilon:
https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L867

Then later here, when terminating the training loop:
https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L949

I found this error when doing some benchmarks. I noticed after a certain amount of epochs, the training time would stagnate (it should increase when you increase the number of epochs).

There is a work around, if you set term criteria to COUNT + EPS and define epsilon = 0:
network->setTermCriteria(cv::TermCriteria(cv::TermCriteria::COUNT + cv::TermCriteria::EPS, nEpochs, 0));

However, according to the documentation, just using cv::TermCriteria::COUNT should suffice.

**Comment by npochhi** [comment]
We would have to set the DBL_EPSILON in https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L867 to DOUBLE_MAX, right? Or should we stop epsilon check?

**Comment by WreckItTim** [comment]
epsilon would just have to revert to a default value of zero if the user
specified COUNT

**Comment by WreckItTim** [comment]
That is if the user did not specify TermCriteria::EPS

**Comment by npochhi** [comment]
Ah, a brain freeze.. :sweat_smile: Sorry about that.

**Comment by WreckItTim** [comment]
Haha well it had to be either zero or max right :p
