### ISSUE TITLE
    import cv2 ImportError: /home/jacob/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/jacob/anaconda3/lib/python3.5/site-packages/cv2/python-3.5/cv2.cpython-35m-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by Jacob12138xieyuan** [opencv/opencv#13948]
import cv2
ImportError: /home/jacob/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/jacob/anaconda3/lib/python3.5/site-packages/cv2/python-3.5/cv2.cpython-35m-x86_64-linux-gnu.so)

**Comment by dkurt** [comment]
@Jacob12138xieyuan, please use a forum http://answers.opencv.org/ for questions. For now your issue doesn't look like a bug report according our guidelines (see template during issue creation).
