### ISSUE TITLE
opencv 4.0.0 + cuda10 build failed

### ISSUE THREAD

**Issue by Adhders** [opencv/opencv#13954]
Scanning dependencies of target opencv_cudaarithm
[ 30%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/core.cpp.o
[ 30%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/arithm.cpp.o
[ 30%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/reductions.cpp.o
[ 30%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/element_operations.cpp.o
[ 30%] Linking CXX shared library ../../lib/libopencv_cudaarithm.so
[ 30%] Built target opencv_cudaarithm
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Adhders** [comment]
sudo cmake -D CMAKE_BUILD_TYPE=RELEASE \
 -D CMAKE_INSTALL_PREFIX=/u01/package \
 -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=ON \
 -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.0.0/modules \
 -D PYTHON3_EXECUTABLE=/u01/anaconda3/bin/python3 \
 -D WITH_OPENMP=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_GTK=ON \
 -D WITH_OPENGL=ON -D BUILD_EXAMPLES=ON  -D WITH_CUDA=ON \
 -D WITH_CUBLAS=ON -D WITH_NVCUVID=ON -D WITH_LAPACK=ON \
 -D CPU_BASELINE=AVX2 -D BUILD_TIFF=ON -D WITH_VTK=ON
 -D BUILD_opencv_cudacodec=Off
 -D INSTALL_PYTHON_EXAMPLES=ON ..\

this my cmake list

**Comment by qc2105** [comment]
Have a look at these, might be helpful: 
1) [shfl_up_sync -> __shfl_up_sync](https://github.com/qc2105/opencv_contrib/commit/981165bcec5689c27322175d2d2ff9f6bbb80ceb)
2) [cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)
3) If you want to buid cudacodecc, take a look at comments on [https://github.com/opencv/opencv/issues/13897](https://github.com/opencv/opencv/issues/13897)
