### ISSUE TITLE
How to pass thresh and nms_threshold when loading YOLO v3?

### ISSUE THREAD

**Issue by liuyuns** [opencv/opencv#13963]
##### System information (version)

- OpenCV => 3.4.4
- Operating System / Platform => Windows 7
- Compiler => n/a

##### Detailed description

There is no way to pass thresh and nms when working with YOLO v3, in the setYolo method here:
https://github.com/opencv/opencv/blob/master/modules/dnn/src/darknet/darknet_io.cpp#L374

So It always use 0.2 as default thresh:
`thresh = params.get<float>("thresh", 0.2);`
in https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/region_layer.cpp#L72

and 0.4 as default nms_threshold:
`nmsThreshold = params.get<float>("nms_threshold", 0.4);`
in https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/region_layer.cpp#L72

##### Steps to reproduce

`net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)`

After read the net, it has 0.2 as default thresh and 0.4 as default nms_threshold, and we have no option to change that and so no way to evaluate a lower option.

Please kindly help.

**Comment by dkurt** [comment]
@liuyuns, Feel free to propose a PR. Ignoring `thresh` is a bug. Regarding `nms_threshold`, despite Darknet implementation has this value hardcoded (https://github.com/pjreddie/darknet/blob/810d7f797bdb2f021dbe65d2524c2ff6b8ab5c8b/examples/detector.c#L289), we also can read it from a `.cfg` file as well.
