### ISSUE TITLE
opencv-contrib-python 4.0.0 can not read caffe model and prototxt

### ISSUE THREAD

**Issue by jozhuzhu** [opencv/opencv#13961]
##### System information (version)

- OpenCV => :4.0.0.21:
- Operating System / Platform => : windows10:
- Compiler => :pre-build version from pip:

##### Detailed description
background: i wanna achieve opencv dnn model to detect face in an image
after accessing the model and prototxt from [opencv_extra/testdata/dnn/download_models.py](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py), i learned some sample code to test whether it works or not.  And then, I got the following info:

```
[libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:1: Invalid control characters encountered in text.
[libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:2: Interpreting non ascii codepoint 162.
[libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:2: Expected identifier, got: ?
Traceback (most recent call last):
  File "src/facedetect/detector.py", line 103, in <module>
    util.gainFaceByDNN(path, modelpath, deploypath)
  File "src/facedetect/detector.py", line 26, in gainFaceByDNN
    net = cv2.dnn.readNetFromCaffe(modelFile, configFile)
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: D:\project\python\IQA\src\facedetect\res10_300x300_ssd_iter_140000.caffemodel in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'
```
i have tried to google error, and got some solutions to try but they all failed, including checking the invisible content of the deploy.prototxt, redownload the files, etc. 
##### Steps to reproduce
below is the code i used for test and it goes wrong on the first code.
```
net = cv2.dnn.readNetFromCaffe(modelFile, configFile)
image = cv2.imread(imgPath)
(h, w) = image.shape[:2]

blob = cv2.dnn.blobFromImage(cv2.resize(image, (300,300)), 1.0, (300,300), (103.93, 116.77, 123.68), False)
net.setInput(blob)

detections = net.forward()
```

Is there any practical solutions ? thanks ~

**Comment by dkurt** [comment]
@jozhuzhu, arguments are in incorrect order:
```python
net = cv2.dnn.readNetFromCaffe(modelFile, configFile)
```
see https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga29d0ea5e52b1d1a6c2681e3f7d68473a

Change it to 
```python
net = cv2.dnn.readNetFromCaffe(configFile, modelFile)
```
or use [readNet](https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422) with any order.

**Comment by jozhuzhu** [comment]
thanks you very much!!!

**Comment by eliaed** [comment]
hello i also have a problem with the file pose_iter_160000.caffemodel" is failed.
the code is:
import cv2
import time
import numpy as np
protoFile = "pose/mpi/pose_deploy_linevec_faster_4_stages.prototxt"
weightsFile = "pose/mpi/pose_iter_160000.caffemodel"
nPoints = 15
POSE_PAIRS = [[0, 1], [1, 2], [2, 3], [3, 4], [1, 5], [5, 6], [6, 7], [1, 14], [14, 8], [8, 9], [9, 10], [14, 11],
              [11, 12], [12, 13]]

frame = cv2.imread("single.jpeg")
frameCopy = np.copy(frame)
frameWidth = frame.shape[1]
frameHeight = frame.shape[0]
threshold = 0.1

net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)

the failed message is:
[libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 7:1: Expected identifier, got: <
Traceback (most recent call last):
  File "C:/Users/elia/PycharmProjects/Image/test.py", line 16, in <module>
    net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: pose/mpi/pose_deploy_linevec_faster_4_stages.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'

 thank you!!!!!!!!!!

**Comment by noorkhokhar99** [comment]
> ##### System information (version)
> * OpenCV => :4.0.0.21:
> * Operating System / Platform => : windows10:
> * Compiler => :pre-build version from pip:
> 
> ##### Detailed description
> background: i wanna achieve opencv dnn model to detect face in an image
> after accessing the model and prototxt from [opencv_extra/testdata/dnn/download_models.py](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py), i learned some sample code to test whether it works or not. And then, I got the following info:
> 
> ```
> [libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:1: Invalid control characters encountered in text.
> [libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:2: Interpreting non ascii codepoint 162.
> [libprotobuf ERROR C:\projects\opencv-python\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 2:2: Expected identifier, got: ?
> Traceback (most recent call last):
>   File "src/facedetect/detector.py", line 103, in <module>
>     util.gainFaceByDNN(path, modelpath, deploypath)
>   File "src/facedetect/detector.py", line 26, in gainFaceByDNN
>     net = cv2.dnn.readNetFromCaffe(modelFile, configFile)
> cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: D:\project\python\IQA\src\facedetect\res10_300x300_ssd_iter_140000.caffemodel in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'
> ```
> 
> i have tried to google error, and got some solutions to try but they all failed, including checking the invisible content of the deploy.prototxt, redownload the files, etc.
> 
> ##### Steps to reproduce
> below is the code i used for test and it goes wrong on the first code.
> 
> ```
> net = cv2.dnn.readNetFromCaffe(modelFile, configFile)
> image = cv2.imread(imgPath)
> (h, w) = image.shape[:2]
> 
> blob = cv2.dnn.blobFromImage(cv2.resize(image, (300,300)), 1.0, (300,300), (103.93, 116.77, 123.68), False)
> net.setInput(blob)
> 
> detections = net.forward()
> ```
> 
> Is there any practical solutions ? thanks ~



you can try it.
pip install opencv-python==3.1.0.0

enjoy it!.

**Comment by Soumi7** [comment]
i get this error and it isnt resolved

**Comment by berak** [comment]
@Suomi7, please do not append to outdated and closed issues.

instead, ask on https://forum.opencv.org/, where we can help you much better
(given, you supply us opencv version, your code, a link to the model, the whole chi-chi...)

**Comment by mfahmifadh** [comment]
i've the same problem

my code

p```
rototxtPath = r"face_detector\deploy.prototxt"
weightsPath = r"face_detector\res10_300x300_ssd_iter_140000.caffemodel"
faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)

maskNet = load_model("mask_detector.model")
```

and i got error 

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13672/2145281415.py in <module>
     34 prototxtPath = r"face_detector\deploy.prototxt"
     35 weightsPath = r"face_detector\res10_300x300_ssd_iter_140000.caffemodel"
---> 36 faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
     37 
     38 maskNet = load_model("mask_detector.model")

error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1126: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "face_detector\deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'
```

i tried searching on google with the same problem, and i got problem in certain file. My python project file is in C:\Users\mfahm\anaconda3\Test. Am I getting the wrong filename?

**Comment by alalek** [comment]
> fs.is_open(). Can't open

Wrong path is specified. File is missing or no access rights.
(nothing to fix in OpenCV)

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by eliaed** [comment]
thank you !!

‫בתאריך יום ו׳, 26 בנוב׳ 2021 ב-7:34 מאת ‪Alexander Alekhin‬‏ <‪
***@***.***‬‏>:‬

**Comment by njwy1978** [comment]
I doenload "ResNet50_deploy.caffemodel" and "ResNet50_deploy.prototxt", then use the following code:
net = cv2.dnn.readNetFromCaffe(ResNet50_deploy.prototxt, ResNet50_deploy.caffemodel)
I got the eror:
FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: ./mobilenet_ssd/ResNet50_deploy.caffemodel in function 'cv::dnn::ReadNetParamsFromBinaryFileOrDie'
how can I solve this problem?

**Comment by feersdilaa** [comment]
hello sir, excuse me, can you help me?
here my code : 

import numpy as np
import cv2

prototxt_path = 'py/colorization_deploy_v2.prototxt'
model_path = 'py/colorization_release_v2.caffemodel'
kernel_path = 'py/pts_in_hull.npy'
image_path = 'tester.jpg'

net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path)
points = np.load(kernel_path)

points = points.transpose().reshape(2, 313, 1, 1)
net.getLayer(net.getLayerId("class_ab")).blobs = [points.astype(np.float)]
net.getLayer(net.getLayerId("conv8_313_rh")).blobs = [np.full([1, 313], 2.206, dtype="float32")]

bw_image = cv2.imread(image_path)
normalized = bw.image.astype("float32") / 255.0
lab = cv2.cvtCololr(normalized, cv2.COLOR_BGR2LAB)

resized = cv2.resize(lab, (224, 224))

L = cv2.split(resized)[0]
L -= 50

net.setInput(cv2.dnn.blobFromImage(L))
ab = net.forward()[0, :, :, :].transpose((1,2,0))

ab = cv2.resize(ab, (bw_image.shape[1], bw_image[0]))
L = cv2.split(lab)[0]

colorized = np.concatenate((L[:,:,np.newaxis], ab), axis=2)
colorized = cv2.cvtColor(colorized, cv.COLOR_BGR2LAB)
colorized = (255.0 * colorized).astype("uint8")

cv2.imshow("BW Image", bw_image)
cv2.imshow("Colorized", colorized)
cv2.waitKey(0)
cv2.destroyAllWindows()

and im got error : 

net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1126: error: (-2:Unspecified error) 
FAILED: fs.is_open(). Can't open "py/colorization_deploy_v2.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'


thankyou sir!

**Comment by ibtehajali67** [comment]
My problem is solved just updating the right path 
```
protoFile = "pose\mpi\pose_deploy_linevec_faster_4_stages.prototxt"
weightsFile = "pose\mpi\pose_iter_160000.caffemodel"
net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)

```

**Comment by Sayuksh** [comment]
can you guys help me with this ?

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
Cell In[19], line 1
----> 1 cvNet = cv2.dnn.readNetFromCaffe("weights (1).caffemodel")
      2 def getJSON(filePathandName):
      3     with open(filePathandName,'r') as f:

error: OpenCV(4.7.0) D:\bld\libopencv_1675730119851\work\modules\dnn\src\caffe\caffe_io.cpp:1162: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: weights (1).caffemodel in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'

**Comment by meaadMa** [comment]
> hello sir, excuse me, can you help me? here my code :
> 
> import numpy as np import cv2
> 
> prototxt_path = 'py/colorization_deploy_v2.prototxt' model_path = 'py/colorization_release_v2.caffemodel' kernel_path = 'py/pts_in_hull.npy' image_path = 'tester.jpg'
> 
> net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path) points = np.load(kernel_path)
> 
> points = points.transpose().reshape(2, 313, 1, 1) net.getLayer(net.getLayerId("class_ab")).blobs = [points.astype(np.float)] net.getLayer(net.getLayerId("conv8_313_rh")).blobs = [np.full([1, 313], 2.206, dtype="float32")]
> 
> bw_image = cv2.imread(image_path) normalized = bw.image.astype("float32") / 255.0 lab = cv2.cvtCololr(normalized, cv2.COLOR_BGR2LAB)
> 
> resized = cv2.resize(lab, (224, 224))
> 
> L = cv2.split(resized)[0] L -= 50
> 
> net.setInput(cv2.dnn.blobFromImage(L)) ab = net.forward()[0, :, :, :].transpose((1,2,0))
> 
> ab = cv2.resize(ab, (bw_image.shape[1], bw_image[0])) L = cv2.split(lab)[0]
> 
> colorized = np.concatenate((L[:,:,np.newaxis], ab), axis=2) colorized = cv2.cvtColor(colorized, cv.COLOR_BGR2LAB) colorized = (255.0 * colorized).astype("uint8")
> 
> cv2.imshow("BW Image", bw_image) cv2.imshow("Colorized", colorized) cv2.waitKey(0) cv2.destroyAllWindows()
> 
> and im got error :
> 
> net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path) cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1126: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "py/colorization_deploy_v2.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'
> 
> thankyou sir!

I faced the same problem previously and the solution was just to write the full path as:
PROTOTXT = 'C:\\Users\\LEGION\\Documents\\Meaad\\color\\colorization_deploy_v2.prototxt'
POINTS = 'C:\\Users\\LEGION\\Documents\\Meaad\\color\\pts_in_hull.npy'
