### ISSUE TITLE
Problem compiling opencv_contrib/modules/cudaimgproc/src/cuda/clahe.cu(128): error: identifier "PtrStepus" is undefined

### ISSUE THREAD

**Issue by pbuschmeyer** [opencv/opencv#13984]
OS: Ubuntu 16.04
CUDA 9.2
OpenCV-4.0.1

I'm sure this is a CMake setting issue, but I'm stuck and don't know what to do. 

It appears the datatypes "PtrStepus" and "PtrStepSzus" are not defined anywhere.

/home/ubuntu/OpenCV/opencv_contrib/modules/cudaimgproc/src/cuda/clahe.cu(128): error: identifier "PtrStepus" is undefined

/home/ubuntu/OpenCV/opencv_contrib/modules/cudaimgproc/src/cuda/clahe.cu(341): error: identifier "PtrStepSzus" is undefined

I would have thought these to be CUDA definitions, but I cannot find them anywhere.

 Any suggestions?

**Comment by nglee** [comment]
https://github.com/opencv/opencv/pull/13764#commitcomment-32313821

> You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

**Comment by wahyubram82** [comment]
Open CV 4.0.0
Windows 10
CUDA 10.1

same error...
 identifier "PtrStepSzus" is undefined

when i click to attach the source code, it referes to:
clahe.cu
line 128:
__global__ void calcLutKernel_16U(const PtrStepus src, PtrStepus lut,
                                      const int2 tileSize, const int tilesX,
                                      const int clipLimit, const float lutScale,
                                      PtrStepSzi hist)

where i can get PtrStepus src and PtrStepus lut
