### ISSUE TITLE
Pystasm fails to install from source with opencv4 

### ISSUE THREAD

**Issue by liobrando** [opencv/opencv#13981]
running install
running bdist_egg
running egg_info
writing PyStasm.egg-info/PKG-INFO
writing dependency_links to PyStasm.egg-info/dependency_links.txt
writing requirements to PyStasm.egg-info/requires.txt
writing top-level names to PyStasm.egg-info/top_level.txt
reading manifest file 'PyStasm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PyStasm.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'stasm._stasm' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c src/misc.cpp -o build/temp.linux-x86_64-3.6/src/misc.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c src/eyedet.cpp -o build/temp.linux-x86_64-3.6/src/eyedet.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c src/shape17.cpp -o build/temp.linux-x86_64-3.6/src/shape17.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c src/pinstart.cpp -o build/temp.linux-x86_64-3.6/src/pinstart.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c src/err.cpp -o build/temp.linux-x86_64-3.6/src/err.o
src/err.cpp:54:21: error: expected initializer before ‘CvErrorCallbackForStasm’
 static int CV_CDECL CvErrorCallbackForStasm(
                     ^~~~~~~~~~~~~~~~~~~~~~~
src/err.cpp: In function ‘void stasm::CatchOpenCvErrs()’:
src/err.cpp:90:48: error: ‘CvErrorCallbackForStasm’ was not declared in this scope
     cv::ErrorCallback prev = cv::redirectError(CvErrorCallbackForStasm);
                                                ^~~~~~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by alalek** [comment]
Wrong repository.
