### ISSUE TITLE
OpenCV 4.0.0 dnn module with OpenBlas support for android applications

### ISSUE THREAD

**Issue by KMKnation** [opencv/opencv#13998]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Android
- Compiler => Cmake

##### Detailed description
https://github.com/opencv/opencv_contrib/issues/490 as per optimisation related changes implemented for x86 processor with the use of OpenCL and MKL Blas. Can i optimise the same dnn module with OpenBlas library for arm platforms?.

Because in my reading of the CMakeLists.txt, I came on to this line
```
OCV_OPTION(WITH_OPENCL "Include OpenCL Runtime support" (NOT ANDROID AND NOT CV_DISABLE_OPTIMIZATION)
VISIBLE_IF NOT IOS AND NOT WINRT
VERIFY HAVE_OPENCL)
```
which i think even if i turn on OPENCL flag from terminal, it will not gonna be accepted.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
