### ISSUE TITLE
Error while importing opencv

### ISSUE THREAD

**Issue by adityak2920** [opencv/opencv#14009]
I was installing opencv using [this](https://www.pyimagesearch.com/2018/08/17/install-opencv-4-on-macos/#comment-505686) tutorial but at last i am getting an error on importing opencv

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/adityakumar/.virtualenvs/cv/lib/python3.6/site-packages/cv2.so, 2): Symbol not found: __ZN2cv3dnn14dnn4_v201809175Layer10initHalideERKNSt3__16vectorINS_3PtrINS1_14BackendWrapperEEENS3_9allocatorIS7_EEEE
  Referenced from: /Users/adityakumar/.virtualenvs/cv/lib/python3.6/site-packages/cv2.so
  Expected in: /usr/local/lib/libopencv_dnn.4.0.dylib
 in /Users/adityakumar/.virtualenvs/cv/lib/python3.6/site-packages/cv2.so

**Comment by alalek** [comment]
Check #13991

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
