### ISSUE TITLE
Add Debug flag to Android SDK build

### ISSUE THREAD

**Issue by komakai** [opencv/opencv#14010]
##### System information (version)
- OpenCV => Latest
- Operating System / Platform => Android

##### Detailed description
In order to be able to debug while working on the Android platform there should be a build flag "--debug" that builds the OpenCV binaries with debug information. (Additionally this needs to suppress any build stages that strip out debug info).

I have a PR prepared for this.

**Comment by komakai** [comment]
Created PR #14011

**Comment by bommo1** [comment]
Could you add the possibility to make a release build but with debug symbols?
