### ISSUE TITLE
cv2.MORPH_HITMISS can't get the correct result in python.

### ISSUE THREAD

**Issue by Kogel9701** [opencv/opencv#14018]
I tried MORPH_HITMISS in python, but I can't get the correct result.
However, i tried again in C++ with the same parameter,  I can get the correct result.
I wonder if this function is working in python.

def hit_miss(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, bin = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
    cv2.imshow('bin2', bin)
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (11, 11))
    result = cv2.morphologyEx(bin, cv2.MORPH_HITMISS, kernel)
    cv2.imshow('hit', result)

Above is my test code in python.

System information (version)
OpenCV =>3.4.0.12
Operating System / Platform => Windows 8.1
Compiler =>pycharm

**Comment by saskatchewancatch** [comment]
Would you be able to upload the test image you used?

**Comment by Kogel9701** [comment]
![cross](https://user-images.githubusercontent.com/43124514/54256983-c3924780-4598-11e9-8d11-1b7fa4ffd981.JPG)

**Comment by saskatchewancatch** [comment]
Unfortunately I cannot try this in the Windows platform, but I was able to try it out in Ubuntu 18.04 with Python 2.7.

The final result I get doing the same operations as you did between c++ and the python bindings is the same. 

```
        Mat input = imread("/home/anon/cust.jpg");

        Mat gray;
        cvtColor(input, gray, COLOR_BGR2GRAY);

        Mat bin;
        threshold(gray, bin, 0, 255, THRESH_BINARY_INV | THRESH_OTSU);

        Mat kernel = getStructuringElement(MORPH_CROSS, Size(11, 11));

        Mat result;
        morphologyEx(bin, result, MORPH_HITMISS, kernel);
        imwrite("cpp_result.png", result);

```

Here is what I get out of that cpp code:

![cpp_result](https://user-images.githubusercontent.com/21051160/54326766-2f8ea300-45cd-11e9-827a-c9b3dcedb3db.png)

Curious, what output are you getting?

**Comment by Kogel9701** [comment]
![cross](https://user-images.githubusercontent.com/43124514/54328626-9c478300-4649-11e9-8118-48a4cbe9e84a.jpg)

That is what I got the output with my python code.
And when I use cpp code, I can get the result as same as yours.

However, I have a classmate, he use cpp code (same code, same image). He get nothing as same as me. But I don't know the opencv version he used.

So I wonder if there are a few version will occurr this bug.

Thanks for your help.

**Comment by alalek** [comment]
> 3.4.0

This release is outdated (>2 years).
There is no way to amend already released code. So please try latest code first from the maintenance branches (or at least the latest releases: 3.4.10 or 4.3.0).
