### ISSUE TITLE
Opencv 4.0.1 with Cuda 

### ISSUE THREAD

**Issue by jsemeda** [opencv/opencv#14017]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

compiling opencv with cuda fails .. 

##### Steps to reproduce
compiling the "opencv_core" module in debug x64
I applied the suggested changes in cvstd_wrapper.hpp mentioned in another issue

-->
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
2>------ Build started: Project: opencv_core_AVX, Configuration: Debug x64 ------
3>------ Build started: Project: opencv_core_AVX2, Configuration: Debug x64 ------
4>------ Build started: Project: opencv_core_SSE4_1, Configuration: Debug x64 ------
5>------ Build started: Project: opencv_core_SSE4_2, Configuration: Debug x64 ------
2>mathfuncs_core.avx.cpp
4>arithm.sse4_1.cpp
5>stat.sse4_2.cpp
3>arithm.avx2.cpp
3>mathfuncs_core.avx2.cpp
3>stat.avx2.cpp
2>opencv_core_AVX.vcxproj -> D:\Libraries\opencv-4.0.1-cuda\build\modules\core\opencv_core_AVX.dir\Debug\opencv_core_AVX.lib
5>opencv_core_SSE4_2.vcxproj -> D:\Libraries\opencv-4.0.1-cuda\build\modules\core\opencv_core_SSE4_2.dir\Debug\opencv_core_SSE4_2.lib
4>opencv_core_SSE4_1.vcxproj -> D:\Libraries\opencv-4.0.1-cuda\build\modules\core\opencv_core_SSE4_1.dir\Debug\opencv_core_SSE4_1.lib
3>opencv_core_AVX2.vcxproj -> D:\Libraries\opencv-4.0.1-cuda\build\modules\core\opencv_core_AVX2.dir\Debug\opencv_core_AVX2.lib
6>------ Build started: Project: opencv_core, Configuration: Debug x64 ------
6>opencv_core_pch.cpp
6>algorithm.cpp
6>arithm.cpp
6>arithm.dispatch.cpp
6>array.cpp
6>batch_distance.cpp
6>bindings_utils.cpp
6>channels.cpp
6>check.cpp
6>command_line_parser.cpp
6>conjugate_gradient.cpp
6>convert.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\conjugate_gradient.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\conjugate_gradient.cpp(199): note: see reference to function template instantiation 'cv::Ptr<cv::ConjGradSolverImpl> cv::makePtr<cv::ConjGradSolverImpl,>(void)' being compiled
6>convert_c.cpp
6>convert_scale.cpp
6>copy.cpp
6>count_non_zero.cpp
6>cuda_gpu_mat.cpp
6>cuda_host_mem.cpp
6>cuda_info.cpp
6>cuda_stream.cpp
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\cuda_host_mem.cpp(209): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\cuda_host_mem.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\cuda_host_mem.cpp(158): note: see reference to function template instantiation 'cv::Ptr<`anonymous-namespace'::HostMemAllocator> cv::makePtr<`anonymous-namespace'::HostMemAllocator,unsigned int>(const unsigned int &)' being compiled
6>datastructs.cpp
6>directx.cpp
6>downhill_simplex.cpp
6>dxt.cpp
6>gl_core_3_1.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\cuda_stream.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\cuda_stream.cpp(306): note: see reference to function template instantiation 'cv::Ptr<`anonymous-namespace'::StackAllocator> cv::makePtr<`anonymous-namespace'::StackAllocator,cudaStream_t>(const cudaStream_t &)' being compiled
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\downhill_simplex.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\downhill_simplex.cpp(458): note: see reference to function template instantiation 'cv::Ptr<cv::DownhillSolverImpl> cv::makePtr<cv::DownhillSolverImpl,>(void)' being compiled
6>glob.cpp
6>hal_internal.cpp
6>kmeans.cpp
6>lapack.cpp
6>lda.cpp
6>logger.cpp
6>lpsolver.cpp
6>lut.cpp
6>mathfuncs.cpp
6>mathfuncs_core.dispatch.cpp
6>matmul.cpp
6>matrix.cpp
6>matrix_decomp.cpp
6>matrix_c.cpp
6>matrix_expressions.cpp
6>matrix_iterator.cpp
6>matrix_operations.cpp
6>matrix_sparse.cpp
6>matrix_wrap.cpp
6>mean.cpp
6>merge.cpp
6>minmax.cpp
6>norm.cpp
6>ocl.cpp
6>opencl_clamdblas.cpp
6>opencl_clamdfft.cpp
6>opencl_core.cpp
6>opengl.cpp
6>out.cpp
6>ovx.cpp
6>parallel.cpp
6>parallel_impl.cpp
6>pca.cpp
6>persistence.cpp
6>persistence_json.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\out.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\out.cpp(298): note: see reference to function template instantiation 'cv::Ptr<cv::FormattedImpl> cv::makePtr<cv::FormattedImpl,char[2],char[2],cv::Mat,char*,bool,bool,int>(const char (&)[2],const char (&)[2],const cv::Mat &,char *const &,const bool &,const bool &,const int &)' being compiled
6>persistence_types.cpp
6>persistence_xml.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_json.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_json.cpp(852): note: see reference to function template instantiation 'cv::Ptr<cv::JSONEmitter> cv::makePtr<cv::JSONEmitter,cv::FileStorage_API*>(cv::FileStorage_API *const &)' being compiled
6>persistence_yml.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_xml.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_xml.cpp(819): note: see reference to function template instantiation 'cv::Ptr<cv::XMLEmitter> cv::makePtr<cv::XMLEmitter,cv::FileStorage_API*>(cv::FileStorage_API *const &)' being compiled
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_yml.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence_yml.cpp(830): note: see reference to function template instantiation 'cv::Ptr<cv::YAMLEmitter> cv::makePtr<cv::YAMLEmitter,cv::FileStorage_API*>(cv::FileStorage_API *const &)' being compiled
6>rand.cpp
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\opengl.cpp(118): warning C4996: 'cudaGLSetGLDevice': was declared deprecated
6>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\cuda_gl_interop.h(305): note: see declaration of 'cudaGLSetGLDevice'
6>softfloat.cpp
6>split.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\persistence.cpp(1342): note: see reference to function template instantiation 'cv::Ptr<std::vector<uchar,std::allocator<_Ty>>> cv::makePtr<std::vector<_Ty,std::allocator<_Ty>>,size_t>(const size_t &)' being compiled
6>        with
6>        [
6>            _Ty=uchar
6>        ]
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\opengl.cpp(1640): warning C4459: declaration of 'clGetGLContextInfoKHR_pfn' hides global declaration
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\opencl\runtime\autogenerated/opencl_gl.hpp(58): note: see declaration of 'clGetGLContextInfoKHR_pfn' (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\opengl.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\opengl.cpp(1729): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\opengl.cpp(1789): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
6>stat.dispatch.cpp
6>stat_c.cpp
6>stl.cpp
6>sum.cpp
6>system.cpp
6>tables.cpp
6>trace.cpp
6>types.cpp
6>d:\libraries\opencv-4.0.1-cuda\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): error C2338: Can't use this makePtr with custom DefaultDeleter (compiling source file D:\Libraries\opencv-4.0.1-cuda\modules\core\src\ocl.cpp)
6>D:\Libraries\opencv-4.0.1-cuda\modules\core\src\ocl.cpp(371): note: see reference to function template instantiation 'cv::Ptr<cv::utils::fs::FileLock> cv::makePtr<cv::utils::fs::FileLock,const _Elem*>(const _Elem *const &)' being compiled
6>        with
6>        [
6>            _Elem=char
6>        ]
6>umatrix.cpp
6>datafile.cpp
6>filesystem.cpp
6>samples.cpp
6>va_intel.cpp
6>opencl_kernels_core.cpp
6>Done building project "opencv_core.vcxproj" -- FAILED.
========== Build: 5 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

**Comment by alalek** [comment]
> applied the suggested changes in cvstd_wrapper.hpp mentioned in another issue

You should post your results near this suggestion (at least to avoid time wasting of other people) instead of creation of new issue.

Also fixes for new CUDA SDK has been landed on the "master" branch. Thanks to @nglee !

**Comment by jsemeda** [comment]
I look at what you post as answers developers issues and I see you chiding at them in every occasion. No one comes here to deal with this kind of attitude .. I don't know who put someone like you in charge but if you don't like what you are doing DO NOT DO IT and let someone else with much better attitude take care of questions. From your name you sound russian apparently.
