### ISSUE TITLE
OpenCV crash at 'OpenCV(3.4.4) /Volumes/build-storage/build/3_4_iOS-mac/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) Exception in parallel_for() body: Unknown exception in function 'finalize'

### ISSUE THREAD

**Issue by windorz9** [opencv/opencv#14024]
I meet a crash with OpenCV 3.4.4 at iOS 12. 
Describe :libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.4) /Volumes/build-storage/build/3_4_iOS-mac/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) Exception in parallel_for() body: Unknown exception in function 'finalize'.
The crash occurs when I call this method, 
Status stitch(InputArrayOfArrays images, OutputArray pano);
When I write a demo test, there's no problem. However, the crash occurred when I was running the master project, so the problem should have nothing to do with OpenCV, but I don't know why this error occurred.

**Comment by alalek** [comment]
Try to catch triggered exceptions (something like this: https://stackoverflow.com/a/20072659 )

**Comment by windorz9** [comment]
@alalek thanks, I try to catch the exception in my code. 

   bool stitch (const std::vector <cv::Mat> & images, cv::Mat &result) {

    Stitcher stitcher = Stitcher::createDefault(false);//don't need gpu
    try {
        Stitcher::Status status = stitcher.stitch(images, result);
        if (status != Stitcher::OK) {
            return false;
        }
        return true;
    } catch (cv::Exception& e) {
        const char* msg_e = e.what();
        printf("error = %s", msg_e);
        return false;
    }    
}
This error also occurs,:
error = OpenCV(3.4.4) /Volumes/build-storage/build/3_4_iOS-mac/opencv/modules/core/src/parallel.cpp:240: error: (-2:Unspecified error) Exception in parallel_for() body: Unknown exception in function 'finalize'.

**Comment by windorz9** [comment]
@alalek I guess I've solved the problem, thanks.
When I run the project, There have been a lot of warnings like #10872.
When I add -fvisibility=hidden to "Other C++ flags" in Build Settings for your project.
Oh, The warnings all disappeared, and the crash disappeared.
thanks. 👍

**Comment by Light--** [comment]
> @alalek I guess I've solved the problem, thanks.
> When I run the project, There have been a lot of warnings like #10872.
> When I add -fvisibility=hidden to "Other C++ flags" in Build Settings for your project.
> Oh, The warnings all disappeared, and the crash disappeared.
> thanks. 👍

May i ask how do you solve the reported error exactly?

**Comment by SergLam** [comment]
@Light-- as @windorz9 says
"-fvisibility=hidden to "Other C++ flags" in Build Settings for your project."
[https://drive.google.com/open?id=1rVTz2S-0kYFUx86glmZ9zD5yGh3XDyPu](screenshot)

**Comment by Light--** [comment]
> @Light-- as @windorz9 says
> "-fvisibility=hidden to "Other C++ flags" in Build Settings for your project."
> [https://drive.google.com/open?id=1rVTz2S-0kYFUx86glmZ9zD5yGh3XDyPu](screenshot)


thank you, but
1， do you know what does the  ""-fvisibility=hidden to "Other C++ flags" in Build Settings for your project."" mean ? can you show the workable original code or minimal example code? if u can't show the code, could u please let the autor to answer this question cause i am not asking you?

2, the content of the link pointed is empty, throw out an empty link is helpless here

**Comment by SergLam** [comment]
@Light-- 

1. Well after two minutes of googling I have found an answer:
https://orangejuiceliberationfront.com/hiding-symbols-in-static-libraries-with-xcode-or-cmake/

**Symbol Hiding
So how does Xcode know which symbols to throw away and which to keep? I mean, I want users of my library to be able to link to the functions my static library exports, to its public API.

You have to tell it.

By default, Xcode just leaves every symbol in a library visible, unless it is obviously private (like static functions or inlined ones, or in Swift ones declared internal or private). But there is a setting to reverse that: “Symbols Hidden by Default” (Clang flag -fvisibility=hidden).

So how do I now tell it which ones to leave visible? Two approaches.**

Unfortunately, I can't show source code.
