### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [opencv/opencv#14042]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CV_GBTreesTest](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/ml/test/test_gbttest.cpp#L65 "Destructor for CV_GBTreesTest")
- [OpSoftmax](https://github.com/opencv/opencv/blob/997ad12730cfd8bb211a408a751b82ba7dacfa48/modules/dnn/src/vkcom/src/op_softmax.cpp#L34 "Destructor for OpSoftmax")
- [upnp](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/calib3d/src/upnp.cpp#L87 "Destructor for upnp")

**Comment by alalek** [comment]
Take a look on the next question after mentioned by link.
So if compiler is smart enough then generated code would be the same.

Lets avoid "changes for changes" which don't fix anything.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
