### ISSUE TITLE
Access to 3.4.5-dev doc

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14053]
I don't understand somethings seems broken in doc : 
from https://docs.opencv.org/ I can select 3.4 (3.4.x) adress in browser is https://docs.opencv.org/3.4/ but in doxygen  list it is 4.0.1-dev. 

![image](https://user-images.githubusercontent.com/3591626/54342426-b0d14e80-463c-11e9-8507-f3f2d40c75bb.png)

I can reproduce this problem only for 4.0.1-dev and 3.4.5-dev. I can select  other doc 3.4.3, 4.0.0 ...

windows 10 with firefox and edge

**Comment by alalek** [comment]
Try to press "Ctrl+F5" to reload page completely.

**Comment by alalek** [comment]
Fixed. These entries are replaced to "3.4.6-pre" and "4.1.0-pre".
Thank you!
