### ISSUE TITLE
an illegal memory access was encountered in function 'download'

### ISSUE THREAD

**Issue by LearnerZHENG** [opencv/opencv#14052]
##### System information (version)

- OpenCV => 3.4.4
- Operating System / Platform => Ubuntu16.04 LTS
- Cuda => 9.0

##### Detailed description

I would like to read the camera in gpu, but meet:

  opencv-3.4.4/modules/core/src/cuda/gpu_mat.cu:249: error: (-217:Gpu API call) an illegal memory access was encountered in function 'download'. 

when I want to get Mat from GpuMat using ".download"
##### Steps to reproduce

the function to get the frame:

{
       ...
        cv::cuda::GpuMat bayer{cv::Size(sFrameInfo.iWidth, sFrameInfo.iHeight), CV_8U, pbyBuffer};
	cv::cuda::Stream stream;
	cv::cuda::cvtColor(bayer, src, CV_BayerBG2BGR, 0, stream);
        ...
}

another funtion to convert GpuMat to Mat:

void getMat(cv::cuda::GpuMat src)
{
        Mat img;
        src.download(src);
        ...
}

the error:

opencv-3.4.4/modules/core/src/cuda/gpu_mat.cu:249: error: (-217:Gpu API call) an illegal memory access was encountered in function 'download'

**Comment by alalek** [comment]
Try to run OpenCV CUDA tests.

> 3.4.4

Check latest code from 3.4 branch too.

**Comment by nglee** [comment]
Maybe the following line:
```
src.download(src);
```
should be changed to:
```
src.download(img);
             ^^^
```

**Comment by LearnerZHENG** [comment]
@nglee 
Sorry for my wrong type.

However it works if changed to:

{
...
cv::Mat bayer{cv::Size(sFrameInfo.iWidth, sFrameInfo.iHeight), CV_8U, pbyBuffer};
cv::cuda::GpuMat d_bayer;
d_bayer.upload(bayer);
cv::cuda::Stream stream;
cv::cuda::cvtColor(d_bater, src, CV_BayerBG2BGR, 0, stream);
...
}
