### ISSUE TITLE
OpenCV loader: missing configuration file: ['config.py']

### ISSUE THREAD

**Issue by lannyyip** [opencv/opencv#14064]
##### System information (version)

- OpenCV => 3.4.5 / 4.0.0 / 4.0.1
- Operating System / Platform => Ubuntu 16
- Compiler => g++
- Python => 3.6.8

##### Detailed description

I compiled the open-cv with gstreamer support, and I tried to freeze my python codes with cx_freeze / pyinstaller. It prompt success whild freezing. But when I try to run the binary file, it prompted as follow:
```
  File "/usr/local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "/tmp/tmpe6jo_q_3/scripts/my_own_scripts.py", line 14, in <module>
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 58, in bootstrap
    load_first_config(['config.py'], True)
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 56, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
```

This error is not existed if I use open-cv with
`pip install opencv-python`
However, I need the gstream support for open-cv, so I have to compile it myself.
Please help me to check whether it is a bug or not. Thank you

Lanny

##### Steps to reproduce
1. compile opencv as guided
2. compose a python scripts to include opencv
```
import cv2

if __name__ == '__main__':
    print("Hello, world!")
```
3. freeze it with cx_freeze of pyinstaller
4. execute the binay.

**Comment by alalek** [comment]
> I compiled the open-cv

> pip install

There is mess with two different OpenCV setups. Conflicts are from here.

From OpenCV build folder run:
```
$ cmake --build . --target opencv_python3
...
$ ./setup_vars.sh python3 -c 'import cv2; print(cv2.__version__)'
Setting vars for OpenCV 3.4.6-pre
Append PYTHONPATH: /home/alalek/projects/opencv/build/opencv/python_loader
3.4.6-pre
```

> freeze it with cx_freeze of pyinstaller

Perhaps this doesn't work properly. OpenCV is not clear Python module, it contains native binary extensions which require native libraries.

**Comment by emielsteerneman** [comment]
@alalek I tried your proposed solution, but unfortunately I get the following error:

`/opencv/build$ cmake --build . --target opencv_python3`
`make: *** No rule to make target 'opencv_python3'.  Stop.`

Do you have suggestions on how to solve this problem?
I've tried this on both version 3.4.4 and 4.4.0 with the following CMAKE flags:
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=$cwd/installation/OpenCV-"$cvVersion" \
        -D INSTALL_C_EXAMPLES=ON \
        -D BUILD_PYTHON_SUPPORT=ON \
        -D BUILD_NEW_PYTHON_SUPPORT=ON \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D WITH_TBB=ON \
        -D WITH_V4L=ON \
        -D OPENCV_PYTHON3_INSTALL_PATH=$cwd/OpenCV-$cvVersion-py3/lib/python3.5/site-packages \
        -D WITH_OPENGL=ON \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D BUILD_TIFF=ON \
        -D BUILD_EXAMPLES=ON ..
```

**Comment by alalek** [comment]
You should see these lines in CMake [output](http://pullrequest.opencv.org/buildbot/builders/3_4-lin64/builds/331/steps/cmake/logs/stdio):
```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable exact version "3.5.2") 
```

without any of `numpy` errors.

**Comment by ManuelZ** [comment]
Works for me! Thanks!

**Comment by Frederic-Zhou** [comment]
pyinstaller --onefile --paths="/data/data/com.termux/files/usr/lib/python3.9/site-packages/cv2/python-3.9" opencv-test.py

**Comment by shrimp2t** [comment]
> pyinstaller --onefile --paths="/usr/lib/python3.9/site-packages/cv2/python-3.9" main.py

Thank you. You've saved my life

**Comment by lazith17** [comment]
> pyinstaller --onefile --paths="/usr/lib/python3.9/site-packages/cv2/python-3.9" main.py

This worked perfectly

**Comment by ductandev** [comment]
I am using opencv 4.2.0 it resolved my problem

**Comment by rabbit16** [comment]
I found this error in buildozer project which I used to build my kivy apk.
How can I solve it? I don't know how to hook it to buildozer spec file.
