### ISSUE TITLE
Expected cv::UMat for argument 'src'

### ISSUE THREAD

**Issue by iseegr8tfuldeadppl** [opencv/opencv#14077]
##### System information (version)

- OpenCV => latest as of march 15 2019 i'm not sure
- Operating System / Platform => ubuntu 18.04
- Compiler => python 3.6.8

##### Detailed description

I'm trying to apply the canny function on an image and here's the full code but it shows the error only if i put the steps within a function, but doesn't show when leaving all the code outside of any functions, i get the following error:
```
Traceback (most recent call last):
  File "lane.py", line 12, in <module>
    cannyer = canny(img)
  File "lane.py", line 5, in canny
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
TypeError: Expected cv::UMat for argument 'src'
```
With the following code:

##### Steps to reproduce
```
import cv2
import numpy as np

def canny(image):
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    canny = cv2.Canny(blur, 50, 150) #sick
    return canny

sourceimage = cv2.imread('lane.jpg')
img = np.copy(sourceimage)
canny = canny(img)
cv2.imshow("result", canny)
cv2.waitKey(0)


```

**Comment by alalek** [comment]
Message is not obvious, but looks like you trying to process  "None" object or something which is not a normal numpy array.

`print(image)` or dump of `cv.utils.dumpInputArray(image)` may help you.

**Comment by iseegr8tfuldeadppl** [comment]
The issue was fixed, after finding out the original image was corrupted/modified by mistake done by me after i used the variable for the original image rather than the actual copy i made of it, fixed by replacing the original image and making sure it doesn't happen again, thanks for reading.

**Comment by dhanpalrajpurohit** [comment]
There are two reasons for this error.
1.image is null
2.image is corrupted
Suggestion 
`print(image)` and check it.

**Comment by riship2009** [comment]
Hi @iseegr8tfuldeadppl 

I'm facing the same issue: **Expected Ptr<cv::UMat> for argument 'src'**

I'm not able to understand how you solved this issue. Can you please explain further ?
is there anything wrong with mu code in line **gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)**

************************************************************************************
def face_extractor(img):

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    if faces is ():
        return None

    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

******************************************************************************************

**Comment by riship2009** [comment]
> Hi @iseegr8tfuldeadppl
> 
> I'm facing the same issue: **Expected Ptrcv::UMat for argument 'src'**
> 
> I'm not able to understand how you solved this issue. Can you please explain further ?
> is there anything wrong with mu code in line **gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)**
> 
> def face_extractor(img):
> 
> ```
> gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
> faces = face_cascade.detectMultiScale(gray, 1.3, 5)
> 
> if faces is ():
>     return None
> 
> # Crop all faces found
> for (x,y,w,h) in faces:
>     cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
>     cropped_face = img[y:y+h, x:x+w]
> 
> return cropped_face
> ```

Hi @dhanpalrajpurohit 
Can you please help me with this

**Comment by YussifIbrahim** [comment]
> Hi @iseegr8tfuldeadppl
> 
> I'm facing the same issue: **Expected Ptrcv::UMat for argument 'src'**
> 
> I'm not able to understand how you solved this issue. Can you please explain further ?
> is there anything wrong with mu code in line **gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)**
> 
> def face_extractor(img):
> 
> ```
> gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
> faces = face_cascade.detectMultiScale(gray, 1.3, 5)
> 
> if faces is ():
>     return None
> 
> # Crop all faces found
> for (x,y,w,h) in faces:
>     cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
>     cropped_face = img[y:y+h, x:x+w]
> 
> return cropped_face
> ```

In case you are using videoCapture to read from a video, it returns (true, image), so you must use _,frame =Video.read()

**Comment by FTDecoder** [comment]
Expected Ptr<cv::UMat> for argument 'array'
Hi @dhanpalrajpurohit 

I'm not do not know the reason why this issue rises. This error arises when I call upon cv2.moments(). 
The code that I have used is
moments = cv2.moments(contours)

Can you explain as to why it occurs??

**Comment by zhouyuangan** [comment]
using `img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)` can work.

**Comment by scizors** [comment]
Hi all I have same problem 
`import cv2
import numpy as np
capture = cv2.VideoCapture(1,cv2.CAP_V4L2)
#set width  height and format
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 160)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 120)


retur, frame = capture.read()
color_image = np.asanyarray(frame)
#do some transformations on img

#gray = cv2.cvtColor(color_image, cv2.COLOR_RGB2GRAY)
#save matrix/array as image file
isWritten = cv2.imwrite('image-2.jpg', color_image)

if isWritten:
        print('Image is successfully saved as file.')
`


error 
`Traceback (most recent call last):
  File "img.py", line 15, in <module>
    isWritten = cv2.imwrite('image-2.jpg', color_image)
TypeError: Expected Ptr<cv::UMat> for argument 'img'`

**Comment by smitheric95** [comment]
I ran into this problem when copying binary masks with `np.zeros_like()`:
```python
mask_two = np.zeros_like(mask_one)  # creates corrupted mask
```

The workaround was to manually specify the shape and data type myself:
```python
mask_two = np.zeros((mask_one.shape), dtype=np.uint8)
```
