### ISSUE TITLE
getPerfProfile vs wall-clock time?

### ISSUE THREAD

**Issue by rohith14** [opencv/opencv#14075]
Why is there a such a big difference in timing with getPerfProfile vs wall-clock time (using chrono) in C++?

For example, running Yolov3 inference in C++ (opencv 3.4.4), linux, Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz

```
        //score function
        auto startI = std::chrono::system_clock::now();
        net.forward(outs, outNames);
        auto endI = std::chrono::system_clock::now();
        std::chrono::duration<double> elapsed_secondsI = endI - startI;
        std::cout << "Inference time: " << elapsed_secondsI.count() << " sec\n";
        
        // Put efficiency information.
        std::vector<double> layersTimes;
        double freq = getTickFrequency() / 1000;
        double t = net.getPerfProfile(layersTimes) / freq;
        std::cout << "layersTimes: " << t/1000 << " sec\n";
        std::string label = format("Inference time: %.2f ms", t);
```
> 10x difference
**Inference time: 5.77825 sec
layersTimes: 0.308765 sec**

**Comment by alalek** [comment]
What is about second iteration?

**Comment by rohith14** [comment]
thanks @alalek 

It's working as expected after 1st run

**Comment by wangwenchao-job** [comment]
Excuse me, how did you solve it later?@rohith14

I encountered the same problem.

Thank you!
