### ISSUE TITLE
Template matching with mask

### ISSUE THREAD

**Issue by DeMoriarty** [opencv/opencv#14076]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => :grey_question:
- Compiler => Windows 10 64 Bit

##### Detailed description

The mask parameter of matchTemplate doesn't work on TM_CCOEFF and TM_CCOEFF_NORMED. Is there any workaround except using other template matching methods? I prefer using CCOEFF_NORMED since it's much faster.

**Comment by abhinavsagar** [comment]
@DeMoriarty Can you provide all the details?

**Comment by DeMoriarty** [comment]
@abhinavsagar Thanks for replying. I was trying to use matchTemplate on my project, the template image is transparent, to get accurate result I need to use the alpha layer of template image as mask, however on the document it says template matching with mask is only implemented for Square Difference (SQDIFF) and Normalized Cross Correlation(CCORR_NORMED). Is there any reason why other methods like CCOEFF do not support template matching with mask? is it going to be implemented in the future?
