### ISSUE TITLE
OpenCV on TX2: can't read darknet model

### ISSUE THREAD

**Issue by QuentinBoul** [opencv/opencv#14081]
Hi!

I recently installed openCV on my TX2 dev kit. But when trying to read a Darknet yolov3 model, I have the following errors:

> OpenCV(3.4.1-dev) Error: Parsing error (Unknown layer type: shortcut) in ReadDarknetFromCfgFile, file /home/nvidia/opencv/modules/dnn/src/darknet/darknet_io.cpp, line 503
> Traceback (most recent call last):
>   File "HandDetectionUsingCPUAndDarknetlive_TX2CameraOnBoard.py", line 45, in <module>
>     net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
> cv2.error: OpenCV(3.4.1-dev) /home/nvidia/opencv/modules/dnn/src/darknet/darknet_io.cpp:503: error: (-212) Unknown layer type: shortcut in function ReadDarknetFromCfgFile

Here is the part of the code concerned:
```
modelConfiguration = "HumanHandDetectorv3.cfg";
modelWeights = "HumanHandDetectorv3_6700.weights";

net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)
```
I installed openCV by following this tuto: https://www.youtube.com/watch?v=-QVTXdHEzzs

How can I fixe it?

Thank you and best regards!
Quentin

**Comment by dkurt** [comment]
Try to update OpenCV.

**Comment by QuentinBoul** [comment]
Thank you @dkurt ! I updated OpenCV to 4.0.0 using this tuto: https://www.pyimagesearch.com/2018/08/15/how-to-install-opencv-4-on-ubuntu/
and it works now!
