### ISSUE TITLE
Unable to add new function to OpenCv.js

### ISSUE THREAD

**Issue by anshkumar** [opencv/opencv#14086]
I've updated the grabCut function (`opencv-master/modules/imgproc/src/grabcut.cpp`) and also added some new functions in the `imageproc` module. For that I've updated the `opencv-master/modules/imgproc/include/opencv2/imgproc.hpp` file as:

```
CV_EXPORTS_W void grabCut( InputArray img, InputOutputArray mask, OutputArrayOfArrays contour, Rect rect,
                           InputOutputArray bgdModel, InputOutputArray fgdModel,
                           int iterCount, int mode = GC_EVAL );
    
CV_EXPORTS_W void grabCut_slim( InputArray img, InputOutputArray mask,OutputArrayOfArrays contour, Rect rect,
                               InputOutputArray bgdModel, InputOutputArray fgdModel,
                               int iterCount, int mode = GC_EVAL );
    
    
CV_EXPORTS_W void paintselection( InputArray img, InputOutputArray mask,OutputArrayOfArrays contour,
                          InputOutputArray bgdModel, InputOutputArray fgdModel,
                          int iterCount, int mode = GC_EVAL );

CV_EXPORTS_W void paintselection_slim( InputArray img, InputOutputArray mask,OutputArrayOfArrays contour,
                               InputOutputArray bgdModel, InputOutputArray fgdModel,
                               int iterCount, int mode = GC_EVAL );
```

Doing that I'm able to use the updated function in c++. Now I want to use these updated functions in both `js`. Currently running compiled version of OpenCV.js  is giving me following error:

```
TypeError: cv.paintselection is not a function[Learn More] paintselection.html:76:11

    nextIter file:///Users/vedanshu/Desktop/paintselection.html:76 
    keyCheck file:///Users/vedanshu/Desktop/paintselection.html:213 
```

**Comment by dkurt** [comment]
Take a look at https://github.com/opencv/opencv/blob/master/modules/js/src/embindgen.py. Currently all the JS bindings are explicit.

You may use commits History to check how to add new bindings. In example, an entire features2d module: https://github.com/opencv/opencv/pull/12659.

**Comment by anshkumar** [comment]
Updating in the file https://github.com/opencv/opencv/blob/master/modules/js/src/embindgen.py worked.
