### ISSUE TITLE
Incomplete Python BRIEF Example

### ISSUE THREAD

**Issue by zhanwenchen** [opencv/opencv#14093]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => MacOS 10.14 Mojave
- Compiler => Xcode 10.1 

##### Detailed description

The documentation on BRIEF is painfully incomplete. Unlike its peers in the series, not only does it lack explanation for STAR, but it also doesn't show any original or processed image despite the imread in the code.

##### Steps to reproduce
You can read the documentation at https://docs.opencv.org/4.0.1/dc/d7d/tutorial_py_brief.html. The Markdown source is https://github.com/opencv/opencv/blob/master/doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown.

**Comment by LucianaMarques** [comment]
Hi there, I would like to take a try on this! Is it open to PRs or is someoe already taking a look at it? :)
