### ISSUE TITLE
.pbtxt work well in python,but show Nothing in c++

### ISSUE THREAD

**Issue by wangz6886** [opencv/opencv#14097]
##### System information (version)
python 3.6
first，I download 
 ssd_mobilenet_v2_coco.config at https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v2_coco.config，and according to my needs modify “num_classes”-->2， “batch_size” -->24，and some“path”。
second，I use myself pics train ，then obtain frozen_inference_graph.pb
third ，I use tf_text_graph_ssd.py generate frozen_inference_graph.pbtxt
Fourth，I test it by cv.dnn.readNetFromTensorflo in python 3.6 ，and pbtxt pb‘s effect is not bad
![image](https://user-images.githubusercontent.com/33597700/54577498-0c357f00-4a37-11e9-938a-3e1af4eb6015.png)
BUT when I use in C++ ,no errors, and show result pics without any marks。
![image](https://user-images.githubusercontent.com/33597700/54579445-756cc080-4a3e-11e9-90b4-25ee38b3ee19.png)

python code 
`
import cv2 as cv
 
cvNet = cv.dnn.readNetFromTensorflow('C:/dl/aaa/frozen_inference_graph.pb','C:/dl/aaa/frozen_inference_graph.pbtxt')
 
img = cv.imread('C:/dl/aaa/t3.jpg')
rows = img.shape[0]
cols = img.shape[1]
cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
cvOut = cvNet.forward()
 
for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.2:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        cv.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)
        cv.putText(img, str(score), (int(right), int(bottom)), cv.FONT_HERSHEY_SIMPLEX, 1, (23, 230, 210), 2)
 
cv.imshow('img', img)
cv.waitKey()
`
c++ code 

`
#include "pch.h"
#include <iostream>
#include<opencv2\opencv.hpp>
#include<opencv2\dnn.hpp>
#include <iostream>

using namespace std;
using namespace cv;
using namespace dnn;

const size_t inWidth = 300;
const size_t inHeight = 300;
const float WHRatio = inWidth / (float)inHeight;
const char* classNames[] = { "background","eye-open","eye-closed" };//

int main() {

	String weights = "C:/dl/aaa/frozen_inference_graph.pb";
	String prototxt = "C:/dl/aaa/frozen_inference_graph.pbtxt";

	dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);
	Mat image = imread("C:/dl/aaa/21.jpg");

	float detect_thresh = 0.2;

	net.setInput(blobFromImage(image, 1.0, Size(300, 300),true, false));
	 //net.setInput(blobFromImage(image, 1.0/256, Size(300, 300),true, false));  //the result is same
	Mat cvOut = net.forward();

	Mat detectionMat(cvOut.size[2], cvOut.size[3] , CV_32F, cvOut.ptr<float>());
	for (int i = 0; i < detectionMat.rows; i++)
	{
		int obj_class = detectionMat.at<float>(i, 1);
		float confidence = detectionMat.at<float>(i, 2);

		if (confidence > detect_thresh)
		{
			size_t objectClass = (size_t)(detectionMat.at<float>(i, 1));

			int xLeftBottom = static_cast<int>(detectionMat.at<float>(i, 3) * image.cols);
			int yLeftBottom = static_cast<int>(detectionMat.at<float>(i, 4) * image.rows);
			int xRightTop = static_cast<int>(detectionMat.at<float>(i, 5) * image.cols);
			int yRightTop = static_cast<int>(detectionMat.at<float>(i, 6) * image.rows);

			Rect object((int)xLeftBottom, (int)yLeftBottom,
				(int)(xRightTop - xLeftBottom),
				(int)(yRightTop - yLeftBottom));

			rectangle(image, object, Scalar(0, 0, 255), 2);
			putText(image, classNames[obj_class], Point(xLeftBottom, yLeftBottom - 10), 3, 0.5, Scalar(0, 0, 255), 2);
		}
	}

	imshow("test", image);
	cv::waitKey(0);

	return 0;
}
`

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
