### ISSUE TITLE
LinkError: import object field 'memory' is not a Memory

### ISSUE THREAD

**Issue by anshkumar** [opencv/opencv#14098]
I was trying to use OpenCV.js on my webpage. Using `opencv.js` on an independent webpage is working fine. But the moment I integrate it on webpage it is throwing me following error:

```
failed to asynchronously prepare wasm: LinkError: import object field 'memory' is not a Memory opencv.js:24:8278333
LinkError: "import object field 'memory' is not a Memory" opencv.js:24:8478051
LinkError: "import object field 'memory' is not a Memory" opencv.js:24:8478061 
```

I have no idea what does that even mean. What might me going wrong ? Is that a version issue of some dependency ?

**Comment by alalek** [comment]
We have no idea how did you build it and how you configured your environment.
Take a look and compare with these [build logs](http://pullrequest.opencv.org/buildbot/builders/master_javascript-emscripten-lin64).
