### ISSUE TITLE
Pending Pull request to build

### ISSUE THREAD

**Issue by adityak2920** [opencv/opencv#14094]
I had made a PR 4 days ago but it's still waiting for builds, it's showing status "Some checks haven’t completed yet".
This kind of thing happened with my previous PR's also some took almost 1 week to clear all checks. I don't know what to do so that my PR's accepted easily.

My current PR is #14082 

I had previously closed one PR also because of this issue.
So, how can I resolve this issue?

**Comment by alalek** [comment]
Please read contribution guidelines. They state to use proper names of the source branch and to avoid using of generic names of existed branches like "master" / "3.4".
Otherwise these PRs are not triggered testing automatically.
