### ISSUE TITLE
Non-repeated field "min_size" is specified multiple times

### ISSUE THREAD

**Issue by Pinnh** [opencv/opencv#14100]
##### System information (version)
- OpenCV => 3.4.4
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => Python Version OpenCV 3.4.4

**caffe version SSD detector supports multiple  "min_size" and "max_size" param
but OpenCV gives a error:**

[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 913:13: Non-repeated field "min_size" is specified multiple times.
Traceback (most recent call last):
  File "face_det.py", line 60, in <module>
    net = cv.dnn.readNetFromCaffe(prototxt_file, caffeModel=caffemodel_file)
cv2.error: OpenCV(3.4.4) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: yufacedetectnet-open-v1.prototxt in function 'ReadNetParamsFromTextFileOrDie'

**the PriorBoxParameter which Caffe defined as below:**

// Message that store parameters used by PriorBoxLayer
message PriorBoxParameter {
  // Encode/decode type.
  enum CodeType {
    CORNER = 1;
    CENTER_SIZE = 2;
    CORNER_SIZE = 3;
  }
  **// Minimum box size (in pixels). Required!
  repeated float min_size = 1;
  // Maximum box size (in pixels). Required!
  repeated float max_size = 2;**
  // Various of aspect ratios. Duplicate ratios will be ignored.
  // If none is provided, we use default ratio 1.
  repeated float aspect_ratio = 3;
  // If true, will flip each aspect ratio.
  // For example, if there is aspect ratio "r",
  // we will generate aspect ratio "1.0/r" as well.
  optional bool flip = 4 [default = true];
  // If true, will clip the prior so that it is within [0, 1]
  optional bool clip = 5 [default = false];
  // Variance for adjusting the prior bboxes.
  repeated float variance = 6;
  // By default, we calculate img_height, img_width, step_x, step_y based on
  // bottom[0] (feat) and bottom[1] (img). Unless these values are explicitely
  // provided.
  // Explicitly provide the img_size.
  optional uint32 img_size = 7;
  // Either img_size or img_h/img_w should be specified; not both.
  optional uint32 img_h = 8;
  optional uint32 img_w = 9;

  // Explicitly provide the step size.
  optional float step = 10;
  // Either step or step_h/step_w should be specified; not both.
  optional float step_h = 11;
  optional float step_w = 12;

  // Offset to the top left corner of each cell.
  optional float offset = 13 [default = 0.5];
}

**Comment by smartwell** [comment]
@Pinnh do you solve this problem?

**Comment by Pinnh** [comment]
@smartwell solved ,  opencv has not integrated this feature, so I not use opencv to run this ssd model, instead use caffe-ssd.

**Comment by smartwell** [comment]
> @smartwell solved , opencv has not integrated this feature, so I not use opencv to run this ssd model, instead use caffe-ssd.

yes， me too.

**Comment by Doubiiu** [comment]
> @smartwell solved , opencv has not integrated this feature, so I not use opencv to run this ssd model, instead use caffe-ssd.

how to fix this problem by using caffe-ssd? I am new to use yufacedetectnet, thanks!

**Comment by Pinnh** [comment]
You should install [caffe-ssd](https://github.com/weiliu89/caffe) first .

**Comment by mshabunin** [comment]
Fixed in #15076

**Comment by Doubiiu** [comment]
> Fixed in #15076

I use pip install opencv-python==3.4.5.20 to install opencv3.4 again. But it doesn't work. I don't know why.
