### ISSUE TITLE
DNN tensorflow compatibility version

### ISSUE THREAD

**Issue by gouttham** [opencv/opencv#14111]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Mac
- Compiler => 

##### Detailed description

in DNN efficiency page the tensorflow version is pointed to 1.4.1, Will there be an update to the latest tensorflow version 1.13, there have been lost of performance improvements and new data types in the latest version. So is there any updates we can expect in the near future.

**Comment by dkurt** [comment]
OpenCV doesn not use TensorFlow for computations. It just reads trained models and executes layer by layer with default implementation or through one of back ends.

**Comment by gouttham** [comment]
for instance, dt_resource is one such data type which we see in models trained using tensorflow v1.10+

**Comment by dkurt** [comment]
@gouttham, please provide a reproducer. A model or just it's subgraph.

**Comment by dkurt** [comment]
@gouttham, Please complete this issue so it'll look like a feature request or a bug report. Provide minimal working example which might be used to show the problem.

**Comment by dkurt** [comment]
Closing it due no response from author.
