### ISSUE TITLE
Problems with findContours

### ISSUE THREAD

**Issue by Spectra456** [opencv/opencv#14116]
I'm trying to **findContours** of this threshold image. When i'm using **opencv3**, it's okay and i'm getting correct array for drawContours. But, when i'm using **opencv4**, i'm getting array like a [[[-1,-1,-1,-1]]]. Anybody have same problem?
![thresh](https://user-images.githubusercontent.com/31315447/54720704-26737800-4b71-11e9-987e-8b68d9fe7f69.png)

**Comment by LJXLJXLJX** [comment]
I guess the  [[[-1,-1,-1,-1]]] is the hierarchy.
> If for the contour i there are no next, previous, parent, or nested contours, the corresponding elements of hierarchy[i] will be negative.

You can refer to the official doc.
https://docs.opencv.org/4.0.1/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0

**Comment by Spectra456** [comment]
Solved.
