### ISSUE TITLE
Viola and Jones Haar features

### ISSUE THREAD

**Issue by kupferb** [opencv/opencv#14128]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Windows7
- Compiler => VS

##### Detailed description

In `haarfeatures.cpp` in OpenCV I see the following implementation for V & J Haar features:

     void CvHaarEvaluator::generateFeatures()
    {
        int mode = ((const CvHaarFeatureParams*)((CvFeatureParams*)featureParams))->mode;
        int offset = winSize.width + 1;
        for( int x = 0; x < winSize.width; x++ )
        {
            for( int y = 0; y < winSize.height; y++ )
            {
                for( int dx = 1; dx <= winSize.width; dx++ )
                {
                    for( int dy = 1; dy <= winSize.height; dy++ )
                    {
                        // haar_x2
                        if ( (x+dx*2 <= winSize.width) && (y+dy <= winSize.height) )
                        {
                            features.push_back( Feature( offset, false,
                                x,    y, dx*2, dy, -1,
                                x+dx, y, dx  , dy, +2 ) );
                        }
                        // haar_y2
                        if ( (x+dx <= winSize.width) && (y+dy*2 <= winSize.height) )
                        {
                            features.push_back( Feature( offset, false,
                                x,    y, dx, dy*2, -1,
                                x, y+dy, dx, dy,   +2 ) );
                        }
                        // haar_x3
                        if ( (x+dx*3 <= winSize.width) && (y+dy <= winSize.height) )
                        {
                            features.push_back( Feature( offset, false,
                                x,    y, dx*3, dy, -1,
                                x+dx, y, dx  , dy, +3 ) );
                        }
                        // haar_y3
                        if ( (x+dx <= winSize.width) && (y+dy*3 <= winSize.height) )
                        {
                            features.push_back( Feature( offset, false,
                                x, y,    dx, dy*3, -1,
                                x, y+dy, dx, dy,   +3 ) );
                        }
                        // x2_y2
                        if ( (x+dx*2 <= winSize.width) && (y+dy*2 <= winSize.height) )
                        {
                            features.push_back( Feature( offset, false,
                                x,    y,    dx*2, dy*2, -1,
                                x,    y,    dx,   dy,   +2,
                                x+dx, y+dy, dx,   dy,   +2 ) );
                        }

                    }
                }
            }
        }
        numFeatures = (int)features.size();
    } 

Where each feature is represented by two (haar_x2, haar_y2, haar_x3, haar_y3) or three (x2_y2) rectangles and **corresponding weights** in order to compute the feature from the integral image.

    inline float CvHaarEvaluator::Feature::calc( const cv::Mat &_sum, const cv::Mat &_tilted, size_t y) const
    {
        const int* img = tilted ? _tilted.ptr<int>((int)y) : _sum.ptr<int>((int)y);
        float ret = rect[0].weight * (img[fastRect[0].p0] - img[fastRect[0].p1] - img[fastRect[0].p2] + img[fastRect[0].p3] ) +
            rect[1].weight * (img[fastRect[1].p0] - img[fastRect[1].p1] - img[fastRect[1].p2] + img[fastRect[1].p3] );
        if( rect[2].weight != 0.0f )
            ret += rect[2].weight * (img[fastRect[2].p0] - img[fastRect[2].p1] - img[fastRect[2].p2] + img[fastRect[2].p3] );
        return ret;
    }

For haar_x2 the configuration is:

[![enter image description here][1]][1]

so the first rectangle `(x, y, dx*2, dy)` represents the sum A+B (with weight -1)
and the second rectangle `(x+dx, y, dx, dy)` represents just B (with weight +2)
summing up with weights gives -(A + B) + 2 * B = B - A as it should. the same holds for haar_y2

for x2_y2 the configuration is: 

[![enter image description here][2]][2]

Here the first rectangle `(x, y, dx*2, dy*2)` represents (A + B + C + D),
the second rectangle `(x, y, dx, dy)` represents A
and the third rectangle `(x+dx, y+dy, dx, dy)` represents D
so with weights we get -(A + B + C + D) + 2 * A + 2 * D = A + D - (B + C)
as we should.
 
**But** for haar_x3 (and y3) the configuration is:

[![enter image description here][3]][3]

so the first rectangle `(x, y, dx*3, dy)` represents (A + B + C)
and the second rectangle `(x+dx, y, dx, dy)` represents B.

Now, with weights we get -(A + B + C) + **3*B**  = 2 * B - (A + C)
while the V & J paper states that 

> "A three rectangle feature computes the sum within two outside
> rectangles substracted from the sum in the center rectangle"

[![enter image description here][4]][4]

**I read this as B - (A + C) and not 2 * B - (A + C)!.**

Am I missing something here? or is this a bug? can anyone confirm this?

  [1]: https://i.stack.imgur.com/uS6WH.png
  [2]: https://i.stack.imgur.com/zWzKo.png
  [3]: https://i.stack.imgur.com/2fyGl.png
  [4]: https://i.stack.imgur.com/Hffw5.png

**Comment by catree** [comment]
In my opinion you are right about the code, and most likely it is a bug.

---

Some Viola & Jones implementations to compare:
- [An Analysis of the Viola-Jones Face Detection Algorithm](https://www.ipol.im/pub/art/2014/104/) (**`A+C-B`?**)
- [libvj.py](https://github.com/shkolnick-kun/cv_school/blob/f1cec23826b1733863384cae265f7e76c81f41cf/task6/libvj.py#L188-L208) (**`A+C-B`?**):
```
class HaarFeatureHorizontalThreeSegments(HaarFeature):
        
    def __init__(self, x, y, w, h):
        assert(w % 3 == 0)
        assert(x >= 0)
        assert(y >= 0)
        assert(h >= 2)
        assert(w >= 3)
        
        self.y_s  = y
        self.y_e  = y + h - 1
    
        self.x_s  = x
        self.x_m1 = x + w // 3
        self.x_m2 = x + 2 * w // 3 - 1
        self.x_e  = x + w - 1
        
    def compute_value(self, integral_image):
        s1 = integral_image.sum(self.x_s,  self.y_s,  self.x_e,  self.y_e)
        s2 = integral_image.sum(self.x_m1, self.y_s,  self.x_m2, self.y_e)
return s1 - 2*s2
```
- [wasmface](https://github.com/noahlevenson/wasmface/blob/da13eea995af4e3e83a199e459e3779ef597f992/src/cpp/integral-image.cpp#L60-L91) (**`A+C-B`?**):
```
/**
 * Compute the value of a Haar-like feature over an integral image
 * @param  {Haarlike} h  The Haar-like feature to compute
 * @param  {Int}      sx Integral image x offset
 * @param  {Int}      sy Integral image y offset
 * @return {Float}       Feature value
 */
float IntegralImage::computeFeature(Haarlike& h, int sx, int sy) {
	float wSum, bSum;
	if (h.type == 1) {
		wSum = this->getRectangleSum(h.x + sx, h.y + sy, h.w, h.h);
		bSum = this->getRectangleSum(h.x + sx + h.w, h.y + sy, h.w, h.h);
	} else if (h.type == 2) {
		wSum = this->getRectangleSum(h.x + sx, h.y + sy, h.w, h.h) + 
			this->getRectangleSum(h.x + sx + h.w * 2, h.y + sy, h.w, h.h);
		bSum = this->getRectangleSum(h.x + sx + h.w, h.y + sy, h.w, h.h);
	} else if (h.type == 3) {
		wSum = this->getRectangleSum(h.x + sx, h.y + sy, h.w, h.h);
		bSum = this->getRectangleSum(h.x + sx, h.y + sy + h.h, h.w, h.h);
	} else if (h.type == 4) {
		wSum = this->getRectangleSum(h.x + sx, h.y + sy, h.w, h.h) + 
			this->getRectangleSum(h.x + sx, h.y + sy + h.h * 2, h.w, h.h);
		bSum = this->getRectangleSum(h.x + sx, h.y + sy + h.h, h.w, h.h);
	} else {
		wSum = this->getRectangleSum(h.x + sx, h.y + sy, h.w, h.h) + 
			this->getRectangleSum(h.x + sx + h.w, h.y + sy + h.h, h.w, h.h);
		bSum = this->getRectangleSum(h.x + sx + h.w, h.y + sy, h.w, h.h) + 
			this->getRectangleSum(h.x + sx, h.y + sy + h.h, h.w, h.h);
	}
	float f = bSum - wSum;
	return f;
}
```
- [Viola and Jones Object Detection Framework (C++)](https://github.com/alexdemartos/ViolaAndJones/blob/5ed087df8228513a3256108d0cf56e714dbafd80/src/Feature.cpp#L51-L74) (**`B-(A+C)`?**):
```
float Feature::getValue(float *ii, int iiwidth, int x, int y) {
  // 5 types of feature (A, B, C, C^t, D)
  switch(this->type) {
    case 0:
      return rectangleValue(ii, iiwidth, x, y, this->xc+(this->width/2), this->yc, this->width/2, this->height)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc, this->width/2, this->height);
      break;
    case 1:
      return rectangleValue(ii, iiwidth, x, y, this->xc, this->yc, this->width, this->height/2)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc+(this->height/2), this->width, this->height/2);
      break;
    case 2:
      return rectangleValue(ii, iiwidth, x, y, this->xc+(width/3), this->yc, this->width/3, this->height)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc, this->width/3, this->height)-rectangleValue(ii, iiwidth, x, y, this->xc+(width*2/3), this->yc, this->width/3, this->height);
      break;
    case 3:
      return rectangleValue(ii, iiwidth, x, y, this->xc, this->yc+(this->height/3), this->width, this->height/3)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc, this->width, this->height/3)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc+(this->height*2/3), this->width, this->height/3);
      break;
    case 4:
      return rectangleValue(ii, iiwidth, x, y, this->xc+(width/2), this->yc, this->width/2, this->height/2)+rectangleValue(ii, iiwidth, x, y, this->xc, this->yc+(height/2), this->width/2, this->height/2)-rectangleValue(ii, iiwidth, x, y, this->xc+(width/2), this->yc+(height/2), this->width/2, this->height/2)-rectangleValue(ii, iiwidth, x, y, this->xc, this->yc, this->width/2, this->height/2);
      break;
    default:
      std::cout << "Error: feature type " << this->type << " does not exist. Feature type is in range [0, 4]." << std::endl;
      exit(-1);
      break;
  }
}
```
- [Viola Jones](https://github.com/Simon-Hohberg/Viola-Jones/blob/8772a28c7a622643741700bf6807acfe36fb818f/violajones/HaarLikeFeature.py#L41-L78) (**`A+C-B`?**):
```
def get_score(self, int_img):
        """
        Get score for given integral image array.
        :param int_img: Integral image array
        :type int_img: numpy.ndarray
        :return: Score for given feature
        :rtype: float
        """
        score = 0
        if self.type == FeatureType.TWO_VERTICAL:
            first = ii.sum_region(int_img, self.top_left, (self.top_left[0] + self.width, int(self.top_left[1] + self.height / 2)))
            second = ii.sum_region(int_img, (self.top_left[0], int(self.top_left[1] + self.height / 2)), self.bottom_right)
            score = first - second
        elif self.type == FeatureType.TWO_HORIZONTAL:
            first = ii.sum_region(int_img, self.top_left, (int(self.top_left[0] + self.width / 2), self.top_left[1] + self.height))
            second = ii.sum_region(int_img, (int(self.top_left[0] + self.width / 2), self.top_left[1]), self.bottom_right)
            score = first - second
        elif self.type == FeatureType.THREE_HORIZONTAL:
            first = ii.sum_region(int_img, self.top_left, (int(self.top_left[0] + self.width / 3), self.top_left[1] + self.height))
            second = ii.sum_region(int_img, (int(self.top_left[0] + self.width / 3), self.top_left[1]), (int(self.top_left[0] + 2 * self.width / 3), self.top_left[1] + self.height))
            third = ii.sum_region(int_img, (int(self.top_left[0] + 2 * self.width / 3), self.top_left[1]), self.bottom_right)
            score = first - second + third
        elif self.type == FeatureType.THREE_VERTICAL:
            first = ii.sum_region(int_img, self.top_left, (self.bottom_right[0], int(self.top_left[1] + self.height / 3)))
            second = ii.sum_region(int_img, (self.top_left[0], int(self.top_left[1] + self.height / 3)), (self.bottom_right[0], int(self.top_left[1] + 2 * self.height / 3)))
            third = ii.sum_region(int_img, (self.top_left[0], int(self.top_left[1] + 2 * self.height / 3)), self.bottom_right)
            score = first - second + third
        elif self.type == FeatureType.FOUR:
            # top left area
            first = ii.sum_region(int_img, self.top_left, (int(self.top_left[0] + self.width / 2), int(self.top_left[1] + self.height / 2)))
            # top right area
            second = ii.sum_region(int_img, (int(self.top_left[0] + self.width / 2), self.top_left[1]), (self.bottom_right[0], int(self.top_left[1] + self.height / 2)))
            # bottom left area
            third = ii.sum_region(int_img, (self.top_left[0], int(self.top_left[1] + self.height / 2)), (int(self.top_left[0] + self.width / 2), self.bottom_right[1]))
            # bottom right area
            fourth = ii.sum_region(int_img, (int(self.top_left[0] + self.width / 2), int(self.top_left[1] + self.height / 2)), self.bottom_right)
            score = first - second - third + fourth
return score
```

**Comment by kupferb** [comment]
> Nice catch! I would follow the paper, so that implementations follow like they should. This means you actually found a bug and should submit a fix for this. The reason why people never noticed this is that is just a slightly different feature which is then used to train (and which will be equally unique) I suggest for a change!

 @StevenPuttemans - thank you for your resopnse! 
have opened pull request for change. 
Lets see what will happen....
