### ISSUE TITLE
call example_dnn_segmentation with --zoo option

### ISSUE THREAD

**Issue by peter197321** [opencv/opencv#14129]
I am trying to run build examples of DNN modue such as

/example_dnn_segmentation --model=mobilenet_iter_73000.caffemodel --config=mobilenet_deploy.prototxt --input=000067.jpg --mean="104 117 123" --rgb 

this seems to me causing a problem to execute on my side ...
I would use ZOO models for this.

How to execute these DNN examples with --zoo option and alias name of model to extract from models.yml?

**Comment by dkurt** [comment]
If you want to report a bug please provide all the details to reproduce it. Add a reference to model, add a error massage or expected results comparing to observed ones.

**Comment by dkurt** [comment]
@peter197321, Can we close this issue or you can provide steps to reproduce?

`--zoo` is an optional flag. This was introduced just to hide number of parameters such `mean` and `scale`. See PR https://github.com/opencv/opencv/pull/12641 for details.

**Comment by dkurt** [comment]
Closing it due no response from author.
