### ISSUE TITLE
imread failing on image with hebrew name

### ISSUE THREAD

**Issue by eyaler** [opencv/opencv#14132]
python 3.6. opencv 3.4.3.18 and 4.0.0.21. imread returns None for image with hebrew name (python open works fine)
```
import cv2
file = 'א.jpg'
print(open(file,'rb').read() is not None)
print(cv2.imread(file) is not None)
```

True
False

**Comment by eyaler** [comment]
@alalek  which is the dupe? couldn't find one

**Comment by alalek** [comment]
Search for "unicode" symbols.
Use `imdecode()` instead.
