### ISSUE TITLE
Using FileStorage::APPEND

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14130]
I cannot read data written in file when I use FileStorage:: APPEND 

my code : 

```
        FileStorage fs;
        fs.open("test.yml", FileStorage::WRITE);
        fs << "a" << 48;
        fs.release();
        fs.open("test.yml", FileStorage::APPEND);
        fs << "b" << 49;
        fs.release();
        fs.open("test.yml", FileStorage::READ);
        cout << int(fs["a"]) << endl;
        cout << int(fs["b"]) << endl;

```
result : 
a = 48
b = 0

yml file is 

```
%YAML:1.0
---
a: 48
...
---
b: 49

```

It works using xml file

PS I cannot find previous issue about append problem in yml but I can find many post on stackoverflow

**Comment by Mancancode** [comment]
ok i write my codes in python few in c++ , you should make sure that you are using C++ API, but i think you are missing " ./ or /: "

**Comment by saskatchewancatch** [comment]
@LaurentBerger I had to use something similar in 3.4 and your example worked correctly for me.

Were you using master? Build/config information you can provide us?

Your example is very correct and it is puzzling how it fails.

Thanks

**Comment by LaurentBerger** [comment]
Bug is still here using yml file. there is no bug using xml file.

windows 10 win 64
visual studio 2017
opencv-4.1.1-dev

**Comment by TH3CHARLie** [comment]
I did further investigation and found that the current 3.4 branch produces correct results using the same above-mentioned code, which means in 3.4 the reader is able to read multiple documents from one file. Current master branch in 4.x fails to behave the same, so this is a regression issue and I think solution 2 from my last comment would be the correct way to go.
