### ISSUE TITLE
Documentation broken link: classification_classes_ILSVRC2012.txt

### ISSUE THREAD

**Issue by JacobChrist** [opencv/opencv#14148]
##### System information (version)
- OpenCV => Master Branch
- Operating System / Platform => Platform Independent
- Compiler => N/A

##### Detailed description
This web page: https://docs.opencv.org/master/d5/de7/tutorial_dnn_googlenet.html

And thus this location in the repo: https://github.com/opencv/opencv/blob/master/doc/tutorials/dnn/dnn_googlenet/dnn_googlenet.markdown

Refer to the a file with the names of ILSVRC2012 classes.  Specifically the file: classification_classes_ILSVRC2012.txt.

The link to this file goes to a github error 404.

##### Steps to reproduce
Click on the link to the classification_classes_ILSVRC2012.txt file on either of the above pages.

##### Steps to fix
This file does appear to be in the repository at this location:

https://github.com/opencv/opencv/blob/master/samples/data/dnn/classification_classes_ILSVRC2012.txt

**Comment by TanishaShrotriya96** [comment]
Hi, this tutorial isn't up to date with the current code in the repository. There is a variable "mean" which is also given as an input in the command line arguments in the older version. This is no longer there in the latest code.
[Link to Tutorial](https://docs.opencv.org/3.4.2/d5/de7/tutorial_dnn_googlenet.html)
[Link to Code](https://github.com/opencv/opencv/blob/3.4/samples/dnn/classification.cpp)

I would like to update it, if possible.
