### ISSUE TITLE
GStreamer + HLS stream taking up a massive amount of CPU	

### ISSUE THREAD

**Issue by farzaa** [opencv/opencv#14147]
Hello all! Working on a rather tough problem lately that I've having a hard time wrapping my head around. 

I have an HLS livestream I'm reading from twitch.tv. I want to grab one frame per second from the livestream, and save it locally. But, I need to stay real time. So, when I save an image from the stream, that image should be very close to what is actually live. 

This isn't very difficult via GStreamer on the command line. 

But, I actually need to process the stream in Python (because I'm doing some other processing on the frame before I save it). OpenCV actually has a gstreamer integration that can be found here. 

As for the code itself, it's quite simple: 
```
cap = cv2.VideoCapture( 
    f"souphttpsrc is_live=true location={hls_stream_link} ! hlsdemux ! 
    queue ! decodebin ! videorate ! video/x-raw,framerate=1/1 ! 
    videoconvert ! appsink max-buffers=1 drop=true sync=false", 
cv2.CAP_GSTREAMER) 

while True: 
    success, frame = cap.read() 
    save_frame(frame) 
    time.sleep(1.0) 
```

This code is doing exactly what I want it to do. Saving one frame per second and staying close to real time. This is why I do: max-buffers=1 drop=true sync=false. I also have a one second sleep, since I only need to read one frame per second. 

The issue is, the above code takes up 250% of my machine's CPU (tested on Windows, Linux, and OS X). I'm attempting to understand why this is the case and what I can do to reduce CPU usage. 

I'm having a hard time understanding why decoding a single frame from an HLS stream leads to such high CPU usage. I've tried Python multithreading and using a special queue to save frames on a separate process and then read from that queue. 

Thanks for the help!

**Comment by mshabunin** [comment]
1080p decoding on CPU can take this amount of processing. You should either switch to GPU-accelerated decoding (e.g. VA-API gstreamer plugin), either reduce stream quality. Decoder needs to process all frames from the stream (60 per second) to be able to decode it.

**Comment by farzaa** [comment]
"Decoder needs to process all frames from the stream (60 per second) to be able to decode it."

Is there a way to get around this? For example, in my case I only want to be able to process/decode one frame per second. What is forcing the system to need to process all the frames to decode?

**Comment by mshabunin** [comment]
Frames are not coded independently, in most cases decoding frame X requires decoding frames X-1, X-2, X-3, ..., X-n, where n is variable.
* https://en.wikipedia.org/wiki/Video_compression_picture_types
* https://en.wikipedia.org/wiki/Group_of_pictures

**Comment by mshabunin** [comment]
Some decoders actually can provide some means to skip some processing, e.g. avdec_h264 gstreamer node has an option:
```
  skip-frame          : Which types of frames to skip during decoding
                        flags: readable, writable
                        Enum "GstLibAVVidDecSkipFrame" Default: 0, "Skip nothing"
                           (0): Skip nothing     - 0
                           (1): Skip B-frames    - 1
                           (2): Skip IDCT/Dequantization - 2
                           (5): Skip everything  - 5
```

**Comment by mfoglio** [comment]
@farzaa did you find a solution to the high cpu usage?
