### ISSUE TITLE
src.size == dst.size && src.type() == dst.type() && src.isContinuous() && dst.isContinuous() && src.type() == CV_32F

### ISSUE THREAD

**Issue by laolaolulu** [opencv/opencv#14140]
CvDnn.BlobFromImage(image, 1, new OpenCvSharp.Size(800, 600))    Report errors

CvDnn.BlobFromImage(image, 1, new OpenCvSharp.Size(800, 500)) No problem

![TIM截图20190325174407](https://user-images.githubusercontent.com/33310261/54909644-aa3cb400-4f25-11e9-8abe-8758ff0f4493.png)

**Comment by dkurt** [comment]
`OpenCvSharp` is not a part of this repository. Please find an origin project or provide a minimal working example.
