### ISSUE TITLE
Build issue with OpenCV 3.4.2 and Protobuf 3.x

### ISSUE THREAD

**Issue by samfux84** [opencv/opencv#14153]
Hi I am trying to build OpenCV 3.4.2 with protobuf 3.1.0 and it fails because of a protobuf function, where the number of arguments does not seem to be correct.

OpenCV 3.4.1 was building fine with protobuf 3.1.0

##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => CentOS Linux release 7.5.1804 (Core)
- Compiler => GCC 4.8.5

##### Detailed description

I am setting 

-DBUILD_PROTOBUF:BOOL=OFF
-DPROTOBUF_UPDATE_FILES=ON

and try to compile. Then it fails with the error "no matching function call to ‘google::protobuf::TextFormat::Parser::Parser(bool)’". Please find below the full error message

/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/cmake-3.4.3-wlr7puqviq3n4cfku4gyzoixugqbmog3/bin/cmake -E cmake_depends "Unix Makefiles" /cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2 /cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2/modules/videoio /dev/shm/spackapps/spack-stage/spack-stage-EYVnQA/opencv-3.4.2/spack-build /dev/shm/spackapps/spack-stage/spack-stage-EYVnQA/opencv-3.4.2/spack-build/modules/videoio /dev/shm/spackapps/spack-stage/spack-stage-EYVnQA/opencv-3.4.2/spack-build/modules/videoio/CMakeFiles/opencv_videoio.dir/DependInfo.cmake --color=
/cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2/modules/dnn/src/caffe/caffe_io.cpp: In function ‘bool cv::dnn::ReadProtoFromTextFile(const char*, google::protobuf::Message*)’:
/cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2/modules/dnn/src/caffe/caffe_io.cpp:1123:53: error: no matching function for call to ‘google::protobuf::TextFormat::Parser::Parser(bool)’
     return google::protobuf::TextFormat::Parser(true).Parse(&input, proto);
                                                     ^
/cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2/modules/dnn/src/caffe/caffe_io.cpp:1123:53: note: candidates are:
In file included from /cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2/modules/dnn/src/caffe/caffe_io.cpp:95:0:
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/protobuf-3.3.0-zzpdd7u6zenb3bsxwxqqo6vaqmokpax7/include/google/protobuf/text_format.h:413:5: note: google::protobuf::TextFormat::Parser::Parser()
     Parser();
     ^
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/protobuf-3.3.0-zzpdd7u6zenb3bsxwxqqo6vaqmokpax7/include/google/protobuf/text_format.h:413:5: note:   candidate expects 0 arguments, 1 provided
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/protobuf-3.3.0-zzpdd7u6zenb3bsxwxqqo6vaqmokpax7/include/google/protobuf/text_format.h:411:28: note: google::protobuf::TextFormat::Parser::Parser(const google::protobuf::TextFormat::Parser&)
   class LIBPROTOBUF_EXPORT Parser {
                            ^
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/protobuf-3.3.0-zzpdd7u6zenb3bsxwxqqo6vaqmokpax7/include/google/protobuf/text_format.h:411:28: note:   no known conversion for argument 1 from ‘bool’ to ‘const google::protobuf::TextFormat::Parser&’

##### Steps to reproduce

'cmake' '/cluster/apps/spack/var/spack/stage/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/opencv-3.4.2' '-DCMAKE_INSTALL_PREFIX:PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/opencv-3.4.2-z7lau63t3a3lhfyo6mvc353j6vbddcq3/lib64:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gtkplus-2.24.32-2uvg5kax25g475slugimc5kv26amatez/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/atk-2.22.0-wl5y6z5xzxl34qp3wkbjb2i7ojbp4lkb/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/glib-2.53.1-ijbbl5wqlt77v3ixnmfswauow4ab37uq/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gettext-0.19.8.1-kgnq7ppb6j7okopmflxgv7nmtz5ooqvb/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/bzip2-1.0.6-oricxs4nathoo7eamggc5dyksbh3ooyp/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libunistring-0.9.7-sxuyffv6zmnuinztpn533bcsh4cbjqyn/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxml2-2.9.4-wdimbtxlcskbvorduy2gdl6akorvijag/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/xz-5.2.3-gla7wvbtt5igzfbgwlazihdhqxz43avb/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-bq2w5h6vcd64cmfueygcbug4fksi4eb4/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/ncurses-6.0-znvb5kvlta5mc2dspoty5yn27lz5qhlq/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libffi-3.2.1-hhuk5ymmrctrrhwu2tgxwfaj6oe4u33s/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/pcre-8.40-ada35o4k5hczigd223exldpxbujfvicg/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/util-linux-2.29.2-7lsdshs6oq55hjavavo2ttw2yoy3qaq2/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/python-3.6.0-34hohfstdn5fsdkinphnqwoqjrc57b4w/lib:/usr/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/readline-7.0-iksctows4sc5i6zyzzagavzjfdqrczb3/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/sqlite-3.18.0-tfst5jg4vcg6zi5osjoh6cypqaumux3e/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/tcl-8.6.6-roqx67aul42je6k2uh4ieu25rlieexie/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/tk-8.6.6-oo2fsvqnscdaz3b2tcnbqea3u4tbdxhd/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libx11-1.6.3-m7muhqcvb3ewwfyzkftoiuetgh7hz4in/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxcb-1.12-j7dszeiqq37w43g3nbfjcwnuzikzyaab/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libpthread-stubs-0.3-2ftc3lcedvu2erjcnwdyqnojptd72duu/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxau-1.0.8-kd77zemf3ftwxnvcstjg4qkbr7xlvx3z/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxdmcp-1.1.2-qonyagxedsy5srmbcdfttqk4uempbzz6/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gobject-introspection-1.50.0-b2imfrohpnucbffokloxiav46q3xstq6/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/cairo-1.14.12-oo7zznrjuha6ckp6obwbwe7tyfcdijt5/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/fontconfig-2.11.1-vt46m56kazgaha6xqrpj6nwxwz7ru7al/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/font-util-1.3.1-vld2qq3h5bujrsowfby6342unl4ftjqn/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/freetype-2.7-mhhi2pufcglnyisabx7ha4ylcuyqmf3u/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxext-1.3.3-4uahydwnz4uwawvrekyzlgk2renlirgv/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxrender-0.9.10-vq3zjbsj57dq2czazqcl4ffo5f5ghduw/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/pixman-0.34.0-36ghkvcgcblryiaeenizlv7p2p2bl2tc/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gdk-pixbuf-2.31.6-ifqdzyr33kimrvnvk2lnn4wjjw2btwgn/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/jpeg-9b-psjvucpx7xwkflb3meatuo6ugdtapkex/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libtiff-4.0.6-y76bcjaualcxv3hld235ducq3oski7wf/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/pango-1.40.4-kn7igzwzcqkw2hlier3ewdcwdymiz3z5/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/harfbuzz-1.4.8-cttqe6uiqqaog2lmrs2eshy5rkfk43m3/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/icu4c-58.2-oog6twe6grsocdcc2us4qguckwfdq6cn/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libxft-2.3.2-fd3aiwfqhrgd25gi4afvwktck35t3a4w/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/jasper-1.900.1-bumpytrxkpl536motn7fnyuulpka3muf/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libjpeg-turbo-1.5.0-k4k6butvqepajegqqry6irs6uh5qsmb3/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/protobuf-3.3.0-zzpdd7u6zenb3bsxwxqqo6vaqmokpax7/lib:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/cuda-9.0.176-uqbi62cpkd645vbehqscqy42zhdvfvqq/lib64:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libffi-3.2.1-hhuk5ymmrctrrhwu2tgxwfaj6oe4u33s/lib64:/usr/lib64' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DENABLE_PRECOMPILED_HEADERS:BOOL=OFF' '-DWITH_IPP:BOOL=ON' '-DWITH_CUDA:BOOL=ON' '-DWITH_QT:BOOL=OFF' '-DWITH_VTK:BOOL=OFF' '-DBUILD_opencv_java:BOOL=OFF' '-DBUILD_opencv_core:BOOL=ON' '-DBUILD_opencv_highgui:BOOL=ON' '-DBUILD_opencv_imgproc:BOOL=ON' '-DWITH_JPEG:BOOL=OFF' '-DWITH_PNG:BOOL=ON' '-DWITH_TIFF:BOOL=ON' '-DWITH_ZLIB:BOOL=ON' '-DWITH_OPENMP:BOOL=OFF' '-DBUILD_opencv_dnn:BOOL=ON' '-DBUILD_PROTOBUF:BOOL=OFF' '-DPROTOBUF_UPDATE_FILES=ON' '-DWITH_OPENCL=OFF' '-DWITH_OPENCLAMDFFT=OFF' '-DWITH_OPENCLAMDBLAS=OFF' '-DWITH_VA_INTEL=OFF' '-DZLIB_LIBRARY_RELEASE:FILEPATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-bq2w5h6vcd64cmfueygcbug4fksi4eb4/lib/libz.so' '-DZLIB_INCLUDE_DIR:PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-bq2w5h6vcd64cmfueygcbug4fksi4eb4/include' '-DPNG_LIBRARY_RELEASE:FILEPATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/lib/libpng.so' '-DPNG_INCLUDE_DIR:PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/include' '-DTIFF_LIBRARY_RELEASE:FILEPATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libtiff-4.0.6-y76bcjaualcxv3hld235ducq3oski7wf/lib/libtiff.so' '-DTIFF_INCLUDE_DIR:PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/libtiff-4.0.6-y76bcjaualcxv3hld235ducq3oski7wf/include' '-DJASPER_LIBRARY_RELEASE:FILEPATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/jasper-1.900.1-bumpytrxkpl536motn7fnyuulpka3muf/lib/libjasper.so' '-DJASPER_INCLUDE_DIR:PATH=/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/jasper-1.900.1-bumpytrxkpl536motn7fnyuulpka3muf/include' '-DWITH_GTK:BOOL=OFF' '-DWITH_GTK_2_X:BOOL=ON' '-DBUILD_opencv_python2=OFF' '-DBUILD_opencv_python3=OFF'

then run "make".

**Comment by alalek** [comment]
> OpenCV 3.4.2

It is too old.

> Parser(bool)

Problem has been workarounded here: #11923 (OpenCV 3.4.3)
