### ISSUE TITLE
error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'cv::dnn::dnn4_v20181221::`anonymous-namespace'::addConstNodes'

### ISSUE THREAD

**Issue by dlml** [opencv/opencv#14165]
i have successfully transform my keras model to pb model, and test the result is same, when i test pb model in opencv, the bug appears

**Comment by dkurt** [comment]
@dlml, To solve your problem (if it's a bug) we need to have a fully reproducible example.

**Comment by dlml** [comment]
pb   [ https://pan.baidu.com/s/1Zb_NybT2eitdF9EtdZzQ4A ](url)  secret：jk7s 

pbtxt [https://pan.baidu.com/s/1LNIQzQo8DRmEBrsZcJhrrg](url)  secret：lqb8 
@dkurt

**Comment by dlml** [comment]
pb https://pan.baidu.com/s/1Zb_NybT2eitdF9EtdZzQ4A 
secret：jk7s

pbtxt https://pan.baidu.com/s/1LNIQzQo8DRmEBrsZcJhrrg 
secret：lqb8
@dkurt

**Comment by dlml** [comment]
hi @dkurt , so what can be done to solve the problem?

**Comment by dkurt** [comment]
@dlml, please provide a direct link. This service makes users to download some executable .exe files instead.

**Comment by dkurt** [comment]
Closing it due no response from author.

**Comment by jdmking2019** [comment]
hi! I have a pb model with PSEnet, I want to deplay with opencv, but it have bug.error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'cv::dnn::experimental_dnn_v5::`anonymous-namespace'::addConstNodes'

**Comment by wang1210** [comment]
I have the same problem in python-opencv ,I can upload this ,Please take a look for me

**Comment by wang1210** [comment]
Can you tell me your emal @@dkurt
