### ISSUE TITLE
Draw rectangle with openCV.Js

### ISSUE THREAD

**Issue by wilfriednhw** [opencv/opencv#14171]
System information (version)

    OpenCV => 3.4.6
    Operating System / Platform =>ubuntu
    Compiler => javascript

Detailed description
    
   Hi , Please How can draw rectangle on image loaded from url with opencvjavascript.
   thank you.

**Comment by dkurt** [comment]
OpenCV.js methods are named in the same way as methods in C++. So you can easy find samples of how to use it: https://github.com/opencv/opencv/search?l=JavaScript&q=rectangle
