### ISSUE TITLE
Don't understand command line argument "-cl-no-subgroup-ifp"!

### ISSUE THREAD

**Issue by SHADOWMOOON** [opencv/opencv#14187]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => Windows10  64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I ues the C++ version of the code which is based on OpenCV4.0/dnn/object_detection.cpp  to make a prediction with mask-rcnn model  .when I choose the DNN_TARGET_OPENCL as for net.setPreferableTarget( ) parameter. and I get the error like this:
[ INFO:0] Initialize OpenCL runtime...
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\ADMINI~1\AppData\Local\Temp\opencv\4.0\opencl_cache\
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_1080_Ti--419_35
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

However,the code run fine with the choose of DNN_TARGET_CPU 
##### Steps to reproduce 
here is part of my code:
// Load the network
	Net net = readNetFromTensorflow(modelWeights, textGraph);
	net.setPreferableBackend(DNN_BACKEND_OPENCV);
	net.setPreferableTarget(DNN_TARGET_OPENCL);

**Comment by alalek** [comment]
It is just a runtime check of available OpenCL flags. Message says that feature is not supported and should not be used by OpenCV.

It make sense to implement some "quiet" mode for such checks.

**Comment by SHADOWMOOON** [comment]
@alalek So,did it use gpu to run or not. Does OpenCL successfully run? Sorry, I got confused about those Message.

**Comment by alalek** [comment]
It should use GPU (but partially due missing features).

> Windows10 64

You can try to check it [here](https://www.howtogeek.com/351073/how-to-monitor-gpu-usage-in-the-windows-task-manager/).

**Comment by SHADOWMOOON** [comment]
@alalek OK thx! that means I can just ignore the -cl-no-subgroup-ifp..

**Comment by bixiaopeng0** [comment]
我也是遇到这个问题了，用的dnn模块，cpu跑通了，但是速度很慢，想用opencl但是和你遇到一样的问题，请问你是怎么解决的

**Comment by ihg1992** [comment]
on ubuntu16.04 I meet this problem too,how make it works ,help

**Comment by bixiaopeng0** [comment]
> on ubuntu16.04 I meet this problem too,how make it works ,help
现在opencv4.2 dnn模块支持cuda了，速度很快。

**Comment by ihg1992** [comment]
> > on ubuntu16.04 I meet this problem too,how make it works ,help
> > 现在opencv4.2 dnn模块支持cuda了，速度很快。

thanks very much ,I will try it. 给力!

**Comment by bixiaopeng0** [comment]
奥利给！




| |
毕晓鹏
|
|
邮箱：bixiaopeng1996@163.com
|

签名由 网易邮箱大师 定制

On 07/17/2020 17:49, ihg1992 wrote:

on ubuntu16.04 I meet this problem too,how make it works ,help
现在opencv4.2 dnn模块支持cuda了，速度很快。

thanks very much ,I will try it. 给力!
