### ISSUE TITLE
who can help me transformation tensorflow model form ssd.

### ISSUE THREAD

**Issue by kekxv** [opencv/opencv#14183]
OpenCV => 4.0.0
tensorflow => 1.13.1

alway fail when i use dnn/tf_text_graph_ssd.py transformation model for tensorflow to OpenCV model,it tell me:
Traceback (most recent call last):
  File "/home/k/work/opencv/samples/dnn/tf_text_graph_ssd.py", line 368, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "/home/k/work/opencv/samples/dnn/tf_text_graph_ssd.py", line 233, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError

i try `ssd_mobilenet_v1_coco`,`ssd_mobilenet_v2_coco`,`ssd_inception_v2_coco` and other ssd model,but no one succeeded.

i try  dnn/tf_text_graph_faster_rcnn.py and dnn/tf_text_graph_mask_rcnn.py,that was work,but that is very slow.

so who can help me transformation tensorflow model form ssd.

**By the way,All the models I trained myself**

**Comment by dkurt** [comment]
For usage questions please use a forum: http://answers.opencv.org. You may also try to find some help there.

If you want to report a bug - please follow a guide in issue's template. It should be fully reproducible.

**Comment by kekxv** [comment]
@dkurt 
it's working when i try [TransformGraph](https://github.com/opencv/opencv/issues/11560#issuecomment-391047037)

by the way,meybe you can check the [tf_text_graph_ssd.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py),and add [TransformGraph](https://github.com/opencv/opencv/issues/11560#issuecomment-391047037) code

and then, thank you.

**Comment by zcunyi** [comment]
> @dkurt
> it's working when i try [TransformGraph](https://github.com/opencv/opencv/issues/11560#issuecomment-391047037)
> 
> by the way,meybe you can check the [tf_text_graph_ssd.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py),and add [TransformGraph](https://github.com/opencv/opencv/issues/11560#issuecomment-391047037) code
> 
> and then, thank you.

Hi, I have the same error like yours. Just adding the code below?
`import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = TransformGraph(graph_def, ['image_tensor'], ['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'], ['sort_by_execution_order'])
    with tf.gfile.FastGFile('sorted_inference_graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())`
where should it be added ?
thanks.

**Comment by alalek** [comment]
@zcunyi Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by zcunyi** [comment]
@kekxv 
Hi, I have the same error like yours.
how to add the code about  TransformGraph  ?
thanks a lot.

**Comment by kekxv** [comment]
> @kekxv
> 你好,我跟你环境一样,也是遇到这个问题,关于 TransformGraph, 好像最新的' tf_text_graph_ssd.py'代码跟原来的不一样,请问你是如何添加TransformGraph的,在哪个位置添加啊? 谢谢!


你可以试试下面的代码，先把模型转换
（You can try the following code to transform the model first.）

```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = TransformGraph(graph_def, ['image_tensor'], ['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'], ['sort_by_execution_order'])
    with tf.gfile.FastGFile('sorted_inference_graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())
```
