### ISSUE TITLE
Opencv3.4.3 cv::dft() output matrix values are nan

### ISSUE THREAD

**Issue by TMXY** [opencv/opencv#14185]
##### System information (version)
- OpenCV => 3.4.3
- Operating System / Platform => Linux Ubuntu 16.04
- Compiler => GNU++7.1.0

##### Detailed description

Utilize cv::dft() to compute fft, the input matrix is definitely has the values, but after calling it that return the output array with nothing. But it could produce in the OS linux ubuntu 18 

##### Steps to reproduce
    // C++ code example
    ```
  Mat img = cv::imread(argv[1],1);
  resize(img,img,cv::Size(128,128),cv::INTER_AREA);

  Mat imgGray;
  img.convertTo(img,CV_32F);
  cv::cvtColor(img,imgGray,CV_BGR2GRAY);
  imgGray.convertTo(imgGray,CV_64F);
  Mat F;
  cv::dft(imgGray,F,DFT_REAL_OUTPUT);
  for (i=0; i<F.rows; i++){
    for (j=0; j<F.cols; j++){
       cout<<"after dft output pixels "<<F.at<double>(i,j)<<endl;
    }
  }

**Comment by TMXY** [comment]
The input pixel in one position is nan which was found.

**Comment by berak** [comment]
also, please don't use `F.at(i,j)` to print it (uchar !!), but `F.at<double>(i,j)` (CV_64F)

**Comment by alalek** [comment]
@berak Code is fine - it is GitHub parser eat `<double>` (due mis-formatted code snippet, fixed that).
