### ISSUE TITLE
Failed to Build OpenCV 4.0.1 with OpenCV Contrib and CUDA 10.0

### ISSUE THREAD

**Issue by michael080808** [opencv/opencv#14197]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Ubuntu 18.04.2 LTS (Bionic Beaver)
- Compiler => gcc-7.3.0
- CMake => 3.13.4

##### Detailed description

I try to build opencv 4.0.1 with opencv_contrib 4.0.1 and CUDA 10.0
After I solved CMakeList.txt Error in opencv_contrib/cudacodec on Line 17
```cmake
if(HAVE_NVCUVID)
  list(APPEND extra_libs ${CUDA_CUDA_LIBRARY} ${CUDA_nvcuvid_LIBRARY})
endif()
```
I replaced CUDA_CUDA_LIBRARY with CUDA_LIBRARY

After I put nvcuvid.h and related headers to the /usr/local/cuda-10.0/include
After I put libnvcuvid.so and related dynamic libraries to the /usr/local/cuda-10.0/lib64

I got some error in opencv_test_cudacodec.
```shell
../../lib/libopencv_cudacodec.so.4.0.1：undefined reference to ‘cuCtxGetCurrent’
collect2: error: ld returned 1 exit status
modules/cudacodec/CMakeFiles/opencv_test_cudacodec.dir/build.make:108: recipe for target 'bin/opencv_test_cudacodec' failed
make[2]: *** [bin/opencv_test_cudacodec] Error 1
CMakeFiles/Makefile2:9493: recipe for target 'modules/cudacodec/CMakeFiles/opencv_test_cudacodec.dir/all' failed
make[1]: *** [modules/cudacodec/CMakeFiles/opencv_test_cudacodec.dir/all] Error 2
make[1]: *** Waiting for the unfinished task....
```

My cmake configuration is here:
```shell
cmake .. \
-DOPENCV_PYTHON3_VERSION:BOOL="1" \
-DOPENCV_EXTRA_MODULES_PATH:PATH="/home/maho/Downloads/opencv_contrib-4.0.1/modules" \
-DBUILD_JASPER:BOOL="1" \
-DBUILD_JAVA:BOOL="0" \
-DWITH_CUDA:BOOL="1" \
-DCMAKE_BUILD_TYPE:STRING="Release" \
-DWITH_JASPER:BOOL="0"
```

Any Advise? I consider turn off all test unit first before it's solved.

**Comment by alalek** [comment]
> 4.0.1

Try latest master.

Cudacodec is not usable with CUDA > 6.5 - API has been changed.

There are already multiple issues on these topics.

**Comment by michael080808** [comment]
> > 4.0.1
> 
> Try latest master.
> 
> Cudacodec is not usable with CUDA > 6.5 - API has been changed.
> 
> There are already multiple issues on these topics.

Thanks. 
I used to build it with latest master before. 
However I usually got some errors and I moved to releases.
I'll try latest master later.

**Comment by wahyubram82** [comment]
if you read the document in CUDA documentation (doc/pdf/NVIDIA_Video_Decoder.pdf), it's said:

"NVIDIA Video Decoder (NVCUVID) is deprecated. Instead, use the NVIDIA Video Codec SDK."

but if you still wanna use it, you can download the NVIDIA Video Codec SDK, in this link below (got that link from NVIDIA_Video_Decoder.pdf doc), latest version is SDK 9:
https://developer.nvidia.com/nvidia-video-codec-sdk

you will get your nvcuvid library from this sdk
