### ISSUE TITLE
dnn: build failure on gcc, invalid-pch

### ISSUE THREAD

**Issue by seiko2plus** [opencv/opencv#14195]
##### System information (version)

- OpenCV => 3.4, master. after #13932
- Operating System / Platform => all
- Compiler => tested on gcc >= 4.9 on ppc64le, also on x86

##### Detailed description

```bash
cc1plus: warning: /worker/buildbot/Power9_Linux_gcc-6__opencv/build/modules/dnn/test_precomp.hpp.gch/opencv_test_dnn_Release.gch: not used because `__OPENCV_TESTS' not defined [-Winvalid-pch]
[ 50%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_imgproc_umat.cpp.o
In file included from <command-line>:0:0:
/worker/buildbot/Power9_Linux_gcc-6__opencv/build/modules/dnn/test_precomp.hpp:50:27: fatal error: test_common.hpp: No such file or directory
 #include "test_common.hpp"
                           ^
compilation terminated.
make[2]: *** [modules/dnn/CMakeFiles/opencv_perf_dnn.dir/build.make:63: modules/dnn/CMakeFiles/opencv_perf_dnn.dir/test/test_common.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6697: modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
buildbot URI:
nightly builds: [Linux-debug](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/342/steps/compile%20debug/logs/stdio) (other tests uses ccache on Linux)
gcc4.9 : https://ocv-power.imavr.com/#/builders/5/builds/46
gcc5: https://ocv-power.imavr.com/#/builders/16/builds/291
gcc6 : https://ocv-power.imavr.com/#/builders/14/builds/18
gcc7: https://ocv-power.imavr.com/#/builders/12/builds/8

##### Steps to reproduce

build dnn module with tests enabled

**Comment by mendes-davi** [comment]
I'm also getting the same error!

**Comment by seiko2plus** [comment]
@mendes-davi , try this patch #14196 it should fix this issue.

**Comment by nizqsut** [comment]
Same problem. Fixed with disalbe this option:

![image](https://user-images.githubusercontent.com/1464272/63560116-58a55d80-c587-11e9-9bd8-e1b3839882c3.png)
