### ISSUE TITLE
CUDA : OpenCV requires enabled 'cudev' module from 'opencv_contrib'

### ISSUE THREAD

**Issue by iamvishal** [opencv/opencv#14205]
i am building opencv c++ on windows using the script here : https://docs.opencv.org/3.4.3/d3/d52/.... I enabled cuda, tests, perf_tests, docs and samples as i wanted to build eveything. but i get this compilation cmake error. I have installed CUDA toolkit 10.1 on my machine. CMake Error at modules/core/CMakeLists.txt:39 (message): CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib' repository: https://github.com/opencv/opencv_contrib Call Stack (most recent call first): modules/world/CMakeLists.txt:13 (include) modules/world/CMakeLists.txt:32 (include_one_module)

I believe the script sets opencv_contrib path which has cudev module. Unable to figure out what's going wrong here.
Prior i was able to build it and This started happening since 2 days.

**Comment by alalek** [comment]
relates #14177

Current workaround: do not enable `opencv_world` (`cmake -DBUILD_opencv_world=OFF ...`).

**Comment by alalek** [comment]
@iamvishal Could you try this patch: #14206?

**Comment by iamvishal** [comment]
Sure @alalek . Thanks for quick response. What if i wont enable opencv_world? Will it build opencv_world.dll? Il try your patch and let you know.

**Comment by iamvishal** [comment]
@alalek Your patch fixes the issue. Better than a workaround. Thanks 👍

**Comment by thanh15dt2** [comment]
> @alalek Your patch fixes the issue. Better than a workaround. Thanks 👍

i faced the same problem like and i read the solution but i dont understand
force_builders=Custom
buildworker:Custom=linux-2
build_world:Custom=ON
docker_image:Custom=ubuntu-cuda:16.04
build_contrib:Custom=ON
what i need to do with this ? 
tks a lots

**Comment by alalek** [comment]
@thanh15dt2 These lines are not a code patch. Please learn GitHub first.

**Comment by AlexeyAB** [comment]
> Could you try this patch: https://github.com/opencv/opencv/pull/14206 ?

@alalek Why are we getting this problem `CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'` with the current master branch `Mar 21, 2020` even though this fix https://github.com/opencv/opencv/pull/14206 was added almost a year ago `31 Mar 2019`?

**Comment by fader111** [comment]
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.X.X.zip
unzip opencv_contrib.zip
cmake -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.X.X/modules

**Comment by nowhere-girl** [comment]
@fader111 include extra module doesn't work with me, causing more error instead.

**Comment by FlyingSpringrol** [comment]
Was running into this issue. Just followed this video tutorial though and the solution is to link in the path in cmake.
https://youtu.be/TT3_dlPL4vo?t=372

**Comment by Totemi1324** [comment]
@alalek When there's one thing I hate on programmer's forums is that one simply assumes everybody got the same skill level as they do and offending you when you don't understand something. Not everybody has that much experience and knowledge as you do, so _please_ can you explain **IN DETAIL** how to apply the patch?
I have the flag -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules set as mentioned by @fader111 and it still gives me this error:
CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib

**Comment by Totemi1324** [comment]
> @alalek Your patch fixes the issue. Better than a workaround. Thanks +1

Can you please explain to us how you did apply the patch to get it working? As mentioned by my previous post, I have the same issue as you do and still get the error even if I have the modules included. So it would be very helpful. Thank you!

**Comment by mnschmidt** [comment]
> > @alalek Your patch fixes the issue. Better than a workaround. Thanks +1
> 
> Can you please explain to us how you did apply the patch to get it working? As mentioned by my previous post, I have the same issue as you do and still get the error even if I have the modules included. So it would be very helpful. Thank you!

You can see the actual diff here: https://github.com/opencv/opencv/pull/14206/files

**Comment by lorepieri8** [comment]
@Totemi1324 
Make sure to have downloaded and unzipped the opencv_contrib.zip in the right path, as indicated by the cmake flag (-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.X.X/modules).

**Comment by Lorisyy** [comment]
> wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.X.X.zip
> unzip opencv_contrib.zip
> cmake -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.X.X/modules

tks a lot

**Comment by techscapades** [comment]
> Was running into this issue. Just followed this video tutorial though and the solution is to link in the path in cmake.
> https://youtu.be/TT3_dlPL4vo?t=372

LMAO THIS WORKED

**Comment by Joeng22** [comment]
Compile opencv with opencv_contrib
Steps:
git clone https://github.com/opencv/opencv_contrib/
cd opencv_contrib/
git checkout origin/4.x
(version should match with opencv version)
cmake -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules/
(opencv_contrib path)
make
make install

**Comment by raphaeldas** [comment]
This steps worked for me:

git clone -b 4.x https://github.com/opencv/opencv_contrib/
cmake -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules/

Thanks for the help

**Comment by Rainweic** [comment]
```
cd <opencv_build_directory>
git clone https://github.com/opencv/opencv_contrib.git
cmake -DOPENCV_EXTRA_MODULES_PATH=<opencvcontrib>/modules <opencv_source_directory>
make -j5
```

**Comment by vadimax** [comment]
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
ocv_init_download: OpenCV source tree is not fetched as git repository. 3rdparty resources will be downloaded from github.com by default.
Detected processor: AMD64
libjpeg-turbo: VERSION = 3.0.3, BUILD = opencv-4.10.0-dev-libjpeg-turbo
SIMD extensions disabled: could not find NASM compiler.  Performance will suffer.
Could NOT find CUDNN (missing: CUDNN_LIBRARY CUDNN_INCLUDE_DIR) (Required is at least version "7.5")
NVCUVID: Header not found, WITH_NVCUVID requires Nvidia decoding library header C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include/nvcuvid.h
NVCUVENC: Header not found, WITH_NVCUVENC requires Nvidia encoding library header C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include/nvEncodeAPI.h
CUDA: Using CUDA_ARCH_BIN=5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0
CUDA: NVCC target flags -D_FORCE_INLINES
Allocator metrics storage type: 'long long'
CMake Error at modules/core/CMakeLists.txt:158 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib


Configuring incomplete, errors occurred!

![OpenCV extra modules failure #1](https://github.com/user-attachments/assets/73255875-7820-465a-ab73-7684ebe6cb91)
