### ISSUE TITLE
DNN, readNetFromTensorflow, assertion fails on addConstNodes,

### ISSUE THREAD

**Issue by nadavb** [opencv/opencv#14218]
I created a simple convolutional net with Python + Tensorflow/keras, and can't load it in Opencv 4.0.1.

The readNetFromTensorflow throws assertion error.

Any ideas, best practices or examples how to export a classic conv networks from tensorflow+keras to .pb and .pbtxt files so they can be loaded with Opencv 4?

**Comment by dkurt** [comment]
Please provide a minimal working example or at least attach the mentioned model (`.pb` file).

**Comment by nadavb** [comment]
Thanks @dkurt, here is the .pb file,

[my_model.zip](https://github.com/opencv/opencv/files/3033183/my_model.zip)

Let me know if you need more info, like the code that created the layers (it's a very simple network).

**Comment by dkurt** [comment]
@nadavb, you need to disable training phase before model serialization:

![image](https://user-images.githubusercontent.com/25801568/55392391-e1255200-5543-11e9-8a21-f762e7bee32a.png)

**Comment by nadavb** [comment]
@dkurt, it worked.

1. I recommend, if it's possible, to add a more meaningful errors messages in these cases. In addition to writing "Tensor's data type is not supported", you can add the name of the Tensor that is not supported, and this way the "keras_learning_phase" name would have been popped out more easily so it would be feasible to debug it.

2. For the record, the way I removed this is by saving the keras model to hdf5 file, then set:
[tf.keras.backend.set_learning_phase(0)](url)
Then create the model *again*, and load the weights from the filesystem (model.load_weights), and only then serialize it to a .pb file.
