### ISSUE TITLE
contours.py problem

### ISSUE THREAD

**Issue by toncho11** [opencv/opencv#14213]
In opencv/samples/python/contours.py 

the function cv.FindContours takes two 3 output variables, but it works only with 2.

img,c,h=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

should be

c,h=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

**Comment by alalek** [comment]
Check used/loaded OpenCV version (why did you ignore issues template?).

**Comment by toncho11** [comment]
You definitely do not need help ...

Opencv 4.01 with Python 3.7.0

**Comment by alalek** [comment]
Check [sample code from OpenCV 4.0.1](https://github.com/opencv/opencv/blob/4.0.1/samples/python/contours.py#L57):
```
contours0, hierarchy = cv.findContours( img.copy(), cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
```

Similar code is on the HEAD of the `master` branch.

Probably you have code from [3.4 branch](https://github.com/opencv/opencv/blob/3.4.5/samples/python/contours.py#L57).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
