### ISSUE TITLE
error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\dnn\src\darknet\darknet_io.cpp:503: error: (-212) Unknown layer type: shortcut in function cv::dnn::darknet::ReadDarknetFromCfgFile

### ISSUE THREAD

**Issue by MohamedGimmiy** [opencv/opencv#14216]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by dkurt** [comment]
> error: OpenCV(3.4.1)

please use a newer version. YOLO v3 is supported since https://github.com/opencv/opencv/pull/11322 (OpenCV 3.4.2 at least).

**Comment by MohamedGimmiy** [comment]
i am using open cv 4.0.0 @dkurt

**Comment by alalek** [comment]
No, you don't:

> error: OpenCV(3.4.1)

**Comment by MohamedGimmiy** [comment]
Thanks i checked the version i t was 3.4.1  @alalek  @dkurt
