### ISSUE TITLE
imread in opencv4.0.1 constantly fails

### ISSUE THREAD

**Issue by Happylkx** [opencv/opencv#14221]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

While using "opencv_world401.dll", imread() always fails to read image from file, but it works fine with "opencv_world401d.dll".

It seems like the file pointer is null and the image file cannot be read.

**Comment by alalek** [comment]
Debug/Release mess?

**Comment by Happylkx** [comment]
Sorry, I forgot to remove the debug lib. It works fine now.
