### ISSUE TITLE
DNN, readNetFromTensorflow, assertion fails on addConstNodes

### ISSUE THREAD

**Issue by sangjoonhong** [opencv/opencv#14224]
##### System information (version)
- OpenCV => 4.0.1 / 3.4.5, I tested various version.
- Operating System / Platform => Ubuntu 16.04

##### Detailed description
I also faced the same problem, and tried many things but failed to fix the problem.
(https://github.com/opencv/opencv/issues/14218)
I'll Attach the model I tried. This model is MobileFaceNet based on mobilenet_v2
(https://github.com/sirius-ai/MobileFaceNet_TF)

**frozen_model.pb** is the model I tried the first time, and
**frozen_inference_graph_opt** was generated through **optimize_for_inference.py**

I have been blocked during few weeks with this problem.
If you need more information, I will give you it as soon as possible.
Plz help me...

[frozen_models.zip](https://github.com/opencv/opencv/files/3032704/frozen_models.zip)

**Comment by dkurt** [comment]
The problem is in `Switch` nodes. Looks like TensorFlow tools cannot remove it despite their inputs are `false` boolean constants.

![image](https://user-images.githubusercontent.com/25801568/55391990-15e4d980-5543-11e9-957e-48f06dd099d8.png)

similar problem but with different subgraph: https://github.com/opencv/opencv/issues/14073

**Comment by dkurt** [comment]
@sangjoonhong, There is a workaround:

```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

graph = 'frozen_inference_graph_opt.pb'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    for i in reversed(range(len(graph_def.node))):
        op = graph_def.node[i].op
        name = graph_def.node[i].name

        if op == 'Switch' or op == 'Merge':
            inp = graph_def.node[i].input[0]
            for node in graph_def.node:
                for j in range(len(node.input)):
                    if name == node.input[j]:
                        node.input[j] = inp
            del graph_def.node[i]

    graph_def = TransformGraph(graph_def, ["img_inputs"], ["embeddings"], ["strip_unused_nodes"])
    with tf.gfile.FastGFile("graph.pb", 'wb') as f:
        f.write(graph_def.SerializeToString())
```

However we'll try to propose a PR to fix it.

**Comment by sangjoonhong** [comment]
@dkurt Thank you!! It works well.

**Comment by dkurt** [comment]
@sangjoonhong, BTW, can you run `frozen_inference_graph_opt.pb` using TensorFlow? I got the following error with TF 1.12.0:

```
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node MobileFaceNet/MobileFaceNet/Conv2d_0/BatchNorm/cond_1/AssignMovingAvg_1/decay}} = Const[_class=["loc:@MobileFaceNet/Conv2d_0/BatchNorm/moving_variance"], dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 0.005>](MobileFaceNet/MobileFaceNet/Conv2d_0/BatchNorm/cond_1/Switch:1)
```

**Comment by sangjoonhong** [comment]
@dkurt I'm using TF version 1.13. 
I only tested frozen_model.pb using TF.
frozen_inference_graph_opt.pb was generated for opencv. so I didn't test using TF

**Comment by dkurt** [comment]
@sangjoonhong, This PR now handle this workaround: https://github.com/opencv/opencv/pull/14251
