### ISSUE TITLE
problem:cv::imwrite()

### ISSUE THREAD

**Issue by PeachBlossomIsland** [opencv/opencv#14230]
When I use cv: imwirte () on vs2017, it always reports an error message "pointer exception, access conflict occurs in read location",the version is opencv3.4.4 and the vs2017 model is X64 DEBUG.
the code:
```
       cv::Mat imag = cv::Mat(512, 512, CV_16U, pixData16);
	vector<int> compression_params;
	compression_params.push_back(CV_IMWRITE_PNG_COMPRESSION); 
	compression_params.push_back(9);  
	cv::imwrite(path, imag, compression_params);
```
thank you!

**Comment by alalek** [comment]
> pixData16

What is it?

Check your input first:
```
std::cout << imag << std::endl;
```

> Debug

Stack trace is required for crashes.

**Comment by PeachBlossomIsland** [comment]
> > pixData16
> 
> What is it?
> 
> Check your input first:
> 
> ```
> std::cout << imag << std::endl;
> ```
> > Debug
> 
> Stack trace is required for crashes.

![捕获2](https://user-images.githubusercontent.com/29038514/55412301-c41b6e00-5599-11e9-93d9-e3b892707641.PNG)
this is stack trace.Sometimes it's normal and there's no mistake.thank you!

**Comment by PeachBlossomIsland** [comment]
> > pixData16
> 
> What is it?
> 
> Check your input first:
> 
> ```
> std::cout << imag << std::endl;
> ```
> > Debug
> 
> Stack trace is required for crashes.

The variable ”imag“ is problematic.my main problem is that Why is the program sometimes normal?the program is the same.thank you!

**Comment by alalek** [comment]
You create Mat using pointer on some memory via `pixData16`.
This usage is for advanced users (it is developer responsibility to guarantee proper size and lifetime of underlying buffer).

Don't expect answers here (especially without complete minimal reproducers).
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
