### ISSUE TITLE
readNetFromTensorflow  crash,  in    "else if (type == "FusedBatchNorm") {  //break here }"

### ISSUE THREAD

**Issue by ib198669** [opencv/opencv#14236]
System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2015
- Train System =>  Keras + inceptionV3 + tensorflow1.13 +Ubuntu14

My C++ code :
<pre>
<code>
...
String tf_pb_file = "mosaic.model.pb";
Net net = readNetFromTensorflow(tf_pb_file);  //crash here!!!
...
</code></pre>

Code in tf_importer.cpp   crashed in line 1506
<pre><code>
        else if (type == "FusedBatchNorm")
        {
            ... ... 
            if (isTraining)
            {
                if (layerParams.blobs.size() == 2)
                    CV_Error(Error::StsNotImplemented, "Cannot determine number "
                             "of parameters for batch normalization layer.");
                //Crashed here!
                mean = Mat::zeros(1, layerParams.blobs[3].total(), CV_32F);
</code></pre>

the node of FusedBatchNorm in my model is as follows, I think there might be someting wrong with the attribute 'is_training' :
<img width="915" alt="360截图18141217433342" src="https://user-images.githubusercontent.com/14754815/55453766-c91b0480-560f-11e9-819f-70b810303e72.png">

My ‘.pb’ package is in the  [My Google Network disk](https://drive.google.com/file/d/1ChS-Zcg_2jaIyXQ5vhPjUggSmuhiorFa/view?usp=sharing)  ,  I will appreciate it if you can help me ~!

**Comment by dkurt** [comment]
Try to turn Keras's training phase to false because this model serialized in the training mode.

**Comment by ib198669** [comment]
> Try to turn Keras's training phase to false because this model serialized in the training mode.

I've tried  many ways to turn Keras's training phase to false ,  but I failed ,  is that OK if you tell me how to do that  ?    

Error shows as this ：
node.attr['is_training'] = False
ValueError: Direct assignment of submessage not allowed

I've tried the following way, but failed :
<pre><code>

def h5_to_pb(h5_model,output_dir,model_name,out_prefix = "output_",log_tensorboard = True):

    if osp.exists(output_dir) == False:
        os.mkdir(output_dir)
        
    out_nodes = []
    for i in range(len(h5_model.outputs)):
        out_nodes.append(out_prefix + str(i + 1))
        tf.identity(h5_model.output[i],out_prefix + str(i + 1))

    from tensorflow.python.framework import graph_util,graph_io
    sess = K.get_session()
    init_graph = sess.graph.as_graph_def()

    for i in range(len(init_graph.node)):
        node = init_graph.node[i]
        print('node %d :'%i) 
        print (node)
        if node.op == 'FusedBatchNorm':
            if 'is_training' in node.attr: 
                node.attr['is_training'] = False
    main_graph = graph_util.convert_variables_to_constants(sess,init_graph,out_nodes)
    graph_io.write_graph(main_graph,output_dir,name = model_name,as_text = False)

    ## save graph in tensorboard 
    if log_tensorboard:
         from tensorflow.python.tools import import_pb_to_tensorboard
         import_pb_to_tensorboard.import_to_tensorboard(osp.join(output_dir,model_name),output_dir)
</code></pre>

**Comment by dkurt** [comment]
@ib198669, Take a look at https://keras.io/backend/#set_learning_phase

**Comment by ib198669** [comment]
> @ib198669, Take a look at https://keras.io/backend/#set_learning_phase

Thanks @dkurt ,  I have tried to set_learning_phase(0), but it seems it doesn't hep .  It displays is_training phase is True in tensorboard  as well .
my code :
<pre><code>
    from tensorflow.python.framework import graph_util,graph_io
    sess = K.get_session()
    init_graph = sess.graph.as_graph_def()
    K.set_learning_phase(0)
    main_graph = graph_util.convert_variables_to_constants(sess,init_graph,out_nodes)
    graph_io.write_graph(main_graph,output_dir,name = model_name,as_text = False)
</code></pre>

**Comment by dkurt** [comment]
@ib198669, Thank you. We've also found a bug analyzing this model so you need to apply these changes to the code: https://github.com/opencv/opencv/pull/14284.

To enable this model in OpenCV please do the following:
```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph
from tensorflow.python.tools import optimize_for_inference_lib

with tf.gfile.FastGFile('mosaic.model.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    graph_def = TransformGraph(graph_def, ["input_1"], ["dense_2/Softmax"], ["fold_constants", "sort_by_execution_order"])
    graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def, ['input_1'], ['dense_2/Softmax'], tf.float32.as_datatype_enum)
    with tf.gfile.FastGFile("graph.pb", 'wb') as f:
        f.write(graph_def.SerializeToString())
```

Then import `graph.pb` with OpenCV.

**Comment by ib198669** [comment]
@dkurt  Thanks .  After I tried the code  you gave me above  , it crashed as well . It crashed in bellow code   when type is 'Switch' .
in tf_importer.cpp in line 1905:   it crashed here when parsing layer "batch_normalization_94/cond/FusedBatchNorm/Switch_3"
<pre><code>
            for (int i = 0; i < layer.input_size(); ++i)
            {
                if (value_id.find(layer.input(i)) != value_id.end())
                {
                     //it crashed here  line 1905
                    Mat blob = getTensorContent(getConstBlob(layer, value_id, i));
                    layerParams.blobs.push_back(blob);
                }
                else
                    inputsNames.push_back(layer.input(i));
            }
</code></pre>

crashed  in tf_graph_simplifier.cpp in line 773  when Tensor's data type shows as DT_BOOL
<pre><code>
            //crashed here in tf_graph_simplifier.cpp in line 773 
            CV_Error(Error::StsError, "Tensor's data type is not supported");
</code></pre>

**Comment by dkurt** [comment]
@ib198669, make sure you use the latest state of OpenCV (especially the changes from https://github.com/opencv/opencv/pull/14251).

**Comment by ib198669** [comment]
@dkurt  thanks a lot .  After update the newest code of opencv(4.10)  and modify the dnn code as #14284 ,  the bug is gone .
