### ISSUE TITLE
Simple crash on using save method

### ISSUE THREAD

**Issue by jtlz2** [opencv/opencv#14231]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => macOS 10.13.6
- Compiler => Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37:05), IPython 5.8.0

##### Detailed description

From within ipython, trying to "save" a keypoint detector (ORB here) causes a crash:

libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.3) /Users/travis/build/skvark/opencv-python/opencv/modules/core/src/persistence_yml.cpp:785: error: (-2:Unspecified error) EndWriteStruct w/o matching StartWriteStruct in function 'icvYMLEndWriteStruct'

Abort trap: 6

##### Steps to reproduce

```.py
    import cv2
    cv2.ORB_create().save('test.yaml')
```

**Comment by alalek** [comment]
> save

It was buggy, and it is not available anymore in fresh releases.

Use `.write()` instead (including 3.4.3).

Can't reproduce with current HEAD of 3.4 branch.
