### ISSUE TITLE
cv2.dnn.readNet fail to load crnn

### ISSUE THREAD

**Issue by LJXLJXLJX** [opencv/opencv#14240]
- OpenCV => 4.0.1 (python)
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Python 3.6.3 |Anaconda custom (64-bit)

I have trained a crnn model for text image recognition, I froze it and it works well with tensorflow.
But when tried to use cv2.dnn.ReadNet to load it, some error occurred.

> error: OpenCV(4.0.1) D:\Build\OpenCV\opencv-4.0.1\modules\dnn\src\tensorflow\tf_importer.cpp:1125: error: (-213:The function/feature is not implemented) Unsupported squeeze configuration in function 'cv::dnn::dnn4_v20181221::`anonymous-namespace'::TFImporter::populateNet'

Here is my [pb file](https://suall-my.sharepoint.com/:u:/g/personal/46093_officeent_top/EcBajQ9kgNNNoPxu-aWF4sIBEET6kj0XZ8M0D_LC8BngQw?e=E5xZWk).

**Comment by LJXLJXLJX** [comment]
I have debugged the program with the source code of version 4.1.0, I found the exception was raised here
```C++
void blobFromTensor(const tensorflow::TensorProto &tensor, Mat &dstBlob)
{
    switch (tensor.dtype()) {
        case tensorflow::DT_FLOAT:
        case tensorflow::DT_HALF:
            parseTensor<float>(tensor, dstBlob);
            break;
        case tensorflow::DT_DOUBLE:
            parseTensor<double>(tensor, dstBlob);
            break;
        default:
            CV_Error(Error::StsError, "Tensor's data type is not supported");
            break;
    }

```
The tensor.dtype() here is 3 (DT_INT32), it seems not be implemented now, how can I implement it myself? I am in a emergency now.

**Comment by LJXLJXLJX** [comment]
The layer name here is 
"shadow_net/sequence_rnn_module/stack_bidirectional_rnn/cell_1/bidirectional_rnn/bw/bw/concat_2"

I am trying to convert the dtype to DT_FLOAT simply.

**Comment by LJXLJXLJX** [comment]
Unfortunately, type == "Squeeze" hasn't been implemented currently.

**Comment by themechanicalcoder** [comment]
@LJXLJXLJX  could you find the solution to this problem I am also trying to read crnn model using opencv's ```readNet ```function and I get the following error. I used the pretrained model from [this repo](https://github.com/MaybeShewill-CV/CRNN_Tensorflow) and to convert the model to frozen graph I followed [this tutorial](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_CRNN_From_Tensorflow.html)
Here is the error I get 
code
```
import cv2
net = cv2.dnn.readNet("D:\\CRNN_Tensorflow\\frozen_graph.pb")

```
```
Traceback (most recent call last):
  File "D:/CRNN_Tensorflow/tools/test.py", line 2, in <module>
    net = cv2.dnn.readNet("D:\\CRNN_Tensorflow\\frozen_graph.pb")
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:155: error: (-2:Unspecified error) Tensor's data type is not supported in function 'cv::dnn::dnn4_v20191202::`anonymous-namespace'::blobFromTensor'
```



model link  [frozen_graph.pb](https://drive.google.com/open?id=17gOw2qNcC27miWz-C1aAMtROq8mdnmz7)

**Comment by LJXLJXLJX** [comment]
@themechanicalcoder 
No, opencv seems doesn't support BiLSTM yet. 
But CRNN is CNN+BiLSTM+CTC. You can try remove BiLSTM from your model. CNN+CTC is enough.
If you don't want to remove BiLSTM, just use tensorflow to inference.

**Comment by gangrim** [comment]
@LJXLJXLJX, @themechanicalcoder 
How are you?
Have you been solved your issue for loading crnn model in opencv  yet?
Now i met this issue.
If you solved, could you tell me about solution, thanks!

**Comment by themechanicalcoder** [comment]
> @LJXLJXLJX, @themechanicalcoder
> How are you?
> Have you been solved your issue for loading crnn model in opencv yet?
> Now i met this issue.
> If you solved, could you tell me about solution, thanks!

Yes now BiLSTM can be used from  ONNX model. I have also contributed  code for Real-Time Text Recognition to OpenCV  you can see this issue https://github.com/opencv/opencv/issues/16662 and the text recognition sample https://github.com/opencv/opencv/pull/16955
