### ISSUE TITLE
OpenVino 2019 R1 - OpenCV4 Support

### ISSUE THREAD

**Issue by balachandarsv** [opencv/opencv#14246]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Mac

##### Detailed description

Openvino 2019 R1 is available for mac now. 
I am trying to build opencv from source with Inference Engine. But the build fails while compiling dnn module. When will the latest version be supported ?

Thanks in advance.

**Comment by dkurt** [comment]
> But the build fails while compiling dnn module

Fails how? What is a error message?

Have you specified cmake's variable `INF_ENGINE_RELEASE` as `201905000`? (It'll be default after https://github.com/opencv/opencv/pull/14241 merged to master branch).

**Comment by balachandarsv** [comment]
Thanks @dkurt and @alalek . Now I can build from master branch. But I am facing this issue though. 

/tmp/open/opencv-master/modules/dnn/src/op_inf_engine.cpp:811: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Unsupported primitive of type: PriorBoxClustered name: PriorBox_5 in function 'initPlugin'

May be this might have something to do with this error. I am using mac.
https://github.com/opencv/opencv/blob/master/modules/dnn/src/op_inf_engine.cpp#L785

It works for simple models which doesn't use any extra layer libraries.

**Comment by dkurt** [comment]
Looks like we need to add corresponding condition. Feel free to open a PR.

```cpp
#elif defined(__APPLE__)
std::string libName = "libcpu_extension" + suffixes[i] + ".dylib"
```

**Comment by balachandarsv** [comment]
Will test once and give a PR
