### ISSUE TITLE
Homogenous precision

### ISSUE THREAD

**Issue by bhack** [opencv/opencv#14242]
Can we have an `inf` at https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L970 if  `1e-39>=sptr[i].z<=1e-45`?

**Comment by mshabunin** [comment]
Do you mean we should replace `ptr[i].z != 0.f` with `std::abs(ptr[i].z) < FLT_EPSILON`?

**Comment by bhack** [comment]
Yes

**Comment by manasbedmutha98** [comment]
On it.

**Comment by manasbedmutha98** [comment]
Hi. I am new to C++ and open source. I have added a pull request for this issue at #14289. Is it correct?

**Comment by thangktran** [comment]
are you still working on this issue @manasbedmutha98?

**Comment by ostarling** [comment]
Hi. Sorry if I'm jumping the gun, thought that this issues is an easy starter given that the original contributor was quiet for 2 weeks.

**Comment by thangktran** [comment]
> Hi. Sorry if I'm jumping the gun, thought that this issues is an easy starter given that the original contributor was quiet for 2 weeks.

Sure no problem. But please let everybody knows when you're working on an issue to avoid collision.
