### ISSUE TITLE
DNN module with OpenCL results in mismatch against CPU based prediction

### ISSUE THREAD

**Issue by TouqeerAhmad** [opencv/opencv#14248]
##### System information (version)

- OpenCV => 4.0.1 building from source 
- Operating System / Platform => macOS High Sierra, 10.13.3
- Compiler => 

##### Detailed description

Trying to see any speedup possible for my simple Tensorflow network. I have build OpenCV with OpenCL target, however when I set the preferable target to OpenCL using 

net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);

I see the following message:

"OpenCV(ocl4dnn): consider to specify kernel configuration cache directory 
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -43: CL_INVALID_BUILD_OPTIONS
-cl-no-subgroup-ifp -D AMD_DEVICE"

Also, numerically the prediction is different than what I get from running directly on CPU. Running the following code snippet produces the positive output which verifies OpenCL being available. 

############## Code Snippet #################
    if (!cv::ocl::haveOpenCL())
        cout << "OpenCL is not available..." << endl;
    else
        cout << "OpenCL is AVAILABLE! :) " << endl; //this is the output    
    cv::ocl::setUseOpenCL(true);    
    cv::ocl::Context ctx = cv::ocl::Context::getDefault();    
    cout << ctx.ndevices() << " GPU devices are detected." << endl;
    for (int i = 0; i < ctx.ndevices(); i++)
    {
        cv::ocl::Device device = ctx.device(i);
        cout << "name:              " << device.name() << endl;
        cout << "available:         " << device.available() << endl;
        cout << "imageSupport:      " << device.imageSupport() << endl;
        cout << "OpenCL_C_Version:  " << device.OpenCL_C_Version() << endl;
        cout << endl;
    } //this works & i can see my video card name & opencl version
    cv::ocl::Device(ctx.device(0));

############### Output ######################

OpenCL is AVAILABLE! :) 
1 GPU devices are detected.
name:              AMD Radeon R9 M395X Compute Engine
available:         1
imageSupport:      1
OpenCL_C_Version:  OpenCL C 1.2

Is this a bug in OpenCV or am I overlooking a step in building OpenCv with OpenCL. Looking for help and feedback!

**Comment by alalek** [comment]
1. Don't create duplicated, edit them instead: #14247 
2. "I see the following message" - use search for similar issues.
3. Floating point computations don't guarantee **bit-exact** results between platforms / accelerators, so results may differ.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by TouqeerAhmad** [comment]
The difference is much bigger than to be bit-exact. Sorry about the duplicated ones. Checked in the answers.opencv.org as well -- was not sure if it is an OpenCV bug. I've now verified on two different iMac and it seems to be consistent with two different installations of 4.0.1.

Thanks!

**Comment by dkurt** [comment]
@TouqeerAhmad, Have you tried to update OpenCL? How you compare the difference between targets? Please provide a reproducer.

**Comment by TouqeerAhmad** [comment]
Sorry about the late reply.
I'm working on iMac, and Apple has not updated OpenCL to current versions, it is still at 1.2.

**Comment by TouqeerAhmad** [comment]
current versions of OpenCL on the iMacs ...
https://support.apple.com/en-us/HT202823

**Comment by dkurt** [comment]
@TouqeerAhmad, In this issue https://github.com/opencv/opencv/issues/10465 I added a list of tests which are failed with old Intel GPU as well.

May I ask you to run accuracy tests and provide a list of failed tests as well?

**Comment by TouqeerAhmad** [comment]
@dkurt please find below the result of running 'opencv_perf_dnn' test:

Touqeers-iMac:bin touqeera$ ./opencv_perf_dnn 
Time compensation is 0
CTEST_FULL_OUTPUT
OpenCV version: 4.1.0-pre
OpenCV VCS version: unknown
Build type: Release
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 9.0.0.9000039)
Parallel framework: gcd
CPU features: SSE SSE2 SSE3 SSSE3 SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2019.0.0 Gold (-) Jul 25 2018
OpenCL Platforms: 
    Apple
        CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (OpenCL 1.2 )
        dGPU: AMD Radeon R9 M395X Compute Engine (OpenCL 1.2 )
Current OpenCL device: 
    Type = dGPU
    Name = AMD Radeon R9 M395X Compute Engine
    Version = OpenCL 1.2 
    Driver version = 1.2 (Dec 20 2017 17:28:06)
    Address bits = 32
    Compute units = 32
    Max work group size = 256
    Local memory size = 32 KB
    Max memory allocation size = 1 GB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_APPLE_SetMemObjectDestructor
        cl_APPLE_ContextLoggingFunctions
        cl_APPLE_clut
        cl_APPLE_query_kernel_names
        cl_APPLE_gl_sharing
        cl_khr_gl_event
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_byte_addressable_store
        cl_khr_image2d_from_buffer
        cl_khr_depth_images
        cl_APPLE_command_queue_priority
        cl_APPLE_command_queue_select_compute_units
        cl_khr_fp64
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 4
    Preferred vector width short = 2
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
[==========] Running 357 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 300 tests from Conv
[ RUN      ] Conv.conv/0, where GetParam() = (GFLOPS=10.087, K=[3 x 3], IN={1, 576, 38, 50}, OCN=512, PM=SAME, BIAS, OCV/OCL)
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory 
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -43: CL_INVALID_BUILD_OPTIONS
-cl-no-subgroup-ifp -D AMD_DEVICE

IN=4275 Kb [ 1 576 38 50 ]    OUT=3800 Kb [ 1 512 38 50 ]    Weights(parameters): 10370 Kb    MFLOPS=10087
[ PERFSTAT ]    (samples=10   mean=63.67   median=63.82   min=63.09   stddev=0.31 (0.5%))
[       OK ] Conv.conv/0 (867 ms)
[ RUN      ] Conv.conv/1, where GetParam() = (GFLOPS=10.087, K=[3 x 3], IN={1, 576, 38, 50}, OCN=512, PM=SAME, BIAS, OCV/OCL_FP16)
IN=4275 Kb [ 1 576 38 50 ]    OUT=3800 Kb [ 1 512 38 50 ]    Weights(parameters): 10370 Kb    MFLOPS=10087
[ PERFSTAT ]    (samples=10   mean=63.51   median=63.53   min=63.07   stddev=0.21 (0.3%))
[       OK ] Conv.conv/1 (715 ms)
[ RUN      ] Conv.conv/2, where GetParam() = (GFLOPS=10.087, K=[3 x 3], IN={1, 576, 38, 50}, OCN=512, PM=SAME, BIAS, OCV/CPU)
IN=4275 Kb [ 1 576 38 50 ]    OUT=3800 Kb [ 1 512 38 50 ]    Weights(parameters): 10370 Kb    MFLOPS=10087
[ PERFSTAT ]    (samples=100   mean=32.31   median=32.37   min=28.35   stddev=2.13 (6.6%))
[       OK ] Conv.conv/2 (3326 ms)
[ RUN      ] Conv.conv/3, where GetParam() = (GFLOPS=1.704, K=[3 x 3], IN={1, 512, 19, 19}, OCN=512, G=512, P=[1 x 1], BIAS, OCV/OCL)
IN=722 Kb [ 1 512 19 19 ]    OUT=722 Kb [ 1 512 19 19 ]    Weights(parameters): 20 Kb    MFLOPS=1703.6
[ PERFSTAT ]    (samples=16   mean=16.86   median=16.75   min=16.19   stddev=0.51 (3.0%))
[       OK ] Conv.conv/3 (328 ms)
[ RUN      ] Conv.conv/4, where GetParam() = (GFLOPS=1.704, K=[3 x 3], IN={1, 512, 19, 19}, OCN=512, G=512, P=[1 x 1], BIAS, OCV/OCL_FP16)
IN=722 Kb [ 1 512 19 19 ]    OUT=722 Kb [ 1 512 19 19 ]    Weights(parameters): 20 Kb    MFLOPS=1703.6
[ PERFSTAT ]    (samples=100   mean=16.52   median=16.54   min=14.78   stddev=0.51 (3.1%))
[       OK ] Conv.conv/4 (1696 ms)
[ RUN      ] Conv.conv/5, where GetParam() = (GFLOPS=1.704, K=[3 x 3], IN={1, 512, 19, 19}, OCN=512, G=512, P=[1 x 1], BIAS, OCV/CPU)
IN=722 Kb [ 1 512 19 19 ]    OUT=722 Kb [ 1 512 19 19 ]    Weights(parameters): 20 Kb    MFLOPS=1703.6
[ PERFSTAT ]    (samples=100   mean=0.69   median=0.66   min=0.55   stddev=0.10 (15.2%))
[       OK ] Conv.conv/5 (81 ms)
[ RUN      ] Conv.conv/6, where GetParam() = (GFLOPS=1.704, K=[3 x 3], IN={1, 512, 19, 19}, OCN=512, PM=SAME, OCV/OCL)
IN=722 Kb [ 1 512 19 19 ]    OUT=722 Kb [ 1 512 19 19 ]    Weights(parameters): 9216 Kb    MFLOPS=1703.6
[ PERFSTAT ]    (samples=38   mean=9.36   median=9.32   min=9.12   stddev=0.27 (2.9%))
[       OK ] Conv.conv/6 (404 ms)
[ RUN      ] Conv.conv/7, where GetParam() = (GFLOPS=1.704, K=[3 x 3], IN={1, 512, 19, 19}, OCN=512, PM=SAME, OCV/OCL_FP16)

**Comment by TouqeerAhmad** [comment]
I can also see the message PASSED 357 tests.

**Comment by TouqeerAhmad** [comment]
Looking at the log carefully, it is showing the same messages as I mentioned in my original concern:

OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -43: CL_INVALID_BUILD_OPTIONS
-cl-no-subgroup-ifp -D AMD_DEVICE

**Comment by alalek** [comment]
> ask you to run accuracy tests
> opencv_perf_dnn

It should be `opencv_test_dnn`.
Also there are should be minimal number of **skipped** tests (or you didn't download DNN models or specify `OPENCV_DNN_TEST_DATA_PATH` / `OPENCV_TEST_DATA_PATH` variables).

**Comment by TouqeerAhmad** [comment]
My bad, ran the opencv_test_dnn -- here is what I am getting at the top, the entire run is too big to share. Most of test are now failing and the end it shows a message saying '144 FAILED TEST'

Touqeers-iMac:bin touqeera$ ./opencv_test_dnn
CTEST_FULL_OUTPUT
OpenCV version: 4.1.0-pre
OpenCV VCS version: unknown
Build type: Release
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 9.0.0.9000039)
Parallel framework: gcd
CPU features: SSE SSE2 SSE3 SSSE3 SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2019.0.0 Gold (-) Jul 25 2018
OpenCL Platforms: 
    Apple
        CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (OpenCL 1.2 )
        dGPU: AMD Radeon R9 M395X Compute Engine (OpenCL 1.2 )
Current OpenCL device: 
    Type = dGPU
    Name = AMD Radeon R9 M395X Compute Engine
    Version = OpenCL 1.2 
    Driver version = 1.2 (Dec 20 2017 17:28:06)
    Address bits = 32
    Compute units = 32
    Max work group size = 256
    Local memory size = 32 KB
    Max memory allocation size = 1 GB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_APPLE_SetMemObjectDestructor
        cl_APPLE_ContextLoggingFunctions
        cl_APPLE_clut
        cl_APPLE_query_kernel_names
        cl_APPLE_gl_sharing
        cl_khr_gl_event
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_byte_addressable_store
        cl_khr_image2d_from_buffer
        cl_khr_depth_images
        cl_APPLE_command_queue_priority
        cl_APPLE_command_queue_select_compute_units
        cl_khr_fp64
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 4
    Preferred vector width short = 2
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
[==========] Running 1867 tests from 61 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from Test_Caffe
[ RUN      ] Test_Caffe.memory_read
[     SKIP ] OpenCV tests: Can't find data file: dnn/bvlc_googlenet.prototxt
[       OK ] Test_Caffe.memory_read (1 ms)
[ RUN      ] Test_Caffe.read_gtsrb
unknown file: Failure
C++ exception with description "OpenCV(4.1.0-pre) /Users/touqeera/work/opencv-master2/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/dnn/gtsrb.prototxt" in function 'ReadProtoFromTextFile'
" thrown in the test body.
[  FAILED  ] Test_Caffe.read_gtsrb (1 ms)
[ RUN      ] Test_Caffe.read_googlenet
unknown file: Failure
C++ exception with description "OpenCV(4.1.0-pre) /Users/touqeera/work/opencv-master2/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/dnn/bvlc_googlenet.prototxt" in function 'ReadProtoFromTextFile'
" thrown in the test body.
[  FAILED  ] Test_Caffe.read_googlenet (0 ms)
[ RUN      ] Test_Caffe.multiple_inputs
[     SKIP ] OpenCV tests: Can't find data file: dnn/layers/net_input.prototxt
[       OK ] Test_Caffe.multiple_inputs (0 ms)
[ RUN      ] Test_Caffe.shared_weights
[     SKIP ] OpenCV tests: Can't find data file: dnn/layers/shared_weights.prototxt
[       OK ] Test_Caffe.shared_weights (0 ms)
[----------] 5 tests from Test_Caffe (2 ms total)

[----------] 1 test from Reproducibility_FCN

**Comment by dkurt** [comment]
@TouqeerAhmad, You need to have https://github.com/opencv/opencv_extra test data (also models downloaded by [download_models.py](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py)). Then set the following env:
```
OPENCV_TEST_DATA_PATH=/path/to/opencv_extra/testdata
OPENCV_DNN_TEST_DATA_PATH=/path/to/opencv_extra/testdata
```
