### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by TanishaShrotriya96** [opencv/opencv#14243]
**System Information:**

    OpenCV => 4.0.0

**Detailed description:** 

This tutorial may not be up to date with the current code in the repository. There is a variable "mean" which is also given as an input in the command line arguments in the older version. This is no longer there in the latest code.
[Link to Tutorial](https://docs.opencv.org/3.4.2/d5/de7/tutorial_dnn_googlenet.html)
[Link to Code](https://github.com/opencv/opencv/blob/3.4/samples/dnn/classification.cpp)

I would like to update it, if possible.

_Originally posted by @TanishaShrotriya96 in https://github.com/opencv/opencv/issues/14148#issuecomment-479574156_

**Comment by dkurt** [comment]
> [Link to Tutorial](https://docs.opencv.org/3.4.2/d5/de7/tutorial_dnn_googlenet.html)

3.4.2 ?

**Comment by alalek** [comment]
> I would like to update it, if possible.

No way to do this properly.
Documentation is part of code (you can't change documentation without changing code, which is already tagged).

**Comment by dkurt** [comment]
@TanishaShrotriya96, please provide an output from 
```
./example_opencv_classification --help
```
The following procedure adds mean flag:
https://github.com/opencv/opencv/blob/ad5898224dedec79a10a3fd68548048ac2ce1549/samples/dnn/classification.cpp#L40

**Comment by TanishaShrotriya96** [comment]
Yes, I did notice this.
` keys += genPreprocArguments(modelName, zooFile); `

This is the output for -
`$ python classification.py --help`
```
usage: classification.py [-h] [--zoo ZOO] [--input INPUT]
                         [--framework {caffe,tensorflow,torch,darknet}]
                         [--backend {0,1,2,3}] [--target {0,1,2,3}] --model
                         MODEL [--config CONFIG] [--mean MEAN [MEAN ...]]
                         [--scale SCALE] [--width WIDTH] [--height HEIGHT]
                         [--rgb] [--classes CLASSES]
                         [{}]

```
However, for the normal command this is what I get - 

```
$ python classification.py  --model=bvlc_googlenet.caffemodel --config=bvlc_googlenet.prototxt --width=224 --height=224 --classes=classification_classes_ILSVRC2012.txt --input=sample.jpg --mean="104 117 123"
```
```usage: classification.py [-h] [--zoo ZOO] [--input INPUT]
                         [--framework {caffe,tensorflow,torch,darknet}]
                         [--backend {0,1,2,3}] [--target {0,1,2,3}] --model
                         MODEL [--config CONFIG] [--mean MEAN [MEAN ...]]
                         [--scale SCALE] [--width WIDTH] [--height HEIGHT]
                         [--rgb] [--classes CLASSES]
                         [{}]
```
`classification.py: error: argument --mean: invalid float value: '104 117 123'`

And the command that does work is - 
```
$ python classification.py  --model=bvlc_googlenet.caffemodel --config=bvlc_googlenet.prototxt --width=224 --height=224 --classes=classification_classes_ILSVRC2012.txt --input=sample.jpg
```

Also, a few of the graphics related functions are not working for me either. I have tried fixing them but there are quite a few ambiguous answers on forums such as StackOverflow. So these three are giving an error- 

`winName = 'Deep learning image classification in OpenCV'`
`cv.namedWindow(winName, cv.WINDOW_NORMAL)`
`while cv.waitKey(1) < 0:`

My OpenCV version right now is 4.0.0

**Comment by dkurt** [comment]
@TanishaShrotriya96, May I ask you to try `--mean 104 117 123`

**Comment by TanishaShrotriya96** [comment]
Yes, I did notice this.
`keys += genPreprocArguments(modelName, zooFile);`

This is the output for -
`$ python classification.py --help`
```
usage: classification.py [-h] [--zoo ZOO] [--input INPUT]
                         [--framework {caffe,tensorflow,torch,darknet}]
                         [--backend {0,1,2,3}] [--target {0,1,2,3}] --model
                         MODEL [--config CONFIG] [--mean MEAN [MEAN ...]]
                         [--scale SCALE] [--width WIDTH] [--height HEIGHT]
                         [--rgb] [--classes CLASSES]
                         [{}]
```
However, for the normal command, this is what I get -
```
$ python classification.py  --model=bvlc_googlenet.caffemodel --config=bvlc_googlenet.prototxt --width=224 --height=224 --classes=classification_classes_ILSVRC2012.txt --input=sample.jpg --mean="104 117 123"
```
```
usage: classification.py [-h] [--zoo ZOO] [--input INPUT]
                         [--framework {caffe,tensorflow,torch,darknet}]
                         [--backend {0,1,2,3}] [--target {0,1,2,3}] --model
                         MODEL [--config CONFIG] [--mean MEAN [MEAN ...]]
                         [--scale SCALE] [--width WIDTH] [--height HEIGHT]
                         [--rgb] [--classes CLASSES]
                         [{}]
```
`classification.py: error: argument --mean: invalid float value: '104 117 123'`

And the command that does work is -
```
$ python classification.py  --model=bvlc_googlenet.caffemodel --config=bvlc_googlenet.prototxt --width=224 --height=224 --classes=classification_classes_ILSVRC2012.txt --input=sample.jpg
```
Also, a few of the graphics related functions are not working for me either. I have tried fixing them but there are quite a few ambiguous answers on forums such as StackOverflow. So these three are giving an error-

`winName = 'Deep learning image classification in OpenCV'`
`cv.namedWindow(winName, cv.WINDOW_NORMAL)`
`while cv.waitKey(1) < 0:`

My OpenCV version right now is 4.0.0, so I thought maybe that isn't backward compatible. However the same command is there in the tutorial. 
[4.0.0 Documentation](https://docs.opencv.org/4.0.0/d5/de7/tutorial_dnn_googlenet.html)

**Comment by TanishaShrotriya96** [comment]
> @TanishaShrotriya96, May I ask you to try `--mean 104 117 123` (without `=` and quotes).

I had tried that -
```
$ python classification.py  --model=bvlc_googlenet.caffemodel --config=bvlc_googlenet.prototxt --width=224 --height=224 --classes=classification_classes_ILSVRC2012.txt --input=space_shuttle.jpg --mean=104 117 123

usage: classification.py [-h] [--zoo ZOO] [--input INPUT]
                         [--framework {caffe,tensorflow,torch,darknet}]
                         [--backend {0,1,2,3}] [--target {0,1,2,3}] --model
                         MODEL [--config CONFIG] [--mean MEAN [MEAN ...]]
                         [--scale SCALE] [--width WIDTH] [--height HEIGHT]
                         [--rgb] [--classes CLASSES]
                         [{}]

classification.py: error: argument alias: invalid choice: '117' (choose from )

```

**Comment by TanishaShrotriya96** [comment]
> @TanishaShrotriya96, May I ask you to try `--mean 104 117 123` (without `=` and quotes).

Okay. Now it is working. Thank you!

**Comment by TanishaShrotriya96** [comment]
I had one last question, is this a system dependent thing? Does the normal tutorial work otherwise?

**Comment by alalek** [comment]
The first links are about C++ tutorial.

You using "python" - so at least, command line parser is different.

**Comment by TanishaShrotriya96** [comment]
Oh, okay. That makes sense. Will keep that in mind. Thank you so much!
