### ISSUE TITLE
Opencv has a function of matching shape template, or extracts contour and edge under complex illumination, and also extracts edge under occlusion？

### ISSUE THREAD

**Issue by honghande** [opencv/opencv#14254]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by honghande** [comment]
No landing.
