### ISSUE TITLE
Problem to inherit a OpenCV class in Swift

### ISSUE THREAD

**Issue by zhouhao27** [opencv/opencv#14250]
##### System information (version)

- OpenCV => :4.0.1
- Operating System / Platform => :10.13.6
- Compiler => Xcode 10.0 GNU++ 11

##### Detailed description

I want to inherit an openCV class **_CvVideoCamera_** in my Swift project. Here is what I did:

1. Create a Objective-C wrapper
2. Create a bridging file to import the header of the wrapper
3. In the header of my Objective-C wrapper

```
#import <opencv2/videoio/cap_ios.h>

@interface VideoCameraImpl: CvVideoCamera

```

Then I got the following error message:

>> opencv2.framework/Headers/core.hpp:49:4: Core.hpp header must be compiled as C++

I know it's possible to moving the import to .mm file is able to fix the issue. But I can't do that because I need to inherit a class from OpenCV and make it public so that I can use it in my Swift project. Is there a way to do this? Thanks.

**Comment by nizenyang** [comment]
你好，这边这个问题解决了吗，我这边和你的问题差不多，也是swift ，但是不知道怎么弄

**Comment by alalek** [comment]
> must be compiled as C++

That is.
