### ISSUE TITLE
Aspect ratio resizing in cv::dnn::blobFromImage

### ISSUE THREAD

**Issue by rubenvb** [opencv/opencv#14253]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Mac OS X 10.14
- Compiler => XCode 9.2

##### Detailed description

cv::dnn::blobFromImage should support aspect-ratio resizing.
It currently warps the image by stretching it if you don't crop.
Making use of cv::copyMakeBorder is a workaround, but IMHO it could be part of the integrated preprocessing. This is especially important if your data has to keep aspect ratio inside the NN.

##### Steps to reproduce

N.A.

**Comment by dkurt** [comment]
@rubenvb, Please provide an example.

**Comment by rubenvb** [comment]
```
cv::Mat image(128, 90, CV_32F);
cv::Size size{128,128};
cv::Mat blob = cv::dnn::blobFromImage(image, 1.0, size, 0.);
```
Here, `blob` will have dimensions 128x128, as requested, but the image's aspect ratio will be changed to 1:1, resulting in a stretched image. For certain types of classification networks, this ruins the results as relative width/height proportions are completely destroyed. An option to keep the aspect ratio (and e.g. zero pad) would save a lot of menial preprocessing.

**Comment by alalek** [comment]
There is no well defined process how to fix any image into network inputs with mismatched aspect ratio:
- fill border
- or crop
- or mix both - partially crop / partially fill

It depends on your application.
OpenCV as library should provide basic well-defined functionality at first. It is a set of basic blocks.
Complex (in meaning set of basic operations), application-specific or rarely used operations should not be added into OpenCV:
- you can still express your actual needs using basic OpenCV functionality.

---

Did you check existed "bool crop=false" parameter of `blobFromImage()`?

**Comment by rubenvb** [comment]
The crop=false parameter will result in the image being stretched. As stated, the result of pushing this through the network is suboptimal and zero-padding it resolves this issue.

There are indeed multiple ways to resolve the size mismatch with a lot of picky details to choose. I can understand if you feel it's not a good fit. Feel free to close the issue in that case.

**Comment by dkurt** [comment]
Closing it.

@rubenvb, For now you may do necessary transformations out of the `blobFromImage`.  However it's a good feature proposal for new [Data augmentation module](https://github.com/opencv/opencv/wiki/GSoC_2019#idea-computer-vision-data-augmentation-module) which is going to be implemented during GSoC.
