### ISSUE TITLE
0x00007FF8F4273FB8 处(位于 testopencv01.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000A922FACC10 处。

### ISSUE THREAD

**Issue by AssiduousOne** [opencv/opencv#14263]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
> std::bad_alloc

That's it. Can't be fixed in OpenCV.
