### ISSUE TITLE
Undefined reference to OpenVINO's TBB

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#14262]
##### System information (version)

- OpenCV => 3.4.x
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 5.4.0

##### Detailed description

With OpenVINO 2019R1:

```
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libinference_engine.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
collect2: error: ld returned 1 exit status
modules/dnn/CMakeFiles/opencv_perf_dnn.dir/build.make:208: recipe for target 'bin/opencv_perf_dnn' failed
make[2]: *** [bin/opencv_perf_dnn] Error 1
CMakeFiles/Makefile2:2452: recipe for target 'modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all' failed
make[1]: *** [modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

```
$ ldd /opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libinference_engine.so

linux-vdso.so.1 =>  (0x00007ffc4c170000)
libtbb.so.2 => /opt/intel/opencl/libtbb.so.2 (0x00007f5757ab0000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5757893000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f575768f000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f575730d000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5757004000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5756dee000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5756a24000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f575681c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f5758398000)
```

TBB from OpenCL is used instead of `/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2`

**Comment by dkurt** [comment]
From OpenVINO's setupvars.sh:

```cmake
    if [[ "$OSTYPE" == "darwin"* ]]; then
        export DYLD_LIBRARY_PATH=$INSTALLDIR/deployment_tools/inference_engine/external/mkltiny_mac/lib:$INSTALLDIR/deployment_tools/inference_engine/external/tbb/lib:$IE_PLUGINS_PATH:$DYLD_LIBRARY_PATH
        export LD_LIBRARY_PATH=$INSTALLDIR/deployment_tools/inference_engine/external/mkltiny_mac/lib:$INSTALLDIR/deployment_tools/inference_engine/external/tbb/lib:$IE_PLUGINS_PATH:$LD_LIBRARY_PATH
    else
        export LD_LIBRARY_PATH=/opt/intel/opencl:$HDDL_INSTALL_DIR/lib:$INSTALLDIR/deployment_tools/inference_engine/external/gna/lib:$INSTALLDIR/deployment_tools/inference_engine/external/mkltiny_lnx/lib:$INSTALLDIR/deployment_tools/inference_engine/external/tbb/lib:$IE_PLUGINS_PATH:$LD_LIBRARY_PATH
    fi
```

So workaround is to replace
```cmake
        export LD_LIBRARY_PATH=/opt/intel/opencl:$HDDL_INSTALL_DIR/lib:$INSTALLDIR/deployment_tools/inference_engine/external/gna/lib:$INSTALLDIR/deployment_tools/inference_engine/external/mkltiny_lnx/lib:$INSTALLDIR/deployment_tools/inference_engine/external/tbb/lib:$IE_PLUGINS_PATH:$LD_LIBRARY_PATH
```
to
```cmake
        export LD_LIBRARY_PATH=$HDDL_INSTALL_DIR/lib:$INSTALLDIR/deployment_tools/inference_engine/external/gna/lib:$INSTALLDIR/deployment_tools/inference_engine/external/mkltiny_lnx/lib:$INSTALLDIR/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/opencl:$IE_PLUGINS_PATH:$LD_LIBRARY_PATH
```

**Comment by alalek** [comment]
I can confirm this problem on systems with installed Intel OpenCL CPU device (which has own TBB version under the same name).

Workaround:
- rename /opt/intel/opencl/libtbb.so.2 from Intel OpenCL (if you don't need Intel OpenCL CPU device).
- or remove /opt/intel/opencl from setupvars.sh

OpenVINO team should drop /opt/intel/opencl entry from these environment variables. By Khronos specification it is not need to include /opt/intel/opencl for making OpenCL work.
How ever using of mismatched version of TBB library can cause bad effects:
- InferenceEngine can't use libtbb2.so from Intel OpenCL CPU device
- Intel OpenCL CPU device implementation perhaps can't work with InferenceEngine's libtbb2.so.

Also there is system-wide libtbb2.so (Ubuntu system package with own version) which can be loaded by some apps.

**Comment by jorge88cs** [comment]
This solution does not work for me

**Comment by jorge88cs** [comment]
After do steps, i have this out now:
$ ldd /opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so

	linux-vdso.so.1 =>  (0x00007ffca31ee000)
	libtbb.so.2 => /opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f2ebe4f8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ebe2db000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2ebe0d7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2ebdd55000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ebda4c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2ebd836000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ebd46c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2ebd264000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2ebeded000)

And my CLion project show this:

//opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so: referencia a `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)' sin definir
collect2: error: ld returned 1 exit status
CMakeFiles/openvino_test.dir/build.make:132: fallo en las instrucciones para el objetivo 'openvino_test'
make[3]: *** [openvino_test] Error 1
CMakeFiles/Makefile2:72: fallo en las instrucciones para el objetivo 'CMakeFiles/openvino_test.dir/all'
make[2]: *** [CMakeFiles/openvino_test.dir/all] Error 2
CMakeFiles/Makefile2:84: fallo en las instrucciones para el objetivo 'CMakeFiles/openvino_test.dir/rule'
make[1]: *** [CMakeFiles/openvino_test.dir/rule] Error 2
Makefile:118: fallo en las instrucciones para el objetivo 'openvino_test'
make: *** [openvino_test] Error 2

Please some help. Thanks you.

**Comment by dkurt** [comment]
@jorge88cs, Have you tried to clean a build folder?

**Comment by alalek** [comment]
> /opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2

Replace this file (with INPUT script) with symbolic link on the file `libtbb.so` from the same folder.

**Comment by jorge88cs** [comment]
Sorry, still not working.
CLion project with same output. Further, i get this:
$ ldd //opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so

//opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so: error while loading shared libraries: /opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2: file too short

Can i do something else.

**Comment by alalek** [comment]
> CLion project

Try to minimize dependencies.
We have no idea how did you run this IDE. Probably it is launched without required environment from OpenVINO's `setupvars.sh`.

Try to grab linker command and run it in proper prepared terminal by yourself.

---

> file too short

It should look like this:

```
$ cd /opt/intel/openvino/inference_engine/external/tbb/lib/
$ ls -al libtbb.so*
-rwxr-xr-x 1 root root      20 Apr  2 10:30 libtbb.so
-rwxr-xr-x 1 root root 2175583 Apr  2 10:30 libtbb.so.2
# rm libtbb.so
# ln -s libtbb.so.2 libtbb.so
$ ls -al libtbb.so*
lrwxrwxrwx 1 root root      11 May 13 21:17 libtbb.so -> libtbb.so.2
-rwxr-xr-x 1 root root 2175583 Apr  2 10:30 libtbb.so.2
```

**Comment by jorge88cs** [comment]
> CLion project
> 
> Try to minimize dependencies.
> We have no idea how did you run this IDE. Probably it is launched without required environment from OpenVINO's `setupvars.sh`.
> 
> Try to grab linker command and run it in proper prepared terminal by yourself.

You are right !! IDE launch app without OpenVINO's eviroments variables "setupvars.sh". Thanks you very much.

**Comment by wf19910313** [comment]
你好，我也出现上面的问题，//opt/intel/openvino/inference_engine/lib/intel64/libinference_engine.so:referencia a`tbb :: interface7 :: internal :: task_arena_base :: internal_max_concurrency（tbb :: interface7 :: task_arena const *）'sin definir
collect2：错误：ld返回1退出状态
我是在在openvino后端环境下编译安装opencv4.1.0，opencv_contrib-4.1.0，
系统版本：ubuntu16.04
cmake：3.5.1
opencv4.1.0和opencv_contrib-4.1.0
openvino：2019：R1.1
cmake标志
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local/OpenCV4 \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D WITH_CUDA=ON \
      -D WITH_IPP=ON \
      -D OPENCV_EXTRA_MODULES_PATH=/home/wangfei/MyFile/opencv-4.1.0-openvino/opencv_contrib-4.1.0/modules/ \
      -D WITH_INF_ENGINE=ON \
      -D ENABLE_CXX11=ON \
      -D INTEL_CVSDK_DIR=/opt/intel/openvino_2019.1.144/deployment_tools \
      -D IE_PLUGINS_PATH=/opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64/  \
      -D INF_ENGINE_RELEASE=2019010100 \
      -D WITH_TBB=ON \
      -D BUILD_EXAMPLES=ON ..
make编译过程中没有问题，sudo make install过程中出现上述问题，“setupvars.sh”已经添加至环境变量文件，请问我哪里做错了吗，请帮助我一下，谢谢

**Comment by harmlu** [comment]
> I can confirm this problem on systems with installed Intel OpenCL CPU device (which has own TBB version under the same name).
> 
> Workaround:
> 
> * rename /opt/intel/opencl/libtbb.so.2 from Intel OpenCL (if you don't need Intel OpenCL CPU device).
> * or remove /opt/intel/opencl from setupvars.sh
> 
> OpenVINO team should drop /opt/intel/opencl entry from these environment variables. By Khronos specification it is not needed to include /opt/intel/opencl for making OpenCL work.
> However using of mismatched version of TBB library can cause bad effects:
> 
> * InferenceEngine can't use libtbb2.so from Intel OpenCL CPU device
> * Intel OpenCL CPU device implementation perhaps can't work with InferenceEngine's libtbb2.so.
> 
> Also there is system-wide libtbb2.so (Ubuntu system package with own version) which can be loaded by some apps.

My inference_engine.so does link to the Ubuntu 16.04. libtbb.so.2. This results in the above described errors wegen building my application with opencv using IE backend. Does anyone know how to fix this?

**Comment by hewen0901** [comment]
我刚刚也碰到那个问题
```
libtbb.so.2 => /opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007fce5bff8000)
```
libtbb.so路径不对，偷懒一点的做法可以直接在cmakelists中加这一句
FILE(GLOB_RECURSE LIBS_INTEL64 
/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib/*.so)
再编译的话就能编过了。
