### ISSUE TITLE
No performance gain with threading DNN module

### ISSUE THREAD

**Issue by kafan1986** [opencv/opencv#14270]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Android armv8a
- Compiler => NDK 19.2

##### Detailed description

I have implemented two separate DNN networks initialized with same config and weight file and used two separate threads to infer images parallely. Surprisingly compared to time taken by one thread and one image, processing times are adding up in parallel execution on a multi-core environment, which makes it look like the two networks are sharing resources. I have not checked the output of the networks to validate the inferred result. Is this expected behaviour from the DNN module?

##### Steps to reproduce

// Threading is not throwing any error and is working as expected. I can post some code if it helps. Not sure if it is required.
-->

**Comment by alalek** [comment]
> No performance

Lets make problem reproducible (no way to know which models are used, no info about inputs, or other processes).
Did you run OpenCV performance tests?

**Comment by kafan1986** [comment]
I am using res10_300x300_ssd_iter_140000.caffemodel for face detection

My thread block is this:

```

struct ComputeFaceDetectionData {
    cv::Mat& camImage;
    std::vector<FaceRect>& result;
    std::vector<double>& conf;
    cv::dnn::Net& pNet;
    int fdWidth;
    int fdHeight;
    double faceDetectionConfidence;
};

void *performFaceDetection(void *threadarg)
{
    struct ComputeFaceDetectionData *my_data;
    my_data = (struct ComputeFaceDetectionData *)threadarg;

    int frameHeight = my_data->camImage.rows;
    int frameWidth = my_data->camImage.cols;

    cv::Mat inputBlob = dnn::blobFromImage(my_data->camImage, 1.0, cv::Size(my_data->fdWidth, my_data->fdHeight), Scalar(104.0, 177.0, 123.0), false, false);
    my_data->pNet.setInput(inputBlob, "data");
    cv::Mat detection = my_data->pNet.forward("detection_out");
    cv::Mat detectionMat(detection.size[2], detection.size[3], CV_32F, detection.ptr<float>());

    for (int i = 0; i < detectionMat.rows; i++) {
        float confidence = detectionMat.at<float>(i, 2);
        if (confidence > my_data->faceDetectionConfidence) {
            FaceRect boundingBox;
            boundingBox.top = static_cast<int>(detectionMat.at<float>(i, 4) * frameHeight);
            boundingBox.left = static_cast<int>(detectionMat.at<float>(i, 3) * frameWidth);
            boundingBox.right = static_cast<int>(detectionMat.at<float>(i, 5) * frameWidth);
            boundingBox.bottom = static_cast<int>(detectionMat.at<float>(i, 6) * frameHeight);
            my_data->result.push_back(boundingBox);
            my_data->conf.push_back(confidence);
        }
    }

    return 0;
};

// Creating two global nets
dnn::Net net1 = dnn::readNetFromCaffe(fdcaffeConfigFile, fdcaffeWeightFile);
dnn::Net net1 = dnn::readNetFromCaffe(fdcaffeConfigFile, fdcaffeWeightFile);


// Thread creation and calling code block
            vector<FaceRect> resultFaceDetectDNN;
            vector<double> resultFaceDetectDNNConfidence;

            //Create thread
            pthread_t threads;
            pthread_attr_t attr;
            void *status;

            // Initialize and set thread joinable
            pthread_attr_init(&attr);
            pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);

            // Creating thread data and initializing it
            ComputeFaceDetectionData threadData = {CamImage, resultFaceDetectDNN, resultFaceDetectDNNConfidence, net1, fdWidth, fdHeight, faceDetectionConfidenceThreshold};
            int rc;

            rc = pthread_create(&threads, NULL, performFaceDetection, (void *)&threadData);
            if (rc)
            {
                __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Error: faceDetectDNN unable to create thread - %d",rc);
            }

            // free attribute and wait for the other threads
            rc = pthread_attr_destroy(&attr);
            if (rc != 0)
            {
                __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Error: faceDetectDNN pthread_attr_destroy - %d",rc);
            }

            // Call any parallel work to be done in main thread

            rc = pthread_join(threads, &status);
            if (rc)
            {
                __android_log_print(ANDROID_LOG_ERROR, APPNAME, "Error: faceDetectDNN unable to join  - %d",rc);
            }

```

**Comment by alalek** [comment]
Do you know OpenCV uses own ThreadPool?
check `cv::setNumThreads()` / `cv::getNumThreads()`.

`cv::setNumThreads(1)` may help with your own threading attempt.

**Comment by kafan1986** [comment]
current default getNumThreads is set to 8 (same as number of cores on the device). Setting it to 1 slows it down considerably.

**Comment by alalek** [comment]
OpenCV already utilizes available CPU resources.
Concurrent task in the new separate thread may have these negative effects:
- `+1` thread - CPU oversubsciption, overhead on threads switching has been increased. Also `cv::parallel_for()` is synchronized operation, so dis-balancing may slowdown efficiency significantly.
- total CPU cache size is limited. Adding twice more data would cause cache data eviction.

Try to `cv::setNumThreads(N-1)`, where N is number of cores.

> Single Thread mode takes less than 200 ms and doing it in 2 thread takes 390 ms.

Without analyzing of detailed profiling information it is hard to detect the real problem.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by dkurt** [comment]
Let me close this issue
