### ISSUE TITLE
Issue  in function 'cv::dnn::ReadProtoFromBinaryFile'

### ISSUE THREAD

**Issue by palbha** [opencv/opencv#14279]
##### System information (version)

- OpenCV => :4.0.0
- Operating System / Platform => :Windows 64 bit
- Compiler => :Visual Studio 2015

##### Detailed description

Referring https://www.learnopencv.com/face-detection-opencv-dlib-and-deep-learning-c-python/ .. tried to run the first python code .. in the below section
 2. DNN Face Detector in OpenCV

##### Steps to reproduce

loaded the file in the particualr directory and tried to run it but i am getting error as 

 OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "C:/Users/palbh/Documents/Python/self learning/Image classifictaion/Online/face_detector/opencv_face_detector_uint8.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'

import cv2
DNN = "TF"
if DNN == "CAFFE":
    modelFile = "res10_300x300_ssd_iter_140000_fp16.caffemodel"
    configFile = "deploy.prototxt"
    net = cv2.dnn.readNetFromCaffe(configFile, modelFile)
else:
    modelFile = "C:/Users/palbh/Documents/Python/self learning/Image classifictaion/Online/face_detector/opencv_face_detector_uint8.pb"
    configFile = "C:/Users/palbh/Documents/Python/self learning/Image classifictaion/Online/face_detector/opencv_face_detector.pbtxt"
    net = cv2.dnn.readNetFromTensorflow(modelFile, configFile)

 or attach as .txt or .zip file
-->

**Comment by dkurt** [comment]
> modelFile = "C:/Users/palbh/Documents/Python/self learning/Image classifictaion/Online/face_detector/opencv_face_detector_uint8.pb"
configFile = "C:/Users/palbh/Documents/Python/self learning/Image classifictaion/Online/face_detector/opencv_face_detector.pbtxt"

@palbha, These are not Windows paths. Please use a forum for usage questions: http://answers.opencv.org/.
