### ISSUE TITLE
problem with OpenCV cross-compile for Raspbian Stretch 

### ISSUE THREAD

**Issue by hamzeah** [opencv/opencv#14280]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Ubuntu 18

when I follow cross-compile of OpenCV for RaspberryPi using Dockers, EXACTLY according to  [this guide](https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#raspbian-stretch), I get make error, when build reaches to 73% (see image of error).

in step 3 (define path to opencv), I set it as follows (after downloading opencv and opencv_contrib source):
sudo docker run -i -t -v /home/hamzeh/opencv_4_crosscompile:/opencv -v /home/hamzeh/opencv_contrib_4_crosscompile:/opencv_contrib debian_9_armhf /bin/bash

Thanks 

![error](https://user-images.githubusercontent.com/23367987/55722801-ebe25a00-5a0f-11e9-9451-3ac4a237d070.png)

**Comment by alalek** [comment]
General note: avoid using of screenshots with text information - It is completely useless for other users to find similar issues.

CMake output is required (see above of your error lines). It is better to **attach** this dumps as ".txt" file.

**Comment by dkurt** [comment]
@hamzeah, Which version of OpenCV do you use? Current master branch has no mentioned methods on these lines. Have you tried to update both OpenCV and opencv_contrib?

**Comment by hamzeah** [comment]
@dkurt 
    Operating System / Platform => Ubuntu 18
    OpenCV => 4.0.1 ( I just download them from [here](https://github.com/opencv/opencv/archive/4.0.1.zip) and [here](https://github.com/opencv/opencv_contrib/archive/4.0.1.zip), unzip them, before starting the steps.
@alalek 
thank you for tip.  The terminal output is attached:
[dump.txt](https://github.com/opencv/opencv/files/3054323/dump.txt)

**Comment by dkurt** [comment]
@hamzeah, here is problem:

```
--     Inference Engine:            YES (2018050000 / Unknown)
--                 libs:            /inference_engine_vpu_arm/deployment_tools/inference_engine/lib/armv7l/libinference_engine.so
--             includes:            /inference_engine_vpu_arm/deployment_tools/inference_engine/include
```

For OpenVINO 2018R5 the libraries are in 
```
/inference_engine_vpu_arm/deployment_tools/inference_engine/lib/raspbian_9/armv7l/libinference_engine.so
```
You downloaded IE of version 2019R1 but OpenCV 4.0.1 was released before it. So you need to download OpenVINO 2018R5 or update OpenCV source code.

**Comment by hamzeah** [comment]
@dkurt 
thank you!, I updated opencv to latest code, and then it was compiled successfully. It is good if you add note in the instruction about this.
Moreover, I've also added below options to CMake:
-DOPENCV_EXTRA_MODULES_PATH="/opencv_contrib/modules"	  
-DOPENCV_ENABLE_NONFREE=ON  
-DENABLE_VFPV3=ON

**Comment by dkurt** [comment]
Let me close this issue due.

**Comment by dkurt** [comment]
@hamzeah, There is no need to specify `-DENABLE_VFPV3=ON` when NEON is enabled:

https://github.com/opencv/opencv/blob/cbf80117afb488e7f18bf1616b30169e5f652f20/3rdparty/cpufeatures/cpu-features.h#L167-L174
