### ISSUE TITLE
Error compiling 4.1.0 source code with mingw-w64: 'D3D11_TEXTURE2D_DESC' was not declared in this scope

### ISSUE THREAD

**Issue by huihut** [opencv/opencv#14286]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Windows 10 64bit
- Compiler => mingw-w64 8.1.0-posix-seh-rt_v6-rev0

##### Detailed description

When I compiled the 4.1.0 version with mingw-w64, there was an error 

```
E:\opencv-4.1.0\opencv-4.1.0\modules\core\src\directx.cpp:1035:5: error: 'D3D11_TEXTURE2D_DESC' was not declared in this scope
     D3D11_TEXTURE2D_DESC desc = { 0 };
     ^~~~~~~~~~~~~~~~~~~~
```

I can solve it like this

```
cmake -DWITH_OPENCL_D3D11_NV=OFF
```
But I don't know if this is the right solution, and whether this will affect the compiled dll.

**Comment by Mainvooid** [comment]
`D3D11_TEXTURE2D_DESC` is declared in `d3d11.h`. If you don't need interoperability between D3D11 and OpenCL, you can turn off compile options, as you did.

**Comment by alalek** [comment]
Need to ensure that `HAVE_OPENCL_D3D11_NV` become disabled if `HAVE_DIRECTX=OFF`.

Main problem here is that DirectX checks are performed after OpenCL checks.

**Comment by huihut** [comment]
I configured

* `WITH_OPENCL=ON`
* `WITH_OPENCL_D3D11_NV=OFF`
* `WITH_DIRECTX=ON`

It can be successfully compiled

**Comment by alalek** [comment]
@huihut Could you check this patch: #14294 ? (with default CMake parameters)

**Comment by huihut** [comment]
@alalek Well, this can be successfully compiled without modifying the default `WITH_OPENCL_D3D11_NV`.
