### ISSUE TITLE
Webassembly build does not contain the calib3d module

### ISSUE THREAD

**Issue by cameron-martin** [opencv/opencv#14293]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.10
- Compiler => Emscripten

##### Detailed description

I am wanting to use the [`findHomography`](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#findhomography) function in the webassembly build of opencv. However, no bindings are provided for the calib3d module. By the [comment in the build script](https://github.com/opencv/opencv/blob/64168fc20aa8a914cb5529f90ffac309854563b1/platforms/js/build_js.py#L119) this is intentional.

However, I wanted to start a discussion on whether it is feasible to include this module, and if so what would be needed to be done to get this working.

**Comment by alalek** [comment]
I would be useful. At least, we can start from adding of a part of calib3d functionality.
Unfortunately we have lack of resources to do this in the nearest future, so feel free to contribute.

You can take a look on this PR about adding of photo module: #13300

**Comment by cameron-martin** [comment]
Thanks for the pointer. One question: how do I run the javascript tests? The [instructions on the wiki](https://github.com/opencv/opencv/wiki/How_to_contribute) don't seem to cover the JS tests.

**Comment by alalek** [comment]
@cameron-martin You can take a look on logs from this [build](http://pullrequest.opencv.org/buildbot/builders/3_4_javascript-emscripten-lin64/builds/353).
