### ISSUE TITLE
 import threading vs OpenCV vs HTTPS/TLS url video

### ISSUE THREAD

**Issue by adrianovieira** [opencv/opencv#14295]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Linux/Fedora
- Compiler => :grey_question:

##### Detailed description

There a trouble when import OpenCV and threading in a fashion way:

##### Steps to reproduce

- **it won't works**  
  ```
  from threading import Thread
  import cv2
  ```

- **it works**  
  ```
  import cv2
  from threading import Thread
  ```

```python
url = 'https://storage.googleapis.com/dev-brdu1976/268.mov'
video = cv2.VideoCapture(url)
# [..]
video.release()
```

My gitlab snippet with a full demo: https://gitlab.com/snippets/1846347

**Comment by alalek** [comment]
see this thread: #5150
