### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by ssridhar2065** [opencv/opencv#14309]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 18.04
- ARM64 Single Board Computer - Rockchip rk3399

Description
- OpenCV => I followed the instructions of building Opencv and installing, but I am getting this
error again and again.
ModuleNotFoundError: No module named 'cv2'

Till Opencv 3.4.0 I was able to install.

$ cd ~/opencv
$ mkdir build
$ cd build
$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
    -D BUILD_EXAMPLES=ON ..

make -j4

sudo make install

==============================
pi@NanoPC-T4:/storage/opencv-4.0.0/opencv/build$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>import cv2
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'

===============================

Struggling from 4 days. Please help close.

**Comment by dkurt** [comment]
@ssridhar2065, For usage questions please use a forum: http://answers.opencv.org

If you want to report a bug it should have at least cmake + make logs.
