### ISSUE TITLE
imread cannot use both IMREAD_UNCHANGED and IMREAD_IGNORE_ORIENTATION

### ISSUE THREAD

**Issue by eyaler** [opencv/opencv#14300]
I want to use IMREAD_UNCHANGED to allow alpha channels AND use IMREAD_IGNORE_ORIENTATION to ignore EXIF, however it is not possible to combine both

**Comment by alalek** [comment]
What image has been used? (format/codec?)
Are `ApplyExifOrientation()` functions get called?

**Comment by hurzl** [comment]
On android, when I combine both, the resulting image is reduced to half size. (3.4.7) camera image in jpeg format, opencv type=0 or 16

**Comment by alalek** [comment]
`IMREAD_UNCHANGED` (`-1` value) ignores orientation.

`IMREAD_UNCHANGED + IMREAD_IGNORE_ORIENTATION` is invalid mode.
`IMREAD_UNCHANGED | IMREAD_IGNORE_ORIENTATION` is equal to `IMREAD_UNCHANGED`.

**Comment by hurzl** [comment]
1. why is it invalid to request both?
2. why do I get half the image size instead of an error?
