### ISSUE TITLE
fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

### ISSUE THREAD

**Issue by zchrissirhcz** [opencv/opencv#14317]
##### System information (version)

- OpenCV => 3.4.5
- Operating System / Platform => Windows 10, 64 Bit
- Compiler => Visual Studio 2017 (15.9.11, Community Version)
- CUDA: 9.0

##### Detailed description

Failed to build opencv + opencv_contrib + cuda support with VS2017.

17>c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
14>ImfScanLineInputFile.cpp
17>CMake Error at cuda_compile_generated_gpu_mat.cu.obj.cmake:206 (message):
17>  Error generating
17>  F:/opencv_345/build-vs2017-x64-contrib-cuda/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/Release/cuda_compile_generated_gpu_mat.cu.obj
17>
17>
17>已完成生成项目“opencv_core.vcxproj”的操作 - 失败。

##### Steps to reproduce
```bat
@echo off

set BUILD_DIR=build-vs2017-x64-contrib-cuda
if exist %BUILD_DIR% rd /s /q %BUILD_DIR%
md %BUILD_DIR%
cd %BUILD_DIR%

cmake ^
    -G "Visual Studio 15 2017 Win64" ^
    -D CMAKE_BUILD_TYPE=Release ^
    -D CMAKE_INSTALL_PREFIX=%cd%/install ^
    -D WITH_CUDA=ON ^
    -D WITH_VTK=OFF ^
    -D WITH_MATLAB=OFF ^
    -D BUILD_DOCS=ON ^
    -D OPENCV_EXTRA_MODULES_PATH=F:/opencv_contrib_345/modules ^
    ../sources

cd ..

pause
```

Save the above to `run.bat` and run it. Then opencv OpenCV.sln with VS2017 and build in Release mode.

**Comment by alalek** [comment]
> cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error: -- unsupported Microsoft Visual Studio version!

Its CUDA headers.
- Check NVIDIA site for CUDA/MSVS compatibility information.
- Try to upgrade CUDA to 9.1.

Looks like this can't be fixed in OpenCV.

We can try to check correctness of command line. But you need to provide exact command line - check lines above your cut with `17>` marker (similar to error line).

Also try to add calling of "vcvars.bat" from MSVS before CMake run (use clean build directory - to avoid stalled cache entries of CMake).

**Comment by zchrissirhcz** [comment]
@alalek Hi, thanks for response.
Let me make it clear about my pasted script.

This script will firstly check the building directory, if it exists, it will be removed, then re-created.

In this script, I also specified cmake's generator, it's "Visual Studio 15 2017 Win64".  In this case, I don't think vcvars.bat is needed to be called.

**Comment by zchrissirhcz** [comment]
Close since this is not related with OpenCV. This is the uncompatible between VS2017 and CUDA9.

Ref:
https://devtalk.nvidia.com/default/topic/1027209/cuda-9-0-does-not-work-with-the-latest-vs-2017-update/
