### ISSUE TITLE
File not found opencv_createsamples.exe and opencv_traincascade.exe 

### ISSUE THREAD

**Issue by pardeep3december** [opencv/opencv#14322]
### System information (version)
- OpenCV =>4.0.0-vc14_vc15
- Operating System / Platform => Windows 64 Bit
- IDE => IDLE 3.7.3

- OpenCV => :grey_question: files opencv_createsamples.exe and opencv_traincascade.exe  are not available
##### Detailed description
actually i am searching procedure to develop own/customize haarcascade xml file to detect customize object in real time camera.

i followed 
https://www.instructables.com/id/Create-OpenCV-Image-Classifiers-Using-Python/  (opencv_createsamples.exe and opencv_traincascade.exe files are not found  )
and
https://www.researchgate.net/publication/259584296_Tutorial-_Creating_a_Cascade_of_Haar-like_Classifiers_Step_by_Step (detecting so many rectangles but not on the pens)

but not no result.
Files are attached with positive and negative images.

Guide me how can i develop customize xml file to detect only one thing  to use it in python program to detect in real time camera.
Thanks 
[HaarTrainingPEN.zip](https://github.com/opencv/opencv/files/3076684/HaarTrainingPEN.zip)

##### Steps to reproduce

[HaarTrainingPEN.zip](https://github.com/opencv/opencv/files/3076684/HaarTrainingPEN.zip)

**Comment by alalek** [comment]
Use OpenCV 3.4.x to work with opencv_createsamples and opencv_traincascade tools.

**Comment by pardeep3december** [comment]
Thank you.

**Comment by jrichardsz** [comment]
What a pain is the installation of opencv 3.4. I need to pickup and old branch, install a ton of os tools and build from source :s with no success :(

https://gist.github.com/donghee/15d7272885ac3505e0f20a63678e7ba3

Is there any other chance to have **opencv_createsamples** and **opencv_traincascade** in lastest opencv version: 4.5.4 and python Python 3.8.10 (default, Nov 26 2021, 20:14:08)?

Thanks so much!!
