### ISSUE TITLE
ArchLinux: cmake "non-existent path" errors due to OpenCV_CONFIG_PATH 

### ISSUE THREAD

**Issue by lainy** [opencv/opencv#14323]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Arch Linux / amd64
- Compiler => gcc

##### Detailed description

While attempting to build [sdrangel](https://github.com/f4exb/sdrangel) (which has a dependency on OpenCV), I encounter a rather peculiar build error:

```
CMake Error in pluginssrv/channeltx/modatv/CMakeLists.txt:
  Imported target "opencv_calib3d" includes non-existent path

    "//include/opencv4"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

#### The problem seems to be [this line](https://github.com/opencv/opencv/blob/master/cmake/templates/OpenCVConfig.cmake.in#L79):
```
set(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_DIR}")
```

On Arch this sets `OpenCV_CONFIG_PATH` to `/lib64/cmake/opencv4/`

Then the next line in OpenCVConfig.cmake is:
```
get_filename_component(OpenCV_INSTALL_PATH "${OpenCV_CONFIG_PATH}/../../../" REALPATH)
```
... which resolves to `/lib64/cmake/opencv4/../../../` which is simply `/`, which is clearly incorrect.

`/lib64` symlinks to `/usr/lib`, so a quick fix is to change:
```
set(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_DIR}")
```
to
```
get_filename_component(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_DIR}" REALPATH)
```
which will resolve the `/lib64` symlink, correctly setting `OpenCV_CONFIG_PATH` to `/usr/lib/cmake/opencv4`

##### Steps to reproduce

On Arch Linux, attempt to build sdrangel-git from AUR.

**Comment by alalek** [comment]
@lainy Thank you for the report, investigation and proposed fix!

Feel free to prepare Pull Request into 3.4 branch.
We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

**Comment by dengdengdeng** [comment]
Hi, I have encountered the same problem as reported by @lainy when I tried to build ros-melodic-image-geometry as a dependency to ros-melodic-desktop-full.

**Error info:**
CMake Error in CMakeLists.txt:
  Imported target "opencv_calib3d" includes non-existent path

    "//include/opencv4"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_BASENAME
    PYTHON_INCLUDE_DIR
    PYTHON_LIBRARY


-- Build files have been written to: /home/ray/.cache/yay/ros-melodic-image-geometry/src/build
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-image-geometry


**System info:**

- Manjaro x64
- opencv 4.1.0

I tried to remove the opencv4 and to build it from git repo, but I got another build error as shown below:
[ 38%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx2.cpp.o
[ 38%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin256.avx2.cpp.o
[ 38%] Linking CXX executable ../../bin/opencv_test_core
/bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_dgemm'
/bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_cgemm'
/bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_zgemm'
/bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_sgemm'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/core/CMakeFiles/opencv_test_core.dir/build.make:692: bin/opencv_test_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:1262: modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I am new to ROS and OpenCV. Could anyone tell me or guide me how to fix it? Thank you!

**Comment by aaronrancsik** [comment]
> Hi, I have encountered the same problem as reported by @lainy when I tried to build ros-melodic-image-geometry as a dependency to ros-melodic-desktop-full.
> 
> **Error info:**
> CMake Error in CMakeLists.txt:
> Imported target "opencv_calib3d" includes non-existent path
> 
> ```
> "//include/opencv4"
> ```
> 
> in its INTERFACE_INCLUDE_DIRECTORIES. Possible reasons include:
> 
> * The path was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and references files it does not
>   provide.
> 
> -- Generating done
> CMake Warning:
> Manually-specified variables were not used by the project:
> 
> ```
> PYTHON_BASENAME
> PYTHON_INCLUDE_DIR
> PYTHON_LIBRARY
> ```
> 
> -- Build files have been written to: /home/ray/.cache/yay/ros-melodic-image-geometry/src/build
> ==> ERROR: A failure occurred in build().
> Aborting...
> Error making: ros-melodic-image-geometry
> 
> **System info:**
> 
> * Manjaro x64
> * opencv 4.1.0
> 
> I have also tried to remove the opencv4 and to build it directly from the version from github repo, but I got another build error as shown below:
> 
> **Error info by building:**
> 
> [ 38%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx2.cpp.o
> [ 38%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin256.avx2.cpp.o
> [ 38%] Linking CXX executable ../../bin/opencv_test_core
> /bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_dgemm' /bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_cgemm'
> /bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_zgemm' /bin/ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `cblas_sgemm'
> collect2: error: ld returned 1 exit status
> make[2]: *** [modules/core/CMakeFiles/opencv_test_core.dir/build.make:692: bin/opencv_test_core] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1262: modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
> make: *** [Makefile:163: all] Error 2
> 
> I am new to ROS and OpenCV. Could anyone tell me or guide me how to fix it? Thank you!

Hello, [THIS](https://unix.stackexchange.com/questions/417032/arch-linux-problems-building-opencv-with-cuda-libopencv-core-so-3-4-0-undefin) fixed for me :) basically just add `CMAKE_EXE_LINKER_FLAGS=-lcblas` to cmake

**Comment by keineahnung2345** [comment]
I've tried `cmake -D CMAKE_EXE_LINKER_FLAGS=-lcblas ..` but the result is still the same.

**Comment by wybert** [comment]
> I've tried `cmake -D CMAKE_EXE_LINKER_FLAGS=-lcblas ..` but the result is still the same.

The same for me
