### ISSUE TITLE
HoughLinesP access voilation(s) for images with info at edges of image

### ISSUE THREAD

**Issue by bobatious** [opencv/opencv#14335]
OpenCV => 4.0 or later, including 4.1 (latest)
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2017 (compiler Version 15.9.11)

##### Detailed description
With busy images and/or those with information up to the edges, HoughLinesP (and HoughLinesProbabilistic) causes access violations as loop exit conditions do not catch all cases of reaching the limits of the image.

##### Steps to reproduce
Using the attached image, process with arguments
  minLineLength = 35
  threshold = 10
  minLineGap = 25
and all other arguments as in the HoughLinesP sample.

![ROI43](https://user-images.githubusercontent.com/49570590/56150303-76244400-5f63-11e9-8de2-129b61e29f1b.png)

PS: author has already produced a fix for this and will be submitting a pull request "presently".

**Comment by alalek** [comment]
Thank you for the report!

Please prepare fix for 3.4 branch ("bugfixes" should go there first).

**Comment by bobatious** [comment]
OK ... will do.

**Comment by asmorkalov** [comment]
@bobatious Do you have any progress with the issue fix?

**Comment by bobatious** [comment]
I do have a patch with fix to the fatal error / memory access problem.

However the algorithm still does not produce proper results. E.g. number of
segments found does not increase monotonically when threshold is lowered.
So I did not integrate my change yet.

Meanwhile, after much followup with Intel/IPP people, the IPP (Intel
library) implementation has been fixed for the same kind of memory access
violation issue, but their algorithm does produce proper results. So we may
want to note this in release notes or so.

Of course the IPP "implementation" of OpenCV probabilistic hough should
just make it faster, not change the answer. So the overall state is a bit
odd.

Not sure what to do with my patch for the fatal error, but could integrate
it as that would be an improvement, to be sure.

Cheers
-Bob Davis

**Comment by asmorkalov** [comment]
@bobatious could you attach your implementation/fix to the ticket. It can be useful if somebody will try to help you with the issue.

**Comment by alalek** [comment]
Can't reproduce access violations with following code on master branch:

<details>

```.cpp
Mat image = imread(base + "test.png", IMREAD_GRAYSCALE);
std::cout << image.size << std::endl;
Mat lines;
HoughLinesP(image, lines, 1, CV_PI/180,
            10/*threshold*/,
            35/*minLineLength*/,
            25/*maxLineGap*/);
std::cout << lines.size << std::endl;
```

</details>

Output:
```
40388 x 472
1962 x 1
```

Valgrind is clean too.
