### ISSUE TITLE
Use IplImage in opencv 4.0.1

### ISSUE THREAD

**Issue by GrandmaPeng** [opencv/opencv#14344]
Hi,

In the [wiki](https://github.com/opencv/opencv/wiki/Opencv4) it reads **'IplImage ... are mostly excluded from API and will be completely excluded in further OpenCV 4.x updates'**. But in the 4.0.1 version there is still a include\opencv2\core\type_c.h file which contains the structure IplImage. Does it mean we can still use this data structure in opencv 4.0.1 [though it's not recommended to do so]?

Thanks

**Comment by alalek** [comment]
All legacy C API structures can be removed in the future releases (4.2 or 4.3, etc) without providing fallback replacement.
Also please note, that deprecated code is probably out of scope of regular testing.
