### ISSUE TITLE
How to convert 3d array to 4d array using Mat::reshape

### ISSUE THREAD

**Issue by myproject24** [opencv/opencv#14349]
@alalek @ilya-lavrenov @sturkmen72
Hi, I have 3d RGB array I need to convert it to 4d RGBA array using reshape how to do that kindly help me. Basically x = np.reshape(x, (1,64,64,3)) this python operation i have to do in c++.

**Comment by dkurt** [comment]
Please use a forum http://answers.opencv.org/ for questions.
