### ISSUE TITLE
Opencv make error

### ISSUE THREAD

**Issue by FJarecki** [opencv/opencv#14359]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Ubuntu 18.04
- Compiler => cMake
##### Detailed description
Hi, i am trying to install OpenCv, but i got the error after "make -j8" instruction.
that's my cMake instruction:
`cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..`
After it I am pasting "make -j8" and get error:
`[ 84%] Built target opencv_test_cvv
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_PC32 against symbol stderr@@GLIBC_2.2.5 can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/sfm/CMakeFiles/opencv_sfm.dir/build.make:348: recipe for target lib/libopencv_sfm.so.4.1.0 failed
make[2]: *** [lib/libopencv_sfm.so.4.1.0] Error 1
CMakeFiles/Makefile2:24735: recipe for target modules/sfm/CMakeFiles/opencv_sfm.dir/all failed
make[1]: *** [modules/sfm/CMakeFiles/opencv_sfm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`
Can u help me? What i am doing wrong or what's wrong with my files?

**Comment by alalek** [comment]
> /usr/local/lib/libgflags.a
> recompile with -fPIC

Can be fixed in OpenCV.
You can try to disable OpenCV components (`cmake -DBUILD_opencv_sfm=OFF ...`) which using `gflags` or remove that `gflags` from your system.

---

Build/usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
