### ISSUE TITLE
results of function findCirclesGrid show shift from the real circle centers, why?

### ISSUE THREAD

**Issue by yyxr75** [opencv/opencv#14350]
##### System information (version)

- OpenCV =>  2.4.11
- Operating System / Platform =>Windows 64 Bit
- Compiler => python

##### Detailed description

Much thanks to anyone who may help,

I am using the cv2.findcirclesgrid() in python script to detect the centers of images of calibration board, but the results appear to be existing a shift between the detected centers and visual  centers(from my own point of view). As follows:
![image](https://user-images.githubusercontent.com/44866138/56272117-a66b0e80-612c-11e9-8902-2eb719aa09bd.png)

I checked the blob detector this morning, it successfully extracted the circles in my pictures. So maybe this shift is not because of the blob parameters(I think so). As follows:
![checkedImg0](https://user-images.githubusercontent.com/44866138/56272236-e03c1500-612c-11e9-8ecb-4f326bce3f5c.jpg)

Anyhow, I wonder:
1. Whether this should happen? apparent bias of extracted centers between real position.
2. If the answer is 'it should not be like this', then what should I do?

##### Steps to reproduce

here is my code in python, appreciation for any information you may supply to me
[findCircleGridAsymmetric.txt](https://github.com/opencv/opencv/files/3088604/findCircleGridAsymmetric.txt)

**Comment by alalek** [comment]
Could you please attach non-processed input image? (preferable in lossless format, like PNG)

Do you use some flags in findCirclesGrid() method?


> OpenCV => 2.4.11

This is ancient OpenCV version.
Could you try latest OpenCV releases from 3.4.x or 4.1 (master branch)?

**Comment by yyxr75** [comment]
> Could you please attach non-processed input image? (preferable in lossless format, like PNG)
> 
> Do you use some flags in findCirclesGrid() method?
> 
> > OpenCV => 2.4.11
> 
> This is ancient OpenCV version.
> Could you try latest OpenCV releases from 3.4.x or 4.1 (master branch)?

here is the PNG image:
![2original](https://user-images.githubusercontent.com/44866138/56284929-85181b80-6148-11e9-9ae7-0768d8577d3b.png)
I also have a raw image which is in 14 bit format, but it seems I can not load this file here. I can email it to you if you want it.

As your advice tells. I will try to use a newer version of opencv to see the differences. Thank you a lot.

**Comment by yyxr75** [comment]
> Could you please attach non-processed input image? (preferable in lossless format, like PNG)
> 
> Do you use some flags in findCirclesGrid() method?
> 
> > OpenCV => 2.4.11
> 
> This is ancient OpenCV version.
> Could you try latest OpenCV releases from 3.4.x or 4.1 (master branch)?

Sorry to bother,

I used the newest version of opencv which is v-4.1

![image](https://user-images.githubusercontent.com/44866138/56340719-5603b780-61e5-11e9-882d-0d3f75320013.png)

but the result remains unacceptable

![image](https://user-images.githubusercontent.com/44866138/56340788-8c413700-61e5-11e9-96e5-f84e57d3c92b.png)

I didn't change the code, what should I do with this situation?

**Comment by yyxr75** [comment]
Does anyone have any idea?

**Comment by mshabunin** [comment]
I can not reproduce the problem (Linux, latest _master_ branch version):
```.py
import numpy as np
import cv2 as cv

img = cv.imread('circles0.png')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
ret, corners = cv.findCirclesGrid(gray, (4,9), None, flags = cv.CALIB_CB_ASYMMETRIC_GRID)
if ret == True:
    corners2 = corners
    # corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001))
    cv.drawChessboardCorners(img, (4,9), corners2, ret)
    cv.imwrite('output.jpg', img)
    cv.imshow('img', img)
    cv.waitKey(0)
```
![output](https://user-images.githubusercontent.com/3304494/56901219-554e0980-6aa0-11e9-9bf8-6a4867330717.jpg)

Please check output of `cv2.getBuildInformation()` to verify which version has been used.

**Comment by yyxr75** [comment]
> I can not reproduce the problem (Linux, latest _master_ branch version):
> 
> ```python
> import numpy as np
> import cv2 as cv
> 
> img = cv.imread('circles0.png')
> gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
> ret, corners = cv.findCirclesGrid(gray, (4,9), None, flags = cv.CALIB_CB_ASYMMETRIC_GRID)
> if ret == True:
>     corners2 = corners
>     # corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001))
>     cv.drawChessboardCorners(img, (4,9), corners2, ret)
>     cv.imwrite('output.jpg', img)
>     cv.imshow('img', img)
>     cv.waitKey(0)
> ```
> 
> ![output](https://user-images.githubusercontent.com/3304494/56901219-554e0980-6aa0-11e9-9bf8-6a4867330717.jpg)
> 
> Please check output of `cv2.getBuildInformation()` to verify which version has been used.

OK, I will give it a try

**Comment by yyxr75** [comment]
> > I can not reproduce the problem (Linux, latest _master_ branch version):
> > ```python
> > import numpy as np
> > import cv2 as cv
> > 
> > img = cv.imread('circles0.png')
> > gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
> > ret, corners = cv.findCirclesGrid(gray, (4,9), None, flags = cv.CALIB_CB_ASYMMETRIC_GRID)
> > if ret == True:
> >     corners2 = corners
> >     # corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001))
> >     cv.drawChessboardCorners(img, (4,9), corners2, ret)
> >     cv.imwrite('output.jpg', img)
> >     cv.imshow('img', img)
> >     cv.waitKey(0)
> > ```
> > 
> > 
> > ![output](https://user-images.githubusercontent.com/3304494/56901219-554e0980-6aa0-11e9-9bf8-6a4867330717.jpg)
> > Please check output of `cv2.getBuildInformation()` to verify which version has been used.
> 
> OK, I will give it a try

Thank you so much,
I receive the same result as yours Using your code , that was how it should be. Thanks a lot again!

**Comment by alalek** [comment]
> cornerSubPix

Main purpose of this function is corners location refinement. It should not be used for circles.

**Comment by edbrisley** [comment]
Hi there,

I am attempting to do calibration on a target that is symmetric, but with an alternating amount of CT's row-wise. So it is similar to the problem above, except that the pattern is symmetric. So essentially I am looking for a 'flags' parameter that will allow the detection of all points. Right now the code looks for a symmetric pattern within the mother pattern. 

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy

im1 = cv.imread('16-mmLaVision-sys2-0043_0.tif', 0)


im2 = 1-im1


criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

#Blob Detector
# Setup SimpleBlobDetector parameters.
blobParams = cv.SimpleBlobDetector_Params()

# Change thresholds
blobParams.minThreshold = 8
blobParams.maxThreshold = 255

# Filter by Area.
blobParams.filterByArea = True
blobParams.minArea = 64     # minArea may be adjusted to suit for your experiment
blobParams.maxArea = 2500   # maxArea may be adjusted to suit for your experiment

# Filter by Circularity
blobParams.filterByCircularity = True
blobParams.minCircularity = 0.6

# Filter by Convexity
blobParams.filterByConvexity = True
blobParams.minConvexity = 0.87

# Filter by Inertia
blobParams.filterByInertia = True
blobParams.minInertiaRatio = 0.01

# Create a detector with the parameters
blobDetector = cv.SimpleBlobDetector_create(blobParams)

keypoints = blobDetector.detect(im2) # Detect blobs.
# Draw detected blobs as red circles. This helps cv.findCirclesGrid() . 
im_with_keypoints = cv.drawKeypoints(im2, keypoints, np.array([]), (0,255,0), cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
im_with_keypoints_gray = cv.cvtColor(im_with_keypoints, cv.COLOR_BGR2GRAY)

plt.imshow(im_with_keypoints, cmap = 'gray')
plt.show()

#find the grid of circles located on the calibration plate
ret, corners = cv.findCirclesGrid(im_with_keypoints, (11,11), None, flags = cv.CALIB_CB_SYMMETRIC_GRID)   # Find the circle grid

#display the grid if it was correctly identified according to criteria in line above
if ret == True:
    corners2 = corners
    # corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001))
    im_with_keypoints2 = copy.deepcopy(im_with_keypoints)
    cv.drawChessboardCorners(im_with_keypoints2, (11,11), corners2, ret)
    cv.imwrite('ouput/output.jpg', im_with_keypoints2)
    plt.imshow(im_with_keypoints2)
    plt.show()


attched is the  input and output file
[16-mmLaVision-sys2-0043_0.zip](https://github.com/opencv/opencv/files/9594341/16-mmLaVision-sys2-0043_0.zip)
![image](https://user-images.githubusercontent.com/82768031/190916158-a2cdf9ac-473b-4f40-95fa-384fc8782e85.png)

**Comment by mshabunin** [comment]
@edbrisley , I think your target is actually called "asymmetric circles grid": https://www.google.com/search?q=asymmetric+circles+grid So you should try `cv.CALIB_CB_ASYMMETRIC_GRID` flag to find it.

**Comment by m0ose** [comment]
CornerSubPix does not seem to work with circular grids. It also, mutates the original points. 
![Screenshot 2023-07-19 at 12 06 34 PM](https://github.com/opencv/opencv/assets/393666/87e6a702-1ee6-4a93-ba23-339aee8acdb3)

**Comment by mshabunin** [comment]
I believe `cornerSubPix` is not meant to work with circles, because it refines corners locations and circles do not have corners (https://docs.opencv.org/4.x/dd/d1a/group__imgproc__feature.html#ga354e0d7c86d0d9da75de9b9701a9a87e).

**Comment by yldhgs** [comment]
> Hi there, if cornerSubPix is not meant to work with circles, is there any algorithm that exist can refine centre of mass of circle grid to sub-pixel accuracy?

I found findCirclesGrid has already return coordnates in sub-pixel accuracy
