### ISSUE TITLE
cv::Mat: create channelRange method or similar slice/view across third dimension

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#14355]
We just had a discussion in IRC about doing elementwise matrix operations on the BGR channels of a BGRA image, leaving the fourth channel alone.

In python this would have been operations on a slice/view like `img[:,:,0:3]` but the C++ API doesn't appear to support views along this axis, only the first two.

I would like to propose a `channelRange` method, which, similar to `colRange` and `rowRange`, only creates a new header.

Files of interest are `modules/core/include/opencv2/core/mat.hpp` and `modules/core/include/opencv2/core/mat.inl.hpp`

**Comment by alalek** [comment]
Current limitations of cv::Mat:
- no gap between pixel elements (neighbor channels)
- no gap between neighbor elements in the row (the first dimension : same row, different column).
- positive "step" for others dimensions (negative step is not tested and may not work properly).

This is done due performance reasons at first. The second, we want simple code (there are still many users which don't know difference between `step` and `width`).

There are no plans to change `cv::Mat` header.
Extra operations can be added, but they should not explode OpenCV library itself.

**Comment by crackwitz** [comment]
Good points. I have encountered functions that required stride == element size, but wasn't sure if that was a general rule.
