### ISSUE TITLE
mobilenet_ssd_v2_quantized opencv apper Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [opencv/opencv#14360]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => ubuntu16.04
python =>3.5

##### Detailed description
First, I train mobilenet_ssd_v1 with my own data.I can convert my pb to pbtxt  follow the way of https://github.com/opencv/opencv/issues/11560   and can successfully detect the target.
But ,follow the same method,I also can convert my mobilenet_ssd_v2_quantify.pb to pbtxt,when I 
detect object ,it apper Segmentation fault (core dumped).

cvNet = cv.dnn.readNetFromTensorflow('/home/mars/Mobilenet_v2/cnkrflags/v2_cn_graph.pb', '/home/mars/Mobilenet_v2/cnkrflags/v2_cn_graph.pbtxt')

my project is      https://github.com/LUOBO123LUOBO123/Mobilenet-ssd-v2

**Comment by alalek** [comment]
> core dumped

Provide stack trace from crash point (for example, via gdb "bt" command).


> OpenCV => 4.0.0

This release is old. Try latest OpenCV code from the master branch.

**Comment by LUOBO123LUOBO123** [comment]
1.Provide stack trace from crash point (for example, via gdb "bt" command).I try it.

2.my opencv version is '4.0.0'
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.0.0'

I try to update the version of opencv.

**Comment by dkurt** [comment]
OpenCV doesn't support Int8 convolutions for now.

**Comment by LUOBO123LUOBO123** [comment]
@dkurt  Thank you for your help.

**Comment by LUOBO123LUOBO123** [comment]
@dkurt In order to use this model,How should I modify it?

**Comment by dkurt** [comment]
You may use not quantized model.

**Comment by LUOBO123LUOBO123** [comment]
@dkurt OK,Thank you for your help.
