### ISSUE TITLE
intersectionConvexConvex works incorrectly

### ISSUE THREAD

**Issue by aleksartamonov** [opencv/opencv#14367]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => Mac
- Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05)
- IPython 5.8.0

##### Detailed description

If contour with points out of frame has 0 coordinates,  intersectConvexConvex does not works

##### Steps to reproduce

```
In [30]: frame
Out[30]:
array([[  0,   0],
       [740,   0],
       [740, 540],
       [  0, 540]])

In [31]: contour = np.array([[0,210],[-30,210],[-37,170],[ -7,172]])

In [32]: sq , chain  = cv2.intersectConvexConvex(frame, contour)

In [33]: chain
Out[33]:
array([[[  0., 210.]],

       [[-30., 210.]],

       [[-37., 170.]],

       [[ -7., 172.]]], dtype=float32)

In [34]: sq
Out[34]: 1163.0
```

**Comment by thangktran** [comment]
I'm working on this issue.

**Comment by alalek** [comment]
@aleksartamonov Could you try this patch: #14463 ?

**Comment by thangktran** [comment]
@alalek how should we proceed with this issue?
