### ISSUE TITLE
No NVIDIA OpenCL for DISOpticalFlow

### ISSUE THREAD

**Issue by andreasg123** [opencv/opencv#14372]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.3.0

##### Detailed description

I ran optical flow detection in an NVIDIA OpenCL Docker container. With `FarnebackOpticalFlow`, the GPU version is 9 times faster than the CPU version.  With `DISOpticalFlow`, there is no difference.  It looks like it is due to the test for `ocl::Device::getDefault().isIntel()`:

https://github.com/opencv/opencv/blob/master/modules/video/src/dis_flow.cpp#L1371

Is there a reason why the OpenCL implementation of `DISOpticalFlow` would not work on NVIDIA?

##### Steps to reproduce

If you like, I can provide a sample program. However, with the current source, `DISOpticalFlow` will not use OpenCL on NVIDIA.

**Comment by alalek** [comment]
This usually means that algorithm has been optimized using of Intel devices. Other OpenCL devices are not validated (neither accuracy, not performance).

Good news - I don't see any Intel-specific extensions in OpenCL code (.cl files).

- try to remove this check and and built OpenCV locally.
- run OpenCV accuracy tests
- there are [OpenCV performance tests](https://github.com/opencv/opencv/wiki/HowToUsePerfTests) for this algorithm (prefer using of `summary.py` utility instead of legacy `report.py` for analyzing results)
- run with your sample program and evaluate results
- finally, feel free to prepare Pull Request if OpenCL code works well on NVIDIA devices (accuracy tests are passed and performance is fine). Additionally please specify used NVIDIA device in PR description.

BTW, there is OpenCL for AMD devices too - but you can just remove this `.isIntel()` check (If NVIDIA device is fine, then AMD devices should be fine too).

**Comment by andreasg123** [comment]
After removing the test for Intel, the program produces this output.  Googling revealed that `ptxas` is the [NVIDIA Ptx optimizing assembler](https://helpmanual.io/help/ptxas/).

    OpenCL program build log: video/dis_flow
    Status -9999: Unknown OpenCL error
    
    ptxas application ptx input, line 2239; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 2257; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 2514; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 2532; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 3480; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 3498; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 3755; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas application ptx input, line 3773; error   : Type of argument does not match formal parameter '%VAParam'
    ptxas fatal   : Ptx assembly aborted due to errors

I don't know anything about OpenCL but I may have a look as time permits.  I would appreciate pointers in the right direction.  In particular, it would be helpful to know what the line numbers refer to (the merged OpenCL program?).

**Comment by andreasg123** [comment]
I determined that the `ptxas` errors are for all calls to `sub_group_reduce_add` (called here): https://github.com/opencv/opencv/blob/master/modules/video/src/opencl/dis_flow.cl#L217

This appears to be part of [cl_intel_subgroups](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups.html). I guess this means that the DIS OpenCL code will only work on Intel.

**Comment by andreasg123** [comment]
If somebody else would like to make the DIS OpenCL code available for more platforms, one could test for the presence of [cl_intel_subgroups](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups.html) or [cl_khr_subgroups](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/cl_khr_subgroups.html). As the latter is [part of core in 2.1](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/cl_khr_subgroups.html), one would have to check for the version, too.

    (ocl::Device::getDefault().deviceVersionMajor() > 2 || 
     (ocl::Device::getDefault().deviceVersionMajor() == 2 && ocl::Device::getDefault().deviceVersionMinor() > 0) || 
     ocl::Device::getDefault().isExtensionSupported("cl_khr_subgroups") ||
     ocl::Device::getDefault().isExtensionSupported("cl_intel_subgroups"))

I cannot test any of this because our environment consists of Intel Xeon servers, either with or without NVIDIA cards. NVIDIA is only moving very slowly towards OpenCL 2.0, a requirement for `cl_khr_subgroups`. Having the documentation for the extensions that provide `sub_group_reduce_add` may be useful for others.

**Comment by alalek** [comment]
Thank you for the investigation!

Could you try this patch: https://github.com/alalek/opencv/commit/issue_14372 ?

**Comment by andreasg123** [comment]
This is a very nice approach for working around the issue with `sub_group_reduce_add`. Unfortunately, it runs slower than the CPU version on my NVIDIA card (GPU: 19 fps, CPU 24 fps for a video with frame size 360x636).  With the same video, Farneback has 17 fps for CPU and 154 fps for GPU. This includes the time for reading the video frames.

I verified that `subgroups_build_options` contained an empty string in `ocl_PatchInverseSearch`. Thus, it used the OCL code without errors. It just ran slower.

**Comment by alalek** [comment]
I'm observing these results on Linux machine with i7-6700 + GTX 1080 (OpenCL 1.2 / 387.34):

<details>

<summary>opencv_perf_video</summary>

|Name of Test|cpu|ocl-shm|ocl-shm vs cpu (x-factor)|
|---|:-:|:-:|:-:|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 640x480)|3.910|4.886|0.80|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 1280x720)|11.251|11.245|1.00|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 1920x1080)|24.210|20.127|1.20|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 640x480)|13.245|11.974|1.11|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1280x720)|44.255|34.576|1.28|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1920x1080)|121.652|88.296|1.38|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 640x480)|2.259|2.815|0.80|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 1280x720)|6.526|5.117|1.28|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 1920x1080)|13.939|6.431|2.17|

</details>

CPU is faster than OpenCL path in case of low resolution images like 640x480.
1280x720 / 1920x1080 OpenCL is not slower that CPU path (1-2x speedup).


BTW, theoretically utilization of GPU can release some CPU power for other latency-bound tasks of pipeline (if GPU is not busy already).

**Comment by andreasg123** [comment]
Thanks for the investigation of performance. For now, I'll stick with Farnebäck because that is already used in the [dense trajectories approach](https://www.cv-foundation.org/openaccess/content_iccv_2013/papers/Wang_Action_Recognition_with_2013_ICCV_paper.pdf) that I'm adapting. I had hoped that DIS would be both more accurate and faster but that isn't true when considering the respective GPU implementations.
