### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by rutujar** [opencv/opencv#14370]
code:
gray = cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)

error
<ipython-input-1-88cc798ec402> in detectPlates(self)
     54 
     55         # convert the image to grayscale, and apply the blackhat operation
---> 56         gray = cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)
     57         PLOT(gray, 'GRAY')
     58         blackhat = cv2.morphologyEx(gray, cv2.MORPH_BLACKHAT, rectKernel)

error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\color.cpp:11147: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

**Comment by Mainvooid** [comment]
Why don't you update OpenCV to the latest version?

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org/
