### ISSUE TITLE
libjpeg-turbo faster execution, slower VideoCapture() framerate?

### ISSUE THREAD

**Issue by scottmudge** [opencv/opencv#14377]
Operating System: Lubuntu 18.04
Platform: x86_64
OpenCV Version: 4.1.0
CPU: Intel Atom Z8350
Memory: 2 GB

Compile Option In Question: BUILD_JPEG = YES/NO

Example code (python):

    cap = cv.VideoCapture()

    # Set prop
    cap.open(0, apiPreference=cv.CAP_V4L2)

    cap.set(cv.CAP_PROP_FOURCC, cv.VideoWriter_fourcc('M', 'J', 'P', 'G'))
    cap.set(cv.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv.CAP_PROP_FRAME_HEIGHT, 960)
    cap.set(cv.CAP_PROP_FPS, 30.0)
    cap.set(cv.CAP_PROP_AUTO_EXPOSURE, True)

    if not cap.isOpened():
        logger.error("Could not open camera.")
        exit(-1)

    while True:
        # Capture frame
        ret, frame = cap.read()

        if not ret:
            logger.warn("Could not receive frame.")

        cv.imshow('webcam', frame)
        if cv.waitKey(1) == ord('q'):
           break

When compiling with BUILD_JPEG enabled (thus building libjpeg_turbo in the 3rdparty directory), using the above code I am only able to achieve 17 FPS when 30 is requested, at ~30% CPU utilization. This utilization is restricted to a single core.

However, when compiling using the system libjpeg library, the same code yields a maximum capture FPS of >= 30 FPS, when 30 is requested. However, the CPU utilization is considerably higher at 50-60%. The utilization is spread evenly over 3-4 cores.

I would prefer the higher framerate over less CPU overhead, but what I do not understand is why using libjpeg-turbo produces a lower framerate.

Is there something about libjpeg-turbo that requires it to operate on a single thread? How can I enable multiple threads?

**Comment by scottmudge** [comment]
If this is on an invalid tracker, where should it go? It involves OpenCV's implementation/integration of libjpeg-turbo and the opencv-videoio module.

**Comment by mshabunin** [comment]
Try to measure real performance of capture and drawing:
```.py
tick_cap = cv.TickMeter()
# ...
    tick_cap.start()
    ret, frame = cap.read()
    tick_cap.stop()

    print("Capture FPS: {}".format(tick_cap.getCounter() / tick_cap.getTimeSec()))
```
