### ISSUE TITLE
Build OpenCV 4.0.1 for UWP

### ISSUE THREAD

**Issue by Rathod1806** [opencv/opencv#14388]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Windows UWP (Hololens)
- Compiler => Visual Studio 2017 
- CMake GUI => 3.14.2

##### Detailed description
Hi,

I am able to build the OpenCv 4.0.1 with extra contrib for x86 and x64 on desktop.
However failed for UWP platform on windows 10.

##### Steps to reproduce
Fallowed steps as per the below link.

https://medium.com/@rabbi.cse.sust.bd/how-to-build-opencv-for-universal-windows-platform-uwp-1a642ec09955

After fallowing steps CMake generate project successfully with extra contrib .

When try to build the solution the module compilation fails.

**Comment by alalek** [comment]
UWP is not in the list of supported/tested configurations for now. So OpenCV team can't help here.

I believe community can help here somehow.
But please avoid posting of text information via screenshots - it is ridiculous and search engines are not able to handle that properly.

Did you try [vcpkg](https://github.com/Microsoft/vcpkg) / [opencv package](https://github.com/Microsoft/vcpkg/tree/master/ports/opencv)?

**Comment by kinchungwong** [comment]
@Rathod1806 

> When try to build the solution the module compilation fails.

How does it fail? What are the error messages?

Although OpenCV team cannot help with UWP, please take time to review the Microsoft documentations on porting Win32 DLLs to UWP: https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019

**Comment by vonchenplus** [comment]
I found two compilation problems:
https://github.com/opencv/opencv/blob/1d2ef6b2a14fd5f80277d64b14e4a9a2faddc7d8/3rdparty/libpng/pngpriv.h#L560
https://github.com/opencv/opencv/blob/1d2ef6b2a14fd5f80277d64b14e4a9a2faddc7d8/modules/core/src/utils/datafile.cpp#L112

UWP Unsupport ExitProcess and GetModuleHandleEx, when I compile the UWP version, just comment it out and it will work.
