### ISSUE TITLE
Compiling code failed in atomic  of C++11   when include dnn.hpp

### ISSUE THREAD

**Issue by ib198669** [opencv/opencv#14386]
- OpenCV => 3.4.7   **static** lib   (the newest lib of opencv 3.4 branch)
- Operating System / Platform => Ubuntu14.04 64 Bit
- Compiler => g++-4.8 

error seems occurs in  C++11 in  atomic, this is compiling outputs :
<pre><code>
In file included from /work/lib/opencv/ubuntu14/3.4.7/include/opencv2/dnn/dnn.hpp:48:0,
                 from /work/lib/opencv/ubuntu14/3.4.7/include/opencv2/dnn.hpp:76,
                 from ../oop/cnn/classifier.hpp:3,
                 from src/detection.h:7,
                 from src/pic_render_service.h:41,
                 from src/pic_render_service.cpp:1:
/usr/include/c++/4.8/future: At global scope:
/usr/include/c++/4.8/future:313:7: error: ‘atomic_flag’ does not name a type
       atomic_flag          _M_retrieved;
       ^
/usr/include/c++/4.8/future: In constructor ‘std::__future_base::_State_base::_State_base()’:
/usr/include/c++/4.8/future:317:45: error: class ‘std::__future_base::_State_base’ does not have any field named ‘_M_retrieved’
       _State_base() noexcept : _M_result(), _M_retrieved(ATOMIC_FLAG_INIT) { }

</code></pre>

My Makefile shows as bellow:
<pre><code>
c = cc
c++ = g++
debug = 0
FILE = ../oop/

PKG_CFLAGS= -I /work/lib/opencv/ubuntu14/3.4.7/include

PKG_LIBS= \
-L /work/lib/opencv/ubuntu14/3.4.7/lib/x86_64-linux-gnu \
-L /work/lib/opencv/ubuntu14/3.4.7/share/OpenCV/3rdparty/lib/x86_64-linux-gnu \
-lopencv_photo \
-lopencv_highgui \
-lopencv_imgproc \
-lopencv_core \
-lopencv_imgcodecs \
-llibwebp -littnotify -llibprotobuf -lzlib \
-ldl -lm -lpthread -lrt -lz \
-lippiw -lippicv \
-lopencv_dnn
##-llibjpeg-turbo -llibwebp -llibpng -llibtiff -llibjasper -lIlmImf \

ifeq ($(debug), 1)
	GFLAG   = -g -fno-inline 
	SFLAG   =
	OFLAG   =
	APPNAME = libpic_detection_service.so.1.0.4
else
	GFLAG   =
	SFLAG   = -s
	OFLAG   = -O3
	APPNAME = libpic_detection_service.so.1.0.4
endif

OBJS = src/pic_render_service.o \
	$(FILE)/picture/picture_tools.o \
	$(FILE)/picture/cv_picture.o \
	$(FILE)/cv/cv_tools.o \
	$(FILE)/m_tools.o \
	##$(FILE)/face_detect/face_detect_mtcnn.o
	#src/ook/codecs/avdef \

CPPFLAGS = \
	-std=c++11 \
	-Wall -DNDEBUG -DP_LINUX -D_GNU_SOURCE -D__USE_GNU -D_GLIBCXX_ATOMIC \
	-DOPENCV_INCLUDED \
	-DCPU_ONLY \
	-fno-strict-aliasing \
	-shared \
	-fPIC \
	-I $(FILE) \
	-I ./src \
	$(PKG_CFLAGS)

.cpp.o:
	$(c++) $(CPPFLAGS) $(OFLAG) $(GFLAG) -c $< -o $@

all: $(OBJS)
	$(c++) $(SFLAG) -shared -o $(APPNAME) $(OBJS) \
	-lrt \
	-Wl,--version-script=libpic_detection_service.version \
	$(PKG_LIBS)

clean:
	rm -f $(OBJS)

</code></pre>

I dont know how to handle this error,   the error occurs in g++-5 , g++-6 as well ,I will appreciate it if you can help me .

**Comment by alalek** [comment]
Thank you for the report!

> -std=c++11

This flag is important for reproducing of this problem.

Could you try to `#include <atomic>` before opencv dnn header?

**Comment by ib198669** [comment]
@alalek    thanks for your that quick answer   ,   it seems that  there is "-D_GLIBCXX_ATOMIC" in my Makefile,   when undefined D_GLIBCXX_ATOMIC ,  the bug is gone
