### ISSUE TITLE
How could I Build OpenCV4Android from sources

### ISSUE THREAD

**Issue by sxl2016** [opencv/opencv#14397]
![image](https://user-images.githubusercontent.com/22267482/56545510-65e71700-65aa-11e9-9faf-ea070d6b7d37.png)
I found a tutorial to build opencv4android from sources.
But this tutorial can't be download. 502 Bad Gateway

**Comment by dkurt** [comment]
Please use a forum for build/usage questions: http://answers.opencv.org/

**Comment by alalek** [comment]
Mentioned page is some ancient outdated manual (> 5 years).

Actual build steps are here: http://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack
