### ISSUE TITLE
Failed to initialize Inference Engine backend: Unsupported primitive of type:

### ISSUE THREAD

**Issue by didulle** [opencv/opencv#14409]
Hi

I am trying to test the Intel Model "person-vehicle-bike-detection-crossroad-0078" using OpenCV 4.1. The model is loaded successfully with cv::dnn::readNetFromModelOptimizer. However, I have an error message complaining about "PriorBoxClustered" when I try to forward the result using "predictObjects". It seems that this type is not supported but appears in the list of supported layers: https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html

The full error message is the following:

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.1.0-openvino) Error: Assertion failed (Failed to initialize Inference Engine backend: Unsupported primitive of type: PriorBoxClustered name: x08_priorbox) in cv::dnn::InfEngineBackendNet::initPlugin, file C:\jenkins\workspace\OpenCV\OpenVINO\build\opencv\modules\dnn\src\op_inf_engine.cpp, line 747

How this issue could be solved? I have tried with other models from Intel repository but all the detection ones has a type in the last layers which is not supported by the Inference Engine.

**Comment by dkurt** [comment]
Cannot reproduce this issue. Please try to run the following script:

```python
import cv2 as cv
import numpy as np

net = cv.dnn.readNet('person-vehicle-bike-detection-crossroad-0078.bin',
                     'person-vehicle-bike-detection-crossroad-0078.xml')
inp = np.random.standard_normal([1, 3, 1024, 1024]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print (out.shape)
```

This way please add more details about OpenVINO version, Windows version. Provide minimal working example including `setupvars.bat` invocation if you have one.

**Comment by didulle** [comment]
Hi

I am using Windows 7 and OpenVino_2019.1.087 (I have the same issue with computer_vision_sdk_2018.5.456). I usually load caffe models and forward the results with no difficulty.

However for these Intel Models provided with the OpenVino release there are errors with some layers: 
PriorBoxClustered for person-vehicle-bike-detection-crossroad-0078
PriorBox for person-vehicle-bike-detection-crossroad-0078
pixel_link/resize_images/ResizeBilinear for text-detection-0001

It seems that some layers even if they are listed here: https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html They are not linked.

Is there any tutorial on how to add a custom layer or to link those supported layers

Best regards

**Comment by dkurt** [comment]
@didulle, The problem in the `cpu_extension` library. OpenCV just cannot find it. So that's why I asked you to try to run a Python sample (if you can) so we can check if this is a problem in your application or not.

Please show the content of `C:\Program Files (x86)\IntelSWTools\openvino\bin\intel64\Release`

It seems to me that there is only AVX2 version of `cpu_extension.dll` library but your hardware doesn't support AVX2.

Please check boolean output of the following method:

```cpp
cv::checkHardwareSupport(cv::CPU_AVX2)
```

**Comment by didulle** [comment]
Hi

yes it's probably the cpu_extension since most of the layers getting the errors are located here
C:\Program Files (x86)\IntelSWTools\openvino_2019.1.087\deployment_tools\inference_engine\src\extension

The Dll generated is the following: cpu_extension_avx2.dll
cv::checkHardwareSupport(CV_CPU_AVX2) returns 0

**Comment by dkurt** [comment]
@didulle, So let's try one of the following ways to solve it:

1. Just copy `cpu_extension_avx2.dll` and name it `cpu_extension.dll`. This is very simple but I'm not sure that it'll work.
2. Build the library by yourself:
* Open Developer Command Prompt
* Go somewhere and create a build folder
```
cd C:\Users\user_name
mkdir build
cd build
````
* Run setupvars.bat:
```
"C:\Program Files (x86)\IntelSWTools\openvino\bin\setupvars.bat"
```
* Run cmake
```
"C:\Program Files\CMake\bin\cmake.exe" ^
  -G "Visual Studio 14 Win64" ^
   "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\inference_engine\samples"
```
* Build (it builds all the samples. Maybe there is a way to specify only extensions library target)
```
"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release -- /m:4
```
* Copy library from `build\intel64\Release\cpu_extension.dll` to `C:\Program Files (x86)\IntelSWTools\openvino\bin\intel64\Release`

**Comment by alalek** [comment]
> cv::checkHardwareSupport(CV_CPU_AVX2) returns 0

What CPU/OS are you using?

Please add dump of `opencv_version --hw`.

**Comment by didulle** [comment]
Hi

Just by renaming cpu_extension_avx2.dll on cpu_extension.dll it works

Many thanks !!!

**Comment by razzOn2calculus** [comment]
@dkurt  , In openvino 2020.1 , there are no cpu extension available still getting error. 


```
(base) C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo>demo_s
queezenet_download_convert_run.bat
target_precision = FP16
ECHO is off.
PYTHONPATH=C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\open_mo
del_zoo\tools\accuracy_checker;C:\Program Files (x86)\IntelSWTools\openvino\pyth
on\python3.6;C:\Program Files (x86)\IntelSWTools\openvino\python\python3;C:\Prog
ram Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer;C:\Progra
m Files (x86)\IntelSWTools\openvino_2019.3.379\python\python3.6
[setupvars.bat] OpenVINO environment initialized
INTEL_OPENVINO_DIR is set to C:\Program Files (x86)\IntelSWTools\openvino
ECHO is off.
Requirement already satisfied: pyyaml in c:\users\ra\anaconda3\lib\site-packages
 (from -r C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\..\
open_model_zoo\tools\downloader\requirements.in (line 1)) (3.12)
Requirement already satisfied: requests in c:\users\ra\anaconda3\lib\site-packag
es (from -r C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\.
.\open_model_zoo\tools\downloader\requirements.in (line 2)) (2.18.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\ra\anaconda3\li
b\site-packages (from requests->-r C:\Program Files (x86)\IntelSWTools\openvino\
deployment_tools\demo\..\open_model_zoo\tools\downloader\requirements.in (line 2
)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\ra\anaconda3\lib\site-
packages (from requests->-r C:\Program Files (x86)\IntelSWTools\openvino\deploym
ent_tools\demo\..\open_model_zoo\tools\downloader\requirements.in (line 2)) (2.6
)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\ra\anaconda3\li
b\site-packages (from requests->-r C:\Program Files (x86)\IntelSWTools\openvino\
deployment_tools\demo\..\open_model_zoo\tools\downloader\requirements.in (line 2
)) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ra\anaconda3\lib\s
ite-packages (from requests->-r C:\Program Files (x86)\IntelSWTools\openvino\dep
loyment_tools\demo\..\open_model_zoo\tools\downloader\requirements.in (line 2))
(2018.1.18)
Download public squeezenet1.1 model
python "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\open_model
_zoo\tools\downloader\downloader.py" --name "squeezenet1.1" --output_dir "C:\Use
rs\ra\Documents\Intel\OpenVINO\openvino_models\models" --cache_dir "C:\Users\ra\
Documents\Intel\OpenVINO\openvino_models\cache"
################|| Downloading models ||################

========== Retrieving C:\Users\ra\Documents\Intel\OpenVINO\openvino_models\model
s\public\squeezenet1.1\squeezenet1.1.prototxt from the cache

========== Retrieving C:\Users\ra\Documents\Intel\OpenVINO\openvino_models\model
s\public\squeezenet1.1\squeezenet1.1.caffemodel from the cache

################|| Post-processing ||################

========== Replacing text in C:\Users\ra\Documents\Intel\OpenVINO\openvino_model
s\models\public\squeezenet1.1\squeezenet1.1.prototxt
squeezenet1.1 model downloading completed

Waiting for 0 seconds, press a key to continue ...

Target folder C:\Users\ra\Documents\Intel\OpenVINO\openvino_models\ir\public\squ
eezenet1.1\FP16 already exists. Skipping IR generation with Model Optimizer.
If you want to convert a model again, remove the entire C:\Users\ra\Documents\In
tel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16 folder.

Waiting for 0 seconds, press a key to continue ...

###############|| Generate VS solution for Inference Engine samples using cmake
||###############


Waiting for 0 seconds, press a key to continue ...
Creating Visual Studio 16 2019 x64 files in C:\Users\ra\Documents\Intel\OpenVINO
\inference_engine_samples_build...
CMake Error at CMakeLists.txt:7 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/ra/Documents/Intel/OpenVINO/inference_engine_samples_build/CM
akeFiles/CMakeOutput.log".
Error

```

I have already installed latest version of visual studio, also downloaded build tools bundle. It didnt worked. In 2019.1 I had used and build the **cpu_extension.dll** and as i copied it to the path , even it does get error as i asked  [unsupported primitive type](https://github.com/opencv/opencv/issues/16540) . After new installation cpu_extension_avx2.dll was not available. Any solution .

**Comment by dkurt** [comment]
>   Generator
    Visual Studio 16 2019
  could not find any instance of Visual Studio.

That means you have no MS Visual Studio of that version.

**Comment by razzOn2calculus** [comment]
I have installed it, latest MS visual Studio. I tried to solve problem for 2019 by this
[CMake: Visual Studio 15 2017 could not find any instance of Visual Studio](https://stackoverflow.com/questions/51668676/cmake-visual-studio-15-2017-could-not-find-any-instance-of-visual-studio) .
 
Also previously i was also getting error like that, even my visual studio is just installed recently "Visual Studio 19 Win64"  didnt worked surprisingly your answer visual studio worked "Visual Studio 14 Win64". 
Now i installed latest openvino , and run  all installations including **demo_s
queezenet_download_convert_run.bat**
It throws error same error i was previously getting in older openvino
Please help me to figure out changes should i make  to "Visual Studio 14" or try different  version.


[New Text Document.txt](https://github.com/opencv/opencv/files/4181619/New.Text.Document.txt)

**Comment by razzOn2calculus** [comment]
Problem not solved . I had successfully installed it, even not working.

**Comment by dkurt** [comment]
Try to clean build directory, check which other generators are available by CMake. Attach the list here.

**Comment by razzOn2calculus** [comment]
In 2020.1 version, After installing and running the demo It thrown same error
**Could not find instance of visual studio**

I've uninstalled 2019 visual studio, and after installing visual studio 2017 , also same error with
**Visual Studio 15 2017.... Could ot find any instance of Visual Studio**

I ran with my own code, now giving another error, 
**RuntimeError: Failed to create plugin MKLDNNPlugin.dll for device CPU**
I found two MKLDNNPlugin.dll files. I am not getting what to do with it. 
I've also gave that issue, but unsolved yet  [Failed to create plugin MKLDNNPlugin.dll ](https://github.com/opencv/opencv/issues/16557) .

**Comment by razzOn2calculus** [comment]
I installed ubuntu and problem solved successfully. Thanks @dkurt   and @alalek :)

**Comment by beep-love** [comment]
I have the same issue occurring with me in Windows. Do this problem meet any solution in windows format???

**Comment by beep-love** [comment]
The error that I encountered in Windows is exactly the same.

> Creating Visual Studio 16 2019 x64 files in C:\Users\rbipl\Documents\Intel\OpenVINO\inference_engine_samples_build...
> CMake Error at CMakeLists.txt:7 (project):
>   Generator
> 
>     Visual Studio 16 2019
> 
>   could not find any instance of Visual Studio.
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/rbipl/Documents/Intel/OpenVINO/inference_engine_samples_build/CMakeFiles/CMakeOutput.log".
> Error

I have set up the necessary variables,
I went through the directory deployment_tools\demo and selected demo_squeezenet_download_convert_run.bat and encountered this error at this step termed as

 **' Generate VS solution for Inference Engine samples using cmake'**
 after IR generation with model optimizer.

**Comment by AAA-Fan** [comment]
I got the same issue: 
[ INFO ] Loading Person Detection model to the CPU device
[ ERROR ] Unsupported primitive of type: PriorBoxClustered name: x08_priorbox
when I use the demo to test the pre-trained model person-vehicle-bike-detection-crossroad-0078.
My environment: Ubuntu 16.04.5
openvino: 2019.3.334
opencv: opencv3.4

How can I fix it?

**Comment by dkurt** [comment]
@AAA-Fan, is that for GPU target? Please check that there are `/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/cldnn_global_custom_kernels/`. It contains `prior_box_clustered.cl` which is necessary file for now for GPU plugin of Inference Enine.
