### ISSUE TITLE
opencv4.1.0 build error

### ISSUE THREAD

**Issue by cheermc** [opencv/opencv#14417]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => CentOS 6.3
- Compiler => gcc 4.46 / cmake 3.14.3

##### Steps to reproduce

I want to generate libopencv_java410.so for my project.

I reference to this link: https://docs.opencv.org/4.1.0/d7/d9f/... .

After I execute 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF ..', it seems ok.

And then I execute 'make', things go wrong on libprotobuf. The command line errors are in the text file:
[cmake_error.txt](https://github.com/opencv/opencv/files/3116018/cmake_error.txt)

I wonder why this happens and how to solve it. Thanks in advance.

**Comment by alalek** [comment]
> gcc 4.46

OpenCV 4.1 is tested with GCC 5.4+
Try to exclude protobuf from build via CMake flags: `cmake -DWITH_PROTOBUF=OFF ...`

**Comment by cheermc** [comment]
which gcc version should I use? I exclude protobuf but more problems occurs. 

Some module gives me "OpenCV 4.x+ requires enabled C++11 support" error and after I google it, I use -DCMAKE_CXX_FLAGS="-std=c++0x" (because -std=c++11 is not supported in my gcc version). But things remain unchanged.

The errors are:
[ 28%] Building CXX object modules/core/CMakeFiles/opencv_test_core_pch_dephelp.dir/opencv_test_core_pch_dephelp.cxx.o
In file included from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core.hpp:52,
                 from /home/meicheng/tools/opencv-4.1.0/modules/ts/include/opencv2/ts.hpp:10,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/test/test_precomp.hpp:7,
                 from /home/meicheng/tools/opencv-4.1.0/build/modules/core/opencv_test_core_pch_dephelp.cxx:1:
/home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/cvdef.h:666:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
In file included from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/base.hpp:58,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core.hpp:54,
                 from /home/meicheng/tools/opencv-4.1.0/modules/ts/include/opencv2/ts.hpp:10,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/test/test_precomp.hpp:7,
                 from /home/meicheng/tools/opencv-4.1.0/build/modules/core/opencv_test_core_pch_dephelp.cxx:1:
/home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/cvstd_wrapper.hpp:16: error: ‘std::nullptr_t’ has not been declared
In file included from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core/base.hpp:58,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/include/opencv2/core.hpp:54,
                 from /home/meicheng/tools/opencv-4.1.0/modules/ts/include/opencv2/ts.hpp:10,
                 from /home/meicheng/tools/opencv-4.1.0/modules/core/test/test_precomp.hpp:7,
                 from /home/meicheng/tools/opencv-4.1.0/build/modules/core/opencv_test_core_pch_dephelp.cxx:1:

Maybe I should upgrade my gcc version?

**Comment by alalek** [comment]
CentOS 6.3 has been released in Aug 2012.
Probably you should try some outdated OpenCV 2.4.x (not recommended for using actually).

OpenCV 4.x requires C++11 compiler. It is mandatory.
