### ISSUE TITLE
error installation opencv on mac

### ISSUE THREAD

**Issue by vadly** [opencv/opencv#14415]
Hi all
please help me, i found this error while trying to install opencv on mac

Nurvadli-MacBook-Pro:build vadly$ make
[  2%] Built target zlib
[  5%] Built target libjpeg-turbo
[  8%] Built target libtiff
[ 16%] Built target libwebp
[ 19%] Built target libjasper
[ 21%] Built target libpng
[ 26%] Built target IlmImf
[ 28%] Built target ippiw
[ 33%] Built target libprotobuf
[ 33%] Built target quirc
[ 33%] Built target ittnotify
[ 34%] Built target ade
[ 34%] Built target opencv_videoio_plugins
[ 34%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:49:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/utility.hpp:56:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core.hpp:52:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/cvdef.h:782:39: error: 
      use of undeclared identifier '_mm_cvtps_ph'; did you mean '_mm_cvtss_sd'?
        w = (ushort)_mm_cvtsi128_si32(_mm_cvtps_ph(v, 0));
                                      ^~~~~~~~~~~~
                                      _mm_cvtss_sd
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/emmintrin.h:420:1: note: 
      '_mm_cvtss_sd' declared here
_mm_cvtss_sd(__m128d __a, __m128 __b)
^
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:49:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/utility.hpp:56:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core.hpp:52:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/cvdef.h:782:55: error: 
      cannot initialize a parameter of type '__m128'
      (vector of 4 'float' values) with an rvalue of type 'int'
        w = (ushort)_mm_cvtsi128_si32(_mm_cvtps_ph(v, 0));
                                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/emmintrin.h:420:34: note: 
      passing argument to parameter '__b' here
_mm_cvtss_sd(__m128d __a, __m128 __b)
                                 ^
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:49:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/utility.hpp:56:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core.hpp:52:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/cvdef.h:813:26: error: 
      use of undeclared identifier '_mm_cvtph_ps'; did you mean '_mm_cvtpd_ps'?
        _mm_store_ss(&f, _mm_cvtph_ps(_mm_cvtsi32_si128(w)));
                         ^~~~~~~~~~~~
                         _mm_cvtpd_ps
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/emmintrin.h:376:1: note: 
      '_mm_cvtpd_ps' declared here
_mm_cvtpd_ps(__m128d __a)
^
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:85:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin.hpp:179:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp:2746:24: error: 
      use of undeclared identifier '_mm256_cvtph_ps'; did you mean
      '_mm256_cvtpd_ps'?
    return v_float32x8(_mm256_cvtph_ps(_mm_loadu_si128((const __m128i*)ptr)));
                       ^~~~~~~~~~~~~~~
                       _mm256_cvtpd_ps
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/avxintrin.h:539:1: note: 
      '_mm256_cvtpd_ps' declared here
_mm256_cvtpd_ps(__m256d __a)
^
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:85:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin.hpp:179:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp:2746:40: error: 
      cannot initialize a parameter of type '__m256d' (vector of 4 'double'
      values) with an rvalue of type '__m128i' (vector of 2 'long long' values)
    return v_float32x8(_mm256_cvtph_ps(_mm_loadu_si128((const __m128i*)ptr)));
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/avxintrin.h:539:25: note: 
      passing argument to parameter '__a' here
_mm256_cvtpd_ps(__m256d __a)
                        ^
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/src/precomp.hpp:85:
In file included from /Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin.hpp:179:
/Users/nurvadli/Documents/parallel/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp:2751:18: error: 
      use of undeclared identifier '_mm256_cvtps_ph'
    __m128i ah = _mm256_cvtps_ph(a.val, 0);
                 ^
6 errors generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2
Nurvadli-MacBook-Pro:build vadly$

**Comment by shanemswartz** [comment]
I encountered the same error on CentOS 6.10.  Any help would be greatly appreciated.  Using gcc version 4.9.2 to compile.

[ 25%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o
/tmp/cc0YSvEr.s: Assembler messages:
/tmp/cc0YSvEr.s:1661: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:1662: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:1663: Error: suffix or operands invalid for `vpaddd'
/tmp/cc0YSvEr.s:1665: Error: no such instruction: `vgatherdps %ymm6,(%rax,%ymm4,4),%ymm5'
/tmp/cc0YSvEr.s:1666: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:1667: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:1668: Error: suffix or operands invalid for `vpaddd'
/tmp/cc0YSvEr.s:1672: Error: no such instruction: `vgatherdps %ymm5,(%rax,%ymm6,4),%ymm4'
/tmp/cc0YSvEr.s:1674: Error: suffix or operands invalid for `vpmaxsd'
/tmp/cc0YSvEr.s:1675: Error: suffix or operands invalid for `vpminsd'
/tmp/cc0YSvEr.s:1676: Error: suffix or operands invalid for `vpslld'
/tmp/cc0YSvEr.s:1678: Error: suffix or operands invalid for `vpmaxsd'
/tmp/cc0YSvEr.s:1679: Error: suffix or operands invalid for `vpminsd'
/tmp/cc0YSvEr.s:1681: Error: suffix or operands invalid for `vpslld'
/tmp/cc0YSvEr.s:1934: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:1936: Error: no such instruction: `vgatherdpd %ymm14,(%rax,%xmm1,8),%ymm15'
/tmp/cc0YSvEr.s:1937: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:1938: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:1939: Error: suffix or operands invalid for `vpaddd'
/tmp/cc0YSvEr.s:1941: Error: no such instruction: `vgatherdpd %ymm6,(%rax,%xmm1,8),%ymm14'
/tmp/cc0YSvEr.s:1942: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:1944: Error: suffix or operands invalid for `vpaddd'
/tmp/cc0YSvEr.s:1945: Error: suffix or operands invalid for `vpmaxsd'
/tmp/cc0YSvEr.s:1946: Error: suffix or operands invalid for `vpmaxsd'
/tmp/cc0YSvEr.s:1947: Error: suffix or operands invalid for `vpminsd'
/tmp/cc0YSvEr.s:1948: Error: suffix or operands invalid for `vpmovsxdq'
/tmp/cc0YSvEr.s:1949: Error: suffix or operands invalid for `vpminsd'
/tmp/cc0YSvEr.s:1950: Error: suffix or operands invalid for `vpmovsxdq'
/tmp/cc0YSvEr.s:1952: Error: suffix or operands invalid for `vpsllq'
/tmp/cc0YSvEr.s:1954: Error: suffix or operands invalid for `vpsllq'
/tmp/cc0YSvEr.s:2192: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:2193: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2194: Error: suffix or operands invalid for `vpsrad'
/tmp/cc0YSvEr.s:2195: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2196: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2197: Error: suffix or operands invalid for `vpor'
/tmp/cc0YSvEr.s:2202: Error: suffix or operands invalid for `vpsubd'
/tmp/cc0YSvEr.s:2225: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/cc0YSvEr.s:2407: Error: suffix or operands invalid for `vpsrlq'
/tmp/cc0YSvEr.s:2408: Error: suffix or operands invalid for `vpsrlq'
/tmp/cc0YSvEr.s:2432: Error: suffix or operands invalid for `vpaddq'
/tmp/cc0YSvEr.s:2433: Error: suffix or operands invalid for `vpsrlq'
/tmp/cc0YSvEr.s:2434: Error: suffix or operands invalid for `vpsrlq'
/tmp/cc0YSvEr.s:2435: Error: suffix or operands invalid for `vpsubq'
/tmp/cc0YSvEr.s:2436: Error: suffix or operands invalid for `vpshufd'
/tmp/cc0YSvEr.s:2437: Error: suffix or operands invalid for `vpsubq'
/tmp/cc0YSvEr.s:2438: Error: suffix or operands invalid for `vpshufd'
/tmp/cc0YSvEr.s:2439: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2440: Error: suffix or operands invalid for `vpunpcklqdq'
/tmp/cc0YSvEr.s:2441: Error: suffix or operands invalid for `vpunpcklqdq'
/tmp/cc0YSvEr.s:2442: Error: suffix or operands invalid for `vpor'
/tmp/cc0YSvEr.s:2443: Error: no such instruction: `vpermq $216,%ymm0,%ymm0'
/tmp/cc0YSvEr.s:2444: Error: no such instruction: `vpermq $216,%ymm1,%ymm1'
/tmp/cc0YSvEr.s:2446: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2447: Error: suffix or operands invalid for `vpand'
/tmp/cc0YSvEr.s:2449: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/cc0YSvEr.s:2450: Error: suffix or operands invalid for `vpsubd'
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by shanemswartz** [comment]
If I switch back to gcc version 4.7.3 the error output becomes:

[  7%] Built target libwebp
[  9%] Built target libjasper
[ 14%] Built target IlmImf
[ 16%] Built target ippiw
[ 22%] Built target libprotobuf
[ 23%] Built target quirc
[ 23%] Built target ittnotify
[ 24%] Built target ade
[ 24%] Built target opencv_videoio_plugins
[ 24%] Built target opencv_core_pch_dephelp
[ 24%] Built target opencv_perf_core_pch_dephelp
[ 25%] Built target opencv_highgui_pch_dephelp
[ 25%] Built target pch_Generate_opencv_highgui
[ 25%] Built target opencv_imgproc_pch_dephelp
[ 25%] Built target pch_Generate_opencv_imgproc
[ 25%] Built target pch_Generate_opencv_core
[ 25%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o
In file included from /opt/software_sources/OpenCV/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin.hpp:179:0,
                 from /opt/software_sources/OpenCV/opencv-4.1.0/modules/core/src/precomp.hpp:85,
                 from /opt/software_sources/OpenCV/opencv-4.1.0/build/modules/core/mathfuncs_core.avx2.cpp:2:
/opt/software_sources/OpenCV/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp: In function ‘cv::hal_AVX2::v_int8x32 cv::hal_AVX2::v_pack_triplets(const cv::hal_AVX2::v_int8x32&)’:
/opt/software_sources/OpenCV/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp:1601:161: error: ‘_mm256_broadcastsi128_si256’ was not declared in this scope
/opt/software_sources/OpenCV/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp: In function ‘cv::hal_AVX2::v_int16x16 cv::hal_AVX2::v_pack_triplets(const cv::hal_AVX2::v_int16x16&)’:
/opt/software_sources/OpenCV/opencv-4.1.0/modules/core/include/opencv2/core/hal/intrin_avx.hpp:1608:162: error: ‘_mm256_broadcastsi128_si256’ was not declared in this scope
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/mathfuncs_core.avx2.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2
