### ISSUE TITLE
Different results of stitching on 'samples/python/stitching.py' and 'samples/python/stitching_detailed.py'

### ISSUE THREAD

**Issue by MiracleHW** [opencv/opencv#14413]
- OpenCV =4.1.0
- Operating System / Platform => Windows 64 Bit
- Python = 3.5.6

Code:
https://github.com/opencv/opencv/blob/master/samples/python/stitching.py
https://github.com/opencv/opencv/blob/master/samples/python/stitching_detailed.py

I try to stitch 3 images using above sample code, but get different results, stitching.py is more better than stitching_detailed.py.
There is no change for these sample code and use default parameters.

![res](https://user-images.githubusercontent.com/19424263/56706925-594cf500-6749-11e9-9161-5689f3169442.jpg)   
stitching_detailed.py result

![out](https://user-images.githubusercontent.com/19424263/56706949-7f729500-6749-11e9-9fe4-dc91842cd521.jpg)
stitching.py result

**Comment by jmmeneguel** [comment]
I am facing the same problem, except that for me the masks seem to be equal, but the image provided by stitching_detailed.py is blurred.

Any solutions yet?
