### ISSUE TITLE
hi. i have an issue on using mex. it appears that the issue on Net_.cpp . i have no idea to fix it 

### ISSUE THREAD

**Issue by suyellazzmin** [opencv/opencv#14416]
Error using mex
Net_.cpp
C:\Users\Suhayl\Documents\MATLAB\bg\mexopencv-master\src\+cv\private\Net_.cpp(129): warning C4267: 'argument': conversion from 'size_t' to
'int', possible loss of data
C:\Users\Suhayl\Documents\MATLAB\bg\mexopencv-master\src\+cv\private\Net_.cpp(137): warning C4267: 'argument': conversion from 'size_t' to
'int', possible loss of data
C:\Users\Suhayl\Documents\MATLAB\bg\mexopencv-master\src\+cv\private\Net_.cpp(145): warning C4267: 'argument': conversion from 'size_t' to
'int', possible loss of data
C:\Users\Suhayl\Documents\MATLAB\bg\mexopencv-master\src\+cv\private\Net_.cpp(440): error C2039: 'deleteLayer': is not a member of
'cv::dnn::experimental_dnn_34_v11::Net'
c:\opencv(1)\build\include\opencv2\dnn\utils\../dnn.hpp(371): note: see declaration of 'cv::dnn::experimental_dnn_34_v11::Net'

**Comment by alalek** [comment]
> mexopencv-master

We don't maintain this.
Probably you should go here: https://github.com/kyamagu/mexopencv

**Comment by Kyle-RuidongLI** [comment]
same problem, too! can anyone help me with this?
