### ISSUE TITLE
Opencv 4.1.0 building from source is trying to use absolute paths for python bindings.

### ISSUE THREAD

**Issue by stevencnix** [opencv/opencv#14422]
System information (version)
OpenCV => 4.1.0
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2017

I was trying to build opencv with python bindings from source using cmake and visual studio 2017. I ran into issues when trying to run the Install Build and Package Build. I noticed the python files would do a few things. The first they would be put into my python site packages dir. The config-3.7.py file would contain an absolute path to my python environment instead of the normal LOADER_DIR. If I try to run the PACKAGE Build an error would be displayed saying it cant use absolute paths.

**Comment by alalek** [comment]
> The first would be put into my python site packages dir

We using `INSTALL_CREATE_DISTRIB=ON` to avoid that.

> The config-3.7.py file

There are multiple different contents for this file: build and install. What is the case you talking about?

> PACKAGE Build

What is that?
Provide exact error message.

---

Please provide exact used commands and CMake's parameters. It is hard to understand/reproduce your case.

BTW, there are our Python builds for [Windows package](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/10783).

**Comment by dkurt** [comment]
Let me close it due no response from author.
