### ISSUE TITLE
Pose Estimation Tutorial not compiling

### ISSUE THREAD

**Issue by alexs7** [opencv/opencv#14427]
I am trying to follow this: [https://docs.opencv.org/3.4.4/dc/d2c/tutorial_real_time_pose.html](https://docs.opencv.org/3.4.4/dc/d2c/tutorial_real_time_pose.html)

I create a directory "build" in 

> opencv/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation

and run `cmake ..`

I get this:

    CMake Error at CMakeLists.txt:15 (ocv_include_modules_recurse):
      Unknown CMake command "ocv_include_modules_recurse".
    
    
    CMake Warning (dev) in CMakeLists.txt:
      No cmake_minimum_required command is present.  A line of code such as
    
        cmake_minimum_required(VERSION 3.13)

I have OpenCV 2.4 compiled with `open_contrib` and 3.4 without. Usually when I compile a `.cpp` program that uses openCV I run.

    g++ $(pkg-config --cflags --libs /usr/local/Cellar/opencv@3/3.4.5/lib/pkgconfig/opencv.pc) -std=c++11 main.cpp

since I am on MacOS. Should I ignore `cmake` and compile it like that ? How do I fix the error ?

**Comment by alalek** [comment]
CMake script in "real_time_pose_estimation" directory is not supposed to be used as standalone entry point.

You can build this sample:
- with OpenCV itself (`cmake -DBUILD_EXAMPLES=ON ...`)
- try to use `samples/CMakeLists.txt` as root CMake

**Comment by alexs7** [comment]
@alalek Ok so I should rebuild all of OpenCV using the sdk ?  Do you mean recompile OpenCV ?

**Comment by alexs7** [comment]
I have managed to compile some of it (the _main_registration.cpp_ ) with `g++ $(pkg-config --cflags --libs /usr/local/Cellar/opencv@3/3.4.5/lib/pkgconfig/opencv.pc) -std=c++11 main_registration.cpp CsvReader.cpp CsvWriter.cpp Mesh.cpp Model.cpp PnPProblem.cpp RobustMatcher.cpp Utils.cpp ModelRegistration.cpp`
