### ISSUE TITLE
OpenCV 4.0.1 with CUDA 10 windows 10 64 bit

### ISSUE THREAD

**Issue by mlatjekson** [opencv/opencv#14425]
- OpenCV => 4.0.1 with cuda 10
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- cmake =>3.14.0

##### Detailed description
I am trying to build OpenCV 4.0.1 with CUDA 10 on VS 2015 windows 10 64 bit system. But multiple build are getting failed. I am attaching text file with all LINK errors.
[opencv_build_errors.txt](https://github.com/opencv/opencv/files/3120533/opencv_build_errors.txt)

**Comment by alalek** [comment]
> 4.0.1

Avoid using of old releases. The latest code has more adequate error message.
CUDA modules has been moved into opencv_contrrib repository since OpenCV 4.0.

**Comment by mlatjekson** [comment]
> 
> 
> > 4.0.1
> 
> Avoid using of old releases. The latest code has more adequate error message.
> CUDA modules has been moved into opencv_contrrib repository since OpenCV 4.0.

Thnak you Alalek.
