### ISSUE TITLE
mac os go run  ./cmd/version/main.go error

### ISSUE THREAD

**Issue by khlipeng** [opencv/opencv#14421]
➜  gocv git:(master) ✗ go run ./cmd/version/main.go                    

dyld: Library not loaded: /usr/local/opt/glog/lib/libglog.0.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_sfm.4.1.dylib
  Reason: image not found
signal: abort trap
➜  gocv git:(master) ✗ go run -tags customenv ./cmd/version/main.go

# gocv.io/x/gocv
In file included from calib3d.cpp:1:
./calib3d.h:5:10: fatal error: 'opencv2/opencv.hpp' file not found

**Comment by alalek** [comment]
There is no support for Go bindings in this repository.

> calib3d.h

Ancient C API has been deprecated since OpenCV 2.4 and it is gone from OpenCV 4.x.

**Comment by khlipeng** [comment]
opencv_version 
4.1.0  @alalek

**Comment by khlipeng** [comment]
solved, not installed glog,
