### ISSUE TITLE
Building with cmake 3.14.3 

### ISSUE THREAD

**Issue by rashenoy** [opencv/opencv#14436]
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => OSX Mojave
- Compiler => 10.0.1.10010046
- Python => 2.7.10
- Cmake - 3.14.3 installed using homebrew

##### Detailed description
In cmake 3.14.3 tree there exists an iOS.cmake (share/cmake/Modules/Platforms). In the build process, CMakeSystemSpecificInformation.cmake picks the iOS.cmake from cmake-3.14.3 tree instead of the opencv tree (platforms/ios/cmake/Modules/Platforms). As a result, the build process fails. 

The last version of cmake I tried (3.12.0) there no iOS.cmake inside the cmake tree. 

##### Steps to reproduce
Build command:
python platforms/ios/build_framework.py /ios
Fails

**Comment by alalek** [comment]
> OpenCV => 3.2.0

Why are you trying to use old OpenCV (> 2 years) with fresh dependencies? Failure is expected in these cases.

Try latest release / code from 3.4/master branches at first.

**Comment by rashenoy** [comment]
Legacy reasons

**Comment by rashenoy** [comment]
Same issue on when I try to build on 3.4.2
