### ISSUE TITLE
Fail to build opencv3.4.6

### ISSUE THREAD

**Issue by cheermc** [opencv/opencv#14439]
##### System information (version)

- OpenCV => 3.4.6
- Operating System / Platform => centos6.3
- Compiler => 4.8.2

##### Detailed description

I try to build opencv3.4.6 but the below errors occurs:

[ 57%] Built target opencv_imgcodecs
[ 57%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o
BullseyeCoverage Compile C++ 8.13.21 Linux-x64 License 3179 
Copyright (c) Bullseye Testing Technology 1990-2017
BullseyeCoverage Compile C++ 8.13.21 Linux-x64 License 3179 
Copyright (c) Bullseye Testing Technology 1990-2017
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp: In function 'int cv::capPropertyToV4L2(int)':
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp:1614:9: error: 'V4L2_CID_ROTATE' was not declared in this scope
         return V4L2_CID_ROTATE;
         ^
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp:1616:9: error: 'V4L2_CID_IRIS_ABSOLUTE' was not declared in this scope
         return V4L2_CID_IRIS_ABSOLUTE;
         ^
BullseyeCoverage error: status 1 from /opt/compiler/gcc-4.8.2/bin/c++
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:154: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2515: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

My cmake command is:
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_contrib=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_photo=OFF  ..

I execlude some modules because some compile errors happens.
But I can not exclude opencv_imgcodecs, so what's the solution?
Thanks in advance.

**Comment by alalek** [comment]
Similar issues: #13335 #13929

**Comment by cheermc** [comment]
@alalek Do you mean this problem was solved in 3.4.7? Where can I download this version?

**Comment by cheermc** [comment]
I add some default value for this two parameters, then another problem comes:

[ 59%] Linking CXX executable ../../bin/opencv_test_core
BullseyeCoverage Compile C++ 8.13.21 Linux-x64 License 3179 
Copyright (c) Bullseye Testing Technology 1990-2017
/home/opt/gcc-4.8.2.bpkg-r2/gcc-4.8.2.bpkg-r2/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../x86_64-baidu-linux-gnu/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
BullseyeCoverage error: status 1 from /opt/compiler/gcc-4.8.2/bin/c++
make[2]: *** [modules/core/CMakeFiles/opencv_test_core.dir/build.make:679: bin/opencv_test_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:1719: modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

How can I solve it?

**Comment by alalek** [comment]
We don't have configuration setup with CentOS 6.3. Especially with custom compiler installation.

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

"Milestone" is used as a target version for the fix (3.4.7 is not released).

**Comment by cheermc** [comment]
@alalek Thanks for your replay. Could you give a valid environment which I can build 3.4.6 successfully? Maybe I can create a new operating system to do this.

**Comment by cheermc** [comment]
@alalek I change my environment and finally I use 2.4.13 for my project. Thanks for your patient explanation.
