### ISSUE TITLE
Memory Leak Video Capture

### ISSUE THREAD

**Issue by balachandarsv** [opencv/opencv#14449]
- OpenCV => 4.0.1
- Operating System / Platform => Ubuntu 16.04

##### Detailed description
VideoCapture Backend : FFMPEG 
Language  : JAVA
The memory keeps on increasing and system hangs. We tried calling System.gc() after every 1000 frames, which prevented the system from hanging but still the memory keeps on increasing. Is there a way to find out what exactly causes the leak?  

Also I would like to know if any one faced such issue before or have tried any work around do let me know.

Thanks in advance.

**Comment by balachandarsv** [comment]
I would like to take this up and try to fix, if someone can tell me where to start from?

**Comment by alalek** [comment]
Take a look on this issue: #7919 and others connected.
