### ISSUE TITLE
Having issue with ROS Package : video_stream_opencv

### ISSUE THREAD

**Issue by dohkim119** [opencv/opencv#14453]
I'm the one who are using ros package named 'video_stream_opencv'.

While I'm using it, I met a problem getting video stream from the device.

Here is my H/W Spec and situation.

- Board : Jetson TX2

- Device : Fushicai USBTV007 Video Grabber [EasyCAP]

- rosdistro : ROS- Kinetic

- OS : Ubuntu 16.04

- OpenCV : 3.4.1 (replace 3.3.1-dev cv2.so with 3.4.1 cv2.so)

So I tried to get a video stream through the Easycap. 
The './test_video_resource.py' works well at the moment at it shows video stream. 
But when I use 'webcam_launch', if keep showing 'VIDIOC_QUERYCTRL: Inappropriate ioctl for device' error message. 

So would anyone can give me some advice to solve this problem?

**Comment by alalek** [comment]
> ros package named 'video_stream_opencv'

We don't maintain this package here. Consider finding the proper repository.

> VIDIOC_QUERYCTRL

We observing this message with some devices, but it is showed only once per camera opening (stream is still captured well).

**Comment by skhadem** [comment]
@dohkim119 I have gotten the same error while using a kinect switching between ROS and OpenCV. There was an issue with freeing the memory by libfreenect I believe. My solution was to unplug and replug the camera before calling OpenCV's capture. Also removing and re adding the drivers "sudo modprobe..." has fixed issues for me in the past
