### ISSUE TITLE
multy-threads problem with DNN

### ISSUE THREAD

**Issue by linquanxu** [opencv/opencv#14456]
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

Hi,I used DNN to detect the images which inferred with yoloV3. I found that all of CPUS have been used.so I didn't have free gpu to run other programs.  how to set the numbers of threads?

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org/
