### ISSUE TITLE
Which dataset has been used to train hogcascade_pedestrians.xml ?

### ISSUE THREAD

**Issue by lovehell** [opencv/opencv#14458]
Hi,

Do you know by any chance which dataset has been used to train hogcascade_pedestrians.xml (opencv/data/hogcascades/) ? 
I do not manage to find similar performances when training with Inria pedestrian dataset. I played a lot with the input parameters but I definitely think that 600 pos and 1200 neg images are not enough. 
Any tips about the used dataset would be welcomed :) 

Thanks

**Comment by alalek** [comment]
Check similar question: https://answers.opencv.org/question/15646/hog-cascadeclassifier-training-amount-of-samples/

**Comment by lovehell** [comment]
Thanks
