### ISSUE TITLE
Install fails on Fedora 30

### ISSUE THREAD

**Issue by fuzzyBatman** [opencv/opencv#14466]
Built OpenCV 4.1.0-openvino with CUDA on Fedora 30
Build was successful.
Ran `sudo make install` and  the process fails at 99% :(

```
[ 99%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
In file included from /home/fuzzybatman/Downloads/src/opencv/modules/python/src2/cv2.cpp:109:
/home/fuzzybatman/Downloads/src/opencv/build/modules/python_bindings_generator/pyopencv_generated_include.h:14:10: fatal error: opencv2/cudaarithm.hpp: No such file or directory
   14 | #include "opencv2/cudaarithm.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:63: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9594: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

Is this an [opencv_contrib](https://github.com/opencv/opencv_contrib) issue?

**Comment by fuzzyBatman** [comment]
Opened an issue at opencv_contrib as well.
Issue [2112](https://github.com/opencv/opencv_contrib/issues/2112)

**Comment by alalek** [comment]
Exact parameter of failed command are required. Capture them via `make VERBOSE=1`.

**Comment by fuzzyBatman** [comment]
```
make -f modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/depend
make[2]: Entering directory '/home/fuzzybatman/Downloads/src/opencv/build'
cd /home/fuzzybatman/Downloads/src/opencv/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/fuzzybatman/Downloads/src/opencv /home/fuzzybatman/Downloads/src/opencv/modules/python/bindings /home/fuzzybatman/Downloads/src/opencv/build /home/fuzzybatman/Downloads/src/opencv/build/modules/python_bindings_generator /home/fuzzybatman/Downloads/src/opencv/build/modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/fuzzybatman/Downloads/src/opencv/build'
make -f modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build
make[2]: Entering directory '/home/fuzzybatman/Downloads/src/opencv/build'
make[2]: Nothing to be done for 'modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build'.
make[2]: Leaving directory '/home/fuzzybatman/Downloads/src/opencv/build'
[ 98%] Built target gen_opencv_python_source
make -f modules/python3/CMakeFiles/opencv_python3.dir/build.make modules/python3/CMakeFiles/opencv_python3.dir/depend
make[2]: Entering directory '/home/fuzzybatman/Downloads/src/opencv/build'
cd /home/fuzzybatman/Downloads/src/opencv/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/fuzzybatman/Downloads/src/opencv /home/fuzzybatman/Downloads/src/opencv/modules/python/python3 /home/fuzzybatman/Downloads/src/opencv/build /home/fuzzybatman/Downloads/src/opencv/build/modules/python3 /home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/DependInfo.cmake --color=
Dependee "/home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/DependInfo.cmake" is newer than depender "/home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/depend.internal".
Dependee "cvconfig.h" is newer than depender "modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o".
Dependee "modules/python_bindings_generator/pyopencv_custom_headers.h" is newer than depends file "/home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/depend.internal".
Dependee "opencv2/opencv_modules.hpp" is newer than depends file "/home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/depend.internal".
Clearing dependencies in "/home/fuzzybatman/Downloads/src/opencv/build/modules/python3/CMakeFiles/opencv_python3.dir/depend.make".
Scanning dependencies of target opencv_python3
make[2]: Leaving directory '/home/fuzzybatman/Downloads/src/opencv/build'
make -f modules/python3/CMakeFiles/opencv_python3.dir/build.make modules/python3/CMakeFiles/opencv_python3.dir/build
make[2]: Entering directory '/home/fuzzybatman/Downloads/src/opencv/build'
[ 98%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
cd /home/fuzzybatman/Downloads/src/opencv/build/modules/python3 && /usr/lib64/ccache/c++  -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/fuzzybatman/Downloads/src/opencv/build/3rdparty/ippicv/ippicv_lnx/icv/include -I/home/fuzzybatman/Downloads/src/opencv/build/3rdparty/ippicv/ippicv_lnx/iw/include -I/home/fuzzybatman/Downloads/src/opencv/build -I/home/fuzzybatman/Downloads/src/opencv/modules/python/python3/include -I/home/fuzzybatman/Downloads/src/opencv/build/modules/python3 -I/home/fuzzybatman/Downloads/src/opencv/modules/core/include -I/home/fuzzybatman/Downloads/src/opencv/modules/flann/include -I/home/fuzzybatman/Downloads/src/opencv/modules/imgproc/include -I/home/fuzzybatman/Downloads/src/opencv/modules/ml/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/phase_unwrapping/include -I/home/fuzzybatman/Downloads/src/opencv/modules/photo/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/plot/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/reg/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/surface_matching/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/xphoto/include -I/home/fuzzybatman/Downloads/src/opencv/modules/dnn/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/freetype/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/fuzzy/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/hfs/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/img_hash/include -I/home/fuzzybatman/Downloads/src/opencv/modules/imgcodecs/include -I/home/fuzzybatman/Downloads/src/opencv/modules/videoio/include -I/home/fuzzybatman/Downloads/src/opencv/modules/highgui/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/bioinspired/include -I/home/fuzzybatman/Downloads/src/opencv/modules/features2d/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/line_descriptor/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/saliency/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/text/include -I/home/fuzzybatman/Downloads/src/opencv/modules/calib3d/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/ccalib/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/cvv/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/datasets/include -I/home/fuzzybatman/Downloads/src/opencv/modules/objdetect/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/rgbd/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/shape/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/structured_light/include -I/home/fuzzybatman/Downloads/src/opencv/modules/video/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/videostab/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/xfeatures2d/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/ximgproc/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/xobjdetect/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/aruco/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/bgsegm/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/dpm/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/face/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/optflow/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/sfm/include -I/home/fuzzybatman/Downloads/src/opencv/modules/stitching/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/superres/include -I/home/fuzzybatman/Downloads/src/opencv_contrib/modules/tracking/include -I/home/fuzzybatman/Downloads/src/opencv/modules/python/src2 -I/home/fuzzybatman/Downloads/src/opencv/build/modules/python_bindings_generator -isystem /usr/include/eigen3 -isystem /usr/include/openblas -isystem /usr/include/python3.7m -isystem /home/fuzzybatman/.local/lib/python3.7/site-packages/numpy/core/include  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations  -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-unused-function -Wno-deprecated-declarations -Wno-overloaded-virtual -Wno-undef -O2 -DNDEBUG  -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o -c /home/fuzzybatman/Downloads/src/opencv/modules/python/src2/cv2.cpp
In file included from /home/fuzzybatman/Downloads/src/opencv/modules/python/src2/cv2.cpp:109:
/home/fuzzybatman/Downloads/src/opencv/build/modules/python_bindings_generator/pyopencv_generated_include.h:14:10: fatal error: opencv2/cudaarithm.hpp: No such file or directory
   14 | #include "opencv2/cudaarithm.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:63: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[2]: Leaving directory '/home/fuzzybatman/Downloads/src/opencv/build'
make[1]: *** [CMakeFiles/Makefile2:9305: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make[1]: Leaving directory '/home/fuzzybatman/Downloads/src/opencv/build'
make: *** [Makefile:163: all] Error 2
```

**Comment by fuzzyBatman** [comment]
Alright.
There is no inclusion of the path
`-I ../opencv_contrib/modules/cudaarithm/include`

**Comment by alalek** [comment]
For some reason cudaarithm includes are missing in your command line.

Proper compilation command line should [look like this](http://pullrequest.opencv.org/buildbot/builders/master-contrib_cuda-lin64/builds/206/steps/compile%20release/logs/stdio):

>cd /build/master-contrib_cuda-lin64/build/modules/python3 && /usr/bin/ccache /usr/bin/c++   -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/master-contrib_cuda-lin64/build/3rdparty/ippicv/ippicv_lnx/icv/include -I/build/master-contrib_cuda-lin64/build/3rdparty/ippicv/ippicv_lnx/iw/include -isystem /build/master-contrib_cuda-lin64/build -isystem /usr/include/gdal -isystem /usr/include/eigen3 -isystem /usr/include/python3.5m -isystem /usr/lib/python3/dist-packages/numpy/core/include -I/build/master-contrib_cuda-lin64/opencv/modules/python/python3/include -I/build/master-contrib_cuda-lin64/build/modules/python3 -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudev/include -I/build/master-contrib_cuda-lin64/opencv/modules/core/include **-I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudaarithm/include** -I/build/master-contrib_cuda-lin64/opencv/modules/flann/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/hdf/include -I/build/master-contrib_cuda-lin64/opencv/modules/imgproc/include -I/build/master-contrib_cuda-lin64/opencv/modules/ml/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/phase_unwrapping/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/plot/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/quality/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/reg/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/surface_matching/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/viz/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudafilters/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudaimgproc/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudawarping/include -I/build/master-contrib_cuda-lin64/opencv/modules/dnn/include -I/build/master-contrib_cuda-lin64/opencv/modules/features2d/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/freetype/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/fuzzy/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/hfs/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/img_hash/include -I/build/master-contrib_cuda-lin64/opencv/modules/imgcodecs/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/line_descriptor/include -I/build/master-contrib_cuda-lin64/opencv/modules/photo/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/saliency/include -I/build/master-contrib_cuda-lin64/opencv/modules/videoio/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/xphoto/include -I/build/master-contrib_cuda-lin64/opencv/modules/calib3d/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudacodec/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudafeatures2d/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudastereo/include -I/build/master-contrib_cuda-lin64/opencv/modules/highgui/include -I/build/master-contrib_cuda-lin64/opencv/modules/objdetect/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/rgbd/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/shape/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/structured_light/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/text/include -I/build/master-contrib_cuda-lin64/opencv/modules/video/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/xfeatures2d/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/ximgproc/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/xobjdetect/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/aruco/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/bgsegm/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/bioinspired/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/ccalib/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudabgsegm/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudalegacy/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudaobjdetect/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/datasets/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/dpm/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/face/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/optflow/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/sfm/include -I/build/master-contrib_cuda-lin64/opencv/modules/stitching/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/tracking/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/cudaoptflow/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/superres/include -I/build/master-contrib_cuda-lin64/opencv_contrib/modules/videostab/include -I/build/master-contrib_cuda-lin64/opencv/modules/python/src2 -I/build/master-contrib_cuda-lin64/build/modules/python_bindings_generator  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-unused-function -Wno-deprecated-declarations -Wno-overloaded-virtual -Wno-undef -O3 -DNDEBUG  -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o -c /build/master-contrib_cuda-lin64/opencv/modules/python/src2/cv2.cpp

Probably you need to dig into CMake scripts.
Includes should be added [by this macro](https://github.com/opencv/opencv/blob/4.1.0/modules/python/common.cmake#L10-L13).
Also you can try to compare CMakeVars.txt output from [mentioned build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_cuda-lin64/builds/206).

**Comment by fuzzyBatman** [comment]
The include directories for all the cuda based opencv_contrib modules are missing in 
`build/modules/python3/CMakeFiles/opencv_python3.dir/flags.make`

**Comment by fuzzyBatman** [comment]
I hope this particular command does not require a version of GCC < 7.
I had built 4.0.1-openvino about a month ago and had no issues.

**Comment by alalek** [comment]
I hope you clean your build directory after Fedora upgrade.

**Comment by fuzzyBatman** [comment]
Did a clean install of Fedora 30

**Comment by alalek** [comment]
No, I mean that it is important to clean CMake cache if some dependencies are changed (it is located in build directory so easy way is to clean whole build directory).

**Comment by fuzzyBatman** [comment]
Did that.

I think it has to do with CUDA.
When I configure using cmake and generate the files I get
```
NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS)
    NVIDIA GPU arch:             61
    NVIDIA PTX archs:
```

When I run `sudo make install VERBOSE=1` I get

```
CMake Warning at cmake/OpenCVFindLibsPerf.cmake:35 (message):
  OpenCV is not able to find/configure CUDA SDK (required by WITH_CUDA).

  CUDA support will be disabled in OpenCV build.

  To eliminate this warning remove WITH_CUDA=ON CMake configuration option.
```

When I built the libraries a month ago, I used the CUDA toolkit from the Nvidia site. Now I am using them from the negativo17 repo on Fedora 30.

**Comment by alalek** [comment]
This is not expected message (see messages of [our CUDA build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_cuda-lin64) on CI).

Try to build without "sudo" (but cleanup build directory first again, because some files can be locked by "root" user).

---

Running `sudo make install` (or `sudo make <whatever>`) is a bad idea in general (see StackOverflow discussions):
- consider using of `CMAKE_INSTALL_PREFIX` instead (with path in home directory or writable by current user) - `make install` command will not require `sudo`
- ensure running with "root" of **installation step only** (after normal "make all"):
```
sudo /usr/bin/cmake -P cmake_install.cmake
sudo /usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
```
- try to build package first and install it via package manager. Try `checkinstall`, `cpack` or other tools. Main purpose of that is avoid issues with "uninstallation" step. Unfortunately, I have no exact guide here.

**Comment by fuzzyBatman** [comment]
Built and installed without sudo. Worked as it should. Thank you!

Did some reading on why using sudo is a bad idea. Thanks for pointing me in that direction.
I used sudo because the earliest installation guides did it this way. Never bothered to change.

Though, I'd still like to know why it worked before and not now. I believe it is due to the use of proprietary CUDA before, and from the negativo17 repo this time.
