### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'createTonemapDurand'

### ISSUE THREAD

**Issue by vishwesh5** [opencv/opencv#14468]
##### System information (version)

- OpenCV => 3.4.5, 4.0.1, 4.1.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.3.0

##### Detailed description

I am trying to use Tonemaping using different methods to obtain a 24-bit color image. All the following methods except `cv2.createTonemapDurand` are working fine.

1. cv2.createMergeDebevec
2. cv2.createTonemapDrago
3. cv2.createTonemapReinhard
4. cv2.createTonemapMantiuk

Here's the error I am getting:
```
AttributeError: module 'cv2' has no attribute 'createTonemapDurand'
```
I checked out the documentation but the function has been mentioned there so I don't think it has been removed.

##### Steps to reproduce

Script: [hdr.py](https://github.com/spmallick/learnopencv/blob/master/hdr/hdr.py)
Images can be found in [this](https://github.com/spmallick/learnopencv/tree/master/hdr) location.

**Comment by alalek** [comment]
Moved into opencv_contrib under NONFREE build flag.

**Comment by t2ac32** [comment]
what was the answer for this ?

**Comment by cianhwang** [comment]
Try cv2.createTonemap(2.2) instead, reference: https://docs.opencv.org/3.4/d3/db7/tutorial_hdr_imaging.html
