### ISSUE TITLE
A problem about dnn

### ISSUE THREAD

**Issue by ReedZyd** [opencv/opencv#14479]
When I use opencv 4.0.1 to load a training model，I have this problem.My model is .pb file.

**terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.1) /home/lab/install/opencv-4.0.1/modules/dnn/src/tensorflow/tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: pred_a/add/x in function 'connect'**

My code:
cv::dnn::Net net_gender = cv::dnn::readNet("/home/lab/Reed/Qt/Qt_face/SSR-Net/model/gender_model.pb")

**Comment by dkurt** [comment]
Please provide a minimal reproducible example. At least the mentioned `gender_model.pb` file.

**Comment by zhly0** [comment]
too much bug,take too much time using opencv to inference tf model.......

**Comment by dkurt** [comment]
Closing it due no response from author. There is no criteria to know if the problem is solved on our side. You need to provide at least the network source.
