### ISSUE TITLE
redeclaration of ‘IMREAD_UNCHANGED’ 

### ISSUE THREAD

**Issue by ChewbEp** [opencv/opencv#14485]
Hi everyone!
I am using Ubuntu 16.04 LTS, and I have written a simple code just to read and show an image; I have copied the entire code from the following link:

https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/introduction/display_image/display_image.cpp

I have just changed the image's path and name (for the rest, the code is exactly the same), and I've called this file "phoebe.cpp", and I have tried to compile it using the command:

`g++ -o phoebe phoebe.cpp`

So that's the error that appears:

> /usr/local/include/opencv2/highgui/highgui.hpp:165:25: error: redeclaration of ‘IMREAD_UNCHANGED’
>      IMREAD_UNCHANGED  =-1,
>                          ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:65:8: note: previous declaration ‘cv::ImreadModes IMREAD_UNCHANGED’
>         IMREAD_UNCHANGED            = -1, //!< If set, return the loaded image a
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:167:24: error: redeclaration of ‘IMREAD_GRAYSCALE’
>      IMREAD_GRAYSCALE  =0,
>                         ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:66:8: note: previous declaration ‘cv::ImreadModes IMREAD_GRAYSCALE’
>         IMREAD_GRAYSCALE            = 0,  //!< If set, always convert image to t
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:169:24: error: redeclaration of ‘IMREAD_COLOR’
>      IMREAD_COLOR      =1,
>                         ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:67:8: note: previous declaration ‘cv::ImreadModes IMREAD_COLOR’
>         IMREAD_COLOR                = 1,  //!< If set, always convert image to t
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:171:24: error: redeclaration of ‘IMREAD_ANYDEPTH’
>      IMREAD_ANYDEPTH   =2,
>                         ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:68:8: note: previous declaration ‘cv::ImreadModes IMREAD_ANYDEPTH’
>         IMREAD_ANYDEPTH             = 2,  //!< If set, return 16-bit/32-bit imag
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:173:24: error: redeclaration of ‘IMREAD_ANYCOLOR’
>      IMREAD_ANYCOLOR   =4
>                         ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:69:8: note: previous declaration ‘cv::ImreadModes IMREAD_ANYCOLOR’
>         IMREAD_ANYCOLOR             = 4,  //!< If set, the image is read in any 
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:178:27: error: redeclaration of ‘IMWRITE_JPEG_QUALITY’
>      IMWRITE_JPEG_QUALITY =1,
>                            ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:82:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_JPEG_QUALITY’
>         IMWRITE_JPEG_QUALITY        = 1,  //!< For JPEG, it can be a quality fro
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:179:30: error: redeclaration of ‘IMWRITE_PNG_COMPRESSION’
>      IMWRITE_PNG_COMPRESSION =16,
>                               ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:88:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_COMPRESSION’
>         IMWRITE_PNG_COMPRESSION     = 16, //!< For PNG, it can be the compressio
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:180:27: error: redeclaration of ‘IMWRITE_PNG_STRATEGY’
>      IMWRITE_PNG_STRATEGY =17,
>                            ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:89:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_STRATEGY’
>         IMWRITE_PNG_STRATEGY        = 17, //!< One of cv::ImwritePNGFlags, defau
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:181:26: error: redeclaration of ‘IMWRITE_PNG_BILEVEL’
>      IMWRITE_PNG_BILEVEL =18,
>                           ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:90:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_BILEVEL’
>         IMWRITE_PNG_BILEVEL         = 18, //!< Binary level PNG, 0 or 1, default
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:182:35: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_DEFAULT’
>      IMWRITE_PNG_STRATEGY_DEFAULT =0,
>                                    ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:105:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_DEFAULT’
>         IMWRITE_PNG_STRATEGY_DEFAULT      = 0, //!< Use this value for normal da
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:183:36: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_FILTERED’
>      IMWRITE_PNG_STRATEGY_FILTERED =1,
>                                     ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:106:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_FILTERED’
>         IMWRITE_PNG_STRATEGY_FILTERED     = 1, //!< Use this value for data prod
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:184:40: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY’
>      IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY =2,
>                                         ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:107:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY’
>         IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY = 2, //!< Use this value to force Huff
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:185:31: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_RLE’
>      IMWRITE_PNG_STRATEGY_RLE =3,
>                                ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:108:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_RLE’
>         IMWRITE_PNG_STRATEGY_RLE          = 3, //!< Use this value to limit matc
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:186:33: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_FIXED’
>      IMWRITE_PNG_STRATEGY_FIXED =4,
>                                  ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:109:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_FIXED’
>         IMWRITE_PNG_STRATEGY_FIXED        = 4  //!< Using this value prevents th
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:187:25: error: redeclaration of ‘IMWRITE_PXM_BINARY’
>      IMWRITE_PXM_BINARY =32
>                          ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:91:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PXM_BINARY’
>         IMWRITE_PXM_BINARY          = 32, //!< For PPM, PGM, or PBM, it can be a
>         ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:190:62: error: default argument given for parameter 2 of ‘cv::Mat cv::imread(const string&, int)’
>  CV_EXPORTS_W Mat imread( const string& filename, int flags=1 );
>                                                               ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:166:18: note: previous specification in ‘cv::Mat cv::imread(const String&, int)’ here
>  CV_EXPORTS_W Mat imread( const String& filename, int flags = IMREAD_COLOR );
>                   ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:192:54: error: default argument given for parameter 3 of ‘bool cv::imwrite(const string&, cv::InputArray, const std::vector<int>&)’
>                const vector<int>& params=vector<int>());
>                                                       ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:239:19: note: previous specification in ‘bool cv::imwrite(const String&, cv::InputArray, const std::vector<int>&)’ here
>  CV_EXPORTS_W bool imwrite( const String& filename, InputArray img,
>                    ^
> In file included from /usr/local/include/opencv2/highgui.hpp:43:0,
>                  from phoebe.cpp:4:
> /usr/local/include/opencv2/highgui/highgui.hpp:197:68: error: default argument given for parameter 4 of ‘bool cv::imencode(const string&, cv::InputArray, std::vector<unsigned char>&, const std::vector<int>&)’
>                              const vector<int>& params=vector<int>());
>                                                                     ^
> In file included from phoebe.cpp:3:0:
> /usr/local/include/opencv2/imgcodecs.hpp:273:19: note: previous specification in ‘bool cv::imencode(const String&, cv::InputArray, std::vector<unsigned char>&, const std::vector<int>&)’ here
>  CV_EXPORTS_W bool imencode( const String& ext, InputArray img,
>                    ^

Now, I think that the error could be a conflict between the two OpenCV versions that I have on my computer (the first is just OpenCV, the second is OpenCV-2.4.13.5); but I am not sure that this is the real problem, and actually in this case I dont' know how to remove the first version without creating other problems;
Do you have any suggestions?
Thanks a lot!

**Comment by alalek** [comment]
You have mess with different OpenCV versions.
They can't be installed into the same location (`/usrlocal`) or without forced version mangling (see `INSTALL_TO_MANGLED_PATHS`). You can use `CMAKE_INSTALL_PREFIX`:
- `cmake -DCMAKE_INSTALL_PREFIX=/opt/opencv-2.4 ...`
- `cmake -DCMAKE_INSTALL_PREFIX=/opt/opencv-3.4 ...`

For building samples don't use `gcc` directly. Consider using of CMake for that - [demo](https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake).

At first, you should properly remove your existed installations.
It is not a trivial task if installations have been done via `sudo make install` - you need original build directories with saved `install_manifest.txt` files or remove files carefully.

---

For experiments it is better to build samples/tutirial with OpenCV binaries from sources directly:
```
mkdir opencv_build
cd opencv_build
cmake -DBUILD_EXAMPLES=ON <opencv_src_dir>
make example_tutorial_display_image -j5
./bin/example_tutorial_display_image <opencv_src_dir>/samples/data/HappyFish.jpg
```


---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by ChewbEp** [comment]
Thank you, I have specified the OpenCV version that I wanted to use during the compiling step, and it worked perfectly!!

**Comment by Alex-Beh** [comment]
@ChewbEp How you specific your opencv version? Thanks in advance.

**Comment by Alex-Beh** [comment]
@ChewbEp May I know how to specific opencv version in CMakeLists.txt? I have opencv and opencv2 under /usr/local/include..
