### ISSUE TITLE
How i am install OpenCV 4 and how to link with gcc compiler ?

### ISSUE THREAD

**Issue by HelloWar75** [opencv/opencv#14481]
Hello, i am need help with how to install opencv 4.0~ and how to link the library with gcc, i am use codeblocks as IDE, but all examples in documentation, be installation or use, not show how to link with the new version, and do not show how to install with version 4.0~.

Have a tutorial for install and use this version, i want use with C++.

**Comment by dkurt** [comment]
Please use a forum for usage questions: https://answers.opencv.org.

This is a tracker for bugs or feature requests.
