### ISSUE TITLE
tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: image_batch in function 'connect

### ISSUE THREAD

**Issue by jaiatncson7** [opencv/opencv#14496]
Hi, May i know how to fix this issue? I am getting this error when i load facenet model as below,
detector = cv2.dnn.readNetFromTensorflow(20180402-114759.pb)

Traceback (most recent call last):
File "extract_embeddings.py", line 37, in 
detector = cv2.dnn.readNetFromTensorflow(ts_modelPath)
cv2.error: OpenCV(4.1.0-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: image_batch in function 'connect'

can you please tell me how to fix it?

My system env:
Ubuntu 18.04
Installed Openvino toolkit to use NCS2 stick
Python & OpenCV:
$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.0-openvino'
>>>

**Comment by alalek** [comment]
Link to the model is required.

**Comment by jaiatncson7** [comment]
20180402-114759.pb is the model file and i already using this model as: cv2.dnn.readNetFromTensorflow(20180402-114759.pb)

**Comment by jaiatncson7** [comment]
Reproduce:
Just download the facenet model from https://github.com/davidsandberg/facenet and run the below code,

import cv2
detector = cv2.dnn.readNetFromTensorflow(20180402-114759.pb)

**Comment by dkurt** [comment]
Please try to turn your model into testing phase before creation a `.pb` file:
![image](https://user-images.githubusercontent.com/25801568/58193740-5c95bb00-7ccc-11e9-99d9-7ac6ab3af4df.png)

**Comment by dkurt** [comment]
@jaiatncson7, Have you solved the error? Can we close an issue?

**Comment by jaiatncson7** [comment]
Hi @dkurt , this is related to issue https://github.com/opencv/opencv/issues/14497. and you have helped me to fix. Thank you so much. 

But i want to ask one more thing, Did anyone try to run facenet on NCS2 stick? Is there any sample application/code?

**Comment by dkurt** [comment]
@jaiatncson7, Please try to use a forum: https://answers.opencv.org

**Comment by TrungDinhT** [comment]
Sorry for hijacking to this thread, but I'm having the same issue. 
@dkurt could you explain to me what you meant by "turn your model into testing phase before creation a .pb file"? I set phase_train to False but I still got the same issue. Apparently, the error was not there, it relates to image_batch instead. But I don't know how to do as you said.
@jaiatncson7 In fact, you mentioned an optimized model for facenet using openvino in issue #14497. So, were you able to solve the problem before optimizing model with openvino? How did you do that?

**Comment by jaiatncson7** [comment]
I have confirmed with Intel that NCS2 doesn't support Inception Resnet V1 architecture used by facenet. So, there is no way to proceed with facenet code on NCS2.

**Comment by dkurt** [comment]
Please attach the mentioned model so we can reproduce it.

**Comment by TrungDinhT** [comment]
I got the model (20180402-114759) from this github: https://github.com/davidsandberg/facenet. 
The zip file of model is too big to attach, so here is the link to download it: https://drive.google.com/file/d/1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-/view

**Comment by dkurt** [comment]
@TrungDinhT, This model also contains a lot of training only nodes. Please try to remove it.

**Comment by dkurt** [comment]
@jaiatncson7, Please add a reference to model with the problem with NCS.

**Comment by jaiatncson7** [comment]
Hi, 
As they mentioned in the below ncs forum, NCS2 stick doesn't support inception resnet v1 architecture which is facenet model. So, right now we can use NCS2 with facenet model.

**Comment by dkurt** [comment]
@jaiatncson7, OpenCV uses Intel's Inference Engine to run networks on NCS2. So it could be supported through OpenCV. However we need the model to check it. Please upload it somewhere.

**Comment by dkurt** [comment]
I have to close it and mute due no support with problem investigation. Feel free to open a new issue providing all the details to reproduce the problem.
