### ISSUE TITLE
VideoCapture set manual exposure not working

### ISSUE THREAD

**Issue by hez2010** [opencv/opencv#14494]
##### System information (version)
- OpenCV => both 4.0.1 and 4.1.0
- Operating System / Platform => Ubuntu 16.04 x64
- Compiler => g++ 5

##### Detailed description

I followed the solution in https://github.com/opencv/opencv/issues/9738: I set AutoExposure to 0.25 first but found that the solution no longer works. 
I cannot disable AutoExposure and setting Exposure property didn't change anything. 

##### Steps to reproduce

```python
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25)
cap.set(cv2.CAP_PROP_EXPOSURE, -7.0)

while True:
	ret, frame = cap.read()
	cv2.imshow('test', frame)
	cv2.waitKey(1)
```

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

---

> cap.set(...)

Always check returned values.

---

Properties availability/implementation/etc are backend-specific. So it is bad idea to use them without backend check.
To use V4L2 properties you should force backend via `CAP_V4L2` parameter.
