### ISSUE TITLE
CUDA_nppi_LIBRARY (ADVANCED)

### ISSUE THREAD

**Issue by test4fest** [opencv/opencv#14502]
I have 2 different python version and cuda9.0 and cuda 9.2
For a project I need to install opencv 2.4.9 on python2.7.
I had already installed opencv version 3. Right now uninstalled it.

But I get the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nppi_LIBRARY (ADVANCED)
linked by target "opencv_test_core" in directory /home/username/opencv-2.4.9/modules/core
linked by target "opencv_core" in directory /home/username/opencv-2.4.9/modules/core
linked by target "opencv_core" in directory /home/username/opencv-2.4.9/modules/core
linked by target "opencv_perf_core" in directory /home/username/opencv-2.4.9/modules/core
linked by target "opencv_flann" in directory /home/username/opencv-2.4.9/modules/flann
linked by target "opencv_test_flann" in directory /home/username/opencv-2.4.9/modules/flann
linked by target "opencv_test_imgproc" in directory /home/username/opencv-2.4.9/modules/imgproc
linked by target "opencv_imgproc" in directory /home/username/opencv-2.4.9/modules/imgproc
linked by target "opencv_perf_imgproc" in directory /home/username/opencv-2.4.9/modules/imgproc
linked by target "opencv_test_highgui" in directory /home/username/opencv-2.4.9/modules/highgui
linked by target "opencv_perf_highgui" in directory /home/username/opencv-2.4.9/modules/highgui
linked by target "opencv_highgui" in directory /home/username/opencv-2.4.9/modules/highgui
linked by target "opencv_features2d" in directory /home/username/opencv-2.4.9/modules/features2d
linked by target "opencv_perf_features2d" in directory /home/username/opencv-2.4.9/modules/features2d
linked by target "opencv_test_features2d" in directory /home/username/opencv-2.4.9/modules/features2d
linked by target "opencv_calib3d" in directory /home/username/opencv-2.4.9/modules/calib3d
linked by target "opencv_test_calib3d" in directory /home/username/opencv-2.4.9/modules/calib3d
linked by target "opencv_perf_calib3d" in directory /home/username/opencv-2.4.9/modules/calib3d
linked by target "opencv_test_ml" in directory /home/username/opencv-2.4.9/modules/ml
linked by target "opencv_ml" in directory /home/username/opencv-2.4.9/modules/ml
linked by target "opencv_test_video" in directory /home/username/opencv-2.4.9/modules/video
linked by target "opencv_perf_video" in directory /home/username/opencv-2.4.9/modules/video
linked by target "opencv_video" in directory /home/username/opencv-2.4.9/modules/video
linked by target "opencv_legacy" in directory /home/username/opencv-2.4.9/modules/legacy
linked by target "opencv_test_legacy" in directory /home/username/opencv-2.4.9/modules/legacy
linked by target "opencv_test_objdetect" in directory /home/username/opencv-2.4.9/modules/objdetect
linked by target "opencv_perf_objdetect" in directory /home/username/opencv-2.4.9/modules/objdetect
linked by target "opencv_objdetect" in directory /home/username/opencv-2.4.9/modules/objdetect
linked by target "opencv_test_photo" in directory /home/username/opencv-2.4.9/modules/photo
linked by target "opencv_photo" in directory /home/username/opencv-2.4.9/modules/photo
linked by target "opencv_perf_photo" in directory /home/username/opencv-2.4.9/modules/photo
linked by target "opencv_gpu" in directory /home/username/opencv-2.4.9/modules/gpu
linked by target "opencv_gpu" in directory /home/username/opencv-2.4.9/modules/gpu
linked by target "opencv_perf_gpu" in directory /home/username/opencv-2.4.9/modules/gpu
linked by target "opencv_test_gpu" in directory /home/username/opencv-2.4.9/modules/gpu
linked by target "gpu_perf4au" in directory /home/username/opencv-2.4.9/modules/gpu/perf4au
linked by target "opencv_test_ocl" in directory /home/username/opencv-2.4.9/modules/ocl
linked by target "opencv_perf_ocl" in directory /home/username/opencv-2.4.9/modules/ocl
linked by target "opencv_ocl" in directory /home/username/opencv-2.4.9/modules/ocl
linked by target "opencv_perf_nonfree" in directory /home/username/opencv-2.4.9/modules/nonfree
linked by target "opencv_nonfree" in directory /home/username/opencv-2.4.9/modules/nonfree
linked by target "opencv_test_nonfree" in directory /home/username/opencv-2.4.9/modules/nonfree
linked by target "opencv_test_contrib" in directory /home/username/opencv-2.4.9/modules/contrib
linked by target "opencv_contrib" in directory /home/username/opencv-2.4.9/modules/contrib
linked by target "opencv_test_stitching" in directory /home/username/opencv-2.4.9/modules/stitching
linked by target "opencv_stitching" in directory /home/username/opencv-2.4.9/modules/stitching
linked by target "opencv_perf_stitching" in directory /home/username/opencv-2.4.9/modules/stitching
linked by target "opencv_perf_superres" in directory /home/username/opencv-2.4.9/modules/superres
linked by target "opencv_superres" in directory /home/username/opencv-2.4.9/modules/superres
linked by target "opencv_test_superres" in directory /home/username/opencv-2.4.9/modules/superres
linked by target "opencv_ts" in directory /home/username/opencv-2.4.9/modules/ts
linked by target "opencv_videostab" in directory /home/username/opencv-2.4.9/modules/videostab
linked by target "opencv_haartraining" in directory /home/username/opencv-2.4.9/apps/haartraining
linked by target "opencv_haartraining_engine" in directory /home/username/opencv-2.4.9/apps/haartraining
linked by target "opencv_createsamples" in directory /home/username/opencv-2.4.9/apps/haartraining
linked by target "opencv_performance" in directory /home/username/opencv-2.4.9/apps/haartraining
linked by target "opencv_traincascade" in directory /home/username/opencv-2.4.9/apps/traincascade
linked by target "example_polar_transforms" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_motempl" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_morphology" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_fback_c" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_find_obj" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_blobtrack_sample" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_adaptiveskindetector" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_facedetect" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_latentsvmdetect" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_find_obj_calonder" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_bgfg_codebook" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_find_obj_ferns" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_mser_sample" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_pyramid_segmentation" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_contours" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_mushroom" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_one_way_sample" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_smiledetect" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_tree_engine" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_convert_cascade" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_delaunay" in directory /home/username/opencv-2.4.9/samples/c
linked by target "example_videostab" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_video_homography" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_tvl1_optical_flow" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_objectDetection" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_non_linear_svms" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_introduction_windows_vs" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_display_image" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_gpu-basics-similarity" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_SURF_detector" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_SURF_Homography" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_SURF_FlannMatcher" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Drawing_2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_camera_calibration" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_goodFeaturesToTrack_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_cornerHarris_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_watershed" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_pointPolygonTest_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_generalContours_demo2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_generalContours_demo1" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_findContours_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Sobel_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Laplace_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Geometric_Transforms_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Pyramids" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Morphology_1" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_compareHist_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_mat_the_basic_image_container" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Threshold" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_calcHist_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_calcBackProject_Demo2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_calcBackProject_Demo1" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_EqualizeHist_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_video-write" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_filter2D_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_generic_descriptor_match" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_freak_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_moments_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_filestorage" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_SURF_descriptor" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_bagofwords_classification" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_convexhull" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Morphology_2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_openni_capture" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Smoothing" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_minarea" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Remap_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_phase_corr" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_objectDetection2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_distrans" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_delaunay2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_cornerDetector_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_dft" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_segment_objects" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_detector_descriptor_evaluation" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_fitellipse" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_file_input_output" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_CannyDetector_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_hybridtrackingsample" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_descriptor_extractor_matcher" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_demhist" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_bgfg_segm" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_letter_recog" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_kmeans" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_Drawing_1" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_detector_descriptor_matcher_evaluation" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_hull_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_MatchTemplate_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_edge" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_how_to_scan_images" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_bgfg_gmg" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_drawing" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_image" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_OpenEXRimages_HDR_Retina_toneMapping_video" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_laplace" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_points_classifier" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_detection_based_tracker_sample" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_3calibration" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_em" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_build3dmodel" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_video_dmtx" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_OpenEXRimages_HDR_Retina_toneMapping" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_cout_mat" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_discrete_fourier_transform" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_calibration" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_HoughLines_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_morphology2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_brief_match_test" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_chamfer" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_fback" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_interoperability_with_OpenCV_1" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_cornerSubPix_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_select3dobj" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_calibration_artificial" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_HoughCircle_Demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_linemod" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_ffilldemo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_latentsvm_multidetect" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_contours2" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_imagelist_creator" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_rgbdodometry" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_camshiftdemo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_introduction_to_svm" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_starter_video" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_connected_components" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_image_sequence" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_meanshift_segmentation" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_grabcut" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_mat_mask_operations" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_houghlines" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_video-input-psnr-ssim" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_intelperc_capture" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_fabmap_sample" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_kalman" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_BasicLinearTransforms" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_logpolar_bsm" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_facerec_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_matcher_simple" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_stereo_calib" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_pca" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_retina_tutorial" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_peopledetect" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_SBM_Sample" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_BasicLinearTransformsTrackbar" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_opencv_version" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_retinaDemo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_houghcircles" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_simpleflow_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_inpaint" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_squares" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_matching_to_many_images" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_starter_imagelist" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_copyMakeBorder_demo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_stitching_detailed" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_AddingImages" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_lkdemo" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_stereo_match" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "tutorial_AddingImagesTrackbar" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_gencolors" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_stitching" in directory /home/username/opencv-2.4.9/samples/cpp
linked by target "example_gpu_video_writer" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_surf_keypoint_matcher" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_super_resolution" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_stereo_multi" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_pyrlk_optical_flow" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_cascadeclassifier_nvidia_api" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_farneback_optical_flow" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_driver_api_multi" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_brox_optical_flow" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_stereo_match" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_alpha_comp" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_cascadeclassifier" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_bgfg_segm" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_driver_api_stereo_multi" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_morphology" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_optical_flow" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_opticalflow_nvidia_api" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_hog" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_performance" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_video_reader" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_opengl" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_generalized_hough" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_houghlines" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_gpu_multi" in directory /home/username/opencv-2.4.9/samples/gpu
linked by target "example_ocl_pyrlk_optical_flow" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_hog" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_clahe" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_adaptive_bilateral_filter" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_bgfg_segm" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_facedetect" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_squares" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_stereo_match" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_surf_matcher" in directory /home/username/opencv-2.4.9/samples/ocl
linked by target "example_ocl_tvl1_optical_flow" in directory /home/username/opencv-2.4.9/samples/ocl

-- Configuring incomplete, errors occurred!
See also "/home/username/opencv-2.4.9/build/CMakeFiles/CMakeOutput.log".
See also "/home/username/opencv-2.4.9/build/CMakeFiles/CMakeError.log".

**Comment by alalek** [comment]
> OpenCV 2.4.9
> cuda9.0

Incompatible versions.
You trying to use dependencies released after OpenCV.

---

Read issue template at first!
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
