### ISSUE TITLE
Mask rcnn model using OpenVINO is not accurate

### ISSUE THREAD

**Issue by stq054188** [opencv/opencv#14509]
**##### System information (version)**
OpenCV => 4.1.0
Operating System / Platform => Windows10 64 Bit
Compiler => Visual Studio 2017
OpenVINO => w_openvino_toolkit_p_2018.5.456

**##### Detailed description**
I have trained a mask rcnn model with tensorflow and I used openvino to accelerate it. But I found the
result with using  parameter DNN_BACKEND_OPENCV is more accurate than using DNN_BACKEND_INFERENCE_ENGINE.

**##### Steps to reproduce**
1. Test code is OpenCV_Mask_RCNN.cpp, test images are 2.png and 7.png. All files are packed as files.zip. 
[files.zip](https://github.com/opencv/opencv/files/3155237/files.zip)
2. Model files and config files are here. https://drive.google.com/open?id=1xTI6_bqbZpi3vbeVcFxX1emBSa7QI58z
3. Here is my test result.
**DNN_BACKEND_INFERENCE_ENGINE result**
![Q1](https://user-images.githubusercontent.com/15775782/57346503-56a6c280-7181-11e9-81eb-f85ff0e25434.JPG)

**DNN_BACKEND_OPENCV result**
![Q2](https://user-images.githubusercontent.com/15775782/57346524-68886580-7181-11e9-909f-7b82c9aae9d1.JPG)

4. I also test faster rcnn model，both of DNN_BACKEND_OPENCV  and DNN_BACKEND_INFERENCE_ENGINE result are same. With mask rcnn model seems bounding rects are same but masks are different. @dkurt This looks like a real bug.

**Comment by alalek** [comment]
Avoid creation of issues for similar problems: #14480

> w_openvino_toolkit_p_2018.5.456

This package is not fresh. Try latest release 2019R1 at first.

**Comment by stq054188** [comment]
@alalek  @dkurt dkurt  Although I changed the version to 2019_R1.01, the results did not improve.

**Comment by stq054188** [comment]
Has someone encountered a similar situation?

**Comment by Bleach665** [comment]
The same problem. Win10, OpenCV rev. af19023e4ab580083873b6871f59e240b41ef52e, OpenVINO 2019.3.379.
Model: mask_rcnn_inception_v2_coco_2018_01_28.
OpenCV backend, CPU target:
![a1](https://user-images.githubusercontent.com/6595124/74598155-ef556180-5074-11ea-9d46-4f8e6f18f6ec.png)
Inference engine backend, CPU target: 0 object detected.

**Comment by Bleach665** [comment]
@dkurt. A small addition: I use PC's with old CPU which not support AVX instruction set. Maybe that matters.

**Comment by dkurt** [comment]
@Bleach665, probably not. I can reproduce the problem on different CPU. The thing is that it can compute masks and boxes separately but the problem appears if we return both of them. Let me try to find a workaround or fix that.

**Comment by dkurt** [comment]
@Bleach665, May I ask you to open a `.pbtxt` file and try to apply this changes?
```patch
@@ -5926,7 +5926,7 @@ node {
   input: "variance_encoded"
 }
 node {
-  name: "detection_out_final"
+  name: "detection_out_final/real"
   op: "DetectionOutput"
   input: "variance_encoded/flatten"
   input: "SecondStageBoxPredictor/Reshape_1/Reshape"
@@ -5992,11 +5992,35 @@ node {
     }
   }
 }
+node {
+  name: "one"
+  op: "Const"
+  attr {
+    key: "value"
+    value {
+      tensor {
+        dtype: DT_FLOAT
+        tensor_shape {
+          dim {
+            size: 1
+          }
+        }
+        float_val: 1.0
+      }
+    }
+  }
+}
+node {
+  name: "detection_out_final"
+  op: "Mul"
+  input: "detection_out_final/real"
+  input: "one"
+}
 node {
   name: "CropAndResize_1"
   op: "CropAndResize"
   input: "FirstStageFeatureExtractor/InceptionV2/InceptionV2/Mixed_4e/concat"
-  input: "detection_out_final"
+  input: "detection_out_final/real"
   input: "CropAndResize_1/crop_size"
   attr {
     key: "extrapolation_value"
```
and try to run with IE backend?

**Comment by Bleach665** [comment]
@dkurt , works great with these changes. The result is the same as when used CUDA or OpenCV backends.
The result with the changes above and inference engine backend:
![1112](https://user-images.githubusercontent.com/6595124/74608928-f5d3ef80-50ed-11ea-895b-77a7bda25c0d.png)

**Comment by dkurt** [comment]
@Bleach665, great. thanks! Based on this experiment we will propose a patch so old version of `.pbtxt` will also work.

**Comment by dkurt** [comment]
@stq054188, sorry for late solution, but here it is: https://github.com/opencv/opencv/pull/16595. I was not able to download your model but at least with @Bleach665's image we achieve exact outputs.

BTW, for now OpenCV can work with two APIs of Inference Engine: legacy DNNBuilder and nGraph API. With nGraph API we can achieve monolithic model (all the layers are executed by IE) that means the model can work faster and even go to accelerators (i.e. Myriad NCS2).

**Comment by zpmmehrdad** [comment]
@stq054188 Hi,

How did you convert yours .h5 to .pb? I'm going to use C++ API.

Thanks
