### ISSUE TITLE
readNetFromTorch cannot load the model from sample (opencv4.1)

### ISSUE THREAD

**Issue by lunasdejavu** [opencv/opencv#14510]
##### System information (version)

- OpenCV =>4.1
- Operating System / Platform => Windows 64 Bit
- python 3.7.3
-pytorch 

##### Detailed description

I used the sample code from [here](https://github.com/opencv/opencv/blob/3.4.0/samples/dnn/fast_neural_style.py)
 followed the step and downloaded the model from  [here](https://github.com/jcjohnson/fast-neural-style)
then I chose the model starry_night.t7
run something like 
(base) C:\Users\willy_sung\Documents>python test_torch.py --input C:/Users/willy_sung/Downloads/751118.jpg --model C:\\fast-neural-style\\models\\models\\eccv16\\starry_night.t7

but the error showed up :
cv2.error: OpenCV(4.1.0) D:\Build\OpenCV\opencv-4.1.0\modules\dnn\src\torch\torch_importer.cpp:1022: error: (-213:The function/feature is not implemented) Unsu
pported Lua type in function 'cv::dnn::dnn4_v20190122::TorchImporter::readObject'

**Comment by dkurt** [comment]
Please check that your file is valid. Check it's size on disk.

**Comment by lunasdejavu** [comment]
@dkurt  thanks! I will close it now.
