### ISSUE TITLE
Master Build fails gtk2 Opengl

### ISSUE THREAD

**Issue by wehnersteffensielaff** [opencv/opencv#14522]
##### System information (version)
OpenCV => master/4.1.0
Operating System / Platform => Ubuntu 19.04
Compiler => gcc 8.3
Cmake => 3.12.1 installed using homebrew

##### Detailed description

after Pulling on branch master build fails in Module highgui complaining that "gtk/gtkgl.h" is missing. When trying to compile with OpenGL . While tag "4.1.0" builds with this configuration

error:
{OpenCVCheckoutDir}/opencv/modules/highgui/src/window_gtk.cpp:62:14: fatal error: gtk/gtkgl.h: No such file or directory
     #include <gtk/gtkgl.h>
              ^~~~~~~~~~~~~
compilation terminated.

the configuration commandline used:

cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
-DOPENCV_GENERATE_PKGCONFIG=ON -DWITH_OPENGL=ON -DBUILD_TBB=ON -DWITH_TBB=ON ..

which results in cmake output of:
[cmakeOutput.txt](https://github.com/opencv/opencv/files/3161307/cmakeOutput.txt)
output of make is:
[makeOutput.txt](https://github.com/opencv/opencv/files/3161316/makeOutput.txt)

##### Steps to reproduce

cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
-DOPENCV_GENERATE_PKGCONFIG=ON -DWITH_OPENGL=ON -DBUILD_TBB=ON -DWITH_TBB=ON ..

make

**Comment by mshabunin** [comment]
Try to add `-DOpenGL_GL_PREFERENCE=LEGACY` cmake option.

**Comment by wehnersteffensielaff** [comment]
Thank you for this hint. I tried that but the Issue persisted. And I haven´t invested this further

**Comment by mshabunin** [comment]
@wehnersteffensielaff , please check this patch: #14610
