### ISSUE TITLE
Feature request, FloodFill on opencv.js

### ISSUE THREAD

**Issue by Makogan** [opencv/opencv#14525]
FloodFill is not currently available in OpenCV.js, it would be nice to expose at least some of its functionality.

Someone has suggested a way to do it: https://answers.opencv.org/question/195457/floodfill-missing-in-opencvjs/

I didn't get it to work however. All modifications I did to the source code failed to compile.

**Comment by thangktran** [comment]
i'm working on this issue.

**Comment by Makogan** [comment]
Thank you so much, I am updating and will try it out.

**Comment by thangktran** [comment]
> Thank you so much, I am updating and will try it out.

sure. please let me know if there's any issue.

**Comment by Makogan** [comment]
Hmm, I downloaded the latest version of opencv (git pull), rebuilt the js script through:

`python ./platforms/js/build_js.py build_js`

However wehn I try to use the function in js I get:

` cv.floodfill is not a function`

I tried:

cv.floodFill(/* parameters */)

**Comment by thangktran** [comment]
@Makogan oh the fix is not merged yet to the upstream. You need to clone [my branch] (https://github.com/thangktran/opencv/tree/thangktran/feature/floodFill-on-opencv.js) for that.

**Comment by dmandrioli** [comment]
It works as expected at least for filling an RGB image with zero tolerance:
```
        const mask = new cv.Mat(img.rows + 2, img.cols + 2, cv.CV_8U, [0, 0, 0, 0])
        const rect = {};
        cv.floodFill(
            img,
            mask,
            {x: col, y: row},
            [255, 128, 0, 255],
            rect,
            [0, 0, 0, 0],
            [0, 0, 0, 0],
            4 | (255 << 8));
        console.log("Flood area", rect);
```

Thanks a lot!

**Comment by Makogan** [comment]
I tried calling it with 3 arguments, image source, point, fill color, I got an incorrect number of arguments error.

What should the correct number of parameters be?

**Comment by dmandrioli** [comment]
@Makogan Hum, 7 arguments? :) It will work also with 6 arguments.
https://docs.opencv.org/4.1.0/d7/d1b/group__imgproc__misc.html#ga366aae45a6c1289b341d140839f18717

**Comment by thangktran** [comment]
> I tried calling it with 3 arguments, image source, point, fill color, I got an incorrect number of arguments error.
> 
> What should the correct number of parameters be?

@Makogan the number of parameters must be at least 4. Please refer to the documentation.
