### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by TFDeeplearner** [opencv/opencv#14528]
[ 15%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking_pch_dephelp.dir/opencv_tracking_pch_dephelp.cxx.o
[ 15%] Linking CXX static library ../../lib/libopencv_perf_optflow_pch_dephelp.a
[ 15%] Building CXX object modules/tracking/CMakeFiles/opencv_test_tracking_pch_dephelp.dir/opencv_test_tracking_pch_dephelp.cxx.o
[ 15%] Built target opencv_perf_optflow_pch_dephelp
Scanning dependencies of target opencv_perf_tracking_pch_dephelp
[ 15%] Building CXX object modules/tracking/CMakeFiles/opencv_perf_tracking_pch_dephelp.dir/opencv_perf_tracking_pch_dephelp.cxx.o
modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/build.make:62: recipe for target 'modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/opencv_stitching_pch_dephelp.cxx.o' failed
make[2]: *** [modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/opencv_stitching_pch_dephelp.cxx.o] Error 1
CMakeFiles/Makefile2:26438: recipe for target 'modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/all' failed
make[1]: *** [modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 15%] Linking CXX static library ../../lib/libopencv_optflow_pch_dephelp.a
[ 15%] Built target opencv_optflow_pch_dephelp
[ 15%] Linking CXX static library ../../lib/libopencv_test_superres_pch_dephelp.a
[ 15%] Linking CXX static library ../../lib/libopencv_superres_pch_dephelp.a
[ 15%] Built target opencv_test_superres_pch_dephelp
[ 15%] Built target opencv_superres_pch_dephelp
[ 15%] Linking CXX static library ../../lib/libopencv_perf_superres_pch_dephelp.a
[ 15%] Built target opencv_perf_superres_pch_dephelp
[ 16%] Linking CXX static library ../../lib/libopencv_test_tracking_pch_dephelp.a
[ 16%] Linking CXX static library ../../lib/libopencv_tracking_pch_dephelp.a
[ 16%] Built target opencv_test_tracking_pch_dephelp
[ 16%] Built target opencv_tracking_pch_dephelp
[ 16%] Linking CXX static library ../../lib/libopencv_perf_tracking_pch_dephelp.a
[ 16%] Built target opencv_perf_tracking_pch_dephelp
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dkurt** [comment]
We cannot help with your problems unless you specified the steps to reproduce it.
