### ISSUE TITLE
TypeError: VideoCapture() takes no arguments

### ISSUE THREAD

**Issue by suyellazzmin** [opencv/opencv#14532]
hi. im running deepgaze source code for background subtractor comparison. 
im using python 3.7 with pycharm IDE. and using opencv4.0. 

import cv2
import numpy as np

# Video Capture
capture = cv2.VideoCapture("demo.mov")

# Subtractors
mogSubtractor = cv2.bgsegm.createBackgroundSubtractorMOG(300)
mog2Subtractor = cv2.createBackgroundSubtractorMOG2(300, 400, True)
gmgSubtractor = cv2.bgsegm.createBackgroundSubtractorGMG(10, .8)
knnSubtractor = cv2.createBackgroundSubtractorKNN(100, 400, True)
cntSubtractor = cv2.bgsegm.createBackgroundSubtractorCNT(5, True)

# Keeps track of what frame we're on
frameCount = 0

this is part of the source code and follow is the error.
 File "C:/Users/user/Documents/Python/Background-Subtractor-Comparisons-master/main.py", line 5, in <module>
    capture = cv2.VideoCapture("demo.mov")
TypeError: VideoCapture() takes no arguments

can anyone help me. im new to this

**Comment by abhilb** [comment]
I tried the attached code and it is working 

[14532.zip](https://github.com/opencv/opencv/files/3168594/14532.zip)

**Comment by suyellazzmin** [comment]
but it still cant run even with your source code.

**Comment by suyellazzmin** [comment]
i got it right.

**Comment by saran-kumar-sk** [comment]
Hello!!
I tried this video capture in python 3.11.1 and open cv2 4.7.0 

I got an error Like this TypeError: VideoCapture() takes no arguments
