### ISSUE TITLE
setLogLevel

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#14535]
How to use 'setLogLevel' in python3?
opencv3.4.1

**Comment by alalek** [comment]
Currently this API is experimental and it is not exposed into Python.
You can try to set `OPENCV_LOG_LEVEL=INFO` environment variable before loading of OpenCV binaries.

What kind of messages do you want to turn off?

**Comment by zihaozhang9** [comment]
> 目前这个API是实验性的，它不会暴露给Python。
> 您可以`OPENCV_LOG_LEVEL=INFO`在加载OpenCV二进制文件之前尝试设置环境变量。
> 
> 你想关闭什么样的消息？

[ INFO:0] Initialize OpenCL runtime...

**Comment by alalek** [comment]
In modern OpenCV: "INFO" is for Debug builds only. In release builds "WARNING" is threshold level.
Or use: `OPENCV_LOG_LEVEL=WARN`.
