### ISSUE TITLE
boxes, masks = net.forward(['detection_out_final', 'detection_masks']) crashes with matrix.cpp:541: error: (-215:Assertion failed)

### ISSUE THREAD

**Issue by ConsMe** [opencv/opencv#14530]
Opencv 4.1.0
Ubuntu 18.04

Hello, 
According to [opencv tensorflow object detection api](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) I run segmentation with trained Mask-RCNN Inception v2 model. Mainly it works well, but with about 15% images I get the error:
boxes, masks = net.forward(['detection_out_final', 'detection_masks'])
cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/matrix.cpp:541: error: (-215:Assertion failed) r == Range::all() || (0 <= r.start && r.start < r.end && r.end <= m.size[i]) in function 'Mat'
At the same time if I try these images with original [tensorflow object detection api](https://github.com/tensorflow/models/tree/master/research/object_detection) it works well, so I conclude it's not because of corrupted images or model mistakes, but because of opencv error.
Can you help me please? 
Thank you in advance.

**Comment by alalek** [comment]
Provide complete minimal reproducer with included input images with issues.

**Comment by ConsMe** [comment]
Please check this example code with .pb and .pbtxt - [https://yadi.sk/d/I8xDeLPQ4-4DEw](https://yadi.sk/d/I8xDeLPQ4-4DEw)
To get right result please run python mask_rcnn.py --input https://ayamama.ru/wp-content/uploads/2017/06/snils.jpg --model frozen_inference_graph.pb --config graphcv.pbtxt --width 500 --height 500
To get error run python3 mask_rcnn.py --input https://pensioved.ru/wp-content/uploads/2018/02/1-7.jpg --model frozen_inference_graph.pb --config graphcv.pbtxt --width 500 --height 500
Thank you

**Comment by ConsMe** [comment]
@alalek , will you help me?

**Comment by dkurt** [comment]
The problem looks like one described in https://github.com/opencv/opencv/pull/14459. Inner `DetectionOutput` produces varying size output. Please try the following workaround:

replace
```cpp
int outputShape[] = {1, 1, (int)numKept, 7};
outputs[0].create(4, outputShape, CV_32F);
```

to

```cpp
outputs[0].setTo(0);
```

in https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/detection_output_layer.cpp

We just need to decide if we fix `DetectionOutput` layer so it'll produce fixed output shape every time or we'll replace Mask R-CNN's inner `DetectionOutput` to `Proposal` layer (originally introduced in Faster R-CNN family). Or both variants :smile:

**Comment by dkurt** [comment]
@ConsMe, Please try the changes from https://github.com/opencv/opencv/pull/14552

This is result from TensorFlow:

![tf](https://user-images.githubusercontent.com/25801568/57694448-5e200d00-7654-11e9-9337-b6bdf94a319c.jpg)

and with [mask_rcnn.py](https://github.com/opencv/opencv/blob/master/samples/dnn/mask_rcnn.py) sample:
```bash
python mask_rcnn.py --input 1-7.jpg --model frozen_inference_graph.pb --config graphcv.pbtxt --width 500 --height 500 --thr 0.6
```

Please note that I had to replace a `swapRB` flag to `False` (perhaps the training was different for your model)

```python
blob = cv.dnn.blobFromImage(frame, size=(args.width, args.height), swapRB=False, crop=False)
```
![cv](https://user-images.githubusercontent.com/25801568/57694442-5b251c80-7654-11e9-8eeb-f5e1dec8650c.jpg)

**Comment by ConsMe** [comment]
Hello @dkurt ,
Sorry for my backwardness, but how can I apply these changes for v.3.4 to my installed v.4.1.0?

**Comment by dkurt** [comment]
You need to rebuild OpenCV. After merge the changes will be ported to master branch as well.

**Comment by ConsMe** [comment]
Hello @dkurt 
I've rebuilt opencv and it works! Thank you.
But I have another question. The mask and bounding box that I get with opencv differs from the mask and box with tensorflow:
Original image:
![1-7_rotated](https://user-images.githubusercontent.com/25854942/57776926-59795880-7729-11e9-859b-5b63f076e1b1.jpg)
Detected with opencv:
![1-7_rotated_opencv](https://user-images.githubusercontent.com/25854942/57776968-6e55ec00-7729-11e9-8674-31ec8f6393d2.jpg)
Detected with tensorflow:
![1-7_rotated](https://user-images.githubusercontent.com/25854942/57776998-7a41ae00-7729-11e9-8935-66c8da3ecfe4.jpg)
Can it be somehow improved?
Thank you.

**Comment by dkurt** [comment]
@ConsMe, have you considered 

> Please note that I had to replace a swapRB flag to False (perhaps the training was different for your model)
?

**Comment by ConsMe** [comment]
> have you considered

@dkurt, yes, sure, I've got that result with swapRB = False

**Comment by dkurt** [comment]
Ok, let's reopen the issue so we won't lose it.

**Comment by dkurt** [comment]
This is my experiment:

Using the following script I get similar results in TensorFlow:

```python
import tensorflow as tf
import cv2 as cv
import numpy as np

img = cv.imread('test.jpg')
inp = cv.resize(img, dsize=(500, 500))
inp = inp.reshape(1, 500, 500, 3)


graph = 'frozen_inference_graph.pb'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Session() as sess:
    # Restore session
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

    tfOut = sess.run([sess.graph.get_tensor_by_name('num_detections:0'),
                      sess.graph.get_tensor_by_name('detection_scores:0'),
                      sess.graph.get_tensor_by_name('detection_boxes:0'),
                      sess.graph.get_tensor_by_name('detection_classes:0'),
                      sess.graph.get_tensor_by_name('detection_masks:0'),
                      sess.graph.get_tensor_by_name('Preprocessor/sub:0')
                      ],
                     feed_dict={'image_tensor:0': inp})

print tfOut[-1].shape

num = int(tfOut[0])
scores = tfOut[1] # 1xN
boxes = tfOut[2] # 1xNx4
classes = tfOut[3] # 1xN
masks = tfOut[4] # 1xNx15x15

color = np.array([0, 121, 255], dtype=np.uint8)

for i in range(num):
    score = float(scores[0, i])
    if score < 0.8:
        continue

    print 1

    box = boxes[0, i]
    ymin = int(img.shape[0] * box[0])
    xmin = int(img.shape[1] * box[1])
    ymax = int(img.shape[0] * box[2])
    xmax = int(img.shape[1] * box[3])

    classMask = masks[0, i]
    classMask = cv.resize(classMask, (xmax - xmin + 1, ymax - ymin + 1))
    mask = (classMask > 0.5)

    roi = img[ymin:ymax+1, xmin:xmax+1][mask]
    img[ymin:ymax+1, xmin:xmax+1][mask] = (0.7 * color + 0.3 * roi).astype(np.uint8)

cv.imwrite('tf.jpg', img)
```

![tf](https://user-images.githubusercontent.com/25801568/58154516-76a6ad80-7c7a-11e9-9ce3-ebef745dcbc9.jpg)

So please share the code you used to get target result.

**Comment by ConsMe** [comment]
Hello @dkurt 
I used this [code](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) form tensorflow object detection repo. I got the same result with your code example. So it's not a problem with opencv. We can close this issue. Thank you.

**Comment by ajinkya933** [comment]
this code is good
