### ISSUE TITLE
build_wasm: generator error

### ISSUE THREAD

**Issue by daubaris** [opencv/opencv#14536]
Hi, I am trying to bring face module to JS, so far unsuccessfully. 

I've added `js` in `opencv_contrib` `face` module `CMakeLists.txt` file, `face` namespace to `core_bindings.cpp` file and related `face` methods to `embindgen.py`. When running the build it outputs `Generator error: unable to resolve base face::Facemark for face_FacemarkKazemi`. 
I've looked at already merged PR's, like `aruco`, `dnn` module bindings but as they are not related it does not seem to help much.

Could anyone explain what this error stands for and what could be the possible issue?

**Comment by daubaris** [comment]
Nevermind, it seems that error occure'd because `.hpp` files were built not in order, e.g `face_alignment.hpp` was built before `facemark.hpp`.

**Comment by kavikode** [comment]
@daubaris hi how did you solve this problem as I'm going through the same thing? Thanks in advance for your help

**Comment by daubaris** [comment]
@kavikode Well if I remember correctly, as written above, the problem was that somehow the header files were compiling not in the correct order. Because of time pressure I took the easy path by renaming the header files (adding numbers to the filenames) in which they should compile. You should look into each face module file and see which include which and by what order it should compile, then rename them, e.g `facemark1.hpp`.

**Comment by kavikode** [comment]
Thank you. So facemark1.hpp will compile first before face_alignment.hpp because of alphabetic order ? For face_FacemarkKazemi do you remember what you did? Do you have the files on your github account? Really appreciated

**Comment by kavikode** [comment]
@daubaris I renamed the two files facemark1.hpp and facemark1.cpp. I did a clean build and still the same error message appears. I don't see any other files that need to be renamed and I still receive the same error message. Is there any thing that I'm missing? I'd really appreciate. This information will also help anybody in the future that needs to do the same. Thanks in advance for your help.

**Comment by daubaris** [comment]
@kavikode `facemark1.hpp` was just an example. I've just found the files, although it might be that I am missing something so take this with a grain of salt. Your best bet now is to go to `opencv_contrib/modules/face/include/opencv2/face` folder and to rename `facemark.hpp` to `afacemark.hpp` and `facemark_train.hpp` to `bfacemark_train.hpp` and try to compile. Dont forget to change the `#include` names. Good luck.

**Comment by kavikode** [comment]
Thank you so much @daubaris! It finally works! You are great!

Now, I'm getting an error now when using the detectMultiScale function using wasm. Did you have the same error?

**Comment by daubaris** [comment]
@kavikode what kind of error is it, can't really remember, but I think the cause of this error lays inside `opencv/modules/js/src/embindgen.py` file. You must add the functions you want to use into the configuration. So if you want to use `detectMultiScale` your `embindgen.py` file `objdetect` dictionary should look something like this (notice `detectMultiScale` function):

```
objdetect = {'': ['groupRectangles'],
             'HOGDescriptor': ['load', 'HOGDescriptor', 'getDefaultPeopleDetector', 'getDaimlerPeopleDetector', 'setSVMDetector', 'detectMultiScale'],
             'CascadeClassifier': ['load', 'detectMultiScale2', 'CascadeClassifier', 'detectMultiScale3', 'empty', 'detectMultiScale']}
```

**Comment by kavikode** [comment]
thank you! @daubaris it is working out well!

Now the challenge I get the following error: Uncaught TypeError: Cannot read property 'createFacemarkLBF' of undefined

I have the following?
    cv['onRuntimeInitialized']=()=>{
        // do all your work here
        let utils = new Utils('errorMessage');
        let faceCascadeFile = 'haarcascade_frontalface_alt2.xml';
        let faceCascade = new cv.CascadeClassifier();
        let src = cv.imread('imageSrc');
        let gray = new cv.Mat();
        cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY, 0);
        let faces = new cv.RectVector();
        let msize = new cv.Size(0, 0);
        console.log("face CascadeClassifier");
        utils.createFileFromUrl(faceCascadeFile, faceCascadeFile, () => {
            faceCascade.load(faceCascadeFile);
            faceCascade.detectMultiScale(gray, faces, 1.1, 3, 0, msize, msize);

            let facemark = new cv.face.createFacemarkLBF();
            console.log('yes cascade ready to load.');

        });
    };

Any ideas please?

**Comment by daubaris** [comment]
Well, I am not quite sure because I did not use `facemarks`. But I'm quite confident that the problem is that you did not add the functions you want to use to `embindgen.py` file. So what you can try is to add the functions to the previously mentioned `embindgen.py` file by adding `face` module functions. So it could start something like this:

```
face = {''}  # Functions goes inside
```
You should look how the class is structured from the documentation.

**Comment by kavikode** [comment]
Added the face module in the opencv/modules/js/src/embindgen.py

face = {'': ['createFacemarkLBF', 'createFacemarkAAM', 'createFacemarkKazemi', 'drawFacemarks'], 'Facemark': ['fit', 'loadModel'], 'FacemarkLBF': [], 'FacemarkAAM'': [], 'FacemarkKazemi': [], }

Do you remember how you built your code and how you called your functions in the face module? What functions did you call in the face module?

Thanks!

**Comment by daubaris** [comment]
Nope, I really don't have what you are looking for, sorry. You'll have to search and try on your own..

**Comment by svgorin** [comment]
> Thank you so much @daubaris! It finally works! You are great!
> 
> Now, I'm getting an error now when using the detectMultiScale function using wasm. Did you have the same error?

Hi, could you please publish your findings how to fix the error. Thank you in advance.
