### ISSUE TITLE
OpenCV using VS compilation issue

### ISSUE THREAD

**Issue by vic9527** [opencv/opencv#14546]
I want to confirm that the current and future versions of opencv4 will no longer support vs2013?

Will the opencv3 version always support vs2013?

Thanks answer.

**Comment by alalek** [comment]
No official support.
No official support for future versions of OpenCV 3.4.x.

---

We prefer to support two latest major MSVS versions only. Currently it is MSVS 2015/2017. MSVS 2019 is in plans.
