### ISSUE TITLE
Is there an error with cv::UMat?

### ISSUE THREAD

**Issue by vic9527** [opencv/opencv#14543]
When I wrote the program using cv::UMat, the following error occurred on several computers (mainly Ultrabook). 
![微信截图_20190514143908](https://user-images.githubusercontent.com/9958494/57677039-7eea6180-7658-11e9-8894-2215f7c6a6f3.png)

But, when I use cv::Mat, there is no problem, I guess it should be related to OpenCL. 

I want to know if the computer does not support OpenCL, even if you use cv::UMat should be equivalent to cv::Mat, why report an error? 

How do I know if this machine supports OpenCL or cv::UMat?

**Comment by alalek** [comment]
You need to fix OpenCL runtime installation on your machine.
Try `clinfo` tool for validation of OpenCL installations.

You can disable OpenCL in OpenCV via environment variable:
```
export OPENCV_OPENCL_RUNTIME=disabled
```

**Comment by vic9527** [comment]
> You need to fix OpenCL runtime installation on your machine.
> Try `clinfo` tool for validation of OpenCL installations.
> 
> You can disable OpenCL in OpenCV via environment variable:
> 
> ```
> export OPENCV_OPENCL_RUNTIME=disabled
> ```

Thank you for your answer, but my real thought is how to make OpenCV automatically recognize this problem. In other words, cv::UMat is used by default, and when the OpenCL environment does not support it, cv::Mat is automatically used, and the program will not crash due to OpenCL problems. For example, I can know in advance whether this computer supports cv::UMat, or OpenCV can judge it by itself.

**Comment by alalek** [comment]
> OpenCV automatically recognize

OpenCV expects that installed OpenCL conforms to Khronos OpenCL specifications.

Probably your case can't be handled at all, because mentioned error calls `abort()` for program completely without any possibility for recovering.
