### ISSUE TITLE
cv::resize memory leak

### ISSUE THREAD

**Issue by daeyeun** [opencv/opencv#14542]
##### System information (version)

- OpenCV => 3.4.6
- Operating System / Platform => Windows7 64Bit
- Compiler => c++

##### Detailed description

vs 2015 detect memory leak after cv::resize
without resize, there is no memory leak

how I can i fix it?
is there any right way to this code?

##### Steps to reproduce

void main()
{
		cv::Mat matImg = cv::imread("181031085202_lb-000000_000594_rectified_cam0.jpg");
		cv::resize(matImg, matImg, cv::Size(2500 , 3500), 0, 0, cv::INTER_NEAREST);
		_CrtDumpMemoryLeaks();
}

{794} normal block at 0x0000000002B065F0, 256 bytes long.
 Data: <         g      > 00 00 00 00 00 00 00 00 10 67 11 00 00 00 00 00 
{793} normal block at 0x0000000000142000, 16 bytes long.
 Data: < g              > 80 67 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{792} normal block at 0x0000000000116780, 40 bytes long.
 Data: <         e      > 00 20 14 00 00 00 00 00 F0 65 B0 02 00 00 00 00 
{791} normal block at 0x0000000000116710, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{782} normal block at 0x0000000002B01890, 256 bytes long.
 Data: <        0f      > 00 00 00 00 00 00 00 00 30 66 11 00 00 00 00 00 
{781} normal block at 0x0000000000141F60, 16 bytes long.
 Data: < f              > A0 66 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{780} normal block at 0x00000000001166A0, 40 bytes long.
 Data: <`               > 60 1F 14 00 00 00 00 00 90 18 B0 02 00 00 00 00 
{779} normal block at 0x0000000000116630, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{765} normal block at 0x0000000002AFF380, 256 bytes long.
 Data: <        Pe      > 00 00 00 00 00 00 00 00 50 65 11 00 00 00 00 00 
{764} normal block at 0x0000000000141EC0, 16 bytes long.
 Data: < e              > C0 65 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{763} normal block at 0x00000000001165C0, 40 bytes long.
 Data: <                > C0 1E 14 00 00 00 00 00 80 F3 AF 02 00 00 00 00 
{762} normal block at 0x0000000000116550, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{753} normal block at 0x0000000002AFE650, 256 bytes long.
 Data: <        pd      > 00 00 00 00 00 00 00 00 70 64 11 00 00 00 00 00 
{752} normal block at 0x0000000000141E70, 16 bytes long.
 Data: < d              > E0 64 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{751} normal block at 0x00000000001164E0, 40 bytes long.
 Data: <p       P       > 70 1E 14 00 00 00 00 00 50 E6 AF 02 00 00 00 00 
{750} normal block at 0x0000000000116470, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{739} normal block at 0x0000000002AFD7F0, 256 bytes long.
 Data: <         c      > 00 00 00 00 00 00 00 00 90 63 11 00 00 00 00 00 
{738} normal block at 0x0000000000141DD0, 16 bytes long.
 Data: < d              > 00 64 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{737} normal block at 0x0000000000116400, 40 bytes long.
 Data: <                > D0 1D 14 00 00 00 00 00 F0 D7 AF 02 00 00 00 00 
{736} normal block at 0x0000000000116390, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{703} normal block at 0x0000000002AFBC70, 256 bytes long.
 Data: <         b      > 00 00 00 00 00 00 00 00 B0 62 11 00 00 00 00 00 
{702} normal block at 0x0000000000141C90, 16 bytes long.
 Data: < c              > 20 63 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{701} normal block at 0x0000000000116320, 40 bytes long.
 Data: <        p       > 90 1C 14 00 00 00 00 00 70 BC AF 02 00 00 00 00 
{700} normal block at 0x00000000001162B0, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{699} normal block at 0x0000000002AFBB30, 256 bytes long.
 Data: <         a      > 00 00 00 00 00 00 00 00 D0 61 11 00 00 00 00 00 
{698} normal block at 0x0000000000141C40, 16 bytes long.
 Data: <@b              > 40 62 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{697} normal block at 0x0000000000116240, 40 bytes long.
 Data: <@       0       > 40 1C 14 00 00 00 00 00 30 BB AF 02 00 00 00 00 
{696} normal block at 0x00000000001161D0, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{677} normal block at 0x000000000015FC70, 256 bytes long.
 Data: <         `      > 00 00 00 00 00 00 00 00 F0 60 11 00 00 00 00 00 
{676} normal block at 0x0000000000141BA0, 16 bytes long.
 Data: <`a              > 60 61 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{674} normal block at 0x0000000000116160, 40 bytes long.
 Data: <        p       > A0 1B 14 00 00 00 00 00 70 FC 15 00 00 00 00 00 
{673} normal block at 0x00000000001160F0, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{637} normal block at 0x000000000015E5C0, 256 bytes long.
 Data: <         `      > 00 00 00 00 00 00 00 00 10 60 11 00 00 00 00 00 
{636} normal block at 0x0000000000141AB0, 16 bytes long.
 Data: < `              > 80 60 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{635} normal block at 0x0000000000116080, 40 bytes long.
 Data: <                > B0 1A 14 00 00 00 00 00 C0 E5 15 00 00 00 00 00 
{634} normal block at 0x0000000000116010, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD 
{633} normal block at 0x0000000002AF6E20, 256 bytes long.
 Data: <         [      > 00 00 00 00 00 00 00 00 B0 5B 11 00 00 00 00 00 
{632} normal block at 0x0000000000141A60, 16 bytes long.
 Data: < _              > A0 5F 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{631} normal block at 0x0000000000115FA0, 40 bytes long.
 Data: <`        n      > 60 1A 14 00 00 00 00 00 20 6E AF 02 00 00 00 00 
{630} normal block at 0x0000000000115BB0, 40 bytes long.
 Data: <                > FF FF FF FF 00 00 00 00 00 00 00 00 CD CD CD CD

---------------------below is cause of dll load 
{395} normal block at 0x0000000000119320, 16 bytes long.
 Data: <                > 08 92 11 00 00 00 00 00 00 00 00 00 00 00 00 00 
{393} normal block at 0x0000000000106CA0, 4 bytes long.
 Data: <    > 00 00 00 00 
...

**Comment by jaybo** [comment]
This is probably not related, but we have a complicated OpenCV CUDA codebase with 5 threads, and upgraded to OpenCV 3.4.5 from 3.3.3 and recently noticed an intermittent GPU memory leak which we can't track down, but which disappears when the Mat and GpuMat dimensions are both multiples of 256.

Just out of curiosity, change your image dimensions to a multiple of 256 and see if it still happens.
