### ISSUE TITLE
SIFT in opencv v 4.0.0.21-openvino

### ISSUE THREAD

**Issue by fnando1995** [opencv/opencv#14540]
##### System information (version)

- OpenCV => 4.1.0-openvino
- Operating System / Platform => Linux / Ubuntu 16.04

##### Detailed description
I'm trying to make a 
`det = cv2.xfeatures2d.SIFT_create()`
in the opencv version detailed before. But gives me this:
`AttributeError: module 'cv2' has no attribute 'xfeatures2d'`
I already have opencv and opencv-contrib

##### Steps to reproduce
Install openvino in a empty environment and try SIFT_create()

**Comment by alalek** [comment]
There are no opencv_contrib modules in OpenVINO builds. Also there are no plans to add them.

Moreover SIFT is patented so its usage is limited (non-commercial use). Contact your lawyer for details.

**Comment by mattiasmar** [comment]
The patent of SIFT has expired now. 
Is there a OpenVINO optimization of SIFT available now? If, what performance is measured on Intel's latest CPUs?
