### ISSUE TITLE
What is the latest version of OpenCV that supports VS2013 compilation?

### ISSUE THREAD

**Issue by vic9527** [opencv/opencv#14553]
I've successfully compiled opencv3.4.3 with vs2013, but I don't know if this is the last version.

I hope to get an official reply. 

Thank you.

**Comment by clunietp** [comment]
OpenCV 4.x requires a C++11 compiler:
https://opencv.org/opencv-4-0/

VS 2013 is not fully C++11 compliant:
https://devblogs.microsoft.com/cppblog/c1114-core-language-features-in-vs-2013-and-the-nov-2013-ctp/

Therefore, I would expect that any OpenCV 3.x branch would compile fine on VS 2013, but not expect OpenCV 4.x to compile successfully.  Or, if it does compile successfully today, it may not do so tomorrow.

**Comment by vic9527** [comment]
> OpenCV 4.x requires a C++11 compiler:
> https://opencv.org/opencv-4-0/
> 
> VS 2013 is not fully C++11 compliant:
> https://devblogs.microsoft.com/cppblog/c1114-core-language-features-in-vs-2013-and-the-nov-2013-ctp/
> 
> Therefore, I would expect that any OpenCV 3.x branch would compile fine on VS 2013, but not expect OpenCV 4.x to compile successfully. Or, if CV4 does compile successfully today on VS13, it may not do so tomorrow.

Thanks for your answer, I recently tested the compilation of 3.4.3, 3.4.4, 3.4.5, 3.4.6 in VS2013. The result is that only 3.4.3 can be fully compiled successfully (including opencv_world). So the high probability of opencv3.4.3 may be the last version that supports VS2013 compilation.

**Comment by clunietp** [comment]
Thanks for the correction.  Looks like this has already been addressed as well:
https://github.com/opencv/opencv/issues/14546
