### ISSUE TITLE
NMSBoxes returned NULL without setting an error

### ISSUE THREAD

**Issue by Songsterr99** [opencv/opencv#14551]
https://stackoverflow.com/questions/56128484/cv2-dnn-nmsboxes-returns-null-without-setting-an-error

**Comment by dkurt** [comment]
Closing it. Please check samples of how we use NMSBoxes:
https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp  
https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py
