### ISSUE TITLE
Getting module 'cv2.dnn' has no attribute 'readNet'

### ISSUE THREAD

**Issue by abhinavsagar** [opencv/opencv#14560]
I am trying to run a simple yolo code. But on running I am getting-
`Traceback (most recent call last):
  File "yolo_opencv.py", line 57, in <module>
    net = cv2.dnn.readNet(args.weights, args.config)
AttributeError: module 'cv2.dnn' has no attribute 'readNet'`

**Comment by dkurt** [comment]
@abhinavsagar, Please do not ignore issues template. They contain necessary fields which may help you to solve the problem.
