### ISSUE TITLE
AssertionError   tf_text_graph_ssd.py 

### ISSUE THREAD

**Issue by zcunyi** [opencv/opencv#14563]
###  System information (version)
OpenCV => 4.0.0
Operating System / Platform => Ubuntu 16.04 LTS
Compiler => cmake

###  Detailed description
When I use the newest version of tf_text_graph_ssd.py to generate graph txt file for my own tensorflow model, I keep getting this error:

```
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 368, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 232, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError
```

Please take a look to the new version, I honestly don't know why it does not work while the other Issue post says it worked. Thank you!

**Comment by alalek** [comment]
> OpenCV => 4.0.0
> the newest version of tf_text_graph_ssd.py

4.0.0 is not the latest release. Please try latest master.

> my own tensorflow model

Priority => low
We can't fix issues which we can't reproduce on our side.

**Comment by zcunyi** [comment]
> > OpenCV => 4.0.0
> > the newest version of tf_text_graph_ssd.py
> 
> 4.0.0 is not the latest release. Please try latest master.
> 
> > my own tensorflow model
> 
> Priority => low
> We can't fix issues which we can't reproduce on our side.

I reinstall the opencv '4.1.0-dev', but I also get the same error:
`Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 739, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 603, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError
`
The commands I used is below:
`(base) zcy@zcy-desktop:~/0_projects/opencv-master/samples/dnn$ python2 tf_text_graph_ssd.py  --input /home/zcy/0_projects/tensorflow/models-master/research/object_detection/data/zcy_data/zcy_inference_516/frozen_inference_graph.pb  --config /home/zcy/0_projects/tensorflow/models-master/research/object_detection/data/zcy_data/zcy_inference_516/pipeline.config  --output /home/zcy/0_projects/tensorflow/models-master/research/object_detection/data/zcy_data/zcy_opecv_dnn/517_graph.pbtxt
Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.33329999446868896]
Reduce boxes in the lowest layer: True
Number of classes: 2
Number of layers: 6
box predictor: convolutional
Input image size: 300x300
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 739, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 603, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError
`

**Comment by zcunyi** [comment]
> > OpenCV => 4.0.0
> > the newest version of tf_text_graph_ssd.py
> 
> 4.0.0 is not the latest release. Please try latest master.
> 
> > my own tensorflow model
> 
> Priority => low
> We can't fix issues which we can't reproduce on our side.

I reinstall the opencv4.1.0 by 'https://docs.opencv.org/master/d2/de6/tutorial_py_setup_in_ubuntu.html' .
why it always python2 ?
`--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.12)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.12)
--     numpy:                       /home/zcy/.local/lib/python2.7/site-packages/numpy/core/include (ver 1.16.3)
--     install path:                lib/python2.7/dist-packages/cv2/python-2.7
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:                          
--     ant:                         NO
`

**Comment by dkurt** [comment]
@zcunyi, Can you provide reference to mentioned model?

**Comment by BTM520** [comment]
> @zcunyi, Can you provide reference to mentioned model?
### same the problem:
```sh
Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.333299994469]
Reduce boxes in the lowest layer: True
Number of classes: 3
Number of layers: 6
box predictor: convolutional
Input image size: 300x300
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 369, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 233, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError
```
### my env:
```sh
opencv-contrib-python              4.1.0.25   
opencv-python                      4.1.0.25 

```
### model 
the model I used: `ssdlite_mobilenet_v2_coco_2018_05_09.config` ...

**Comment by alex4men** [comment]
@zcunyi @BTM520 have you tried this solution? https://github.com/opencv/opencv/issues/11560#issuecomment-391047037
I had exactly the same issue and sorting nodes in the graph, as advised, helped me.

**Comment by skaldesh** [comment]
@alex4men I tried it and it fixed the problem with the assertion error. However, now I get the next error:
```python
Traceback (most recent call last):
  File "/scripts/tf_text_graph_ssd.py", line 380, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "/scripts/tf_text_graph_ssd.py", line 264, in createSSDGraph
    addConstNode('concat/axis_flatten', [-1], graph_def)
  File "/scripts/tf_text_graph_common.py", line 114, in addConstNode
    graph_def.node.extend([node])
TypeError: Not a cmessage
```

**Comment by skaldesh** [comment]
I created a separate issue for this new exception: https://github.com/opencv/opencv/issues/14993
