### ISSUE TITLE
connectedComponents merges regions separated by single pixel divider

### ISSUE THREAD

**Issue by hlgirard** [opencv/opencv#14568]
##### System information (version)

- opencv-python => 4.1
- Operating System => macos 10.14.4 Mojave
- Python => 3.7

##### Detailed description

It appears that `connectedComponents` does not separate components that are divided by a single pixel dividing line.

For context, this is an issue when trying to obtain region stats from an image segmented with the `watershed` method (ultimately I want to use `connectedComponentsWithStats`). Since `connectedComponents` does not handle already labeled images, I binarize the image by setting the background and dividing lines as 0 and the labeled regions as 255. The resulting binary image (`segmented_bin`) has regions separated by a single-pixel-wide line.
 
![CoinsSegmented](https://user-images.githubusercontent.com/8866213/57786871-499a4e00-7702-11e9-8915-3b0ff10955a1.JPG)

Running `connectedComponents` on this image returns only 2 regions: the background and an aggregate of the foreground regions.

##### Steps to reproduce

Here is a sample code to reproduce the issue

```python
import cv2

[...] # Prepare markers as in https://docs.opencv.org/3.4/d3/db4/tutorial_py_watershed.html

segmented = cv2.watershed(img,markers)

segmented_bin = segmented.copy()
segmented_bin[segmented < 2] = 0 # -1 is dividing regions, no 0s, 1 is background
segmented_bin[segmented > 1] = 255 # all above 1 are distinct regions
num_labels, label_image = cv2.connectedComponents(segmented_bin.astype('uint8'), 8, cv2.CV_16U, cv2.CCL_GRANA)
```

Executing this code returns `num_labels = 2` instead of 27.

**Comment by alalek** [comment]
JPEG images are not lossless, don't put them as a reproducer data. Use PNG or other losless format instead for reproducible results.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Why is 8-way connectivity used?

**Comment by hlgirard** [comment]
Sorry about the JPEG format, here is a PNG image that shows the same problem:

![CoinsSegmented](https://user-images.githubusercontent.com/8866213/57859217-83ca2500-77c0-11e9-81e8-44ffa0e843d1.PNG)

I have asked this question on stackoverflow and answers.opencv.org and gotten good suggestions on how to make it work for me by using contours and doing an erosion step but neither explain why `connectedComponents()` doesn't perform as expected.

I have tried with both 4-way and 8-way connectivity as well as with all 3 algorithms offered: wu, default, and grana.

**Comment by crackwitz** [comment]
check the signature of your connectedComponents call. you missed the `labels` argument? https://docs.opencv.org/trunk/d3/dc0/group__imgproc__shape.html#gaedef8c7340499ca391d459122e51bef5
