### ISSUE TITLE
Opencv build failed in TinkerBoard with ArmbianOS(Ubuntu 18.04)

### ISSUE THREAD

**Issue by wan420** [opencv/opencv#14564]
OS details :

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

running on TinkerBoard

```[ 77%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlof/rlof_localflow.cpp.o
/home/cst/opencv_contrib/modules/optflow/src/rlof/rlof_localflow.cpp:7:10: fatal error: opencv2/highgui.hpp: No such file or directory
 #include "opencv2/highgui.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
modules/optflow/CMakeFiles/opencv_optflow.dir/build.make:189: recipe for target 'modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlof/rlof_localflow.cpp.o' failed
make[2]: *** [modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlof/rlof_localflow.cpp.o] Error 1
CMakeFiles/Makefile2:22420: recipe for target 'modules/optflow/CMakeFiles/opencv_optflow.dir/all' failed
make[1]: *** [modules/optflow/CMakeFiles/opencv_optflow.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2```

any idea on this issue?
It seems a file is trying to include highgui.hpp before the opencv build is complete
sorry I dont have more to go on..
Thanks for any input

**Comment by alalek** [comment]
> opencv_contrib

Wrong repository.


> rlof_localflow.cpp

Fixed in latest master.

You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

**Comment by wan420** [comment]
hmm.. ok .. i thought I had that covered, I mean I downloaded the 4.1.0 of opencv_contrib and the master repo of opencv, does this still come into mismatch?
