### ISSUE TITLE
MaskRCNN doesnt work using cv::dnn::Net when image resolution changes of input images

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#14566]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Forwarding images using MaskRCNN fails if the image resolution changes over time.

##### Steps to reproduce

It works for the first few images, but after about 5 images with each a different resolution no results are available anymore.

in the function postprocess(...) 

outDetections = outDetections.reshape(1,(int)(outDetections.total() / 7)); always returns the same number for any forwarded image. Its being stuck at the number of the last successful forwarding.

I used the following code as a reference.

https://github.com/opencv/opencv/blob/48dad1b02ea8f743e6d165e94a5a4842d96c7a7e/samples/dnn/mask_rcnn.cpp

with net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);

**Comment by tompollok** [comment]
@alalek isn't this rather a bug than a feature?

**Comment by dkurt** [comment]
Have you tried to use the latest version of OpenCV? I just want to check if this merged changes resolved your problem: https://github.com/opencv/opencv/pull/14552.

**Comment by tompollok** [comment]
No only 4.1. Ill try master on Monday

**Comment by tompollok** [comment]
Opencv 4.1 master did not resolve the issue.

I checked and the commit was already merged into master from 3.4
https://github.com/opencv/opencv/pull/14570

Here a video of the issue, that shows that the output of the forwarding is not deterministic and fails after forwarding the same pair of images after two iterations:
https://www.youtube.com/watch?v=o0uvMSGZskA&feature=youtu.be

**Comment by dkurt** [comment]
@tompollok, If you want to help us solve it faster please do not make us to reproduce the video - add a fully working example with all the images.

**Comment by tompollok** [comment]
The code i use is as mentioned in https://github.com/opencv/opencv/blob/48dad1b02ea8f743e6d165e94a5a4842d96c7a7e/samples/dnn/mask_rcnn.cpp

The only thing that is missing is that the example does not habe a loop to always use the same two images.

Image A must have a different resolution than B and should contain RCNN model supported objects. In my case persons.

Forward image A (gives results)
Forward image B (gives results)
Forward image A (gives different results than in A1)
Forward image B (gives different results than in B1)
Forward image A (gives no results anymore)
Forward image B (gives no results anymore)

**Comment by dkurt** [comment]
What is image A and image B? Attach them please (in `.png` format).

**Comment by tompollok** [comment]
![Image_0000000A](https://user-images.githubusercontent.com/4457821/58174296-db273400-7c9d-11e9-9f21-58d1a0249e3d.PNG)
![Image_0000000B](https://user-images.githubusercontent.com/4457821/58174297-db273400-7c9d-11e9-9b0c-5233b91458fc.PNG)

I should be reproducible for any images as long as the resolution is not equal.

**Comment by dkurt** [comment]
Can confirm the bug:
![0](https://user-images.githubusercontent.com/25801568/58177060-4c6de380-7cac-11e9-8949-12c4dd5da238.jpg) ![1](https://user-images.githubusercontent.com/25801568/58177059-4c6de380-7cac-11e9-9a6b-5e35dfb58b9f.jpg)
![2](https://user-images.githubusercontent.com/25801568/58177057-4bd54d00-7cac-11e9-96df-dd016f19ee81.jpg) ![3](https://user-images.githubusercontent.com/25801568/58177056-4bd54d00-7cac-11e9-8a56-78df33a9945b.jpg)

**Comment by tompollok** [comment]
Same issue with inference engine backend.

**Comment by tompollok** [comment]
Any ideas how to fix this?

**Comment by dkurt** [comment]
@tompollok, For now you can forward fixed inputs. Do you really need to vary their sizes?

**Comment by tompollok** [comment]
I can reinitialize each time the resolution changes. I use it to create binary masks for imageregions where humans are visible to improve Structure from Motion pipeline by avoiding matching dynamic scene parts.

Im not in a hurry for a fix.

**Comment by dkurt** [comment]
@tompollok, But why not to resize each humar ROI to specific size, predict on it and then remap to origin size?

**Comment by tompollok** [comment]
That i could do, too, but then the inference time scales linear with the number of people. I just reinitialize for now on resolution change. The inference time on CPU is quite slow anyways.

The reason why i reported this bug is because i thought that this bug might be an issue in general, not only for mask_rcnn.

**Comment by dkurt** [comment]
@tompollok, It's not clear for me. How you select image regions and why not to run all the model on entire frame? Why not to resize each image region to specific size?

**Comment by dkurt** [comment]
Sorry for too late fix but here it is: https://github.com/opencv/opencv/pull/16580. Thanks for nice catch!

**Comment by tompollok** [comment]
You dont have to say sorry. Im very thankful for you investigating it, so thank you for the patch! Its really awesome to see how fast the DNN backends have evolved, especcially in the last 12 months!
