### ISSUE TITLE
Is there a python version of yolo?

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#14577]
I used the opencv3.4.1 test code before.
 I USE the python opencv yolo ： [https://github.com/spmallick/learnopencv](https://github.com/spmallick/learnopencv)
Now I want to use yolov3 network, so I use opencv4.0

1、Why do I use opencv3 and opencv4 to test yolo networks at different speeds?Opencv4 runs yolov2 network slower
2、Why can't I detect any objects using opencv4 test yolov2?  USE this code ： [https://github.com/spmallick/learnopencv](https://github.com/spmallick/learnopencv)
3、[https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp) Is this code the latest yolo test code?Does this code have a python version?

**Comment by dkurt** [comment]
Yes, there is: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

For other questions please do some research: provide numbers, target and resulting images, etc.
