### ISSUE TITLE
meanStdDev

### ISSUE THREAD

**Issue by TMXY** [opencv/opencv#14571]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by TMXY** [comment]
*Opencv4.0.1
*Ubuntu16.04
*GCC7.4
Utilize cv::meanStdDev() function to deal one-channel image as the method as follow,
 cv::Scalar mean,stddev;
  cv::meanStdDev(noiseGrayDouble,mean,stddev);
  double standNoise = stddev.val[0];
And the value standNoise would be changed as execution, of course dealing with the same image.
Eg, as the 1st running execution, the value was 0.0156472, then on the 2nd, it changed to be 0.015675, 3rd would be 0.015677... it would be loop.
As the result solved by valgrind, the error is "conditional jump or move depends on uninitialised value(s)"
at meanStdDev of libopencv_core.so.4.0.1

**Comment by alalek** [comment]
Consider using of "Edit" button for updating of the issue's description.

What is dimension / sizes of `noiseGrayDouble` input?
Did you run with IPP? Try `OPENCV_IPP=disabled` environment variable.

> 4.0.1

This release is not latest.
Please try latest code from the master branch too.

**Comment by TMXY** [comment]
noiseGrayDouble's is 2D and gray scale.

**Comment by TMXY** [comment]
Why turn down the IPP flag which could improve the dft running time? Thx.

**Comment by alalek** [comment]
Exact input size is required.
Turn off IPP to find what optimization is caused this problem.

**Comment by TMXY** [comment]
what do you mean input size? If you means the "noiseGrayDouble" that was already defined. 
As the opencv document does not mention it. BTW, I utilize the method as  https://github.com/arnaudgelas/OpenCVExamples/blob/master/cvMat/Statistics/StandardDeviation/StandardDeviation.cpp
Thx.

**Comment by alalek** [comment]
`std::cout << noiseGrayDouble.size() << std::endl;`

It is required to construct complete minimal reproducer.

**Comment by TMXY** [comment]
???Actually the size of noiseGrayDouble.size() = [2556 1440], which is defined as cv::Mat noiseGrayDouble=cv::Mat(row,col,CV_64F).
And I do not get your point.

**Comment by TMXY** [comment]
No need to turn off IPP
