### ISSUE TITLE
Can cv2. putText support Chinese output?python opencv

### ISSUE THREAD

**Issue by QQ2737499951** [opencv/opencv#14579]
Can cv2.putText support Chinese output? ?such as“人”，“狗” ,THX!

cv2.putText(img, text=‘中文显示’, (123,456)), font, 2, (0,255,0), 3)

各参数依次是：图片，添加的文字，左上角坐标，字体，字体大小，颜色，字体粗细

**Comment by alalek** [comment]
No. Also there is no plan to add that (lets keep library simple).

Consider using alternative API via 3rdparty libraries (QT or freetype from opencv_contrib).
Or use something from Python world to draw on numpy array.

If you need static text message, then you can prepare image with its content (sprite).
Draw image instead of text (something like: `img(roi_rect).setTo(text_img, /*mask=*/ text_img_mask)` (C++)).

**Comment by crackwitz** [comment]
the freetype module's `putText` procedure in python is called `cv2.freetype.putText`, so give that a try

**Comment by crackwitz** [comment]
if you build opencv with the freetype contrib module, you can use its `putText` procedure. here's something you can try:
```
import numpy as np
import cv2 as cv
ft2 = cv.freetype.createFreeType2()
ft2.loadFontData("c:\\windows\\fonts\\msjh.ttf", 0)
im = np.zeros((100,1000,3), 'uint8')
text = "各参数依次是：图片，添加的文字，左上角坐标，字体，字体大小，颜色，字体粗细"
ft2.putText(im, text, (10,10), fontHeight=20, color=(255,255,255), thickness=1, line_type=cv.LINE_
4, bottomLeftOrigin=False)
cv.imshow("im", im)
cv.waitKey()
```
for me it has some glitches but it might work better for you.
![freetype chinese](https://user-images.githubusercontent.com/7065108/58633128-dab71a80-82e7-11e9-9c63-5610e753c4db.png)

**Comment by shawnthu** [comment]
module 'cv2.cv2' has no attribute 'freetype'
cv2 version: 4.2.0
os: ubuntu 16.04 LTS
python: 3.6.5

**Comment by crackwitz** [comment]
then your opencv wasn't built with support for freetype. run `print(cv.getBuildInformation())`

**Comment by shawnthu** [comment]
> then your opencv wasn't built with support for freetype. run this:
> 
> ```python
> import cv2 as cv
> print(cv.getBuildInformation())
> ```
thx, got the following output:
Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf java js matlab ovis python2 sfm ts viz

I installed opencv-python with 'pip install opencv-contrib-python'. So I can only build from source to install extra freetype module?

**Comment by oo-simbo** [comment]
> How to draw Chinese text on the image using Cv2.PutText in C# (opencvsharp)?

You can draw text by using System.Drawing.dll
