### ISSUE TITLE
LineSegmentDetector  original code liscence issue

### ISSUE THREAD

**Issue by oym1994** [opencv/opencv#14576]
When I use the build-in class  LSDDetector::createLSDDetector ,  I just follow the opencv tutorial " https://docs.opencv.org/master/df/d4c/classcv_1_1ximgproc_1_1FastLineDetector.html".

But I just got the issue 
"error: (-213:The function/feature is not implemented) Implementation has been removed due original code license issues in function 'LineSegmentDetectorImpl'".

I know its meaning. But I just want to verify whether is means we can't use this class and algorithm anymore. And how to solve it. Thank you very much ! ! ! !

**Comment by mshabunin** [comment]
@oym1994 , here is an explanation: https://github.com/opencv/opencv_contrib/issues/2016

**Comment by sturkmen72** [comment]
you can use `FastLineDetector`
see https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/samples/fld_lines.cpp

**Comment by maky-hnou** [comment]
I had the same issue with `opencv-contrib-python==4.1.1.26` and `opencv-python==4.1.1.26`.  
**The solutions** I ended to are: 

- Downgrade to `opencv-contrib-python==4.0.0.21` and `opencv-python==4.0.0.21`.  

- According to this [question](https://stackoverflow.com/questions/56016650/how-to-implement-lsd-in-opencv-4-1-0) on Stakoverflow, to replace the missing `LineSegmentDetectorImpl`, install pylsd using `pip install pylsd`. For more details about how to use it with opencv, please check [the documentation](https://github.com/primetang/LSD-OpenCV-MATLAB/tree/master/pylsd).

**Comment by SubMishMar** [comment]
Is there a way to match lines detected by the Fast Line Detector? I think that was an added advantage of using the Line Segment Detector, one could match keylines..
