### ISSUE TITLE
Unknown CMake command  android_get_compatible_target

### ISSUE THREAD

**Issue by babykangaroo22** [opencv/opencv#14572]
##### Detailed description
OpenCV: 3.4.1
Operating System / Platform => Linux ubuntu 4.15.0-45-generic~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

I want to compile android .so，here is my command:
cmake -DCMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake -DCMAKE_ANDROID_NDK=/home/xx/android/android-ndk-r17c -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_ANDROID_PROJECTS=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_INSTALL_PREFIX=/home/xx/opencv/android ..

it supposed to be every easy,but I got a problem:
"### **Unknown CMake command  android_get_compatible_target**"
I don't know where the definition is , or what command should I use.

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

> OpenCV: 3.4.1

Try latest OpenCV code at first.
