### ISSUE TITLE
Higher level API for DL networks.

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#14580]
Basically, this is a GSoC project which has not been applied this year: 

We want to see some kind of higher level API which can manage DL networks. There are several criterias for now:

* Hide asynchronous inference management internally. User just choose the number of requests (what about heterogenous scenario? In example, use both GPU and VPU with specific number of requestst for each other).
* Models from https://github.com/opencv/opencv/blob/master/samples/dnn/models.yml should be downloaded automatically in samples. Can we also introduce some kind of new automatically generated classes definitions for them? I.e.:

```cpp
CV_EXPORTS_W YOLOv3 : public Model {
  YOLOv3(const std::string& model = "yolov3.weights", const std::string& config= "yolov3.cfg", int weight = 416, int height = 416, Scalar mean = Scalar(), float scale = 0.00392);
};
```
User do not need to care about input's preprocessing. We can do it automatically. The base class can find the files (already implemented) or download if there are no (need to do).

```cpp
class Model : public Net {
  Model(const std::string& model, const std::string& config = "", int weight = -1, int height = -1, Scalar mean = Scalar(), float scale = 1.0);

  // Overridden version which accepts frame and can make blob.
  void setInput();
};
```

* We can add some methods to simplify postprocessing (i.e. detect type of output layer for detection network as we do in object detection samples):
```cpp
void detect(std::vector<float>& confidences, std::vector<Rect>& boxes, float confThreshold, float nmsThreshold);
```

So instead doing `forward` with postprocessing and can just call `detect` and then manage the predictions (i.e. draw it on the frame).

*

**Comment by skhadem** [comment]
Managing the postprocessing seems awesome. Could be cool to be able to call detect() and pass a flag, which would automatically visualize outputs on an image by drawing the BB or applying the segmentation mask.
I have been working to try and contribute by getting comfortable with the code base, and would love to try and take this on. Do you have any additional suggestions for getting started? I have read all the guides and so far have been just going through code.

**Comment by dkurt** [comment]
@skhadem, I also think that this is a good idea. Yeah, we also wanted to add a camera management here. Something like

```cpp
void Model::setVideoCapture(VideoCapture& cap, bool async = true);

void Mat getFrame();
```

You can call `getFrame` and `setInput` or just `detect` and the Model can just check if VideoCapture is opened so it's a source for inputs. The thing is that the best efficiency might be achieved with separate camera thread (see https://github.com/opencv/opencv/pull/14516 for example).

Looking forward to see you results. Thanks! I think that we can solve this issue by separate PRs. First one might introduce `dnn::Model` with different methods. In example,

```
void Model::setInput(const Mat& frame);

void Model::detect(CV_OUT std::vector<float>& confidences, CV_OUT std::vector<Rect>& boxes, float confThreshold = 0.5f, float nmsThreshold = 0.4f);

void Model::classify(float& confidence, int& classId, float confThreshold);

void Model::classify(CV_OUT std::vector<float>& confidences, CV_OUT std::vector<int>& classIds, float confThreshold, int top);
```

`CV_OUT` here is just a macro to tell bindings generator that these arguments are output ones so i.e. in Python we will have something like
```python
confs, boxes = opencv_fd.detect()
```
(just to not forget)

**Comment by skhadem** [comment]
@dkurt Sounds good, I can begin to work on it. Is there a better way to contact you (or someone else) about questions that may arise? Or does this thread work best?

**Comment by dkurt** [comment]
@skhadem, I'd like to recommend this thread. I'm not an only person who can provide good advice about the issue.

**Comment by l-bat** [comment]
@skhadem, will you work on this issue? Or can I start working on it?

**Comment by skhadem** [comment]
@l-bat I am currently working on it, but am open to collaborating and working together

**Comment by skhadem** [comment]
@dkurt I am working on adding asynchronous capabilities, and had a question for you. Similar to the cpp_object_detection I have a thread spun up to grab image frames, but I don't understand where the performance gain is. With async, a backlog of frames will build up since the camera frame rate is higher than the network frame rate. Without async, a frame is obtained, processed, then returned. But in both modes, the consumer has the same output frame rate, since the bottleneck is based on the network speed. Is the idea of async to simply use the net with intel's inference engine and call forwardAsync()? I see how that is much faster, but this is mostly due to the better backend, correct? So having a separate thread to read frames from a camera doesn't seem to matter, unless I am doing something wrong

**Comment by dkurt** [comment]
@skhadem, we prepared an initial version in https://github.com/opencv/opencv/pull/14780. So I'd like to suggest how the skeleton will looks like at the end and then you can join with next steps.

**Comment by skhadem** [comment]
Oh okay. Looks like we have duplicated a lot of work :/ Mine is more modularized with different objects and also has multithreading and segmentation support. So maybe once skeleton is in I will go through and merge mine into that structure

**Comment by edgarriba** [comment]
@dkurt we have just found this now and I think there was probably a miscommunication issue between intel team and opencv org responsible for gsoc projects. We started to work on something similar two weeks ago. You can see the details here: https://github.com/dvd42/opencv/wiki

See more: https://github.com/opencv/opencv/issues/14772

/cc @bhack @alalek @garybradski

**Comment by dkurt** [comment]
@edgarriba, That's really confusion moment because this issue is based on https://github.com/opencv/opencv/wiki/GSoC_2019#idea-python-deep-learning-inference-on-video GSoC idea which was not accepted this year:

> But, performing inference on video requires producing much boilerplate code and skills not directly relevant to computer vision. The goal of this project is to develop a high-level helper class in python to perform optimized inference on videos (eg, pose detection, emotion detection) with data storage (eg, output and bounding boxes) in dataframes for easy access.

However original idea of Diego's task is to extend Model Zoo and provide an access for the models: https://github.com/opencv/opencv/wiki/GSoC_2019#idea-model-zoo-curate-deep-nets-for-the-dnn

> The goal of this project is to curate more models for ease of use by the OpenCV DNN module and put them in a place that they can be easily accessed such as LFS on Git. The mentor/admins will formalize the storage place.

So this issue is about efficient management of OpenCV's network on video (how to use VideoCapture and asynchronous inference feature without queues management).

I must agree that this is a kind of miscommunication. What do you think if we provide a basic classes `cv::dnn::Model` and `cv::dnn::DetectionModel` as a baseline so you can adjust them for other tasks? I believe you haven't started to work on API implementations but first started with networks enablement?

**Comment by bhack** [comment]
@dvd42 (Diego) started with an API design stub. You have a base UML rendering of the stub at https://github.com/dvd42/opencv/wiki#api-uml and stub code https://github.com/dvd42/opencv_contrib/tree/dnn_models/modules/dnn_models. 
Diego is maintaining the stub design in PlantUML format, as some years ago we have done for introducing the Opencv Tracking API design, so that it could be patched in git.
Can we co-design over that UML? If you want @dvd42 could open a PR just with the UML source file.

**Comment by dkurt** [comment]
@bhack , The thing is that we also opened an initial PR https://github.com/opencv/opencv/pull/14780.

**Comment by bhack** [comment]
@dkut So can you  comment on this? Do you plan to cover something like this design with a #14780 follow-up in charge of your team? Or can we adapt this UML design to be compatible with #14780? 

Cause we need absolutely need to perimeter as soon as the GSOC activity. 

![uml](https://user-images.githubusercontent.com/1710528/59444008-627b4980-8dfd-11e9-91ac-f08aba05de6f.png)

**Comment by dkurt** [comment]
Yeah, our design for now looks in the same way. The only thing is that `DNNModel` we named as `Model` (due we want to put in in the `cv::dnn` namespace). And there are a bit different methods.

**Comment by skhadem** [comment]
Just a note, I believe `SegmentationModel` may need a different interface, especially for semantic, since the output will be a `cv::Mat` with confidences per pixel

**Comment by AlexeyAB** [comment]
@dkurt 

> User do not need to care about input's preprocessing. We can do it automatically. The base class can find the files (already implemented) or download if there are no (need to do).

If you want to do automatic pre-processing that includes `blobFromImage()`, then there must be a switch to do one of three ways of resizing:
1. Resizing that keeps apsect ratio and crops part of image - in OpenCV-dnn `blobFromImage()`
2. Resizing that keeps apsect ratio and higher reduces the image - in original Darknet Yolo repository `letterbox`
3. Resizing that doesn't keep aspect ratio - simple `cv::resize()` (the largest object size)


There are trade-off in any cases - below are an examples of resizing an image in different ways:
**Original image:**
![air](https://user-images.githubusercontent.com/4096485/31623978-dc1fcada-b2a9-11e7-99a1-9d87293fcc74.jpg)


1. `blobFromImage()`: object size **71 x 43**, keeps aspect ratio, but **part of image is lost (cropped)**
![air_416x416_cropped](https://user-images.githubusercontent.com/4096485/31624238-b102326a-b2aa-11e7-9db1-399b2888927e.jpg)


2. `letterbox_image()`: **the smallest** object size **48 x 28**, keeps aspect ratio and see whole image
![air_416x416_letterbox](https://user-images.githubusercontent.com/4096485/31624244-b5a8a722-b2aa-11e7-9330-bf7b3feef65a.jpg)


3. `cv::resize()`: object size **48 x 43**, see whole image but **doesn't keep aspect ratio** - just resizes image to 416x416
![air_416x416](https://user-images.githubusercontent.com/4096485/31624247-b89e6c14-b2aa-11e7-8992-b2fc020575af.jpg)

**Comment by dkurt** [comment]
@AlexeyAB, Thanks for proposal! Looks like also related to this issue: https://github.com/opencv/opencv/issues/14659. We need both resize it and then map predictions to origin frame.
