### ISSUE TITLE
Linking the 4.1 dylibs causes gatekeeper validation failure on macOS 10.14

### ISSUE THREAD

**Issue by LGriffioen** [opencv/opencv#14588]
Linking any dylib from OpenCV 4.1 to an existing macOS app causes gatekeeper to fail the validation, presenting the unidentified developer message. All checks related to validating codesigning are passing, so the app is being properly signed with a valid certificate. This issue does not happen with Open CV 3.x

Files were built from source on macOS 10.14 using CMake

**Comment by mshabunin** [comment]
Did you build OpenCV yourself? How did you sign it?

**Comment by LGriffioen** [comment]
Yes, are there prebuilt versions for macOS that I could try?

we're signing with a shell script that looks like this:
```
for dylib in "$FULL_PRODUCT_NAME"/Contents/Frameworks/*.dylib; do
   codesign -f --verify --verbose=4 --display --timestamp -s "$SIGNING_CERT" "$dylib";
done
```

note that we did not change the script from when we were using OpenCV 3.1.0

**Comment by mshabunin** [comment]
My guesses are unsigned 3rdparty dependencies (e.g. FFmpeg) or camera authorization functionality added to 4.1.0 (#14267). It is hard to say without detailed information about failed Gatekeeper check.

**Comment by LGriffioen** [comment]
Unfortunately gatekeeper doesn't give us any helpful information. I'm glad you mentioned the camera access though, I can try signing OpenCV with entitlements.

**Comment by LGriffioen** [comment]
Signing OpenCV with entitlements didn't seem to help. Do you know if there are prebuilt versions of OpenCV for macOS that I can try?

**Comment by mshabunin** [comment]
You can try OpenCV from [OpenVINO for OSX](https://software.intel.com/en-us/openvino-toolkit), but it is linked with InferenceEngine dynamic library.

Try [deep verification](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG404) to get more information:

>When verifying signatures, add --deep to perform recursive validation of nested code. Without --deep, validation will be shallow: it will check the immediate nested content but not check that fully. Note that Gatekeeper always performs --deep style validation.

**Comment by LGriffioen** [comment]
I tried the deep validation and it claims everything is ok, including the OpenCV dylibs. I tried the approach of making a test app with nothing other than openCV linked to it and that appears to work, so in theory I should be able to fix this, but I'm not sure what would cause the difference. I'm signing the test app with the same cert and entitlements as our main app.

**Comment by LGriffioen** [comment]
oh I found something in the system console that may be helpful:

> File OurApp.app/Contents/MacOS/../Frameworks/libopencv_photo.4.1.dylib failed on rPathCmd ~/Downloads/build/lib/libopencv_imgproc.4.1.dylib

so i built OpenCV to `~/Downloads/build/` and it appears the app's photo lib is trying to reference the imgproc lib from my downloads folder

**Comment by alalek** [comment]
Avoid using "build" folders for packaging. Use "install" directory for that (and "install" target).

Did you try this script: [osx/build_framework.py](https://github.com/opencv/opencv/blob/4.1.0/platforms/osx/build_framework.py)  ?

**Comment by mshabunin** [comment]
@LGriffioen , you need to build OpenCV with disabled RPATH: `-DCMAKE_SKIP_RPATH=ON` cmake option (https://cmake.org/cmake/help/v3.5/variable/CMAKE_SKIP_RPATH.html)

**Comment by LGriffioen** [comment]
`CMAKE_SKIP_INSTALL_RPATH` did the trick! Thank you so much for your help and quick responses.

P.S. The performance improvements in v4 are awesome, great work
