### ISSUE TITLE
Python typing stub

### ISSUE THREAD

**Issue by milliams** [opencv/opencv#14590]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Linux
- Compiler => GCC 8.3.1

##### Detailed description

When importing `cv2` as a Python module and using a tool like mypy or an IDE like PyCharm they have no information about the functions etc. in the module.

I propose adapting the Python API generating script `gen2.py` to do two things:

1. Change the signature description to include type information in the modern Python style.
2. Create a [Python typing stub file](https://www.python.org/dev/peps/pep-0484/#stub-files) which will allow tools to know what functions are available and what types they expect/return.

By type information in the signature I mean, change for example:

```python
def GaussianBlur(src, ksize, sigmaX[, dst[, sigmaY[, borderType]]]) -> dst
```
to
```python
def GaussianBlur(src: Union[Mat, UMat],
                 ksize: Size,
                 sigmaX: int,
                 dst: Optional[Union[Mat, UMat]] = None,
                 sigmaY: int = 0,
                 borderType: int = BORDER_DEFAULT
                ) -> Union[Mat, UMat]
```

Once you have these adapted signature strings, you can put them into a file called `__init__.pyi` in the `cv2` Python directory and the tools will find it.

Even if it is not feasible to get full typing support (due to ambiguity for some types), it will at least provide autocompletion support for IDEs.

**Comment by lwyj123** [comment]
any updates?

**Comment by 517030910405** [comment]
Is the issue solved?

**Comment by neelkarma** [comment]
+1 to this - many tools currently have to generate stub files for compiled modules like these, and many of the argument and return types of functions end up being `Any` or `Unknown`, which doesn't help. If type stubs were included with the library, it would be a godsend.

**Comment by crackwitz** [comment]
might this be a decent candidate for GSoC? I don't see much "housekeeping" yet in the ideas list yet: https://github.com/opencv/opencv/wiki/GSoC_2021

**Comment by alalek** [comment]
We need an example for case with wrapping C++ overloads with different number / set of parameters (not types only).

Also there are some internal requirements on arrays, for example, specific for layout representation: 2D matrix, 2D+RGB image layout, 2D 3x3 matrix, etc. Some of these requirements are available through doc strings (available through `help()` by it requires loading of "binary extension module", so it is not available in IDEs).
Perhaps this stuff should be ported into `.pyi` file somehow too.

BTW, Currently there is no `Mat` in Python, `numpy.array` is used for that (with some transformations).

**Comment by metal3d** [comment]
It's been 2 years now... no any update ? Using coc-pyright on vim is a very bad experience with opencv:
![image](https://user-images.githubusercontent.com/100080/123507654-dac2a980-d66a-11eb-874f-3eac73451d92.png)

**Comment by neelkarma** [comment]
@metal3d When OpenCV 5 gets released, it will come with named arguments, hopefully fixing the issue, but in the meantime, you'll have to generate type stubs with something like [stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) to let coc-pyright know what the members of the cv2 module are

**Comment by metal3d** [comment]
@neelkarma right, this is what I did right now:
```
stubgen -m cv2 -o .venv/lib/python3.9/site-packages/cv2/
pylint --generate-rcfile > .pylintrc
# changed on .pylintrc => extension-pkg-whitelist=cv2
```

No complaints about cv2 now 😄 

Thanks (even if I found my way alone :p )

**Comment by metal3d** [comment]
Someone made it: https://github.com/bschnurr/python-type-stubs/tree/add-opencv/cv2

I have everything working with complete documentation and completion AFAIK:
```
curl -sSL https://raw.githubusercontent.com/bschnurr/python-type-stubs/add-opencv/cv2/__init__.pyi -o $(pipenv run python -c 'import cv2, os; print(os.path.dirname(cv2.__file__))')/cv2.pyi
```

**Comment by AnkushMalaker** [comment]
The method described by [metal3d](https://github.com/metal3d) worked for me using Conda environment as well.

**Comment by olejorgenb** [comment]
For PyCharm you can place the stubs anywhere [of you choosing](https://www.jetbrains.com/help/pycharm/stubs.html) (eg.: PROJECT_ROOT/.stubs/cv2/__init__.py and mark .stubs as sources root)

**Comment by evan0greenup** [comment]
@neelkarma , Since it is not difficult to generate typing stubs, why we don't simply generate a complete `*.pyi` files and prepackaged in `opencv-python`, It would be more convenient for all the users.

**Comment by hoel-bagard** [comment]
In case that can be of help to someone, I've begun to work on some OpenCV stubs that can be used until official ones ship with the OpenCV package. They are available on PyPI [here](https://pypi.org/project/opencv-stubs/).

They only include typing for some functions (like `imread`, `imread`, `imshow`, `cvtColor`, etc...), but I can add typing to any function/class if requested. Even the parts without typing can still be used for auto-completion purposes.

**Comment by hoel-bagard** [comment]
Until proper typing stubs are ready, you can use [this PyPI package](https://pypi.org/project/opencv-stubs/) to have some typing / auto-completion.

**Comment by alanwilter** [comment]
`mypy` is complaining about `cv2.CV_64F`

```
error: Module has no attribute "CV_64F"  [attr-defined]
```

**Comment by Avasam** [comment]
> Using CV2 v4.8.1 and `mypy` is complaining about `cv2.CV_64F`
> 
> ```
> error: Module has no attribute "CV_64F"  [attr-defined]
> ```

@alanwilter This issue is complete as stubs have been added. Please open a new issue for new static-typing problems. Your comment is likely to get lost w/o any action. Especially since your problem seems valid given that `cv2.CV_64F` exists at runtime but I cannot find a reference to it anywhere in the installed package.
