### ISSUE TITLE
about use the face detector model-resenet10_ssd300x300_fp16 error

### ISSUE THREAD

**Issue by lyp-deeplearning** [opencv/opencv#14595]
##### Detailed description

When i use the resnet10_ssd300x300_fp16model as a pretrained model to train a face detect model,there is a error occurs:
![image](https://user-images.githubusercontent.com/31647204/58152874-3ce89d80-7ca0-11e9-8a43-74b9359fd8c7.png)
My train.prototxt and test.prototxt are writed as the samples how to train your own model:https://github.com/opencv/opencv/tree/master/samples/dnn/face_detector。
So what can i do to solve this problem ,wishing for the anwers.

**Comment by dkurt** [comment]
This is OpenCV forum but not a Caffe one.

FP16 model is supported only by NVIDIA's Caffe because it's converted from FP32 model to it's format.

**Comment by lyp-deeplearning** [comment]
Thanks for your anwer. Your meaning is that  if i want to train a resnet10 face detector model ,i can not use the pretrained model.Because the opencv/dnn/samples/facedetector only provid a FP16 model and an init8 model.  I can not use this model as my pretrained model.
And the train speed is very slow ,your guide said that we can complete training 140000 iters 
in 8hours. Actually, i use my TITAN1080 train this model without pretrained model ,the speed is very slow,

**Comment by dkurt** [comment]
> Because the opencv/dnn/samples/facedetector only provid a FP16 model and an init8 model

No. Please find a FP32 model here: https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel

source: https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py

OpenCV team is not responsible for other training frameworks. Sorry.

**Comment by lyp-deeplearning** [comment]
Sorry, i have used the model you offer, but i can not run the net.forward calculation in my code.There is a very strange error:
my main code is as follow, i use the windows10+vs2017+opencv3.4 test the model:
 `int main(int argc, char** argv)
{
	CV_TRACE_FUNCTION();
	String modelConfiguration = "D:/code/C++/OpenCV-facedetector/facedelete/dnn_face_detectorcaffe/deploy.prototxt";
	String modelBinary = "D:/code/C++/OpenCV-facedetector/facedelete/dnn_face_detectorcaffe/res10_300x300_ssd_iter_140000.caffemodel";
    //! [Initialize network]
    dnn::Net net = readNetFromCaffe(modelConfiguration, modelBinary);
    if (net.empty())
    {
        cerr << "Can't load network by using the following files: " << endl;
        cerr << "prototxt:   " << modelConfiguration << endl;
        cerr << "caffemodel: " << modelBinary << endl;
        cerr << "Models are available here:" << endl;
        cerr << "<OPENCV_SRC_DIR>/samples/dnn/face_detector" << endl;
        cerr << "or here:" << endl;
        cerr << "https://github.com/opencv/opencv/tree/master/samples/dnn/face_detector" << endl;
		cout << "Couldn't open camera : " << endl;
		return -1;
    }
	Mat image;
	image = cv::imread("D:/work/opencv/sources/samples/data/lena.jpg");

	int bt = cv::getTickCount();
	//! [Prepare blob]
	//!  image: 3 channels
	Mat inputBlob = blobFromImage(image, inScaleFactor,
		Size(inWidth, inHeight), Scalar(128), false, false); //Convert Mat to batch of images

	net.setInput(inputBlob, "data"); //set the network input
	//! [Make forward pass]
	Mat detection = net.forward("detection_out"); //compute output`
The error is happend for the last code:  net.forward("detection_out")
![image](https://user-images.githubusercontent.com/31647204/58156445-ab315e00-7ca8-11e9-813c-ed8a6ee5991c.png)

So i am perplexed by this, the test code can run normaly if i use the fp16 resnet10 model, but can not run by the FP32 model. The deploy.protxt is just used your sample file 's deploy.prototxt.

**Comment by lyp-deeplearning** [comment]
And i have check my deploy.protxt ,the input channel is 1,3,300,300. So why does the error say my blob.size>3. But the same deploy.prototxt，i can run the resnet10_300x300_fp16 model perfectly!

**Comment by dkurt** [comment]
@lyp-deeplearning, please use http://answers.opencv.org/ for usage questions. We use issues to track bugs and feature requests.

This face detection model is tested so the problem in you r application.

**Comment by alalek** [comment]
@lyp-deeplearning

Please don't post text messages via screenshots. It is useless for searching of similar issues.

> 3.4.1

This release is very old (>1 year). Try latest OpenCV release or code from 3.4/master branch at first.

**Comment by lyp-deeplearning** [comment]
@alalek  Ok, I will put the information on the board. I have changed my version to opencv4.0, but the problem can not solve ,too.

**Comment by lyp-deeplearning** [comment]
@alalek should i just use the sample's deploy.prototxt?

**Comment by dkurt** [comment]
@lyp-deeplearning, Check https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py one more time please:

[deploy.prototxt](https://raw.githubusercontent.com/opencv/opencv/master/samples/dnn/face_detector/deploy.prototxt)  
[res10_300x300_ssd_iter_140000.caffemodel](https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel)

**Comment by lyp-deeplearning** [comment]
Sorry, I can not run this model .I always use the model https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel,
but the question has also happened on the net.forward.
My friend use the python run the model and deploy.prototxt occurs the same quetion, blob.size is error:
Traceback (most recent call last):
  File "mobilenet_ssd_python.py", line 49, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/layers/batch_norm_layer.cpp:36: error: (-215:Assertion failed) blobs.size() >= 2 in function 'BatchNormLayerImpl'
So i want to ask ,can you run it  when you use the res10_300x300_ssd_140000.model?
