### ISSUE TITLE
JPEG2000 support broken?

### ISSUE THREAD

**Issue by CSBVision** [opencv/opencv#14598]
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 10 and Linux (Ubuntu), both 64 Bit
- Compiler => Visual Studio 2015 / g++

##### Detailed description

I noticed that JPG2000 import seems not to work at all. I built OpenCV with JPEG2000 support

```
  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.35)
    TIFF:                        build (ver 42 - 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES
```

on both, Windows and Linux (Ubuntu), but loading does neither work with Python nor with C++ directly. With Python, the loaded image is printed as empty while cv::imread() returns an empty Mat (zero rows and columns). Interestingly, no error or exception is reported, the image is just empty.

Since I run into this issue on Linux and Windows I conjecture that the JPG2000 support is generally broken. If not, it would be interesting to know what is wrong with my build or how it could be fixed.

A sample image can be obtained from [here](http://www.gwg.nga.mil/ntb/baseline/software/testfile/Jpeg2000/jpeg2k.htm) and it could be loaded correctly with other tools supporting JPG2000.

##### Steps to reproduce

- Take a sample image, for instance download one from the link provided (I used the first one, file1.jpg2)
- loading it with Python produces an empty image:
    ```
    import cv2
    img = cv2.imread("/path/to/image.jp2")
    img #will be empty
    ```
- loading it with OpenCV produces an empty Mat:
    ```
    Mat img = cv::imread("/path/to/image.jp2")
    //img contains no data (zero rows and columns)
    ```

**Comment by alalek** [comment]
> Interestingly, no error or exception is reported

Check stdout/stderr output.

**Comment by CSBVision** [comment]
Thanks for the reply! I've also checked the stdout/stderr output, but there is nothing available (if there is, at least Python should print it, too?).

I tried to analyze the error in more detail and there seem to be multiple problems. The sample image mentioned now can be loaded, but only if its path is provided as an absolute path. So at least JPEG2000 generally seems to work.
However, I have single-channel JPEG2000 files from a third-party library (Matrox Imaging Library) that cannot be loaded with OpenCV, I also attached an example in case someone wants to reproduce the issue. Does OpenCV maybe only support multi-channel JPEG2000 files?

[sample.zip](https://github.com/opencv/opencv/files/3210810/sample.zip)

**Comment by alalek** [comment]
`imread` is our legacy from C API which can't throw exceptions. Adding exceptions will lead breaking of old applications.

Correct path for `imread()` is expected and we can't help here a lot. However, I agree that this is the most frequent problem of OpenCV users.

`OPENCV_LOG_LEVEL=INFO` environment variable may show extra messages (however `imgcodecs` module is not covered by logging well).

---

I found this gray [image](https://github.com/opencv/opencv_extra/blob/master/testdata/highgui/readwrite/Grey.jp2) in our test data.
So some gray images should be supported (probably 8-bit only).

JPEG2000 format is tricky enough and support in OpenCV is very limited.
Also it is disabled in runtime by default in latest releases (3.4.6/4.1.0): see #14058 for details.

**Comment by CSBVision** [comment]
Thanks for pointing out; the provided single-channel file works on my side, too. Maybe it has something to do with the exported files, but probably not with OpenCV. So for the moment everything seems to be ok, thanks!
