### ISSUE TITLE
visual studio opencv debug memory leak (false detection)

### ISSUE THREAD

**Issue by space03** [opencv/opencv#14593]
##### System information (version)

- OpenCV => :3.4.1 and 4.1.0 Tested
- Operating System / Platform =>Windows 7/ 
- Compiler => : Visual studio 2017 pro

##### Detailed description

Hi. I'm using opencv multiple projects. But I have a problem with using opencv.
When i use opencv, Opencv maeks memory leaks on debug mode, actually not real leak but false leak alarm.

Here is the leak script.
![cap](https://user-images.githubusercontent.com/41726365/58147271-b8dce880-7c94-11e9-95e7-dae1bd51af5b.PNG)

From searching, I found the sites(http://www.pklab.com/index.php?lang=EN&id=397) so I applied the method that using delay loaded DLL, but  it does not work.
(I cannnot use "Static link for MFC" because of my project environments.)

I know that this is not real leak but when i'm using debugging mode, it makes me annoying.
How can  I fix this problem??

Project Properties > Configuration Properties > Debugging> Environment > PATH=D:\Downloads\opencv\build\x64\vc15\bin;%PATH% 
Project Properties > Configuration Properties > C/C++>General >Additional Include Directories > D:\Downloads\opencv\build\include
Project Properties > Configuration Properties > Linker > General > Additional Library Directories > D:\Downloads\opencv\build\x64\vc15\lib
Project Properties > Configuration Properties > Linker > Input > Additional Dependencies > opencv_world410d.lib
Project Properties > Configuration Properties > Linker > Input > Delay Loaded Dlls > opencv_world410d.dll

##### Steps to reproduce

This is not my project code but it is same false leak using opencv.

// Here is the code
#include <opencv2/highgui.hpp>  
#include <opencv2/imgproc.hpp>  
#include <iostream>  

using namespace cv;
using namespace std;

#include <stdlib.h>
#include <crtdbg.h>

int main(int argc, char** argv)
{
	Mat img_original, img_gray;
	//Image Load  
	img_original = imread("1.jpg", IMREAD_COLOR);
	if (img_original.empty())
	{
		cout << "Could not open or find the image" << std::endl;
		return -1;
	}

	cout << "Open CV Version : " << CV_VERSION << std::endl;
	
	//Create Window 
	namedWindow("original image", WINDOW_AUTOSIZE);

	//Show in Window  
	imshow("original image", img_original);

	waitKey(0);

	_CrtDumpMemoryLeaks();
	return 0;
}

**Comment by space03** [comment]
@alalek 
Sorry for duplicate question.
But I could not find the exact solution for this issue. 
Please give me the answer.

**Comment by alalek** [comment]
We using this: https://github.com/opencv/opencv/blob/master/platforms/scripts/valgrind.supp

Feel free to port that on MSVS tooling.

Related issues: #5452 #6411 #9745 and others.
