### ISSUE TITLE
VideoCapture don't work with some cameras after Windows 10 update

### ISSUE THREAD

**Issue by andrey-parasich** [opencv/opencv#14604]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => MXE

##### Detailed description
VideoCapture don't work with some cameras after some Windows 10 update. It hangs on retrieving frame with >> operator, or returns empty black frame.

**Comment by andrey-parasich** [comment]
There is a VFW backend issue. It hangs in grabFrame() method, on capGrabFrameNoStop(capWnd) function.

**Comment by alalek** [comment]
> 3.4.0
> VFW

Consider using of MSMF or DShow backend instead.

VFW backend has been dropped from OpenCV 4.x.

Fresh versions OpenCV 3.4.x can disable VFW backend in runtime via environment variables (`OPENCV_VIDEOIO_PRIORITY_VFW=0`).

**Comment by andrey-parasich** [comment]
These backends refuses to work with my camera. So, if I disable VFW backend, nothing is streamed (vc.isOpen() return false after construction).

**Comment by andrey-parasich** [comment]
OpenCV search for DShow.h file, but MXE has only dshow.h file, so OpenCV cannot find file and do build without DSHOW, without any error message (but WITH_DSHOW flag is ON).

**Comment by mshabunin** [comment]
@andrey-parasich , enable option `ENABLE_CONFIG_VERIFICATION` to fail configuration step if any `WITH_*` option didn't enable corresponding dependency. Problem with `dshow.h` should've been fixed on _master_ branch ([here](https://github.com/opencv/opencv/pull/13422/files#diff-e13c8d50f116f4e43921763d773d05d1)) could you try it? If it works you can try to port it to 3.4.
