### ISSUE TITLE
error: expected class-name before ‘{’ token

### ISSUE THREAD

**Issue by LeisureLei** [opencv/opencv#14608]
error: expected class-name before ‘{’ token
error: expected class-name before ‘{’ token
error: ‘class MySVM’ has no member named ‘decision_func’
         return this->decision_func->alpha;
error: ‘class MySVM’ has no member named ‘decision_func’
         return this->decision_func->rho;
error: ‘class MySVM’ has no member named ‘load’
         svm.load(path.c_str());

**Comment by alalek** [comment]
There is no such code in OpenCV.
