### ISSUE TITLE
why the calibrated intrinsic matrix drifts a lot from the true value?

### ISSUE THREAD

**Issue by yyxr75** [opencv/opencv#14603]
##### System information (version)

- OpenCV => :3.2
- Operating System / Platform => :ubuntu18.04
- Compiler => :python3

##### Detailed description

Hello there,
I was using this demo to calibrate my own camera while the result showed a unacceptable drifts from the truth.
OpenCV version 3.2.0
Python version 3.6.7
The input images series is like below:

![Infrared1-00](https://user-images.githubusercontent.com/44866138/58236705-0c733300-7d76-11e9-8c6a-61a269b1be92.png)
and the circle detected images is
![outimg1](https://user-images.githubusercontent.com/44866138/58236736-1e54d600-7d76-11e9-9e0a-545cf062ce65.png)

There is one problem I am not that sure is, the asymmetric calibration target I used has a differently distance between the columns and rows which could be seen clearly from my code

[longerCalibrate.txt](https://github.com/opencv/opencv/files/3210974/longerCalibrate.txt)
Finally, the result of intrinsic calibration is

camera_matrix:
    [451.6701112652139, 0.0, 777.2304056394676]
    [0.0, 469.37232191132745, 321.2437268938009]
    [0.0, 0.0, 1.0]
dist_coeff:
    [-0.1705178885286108, 0.013773972732487686, 0.0012506566857040959, 0.004203751684462792,
    0.006202670677996154]

but actually, the intrinsic matrix should be
9.543190920000000000e+02 0.000000000000000000e+00 6.399660030000000000e+02 0.000000000000000000e+00 9.543190920000000000e+02 3.634058530000000000e+02 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00

this is correct because the resolution of these pictures is 1280x720, the second intrinsic matrix is more reasonable

So the question is, is there anything wrong with my code or is it a kernel problem of the opencv function?

Much appreciation

**Comment by yyxr75** [comment]
@alalek what does this mean? invalid tracker

**Comment by paroj** [comment]
the results are as to be expected.

see https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf Figure 3

**Comment by yyxr75** [comment]
> the results are as to be expected.
> 
> see https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf Figure 3

thanks for replying,
u gave me so much hope, I thought no one here would be willing to answer me at all.
I have read the article of Zhang, the truth is, the result returned by the opencv-calibration actually drifts a lot with the principle point at 
(777.2304056394676, 321.2437268938009)
while the principle points showed by the camera is at
(639.966003, 363.405853)
the second one is surely more acceptable because the camera resolution is (1280, 720)
and the principle points should be located in the center of the image plane as in most cases  I think.

Last time I use matlab-calibration as tool to calibrate my camera using symmetric calibration board(like chessboard etc.), it gave me a better result without such a large drift. (But it is said that the reprojecting error given by the matlab is 10 times bigger than the opencv result, that is why I want to use a new asymmetric board to do a new calibration.)
Don't you think it is a unacceptable result? Would you mind to tell me more about this? With so much appreciation!!

**Comment by alalek** [comment]
> the principle points should be located in the center of the image plane as in most cases I think

This is valid for high quality ideal cameras with ideal optics.
Usually it is not true and cameras differ (even between instances of the same model) - this is why we have calibration tool here.

> the principle points showed by the camera is at

Check the "reprojection error" for selected Camera model at first.
Or selected camera model (pinhole) is not corresponding to used camera device (also camera firmware may emulate "something" internally)

Also you must ensure that auto-focus functionality has been turned off (fixed focus to infinity) for your camera.

If you still think that calibration process is broken in OpenCV then you should provide reproducer (used images from the camera and calibration flags)

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by yyxr75** [comment]
> > the principle points should be located in the center of the image plane as in most cases I think
> 
> This is valid for high quality ideal cameras with ideal optics.
> Usually it is not true and cameras differ (even between instances of the same model) - this is why we have calibration tool here.
> 
> > the principle points showed by the camera is at
> 
> Check the "reprojection error" for selected Camera model at first.
> Or selected camera model (pinhole) is not corresponding to used camera device (also camera firmware may emulate "something" internally)
> 
> Also you must ensure that auto-focus functionality has been turned off (fixed focus to infinity) for your camera.
> 
> If you still think that calibration process is broken in OpenCV then you should provide reproducer (used images from the camera and calibration flags)
> 
> Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
> This tracker is for issues and bugs that needs fix in OpenCV.

thanks a lot,
I'm very willing to provide reproducer.
I will check the aspects you have mentioned and also upload all the used images for reproducing.
I totally agree with you that the principle points located in the center of the image plane is an ideal situation, and I also didn't expect such a good situation with my camera.
I'm pretty sure the pinhole model is suitable for my camera
Meanwhile, the focus length is not adjustable.
actually what I was calibrating is Intel-Realsense D415 depth camera and a thermal camera FLIR Tau-640.
Here I give the link of my images data

link：https://pan.baidu.com/s/1TipR35fOx_RcT_gx2iZHQQ 
Verification code：5uci

**Comment by paroj** [comment]
your calibration set is bad - it does not constrain the intrinsic parameters. See the following sequence for calibration poses that your set should include:
https://www.youtube.com/watch?v=aDzUNgVihdQ

**Comment by yyxr75** [comment]
> your calibration set is bad - it does not constrain the intrinsic parameters. See the following sequence for calibration poses that your set should include:
> https://www.youtube.com/watch?v=aDzUNgVihdQ

Ahhh.... I think I will try to shoot more pics in diff position

**Comment by yyxr75** [comment]
> your calibration set is bad - it does not constrain the intrinsic parameters. See the following sequence for calibration poses that your set should include:
> https://www.youtube.com/watch?v=aDzUNgVihdQ

So much appreciation to all of you,
Here I would like to point out 2 of my mistakes when doing the calibration.
First, I should not use the cv::cornerSubPix() in the code, as this is for the chessboard calibration in most situation.
Second, the position of calibration board should be more variable rather than just be slightly moved around the center of the image, and also shoot as many pics as possible for unavailability.
Thanks again
