### ISSUE TITLE
cv::dnn::Net::forward() documentation incomplete

### ISSUE THREAD

**Issue by mshtang** [opencv/opencv#14613]
It took me quite a while to figure out how does the `outputBlobs` look like. 
I found somewhere deep in a tutorial these comments:
https://github.com/opencv/opencv/blob/2080e06f7b17116a3e2b7d7905cb33942be73fd9/samples/dnn/object_detection.cpp#L329
```
// Network produces output blob with a shape 1x1xNx7 where N is a number of
// detections and an every detection is a vector of values
// [batchId, classId, confidence, left, top, right, bottom]
```
If  `outputBlobs` always has this shape, then this description found in the comment should go to the documentation of the method.

**Comment by alalek** [comment]
That format depends on used model and layer type (see `outLayerType == "DetectionOutput"` pre-condition).

`forward()` documentation is not going to handle/describe all possible network models.

**Comment by shazbits** [comment]
@alalek How can one find the output blob shape based on a model and layer type? Where does the 7 come from here?

**Comment by alalek** [comment]
> 7

Related documentation issue is here: #14645
Original idea is from Caffe [fork](https://github.com/weiliu89/caffe/blame/ssd/include/caffe/layers/detection_output_layer.hpp#L60). [Article](https://arxiv.org/abs/1512.02325)

**Comment by vermavinay982** [comment]
It may help, If someone is dealing with output issues from forward.

```
conf = inference_results[0, 0, i, 2]   # extract the confidence (i.e., probability) 
idx = int(inference_results[0, 0, i, 1])   # extract the index of the class label
boxPoints = inference_results[0, 0, i, 3:7]
```
