### ISSUE TITLE
Program abort when searching for max element in CV_16F

### ISSUE THREAD

**Issue by brtndr** [opencv/opencv#14624]
- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++

##### Detailed description
Hi. I've recently switched to opencv 4 to use new type CV_16F to load data in tensorflow. After inference I have packed tensorflow scores data into a cv::Mat *SCORES* of type CV_16FC1 with size MxN. *SCORES(i, j)* holds the probability for the object *i* to belong to class *j*.

To extract the class of each object I then proceeded to search the index of the max value for each raw by using  *cv::minMaxLoc*.

It appears that there is an issue with this function (maybe caused by the new type CV_16F) because it SIGSEGVs. As a turnaround I'm now converting the matrix to CV_32FC1 and perform the same search and everything is fine but it would be better to avoid this conversion.

##### Steps to reproduce
A simple program that generates a matrix of float32, converts it float16 then performs the search for the index of max in each row for both matices. The indexes should be the same.

```.cpp
#include <opencv2/imgproc.hpp>

int main(int argc, char** argv)
{
    cv::Mat float32(5, 10, CV_32FC1);
    cv::randu(float32, cv::Scalar(0), cv::Scalar(255));

    cv::Mat float16;
    float32.convertTo(float16, CV_16FC1);

    cv::Point max_idx16, max_idx32;

    for (size_t b = 0; b < float32.rows; b++)
    {
        cv::minMaxLoc(float32.row(b), nullptr, nullptr, &max_idx32, nullptr);
        cv::minMaxLoc(float16.row(b), nullptr, nullptr, &max_idx16, nullptr);

        assert(max_idx16.x == max_idx32.x);
    }

    return 0;
}
```

**Comment by alalek** [comment]
CV_16F data type support is very limited.
Only storage and conversion related operations are implemented.
Arithmetic/logic operations are not implemented and there are no plans to add them (to avoid exploding of OpenCV binaries).

> Program abort

This is not accurate.
Regular C++ exception has been raised due unsupported input type with the following message:

> modules/core/src/minmax.cpp:782: error: (-215:Assertion failed) func != 0 in function 'minMaxIdx'
