### ISSUE TITLE
What is the internal processing of the target detection module of opencv? Why is the speed fast?

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#14620]
I modified the darknet script test to handle video speed
[darknet.py](https://github.com/pjreddie/darknet/blob/master/python/darknet.py)
`if __name__ == "__main__":
    cfgPath = b'/home/AlexeyAB-darknet/YOLO-LITE-master/cfg/tiny-yolov2-trial3-noBatch.cfg'
    wightPath = b'/home/AlexeyAB-darknet/YOLO-LITE-master/weights/tiny-yolov2-trial3-noBatch.weights'
    dataPath = b'/home/AlexeyAB-darknet/YOLO-LITE-master/voc.names'
    net = load_net(cfgPath,wightPath, 0)
    meta = load_meta(dataPath)
    cap = cv2.VideoCapture('b.avi')
    suc,frame = cap.read()
    t0 = cv2.getTickCount()
    while suc:
        cv2.imwrite('temp.jpg',frame)
        r = detect(net, meta, b"temp.jpg")
        for classes,cofid,box in r:
            cv2.putText(frame,classes.decode(),(int(box[0]),int(box[1])),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),2)
            cv2.rectangle(frame,(int(box[0]-box[2]/2),int(box[1]-box[3]/2)),(int(box[0]+box[2]/2),int(box[1]+box[3]/2)),(0,255,0),2,1)
        t = (cv2.getTickCount()-t0)/cv2.getTickFrequency()
        fps = (1.0/t)
        str_time = '%.2f'%t
        str_fps = '%.2f'%fps
        cv2.putText(frame, str_time, (20, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
        cv2.putText(frame, str_fps, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255, 2)
        cv2.imshow('resule',frame)
        cv2.waitKey(1)
        suc,frame = cap.read()
        t0 = cv2.getTickCount()`

I use the following opencv code to test the video processing speed.
[object_detection_yolo.py](https://github.com/spmallick/learnopencv/blob/master/ObjectDetection-YOLO/object_detection_yolo.py)

I use the darknet test model to speed about 4FPS
BUT I can use opencv3 to load the model to reach 25FPS.

The device I am using：
ubuntu、i5cpu

1 What is the internal processing of the target detection module of opencv? Why is the speed fast?
2 Why are the predictions different?
opencv result：
![image](https://user-images.githubusercontent.com/21007783/58309245-4c015400-7e36-11e9-80d0-e4bfd0b88608.png)

 darknet result：
![image](https://user-images.githubusercontent.com/21007783/58309318-7b17c580-7e36-11e9-80fa-6bfa0d2bb507.png)

**Comment by dkurt** [comment]
Please use https://answers.opencv.org/ for usage questions. We use GitHub issues only for bugs and propose feature requests.
