### ISSUE TITLE
Error in YOLO object detection tutorial, forwardAsync does not exist anymore

### ISSUE THREAD

**Issue by doraemon96** [opencv/opencv#14625]
forwardAsync is not a method of Net as of v4 for sure. And I believe it was removed in version 3.4 or around there.
Who let the dogs out?

https://github.com/opencv/opencv/blob/166ecaeda814c654e680b489bb483042ff0b5df5/samples/dnn/object_detection.cpp#L216

**Comment by dkurt** [comment]
This is a new method. Looks like you copy-pasted sample from master branch and tried to compile with OpenCV 4.1.0.

So you need to use the version of sample for OpenCV 4.1.0: https://github.com/opencv/opencv/blob/4.1.0/samples/dnn/object_detection.cpp

**Comment by doraemon96** [comment]
Hmmm I'm not seeing those changes reflected on docs @dkurt
