### ISSUE TITLE
cvtColor memory leak

### ISSUE THREAD

**Issue by TMXY** [opencv/opencv#14639]
==14557==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14557==    by 0x40138B4: allocate_dtv (dl-tls.c:322)
==14557==    by 0x40138B4: _dl_allocate_tls (dl-tls.c:539)
==14557==    by 0xA21226E: allocate_stack (allocatestack.c:588)
==14557==    by 0xA21226E: pthread_create@@GLIBC_2.2.5 (pthread_create.c:539)
==14557==    by 0x81E7A4C: cv::WorkerThread::WorkerThread(cv::ThreadPool&, unsigned int) (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x81E90C1: cv::ThreadPool::reconfigure_(unsigned int) (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x81E9C87: cv::ThreadPool::run(cv::Range const&, cv::ParallelLoopBody const&, double) (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x81E56DC: cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x696CF66: cv::hal::cvtBGRtoGray(unsigned char const*, unsigned long, unsigned char*, unsigned long, int, int, int, int, bool) (in /usr/local/lib/libopencv_imgproc.so.4.0.1)
==14557==    by 0x696F605: cv::cvtColorBGR2Gray(cv::_InputArray const&, cv::_OutputArray const&, bool) (in /usr/local/lib/libopencv_imgproc.so.4.0.1)
==14557==    by 0x693F8D2: cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int) (in /usr/local/lib/libopencv_imgproc.so.4.0.1)

**Comment by alalek** [comment]
#14638
