### ISSUE TITLE
imdecode memory leak

### ISSUE THREAD

**Issue by TMXY** [opencv/opencv#14638]
==14557==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14557==    by 0x82467E9: cv::TLSDataContainer::TLSDataContainer() (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x824A978: cv::utils::trace::details::TraceManager::TraceManager() (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x824B23B: cv::utils::trace::details::getTraceManager() (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x824C268: cv::utils::trace::details::TraceManager::isActivated() (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x824DD69: cv::utils::trace::details::Region::Region(cv::utils::trace::details::Region::LocationStaticStorage const&) (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x5ECF636: cv::imdecode(cv::_InputArray const&, int) (in /usr/local/lib/libopencv_imgcodecs.so.4.0.1)

**Comment by alalek** [comment]
Use this file with OpenCV: https://github.com/opencv/opencv/blob/master/platforms/scripts/valgrind.supp

**Comment by anhtu812** [comment]
@alalek  How to use this file with OpenCV? Have OpenCV 4.1.0 fixed this issue? Thanks.
