### ISSUE TITLE
split memory leak

### ISSUE THREAD

**Issue by TMXY** [opencv/opencv#14640]
==14557==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14557==    by 0x8238AEF: cv::TLSData<cv::CoreTLSData>::createDataInstance() const (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x8245698: cv::TLSDataContainer::getData() const (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x8247B71: cv::ipp::useIPP() (in /usr/local/lib/libopencv_core.so.4.0.1)
==14557==    by 0x822B1EE: cv::split(cv::Mat const&, cv::Mat*) (in /usr/local/lib/libopencv_core.so.4.0.1)

**Comment by alalek** [comment]
#14638
