### ISSUE TITLE
dead link 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14644]
https://github.com/cdmh/deeplab-public is a dead link in https://docs.opencv.org/trunk/de/d56/classcv_1_1dnn_1_1InterpLayer.html

**Comment by mshabunin** [comment]
Shouldn't it be https://bitbucket.org/deeplab/deeplab-public or http://liangchiehchen.com/projects/DeepLab.html?
**cc** @dkurt

**Comment by dkurt** [comment]
Or https://github.com/cdmh/deeplab-public-ver2

**Comment by mshabunin** [comment]
Ok, the link should be changed to https://github.com/cdmh/deeplab-public-ver2
