### ISSUE TITLE
DetectionOutput layer doc

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14645]
FasterRCnn use DetectionOutput as inference results. In source code it is written

[        // num() and channels() are 1.
        // Since the number of bboxes to be kept is unknown before nms, we manually
        // set it to maximal number of detections, [keep_top_k] parameter multiplied by batch size.
        // Each row is a 7 dimension std::vector, which stores
// [image_id, label, confidence, xmin, ymin, xmax, ymax]](https://github.com/LaurentBerger/opencv/blob/6c6dd16acf47da980f1f33ce578b02868f112b47/modules/dnn/src/layers/detection_output_layer.cpp#L221-L222)

Can we add this comment in [detectionOutput layer doc](https://docs.opencv.org/trunk/da/dbd/classcv_1_1dnn_1_1DetectionOutputLayer.html)?

**Comment by harshajayaweeraXHJ** [comment]
Is this issue still open?

**Comment by MetalDent** [comment]
Hello, anyone working on this issue?

**Comment by tabaddor** [comment]
I'd like to look into this issue. Is there any other information I should know?
