### ISSUE TITLE
Wrong error message on SeamFinder::createDefault()

### ISSUE THREAD

**Issue by SciMad** [opencv/opencv#14646]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => 7.4.0

##### Detailed description
The error message for unsupported `SeamFinder` type on function  `SeamFinder::createDefault(int type)` in `stitching/src/seam_finders.cpp` seems is misleading. Seems to be copied from `ExposureCompensator::createDefault(int type)` at `stitching/src/exposure_compensate.cpp`.

**Comment by harsh020** [comment]
It seems like an easy first issue. If there is no open PR, can I please take this one?
