### ISSUE TITLE
NDK version support

### ISSUE THREAD

**Issue by xiaoxianggithub** [opencv/opencv#14653]
I have some problems when I tranplate opencv from pc to android ,So I would like to ask you some questions. in the source code of opencv 4.01 platforms/android/android.toolchain.cmake file ,it say  the highest NDK  version be support is r5-r10d,but I find it also could support higher  version than  r5-r10d,  Is this because there is no maintenance and modification? Or it just support to use r5-r10d NDK version?I would appreciate your reply at your convenience.

**Comment by Liujiangy1** [comment]
good boy!

**Comment by alalek** [comment]
Take a look on build scripts about used Android toolchain by default:

https://github.com/opencv/opencv/blob/4.1.0/platforms/android/build_sdk.py#L179

and on Android documentation: https://developer.android.com/ndk/guides/cmake

---

Mentioned legacy OpenCV's Android toolchain should not be used with NDK 16+.
