### ISSUE TITLE
There is a logical bug in dnn-tensorflow module in removing identity layer

### ISSUE THREAD

**Issue by summer-wing** [opencv/opencv#14656]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
In source file opencv/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp,line 750-761, lies the code below:
    for (int li = 0; li < layersCount; li++)
    {
        tensorflow::NodeDef* layer = net.mutable_node(li);
        for (int input_id = 0; input_id < layer->input_size(); input_id++) {
            String input_op_name = layer->input(input_id);
            IdentityOpsMap::iterator it = identity_ops.find(input_op_name);

            if (it != identity_ops.end()) {
                layer->set_input(input_id, it->second);
            }
        }
    }

These codes try to redirect the layers, replacing the original identity-input tensor with the input of identity-input. However, the developer might leave behind one special case, in which the input of an identity-input is still an identity layer. I mean, there may be 2 or more continuous identity operations in one net, and the codes above could not deal with this situation correctly. I came across this problem when I'm trying to use the Tensorflow-deeplab-mobilenetv2 model with opencv 4.1.0.
I think the line "layer->set_input(input_id, it->second);" should be modified with a while-loop to deal the continuous identity operations.

**Comment by dkurt** [comment]
> Tensorflow-deeplab-mobilenetv2

Please add a reference. If you want to report a bug you need to provide reproducer. Thanks!
