### ISSUE TITLE
build failure => 3.4.0

### ISSUE THREAD

**Issue by woniurensheng** [opencv/opencv#14658]
ystem information (version)
OpenCV => 3.2.0
Operating System / Platform => OSX Mojave
Compiler => 10.0.1.10010046
Python => 2.7.10
Cmake - 3.14.3

-- Performing Test HAVE_CPU_BASELINE_FLAGS
-- Performing Test HAVE_CPU_BASELINE_FLAGS - Failed
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:459 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:262 (ocv_compiler_optimization_options)
  CMakeLists.txt:526 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/../Desktop/face_sdk/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeOutput.log".
See also "/Users/../Desktop/face_sdk/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeError.log".
============================================================
ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_opencv_world=OFF', '-DBUILD_opencv_dynamic=OFF', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/yangxiao/Desktop/face/opencv-3.4.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/yangxiao/Desktop/face/opencv-3.4.0']' returned non-zero exit status 1

**Comment by alalek** [comment]
> OpenCV 3.2.0

has been released 2+ years ago. 3.4.0 has been released > 1 year ago.

So used dependencies

> Xcode 10 + OSX Mojave
> CMake 3.14.3

are newer than OpenCV release.

---

This case is not tested (and probably not supported).
Try modern OpenCV release instead or try code from 3.4/master branch.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
