### ISSUE TITLE
computeECC bug

### ISSUE THREAD

**Issue by quizzy5889** [opencv/opencv#14657]
##### System information (version)
- OpenCV => 4.1.0.25
- Operating System / Platform => macOS Mojave 10.14
- Interpreter => Python 3.7.1

#### Detailed description
From version 4.1.x there's the opportunity the compute the enhanced correlation coefficient between two images. It seems to me that it's not working correctly. My two images are very similar and I get an ECC=0.474. Just to test the functionality I also tried to run the operator on two identical images and it returns something like 0.475. I expected the same output of findTransformECC method that is actually 1.0 and an identity warp matrix.

##### Steps to reproduce
`retval = cv2.computeECC(templateImage=reference, inputImage=reference)`

**Comment by mshabunin** [comment]
**cc** @amithjkamath

**Comment by crackwitz** [comment]
here's a curious situation for v4.1.0 that might help hunt the problem down:
```
>>> A = np.random.randint(256, size=(100,100)); B = A.astype(np.uint8)
>>> (A == B).all()
True
>>> cv.computeECC(A, A); cv.computeECC(B, B)
1.0000207255989666
0.49794145277195634
```

**Comment by amithjkamath** [comment]
Thanks for fixing this, @danielenricocahall!

**Comment by danielenricocahall** [comment]
Glad to help! :)
