### ISSUE TITLE
blobFromImage and crop

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14659]
in blobFromImage it is possible to resize and crop image. blob generated can be used as input for yolo net. Values return by yolo are in a new coordinates system that must be computed using this code : 

```
            if crop:
                s = max([blob_width / img.shape[1], blob_height / img.shape[0]])
                r_blob = (int(0.5 / s * (int(img.shape[1] * s) - blob_width )),
                          int(0.5 / s * (int(img.shape[0] * s) - blob_height )),
                          int(blob_width / s),
                          int(blob_height / s))
            else:
                r_blob = (0, 0, img.shape[1], img.shape[0])

```
for yolov3 or yolov2 result.

new function would be Rect getBlobFromimagerect(Mat , Size ,  bool crop)

Is it  a good pr?

**Comment by alalek** [comment]
Perhaps related discussion: #14253

**Comment by dkurt** [comment]
I think that it's better to implement it inside a `cv::dnn::Model` class which is described in https://github.com/opencv/opencv/issues/14580. So if user passed `crop` as true, we must return bounding boxes in the origin frame coordinates. Thank you for proposal!

**Comment by skhadem** [comment]
Definitely doable, I will include it in `cv::dnn::Model`. It may be possible to do this automatically, by looking at difference between input image size and expected input size to net

**Comment by LaurentBerger** [comment]
I think sometime user need only which roi is iselected afer crop=true: example GoogLeNet

**Comment by dkurt** [comment]
@skhadem, in case of crop we need to map bounding boxes not to entire frame but to crop of it. So we need to check just `crop` value of `blobFromImage`.

**Comment by skhadem** [comment]
Oh that does make sense now. That would make sense and have good use cases I think

**Comment by themechanicalcoder** [comment]
@dkurt can I work on this issue.

**Comment by dkurt** [comment]
@themechanicalcoder, Yes, please extend `cv::dnn::DetectionModel` so it can consider `crop`

**Comment by themechanicalcoder** [comment]
@dkurt 
1) I think blobFromImage() and blobFromImages() are needed.

**Comment by asmorkalov** [comment]
The proposal (resize, crop) implemented in https://github.com/opencv/opencv/pull/22750. See documentation: https://docs.opencv.org/4.x/d9/d3c/structcv_1_1dnn_1_1Image2BlobParams.html

**Comment by asmorkalov** [comment]
You cannot. I got the problem and re-opened the bug.
