### ISSUE TITLE
Is there any way to free or delete <Stitcher> object?

### ISSUE THREAD

**Issue by Lunashiel** [opencv/opencv#14669]
##### System information (version)

- OpenCV => 4.1.0 / C++
- Operating System / Platform => Windows 10 64 Bit
- Compiler => (IDE)MS Visual Studio 2015(VC14)

### **Is there any way to free or delete Stitcher object?**
I studied opencv library to stitch aerial images taken by drone.
After loading images, creating stitcher object using
'Ptr<Stitcher> stitcher =Stitcher::create(Stitcher::SCANS)'
and stitching images, I want to release my memory used for image stitching.
So, at the end of the code, I called **'delete stitcher' or 'free(stitcher)'**.

But, when my program execute 'delete stitcher' or 'free(stitcher)', it became crashed.
If I didn't use those ways, some parts of memory occupied by the program still remained.

**So, I want to know how to release memory when using high level API Stitcher Class.   
And also, if someone has an effective way to remove the image variables that are left in memory, please let me know how.**

##### Steps to reproduce

```
**// Setting variables**
vector<Mat> imgs;
Mat result;
vector<string> imgPaths;
string resultPath;

**// Setting image paths**
(..............)//(add several image paths to imgPaths)

**// Adding images to image vector**
for(int i = 0; i < nImages; i++){
    Mat inputImage;
    inputImages = imread(imgPaths[i]);
    imgs.push_back(inputImage.clone());
} //(load images more than 20~50 pictures into vectors...)

**// Creating Stitcher object and Stitching Images**
Ptr<Stitcher> stitcher = Stitcher::create(Stitcher::SCANS)
stitcher->setFeaturesFinder(ORB::create(1000));
Stitcher::Status status = stitcher->stitch(imgs, result);

**// Writing result images**
imwrite(resultPaths+".jpg", result);

**// Releasing Images**
result.release();
for(Mat image : imgs) image.release();
vector<Mat>().swap(imgs);
**delete stitcher;** //<- **ERROR OCCURED!**
```

**Comment by alalek** [comment]
`stitcher.release();`

**Comment by Lunashiel** [comment]
After finishing the program works, i found that unreleased memories still exists.
How can I initialize the remaining memory after the program is finished?

https://www.youtube.com/watch?v=NpS4reYXbh4

after finishing stitch process, lots of memory still exist.....(578.9MB)
