### ISSUE TITLE
Cannot import cv2 in python3, libopencv_hdf3.so.3.3 not find

### ISSUE THREAD

**Issue by Gloriabhsfer** [opencv/opencv#14681]
Hi:
I am doing a project with openpose the CUDA version is 10.0.
##### System information (version)

- OpenCV => :3.4.4
- Operating System / Platform => :Ubuntu 16.04
- Compiler => :python3

##### Detailed description
When I installed build opencv from source code with cmake, and test it with 
`import cv2 as cv`
it will give me error like this:
`ImportError: libopencv_hdf3.so.3.3: cannot open shared object file: No such file or directory    `

##### Steps to reproduce
It seems lack the  package `libopencv_hdf3.so.3.3` so I searched it online but find nothing. And I used  find command in ubuntu to find `libopencv_hdf*`, it doesn't contained the `hdf3` version
I have no idea about this problem, hope someone can gave me some idea.
Best,
Gloria

**Comment by alalek** [comment]
> OpenCV => 3.4.4
> ImportError: libopencv_hdf3.so.3.3

You have mess with OpenCV installations on your machine. You should resolve this at first.

`hdf` is [opencv_contrib](https://github.com/opencv/opencv_contrib/tree/master/modules/hdf) module.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
