### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.1.0) /Volumes/build-storage/build/master_iOS-mac/opencv/modules/core/src/utils/filesystem.cpp:571: error: (-213:The function/feature is not implemented)  in function 'canonical'

### ISSUE THREAD

**Issue by wanggao1990** [opencv/opencv#14698]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => IOS 12

##### Detailed description
The crash occurs when running one line code.
` std::cout << cv::utils::fs::canonical("./")  << std::endl;`

After catch the exception, 
```
    try {
        std::cout << cv::utils::fs::canonical("./")  << std::endl;
    } catch (const std::exception& e) {
        std::cout << e.what() <<std::endl;
    }
```
This error also occurs:
OpenCV(4.1.0) /Volumes/build-storage/build/master_iOS-mac/opencv/modules/core/src/utils/filesystem.cpp:571: error: (-213:The function/feature is not implemented)  in function 'canonical'

When I add -fvisibility=hidden to "Other C++ flags" in Build Settings, the error and crash appeared again.

**Comment by alalek** [comment]
> The function/feature is not implemented

There is no iOS implementation of filesystem routines in OpenCV.
There is no plans to add them in the nearest future, so fell free to contribute if you want them.

**Comment by wanggao1990** [comment]
thanks.

**Comment by zimenglan-sysu-512** [comment]
hi @wanggao1990, how did u solved it?

**Comment by wanggao1990** [comment]
@zimenglan-sysu-512   
The original intention is to write a cross platform visual processing library that can be used universally. It turn out thatcv::utils::fs::canonical cannot be work well on IOS. The directories that IOS can read and write with permission were basically fixed. 
 For catching up with timepoint, I wrote an interface for IOS application to provide directories and ensure the existence of directories in the end.   -_-!
