### ISSUE TITLE
OpencCV.js: Add missing fillPoly() and fillConvexPoly() functions

### ISSUE THREAD

**Issue by dmandrioli** [opencv/opencv#14690]
These two functions are missing in OpenCV.js. 

It's currently possible to simulate fillConvexPoly() with drawContours() but it's verbose and not very convenient.

**Comment by thangktran** [comment]
i'm working on this issue.

**Comment by thangktran** [comment]
@dmandrioli could you please test this patch.

**Comment by WangYundong** [comment]
Hello~ this function in opencv.js, can help draw lines for vetices, but can't fill the content. Do you have methods to solve this problem ?

**Comment by WangYundong** [comment]
The details for my question can be found from #22323

**Comment by WangYundong** [comment]
Hello~ @dmandrioli @alalek @thangktran Help me, please
