### ISSUE TITLE
cv::Transform SIMD incorrect output when done in place (issue for 3.4.6, does not happen in 3.4.5)

### ISSUE THREAD

**Issue by zhumxcq** [opencv/opencv#14727]
##### System information (version)
General configuration for OpenCV 3.4.6 =====================================
  Version control:               unknown

  Platform:
    Timestamp:                   2019-05-17T20:01:53Z
    Host:                        Windows 6.1.7601 AMD64
    CMake:                       3.9.0
    CMake generator:             Visual Studio 14 2015
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE2
      required:                  SSE SSE2 SSE3
      disabled:                  SSSE3 SSE4_1 SSE4_2 POPCNT AVX AVX2 FMA3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
      SSE4_1 (12 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (26 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++11:                       YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe  (ver 19.0.24215.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast   /arch:SSE /arch:SSE2   /arch:SSE /arch:SSE2  /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP4   /MD /O2 /Ob2 /D NDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast   /arch:SSE /arch:SSE2   /arch:SSE /arch:SSE2  /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP4   /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast   /arch:SSE /arch:SSE2   /arch:SSE /arch:SSE2    /MP4    /MD /O2 /Ob2 /D NDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi /fp:fast   /arch:SSE /arch:SSE2   /arch:SSE /arch:SSE2    /MP4  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:X86  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:X86  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc ml objdetect photo shape stitching superres ts video videoio videostab
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java js python2 python3 viz
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI: 
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.36)
    TIFF:                        build (ver 42 - 4.0.10)
    OpenEXR:                     build (ver 1.7.1)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES

  Video I/O:
    Video for Windows:           YES
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.107.100)
      avformat:                  YES (ver 57.83.100)
      avutil:                    YES (ver 55.78.100)
      swscale:                   YES (ver 4.8.100)
      avresample:                YES (ver 3.7.0)
    PvAPI:                       NO
    DirectShow:                  YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2019.0.0 Gold [2019.0.0]
           at:                   E:/Documents/opencv/build-86/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2019.0.0)
              at:                E:/Documents/opencv/build-86/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   NO

  OpenCL:                        YES (NVD3D11)
    Include path:                E:/Documents/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            NO

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    E:/Documents/opencv/build-86/install
-----------------------------------------------------------------

##### Detailed description
Compiled as 32-bit (x86) on 64-bit platform, when cv::transform is done in-place, the results are wrong (see attached picture).
CPU is Intel i5-3570

##### Steps to reproduce
```.cpp
{
		cv::Mat t = (cv::Mat_<double>(3, 3) << 575.7921, 0, 325.8341, 0, 575.2544, 244.8807, 0, 0, 1);
		std::vector<cv::Vec3f> pts(2), pts_out;
		pts[0] = cv::Vec3f(151226, 364400, 1822);
		pts[1] = cv::Vec3f(1032900, 525840, 1878);
		std::cout << "Input: " << std::endl << pts[0] << std::endl << pts[1] << std::endl << std::endl;
		std::cout << "Transform: " << std::endl << t.inv() << std::endl << std::endl;
		cv::transform(pts, pts_out, t.inv());
		std::cout << "Correct output: " << std::endl << pts_out[0] << std::endl << pts_out[1] << std::endl << std::endl;
		cv::transform(pts, pts, t.inv());
		std::cout << "Incorrect output (in place): " << std::endl << pts[0] << std::endl << pts[1] << std::endl << std::endl;
}
```
![image](https://user-images.githubusercontent.com/10454438/58971898-63233880-878a-11e9-9a2d-056fec19bb23.png)

**Comment by zhumxcq** [comment]
Sorry this should be the correct code block
```.cpp
cv::Mat t = (cv::Mat_<double>(3, 3) << 575.7921, 0, 325.8341, 0, 575.2544, 244.8807, 0, 0, 1);
std::vector<cv::Vec3f> pts(2), pts_out;
pts[0] = cv::Vec3f(151226, 364400, 1822);
pts[1] = cv::Vec3f(1032900, 525840, 1878);
std::cout << "Input: " << std::endl << pts[0] << std::endl << pts[1] << std::endl << std::endl;
std::cout << "Transform: " << std::endl << t << std::endl << std::endl;
cv::transform(pts, pts_out, t.inv());
std::cout << "Correct output: " << std::endl << pts_out[0] << std::endl << pts_out[1] << std::endl << std::endl;
cv::transform(pts, pts, t.inv());
std::cout << "Incorrect output (in place): " << std::endl << pts[0] << std::endl << pts[1] << std::endl << std::endl;
```

**Comment by rrodrigues** [comment]
This happens to me as well but on 4.1.1.

Not with the same steps. I discover it in another way:

##### System information (version)
```
-- General configuration for OpenCV 4.1.1 =====================================
--   Version control:               4.1.1
-- 
--   Extra modules:
--     Location (extra):            ../opencv_contrib-github/modules
--     Version control (extra):     4.1.1
-- 
--   Platform:
--     Timestamp:                   2019-09-25T08:25:51Z
--     Host:                        Darwin 18.7.0 x86_64
--     CMake:                       3.15.3
--     CMake generator:             Ninja
--     CMake build tool:            /usr/local/bin/ninja
--     Configuration:               RelWithDebInfo
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3 SSSE3 SSE4_1
--       requested:                 DETECT
--     Dispatched code generation:  SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_2 (1 files):          + POPCNT SSE4_2
--       FP16 (0 files):            + POPCNT SSE4_2 FP16 AVX
--       AVX (4 files):             + POPCNT SSE4_2 AVX
--       AVX2 (27 files):           + POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (2 files):      + POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 11.0.0.11000033)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,-dead_strip  
--     Linker flags (Debug):        -Wl,-dead_strip  
--     ccache:                      YES
--     Precompiled headers:         NO
--     Extra dependencies:
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann freetype fuzzy gapi hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab world xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    cvv
--     Disabled by dependency:      -
--     Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev hdf java js matlab ovis python2 sfm ts viz
--     Applications:                apps
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   GUI: 
--     QT:                          YES (ver 5.13.0)
--       QT OpenGL support:         NO
--     Cocoa:                       YES
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        build (ver 1.2.11)
--     JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         build (ver 1.6.37)
--     TIFF:                        build (ver 42 - 4.0.10)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 2.3.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (58.54.100)
--       avformat:                  YES (58.29.100)
--       avutil:                    YES (56.31.100)
--       swscale:                   YES (5.5.100)
--       avresample:                YES (4.0.0)
--     GStreamer:                   NO
--     AVFoundation:                YES
-- 
--   Parallel framework:            GCD
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Intel IPP:                   2019.0.0 Gold [2019.0.0]
--            at:                   <>/3rdparty/ippicv/ippicv_mac/icv
--     Intel IPP IW:                sources (2019.0.0)
--               at:                <>/3rdparty/ippicv/ippicv_mac/iw
--     Lapack:                      YES (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework)
--     Eigen:                       NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                NO
--     Link libraries:              -framework OpenCL
-- 
--   Python 3:
--     Interpreter:                 /usr/local/bin/python3 (ver 3.7.4)
--     Libraries:                   /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (ver 3.7.4)
--     numpy:                       /usr/local/lib/python3.7/site-packages/numpy/core/include (ver 1.17.2)
--     install path:                lib/python3.7/site-packages/cv2/python-3.7
-- 
--   Python (for build):            /usr/local/bin/python3
-- 
--   Java:                          
--     ant:                         NO
--     JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Headers
--     Java wrappers:               NO
--     Java tests:                  NO
```

##### Steps to reproduce

```.cpp
    std::vector<cv::Point3f> points = {
        {141, 162, 1 },
        {138, 165, 1 },
        {138, 201, 1 },
        {141, 201, 1 },
        {174, 168, 1 },
        {174, 162, 1 },
    };

    cv::Point center = std::accumulate(points.begin(), points.end(), cv::Point(), [](cv::Point p, cv::Point3f q) { return p + cv::Point(q.x, q.y); });
    center.x /= points.size();
    center.y /= points.size();

    float expandFactor = 1.1f;
    cv::Mat scale = (cv::Mat_<double>(3,3) << expandFactor, 0, 0, 0, expandFactor, 0, 0, 0, 1);
    cv::Mat translation = (cv::Mat_<double>(3,3) << 1, 0, center.x, 0, 1, center.y, 0, 0, 1);
    cv::Mat T = translation * scale * translation.inv();

    std::cout << "T: " << std::endl << T << std::endl;

    std::vector<cv::Point3f> wrongOut = points;
    cv::transform(wrongOut, wrongOut, T);

    std::vector<cv::Point3f> goodOut = points;
    cv::transform(points, goodOut, T);

    std::cout << T << std::endl;
    for (size_t index = 0; index < points.size(); ++index) {
        std::cout << "Expected:  " << goodOut[index] << std::endl;
        std::cout << "Result:    " << wrongOut[index] << std::endl;
    }

```


##### Output

```
T: 
[1.100000023841858, 0, -15.10000360012054;
 0, 1.100000023841858, -17.60000419616699;
 0, 0, 1]
[1.100000023841858, 0, -15.10000360012054;
 0, 1.100000023841858, -17.60000419616699;
 0, 0, 1]
Expected:  [140, 160.6, 1]
Result:    [140, 160.6, 1]
Expected:  [136.7, 163.9, 1]
Result:    [136.7, 163.9, 1]
Expected:  [136.7, 203.5, 1]
Result:    [-15.1, -17.6, 1]
Expected:  [140, 203.5, 1]
Result:    [140, 203.5, 1]
Expected:  [176.3, 167.2, 1]
Result:    [-15.1, -17.6, 1]
Expected:  [176.3, 160.6, 1]
Result:    [176.3, 160.6, 1]
```
