### ISSUE TITLE
Eigen core missing during installation

### ISSUE THREAD

**Issue by ashneg** [opencv/opencv#14723]
![Screenshot from 2019-06-05 04-00-20](https://user-images.githubusercontent.com/44631967/58918202-efac0780-8746-11e9-8d83-f4e61e5b19eb.png)

##### System information (version)

- OpenCV => 3.1
- Operating System / Platform =>  Linux 4.18.0-kali2-amd64
- Compiler => g++ 8.3.0

##### Detailed description

Not able to execute the make command ,as it is showing
` #  include <Eigen/Core>`
No such directory exists

##### Steps to reproduce

Installation steps were taken from this [installation steps](https://www.learnopencv.com/install-opencv-4-on-ubuntu-16-04/)

and the make command was this

`cmake -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=$cwd/installation/OpenCV-"$cvVersion" \
            -D INSTALL_C_EXAMPLES=ON \
            -D INSTALL_PYTHON_EXAMPLES=ON \
            -D WITH_TBB=ON \
            -D WITH_V4L=ON \
            -D OPENCV_PYTHON3_INSTALL_PATH=$cwd/OpenCV-$cvVersion-py3/lib/python3.5/site-packages \
        -D WITH_QT=ON \
        -D WITH_OPENGL=ON \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D BUILD_EXAMPLES=ON ..`

Please describe the make command for successful build

**Comment by benzwt** [comment]
You need to use the eigen source code published by http://eigen.tuxfamily.org/index.php?title=Main_Page
Get the package, unpack and add the option
-DEIGEN_INCLUDE_PATH='your eigen directory' to cmake

You could also clone the source with 
hg clone https://bitbucket.org/eigen/eigen/
Thus, you don't have to download the latest version, manually

**Comment by alalek** [comment]
Probably problem is related to broken support of precompiled headers (PCH) with GCC 6+.
Outdated OpenCV 3.1 doesn't have fixes for that.
See #6541

Update used OpenCV version or disable PCH.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Avoid posting of text information via screenshots. It is useless for searching of similar issues.

**Comment by akshay-c** [comment]
Hi,
    I faced this issue recently. I have eigen3 installed and the include files are located under /usr/include/eigen3. So I decided to back trace the problem. The file " [OpenCVFindLibsPerf](https://github.com/opencv/opencv/blob/master/cmake/OpenCVFindLibsPerf.cmake)" at around line 46: tries to append the linker flags and sets "HAVE_EIGEN" flag without appropriate Eigen Include path set(${EIGEN_INCLUDE_PATH}). You may want to set the include directories before  "HAVE_EIGEN" flag. Simply commenting line 50 causes it to compile. But I believe it is not the right way.
