### ISSUE TITLE
Differences between maths with Mat and MatExpr

### ISSUE THREAD

**Issue by awebb-nz** [opencv/opencv#14738]
There seems to be inconsistencies in mathematical expressions that create `MatExpr`s. 

##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => macOS 10.13.6
- Compiler => clang-1000.11.45.5

##### Detailed description

I have been trying to use opencv to do some image processing, and I have found an inconsistency between using Mat and MatExpr. 

##### Steps to reproduce

Specifically, in the following code, I would expect the output in both cases to be the same:
```.cpp
Mat m(1, 1, CV_32FC3, 1);
Mat n = m.clone();

Mat temp = m * 5;
temp = temp + 10;
std::cout << temp << std::endl;

Mat temp2 = n * 5 + 10;
std::cout << temp2 << std::endl;
```

However, the output I get is:
```
[15, 0, 0]
[15, 10, 10]
```
There have been some similar previous issues ([#9688](https://github.com/opencv/opencv/issues/9688) [#9720](https://github.com/opencv/opencv/issues/9720)), but those are both a bit older, and I am not sure they show the same issues.

**Comment by alalek** [comment]
It make sense to make both code paths provide the same result, but unfortunately there is no well defined result (what is case correct here?).
So code is ambiguous initially with multi-channel Mat.

1. Did you try to replace "10" to `Scalar(10)` / `Scalar:all(10)`?
2. `1` -> `Scalar::all(1)` ?


> Mat m(1, 1, CV_32FC3, 1);

Be careful, avoiding Scalars here:
- `Mat m(1, 1, CV_32FC3, 0);` - doesn't not work at all (`0` is used as `(void *)0` instead `Scalar(0)`).
- there is plan to ban overload with `int`, so this code will not compile.

**Comment by alalek** [comment]
Lets track this issue here: #16739
