### ISSUE TITLE
Ubuntu OpenCV Install instructions has incorrect dependencies?

### ISSUE THREAD

**Issue by IanMaquignaz** [opencv/opencv#14731]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu
- Compiler => N/A but gcc, g++

##### Detailed description

OpenCV install instructions in the docs asks users to install non-existent libraries. See: https://docs.opencv.org/4.1.0/d2/de6/tutorial_py_setup_in_ubuntu.html

The following libraries don't exist in the default Ubuntu apt-get repositories:
[What they are] -> [What they should be]
python-devel  -> python-dev
numpy            -> python-numpy
gcc                 -> OK
gcc-c++          -> g++ 
gtk2-devel       
ffmpeg-devel
gstreamer-plugins-base-devel
libpng-devel 
libjpeg-turbo-devel
jasper-devel
openexr-devel
libtiff-devel
libwebp-devel

**Comment by jxu** [comment]
Yeah this one is more up-to-date https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

**Comment by IanMaquignaz** [comment]
Can we fix this? It's the first result from the OpenCV Docs when you put "install opencv ubuntu" into google
