### ISSUE TITLE
opencv.js: face recognition sample doesn't work for the WASM version of opencv.js

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [opencv/opencv#14734]
##### System information (version)

- OpenCV => opencv.js 4.1.0-dev
- Operating System / Platform => Version 74.0.3729.157 (Official Build) unknown (64-bit)
- Compiler => opencv.js WASM build from master branch as described [here](https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html).

##### Detailed description

Now the [sample of face recognition with opencv.js](https://docs.opencv.org/master/d5/d86/tutorial_dnn_javascript.html) just work for the asm.js version of, and doesn't work for the WASM version of opencv.js, saying `cv.Mat is not a constructor` in the console.log. Seems we need `cv.onRuntimeInitialized=()=>{}` for the loading of opencv.js WASM. 

##### Steps to reproduce

Go to [here](https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html)

**Comment by dkurt** [comment]
@Wenzhao-Xiang, Thank you!

Feel free to open a PR. I think that's even better to use `loadOpenCv` from `utils.js` because it can manage both versions.

**Comment by Wenzhao-Xiang** [comment]
> I think that's even better to use `loadOpenCv` from `utils.js`

Sounds good to me! where should I modify the file? Just in https://github.com/opencv/opencv/blob/master/samples/dnn/js_face_recognition.html?

**Comment by dkurt** [comment]
@Wenzhao-Xiang, yes, this one.
