### ISSUE TITLE
opencvforandroid DNN模块使用OPENCL奔溃

### ISSUE THREAD

**Issue by lhxy1991** [opencv/opencv#14753]
编译opencv3.4.3版本带OPENCL的，测试能够检测到opencl，但是当运行DNN模块net.forword（output）函数就会导致系统奔溃，用官网的Android SDK版本的CPU版本是正常的

芯片是imx8Q  ,opencl 1.2.
请问是编译问题还是版本问题？

**Comment by dkurt** [comment]
@lhxy1991, Sorry but we don' understand Chinese :smile: . Please try to translate it to English if it's a bug report or use http://www.opencv.org.cn/ if it's a question.

**Comment by lhxy1991** [comment]
I build opencv3.4.3 to android  with opencl , I can detect GPU by using ocl::haveOpenCL()), but when i use DNN to detect object with YOLO_Lite ,it crash at  function: net.forword(output) .However  when I use your SDK ,i can get result. My chip is IMX8Q 。
Can you help me ?

**Comment by alalek** [comment]
> crash

Stack trace is required.

> your SDK

What is it?

---

Try to run OpenCV tests at first (including core module - it has testing for basic OpenCL functionality).

**Comment by lhxy1991** [comment]
05-23 08:14:24.409 32322 32322 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffffc
05-23 08:14:24.409 32322 32322 F DEBUG   :     r0  00000000  r1  00000001  r2  00000000  r3  fffffff8
05-23 08:14:24.409 32322 32322 F DEBUG   :     r4  b6afea00  r5  00000144  r6  00000140  r7  0000013c
05-23 08:14:24.409 32322 32322 F DEBUG   :     r8  a2500dc0  r9  ab7ddf80  r10 a2500e30  r11 ac84d850
05-23 08:14:24.409 32322 32322 F DEBUG   :     ip  ed634d00  sp  a2500da0  lr  a43c9f4b  pc  a43cf8b0
05-23 08:14:24.415 32322 32322 F DEBUG   : 
05-23 08:14:24.415 32322 32322 F DEBUG   : backtrace:
05-23 08:14:24.415 32322 32322 F DEBUG   :     #00 pc 0059d8b0  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #01 pc 0059e6a9  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #02 pc 0059e90f  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #03 pc 005568bb  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #04 pc 00557367  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #05 pc 005443db  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #06 pc 0054536b  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so
05-23 08:14:24.415 32322 32322 F DEBUG   :     #07 pc 00548f87  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libopencv_java3.so (cv::dnn::experimental_dnn_34_v7::Net::forward(cv::String const&)+134)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #08 pc 00016078  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libimageproc.so (ImageProcessor::classify(cv::Mat)+380)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #09 pc 00015650  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libimageproc.so (ImageProcessor::DoCarDetected(cv::Mat)+428)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #10 pc 00014328  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libimageproc.so (ImageProcessor::do_CarDetect(_JNIEnv*)+1360)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #11 pc 000131d4  /data/app/com.pateonavi.naviapp-QvoCpljLBcYiUoWcQ9WmDg==/lib/arm/libimageproc.so (ImageProcessor::processor_thread_fCarDetect(void*)+144)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #12 pc 00063c35  /system/lib/libc.so (__pthread_start(void*)+22)
05-23 08:14:24.415 32322 32322 F DEBUG   :     #13 pc 0001e085  /system/lib/libc.so (__start_thread+22)
