### ISSUE TITLE
Android, ndk-20, clang

### ISSUE THREAD

**Issue by crazyhappygame** [opencv/opencv#14762]
Hi,

Is there any chance to upgrade Android build process to latest ndk-20? 

Gcc is not supported for couple of ndk releases
 Ndk10 is more than 4 years old.

Please provide here Android pack build with latest ndk-20 and clang:
https://opencv.org/releases/

**Comment by crazyhappygame** [comment]
@alalek did you have chance to work on that?

**Comment by alalek** [comment]
Try OpenCV 4.x.

OpenCV 3.x is stuck with its dependencies. No plans to change these releases.

Custom builds with modern NDKs are possible, like:
https://github.com/opencv/opencv/blob/3.4/platforms/android/ndk-17.config.py

but they are very limited on 3.x branch (no Java support, no samples - native C++ binaries only).

**Comment by crazyhappygame** [comment]
"Try OpenCV 4.x." - what ndk, compiler is used for 4.x ? What is in official 4.1.0 release?
https://sourceforge.net/projects/opencvlibrary/files/4.1.0/opencv-4.1.0-android-sdk.zip/download

**Comment by alalek** [comment]
http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/10779
```
Package configuration:
================================================================================
ABIs = [
    ABI("2", "armeabi-v7a", None, 21, cmake_vars=dict(ANDROID_ABI='armeabi-v7a with NEON')),
    ABI("3", "arm64-v8a",   None, 21),
    ABI("5", "x86_64",      None, 21),
    ABI("4", "x86",         None, 21),
]
================================================================================
Android NDK path: /opt/android/android-ndk-r18b/
Android SDK path: /opt/android/android-sdk.gradle/

...

C++ Compiler:                /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  (ver 7.0)
```

**Comment by crazyhappygame** [comment]
Thank you.

I see only one problem with current configuration: AndroidSdk=21. 
Could you explain why 21 is used? 

I think that it should be changed to 16. Sdk 16 is the oldest supported android sdk. With 21 it means that we may have undefined behaviour on devices older than 21(android 5.0)

**Comment by alalek** [comment]
Android 21 is needed to bring new features to OpenCV Users:
- Media NDK for reading video files from C++ code (useful for tests)
- Camera2 Java API

Android API 16 can be built too, see [ndk-18.config.py](https://github.com/opencv/opencv/blob/4.1.0/platforms/android/ndk-18.config.py).
However it is not tested for now.

**Comment by crazyhappygame** [comment]
Thank you for clarification. I will build opencv my self
