### ISSUE TITLE
Support for Mean layer (Can't create layer "34" of type "ReduceMean")

### ISSUE THREAD

**Issue by Aeroxander** [opencv/opencv#14768]
##### System information (version)

- OpenCV => 4.1.0 C++
- Operating System / Platform => Windows 10
- Compiler => Visual Studio

##### Detailed description

I'm currently getting this error with a model ([another one than this one](https://github.com/opencv/opencv/issues/14713)): "Can't create layer \"34\" of type \"ReduceMean\"".
Is the ReduceMean layer not supported in OpenCV?

I could try to add a custom ReduceMean layer to OpenCV DNN myself..

##### Steps to reproduce
Load a model with a ReduceMean layer

**Comment by dkurt** [comment]
Looks like this is an ONNX model, right? @l-bat, May I ask you to take a look? Thanks!

**Comment by Aeroxander** [comment]
Correct this is an ONNX model, originally a PyTorch one :)

**Comment by dkurt** [comment]
I believe that `AveragePool` is a special case of `ReduceMean` with axis == channel axis (number 1). In example, there is similar layer from TensorFlow:

https://github.com/opencv/opencv/blob/166ecaeda814c654e680b489bb483042ff0b5df5/modules/dnn/src/tensorflow/tf_importer.cpp#L1907-L1939

**Comment by Aeroxander** [comment]
> 
> 
> I believe that `AveragePool` is a special case of `ReduceMean` with axis == channel axis (number 1). In example, there is similar layer from TensorFlow:
> 
> https://github.com/opencv/opencv/blob/166ecaeda814c654e680b489bb483042ff0b5df5/modules/dnn/src/tensorflow/tf_importer.cpp#L1907-L1939

So do I need to convert the ONNX model to Tensorflow? I tried to with [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) but this gave an error:

ValueError: `Tensor conversion requested dtype float32 for Tensor with dtype int64: 'Tensor("Mul_3:0", shape=(), dtype=int64)'`

I tried to convert the int64 to float but that wasn't able to do that yet.
Thing is that PyTorch works with LongTensors what are int64's, but I don't know why Tensorflow doesn't accept this.

So preferably I would like that OpenCV could read the ReduceMean layer, I can begin with an adding it as a Custom Layer and see if you guys can integrate the code?

**Comment by dkurt** [comment]
@Aeroxander, No. I just pointed that it's possible to map ReduceMean layer from ONNX to OpenCV's Average pooling. Using custom layers (see https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html) or modifying onnx_importer.

**Comment by Aeroxander** [comment]
@dkurt So all I did is add

`|| layer_type == "ReduceMean"`

to the AveragePool if statement and I get this error:

`kernel_size (or kernel_h and kernel_w) not specified`

Think I have to create a custom layer for this one?

**Comment by Aeroxander** [comment]
Actually adding ReduceMean to the GlobalAveragePool if statement made it work, thanks!!! Should I propose a commit or will you guys short this out?

**Comment by Aeroxander** [comment]
@dkurt Actually adding ReduceMean to the GlobalAveragePool if statement made it work, thanks!!! Should I propose a commit or will you guys short this out?
Sadly an "Expand" layer is missing this time but I'll try the same method again :D

**Comment by wait1988** [comment]
@Aeroxander I can successfully run the mobilenetv2 with your code.But the classification result is wrong.

**Comment by Aeroxander** [comment]
@wait1988 Hmm ok, well I'm not going with OpenCV anymore so can't help you much further sorry about that

**Comment by dkurt** [comment]
Fixed by https://github.com/opencv/opencv/pull/15032.
