### ISSUE TITLE
ONNX Graph Traversal and Unsupported Operation Handling 

### ISSUE THREAD

**Issue by dvd42** [opencv/opencv#14772]
Hello I am a GSoC student working on an [OpenCV project](https://github.com/dvd42/opencv/wiki). This project requires importing multiple ONNX models using the OpenCV importer (readNetFromONNX). 
It might be the case that some of the models that have to be imported have some operations that are currently not supported in OpenCV _(e.g: acos, asin, etc)_. I am aware that OpenCV supports the creation of custom layers and one could implement any functionality in order to eventually export the model. However before starting to implement a custom layer for model **X** it could be very useful to know how many unsupported layers model **X** has, in order to perform a risk evaluation on the task of implementing this custom operation.  I am aware that you can look at the [importer code](https://github.com/opencv/opencv/blob/master/modules/dnn/src/onnx/onnx_importer.cpp#L385) to check every supported operation, however this is not very practical. 
Currently the importer will stop at the first unsupported operation and raise and exception. For example when running the following graph:

```
graph(%input.1 : Float(5, 10)
      %1 : Float(10, 10)
      %2 : Float(10)) {
      %3 : Float(5, 10) = onnx::Gemm[alpha=1, beta=1, transB=1](%input.1, %1, %2), scope: mymodel/Linear[linear]
  %4 : Float(5, 10) = onnx::Acos(%3), scope: mymodel
  %5 : Float(5, 10) = onnx::Gemm[alpha=1, beta=1, transB=1](%4, %1, %2), scope: mymodel/Linear[linear]
  %6 : Float(5, 10) = onnx::Gemm[alpha=1, beta=1, transB=1](%5, %1, %2), scope: mymodel/Linear[linear]
  %7 : Float(5, 10) = onnx::Asin(%6), scope: mymodel
  return (%7);
}
```

It will raise: 

` error: (-2:Unspecified error) Can't create layer "4" of type "Acos" in function 'getLayerInstance'`

But it wont tell you anything about layer 7 (Asin). 

So I would like to open a PR that fixes this minor issue by accumulating information about all the unsupported operations during the ONNX graph traversal and then throw an error at the end detailing each unsupported operation was found and what the operation is.

**Comment by bhack** [comment]
I am co-mentoring this project with @edgarriba. This is a proposed workaround cause Opencv currently has any declared compliance over ONNX opset versions.

**Comment by dkurt** [comment]
@dvd42, @bhack, Nice to meet you guys!

> So I would like to open a PR that fixes this minor issue by accumulating information about all the unsupported operations during the ONNX graph traversal and then throw an error at the end detailing each unsupported operation was found and what the operation is.

The error `error: (-2:Unspecified error) Can't create layer "4" of type "Acos" in function 'getLayerInstance'` is out of ONNX importer. We designed it in this way for custom layers support so users can register unsupported layers: https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html.

So we need to collect the names of unsupported layers not in the ONNX importer.

**Comment by dvd42** [comment]
So we should somehow modify [this function](https://github.com/opencv/opencv/blob/987061d800609ba8e4cff893fb6502bc6a4750c4/modules/dnn/src/dnn.cpp#L522) to collect the errors?

**Comment by edgarriba** [comment]
@dkurt just to give more context to this. What we have been discussing so far is more or less to do something similar what the Keras guys are already kicking off in here:

https://github.com/AakashKumarNain/Keras-model-zoo/tree/master/KerasCV

they have been iterating the idea here:

https://groups.google.com/a/tensorflow.org/forum/m/?utm_medium=email&utm_source=footer#!msg/developers/xkX_dkpnSF4/NA2PLDqABQAJ
