### ISSUE TITLE
VideoCapture results in segmentation fault while opening a video file

### ISSUE THREAD

**Issue by Ramesh-X** [opencv/opencv#14773]
##### System information (version)

- OpenCV => 3.4.6
- Operating System / Platform => Ubuntu 18.04 LTS 64 Bit
- Compiler => Makefile (with gcc 7.4)
- FFMPEG => Most recent release (see build information file)

##### Detailed description

I'm trying to run the official example code to read a video file.

Getting error `Segmentation fault (core dumped)` while executing 

```c++
  VideoCapture cap("a.mp4"); 
```

I tried to use the video files after converting into `avi` and `mkv`. Same problem.

The code I used is attached bellow. I compile it with

```bash
$ g++ temp.cpp  `pkg-config opencv --libs --cflags`
```

Compilation was successful. But after I run, here is the output.

```
$ ./a.out
Starting...
Segmentation fault (core dumped)
````

- C++ Code => [temp.cpp.txt](https://github.com/opencv/opencv/files/3272870/temp.cpp.txt)
- BuildInformation => [temp.txt](https://github.com/opencv/opencv/files/3272871/temp.txt)

Any help ??

Thank You !!!

**Comment by Ramesh-X** [comment]
Can you tell me why this is marked as `incomplete`. I gave all the information that was asked. Can you tell me what are the other information needed so that I can provide them as well.

**Comment by mshabunin** [comment]
Can not reproduce (OpenCV 3.4.6, Ubuntu 18.04, FFmpeg from system repository):
```
$ ./a.out 
Starting...
Capture created...
```
Try to build both libraries and the app in debug mode and check crash stack trace.
