### ISSUE TITLE
Load two differentnet failed

### ISSUE THREAD

**Issue by wait1988** [opencv/opencv#14778]
##### Detailed description
I load two different nets,either one works well.But when they work together,the program throws exception.Because the debug version can't run in my PC,so I can't get the exception message.

I load the Nets as follows:
Net angleNet = readNetFromDarknet(angleModelConfiguration, angleModelWeights);
angleNet.setPreferableBackend(DNN_BACKEND_OPENCV);
angleNet.setPreferableTarget(DNN_TARGET_CPU);
	
Net textNet = readNetFromDarknet(textModelConfiguration, textModelWeights);
textNet.setPreferableBackend(DNN_BACKEND_OPENCV);
textNet.setPreferableTarget(DNN_TARGET_CPU);

**Comment by wait1988** [comment]
what():  OpenCV(4.1.0) /home/sunqin/opencv-opencv-0399435/modules/dnn/src/dnn.cpp:1309: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'getLayerData'

**Comment by SunlifeV** [comment]
我在用c++版本的opencv4.1.0的时候也遇到了这个，我用的是网上的例程，里面有下面一段函数
vector<cv::String> darknet_opencv::getOutputsNames(const Net& net)
{
    //static vector<cv::String> names;  把static 去掉可以运行成功
    vector<cv::String> names;
    if (names.empty())
    {
        //Get the indices of the output layers, i.e. the layers with unconnected outputs
        vector<int> outLayers = net.getUnconnectedOutLayers();

        //get the names of all the layers in the network
        vector<cv::String> layersNames = net.getLayerNames();
        // Get the names of the output layers in names
        names.resize(outLayers.size());
        for (size_t i = 0; i < outLayers.size(); ++i)
            names[i] = layersNames[outLayers[i] - 1];
    }
    return names;
}
