### ISSUE TITLE
Opencv failed to run 4 tests with release and debug configuration

### ISSUE THREAD

**Issue by KarenHuang2016** [opencv/opencv#14787]
**Environment:**
Windows Server 2016 + VS2017 opencv master branch latest srouce code

**Issue description:**
Opencv failed to run 4 tests. These 4 tests are newly added. They failed with release configuration and debug configuration. Could you please help take a look at this? Thanks in advance
1. [  FAILED  ] Imgcodecs_EXR.readWrite_32FC1
2. [  FAILED  ] Imgcodecs_EXR.readWrite_32FC3
3. [  FAILED  ] Imgcodecs_EXR.readWrite_32FC1_half
4. [  FAILED  ] Imgcodecs_EXR.readWrite_32FC3_half

**Steps to reproduce the issue:**
1. git clone https://github.com/opencv/opencv D:\OpenCV\src
2. git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
3. Open a VS 2017 x86 prompt and browse to D:\OpenCV
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6. msbuild /p:Configuration=Release;Platform=Win32 .\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true
7. pushd build_x86\bin\Release
8. set OPENCV_TEST_DATA_PATH=D:\OpenCV\src\extra\testdata
9. opencv_test_imgcodecsd.exe --gtest_filter=Imgcodecs_EXR.*

**The whole log file please see attachment.**
log_x86_test_9.log
[log_x86_test_9.log](https://github.com/opencv/opencv/files/3279913/log_x86_test_9.log)

**TestErrorMessage:**
[ RUN      ] Imgcodecs_EXR.readWrite_32FC1
D:\OpenCV\src\modules\imgcodecs\test\test_exr.impl.hpp(22): error: Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC1 (10 ms)
[ RUN      ] Imgcodecs_EXR.readWrite_32FC3
D:\OpenCV\src\modules\imgcodecs\test\test_exr.impl.hpp(46): error: Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC3 (2 ms)
[ RUN      ] Imgcodecs_EXR.readWrite_32FC1_half
D:\OpenCV\src\modules\imgcodecs\test\test_exr.impl.hpp(76): error: Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC1_half (2 ms)
[ RUN      ] Imgcodecs_EXR.readWrite_32FC3_half
D:\OpenCV\src\modules\imgcodecs\test\test_exr.impl.hpp(105): error: Value of: img.empty()
  Actual: true
Expected: false
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC3_half (2 ms)
[----------] 4 tests from Imgcodecs_EXR (32 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (45 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC1
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC3
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC1_half
[  FAILED  ] Imgcodecs_EXR.readWrite_32FC3_half

 4 FAILED TESTS

**Comment by alalek** [comment]
Ensure that you have files in `opencv_extra` from this patch: https://github.com/opencv/opencv_extra/pull/618
