### ISSUE TITLE
Follow-up on G-API tests refactoring

### ISSUE THREAD

**Issue by dmatveev** [opencv/opencv#14795]
hmm. If this is all about specifying some enum, y not
1. Use CRTP and define some new macro to define tests (macro would pass the derived type to `TestWithParamBase` as template argument. Something like
```c++
#define GAPI_TEST(Class, Signature)   struct Class: public TestWithParamBase<Class, std::tuple Signature >
```
2. These macros become
```
#define USE_INTERPOLATION(X) constexpr int INTERPOLATION = X;
```
3. In the base class you just refer to interpolation via CRTP (or to a default value if interpolation is not defined)

_Originally posted by @dmatveev in https://github.com/opencv/opencv/pull/14757_

**Comment by dmatveev** [comment]
@andrey-golubev here it is

**Comment by andrey-golubev** [comment]
@dmatveev thanks
