### ISSUE TITLE
Viz module not created on 4.1.0

### ISSUE THREAD

**Issue by chriseyhorn** [opencv/opencv#14796]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => macOS 10.14
- Compiler => Xcode 10.1

##### Detailed description

The viz module is not getting created when running cmake using 4.1.0.  

The viz module does get created on 3.4.6 with exact same configuration.

**Comment by alalek** [comment]
Viz module has been moved into [opencv_contrib](https://github.com/opencv/opencv_contrib) since OpenCV 4.0.
