### ISSUE TITLE
Undefined symbols for architecture x86_64 for c++, python works fine

### ISSUE THREAD

**Issue by brentmsmith** [opencv/opencv#14798]
##### System information (version)

- OpenCV => 4.1.0_2
- Operating System / Platform => OS X 10.13.6
- Compiler => g++ (MacPorts gcc8 8.3.0_0) 8.3.0

##### Detailed description

I am trying to compile a very simple code with g++ (MacPorts gcc8 8.3.0_0) 8.3.0. I installed opencv4.1.0_2 with homebrew and it works perfectly for python. I need to switch to c++ at this point to use more transparent api functions. My code is:

##### Steps to reproduce

```.cpp
#include <thread>
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include "opencv2/imgcodecs/imgcodecs.hpp"
#include <iostream>
#include <stdio.h>

using namespace std;
using namespace cv;
const string ip = "192.168.122.1";

const string url1 = "http://"+ip+":8081/?action=stream";
const string url2 = "http://"+ip+":8082/?action=stream";
const string url3 = "http://"+ip+":8083/?action=stream";
const string url4 = "http://"+ip+":8084/?action=stream";
const string url5 = "http://"+ip+":8080/?action=stream";
const string url6 = "http://"+ip+":8085/?action=stream";
const string url7 = "http://"+ip+":8086/?action=stream";

void VideoGet(string url) {
    UMat frame;
    VideoCapture cap(url);
    cap.open(url);
    if (!cap.isOpened()) {
        cerr << "Unable to open camera "+url+"\n";
        return;
    }
    while (true) {
        cap.read(frame);
        if (frame.empty()) {
            cerr << "Grabbed blank frame\n";
            break;
        }
    }
}
int main() {
    thread cam1(VideoGet,url1);
    thread cam2(VideoGet,url2);
    thread cam3(VideoGet,url3);
    thread cam4(VideoGet,url4);
    thread cam5(VideoGet,url5);
    thread cam6(VideoGet,url6);
    thread cam7(VideoGet,url7);
}
```
I compile with `g++ ttc_multi_osx.cpp 'pkg-config opencv4 --cflags --libs' -o ttc_multi_osx.o` and the compiler throws 
```bash
Undefined symbols for architecture x86_64:
"cv::VideoCapture::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
VideoGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) in ccgUe88M.o
"cv::VideoCapture::VideoCapture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
VideoGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) in ccgUe88M.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
Any help would be very much appreciated.

**Comment by alalek** [comment]
> OS X
> GCC

Unsupported configuration.
Priority => low (expect help from community only)

> opencv4.1.0_2 with homebrew

Probably compiled with Xcode.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by pierrom** [comment]
Shouldn't there be backticks instead of single quotes?

**Comment by pierrom** [comment]
I think the underlying problem is that gcc uses libstdc++, but opencv was compiled with libc++.

I can compile your code with:

> /usr/local/opt/gcc/bin/g++-9 \\
> 	--std=c++11 \\
> 	$(pkg-config --libs --cflags opencv4) \\
> 	-nostdinc++ -nodefaultlibs \\
> 	-I/Library/Developer/CommandLineTools/usr/include/c++/v1 \\
>      -lc++ -lc++abi -lc \\
> 	ttc_multi_osx.cpp

**Comment by brentmsmith** [comment]
Thank you @pierrom. I just solved my compilation issue by compiling with Xcode g++. As @alalek mentioned, opencv was probably compiled with Xcode from homebrew, so all the linking must have been performed with Xcode.
