### ISSUE TITLE
OpenCV4.1.0, Build Failed. Error: no such instruction: `kmovb %eax,%k6'

### ISSUE THREAD

**Issue by mptangtang** [opencv/opencv#14801]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 14.04
- Compiler => gcc 7/8

##### Detailed description

I use cmake to build OpenCV4.1.0 on Ubuntu 14.04. During the make process, errors came out as follows:
[ 26%] Linking CXX shared library ../../lib/libopencv_surface_matching.so
[ 26%] Built target opencv_surface_matching
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/moments.cpp.o
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/morph.dispatch.cpp.o
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/phasecorr.cpp.o
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/pyramids.cpp.o
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/resize.cpp.o
[ 26%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/rotcalipers.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/samplers.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/segmentation.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/shapedescr.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/smooth.dispatch.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/spatialgradient.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/subdivision2d.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/sumpixels.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/tables.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/templmatch.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/thresh.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/utils.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/opencl_kernels_imgproc.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/imgwarp.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/resize.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/accum.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/box_filter.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/filter.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_hsv.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_rgb.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_yuv.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/median_blur.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/morph.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/smooth.sse4_1.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/corner.avx.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/accum.avx.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/imgwarp.avx2.cpp.o
[ 27%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/resize.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/accum.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/bilateral_filter.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/box_filter.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/filter.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_hsv.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_rgb.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/color_yuv.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/median_blur.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/morph.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/smooth.avx2.cpp.o
[ 28%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/sumpixels.avx512_skx.cpp.o
/tmp/ccYYDUeK.s: Assembler messages:
/tmp/ccYYDUeK.s:112: Error: no such instruction: `kmovb %eax,%k6'
/tmp/ccYYDUeK.s:115: Error: no such instruction: `kmovb %eax,%k2'
/tmp/ccYYDUeK.s:117: Error: no such instruction: `kmovb %eax,%k1'
/tmp/ccYYDUeK.s:119: Error: no such instruction: `kmovb %eax,%k3'
/tmp/ccYYDUeK.s:149: Error: no such instruction: `vpmullq %zmm6,%zmm6,%zmm6'
/tmp/ccYYDUeK.s:151: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:156: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:163: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:170: Error: no such instruction: `vextracti64x2 $0,%zmm7,%xmm8'
/tmp/ccYYDUeK.s:172: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:177: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:184: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:189: Error: no such instruction: `vpmullq %zmm6,%zmm6,%zmm6'
/tmp/ccYYDUeK.s:191: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:196: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:203: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:210: Error: no such instruction: `vextracti64x2 $0,%zmm7,%xmm8'
/tmp/ccYYDUeK.s:212: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:217: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:224: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:229: Error: no such instruction: `vpmullq %zmm6,%zmm6,%zmm6'
/tmp/ccYYDUeK.s:231: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:236: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:243: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:251: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:256: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:263: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:268: Error: no such instruction: `vpmullq %zmm6,%zmm6,%zmm6'
/tmp/ccYYDUeK.s:270: Error: no such instruction: `vpmullq %zmm7,%zmm7,%zmm7'
/tmp/ccYYDUeK.s:273: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:280: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:295: Error: no such instruction: `vmovdqu8 (%r10),%zmm8'
/tmp/ccYYDUeK.s:300: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:305: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:312: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm2'
/tmp/ccYYDUeK.s:386: Error: no such instruction: `kmovb %eax,%k3'
/tmp/ccYYDUeK.s:389: Error: no such instruction: `kmovb %eax,%k2'
/tmp/ccYYDUeK.s:391: Error: no such instruction: `kmovb %eax,%k1'
/tmp/ccYYDUeK.s:393: Error: no such instruction: `kmovb %eax,%k4'
/tmp/ccYYDUeK.s:409: Error: no such instruction: `kmovb %esi,%k5'
/tmp/ccYYDUeK.s:426: Error: no such instruction: `vpmullq %zmm3,%zmm3,%zmm3'
/tmp/ccYYDUeK.s:429: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:435: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:445: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:452: Error: no such instruction: `vextracti64x2 $0,%zmm1,%xmm8'
/tmp/ccYYDUeK.s:454: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:461: Error: no such instruction: `vcvtuqq2pd %zmm2,%zmm3'
/tmp/ccYYDUeK.s:470: Error: no such instruction: `vcvtuqq2pd %zmm2,%zmm3'
/tmp/ccYYDUeK.s:475: Error: no such instruction: `vpmullq %zmm4,%zmm4,%zmm4'
/tmp/ccYYDUeK.s:478: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:484: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:493: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:500: Error: no such instruction: `vextracti64x2 $0,%zmm1,%xmm8'
/tmp/ccYYDUeK.s:502: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:509: Error: no such instruction: `vcvtuqq2pd %zmm2,%zmm3'
/tmp/ccYYDUeK.s:518: Error: no such instruction: `vcvtuqq2pd %zmm2,%zmm3'
/tmp/ccYYDUeK.s:523: Error: no such instruction: `vpmullq %zmm7,%zmm7,%zmm7'
/tmp/ccYYDUeK.s:526: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:532: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:541: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:549: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:556: Error: no such instruction: `vcvtuqq2pd %zmm2,%zmm3'
/tmp/ccYYDUeK.s:565: Error: no such instruction: `vcvtuqq2pd %zmm7,%zmm2'
/tmp/ccYYDUeK.s:570: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:573: Error: no such instruction: `vpmullq %zmm1,%zmm1,%zmm1'
/tmp/ccYYDUeK.s:577: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:587: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:602: Error: no such instruction: `vmovdqu8 (%r10),%zmm2'
/tmp/ccYYDUeK.s:608: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:615: Error: no such instruction: `vcvtuqq2pd %zmm7,%zmm4'
/tmp/ccYYDUeK.s:624: Error: no such instruction: `vcvtuqq2pd %zmm7,%zmm4'
/tmp/ccYYDUeK.s:707: Error: no such instruction: `kmovb %eax,%k7'
/tmp/ccYYDUeK.s:710: Error: no such instruction: `kmovb %eax,%k2'
/tmp/ccYYDUeK.s:712: Error: no such instruction: `kmovb %eax,%k5'
/tmp/ccYYDUeK.s:737: Error: no such instruction: `kmovb %ebx,%k6'
/tmp/ccYYDUeK.s:739: Error: no such instruction: `kmovb %ebx,%k1'
/tmp/ccYYDUeK.s:751: Error: no such instruction: `vextracti64x2 $0,%zmm10,%xmm0'
/tmp/ccYYDUeK.s:755: Error: no such instruction: `kmovd %edi,%k4'
/tmp/ccYYDUeK.s:759: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:760: Error: no such instruction: `kmovd %edi,%k3'
/tmp/ccYYDUeK.s:776: Error: no such instruction: `vcvtuqq2pd %zmm4,%zmm3'
/tmp/ccYYDUeK.s:793: Error: no such instruction: `vcvtuqq2pd %zmm16,%zmm3'
/tmp/ccYYDUeK.s:797: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:800: Error: no such instruction: `vpmullq %zmm0,%zmm0,%zmm3'
/tmp/ccYYDUeK.s:815: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:833: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm0'
/tmp/ccYYDUeK.s:954: Error: no such instruction: `kmovb %eax,%k4'
/tmp/ccYYDUeK.s:956: Error: no such instruction: `kmovb %eax,%k1'
/tmp/ccYYDUeK.s:958: Error: no such instruction: `kmovb %eax,%k3'
/tmp/ccYYDUeK.s:960: Error: no such instruction: `kmovb %eax,%k2'
/tmp/ccYYDUeK.s:975: Error: no such instruction: `kmovb %esi,%k5'
/tmp/ccYYDUeK.s:992: Error: no such instruction: `vpmullq %zmm4,%zmm4,%zmm4'
/tmp/ccYYDUeK.s:996: Error: no such instruction: `vpmullq %zmm3,%zmm3,%zmm3'
/tmp/ccYYDUeK.s:1003: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:1014: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:1021: Error: no such instruction: `vextracti64x2 $0,%zmm2,%xmm10'
/tmp/ccYYDUeK.s:1024: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1033: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1044: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1049: Error: no such instruction: `vpmullq %zmm9,%zmm9,%zmm9'
/tmp/ccYYDUeK.s:1053: Error: no such instruction: `vpmullq %zmm10,%zmm10,%zmm10'
/tmp/ccYYDUeK.s:1060: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:1071: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:1078: Error: no such instruction: `vextracti64x2 $0,%zmm2,%xmm10'
/tmp/ccYYDUeK.s:1081: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1090: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1101: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1106: Error: no such instruction: `vpmullq %zmm9,%zmm9,%zmm9'
/tmp/ccYYDUeK.s:1110: Error: no such instruction: `vpmullq %zmm10,%zmm10,%zmm10'
/tmp/ccYYDUeK.s:1117: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:1128: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:1136: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1145: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1156: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm3'
/tmp/ccYYDUeK.s:1161: Error: no such instruction: `vpmullq %zmm8,%zmm8,%zmm8'
/tmp/ccYYDUeK.s:1165: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:1170: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm3'
/tmp/ccYYDUeK.s:1181: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:1196: Error: no such instruction: `vmovdqu8 (%r10),%zmm3'
/tmp/ccYYDUeK.s:1201: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1210: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm5'
/tmp/ccYYDUeK.s:1221: Error: no such instruction: `vcvtuqq2pd %zmm11,%zmm1'
/tmp/ccYYDUeK.s:1292: Error: no such instruction: `kmovq -160(%rbp),%k6'
/tmp/ccYYDUeK.s:1293: Error: no such instruction: `vmovdqu8 0(%r13),%zmm6{%k6}{z}'
/tmp/ccYYDUeK.s:1294: Error: no such instruction: `kmovq %k6,%rdx'
/tmp/ccYYDUeK.s:1295: Error: no such instruction: `kmovb %ebx,%k6'
/tmp/ccYYDUeK.s:1297: Error: no such instruction: `kmovb %ebx,%k1'
/tmp/ccYYDUeK.s:1301: Error: no such instruction: `vextracti64x2 $0,%zmm6,%xmm0'
/tmp/ccYYDUeK.s:1304: Error: no such instruction: `kmovd %ebx,%k4'
/tmp/ccYYDUeK.s:1309: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1310: Error: no such instruction: `kmovd %ebx,%k3'
/tmp/ccYYDUeK.s:1326: Error: no such instruction: `vcvtuqq2pd %zmm3,%zmm4'
/tmp/ccYYDUeK.s:1343: Error: no such instruction: `vcvtuqq2pd %zmm16,%zmm3'
/tmp/ccYYDUeK.s:1347: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:1356: Error: no such instruction: `vpmullq %zmm0,%zmm0,%zmm0'
/tmp/ccYYDUeK.s:1366: Error: no such instruction: `vcvtuqq2pd %zmm3,%zmm1'
/tmp/ccYYDUeK.s:1383: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm0'
/tmp/ccYYDUeK.s:1398: Error: no such instruction: `kmovq -136(%rbp),%k7'
/tmp/ccYYDUeK.s:1399: Error: no such instruction: `vmovdqu8 (%r10),%zmm9{%k7}{z}'
/tmp/ccYYDUeK.s:1400: Error: no such instruction: `kmovq %k7,%rcx'
/tmp/ccYYDUeK.s:1404: Error: no such instruction: `vextracti64x2 $0,%zmm9,%xmm7'
/tmp/ccYYDUeK.s:1408: Error: no such instruction: `kmovd %esi,%k5'
/tmp/ccYYDUeK.s:1412: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1413: Error: no such instruction: `kmovd %esi,%k4'
/tmp/ccYYDUeK.s:1418: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm6'
/tmp/ccYYDUeK.s:1426: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm6'
/tmp/ccYYDUeK.s:1432: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:1434: Error: no such instruction: `vpmullq %zmm7,%zmm7,%zmm7'
/tmp/ccYYDUeK.s:1438: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:1446: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:1461: Error: no such instruction: `kmovq -136(%rbp),%k7'
/tmp/ccYYDUeK.s:1462: Error: no such instruction: `vmovdqu8 (%r10),%zmm8{%k7}{z}'
/tmp/ccYYDUeK.s:1463: Error: no such instruction: `kmovq %k7,%rcx'
/tmp/ccYYDUeK.s:1467: Error: no such instruction: `vextracti64x2 $0,%zmm8,%xmm3'
/tmp/ccYYDUeK.s:1471: Error: no such instruction: `kmovd %esi,%k6'
/tmp/ccYYDUeK.s:1475: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1476: Error: no such instruction: `kmovd %esi,%k5'
/tmp/ccYYDUeK.s:1483: Error: no such instruction: `vcvtuqq2pd %zmm7,%zmm2'
/tmp/ccYYDUeK.s:1493: Error: no such instruction: `vcvtuqq2pd %zmm7,%zmm2'
/tmp/ccYYDUeK.s:1498: Error: no such instruction: `vpmullq %zmm3,%zmm3,%zmm4'
/tmp/ccYYDUeK.s:1500: Error: no such instruction: `vpmullq %zmm1,%zmm1,%zmm1'
/tmp/ccYYDUeK.s:1507: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:1517: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm1'
/tmp/ccYYDUeK.s:1532: Error: no such instruction: `kmovq -120(%rbp),%k7'
/tmp/ccYYDUeK.s:1533: Error: no such instruction: `vmovdqu8 (%r10),%zmm9{%k7}{z}'
/tmp/ccYYDUeK.s:1534: Error: no such instruction: `kmovq %k7,%rcx'
/tmp/ccYYDUeK.s:1538: Error: no such instruction: `vextracti64x2 $0,%zmm9,%xmm3'
/tmp/ccYYDUeK.s:1542: Error: no such instruction: `kmovd %esi,%k6'
/tmp/ccYYDUeK.s:1546: Error: operand type mismatch for `vpcompressq'
/tmp/ccYYDUeK.s:1547: Error: no such instruction: `kmovd %esi,%k5'
/tmp/ccYYDUeK.s:1556: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm4'
/tmp/ccYYDUeK.s:1568: Error: no such instruction: `vcvtuqq2pd %zmm1,%zmm4'
/tmp/ccYYDUeK.s:1573: Error: no such instruction: `vpmullq %zmm3,%zmm3,%zmm8'
/tmp/ccYYDUeK.s:1574: Error: no such instruction: `vpmullq %zmm2,%zmm2,%zmm2'
/tmp/ccYYDUeK.s:1584: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:1596: Error: no such instruction: `vcvtuqq2pd %zmm0,%zmm2'
/tmp/ccYYDUeK.s:1613: Error: no such instruction: `kmovb %esi,%k7'
/tmp/ccYYDUeK.s:1637: Error: no such instruction: `kmovb %esi,%k7'
make[2]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/sumpixels.avx512_skx.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2
make: *** [all] Error 2

##### Steps to reproduce

I followed the steps:
1. mkdir build & cd build
2. cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules \
      -DBUILD_LIBPROTOBUF_FROM_SOURCES=ON \
      -DBUILD_opencv_dnn=OFF \
      -D BUILD_EXAMPLES=ON ..
Then Configure done
3. sudo make -j 4

Then errors are generated!

**Comment by alalek** [comment]
> Ubuntu 14.04

No standard support anymore.

> gcc 7/8

Custom compiler for Ubuntu 14.04.

> Error: no such instruction

Looks like this is compiler / binutils (assembler) compatibility problem.
Can't be resolved by OpenCV.

---

Try to disable AVX2 / AVX512 optimizations: https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by LaurentBerger** [comment]
update eigen read #14789
