### ISSUE TITLE
VideoWriter failed to write codec info(fourcc) in the output file

### ISSUE THREAD

**Issue by ritwikgiri** [opencv/opencv#14803]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

I have a problem while writing a video file whose frame size is huge(3840*2160). VideoWriter did not give any error but output file is missing codec information hence producing corrupted file.

##### Steps to reproduce
```.cpp
bool read_write_video(string video_path, string out_video_path) {
        VideoCapture capture(0);
	try {
		capture.open(video_path);
		double dWidth = capture.get(CV_CAP_PROP_FRAME_WIDTH);
		double dHeight = capture.get(CV_CAP_PROP_FRAME_HEIGHT);
		Size frameSize(static_cast<int>(dWidth), static_cast<int>(dHeight));
		double fps = capture.get(CV_CAP_PROP_FPS);
		int four_cc = (int)capture.get(CV_CAP_PROP_FOURCC);
		if (four_cc <= 0) {
			return false;
		}
		VideoWriter videowriter(out_video_path, four_cc, fps, frameSize, true);
		while(capture.isOpened()){
			Mat frame;
			capture.read(frame);
			if (frame.empty()) break;
			videowriter.write(frame);
			frame.release();
		}
		videowriter.release();
		capture.release();
		return true;
	}
	catch (exception ex) {
		return false;
	}
}
```

**Comment by mshabunin** [comment]
@ritwikgiri , `VideoWriter` can use different backends under the hood, please add more information about your build configuration (cmake output). Some logs would be good too (`OPENCV_VIDEOIO_DEBUG=1`, `OPENCV_LOG_LEVEL=debug`).

**Comment by ritwikgiri** [comment]
VideoWriter is using FFmpeg as the backend. When I am resizing the frames to smaller size it is working perfectly. I have also attached the input file for your convenience.
[input.zip](https://github.com/opencv/opencv/files/3290187/input.zip)

**Comment by alalek** [comment]
OpenCV has [test](https://github.com/opencv/opencv/blob/4.1.0/modules/videoio/test/test_ffmpeg.cpp#L72) with FFmpeg and 4k images.

Copying FOURCC from input stream is a bad idea. It may be just not supported.
Proper selection of FOURCC for VideoWriter is user/developer responsibility for actual target platform configuration.

> did not give any error

Why you didn't check operation results?
- videowriter.isOpened() => bool
- videowriter.write(frame) => bool

**Comment by ritwikgiri** [comment]
As per your recommendation I have modified the code 
while(capture.isOpened() && videowriter.isOpened()) 
but the result is same. I have debuged it and the condition is true so I think there is no issue in creating the videowriterobject.
Also in c++ videowriter.write(frame) does not return bool value.

**Comment by ritwikgiri** [comment]
After further investigation I observed that my VideoWriter is using MSMF as it's backend. As previously mentioned I am facing the issue only for high resolution.

**Comment by mshabunin** [comment]
@ritwikgiri , consider using [VideoWriter constructor](https://docs.opencv.org/master/dd/d9e/classcv_1_1VideoWriter.html#af52d129e2430c0287654e7d24e3bbcdc) with `apiPreference` parameter, try to explicitly use FFmpeg backend (`CAP_FFMPEG`).

**Comment by ritwikgiri** [comment]
I have already tried to use explicitly CAP_FFMPEG while creating VideoWriter but it failed.
videowriter.open(out_video_path, CAP_FFMPEG , four_cc, fps, frameSize, true) as it returns bool value so I am unable to debug why it is returning false value?

**Comment by hamlatzis** [comment]
https://github.com/opencv/opencv/issues/14803#issuecomment-502061194

According to [documentation](https://docs.opencv.org/3.4/dd/d9e/classcv_1_1VideoWriter.html#a3115b679d612a6a0b5864a0c88ed4b39) VideoWriter's method `write` is void. 

And if connection is lost `isOpened()` still returns true. Is there a way to detect if connection is lost?
