### ISSUE TITLE
Typo in Cmake hook name

### ISSUE THREAD

**Issue by rwiesenfarth** [opencv/opencv#14807]
##### System information (version)

- OpenCV => master, commit 11b020b9f9e111bddd40bffe3b1759aa02d966f0 (and earlier)
- Operating System / Platform => any
- Compiler => any

##### Detailed description

- Severity => low
- Priority => low

One of the hook names is misspelled. If a hook is added with the correct spelling, it will not be used.

###### Actual version

CMakeLists.txt (toplevel):
```.cmake
l.949: ocv_cmake_hook(POST_DETECT_DEPENDECIES)
```

###### Expected

CMakeLists.txt (toplevel):
```.cmake
l.949: ocv_cmake_hook(POST_DETECT_DEPENDENCIES)
```
(note the additional 'N')

##### Steps to reproduce

n/a

**Comment by alalek** [comment]
Thank you! I will take a look on this.
