### ISSUE TITLE
Add support for ONNX "Expand" Layer

### ISSUE THREAD

**Issue by Aeroxander** [opencv/opencv#14813]
##### System information (version)

- OpenCV => 4.1.0 (Master)
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2019

##### Steps to reproduce

There is no support for the ONNX ["Expand"](https://github.com/onnx/onnx/blob/master/docs/Operators.md#expand) layer inside OpenCV.
I will try to make this work myself, "Expand" basically broadcasts [(Numpy style)](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) a tensor to a specified size.

_Feel free to find a solution yourself as it might take quite a while for me to figure this out!_

**Comment by Aeroxander** [comment]
This is the solution I came up with right now:

```
layerParams.blobs.push_back(Mat::ones(blob.cols, blob.rows, blob.type()));
layerParams.type = "Scale";
```

Basically what needs to happen is the similar as what Numpy does:
`numpy.array(input) * numpy.ones(shape)`

I'm guessing that OpenCV does have support for broadcasting, so all what is needed to be done is make the second argument the size what you want, by keeping the size of the second argument but changing all the value inside it to 1's; in order to expand the shape but not multiply the values.

But the following error arises:
> "Blob " + node_proto.input(index) + " not found in const blobs");

There could be something wrong with my model, but I don't if I do it correctly with `layerParams.blobs.push_back(Mat::ones(blob.cols, blob.rows, blob.type()));`, I'm just guessing the first argument is already there and I changed the second argument value to ones?

**Comment by alalek** [comment]
From OpenCV side, there is [`cv::repeat()`](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga496c3860f3ac44c40b48811333cfda2d)call (but it supports 2D matrixes only and uses size multiplier).

---

> Mat::ones(blob.cols, blob.rows, ...

OpenCV Mat expects (rows, cols) parameters (in that order). Or use `cv::Size(cols, rows)`

**Comment by Aeroxander** [comment]
@alelek Ok thanks I'll switch up the order! The error still comes up when reading the ONNX file though, it happens after the layer after Expand, (the Sub layer) tries to get the Blob. I just sort of copied the Mul layer as example so have no idea why there is no output of the Expand layer.. 

I can give a reproduction project if there is need for one!

**Comment by Aeroxander** [comment]
@alalek Can't figure out why it the blob still gives the `Blob "37" not found in const blobs` error

The reproduction project with the matrix.onnx model with the error is ([matrix.onnx](https://github.com/Aeroxander/decodererror/blob/master/matrix.onnx)) is in https://github.com/Aeroxander/decodererror/

I'd think this fault is due to the PyTorch -> ONNX conversion rather than something with OpenCV..

**Comment by Aeroxander** [comment]
@alalek Can't figure out why it the blob still gives the `Blob "37" not found in const blobs` error

The reproduction project with the [matrix.onnx](https://github.com/Aeroxander/decodererror/blob/master/matrix.onnx) model with the error  is in https://github.com/Aeroxander/decodererror/

I'd think this fault is due to the PyTorch -> ONNX conversion rather than something with OpenCV..

**Comment by Aeroxander** [comment]
Alright so after doing this: 
```
layerParams.type = "Scale";
Mat blob = getBlob(node_proto, constBlobs, 1);
layerParams.set("bias_term", false);
constBlobs.insert(std::make_pair(layerParams.name, Mat::ones(blob.cols, blob.rows, blob.type())));
```
It works until the "MatMul", where I get a similar error:
`Blob "37" not found in const blobs`

I have no idea why I keep getting these `Blob not found` errors but doing constBlobs.insert seem to fix it (temporarily)

**Comment by WillNichols726** [comment]
I'm currently having this issue as well trying to load a Mobilenet v3 model

**Comment by dkurt** [comment]
Please try https://github.com/opencv/opencv/pull/16840
