### ISSUE TITLE
No make doxygen target

### ISSUE THREAD

**Issue by jxu** [opencv/opencv#14810]
Following guide here: https://docs.opencv.org/master/d4/db1/tutorial_documentation.html

Even when running make with -DBUILD_DOCS=ON there is no make target doxygen.

I use the following to make/install:

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DBUILD_DOCS=ON ..
    make -j8
    sudo make install

Running Ubuntu 18.04.2 LTS x86_64, OpenCV 4.1.0-dev

**Comment by alalek** [comment]
Please read this part (with provided links) from mentioned tutorial page:

> Please, check official download and installation pages. Some linux distributions can also provide doxygen packages.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by jxu** [comment]
Yes you're right, I forgot to install doxygen. 
Weird that cmake did not error. Ideally cmake will stop and complain if no doxygen is found.
