### ISSUE TITLE
OpenCV 4.1.0 DNN didn't support the Caffe-Segnet? 

### ISSUE THREAD

**Issue by ZuDame** [opencv/opencv#14824]
##### System information (version)

- OpenCV =>  4.1.0
- Operating System / Platform => ubuntu 16.04
- Compiler => g++/gcc/  c++ 11

##### Detailed description

   I have learn the tutorials about the OpenCV4 DNN module, so I want to try a new model to test the semantic segmentation (NOT the fcns and Enet, these method has successed ! ), but it doesn't work.
   I want try the semantic segmentation indoor, what I have tried the method is Caffe-Segnet, the model is segnet-sun.caffemodel, What should I do can make it work.
   And Maybe the OpenCV4.1.0 can't support this net?
  
   
##### Steps to reproduce
   The Error is just like this (gdb) :
#0  0x00007ffff7099d29 in cv::dnn::dnn4_v20190122::(anonymous namespace)::CaffeImporter::populateNet(cv::dnn::dnn4_v20190122::Net) [clone .constprop.225] () from /usr/local/opencv410/lib/libopencv_dnn.so.4.1
#1  0x00007ffff709db7c in cv::dnn::dnn4_v20190122::readNetFromCaffe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/local/opencv410/lib/libopencv_dnn.so.4.1
#2  0x0000000000403206 in main ()

**Comment by ZuDame** [comment]
By the way, the Caffe-Segnet have installed successed, because I have tested this !!.

**Comment by ZuDame** [comment]
I want to combine the Segnet with OpenCV to do sth, which just like OpenCV support the Enet, So What should I do about that ?

**Comment by dkurt** [comment]
We cannot reproduce your issue because we need at least the reference to mentioned network.

Please check the the model is valid (it downloaded without any issues and isn't broken).

**Comment by ZuDame** [comment]
> We cannot reproduce your issue because we need at least the reference to mentioned network.
> 
> Please check that the model is valid (it downloaded without any issues and isn't broken).
Thank you for your reply,
The model is fine. Because I have tested this model alone and get the great effects! (this model have been trained by caffer-Segnet). After that, I want combine this model with OpenCV,  but it doesn't work.

**Comment by ZuDame** [comment]
Thank you for your reply,
The model is fine. Because I have tested this model alone and get the great effects! (this model have been trained by caffer-Segnet). After that, I want combine this model with OpenCV,  but it doesn't work.

**Comment by dkurt** [comment]
@ZuDame, share code which might be used to reproduce an issue. Attach the reference to mentioned model (upload it to dropbox or provide a URL to GitHub repo).

**Comment by dkurt** [comment]
Closing it due no response from author
