### ISSUE TITLE
set a 15 channels input to a CNN net work

### ISSUE THREAD

**Issue by LjwPanda** [opencv/opencv#14843]
##### System information (version)

- OpenCV => :3.4.0:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Visual Studio 2015:

##### Detailed description

I want to input a 1x15x24x24 input on a CNN network. Is there any feasible way

**Comment by alalek** [comment]
Use `cv::Mat` API directly.

`blobFromImages()` is designed to work with images only.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by LjwPanda** [comment]
> 
> 
> Use `cv::Mat` API directly.
> 
> `blobFromImages()` is designed to work with images only.
> 
> Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

But,blobFromImages() will create a 5x3x24x24 matrix, errors occur when executing forward().
