### ISSUE TITLE
compiling from master cap_ffmpeg_api.hpp missing

### ISSUE THREAD

**Issue by tasoss** [opencv/opencv#14850]
Hello.
I just got the latest code from master and tried to compile(i haven't compiled for maybe 1-2 months) and i get 

`/opt/opencv_contrib/modules/cudacodec/src/precomp.hpp:84:41: fatal error: ../src/cap_ffmpeg_api.hpp: No such file or directory
compilation terminated.
modules/cudacodec/CMakeFiles/opencv_cudacodec_pch_dephelp.dir/build.make:62: recipe for target 'modules/cudacodec/CMakeFiles/opencv_cudacodec_pch_dephelp.dir/opencv_cudacodec_pch_dephelp.cxx.o' failed
make[2]: *** [modules/cudacodec/CMakeFiles/opencv_cudacodec_pch_dephelp.dir/opencv_cudacodec_pch_dephelp.cxx.o] Error 1
CMakeFiles/Makefile2:6081: recipe for target 'modules/cudacodec/CMakeFiles/opencv_cudacodec_pch_dephelp.dir/all' failed
make[1]: *** [modules/cudacodec/CMakeFiles/opencv_cudacodec_pch_dephelp.dir/all] Error 2`

I'm using cuda 10.1 and if i set DWITH_NVCUVID=OFF it works as expected , but i need nvcuvid.
I have installed Video_Codec_SDK_9.0.20 and i was compiling without any problems.
The thing is that cap_ffmpeg_api.hpp doesn't exist anymore.
Thanks!

**Comment by tasoss** [comment]
I'm on Ubuntu 16.04.6

**Comment by alalek** [comment]
relates #14774

**Comment by llvim** [comment]
does opencv have any CI? why the code that bring this simple issue get merged!!!!

**Comment by acamargofb** [comment]
I am having a similar problem, I am trying to use OpenCV4.2 and I am getting this error:
[ 15%] Built target opencv_cudaarithm
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Does anyone has any idea how to fix this problem ? I tried different things but still I stuck in the installation of OpenCV on Linux Ubuntu 18.04

Thanks a lot,

Aldo

**Comment by mtlcrusher** [comment]
change `../src/cap_ffmpeg_api.hpp` with `../src/cap_ffmpeg_legacy_api.hpp`

**Comment by mtlcrusher** [comment]
> I am having a similar problem, I am trying to use OpenCV4.2 and I am getting this error:
> [ 15%] Built target opencv_cudaarithm
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Does anyone has any idea how to fix this problem ? I tried different things but still I stuck in the installation of OpenCV on Linux Ubuntu 18.04
> 
> Thanks a lot,
> 
> Aldo

can you explain more about this?
