### ISSUE TITLE
Error using tf_text_graph_fast_rcnn.py

### ISSUE THREAD

**Issue by zrx1046** [opencv/opencv#14854]
I used tf_text_graph_fast_rcnn.py to generate pbtxt for my data set. In fast_rcnn_resnet50_coco.config, I only modified class_num, but the following problems arose.

##### System information (version)
opencv=4.1.0
tensorflow=1.8.0
keras=2.2.0

(keras-frcnn) C:\Users\Admin\Desktop\pbtxt>python tf_text_graph_faster_rcnn.py
-input model.pb --config faster_rcnn_resnet50_coco.config --output sp.pbtxt
Number of classes: 84
Scales:            [0.25, 0.5, 1.0, 2.0]
Aspect ratios:     [0.5, 1.0, 2.0]
Width stride:      16.000000
Height stride:     16.000000
Features stride:   16.000000
Traceback (most recent call last):
  File "tf_text_graph_faster_rcnn.py", line 299, in <module>
    createFasterRCNNGraph(args.input, args.config, args.output)
  File "tf_text_graph_faster_rcnn.py", line 97, in createFasterRCNNGraph
    assert(graph_def.node[0].op == 'Placeholder')
IndexError: list index out of range

**Comment by dkurt** [comment]
@zrx1046, Please follow issues guideline and add information about OpenCV version, reference to model (if it's possible).

**Comment by zrx1046** [comment]
@dkurt  sorry，this is the first time I have asked a question. my opencv=4.1.0，
My model is bigger than 100M and can't be uploaded.
Thank you

**Comment by zrx1046** [comment]
@dkurt Thank you for answering my questions. This is the first time I have asked a question. I'm sorry.
My opencv=4.1.0，but my model >100M, I'm trying to upload it.

**Comment by zrx1046** [comment]
@dkurt This is my pb model https://github.com/zrx1046/pb/tree/7d94bf67d2189d24011a974079d8864b99c6bb54

**Comment by zrx1046** [comment]
@dkurt Thank you for answering my questions. This is the first time I have asked a question. I'm sorry.
I update my issue comment，and this is my pb model 
https://github.com/zrx1046/pb/tree/7d94bf67d2189d24011a974079d8864b99c6bb54

**Comment by dkurt** [comment]
@zrx1046, You need also add a config file which were used for training `faster_rcnn_resnet50_coco.config`.

**Comment by zrx1046** [comment]
@dkurt this is  my config file 
[faster_rcnn_resnet50_coco.zip](https://github.com/opencv/opencv/files/3334635/faster_rcnn_resnet50_coco.zip)

**Comment by zrx1046** [comment]
@dkurt This is my config which were used for my training
[faster_rcnn_resnet50_coco.zip](https://github.com/opencv/opencv/files/3343838/faster_rcnn_resnet50_coco.zip)

**Comment by dkurt** [comment]
@zrx1046, Can you please specify the framework which was used for training? The model structure looks a bit different from TensorFlow Object Detection API.

**Comment by zrx1046** [comment]
Yes, I made a mistake. TensorFlow Object Detection API is ok. Thank you. I'll close this comment.

**Comment by zrx1046** [comment]
@dkurt Yes, I made a mistake. TensorFlow Object Detection API is ok. Thank you. I'll close this comment.
