### ISSUE TITLE
cv::accumulateSquared function throws exception on giving CV_8UC1 images

### ISSUE THREAD

**Issue by sagniknitr** [opencv/opencv#14865]
- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
Using a CV_8UC1 image as input to cv::accumulateSquared function in imgproc module throws exception. However CV_16FC3 images works ok, even though the documentation suggests that the function is compatible with both 8 bit and 16 bit , 1 or 3 channel floating point.

##### Steps to reproduce

Step 1 . use imread to read  a  GRAYSCALE image inside a CV_8UC1 Mat data.
Step 2. call the cv::accumulateSquared function on the image. `(accumulateSquared(image,image))`

**Comment by alalek** [comment]
What is exception message?
Provide complete minimal reproducer.

> However CV_16FC3 images works ok

They should not work at all. CV_16F type support is very limited (storage only and basic conversions). Probably you got garbage result with CV_16F.

Also you can investigate how corresponding test works with 8UC1 inputs:
```
[ RUN      ] OCL_AccumulateSquareFixture_AccumulateSquare.AccumulateSquare/0, where GetParam() = (640x480, 8UC1)
```

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
