### ISSUE TITLE
Update "Installation in Linux" documentation page (instructions provided)

### ISSUE THREAD

**Issue by macheeto** [opencv/opencv#14870]
This is the page in question:
https://docs.opencv.org/4.1.0/d7/d9f/tutorial_linux_install.html

In section "Building OpenCV from Source Using CMake", paragraph 2, there is this command:
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..

As provided there it does not work, without any changes the build fails because it's using system libtiff-dev library which apparently is not compatible (although listed as a requirement under "Required Packages" on the same page).

This works out of the box:
cmake -D BUILD_TIFF=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..

Replacing earlier command with that one fixes issues like these:
error: ‘read’ is not a member of ‘cv::TiffDecoderBufHelper’
error: ‘write’ is not a member of ‘cv::TiffDecoderBufHelper’
...

That's all, just that update does the trick. Thanks!

**Comment by alalek** [comment]
> BUILD_TIFF=ON

is not required.

What is OS version and tiff package version you using?

**Comment by macheeto** [comment]
I'm using Debian Jessie and libtiff4-dev version 3.9.6.
I don't have any problems anymore because I found that answer, but I think it would be good to include that info since for some people the default instructions are not going to work.

**Comment by andreygursky** [comment]
> I'm using Debian Jessie and libtiff4-dev version 3.9.6.

Current libtiff in Jessie:
> Source Package: tiff (4.0.3-12.3+deb8u8) [security]

https://packages.debian.org/source/jessie/tiff

> default instructions are not going to work.

I'd prefer opencv would use system libtiff and fallback to the bundled one only if the system one is of a lower version than minimum required.
