### ISSUE TITLE
copyMakeBorder causes memory leak

### ISSUE THREAD

**Issue by louisabraham** [opencv/opencv#14882]
Hi, I'm pretty sure copyMakeBorder causes memory leaks in Python.

My workflow is pretty simple: I iterate over a folder with images. For each image, I apply `copyMakeBorder`, make some computations and then explicitely `del` the result. `tracemalloc` indicates that the call to `copyMakeBorder` creates a lot of memory that is never freed.

**Comment by dkurt** [comment]
> I'm pretty sure 

Provide sample code, tool log.

**Comment by louisabraham** [comment]
Actually I solved it.

My code was doing the following:

```python
padded = cv.copyMakeBorder(
    img, size1, size2, size1, size2, cv.BORDER_CONSTANT, value=0
)

ans = [padded[y : y + size, x : x + size].copy() for x, y in centers]
```

Here, `ans` was composed of views to the padded image which was preventing from freeing the memory.
