### ISSUE TITLE
cv::divide behavioural guarantee changed

### ISSUE THREAD

**Issue by JosiahKane** [opencv/opencv#14887]
In [OpenCV 3](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga6db555d30115642fedae0cda05604874) the cv::divide function had a documented behaviour guarantee that 

"When src2(I) is zero, dst(I) will also be zero."

In [OpenCV 4](https://docs.opencv.org/4.1.0/d2/de8/group__core__array.html#ga6db555d30115642fedae0cda05604874) this has been changed to 

"For integer types when src2(I) is zero, dst(I) will also be zero."

Such changes to edge case behaviour in a major version seems reasonable, but it should be clearly present in the changelog to allow for upgrading.

**Comment by alalek** [comment]
`cv::divide()` has been fixed for floating-point numbers (to follow IEEE rules).
Due "breaking changes" it is not landed on 3.x branch.
Related PR: #12826

---

Changelog on wiki is intended for short list of highlights only.
More detailed change list is available via `git log` command.
