### ISSUE TITLE
arm: GaussianBlur wrong gray value with some kernel size

### ISSUE THREAD

**Issue by Chen-JQ** [opencv/opencv#14893]
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => Debian8 / arm rk3288
- Compiler => gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf

##### Detailed description

Gaussian Blur a gray image with kernel size 9x3 13x3 17x3 25x3, some pixels be black which should be white.
Maybe convert 256 to 0;

##### Steps to reproduce

```.cpp
#include <iostream>
#include <string>
#include <opencv2/opencv.hpp>

int main(int argc, char* argv[]) {
    cv::Mat src;
    if (1 >= argc) {
        src = cv::Mat(256, 256, CV_8UC1, cv::Scalar::all(0));
        cv::rectangle(src, cv::Point(100, 100), cv::Point(200, 200), cv::Scalar::all(255), -1);
    } else {
        src = cv::imread(argv[1], cv::IMREAD_GRAYSCALE);
    }
    cv::imwrite("./image/src.png", src);
    cv::Mat dst;
    cv::Size ksize{3, 3};
    for (ksize.width = 3; ksize.width < 41; ksize.width+=2) {
        cv::GaussianBlur(src, dst, ksize, 0.);
        std::string name = "./image/" + std::to_string(ksize.width) + "X" + std::to_string(ksize.height) + ".png";
        std::cout << name << std::endl;
        cv::imwrite(name, dst);
    }
    return 0;
}
```

**Comment by asmorkalov** [comment]
The issue is not reproducible with current 4.x branch. Attaching 25x3 result for reference. Tested armv7 with neon and without neon against desktop. Result images are identical. I do not see noise or obviously erroneous
![25X3](https://github.com/opencv/opencv/assets/2536374/5ad45410-38c2-45c6-b614-88b3d5a274a0)
 pixels.
