### ISSUE TITLE
Clip Operation for ONNX

### ISSUE THREAD

**Issue by dvd42** [opencv/opencv#14902]
Hello I am a GSoC student and, as part of my project I need to implement several ONNX layers/operations in the OpenCV ONNX importer. Right now I have to import the `clip`  operation. Before starting to implement a new layer to cover this functionality. I would like to make sure that the only way to cover it is by implementing a new layer and not by combining 2 different layers or something like that, as it happened to me in #14858 
So is an entirely new layer required for this operation or can it be done some other way? 
Thanks in advance for your help! :)

**Comment by dkurt** [comment]
Can you define `Clip` operation?

**Comment by dvd42** [comment]
Of course, its a simple operation that limits the values of an input tensor, it is defined in [ONNX](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip). So:

>>> import numpy as np
>>> inp = np.asarray([1,2,3,4,5])
>>> np.clip(inp, a_min=2, a_max=4)
array([2, 2, 3, 4, 4])

**Comment by dkurt** [comment]
This might be done by ReLU6 layer: https://github.com/opencv/opencv/blob/66d7956e672f06cc308e491b19c312187974639c/modules/dnn/src/layers/elementwise_layers.cpp#L382-L385

**Comment by dvd42** [comment]
Great, Ill make some test and implement it for ONNX and open a PR. sound good?

**Comment by dkurt** [comment]
I'm fine with it, thanks!

ср, 26 июн. 2019 г., 20:07 Diego <notifications@github.com>:

**Comment by dkurt** [comment]
I'm fine with it. Thanks!

**Comment by dkurt** [comment]
resolved by https://github.com/opencv/opencv/pull/14959
