### ISSUE TITLE
Linking error compiling with cuda on Mac

### ISSUE THREAD

**Issue by ujdurgam** [opencv/opencv#14909]
I observe strange linker lib added to the extra dependencies list, when I compiled OpenCV 4.1.0 with cuda 10.1 on my Mac (High sierra).
`Extra dependencies:          cudart_static lib nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/local/cuda/lib -L-Wl,-rpath,/usr/local/cuda
`
This linker library is resulting in a linking error

> [ 21%] Linking CXX shared library ../../lib/libopencv_cudev.dylib
> ld: warning: directory not found for option '-L/Users/****/opencv/-Wl,-rpath,/usr/local/cuda'
> ld: warning: directory not found for option '-L-Wl,-rpath,/usr/local/cuda'
> ld: library not found for -llib
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/libopencv_cudev.4.0.1.dylib] Error 1
> make[1]: *** [modules/cudev/CMakeFiles/opencv_cudev.dir/all] Error 2
> make: *** [all] Error 2

##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Mac
- Compiler => Clang

**Comment by ujdurgam** [comment]
A [thread ]( https://devtalk.nvidia.com/default/topic/1046739/cuda-setup-and-installation/linking-error-while-compiling-opencv-with-cuda-on-high-sierra/post/5311651/?offset=10#5357136)in nvidia also discuss this issue

**Comment by alalek** [comment]
What is CMake version?
With CMake 3.9+ OpenCV [uses FindCUDA from CMake](https://github.com/opencv/opencv/blob/4.1.0/cmake/OpenCVDetectCUDA.cmake#L12-L17) by default.
Are you able to build other CUDA projects via CMake? CUDA samples on Mac?

More details are required:
- used CMake parameters
- CMake stdout (from clean build)
- files from build folder: CMakeCache.txt and CMakeVars.txt (as attachment or use "grep" for related problem keyword - `cuda`)
- failed command line via `make VERBOSE=1` (without any `-j` option)

**Comment by ujdurgam** [comment]
Cmake 3.10 is used
I am able to make other CUDA projects. (CUDA samples)
I copied the files of findcuda in opencv/cmake to cmake-bin/share/cmake-3.10/modules/findCUDA and the build is successful

**Comment by alalek** [comment]
Consider upgrading CMake (current version is 3.14+)

> opencv/cmake to cmake-bin/share/cmake-3.10/modules/findCUDA

Perhaps it is enough adding `OPENCV_CUDA_FORCE_BUILTIN_CMAKE_MODULE` flag, instead of replacing native CMake files.

**Comment by ujdurgam** [comment]
That works absolutely fine, I will update my cmake. Closing the issue, thank you so much.
