### ISSUE TITLE
How to reduce memory allocation for Volume Binary Images? Binary Volume image shape= 1000 X 1000 X3000?

### ISSUE THREAD

**Issue by selvakarna** [opencv/opencv#14913]
How to reduce memory allocation for Volume Binary Images? Binary Volume image shape= 1000 X 1000 X3000?

from above Volume binary image , how to allocate [reduce memory ] during Python Running? except RAM Memory ?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

---

1. Tiling.
2. Something like `cv::SparseMat` (lack of operations which support that), C++ only.
