### ISSUE TITLE
Found frame skipping in the read, write operation?

### ISSUE THREAD

**Issue by anmol8496** [opencv/opencv#14911]
There is we use .read() and .write function for captured video from the ip camera. approximately >50% frame area missed to write in the video. so we are not found sync between live streaming and saved video. recorded video also play  like as fast forwarding and end in less duration as respect to original video.

**Comment by alalek** [comment]
At first, OpenCV is not Media I/O library.
For such tasks consider using of corresponding frameworks like FFmpeg or GStreamer or may be VLC.

If you want to report a bug, be more specific and provide complete minimal reproducer.

> missed ... we are not found sync

In case of GStreamer parameter which controls that is called "drop".

---

> also play like as fast forwarding

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by anmol8496** [comment]
if functionality provide for read and write frame that means it's work proper way not that miss the information. it is con of the OpenCV library.  many of people suffering from this problem. when we use read and write function than **_we found less than 50% frames of the original video write_** into the new file. if 1-2% frames are drop that considerable. OpenCV read write buffer time is large and this library not use FIFO or PIPE-LINING  type concept for read and write operation.
