### ISSUE TITLE
Compilation error opencv_dnn with inference engine 1.6

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv#14912]
##### System information
- OpenCV => 4.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7

##### Detailed description

Names conflict with dldt:
In file  opencv/modules/dnn/src/op_inf_engine.hpp and opencv/modules/dnn/src/op_inf_engine.cpp in function addBlobs was used cv::Ptr but without namespace specification.
It conflicts with ICNNNetwork::Ptr from   dldt/inference-engine/include/ie_icnn_network.hpp : `using Ptr = std::shared_ptr<ICNNNetwork>`

##### Steps to reproduce

Compilation opencv_dnn with inference engine 1.6 (2019 branch)

It can write cv::Ptr in addBlobs or rename Ptr in ICNNNetwork

**Comment by alalek** [comment]
`cv::Ptr` should resolve these problems.
Could you prepare patch for that (onto 3.4 branch)?

**Comment by Nuzhny007** [comment]
Yes, resolve.
Ok
