### ISSUE TITLE
Camera issues: Stucking after running 

### ISSUE THREAD

**Issue by codewithdev** [opencv/opencv#14927]
cv2.release(): is not working. Execution completion but takes time to smoothly release the camera. 
Whenever i run the Program it prompts unusual Not responding error. And camera gets stuck with a new window named 'vid' as i defined as the syntax.

**Comment by developerd3v** [comment]
# Using the "haarcascade_frontalface" and "haarcascade_eye" algorithm to detect the live web cam face detection/

Pulling Issues:




cv2.release(): is not working. Execution completion but takes time to smoothly release the camera.
Whenever i run the Program it prompts unusual Not responding error. And camera gets stuck with a new window named 'vid' as i defined as the syntax.

**Comment by alexander-soare** [comment]
I'm also having this issue. Is there any reason this was closed. Can I provide more detail to help?

Here's some prototype code:

requirements.txt
```
opencv-contrib-python==4.1.1.26
```

application.py
```
import cv2

def run_analysis(path_to_video):
    vs = cv2.VideoCapture(path_to_video)

    while True:
         frame = vs.read()
         if frame is None:
             break
         do_stuff_with_frame(frame)
    
    vs.release()
```
This code works all the time on my mac. It works only the first time around when I deploy it as a Flask app to Elastic Beanstalk (runs on Red Hat Linux).

Even if I can't get an answer for why, I'd be happy with a brute force way of making it work.
