### ISSUE TITLE
Building with MinGW on windows - failing on chmod

### ISSUE THREAD

**Issue by beckylum0216** [opencv/opencv#14939]
Hi,

I am trying to build OpenCV with MinGW on windows. The cmake configures as expected, but the make fails on libopencv_core_pch_dephelp.a with an error pointing to chmod?! As I understand it there is no chmod in windows. I am wondering if it is a bug in the cmake build or in the MinGW compiler. Can someone please clarify? Attached is a screen dump of the error.

![Annotation 2019-07-01 015236](https://user-images.githubusercontent.com/11342938/60400259-b333c600-9ba3-11e9-9530-3b8fe0d63384.jpg)

**Comment by huihut** [comment]
I fixed it by not using chmod in WIN32.  https://github.com/opencv/opencv/pull/15433
