### ISSUE TITLE
Bug: dot product throws error: (-215:Assertion failed) mat.size == size in function 'dot' uncessarily

### ISSUE THREAD

**Issue by abhiTronix** [opencv/opencv#14944]
##### System information (version)

- OpenCV => 4.1.0-dev
- Operating System / Platform => Ubuntu x64 bionic 18.04.1
- Compiler => gcc 8.0.1

**Hello, There is a bug with dot product [`dot (InputArray m) const`]() when used in c++ implementation, But strangely this bug is not present in python implementation.** 

##### Detailed description
Check following python code:
```shell
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a  = np.zeros((5, 5),np.float32)
>>> b = np.ones((5,1),np.float32)
>>> a.dot(b)
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)
```
which works as expected.

But when I tried to implement the same code in C++, it throws the following error everytime regardless of the case:
```shell
abhishek@abhishek-HP-Pavilion-Notebook:~/testing$ ./test
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.1-dev) /home/abhishek/Downloads/opencv-master/modules/core/src/matmul.cpp:3274: error: (-215:Assertion failed) mat.size == size in function 'dot'

Aborted (core dumped)
```

##### Steps to reproduce
The code I'm using for c++ is as below:
```cpp
#include <opencv2/opencv.hpp>
#include <iostream>
#include <cassert>
#include <fstream>

int main(){
        cv::Mat a = cv::Mat::ones(5,5, CV_32F);
	cv::Mat b = cv::Mat::ones(5,1, CV_32F);
	cout <<  a.dot(b)  << endl ;
	return 0; 
}
```

**Comment by dkurt** [comment]
`a.dot(b)` from Python is a Numpy's matrix multiplication: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In OpenCV `dot` is a dot product: https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a0f683eab191eeece33dfc64ae299a9cb

**Comment by abhiTronix** [comment]
> a.dot(b) from Python is a Numpy's matrix multiplication: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html
> 
> In OpenCV dot is a dot product: https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a0f683eab191eeece33dfc64ae299a9cb

@dkurt Yes, only OpenCV dot is throwing this error regardless of the Mat size.

**Comment by alalek** [comment]
> mat.size == size

Problem is pointed correct. In OpenCV both vectors (matrix with some assumptions - 1D Mat is not supported in OpenCV) should have the same size and probably the same data type.

> isn't OpenCV uses numpy for handling matrix in python

No, only storage container is re-used (if possible)

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
