### ISSUE TITLE
error in opening camera

### ISSUE THREAD

**Issue by suryansh-singh-verma** [opencv/opencv#14942]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by suryansh-singh-verma** [comment]
>>>import cv2
>>>cam=cv2.VideoCapture(0)
>>> while 1:
	r,i=cam.read()
	cv2.imshow('i',i)
	if cv2.waitKey(1)!=-1:
		break

	
Traceback (most recent call last):
  File "<pyshell#62>", line 3, in <module>
    cv2.imshow('i',i)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

**Comment by soumyaiitkgp** [comment]
This error occurs when no input is being passed into cv2.VideoCapture. Please check if camera is working or not.

**Comment by suryansh-singh-verma** [comment]
my camera is working well with the camera app provided by windows.
i also passed the values 0,1,2 as this were to be passed as the no. of
cameras we were using in the programming but still the issue remains same.
thanx for the support
in case of any other information pls let me know.
