### ISSUE TITLE
Opencv function call failed on Android camera hal

### ISSUE THREAD

**Issue by peacherwu** [opencv/opencv#14948]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => mtk6739, android 9.0, RAM:2G
- Compiler => Clang (ndk19)

##### Detailed description

OpenCV is compiled as static library with NDK19 and then wrapped as C dynamic library for use of camera hal. Many basic OpenCV function calls would fail (core dump) such as `resize` and `cvtColor`.

Our debug log shows the `resize` ( `resize.cpp` ) function fails at
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/resize.cpp#L3358

   `CALL_HAL(resize, cv_hal_resize, src_type, src_data, src_step, src_width, src_height, dst_data, dst_step, dst_width, dst_height, inv_scale_x, inv_scale_y, interpolation);`

**Comment by peacherwu** [comment]
The reason we wrapped Opencv static library as C dynamic library is that [https://github.com/opencv/opencv/issues/14947](https://github.com/opencv/opencv/issues/14947)

**Comment by alalek** [comment]
Lets keep this discussion in the single place: #14947

**Comment by andytian1991** [comment]
> The reason we wrapped Opencv static library as C dynamic library is that #14947

Hi , is your issue resolved?
And you can use opencv lib in camera vendor HAL now?
