### ISSUE TITLE
Android compile (link) failed with OpenCV dynamic library

### ISSUE THREAD

**Issue by peacherwu** [opencv/opencv#14947]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => mtk6739, android 9.0, RAM:2G
- Compiler => Clang (ndk19)

##### Detailed description

If OpenCV is compiled with NDK19 as dynamic library, subsequent linking with Android source code would fail, due to namespace inconsistency.

**Comment by alalek** [comment]
OpenCV Android packages are built with `ANDROID_STL=c++_static`.
You can rebuild OpenCV with `c++_shared` option (see https://github.com/opencv/opencv/issues/14906#issuecomment-506261419 )

**Comment by peacherwu** [comment]
Change ANDROID_STL = c++_static to c++_shared, and rebuild OpenCV. compile with android source code will still report an error,

log:
vendor/mediatek/proprietary/hardware/mtkcam3/3rdparty/mtk/GsFb/preview/GsFBImpl.cpp:365: error: undefined reference to 'cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)'
vendor/mediatek/proprietary/hardware/mtkcam3/3rdparty/mtk/GsFb/preview/GsFBImpl.cpp:368: error: undefined reference to 'cv::imwrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'

**Comment by peacherwu** [comment]
> OpenCV Android packages are built with `ANDROID_STL=c++_static`.
> You can rebuild OpenCV with `c++_shared` option (see [#14906 (comment)](https://github.com/opencv/opencv/issues/14906#issuecomment-506261419) )

**Comment by alalek** [comment]
Switched onto `c++_shared` builds by default.

**Comment by Moonsimon** [comment]
> I have rebuilt OpenCV with `ANDROID_STL = c++_shared`. But linking with android source will still report an error,
> 
> Log: `vendor/mediatek/proprietary/hardware/mtkcam3/3rdparty/mtk/GsFb/preview/GsFBImpl.cpp:365: error: undefined reference to 'cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)' vendor/mediatek/proprietary/hardware/mtkcam3/3rdparty/mtk/GsFb/preview/GsFBImpl.cpp:368: error: undefined reference to 'cv::imwrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'`

Hello ,
Have you already fixed this issue?
