### ISSUE TITLE
ORB features in 4.0

### ISSUE THREAD

**Issue by barca1987** [opencv/opencv#14949]
Has anything changed in the ORB feature calculation between OpenCV3.4 and OpenCV4.0. Seems like the two versions give me different results in both the actual ORB features that are calculated and in the number of matching features that are found.

**Comment by dkurt** [comment]
Please provide the reproducible code.

**Comment by mathieu-fernandes** [comment]
I have also a difference between OpenCV 3.0.0 and OpenCV 4.1.0 in the number of key points found by ORB detector. Please find below a simple reproducible example:

`cv::Mat image = cv::Mat::zeros(200, 200, CV_8UC1);
cv::putText(image, "TOTO", cv::Point(10, 120), CV_FONT_HERSHEY_PLAIN, 4.2, cv::Scalar(255), 5);
cv::GaussianBlur(image, image, cv::Size(11, 11), 0);

cv::Ptr<cv::ORB> orb = cv::ORB::create();
orb->setNLevels(4);
orb->setScoreType(cv::ORB::HARRIS_SCORE);
orb->setWTA_K(2);
orb->setMaxFeatures(300);
orb->setEdgeThreshold(20);
orb->setPatchSize(20);

std::vector<cv::KeyPoint> keyPoints;
cv::Mat descriptors;
orb->detectAndCompute(image, cv::noArray(), keyPoints, descriptors);

std::cout << keyPoints.size() << std::endl;`

**Comment by alalek** [comment]
> OpenCV 3.0.0

ORB in this version tries using of OpenCL even with Mat - refer to corresponding bug reports.
