### ISSUE TITLE
Error when running opencv android sdk samples

### ISSUE THREAD

**Issue by abdou31** [opencv/opencv#14956]
- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

I cloned OpenCV Samples and I try to import the project on Android Studio but I get many errors.
How can I solve these problems?

![image](https://user-images.githubusercontent.com/19480228/60471250-2dc41a80-9c64-11e9-81cb-88d4eaf66e73.png)

**Comment by alalek** [comment]
You have message about "broken compiler" in Android NDK. Not sure that this can be fixed in OpenCV.

Try some Android samples with JNI code - for example, [this one](https://github.com/googlesamples/android-ndk/tree/master/hello-jni/#readme).

**Comment by abdou31** [comment]
Okey thanks,
I can say that I have successfully running tutorial about how creating OpenCV project
( Juste for testing ).
In the tuto, I remember that I change the repo of the Android NDN in local properties 
But I want really to run a sample app because I need some pieces of code.
