### ISSUE TITLE
DNN spews out inaccurate results after a backend/target switch

### ISSUE THREAD

**Issue by YashasSamaga** [opencv/opencv#14965]
##### System information (version)

- OpenCV => 4.1 (master at 2bf87936323d68e66b14c4d1c89b07a753bec2f5)
- Operating System / Platform => Windows 10 64-bit
- Compiler => MSVC 19.16

##### Detailed description

Changing the preferable backend/target of a `cv::dnn::Net` leads to incorrect results on the new backend/target. The expectation is that the network should give similar results after a backend/target switch.

I am not sure if this is a bug or a missing feature. I couldn't find anything in the documentation which states that the backend/target cannot be changed once set.

This doesn't seem to be happening with every model; `mobilenet_ssd_v1_coco_2017_11_17` is one model which doesn't work well with these backend/target switches.

##### Steps to reproduce

**MCVE:**
The code below starts off with the OCV CPU backend. It performs a forward pass and then switches to the OpenCL target where it again performs a forward pass. It switches back to the CPU target and performs a forward pass again. The outputs from the three forward passes do not agree with each other.

Note that the outputs (`first_detection` and `third_detection`) are from the same backend-target combination but still give inaccurate results. The results from the OpenCL target are also inaccurate. This appears to happen with other backends and targets as well. Hence, it's a general problem with the `cv::Net` object.

```
#include <iostream>

#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>

int main() {
    auto input_size = cv::Size(300, 300);

    cv::Mat image(input_size, CV_32FC3);
    cv::randu(image, cv::Scalar(0, 0, 0), cv::Scalar(255, 255, 255));

    cv::Mat blob = cv::dnn::blobFromImage(image, 1.0f, input_size, 0.0f);

    auto net = cv::dnn::readNetFromTensorflow("data/mobilenet_ssd_v1_coco_2017_11_17/ssd_mobilenet_v1_coco_2017_11_17.pb", "data/mobilenet_ssd_v1_coco_2017_11_17/ssd_mobilenet_v1_coco_2017_11_17.pbtxt");

    net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
    net.setInput(blob);
    auto first_detection = net.forward();

    net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);
    net.setInput(blob);
    net.forward();
    auto second_detection = net.forward();

    net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
    net.setInput(blob);
    auto third_detection = net.forward();

    std::cout << "Mismatches: " << cv::countNonZero(first_detection - third_detection) << std::endl;

    for (int i = 0; i < 10; i++)
        std::cout << first_detection.at<float>(i) << ' ' << third_detection.at<float>(i) << std::endl;

    return 0;
}
```

**Actual Output:**
```
Mismatches: 590
0 0
1 1
0.0245883 0.0261505
0.768966 0.849214
-0.00513216 -0.00365399
1.03373 0.998887
0.0901401 0.239716
0 0
1 1
0.0209146 0.0254748
```

**Comment by YashasSamaga** [comment]
Disabling layer fusion (using `Net::enableFusion`) solves the problem.

I think the inaccurate results are due to the fusion process wrongly altering the already fused parameters.

**Comment by dkurt** [comment]
We just do not consider backends switching. Is it a kind of tuning in your application?

**Comment by YashasSamaga** [comment]
I was trying to compare different backends/targets. It had worked for over 10 popular models so it seemed like a bug when it didn't work for one.

Anyway, for the record, the problem is because of a check in `tryFuse` of `PowerFunctor`.
https://github.com/opencv/opencv/blame/master/modules/dnn/src/layers/elementwise_layers.cpp#L1012-L1013

```
        if (power != 1.0f && shift != 0.0f)
              return false;
```

Suppose `power` and `shift` is `1.0` and `0.0` respectively and a fusion requires shifting by `1.0`. On the first call to `tryFuse`, the condition fails because of both `power` and `shift` and hence the fusion continues. On the second call to `tryFuse`, it fails again because `power` is still `1.0` even though `shift` is `1.0`.

**Comment by YashasSamaga** [comment]
Is `power` in the if statement supposed to be `scale`?
