### ISSUE TITLE
opencl sync problem

### ISSUE THREAD

**Issue by xrataj00** [opencv/opencv#14962]
##### System information (version)
- OpenCV => 3.4.6
- Operating System / Platform => Linux Debian/Ivy Bridge,Kaby Lake,Coffee Lake
- Compiler => gcc
- OpenCL=> beignet 1.3

##### Detailed description

If I run following code in two separate threads I am getting corrupted images or the image from the second thread:
```
Mat image,
UMat uimage, uimage_bw, uimage_canny;

image.copyTo(uimage);
cvtColor(uimage,uimage_bw, cv::COLOR_BGR2GRAY);
GaussianBlur(uimage_bw, uimage_bw, cv::Size(7,7), 0, 0);
Canny(uimage_bw, uimage_canny, 20, 50, 3);
```

Following fixes the problem:
1. change Umat to Mat
2. disable opencl with setenv("OPENCV_OPENCL_RUNTIME","disabled", 1)
3. put cv::ocl::finish(); after every function
4. use just one UMat:
```
Mat image,
UMat uimage;

image.copyTo(uimage);
cvtColor(uimage,uimage, cv::COLOR_BGR2GRAY);
GaussianBlur(uimage, uimage, cv::Size(7,7), 0, 0);
Canny(uimage, uimage, 20, 50, 3);
```

**Comment by alalek** [comment]
Provide complete minimal reproducer (including your threading approach).

**Comment by xrataj00** [comment]
I have made simple test app to reproduce the problem. It creates 10 threads and in each thread load different image and do some processing (Canny). There is also a short screen video captured on my system. 

[opencv_test.zip](https://github.com/opencv/opencv/files/3350979/opencv_test.zip)

**Comment by xrataj00** [comment]
After some further investigation I have found out that when I call two opencl accelerated functions passing data from one to another like following code:

```
Mat image,
UMat uimage;

image.copyTo(uimage);
cvtColor(uimage,uimage, cv::COLOR_BGR2GRAY);
GaussianBlur(uimage, uimage, cv::Size(7,7), 0, 0);
Canny(uimage, uimage, 20, 50, 3);
```
It is actually running in parallel, e.g. Canny is not waiting for GaussianBlur to finish. It is just more visible for multithreaded app. When I force the synchronization with copyTo(Mat) after each function it is working fine:

```
Mat image,
UMat uimage;

image.copyTo(uimage);
cvtColor(uimage,uimage, cv::COLOR_BGR2GRAY);
uimage.copyTo(image);
GaussianBlur(uimage, uimage, cv::Size(7,7), 0, 0);
uimage.copyTo(image);
Canny(uimage, uimage, 20, 50, 3);
uimage.copyTo(image);
```
Is there a way how to pass the UMat between opencl functions correctly without copying back to CPU?

**Comment by alalek** [comment]
Probably this problem is related to using of "inplace" destination parameters.
They are buggy (even for CPU), not tested and make no sense here (there is no inplace processing for these operations - `src`/`dst` buffers must be always different).

```
cvtColor(uimage, uGrayimage, cv::COLOR_BGR2GRAY);
GaussianBlur(uGrayimage, blurredImage, cv::Size(7,7), 0, 0);
Canny(blurredImage, edges, 20, 50, 3);
```

**Comment by xrataj00** [comment]
Please check the packed app from my previous post. There are no inplace destination parameters but still not working. Seems that the problem is not related to that.

**Comment by xrataj00** [comment]
This could be minimal reproducer. It fails every few seconds on my system. Seems that frequency of "fail" is related to GPU usage (switching windows etc.)

```
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/ocl.hpp>

#include <iostream>
#include <unistd.h>

using namespace cv;
using namespace std;

int main( int argc, char** argv ) {    
    UMat uimage = cv::UMat::zeros(640,640, CV_8U);
   
    while(1) {
        UMat uimage_res, uimage_canny;
        Mat image;
        
        uimage_canny = cv::UMat(uimage.rows,uimage.cols, CV_8U,255);
        Canny(uimage, uimage_canny, 20,50, 3);
        
        //one of those fixes the problem
        //cv::ocl::finish();
        //uimage_canny.copyTo(image);
        
        resize(uimage_canny,uimage_res, Size(500,500));        
        uimage_res.copyTo(image);
        
        if(image.at<uchar>(0,0) != 0) cout << "fail" << endl;
    }    
    
    return 0;
}
```

**Comment by alalek** [comment]
> beignet 1.3

Please try modern Intel OpenCL Runtime:
https://github.com/intel/compute-runtime/releases

(125000 iterations with switching windows/workspaces without any "fail" messages on i5-6600 + kernel 4.20)

**Comment by xrataj00** [comment]
Opened an issue on beignet. Thanks for your help.
intel/beignet#13
