### ISSUE TITLE
cap_openni2.cpp:275: error: (-2:Unspecified error) OpenCVKinect2: Device index exceeds the number of available OpenNI devices in function 'CvCapture_OpenNI2::CvCapture_OpenNI2'

### ISSUE THREAD

**Issue by tr0ublee** [opencv/opencv#14969]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Windows  10 64 Bit
- Compiler => Visual Studio 2017 (Working with QT)
Hello,
I am trying to use Kinect 1 with OpenNI2.2 + OpenCV 4.1.1 + QT. I can take images and videos from Kinect with my code. However, when I try the following code (attached in the file), i get an exception. Note that when building the OpenCV, I have marked WITH_OPENNI and WITH_OPENNI2 and added the required directory paths to cmake.
[issue.txt](https://github.com/opencv/opencv/files/3354726/issue.txt)

Throws the exception : 
`[ERROR:0] global C:\Users\username\Downloads\opencv-master\modules\videoio\src\cap.cpp (187) cv::VideoCapture::open VIDEOIO(OPENNI2): raised OpenCV exception:`

`OpenCV(4.1.1-pre) C:\Users\username\Downloads\opencv-master\modules\videoio\src\cap_openni2.cpp:275: error: (-2:Unspecified error) OpenCVKinect2: Device index exceeds the number of available OpenNI devices in function 'CvCapture_OpenNI2::CvCapture_OpenNI2'`
I really dont know what is the issue here but the reason I am trying to do this is that Kinect's sensors are not calibrated, so I am trying this piece of code. Thanks in advance !

**Comment by alalek** [comment]
> capture.open(CV_CAP_OPENNI);

Try:

```
capture.open(0, CAP_OPENNI2);
```

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by tr0ublee** [comment]
Hello, sorry for the inconvenience. Actually, I am trying with CAP_OPENNI2. The thing is it throws exception, but if I rerun it again, it works fine. 
Again, sorry for posting to wrong place.

**Comment by tr0ublee** [comment]
> 
> 
> > capture.open(CV_CAP_OPENNI);
> 
> Try:
> 
> ```
> capture.open(0, CAP_OPENNI2);
> ```
> 
> Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
> This tracker is for issues and bugs that needs fix in OpenCV.

Hello, sorry for the inconvenience. Actually, I am trying with CAP_OPENNI2. The thing is it throws exception, but if I rerun it again, it works fine.
Again, sorry for posting to wrong place.
