### ISSUE TITLE
make install error: Generator error: constant l_MAGIC_VAL (cname=cv::l::MAGIC_VAL) already exists

### ISSUE THREAD

**Issue by kli017** [opencv/opencv#14972]
##### Detailed description
[ 98%] Built target pch_Generate_opencv_videostab
[ 98%] Built target opencv_videostab
[ 98%] Built target opencv_python2
[ 98%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
Note: Class l has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::a, cv::s, cv::s, cv::A, cv::l, cv::g, cv::o, cv::r, cv::i, cv::t, cv::h, cv::m
      Only the first base class will be used
Generator error: constant l_MAGIC_VAL (cname=cv::l::MAGIC_VAL) already exists
modules/python3/CMakeFiles/opencv_python3.dir/build.make:158: recipe for target 'modules/python3/pyopencv_generated_include.h' failed
make[2]: *** [modules/python3/pyopencv_generated_include.h] Error 255
CMakeFiles/Makefile2:11977: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment]
> l_MAGIC_VAL

Can your point on that code in OpenCV?

**Comment by kli017** [comment]
I don‘t know where this variable located in... Actually I have complied and make install successfully before, for some reason I deleted the old build and rebuild it again. Then I met this error.

**Comment by alalek** [comment]
> Bases: cv::a, cv::s, cv::s, cv::A, cv::l, cv::g, cv::o, cv::r, cv::i, cv::t, cv::h, cv::m

I decrypted part of this code - "Algorithm" is here.

What python version are you using?
Please check source files for UTF-16 content.

Please provide exact steps which reproduces problem. Without reproducer it is unlikely to fix issue.

**Comment by kli017** [comment]
Sorry for the late response. 
I was using python3.7 

cd ~/opencv
mkdir build 
cd build
sudo cmake -D OpenCV_DIR=/home/opencv/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
sudo make -j8 
sudo make install 
and get the error.

**Comment by Kamran-nust** [comment]
Did you find the solution ?
Because I am facing the exact same problem

**Comment by kli017** [comment]
@Kamran-nust  Not yet, But I switchd my python to 3.6 and no error occurred anymore

**Comment by alalek** [comment]
Fixed several years ago by #7656 (OpenCV 3.2.0).

Marking as invalid because issue was reported against unsupported version (3.1).

**Comment by cemanughian** [comment]
i also have this issue

**Comment by mbelgrat** [comment]
@cemanughian Did you find the solution?

**Comment by ElClopitan** [comment]
Getting a similar error
Generator error: class Tracker (cname=cv::Tracker) already exists
on 4.5.1
Any help would be greatly appreciated.

**Comment by cdangerdouglas** [comment]
I also have this error:
class Tracker (cname=cv::Tracker) already exists

**Comment by Luke1962** [comment]
Me also on jetson nano, building opencv 4.5.1, and after deleting any previous installation file
```
[ 17%] Built target tegra_hal
[ 17%] Built target opencv_cudev
Generator error: class Tracker (cname=cv::Tracker) already exists
modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make:332: recipe for target 'modules/python_bindings_generator/pyopencv_generated_enums.h' failed
make[2]: *** [modules/python_bindings_generator/pyopencv_generated_enums.h] Error 255
CMakeFiles/Makefile2:7948: recipe for target 'modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all' failed
make[1]: *** [modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building C object 3rdparty/libjpeg-turbo/CMakeFiles/libjpeg-turbo.dir/src/jcmaster.c.o
[ 17%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.o

```

the build is succesful if I disable track module

**Comment by andno037** [comment]
It seems that I'm facing the same problem :thinking: 

```
Note: Class detail_GraphCutSeamFinder has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::detail::GraphCutSeamFinderBase, cv::detail::SeamFinder
      Only the first base class will be used
Generator error: class Tracker (cname=cv::Tracker) already exists
```

**Comment by berak** [comment]
> class Tracker (cname=cv::Tracker) already exists

tracking code got moved around in 4.5
please make sure, to use **exactly the same branch** for both opencv / contrib repos.
