### ISSUE TITLE
while importing cv2 in my opencv python code the following Error appear 

### ISSUE THREAD

**Issue by imzi** [opencv/opencv#14986]
##### System information (version)

- OpenCV => 3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio Code
- Python => 2.7

##### Detailed description

Code : 
import cv2

Error:

import cv2
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by dkurt** [comment]
@imzi, Please ask usage questions on forum: http://answers.opencv.org. We use issues for bugs or feature requests.

P.S. Check that Python is 64-bit
