### ISSUE TITLE
I build opencv4.1.1-pre with jasper,but i can read jp2 image

### ISSUE THREAD

**Issue by liangzhongzhuang** [opencv/opencv#14998]
Here is my code.
`#include <opencv2/opencv.hpp>
#include <opencv2/stitching.hpp>
#include <opencv2/imgcodecs.hpp>
using namespace cv;
int main(){
Mat img = imread("/home/B02.jp2");
}
`
And i get this error."error: (-5:Bad argument) Invalid value for parameter OPENCV_IO_ENABLE_JASPER: ON in function 'read' " What's wrong with my code?

**Comment by alalek** [comment]
> OPENCV_IO_ENABLE_JASPER=ON

Where is you got that wrong expression?

Information is available via searching of similar issues. This is really useful skill on GitHub.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
