### ISSUE TITLE
GaussianBlur method, strange border on both ends

### ISSUE THREAD

**Issue by nakamichi3011** [opencv/opencv#15015]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Windows 10 Pro 64bit (10.0, build 17763)
- Compiler => Visual Studio 2017 or Python 2.7.15

##### Detailed description

When using GaussianBlur, when Width = 5 and SigmaX = 9, strange lines are visible at both ends of the image. 

##### Steps to reproduce

Source image
![test](https://user-images.githubusercontent.com/32478538/61028842-a8bfca80-a3f4-11e9-81ca-b14fe33d1be1.jpg)

Output image
![output](https://user-images.githubusercontent.com/32478538/61028846-ab222480-a3f4-11e9-828c-2fb91cc33063.PNG)

below code is same thing happens C++.

```.py
# coding: utf-8

import numpy as np
import cv2

print('OpenCV version : ' + cv2.__version__)

img = cv2.imread('test.bmp')

gau1 = cv2.GaussianBlur(img, (5,5), 8)
gau2 = cv2.GaussianBlur(img, (5,5), 9)
gau3 = cv2.GaussianBlur(img, (5,5), 10)

cv2.imshow('origin', img)
cv2.imshow('gau1', gau1)
cv2.imshow('gau2', gau2)
cv2.imshow('gau3', gau3)

cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by mshabunin** [comment]
Looks like it was broken in #10345, since 3.4.1.
**cc** @terfendail

**Comment by nakamichi3011** [comment]
thanks for information.
