### ISSUE TITLE
No cv::detail::FeaturesFinder in opencv 4.0.1

### ISSUE THREAD

**Issue by GrandmaPeng** [opencv/opencv#15019]
Hi,
I'm trying to implement image stitching with cv::Stitcher. It seems to me the stitcher is using ORB as its feature detection algorithm. 
![image](https://user-images.githubusercontent.com/36261066/61039093-b8451080-a400-11e9-96b5-aa3dbad6e800.png)

I tried to call the function setFeaturesFinder() to change it to SURF, but I didn't see the type detail::FeaturesFinder in the matcher.hpp in opencv 4.0.1 (https://docs.opencv.org/4.0.1/d3/dc9/matchers_8hpp.html), while it does exist in the previous versions before 4.0. Is there any alternative way to set the SURF?

Many thanks.

**Comment by SciMad** [comment]
You are right, the `Stitcher` uses ORB as it's default feature finder (SIFT and SURF are patented but ORB is not. Also, the computation cost and performance of ORB is comparable to the others).

To use SURF as feature finder, you can set the feature finder of the `Stitcher` object by passing `SURF::create()` the public function `Stitcher::setFeaturesFinder()` which takes `Ptr<Feature2D>` as its argument.

Remember however you have to enable `OPENCV_ENABLE_NONFREE` flag during compilation to use  SURF stuffs.

**Comment by SciMad** [comment]
You are right, the `Stitcher` uses ORB as it's default feature finder (SIFT and SURF are patented but ORB is not. Also, the computation cost and performance of ORB is comparable to the others).

To use SURF as feature finder, you can set the feature finder of the `Stitcher` object by passing `SURF::create()` the public function `Stitcher::setFeaturesFinder()` which takes `Ptr<Feature2D>` as its argument. (SURF stuffs are in `cv::xfeatures2d` namespace.)

Remember however you have to enable `OPENCV_ENABLE_NONFREE` flag during compilation to use  SURF stuffs.
