### ISSUE TITLE
how to import lstm net  in opencv?

### ISSUE THREAD

**Issue by cuixing158** [opencv/opencv#15017]
System information (version)

OpenCV => 4.1

Operating System / Platform => Windows 64 Bit

Compiler => Visual Studio 2015

Detailed description

I want to use LSTM network to classify sequence data in OpenCV, but I have seen many tutorials are image classification. The general way is to use Imread to read the image first, use blobFromImage/blobFromImages to convert the image to blob, then pass the blob. Into the network forward. My problem is that the LSTM network input is not an image, it is a sequence of data, 1024*nImages variable size input data, how to pass into the network for forward?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
