### ISSUE TITLE
Mat is constructed incorrectly in debug from an empty ROI 

### ISSUE THREAD

**Issue by alex-176** [opencv/opencv#15018]
##### System information (version)

- OpenCV => 3.4+
- Operating System / Platform => windows
- Compiler => MSVC debug with _DEBUG macro defined

##### Steps to reproduce
The following c++ code fails in assert inside Mat::elemSize
    
    int f()
    {
        cv::Mat1b m(2, 2);
        auto crop = m(cv::Rect(0,0,0,0));
        int res = cv::sum(crop)[0]; // assert fails in Mat::elemSize
        return res;
    }

##### Detailed description:
Matrix ctor calls Mat::release() in case of rows==0 && cols==0.
In debug mode (if _DEBUG is defined) Mat::release() sets dims to 0.
Thus Mat::dims variable has different values in debug and release after the construction of the matrix. 

##### expected behavior:

assert fails only in case of an uninitialized matrix. 
```
cv::sum(cv::Mat()); // should fail
cv::Mat1b m(2, 2);
cv::sum(m(cv::Rect(0,0,0,0))); // should not fail
```
Mat is expected to have the same dims value in release and debug

possible fix:
```
--- a/modules/core/src/matrix.cpp
+++ b/modules/core/src/matrix.cpp
@@ -475,6 +475,7 @@ Mat::Mat(const Mat& m, const Rect& roi)
     if( rows <= 0 || cols <= 0 )
     {
         release();
+        dims = 2;
         rows = cols = 0;
     }
 }
```

**Comment by wisealex2** [comment]
@alalek i thought it's a bug in opencv. but according to your label it's not a bug it's a feature ...

**Comment by alalek** [comment]
Empty ROI is not supported.
Most part of functions is not able to handle it properly. Also there are lack of tests for this case.
There is no way to propagate type of data of empty ROI in current Mat design.

See also #8300

**Comment by alex-176** [comment]
@alalek got it. thanks
