### ISSUE TITLE
libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288

### ISSUE THREAD

**Issue by angyee** [opencv/opencv#15029]
Hi

I have converted the .h5 file  to  .pb file   using https://github.com/bendangnuksung/mrcnn_serving_ready

and converted .pb file to .pbtxt file using  https://gist.github.com/Arafatk/c063bddb9b8d17a037695d748db4f592

after then I have a .pb file and .pbtxt file yes, so I used your blog post   https://www.pyimagesearch.com/2018/11/19/mask-r-cnn-with-opencv/

I have used above generated .pb and .pbtxt to produce masked result image so I am getting the error like this :

python3 mask_rcnn.py --mask-rcnn mask-rcnn-coco --image /home/deepedge/mask_rcnn-master/mask-rcnn-bottle-training-master/dataset/val/car39.jpg

[INFO] loading Mask R-CNN from disk...
[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_tensorflow.GraphDef: 60540:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
Traceback (most recent call last):
File "mask_rcnn.py", line 48, in
net = cv2.dnn.readNetFromTensorflow(weightsPath, configPath)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: mask-rcnn-coco/dent.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'

How to solve?

please help

@dkurt

**Comment by dkurt** [comment]
Please follow https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API and use sample https://github.com/opencv/opencv/blob/master/samples/dnn/mask_rcnn.py. It supports only networks trained in TensorFlow Object Detection API.

**Comment by angyee** [comment]
> Please follow https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API and use sample https://github.com/opencv/opencv/blob/master/samples/dnn/mask_rcnn.py. It supports only networks trained in TensorFlow Object Detection API.

python3   tf_text_graph_mask_rcnn.py --input /home/deepedge/mask_rcnn-master/mask_dent_frozen_graph.pb   --config /home/deepedge/mask_rcnn-master/mask-rcnn/mask_rcnn_inception_v2_coco.config  --output /home/deepedge/mask_rcnn-master/mask-rcnn/dent_graph.pbtxt
Number of classes: 90
Scales:            [0.25, 0.5, 1.0, 2.0]
Aspect ratios:     [0.5, 1.0, 2.0]
Width stride:      16.000000
Height stride:     16.000000
Features stride:   16.000000
Traceback (most recent call last):
  File "tf_text_graph_mask_rcnn.py", line 86, in <module>
    assert(graph_def.node[0].op == 'Placeholder')
IndexError: list index out of range
@dkurt

**Comment by zrx1046** [comment]
Have you solved it? I'm the same question.

**Comment by zrx1046** [comment]
@angyee @dkurt 
Have you solved it? I'm the same question.
