### ISSUE TITLE
DNN: back() called on an empty vector

### ISSUE THREAD

**Issue by NTrixner** [opencv/opencv#15030]
#### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017, ninja

##### Detailed description

When I run the following code, I get "back() called on an empty vector" on the net.forward(output) line.

##### Steps to reproduce
    std::string Main::getOpenCVMessage(std::string filePath) {
      std::stringstream stringStream;
      try{
	    cv::Mat im = cv::imread(filePath, cv::ImreadModes::IMREAD_REDUCED_COLOR_8);
	    int cols = im.cols;
	    int rows = im.rows;
	    cv::Mat blob;
	    cv::dnn::Net net = cv::dnn::readNetFromTensorflow("C:\\path\\frozen_inference_graph.pb", "C:\\path\\mscoco_label_map.pbtxt");
	    cv::dnn::blobFromImage(im, blob, 1.0, cv::Size(cols, rows), cv::Scalar(127.5, 127.5, 127.5), false, false); 
	    net.setInput(blob);
	    std::vector<cv::Mat> output;
	    net.forward(output);
  	    for (cv::Mat m : output) {
	      stringStream << "M= " << m << std::endl;
	    }
	  }
	  catch (std::exception e) {
	    stringStream << e.what() << std::endl;
	  }

	  return stringStream.str();
}

**Comment by dkurt** [comment]
What is `C:\\path\\mscoco_label_map.pbtxt`? Please provide all the files mentioned required to reproduce the code: image (or we can use any image?), `frozen_inference_graph.pb` and `mscoco_label_map.pbtxt`.

**Comment by NTrixner** [comment]
Hi!
The pb can be found here: http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz
The pbtxt is here:
https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt

Thanks a lot

**Comment by dkurt** [comment]
@NTrixner, Please follow corresponding guide: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. `ssd_mobilenet_v2_coco_2018_03_29` is tested.

**Comment by NTrixner** [comment]
That guide only explains tensorflow models in python, I need them in C++

**Comment by dkurt** [comment]
@NTrixner, There is a difference in API only:

C++
```cpp
cv::dnn::Net net = cv::dnn::readNet(...)
```

Python
```python
net = cv.dnn.readNet(...)
```

Check sample for reference: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp

**Comment by NTrixner** [comment]
I got it to work now, seems like I either did the wrong preprocessing for my model or the wrong postprocessing.

**Comment by Sampson-Neko** [comment]
> I got it to work now, seems like I either did the wrong preprocessing for my model or the wrong postprocessing.
Hi, how did you solve the problem? I have the same issue as you, except that my model is faster rcnn resnet50 coco

**Comment by Sampson-Neko** [comment]
@NTrixner

**Comment by NTrixner** [comment]
I honestly just tried a few different models, and with one it worked.
Sorry if that's not very helpful.
