### ISSUE TITLE
core:intrin SSE2 does not compile on vs120 (msvc1800)

### ISSUE THREAD

**Issue by hugolm84** [opencv/opencv#15034]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Windows 10 64bit
- Compiler =>  Visual Studio 2013, VS120 x86 32bit

##### Detailed description
Compiling OpenCV 3.4 using MSVC1800 VS120 for x86 fails due to missing identifiers:

```
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2816): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2836): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2848): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2982): error C3861: '_mm_set1_epi64x': identifiernot found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C2660: '_mm_and_si128' : function does not take 1 arguments [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C2660: '_mm_or_si128' : function does not take 1 arguments [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
``` 

##### Steps to reproduce
Configure CMake:
```
cmake -G "Visual Studio 12 2013" -A "Win32" -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -DBUILD_opencv_videostab=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python_bindings_generator=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_QUIRC=OFF ..
```

Outputs (snippet)
```
-- Detected processor: AMD64
-- sizeof(void) = 4 on 64 bit processor. Assume 32-bit compilation mode
-- Looking for include file intrin.h
-- Looking for include file intrin.h - found

-- General configuration for OpenCV 3.4.7-pre =====================================
--   Version control:               3
--
--   Platform:
--     Timestamp:                   2019-07-12T13:03:27Z
--     Host:                        Windows 10.0.17134 AMD64
--     CMake:                       3.14.0-rc3
--     CMake generator:             Visual Studio 12 2013
--     CMake build tool:            C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe
--     MSVC:                        1800
--
--   CPU/HW features:
--     Baseline:                    SSE SSE2
--       requested:                 SSE2
--     Built as dynamic libs?:      YES
--     C++11:                       YES
--     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe  (ver 18.0.40629.0)
--     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MD /O2 /Ob2 /DNDEBUG
--     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MDd /Zi /Ob0 /Od /RTC1
```

Build:
`cmake --build . -j 16`

**Comment by alalek** [comment]
> MSVS 2013

We don't support this configuration anymore (see related issues about MSVS2013).
Consider migration onto MSVS2015/2017/2019.
Feel free to propose fix via PR for that if you really need it.

**Comment by hugolm84** [comment]
Hm. #11979 seems to consider 4.x and not 3.x. OpenCV 3.X should still support pre c++11 and I guess that's why CV_NOEXCEPT et al exists.

Please clarify

**Comment by alalek** [comment]
Policy about MSVS support is the same:

> OpenCV dev team supports last bugfix updates of two last major MSVS versions

**Comment by hugolm84** [comment]
As OpenCV 3.4 is in maintenance mode, I guess it should not allow for feature growth that requires migration to newer toolsets. In this light, if VS13 was supported before going to maintenance, I suppose VS13 support should continue? Breaking toolset compatibility is probably not inline with "only bugfixes and light features will be accepted.". [1]
It's important to know as many users are stuck on a particular toolset and cannot migrate.

Will OpenCV accept patches that enables compatibility with older (c++11ish) AND newer VS toolsets on the 3.4 branch? If so, I am happy to send in PR's.

Best regards

[1] https://opencv.org/opencv-4-0/

**Comment by alalek** [comment]
Policy about branches: https://github.com/opencv/opencv/wiki/Branches
Optimizations are still accepted into 3.4 branch.

I can say that OpenCV releases don't follow the ideal "semantic versioning" approach. Main reason is limited resources for that.

> Will OpenCV accept patches that enables compatibility with older (c++11ish) AND newer VS toolsets on the 3.4 branch?

Feel free to propose fix via PR (it should not break our current builds and it should be compact enough).

There is no MSVS2013 builders in our infrastructure (since rebuild in mid 2016), so we can't validate such patches for 100% (or guarantee that further PRs will not break something again).

**Comment by neFAST** [comment]
I second this idea that a branch in maintenance mode should not force migration of our toolset.
@hugolm84 Looks like someone has worked on that issue: https://git.kaloncouture.com/lip/OpenCV/commit/7cc8e0ae1589b0dc87a2a0d4be03bb0225826637

**Comment by JulienMaille** [comment]
@hugolm84 have you solved that issue? I lost the code I took from the link above and this link is now unavailable. Any chance you have an archive of their fix? Thanks a lot

**Comment by aopaw** [comment]
> ##### System information (version)
> * OpenCV => 3.4
> * Operating System / Platform => Windows 10 64bit
> * Compiler =>  Visual Studio 2013, VS120 x86 32bit
> 
> ##### Detailed description
> Compiling OpenCV 3.4 using MSVC1800 VS120 for x86 fails due to missing identifiers:
> 
> ```
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2816): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2836): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2848): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2982): error C3861: '_mm_set1_epi64x': identifiernot found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C2660: '_mm_and_si128' : function does not take 1 arguments [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C2660: '_mm_or_si128' : function does not take 1 arguments [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> C:\third_party\opencv\modules\core\include\opencv2/core/hal/intrin_sse.hpp(2983): error C3861: '_mm_set_epi64x': identifier not found [C:\third_party\opencv\build\modules\core\opencv_core.vcxproj]
> ```
> 
> ##### Steps to reproduce
> Configure CMake:
> 
> ```
> cmake -G "Visual Studio 12 2013" -A "Win32" -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -DBUILD_opencv_videostab=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python_bindings_generator=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_QUIRC=OFF ..
> ```
> 
> Outputs (snippet)
> 
> ```
> -- Detected processor: AMD64
> -- sizeof(void) = 4 on 64 bit processor. Assume 32-bit compilation mode
> -- Looking for include file intrin.h
> -- Looking for include file intrin.h - found
> 
> -- General configuration for OpenCV 3.4.7-pre =====================================
> --   Version control:               3
> --
> --   Platform:
> --     Timestamp:                   2019-07-12T13:03:27Z
> --     Host:                        Windows 10.0.17134 AMD64
> --     CMake:                       3.14.0-rc3
> --     CMake generator:             Visual Studio 12 2013
> --     CMake build tool:            C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe
> --     MSVC:                        1800
> --
> --   CPU/HW features:
> --     Baseline:                    SSE SSE2
> --       requested:                 SSE2
> --     Built as dynamic libs?:      YES
> --     C++11:                       YES
> --     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe  (ver 18.0.40629.0)
> --     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MD /O2 /Ob2 /DNDEBUG
> --     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise  /arch:SSE /arch:SSE2 /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MDd /Zi /Ob0 /Od /RTC1
> ```
> 
> Build:
> `cmake --build . -j 16`

Did you solve this? I really don't want to migrate to a higher toolset.

**Comment by JulienMaille** [comment]
I think one solution is to use the knowledge from this SO post: https://stackoverflow.com/a/23496916/1033400
and define:

```c++
#if defined(_MSC_VER) && defined(_M_IX86) && _MSC_VER < 1900
inline __m128i _mm_set_epi64x(__int64 i0, __int64 i1)
{
    union
    {
        int64_t q[2];
        int32_t r[4];
    } u;
    u.q[0] = i0;  u.q[1] = i1;
    // this is inefficient, but other solutions are worse
    return _mm_setr_epi32(u.r[0], u.r[1], u.r[2], u.r[3]);
}

inline __m128i _mm_set1_epi64x(__int64 a)
{
    return _mm_set_epi64x(a, a);
}
#endif
```
@alalek I know this toolchain is not supported, but such a small fix would not hurt. (it will only apply for old 32bit msvc)
