### ISSUE TITLE
ImportError: /usr/lib/python3.7/cv2/cv2.so: undefined symbol: PyInt_Type in Ubuntu19.04

### ISSUE THREAD

**Issue by NewtronReal** [opencv/opencv#15044]
I am a noob in programming. Recently I've got this issue. I've installed opencv using `pip3 install opencv`. When I tried to import it using 
`import cv2` it shows an error message given below.
 ```
 File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /usr/lib/python3.7/cv2/cv2.so: undefined symbol: PyInt_Type
```
Anyone can help me?. Thanks

**Comment by dkurt** [comment]
This is not a right place for usage questions. This is a tracker for bug reports and proposals. Use a forum instead: http://answers.opencv.org.
