### ISSUE TITLE
OPENCV 3.4.4 ARM V8 CROSS COMPILE FAIL.“float32x4x2_t was not declared in this scope"

### ISSUE THREAD

**Issue by yangchengtest** [opencv/opencv#15067]
- OpenCV => 3.4.4
- Operating System / Platform => Ubuntu 16.04
- Compiler => Cmake 3.6.3
gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tgz

modules/core/src/rand.cpp:250:9

float32x4x2_t q = vld2q_f32((const float*)(p + i));
“float32x4x2_t was not declared in this scope"

**Comment by mshabunin** [comment]
Please provide more information about build configuration: build environment, cmake options, etc.

**Comment by yangchengtest** [comment]
I set CV_ENABLE_INTRINSICS=OFF yesterday.
When  I set CV_ENABLE_INTRINSICS=ON,there is no error.Thanks.
