### ISSUE TITLE
Opencv failed to build due to error C2280 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [opencv/opencv#15066]
Environment:
Windows Server 2016 + VS2017 opencv master branch latest srouce code

Opencv failed to build due to error C2280: 'std::unique_ptr<cv::gimpl::FluidAgent,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function on windows with MSVC. It can be first reproduced on 97e88bd reversion on master branch. Could you please look at this issue? Thanks a lot!

 1. git clone https://github.com/opencv/opencv D:\OpenCV\src
 2. git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
 3. Open a VS 2017 x86 prompt and browse to D:\OpenCV
 4. mkdir build_x86 && pushd build_x86
 5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..\src
6. msbuild /p:Configuration=Release;Platform=Win32 build_x86\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true

The whole log file please see attachment.
[log_x64_build.log](https://github.com/opencv/opencv/files/3400407/log_x64_build.log)

ErrorMessage:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory(758): error C2280: 'std::unique_ptr<cv::gimpl::FluidAgent,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function [D:\OpenCV\build_x64\modules\gapi\opencv_gapi.vcxproj]

**Comment by mshabunin** [comment]
**cc** @anton-potapov

**Comment by mshabunin** [comment]
Oh, looks like we already have similar issue.
duplicate #15065
