### ISSUE TITLE
imencode too slow on png file?

### ISSUE THREAD

**Issue by zhu-ty** [opencv/opencv#15068]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 10
- Compiler => VS2015 x64

##### Detailed description

I am currently using cv::imencode to encode my png images, but it seems that it works much more slower than imwrite (with exactly same param), is this a bug?
Images: 16bit 2048x2048
imencode cost about 1.8s/img vs imwrite(including writing to the disk) cost 0.08s/img
I have check the source code however but didn't find out what cause this.

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example


 or attach as .txt or .zip file
-->

    cv::Mat tmp;
    tmp.create(2048,2048,CV_16UC1);
    std::vector<ushort> data;
    cv::imencode(".png", tmp, data);

compared with:

    cv::Mat tmp;
    tmp.create(2048,2048,CV_16UC1);
    std::vector<uchar> data;
    data.reserve(2048*2048*2);
    cv::imwrite("test.png", tmp);

**Comment by mshabunin** [comment]
> `std::vector<ushort> data;`

Why ushort?

---

Checked on Linux - can not reproduce:
```
imencode: 20.637 ms
imwrite: 22.2009 ms
```
```.cpp
    {
        TickMeter tm;
        tm.start();
        cv::Mat tmp;
        tmp.create(2048,2048,CV_16UC1);
        std::vector<uchar> data;
        cv::imencode(".png", tmp, data);
        tm.stop();
        cout << "imencode: " << tm.getTimeMilli() << " ms" << endl;
    }
    {
        TickMeter tm;
        tm.start();
        cv::Mat tmp;
        tmp.create(2048,2048,CV_16UC1);
        std::vector<uchar> data;
        data.reserve(2048*2048*2);
        cv::imwrite("test.png", tmp);
        tm.stop();
        cout << "imwrite: " << tm.getTimeMilli() << " ms" << endl;
    }
```

**Comment by zhu-ty** [comment]
@mshabunin Thanks for your reply, ushort was a mistake written, I use uchar in my actual code.
However it's weird I can't reproduce the problem either(QwQ), let me check my original project code for further information.

**Comment by zhu-ty** [comment]
Alright, I can't reproduce it anymore, anyway I'll close this issue, sorry for the bothering.
