### ISSUE TITLE
Cant store Mat instances in an array after compiling in opencv.js

### ISSUE THREAD

**Issue by slushnys** [opencv/opencv#15062]
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => MacOS
- Compiler => emsdk

##### Detailed description

I'm trying to use a freshly build opencv.js build with increased memory as I need a bit more as the default provides me. This leads me to having even less memory available on the go when compiled a build having a flag of '-s TOTAL_MEMORY=1342177280 '. 
I'm using the latest emsdk and latest opencv version.

**Comment by dkurt** [comment]
@slushnys, please provide a reproducer.

**Comment by slushnys** [comment]
So the issue is that I try to compile a new opencv.js file from 4.1.0 version coming from this repository.

After compilation and including it to the website trying to create mat instances pushing it to an array will result to an error being thrown out that would be equal to the pointer number: $$: { ptr: 6521712 } to give an example. This doesn't say much. Same happends after I increase the WASM_MEMORY flag when compiling. 

repository to see: https://github.com/slushnys/opencv-pointer-exception

After I change the opencv/modules/js/CMakeLists.txt `TOTAL_MEMORY` and inrease it to lets say something about 2GB that would be dividable by 64kB, the compilation gives errors after displaying a very very long list of wasm code from what i could catch a glimpse of.
