### ISSUE TITLE
DISOptical flow result bad

### ISSUE THREAD

**Issue by jjdbear** [opencv/opencv#15070]
##### System information (version)
- OpenCV => : 4.1.0.25
- Operating System / Platform => :Unbuntu16.04 64 Bit
- Compiler => :Pycharm Community Edition2017.2

##### Detailed description

I use Opencv 4.1.0.25 for DIS Optical Flow, code as below , but I got the result  of UseMeanNormalization to calc distances of current imgs and reference image, I got results parameter "flows" all zeros. This could not be true result, for I picture the moving object. I don't know why this happened. And I try on OpenCV Online Document for help, but I could not find detail descriptions on how to use python code of DIS Optical flow

##### Steps to reproduce

    ```.python
    ref = np.uint8(allimgs[0] * 255)
    motions = []
    flows = []
    h, w = ref.shape
    count = h * w
    totalMotions = 0
    #
    dis = cv2.DISOpticalFlow_create(1) #for use PRESET_FAST = 1
    dis.setUseMeanNormalization(True)
    flows.append(np.zeros((h, w), np.float32))
    for i in range(1, len(allimgs)):
        curr_img = np.uint8(allimgs[i] * 255)
        flow = np.zeros((h, w), np.float32)
        dis.calc(ref, curr_img, flow)
        flows.append(flow)
    ```

**Comment by mshabunin** [comment]
Did you check the sample: https://github.com/opencv/opencv/blob/master/samples/python/dis_opt_flow.py ?

**Comment by jjdbear** [comment]
Thank you for your sample， I found where I make mistake and fix the problem. For OpenCV online document is not same as sample code, and little talk about how to use in python,  hope you can add some instructions.
