### ISSUE TITLE
Python binding: VideoCapture(index) freezes the program if the camera is busy

### ISSUE THREAD

**Issue by manusaurio** [opencv/opencv#15074]
##### System information (version)
- OpenCV => 4.1.1-pre
- Python 2 => 2.7.16
- Python 3 => 3.7.3
- Operating System / Platform => Arch Linux 64 Bit
- Compiler => gcc 9.1.0

##### Detailed description

I compiled OpenCV to check if a problem I was having with the Python bindings was because of the repository I installed them from or not: if a camera is busy, trying to start a capture from it will freeze the script. It won't even raise any exceptions, so I'm not sure what's going on. I got the following warnings, though, but I don't know if they are meaningful to this:
- Requesting a video capture from an available camera:
`[ WARN:0] global /home/manuel/ocv/opencv-git/src/opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1`

- Trying to start a capture from a busy camera (freezes after these):
`[ WARN:0] global /home/manuel/ocv/opencv-git/src/opencv/modules/videoio/src/cap_gstreamer.cpp (1738) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src1 reported: Device '/dev/video0' is busy`
`[ WARN:0] global /home/manuel/ocv/opencv-git/src/opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline`
`[ WARN:0] global /home/manuel/ocv/opencv-git/src/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created`

As a side note, I tried this on a Raspberry Pi 3B+ too, running Raspbian, but using [skavrk's prebuilt packages](https://github.com/skvark/opencv-python). The version 2.4.9.1 works fine on Python 2, but 3.4.4 freezes on Python 3.

##### Steps to reproduce

This is one way to reproduce this, either on Python 2 or 3. It doesn't matter if it's OpenCV the one that claims the camera first:

```python
import cv2

cam_a = cv2.VideoCapture(0)
print("Done with cam_a")

cam_b = cv2.VideoCapture(0)
print("Done with cam_b. This message won't be printed")
```

**Comment by mshabunin** [comment]
It could've been fixed in recent #14834 and #14846.

**Comment by manusaurio** [comment]
Alright, I removed 4.1.1-pre and compiled the latest 3.4.7, but it seems to happen anyway:
```pycon
>>> import cv2
>>> cv2.__version__
'3.4.7-pre'
>>> cam1 = cv2.VideoCapture(0)
[ WARN:0] OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
>>> cam2 = cv2.VideoCapture(0)
[ WARN:0] OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src1 reported: Device '/dev/video0' is busy
[ WARN:0] OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```
Can't type anything after that, and it never crashes or raises anything. I tried this on the same system and Python versions mentioned in the first post.

**Comment by manusaurio** [comment]
Tested again on several computers and configurations, version 4.2.0.

It seems it has been fixed, although I'm unsure which PR did the magic. I'm closing the issue now.

**Comment by jaqif** [comment]
Reproduce on 4.2.0 using this https://github.com/mit-han-lab/temporal-shift-module/tree/master/online_demo.

[ WARN:0] global /tmp/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

**Comment by manusaurio** [comment]
The warning itself never was the issue, @jaqif, but the fact that the program freezes and ends with a crash dump.

**Comment by jaqif** [comment]
@manusaurio ok, just notice that when it occur, it can be resolving by adding CAP_V4L on cv2.videocapture function : 
cap = cv2.VideoCapture(0**, cv2.CAP_V4L**)

**Comment by Lyubomyr01** [comment]
> @manusaurio ok, just notice that when it occur, it can be resolving by adding CAP_V4L on cv2.videocapture function :
> cap = cv2.VideoCapture(0 **, cv2.CAP_V4L** )
Jetson Nano
Jetpack 4.4 Production release 
OpenCV 4.1.1
 Thanks a lot, you've solved my problem!!
