### ISSUE TITLE
OpenCV 4.1.0 crashes at imgproc::pointSetBoundingRect(const Mat& points)

### ISSUE THREAD

**Issue by seratg** [opencv/opencv#15078]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => IOS: 12.2
- XCode 11

We have recently upgraded OpenCV from 3.4.6 to 4.1 and a crash appeared at `cv::pointSetBoundingRect(cv::Mat const&)`. Unfortunately, we do not have sample input that would cause the crash as when we run the app in Debug mode or when we add some LOGS, it doesn't crash anymore.

We are not using `cv::pointSetBoundingRect(cv::Mat const&)` directly, but it is being called from `cv::aruco::DetectInitialCandidatesParallel()` and then from `cvFindNextContour()`.

We have finally decided to give OpenCV 4.0.0 a try and we have seen that the crash doesn't happen anymore.

`cv::pointSetBoundingRect(cv::Mat const&)` in OpenCV 3.4.6 and OpenCV 4.1.0 is exactly the same (line by line); however, in OpenCV 4.0.0 the method is completely refactored and easier to understand.

The method in OpenCV 3.4.6: https://github.com/opencv/opencv/blob/33b765d7979fd8a6038026aa44f6ff1a9c082b7b/modules/imgproc/src/shapedescr.cpp#L739

The method in OpenCV 4.1.0: https://github.com/opencv/opencv/blob/371bba8f54560b374fbcd47e7e02f015ac4969ad/modules/imgproc/src/shapedescr.cpp#L739

The method in OpenCV 4.0.0: https://github.com/opencv/opencv/blob/75ed282b20770a7a9b490102fd2e0b4fa26223e5/modules/imgproc/src/shapedescr.cpp#L737

As you will see, OpenCV 3.4.6 and 4.1.0(where crash happens) have exactly the same code, but 4.0.0 has a refactored version.

Maybe something went wrong during a merge request ?

P.S. On desktop the crash doesn't happen.

Thank you,
Serhat

**Comment by alalek** [comment]
Could you try latest code from master branch? (perhaps this fix may help to you: #14889)

No significant difference is expected between master/3.4 branch for this function.

**Comment by seratg** [comment]
Just tried the master branch out and seems to be working fine. Thanks
