### ISSUE TITLE
InferenceEngineException  Failed to infer shapes for Convolution layer 

### ISSUE THREAD

**Issue by paulbauriegel** [opencv/opencv#15094]
While trying to predict an embedding vector from an image using a pretrained model from the openvino model zoo I got an InferenceEngineException

##### System information (version)
- OpenCV => 4.1.1-pre https://github.com/opencv/opencv/commit/199ddff13b73071529a42cff97ee8286cfc15d02
- OS => Linux Ubuntu 19.04 64bit
- Compiler => gcc 8.3.0

##### Detailed description
```
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Failed to infer shapes for Convolution layer (410) with error: New shapes [257,1,128,128] make Kernels(3x3), Channels(1), Output depth(64), Groups(1) not matching weights size: 576 vs 1728
Aborted (core dumped)
```

##### Steps to reproduce
- `wget https://download.01.org/opencv/2019/open_model_zoo/R1/20190404_140900_models_bin/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.xml`
- `wget https://download.01.org/opencv/2019/open_model_zoo/R1/20190404_140900_models_bin/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.bin`

```python
import cv2
weights_path = "face-reidentification-retail-0095.bin"
config_path = "ace-reidentification-retail-0095.xml"
net = cv2.dnn.readNet(weights_path, config=config_path, framework="DLDT")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
img_path = "opencv_frame_0.png"
ref_image = cv2.imread(img_path)
blob = cv2.dnn.blobFromImages(ref_image, 1., (128, 128), True, crop=True)
net.setInput(blob)
res = net.forward()
print(res[0])
```

**Comment by paulbauriegel** [comment]
[cmake.log](https://github.com/opencv/opencv/files/3410444/cmake.log)

**Comment by dkurt** [comment]
> weights_path = "face-reidentification-retail-0095.bin"
config_path = "ace-reidentification-retail-0095.xml"

Check the .xml please

**Comment by paulbauriegel** [comment]
@dkurt Thanks for the fast reply. I rechecked the arguments. `blob.shape -> (257, 1, 128, 128)` because of a spelling error (blobFromImages vs blobFromImage). Changed the line to:
`blob = cv2.dnn.blobFromImage(ref_image, img_norm, (128, 128), True, crop=True)`
and its working now.
