### ISSUE TITLE
Segmentation fault when creating cv::Mat in std::thread

### ISSUE THREAD

**Issue by tvabramov** [opencv/opencv#15108]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Windows 10
- Compiler => GNU 5.3.0

##### Detailed description

Hello there! I get segmentation fault when create a cv::Mat object in a C++ std::thread. I've seen some similar problems around but not quite the same. Also, the ones I've found were not solved.

##### Steps to reproduce

```.cpp
#include <iostream>
#include <thread>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main(int argc, char *argv[])
{	
	auto func = []() {
		Mat _frame = Mat::zeros(cv::Size(320,240), CV_8UC3);
		cout << "Done!" << endl;
	};
		
	std::thread thread(func);
		
	thread.join();
		
	return EXIT_SUCCESS;
}
```

This simple program crashes with this debug message:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 7124.0x28f8]
0x64023058 in cv::MatOp_Initializer::makeExpr(cv::MatExpr&, int, cv::Size_<int>, int, double) ()
   from C:\OpenCV\install\x86\mingw\bin\libopencv_core411.dll
```

Also I've tried to use std::async. If I launch it with "launch::deferred" flag, it works. But when I use "launch::async", I have the same error. At last, I've tried to capture a frame and pass it in std::async:

```.cpp
VideoCapture cap(0);
			
Mat frame;
cap >> frame;
	
auto asyncRec = async(launch::async, [](Mat _frame) -> void {
		
	Mat frame2;
		
	resize(_frame, frame2, Size(300, 300));
		
	cout << "Done!" << endl;		
		
}, frame);
		
asyncRec.get();
```

It crashed with:
```
[Switching to Thread 6252.0x22bc]
0x71684f42 in cv::resizeGeneric_Invoker<cv::HResizeLinear<unsigned char, int, short, 2048, cv::HResizeNoVec>, cv::VResizeLinear<unsigned char, int, short, cv::FixedPtCast<int, unsigned char, 22>, cv::VResizeLinearVec_32s8u> >::operator()(cv::Range const&) const () from C:\OpenCV\install\x86\mingw\bin\libopencv_imgproc411.dll
```

But, if I replace "launch::async" with "launch::deferred", it works fine. It seems I can't create cv::Mat object in std::thread at all...

**Comment by alalek** [comment]
> MinGW

is not supported officially.
Expect community help only.

> GCC 5.3.0

Try to upgrade.
Also learn about MinGW threading modes (posix/win32).

**Comment by tvabramov** [comment]
Thank you for your response!
I've updated my GCC to 8.1.0 (posix thread model) and it fixed this problem.

Thank you!

**Comment by sepehrhm** [comment]
This seems like such a simple thing to be fixed by an overkill of upgrading the system's compiler version. Any other ways around this issue?
