### ISSUE TITLE
Tensorflow Object detection with multiple camera

### ISSUE THREAD

**Issue by gkartik6** [opencv/opencv#15117]
I tried with a single camera and my object-detection model is working fine but when I tried with two cameras then below errors comes up:

_* Running on http://192.168.43.70:8888/ (Press CTRL+C to quit)
192.168.43.70 - - [22/Jul/2019 12:26:51] "GET / HTTP/1.1" 200 -
Starting camera thread.
Starting camera thread.
192.168.43.70 - - [22/Jul/2019 12:26:54] "GET /video_feed1 HTTP/1.1" 200 -
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/vvdn/flask/flask_video/base_camera.py", line 93, in _thread
for frame in frames_iterator:
File "/home/vvdn/flask/flask_video/camera_opencv.py", line 54, in frames
cvOut = cvNet.forward()
error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp:705: error: (-215:Assertion failed) prior_width > 0 in function 'DecodeBBox'

Exception in thread Thread-5:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/vvdn/flask/flask_video/base_camera1.py", line 93, in _thread
for frame in frames_iterator:
File "/home/vvdn/flask/flask_video/camera_opencv.py", line 99, in frames
cvOut = cvNet.forward()
error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp:705: error: (-215:Assertion failed) prior_width > 0 in function 'DecodeBBox'_

Please help me, its already been 7 days and I'm not able to solve this issue.

**Comment by dkurt** [comment]
@gkartik6, No one could help you unless you specify the way two reproduce this issue.

What does it mean to run the network with two cameras? Is it a batch or two instances of `cv::dnn::Net`? Which model is used (provide link to download this model)?

**Comment by gkartik6** [comment]
Hi,

Thanks for your quick response.

Please find the below files which I'm using to open two cameras in single URL to detect the trained object. 
To reproduce this issue, download files and convert these files in .py files and run _main.py_ script.

I'm using the two instances of cv::dnn::Net and the model which is I'm using is my custom model to detect industrial helmet and industrial google. You can use any other model and change the path in the file. If you want then I can share my model also.

[camera_opencv.txt](https://github.com/opencv/opencv/files/3417035/camera_opencv.txt)
[base_camera.txt](https://github.com/opencv/opencv/files/3417036/base_camera.txt)
[base_camera1.txt](https://github.com/opencv/opencv/files/3417037/base_camera1.txt)
[main.txt](https://github.com/opencv/opencv/files/3417038/main.txt)

**Comment by dkurt** [comment]
@gkartik6, can you provide a reproducer? The simpler the code the faster someone could check if it's a bug in OpenCV or not.

**Comment by gkartik6** [comment]
Hi,
Run this code with two cameras connected it will give the OpenCV error.

import cv2 as cv
from base_camera import BaseCamera
from base_camera1 import BaseCamera1

from webcamvideostream import WebcamVideoStream
import numpy as np
import time
import os
from threading import Thread

flaskDir='/home/vvdn/flask/2object_detect'
labelsPath = os.path.sep.join([flaskDir,"3object_detect_classes.txt"])
labels = open(labelsPath).read().strip().split("\n")

# BGR
classColors = [ (23, 230, 210), (0, 165, 255), (192, 192, 192)]
if len(labels) > 3:
    classColors = np.append(classColors, np.random.randint(0, 255, size=(len(labels)-3, 3), dtype="uint8", axis=0))

modelDir='/home/vvdn/flask/2object_detect'
model = os.path.sep.join([modelDir, "frozen_inference_graph.pb"])
graph = os.path.sep.join([modelDir, "graph.pbtxt"])
if os.environ.get('THRESHOLD'):
    confThreshold = float(os.environ.get('THRESHOLD'))
else:
    confThreshold = 0.6
    nmsThreshold = 0.4

cvNet = cv.dnn.readNetFromTensorflow(model, graph)

class Camera1(BaseCamera):
    video_source = 0


    @staticmethod
    def set_video_source(source):
        Camera1.video_source = source

    @staticmethod
    def frames():
        camera = cv.VideoCapture(Camera1.video_source)
        if not camera.isOpened():
            raise RuntimeError('Could not start camera.')

        while True:
            # read current frame
            ret, img0 = camera.read()

            rows = img0.shape[0]
            cols = img0.shape[1]

            cvNet.setInput(cv.dnn.blobFromImage(img0, size=(300, 300), swapRB=True, crop=False))
            cvOut = cvNet.forward()

            for detection in cvOut[0,0,:,:]:
                score = float(detection[2])
                if score > 0.87:
                    left = int(detection[3] * cols)
                    top = int(detection[4] * rows)
                    right = int(detection[5] * cols)
                    bottom = int(detection[6] * rows)
                    id = int(detection[1] - 1)
                    color = classColors[id]
                    cv.rectangle(img0, (left, top), (right, bottom), color, thickness=2)
                    text = "{}: {:.2f}".format(labels[id], score)
                    cv.putText(img0, text, (left, top - 5), cv.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)


            # encode as a jpeg image and return it
            yield cv.imencode('.jpg', img0)[1].tobytes()


class Camera2(BaseCamera1):
    video_source = 1

    @staticmethod
    def set_video_source(source):
        Camera2.video_source = source

    @staticmethod
    def frames():
        camera = cv.VideoCapture(Camera2.video_source)
        if not camera.isOpened():
            raise RuntimeError('Could not start camera.')

        while True:
            # read current frame
            ret1, img = camera.read()

            rows1 = img.shape[0]
            cols1 = img.shape[1]

            cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
            cvOut = cvNet.forward()

            for detection in cvOut[0,0,:,:]:
                score = float(detection[2])
                if score > 0.87:
                    left1 = int(detection[3] * cols1)
                    top1 = int(detection[4] * rows1)
                    right1 = int(detection[5] * cols1)
                    bottom1 = int(detection[6] * rows1)
                    id = int(detection[1] - 1)
#                    print(score, id, left, top, right, bottom)
                    color = classColors[id]
                    cv.rectangle(img, (left1, top1), (right1, bottom1), color, thickness=2)
                    text = "{}: {:.2f}".format(labels[id], score)
                    cv.putText(img, text, (left1, top1 - 5), cv.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

            # encode as a jpeg image and return it
            yield cv.imencode('.jpg', img)[1].tobytes()

**Comment by alalek** [comment]
... provided code is not readable and not complete ...

You can't share/use object (like `cvNet`) between both threads.
See threading safety notice in OpenCV introduction.
Each thread should have self-owned object instance (python "shadow" copy doesn't work too).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
