### ISSUE TITLE
Raspberry internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by karnhack** [opencv/opencv#15116]
Can anyone help me with this compilation error? Thanks

Raspberry Pi 3 B+
OpenCV 4.1.0

`cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
-D ENABLE_NEON=ON \
-D ENABLE_VFPV3=ON \
-D BUILD_TESTS=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D CMAKE_SIZEOF_VOID_P=4 \
-D BUILD_opencv_python3=TRUE \
-D PYTHON3_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so \
-D BUILD_EXAMPLES=OFF ..`

Error during compilation:

`[ 98%] Built target gen_opencv_python_source
[ 98%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
during RTL pass: expand
In file included from /home/pi/opencv/modules/python/src2/cv2.cpp:1722:
/home/pi/opencv/build/modules/python_bindings_generator/pyopencv_generated_types.h: In function ‘PyObject* pyopencv_cv_detail_detail_BlocksGainCompensator_apply(PyObject*, PyObject*, PyObject*)’:
/home/pi/opencv/build/modules/python_bindings_generator/pyopencv_generated_types.h:79645:17: internal compiler error: Segmentation fault
     const char* keywords[] = { "index", "corner", "image", "mask", NULL };
                 ^~~~~~~~
0x76a7311f ???
	../sysdeps/unix/sysv/linux/arm/sigrestorer.S:64
0x76a5d717 __libc_start_main
	/build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:63: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:11793: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`

https://pastebin.com/5FnMjAQe
Complete compilation: https://pastebin.com/ujKu1mRT

**Comment by karnhack** [comment]
What does the label: question (invalid tracker)?
I edited the previous ticket adding the whole compilation: https://pastebin.com/ujKu1mRT

**Comment by andreygursky** [comment]
Related: https://github.com/opencv/opencv/issues/13475

**Comment by tomoaki0705** [comment]
https://github.com/opencv/opencv/issues/13475#issuecomment-448415086

**Comment by karnhack** [comment]
Is this also a memory problem?

`[ 98%] Linking CXX shared module ../../lib/python3/cv2.cpython-37m-arm-linux-gnueabihf.so
/usr/bin/ld: error: ../../lib/libopencv_stitching.so.4.1.0: file too short
collect2: error: ld returned 1 exit status
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:129: lib/python3/cv2.cpython-37m-arm-linux-gnueabihf.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:11793: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2`

**Comment by alalek** [comment]
> file too short

I believe you have zero sized file (due previous compilation crash caused by lack of available memory).
Yes, it is still not an OpenCV problem (there is nothing to fix in OpenCV).

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
