### ISSUE TITLE
Reason for different prediction times on CPU with same processor but different RAM capacities for Opencv-dnn-yolo?

### ISSUE THREAD

**Issue by chetansarmak** [opencv/opencv#15113]
##### System information (version)
- OpenCV 4.1.0
- Operating System / Platform => Linux System -(Intel -i3)

##### Detailed description

when I try to run the openCV dnn yolo detection module on System with same processor but different RAM i.e Intel-i3 processor - 4GB RAM & 8GB RAM . The prediction time for both RAM configuration are:
For 4GB : 0.14 sec
For 8GB : 0.07 sec
But when I checked the memory occupied in CPU by running command - `watch -n 0.5 free -m`  , it's taking nearly  ~110 MB on both Systems with 4GB & 8GB and same CPU utility .

Can someone tell me, what might be the reason for different prediction times ?

Thanks in advance!!

**Comment by dkurt** [comment]
The difference in RAM is not only in volume. Check `sudo dmidecode --type 17`
