### ISSUE TITLE
Feature request - SiamRPN++ Object Tracker

### ISSUE THREAD

**Issue by AlexeyAB** [opencv/opencv#15119]
Feature request - **SiamRPN++** as the most accurate Object Tracker - comparison: https://paperswithcode.com/sota/visual-object-tracking-on-vot201718

* **SiamRPN++**: https://paperswithcode.com/paper/siamrpn-evolution-of-siamese-visual-tracking
    * paper: https://arxiv.org/abs/1812.11703
    * http://bo-li.info/SiamRPN++/
    * source code: https://github.com/STVIR/pysot

**Comment by devanshbatra04** [comment]
I want to work on this. Some directions would be great @alalek @dkurt

**Comment by dkurt** [comment]
For now we are working on enabling https://github.com/foolwood/DaSiamRPN

/cc @ieliz

**Comment by devanshbatra04** [comment]
Is there a PR underway for this (or a relevant issue)?

I am looking for a challenging feature preferably in dnn/imgproc to keep myself busy.

**Comment by dkurt** [comment]
I think that the most challenging now is a number of opened issues related to dnn module: https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3A%22category%3A+dnn%22 .So if you can resolve any of them that would be useful.

**Comment by bhack** [comment]
Check GSOC WIP at https://github.com/opencv/opencv/pull/17647

**Comment by bhack** [comment]
@l-bat Can you ask internally if we could maintain the ONNX exporting code in a not runnable (textfile?) on the repository?
I think It could enable:
 - the standard commit/revision flow also for the exporting component
- It could be useful for developers, after merge, to easly find the reference exporting instead to search for description on the PR that introduced the new model.

**Comment by l-bat** [comment]
see #17647

**Comment by AlexeyAB** [comment]
@jinyup100 Great work!
