### ISSUE TITLE
imdecode  is slow when handle big picture

### ISSUE THREAD

**Issue by AnberLu** [opencv/opencv#15126]
when i used imdecode handle big picture (like 10000*1000), the speed is very slow (about 700ms-5000ms), anyone  had method  speed  it up？

**Comment by mshabunin** [comment]
`imdecode` uses different 3rdparty libraries under the hood. Please add more information about your platform and OpenCV build configuration. Add an application reproducing the issue.

**Comment by AnberLu** [comment]
@mshabunin 

code

```
color = ::cv::imdecode(data, CV_LOAD_IMAGE_COLOR);
```

env：
```
CentOS Linux release 7.2.1511 (Core)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
```

**Comment by mshabunin** [comment]
@AnberLu , this information is not enough. Depending on `data` format (PNG, JPEG, etc.) different libraries can handle processing. Please add cmake build configuration (`cv::getBuildInformation()`), input file and full application code.

**Comment by FishermanZzhang** [comment]
@mshabunin 

this is my environment  (same as @AnberLu ): 
General configuration for OpenCV 3.4.0 =====================================
  Version control:               66d4f94-dirty

  Platform:
    Timestamp:                   2018-01-16T07:19:52Z
    Host:                        Linux 3.10.0-229.20.1.el7.x86_64 x86_64
    CMake:                       3.8.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/gmake
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
      SSE4_1 (3 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /usr/bin/c++  (ver 4.8.5)
    C++ flags (Release):         -std=c++11   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -std=c++11   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          dl m pthread rt
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc ml objdetect photo python2 python_bindings_generator shape stitching superres ts video videoio videostab
    Disabled:                    js world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python3 viz
    Applications:                tests perf_tests apps
    Documentation:               YES (/usr/bin/doxygen 1.8.5)
    Non-free algorithms:         NO

  GUI: 
    GTK+:                        YES (ver 2.24.28)
      GThread :                  YES (ver 2.46.2)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /lib64/libz.so (ver 1.2.7)
    JPEG:                        /lib64/libjpeg.so (ver )
    WEBP:                        /lib64/libwebp.so (ver encoder: 0x0201)
    PNG:                         /lib64/libpng.so (ver 1.5.13)
    TIFF:                        /lib64/libtiff.so (ver 42 / 4.0.3)
    JPEG 2000:                   /lib64/libjasper.so (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    gPhoto2:                     NO

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   /export/chenbiaolong/working/fashion/3rdparty/opencv/build/3rdparty/ippicv/ippicv_lnx
    Intel IPP IW:                sources (2017.0.3)
              at:                /export/chenbiaolong/working/fashion/3rdparty/opencv/build/3rdparty/ippicv/ippiw_lnx
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO

  OpenCL:                        YES (no extra features)
    Include path:                /export/chenbiaolong/working/fashion/3rdparty/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 2:
    Interpreter:                 /usr/bin/python2.7 (ver 2.7.5)
    Libraries:                   /lib64/libpython2.7.so (ver 2.7.5)
    numpy:                       /usr/lib64/python2.7/site-packages/numpy/core/include (ver 1.12.0)
    packages path:               lib/python2.7/site-packages

  Python (for build):            /usr/bin/python2.7

  Java:
    ant:                         NO
    JNI:                         /usr/lib/jvm/java/include /usr/lib/jvm/java/include/linux /usr/lib/jvm/java/include
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Install to:                    /opm
-----------------------------------------------------------------

**Comment by FishermanZzhang** [comment]
And the source data is jpeg format @mshabunin

**Comment by mshabunin** [comment]
Can not reproduce:
```.cpp
int main()
{
    {
        Mat img(10000, 1000, CV_8UC3, Scalar::all(0));
        imwrite("test.jpg", img);
    }
    ifstream f("test.jpg", ios::binary | ios::ate);
    f.seekg(0, ios_base::end);
    const unsigned long long sz = f.tellg();
    f.seekg(0);
    cout << "Read " << sz << " bytes" << endl;
    vector<char> data(sz, 0);
    f.read(&(data.at(0)), sz);
    f.close();
    TickMeter tm;
    tm.start();
    Mat m = imdecode(data, IMREAD_COLOR);
    tm.stop();
    cout << "Read image " << m.size() << " in " << tm.getTimeMilli() << " ms" << endl;
}
```
Output:
```
Read 158127 bytes
Read image [1000 x 10000] in 58.3129 ms
```
