### ISSUE TITLE
Release contrib pack or add ability to filter a tag/release in build farm

### ISSUE THREAD

**Issue by iamareebjamal** [opencv/opencv#15138]
OpenCV Build Farm builds all forms of packages nightly, on pull requests and merges. 

There is ability to filter between build platform, type (nightly, merge, pre-commit), but no way to filter for an actual release.

In an ideal scenario, OpenCV build farms should generate Android aar files and publish the package since all the building and testing is already done for these. But as it is low priority (#4588), a lot of 3rd party developers have created repositories to publish the aar files, like https://github.com/quickbirdstudios/opencv-android, https://github.com/piruin/opencv-android, https://github.com/jewelzqiu/opencv-android-library, and mine (https://github.com/iamareebjamal/opencv-android)

Needless to say, they quickly become obsolete as maintainers can't continue to maintain them once their usage is fulfilled. So, if OpenCV devs cannot publish the packages on a maven repository, at least they can make the process easier for other developers to access their builds, so they can automate the process of releasing an aar/jar files on each OpenCV release. 

The Android SDK is released as an artifact with each release like https://github.com/opencv/opencv/releases/download/4.1.0/opencv-4.1.0-android-sdk.zip. which makes it easy for 3rd party devs to automate the release. Just change 4.0.1 to 4.1.0 and it will most likely work.

The contrib android pack is not released but built on each might

So, it would not take much to either:
- Also add the artifact in release 
- Make it easier to get the built artifacts for each release from build farm

https://pullrequest.opencv.org/buildbot/waterfall?tag=android_pack

If there is a simple way to get an android pack for a particular release using TAG 4.1.0, or even the commit ID/hash, it can be automatically fetched and downloaded, and won't need to be built locally as it already is built literally each day.

I hope maintainers consider this request as it is already quite painful to download the libraries and it is ironic as well, because these packs are built each day, and still 3rd party devs have to publish them from their forks

**Comment by mshabunin** [comment]
Try this Maven repository: https://search.maven.org/artifact/org.bytedeco/opencv/4.1.0-1.5.1/jar

**Comment by iamareebjamal** [comment]
I want aar files for android. https://github.com/quickbirdstudios/opencv-android release 4.1.0 contrib package today but after 4 months of 4.1.0 release. If the sdk files are machine accessible, then I can automate the process of release, removing human intervention, so that even if I am unavailable and uninterested in maintaining the packages, they still are released automatically. 

However, stressing again that it **should** and can ideally happen through open cv build farms only, because they already have testing and packaging infrastructure in place, but this is a pragmatic solution for now.

**Comment by alalek** [comment]
Artifacts from BuildBot is for development/internal testing purposes only. Please avoid regular downloads from our CI - internet channel is very limited (without any CDN).

Publishing of nightly builds are out of our plans and available resources (we don't want to track extra issues from these nightly binaries too).
Also there are no plans to publish opencv_contrib releases.

OpenCV CI is open (including logs). There is no technical problem to build package on your side for your needs (build flags).

**Comment by iamareebjamal** [comment]
There is no need to publish nightly builds, just making release builds accessible is enough. I don't understand why anyone should build on their side when it is already happening in a tested environment on OpenCV build farm. Needless to say, a lot of people want #4588 to happen, but OpenCV devs neither want to put effort into releasing official maven packages of the library, nor they want to make this process easier for others who want to automate the process

**Comment by mshabunin** [comment]
@iamareebjamal , the Maven repository I mentioned provides packages with contrib modules for PC, Android and iOS. It is already automated, just add one line to your Gradle project: `implementation 'org.bytedeco:opencv:4.1.0-1.5.1'`. Or take raw files here: https://repo1.maven.org/maven2/org/bytedeco/opencv/4.1.0-1.5.1/
4.1.0 is the latest release.

Packaging and distributing software is more complex task than just build and publish the archive.

**Comment by iamareebjamal** [comment]
> Packaging and distributing software is more complex task than just build and publish the archive.

How?

**Comment by alalek** [comment]
> I couldn't find an aar file with all platforms like arm, x86, x64. Only individual ones.

They want this build config. You want another.
Just because there is no gold setup for build flags for all purposes.

**Comment by iamareebjamal** [comment]
There is. Almost every Android developer wants either of 2 builds, core aar with all platforms, and contrib aar with all platforms. Both of which are built on build farms regularly. Even Java devs want a common jar for cross platform access. There's no mix and match required actually. Why do you think that up to 50 people have created their own maven repositories but only host same aars? Because everyone wants only those specific ones

**Comment by mshabunin** [comment]
> Almost every Android developer wants either of 2 builds, core aar with all platforms, and contrib aar with all platforms.

There are several options laying deeper:
* ENABLE_NONFREE - to enable patented algorithms in contrib (many people want them)
* CPU optimizations/dispatching - affect compatibility, binary size and execution speed
* built-in libraries - libjpeg, libpng, libtbb, etc., some developers need them, others not
* static or dynamic binaries, Java bindings combined with native part into one huge library or separate C++ and Java binaries
* Android specific options (MediaNDK support) which can limit supported platforms by setting high minimal native API level

> Even Java devs want a common jar for cross platform access.

Wouldn't maven/gradle automatically download packages for all needed platforms? I believe most desktop Java devs do not need gigantic package for arm/aarch64/i386/x86_64/ppc64le, but single one for x86_64.

**Comment by iamareebjamal** [comment]
For Android, sane defaults can be used for core and contrib packages, like the Android SDK released with default build. This is what other libraries like tensorflow do. You can use unoptimized packages from pip and elsewhere, and if you want to customize, compile on your own. Nobody is going to disagree with that.

About java devs, they'd like the JAR to be as platform agnostic as possible. I simply know no java dev who would like to compromise the build once run anywhere jar for few megabytex, but there might be. But at least it should be easier for android devs to use the OpenCV SDK instead of importing the code and maintaining it with their software
