### ISSUE TITLE
Error in loading .pb file from readNetFromTensorflow?

### ISSUE THREAD

**Issue by ibrahimLearning** [opencv/opencv#15142]
I have created .pb file from .h5 file using the following code:

`model = modellib.MaskRCNN(mode="inference", 
                          config=inference_config,
                          model_dir=MODEL_DIR)
model.load_weights(weights_path, by_name=True)  #, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask"]

def freeze_session(session, cpkt_name, keep_var_names=None, output_names=None, clear_devices=True):
    graph = sess.graph
    sess.run(tf.global_variables_initializer())
    saver=tf.train.Saver()    
    saver.save(sess,cpkt_name)

    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.compat.v1.global_variables()).difference(keep_var_names or []))

        output_names = output_names or []
        input_graph_def = graph.as_graph_def()
        
        
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        
        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        
        return frozen_graph, output_names

def freeze_model(model, directory, name, cpkt_name, pbtxt_file):
    frozen_graph, output_names = freeze_session(sess, cpkt_name, 
                                                output_names=[out.op.name for out in model.outputs][:4])
    
    #tf.train.write_graph(frozen_graph, directory, name , as_text=False)
    #graph_io.write_graph(frozen_graph, directory, pbtxt_file, as_text=True)
    #graph_io.write_graph(frozen_graph, directory, name, as_text=False)
    
    frozen_graph_path=os.path.join(directory,name).replace("\\","/")
    pbtxt_path=os.path.join(directory,pbtxt_file).replace("\\","/")
    
    input_names=[inp.op.name for inp in model.inputs][:4]
    print(output_names)
    print(input_names)
   
    with tf.gfile.GFile(frozen_graph_path,'wb') as f:
        f.write(frozen_graph.SerializeToString())
        
    with tf.gfile.GFile(pbtxt_path,'w') as f:
        f.write(frozen_graph.SerializeToString())`
When I am going to load .pb file using the following code:
`net=cv2.dnn.readNetFromTensorflow('Tensorflowmodel/mask_frozen_graph.pb')`
it gives the following error:

> error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1383: error: (-215:Assertion failed) scaleMat.type() == CV_32FC1 in function 'cv::dnn::dnn4_v20190122::`anonymous-namespace'::TFImporter::populateNet'

Where is my wrong? Would you give any suggestion please? My opencv-python version is 4.1.0

@dkurt @peters @blebo @alalek

**Comment by dkurt** [comment]
Please follow issue template and provide all the details to reproduce issue.

**Comment by dkurt** [comment]
Closing it unless we have a reproducer. Thanks!

**Comment by zhoujinhai** [comment]
> I have created .pb file from .h5 file using the following code:
> 
> `model = modellib.MaskRCNN(mode="inference",
> config=inference_config,
> model_dir=MODEL_DIR)
> model.load_weights(weights_path, by_name=True) #, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask"]
> 
> def freeze_session(session, cpkt_name, keep_var_names=None, output_names=None, clear_devices=True):
> graph = sess.graph
> sess.run(tf.global_variables_initializer())
> saver=tf.train.Saver()
> saver.save(sess,cpkt_name)
> 
> ```
> with graph.as_default():
>     freeze_var_names = list(set(v.op.name for v in tf.compat.v1.global_variables()).difference(keep_var_names or []))
> 
>     output_names = output_names or []
>     input_graph_def = graph.as_graph_def()
>     
>     
>     if clear_devices:
>         for node in input_graph_def.node:
>             node.device = ""
>     
>     frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(
>         session, input_graph_def, output_names, freeze_var_names)
>     
>     return frozen_graph, output_names
> ```
> 
> def freeze_model(model, directory, name, cpkt_name, pbtxt_file):
> frozen_graph, output_names = freeze_session(sess, cpkt_name,
> output_names=[out.op.name for out in model.outputs][:4])
> 
> ```
> #tf.train.write_graph(frozen_graph, directory, name , as_text=False)
> #graph_io.write_graph(frozen_graph, directory, pbtxt_file, as_text=True)
> #graph_io.write_graph(frozen_graph, directory, name, as_text=False)
> 
> frozen_graph_path=os.path.join(directory,name).replace("\\","/")
> pbtxt_path=os.path.join(directory,pbtxt_file).replace("\\","/")
> 
> input_names=[inp.op.name for inp in model.inputs][:4]
> print(output_names)
> print(input_names)
> 
> with tf.gfile.GFile(frozen_graph_path,'wb') as f:
>     f.write(frozen_graph.SerializeToString())
>     
> with tf.gfile.GFile(pbtxt_path,'w') as f:
>     f.write(frozen_graph.SerializeToString())`
> ```
> 
> When I am going to load .pb file using the following code:
> `net=cv2.dnn.readNetFromTensorflow('Tensorflowmodel/mask_frozen_graph.pb')`
> it gives the following error:
> 
> > error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1383: error: (-215:Assertion failed) scaleMat.type() == CV_32FC1 in function 'cv::dnn::dnn4_v20190122::`anonymous-namespace'::TFImporter::populateNet'
> 
> Where is my wrong? Would you give any suggestion please? My opencv-python version is 4.1.0
> 
> @dkurt @peters @blebo @alalek

I have the same problem, Have you solved it?
