### ISSUE TITLE
Oudated link in sample

### ISSUE THREAD

**Issue by ChillerDragon** [opencv/opencv#15148]
https://github.com/opencv/opencv/blob/4.1.0/samples/python/camshift.py#L11

http://www.robinhewitt.com/research/track/camshift.html

**Comment by shahianshu** [comment]
Can i solve this issue ?

**Comment by sturkmen72** [comment]
which is the best solution ?

1. removing the link
2. replacing with http://web.archive.org/web/20070331065631/http://www.robinhewitt.com/research/track/camshift.html

**Comment by craterkamath** [comment]
if @shahianshu is not working on the issue, I'd like to fix this issue. Can someone assign this issue to me?

**Comment by crackwitz** [comment]
maybe use http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.14.7673
that's a link to the original paper, not some seemingly random web page
also, you don't need anything assigned. just work on it, then make a pull request.
