### ISSUE TITLE
Error with cmake build_type Installing OpenCV 4.0.0 on mac 

### ISSUE THREAD

**Issue by Pebblebro** [opencv/opencv#15153]
- OpenCV => 4.0.0
- Operating System / Platform => mac OS 10.14.6 "Mojave"
- Compiler => XCode

I'm trying to install opencv4 on a mac using the instruction provided by https://www.pyimagesearch.com/2018/08/17/install-opencv-4-on-macos/ .
I've arrived at the steps for CMake and am stuck here with errors I don't understand.
Any help would be appreciated.

This is what I enter in terminal:
(cv) Alex-2:build Alex$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
>  -D CMAKE_INSTALL_PREFIX=/usr/local \
>     -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
>     -D PYTHON3_LIBRARY=`python -c 'import subprocess ; import sys ; s = subprocess.check_output("python-config --configdir", shell=True).decode("utf-8").strip() ; (M, m) = sys.version_info[:2] ; print("{}/libpython{}.{}.dylib".format(s, M, m))'` \
>     -D PYTHON3_INCLUDE_DIR=`python -c 'import distutils.sysconfig as s; print(s.get_python_inc())'` \
>     -D PYTHON3_EXECUTABLE=$VIRTUAL_ENV/bin/python \
>     -D BUILD_opencv_python2=OFF \
>     -D BUILD_opencv_python3=ON \
>     -D INSTALL_PYTHON_EXAMPLES=ON \
>     -D INSTALL_C_EXAMPLES=OFF \
>     -D OPENCV_ENABLE_NONFREE=ON \
>     -D BUILD_EXAMPLES=ON ..

Error:

(cv) Alex-2:build Alex$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
>  -D CMAKE_INSTALL_PREFIX=/usr/local \
>     -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
>     -D PYTHON3_LIBRARY=`python -c 'import subprocess ; import sys ; s = subprocess.check_output("python-config --configdir", shell=True).decode("utf-8").strip() ; (M, m) = sys.version_info[:2] ; print("{}/libpython{}.{}.dylib".format(s, M, m))'` \
>     -D PYTHON3_INCLUDE_DIR=`python -c 'import distutils.sysconfig as s; print(s.get_python_inc())'` \
>     -D PYTHON3_EXECUTABLE=$VIRTUAL_ENV/bin/python \
>     -D BUILD_opencv_python2=OFF \
>     -D BUILD_opencv_python3=ON \
>     -D INSTALL_PYTHON_EXAMPLES=ON \
>     -D INSTALL_C_EXAMPLES=OFF \
>     -D OPENCV_ENABLE_NONFREE=ON \
>     -D BUILD_EXAMPLES=ON ..

-- Detected processor: x86_64
CMake Warning at cmake/OpenCVUtils.cmake:660 (message):
  Unexpected option: WITH_V4L (=ON)

  Condition: IF (UNIX;AND;NOT;ANDROID;AND;NOT;APPLE)
Call Stack (most recent call first):
  CMakeLists.txt:360 (OCV_OPTION)

-- Looking for ccache - not found
-- AVX512_KNM is not supported by C++ compiler
-- libjpeg-turbo: VERSION = 2.0.2, BUILD = opencv-3.4.7-pre-libjpeg-turbo
CMake Error at cmake/OpenCVFindLibsGUI.cmake:18 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:798 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/Alex/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/Users/Alex/opencv/build/CMakeFiles/CMakeError.log".

**Comment by DanielAzu** [comment]
Any luck with a solution?

**Comment by aswinpajayan** [comment]
I was able to build it with the following flags 
 -D WITH_QT=OFF -D WITH_GTK=ON 


Output for GUI

--   GUI: 
--     GTK+:                        YES (ver 3.22.30)
--       GThread :                  YES (ver 2.56.4)

I am okay with just GTK for building GUI. guess this works out

**Comment by Thandohimself** [comment]
If you still having this issue like I did try this

"QT5PATH=/usr/local/Cellar/qt/5.11.2_1" needs to be changed to "QT5PATH=/usr/local/Cellar/qt/your version here"

in my case it's  --> version is  5.14.1

**Comment by leimao** [comment]
I don't understand why `WITH_V4L (=ON)` is not an option (anymore)?
