### ISSUE TITLE
Error with #include <Eigen/core> when building opencv 4.1.1

### ISSUE THREAD

**Issue by boitumeloruf** [opencv/opencv#15157]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Linux Debian 9
- Compiler => GCC 6.3.0

##### Detailed description

I encountered an error with \#include <Eigen/core> when building OpenCV 4.1.1 even though Eigen is installed on the system and is found by cmake.

`[  1%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Half/half.cpp.o
 In file included from /home/user/OpenCV/opencv-4.1.1/modules/imgproc/src/precomp.hpp:50:0,
                 from /home/user/OpenCV/build/modules/imgproc/opencv_imgproc_pch_dephelp.cxx:1:
/home/user/OpenCV/opencv-4.1.1/modules/core/include/opencv2/core/private.hpp:66:24: fatal error: Eigen/Core: No such file or directory #  include <Eigen/Core>`

Please find attached my [CMakeCache.txt](https://github.com/opencv/opencv/files/3435311/CMakeCache.txt).

Temporary workaround that solved the issue:
Add `-I<path-to-include/eigen3>` to `CMAKE_CXX_FLAGS`. 

##### Steps to reproduce

1. Download code of OpenCV 4.1.1
2. Build with configuration specified in [CMakeCache.txt](https://github.com/opencv/opencv/files/3435311/CMakeCache.txt).

**Comment by elmuz** [comment]
Same here.

**Comment by antonio-rojas** [comment]
Since bc4b2d521c5eb25496a4e4632cea21cc3110a463 EIGEN_INCLUDE_PATH is not defined if TARGET Eigen3::Eigen is true (which is the case if there is a correct eigen install)

**Comment by LaurentBerger** [comment]
May be relative to #14789 try to update eigen

**Comment by antonio-rojas** [comment]
No, it is not related to that. This is about not finding headers.

**Comment by cenit** [comment]
Same problem experienced in preparing vcpkg port. We had to patch the new code
https://github.com/microsoft/vcpkg/pull/5169

**Comment by applied-machinelearning** [comment]
Reverting commit bc4b2d521c "fixes" the issue for me on Debian Buster.

**Comment by noitauqe** [comment]
What is the simplest way to workaround this problem in a vanilla build like cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local .. 

How does one initialize -I<path-to-include/eigen3> to CMAKE_CXX_FLAGS ?

**Comment by antonio-rojas** [comment]
> What is the simplest way to workaround this problem in a vanilla build like cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
> 
> How does one initialize -I<path-to-include/eigen3> to CMAKE_CXX_FLAGS ?

-DEIGEN_INCLUDE_PATH=/usr/include/eigen3
