### ISSUE TITLE
cv2.imwrite does not report error if user does not have permission to write to a directory

### ISSUE THREAD

**Issue by ksivaman** [opencv/opencv#15155]
##### System information (version)

- OpenCV => 3.*
- Operating System / Platform => Windows x64

##### Detailed description

In python 3.6.8 using the cv2 library, when using cv2.imwrite as:

> cv2.imwrite('path/to/image/myi_image.jpg', my_image)

cv2 does not report an error if the user running the script does not have write permissions to the directory '/path/to/image' as in the above code segment.

imwrite just returns false and the error is extremely hard to debug due to no stderr output.

In addition, the existence of the directory is also not validated.

**Comment by dkurt** [comment]
@ksivaman, Feel free to propose a PR which will describe [imwrite](https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce) return value.

**Comment by heisenbuug** [comment]
@dkurt can I work on this issue?

**Comment by vpisarev** [comment]
@heisenbuug, if you still work on this issue, this is a good moment :)
