### ISSUE TITLE
The tarball for version 4.1.1 expands to wring directory

### ISSUE THREAD

**Issue by bdubbs** [opencv/opencv#15173]
b80c59c7e4feee6a00608315e02b0b73  opencv-4.1.1.tar.gz

$ tar -tf opencv-4.1.1.tar.gz|head
opencv-4.1.0/
opencv-4.1.0/.editorconfig
opencv-4.1.0/3rdparty/
opencv-4.1.0/3rdparty/carotene/
opencv-4.1.0/3rdparty/carotene/CMakeLists.txt
opencv-4.1.0/3rdparty/carotene/README.md
opencv-4.1.0/3rdparty/carotene/hal/
opencv-4.1.0/3rdparty/carotene/hal/CMakeLists.txt
opencv-4.1.0/3rdparty/carotene/hal/tegra_hal.hpp
opencv-4.1.0/3rdparty/carotene/include/

The directory should be opencv-4.1.1/

**Comment by dkurt** [comment]
Cannot understand the problem, sorry.

Release pack is OK (it's generated by GitHub automatically): https://github.com/opencv/opencv/archive/4.1.1.zip

**Comment by bdubbs** [comment]
My mistake.  Sorry.  I used the wrong URL.
