### ISSUE TITLE
Instructions for installing on MacOS are destructive

### ISSUE THREAD

**Issue by chilton** [opencv/opencv#15175]
Instructions here have you creating a symbolic link between the Xcode developer folder and a root level developer folder. I don't know who thinks creating symbolic links to the root level is a good idea, but it breaks toolchains. For example, Android Studio, Google Cardboard, and a host of other products in the past have all placed symbolic links to various things at this location, with the same name. 

***This has never been an acceptable or good idea***

On some earlier versions of MacOS, this is an actual folder with other tools located inside it. 

Is there really no other way to make this work, other than a symbolic link to a 'Developer' folder at the root? 

https://docs.opencv.org/master/d5/da3/tutorial_ios_install.html

**Comment by mshabunin** [comment]
I believe running `xcode-select` should be enough.

**Comment by Patil2099** [comment]
Can I work on this ?

**Comment by farzidev** [comment]
is it safe to install on mac?

**Comment by Piyushhbhutoria** [comment]
is it ok to install on mac? i am worried.

**Comment by SSteve** [comment]
I don't know whether or not creating that link was ever necessary, but currently it isn't. I just submitted #15975 before having seen this issue. In addition to adding more details about building under iOS, it notes that creating the link isn't needed.
