### ISSUE TITLE
Comparision : raw data from skimage.io.imread, scipy.misc.imread differs from opencv cv2.imread

### ISSUE THREAD

**Issue by milinddeore** [opencv/opencv#15179]
##### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => MacOS, x86_64-apple-darwin17.7.0
- Compiler => Apple LLVM version 9.1.0 (clang-902.0.39.2)
- Python Version => Python 3.7.3

##### Detailed description

I have a following python script that tries to read a .jpeg image using opencv `cv2.imread()` but the raw data is not matching with respect to `skimage.io.imread()` or `scipy.misc.imread()`. 

I Found that `skimage.io.imread()` or `scipy.misc.imread()` are matching and same but `cv2.imread()` is different. The same i experience with c++ implementation too (i think both are using same encoder/decoder?). 

##### Steps to reproduce

```
 import cv2
 from skimage import io
 import numpy as np
 from scipy import misc

 # skimage
 ski = io.imread('Milind-Deore.jpeg')
 print(ski)

 #scipy
 sci = misc.imread('Milind-Deore.jpeg')
 print(sci)

 #opencv
 ocv = cv2.imread('Milind-Deore.jpeg')
 ocv = cv2.cvtColor(ocv, cv2.COLOR_BGR2RGB)
 print(ocv)

 print('Scipy Vs Skimage  : ', np.array_equal(sci, ski))
 print('OpenCV Vs Skimage : ', np.array_equal(ocv, ski))
 print('OpenCV Vs Scipy   : ', np.array_equal(ocv, sci))
 print('Opencv Version : ', cv2.__version__)
```

Following is the output: (attaching snippet of the output)

```
 ...

 [[ 6  6  6]
  [ 6  6  6]
  [ 6  6  6]
  ...
  [43 41 44]
  [43 38 44]
  [41 36 42]]

 [[ 5  5  5]
  [ 5  5  5]
  [ 5  5  5]
  ...
  [42 40 43]
  [43 38 44]
  [42 35 43]]

 [[ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [41 39 42]
  [44 37 44]
  [44 37 45]]]
Scipy Vs Skimage  :  True
OpenCV Vs Skimage :  False
OpenCV Vs Scipy   :  False
Opencv Version :  3.4.3
```

I noticed this problem while training SVM classifier with images embeddings (implemented in c++ utilizing `cv2.imread` to read images) and noticed that the accuracy is not as compared to my python program (where i am using `skimage`).

**Comment by catree** [comment]
Jpeg decoding is not bit-exact depending on the libjpeg version, host, ... Use png if you need reproducible results.
See #12340 or on the net some infos:
  - [Does an image loses quality when it is converted from jpg to png?](https://stackoverflow.com/questions/38554199/does-an-image-loses-quality-when-it-is-converted-from-jpg-to-png/38557507#38557507)
  - [Reproducible pixel perfect JPEG decoding](https://stackoverflow.com/questions/32251501/reproducible-pixel-perfect-jpeg-decoding/32257778#32257778)
