### ISSUE TITLE
4.1.0 imgproc module build size doubled

### ISSUE THREAD

**Issue by boulabiar** [opencv/opencv#15177]
- OpenCV => 4.1.1
- Operating System / Platform => Linux Ubuntu 18.04
- Compiler => GCC 7.4

##### Detailed description

The built imgproc module almost doubled in size between OpenCV 4.0.1 and 4.1.0 
22M libopencv_imgproc.so.4.0.1
41M libopencv_imgproc.so.4.1.0
41M libopencv_imgproc.so.4.1.1

Is this intended ?
Is there any explanation for this (fusion with other modules? compiler option?)

**Comment by mshabunin** [comment]
Please provide more information: build configuration, build options, etc.

I have several prebuilt libraries from 4.0.0-4.1.1 all around 40 Mb. Do you have IPP integration disabled in your 4.0.1 build?

**Comment by boulabiar** [comment]
I used the default build options for each version.
In version 4.0.1 the imgproc.so should be 22MB by default.

IPP integration option are the same below

```
$ cat opencv-4.1.0/build/CMakeCache.txt | grep IPP
//Build IPP IW from source
BUILD_IPP_IW:BOOL=ON
//Enables dynamic linking of IPP (only for standalone IPP)
BUILD_WITH_DYNAMIC_IPP:BOOL=OFF
//Include Intel IPP support
WITH_IPP:BOOL=ON
OCV_DOWNLOAD_IPPICV_HASH_3rdparty_ippicv_ippicv_2019_lnx_intel64_general_20180723_tgz:INTERNAL=c0bd78adb4156bbf552c1dfe90599607

$ cat opencv-4.0.1/build/CMakeCache.txt | grep IPP
//Build IPP IW from source
BUILD_IPP_IW:BOOL=ON
//Enables dynamic linking of IPP (only for standalone IPP)
BUILD_WITH_DYNAMIC_IPP:BOOL=OFF
//Include Intel IPP support
WITH_IPP:BOOL=ON
OCV_DOWNLOAD_IPPICV_HASH_3rdparty_ippicv_ippicv_2019_lnx_intel64_general_20180723_tgz:INTERNAL=c0bd78adb4156bbf552c1dfe90599607

```

[CMakeCache_4.0.1.txt](https://github.com/opencv/opencv/files/3450796/CMakeCache_4.0.1.txt)
[CMakeCache_4.1.0.txt](https://github.com/opencv/opencv/files/3450797/CMakeCache_4.1.0.txt)
[CMakeCache_4.1.1.txt](https://github.com/opencv/opencv/files/3450798/CMakeCache_4.1.1.txt)

**Comment by mshabunin** [comment]
Thanks!

Looks like size reduction introduced by #13085 in 4.0.1 has been cancelled during big merge from _3.4_ branch here: #14033 (#14013)

We need to reintroduce #13085 to _master_ and _3.4_ branches.
