### ISSUE TITLE
HfsSegment, performSegmentCpu and performSegmentGpu gives a different results

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#15183]
Windows 10, CMake 3.13, VS 2017. Opencv was built with Qt, MKL, Eigen, CUDA. rev 426482e05b9db0e891539d01177dc5be120af370.

performSegmentCpu and performSegmentGpu from HfsSegment gives a different results.
Test code:
````
shared_ptr<hfs::HfsSegment> h = hfs::HfsSegment::create(m.cols, m.rows);
Mat m1 = h->performSegmentCpu(m),
m2 = h->performSegmentGpu(m);
````
Source img:
![lena](https://user-images.githubusercontent.com/6595124/62044042-9d4d0b80-b20a-11e9-9805-140cabf22d0e.jpg)
m1:
![m1](https://user-images.githubusercontent.com/6595124/62044058-accc5480-b20a-11e9-864f-71a96e161be8.png)
m2:
![m2](https://user-images.githubusercontent.com/6595124/62044062-b0f87200-b20a-11e9-8191-39d42322bf67.png)

**Comment by catree** [comment]
Known issue, see opencv/opencv_contrib#1417

**Comment by Bleach665** [comment]
@catree. Thanks.
