### ISSUE TITLE
chmod is neither an exe nor a bat! for opencv 3.4.7

### ISSUE THREAD

**Issue by lucodercom** [opencv/opencv#15182]
#14747 ### System information (version)
- OpenCV => :3.4.7
- Operating System / Platform => :Windows 10 Enterprise 1803
- Compiler => :

chmod is neither an exe nor a bat!
```
mingw32-make[2]: *** [modules\core\CMakeFiles\pch_Generate_opencv_core.dir\build.make:64: modules/core/precomp.hpp.gch/opencv_core_Release.gch] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:2744: modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
```

##### Detailed description
![20190729170805](https://user-images.githubusercontent.com/26165851/62035982-79e28a80-b223-11e9-826f-53a907de6c86.png)

**Comment by longjiang321** [comment]
hi,  had you resolved this issue??

**Comment by lucodercom** [comment]
> hi, had you resolved this issue??

No, I have rolled the version back to 3.4.0, and I am suer the error may happend on windows only
