### ISSUE TITLE
How to fix OpenCV's different importing errors in Android Studio?

### ISSUE THREAD

**Issue by K2240** [opencv/opencv#15186]
I imported OpenCV 3.3.0 SDK module to Android Studio and I saw 2 errors and 1 warning (Min SDK Version Error, Target SDK Version Warning, Input length = 1 Error).

Note: Sync is successful without importing anything.

And I changed OpenCVLibrary's compileSdkVersion, buildToolsVersion, minSdkVersion and targetSdkVersion to versions that I'm using in my app. But now it's still giving same errors, warning and failing at Run build and Run tasks.

ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

WARNING: The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

ERROR: Input length = 1

I am using Windows x64, my Android Studio version is 3.4.2

Edit: Now I fixed "Input length = 1" error with changing my pc's language to English but others are still here.

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org/
