### ISSUE TITLE
persistence.cpp:719: open(): wrong file signature incorrectly errored as "Input file is empty"

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#15187]
situation: someone downloaded `haarcascade_frontalface_default.xml` from github, but the actual web page, not the file itself. thus it's clearly not a supported format and doesn't match any of the supported signatures.

the first few bytes of what was actually fed to the CascadeClassifier constructor ( https://uploadfiles.io/6o850rkw )
```
00000000   0A 0A 0A 0A 0A 0A 3C 21  44 4F 43 54 59 50 45 20   ......<!DOCTYPE 
00000010   68 74 6D 6C 3E 0A 3C 68  74 6D 6C 20 6C 61 6E 67   html>.<html lang
00000020   3D 22 65 6E 22 3E 0A 20  20 3C 68 65 61 64 3E 0A   ="en">.  <head>.
00000030   20 20 20 20 3C 6D 65 74  61 20 63 68 61 72 73 65       <meta charse
```
the Python code:
```
face_cascade = cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')
```
throws this error, while the file is *not* empty:
```
cv2.error: OpenCV(4.0.0) /home/pi/opencv/modules/core/src/persistence.cpp:722: error: (-49:Unknown error code -49) Input file is empty in function 'open'
```

it *should* say something like "wrong signature" instead.

[The relevant paragraph of code](https://github.com/opencv/opencv/blob/3debb988050b1e3876cc219030c9ed8a5f718be2/modules/core/src/persistence.cpp#L712-L721) (and the whole file) hasn't changed from 4.0.0 to 4.1.1. I just verified that 4.1.0 gives the same message as that user's 4.0.0.

**Comment by thangktran** [comment]
i'm working on this issue.
