### ISSUE TITLE
Undefined references to various __atomic macros when building opencv 4.1.1

### ISSUE THREAD

**Issue by BoxWizard000000** [opencv/opencv#15192]
System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Raspbian Buster armv71
- Compiler => gcc v8.3.0

Output log
```
[ 40%] Linking CXX executable ../../bin/opencv_perf_core
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to `__atomic_fetch_sub_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to `__atomic_compare_exchange_8'
```

Here's my build config:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
   -D CMAKE_INSTALL_PREFIX=/usr/local/ \
   -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-master/modules/ \
   -D ENABLE_NEON=ON \
   -D ENABLE_VFPV3=ON \
   -D ENABLE_LTO=ON \
   -D CPU_BASELINE=NEON \
   -D WITH_TBB=ON \
   -D WITH_OPENCL=ON \
   -D WITH_GSTREAMER=ON \
   -D BUILD_EXAMPLES=OFF \
   -D BUILD_TESTS=OFF \
   -D BUILD_SHARED=OFF ..

make
```

Any ideas how I might resolve this issue?

**Comment by PieGtro** [comment]
It may be a very crude solution, but I solved this adding a  -latomic in the link.txt file of the failing cmake module

**Comment by BoxWizard000000** [comment]
Hm alright, but I wonder why opencv isn't detecting libatomic.

**Comment by BoxWizard000000** [comment]
> It may be a very crude solution, but I solved this adding a -latomic in the link.txt file of the failing cmake module

Where can I find the link.txt file?

**Comment by BoxWizard000000** [comment]
> It may be a very crude solution, but I solved this adding a -latomic in the link.txt file of the failing cmake module

I'm not entirely sure where to add it in the file. Can you show me how yours looks?

**Comment by BoxWizard000000** [comment]
> > It may be a very crude solution, but I solved this adding a -latomic in the link.txt file of the failing cmake module
> 
> I'm not entirely sure where to add it in the file. Can you show me how yours looks? I just put mines by where all the other linkers appear to be.
> 
> ```
> -ldl -lm -lpthread -lrt -latomic
> ```

Never mind, I did it in the wrong file.

**Comment by PieGtro** [comment]
I added -latomic at the end of the link.txt that you can find in the directory listed after the error it is like modules/some_nwme/some_FOLDER/Cmake_file/some_name.dir/........

**Comment by mshabunin** [comment]
As a workaround try to use cmake option: `-DOPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic`

**Comment by PieGtro** [comment]
This bug exists also when compiling code using the OpenCV library, I have to add
set(CMAKE_CXX_FLAGS "-Wl,-latomic") to my program CMakeFile

**Comment by paulbauriegel** [comment]
@mshabunin the cmake option helped to build opencv successfully. But when I'm using python to import opencv, I'm still getting more or less the same exception:
`ImportError: /usr/local/lib/libopencv_core.so.4.1: undefined symbol: __atomic_compare_exchange_8`

**Comment by BoxWizard000000** [comment]
I'm just getting other linker errors now. I got undefined references to `Imf_opencv` and so I stopped trying to build the module and now I'm getting undefined references to `google::protobuf`

**Comment by paulbauriegel** [comment]
@BoxWizard000000 for the protobuf problems https://github.com/opencv/opencv/issues/13328 could help, most likely cmake option `-DENABLE_PRECOMPILED_HEADERS=OFF` should help

**Comment by BoxWizard000000** [comment]
> @BoxWizard000000 for the protobuf problems #13328 could help, most likely cmake option `-DENABLE_PRECOMPILED_HEADERS=OFF` should help

Nope that didn't do it for me.

**Comment by BoxWizard000000** [comment]
> @BoxWizard000000 for the protobuf problems #13328 could help, most likely cmake option `-DENABLE_PRECOMPILED_HEADERS=OFF` should help

Realized I forgot to `make clean` before I tried again and it seemed to work. Thanks!

**Comment by baqwas** [comment]
Didn't work for me on RPi2 under Buster. A whole slew of __atomic__ errors starting with the follwoing:

```
[ 69%] Linking CXX executable ../../bin/opencv_perf_core
/usr/bin/ld: ../../lib/libopencv_core.a(alloc.cpp.o): in function `cv::utils::(anonymous namespace)::AllocatorStatistics::getPeakUsage() const':
alloc.cpp:(.text._ZNK2cv5utils12_GLOBAL__N_119AllocatorStatistics12getPeakUsageEv+0x8): undefined reference to `__atomic_load_8'

```
The command used was:
```
cmake -D CMAKE_BUILD_TYPE=Release \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_C_EXAMPLES=ON \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
-D PYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3 \
-D WITH_PROTOBUF=OFF \
-D ENABLE_PRECOMPILED_HEADERS=OFF \
-D BUILD_EXAMPLES=ON ..

```
Since I have very limited understanding, any guidance here would be appreciated.

Kind regards.
