### ISSUE TITLE
有时候使用opencv-python录制视频，播放起来会很快

### ISSUE THREAD

**Issue by tangbinbinyes** [opencv/opencv#15193]
为什么有时候使用opencv-python录制视频，播放起来会很快，有时候又是正常的速度？原本以为是摄像头的解析力不够，在暗光下就会这样，但是我现在换了一个好的摄像头，依然会发生这种情况，导致我后面的工作不能够正常进行。

**Comment by dkurt** [comment]
Please translate it in English
