### ISSUE TITLE
Failing to display YOLO object detection result via OpenCV-dnn module 

### ISSUE THREAD

**Issue by barzan-hayati** [opencv/opencv#15212]
##### System information (version)

- OpenCV => :4.1.0
- Operating System / Platform => :Linux Ubuntu 18.04

and
- OpenCV => :4.1.0
- Operating System / Platform => :Windows 7

##### Detailed description

I have trained YOLO object detection via darknet and I could check result using 
`./darknet detector test cfg/obj.data cfg/yolo-obj.cfg yolo.weights data/test.jpg`
but when I want to use dnn module in OpenCV for showing result on input image(`160*30`), it failed. But it could show result correctly for larger images such `1280*760`.
![Input Image](https://user-images.githubusercontent.com/7418329/62410286-006ae380-b5f9-11e9-9fad-b8b6adda11c9.jpg)

I think that, `blobfromimage` function crop upper region of this image and subsequently show incorrect results for input image. 

At last I show a sample of image that showed correctly by this module:
![2](https://user-images.githubusercontent.com/7418329/62410612-3f9b3380-b5fd-11e9-8f05-0352dabf99f4.jpg)

**Comment by dkurt** [comment]
If you want to report a bug please provide all the details to reproduce it. In case of usage question please use a forum http://answers.opencv.org/

**Comment by jsxyhelu** [comment]
you may have to change a model to find the car

**Comment by barzan-hayati** [comment]
@jsxyhelu When I have a small objects, I could not find objects in it. I can find cars but I can not find characters in the small images.

**Comment by barzan-hayati** [comment]
I solved it. When we want to showing result using opencv and dnn module, we must consider ratio of resizing of original image. For example when I have a `160*30` input image, at first I convert it to `416*78`(resizing one of the width or height to 416). Now for showing results, I resize height by multiplying it to `416/78`
