### ISSUE TITLE
Color space conversion RAW->RGB

### ISSUE THREAD

**Issue by sk34nk** [opencv/opencv#15231]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2019 16.2.0

##### Detailed description

I have an original image in green tones:
![raw](https://user-images.githubusercontent.com/42886604/62464462-570d2480-b795-11e9-8773-86ff3e6953fd.png)
In legacy code with OpenCV 3.1.0 it was converted to normal colors with:
`cv::cvtColor(Mat(size.height, size.width, CV_16UC1, rawRight.data), frameRight, color);	// convert CV_8UC2 to CV_16UC1`
And it's work ok. 
But when I update OpenCV 4.1.1. And it began to work with problems. Instead of the image with normal colors received:
![vBlahj5N1Vk](https://user-images.githubusercontent.com/42886604/62464713-ff22ed80-b795-11e9-8a0a-7c8aebe3dec6.jpg)
I tried sorting through all the methods from enum: 
https://docs.opencv.org/4.1.1/d8/d01/group__imgproc__color__conversions.html#ga4e0972be5de079fed4e3a10e24ef5ef0
but not one made the colors right.
OpenCV gives the following image information:
```
[i] channels:  3
[i] pixel depth: 0 bits
[i] elemSize:       3 bytes
[i] elemSize1:       1 bytes
[i] type: CV_8UC3
```

I would be grateful for any help.

**Comment by alalek** [comment]
Select small ROI (`cv::Rect(0,0,4,4)`) of input image and dump its values on `stdout` (`std::cout`) on each stage.
At least to exclude issues with image rendering.

> cv::cvtColor(..., color);
> // convert CV_8UC2 to CV_16UC1

You should not use `cvtColor` for that. See `convertTo()` with `alpha`/`beta` parameters.

**Comment by sk34nk** [comment]
I'm right understood?
```
if (src.read(raw))
{
     Rect roi(0, 0, 4, 4);
     Mat temp = raw(roi);
     cout << "raw(roi):  " << endl;
     cout << temp << endl;
     cout << endl;		
     raw.convertTo(frame, CV_16UC3);
     imshow("raw", raw);
     temp = frame(roi);
     cout << "frame(roi):  " << endl;
     cout << temp << endl;
     cout << endl;
     imshow("convert", frame);
}
```

in console:

> raw(roi):
> [ 13, 255,  53,  13, 255,  53,  13, 255,  53,  13, 255,  53;
>   13, 255,  53,  13, 255,  53,  13, 255,  53,  13, 255,  53;
>   13, 255,  53,  13, 255,  53,  13, 255,  53,  13, 255,  53;
>   13, 255,  53,  13, 255,  53,  13, 255,  53,  13, 255,  53]
> frame(roi):
> [13, 255, 53, 13, 255, 53, 13, 255, 53, 13, 255, 53;
>  13, 255, 53, 13, 255, 53, 13, 255, 53, 13, 255, 53;
>  13, 255, 53, 13, 255, 53, 13, 255, 53, 13, 255, 53;
>  13, 255, 53, 13, 255, 53, 13, 255, 53, 13, 255, 53]


In window:
![converTo](https://user-images.githubusercontent.com/42886604/62478629-37d1bf80-b7b4-11e9-96b1-9a85b712da86.png)

What have I done wrong?

**Comment by mshabunin** [comment]
Please add more details. Which `cvtColor` mode did you use in 3.1.0? Can you check several versions from 3.x branch? Please attach minimal application reproducing the issue and problematic input image.

Do you want to convert 8UC2 to 16UC1? What does channels represent in the original image and what should they represent in resulting image?

I believe `imshow` of 16U image will scale all values (0-65535) to 0-255 so most of pixels in your image will be zero on display.

**Comment by sk34nk** [comment]
1. I can’t check in 3 versions, because there is a question about speeding up calculations, for which I built 4.1.1 with cuda modules.
```
int main(int argc, char** argv)
{
	Size boardSize, sizeFrame(1280, 720);
	VideoCapture src;
	Mat raw, frame;
	src.open("liveLeftCalib.avi", CAP_OPENCV_MJPEG);
	if (!src.isOpened())
	{
		cout << "Error opening left video stream or file" << endl;
		return -1;
	}
	if (src.read(raw))
	{
		Rect roi(0, 0, 4, 4);
		Mat temp = raw(roi);
		cout << "raw(roi):  " << endl;
		cout << temp << endl;
		cout << endl;
		imshow("raw", raw);
		raw.convertTo(frame, CV_16U, 100);
		temp = frame(roi);
		cout << "frame(roi):  " << endl;
		cout << temp << endl;
		imshow("convert", frame);
		cout << endl;
	}
	while (1)
	{
		waitKey(10000);
	}	
}
```
 Frame from video : 
![raw](https://user-images.githubusercontent.com/42886604/62494345-f5bc7400-b7db-11e9-89f8-b62a20df6320.png)

2. So it was, why it was converted, I did not understand (apparently just a crutch). Now images are 3 channels. There is a lot of green. How can this be fixed? In the sense of how to reduce / add colors on individual channels?

3. Yes, thanks. I understood it.
