### ISSUE TITLE
Opencv cmake build detect wrong CUDA version

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#15245]
##### System information (version)

OpenCV 4.1.1
Ubuntu 18.04.2
Cuda 10.0
Platform: NVIDIA GeForce RTX 2070

This is what I have in /usr/local
cuda -> cuda-10.0/
cuda-10.0/

##### Detailed description

Not sure which cmake file detect Cuda 10.1 instead of 10.0, the compiling is successful, but other program that depends on OpenCV fails as openCV requires CUDA 10.1 (the wrong version) but the other app detect the good version

As a workaround I force the CUDA version on the cmake command
```
cmake -D CUDA_VERSION=10.0 ..
```
An example of an output of an application depending on OpenCV is

```
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA: Found unsuitable version "10.0", but required is exact
  version "10.1" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindCUDA.cmake:1092 (find_package_handle_standard_args)
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  lib/zense/capture/CMakeLists.txt:7 (find_package)
```

**Comment by fengyuentau** [comment]
Some here. cmake detected version 9.1 in my case, but this version of CUDA is actually not installed. Found a solution from https://stackoverflow.com/a/19981506/6769366:
```shell
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda # or the CUDA installation dir in your case
```

**Comment by ThomasVolkert** [comment]
Same here, CMake detects 10.1 while the system has 11.1 and 11.2 installed.
