### ISSUE TITLE
can't use openvino gaze-estimation-adas-0002 (python)

### ISSUE THREAD

**Issue by RobbeDePrins** [opencv/opencv#15248]
I'm trying to use pre-trained model gaze-estimation-adas-0002 from openvino. This link should tell me which inputs to use: https://docs.openvinotoolkit.org/2019_R1/_gaze_estimation_adas_0002_description_gaze_estimation_adas_0002.html

I detect left and right eye using haar cascades. An make blobs using:
```right_eye_image = cv.dnn.blobFromImage(right_eye, size = (60, 60), crop=False)```
```left_eye_image = cv.dnn.blobFromImage(left_eye, size = (60, 60), crop=False)```
head_pose_angles is just a list with the three headpose directions

by reading errors I know that only the first argument of model_gaze.setInput() contains a blob and that it should be of type cv::UMat. When i use ```model_gaze.setInput(cv.UMat(np.array([left_eye_image, right_eye_image, head_pose_angles])))``` I get the error ```TypeError: Required argument 'ranges' (pos 2) not found```. How do I correctly use the model?

**Comment by dkurt** [comment]
@RobbeDePrins, have you tried to set inputs in the following way?
```python
right_eye_image = cv.dnn.blobFromImage(right_eye, size = (60, 60))
left_eye_image = cv.dnn.blobFromImage(left_eye, size = (60, 60))

model_gaze.setInput(right_eye_image , 'right_eye_image')
model_gaze.setInput(left_eye_image , 'left_eye_image ')
```
?

According the documentation, there is also third input named as `head_pose_angles `.

**Comment by RobbeDePrins** [comment]
works perfectly! Thank you so much!

**Comment by dkurt** [comment]
@RobbeDePrins, you're welcome!

**Comment by syaheedz** [comment]
Can I have the example of the inferencing code in Python using gaze-estimation-adas-0002?

**Comment by soyjorge** [comment]
Hi!! Thanks @RobbeDePrins  for the heads up...

Though I'm getting the following error:
`
cv2.error: OpenCV(4.1.2-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/dnn.cpp:2982: error: (-204:Requested object was not found) Requested blob "left_eye_image " not found in function 'setInput'
`
I've entered input name as you suggested, which matches instructions from:
http://docs.openvinotoolkit.org/2019_R1/_gaze_estimation_adas_0002_description_gaze_estimation_adas_0002.html

Any help would be appreciated!
