### ISSUE TITLE
Rect_ intersection improve to support only border overlap detect

### ISSUE THREAD

**Issue by iamgd67** [opencv/opencv#15254]
##### Detailed description

template Rect_ union operator will return Rect(0,0,0,0) when two Rects have only border or point overlap, I think better to keep the overlap info, meaning may return a Rect who's width or/and height may be zero when there is only border or point overlap. 

##### Steps to reproduce

Rect(0, 0, 1, 1) & Rect(1, 0, 1, 1) will got Rect(0, 0, 0, 0) instead of Rect(1, 0, 0, 1)

**Comment by alalek** [comment]
Right-bottom border of cv::Rect is "open" (like cv::Range: `[start, end)`).
Point `(1, 1)` doesn't belong to `Rect(0, 0, 1, 1)`

**Comment by iamgd67** [comment]
consider the "open" idear, what about the top-right corner, it's both on top border(include) and right border(exclude).
just thinking make it return the result of border overlap is more useful and more Intuitive.

**Comment by iamgd67** [comment]
Just to clarify, Rect(1, 0, 0, 1) contains no point just as Rect(0, 0, 0, 0)
