### ISSUE TITLE
build opencv 3.4 with VS 2019 (msvc 1921)

### ISSUE THREAD

**Issue by zihao0821** [opencv/opencv#15253]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I use cmake to build opencv 3.4, and there is a warning about OpenCV_RUNTIME.
```
CMake Warning at cmake/OpenCVDetectCXXCompiler.cmake:147 (message):
  OpenCV does not recognize MSVC_VERSION "1921".  Cannot set OpenCV_RUNTIME
Call Stack (most recent call first):
  CMakeLists.txt:157 (include)
```
I check the file OpenCVDetectCXXCompiler.cmake, and in line 132-148.
```
  if(MSVC_VERSION EQUAL 1400)
    set(OpenCV_RUNTIME vc8)
  elseif(MSVC_VERSION EQUAL 1500)
    set(OpenCV_RUNTIME vc9)
  elseif(MSVC_VERSION EQUAL 1600)
    set(OpenCV_RUNTIME vc10)
  elseif(MSVC_VERSION EQUAL 1700)
    set(OpenCV_RUNTIME vc11)
  elseif(MSVC_VERSION EQUAL 1800)
    set(OpenCV_RUNTIME vc12)
  elseif(MSVC_VERSION EQUAL 1900)
    set(OpenCV_RUNTIME vc14)
  elseif(MSVC_VERSION MATCHES "^191[0-9]$")
    set(OpenCV_RUNTIME vc15)
  else()
    message(WARNING "OpenCV does not recognize MSVC_VERSION \"${MSVC_VERSION}\". Cannot set OpenCV_RUNTIME")
  endif()
```
Can I just add MSVC_VERSION 1921 like this, or something else?
```
  elseif(MSVC_VERSION MATCHES "^192[0-9]$")
    set(OpenCV_RUNTIME vc16)
```

**Comment by alalek** [comment]
You are using an outdated version.
There is no way to amend code of released versions. You need to upgrade.

**Comment by JiYou** [comment]
I've solved this problem with below steps.

# Step 1. Build OpenCV

Open file `./cmake/OpenCVDetectCXXCompiler.cmake`

```C
121   elseif(MSVC_VERSION MATCHES "^191[0-9]$")
122     set(OpenCV_RUNTIME vc15)
123   elseif(MSVC_VERSION MATCHES "^192[0-9]$") <-- add this line
124     set(OpenCV_RUNTIME vc16) <-- add this line
125   else()
```

Then compile OpenCV as usually steps and install OpenCV.

# Step 2.  Change install configurations.

after build -> install of OpenCV. Change install_dir/OpenCVConfig.cmake

```C
 83   elseif(MSVC_VERSION MATCHES "^191[0-9]$")
 84     set(OpenCV_RUNTIME vc15)
 85   elseif(MSVC_VERSION MATCHES "^192[0-9]$") // <-- add this line
 86     set(OpenCV_RUNTIME vc16) // <-- add this line
 87   endif()
```

# PS:

if you build opencv in world mode. you would get `opencv_world341.lib`. if you can not find this file, you may ignore below step.:

open install_dir/x86/vc16/staticlib/OpenCVConfig.cmake

change line 115 to

```C
 set(OpenCV_LIB_COMPONENTS opencv_world)
```

Good luck for you.
