### ISSUE TITLE
dead link in https://opencv.org/opencv4android-usage-models/

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#15264]
At bottom page “Tutorial” for you: “Building OpenCV4Android from trunk”. link is dead
 I think new link should be https://github.com/opencv/opencv/wiki/Building_OpenCV4Android_from_trunk instead of https://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk

**Comment by alalek** [comment]
There is no up-to-date Android build instructions. Wiki page is outdated too.

**Comment by jsxyhelu** [comment]
what do you mean of "CI builds "?

**Comment by LaurentBerger** [comment]
[CI Builds](https://pullrequest.opencv.org/buildbot/builders/precommit_android/builds/20299)

**Comment by VadimLevin** [comment]
Things that can be done to resolve the ticket:
- [ ] Analyse steps that CI bot is doing to build an Andriod version
- [ ] Formalize them into the wiki page.
 >  - Create a new repository in your account, e.g. `opencv-android-wiki`  
 >  - Clone official opencv wiki to local machine `git clone https://github.com/opencv/opencv.wiki.git` 
 >  - Change `origin` of the original repository to your newly created one. 
 >     ```bash
 >     $ git remote rm origin
 >     $ git remove add origin git@git.github.com:<YOUR-USER-NAME>/opencv-android-wiki
 >     # Verify new remote
 >     $ git remote -v
 >     ```
 >  - Make proposed changes locally, push them to your github account repository.
- [ ] Add a comment to this ticket requesting to review your changes and merge them in. (Include a link to your repo)

**Comment by asmorkalov** [comment]
Proper link: https://github.com/opencv/opencv/wiki/Custom-OpenCV-Android-SDK-and-AAR-package-build

**Comment by asmorkalov** [comment]
@philnelson could you handle this?

**Comment by philnelson** [comment]
Fixed on page
