### ISSUE TITLE
Read RAW or ARW file

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#15269]
I have just tried libraw library to read an raw file (sony format). it works. libraw is Library for reading and processing of RAW digicam images.

license is 
LibRaw is distributed for free under two different licenses:

    GNU Lesser General Public License, version 2.1
    COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0

Is it possible to make a PR to add possibility to read raw file using imread with this lib?

**Comment by alalek** [comment]
GPhoto2 may read [these formats](https://github.com/gphoto/libgphoto2/blob/libgphoto2-2_5_23-release/gphoto2/gphoto2-file.h#L61).
Currently there is videoio's backend using GPhoto2, but there is no backend for imread/imdecode.

> GNU Lesser General Public License, version 2.1

No problem from LGPL if you are using system/external binaries.

**Comment by LaurentBerger** [comment]
gphoto is only for [linux](https://github.com/gphoto/libgphoto2#platforms)

**Comment by LaurentBerger** [comment]
Is [libraw ](https://www.libraw.org/)compatible with opencv license?

**Comment by mshabunin** [comment]
Yes, it should be compatible, at least under LGPL license. There are several LGPL libraries integrated by the OpenCV, e.g. GTK.
