### ISSUE TITLE
./gradlew: No such file or directory

### ISSUE THREAD

**Issue by AlbertSnow** [opencv/opencv#15272]
Crash happen when call:
make install
···
/bin/sh: ./gradlew: No such file or directory
make[2]: *** [/opencv/build/outputs/aar/opencv-release.aar] Error 127
make[1]: *** [modules/java/android_sdk/CMakeFiles/opencv_java_android.dir/all] Error 2
make: *** [all] Error 2
···

- OpenCV => 4.1
- Operating System / Platform => mac 64 Bit

**Comment by AlbertSnow** [comment]
I guess it maybe Cmake params problem, so I change the Cmake params: 
```
-DBUILD_ANDROID_EXAMPLES=ON       -DBUILD_ANDROID_PROJECTS=ON  
```
To turn on the android example params. 
And everything is ok;

**Comment by alsaleem00** [comment]
I spent alot of time figuring out where this gradlew could be at!

@AlbertSnow is there away to compile all platforms at once : armeabi-v7a, arm64-v8a, x86, x86_64?
The aar file will contain only one variant with ANDROID_ABI. can we do "armeabi-v7a, arm64-v8a" or like?
Thanks.

**Comment by AlbertSnow** [comment]
> 

I already not develop opencv any more.

But I search some article about that:

You can see that from official [website](https://developer.android.com/ndk/guides/abis#gradle) 
With CMake, you build for a single ABI at a time and must specify your ABI explicitly. 

So it's can't ???

**Comment by alsaleem00** [comment]
This is what i am doing right now. Compile for an abi, save, then delete /build, and repeat same for another abi.
Then, combine these outputs into one aar file.

Thanks. I appreciate your help.

**Comment by alalek** [comment]
BTW, There are useful build scripts for Android platform: https://github.com/opencv/opencv/tree/4.x/platforms/android

**Comment by alsaleem00** [comment]
@alalek  Thanks. It works!
I can get all in one aar file.
