### ISSUE TITLE
There is no big improvement when use libjpeg-turbo instead of libjpeg

### ISSUE THREAD

**Issue by HaoLiuHust** [opencv/opencv#15271]
According to the description, libjpeg-turbo seems faster 2.X than libjpeg，but on Intel-cpu, seems there is no difference to build opencv with libjpeg-turbo or libjpeg, the imdecode cost time seems nearly equal, is there any advice?

**Comment by catree** [comment]
Maybe [this](https://github.com/opencv/opencv/issues/12115) if you are using the OpenCV libjpeg-turbo?

**Comment by HaoLiuHust** [comment]
@catree You mean the libjpeg-turbo in opencv has disabled SIMD?
