### ISSUE TITLE
openCv Screen Recording

### ISSUE THREAD

**Issue by paramesharobit** [opencv/opencv#15273]
Hi, I am new be in opencv as well as python. I want to record the desktop screen and it is working fine for me. But during recording multiple screens are comming with full screen. I want to hide these screen and also I am unable to implement a button so that I can stop recording. Bellow is my code :
fourcc = cv2.VideoWriter_fourcc(*'XVID')
	vid=cv2.VideoWriter("c:\\IQOutput\\rec.avi", fourcc, 10, (990,690))

	while(True):
		img = ImageGrab.grab(bbox=(10,10,1000,700))
		img_np=np.array(img)
		frame=cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
		vid.write(frame)
		
		cv2.imshow("frame", frame)
		key=cv2.waitKey(0)
		if key==27:
			break
	vid.release()
	cv2.destroyAllWindows()
	tkMessageBox.showwarning('', 'Screen Recording Stopped', icon="warning")

Please guide me.

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org
