### ISSUE TITLE
StereoRectifiy : Q is not exactly exact

### ISSUE THREAD

**Issue by SJaminion** [opencv/opencv#15284]
Hi,
I'm working on 3D points reconstruction using disparity map. I read on your book OpenCV   (version 2008), page 435, that the Q is defined like this
            1      0     0     -Cx
            0      1     0     -Cy
Q =      0      0     0        f
            0      0  -1/Tx  (Cx-Cx')/Tx
 
I decided to  the calculis, I found that the last two terms don't have the right sign. Q should be equal at
            1     0      0     -Cx
            0      1     0     -Cy
Q =      0      0     0        f
            0      0  1/Tx  -(Cx-Cx')/Tx           

Did you know it ?

Kind regards

Stéphanie

nb : I didn't find on the documentation website the Q maxtrix definition

**Comment by alalek** [comment]
Corresponding code: https://github.com/opencv/opencv/blame/4.1.1/modules/calib3d/src/calibration.cpp#L2693-L2700

Please add more details or prepare minimal complete reproducer.

**Comment by SJaminion** [comment]
![image](https://user-images.githubusercontent.com/9929506/62875913-29d7ed80-bd24-11e9-8433-a2ab10602455.png)
We have this relation : 
X = Z *xl / f 
Z = f *( Z*xl/f –T)/xr
Z* xr = Z*xl –f*T
Z (xl – xr) = f*T  
Or
Pixel jl = cl(0) + xl ;
Pixel jr = cr(0) + xr;
Then
xl = jl - cl(0)
xr = jr -cr(0)
Z is equal at 
Z = f*T / ( jl – jr –(cl(0) –cr(0) ) ;
Or Disp = jl - jr;
Z = fT / (Disp -(cl(0) –cr(0) );
Z = f / (Disp/T - (cl(0) –cr(0))/T);
And
Z * Disp - Z*(cl(0) –cr(0)) = fT
Z * Disp/T - Z*(cl(0) –cr(0))/T = f
Disp = ( (f + (Z*(cl(0) –cr(0))/T) / (Z/T)

Then X = ( jc - cl(0) ) / (Disp/T + (cl(0) –cr(0))/T)
and Y = ( il - cl(1) ) / (Disp/T + (cl(0) –cr(0))/T)

For matrix 
![image](https://user-images.githubusercontent.com/9929506/62877115-abc91600-bd26-11e9-8640-b80240e8d5e1.png)

I have for Q(3,2 ) = 1/T and you have Q(3,2) = -1/T
and for Q(3,3) = -(cl(0) -cr(0)) /T  and you have  Q(3,3) = (cl(0) -cr(0)) /T

If you want, I can scan my papers : it will be more easily to understand.

**Comment by SJaminion** [comment]
At the begining of the equation 
Z/f = X/ xl
Z/f  = (X -T) / xr

**Comment by SJaminion** [comment]
About matrix, ti's not (jl, yl, Disp, 1) but (jl, il, Disp, 1)

**Comment by dmgotsch** [comment]
Could this be a difference between the left/right handedness of the coordinate system used in OpenCV vs. your calculations?

**Comment by catree** [comment]
From [`stereoCalibrate()` doc](https://docs.opencv.org/4.1.1/d9/d0c/group__calib3d.html#ga91018d80e2a93ade37539f01e6f07de5):

```
R2 = R x R1
T2 = R x T1 + T
```

So `(R,T)` allows transforming a 3D point expressed in the left camera into the right camera.

`T_x` is < 0 in OpenCV whereas yours is > 0.

**Comment by SJaminion** [comment]
And for me,  R and T that I used was  from the right camera to the left camera.

**Comment by catree** [comment]
Yes, so both formulas are correct.

**Comment by SJaminion** [comment]
Ok. thanx
