### ISSUE TITLE
package opencv4 not found in the pkg-config path 

### ISSUE THREAD

**Issue by horkooo** [opencv/opencv#15288]
I compiled opencv(4.1.1) with module opencv_contrib , when I finished by command "make install" .
the system note that "**No package 'opencv4' found**"

**following is the whole infomation:**
`-- Installing: /usr/local/share/opencv4/samples/python/video_threaded.py
-- Installing: /usr/local/share/opencv4/samples/python/video_v4l2.py
-- Installing: /usr/local/share/opencv4/samples/python/watershed.py
[root@localhost build]# pkg-config --libs opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv4' found
[root@localhost build]#`

can you help me to solve it ?  opencv is installed in "/usr/local/lib64" and my system is cent_os(7.6) ,

**Comment by adinriv** [comment]
This problem is related to https://github.com/opencv/opencv/issues/13154 (if not the same).
