### ISSUE TITLE
seamlessClone bug 

### ISSUE THREAD

**Issue by Kepnu4** [opencv/opencv#15294]
Opencv 3.4.6-dev
Python 3.6.8

There is a problem in seamlessClone that was produced by this pr https://github.com/opencv/opencv/pull/12512.

1.  When mask is on borders only (like border line) it's just crashes. It happens because
https://github.com/opencv/opencv/blob/72ccb5fe6e355e2e6e7c6960b5a456c1d08ec28e/modules/photo/src/seamless_cloning.cpp#L77 
this line places zeros on mask borders.
2. It produces undesirable ghost effect on borders

Here is code to reproduce:
```LINES = 60
dst = np.ones((101, 101, 3), np.uint8) * 255
src = np.ones((101, 101, 3), np.uint8) * 255
cv.circle(dst,  center=(50, 50), radius=5, color=(0, 0, 255), thickness=-1)
cv.circle(dst, center=(50, 0), radius=5, color=(0, 0, 255), thickness=-1)

mask = np.zeros((101, 101, 1), np.uint8)
mask[:LINES,:] = 255

res = cv.seamlessClone(src, dst, mask, (50, 50), cv.NORMAL_CLONE)
cv.imwrite('result.png', np.concatenate([dst, src, np.concatenate([mask, mask, mask], axis=2), res], axis=1))
```

That's even stranger behavior 
If i set LINES to 1 or 2 i get
`terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)
`
If i set LINES to 3 i get 
`Traceback (most recent call last):
  File "seamless_test.py", line 13, in <module>
    res = cv.seamlessClone(src, dst, mask, (50, 50), cv.NORMAL_CLONE)
cv2.error: OpenCV(3.4.6-dev) /home/vfilev/packages/opencv/modules/core/src/matrix_wrap.cpp:1658: error: (-215:Assertion failed) !fixedSize() in function 'release'
`

and if i set LINES to 60 i get the result below
Example:  
![result](https://user-images.githubusercontent.com/2921717/63006070-71768a80-be86-11e9-952f-aeaaff4a6278.png)

So you can see that circle inside image is gone but circle on a border is left here.

**Comment by sturkmen72** [comment]
@Kepnu4 could you provide the code ( reproducer ) . let me check it.

**Comment by Kepnu4** [comment]
@sturkmen72 yes, sure, i updated report.

**Comment by sturkmen72** [comment]
@Kepnu4 if mask has white pixels only on borders in my opinion it is misusing mask concept and not worth to fix.

**Comment by Kepnu4** [comment]
@sturkmen72 yeah, maybe. But still don't you find that crash with valid arguments is not expected behaviour? And it's worth check inside for such mask

**Comment by alalek** [comment]
@Kepnu4 Could you try the fix from the linked PR above: #15316 ?

**Comment by TheOnlyBeliever** [comment]
How to solve this problem? i used the lastest version 4.4.0.44, or use other versions, I always meet error like this：
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped).
following is my code.
![image](https://user-images.githubusercontent.com/46390195/97291530-05165a00-1885-11eb-8fc9-6a7e773f9c9b.png)

**Comment by alalek** [comment]
@ForeverBeliever Please fill a separate issue with complete minimal reproducer (including input data - you can capture them before the failed call).
