### ISSUE TITLE
DISOpticalFlow , android,  PRESET_ULTRAFAST/PRESET_FAST  not work

### ISSUE THREAD

**Issue by doodoo0006** [opencv/opencv#15291]
OpenCV => 4.1.1
Operating System / Platform => android 9.1.0
Compiler => android studio , ndk r20

rt. when I set PRESET_MEDIUM as follows,  the android project work well, 
    cv::Ptr<cv::DenseOpticalFlow> algorithm = 
       cv::DISOpticalFlow::create(cv::DISOpticalFlow::PRESET_MEDIUM  );
    if (!img1.empty())
    {
        algorithm->calc(img1, img2, flow);
    }

    but when I set to PRESET_FAST or PRESET_ULTRAFAST,  the program crash and forced terminal.
    
    also the PRESET_FAST/PRESET_ULTRAFAST work well at winx64 environment.

**Comment by alalek** [comment]
Add stack trace dump from lldb and used input data (image dimensions at least)
