### ISSUE TITLE
G-API: Valgrind issues "OwnMatConversion.WithND" (2019-08-10)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#15293]
[Weekly build](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10185)

Error types:
- "Invalid read of size 16"
- "Conditional jump or move depends on uninitialised value(s)"

Test code: `opencv_test::OwnMatConversion_WithND_Test::TestBody`

relates #15090
/cc @dmatveev

**Comment by dmatveev** [comment]
Thanks, will have a look on this

**Comment by alalek** [comment]
There is related sporadic crash in [Win32 build](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/21280):
```
[ RUN      ] OwnMatConversion.WithND
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] OwnMatConversion.WithND (3 ms)
```
