### ISSUE TITLE
C++ ORB Feature Matching with FLANN Lsh Error

### ISSUE THREAD

**Issue by DavorJordacevic** [opencv/opencv#15304]
I am trying to match Orb features using FLANN matcher and LSH, and it gives me this error:

OpenCV: terminate handler is called! The last OpenCV error is:

OpenCV(4.1.0) Error: Unsupported format or combination of formats (> type=5 > ) in buildIndex_, file
C:\opencv\source\opencv-4.1.0\modules\flann\src\miniflann.cpp, line 315

What is the reason for this?

Descriptors are already converted to CV_32F.
```
cv::FlannBasedMatcher matcher = cv::FlannBasedMatcher(cv::makePtr(12, 20, 2));
std::vector< std::vector > matches;
matcher.knnMatch(descriptors1, descriptors2, matches, 2 );
```

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Provide minimal complete reproducer for your problem.

> converted to CV_32F

This doesn't make sense if descriptors are not FP32.
You should not replace Hamming distance to L2/L1.

**Comment by DavorJordacevic** [comment]
`

    // Feature detection
    orb->detect(image_left, keypoints1);
    orb->detect(image_right,keypoints2);

    cv::Mat imageKeyPoints;

    // Extraction of the orb descriptors
    cv::Mat descriptors1, descriptors2;
    orb->compute(image_left, keypoints1, descriptors1);
    orb->compute(image_right, keypoints2, descriptors2);


    if(descriptors1.type()!=CV_32F) {
        descriptors1.convertTo(descriptors1, CV_32F);
    }

    if(descriptors2.type()!=CV_32F) {
        descriptors2.convertTo(descriptors2, CV_32F);
    }

    cv::FlannBasedMatcher matcher = cv::FlannBasedMatcher(cv::makePtr<cv::flann::LshIndexParams>(12, 20, 2));
    //cv::Ptr<cv::DescriptorMatcher> matcher = cv::DescriptorMatcher::create(cv::DescriptorMatcher::FLANNBASED);
    std::vector< std::vector<cv::DMatch> > matches;
    matcher.knnMatch(descriptors1, descriptors2, matches, 2 );`

**Comment by DavorJordacevic** [comment]
The problem was solved. 
The problem was that descriptors should not be converted to CV_32F and that I need to check 
`if (matches[i].size() >= 2). `
Thanks!
