### ISSUE TITLE
cross compile arm-linux show errors invalid conversion 

### ISSUE THREAD

**Issue by streamtostream** [opencv/opencv#15308]
opencv-4.1.1/modules/imgcodecs/src/grfmt_jpeg.cpp:224:58: error: invalid conversion from ‘uchar* {aka unsigned char*}’ to ‘const JOCTET* {aka const char*}’ [-fpermissive]
     state->source.pub.next_input_byte = m_buf.ptr();
/opencv-4.1.1/modules/imgcodecs/src/grfmt_jpeg.cpp:456:56: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘const uchar* {aka const unsigned char*}’ [-fpermissive]
                         icvCvt_RGB2BGR_8u_C3R( buffer[0], 0, data, 0, Size(m_width,1) );
opencv-4.1.1/modules/imgcodecs/src/grfmt_jpeg.cpp:458:59: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘const uchar* {aka const unsigned char*}’ [-fpermissive]
                         icvCvt_CMYK2BGR_8u_C4C3R( buffer[0], 0, data, 0, Size(m_width,1) );
opencv-4.1.1/modules/imgcodecs/src/grfmt_jpeg.cpp:465:60: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘const uchar* {aka const unsigned char*}’ [-fpermissive]
                         icvCvt_CMYK2Gray_8u_C4C1R( buffer[0], 0, data, 0, Size(m_width,1) );
and more ...

**Comment by dkurt** [comment]
@streamtostream, Please follow issue template and add all the details about build configuration: OS, compiler, etc.

**Comment by streamtostream** [comment]
ubuntu 18.04；
 cross compiler：aarch64-linux-gnu-g++， aarch64-linux-gnu-gcc；
use cmake-gui to config opencv4.1.1

**Comment by mshabunin** [comment]
Do you use cmake toolchain file for cross-compilation (`CMAKE_TOOLCHAIN_FILE`)?

**Comment by forestguan** [comment]
How to solve it?

**Comment by xiaolitongxue666** [comment]
I had the same problem, how to solve it ?

**Comment by alalek** [comment]
> -fpermissive

Remove this (perhaps from your toolchain file / build scripts).

> grfmt_jpeg.cpp

`cmake ... -DWITH_JPEG=OFF`

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
