### ISSUE TITLE
Webcam initialization on macOS Mojave

### ISSUE THREAD

**Issue by kristyanYochev** [opencv/opencv#15307]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => macOS Mojave (10.14.3)
- Compiler => XCode 10.3

##### Detailed description

The camera crashes while trying to initialize when the user is prompted with the "Do you allow <app> to access your camera?" instead of waiting for approval. After granting approval and rerunning the program again everything works just as intended but it is not good for development where the binary changes often and every time you want to test a change you have to run your code twice.

##### Note

In order to force the authorization prompt to appear I added the Info.plist file to be copied to the binary like the suggestion in [this StackOverflow post](https://stackoverflow.com/questions/52541086/nscamerausagedescription-needed-for-c-projects-in-xcode-for-macos-mojave)

##### Steps to reproduce

 ```.cpp
#include "opencv2/opencv.hpp"

int main() {
    const int cameraDev = 0;
    cv::VideoCapture capture(cameraDev);

    while (!capture.isOpened()) {
        return -1;
    }
    
    cv::Mat frame;
    
    while(true) {
        capture >> frame;
        
        if (frame.empty()) {
            std::cout << "Empty frame, breaking!" << std::endl;
            break;
        }
        
       cv::imshow("What I see", frame);
        
        if (cv::waitKey(30) == 27) break; // KEY_ESCAPE
    }
    return 0;
}
```

1. Hit run.
2. Accept the prompt when the popup appears.
3. Stop the execution.
4. Run again.

**Comment by alalek** [comment]
see this issue: #14258

> Info.plist

Responsibility of Application. OpenCV as a library should not (can't properly) handle that.
