### ISSUE TITLE
cv::dnn::readNetFromONNX from memory buffer not working

### ISSUE THREAD

**Issue by Dragon116rus** [opencv/opencv#15310]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc

##### Detailed description

When I load the onnx model (converted from pytorch ) using cv::dnn::readNetFromONNX from memory buffer, it will get the "error: (-210:Unsupported format or combination of formats) Failed to parse onnx model from in-memory byte array. in function 'ONNXImporter'". 

##### Steps to reproduce

    ```
    ifstream modelStream("../model.onnx", ios::binary);

    modelStream.seekg(0, ios_base::end);
    int bufferSize = modelStream.tellg(); //getting file size
    char* modelData = new char[bufferSize];

    modelStream.seekg(0, ios::beg);
    modelStream.read(modelData, bufferSize);

    cv::dnn::Net model = cv::dnn::readNetFromONNX(modelData, bufferSize);

    delete [] modelData;
    ```
But if I use cv::dnn::readNetFromONNX from file, it work fine:
```cv::dnn::Net model = cv::dnn::readNetFromONNX("../model.onnx");```

**Comment by dkurt** [comment]
@Dragon116rus, Can we reproduce this issue with any model you your can provide problematic one?

**Comment by Dragon116rus** [comment]
@dkurt, I think yes, for any onnx model you can reproduce this problem. I tried on my model converted from pytorch and on shufflenet and mnsit from [onnx repo](https://github.com/onnx/models/tree/master/vision/classification)

**Comment by Dragon116rus** [comment]
@dkurt, sorry, the problem was because I messed up `get` and `read`, while I read the data. Now it work fine. Thank you
