### ISSUE TITLE
undefined reference to 'main' in opencv_ts_RELEASE

### ISSUE THREAD

**Issue by ctcarroll** [opencv/opencv#15328]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Raspian Buster on a Raspberry Pi 4 / 4GB

##### Detailed description
When attempting to build opencv 4.1.1, the build process consistently quits with an error at the same point:

```
[ 18%] Generating precomp.hpp.gch/opencv_ts_RELEASE.gch
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crt1.o: in function `_start':
(.text+0x34): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/build.make:66: modules/ts/precomp.hpp.gch/opencv_ts_RELEASE.gch] Error 1
make[1]: *** [CMakeFiles/Makefile2:10634: modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
##### Steps to reproduce
For the most part, I'm following the steps in this tutorial:   https://www.pyimagesearch.com/2018/09/26/install-opencv-4-on-your-raspberry-pi/
Quick summary:
From a fresh build of the July 20 release of Raspian Buster with desktop, I expand filesystem, install dependencies, download opencv and opencv_contrib v4.1.1, set up a virtual env called 'cv', install numpy, increase swap, then run cmake and make / make -j4 (both error out)
(I'm following all steps in the tutorial but didn't want to list them again here.)

For my cmake values I'm using:
```
$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D BUILD_TESTS=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D CMAKE_CXX_FLAGS=-latomic \
    -D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
    -D BUILD_EXAMPLES=OFF ..
```
The two lines with -latomic are because of the bug reported in https://github.com/opencv/opencv/issues/15278 and can probably be removed later.

I'm admittedly new to cmake so apologies if I'm doing something wrong in that step.

At least one other person is getting this same error though:   https://answers.opencv.org/question/216034/trying-to-install-opencv-with-cmake-on-raspberry-pi-3/

#15278

**Comment by fnoop** [comment]
Just speculating, but opencv_ts is the test module - might be because you're turning -DBUILD_TESTS=OFF?

Would recommend setting `-DENABLE_PRECOMPILED_HEADERS=NO`, will save you a lot of space and wear and tear on SD card.

**Comment by ctcarroll** [comment]
Hey @fnoop, that did the trick!   After a week of trying I finally got a successful build.   Thanks a million!    The precompiled headers was all I needed.    I didn't end up changing DBUILD_TESTS=OFF.
For anyone else running into these same errors, my full cmake command is below.  Note that I also ended up building with just 'make' instead 'make -j4' to remove that possible failure point.   Took about 90 mins on the pi 4.  

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D BUILD_TESTS=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D CMAKE_CXX_FLAGS=-latomic \
    -D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
    -D BUILD_opencv_ts:BOOL=OFF \
    -D ENABLE_PRECOMPILED_HEADERS=NO \
    -D BUILD_EXAMPLES=OFF ..

**Comment by fnoop** [comment]
Great!  I suspect it was because of this though: `-D BUILD_opencv_ts:BOOL=OFF`.  pi4 is so much faster, used to take hours and hours and hours on a pi3!
