### ISSUE TITLE
The convert function and multiply function takes too long in arm board.

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [opencv/opencv#15320]
##### Detailed description
1.On the arm board, Float64 conversion to  uint8 takes 5ms.It took too long.
final.convertTo(con_final, CV_8UC1);
How should I optimize?
2.On the arm board, multiply function  took too long.
multiply(meanI, meanP,mul_mat); The data type of meanI is float64.

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org/
