### ISSUE TITLE
Opencv 4 Android crash whell call orb->detectAndCompute

### ISSUE THREAD

**Issue by frigiddragon** [opencv/opencv#15332]
##### System information (version)
- OpenCV => 4.0.1
- Operating System / Platform => Android 5.2
- Compiler => Android Studio

##### Steps to reproduce
My code is as bellow
-----------
    Mat rotateMat, refGray, testGray;
    //1. convert ref and test image to gray
    cvtColor(refMat, refGray, cv::COLOR_BGR2GRAY);
    
    //2. detect feature and compute descriptors
    vector<KeyPoint> refKp, testKp;
    Mat refdesc;
    Ptr<ORB> or2b = ORB::create();
    orb->detectAndCompute(refGray, Mat(), refKp, refdesc);
-------------
 
Application runs without error on Android 9.0.
But it crashed after calling to detectAndCompute on Android 5.2.

Error message is:
    --------- beginning of crash
08-19 12:51:19.281 32531-32686/test.opencv.app A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0xa1e511a9 in tid 32686 (AsyncTask #2)

**Comment by alalek** [comment]
> 4.0.1

This is old release. Please try 4.1.1 or latest code from the "master" branch.

In case of crashes with fresh version, please provide a stack trace.

**Comment by frigiddragon** [comment]
Thanks a lot Alalek.
After upgraded to latest official release 4.1.1 the issue is resolved.
