### ISSUE TITLE
Opencv memory occupation all the time 

### ISSUE THREAD

**Issue by zuoshaobo** [opencv/opencv#15333]
Becase I use an embed device, memory very little , I found some strange problems:
I juse use code below:
Mat ss=(1000,1000,CV_8UC1) //use memory 1000*1000 bytes
resize(ss,ss,(500,500));//use about 80M memory
ss.release()
How to free the resize memory , during out test ,it will occupy about 80M all the time if i resize serveral times
Not only the resize function ,i found pyrdown api still like that

It seems that opencv‘s some api will occupy fixed memory all the time .

so how to release these memory?

**Comment by alalek** [comment]
> resize(ss,ss, ...)

Using "inplace" mode with src==dst doesn't make sense in case of resize operation.
Avoid that. To avoid unnecessary coping of input in the worst case.

> //use about 80M memory

What is measured? Process RSS?

**Comment by zuoshaobo** [comment]
use linux command  "free"
Process RSS still increase
the occupy size "80M" dose not decided by input image size

**Comment by alalek** [comment]
Measuring of process RSS is not accurate to track memory usage - memory can be hold from OS by heap allocator (for future allocations in this process) and this can't be fixed in OpenCV.

Try to debug and investigate of problem's origin.

**Comment by zuoshaobo** [comment]
I just want to konw why opencv alloc such big memory, does it really free it after resize function ?
