### ISSUE TITLE
Issues building OpenCV Framework Dynamic

### ISSUE THREAD

**Issue by JakeWade3** [opencv/opencv#15346]
- OpenCV => 3.43 && 4.0.1
- Operating System / Platform => MacOS

Having build issues with using OpenCV as a Dynamic Framework.
I have managed to build OpenCV as a dynamic framework quite easily using the following command:

`python platforms/ios/build_framework.py ios --dynamic`

After a little while this builds me an end framework at the following directory:

> /iOS/opencv2.framework

When I add this framework to my iOS Framework all is good and build fine, but when I add my custom framework to my app I get the following issues

```
dyld: Library not loaded: /Desktop/Workspace/OpenCV/ios/build/build-iphoneos/lib/Release/opencv2.framework/opencv2

  Referenced from: /private/var/containers/Bundle/Application/UUID/MyApp.app/Frameworks/MyApp.framework/MyApp
  Reason: image not found

```
We require OpenCV to be Dynamic to avoid collisions when clients are implementing our framework. I have tried both versions 3.4 and 4.0 and both are having the exact same issue. It seems like a bug with the build process of the Dynamic Library.

I've also tried using Legoless's OpenCV-Dynamic Coccoa pod but this also has similar issues.
https://github.com/Legoless/OpenCV-Dynamic
https://github.com/Legoless/OpenCV-Dynamic/issues/11

Any help on this issue would be appreciated

**Comment by mixo44** [comment]
+. The same problem.

**Comment by xnxy** [comment]
出现了同样的问题。

**Comment by MegatronKing** [comment]
+. The same.

**Comment by xnxy** [comment]
install_name_tool -id @rpath/opencv2.framework/opencv2 opencv2

**Comment by xnxy** [comment]
https://xnxy.github.io/xnxy.github.io/2020/05/11/如何编译iOS版OpenCV动态库/
