### ISSUE TITLE
dead link in stitching tutorial

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#15344]
Something weird in[ stitching tutorial](https://docs.opencv.org/master/d8/d19/tutorial_stitcher.html) :  link to code is dead. 

This tutorial code's is shown lines below. You can also download it from [here](https://github.com/opencv/opencv/tree/master/samples/cpp/samples/cpp/stitching.cpp).

**Comment by LaurentBerger** [comment]
@prakhar9998 Are you looking for easy commit to write your CV? :relaxed:

**Comment by prakhar9998** [comment]
> @prakhar9998 Are you looking for easy commit to write your CV? relaxed

I am a beginner in open source so trying out on easy issues. I am passionate to learn and I don't think that a mention in CV is a good motivation for that, so I am trying my best to contribute in any way I can :)

**Comment by LaurentBerger** [comment]
@prakhar9998  May be a good way to contribute it is : ask to author issue  if you can manage  this issue before.

Now if you ask me can I mange this issue?

My answer is yes

**Comment by prakhar9998** [comment]
@LaurentBerger Sorry, my bad. Will keep this in mind for future.
