### ISSUE TITLE
warpPerspective result not continuous at border

### ISSUE THREAD

**Issue by jansende** [opencv/opencv#15347]
##### System information (version)
- OpenCV => 3.4.5
- Operating System / Platform =>linux
- Compiler => clang

##### Detailed description
I tried to transform parts of an image using `warpPerpective`, however the resulting image is not continuous at the border. The following code presents an example of that. I would expect the upper half of the image to be transformed, and continuously connect with the lower half at the middle.

Being that floating point math is involved, I expected the border to be off by one or two pixels. However, it is shifted by around 8! Thus, this seems to be a bug in the `warpPerspective`function.

##### Steps to reproduce

```c++
#include <opencv2/imgproc.hpp>
#include <opencv2/opencv.hpp>
#include <array>

using namespace cv;

int main()
{
  //create sample image
  const auto width = size_t{2000};
  const auto height = size_t{3000};

  auto image = Mat{height, width, CV_8UC3, Scalar{255, 255, 255}};
  line(image, Point2i{500, 0}, Point2i{500, height}, Scalar{0, 0, 0});
  line(image, Point2i{1000, 0}, Point2i{1000, height}, Scalar{0, 0, 0});
  line(image, Point2i{1500, 0}, Point2i{1500, height}, Scalar{0, 0, 0});

  //transform upper hald
  auto upper_half = image(Rect2i{Point2i{0, 0}, Point2i{width - 1, (height - 1) / 2}});
  const auto trafo = getPerspectiveTransform(
                       std::array<cv::Point2f, 4>
  {
    Point2f{0, 0},
    Point2f{width - 1, 0},
    Point2f{width - 1, (height - 1) / 2},
    Point2f{0, (height - 1) / 2}
  },
  std::array<cv::Point2f, 4>
  {
    Point2f{30, 70},
    Point2f{width - 50, 100},
    Point2f{width - 1, (height - 1) / 2},
    Point2f{0, (height - 1) / 2}
  });
  warpPerspective(upper_half, upper_half, trafo, upper_half.size());
  
  //write
  imwrite("out.jpg", image);
}
```
![out](https://user-images.githubusercontent.com/44576417/63336783-045c6c80-c340-11e9-9961-58296a26e00f.jpg)

**Comment by mshabunin** [comment]
Are you sure there is a problem? Should perspective transform defined this way save distances between points on lower border?

I tried your example with little modificatons (600x600) image, vertical lines at 10, 300 and 590 pixels:
![perpective1](https://user-images.githubusercontent.com/3304494/63348858-d2103680-c362-11e9-8e2b-a02cb44d8d4a.png)

And here is perspective transform without vertical skew (?):
![perspective2](https://user-images.githubusercontent.com/3304494/63348933-0126a800-c363-11e9-8612-1e13ee4d598e.png)

```.cpp
  const auto trafo = getPerspectiveTransform(
    std::array<cv::Point2f, 4>
    {
      Point2f{0, 0},
      Point2f{width, 0},
      Point2f{width - 1, (height - 1) / 2},
      Point2f{0, (height - 1) / 2}
    },
    std::array<cv::Point2f, 4>
    {
      Point2f{30, 70},
      Point2f{width - 80, 70},
      Point2f{width - 1, (height - 1) / 2},
      Point2f{0, (height - 1) / 2}
    });
```

**Comment by jansende** [comment]
I am not sure, but this is at least what I would expect. If the new and original points of a transformation are the same, nothing should be transformed, or should it?

How did you achieve the second image?

**Comment by mshabunin** [comment]
@jansende , by using code snippet I pasted below the image.

**Comment by catree** [comment]
@jansende 

There is two things:
 1. is the estimated transformation (homography) correct?
 2. is the warping function correct?

For:
 1. The estimated transformation can be compared with another library
 2. You can perform the matrix-vector multiplication yourself once 1) is validated

With Python skimage:

<details><summary>code</summary>
<p>

```python
import numpy as np
from skimage.transform import ProjectiveTransform

width = 2000
height = 3000
src = np.array([[0, 0],
                [width-1, 0],
                [width-1, (height - 1) / 2],
                [0, (height - 1) / 2]])

print('src.shape:', src.shape)
print('src:\n', src)

dst = np.array([[30, 70],
                [width - 50, 100],
                [width - 1, (height - 1) / 2],
                [0, (height - 1) / 2]])

print('dst.shape:', dst.shape)
print('dst:\n', dst)

tform = ProjectiveTransform()
tform.estimate(src, dst)
print('tform:\n', tform.params)

pt = np.array([500, (height - 1) / 2, 1])
print('pt:', pt)
pt_trans = tform.params @ pt
pt_trans = pt_trans / pt_trans[-1]
print('pt_trans:', pt_trans)
```

</p>
</details>

This gives:

```
src.shape: (4, 2)
src:
 [[   0.     0. ]
 [1999.     0. ]
 [1999.  1499.5]
 [   0.  1499.5]]
dst.shape: (4, 2)
dst:
 [[  30.    70. ]
 [1950.   100. ]
 [1999.  1499.5]
 [   0.  1499.5]]
tform:
 [[ 9.90608122e-01 -2.01945691e-02  3.02817563e+01]
 [ 1.62308713e-02  9.21849907e-01  7.06574315e+01]
 [ 1.08241889e-05 -2.69565254e-05  1.00939188e+00]]
pt: [5.0000e+02 1.4995e+03 1.0000e+00]
pt_trans: [5.0832602e+02 1.4995000e+03 1.0000000e+00]
```

**Comment by mshabunin** [comment]
Transform from the sample app is almost the same (_master_ branch):
```
[0.9813984905247479, -0.0200133422281521, 30;
 0.01608023454185993, 0.9132568035006131, 70;
 1.072730789983992e-05, -2.671474180589209e-05, 1]
```

And

> `pt: [5.0000e+02 1.4995e+03 1.0000e+00]`
> `pt_trans: [5.0832602e+02 1.4995000e+03 1.0000000e+00]`

means point shifted 8 pixels to the right after transform, so it seems there are no bugs.

**Comment by jansende** [comment]
@mshabunin So you chose points in a way, that the bug is no longer visible? That's is not very helpful...

@catree I don't really understand what you trying to say. Please elaborate! However, assuming that you wanted my to test the transformation on points, I did. It's still wrong.

```c++
//extension of the code above
auto before = std::array<cv::Point2f, 5>{
    cv::Point2f{0, (height - 1) / 2},
    cv::Point2f{500, (height - 1) / 2},
    cv::Point2f{1000, (height - 1) / 2},
    cv::Point2f{1500, (height - 1) / 2},
    cv::Point2f{width - 1, (height - 1) / 2},
};
auto after = std::array<cv::Point2f, 5>{};
cv::perspectiveTransform(before, after, trafo);
for (auto i = size_t{0}; i < 5; ++i)
  std::cout << '[' << before[i].x << ',' << before[i].y << "] --> ["
            << after[i].x << ',' << after[i].y << "]\n";
```

Result:
```bash
[0,1499] --> [0,1499]
[500,1499] --> [508.329,1499]
[1000,1499] --> [1011.04,1499]
[1500,1499] --> [1508.23,1499]
[1999,1499] --> [1999,1499]
```

The endpoints match, but in between there an the offset!

**Comment by catree** [comment]
@jansende 

In 1), I wanted to validate that [`getPerspectiveTransform()`](https://docs.opencv.org/4.1.1/da/d54/group__imgproc__transform.html#ga20f62aa3235d869c9956436c870893ae) is correct and it matches OpenCV (minus the normalization in `h33`, see Homography topic).

In 2), I just did what `perspectiveTransform()` or `warpPerspective()` do internally, that is a matrix-vector multiplication to map source coordinates using the estimated transformation.

You get the same results so unless the offset in the image is greater/different than 8 pixels, there is no issue here with `getPerspectiveTransform()` or `warpPerpective()`.

---

If you are not familiar with some topics in computer vision, the [Szeliski's book](http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf) is a good start.

Some properties of the perspective projection are:

- Lines in 3D project to lines in 2D
- Distances and angles are not preserved
- Parallel lines do not in general project to parallel lines (unless they are parallel to the image plane)

I can only suggest you to play with Blender or any physical render engine to convince yourself since I don't trust my intuitions with geometries.
