### ISSUE TITLE
@dkurt Unable to load deeplab model, getting same error as below

### ISSUE THREAD

**Issue by Roopesh-Nallakshyam** [opencv/opencv#15361]
@dkurt 
Firstly I try use the official model, export pbtxt 
```
    import tensorflow as tf
    with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
      for i in reversed(range(len(graph_def.node))):
        if graph_def.node[i].op == 'Const':
            del graph_def.node[i]

       for attr in ['T', 'data_format', 'Tshape', 'N', 'Tidx', 'Tdim',
                 'use_cudnn_on_gpu', 'Index', 'Tperm', 'is_training',
                 'Tpaddings']:
           if attr in graph_def.node[i].attr:
               del graph_def.node[i].attr[attr]
    tf.train.write_graph(graph_def, "", "frozen_inference_graph.pbtxt", as_text=True)
```
there was error:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_importer.cpp:1153: error: (-213:The function/feature is not implemented) Unsupported squeeze configuration in function 'populateNet'

then I transformed the pb model use tensorflow 's code
tensorflow/tensorflow/tools/graph_transforms/transform_graph.cc
with command line and export the transform pbtxt
`bazel run tensorflow/tools/graph_transforms:transform_graph -- --in_graph="frozen_inference_graph_opt.pb" --out_graph="frozen_inference_graph_transf.pb" --inputs="ImageTensor" --outputs="SemanticPredictions" --transforms="fold_constants sort_by_execution_order remove_nodes(op=Squeeze)"`
there was error:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-rc) /home/crwon/opencv-4.0.0-rc/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:773: error: (-2:Unspecified error) Tensor's data type is not supported in function 'getTensorContent'
and when I use your optimization code in official model or transform model  and export the optimization pbtxt:
```
graph = 'frozen_inference_graph_trasf.pb'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.summary.FileWriter('logs', graph_def)
    inp_node = 'ImageTensor'
    out_node = 'SemanticPredictions'
    graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def, [inp_node], [out_node], tf.float32.as_datatype_enum)
    graph_def = TransformGraph(graph_def, [inp_node], [out_node])
 
with tf.gfile.FastGFile('frozen_inference_graph_trasf_opt.pb', 'wb') as f:
    f.write(graph_def.SerializeToString())
```
it was the same error:
Tensor's data type is not supported in function 'getTensorContent'
can you help me?

_Originally posted by @gwang92 in https://github.com/opencv/opencv/issues/13247#issuecomment-441164516_

**Comment by dkurt** [comment]
Have you read my response there? Please follow issue template and provide all the files to reproduce the issue "official deeplab" means almost nothing without links.
