### ISSUE TITLE
Always download face_landmark_model.dat

### ISSUE THREAD

**Issue by nizqsut** [opencv/opencv#15374]
##### System information (version)

- OpenCV => 4.11
- Operating System / Platform => Raspberry Pi 4
- Compiler => g++(Raspbian 8.3.0-6+rpi1)

##### Detailed description
Always download face_landmark_model.dat, even though it was not the first time run cmake.
It wastes so many time.

note like that:   
```
-- data: Download: face_landmark_model.dat
```

##### Steps to reproduce
My cmake options like this:
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=/usr/local \
            -D INSTALL_C_EXAMPLES=ON \
            -D INSTALL_PYTHON_EXAMPLES=ON \
	    -D ENABLE_NEON=ON \
	    -D ENABLE_VFPV3=ON \
	    -D OPENCV_ENABLE_NONFREE=ON \
	    -D BUILD_TESTS=OFF \
            -D WITH_V4L=ON \
        -D WITH_QT=ON \
        -D WITH_OPENGL=ON \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
	-D PYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3 \
        -D BUILD_EXAMPLES=ON ..
```

**Comment by alalek** [comment]
Can't reproduce - second run doesn't emit "download" messages.

Provide cmake logs (terminal stdout) + CMakeCache.txt + CMakeDownloadLog.txt for both first run (from clean build dir) and second run.

**Comment by kinchungwong** [comment]
Checklist. Did you:

1. configure OPENCV_DOWNLOAD_PATH, 
1. its permissions (to make sure CMake is able to write to this folder), 
1. to make sure its contents are not being wiped out between CMake runs?
