### ISSUE TITLE
Error:Performing Test HAVE_CXX*** FAILED

### ISSUE THREAD

**Issue by horkooo** [opencv/opencv#15375]
I compiled opencv(3.4.7) with opencv_contrib(3.4.7) on my Raspberry Pi (latestest system os) ,everything is ok . but when I executed the cmake command ,Some error messages appeared on the screen .

The following is the error message：

`-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed`

Is there a problem with the C compiler & how to fix them ? 

this is a screen shortcut 

![mDUbm6.png](https://s2.ax1x.com/2019/08/23/mDUbm6.png)

[![mDaxET.png](https://s2.ax1x.com/2019/08/23/mDaxET.png)](https://imgchr.com/i/mDaxET)

**Comment by alalek** [comment]
It is just checks result.
Handled by CMake configuration scripts automatically.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
