### ISSUE TITLE
cv2.VideoCapture() not working

### ISSUE THREAD

**Issue by d-suri** [opencv/opencv#15384]
- OpenCV => 4.1.0
- Operating System / Platform => Linux (Ubuntu 16.04)
- Language => Python 2.7.12

##### Detailed description

I've been working with a camera to adjust brightness and contrast using keyboard controls. When I used `cv2.VideoCapture(-1)`, the program worked perfectly. Since the goal is to use multiple cameras, I began using `cv2.VideoCapture(0)`. Without any other changes (only one camera plugged in to the USB bus, and found at `/dev/video0`), the program began to fail.

Looking closer at what caused the issue, I ended up with the following shortened code. If I tried to change two settings and take two pictures, the program would fail.  If I changed one setting, I could take as many pictures as I wanted without an error. Similarly, if I only took one picture, I could change the settings as many times as I wanted. However, whenever I tried to change a setting, it was always set to 0 until I next initialized my camera.

I would like to reiterate that `cv2.VideoCapture(-1)` was always successful. I also found that using `cv2.VideoCapture("/dev/video0")` worked. The issue was not the capabilities of my camera. However, `cv2.VideoCapture(0)` always failed. I tried adding a second camera, and found that `cv2.VideoCapture("/dev/video1")` worked and `cv2.VideoCapture(1)` failed.

##### Notes

cv2.CAP_PROP_BRIGHTNESS = 10
cv2.CAP_PROP_CONTRAST = 11
I tried placing a delay (`cv2.waitKey(500)`) between lines to no avail. I also tried this with only one USB camera plugged into the USB bus.

##### Code

    import cv2
    
    cam = cv2.VideoCapture(0)
    r1 = cam.set(10,55)
    ret0,img0 = cam.read()
    r2 = cam.set(11,60)
    ret1,img1 = cam.read()
    r3 = cam.set(10,70)
    print("Settings changed successfully?", r1,r2,r3)
    print(cam.get(10), cam.get(11))
    print("Pictures taken sucessfully?", ret0,ret1)
    print("Cam open", cam.isOpened())
    cam.open(0)
    print("Reached end of program")

##### Output

    libv4l2: error setting pixformat: Device or resource busy
    ('Settings changed successfully?', True, True, False)
    (0.0, 0.0)
    ('Pictures taken sucessfully?', True, False)
    ('Cam open', False)
    libv4l2: error setting pixformat: Device or resource busy

When I included `cam.open(0)`, the program would not continue to the next line of code.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Also read how to debug and/or disable different VideoCapture backends: https://docs.opencv.org/3.4/de/db1/group__videoio__registry.html

This tracker is for issues and bugs that needs fix in OpenCV.
Return back if you have clear understanding that should be fixed in OpenCV.

**Comment by d-suri** [comment]
I went to the OpenCV Q/A forum earlier. I was asked to add this here by StevenPuttemans since he thought that perhaps the internal translation of the indexes is somehow broken.

**Comment by alalek** [comment]
You can try to debug related [code of indexes translation](https://github.com/opencv/opencv/blob/576644a19705f3ee762d168a4ab780102fb824b7/modules/videoio/src/cap_v4l.cpp#L796-L799) into `/dev/video`.

**Comment by mshabunin** [comment]
@d-suri , `VideoCapture` can use different backends under the hood, please provide more information:
set environment variables `OPENCV_VIDEOIO_DEBUG=1` and `OPENCV_LOG_LEVEL=debug` and rerun your program.

Try to explicitly select V4L backend: `cv2.VideoCapture(0, cv2.CAP_V4L)`
