### ISSUE TITLE
4.1.0 native library fails to load on Android KitKat

### ISSUE THREAD

**Issue by FROGbots-4634** [opencv/opencv#15389]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Android KitKat ARM 32-bit
- Compiler => Android Studio 3.4.2

##### Detailed description

When trying to load the OpenCV 4.x native library (found in `OpenCV-4.1.0-android-sdk/sdk/native/libs/armeabi-v7a/libopencv_java4.so`) on Android KitKat, the following error this thrown:

    dlopen failed: could not load library "libmediandk.so" needed by "libopencv_java4.so"; caused by library "libmediandk.so" not found

**Comment by alalek** [comment]
Android level 21+ (Android 5.0+) is requires for OpenCV builds (from releases page).
For KitKat (Android 4.4) you need to rebuild Android package from sources.

Take a look on [release build](http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/10883) for reference build logs.
Configuration files for Android builds are here: https://github.com/opencv/opencv/tree/master/platforms/android
