### ISSUE TITLE
findContours returns different results on same image

### ISSUE THREAD

**Issue by invernie** [opencv/opencv#15404]
I have run into the [following issue ](https://stackoverflow.com/questions/57660409/findcontours-approach-in-open-cv-returns-different-results-on-the-same-image-dep) when working with open-cv python library 4.1, on python 3.7 . It seems to be a bug with the function findContours.

**Comment by alalek** [comment]
> findContours

results are useless without edge detector processing, like `Canny()`.

[Tutorial](https://docs.opencv.org/3.4/df/d0d/tutorial_find_contours.html).

**Comment by catree** [comment]
> findContours returns different results on same image

Your images are not the same. The ants are not at the same position. This is not the reason of the contour artefacts but you have said `same image`...
The contour artefacts come from some kind of image compression artefacts.
You can see it if you dump the raw data (these regions are not zero):

![img_diff](https://user-images.githubusercontent.com/8229425/63898743-7d238e80-c9fa-11e9-822c-11700eb7620a.png)

**Comment by invernie** [comment]
Thanks for the reply - this is the solution to the problem. It must be an issue with a hidden setting differing between commands in ffmpeg and unrelated to open-cv. The small indents in the mask are then closed and detected as separate objects by findContours. How did you dump the row data (working in python open-cv, plotting the matrix just returns the image)?

**Comment by catree** [comment]
This is the code:

```
import numpy as np
import cv2 as cv

img1 = cv.imread('7Br82N.png')
img2 = cv.imread('mpijwX.png')

np.savetxt('7Br82N_0.txt', img1[:,:,0], '%d')
np.savetxt('mpijwX_0.txt', img2[:,:,0], '%d')

img_diff_raw = img1[:,:,0].astype(np.float32) - img2[:,:,0].astype(np.float32)
img_diff = np.zeros(img_diff_raw.shape, np.uint8)

img_diff[np.where(img_diff_raw != 0)] = 255
cv.imwrite('img_diff.png', img_diff)
```
