### ISSUE TITLE
Converting from RGB to BGR or vice versa with cv2.cvtColor(img, cv2.COLOR_RGB2BGR and BGR2RGB) not working

### ISSUE THREAD

**Issue by JennyLouise** [opencv/opencv#15408]
##### System information (version)

- OpenCV => 4.1.0.25
- Operating System / Platform => MacOS - High Sierra
- Compiler => Python

##### Detailed description

The command cv2.cvtColor(img, cv2.COLOR_RGB2BGR) returns the image without swapping colour channels. It also does this when using cv2.cvtColor(img, cv2.COLOR_BGR2RGB).

In my case, I'm debayering a greyscale image and then saving as a 3 channel colour image. When saving both the 'rgb' and 'bgr' images, they turn out identical, and clearly are saving an rgb image as though it's bgr with red things appearing blue and vice versa.

##### Steps to reproduce

``` 
import cv2
from colour_demosaicing import demosaicing_CFA_Bayer_bilinear

img = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
img_rgb = np.array(demosaicing_CFA_Bayer_bilinear(img, pattern))
img_bgr = cv2.cvtColor(img_rgb.astype(datatype), cv2.COLOR_RGB2BGR)

cv2.imwrite("bgr.png", img_bgr)
cv2.imwrite("rgb.png", img_rgb)

```

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
OpenCV's I/O functions are usually expect color images in BGR format.

If you want to report a bug, then you should provide reproducer:
- complete (including input data)
- minimal (no extra external dependencies and even `imread`/`imwrite` calls are not needed to report `cvtColor()` problem)
- with expected result
- and actual output (we need to ensure that we reproduce problem correctly on local machines)

<details>

<summary>Code</summary>

```
import numpy as np
import cv2 as cv

a = np.array(
    [
        [[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]],
        [[11,12,13], [14,15,16], [17,18,19]],
    ],
    dtype=np.uint8)

print(a)

b = cv.cvtColor(a, cv.COLOR_RGB2BGR)

print(b)
```

</details>

<details>

<summary>Output</summary>

```
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
[[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]

 [[13 12 11]
  [16 15 14]
  [19 18 17]]]
```

</details>
