### ISSUE TITLE
unexplainable reversal of y coordinate in numpy image array

### ISSUE THREAD

**Issue by nyck33** [opencv/opencv#15406]
##### System information (version)

- OpenCV => 4.1.0 (opencv-contrib-python)
- Operating System / Platform => Ubuntu 18
- Compiler => VSCode

##### Detailed description
The rows are getting switched when I assign them to variables.
`cv2.rectangle()` requires top left then bottom right so I know which ones these are in my bbox[] list and can draw the rectangle.  However when I try to use the same coordinates for slicing, my `y`'s (which I assigned `y1 = bbox[3]`, `y2=bbox[1]` are reversed with y1 being a larger integer than `y2`  so I have to slice using `y2:y1` instead.  I am pretty sure that I printed out `bbox[]` 0 to 3 as well and it was the same so not sure why those coordinates work for both `cv2.rectange()` and `plt.Rectangle()` but then not for slicing in this case.  
I posted on datasciencestackexchange about it:  https://datascience.stackexchange.com/questions/58308/unexplainable-reversal-of-x-y-coordinates-in-numpy-image-array?noredirect=1#comment63897_58308

##### Steps to reproduce

python code, please look at cv2.rectangle() at the bottom of the function so you know what top left and bottom  of bbox are:

<!-- to add code example fence it with triple backticks and optional file extension

**Comment by nyck33** [comment]
Cannot post code in above comment for some reason.
```
for i in inds:
        bbox = dets[i, :4]
        score = dets[i, -1]

        #crop y1 to y2+1, x1 to x2+1 with top left of image as 0,0
        x1 = int(bbox[0]) 
        x2 = int(bbox[2])
        y1 = int(bbox[3]) 
        y2 = int(bbox[1])

        #print("y1 {}: y2 {}, x1 {}: x2 {}".format(y1, y2, x1, x2))
        #print("bbox[3] {} : bbox[1] {}, bbox[0] {}: bbox[2] {}".format(bbox[3], \
        #    bbox[1], bbox[0], bbox[2]))
        crop = im[y2:y1, x1:x2]
        #print("crop.shape and type", crop.shape, crop.dtype)
        #append bbox and crop to list if height and width are not zero
        if crop.shape[0]!= 0 and crop.shape[1]!=0:
            thumbs.append(crop)
            bboxes.append(bbox)

        #predict gender in crop
        #height = int(bbox[3])-int(bbox[1])
        #width = int(bbox[2])-int(bbox[0])
        height, width, _ = crop.shape
        #print("height {}  width {}".format(height, width))

        if crop.shape[0]!= 0 and crop.shape[1]!=0:
            gender = pred_gender(crop)
            #print("gender", gender)
            if gender == 'Male':
                pixelated = pixelate(crop, width, height)
                #replace im crop with pixelated
                im[y2:y1, x1:x2] = pixelated

        #draw bounding boxes in RBG detection order
        if(i==0):
            box_color = (255, 0, 0) #red
        elif(i==1):
            box_color = (0,155,255) # blue
        else:
            box_color = (0, 255, 0) # green
        #params:  (image, (x,y of top L), (x,y of bottom R), 
        # color, line type)
        cv2.rectangle(im, (int(bbox[0]), int(bbox[3])), \
            (int(bbox[2]), int(bbox[1])), box_color, 2)


    ```

**Comment by nyck33** [comment]
@alalek what do you need for this to be "complete"?

**Comment by alalek** [comment]
All people should be able to run reproducer easily using provided information and ensure that they reproduce mentioned problem ("actual results" must be filled).

https://github.com/opencv/opencv/issues/15408#issuecomment-525808311

**Comment by nyck33** [comment]
@alalek,

Okay, I'll try to write a simplified version of the script that includes the function as it won't run without the associated deep learning CNN libraries from Tencent DFSD on Github.  Thanks!

**Comment by dkurt** [comment]
Closing it until reproducible sample is provided.
