### ISSUE TITLE
Object detection sample code does not work with YOLOv3 model

### ISSUE THREAD

**Issue by rgov** [opencv/opencv#15403]
- OpenCV => 4.1.0
- Operating System / Platform => macOS 10.14.6
- Compiler => Python 3

##### Detailed description

The `object_detection.py` script barfs when using YOLOv3 weights and config.

##### Steps to reproduce

Download weights and config:

```
wget https://pjreddie.com/media/files/yolov3.weights  
wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg
```

Run the example code:

```
$ python object_detection.py --model yolov3.weights --config yolov3.cfg
Traceback (most recent call last):
  File "object_detection.py", line 71, in <module>
    net = cv.dnn.readNet(cv.samples.findFile(args.model), cv.samples.findFile(args.config), args.framework)
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/darknet/darknet_io.cpp:509: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'
```

**Comment by ManzarIMalik** [comment]
@rgov, I am having this code error in object detection sample code file. How did you fix this?

`if args.async: line 234
                ^
SyntaxError: invalid syntax`

**Comment by rgov** [comment]
@ManzarIMalik My guess is that you are running Python 3.7 or newer, where the `async` keyword is reserved. You will have to change the variable name used by the sample code, or use an earlier version of the sample code (a few commits back) that does not provide the async feature.

Please post back if that works.

**Comment by ManzarIMalik** [comment]
@rgov, Yes it works now. Thank you :)

**Comment by zhoujinhai** [comment]
@rgov， Hello, I am having this error, Have you ever met?
```
 File "object_detection.py", line 262, in processingThreadBody
   outs = net.forward(outNames)

cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers
\concat_layer.cpp:95: error: (-201:Incorrect size of input array) Inconsistent s
hape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'
```

**Comment by zhoujinhai** [comment]
@rgov
The code is run, but the result is bad, What parameters do you need to adjust?
```python
python detection.py --input 000035.jpg --model yolov3.weights --config yolov3.cfg --width 416 --height 416 --classes coco_classes.txt
```

![image](https://user-images.githubusercontent.com/20365125/64342711-ad33e880-d01d-11e9-9449-8ecfe734ed30.png)

**Comment by zhoujinhai** [comment]
![image](https://user-images.githubusercontent.com/20365125/64343228-b83b4880-d01e-11e9-9bdc-ee7508bbd250.png)

**Comment by rgov** [comment]
Hi @zhoujinhai maybe this will help you? https://stackoverflow.com/questions/57679946/poor-object-detection-with-opencv-dnn-and-yolov3 The answer involves passing the `--scale` and `--rgb` parameters.

**Comment by zhoujinhai** [comment]
@rgov yes, it run well after add ```--scale```， I have an other question that I train my model(model.h5) by [qqwweee](https://github.com/qqwweee/keras-yolo3)，then I convert the model's format to model.weights, but the result is so bad,  Do you have any good suggestions?

use-> model.weights model.cfg and classes
![image](https://user-images.githubusercontent.com/20365125/64391277-ba32f500-d07a-11e9-88b0-86f8b5df0b43.png)

use->model.h5
![image](https://user-images.githubusercontent.com/20365125/64391496-87d5c780-d07b-11e9-8b1b-12a52c3d5117.png)

**Comment by rgov** [comment]
Sorry @zhoujinhai, I don't know. I suggest posting your question to StackOverflow or https://answers.opencv.org.

**Comment by zhoujinhai** [comment]
@rgov ok, thanks.
