### ISSUE TITLE
why my cpu usage getting lower and lower

### ISSUE THREAD

**Issue by jialebifashi** [opencv/opencv#15428]
By the program start I may got at least 90% of cpu usage , and it run fast !   Ater a little while I feel my program getting slower , the cpu usage is becoming lower and lower by time ,  finally only 50% at most.   I track the code and find out  it takes more and more time for each [detectAndCompute] function ,   several parts inside of the function gets slower,  and they all called [parallel_for_] ,    i tracked one [parallel_for_]'s Circulatory body and is the [AutoBuffer] class cost most of the time!
All above code used thread_pool,  so i run in Single thread and it turns out the same!  I don't know if is the CPU usage reduce caused the [AutoBuffer] class use more time for each call, or they are two independent issues !
windows 10 ,  intel i7 8900K or AMD 3900X(both tried) ,   cmake opencv with tbb or openmp(both tried), also with intel MKL ,  cpu_baseline and cpu_dispatch both avx2.     
also when using thread_pool , even i waited  for all sub thread successfully finish them job ,and reassign task , the problem remains , so i think is not dead lock or some normal program bug. in a word , as long as the program haven't been restarted ,  the problem remains.
Coud anyone tell me what possiblely cause these problem?
By the way , i used opencv 4.1.0   and opencv_contrib-master

**Comment by dkurt** [comment]
Please follow issues creation guidelines and provide a reproducer.
