### ISSUE TITLE
PNG image decode result is not correct with Imgcodecs.IMREAD_UNCHANGED flag

### ISSUE THREAD

**Issue by tc350981** [opencv/opencv#15420]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => redhat 7, 64bit
- Compiler => gcc

##### Detailed description
My operation is pretty simple:
1. load png image to byte array
2. decode image to Mat
3. resize Mat
4. encode Mat to bytes
5. write bytes as a file

Issue: The output file is all white pixels if I use Imgcodecs.IMREAD_UNCHANGED decode flag. However, if I use Imgcodecs.IMREAD_ANYCOLOR decode flag the output image is good. I attached the input image and the two output images.

Please see the following example code

##### Steps to reproduce
I use OpenCV jni, code is in Java

public void test() throws Exception {
    System.load("*/libopencv_java410.so");
    byte[] imageData = Files.readAllBytes(Paths.get("/home/xwang4/Desktop/input.png"));
    MatOfByte matOfByte = new MatOfByte(imageData);
    Mat image = Imgcodecs.imdecode(matOfByte, Imgcodecs.IMREAD_ANYCOLOR);
    matOfByte.release();
    Mat result = new Mat(104, 200, image.type());
    Imgproc.resize(image, result, result.size(), 0, 0, Imgproc.INTER_AREA);
    MatOfInt params = new MatOfInt();
    MatOfByte imageBytes = new MatOfByte();
    List<Integer> quality = new ArrayList<>();
    quality.add(Imgcodecs.IMWRITE_JPEG_QUALITY);
    quality.add((int) (0.9 * 100));
    quality.add(Imgcodecs.IMWRITE_JPEG_PROGRESSIVE);
    quality.add(1);
    params.fromList(quality);
    Imgcodecs.imencode(".jpeg", result, imageBytes, params);
    byte[] bytes = imageBytes.toArray();
    Files.write(Paths.get("/home/xwang4/Desktop/testOutput.jpeg"), bytes, StandardOpenOption.CREATE);
    image.release();
  }

Input image: 
![input_image](https://user-images.githubusercontent.com/9836492/63983272-d0d5bc80-ca7a-11e9-983b-952b701bfd06.png)
bad output image with Imgcodecs.IMREAD_UNCHANGED decode flag:
![bad_output_image_with_IMREAD_UNCHANGED_flag](https://user-images.githubusercontent.com/9836492/63983285-e2b75f80-ca7a-11e9-8518-b625e37f9f73.jpeg)
good output image with Imgcodecs.IMREAD_ANYCOLOR decode flag:
![good_output_image_with_IMREAD_ANYCOLOR_flag](https://user-images.githubusercontent.com/9836492/63983317-05497880-ca7b-11e9-8019-9f8d84493b0d.jpeg)

**Comment by alalek** [comment]
> IMREAD_UNCHANGED

Reads 16-bit 3 channel image (ushort: 0-65535).

> IMREAD_ANYCOLOR

Reads 8-bit 3 channel image (uchar: 0-255).


> PNG image decode result is not correct

This is not true.

---

Problem of your pipeline is encoding step - encoder doesn't support 16-bit inputs and it doesn't automatically downscale values from 16-bit into 8-bit (it is responsibility of caller code).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by tc350981** [comment]
ah, thanks for the response!
