### ISSUE TITLE
Not all data type combinations are being tested with the integral function performance tests

### ISSUE THREAD

**Issue by everton1984** [opencv/opencv#15439]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Linux 64bit
- Compiler => gcc

##### Detailed description

I'm trying to analyse the performance of the integral function for several parameter
combinations since some of those combinations use HAL instructions and others do
not. Running the performance tests I realised that only one combinations of matrix
size for square sum and sum matrices.

**Comment by alalek** [comment]
There is no goal to test everything on performance regressions.
Only most interested/useful/representative cases should be tested for performance on regular basis.

If you want more detailed tests, please create them with `DISABLED_` prefix (which you can use during development / optimization of the target function via `--gtest_also_run_disabled_tests`).

**Comment by everton1984** [comment]
Where should I add the DISABLED_ prefix exactly? Before PERF_TEST_P?

**Comment by everton1984** [comment]
Just made the new tests disabled by default on PR #15440 as requested.
