### ISSUE TITLE
does opencv support cuda runtime apis cudadevicesynchronize() ? 

### ISSUE THREAD

**Issue by shivSD** [opencv/opencv#15441]
Opencv 3.4.5
OS: ubuntu 
cuda: 10.0

 I'm using opencv cv::cuda::warpPerspective() functions now i need to wait till the all the threads complete the process. Is there any method in the cv::cuda to check or wait till all the threads are completed. I have tired cv::cuda::cudadevicesynchronize() but i'm getting unrecognized functions error.

**Comment by yasamoka** [comment]
You can use cudaDeviceSynchronize() normally just like you would in any other CUDA application.

The documentation can help greatly when you want to check how something works in OpenCV:
https://docs.opencv.org/3.4.5/

As an added bonus, check out how cv::cuda::Stream works and see if that helps you in your project as well. Streams provide waitForCompletion() which is a wrapper for cudaStreamSynchronize(), if you also end up using CUDA streams.
