### ISSUE TITLE
Segmentation Fault protobuf InitDefaultsMethodImpl()

### ISSUE THREAD

**Issue by M0l0ch0** [opencv/opencv#15448]
##### System information (version)

- OpenCV => : OpenCV 3
- Operating System / Platform => ros-melodic-desktop-full on Manjaro
- Compiler => :gcc 9.1

##### Detailed description

I'm installing ROS in my linux but when bulding  opencv i get a segmentation Fault in the function InitDefaultsMethodImpl()  i got this message:
during GIMPLE pass: wrestrict
En la función ‘void protobuf_google_2fprotobuf_2fapi_2eproto::InitDefaultsMethodImpl()’:
Violación de segmento
   67 | void InitDefaultsMethodImpl() {
      |      ^~~~~~~~~~~~~~~~~~~~~~
Por favor, envíe un informe completo de errores,
con el código preprocesado si es apropiado.
Véase <https://bugs.archlinux.org/> para instrucciones.
make[2]: *** [3rdparty/protobuf/CMakeFiles/libprotobuf.dir/build.make:401: 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/api.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:325: 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
==> ERROR: Se produjo un fallo en build().

**Comment by alalek** [comment]
Sorry, we really can't fix internal compiler errors (most of them are due lack of free memory).
See this thread #15334 and others
