### ISSUE TITLE
OpenVino inference engine fails on Raspberry Pi 4+NCS 2+OpenCV compiled from source

### ISSUE THREAD

**Issue by refigh** [opencv/opencv#15446]
I already opened a post about this on[ opencv forum](https://answers.opencv.org/question/217711/openvino-inference-engine-fails-on-raspberry-pi-4ncs-2opencv-compiled-from-source/), but got no answer and want to repeat it here.

Hello, I have used below config on an ARM board (Asus tinker board s) successfully for many DNN models (YOLO3, bvlc, squeezenet,...). I also have used different model inputting methods, i.e., reading original model format and let opencv-openvino convert it to intel IR model, or directly input my own converted IR_16 models. All worked. 

Board: Asus tinker board s (ARM 7)
Python 3.5.3 (shipped with latest 32bit Linaro Linux)
gcc 6.3.0 20170516
OpenCV 4.1.1 (compiled from source)
OpenVino 2019 R2

But recently I moved to Raspberry Pi 4 board. The only differences I notice are:

Python 3.7.3
gcc 8.2.0

When I use NCS2, I get below errors exactly when I run "net.forward" inference command in python. Inference on CPU, i.e. without using NCS2 works fine. My test code is [this short code by intel](https://software.intel.com/en-us/forums/computer-vision/topic/803928#comment-1933110) to test NCS2 :

- when model is original model (like caffe model), with CV_32 or CV_8 blob depth, error is: pure virtual method called, terminate called without an active exception, Aborted
- when model is manually converted IR16 model with CV_8, error is: corrupted double-linked list, Aborted

This is my openCV compile instruction (OpenVino 2019 R2 already installed):
cmake
-D CMAKE_BUILD_TYPE=RELEASE
-D WITH_INF_ENGINE=ON
-D ENABLE_NEON=ON
-D ENABLE_VFPV3=ON
-D WITH_V4L=ON
-D ENABLE_CXX11=ON
-D CMAKE_INSTALL_PREFIX=/usr/local
-D INSTALL_PYTHON_EXAMPLES=OFF
-D INSTALL_C_EXAMPLES=OFF
-D ENABLE_PRECOMPILED_HEADERS=OFF #added to remove a [compile error](https://github.com/opencv/opencv/issues/14868)
-D OPENCV_ENABLE_NONFREE=ON
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules
-D PYTHON_EXECUTABLE=/usr/bin/python3
-D WIDTH_GTK=ON
-D BUILD_TESTS=OFF
-D BUILD_DOCS=OFF
-D WITH_GSTREAMER=ON
-D WITH_FFMPEG=ON
-D CMAKE_CXX_FLAGS=-latomic #added to remove compile error of [atomic operations](https://github.com/opencv/opencv/issues/15278)
-D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic
-D BUILD_EXAMPLES=OFF ..

`make -j2; sudo make install; sudo ldconfig;`

and then I run to replace default opencv-openvino with my own compiled one:
```
sed -i '1iINSTALLDIR=/opt/intel/openvino' /opt/intel/openvino/opencv/setupvars.sh;
echo 'export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH' | grep '\$' >> ~/.bashrc
echo 'export PYTHONPATH=/usr/local/lib/python3.7/dist-packages/:$PYTHONPATH' | grep '\$' >> ~/.bashrc 
```

everything was fine on AsusTinkerboard S + NCS2, but now on RaspberryPi4 inference on NCS2 fails.

I want to add a point: when I use small opencv shipped with openvino 2019R2-Raspberry version, problem does not exist. I can run inference on Raspberry Pi 4+NCS2 (MYRIAD). But when I compile OpenCV from source to have access to additional functions such as tracking functions, (I do not use cross-compile, I directly compile on the device, as I explained the steps earlier), running inference on Raspberry Pi 4 + NCS2 (MYRIAD) gives errors I mentioned earlier. I have no problem on Raspberry 4+DNN_TARGET_CPU, or Raspberry 4+NCS2+default OpenCV-OpenVino. Problem only exists on: Raspberrypi 4+ NCS2+my own complied openCV. I though maybe my compiling procedure is wrong, but interesting point is that by following exactly same procedure on an older ARM board, Asus Tinker board S, NCS2 works ok with compiled opencv.

Is there any idea what is source if this issue? Unfortunately it is not easy, but only solution I have is to downgrade from python 3.7.3 to python 3.5.3, and downgrade gcc.

**Comment by dkurt** [comment]
Can you provide a stacktrace?

**Comment by refigh** [comment]
> 
> 
> Can you provide a stacktrace?

no exception is generated, so I can't handle it and print stack trace. When run "net.forward", error message is:
```
pure virtual method called
terminate called without an active exception
Aborted
```
I try to use cross-compile instead of direct compiling, but anyway such issue exists on RaspberryPi 4.

**Comment by alalek** [comment]
You need `gdb` (install via system package manager):
```
gdb -ex r --args python your_script.py ...
... running ...
... stop message from gdb ...
(gdb) bt
... stack trace is here ...
(gdb) info threads
(gdb) info sharedlibrary
```

**Comment by refigh** [comment]
good news is with cross compile as explained [here](https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend), with some modification to add opencv_contrib folder, etc, problem does not happen.

**Comment by refigh** [comment]
I review the procedure again and reconfirm again: 
direct compile of opencv on raspberry pi 4 is problematic, but cross-compile is ok.

this is output of debug (with @alalek instructions):
(gdb) bt
#0  0xb6cfdf24 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xb6ce9230 in __GI_abort () at abort.c:79
#2  0xb27ae8d8 in __gnu_cxx::__verbose_terminate_handler() ()
    at /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#3  0xb27ac5b0 in  () at /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#4  0xb27ac624 in  () at /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#5  0xb27ad4c8 in __cxa_pure_virtual ()
    at /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#6  0xb21eb3f6 in  ()
    at /opt/intel/openvino/deployment_tools/inference_engine/lib/armv7l/libinference_engine.so
(gdb) info threads
  Id   Target Id                               Frame 
* 1    Thread 0xb6ff81e0 (LWP 31104) "python3" __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
