### ISSUE TITLE
Python error for 4.1.0 - cv.imshow(winname, mat	) not implemented

### ISSUE THREAD

**Issue by sunilvb** [opencv/opencv#15447]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Raspberry Pi 4 / Python 3.7.3
- Compiler => cpp

##### Detailed description

I am trying to run a python3.7 code with OpenCV 4.1 on Raspberry 4
I have OpenCV compiled and installed on RPi4 and tested the version number with cv2.__version__ command.

I get an error when I try to run the Capture Video from Camera sample from https://docs.opencv.org/4.1.0/dd/d43/tutorial_py_video_display.html

The error message is as follows : 
cv2.error: OpenCV(4.1.0) /home/pi/opencv/modules/highgui/src/window.cpp:627: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
