### ISSUE TITLE
convert keras model mask-rcnn to file .pb

### ISSUE THREAD

**Issue by hoangtubatu123** [opencv/opencv#15453]
I tried to convert keras model to file which forms .pb. i want to use it in cv::dnn in c++. But i tried many times and i had a problem: 
<img width="562" alt="Screen Shot 2019-09-04 at 5 44 10 PM" src="https://user-images.githubusercontent.com/30885438/64273853-5f12dc80-cf6c-11e9-968b-814a178ee94c.png">
Please help me. i need your help. Thanks

**Comment by dkurt** [comment]
Please use a forum for usage questions: answers.opencv.org

If you want to report a bug or create a feature request - follow issues template.
