### ISSUE TITLE
DNN is absurdly slower on android

### ISSUE THREAD

**Issue by gulzainali98** [opencv/opencv#15450]
##### System information (version)

- OpenCV =>  4.1.1
- Operating System / Platform =>  Android/ Lenovo Z5
- Compiler => Cmake

##### Detailed description

I have a caffe model of mtcnn and a caffe model of sphereface. I have built a pipeline that takes an image and produces an embedding of the face. Pipeline is written in c++. On my CPU i5 processor opencv dnn is loading the models and is taking 100 milliseconds for processing. Exactly same code when i deploy on android takes around 20 times more time for execution. I have tried compiling opencv on android using MKL and openblas but i found no different at all in processing speed. Here is my cmake configuration:

"-DBUILD_opencv_world=ON -DBUILD_opencv_gapi=OFF -DWITH_NVCUVID=OFF " +
                        "-DWITH_CUBLAS=ON -DWITH_MKL=ON -DMKL_USE_MULTITHREAD=ON -DMKL_WITH_TBB=ON -DWITH_TBB=ON " +
                        "-DINSTALL_TESTS=ON -DINSTALL_C_EXAMPLES=ON -DBUILD_EXAMPLES=ON -DWITH_OPENGL=ON" +
                        "-DOPENCV_ENABLE_NONFREE=ON -DWITH_NVCUVID=ON -DWITH_MFX=ON"

##### Steps to reproduce

Simply take any caffe model and run it on CPU and then use the same code android. Android processing will be a lot slower. I am expecting this to be slow on android but it is absurdly slower in my case. I can expect 4 to 5 times slower performance but 20 times is just not acceptable.

**Comment by mshabunin** [comment]
Did you enable NEON optimizations?

**Comment by gulzainali98** [comment]
can you guide me a little bit on how to turn the neon optimization on? maybe a tutorial would help.
