### ISSUE TITLE
net can't forward again?

### ISSUE THREAD

**Issue by cuixing158** [opencv/opencv#15452]
my envs: openVINO2019.1.148+win10+VS2015
When I use bvlc_googlenet.xml and the bvlc_googlenet.bin model to extract image features, the network model can only successfully forward only one time. When the second time loop, images length is not the same with the first time,it will go wrong. Why,any idea ? thank you!

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.1.0-openvino) Error: Assertion failed (!isInitialized()) in cv::dnn::InfEngineBackendNet::initPlugin, file C:\jenkins\workspace\OpenCV\OpenVINO\build\opencv\modules\dnn\src\op_inf_engine.cpp, line 688

The main code that caused the error is：
```
Net net = readNetFromModelOptimizer(xmlFile,model);// 此模式下必须设置为DNN_BACKEND_INFERENCE_ENGINE
	if (net.empty())
	{
		cout << "net is empty!" << endl;
	}
	net.setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE);
	net.setPreferableTarget(DNN_TARGET_CPU);

	int net_size = 224;
	images.clear();
	images.push_back(img);

	while (true)
	{
		Mat blob;
		blobFromImages(images, blob, 1.0, Size(net_size, net_size), Scalar(104, 117, 123), false);
		net.setInput(blob);
		Mat prob = net.forward("pool5/7x7_s1"); // second time, error! (when images length is not the same with the first time)
            images.push_back(img); // for example , add image to images
      }
```

![err](https://user-images.githubusercontent.com/22857777/59490596-b21e4b80-8eb7-11e9-9a6e-9f68f6465bca.png)

**Comment by Kulikovpavel** [comment]
Any solution for this?

**Comment by JulienMaille** [comment]
@dkurt sorry for the mentions, I too have this issue when running inference a second time with a different input shape. I was able to confirm it works with cpu backend, gpu cuda backend but not with cpu OpenVino. Network is a basic Unet.
Reproduce with latest OpenCV but OpenVino 2019.R3
> OpenCV(4.3.0-dev) Error: Assertion failed (!isInitialized()) in cv::dnn::InfEngineBackendNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp, line 742

**Comment by dkurt** [comment]
@JulienMaille, please upload the model so we can reproduce it.

**Comment by JulienMaille** [comment]
Ok, can I send it on a private email? Although I don't think it is specific to any model but rather to the way IE is reinited.

I traced the assert to `netWasAllocated` being set to false when input size is changed.
https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L3967 Then when calling `Net::forward`, which calls `Net::impl::setUpNet()` we end up in
https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L1452 https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L1601 https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L1793 then in `InfEngineBackendNet::init()`
https://github.com/opencv/opencv/blob/ca23c0e630ba9c4fc147c4913d6238f5de3bbcd9/modules/dnn/src/op_inf_engine.cpp#L422 and this assert will fail
https://github.com/opencv/opencv/blob/ca23c0e630ba9c4fc147c4913d6238f5de3bbcd9/modules/dnn/src/op_inf_engine.cpp#L740-L742

**Comment by JulienMaille** [comment]
@dkurt  note that when `skipInfEngineInit` is True `InfEngineBackendNet::init()` is called unconditionally
https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L1792-L1794 while there's a test otherwise
https://github.com/opencv/opencv/blob/b8579f12be35b4ecafec5059245ee9f66e0210ac/modules/dnn/src/dnn.cpp#L1975-L1979

**Comment by dkurt** [comment]
Sure, please find in in the profile

**Comment by JulienMaille** [comment]
@dkurt email sent, let me know if there's any approaches I could try by myself.

**Comment by dkurt** [comment]
Thanks everyone! Please try this patch: https://github.com/opencv/opencv/pull/17102

**Comment by JulienMaille** [comment]
Hmm I've cherry-picked your commit on top of origin/master and it' still crashing in the assert.
Are you sure that the `ieNode->net->init((Target)preferableTarget);` call shouldn't be skipped in addtion to your pach?
https://github.com/opencv/opencv/blob/ca23c0e630ba9c4fc147c4913d6238f5de3bbcd9/modules/dnn/src/op_inf_engine.cpp#L740-L742

**Comment by dkurt** [comment]
@JulienMaille, can you please show a code example? I've tried the following one:
```cpp
#include <iostream>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace cv::dnn;

Mat runWithReshape(const Mat& inp) {
  Net net = readNet("model.xml", "model.bin");

  Mat inp0(256, 256, CV_32FC1);
  randu(inp0, -1, 1);
  inp0 = blobFromImage(inp0);
  net.setInput(inp0);
  Mat out0 = net.forward();

  net.setInput(inp);
  return net.forward();
}

Mat runWithFixedShape(const Mat& inp) {
  Net net = readNet("model.xml", "model.bin");
  net.setInput(inp);
  return net.forward();
}


int main(int argc, char** argv) {
  Mat inp(312, 312, CV_32FC1);
  inp = blobFromImage(inp);
  Mat ref = runWithFixedShape(inp);
  Mat out = runWithReshape(inp);
  std::cout << norm(ref, out, NORM_INF) << std::endl;
  return 0;
}

```

**Comment by JulienMaille** [comment]
I'll try to reproduce with your code, but do you agree that our crash has to do with an assert checking we don't call `ieNode->net->init()` twice? And you patch doesn't change this, correct?

**Comment by JulienMaille** [comment]
@dkurt I suppose you tried in nGraph mode? Can you check without `HAVE_DNN_NGRAPH`?

**Comment by dkurt** [comment]
@JulienMaille, tried with both nGraph and NNBuilder modes.

**Comment by JulienMaille** [comment]
@dkurt This also works fine on my setup. I tried to understand why my code still fails the assert. And after recompiling opencv the failing assert is gone. I must have messed up somewhere. I still don't understand why your patch fixed the assert that I had (and that the OP had too).
Anyway, thanks for that quick patch!

In term of performances, on a gpu, will the openCL code be generated every-time the input size changes?

**Comment by dkurt** [comment]
Thanks! For OpenCL I highly recommend to take look at cl-cache feature - it not just only about deep learning but general the best known method working to avoid resundant OpenCL kernels recompilation.

see https://github.com/intel/compute-runtime/blob/19.23.13131/documentation/FAQ.md#feature-cl_cache

**Comment by JulienMaille** [comment]
Is it available out of the box with OpenCV? I just create an cl_cache folder next to my executable and I'm good?

**Comment by dkurt** [comment]
@JulienMaille, it's not only about OpenCV or OpenVINO - it's about OpenCL and supported at the driver. You need to create a folder and setup an environment variable `cl_cache_dir` with an absolute path to it - then after first run it will contain OpenCL cache.

**Comment by alalek** [comment]
> D:\Dev

`cl_cache_dir` environment doesn't work on Windows.
`cl_cache` directory in current working directory (CWD) should work well.

Create directory and run your app - check directory contents (it works if you can see new files there)

**Comment by JulienMaille** [comment]
What if my app is in /program files (x86)/ ie. with limited write permissions?

**Comment by alalek** [comment]
You need to configure Windows registry - refer to mentioned document from OpenCL repository.

**Comment by JulienMaille** [comment]
I tried the cl_cache directory trick in a folder where I have write persmissions but cl_cache stays empty. Do I need to compile OpenCV with a specific intel compiler for this to work?

**Comment by JulienMaille** [comment]
@alalek sorry for this out-of-topic question, but can you confirm if cl_cache requires anything special?

**Comment by dkurt** [comment]
@JulienMaille , https://github.com/intel/compute-runtime/blob/19.23.13131/documentation/FAQ.md#windows-configuration
