### ISSUE TITLE
(Question)  Need to load ERT(Ensemble Regression Tree) XML model using OpencvJS

### ISSUE THREAD

**Issue by vasanthhr** [opencv/opencv#15455]
Hello,

We have trained Ensemble Regression Tree for face landmark detection( 68 points ), the saved model is in .xml format. I didn't find any example on how to load this XML model using opencv.js 

`(Model saved as : ert_face.xml)`

Can someone please guide here on how to load this model using OpenCV.js

**Comment by vasanthhr** [comment]
@alalek 

Let me know what is the reason is it closed?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
