### ISSUE TITLE
Incorrect error message for non-integer points in rectangle draw function: TypeError: function takes exactly 4 arguments (2 given)

### ISSUE THREAD

**Issue by maxschommer** [opencv/opencv#15465]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => :grey_question:

##### Detailed description

The rectangle function is meant to take integer tuples for p1 and p2, however when floats are used instead, a `TypeError: function takes exactly 4 arguments (2 given)` error is given, instead of a `TypeError: integer argument expected, got float`, which is the response given by the line function. The error given is very misleading, and I believe it would be more useful to give the same error that other drawing functions give when non-integers are used. 

##### Steps to reproduce
```
import numpy as np
import cv2

img = cv2.rectangle(np.ones((10, 10)),(384.2,0),(510,128),1)
```
This throws the error, `TypeError: function takes exactly 4 arguments (2 given)`, while

`img = cv2.line(np.ones((10, 10)),(384.2,0),(510,128),1)` throws `TypeError: integer argument expected, got float`.

**Comment by maxschommer** [comment]
@alalek Why was this tagged as a question?

**Comment by spongebobZ** [comment]
I meet this lousy problem too

**Comment by ajithvallabai** [comment]
i think it is because of the reason that you are executing a python2 code in python3 but i am not sure of it

**Comment by spongebobZ** [comment]
The reason of this issue is I set two locations as float type, but I think this is quite confusing 😅

在 2019-10-14 14:13:07，Ajith <notifications@github.com> 写道：


i think it is because of the reason that you are executing a python2 code in python3 but i am not sure of it

**Comment by ajithvallabai** [comment]
ok

**Comment by davae1an** [comment]
same here getting this error

**Comment by jakubLangr** [comment]
I got the same error, but everything is a tuple of ints?

**Comment by alalek** [comment]
Investigate problem by using `OPENCV_PYTHON_DEBUG=1` environment variable.

**Comment by mnsuccess** [comment]
getting the same error

**Comment by alexanderfrey** [comment]
This could be a integer overrun.

**Comment by Linranran** [comment]
got the same error!   
python3.8
opencv3.4

**Comment by MLDLCo** [comment]
I got the same issue. I resolved it by converting all the coordinate of the bounding box into int instead of float. You are facing the problem because of one coordinate in float

**Comment by maxschommer** [comment]
@MLDLCo The issue isn't that ints are required, rather that the wrong error message is being given for this problem. It should give `TypeError: integer argument expected, got float.` instead of `TypeError: function takes exactly 4 arguments (2 given)`.

**Comment by thuphuong1401** [comment]
@MLDLCo thank you very much! Your solution solves my problem.

**Comment by shakti365** [comment]
> I got the same error, but everything is a tuple of ints?

@jakubLangr Make sure it is int32 and not int64

**Comment by VanditGupta** [comment]
> I got the same issue. I resolved it by converting all the coordinate of the bounding box into int instead of float. You are facing the problem because of one coordinate in float

@MLDLCo  Thank You.

**Comment by bryangreener** [comment]
I had the same error which ended up being caused by my color tuple being a tuple of numpy.int32 values which I thought were allowed in cv2. I had to manually convert the items to the stock python int() type.

This error message definitely needs to be fixed since it leads you down the wrong rabbit hole for a long time before you realize what the actual problem is.

**Comment by kirbyderby2000** [comment]
Ran into this problem too, started questioning my sanity because I was providing more than 2 arguments when it was complaining that I wasn't. Casting the tuple values into ints made this error go away.

**Comment by crackwitz** [comment]
OpenCV should get more tolerant of various data types when it expects exactly tuples of integers. it would be great if OpenCV accepted floats in addition to ints, and if it accepted numpy arrays in addition to tuples.

**Comment by yartem** [comment]
sometimes this happen when coordinates are out of image.shape

**Comment by Ryan-Awad** [comment]
This is cause because you tuples contain floats. OpenCV takes integers within those tuples.

**Comment by maxschommer** [comment]
As an update, I ran with `OPENCV_PYTHON_DEBUG=1` environment variable while compiled in debug mode:

```
>>> img = cv2.rectangle(np.ones((10, 10)),(384.2,0),(510,128),1)
[ INFO:0] global /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp (1176) haveOpenCL Initialize OpenCL runtime...
[ INFO:0] global /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp (1182) haveOpenCL OpenCL: found 1 platforms
[ INFO:0] global /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp (974) getInitializedExecutionContext OpenCL: initializing thread execution context
[ INFO:0] global /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp (984) getInitializedExecutionContext OpenCL: creating new execution context...
OpenCV(4.5.1-dev) Error: Unknown error code -220 (OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clCreateContext) in createFromDevice, file /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp, line 2557
[ INFO:0] global /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp (1017) getInitializedExecutionContext OpenCL: Can't initialize OpenCL context/device/queue: OpenCV(4.5.1-dev) /home/maxschommer/Documents/Github/opencv/modules/core/src/ocl.cpp:2557: error: (-220:Unknown error code -220) OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clCreateContext in function 'createFromDevice'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes exactly 4 arguments (2 given)
```

**Comment by maxschommer** [comment]
Ok, so I noticed that one difference between `line` and `rectangle`, despite having identical call signatures, is that `rectangle` had one overload:
```
void rectangle( InputOutputArray img, Rect rec,
                const Scalar& color, int thickness,
                int lineType, int shift )
```

I commented out this function, recompiled and got the correct error message:
```
>>> img = cv2.rectangle(np.ones((10, 10)),(384.2,0),(510,128),1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: integer argument expected, got float
```

So it seems that the issue might have something to do with how functions with overloads are parsed.

**Comment by VadimLevin** [comment]
The root cause of the issue is current implementation of the overload resolution in the generated Python bindings. First of all it tries to parse arguments for  
```cpp
void rectangle(InputOutputArray img, Point pt1, Point pt2, const Scalar& color, 
               int thickness = 1, int lineType = LINE_8, int shift = 0);
```
but it fails (because floats are not convertible to integers as was already stated above) - it sets error message, but in C++ interface there is an overload, that clears previously set error message:
```cpp
void rectangle(InputOutputArray img, Rect rec, const Scalar& color,
               int thickness = 1, int lineType = LINE_8, int shift = 0);
``` 
that accepts tuple with 4 elements as the second argument. First it is checking the tuple length - you provide tuple with 2 elements instead of 4 - error message as reported to user as the last set.

In my opinion, to solve the problem with inappropriate/misleading message the following steps should be done:
1. Update the logic for argument parsing - argument name or at least argument index should present in the reported error (if possible, e.g. while parsing tuples with default `PyArg_ParseTuple` it is not possible).
2. Collect all error messages during overload resolution.
3. If the last overload fits - use it and forget about previous errors.
4. Otherwise raise custom OpenCV exception of `OverloadError` type with previously collected messages.
The main drawback of the suggested way is a small overhead increasing for functions calls.

**Comment by chado98** [comment]
i recommande to install the version python 3.4.8.29
pip install -U opencv-python==3.4.8.29
