### ISSUE TITLE
Does opencv support connect constant nodes as connect nodes?

### ISSUE THREAD

**Issue by vonchenplus** [opencv/opencv#15470]
Hello guys,

I use readNetFromTensorflow to read a [face detection model](https://drive.google.com/open?id=1growhXi9KL7OlDxF76Xq8oX9Fnkr0nfu) failed.
Because this model hava one 'StridedSlice' operation, have one ‘Const’ input, please see follow pictures:
![image](https://user-images.githubusercontent.com/3349963/64404387-575b5100-d0ae-11e9-9104-15f00e1077a3.png)
![image](https://user-images.githubusercontent.com/3349963/64404435-8b367680-d0ae-11e9-91fe-d73d7c67f5e7.png)

Can anyone tell me how to fixed it?

**Comment by dkurt** [comment]
Have you tried to follow the guide with TensorFlow Object Detection API? https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend

If this is not this kind of model please provide all the details of it's origin.

**Comment by vonchenplus** [comment]
hello @dkurt,

I don't really want to use OpenVINO.
And I upload model(https://drive.google.com/open?id=1growhXi9KL7OlDxF76Xq8oX9Fnkr0nfu) already, please have a look.

**Comment by dkurt** [comment]
@vonchenplus, Oh sorry, just a wrong link. Here it is: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by vonchenplus** [comment]
hello @dkurt,
I want to detect face instead of detect object.

**Comment by dkurt** [comment]
@vonchenplus, Hi!

Please specify origin of this model. If it is TensorFlow Object Detection API, have you tried a guide above?

**Comment by vonchenplus** [comment]
Hello @dkurt,
I think this is not the problem encountered by the face detection model alone.
And i upload a [face detection model](https://drive.google.com/open?id=1growhXi9KL7OlDxF76Xq8oX9Fnkr0nfu) already, please have a look.

In my experience, before converting checkpoint to pb, tf.graph_util.convert_variables_to_constants method will be called and convert variables into constant nodes, which will generate many constant inputs.

**Comment by dkurt** [comment]
@vonchenplus, just `.pb` file is not enough. That's why we asked you if the model has been trained in https://github.com/tensorflow/models/tree/master/research/object_detection or not. You should provide a `*.config` file to help us reproduce the problem.

**Comment by vonchenplus** [comment]
Hello @dkurt,
I download the pretrained model from https://github.com/yeephycho/tensorflow-face-detection/tree/master/model, and I didn't find any configuration files here. 

And other models I trained had similar problems, So I think this is a public issue.

**Comment by dkurt** [comment]
@vonchenplus, the problem is that this repository does not contain necessary configuration file which can help to extract model's hyperparametes. Please read https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. Unless author provide a `.config` file which was used in training (all the [public models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models) have this `pipeline.config` inside) we cannot infer it through OpenCV.

**Comment by vonchenplus** [comment]
hello @dkurt,
I think pipeline.config only appears in the tensorflow detection framework, Other frameworks may not need. For example, the classification model I trained myself does not have this file.

So, does it indicate that I need to generate a pipeline.config-like file for any model, to help opencv infer?

**Comment by dkurt** [comment]
@vonchenplus, that's right. It only used in TensorFlow Object Detection API and in the repository there is a [note](https://github.com/yeephycho/tensorflow-face-detection#tensorflow-face-detector) that this model has been trained inside it:

> A mobilenet SSD(single shot multibox detector) based face detector with pretrained model provided, powered by tensorflow object detection api, trained by WIDERFACE dataset.

**Comment by vonchenplus** [comment]
Hello @dkurt,
Thank you very much for your guidance.

Generating a pbtxt seems to solve the problem, but it is still more troublesome to generate such a file for each file. Expect further optimizations in OpenCV in the future.
