### ISSUE TITLE
Onnx model parsing error for resnet-34_kinetics.onnx 4.1.1

### ISSUE THREAD

**Issue by zkumar** [opencv/opencv#15471]
Just installed opencv (contrib) 4.1.1 downloaded the sample for action recognition and supporting files. Downloaded the ONNX model as per download_models.py from https://www.dropbox.com/s/065l4vr8bptzohb/resnet-34_kinetics.onnx?dl=1',
        sha='88897629e4abb0fddef939f0c2d668a4edeb0788',

but net = cv.dnn.readNet(net_path) is failing, I tried net = cv.dnn.readNetFromONNX(net_path), it is also failing.

error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:57: error: (-210:Unsupported format or combination of formats) Failed to parse onnx model in function 'cv::dnn::dnn4_v20190621::ONNXImporter::ONNXImporter'

I tested with OpenCV 3.4.5 and tried the code but error is consistent

error: OpenCV(3.4.5) C:\projects\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:57: error: (-210:Unsupported format or combination of formats) Failed to parse onnx model in function 'cv::dnn::experimental_dnn_34_v11::ONNXImporter::ONNXImporter'

Is this example tested?

**Comment by alalek** [comment]
> 4.1.1
> error: OpenCV(3.4.5)

Version should be the same.

> resnet-34_kinetics

Try latest releases at first. 3.4.5 is old and without support of that model.

**Comment by zkumar** [comment]
I assumed that I mentioned it was reproducible in latest as well as old version

error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:57: error: (-210:Unsupported format or combination of formats) Failed to parse onnx model in function 'cv::dnn::dnn4_v20190621::ONNXImporter::ONNXImporter'

**Comment by zkumar** [comment]
Only suspect is the Model it self. Is it possible to get the link to the model used in testing?

**Comment by alalek** [comment]
Download description is [here](https://github.com/opencv/opencv_extra/blame/7ccc96c0340a95a9d8ccffb3d1b3906d765e1ee2/testdata/dnn/download_models.py#L773-L777).

Size + hash sums:
```
$ ls -al resnet-34_kinetics.onnx
-rw-rw-r-- 1 alalek alalek 254257945 May 29 09:52 resnet-34_kinetics.onnx
$ sha1sum resnet-34_kinetics.onnx
88897629e4abb0fddef939f0c2d668a4edeb0788  resnet-34_kinetics.onnx
$ md5sum resnet-34_kinetics.onnx
41258eefdcb8b9a27f50dd0a753ff34c  resnet-34_kinetics.onnx
```

(BTW, sum utilits are available in "Git For Windows" package through bash shell)

**Comment by zkumar** [comment]
I have downloaded the model from the same location using same file.  Hash matches as per the script. Still this a error.  I am not sure some body can test at you end or the contributor at your end. I have been trying this for 2 days now.  Issue persists.

**Comment by dkurt** [comment]
@zkumar, check that `net_path` is valid. Most likely the problem in Window paths. You shoulduse escape symbols like `\\` for subfolders.
