### ISSUE TITLE
ORB detector behaves differently with submat

### ISSUE THREAD

**Issue by csterg** [opencv/opencv#15473]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => pre-compiled dll, using Java binding

##### Detailed description

Running the same code using a continuous and non-continuous mat returns different results.

##### Steps to reproduce

```
// Java code; should be easy to translate to c++
public class ORBBug {
  static String doOrb(Mat m1, Mat m2){  
    int patchSize = Math.min(m1.height(), Math.min(20, m1.width()));
    ORB orb = ORB.create(500, //number of features to retain
            1.1f, //Pyramid decimation ratio; default is 1.2
            8, //nlevel
            0, //edgeThreshold, 1pix
            2, //firstLevel
            2/*WTA_K*/, //#points for each feture, default 2
            ORB.HARRIS_SCORE, 
            patchSize/*patchSize*/, 
            20 //fastThreshold, def=20
    );
    MatOfKeyPoint kp1 = new MatOfKeyPoint();
    MatOfKeyPoint kp2 = new MatOfKeyPoint();
    Mat descr1 = new Mat();
    Mat descr2 = new Mat();    
    orb.detect(m1, kp1);
    orb.detect(m2, kp2);
    orb.compute(m1, kp1, descr1);
    orb.compute(m2, kp2, descr2);

    BFMatcher matcher = BFMatcher.create(Core.NORM_HAMMING);
    MatOfDMatch matOfDMatch = new MatOfDMatch();            
    matcher.match(descr1, descr2, matOfDMatch);
    String s = matOfDMatch.dump(); //just make a string
    descr1.release();
    descr2.release();
    return s;
  }
  
  
  public static void main(String[] args) {
    ImageUtils_OpenCV.init(); //load opencv dll in process memory
    File fFull = new File("test/bugs/orb/full.tif");
    File fSearch = new File("test/bugs/orb/search.tif");
    Mat full = Imgcodecs.imread(fFull.getAbsolutePath(), Imgcodecs.IMREAD_GRAYSCALE); 
    Mat search = Imgcodecs.imread(fSearch.getAbsolutePath(), Imgcodecs.IMREAD_GRAYSCALE); 
    Rect roi = new Rect(242,334,70,14);
    String s1 = doOrb(full.submat(roi), search);
    String s2 = doOrb(full.submat(roi).clone(), search);    
    System.out.println("results should be equal: " + s1.equals(s2));
  }
  
}
```
See attached files for testing: [test-images.zip](https://github.com/opencv/opencv/files/3583711/test-images.zip)

**Comment by alalek** [comment]
OpenCV submats are not "isolated" by default (main difference is related to borders handling)

**Comment by csterg** [comment]
Not sure what you mean. Is this expected behavior?

**Comment by kpentaris** [comment]
@alalek We know that OpenCV submats essentially reference a portion of the original mat but we expected the ORB detector to maybe detect and handle this. Is there a reason it doesn't?

**Comment by alalek** [comment]
OpenCV submats can utilize external pixels from the whole image to handle borders during filtering. Refer to `BORDER_ISOLATED` parameter meaning for details.

**Comment by csterg** [comment]
I read the BORDER_ISOLATED documentation. I get your point but I don't understand how this is related.

As it seems to me, this is a bug that for some reason you don't want to handle/fix, or I am not understanding why the same API call can return different values against the documented behavior.

**Comment by alalek** [comment]
ORB has filtering in implementation: https://github.com/opencv/opencv/blob/3.4.8/modules/features2d/src/orb.cpp#L1174

So whole ORB pipeline can use pixels outside of your submat.
`.clone()` breaks relation between submat and parent mat (pixels outside submat are not used anymore).
So you got different results, because inputs are different.

**Comment by csterg** [comment]
I understand your point, I am not arguing that.
Excuse my ignorance and correct me if I am wrong, yet let me ask:
Aren't mats and submats supposed to be giving the same results throughout the public API? If they don't, is this something expected and if yes should it be documented on those operations that can yield different results?

As a user of OpenCV's API: how am I to guard my code against this? is it by creating clones all the time? If yes, wouldn't that void the whole idea of using submats in the first place?

Thanks for addressing these concerns,
Costas
