### ISSUE TITLE
Error Make OpenCV-4.1.1 on Raspberry Pi 3

### ISSUE THREAD

**Issue by Behnamzaki** [opencv/opencv#15484]
Hi, i get following error when i use

`make -j4`

to make openCV-4.1.1 on Raspberry Pi 3

[ 39%] Built target opencv_tracking_pch_dephelp
[ 39%] Built target opencv_stereo_pch_dephelp
[ 39%] Built target gen_opencv_python_source
[ 40%] Generating precomp.hpp.gch/opencv_core_RELEASE.gch
[ 40%] Built target tegra_hal
/bin/sh: 1: ./precomp.hpp.command.sh: Permission denied
make[2]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:66: modules/core/precomp.hpp.gch/opencv_core_RELEASE.gch] Error 126
make[1]: *** [CMakeFiles/Makefile2:2716: modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Generating precomp.hpp.gch/opencv_flann_RELEASE.gch
/bin/sh: 1: ./precomp.hpp.command.sh: Permission denied
make[2]: *** [modules/flann/CMakeFiles/pch_Generate_opencv_flann.dir/build.make:66: modules/flann/precomp.hpp.gch/opencv_flann_RELEASE.gch] Error 126
make[1]: *** [CMakeFiles/Makefile2:2845: modules/flann/CMakeFiles/pch_Generate_opencv_flann.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
pi@raspberrypi:/media/pi/USBSTORAGE/build $ ^C

any idea?
Thanks.

**Comment by decster** [comment]
./precomp.hpp.command.sh: Permission denied
I got the same error today, the reason is precomp.hpp.command.sh is not executable, possibly because you directory is mounted with noexec option, imply every file on this mount partition is not executable(at least this is my case)

**Comment by alalek** [comment]
try latest master with #15195 or prefer using cross-compilation (Raspberry Pi 3 requires several hours)

**Comment by alalek** [comment]
> precomp.hpp.command.sh: Permission denied

should be fixed.
