### ISSUE TITLE
Include Opencv_contrib modules in opencv.js

### ISSUE THREAD

**Issue by Rakeshvcr** [opencv/opencv#15493]
Is it possible to include opencv contrib modules to opencv .js, please guide me if there is way to include opencv contrib modules in opencv.js.

**Comment by AnastasiiaBorodulina** [comment]
Hei! I am also trying to do the same. Have you found any way to do it?

**Comment by Rakeshvcr** [comment]
I tried similar way of including the functions using this [link](https://github.com/ganwenyao/opencv_js). When I checked in binding.cpp, functions were not included.
