### ISSUE TITLE
Building error with current release version(Ubuntu18.04)

### ISSUE THREAD

**Issue by Hanqer** [opencv/opencv#15497]
##### System information (version)
- OpenCV => current release version
- Operating System / Platform => Ubuntu18.04
- Compiler => make

Firstly, I run cmake with
`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -DUSE_fPIC=1 ..`
And then run make, but got a Linking error when Linking CXX shared library ../../lib/libopencv_imgcodecs.so
/usr/bin/ld: /usr/local/lib/libIlmImf.a(ImfHeader.o): relocation R_X86_64_PC32 against symbol `_ZN7Imf_2_214TypedAttributeIN9Imath_2_23BoxINS1_4Vec2IfEEEEE16makeNewAttributeEv' can not be used when making a shared object; recompile with -fPIC

I don't konw why the compiler try to link libIlmImf.a and I try to use -fPIC flag when using cmake but it don't work.

**Comment by alalek** [comment]
> /usr/local/lib/libIlmImf.a

This file is not from OpenCV (and it is not from Ubuntu system packages).
You need to fix that file on your system first or disable/switch OpenEXR support in OpenCV.
