### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by sparshgarg23** [opencv/opencv#15502]
System Information:
OpenCV>=4.0
Operating System: Ubuntu 16.04
compiler:GCC 5.4.0
Description: While working on a course project that relies  on the yolo3 model to make detections I ran into the following error:
#1 : LOAD IMAGE INTO BUFFER done
terminate called after throwing an instance of 'cv::Exception'
what(): OpenCV(4.1.0) /home/kieranych/SFND/opencv/opencv-4.1.0/modules/dnn/src/darknet/darknet_io.cpp:694: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

Aborted (core dumped)
Steps to reproduce:
1)Clone the following repository: https://github.com/udacity/SFND_3D_Object_Tracking
2)mkdir build & cd build
3)cmake .. & make
4).3D_object_tracking
Further Dependencies:
cmake>=2.8
Git LFS
OpenCV>=4.1
gcc/g++>=5.4

**Comment by sparshgarg23** [comment]
I saw on this link  "https://stackoverflow.com/questions/54785928/opencv-implementation-of-yolo-v3-reproduces-exception-on-a-gcp-instance" that re-downloading the weights may solve the issue but I am not sure.

**Comment by YoungGer** [comment]
same question as you.
If you solved the problem, please tell me what you do.
Thank you.

**Comment by sparshgarg23** [comment]
You need to redownload the weights .Follow the link wget https://pjreddie.com/media/files/yolov3.weights

**Comment by Etragas** [comment]
This worked for me as well, thank you
