### ISSUE TITLE
OpenCV64 project build failed due to Eigen new source code error C2665

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv#15525]
##### System information (version)

- OpenCV =>Newest
- Operating System / Platform => WIN10X64
- Compiler =>VS2017X64

##### Detailed description

opencv_imgproc_AVX512_SKX: 
  D:\Eigen\src\Eigen\src/Core/GenericPacketMath.h(524): error C2665: 'log': none of the 3 overloads could convert all the argument types 
  D:\Eigen\src\Eigen\src/Core/GenericPacketMath.h(537): error C2665: “exp”: none of the 3 overloads could convert all the argument types

**Comment by asmorkalov** [comment]
@dbyoung720 Thanks for the bug report. Could you provide Eigen library version and cmake command line options?

**Comment by dbyoung720** [comment]
It's been too long. I'm not sure if it's still a problem.
Tomorrow, I'm trying to compile it

**Comment by dbyoung720** [comment]
The problem remains.
Source Eigen (https://github.com/eigenteam/eigen-git-mirror.git)
add E:\Source\Eigen to system search path

**Comment by bemol38** [comment]
I'm having the same issue.
**System Information**
 Eigen 3.3.7, OpenCV 4.1.2, Compiler: vc2019 x64, Windows 10 x64

**CMake configuration**

General configuration for OpenCV 4.1.2-dev 

Version control:               4.1.2-209-gad0ab4109a
Platform:
Timestamp:                   2019-11-25T11:59:12Z
Host:                        Windows 10.0.17763 AMD64
    CMake:                       3.15.4
    CMake generator:             Ninja
    CMake build tool:            C:/PROGRA~2/CMake/bin/ninja.exe
    MSVC:                        1923
    Configuration:               Debug
  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSSE3 SSE4_1
      SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (29 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (6 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe  (ver 19.23.28107.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS       /MP8    /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS       /MP8  /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:
    3rdparty dependencies:
  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo stitching ts video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java js python2 python3
    Applications:                tests perf_tests apps
    Documentation:               NO
    Non-free algorithms:         NO
  Windows RT support:            NO
  GUI: 
    Win32 UI:                    YES
    VTK support:                 NO
  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES
  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.54.100)
      avformat:                  YES (58.29.100)
      avutil:                    YES (56.31.100)
      swscale:                   YES (5.5.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES
  Parallel framework:            Concurrency
  Trace:                         YES (with Intel ITT)
  Other third-party libraries:
    Intel IPP:                   2019.0.0 Gold [2019.0.0]
           at:                   C:/opencv-4.1.2/build-Debug/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2019.0.0)
              at:                C:/opencv-4.1.2/build-Debug/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.90)
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)
  OpenCL:                        YES (NVD3D11)
    Include path:                C:/opencv-4.1.2/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load
  Python (for build):            C:/Users/******/AppData/Local/Programs/Python/Python38/python.exe
  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO
  Install to:                    C:/opencv-4.1.2/build-Debug/install


**cl.exe command**

FAILED: modules/core/CMakeFiles/opencv_core.dir/matmul.avx512_skx.cpp.obj 
C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\HostX64\x64\cl.exe  /nologo /TP -DCVAPI_EXPORTS -DOPENCV_WITH_ITT=1 -D_USE_MATH_DEFINES -D_VARIADIC_MAX=10 -D_WIN32_WINNT=0x0601 -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX512_COMMON=1 -DCV_CPU_COMPILE_AVX512_SKX=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_AVX_512F=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_COMPILE_POPCNT=1 -DCV_CPU_COMPILE_SSE4_1=1 -DCV_CPU_COMPILE_SSE4_2=1 -DCV_CPU_COMPILE_SSSE3=1 -DCV_CPU_DISPATCH_MODE=AVX512_SKX -I3rdparty\ippicv\ippicv_win\icv\include -I3rdparty\ippicv\ippicv_win\iw\include -I. -I..\modules\core\src -I..\modules\core\include -Imodules\core -I..\3rdparty\zlib -I3rdparty\zlib -I..\3rdparty\include\opencl\1.2 -I..\3rdparty\ittnotify\include -IC:\eigen-3.3.7\build-vc16\install\include\eigen3 /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MDd /Zi /Ob0 /Od /RTC1         /arch:AVX  /arch:AVX /arch:AVX2 /arch:AVX512 /arch:AVX512 /arch:AVX512 /showIncludes /Fomodules\core\CMakeFiles\opencv_core.dir\matmul.avx512_skx.cpp.obj /Fdlib\opencv_core412d.pdb /FS -c modules\core\matmul.avx512_skx.cpp

**Error message**

C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/GenericPacketMath.h(541): error C2665: 'log': none of the 3 overloads could convert all the argument types
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include\cmath(382): note: could be 'long double log(long double) noexcept'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include\cmath(149): note: or       'float log(float) noexcept'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(480): note: or       'double log(double)'
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/GenericPacketMath.h(541): note: while trying to match the argument list '(const Packet)'
        with
        [
            Packet=Eigen::internal::Packet16f
        ]
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/arch/Default/GenericPacketMathFunctions.h(142): note: see reference to function template instantiation 'Packet Eigen::internal::plog<Packet>(const Packet &)' being compiled
        with
        [
            Packet=Eigen::internal::Packet16f
        ]
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/arch/AVX512/MathFunctions.h(399): note: see reference to function template instantiation 'Packet Eigen::internal::generic_plog1p<Eigen::internal::Packet16f>(const Packet &)' being compiled
        with
        [
            Packet=Eigen::internal::Packet16f
        ]
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/GenericPacketMath.h(533): error C2665: 'exp': none of the 3 overloads could convert all the argument types
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include\cmath(313): note: could be 'long double exp(long double) noexcept'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include\cmath(81): note: or       'float exp(float) noexcept'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(477): note: or       'double exp(double)'
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/GenericPacketMath.h(533): note: while trying to match the argument list '(const Packet)'
        with
        [
            Packet=Eigen::internal::Packet16f
        ]
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/arch/Default/GenericPacketMathFunctions.h(157): note: see reference to function template instantiation 'Packet Eigen::internal::pexp<Packet>(const Packet &)' being compiled
        with
        [
            Packet=Eigen::internal::Packet16f
        ]
C:\eigen-3.3.7\build-vc16\install\include\eigen3\Eigen\src/Core/arch/AVX512/MathFunctions.h(404): note: see reference to function template instantiation 'Packet Eigen::internal::generic_expm1<Eigen::internal::Packet16f>(const Packet &)' being compiled
        with
        [
            Packet=Eigen::internal::Packet16f
        ]

**Comment by karlphillip** [comment]
I'd like to work on this.

**Comment by burak-yildizoz** [comment]
> Source Eigen (https://github.com/eigenteam/eigen-git-mirror.git)

That mirror is last updated 2 years ago. I have successfully build OpenCV 4.5.2 on Windows with the latest Eigen source code ([`91cd67f0`](https://gitlab.com/libeigen/eigen/-/commit/91cd67f057f90101cf858d63916ee56a58511b0d)) from **<https://gitlab.com/libeigen/eigen>**.
