### ISSUE TITLE
Grammar fixes - Python Tutorials

### ISSUE THREAD

**Issue by collinbrake** [opencv/opencv#15524]
While reading the python tutorials, I found some grammar errors that I can fix. These are located in the section on Gui features.

**Comment by mshabunin** [comment]
@collinbrake , feel free to [submit pull request](https://github.com/opencv/opencv/wiki/How_to_contribute) with your fixes. Please use [branch 3.4](https://github.com/opencv/opencv/wiki/Branches) as a target and we will merge fixes to master.
