### ISSUE TITLE
ROI axis rotates implicitly

### ISSUE THREAD

**Issue by chiboreache** [opencv/opencv#15539]
##### System information (version)
- OpenCV => 4.1.1-1
- Operating System / Platform => Arch Linux

##### Detailed description
Can't figuring out why axis of my ROI is flipped and rotated, meanwhile circles drawing by same points - looks like they should

##### Steps to reproduce

```python
image = cv2.imread(image_path)
patch = cv2.imread(patch_path)
region_x, region_y, _ = patch.shape

render_image = image.copy()

with open('fp_render_data.pickle', 'rb') as handle:
    d = pickle.load(handle)
    for i in d['DOORS']['items']:
        for c, k in i.items():

            coord_x, coord_y = k['pt']

            cv2.circle(render_image,
                       (coord_x, coord_y),
                       2, (0, 250, 0), -1)  # ? marker
            cv2.circle(render_image,
                       (coord_x+region_x,
                        coord_y+region_y),
                       2, (250, 0, 0), -1)  # ? marker

            render_image[coord_x:coord_x+region_x,
                         coord_y:coord_y+region_y] = patch

cv2.imshow('render_image', render_image)
```

![image](https://user-images.githubusercontent.com/16459251/65159479-d0f32780-da3c-11e9-9b83-47fd38a55ce3.png)

**Comment by dkurt** [comment]
> render_image[coord_x:coord_x+region_x,
                         coord_y:coord_y+region_y] = patch

Maybe because numpy arrays are row-major?

```
render_image[coord_y:coord_y+region_y,
                         coord_x:coord_x+region_x] = patch
```

**Comment by chiboreache** [comment]
> > render_image[coord_x:coord_x+region_x,
> > coord_y:coord_y+region_y] = patch
> 
> Maybe because numpy arrays are row-major?
> 
> ```
> render_image[coord_y:coord_y+region_y,
>              coord_x:coord_x+region_x] = patch
> ```

yeah, I having the same thoughts, but get `ValueError: could not broadcast input array from shape (38,37,3) into shape (37,38,3)` so now I dig in deeper and realised that I need to also wrap a `region_y, region_x, _ = patch.shape` 

so now all works like a charm, thanks mate!

![Screenshot_20190918_183214](https://user-images.githubusercontent.com/16459251/65162871-a73cff00-da42-11e9-9df1-f43d793af48a.png)
