### ISSUE TITLE
cv2.error: OpenCV(4.1.1) /io/opencv/modules/dnn/src/dnn.cpp:525: error: (-2:Unspecified error) Can't create layer "679" of type "Cast" in function 'getLayerInstance'

### ISSUE THREAD

**Issue by wangpupanjing** [opencv/opencv#15532]
cv2.error: OpenCV(4.1.1) /io/opencv/modules/dnn/src/dnn.cpp:525: error: (-2:Unspecified error) Can't create layer "679" of type "Cast" in function 'getLayerInstance'

**Comment by dkurt** [comment]
Please provide a reproducer.
