### ISSUE TITLE
opencv3.4.3+cuda9.2 or cuda 10.0 or cuda10.1+2080Ti, hang when using SURF_CUDA

### ISSUE THREAD

**Issue by qinzhenguo** [opencv/opencv#15535]
##### System information (version)
- OpenCV  3.4.3
- Operating System / Platform => linux 64 Bit
- CUDA:  9.2 or 10.0 or 10.1 ( I test on 3 CUDA versions...)
- GPU:   2080Ti

##### Detailed description

When using SURF_CUDA to extract surf features from images, the program hangs and nothing is print. At the meantime, the GPU usage is 100%. Don't know why....  I also test GPU ORB extractor and it works fine.( Ptr\<cuda::ORB\> d_orb = cuda::ORB::create(......) ).

##### Steps to reproduce

#include \<iostream\>
#include "opencv2/opencv_modules.hpp"
#include "opencv2/core.hpp"
#include "opencv2/features2d.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/cudafeatures2d.hpp"
#include "opencv2/xfeatures2d/cuda.hpp"

using namespace std;
using namespace cv;
using namespace cv::cuda;

int main(int argc, char* argv[])
{

    GpuMat img1, img2;
	
	img1.upload(imread("test.jpg", IMREAD_GRAYSCALE));
    CV_Assert(!img1.empty());
	
	img2.upload(imread("test.jpg", IMREAD_GRAYSCALE));
    CV_Assert(!img2.empty());

    cv::cuda::printShortCudaDeviceInfo(cv::cuda::getDevice());

    SURF_CUDA surf;

    // detecting keypoints & computing descriptors
    GpuMat keypoints1GPU, keypoints2GPU;
    GpuMat descriptors1GPU, descriptors2GPU;
	cout << "begin surf extracting..." << endl;   // this info is print and then the program hangs..
    surf(img1, GpuMat(), keypoints1GPU, descriptors1GPU);
    surf(img2, GpuMat(), keypoints2GPU, descriptors2GPU);

    cout << "FOUND " << keypoints1GPU.cols << " keypoints on first image" << endl;
    cout << "FOUND " << keypoints2GPU.cols << " keypoints on second image" << endl;

    return 0;
}

Besides, the code works fine on 1080Ti/P100+cuda8.0.

Any information is appreciated. Thanks in advance.

**Comment by M-Roof** [comment]
I seem to be having the same issue with OpenCV3.4.3 and CUDA 10.1. My GPU device is GeForce RTX 2080. My system hangs when trying to run the example stitcher code with cuda (https://docs.opencv.org/3.4.3/d9/dd8/samples_2cpp_2stitching_detailed_8cpp-example.html). I monitor the gpu and it goes to 100% and stays there indefinitely. It seems to occur right after calling:
```
        if (try_cuda && cuda::getCudaEnabledDeviceCount() > 0)
            finder = makePtr<SurfFeaturesFinderGpu>();
```
which leads me to believe it is something with the gpu surf features.

I also tried using this code qinzhenguo posted and I hang in the same spot. I've tried other cuda functions and they seem to work. I would also appreciate any info on this. Thanks.

**Comment by GrainsofSalt** [comment]
Same exact issue as M-Roof. CV3.4.3, CUDA10.1, RTX 2080.. GPU goes crazy and the program just sticks when try_use_gpu is flagged true

**Comment by qinzhenguo** [comment]
> I seem to be having the same issue with OpenCV3.4.3 and CUDA 10.1. My GPU device is GeForce RTX 2080. My system hangs when trying to run the example stitcher code with cuda (https://docs.opencv.org/3.4.3/d9/dd8/samples_2cpp_2stitching_detailed_8cpp-example.html). I monitor the gpu and it goes to 100% and stays there indefinitely. It seems to occur right after calling:
> 
> ```
>         if (try_cuda && cuda::getCudaEnabledDeviceCount() > 0)
>             finder = makePtr<SurfFeaturesFinderGpu>();
> ```
> 
> which leads me to believe it is something with the gpu surf features.
> 
> I also tried using this code qinzhenguo posted and I hang in the same spot. I've tried other cuda functions and they seem to work. I would also appreciate any info on this. Thanks.

Thanks for your attention. Opencv 4.1.1+CUDA 10.1+2080Ti  works.

**Comment by qinzhenguo** [comment]
> Same exact issue as M-Roof. CV3.4.3, CUDA10.1, RTX 2080.. GPU goes crazy and the program just sticks when try_use_gpu is flagged true
> 
> https://docs.opencv.org/3.4.3/d8/d19/tutorial_stitcher.html

Thanks for your attention. Opencv 4.1.1+CUDA 10.1+2080Ti  works for me.

**Comment by qinzhenguo** [comment]
Opencv 4.1.1+CUDA 10.1+2080Ti works.

**Comment by jadehh** [comment]
I have the same questions, Please tell me how to solve this  problem;

**Comment by M-Roof** [comment]
Hi @jadehh I ended up using openCV 4.1.1 like quizhenguo and that worked. I couldn't find a way to make it work without upgrading openCV. Sorry.

**Comment by jadehh** [comment]
Thank you for your reply.

Re: [opencv/opencv] opencv3.4.3+cuda9.2 or cuda 10.0 or cuda10.1+2080Ti, hang when using SURF_CUDA (#15535)


Hi @jadehh<https://github.com/jadehh> I ended up using openCV 4.1.1 like quizhenguo and that worked. I couldn't find a way to make it work without upgrading openCV. Sorry.

―
