### ISSUE TITLE
Opencv is not ready

### ISSUE THREAD

**Issue by cenoyadiweb** [opencv/opencv#15549]
Hi,I developed the app with opencv in Android Studio, now please help me fix this error on installing app in Android:
**"OpenCV is not ready**
Installation is in progress. _wait or exit?"_

i use android 3.5

**Comment by dkurt** [comment]
Try to follow one of the tutorials. In example, https://docs.opencv.org/master/d0/d6c/tutorial_dnn_android.html

At least you may also try this: https://gist.github.com/dkurt/d8dee79eaa8a0275f7cf037d7bc9b5ac
