### ISSUE TITLE
compiling from master jasper.h not found

### ISSUE THREAD

**Issue by tasoss** [opencv/opencv#15543]
Hello i'm compiling from master and i get the following error.
Thanks!
>  [ 63%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpubackend.cpp.o
[ 63%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o
/opt/opencv/modules/imgcodecs/src/grfmt_jpeg2000.cpp:63:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:278: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o' failed
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o] Error 1
CMakeFiles/Makefile2:5196: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by mshabunin** [comment]
Please add more information about your configuration: OpenCV version, OS/platform...
It can be an output of cmake command or the string returned by `cv::getBuildInformation()` (C++ function) or `cv.getBuildInformation()` (Python function).

**Comment by tasoss** [comment]
Of course , my mistake.
I'm using ubuntu 18.04.3.
The error started appearing in the last commits
Right now i have tried to compiled with commit a052567db8be26a09a78b5d51e67e6224e6a6d55
and again i got the same error.

> [ 62%] Built target opencv_line_descriptor
[ 62%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pam.cpp.o
[ 63%] Built target opencv_hfs
/opt/opencv/modules/imgcodecs/src/grfmt_jpeg2000.cpp:63:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
[ 63%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pxm.cpp.o
modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:278: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o' failed
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 63%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_png.cpp.o
[ 63%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pfm.cpp.o
[ 63%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/BING/CmFile.cpp.o
[ 63%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/erfilter.cpp.o
[ 63%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/BING/CmShow.cpp.o
[ 63%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/BING/FilterTIG.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/BING/ValStructVec.cpp.o
CMakeFiles/Makefile2:5196: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/ocr_beamsearch_decoder.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/BING/objectnessBING.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/motionSaliency.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/motionSaliencyBinWangApr2014.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/objectness.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/saliency.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/staticSaliency.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/staticSaliencyFineGrained.cpp.o
[ 64%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency.dir/src/staticSaliencySpectralResidual.cpp.o
[ 64%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/ocr_hmm_decoder.cpp.o
[ 64%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/ocr_holistic.cpp.o
[ 64%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/ocr_tesseract.cpp.o
[ 64%] Linking CXX shared library ../../lib/libopencv_saliency.so
[ 64%] Built target opencv_saliency
[ 64%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/text_detectorCNN.cpp.o
[ 64%] Linking CXX shared library ../../lib/libopencv_text.so
[ 64%] Built target opencv_text
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mshabunin** [comment]
Please attach your cmake configuration output.

**Comment by tasoss** [comment]
Sorry for the delay but i didn't receive a notification.
Here is the output https://pastebin.com/6Tzd0J3Z
Thanks!

**Comment by alalek** [comment]
> Ubuntu 18.04.3
> jasper

This package has been dropped from Ubuntu repository (not available anymore in 18.04).
It is hard to guess how this library was installed in your system and which version is used.

Workaround: disable using of Jasper library by OpenCV on your system (`cmake -DWITH_JASPER=OFF ...`).

---

> output

You should clean CMake cache first. Useful things are just missing from provided output (due CMake cache).

**Comment by tasoss** [comment]
Hello and thanks for replying @alalek .
Indeed after installing jasper everything is ok.
I'm sorry.
Thanks for the cache tip btw!
