### ISSUE TITLE
Android Opencv VideoCapture property all return 0

### ISSUE THREAD

**Issue by Jessespace** [opencv/opencv#15547]
CAP_PROP_FRAME_COUNT & 
CAP_PROP_FRAME_WIDTH & 
CAP_PROP_FRAME_HEIGHT &
CAP_PROP_FPS 
all return 0

Android Opencv : 4.1.0
Is't a bug? please fix it.

**Comment by Jessespace** [comment]
Any solution?

**Comment by OgulcanCelik** [comment]
@alalek hey, did you find any solution for this?

**Comment by alalek** [comment]
duplicate of #11952

**Comment by Penguinang** [comment]
> duplicate of #11952

it seems not equal to this problem? In my demo, I opened a local mp4 file and tried to get propertities(Frame_Count, FPS, POS_MSEC), got zero for all, except for WIDTH, HEIGHT. By the way, this problem was also only on android backend(MediaNDK). Does not MediaNDK backend support these propertities?

**Comment by Penguinang** [comment]
alright, it seems media ndk backend supports only width and height , here is source code https://github.com/opencv/opencv/blob/4.5.0/modules/videoio/src/cap_android_mediandk.cpp#L150
