### ISSUE TITLE
Android Opencv VideoCapture property return 0

### ISSUE THREAD

**Issue by Jessespace** [opencv/opencv#15546]
CAP_PROP_FRAME_WIDTH &
CAP_PROP_FRAME_HEIGHT &
CAP_PROP_FRAME_FRAMECOUNT &
CAP_PROP_FPS
all return 0

Android opencv：4.1.0

**Comment by asmorkalov** [comment]
The mentioned properies are available if `cv::VideoCapture` is configured and opened properly, otherwise 0 is returned.

*NOTE*: Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
