### ISSUE TITLE
High cpu usage when read frame from CSI camera

### ISSUE THREAD

**Issue by refigh** [opencv/opencv#15545]
Hi,
on my Raspberry Pi 4 with its CSI camera module (OV5647 lens), I tested two ways of reading frame from camera:
1- from command line with 
   `$ raspivid  -fps 30 -t 0 -w 640 -h 480`
or  alternatively with 
   `$ dd if=/dev/video0 of=~/video.h264 bs=1M & pid=$! ; sleep 20; kill $pid`
2- with python/opencv code and an infinite loop:
```
...
vs = cv2.VideoCapture(0)
vs.set(cv2.CAP_PROP_FRAME_WIDTH, 640) 
vs.set(cv2.CAP_PROP_FRAME_HEIGHT, 480) 
while(True): 
	ret, frame = vs.read()  
 	cv2.imshow('video', frame)
```

while in first case, cpu usage is close to 0%, in second case it is considerable, around 10%-20% on all 4 cores.  I did a new test with another simple USB camera.  1- with "cheese" app, and 2-again with python. this time both have high cpu usage.

what can be explanation for this? is this related to internal GPU/encoder/decode module of Raspberry SoC, which cannot be used by some of apps, including python/openCV?

**Comment by refigh** [comment]
I did more tests on  Raspberry pi 4:
-read rtsp video stream with VLC,
-read rtsp video stream in python-OpenCV 4.1.1
-read and play CSI camera module with python-picamera library

Finally I concluded that Python-openCV does not use Raspberry pi 4's internal CPU/encoder/decoders
but python-picamera library, and VLC both use it.

**Comment by alalek** [comment]
Actually you trying to measure "something":
- perf1: reading/decoding of frame data
- perf2: showing captured frame
- did you limit/count FPS? If there are no delays, then 100% CPU load is expected.

> does not use Raspberry pi 4's internal GPU/video encoder/video decoder

No such code in OpenCV directly (and no plans to add that - OpenCV relys on other Media I/O libraries).
You can try to use GStreamer backend (with properly configured pipeline and RPi's GStreamer plugins).

**Comment by refigh** [comment]
Yes, I limited the FPS. 
Using uniform opencv function interface for all kinds of cameras is very desirable (or at least for some famous ones). Instead of using libraries like "picamera", it is good if opencv handles it internally, and gives user common interface functions.
Exactly like what opencv currently doing for different types of dnn models, and dnn processing platform ('MYRIAD' or 'CPU' or 'FPGA', and reset is same).
