### ISSUE TITLE
cd::VideoCapture is always less a frame than get(7)

### ISSUE THREAD

**Issue by Dauber01** [opencv/opencv#15569]
the picture number of cd::VideoCapture get is always less a frame than cv2.VideoCapture().get7()，idon't know what happend in this ,i used the version 4.X

**Comment by mshabunin** [comment]
Please add more information about your configuration: OpenCV version, OS/platform...
It can be an output of cmake command or the string returned by `cv::getBuildInformation()` (C++ function) or `cv.getBuildInformation()` (Python function).

Add a small reproducer application.

**Comment by Dauber01** [comment]
OpenCV version 4.1.1,OS ,cenos7.3 ,here is the code
            if vc.isOpened():  # 判断是否正常打开

                rval, frame = vc.read()
            else:
                rval = False
                app.logger.info('sorry, the file can,t be open')

            while rval:  # 循环读取视频帧
                if (c == 1) | (c == int(count / 2)) | (c == count - 1):
                    frame = cv2.resize(frame, (900, 800))
                    cv2.imwrite('/home/video/' + filename[0:-4] + '-' + str(c) + '.jpg', frame)

                rval, frame = vc.read()
                c = c + 1  # 用于计数和选择具体帧数
                app.logger.info(c)
                #cv2.waitKey(3)
            #要将文件释放掉，以便之后可以进行删除
            vc.release()
i have try for sometime ,for many video it can be common and for others the problem would appear ,didi the video file has some require?

**Comment by mshabunin** [comment]
There is no `vc.get(...)` calls in your code.

**Comment by Dauber01** [comment]
ofcourse it have, sorry i forget to cut it in the picture
            vc = cv2.VideoCapture(app.config['UPLOAD_FOLDER'] + os.sep + filename)  # 读取视频文件
            c = 1

            count = vc.get(7)
            app.logger.info(count)
            if vc.isOpened():  # 判断是否正常打开

                rval, frame = vc.read()
            else:
                rval = False
                app.logger.info('sorry, the file can,t be open')

            while rval:  # 循环读取视频帧
                if (c == 1) | (c == int(count / 2)) | (c == count - 1):
                    frame = cv2.resize(frame, (900, 800))
                    cv2.imwrite('/home/video/' + filename[0:-4] + '-' + str(c) + '.jpg', frame)

                rval, frame = vc.read()
                c = c + 1  # 用于计数和选择具体帧数
                app.logger.info(c)
                #cv2.waitKey(3)
            #要将文件释放掉，以便之后可以进行删除
            vc.release()
            app.logger.info(c)
just like this

**Comment by Dauber01** [comment]
for some video file, you know the number of picture i write in dir, is always less one than the number i get by the method vc.get(7)

**Comment by mshabunin** [comment]
This seems like a limitation of FFmpeg library (assuming you use FFmpeg backend), see https://stackoverflow.com/questions/48997930/why-does-ffmpeg-return-a-different-framecount-than-ffprobe-for-the-same-file

Try to use different capture backend, e.g. GStreamer:  https://docs.opencv.org/master/d8/dfe/classcv_1_1VideoCapture.html#ac4107fb146a762454a8a87715d9b7c96 (apiPreference)

**Comment by Dauber01** [comment]
i almost know what you mean ,and have read the two page you share ,but istill can't find how to use the opencv get accurate number of frame ,i have find how to use the  capture backend of ffprobe in the api

**Comment by Dauber01** [comment]
have't find
