### ISSUE TITLE
TypeError: Expected cv::UMat for argument 'img'

### ISSUE THREAD

**Issue by insung3511** [opencv/opencv#15563]
Hi, I made openCV Take Picture Function. But maybe it has something problem...
Anybody help me plz.... 😭 

This is my function code..
<pre>
def takePicture(name, route):
	cap = cv2.VideoCapture(0)
	cv2.imwrite(name, route)
	print("[INFO] Saved in {} ...".format(route))	
	returnValue = name + route
	return returnValue
</pre>

and this is error.
<pre>Traceback (most recent call last):
  File "testLive.py", line 49, in <module>
    imageRoute = takePicture('testOne.jpg', '/Users/Bahk_InSung/Github/yolo-human/testImages/')
  File "testLive.py", line 14, in takePicture
    cv2.imwrite(name, route)
TypeError: Expected cv::UMat for argument 'img'
</pre>

> OpenCV Version : 4.1.0
> Computer : Macbook Pro 13inch, 2015 early (OS X 10.14.6)
> Python 3.7

Thank you 😄

**Comment by asmorkalov** [comment]
*NOTE*: Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
