### ISSUE TITLE
Cannot load info library for OpenCV

### ISSUE THREAD

**Issue by hasanAjsf** [opencv/opencv#15567]
With OpenCV 4.1.1 for Android, I got the below error:
```bash
E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
```

![Screen Shot 2019-09-22 at 6 28 05 PM](https://user-images.githubusercontent.com/46838626/65390419-314cd680-dd67-11e9-90c8-832a78201b51.png)

**Comment by alalek** [comment]
Ignore this error message.
"Info library" is used for special Android configurations, like builds with CUDA support.

**Comment by gitam2869** [comment]
i also face same problem.

**Comment by drriguz** [comment]
same problem, which causes `OpenCVLoader.initDebug()` fail.

**Comment by shreyas29** [comment]
I am also facing the same issue in static initalization of OpenCV library in Android.
I created opencv 4.4.0 android AAR using build_sdk.py script with modules list core,imgproc,imgcodecs and java.

**Comment by shreyas29** [comment]
> I am also facing the same issue in static initalization of OpenCV library in Android.
> I created opencv 4.4.0 android AAR using build_sdk.py script with modules list core,imgproc,imgcodecs and java.

This link seems useful.
https://zen.yandex.ru/media/id/5cafa05b0a588d00b0a57bad/pishem-prosteishee-prilojenie-pod-android-dlia-raspoznavaniia-obektov-s-kamery-5e624bfa824a2d437a810a71

**Comment by RandGor** [comment]
> I am also facing the same issue in static initalization of OpenCV library in Android.
> I created opencv 4.4.0 android AAR using build_sdk.py script with modules list core,imgproc,imgcodecs and java.

Okay, but had you solve this issue? Or maybe these messages were not important?

**Comment by Opmdsq** [comment]
console print : E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
but it can work

**Comment by sensbo** [comment]
> console print : E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
> but it can work

Could we ignore this error? Unfortunately, I couldn't load any example project without an immediately crash of the app by calling  `OpenCVLoader.initDebug() `. I hoped the error has a connection to this error....

**Comment by namhkoh** [comment]
Has anyone managed to work around this error?

**Comment by alexanderconner** [comment]
Any updates with this? I am also experiencing this error when attempting to run OpenCVLoader.initDebug() with the quickbirdstudios/opencv-android dependency.

**Comment by shreyas29** [comment]
I am using com.quickbirdstudios:opencv:4.5.3.0 and not facing this issue.

**Comment by alexanderconner** [comment]
> I am using com.quickbirdstudios:opencv:4.5.3.0 and not facing this issue.

Interesting. I am (attempting) to use the same one. Did you still need to manually import the source code as a module dependency in your project? The setup steps for that repo claims you can simply add the Gradle dependency in the build file and it should work, yet I am not able to initialize OpenCV.

**Comment by RandGor** [comment]
After one year of researches I can tell you what: this message is not the error. This is one useless message from opencv. You should better ignore it.

**Comment by alexanderconner** [comment]
Ahh figured it out. I had a conflict with this dependency and the source module in my Gradle build file. With the  com.quickbirdstudios:opencv import you do not need to manually import the Open CV source code.

**Comment by asmorkalov** [comment]
opencv_info and related logic was removed in https://github.com/opencv/opencv/pull/24640.
