### ISSUE TITLE
Read ir model from buffer not implemented

### ISSUE THREAD

**Issue by marcellBan** [opencv/opencv#15578]
- OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit / Ubuntu 18.04 LTS
- Compiler => Visual Studio 2017 / clang6.0

We are trying to load an IR model from a memory buffer (loaded from a single binary file, not relevant) but `dnn::readNet()` for dldt from buffer is not implemented.

```cpp
 else if (framework == "dldt")
        CV_Error(Error::StsNotImplemented, "Reading Intel's Model Optimizer models from buffers");
```

My colleague is already working on submitting a pull request to implement this.

**Comment by dkurt** [comment]
Hi, @marcellBan. Any progress on this?

**Comment by marcellBan** [comment]
Hi, @dkurt. Sorry for the silence, life decided to throw some obstacles at us. We are testing an reviewing the code and will be submitting it during the week.
