### ISSUE TITLE
Unresolved reference rgba()

### ISSUE THREAD

**Issue by hajsf** [opencv/opencv#15589]
In all the tutorials I read, for using `OpenCV4 Camera` in `Android` app, it is mentioned that:
```kotlin
    override fun onCameraFrame(inputFrame: CameraBridgeViewBase.CvCameraViewFrame): Mat {
        // retrieve the frame from `inputFrame`
        // - the grayscale frame by imputFrame.gray()
        // - the RGBA frame by inputFrame.rgba()

        return inputFrame.rgba() // will show in the UI
    }
```

I tried both `imputFrame.gray()` and `inputFrame.rgba()` but got the same error for both cases:
```bash
Unresolved reference rgba()
```

If I tried to use `return inputFrame` only, I get black screen.

I also tried the below, but still getting black screen:
```kotlin
import org.opencv.android.CameraBridgeViewBase
import org.opencv.core.CvType.CV_8U
import org.opencv.core.Mat
import org.opencv.imgproc.Imgproc


class OpenCVCListner(context: Context) : CameraBridgeViewBase.CvCameraViewListener {
    private var mRgba: Mat? = null
    private var mGray: Mat? = null
    override fun onCameraViewStarted(width: Int, height: Int) {
        mGray = Mat()
        mRgba = Mat()
    }

    override fun onCameraViewStopped() {

    }

    override fun onCameraFrame(inputFrame: Mat?): Mat {
        inputFrame!!.convertTo(mRgba, CV_8U, 1.0, 0.0)
        Imgproc.cvtColor(mRgba, mGray, Imgproc.COLOR_BGRA2GRAY)
        return mGray!!
    }
}
```

**Comment by alalek** [comment]
OpenCV Android samples is here: https://github.com/opencv/opencv/tree/master/samples/android

**Comment by hajsf** [comment]
@alalek  I tried to replicate the one in [this](https://github.com/opencv/opencv/blob/master/samples/android/tutorial-1-camerapreview/src/org/opencv/samples/tutorial1/Tutorial1Activity.java) example, and it is showing the same `return inputFrame.rgba()` which failed with me!
