### ISSUE TITLE
How to use dnn module with opencl

### ISSUE THREAD

**Issue by bixiaopeng0** [opencv/opencv#15586]
I set the parameter is:
	net.setPreferableBackend(DNN_BACKEND_OPENCV);       //启动GPU加速
	net.setPreferableTarget(DNN_TARGET_OPENCL);         //启动GPU加速
but error happen:
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

What should I do?

**Comment by dkurt** [comment]
Please follow issues template and specify you hardware and OS.

**Comment by bixiaopeng0** [comment]
hardware is i5-4590cpu,gpu is 1050ti and os is win10

**Comment by amswly** [comment]
hey,I got the same error,but my program ran ok.Yet,it took 20+s to detect a pic.So do you get any solution to solve this problem?

OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\ADMINI~1\AppData\Local\Temp\opencv\3.4.x\opencl_cache\
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_750_Ti--430_64
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

**Comment by YashasSamaga** [comment]
@amswly The OpenCL backend won't perform well on NVIDIA GPUs presumably due to the costly memory transfers involved when the fallbacks are used. I have also [observed this performance issue](https://github.com/opencv/opencv/pull/14827#issuecomment-522229894). You might be interested in PR #14827 which adds a CUDA backend to the DNN module.

**Comment by bixiaopeng0** [comment]
emmm,sorry I don't konw.I will tell you if I solve the question

At 2019-09-25 17:12:14, "amswly" <notifications@github.com> wrote:


hey,I got the same error,but my program ran ok.Yet,it took 20+s to detect a pic.So do you get any solution to solve this problem?

OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
via OPENCV_OCL4DNN_CONFIG_PATH parameter.
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\ADMINI~1\AppData\Local\Temp\opencv\3.4.x\opencl_cache
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_750_Ti--430_64
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

**Comment by GTMHS** [comment]
你这个问题解决了么，我也遇到了类似的问题 
`OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
via OPENCV_OCL4DNN_CONFIG_PATH parameter.`
然后我设置了OPENCV_OCL4DNN_CONFIG_PATH 这个的环境变量，他不提示错误了，但是运行的超级慢，第一张图片检测运行了319秒，其他的1.6s左右，比CPU（1.2s）还要慢，而且还不稳定
我的GPU是Inteld的集显Intel(R) HD Graphics 530
参考：https://github.com/opencv/opencv/issues/12155#issuecomment-418036136
![)8XEH UR%5}DPQI1JFM9GUN](https://user-images.githubusercontent.com/20610228/66709693-066d0580-ed9c-11e9-847c-810d98fd06d9.png)

**Comment by Max-Worker** [comment]
I have the same problem, and I don't have a clue yet，
The parameters I set are:
```
self.net = cv2.dnn.readNetFromDarknet(modelCfg, modelWeights)
self.net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
# self.net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
self.net.setPreferableTarget(cv2.dnn.DNN_TARGET_OPENCL)
# self.net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
```
