### ISSUE TITLE
Issue setting Blender and FeaturesFinder

### ISSUE THREAD

**Issue by yakirs57** [opencv/opencv#15588]
I'm trying to define the stitcher to my own need, setting the blender type and featuresFinder type as shown in the documentation, yet I'm unable to perform **stitcher.setBlender(<Blender>)**
becuase it returns:
**AttributeError: 'cv2.Stitcher' object has no attribute 'setBlender'**

Someone has an idea of how to solve it?

**Comment by asmorkalov** [comment]
OpenCV is C++ library and Python bindings for OpenCV is wrapper on top of C++ code to use it in Python code. methods like `setBlender` have C++ specific code and cannot be wrapped to Python automatically and are not available in Python.

*NOTE*: Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
