### ISSUE TITLE
How to use dnn with opencl

### ISSUE THREAD

**Issue by bixiaopeng0** [opencv/opencv#15587]
System information (version)
OpenCV => 4.10
Operating System / Platform => Windows10 64 Bit
Compiler => Visual Studio 2015
Detailed description
I ues the C++ version of the code which is based on OpenCV4.0/dnn/object_detection.cpp to make a prediction with yolov3 model .when I choose the DNN_TARGET_OPENCL as for net.setPreferableTarget( ) parameter. and I get the error like this:
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

However,the code run fine with the choose of DNN_TARGET_CPU

Steps to reproduce
here is part of my code:
	Net net = readNetFromDarknet(yolo_cfg, yolo_model);
	//net.setPreferableBackend(DNN_BACKEND_OPENCV);
	//net.setPreferableTarget(DNN_TARGET_CPU);
	net.setPreferableBackend(DNN_BACKEND_OPENCV);       //启动GPU加速
	net.setPreferableTarget(DNN_TARGET_OPENCL);         //启动GPU加速

**Comment by alalek** [comment]
Please stop spamming.
Answer for your question is already here (use searching first).

For NVIDIA GPUs you should take a look on this GSoC project: #14827
