### ISSUE TITLE
imgproc: calcHist generates miss counts pixel in release mode

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#15597]
##### System information (version)

- OpenCV => recent 3.4 ( c2096771cb705097d2203146838bf4ff71a9c774 )
- Operating System / Platform => Jetson Xavier, Jetson TX1, Jetson TX2, Jetson Nano, Firefly RK3399, ODROID-N2 (All Aarch64)
- Compiler => GCC 7.4.0

##### Abstract
- Another rounding error causes missing count in histogram
- This leads to test failure in xphoto module

##### Detailed description

The original issue comes from `opencv_test_xphoto` which is contrib module.

```
$ ./build/bin/opencv_test_xphoto --gtest_filter=*float_min_value
CTEST_FULL_OUTPUT
OpenCV version: 3.4.8-pre
OpenCV VCS version: 3.4.7-189-gc209677
Build type: Release
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = *float_min_value
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from xphoto_simplecolorbalance
[ RUN      ] xphoto_simplecolorbalance.float_min_value
/home/nvidia/opencv_contrib/modules/xphoto/test/simple_color_balance.cpp:197: Failure
The difference between minDst and newMin is 65468.87890625, which exceeds 65536*1e-4, where
minDst evaluates to -65468.87890625,
newMin evaluates to 0, and
65536*1e-4 evaluates to 6.5536000000000003.
[  FAILED  ] xphoto_simplecolorbalance.float_min_value (1 ms)
[----------] 1 test from xphoto_simplecolorbalance (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] xphoto_simplecolorbalance.float_min_value

 1 FAILED TEST
```
Not only `float_min_value` but total 3 tests fail.

```
[==========] 15 tests from 4 test cases ran. (1171 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] xphoto_simplecolorbalance.float_min_value
[  FAILED  ] xphoto_simplecolorbalance.float_p
[  FAILED  ] xphoto_simplecolorbalance.float_c3
```

##### Steps to reproduce

These tests were added by opencv/opencv_contrib#2263
opencv/opencv_contrib#2263 also [modified balanceWhiteSimple to use calcHist](https://github.com/opencv/opencv_contrib/pull/2263/files#diff-4865499a75d5cb18c0afb5d1bf869124R92) 

In [calcHist](https://github.com/opencv/opencv/blob/c2096771cb705097d2203146838bf4ff71a9c774/modules/imgproc/src/histogram.cpp#L862), it's computing the bin number [here](https://github.com/opencv/opencv/blob/c2096771cb705097d2203146838bf4ff71a9c774/modules/imgproc/src/histogram.cpp#L251)
https://github.com/opencv/opencv/blob/c2096771cb705097d2203146838bf4ff71a9c774/modules/imgproc/src/histogram.cpp#L251-L253

In Release mode + Aarch64, this `multiply and add` operations are tend to be compiled as `fmadd` instruction

```
fmadd  d0, d2, d0, d1
```

And this `fmadd` causes digit loss when the result becomes near to zero.
Following text shows that `*p0*a+b` is supposed to become 0.

```
(gdb) p  *p0
$22 = 24000
(gdb) p a
$23 = 0.098610877049377668
(gdb) p b
$24 = -2366.6610491850643
(gdb) p *p0*a+b
$25 = 0
```

when the actual computation result becomes negative, not 0.

```
(gdb) p value
$20 = -2.2115642650533118e-13
```

Since we are doing `cvFloor` on negative value, the result becomes `-1` and it won't pass the following `if` condition
https://github.com/opencv/opencv/blob/c2096771cb705097d2203146838bf4ff71a9c774/modules/imgproc/src/histogram.cpp#L252-L253
This will lead to missing count of pixel.
The cause is same as #6536 , it's another headache rounding error.

Now, my best solution I can imagine is to apply `round-to-zero` instead of `cvFloor` inside `calcHist`
Another solution is to modify the parameter of `xphoto` so the test passes.
I just like to know which way to fix this issue, or if there are any already implemented `round-to-zero` function in OpenCV (AFAIK, there are only cvFloor, cvRuond and cvCeil).

**Comment by mshabunin** [comment]
@tomoaki0705 , can we use `saturate_cast<unsigned>`?

**Comment by tomoaki0705** [comment]
I'll have a try.  Quick try ended up with test failure of imgproc.
I need to check carefully.

**Comment by tomoaki0705** [comment]
I'm still in the middle of debug.
Basically, 3 tests fail if I use `saturate_cast<unsigned>` in `calcHist`
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Imgproc_Hist_Calc.accuracy
[  FAILED  ] Imgproc_Hist_CalcBackProject.accuracy
[  FAILED  ] Imgproc_Hist_CalcBackProjectPatch.accuracy
```
These tests pass if I use `cvFloor` instead of `saturate_cast`.  I'm still in the middle of this debug.

Also, I implemented `CV_ROUND_TO_ZERO` using macro
```
#define CV_ROUND_TO_ZERO(v) ((v) < 0 ? cvCeil(v) : cvFloor(v))
```
Now, this macro and `saturate_cast` shows different behavior.
Biggest difference is that the tests from `opencv_test_xphoto` fail with `saturate_cast` but pass with `CV_ROUND_TO_ZERO`.

In either implementation, test from `opencv_test_imgproc` still fails, so I'll keep on debugging.

|implementation|test_imgproc|test_xphoto|
|--|--|--|
|`cvFloor`|PASS|FAIL|
|`saturate_cast`|FAIL|FAIL|
|`CV_ROUND_TO_ZERO`|FAIL|PASS|

**Comment by mshabunin** [comment]
@tomoaki0705 , I tried to use safe_cast for each conversion in `calcHist_`:
```.cpp
template <typename D, typename S>
inline D safe_int_cast(S val, const char * msg = 0)
{
    typedef std::numeric_limits<S> st;
    typedef std::numeric_limits<D> dt;
    CV_StaticAssert(st::is_integer && dt::is_integer, "Integer type is expected");
    const bool in_range_r = (double)val <= (double)dt::max();
    const bool in_range_l = (double)val >= (double)dt::min();
    if (!in_range_r || !in_range_l)
    {
        if (!msg)
            CV_Error_(Error::StsOutOfRange, ("Can not convert integer values (%s -> %s), value 0x%jx is out of range", typeid(S).name(), typeid(D).name(), (uintmax_t)val));
        else
            CV_Error(Error::StsOutOfRange, msg);
    }
    return static_cast<D>(val);
}
```
And got exceptions:
```
[ RUN      ] Imgproc_Hist_Calc.accuracy                        
../opencv/modules/ts/src/ts.cpp:590: Failure                            
Failed                                         
                                                  
        failure reason: cvError invoked             
        test case #5                                         
        seed: 980559c14fbc8958                                  
-----------------------------------            
        LOG:                                  
OpenCV Error:                                                     
        One of the arguments' values is out of range (Can not convert integer values (i -> j), value 0xfffffffffffffff
f is out of range) in safe_int_cast, file /opencv/modules/imgproc/src/histogram.cpp, lin
e 228                                                
OpenCV Error:                                              
        One of the arguments' values is out of range (Can not convert integer values (i -> j), value 0xfffffffffffffff
f is out of range) in safe_int_cast, file /opencv/modules/imgproc/src/histogram.cpp, lin
e 228                                                                              
                                                          
-----------------------------------                                               
        CONSOLE: ...                                     
-----------------------------------                             
                  
[  FAILED  ] Imgproc_Hist_Calc.accuracy (1 ms) 
```
Perhaps in some cases the index is `-1` and pixels got missing from the histogram. Tests compare results with reference implementation (written in C) which can be incorrect.

**Comment by alalek** [comment]
@tomoaki0705 Could you take a look on #15642 ?

**Comment by tomoaki0705** [comment]
@alalek Thank you very much for the fix.
I've confirmed that #15642 works.

 - result of `opencv_test_xphoto` before (failed)

```
CTEST_FULL_OUTPUT
OpenCV version: 3.4.8-pre
OpenCV VCS version: 3.4.7-217-ga105f56957
Build type: Release
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 20 tests from 6 test cases.

[==========] 20 tests from 6 test cases ran. (17857 ms total)
[  PASSED  ] 17 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] xphoto_simplecolorbalance.float_min_value
[  FAILED  ] xphoto_simplecolorbalance.float_p
[  FAILED  ] xphoto_simplecolorbalance.float_c3

 3 FAILED TESTS
```

 - result of `opencv_test_xphoto` after (passed)

```
CTEST_FULL_OUTPUT
OpenCV version: 3.4.8-pre
OpenCV VCS version: 3.4.7-218-gf301f17b61
Build type: Release
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 20 tests from 6 test cases.

[==========] 20 tests from 6 test cases ran. (18157 ms total)
[  PASSED  ] 20 tests.
```

- result of `opencv_test_imgproc` before (passed)


```
CTEST_FULL_OUTPUT
OpenCV version: 3.4.8-pre
OpenCV VCS version: 3.4.7-217-ga105f56957
Build type: Release
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 9944 tests from 194 test cases.

[==========] 9944 tests from 194 test cases ran. (207160 ms total)
[  PASSED  ] 9944 tests.
```

- result of `opencv_test_imgproc` after (still passed)

```
CTEST_FULL_OUTPUT
OpenCV version: 3.4.8-pre
OpenCV VCS version: 3.4.7-218-gf301f17b61
Build type: Release
Compiler: /usr/bin/c++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: NEON FP16
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 9944 tests from 194 test cases.

[==========] 9944 tests from 194 test cases ran. (206620 ms total)
[  PASSED  ] 9944 tests.
```

I've confirmed on all of my Aarch64 boards.
