### ISSUE TITLE
ERROR in Ubuntu 18.04

### ISSUE THREAD

**Issue by guilombardi91** [opencv/opencv#15594]
Hi guys, I'm new here. I can not proceed with the installation on linux ubuntu 18.04 LTS ....
After the step

cmake -DCMAKE_BUILD_TYPE=Release ..

I got this in errorlog

Determining if the include file io.h exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9a62c/fast"
/usr/bin/make -f CMakeFiles/cmTC_9a62c.dir/build.make CMakeFiles/cmTC_9a62c.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9a62c.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections  -O3 -DNDEBUG   -o CMakeFiles/cmTC_9a62c.dir/CheckIncludeFile.c.o   -c /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: io.h: No such file or directory
 #include <io.h>
          ^~~~~~
compilation terminated.
CMakeFiles/cmTC_9a62c.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_9a62c.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_9a62c.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9a62c/fast' failed
make: *** [cmTC_9a62c/fast] Error 2

Determining if the function jbg_newlen exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c20c7/fast"
/usr/bin/make -f CMakeFiles/cmTC_c20c7.dir/build.make CMakeFiles/cmTC_c20c7.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c20c7.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -DCHECK_FUNCTION_EXISTS=jbg_newlen -O3 -DNDEBUG   -o CMakeFiles/cmTC_c20c7.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_c20c7
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c20c7.dir/link.txt --verbose=1
/usr/bin/cc    -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -DCHECK_FUNCTION_EXISTS=jbg_newlen -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_c20c7.dir/CheckFunctionExists.c.o  -o cmTC_c20c7 
CMakeFiles/cmTC_c20c7.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text.startup.main+0xc): undefined reference to `jbg_newlen'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c20c7.dir/build.make:97: recipe for target 'cmTC_c20c7' failed
make[1]: *** [cmTC_c20c7] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c20c7/fast' failed
make: *** [cmTC_c20c7/fast] Error 2

Determining if the include file linux/videodev.h exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_af3e0/fast"
/usr/bin/make -f CMakeFiles/cmTC_af3e0.dir/build.make CMakeFiles/cmTC_af3e0.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_af3e0.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections  -O3 -DNDEBUG   -o CMakeFiles/cmTC_af3e0.dir/CheckIncludeFile.c.o   -c /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: linux/videodev.h: No such file or directory
 #include <linux/videodev.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_af3e0.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_af3e0.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_af3e0.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_af3e0/fast' failed
make: *** [cmTC_af3e0/fast] Error 2

Determining if the include file sys/videoio.h exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a3602/fast"
/usr/bin/make -f CMakeFiles/cmTC_a3602.dir/build.make CMakeFiles/cmTC_a3602.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a3602.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections  -O3 -DNDEBUG   -o CMakeFiles/cmTC_a3602.dir/CheckIncludeFile.c.o   -c /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/videoio.h: No such file or directory
 #include <sys/videoio.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_a3602.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a3602.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_a3602.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a3602/fast' failed
make: *** [cmTC_a3602/fast] Error 2

Determining if the include file libavformat/avformat.h exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_758ba/fast"
/usr/bin/make -f CMakeFiles/cmTC_758ba.dir/build.make CMakeFiles/cmTC_758ba.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_758ba.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections  -O3 -DNDEBUG   -o CMakeFiles/cmTC_758ba.dir/CheckIncludeFile.c.o   -c /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: libavformat/avformat.h: No such file or directory
 #include <libavformat/avformat.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_758ba.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_758ba.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_758ba.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_758ba/fast' failed
make: *** [cmTC_758ba/fast] Error 2

Determining if the include file ffmpeg/avformat.h exists failed with the following output:
Change Dir: /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_76e9e/fast"
/usr/bin/make -f CMakeFiles/cmTC_76e9e.dir/build.make CMakeFiles/cmTC_76e9e.dir/build
make[1]: Entering directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_76e9e.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections  -O3 -DNDEBUG   -o CMakeFiles/cmTC_76e9e.dir/CheckIncludeFile.c.o   -c /home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: ffmpeg/avformat.h: No such file or directory
 #include <ffmpeg/avformat.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_76e9e.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_76e9e.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_76e9e.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/server/Downloads/opencv-2.4.11/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_76e9e/fast' failed
make: *** [cmTC_76e9e/fast] Error 2

**Comment by mathuse** [comment]
i want to know it too

**Comment by alalek** [comment]
Failed CMake **checks** are NOT errors.
