### ISSUE TITLE
OpenCV looking for png.h in wrong location when overriding PNG_PNG_INCLUDE_DIR

### ISSUE THREAD

**Issue by Legends0** [opencv/opencv#15605]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => CentOS 7.7
- Compiler => GCC 9.2.0

##### Detailed description

Using libpng 1.6.37 built from http://www.libpng.org/pub/png/libpng.html. This build does not create a symlink of libpng16 to libpng, but does make symlinks of libpng16/png.h to png.h.

CMake variable, PNG_PNG_INCLUDE_DIR, is set to png/include. OpenCV tacks on libpng/png.h to the variable given leading to problem.

-- Found PNG: png/lib/libpng.so
-- Looking for png/include/libpng/png.h
-- Looking for png/include/libpng/png.h - not found

Ref: conda-forge/opencv-feedstock#127

**Comment by alalek** [comment]
Use absolute path if override some settings.

**Comment by Legends0** [comment]
I made a typo in what opencv added to the path. Meant to type libpng/png.h instead of include/png.h.

There are two parts in opencv that would need to be corrected as one file references libpng/png.h and cmake file is setup to append libpng/png.h to the include path when png library is specified.

**Comment by alalek** [comment]
What is the real problem?

OpenCV supports both variants for libpng (of different installation layouts):
- `#include <libpng/png.h>`
- `#include <libpng.h>`

This is just a CMake configuration check (`HAVE_LIBPNG_PNG_H`).

**Comment by Legends0** [comment]
I have not been defining `HAVE_LIBPNG_PNG_H`. It is set as `HAVE_LIBPNG_PNG_H:INTERNAL=`  when I define  `PNG_PNG_INCLUDE_DIR`, `PNG_LIBRARY_DEBUG`, and `PNG_LIBRARY_RELEASE`.

`libpng/png.h` in my libpng install does not exist. The includes that would work are libpng16/png.h or png.h.

`HAVE_LIBPNG_PNG_H`  is evaluating to true inside [modules/imgcodecs/src/grfmt_png.cpp](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_png.cpp)  and so `libpng/png.h` gets chosen.

**Comment by alalek** [comment]
Check `cvconfig.h` (from build folder) for `HAVE_LIBPNG_PNG_H`.

**Comment by Legends0** [comment]
I am getting the expected result in cvconfig.

But I see this in the cmake output:

```
-- Looking for/opt/png/include/libpng/png.h
-- Looking for/opt/png/include/libpng/png.h - not found
```

CMake is calling this a fatal error within errors file CMakeFiles/CMakeError.log:
```
/root/opencv-4.1.1/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: /opt/png/include/libpng/png.h: No such file or directory
    1 | #include </opt/png/include/libpng/png.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[1]: *** [CMakeFiles/cmTC_a6e35.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory `/root/opencv-4.1.1/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_a6e35/fast] Error 2
```

**Comment by alalek** [comment]
> CMakeFiles/CMakeError.log

Again, this is just a CMake configuration check.
Fatal error is for compiler only. Such broken configuration is not used for next steps.
