### ISSUE TITLE
How to load any of this tracking algorithm in opencvjs(BOOSTING, MIL, KCF, TLD, MEDIANFLOW, GOTURN, MOSSE or CSRT)

### ISSUE THREAD

**Issue by vasanthhr** [opencv/opencv#15607]
Hello,

I wanted to load any of these tracking algorithms in javascript using opencvjs. please suggest me or giving some links to do the same. (We do have opencv.js compiled file and it has all these tracking algorithms)

I tried to refer this c++ and Python code link :

https://www.learnopencv.com/object-tracking-using-opencv-cpp-python/#opencv-tracking-api

code:

```
let video = document.getElementById('videoInput');
let cap = new cv.VideoCapture(video);

    // take first frame of the video
    let frame = new cv.Mat(video.height, video.width, cv.CV_8UC4);
    cap.read(frame);

    // hardcode the initial location of window
    let trackWindow = new cv.Rect(150, 60, 125, 125);

      let tracker_c = cv.TrackerKCF_create();

    // set up the ROI for tracking
    let roi = frame.roi(trackWindow);
```

Errror:

`TypeError: cv.TrackerKCF_create is not a function`

**Comment by vasanthhr** [comment]
Please refer this link for more info on this issue:

https://answers.opencv.org/question/218980/how-to-load-any-of-this-tracking-algorithm-in-opencvjsboosting-mil-kcf-tld-medianflow-goturn-mosse-or-csrt/

**Comment by asmorkalov** [comment]
NOTE: Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
