### ISSUE TITLE
G-API: crash in PatternMatching test

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#15603]
[Nightly build (Win64 debug)](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-win64-vc14-debug/builds/10939):

```
[ RUN      ] PatternMatchingIntegrationBasic.OneTransformationApplied
Process returned: -1073740791
```

relates #15313

**Comment by dmatveev** [comment]
@AsyaPronina I believe it is for you :)

**Comment by dmatveev** [comment]
CC: @andrey-golubev

**Comment by andrey-golubev** [comment]
Managed to reproduce locally with Visual Studio 15 (Win64 Debug). Not sure if I'll have time to investigate, but it fails in this [line](https://github.com/opencv/opencv/blob/3133bb49aa1af0152b155d6299c3fcecefce317a/modules/gapi/src/compiler/passes/perform_substitution.cpp#L61)

CC: @dmatveev @AsyaPronina

**Comment by andrey-golubev** [comment]
Opened PR (see above) that should fix the issue

FYI: @alalek @dmatveev @AsyaPronina
