### ISSUE TITLE
Does Opencv DNN support predicting for any model  which i create by tensorflow?

### ISSUE THREAD

**Issue by Jasonfinish** [opencv/opencv#15601]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by dkurt** [comment]
You may check tests https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_tf_importer.cpp

Additionally, https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API
