### ISSUE TITLE
OpenCV.js and three.js

### ISSUE THREAD

**Issue by kavikode** [opencv/opencv#15612]
I am trying to use OpenCV.js and three.js together. Using the Hough Circles example  https://docs.opencv.org/3.4.1/d3/de5/tutorial_js_houghcircles.html, how do I detect circles from a three.js scene?

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by asmorkalov** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
