### ISSUE TITLE
Seeking more clarity in running action_recognition.py

### ISSUE THREAD

**Issue by sayakpaul** [opencv/opencv#15614]
I am referring to this script [action_recognition.py](https://github.com/opencv/opencv/blob/master/samples/dnn/action_recognition.py). To get the script up and running, I am following these steps:

- Cloning this repo: https://github.com/kenshohara/video-classification-3d-cnn-pytorch
- Editing the `resnet.py` script as instructured in `action_recognition.py`. 
- I am downloading the `resnet-34` model weights from [link](https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M) mentioned in https://github.com/kenshohara/video-classification-3d-cnn-pytorch. 
- In order to convert the model to ONNX, I am needed to follow (reference: https://michhar.github.io/convert-pytorch-onnx/):
   
   ```python
    import torch
    import torch.onnx

    # A model class instance (class not shown)
    model = MyModelClass()

    # Load the weights from a file (.pth usually)
    state_dict = torch.load(weights_path)

    # Load the weights now into a model net architecture defined by our class
    model.load_state_dict(state_dict)

    # Create the right input shape (e.g. for an image)
    dummy_input = torch.randn(sample_batch_size, channel, height, width)

    torch.onnx.export(model, dummy_input, "onnx_model_name.onnx")

My question here is how do I instantiate `MyModelClass()` for this use-case?

**Comment by jrosebr1** [comment]
Also, to add some extra context -- myself and @sayakpaul plan on writing a tutorial on PyImageSearch on how to use OpenCV's `action_recognition.py` script. Any insight that can be provided we'll absolutely include in the publicly available tutorial to ensure others can learn from it.

**Comment by dkurt** [comment]
@sayakpaul, @jrosebr1, if you want to use pre-trained model, you can take a look at opencv_extra: https://github.com/opencv/opencv_extra/blob/c83f296dc15dbed7d4e943ac74227c1797032798/testdata/dnn/download_models.py#L773-L777

**Comment by sayakpaul** [comment]
Thanks for passing that on @dkurt. We will try it out and will keep you posted.

**Comment by sayakpaul** [comment]
Hi @dkurt. I tried running the `action_recognition.py` script with the following:

```python
python action_recognition.py --input lifting.mp4 --model resnet-34_kinetics.onnx --classes action_recognition_kinetics.txt
```

However, I am getting the following error:

```
Traceback (most recent call last):
  File "action_recognition.py", line 81, in <module>
    classify_video(args.input if args.input else 0, args.model)
  File "action_recognition.py", line 47, in classify_video
    net = cv.dnn.readNet(net_path)
cv2.error: OpenCV(3.4.4) /home/pyimagesearch/opencv/modules/dnn/src/onnx/onnx_importer.cpp:215: error: (-215:Assertion failed) attribute_proto.ints_size() == 2 in function 'getLayerParams'
```

I am using the following classes` file:
[action_recognition_kinetics.txt](https://github.com/opencv/opencv/files/3684480/action_recognition_kinetics.txt)

**OpenCV version: 3.4.4**. 

Could you suggest anything?

**Comment by dkurt** [comment]
> OpenCV version: 3.4.4.
> Could you suggest anything?

To try at least [OpenCV 3.4.7](https://github.com/opencv/opencv/releases/tag/3.4.7). The model is merged in 30 of May: https://github.com/opencv/opencv/pull/14627.

**Comment by sayakpaul** [comment]
Okay, thanks!

**Comment by sayakpaul** [comment]
@dkurt tried with OpenCV 3.4.7 and here's the new issue:

```
Traceback (most recent call last):
  File "action_recognition.py", line 81, in <module>
    classify_video(args.input if args.input else 0, args.model)
  File "action_recognition.py", line 66, in classify_video
    outputs = net.forward()
cv2.error: OpenCV(3.4.7) /home/pyimagesearch/opencv/modules/dnn/src/dnn.cpp:993: error: (-215:Assertion failed) haveInfEngine() in function 'wrapMat'
```

**Comment by sayakpaul** [comment]
@dkurt we had to comment out Lines 49 - 50 for the following reasons:
- I am not using OpenVINO
- Line 50 because by default our target is CPU

**Comment by dkurt** [comment]
@sayakpaul, feel free to propose a PR which removes IE backend setup - it'll be used automatically if available.

**Comment by Walid-Ahmed** [comment]
I am also having this error:
"opencv\modules\dnn\src\onnx\onnx_importer.cpp:215: error: (-215:Assertion failed) attribute_proto.ints_size() == 2 in function 'cv::dnn::dnn4_v20180917::ONNXImporter::getLayerParams'"

My opencv version is  4.0.0
Any advice please?

**Comment by KushalHM** [comment]
> I am also having this error:
> "opencv\modules\dnn\src\onnx\onnx_importer.cpp:215: error: (-215:Assertion failed) attribute_proto.ints_size() == 2 in function 'cv::dnn::dnn4_v20180917::ONNXImporter::getLayerParams'"
> 
> My opencv version is 4.0.0
> Any advice please?

Try downgrading openCV to version 3.4.7.28 and check. That resolved it for me.
