### ISSUE TITLE
import cv2 error:uncaught exception of type std::length_error: vector and abort

### ISSUE THREAD

**Issue by dobefore** [opencv/opencv#15616]
I got the source code using this command `git clone https://github.com/opencv/opencv`,so i can't got its version
the process of compiling is all right,yet when I import it ,the problem arose.it caused python process to abort
thanks a lot!
```
Python 3.7.4 (default, Aug  6 2019, 00:02:37) 
Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
OS:Android on termux
Arch:Aarch64)
```

```
>>> import cv2
terminating with uncaught exception of type std::length_error: vector
Aborted
```

**Comment by yusanshi** [comment]
I have met the same problem when importing cv2.
I also use termux on Android with Python 3.7.4.

Following instructions [here](https://wiki.termux.com/wiki/Instructions_for_installing_python_packages#opencv), this is what I did:
```bash
pkg install cmake pkg-config libjpeg-turbo libpng python
git clone https://github.com/opencv/opencv && cd opencv
mkdir build && cd build
LDFLAGS=" -llog -lpython3" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF ..
make
make install
```

**Comment by alalek** [comment]
> -lpython3

Why is it here? Try to remove.

**Comment by dobefore** [comment]
> I have met the same problem when importing cv2.
> I also use termux on Android with Python 3.7.4.
> 
> Following instructions [here](https://wiki.termux.com/wiki/Instructions_for_installing_python_packages#opencv), this is what I did:
> 
> ```shell
> pkg install cmake pkg-config libjpeg-turbo libpng python
> git clone https://github.com/opencv/opencv && cd opencv
> mkdir build && cd build
> LDFLAGS=" -llog -lpython3" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF ..
> make
> make install
> ```

hello，thanks for your helpful commands，but it got the same error.I 've imorted three times,it printed differernt info.
```
>>> import cv2
Segmentation fault
$ ipython
>>> import cv2
Segmentation fault
>>> import cv2
Killed
>>> import cv2
Segmentation fault
>>> import cv2
terminating with uncaught exception of type std::length_error: vector
Aborted
```
