### ISSUE TITLE
Extend v_permute intrinsic support to AVX2 and AVX512 baselines

### ISSUE THREAD

**Issue by terfendail** [opencv/opencv#15613]
related to #15596
##### Detailed description
Implement new v_permute intrinsic added by #15596 for AVX2 and AVX512 baselines

**Comment by alalek** [comment]
Generic permute operation doesn't seem universal (as we expecting) on different platforms due different limitations.
It is better to define specific operations instead like (de)interleave, broadcast, expand, swap, etc.

**Comment by pmur** [comment]
Newer variants of AVX512 with support for AVX512VBMI support this operation. 256b vectors also gain this if supporting AVX512VL too.

I'm not sure a simple solution exists for AVX2. I didn't realize how difficult it is to cross the 128b lanes.

**Comment by pmur** [comment]
I've updated the PR to support AVX and AVX512 baseline. I can't measure performance, but I have tested them via the Intel SDE.

**Comment by terfendail** [comment]
PR was extended with AVX2 and AVX512 so the issue could be considered solved
