### ISSUE TITLE
VideoCapture fails on linux with "VIDIOC_REQBUFS: Inappropriate ioctl for device", when filename contains a colon

### ISSUE THREAD

**Issue by eyaler** [opencv/opencv#15624]
opencv 4.1.1 (also 4.*, 3.*) on ubuntu 16.04, python 3.6

trying to use VideoCapture with a file containing a colon (:) in the filename (linux only), will result in error: 

VIDIOC_REQBUFS: Inappropriate ioctl for device

the internet will tell you to rebuild opencv with ffmpeg support, but what you actually need to do is add ./ to the beginning of the filename. i wasted 3 hours of my life on this.

although this is an ffmpeg issue (e.g. https://bbs.archlinux.org/viewtopic.php?id=141818), i think we should issue a warning to the very least, when the filename contains a colon or any other problematic character.

**Comment by alalek** [comment]
> warning
> contains a colon

Valid in case of RSTP/HTTP streams (can be handled by FFmpeg backend).

**Comment by sr1jan** [comment]
> opencv 4.1.1 (also 4._, 3._) on ubuntu 16.04, python 3.6
> 
> trying to use VideoCapture with a file containing a colon (:) in the filename (linux only), will result in error:
> 
> VIDIOC_REQBUFS: Inappropriate ioctl for device
> 
> the internet will tell you to rebuild opencv with ffmpeg support, but what you actually need to do is add ./ to the beginning of the filename. i wasted 3 hours of my life on this.
> 
> although this is an ffmpeg issue (e.g. https://bbs.archlinux.org/viewtopic.php?id=141818), i think we should issue a warning to the very least, when the filename contains a colon or any other problematic character.

Nah, doesn't help. I am using [this](https://github.com/TadasBaltrusaitis/OpenFace) for feature extraction. Using the docker image through docker-compose. I've tried adding the ffmpeg support but it doesn't help.

**Comment by bhargav28** [comment]
Hey ! i am facing similar issues .How did you manage to solve it ?

**Comment by bhargav28** [comment]
I do no have a colon in the file name and i still get the same error ? any idea as to what this might be related to ?
