### ISSUE TITLE
Xcode in macox 10.15 beta library code signature problem

### ISSUE THREAD

**Issue by CaffeCat** [opencv/opencv#15645]
This is the first time to use opencv at Mac OS. I used homebrew to install opencv in my Macbook, and all path search definitely correct in Xcode. I created a hello world in commandline tool project using C++ language not OBJC language. I could compile my opencv hello world, but it was broken in runtime, with showing the following logs:
=== logs ====
dyld: Library not loaded: /usr/local/opt/opencv/lib/libopencv_flann.4.1.dylib
  Referenced from: /Users/weibinwu/Library/Developer/Xcode/DerivedData/OpenCV-frdcgrfkxsvbyahjaonnyllerinn/Build/Products/Debug/OpenCV
  Reason: no suitable image found.  Did find:
	/usr/local/opt/opencv/lib/libopencv_flann.4.1.dylib: code signature in (/usr/local/opt/opencv/lib/libopencv_flann.4.1.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libopencv_flann.4.1.dylib: code signature in (/usr/local/lib/libopencv_flann.4.1.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/Cellar/opencv/4.1.1_2/lib/libopencv_flann.4.1.1.dylib: code signature in (/usr/local/Cellar/opencv/4.1.1_2/lib/libopencv_flann.4.1.1.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
== logs ===

please could somebody help me out of this problem?

**Comment by CaffeCat** [comment]
<img width="1407" alt="截屏2019-10-0518 27 38" src="https://user-images.githubusercontent.com/20905473/66253608-e5a22000-e79d-11e9-8af4-7c21f742f602.png">
this is screenshot of logs.

**Comment by CaffeCat** [comment]
I still waiting for your help, and really get confused on code signature >V<

**Comment by alalek** [comment]
> macox 10.15 beta

Probably no support for that yet (we don't have these configurations).

> /usr/local/Cellar/
> homebrew

It is better to ask there about MacOSX signing issues. Or check Apple forums about 10.15 beta signatures.

**Comment by LeeGwangYong** [comment]
@CaffeCat I met same problem, and solved it using `code sign`
I just codesign all errors.
`codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib`

**Comment by CaffeCat** [comment]
@LeeGwangYong If my opencv lib is not in directory  /usr/local/opt/*/lib/, may I change it my directory? For example
`codesign -f -s "Mac Developer: caffe@gmail.com" /usr/local/opencv2/*.lib/*.dylib`
Is it right?

**Comment by CaffeCat** [comment]
@LeeGwangYong Thanks a lot! I will try after work.

**Comment by CaffeCat** [comment]
@LeeGwangYong You are exactly right!!! It is useful to use your recommended command to code sign every error dylib file!

**Comment by vivek-ram** [comment]
@LeeGwangYong hi bro i also have same problem but codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib is not working it is saying Mac developer not found can you please help me

**Comment by pedrofrodenas** [comment]
I have the same problem, I can compile opencv 4 project but when it comes to execute it throws those errors.

**Comment by vivek-ram** [comment]
@pedrofrodenas yeah exactly I don't know what to do. have you solved that error?

**Comment by pedrofrodenas** [comment]
> @pedrofrodenas yeah exactly I don't know what to do. have you solved that error?

not yet. I don't know what to do

**Comment by vivek-ram** [comment]
@pedrofrodenas okay bro thanks 😊 let me know if u solved it thanks

**Comment by AnisimovArthur** [comment]
Hey,
I have the same problem with Vulkan.
I solved this by checking this boxes:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/39820747/68969716-b350fd00-07f6-11ea-9038-7a8c3ee5c119.png">

Hope it will help! 🙂

**Comment by pedrofrodenas** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

yes it works, thanks!

**Comment by huangxiaojingCN** [comment]
> @CaffeCat I met same problem, and solved it using `code sign`
> I just codesign all errors.
> `codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib`

yet it works, thanks 👍👍

**Comment by Meriky** [comment]
I have this problem too, but I don't have a developer account
and I finally solved this by removing the default git of mac and using git from homebrew
```
#remove /usr/bin/git
brew install git
```

**Comment by jimgeldermann** [comment]
Thanks - same problem with custom frameworks after I upgraded to Catalina

**Comment by ShaneMatthias** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

Hey, I don't have this options. Know why?

**Comment by KangWeon** [comment]
codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib

when running above, replace "YOURDEVELOPEREMAIL" by "YOUR TEAM NAME".

**Comment by kakyoism** [comment]
> @CaffeCat I met same problem, and solved it using `code sign`
> I just codesign all errors.
> `codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib`

Thanks. This helped me.
But in my case (macOS 10.14.6), I had to use the identity found in keychain which happens to be like this "Apple Development: Firstname Surname (xxxxxxxxxx)".

**Comment by Anxdada** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

I meet this problem with SDL2, which has troubled me for a long time.
Thanks u. bro

**Comment by mohsinbmwm3** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

Ton of thanks to you

**Comment by panandafog** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

Thank you, kind man!

**Comment by degreesky** [comment]
Thank you!

**Comment by sreexamus** [comment]
I have the same problem on Xcode 11.4.1. ran the command "codesign -f -s "Mac Developer:" getting no identity error. I don't see the option of Disable Library validation on Xcode 11.4.1

**Comment by mohitTomar** [comment]
> Hey,
> I have the same problem with Vulkan.
> I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

Yes, it works
Thanks a lot

**Comment by xmjiaming** [comment]
> I have the same problem, I can compile opencv 4 project but when it comes to execute it throws those errors.
> Executing this not solves the error
> codesign -f -s "Mac Developer: MYDEVELOPEREMAIL" /usr/local/opt/_/lib/_.dylib
> 
> Mac Developer: MYDEVELOPEREMAIL: no identity found



> @pedrofrodenas yeah exactly I don't know what to do. have you solved that error?


> I have the same problem on Xcode 11.4.1. ran the command "codesign -f -s "Mac Developer:" getting no identity error. I don't see the option of Disable Library validation on Xcode 11.4.1

Please use command `security find-identity` to find out the exact one's own identity.

**Comment by StevenACoffman** [comment]
If you are developing or compiling the binaries yourself, you can [generate a self-signed certificate](https://support.apple.com/en-au/guide/keychain-access/kyca8916/mac) by accessing Keychain Access > Certificate Assistant > Create Certificate -> Certificate Type: Code Signing. You can then sign your binary with:
```
codesign -f --sign <Name of certificate created above> /usr/local/opt/*/lib/*.dylib
```

**Comment by Dimisz** [comment]
> Hey, I have the same problem with Vulkan. I solved this by checking this box:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/39820747/68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8.png">
> 
> Hope it will help! 🙂

Worked for me in Nov 2021. Thanks a lot!!!
