### ISSUE TITLE
VideoCapture CPU utilization problem

### ISSUE THREAD

**Issue by 363325971** [opencv/opencv#15660]
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => Windows 10 64Bit
- Operating System / Platform => Ubuntu 18.04
- Compiler => vs2015

##### Detailed description

I found that cv2.VideoCapture() costs different CPU utilization in Windows and in Ubuntu.
I ran the following code in Windows and in Ubuntu respectively, it costs 25% CPU utilization in Windows and more than 80% CPU utilization costed in Ubuntu. Why it makes such big difference? Both OSs are run in a same machine, the only difference is the OS. So I guess is there some dependency libs I missed in the Ubuntu OS?

       cam = cv2.VideoCapture('rtmp://192.168.1.29:9935/live/0')
       while True:
               ret, frame = cam.read()
               frame = cv2.resize(frame, (960,540))

**Comment by asmorkalov** [comment]
OpenCV does not implement video decoding and encoding operations, but relays on system APIs and popular libraries like FFmpeg. There is no informaition about OpenCV build options, but the major reason -- different video decoding backends on Windows and Linux and possible hardware acceleration on some of them.

---
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
