### ISSUE TITLE
New React Native package react-native-opencv3!!  I need your help!

### ISSUE THREAD

**Issue by adamgf** [opencv/opencv#15668]
I spent about seven or eight months creating a React Native OpenCV package from scratch that is very cool: https://github.com/adamgf/react-native-opencv3.

I have no idea how to promote it and I need some help.  It has face detection, face landmarks, image processing (a good chunk of Imgproc and Core is currently supported), saves images and records videos for React Native Android and iOS apps.  The React Native community of developers need something like this.  I spent a lot of time putting this together please help me out by becoming a contributor or helping to promote it.

My e-mail is: adamgf@gmail.com

**Comment by dkurt** [comment]
Hi, @adamgf, thank you for this great contribution! I believe that's what will help more users to dive into computer vision area with positive experience.

Unfortunately we have no channels to promote community projects and the only thing we can help with are recommendations of how to make it better.

At the first sight I think it'd be useful to add tags (topics) for the repository.

**Comment by dkurt** [comment]
If you do not mind, let me close this issue as solved.

**Comment by adamgf** [comment]
Hi @dkurt I am not really sure that I want to do any more work on this you know?  I mean if people want to use it it is there for them to use.  If other people can take the mantle and continue working on this that would be cool.  I wanted to contribute to open source and I thought this would be a cool thing to contribute but I don't want to keep working on it forever by myself.
