### ISSUE TITLE
bilateralFilter exception Assertion failed

### ISSUE THREAD

**Issue by photoniker** [opencv/opencv#15686]
bilateralFilter throws an Assertion failed exception in the case of a shallow copy of a cv::Mat. In the case of a deep copy (cv::clone) the calculation is executed. 

`cv::Mat input = cv::Mat::ones(cv::Size(1000, 1000), CV_32F);

cv::Mat output = input;

cv::bilateralFilter(input, output, 9, 100, 100);`

 OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

**Comment by berak** [comment]
[from docs](https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga9d7064d478c95d60003cf839430737ed):

> This filter does not work inplace. 

and:

https://github.com/opencv/opencv/blob/46206b481446fb0f64f4a4ad9d52d775ded5f688/modules/imgproc/src/bilateral_filter.dispatch.cpp#L409

so please pass an empty, new Mat for `output` (it will get overwritten anyway)
