### ISSUE TITLE
mac java could not open video opencv 3.4.2-1

### ISSUE THREAD

**Issue by friends110110** [opencv/opencv#15689]
My computer is macOs,

```
  <dependency>
        <groupId>org.openpnp</groupId>
        <artifactId>opencv</artifactId>
        <version>3.4.2-1</version>
    </dependency>
```

the code is:

    public static void main(String[] args) throws InterruptedException {
        nu.pattern.OpenCV.loadShared();
        VideoCapture videoCapture = new VideoCapture();
        videoCapture.open("/Users/friends/projects/opencv/img-demo-video/src/main/resources/video/vtest.avi");
        BackgroundSubtractorMOG2 fgbg = createBackgroundSubtractorMOG2();
        Mat kernel = Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(3, 3));
        Mat frame = new Mat();
        while (true){

            boolean have = videoCapture.read(frame);
            Thread.sleep(100);
            Core.flip(frame,frame,1);
            if (!have){
                break;
            }
            if(!frame.empty()){
                HighGui.imshow("aa",frame);
                HighGui.waitKey(0);
            }
        }

    }
the videoCapture.isOpen is true, but 'have' is false, and frame is empty ？ it seems that opencv 3.4.2-1 has this problem

**Comment by alalek** [comment]
> 3.4.2-1

We don't maintain that package. And we don't know how it was built (`getBuildInformation()` must be provided).
Anyway, this is very outdated version (~18 months, 6 releases after that), so you should try latest version first.

**Comment by friends110110** [comment]
@alalek  it does not provider the latest opencv jar maven  for java ? Do you have the plan to provide the 4.1.2 opencv jar for  maven java ?

**Comment by alalek** [comment]
No plans for that. Related issue: #4588
