### ISSUE TITLE
[Feature Request opencv-dnn] Swish Activation, Mish Activation

### ISSUE THREAD

**Issue by LukeAI** [opencv/opencv#15693]
Google's famous [Efficientnet](https://ai.googleblog.com/2019/05/efficientnet-improving-accuracy-and.html) uses the [Swish Activation function](https://arxiv.org/abs/1710.05941)
It is currently not possible to use efficientnet in opencv due to the absence of swish.

The newer [Mish](https://arxiv.org/abs/1908.08681) activation function reportedly outperforms swish and would be great to have as an option.

**Comment by dkurt** [comment]
It's possible for now to enable this network with custom layers mechanism. Please read a tutorial https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html.

**Comment by suab321321** [comment]
@dkurt @LukeAI I would like to help with this one

**Comment by dkurt** [comment]
@suab321321, thanks! Feel free to open a PR

**Comment by grassknoted** [comment]
Hi @dkurt seeing no progress, I was wondering if I could take this issue up? I had a look at the link:

> Please read a tutorial https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html.

I'm still unsure of where to add the Mish activation function. Could you just help me get started, please?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Custom layers are part of User code. Check "samples".

**Comment by grassknoted** [comment]
Thanks for the reply @alalek ! 
Just to clarify, I would need to create an Mish function example in the `samples/` directory, right? Something like: `samples/python/mish.py`?

**Comment by alalek** [comment]
Well, if you want to add this implementation OpenCV then check this patch: #10889 + add tests on data from original framework (1-2 layers, to ensure that it is parsed properly).

Not sure if this is really "good first issue".

**Comment by dkurt** [comment]
As far as I know Swish is an activation layer so you need to implement it here: https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/elementwise_layers.cpp.

Also, you need to register a new name at https://github.com/opencv/opencv/blob/master/modules/dnn/src/init.cpp

and write some tests depends on origin framework.

**Comment by grassknoted** [comment]
> Well, if you want to add this implementation OpenCV then check this patch: #10889 + add tests on data from original framework (1-2 layers, to ensure that it is parsed properly).
> 
> Not sure if this is really "good first issue".

Looking at the required changes, I'm not very sure I could take this on. I will instead look for more beginner focussed issues. Thank you @dkurt  and @alalek for the help!
