### ISSUE TITLE
[Java/Android] submat doesn't appear to share buffer with parent mat?

### ISSUE THREAD

**Issue by UsernameInvalidException** [opencv/opencv#15697]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Android
- Compiler => N/A

##### Detailed description

From what [I've read on answers.opencv.org, when you make a submat in OpenCV, it shares the image buffer of the parent mat](https://answers.opencv.org/question/6755/submat-roi-help/?answer=6772):

![Capture](https://user-images.githubusercontent.com/26417650/66758191-cc6b3480-ee6b-11e9-8131-f977735112eb.PNG)

However, this does not seem to be the behavior I'm getting when using OpenCV from Java on Android.

Here's a snippet which makes a submat, and then fills it with solid blue. However, **the parent mat remains untouched when rendered to the screen:**

```java
//Create submat
submat1 = input.submat(new Rect(sub1pointA, sub1pointB));

//Fill submat with solid color
Imgproc.rectangle(
    submat1 ,
    new Point(0,0),
    new Point(submat1.width(), submat1.height()),
    new Scalar(0, 0, 255), -1);
```

If, however, I change the call to `rectangle()` to operate on the input mat, then I do indeed get a solid blue rectangle on the screen. It seems that either I'm missing something obvious, or this is a bug with OpenCV for Java.

**Comment by alalek** [comment]
Can't reproduce:

<details><summary>Code</summary>

```
Mat m = new Mat(7, 6, CvType.CV_32SC1);
m.put(0,  0,
         0,  1,  2,  3,  4,  5,
        10, 11, 12, 13, 14, 15,
        20, 21, 22, 23, 24, 25,
        30, 31, 32, 33, 34, 35,
        40, 41, 42, 43, 44, 45,
        50, 51, 52, 53, 54, 55,
        60, 61, 62, 63, 64, 65 );

Mat s = m.submat(1, 3, 2, 5);

System.out.println(m);
System.out.println(s);

System.out.println(m.dump());
System.out.println(s.dump());

s.setTo(new Scalar(128));

System.out.println(m.dump());
System.out.println(s.dump());
```

</details>

<details><summary>Output</summary>

```
    [junit] [0, 1, 2, 3, 4, 5;
    [junit]  10, 11, 12, 13, 14, 15;
    [junit]  20, 21, 22, 23, 24, 25;
    [junit]  30, 31, 32, 33, 34, 35;
    [junit]  40, 41, 42, 43, 44, 45;
    [junit]  50, 51, 52, 53, 54, 55;
    [junit]  60, 61, 62, 63, 64, 65]
    [junit] [12, 13, 14;
    [junit]  22, 23, 24]
    [junit] [0, 1, 2, 3, 4, 5;
    [junit]  10, 11, 128, 128, 128, 15;
    [junit]  20, 21, 128, 128, 128, 25;
    [junit]  30, 31, 32, 33, 34, 35;
    [junit]  40, 41, 42, 43, 44, 45;
    [junit]  50, 51, 52, 53, 54, 55;
    [junit]  60, 61, 62, 63, 64, 65]
    [junit] [128, 128, 128;
    [junit]  128, 128, 128]
```

</details>

**Comment by UsernameInvalidException** [comment]
Ok, I did a bit more testing and found something interesting.

If I do this then it fails as I detailed earlier:

```
Core.rotate(frame, frame, rotateCode);
processFrame(frame);
```

But if I do this then it works just fine:

```
Core.rotate(frame, rotatedFrame, rotateCode);
processFrame(rotatedFrame);
```
