### ISSUE TITLE
SIMD: v_reverse() is missing in MIPS-MSA backend

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#15705]
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_mips-msa-lin64/builds/14).

relates #15662

**Comment by alalek** [comment]
@mipsopen-fwu Could you help with MSA implementation?

**Comment by mipsopen-fwu** [comment]
@alalek Thanks a lot for the fixing. I was just going to fix it and the changes you made is fine.  👍
