### ISSUE TITLE
What is CC_STAT_MAX in ConnectedComponentsTypes?

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#15721]
All the other enums in ConnectedComponentsTypes are documented besides `CC_STAT_MAX` as shown in the code [here](https://github.com/opencv/opencv/blob/507ca291e1c0d45a8cebac4fbf7e6042fd4a093b/modules/imgproc/include/opencv2/imgproc.hpp#L397)

I couldn't find any answers on StackOverflow either. Can someone let me know what `CC_STAT_MAX` exactly means? Is it the max area? 

I will be happy to submit a PR to document it once someone can tell me the answer. 

##### System information
- OpenCV => Latest
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC 7

**Comment by alalek** [comment]
It is max enumeration value. Used internally only (for memory allocation).

Probably should be excluded from documentation completely, like [this](https://github.com/opencv/opencv/blob/4.1.2/modules/calib3d/include/opencv2/calib3d.hpp#L250-L252).

**Comment by jasjuang** [comment]
@alalek thanks for the explanation, please see #15722

**Comment by asmorkalov** [comment]
Fix merged.
