### ISSUE TITLE
findContours not working as expected for 4-connectivity

### ISSUE THREAD

**Issue by fraukej** [opencv/opencv#15726]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => c++

##### Detailed description

When I create a binary image with few pixels and call `findContours`, it seems to me that some points are skipped. Code example:

```
#include <opencv2/opencv.hpp>

int main()
{
  uchar img_data[] = {255, 255, 255, 0, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 0};
  cv::Mat img(cv::Size(5, 3), CV_8UC1, img_data);

  cv::imshow("img", img);
  cv::waitKey();

  std::vector<std::vector<cv::Point>> contours;
  std::vector<cv::Vec4i> hierarchy;
  cv::findContours(img, contours, hierarchy, cv::RETR_TREE,
      cv::CHAIN_APPROX_NONE);

  for (std::vector<cv::Point> contour : contours)
  {
    for (cv::Point p : contour)
    {
      std::cout << p << std::endl;
    }
  }
}
```
I expect the points [0,0], [0,1], [1,1], [1,2], [0,2], [0,3], [1,2], [1,2], [2,2], [2,3], [3,3], [3,2], [4,2], [4,1] and [3,0] to show up. Instead the output is:
```
[0, 0]
[1, 1]
[0, 2]
[1, 1]
[2, 2]
[3, 1]
[2, 0]
[1, 0]
[1, 1]
[2, 0]
[3, 1]
[2, 2]
```
The problem gets clearer if the image is scaled by a positive value. Then, most of the structures are recognizable, but in the corners there are diagonals instead of harsh 90 degree angles. The diagonal neighboring pixels seems to be replaced with a diagonal line. So it seems to me that 8-connectivity is used as default. For my case, I'd like to use 4-connectivity. Is there any way to do this? Thanks-

##### Steps to reproduce
Use above code.

**Comment by alalek** [comment]
> 3.2.0

Very old release (~3 years).

> cv::Size(5, 3)

Image is really small.
Some contours pixels are on the image border (result on border is not defined well).

> if the image is scaled by a positive value

You can't just resize image with contours.
Contours image must contain contours with thickness = 1. No filled regions.

**Comment by fraukej** [comment]
> Very old release (~3 years).
I tested again with 4.1.1, same results.

> Image is really small.
Agreed, but that does not change my point. For the image I expect the above mentioned points and I guess my assumption there is not wrong.

> Some contours pixels are on the image border (result on border is not defined well).
Okay, I tested again with a 0 image border (modified version below). Again, same results.
```
#include <opencv2/opencv.hpp>

int main()
{
  uchar img_data[] = {0,     0,   0,   0,   0,   0,   0,
                      0,   255, 255, 255,   0,   0,   0,
                      0,     0, 255,   0, 255,   0,   0,
                      0,   255,   0, 255,   0,   0,   0,
                      0,     0,   0,   0,   0,   0,   0};
  cv::Mat img(cv::Size(7, 5), CV_8UC1, img_data);

  cv::imshow("img", img);
  cv::waitKey();

  std::vector<std::vector<cv::Point>> contours;
  std::vector<cv::Vec4i> hierarchy;
  cv::findContours(img, contours, hierarchy, cv::RETR_TREE,
      cv::CHAIN_APPROX_NONE);

  for (std::vector<cv::Point> contour : contours)
  {
    for (cv::Point p : contour)
    {
      std::cout << p << std::endl;
    }
  }
}
```

> You can't just resize image with contours.
I used INTER_NEAREST with factor 2. I want to work at pixel level. This creates twice as large contours.

> Contours image must contain contours with thickness = 1. No filled regions.
What do you mean with that? `findContours` always worked for me with filled regions.


Can you confirm that `findContours` uses 8-connectivity as default?

**Comment by alalek** [comment]
There is some [code](https://github.com/opencv/opencv/blob/4.1.2/modules/imgproc/src/contours.cpp#L46-L54) in OpenCV implementation about 8-connectivity.

For details you may refer to this article (mentioned in [findContours() documentation](https://docs.opencv.org/3.4.8/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a)):
- ["Suzuki, S. and Abe, K., Topological Structural Analysis of Digitized Binary Images by Border Following. CVGIP 30 1, pp 32-46 (1985)"](https://scholar.google.ca/scholar?q=Topological%20structural%20analysis%20of%20digitized%20binary%20images%20by%20border%20following&hl=en&as_sdt=0&as_vis=1&oi=scholart)

Connectivity related cite:
> It is well known that in order to avoid a topological contradiction
> 0-pixels must be regarded as 8- (4-) connected if
> 1-pixels are dealt with as 4- (8-) connected.

So both 4-/8- connectivity should be used.
Did you try with inverted input?
