### ISSUE TITLE
ISA Baseline violation on mips machines

### ISSUE THREAD

**Issue by cdluminate** [opencv/opencv#15730]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942561

There are still many mips{,64} machines without MSA support.
Unconditionally enabling MSA by default will lead to SIGILL in most cases.

https://github.com/opencv/opencv/blob/4.1.2/cmake/OpenCVCompilerOptimizations.cmake#L345-L349

##### System information (version)

opencv: 4.1.2

**Comment by alalek** [comment]
@cdluminate Please try `cmake -DCPU_BASELINE=DETECT ...`

**Comment by cdluminate** [comment]
`cmake -DCPU_BASELINE=DETECT` compiles correct binary on loongson notebook. And the PR looks good to me. Thanks for the quick fix!
