### ISSUE TITLE
Feature request to add python pathlib Paths to cv2.imread and cv2.imwrite

### ISSUE THREAD

**Issue by hovnatan** [opencv/opencv#15731]
Please add support modern python's `pathlib.Path` support to OpenCV's python API. E.g., now I use `cv2.imread(str(pathlib.Path), ...)` instead of straight `cv2.imread(pathlib.Path, ...)`.

**Comment by TH3CHARLie** [comment]
@alalek Is this feature approved to go? If so,  I'd like to take this. I assume this requires changing the Python binding generator code in `modules/python/src2/cv.cpp` and `modules/python/src2/gen2.py`

**Comment by alalek** [comment]
Primary OpenCV library sources is C++ code.
Python bindings are auto-generated from public .hpp files (large part of them).
At first, lets avoid dedicated Python code (especially for specific functions only).

C++ input for mentioned functions is "string".

BTW, There is related problem with file names - Unicode symbols support (details #15675)

I believe `str()` is acceptable until we have robust universal solution.
(I'm not sure about meaningful/useful error message for `Path` parameter in current version of bindings)

Possible approach:
1. Bindings **parser** should understand that input parameter is a filesystem path. We may use some behavior tag/label in .hpp for such parameters, like [these](https://github.com/opencv/opencv/blob/4.1.2/modules/core/include/opencv2/core/cvdef.h#L409-L422).
    For example: `CV_WRAP_FILE_PATH cv::String& src`
2. For these tagged parameters supported bindings **generators** can add related overloads (in case of Java for "File") or parameter type detection with conversion to "string".
3. Bindings **generators** without support for this should not be broken.

**Comment by TH3CHARLie** [comment]
Good approach to me, but I'd like to investigate more and discuss again before coding

**Comment by tailsu** [comment]
How about a minimalistic solution that always converts `os.PathLike` objects to string?

In `getUnicodeString()` check if the object has a `__fspath__` attribute, and if so, use it to get the path as a string. From then on the conversion to string continues as usual.

**Comment by IRDonch** [comment]
FWIW, Python 3.6+ has [`PyOS_FSPath`](https://docs.python.org/3/c-api/sys.html#c.PyOS_FSPath), which does all the heavy lifting for you. So once you drop Python 3.5 (which presumably will happen eventually, its EOL is not that far off), you could just use that.

I don't think it's a good idea to use it for _all_ string parameters, though... Parameters that aren't paths shouldn't take `PathLike` objects, so that accidental conversions are prevented. IMO, the parameters that are paths should be specially marked and the bindings generator should use those marks to decide when to add `PyOS_FSPath` calls.

**Comment by TemitopeOladokun** [comment]
I tried to download all the images generated and saved in new_image but I could only see the first image in the folder's path. What am I doing wrong?

Feel free to edit the code if it is wrong.

height = original_Image.shape[1]
width = original_Image.shape[0]
height = 1024
width = 1024
newX,newY = height, width
new_image = cv2.resize(original_Image,(int(newX),int(newY)))
  for i in (new_image):
    new_folder = cv2.imwrite(os.path.join(path, 'resizedimg.jpg'), new_image)
    print(new_folder)

**Comment by jinfagang** [comment]
Does this feature support for now?

**Comment by tildekarthik** [comment]
I also request if this can be added for the VideoCapture function

I have used str(PathLib_Object) and passed it as a workaround

**Comment by HalfWhitt** [comment]
One more reason in favor is that if you're working with Path objects, it's not always simply a matter of converting with `str(path)`, because it might be a path that's relative to somewhere other than the current working directory. In this case you have to supply `str(path.resolve())`, when ideally one could simply use `path` alone.

**Comment by MasaYan24** [comment]
+1

**Comment by JJBT** [comment]
+1

**Comment by songyuc** [comment]
Hello OpenCV team and community,

I came across this issue and wanted to express my strong support for adding `pathlib.Path` support to `cv2.imread()` and `cv2.imwrite()` functions. As someone who frequently works with file paths in Python, I find the `pathlib` library to be an invaluable tool for writing clean and maintainable code.

#### Why This Feature is Important

1.  **Consistency with Modern Python Practices**: The use of `pathlib.Path` objects is becoming a standard in modern Python codebases. Supporting this in OpenCV would make the library more Pythonic and consistent with other Python libraries.
    
2.  **Ease of Use**: Using `Path` objects can simplify code and make it more readable. For example, one could easily chain methods to manipulate paths, which is not as straightforward with string paths.
    
3.  **Enhanced Functionality**: `Path` objects offer additional methods and attributes that can be useful in various scenarios, such as checking if a file exists, getting the file's parent directory, etc.
    

#### Example

Here's a simple example to illustrate the convenience:

```python
from pathlib import Path
import cv2

# Define the Path object
image_path = Path("images") / "sample.jpg"
output_path = Path("output") / "result.jpg"

# Read and write the image using Path objects
image = cv2.imread(image_path)
cv2.imwrite(output_path, image)
```

I believe that adding this feature would be a significant improvement to OpenCV's Python API and would benefit many users. Thank you for considering this request, and I look forward to any updates on this issue.

Best regards,
Yucheng Song

**Comment by HalfWhitt** [comment]
@songyuc Agreed with all your points. However, your example code would look just about the same using string paths. I think a better example would be something that loops through a directory and has to concatenate relative paths on the fly. Something like this:

```python
from pathlib import Path
import cv2

source_dir = Path('images_to_process')
output_dir = Path('output')

for image_path in source_dir.glob('*.jpg'):
    image = cv2.imread(image_path) # image_path is relative, but already knows where it's relative to
    cv2.imwrite(output_dir / image_path.name, image)
```

Without pathlib, this would be:

```python
import glob, os
import cv2

source_dir = 'images_to_process'
output_dir = 'output'

for image_path in glob('*.jpg', root_dir=source_dir):
    in_name = os.join(source_dir, image_path)
    image = cv2.imread(in_name)
    out_name = os.join(output_dir, image_path)
    cv2.imwrite(out_name, image)
```

And that's only in Python 3.10+, when `glob` gained the `root_dir` parameter. Prior to that it would be even more cumbersone, since you'd have to call `os.chwd` or `os.walk` or something like that to work with the multiple directories involved.

**Comment by songyuc** [comment]
@HalfWhitt, your example is very enlightening to me. Thanks!

**Comment by windygoo** [comment]
Any update?

**Comment by StephenZhao1** [comment]
> Hello OpenCV team and community,
> 
> I came across this issue and wanted to express my strong support for adding `pathlib.Path` support to `cv2.imread()` and `cv2.imwrite()` functions. As someone who frequently works with file paths in Python, I find the `pathlib` library to be an invaluable tool for writing clean and maintainable code.
> 
> #### Why This Feature is Important
> 1. **Consistency with Modern Python Practices**: The use of `pathlib.Path` objects is becoming a standard in modern Python codebases. Supporting this in OpenCV would make the library more Pythonic and consistent with other Python libraries.
> 2. **Ease of Use**: Using `Path` objects can simplify code and make it more readable. For example, one could easily chain methods to manipulate paths, which is not as straightforward with string paths.
> 3. **Enhanced Functionality**: `Path` objects offer additional methods and attributes that can be useful in various scenarios, such as checking if a file exists, getting the file's parent directory, etc.
> 
> #### Example
> Here's a simple example to illustrate the convenience:
> 
> ```python
> from pathlib import Path
> import cv2
> 
> # Define the Path object
> image_path = Path("images") / "sample.jpg"
> output_path = Path("output") / "result.jpg"
> 
> # Read and write the image using Path objects
> image = cv2.imread(image_path)
> cv2.imwrite(output_path, image)
> ```
> 
> I believe that adding this feature would be a significant improvement to OpenCV's Python API and would benefit many users. Thank you for considering this request, and I look forward to any updates on this issue.
> 
> Best regards, Yucheng Song

pathlib is better than os.path as far as I am concerned.

**Comment by HalfWhitt** [comment]
@StephenZhao1 I don't think anyone here disagrees with you. The feature to use pathlib paths has already been implemented and merged — mission accomplished!
