### ISSUE TITLE
How to build the opencv4.1.1 with dldt on arm platform?

### ISSUE THREAD

**Issue by zhaozj0529** [opencv/opencv#15734]
How to build the opencv4.1.1 with dldt on arm platform

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
It depends on ARM platform.
Some common steps are available on Wiki page: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#raspbian-buster
