### ISSUE TITLE
CUDA_nppc_LIBRARY (ADVANCED) error during compile opencv 4.1.1

### ISSUE THREAD

**Issue by aaktaev** [opencv/opencv#15732]
##### System information (version)
 OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => cmake
-CUDA 10.0.130
- PYTHON 3.7.5

##### Steps to reproduce
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D WITH_TBB=ON \
        -D WITH_CUDA=ON \
        -D ENABLE_FAST_MATH=1 \
        -D CUDA_FAST_MATH=1 \
        -D WITH_CUBLAS=1 \
        -D WITH_OPENGL=ON \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D PYTHON_DEFAULT_AVAILABLE=/usr/bin/python3.7 \
        -D BUILD_OPENCV_PYTHON3=ON \
        -D PYTHON_INCLUDE_DIR=/usr/bin/python3 \
        -D PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.1/modules \
        -D CMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
        -D BUILD_opencv_cudacodec=OFF \
        -D BUILD_EXAMPLES=ON .. 
```
It fails with error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nppc_LIBRARY (ADVANCED)
```

**Comment by alalek** [comment]
> CUDA_nppi_LIBRARY=true

Are you sure that this is correct?

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by aaktaev** [comment]
> > CUDA_nppi_LIBRARY=true
> 
> Are you sure that this is correct?
> 
> Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
> This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by aaktaev** [comment]
@alalek I've tried different ways, even if I remove this property - error is the same

**Comment by aaktaev** [comment]
Fixed by installing cuda-npp lib.

**Comment by hererookie** [comment]
> Fixed by installing cuda-npp lib.

install cuda-npp lib. ??????
