### ISSUE TITLE
Imshow incorrect behaviour

### ISSUE THREAD

**Issue by anuppari** [opencv/opencv#15745]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc

##### Detailed description

The [documentation claims](https://docs.opencv.org/master/d7/dfc/group__highgui.html#ga453d42fe4cb60e5723281a89973ee563) that imshow maps [0,1] to [0,255] for float matrices, however it seems to also be including negative values, i.e., [0, -1] is also mapped to [0,255]. Previously, negative values were clamped to 0. See examples below

##### Steps to reproduce

Note the negative values in the matrices.

```python
import cv2 as cv
import numpy as np

mat1 = -1*np.ones([500,500])
cv.imshow("mat1", mat1)
mat2 = np.tile(np.linspace(-1, 1, 500), (500,1))
cv.imshow("mat2", mat2)
cv.waitKey(0)
```
This produces:
![imshow_error](https://user-images.githubusercontent.com/3847301/67132651-a96fb600-f1c6-11e9-8a3f-6dc65ae296db.png)

**Comment by alalek** [comment]
Related code is [here](https://github.com/opencv/opencv/blame/4.1.2/modules/highgui/src/precomp.hpp#L155).

`convertScaleAbs()` has been misused.
`convertTo()` should be used instead.

**Workaround**: pass normlized `uint8` input to `imshow()`

**Comment by TH3CHARLie** [comment]
I have submitted a PR #15746 solving this. After the PR, the sample Python code produces the following output:
<img width="998" alt="Screen Shot 2019-10-19 at 4 12 15 PM" src="https://user-images.githubusercontent.com/22651013/67140336-2add4c00-f28c-11e9-9fec-6f2ea48e48e5.png">
