### ISSUE TITLE
cv2.CAP_PROP_POS_MSEC does not work, if not "read" is called

### ISSUE THREAD

**Issue by kanehekili** [opencv/opencv#15749]
##### System information (version)

- OpenCV =>4.1.2-1
- Operating System / Platform => Linux (Arch)
- Compiler => gcc (but not relevant)

##### Detailed description
cap=cv2.VideoCapture (this is python 3 code!)
cap.get(cv2.CAP_PROP_POS_MSEC) does not work, if not cap.read has been called before.
The current version does not seem to read the position in milliseconds, if a cap.read() has not been issued before the query. It works in Version 4.1.1-1
##### Steps to reproduce

This python3 code shows the problem:
```.py
import cv2

cap=cv2.VideoCapture("set/your/file/here")
w = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
cnt = cap.get(cv2.CAP_PROP_FRAME_COUNT)
print("Opencv width %d frames %d"%(w,cnt))

cap.read()
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 0 after read %.3f"%ts)

#set pos
cap.set(cv2.CAP_PROP_POS_FRAMES,5)
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 5 after setPos %.3f"%ts)

ret,frame=cap.retrieve()
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 5 after retrieve %.3f"%ts)

ret,frame=cap.read()
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 5 after read %.3f"%ts)

cap.release()

if __name__ == '__main__':
    pass
  ```
Result for Version 4.1.2-1:
  ```
Opencv width 720 frames 9000
ts @ frame 0 after read 0.000
ts @ frame 5 after setPos -2969.967
ts @ frame 5 after retrieve -2969.967
ts @ frame 5 after read 520.000
  ```
Result for Version 4.1.1-1:
  ```
Opencv width 720 frames 9000
ts @ frame 0 after read 40.000
ts @ frame 5 after setPos 480.000
ts @ frame 5 after retrieve 480.000
ts @ frame 5 after read 520.000
  ```

**Comment by alalek** [comment]
Please note, that VideoCapture properties are backends implementation-specific and optional. Some of them are not reliable in some cases (like set frame pos).

Usually frame properties can be returned for grabbed frames only.
Anyway errors emitting should be improved.

**Comment by kanehekili** [comment]
I do not concur with that. I've printed out the build information of both versions, the backends are the same.
From my point of view you've changed a well known behavior within the API. I'm using OpenCV since its Version 2, and this always worked (your code is an important part of my project).
Atached is the build information of the two versions, maybe I've overlooked something .. 
[OpenCV-410.txt](https://github.com/opencv/opencv/files/3764723/OpenCV-410.txt)
[OpenCV-412.txt](https://github.com/opencv/opencv/files/3764724/OpenCV-412.txt)

**Comment by alalek** [comment]
There is this issue: #8834
Fix for FFmpeg backend: #15757

Fix is valid.
So reading of frame's property `CAP_PROP_POS_MSEC` before grabbing the frame is invalid operation.

Possible improvement here is adding warning messages if property has been accessed before grabbing actual after "seek" operation (strange negative numbers in your output). Unfortunately proper detection between grab calls is not possible.

**Comment by kanehekili** [comment]
I understand. The mistake is, that i retrieve but not grab the frame.
So I'll revamp my code to get it working again. Still I do not understand why it has been working until now... (obviously being "invalid" all the time).
Thank you for your support!

**Comment by williamfzc** [comment]
@kanehekili hello :) 
same issue here so, can I know how you get your code working again ?
thanks

**Comment by williamfzc** [comment]
what's more,

```python
import cv2

cap=cv2.VideoCapture("set/your/file/here")
w = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
cnt = cap.get(cv2.CAP_PROP_FRAME_COUNT)
print("Opencv width %d frames %d"%(w,cnt))

cap.read()
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 0 after read %.3f"%ts)
```

Result:

```
4.1.2
ts @ frame 0 after read 0.000
4.1.1
ts @ frame 0 after read 40.000
```

a little confused. which one is (will be) correct in the future?
and, what is the actual meaning of these timestamps? (start time ? end time ? )

**Comment by native-api** [comment]
@alalek If I'm at the end of the video, I still get a wrong number even after calling `read()`. How am I supposed to get the position in this case?

```
In [1]: import cv2
In [2]: v=cv2.VideoCapture('sample.mp4')
In [3]: v.get(cv2.CAP_PROP_POS_MSEC)
Out[3]: 0.0

In [4]: v.set(cv2.CAP_PROP_POS_AVI_RATIO,1)
Out[4]: True

In [5]: v.get(cv2.CAP_PROP_POS_MSEC)
Out[5]: 0.078125

In [10]: v.read()
Out[10]: (False, None)

In [11]: v.get(cv2.CAP_PROP_POS_MSEC)
Out[11]: 0.0
```

**Comment by alalek** [comment]
> (False, None)

`read()` call is failed due to end of video stream (as requested).

What is expected behavior?

**Comment by native-api** [comment]
The expected behavior is for `v.get(cv2.CAP_PROP_POS_MSEC)` to return the correct value after that -- since this is how it's supposed to be done now according to this ticket.

**Comment by alalek** [comment]
But ... there is no correct timestamp value after the end of video stream.
0.0 is default value for "not supported" property ([legacy of `.get()` behavior](https://github.com/opencv/opencv/blame/1192734131aed215b8780743e745754f24c0f9aa/modules/videoio/include/opencv2/videoio.hpp#L787))

**Comment by native-api** [comment]
Intuitively, the timestamp should be the previous one + the duration of the frame. At the end of the stream, that would also be the total length of the stream.

**Comment by native-api** [comment]
AFAICS from [the code](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L1590-L1609), it looks like setting `CAP_PROP_POS_AVI_RATIO` is not supposed to require calling read() because it sets `picture_pts` which `CAP_PROP_POS_MSEC` getter checks for.

**Comment by native-api** [comment]
(A code link in the last message was incorrect. Fixed it).

**Comment by alalek** [comment]
> + the duration of the frame

Doesn't make sense for [VFR](https://en.wikipedia.org/wiki/Variable_frame_rate) videos (almost all modern videos from Android / GoPro cameras).

---

Please do not mess `getProperty()` and `setProperty()` behavior.

**Comment by native-api** [comment]
CFR or VFR, each individual frame still has a duration.

**Comment by kanehekili** [comment]
I second  alalek. After the end of the stream you don't have a valid timestamp. I've caught that in my code, so from my perspective the code it working correctly. BTW: Setting CAP_PROP_POS_AVI_RATIO is about the worst thing you can do. I*ve tried that, but this is basically unusable - not the fault of opencv but of the ffmpeg API.

**Comment by sjtu-zy** [comment]
OpenCV =>4.5.1

```python
import cv2
stream=cv2.VideoCapture(r"D:\IPP\visual-vehicle-behavier-analyzer\scene_data\test.mp4")
stream.set(cv2.CAP_PROP_POS_AVI_RATIO,0)
total_time = stream.get(cv2.CAP_PROP_POS_MSEC)
print("set cv2.CAP_PROP_POS_AVI_RATIO = 0 , result "+str(total_time))

stream.set(cv2.CAP_PROP_POS_AVI_RATIO,1)
total_time = stream.get(cv2.CAP_PROP_POS_MSEC)
print("set cv2.CAP_PROP_POS_AVI_RATIO = 1 , result "+str(total_time))

stream.set(cv2.CAP_PROP_POS_AVI_RATIO,2)
total_time = stream.get(cv2.CAP_PROP_POS_MSEC)
print("set cv2.CAP_PROP_POS_AVI_RATIO = 2 , result "+str(total_time))
```

**Comment by kanehekili** [comment]
Ratio goes between 0.0 and 1.0 What do you want to tell us?
