### ISSUE TITLE
Support Bazel BUILD

### ISSUE THREAD

**Issue by jinay1991** [opencv/opencv#15742]
I would like to propose change BUILD SYSTEM to more advance and faster, scalable BUILD SYSTEM by adding support to [Bazel](https://bazel.build).

**Comment by alalek** [comment]
Due resource limitations we prefer to avoid supporting of multiple build systems with a similar features.

Feel free to propose wrappers to use OpenCV from bazel.

**Comment by evan-flynn-apexai** [comment]
This thread on stackoverflow might help others who end up here: https://stackoverflow.com/questions/76777350/building-opencv-with-rules-foreign-cc
