### ISSUE TITLE
"sudo ln -s /Applications/Xcode.app/Contents/Developer Developer" fails on macOS Catalina

### ISSUE THREAD

**Issue by y-ich** [opencv/opencv#15755]
Hello.

 I read https://docs.opencv.org/2.4/doc/tutorials/introduction/ios_install/ios_install.html#ios-installation for iOS development.

"sudo ln -s /Applications/Xcode.app/Contents/Developer Developer" fails on macOS Catalina as below.

    ln: Developer: Read-only file system

Are there any workarounds?

Thanks.

**Comment by y-ich** [comment]
I found a prebuilt framework in release 4.1.1 and my problem was solved.
Thank you for great efforts.

As I think that someone who wants to build the framework from source on Catalina will encounter this issue, I keep it open.

**Comment by alalek** [comment]
OpenCV 2.4 is not supported anymore.
Perhaps, "ln -s" is a workaround for ancient MacOSX - it is not needed with modern versions.

**Comment by y-ich** [comment]
@alalek san,

Thank you for your information.
Then is this issue for documentation?

I saw the page below.
https://docs.opencv.org/4.1.2/d5/da3/tutorial_ios_install.html

**Comment by alalek** [comment]
Right, documentation should be improved.

**Comment by alalek** [comment]
duplicate of #15175
fixed #15975 (3.4.9 / 4.2.0)
