### ISSUE TITLE
OpenCV using Movidius NCS2 gives error when using Darknet neural network

### ISSUE THREAD

**Issue by sharma-n** [opencv/opencv#15750]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Raspbian Stretch / Raspberry Pi 3B+
- Language => Python

##### Detailed description

I am trying to perform OCR using the Intel Movidius Neural Compute Stick 2. The OCR network that I am using is based on YOLO, and therefore has the graph structure saved as a  `.cfg` file and the weights as a `.weights` file. I use OpenCV which was installed with Openvino on a Raspberry Pi 3b+. My code is given below:

```python
import cv2
 
# load network
ocr_net  = cv2.dnn.readNetFromDarknet('ocr-net.cfg', 'ocr-net.weights')
ocr_net.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD)
ocr_net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
 
# perform inference
im = cv2.imread('img_path.jpg')
blob = cv2.dnn.blobFromImage(im, swapRB=False)
ocr_net.setInput(blob)
result = ocr_net.forward()
```
On running the code, I get the following error:

```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    result = ocr_net.forward()
cv2.error: OpenCV(4.1.2-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Device with "CPU" name is not registered in the InferenceEngine in function 'initPlugin'
```
If I change the inference target to `cv2.dnn.DNN_TARGET_CPU` and the inference backend to `cv2.dnn.DNN_BACKEND_OPENCV`, the model works fine and is able to correctly perform OCR. My openvino/openCV setup is also correctly installed since I can correctly run other Tensorflow/Caffe models using openCV (using `readNetFromTensorflow()`/`readNetFromCaffe()`).

The OCR network that I am attempting to use can be found here: [cfg](https://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.cfg) , [weights](https://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.weights) .

I was advised by the Intel community to open up an issue here, since this may be a OpenCV specific issue.

**Comment by alalek** [comment]
> Raspberry Pi
> Device with "CPU" name is not registered

Not supported, refer to OpenVINO release notes.

**Comment by alalek** [comment]
Probably relates: #15063

**Comment by dkurt** [comment]
As a workaround you may build `libMKLDNNPlugin.so` following a guide from https://github.com/opencv/dldt/blob/2019/inference-engine/README.md#build-for-raspbian-stretch-os. And put it to the `/opt/intel/openvino/deployment_tools/inference_engine/lib/armv7l`

**Comment by r0l1** [comment]
I get the same error

```
OpenCV(4.1.2) /tmp/opencv/src/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Unsupported primitive of type: OpenCVLayer name: yolo_89 in function 'initPlugin'
```

Trying to use the model optimizer with the custom extension does not work either. I precisely followed the instructions from the [OpenVINO docs page](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html).

The model optimizer fails with:
```
[ ERROR ]  'Graph' object has no attribute 'node'
Cannot pre-process TensorFlow graph after reading from model file "/v/c/frozen_darknet_yolov3_model.pb". File is corrupt or has unsupported format. Details: 'Graph' object has no attribute 'node'. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #44. 
```

Our application is not usable at all with the latest OpenVINO release. Hope we can get this fixed.

**Comment by r0l1** [comment]
@alalek #15063 works. Thank you for you fast support.
