### ISSUE TITLE
InferenceEngine: Custom Layer missing (YOLO)

### ISSUE THREAD

**Issue by r0l1** [opencv/opencv#15766]
Loading a YOLOv3 model prepared with the Model Optimizer fails with the Myriad backend:
```
unsupported outer layer type: RegionYolo
```

The RegionYolo layer is supported as listed [here](https://docs.openvinotoolkit.org/2019_R1.1/_docs_IE_DG_supported_plugins_Supported_Devices.html).

Thanks in advance for helping!

**Comment by r0l1** [comment]
@alalek Could you please outline, what's required to get this implemented? If it's not too time consuming, I would try to contribute. Thanks!

**Comment by alalek** [comment]
What is host system? (x86 or ARM)

**Comment by r0l1** [comment]
We are working with Intel CPUs: x86_64

**Comment by alalek** [comment]
Good (there is separate issue with missing support for custom layers on ARM hosts (RPi) - due missing CPU plugin).

Does CPU target work? (without Myriad/VPU)

2019 R1 is not the latest version. 2019 R3 should have [support](https://docs.openvinotoolkit.org/2019_R3/_docs_IE_DG_supported_plugins_Supported_Devices.html) for this layer on VPU too. Did you try this version?

Which API is used? Did you try to load original YOLOv3 into OpenCV?

There is [OpenCV DNN tests with 2019R3 + Myriad2 (NCS)](http://pullrequest.opencv.org/buildbot/builders/master_openvino-opencl-skl-lin64/builds/471) and YOLOv3 test is running:
```
[ RUN      ] Test_Darknet_nets.YOLOv3/1, where GetParam() = DLIE/MYRIAD
[       OK ] Test_Darknet_nets.YOLOv3/1 (15007 ms)
```
(this is without using of Model Optimizer and IRs files)

However MyriadX(NCS2) test is [skipped](http://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/2807):
```
[ RUN      ] Test_Darknet_nets.YOLOv3/1, where GetParam() = DLIE/MYRIAD
[     SKIP ] Test with tag 'dnn_skip_ie_myriadx' is skipped ('dnn_skip_ie_myriadx' is in skip list)
[       OK ] Test_Darknet_nets.YOLOv3/1 (2368 ms)
```

Which VPU/Myriad device do you have?

**Comment by r0l1** [comment]
Thanks for the fast reply.

> Good (there is separate issue with missing support for custom layers on ARM hosts (RPi) - due missing CPU plugin).

We have switched to Intel CPUs together with our Hardware Partner due to those limitations. A positive side effect where faster RAM accesses.

> Does CPU target work? (without Myriad/VPU)

CPU target and Myriad VPU target works without the Model Optimizer.

> 2019 R1 is not the latest version. 2019 R3 should have support for this layer on VPU too. Did you try this version?

Our build environment builds a clean OpenCV 4.1.2 library with the open source dldt 2019 R3 release. We included following patch #15752 to get YOLOv3 working.

> Which API is used? Did you try to load original YOLOv3 into OpenCV?

It is a standard YOLOv3. Loading through OpenCV works with the mentioned patch. Converting the model with the Model Optimizer and then loading it produces the `unsupported outer layer type: RegionYolo` error.

> Which VPU/Myriad device do you have?

We only use the latest Myriad2 Chips.

**Why using the Model Optimizer?** Because we experience a too high memory consumption and I am trying to minimize the required RAM requirements. Our embedded Intel system has only 2 GB of RAM. I opened the following issue: #15859

**Comment by r0l1** [comment]
After some more testing, the OpenCV CPU backend is also affected.

**Comment by r0l1** [comment]
YOLO networks require a custom handling procedure for the final 3 YOLO layers. Using IR models prepared with the model optimizer causes this issue. OpenCV should handle these final output layers as if parsed with the default DNN parser...

**Comment by dkurt** [comment]
@r0l1, can you please clarify a bit this issue? If it's a bug report pleas provide a minimal working example. Or this is a feature request? Please note that Inference Engine's Region is different from OpenCV's and enabling it will require additional postprocessing like they do in the samples:
https://github.com/opencv/open_model_zoo/blob/2019_R3/demos/object_detection_demo_yolov3_async/main.cpp#L143-L168

**Comment by dkurt** [comment]
After this PR all the layers are directly supported by IE backend: https://github.com/opencv/opencv/pull/17112

**Comment by r0l1** [comment]
@dkurt sorry for not answering. Was quite busy during the last month... I'll test the latest release with the new PR! Have a great day
