### ISSUE TITLE
module 'cv2.cv2' has no attribute 'linemod'

### ISSUE THREAD

**Issue by SongZRui** [opencv/opencv#15767]
##### System information (version)

- OpenCV == 4.1.1:
- Operating System / Platform == ubuntu 16.04
- Compiler => python 3.5

##### Detailed description

calling 'cv2.linemod.colormap' according to [doc](https://docs.opencv.org/4.1.1/d2/d3a/group__rgbd.html#gaa6148fb2b9582f983782fdc89afe3384) returns the following error:
module 'cv2.cv2' has no attribute 'linemod'

##### Steps to reproduce
import cv2 
cv2.linemod.colormap(some-parameter)

**Comment by dkurt** [comment]
Please check you environment / IDE. This is not OpenCV error.
