### ISSUE TITLE
Windows-only releases?

### ISSUE THREAD

**Issue by GMTSE** [opencv/opencv#15776]
[Sorry if it is not an actual issue, but I could not find the answer on the web.]

My question is "why are there official releases only for the Microsoft's Windows platform and none for Apple's macOS or for GNU-Linux/*BSD?" Is that technically that more simple to build a release for this platform??? Are the devs of OpenCV using this platform in majority?

I'm a teacher in a university and we ask our CS students to use OpenCV. There are as many students using each of the platforms (as it is the case in the business Image-dev world or in CS/IA/ImageProcessing research domain), so I don't see why people using Microsoft's platform would benefit from such an advantage.

**Comment by alalek** [comment]
I'm not sure that you will get full answer here.
- Our resources are limited.
- Linux* ecosystem has many options (single "Linux package" is not possible) - but it is not bad.

> Are the devs of OpenCV using this platform in majority?

The devs of OpenCV usually build OpenCV from sources.

OpenCV is cross-platform library.
Nowadays, all major Linux distributions provide OpenCV binary packages. Apple has own specific distribution channels, like homebrew. Also there are conda, vcpkg, Python's pypi/pip and many others which support multiple platforms.
Big thanks to the maintainers of all distribution channels!
