### ISSUE TITLE
Bug in stereo_match.cpp

### ISSUE THREAD

**Issue by oleg-alexandrov** [opencv/opencv#15779]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

The stereo_match.cpp code (https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_match.cpp) has a scaling issue that took me 2 days to track down. The computed disparity is a signed int16, and is scaled by a factor of 16 compared to the true disparity, as per the documentation. The disparity thus must be converted to float and divided by 16.0 before invoking reprojectImageTo3D(). As it is now, since this division is not done, the result of reprojectImageTo3D() is wrong, as is at 1/16-the the scale. 

Suggested fix:

    Mat float_disp;
    disp.convertTo(float_disp, CV_32F, 1.0f/16.0f);
    reprojectImageTo3D(float_disp, xyz, Q, true);

**Comment by alalek** [comment]
Investigation notes:

1.
Previous [reprojectImageTo3D()](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/include/opencv2/calib3d.hpp#L2378-L2407) documentation note about 16-bit has been added in #5449:
> If 16-bit signed format is used, the values are assumed to have no
fractional bits.

2.
`StereoBM` and `StereoSGBM` are both implements [`StereoMatcher`](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/include/opencv2/calib3d.hpp#L2648)  algorithm with the following documentation:
> Some algorithms, like StereoBM or StereoSGBM compute 16-bit fixed-point disparity map (where each disparity value has 4 fractional bits), whereas other algorithms output 32-bit floating-point disparity map.

3.
There is function [`filterSpeckles()`](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/include/opencv2/calib3d.hpp#L2352-L2366): note about `maxDiff` parameter:
> Note that since StereoBM, StereoSGBM and may be other algorithms return a fixed-point disparity map, where disparity values are multiplied by 16, this scale factor should be taken into account when specifying this parameter value"

4.
One more related function [validateDisparity()](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/include/opencv2/calib3d.hpp#L2374) has no documentation about 16-bit handling (but disparity are [divided by its implementation](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/src/stereosgbm.cpp#L2472)).

5.
`stereo` module from `opencv_contrib` uses 4-bit fractional part in their algorithms too.

6.
StereoBM may provide 32S output ([8-bit fraction part](https://github.com/opencv/opencv/blame/4.1.2/modules/calib3d/src/stereobm.cpp#L279), see #6959)

---

So only `reprojectImageTo3D()` has consistency conflict with 16S (and obviously 32S) disparity handling. Also I don't see users for 8U disparity maps.

**Comment by mshabunin** [comment]
7. [reprojectImageTo3D](https://github.com/opencv/opencv_contrib/blob/3e9ebc4b0103cedd2435b6499134f5b0b6c4d6fa/modules/cudastereo/include/opencv2/cudastereo.hpp#L297-L311) from _cudastereo_ module assumes 16S image have no fractional bits.

8. 8U disparity is used in the [sample](https://github.com/opencv/opencv_contrib/blob/3e9ebc4b0103cedd2435b6499134f5b0b6c4d6fa/modules/stereo/samples/sample.cpp#L57) in _opencv_contrib/stereo_ module

**Comment by alalek** [comment]
Well, lets keep current behavior of `reprojectImageTo3D()`.
(scaled 16S input can't be passed here, so user should pre-scale input and convert it into 32F)
