### ISSUE TITLE
IMRead() with IMReadUnchanged flag ignores EXIF orientation, when it should preserve it

### ISSUE THREAD

**Issue by Alexn117** [opencv/opencv#15786]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => macOS Catalina version: 10.15
- Compiler => gocv version: 0.21.0

##### Detailed description

The documentation seems to indicate that an image's EXIF orientation will be preserved, unless the **IMREAD_IGNORE_ORIENTATION** flag is set. But when I set the **IMREAD_UNCHANGED** flag, the EXIF orientation is also not preserved. Strangely, if I use **IMREAD_COLOR**, it is preserved.

_If EXIF information are embedded in the image file, the EXIF orientation will be taken into account and thus the image will be rotated accordingly **except if the flag IMREAD_IGNORE_ORIENTATION is passed**._
https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56

_IMREAD_IGNORE_ORIENTATION  | **If set, do not rotate the image according to EXIF's orientation flag**._
https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga61d9b0126a3e57d9277ac48327799c80

##### Steps to reproduce

EXIF orientation is ignored, even though the IMREAD_IGNORE_ORIENTATION flag is not being set:

`img := gocv.IMRead(name, gocv.IMReadUnchanged)`

EXIF orientation is preserved:

`img := gocv.IMRead(name, gocv.IMReadColor)`

EDIT: sample image
![IMG_3543 - no location](https://user-images.githubusercontent.com/29024614/67626728-ace5eb80-f81d-11e9-928c-a3720d64a956.jpg)

**Comment by alalek** [comment]
Please attach sample image.

BTW, Not all image codecs in OpencV support EXIF.

**Comment by Alexn117** [comment]
> Please attach sample image.
> 
> BTW, Not all image codecs in OpencV support EXIF.

I attached the image to the post.

**Comment by alalek** [comment]
`IMREAD_COLOR`(1) - apples EXIF
`IMREAD_IGNORE_ORIENTATION` = `IMREAD_IGNORE_ORIENTATION | IMREAD_GRAYSCALE`(128) - doesn't apply EXIF
`IMREAD_UNCHANGED`(-1) - doesn't apply EXIF too

Image is handled as expected.

[`IMREAD_UNCHANGED` documentation says](https://github.com/opencv/opencv/blob/3.4.8/modules/imgcodecs/include/opencv2/imgcodecs.hpp#L65):

> If set, return the loaded image as is (with alpha channel, otherwise it gets cropped).


If you want to improve documentation, feel free to propose a PR

**Comment by collinbrake** [comment]
@alalek I proposed a PR to improve the documentation for the IMREAD_UNCHANGED flag. Should the documentation for the `imread()` function also be changed?
>If EXIF information are embedded in the image file, the EXIF orientation will be taken into account >and thus the image will be rotated accordingly except if the flag IMREAD_IGNORE_ORIENTATION >is passed.

**Comment by preeti13456** [comment]
I proposed a PR to image_ignore_orientation can we change the params(parameters) . And can we use image_frame(length,width) and change the orientation accordingly.
