### ISSUE TITLE
Typo in Assert in fisheye.cpp

### ISSUE THREAD

**Issue by Cherubin7th** [opencv/opencv#15788]
I think you want to assert K2 and D2 not K1 and D1 again in see last line
    CV_Assert(K1.empty() || (K1.size() == Size(3,3)));
    CV_Assert(D1.empty() || (D1.total() == 4));
    CV_Assert(K2.empty() || (**K1**.size() == Size(3,3)));
    CV_Assert(D2.empty() || (**D1**.total() == 4)); 

In: https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fisheye.cpp#L860

**Comment by alalek** [comment]
Nice catch!
Feel free to prepare PR into "3.4" branch.
