### ISSUE TITLE
Opencv4.1.1 can't use in Android but else version can do in same config..

### ISSUE THREAD

**Issue by Guanyan1996** [opencv/opencv#15783]
IDE: Android studio 
computer: windows and mac.
Opencv Version:4.1.1
phone:  荣耀9x

follow this:
https://blog.csdn.net/weixin_43815930/article/details/90516455

When I use 4.1.1 in right config..
![image](https://user-images.githubusercontent.com/41716379/67613834-c7e83980-f7e4-11e9-959c-359fab8bf94a.png)

I search all problems in this error,but can't solve....

finally, in same config , I  replace the 4.1.1 to 3.4.7, all be ok...
This problem bothered me for two days...Now I think is OpenCV's problem...

**Comment by dkurt** [comment]
libc++_shared.so is a part of NDK: https://developer.android.com/ndk/downloads

**Comment by Guanyan1996** [comment]
I konw.but i use 411 not should use ndk

发自我的华为手机


-------- 原始邮件 --------
发件人： Dmitry Kurtaev <notifications@github.com>
日期： 2019年10月26日周六 下午2:11
收件人： opencv/opencv <opencv@noreply.github.com>
抄送： Guanyan1996 <gy_1996@hotmail.com>, Author <author@noreply.github.com>
主 题： Re: [opencv/opencv] Opencv4.1.1 can't use in Android but else version can do in same config.. (#15783)

libc++_shared.so is a part of NDK: https://developer.android.com/ndk/downloads

―

**Comment by alalek** [comment]
Try OpenCV Android samples first.
