### ISSUE TITLE
How to estimate Extrinsic Params about fisheye

### ISSUE THREAD

**Issue by o-ham5** [opencv/opencv#15785]
I want to estimate only Extrinsic Params (fix Intrinsic Params and Ditortion) about fisheye, but I cannot find any method or function to resolve it. 
Is there any way to solve it ?

**Comment by alalek** [comment]
Refer to `solvePnP()` documentation.

**Comment by o-ham5** [comment]
I looked at `solvePnP()` documentation, but I think this function does not support fisheye camera.
Is there any way to resolve this question?
(I looked at `solvepnp.cpp`, then I think that if I change the function `undistortPoints()` to `fisheye::undistortPoints()` in `solvePnPGeneric()`, the estimation (about fisheye camera) will work. Is my perception correct?)

**Comment by iegorval** [comment]
@o-ham5 any chance you were able to solve the issue?
