### ISSUE TITLE
randn and randu unexpected behavior using >1 channel images

### ISSUE THREAD

**Issue by RomanSteinberg** [opencv/opencv#15792]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => Python 3.6

##### Detailed description

Documentation for `cv2.randn` says  _Fills the array with normally distributed random numbers_, so I expect it to fill whole array, but it actually works only with the channel 0. Later it says _dst - output array of random numbers; the array must be pre-allocated and have 1 to 4 channels_, means 3 channel images are allowed and it should fill the whole array. The same for `cv2.randu`.

##### Steps to reproduce

This code

```.py
noise = np.zeros((10,10,3), dtype=np.uint8)
print(cv2.randn(noise, 128, 50)[:,:,1:])
print(cv2.randu(noise, 0, 255)[:,:,1:])
```
prints only zeros.

**Comment by alalek** [comment]
`128` is `Scalar(128, 0, 0, 0)`.

You should specify RNG parameters for all channels:

```.diff
-cv2.randn(noise, 128, 50)
+cv.randn(noise, (128, 128, 128), (50, 10, 20))
```

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by RomanSteinberg** [comment]
@alalek it is not a usage question. Let's look at opencv [documentation](https://docs.opencv.org/4.1.2/d2/de8/group__core__array.html#gaeff1f61e972d133a04ce3a5f81cf6808). Arguments for `randn` are not specified as RNG. Contrary to `randShuffle` routine (it says that interface accepts RNG* argument). So, please, add information to your documentation.

PS: Q/A forum is not working. I mean you can wait for response for a years.

**Comment by sturkmen72** [comment]
>> PS: By the way, Q/A forum is not working. I mean one can wait a response for a years.

it is not true for questions asked well

**Comment by RomanSteinberg** [comment]
Ok. Your dig is accepted. I'll study how to ask questions. And recommend you to go and browse that forum and count how many questions were answered during last month and how many not. You'll find out that it is mostly not working. Or you can think that most of it's visitors are fools and can't ask questions if you prefer this way of thinking.

**Comment by RomanSteinberg** [comment]
Talks about forum are offtopic, actually. So, close the issue when you fix the documentation.
