### ISSUE TITLE
RFC: retire answers.opencv.org and switch to https://stackoverflow.com/questions/tagged/opencv

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#15809]
What do you think?

- [Stackoverflow](https://stackoverflow.com/questions/tagged/opencv) seems much more active (53k questions vs 31k questions)
- stackoverflow is the de-facto industry standard for programming questions
- answers.opencv.org even links to stackoverflow in its faq
- Askbot (which is used by answers.opencv.org) seems to be dead: https://pypi.org/project/askbot/ latest version is from March 1st 2017
- other projects also link to stackoverflow as their official Q&A , e.g. ARCore: https://developers.google.com/ar/community

**Comment by dkurt** [comment]
We also should consider that Stackoverflow historically has more strict rules about asking questions. As for me, https://answers.opencv.org/ let users sometimes ask "how to" questions with a chance to learn something however in case Stackoverflow it's required to do research first.

**Comment by PhilLab** [comment]
Thanks for the comments. What really made sense for me is the argument that stackoverflow discourages "how do I approach XYZ" questions and rather likes "how to I fix XYZ", with some notable exemptions like the [cola can recognition](https://stackoverflow.com/questions/10168686/image-processing-algorithm-improvement-for-coca-cola-can-recognition).

So answers.opencv.org is clearly helpful here. From my standpoint, this issue is ready to be closed and can be done by one of the maintainers.

**Comment by catree** [comment]
In my opinion, the input/feeling of the moderators of [https://answers.opencv.org/questions/](https://answers.opencv.org/questions/) are important.

If they feel that they can't maintain anymore the site (remove the spams, edit the questions, answers the questions, ...) or prefer to step back from the site, it makes sense to look for new moderators. If nobody wants to do these jobs, retiring the site can be considered.

Activity of the site is also important. If there are too much questions asked and no answers, the site is not useful and can bring frustation to the user.

Probably money to keep the servers alive can play a role but I have no idea how much it costs to the organisation.

In any case, keeping the site in a read-only state, archiving the site would be great to keep the useful answers, the links referenced from other sites accessible if the site must be closed.

---

If for some reasons the switch to SO must be made, SO is the right place in my opinion. I don't mind the strict rules. Especially for a collaborative site where few people help many more for free. Discussion about computer vision topics could have a place in a dedicated area:

- [https://dsp.stackexchange.com/](https://dsp.stackexchange.com/)?
- a discourse site like [https://discourse.ros.org/](https://discourse.ros.org/)?
- …

On the other hand, there is a [https://robotics.stackexchange.com/](https://robotics.stackexchange.com/) site and there is a [https://datascience.stackexchange.com/](https://datascience.stackexchange.com/). It would be great to have something similar for computer vision topic: 

- [Stack Exchange site to ask questions about computer vision?](https://stats.meta.stackexchange.com/questions/2794/stack-exchange-site-to-ask-questions-about-computer-vision)
- [Where to ask questions about computer vision?](https://meta.stackexchange.com/questions/284827/where-to-ask-questions-about-computer-vision).
