### ISSUE TITLE
Is cvPOSIT function abandoned by opencv4.0.1?

### ISSUE THREAD

**Issue by jiajiajun** [opencv/opencv#15801]
Thank you for your fabulous work on the version updating of opencv!
When I use opencv4.0.1 for 3D construction, I can't find the cvPOSIT function, which could use in opencv2.4.11, and I can't find any function that does what this function does (solvePNP is similar to it but different, and I can just find it in opencv\sources\modules\calib3d\src\calib3d_c_api.h, but not in build files, and can't use it). Could you please tell me which function has replaced it?
Hoping to hearing from you, and Thanks very much for your help!

**Comment by alalek** [comment]
`cv*` function are from OpenCV 1.x and they are deprecated due migration on C++.
You should migrate on using `solvePnP()` if you want to use modern OpenCV.
