### ISSUE TITLE
MapViewOfFileEx: Attempt to access invalid address. openCV error

### ISSUE THREAD

**Issue by MatejMatula** [opencv/opencv#15807]
I am trying to build OpenCV on windows,i downloaded MinGW with POSIX threads and followed these instructions(https://stackoverflow.com/questions/35984678/use-opencv-with-clion-ide-on-windows). However after running mingw32-make I received an error:

```

> Scanning dependencies of target opencv_core [ 32%] Building CXX object
> modules/core/CMakeFiles/opencv_core.dir/src/algorithm.cpp.obj internal
> error in mingw32_gt_pch_use_address, at
> config/i386/host-mingw32.c:186: MapViewOfFileEx: Attempt to access
> invalid address.
> 
> mingw32-make[2]: ***
> [modules\core\CMakeFiles\opencv_core.dir\build.make:90:
> modules/core/CMakeFiles/opencv_core.dir/src/algorithm.cpp.obj] Error 1
> mingw32-make[1]: *** [CMakeFiles\Makefile2:2020:
> modules/core/CMakeFiles/opencv_core.dir/all] Error 2 mingw32-make: ***
> [Makefile:162: all] Error 2

```
I am not sure what it means and Google finds nothing. Does it mean I have a corrupted OpenCV or where is the problem?

**Comment by alalek** [comment]
> internal error

This usually means that you have corrupted version of MinGW compiler, OOM, lack of storage space.

> pch

Precompiled headers are disabled by default in modern OpenCV (`ENABLE_PRECOMPILED_HEADERS=OFF`)
