### ISSUE TITLE
python-opencv-riscv

### ISSUE THREAD

**Issue by lrakesh24** [opencv/opencv#15810]
hello all,

i am building a caffe on riscv target, for that opencv-python is needed so, clone the sources opencv-python from the git 
https://github.com/skvark/opencv-python.git
but while doing the install
**python 2.7 setup.py install**

getting the error log attached below

 File "setup.py", line 41, in main
    g.run_command(["submodule", "sync"])
  File "/usr/lib/python2.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 632, in run_command
    log_failed_cmd=log_failed_cmd)
  File "/usr/lib/python2.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    **raise InstallationError(exc_msg)**
**pip._internal.exceptions.InstallationError**: Command errored out with exit status 1: git submodule sync Check the logs for full command output.

need a solution

**Comment by alalek** [comment]
Mentioned repo contains submodules, so probably you should use this command for cloning:
```
git clone --recursive URL
```

BTW, Actual build instructions are always available on CI systems - check Travis/Appveyor build logs.
