### ISSUE TITLE
undefined symbol: _Z10cvIplImageRKN2cv3MatE

### ISSUE THREAD

**Issue by huangjin15** [opencv/opencv#15815]
undefined symbol: _Z10cvIplImageRKN2cv3MatE

**Comment by huangjin15** [comment]
![7BBAA4911181F0BBE479107C8C15F531](https://user-images.githubusercontent.com/34228720/67909903-e3c05680-fbbb-11e9-9b64-b97749d081ed.jpg)

**Comment by alalek** [comment]
Probably you have mess with different OpenCV versions on your machine:
- built with one version (`CXXFLAGS=-H` would help with investigation)
- load another (`LD_DEBUG=libs` env may help with investigation)

We can't fix that from OpenCV side.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
