### ISSUE TITLE
Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'validateInputImageSize' | Giving me headaches

### ISSUE THREAD

**Issue by deimsdeutsch** [opencv/opencv#15829]
In my python script i am loading a 538 MB JPG file.

```
    img = cv2.imread(img_path)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgcodecs/src/loadsave.cpp:75: error: (-215:Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'validateInputImageSize'

```

Any idead how to override this limitation ?

**Comment by alalek** [comment]
Documentation says:
> By default number of pixels must be less than 2^30. Limit can be set using system variable OPENCV_IO_MAX_IMAGE_PIXELS

**Comment by tongpinmo** [comment]
> Documentation says:
> 
> > By default number of pixels must be less than 2^30. Limit can be set using system variable OPENCV_IO_MAX_IMAGE_PIXELS
Hi , my opencv version is 3.3.1.The problem is : loadsave.cpp:74: error: (-215) pixels <= (1<<30) in function validateInputImageSize.
I don't know how to set the system variable:OPENCV_IO_MAX_IMAGE_PIXELS

**Comment by alalek** [comment]
> cv2.error: OpenCV(4.1.1)
> my opencv version is 3.3.1

You need to upgrade or use custom own build from sources.

> I don't know how to set the system variable

Google for "environment variable".

**Comment by tongpinmo** [comment]
> > cv2.error: OpenCV(4.1.1)
> > my opencv version is 3.3.1
> 
> You need to upgrade or use custom own build from sources.
> 
> > I don't know how to set the system variable
> 
> Google for "environment variable".

ok,you mean i can upgrade the opencv version?

**Comment by yasohasakii** [comment]
> Documentation says:
> 
> > By default number of pixels must be less than 2^30. Limit can be set using system variable OPENCV_IO_MAX_IMAGE_PIXELS

Hi!, the image size is 28672*103424, I have change  CV_IO_MAX_IMAGE_PIXELS=18500000000 in `~/.bashrc` and source it,but still got `cv2.error: /io/opencv/modules/imgcodecs/src/loadsave.cpp:74: error: (-215) pixels <= (1<<30) in function validateInputImageSize`. How to fix it?

**Comment by jtoa2** [comment]
> > cv2.error: OpenCV(4.1.1)
> > my opencv version is 3.3.1
> 
> You need to upgrade or use custom own build from sources.
> 
> > I don't know how to set the system variable
> 
> Google for "environment variable".

Sorry I'm also stuck here. Is there a way of setting this from within a jupyter notebook for example?

**Comment by Sampath3128** [comment]
> > Documentation says:
> > > By default number of pixels must be less than 2^30. Limit can be set using system variable OPENCV_IO_MAX_IMAGE_PIXELS
> 
> Hi!, the image size is 28672*103424, I have change CV_IO_MAX_IMAGE_PIXELS=18500000000 in `~/.bashrc` and source it,but still got `cv2.error: /io/opencv/modules/imgcodecs/src/loadsave.cpp:74: error: (-215) pixels <= (1<<30) in function validateInputImageSize`. How to fix it?

**Comment by jeremyJJB** [comment]
Hi, 

I ran into the same issues and found this as a [solution](https://stackoverflow.com/questions/58070174/overcome-opencv-cv-io-max-image-pixels-limitation-in-python)

which should work inside a jupyter notebook. Specifically from that [link](https://stackoverflow.com/questions/58070174/overcome-opencv-cv-io-max-image-pixels-limitation-in-python) use the following,
`os.environ["OPENCV_IO_MAX_IMAGE_PIXELS"] = pow(2,40).__str__()`
`import cv2 `
you can replace 40 with whatever number you need. However with this solution you need to be careful of bugs resulting in other cv2 calls when you override the defaults. See the this [discussion](https://github.com/opencv/opencv/issues/10211).

**Comment by apal6** [comment]
Hi,

I tried all the solutions mentioned above and still couldn't fix this. Can someone help?

`CV_IO_MAX_IMAGE_PIXELS in function 'validateInputImageSize'`

Thank you!
