### ISSUE TITLE
org.opencv.dnn: dnn::readNet_14() caught cv::Exception: OpenCV(4.1.1)

### ISSUE THREAD

**Issue by merria28** [opencv/opencv#15825]
I wanna use dnn in android studio, and an error shows up after "Dnn.readNet("F:/text_detect/models/east/frozen_east_text_detection.pb") "

The whole code is :

public class MainActivity extends AppCompatActivity {

    private ImageView mImageView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // opencv 初始化
        OpenCVNativeLoader loader = new OpenCVNativeLoader();
        loader.init();

        //String model = getPath("model.net", getApplicationContext());

        String model = "F:/text_detect/models/east/frozen_east_text_detection.pb";
        TextView tv = findViewById(R.id.textView);
        tv.setText(model);

        // test dnn

        Net net = Dnn.readNet(model);
	}
}

The Logcat is :

2019-11-01 10:46:26.291 18419-18419/? E/cv::error(): OpenCV(4.1.1) Error: Unspecified error (FAILED: fs.is_open(). Can't open "F:/text_detect/models/east/frozen_east_text_detection.pb") in ReadProtoFromBinaryFile, file /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1132
2019-11-01 10:46:26.293 18419-18419/? E/org.opencv.dnn: dnn::readNet_14() caught cv::Exception: OpenCV(4.1.1) /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "F:/text_detect/models/east/frozen_east_text_detection.pb" in function 'ReadProtoFromBinaryFile'
2019-11-01 10:46:26.293 18419-18419/? D/AndroidRuntime: Shutting down VM
2019-11-01 10:46:26.294 18419-18419/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.opencv, PID: 18419
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.opencv/com.example.opencv.MainActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "F:/text_detect/models/east/frozen_east_text_detection.pb" in function 'ReadProtoFromBinaryFile']

I have searched at https://answers.opencv.org/questions, other people can call normally function like"readNet".
Functions: readNet,readNetFromTensorflow, redNetFromDarknet, are all crashed.

opencv 4.1.1 android sdk from https://sourceforge.net/projects/opencvlibrary/files/4.1.1/

I donot know why is the error, or any configure should set? 

(This web  https://answers.opencv.org/questions I can't ask question in china)

**Comment by alalek** [comment]
> android
> Can't open "F:/text_detect/models/east/frozen_east_text_detection.pb"

Where do you see Windows paths on Android?

---

Take a look on existed OpenCV samples first (files handing implementation is not the best, but it works).

**Comment by merria28** [comment]
I use an android emulator in android studio

**Comment by merria28** [comment]
I read an image from windows local place, my emulator can work well, like following:

import org.opencv.android.Utils;
import org.opencv.imgproc.Imgproc;
import org.opencv.osgi.OpenCVNativeLoader;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;
……
String imPath = "E:/images/LinuxLogo.jpg";
Mat im = Imgcodecs.imread(imPath, Imgcodecs.IMREAD_COLOR);

I donot know why "reaNet" cannot load from windows local place with a avd emulator

**Comment by alalek** [comment]
Good practice is adding checks for received results (don't rely on exceptions).

**Comment by merria28** [comment]
Firstly thanks very much!
Now I upload my pb file onto my emulator sdcard file, then I try to load again like this:
String sdcard_path = Environment.getExternalStorageDirectory().getPath();
 String model = sdcard_path + "/Download/frozen_east_text_detection.pb";
 Net net = Dnn.readNet(model);

It still not work:
error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/storage/emulated/0/Download/frozen_east_text_detection.pb" in function 'ReadProtoFromBinaryFile'

**Comment by Rolan10** [comment]
Same issue here, did you find how to make it work @merria28?

**Comment by vanpham981986** [comment]
display as desktop

**Comment by DarshanChhatrala** [comment]
why not read 'Read Proto From binary File' this file ?
