### ISSUE TITLE
rename a parameter R to H in AffineWarper member declarations

### ISSUE THREAD

**Issue by sergii-bond** [opencv/opencv#15824]
##### System information (version)
- OpenCV => 4.1.2

##### Detailed description

It would be more obvious if the homography matrix were named H instead of R in `AffineWarper` class [here](https://github.com/opencv/opencv/blob/469addeca334d384178bfe2de08513628d261afa/modules/stitching/include/opencv2/stitching/detail/warpers.hpp#L224). 
Also because of class inheritance the documentation renders it as rotation matrix:

![image](https://user-images.githubusercontent.com/19783366/67989584-85fa3180-fbf0-11e9-836a-d638dd41e5a1.png)

In the function definition [here](https://github.com/opencv/opencv/blob/469addeca334d384178bfe2de08513628d261afa/modules/stitching/src/warpers.cpp#L311) it is named H. So the declaration in the header is slightly inconsistent with its definition.

**Comment by alalek** [comment]
Yes, it accepts 3x3 matrix as affine transformation in homogeneous coordinates.
Feel free to propose PR onto [3.4 branch](https://github.com/opencv/opencv/wiki/Branches)

May be it make sense to rename "R" into some generic "camera extrinsic parameters" which may cover:
- classical stitching with rotation-only transformations
- "scan"-based affine transformations (with corresponding estimators)

/cc @hrnr
