### ISSUE TITLE
Process finished with exit code -1073741515 (0xC0000135)

### ISSUE THREAD

**Issue by sleeplessai** [opencv/opencv#15830]
#### CLion build with CMake

I had tried both self-built and pre-built OpenCV 4.1.1 libs with Cmake build in CLion.
After successfully built, I got the error during runtime.

> Process finished with exit code -1073741515 (0xC0000135)

And I don't know how to solve this.

- OpenCV => 4.1.1 Windows pre-built self-built
- Operating System / Platform => Windows 10 Build 18970
- Compiler => MSVC 15（Visual Studio 2017)

#### Detailed description

```cpp
void OpenCVTest() {
  std::string path = "../1.jpg";
  cv::Mat m = cv::imread(path);
  if (!m.data) {
    std::cout << "no data read" << std::endl;
    return;
  }
  cv::imshow("imshow", m);
  cv::waitKey(0);
}
```

```cmake
cmake_minimum_required(VERSION 3.15)
project(untitled)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_PREFIX_PATH D:/opencv/build/x64/vc15/lib)
find_package(OpenCV REQUIRED)
add_executable(${PROJECT_NAME} main.cpp)
include_directories(${OpenCV_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS})
```

How to solve this ?

**Comment by sleeplessai** [comment]
Currently I solved this problem though vcpkg on Windows installing opencv4[*] series packages.
What's different between self-built, official release and vcpkg-installed package?

**Comment by alalek** [comment]
> 0xC0000135

It is `STATUS_DLL_NOT_FOUND`.
Looks like it is configuration issue, which can't be fixed from OpenCV side.
