### ISSUE TITLE
TypeError: Expected Ptr<cv::UMat> for argument '%s'

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#15833]
This is about the uninterpolated `'%s'` in that error message.

Expected behavior: error message says which argument. In the following case it should have been interpolated to read `'img'`.

Run this to reproduce:
```py
import cv2 as cv
cv.line([], (0,0), (10,10), (0,0,255), 2)
# TypeError: Expected Ptr<cv::UMat> for argument '%s'
cv.circle([], (0,0), 10, (0,0,255), 2)
# TypeError: Expected Ptr<cv::UMat> for argument '%s'
```

Other APIs use the same error reporting scheme but interpolate properly. This bug is probably situated in or near the API implementations themselves.

compare to `cv::rectangle`, which has a different error reporting scheme:
```py
cv.rectangle([], (0,0), (10,10), (0,0,255), 2)
# TypeError: an integer is required (got type tuple)
```

**Comment by devinhunsberger** [comment]
I recently installed OpenCV and am getting this error, I'll uninstall and reinstall, but as of now I'm still getting the error.

**Comment by Masao-Taketani** [comment]
For my case, it's soooooo dumb...., but the same error message 
> # TypeError: Expected Ptr<cv::UMat> for argument '%s'
happened when I tried to perform a look-up table transformation for Image object obtained by PIL.Image.open().

**Comment by alalek** [comment]
Error message is not correct, but there is still an error in your code with passed parameters types (as your wrote 'Image object' which is not supported).
See #15918

**Comment by Masao-Taketani** [comment]
@alalek 
Thank you for your reply!
Sorry I think I should've said it more clearly.
What I meant to say was if you pass the 'Image object' created by PIL.Image.Open() into src(the first parameter of cv2.LUT) by mistake, you get the same error message.
That was my dumb mistake... hahaha
That was what I meant.
