### ISSUE TITLE
dense_flow_gpu.cpp

### ISSUE THREAD

**Issue by SKBai1996** [opencv/opencv#15837]
when I finish cmake .. I use "make" to compile. when it runed in 81%, I got the issue:
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `calcDenseWarpFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_warp_flow_gpu.cpp:(.text+0x2456): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_warp_flow_gpu.cpp:(.text+0x24cb): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_warp_flow_gpu.cpp:(.text+0x251a): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_warp_flow_gpu.cpp:(.text+0x2de0): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
dense_warp_flow_gpu.cpp:(.text+0x377a): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, int, int)':
dense_flow_gpu.cpp:(.text+0x82b): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x8a0): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x8ef): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x12eb): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_flow_gpu.cpp:(.text+0x1b61): undefined reference to `cv::cudacodec::createVideoReader(cv::String const&)'
dense_flow_gpu.cpp:(.text+0x1c8e): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x1d03): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x1d52): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x258d): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_warp_gpu.dir/build.make:143: recipe for target 'extract_warp_gpu' failed
make[2]: *** [extract_warp_gpu] Error 1
collect2: error: ld returned 1 exit status
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/extract_gpu.dir/build.make:143: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
[100%] Linking CXX shared library libpydenseflow.so
[100%] Built target pydenseflow
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Could you help me.

**Comment by alalek** [comment]
> libdenseflow.a
> pydenseflow

What is that?

**Comment by SKBai1996** [comment]
This is the problem of my own download opencv, the dense flow needs cuda module, but I didn't have it. So I reinstalled the opencv, and in cmake, I use the command  as follow:
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=ON -D WITH_CUBLAS=ON -D BUILD_TIFF=ON -D WITH_CUDA=ON -D WITH_CUFFT=ON  WITH_NVCUVID=ON -D OPENCV_EXTRA_MODULES_PATH=./opencv-3.4.6/opencv_contrib/modules ..
The other commands as usual, I sincerely can give someone else help.
