### ISSUE TITLE
Traceback (most recent call last):   File "g:/video_capture/capture.py", line 25, in <module>     (_,cnts,_)=cv2.findContours(np.array(thresh_frame.copy),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE) TypeError: Expected Ptr<cv::UMat> for argument '%s'

### ISSUE THREAD

**Issue by Mehroz456** [opencv/opencv#15846]
this is my code

import cv2, time

video = cv2.VideoCapture(0,cv2.CAP_DSHOW)
first_frame=None

while True:
    check, frame = video.read()

    print(check)
    print(frame)

    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray=cv2.GaussianBlur(frame,(21,21),0)

    if first_frame is None:
        first_frame=gray
        continue

    delta_frame=cv2.absdiff(first_frame,gray)
    thresh_frame=cv2.threshold(delta_frame, 30, 255,cv2.THRESH_BINARY)[1]
    thresh_frame=cv2.dilate(thresh_frame, None, iterations=2)
    
    (_,cnts,_)=cv2.findContours(thresh_frame.copy,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

    for contour in cnts:
        if cv2.contourArea(contour) < 1000:
            continue
        (x,y,w,h) = cv2.boundingRect(contour)
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,225,0),3)

    cv2.imshow("Gray_Image",gray)
    cv2.imshow("Delta_image",delta_frame)
    cv2.imshow("Threshold_frame",thresh_frame)
    cv2.imshow("color frame",frame)

    key=cv2.waitKey(1)
    print(gray)
    print(delta_frame)

    if key==ord("q"):
        break

video.release()
cv2.destroyAllWindows

ppllzz help!!

**Comment by berak** [comment]
error is on your side, see:

    a = np.zeros((5,5,3),np.uint8)
    z = a.copy
    print(type(z))
    <type 'builtin_function_or_method'>

so, `np.array(thresh_frame.copy)` is just junk.

**Comment by Mehroz456** [comment]
> error is on you're side, see:
> 
> ```
> a = np.zeros((5,5,3),np.uint8)
> z = a.copy
> print(type(z))
> <type 'builtin_function_or_method'>
> ```
> 
> so, `np.array(thresh_frame.copy)` is just junk.

it also didn't work without the np.array try it it gives the same error!!

ppllzz  try i tried alot fixing it

**Comment by berak** [comment]
@Mehroz456 

`thresh_frame` (if valid) would have been all ever needed here, 
`thresh_frame.copy()`  (with braces) would have been, what you intended 
(the return value of the function being called, not the function pointer/object)

**Comment by Mehroz456** [comment]
> @Mehroz456
> 
> `thresh_frame` (if valid) would have been all ever needed here,
> `thresh_frame.copy()` (with braces) would have been, what you intended
> (the return value of the function being called, not the function pointer/object)

if i do this it gives me this error


Traceback (most recent call last):
  File "g:/video_capture/capture.py", line 24, in <module>
    (_,cnts,_)=cv2.findContours(thresh_frame,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cv2.error: OpenCV(4.1.2) D:\Build\OpenCV\opencv-4.1.2\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
