### ISSUE TITLE
warning: setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by bencha30** [opencv/opencv#15858]
Hello, got this warning, trying to use cuda to run my model.
##### System information (version)

- OpenCV => 4.1.2 (installed on Nov. 11, 2019 via cmake)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
-GPU:Nvidia RTX2060
-CudaToolKit =10.0
-Python =>3.7

1. installed opencv with cuda via cmake
2. run an inference (moblinetv1) using dnn

     cvNet.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
    cvNet.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
    cvOut = cvNet.forward()

got a warning:

dnn.cpp (1314) cv::dnn::dnn4_v20191024::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

Please advise how to build dnn module with CUDA backend.

thank you..

**Comment by bencha30** [comment]
solved! rebuild opencv removed cuda arch bin version  < 5.3

**Comment by ankit12321** [comment]
@bencha30 : Could you help with the solution?  i am getting the same error and was not able to interpret the above sol "rebuild opencv removed cuda arch bin version < 5.3"

**Comment by bencha30** [comment]
If you install your opencv through cmake, remove the arch bin version below 7 on the configuration file.
Note: cuda will not work if you install your opencv using pip /sudo apt install, use cmake instead.

**Comment by iqorqua** [comment]
@bencha30 : Hi! I have the save issue...
Can you help? 
Here is my build info. Whats wrong with it?
`General configuration for OpenCV 4.2.0-dev =====================================
  Version control:               4.2.0-85-g8b3042da63

  Extra modules:
    Location (extra):            /media/ssd/test/opencv_contrib/modules
    Version control (extra):     4.2.0-12-gc8b405eb

  Platform:
    Timestamp:                   2020-01-22T10:02:24Z
    Host:                        Linux 4.9.140-tegra aarch64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    NEON FP16
      required:                  NEON
      disabled:                  VFPV3

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /usr/bin/c++  (ver 7.4.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--gc-sections  
    Linker flags (Debug):        -Wl,--gc-sections  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/aarch64-linux-gnu
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cvv java js matlab ovis python2 viz
    Applications:                tests perf_tests examples apps
    Documentation:               NO
    Non-free algorithms:         NO

  GUI: 
    GTK+:                        YES (ver 3.22.30)
      GThread :                  YES (ver 2.56.4)
      GtkGlExt:                  NO
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/aarch64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/aarch64-linux-gnu/libjpeg.so (ver 80)
    WEBP:                        /usr/lib/aarch64-linux-gnu/libwebp.so (ver encoder: 0x020e)
    PNG:                         /usr/lib/aarch64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/aarch64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      YES (2.2.5)
    FFMPEG:                      YES
      avcodec:                   YES (57.107.100)
      avformat:                  YES (57.83.100)
      avutil:                    YES (55.78.100)
      swscale:                   YES (4.8.100)
      avresample:                YES (3.7.0)
    GStreamer:                   YES (1.14.5)
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            TBB (ver 2017.0 interface 9107)

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  YES (carotene (ver 0.0.1))
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS)
    NVIDIA GPU arch:             72
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 7.6.3)

  OpenCL:                        YES (no extra features)
    Include path:                /media/ssd/turrel/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /media/ssd/turrel/env/bin/python3 (ver 3.6.9)
    Libraries:                   /usr/lib/aarch64-linux-gnu/libpython3.6m.so (ver 3.6.9)
    numpy:                       /media/ssd/turrel/env/lib/python3.6/site-packages/numpy/core/include (ver 1.18.1)
    install path:                lib/python3.6/site-packages/cv2/python-3.6

  Python (for build):            /media/ssd/turrel/env/bin/python3

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /usr/local`

**Comment by iqorqua** [comment]
solved with this guy help 
https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

**Comment by ckchin97** [comment]
@iqorqua may i know how you solve the problem?

**Comment by baolong97-hust** [comment]
@iqorqua I think maybe you choose NVIDIA GPU arch = 7.2 but your hardware is not compatible with it. You can search here to finh your compatible Nvida gpu arch.
https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by ZIKO94ZIKO** [comment]
any update ??

**Comment by iqorqua** [comment]
> @iqorqua may i know how you solve the problem?

check previous comment, there is link to article and use that step by step
i`m strongly believe that compilation process was uncorrect

**Comment by zongoalbert** [comment]
should i reinstall opencv? ?

**Comment by iqorqua** [comment]
> @iqorqua I think maybe you choose NVIDIA GPU arch = 7.2 but your hardware is not compatible with it. You can search here to finh your compatible Nvida gpu arch.
> https://en.wikipedia.org/wiki/CUDA#GPUs_supported

i think so too, because i checked my params more attentively, then recompiled project and now everything is working like a charm

**Comment by iqorqua** [comment]
> should i reinstall opencv? ?

pretty sure that you need to do that.
uninstall previous version and make sure that there no its remains in the system, than you can use that guide what i mentioned before in my comments.

**Comment by zongoalbert** [comment]
@iqorqua  ifi uninstall opencv,nothing be happening to installation of CUDA?

**Comment by iqorqua** [comment]
> @iqorqua ifi uninstall opencv,nothing be happening to installation of CUDA?

nope

**Comment by zongoalbert** [comment]
@iqorqua  i follow the tutorial , and i have the same problem  : [ WARN:0] global /io/opencv/modules/dnn/src/dnn.cpp (1363) setUpNet DNN module was not built with CUDA backend; switching to CPU

**Comment by Brittanygirl** [comment]
> solved! rebuild opencv removed cuda arch bin version < 5.3



> If you install your opencv through cmake, remove the arch bin version below 7 on the configuration file then rebuild/reinstall your opencv.
> Note: cuda will not work if you install your opencv using pip /sudo apt install, use cmake instead.


> If you install your opencv through cmake, remove the arch bin version below 7 on the configuration file then rebuild/reinstall your opencv.
> Note: cuda will not work if you install your opencv using pip /sudo apt install, use cmake instead.



> 如果通过cmake安装opencv，请删除配置文件中低于7的Arch Bin版本，然后重新构建/重新安装opencv。
> 注意：如果您使用pip / sudo apt install安装opencv，请使用cmake代替cuda。

Can I solve it in windows?

**Comment by rodolfobetanzos** [comment]
I have tried to solve this and I  have not had sucess :/
I am working with a Jetson Nano with a version 5.3 for CUDA ... I have followed the next tutorial and I have obtained the same fail results.
https://www.pyimagesearch.com/2020/03/25/how-to-configure-your-nvidia-jetson-nano-for-computer-vision-and-deep-learning/

**Comment by bencha30** [comment]
Jetson nano with opencv cuda will not work,  been there  done that, it won't work. Better use tensorrt if you want to speed up your inference.

**Comment by dipampatel18** [comment]
@rodolfobetanzos @bencha30 I also had the same issue. But I think the problem is with the cuDNN version (not detected) in the latest Jetpack 4.4 for Nano. Downgrade your Jetpack to 4.3 and have CUDA_ARCH_BIN=5.3,6.0,6.1,6.2,7.0,7.2,7.5 and CUDA_ARCH_PTX=7.5. It will work for sure.
Make sure to verify them both in the build info as well as the cuDNN version before you make it. Also, the make will take a very long long time with intermediate freezes. So just unplug it and make it again.

**Comment by tabarkarajab** [comment]
> solved! rebuild opencv removed cuda arch bin version < 5.3

Hi, can you please help me in this? I'm having the same problem.

**Comment by ismet-dagli** [comment]
> solved with this guy help
> https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

I followed here but I am getting the same error :/

**Comment by NuwanMadhusanka0417** [comment]
I solved that error by removing  " -D CUDA_ARCH_BIN=6.1  " part and build OpenCV/build again. 

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=OFF -D OPENCV_ENABLE_NONFREE=ON -D WITH_CUDA=ON -D WITH_CUDNN=ON -D OPENCV_DNN_CUDA=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules -D HAVE_opencv_python3=ON -D PYTHON_EXECUTABLE=~/env/bin/python -D BUILD_EXAMPLES=ON -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.0 -D CUDNN_INCLUDE_DIR=/usr/include -DCUDNN_LIBRARY=/usr/local/cuda/lib64/libcudnn.so.8 -D CUDNN_VERSION=8.0.3.33 ..

**Comment by laygond** [comment]
I found the solution to my problem [here](https://github.com/torch/torch7/issues/1190). It was switching to CPU because the CUDA version I had was not corresponding to the architecture of my RTX 2080 Ti. 
So, in my case, the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one).  I ended up upgrading to cuda 10 following [this tutorial](https://www.pyimagesearch.com/2019/12/09/how-to-install-tensorflow-2-0-on-ubuntu/) (Extra Note from tutorial: ignore accelerated driver when prompted from the nvidia installer since you already updated the driver manually in the previous step). Once the previous is properly configured you can follow https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/ which was suggested by @iqorqua

**Comment by yassinesefrioui** [comment]
please, how i can remove the arch bin version below 7 on the config file ?  @bencha30

**Comment by Moshiur-Rahman-Faisal** [comment]
> 2\. cvNet.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
>     cvNet.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
>     cvOut = cvNet.forward()

follow this tutorial: https://www.youtube.com/watch?v=YsmhKar8oOc
