### ISSUE TITLE
InferenceEngine: Myriad: Reduce RAM usage

### ISSUE THREAD

**Issue by r0l1** [opencv/opencv#15859]
When loading a model (tensorflow, darknet) to a myriad VPU, following happens as I understood:
1. OpenCV reads the model and converts it to the IE representation.
2. The model will be transferred to the VPU.
3. Ready to accept forward requests.

Is it possible to release the converted model from the RAM, because it is already loaded into the VPUs RAM? Or did I misunderstand the whole concept? Due to limited RAM on our execution nodes, we would like to reduce the memory overhead required for bigger yolo networks.

Kind Regards
Roland

**Comment by dkurt** [comment]
@r0l1, please do some research. Provide memory estimations for the model like here: https://github.com/opencv/opencv/pull/13716. You may also use peaks estimations by reading a content of `/proc/self/status`: `VmHWM` for peak and `VmRSS` for permanent estimations.

**Comment by r0l1** [comment]
@dkurt thanks. I'll post some more information soon!

**Comment by r0l1** [comment]
Here are the memory measurement results for a YOLOv3 model:
- OpenCV 4.2.1
- DLDT 2019 R3

| OpenCV Build         | DNN Backend      | DNN Target | VmHWM   | VmRSS  |
|----------------------|------------------|------------|---------|--------|
| OpenCV without IE    | OPENCV           | CPU        | 522404  | 522404 |
| OpenCV build with IE | OPENCV           | CPU        | 1018532 | 787408 |
| OpenCV build with IE | INFERENCE_ENGINE | MYRIAD     | 899088  | 899088 |

We have 2GB RAM on our embedded Intel platform and three models are loaded and handled by the Myriad Chip. Due to frame grabbing and other image manipulation tasks, we are running short on memory. I'll continue digging into the DNN source code and try to understand, if it's possible to release some unused memory for the Myriad target. Would be grateful, if you could leave some hints.

Thank you

**Comment by r0l1** [comment]
Update: Using the inference engine directly results into a ~55% less memory usage. I'll post some detailed results soon.

**Comment by dkurt** [comment]
@r0l1, see related issue: https://github.com/opencv/opencv/issues/13413.

The thing is that IE loads FP16 model but OpenCV imports FP32 and converts it to FP16 in runtime when you choose MYRIAD target.

**Comment by r0l1** [comment]
@dkurt this happens also with CPU target (FP32). Please reopen. I'll post some more infos soon.
