### ISSUE TITLE
Talos security advisory for Opencv (TALOS-2019-0852, 0853)

### ISSUE THREAD

**Issue by CiscoTalos** [opencv/opencv#15857]
The Cisco Talos team found two security vulnerabilities affecting Opencv OpenCV 4.1.0. As this is a sensitive security issue, this message is to request a point of contact to report the detailed report. 
Email requests to admin at opencv.org were also sent.

**Comment by alalek** [comment]
@CiscoTalos Thank you for the detailed report!

We are able to reproduce problem on OpenCV 4.x releases (up to the latest 4.1.2 release).
OpenCV 3.4.8 is not affected by mentioned problems.

**Comment by CiscoTalos** [comment]
Thanks for the update.  Do you have a timeline for public disclosure?

**Comment by alalek** [comment]
Next release is planned in the end of the year (before 25 Dec).
It would be nice to postpone full disclosure till that.

**Comment by CiscoTalos** [comment]
The issue reached 90 days on Oct 22 and we extended through end of this month (November).  We can issue a final extension to 2019-12-13 which is 30 days from today for public disclosure.

**Comment by CiscoTalos** [comment]
Hello,

If you have an exact date for the release at this time, we will make note and provide an additional extension.  You noted before Dec 25, 2019, so it would help to know the exact date.

**Comment by CiscoTalos** [comment]
We provided the two week extension to the last communicated date for public disclosure postponement.  Please advise status and/or URL for public release.  Thanks

**Comment by alalek** [comment]
Thank you!
OpenCV 4.2.0 has been released with fix: https://github.com/opencv/opencv/releases/tag/4.2.0
