### ISSUE TITLE
Retrained Inception_v2 model in opencv error

### ISSUE THREAD

**Issue by RaveIa** [opencv/opencv#15863]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows 10 64 Bit

##### Detailed description

I've retrained cnn_inception_v2_coco for object detection. The training went fine, I ran the test script on some images and it worked. I wanted to use this new retrained model on OpenCV. I followed the insctruction [here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) :
The pbtxt was created, but when running the openCV detection script I get the error :

Process finished with exit code -1073741819 (0xC0000005)

##### Steps to reproduce

**frozen_inference_graph.pb**  Generated after training
**Graph.pbtxt** Generated with tf_text_graph_ssd.py

As the files are big for Github I hosted them on google [drive](https://drive.google.com/drive/folders/1uPEi6x3TsDAnzCYIK6eZoBsRbAVCFfY5?usp=sharing)

I'm stuck since a while, I searched online but couldn't find a solution. To make sure that I wasn't doing anythong wrong while generating the pbtxt,I did the same steps using the original frozen_inference_graph.pb and .config files of cnn_inception_v2_coco model and it worked.

**Comment by dkurt** [comment]
Please choose different archive extension. I'm not able to unpack it.

**Comment by RaveIa** [comment]
Thank you for the fast answer. I took the files out of the archive, there should be .pb  .pbtxt and  .config at the root of the drive folder.

**Comment by RaveIa** [comment]
I did some experimenting around and I guess the issue comes from Tensorflow 1.15. I don't exactly why .. Any luck figuring it out @dkurt ?

**Comment by dkurt** [comment]
@RaveIa, Hi! Can you please test the following PR https://github.com/opencv/opencv/pull/15986?

Or you can share some test image and expected output from TensorFlow so I can run it with OpenCV and check the results.

**Comment by RaveIa** [comment]
Hi @dkurt, thank you for your help! 
I couldn't find tf_importer.cpp, I've only installed Opencv-python. 
I retrained the model with another version of Tensorflow (1.10) and ran it on OpenCV without a problem.

I Uploaded on the same google [drive](https://drive.google.com/drive/folders/1uPEi6x3TsDAnzCYIK6eZoBsRbAVCFfY5) a test image + the expected result from Tensorflow.

**Comment by dkurt** [comment]
@RaveIa, thanks for the details!

Tested with TensorFlow and OpenCV code from https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API (**NOTE**: with BGR input channels order, so comment `inp = inp[:, :, [2, 1, 0]]`):

TensorFlow output:
```
score, left, top, right, bottom
0.9254, 503.5272, 125.8555, 876.3299, 605.9547
```

OpenCV output (for `swapRB=False`):
```
0.9254, 503.5271, 125.8555, 876.3298, 605.9547
```
![img](https://user-images.githubusercontent.com/25801568/69538552-a02af380-0f93-11ea-9478-70379acf0168.png)

**Comment by RaveIa** [comment]
@dkurt Great work!
So this result is with generating .pbtxt with the modified tf_importer.cpp and tf_text_graph_ssd?

**Comment by dkurt** [comment]
@RaveIa, that's right. Only the changes from https://github.com/opencv/opencv/pull/15986.

**Comment by RaveIa** [comment]
@dkurt, hi again. This might seem like a stupid question, but I have to ask it.

How can I get the modified files? I installed Opencv-python by pip, I can't find the opencv directory or the tf_importer.cpp file on my computer (windows), even with search. Do I have to install openCV from source using Cmake?

Thanks in advance

**Comment by dkurt** [comment]
@RaveIa, Please try this workaround for now:

1) Change `tf_text_graph_ssd.py` as proposed in the PR https://github.com/opencv/opencv/pull/15986. Generate a `.pbtxt` file
2) Open `.pbtxt` file and replace all the `op: "FusedBatchNormV3"` to `op: "FusedBatchNorm"`.

**Comment by RaveIa** [comment]
Hats off to you @dkurt. Thanks a lot!
