### ISSUE TITLE
resultRoiIntersection bottom right corner issue

### ISSUE THREAD

**Issue by lizix7** [opencv/opencv#15862]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Mac OS
- Compiler => g++

##### Detailed description

In resultRoiIntersection, the bottom right corner is wrong.
`br.x = std::min(br.x, corners[i].x + sizes[i].width);`

 `br.y = std::min(br.y, corners[i].y + sizes[i].height);`

##### Steps to reproduce

Just run the function and report bottom right corner. It will give you exactly size.width and size.height, which is not supposed to exist.

**Comment by alalek** [comment]
What do you mean?
Provide complete reproducer with actual / expected results.

**Comment by dkurt** [comment]
Closing it unless we have a reproducer (expected behavior in this case)
