### ISSUE TITLE
OpenCV using Movidius NCS2 error using Darknet

### ISSUE THREAD

**Issue by light00l** [opencv/opencv#15870]
I am trying to perform  my custom object detector using the Intel Movidius Neural Compute Stick 2. The network that I am using is based on YOLO, and therefore has the graph structure saved as a `.cfg` file and the weights as a `.weights` file. I use OpenCV which was installed with Openvino.

More information : 

- Operating System -> Ubuntu 18.04.3 LTS
- OpenCV => 4.1.2

My code is here : 
```python
   import cv2 as cv
   modelConfiguration_big = "yolov3.cfg"
   modelWeights_big = "yolov3.weights"
   # load network
   net = cv.dnn.readNetFromDarknet(modelConfiguration_big, modelWeights_big)
   net.setPreferableBackend(cv.dnn.DNN_BACKEND_INFERENCE_ENGINE)
   net.setPreferableTarget(cv.dnn.DNN_TARGET_MYRIAD)
   # perform inference
   frame  = cv2.imread('img_path.jpg')
   blob = cv.dnn.blobFromImage(frame, 1/255, (inpWidth, inpHeight), [0,0,0], 1, crop=False)
   net.setInput(blob)
   outs = net.forward(getOutputsNames(net))
```

On running the code, I get the following error:
```python
Traceback (most recent call last):
  File "Detector_1.py", line 236, in <module>
    outs = net_big.forward(getOutputsNames(net_big))
cv2.error: OpenCV(4.1.2-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Unsupported primitive of type: OpenCVLayer name: yolo_82 in function 'initPlugin'
```

If I change the inference target to `cv2.dnn.DNN_TARGET_CPU` the model works fine.

**Comment by dkurt** [comment]
Can reproduce it with OpenVINO 2019R3.

Please try to build OpenCV with IE backend from master branch instead: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend

**Comment by light00l** [comment]
@dkurt II already reproduced it with OpenVINO 2019R3 and I tryed to build OpenCV with IE backend from that master branch but don't work.

**Comment by dkurt** [comment]
Please check OpenCV source:
```python
import cv2 as cv
print(cv.__file__)
```
it should be a custom one.

**Comment by dkurt** [comment]
master branch working
