### ISSUE TITLE
Windows installation script fails

### ISSUE THREAD

**Issue by michael-angelozzi** [opencv/opencv#15872]
##### System information (version)
Following this installation guideline:
https://docs.opencv.org/4.1.2/d3/d52/tutorial_windows_install.html
And the gitbash script fails with the following:

    $ ./installOCV.sh
    cloning opencv
    Cloning into 'opencv'...
    remote: Enumerating objects: 4, done.
    remote: Counting objects: 100% (4/4), done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 262823 (delta 0), reused 0 (delta 0), pack-reused 262819
    Receiving objects: 100% (262823/262823), 464.01 MiB | 2.99 MiB/s, done.
    Resolving deltas: 100% (183205/183205), done.
    Checking out files: 100% (6097/6097), done.
    cloning opencv_contrib
    Cloning into 'opencv_contrib'...
    remote: Enumerating objects: 26, done.
    remote: Counting objects: 100% (26/26), done.
    remote: Compressing objects: 100% (20/20), done.
    remote: Total 30602 (delta 5), reused 12 (delta 5), pack-reused 30576
    Receiving objects: 100% (30602/30602), 127.44 MiB | 2.67 MiB/s, done.
    Resolving deltas: 100% (18926/18926), done.
    Checking out files: 100% (2589/2589), done.
    mkdir: cannot create directory ‘Build’: File exists

If it is the first time installation:

    if [  ! -d "$myRepo/opencv"  ]; then
        ....
        mkdir Build
        ...

and

    if [  ! -d "$myRepo/opencv_contrib"  ]; then
        ...
        mkdir Build
        ...

**Both** try to create the **Build/**
The second attempt fails and halts the script. Should create the dir only if it does not exists.

**Comment by alalek** [comment]
It is better to use `mkdir -p ...` instead (with excluding of intermediate steps like "Build" creation)
Target patch onto [3.4 branch](https://github.com/opencv/opencv/wiki/Branches).

P.S. Looks like "Build/opencv_contrib" is not used.

**Comment by gyadam** [comment]
Hi! Can I take this one as my first issue?

**Comment by gyadam** [comment]
By the way, shouldn't this be fixed on the master branch as well? I'm still new here so I might miss something, but seems to me that the issue occurred with the 4.1.2 documentation which is still incorrect.

**Comment by alalek** [comment]
No, fixes from "3.4" will be merged into "master" during regular "Merge-3.4" process: https://github.com/opencv/opencv/wiki/Branches
