### ISSUE TITLE
when im loading tensorflow faster rcnn model in opencv i got error of shape

### ISSUE THREAD

**Issue by SagarPawar606** [opencv/opencv#15873]
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:693: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::dnn4_v20190621::DataLayer::getMemoryShapes'

and my code is
import cv2 

cap = cv2.VideoCapture(1)
#cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'ssd_graph.pbtxt')
cv2Net = cv2.dnn.readNetFromTensorflow('C://tensorflow1//models//research//object_detection//graphsix//frozen_inference_graph.pb', 'C://tensorflow1//models//research//object_detection//training//labelmap.pbtxt')

while True:
    ret, img = cap.read()
    rows = img.shape[0]
    cols = img.shape[1]
    cv2Net.setInput(cv2.dnn.blobFromImage(img, 1.0/127.5, (1024,600), (127.5, 127.5, 127.5), swapRB=True, crop=False))
    cv2Out = cv2Net.forward()

    for detection in cv2Out[0,0,:,:]:
        score = float(detection[2])
        if score > 0.3:
            left = detection[3] * cols
            top = detection[4] * rows
            right = detection[5] * cols
            bottom = detection[6] * rows
            cv2.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)
    cv2.imshow('img', img)
    if cv2.waitKey(1) ==27:
        exit(0)

**Comment by dkurt** [comment]
Please provide a reproducer (references to mentioned `frozen_inference_graph.pb` and `ssd_graph.pbtxt`)

**Comment by SagarPawar606** [comment]
item {
  id: 1
  name: 'fire'
}

item {
  id: 2
  name: 'none'
}
this is a .pbtxt file

**Comment by dkurt** [comment]
@SagarPawar606, please follow https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. This is not right `.pbtxt` format.

**Comment by dkurt** [comment]
Please use a forum for usage questions: https://answers.opencv.org/. This is a tracker for bug reports and feature requests.
