### ISSUE TITLE
Open cv image loading problem

### ISSUE THREAD

**Issue by QasimEvil** [opencv/opencv#15876]
I am using this code in python and error as follow is shown to me. Do please help

>>> import numpy as np
>>> import cv2 as cv
>>> import math
>>> img=np.array(cv.imread('download (3).JPEG',0))
>>> cv.imshow('img',img)
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected Ptr<cv::UMat> for argument '%s'**

**Comment by themechanicalcoder** [comment]
No need to convert it to an numpy array use the following line 
```img=cv.imread('download (3).JPEG',0t)
cv.imshow('img',img)
```

**Comment by vsinghrana82** [comment]
import numpy as np
import cv2 as cv
import math
img=cv.imread('download (3).JPEG',0) #download(3).jpeg must be in working directory
cv.imshow('img',img)
