### ISSUE TITLE
Improving the Wiki Branches documentation

### ISSUE THREAD

**Issue by cbachhuber** [opencv/opencv#15884]
When I read [opencv/wiki/Branches.md](https://github.com/opencv/opencv/wiki/Branches), I found a few opportunities to improve grammar and to align structure to the remaining wiki documents.

As i cannot submit a PR to merge my suggestions into the wiki, I went with the [canonical alternative](https://stackoverflow.com/a/11481887/7260972):

- Clone the OpenCV wiki into [my own repository](https://github.com/cbachhuber/opencv-wiki)
- Apply my changes. See resulting [Branches.md](https://github.com/cbachhuber/opencv-wiki/blob/fix-grammar-in-branches/Branches.md) file and [**diff**](https://github.com/cbachhuber/opencv-wiki/compare/fix-grammar-in-branches) to [opencv/wiki/Branches](https://github.com/opencv/opencv/wiki/Branches))
- Link to all the material in this issue
- Ask OpenCV maintainers to apply my changes to the OpenCV wiki.

Hence, my final question: dear OpenCV maintainers, could you please review the changes above, and, if they are appropriate, merge them into [opencv/wiki/Branches.md](https://github.com/opencv/opencv/wiki/Branches)? Thank you!

**Comment by alalek** [comment]
Looks good to me. I [pushed your updates](https://github.com/opencv/opencv/wiki/Branches/_compare/163d184663c0433a6d57f1da3446b5ccf28a7eef...70f6e0f33c9405c61f4524f6aee13505b8bb8981) into OpenCV Wiki.
Thank you :+1:

BTW, Separate GitHub repository is not necessary - you can work on Wiki pages in your fork of the opencv repository (perhaps additionally you need to enable Wiki in fork settings first).

**Comment by cbachhuber** [comment]
Thanks! Thank you also for the hint - unfortunately, even after some more googling, I could not find how to enable the opencv wiki in my fork. Also, it seems like [stackoverflow](https://stackoverflow.com/a/33828142/7260972) has a different opinion on this topic. Would you mind giving me more specific advice?

**Comment by alalek** [comment]
https://github.com/cbachhuber/opencv/settings
=> Features => Wiki (this check box and check box with Wiki editors restriction)

**Comment by cbachhuber** [comment]
Got it, thank you! 
But I will still need to use an issue and not be able to open a PR, right?

**Comment by alalek** [comment]
Right.
