### ISSUE TITLE
Missing return type for CV_XADD in cvdef.h in some configurations

### ISSUE THREAD

**Issue by lebarsfa** [opencv/opencv#15887]
**System information (version)**
OpenCV => 3.2.0 and later
Operating System / Platform => Multiple, but probably uncommon
Compiler => Multiple, but probably uncommon

**Detailed description**

I noticed that a return type for CV_XADD (probably int, or maybe unsigned...) seems to be missing here : 

https://github.com/opencv/opencv/blob/5dd3e6052ed9e614cf4303eee64d092fefbabd8e/modules/core/include/opencv2/core/cvdef.h#L644

It seems it was mentioned in #8278 and probably solved in another way, but I don't think it can build if we fall in that case...

I saw that because I had to build OpenCV 3.2.0 with an old MinGW with GCC 4.4, and it seems we fall in this case : 
https://github.com/opencv/opencv/blob/5dd3e6052ed9e614cf4303eee64d092fefbabd8e/modules/core/include/opencv2/core/cvdef.h#L637
Unfortunately, when building an app, the linker cannot find a definition for `__sync_fetch_and_add` which can happen on some hosts according to https://gcc.gnu.org/onlinedocs/libstdc++/manual/ext_concurrency_impl.html . FYI I replaced the line https://github.com/opencv/opencv/blob/5dd3e6052ed9e614cf4303eee64d092fefbabd8e/modules/core/include/opencv2/core/cvdef.h#L637 
with 
```
#      if defined(_WIN32) && !defined(__ATOMIC_ACQ_REL) && !defined __clang__
         // __sync_fetch_and_add() definition might be missing in old MinGW versions...
         CV_INLINE unsigned __CV_XADD(unsigned* addr, unsigned delta) { unsigned tmp = *addr; *addr += delta; return tmp; }
#        define CV_XADD(addr, delta) (int)__CV_XADD((unsigned*)(addr), (unsigned)(delta))
#      else
#        define CV_XADD(addr, delta) (int)__sync_fetch_and_add((unsigned*)(addr), (unsigned)(delta))
#      endif
```
But I guess the recommendation is to pre-define CV_XADD macro before somehow to override the definitions in cvdef.h (note that I have also to define _WIN32_WINNT 0x0500 and _WIN32_IE 0x0500 for other reasons related to GUI parts to build successfully OpenCV in the configuration OpenCV 3.2.0+old MinGW)...

**Comment by alalek** [comment]
> GCC 4.4

Perhaps won't fix (mentioned GCC is very old).

Default "else" case (which you are reusing in your trick) is not thread-safe. We have plant to disable that.

Latest OpenCV sources allows to use own custom implementations for `CV_XADD()` - feel free to try them: https://github.com/opencv/opencv/blob/3.4.8/modules/core/include/opencv2/core/cvdef.h#L502
