### ISSUE TITLE
Error in Image stitching tutorial

### ISSUE THREAD

**Issue by themechanicalcoder** [opencv/opencv#15902]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => Ubuntu terminal (g++)
-Compiled using g++ stitch.cpp -o app pkg-config --cflags --libs opencv "

##### Detailed description

The[ Image stitching](https://docs.opencv.org/master/db/deb/tutorial_display_image.html) tutorial gives the following error<br/>
**: error: ‘samples’ has not been declared
Mat img = imread(samples::findFile(argv[i]));**
Also when I used the following
**using namespace samples;**
in the code it gives the following error
**error: expected namespace-name before ‘;’ token using namespace samples;**
It looks like the latest version of opencv does not support namespace "samples"
It can be corrected by replacing the above line with<br/>
``Mat image=imread(argv[1],IMREAD_COLOR);``

Can I take up this issue and fix this

##### Steps to reproduce
Here is the code from the tutorial<br/>
```.cpp
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <iostream>
using namespace cv;
using namespace std;
int main( int argc, char** argv )
{
    String imageName( "HappyFish.jpg" ); // by default
    if( argc > 1)
    {
        imageName = argv[1];
    }
    Mat image;
    image = imread( samples::findFile( imageName ), IMREAD_COLOR ); // Read the file

    if( image.empty() )                      // Check for invalid input
    {
        cout <<  "Could not open or find the image" << std::endl ;
        return -1;
    }
    namedWindow( "Display window", WINDOW_AUTOSIZE ); // Create a window for display.
    imshow( "Display window", image );                // Show our image inside it.
    waitKey(0); // Wait for a keystroke in the window
    return 0;
}
```

**Comment by alalek** [comment]
You can't use new samples (from 4.x+) with outdated OpenCV version (3.2 - released 3 years ago).
