### ISSUE TITLE
About opencv.js aruco

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [opencv/opencv#15913]
Is it possible to add aruco to opencv.js, what should I do when I build it.

**Comment by dkurt** [comment]
Please try to follow this guide: https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html. Aruco module should be supported after https://github.com/opencv/opencv/pull/13571.

**Comment by Ouyang-Zhaoxing** [comment]
@dkurt I have successfully built opencv.js, but I have not found support for aruco. What switch do I need to set? Forgive me for not knowing what to do.

**Comment by alalek** [comment]
> successfully built opencv.js

No idea what exactly your build (no logs or inputs provided), but I believe you have misconfigured build settings.
Tutorial says how to build "default" opencv.js. Detailed configuration for your needs is out of scope.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Ouyang-Zhaoxing** [comment]
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git

**opencv/platforms/js/build_js.py** -> **def get_cmake_cmd** add
"-DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules",

docker run --rm --workdir /code -v "$(get-location):/code" "trzeci/emscripten:sdk-tag-1.38.32-64bit" python ./platforms/js/build_js.py build

If this is not true, what else do I need to do?

**Comment by alalek** [comment]
> ../opencv_contrib
> python ./platforms

Are you sure that "opencv_contrib" repo is mounted properly into container?

---

Attach logs, like [these](http://pullrequest.opencv.org/buildbot/builders/3_4_javascript-emscripten-lin64/builds/573/steps/build/logs/stdio) (CMake's part is enough for initial investigation).

**Comment by gpiffault** [comment]
In case someone end up here, this worked for me:

```bash
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git
# Notice we don't change dir so that both repos are mounted in the container
docker run --rm --workdir /src -v $(pwd):/src emscripten/emsdk emcmake python3 opencv/platforms/js/build_js.py build_js  --cmake_option="-DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules"
```

**Comment by PapeCoding** [comment]
@gpiffault Thank you for your comment, it really helped!

As I still had troubles getting stuff to run I would like to add some advice for people coming here later:
1. You should select a specific tag not the default branch. For me, the 4.6 tags worked. With 4.7 the Aruco functionality was moved and I could not figure it out how to use it.

2. If you ever need functions which are not exported via the `https://github.com/opencv/opencv/blob/4.x/platforms/js/opencv_js.config.py` you can just put them there and they are exported as well.
