### ISSUE TITLE
could we include 4-channels images, too? i.e. 4D alpha images?

### ISSUE THREAD

**Issue by tati-z** [opencv/opencv#15927]
https://github.com/opencv/opencv/blob/1acadd363b0d0ffcdabac8af3196cb65bef426b1/modules/photo/src/seamless_cloning.cpp#L54
reason:  all images with 4 channels (alpha channels) are required to be converted to 3 channels on the client side, then back to 3 channels just for API compatibility purposes.

**Comment by nappaillav** [comment]
Hello
I am new to opencv community and would like to work on this issue. So I just wanted to know if the  following code would resolve the issue. If not, do let me know how to resolve the issue

`

    static Mat checkMask(InputArray _mask, Size size)
    {
        Mat mask = _mask.getMat();
        Mat gray;
        
        if (mask.channels() == 3)
            cvtColor(mask, gray, COLOR_BGR2GRAY);
        
        else if(mask.channels() == 4)
            cvtColor(mask, gray, COLOR_BGRA2GRAY);
        
        else
        {
            if (mask.empty())
                gray = Mat(size.height, size.width, CV_8UC1, Scalar(255));
            else
                mask.copyTo(gray);
        }
        
        return gray;
    }

`

**Comment by tati-z** [comment]
I was working on COLOR_BGRA2GRAY images when this issue arose. 
I don't know which other colour scheme in cv2.COLOR_* has more than 3 channels, or exactly 4.
the code
```
if (mask.channels() == 3)
        cvtColor(mask, gray, COLOR_BGR2GRAY);
```
from the original code, was assuming that every 3 channels image sent to this function will be of colour scheme BGR. which will not always be true in itself.
**But whether this matters or not**, I am not sure.

it might not matter because for every 3 channel image, GRAY could just be the average values from all channels.
furthermore, not all channels are directly convertible to gray; e.g COLOR_HSV2GRAY is not supported. making it a general assumption that other 3 channels will be converted to BGR first.

when looking at:
```python
>>> import cv2
>>> [ c for c in dir(cv2) if c.find('2GRAY') != -1]
['COLOR_BAYER_BG2GRAY', 'COLOR_BAYER_GB2GRAY', 'COLOR_BAYER_GR2GRAY', 'COLOR_BAYER_RG2GRAY', 'COLOR_BGR2GRAY', 'COLOR_BGR5552GRAY', 
'COLOR_BGR5652GRAY', 'COLOR_BGRA2GRAY', 'COLOR_BayerBG2GRAY', 
'COLOR_BayerGB2GRAY', 'COLOR_BayerGR2GRAY', 'COLOR_BayerRG2GRAY', 'COLOR_RGB2GRAY', 
'COLOR_RGBA2GRAY', 'COLOR_YUV2GRAY_420', 'COLOR_YUV2GRAY_I420', 
'COLOR_YUV2GRAY_IYUV', 'COLOR_YUV2GRAY_NV12', 'COLOR_YUV2GRAY_NV21', 
'COLOR_YUV2GRAY_UYNV', 'COLOR_YUV2GRAY_UYVY', 'COLOR_YUV2GRAY_Y422', 
'COLOR_YUV2GRAY_YUNV', 'COLOR_YUV2GRAY_YUY2', 'COLOR_YUV2GRAY_YUYV', 
'COLOR_YUV2GRAY_YV12', 'COLOR_YUV2GRAY_YVYU', 'COLOR_YUV420P2GRAY', 
'COLOR_YUV420SP2GRAY', 'COLOR_YUV420p2GRAY', 'COLOR_YUV420sp2GRAY']
>>>
```
These are the colour schemes that can be converted to gray.  If any of them apart from COLOR_BGRA2GRAY has 4 channels, I don't know what the behaviour of 
```
else if(mask.channels() == 4)
        cvtColor(mask, gray, COLOR_BGRA2GRAY);
```
could be.

the code in master generalised with  
```
if (mask.channels() == 3)
        cvtColor(mask, gray, COLOR_BGR2GRAY);
```
but whether the same generalisation can be made with (mask.channels() == 4) I would personally need more information to conclude..

**Comment by Lalit-garg** [comment]
Surely,we can use this to convert 3 channels to 4 channels
**image = cv2.cvtColor(image, cv2.COLOR_BGR2RGBA)**
And similarly if we can convert into 3 channels .
So, we use RGBA2BGR
