### ISSUE TITLE
Error: !haveConst || layer.input_size() == 2 in function 'populateNet'

### ISSUE THREAD

**Issue by Alpheron** [opencv/opencv#15924]
##### System information (version)

- OpenCV => 4.1.2 dev
- Operating System / Platform => Mac OS X 64 Bit 10.15.1
- Compiler => Python 3.6

##### Detailed description

Hello all, I recently retrained a model and wanted to run it using OpenCV's DNN module. However, when I try to run the file, I keep getting this error.
```
File "Stone.py", line 23, in <module>
    net = cv2.dnn.readNetFromTensorflow('/Users/Username/Skystone-Vision/SkystoneVision/PB-File/model.pb', '/Users/Username/Skystone-Vision/SkystoneVision/new_PBtxt/plswork.pbtxt')
cv2.error: OpenCV(4.1.2-dev) /Users/Username/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1495: error: (-215:Assertion failed) !haveConst || layer.input_size() == 2 in function 'populateNet'
```
I do not know how to proceed next as I have no clue on how to fix this problem. Please help if you can. I will be attaching my checkpoint files below.

Any help would be greatly appreciated. Thanks!

The link to reproduce can be running the Stone.py and changing the directories inside the script to match where the .pb file and the .pbtxt file are located. 
https://drive.google.com/drive/folders/1C4SGBkQqsen7PVh8IlcyTM9r1VrLa_dE

**Comment by Alpheron** [comment]
@dkurt I think you are the main developer for the DNN module so wanted to tag you to see if you had any ideas.

**Comment by dkurt** [comment]
Can you provide the details about .pbtxt file? If it is TensorFlow Object Detection API, please provide a config file (usually named as pipeline.config)

**Comment by Alpheron** [comment]
@dkurt Hello, sorry for the late comment, the .pbtx is a part of the Google drive link I had sent earlier. The .pbtxt file is a bit long so you may be able to see it if you click on the link and enter SkystoneVision and then click on new_PBtxt, and then download the plswork.pbtxt file. For convenience I will just throw it up on pastebin: https://pastebin.com/ZtEiUMFa That link should show you the entire PBtxt file. I did in fact use the Tensorflow Object Detection API. I used supervise.ly to annotate the images and train so the config file is named model.config. I will drop that into a pastebin too: https://pastebin.com/NLKjYSmx 
Please do keep in mind that the files are pretty long so it might be a bit tedious. Also supervise.ly does do some weird stuff in terms of data management and also custom syntax commands (they have some custom syntax for other things, for models I am not sure). Please let me know if you have any other details, I have a somewhat tight schedule of the next 5 days to finish this. Thank you so much!

**Comment by Alpheron** [comment]
@dkurt @alalek Can this issue please be tagged?

**Comment by dkurt** [comment]
@l-bat, may I kindly ask you to take a look? Thanks!

**Comment by l-bat** [comment]
I looked at the model. I don't understand yet why "Mul" node has one constant input.
```
node {
  name: "Preprocessor/mul"
  op: "Mul"
  input: "Preprocessor/mul/x"
}
```
Could you provide the code model?

**Comment by Alpheron** [comment]
So in order to generate the pbtxt file, I used the tf_graph_ssd.py file. I do not know why or how it is throwing me that error.

**Comment by Alpheron** [comment]
@dkurt @l-bat Was there any progress made on this issue?

**Comment by Alpheron** [comment]
@dkurt @l-bat Was this issue fixed? Has it been able to be reproduced and has a solution been discovered?

**Comment by dkurt** [comment]
As @l-bat pointed, the problem in the `Preprocessor/mul`. Modify .pbtxt file in the following way:

```yml
node {
  name: "Preprocessor/mul"
  op: "Mul"
  input: "Preprocessor/mul/x"
  input: "tf_example"
}
```

**Comment by Alpheron** [comment]
Thank you so much, changing that one thing fixed it!
