### ISSUE TITLE
opencv4.1.2 complie error

### ISSUE THREAD

**Issue by burgesswu** [opencv/opencv#15921]
[ 58%] Linking CXX executable ../../bin/opencv_interactive-calibration
/home/burgess/raspi/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: ../../lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `png_do_expand_palette_rgba8_neon'
/home/burgess/raspi/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: ../../lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `png_init_filter_functions_neon'
/home/burgess/raspi/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: ../../lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `png_do_expand_palette_rgb8_neon'
/home/burgess/raspi/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: ../../lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `png_riffle_palette_neon'
collect2: error: ld returned 1 exit status
apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/build.make:233: recipe for target 'bin/opencv_interactive-calibration' failed
make[2]: *** [bin/opencv_interactive-calibration] Error 1
CMakeFiles/Makefile2:8877: recipe for target 'apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/all' failed
make[1]: *** [apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by airbak** [comment]
aarch64 compile error,  follow patch fix it. Please help to solve the compile error.

diff --git a/3rdparty/libpng/pngpriv.h b/3rdparty/libpng/pngpriv.h
index 583c26f9bd..c7b67d4a00 100644
--- a/3rdparty/libpng/pngpriv.h
+++ b/3rdparty/libpng/pngpriv.h
@@ -127,7 +127,7 @@
     * associated assembler code, pass --enable-arm-neon=no to configure
     * or put -DPNG_ARM_NEON_OPT=0 in CPPFLAGS.
     */
-#  if (defined(__ARM_NEON__) || defined(__ARM_NEON)) && \
+# if defined(PNG_ARM_NEON) && (defined(ARM_NEON) || defined(__ARM_NEON)) && \
    defined(PNG_ALIGNED_MEMORY_SUPPORTED)
 #     define PNG_ARM_NEON_OPT 2
 #  else

**Comment by airbak** [comment]
The follow patch fix it. @alalek @dkurt 

> diff --git a/3rdparty/libpng/pngpriv.h b/3rdparty/libpng/pngpriv.h
index 583c26f9bd..c7b67d4a00 100644
--- a/3rdparty/libpng/pngpriv.h
+++ b/3rdparty/libpng/pngpriv.h
@@ -127,7 +127,7 @@
     * associated assembler code, pass --enable-arm-neon=no to configure
     * or put -DPNG_ARM_NEON_OPT=0 in CPPFLAGS.
     */
-#  if (defined(__ARM_NEON__) || defined(__ARM_NEON)) && \
+# if defined(PNG_ARM_NEON) && (defined(ARM_NEON) || defined(__ARM_NEON)) && \
    defined(PNG_ALIGNED_MEMORY_SUPPORTED)
