### ISSUE TITLE
  CUDA backend for DNN module requires CC 5.3 or higher.  Please remove   unsupported architectures from CUDA_ARCH_BIN option.

### ISSUE THREAD

**Issue by ashuezy** [opencv/opencv#15930]
CC version 5.3 or higher ? What is CC ? Cuda compiler or GCC ?

OS: Ubuntu 18.04
Cuda : 10.1
Cudnn : 7.6.5
Opencv: github latest

```
-- Checking for module 'tesseract'
--   No package 'tesseract' found
-- Tesseract:   NO
-- Performing Test HAVE_CXX_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_CXX_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': /opt/opencv_from_github_with_cuda/opencv/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
CMake Error at modules/dnn/CMakeLists.txt:97 (message):
  CUDA backend for DNN module requires CC 5.3 or higher.  Please remove
  unsupported architectures from CUDA_ARCH_BIN option.


-- Configuring incomplete, errors occurred!
See also "/opt/opencv_from_github_with_cuda/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/opt/opencv_from_github_with_cuda/opencv/build/CMakeFiles/CMakeError.log".
root@laptop3:/opt/opencv_from_github_with_cuda/opencv/build# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by alalek** [comment]
Check these CMake variables:

> CUDA_ARCH_BIN
> CUDA_ARCH

**Comment by ashuezy** [comment]
I have a GTX 1060. How do i know the values of these cmake variables ?

**Comment by alalek** [comment]
> 1060.

Use "6.1" (one value only): https://en.wikipedia.org/wiki/CUDA#GPUs_supported

CMake output should have something like this:
```
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so (found suitable version "7.6.0", minimum required is "7.5") 
-- CUDA detected: 10.1
-- CUDA NVCC target flags: -gencode;arch=compute_61,code=sm_61;-D_FORCE_INLINES
```

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by jiapei100** [comment]
So unlucky... Mine is 5.2

**Comment by alalek** [comment]
@jiapei100 You may validate this patch #16218 on your configuration.

**Comment by j2eejb8** [comment]
CUDA_ARCH_BIN中低于6.0的值删掉

**Comment by zubairahmed-ai** [comment]
CUDA_ARCH_BIN=6.1
Spent 5 hours today :(

**Comment by Pedro-lr** [comment]
thanks guys, to be more explicit, when building with cmake, for example:
`cmake     -D WITH_CUDA=ON \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules \
        -D WITH_GSTREAMER=ON \
        -D WITH_LIBV4L=ON \
        -D BUILD_opencv_python2=ON \
        -D BUILD_opencv_python3=ON \
        -D BUILD_TESTS=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D BUILD_EXAMPLES=OFF \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local ..`

i added in my case as mi graphics card is Nvidia gtx1070
   `-D CUDA_ARCH_BIN=6.1 \` 

Thanks!
