### ISSUE TITLE
ContourArea does Not Work in cv2 4.0 ?

### ISSUE THREAD

**Issue by sassimon** [opencv/opencv#15941]
Hey, I am using cv2 4.0 and Python 3.6 and i am trying to extract a hand Out of a picture.

This ist my code.

cnts = cv2.findContours(thresholded.copy(), cv2.RETR_EXTERNAL,conto cv2.CHAIN_APPROX_SIMPLE) # return None, if no contours detected ifArea len(cnts) == 0: return else: # based on contour area, get the maximum contour which is the hand segmented = max(cnts, key=cv2.contourArea)

Sadly It Returns this Error 

Traceback (most recent call last): File "test.py", line 85, in <module> hand = segment(gray) File "test.py", line 37, in segment segmented = max(cnts, key=cv2.contourArea) TypeError: Expected cv::UMat for argument 'contour'

Is this a Error that can be avoided?

Answers appreciated

**Comment by alalek** [comment]
Please provide complete minimal reproducer including inputs.

> TypeError: Expected cv::UMat for argument 'contour'

This message is not correct (only last conversion error is showed), but there is problem with parameter types.

**Comment by a-v-s-coder** [comment]
external_contours=np.zeros(cnts.shape)
for i in range(len(cnts)):
    #External contour
    if heirarchy[0][i][3] == -1:
           cv2.drawContours(external_contours,contours1,i,255,-1)
plt.imshow(external_contours)

Above code might be helpful to get hand as a contour if hand is external/largest contour among others.
