### ISSUE TITLE
Add support for nvvideoconvert, and nvvidconv

### ISSUE THREAD

**Issue by HEBOS** [opencv/opencv#15948]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc

##### Detailed description
There is no way to use nvvideoconvert, or nvvidconv plugins by V4LT, as videoconvert is enforced when checking for the destination color type.

##### Steps to reproduce
For example, this pipeline works normally, when run through shell:

gst-launch-1.0 -v rtspsrc location=rtsp://192.168.0.153:554 latency=200 ! rtph265depay ! h265parse ! nvv4l2decoder enable-max-performance=1 drop-frame-interval=1 ! nvvideoconvert ! capsfilter caps='video/x-raw(memory:NVMM),width=1920,height=1080,format=I420,framerate=25/1' ! nvvideoconvert ! capsfilter caps='video/x-raw,width=1920,height=1080,format=I420,framerate=25/1' ! appsink sync=0

However, the captured frames, using OpenCV are in grayscale.
After I've checked https://github.com/opencv/opencv/blob/4.1.1/modules/videoio/src/cap_gstreamer.cpp (line 74, and line 774), I discovered, that the destination color is being picked up from videoconvert sink caps.
It means that videoconvert, which is painfully slow plugin cannot be used in production on IoT devices is enforced, which shouldn't be the case. The mentioned V4LT plugins can use CUDA too, so if we decide to use any of those, and not videoconvert, we should be able to do so.

Thank you

**Comment by alalek** [comment]
Why is check on the [line 770](https://github.com/opencv/opencv/blob/4.1.1/modules/videoio/src/cap_gstreamer.cpp#L770) failed in your case?
```
if (strstr(name, "opencvsink") != NULL || strstr(name, "appsink") != NULL)
{
    sink.attach(GST_ELEMENT(gst_object_ref(element)));
}
else if (strstr(name, COLOR_ELEM_NAME) != NULL)
{
    color.attach(GST_ELEMENT(gst_object_ref(element)));
}
```

**Comment by alalek** [comment]
Can't reproduce:

```.py
import cv2 as cv

# output is BGR 24-bit
#pipeline = 'videotestsrc pattern=smpte ! video/x-raw,width=640,height=480,framerate=25/1 ! appsink sync=false'
# output is I420 640x720 (width, height*3/2)
pipeline = 'videotestsrc pattern=smpte ! video/x-raw,width=640,height=480,framerate=25/1,format=I420 ! appsink sync=false'

print("pipeline: ", pipeline)

vid = cv.VideoCapture(pipeline, cv.CAP_GSTREAMER)

print('Codec FOURCC: {}'.format(hex(int(vid.get(cv.CAP_PROP_FOURCC)))))
print('Codec pixel FOURCC: {}'.format(hex(int(vid.get(cv.CAP_PROP_CODEC_PIXEL_FORMAT)))))

success, image = vid.read()

print("Image shape: ", image.shape)

if len(image.shape) == 2:
   cv.imshow("test", cv.cvtColor(image, cv.COLOR_YUV2BGR_I420))
else:
   cv.imshow("test", image)
cv.waitKey(0)
```

**Comment by HEBOS** [comment]
> 
> 
> Why is check on the [line 770](https://github.com/opencv/opencv/blob/4.1.1/modules/videoio/src/cap_gstreamer.cpp#L770) failed in your case?
> 
> ```
> if (strstr(name, "opencvsink") != NULL || strstr(name, "appsink") != NULL)
> {
>     sink.attach(GST_ELEMENT(gst_object_ref(element)));
> }
> else if (strstr(name, COLOR_ELEM_NAME) != NULL)
> {
>     color.attach(GST_ELEMENT(gst_object_ref(element)));
> }
> ```

Because, I don't include videoconvert in my pipeline.

**Comment by HEBOS** [comment]
> 
> 
> Can't reproduce:
> 
> ```python
> import cv2 as cv
> 
> # output is BGR 24-bit
> #pipeline = 'videotestsrc pattern=smpte ! video/x-raw,width=640,height=480,framerate=25/1 ! appsink sync=false'
> # output is I420 640x720 (width, height*3/2)
> pipeline = 'videotestsrc pattern=smpte ! video/x-raw,width=640,height=480,framerate=25/1,format=I420 ! appsink sync=false'
> 
> print("pipeline: ", pipeline)
> 
> vid = cv.VideoCapture(pipeline, cv.CAP_GSTREAMER)
> 
> print('Codec FOURCC: {}'.format(hex(int(vid.get(cv.CAP_PROP_FOURCC)))))
> print('Codec pixel FOURCC: {}'.format(hex(int(vid.get(cv.CAP_PROP_CODEC_PIXEL_FORMAT)))))
> 
> success, image = vid.read()
> 
> print("Image shape: ", image.shape)
> 
> if len(image.shape) == 2:
>    cv.imshow("test", cv.cvtColor(image, cv.COLOR_YUV2BGR_I420))
> else:
>    cv.imshow("test", image)
> cv.waitKey(0)
> ```

**You haven't been using the pipeline, I've provided, especially with respect to using nvvideoconvert.**

gst-launch-1.0 -v rtspsrc location=rtsp://192.168.0.153:554 latency=200 ! rtph265depay ! h265parse ! nvv4l2decoder enable-max-performance=1 drop-frame-interval=1 ! nvvideoconvert ! capsfilter caps='video/x-raw(memory:NVMM),width=1920,height=1080,format=I420,framerate=25/1' ! nvvideoconvert ! capsfilter caps='video/x-raw,width=1920,height=1080,format=I420,framerate=25/1' ! appsink sync=0

**Comment by alalek** [comment]
Try to minimize scope of the problem and make it reproducible (get rid of network RSTP stream at first, next is NVIDIA elements).

Mentioned "videoconvert" check is not triggered in the sample above. It is equal to
```
videotestsrc pattern=smpte ! capsfilter caps="video/x-raw,width=640,height=480,framerate=25/1,format=I420" ! appsink sync=false
```

---

If you can't make/build minimal reproducer without NVIDIA elements, then it is likely NVIDIA-related issue. In that case, it is better to ask for help with pipeline here: https://devtalk.nvidia.com/

**Comment by isra60** [comment]
Maybe the problem is this??

 nvvideoconvert ! capsfilter caps='video/x-raw(memory:NVMM)

Using GPU memory instead CPU memory???

**Comment by ozett** [comment]
i discovered the same result as thread-starter HEBOS

> However, the captured frames, using OpenCV are in grayscale

But i cannot find any hint here, why openCV gets grayscale-images from the gstreamer pipeline with appsink, as correctly showing color-images with xvimagesink on the gstreamer cmd-line.

it must be something with conversion and rtsp-color-formats, with nvvidconv or videoconvert, but this thread shows me no hint or solution to investigate in the right direction.

would be very,very glad , if someone could help me out

i can provide more details about jetson nano versions, running without problems, but only grayscale:

```
[clipped]

cap = cv2.VideoCapture('rtspsrc location=rtspt://user:pwd@192.168.14.83/Streaming/Channels/101 ! decodebin ! nvvidconv ! video/x-raw,format=I420 ! appsink',cv2.CAP_GSTREAMER)

while True:
      ret,frame = cap.read()
      if not ret:
        print('empty frame')
        continue

[clipped]

```

**Comment by HEBOS** [comment]
I've managed to get it working, after a few weeks, and with the best performance.

To read from rstp compatible camera, use this  pipe:

`rtspsrc location={location} latency=200 user-id={user} user-pw={password} ! queue ! rtph264depay ! h264parse ! nvv4l2decoder enable-max-performance=1 drop-frame-interval=1 ! nvvidconv ! video/x-raw(memory:NVMM),format=BGRx,width={width},height={height} ! queue ! nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw,format=BGR ! videorate max-rate={fps} drop-only=true average-period=5000000 ! video/x-raw,framerate={fps}/1 ! appsink sync=true`

You will need to replace location, user, password, fps, width, height, latency with real values (remove curly brackets too).


If you need to write to the video stream, i.e. create a video file, use this pipe:


`appsrc ! capsfilter caps='video/x-raw,format=I420,framerate={fps}/1' ! videoconvert ! capsfilter caps='video/x-raw,format=BGRx,interpolation-method=1' ! nvvideoconvert ! capsfilter caps='video/x-raw(memory:NVMM)' ! nvv4l2h264enc maxperf-enable=true ! h264parse ! qtmux ! filesink location={video}`

You will need to replace fps, and video, and also remove curly brackets.

I hope, it will work for you too.

**Comment by PythonImageDeveloper** [comment]
@HEBOS 
Did you test for decoding h264 rtsp stream with jetson nano, It doesn't work for me with opencv-3.4.6 cuda and gstreamer compiled. and this work with omxh264dec but nvv2l2decoder doesn't with in opencv, but work for filesrc in terminal execution, How to solve this problem to work nvv4l2decoder in opencv?

**Comment by HEBOS** [comment]
I used opencv 4.1.1, and it worked with above with pipe, I specified above.

If you decide to install 4.1.1 use the following script:

mkdir $HOME/GitHub
cd $HOME/GitHub
sudo apt update; \
sudo apt install -y build-essential cmake git libgtk2.0-dev pkg-config  libswscale-dev libtbb2 libtbb-dev; \
sudo apt install -y python-dev python3-dev python-numpy python3-numpy; \
sudo apt install -y curl; \
sudo apt install -y  libjpeg-dev libpng-dev libtiff-dev libjasper-dev ; \
sudo apt install -y libavcodec-dev libavformat-dev; \
sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev; \
sudo apt install -y libv4l-dev v4l-utils qv4l2 v4l2ucp libdc1394-22-dev

curl -L https://github.com/opencv/opencv/archive/4.1.1.zip -o opencv-4.1.1.zip
curl -L https://github.com/opencv/opencv_contrib/archive/4.1.1.zip -o opencv_contrib-4.1.1.zip
unzip opencv-4.1.1.zip 
unzip opencv_contrib-4.1.1.zip 
cd opencv-4.1.1/
mkdir release
cd release/
cmake -D WITH_CUDA=ON \
	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.1/modules \
	-D WITH_GSTREAMER=ON \
	-D WITH_LIBV4L=ON \
	-D WITH_OPENGL=ON \
	-D BUILD_opencv_python2=OFF \
	-D BUILD_opencv_python3=ON \
	-D BUILD_TESTS=OFF \
	-D BUILD_PERF_TESTS=OFF \
	-D BUILD_EXAMPLES=OFF \
	-D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D ENABLE_PRECOMPILED_HEADERS=OFF ..
make -j4
sudo make install

**Comment by PythonImageDeveloper** [comment]
@HEBOS 
you used that command in terminal or passed that command into opencv?
and you tested with jetson nano? if so which version of jetpack?

**Comment by HEBOS** [comment]
@PythonImageDeveloper Used in python script with VideoCapture class.
It was JetPack 4.3.
You can easily remove user-id, and user-pw.
But it won't work with your version of opencv.
It needs to be 4.1.1 +

**Comment by PythonImageDeveloper** [comment]
@HEBOS 
I tested your code in jetpack 4.4 + opencv 4.1.1 and jetpack 4.2.2 + opencv 3.4.8.  I stuck in this situation, but work with omxh264dec. In your opinion, your code will work with nvv4l2decoder?

**This is with jetpack 4.2.2 :**

    ```
nvbuf_utils: Could not get EGL display connection
    Opening in BLOCKING MODE 
    NvMMLiteOpen : Block : BlockType = 261 
    NVMEDIA: Reading vendor.tegra.display-size : status: 6 
    NvMMLiteBlockCreate : Block : BlockType = 261 

    (python3:20431): GStreamer-CRITICAL **: 11:29:19.872: gst_mini_object_unref: assertion 'mini_object != NULL' failed
    NvMMLiteOpen : Block : BlockType = 261 
    NVMEDIA: Reading vendor.tegra.display-size : status: 6 
    NvMMLiteBlockCreate : Block : BlockType = 261
```

**This is with jetpack 4.4 DP:**

    ```
libEGL warning: DRI2: failed to authenticate
    libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

    libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

    nvbuf_utils: Could not get EGL display connection
    Opening in BLOCKING MODE 
    NvMMLiteOpen : Block : BlockType = 261 
    NVMEDIA: Reading vendor.tegra.display-size : status: 6 
    NvMMLiteBlockCreate : Block : BlockType = 261
```

**Comment by PythonImageDeveloper** [comment]
@HEBOS 
I tested your codes in jetpack 4.3 and opencv 4.1.1, again I also have same problem, My opinion this is related to streaming with live555 that don't adaptive with nvv4l2decoder.
