### ISSUE TITLE
opencv installation

### ISSUE THREAD

**Issue by amityu** [opencv/opencv#15940]
Hello I try to use opencv on ubuntu.18.04.3 
I get this message when I import cv2 in anaconda notebook

 55 if required: ---> 56 raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames)) 57 58 load_first_config(['config.py'], True) ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation

please please advise if it is a bug or how to fix it
thanks
Yuval

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by dkurt** [comment]
Please use a forum for build / install questions: answers.opencv.org. This is a bug tracker.
