### ISSUE TITLE
Opencv-python for python 3.8

### ISSUE THREAD

**Issue by varshaneya** [opencv/opencv#15952]
Python 3.8 is the latest stable version of python. Need to create a wheel of Opencv-python for python 3.8 in PyPI.

**Comment by alalek** [comment]
PyPI opencv-python* packages are maintained in another repository (thanks to @skvark).

https://pypi.org/project/opencv-python/
https://github.com/skvark/opencv-python/issues

**Comment by skvark** [comment]
See: https://github.com/skvark/opencv-python/issues/253

Python 3.8 wheels will be available during this week.
