### ISSUE TITLE
Error during Installing openCV on raspberry pi

### ISSUE THREAD

**Issue by zaman-ahmad** [opencv/opencv#15954]
I am trying to install openCV on raspberry pi 3. 
I don't have any experience using cmake. I used following command to install openCV on raspberry pi.

cmake -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D OPENCV_EXTRA_MODULES_PATH=$OPENCV_CONTRIB_MODULES_SRC_DIR \
  ..

There are lots of errors in CMAKEERROR.log file.
Can anyone help me what I did wrong?

[CMakeError.log](https://github.com/opencv/opencv/files/3867968/CMakeError.log)
[CMakeOutput.log](https://github.com/opencv/opencv/files/3867969/CMakeOutput.log)

**Comment by alalek** [comment]
> I don't have any experience using cmake.
> There are lots of errors in CMAKEERROR.log file.

Ignore them. They are just configuration checks. Their failures are normal.

You should look on CMake stdout (terminal output) for the actual problem.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
