### ISSUE TITLE
undefined reference to ' cv::dnn::experimental_dnn_34_v7***'

### ISSUE THREAD

**Issue by RorschachS** [opencv/opencv#15960]
##### System information (version)

- OpenCV =>3.4.3
- Operating System / Platform => Ubuntu14.04
- Compiler =>cmake
##### Detailed description

 
My project runs normal which contains other OpenCV module until I attach parts of code about dnn to load a YOLO model for object detection。
I use CMakeList.txt to generate Makefile which build the program.I can generate the executable file and .so file and they run fine.But when I want to delete source file and generate executable file by .so file,it goes wrong.What shoud I do to CMakeList.txt to solve the problem.
![error](https://user-images.githubusercontent.com/20204666/69264445-4ed0dc00-0c02-11ea-854e-f7ce31d7ba40.png)

##### Steps to reproduce

**CMakeList.txt(exe&.so)**
```
cmake_minimum_required(VERSION 3.5)
project(algorithm-sdk)

set(CMAKE_CXX_STANDARD  11)
find_package(OpenCV REQUIRED)

 add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rd/cJSON)
add_library(SmokeDetectAlgorithm  SHARED ${CMAKE_CURRENT_SOURCE_DIR}/src/SmokeDetectAlgorithm.cpp)
	   
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(SmokeDetectAlgorithm
			cjson
			)

add_executable(test-algo-sdk 
		${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp 
		${CMAKE_CURRENT_SOURCE_DIR}/src/SmokeDetectAlgorithm.cpp		
		)

target_include_directories(test-algo-sdk
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include
        PUBLIC ${OpenCV_INCLUDE_DIRS})

target_link_libraries(test-algo-sdk
        ${OpenCV_LIBS}
        cjson
        m
#	${CMAKE_CURRENT_SOURCE_DIR}/build/libSmokeDetectAlgorithm.so
	dl
	)
```
**CMakeList.txt(.so only)**
```
cmake_minimum_required(VERSION 3.5)
project(algorithm-sdk)

set(CMAKE_CXX_STANDARD  11)
find_package(OpenCV REQUIRED)

 add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rd/cJSON)
#add_library(SmokeDetectAlgorithm  SHARED ${CMAKE_CURRENT_SOURCE_DIR}/src/SmokeDetectAlgorithm.cpp)
	   
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(#SmokeDetectAlgorithm
			cjson
			)

add_executable(test-algo-sdk 
		${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp 
#		${CMAKE_CURRENT_SOURCE_DIR}/src/SmokeDetectAlgorithm.cpp		
		)

target_include_directories(test-algo-sdk
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include
        PUBLIC ${OpenCV_INCLUDE_DIRS})

target_link_libraries(test-algo-sdk
        ${OpenCV_LIBS}
        cjson
        m
	${CMAKE_CURRENT_SOURCE_DIR}/build/libSmokeDetectAlgorithm.so
	dl
	)
```

**Comment by alalek** [comment]
1. Do not post test messages as screenshots. It is ridiculous and blocks searching for similar problems.
2. It is build configuration error of your application. There is nothing to fix in OpenCV. Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
