### ISSUE TITLE
cv2 read .tif picture strange problem

### ISSUE THREAD

**Issue by ustcmashuai** [opencv/opencv#15969]
I use cv2.imread deal with some .tif pictures, but the image ndarray is always uniform and really strange. The attachment is an example picture (it doesn't support .tif file, so I change the picture to .png). Who knows how to solve this problem? Thanks a lot.
![tif-image](https://user-images.githubusercontent.com/5077894/69405884-1532ca80-0d01-11ea-9b12-32b29062079d.PNG)
![show-image](https://user-images.githubusercontent.com/5077894/69405893-195ee800-0d01-11ea-9133-5aa76f7d95f0.PNG)

**Comment by alalek** [comment]
Both images are PNG (by **content**).
Try to attach through .zip archive and provide minimal code as reproducer.
Also include information about OpenCV version.

**Comment by ustcmashuai** [comment]
import cv2
img = cv2.imread('EM()(26.10.2018_13-01) 15.tif')
cv2.imshow('original',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

There is no error or alarm.
[images.zip](https://github.com/opencv/opencv/files/3882227/images.zip)

**Comment by ustcmashuai** [comment]
I tried pyplot. It works. But it cannot satisfy the following processings.

**Comment by alalek** [comment]
By default, OpenCV I/O functions works with 8-bit BGR images.
Your image is 16-bit. Truncation to 8-bit just lost information.

The same note is about `imshow()`. You have to define own data conversion to 8-bit (re-scaling through `convertTo` or `normalize`)

```
def dumpImage(flags):
    try:
        img = cv.imread(filename, flags)
        print(img.shape, img.dtype)
        print(img[300:305, 250:255])
    except Exception as e:
        print(e)

dumpImage(cv.IMREAD_COLOR)
dumpImage(cv.IMREAD_UNCHANGED)
```

<details>

```
(494, 659, 3) uint8
[[[128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]
  [128 128 128]]]
(494, 659) uint16
[[32785 32786 32781 32785 32777]
 [32781 32779 32781 32778 32779]
 [32782 32785 32776 32780 32777]
 [32779 32785 32780 32786 32781]
 [32778 32777 32779 32783 32781]]
```

</details>


---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
