### ISSUE TITLE
Video play or record is impossible!!

### ISSUE THREAD

**Issue by YsBsr** [opencv/opencv#15985]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I cant open a video and I can't record video from my webcam, always same iisue. I installed FFMPEG and it works fine. But opencv can't use FFMPEG and cannot play video or record video.

##### Steps to reproduce

'''
#include <opencv2/opencv.hpp>
#include <iostream>

using namespace cv;
using namespace std;

int main() {

	VideoCapture cap(0);

	if (!cap.isOpened()) return 1;

	int frame_width = cap.get(CAP_PROP_FRAME_WIDTH);
	int frame_height = cap.get(CAP_PROP_FRAME_HEIGHT);

	VideoWriter video("output.avi", ('M', 'J', 'P', 'G'), 10, Size(frame_width, frame_height), true);
/*VideoWriter always crushes*/
	return 0;
}

'''

And the Crush message is this.

OpenCV: FFMPEG: tag 0x00000047/'G???' is not found (format 'avi / AVI (Audio Video Interleaved)')'
[ERROR:0] global C:\opencv-4.1.2\modules\videoio\src\cap.cpp (392) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.1.2) C:\opencv-4.1.2\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): output.avi in function 'cv::icvExtractPattern'

[ WARN:0] global C:\opencv-4.1.2\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

Error screenshot
![ctush](https://user-images.githubusercontent.com/54865267/69492754-5371ea80-0eb7-11ea-81e7-8ffc6f161cbf.JPG)

**Comment by YsBsr** [comment]
Error screenshot
![ctush](https://user-images.githubusercontent.com/54865267/69492754-5371ea80-0eb7-11ea-81e7-8ffc6f161cbf.JPG)

**Comment by alalek** [comment]
"Crash" has a stack trace.
Where is it?

> exited with code 0

Not sure, if stack trace can be found due normal program exit.

> messages

There messages are about handling of unsupported input parameters.

---

This tracker is for issues and bugs that needs fix in OpenCV.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
