### ISSUE TITLE
The cv2 python module conflicts with TensorFlow

### ISSUE THREAD

**Issue by yurivict** [opencv/opencv#15982]
This Python code:
```
import cv2
import tflearn
```

causes this failure:
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:173] Symbol name "tensorflow.TensorShapeProto" conflicts with the existing symbol "tensorflow.TensorShapeProto".
[libprotobuf FATAL google/protobuf/descriptor.cc:1379] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Abort trap
```

I think ```BUILD_PROTOBUF``` might be related to this conflict, but setting ```BUILD_PROTOBUF=ON``` causes the build to fail: https://github.com/opencv/opencv/issues/15981

opencv-3.4.1
py36-tensorflow-1.14.0

**Comment by alalek** [comment]
You using outdated version of OpenCV. You should upgrade.
