### ISSUE TITLE
Feature-request: EfficientNet as backbone for Yolo v3 Detector:

### ISSUE THREAD

**Issue by AlexeyAB** [opencv/opencv#15987]
@dkurt Hi,

Feature-request: support **EfficientNet** as backbone for Yolo v3 Detector (this is just part of the changes for newer versions of Yolo):

* EfficientNetB0-Yolo - 45.5% mAP@0.5 - 3.7 BFLOPS - 1.5x less flops than Yolov3-tiny, but +12.1 higher mAP@0.5
* YOLOv3-tiny - 33.1% mAP@0.5 - 5.56 BFLOPS
* YOLOv3-416 - 55.3% mAP@0.5  - 65.86 BFLOPS

EfficientNetb0-Yolo:
* cfg-file: https://github.com/AlexeyAB/darknet/blob/master/cfg/enet-coco.cfg
* weights file: https://drive.google.com/file/d/1FlHeQjWEQVJt0ay1PVsiuuMzmtNyv36m/view
* coco.names file: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/coco.names

`./darknet detector test cfg/coco.data enet-coco.cfg enetb0-coco_final.weights dog.jpg`

----

* **45.5% mAP@0.5** on MS COCO: https://github.com/WongKinYiu/PartialResidualNetworks#partial-residual-networks
* **3.7 BFlops** (1.85B FMA in terms of google flops = **1.85 BFlops**)
*  2019 ICCV Workshop on Low-Power Computer Vision: https://github.com/WongKinYiu/PartialResidualNetworks/blob/master/pdf/iccvw-prn.pdf

----

EfficientNet B0 - B7:
* paper: https://arxiv.org/abs/1905.11946v2

| <img width="979" alt="params" src="https://user-images.githubusercontent.com/4096485/59429202-f6421b00-8de7-11e9-9b9e-95abae83a994.png"> | <img width="1070" alt="flops" src="https://user-images.githubusercontent.com/4096485/59429215-fb9f6580-8de7-11e9-9b6d-63ff4bddd897.png"> |
|-|-|
|  | |

----

Required changes:

* swish-activation: https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/cfg/enet-coco.cfg#L65

* groups for Grouped and Depth-wise convolution: https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/cfg/enet-coco.cfg#L48

* `[avgpool]` - Global average pooling layer - for squeeze and excitation blocks (as in MobileNet v3): https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/cfg/enet-coco.cfg#L112

* `[scale_channels]` - layer for squeeze and excitation blocks - it just multiply each of WxH element in channel-C in one layer (size WxHxC) by value from channel-C in another layer (size: 1x1xC) - source code: https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/src/scale_channels_layer.c#L61-L74
https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/cfg/enet-coco.cfg#L129-L130

![image](https://user-images.githubusercontent.com/4096485/69502064-1db31d00-0f1c-11ea-83fc-b0ec3c2189ec.png)

**Comment by YashasSamaga** [comment]
Is anyone working on this? I have it working in 4.2.0 for a personal project. I can make a PR into 3.4 branch with the changes.

**Comment by alalek** [comment]
@YashasSamaga It will be great!

**Comment by mmaaz60** [comment]
> Is anyone working on this? I have it working in 4.2.0 for a personal project. I can backport the relevant changes to 3.4 and make a PR for 3.4.

Hi @YashasSamaga,

I see you have a version of OpenCV 4.2.0 where you managed to EfficientNetb0-Yolo with OpenCV dnn module. Can I have the access to that branch? Thanks
