### ISSUE TITLE
Unable view image on Manjaro with python

### ISSUE THREAD

**Issue by JohnnyWobble** [opencv/opencv#15983]
##### System information (version)

- OpenCV => 4.1.2.30
- Operating System / Platform => Manjaro XFCE
- Compiler => PyCharm (python==3.7.5)

##### Detailed description

I am trying to use `imshow()` to view an image but it will print `Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed` and then image will be all black.

##### Steps to reproduce
```.py
import cv2
import os
import time

image = 'images/pencil.jpg'

if not os.path.exists(image): raise FileNotFoundError

img = cv2.imread(image)

cv2.imshow(image, img)

input("> ")
```
###### Full output
```
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
> 
```

**Comment by alalek** [comment]
Refer to `imshow()` documentation - you have missing `waitKey()` call.

---

> '/'

Try to avoid that in window names.

---

> 4.1.2.30

Perhaps you using opencv-python bundle (not supported in this repository).
It has own old Qt version, so it may conflict with system Qt. Try to rebuild OpenCV from sources with your system Qt.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by JohnnyWobble** [comment]
Thank you, and yes I am using opencv-python
