### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'LoadImage'

### ISSUE THREAD

**Issue by ucasiggcas** [opencv/opencv#15997]
##### Detailed description
when I used the code below,
`cv.LoadImage()`
it tells me the error
```
>>> cv.LoadImage()
Traceback (most recent call last):
  File "<pyshell#93>", line 1, in <module>
    cv.LoadImage()
AttributeError: module 'cv2.cv2' has no attribute 'LoadImage'
```

so how to solve the problem ?
thx

**Comment by dkurt** [comment]
> cv.LoadImage()

What is the source of this method? Looks like it was removed long time ago. Use `cv.imread` instead.

**Comment by copperCity17** [comment]
I was looking forward to LoadImage because imread always give me a NoneType. Do you know what I can do?
