### ISSUE TITLE
imread then imwrite will change the volume of the pic ?

### ISSUE THREAD

**Issue by ucasiggcas** [opencv/opencv#16005]
##### System information (version)
```
>>> cv2.__version__
'4.1.1'
>>> 
```
- Operating System / Platform => Windows 64 Bit
- Compiler => python
-->

##### Detailed description

I have two pics below,but use the same codes will get different results
first  gg.jpg got less volume
second gg6_th.jpeg got bigger volume

the pics and results
[img.zip](https://github.com/opencv/opencv/files/3895454/img.zip)
![image](https://user-images.githubusercontent.com/35590066/69700287-0b57ff80-1125-11ea-9b6b-a9ab6f5e3877.png)

##### Steps to reproduce
the same code 
```
>>> jpgfile='./gg6_th.jpeg'
>>> img=cv2.imread(jpgfile)
>>> cv2.imwrite('gg6_th_cv.jpg',img)
```

any advice and suggestion will be appreciated.
thx

**Comment by dkurt** [comment]
What is the source of origin jpeg? It can be produced by a different library.

Please use a forum for usage questions: answers.opencv.org or modify the issue to bug report - provide minimal working example with image attached.
