### ISSUE TITLE
libopencv_core.so: undefined reference to `__TBB_machine_fetchadd4'

### ISSUE THREAD

**Issue by shodow** [opencv/opencv#16019]
when i make opencv 3.4.3 in Ubuntu16.04, i get this error
```
../../lib/libopencv_core.so.3.4.3: undefined reference to `__TBB_machine_fetchadd4'
```
this is my cmake 
```
cmake ../../ -DCMAKE_BUILD_TYPE=RELEASE
 -DCMAKE_INSTALL_PREFIX=../install/ 
 -DCMAKE_C_COMPILER=aarch64-himix100-linux-gcc  
 -DCMAKE_CXX_COMPILER=aarch64-himix100-linux-g++ 
 -DBUILD_opencv_world=OFF 
 -DWITH_CUDA=OFF 
 -DWITH_FFMPEG=OFF 
 -DWITH_1394=OFF 
 -DWITH_GSTREAMER=OFF 
 -DWITH_V4L=OFF 
 -DWITH_CUBLAS=OFF 
 -DWITH_CUFFT=OFF 
 -DWITH_QT=OFF 
 -DWITH_GTK=OFF 
 -DWITH_IPP=OFF 
 -DWITH_NVCUVID=OFF 
 -DWITH_TIFF=OFF 
 -DWITH_TBB=OFF 
 -DZLIB_INCLUDE_DIR="~/tmp/opencv/testBuild/zlib/install/include" 
 -DZLIB_LIBRARY_RELEASE="~/tmp/opencv/testBuild/zlib/install/lib/libz.so" 
 -DZLIB_LIBRARY_DEBUG="~/tmp/opencv/testBuild/zlib/install/lib/libz.so" 
 -DPNG_PNG_INCLUDE_DIR="~/tmp/opencv/testBuild/png/install/include" 
 -DPNG_LIBRARY_DEBUG="~/tmp/opencv/testBuild/png/install/lib/libpng.so" 
 -DPNG_LIBRARY_RELEASE="~/tmp/opencv/testBuild/png/install/lib/libpng.so" 
 -DJPEG_INCLUDE_DIR="~/tmp/opencv/testBuild/jpg/install/include" 
 -DJPEG_LIBRARY="~/tmp/opencv/testBuild/jpg/install/lib/libjpeg.so"
```

**Comment by TuringKi** [comment]
You does not choose the plateform or operating system.

Solution:
1). touch a h3559av100.toolchains.cmake file:
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
SET(CMAKE_CXX_COMPILER aarch64-himix100-linux-g++)
SET(CMAKE_C_COMPILER aarch64-himix100-linux-gcc)
SET(CMAKE_FIND_ROOT_PATH /opt/hisi-linux/x86-arm/aarch64-himix100-linux/bin)

2).run the following cmd:
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_TOOLCHAIN_FILE=../platforms/linux/h3559av100.toolchains.cmake \
-D CMAKE_INSTALL_PREFIX=../output \
-D CMAKE_C_COMPILER=/opt/hisi-linux/x86-arm/aarch64-himix100-linux/bin/aarch64-himix100-linux-gcc \
-D CMAKE_CXX_COMPILER=/opt/hisi-linux/x86-arm/aarch64-himix100-linux/bin/aarch64-himix100-linux-g++ \
-D CMAKE_EXE_LINKER_FLAGS=-lpthread -lrt -ldl \
-D BUILD_SHARED_LIBS=OFF \
-D BUILD_ZLIB=ON \
-D ENABLE_NEON=ON \
-D WITH_CUBLAS=OFF \
-D WITH_CUDA=OFF \
-D WITH_OPENEXR=OFF \
-D WITH_GTK=OFF \
-D WITH_GSTREAMER=OFF \
-D WITH_TBB=OFF \
-D BUILD_TBB=OFF \
-D ZLIB_INCLUDE_DIR=../3rdparty/zlib \
../
