### ISSUE TITLE
error in res = cv2.matchTemplate(img_rgb, template, cv2.TM_CCOEFF_NORMED )

### ISSUE THREAD

**Issue by farigami** [opencv/opencv#16016]
error in res = cv2.matchTemplate(img_rgb, template, cv2.TM_CCOEFF_NORMED )
    res = cv2.matchTemplate(img_rgb, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1104: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

Process finished with exit code 1

from PIL import ImageGrab
import cv2
import pyautogui
import numpy as np
import time

average = [0, ]

template = cv2.imread('template.png', 0)
w, h = template.shape[::-1]
for _ in range(9999):
    time.sleep(1)
    pyautogui.press('pause')
    base_screen = ImageGrab.grab(bbox=(425, 420, 607, 564))
    base_screen.save('C:\\Users\\farigami\\Desktop\\project1337\\base_screen.png')

    img_rgb = cv2.imread('base_screen.png')
    img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB)

    res = cv2.matchTemplate(img_rgb, template, cv2.TM_CCOEFF_NORMED )
    loc = np.where(res >= 0.7)

for i in range(40):
    try:
        clean_screen = ImageGrab.grab(bbox=(x, y, x + w, y + h))
        mean = np.mean(clean_screen)
        diff = average[-1] - mean
        if diff >= 4:
            pyautogui.press('pause')
            break
        average.append(mean)
    except:
        for pt in zip(*loc[::-1]):
            x = int(pt[0])
            y = int(pt[1])
        time.sleep(0.5)
    try:
        del(x)
        del(y)
    except:
         pass
    average = [0, ]
    time.sleep(1)

**Comment by ajithvallabai** [comment]
This error comes if the image is not proper/not found . check the shape of img_rgb with img_rgb.shape before match template .
