### ISSUE TITLE
GStreamer features do not work

### ISSUE THREAD

**Issue by 132ikl** [opencv/opencv#16029]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Linux armv7l
- Compiler => GCC 8.3.0

##### Detailed description

Upon trying to create a VideoCapture or VideoWriter object using the GStreamer backend, the Python interpreter freezes indefinitely.

##### Steps to reproduce

1. Compile OpenCV with GStreamer support. May also need to be on an ARM platform.
2. Open the python3 interpreter.
3. import cv2 and create a new VideoCapture or VideoWriter object using the GStreamer backend. 
4. Press Ctrl+C.
5. Errors will appear. After this point, only a `kill -9` will stop the process.

Output:
```
pi@opensight:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> x = cv2.VideoCapture(1)
^C
(python3:1013): GStreamer-CRITICAL **: 03:20:46.243:
Trying to dispose element pipeline0, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

[ WARN:0] global /home/pi/opencv/opencv-4.1.2/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline

(python3:1013): GStreamer-CRITICAL **: 03:20:46.244:
Trying to dispose element videoconvert0, but it is in PLAYING instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

[ WARN:0] global /home/pi/opencv/opencv-4.1.2/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

(python3:1013): GStreamer-CRITICAL **: 03:20:46.244:
Trying to dispose element appsink0, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.
```

**Comment by 132ikl** [comment]
Build information: https://fs.ikl.sh/selif/ejzypqzg.file
Camera formats: https://fs.ikl.sh/selif/qmqou842.txt

**Comment by alalek** [comment]
Try to investigate:
- capture logs with `GST_DEBUG=4`
- capture stack traces of threads through GDB

Workaround: try to specify `cv.CAP_V4L2` explicitly:
```
cap = VideoCapture(0, cv.CAP_V4L2)
```

**Comment by 132ikl** [comment]
V4L2 does work as a workaround for VideoCapture, however things like GStreamer's VideoWriter are important for what I'm working on so unfortunately that is not a great solution.

GST_DEUBG=4 output: https://fs.ikl.sh/selif/xneorx06.file
GDB output w/ bt of GStreamer thread: https://fs.ikl.sh/selif/u666duxr.file

It seems to be failing to find a file at the path `sysdeps/unix/sysv/linux/arm/syscall.S`. This file doesn't seem to exist anywhere on the system based on a `find`.

Thanks!

**Comment by alalek** [comment]
> V4L2 does work as a workaround for VideoCapture

It works well on desktop Linux configurations.

> GST_DEBUG output
> Dropping truncated buffer, this is likely a driver bug.

GStreamer uses V4L2 API for camera access too.
**Please try to localize problem first.**
Try to use "gst-launch" tool to check camera without OpenCV:
- https://gstreamer.freedesktop.org/documentation/video4linux2/v4l2src.html?gi-language=c
- `gst-launch-1.0 -v v4l2src device=/dev/video0 ! video/x-raw,framerate=30/1,width=1280,height=720 ! xvimagesink` from [here](https://medium.com/@petehouston/play-webcam-using-gstreamer-9b7596e4e181)


> framerate=(fraction)60/1

Try to reduce framerate if it is possible (probably you need to write manual GStreamer pipeline for that, because it hands in "open")

> sysdeps/unix/sysv/linux/arm/syscall.S

This file is with source code only (.S - assembler code). It is not required.

> GDB output

Looks like It stucks in GStreamer code trying to read from the camera.

**Comment by 132ikl** [comment]
I have previously confirmed that a similar GStreamer pipeline works outside of OpenCV. The VideoWriter also suffers from the same issue. I will get logs for VideoWriter when I am at my computer.

**Comment by 132ikl** [comment]
I confirmed once again that the camera does indeed work using GStreamer directly, and it works using V4L2 video capture.

Here is my VideoWriter instantiation: `cv2.VideoWriter("appsrc ! video/x-raw,width=320,height=240,framerate=15/1 ! videoconvert ! video/x-raw,format=I420 ! shmsink socket-path=/tmp/testsocket", cv2.CAP_GSTREAMER, 30, (320, 240))`

Python Output: https://fs.ikl.sh/selif/sugae140.file
GDB output: https://fs.ikl.sh/selif/8u2kf38b.file

Thanks!

**Comment by Ayke** [comment]
I was having the similar issue as well, but I've solved by this gist:  https://gist.github.com/jkjung-avt/86b60a7723b97da19f7bfa3cb7d2690e

And I know it seems scary, but could you try running

```
width = 1920
height = 1080

gst_str = ('nvarguscamerasrc ! ' + 'video/x-raw(memory:NVMM), ' +
          'width=(int)1920, height=(int)1080, ' +
          'format=(string)NV12, framerate=(fraction)30/1 ! ' + 
          'nvvidconv flip-method=2 ! ' + 
          'video/x-raw, width=(int){}, height=(int){}, ' + 
          'format=(string)BGRx ! ' +
          'videoconvert ! appsink').format(width, height)

cap = cv.VideoCapture(gst_str, cv.CAP_GSTREAMER) 
```

and see if the `cap` works fine? The above script actually solved my issues

**Comment by husseinpasha** [comment]
> , cv.CAP_V4L2
Thanks!
Changing **cv.CAP_V4L2**  to **cv2.CAP_V4L2** solved the issue.
