### ISSUE TITLE
error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)

### ISSUE THREAD

**Issue by tupm97** [opencv/opencv#16022]
System information (version)
OpenCV => 3.4.1 Android SDK
Operating System / Platform => Windows 64 Bit (for coding),
Compiler => Android studio 3.3
I am using NDK r20b

Detailed description
I am trying to make an app for face detection on android using opencv.
but every time i try to build the project  it is giving me error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::ndk1::vector<cv::Rect, std::ndk1::allocator<cv::Rect > >&, double, int, int, cv::Size, cv::Size)'

**Comment by hensonwells** [comment]
> System information (version)
> OpenCV => 3.4.1 Android SDK
> Operating System / Platform => Windows 64 Bit (for coding),
> Compiler => Android studio 3.3
> I am using NDK r20b
> 
> Detailed description
> I am trying to make an app for face detection on android using opencv.
> but every time i try to build the project it is giving me error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::ndk1::vector<cv::Rect, std::ndk1::allocator<cv::Rect > >&, double, int, int, cv::Size, cv::Size)'



> System information (version)
> OpenCV => 3.4.1 Android SDK
> Operating System / Platform => Windows 64 Bit (for coding),
> Compiler => Android studio 3.3
> I am using NDK r20b
> 
> Detailed description
> I am trying to make an app for face detection on android using opencv.
> but every time i try to build the project it is giving me error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::ndk1::vector<cv::Rect, std::ndk1::allocator<cv::Rect > >&, double, int, int, cv::Size, cv::Size)'

Hello，I got the same issue as you,did you figure it out ?Could you share the way you work out？Thx~
