### ISSUE TITLE
FacemarkAAM example refers to non-existant functionality/code in OpenCV?

### ISSUE THREAD

**Issue by patrikhuber** [opencv/opencv#16038]
Hi, the docs contain this tutorial/example:
https://docs.opencv.org/4.1.2/d5/dd8/tutorial_facemark_aam.html

However nowhere can I find a sample or the FacemarkAAM library code in question.

The only thing faintly related I can find is an old transferred issue #4271.

Does above tutorial refer to code that ever existed in OpenCV?

**Comment by alalek** [comment]
Check this: https://github.com/opencv/opencv_contrib/tree/4.1.2/modules/face/samples

**Comment by patrikhuber** [comment]
Aah! This stuff is in the contrib module. The tutorial even mentions this in its breadcrumbs ("Tutorials for contrib modules") but it's quite small and it wasn't obvious to me. Thank you very much.
