### ISSUE TITLE
OpenCV 4.1.2 cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE cv2.dnn.DNN_TARGET_OPENCL

### ISSUE THREAD

**Issue by heiheiya** [opencv/opencv#16043]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I compiled OpenCV4.1.2 from source , add OpenVINO R3 support and banding to python3.6.4.
When i use net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_OPENCL) to load darknet yolov3.weights, it comes to failed with log:
cv2.error: OpenCV(4.1.2) D:\software\opencv-4.1.2\modules\dnn\src\op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Unsupported primitive of type: OpenCVLayer name: yolo_106 in function 'cv::dnn::InfEngineBackendNet::initPlugin'

Can anyone help me?

**Comment by alalek** [comment]
Looks like it is not supported for [now](http://pullrequest.opencv.org/buildbot/builders/master_openvino-opencl-win64/builds/59/steps/test_dnn-opencl/logs/stdio):
```
[ RUN      ] Test_Darknet_nets.YOLOv3/1, where GetParam() = DLIE/OCL
[     SKIP ] Test with tag 'dnn_skip_ie_ocl' is skipped ('dnn_skip_ie_ocl' is in skip list)
[       OK ] Test_Darknet_nets.YOLOv3/1 (2507 ms)
```

**Comment by alalek** [comment]
@dkurt Please update list in #11866 and close this issue as a duplicate (lets track DNN tests in single place)

**Comment by heiheiya** [comment]
But I have built opencv 4.1.2 with OpenVINO R1, it's OK.

**Comment by dkurt** [comment]
@heiheiya, May we ask to try the latest OpenVINO and OpenCV? Seems like all the targets except Myriad work fine according to the tests:
```
[ RUN      ] Test_Darknet_nets.YOLOv3/4, where GetParam() = NGRAPH/CPU
[       OK ] Test_Darknet_nets.YOLOv3/4 (3083 ms)
[ RUN      ] Test_Darknet_nets.YOLOv3/5, where GetParam() = NGRAPH/MYRIAD
[     SKIP ] Test with tag 'dnn_skip_ie_myriadx' is skipped ('dnn_skip_ie_myriadx' is in skip list)
[       OK ] Test_Darknet_nets.YOLOv3/5 (0 ms)
[ RUN      ] Test_Darknet_nets.YOLOv3/6, where GetParam() = NGRAPH/OCL
[       OK ] Test_Darknet_nets.YOLOv3/6 (5059 ms)
[ RUN      ] Test_Darknet_nets.YOLOv3/7, where GetParam() = NGRAPH/OCL_FP16
[       OK ] Test_Darknet_nets.YOLOv3/7 (2702 ms)
```

**Comment by heiheiya** [comment]
@dkurt OpenCV4.2.0 is OK
