### ISSUE TITLE
cvGetSize break!

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencv/opencv#16042]
##### Steps to reproduce

I use the cvGetSize to get the cvsize, but it break, as:
![图片](https://user-images.githubusercontent.com/40679769/70016424-43df5980-15bb-11ea-8884-dc29525f3ff3.png)

**Comment by alalek** [comment]
> cv::Exception

It is programmer responsibility to handle C++ exceptions (they are usually raised in case of invalid inputs).

Please note, that OpenCV C API is dead and broken more than 5 years ago. Do not use that anymore with modern OpenCV.
