### ISSUE TITLE
Reading JPEG file fails on Windows 10, Python 2.7 (file attached, other files work)

### ISSUE THREAD

**Issue by sshankar-rks** [opencv/opencv#16044]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Windows 10 (Version 1809)/
- Compiler => Installed from conda-forge/Environment has Python 2.7

##### Detailed description

The attached file breaks imread, which produces None as a result. Windows Explorer and Photo Viewer work fine with the file as  does Paint.Net. PyPlot reads the file, but can't display it with imshow.

##### Steps to reproduce

```
# fill in the filepath to wherever you save the attached file
filepath = ""
print(filepath)
if os.path.isfile(filepath):
    print("File:" + filepath + " exists")
    img = cv.imread(filepath)
    print("OpenCV read")
    print(img)
else:
    print("File: " + filepath + " does not exist")
```

![303386424685_orig](https://user-images.githubusercontent.com/57481549/70035730-75671d80-15d9-11ea-809d-20d64f59837f.jpg)

**Comment by dkurt** [comment]
> OpenCV => 3.2.0

Have you tried newer releases?

**Comment by sshankar-rks** [comment]
I installed via the Conda-Forge channel, don't want to build on my own.

**Comment by alalek** [comment]
So do you prefer using 3 years old release?

> Conda-Forge

This distribution is not maintained here. We can't this anything here.
