### ISSUE TITLE
When using solvePnPGeneric to get reprojectionError, exception occurred.

### ISSUE THREAD

**Issue by hanseun** [opencv/opencv#16040]
solvePnPGeneric work normally when reprojectionError parameter is skipped, but exception occurred reprojectionError parameter was sent to the function.

...
Mat reprojectionError = new Mat(2,1,CvType.CV_64FC1);
Calib3d.solvePnPGeneric(objectPoints, imgPointsMat, cameraMatrix, distCoeffs, rvecs, tvecs, false, Calib3d.SOLVEPNP_IPPE, rvec, tvec, reprojectionError);
...

- Environment : java
- Version : opencv 4.1.1 / opencv_contrib 4.1.1
- Log: 

Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) ../modules/core/src/norm.cpp:1018: error: (-215:Assertion failed) _src1.sameSize(_src2) && _src1.type() == _src2.type() in function 'norm'
    ]
        at org.opencv.calib3d.Calib3d.solvePnPGeneric_0(Native Method)
        at org.opencv.calib3d.Calib3d.solvePnPGeneric(Calib3d.java:6641)

**Comment by alalek** [comment]
Please provide minimal complete reproducer (including some input data).
Take a look on current Java [tests](https://github.com/opencv/opencv/blob/4.1.2/modules/calib3d/misc/java/test/Calib3dTest.java).

Could you try this too?
```.diff
-Mat reprojectionError = new Mat(2,1,CvType.CV_64FC1);
+Mat reprojectionError = new Mat();
```

**Comment by vwvw** [comment]
I was testing solvePnpGeneric in Python (4.1.2) today and encountered the same error.
Here the code:

```python
import numpy as np
import cv2

obj_points = np.array([[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 0]], dtype=np.float32)
img_points = np.array(
    [[700, 400], [700, 600], [900, 600], [900, 400]], dtype=np.float32
)

cameraMatrix = np.array(
    [[712.0634, 0, 800], [0, 712.540, 500], [0, 0, 1]], dtype=np.float32
)
distCoeffs = np.array([[0, 0, 0, 0]], dtype=np.float32)
r = np.array([], dtype=np.float32)
x, r, t, e = cv2.solvePnPGeneric(
    obj_points, img_points, cameraMatrix, distCoeffs, reprojectionError=r
)
print(e)
print(t)
```

I can fix the error if I create img_points in this way (notice the extra array).

```python
img_points = np.array(
    [[[700, 400], [700, 600], [900, 600], [900, 400]]], dtype=np.float32
)
``` 
Hope this can help debugging!
