### ISSUE TITLE
opencv_fls_destructor called after DLL unloaded

### ISSUE THREAD

**Issue by hglee** [opencv/opencv#16041]
##### System information (version)

- OpenCV => 4.1 master
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I'm try master branch with .NET assembly and testing with xunit.

But most of time it crashed at end of xunit running.

Detail windbg trace attached:

[20191203_crash.txt](https://github.com/opencv/opencv/files/3914096/20191203_crash.txt)

**Comment by alalek** [comment]
Thank you for the report!
Could you try this patch: #16055 ?

**Comment by hglee** [comment]
> 
> 
> Thank you for the report!
> Could you try this patch: #16055 ?

It works, thanks.

Tested under 4.1 master branch.
