### ISSUE TITLE
net.forward() for the given model works on python but not c++

### ISSUE THREAD

**Issue by RaniemAR** [opencv/opencv#16047]
I am testing the opencv 4.1.1 on windows 10 Pro x64.
I have frozen part of the model in the cited paper below. 

However, the same code with the same frozen model works just fine in python but not in c++.
in python I am getting the output i am expecting but in c++ version i am getting an empty mat (1*-1*-1

Screenshot of the C++ code:
![c++](https://user-images.githubusercontent.com/15360299/70052408-21edd300-15cb-11ea-9f5e-765ecd216852.png)

Screenshot of the python code:

![python](https://user-images.githubusercontent.com/15360299/70052409-21edd300-15cb-11ea-83c3-f0110091dd98.png)

 )

The frozen model is 30 MB I couldn't attach it here but I have attached the corresponding .pbtxt file
[original_model_exported.zip](https://github.com/opencv/opencv/files/3916635/original_model_exported.zip)

model summary: 
[model_summary.txt](https://github.com/opencv/opencv/files/3916652/model_summary.txt)

@inproceedings{wu2018eccv,
  title={BusterNet: Detecting Image Copy-Move Forgery With Source/Target Localization},
  author={Wu, Yue, and AbdAlmageed, Wael and Natarajan, Prem},
  booktitle={European Conference on Computer Vision (ECCV)},
  year={2018},
  organization={Springer},
}

**Comment by alalek** [comment]
Mat's `.rows`, `.cols` is for 2D arrays only. These fields can't be used with 4D arrays (`.forward()` returns 4D array).
Use `.dims` and `.size[i]` instead.

**Comment by RaniemAR** [comment]
Thanks, I am really sorry I thought this is an issue. My bad.
Thanks for your reply.
Regards
