### ISSUE TITLE
While cross-validation one or more of the classes have "   "been fell out of the sample. Try to reduce <Params::k_fold>

### ISSUE THREAD

**Issue by ZTFtrue** [opencv/opencv#16059]
##### System information (version)

- OpenCV => 4.1.2-dev
- Operating System / Platform => ArchLinux 5.3.11-arch1-1 x86_64 GNU/Linux (31.0 GiB)
- Compiler => Eclipse/Cmake

##### Detailed description

When i try to set kFold=5 , kFold=2 and kFold=9 , it throw ```While cross-validation one or more of the classes have "
                "been fell out of the sample. Try to reduce <Params::k_fold>```
 
I try to set kFold=20 , now it's ok, I searched this [issues](https://github.com/opencv/opencv/issues/5699),what should I do? 
##### Steps to reproduce

code:

```c++
outSVM = cv::ml::SVM::create();
outSVM->setType(SVM::C_SVC);
outSVM->setKernel(SVM::CHI2);
Ptr<TrainData> pt = ml::TrainData::create(samples, ml::ROW_SAMPLE, labels);
std::cout << "labels size : " << labels.size() << std::endl;
std::cout << "samples rows : " << samples.rows << std::endl;
std::cout << "samples cols : " << samples.cols << std::endl;
bool result = outSVM->trainAuto(pt, 5);
outSVM->save("svm.xml");
```
out put:

```c++
labels size : 9
samples rows : 9
samples cols : 10
```

 ##### Resource

 [Download lables and samples from google drive ](https://drive.google.com/open?id=1H-8j34qnj0WCY-O4kb517aDUzUVPghUC)

**Comment by alalek** [comment]
> labels size : 9

are labels have 9 different values? If so, this dataset is bad and Machine Learning (ML) can't help here.

For dictionary searching take a look on flann.

**Comment by ZTFtrue** [comment]
thank you , i understand
