### ISSUE TITLE
Is it possible to pass parameters to the FFMPEG backend?

### ISSUE THREAD

**Issue by bkarpati** [opencv/opencv#16058]
##### System information (version)

- OpenCV => Master
- Operating System / Platform => Any
- Compiler => Any

##### Detailed description
I am using the FFV1 codec proivded by FFMPEG to record videos with `VideoWriter`. This defaults to using FFV1 version 3, however, I would like to change the codec used to FFV1 version 1. In plain FFMPEG this can be done by passing the `-level 1` flag to the call.

Is it possible to do something like this through OpenCV? So far, I have not found anything useful regarding this.

I have asked the same [question](https://answers.opencv.org/question/222493/setting-codec-parameters-with-ffmpeg-backend/) on the forum but have recieved no response. Hence I am asking here as well.

**Comment by alalek** [comment]
duplicate of #6342

**Comment by bkarpati** [comment]
> 
> 
> duplicate of #6342

Have not found this issue previously, thanks!
