### ISSUE TITLE
approxPolyDP OOMs

### ISSUE THREAD

**Issue by mcellis33** [opencv/opencv#16053]
### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Linux 64 Bit
- Compiler => x86_64-linux-gnu-g++-8

##### Detailed description

For certain contours, if approxPolyDP is passed an epsilon of NaN, then it OOMs.

This may simply be a request for input validation in approxPolyDP, because I believe an epsilon of NaN is meaningless.

##### Steps to reproduce

Here is a fairly minimal repro. Note that this uses the same contour as in the repro of #16051. You may need to tweak the headers/namespaces.
```
#include "third_party/OpenCVX/include/opencv2/imgproc/imgproc.hpp"
int main(int argc, char **argv) {
  std::vector<cv::Point> contour(
      {cv::Point(2085, 1415), cv::Point(2087, 1415), cv::Point(2089, 1414),
       cv::Point(2089, 1414), cv::Point(2087, 1412)});
  float epsilon = NAN;
  std::vector<cv::Point> approx;
  cv::approxPolyDP(contour, approx, epsilon,
                    true /* closed curve */);
  // The process will OOM before getting here.
}
```

**Comment by saskatchewancatch** [comment]
Epsilon is the error "distance" between the approximation and input polyline. So NaN in the Douglas-Peucker algo would cause it to go overboard. I agree,
 ` CV_Error( Error::StsBadArg, "Epsilon not valid." )` seems like a good response?

**Comment by alalek** [comment]
@saskatchewancatch Agreed on error message, like this:
```
if (epsilon < 0 || !(epsilon < 1e30))
    CV_Error(...)
```

with simple regression test `test_approxpoly.cpp` with `ASSERT_ANY_THROW(cv::approxPolyDP(...));` check (avoid using of legacy testing approach with classes - [use this as example](https://github.com/opencv/opencv/blob/3.4.8/modules/imgproc/test/test_contours.cpp#L488-L500))

Target branch is 3.4

**Comment by saskatchewancatch** [comment]
PR #16094 should take care of this.
@alalek as it turns out there was already a test file for polyapprox, so I added a test there.
