### ISSUE TITLE
Why can not the intersectConvexConvex support CV_64F inputs for years?

### ISSUE THREAD

**Issue by SunAriesCN** [opencv/opencv#16067]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Android 9
- Compiler => Android Studio 

##### Detailed description
Why can not the intersectConvexConvex support CV_64F inputs for years?
```
 OpenCV(4.1.2-dev) Error: Assertion failed (p1.depth() == CV_32S || p1.depth() == CV_32F) in intersectConvexConvex, file ../../modules/imgproc/src/geometry.cpp, line 493
```

**Comment by alalek** [comment]
There is no goal to support all possible flavors.
OpenCV is pre-compiled library, so nobody wants exploded binaries for several GBs.

`CV_32F` should be enough for normal cases (pixel-size errors from cameras are much higher).

Without real use case this request would be rejected.
