### ISSUE TITLE
import cv2 error [python3]

### ISSUE THREAD

**Issue by portgasray** [opencv/opencv#16064]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 18.04
- Compiler => cmake3.10.2

##### Detailed description

It caused an error following after ` import cv2` under `python3`

```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopencv_ml.so.4.1: cannot open shared object file: No such file or directory
>>> 

```

##### Steps to reproduce

compile with
```
cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/usr/local \
-D OPENCV_EXTRA_MODULES_PATH=<path>/opencv_3.4.2_build/opencv_contrib/modules/ ..
```

**Comment by portgasray** [comment]
I am not sure, this problem whether caused by I installed opencv4.1.x and uninstalled before. Even though, I had already cleaned the environment well.

**Comment by portgasray** [comment]
![repeat](https://user-images.githubusercontent.com/17681580/74294207-21667b00-4d78-11ea-9632-56c33065b2a9.PNG)
![repeat2](https://user-images.githubusercontent.com/17681580/74294220-29261f80-4d78-11ea-85e4-5ef58b2c60a2.PNG)
![repeat3](https://user-images.githubusercontent.com/17681580/74294230-2c211000-4d78-11ea-890d-cea4a462b3fa.PNG)

remove 'cv2' folder from ```/usr/local/lib/python3.6/dist-packages```

**Comment by kkrusher** [comment]
I have the same problem. At the first time I install opencv-python, the libopencv-dev version is 3.4. After I uninstall libopencv-dev3.4 and install libopencv-dev4.2, "import cv2" still search for libopencv_ml.so.3.4. I wonder if this situation is 
 not considered by developers of opencv.

The solution is to create another conda environment and install opencv-python again.
