### ISSUE TITLE
Opencv DNN Inference Engine FPGA Target

### ISSUE THREAD

**Issue by balachandarsv** [opencv/opencv#16060]
Tried using the FPGA Target in Inference Engine using OPENCV Dnn. Getting the following error. 
I tried setting the library path as LD_LIBRARY_PATH still the same error. 

opencv-4.1.2/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) in function 'initPlugin'
> Failed to initialize Inference Engine backend: Failed to create plugin /opt/intel/openvino_2019.3.376/deployment_tools/inference_engine/lib/intel64/libdliaPlugin.so for device FPGA
> Please, check your environment
> Cannot load library '/opt/intel/openvino_2019.3.376/deployment_tools/inference_engine/lib/
]

The same model works on CPU Target. 

How to solve this issue?

**Comment by dkurt** [comment]
@balachandarsv, Hi!

Do you use FPGA distribution of OpenVINO?

**Comment by scianand** [comment]
Hi

**Comment by balachandarsv** [comment]
@dkurt Yes. I am using FPGA Distribution only.

**Comment by alalek** [comment]
> Cannot load library

Running `LD_DEBUG=libs <your_app>` should help with investigation.

**Comment by balachandarsv** [comment]
I was able to solve this by keeping the libs in intel fpga sdk folder.

But while running the googlenet model (bvlc_googlenet.caffemodel) I am getting the following error. 

How to activate heterogeneous plugin of InferenceEngine from opencv?  

OpenCV(4.1.2) /opt/opencv-4.1.2/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) in function 'initPlugin'
> Failed to initialize Inference Engine backend: Graph is not supported on FPGA plugin due to existance of layer (Name: pool1/norm1, Type: Norm)
> in topology. Most likely you need to use heterogeneous plugin instead of FPGA plugin directly.
> ]

**Comment by dkurt** [comment]
@balachandarsv, Please check the following code execution:

https://github.com/opencv/opencv/blob/8108fb0575e6470d92f744244064472a57056031/modules/dnn/src/op_inf_engine.cpp#L742-L765

**Comment by balachandarsv** [comment]
@dkurt I tried the same with the above commit, still the same response. 


Most likely you need to use heterogeneous plugin instead of FPGA plugin direct

**Comment by dkurt** [comment]
@balachandarsv, I just wanted to ask, which code part is used (2019R1 or another one) and which device name is used there ("CPU" or "HETERO:FPGA,CPU"). Please check it by print.

**Comment by balachandarsv** [comment]
@dkurt  I am using opencv JAVA bindings.  I will try to use the c++ and update here.

**Comment by balachandarsv** [comment]
@dkurt Device name : FPGA , ishetero : true . Its branching to the else part, not to 2019R1. 

Device name is not changing to HETERO:FPGA,CPU. 

It's still FPGA.

I printed these in the catch block in that function.

**Comment by dkurt** [comment]
@balachandarsv, thanks!

Can you please provide a model to reproduce it?

**Comment by balachandarsv** [comment]
Mobilenet Model : 

https://download.01.org/opencv/2019/open_model_zoo/R2/20190628_180000_models_bin/mobilenetv2-int8-tf-0001/FP16/

Googlenet Model : https://github.com/intel/caffe/tree/master/models/bvlc_googlenet 

You can use either of these models. 

I just used model optimizer to convert the googlenet model to FP16 for bin and xml files so that i can run using IE.

**Comment by ilya-lavrenov** [comment]
Could you please run LoadNetwork for HETERO:FPGA,CPU device with additional flags HETERO_CONFIG_KEY(DUMP_GRAPH_DOT) -> YES?

It forces HETERO plugin to dump .dot files which shows how HETERO plugin splitted layers between CPU and FPGA devices.

**Comment by dkurt** [comment]
Please also try the following code to check that the problem inside OpenCV:
```python
from openvino.inference_engine import IENetwork, IECore

net = IENetwork('mobilenetv2-int8-tf-0001.xml', 'mobilenetv2-int8-tf-0001.bin')

ie = IECore()
ie.add_extension('libcpu_extension_avx2.so', "CPU")
exec_net = ie.load_network(net, 'HETERO:FPGA,CPU')
```

**Comment by balachandarsv** [comment]
@dkurt  I am not getting any error while running the code you shared. It runs without any warning. 
<img width="1037" alt="Screenshot 2019-12-06 at 9 53 01 PM" src="https://user-images.githubusercontent.com/6115858/70338379-d65d5280-1872-11ea-8bce-7f69b4470297.png">


@ilya-lavrenov I am not sure how to do that. Can you please let me know how to proceed ?

**Comment by dkurt** [comment]
@balachandarsv, @ilya-lavrenov, thanks for help!

It's a bug on OpenCV side. Here is a patch: https://github.com/opencv/opencv/pull/16089

**Comment by balachandarsv** [comment]
Thanks @dkurt Its working fine now. 

Out of context, Is there any way to improve the execution speed in Hetero plugin?

When running on CPU Target, the image takes 20 ms
But on FPGA,CPU it takes around 600ms.

Any idea why this happens?
Is it because of too many CPU<->FPGA layer switches?

**Comment by dkurt** [comment]
Please dump an affinity graph as @ilya-lavrenov suggested. This way we can see the exact hardware utilisation.
