### ISSUE TITLE
Error Loading frozen graph(.pb) using readNet

### ISSUE THREAD

**Issue by AbhishekNalamothu** [opencv/opencv#16075]
System information (version)
OpenCV => 4.1.2
[Google colab](https://colab.research.google.com/drive/1-RYmFFH1-uUKPnuU6rZ3FgAgIaPQPYGk) - this notebook reproduce the errors.

@dkurt @alalek I am getting the following errors while trying to read `.pb` and` .pbtxt` of darknet using readNet/readNetFromTensorflow/readNetFromDarknet. 

**readNet/readNetFromTensorflow(.pb,.pbtxt)**  
`error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:663: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'
`
**readNet/readNetFromTensorflow(.pb)**
`error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:569: error: (-2:Unspecified error) More than one input is Const op in function 'getConstBlob'  
`

**readNetFromDarknet(.pb,.pbtxt)/readNetFromDarknet(.pb)**
`error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:509: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'`

I did find a lot of similar opencv github issues with solutions and tried them but they did not work for my problem. 

Please help me with this error. Thank you

**Comment by alalek** [comment]
> readNetFromDarknet(.pb,.pbtxt)/readNetFromDarknet(.pb)

Invalid usage: this function can't handle models in Tensorflow format.

`readNetFromDarknet()` can load native models in Darknet format only.
Consider using this way with Darknet original native network (without Tensorflow converter).

Perhaps Tensorflow converter adds some extra still unsupported layers or tricky unsupported sub-graphs. OpenCV TF importer can't handle that properly yet, so you see the first exception.

**Comment by AbhishekNalamothu** [comment]
@alalek Thanks for the prompt response.  
I am trying to read `.pb` & `.pbtxt` files using readNet (or similar)functions of opencv. In **Darkflow**,  I don't get `.cfg` and `.weights` files after training my own models. I can only get `.pb`  from checkpoint.   
In the colab noteboook, I tried `readNet` and `readNetFromTensorflow` to read `.pb` & `.pbtxt` . They also did not work. 

`I am looking for a way to read .pb and .pbtxt of my trained models using opencv`

Please help me with this. Thank you once again. :)

**Comment by alalek** [comment]
> after training my own models

Post training make sense.

Could you please upload these files on Google Drive and share a link? (can't extract them from colab space by myself)
- `/content/darkflow/DW2TF/data/yolov2-tiny.pb`
- `/content/darkflow/DW2TF/data/yolov2-tiny.pbtxt`

**Comment by AbhishekNalamothu** [comment]
Sure.
Please find the attachments :  

[yolov2-tiny.pb ](https://drive.google.com/file/d/1LSb3-q44dYNUrdNcPa3HuWPD-rPAfmoO/view?usp=sharing)

[yolov2-tiny.pbtxt](https://drive.google.com/file/d/1x6AcnJIm26H6DOgIgs_CwYCR1_tH-xmV/view?usp=sharing)

Also, running the colab notebook from the beginning would create` .pb` and `.pbtxt`

Thank you :)

**Comment by AbhishekNalamothu** [comment]
@bsekachev  and @dkurt , could you guys also please take a look into [it](https://colab.research.google.com/drive/1-RYmFFH1-uUKPnuU6rZ3FgAgIaPQPYGk)? I have been stuck in this error from past few weeks. Any help would be really appreciated.   
Thank you so much :)

**Comment by giorgiomondauto** [comment]
Is there actually a way to convert tensorflow weights or pb files into darknet format in order to use readNetFromDarknet(modelConfiguration, modelWeights)??

**Comment by rogday** [comment]
@AbhishekNalamothu, your graph is still trainable(it contains VariableV2 nodes). OpenCV requires frozen graphs.
