### ISSUE TITLE
Unintuitive exception message in C++ (calibrateCamera: assertion failed, ni == ni1)

### ISSUE THREAD

**Issue by torresguilherme** [opencv/opencv#16095]
OpenCV version 4.1.1
on Linux openSUSE Tumbleweed
Compiler is g++

##### Detailed description
I get this error message when trying to call calibrateCamera. I searched on it in some foruns and found out that it can mean that either:

- my vectors of object points and image points are not the same size (in my case, they are, I did check that)

- the type is wrong (in this case, I have no idea what to do).

Anyway, this message is really not intuitive and aside from some help with my situation I'd appreciate if this exception could have a better error message.
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.1) /home/abuild/rpmbuild/BUILD/opencv-4.1.1/modules/calib3d/src/calibration.cpp:3349: error: (-215:Assertion failed) ni == ni1 in function 'collectCalibrationData'
```

##### Steps to reproduce

My module can be seen here: https://github.com/torresguilherme/bakeneko/blob/master/src/calibration/calibration.cpp

thanks in advance for your work and the assistance

**Comment by catree** [comment]
Quick look. This [code](https://github.com/torresguilherme/bakeneko/blob/415560cee5c19ed1d0244f968ba5eb609334823c/src/calibration/calibration.cpp#L16-L20) looks not correct:

```
obj_corner_points_in_3d.assign({
        cv::Point3f(0.0, 0.0, 0.0),
        cv::Point3f(0.0, CHESSBOARD_HEIGHT * CHESSBOARD_SQUARE_LENGTH, 0.0),
        cv::Point3f(CHESSBOARD_WIDTH * CHESSBOARD_SQUARE_LENGTH, CHESSBOARD_HEIGHT * CHESSBOARD_SQUARE_LENGTH, 0.0),
        cv::Point3f(CHESSBOARD_WIDTH * CHESSBOARD_SQUARE_LENGTH, 0.0, 0.0)
    });
```

You should have `CHESSBOARD_HEIGHT*CHESSBOARD_WIDTH` numbers of `objectPoints` (same number than the corners detected by `findChessboardCorners`).

There is already a sample file that performs the calibration: [`calibration.cpp`](https://github.com/opencv/opencv/blob/4.1.2/samples/cpp/calibration.cpp).

**Comment by torresguilherme** [comment]
Understood. I took a look at the ``calibration.cpp`` code and will fix mine

**Comment by torresguilherme** [comment]
@alalek from what I see the changes were pretty much on point. Very nice, I'll approve it. I remember there being also other points in the code where the error messages tell the user little to nothing, if I find one in partucular I'll report it, or maybe fix them myself (depends on how much time I have on my hands)

**Comment by BadMachine** [comment]
I had the same exception, my advice:
check object poinst and image points vector's size, it should be the same if I'm not mistaken.
Also its better to use different width/height chessboard size to avoid problems with rotation perception.

**Comment by torresguilherme** [comment]
@BadMachine ok, my calibration works now, I'm getting a high mean square error but I have my ways to lower it. Thanks for tips

**Comment by BadMachine** [comment]
@torresguilherme 
Also I can share part of my calib code
```c++

void CalcBoardCornerPositions(cv::Size boardSize, double squareSize, std::vector<cv::Point3f>& corners) { //24 //4
	corners.clear();
	for (int i = 0; i < boardSize.height; ++i)
		for (int j = 0; j < boardSize.width; ++j)
			corners.push_back(cv::Point3f(float(j * squareSize), float(i * squareSize), 0));
}

int numSquares = numCornersHor * numCornersVer;
		Size board_sz = Size(numCornersHor, numCornersVer);

		vector<vector<Point3f>> object_points;
		vector<vector<Point2f>> image_points;

		vector<Point2f> corners;
		vector<vector<Point3f>> object_points2;
		vector<vector<Point2f>> image_points2;

		vector<Point2f> corners2;








		int successes = 0;
		int successes2 = 0;
		Mat image;
		Mat image2;
		Mat gray_image;
		Mat gray_image2;
	
		vector<Point3f> obj;
		int z = 0;
		CalcBoardCornerPositions(board_sz, 4, obj);

		while (successes < numBoards)
		{
			capture >> image;
			tapture >> image2;
			cvtColor(image, gray_image, COLOR_BGR2GRAY);
			cvtColor(image2, gray_image2, COLOR_BGR2GRAY);

			bool found = findChessboardCorners(image, board_sz, corners, CALIB_CB_ADAPTIVE_THRESH | CALIB_CB_FILTER_QUADS);
			bool found2 = findChessboardCorners(image2, board_sz, corners2, CALIB_CB_ADAPTIVE_THRESH | CALIB_CB_FILTER_QUADS);

			if (found && found2)
			{
				z++;
				cout << "Captured " << z << endl;
				cornerSubPix(gray_image, corners, Size(11, 11), Size(-1, -1), TermCriteria(cv::TermCriteria::EPS | cv::TermCriteria::MAX_ITER, 30, 0.1));
				cornerSubPix(gray_image2, corners2, Size(11, 11), Size(-1, -1), TermCriteria(cv::TermCriteria::EPS | cv::TermCriteria::MAX_ITER, 30, 0.1));
				drawChessboardCorners(gray_image, board_sz, corners, found);
				drawChessboardCorners(gray_image2, board_sz, corners2, found2);
			}

			imshow("win1", image);
			imshow("win2", gray_image);
			imshow("win3", image2);
			imshow("win4", gray_image2);

			capture >> image;
			tapture >> image2;
			int key = waitKey(1);

			if (key == 27)

				return 0;

			if (key == 32 && found != 0)
			{
				image_points.push_back(corners);
				image_points2.push_back(corners2);
				object_points.push_back(obj);

				printf("Snap stored!");

				successes++;

				if (successes >= numBoards)
					break;
			}
		}
```

**Comment by torresguilherme** [comment]
No worries, the issue with my high MSE isn't probably in the code but the lack of images/different poses for the chessboard. And after alalek's merging I don't think there's a reason to keep this issue open anymore
