### ISSUE TITLE
4.1.2 test suite is failing

### ISSUE THREAD

**Issue by kloczek** [opencv/opencv#16099]
Full build log with executed after build test suite is in attachment. Here is only summary list of failed tests:
<pre>Total Test time (real) = 2172.93 sec

The following tests FAILED:
	  1 - opencv_test_core (Failed)
	  3 - opencv_sanity_core (Failed)
	  6 - opencv_test_imgproc (Failed)
	  7 - opencv_perf_imgproc (Failed)
	  8 - opencv_sanity_imgproc (Failed)
	  9 - opencv_test_ml (Failed)
	 11 - opencv_test_photo (Failed)
	 12 - opencv_perf_photo (Failed)
	 13 - opencv_sanity_photo (Failed)
	 14 - opencv_test_quality (Failed)
	 15 - opencv_test_reg (Failed)
	 18 - opencv_test_xphoto (Failed)
	 20 - opencv_sanity_xphoto (Failed)
	 21 - opencv_test_dnn (Failed)
	 22 - opencv_perf_dnn (Failed)
	 23 - opencv_sanity_dnn (Failed)
	 24 - opencv_test_features2d (Failed)
	 25 - opencv_perf_features2d (Failed)
	 26 - opencv_sanity_features2d (Failed)
	 27 - opencv_test_fuzzy (Failed)
	 32 - opencv_test_imgcodecs (Failed)
	 35 - opencv_test_line_descriptor (Failed)
	 40 - opencv_test_videoio (SEGFAULT)
	 41 - opencv_perf_videoio (Failed)
	 42 - opencv_sanity_videoio (Failed)
	 43 - opencv_test_calib3d (Failed)
	 44 - opencv_perf_calib3d (Failed)
	 45 - opencv_sanity_calib3d (Failed)
	 47 - opencv_test_dnn_superres (Failed)
	 48 - opencv_perf_dnn_superres (Failed)
	 49 - opencv_sanity_dnn_superres (Failed)
	 50 - opencv_test_highgui (SEGFAULT)
	 51 - opencv_test_objdetect (Failed)
	 52 - opencv_perf_objdetect (Failed)
	 53 - opencv_sanity_objdetect (Failed)
	 54 - opencv_test_rgbd (Failed)
	 55 - opencv_test_shape (Failed)
	 56 - opencv_test_structured_light (Failed)
	 57 - opencv_test_video (Failed)
	 58 - opencv_perf_video (Failed)
	 59 - opencv_sanity_video (Failed)
	 61 - opencv_test_xfeatures2d (Failed)
	 62 - opencv_perf_xfeatures2d (Failed)
	 63 - opencv_sanity_xfeatures2d (Failed)
	 64 - opencv_test_ximgproc (Failed)
	 65 - opencv_perf_ximgproc (Failed)
	 66 - opencv_sanity_ximgproc (Failed)
	 68 - opencv_test_bgsegm (Failed)
	 69 - opencv_test_bioinspired (Failed)
	 70 - opencv_perf_bioinspired (Failed)
	 71 - opencv_sanity_bioinspired (Failed)
	 72 - opencv_test_face (Failed)
	 73 - opencv_test_optflow (Failed)
	 74 - opencv_perf_optflow (Failed)
	 75 - opencv_sanity_optflow (Failed)
	 76 - opencv_test_sfm (Failed)
	 77 - opencv_test_stitching (Failed)
	 78 - opencv_perf_stitching (Failed)
	 79 - opencv_sanity_stitching (Failed)
	 82 - opencv_sanity_superres (Failed)
	 83 - opencv_test_tracking (Failed)
	 84 - opencv_perf_tracking (Failed)
	 85 - opencv_sanity_tracking (Failed)
	 86 - opencv_test_stereo (Failed)
	 88 - opencv_sanity_stereo (Failed)
Errors while running CTest
make: *** [Makefile:133: test] Error 8
make: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/opencv-4.1.2/x86_64-redhat-linux-gnu&apos;
error: Bad exit status from /var/tmp/rpm-tmp.HOrawc (%check)
</pre>

**Comment by catree** [comment]
You should run with the verbose option: `ctest -VV`.

Maybe you did not have downloaded the [test data](https://github.com/opencv/opencv_extra) and:

```
export OPENCV_TEST_DATA_PATH=<opencv_extra_dir>/testdata
```

Also, you can run directly the binaries.

**Comment by dkurt** [comment]
Let me close this issue unless it's filled according the template (includes OS, exact version and build configuration).
