### ISSUE TITLE
Results of opencv dnn looks weird when using the tensorflow model(faster rcnn) to detect the object

### ISSUE THREAD

**Issue by stereomatchingkiss** [opencv/opencv#16113]
I think this is a bug and I post the details on stackoverflow, please check it on [this page](https://stackoverflow.com/questions/59156838/results-of-opencv-dnn-looks-weird-when-using-the-tensorflow-modelfaster-rcnn-t).

**Comment by dkurt** [comment]
related https://github.com/opencv/opencv/issues/14634

**Comment by dkurt** [comment]
See https://stackoverflow.com/a/59541189/6548453
