### ISSUE TITLE
OpenCV incompatible with Anaconda

### ISSUE THREAD

**Issue by MGarvinNYC** [opencv/opencv#16111]
I've been trying to build OpenCV 4.1.2 under Linux, with compatibility/bindings for Anaconda Python 3.7.  I keep encountering problems arising from CMake's Generate process, where several libraries (including gstreamer) cannot be located.  This is presumably because Anaconda installs libraries that 'shadow' those that CMake is looking for.  The problems relating to the gstreamer libs also seem to be triggered by enabling the flag "WITH_QT", though I'm not sure of the connection.  Presumably this is a larger problem, related to shadowing of expected libraries in general.

I've noticed that several others have experienced similar problems.  This seems like there should be a work-around, given the prevalence of Anaconda in neural net programming.

Sample error messages:

CMake Warning at cmake/OpenCVUtils.cmake:1471 (add_executable): Cannot generate a safe runtime search path for target opencv_test_videoio because files in some directories may conflict with libraries in implicit directories:

runtime library [libgstbase-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  /opt/Anaconda/3.7/lib

runtime library [libgstreamer-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  /opt/Anaconda/3.7/lib

runtime library [libgobject-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
  /opt/Anaconda/3.7/lib

etc...

Though CMake-Gui Generate flags these as 'warnings', subsequent attempts to compile code via make fail with a message about failing to build cudawarping libs.  While this sounds like the major show-stopper, I'm sure that it must be caused by interactions that are evident in the 'generate' messages above.  When WITH_QT is switched off, CMake-Gui generates with no errors, and make compiles with no errors.

**Comment by alalek** [comment]
Perhaps you should use CMake from Anaconda too, which must be configured to avoid using of **any system** libraries.

**Comment by jinxinbao** [comment]
> Perhaps you should use CMake from Anaconda too, which must be configured to avoid using of **any system** libraries.

I have the same problem too, how can i use CMake from Anaconda ?
