### ISSUE TITLE
about function:  void cvInitIntrinsicParams2D

### ISSUE THREAD

**Issue by 15757170756** [opencv/opencv#16131]
the function CV_IMPL void cvInitIntrinsicParams2D( const CvMat* objectPoints,
                         const CvMat* imagePoints, const CvMat* npoints,
                         CvSize imageSize, CvMat* cameraMatrix,
                         double aspectRatio )
can get the intrinsic parameters of camera。 I find an annotation：
// extract vanishing points in order to obtain initial value for the focal length
and following source code：
       H[0] -= H[6]*a[2]; H[1] -= H[7]*a[2]; H[2] -= H[8]*a[2];
        H[3] -= H[6]*a[5]; H[4] -= H[7]*a[5]; H[5] -= H[8]*a[5];

        for( j = 0; j < 3; j++ )
        {
            double t0 = H[j*3], t1 = H[j*3+1];
            h[j] = t0; v[j] = t1;
            d1[j] = (t0 + t1)*0.5;
            d2[j] = (t0 - t1)*0.5;
            n[0] += t0*t0; n[1] += t1*t1;
            n[2] += d1[j]*d1[j]; n[3] += d2[j]*d2[j];
        }

        for( j = 0; j < 4; j++ )
            n[j] = 1./sqrt(n[j]);

        for( j = 0; j < 3; j++ )
        {
            h[j] *= n[0]; v[j] *= n[1];
            d1[j] *= n[2]; d2[j] *= n[3];
        }

        Ap[0] = h[0]*v[0]; Ap[1] = h[1]*v[1];
        Ap[2] = d1[0]*d2[0]; Ap[3] = d1[1]*d2[1];
        bp[0] = -h[2]*v[2]; bp[1] = -d1[2]*d2[2];
    }

    cvSolve( matA, _b, &_f, CV_NORMAL + CV_SVD );
    a[0] = sqrt(fabs(1./f[0]));
    a[4] = sqrt(fabs(1./f[1]));

I can't understand the code what it represent，and there is little information about “extract vanishing points in order to obtain initial value for the focal length” in the internet。Can anyone give a explanation？
thanks a lot！

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

---

> cvInitIntrinsicParams2D

It is part of legacy OpenCV 1.x C API. Deprecated >5 years ago, candidate for removal. So don't use this function.

**Comment by y8han** [comment]
I have the same question!

**Comment by ichangjian** [comment]
The formula (3) (4) in [zhang](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf) was used in this function. Vanishing points was not used in zhang's article.In camera intrinsic A, γ =0, u=imageSize.width/2,v=imageSize.height/2, so only α and β is not know which is _f in code to cvSolve. H[0] -= H[6]*a[2] and so on is in order to cancel u and v in A.
