### ISSUE TITLE
GSoC Future Work

### ISSUE THREAD

**Issue by heisenbuug** [opencv/opencv#16132]
OpenCV Zoo needs implementation of Semantic Segmentation as it was [discussed](https://github.com/dvd42/opencv/wiki#summary) in the future work of GSoC 2019 project. I want to work on adding new segmentation models. I found a list of suggested models [here](https://github.com/kjw0612/awesome-deep-vision#semantic-segmentation). Is there any specific model that I should consider working on? I also need some guidance regarding this work.

**Comment by heisenbuug** [comment]
@IRDonch @dkurt I haven't received any response here, also there is no specific project proposal for adding more segmentation models this year. So, I think we can close this issue?

**Comment by dkurt** [comment]
@heisenbuug, as  a part of GSoC program we expect some research from student. Adding a single segmentation model is not a good proposal for 3+ months of real coding.

Please take a look to more generic

https://github.com/opencv/opencv/wiki/GSoC_2020#idea-Write-a-tutorial-about-training-a-network-in-TF-or-PyTorch-and-then-running-it-in-OpenCV

and

https://github.com/opencv/opencv/wiki/GSoC_2020#idea-fully-support-onnx-for-dnn

**Comment by heisenbuug** [comment]
@dkurt , Hey I understand that implementing 1 model through out the summer is not at all resourceful, this was nearly 2 months ago I just wanted to do this before submitting my gsoc proposal to display my knowledge regarding the library. I already posted in the group for the project "Revise/improve Text & Digit Recognition Samples".

**Comment by alalek** [comment]
GSoC projects ideas are discussed here: https://github.com/opencv/opencv/issues/7263
