### ISSUE TITLE
What is the square size unit for calibration.py ? 

### ISSUE THREAD

**Issue by yolingen23** [opencv/opencv#16144]
Hi, I use /master/samples/python/calibrate.py to calibrate my photos. As Chess Board I use chessboard.png in your data. But the square in the code field is 1 square. What is Square size's unit? Your sample chessboard unuz looks 2.2cm. What should I write on code?

#!/usr/bin/env python

'''
camera calibration for distorted images with chess board samples
reads distorted images, calculates the calibration and write undistorted images
usage:
    calibrate.py [--debug <output path>] [--square_size] [<image mask>]
default values:
    --debug:    ./output/
    -**-square_size: 1.0**
    <image mask> defaults to ../data/left*.jpg

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

---

Camera intrinsics (fx,fy,cx,cy + distorsion) should not depend on that value.
So write anything > 0. `1.0` is good enough choice.

This parameter specifies board's "cell" size in "world" coordinates. See [code](https://github.com/opencv/opencv/blob/4.1.2/samples/python/calibrate.py#L50-L52).

**Comment by yolingen23** [comment]
I understand that I am not making any changes to the code either. But the action camera doesn't work when you make a wide angle image. @alalek

**Comment by alalek** [comment]
> wide angle image.

Used camera should fit into pinhole camera model (used by default in samples).

You may want to look on "fisheye" model.
