### ISSUE TITLE
cv::cvarrToMat link error and mat to Ipimage error!!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencv/opencv#16149]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

1、cv::cvarrToMat link error
code:
 cv::Mat m = cv::cvarrToMat(ipl, true);
error:
 error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::cvarrToMat(void const *,bool,bool,int,class cv::AutoBuffer<double,136> *)"

2: cv:mat to IpImage error
code:
    IplImage *ipl = new IplImage;
    *ipl = &IplImage(mat);
error:
error C2440: '<function-style-cast>': cannot convert from 'cv::Mat' to 'IplImage'

**Comment by xinsuinizhuan** [comment]
opencv 4.2.0
windows10 64
vs 2019
1、cv::cvarrToMat link error:
code:
cv::Mat m = cv::cvarrToMat(ipl, true);
error:
 error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::cvarrToMat(void const *,bool,bool,int,class cv::AutoBuffer<double,136> *)
2、 mat to imlmage error:
code:
 IplImage *ipl = new IplImage;
    *ipl = &IplImage(mat);
error:
error C2440: '<function-style-cast>': cannot convert from 'cv::Mat' to 'IplImage'

**Comment by alalek** [comment]
```
IplImage *ipl = new IplImage;
*ipl = &IplImage(mat);
```

This code looks wrong from C++ perspective. I believe you want to write something like this:
```
IplImage *ipl = new IplImage(mat);
```

Anyway this would not work.
`IplImage` is POD C type (from OpenCV 1.x) which can't have constructors (some versions of OpenCV 2.4 and 3.x has constructors for POD types - but it was wrong).

Consider to stop using of legacy C API - it is not tested/supported for years (deprecated since 2.4.0, >7 years).

---

>  unresolved external symbol "class cv::Mat __cdecl cv::cvarrToMat

Check opencv_core/opencv_world DLL files for this symbol: `?cvarrToMat@cv@@YA?AVMat@1@PEBX_N1HPEAV?$AutoBuffer@N$0II@@1@@Z`

[Can't reproduce](https://github.com/opencv/opencv/blob/c2b6c6743175241d895fe4e67028fd960a405b00/modules/core/test/test_math.cpp#L1333).

**Comment by xinsuinizhuan** [comment]
> 
> 
> ```
> IplImage *ipl = new IplImage;
> *ipl = &IplImage(mat);
> ```
> 
> This code looks wrong from C++ perspective. I believe you want to write something like this:
> 
> ```
> IplImage *ipl = new IplImage(mat);
> ```
> 
> Anyway this would not work.
> `IplImage` is POD C type (from OpenCV 1.x) which can't have constructors (some versions of OpenCV 2.4 and 3.x has constructors for POD types - but it was wrong).
> 
> Consider to stop using of legacy C API - it is not tested/supported for years (deprecated since 2.4.0, >7 years).
> 
> > unresolved external symbol "class cv::Mat __cdecl cv::cvarrToMat
> 
> Check opencv_core/opencv_world DLL files for this symbol: `?cvarrToMat@cv@@YA?AVMat@1@PEBX_N1HPEAV?$AutoBuffer@N$0II@@1@@Z`
> 
> [Can't reproduce](https://github.com/opencv/opencv/blob/c2b6c6743175241d895fe4e67028fd960a405b00/modules/core/test/test_math.cpp#L1333).

the new version of opencv(4.2.0),how to conver mat to iplImage，no matter how i do, it error:
error C2440: '': cannot convert from 'cv::Mat' to 'IplImage'

how to Check opencv_core/opencv_world，i cmake it, but it is makered:
![图片](https://user-images.githubusercontent.com/40679769/70772274-efa05a80-1dae-11ea-882b-b1f720a4cf52.png)

**Comment by bvnp43** [comment]
this code stopped working after moving from 4.1.2 to 4.2.0

```
cv::Mat _roi_patch;
IplImage z_ipl = _roi_patch;

....

 error: no viable conversion from 'cv::Mat' to 'IplImage' (aka '_IplImage')
            IplImage z_ipl = _roi_patch;

```
