### ISSUE TITLE
OpenCV 4.1.1 global loss of performance 

### ISSUE THREAD

**Issue by maximefp** [opencv/opencv#16158]
When upgrading OpenCV from 2.4.11 to 4.1.1, we have noticed a global loss of performance in our system. Execution time is decreased up to 25% in some parts of the code. (whereas the OpenCV tests perfs do not expose the same loss of performance).

Investigations seems to show that dynamic allocations (all of them, not only related to OpenCV objects!) become slower when linking to OpenCV 4.1.1.

We can reproduce with a basic program just performing non OpenCV operations (Mat allocation is out of the bench measurement, just here to ensure the link).
The code is the following:
```.cpp
#include "stdafx.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <ch_cvl\timer.h>
#include <opencv2/opencv.hpp>

int main()
{
       using namespace std;

       vector<int> g1;

       /*implementation of openCV matrix in order to link OpenCV lib*/
       cv::Mat m(10, 10, CV_8UC1, 1);
       cv::Mat m2 = m; //this is needed to ensure the compiler does not remove the OpenMP 'm' during the optimization phase

       /*Cognex accuratetimer*/
       double totalTimeInSeconds = 0.;                                           
       ccTimer oCognexTimer(true);
       
       /*computation loop*/
       for (int j = 0; j < 100000; j++)
       {
             for (int i = 1; i <= 1000000; i++)
                    g1.push_back(i); // ! dynamic allocation

             for (auto i = g1.begin(); i != g1.end(); ++i)
             {
                    *i++;
             }
             g1.clear();
       }

       oCognexTimer.stop(); // stop the timer
       totalTimeInSeconds = oCognexTimer.sec();

       ofstream ofs;                                                             
       ofs.open("result.txt", ofstream::out | ofstream::app);
       if (!ofs.fail())                                                                 
             ofs << totalTimeInSeconds << "(s)" << endl;
       cout << totalTimeInSeconds << "(s)" << endl;
       return 0;
}
```
We ran this test program:

1. **Without OpenCV**, removing the two “cv::Mat …” lines. (the OpenCV library is not linked). 
In this case, the time elapsed is the computation loop is approx. **23.1s** on my computer (Intel i7, 8GB ram)
2. With **OpenCV 2.4.1**
The time elapsed is the computation loop is approx. **23.5s**.
3. With **OpenCV 4.1.1**
The time elapsed is the computation loop is approx. **26.1s**.

Then, we ran the similar computation loop but without dynamic allocation. The code is now the following:
```.cpp
#include "stdafx.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <ch_cvl\timer.h>
#include <opencv2/opencv.hpp>

int main()
{
       using namespace std;

       vector<int> g1(1000000); //static allocation

       /*implementation of openCV matrix in order to link OpenCV lib*/
       cv::Mat m(10, 10, CV_8UC1, 1);
       cv::Mat m2 = m; //this is needed to ensure the compiler do not delete the OpenMP 'm' during the optimization phase

       /*Cognex precise timer*/
       double totalTimeInSeconds = 0.;
       ccTimer oCognexTimer(true);

       /*computation loop*/
       for (int j = 0; j < 100000; j++)
       {
             for (int i = 1; i <= 1000000; i++)
                    g1[i] = i;

             for (auto i = g1.begin(); i != g1.end(); ++i)
             {
                    *i++;
             }
             g1.clear();
       }

       oCognexTimer.stop(); // stop the timer
       totalTimeInSeconds = oCognexTimer.sec();

       ofstream ofs;
       ofs.open("result.txt", ofstream::out | ofstream::app);
       if (!ofs.fail())
             ofs << totalTimeInSeconds << "(s)" << endl;
       cout << totalTimeInSeconds << "(s)" << endl;
       return 0;
}
```
The delays measured are those:
1.	**Without OpenCV**, removing the two “cv::Mat …” lines; (the OpenCV library is not linked).
Approx. **13.9s** 
2.	With **OpenCV 4.1.1**
The time elapsed is the computation loop is approx. **13.9s**.

This behaviour is quite weird and we guess we are missing something important, maybe in the way of compiling OpenCV 4.
Could it be that OpenCV 4.1.1 overloads the system dynamic allocation or performs something which can explain the observed slow down?

##### System information (version)
The OpenCV 2.4.11 and 4.1.1 is built Visual C++ 2015 (MSVC++ 14.0). 
The cmake configuration command for 4.1.1 was: 
```
cmake.exe ../ -G "Visual Studio 14 2015 Win64" \
-DCMAKE_C_FLAGS_DEBUG="/O2 /MDd" -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_FLAGS_DEBUG="/O2 /MDd" -DCMAKE_CXX_FLAGS_RELEASE="/O2 /MD" \
-DCMAKE_C_FLAGS_RELEASE="/O2 /MD" -DWITH_IPP=ON -DWITH_CUDA=ON -DWITH_CUBLAS=ON \
-DWITH_CUFFT=ON -DCUDA_FAST_MATH=ON -DCUDA_ARCH_BIN="3.0 3.5 5.2 6.1 7.5" \
-DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-%OPENCV_VERSION%/modules \
-DBUILD_LIST=calib3d,core,cudev,cudaarithm,cudafilters,cudaimgproc,cudalegacy, \
cudawarping,feature2d,imgcodecs,imgproc,objdetect,photo,shape, \
stitching,superres,text,video,ximgproc \
-DWITH_EIGEN=ON -DWITH_OPENMP=OFF -DWITH_OPENCL=OFF -DWITH_QUIRC=OFF \
-DBUILD_PROTOBUF=OFF -DPYTHON_EXECUTABLE=OFF -DCMAKE_INSTALL_PREFIX=%DEST_DIR% \
-DBUILD_EXAMPLES=OFF -DBUILD_APPS=OFF -DBUILD_TESTS=OFF -DCPU_BASELINE=SSE4_2 \
-DCPU_DISPATCH=AVX,AVX2
```
The test program is built Visual C++ 2015 (MSVC++ 14.0).

**Comment by alalek** [comment]
OpenCV should not intercept C++ allocator.

We allocate memory through `memalign()` in OpenCV 3.4+. OpenCV 2.4 should use `malloc()`.
You can try `OPENCV_ENABLE_MEMALIGN=0` environment variable (OpenCV 4.1.2+)

You may continue investigation by disabling of these flags:
- `-DWITH_CUDA=OFF`
- `-DWITH_IPP=OFF`
- `-DWITH_EIGEN=OFF` (do you have it on Windows?)

**Comment by mshabunin** [comment]
Can not reproduce the issue on Ubuntu 18 with GCC 7.4, branch _master_.

My file:
```.cpp
#include <vector>
#include <iostream>
#include <chrono>
#ifdef USE_OPENCV
#   include <opencv2/opencv.hpp>
#endif

int main()
{
    using namespace std;
    vector<int> g1;
#ifdef USE_OPENCV
    cout << "With OpenCV..." << endl;
    cv::Mat m(10, 10, CV_8UC1, 1);
    cv::Mat m2 = m;
#endif
    std::chrono::time_point<std::chrono::system_clock> start, end;
    start = std::chrono::system_clock::now();
    for (int j = 0; j < 10000; j++)
    {
        for (int i = 1; i <= 1000000; i++)
            g1.push_back(i);
        for (auto i = g1.begin(); i != g1.end(); ++i)
            *i++;
        g1.clear();
    }
    end = std::chrono::system_clock::now();
    std::chrono::duration<double> elapsed_seconds = end-start;
    std::cout << "elapsed time: " << elapsed_seconds.count() << "s\n";
    return 0;
}
```

Console log:
```.sh
$ g++ --std=c++11 -O2 scripts/test.cpp 
$ ./a.out 
elapsed time: 11.6985s

$ g++ --std=c++11 -O2 scripts/test.cpp -Ibuild/install/include/opencv4 -Lbuild/install/lib -lopencv_core -DUSE_OPENCV
$ ./a.out 
With OpenCV...
elapsed time: 11.7062s
```

**Comment by maximefp** [comment]
> 
> 
> OpenCV should not intercept C++ allocator.
> 
> We allocate memory through `memalign()` in OpenCV 3.4+. OpenCV 2.4 should use `malloc()`.
> You can try `OPENCV_ENABLE_MEMALIGN=0` environment variable (OpenCV 4.1.2+)
> 
> You may continue investigation by disabling of these flags:
> 
>     * `-DWITH_CUDA=OFF`
> 
>     * `-DWITH_IPP=OFF`
> 
>     * `-DWITH_EIGEN=OFF` (do you have it on Windows?)

Thank you for this answer, unfortunately the OPENCV_ENABLE_MEMALIGN=0 variable does not solve our issue, nor with the OpenCV 4.1.2, nor with the git commit “ba7b0f4” of the project.
We tried different releases of OpenCV and our issue comes up with the 4.0.0-alpha release.
With **OpenCV 3.4.8**, when OpenCV matrix are allocated, the time elapsed is the computation loop is approx. **23.5s** against ### 26.0s with the versions **4.0.0-alpha** of OpenCV.

N.B: All tests were performed by disabling of these flags:
•	 -DWITH_CUDA=OFF
•	-DWITH_IPP=OFF
•	-DWITH_EIGEN=OFF

**Comment by pwnorbitals** [comment]
Does this still reproduce with the latest versions ? @maximefp
