### ISSUE TITLE
cap.isOpened return false before videoCapture resource is finished to release

### ISSUE THREAD

**Issue by flybirdinsky** [opencv/opencv#16154]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 16.04 64bit
- Compiler => gcc 5.4.0

##### Detail description
In opencv4 if cap.isOpened return false, the action to release videoCapture resource does not finish in deed. This action implements correctly for opencv3.4. 
Looking into the code, the difference is caused by implementation of shared_ptr class. In opencv3.4, shared_ptr is implemented by opencv self in ptr.inl.hpp. In this implementation, it will deleteSelf() at first, and then set cap to null. In opencv4.1, shared_ptr use gcc c++11 data type. It will call reset() to set cap ptr to null, but the resource will be released by deconstructor. 

##### Steps to reproduce

```.cpp
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/videoio/videoio_c.h>
#include <unistd.h>
#include <string>
#include <iostream>
#include <thread>
#include <chrono>
     
using namespace cv;
using namespace std;

VideoCapture cap;
int g_exit_flag;
string g_filename;

void t1()
{
    cap.open(g_filename);
    if (!cap.isOpened()){
        cout << "Failed to open cap!" << endl;
        return; 
    }

    g_exit_flag = 0;
    while (!g_exit_flag) {
        Mat frame;
        cap.read(frame);
        cout << "frame!\n";

        std::this_thread::sleep_for(std::chrono::seconds(1));
    }

    if (cap.isOpened()){
        cout << " start to release " << clock() << endl;
        cap.release();
        cout << "  release done " << clock() << endl;
    }
}

int main(int argc, char *argv[])
{
    g_filename = argv[1];

    std::thread helper1(t1);

    cout << "start thread t1\n";
    sleep(10);

    g_exit_flag = 1;
    cout << "wait for cap close!\n";
    while(cap.isOpened())
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    cout << " cap is closed! " << clock() << endl;

    helper1.join();

    std::cout << "done!\n";

    return 0;
}
```

Outputs:
```cpp
start thread t1
frame!
frame!
frame!
frame!
frame!
frame!
frame!
frame!
frame!
wait for cap close!
 start to release 358020
 cap is closed! 358443
  release done 361476
done!
```
More precise watch-point can be inserted into opencv videoio module.

**Comment by flybirdinsky** [comment]
Attach my patcheds for this problem. Add a release funciton in cap_interface.hpp to release resource
'''cpp
diff --git a/opencv/modules/videoio/src/cap.cpp b/opencv/modules/videoio/src/cap.cpp
old mode 100644
new mode 100755
index 0aab7987..76a40abf
--- a/opencv/modules/videoio/src/cap.cpp
+++ b/opencv/modules/videoio/src/cap.cpp
@@ -73,7 +73,7 @@ VideoCapture::VideoCapture(int index, int apiPreference)
 VideoCapture::~VideoCapture()
 {
     CV_TRACE_FUNCTION();
-    icap.release();
+    release();
 }
 
 bool VideoCapture::open(const String& filename, int apiPreference)
@@ -210,7 +210,9 @@ String VideoCapture::getBackendName() const
 void VideoCapture::release()
 {
     CV_TRACE_FUNCTION();
-    icap.release();
+    if (isOpened() && (icap.use_count() == 1))
+        icap->release(); // IVideoCapture release resouce. Here thread competetion risk exists for this patch. But capture is seldom shared with other thread, so this is acceptable. 
+    icap.release(); // shared_ptr release pointer
 }
 
 bool VideoCapture::grab()
diff --git a/opencv/modules/videoio/src/cap_ffmpeg.cpp b/opencv/modules/videoio/src/cap_ffmpeg.cpp
old mode 100644
new mode 100755
index 17c44c6a..e9eb2fd3
--- a/opencv/modules/videoio/src/cap_ffmpeg.cpp
+++ b/opencv/modules/videoio/src/cap_ffmpeg.cpp
@@ -258,8 +258,10 @@ public:
 )
             icvReleaseCapture_FFMPEG_p( &ffmpegCapture );
         CV_Assert(ffmpegCapture == 0);
+
         ffmpegCapture = 0;
     }
+    virtual void release() { close(); }
 
     virtual bool isOpened() const CV_OVERRIDE { return ffmpegCapture != 0; }
     virtual int getCaptureDomain() CV_OVERRIDE { return CV_CAP_FFMPEG; }
diff --git a/opencv/modules/videoio/src/cap_interface.hpp b/opencv/modules/videoio/src/cap_interface.hpp
old mode 100644
new mode 100755
index 1eb9f873..a6abf51d
--- a/opencv/modules/videoio/src/cap_interface.hpp
+++ b/opencv/modules/videoio/src/cap_interface.hpp
@@ -49,6 +49,7 @@ public:
     virtual bool SetResampler(int, int) { return 0; }
     virtual bool GetResampler(int *, int *) { return 0; }
     virtual bool isOpened() const = 0;
+    virtual void release() {}
     virtual int getCaptureDomain() { return CAP_ANY; } // Return the type of the capture object: CAP_DSHOW, etc...
 };
 '''

**Comment by flybirdinsky** [comment]
Attach my patches for this issue here. Hope it useful. This patch add an release function in cap_interface.hpp, and it may have thread competetion potential risk when release and assign the same VideoCapture instance in different thread at the same time. 
```
  diff --git a/opencv/modules/videoio/src/cap.cpp b/opencv/modules/videoio/src/cap.cpp
  old mode 100644
  new mode 100755
  index 0aab7987..76a40abf
  --- a/opencv/modules/videoio/src/cap.cpp
  +++ b/opencv/modules/videoio/src/cap.cpp
  @@ -73,7 +73,7 @@ VideoCapture::VideoCapture(int index, int apiPreference)
   VideoCapture::~VideoCapture()
   {
       CV_TRACE_FUNCTION();
   -    icap.release();
   +    release();
    }
 
   bool VideoCapture::open(const String& filename, int apiPreference)
   @@ -210,7 +210,9 @@ String VideoCapture::getBackendName() const
    void VideoCapture::release()
    {
        CV_TRACE_FUNCTION();
     -    icap.release();
    +    if (isOpened() && (icap.use_count() == 1))
    +        icap->release(); // IVideoCapture release resouce. Here thread competetion risk exists for 
    this patch. But capture is seldom shared with other thread, so this is acceptable. 
    +    icap.release(); // shared_ptr release pointer
     }
 
    bool VideoCapture::grab()
    diff --git a/opencv/modules/videoio/src/cap_ffmpeg.cpp 
     b/opencv/modules/videoio/src/cap_ffmpeg.cpp
     old mode 100644
     new mode 100755
     index 17c44c6a..e9eb2fd3
     --- a/opencv/modules/videoio/src/cap_ffmpeg.cpp
    +++ b/opencv/modules/videoio/src/cap_ffmpeg.cpp 
        @@ -258,8 +258,10 @@ public:
     )
                  icvReleaseCapture_FFMPEG_p( &ffmpegCapture );
              CV_Assert(ffmpegCapture == 0);
              ffmpegCapture = 0;
          }
     +    virtual void release() { close(); }
 
          virtual bool isOpened() const CV_OVERRIDE { return ffmpegCapture != 0; }
          virtual int getCaptureDomain() CV_OVERRIDE { return CV_CAP_FFMPEG; }
       diff --git a/opencv/modules/videoio/src/cap_interface.hpp  
            b/opencv/modules/videoio/src/cap_interface.hpp
       old mode 100644
       new mode 100755
       index 1eb9f873..a6abf51d
         --- a/opencv/modules/videoio/src/cap_interface.hpp
        +++ b/opencv/modules/videoio/src/cap_interface.hpp
        @@ -49,6 +49,7 @@ public:
           virtual bool SetResampler(int, int) { return 0; }
           virtual bool GetResampler(int *, int *) { return 0; }
           virtual bool isOpened() const = 0;
     +    virtual void release() {}
            virtual int getCaptureDomain() { return CAP_ANY; } // Return the type of the capture object: 
                 CAP_DSHOW, etc...
        };
```

**Comment by alalek** [comment]
You can't share OpenCV one object between threads in general.
Exception is storage containers (`cv::Mat`, `cv::UMat`).

Documentation says:

> the same methods of **different** class instances can be called from different threads

https://docs.opencv.org/3.4/d1/dfb/intro.html

**Comment by flybirdinsky** [comment]
Understand your exaplanation. Yes, based on the document, only same method of difference instance can be called in different thread. But it is better to keep consequence between release operatoin and isOpened state. In opencv 3.x series, program can use isOpened method to know the completeness of Mat release operation. That is quite usefull when we register signal handler to process exception such as segment fault and etc. Now a signal have to be set everywhere to notify this in Opencv 4.x.
