### ISSUE TITLE
CUDA: minmax causes shared memory leak with multiple GPU and driver version 441.22

### ISSUE THREAD

**Issue by fbabian** [opencv/opencv#16175]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Gpu Model-> RTX 2080 - 2 and 3 Devices tested

##### Detailed description

Running minmax on multiple gpus will cause GPU shared memory allocation to increase until out of memory error occurs. 
The problem occurs on driver version 441.22, but not on driver version 431.60. 
A number of other methods were tested and only minmax produces a shared memory leak.

##### Steps to reproduce

    ```.cpp
    
#include <iostream>
#include "opencv2/imgproc.hpp"
#include "opencv2/cudafilters.hpp"
#include "opencv2/cudaimgproc.hpp"
#include "opencv2/cudaarithm.hpp"

using namespace std;
using namespace cv;

int main()
{
  double min = 0;
  double max = 0;
  int numDevices = cuda::getCudaEnabledDeviceCount();
  cuda::GpuMat * img = new cuda::GpuMat[numDevices];

  for (int i = 0; i < numDevices; i++)
  {
    cuda::setDevice(i);
    img[i] = cuda::GpuMat(500, 500, CV_32F);
    cuda::printShortCudaDeviceInfo(i);
  }

  for (int i = 0; ; i++)
  {
    cuda::setDevice(i % numDevices);
    cuda::minMax(img[i%numDevices], &min, &max);
  }
}

    ```

**Comment by alalek** [comment]
> The problem occurs on driver version 441.22, but not on driver version 431.60.

Not sure that this can be fixed by OpenCV. Did you contact with NVIDIA? (https://devtalk.nvidia.com/)

**Comment by fbabian** [comment]
Good suggestion, I will do that. Thanks

**Comment by fbabian** [comment]
NVIDIA was able to duplicate the problem on driver version 441.22. The problem has been fixed on their development branch which will get distributed in the near future.
