### ISSUE TITLE
CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib' error still exists

### ISSUE THREAD

**Issue by PascalYIN** [opencv/opencv#16173]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Ubuntu18.04 64 Bit
- Compiler => Unix Makefiles for GCC/G++ 7.4.0

##### Detailed description

Hello, I'm trying to build OpenCV 4.1.2 on Unbuntu 18.04 with CUDA10.1/10.2, an error occurred during the configuration : 

CMake Error at modules/core/CMakeLists.txt:40 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib

I have tried this with cmake 3.10 (the version that on can install with the apt-get install command line) as well as cmake 3.16.0, and I got the same error. 

Though I found a familiar issue [#14025](https://github.com/opencv/opencv/issues/14205#issue-427434567) that has been closed 8 months ago, I didn't understand what to do exactly, I didn't even understand whether that's an operation to be accomplished by my side. I commented on the bottom of [#14206](https://github.com/opencv/opencv/pull/14206#issue-266040527), however two weeks passed and I got no response. 

Could someone please make an explanation which is a little bit more detailed about what one should do to resolve this problem ?

Being grateful while waiting for your response.

**Comment by alalek** [comment]
Please read information from the provided link: https://github.com/opencv/opencv_contrib

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by PascalYIN** [comment]
for those who come for the same error you can refer to [this](https://github.com/opencv/opencv/pull/14206#issuecomment-570029627)

**Comment by fsan** [comment]
@PascalYIN answer solved my problem.
I would add [this](https://jamesbowley.co.uk/accelerate-opencv-4-2-0-build-with-cuda-and-python-bindings/) reference also helped me in other related problems

**Comment by charlielito** [comment]
What if you want opencv with cuda but you dont want contrib? it is not possible to have that set up?

**Comment by Joeng22** [comment]
Compile opencv with opencv_contrib
Steps:
git clone https://github.com/opencv/opencv_contrib/
cd opencv_contrib/
git checkout origin/4.x   
(version should match with opencv version)
cmake -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules/
(opencv_contrib path)
make
make install

**Comment by mheriyanto** [comment]
> @alalek What if you want opencv with cuda but you dont want contrib? it is not possible to have that set up?

Hi @charlielito, what are there updates for your question?

**Comment by cudawarped** [comment]
> > @alalek What if you want opencv with cuda but you dont want contrib? it is not possible to have that set up?
> 
> Hi @charlielito, what are there updates for your question?

I am not sure I understand your question, the source code for the CUDA modules is contained within the contrib repo, without the contrib module there is no opencv with cuda.

@alalek can this issue be closed?

**Comment by charlielito** [comment]
> 

That pretty much answers my question. Thanks
