### ISSUE TITLE
opencv-4.1.2-vc14_vc15.exe + Windows 2012 => java: Can't find dependent libraries / MFPlat.DLL is missing

### ISSUE THREAD

**Issue by deltatree** [opencv/opencv#16178]
Hi,

I have to run opencv under Windows 2012 but I'm getting following errors:

With java using opencv_java412.dll -> Can't find dependent libraries
With running the binary opencv_version_win32.exe -> MFPlat.DLL is missing

How I can fix this?

I'm using the precompiled version for windows - from here: https://opencv.org/releases/ (https://sourceforge.net/projects/opencvlibrary/files/4.1.2/opencv-4.1.2-vc14_vc15.exe/download)

**Comment by alalek** [comment]
> Windows 2012

It is server version of Windows 8. We provide binaries build on up-to-date Windows 10 machines, so some incompatibilities may occur.
Reliable way is to rebuild OpenCV from sources on your target platform (or compatible configuration).

> MFPlat.DLL

You may try something from here (if it is applicable):
- https://social.technet.microsoft.com/Forums/en-US/f7cac36d-cf58-40e8-8509-d36c10ee2a8c/dll-files-missing-inwindow-server-2012-r2?forum=winserver8gen
- https://github.com/opencv/opencv/issues/12010#issuecomment-420640169

**Comment by deltatree** [comment]
I will rebuild OpenCV from sources - thank you for the quick answer.
