### ISSUE TITLE
how can i put source image to destination image with source picture's original color using seamlessClone function

### ISSUE THREAD

**Issue by HackerJLY** [opencv/opencv#16180]
hello, 
i want to put source image to destination image using seamlessClone function, but the color of source image changed.
i need the source image have the original color.
how can i do it?
how can i modify the seamlessClone function?
thanks!
------------------------------------------------------------------------------------
sky with plane
![sky-with-plane](https://user-images.githubusercontent.com/3407061/70971621-5d64c300-20dc-11ea-8418-058987325ae0.jpg)
------------------------------------------------------------------------------------
seamlessclone function example
![seamless-cloning-example](https://user-images.githubusercontent.com/3407061/70971641-66ee2b00-20dc-11ea-89ad-75761da0b146.jpg)
------------------------------------------------------------------------------------
photoshop example, i need this 
![sky-with-plane-masked](https://user-images.githubusercontent.com/3407061/70971656-6d7ca280-20dc-11ea-9d6a-3202c4c6febc.jpg)

**Comment by dkurt** [comment]
I believe that mask parameter is what you are looking for: https://docs.opencv.org/master/df/da0/group__photo__clone.html#ga2bf426e4c93a6b1f21705513dfeca49d

Let's close this issue. Usage questions should go to forum and at least there should be origin images so other users who can help you can reproduce the experiment.
