### ISSUE TITLE
OpenCV 4.1.2 OpenCL SVM Build Error

### ISSUE THREAD

**Issue by oras** [opencv/opencv#16181]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Android 64 Bit
- Compiler => C++ Compiler:                C:/android-ndk-r17c-windows-x86_64/android-ndk-r17c/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe  (ver 3.8)

Hi,

 trying to build Opencv 4.1.2 include OpenCL SVM for:
Qualcomm's MSM8996 GPU (Qualcomm Adreno 530)

https://www.khronos.org/conformance/adopters/conformant-products/opencl#submission_273

I have the vendor libOpenCL.so include headers from Khronos site,  at the end of the build
I get the following error:

[ 99%] Built target gen_opencv_java_source
Scanning dependencies of target opencv_java
[ 99%] Building CXX object modules/java/jni/CMakeFiles/opencv_java.dir/__/generator/src/cpp/opencv_java.cpp.o
[100%] Linking CXX shared library ..\..\..\jni\armeabi-v7a\libopencv_java4.so
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSVMAlloc_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMMap_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMUnmap_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSVMFree_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSVMFree_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSVMAlloc_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSVMFree_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clSetKernelArgSVMPointer_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMMemcpy_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMMemFill_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMMap_pfn'
C:\opencv-4.1.2\modules\core\src/ocl.cpp:0: error: undefined reference to 'clEnqueueSVMUnmap_pfn'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
mingw32-make[2]: *** [modules\java\jni\CMakeFiles\opencv_java.dir\build.make:261: jni/armeabi-v7a/libopencv_java4.so] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:5230: modules/java/jni/CMakeFiles/opencv_java.dir/all] Error 2
mingw32-make: *** [Makefile:162: all] Error 2

Thanks

<details>

![build_error](https://user-images.githubusercontent.com/1174496/70973749-ec5ae680-20ae-11ea-9888-7528669f8638.png)

</details>

**Comment by mshabunin** [comment]
Please add more information about your configuration: cmake arguments, cmake output.

**Comment by alalek** [comment]
SVM is in experimental status (and on hold for the last 5+ years).

Its enabling doesn't provide performance benefits over regular `clEnqueueMapBuffer()` calls (by results from 2014) - so SVM feature is kept disabled by default.

**Comment by oras** [comment]
Hi thanks for fast replay,

I need it for stress work loads on my Adreno530 GPU. 

I understand that no benefits like SURF algorithm  can I get ?

**Comment by alalek** [comment]
> I understand that no benefits like SURF algorithm can I get ?

It depends on target platform and implementation of OpenCL runtime.

---

Do you need Java API of OpenCV? If no, then try to disable that: `-DBUILD_opencv_java=OFF` or `-DBUILD_JAVA=OFF`

---

Can't reproduce problem on **master** by adding `-DWITH_OPENCL_SVM=ON` into regular Android builds (NDK 19).

**Comment by oras** [comment]
I am using the Android platform, i think that I need it

**Comment by oras** [comment]
As Qualcomm says Adreno530 support SVM with OpenCL 2.0

**Comment by oras** [comment]
I will try with NDK 19 & update
