### ISSUE TITLE
imshow() High DPI toolbar option

### ISSUE THREAD

**Issue by JJW152** [opencv/opencv#16198]
- OpenCV => 4.1.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Python 3.7.5, Anaconda Dist.

An admittedly minor issue, but I figured I would report it and see if there was any feedback. I've been working on a Surface Pro 6 with a high DPI screen. When I display an image with imshow, there is no high DPI adjustment for the toolbar in the window. Regardless of the size of the image, the menu of options and the pointer information in the bottom left are extremely small and basically unusable. I just think that toolbar is a nice addition in 4.1.2 and would like to be able to use it on the small screen.

![image](https://user-images.githubusercontent.com/49687308/71143748-a8203100-21e9-11ea-9bbe-d63f898c8dcd.png)

**Comment by tompollok** [comment]
qt::AA_EnableHighDpiScaling


Enables high-DPI scaling in Qt on supported platforms (see also High DPI Displays). Supported platforms are X11, Windows and Android. Enabling makes Qt scale the main (device independent) coordinate system according to display scale factors provided by the operating system. This corresponds to setting the QT_AUTO_SCREEN​_SCALE_FACTOR environment variable to 1. This attribute must be set before QGuiApplication is constructed. This value was added in Qt 5.6.

**Comment by JJW152** [comment]
> I think this is part of the qt gui interface in opencv.
> 
> Use qt::AA_EnableHighDpiScaling
> 
> Enables high-DPI scaling in Qt on supported platforms (see also High DPI Displays). Supported platforms are X11, Windows and Android. Enabling makes Qt scale the main (device independent) coordinate system according to display scale factors provided by the operating system. This corresponds to setting the QT_AUTO_SCREEN​_SCALE_FACTOR environment variable to 1. This attribute must be set before QGuiApplication is constructed. This value was added in Qt 5.6.

Yeah, I discovered this last night. Works like a charm.

Thanks!

Closing this issue.

**Comment by JJW152** [comment]
Issue can be solved via PyQT a parameter change.
