### ISSUE TITLE
Wrong image pyramid generated by ORB feature, if FirstLevel > 0, and crash if FirstLevel >= 3

### ISSUE THREAD

**Issue by lincccc** [opencv/opencv#16197]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

ORB feature generate wrong image pyramid if set firstLevel > 0. For example firstLevel = 2, create imagePyramid as following image 72 *72. The upscaled image overlaps others.

![aaaa](https://user-images.githubusercontent.com/1185380/71140225-91122b00-224b-11ea-9d08-6dd4c331eb11.png)

If firstLevel >= 3, it crashes around line 1051 `Mat extImg = imagePyramid(wholeLinfo), extMask;`

It seems there is still some issue in code that calculates image pyramid's height.

##### Steps to reproduce

	Mat img = imread("119_10_1_15_31_7086.png");
	Ptr<ORB> orbPtr = ORB::create();
	orbPtr->setNLevels(5);
	orbPtr->setFirstLevel(2);
	// orbPtr->setFirstLevel(3); exception
	orbPtr->setScaleFactor(1.8);
	orbPtr->setPatchSize(8);
	orbPtr->setEdgeThreshold(8);
	std::vector<KeyPoint> kps;
	Mat fv;
	orbPtr->detectAndCompute(img, noArray(), kps, fv);
![119_10_1_15_31_7086](https://user-images.githubusercontent.com/1185380/74296295-570e6280-4d7e-11ea-8e48-8d1ffa3566c1.png)

**Comment by asmorkalov** [comment]
@lincccc could you share reproducer code and image that you use?

**Comment by lincccc** [comment]
@asmorkalov I've updated with code and image.
