### ISSUE TITLE
dnn: human keypoint onnx model seems broken

### ISSUE THREAD

**Issue by berak** [opencv/opencv#16204]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Windows 64 Bit / ubuntu18
- Compiler => mingw64 8.3 / python

the [lightweight-human-pose model in opencv_extra](https://github.com/opencv/opencv_extra/blob/4fdb88f83fe39f969e9945f531045a5a0f51b827/testdata/dnn/download_models.py#L783-L787)  looks broken, the last (output) layer:

![Clipboard01](https://user-images.githubusercontent.com/854416/70997603-c4cb4480-20d5-11ea-9a8a-7b987387fe3c.jpg)

looks like it only contains the 38 paf maps , but not the required heatmaps. (so the KeypointModel code goes haywire, and the results are all bogus)

there should be 19 heatmaps, and optionally 38 paf maps, like below:

![Clipboard02](https://user-images.githubusercontent.com/854416/71083950-7335bf00-2194-11ea-86c1-5967f690a58e.jpg)

the [newly added opencv Keypoints model](https://github.com/opencv/opencv/pull/15189/files#diff-6de938636906f03a3c475c556f5c8878R166) tries to loop over all 38 of them, and results look quite bad ;( also those 14 (!) of 38 that made it over the threshold were  wrongly saved to the test expectation npy.

there is also an issue here:
https://github.com/opencv/opencv/pull/15189/files#diff-6de938636906f03a3c475c556f5c8878R180
keypoints with low confidence must not be skipped, else we change the expected order.

so, imho, we should

* upload a new,corrected model, [based on daniil osokins script](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/convert_to_onnx.py#L13)  (this also produced the correct output above)
* correct the dnn model code: use `net.forward("stage_1_output_1_heatmaps")` and don't skip low prb kps
* record new test keypoints and upload to extra
* update the test code, 

see also: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/58

[noisy colab](https://colab.research.google.com/drive/186N1ZF5UrCCD2lKMWjQYAAK 35DV9Geje)

ps: imho it's not a problem with the dnn importer, the heatmaps are simply not in the current onnx file (same dot graph from onnx.tools)

**Comment by dkurt** [comment]
Can you please provide some details?

**Comment by berak** [comment]
still editing, heh ;)
