### ISSUE TITLE
Broken BGR color conversion utilities in opencv/modules/imgcodecs/src/utils.cpp.

### ISSUE THREAD

**Issue by JanuszL** [opencv/opencv#16215]
https://github.com/opencv/opencv/commit/058367f34c60d6a843579adce84895f4bc5d31dd#diff-c868f69925dd124c54190546d4843841 break BGR color conversion utilities in opencv/modules/imgcodecs/src/utils.cpp.
Before this commit when swap channels is set to 0 we have a following formula:
rgba[0]*cB + rgba[1]*cG + rgba[2]*cR

As `rgba`, in this case, is really BGRA data it works fine.

After this change:
rgba[0]*cRGB0 + rgba[1]*cG + rgba[2]*cRGB2
where
cRGB0 = cR
cRGB0 = cB

It is used by ../modules/imgcodecs/src/grfmt_tiff.cpp which reads RBG data, but uses icvCvt_BGRA2Gray_8u_C4C1R for conversion but with channel swapped.

relates #14760

**Comment by mshabunin** [comment]
Could you please propose pull request with the fix?

**Comment by JanuszL** [comment]
@mshabunin - please check https://github.com/opencv/opencv/pull/16265.
