### ISSUE TITLE
docs examples mistake, tutorial_charuco_detection.

### ISSUE THREAD

**Issue by barakooda** [opencv/opencv#16224]
https://docs.opencv.org/4.1.1/df/d4a/tutorial_charuco_detection.html

instead: 
`cv::aruco::detectMarkers(inputImage, board.dictionary, markerCorners, markerIds, params);`

probably should be :
`cv::aruco::detectMarkers(inputImage, board->dictionary, markerCorners, markerIds, params);`

instead :
`cv::Ptr<cv::aruco::DetectorParameters> params;`

probably should be :
`Ptr<aruco::DetectorParameters> params = aruco::DetectorParameters::create();`

**Comment by radupasparuga** [comment]
Anyone actively working on this?

**Comment by asmorkalov** [comment]
The best solution for the tutorial is not to fix code snippets inside of  text, but add Doxygen references to existing sample that is build during CI cycle. As example you can use OpenCV core basic tutorial for `cv::FileStorage`. It's code is in https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/core/file_input_output/file_input_output.cpp and tutorial text is https://raw.githubusercontent.com/opencv/opencv/master/doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.markdown. CI bot helps to find code build errors and indicates, if module API is changed, but documentation is not.

**Comment by jshiwam** [comment]
> The best solution for the tutorial is not to fix code snippets inside of text, but add Doxygen references to existing sample that is build during CI cycle. As example you can use OpenCV core basic tutorial for `cv::FileStorage`. It's code is in https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/core/file_input_output/file_input_output.cpp and tutorial text is https://raw.githubusercontent.com/opencv/opencv/master/doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.markdown. CI bot helps to find code build errors and indicates, if module API is changed, but documentation is not.

You mean that if I am supposed to make changes in the FileStorage documentation I have to change the code in corresponding file_input_output.cpp file so that next time the build is done the file_input_output_with_xml_yml.markdown file will refer to the changed code in the .cpp file and update the documentation itself?

**Comment by asmorkalov** [comment]
yes

**Comment by jshiwam** [comment]
> yes

The .markdown file here contains of @code tags where code samples are given as you have said to add references, for that I have to create a new cpp file which has these code snippets and then I have to add references of that cpp file into the markdown file. Should I create a new cpp file for that?

**Comment by asmorkalov** [comment]
yes, please create new C++ file and move code there.

**Comment by jshiwam** [comment]
> yes, please create new C++ file and move code there.

I have made a pull request to opencv_contrib. For this issue.
