### ISSUE TITLE
Problems with out of focus cpp tutorial

### ISSUE THREAD

**Issue by themronion** [opencv/opencv#16227]
##### System information (version)
- OpenCV => from 3.3.0 to 4.2.0
- Operating System / Platform => Windows 10
- Compiler => MSVC

##### Detailed description
I tried to use this code located over here: [Out of focus cpp tutorial](https://github.com/opencv/opencv/tree/master/samples/cpp/tutorial_code/ImgProc/out_of_focus_deblur_filter)

And i encountered a problem: while using the same parameters, as specified by the author, the same image and definitely the same code i am getting an absolutely different result from his result.  To be more specific instead of a nice deblurred image i am getting the one i will paste down here. What is the problem? Again the parameters are exactly the same.
P.S. I tried all versions of OpenCV starting from 3.3.0.

![image](https://user-images.githubusercontent.com/52563426/71381427-3296d500-25dc-11ea-8a57-99d2c5cfa7b7.png)

##### Steps to reproduce
I think i need the author to take a look at this problem @VladKarpushin what can u say?

**Comment by VladKarpushin** [comment]
Dear
 @themronion. Because you should use the original full-size image. Attached

![DSC_0148_edgetape_old](https://user-images.githubusercontent.com/40189112/71386550-3dc02400-2621-11ea-8a51-462006326348.JPG)

**Comment by dkurt** [comment]
Check https://github.com/opencv/opencv/pull/12046 for details.

**Comment by themronion** [comment]
Oh, i see, thx
