### ISSUE TITLE
load onnx model error

### ISSUE THREAD

**Issue by VictoryDong** [opencv/opencv#16235]
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
error :
```
OpenCV(4.2.0) C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\dnn.cpp:4559: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20191202::Layer::getMemoryShapes'
when load a onnx model.
```
This is my model structure diagram：[png](https://user-images.githubusercontent.com/11418609/71446108-d1494000-275a-11ea-83c7-7c5847093e31.png)
I can't figure out which node would have no input information.

##### Steps to reproduce
```.cpp

#include <iostream>
#include "opencv2/opencv.hpp"

int main()
{
	try {
		auto net = cv::dnn::readNetFromONNX("H:\\store\\spk\\model_fixed.onnx");

	}
	catch (cv::Exception &e) {
		std::cout << e.msg << std::endl;

	}
	catch (std::exception & e) {
		std::cout << e.what() << std::endl;
	}
}
  ```
this is my model: [model_fixed.zip](https://github.com/opencv/opencv/files/4000478/model_fixed.zip)

**Comment by VictoryDong** [comment]
debug  information ：
  layer_type=="Mul",(dnn/src/onnx/onnx_importer.cpp,line:694)
  layerParams.type = "Power";,(dnn/src/onnx/onnx_importer.cpp,line:702)
 layer->getMemoryShapes(layerInpShapes, 0, layerOutShapes, layerInternalShapes);((dnn/src/onnx/onnx_importer.cpp,line:993)
-----------------------------------------------------------------------------------------
I infer that this should be a logical problem of the Mul node, “layer_id.find (node_proto.input (1)) == layer_id.end ()“  judgment error

**Comment by BadMachine** [comment]
@VictoryDong  Did u solve it?

**Comment by VictoryDong** [comment]
> @VictoryDong Did u solve it?
Not yet

**Comment by dkurt** [comment]
@l-bat, I see you referenced this issue in https://github.com/opencv/opencv_extra/pull/732#discussion_r399994197. Can you check if issue has been solved? Thanks!

**Comment by l-bat** [comment]
This issue is not solved because the model has a strange Expand ops.

**Comment by dkurt** [comment]
Please try https://github.com/opencv/opencv/pull/18096
