### ISSUE TITLE
Is there any plan to provide API for julia language?

### ISSUE THREAD

**Issue by cherichy** [opencv/opencv#16233]
The python interface of Opencv is very easy to use. But for the Julia community, there has been a lack of an good and complete computer vision library like OpenCV. Currently, if someone want to use OpenCV in julia, he/she can only call it indirectly through PyCall.jl. Several existing warppers for OpenCV have also been obsolete for many years. 
Julia has unique advantages in differentiable calculations and numerical calculations, I hope there will be an official Julia API for OpenCV.

**Comment by dkurt** [comment]
@cherichy, feel free to format this proposal as evolution request: https://github.com/opencv/opencv/wiki/Evolution-Proposals. Probably, some of the students and mentors of coming [GSoC 2020](https://github.com/opencv/opencv/wiki/GSoC_2020) would be interested in it.

**Comment by vpisarev** [comment]
@archit120, thank you! Added to the list of evolution proposals: https://github.com/opencv/opencv/wiki/OE-31.-Julia-Bindings

**Comment by archit120** [comment]
Hi @cherichy 

Julia bindings have now been added as part of my GSoC project. It would be great if you could give feedback and help spread the word.
