### ISSUE TITLE
yolov3 CUDA kill time 423ms，not fast, how about it?

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencv/opencv#16234]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

![图片](https://user-images.githubusercontent.com/40679769/71443119-24fc5f00-2744-11ea-8b36-e00c2c8a06c1.png)
 but my cuda 10.1 cudnn 7.2, and windows10 64, nvida 1060T, opencv compile with the cuda, yolov3 kill time 450ms,as below:
![图片](https://user-images.githubusercontent.com/40679769/71443185-83294200-2744-11ea-99db-8144e6a4cafd.png)
How about it?

**Comment by dkurt** [comment]
Please follow issues template and make it reproducible: add minimal working code example.

**Comment by alalek** [comment]
Run OpenCV performance tests first.
No idea what you are measuring (probably model loading, first frame bootstrap time or you custom pre/post processing).
