### ISSUE TITLE
[error 3] please make sure gcc >= 4.4 g++ >= 4.4 is installed

### ISSUE THREAD

**Issue by tsameema** [opencv/opencv#16231]
I am trying to run a code. For this purpose, I have download that code from [github](https://github.com/kopepod/ADCSF).  Whenerver that code tries to check mexopencv. It shows an error
> 
[error 3] please make sure gcc >= 4.4 g++ >= 4.4 is installed ...
> 
Following is the description of system
Window 10
Visual Studio 2012
Matlab 2017a
opencv 2.4.10
mexopencv (install from your folder LIB)

**Comment by dkurt** [comment]
> mexopencv

Please transfer issue to https://github.com/kyamagu/mexopencv
