### ISSUE TITLE
darknet importer: padding is parsed incorrectly for convolutional layers

### ISSUE THREAD

**Issue by YashasSamaga** [opencv/opencv#16259]
### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++ 7.4

##### Detailed description

It appears that the `pad` value in darknet configuration files indicates the padding mode and not the padding value itself. I think `pad` being one implies same padding and `pad` being zero implies manual padding (which is specified in the `padding` parameter).

https://github.com/AlexeyAB/darknet/blob/dcfeea30f195e0ca1210d580cac8b91b6beaf3f7/src/parser.c#L180-L182

The OpenCV darknet parser treats the pad value as the actual padding value. There is also a comment which shows that the original author of the parser was stunned by the weird `pad=1` and sets it to zero. It's actually zero because `pad=1` would imply a padding of `kernel_size//2` which would anyway give zero.

https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/modules/dnn/src/darknet/darknet_io.cpp#L566-L567

**Comment by YashasSamaga** [comment]
This is required for #15987 as it has 5x5 convolutional layers.

**Comment by dkurt** [comment]
Nice catch! You may use https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/darknet/generate_darknet_models.py to generate a test sample.

**Comment by anshu0612** [comment]
I would be like to take up the issue @dkurt

**Comment by dkurt** [comment]
@anshu0612, feel free to open a PR

**Comment by ashishkrshrivastava** [comment]
@anshu0612 , have you started working on this issue ? I would like to take this issue if you haven't because I think I already got the solution.

**Comment by anshu0612** [comment]
hi! @ashishkrshrivastava I am already working on it after going the code base and i’m near the solution. I will be sending the PR soon.
In case of need I’ll inform you. Thanks

**Comment by YashasSamaga** [comment]
@anshu0612 any news? I have a PR to make which requires this bug to be fixed.

**Comment by anshu0612** [comment]
**I apologize for the delay.** 
@ashishkrshrivastava Please go ahead and open a PR since I am stuck with other work.
@YashasSamaga AFAIK we need to take care of max-pooling and avg-pooling layers too.

**Comment by ashishkrshrivastava** [comment]
Thankyou @anshu0612, @YashasSamaga I have already made your suggested changes. I will push PR soon.
