### ISSUE TITLE
cv2.imread does not raise error on loading invalid image 

### ISSUE THREAD

**Issue by AND2797** [opencv/opencv#16269]
cv2 build tested on - `3.4.2` in Python environment 

Using `cv2.imread` on a file that does not exist returns a `None` type (not explicit) instead of raising an error.
I am not sure if this has been fixed on the latest build, can anyone check? Maybe this can be improved to give a more informative error message.

Steps to reproduce -

`import cv2`
`image = cv2.imread('test.jpg') #test.jpg is a file that does not exist in the directory.`

inspecting `image` shows that is a `None` type. There is no explicit error that is raised.

**Comment by dkurt** [comment]
> I am not sure if this has been fixed on the latest build, can anyone check? Maybe this can be improved to give a more informative error message.

Why it should throw an exception this way? This way any `imread` should be covered by try-except block.

According to the [documentation](https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56):

>  The function imread loads an image from the specified file and returns it. If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format), **the function returns an empty matrix ( Mat::data==NULL )**.

**Comment by adamjstewart** [comment]
Just stumbled on this myself, this is one of the most unintuitive bugs ("features"?) I've seen in a Python library. If you try to open a file that doesn't exist, it should error. That's how every builtin function in Python and every other Python library I've ever used works.

**Comment by mattbaker-digital** [comment]
Related issue now RFC: https://github.com/opencv/opencv/issues/14095
