### ISSUE TITLE
Stop using `using namespace  ...` in samples!

### ISSUE THREAD

**Issue by LeonineKing1199** [opencv/opencv#16266]
Can we stop using `using namespace` in all the OpenCV C++ samples?

`using namespace std;` is typically considered poor practice and what's more, it makes it incredibly cumbersome to copy-paste sample code in my application as well as track down where each function comes from specifically.

**Comment by saskatchewancatch** [comment]
Fair point. The samples are intended to be very small, standalone, instructional/demonstrative sources.
The chances of a namespace problems concerning std and everything else in OpenCV are unlikely, and it makes the small source file less intimidating for those starting out with OpenCV.

**Comment by LeonineKing1199** [comment]
Closed and marked as "wontfix". Quality. Discussion.

**Comment by dkurt** [comment]
@LeonineKing1199, feel free to propose a PR.
