### ISSUE TITLE
[BUG] AKAZE detector.detectAndCompute will cause memory leak in async python

### ISSUE THREAD

**Issue by FLming** [opencv/opencv#16283]
##### System information (version)

- opencv-python: 4.1.2.30
- python: 3.6
- Operating System: ubuntu18.04
##### Detailed description
I use Fastapi to build my app, and I find `AKAZE` detector.detectAndCompute will cause memory leak in async python, but `ORB` detector will not. code just like:
```python
def feature_detect(...)
    detector = cv.AKAZE_create()
    kpts, desc = detector.detectAndCompute(gray, mask)
```
and this function will be called by Fastapi with `def` define, in fastapi, a function will `def`, instead of `async def` will create a process pool to run.

**Comment by alalek** [comment]
Python multiprocessing may not work properly due `fork()` call issues: #5150


> memory leak

Please provide more details.

Try to investigate and localize source of this issue.

**Comment by FLming** [comment]
A small example is as follows:
```python
import cv2 as cv
from fastapi import FastAPI

app = FastAPI()

@app.get("/test")
def feature_detect():
    img = cv.imread("cap.jpg", 0)
    detector = cv.AKAZE_create()
    kpts, desc = detector.detectAndCompute(img, None)
    return None
```
and I use ab to send requests.
