### ISSUE TITLE
Any one have the CV_SubPix.cpp and CV_SubPix.h file?

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencv/opencv#16284]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

I am working on a project that uses matchTemplate and I need sub pixel accuracy. I find this web:
https://answers.opencv.org/question/29665/getting-subpixel-with-matchtemplate/
but can't access the CV_SubPix.cpp and CV_SubPix.h file
Any one have this two file? Thank you very mych.

**Comment by LaurentBerger** [comment]
use webarchive  : https://web.archive.org/web/20170921052938/http://www.longrange.net/Temp/CV_SubPix.cpp

**Comment by xinsuinizhuan** [comment]
> https://web.archive.org/web/20170921052938/http://www.longrange.net/Temp/CV_SubPix.cpp

Could you download them, then pass to me(rename them to xx.txt, then attach file by dragging)?
![图片](https://user-images.githubusercontent.com/40679769/71788893-b384b080-3061-11ea-80fd-39b697dc2a90.png)
 I still can't acccess the https://web.archive.org/web/20170921052938/http://www.longrange.net/Temp/CV_SubPix.cpp

**Comment by xinsuinizhuan** [comment]
> 
> 
> use webarchive : https://web.archive.org/web/20170921052938/http://www.longrange.net/Temp/CV_SubPix.cpp

Thank you very much. I have download them.But don't know how to use it.
