### ISSUE TITLE
Compilation error: Intel openvx on Windows

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv#16287]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

Compilation OpenCV on Windows with Intel openVINO 2019.3.379 and openvx from openVINO package. In file modules/core/src/ovx.cpp in line 28:
` static TLSData<OpenVXTLSData>& getOpenVXTLSData()`
_The TLSData is not template._

I'm added in this file: #include "opencv2/core/utils/tls.hpp"
And error was fixed.

**Comment by alalek** [comment]
Thank you for the report.
Feel free to propose PR for 3.4 branch.

OpenVX support in OpenCV is deprecated due lack of performance with current OpenVX calling approach.

**Comment by Nuzhny007** [comment]
>OpenVX support in OpenCV is deprecated due lack of performance with current OpenVX calling approach.
Ok, thank you.
