### ISSUE TITLE
OpenCV 3.1 + Protobuf 3.11 will have this error while building OpenCV

### ISSUE THREAD

**Issue by RioChan** [opencv/opencv#16281]
##### Steps to reproduce

Hi Champs:
I'm using the uBuntu18.10 + OpenCV 3.1 + Protobuf 3.11.
I'm having this error while building OpenCV with "make all -j4".

I studied for 2 days from the google, and found no solid answer.

/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2083:8: error: ‘void caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const’ marked ‘final’, but is not virtual
   void SerializeWithCachedSizes(
        ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2085:35: error: ‘google::protobuf::uint8* caffe::SolverParameter::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
   ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2632:8: error: ‘bool caffe::SolverState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’ marked ‘final’, but is not virtual
   bool MergePartialFromCodedStream(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2635:8: error: ‘void caffe::SolverState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const’ marked ‘final’, but is not virtual
   void SerializeWithCachedSizes(
        ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2637:35: error: ‘google::protobuf::uint8* caffe::SolverState::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
   ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2807:8: error: ‘bool caffe::NetState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’ marked ‘final’, but is not virtual
   bool MergePartialFromCodedStream(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2810:8: error: ‘void caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const’ marked ‘final’, but is not virtual
   void SerializeWithCachedSizes(
        ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2812:35: error: ‘google::protobuf::uint8* caffe::NetState::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
   ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2974:8: error: ‘bool caffe::NetStateRule::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’ marked ‘final’, but is not virtual
   bool MergePartialFromCodedStream(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2977:8: error: ‘void caffe::NetStateRule::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const’ marked ‘final’, but is not virtual
   void SerializeWithCachedSizes(
        ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/OpenVX_Demo/opencv-3.1.0/build/modules/dnn/caffe.pb.h:2979:35: error: ‘google::protobuf::uint8* caffe::NetStateRule::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual

------------------------
I have tried to remove do the following steps, but with the same error.
Below is my build config.
ps. I have the conda for Caffe in the same ubuntu before.

	cmake -D CMAKE_INSTALL_PREFIX=/opt/OpenVX_Demo \
-D OPENCV_EXTRA_MODULES_PATH=/opt/OpenVX_Demo/opencv_contrib-3.1.0/modules \
-D BUILD_DOCS=OFF -D BUILD_PACKAGE=OFF -D BUILD_PERF_TESTS=OFF \
-D BUILD_TESTS=OFF -D BUILD_opencv_apps=OFF \
-D BUILD_opencv_nonfree=OFF -D BUILD_opencv_stitching=OFF \
-D BUILD_opencv_superres=OFF -D BUILD_opencv_ts=OFF \
-D BUILD_WITH_DEBUG_INFO=OFF -D WITH_1394=OFF -D WITH_CUDA=OFF \
-D WITH_CUFFT=OFF -D WITH_GIGEAPI=OFF -D WITH_JASPER=OFF \
-D WITH_OPENEXR=OFF -D WITH_PVAPI=OFF -D WITH_GTK=OFF \
-D ENABLE_PRECOMPILED_HEADERS=OFF \
-D BUILD_opencv_python=ON \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D BUILD_PROTOBUF=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D BUILD_EXAMPLES=ON ..

**Comment by RioChan** [comment]
Hi Champs:

I have solved this by adding those 2:

+               -DBUILD_PROTOBUF=OFF
+               -DBUILD_opencv_dnn=OFF

1 more question:
    How to open those 3 options ON with no any build error?
    WITH_CUDA=OFF
    BUILD_PROTOBUF=OFF
    BUILD_opencv_dnn=OFF


BR Rio

**Comment by dkurt** [comment]
Have you tried newer version but not OpenCV 3.1.0?

**Comment by dkurt** [comment]
Let's close this issue. Feel free to add more details if problem remains.
