### ISSUE TITLE
error: (-215: Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by Alpheron** [opencv/opencv#16288]
Hello all, I was trying to run an OpenCV program to run a DNN on an Android device using the OpenCv DNN module with Tensorflow and an SSD. However, I keep receiving this error when I try to run the program. CvException - cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:692: error: (-2.15:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes' I do not know how to fix this error because as far as I know, my code to access the protobuf and protobuf text file seems correct. My code to access the variables and read from them seem correct and the other OpenCV loaders are in other classes which seem to work fine. My code to access the pb and the pbtxt file are listed below:

```
public Mat processFrame(Mat inputFrame) {
    final int IN_WIDTH = 300;
    final int IN_HEIGHT = 300;
    final double IN_SCALE_FACTOR = 1;
    final double MEAN_VAL = 0;
    final double THRESHOLD = 0.85;

    // Get a new frame
    Imgproc.cvtColor(inputFrame, inputFrame, Imgproc.COLOR_RGBA2RGB);

    // Forward image through network.
    Mat blob = Dnn.blobFromImage(inputFrame, IN_SCALE_FACTOR, new Size(IN_WIDTH, IN_HEIGHT), new Scalar(MEAN_VAL, MEAN_VAL, MEAN_VAL), true, false);
    net.setInput(blob);

    List<List<Double>> blobList = new ArrayList<>();

    Mat detections = net.forward();

    int cols = inputFrame.cols();
    int rows = inputFrame.rows();


    detections = detections.reshape(1, (int) detections.total() / 7);
    for (int i = 0; i < detections.rows(); ++i) {
        System.out.println(detections);
        double confidence = detections.get(i, 2)[0];

        if (confidence > THRESHOLD) {
            int classId = (int) detections.get(i, 1)[0];
            int left = (int) (detections.get(i, 3)[0] * cols);
            int top = (int) (detections.get(i, 4)[0] * rows);
            int right = (int) (detections.get(i, 5)[0] * cols);
            int bottom = (int) (detections.get(i, 6)[0] * rows);

            List<Double> list = new ArrayList<>();
            list.add(confidence);
            list.add(Double.valueOf(left));
            list.add(Double.valueOf(top));
            list.add(Double.valueOf(right));
            list.add(Double.valueOf(bottom));
            list.add(Double.valueOf(classId));

            blobList.add(list);
        }
    }

    Collections.sort(blobList, new Comparator<List<Double>>() {
        @Override
        public int compare(List<Double> a, List<Double> b) {
            return a.get(0) > b.get(0) ? 1 : -1;
        }
    });

    Collections.reverse(blobList);

    int maxIndex = blobList.size() > 6 ? 6 : blobList.size();
    int numOfSkystone = 0;

    for (int i = 0; i < 6; i++) {
        List<Double> blobStuff = blobList.get(i);
        String detectedObj = "";


        double v = blobStuff.get(5).doubleValue();
        if (v == 3.0) {
            detectedObj = "Skystone";
            numOfSkystone++;
        } else if (v == 4.0) {
            detectedObj = "Stone";
        } else if (v == 2.0) {
            detectedObj = "Red Foundation";
        } else if (v == 1.0) {
            detectedObj = "Blue Foundation";
        } else {
            detectedObj = "Unknown";
        }

        String label = detectedObj + ": " + blobStuff.get(0);
        int[] baseLine = new int[1];
        Size labelSize = Imgproc.getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, baseLine);
        Imgproc.rectangle(inputFrame, new Point((int) blobStuff.get(1).intValue(), (int) blobStuff.get(2).intValue() - labelSize.height),
                new Point((int) blobStuff.get(1).intValue() + labelSize.width, (int) blobStuff.get(2).intValue() + baseLine[0]),
                new Scalar(255, 255, 255), Imgproc.FILLED);
        // Write class name and confidence.
        Imgproc.putText(inputFrame, label, new Point(blobStuff.get(0), blobStuff.get(2)),
                FONT_HERSHEY_SIMPLEX, 0.5, new Scalar(0, 0, 0));
    }
    return inputFrame;
}
```
As far as I know, the code for that seems correct but I feel like the error may be within the pbtxt file, but I have no clue how to fix it. The pbtxt had to be attacked as a link mainly because of the reason that it is very very long close to 5000 lines and I ran the tf_graph_ssd.py file in order to generate it. However, all the lines in that too seem correct can anyone help me understand what is going wrong with it?

PB file, Pbtxt, config: https://drive.google.com/drive/folders/19g7xnC9ekjUHeFNtgcvSn2J1ioWmrb_L?usp=sharing

I am trying to build an Android app with OpenCv 4.1.0 and it is being developed on a 2012 Macbook Pro with Mac OS X 10.15.2

@dkurt, since you are the lead developer for the DNN module, how would you go about solving this issue?

**Comment by dkurt** [comment]
> I am trying to build an Android app with OpenCv 4.1.0 and it is being developed on a 2012 Macbook Pro with Mac OS X 10.15.2

Please try the latest master branch or at least newer release. Thanks!

**Comment by Alpheron** [comment]
However, I am developing an Android app. Would updating to the newest android build tools solve the problem @dkurt ?

**Comment by dkurt** [comment]
@Alpheron, Which version of tf_text_graph_ssd.py is used? Note that for OpenCV 4.1.0 it's better to use corresponding version of the script: https://github.com/opencv/opencv/blob/4.1.0/samples/dnn/tf_text_graph_ssd.py. Please try it.

**Comment by dkurt** [comment]
From the model.config:
```
      fixed_shape_resizer {
        height: 256
        width: 256
      }
```
that means the network should work on 256x256 input blobs but not 300x300 as in the code snippet.

**Comment by Alpheron** [comment]
So what I find odd is that I have a python version that runs properly using the same 300x300 blobs and I used the same tf_text_graph_ssd.py script.
```
import cv2 as cv
from collections import defaultdict
cvNet = cv.dnn.readNetFromTensorflow('model.pb', 'model.pbtxt')

cap = cv.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, img = cap.read()
    rows = img.shape[0]
    cols = img.shape[1]
    cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
    cvOut = cvNet.forward()
    numOfSkystone = 0
    objects_dict = {}
    StoneOrder = []
    for detection in cvOut[0,0,:,:]:
        score = float(detection[2])
        if score > 0.85:
            objectClass = detection[1]
            left = detection[3] * cols
            top = detection[4] * rows
            right = detection[5] * cols
            bottom = detection[6] * rows
            objects_dict[score]=[left,top,right,bottom, objectClass]
            
        
    l=list(objects_dict.keys())
    l.sort(reverse=True)
    for i in l[:6] :
        #print(i,objects_dict[i])
        if objects_dict[i][4] == 3.0:
            detectedObject = "Skystone"
            numOfSkystone +=1
        elif objects_dict[i][4] == 4.0:
            detectedObject = "Stone"
        elif objects_dict[i][4] == 2.0:
            detectedObject = "Red Foundation"
        elif objects_dict[i][4] == 1.0:
            detectedObject = "Blue Foundation"
        cv.rectangle(img, (int(objects_dict[i][0]), int(objects_dict[i][1])), (int(objects_dict[i][2]), int(objects_dict[i][3])), (23, 230, 210), thickness=5)
        cv.putText(img, detectedObject, (int(objects_dict[i][0]), int(objects_dict[i][1])), cv.FONT_HERSHEY_SIMPLEX, 2, (0,0,0), 7, cv.LINE_AA)
        #print(i, objects_dict)
        StoneOrder.append(detectedObject)
        if numOfSkystone==2:
            
            #print(StoneOrder)
            SkystonePosition = [i for i, value in enumerate(StoneOrder) if value == "Skystone"]
            print('The Skystone is located in positions: ' + str(int(SkystonePosition[0]) + 1) + ' and ' + str(int(SkystonePosition[1]) + 1))

    cv.imshow('img', img)
    cv.waitKey(1)
    cv.destroyAllWindows()
```

**Comment by dkurt** [comment]
@Alpheron, probably, Python's version of OpenCV is different (check `cv.__version__`).

Let me check if the network can work with OpenCV 4.1.0.

**Comment by Alpheron** [comment]
So I checked the version just now on my computer and it outputs `'4.1.0`

**Comment by dkurt** [comment]
@Alpheron, So 4.1.0 release also works fine for me. Can you check once again Android version of OpenCV? You may also provide `getBuildInformation()` output.

Please also debug the code more careful - `net` object initialization and if `inputFrame` is empty or not.

**Comment by Alpheron** [comment]
My app has a bit more modules and libraries but I'll post what I can:
`package org.firstinspires.ftc.teamcode.modules;

import org.firstinspires.ftc.teamcode.core.Hardware;
import org.opencv.core.*;
import org.opencv.dnn.Dnn;
import org.opencv.dnn.Net;
import org.opencv.imgproc.Imgproc;
import org.openftc.easyopencv.OpenCvPipeline;

import java.util.*;
import java.lang.*;


import static org.apache.commons.io.FilenameUtils.getPath;
import static org.opencv.imgproc.Imgproc.FONT_HERSHEY_SIMPLEX;

/**
 * SUPER COOL, ADVANCED, OPENCV DNN NEURAL NETWORK!!!
 */

public class CvPipeline extends OpenCvPipeline {

    private static Net net;
    public Hardware hardware;
    private static final String TAG = "OpenCV/DNN";

    public CvPipeline(Hardware hardware) {
        String pbFile = getPath("model.pb");
        String pbTxt = getPath("model.pbtxt");
        net = Dnn.readNetFromTensorflow(pbFile);
        this.hardware = hardware;
    }

    @Override
    public Mat processFrame(Mat inputFrame) {
        final int IN_WIDTH = 300;
        final int IN_HEIGHT = 300;
        final double IN_SCALE_FACTOR = 1;
        final double MEAN_VAL = 0;
        final double THRESHOLD = 0.85;

        // Get a new frame
        Imgproc.cvtColor(inputFrame, inputFrame, Imgproc.COLOR_RGBA2RGB);

        // Forward image through network.
        Mat blob = Dnn.blobFromImage(inputFrame, IN_SCALE_FACTOR, new Size(IN_WIDTH, IN_HEIGHT), new Scalar(MEAN_VAL, MEAN_VAL, MEAN_VAL), true, false);
        net.setInput(blob);

        List<List<Double>> blobList = new ArrayList<>();

        Mat detections = net.forward();

        int cols = inputFrame.cols();
        int rows = inputFrame.rows();


        detections = detections.reshape(1, (int) detections.total() / 7);
        for (int i = 0; i < detections.rows(); ++i) {
            System.out.println(detections);
            double confidence = detections.get(i, 2)[0];

            if (confidence > THRESHOLD) {
                int classId = (int) detections.get(i, 1)[0];
                int left = (int) (detections.get(i, 3)[0] * cols);
                int top = (int) (detections.get(i, 4)[0] * rows);
                int right = (int) (detections.get(i, 5)[0] * cols);
                int bottom = (int) (detections.get(i, 6)[0] * rows);

                List<Double> list = new ArrayList<>();
                list.add(confidence);
                list.add(Double.valueOf(left));
                list.add(Double.valueOf(top));
                list.add(Double.valueOf(right));
                list.add(Double.valueOf(bottom));
                list.add(Double.valueOf(classId));

                blobList.add(list);
            }
        }

        Collections.sort(blobList, new Comparator<List<Double>>() {
            @Override
            public int compare(List<Double> a, List<Double> b) {
                return a.get(0) > b.get(0) ? 1 : -1;
            }
        });

        Collections.reverse(blobList);

        int maxIndex = blobList.size() > 6 ? 6 : blobList.size();
        int numOfSkystone = 0;

        for (int i = 0; i < 6; i++) {
            List<Double> blobStuff = blobList.get(i);
            String detectedObj = "";


            double v = blobStuff.get(5).doubleValue();
            if (v == 3.0) {
                detectedObj = "Skystone";
                numOfSkystone++;
            } else if (v == 4.0) {
                detectedObj = "Stone";
            } else if (v == 2.0) {
                detectedObj = "Red Foundation";
            } else if (v == 1.0) {
                detectedObj = "Blue Foundation";
            } else {
                detectedObj = "Unknown";
            }

            String label = detectedObj + ": " + blobStuff.get(0);
            int[] baseLine = new int[1];
            Size labelSize = Imgproc.getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, baseLine);
            Imgproc.rectangle(inputFrame, new Point((int) blobStuff.get(1).intValue(), (int) blobStuff.get(2).intValue() - labelSize.height),
                    new Point((int) blobStuff.get(1).intValue() + labelSize.width, (int) blobStuff.get(2).intValue() + baseLine[0]),
                    new Scalar(255, 255, 255), Imgproc.FILLED);
            // Write class name and confidence.
            Imgproc.putText(inputFrame, label, new Point(blobStuff.get(0), blobStuff.get(2)),
                    FONT_HERSHEY_SIMPLEX, 0.5, new Scalar(0, 0, 0));
        }
        return inputFrame;
    }
}`

Input frame does seem to be returning a valid frame when not using the DNN. Net initialization seems correct too since it does seem to be using the Net variable which is initialized in the top 10 lines.

**Comment by dkurt** [comment]
>    String pbFile = getPath("model.pb");
    String pbTxt = getPath("model.pbtxt");
    net = Dnn.readNetFromTensorflow(pbFile);

It seems to me it should be something like
```
net = Dnn.readNetFromTensorflow(pbFile, pbTxt);
```
?

**Comment by Alpheron** [comment]
Yes, that is what I originally thought it was but then I remembered the pbtxt file was optional and tried to run the net that way too. Unfortunately, what you had suggested earlier with:

> > String pbFile = getPath("model.pb");
> > String pbTxt = getPath("model.pbtxt");
> > net = Dnn.readNetFromTensorflow(pbFile);
> 
> It seems to me it should be something like
> 
> ```
> net = Dnn.readNetFromTensorflow(pbFile, pbTxt);
> ```
> 
> ?

Adding both the pbtxt and the pb file make no difference to mitigate the error. The error is exactly the same as what it was before `CvException - cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:692: error: (-2.15:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'`

**Comment by dkurt** [comment]
> Adding both the pbtxt and the pb file make no difference to mitigate the error. The error is exactly the same as what it was before CvException - cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:692: error: (-2.15:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'

What is what is strange. Error should be different because without `.pbtxt` file the error should be at `readNetFromTensorFlow` but not at `forward`. so I think that `model.pb` attached to the issue is different from one which is used in the app.

OpenCV 4.1.0:
```
>>> cv.dnn.readNet('model.pb')
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('model.pb')
cv2.error: OpenCV(4.1.0) /home/dkurt/opencv/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:860: error: (-215:Assertion failed) nodesMapIt != nodesMap.end() in function 'sortByExecutionOrder'
```

**Comment by Alpheron** [comment]
@dkurt When I run the same Python program without the `.pbtxt` file, it throws the same error which you describe above. However, when I run the code I sent above in Java, it throws the same error `CvException - cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:692: error: (-2.15:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'` whether there are both `.pb` and `.pbtxt` files included or just the `.pb` file.  Any clue on what it may be?

**Comment by Alpheron** [comment]
@dkurt Has any progress been made on this issue?

**Comment by Alpheron** [comment]
@dkurt Has this issue been solved yet? I believe it is something to do with the actual internal android build pack itself because the syntax and net initialization seems correct and the Python code seems to work perfectly fine. Would you be able to explain to me what the error means and what the issue with the code is?

**Comment by dkurt** [comment]
The problem us solved and the model works fine woth OpenCV 4.1.0. You need to investigate why Android version behaves differently comparing to Python - check versions, output from getBuildInformation.

**Comment by Alpheron** [comment]
@dkurt I have been able to acquire the output from `getBuildInformation` and it seems to be fairly identical to the Python one that I have installed on my computer aside from the filepaths and the C++ compiler. Below is what I have received when running the `getBuildInformation` command on the app.
`General configuration for OpenCV 4.1.0 =====================================
   Version control:               4.1.0
   Platform:
     Timestamp:                   2019-04-07T19:00:18Z
     Host:                        Linux 4.15.0-47-generic x86_64
     Target:                      Android 1 armv7-a
     CMake:                       3.6.0-rc2
     CMake generator:             Ninja
     CMake build tool:            /opt/android/android-sdk.gradle/cmake/3.6.4111459/bin/ninja
     Configuration:               Release
   CPU/HW features:
     Baseline:                    NEON
       requested:                 DETECT
   C/C++:
     Built as dynamic libs?:      NO
     C++ Compiler:                /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  (ver 7.0)
     C++ flags (Release):         -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden  -Oz -DNDEBUG   -DNDEBUG
     C++ flags (Debug):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
     C Compiler:                  /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
     C flags (Release):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden  -Oz -DNDEBUG   -DNDEBUG
     C flags (Debug):             -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
     Linker flags (Release):      -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now    
     Linker flags (Debug):        -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now    
     ccache:                      YES
     Precompiled headers:         NO
     Extra dependencies:          z dl m log
     3rdparty dependencies:       tbb libcpufeatures libprotobuf libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc tegra_hal
   OpenCV modules:
     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java ml objdetect photo stitching video videoio
     Disabled:                    world
     Disabled by dependency:      -
     Unavailable:                 gapi js python2 python3 ts
     Applications:                -
     Documentation:               NO
     Non-free algorithms:         NO
   Android NDK:                   /opt/android/android-ndk-r18b (ver 18.1.5063045)
     Android ABI:                 armeabi-v7a
     NDK toolchain:               arm-linux-androideabi-clang
     STL type:                    c++_static
     Native API level:            21
   Android SDK:                   /opt/android/android-sdk.gradle (tools: 26.1.1 build tools: 28.0.3)
   GUI: 
   Media I/O: 
     ZLib:                        z (ver 1.2.7)
     JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
     WEBP:                        build (ver encoder: 0x020e)
     PNG:                         build (ver 1.6.36)
     TIFF:                        build (ver 42 - 4.0.10)
     JPEG 2000:                   build (ver 1.900.1)
     OpenEXR:                     build (ver 1.7.1)
     HDR:                         YES
     SUNRASTER:                   YES
     PXM:                         YES
     PFM:                         YES
   Video I/O:
   Parallel framework:            TBB (ver 2018.0 interface 10001)
   Trace:                         YES (built-in)
   Other third-party libraries:
     Custom HAL:                  YES (carotene (ver 0.0.1))
     Protobuf:                    build (3.5.1)
   Python (for build):            /usr/bin/python2.7
   Java:                          export all functions
     ant:                         NO
     Java wrappers:               YES
     Java tests:                  NO
   Install to:                    /build/master_pack-android/build/o4a/install
 -----------------------------------------------------------------`

**Comment by dkurt** [comment]
@Alpheron, So still I have concerns with you environment because
```
 net = Dnn.readNetFromTensorflow(pbFile);
```
should throw
```
cv2.error: OpenCV(4.1.0) /home/dkurt/opencv/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:860: error: (-215:Assertion failed) nodesMapIt != nodesMap.end() in function 'sortByExecutionOrder'
```

Try to delete an app from the device, rebuild the solution.

**Comment by BadMachine** [comment]
Similar problem here.
Tryin` to use onnx model.
Attempt to load model:
```C++
auto network = readNetFromONNX("test.onnx");
```
Error:

{msg="OpenCV(4.2.0-pre) F:\\OpenCV\\opencv-master\\modules\\dnn\\src\\dnn.cpp:4479: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20191202::Layer::getMemoryShapes'\n" 
[MODEL LINK](https://drive.google.com/open?id=1qQ5oFBk8UjzK0FAYLBaCYcGYfKMm5AXB)

**Comment by dkurt** [comment]
@BadMachine, pleasae open a separate issue

**Comment by Alpheron** [comment]
@dkurt I have reconfigured my OpenCV installation on the Android device and when i only include the PB_file, it seems to throw a very similar error to what you have aforementioned with differences in the file paths. However, when I include both the Pb file and the Pbtxt it throws this error `CvException - cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:692: error: (-2.15:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'`

**Comment by dkurt** [comment]
@Alpheron, We cannot debug this app remotely.

As you experimented, Python code of OpenCV 4.1.0 works fine so you need to properly port it to Android. Check that Java and Python samples are similar, check that both .pb and .pbtxt files are the same.
