### ISSUE TITLE
haarcascade_mcs_mouth.xml throws SystemError

### ISSUE THREAD

**Issue by jzod** [opencv/opencv#16299]
### System information (version)

- OpenCV => 4.1.0.26, 4.1.0.30, 4.1.2
- Operating System / Platform => Windows 10 / 64 Bit
- Compiler => Python 3.6

##### Detailed description

When trying to open the file haarcascade_mcs_mouth.xml I get a SystemError “Unable to display children”. I went back and installed OpenCV version 3.4.4.19 and it worked with no error. So, I continued to work my way to newer versions, and it failed on version 4.1.0.26. The last version that worked was 4.1.0.25.

##### Steps to reproduce

import cv2
cascade = cv2.CascadeClassifier('haarcascade_mcs_mouth.xml')

**Comment by alalek** [comment]
>  it failed on version 4.1.0.26. The last version that worked was 4.1.0.25

Looks like this issue relates to Python bindings package distribution.
It is better to check/fill problem in proper repository:
- information about the package: https://pypi.org/project/opencv-python/
- issue's tracker: https://github.com/skvark/opencv-python/issues
