### ISSUE TITLE
cv2.VideoCapture on GIF files break after Pyinstaller

### ISSUE THREAD

**Issue by BurguerJohn** [opencv/opencv#16296]
Sorry if this is a bug generated by pyinstaller, I don't have enough knowledge to know who is responsible for this bug.

##### System information (version)

- OpenCV => Tested in 4.1.2.30 and 3.4.8.29
- Operating System / Platform => Windows 10 Windows 64 Bit
- Compiler =>Python 3.6.9
- PyInstaller => 3.5

##### Detailed description

Using cv2.VideoCapture with both **mp4** and **gif** files as input work perfectly before compiling a .exe using pyinstaller. Trying the same code in the .exe generated by pyinstaller still work for **mp4** files, but for **gif** files it throw this error:
````
[ERROR:0] VIDEOIO(cvCreateFileCapture_Images(filename.c_str())): raised OpenCV exception:

OpenCV(3.4.8) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:246: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): E:\Downloads\gifs\mygif.gif in function 'cv::icvExtractPattern'
````

##### Steps to reproduce

Write a .py file with this code:
````
import cv2

def GetFPS(pathVideo):
    cam = cv2.VideoCapture(pathVideo)
    print("Input FPS: " + str(cam.get(cv2.CAP_PROP_FPS)))

GetFPS("{Full path to mp4 file}")
GetFPS("{Full path to gif file}")
````

Now run the code:
`pyinstaller myfile.py`

Executing the final .exe should run the mp4 just fine, but thow the error in the gif file.

**Comment by alalek** [comment]
You need to [debug videoio subsystem](https://docs.opencv.org/3.4/de/db1/group__videoio__registry.html).
Perhaps FFmpeg DLL is lost in your distribution.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by BurguerJohn** [comment]
Thanks for the fast and correct answer. You are awesome.
You are right, adding the dll fixed the problem.
For anyone with the same problem. You need to use 
`--add-data opencv_ffmpeg348_64.dll;.` (Name is the same of the opencv version)
to compile the script.
