### ISSUE TITLE
Disabling tests while enabling freetype support breaks CMake configuration process

### ISSUE THREAD

**Issue by h6197627** [opencv/opencv#16290]
CMake configuring of OpenCV 4.2.0 breaks when WITH_FREETYPE support is enabled and BUILD_TESTS is disabled with error:
```
CMake Error at cmake/OpenCVUtils.cmake:1465 (message):
  ocv_target_compile_definitions: invalid target: 'opencv_test_gapi'
Call Stack (most recent call first):
  modules/gapi/CMakeLists.txt:151 (ocv_target_compile_definitions)
```

##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.4.0

##### Steps to reproduce

> mkdir build && cd build

> cmake -D WITH_FREETYPE=ON -D BUILD_TESTS=OFF ..

**Comment by asmorkalov** [comment]
@dmatveev please take a look.
