### ISSUE TITLE
[BUG] The grayscale image by imread() is incorrect!

### ISSUE THREAD

**Issue by sunkyoo** [opencv/opencv#16297]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit / C++ & Python
- Compiler => Visual Studio 2017, Python 3.7.6

##### Detailed description

I just updated OpenCV 4.2.0 and found a big problem.
If I open the lenna BMP image with IMREAD_GRAYSCALE flag, the image is little bit dark. (the mean value was 110)
I felt something weird because I knew the mean value of lenna gray image is 124.
So I tried to open the lenna image as a color image and convert it to a grayscale image using cvtColor(), then the mean value was 124.
So there must be something wrong on the color conversion code in imread().

##### Steps to reproduce

Mat src1 = imread("lenna.bmp", IMREAD_GRAYSCALE);
Mat src2 = imread("lenna.bmp", IMREAD_COLOR);
cvtColor(src2, src2, COLOR_BGR2GRAY);
			
cout << mean(src1)[0] << endl;  // 110.207
cout << mean(src2)[0] << endl;  // 124.049

##### My opinion

I checked the recent versions, and found that OpenCV 4.1.0 was ok.
So I searched commits and found it:
https://github.com/opencv/opencv/commit/058367f34c60d6a843579adce84895f4bc5d31dd#diff-c868f69925dd124c54190546d4843841

In the updated code, I think 68th line should be changed like this:

(-) if (_swap_rb) std::swap(cRGB0, cRGB2);
(+) if (!_swap_rb) std::swap(cRGB0, cRGB2);

Please check the code.

**Comment by alalek** [comment]
Looks like a duplicate of #16215 (fix is available on 3.4 branch and will be merged into master soon)

**Comment by sunkyoo** [comment]
Ok, thanks.
