### ISSUE TITLE
Glitch in cv::ellipse(): draws horizontal lines if thickness is low

### ISSUE THREAD

**Issue by mcamurri** [opencv/opencv#16301]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc

##### Detailed description

When drawing an ellipse with specific but not pathological values and a line thickness less than 5, horizontal lines are displayed.

##### Steps to reproduce
The following snipped is sufficient to expose the problem:
![Screenshot from 2020-01-07 12-21-10](https://user-images.githubusercontent.com/13381545/71895240-67606b80-3148-11ea-8f67-3b862e7f11b7.png)

```
#include <opencv2/viz/types.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui.hpp> // for imshow

int main(int argc, char** argv){
  cv::RotatedRect rect;
  rect.angle = 6.52944;
  rect.center.x = 201.968;
  rect.center.y = 373.492;
  rect.size.width = 65.2557;
  rect.size.height = 20.5783;

  cv::Mat test(848,800,CV_8UC3);
  cv::ellipse(test,rect,cv::viz::Color::magenta(),2);
  cv::imshow("windowName", test);
  cv::waitKey(0);
}
```

When using a higher thickness (e.g., 5) the problem goes away.

**Comment by dkurt** [comment]
> OpenCV => 3.2.0

Have you tried newer version?

**Comment by mcamurri** [comment]
> > OpenCV => 3.2.0
> 
> Have you tried newer version?

I've just tried the 3.4.9 locally just now and the problem disappeared. 
Unfortunately, I'm forced to use the 3.2.0 version as it is the default for Ubuntu 18.04 / ROS Melodic.

**Comment by dkurt** [comment]
So if you are not able to rebuild library - there is a little chance that you can fix it in runtime. Can we close the issue due there is no feature request and the problem is solved in current state of OpenCV?

**Comment by mcamurri** [comment]
I guess so, thank you.
