### ISSUE TITLE
  How to open Android USB camera with QT for Android + opencv

### ISSUE THREAD

**Issue by smileflyfish** [opencv/opencv#16317]
I'm trying to move a very simple OpenCV application to android. The code tries to access the camera from a qt for android . My qt code simply tries to access the camera using cv::VideoCapture like so:
    cv::VideoCapture cap(0); //  /dev/video0
Camera cannot be opened,Permissions are open,chmod 777 /dev/video0,The camera still doesn't open.
What did I add less? Or is my method wrong, Android can't open the camera in this way at all?
Opencv version:　4.1.1
qt version:　5.12.3
android ndk: android-ndk-r19c

**Comment by alalek** [comment]
Not supported.

I believe you should take a look in direction of NDK Camera API:
- https://github.com/android/ndk-samples/tree/master/camera

There is already feature request for that. Marking as duplicate.

> qt version

QT do nothing with camera.

**Comment by smileflyfish** [comment]
cv::Mat frame=cv::imread("open.jpg");
The picture can be opened and displayed normally,basic configuration should be ok.
Refer to the relevant materials, where does libnative_camera.so come from? I can't find it in opencv Android SDK. Do I need cross compilation of source code?

**Comment by smileflyfish** [comment]
Well, thank you!
