### ISSUE TITLE
Hi, i get the same problem too.. help me please to slve this.. wthat's going wrong?

### ISSUE THREAD

**Issue by Rumpic** [opencv/opencv#16315]
Hi, i get the same problem too.. help me please to slve this.. wthat's going wrong?

[ 83%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
/Users/Myuser/OpenCV/opencv/modules/python/src2/cv2.cpp:17:10: fatal error: 'python.h' file not found
#include <python.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:63: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [all] Error 2

_Originally posted by @Abdurrasith in https://github.com/opencv/opencv/issues/6464#issuecomment-557863173_

**Comment by dkurt** [comment]
Please provide all the necessary information to reproduce this error (build flags and CMake output in that case). Until that let's keep it closed.

**Comment by sxj731533730** [comment]
/home/pi/opencv/modules/python/src2/cv2.cpp:17:10: fatal error: Python.h: No such file or directory
 #include <Python.h>

**Comment by dkurt** [comment]
@sxj731533730, please do not use closed issues to ask build or usage questions.

You need to install `libpython-dev` to solve the problem
