### ISSUE TITLE
In python, cv2.addWeighted changes shape of image

### ISSUE THREAD

**Issue by rggjan** [opencv/opencv#16313]
##### System information (version)
- opencv-python-headless 3.4.5.20 (from conda)
- Operating System / Platform => OSX

##### Detailed description

I would assume that running `cv2.addWeighted` preserves the shape of the array I put in. However, if the last dimension of the images is `1` (instead of missing), then that dimension is removed in the output array. See the following sample code:

##### Steps to reproduce

```
import cv2
import numpy as np

side = 10

input = np.random.random(side * side).reshape((side, side, 1))
output = cv2.addWeighted(input, alpha=0, src2=0, beta=0, gamma=0)

print(input.shape)
print(output.shape)

assert input.shape == output.shape
```

**Comment by dkurt** [comment]
please read https://github.com/opencv/opencv/issues/16126#issuecomment-564388040

**Comment by rggjan** [comment]
I see, thanks!
