### ISSUE TITLE
Possible Bug: TypeError: descriptor 'setPreferableTarget' requires a 'cv2.dnn_Net' object but received a 'int'

### ISSUE THREAD

**Issue by mcarpenterjr** [opencv/opencv#16320]
##### System information (version)

 Using the cv2 libraray in a python3.6 application, when I try to set the preferable target to CUDA using the line `cv.dnn_Net.setPreferableTarget(cv.dnn.DNN_TARGET_CUDA)` I get the following error;
```
TypeError: descriptor 'setPreferableTarget' requires a 'cv2.dnn_Net' object but received a 'int'
```
I followed the 4.2 docs when determing the object to use when setting the target.

Can't really determine if it's a bug or silly mistake.Everything else runs without issue.

**Comment by dkurt** [comment]
`setPreferableTarget` is not a static object of `cv::dnn::Net`. You need to create an object first.

Follow the Python samples: https://github.com/opencv/opencv/tree/master/samples/dnn

**Comment by mcarpenterjr** [comment]
Yerp silly mistake, I just wasn't seeing it.
