### ISSUE TITLE
OpenCV requires enabled 'cudev' module from 'opencv_contrib' repository

### ISSUE THREAD

**Issue by efedoganay** [opencv/opencv#16331]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Linux Ubuntu 18.04
- CUDA => 10.2
##### Detailed description

I am trying to build opencv 4.2.0 with cmake with the following command

 `cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
        -D BUILD_TIFF=ON \
        -D WITH_FFMPEG=ON \
        -D WITH_GSTREAMER=ON \
        -D WITH_TBB=ON \
        -D BUILD_TBB=ON \
        -D WITH_EIGEN=ON \
        -D WITH_V4L=ON \
        -D WITH_LIBV4L=ON \
        -D WITH_VTK=OFF \
        -D WITH_OPENGL=ON \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D INSTALL_C_EXAMPLES=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D BUILD_NEW_PYTHON_SUPPORT=ON \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D BUILD_TESTS=OFF \
        -D BUILD_EXAMPLES=OFF \
        -D WITH_CUDA=ON \
        -D ENABLE_FAST_MATH=ON \
        -D CUDA_FAST_MATH=ON \` 

after a bit, although I have opencv_contrib and cudev, I got an error stating:

`CMake Error at cmake/OpenCVModule.cmake:288 (message):
  No modules has been found: ~/opencv_contrib/modules
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:370 (_glob_locations)
  modules/CMakeLists.txt:7 (ocv_glob_modules)`

`-- OpenCV Python: during development append to PYTHONPATH: ~/openwork/opencv/build/python_loader
CMake Error at modules/core/CMakeLists.txt:40 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib`

Any ideas on how to resolve this? Thanks.

**Comment by dkurt** [comment]
> No modules has been found: ~/opencv_contrib/modules

Have you checked that this folder exists?

**Comment by efedoganay** [comment]
> > No modules has been found: ~/opencv_contrib/modules
> 
> Have you checked that this folder exists?

Yes, both opencv_contrib and cudev folders exist.

**Comment by efedoganay** [comment]
Resolved the issue by manually adding the extra modules path with cmake-gui.

**Comment by molyswu** [comment]
How to adding the extra modules path with cmake-gui?

Thank!
