### ISSUE TITLE
Could not find CUDA: Found unsuitable version "9.1" but required is exact version "10.2"

### ISSUE THREAD

**Issue by efedoganay** [opencv/opencv#16333]
##### System information (version)

- OpenCV => : 4.2.0
- Operating System / Platform => : Linux Ubuntu 18.04
- CUDA => : 10.2

##### Detailed description

I am trying to compile (with cmake) a C++ object detection code that includes OpenCV and CUDA , however when I do that I receive an unsuitable CUDA version error. Here are the outputs of my nvidia compiler driver and nvcc version, which are different. 

![1](https://user-images.githubusercontent.com/42215081/72248506-65931e00-3608-11ea-942f-135fc0e1a53b.jpg)
![2](https://user-images.githubusercontent.com/42215081/72248649-b60a7b80-3608-11ea-84e4-0ecd6dc6a3bf.jpg)

And above is the error I get. Any suggestions on how to resolve this?

**Comment by alalek** [comment]
> /usr/local

How did you get OpenCV there?

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by efedoganay** [comment]
When I build with Cmake I change CMAKE_INSTALL_PREFIX = /usr/local/ for system-wide installation.
I am not using Raspberry Pi but step 5 shows it in this link below. https://www.learnopencv.com/install-opencv-4-on-raspberry-pi/

**Comment by efedoganay** [comment]
> > /usr/local
> 
> How did you get OpenCV there?
> 
> Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

When I build with Cmake I change CMAKE_INSTALL_PREFIX = /usr/local/ for system-wide installation.
I am not using Raspberry Pi but step 5 shows it in this link below. https://www.learnopencv.com/install-opencv-4-on-raspberry-pi/

**Comment by alalek** [comment]
Next question is "when". Which version of CUDA did you have in that time?

I mean you need to rebuild anything if you change/upgrade dependencies (like CUDA upgrade 9.2 => 10.1).
It is not OpenCV specific rule, this rule is applied for any software.

**Comment by alalek** [comment]
Looks like you still have CUDA 9.1 on your system.
Consult NVIDIA how to cleanup old versions: https://devtalk.nvidia.com/

OpenCV is able to found CUDA 10.2 (perhaps due custom search scripts or command line pararmeters), but CMake 3.10 (which was released before CUDA 10.2) can't do that.
Try to upgrade CMake or help to find CUDA 10.2 through `find_package(CUDA 10.2)`.

---

Don't post screenshots with text messages. It is ridiculous (similar issues can't be searched, it blocks proper quoting).

**Comment by efedoganay** [comment]
> Looks like you still have CUDA 9.1 on your system.
> Consult NVIDIA how to cleanup old versions: https://devtalk.nvidia.com/
> 
> OpenCV is able to found CUDA 10.2 (perhaps due custom search scripts or command line pararmeters), but CMake 3.10 (which was released before CUDA 10.2) can't do that.
> Try to upgrade CMake or help to find CUDA 10.2 through `find_package(CUDA 10.2)`.
> 
> Don't post screenshots with text messages. It is ridiculous (similar issues can't be searched, it blocks proper quoting).

Yes, OpenCV can find it because I specified CUDA_TOOLKIT_ROOT_DIR as /usr/local/cuda on CMake, which is the current location of CUDA 10.2.

**Comment by efedoganay** [comment]
The following command was able to solve the issue. Btw I have installed CMake 3.16.
`cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda`

**Comment by Hyrtsi** [comment]
If you have the same issue, a list of many solutions can be found [here](https://stackoverflow.com/questions/63737492/opencv-claims-to-find-wrong-cuda-version/75080353).

**Comment by Rurouni-z** [comment]
1. cd /usr/local
2. sudo rm -rf cuda
3. sudo ln -s /usr/local/cuda-xx.0 /usr/local/cuda

suit for symlink, maybe work

make sure you delete all files in cuda in step two
