### ISSUE TITLE
Phishing link in documentation

### ISSUE THREAD

**Issue by kevinhanna** [opencv/opencv#16347]
### System information (version)
- OpenCV => 3.4.1

##### Detailed description

Under additional details "An interesting interview regarding Face Detection by Adam Harvey" links to a site and redirects a few times currently ending with a page reporting "You're 1 of 100 selected by Google to win a phone" and tries to get CC info.

Found in markdown here:
https://github.com/opencv/opencv/blob/9ec3d76b21e7f9b15b8ffccfafe254b6113d0a75/doc/tutorials/objdetect/cascade_classifier/cascade_classifier.markdown

Which I assume will eventually fix it here?
https://docs.opencv.org/3.4.1/d7/d8b/tutorial_py_face_detection.html

Has link to http://www.makematics.com/research/viola-jones/ which reports browser has won a phone to get credit card info. 

##### Steps to reproduce

Go here, and don't provide them with your info.  Or do, it's really your choice :D 
http://www.makematics.com/research/viola-jones/

**Comment by alalek** [comment]
Mentioned file has link guarded by `webarchive`: https://web.archive.org/web/20171204220159/http://www.makematics.com/research/viola-jones/

Problem file version is [here](https://github.com/opencv/opencv/blame/3.4.1/doc/py_tutorials/py_objdetect/py_face_detection/py_face_detection.markdown) - its content is not available in actual 3.x/4.x versions.

**Comment by mshabunin** [comment]
All links have been replaced with web.archive.org wrapped ones. Archives repacked.
