### ISSUE TITLE
Python's initUndistortRectifyMap() produces different results than C++'s

### ISSUE THREAD

**Issue by MoBaT** [opencv/opencv#16341]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 16.04 64bit
- Compiler => GCC 5.4.0 20160609

##### Detailed description

When running initUndistortRectifyMap() in C++, it produces different results than in Python. My python result seems to be the correct one.

##### Steps to reproduce
Run this C++ code and compare the rm1 and rm2 with the python below

```cpp
#include <opencv2/opencv.hpp>
#include <iostream>

int main(int argc, char* argv[])
{
    float K_right_data[9] = {284.55701, 0, 412.48611,
                             0, 284.53479, 398.30951,
                             0, 0, 1};
    auto K_right = cv::Mat(3, 3, CV_32FC1, K_right_data);

    float D_right_data[4] = {-0.003575698, 0.03984385, -0.037921712, 0.0063790609};
    auto D_right = cv::Mat(1, 4, CV_32FC1, D_right_data);

    float R_right_data[9] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
    auto R_right = cv::Mat(3, 3, CV_32FC1, R_right_data);

    float P_right_data[12] = {150, 0, 261, -9.5907145, 0, 150, 149, 0, 0, 0, 1, 0};
    auto P_right = cv::Mat(3, 4, CV_32FC1, P_right_data);

    auto stereo_size = cv::Size(412, 300);

    cv::Mat rm1, rm2;
    cv::initUndistortRectifyMap(K_right, D_right, R_right, P_right, stereo_size, CV_32FC1, rm1, rm2);

    for (int i = 0; i < 100; i++)
    {
        std::cout << rm1.at<float>(i) << ",";
    }

    std::cout << std::endl;

    for (int i = 0; i < 100; i++)
    {
        std::cout << rm2.at<float>(i) << ",";
    }
}
```

```python
import cv2
import numpy as np
from math import tan, pi

K_right = np.array([[284.55701, 0, 412.48611],
                [0, 284.53479, 398.30951],
                [0, 0, 1]])

D_right = np.array([-0.003575698, 0.03984385, -0.037921712, 0.0063790609])
R_right = np.eye(3)
P_right = np.array([[150, 0, 261, -9.5907145],
                     [0, 150, 149, 0],
                     [0, 0, 1, 0]])
stereo_size = (412, 300)

m1type = cv2.CV_32FC1
(rm1, rm2) = cv2.fisheye.initUndistortRectifyMap(K_right, D_right, R_right, P_right, stereo_size, m1type)

print(rm1[:100])
print(rm2[:100])
```

**Comment by BadMachine** [comment]
@MoBaT  May i ask u why in first example you are using [cv::initUndistortRectifyMap](https://docs.opencv.org/4.1.2/d9/d0c/group__calib3d.html#ga7dfb72c9cf9780a347fbe3d1c47e5d5a)
but in second [cv2.fisheye.initUndistortRectifyMap](https://docs.opencv.org/4.1.2/db/d58/group__calib3d__fisheye.html#ga0d37b45f780b32f63ed19c21aa9fd333) ?

**Comment by MoBaT** [comment]
> @MoBaT May i ask u why in first example you are using [cv::initUndistortRectifyMap](https://docs.opencv.org/4.1.2/d9/d0c/group__calib3d.html#ga7dfb72c9cf9780a347fbe3d1c47e5d5a)
> but in second [cv2.fisheye.initUndistortRectifyMap](https://docs.opencv.org/4.1.2/db/d58/group__calib3d__fisheye.html#ga0d37b45f780b32f63ed19c21aa9fd333) ?

Because I'm a dumbass..

**Comment by BadMachine** [comment]
@MoBaT  *** happening)
