### ISSUE TITLE
Building iOS Framework on Mac OS Catalina (10.15.2 (19C57))

### ISSUE THREAD

**Issue by cmooreml** [opencv/opencv#16340]
##### System information (version)

- OpenCV => 3.4.7
- Operating System / Platform => Mac OS Catalina (10.15.2 (19C57))
- Compiler => Cmake

##### Detailed description

Cannot compile iOS framework on Mac OS Catalina - Readme: https://github.com/opencv/opencv/tree/master/platforms/ios

##### Steps to reproduce

Maybe this has to do with SIP (System Integrity Protection) Read only, when I try to create the Symlink I get:

```
cd / && sudo ln -s /Applications/Xcode.app/Contents/Developer Developer
ln: Developer: Read-only file system
```

```
python2 opencv/platforms/ios/build_framework.py ios
```

Results:
```
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 117, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 109, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 196, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 39, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by cmooreml** [comment]
May have to do with the iOS.cmake

```
# Setup iOS developer location
if (IPHONEOS)
    set (_CMAKE_IOS_DEVELOPER_ROOT "/Developer/Platforms/iPhoneOS.platform/Developer")
else ()
    if (IPHONESIMULATOR)
        set (_CMAKE_IOS_DEVELOPER_ROOT "/Developer/Platforms/iPhoneSimulator.platform/Developer")
    endif ()
endif ()```

**Comment by alalek** [comment]
> cd / && sudo ln -s /Applications/Xcode.app/Contents/Developer Developer

Ignore this step.
Could you add link on documentation with this step?

---

> ERROR: [Errno 2] No such file or directory

Ensure that CMake is properly installed (try `cmake --version`).

---

> platforms/ios/cmake/Modules/Platform/iOS.cmake

I believe we should cleanup that unused code.

**Comment by cmooreml** [comment]
It seems the instructions got updated on 3.4.7 branch had old instructions:

https://github.com/opencv/opencv/blob/master/doc/tutorials/introduction/ios_install/ios_install.markdown

I confirmed I had invalid cmake installation and it works now, thank you very much... easy solution.

**Comment by heenamansoori** [comment]
@cmooreml Can you please tell me where are the instructions to build ios framework on Mac OS Catalina?Where to get correct CMake installation?
