### ISSUE TITLE
Memory version of VideoWriter

### ISSUE THREAD

**Issue by pfeatherstone** [opencv/opencv#16359]
Could there be a raw memory version of VideoWriter, call it MemoryWriter, with a callback that gets called when the object is about to write the encoded stream. 
VideoWriter could simply use MemoryWriter with a callback set to a file writer. 
A raw memory version of VideoWriter would be very useful for forwarding encoded streams over a network for example.

**Comment by alalek** [comment]
OpenCV is not Media I/O library.
Consider using of FFmpeg or GStreamer frameworks for your task directly.

**Comment by pfeatherstone** [comment]
OpenCV has a videoio module so it seems to fit well.
Also OpenCV is not really a neural network library either but has a dnn module...
