### ISSUE TITLE
I want to build opencv on arm64,but there is an error,anyone konws how to solve it? 

### ISSUE THREAD

**Issue by luxianjun** [opencv/opencv#16365]
[root@localhost build]# pwd
/home/opencv-4.1.2/build
[root@localhost build]#
[root@localhost build]#
[root@localhost build]#
[root@localhost build]# cmake -D WITH_TBB=ON -D WITH_EIGEN=ON ..

-- Configuring done
-- Generating done
-- Build files have been written to: /home/opencv-4.1.2/build
[root@localhost build]#make -j 64
/tmp/ccbfOf64.s: Assembler messages:
/tmp/ccbfOf64.s:69: Error: register number out of range 0 to 15 at operand 3 -- `smull v2.4s,v0.4h,v21.h[0]'
/tmp/ccbfOf64.s:75: Error: register number out of range 0 to 15 at operand 3 -- `smlal v2.4s,v7.4h,v20.h[0]'
/tmp/ccbfOf64.s:78: Error: register number out of range 0 to 15 at operand 3 -- `smull v3.4s,v1.4h,v21.h[0]'
/tmp/ccbfOf64.s:84: Error: register number out of range 0 to 15 at operand 3 -- `smlal v3.4s,v16.4h,v20.h[0]'
/tmp/ccbfOf64.s:106: Error: register number out of range 0 to 15 at operand 3 -- `smlal v1.4s,v16.4h,v19.h[0]'
/tmp/ccbfOf64.s:109: Error: register number out of range 0 to 15 at operand 3 -- `smlal v0.4s,v7.4h,v19.h[0]'
/tmp/ccbfOf64.s:112: Error: register number out of range 0 to 15 at operand 3 -- `smlal v1.4s,v6.4h,v18.h[0]'
/tmp/ccbfOf64.s:115: Error: register number out of range 0 to 15 at operand 3 -- `smlal v0.4s,v5.4h,v18.h[0]'
/tmp/ccbfOf64.s:298: Error: register number out of range 0 to 15 at operand 3 -- `smull v3.4s,v1.4h,v21.h[0]'
/tmp/ccbfOf64.s:301: Error: register number out of range 0 to 15 at operand 3 -- `smull v2.4s,v0.4h,v21.h[0]'
/tmp/ccbfOf64.s:304: Error: register number out of range 0 to 15 at operand 3 -- `smlal v3.4s,v16.4h,v20.h[0]'
/tmp/ccbfOf64.s:307: Error: register number out of range 0 to 15 at operand 3 -- `smlal v2.4s,v7.4h,v20.h[0]'
/tmp/ccbfOf64.s:332: Error: register number out of range 0 to 15 at operand 3 -- `smlal v1.4s,v16.4h,v19.h[0]'
/tmp/ccbfOf64.s:335: Error: register number out of range 0 to 15 at operand 3 -- `smlal v0.4s,v7.4h,v19.h[0]'
/tmp/ccbfOf64.s:338: Error: register number out of range 0 to 15 at operand 3 -- `smlal v1.4s,v6.4h,v18.h[0]'
/tmp/ccbfOf64.s:341: Error: register number out of range 0 to 15 at operand 3 -- `smlal v0.4s,v5.4h,v18.h[0]'
[ 27%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/token_enc.c.o
[ 27%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfDeepTiledOutputPart.cpp.o
make[2]: *** [3rdparty/libwebp/CMakeFiles/libwebp.dir/src/dsp/yuv_neon.c.o] Error 1

The above is a compilation error,does anyone know how to solve it?  thanks!

**Comment by luxianjun** [comment]
upgrade gcc to version 7.3.0

**Comment by liuzhuni** [comment]
why this happend in gcc 4.8.5?   Add -march=armv8-a can solve it ?
