### ISSUE TITLE
 python freezes upon video webcam capture

### ISSUE THREAD

**Issue by mthomp89** [opencv/opencv#16386]
##### System information (version)
  - python==3.6.8
  - pandas==0.23.4
  - numpy==1.15.4
  - matplotlib==3.0.2
  - Keras==2.2.4
  - opencv==3.4.2
  - seaborn==0.9.0
  - scikit-learn==0.20.2
  - mkl-service==1.1.2
  - theano==1.0.3
  - pillow==5.4.1
  - ipykernel==5.1.0
  - jupyter
  - pip:
    - piexif==1.1.2
  - spyder==4.0.1
- mac OSX Catalina

##### Detailed description

Attempting to use the webcam for some object recognition. Inserted the cv2.waitKey(1) after reading a few forums. Running the following turns off the webcam and closes the window but python freezes causing a manual force quit. Please advise.

##### Steps to reproduce

`import cv2
import math
import utils
import face_detection

video_capture = cv2.VideoCapture(0)
counter = 5

while True:
    _, frame = video_capture.read()
    frame, face_box, face_coords = face_detection.detect_faces(frame)
    text = 'Image will be taken in {}..'.format(math.ceil(counter))
    if face_box is not None:
        frame = utils.write_on_frame(frame, text, face_coords[0], face_coords[1]-10)
    cv2.imshow('Video', frame)
    cv2.waitKey(1)
    counter -= 0.1
    if counter <= 0:
        cv2.imwrite('true_img.png', face_box)
        break

video_capture.release()
cv2.destroyAllWindows()
print("Onboarding Image Captured")`

**Comment by dkurt** [comment]
Please try to add `sys.exit(0)` at the end (and check that it is executed at least).

**Comment by BadMachine** [comment]
@mthomp89 also try this:
```
if cv2.waitKey(1)& 0xFF == ord('x') :
        break
```
press "x" to quit )
