### ISSUE TITLE
How do I add the opencv4.2 to the anaconda python environment ?

### ISSUE THREAD

**Issue by brian208579** [opencv/opencv#16384]
- OpenCV => 4.2
- Python => 3.7 ( Anaconda )
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

When I finish building opencv4.2 using Visual Studio 2019
I open spyder ( Anaconda Python IDE ) and import cv2
I got this error information : ModuleNotFoundError: No module named 'cv2'
How do I add the opencv4.2 to the anaconda python environment ?
Thanks a lot ...

**Comment by BadMachine** [comment]
@brian208579 
[Guide](https://docs.opencv.org/master/d5/de5/tutorial_py_setup_in_windows.html)

**Comment by alalek** [comment]
> Anaconda

I believe, a more convenient way for Anaconda is using its package manager.
OpenCV 4.2.0 is available [here](https://anaconda.org/conda-forge/opencv).

> Python

Any Python modules are loaded through `sys.path` (which may be adjusted by `PYTHONPATH` environment variable). Refer to Python documentation for details.

---

Also you make take a look on OpenCV's `setup_vars.cmd` script (works with "Release" builds only):
```
setup_vars.cmd python -c "import cv2 as cv; print(cv.__version__, cv.__file__)"
```

**Comment by BadMachine** [comment]
@alalek 
But if someone needs modules from contrib (e.g CUDA) it seems that this solution will not work, am I wrong?

**Comment by brian208579** [comment]
@alalek 
Thanks for your suggestion
But i need cuda and cudnn to execute the model
For example :
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
Anaconda doesn't seem to compile with cuda and cudnn
so i try to bulid with Visual Studio 2019
But i can't add the opencv4.2 to the anaconda python environment
This is my current problem ...

**Comment by brian208579** [comment]
@BadMachine 
I have the same idea as you
Using anaconda to install opencv can't work with cuda and cudnn

**Comment by BadMachine** [comment]
@brian208579 i have an idia about this problem. Check email

**Comment by dkurt** [comment]
Let's close it. Please issues for bug reports or feature requests that require specific actions. For usage questions please use StackOverflow or http://answers.opencv.org/
