### ISSUE TITLE
Opencv Build: Libs and Modules are not generating for imgcodec and highgui even though its enabled in build_js.py

### ISSUE THREAD

**Issue by vasanthhr** [opencv/opencv#16381]
I enabled "-DBUILD_opencv_imgcodecs=ON" and  "-DBUILD_opencv_highgui=ON" in build_js.py and then executed the build command as mentioned below, but /build/lib folder doesn't have **libopencv_imgcodecs.a** and  **libopencv_highgui.a** files. 
Under build/modules,  **opencv_imgcodecs.dir/src** and **opencv_highgui.dir/src** folders are having no files in it.

I observed one thing here: inside **opencv/platform/js/opencv_js.config.py**  has classes and methods for all modules except imgcodecs and highgui, even these modules not included in white_list, below is the white_list

`white_list = makeWhiteList([core, imgproc, objdetect, video, dnn, features2d, photo, aruco, calib3d])
`

I used this below command to build opencv:

```
#build command
cd opencv

python ./platforms/js/build_js.py --emscripten_dir=/home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten ../build

```

Please guide me how to include these modules along with all classes/methods in final build folder.

**Comment by alalek** [comment]
> JavaScript
> imgcodec and highgui

Please follow the existed OpenCV.JS tutorials.
Functionality of these modules is not going to be exposed due "platform" (browser) limitations.

> how to include these modules

Not supported.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
