### ISSUE TITLE
Can't create layer "bn_Conv1/FusedBatchNormV3" of type "FusedBatchNormV3"

### ISSUE THREAD

**Issue by dbacea** [opencv/opencv#16388]
### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2019
- TensorFlow 2.1.0

##### Detailed description

I have trained a MobileNetV2 using tf.keras. Then I exported the model as frozen graph *.pb file, and tried to load the network using cv::dnn::readNetFromTensorflow(). When I run the app the following error occurs: 
OpenCV(4.1.1) Error: Unspecified error (Can't create layer "bn_Conv1/FusedBatchNormV3" of type "FusedBatchNormV3") in cv::dnn::dnn4_v20190621::LayerData::getLayerInstance, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\dnn.cpp, line 525

When using TensorFlow version 1.14 this kind of error does not appear

##### Steps to reproduce

_net = cv::dnn::readNetFromTensorflow(pathToPbFile);

**Comment by alalek** [comment]
> 4.1.1

You are using an outdated version.
Try the latest OpenCV version first - OpenCV 4.2.0 or "master" branch.

**Comment by dkurt** [comment]
issue has been resolved by https://github.com/opencv/opencv/pull/15986
P.S.: we still need to rebase @Razor1O9's PR https://github.com/opencv/opencv/pull/16345
