### ISSUE TITLE
Dead kernel when using readNetFromTensorflow in jupyter

### ISSUE THREAD

**Issue by shahdghorsi** [opencv/opencv#16387]
**System information (version)**
OpenCV => 4.1.2.30 
Operating System / Platform => Windows 10 64 Bit
TensorFlow=>  2.0.0 

**Detailed description**
I have used TensorFlow object detection API on a dataset that I have created. I used the faster_rcnn_inception_v2 pre-trained model and tested it with TensorFlow successfully, using the script supplied down, I wanted to test it with openCv so, I needed to generate graph.pbtxt file and I did using the steps in [this script](https://github.com/opencv/opencv/issues/13050) 
I am running the opencv script in jupyter but I am getting the kernel dead when it reaches the function readNetFromTensorflow: 
cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'graph.pbtxt')

I believe it is related to the graph.pbtxt that I generated but I did not find a way to solve it.

**Comment by dkurt** [comment]
Please provide a reproducer.

**Comment by shahdghorsi** [comment]
> Please provide a reproducer.

I solved the problem it was related to my graph.pbtxt it turned out that I edited the wrong MaxPool2D/MaxPool named node by deleting the already found inputs and adding one input:
**node {
  name: "MaxPool2D/MaxPool"
  op: "MaxPool"
  input: "CropAndResize/CropAndResize"
  ...**

**Comment by dkurt** [comment]
@shahdghorsi, great, thanks! Can we close it?

**Comment by shahdghorsi** [comment]
> @shahdghorsi, great, thanks! Can we close it?

@dkurt I edited the replay above may you check it out before closing the issue?

**Comment by dkurt** [comment]
@shahdghorsi, please try newer version. We added `FusedBatchNormV3` here: https://github.com/opencv/opencv/pull/15986

**Comment by shahdghorsi** [comment]
> @shahdghorsi, please try newer version. We added `FusedBatchNormV3` here: #15986

I searched the OpenCV version that you recommended in the official OpenCV-python PyPI website but it is not found so I downloaded it[ from here](https://sourceforge.net/projects/opencvlibrary/) ran the exe but when I check what version I am using it still shows the old one, 
I am running python with anaconda I searched a lot to change the version from 4.1 to 4.2  with normal commands but all of the resources need many other installations like cmake and gocv is there a simple way to change the version? or am I supposed to go through all of the other preinstallations

**Comment by dkurt** [comment]
@shahdghorsi, please try regenerate `.pbtxt` using the script from master branch then open and replace all the `FusedBatchNormV3` to `FusedBatchNorm`.

**Comment by shahdghorsi** [comment]
> @shahdghorsi, please try to regenerate `.pbtxt` using the script from the master branch then open it and replace all the `FusedBatchNormV3` to `FusedBatchNorm`.

@dkurt I did use the script found in master, but it gives me the following error:

Traceback (most recent call last):
  File "graph_generator.py", line 299, in <module>
    createFasterRCNNGraph(args.input, args.config, args.output)
  File "graph_generator.py", line 52, in createFasterRCNNGraph
    writeTextGraph(modelPath, outputPath, ['num_detections', 'detection_scores', 'detection_boxes', 'detection_classes'])
NameError: name 'writeTextGraph' is not defined

**Comment by dkurt** [comment]
@shahdghorsi, put [tf_text_graph_common.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_common.py) nearby a script as well.

**Comment by shahdghorsi** [comment]
> @shahdghorsi, put [tf_text_graph_common.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_common.py) nearby a script as well.

I did and that solved the problem thank you a lot. I regenerated the graph.pbtxt and replaced all the
FusedBatchNormV3 to FusedBatchNorm.
But again when ı ran the inference I have got the following error:
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-04b423450a0e> in <module>
      8 cols = img.shape[1]
      9 cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
---> 10 cvOut = cvNet.forward()
     11 
     12 for detection in cvOut[0,0,:,:]:

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\layers\detection_output_layer.cpp:214: error: (-215:Assertion failed) (numPriors * _numLocClasses * 4) == total(inputs[0], 1) in function 'cv::dnn::DetectionOutputLayerImpl::getMemoryShapes'




I tried what you mentioned in [this comment](https://github.com/opencv/opencv/issues/10973#issuecomment-369624586) but it did not solve it

**Comment by dkurt** [comment]
@shahdghorsi, Can you share `.pb` and `.config` files? Cannot find the link in the issue.

**Comment by shahdghorsi** [comment]
@dkurt For sure, here are they: [.config](https://drive.google.com/open?id=18GHtId6dkvLT2Lh0H8fM7aaNOAOBn8HI)
[.pb](https://drive.google.com/open?id=124ys-y0hMWjnIRSDiS3x0albZWq242uY)

**Comment by shahdghorsi** [comment]
@dkurt when editing the graph.pbtxt am I supposed to do the [changes made here](https://github.com/opencv/opencv/issues/13050) as well besides changing the FuseBatchNormv3 to FuseBatchNorm

**Comment by shahdghorsi** [comment]
I eventually solved it, the configs file input and output paths are configured in my collab notebook, when I generated the graph ı ran it in my local machine using the config without changing the paths

**Comment by Jargon4072** [comment]
Hi,
I am trying to load an onnx model converted from mxnet (insightface's retinaface model: https://github.com/zheshipinyinMc/arcface_retinaface_mxnet2onnx/blob/master/Retinaface/mnet.25/onnx/mnet.25_deconv.onnx) through opencv4.2.0 for visual studio, in c++. I am getting the below error:

OpenCV: terminate handler is called! The last OpenCV error is:

```code
penCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.2.0) Error: Requested object was not found (Required argument "starts" not found into dictionary) in cv::dnn::dnn4_v20191202::Dict::get, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\include\opencv2/dnn/dnn.inl.hpp, line 349
```
The same model is working fine if I am trying to read it through python on windows.

Please help!
