### ISSUE TITLE
Transferring OpenCv versionfrom 4.1.0 to 4.2.0

### ISSUE THREAD

**Issue by shahdghorsi** [opencv/opencv#16395]
System information (version)
OpenCV => 4.1.2.30
Operating System / Platform => Windows 10 64 Bit

**Detailed description:**
I am using OpenCV installed with pip over python 3.7 and anaconda. I need to change the version of OpenCV to 4.2.0
I could not find a release in the official [opencv-python PyPI releases page](https://pypi.org/project/opencv-python/) so I download it from [here](https://sourceforge.net/projects/opencvlibrary/) how to make my Jupyter notebook use this version?
how to make sure that I correctly installed şt or if possible how to change versions using anaconda prompt.

**Comment by dkurt** [comment]
>  I could not find a release in the official opencv-python PyPI releases page so I download it from here how to make my Jupyter notebook use this version?

> **Unofficial** pre-built OpenCV packages for Python.

So please track https://github.com/skvark/opencv-python/issues/280
