### ISSUE TITLE
opencv mips1 : atomic<long long> not supported

### ISSUE THREAD

**Issue by pfeatherstone** [opencv/opencv#16398]
On MIPS1 version 1, atomic only supports 32 bit types.
So in cmake/checks/atomic_check.cpp and modules/core/include/opencv2/core/utils/allocator_stats.impl.hpp, atomic<long long> won't compile. Do we really need long long types for the statistics? If not, you will fix opencv for mips

**Comment by alalek** [comment]
Could you please attach dump of this command from mentioned architecture?
```
gcc -dM -E - < /dev/null
```

**Comment by pfeatherstone** [comment]
[dump.txt](https://github.com/opencv/opencv/files/4090630/dump.txt)

**Comment by pfeatherstone** [comment]
Also, MIPS1 VERSION 1 doesn't like using std::rint or std::round. If you omit std:: from both of these, it works fine. This has probably something to do with using gcc 4.8.5. Unfortunately, that is the highest gcc version I can find for this architecture.

**Comment by alalek** [comment]
Could you try this patch: https://github.com/alalek/opencv/commit/issue_16398 ?

**Comment by pfeatherstone** [comment]
It will still fail atomic_check.cpp which is done by cmake.

**Comment by alalek** [comment]
`cmake -DOPENCV_SKIP_LIBATOMIC_COMPILER_CHECK=ON ...`

**Comment by pfeatherstone** [comment]
okidoki. Otherwise i refactored atomic<long long> everywhere to atomic<long>. Yolo

**Comment by alalek** [comment]
It would be nice if your could validate this PR in your environment: #16786
