### ISSUE TITLE
the authority of OpenCV on trade issues of EAR

### ISSUE THREAD

**Issue by ilikelucifer** [opencv/opencv#16402]
We are concerned about the authority of OpenCV as recently arised trade issues between US and the rest of the world (especially China). We are looking forward to get your official answers for the questions below:
1. Is the OpenCV project subject to U.S. Export Administration Regulations (EAR) and classified under ECCN 0D521? Or such AI software is subject to EAR, but not classified under ECCN 0D521? 
2.  Is U..S. Bureau of Industry and Security license required for exporting this project to China？

**Comment by saskatchewancatch** [comment]
Interesting question.

OpenCV source is available in the "public domain" _so to speak_. These are exempt from EAR (and closely related ITAR). That is my understanding based on an ITAR course I took from Siemens AG and perusing reputable online sources on this matter.

I'm _not_ a maintainer btw, just throwing in my view.

**Comment by dkurt** [comment]
related question: https://answers.opencv.org/question/207637/export-control-classification-number-eccn-for-opencv/

@yssemaev, can you add some details here?

**Comment by yssemaev** [comment]
Hi,
Based on records in CC, OpenCV (open source) Export Commodity Control Number (ECCN) is EAR99.

**Comment by alalek** [comment]
@ilikelucifer In any case, you should contact with **own** lawyer about any legal questions. Answers from "Internet" may be non-accurate or outdated - don't rely on them.

**Comment by garybradski** [comment]
As Open source code, we are probably not under any export restrictions but this is not an "official answer" and comes with no Warranty. You must determine this yourself.

**Comment by ilikelucifer** [comment]
> @ilikelucifer In any case, you should contact with **own** lawyer about any legal questions. Answers from "Internet" may be non-accurate or outdated - don't rely on them.

thanks for your sincere advice!
