### ISSUE TITLE
ios framework : unsealed content at the root of the framework

### ISSUE THREAD

**Issue by dooxe** [opencv/opencv#16403]
Hello,

I have a problem when using the ios framework generated by the python script.

##### System information (version)
- OpenCV 4.2.0
- MacOS Mojave
- Compiler: clang 11.0.0
- XCode 11.0

##### Detailed description

When compiling `opencv2.framework` using the python script at `platforms/ios`, my XCode project won't build, and say: 'Unsealed content at the root of the framework'.

##### Steps to reproduce

- compile OpenCV for ios with the python script
- create an XCode project for ios
- link the compiled opencv2.framework with the project
- compile / laucnh the app

##### Clues about what's the problem (custom section)

After some investigations I noticed that (among all the 5 third-party frameworks I use), `opencv2.framework` is the only using a subfolder `Resources` to put the `Info.plist` in.

Replacing the line: 
https://github.com/opencv/opencv/blob/8b3042da63f4d0f112a1ec2199ebffc2894f567d/platforms/ios/build_framework.py#L259

with the follwing:
`resdir = framework_dir`

put the `Info.plist` at the root of the framework, and make all the things work properly when building in XCode.

**Comment by alalek** [comment]
Feel free to propose Pull Request (onto 3.4 branch, we will port fixes onto master later, through regular process)

**Comment by alalek** [comment]
See here "Framework Bundle Structure": https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

Current package structure looks like this (4.3.0):
```
$ tree -a --filelimit 5 opencv2.framework/
opencv2.framework/
├── Headers -> Versions/Current/Headers
├── opencv2 -> Versions/Current/opencv2
├── Resources -> Versions/Current/Resources
└── Versions
    ├── A
    │   ├── Headers [34 entries exceeds filelimit, not opening dir]
    │   ├── opencv2
    │   └── Resources
    │       └── Info.plist
    └── Current -> A
```

Considering proposal with moving of `Info.plist` as invalid.

---

Complete minimal reproducer is required for further investigation.
