### ISSUE TITLE
MathOpTest.MatricesAccuracyTest failure on aarch64 with Alpine Linux

### ISSUE THREAD

**Issue by russkel** [opencv/opencv#16419]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Alpine Linux Edge - aarch64
- Compiler => GCC 9.2.0

##### Detailed description

A small number of `gapi` tests fail when compiling on AARCH64:

```
2894 8: [----------] Global test environment tear-down
2895 8: [==========] 20872 tests from 349 test cases ran. (414883 ms total)
2896 8: [  PASSED  ] 20864 tests.
2897 8: [  FAILED  ] 8 tests, listed below:
2898 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/11, where GetParam() = (8UC3, 1920x1080, SAME_TYPE, 0xaab33936dd28, DIV, true, 1, true)
2899 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/27, where GetParam() = (8UC3, 1920x1080, 8UC1, 0xaab33936dd28, DIV, true, 1, true)
2900 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/59, where GetParam() = (8UC3, 1280x720, SAME_TYPE, 0xaab33936dd28, DIV, true, 1, true)
2901 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/75, where GetParam() = (8UC3, 1280x720, 8UC1, 0xaab33936dd28, DIV, true, 1, true)
2902 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/107, where GetParam() = (8UC3, 640x480, SAME_TYPE, 0xaab33936dd28, DIV, true, 1, true)
2903 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/123, where GetParam() = (8UC3, 640x480, 8UC1, 0xaab33936dd28, DIV, true, 1, true)
2904 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/155, where GetParam() = (8UC3, 128x128, SAME_TYPE, 0xaab33936dd28, DIV, true, 1, true)
2905 8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/171, where GetParam() = (8UC3, 128x128, 8UC1, 0xaab33936dd28, DIV, true, 1, true)
```

Full build and test log here:
[job.log](https://github.com/opencv/opencv/files/4107583/job.log)

##### Steps to reproduce

Build opencv on Alpine Linux on aarch64 and run the gapi test suite.

**Comment by alalek** [comment]
> WITH_LAPACK=OFF

Do you mean, that `WITH_LAPACK=ON` fixes this problem?


Messages are look like (from `job.log`):
```
8: ../modules/gapi/test/common/gapi_core_tests_inl.hpp:123: Failure
8: Expected: (countNonZeroPixels(cv::abs(out_mat_gapi - out_mat_ocv) > 0)) <= (0.01*out_mat_ocv.total()), actual: 40348 vs 20736
8: [  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/11, where GetParam() = (8UC3, 1920x1080, SAME_TYPE, 0xaab33936dd28, DIV, true, 1, true) (347 ms)
```

All failed tests are about "DIV" operation.
Result is still accurate enough (test tolerance 0.01 => 0.02 update is acceptable here).
But it is strange anyway, why results may differ.

**Comment by russkel** [comment]
> Do you mean, that WITH_LAPACK=ON fixes this problem?
Please disregard that, I double checked and the same issues occured WITH_LAPACK. I got mixed up with architecture build logs from CI.

**Comment by alalek** [comment]
Could you try this patch on your configuration: #16422 ?

**Comment by russkel** [comment]
> But it is strange anyway, why results may differ.

I had a quick google and found something called [Extended Precision](https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format). It could be related to that?

**Comment by russkel** [comment]
> Could you try this patch on your configuration: #16422 ?

Building now.. thanks for the quick patch. Will let you know the results.

**Comment by russkel** [comment]
Unfortunately nothing has changed. Same tests are failing. Patch applied fine as seen in the build log: 
[job2.log](https://github.com/opencv/opencv/files/4108724/job2.log)

**Comment by alalek** [comment]
Thank you for the check!

My mistake, tolerance is not updated due misused `#if` condition:
```
#if defined(__arm__) || defined(__aarch64__)
```

**Comment by russkel** [comment]
That did the trick! Thanks @alalek
