### ISSUE TITLE
OpenCV DNN on Raspberry Pi 4?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#16417]
Did anybody successfully run DNN on Raspberry Pi 4? I think I should enable OpenCL to run DNN on Raspberry Pi, right?

Please can anybody take a look at [https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit/topic/843560#comment-1951534](https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit/topic/843560#comment-1951534) .

Thank you 
Pei

**Comment by jrosebr1** [comment]
Hey @jiapei100, I assume you're referring to OpenVINO? If so, I have a tutorial on how to configure your RPi for OpenCV-OpenVINO over on the PyImageSearch blog:

https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/

That will enable you to use OpenCV's `dnn` module within the RPi using OpenVINO.

**Comment by jiapei100** [comment]
@jrosebr1 

Hi, Adrian. Thank you for your reply. I refer to your blog **pyimagesearch** often. I actually have built my own [rpi4-raspbian20200213-opencv4.3-openvino2020.1.023-ncsdk2.10.01.01.img](https://www.longervision.cc/iso/rpi4-raspbian20200213-opencv4.3-openvino2020.1.023-ncsdk2.10.01.01.img) already. However, the **ONLY** example code I failed to run is **object_detection_sample_ssd**, with the following ERROR message (on rpi4):

```console
➜  samples ./cpp/build/armv7l/Release/object_detection_sample_ssd -m face-detection-adas-0001.xml -d MYRIAD -i parents.jpg
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_releases/2020/1_d349c3ba4a2508be72f413fa4dee92cc0e4bc0e1
	Description ....... API
Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     parents.jpg
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... 37988
[ INFO ] Loading network files:
	face-detection-adas-0001.xml
	face-detection-adas-0001.bin
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the device
[ INFO ] Create infer request
[ WARNING ] Image is resized from (1280, 960) to (672, 384)
[ INFO ] Batch size is 1
[1]    9210 segmentation fault  ./cpp/build/armv7l/Release/object_detection_sample_ssd -m  -d MYRIAD -i
```

It seems something weird happened during run-time....

Cheers
Pei

**Comment by dkurt** [comment]
@jiapei100, please read the official documentation first: https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html. Most likely, `-DCMAKE_CXX_FLAGS="-march=armv7-a"` is missed.

**Comment by jiapei100** [comment]
@dkurt 

Thank you Dmitry. I actually have added `-DCMAKE_CXX_FLAGS="-march=armv7-a"`. 
The weird thing to me is: **object_detection_sample_ssd_c** works properly, but **object_detection_sample_ssd** does NOT...

My blog is at **[here](https://longervision.github.io/2020/04/12/AI/EdgeComputing/raspberry-pi-4-movidius-nerual-compute-stick-2-openvino/)**, and all **OTHER** tests run **OK**, **ONLY** **object_detection_sample_ssd** failed.
