### ISSUE TITLE
dis_opticalflow.cpp incorrect return value check for waitKey

### ISSUE THREAD

**Issue by gituuu** [opencv/opencv#16428]
https://github.com/opencv/opencv/blob/4.2.0/samples/cpp/dis_opticalflow.cpp

In OpenCV4, the return value of waitKey is now 255 in case of no key press. The code above expects it to be -1, hence

if ((ret = (char)waitKey(20)) > 0)

should be

if ((ret = (unsigned char)waitKey(20)) != 255)

This should also be compatible with previous versions of OpenCV.

**Comment by alalek** [comment]
> the return value of waitKey is now 255 in case of no key press

Please double check that.
If so, add dump of `getBuildInformation()` call.

**Comment by gituuu** [comment]
Sorry, I have now uninstalled that version of OpenCV.

Here:
https://github.com/opencv/opencv/blob/4.2.0/modules/highgui/src/window.cpp

In int cv::waitKey(int delay) you can see if the environment variable OPENCV_LEGACY_WAITKEY is not set, you always get this returned:

`code & 0xff`

So maybe the C++ program could check for that if it is doing things properly.

But at present it is incorrect behaviour unless this environment variable is set and there is no mention of that in the sample code.

**Comment by alalek** [comment]
Full return expression is:
```
int code = waitKeyEx(delay);
...
return (code != -1) ? (code & 0xff) : -1;
```

So `-1` timeout value should be preserved.

**Comment by gituuu** [comment]
Do we both agree that this code will result in the variable "code" to be set to 0?
```
    int code = waitKeyEx(delay);
#ifndef WINRT
    static int use_legacy = -1;
    if (use_legacy < 0)
    {
        use_legacy = getenv("OPENCV_LEGACY_WAITKEY") != NULL ? 1 : 0;
    }
    if (use_legacy > 0)
        return code;
#endif
```

So the return value will be:

`(code & 0xff)`

This will NOT be "-1" because as soon as you do bitwise operations, the compiler casts to unsigned values. Here is some test code for you to try:

```
#include <stdio.h>

int testfunc()
{
        int testvar = -10;

        return testvar & 0xff;
}

int main()
{
        printf("testvar is %d\n", testfunc());
        return 0;
}
```

**Comment by alalek** [comment]
No.
You should build/install and try some OpenCV sample.

**Comment by gituuu** [comment]
Sorry, I meant:
"Do we both agree that this code will result in the variable "use_legacy" to be set to 0?"

Please could you respond to my post with this correct text.

**Comment by gituuu** [comment]
And yes, I have built every single OpenCV sample and run about half of them.

Please fix the bug as it will help others in the future. Thanks.

**Comment by alalek** [comment]
Try "polar_transforms.cpp" example which has this [code](https://github.com/opencv/opencv/blob/4.2.0/samples/cpp/polar_transforms.cpp#L103-L104):
```
if( waitKey(10) >= 0 )
    break;
```

(if you don't have camera use "vtest.avi" parameter. You should not get "Could not initialize capturing..." message)

Normal app behavior is processing video until key pressed.
If your theory is correct then application should exit unconditionally (~10ms) after the first frame.

**Comment by gituuu** [comment]
> If your theory is correct then application should exit unconditionally (~10ms) after the first frame.

That's exactly what happens, and that is the reason for me filing this bug report.

**Comment by alalek** [comment]
So, please attach additional information: https://github.com/opencv/opencv/issues/16428#issuecomment-578256665

---

Also, please apply this patch for mentioned sample and dump here "timeout" values from the console.
```.diff
-if( waitKey(10) >= 0 )
-    break;

+int c = waitKeyEx(10);
+int c2 = waitKey(10);
+std::cout << "waitKeyEx() => " << c << "    waitKey() => " << c2 << std:endl;
+if (c >= 0 )
+    break;
```

---

Your test func should be corrected in this way:
```.diff
 int testfunc()
 {
     int code = -1;
-    return testvar & 0xff;
+    return (code != -1) ? (code & 0xff) : -1;
 }
```
