### ISSUE TITLE
Can't compile opencv 3.4.9 with gstreamer, error in test_gstreamer

### ISSUE THREAD

**Issue by kiodos** [opencv/opencv#16425]
##### System information (version)

- OpenCV => 3.4.9
- Operating System / Platform => OSX 10.13.6 (17G10021)
- Compiler => XCode 9.2 (clang llvm 900.0.39.2)
- CUDA => 9.1.128
- GStreamer => 1.16.2

##### Detailed description

I am trying to compile and install opencv 3.4.9 with CUDA support under osx 10.13.6 and GStreamer libraries (1.16.2) through CMake-gui (3.16) and the build fails to compile `test_gstreamer.cpp.o`

(note I can build and install opencv3.4.9 with CUDA support without gstreamer, but I want gstreamer)

##### Steps to reproduce

Configuring cmake with these options:
[CMakeVars.txt](https://github.com/opencv/opencv/files/4108599/CMakeVars.txt)

and I obtained this :

    [ 72%] Building CXX object modules/videoio/CMakeFiles/opencv_test_videoio.dir/test/test_gstreamer.cpp.o
    In file included from /Users/filippo/Downloads/opencv-3.4.9/modules/videoio/test/test_gstreamer.cpp:5:
    In file included from /Users/filippo/Downloads/opencv-3.4.9/modules/videoio/test/test_precomp.hpp:7:
    In file included from /Users/filippo/Downloads/opencv-3.4.9/modules/ts/include/opencv2/ts.hpp:125:
    /Users/filippo/Downloads/opencv-3.4.9/modules/ts/include/opencv2/ts/ts_gtest.h:1392:53: error: array initializer must be an initializer list
      or string literal
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3) : f0_(f0), f1_(f1), f2_(f2),
                                                    ^
    /Users/filippo/Downloads/opencv-3.4.9/modules/ts/include/opencv2/ts/ts_gtest.h:1755:10: note: in instantiation of member function
      'std::tr1::tuple<char [24], cv::Size_<int>, cv::Size_<int>, cv::ColorConversionCodes, void, void, void, void, void, void>::tuple'
      requested here
    return GTEST_4_TUPLE_(T)(f0, f1, f2, f3);
         ^
    /Users/filippo/Downloads/opencv-3.4.9/modules/ts/include/opencv2/ts/ts_gtest.h:1132:27: note: expanded from macro 'GTEST_4_TUPLE_'
    #define GTEST_4_TUPLE_(T) tuple<T##0, T##1, T##2, T##3, void, void, void, \
                          ^
    /Users/filippo/Downloads/opencv-3.4.9/modules/videoio/test/test_gstreamer.cpp:59:5: note: in instantiation of function template
    specialization 'std::tr1::make_tuple<char [24], cv::Size_<int>, cv::Size_<int>, cv::ColorConversionCodes>' requested here
    make_tuple("video/x-raw, format=BGR"  , Size(640, 480), Size(640, 480), COLOR_BGR2RGB),

**Comment by alalek** [comment]
> XCode 9.2

Unfortunately, we don't have builds (or environment setup) with mentioned configuration so we can't help with problem investigation.

Feel free to propose fix through GitHub Pull Requests.

**Comment by kindow** [comment]
same problem here，  @kiodos  have you found solution？

**Comment by yannpom** [comment]
Same error with:
OpenCV: 3.4.10
Gstreamer: 1.0
OS X: 10.14.4

**Comment by ebachard** [comment]
I confirm : someone broke 3.4.x version with gstreamer on Linux, probably since a long while.

I"m restarting from 3.4.0 to understand what has been "improved"  (say accidentaly ...) between 3.4.0 [building and working well]  and 3.4.11 [chaotic build, and nicely broken]  (3.4.10 now ... teached me this issue).

gstreamer seems to be -completely- broken on Linux too : can no longer connect a simple webcam, build 3.4.11 was a sport, while it should be simple, with most of the bugs fixed ... Maybe some dichotomy will save me some time.

@OpenCV guys : seriously, are every changes verified before integration ? Looks like someone modified the API in a major version. Basicaly a total non sense.

**Comment by neilyoung** [comment]
Same with OpenCV 3.4.11
