### ISSUE TITLE
VideoCapture (0) does not work in mac Catalina. The program crashed

### ISSUE THREAD

**Issue by robertodaza92** [opencv/opencv#16427]
VideoCapture (0) of opencv 4.2.0  in Java does not work for me. Show the following error:

```
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: can not spin main run loop from other thread, set OPENCV_AVFOUNDATION_SKIP_AUTH=1 to disable authorization request and perform it in your application.
OpenCV: camera failed to properly initialize!
```
**how i can setup OPENCV_AVFOUNDATION_SKIP_AUTH = 1 to disable the authorization request?**

**How can I fix the error?**

**Comment by ssrivastava123** [comment]
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: can not spin main run loop from other thread, set OPENCV_AVFOUNDATION_SKIP_AUTH=1 to disable authorization request and perform it in your application.
OpenCV: camera failed to properly initialize!

how to fix this error

**Comment by quantrpeter** [comment]
any hints?
