### ISSUE TITLE
Incorrect error message in cv2.rectangle

### ISSUE THREAD

**Issue by MrGrayCode** [opencv/opencv#16432]
`cv2.rectangle(img,(x,y),(x+w,y+h))` gives ```TypeError: function takes exactly 4 arguments (2 given)``` when actually the number of arguments given is 3
# Steps to reproduce
```
img = cv2.imread("path_to_img")
x,y,w,h = 10,10,10,10
cv2.rectangle(img,(x,y),(x+w,y+h))
cv2.imshow("Frame",img)
```
# Expected Result
```TypeError: function takes exactly 4 arguments (3 given)```

**Comment by berak** [comment]
```
>>> help(cv2.rectangle)
Help on built-in function rectangle:

rectangle(...)
    rectangle(img, pt1, pt2, color[, thickness[, lineType[, shift]]]) -> img
    .   @brief Draws a simple, thick, or filled up-right rectangle.
    ....
    .
    rectangle(img, rec, color[, thickness[, lineType[, shift]]]) -> img
    .   @overload
```

so, 2 overloaded functions, if it  cant resolve the 1st,  it will try the 2nd.

given, your 2nd argument is a `(x,y)` tuple, it cannot construct a `Rect` object (needing 4 values) from it.

(error is from `pyopencv_to(PyObject* obj, Rect2d& r, const ArgInfo& info)` , not directly from `cv2.rectangle`

**Comment by jshiwam** [comment]
Hello everyone I have a problem in understanding the python bindings. I read the python binding documentation on how  bindings are generated in opencv, I found out that the gen2.py file generates the wrapper functions for all the functions, classes etc. that are pyopencv_generated_*.h. These header files are included in cv2.cpp file where manual wrapper functions are placed. My question is if there is any argument type mismatch or less number of arguments are provided to a python function call then the PyArg_ParseTuple() under pyopencv_to() in the cv2.cpp file returns false which in turn triggers the exception that has occured. How/Where are these exceptions declared I am not able to figure it out. If anyone has a idea please help

**Comment by jshiwam** [comment]
I was trying to work on this bug. I have a problem in understanding the python bindings. I read the python binding documentation on how  bindings are generated in opencv, I found out that the gen2.py file generates the wrapper functions for all the functions, classes etc. that are pyopencv_generated_*.h. These header files are included in cv2.cpp file where manual wrapper functions are placed. My question is if there is any argument type mismatch or less number of arguments are provided to a python function call then the PyArg_ParseTuple() under pyopencv_to() in the cv2.cpp file returns false which in turn triggers the exception that has occured. How/Where are these exceptions declared I am not able to figure it out. Do I need to change those exception message or give a custom exception message?

**Comment by jshiwam** [comment]
> ```
> >>> help(cv2.rectangle)
> Help on built-in function rectangle:
> 
> rectangle(...)
>     rectangle(img, pt1, pt2, color[, thickness[, lineType[, shift]]]) -> img
>     .   @brief Draws a simple, thick, or filled up-right rectangle.
>     ....
>     .
>     rectangle(img, rec, color[, thickness[, lineType[, shift]]]) -> img
>     .   @overload
> ```
> 
> so, 2 overloaded functions, if it cant resolve the 1st, it will try the 2nd.
> 
> given, your 2nd argument is a `(x,y)` tuple, it cannot construct a `Rect` object (needing 4 values) from it.
> 
> (error is from `pyopencv_to(PyObject* obj, Rect& r, const ArgInfo& info)` , not directly from `cv2.rectangle`

I tried to give a custom error message from `pyopencv_to(PyObject* obj, Rect& r, const ArgInfo& info)` using PyError_SetString() or failmsg() which is defined in cv2.cpp file but that doesn't seem to work even after making the changes in cv2.cpp same error message is obtained

**Comment by janusheide** [comment]
I bumped into a wrong error message that could be related to this, when using keyword arguments;

```
----> 1 cv2.rectangle('fail', (0,0), (0,0), 1, thickness = 1)
TypeError: argument for rectangle() given by name ('thickness') and position (4)
```
Here the first argument img is wrong, not the thickness.

When using a positional argument I get the correct error message:
```
----> 1 cv2.rectangle('fail', (0,0), (0,0), 1, 1)
TypeError: Expected Ptr<cv::UMat> for argument 'img'
```

Also the following does not give an error, which I guess it should 
```
cv2.rectangle(None, (0,0), (0,0), 1, thickness = 1) 
```

And the following silly input yields a similarly silly result, instead of an error
```
cv2.rectangle(42, (0,0), (1,1), 13, thickness = 1)                                                                  
array([[13.],
       [13.],
       [ 0.],
       [ 0.]])

```

**Comment by polydefk** [comment]
cv2 expects a BGR format. Most likely you are trying to add a rectangle using an RGB format. Try to convert your image to BGR first. 

Something like that should do the trick: 
image_rgb = image_bgr[:, :, [2, 1, 0]]
image_rgb = image_bgr[:, :, ::-1]
