### ISSUE TITLE
CMake OpenCV error when compiling with CUDA

### ISSUE THREAD

**Issue by ss-github-code** [opencv/opencv#16449]
Hi,
I guess this is a different variant of a similar issue #16380 that was closed.

Environment: Win 10, CMake GUI, Visual Studio Community Edition 2019.

Could NOT find CUDNN (missing: CUDNN_LIBRARY CUDNN_INCLUDE_DIR) (found suitable version "7.5.0", minimum required is "7.5")

  NVIDIA CUDA:                   YES (ver 10.0, no extra features)
    NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
    NVIDIA PTX archs:

  cuDNN:                         NO

-----------------------------------------------------------------

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nppc_LIBRARY (ADVANCED)

**Comment by BadMachine** [comment]
@ss-github-code 
https://github.com/opencv/opencv/issues/16380#issuecomment-579761722

**Comment by ss-github-code** [comment]
Hi, 
I have copied cudnn inside cuda (as per your comment). I believe it is finding cudnn version 7.5.0 which is correct. I am not sure why it still says could not find CUDNN. Also, I am not able to generate OpenCV.sln file, so I cannot compile anything yet. Thank you in advance!

Could NOT find CUDNN (missing: CUDNN_LIBRARY CUDNN_INCLUDE_DIR) (**found suitable version** "7.5.0", minimum required is "7.5")

**Comment by solarflarefx** [comment]
@ss-github-code Were you able to fix your problem?  I am still getting this error, even though I have downloaded cudnn and placed the files in the proper directories.  The path is also included in my environment variables.

**Comment by YashasSamaga** [comment]
Did any of you fix this? Can you please share the locations of cudnn64.dll and cudnn.h?

**Comment by NatGr** [comment]
As found out by
https://github.com/opencv/opencv/issues/16380#issuecomment-638099242

downgrading to python 3.6 solved the issue for me (don't ask me why).
