### ISSUE TITLE
Make README.md file more interactive to the user

### ISSUE THREAD

**Issue by bosecodes** [opencv/opencv#16440]
The current README.md file just has a few links and I think a better documentation with better wording would make the code more welcoming to beginners who wish to contribute.

**Comment by dkurt** [comment]
Feel free to propose a PR.

**Comment by phoenixcool12** [comment]
Is anybody working on this issue? I would like to work on this issue if possible.

**Comment by alalek** [comment]
It would be nice to improve OpenCV documentation itself (you may start from "tutorials" section).
Duplication of documentation/wiki pages into README.md doesn't sound as a good idea.

**Comment by phoenixcool12** [comment]
I wanted to confirm once like should I organise contents of this link
https://docs.opencv.org/master/d9/df8/tutorial_root.html

**Comment by dkurt** [comment]
@phoenixcool12, not exactly this page but documentation itself. Try to follow some of the guides and if you confused about something or found typos or nor working examples - propose a pull request. No need to have our approvals for everything before you started :)
