### ISSUE TITLE
[DNN]Supporting string in `Constant` layer.

### ISSUE THREAD

**Issue by czgdp1807** [opencv/opencv#16456]
##### System information (version)

- OpenCV => branch `3.4` 
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++ 7.4.0

##### Detailed description

This issue aims at discussing and inviting suggestions for supporting `string` data type in `Constant` layer. Currently, `getMatFromTensor` only supports few data types from [this list](https://github.com/onnx/onnx/blob/master/docs/Operators.md#type-constraints-20).

Also, see https://github.com/opencv/opencv/issues/16370#issuecomment-578788207

##### Steps to reproduce

Code,
```cpp
#include<opencv2/dnn.hpp>
#include<vector>
#include<iostream>

int main()
{
    const std::string model = "model.onnx";
    cv::dnn::Net net = cv::dnn::readNet( model ); // error
}
```
`model.onnx` available [here](https://github.com/opencv/opencv/files/4074830/model.zip).

Apply the commits in https://github.com/opencv/opencv/pull/16424 before executing the above code. You will be able to see an error conveying that the tensor is empty and will be thrown by `getMatFromTensor`.

**Comment by alalek** [comment]
> string

Main question is how this should be processed.
Where is it really used?

OpenCV may use `CV_8U` for ASCII and `CV_32S` for Unicode on fixed-size strings.
Docs of ONNX "Constant" operator is [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant).

**Comment by dkurt** [comment]
Can you provide a reference to code which produces this .onnx model?

**Comment by czgdp1807** [comment]
> Main question is how this should be processed.
> Where is it really used?

I have mentioned about use case in [this comment](https://github.com/opencv/opencv/issues/16370#issuecomment-578788207).
Actually there can be cases when `Constant` layer is used to store label names. I have describe the scenario in the comment.



> Can you provide a reference to code which produces this .onnx model?

Actually the author of #16370 hasn't provided code but the visualisation of model(obtained using `dot` and `onnx` python package) is available at [this svg](https://drive.google.com/file/d/1TEjZF_SJY8uzC_C0FFXFBlYxvaNVqJhb/view?usp=sharing).

**Comment by czgdp1807** [comment]
> OpenCV may use `CV_8U` for ASCII and `CV_32S` for Unicode on fixed-size strings.

It looks like this is worth trying. I will see if things work out with these types. Thanks.

**Comment by czgdp1807** [comment]
Closing this as the purpose has been fulfilled.
