### ISSUE TITLE
GFFTDetector and goodFeaturesToTrack do not return intensity of the corner

### ISSUE THREAD

**Issue by WisdomPill** [opencv/opencv#16462]
##### System information (version)
- OpenCV => should be all of them, from at least 2.4
- Operating System / Platform => not relevant
- Compiler => not relevant

##### Detailed description

GFFTDetector and goodFeaturesToTrack do not fill the response field in keypoints returned from detect method.
Other detectors such as FastFeatureDetector fill that field.

##### Steps to reproduce

``` python
import cv2
capture = cv2.VideoCapture('video.mp4')

# detector = cv2.GFTTDetector_create(60, 0.01, 22, 5)
detector = cv2.FastFeatureDetector_create(threshold=90)

stop = False

while not stop:
    try:
        raw = capture.read()

        if raw is None:
            break

        raw = cv2.resize(raw, (480, 640))
        gray = cv2.cvtColor(raw, cv2.COLOR_BGR2GRAY)

        kp = detector.detect(gray, None)
        frame = cv2.drawKeypoints(raw, kp, None, color=(255, 255, 255))

        print("Total Keypoints with nonmaxSuppression: {}".format(len(kp)))

        cv2.imshow('fast_true', frame)

        key = cv2.waitKey(1) & 0xFF

        if key == ord('q'):
            stop = True

    except KeyboardInterrupt:
        break

cv2.destroyAllWindows()

```

using 

``` python
set(k.size for k in kp)
set(k.response for k in kp)
set(k.octave for k in kp)
set(k.angle for k in kp)
```

you can prove that.

As far as I know in my company we maintain a version of opencv to return the intensity of the corner in the method goodFeaturesToTrack, in case I can help to fix this.

**Comment by catree** [comment]
I do not see any issue that would prevent adding the feature response, except maybe to check that the response is coherent between the different implementations (OpenCV, OpenCL, IPP, ...) and between the different input image depth types (`CV_8U`, `CV_32F`, `CV_64F`).

Maybe also check that the default "unused" value for the `response` field is not used in some way as a hint to a feature descriptor method. For instance the default constructor:
```
KeyPoint (Point2f _pt, float _size, float _angle=-1, float _response=0, int _octave=0, int _class_id=-1)
```
So I think that if `angle==-1`, the feature descriptor method will compute the keypoint orientation, otherwise it should use the value.

---

If you have already the patch, you should propose a pull request.

**Comment by WisdomPill** [comment]
Yes I have the patch, in the next week or the one after I will make a PR about that.

As of now, I don't now about the angle, but for sure there's the value in the matrix that `cornerHarris` and `cornerMinEigenVal` gives back that should be returned, as a part of the function goodFeaturesToTrack and GFTTDetector.

If anybody knows where this information should go, just point it out, otherwise I have to do some digging in the code.
Furthermore I noticed that FastCornerDetector populates the size is always one unique value but the responses vary between lots of values.

So my guess is that the value of the point in the response of the two functions that retrieve corners in `goodFeaturesToTrack` should be in the response field of keypoints.

I took `FASTConerDetector` as an example because it is also the only one besides GFTT that is implemented in CUDA, in opencv_contrib, but I'm aware that there are more detectors in the standard opencv. And I already have an idea on who to do the same in opencv_contrib on the cuda version.

**Comment by WisdomPill** [comment]
Sorry for the huge delay, I started working with `goodFeaturesToTrack` to begin with, the unit test pass, I changed one test because `test_cornerEigenValsVecs` was incomplete and resulting in bad accuracy. I still have some problems with perf tests, while I have already adapted the OCL version.

I still need to have a look at the GFTT detector.

**Comment by WisdomPill** [comment]
closing since #19392 has been merged
