### ISSUE TITLE
Memory leak in cvtColor

### ISSUE THREAD

**Issue by Moldoteck** [opencv/opencv#16466]
##### System information (version)

- OpenCV = 4.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I think there is a memory leak in cvtColor function(heap is not fully deallocated). Please correct me if i am wrong

##### Steps to reproduce
If i run this code, i get ~+300KB in heap size and this memory is not freed at the end of execution:
```
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>
int main()
{
    cv::Mat imageObject = cv::imread(cv::samples::findFile("image.jpg"), cv::IMREAD_COLOR);
    cv::Mat output;
    cv::cvtColor(imageObject, output, cv::COLOR_BGR2GRAY); 
    return 0;
}
```
Inputs: 
image.jpg can be found here: https://i.stack.imgur.com/79vai.jpg

Expected heap size:
~300 KB - Initial;
~6550 KB - after imread
~9000 KB - after cvtColor (allocations for gray image)
~300 KB - end of program

Actual heap size evolution:
~300 KB - Initial;
~6550 KB - after imread
~9000 KB - after cvtColor (allocations for gray image)
~**680 KB** - end of program

**Comment by dkurt** [comment]
Which tools you have used to measure memory usage? Have you tried to run valgrind to test memory leaks?

**Comment by Moldoteck** [comment]
> 
> 
> Which tools you have used to measure memory usage? Have you tried to run valgrind to test memory leaks?
> 
> Where is "end of program" and how you got the values from there?

I used Visual Studio Debugging and Memory Usage Tab. I took snapshots of memory usage at every breakpoint. "end of program" is last '}', right after 'return 0;'

**Comment by mshabunin** [comment]
Try to use CRT memory leak detection: https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2019

**Comment by Moldoteck** [comment]
> 
> 
> Try to use CRT memory leak detection: https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2019

Well, i tried, but it shows several hundreds of entries. I can't understand what/where i should search memory leak(file names are not displayed probably because i use pre-compiled libraries)

**Comment by lodmacro** [comment]
저도 비슷한 증상을 겪고 있습니다.
cvtColor 함수를 사용할 경우 Page Fault가 계속 증가합니다.

OpenCV Version = 4.2.0
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2017

**Comment by mshabunin** [comment]
`cvtColor` can allocate internal static tables at first run, please try to add a loop into your sample and check if the leak is growing with each iteration.

**Comment by dyanikoglu** [comment]
Why this was closed? without any explanation? On debug builds, the code piece below causes huge amount of memory leak:

```
  while (true)
  {
    cv::Mat mat(1920, 1080, CV_8UC1);
    cv::Mat mat2(1920,1080, CV_8UC1);
    cv::cvtColor(mat, mat2, cv::COLOR_YUV420p2BGR);
  }
```
