### ISSUE TITLE
Segmentation fault (core dumped) after Relink issue while importing cv2 in python3

### ISSUE THREAD

**Issue by swiss-knight** [opencv/opencv#16468]
##### System information (version)
- OpenCV => build from master
- Operating System / Platform => Ubuntu 18.04 64 bits `5.3.0-26-generic x86_64 GNU/Linux`
- Compiler => gcc: `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)`
- Python => `Python 3.6.9 (default, Nov  7 2019, 10:44:02) `
- CMake => `cmake version 3.13.20181205-gf92e9`

##### Detailed description

I have a segmentation fault (core dumped) when trying to import `cv2` in `python3` (see hereafter).

I build `opencv` using the latest sources + the corresponding latest `opencv_contrib`; everything went fine. I used `cmake-gui` & `make` & `checkinstall`.

##### Steps to reproduce
```
$ python3    

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.    

>>> import cv2
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

( + is there a way to tell the install where to place the python lib because it uses the exact same directory than the one installed using `pip`: `/usr/local/lib/python3.6/dist-packages/cv2/` )

**Comment by alalek** [comment]
You do not need to call "make install" to try OpenCV (install only "packages" on Linux - google for "make install is bad").

0. Remove previously installed OpenCV outside of source/build directories (no exact recipe for that)
1. Just build OpenCV (`make opencv_python3` should be enough)
2. Try from build directory: `./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'`
3. If crashed, collect this log: `LD_DEBUG=files ./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'`
4. and stacktrace from gdb: `./setup_vars.sh gdb -ex r --args python -c 'import cv2; print(cv2.__file__)'`


---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by swiss-knight** [comment]
> You do not need to call "make install" to try OpenCV (install only "packages" on Linux - google for "make install is bad"). 

Actually, I always use `checkinstall` instead of `make install` which gives me the ability to remove the package using `dpkg -r` after if needed.     

Here are the results for each command (both for `python2` and `python3`, even If I do not use `python2` anymore now).

>     1. Remove previously installed OpenCV outside of source/build directories (no exact recipe for that)
```
$ cd /opt/opencv/build
$ sudo dpkg -r opencv
$ make clean
```

>     2. Just build OpenCV (`make opencv_python3` should be enough)
```
$ make opencv_python2
```
```
$ make opencv_python3
```

>     3. Try from build directory: `./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'`
Python2:
```
$ ./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'
Setting vars for OpenCV 4.2.0-dev
Append PYTHONPATH: /opt/opencv/build/python_loader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/opencv/build/python_loader/cv2/__init__.py", line 96, in <module>
    bootstrap()
  File "/opt/opencv/build/python_loader/cv2/__init__.py", line 86, in bootstrap
    import cv2
ImportError: libzzip.so.13: cannot open shared object file: No such file or directory

```

Python3:
```
$ ./setup_vars.sh python3 -c 'import cv2; print(cv2.__file__)'
Setting vars for OpenCV 4.2.0-dev
Append PYTHONPATH: /opt/opencv/build/python_loader
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

>     4. If crashed, collect this log: `LD_DEBUG=files ./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'`    
>
>     5. and stacktrace from gdb: `./setup_vars.sh gdb -ex r --args python -c 'import cv2; print(cv2.__file__)'`
> 
Python2:
```
$ LD_DEBUG=files ./setup_vars.sh python -c 'import cv2; print(cv2.__file__)'
(long output; I don't paste it here)
$ ./setup_vars.sh gdb -ex r --args python -c 'import cv2; print(cv2.__file__)'
Setting vars for OpenCV 4.2.0-dev
Append PYTHONPATH: /opt/opencv/build/python_loader
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
Starting program: /usr/bin/python -c import\ cv2\;\ print\(cv2.__file__\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3bcc700 (LWP 2733)]
[New Thread 0x7ffff13cb700 (LWP 2734)]
[New Thread 0x7ffff0bca700 (LWP 2736)]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/opencv/build/python_loader/cv2/__init__.py", line 96, in <module>
    bootstrap()
  File "/opt/opencv/build/python_loader/cv2/__init__.py", line 86, in bootstrap
    import cv2
ImportError: libzzip.so.13: cannot open shared object file: No such file or directory
[Thread 0x7ffff0bca700 (LWP 2736) exited]
[Thread 0x7ffff13cb700 (LWP 2734) exited]
[Thread 0x7ffff3bcc700 (LWP 2733) exited]
[Inferior 1 (process 2721) exited with code 01]
(gdb) 

```
Python3:
```
$ LD_DEBUG=files ./setup_vars.sh python3 -c 'import cv2; print(cv2.__file__)'
(long output; I don't paste it here)
$ ./setup_vars.sh gdb -ex r --args python3 -c 'import cv2; print(cv2.__file__)'
Setting vars for OpenCV 4.2.0-dev
Append PYTHONPATH: /opt/opencv/build/python_loader
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
Starting program: /usr/bin/python3 -c import\ cv2\;\ print\(cv2.__file__\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3844700 (LWP 2689)]
[New Thread 0x7ffff3043700 (LWP 2690)]
[New Thread 0x7fffee842700 (LWP 2691)]
/usr/bin/python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
/usr/bin/python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x0000000000002360 in ?? ()
(gdb) 
```

> We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

That's really nice btw.

**Comment by mshabunin** [comment]
>  is there a way to tell the install where to place the python lib 
Try to set `OPENCV_PYTHON_INSTALL_PATH` and/or `OPENCV_PYTHON3_INSTALL_PATH`: https://github.com/opencv/opencv/blob/0d456f9111c8c8adbe1ef990d8e133ce1870243f/modules/python/common.cmake#L157-L175

> (long output; I don't paste it here)
Using this output you can verify each .so being loaded. Make sure cv2.so and libopencv_*.so are consistent (from the same installation).

**Comment by alalek** [comment]
> I always use `checkinstall` instead of `make install`

Great :+1:

> long output; I don't paste it here

Please dump `stdout+stderr` into a `.txt` file (with python3) and attach it to issue's comment.
You may use `... >dump.txt 2>&1`

> gdb

Please run gdb's `bt` command to collect stacktrace after `SIGSEGV` signal.

---

> That's really nice btw.

Also there is a big OpenCV community who may try to help - but you still need to provide extra information for investigation of this problem.

**Comment by asmorkalov** [comment]
@swiss-knight friendly reminder.
