### ISSUE TITLE
HOW TO IMPORT CAMERA FROM URL TO OPENCV

### ISSUE THREAD

**Issue by aman-17** [opencv/opencv#16477]
I want to import a 'camera' from a URL to OpenCV. I can't use my mobile camera as WEB-CAMERA in OpenCV although I have established a connection from different applications like DroidCam where we can use mobile cameras as a web camera by going to a web address.

**Comment by BadMachine** [comment]
For your questions please use [https://answers.opencv.org](https://answers.opencv.org).
Looks like [here](https://answers.opencv.org/question/24154/how-to-using-opencv-api-get-web-video-stream/) answer to the question.
