### ISSUE TITLE
[ 82%] Built target opencv_java   (Error) raspi 3 B+

### ISSUE THREAD

**Issue by jorickjuh** [opencv/opencv#16470]
##### System information (version)
- OpenCV => 3.3
- Raspberry pi 3 B+ / raspbian
- Compiler => make

##### 

I am trying for days to install opencv correctly on version 3.3.0. but I can't get it to work. Mij latest error was:

[ 82%] Linking CXX shared library ../../lib/libopencv_java330.so
[ 82%] Built target opencv_java
make: *** [Makefile:163: all] Fout 2

Could not find much about it online. Hope you guys can help?
##### 

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D ENABLE_PRECOMPILED_HEADERS=OFF \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=OFF \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.0/modules \
-D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
-D BUILD_EXAMPLES=ON ..
    ```

**Comment by dkurt** [comment]
Please add build flags and logs. This part is almost useless
