### ISSUE TITLE
Error accessing outputs of `Slice layers in Caffe models

### ISSUE THREAD

**Issue by ccqu** [opencv/opencv#16489]
##### System information (version)

- OpenCV => 4.2.0-dev https://github.com/opencv/opencv/commit/5265db82c7ed0880117634cc723ed1bc91333b1b
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I have a Caffe model with [`Slice`](https://caffe.berkeleyvision.org/tutorial/layers/slice.html) layers. However, I'm not able to access the "implicit" outputs of the layer.

##### Steps to reproduce

Here is a MWE:

Model definition and weights: https://github.com/BVLC/caffe/tree/master/models/bvlc_reference_caffenet

By adding a Slice layer after the final `prob` layer:
```
layer {
  name: "split"
  type: "Slice"
  bottom: "prob"
  top: "out1"
  top: "out2"
  slice_param {
    axis: 1
    slice_point: 100
  }
}
```
the outputs `out1` / `out2` can be accessed in Caffe by
```
net.forward()['out1']
```

In OpenCV, though, I got the error:
`OpenCV(4.2.0-dev) Error: Unspecified error (Requested layer "out1" not found) in cv::dnn::dnn4_v20191202::Net::Impl::getLayerData, file C:\src\opencv\modules\dnn\src\dnn.cpp, line 1473`
with the following code:
```
net = cv::dnn::readNetFromCaffe("deploy.prototxt", "bvlc_alexnet.caffemodel");
net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
cv::Mat blob, img = cv::imread("examples/images/cat.jpg");
cv::dnn::blobFromImage(img, blob, 1, cv::Size(227, 227), cv::Scalar(104, 117, 123), false/*swapRB*/, false/*crop*/);
net.setInput(blob, "data");
cv::Mat detection = net.forward("out1");
```

Note:
* There is no problem executing `net.forward("prob")`.
* Both on CPU and CUDA backend.

I'm not sure if this is a bug or not. :thinking:

**Comment by dkurt** [comment]
As a workaround, 
```python
outs = net.forward(outputBlobs=[], outputName="split")
for out in outs:
    print(out.shape)
```

We use field "name" is used for layers names, not "top". 

For first output, 
```python
outs = net.forward("split")
for out in outs:
    print(out.shape)
```

**Comment by dkurt** [comment]
I think it might make sense to add this:

```cpp
CV_WRAP_AS(forwardAndRetrieve) void forward(OutputArrayOfArrays outputBlobs, const String& outputName = String());
```
to make it similar to
```cpp
        CV_WRAP_AS(forwardAndRetrieve) void forward(CV_OUT std::vector<std::vector<Mat> >& outputBlobs,
                                                    const std::vector<String>& outBlobNames);
```
