### ISSUE TITLE
Feature Request: Channel Max and Channel Idx Max

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv#16507]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC 5.4

##### Detailed description
For segmentation output (both image channel planes and interleaved) it would be great to have an optimized `void channelMax(cv::InputArray src, cv::OutputArray dst)` that returns the max value across channels and a  `void channelIdxMax(cv::InputArray src, cv::OutputArray dst)` that returns the max index across channels (or perhaps combine these into a single function).

##### Steps to reproduce
N/A

**Comment by dkurt** [comment]
Thanks! Looks like a duplicate to https://github.com/opencv/opencv/issues/10286
