### ISSUE TITLE
Bug in resize for 5 channels images

### ISSUE THREAD

**Issue by bonlime** [opencv/opencv#16501]
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Ubuntu 16.04
- Compiler => :grey_question:

##### Detailed description

I'm using python bindings for opencv and found a bug with resizing images with 5 channels. It works fine for any other number of channels. 
I've also checked previous versions and it works in 4.1.1. So the bug should be very recent

##### Steps to reproduce
```
import numpy as np
import cv2
arr = np.ones((1200, 1200, 5), dtype=np.uint8)
cv2.resize(arr, (512, 512))
```
for me it fails with 
`double free or corruption (!prev)`

**Comment by alalek** [comment]
Reproduced without Python:
```
    Mat src(Size(1200, 1200), CV_MAKETYPE(CV_8U, 5), Scalar::all(0));
    Mat dst;
    resize(src, dst, Size(512, 512));
```

**Comment by bonlime** [comment]
Thanks for fixing this so fast!
