### ISSUE TITLE
[stereo calibration] intrinsic parameters estimation

### ISSUE THREAD

**Issue by amaanda** [opencv/opencv#16515]
hi!

i am currently using opencv to calibrate a camera. once I have the calibration parameters cx and cy for the 2k resolution, am i able to calculate/estimate the cx and cy for a different resolution?

any help will be appreciated. thanks!

**Comment by alalek** [comment]
It depends on camera's sensor / firmware / drivers / SDK.
In general, for real cameras, answer is NO.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
