### ISSUE TITLE
CMake: VideoIo dll are not copied to custom config folders (e.g. RelWithDebInfo, MinSizeRel, etc.)

### ISSUE THREAD

**Issue by xenux** [opencv/opencv#16517]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019 / CMake

##### Detailed description

When building OpenCV solution for Visual Studio IDE using CMake, videoio dll are not copied to custom config folders such as RelWithDebInfo, MinSizeRel. 
As a result video reading silently fails when trying to execute for one of those configurations.

##### Steps to reproduce

Build a project with custom configs using OpenCV videoio ffmpeg. 

##### Cause 

Release and Debug folders are hardcoded for the dll copy in  [CMakeLists.txt](https://github.com/opencv/opencv/blob/master/modules/videoio/CMakeLists.txt) file:
```
if(MSVC_IDE)
    execute_process(
      COMMAND ${CMAKE_COMMAND} -E copy_if_different "${ffmpeg_path}" "${EXECUTABLE_OUTPUT_PATH}/Release/${ffmpeg_bare_name_ver}"
      COMMAND ${CMAKE_COMMAND} -E copy_if_different "${ffmpeg_path}" "${EXECUTABLE_OUTPUT_PATH}/Debug/${ffmpeg_bare_name_ver}")
```

**Comment by alalek** [comment]
> RelWithDebInfo, MinSizeRel

Not supported at all.

Use Debug/Release configurations only + `BUILD_WITH_DEBUG_INFO` if necessary.
