### ISSUE TITLE
ImportError: cannot import name 'Sketcher' from 'common'

### ISSUE THREAD

**Issue by HoLue** [opencv/opencv#16526]
##### System information (version)
- OpenCV =>4.1.1.26
- Operating System / Platform =>Windows 10
- Python => 3.7.4 64bit

##### Detailed description

After start I get the message:

`Traceback (most recent call last):
  File "watershed.py", line 30, in <module>
    from common import Sketcher
ImportError: cannot import name 'Sketcher' from 'common' (C:\Programme_Tools\Python\Python3_7_4_64bit\lib\site-packages\common\__init__.py)`

common package is: common-0.1.2

##### Steps to reproduce
Start from console:

`python watershed.py`

**Comment by HoLue** [comment]
Works in the original directory (samples\python), when I copy the fruits.jpg into it.

**Comment by nataliameira** [comment]
You did it?

**Comment by mattjbrundage** [comment]
Its importing a local script
