### ISSUE TITLE
How to avoid lib/opencv4/3rdparty/ libraries?

### ISSUE THREAD

**Issue by emmenlau** [opencv/opencv#16537]
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04, macOS 10.14, Windows 64 Bit
- Compiler => gcc-7.2, Apple Clang XCode 11.3, Visual Studio 2017, Visual Studio 2019

##### Detailed description

I've found that some of my non-OpenCV thirdparty libraries are copied to the installation directory into `lib/opencv4/3rdparty/`. This is breaking my build because I can no longer resolve duplicate linking. Some libraries from `lib/opencv4/3rdparty/` where copied from `lib/` and exist now twice under different names. When they get pulled into the build by different dependencies then I can not easily resolve the duplication.

What is the purpose of `lib/opencv4/3rdparty/`? And can it be disabled/avoided/removed?

**Comment by dkurt** [comment]
Please provide a reproducer - cmake flags and commands which were used to prepare install package.

**Comment by asmorkalov** [comment]
@emmenlau OpenCV relies on several projects for image and video decoding and acceleration. OpenCV has own instance of libjpeg, libpng, protobuf, etc and uses it in case if it cannot find system instance of the library. In case if you build OpenCV as static library the 3rd party libs are not linked inside of OpenCV and you need them for linkage of your application.
There are 2 ways to resolve your problem:
- Disable some 3rd party libs build during OpenCV build procedure with cmake flags like `-DWITH_JPEG=OFF` `-DWITH_PNG=OFF`. JPEG and PNG decoding libraries will disappear for 3rd party, but `cv::imread` cannot handle disabled formats.
- Use shared instance of 3rd party libraries. OpenCV can find JPEG, PNG, etc libraries in system with cmake `find_package` and use them instead of own version. Please check CMake output for 3rd party components, it prints path to used library and it's version.

**Comment by emmenlau** [comment]
Dear @asmorkalov , thanks, but I'm not talking about libraries that are compiled by OpenCV. The problem arises for binary thirdparty libraries.

To be more specific, before OpenCV is built, I have a number of binary IPP libraries in `TARGETDIR/lib/libipp*.a`. After I build OpenCV, I have copies of several of these libraries additionally in `TARGETDIR/lib/opencv4/3rdparty/`. When I build my own image processing library (that is based on IPP and OpenCV), it will link `TARGETDIR/lib/libipp*.a` for IPP and `TARGETDIR/lib/opencv4/3rdparty/libipp*.a` as an OpenCV dependency. This leads to errors.

I think this problem is specific to *binary* dependencies. In my humble opinion, OpenCV should not make copies of *binary* libraries that exist prior to building OpenCV. I think that because these libraries can be used from their original location, there is no benefit but some harm and confusion in making additional copies.

On the other hand (what you mention), its completely fine to create libraries from source and put them somewhere! This is a different topic and I fully agree with you there.

**Comment by emmenlau** [comment]
Dear @asmorkalov this is not a "question" about OpenCV, it is a problem in using OpenCV. Please remove the label "question (invalid tracker)".

The current behavior leads to duplicate symbol errors in downstream projects because OpenCV unnecessarily copies binary dependencies and puts them in the linker path. I know no other library that does this. And it leads to issues in compilation.

**Comment by dkurt** [comment]
@emmenlau, that's why we ask you for complete reproducer. If static libraries are inside **install** package - it's a bug. By default, it should not be there

**Comment by emmenlau** [comment]
Thanks @dkurt and @asmorkalov for your consideration! And sorry, I'm trying to prepare a more minimal example and cut away the unrelated options from cmake, because I specify all options manually. Here it is the full list, I will edit it to remove unrelated options:
```
cmake ../opencv-4.2.0 \
     -G"Ninja" \
     -DCMAKE_VERBOSE_MAKEFILE="ON" \
     -CMAKE_PREFIX_PATH="/data/Debug;/data/Debug/lib/cmake;/data/Tools;/data/Tools/lib/cmake" \
     -DCMAKE_INSTALL_PREFIX="/data/Debug" \
     -DCMAKE_INSTALL_LIBDIR="lib" \
     -DCMAKE_INSTALL_DATADIR="lib" \
     -DCMAKE_FIND_USE_PACKAGE_REGISTRY="OFF" \
     -DCMAKE_BUILD_TYPE="Debug" \
     -DCMAKE_POSITION_INDEPENDENT_CODE="ON" \
     -DCMAKE_INSTALL_RPATH="/data/Tools/lib:/data/Tools/lib64:/data/Debug/lib" \
     -DBUILD_SHARED_LIBS="OFF" \
     -DBUILD_WITH_DEBUG_INFO=ON \
     -DENABLE_OMIT_FRAME_POINTER=OFF \
     -DIPPROOT="/data/Tools/ipp" \
     -DOPENCV_INCLUDE_INSTALL_PATH="include" \
     -DOPENCV_CONFIG_INSTALL_PATH="share/opencv" \
     -DOPENCV_OTHER_INSTALL_PATH="share/opencv" \
     -DENABLE_PIC="ON" \
     -DBUILD_LIST="core,imgproc,imgcodecs,ml,video,videoio,features2d,flann,gapi,highgui" \
     -DOPENCV_ENABLE_NONFREE="OFF" \
     -DPROTOBUF_UPDATE_FILES="OFF" \
     -DUPDATE_PROTO_FILES="OFF" \
     -DWITH_MATLAB="OFF" \
     -DOPENCV_FORCE_3RDPARTY_BUILD="OFF" \
     -DBUILD_ZLIB="OFF" \
     -DBUILD_TIFF="OFF" \
     -DBUILD_JASPER="OFF" \
     -DBUILD_JPEG="OFF" \
     -DBUILD_PNG="OFF"\
     -DBUILD_OPENEXR="OFF" \
     -DBUILD_WEBP="OFF" \
     -DBUILD_TBB="OFF" \
     -DBUILD_IPP_IW="OFF"\
      -DBUILD_ITT="OFF" \
     -DWITH_1394="OFF" \
     -DWITH_AVFOUNDATION="OFF" \
     -DWITH_CAP_IOS="OFF" \
     -DWITH_CAROTENE="OFF" \
     -DWITH_CPUFEATURES="OFF" \
     -DWITH_VTK="OFF" \
     -DWITH_EIGEN="ON" \
     -DWITH_FFMPEG="OFF" \
     -DWITH_GSTREAMER="OFF" \
     -DWITH_GTK="OFF" \
     -DWITH_GTK_2_X="OFF" -DWITH_IPP="ON" -DWITH_HALIDE="OFF" -DWITH_VULKAN="OFF" -DWITH_INF_ENGINE="OFF" -DWITH_NGRAPH="OFF" -DWITH_JASPER="OFF" -DWITH_JPEG="ON" -DWITH_WEBP="OFF" -DWITH_OPENEXR="OFF" -DWITH_OPENGL="OFF" -DWITH_OPENVX="OFF" -DWITH_OPENNI="OFF" -DWITH_OPENNI2="OFF" -DWITH_PNG="ON" -DWITH_GDCM="OFF" -DWITH_PVAPI="OFF" -DWITH_ARAVIS="OFF" -DWITH_QT="OFF" -DWITH_WIN32UI="OFF" -DWITH_TBB="OFF" -DWITH_HPX="OFF" -DWITH_OPENMP="OFF" -DWITH_PTHREADS_PF="OFF" -DWITH_TIFF="ON" -DWITH_V4L="OFF" -DWITH_DSHOW="OFF" -DWITH_MSMF="OFF" -DWITH_MSMF_DXVA="OFF" -DWITH_XIMEA="OFF" -DWITH_XINE="OFF" -DWITH_CLP="OFF" -DWITH_OPENCL="OFF" -DWITH_OPENCL_SVM="OFF" -DWITH_OPENCLAMDFFT="OFF" -DWITH_OPENCLAMDBLAS="OFF" -DWITH_DIRECTX="OFF" -DWITH_OPENCL_D3D11_NV="OFF" -DWITH_LIBREALSENSE="OFF" -DWITH_VA="OFF" -DWITH_VA_INTEL="OFF" -DWITH_MFX="OFF" -DWITH_GDAL="OFF" -DWITH_GPHOTO2="OFF" -DWITH_LAPACK="OFF" -DWITH_ITT="OFF" -DWITH_PROTOBUF="OFF" -DWITH_IMGCODEC_HDR="OFF" -DWITH_IMGCODEC_SUNRASTER="OFF" -DWITH_IMGCODEC_PXM="OFF" -DWITH_IMGCODEC_PFM="OFF" -DWITH_QUIRC="OFF" -DWITH_ANDROID_MEDIANDK="OFF" -DBUILD_opencv_apps="OFF" -DBUILD_opencv_js="OFF" -DBUILD_ANDROID_PROJECTS="OFF" -DBUILD_ANDROID_EXAMPLES="OFF" -DBUILD_DOCS="OFF" -DBUILD_EXAMPLES="ON" -DBUILD_PACKAGE="OFF" -DBUILD_PERF_TESTS="OFF" -DBUILD_TESTS="ON" -DBUILD_WITH_STATIC_CRT="OFF" -DBUILD_WITH_DYNAMIC_IPP="OFF" -DBUILD_FAT_JAVA_LIB="OFF" -DBUILD_ANDROID_SERVICE="OFF" -DBUILD_CUDA_STUBS="OFF" -DBUILD_JAVA="OFF" -DINSTALL_CREATE_DISTRIB="OFF" -DINSTALL_C_EXAMPLES="OFF" -DINSTALL_PYTHON_EXAMPLES="OFF" -DINSTALL_ANDROID_EXAMPLES="OFF" -DINSTALL_TO_MANGLED_PATHS="OFF" -DINSTALL_TESTS="OFF" -DENABLE_CCACHE=ON -DENABLE_PRECOMPILED_HEADERS="OFF" -DENABLE_SOLUTION_FOLDERS="OFF" -DENABLE_PROFILING="OFF" -DENABLE_COVERAGE="OFF" -DOPENCV_ENABLE_MEMORY_SANITIZER="OFF" -DENABLE_POWERPC="OFF" -DENABLE_FAST_MATH="ON" -DENABLE_NEON="OFF" -DENABLE_VFPV3="OFF" -DENABLE_NOISY_WARNINGS="OFF" -DOPENCV_WARNINGS_ARE_ERRORS="OFF" -DANDROID_EXAMPLES_WITH_LIBS="OFF" -DENABLE_IMPL_COLLECTION="OFF" -DENABLE_INSTRUMENTATION="OFF" -DENABLE_GNU_STL_DEBUG="OFF" -DENABLE_BUILD_HARDENING="OFF" -DENABLE_LTO="OFF" -DENABLE_THIN_LTO="OFF" -DGENERATE_ABI_DESCRIPTOR="OFF" -DOPENCV_GENERATE_PKGCONFIG="OFF" -DCV_ENABLE_INTRINSICS="ON" -DCV_DISABLE_OPTIMIZATION="OFF" -DCV_TRACE="OFF" -DOPENCV_GENERATE_SETUPVARS="OFF" -DENABLE_CONFIG_VERIFICATION="ON" -DOPENCV_ENABLE_MEMALIGN="ON" -DENABLE_PYLINT="OFF" -DENABLE_FLAKE8="OFF"
```

**Comment by emmenlau** [comment]
Note that to reproduce this issue it may be required to work around issues #16536 and #16533 so that IPP libraries are detected.

**Comment by alalek** [comment]
> -DBUILD_SHARED_LIBS="OFF"

This is source of your problems.
Static build requires all used dependencies.

So you have two options:
- use shared build
- exclude dependencies

**Comment by emmenlau** [comment]
@alalek Thanks for your reply. Can you elaborate more, please? Every build requires all dependencies, otherwise the executable will not link? But that does not mean to create copies of dependencies?

**Comment by alalek** [comment]
See comment above from @asmorkalov :

> In case if you build OpenCV as static library the 3rd party libs are not linked inside of OpenCV and you need them for linkage of your application

**Comment by emmenlau** [comment]
@alalek I am not sure that this has something to do with my concern. Maybe the problem did not become very clear.

Obviously, when I want to use IPP features, I need to link IPP. But this is rather simple linker logic. It is not related to static or shared build. Furthermore, it is not related to making *copies* of libraries.

Also, what you say is not used anywhere else in practice, not even inside OpenCV. OpenCV does not make copies of all binary dependencies, or at least I can not see them. There are only copies of IPP and one or two others. But at least for me, there is no copy of `libtiff.a` or `libpng.a`. I also know no other major C++ library that would make copies of dependencies.

To further elaborate, if what you say is correct, then when I build higher-level libraries again static, they would need to make copies of OpenCV including the copies that OpenCV made. This works recursively up until the application. Copies of copies of copies, for every static library?

Dependencies are to be specified in the cmake package configuration, nothing more.

Can you please elaborate why additional copies of libraries would be helpful or needed?

**Comment by alalek** [comment]
You can try to remove these non-system libraries and try to build your application.
Be constructive and describe how it should work (from the beginning to the end - with launching of final user application).

> ninja -v install

`install` target is intended to prepare bundle which can be redistributed.
Currently policy is that its content should not depend/require something which is not classified as "system" libraries (like stuff from "/data/Tools").

You don't need `install` if you don't want to redistribute build content. Use build directory directly to build your apps and distribute your apps only.

> there is no copy of libtiff.a or libpng.a

Try `-DBUILD_TIFF=ON` and `-DBUILD_PNG=ON` to "fix" that.
Update your proposal with this assumption (required for Android SDK package).

**Comment by emmenlau** [comment]
Dear @alalek I appreciate your effort, thanks for taking the time. About your comments:

> You can try to remove these non-system libraries and try to build your application.

This breaks in another place. In my opinion (and similar to all C++ libraries I have ever used), OpenCV should specify its dependencies in the [cmake package config OpenCVModules.cmake](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html). If OpenCV copies the binaries, it will most likely also use the (wrong) path to these libraries instead of the "official" ones in my `TARGETDIR/ipp` directory.

> Be constructive and describe how it should work (from the beginning to the end - with launching of final user application).

Actually, just removing the copy step may be all that is needed. To be very specific, that most libraries do and what I would expect:
 1. OpenCV should add cmake code to detect its dependencies with their correct parameters in the OpenCV [cmake package config OpenCVModules.cmake](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html). This file already exist and it does that already! Everything is already in place. But its currently broken for IPP, see my issue #16536
 2. OpenCV should not create copies of binaries that it does not build itself. It should instead list dependencies from their *original* place.

> > ninja -v install
> 
> `install` target is intended to prepare bundle which can be redistributed.
> Currently policy is that its content should not depend/require something which is not classified as "system" libraries (like stuff from "/data/Tools").
> 
> You don't need `install` if you don't want to redistribute build content. Use build directory directly to build your apps and distribute your apps only.

I do not think this is the case. If it is the case, it would be contrary to all other C++ libraries I have ever seen or used. There are millions of libraries that can be configured, compiled and installed with the instructions `./configure (or cmake) && make && make install`. This is a very standard workflow. If this workflow does *not* create a valid installation in `TARGETDIR` that can be used to develop against, it would be very un-intuitive, to say the least.
How would this work in a CI system? I can not extract all libraries on top of each other. I need to install them into the same `TARGETDIR` that can be used as a dependency prefix.

> > there is no copy of libtiff.a or libpng.a
> 
> Try `-DBUILD_TIFF=ON` and `-DBUILD_PNG=ON` to "fix" that.

No, I think you completely misunderstand what I'm saying.

**Comment by alalek** [comment]
The main assumptions of described approach are:
- dependent packages have "config" file for CMake.
- "configuration" file can be properly versioned (to avoid mismatched versions and runtime crashes).

>  that copies are not required

You still need IPP's .a files to build final application.
How to you plan to specify them? Especially on correct version which were used to build OpenCV to ?

---

This issue report contradicts to #16536.

**Comment by emmenlau** [comment]
Dear @alalek , I'm very thankful for your help and time. But there seems to be a lot of confusion about software deployment. Is there possibly somebody available that has additional experience in this topic, and/or in cmake and/or pkgconfig?

If you want to further dive into this issue I may also be able to schedule a short call so we can go over some of the points?

Basically, what you say is not correct. I'll try to outline briefly:



> * dependent packages have "config" file for CMake.

That is not a core feature of the outlined approach. The core feature of the approach is that OpenCV (like any other library) wants and needs to inform consumers about the dependencies that OpenCV was built against. cmake offers options on how to do that. pkgconfig is another such mechanism (and one that is also in use in OpenCV, and that should also be adapted accordingly, if it is not already). There may be even more such mechanisms. But that is all beyond the scope of this issue.

The issue at hand is that OpenCV
  * *should* inform consumers about which dependencies are required, but
  * should *not* make copies of said dependencies

> * "configuration" file can be properly versioned (to avoid mismatched versions and runtime crashes).

This is not related. Obviously, users may only exchange dependent libraries within the scope of the API compatibility of said library. But this is completely out of the control and out of scope for OpenCV! A user could always exchange dependent libraries between linking steps, and there is just nothing OpenCV can do about it.

But I am slightly confused why you would see a responsibility on OpenCV side? It seems you are concerned about the following scenario, am I understanding correctly?
 1. A users installs IPP
 2. The user builds OpenCV against this IPP
 3. The user removes IPP and/or replaces it with a different version
 4. The user compiles an application against OpenCV and expects IPP to work correctly

This is an invalid workflow and every developer should know that. Even *if* you wanted this to be a valid workflow, how would you preserve the required IPP headers to match the binaries that OpenCV copies? How do you ensure that IPP is not already pulled in from another dependency in a different version? You open a pandora box!

> > that copies are not required
> 
> You still need IPP's .a files to build final application.

This is unrelated and an obvious fact. You seem to be ignorant to that. A user that wants to use IPP must link IPP. There is no difference if the build is static or shared.

> How to you plan to specify them? Especially on correct version which were used to build OpenCV to ?
> 
> This issue report contradicts to #16536.

No, absolutely not. Please review both issues again.

**Comment by emmenlau** [comment]
Can anyone help with this issue?

**Comment by mshabunin** [comment]
If your problem is `libipp*.a` files getting copied from standalone IPP installation to `<INSTALL>/lib/opencv4/3rdparty`, then I agree, this is an issue. All other libraries, e.g. `libade.a`, `libIlmImf.a`, ... are built with OpenCV from sources and can be considered a part of OpenCV installation - i.e. not an issue.

**Comment by emmenlau** [comment]
Dear @mshabunin , yes this is exactly my issue. See my original description:

> I've found that some of my non-OpenCV thirdparty libraries are copied to the installation directory into `lib/opencv4/3rdparty/`. This is breaking my build because I can no longer resolve duplicate linking.

Non-OpenCV-libraries should not be copied / duplicated. Could you please help?

**Comment by emmenlau** [comment]
Thanks guys!!!
