### ISSUE TITLE
Can not link against OpenCV due to missing IPP libs

### ISSUE THREAD

**Issue by emmenlau** [opencv/opencv#16536]
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04, macOS 10.14, Windows 64 Bit
- Compiler => gcc-7.2, Apple Clang XCode 11.3, Visual Studio 2017, Visual Studio 2019

##### Detailed description

I've built OpenCV with `-DBUILD_WITH_DYNAMIC_IPP="OFF"`. The build works fine, but I can not link executables against this OpenCV because I get missing library errors for IPP. The errors are slightly different on different platforms (Linux, Windows, Mac) but all agree that IPP libraries can not be found. For example on Ubuntu 18.04 I get `/usr/bin/ld: cannot find -lippcv`, ` /usr/bin/ld: cannot find -lippi`, ` /usr/bin/ld: cannot find -lippcc`, ... ` /usr/bin/ld: cannot find -lippcore`, on MSVC I get  `LINK : fatal error LNK1104: cannot open file 'ippcv.lib'` and on macOS XCode 11.3 I get ` ld: library not found for -lippcv`.

I've traced the issue and I'm under the impression that definitions are missing in `OpenCVConfig.cmake`. There are entries that specify for example the full path to some thirdparty libraries, but not for IPP. Then in `OpenCVModules.cmake` only the short names (without path) are used:
```
set_target_properties(opencv_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:dl>;\$<LINK_ONLY:m>;\$<LINK_ONLY:pthread>;\$<LINK_ONLY:rt>;\$<LINK_ONLY:ippiw>;\$<LINK_ONLY:ippcv>;\$<LINK_ONLY:ippi>;\$<LINK_ONLY:ippcc>;\$<LINK_ONLY:ipps>;\$<LINK_ONLY:ippvm>;\$<LINK_ONLY:ippcore>;\$<LINK_ONLY:Eigen3::Eigen>;/data/Debug/lib/libz.so"
)
```

**My assumption about what is wrong**
I'm under the impression that `OpenCVConfig.cmake` is missing entries like the following (that exists for `ippiw`) for the IPP libraries:
```
if(NOT TARGET ippiw)
  add_library(ippiw STATIC IMPORTED)
  set_target_properties(ippiw PROPERTIES
    IMPORTED_LINK_INTERFACE_LIBRARIES ""
    IMPORTED_LOCATION "${OpenCV_INSTALL_PATH}/lib/opencv4/3rdparty/libipp_iw.a"
  )
endif()
```

If I create similar entries for the IPP libraries, everything builds and works as expected.

##### Steps to reproduce

 1. Install Intel IPP libraries 2020.0 on the machine
 1. Build OpenCV against IPP 2020.0 with `-DBUILD_WITH_DYNAMIC_IPP="OFF"`
 2. Build a separate project with executable against OpenCV
 3. The build will fail with errors to link IPP libraries

**Comment by emmenlau** [comment]
To reproduce this issue it was for me required to fix issue #16533 first, so IPP libraries are detected. Please test for yourself because it may be different for your version of IPP...

**Comment by alalek** [comment]
Please provide complete steps with full list of CMake options.
At least your report didn't mention important option "BUILD_SHARED_LIBS=OFF".

> is missing entries like the following

Please check contents of `OpenCVModules.cmake` + `OpenCVModules-release.cmake` files.

In case of Windows these lines are expected:
```
# Create imported target ippiw
add_library(ippiw STATIC IMPORTED)
```
and
```
# Import target "ippiw" for configuration "Release"
set_property(TARGET ippiw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ippiw PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/x64/vc15/staticlib/ippiw.lib"
  )
```

But other targets from "standalone" IPP are missing: `ippcv;ippi;ippcc;ipps;ippvm;ippcore`

**Comment by emmenlau** [comment]
> Please provide complete steps with full list of CMake options.
> At least your report didn't mention important option "BUILD_SHARED_LIBS=OFF".

Sorry, I was not aware that this makes a difference. The options are the same as in https://github.com/opencv/opencv/issues/16537#issuecomment-584027837. Is that sufficient?

> > is missing entries like the following
> 
> Please check contents of `OpenCVModules.cmake` + `OpenCVModules-release.cmake` files.

I've checked all cmake files.

> In case of Windows these lines are expected:
> 
> ```
> # Create imported target ippiw
> add_library(ippiw STATIC IMPORTED)
> ```
> 
> and
> 
> ```
> # Import target "ippiw" for configuration "Release"
> set_property(TARGET ippiw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
> set_target_properties(ippiw PROPERTIES
>   IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
>   IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/x64/vc15/staticlib/ippiw.lib"
>   )
> ```
> 
> But other targets from "standalone" IPP are missing: `ippcv;ippi;ippcc;ipps;ippvm;ippcore`

Yes, correct, this is exactly the issue! To be 150% certain we mean the same thing I will phrase in my own words: The libraries are referenced with their short name from `OpenCVModules.cmake`, but the definitions how to resolve the short names are missing from `OpenCVConfig.cmake`. Is that what you observe too?

**Comment by emmenlau** [comment]
The same error may be true for other libraries like `ADE`. On macOS I get an error that no target exists for `libade`, similarly to the IPP libraries.

**Comment by emmenlau** [comment]
I see that this issue is labelled `feature` but it breaks the build of OpenCV consumers. Should it not be labelled `bug` instead?

**Comment by alalek** [comment]
Distribution through "install" target of "static builds" are not well supported / tested.

Use `-DBUILD_SHARED_LIBS=ON` or don't call "install".

**Comment by mshabunin** [comment]
Static builds' users should add all 3rdparty dependencies by themselves, OpenCV can only record library names, not locations, in the cmake package. Furthermore it is user's responsibility to link libraries in the correct order. In some cases setting environment variables like `LD_LIBRARY_PATH` can be enough to resolve linking problems, in complex cases it can be necessary to reproduce same detection process as in OpenCV build (if cmake targets have been used instead of library names).

**Comment by emmenlau** [comment]
Dear @mshabunin Can you elaborate why OpenCV should not use cmake best practices for this case? The current behavior is very uncommon, and goes against cmake standards. Also it puts a much higher burden on downstream projects than necessary. Is there a strong reason not to add the simple fixes for OpenCV?

The standard cmake practice is that when OpenCV links against a library X, then OpenCV's package configuration should resolve X (for example by means of `find_dependency(X)`, or by the means that OpenCV currently uses (see my first comment). If OpenCV does not add this resolution, then downstream projects can not link OpenCV.

**Comment by mshabunin** [comment]
Currently this can not be easily implemented because most of OpenCV dependencies do not have cmake package or have semi-working/non-standard package. Many dependencies require additional environment variables being set or special cmake options, thus even if OpenCV would add own search scripts for all 3rdparty libraries to the installation package, it still will not be usable without specific options and environment and can conflict with another libraries doing the same thing. So, the recommendation for static builds is: turn off as much dependencies as possible.

Integration level you are describing can be achieved by using cmake-based package managers like Conan or vcpkg.

**Comment by emmenlau** [comment]
Dear @mshabunin I understand your concern about maintaining find-scripts. But I think the current option, to require the user to have their own find scripts for libraries that OpenCV may or may not depend on, is the worst of the possible choices. Because of two reasons:
  * The user may not find the same set of dependencies (different threading options, different runtime options, ...)
  * All users will have to maintain their own find-scripts which is a large burden

In my opinion, if you do not want to provide find-scripts, then it would still be much better to use the absolute library path (that OpenCV already knows). This would be much better than not providing any path at all. OpenCV already does that for several of its dependencies, just not for all of them.

**Comment by mshabunin** [comment]
It is not always possible to write absolute paths, because not all linked targets are libraries, it can be cmake targets or static libraries with their own dependencies and compilation options. IPP is the easiest case, if you'd use static FFmpeg, you'd get 100+ dependent libraries in specific order.

This is package management problem and we can not solve it in single library.

**Comment by emmenlau** [comment]
Ok I think I understand. Its really quite unfortunate, but I can understand if a generic solution is not easy. So I will need to maintain my own patch... if I come up with something nice I'll post it here for other users.
