### ISSUE TITLE
IPP library directory not detected on MSVC, is it correct?

### ISSUE THREAD

**Issue by emmenlau** [opencv/opencv#16533]
##### System information (version)
- OpenCV => 4.2.0
- IPP 2020.0 for Windows
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017 x64, Visual Studio 2019 x64

##### Detailed description

When building OpenCV with `-DWITH_IPP=ON -DIPPROOT="C:/Tools/ipp"` I get a cmake error:
```
 -- found Intel IPP: 2020.0.0 [2020.0.0 Gold]
 -- at: C:/Tools/ipp
 -- Intel IPP library directory not found
```
I checked and the problem seems to be that https://github.com/opencv/opencv/blob/master/cmake/OpenCVFindIPP.cmake#L121 expects the IPP library directory at `${IPP_ROOT_DIR}/lib/intel64` but for me it is at `${IPP_ROOT_DIR}/lib/intel64_win`. I'm not sure if there is something broken with my IPP, but for validation I have the same path with Intel MKL and Intel DAAL. Could OpenCV add this path to the search list?

##### Steps to reproduce

 1. Install IPP 2020.0 into IPPROOT
 2. Build OpenCV with `-DWITH_IPP=ON -DIPPROOT="..."`
 3. See error in cmake configuration log

**Comment by alalek** [comment]
Can't reproduce:
```
  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/ipp
       linked:                   static
    Intel IPP IW:                sources (2019.0.0)
              at:                C:/projects/build_vc16/3rdparty/ippicv/ippicv_win/iw/
```

`${IPP_ROOT_DIR}/lib/intel64` has been created by IPP 2020.0.166 package.

**Comment by emmenlau** [comment]
Dear @alalek thanks a lot for investigating this issue.

My installation of IPP does not have the folder `${IPP_ROOT_DIR}/lib/intel64` but instead has folder `${IPP_ROOT_DIR}/lib/intel64_win`. But my installation is done by our local IT department, and was somehow performed in a scripted manner. I will check and see if they may have done extra steps to get the automatic scripting working.

Closing for further investigation on my side.
