### ISSUE TITLE
VideoWroter using CAP_INTEL_MFX doesn't seem to close the file properly. Can't get info of the file length, etc.

### ISSUE THREAD

**Issue by Benzez** [opencv/opencv#16545]
##### System information (version)
- OpenCV => 4.11 (openvino)
- Operating System / Platform => UBUNTU 16.04
- Compiler => 

##### Detailed description
VideoWroter using CAP_INTEL_MFX doesn't seem to close the file properly. Can't get info of the file length, etc.

##### Steps to reproduce
int compress = VideoWriter::fourcc('H', '2', '6', '5');
m_videoWriter VideoWriter(fileName + ".mp4", cv::CAP_INTEL_MFX, compress, Camera::recordFPS, Size(1920, 1080), true);

**Comment by mshabunin** [comment]
This backend does not support media containers, e.g. `mp4`. It can write raw video streams only: `h264`, `h265`, `mjpeg`, `mpeg2`; these streams do not contain meta information like format, length, etc.

See also: https://github.com/opencv/opencv/wiki/MediaSDK-encode-decode-backend
