### ISSUE TITLE
multiTracker.update() with pre-existing bounding boxes?

### ISSUE THREAD

**Issue by cortical-iv** [opencv/opencv#16547]
I am using OpenCV 4.1.1 on Python 3.7 in Windows 10 64 bit.

##### Detailed description
I have a good object detection network that is really accurate, and am working on *tracking* the objects now. Interestingly, in the documentation for `multiTracker.update()` it seems to be overloaded with a version that takes in a bounding box as an input (https://docs.opencv.org/3.4.9/d8/d77/classcv_1_1MultiTracker.html#ad4f8791aa78ca01a57c9135d1dc8a7ed). 

Unfortunately, when I try this I get an error (`TypeError: MultiTracker.update() takes at most 1 argument (2 given)`). Is there some other way to use the multitracker so that it can take advantage of bounding boxes that you already have from another application?

##### Steps to reproduce
    # Create MultiTracker object
    tracker = cv2.TrackerCSRT_create()
    multiTracker = cv2.MultiTracker_create()
    multiTracker.add(tracker, initial_frame, bboxes_first)
      
    #then update to next one (try using bboxes generated using object detector)
    success, boxes = multiTracker.update(second_frame, bboxes_second)
 
Output: 
`TypeError: MultiTracker.update() takes at most 1 argument (2 given)
`
As expected there is no error when I leave out the second argument.

**Comment by alalek** [comment]
> TypeError

This means that passed parameters are not valid.
Your snippet is not complete, so there is no way to reproduce the problem.

There is no [.update()](https://docs.opencv.org/3.4/d8/d77/classcv_1_1MultiTracker.html#ad4f8791aa78ca01a57c9135d1dc8a7ed) API which requires two inputs. Check headers:

> CV_WRAP bool update(InputArray image, CV_OUT std::vector<Rect2d> & boundingBox);

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

And finally, you should take a look on samples first: https://github.com/opencv/opencv_contrib/blob/4.2.0/modules/tracking/samples/multitracker.py

**Comment by L-Reichardt** [comment]
Im late and this topic is closed, but here goes if anyone finds this through google:

`success, boxes = multiTracker.update(second_frame, bboxes_second)`
should be
`success, bboxes_second = multiTracker.update(second_frame)`
