### ISSUE TITLE
libjasper-dev not getting installed in the virtual box installation of the ubuntu 18.04

### ISSUE THREAD

**Issue by vishwas1234567** [opencv/opencv#16550]
sudo apt-get install -y libjasper-dev
(base) vishwas@vishwas-VirtualBox:~$ sudo apt-get install -y libjasper-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libjasper-dev

**Comment by dkurt** [comment]
How this error relates to OpenCV?

Have you tried `apt-get update` before `apt-get install`?
