### ISSUE TITLE
Microsoft Windows Server 2012 R2 Datacenter  invoke  split  method  crash

### ISSUE THREAD

**Issue by kekekeke4** [opencv/opencv#16553]
I use split method:
    Mat img = imread("base.jpg");
    vector<Mat> img_channels;
    split(img, img_channels);
on win10 it's ok , but I run the app on  Microsoft Windows Server 2012 R2 Datacenter,it crashed. the attachment is app crashed 
![image](https://user-images.githubusercontent.com/8359389/74220418-896e8000-4cea-11ea-884e-fb7fd149251f.png)

**Comment by dkurt** [comment]
Please use https://answers.opencv.org/questions/ for usage questions.
