### ISSUE TITLE
imread() triggers an assert on this image

### ISSUE THREAD

**Issue by jklontz** [opencv/opencv#16551]
##### System information (version)
- OpenCV => master branch and 2.4 branch
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC 7.4.0

##### Detailed description

![This invalid image](https://user-images.githubusercontent.com/682795/74201902-346a3580-4c28-11ea-9843-742bb3545b34.jpg) crashes cv::imread on the validateInputImageSize() call [here](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L457). We feel that it would be preferable for this validation check to not trigger an assert and instead return a null result as other image decoding failures do. If fixed, we request that the patch is backported to the 2.4 branch.

##### Steps to reproduce

cv::imread("74201902-346a3580-4c28-11ea-9843-742bb3545b34.jpg");

**Comment by alalek** [comment]
Can't reproduce:
- OpenCV VCS version: 3.4.9-197-g1dd24eeec0
- OpenCV VCS version: 4.2.0-276-gaa2777ed61

With both builtin JPEG code (3rdparty directory through `BUILD_JPEG=ON`) or system library (Fedora 31).

```
Mat m = imread("74201902-346a3580-4c28-11ea-9843-742bb3545b34.jpg");
std::cout << m.size() << std::endl;
```

Output:

```
Premature end of JPEG file
[0 x 0]
```

Perhaps you should attach malformed content through `.zip` file to avoid any processing from GitHub.

---

> crashes cv::imread on the validateInputImageSize() call

It is a regular C++ exception.

---

> we request that the patch is backported to the 2.4 branch

2.4 is EOL. No more patches are accepted.

**Comment by jklontz** [comment]
Ah this is in indeed a regular C++ exception. I'm sorry for wasting your time here, I should have looked at the CV_Assert implementation more carefully.
