### ISSUE TITLE
Faster-RCNN Caffe Inference with OpenCV

### ISSUE THREAD

**Issue by enjoykcc456** [opencv/opencv#16568]
Hi, 

I have run into an error while trying to make inference with Faster-RCNN caffemodel using OpenCV (4.2.0) following this https://github.com/opencv/opencv/issues/10476.

The following is the code i use:
```
import cv2
import numpy as np

MODEL_PATH = '3c773411-a963-41b1-ae24-707545e9f601.caffemodel'
PROTOTXT_PATH = 'test.prototxt'
IMAGE_PATH = '3c773411-a963-41b1-ae24-707545e9f601.jpg'

kInpWidth = 800
kInpHeight = 600
net = cv2.dnn.readNetFromCaffe(PROTOTXT_PATH, MODEL_PATH)

img = cv2.imread(IMAGE_PATH)
img = cv2.resize(img, (kInpWidth, kInpHeight))
blob = cv2.dnn.blobFromImage(img, 1.0, None, (102.9801, 115.9465, 122.7717), False, False)
print("Input:", blob.shape, blob.dtype)

imInfo = np.array([600, 800, 1.6]).reshape([1,3]).astype('float32')
print("imInfo:", imInfo.shape, imInfo.dtype)

net.setInput(blob,"data")
net.setInput(imInfo, "im_info")

detections = net.forward()
```
The prototxt of the model:
```
name: "VGG_ILSVRC_16_layers"
input: "data"
input: "im_info"
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}
input_shape {
  dim: 1
  dim: 3
}
layer {
  name: "conv1_1"
  type: "Convolution"
  bottom: "data"
  top: "conv1_1"
  param {
    lr_mult: 0.0
    decay_mult: 0.0
  }
  param {
    lr_mult: 0.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
  }
}
And more...
```
The error that i ran into:
`detections = net.forward()
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "proposal" of type "Python" in function 'getLayerInstance'`

May i know what is the problem and how can i make it works?
Thanks in advance

**Comment by dkurt** [comment]
Check how Python later replaced here: https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/faster_rcnn_vgg16.prototxt

**Comment by enjoykcc456** [comment]
Hi @dkurt, thanks for the reply. 
May i know what you mean by check the python layer. I am quite new in this field. Greatly appreciate if you could describe more on this. 
Does it mean that the model i trained by my own is not compatible with OpenCV dnn? 
Is there any way that i can do to make it works? 
Thank you

**Comment by dkurt** [comment]
It's compatible but you need to apply this change:

https://github.com/opencv/opencv_extra/blob/04efd6f5b4160613dfb78b1cc2e4d3bd61c272f2/testdata/dnn/faster_rcnn_vgg16.prototxt#L329-L357

**Comment by enjoykcc456** [comment]
Hi @dkurt , thanks a lot for the info, after applying the changes, it can now be forwarded into the net. 

When i try the script above with the model VGG16_faster_rcnn_final.caffemodel and faster_rcnn_vgg16.prototxt, the output of the detections is an array of (1, 1, 100, 7) where every detection (100 rows) is a vector (with 7 colums ) [id, classId, confidence, left, top, right, bottom].

However, when i try with my model and prototxt, the output of detections is an array of (300, 1) all the same value. Would like to ask which portion should i modify to get the detections with bounding boxes result?

The following is the prototxt of the model i trained:
[test.prototxt.txt](https://github.com/opencv/opencv/files/4202887/test.prototxt.txt)

Thank you

**Comment by dkurt** [comment]
Try to add postprocessing from the same file: https://github.com/opencv/opencv_extra/blob/04efd6f5b4160613dfb78b1cc2e4d3bd61c272f2/testdata/dnn/faster_rcnn_vgg16.prototxt#L428-L520

**Comment by enjoykcc456** [comment]
Hi @dkurt ,

After i append the postprocessing to the prototxt, the following error occurs:
```
Traceback (most recent call last):
  File "/home/kong.cheechung/Documents/opencv-test/opencv.py", line 49, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp:220: error: (-215:Assertion failed) (numPriors * _numLocClasses * 4) == total(inputs[0], 1) in function 'getMemoryShapes'
```
The prototxt after appending the postprocessing:
[test.prototxt.txt](https://github.com/opencv/opencv/files/4203138/test.prototxt.txt)

**This custom Faster-RCNN model is trained on data set with only one type of object using IBM PowerAI Vision training tool.

**Comment by dkurt** [comment]
Check number os classes please at DetectionOutput layer. Probably it is different for your dataset.

**Comment by enjoykcc456** [comment]
Hi @dkurt,

After changing the num_classes, the inference works well now!
Thanksss a lot for your help! Really appreciate it!

**Comment by dkurt** [comment]
Great, thanks! I believe our investigation will be also useful for others who have trained Faster R-CNN.

You may also try to run it with IE backend to improve efficiency: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend

Can we close issue?

**Comment by enjoykcc456** [comment]
Hi @dkurt ,

Will test the IE backend out.
Yea sure, we can close this issue now.

Once again. Thanks for the help!

**Comment by enjoykcc456** [comment]
Hi @dkurt, 

Would like to know why is the time taken to forward the blob to the net and get the detection results for Faster-RCNN is so long (around 5 to 7 seconds per forward) as compared to SSD (only around 0.05s per forward).

Is there any settings that i can tune to make it faster? Because 5 to 7 seconds per forward is quite long. 

Thank you

**Comment by dkurt** [comment]
@enjoykcc456 , There are several points:
1) Do warmup run - it takes to most time to initialize network. So you need to measure in this way (Python):
```python
import time

net.forward()
n = 10
start = time.time()
for i in range(n):
    net.forward()
print(1000 * (time.time() - start) / n), 'ms')
```
2. Need to check that all the layers are executed with IE backend with no fallbacks to OpenCV implementation. I will check it (we recently [updated Mask R-CNN](https://github.com/opencv/opencv/pull/16595) which set of layers close to Faster R-CNN)

**Comment by enjoykcc456** [comment]
Hi @dkurt , 

I tested with the following code:

```
import time
import cv2
import numpy as np

PROTOTXT = '/home/kong.cheechung/Documents/opencv_gpu_docker/opencv-dnn-gpu/fire.prototxt'
MODEL = '/home/kong.cheechung/Documents/opencv_gpu_docker/opencv-dnn-gpu/fire_faster-rcnn.caffemodel'
net = cv2.dnn.readNetFromCaffe(PROTOTXT, MODEL)

kInpWidth = 800
kInpHeight = 600
n = 10

img_path = '1.jpg'
frame = cv2.imread(img_path)

# resize the frame, grab the frame dimensions, and convert it to
# a blob
frame = cv2.resize(frame, (kInpWidth, kInpHeight))
(h, w) = frame.shape[:2]
blob = cv2.dnn.blobFromImage(frame, 1.0, None, (102.9801, 115.9465, 122.7717), False, False)
imInfo = np.array([600, 800, 1.6]).reshape([1, 3]).astype('float32')

# pass the blob through the network and obtain the detections and
# predictions
net.setInput(blob, "data")
net.setInput(imInfo, "im_info")

detections = net.forward()  # warmup

start_forward_time = time.time()
for i in range(n):
    detections = net.forward()

print(f'Forward time taken: { ((time.time() - start_forward_time)/n) * 1000 } ms\n')
```
The average time taken is `Forward time taken: 8303.21741104126 ms`

I havent try out the IE backend yet. But with similar settings. SSD forward is taking a shorter time of only ~ 0.05s.

**Comment by dkurt** [comment]
@enjoykcc456, The model is VGG16 based - it's a family of the most time consuming models for object detection. If you want to keep high accuracy but achieve better efficiency - take a look to lighter backbones. Or you may try to forward lower input resolution (i.e. 400x300)

Check https://dkurt.github.io/dl_tradeoff/. For Image classification there are both more accurate and faster topologies

![Screenshot from 2020-02-17 12-02-45](https://user-images.githubusercontent.com/25801568/74638699-7857c000-517d-11ea-9be9-f85360b834e8.png)

For object detection there is no VGG based topology on diagram but you may see others.

![Screenshot from 2020-02-17 12-06-37](https://user-images.githubusercontent.com/25801568/74638957-fcaa4300-517d-11ea-9d04-dacac5bce3b5.png)

**Comment by enjoykcc456** [comment]
Hi @dkurt,

Okay. Understand what you are trying to say.
I have tested again with input size of 400x300. 
The average is lowered around `Forward time taken: 6204.8027992248535 ms`.
I will try it out with DNN module with CUDA backend to see if it will be better.

Thanks for your info and have a nice day.

**Comment by enjoykcc456** [comment]
Hi @dkurt ,

When i try to run the same inference code for the faster-rcnn caffemodel but with the backend set to cuda:
```
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
```

I got the following error:
```
Traceback (most recent call last):
  File "faster_rcnn_object_detection.py", line 110, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /opencv_gpu_files/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/inner_product.hpp:34: error: (-215:Assertion failed) get_effective_rank(weightsTensor) == 2 in function 'InnerProductOp'
```

However, I was able to run the inference code for MobileNet SSD caffemodel with backend set to cuda in the same environment without any error.

Would like to know is it because faster-rcnn inference is not supported yet in dnn cuda?

Thank you.

**Comment by dkurt** [comment]
@enjoykcc456, Please provide a minimal reproducer which includes `net.setInput`.

/cc @YashasSamaga

**Comment by YashasSamaga** [comment]
@enjoykcc456 It's a bug.

The assertion ensures that the weights matrix is effectively a 2D matrix. But if the number of outputs is one (as in the case of `attribute_score` layer in your model), the weights matrix effectively becomes a vector (which has a rank of one). The assertion should have been `<= 2` instead of `== 2`.

Change the line in `/opencv_gpu_files/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/inner_product.hpp` at line 34 from `CV_Assert(get_effective_rank(weightsTensor) <= 2);` to `CV_Assert(get_effective_rank(weightsTensor) <= 2);`

If that's difficult, you can try using this branch (master branch with a fix for the bug):
https://github.com/YashasSamaga/opencv/tree/cuda4dnn-hotfix-i16568

**Comment by enjoykcc456** [comment]
Hi @dkurt @YashasSamaga ,

Thanks for info. 
After making the changes and rebuild. I am able to get rid of the error.
However, i have got another error:

```
Traceback (most recent call last):
  File "faster_rcnn_object_detection.py", line 110, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /opencv_gpu_files/opencv/modules/dnn/src/op_cuda.hpp:142: error: (-215:Assertion failed) destMat.total() >= srcTensor.size() in function 'copyTensorToMat<float>'
```

Based on the assertion, i assume my model srcTensor is larger than the destMat. 
How should i change the line and rebuild? Or should i just remove it? 

Thank you.

**Comment by YashasSamaga** [comment]
@enjoykcc456 please upload the weights and the config file

**Comment by enjoykcc456** [comment]
Hi @YashasSamaga , 

Please find the weights and config file in the following link:
https://drive.google.com/uc?id=1loXafiOcMboKXOiX7GlQ6Q51IPjGyRGK&export=download

Thanks

**Comment by enjoykcc456** [comment]
Hi @YashasSamaga , are you able do the net.forward() with the weight and config file?
Thanks

**Comment by YashasSamaga** [comment]
@enjoykcc456 No, exceptions were thrown. I'll look into this on Sunday. Sorry for the dealy.

**Comment by YashasSamaga** [comment]
@enjoykcc456 can you please try the patch proposed in #16835? I have used your python script. It's working locally. But the error I faced when I tried running was different from what you had.
