### ISSUE TITLE
Input layer not found: dense2/bias in function 'cv::dnn::dnn4_v20190902::`anonymous-namespace'::TFImporter::connect

### ISSUE THREAD

**Issue by Zrufy** [opencv/opencv#16566]
##### System information (version)

- OpenCV => : 4.1.2:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Visual Studio 2015:

##### Steps to reproduce

I converted from a keras model to tensorflow. But I get this error. Has anyone already encountered this type of error?

**Comment by dkurt** [comment]
Please provide a reproducer
