### ISSUE TITLE
Throw exception when creating VideoWriter with invalid name

### ISSUE THREAD

**Issue by basedrhys** [opencv/opencv#16560]
##### System information (version)

- OpenCV => 4.2.0 (Python)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

When creating a VideoWriter object, if you supply an invalid filename, it silently fails and doesn't create the video file. This was found when using datetime as a filename:
2020-02-12_12:31:35.avi --- The colons are not allowed, however rather than throwing an exception it silently fails, not creating the video file. It would be better to return an exception to the user alerting them that they've supplied an invalid filename.

##### Steps to reproduce

    import cv2
    import datetime
    
    d = datetime.datetime.today().replace(microsecond=0)
    curr_datetime = str(d).replace(" ", "_")
    vid_name = "{}.avi".format(curr_datetime)
    print("Saving in video: %s" % vid_name)
    output_video = cv2.VideoWriter(vid_name, \
                              cv2.VideoWriter_fourcc(*'MJPG'), \
                              30, \
                              (1920, 1080))

**Comment by alalek** [comment]
Colons are allowed for URL parameters.
Also complex GStreamer pipelines are allowed too.

There is `.isOpened()` method which you should use.
