### ISSUE TITLE
Can't create layer "result" of type "CTCGreedyDecoder" in function 'cv::dnn::dnn4_v20190902::LayerData::getLayerInstance'

### ISSUE THREAD

**Issue by guapimaomao** [opencv/opencv#16571]
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler =>Visual Studio 2015

##### Steps to reproduce

The following is the code i use:
```
detection_graph = _load_model("deploy.prototxt", "dense121.caffemodel")
detection_graph.setInput(pre_img, "data")
out = detection_graph.forward('result')
```
The prototxt of the model:
```
layer {
  name: "blstm_input"
  type: "Reshape"
  bottom: "conv5_transpose"
  top: "blstm_input"
  reshape_param {
    shape { dim: -1 }
    axis: 0
    num_axes: 2
  }
}
layer {
	name: "result"
	type: "CTCGreedyDecoder"
	bottom: "blstm_input"
	top: "result"
}
```
The error that i ran into:
`cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:525: error: (-2:Unspecified error) Can't create layer "result" of type "CTCGreedyDecoder" in function 'cv::dnn::dnn4_v20190902::LayerData::getLayerInstance'`
May i know what is the problem and how can i make it works?

**Comment by dkurt** [comment]
Please add a reference to origin implementation of CTCGreedyDecoder layer (or just link to Caffe fork with it). Thanks in advance!

**Comment by guapimaomao** [comment]
> Caffe fork



> Please add a reference to origin implementation of CTCGreedyDecoder layer (or just link to Caffe fork with it). Thanks in advance!

Please be specific

**Comment by guapimaomao** [comment]
> Please add a reference to origin implementation of CTCGreedyDecoder layer (or just link to Caffe fork with it). Thanks in advance!

Please explain in details

**Comment by czgdp1807** [comment]
Is it possible to share `dense121.caffemodel` file? IMO, it is needed for re-producing the error locally.
