### ISSUE TITLE
VideoCapture.read drop the last few frames

### ISSUE THREAD

**Issue by roadcode** [opencv/opencv#16576]
##### System information (version)

- OpenCV => :3.4.4.19:
- Operating System / Platform => :Ubuntu16.04LTS:
- Compiler => :Using pip opencv_ptyhon:

##### Detailed description
Using VideoCapture the read video, and sometimes it will drop the last fewe frame.
the last frame num CAP_PROP_POS_FRAMES is not qual CAP_PROP_FRAME_COUNT value

##### Steps to reproduce
here is the Python code
```python
import cv2
cam = cv2.VideoCapture(video_path)
video_frame_num = cam.get(cv2.CAP_PROP_FRAME_COUNT)
success, frame = cam.read()
while success:
    success, frame = cam.read()
extract_video_frame_num = cam.get(cv2.CAP_PROP_POS_FRAMES)
print(video_frame_num, extract_video_frame_num)
```

the result is 356.0, 285.0
why VideoCapture can't extract all frames?

**Comment by abhiTronix** [comment]
@roadcode Nope not producible. Something it wrong with your video, try different source.

**Comment by roadcode** [comment]
@abhiTronix i upload the video to [Google Drive](https://drive.google.com/file/d/1bKU7TFWEdQ7-wD8URLtGcd9yN_kX6LaH/view?usp=sharing), this video have 300 frames, but can only read 244 frames,

**Comment by abhiTronix** [comment]
@roadcode your video is trimmed from original video that's why this is happening. Try another video and you won't get this behavior.

**Comment by roadcode** [comment]
@abhiTronix thks
