### ISSUE TITLE
NVIDIA FFmpeg wrapper for  Windows OpenCV (opencv_ffmpeg_64.dll) - Help

### ISSUE THREAD

**Issue by fhwzl** [opencv/opencv#16589]
### System information 
- OpenCV => 3.4.9
- Operating System / Platform => Win10 64 Bit
- Compiler => Visual Studio 2015 and mingw64
- FFmpeg => n4.2.1

##### Detailed description
- I compile FFmpeg  with nvidia gpu support based on vs2015 and mingw64
  (Using_FFmpeg_with_NVIDIA_GPU_Hardware_Acceleration.pdf in NVIDIA Video_Codec_SDK doc)
- I do ffmpeg warpper failed based on 
  https://github.com/opencv/opencv_3rdparty/blob/ffmpeg/3.4_20191118/ffmpeg/make_mingw.sh
  the command is x86_64-w64-mingw32-g++ -m64 -s -Wall -shared -o opencv_ffmpeg_64.dll -O2 -x c++ -I../include/ffmpeg3 -I../../modules/videoio/src ffopencv.c  -L../lib3 -lavformat -lavcodec -lavdevice -lswscale -lavutil -lavfilter -lsecur32 -lws2_32 -lswresample -static -static-libgcc -static-libstdc++ -Bstatic -lstdc++ -lz -liconv  -lbcrypt

##### Error description
 D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x1e): undefined reference to `__chkstk'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x30d): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x1e): undefined reference to `__chkstk'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x2f5): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x1e): undefined reference to `__chkstk'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x30e): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x106): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x106): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0xfe): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.text$mn+0x106): undefined reference to `__security_check_cookie'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.xdata[$unwind$idct_8x8_8]+0x1c): undefined reference to `__GSHandlerCheck'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.xdata[$unwind$idct_16x16_8]+0x1c): undefined reference to `__GSHandlerCheck'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.xdata[$unwind$idct_32x32_8]+0x20): undefined reference to `__GSHandlerCheck'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.xdata[$unwind$sao_band_filter_8]+0x18): undefined reference to `__GSHandlerCheck'
D:/Softwares/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib3\libavcodec.a(libavcodec/hevcdsp.o):(.xdata[$unwind$put_hevc_qpel_hv_8]+0x10): undefined reference to `__GSHandlerCheck'

  Please help, any solutions?

**Comment by alalek** [comment]
I believe you should try to replace MinGW with MSVC compiler in this case.

**Comment by fhwzl** [comment]
Thank you for your reply.  I replace x86_64-w64-mingw32-g++ with cl, but I'm not familiar with cl's command line arguments. Can you give me the detailed command line parameters with cl compile? I have try:
cl  ffopencv.cpp /LD /I ..\..\modules\videoio\src\ /I ..\include\ffmpeg3\ /link ..\lib3\libavcodec.a ..\lib3\libavdevice.a ..\lib3\libavfilter.a  ..\lib3\libavformat.a ..\lib3\libavutil.a ..\lib3\libswresample.a ..\lib3\libswscale.a
Error info:
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ffopencv.cpp
d:\cmake\opencv349\opencv-3.4.9\3rdparty\include\ffmpeg3\libavutil\rational.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1493): error C2589: '(': illegal token on right side of '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1493): error C2059: syntax error: '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1503): error C2589: '(': illegal token on right side of '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1503): error C2059: syntax error: '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1792): error C2589: '(': illegal token on right side of '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(1792): error C2059: syntax error: '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(2489): error C2589: '(': illegal token on right side of '::'
..\..\modules\videoio\src\cap_ffmpeg_impl.hpp(2489): error C2059: syntax error: '::'

**Comment by fhwzl** [comment]
Hello, I update the command line parameters, and it can get the ffopencv.lib and ffopencv.dll. I don't know if it works.  Any suggestions ? thank you very much.
D:\CMake\OpenCV349\opencv-3.4.9\3rdparty\ffmpeg>cl  ffopencv.cpp /LD /I ..\..\modules\videoio\src\ /I ..\include\ffmpeg3\ /link ..\lib3\libavcodec.a ..\lib3\libavdevice.a ..\lib3\libavfilter.a  ..\lib3\libavformat.a ..\lib3\libavutil.a ..\lib3\libswresample.a ..\lib3\libswscale.a ..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libws2_32.a ..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libsecur32.a ..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libbcrypt.a ..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libole32.a ..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libuser32.a
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ffopencv.cpp
d:\cmake\opencv349\opencv-3.4.9\3rdparty\include\ffmpeg3\libavutil\rational.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:ffopencv.dll
/dll
/implib:ffopencv.lib
..\lib3\libavcodec.a
..\lib3\libavdevice.a
..\lib3\libavfilter.a
..\lib3\libavformat.a
..\lib3\libavutil.a
..\lib3\libswresample.a
..\lib3\libswscale.a
..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libws2_32.a
..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libsecur32.a
..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libbcrypt.a
..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libole32.a
..\..\..\..\..\Softwares\msys64\mingw64\x86_64-w64-mingw32\lib\libuser32.a
ffopencv.obj
   Creating library ffopencv.lib and object ffopencv.exp

D:\CMake\OpenCV349\opencv-3.4.9\3rdparty\ffmpeg>ls
BufferOverflow.lib   ffmpeg-download.ps1.in  ffopencv.cpp  ffopencv.exp  ffopencv.obj  opencv_ffmpeg.rc    readme.txt
BufferOverflowU.lib  ffmpeg.cmake  ffopencv.dll  ffopencv.lib  license.txt   opencv_ffmpeg_64.o
