### ISSUE TITLE
Import SavedModel from TensorFlow

### ISSUE THREAD

**Issue by ouening** [opencv/opencv#16582]
##### System information (version)

- OpenCV => 4.1.2（Ubuntu18.04），4.2（Win10 64bit)
- Operating System / Platform => Linux, Win
- Compiler => gcc7.5(linux), Visual Studio 2019(Win10)
- Tensorflow => 2.1

##### Detailed description
I want to convert keras model to `.pb` file and load it using `dnn.readNetFromTensorflow()` , and I got an error like the title shows ( same error in Ubuntu18.04 with opencv 4.1.2):
```
error: OpenCV(4.2.0) E:\ScientificComputing\opencv-4.2.0\modules\dnn\src\tensorflow\tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: my_model/saved_model.pb in function 'ReadTFNetParamsFromBinaryFileOrDie'
```
Can someone tell me the best way to load a keras model (tf version is 2.1)? I tried the solution in issue #13728 , but didn't work for me.

##### Steps to reproduce

```python
import tensorflow as tf
import cv2
from cv2 import dnn
import numpy as np 
import matplotlib.pyplot as plt
import os
print(tf.__version__)
print(cv2.__version__)
model = tf.keras.applications.mobilenet.MobileNet(weights=None)
model.save('my_model', save_format='tf')

net = dnn.readNetFromTensorflow('my_model/saved_model.pb')
```
 In tf2.1, the `save` method using argument `save_format='tf'` will generate files like below:
![image](https://user-images.githubusercontent.com/15122811/74510623-232e6b00-4f3f-11ea-8af4-838decbc5173.png)

**Comment by dkurt** [comment]
OpenCV do not support loading from SavedModel format for now. You need to create a frozen graph.

That's kind of strange that TensorFlow has a lot of ways to export models in different formats: TFLite, frozen graph, SavedModel, serving model, TFHub representation, Keras's .h5.

**Comment by ouening** [comment]
> OpenCV do not support loading from SavedModel format for now. You need to create a frozen graph.
> 
> That's kind of strange that TensorFlow has a lot of ways to export models in different formats: TFLite, frozen graph, SavedModel, serving model, TFHub representation, Keras's .h5.
> 
> Please upload your model somewhere so one who will work on that feature can use it as a start point.

Thanks, the model is simple and everyone who have installed tensorflow can obtain from :
```python
import tensorflow as tf
# model = tf.keras.applications.mobilenet.MobileNet(weights='imagenet')
model = tf.keras.applications.mobilenet.MobileNet(weights=None)
```

With reference to [https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/) and [https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py](https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py), I convert keras model to tensorflow's frozen graph and load it successfully using `dnn.readNetFromTensorflow`, my code lists below:

```python
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 14 15:04:32 2020

@author: zhou-
"""

from cv2 import dnn
import cv2
import numpy as np 
import matplotlib.pyplot as plt
import os
from keras import backend as K
from keras.models import load_model
#from tensorflow_serving.session_bundle import exporter
from keras.models import model_from_config
from keras.models import Sequential,Model
import tensorflow as tf
from tensorflow.python.tools import freeze_graph
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
import os

print(tf.__version__)
print(cv2.__version__)
#%% opencv处理适合模型输入的图片
img_file = r"C:\Users\zhou-\Pictures\cat.jpg"
img_cv2 = cv2.imread(img_file)
print("[INFO]Image shape: ", img_cv2.shape)

# 主要图片尺寸要和模型输入匹配（mobilenet要求输入的尺寸为224*224）
inWidth = 224
inHeight = 224
blob = cv2.dnn.blobFromImage(img_cv2,
                                scalefactor=1.0 / 255,
                                size=(inWidth, inHeight),
                                mean=(0, 0, 0),
                                swapRB=False,
                                crop=False)
# blob = np.transpose(blob, (0,2,3,1)) # 适合keras mobilenet网络输入格式
print("[INFO]img shape: ", blob.shape)

#%% 保存keras模型为SaveModel会报错，相关issue见：
# https://github.com/opencv/opencv/issues/16582
model = tf.keras.applications.mobilenet.MobileNet(weights=None)
# model.save('my_model', save_format='tf') # Save model to SavedModel format

# 参考https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py

# Save model to SavedModel format
tf.saved_model.save(model, "./models")

# Convert Keras model to ConcreteFunction
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))

# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()

layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 50)
print("Frozen model layers: ")
for layer in layers:
    print(layer)

print("-" * 50)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)

# Save frozen graph from frozen ConcreteFunction to hard drive
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="frozen_graph.pb",
                  as_text=False)

net = dnn.readNetFromTensorflow('frozen_models/frozen_graph.pb')

# Run a model
net.setInput(blob)
out = net.forward()

# Get a class with a highest score.
out = out.flatten()
classId = np.argmax(out)
confidence = out[classId]

# Put efficiency information.
t, _ = net.getPerfProfile()
label = 'Inference time: %.2f ms' % (t * 1000.0 / cv2.getTickFrequency())
cv2.putText(img_cv2, label, (0, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0))

# Print predicted class.
def load_imagenet_classes(file_path):
    '''
    imagenet对应的标签数据如下所示：
    0: 'tench, Tinca tinca',
    1: 'goldfish, Carassius auratus',
    ...
    '''
    classes = []
    contents = None
    with open(file_path,'r') as f:
        contents = f.readlines()
    for cnt in contents:
        cnt = cnt.strip()
        classes.append(cnt.split(':')[1].strip().replace(',',''))
    
    return classes
        
classes = load_imagenet_classes('imagenet_classes.txt')

label = '%s: %.4f' % (classes[classId] if classes else 'Class #%d' % classId, confidence)
cv2.putText(img_cv2, label, (0, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0))

cv2.imwrite('output-{}.png'.format(img_file.split('\\')[-1][:-4]), img_cv2)
```

**Comment by dkurt** [comment]
@ouening, Glad to present that with PR https://github.com/opencv/opencv/pull/16905 you can now do:

1. Export to SavedModel
```python
import tensorflow as tf

model = tf.keras.applications.mobilenet.MobileNet(weights=None)
model.save('my_model', save_format='tf')
```

2. Conversion of SavedModel to a frozen graph by
```python
import tensorflow as tf

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('my_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 224, 224, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
```

3. Import and running through OpenCV:
```python
import numpy as np
import cv2 as cv

net = cv.dnn.readNet('frozen_graph.pb')
inp = np.random.standard_normal([1, 3, 224, 224]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```

Looking forward for your feedback!

**Comment by Lotte1990** [comment]
I see this didn't make it into 4.3.0, which was released a couple of days after the pull request. Will it be in 4.4.0?

**Comment by dkurt** [comment]
@Lotte1990, please try https://github.com/opencv/opencv/issues/16879#issuecomment-603416876. The key part is `Remove NoOp nodes` block.

**Comment by Lotte1990** [comment]
Perhaps my question was a bit unclear. It works for the master branch (without modifications), but it doesn't work for the 4.2.0 and 4.3.0 versions. I prefer using the official release versions, so I was just wondering if this will make it to 4.4.0.

**Comment by dkurt** [comment]
@Lotte1990, it will be available in 4.4.0, sure.

**Comment by livezingy** [comment]
@dkurt
Thanks you very much!
I have tried your steps. It could convert to the .pb file successfully. But when I Import and running through OpenCV, It report the following errors:
```
net = dnn.readNet('frozen_graph2.pb')
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-10658tfl\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:553: error: (-2:Unspecified error) Input layer not found: StatefulPartitionedCall/StatefulPartitionedCall/model/tf_op_layer_Tile_3/multiples/Tile_3/multiples/0 in function 'cv::dnn::dnn4_v20200609::`anonymous-namespace'::TFImporter::connect'
```
Could you give me some suggestions please? thanks very much!

System information (version)

- python3.6
- opencv-contrib-python 4.4.0.44 
- tensorflow-cpu 2.2.0
- keras 2.3.1

Detailed description
My Model is trained refer to this: https://github.com/YunYang1994/TensorFlow2.0-Examples.
There is a _yolov3.index_ and _yolov3.data-00000-of-00001_  in the model folder yolov3. 
```
D:\YOLOV3
    yolov3.data-00000-of-00001
    yolov3.index
```
The model could work normally when I load it as following:
```
import tensorflow as tf
from core.yolov3 import YOLOv3
INPUT_SIZE   = 416
input_layer  = tf.keras.layers.Input([INPUT_SIZE, INPUT_SIZE, 3])
feature_maps = YOLOv3(input_layer)

bbox_tensors = []
for i, fm in enumerate(feature_maps):
    bbox_tensor = decode(fm, i)
    bbox_tensors.append(bbox_tensor)

model = tf.keras.Model(input_layer, bbox_tensors)
model.load_weights("./yolov3/yolov3")
```
 I convert it to .pb as following:
1. Export to SavedModel
```
import tensorflow as tf
from core.yolov3 import YOLOv3
from tensorflow.python.tools import freeze_graph
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

INPUT_SIZE   = 416

input_layer  = tf.keras.layers.Input([INPUT_SIZE, INPUT_SIZE, 3])
feature_maps = YOLOv3(input_layer)

bbox_tensors = []
for i, fm in enumerate(feature_maps):
    bbox_tensor = decode(fm, i)
    bbox_tensors.append(bbox_tensor)

model = tf.keras.Model(input_layer, bbox_tensors)
model.load_weights("./yolov3/yolov3")
model.save('my_model', save_format='tf')
```
2. Conversion of SavedModel to a frozen graph by

```
loaded = tf.saved_model.load('my_model')
infer = loaded.signatures['serving_default']
f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 416, 416, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
    f.write(graph_def.SerializeToString())
```

3. Import and running through OpenCV:
```
import numpy as np
import cv2 as cv

net = cv.dnn.readNet('frozen_graph.pb')
inp = np.random.standard_normal([1, 3, 416, 416]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```
Then it report the error I mentioned above. Thanks again for any help or suggestions!

**Comment by dkurt** [comment]
@livezingy, with `StatefulPartitionedCall` OpenCV cannot import models (it's called Eager mode of TensorFlow). Can you try if [OpenVINO](https://github.com/openvinotoolkit/openvino/) can convert a model?

**Comment by livezingy** [comment]
@dkurt Thanks very much for your reply. I will try it and let you know the results.

**Comment by livezingy** [comment]
@dkurt 
 I have tried the OpenVINO, It Can't convert a model too.
1. According to [Converting a TensorFlow* Model ](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html), When it convert the type of "MetaGraph" TensorFlow, It requires a path to the MetaGraph .meta file to convert a model. But there is no .meta file in my TensorFlow Model. So I can't convert it from only .index and .data-00000-of-00001 files.
2. I try to convert the  frozen graph file that generated according the method you mentioned in this link. 
```
C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\model_optimizer>python mo_tf.py --input_model D:\PYTHON\yolov3\frozen_graph.pb
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      D:\PYTHON\yolov3\frozen_graph.pb
        - Path for generated IR:        C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\model_optimizer\.
        - IR output name:       frozen_graph
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
Model Optimizer version:        2021.1.0-1237-bece22ac675-releases/2021/1
[ ERROR ]  Shape [ -1 416 416   3] is not fully defined for output 0 of "x". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "x".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "x".
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]
[ ERROR ]  It can happen due to bug in custom shape infer function <function Parameter.infer at 0x000002B313D37E18>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "x" node.
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
```

**Comment by binlbl** [comment]
@livezingy 
Any solutions to the "Input layer not found: StatefulPartitionedCall/StatefulPartitionedCall" problem?
I had this problem too.

**Comment by bozdemir** [comment]
I have the same problem, any solutions ?

**Comment by agorman** [comment]
Same StatefulPartitionedCall problem.

**Comment by dkurt** [comment]
@livezingy, you need use `--saved_model_dir` flag instead of `--input_model` and point it to the folder with SavedModel.

Sorry for ignoring this thread for a long time. At this moment support of SavedModel format in OpenCV is very limited. Need create a frozen `.pb` graph.  In case `StatefulPartitionedCall` error, please try switch Eager execution Off by `tf.compat.v1.disable_eager_execution()` right after TensorFlow import.

Alternatively, OpenVINO backend can be used, which supports SavedModel format better.

**Comment by SEHAIRIKamal** [comment]
> 
Hi dkurt
adding `tf.compat.v1.disable_eager_execution()` after after TensorFlow import. in 
`import tensorflow as tf
tf.compat.v1.disable_eager_execution()
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('C:/Tensorflow/data/models/centernet_hg104_1024x1024_coco17_tpu-32/saved_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(input_tensor=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph_centernet.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())`

returns the following error:
`Traceback (most recent call last):
  File "C:\Tensorflow\convertsavedmodeltofrozengraph.py", line 11, in <module>
    f2 = convert_variables_to_constants_v2(f)
  File "C:\Tensorflow\venv\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 1143, in convert_variables_to_constants_v2
    converter_data = _FunctionConverterDataInEager(
  File "C:\Tensorflow\venv\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 813, in __init__
    self._build_tensor_data()
  File "C:\Tensorflow\venv\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 835, in _build_tensor_data
    data = self._eval(map_index_to_variable[idx])
  File "C:\Tensorflow\venv\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 868, in _eval
    return tensor.numpy()
  File "C:\Tensorflow\venv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 675, in numpy
    raise NotImplementedError(
NotImplementedError: numpy() is only available when eager execution is enabled.`

**Comment by reyamed** [comment]
@SEHAIRIKamal did you find any solution to this?
I'm having the same problem and I don't know how to solve it

**Comment by SEHAIRIKamal** [comment]
> @SEHAIRIKamal did you find any solution to this? I'm having the same problem and I don't know how to solve it

Unfortunately, not yet! 
I tried tf2onnx but the same thing I still got errors
