### ISSUE TITLE
CMake fails to configure opencv 4.1.2 WindowsStore (UWP/ WinRT)

### ISSUE THREAD

**Issue by lapislazinus** [opencv/opencv#16584]
### Detailed description
Error when trying to configure opencv 4.1.2 for VS 16 2019 ARM64 UWP

`include could not find load file: cmake/platforms/OpenCV_WinRT.cmake`

CMakeLists.txt line 104:
`include("cmake/platforms/OpenCV-${CMAKE_SYSTEM_NAME}.cmake" OPTIONAL RESULT_VARIABLE "OPENCV_CMAKE_SYSTEM_FILE")`

which resolves to _cmake/platforms/OpenCV-WindowsStore.cmake_
The only line in this file is:
`include("${CMAKE_CURRENT_LIST_DIR}/OpenCV_WinRT.cmake")`

but the file in the same folder is named `OpenCV-WinRT.cmake` and therefore obviously fails to include.

##### Steps to reproduce
set CMAKE_SYSTEM_PROCESSOR to aarch64 (in order to avoid another bug)
Configure -> Select Toolchain for Cross-Compiling (ARM64) -> WindowsStore Version 10.0

##### Suggested Fix
Changing the content of _OpenCV-WindowsStore.cmake_ to `include("${CMAKE_CURRENT_LIST_DIR}/OpenCV-WinRT.cmake")` fixes the issue

**Comment by alalek** [comment]
Already fixed: #15720
Update to latest version.

**Comment by lapislazinus** [comment]
my apologies, i thought i had the latest version
