### ISSUE TITLE
dyld: warning, LC_RPATH

### ISSUE THREAD

**Issue by Echo-Joker** [opencv/opencv#16583]
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Library/Python/2.7/site-packages/cv2/.dylibs/QtWidgets being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)

**Comment by alalek** [comment]
> cv2/.dylibs/QtWidgets

We don't ship these Python bindings.
We can't fix that because it is not a part of this repository.
