### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.

### ISSUE THREAD

**Issue by YuqingWu79** [opencv/opencv#16590]
**I just want to run a simple opencv code.
This my code:**

`import cv2
import sys
import imutils

if __name__ == '__main__':

    # Set up tracker.
    # Instead of MIL, you can also use

    # tracker_types = ['BOOSTING', 'MIL', 'KCF', 'TLD', 'MEDIANFLOW', 'GOTURN', 'MOSSE']
    # tracker_type = tracker_types[2]
    #
    # if int(minor_ver) < 3:
    #     tracker = cv2.TrackerCSRT_create()
    # else:
    #     if tracker_type == 'BOOSTING':
    #         tracker = cv2.TrackerBoosting_create()
    #     if tracker_type == 'MIL':
    #         tracker = cv2.TrackerMIL_create()
    #     if tracker_type == 'KCF':
    #         tracker = cv2.TrackerKCF_create()
    #     if tracker_type == 'TLD':
    #         tracker = cv2.TrackerTLD_create()
    #     if tracker_type == 'MEDIANFLOW':
    #         tracker = cv2.TrackerMedianFlow_create()
    #     if tracker_type == 'GOTURN':
    #         tracker = cv2.TrackerGOTURN_create()
    #     if tracker_type == 'MOSSE':
    #         tracker = cv2.TrackerMOSSE_create()

    tracker = cv2.TrackerCSRT_create()

    # Read video
    video = cv2.VideoCapture("/Users/wuyuqing/Desktop/bishe/code/march_madness/video/g.mp4")

    # Exit if video not opened.
    if not video.isOpened():
        print("Could not open video")
        sys.exit()

    # Read first frame.
    ok, frame = video.read()
    if not ok:
        print('Cannot read video file')
        sys.exit()

    # Define an initial bounding box
    bbox = (287, 23, 86, 320)

    # Uncomment the line below to select a different bounding box
    #bbox = cv2.selectROI(frame, False)

    # Initialize tracker with first frame and bounding box
    ok = tracker.init(frame, bbox)

    while True:
        # Read a new frame
        ok, frame = video.read()

        # Start timer
        timer = cv2.getTickCount()

        # Update tracker
        ok, bbox = tracker.update(frame)

        # Calculate Frames per second (FPS)
        fps = cv2.getTickFrequency() / (cv2.getTickCount() - timer)

        # Draw bounding box
        if ok:
            # Tracking success
            p1 = (int(bbox[0]), int(bbox[1]))
            p2 = (int(bbox[0] + bbox[2]), int(bbox[1] + bbox[3]))
            cv2.rectangle(frame, p1, p2, (255, 0, 0), 2, 1)
        else:
            # Tracking failure
            cv2.putText(frame, "Tracking failure detected", (100, 80), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 0, 255), 2)

        # Display tracker type on frame
        cv2.putText(frame,"CSRTTracker", (100, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (50, 170, 50), 2)

        # Display FPS on frame
        cv2.putText(frame, "FPS : " + str(int(fps)), (100, 50), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (50, 170, 50), 2)

        # Display result
        cv2.imshow("Tracking", frame)

        # Exit if ESC pressed
        k = cv2.waitKey(1) & 0xff
        if k == 27: break`

**But I face a qt problem.
My pycharm displayed the mistake as follows:**

`
objc[22067]: Class QMacAutoReleasePoolTracker is implemented in both /Users/wuyuqing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/cv2/.dylibs/QtCore (0x10db83700) and /usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Versions/5/QtCore (0x1177ad088). One of the two will be used. Which one is undefined.
objc[22067]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/wuyuqing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/cv2/.dylibs/QtCore (0x10db83778) and /usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Versions/5/QtCore (0x1177ad100). One of the two will be used. Which one is undefined.
objc[22067]: Class KeyValueObserver is implemented in both /Users/wuyuqing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/cv2/.dylibs/QtCore (0x10db837a0) and /usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Versions/5/QtCore (0x1177ad128). One of the two will be used. Which one is undefined.
objc[22067]: Class RunLoopModeTracker is implemented in both /Users/wuyuqing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/cv2/.dylibs/QtCore (0x10db837f0) and /usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Versions/5/QtCore (0x1177ad178). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7ff0df8a4930) is not the object's thread (0x7ff0df8b7720).
Cannot move to target thread (0x7ff0df8a4930)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen, webgl.

`

**I have tried this:**

`
export Qt5_DIR=/usr/local/Cellar/qt/5.13.1
export PATH=$PATH:$Qt5_DIR/bin
export QT_PLUGIN_PATH=/usr/local/Cellar/qt/5.13.1/plugins
export DYLD_PRINT_LIBRARIES=1
`

**but it didn't work!
Hope somebody could help me!!Thanks!!!!**

**Comment by alalek** [comment]
> cv2/.dylibs/QtCore

We don't ship these Python bindings.
We can't fix that because it is not a part of this repository.

> You might be loading two sets of Qt binaries into the same process

Investigate in this direction.
