### ISSUE TITLE
Extra cudaStreamCreate/cudaStreamDestroy

### ISSUE THREAD

**Issue by mnicely** [opencv/opencv#16592]
##### System information (version)

- OpenCV => 4.2.0-dev
- Operating System / Platform => Ubuntu 18.04
- Compiler => GNU G++ 7.4.0
- Python => 3.6.9

##### Detailed description

When I run **self.frame_device.upload(self.frame, stream)** I'm getting an extra _cudaStreamCreate_ and _cudaStreamDestroy_ right before the _cudaMemcpy2DAsync_. (See attached)
![extraStream](https://user-images.githubusercontent.com/50021634/74594782-014ceb00-5008-11ea-9b89-a381021ecde5.png)

##### Steps to reproduce

```
import os
import sys
import glob
import numpy as np
import time
import cv2
import cudasift

class PreCuda:
    def __init__(self, size):
        print("__init__")
        self.rows = size
        self.cols = size
        self.stream = cv2.cuda_Stream( )
        self.frame = np.zeros((size,size,3),np.uint8)
        cv2.cuda.registerPageLocked(self.frame)
        self.frame_device = cv2.cuda_GpuMat(size,size,cv2.CV_8UC3)

    def __del__(self):
        print("unregisterPageLocked")
        cv2.cuda.unregisterPageLocked(self.frame)

    def ProcessFrame(self):
        print("ProcessFrame")
        self.frame_device.upload(self.frame, self.stream) # <-- issue

    def Frame(self, img):
        print("Frame")
        img = cv2.imread(image_name)
        img.resize(self.rows, self.cols, 3)
        np.copyto(self.frame,img)

image_names = glob.glob('images/*')


size = 512
image_data = PreCuda(size)

for image_name in image_names:
    image_data.Frame(image_name)
    image_data.ProcessFrame()
```
-->

**Comment by r2d3** [comment]
Hello Matthew @mnicely,

you could verify the latest version of OpenCV master, it integrates my patch that solves this issue. And confirm that this is solving the issue for you too.

Regards

David

**Comment by mnicely** [comment]
Hi @r2d3
Unfortunately, that task is not active and it might be awhile before I can circle back. I'm fine with closing this.
