### ISSUE TITLE
Can't run OpenCV – 4.2.0 Windows build exe.

### ISSUE THREAD

**Issue by muhsinkompas** [opencv/opencv#16593]
##### System information (version)

- OpenCV => OpenCV – 4.2.0
- Operating System / Platform => Windows
- Compiler => none

##### Detailed description

Nothing happens when I run the OpenCV-4.2.0 exe file. But it is working smoothly in other versions.

**Comment by dkurt** [comment]
Please follow issues guidelines to create a bug request. Unless that let's keep issue closed.
