### ISSUE TITLE
OPENCV4.2.0 +cuda10.0+cudnn7.6.5 with VS2017 on win10 ,unhandled exceptions: Microsoft C++ exceptions: cv::dnn::cuda4dnn::csl::CUDAException

### ISSUE THREAD

**Issue by molyswu** [opencv/opencv#16602]
Hi,
VS2017 +OPENCV4.2.0 +cuda10.0+cudnn7.6.5 what run yolov3 model tested bug :

   net.setPreferableBackend(DNN_BACKEND_CUDA);
net.setPreferableTarget(DNN_TARGET_CUDA);
0x00007FFD17B04048(located at test2.exe )There are unhandled exceptions: Microsoft C++ exceptions: cv::dnn::cuda4dnn::csl::CUDAException，In memory location 0x000000FE94BADDD0 。

Thanks

**Comment by YashasSamaga** [comment]
@molyswu what was the message in the exception?

**Comment by molyswu** [comment]
print as follows error at detection.exe
OpenCV(4.2.0) Error: Parsing error (Failed to parse NetParameter file: yolov3_1_80000.weights) in cv::dnn::dnn4_v20191202::readNetFromDarknet, file E:\tools\opencv-4.2.0\modules\dnn\src\darknet\darknet_importer.cpp, line 214
.\pei010718
[ INFO:0] global E:\tools\opencv-4.2.0\modules\core\src\ocl.cpp (891) cv::ocl::haveOpenCL Initialize OpenCL runtime...
[ INFO:0] global E:\tools\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type NetInputLayer

**Comment by YashasSamaga** [comment]
@molyswu Can you share a link to the weights and configuration file?

**Comment by molyswu** [comment]
The weights and configuration file as :

**Comment by YashasSamaga** [comment]
@molyswu I am not able to reproduce the problem on master in Ubuntu with CUDA 10.2. Can you provide code which reproduces the error?

**Comment by molyswu** [comment]
Hi,YashasSamaga!
The test_code  send to your email( Yashas_2010@yahoo.com) .

Thanks
molyswu

**Comment by molyswu** [comment]
@YashasSamaga  Has this bug been solved?

Thanks
molyswu

**Comment by YashasSamaga** [comment]
@molyswu I haven't got the code. Please upload it on a public code hosting service such as Gist and share a link here.

**Comment by YashasSamaga** [comment]
@molyswu It's working for me but the detections appear to be wrong. The problem is probably specific to your PC.

The exception will have a message associated with it. If you can find that out, it'll help identify the problem.

**Comment by molyswu** [comment]
@YashasSamaga 
code :
[V3.txt](https://github.com/opencv/opencv/files/4261913/V3.txt)

**Comment by YashasSamaga** [comment]
@molyswu Please enclose `int main()` with a try-catch block.

```
int main () try
{
    // other code
}
catch(const std::exception& ex)
{
    std::cout << ex.what() << std::endl;
}
```

**Comment by molyswu** [comment]
@YashasSamaga  Chnanged code:"int main() with a try-catch block", inf:

[ INFO:0] global E:\tools\opencv-4.2.0\modules\core\src\ocl.cpp (891) cv::ocl::haveOpenCL Initialize OpenCL runtime...
[ INFO:0] global E:\tools\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

OpenCV(4.2.0) e:\tools\opencv-4.2.0\modules\dnn\src\cuda\execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'cv::dnn::cuda4dnn::csl::make_policy'

**Comment by YashasSamaga** [comment]
@molyswu what device do you have? can you upload your CMakeCache.txt?

You have mostly got your build wrong. [This](https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/) is a good tutorial which covers the compute capability part.

I think these error messages need to be improved and building has to be simplfiied because people are running into these problems often.

**Comment by kaanaykutkabakci** [comment]
My platform is:

OpenCV: 4.2.0
CUDA: 10.0
WIN7
cuDNN: 7.6.5
GPU: 1080 TI
Visual Studio: 2019

I am trying to run ssd_mobilenet_v1_coco_2018_01_28, then i am getting these errors after try/catch implementation:

  | [0] | 0x000007fed012e0e0 {opencv_core420.dll!cv::Exception::`vector deleting destructor'(unsigned int)} | void *

  | [1] | 0x000007fed031a090 {opencv_core420.dll!cv::Exception::what(void)const } | void *

My CMakeCache.txt is linked below:

[CMakeCache.txt](https://github.com/opencv/opencv/files/4273829/CMakeCache.txt)

**Comment by YashasSamaga** [comment]
@kaanaykutkabakci Can you post a backtrace if possible? That exception is mostly not from the DNN module.

**Comment by kaanaykutkabakci** [comment]
Hello @YashasSamaga, thank you for your interest. Sorry for my wrong question. I have  solved my problem by uninstall all CUDA things(Runtime, Drivers, cuDNN etc.) and reinstall them. My custom Mask R-CNN model works with OpenCV+CUDA. 

I guess, my problem was about NVIDIA driver version and cuDNN.

**Comment by molyswu** [comment]
Hi,YashasSamaga!
My CMakeCache.txt file  send to your email.

Thanks
molyswu

**Comment by YashasSamaga** [comment]
@molyswu It looks fine. Can you try reinstalling CUDA Toolkit and cuDNN?

**Comment by Ya2knight** [comment]
I came with the same problem

**Comment by kaanaykutkabakci** [comment]
@Ya2knight What kind of model you are using ? If it has proposal layer, proposal number may cause this problem. I have overcame this problem by two ways.  First one is reinstalling CUDA, driver and cuDNN. Second one is decreasing proposal number.

**Comment by YashasSamaga** [comment]
@Ya2knight Please share the exception message. https://github.com/opencv/opencv/issues/16602#issuecomment-592871033 gives the steps.

**Comment by Ya2knight** [comment]
@kaanaykutkabakci thanks for your advice! I use yolo. I replaced my driver of version 10.1 with 10.2, the newest one, and reinstalled CUDA, cuDNN. finally, it's OK now
@YashasSamaga I forgot to copy the message.
