### ISSUE TITLE
t.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

### ISSUE THREAD

**Issue by ProfessorDobby** [opencv/opencv#16613]
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may 
fix this problem.

Abort trap: 6

**Comment by ifueko** [comment]
Having the same issue. Occurs when attempting to open videos with cv2.VideoCapture in python.

**Comment by emakryo** [comment]
this workaround may help
https://github.com/ageitgey/face_recognition/issues/1041#issuecomment-582401795
