### ISSUE TITLE
missing V4L2_PIX_FMT_Y12 support

### ISSUE THREAD

**Issue by firebladed** [opencv/opencv#16620]
I am trying to get an AMG88xx infra red camera working see [question](https://answers.opencv.org/question/226432/videoio-error-v4l2-pixel-format-of-incoming-image-is-unsupported-by-opencv/) which only outputs Y12

after exploring the source for video4linux capture i noticed that [cap_v4l.cpp](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_v4l.cpp#L572) is missing V4L2_PIX_FMT_Y12 but supports V4L2_PIX_FMT_Y10 and V4L2_PIX_FMT_Y16

im not very familiar with the inner working of OpenCV but the supported y10 format is very similar to the Y12 see [YUV picture formats](https://linuxtv.org/downloads/v4l-dvb-apis/uapi/v4l/yuv-formats.html) the both are stored as 16bit words with the y10 having more zero padding than the y12 which was added by this [patch](https://github.com/opencv/opencv/commit/4997a6bf06ce008ed750da8f199f27aedccf0139#diff-8afbfaee78cb993ca4836dd4ccb5ae9b)

could i do the same and would anything else be needed to add support for Y12?

**Comment by alalek** [comment]
Feel free to propose PR similar to Y10.
We don't have this camera, so validation for this H/W is on your side.
