### ISSUE TITLE
event.LBUTTONDOWN mouse click x and y coordinates are consistently incorrect in Linux OS

### ISSUE THREAD

**Issue by kkemillie** [opencv/opencv#16621]
##### System information (version)

- OpenCV => :3.4.3.18
- Operating System / Platform => Linux (Raspberry Pi 3 Model B)
- Compiler => Thonny Python IDE

##### Detailed description

Hello,

I wrote a simple image display script in Python
[imageDisplay.txt](https://github.com/opencv/opencv/files/4228943/imageDisplay.txt)
 that cycles through 3 jpg images stored in the same folder. When I click on the right side of the picture, the next picture in the cycle should be displayed. When I click on the left side of the picture the previous image in the cycle should be displayed. The x coordinates on my screen range from 0 to ~1300 so I set a left-side click to be x<600 and a right-side click to be x>600.

My script works perfectly on a Windows 64 bit computer, however it doesn't work when I run it on my Raspberry Pi Model 3. I'm not sure if it's a Linux problem or if there's some sort of incompatibility with the Pi. When I click the right side of the image once, x correctly displayed as a value greater than 600. However, when I click the exact same spot again a second time, a value less than 600 is display. As I continue clicking the exact same spot, the x coordinate alternates between correct/incorrect x values .

In the screenshot below, I clicked the exact same spot on the right side of my image each time and printed out the associated x coordinate. As you can see, the x coordinate alternates between x>600 and x<600.

![example](https://user-images.githubusercontent.com/60238641/74905485-51b3a800-537c-11ea-9e0b-b96a77daf341.PNG)

I have a similar issue with the y coordinate. How can this be fixed? Any help is greatly appreciated! Thank you!

**Comment by alalek** [comment]
Coordinates are returned in images system, not screen or window (if image is scaled).

So, this assumption is not correct:

> The x coordinates on my screen range from 0 to ~1300, so I set a left-side click to be x<600 and a right-side click to be x>600

Right condition should work with half of image.cols.

Also you can resize input images yourself on some "screen"-sized canvas.

---

> cv2.namedWindow("window", cv2.WND_PROP_FULLSCREEN)

Invalid second parameter.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org


<details>

<summary>Learn how OpenCV mouse events works</summary>

```
import sys
import numpy as np
import cv2 as cv

print(cv.getBuildInformation())

cv.namedWindow("window", cv.WINDOW_NORMAL)

img = np.zeros((600, 800, 3), dtype=np.uint8)
cv.imshow("window", img)

def handleEvent(event, x, y, flag, param):
    print(x, y, flag)
    img = np.zeros((600, 800, 3), dtype=np.uint8)
    cv.putText(img, "%dx%d  %d" % (x, y, flag), (100, 100), cv.FONT_HERSHEY_PLAIN, 1.0, (0, 255, 0), thickness = 2, lineType=cv.LINE_AA)
    cv.imshow("window", img)

cv.setMouseCallback("window", handleEvent)

isFullScreen = False
while True:
    key = cv.waitKey()
    if key == 27:
        break
    if key == ord(' '):
        isFullScreen = not isFullScreen
        print("full screen: %s" % isFullScreen)
        cv.setWindowProperty("window", cv.WND_PROP_FULLSCREEN,
                             cv.WINDOW_FULLSCREEN if isFullScreen else cv.WINDOW_NORMAL)

print('Done')
cv.destroyAllWindows()
```

</summary>
