### ISSUE TITLE
Help with OpenCV configure - objdetec

### ISSUE THREAD

**Issue by adamrankin** [opencv/opencv#16642]
Hello,

I am trying to configure OpenCV 4.2.0 with OpenCV_contrib 4.2.0 specified, and I get the following CMake error:

```cmake
CMake Error at cmake/OpenCVUtils.cmake:1481 (target_include_directories):
  Cannot specify include directories for target "opencv_objdetect_AVX" which
  is not built by this project.
```

Could anyone help me with figure out where the AVX cmake target should come from? Or if they've seen a similar issue elsewhere?

Thanks,
Adam

**Comment by dkurt** [comment]
Please add all the details to make it reproducible - commits hashes, CMake command flags

**Comment by adamrankin** [comment]
Wrong place for this, was more of a question. Will post in the forums.

**Comment by CrazyForSummer** [comment]
Excluding from source files list: modules/core/test/test_intrin.fp16.cpp
CMake Error at cmake/OpenCVUtils.cmake:266 (target_include_directories):
  Cannot specify include directories for target "opencv_test_core_FP16" which
  is not built by this project.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:672 (ocv_target_include_directories)
  cmake/OpenCVModule.cmake:1207 (ocv_target_include_modules)
  modules/core/CMakeLists.txt:71 (ocv_add_accuracy_tests)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


CMake Error at cmake/OpenCVUtils.cmake:266 (target_include_directories):
  Cannot specify include directories for target "opencv_test_core_FP16" which
  is not built by this project.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:672 (ocv_target_include_directories)
  cmake/OpenCVModule.cmake:1207 (ocv_target_include_modules)
  modules/core/CMakeLists.txt:71 (ocv_add_accuracy_tests)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


CMake Error at cmake/OpenCVUtils.cmake:266 (target_include_directories):
  Cannot specify include directories for target "opencv_test_core_FP16" which
  is not built by this project.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:672 (ocv_target_include_directories)
  cmake/OpenCVModule.cmake:1207 (ocv_target_include_modules)
  modules/core/CMakeLists.txt:71 (ocv_add_accuracy_tests)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


CMake Error at cmake/OpenCVUtils.cmake:266 (target_include_directories):
  Cannot specify include directories for target "opencv_test_core_FP16" which
  is not built by this project.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:672 (ocv_target_include_directories)
  cmake/OpenCVModule.cmake:1207 (ocv_target_include_modules)
  modules/core/CMakeLists.txt:71 (ocv_add_accuracy_tests)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)
