### ISSUE TITLE
[Proposal] Remove code for old compute capability

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#16649]
Now, OpenCV has code for old compute capability.

- https://github.com/opencv/opencv/blob/4.2.0/modules/core/include/opencv2/core/cuda/simd_functions.hpp#L95-L103
- https://github.com/opencv/opencv/blob/4.2.0/modules/core/include/opencv2/core/cuda/saturate_cast.hpp#L105-L107
- https://github.com/opencv/opencv/blob/4.2.0/modules/core/include/opencv2/core/cuda/scan.hpp#L196-L207

But, the latest CUDA Toolkit will stop to support old compute capability.  
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#deprecated-features

> * Support for the following compute capabilities are deprecated in CUDA 10.2. Note that support for these compute capabilities may be removed in a future release of CUDA. 
>   * sm_35 (Kepler)
>   * sm_37 (Kepler)
>   * sm_50 (Maxwell)

So, I think that OpenCV had better to remove code for old compute capability.
It's also effective in terms of maintenance.

**Comment by asmorkalov** [comment]
Users still use Jetson TX boards with Maxwell GPU, so I do not think that it's time to throw it away.

**Comment by atinfinity** [comment]
@asmorkalov Thank you for your reply. My opinion is as follows.

Maxwell generation has the following compute capability.  

- `sm_50`: GeForce GTX 750,  etc...
- `sm_52`: GeForce GTX 950,  GeForce GTX TITAN X etc...
- `sm_53`: Jetson TX1 etc...

https://developer.nvidia.com/cuda-gpus

> Users still use Jetson TX boards with Maxwell GPU, so I do not think that it's time to throw it away.

I have the same opinion as you.  
And, there is the following description in <https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#deprecated-features>.

> * Support for the following compute capabilities are deprecated in CUDA 10.2. Note that support for these compute capabilities may be removed in a future release of CUDA. 
>   * sm_35 (Kepler)
>   * sm_37 (Kepler)
>   * sm_50 (Maxwell)

Therefore, I think that there are two approaches.

- Removed code for Kepler<br>or
- Removed code for Maxwell(`sm_50`)
  - Expect `sm_52` and `sm_53`

**Comment by atinfinity** [comment]
@asmorkalov Please give me your opinion.

**Comment by asmorkalov** [comment]
@atinfinity I think that sm_50 support should be presumed, because it's still actively used on host systems.
