### ISSUE TITLE
Javascript fillConvexPoly Error

### ISSUE THREAD

**Issue by Penggggg** [opencv/opencv#16646]
- OpenCV => 4.2.0
- Operating System / Platform => Mac OS
- Compiler => VSCODE

##### Detailed description

when I Use `cv.fillConvexPoly` in Javascript, it got an Error like this:

`
Uncaught TypeError: Incorrect number of tuple elements for Scalar: expected=4, actual=3
` 

##### Steps to reproduce

Here's my code

```
let fillMaskMat = new cv.Mat( );
cv.fillConvexPoly( 
            // the imageMat from HTML input
            imgMat,
            // my other Mat 
            fillMaskMat,
            // points for an triangle
            [ 
                new cv.Point( 0, 0 ),
                new cv.Point( 0, 255 ),
                new cv.Point( 71, 152 ),
            ],
            // numbers for points
            3,
           // color
            new cv.Scalar( 1, 1, 1, 1 )
        )
```
PS: I can't find any doc `fillConvexPoly` **for Javascript** in [URL](https://docs.opencv.org/)

**Comment by dkurt** [comment]
I think that set of point should be wrapped in different data structure. Please take a look: https://github.com/opencv/opencv/blob/3fb6617d62abc104c60f521316aeb50eec18cde7/modules/js/test/test_imgproc.js#L273
