### ISSUE TITLE
using Gpu for dnn Face detection 

### ISSUE THREAD

**Issue by SaddamBInSyed** [opencv/opencv#16664]
Hi 
@YashasSamaga 

I successfully used my GPU for my object detection task.

Now I want to use my GPU for face detection too.

my current code below, 

`def detectFaceOpenCVDnn(net, frame):
    frameOpencvDnn = frame.copy()
    frameHeight = frameOpencvDnn.shape[0]
    frameWidth = frameOpencvDnn.shape[1]
    blob = cv2.dnn.blobFromImage(frameOpencvDnn, 1.0, (300, 300), [104, 117, 123], False, False)

    net.setInput(blob)
    detections = net.forward()
    bboxes = []
    for i in range(detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        if confidence > conf_threshold:
            x1 = int(detections[0, 0, i, 3] * frameWidth)
            y1 = int(detections[0, 0, i, 4] * frameHeight)
            x2 = int(detections[0, 0, i, 5] * frameWidth)
            y2 = int(detections[0, 0, i, 6] * frameHeight)
            bboxes.append([x1, y1, x2, y2])
            cv2.rectangle(frameOpencvDnn, (x1, y1), (x2, y2), (0, 255, 0), int(round(frameHeight/150)), 8)
    return frameOpencvDnn, bboxes
`

`DNN = "TF"
    if DNN == "CAFFE":
        modelFile = "res10_300x300_ssd_iter_140000_fp16.caffemodel"
        configFile = "deploy.prototxt"
        net = cv2.dnn.readNetFromCaffe(configFile, modelFile)
    else:
        modelFile = "opencv_face_detector_uint8.pb"
        configFile = "opencv_face_detector.pbtxt"
        net = cv2.dnn.readNetFromTensorflow(modelFile, configFile)
  
   # run on gpu 
   net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
    net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
`

But after setting the GPU flag the application seems still using CPU. (jetson nano)

please advise where I am wrong

**Comment by dkurt** [comment]
Please follow issue guideline if you want to report a bug. For usage questions please use a forum: https://answers.opencv.org/questions/

**Comment by YashasSamaga** [comment]
@SaddamBInSyed how did you verify that GPU wasn't being used? If one model can run on GPU, it's not possible that the other cannot run on the GPU. Either both run on GPU or none of them run on GPU.

You might get some useful information by setting `OPENCV_LOG_LEVEL` environment variable to `INFO` and then running your program.

**Comment by SaddamBInSyed** [comment]
@YashasSamaga 

Thanks for your response.
Yes it's using GPU but I couldn't sense more speed on Jetson nano

Thanks again

**Comment by YashasSamaga** [comment]
@SaddamBInSyed How did you measure the timings? Please show your full code including the part that measures the FPS/timings.

**Comment by dkurt** [comment]
Let's close it due no response from author. Feel free to reopen.
