### ISSUE TITLE
TrackerMOSSE_create cannot track objects

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#16669]
I use `cv2.TrackerMOSSE_create ()` to create tracker. Then use `tracker.update (frame) `to update, but there is no output result, and the object cannot be tracked.
envs: ubuntu
opencv-python 4.2.0.32
opencv-contrib-python 4.2.0.32
python27
opencv install via pip

But I can track objects when I use another environment. Of course track the same video, OTB Car4.
envs:
windows
opencv-contrib-python 4.2.0.32
opencv-python 4.0.0.21
python27

**Comment by alalek** [comment]
You can't install both of these packages:

- opencv-python
- opencv-contrib-python

We don't maintain these packages, so we can't help here.
Refer to documentation of these packages on PyPi.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
