### ISSUE TITLE
Mat copyTo with mask: copying to itself error

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#16676]
Windows 10, Opencv rev. 96b26dc8f485026ec432eb69bb5730dfbd71e014

Mat copyTo with mask argument dont work when Mat is copied into itself.
Test code:
````
Mat src = imread("d:/8.png"),
mask = imread("d:/7.png", IMREAD_GRAYSCALE);

imshow("src", src);
src.copyTo(src, mask);
imshow("res", src);
imshow("mask", mask);
waitKey(0);
````
Result.
src:
![1res](https://user-images.githubusercontent.com/6595124/75402250-03b71b00-590d-11ea-9596-e778b0cf077b.png)
res:
![2res](https://user-images.githubusercontent.com/6595124/75402251-044fb180-590d-11ea-94db-6485b97cf0d4.png)
mask:
![mask](https://user-images.githubusercontent.com/6595124/75402252-04e84800-590d-11ea-92be-e5f630cb2c6c.png)

UPD. `src.clone().copyTo(src, mask);` also does not work correctly.

**Comment by alalek** [comment]
> Mat copyTo with mask argument dont work when Mat is copied into itself

What is defined as "expected" result for that case?

---

Perhaps you want something like `src.setTo(Scalar::all(0), mask == 0);`

**Comment by Bleach665** [comment]
Expected result is
![2res_1](https://user-images.githubusercontent.com/6595124/75413088-3a049280-592d-11ea-89a1-85cf18ee3759.png)

We can obtain it using a crutch
````
Mat src = imread("d:/8.png"),
		mask = imread("d:/7.png", IMREAD_GRAYSCALE);

	imshow("1res", src);
	Mat t;
	src.copyTo(t, mask);
	src = t;
	imshow("2res", src);
	imshow("mask", mask);
	waitKey(0);
````

**Comment by alalek** [comment]
`.copyTo()` with mask updates masked values **only**.
It does nothing with other pixels (ignores them). It should NOT reset values outside of mask to zero as you expected.
Also there is some exception for empty `dst` (it is filled to zero before to avoid garbage) - but it is some kind of invalid usage and should be avoided.

**Comment by Bleach665** [comment]
> .copyTo() with mask updates masked values only.
Clear. Thanks.
