### ISSUE TITLE
 undefined reference to 'cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)'

### ISSUE THREAD

**Issue by JunWeston** [opencv/opencv#16678]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by saskatchewancatch** [comment]
@JunWeston Please help us out by providing reproduction steps, OpenCV version you built/used, OS, and compiler you used.

**Comment by JunWeston** [comment]
@saskatchewancatch 

System information (version)

- OpenCV => 4.2
- Operating System / Platform =>  Mac OS 10.14.6❔
- Compiler => android studio 3.5.1

Steps to reproduce

- step1: imread() // load a picture.
- step2: Canny() // to detect edges.
- step3: findContours() // to find contours.

Issue description

- when I am compile the code with android studio, the issue is produced, "undefined reference to 'cv::findContours", but imread() and Canny() don't have any problem, the three functions are included in the same file " improc.hpp"

**Comment by alalek** [comment]
Can't reproduce.
Try to build OpenCV Android samples first (from SDK).

Perhaps you have mess with headers (from other OpenCV version) or misconfigured linker options.

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by lsgmkk** [comment]
> @saskatchewancatch
> 
> System information (version)
> 
> * OpenCV => 4.2
> * Operating System / Platform =>  Mac OS 10.14.6❔
> * Compiler => android studio 3.5.1
> 
> Steps to reproduce
> 
> * step1: imread() // load a picture.
> * step2: Canny() // to detect edges.
> * step3: findContours() // to find contours.
> 
> Issue description
> 
> * when I am compile the code with android studio, the issue is produced, "undefined reference to 'cv::findContours", but imread() and Canny() don't have any problem, the three functions are included in the same file " improc.hpp"

Have you solved the problem? I have the same problem now

**Comment by saskatchewancatch** [comment]
@lsgmkk I'm not set up to look into Android issues unfortunately. I haven't looked into this.

**Comment by lsgmkk** [comment]
@saskatchewancatch oh ,  I found a solution，In higher versions,  Android ndk APP_STL is c ++ _ static, but opencv seems to use gnustl_static, so lowering the ndk version and configuring it can solve this problem, the configuration is as follows:

![image](https://user-images.githubusercontent.com/20055808/76156138-cc2c4800-6130-11ea-8f72-821ba05fe1ad.png)
![image](https://user-images.githubusercontent.com/20055808/76156146-eebe6100-6130-11ea-92fc-227d1d0051f6.png)

Link to solution ： https://blog.csdn.net/u014159143/article/details/89011091
android ndk link : https://developer.android.com/ndk/guides/cpp-support.html
so might opencv use c ++ share to compile again?

**Comment by alalek** [comment]
> so might opencv use c ++ share to compile again?

OpenCV already using `c++_shared` by default.
- 4.2.0 package build logs: http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/11032
- Changed in this PR: #15024

P.S. `gnustl` stuff is deprecated in modern NDKs. GCC has been removed. Check NDK r18 notes here: https://developer.android.com/ndk/downloads/revision_history

**Comment by genasn** [comment]
Hi,

 I also encountered same phenomenon, so I posted here.
The detail is the following.

OpenCV => 4.5.4 (installed by "aptget install libopencv-xxx-dev" command) 
Operating System / Platform => Ubuntu 22.04.3 LTS
Compiler => gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

I was build INDIGO, by following https://www.indigo-astronomy.org/for-developers.html.
Note that I replaced QHY SDK under the indigo_drivers/ccd_qhy2/bin_externals/  latest one (https://www.qhyccd.com/file/repository/publish/SDK/231011/sdk_Arm64_23.10.11.tgz).

As a result, build generated many errors related "undefined reference" related OpenCV.
So, I added -lopencv_xxx in indigo_drivers/ccd_qhy2/Makefile.inc to solve it.
That was almost of good, however, last one symbol couldn't be found from any modules.

/usr/bin/ld: bin_externals/qhyccd/lib/Linux/arm64//libqhyccd.a(qhyccdimgprocess.cpp.o): in function `QHYBASE::function_ImageStabilization(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned char*, void*)':
qhyccdimgprocess.cpp:(.text+0x3464): undefined reference to `cv::findContours(cv::_InputOutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)'

More detailed log is attached.
[log.txt](https://github.com/opencv/opencv/files/13465915/log.txt)

I understand that this may not be OpenCV's issue, however, could you advise me from the OpenCV's perspective?
I notice that previous SDK(23.09.06) is working without linking OpenCV.
