### ISSUE TITLE
imread JPEG support is broken when cross-compiling for Windows

### ISSUE THREAD

**Issue by mtamburrano** [opencv/opencv#16696]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Windows 64 Bit
- Compiler => x86_64-w64-mingw32-g++-posix

##### Detailed description

I've cross compiled a static version of opencv for Windows from Linux with just 3 modules enabled:
- core
- imgproc
- imgcodecs

All the optional flags are OFF except -DBUILD_JPEG and -DWITH_JPEG that are both ON.
The building process fails when creating the object `grfmt_jpeg.cpp.o` because there is a double definition of `boolean`:
```
In file included from /home/pompolus/src/opencv_4.2.0/3rdparty/libjpeg-turbo/src/jpeglib.h:31:0,
                 from /home/pompolus/src/opencv_4.2.0/modules/imgcodecs/src/grfmt_jpeg.cpp:76:
/home/pompolus/src/opencv_4.2.0/3rdparty/libjpeg-turbo/src/jmorecfg.h:242:13: error: conflicting declaration ‘typedef int boolean’
 typedef int boolean;
             ^~~~~~~
/home/pompolus/src/opencv_4.2.0/modules/imgcodecs/src/grfmt_jpeg.cpp:69:23: note: previous declaration as ‘typedef unsigned char boolean’
 typedef unsigned char boolean;
```
To overcome that issue I tried to add
```
#define HAVE_BOOLEAN
```
in `grfmt_jpeg.cpp` before including `jmorecfg.h`.
With that fix the build process succeed and the static libraries are produced.

Anyway when linking against those libraries, the `cv::imread` fails, it returns an empty `cv::Mat`. I used different valid jpeg images to test it, it always fails.

Then I rebuilt the libraries with  -DBUILD_PNG=ON and -DWITH_PNG=ON and switched jpeg images with png images. Everything works fine, the `cv::imread` can correctly load the images into a `cv::Mat`.

Any ideas how to correctly add support for jpeg images when building for Windows?

**Comment by alalek** [comment]
> mingw32

No official support. Community support only.

---

On Windows we recommend to use MSVS 2015+ compiler.
`HAVE_BOOLEAN` is handled here:
https://github.com/opencv/opencv/blob/db5f1c35540df1ed0771571a321c249edf0e347f/3rdparty/libjpeg-turbo/jconfig.h.win.in#L27

You may try to update CMake scripts for MinGW and try to use `jconfig.h.win.in`

**Comment by mtamburrano** [comment]
thank you @alalek 
I rebuilt the library with the WIN32 CMake variable ON (so the file you pointed out would be used) and everything works, JPEG support is back.

Issue can be closed, thank you again
