### ISSUE TITLE
Built-in FFmpeg support broken

### ISSUE THREAD

**Issue by justinboneh** [opencv/opencv#16703]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Linux x86 (cross compiling to ARMv7)
- Compiler => GNU 8.2.1

##### Detailed description
https://github.com/opencv/opencv/blob/8808aaccffaec43d5d276af493ff408d81d4593c/modules/videoio/cmake/detect_ffmpeg.cmake#L27
`PKG_CONFIG_FOUND` here is always false, since `include(FindPkgConfig)` was never called after the fix in https://github.com/opencv/opencv/pull/14426.

##### Steps to reproduce
Run cmake with `-DWITH_FFMPEG=ON` after setting the environment variable `PKG_CONFIG_PATH` to the target dir.
Result:  
```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
```
After adding `include(FindPkgConfig)`:
```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (58.54.100)
--       avformat:                  YES (58.29.100)
--       avutil:                    YES (56.31.100)
--       swscale:                   YES (5.5.100)
--       avresample:                NO
```

**Comment by alalek** [comment]
Unconditional `include(FindPkgConfig)` during cross-compilation should not be called:
- it may find "host" pkgconfig (CMake's FindPkgConfig doesn't care about that). Like it finds host "git" or other tools.
- misconfigured "pkgconfig" finds invalid "host" packages

You can still enable pkgconfig on cross-compiling mode with:
-  setting of `PKG_CONFIG_SYSROOT_DIR` or `PKG_CONFIG_LIBDIR` environment variables. Usually it is done by toolchain setupenv scripts (examples: [1](https://autotools.io/pkgconfig/cross-compiling.html), [2](https://wiki.yoctoproject.org/wiki/How_to_Build_Target_Application_in_the_Host_Machine))
- or forcing `OPENCV_ENABLE_PKG_CONFIG=ON` CMake variable (it is user responsibility to check that weird items above doesn't happen).

You can propose patch to improve check "condition" during cross-compilation.
