### ISSUE TITLE
what's the correct meaning about timestamp in videocapture?

### ISSUE THREAD

**Issue by williamfzc** [opencv/opencv#16705]
hi

```python
import cv2

cap=cv2.VideoCapture("set/your/file/here")
w = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
cnt = cap.get(cv2.CAP_PROP_FRAME_COUNT)
print("Opencv width %d frames %d"%(w,cnt))

cap.read()
ts= cap.get(cv2.CAP_PROP_POS_MSEC)
print("ts @ frame 0 after read %.3f"%ts)
```

i have run this on my PC and got different results in different versions:

```text
after 4.1.2:
ts @ frame 0 after read 0.000

before 4.1.1:
ts @ frame 0 after read 40.000
```

so i am a little confused.

- which one is (will be) correct in the future?
- what is the actual meaning of these timestamps? (start time ? end time ? )

thanks

**Comment by alalek** [comment]
Don't open new duplicated issues.
See comments above your https://github.com/opencv/opencv/issues/15749#issuecomment-584501862
