### ISSUE TITLE
DNN : cannot set GPU device

### ISSUE THREAD

**Issue by pfeatherstone** [opencv/opencv#16725]
Is there a way of setting the GPU device ID in the DNN module?

**Comment by dkurt** [comment]
@pfeatherstone, There is already a way to select OpenCL device by environment: https://github.com/opencv/opencv/wiki/OpenCL-optimizations (`OPENCV_OPENCL_DEVICE`). do you mean NVIDIA GPU?

**Comment by pfeatherstone** [comment]
Yes NVIDIA or CUDA device id

**Comment by YashasSamaga** [comment]
@pfeatherstone 

To select a device in the code or to make use of multiple GPUs, refer to [this comment](https://github.com/opencv/opencv/pull/14827#issuecomment-536204605).

To control the CUDA device which has to be used by an application, use [`CUDA_VISIBLE_DEVICES`](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars) environment variable.

**Comment by pfeatherstone** [comment]
Thank you. Didn't know you could call "cv::cuda::setDevice"

**Comment by pfeatherstone** [comment]
On a similar note, is there a way of loading a cv::Mat to GPU before inference? I'm doing some batch loading on a separate thread, and would like that thread to also load memory to GPU

**Comment by YashasSamaga** [comment]
@pfeatherstone The DNN module as of now cannot accept inputs in GPU memory. It requires the input to be in the host and it internally copies the data to the GPU.

There is already a feature request issue for this #16433

**Comment by pfeatherstone** [comment]
Ok thank you
