### ISSUE TITLE
Where is the "LineSegmentDetectorImpl"?

### ISSUE THREAD

**Issue by nonlinear1** [opencv/opencv#16729]
When I use opencv 3.4.6 to extract lines. I was confronted with the runtime errors "terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.6) /home/manifold/software/opencv/modules/imgproc/src/lsd.cpp:139: error: (-213:The function/feature is not implemented) Implementation has been removed due original code license issues in function 'LineSegmentDetectorImpl' ". So the LineSegmentDetectorImpl is removed?
and How can I use the function "createLineSegmentDetector"?
Thank you very much!!

**Comment by alalek** [comment]
No way until we have another implementation compatible with BSD license.

**Comment by nonlinear1** [comment]
Thank you very much!
