### ISSUE TITLE
Try to use opencv load the onnx model has error

### ISSUE THREAD

**Issue by wawltor** [opencv/opencv#16728]
We use the paddle2onnx tools to convert the paddle model to onnx model, we use the onnx to check the model, just OK.
    import onnx
    onnx_model = onnx.load( 'model.onnx')
    onnx.checker.check_model(onnx_model)

But we use the opencv to load the onnx model, has the errors as follows
![image](https://user-images.githubusercontent.com/16698950/75843516-4cd80500-5e0e-11ea-877f-03280d9614ff.png)

Can you help me to fix the problem?
 Thank you!

**Comment by l-bat** [comment]
@wawltor  You issue should contain `model.onnx` to reproduce it. Can you upload the model to cloud?

**Comment by wawltor** [comment]
[shuffle_onnx.tar.gz](https://github.com/opencv/opencv/files/4286119/shuffle_onnx.tar.gz)
Here is my onnx model, maybe you need to change the model name to xxx.onnx.

**Comment by l-bat** [comment]
@wawltor Please check link to model. Page not found.

**Comment by wawltor** [comment]
[shuffle_onnx.tar.gz](https://github.com/opencv/opencv/files/4290567/shuffle_onnx.tar.gz)

**Comment by wawltor** [comment]
> [shuffle_onnx.tar.gz](https://github.com/opencv/opencv/files/4290567/shuffle_onnx.tar.gz)

@l-bat  I had upload the onnx model.

**Comment by l-bat** [comment]
@wawltor  Please try the changes from #16735.

**Comment by wawltor** [comment]
> @wawltor Please try the changes from #16735.
Thank you very much. But how can i get the fixed version ？

**Comment by wawltor** [comment]
> @wawltor Please try the changes from #16735.

@l-bat  Thank you very much. But how can i get the fixed version ？

**Comment by dkurt** [comment]
Please test the latest 3.4 branch. The changes will be ported to master branch soon.
