### ISSUE TITLE
object localisation in image from coord of bounding box with opencv

### ISSUE THREAD

**Issue by hamdii02** [opencv/opencv#16727]
I am working on a project where i want to detect specify which element is in the middle of the image.
to make it more clearer i want to detect multiple object in the image and to distinguish which one is in the middle of the image using the coordinates of bounding boxes.
Thanks

**Comment by dkurt** [comment]
Please use a forum for usage questions: http://answers.opencv.org/

We use GitHub issue for bug requests / feature proposals. Thanks!
