### ISSUE TITLE
Transfer SIFT to the main repository

### ISSUE THREAD

**Issue by ychechik** [opencv/opencv#16736]
As of the day after tomorrow (7.3.20) [the patent on SIFT will expire](https://patents.google.com/patent/US6711293) and so it should be free to use.

Moving it out of the non-free folder will enable all to compile opencv with default flags and still get SIFT (will also help for the python binding as it doesn't compile the non-free folder).

**Comment by vpisarev** [comment]
See https://github.com/opencv/opencv/wiki/GSoC_2020#idea-better-sift-in-the-main-repository

**Comment by alalek** [comment]
As a quick step in this way we can remove `#ifdef` guards with OPENCV_ENABLE_NONFREE for SIFT source code in opencv_contrib repository (without moving the code).

**Comment by saskatchewancatch** [comment]
@alalek @vpisarev , I attempted this in PR 2449 in opencv_contrib repository. It implements the "quick step" by moving SIFT out of non-free into free. I suppose the rest of the work involving moving it into opencv could be a later work for GSoC as per Vadim's suggestion.

**Comment by miloshavlicek** [comment]
Can I ask, when we can expect it to be included in a new release?
Thank you!

**Comment by alalek** [comment]
#17119 backlog:
- [ ] 2 disabled SIFT tests
- [ ] fix C++ compatibility? `cv::xfeatures2d::SIFT::create()` (problem is due MSVS ambiguous errors)
- [ ] fix Java bindings compatibility? `org.opencv.features2d.SIFT.create()`

**Comment by Zenos-Paradox** [comment]
If SIFT is now included in the packages, why do i get a `module 'cv2.cv2' has no attribute 'xfeatures2d'`  error when using the opencv-python pip package and a DEPRACATED error when trying with the opencv-contrib-python package? which should I use?

**Comment by towr** [comment]
@Zenos-Paradox
It looks like it's been moved. You should use `cv2.SIFT_create()`  instead of  `cv2.xfeatures2d.SIFT_create()` now. (`xfeatures2d` only exists in the contrib package, but sift is part of the main package now.)

**Comment by Zenos-Paradox** [comment]
Oh, alright. Thanks.

**Comment by HaiderAbasi** [comment]
For anyone still stuck...

SIFT was **not working** for me in OpenCV-contib-python **(Version 4.2.0.34)** either. 
Both of methods cv2.xfeatures2d.SIFT_create() and  cv2.SIFT_create() **Did not work!**

**What did work:**
pip install opencv-contrib-python==4.4.0.46

**OS** = Windows 10
**Python Version** = 3.8.10

**Comment by Byte247** [comment]
@HaiderAbasi what exactly did you do after installing opencv-contrib-python==4.4.0.46? Did you still use  cv2.xfeatures2d.SIFT_create() or cv2.SIFT_create() ?

**Comment by danielagam** [comment]
> @HaiderAbasi what exactly did you do after installing opencv-contrib-python==4.4.0.46? Did you still use cv2.xfeatures2d.SIFT_create() or cv2.SIFT_create() ?

cv2.xfeatures2d.SIFT_create() show warning so I use cv2.SIFT_create() and the warning disappeared.
