### ISSUE TITLE
can't use universal intrinsics

### ISSUE THREAD

**Issue by zanazakaryaie** [opencv/opencv#16732]
##### System information (version)
- OpenCV => 3.4.5
- Operating System / Platform => Linux 64 Bit
- Compiler => g++

##### Detailed description

I want to use universal intrinsics inside my code to accelerate some functions. So, I included the header file `<opencv2/core/hal/intrin.hpp>`. But the compiler says: 

> /usr/local/include/opencv2/core/hal/intrin_sse.hpp|2805|error: ‘CV_CPU_HAS_SUPPORT_SSE2’ was not declared in this scope|

This is strange. Because when I print `getBuildInformation()`, I get the following output which seems to support SSE.

> General configuration for OpenCV 3.4.5 =====================================
>   Version control:               unknown
> 
>   Extra modules:
>     Location (extra):            /home/zana/opencv3/opencv_contrib-3.4.5/modules
>     Version control (extra):     unknown
> 
>   Platform:
>     Timestamp:                   2020-01-30T13:54:14Z
>     Host:                        Linux 5.0.0-37-generic x86_64
>     CMake:                       3.10.2
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               RELEASE
> 
>   CPU/HW features:
>     Baseline:                    SSE SSE2 SSE3
>       requested:                 SSE3
>     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
>       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
>       SSE4_1 (6 files):          + SSSE3 SSE4_1
>       SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
>       FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
>       AVX (6 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
>       AVX2 (12 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
>       AVX512_SKX (1 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_SKX

**Comment by alalek** [comment]
This is internal OpenCV functionality (between OpenCV modules), so external using may be tricky.

> 3.4.5

You need modern OpenCV version and use "opencv2/core/simd_intrinsics.hpp" header instead.
Also you should take a look on `simd_basic.cpp` sample.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
