### ISSUE TITLE
ERROR: Downloading OpenCV on Raspberry PI Zero W

### ISSUE THREAD

**Issue by Kinggsg22** [opencv/opencv#16762]
make[2]: *** [modules/python3/CMakefiles/opencv_python3.dir/build.make:63: modules/python3/CMakefiles/opencv.python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7576: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

Getting these two errors after the 95% mark in the make.

*/I'm trying to make a school project, and I am very new to OpenCV. /*

**Comment by Kinggsg22** [comment]
In the build directory, I used: cmake -D CMAKE_BUILD_TYPE=RELEASE \ -D CMAKE_INSTALL_PREFIX=/usr/local \ -D INSTALL_C_EXAMPLES=ON \ -D INSTALL_PYTHON_EXAMPLES=ON \ -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.4.1/modules \ -D BUILD_EXAMPLES=ON ..

**Comment by dkurt** [comment]
Please fill bug report including all the logs, CMake summary, build configuration - is that cross compilation or native compilation?

**Comment by Kinggsg22** [comment]
it is native

**Comment by Kinggsg22** [comment]
ill try to fill in the logs as fast as possible

**Comment by Kinggsg22** [comment]
General configuration for OpenCV 3.4.1 =====================================
--   Version control:               unknown
--
--   Platform:
--     Timestamp:                   2020-03-08T23:34:30Z
--     Host:                        Linux 4.19.108+ armv6l
--     CMake:                       3.13.4
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               RELEASE
--
--   CPU/HW features:
--     Baseline:
--       requested:                 DETECT
--       disabled:                  VFPV3 NEON
--
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++11:                       YES
--     C++ Compiler:                /usr/bin/c++  (ver 8.3.0)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfp16-format=ieee -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfp16-format=ieee -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -mfp16-format=ieee -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         YES
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
--
--   OpenCV modules:
--     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java_bindings_generator ml objdetect photo python2 python3 python_bindings_generator shape stitching superres ts video videoio videostab
--     Disabled:                    js world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java viz
--     Applications:                tests perf_tests apps
--     Documentation:               NO
--     Non-free algorithms:         NO
--
--   GUI:
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.58.3)
--       GtkGlExt:                  NO
--     VTK support:                 NO
--
--   Media I/O:
--     ZLib:                        /usr/lib/arm-linux-gnueabihf/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/arm-linux-gnueabihf/libjpeg.so (ver )
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         /usr/lib/arm-linux-gnueabihf/libpng.so (ver 1.6.36)
--     TIFF:                        /usr/lib/arm-linux-gnueabihf/libtiff.so (ver 42 / 4.1.0)
--     JPEG 2000:                   /usr/lib/arm-linux-gnueabihf/libjasper.so (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 58.35.100)
--       avformat:                  YES (ver 58.20.100)
--       avutil:                    YES (ver 56.22.100)
--       swscale:                   YES (ver 5.3.100)
--       avresample:                NO
--     GStreamer:                   NO
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
--     gPhoto2:                     NO
--
--   Parallel framework:            pthreads
--
--   Trace:                         YES (built-in)
--
--   Other third-party libraries:
--     Lapack:                      NO
--     Eigen:                       NO
--     Custom HAL:                  YES (carotene (ver 0.0.1))
--     Protobuf:                    build (3.5.1)
--
--   NVIDIA CUDA:                   NO
--
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/pi/opencv-3.4.1/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
--
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.16)
--     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython2.7.so (ver 2.7.16)
--     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.16.2)
--     packages path:               lib/python2.7/dist-packages
--
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.7.3)
--     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.3)
--     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.16.2)
--     packages path:               lib/python3.7/dist-packages
--
--   Python (for build):            /usr/bin/python2.7
--
--   Java:
--     ant:                         NO
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
--
--   Matlab:                        NO
--
--   Install to:                    /usr/local
-- -----------------------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/opencv-3.4.1/build

**Comment by dkurt** [comment]
@Kinggsg22, do you really need to build OpenCV from source? Maybe OpenCV 3.2.0 from the `apt-get`  would be enough? (make sure if Raspbian Buster is used): https://packages.debian.org/source/stable/opencv

**Comment by Kinggsg22** [comment]
`[ 95%] Built target opencv_python2
[ 95%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:598:30: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"get", (PyCFunction)UMatWrapper_get, METH_NOARGS,
                              ^~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:601:33: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*, PyObject*, PyObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*, _object*, _object* ’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"handle", (PyCFunction)UMatWrapper_handle, METH_VARARGS | METH_KEYWORDS,
                                 ^~~~~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:604:39: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"isContinuous", (PyCFunction)UMatWrapper_isContinuous, METH_NOARGS,
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:607:38: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"isSubmatrix", (PyCFunction)UMatWrapper_isSubmatrix, METH_NOARGS,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:610:34: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"context", (PyCFunction)UMatWrapper_context, METH_NOARGS | METH_STATIC,
                                  ^~~~~~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:613:32: warning: cast between incompatible function types from ‘PyObject* (*)(cv2_UMatWrapperObject*)’ {aka ‘_object* (*)(cv2_UMatWrapperObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
         {"queue", (PyCFunction)UMatWrapper_queue, METH_NOARGS | METH_STATIC,
                                ^~~~~~~~~~~~~~~~~
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp: In function ‘bool pyopencv_to(PyObject*, T&, const char*) [with T = cv::String; PyObject = _object]’:
/home/pi/opencv-3.4.1/modules/python/src2/cv2.cpp:889:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     char* str = PyString_AsString(obj);
^Cmake[2]: *** wait: No child processes.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [CMakeFiles/Makefile2:7576: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Interrupt
`

**Comment by Kinggsg22** [comment]
I am using Rasbian Buster, but the tutorial that I was following built OpenCV natively

**Comment by Kinggsg22** [comment]
I needed to install OpenCV on my raspberry pi zero w for video processing. The project i am making is a NATCAR, which follows a line.

**Comment by dkurt** [comment]
@Kinggsg22, so please try to install OpenCV from the official distribution first. Can you try and update if it's really 3.2.0? (just print the log of `sudo apt-get update && sudo apt-get install -y libopencv-dev`).

**Comment by Kinggsg22** [comment]
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Fetched 15.0 kB in 3s (5,151 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libavresample-dev libdc1394-22-dev libexif-dev libexif-doc libgdcm2-dev libgphoto2-dev libilmbase-dev libopencv-calib3d-dev libopencv-contrib-dev libopencv-core-dev libopencv-features2d-dev libopencv-flann-dev libopencv-highgui-dev
  libopencv-imgcodecs-dev libopencv-imgproc-dev libopencv-ml-dev libopencv-objdetect-dev libopencv-photo-dev libopencv-shape-dev libopencv-stitching-dev libopencv-superres-dev libopencv-ts-dev libopencv-video-dev libopencv-videoio-dev
  libopencv-videostab-dev libopencv-viz-dev libopencv3.2-java libopencv3.2-jni libopenexr-dev libraw1394-dev libraw1394-tools libtbb-dev opencv-data
Suggested packages:
  opencv-doc libraw1394-doc tbb-examples libtbb-doc
The following NEW packages will be installed:
  libavresample-dev libdc1394-22-dev libexif-dev libexif-doc libgdcm2-dev libgphoto2-dev libilmbase-dev libopencv-calib3d-dev libopencv-contrib-dev libopencv-core-dev libopencv-dev libopencv-features2d-dev libopencv-flann-dev
  libopencv-highgui-dev libopencv-imgcodecs-dev libopencv-imgproc-dev libopencv-ml-dev libopencv-objdetect-dev libopencv-photo-dev libopencv-shape-dev libopencv-stitching-dev libopencv-superres-dev libopencv-ts-dev libopencv-video-dev
  libopencv-videoio-dev libopencv-videostab-dev libopencv-viz-dev libopencv3.2-java libopencv3.2-jni libopenexr-dev libraw1394-dev libraw1394-tools libtbb-dev opencv-data
0 upgraded, 34 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.7 MB of archives.
After this operation, 67.5 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libavresample-dev armhf 7:4.1.4-1+rpt7~deb10u1 [105 kB]
Get:2 http://mirrors.syringanetworks.net/raspbian/raspbian buster/main armhf libexif-dev armhf 0.6.21-5.1+deb10u1 [103 kB]
Get:3 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libexif-doc all 0.6.21-5.1+deb10u1 [277 kB]
Get:4 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libgdcm2-dev armhf 2.8.8-9 [262 kB]
Get:5 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libgphoto2-dev armhf 2.5.22-3 [837 kB]
Get:6 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libilmbase-dev armhf 2.2.1-2 [76.7 kB]
Get:7 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libtbb-dev armhf 2018~U6-4 [286 kB]
Get:8 http://mirrors.syringanetworks.net/raspbian/raspbian buster/main armhf libopencv-core-dev armhf 3.2.0+dfsg-6 [1,094 kB]
Get:9 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-flann-dev armhf 3.2.0+dfsg-6 [182 kB]
Get:10 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libraw1394-dev armhf 2.1.2-1+b1 [55.3 kB]
Get:11 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libdc1394-22-dev armhf 2.2.5-1 [130 kB]
Get:12 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-imgproc-dev armhf 3.2.0+dfsg-6 [947 kB]
Get:13 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-imgcodecs-dev armhf 3.2.0+dfsg-6 [134 kB]
Get:14 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-videoio-dev armhf 3.2.0+dfsg-6 [128 kB]
Get:15 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopenexr-dev armhf 2.2.1-4.1 [673 kB]
Get:16 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-highgui-dev armhf 3.2.0+dfsg-6 [45.2 kB]
Get:17 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-ml-dev armhf 3.2.0+dfsg-6 [284 kB]
Get:18 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-features2d-dev armhf 3.2.0+dfsg-6 [261 kB]
Get:19 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-calib3d-dev armhf 3.2.0+dfsg-6 [490 kB]
Get:20 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-objdetect-dev armhf 3.2.0+dfsg-6 [170 kB]
Get:21 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-photo-dev armhf 3.2.0+dfsg-6 [223 kB]
Get:22 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-video-dev armhf 3.2.0+dfsg-6 [152 kB]
Get:23 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-shape-dev armhf 3.2.0+dfsg-6 [82.2 kB]
Get:24 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-stitching-dev armhf 3.2.0+dfsg-6 [213 kB]
Get:25 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-superres-dev armhf 3.2.0+dfsg-6 [66.5 kB]
Get:26 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-videostab-dev armhf 3.2.0+dfsg-6 [128 kB]
Get:27 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-viz-dev armhf 3.2.0+dfsg-6 [172 kB]
Get:28 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-contrib-dev armhf 3.2.0+dfsg-6 [1,848 kB]
Get:29 http://mirrors.ocf.berkeley.edu/raspbian/raspbian buster/main armhf libopencv-ts-dev armhf 3.2.0+dfsg-6 [277 kB]
Get:30 http://raspbian.mirror.constant.com/raspbian buster/main armhf libopencv3.2-jni armhf 3.2.0+dfsg-6 [173 kB]
Get:31 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libopencv3.2-java all 3.2.0+dfsg-6 [401 kB]
Get:32 http://mirrors.syringanetworks.net/raspbian/raspbian buster/main armhf libopencv-dev armhf 3.2.0+dfsg-6 [198 kB]
Get:33 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libraw1394-tools armhf 2.1.2-1+b1 [37.3 kB]
Get:34 http://raspbian.mirror.constant.com/raspbian buster/main armhf opencv-data all 3.2.0+dfsg-6 [1,207 kB]
Fetched 11.7 MB in 16s (728 kB/s)
Extracting templates from packages: 100%
Selecting previously unselected package libavresample-dev:armhf.
(Reading database ... 169012 files and directories currently installed.)
Preparing to unpack .../00-libavresample-dev_7%3a4.1.4-1+rpt7~deb10u1_armhf.deb ...
Unpacking libavresample-dev:armhf (7:4.1.4-1+rpt7~deb10u1) ...
Selecting previously unselected package libexif-dev:armhf.
Preparing to unpack .../01-libexif-dev_0.6.21-5.1+deb10u1_armhf.deb ...
Unpacking libexif-dev:armhf (0.6.21-5.1+deb10u1) ...
Selecting previously unselected package libexif-doc.
Preparing to unpack .../02-libexif-doc_0.6.21-5.1+deb10u1_all.deb ...
Unpacking libexif-doc (0.6.21-5.1+deb10u1) ...
Selecting previously unselected package libgdcm2-dev.
Preparing to unpack .../03-libgdcm2-dev_2.8.8-9_armhf.deb ...
Unpacking libgdcm2-dev (2.8.8-9) ...
Selecting previously unselected package libgphoto2-dev:armhf.
Preparing to unpack .../04-libgphoto2-dev_2.5.22-3_armhf.deb ...
Unpacking libgphoto2-dev:armhf (2.5.22-3) ...
Selecting previously unselected package libilmbase-dev.
Preparing to unpack .../05-libilmbase-dev_2.2.1-2_armhf.deb ...
Unpacking libilmbase-dev (2.2.1-2) ...
Selecting previously unselected package libtbb-dev:armhf.
Preparing to unpack .../06-libtbb-dev_2018~U6-4_armhf.deb ...
Unpacking libtbb-dev:armhf (2018~U6-4) ...
Selecting previously unselected package libopencv-core-dev:armhf.
Preparing to unpack .../07-libopencv-core-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-core-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-flann-dev:armhf.
Preparing to unpack .../08-libopencv-flann-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-flann-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libraw1394-dev:armhf.
Preparing to unpack .../09-libraw1394-dev_2.1.2-1+b1_armhf.deb ...
Unpacking libraw1394-dev:armhf (2.1.2-1+b1) ...
Selecting previously unselected package libdc1394-22-dev:armhf.
Preparing to unpack .../10-libdc1394-22-dev_2.2.5-1_armhf.deb ...
Unpacking libdc1394-22-dev:armhf (2.2.5-1) ...
Selecting previously unselected package libopencv-imgproc-dev:armhf.
Preparing to unpack .../11-libopencv-imgproc-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-imgproc-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-imgcodecs-dev:armhf.
Preparing to unpack .../12-libopencv-imgcodecs-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-imgcodecs-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-videoio-dev:armhf.
Preparing to unpack .../13-libopencv-videoio-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-videoio-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopenexr-dev.
Preparing to unpack .../14-libopenexr-dev_2.2.1-4.1_armhf.deb ...
Unpacking libopenexr-dev (2.2.1-4.1) ...
Selecting previously unselected package libopencv-highgui-dev:armhf.
Preparing to unpack .../15-libopencv-highgui-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-highgui-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-ml-dev:armhf.
Preparing to unpack .../16-libopencv-ml-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-ml-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-features2d-dev:armhf.
Preparing to unpack .../17-libopencv-features2d-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-features2d-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-calib3d-dev:armhf.
Preparing to unpack .../18-libopencv-calib3d-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-calib3d-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-objdetect-dev:armhf.
Preparing to unpack .../19-libopencv-objdetect-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-objdetect-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-photo-dev:armhf.
Preparing to unpack .../20-libopencv-photo-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-photo-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-video-dev:armhf.
Preparing to unpack .../21-libopencv-video-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-video-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-shape-dev:armhf.
Preparing to unpack .../22-libopencv-shape-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-shape-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-stitching-dev:armhf.
Preparing to unpack .../23-libopencv-stitching-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-stitching-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-superres-dev:armhf.
Preparing to unpack .../24-libopencv-superres-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-superres-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-videostab-dev:armhf.
Preparing to unpack .../25-libopencv-videostab-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-videostab-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-viz-dev:armhf.
Preparing to unpack .../26-libopencv-viz-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-viz-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-contrib-dev:armhf.
Preparing to unpack .../27-libopencv-contrib-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-contrib-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-ts-dev:armhf.
Preparing to unpack .../28-libopencv-ts-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-ts-dev:armhf (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv3.2-jni.
Preparing to unpack .../29-libopencv3.2-jni_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv3.2-jni (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv3.2-java.
Preparing to unpack .../30-libopencv3.2-java_3.2.0+dfsg-6_all.deb ...
Unpacking libopencv3.2-java (3.2.0+dfsg-6) ...
Selecting previously unselected package libopencv-dev.
Preparing to unpack .../31-libopencv-dev_3.2.0+dfsg-6_armhf.deb ...
Unpacking libopencv-dev (3.2.0+dfsg-6) ...
Selecting previously unselected package libraw1394-tools.
Preparing to unpack .../32-libraw1394-tools_2.1.2-1+b1_armhf.deb ...
Unpacking libraw1394-tools (2.1.2-1+b1) ...
Selecting previously unselected package opencv-data.
Preparing to unpack .../33-opencv-data_3.2.0+dfsg-6_all.deb ...
Unpacking opencv-data (3.2.0+dfsg-6) ...
Setting up libexif-dev:armhf (0.6.21-5.1+deb10u1) ...
Setting up libgphoto2-dev:armhf (2.5.22-3) ...
Setting up libraw1394-dev:armhf (2.1.2-1+b1) ...
Setting up libavresample-dev:armhf (7:4.1.4-1+rpt7~deb10u1) ...
Setting up libopencv3.2-jni (3.2.0+dfsg-6) ...
Setting up opencv-data (3.2.0+dfsg-6) ...
Setting up libgdcm2-dev (2.8.8-9) ...
Setting up libexif-doc (0.6.21-5.1+deb10u1) ...
Setting up libraw1394-tools (2.1.2-1+b1) ...
Setting up libtbb-dev:armhf (2018~U6-4) ...
Setting up libilmbase-dev (2.2.1-2) ...
Setting up libdc1394-22-dev:armhf (2.2.5-1) ...
Setting up libopencv3.2-java (3.2.0+dfsg-6) ...
Setting up libopenexr-dev (2.2.1-4.1) ...
Setting up libopencv-core-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-flann-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-ml-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-ts-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-imgproc-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-viz-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-video-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-shape-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-photo-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-imgcodecs-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-videoio-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-superres-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-highgui-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-features2d-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-calib3d-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-objdetect-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-videostab-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-stitching-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-contrib-dev:armhf (3.2.0+dfsg-6) ...
Setting up libopencv-dev (3.2.0+dfsg-6) ...
Processing triggers for man-db (2.8.5-2) ...

**Comment by Kinggsg22** [comment]
This is the log

**Comment by dkurt** [comment]
@Kinggsg22, so that's seems fine for me. You have installed OpenCV 3.2.0 according to the logs. Is that applicable for your project?

For python version, just
```
sudo apt-get install -y python3-opencv
```
source: https://packages.debian.org/buster/python3-opencv

**Comment by Kinggsg22** [comment]
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /home/pi/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

**Comment by Kinggsg22** [comment]
when i try to test if it installed it gives me this error.

**Comment by dkurt** [comment]
Please follow one of the issues: from https://github.com/opencv/opencv/search?q=__atomic_fetch_add_8&type=Issues:

```
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3
```
instead of
```
python3
```

**Comment by Kinggsg22** [comment]
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.4.6'
>>>

**Comment by Kinggsg22** [comment]
Thank you soo much!!!

i used 
pip3 install opencv-python==3.4.6.27
