### ISSUE TITLE
cv2.Rodrigues fails to produce original rotation matrix from rotation vector

### ISSUE THREAD

**Issue by LukasBommes** [opencv/opencv#16778]
##### System information (version)
- OpenCV => opencv-python 4.2
- Operating System / Platform => Ubuntu 18.04

##### Detailed description

Mapping a rotation matrix to rotation vector and subsequent inverse mapping from rotation vector to rotation matrix with cv2.Rodrigues fails for the given example below.

##### Steps to reproduce

```
import numpy as np
import cv2
R = np.array([[ 0.02269121,  0.99974055, -0.00198294],
 [-0.99970877,  0.0227067,   0.00817137],
 [-0.00821428, -0.00179695, -0.99996465]])
print(R, R.shape)
r, _ = cv2.Rodrigues(R)
print(r, r.shape)
R_back, _ = cv2.Rodrigues(r)
print(R_back, R_back.shape)
```
Yields the following output on my machine
```
[[ 0.02269121  0.99974055 -0.00198294]
 [-0.99970877  0.0227067   0.00817137]
 [-0.00821428 -0.00179695 -0.99996465]] (3, 3)

[[-0.01459757]
 [ 0.00912514]
 [-2.92798567]] (3, 1)

[[-0.97723422  0.21190244  0.01051796]
 [-0.21196388 -0.97726416 -0.00510544]
 [ 0.00919697 -0.00721864  0.99993165]] (3, 3)
```
As can be seen, R and R_back are not the same matrix.

**Comment by catree** [comment]
Issue is in your rotation matrix:
```
print('det(R):\n', np.linalg.det(R))
```

> det(R):
> -0.999999992689

I think it is called reflection when the determinant of the rotation matrix is `-1`?

`Rodrigues` function works well I would say. It performs SVD decomposition to make the input rotation matrix orthogonal.

Anyway, look at SE3 / SO3 topics for more information on the subject.

**Comment by LukasBommes** [comment]
Thanks a lot for the hint, catree! I assumed it might have been due to rounding errors in my input matrix. Looks like, I need to revise my maths first.

**Comment by catree** [comment]
I don't think it is the numerical precision the issue.
Where did you get this `R` matrix from? For instance, if you are doing an ICP (Iterative Closest Point), you have to take care of the special case of reflection, [see for instance](https://johnwlambert.github.io/icp/).

Have a look at the [SLAM book](https://github.com/gaoxiang12/slambook-en) (Chapter 3 - 3D Rigid Body Motion, and Chapter 4 - Lie Group and Lie Algebra).
