### ISSUE TITLE
could not compile modules with gapi on android_ndk_r18b 

### ISSUE THREAD

**Issue by shixpGit** [opencv/opencv#16780]
Hi, 
  I just try to build opencv4.2.0 with gapi module on android-ndk, and i have build WITH_ADE=ON, but it seems unavailable, is there any solutions?

### the cmake configure info:
-   OpenCV modules:
--     To be built:                 calib3d core features2d flann highgui imgcodecs imgproc ml objdetect photo stitching video videoio world
--     Disabled:                    -
--     Disabled by dependency:      -
--     Unavailable:                 dnn gapi java js python2 python3 ts

### System information (version)
- OpenCV => 4.2.0

- Operating System / Platform => 
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

- Compiler => 
Android NDK:                   android-ndk-r18b (ver 18.1.5063045)
--     Android ABI:                 arm64-v8a
--     NDK toolchain:               aarch64-linux-android-clang
--     STL type:                    c++_static
--     Native API level:            26
--   Android SDK:                  android-sdk (tools:  build tools: )

############################
opencv/modules/gapi/cmakelist.txt, line: 10.

if(NOT TARGET ade)
  ocv_module_disable(gapi)
  return()
endif()
############################

The error I guess should be here, 
however, there is no this problem when I build it on ubuntu with gcc.

### Steps to reproduce

my cmake build option:

-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
-DANDROID_NDK=${ANDROID_NDK} \
-DANDROID_SDK=${ANDROID_SDK} \
-DANDROID_SDK_TOOLS=${ANDROID_SDK_TOOLS} \
-DANDROID_ABI=arm64-v8a \
-DANDROID_TOOLCHAIN=clang \
-DANDROID_PLATFORM=android-26 \
-DANDROID_NATIVE_API_LEVEL=android-26 \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=./opencv_4.2.0_android_install \
-DBUILD_opencv_world=ON \
-DBUILD_ANDROID_EXAMPLES=OFF \
-DBUILD_ANDROID_PROJECTS=ON \
-DBUILD_ANDROID_SERVICE=OFF \
-DBUILD_CUDA_STUBS=OFF \
-DBUILD_DOCS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_FAT_JAVA_LIB=OFF \
-DBUILD_JAVA=OFF \
-DBUILD_PACKAGE=ON \
-DOPENCV_FORCE_3RDPARTY_BUILD=ON \
-DBUILD_opencv_gapi=ON \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_TBB=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_WITH_DEBUG_INFO=ON \
-DBUILD_WITH_DYNAMIC_IPP=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DWITH_ADE=ON \
-DWITH_CUDA=OFF \
-DWITH_EIGEN=ON \
-DWITH_IMGCODEC_HDR=OFF \
-DWITH_IMGCODEC_PXM=OFF \
-DWITH_JPEG=ON \
-DWITH_LIBREALSENSE=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_OPENMP=OFF \
-DWITH_PNG=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_PTHREADS_PF=OFF \
-DWITH_TBB=OFF \
-DWITH_TIFF=OFF \
-DWITH_CLP=OFF \
-DWITH_OPENCL_SVM=OFF \
-DWITH_IMGCODEC_SUNRAS=OFF \
-DWITH_IMGCODEC_SUNRASTER:BOOL=OFF \
-DWITH_JASPER:BOOL=OFF \
-DWITH_QUIRC:BOOL=OFF \
-DWITH_WEBP:BOOL=OFF \
-DWITH_ITT=OFF \

**Comment by dmatveev** [comment]
Hi,

When G-API has been introduced, it required a higher version of the compiler than was bundled in the OpenCV CI for Android NDK. Since then, the G-API module is excluded from NDK builds: [example](https://pullrequest.opencv.org/buildbot/builders/master_noOCL-android/builds/11106/steps/cmake/logs/stdio)

**Comment by dmatveev** [comment]
What is your g++ version by the way?

**Comment by alalek** [comment]
> g++

Modern Android NDK uses Clang only.

**Comment by shixpGit** [comment]
> What is your g++ version by the way?

Hi, dmatveev, 
  thank you for response, as @alalek  said, my clang version is :
android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --version

Android (4751641 based on r328903) clang version 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://andr
oid.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by dmatveev** [comment]
@alalek do we have our OpenCV CI Buildbot updated to that NDK version? If yes, we could try enable Android support back and see if clang works now

**Comment by alalek** [comment]
OpenCV CI uses Android NDK 18b on the "master" branch. `WITH_ADE=ON` is specified in CMake scripts.

Related blocking code is [here](https://github.com/opencv/opencv/blame/dbb30134bc67a5ee4ee979d1cd1b96f2a8516043/modules/gapi/cmake/DownloadADE.cmake#L1-L4).

**Comment by alalek** [comment]
@shixpGit Could you please check the provided fix?

Prebuilt SDK package can be downloaded [here](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_pack_android/20200320-144127--11263/) (temporary link, will expire in few weeks).

**Comment by shixpGit** [comment]
> @shixpGit Could you please check the provided fix?
> 
> Prebuilt SDK package can be downloaded [here](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_pack_android/20200320-144127--11263/) (temporary link, will expire in few weeks).

I would like to verify this provided fix, and will update the result after my turtle speed downloading~
[OpenCV4Android   1%   4.14M  8.52KB/s    eta 8h 22m ]

**Comment by alalek** [comment]
Patch has been merged into "master". You can try to build package from the sources.

**Comment by shixpGit** [comment]
> Patch has been merged into "master". You can try to build package from the sources.

@alalek @dmatveev  
good news, I have successfully build libopencv_world.a with GAPI modules,  
from branch: master, 
commit: 760e9e0943158c418908c8b3a17eff1c90f315da

I have not yet verified that whether this libopencv_world.a would work in my program with gapi,  becasue it will cost some time, but it should be work correctly according to info showed below:

--   OpenCV modules:
--     To be built:                 calib3d core features2d flann gapi highgui imgcodecs imgproc ml objdetect photo stitching video videoio world

Thank both of you for supporting.

**Comment by dmatveev** [comment]
@shixpGit you're welcome! BTW, can you please explain your need in G-API for Android? Is there any specific use-case you're trying to enable?

**Comment by shixpGit** [comment]
> @shixpGit you're welcome! BTW, can you please explain your need in G-API for Android? Is there any specific use-case you're trying to enable?

@dmatveev  GAPI is the new feature in Opencv4, which I think should bring better performance. I'm just for exploring and learning it in my work related field, now there is no specific use-cases. :)

**Comment by dmatveev** [comment]
@shixpGit ok I see now. Thanks!
