### ISSUE TITLE
Opencv-python compiled by myself on ubuntu cannot open the camera

### ISSUE THREAD

**Issue by Hedgeee** [opencv/opencv#16808]
Opencv version 4.2

If you compile it yourself, you will get stuck at the step cap = cv2.VideoCapture (0)
The camera is there

Either cmake -D CMAKE_BUILD_TYPE = Release -D CMAKE_INSTALL_PREFIX = / usr / local -D OPENCV_EXTRA_MODULES = .. / opencv_contrib / modules -D WITH_LIBV4L = ON -D WITH_CUDA = OFF ...
Compile or cmake ../, are stuck
opencv has been loaded correctly

Using pip install is OK, but I need to modify the opencv source code

May I ask what parameter definition is needed, thank.

**Comment by dkurt** [comment]
@Hedgeee, we cannot help unless you provide all the details: OS, OpenCV commit hash, build summary:
```
import cv2 as cv
print(cv.getBuildInformation())
```
Have you tried to open a camera in C++?

**Comment by Hedgeee** [comment]
@dkurt Thank you for your suggestion, I used print (cv.getBuildInformation ()) to compare pip3 install opencv-python with my compiled opencv, and got the compilation options I needed: cmake -D WITH_GSTREAMER = OFF ../
