### ISSUE TITLE
cv2.TrackerCRST_create() not found error.

### ISSUE THREAD

**Issue by jesperboberg** [opencv/opencv#16801]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => MaxOs 10.13

After importing opencv (import cv2), i can't use the commands cv2.Tracker....
I have made sure to ONLY have opencv-contrib-python installed (uninstalled opencv-python using pip3). Still doesnt work though.

**Comment by 14thApostle** [comment]
The tracker in opencv is CSRT, not CRST.
Try using cv2.TrackerCRST_create()
