### ISSUE TITLE
Unexpected ouputs while dnn forward a tf frozen model

### ISSUE THREAD

**Issue by Yoopex** [opencv/opencv#16816]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 10, 64 Bit
- Compiler => pip install opencv

### These are my codes:

``import cv2
import os
import glob
import time

print(cv2.__version__)
files=glob.glob("D:/AI/datasets/coco2017/val2017/*")
print(files[1])
model_base_path = "D:\AI\models\mask_rcnn_inception_v2_coco_2018_01_28"
net = cv2.dnn.readNetFromTensorflow(os.path.join(model_base_path,"frozen_inference_graph.pb"), os.path.join(model_base_path,"maskrcnn.pbtxt"))

net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
t1 = time.time()
im = cv2.imread(files[1])
input = cv2.dnn.blobFromImage(im, swapRB=True)

net.setInput(input)

boxes, masks = net.forward(['detection_out_final', 'detection_masks'])

num_detections=boxes.shape[2]

print(num_detections)

t2 = time.time()

print(t2-t1)
``
Console outputs:
> 4.2.0

> D:/AI/datasets/coco2017/val2017\000000000285.jpg

> 100

> 1.4780211448669434

The maskrcnn model and pbtxt are downloaded from officical website in your pages.

The process is completed. But the outputs seems not.

The var "num_detections" returns: 100.

But there is only a bear in the image.

Is there any mistake I have made? or is there anyone who can help me to solve this problem?

Thanks in advance.

**Comment by YashasSamaga** [comment]
The network always outputs a fixed number of detections no matter how many objects are in your image. You need to filter out the good detections (high score) from the pool and also remove overlapping detections through Non-Max Suppression.

**Comment by Yoopex** [comment]
> The network always outputs a fixed number of detections no matter how many objects are in your image. You need to filter out the good detections (high score) from the pool and also remove overlapping detections through Non-Max Suppression.

Got it. Thanks.
