### ISSUE TITLE
install prefix option not working

### ISSUE THREAD

**Issue by jjYBdx4IL** [opencv/opencv#16813]
- OpenCV => 4.2
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.5.0/cmake 3.16

cmake -DCMAKE_INSTALL_PREFIX= cannot be used to perform a user installation into a non-standard (non-system) directory. Usually (ie. most other packages) this simply works by running "make DESTDIR=~/.local install".

* wrong rpath in libs
* wrong paths in pkg-config .pc files

**Comment by alalek** [comment]
> ~/

Use absolute paths instead.

> pkg-config .pc

Not maintained: #13154

**Comment by jjYBdx4IL** [comment]
Works if using only CMAKE_INSTALL_PREFIX.
