### ISSUE TITLE
Problem building OpenCV (DNN Cuda) with cmake

### ISSUE THREAD

**Issue by enjoykcc456** [opencv/opencv#16819]
Hi,

Recently, i tried to build opencv with the following Dockerfile:
[Dockerfile.txt](https://github.com/opencv/opencv/files/4336399/Dockerfile.txt)

But i wasn't able to do that due to this error of:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED) 
```
The log can be found here: 
[Log.txt](https://github.com/opencv/opencv/files/4336433/Log.txt)

It seems like cmake cant find the CuDNN. But, when i do checking for CuDNN, i can find it there.
```
root@46d57fefc577:/tf/root# apt list --installed | grep libcudnn*
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
libcudnn7/unknown,now 7.6.4.38-1+cuda10.1 ppc64el [installed,upgradable to: 7.6.5.32-1+cuda10.2]
```
```
root@46d57fefc577:/tf/root# ls /usr/lib/powerpc64le-linux-gnu/libcudnn*
/usr/lib/powerpc64le-linux-gnu/libcudnn.so.7  /usr/lib/powerpc64le-linux-gnu/libcudnn.so.7.6.4
```
Does anyone knows what can i do to make it works?

Thanks

**Comment by BadMachine** [comment]
@enjoykcc456 Try to add path entry: CUDNN_LIBRARY with your cudnn lib file path

**Comment by enjoykcc456** [comment]
Hi @BadMachine ,

Thanks for replying. Do you mean doing
`export CUDNN_LIBRARY=/usr/lib/powerpc64le-linux-gnu` or
`export CUDNN_INCLUDE_LIBRARY=/usr/lib/powerpc64le-linux-gnu` ?

I tried both but still the same error.
