### ISSUE TITLE
cv2.dnn; Why can't the program exit?

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#16815]
cv2.dnn; Why can't the program exit?
I am [learning ](https://www.learnopencv.com/deep-learning-based-object-detection-using-yolov3-with-opencv-python-c/)dnn module.I use the following code for object detection.
```
net = cv2.dnn.readNetFromDarknet (modelConfiguration, modelWeights)
blob = cv2.dnn.blobFromImage (frame, 1/255, (inpWidth, inpHeight), [0,0,0], 1, crop = False)
net.setInput (blob)
outs = net.forward (getOutputsNames (net)) #
```
But after running the code, the program cannot exit.
surroundings:
windows
opencv-python 4.2.0.32

**Comment by dkurt** [comment]
Please add information about the model. It can be heavy and computes long.

**Comment by zihaozhang9** [comment]
> Please add information about the model. It can be heavy and computes long.

yolov3tiny. No. After the network outputs the result, the program cannot exit normally.

**Comment by dkurt** [comment]
What does it mean exit normally? This way please provide a full code. The outputs are correct?

**Comment by zihaozhang9** [comment]
The output is not important. The important thing is that I can't exit normally on my win system.

![image](https://user-images.githubusercontent.com/21007783/76696870-39108680-66cb-11ea-93c3-1cf6df6d05a2.png)

I uploaded my [file ](https://drive.google.com/file/d/1S6uY-sxfy4pNsmMuZ7ONIi83ZVKIlEUU/view?usp=sharing)and thank you for your reply.

**Comment by dkurt** [comment]
Please try `sys.exit(0)`

**Comment by zihaozhang9** [comment]
> Please try `sys.exit(0)`

no work

**Comment by zihaozhang9** [comment]
Python how to use setLogLevel？After using model.forward, the program cannot exit.This seems to be a problem with python's [logging ](https://stackoverflow.com/questions/24816456/python-logging-wont-shutdown)module.

**Comment by zihaozhang9** [comment]
> Python how to use setLogLevel？After using model.forward, the program cannot exit.This seems to be a problem with python's [logging ](https://stackoverflow.com/questions/24816456/python-logging-wont-shutdown)module.

amazing! I have encountered this problem before and cannot use [log](https://github.com/opencv/opencv/issues/14535)

**Comment by zihaozhang9** [comment]
The process of opencv can be ended by another process！
````
import cv2
from multiprocessing import Process, Queue
import os

def run_proc(name,q):
    print('Run run_proc process %s (%s)...' % (name, os.getpid()))
    def getOutputsNames(model):
        layersNames = model.getLayerNames()
    cfg=yolov3.cfg'
    weights='yolov3.weights'
    model = cv2.dnn.readNetFromDarknet(cfg, weights)
    frame = cv2.imread('00043.jpg')
    blob = cv2.dnn.blobFromImage(frame, 1/255.0, (224, 224), [0,0,0], 1, crop=False)
    model.setInput(blob)
    outs = model.forward(getOutputsNames(model)) 
    print('fininsh detect ')
    q.put(0)
    print(name,q)
    
def finish_proc(name,q):
    print('Run finish_proc process %s (%s)...' % (name, os.getpid()))
    value = q.get(True)
    
if __name__=='__main__':
    q = Queue()
    print('Parent process %s.' % os.getpid())
    p = Process(target=run_proc, args=('run_proc',q))
    f = Process(target=finish_proc, args=('finish_proc',q))
    print('Child process will start.')
    f.start()
    p.start()
    f.join()
    p.terminate()
    print('Child process end.')


````
![image](https://user-images.githubusercontent.com/21007783/79176897-0970ad80-7e34-11ea-99b3-babd30c5c860.png)

**Comment by zihaozhang9** [comment]
Just use `os.kill (os.getpid (), signal.SIGTERM)`
