### ISSUE TITLE
CUDA Build Error with VS2019

### ISSUE THREAD

**Issue by ChrisChirs** [opencv/opencv#16829]
##### System information (version)

- OpenCV => :4.2.0:
- Operating System / Platform => :Windows 64Bit:
- Compiler => :Visual Studio 2019:
- CUDA => :10.2:

##### Detailed description

But I met a problem in this when I try to build OpenCV with CUDA : 
Visual Studio repeat out a warning message: "**C:/Users/${MyUserName}/OpenCV420/opencv/sources/modules/core/include\opencv2/core/cuda.hpp(723): warning : field of class type without a DLL interface used in a class with a DLL interface**" forever and could not complete the project to build next project.
Even though print such more than **10,000**  the same warning message like this.
I'm crazy and mad!
Please,Help me!
I need your help!
Thanks!
##### Issue submission checklist

 - [ ] I report the issue, it's not a question
 - [ ] I checked the problem with documentation, FAQ, open issues,
 - [ ] I updated to latest OpenCV version and the issue is still there

**Comment by BadMachine** [comment]
Hello! You are using release version or just latest source code?

**Comment by ChrisChirs** [comment]
> 你好！您使用的是发行版还是最新的源代码？
> 还有什么是contrib版本？

I use the **newest** source(**4.2.0**) and the version of contrib is **4.2.0**

**Comment by ChrisChirs** [comment]
and also,it print some garbled caused by **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\cuda_runtime_api.h**

**Comment by BadMachine** [comment]
@ChrisChirs release version of contrib or latest?

**Comment by ChrisChirs** [comment]
> @ChrisChirs release version of contrib or latest?

Yes

**Comment by BadMachine** [comment]
@ChrisChirs 
1st of all I advise you to use latest contrib version.
2nd - try to change CUDA version to 10.1

**Comment by hjiaozzz** [comment]
I came up the same problem as you got,But when I filtered up all the warnings ,I found that *.cu file is generated normally.so,Just ignore them . Building with CUDA takes so long time ,and THE warnings came up so much times
