### ISSUE TITLE
FileStorage does not handle properly an empty yml file

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#16823]
Under OpenCV 4.2.*, using cv::FileStorage to open an (invalid) empty yml file (0 bytes) results in resource leaking by not closing files properly.
With current 4.3.0 dev, there is even a crash by nullptr dereference when trying to check the BOM.

---

relates #16488

**Comment by alalek** [comment]
@chacha21 Thank you for the report!
Could you please take a look on #16895 ?

**Comment by chacha21** [comment]
I looked at #16895. It also fixes the resource leak, but it is not enough to fix the use case detailed below
So, adding a closeFile() before the CV_Error() tests in the current #16823 is still better for comfort

`
FILE* fp = fopen(filename.c_str(), "wb");//create empty file
 fclose(fp);
{//open a block
 cv::FileStorage fs;
 try{
   fs.open(filename, cv::FileStorage::FORMAT_YAML | cv::FileStorage::READ);
 }
 catch(std::exception& e){
   std::cout << "exception " << e.what() << std::endl;
 }
 int ul = unlink(filename.c_str());//won't unlink since the FileStorage is not yet destroyed
 if (ul != 0)
   std::cout << "cannot unlink" << std::endl;
}
 int ul = unlink(filename.c_str());//will now work since FileStorage is destroyed
 if (ul != 0)
   std::cout << "cannot unlink" << std::endl;
`

**Comment by alalek** [comment]
@chacha21 Do you have a plan to open PR with backported fix and tests?

**Comment by chacha21** [comment]
@alalek, I have no plan to fork and PR on previous versions, I focus on dev for now.
