### ISSUE TITLE
readNetFromCaffe2 ?

### ISSUE THREAD

**Issue by carr123** [opencv/opencv#16839]
Can cv2.dnn load caffe2 model, which has two *.pb file ？？
thanks

**Comment by alalek** [comment]
> This website is being deprecated - Caffe2 is now a part of PyTorch.
> https://caffe2.ai/

Priority low / wont fix.

**Comment by dkurt** [comment]
Please use [Caffe2 to ONNX](https://github.com/pytorch/pytorch/tree/master/caffe2/python/onnx) conversion. Caffe2 is depreceted.
