### ISSUE TITLE
Opencv fails to compile on Android NDK R19. It can pass on NDK R14. Please consult how to compile on NDK R19 correctly

### ISSUE THREAD

**Issue by ht1066608644** [opencv/opencv#16838]
Opencv fails to compile on Android NDK R19. It can pass on NDK R14. Please consult how to compile on NDK R19 correctly

**Comment by dkurt** [comment]
r20 works fine for me

**Comment by dkurt** [comment]
Closing it due no response from author. Feel free to reopen with additional details.
