### ISSUE TITLE
opencv with the camera framerate 120 FPS

### ISSUE THREAD

**Issue by wangwenfeng0** [opencv/opencv#16844]
I have a camera, its frame rate can be set 120 FPS, and its resolution is 640*480, but my process only get 60 FPS. How can I run my process with 120 FPS to get every frame of the camera. 
This is my process:

#include "opencv2/opencv.hpp"
#include <time.h>

using namespace cv;
using namespace std;

int main()
{
	// Start default camera
	VideoCapture video(0);

	video.set(cv::CAP_PROP_FOURCC, VideoWriter::fourcc('M', 'J', 'P', 'G'));
	video.set(cv::CAP_PROP_FRAME_HEIGHT, 640);
	video.set(cv::CAP_PROP_FRAME_WIDTH, 480);

	double fps = video.get(cv::CAP_PROP_FPS);
	// If you do not care about backward compatibility
	// You can use the following instead for OpenCV 3
	// double fps = video.get(CAP_PROP_FPS);
	cout << "Frames per second using video.get(CV_CAP_PROP_FPS) : " << fps << endl;

	// Number of frames to capture
	int num_frames = 120;

	// Start and end times
	time_t start, end;

	// Variable for storing video frames
	Mat frame;

	cout << "Capturing " << num_frames << " frames" << endl;

	// Start time
	time(&start);

	// Grab a few frames
	for (int i = 0; i < num_frames; i++)
	{
		video.read(frame);
	}

	// End Time
	time(&end);

	// Time elapsed
	double seconds = difftime(end, start);
	cout << "Time taken : " << seconds << " seconds" << endl;

	// Calculate frames per second
	fps = num_frames / seconds;
	cout << "Estimated frames per second : " << fps << endl;

	// Release video
	video.release();
	return 0;
}
![image](https://user-images.githubusercontent.com/16935291/76923027-41580400-690d-11ea-9c26-81a45863a560.png)

![image](https://user-images.githubusercontent.com/16935291/76923097-72d0cf80-690d-11ea-806c-7f01bd585c77.png)

**Comment by dkurt** [comment]
Hi! Can you please check which values are returned by cap.set?

Please also try to set CAP_V4L2 backend.

**Comment by wangwenfeng0** [comment]
yes, I have swap the width and height, thank you for your attention. 
this is my codes:
VideoCapture capture;
cout << capture.open(0, CAP_MSMF) << endl;
//cout << capture.open(0, CAP_DSHOW) << endl;

cout << "CAP_PROP_FOURCC: " << capture.set(CAP_PROP_FOURCC, VideoWriter::fourcc('M', 'J', 'P', 'G')) << endl;
cout << "CAP_PROP_FPS: " << capture.set(CAP_PROP_FPS, 120) << endl;
cout << "CAP_PROP_FRAME_WIDTH: " << capture.set(CAP_PROP_FRAME_WIDTH, 640) << endl;
cout << "CAP_PROP_FRAME_HEIGHT: " << capture.set(CAP_PROP_FRAME_HEIGHT, 480) << endl;
capture.set(cv::CAP_PROP_FORMAT, -1);
(1) when I use the CAP_MSMF mode, the output is:
![image](https://user-images.githubusercontent.com/16935291/76939847-1f25ac80-6934-11ea-92e1-5d106e916c54.png)
![image](https://user-images.githubusercontent.com/16935291/76939885-3369a980-6934-11ea-9b35-4f147b76c822.png)
(2)when I use the  CAP_DSHOW mode, the output is:
![image](https://user-images.githubusercontent.com/16935291/76939981-61e78480-6934-11ea-89fd-374fa8c989b6.png)
![image](https://user-images.githubusercontent.com/16935291/76939996-6a3fbf80-6934-11ea-8264-357c04483729.png)
(3) when I use the CAP_V4L2 mode, the camera will not be opened. If windows do not support it?

**Comment by dkurt** [comment]
@wangwenfeng0, you have not specified Windows in the issue description from the beginning.

We cannot help unless you provide all the details like camera model, connection type (USB 2.0, USB 3.0)?

> int num_frames = 120;

Is not reliable way to check that camera can perform with this number of FPS. Make it work at least 10 seconds.

**Comment by wangwenfeng0** [comment]
The camera's name is 'HD USB Camera' and is USB2.0 port,  it connects the PC's USB3.0 port. As your suggest, I have run 10 seconds and then to calculate the FPS, but the output is no different. I will find a camera with USB3.0 port to test it. Thank you for your reply.

**Comment by dkurt** [comment]
> HD USB Camera

Is not the model of camera, sorry.

Please provide more details or find similar questions at forum: https://answers.opencv.org/questions/. Here is bugs tracker which is required to fill the issue properly. Let me close issue for now.

**Comment by mshabunin** [comment]
@wangwenfeng0 , `VideoCapture` in OpenCV may not be the best way to capture high-FPS video since it adds an overhead and does not support async processing. The numbers you get include decoding from JPEG, copying of frame data (maybe more than once) and converting to BGR (presumably).

See also: #9084 and https://social.msdn.microsoft.com/Forums/en-US/32089784-0413-4882-9e62-0b45187c5b57/mediacapture-90fps-and-120fps-video-capture?forum=wpdevelop
