### ISSUE TITLE
Problems with readNetFromTensorflow

### ISSUE THREAD

**Issue by kochsebastian** [opencv/opencv#16856]
##### System information (version)

- OpenCV =>  3.4.3
- Operating System / Platform => Linux Ubuntu
- Tensorflow=> 1.15

##### Detailed description
What I did:
1. Trained Faster-R-CNN Inception V2 with Tensorflow Object Detection API
2. Generted frozen graph
3. Ran image inference in tf session
4. Used tf_text_graph_faster_rcnn.py script to generate .pbtxt from frozen graph and nn config
5. Tried to run OpenCV inference, but got FusedBatchNormV3 error
6. Replaced FusedBatchNormV3 with FusedBatchNorm in pbtxt
7. Tried to run OpenCV inference again, but got following error:
```
error                                     Traceback (most recent call last)
<ipython-input-23-d396e33b9f6d> in <module>
      8 print((rows,cols))
      9 cvNet.setInput(cv.dnn.blobFromImage(img, size=(900, 720), swapRB=True, crop=False))
---> 10 cvOut = cvNet.forward()
     11 
     12 for detection in cvOut[0,0,:,:]:

error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/dnn/src/layers/permute_layer.cpp:137: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'getMemoryShapes'
```

My Code:
```
import cv2 as cv

cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb','frcnn_frozen_inference_graph.pbtxt


')

img = cv.imread('data/warnbake/frames/329.jpg')
rows = img.shape[0]
cols = img.shape[1]
print((rows,cols))
cvNet.setInput(cv.dnn.blobFromImage(img, size=(1280, 1024), swapRB=True, crop=False))
cvOut = cvNet.forward()

for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.3:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        cv.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)

#cv.imshow('img', img)
#cv.waitKey()
```
[pbtxt file](https://drive.google.com/file/d/1bOKjhexunItDOV6JrpcA35_GJqhaUz1k/view?usp=sharing)
[frozen graph file](https://drive.google.com/file/d/179s3wfkW0Ltv2xMSzBDIaEJ-5JNa8Kz5/view?usp=sharing)
[nn config file](https://drive.google.com/file/d/1gY2uhGOwz5XmIgg20onSm4hyiFJwy8Ss/view?usp=sharing)

**Comment by dkurt** [comment]
> OpenCV => 3.4.3

Please try the latest [3.4](https://github.com/opencv/opencv/tree/3.4) or [master](https://github.com/opencv/opencv/tree/master) branch. Cannot reproduce it.

**Comment by kochsebastian** [comment]
@dkurt so it's working for you?
I used the tf_text_graph_faster_rcnn script from master but my OpenCV is set up by conda separately with version 3.4.3 Is that a problem?

**Comment by kochsebastian** [comment]
Different OpenCV version were the problem
