### ISSUE TITLE
JavaCameraView depecrated API

### ISSUE THREAD

**Issue by Ibernato93** [opencv/opencv#16861]
I am currently using JavaCameraView to enable flash. Unfortunately the APIs of camera1 is deprecated.
Is there another class that use camera2 api? 
I saw that there is javacamera2View but unfortunately it does not allow access to the camera.
Solutions?

**Comment by alalek** [comment]
> it does not allow access to the camera

What do you mean? Please provide some details

**Comment by Ibernato93** [comment]
> What do you mean? Please provide some detail

With JavaCameraView I can access the Camera mCamera (because it is protected) field and set the flash. Now the problem is that the API for enable flash is depecrated (camera2 or camerax is the best now).
In JavaCamera2 all fields are private and I have no way of accessing the camera in order to enable flash.

**Comment by alalek** [comment]
> all fields are private

I believe we can change some of them to "protected".
Feel free to propose PR for 3.4 branch.

**Comment by Ibernato93** [comment]
> > all fields are private
> 
> I believe we can change some of them to "protected".
> Feel free to propose PR for 3.4 branch.

I need this for enable flash
```
try {
    // Change some capture settings
    mPreviewRequestBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON);
    // Build new request (we can't just edit existing one, as it is immutable)
    mPreviewRequest = mPreviewRequestBuilder.build();
    // Set new repeating request with our changed one
    mCaptureSession.setRepeatingRequest(mPreviewRequest, mCaptureCallback, mBackgroundHandler);
} catch (CameraAccessException e) {
    e.printStackTrace();
}
```

**Comment by Ibernato93** [comment]
> > all fields are private
> 
> I believe we can change some of them to "protected".
> Feel free to propose PR for 3.4 branch.

so?
