### ISSUE TITLE
Forward input on cuda device crash

### ISSUE THREAD

**Issue by stereomatchingkiss** [opencv/opencv#16869]
##### System information (version)
- OpenCV => 4.3.0(448a5452d085ec39ef812bd5fd33bbde47c814bd)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017 64 bits
- Cuda => 10.1

##### Detailed description

Forward the input data on cpu work, but fail on gpu. Details can find in the issue #16476

[Link of the model](https://drive.google.com/file/d/1Bm8r0wdkSmLI3zpY9A3mvjKVnXEdQF68/view)

##### Steps to reproduce

```
#include <opencv2/core.hpp>
#include <opencv2/dnn.hpp>

#include <iostream>

using namespace std;

void switch_to_cuda(cv::dnn::Net &net)
{
    for(auto const &vpair : cv::dnn::getAvailableBackends()){
        if(vpair.first == cv::dnn::DNN_BACKEND_CUDA && vpair.second == cv::dnn::DNN_TARGET_CUDA){
            net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
            net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
            cout<<__func__<<":can switch to cuda"<<endl; //can switch to cuda
            break;
        }
    }
}

int main()
{
    cv::Mat input(128, 256, CV_32FC3);
    auto blob = cv::dnn::blobFromImage(input);
    cout<<__func__<<":blob get"<<endl;

    cout<<__func__<<":set input"<<endl;
    auto net = cv::dnn::readNetFromONNX("osnet_ain_x1_0.onnx");

    //switch_to_cuda(net); //crash if switch to cuda

    net.setInput(blob);
    cout<<__func__<<":forward"<<endl;
    net.forward();
    cout<<__func__<<":forward done"<<endl;

    std::cout<<__func__<<":forward done"<<std::endl;

    return 0;
}
```

Not error messages, guess there are some layers not supported by cuda yet?

**Comment by YashasSamaga** [comment]
Can you please post a backtrace from GDB? This will help confirm whether the crash is indeed from the ScaleLayer which PR16868 addresses.

```
main:blob get
main:set input
switch_to_cuda:can switch to cuda
main:forward
main:forward done
main:forward done
```

with #16868

**Comment by stereomatchingkiss** [comment]
> Can you please post a backtrace from GDB?

Developing on windows, but I would try with #16868 and tell you the results.

**Comment by stereomatchingkiss** [comment]
Can you please post a backtrace from GDB?

Developing on windows, but I would try with #16868 and tell you the results.

**Comment by YashasSamaga** [comment]
@stereomatchingkiss Not sure if you were subscribed to that PR. The PR has been merged. Can you please try running your model and confirm if the problem has been resolved?

**Comment by stereomatchingkiss** [comment]
> 
> 
> @stereomatchingkiss Not sure if you were subscribed to that PR. The PR has been merged. Can you please try running your model and confirm if the problem has been resolved?

Got it, thanks, will pull it and run, need a few hours to compile, please wait a while. 

ps : CUDA support of MVN is issue #16877?

**Comment by YashasSamaga** [comment]
@stereomatchingkiss Nope. That is not the PR.

MVN doesn't exist in the CUDA backend yet and there is no issue for it.  I'll make a PR for it in a week or two. For now, the CUDA backend will automatically fallback to the CPU version for MVN layer.

If you are interested in performance, you might be interested in #16877. A lot of fusion optimizations don't happen in your model.

**Comment by stereomatchingkiss** [comment]
> The PR has been merged. Can you please try running your model and confirm if the problem has been resolved?

Tried, still crash. You can check out the codes by "4dfa798e75898d6dcc449496713b6cd30882af55", "Merge pull request #16868 from YashasSamaga:cuda4dnn-scale-fix_and_improvements"

**Comment by stereomatchingkiss** [comment]
Sorry, it do work, lack the proper dll.Thanks

>you might be interested in #16877. A lot of fusion optimizations don't happen in your model.

Thanks, will track with this issue. Any tutorials you recommend to study cudnn and cuda? Would like to build the ability to solve this kind of issue by myself, thanks.
