### ISSUE TITLE
Other mask rcnn models show no detection in DNN

### ISSUE THREAD

**Issue by JoeHsiao** [opencv/opencv#16881]
OpenCV => 4.1.0.25
Operating System / Platform => Ubuntu 19.04
Compiler => Python 3.7.3

[Tensorflow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) provides 4 mask rcnn models (.pb). If I use "mask_rcnn_inception_v2_coco" and download the corresponding [.pbtxt](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt) from opencv DNN, [mask-rcnn.py](https://github.com/opencv/opencv/blob/master/samples/dnn/mask_rcnn.py) works perfectly.

That model runs fast but does not generate accurate masks so I just wanted to try other three mask rcnn models by downloading them, and generate corresponding .pbtxt(s) by running [tf_text_graph_mask_rcnn.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_mask_rcnn.py), with the "pipeline.config" coming with each model. 

I didn't see any error message during generation or running the main program, but there is no bounding box or mask in the resulting image.

**Comment by alalek** [comment]
DNN is highly evolving area. Avoid using of outdated releases (anything older than 3 months).
Try code from the "master" branch first if you want report an issue.

---

Provide complete minimal reproducer including input data (models, images) and expected results.

**Comment by dkurt** [comment]
Closing it due no response from author. Feel free to reopen once the reproducer is complete. Thanks!
