### ISSUE TITLE
cap.release() not releasing the camera after clicking the photo

### ISSUE THREAD

**Issue by abhishekkh47** [opencv/opencv#16929]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform =>Windows 10
- Compiler => Jupyter Notebook

##### Detailed description

i am able to click a photo using cv2 module but release() method is not working. The webcam light keeps on blinking

##### Steps to reproduce

```.py
import cv2
cap=cv2.VideoCapture(0)
s,p=cap.read()
cap.release()

**Comment by alalek** [comment]
> 3.4.2

Outdated version.

> Jupyter Notebook

Try without that - it hacks normal processing of native code in python.

**Comment by sabih411** [comment]
either the version is outdated 
or you can try this ->

import cv2
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    if (ret==False):
        continue
    cv2.imshow("video",frame)
    key_pressed= cv2.waitKey(1)&0XFF
    if(key_pressed==ord('q')&0XFF):
        break
cap.release()
cv2.destroyAllWindows()

//on pressing q the video stream loop will break

**Comment by tanumay-deb** [comment]
indentation pls
