### ISSUE TITLE
OpenCv read psd file from Adobe PhotoShop 

### ISSUE THREAD

**Issue by canghaiyunfan** [opencv/opencv#16923]
I want to read psd file (Adobe PhotoShop format) by OpenCV. Whether it is feasible? 
or is there an interface available for psd file?
Thanks for reply!

**Comment by alalek** [comment]
Not supported.
No plans to support that.

Use PhotoShop to export content into .png, .jpg or other formats first.

**Comment by canghaiyunfan** [comment]
Got it, thank you very much!

**Comment by vivasvan1** [comment]
Kindly close this issue as it seems to be solved for now.

**Comment by blue-j** [comment]
One possible solution for this is to extract the flattened full-size preview inside a PSD/PSB file when the user chooses "Maximize Compatibility."  You can extract it fairly easily, as a JPEG (and perhaps other formats?) and then continue operations.  That's what ImageMagick does with `magick filename.psd[0] extraction.jpg` 

The "[0]" indicates the embedded preview.  Were OpenCV to offer at least this level of support, many users could work with PSD/PSB files that are already in front of them.
