### ISSUE TITLE
MSYS2 build failure

### ISSUE THREAD

**Issue by skapix** [opencv/opencv#16935]
##### System information (version)
OpenCV => 4.2
Operating System / Platform => Windows 64 Bit
Compiler => MSYS2

##### Detailed description

Failed to build because it fails to find posix_memalign function, although HAVE_POSIX_MEMALIGN=1.

##### Steps to reproduce

```
git clone -b 4.2.0 --depth 1 https://github.com/opencv/opencv.git
cd opencv
mkdir build && cd build
cmake -DBUILD_DOCS=OFF     -DBUILD_EXAMPLES=OFF     -DWITH_LAPACK=OFF     -DBUILD_LIST=core,imgcodecs,imgproc,objdetect,videoio     -DBUILD_NEW_PYTHON_SUPPORT=OFF     -DBUILD_SHARED_LIBS=OFF     -DBUILD_TESTS=OFF     -DWITH_FFMPEG=OFF     -DWITH_ADE=OFF     -DBUILD_opencv_gapi=OFF     -DWITH_MSMF=OFF     -DWITH_OPENEXR=OFF ..
cmake --build .
```

Possible fix is to replace in cmake `check_symbol_exists` with `check_cxx_symbol_exists`

**Comment by mshabunin** [comment]
Why doesn't _check_symbol_exists_ work? _posix_memalign_ is a C-function, `HAVE_POSIX_MEMALIGN` variable will be enabled by cmake if this function is supported. Did you set C-compiler and environment correctly? Did you try to build in a clean build directory? Perhaps you can use a workaround: [-DOPENCV_ENABLE_MEMALIGN=OFF](https://github.com/opencv/opencv/blob/8d78400052c9e6b60374364163f234790251b8fb/CMakeLists.txt#L645-L654)

This platform is not officially supported, feel free to provide a patch if you think there is an error.

**Comment by skapix** [comment]
Here is the error
```
[ 57%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/bindings_utils.cpp.o
/home/Skap/inspera-fortknox/build/opencv/src/opencv-pe/modules/core/src/alloc.cpp: In function ‘void* cv::fastMalloc(size_t)’:
/home/Skap/inspera-fortknox/build/opencv/src/opencv-pe/modules/core/src/alloc.cpp:135:12: error: ‘posix_memalign’ was not declared in this scope
  135 |         if(posix_memalign(&ptr, CV_MALLOC_ALIGN, size))
      |            ^~~~~~~~~~~~~~
make[5]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:120: modules/core/CMakeFiles/opencv_core.dir/src/alloc.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/home/Skap/inspera-fortknox/build/opencv/src/opencv-pe-build'
make[4]: *** [CMakeFiles/Makefile2:1560: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[4]: Leaving directory '/home/Skap/inspera-fortknox/build/opencv/src/opencv-pe-build'
make[3]: *** [Makefile:180: all] Error 2
make[3]: Leaving directory '/home/Skap/inspera-fortknox/build/opencv/src/opencv-pe-build'
make[2]: *** [CMakeFiles/opencv-pe.dir/build.make:129: opencv/src/opencv-pe-stamp/opencv-pe-build] Error 2
make[2]: Leaving directory '/home/Skap/inspera-fortknox/build'
make[1]: *** [CMakeFiles/Makefile2:121: CMakeFiles/opencv-pe.dir/all] Error 2
make[1]: Leaving directory '/home/Skap/inspera-fortknox/build'
make: *** [Makefile:101: all] Error 2
```

Thank you, `-DOPENCV_ENABLE_MEMALIGN=OFF` works, but there are another errors. Will investigate further. I think, it's more issue of MSYS2, rather than opencv. Thank you for assistance!

P.S. Btw, with `-std=gnu++11` it finds `posix_memalign`

**Comment by lyfadvance** [comment]
The reason for this problem is that - D INSTALL_ C_ EXAMPLES=ON is enabled when cmake opencv。
