### ISSUE TITLE
Missing dependencies = Lapack & Blas Gsl & GslcBlas ,  I can't get cmake to find them

### ISSUE THREAD

**Issue by Davatron** [opencv/opencv#16931]
Hi all,

i am very new to C++.

I am using a `cmake <dir>` command and i get the below shown below. try as i might to install the packages missing or change dirs ..... no change... i appreciate any help.

Find below the Cmakelist.txt  content. 

The full package of what i am trying to do is found in the following link:
https://bitbucket.org/persiansph/sph/src/default/

`-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.25.28611.0
-- The CXX compiler identification is MSVC 19.25.28611.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
!!!!!!!!!!!!!!!!!!!!!!!! Missing dependencies = Lapack & Blas Gsl & GslcBlas !!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Dawit/Desktop/SPH/sph/test`

![image](https://user-images.githubusercontent.com/44058886/77901522-04323100-7280-11ea-90ac-0451ddfdc2d4.png)
CMakeList.txt
    `    
    CMAKE_MINIMUM_REQUIRED (VERSION 3.8)

    PROJECT                (test)

    INCLUDE (C:/Users/Dawit/Desktop/SPH/sph/Modules/FindPKG.cmake)

    SET(EXES 
    testt
    )

    FOREACH(var ${EXES})
        ADD_EXECUTABLE        (${var} "${var}.cpp")
        TARGET_LINK_LIBRARIES (${var} ${LIBS})
        SET_TARGET_PROPERTIES (${var} PROPERTIES COMPILE_FLAGS "${FLAGS}"     LINK_FLAGS "${LFLAGS}")
    ENDFOREACH(var)`

**Comment by alalek** [comment]
This is OpenCV issues tracker (you don't report an issue about OpenCV). Closing
