### ISSUE TITLE
Some questions about opencv4.2 of cuda

### ISSUE THREAD

**Issue by wangwenchao-job** [opencv/opencv#16937]
##### System information (version)

- OpenCV => :4.2:
- Operating System / Platform => :ubuntu 18.04:
- Compiler => :cmake:

##### Detailed description

I am currently investigating the opencv4.2 version of cuda. I have some questions and want to ask everyone, thank you in advance.

1、Are there any requirements for graphics cards when compiling cuda support?
My laptop graphics card is nvidia gtx 1050ti，When compiling, you need to set the value of cuda's computing power，But I didn't find the calculation capacity of 1050ti on the official website.The official website is:https://developer.nvidia.com/cuda-gpus#compute

Some information shows:
    1）Desktop computer requires graphics card greater than or equal to gtx1050
    2）Laptop requires graphics card greater than or equal to gtx1060
    3）cudnn needs to be greater than or equal to 7.5
Are these right？？

2、Do I always need pbtxt when calling pb files for inference? If not, when is it needed and not needed?

3、I can already use the detection model trained by Google api object_detection smoothly. If I get the model obtained by other methods, how should I use it. How to generate a pbtxt file if there is only a pb file and no pipeline file? Is there a reference document?

4、At this stage, using cuda version of opencv4.2 for network inference and tensorflow for inference, compare the two methods to see if they can get the same result. Functionally, does the current opencv have complete functions, and does it support some network layers or nodes? Is there some reference documentation?

There may be many questions, thanks again！

**Comment by wangwenchao-job** [comment]
Do you have any suggestions？Please help me.Thank you! @alalek

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
