### ISSUE TITLE
Compile error opencv_world

### ISSUE THREAD

**Issue by wangwenchao-job** [opencv/opencv#16958]
##### System information (version)

- OpenCV => :4.2.0:
- Operating System / Platform => :ubuntu 18:
- Compiler => :cmake :

##### Detailed description

When compiling CUDA version of OpenCV 4.2, I only want to generate a single so file, so I have opened the opencv_world option,A lot of errors have been reported.The last lines are：
modules/world/CMakeFiles/opencv_world.dir/build.make:55791: recipe for target 'modules/world/CMakeFiles/opencv_world.dir/__/dnn/misc/tensorflow/graph.pb.cc.o' failed
make[2]: *** [modules/world/CMakeFiles/opencv_world.dir/__/dnn/misc/tensorflow/graph.pb.cc.o] Error 1
CMakeFiles/Makefile2:4569: recipe for target 'modules/world/CMakeFiles/opencv_world.dir/all' failed
make[1]: *** [modules/world/CMakeFiles/opencv_world.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

What should I do? Please help me. Thank you very much

**Comment by Rubix982** [comment]
Hi!
Can you list down the steps you took to face this problem?
Would help me to recreate it on my machine.

From what I guess by your logs, I can see it is either missing the build of an object file ( failed compilation, for whatever reason ), or has a build dependency it can't seem to find.

Thanks for the issue!

**Comment by wangwenchao-job** [comment]
> Hi!
> Can you list down the steps you took to face this problem?
> Would help me to recreate it on my machine.
> 
> From what I guess by your logs, I can see it is either missing the build of an object file ( failed compilation, for whatever reason ), or has a build dependency it can't seem to find.
> 
> Thanks for the issue!

I'm sorry for the late reply. It's not easy for me to log in to GitHub. 

I'll update the steps later

**Comment by Rubix982** [comment]
@wangwenchao-job , sure take your time.

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job , sure take your time.

I'm back!
This is my step and error report.
![image](https://user-images.githubusercontent.com/57739867/78904903-d20aa580-7aaf-11ea-9414-0f7e8ad6505a.png)

![image](https://user-images.githubusercontent.com/57739867/78905064-ff575380-7aaf-11ea-91fa-83034ed0835a.png)

![image](https://user-images.githubusercontent.com/57739867/78905155-24e45d00-7ab0-11ea-8da5-6413790a8103.png)

![image](https://user-images.githubusercontent.com/57739867/78905204-3463a600-7ab0-11ea-9793-f62cb9989526.png)

![image](https://user-images.githubusercontent.com/57739867/78905255-480f0c80-7ab0-11ea-9792-c1f8c563566a.png)

**Here is my error message：**
CMake Warning at cmake/OpenCVUtils.cmake:1508 (add_library):
  Cannot generate a safe runtime search path for target opencv_world because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libpng16.so.16] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libtiff.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libpangocairo-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libcairo.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgio-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libpangoft2-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libpango-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgobject-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libglib-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libfontconfig.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libfreetype.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgthread-2.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libharfbuzz.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstbase-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstreamer-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstapp-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstriff-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstpbutils-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstaudio-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib
    runtime library [libgstvideo-1.0.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/jianzhi/anaconda3/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:929 (ocv_add_library)
  cmake/OpenCVModule.cmake:850 (_ocv_create_module)
  modules/world/CMakeLists.txt:60 (ocv_create_module)

This is an error when clicking the generate button when opencv_world is selected.

**Comment by Rubix982** [comment]
Alright! Give me a day or two, I'll look into it. Thank you for the info!

**Comment by alalek** [comment]
> anaconda3

I believe this is a reason of this issue.

**Comment by wangwenchao-job** [comment]
> > anaconda3
> 
> I believe this is a reason of this issue.

Yes, it's really Anaconda's problem！！！

I remove the anconda from the environment variable and close all terminals. If I don't close it, I will still find anaconda. Recompile, no errors.

Thank you again for your help！！！
