### ISSUE TITLE
Unabel to load ONNX model (Yolov3 trained with tensorflow2)

### ISSUE THREAD

**Issue by jackyvr** [opencv/opencv#16966]
##### Detailed description

I was trying to load an onnx model (model.onnx) to opencv with C++, but the following error was shown. I tried both v3.4.9 and v4.2, and they give the same error. It is a YoloV3 model first trained in tensorflow2 and then converted to onnx. Any suggestions how to resolve the problem? Thanks!

OpenCV(3.4.9) Error: Assertion failed (!tensor_proto.raw_data().empty() || !tensor_proto.float_data().empty() || !tensor_proto.double_data().empty() || !tensor_proto.int64_data().empty()) in cv::dnn::experimental_dnn_34_v15::getMatFromTensor, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 110

###### Code:
String model_name = "model.onnx";
Net net = readNetFromONNX(model_name);

**Comment by dkurt** [comment]
Please provide references to origin TensorFlow and ONNX models. We need it to reproduce and solve the problem.

**Comment by dkurt** [comment]
Let's close until we have the steps to reproduce the problem. Feel free to reopen.
