### ISSUE TITLE
Confusing versions of StereoMatcher in v4.2 documentation

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv#16976]
I'm browsing OpenCV 4.2 documentation, which shows two versions of `StereoMatcher` class:
1. `cv::StereoMatcher` declared in `opencv2/calib3d.hpp`
2. `cv::stereo::StereoMatcher` declared in `opencv2/stereo.hpp`

The second version seems to be an old one, no longer included in OpenCV 4.2. Is that accurate? Can someone remove it from v4.x documentation?

**Comment by alalek** [comment]
> cv::stereo::StereoMatcher

This one is from [opencv_contrib](https://github.com/opencv/opencv_contrib) repository, "stereo" module.

Documentation is built and published for both repositories.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by pauljurczak** [comment]
I see. I asked this question there a while ago (https://answers.opencv.org/question/228067/what-is-the-difference-between-cvstereostereomatchercompute-and-cvstereomatchercompute/) and had no response. Thanks for answering.
