### ISSUE TITLE
Some VideoCapture Constructors are missing in OpenCV4.3.0 Java wrapper.

### ISSUE THREAD

**Issue by utibenkei** [opencv/opencv#16988]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => Windows10  64 bits
- Compiler => Visual Studio 2017 64 bits

##### Detailed description

Some VideoCapture Constructors are missing in OpenCV4.3.0 Java wrapper.
**VideoCapture​(int index)
VideoCapture​(int index, int apiPreference)
VideoCapture​(java.lang.String filename)
VideoCapture​(java.lang.String filename, int apiPreference)**

4.2.0
https://docs.opencv.org/4.2.0/javadoc/org/opencv/videoio/VideoCapture.html
4.3.0
https://docs.opencv.org/master/javadoc/org/opencv/videoio/VideoCapture.html

Perhaps this commit is related to this issue ( #16246  - Added `explicit` to `VideoCapture` constructors with 2 arguments, 1 of them has default value ).

**Comment by alalek** [comment]
Thanks for the report!
Regression is confirmed for 4.3.0 release.

Bindings parser can't handle "explicit":

> // Return type 'explicit' is not supported, skipping the function

/cc @VadimLevin

**Comment by VadimLevin** [comment]
Thank you for information.
Python bindings are not affected.
I will add test for header parser, because it gives wrong information to generator and fix it ASAP.
