### ISSUE TITLE
"strange" formulas in the documentation

### ISSUE THREAD

**Issue by albert-github** [opencv/opencv#16987]
##### System information (version)
- OpenCV => 4.3.0-dev
- documentation

##### Detailed description

Some "strange" formulas in the documentation, I'll give the reference to the documentation page plus an image showing the problem (and when necessary some text).

1. https://docs.opencv.org/4.3.0/d0/dcc/tutorial_non_linear_svms.html: backslash
  ![error_01](https://user-images.githubusercontent.com/5223533/78499286-08fb5700-7750-11ea-87c2-7b246797d6a6.jpg)
  **affected**: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/d0/dcc/tutorial_non_linear_svms.html)
2. https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: remaining texttt command
  ![error_02](https://user-images.githubusercontent.com/5223533/78499365-8c1cad00-7750-11ea-98d7-4bff52a58328.jpg)
  **affected**: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/d4/d86/group__imgproc__filter.html)
3. https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: remaining texttt command
  ![error_03](https://user-images.githubusercontent.com/5223533/78499452-19600180-7751-11ea-96c2-fa0687ba5889.jpg)
  **affected**: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/d4/d86/group__imgproc__filter.html)
4. https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: different size underneath sum symbol
  ![error_04](https://user-images.githubusercontent.com/5223533/78499521-722f9a00-7751-11ea-9e73-95ce30e54bf9.jpg)
  **affected**: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/d4/d86/group__imgproc__filter.html#ga27c049795ce870216ddfb366086b5a04)
5. https://docs.opencv.org/4.3.0/d9/d0c/group__calib3d.html: probably missing some `\cdot` around the `E`
  ![error_05](https://user-images.githubusercontent.com/5223533/78499684-760fec00-7752-11ea-9877-385a9b6997b7.jpg)
  **affected**: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/d9/d0c/group__calib3d.html#ga246253dcc6de2e0376c599e7d692303a)
6. https://docs.opencv.org/4.3.0/da/dc5/group__gapi__filters.html: remaining texttt command
  ![error_06](https://user-images.githubusercontent.com/5223533/78499943-03a00b80-7754-11ea-8689-8ca7b1eacd7f.jpg)
  **affected**: [OpenCV 4.0.0](https://docs.opencv.org/4.0.0/da/dc5/group__gapi__filters.html#gaa37a58b30753913cbcc7f5425726dbd5)
7. https://docs.opencv.org/4.3.0/da/dc5/group__gapi__filters.html: different size underneath sum symbol
  ![error_07](https://user-images.githubusercontent.com/5223533/78499991-419d2f80-7754-11ea-88a5-5b8ee8a82733.jpg)
  **affected**: [OpenCV 4.0.0](https://docs.opencv.org/4.0.0/da/dc5/group__gapi__filters.html#ga7f2fc386cd3ecb074d65b3ad124f38eb)
8. https://docs.opencv.org/4.3.0/dc/d6b/group__video__track.html: twice warpMatrix
  ![error_08](https://user-images.githubusercontent.com/5223533/78500063-b4a6a600-7754-11ea-8dd3-0cb3d3740777.jpg)
  affected: [OpenCV 3.0.0](https://docs.opencv.org/3.0.0/dc/d6b/group__video__track.html)

**Comment by ganesh-k13** [comment]
Hi @alalek, I'll try to fix this.
