### ISSUE TITLE
OpenCV 4.3.0+OpenJPEG  fails to build

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#16998]
OpenCV => 4.3.0
Windows 64 Bit
Visual Studio 2017/2019

##### Detailed description

When trying to compile OpenCV with OpenJPEG support, a compilation error occurs.

##### Steps to reproduce

Default CMake, with OPENJPEG_DIR set to [path_to_openjpeg_distrib_downloaded_from_openjpeg.org]/OpenJPEG/2.3.1/[architecture]/lib/openjpeg-2.3

Build errors
VS2017 :
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(968): error C2679: '-' binaire : aucun opérateur trouvé qui accepte un opérande de partie droite de type 'const _Iter' (ou il n'existe pas de conversion acceptable)
        with
        [
            _Iter=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(144): note: est peut-être 'int cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(const cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> &)'
        with
        [
            InT=uint8_t
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(134): note: ou       'cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(int) const'
        with
        [
            InT=uint8_t
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(968): note: lors de la tentative de mise en correspondance de la liste des arguments '(const _Iter, const _Iter)'
        with
        [
            _Iter=ChannelsIt
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(975): note: voir la référence à l'instanciation de la fonction modèle 'int std::_Idl_distance1<_Checked,_Iter>(const _Iter &,const _Iter &,std::random_access_iterator_tag)' en cours de compilation
        with
        [
            _Checked=ChannelsIt,
            _Iter=ChannelsIt
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(2444): note: voir la référence à l'instanciation de la fonction modèle 'int std::_Idl_distance<_InIt,_Iter>(const _Iter &,const _Iter &)' en cours de compilation
        with
        [
            _InIt=ChannelsIt,
            _Iter=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(276): note: voir la référence à l'instanciation de la fonction modèle '_OutIt std::copy<ChannelsIt,_Ty>(_InIt,_InIt,_OutIt)' en cours de compilation
        with
        [
            _OutIt=OPJ_INT32 *,
            _Ty=OPJ_INT32 *,
            _InIt=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(287): note: voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMatImpl<uint8_t,OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<_Ty>> &&)' en cours de compilation
        with
        [
            _Ty=OPJ_INT32 *
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(721): note: voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMat<OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<_Ty>> &&)' en cours de compilation
        with
        [
            _Ty=OPJ_INT32 *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(968): error C2088: '-' : non conforme pour class
```

VS2019 :
```
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(248): message : voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyToMatImpl<uint16_t,const OPJ_INT32>(std::vector<const OPJ_INT32 *,std::allocator<const OPJ_INT32 *>> &&,cv::Mat &,uint8_t)' en cours de compilation
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,1): error C2679: '-' binaire : aucun opérateur trouvé qui accepte un opérande de partie droite de type 'const _Iter' (ou il n'existe pas de conversion acceptable)
        with
        [
            _Iter=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(144,21): message : est peut-être 'int cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(const cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> &)'
        with
        [
            InT=uint8_t
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(134,30): message : ou       'cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(int) const'
        with
        [
            InT=uint8_t
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,1): message : lors de la tentative de mise en correspondance de la liste des arguments '(const _Iter, const _Iter)'
        with
        [
            _Iter=ChannelsIt
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642): message : voir la référence à l'instanciation de la fonction modèle 'auto std::_Idl_distance<_InIt,_InIt>(const _Iter &,const _Iter &)' en cours de compilation
        with
        [
            _InIt=ChannelsIt,
            _Iter=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(276): message : voir la référence à l'instanciation de la fonction modèle '_OutIt std::copy<ChannelsIt,_Ty>(_InIt,_InIt,_OutIt)' en cours de compilation
        with
        [
            _OutIt=OPJ_INT32 *,
            _Ty=OPJ_INT32 *,
            _InIt=ChannelsIt
        ]
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(287): message : voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMatImpl<uint8_t,OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<OPJ_INT32 *>> &&)' en cours de compilation
E:\opencv-4.3.0\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(721): message : voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMat<OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<OPJ_INT32 *>> &&)' en cours de compilation
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,26): error C2672: 'std::_Get_unwrapped_n' : fonction correspondante surchargée introuvable
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): error C2893: La spécialisation du modèle de fonction 'decltype(auto) std::_Get_unwrapped_n(_Iter &&,const _Diff)' a échoué
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1182): message : voir la déclaration de 'std::_Get_unwrapped_n'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : Avec les arguments template suivants :
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : '_Iter=_OutIt &'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : '_Diff=void'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,24): error C2789: '_UDest' : un objet de type qualifié const doit être initialisé
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642): message : voir la déclaration de '_UDest'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3643,1): error C3536: '_UDest' : ne peut pas être utilisé avant d'avoir été initialisé
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,58): error C2088: '-' : non conforme pour class
Génération du projet "opencv_imgcodecs.vcxproj" terminée -- ÉCHEC.
```

**Comment by chacha21** [comment]
Same error with a x64 build

`Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,1): error C2679: '-' binaire : aucun opérateur trouvé qui accepte un opérande de partie droite de type 'const _Iter' (ou il n'existe pas de conversion acceptable)
1>        with
1>        [
1>            _Iter=ChannelsIt
1>        ]
1>E:\github\chacha21\opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(144,21): message : est peut-être '__int64 cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(const cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> &)'
1>        with
1>        [
1>            InT=uint8_t
1>        ]
1>E:\github\chacha21\opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(134,30): message : ou       'cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>> cv::`anonymous-namespace'::ChannelsIterator<cv::`anonymous-namespace'::ConstItTraits<InT>>::operator -(__int64) const'
1>        with
1>        [
1>            InT=uint8_t
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,1): message : lors de la tentative de mise en correspondance de la liste des arguments '(const _Iter, const _Iter)'
1>        with
1>        [
1>            _Iter=ChannelsIt
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642): message : voir la référence à l'instanciation de la fonction modèle 'auto std::_Idl_distance<_InIt,_InIt>(const _Iter &,const _Iter &)' en cours de compilation
1>        with
1>        [
1>            _InIt=ChannelsIt,
1>            _Iter=ChannelsIt
1>        ]
1>E:\github\chacha21\opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(276): message : voir la référence à l'instanciation de la fonction modèle '_OutIt std::copy<ChannelsIt,_Ty>(_InIt,_InIt,_OutIt)' en cours de compilation
1>        with
1>        [
1>            _OutIt=OPJ_INT32 *,
1>            _Ty=OPJ_INT32 *,
1>            _InIt=ChannelsIt
1>        ]
1>E:\github\chacha21\opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(287): message : voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMatImpl<uint8_t,OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<OPJ_INT32 *>> &&)' en cours de compilation
1>E:\github\chacha21\opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(721): message : voir la référence à l'instanciation de la fonction modèle 'void cv::`anonymous-namespace'::copyFromMat<OPJ_INT32>(const cv::Mat &,std::vector<OPJ_INT32 *,std::allocator<OPJ_INT32 *>> &&)' en cours de compilation
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,26): error C2672: 'std::_Get_unwrapped_n' : fonction correspondante surchargée introuvable
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): error C2893: La spécialisation du modèle de fonction 'decltype(auto) std::_Get_unwrapped_n(_Iter &&,const _Diff)' a échoué
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1182): message : voir la déclaration de 'std::_Get_unwrapped_n'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : Avec les arguments template suivants :
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : '_Iter=_OutIt &'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,1): message : '_Diff=void'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642,24): error C2789: '_UDest' : un objet de type qualifié const doit être initialisé
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3642): message : voir la déclaration de '_UDest'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3643,1): error C3536: '_UDest' : ne peut pas être utilisé avant d'avoir été initialisé
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1336,58): error C2088: '-' : non conforme pour class`

**Comment by mshabunin** [comment]
@chacha21 , please take a look at this patch: #17007
