### ISSUE TITLE
Resize problem for 5 channels image

### ISSUE THREAD

**Issue by attashe** [opencv/opencv#16994]
##### System information (version)

- OpenCV => 4.2.0.34
- Operating System / Platform => Ubuntu Server 18.04
- Python Version: 3.6.9
- Compiler: GCC 8.3.0

##### Detailed description

Crash while resize image with 5 channels

##### Steps to reproduce

>>> import numpy as np
>>> import cv2
>>> t = np.random.rand(1600, 1600, 5).astype(np.uint8)
>>> t = cv2.resize(t, (1024, 1024))
--------------
double free or corruption (out)
Aborted (core dumped)

##### Previous issues
This is an identical problem, but the problem reappears

https://github.com/opencv/opencv/issues/16501

**Comment by alalek** [comment]
> 4.2.0.34

You should wait for OpenCV 4.3.0 release through "pip".
