### ISSUE TITLE
windows: OpenCV 4.3.0 build failing on generating vs_version.rc using mingw-w64

### ISSUE THREAD

**Issue by deadprogram** [opencv/opencv#16990]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform =>  Windows 64-bit
- Compiler => mingw-w64 v7.3.0

##### Detailed description

Our current build script fails on our Appveyor CI build when we update to OpenCV 4.3.0. Not sure about the origin of this issue. Thanks for any help.

```
[ 43%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
gcc: error: long: No such file or directory
C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin\windres.exe: preprocessing failed.
mingw32-make[2]: *** [modules\core\CMakeFiles\opencv_core.dir\build.make:1265: modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
mingw32-make[1]: *** [CMakeFiles\Makefile2:3666: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
mingw32-make: *** [Makefile:162: all] Error 2
```

##### Steps to reproduce

See https://ci.appveyor.com/project/deadprogram/gocv/builds/31965264#L1242

**Comment by dkurt** [comment]
Please add full log including cmake step.

**Comment by alalek** [comment]
Please dump compiler command line options: `make VERBOSE=1`

> Allocator metrics storage type: 'long long'

Perhaps this one is related (see #16786). Try to pass:
```
cmake -DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int64_t ...
```

**Comment by deadprogram** [comment]
@dkurt here is the CMake step: https://github.com/hybridgroup/gocv/blob/feature/opencv-4.3.0/appveyor_build_opencv.cmd#L15

**Comment by deadprogram** [comment]
Hi @alalek adding the `-DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int64_t` option to CMAKE allows the build to complete.

If this is covered by #16786 then should I close this issue?

**Comment by alalek** [comment]
Feel free to propose patch with default value for mingw [here](https://github.com/opencv/opencv/blob/3.4.10/modules/core/CMakeLists.txt#L87) (to 3.4 branch).

---

> CMake generator:             MinGW Makefiles

Also it might that this CMake generator doesn't handle spaces in definitions well (this generator is used rarely with CMake).
Consider using "ninja" if it is supported by AppVeyor environment.

**Comment by deadprogram** [comment]
OK, sounds good. I will look into if there is a coherent patch I could submit, or possibly switching to ninja.

Now closing this issue, thanks very much @alalek and @dkurt for quick response.

**Comment by charlescookey** [comment]
> 
> 
> Hi @alalek adding the `-DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int64_t` option to CMAKE allows the build to complete.
> 
> If this is covered by #16786 then should I close this issue?

@alalek when in the cmake-gui , to add the entry, which type should i select (BOOL or STRING ). And should i check the value box. Thanks

**Comment by yiyayiyau** [comment]
Hi, @alalek , i used **mingw32-make** to build opencv3.4 and contrib and have an error like oben:**gcc error: No such file or directory** and then i have added   **OPENCV_ALLOCATOR_STATS_COUNTER_TYPE = int64_t** in cmake:
![Aaron Swartz](https://github.com/yiyayiyau/learnOpenCV/blob/master/cmake.png)
 and have another problem: ![Aaron Swartz](https://github.com/yiyayiyau/learnOpenCV/blob/master/opencv1.PNG)
Could you tell me what happends hier and how  to solve this problem? Thanks a lot.

**Comment by bknhatice** [comment]
Hi, @yiyayiyau i am getting the same errors. I could not find the solution.  Can you share if you found the solution? Thanks a lot.
