### ISSUE TITLE
Error compile opencv4/opencv2/xfeatures2d.hpp

### ISSUE THREAD

**Issue by ren1793753** [opencv/opencv#17003]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 18.04 64bit
- Compiler => catkin build

##### Detailed description

I was making " catkin build " for uni course, it gives me the following 

In file included from /home/ren/workspaces/labaigi_ws/src/srrg_core_ros/src/applications/rosbag_to_message_converter.cpp:39:0:
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:214:103: error: expected ‘;’ at end of member declaration
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                       ^
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:214:105: error: ‘CV_OVERRIDE’ does not name a type; did you mean ‘CV_VERSION’?
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                         ^~~~~~~~~~~
                                                                                                         CV_VERSION
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:218:59: error: expected ‘;’ at end of member declaration
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                           ^
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:218:61: error: ‘CV_OVERRIDE’ does not name a type; did you mean ‘CV_VERSION’?
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                             ^~~~~~~~~~~
                                                             CV_VERSION
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:965:92: error: ‘cv::FastFeatureDetector::DetectorType’ has not been declared
                       int threshold, bool nonmaxSuppression=true, cv::FastFeatureDetector::DetectorType type=FastFeatureDetector::TYPE_9_16);
                                                                                            ^~~~~~~~~~~~
In file included from /home/ren/workspaces/labaigi_ws/src/srrg_core_ros/src/applications/rosbag_to_message_converter_ext_cal.cpp:36:0:
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:214:103: error: expected ‘;’ at end of member declaration
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                       ^
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:214:105: error: ‘CV_OVERRIDE’ does not name a type; did you mean ‘CV_VERSION’?
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                         ^~~~~~~~~~~
                                                                                                         CV_VERSION
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:218:59: error: expected ‘;’ at end of member declaration
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                           ^
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:218:61: error: ‘CV_OVERRIDE’ does not name a type; did you mean ‘CV_VERSION’?
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                             ^~~~~~~~~~~
                                                             CV_VERSION
/usr/local/include/opencv4/opencv2/xfeatures2d.hpp:965:92: error: ‘cv::FastFeatureDetector::DetectorType’ has not been declared
                       int threshold, bool nonmaxSuppression=true, cv::FastFeatureDetector::DetectorType type=FastFeatureDetector::TYPE_9_16);

How could I solve this ? I downloaded from github both opencv-4.0.0 and opencv_contrib-4.0.0 .Thanks.

##### Steps to reproduce

catkin build, for install ROS with proper packages.

**Comment by frank0123** [comment]
@alalek Same error here. But with version 4.1.0. And this issue shouldn't be marked as invalid.
