### ISSUE TITLE
documentation: discontinue "opencv-python-tutroals"

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#17016]
This is about https://opencv-python-tutroals.readthedocs.io/
The source repo is https://github.com/abidrahmank/OpenCV2-Python-Tutorials
The corresponding blog with background info is http://opencvpython.blogspot.com/
> It was a great pleasure to work on this project. I thank my mentor, Mr. **Alexander Mordvintsev** for his help on this project. I also thank many OpenCV developers like **Gary Bradsky, Vadim Pisarevsky, Vincent Rabaud** etc. for their help.

This looks like the owner worked on improving official OpenCV docs in 2013 and meant to take the RTD site offline after that. It hasn't happened. Issues on the repo have been unaddressed for years.

Google ranks this site higher than docs.opencv.org for enough search terms. Newbies keep showing up, pointing at this site, wondering why they have a hard time using information with current OpenCV.

Could someone please see about contacting the owner of the repo and taking down the RTD site?

**Comment by alalek** [comment]
AFAIK, these tutorials are adopted for http://docs.opencv.org by this PR: #1488

**Comment by catree** [comment]
Maybe /cc @abidrahmank

---

I agree also that having multiple sources of documentation/tutorial is not a good thing, moreover when they are outdated.

For https://opencv-python-tutroals.readthedocs.io/en/latest/ easiest thing would be to somehow redirect all the pages to https://docs.opencv.org/ or to a common page that explains that this site is outdated, and with a link to the official OpenCV doc.
There is also a typo in the url: `opencv-python-tutroals` This can be prone to phishing.

For https://github.com/abidrahmank/OpenCV2-Python-Tutorials if it is no longer maintained it can be archived: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories

---

Other possibility is to add something like: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0348c/index.html

![image](https://user-images.githubusercontent.com/8229425/78812934-86330000-79cc-11ea-85c1-36c4d09935bb.png)

Sometimes I would like to have something like that for the OpenCV 2.4 documentation :smile:

**Comment by crackwitz** [comment]
Great news! I contacted "Read the Docs" and they were very helpful in switching that site to "abandoned" status.

**Comment by abidrahmank** [comment]
Hello @crackwitz ,
I am sorry, somehow I missed this discussion. But I remember around April last year, my friend who created the readthedocs page for this repo had discussed the removal of this doc and I had given the permission since everything is now available via opencv docs and better. I wonder why it took so long.

Anyway, thanks a lot for taking this initiative 👍

**Comment by amaniedu71** [comment]
Random note, but I prefer the Read The Docs format in some ways than the way docs.opencv.org 
More welcoming, I think. 
Anyways.
