### ISSUE TITLE
OpenCV Error: Image step is wrong (The matrix is not continuous, thus its number of rows can not be changed) in reshape

### ISSUE THREAD

**Issue by Shivani1796** [opencv/opencv#17031]
I tried to solve this error but unable to solve this one , I already saw many related post but unfortunately I could not solve this issue. 
If anyone knows about it then please help me .

```
`OpenCV Error: Image step is wrong (The matrix is not continuous, thus its number of rows can not be changed) in reshape, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp, line 1047
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:1047: error: (-13) The matrix is not continuous, thus its number of rows can not be changed in function reshape
`
```

**Comment by dkurt** [comment]
Please provide a reproducer

**Comment by Shivani1796** [comment]
Can you explain what you required ? I didn't understand the meaning of `Please provide a reproducer`

**Comment by dkurt** [comment]
How we can reproduce the error? Reproducer is a minimal code example which can trigger the problem.

**Comment by Shivani1796** [comment]
Thanks for the quick reply @dkurt 
I am trying odometry example code: 

`Mat E, R, t, mask ;
	E = findEssentialMat(points2, points1, focal, pp, RANSAC, 0.999, 1.0, mask) ;
	recoverPose(E, points2, points1, R, t, focal, pp, mask) ;

	Mat prevImage = img_2 ;
	Mat currImage ;
	vector<Point2f> prevFeatures = points2 ;
	vector<Point2f> currFeatures ;

	char filename[100] ;

	R_f = R.clone() ;
	t_f = t.clone() ;

	clock_t begin = clock() ;
	namedWindow("Road facing camera", WINDOW_AUTOSIZE) ;
	namedWindow("Road facing camera", WINDOW_AUTOSIZE) ; // Create a window for display.
	namedWindow("Trajectory", WINDOW_AUTOSIZE) ; 		// Create a window for display.
	moveWindow("Trajectory", 600, 600) ;

	Mat traj = Mat::zeros(1000, 1000, CV_8UC3) ;
	Mat traj1 = Mat::zeros(1000, 1000, CV_8UC3) ;
	auto groundScales = getAbsoluteScales();
	for (int numFrame = 2 ; numFrame < MAX_FRAME ; numFrame++)
	{

#ifdef kitti
		sprintf(filename, "%s%06d.png",IMAGES, numFrame);
#endif
#ifdef shivani_dir
		sprintf(filename, "%s%d.png",IMAGES, numFrame);
#endif
#ifdef cj_dir
		sprintf(filename, "%s%d.png",IMAGES, numFrame);
#endif



		getline(infile, line) ;
		getPosition(line, truthPosition) ;
		Mat currImage_c = imread(filename) ;
		cvtColor(currImage_c, currImage, COLOR_BGR2GRAY) ;
		vector<uchar> status ;
		featureTracking(prevImage, currImage, prevFeatures, currFeatures,status) ;

		E = findEssentialMat(currFeatures, prevFeatures, focal, pp, RANSAC,	0.999, 1.0, mask) ;
		recoverPose(E, currFeatures, prevFeatures, R, t, focal, pp, mask) ;

		Mat prevPts(2, prevFeatures.size(), CV_64F), currPts(2,currFeatures.size(), CV_64F) ;

		for (int i = 0 ; i < prevFeatures.size() ; i++)
		{
			//this (x,y) combination makes sense as observed from the source code of triangulatePoints on GitHub
			prevPts.at<double>(0, i) = prevFeatures.at(i) . x ;
			prevPts.at<double>(1, i) = prevFeatures.at(i) . y ;

			currPts.at<double>(0, i) = currFeatures.at(i) . x ;
			currPts.at<double>(1, i) = currFeatures.at(i) . y ;
		}


		//scale = getAbsoluteScale(numFrame, 0, t.at<double>(2), &cur_x, &cur_y) ;
		scale = groundScales[numFrame];
`

Here, I have given image path to read image folder ,but in this it only work for some images and after that it gives error message. (Opencv Error: #17031)

According to me this part of code is producing the error. 
Thanks .
