### ISSUE TITLE
Can not load simple frozen pb file with readNetFromTensorflow. get error at net.forward

### ISSUE THREAD

**Issue by johnlee9501** [opencv/opencv#17032]
I tried to load a customerized frozen pb file in OpenCV (4.2.0) Visual C++ environment (VS2017) by doing following:

Net net = readNetFromTensorflow(modelWeights);

The error comes up when net.forward(outs, outNames);

The model is from mobileNet V1 architecture. I use TransformGraph to optimize the frozen pb model. In order to find the issue, I first TransformGraph the pb model to the output node just after the first conv layer after input. The program can run through net.forward.

When I TransformGraph the pb model to the second layer after DepthwiseConv2dNative convoluation layer, I can not go through net.forward and error appears. 
![image](https://user-images.githubusercontent.com/63490049/79037154-6db91600-7b83-11ea-88ac-10a3c6fbe6c5.png)

I need help to resolve this! Thanks

**Comment by dkurt** [comment]
Hi! Can you please a .pb file for experiment?

**Comment by johnlee9501** [comment]
[mobilenet_075_after1stDepthConv.zip](https://github.com/opencv/opencv/files/4464155/mobilenet_075_after1stDepthConv.zip)
moblilenet_075_after1stDepthConv.zip is not working

[mobilenet_075_before1stDepthConv.zip](https://github.com/opencv/opencv/files/4464156/mobilenet_075_before1stDepthConv.zip)
mobilenet_075_before1stDepthCovn.zip works.

**Comment by johnlee9501** [comment]
Any update? Thank you for help.

**Comment by dkurt** [comment]
Can you complete the issue providing input sizes for each of the models? Both samples works fine for me:
```python
import numpy as np
import cv2 as cv

print(cv.__file__)

net = cv.dnn.readNet('mobilenet_075_before1stDepthConv.pb')
inp = np.random.standard_normal([1, 3, 4, 5]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```

```python
import numpy as np
import cv2 as cv

print(cv.__file__)

net = cv.dnn.readNet('mobilenet_075_after1stDepthConv.pb')
inp = np.random.standard_normal([1, 3, 4, 5]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```

**Comment by johnlee9501** [comment]
Thank you very much to point out the size of the image. After I change the size of the input image. I can run through the two samples I have provided. 

However, I got stuck at the output layer with multiple outputs. 
I can run through the model using net.forward with a single output as below. 
But I can not run through with multiple outputs. Do you know what's wrong?
![image](https://user-images.githubusercontent.com/63490049/79087872-94975980-7cf5-11ea-8fd7-b22ca6a46a27.png)

**Comment by dkurt** [comment]
Please provide the reproducer for each of the step. This is a bug tracker and we just have no time for remote debugging. Check `help(net.forward)` how it works, see samples https://github.com/opencv/opencv/tree/master/samples/dnn. There are examples with multiple outputs.

**Comment by dkurt** [comment]
Hi! Have you solved the problem?

**Comment by johnlee9501** [comment]
The problem is resolved. Please close the ticket. Thank you very much for your help!
