### ISSUE TITLE
DCT_INVERSE flag is ignored

### ISSUE THREAD

**Issue by hananbeer** [opencv/opencv#17038]
##### System information (version)
- OpenCV => 4.2.0 (Python cv2.__version__)
- Operating System / Platform => Windows 10 64 Bit

##### Detailed description
DCT_INVERSE flag is ignored in cv2.dct()
instead it applies a forward DCT. cv2.idct works as intended.

##### Steps to reproduce
```python
import numpy as np
import cv2
data = np.asmatrix(np.random.random(8*8)).reshape(8,8)
dct_data = cv2.dct(data)
inv_dct_good = cv2.idct(dct_data)
print('delta inv_dct_good: (expecting be mostly 0 or near 0)')
print(np.round((data - inv_dct_good))*100/100)
inv_dct_bug = cv2.dct(dct_data, cv2.DCT_INVERSE)
print('delta inv_dct_bug: (is incorrectly a forward dct, not inverse)')
print(np.round((data - inv_dct_bug)*1000)/1000)
```

##### Issue submission checklist

 - [V] I report the issue, it's not a question
 - [V] I checked the problem with documentation, FAQ, open issues,
 - [V] I updated to latest OpenCV version and the issue is still there
 - [V] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by kroware** [comment]
The second parameter of dct is destination.
```
cv2.dct(dct_data, flags = cv2.DCT_INVERSE )
```
