### ISSUE TITLE
HoughLines accumulator not being returned in Python

### ISSUE THREAD

**Issue by akiross** [opencv/opencv#17050]
**System information**

- OpenCV => 3.4.4/4.2
- Operating System / Platform => Fedora Linux
- Language => Python 3.7

**Detailed description**

The `cv.HoughLines` function seems to be unable to return the value of the accumulator (votes) as it is instead possible in C++ since OpenCV 3.4. This issue seems to be [discussed in the relevant PR](https://github.com/opencv/opencv/pull/11108#issuecomment-420396192), but I couldn't find a relevant issue nor a follow-up discussion.

In the [`HoughLines` (python) documentation](https://docs.opencv.org/4.2.0/dd/d1a/group__imgproc__feature.html#ga46b4e588934f6c8dfd509cc6e0e4545a), the output vector `lines` seems to be an optional argument, but providing one as input seems to have no effect.

**Steps to reproduce**

Being a missing feature, there's not much to reproduce, but here's an example showing that lines is not used:

    out_lines = np.zeros((3824, 1, 3))
    ret_lines = cv2.HoughLines(img, 1, 0.1, 0, out_lines)
    assert ret_lines.shape == out_lines.shape, "I was hoping for votes as well..."
    assert not np.array_equal(out_lines, np.zeros((3824, 1, 3))), "Nothing changed in out_lines"

Both these asserts will fail. As a user, I would expect `out_lines` to be filled (with votes, as the array has 3 components) or its shape to be used to determine the shape of `ret_lines`, but neither happens.

**Comment by phlfm** [comment]
Is there a follow up to this issue? Access to the accumulator is one of the most useful things in Hough's transform and google is littered with people asking how to access it.

**Comment by cher-nov** [comment]
I believe this should be closed since that: https://github.com/opencv/opencv-python/issues/164#issuecomment-829865621

**Comment by Laubeee** [comment]
Unfortunately this is not reflected in the docs that there exists `cv2.HoughLinesWithAccumulator`
