### ISSUE TITLE
Does cv2.resize () keeping the aspect ratio ?

### ISSUE THREAD

**Issue by brian208579** [opencv/opencv#17069]
Hi,
I using [AlexeyAB/darknet](https://github.com/AlexeyAB/darknet) to training my yolov3 model then I found the this [issues](https://github.com/AlexeyAB/darknet/issues/232).
So I check the [blobFromImage()](https://docs.opencv.org/3.4/d6/d0f/group__dnn.html#ga29f34df9376379a603acd8df581ac8d7) function, It will preserving the aspect ratio.
But [AlexeyAB/darknet](https://github.com/AlexeyAB/darknet) without keeping aspect ratio, means ` blobFromImage()` will affect performance.
Does cv2.resize() preserving the aspect ratio ?
If not , I will plan to using ` cv2.resize()`  preprocessing first , then execute ` blobFromImage()`.
Is this feasible ? or Could you give me some suggestion to solve this problem ?
Appreciate !!!

**Comment by dkurt** [comment]
With OpenCV you may do any preprocessing which os necessary for the network. Both resize and blobFromImage transform image to specific size.

Please use a forum for usage questions.
