### ISSUE TITLE
a small problem with the python code in tutorial "point polygon test"

### ISSUE THREAD

**Issue by qingshihuangdi** [opencv/opencv#17070]
##### System information (version)

- OpenCV => 4.3
- Operating System / Platform => Linux Ubuntu 18.04 LTS
- Compiler => gcc 7.4.0

##### Detailed description

another issue about the python wrapper/tutorials
in openCV tutorial "Point Polygon test the python code doesn't work 
in line 49 """cv.circle(drawing,maxDistPt, int(maxVal),tuple(255,255,255), 1, cv.LINE_8, 0)"""

should be changed into  """cv.circle(drawing,maxDistPt, int(maxVal),tuple([255,255,255]), 1, cv.LINE_8, 0)"""

**Comment by benji1123** [comment]
working on it

**Comment by benji1123** [comment]
@alalek thanks,  let me know if there are any more issues.
