### ISSUE TITLE
How to determine object position from image

### ISSUE THREAD

**Issue by BarRae** [opencv/opencv#17073]
Hello,

I am currently working on a program to detect and localise purple marbles. These marbles can be located anywhere within a 3D space.

At the moment I can detect the marbles from a colour picture. 
I have access to a depth camera as well and can acquire the distance to the marble this way.

I now need to determine the position of that marble in the 3D space in order to pick it up with a robot arm.

Does anyone have a idea of how I could approach this? 
Feel free to ask for more information if necessary.

**Comment by dkurt** [comment]
This is a bug tracker. Please use a forum instead: https://answers.opencv.org/

**Comment by BarRae** [comment]
Thank you for letting me know.
