### ISSUE TITLE
Opencv stitching_detailed.cpp errors! 

### ISSUE THREAD

**Issue by areebsyed** [opencv/opencv#17086]
##### System information (version)

- OpenCV => 4.3
- Operating System / Platform => Ubuntu 18
- Compiler => g++

Facing these errors in stitching_detailed.cpp 

`stitching_detailed.cpp: In function ‘int main(int, char**)’:

stitching_detailed.cpp:420:9: error: ‘FeaturesFinder’ was not declared in this scope
     Ptr<FeaturesFinder> finder;
         ^~~~~~~~~~~~~~
stitching_detailed.cpp:420:9: note: suggested alternative: ‘features_type’
     Ptr<FeaturesFinder> finder;
         ^~~~~~~~~~~~~~
         features_type
stitching_detailed.cpp:420:23: error: template argument 1 is invalid
     Ptr<FeaturesFinder> finder;
                       ^
stitching_detailed.cpp:425:30: error: ‘SurfFeaturesFinderGpu’ was not declared in this scope
             finder = makePtr<SurfFeaturesFinderGpu>();
                              ^~~~~~~~~~~~~~~~~~~~~
stitching_detailed.cpp:425:53: error: no matching function for call to ‘makePtr<<expression error> >()’
             finder = makePtr<SurfFeaturesFinderGpu>();
                                                     ^
In file included from /usr/local/include/opencv4/opencv2/core/cvstd.hpp:81:0,
                 from /usr/local/include/opencv4/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv4/opencv2/core.hpp:54,
                 from /usr/local/include/opencv4/opencv2/core/utility.hpp:56,
                 from stitching_detailed.cpp:49:
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note: candidate: template<class _Tp, class ... A1> cv::Ptr<_Tp> cv::makePtr(const A1& ...)
 Ptr<_Tp> makePtr(const A1&... a1)
          ^~~~~~~
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note:   template argument deduction/substitution failed:
stitching_detailed.cpp:425:53: error: template argument 1 is invalid
             finder = makePtr<SurfFeaturesFinderGpu>();
                                                     ^
stitching_detailed.cpp:428:30: error: ‘SurfFeaturesFinder’ was not declared in this scope
             finder = makePtr<SurfFeaturesFinder>();

                              ^~~~~~~~~~~~~~~~~~
stitching_detailed.cpp:428:30: note: suggested alternative: ‘features_type’
             finder = makePtr<SurfFeaturesFinder>();
                              ^~~~~~~~~~~~~~~~~~
                              features_type
stitching_detailed.cpp:428:50: error: no matching function for call to ‘makePtr<<expression error> >()’
             finder = makePtr<SurfFeaturesFinder>();
                                                  ^
In file included from /usr/local/include/opencv4/opencv2/core/cvstd.hpp:81:0,
                 from /usr/local/include/opencv4/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv4/opencv2/core.hpp:54,
                 from /usr/local/include/opencv4/opencv2/core/utility.hpp:56,
                 from stitching_detailed.cpp:49:
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note: candidate: template<class _Tp, class ... A1> cv::Ptr<_Tp> cv::makePtr(const A1& ...)
 Ptr<_Tp> makePtr(const A1&... a1)
          ^~~~~~~
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note:   template argument deduction/substitution failed:
stitching_detailed.cpp:428:50: error: template argument 1 is invalid
             finder = makePtr<SurfFeaturesFinder>();
                                                  ^
stitching_detailed.cpp:432:26: error: ‘OrbFeaturesFinder’ was not declared in this scope
         finder = makePtr<OrbFeaturesFinder>();
                          ^~~~~~~~~~~~~~~~~
stitching_detailed.cpp:432:45: error: no matching function for call to ‘makePtr<<expression error> >()’
         finder = makePtr<OrbFeaturesFinder>();
                                             ^
In file included from /usr/local/include/opencv4/opencv2/core/cvstd.hpp:81:0,
                 from /usr/local/include/opencv4/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv4/opencv2/core.hpp:54,
                 from /usr/local/include/opencv4/opencv2/core/utility.hpp:56,
                 from stitching_detailed.cpp:49:
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note: candidate: template<class _Tp, class ... A1> cv::Ptr<_Tp> cv::makePtr(const A1& ...)
 Ptr<_Tp> makePtr(const A1&... a1)
          ^~~~~~~
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note:   template argument deduction/substitution failed:
stitching_detailed.cpp:432:45: error: template argument 1 is invalid
         finder = makePtr<OrbFeaturesFinder>();
                                             ^
stitching_detailed.cpp:435:26: error: ‘SiftFeaturesFinder’ was not declared in this scope
         finder = makePtr<SiftFeaturesFinder>();
                          ^~~~~~~~~~~~~~~~~~
stitching_detailed.cpp:435:26: note: suggested alternative: ‘features_type’
         finder = makePtr<SiftFeaturesFinder>();
                          ^~~~~~~~~~~~~~~~~~
                          features_type
stitching_detailed.cpp:435:46: error: no matching function for call to ‘makePtr<<expression error> >()’
         finder = makePtr<SiftFeaturesFinder>();
                                              ^
In file included from /usr/local/include/opencv4/opencv2/core/cvstd.hpp:81:0,
                 from /usr/local/include/opencv4/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv4/opencv2/core.hpp:54,
                 from /usr/local/include/opencv4/opencv2/core/utility.hpp:56,
                 from stitching_detailed.cpp:49:
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note: candidate: template<class _Tp, class ... A1> cv::Ptr<_Tp> cv::makePtr(const A1& ...)
 Ptr<_Tp> makePtr(const A1&... a1)
          ^~~~~~~
/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp:143:10: note:   template argument deduction/substitution failed:
stitching_detailed.cpp:435:46: error: template argument 1 is invalid
         finder = makePtr<SiftFeaturesFinder>();
                                              ^
stitching_detailed.cpp:481:11: error: invalid type argument of unary ‘*’ (have ‘int’)
         (*finder)(img, features[i]);
           ^~~~~~
stitching_detailed.cpp:489:11: error: base operand of ‘->’ is not a pointer
     finder->collectGarbage();
           ^~
`

**Comment by Crubert-digit** [comment]
Hi, I'm facing this same issue. How do you solved it?
