### ISSUE TITLE
make the Android Studio integration easier

### ISSUE THREAD

**Issue by windmaple** [opencv/opencv#17100]
OpenCV is a great lib, but for God's sake, pls make importing OpenCV in Android Studio easier. Copying libs around, renaming folders, manually adding dependencies, so many hoops to jump through just to get started and it's very error-prone.

There are so many tutorials/SO posts just trying to import OpenCV and many are out of date. Very frustrating. This post (https://android.jlelse.eu/a-beginners-guide-to-setting-up-opencv-android-library-on-android-studio-19794e220f3c) has 3.5K claps; imaging how many ppl struggled with this.

The official documentation still uses Eclipse (how many ppl still use that thing...).

Could you please just do sth like this (https://github.com/quickbirdstudios/opencv-android)?

**Comment by dkurt** [comment]
Feel free to propose an update for tutorials. There are examples with Android Studio as well: https://docs.opencv.org/master/d0/d6c/tutorial_dnn_android.html

**Comment by alalek** [comment]
> This post

Provides obsolete information.
No idea why they don't use builtin "build.gradle" scripts (native way to use with Android Studio).

Due quick and significant changes of Android development itself it is really hard to find tutorial with actual information.
To detect that make an attention on used version of OpenCV (2.4 is EOL, 3.4 it not migrated to Android Studio completely, look for 4.x+).

---

At this moment, actual guidelines for experienced Android Developers are in comments of "sdk/build.gradle" [script](https://github.com/opencv/opencv/blob/4.3.0/modules/java/android_sdk/build.gradle.in) bundled into release packages: `opencv-4.3.0-android-sdk.zip`.
OpenCV samples from the same package should work "from the box".

**Comment by dkurt** [comment]
Last time I tried to use OpenCV with fresh Android Studio, it even moves necessary native libraries automatically into right folders.

**Comment by LiorA1** [comment]
lol. I have 4 white hairs only because of opencv.

Anyway, 
https://www.youtube.com/watch?v=7J4b0Djcips&t=7s

**Comment by dkurt** [comment]
I've prepared a draft for Android Studio: https://gist.github.com/dkurt/f4a84cb954e8da4d8de1201d56e226f5. Will update https://docs.opencv.org/master/d0/d6c/tutorial_dnn_android.html according to it.

**Comment by windmaple** [comment]
Appreciate your nice tutorial.

But is the Maven repo (https://mvnrepository.com/artifact/opencv/opencv/4.0.0-0) still maintained?

**Comment by dkurt** [comment]
This package is not maintained by OpenCV team as far as I know. There is no contact information who is actual author as well.

**Comment by asmorkalov** [comment]
https://central.sonatype.com/artifact/org.opencv/opencv/overview
