### ISSUE TITLE
imread does not work with German Umlaut (ÄÖÜ)

### ISSUE THREAD

**Issue by Wingthor1968** [opencv/opencv#17107]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform =>Windows 64 Bit
- Compiler => n/a

##### Detailed description
I try to open an image file from a folder structure containing a German umlaut (Ö).
('c:\Öffentlich\image.jpg')

Result:
Traceback (most recent call last):
  File "m:\Programmierung\FotoTools\FotoComparer.py", line 27, in <module>
    cv.imshow('Image 1', image1)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

##### Steps to reproduce
1) Create a file path containing an 'Ö'  ('Öffentlich' ='public')
2) Save an image file in this path (any will do since the problem comes from the path, not the image)
3) use imread() and imshow()

            img = 'c:/Öffentlich/image.jpg'
            image1 = cv.imread(img, cv.IMREAD_COLOR)
            cv.imshow('Image 1', image1)
            cv.waitKey(0)
            cv.destroyAllWindows()

**Comment by dkurt** [comment]
It's more generic issue with Unicode paths

**Comment by Wingthor1968** [comment]
It would be helpful to have a link to the duplicate. But anyway: here is a workaround I found:

https://stackoverflow.com/questions/43185605/how-do-i-read-an-image-from-a-path-with-unicode-characters/43185606

It works fine for me.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/wiki/FAQ#video-io-image-io-data-serialization. Solution is discussed in https://github.com/opencv/opencv/issues/4292#issuecomment-601686965
