### ISSUE TITLE
Using opencv to call the darknet version of yolo results are inconsistent

### ISSUE THREAD

**Issue by Hiwyl** [opencv/opencv#17111]
`idxs = cv2.dnn.NMSBoxes(boxes, confidences, confident, threshold)`
You can see that the source code is NMS between categories，there is no incoming category-related information.The NMS of object detection is based on the category, so this is the essential reason for the difference between the two results.Therefore the following changes should be made，with python:
`def NMSBoxes_fix(boxes, confidences, confidence_thre, nms_thre, class_id):`
     `class_id_set = set(class_id)`  
      `result = [] ` 
      `for cls in class_id_set: `
        `cls_boxes = []  `
        `cls_confidences = []  `
      `  indices = [i for i, c in enumerate(class_id) if c == cls] `
        `for i in indices:`
            `cls_boxes.append(boxes[i])`
           ` cls_confidences.append(confidences[i]) `
       ` idxs = cv2.dnn.NMSBoxes(cls_boxes, cls_confidences, confidence_thre, nms_thre) `
       ` for i in idxs:  `
          `  result.append([indices[i[0]]])   `
   ` return np.array(result)`

**Comment by dkurt** [comment]
Hi!

Can you please provide a source of information why NMS should be applied for each class but not for all the detections? Let's assume we have overlapped boxes with high IoU for the same object but two classes,

![image](https://user-images.githubusercontent.com/25801568/79720695-b7bf9b80-82e9-11ea-8998-acba926a20d7.png)

Current approach will keep the highest score object and reject all others detections which have high IoU with selected box but lower score.

Can you provide a reproducer with incorrect results?

**Comment by Hiwyl** [comment]
Hi!
This is the result of darknet，the result is in line with my expectation.
obj and obj1 are the two labels I want to recognize.
![image](https://user-images.githubusercontent.com/44716550/79722525-ca9c9500-8316-11ea-9270-a7137cf6d62f.png)

but,when I did NMS with opencv, the results were very different:
![image](https://user-images.githubusercontent.com/44716550/79724317-e5bcd400-8319-11ea-889d-1458689320f1.png)

The recognition results are as follows:
![image](https://user-images.githubusercontent.com/44716550/79724548-5532c380-831a-11ea-93c0-e357e82d32f5.png)

you can see,this inter-category based NMS suppresses boxes larger than the iou threshold，and these are the boxes that I need to recognize.

For the problems in your picture, you can set the score threshold for processing, it is not necessary to use NMS, if the wrong label score is high, I guess there may be a problem with the model training.

**Comment by dkurt** [comment]
I'm not sure that here is a problem with NMS - overlap is not so high. Please try to find a problem in your application.

**Comment by Hiwyl** [comment]
I use the same iou threshold as darknet  iou threshold=0.45

**Comment by dkurt** [comment]
Got it, thanks! So we have here object inside the object use case. We just have not considered it.

So, as the solution I'd like to recommend to set nms threshold to 0 in the `.cfg` file and do it out of the network in the application (as you have already described).

We will take a look if it's necessary to make it by default or not.

**Comment by Hiwyl** [comment]
ok,I have solved this problem by rewriting NMS and making it a certain versatility

**Comment by dkurt** [comment]
@Hiwyl, you don't need to rewrite NMS - you just need to disable it in Region layer (by specifying `nms_threshold` to zero). And in application side apply multiple NMS procedures for different classes.

**Comment by dkurt** [comment]
Oh, I see now. Both DetectionOutput and Region layers have per-class NMS. Object detection sample and [cv::dnn::DetectionModel::detect](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html#aca8d52a761b41576e3798b1a92e70a9a) need to be fixed. Thanks!
