### ISSUE TITLE
Errors in model use with opencv430 to support cuda

### ISSUE THREAD

**Issue by wangwenchao-job** [opencv/opencv#17116]
##### System information (version)

- OpenCV => :4.3:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Visual Studio 2019:

##### Detailed description

I refer to this site to transform the model
https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs

Use model for reference sample code:
the dir is : xxx/dnn/classification.cpp

but,There was a mistake like this:
![image](https://user-images.githubusercontent.com/57739867/79776248-0ca1f700-8368-11ea-916a-d729845d030d.png)

Finally, if I want to provide the model to you, where can I upload it?

Thank you !

**Comment by YashasSamaga** [comment]
@wangwenchao-job Google Drive or any place would do. Please provide the shape of input given as well.

**Comment by wangwenchao-job** [comment]
@YashasSamaga 
I put the model here, I do n’t know if you can get it.
URL：https://pan.baidu.com/s/1DFcJabMbM8ls2AQL7b8TOg 
Extraction code：4xgz

Below is the code I used：
 
#include <fstream>
#include <sstream>

#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <iostream>

using namespace std;

using namespace cv;
using namespace dnn;


int main(int argc, char** argv)
{
	std::string pbName = "./test_model_pb.pb";
	std::string pbtxtName = "./test_model_pbtxt.pbtxt";

	int backendId = cv::dnn::DNN_BACKEND_CUDA;
	int targetId = cv::dnn::DNN_TARGET_CUDA;

	Net net = readNet(pbName, pbtxtName, "");
	net.setPreferableBackend(backendId);
	net.setPreferableTarget(targetId);

	Mat test_pic = imread("./defect.bmp");

	Mat blob;

	float scale = 1.0;
	Scalar mean = { 0, 0, 0 };
	bool swapRB = true;
	int inpWidth = 160;
	int inpHeight = 200;

	blobFromImage(test_pic, blob, scale, Size(inpWidth, inpHeight), mean, swapRB, false);

	net.setInput(blob);
	Mat prob = net.forward();

	Point classIdPoint;
	double confidence;
	minMaxLoc(prob.reshape(1, 1), 0, &confidence, 0, &classIdPoint);

	std::vector<double> layersTimes;
	double freq = getTickFrequency() / 1000;
	double t = net.getPerfProfile(layersTimes) / freq;
	std::string label = format("Inference time: %.2f ms", t);
	putText(test_pic, label, Point(0, 15), FONT_HERSHEY_SIMPLEX, 0.3, Scalar(0, 255, 0));
	label = format("Confidence: %.4f", confidence);
	putText(test_pic, label, Point(0, 40), FONT_HERSHEY_SIMPLEX, 0.3, Scalar(0, 255, 0));

	imwrite("./res.jpg", test_pic);

	std::cout << "finish" << std::endl;
	return 0;
}

**Comment by wangwenchao-job** [comment]
I put the model here, I do n’t know if you can get it.
URL:https://pan.baidu.com/s/1DFcJabMbM8ls2AQL7b8TOg
Extraction code:4xgz

Below is the code I used:

#include <fstream>
#include <sstream>

#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <iostream>

using namespace std;

using namespace cv;
using namespace dnn;


int main(int argc, char** argv)
{
	std::string pbName = "./test_model_pb.pb";
	std::string pbtxtName = "./test_model_pbtxt.pbtxt";

	int backendId = cv::dnn::DNN_BACKEND_CUDA;
	int targetId = cv::dnn::DNN_TARGET_CUDA;

	Net net = readNet(pbName, pbtxtName, "");
	net.setPreferableBackend(backendId);
	net.setPreferableTarget(targetId);

	Mat test_pic = imread("./defect.bmp");

	Mat blob;

	float scale = 1.0;
	Scalar mean = { 0, 0, 0 };
	bool swapRB = true;
	int inpWidth = 160;
	int inpHeight = 200;

	blobFromImage(test_pic, blob, scale, Size(inpWidth, inpHeight), mean, swapRB, false);

	net.setInput(blob);
	Mat prob = net.forward();

	Point classIdPoint;
	double confidence;
	minMaxLoc(prob.reshape(1, 1), 0, &confidence, 0, &classIdPoint);

	std::vector<double> layersTimes;
	double freq = getTickFrequency() / 1000;
	double t = net.getPerfProfile(layersTimes) / freq;
	std::string label = format("Inference time: %.2f ms", t);
	putText(test_pic, label, Point(0, 15), FONT_HERSHEY_SIMPLEX, 0.3, Scalar(0, 255, 0));
	label = format("Confidence: %.4f", confidence);
	putText(test_pic, label, Point(0, 40), FONT_HERSHEY_SIMPLEX, 0.3, Scalar(0, 255, 0));

	imwrite("./res.jpg", test_pic);

	std::cout << "finish" << std::endl;
	return 0;
}

The size of the input picture is：160x200x3

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job Google Drive or any place would do. Please provide the shape of input given as well.

**Comment by YashasSamaga** [comment]
@wangguoqin1001 can you upload it elsewhere? I am not able to download it.

**Comment by wangwenchao-job** [comment]
> @wangguoqin1001 can you upload it elsewhere? I am not able to download it.

Sorry, I did not find a suitable way to upload the file, so I sent you a email.

Email address is：
yashas_2010@yahoo.com
notifications@github.com

**Comment by YashasSamaga** [comment]
The assertion is being triggered by logic in `strided_slice` layer. The assertion is correct since an attempt is made to squeeze a rank-one tensor which doesn't make sense. The root cause is a bit weird.

The input and output shape for the slice operation is `1 1` and `1 1`. This is weird because there no slicing required. It's just copying "one" number to another. 

There is an optimization that tries to eliminate leading singleton dimensions (to improve compute performance) until you end up with the dimensions required for slicing. But `1 1` doesn't require slicing and hence the optimization won't end up with a valid sliceable tensor (which eventually tips off assertions).

I can fix this by adding a check to do a normal copy if no slicing is required.

Slicing that reduces to copy can be done in-place and eventually removed (just like in #16306).

**Comment by wangwenchao-job** [comment]
hi @YashasSamaga,
Can this issue be opened again？
Is there any progress in the model call in the saved model format.
In my debug process，There is such a mistake：
![image](https://user-images.githubusercontent.com/57739867/80866925-fbd87600-8cc3-11ea-9e02-4bf7dbcb7044.png)

![image](https://user-images.githubusercontent.com/57739867/80866940-08f56500-8cc4-11ea-8b0c-ab3d6fcd9f65.png)

Is this because my compilation is wrong?
I use PB file and pbtxt to test.

The same file can be used normally under CPU.

Best wishes!

**Comment by YashasSamaga** [comment]
@wangwenchao-job what is the message in the exception?

**Comment by wangwenchao-job** [comment]
hi @YashasSamaga,

I refer to this：
https://github.com/opencv/opencv/issues/16602

Using try, we get the following error report：
OpenCV(4.3.0) D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\cuda\execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'cv::dnn::cuda4dnn::csl::make_policy'

Maybe it's because of my compilation error！
But in my compilation process, CUDA and cudnn are both yes！

My configuration is ：
windows10 
vs2019 
opencv4.3.0 
cuda10.1 
cudnn 7.6.5
gtx 1050ti
I checked these options when I compiled：
opencv_dnn_cuda
with_cuda
opencv_extra_modules
opencv_nonfree
cuda_arch_bin = 6.0 6.1 7.0 7.5

So, what did I lose？I'll check it again！
However, on a Ubuntu 18 server, opencv was compiled successfully, because I successfully ran through the TF detection model, in which pbtxt was generated with the code officially provided by OpenCV.

However, I ran the same classification model on this machine and reported the following error:
OpenCV(4.2.0) /home/jianzhi/govion/opencv420/use_cmake_gui/opencv/sources/modules/dnn/src/layers/../cuda4dnn/primitives/inner_product.hpp:34: error: (-215:Assertion failed) get_effective_rank(weightsTensor) == 2 in function 'InnerProductOp'

So I guess, is there a problem with my pbtxt file generation?

The corresponding Pb and pbtxt files, as well as the original saved model file, have been sent to you. We are looking forward to your reply！

Thanks again！

**Comment by YashasSamaga** [comment]
> error: (-217:Gpu API call) invalid device function in function 'cv::dnn::cuda4dnn::csl::make_policy'

This is a very difficult problem to debug. It often indicates a problem in the build. Can you try purging old versions of OpenCV, cuDNN, CUDA Toolkit, etc. and do a clean install?

> error: (-215:Assertion failed) get_effective_rank(weightsTensor) == 2 in function 'InnerProductOp'

 was fixed in #16647. You need to upgrade to 4.3.0.

**Comment by wangwenchao-job** [comment]
> > error: (-217:Gpu API call) invalid device function in function 'cv::dnn::cuda4dnn::csl::make_policy'
> 
> This is a very difficult problem to debug. It often indicates a problem in the build. Can you try purging old versions of OpenCV, cuDNN, CUDA Toolkit, etc. and do a clean install?
> 
> > error: (-215:Assertion failed) get_effective_rank(weightsTensor) == 2 in function 'InnerProductOp'
> 
> was fixed in #16647. You need to upgrade to 4.3.0.

Hello, according to your suggestions, I cleaned the environment, reinstalled cuda, cudnn, uninstalled other versions of opencv, and recompiled. Now cuda can be used normally. 

Thank you so much.

In addition, I have used this method for transformation now. The model is a classification model, from savedmodel to h5 to pb and pbtxt, and then manually modify pbtxt to delete the unsupported layer structure.

In addition, I have used this method for transformation now. The model is a classification model, from savedmodel to h5 to pb and pbtxt, and then manually modify pbtxt to delete the unsupported layer structure. But after I replaced the original model with the detection model, this method no longer works. So I want to know if there is a relatively formal, general method. The original classification model has been uploaded to your email: notifications@github.com
At the same time, I uploaded a detection model in the following link, I don't know if you can access it:
https://www.jianguoyun.com/p/DRuhIW8QtKK2CBjB95cD

We are very grateful for your help!

**Comment by YashasSamaga** [comment]
> this method no longer works. 

What happens?

I am not able to download it. It asks for registration. The one sent through mail on 26th April is expired or I am not able to figure out how to download it.

**Comment by wangwenchao-job** [comment]
@YashasSamaga 
I used the following code to get the pb and pbtxt files from the savedmodel format model

from savedmodel to pb:
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('saved_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(inputs=tf.TensorSpec(shape=[None, 28, 28, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

for node in graph_def.node:
   print(node.op, node.name)

with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())

get pbtxt:
import os
import tensorflow as tf


pb_file = 'frozen_graph.pb'
out_put_pbtxt_file = 'frozen_graph_pbtxt.pbtxt'

graph_def = tf.compat.v1.GraphDef()
try:
    with tf.io.gfile.GFile(pb_file, 'rb') as f:
        graph_def.ParseFromString(f.read())
except:
    with tf.gfile.FastGFile(pb_file, 'rb') as f:
        graph_def.ParseFromString(f.read())
        # Delete weights
for i in reversed(range(len(graph_def.node))):
    if graph_def.node[i].op == 'Const':
        del graph_def.node[i]

graph_def.library.Clear()
tf.compat.v1.train.write_graph(graph_def, "", out_put_pbtxt_file, as_text=True)

When using it, I get the following exception：

OpenCV(4.3.0) Error: Unspecified error (FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb") in cv::dnn::ReadProtoFromBinaryFile, file D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp, line 1132
OpenCV(4.3.0) D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'

**Comment by YashasSamaga** [comment]
> OpenCV(4.3.0) Error: Unspecified error (FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb") in cv::dnn::ReadProtoFromBinaryFile, file D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp, line 1132
> OpenCV(4.3.0) D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
> 

This suggests that the file doesn't exist. Can you check if the file paths are correct?

**Comment by wangwenchao-job** [comment]
> > OpenCV(4.3.0) Error: Unspecified error (FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb") in cv::dnn::ReadProtoFromBinaryFile, file D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp, line 1132
> > OpenCV(4.3.0) D:\opencv_all\opencv430\opencv\sources\modules\dnn\src\caffe\caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "./det_model/frozen_inference.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
> 
> This suggests that the file doesn't exist. Can you check if the file paths are correct?

@ YashasSamaga
I checked, and the model did exist. But the pb file exported by saved_model is only 1k, so there may be a problem with this export method?

```
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('saved_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(inputs=tf.TensorSpec(shape=[None, 28, 28, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

for node in graph_def.node:
   print(node.op, node.name)

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
```
