### ISSUE TITLE
Slack link is dead in https://opencv.org/

### ISSUE THREAD

**Issue by ganesh-k13** [opencv/opencv#17121]
We get the following message:

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

Slack link: https://open-cv.slack.com/join/shared_invite/enQtNDEzMDU2MjIzNDYxLTNhNzQzNWFjMjYwOWRmZmVmNDJiYjBjZjRhOGE3N2Y4OTI2OTFmY2Y1MGVmMzM5MDU3YmEzYjVkOGU0OGMzMWU

**Comment by alalek** [comment]
Issue is tracked here: https://github.com/opencv-infrastructure/opencv.org/issues/30
