### ISSUE TITLE
Inconsistent docs - cv2.ellipse() axes parameter takes FULL length, instead of half

### ISSUE THREAD

**Issue by mkaskow-mc** [opencv/opencv#17135]
##### System information (version)

- OpenCV => opencv-python==4.2.0.34
- Operating System / Platform => Ubuntu 18.04.1 with Python 3.8.2
- Compiler => GCC 7.4.0

##### Detailed description

According to [documentation](https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#ellipse), to draw an ellipse with ```cv2.ellipse(img, (center, axes, angle), ...)```, one should pass half-length axes. However, passing full axes from aforementioned detected **ellipse** draws desired object.

There is a mismatch between docs and implementation (at least in Python)

##### Steps to reproduce
image below:
![test_headless](https://user-images.githubusercontent.com/64066750/80039742-c8922c00-84f8-11ea-8841-7b90ecab22ef.png)
Detecting top-right ellipse and drawing it (red line).
```python
top_right = (
    (549.6209106445312, 140.275146484375),      # (x, y)
    (47.358985900878906, 105.32463073730469),   # (full_minor_axis, full_major_axis)
    93.55953979492188                           # angle
)
cv2.ellipse(img_bgr, top_right, (0, 0, 255), 2)
```
![detected_ellipse](https://user-images.githubusercontent.com/64066750/80040215-e744f280-84f9-11ea-97d5-41f913aba7ef.png)

**Comment by alalek** [comment]
> https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#ellipse

OpenCV 2.4 is EOL.
Please refer on [actual](https://docs.opencv.org/4.3.0/d6/d6e/group__imgproc__draw.html#ga28b2267d35786f5f890ca167236cbc69) documentation instead.

> image below

Why is it so over complicated?
Just draw `circle` and `ellipse` side-by-side instead:

<details>

<summary>Code</summary>

```
import numpy as np
import cv2 as cv

img = np.zeros((480, 640, 3), dtype=np.uint8)
cv.circle(img, (100, 100), 50, (255,255,255))
cv.ellipse(img, (200, 200), (50, 50), 0, 0, 360, (0, 0, 255), 1)
cv.ellipse(img, (200, 200), (100, 50), 0, 0, 300, (255, 0, 255), 1)

rotated_rect = (
    (300, 300),
    (100, 100),  # full width (2 * radius)
    0
)
cv.ellipse(img, rotated_rect, (0, 255, 0), 1)

cv.imshow("result", img)
cv.waitKey()
```

</details>

> top_right

You are using overload with "box" parameter as RotatedRect. There is no any "half".

> cv2.ellipse(img, (center, axes, angle), ...)

No such API.
Issue is invalid.
