### ISSUE TITLE
community staffs

### ISSUE THREAD

**Issue by hidoudou** [opencv/opencv#17142]
sorry to post this issue here, cause i can't find anywhere else to show the problem.

I has found two problems:
1, I can't create a new account to make my post, even I has provide all the information.
2,the slack invite link from "https://opencv.org/releases/" is no longer active.

**Comment by mshabunin** [comment]
1. Account where?
2. This issue is tracked here: https://github.com/opencv-infrastructure/opencv.org/issues/30

**Comment by sergregory** [comment]
@hidoudou updated link to slack (from [opencv-infrastructure/opencv.org#30](https://github.com/opencv-infrastructure/opencv.org/issues/30))
https://join.slack.com/t/open-cv/shared_invite/zt-59r70dt1-iG2WZ3gG2WbnMnGZEYfcSQ

**Comment by asmorkalov** [comment]
closed as duplicate.
