### ISSUE TITLE
Regarding Contribution: new image edge detection technique

### ISSUE THREAD

**Issue by SujoyKG** [opencv/opencv#17146]
Hello Sir/ Madam,

I want to contribute to OpenCV (Python) with a new image edge
detection technique
[a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf](https://github.com/opencv/opencv/files/4527704/a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf)
 which is more generic & better than the similar popular
techniques for the same.
The paper that I have published is attached here with this email.
Please go through it.
If you like it, please tell me the process to move next.

Thanks & Regards,
Sujoy K Goswami
Principal Data Scientist
TVS Motor Company
India

**Comment by alalek** [comment]
Lets track it here: https://github.com/opencv/opencv_contrib/issues/2508
