### ISSUE TITLE
Unable to get result from QRCodeDetector.detectAndDecode() when encoded QR Code data is long

### ISSUE THREAD

**Issue by tweenietomatoes** [opencv/opencv#17152]
OpenCV 4.3 / 4.2
Windows 10 64 Bit
Python 3.8.2 / GoCV

I can't get result from QRCodeDetector.detectAndDecode() in certain circumstances.
I am basically getting realtime image from camera and decoding it. 
When i try with encoded short data it's working OK. But when i encode longer data such as

"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJldCIsImVtYWlsIjoiZW1yZUB0ZW1lbGt1cmFuLmlzdCIsImlhdCI6MTU4Nzc3ODg4NCwiZXhwIjoxNTg3ODY1Mjg0fQ.d3sIn5AQzTInxtLWBHYbCu-7KqjJfSQoMCWjH6SCw9o"

Program runs very slow when it detects code and i am unable to get any result. Looks like something related with memory allocation.

Note: I can get result if i change qr code's error correction level to lower values. But it still runs slow when it detects QR and going out of memory sometimes. I am running on 16 GB DDR4 machine.

**Comment by dkurt** [comment]
Can you please provide an image example with QR code?

**Comment by tweenietomatoes** [comment]
![qr](https://user-images.githubusercontent.com/28833597/80481157-96e6ee00-895a-11ea-8265-2bd3f4fb0ab8.png)

**Comment by tweenietomatoes** [comment]
if i change error correction to L it's working OK.
But still laggy than zbar and crashing after couple minutes.

**Comment by jshiwam** [comment]
> ![qr](https://user-images.githubusercontent.com/28833597/80481157-96e6ee00-895a-11ea-8265-2bd3f4fb0ab8.png)

Using this qrcode example the error occurs while calculating the **block syndrome** for qrcode error correction code. I tested the **detectAndDecode()** method there is no problem in detection part but while decoding the quirc library throws error.

**Detection:**
![Screenshot from 2020-04-29 21-03-59](https://user-images.githubusercontent.com/41477104/80619881-ef091780-8a62-11ea-95c5-6b471aa34b15.png)

**Decoding:**
![Screenshot from 2020-04-29 21-39-04](https://user-images.githubusercontent.com/41477104/80619589-86ba3600-8a62-11ea-991b-8180c90b3d2a.png)

**Comment by dkurt** [comment]
Thanks for experiments!

So, we have QR codes Quirc library replacement project in GSoC 2020 ideas list: https://github.com/opencv/opencv/wiki/GSoC_2020#idea-implementation-of-qr-codes-decoder-and-encoder. Let's see if we will have a student and slot for this task.

**Comment by AleksandrPanov** [comment]
fixed by #22025
