### ISSUE TITLE
opencv4.2 multi-thread call opencv interface cause memory leak

### ISSUE THREAD

**Issue by remember505** [opencv/opencv#17154]
##### System information (version)

- OpenCV => : 3.4.10, 4.2, 4.3
- Operating System / Platform => : Ubuntu 18.04 64 Bit
- Compiler => :g++

##### Detailed description
Hi @alalek ．First of all, I am very grateful for the repair of the opencv async memory leak. This has also been verified after the update of the opencv version(such as 4.2), but now another problem encountered is somewhat similar(not similar with [#15692).](https://github.com/opencv/opencv/pull/15692) The same version(opencv 4.2) is also frequently used async (or std::thread)to open threads, in the child thread Calling opencv interfaces such as canny(or remap), there is a problem of continuous memory growth?

##### Steps to reproduce

```
for (size_t i = 0; i < 1000000; i++) {
        std::async(std::launch::async, []() {
            cv::Mat binary_image_;
            std::cout << cv::utils::getThreadID() << std::endl;
            cv::Mat mImageGray = cv::imread("1.png", 1);
            cv::Canny(mImageGray, binary_image_, 12, 60);
        }).wait();
    }
```

[massif.out.zip](https://github.com/opencv/opencv/files/4532561/massif.out.zip)

**Comment by dkurt** [comment]
I highly recommend to think about threading pool logic for you application. In my experience creation of such number of threads may lead to memory fragmentation so it might be not a leak in classic point of view but increasing number of pages that OS assign for your process.

**Comment by remember505** [comment]
> I highly recommend to think about threading pool logic for you application. In my experience creation of such number of threads may lead to memory fragmentation so it might be not a leak in classic point of view but increasing number of pages that OS assign for your process.

Hi, @dkurt   Thank you very much for your reply.  I think your reply is reasonable,  but there is a doubt that every time async is called, it will wait until the end of the thread before reusing async to start a new thread. In this way, there will be a problem of continuous memory growth. I think this is a bug for opencv, I don’t know if it is planned to be fixed in which version? @alalek
