### ISSUE TITLE
Inconsistent results between 4.1.2 and 4.2.0

### ISSUE THREAD

**Issue by marcelodiaz558** [opencv/opencv#17155]
##### System information (version)
- OpenCV => 4.2.0 and 4.1.2
- Operating System / Platform => Ubuntu
- Compiler => Python
-Platform  => Google Colab & Kaggle Kernels

##### Detailed description

 I've noticed differences in the results of my preprocessing steps between versions 4.1.2 and 4.2.0, I'm using a preprocessing technique that I taked from a kaggle competition know as Ben's crop (he's the winner of the Diabetes Retinopathy 2015 competition), the code is exactly like that:

##### Steps to reproduce
```.py
def crop_image_from_gray(img,tol=7):
      gray_img = np.array(cv2.cvtColor(np.float32(img), cv2.COLOR_RGB2GRAY))
      mask = gray_img>tol
      img = np.array(img)
      check_shape = img[:,:,0][np.ix_(mask.any(1),mask.any(0))].shape[0]
      if (check_shape == 0): 
          return img 
      else:
          img1=img[:,:,0][np.ix_(mask.any(1),mask.any(0))]
          img2=img[:,:,1][np.ix_(mask.any(1),mask.any(0))]
          img3=img[:,:,2][np.ix_(mask.any(1),mask.any(0))]
          img = np.stack([img1,img2,img3],axis=-1)
      return img
  image = cv2.imread(img_path)
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
  image = crop_image_from_gray(image).astype('uint8')
  image = cv2.addWeighted ( image,4, cv2.GaussianBlur( image , (0,0) , 10) ,-4 ,128)
  image = cv2.resize(image, (512, 512))  
```
That's how each image is preprocessed, then I use Pytorch transforms to normalize:
```.py
from torchvision import transforms

_mean = [0.5291, 0.5404, 0.5586]
_std = [0.0978, 0.1216, 0.1278]
val_trans = transforms.Compose([
                            transforms.ToPILImage(),
                            transforms.Resize((384, 384)),
                            transforms.ToTensor(),
                            transforms.Normalize(_mean, _std)
                            ])
```

Now the results, with cv2.__version__ = 4.1.2: (the result I want to get with 4.2.0):
![4.1.2](https://user-images.githubusercontent.com/40875838/80283529-351e4e00-86e6-11ea-8f1e-c68f4d419c8d.png)

Results with after !pip install --upgrade opencv-python (cv2.__version__ = 4.2.0):
![Captura de pantalla (358)](https://user-images.githubusercontent.com/40875838/80283576-82022480-86e6-11ea-92f1-b18c7ca43142.png)
(The plotting code is the same in both cases, just a simple plt.imshow, I think it shouldn't affect).

I have no idea what might be going on! I checked out the documentation and I'm still not clear about this, I really need the images to look like they do in 4.1.2 using 4.2.0 because it's my only option right now, note that I'm using the exact same code in both cases, the only thing that changes is the OpenCV version, someone can give me some light here? Thanks.

**Comment by alalek** [comment]
Check for `GaussianBlur` bugs: #9863
