### ISSUE TITLE
Gradualy increased memory usage when use gstreamer + opencv

### ISSUE THREAD

**Issue by PythonImageDeveloper** [opencv/opencv#17158]
Hi guys,
I want to use gstreamer plugin in the opencv for H264 hardware decoding with jetson nano.
I use this gstreamer elements in opencv:

> gstream_elemets = (
>             'rtspsrc location={} latency=300 !'
>             'rtph264depay ! h264parse ! omxh264dec !'
>             'nvvidconv ! '
>             'video/x-raw , format=(string)BGRx !'
>             'videoconvert ! '
>             'appsink'). 
> cv2.VideoCapture(gstream_elemets, cv2.CAP_GSTREAMER)

This part of code is corectly work and because I want to decode multi-stream decoder, I use threads for this problem, but my problem is that, usage of memory is gradualy increased every time, why?

**Comment by xujiajie-jiangnan** [comment]
Me too，just gstreamer pipeline like yours，and videocapture object then loop capture>>frame and imshow ,the usage of memory is gradualy increased everytime.how did you solve it,plz
