### ISSUE TITLE
OpenCV(4.1.2) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1170: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: pose_iter_102000.caffemodel in function 'ReadNetParamsFromBinaryFileOrDie'

### ISSUE THREAD

**Issue by Kyary112358** [opencv/opencv#17160]
Hello;
I'm running a  Caffe Model using OPEN CV in Google Colab, when I run the program, I get this error:
```
OpenCV(4.1.2) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1170: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: pose_iter_102000.caffemodel in function 'ReadNetParamsFromBinaryFileOrDie'
```
But when I run the code in my Computer using PyCharm, 
It runs correctly, but it takes some time.
I want to use the google servers. 

My python code:
```python
import cv2 

protoFile = "pose_deploy.prototxt"
weightsFile = "pose_iter_102000.caffemodel"
nPoints = 22

frame = cv2.imread("hand.jpg")
net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)
```
I have all my files in the correct folders.
Thanks

**Comment by alalek** [comment]
`cv.getBuildInformation()`

**Comment by dkurt** [comment]
Most likely the path to model is invalid - check that model exists and downloaded correctly.

**Comment by dhananjayan111** [comment]
Did you find the solution @Kyary112358 ?

**Comment by dkurt** [comment]
Closing due no response from author.

@dhananjayan111, if you have similar error - please check that paths are valid:

```python
import os

for path in ['pose_deploy.prototxt', 'pose_iter_102000.caffemodel']:
    print(os.path.exists(path))
```

**Comment by dmetehan** [comment]
I receive the same error and I checked and the paths are valid but I still receive the following error:
error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1156: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: pose_deploy_linevec.prototxt in function 'ReadNetParamsFromTextFileOrDie'

The line that throws the error:
`net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)`

**Comment by Soumi7** [comment]
I receive the same error. Have you found a solution?

**Comment by Soumi7** [comment]
Also @dkurt , I checked, the paths are valid.

**Comment by mk-151090** [comment]
Any Solution to the above error.
Meanwhile I'm also getting the same kind of error
OpenCV(4.8.0) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1162: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: /content/MobileNetSSD_deploy.prototxt in function 'ReadNetParamsFromTextFileOrDie'
