### ISSUE TITLE
Error when using cv.dnn.readNetFromDarknet function with OpenCV 4.2.0 version 

### ISSUE THREAD

**Issue by akshayjaryal603** [opencv/opencv#17166]
##### System information (version)

I encountered this issue when I use dnn library to read yolov4 cfg and weight file.

    net = cv.dnn.readNetFromDarknet(FLAGS.config, FLAGS.weights)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'

**Comment by dkurt** [comment]
Please track https://github.com/opencv/opencv/issues/17148
