### ISSUE TITLE
Please add to read me as a development resource

### ISSUE THREAD

**Issue by daddydrac** [opencv/opencv#17179]
OpenCV + computer vision dev tools that compile for CUDA, DockerHub image avail as well so you dont have to wait 30min for OpenCV to compile:
https://github.com/joehoeller/NVIDIA-GPU-Tensor-Core-Accelerator-PyTorch-OpenCV

**Comment by dkurt** [comment]
Hi, @joehoeller! We have no such kind of the page with community projects.

**Comment by joehoeller** [comment]
Maybe it’s time to make one to help ppl deploy because DevOps and infrastructure is hard or a not known skill for most CV ppl. This will also help accelerate adoption of OpenCV, which is an excellent CV framework. (I’m sure you’re aware — we both use it religiously).

**Comment by dkurt** [comment]
I understand but the key question here is maintenance responsibilities. We do not put references to external projects into the source code. At least it can be [wiki page](https://github.com/opencv/opencv/wiki) but there is no smooth process on GitHub to accept PRs to wiki that means in case of outdated info there (your project update in example) - only repository maintainers can update it manually.

Another issue is organizational - we cannot promote community projects due just there is no mechanisms for that. Some of them may include malware, some of them can change without any notifications. We can as help users as mislead them.

Let's wait for feedback from others. My current point of view is that there is no trust ways to connect community components by force in some kind of ecosystem - it should grow by itself depends on user demand, project popularity and stability.

**Comment by joehoeller** [comment]
I understand. But know that I fully support this repo and have not entered
in any malware. My readme details a minor security hole in jupyter code
hinting, and explains how to remedy if it matters.

**Comment by joehoeller** [comment]
@asmaloney any updates?

**Comment by asmaloney** [comment]
I don't think I'm involved in this? :-)

Did you mean @asmorkalov?

**Comment by mshabunin** [comment]
@joehoeller , as was mentioned we don't have an active page collecting related community-maintained resources. I suggest following alternatives:
* we can add your link to the old ["Links"](https://opencv.org/links/) page, it can be a bit outdated though and there is no convenient way of changing it at the moment (issue tracker is [here](https://github.com/opencv-infrastructure/opencv.org/issues))
* you can write a short article about your resource in some public blog or OpenCV blog (see https://opencv.org/opencv-is-looking-for-blog-authors/)
* add your link to related ["Awesome"](https://github.com/sindresorhus/awesome) lists, e.g. [computer vision](https://github.com/jbhuang0604/awesome-computer-vision)
