### ISSUE TITLE
A historical nominating mistake ?

### ISSUE THREAD

**Issue by PetWorm** [opencv/opencv#17175]
I know this is not important, but I wonder if there is a nominating mistake in the class `SharrDerivInvoker`, which I think it should be `ScharrDerivInvoker`.
The source is In Bouguet' pyramidal LK paper,  he might somehow accidentally used Sharr instead of Scharr. I'm kind of thinking the guy who implemented it did't check that too.
Or maybe its just I didn't get this abbreviation.

**Comment by dkurt** [comment]
This is an internal method so there is no problem to rename it, thanks for catch! Other methods from public API looks fine: [Scharr](https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#gaa13106761eedf14798f37aa2d60404c9)

**Comment by dkurt** [comment]
Please keep it open to not to miss the problem. You may even propose a pull request with fix.

**Comment by PetWorm** [comment]
@dkurt Thanks, I created a pull request [#17176](https://github.com/opencv/opencv/pull/17176)
