### ISSUE TITLE
cuda dnn performance decreasion in tesla p4

### ISSUE THREAD

**Issue by intgogo** [opencv/opencv#17184]
In theory, Tesla P4 should be a little quicker than Titan Xp.

Titan Xp:
![image](https://user-images.githubusercontent.com/31696329/80585527-11d90300-8a46-11ea-8960-189e71f382a5.png)

Tesla P4:
![image](https://user-images.githubusercontent.com/31696329/80585787-7e540200-8a46-11ea-94ef-4e1e5201d609.png)

Help me!

**Comment by YashasSamaga** [comment]
Why do you think P4 should perform better than Titan XP? The specifications suggest the opposite.

Device    | CUDA cores | Boost Clock   | Memory Bandwidth
------------ | ---------------- | ------------------ | ---------------------------
Tesla P4 | 2560             | 1531MHz       | 192 GB/s
Titan XP | 3840            |  1582MHz       | 547.7 GB/s

**Comment by intgogo** [comment]
o-o
