### ISSUE TITLE
[DOC] https://code.opencv.org/ link broken, from https://docs.opencv.org/2.4/

### ISSUE THREAD

**Issue by Rubix982** [opencv/opencv#17199]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

OpenCV: `4.3.0-pre`
Operating System: `Linux archlinux 5.5.3-arch1-1 #1 SMP PREEMPT Tue, 11 Feb 2020 15:35:41 +0000 x86_64 GNU/Linux`
Compiler: `gcc 9.2.1`

##### Detailed description

The link at the bottom of the page `https://docs.opencv.org/2.4/` is broken for filing issues.
The text, `If you think something is missing or wrong in the documentation, please file a bug report.` leads to here `https://code.opencv.org/`, which gives back a 502 error page.
Screenshot attached below,

![image](https://user-images.githubusercontent.com/41635766/80820641-b8f99e00-8bf0-11ea-86dc-866da51587c7.png)

##### Steps to reproduce

Visit https://code.opencv.org/.

##### Issue submission checklist

Nothing related to that here. 

Thank you!
And have a nice day!

**Comment by dkurt** [comment]
https://docs.opencv.org/2.4/ works for me

**Comment by dkurt** [comment]
Hi! OpenCV 2.4.x no longer accepts any patches. Please use actual documentation https://docs.opencv.org/master/

**Comment by Rubix982** [comment]
Hi, @dkurt .
Okay! I did not know that. Thank you!

Closing the issue.
