### ISSUE TITLE
CMake generator for OpenCV?

### ISSUE THREAD

**Issue by liquidmetal** [opencv/opencv#17192]
It seems like the current set of supported generators include Makefiles, Ninja, Xcode, Codeblocks, etc. Is it possible to generate build configurations for CMake?

**Comment by asmorkalov** [comment]
What do you mean under build configurations for CMake? Release/Debug configuration is set by `CMAKE_BUILD_TYPE` option, it's standard way for CMake projects. Also OpenCV generates `OpenCVConfig.cmake` and set of supplementary files to allow other projects to find the library with `find_package`.
