### ISSUE TITLE
resize() with INTER_AREA behaves differently between CPP and Python

### ISSUE THREAD

**Issue by santo4ul** [opencv/opencv#17195]
##### System information (version)
- OpenCV => 4.3.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => GNU g++ 9.2.1

##### Problem:

The output of resize() with interpolation=INTER_AREA  is different in CPP when compared to the python version.

##### Steps to reproduce

1. Download the test image from [here](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_cnn_head_pose_axes/1.jpg).
2. Resize in CPP as 
`cv::resize(face, face, cv::Size(64, 64), cv::INTER_AREA);`
3. Resize in Python as 
`resized = cv2.resize(image, (64, 64),  interpolation=cv2.INTER_AREA)`
4. Compare output

##### Hack

When I pass inv_scale_x=1,and  inv_scale_y=1 manually to the cv::resize() (as shown below), then the output of CPP matches with Python

`		    cv::resize(face, face, cv::Size(64, 64), 1, 1, cv::INTER_AREA);
`

Thank you.

**Comment by dkurt** [comment]
Have you checked that both C++ `face` and Python `image` are the same?

**Comment by dkurt** [comment]
> Hack
When I pass inv_scale_x=1,and inv_scale_y=1 manually to the cv::resize() (as shown below), then the output of CPP matches with Python
> cv::resize(face, face, cv::Size(64, 64), 1, 1, cv::INTER_AREA);

@santo4ul, this is not a hack but proper C++ usage. Please read the documentation https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga47a974309e9102f5f08231edc7e7529d

**Comment by santo4ul** [comment]
Hi @dkurt, thanks for your inputs. 

From the documentation, given below is the signature of the cv::resize() function. The default values of fx and fy are 0. As per documentation, it should work without passing zeros. Please correct me if I"m wrong. 

```
void cv::resize (InputArray src,
OutputArray dst,
Size dsize,
double  fx = 0,
double  fy = 0,
int interpolation = INTER_LINEAR)

```

**Comment by dkurt** [comment]
@santo4ul, this is C++, you cannot skip arguments as in Python.

**Comment by santo4ul** [comment]
@dkurt we can skip the default arguments in CPP as well. 

Either we skip all the default arguments (fx, fy and interpolation) or if we need INTER_AREA, then we must specify fx and fy.

This is clear now. :)

Thanks for the clarification.
