### ISSUE TITLE
Blur - Allocates memory on the heap even when dst is preallocated

### ISSUE THREAD

**Issue by ndvbd** [opencv/opencv#17193]
I think I see in my profiler that the blur function allocates new memory, even when the dst parameter is already pre allocated (by me) beforehand.
Can it be?
I would like to avoid new memory allocations as much as possible (performance, predictability) by the opencv.

**Comment by dkurt** [comment]
Please provide a reproducer

**Comment by ndvbd** [comment]
Hi @dkurt !

Nothing really to reproduce, when I hooked into malloc_hook, and run the opencv blur, i noticed that it does around 7 memory allocations during the blur process.
I wanted to know if that's the right behaviour, and if there's a way to give all the memory to the blur beforehand, in order to save cpu time (and reuse memory).

**Comment by dkurt** [comment]
@ndvbd, can you confirm that mentioned memory allocations affect performance?

If you're looking for highly optimized pipelines in terms of memory usage, try [gapi](https://github.com/opencv/opencv/tree/master/modules/gapi) module

**Comment by ndvbd** [comment]
Thanks @dkurt. I didn't measure the performance in terms of time measurements (because I have nothing to compare to). But I saw 7 memory allocations, and I think it's a bit high. Also the multiply Mat function creates a memory allocation. I don't see why they are needed.

**Comment by dkurt** [comment]
Sorry, if you have some proposals or you can optimize mentioned methods - please open a pull request or do some research and provide all the details about mentioned analysis. Let me close it for now.
