### ISSUE TITLE
Tengine cmake rules for ARM

### ISSUE THREAD

**Issue by tkircher** [opencv/opencv#17203]
In OpenCV 4.3.0, when building with Tengine enabled on arm64, it appears to only check for a system version of Tengine when building for Android. It insists on building Tengine from source on any other platform.

**Comment by asmorkalov** [comment]
@liqi-c Is the issue still relevant?

**Comment by liqi-c** [comment]
> @liqi-c Is the issue still relevant?

@tkircher  the problems is still there ? if yes ,can you attach some more details  ？ if not , may we can close it .

**Comment by tkircher** [comment]
@liqi-c I haven't checked recently, but I look forward to giving it a try this weekend. If the problems are gone I'll close this issue.
