### ISSUE TITLE
Opencv dnn python sample is slow with darknet model

### ISSUE THREAD

**Issue by KyloEntro** [opencv/opencv#17204]
##### System information (version)

- OpenCV => 4.3.0 and 4.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC 7.5.0, python 3.6

##### Detailed description
Hi,

When I use opencv Dnn CUDA with darknet model, I have a performance issue.
In the sample of dnn (object_detection.py), to get net.forward() result, we have to do : 

```python
elif lastLayer.type == Region:
        classIds = []
        confidences = []
        boxes = []
        for out in outs:
            for detection in out:
                scores = detection[5:]
                classId = np.argmax(scores)
                confidence = scores[classId]
                if confidence > confThreshold:
                    center_x = int(detection[0] * frameWidth)
                    center_y = int(detection[1] * frameHeight)
                    width = int(detection[2] * frameWidth)
                    height = int(detection[3] * frameHeight)
                    left = int(center_x - width / 2)
                    top = int(center_y - height / 2)
                    classIds.append(classId)
                    confidences.append(float(confidence))
                    boxes.append([left, top, width, height])
```

net.forwad() takes around 40 milliseconds on my machine, it is what I expect but the code above takes around 40-45 milliseconds.

So from the moment I do : 
```python 
cv.dnn.blobFromImage
```
and get detection result in a list, it takes 80 milliseconds. 

To compare with darknet python bin from https://github.com/AlexeyAB/darknet, It run with 22 FPS so 45 milliseconds per frame (detection and print result).

**Comment by YashasSamaga** [comment]
The darknet code is written in C. The object_detection.py code is in python and python is slow. You could try vectorizing the code.

**Comment by KyloEntro** [comment]
Yes it is true but the detection with darknet model is not so slow. the net.forward() is as fast as cpp version. But the problem is to get the result. How can I vectorize the code ?

**Comment by dkurt** [comment]
Please try cpp sample and change issue topic - this is not about dnn part bit just sample.

Key goal of samples to show library usage.

**Comment by dkurt** [comment]
@KyloEntro, there is also [cv::dnn::DetectionModel](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html) which you may use in Python but with postprocessing in C++. Here an example: https://github.com/opencv/opencv/pull/17185

**Comment by KyloEntro** [comment]
Thank you ! I tried it and I got amazing performance result. Thank you. It is more simple to use and performance is better than before and than daknet yolo tool.

**Comment by marcusbrito** [comment]
> @KyloEntro, there is also [cv::dnn::DetectionModel](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html) which you may use in Python but with postprocessing in C++. Here an example: #17185

Hi, I'm trying to run the code at #17185 as it is, but i'm getting really differente numbers. 

I'm running:

OpenCV =>  4.2.0.32
Operating System / Platform => Docker - python:3.6-slim-buster
Language => python 3.6
CPU => Ryzen 3 2200G (@3.5GHz x 4), (not so far from: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz x8 at #17185)

I'm getting 1300ms for YOLOv3 416x416, instead of 208.74ms. And for YOLOv3-tiny 416x416, i'm getting 167ms.

Do I need to do/configure anything outside the code to run at those speeds?
