### ISSUE TITLE
Broken NumPy links in "Introduction to OpenCV-Python Tutorials"

### ISSUE THREAD

**Issue by dmallia17** [opencv/opencv#17212]
Links 2 and 3 in the "Additional Resources" section of the [Introduction to OpenCV-Python Tutorials](https://docs.opencv.org/master/d0/de3/tutorial_py_intro.html) are currently deprecated/broken. I believe that the current suitable replacements for these links would be the [NumPy Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html) and [NumPy Reference](https://numpy.org/devdocs/reference/index.html#reference). 

I would be happy to make a pull request to correct these links, but also just wanted to bring them to your attention!

**Comment by asmorkalov** [comment]
@dmallia17 Thanks for the feedback. Feel free to submit PR with the fix.

**Comment by asmorkalov** [comment]
Also please pay attention, that the default branch for bug fixes and documentation fixes is 3.4. All changes in 3.4 are promoted to master weekly or beweekly by OpenCV team.

**Comment by dmallia17** [comment]
Will do - thank you for the note. I will submit a PR shortly: I am just reviewing the contributing documents to be safe!

**Comment by asmorkalov** [comment]
Merged to 3.4.
