### ISSUE TITLE
Fix instructions for the Git pre-commit hook in the How to Contribute wiki

### ISSUE THREAD

**Issue by wongjessica** [opencv/opencv#17220]
Go to the [How to contribute to the OpenCV repository wiki](https://github.com/opencv/opencv/wiki/How_to_contribute#the-instruction-in-brief) and scroll down to: "**Q3. I was asked to remove whitespace issues, how can I do that?"**. The terminal command instructions to resolve this issue say to run:

`cd opencv` 
then
`mv opencv/.git/hooks/pre-commit.sample opencv/.git/hooks/pre-commit`

This can't work because the path doesn't exist since we are already in the opencv repository. The solution to this would be to change the `mv` command to:
`mv .git/hooks/pre-commit.sample .git/hooks/pre-commit`

**Comment by manikantanallagatla** [comment]
How to get access to the wiki repo: https://github.com/opencv/opencv.wiki? I am not able to raise a PR to that repo.

**Comment by asmorkalov** [comment]
Thanks for the report. Fixed.
