### ISSUE TITLE
OPENCV_HAVE_FILESYSTEM_SUPPORT is set to “FALSE” on iOS

### ISSUE THREAD

**Issue by periman2** [opencv/opencv#17234]
- OpenCV => 4.2
- Operating System / Platform => iOS emulator
- Compiler => Visual Studio 2019

Using EMGU CV which is a c# wrapper for the opencv platform, I tried implementing the videoCapture class in order to use the TwoPassStabilizer using VideoCapture.Api.Images api. This turns an exception that this is not implemented. Doing some more digging I realized that OPENCV_HAVE_FILESYSTEM_SUPPORT is set to “FALSE” when building for iOS. Can I ask why the file system support is turned off on iOS builds? Is there a way to bypass this? I really need to have video stabilization on iOS and currently opencv-emgu TwoPassStabilizer works in all other platforms (windows, mac, android) except iOS.

**Comment by alalek** [comment]
> EMGU CV
> TwoPassStabilizer

We can't with that here - wrong repository.
