### ISSUE TITLE
Add support for Eigen::Tensor conversions

### ISSUE THREAD

**Issue by jgbradley1** [opencv/opencv#17237]
OpenCV has some support for the [Eigen library](http://eigen.tuxfamily.org/index.php?title=Main_Page). Specifically the [conversion utilities](https://docs.opencv.org/master/d0/daf/group__core__eigen.html) for Eigen::Matrix. Based on my testing, these conversion functions are limited to grayscale (single channel) images. It would be possible to overcome the limitation if OpenCV had support for [Eigen::Tensor](https://eigen.tuxfamily.org/dox/unsupported/classEigen_1_1Tensor.html).

##### System information (version)
OpenCV => 4.3
Operating System / Platform => Ubuntu 18.04
Compiler => GCC 9.3.0

##### Detailed description

```cpp
// this will work
float gray_data[] = {0, 1, 2, 3, 4, 5};
cv::Mat gray_mat(2, 3, CV_32FC1, gray_data);
Eigen::MatrixXf gray_matrix;
cv::cv2eigen(gray_mat, gray_matrix);
cout << gray_matrix << endl;
```

```cpp
// will not work
float color_data[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
cv::Mat color_mat(2, 3, CV_32FC3, color_data);
Eigen::MatrixXf color_matrix;
cv::cv2eigen(color_mat, color_matrix);
cout << color_matrix << endl;
```

I've written some generic code to perform Eigen::Tensor conversions for both cv2eigen and eigen2cv directions, modeled after the current conversion code. I've tested conversions for Eigen::Tensor in row major order (column major is still causing some issues).

I can submit a PR, but my first question is would OpenCV maintainers allow support for an unofficial Eigen module?

**Comment by asmorkalov** [comment]
@vpisarev could you comment it?

**Comment by vpisarev** [comment]
@jgbradley1, thanks! If this Eigen extension (Eigen::Tensor) defines some macro, so its presence can be detected at compile time, I think, such a conversion can be added to OpenCV quite easily. Just provide a patch to the corresponding header files in OpenCV core. Then users should take care of proper #include order, compile flags etc.

Otherwise, the patch should include dedicated CMake flags (WITH_EIGEN_TENSOR or something like that), proper changes to CMake scripts, and then the same patch to the header files.

Another question is what's the use model for this?

**Comment by jgbradley1** [comment]
Update: I finished adapting the code to opencv's coding style and have row-major and col-major conversions working correctly with tests. Submitting a PR soon for review.

I could use some help with the CMake flag instructions though. I'm not sure if it is necessary though - the Eigen::Tensor module is shipped with the default Eigen release so it's guaranteed to always be present. Plus my CMake skills are just average :(

**Comment by alalek** [comment]
> shipped with the default Eigen release

Which Eigen versions support that? (as we can see Eigen 3.2.0 (from old Ubuntu 14.04) doesn't have that).

Consider using conditional compilation against these Eigen's Core defines:
```
#define EIGEN_WORLD_VERSION
#define EIGEN_MAJOR_VERSION
#define EIGEN_MINOR_VERSION
```

**Comment by jgbradley1** [comment]
@alalek Eigen::Tensor was first introduced in Eigen v3.3.0. Conditional compilation checks have been added (which made all CI builds pass so thank you). I added documentation but would appreciate a second look by someone else to make sure I captured the correct style.

**Comment by jgbradley1** [comment]
This issue was resolved in a [PR](https://github.com/opencv/opencv/pull/17320). Closing for now.
