### ISSUE TITLE
cv::dnn::NMSBoxes bug

### ISSUE THREAD

**Issue by dzywater** [opencv/opencv#17246]
OpenCV => 4.3
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2015

Question description:
NMSBoxes:  should do NMS for each class not for all classes. The input params which do not contain class indexes could reflect this issue.

**Comment by dkurt** [comment]
Hi! Please take a look at conversation https://github.com/opencv/opencv/issues/17111.
