### ISSUE TITLE
OPENCV_HAVE_FILESYSTEM_SUPPORT is set to “FALSE” on iOS

### ISSUE THREAD

**Issue by periman2** [opencv/opencv#17241]
- OpenCV => 4.2
- Operating System / Platform => iOS
- Compiler => Visual Studio 2019

I realized that OPENCV_HAVE_FILESYSTEM_SUPPORT is set to “FALSE” when building for iOS. Can I ask why the file system support is turned off on iOS builds? Is there a way to bypass this? It seems counterintuitive that it wouldn't have file system support on iOS.

**Comment by alalek** [comment]
You can always define `OPENCV_HAVE_FILESYSTEM_SUPPORT=1` through CXXFLAGS.
