### ISSUE TITLE
The sample opencl-opencv-interop.cpp dies within five minutes 

### ISSUE THREAD

**Issue by adrianmay** [opencv/opencv#17247]
##### System information (version)

- Current arch linux
- opencv 4.3.0-4
- nvidia geforce GTX 965M
- OpenCL 1.2
- Cuda 10.2.159

##### Detailed description

It dies with:

`error: OpenCV(4.3.0) /build/opencv/src/opencv-4.3.0/modules/core/src/ocl.cpp:5853: error: (-220:Unknown error code -220) OpenCL error CL_INVALID_MEM_OBJECT (-38) during call: clGetMemObjectInfo(memobj, CL_MEM_TYPE, sizeof(cl_mem_object_type), &mem_type, 0) in function 'convertFromBuffer'`

This only happens in buffer mode, not image mode

##### Steps to reproduce

Build all the samples (except qrcode which won't compile at 182 and 187 but that's not my blocker today) using the provided cmake and run `opencl/example_opencl_opencl-opencv-interop -c silly` which seems to make it use the default inbuilt webcam and wait five minutes. Don't hit space.

**Comment by adrianmay** [comment]
I found out that `clEnqueueNDRangeKernel` is failing with `CL_MEM_OBJECT_ALLOCATION_FAILURE` but I don't know why. That causes the `mem_obj[0] = mem;` at the end of `process_frame_with_open_cl` to be skipped so that `convertFromBuffer` gets fed an invalid value.

**Comment by alalek** [comment]
Please try this patch: #17294
