### ISSUE TITLE
same dnn model with different params, the speed is different

### ISSUE THREAD

**Issue by HaoLiuHust** [opencv/opencv#17259]
I have two caffe models with same network construction but different param files. Curiously，they have very different inference speed, one is 2X times faster than the another. Why this could be happen?

**Comment by dkurt** [comment]
Please provide a reproducer

**Comment by HaoLiuHust** [comment]
link：https://pan.baidu.com/s/1aoxn6uxSolvsEYnkl2mgwQ 
download code：90ns
I have uploaded here, model_1.XX is the faster one. I was running it on Win10 with Win32 mode

**Comment by dkurt** [comment]
@HaoLiuHust, sorry, cannot download from it. Please use Dropbox if you can.

**Comment by HaoLiuHust** [comment]
is google drive ok?

**Comment by dkurt** [comment]
@HaoLiuHust, also good, thanks!

**Comment by HaoLiuHust** [comment]
https://drive.google.com/open?id=1ZIrJ9oU0XneNJcl1C9QzCipSkRQHamc2 @dkurt thanks

**Comment by YashasSamaga** [comment]
I am able to reproduce this on OCV CPU but not with CUDA. The CUDA backend gives identical timings for both models.

I have replaced the timing code with this:

```
using std::chrono::steady_clock;
auto start = steady_clock::now();
auto preds = net.forward();
auto end = steady_clock::now();
```

CUDA backend:

<details>
<summary>timings for model 1</summary>
Total time:303ms
Total time:14ms
Total time:16ms
Total time:15ms
Total time:15ms
Total time:16ms
Total time:16ms
Total time:15ms
Total time:15ms
Total time:16ms
Total time:15ms
Total time:16ms
Total time:17ms
Total time:13ms
Total time:15ms
Total time:15ms
Total time:15ms
Total time:14ms
Total time:15ms
Total time:14ms
test
</details>

<details>
<summary>timings for model 2</summary>
Total time:271ms
Total time:15ms
Total time:14ms
Total time:14ms
Total time:14ms
Total time:14ms
Total time:15ms
Total time:13ms
Total time:15ms
Total time:15ms
Total time:15ms
Total time:14ms
Total time:14ms
Total time:15ms
Total time:16ms
Total time:14ms
Total time:14ms
Total time:22ms
Total time:13ms
Total time:15ms
test
</details>

**OCV CPU:**

<details>
<summary>timings for model 1</summary>
Total time:219ms
Total time:69ms
Total time:69ms
Total time:68ms
Total time:69ms
Total time:68ms
Total time:70ms
Total time:70ms
Total time:71ms
Total time:73ms
Total time:72ms
Total time:72ms
Total time:73ms
Total time:72ms
Total time:72ms
Total time:73ms
Total time:72ms
Total time:72ms
Total time:72ms
Total time:72ms
test
</details>

<details>
<summary>timings for model 2</summary>
Total time:505ms
Total time:357ms
Total time:355ms
Total time:352ms
Total time:352ms
Total time:353ms
Total time:353ms
Total time:352ms
Total time:351ms
Total time:350ms
Total time:350ms
Total time:351ms
Total time:350ms
Total time:350ms
Total time:350ms
Total time:350ms
Total time:350ms
Total time:350ms
Total time:349ms
Total time:350ms
test
</details>

**Comment by HaoLiuHust** [comment]
@YashasSamaga Thanks, I am using CPU.

**Comment by dkurt** [comment]
```
$ sha1sum.exe model_*
427859bbcc753a59fc856f0f83c7f4daa6459241 *model_1.caffemodel
181a9f6ade86d2aa8605db82e07a43c018758957 *model_2.caffemodel
b5d68a6126c632dea88174dd3deb8edde98d789f *model_1.prototxt
b5d68a6126c632dea88174dd3deb8edde98d789f *model_2.prototxt
```
Files are correct. Can also confirm that both models work with same efficiency with disabled fusion `net.enableFusion(false)`. So we need to find a problem in fusion.

**Comment by dkurt** [comment]
@HaoLiuHust, with Intel's Inference Engine backend (OpenVINO) both models work with the same efficiency (got about 32ms on Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz). You may try to use OpenCV from https://github.com/opencv/opencv/releases/download/4.3.0/opencv-4.3.0-dldt-2020.2-vc16-avx2.7z while we work on solution for default backend.

**Comment by HaoLiuHust** [comment]
@dkurt Thanks for your warmly help， but I need to use OpenCV on x86, OpenVino only support x64...our customer's compute maybe 32bit OS

**Comment by dkurt** [comment]
@HaoLiuHust, got it. So, OpenVINO does not support 32bit CPU inference, it's only for 64bit. Thanks for highlighting the problem!

**Comment by dkurt** [comment]
@HaoLiuHust, following recommendation from https://github.com/alibaba/MNN/issues/786#issuecomment-626532797 I recompiled OpenCV with `-DENABLE_FAST_MATH=ON` option and got similar efficiency for both weights. But note that this option is `OFF` by default due it's unsafe. In example, it broke 3 accuracy tests:

```
[  FAILED  ] Layer_LSTM_Test_Accuracy_with_.CaffeRecurrent
[  FAILED  ] Test_Caffe_nets.FasterRCNN_vgg16/0, where GetParam() = OCV/CPU
[  FAILED  ] Test_Caffe_nets.FasterRCNN_zf/0, where GetParam() = OCV/CPU
```

/cc @vpisarev

**Comment by HaoLiuHust** [comment]
I have tested it on MNN, still different speed..From profiling, the slower one's convolution layer is much slower. Is  weights value can effect the speed of a layer? too  weird ...

**Comment by dkurt** [comment]
@HaoLiuHust, we are not responsible for MNN, have you tested `ENABLE_FAST_MATH` for OpenCV?

**Comment by HaoLiuHust** [comment]
have not yet. ENABLE_FAST_MATH can not ensure the accuracy, is that right?

**Comment by dkurt** [comment]
@HaoLiuHust, according to the tests, yes. So I'd like just try it and check if both models produce accurate results and their efficiency. It's not solutions, but just an experiment.

**Comment by YashasSamaga** [comment]
```
auto wptr = (float*)w.data;
for (int i = 0; i < w.total(); i++)
{
    CV_Assert(w.isContinuous());
    if (std::abs(wptr[i]) < 1e-15)
        wptr[i] = 0;
}

fuseWeights(w, b);
```

I removed all the small weights before fusing and this fixed the slowdown. `1e-15` is much bigger than the smallest representable floating-point number. It's required because denormals are being created during the fusion, so the arbitrary `1e-15` cutoff prevents smaller numbers from being generated after fusion.

**Comment by YashasSamaga** [comment]
> I have tested it on MNN, still different speed..From profiling, the slower one's convolution layer is much slower. Is weights value can effect the speed of a layer? too weird ...

I zeroed all weights that were smaller than `1e-15` and both give the same efficiency. I suspect that the fusion process is leading to a lot of denormals.

**Comment by dkurt** [comment]
@YashasSamaga, thanks for explanation!

Unfortunalety, despite the model from issue achieves similar efficiency with thresholded weights, there is a stable regression for some of the models in the `opencv_perf_dnn` on CPU:
```
                       Name of Test                         base     ftz      ftz    
                                                                               vs    
                                                                              base   
                                                                           (x-factor)
AlexNet::DNNTestNetwork::OCV/CPU                           14.110  14.181     1.00   
DenseNet_121::DNNTestNetwork::OCV/CPU                      38.680  39.131     0.99   
EAST_text_detection::DNNTestNetwork::OCV/CPU               68.929  68.890     1.00   
ENet::DNNTestNetwork::OCV/CPU                              44.435  26.954     1.65   <<<<<
FastNeuralStyle_eccv16::DNNTestNetwork::OCV/CPU            119.535 124.284    0.96   
GoogLeNet::DNNTestNetwork::OCV/CPU                         15.213  15.050     1.01   
Inception_5h::DNNTestNetwork::OCV/CPU                      16.492  16.505     1.00   
Inception_v2_Faster_RCNN::DNNTestNetwork::OCV/CPU          286.843 288.193    1.00   
Inception_v2_SSD_TensorFlow::DNNTestNetwork::OCV/CPU       43.045  43.664     0.99   
MobileNet_SSD_Caffe::DNNTestNetwork::OCV/CPU               19.457  21.011     0.93   <<<<<
MobileNet_SSD_v1_TensorFlow::DNNTestNetwork::OCV/CPU       21.112  22.336     0.95   <<<<<
MobileNet_SSD_v2_TensorFlow::DNNTestNetwork::OCV/CPU       29.928  31.641     0.95   <<<<<
OpenFace::DNNTestNetwork::OCV/CPU                           3.917   3.936     1.00   
OpenPose_pose_mpi_faster_4_stages::DNNTestNetwork::OCV/CPU 604.125 612.948    0.99   
ResNet_50::DNNTestNetwork::OCV/CPU                         35.706  35.647     1.00   
SSD::DNNTestNetwork::OCV/CPU                               268.489 266.141    1.01   
SqueezeNet_v1_1::DNNTestNetwork::OCV/CPU                    3.910   3.888     1.01   
YOLOv3::DNNTestNetwork::OCV/CPU                            209.808 209.162    1.00   
opencv_face_detector::DNNTestNetwork::OCV/CPU              13.539  14.016     0.97
```

```patch
@@ -414,6 +414,7 @@ public:
                 cv::multiply(originWeights.row(i), weightsMultipliers[i], weightsMat.row(i));
                 biasvec[i] *= wi;
             }
+            weightsMat.setTo(0, abs(weightsMat) <= 1e-15f);  // Flush to zero (FTZ) denormal weights
         }
```

**Comment by dkurt** [comment]
That's crazy :) If we will keep just a signed zero (probably for ReLU?) the performance for target network is OK and there is no efficiency regressions:
```
                       Name of Test                         base     ftz      ftz    
                                                                               vs    
                                                                              base   
                                                                           (x-factor)
AlexNet::DNNTestNetwork::OCV/CPU                           14.110  14.064     1.00   
DenseNet_121::DNNTestNetwork::OCV/CPU                      38.680  38.555     1.00   
EAST_text_detection::DNNTestNetwork::OCV/CPU               68.929  68.397     1.01   
ENet::DNNTestNetwork::OCV/CPU                              44.435  26.273     1.69   
FastNeuralStyle_eccv16::DNNTestNetwork::OCV/CPU            119.535 118.005    1.01   
GoogLeNet::DNNTestNetwork::OCV/CPU                         15.213  15.202     1.00   
Inception_5h::DNNTestNetwork::OCV/CPU                      16.492  16.675     0.99   
Inception_v2_Faster_RCNN::DNNTestNetwork::OCV/CPU          286.843 288.505    0.99   
Inception_v2_SSD_TensorFlow::DNNTestNetwork::OCV/CPU       43.045  42.981     1.00   
MobileNet_SSD_Caffe::DNNTestNetwork::OCV/CPU               19.457  19.491     1.00   
MobileNet_SSD_v1_TensorFlow::DNNTestNetwork::OCV/CPU       21.112  21.173     1.00   
MobileNet_SSD_v2_TensorFlow::DNNTestNetwork::OCV/CPU       29.928  29.599     1.01   
OpenFace::DNNTestNetwork::OCV/CPU                           3.917   3.964     0.99   
OpenPose_pose_mpi_faster_4_stages::DNNTestNetwork::OCV/CPU 604.125 607.526    0.99   
ResNet_50::DNNTestNetwork::OCV/CPU                         35.706  35.471     1.01   
SSD::DNNTestNetwork::OCV/CPU                               268.489 266.976    1.01   
SqueezeNet_v1_1::DNNTestNetwork::OCV/CPU                    3.910   3.898     1.00   
YOLOv3::DNNTestNetwork::OCV/CPU                            209.808 206.514    1.02   
opencv_face_detector::DNNTestNetwork::OCV/CPU              13.539  13.453     1.01 
```
```patch
@@ -414,6 +414,10 @@ public:
                 cv::multiply(originWeights.row(i), weightsMultipliers[i], weightsMat.row(i));
                 biasvec[i] *= wi;
             }
+            Mat mask = (weightsMat <= 1e-15f) & (weightsMat > 0);
+            weightsMat.setTo(0, mask);  // Flush to zero (FTZ) denormal weights
+            mask = (weightsMat <= 1e-15f) & (weightsMat < 0);
+            weightsMat.setTo(-0, mask);  // Flush to zero (FTZ) denormal weights
         }
```

**Comment by dkurt** [comment]
@HaoLiuHust, @YashasSamaga, please take a look to proposed fix: https://github.com/opencv/opencv/pull/17295

**Comment by HaoLiuHust** [comment]
Thanks for your work, I have tested it, speed is ok, and I made similar change in MNN, also OK. I will try more to test accuracy

**Comment by HaoLiuHust** [comment]
The accuracy is OK, Thanks
