### ISSUE TITLE
Suggestion for a OpenPose simplified module.

### ISSUE THREAD

**Issue by snehitvaddi** [opencv/opencv#17271]
### Suggestion
Hey, I am trying to implement pose estimation and I have come across two options, OpenPose and TFPoseNet. TFPosenet is a javascript and OpenPose is python based. OpenPose is a bit complex when compared to TFPosenet methods and implementation. I am a python lover and I am not ready to learn JavaSript for just TFPosenet in TFJS.  

Why can't OpenCV.org develop a simple module of OpenPose so that it can be easily imported, and effectively call some functions like find Hands location or draw the skeleton etc.

I hope this helps and makes sense. Waiting to see a simplified version of OpenPose.

**Comment by asmorkalov** [comment]
Thanks for the proposal, it could be good idea for Google Summer of Code

**Comment by alalek** [comment]
BTW,
Take a look on human pose estimation demos from OMZ repository (through [OpenVINO](https://software.intel.com/openvino-toolkit)):
- C++: https://github.com/opencv/open_model_zoo/tree/2020.2/demos/human_pose_estimation_demo
- Python: https://github.com/opencv/open_model_zoo/tree/2020.2/demos/python_demos/human_pose_estimation_3d_demo

**Comment by dkurt** [comment]
I've also tried to wrap the sample from OpenVINO's model zoo so it can be available from bindings: https://github.com/opencv/open_model_zoo/pull/272
```python
import cv2 as cv
from cv2.open_model_zoo import HumanPoseEstimation

p = HumanPoseEstimation()

frame = cv.imread('example.png')
poses = p.process(frame)

p.render(frame, poses)

cv.imshow('res', frame)
cv.waitKey()
```

**Comment by snehitvaddi** [comment]
@dkurt @alalek  Thank you for the inputs.
 Is there a way to get the location of key features like eyes, nose, etc so that I can further implement for specific applications.

**Comment by asmorkalov** [comment]
@snehitvaddi The model zoo repo provides full list of models with architecture and inference details in [this](https://github.com/opencv/open_model_zoo/blob/master/models/intel/index.md) document. 

- [Landmark regression](https://github.com/opencv/open_model_zoo/blob/master/models/intel/landmarks-regression-retail-0009/description/landmarks-regression-retail-0009.md)
- [Facial landmark](https://github.com/opencv/open_model_zoo/blob/master/models/intel/facial-landmarks-35-adas-0002/description/facial-landmarks-35-adas-0002.md)
