### ISSUE TITLE
Inference engine fails to infer with a different input size

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#17283]
I'm trying to infer a model on images bigger (704²) than what it was trained with (256²) which should not be a problem since it's fully convolutional.
While it works fine with the `DNN_BACKEND_OPENCV`, it fails with `DNN_BACKEND_INFERENCE_ENGINE`

> OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.3.0-dev) Error: Unspecified error (Failed to initialize Inference Engine backend (device = CPU): Incorrect dimensions for broadcasting for Mul_14) in cv::dnn::InfEngineBackendNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp, line 881

The model is timm-efficientnet-b4 https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/efficientnet.py
![image](https://user-images.githubusercontent.com/182520/81835880-0bb54d00-9543-11ea-9638-36e03f8409a9.png)

This is with OpenVino 2019 R3, I tried converting my onnx with 2020.2 and recompiling OpenCV with 2020.2, and it doesn't help. However it works I load the onnx instead of the bin/xml. Is there any chance to fix it with 2019 R3?

**Comment by dkurt** [comment]
> D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp
this file should not be used with 2019R3.

Can you share an onnx file to reproduce the problem?

**Comment by JulienMaille** [comment]
Sorry my bad, after spending some time to reproduce it, the error is not in ie_ngraph.cpp
> Loading image [704,704]..done
[ INFO:0] global D:\Dev\opencv\modules\core\src\ocl.cpp (891) cv::ocl::haveOpenCL Initialize OpenCL runtime...
Loading model..done in 913ms
Running first inference on CPU OpenVino..
[ INFO:0] global D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp (813) cv::dnn::InfEngineBackendNet::initPlugin DNN-IE: Loaded extension plugin: cpu_extension_avx2.dll
OpenCV(4.3.0-dev) Error: Unspecified error (> Failed to initialize Inference Engine backend (device = CPU): Incorrect dimensions for broadcasting for Mul_14
> ..\src\mkldnn_plugin\nodes\mkldnn_eltwise_node.cpp:63
> ../include/details/ie_exception_conversion.hpp:71
) in cv::dnn::InfEngineBackendNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp, line 881
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.3.0-dev) Error: Unspecified error (> Failed to initialize Inference Engine backend (device = CPU): Incorrect dimensions for broadcasting for Mul_14
> ..\src\mkldnn_plugin\nodes\mkldnn_eltwise_node.cpp:63
> ../include/details/ie_exception_conversion.hpp:71
) in cv::dnn::InfEngineBackendNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp, line 881

I emailed you the model files.

**Comment by dkurt** [comment]
Hi!

Can you please describe the usage? If you want to work with 704x704 input resolution you may just generate an IR with this shape:
```
python3 /opt/intel/openvino_2019.3.376/deployment_tools/model_optimizer/mo_onnx.py --input_model model.onnx --input_shape "[1, 3, 704, 704]"
```
then work through OpenCV or OpenVINO API:
```python
import numpy as np
import cv2 as cv
print(cv.__file__)

net = cv.dnn.readNet('model.xml', 'model.bin')
inp = np.random.standard_normal([1, 3, 704, 704]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```
```
(1, 2, 704, 704)
```

**Comment by JulienMaille** [comment]
I want to work with arbitrary size input resolution, similar to what I do with a resnet model (which works fine)

**Comment by JulienMaille** [comment]
It seems the optimisation step performed by https://github.com/daquexian/onnx-simplifier was the reason why the size of some tensors was hardcoded.
Sorry for wasting your time!

**Comment by JulienMaille** [comment]
Oh man, I must be tired. Sorry no the problem is still there with the raw onnx exported by pytorch

**Comment by JulienMaille** [comment]
@dkurt from what I understand
- model being locked on a specific input size is a consequence of IE model optimiser
- solution is to load the onnx instead and let OpenCV adapt it to given input on-the-fly
 Solution requires 2020.2

Shall we close this issue?

**Comment by dkurt** [comment]
@JulienMaille, I'd like to recommend to use 2020.2 if you want to enable flexible input size. The following are performance numbers for the model:

version|min|median|mean|std
---|---|---|---|---
2019.3, IR|54.83ms|55.17ms|55.60ms|2.49
2020.2 IR from 2019.3|46.92ms|47.10ms|47.52ms|2.15
2020.2 IR from 2020.2|47.01ms|47.19ms|47.65ms|2.60
2020.2 ONNX+DNN_BACKEND_INFERENCE_ENGINE|47.23ms|47.43ms|47.84ms|2.20

**Comment by JulienMaille** [comment]
Thanks a lot
> IR has hardcoded shapes for Resize layers so you **may** use import from .onnx file.

In case I want to change input size, do you confirm here the may is a **must**? :)

Regarding inference time  (the model you tried was the efficientnet), may I ask what is your CPU? You get a nice improvement with 2020 where I get a very small degradation on my Xeon E5-1620, as shown in my table here:
https://github.com/openvinotoolkit/openvino/issues/483#issuecomment-629650758

**Comment by dkurt** [comment]
@JulienMaille, please try also to run benhmark_app to check latency/throughput by OpenVINO's tool:
```
"C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\tools\benchmark_tool\benchmark_app.py" -m model.xml
```
I experimented with Ubuntu 18.04 and `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz x8`

**Comment by JulienMaille** [comment]
@dkurt may I ask if you could run your benchmark on the other model (resnet) I emailed you?
Maybe we can close this issue and continue on the other https://github.com/openvinotoolkit/openvino/issues/483 where I posted a couple benchmarks

**Comment by JulienMaille** [comment]
> @JulienMaille, please try also to run benhmark_app to check latency/throughput by OpenVINO's tool:
> 
> ```
> "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\tools\benchmark_tool\benchmark_app.py" -m model.xml

So, it doesn't work with 2019.R3
`[ ERROR ] Unsupported primitive of type: Resample name: Interpolate/Upsample_76`
And this is what I get with 2020.2:
```
[Step 11/11] Dumping statistics report
Count:      1084 iterations
Duration:   60237.74 ms
Latency:    220.64 ms
Throughput: 18.00 FPS
```

**Comment by dkurt** [comment]
@JulienMaille, please specify a path to cpu_extenion.dll by `-l` flag for 2019.3

**Comment by JulienMaille** [comment]
Thank you
I ran: `python "C:\Program Files (x86)\IntelSWTools\openvino_2019.3.379\deployment_tools\tools\benchmark_tool\benchmark_app.py" -m models\model_2020_0427_19h13_9.xml -l "C:\Program Files (x86)\IntelSWTools\openvino_2019.3.379\deployment_tools\inference_engine\bin\intel64\Release\cpu_extension_avx2.dll"`
```
[Step 11/11] Dumping statistics report
Count:      1064 iterations
Duration:   60548.55 ms
Latency:    225.76 ms
Throughput: 17.57 FPS
```
So with this test, 2020.2 is marginally faster than 2019.R3.
Could there be an issue with my c++ setup? This is what I get with my own test:
```
2019.R3: Running 50 inferences on CPU OpenVino..done in avg: 63.2, min: 60, median: 61, std: 6.07
2020.2 : Running 50 inferences on CPU OpenVino..done in avg: 87.1, min: 85, median: 86, std: 2.12
```

**Comment by dkurt** [comment]
@JulienMaille, add `-api sync` flag to measure latency only

**Comment by JulienMaille** [comment]
@dkurt Now this looks like my own benchmarks
```
**** 2019.R3 ****
[ INFO ] InferenceEngine:
         API version............. 2.1.32974
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 32974
[ INFO ] Network batch size: 1, precision: FP32
[ INFO ] Network input 'input.1' precision FP32, dimensions (NCHW): 1 1 256 256
[Step 10/11] Measuring performance (Start inference syncronously, limits: 60000 ms duration)
[Step 11/11] Dumping statistics report
Count:      948 iterations
Duration:   60077.80 ms
Latency:    62.10 ms
Throughput: 16.10 FPS
```
```
**** 2020.2 ****
[ INFO ] InferenceEngine:
         API version............. 2.1.42025
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 42025
[ INFO ] Network batch size: 1
[ INFO ] Network input 'input.1' precision FP32, dimensions (NCHW): 1 1 256 256
[Step 10/11] Measuring performance (Start inference syncronously, limits: 60000 ms duration)
[Step 11/11] Dumping statistics report
Count:      685 iterations
Duration:   60052.85 ms
Latency:    87.23 ms
Throughput: 11.46 FPS
```

**Comment by dkurt** [comment]
@JulienMaille, ok, got it, thanks! So looks like this is not OpenCV issue. Can you open an issue at https://github.com/openvinotoolkit/openvino with the log and CPU specification?

What about this issue, is that solved?

**Comment by JulienMaille** [comment]
I think this one is solved yes!

**Comment by dkurt** [comment]
@JulienMaille, May I ask to benchmark the model on Xeon E5-1620/Win10 once again but now with OpenVINO 2020.4?

**Comment by JulienMaille** [comment]
@dkurt i'll do as soon as I have access to that machine

**Comment by JulienMaille** [comment]
@dkurt I have same speed with 2020.4, no improvement unfortunately

**Comment by dkurt** [comment]
Hi, @JulienMaille, If you are able, can we ask to benchmark the latest 2021.3 or master using your configuration? Thanks in advance!

**Comment by JulienMaille** [comment]
Unfortunately that computer is dead :(

**Comment by dkurt** [comment]
Oh, sorry about that. Anyway thank you!
