### ISSUE TITLE
can you tell me how to fix a assertion bug

### ISSUE THREAD

**Issue by alittlebitcool** [opencv/opencv#17306]
I‘m sorry to boring you, but this step is boring me so much that I can't continue my process.
could you please tell me videoCapture.read() parameter frame has any different from cv.imread("imagepath") I can't figure out what this say
error: (-215:Assertion failed) samples.cols == var_count && samples.type() == 5 in function 'cv::ml::SVMImpl::predict'
please help me, thanks!

**Comment by dkurt** [comment]
Please read issue template and edit description so we can reproduce the problem.
