### ISSUE TITLE
findcontours error

### ISSUE THREAD

**Issue by nmodem2k** [opencv/opencv#17308]
error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'

I am getting the above error.plz anyone help...

**Comment by saskatchewancatch** [comment]
Do you have a reproducer sample? This would help.

Please also see doc for [findContours](https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0).

That error message could definitely be improved.
