### ISSUE TITLE
OpenCV stops processing after x thousand frames

### ISSUE THREAD

**Issue by terribletrouble** [opencv/opencv#17305]
##### System information (version)
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.2.0'
>>> 

##### Detailed description

I have some code in python3, that processes GoPro videos, and adds a timestamp to the individual frames. It then puts the frames together again and re-produces the video with a nice timestamp at the bottom. The problem is that is stops wortking / just hangs, after a certain number of frames. The frame count seems to be anything starting at 16,000 and higher. I have a specific GoPro video I am working with that is 10 mins and 16 sec long, and I stop processing at anything from 16,000 to 22,000 frames. Does not seem to be memory related, I have 32Gb on board and I am watching things with htop. If I run this under Winows it is a lot worse, and cannot process anywhere near the same number of frames.

It does not make sense to attach my source video file to this, take any GoPro video that is greater than 2Gb and process it with the code below.

##### Steps to reproduce

This here is the code that matters, the rest just manipulates file names and so on.
```
#while True:
    while current_frame < total_frames:
        success, image = video.read()
        if success == True:
            elapsed_time = video.get(cv2.CAP_PROP_POS_MSEC)
            current_frame = video.get(cv2.CAP_PROP_POS_FRAMES)
            if current_frame % 100 == 0:
                print('|Current Frame: ', current_frame, '|Total Frames: ', total_frames, '|Image Size: ', sys.getsizeof(image))
            timestamp = initial + dt.timedelta(microseconds = elapsed_time*1000)
            #cv2.putText(image, text, org, font, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])    
            cv2.putText(image, 'Date: ' + str(timestamp)[0:10], (20,int(height-25)), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 255, 255), 2)
            cv2.putText(image, 'Time: ' + str(timestamp)[11:-7], (360,int(height-25)), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 2550, 255), 2)
            pipe.stdin.write(image.tostring())
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    
    video.release()
    pipe.stdin.close()
    pipe.stderr.close()
    pipe.wait()
```

And the result is:
```
....
|Current Frame:  16500.0 |Total Frames:  36939.0 |Image Size:  6220928
|Current Frame:  16600.0 |Total Frames:  36939.0 |Image Size:  6220928
^CTraceback (most recent call last):
  File "GoPro-TimeStamp.py", line 116, in <module>
    pipe.stdin.write(image.tostring())
KeyboardInterrupt

```
In the above example, the input file has 36939 frames, and during processing when I got to above 16600, it just hung, I eventually hot control-C, and the error is what you see.
I have confirmed it is not an issue at this frame count in this file, it just varies from file to file and time to time. I cannot get to the bottom of it.

I have run this inside a debugger and same thing, it just hangs, and the only variable that I can look at is the: pipe.stdin.write(image.tostring())

I am assuming there is a problem inside the cv2 library.

**Comment by dkurt** [comment]
> sys.getsizeof(image)

Can you please use `image.nbytes` instead?

https://docs.python.org/3/library/sys.html#sys.getsizeof:
> Only the memory consumption directly attributed to the object is accounted for, not the memory consumption of objects it refers to.

moreover
> getsizeof() calls the object’s __sizeof__ method and adds an additional garbage collector overhead if the object is managed by the garbage collector.

**Comment by terribletrouble** [comment]
So that sys.getsizeof(image) is just for debugging purposes, nothing else. I was trying to add some code that may show if there was a bad frame that I was dealing with. I did change to image.nbytes, shows the same data and still gets stuck. On Windows, a lot sooner than on Linux.

I just need some clues to add some code that will fail before the hang, or if there is something wrong with the way I am doing this.

```
|Current Frame:  747.0 |Total Frames:  36939.0 |Image Size:  6220800
|Current Frame:  748.0 |Total Frames:  36939.0 |Image Size:  6220800
|Current Frame:  749.0 |Total Frames:  36939.0 |Image Size:  6220800
```

**Comment by alalek** [comment]
> pipe.stdin.write

Try to remove this line - it doesn't look correct and not related to OpenCV.

**Comment by terribletrouble** [comment]
You are correct, however I have just previously opened ffmpeg in stream mode, via pipe commands, so as I have completed adding the relevant data to the respective frame, I then append it via stream mode to the ffmpeg that I have open. I do suppose the problem could rely with the the pipe command, if I could be sure it is not opencv causing issues, that is where I will have to look next.

**Comment by terribletrouble** [comment]
My code is very similar to the example here. Where someone else gets stuck at the same point. 

[https://stackoverflow.com/questions/60606499/python-gets-stuck-at-pipe-stdin-writeimage-tostring](url)

**Comment by terribletrouble** [comment]
Guys, I am sorry to have raised this issue, I found the problem, and it was a common error copied by I think quite a few people and one guy noticed it. Nothing to do with OpenCV. Thank you for your time.

[https://stackoverflow.com/questions/60606499/python-gets-stuck-at-pipe-stdin-writeimage-tostring](url)

**Comment by zhangweizhenGitHub** [comment]
> Guys, I am sorry to have raised this issue, I found the problem, and it was a common error copied by I think quite a few people and one guy noticed it. Nothing to do with OpenCV. Thank you for your time.
> 
> [https://stackoverflow.com/questions/60606499/python-gets-stuck-at-pipe-stdin-writeimage-tostring](url)

so finally,how did you solved it?
