### ISSUE TITLE
How can I get the reference, books, paper or anything else  about the tutorial "real-time pose estimation" in opencv?

### ISSUE THREAD

**Issue by Steven-ZY** [opencv/opencv#17309]
##### System information (version)

I'm going to do the search about object pose estimation. Last week, I found the tutorial [ "real-time pose estimation" in OpenCV ](https://www.docs.opencv.org/4.2.0/dc/d2c/tutorial_real_time_pose.html). But I can't make it clear. Is there someone kind-hearted that can help me figure it out? 
I wanna know about the algorithm principle, execution process, reference, and how to make the input. By the way, Is it an online method to obtain the templates? Thanks in advance!

**Comment by dkurt** [comment]
> You can find the source code of this tutorial in the samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/ folder of the OpenCV source library
