### ISSUE TITLE
 ERROR: OpenCV(3.4.1-dev) matrix.cpp

### ISSUE THREAD

**Issue by drenched9** [opencv/opencv#17314]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Linux (SUSE 12)
- Compiler => g++

##### Detailed description
input an image with 1642*2338
error ocures when read the image, and returns the following exception:
/XXX/opencv/modules/core/src/matrix.cpp:362: error (-215) u !=0 in function create

I have searched many solutions to resolve this question, but all of them are proved useless. Hope someone help me, thanks a lot!

**Comment by MacTian** [comment]
Encountered the same problem, how to solve it?

**Comment by drenched9** [comment]
> Encountered the same problem, how to solve it?

Maybe the picture's attribution was not valid. what I encountered was the bit depths of the image was not different from other images. You can seek for some details from this direction.
