### ISSUE TITLE
opencv dnn error importing onnx model (Can't create layer "835" of type "Cast" in function 'getLayerInstance')

### ISSUE THREAD

**Issue by smpurkis** [opencv/opencv#17311]
##### System information (version)

- OpenCV => 4.2
- onnx => 1.7.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Pycharm 2019

##### Detailed description

Trying to import an onnx model (saved using pytorch) into opencv dnn on python, but keeps producing this error.

```
Traceback (most recent call last):
  File "...app/u2net/load_u2net_in_opencv.py", line 11, in <module>
    cv_model = cv2.dnn.readNetFromONNX(model_path.__str__())
cv2.error: OpenCV(4.2.0) ...modules/dnn/src/dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "835" of type "Cast" in function 'getLayerInstance'
```

I found a couple other examples of this on this forum, often being pointed to make a custom layer (at https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html). I took a look and started writing a cast layer, but it went a little over my head and I got lost at the start.
[u2net_model.zip](https://github.com/opencv/opencv/files/4640054/u2net_model.zip)

##### Steps to reproduce

Script I use to import it, I only use onnx to double check the model is okay.

```.py
from pathlib import Path
import onnx
import cv2

model_path = Path("u2net_tiny_opset_11.onnx")
assert model_path.exists()

onnx_model = onnx.load_model(model_path.__str__())
onnx.checker.check_model(onnx_model, full_check=True)

cv_model = cv2.dnn.readNetFromONNX(model_path.__str__())
```

**Comment by dkurt** [comment]
> OpenCV => 4.2

Please try the latest master branch. There were number of PRs related to this issue.

**Comment by smpurkis** [comment]
updated to 4.3.0, 
I'm now getting this error 
```
Traceback (most recent call last):
  File ".../u2net/load_u2net_in_opencv.py", line 12, in <module>
    cv_model = cv2.dnn.readNetFromONNX(model_path.__str__())
cv2.error: OpenCV(4.3.0) .../opencv/modules/dnn/src/onnx/onnx_importer.cpp:257: error: (-215:Assertion failed) index < node_proto.input_size() in function 'getBlob'
```

**Comment by kalazus** [comment]
If you have upsampling with 'bilinear' mode in your pytorch model, it could be the reason. Try 'nearest' mode instead.

**Comment by IvanKosik** [comment]
@smpurkis I had the same error with OpenCV 4.3.0 release. Solution of @kalazus fixed the problem. But there is one more solution: I tried latest master branch (as @dkurt suggested) of OpenCV 4.3.0 from github (commit https://github.com/opencv/opencv/commit/e96a58f09124bb5ae22cfa036c91c24e1d767f63). And the model without changes was loaded succsesfully.

**Comment by wangwangww** [comment]
> @smpurkis I had the same error with OpenCV 4.3.0 release. Solution of @kalazus fixed the problem. But there is one more solution: I tried latest master branch (as @dkurt suggested) of OpenCV 4.3.0 from github (commit [e96a58f](https://github.com/opencv/opencv/commit/e96a58f09124bb5ae22cfa036c91c24e1d767f63)). And the model without changes was loaded succsesfully.

I had the same error with OpenCV 4.3.0 release. how to get  latest master branch (as @dkurt suggested) of OpenCV 4.3.0 from github.

**Comment by l-bat** [comment]
I checked that this model works on the latest master branch.

**Comment by aktaseren** [comment]
> > OpenCV => 4.2
> 
> Please try the latest master branch. There were number of PRs related to this issue.

@dkurt I am having the same issue here on my conda virtual environment where opencv 4.1.1 runs. How can I try your solution on my case?

**Comment by xiongzhu666** [comment]
> I checked that this model works on the latest master branch.

yes, it works. but the result is incorrect compared with onnxruntime. have you face the problem？？
