### ISSUE TITLE
Poor Results with Out of Focus Deblur Tutorial

### ISSUE THREAD

**Issue by dmallia17** [opencv/opencv#17315]
##### System information (version)

- OpenCV => 4.3
- Operating System / Platform => MacOS (10.14 Mojave)
- Compiler => Xcode (Clang/LLVM?)

##### Detailed description

I attempted to translate the C++ program featured in the [Out-of-focus Deblur Filter](https://docs.opencv.org/3.4/de/d3c/tutorial_out_of_focus_deblur_filter.html) tutorial into Python for adding multi-language coverage. I have included that code below. However, I had trouble recreating the results of the article after translation:

![result](https://user-images.githubusercontent.com/33104112/82168232-480ee300-988c-11ea-9b3e-9ba26a374eab.jpg)

To try to isolate the problem, I compiled and ran the C++ program with the parameters mentioned in the tutorial, but did not receive the "advertised" results:

![result](https://user-images.githubusercontent.com/33104112/82167574-42180280-988a-11ea-86ca-a4e9828e6c8b.jpg)

Any help with debugging both versions would be greatly appreciated, as I would very much like to submit the translation for inclusion.

Two notes:
1. This script uses NumPy `fft.fftshift()` instead of the custom fftshift function from the tutorial, but I got the same results with both.
2. I noticed that adding the cv.DFT_SCALE flag to the `cv.dft` and `cv.idft` functions improved the results, and I believed that flag should be included on all, but I have not included it here, in the interest of a direct translation.

<details>
<summary> Below is the translated Python script </summary>
<br>

```python
import sys, argparse, copy
import numpy as np
import cv2 as cv

def main():
	# Parse arguments
	text = "Recover an out-of-focus image by Wiener filter."
	parser = argparse.ArgumentParser(text)
	parser.add_argument("--image", type=str, required=True, 
		help="Specify the input image filename.")
	parser.add_argument("--R", type=int, required=True,
		help="Specify the point spread circle radius. Demo example: 53")
	parser.add_argument("--SNR", type=float, required=True,
		help="Specify the signal-to-noise ratio (SNR). Demo example: 5200")
	args = parser.parse_args()

	help()

	# Read in image and prepare empty output image
	img_in = cv.imread(args.image, cv.IMREAD_GRAYSCALE)
	if img_in is None:
		sys.exit("ERROR : Image cannot be loaded...!!")

	## [main]
	# it needs to process even image only
	roi = img_in[0:(img_in.shape[0] & -2), 0:(img_in.shape[1] & -2)]
	## Hw calculation (start)
	h = calcPSF(roi.shape, args.R)
	Hw = calcWnrFilter(h, 1.0 / float(args.SNR))
	## Hw calculation (stop)

	## filtering (start)
	imgOut = filter2DFreq(roi, Hw)
	## filtering (stop)
	## [main] 

	imgOut = imgOut.astype(np.float32)
	imgOut = cv.normalize(imgOut, imgOut, alpha=0, beta=255, 
		norm_type=cv.NORM_MINMAX)
	cv.imwrite("result.jpg", imgOut)

## [help]
def help():
	print("2018-07-12")
	print("DeBlur_v8")
	print("You will learn how to recover an out-of-focus image by Wiener\
		 filter")
## [help]

## [calcPSF]
def calcPSF(filterSize, R):
	h = np.zeros(filterSize, dtype=np.float32)
	point = (filterSize[1] // 2, filterSize[0] // 2)
	h = cv.circle(h, point, R, 255, -1, 8)
	summa = np.sum(h)
	return (h / summa) 
## [calcPSF]

## [filter2DFreq]
def filter2DFreq(inputImg, H):
	planes = [inputImg.copy().astype(np.float32), 
		np.zeros(inputImg.shape, dtype=np.float32)]
	complexI = cv.merge(planes)
	complexI = cv.dft(complexI, flags=cv.DFT_SCALE)

	planesH = [H.copy().astype(np.float32), 
		np.zeros(H.shape, dtype=np.float32)]
	complexH = cv.merge(planesH)
	complexIH = cv.mulSpectrums(complexI, complexH, 0)

	complexIH = cv.idft(complexIH)
	planes = cv.split(complexIH)
	return planes[0]
## [filter2DFreq]

## [calcWnrFilter]
def calcWnrFilter(input_h_PSF, nsr):
	h_PSF_shifted = np.fft.fftshift(input_h_PSF)
	planes = [h_PSF_shifted.copy().astype(np.float32), 
		np.zeros(h_PSF_shifted.shape, dtype=np.float32)]
	complexI = cv.merge(planes)
	complexI = cv.dft(complexI)
	planes = cv.split(complexI)
	denom = np.power(np.abs(planes[0]), 2)
	denom += nsr 
	return cv.divide(planes[0], denom) 
## [calcWnrFilter]

if __name__ == "__main__":
	main()
	cv.destroyAllWindows()

```
</details>

##### Steps to reproduce

Build OpenCV from source with samples and run the example_tutorial_out_of_focus_deblur_filter executable with the parameters mentioned in the tutorial.

**Comment by dkurt** [comment]
Please take a look at https://github.com/opencv/opencv/issues/16227 and https://github.com/opencv/opencv/pull/12046#issuecomment-459183757.

You need to use original size image because resizing changes the signal which should be removed by algorithm.

**Comment by dmallia17** [comment]
@dkurt Thank you very much for pointing those out and apologies for not spotting those myself! I do indeed get the correct results with the C++ program and now my Python program is much closer as well, but I still can't get the output exactly right: 

![result](https://user-images.githubusercontent.com/33104112/82274039-0eea7780-994d-11ea-8a66-dc1db774501c.jpg)

Do you have any intuition as to why this might be? I tried to adhere as close as possible to the C++ source code though I should mention that the above used the NumPy fftshift, whereas the below was with an attempted translation of the C++ source:

![resultWIP](https://user-images.githubusercontent.com/33104112/82274087-36414480-994d-11ea-8eee-7dc9f20e0a94.jpg)

```
def fftshift(inputImg):
	outputImg = inputImg.copy()
	cx = int(outputImg.shape[1] / 2) # x = cols
	cy = int(outputImg.shape[0] / 2) # y = rows
	q0 = outputImg[0:cy, 0:cx]         # Top-Left - Create a ROI per quadrant
	q1 = outputImg[0:cy, cx:cx+cx]     # Top-Right
	q2 = outputImg[cy:cy+cy, 0:cx]     # Bottom-Left
	q3 = outputImg[cy:cy+cy, cx:cx+cx] # Bottom-Right
	tmp = np.copy(q0)             # swap quadrants (Top-Left with Bottom-Right)
	outputImg[0:cy, 0:cx] = q3
	outputImg[cy:cy+cy, cx:cx+cx] = tmp
	tmp = np.copy(q1)             # swap quadrant (Top-Right with Bottom-Left)
	outputImg[0:cy, cx:cx+cx] = q2
	outputImg[cy:cy+cy, 0:cx] = tmp
	return outputImg
```

Thank you very much again!

**Comment by dkurt** [comment]
@dmallia17, You need to compare algorithms on different stages. In example, run Python code, dump outputs and then compare with reference sample in C++. I believe it might help you to open NumPy data in C++: [blobFromNPY](https://github.com/opencv/opencv/blob/master/modules/dnn/test/npy_blob.cpp).

BTW, seems like there is no Python sample for corresponding PR. Do you want to contribute this version?

**Comment by dmallia17** [comment]
Yes I was attempting to translate the C++ source so I could contribute the Python version to the tutorial. 😄 I will do my best to debug the translation and hopefully can submit it (make a PR) soon!

**Comment by csverma610** [comment]
Hello,
It seems that example in the tutorial works only for 6000X4000 image.

**Comment by dkurt** [comment]
> It seems that example in the tutorial works only for 6000X4000 image.

That's incorrect. Sample works for specific noise structure which so origin image should be processed but not downsampled.

**Comment by nicheng0019** [comment]
Hi, when I run the program, I get the same result as your c++ program as the first time, how did you fix it, ths
![out](https://github.com/user-attachments/assets/662da6b8-e894-49d9-8edd-1f21a1632356)
