### ISSUE TITLE
How can I find the essential matrix between two different cameras?

### ISSUE THREAD

**Issue by themightyoarfish** [opencv/opencv#17329]
This is a question about the API, not really a bug report.

The documentation on [`findEssentialMat()`](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga13f7e34de8fa516a686a56af1196247f) states
> Note that this function assumes that points1 and points2 are feature points from cameras with the same camera matrix. 

But this is a very strong restriction. Is there a way to solve this problem between two distinct cameras?
Or would it be possible to `undistortPoints()` the points to normalized image coordinates with identity camera matrices for both cameras?

**Comment by tompollok** [comment]
I think you could extract it estimating the Fundamental Matrix and then using the formula to extract the essential matrix.

E = (K')^t F K

Other option could be to undistort the points with 

cv::undistortPoints(inputDistortedPoints, outputUndistortedPoints, cameraMatrix, distCoeffs, R=cv::noArray(), P=cv::noArray());

P – New camera matrix (3x3) or new projection matrix (3x4). P1 or P2 computed by stereoRectify() can be passed here. If the matrix is empty, the identity new camera matrix is used.

So i guess you could just put the identity camera matrix into findEssentialMat().

**Comment by themightyoarfish** [comment]
I think I'd like to submit a PR to the documentation that makes it clear how it can be done, so I'll keep this open for now.

**Comment by chadrs2** [comment]
Use the stereoCalibrate() function
