### ISSUE TITLE
some confusions about the function "cv::reprojectImageTo3D()"

### ISSUE THREAD

**Issue by zengletian1491** [opencv/opencv#17335]
In Binocular camera mode, I would like to obtain real world coordinates of points from a disparity map.With the OpenCV function "reprojectImageTo3D()" ,  **the output seems right, however, the three-dimension coordinates of the points is obviously wrong. I do not know why.** **Please give me some advices！**

 In my case of the following function "cv::reprojectImageTo3D(disparityImage, pointCloud, Q);", Q is computed as follows:

cv::Rect validRoi[2];
cv::stereoRectify(cameraMatrix[0], distCoeffs[0],
                      cameraMatrix[1], distCoeffs[1],
                      m_imageSize,
                      R, T,
                      R[0], R[1],
                      P[0], P[1],
                      Q,
                      0 ,
                      m_imageSize, &validRoi[0], &validRoi[1]);

    for (size_t k = 0; k < 2; k++){
        cv::initUndistortRectifyMap(cameraMatrix[k], distCoeffs[k], R[k], P[k], imageSize, CV_16SC2, rectifyMaps[k][0], rectifyMaps[k][1]);}

**In addition, I also have other questions：**
**（1） Are the three-dimension coordinates (obtained by reprojectImageTo3d() function) located in the camera coordinate system or in the world coordinate system？
(2) What is the metric (i.e.， the unit of the coordinates， such m, cm, mm) of the three-dimension coordinates?**
Could you give me some suggestions?Thank you.

**Comment by zacario-li** [comment]
Q1: the coordinates you obtained is in the camera coordinate system.
Q2: The metric is defined by the calibration.  For example, if you calibrate your stereo camera with 'mm', the result you obtained by the reprojectImageTo3D is in 'mm'.
