### ISSUE TITLE
consistency, GaussianBlur camelcase pep8 to gaussianBlur

### ISSUE THREAD

**Issue by elfelround** [opencv/opencv#17330]
https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html#blur

blur(), boxFilter(), bilateralFilter(), GaussianBlur(), medianBlur()

as you can see all these methods start with lowercase then uppercase but gaussian blur doesnt

personally i would have them all starting with caps since they are used as constructors mainly to instantiate objects HOWEVER since code is already done i would tone down the inconsistency of GaussianBlur (which from my point of view should be the how all the other methods shall be written) to gaussianBlur so at least it fits with the other methods for consistency

**Comment by mshabunin** [comment]
See [Naming Conventions](https://github.com/opencv/opencv/wiki/Coding_Style_Guide#naming-conventions).
