### ISSUE TITLE
deleted cv.Mat retains values

### ISSUE THREAD

**Issue by KurtPachinger** [opencv/opencv#17356]
##### System information (version)

- OpenCV => 4.3.0 JavaScript
- Operating System / Platform =>Windows 10 Home 2004 / Lenovo laptop
- Compiler => //docs.opencv.org/3.4/utils.js

##### Detailed description

- Previously deleted cv.Mat()'s retain Ghost/burn-in/artefacts.
- A new cv.Mat() has a value of 80, which climbs to 247, unless set to 0, in which case it remains 78.
- Effects of operations become unpredictable, i.e. copyTo(), add(), etc.
- First noticed applying multiple masks... transparency mask can reveal staggered tile background of scale/subject that is incorrect, or noise/tearing/vsync.
- mat.setTo([0,0,0,255]) is a hotfix

##### Steps to reproduce

- reuse a variable with... masks, cv.add(), cv.absdiff()... some array calculation with underlying process
- procedural masks that rely on foreground/background white/black and image foreground/background white/black
- https://codepen.io/kpachinger/pen/6e2fd47fc63ebafe492770de44aebcf8
- dst.setTo([0,0,0,255]); // <=BUG? (comment to see)

![lena](https://user-images.githubusercontent.com/48163461/82752047-7f4c2b00-9d89-11ea-8022-e60ad07c2b66.jpg)

**Comment by KurtPachinger** [comment]
More tests from repeat threshold masks.

![mat-delete-still-data](https://user-images.githubusercontent.com/48163461/82762669-5307cd00-9dd0-11ea-94ca-70da8bb80178.jpg)

**Comment by alalek** [comment]
`Mat` constructor doesn't initialize underlying buffer. It only allocates it. To initialize buffer you should pass `Scalar` parameter.

**Comment by KurtPachinger** [comment]
Thank you!

**Comment by KurtPachinger** [comment]
My Pixel 3a no longer freezes on pinch-zoom now that I set mats to [0,0,0,0] and resize to (1,1) before delete.
