### ISSUE TITLE
Errors when enable deeplabV3 model with dnn module

### ISSUE THREAD

**Issue by akineeic** [opencv/opencv#17362]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => ubuntu 18.04 64bit
- Compiler => python

##### Detailed description

I'm tying to use opencvd dnn module to run deeplabV3 model. I use the frozen pb file download [here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) and get error like this:
```
cv2.error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/tensorflow/tf_graph_simplifier.cpp:90: error: (-212:Parsing error) Input node with name MobilenetV2/expanded_conv_1/output not found in function 'getInputNodeId'
```
But I can find this layer `MobilenetV2/expanded_conv_1/output` if I use [Netron](https://lutzroeder.github.io/netron/) to open this model.

Then I use [tf2onnx](https://github.com/onnx/tensorflow-onnx) to conver this frozen file to onnx model since I think opencv may be more compatible with onnx models. But I still get error like this:
```
cv2.error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:155: error: (-210:Unsupported format or combination of formats) Unsupported data type: INT32 in function 'getMatFromTensor'
```
It seems this model contains data types which is not supported by opencv onnx importer and it may be hard to enable this model in onnx format with this gap. But do you have any suggestion about how to enable the frozen tensorflow model?

I put the two models [here](https://drive.google.com/drive/u/1/folders/1rdUqitvMXmbWrlyr3V5VzFZoTNs7kN3Q), please tell me if you need any further information, thanks.

##### Steps to reproduce
```
import cv2 as cv
net = cv.readNet('deeplabV3.pb') // net = cv.readNet('deeplabV3.onnx')
```

**Comment by alalek** [comment]
> 4.1.2

Outdated version.
Please try latest release or code from `master` branch.

**Comment by akineeic** [comment]
> Please try latest release or code from `master` branch.

Thanks for your quick reply! I test with 4.3.0 and the errors are  as follows:
```
>>> cv.dnn.readNet('deeplabV3.pb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.3.0) /home/zzm/software/opencv/modules/dnn/src/graph_simplifier.cpp:79: error: (-212:Parsing error) Input node with name MobilenetV2/expanded_conv_1/output not found in function 'getInputNodeId'
```

```
>>> cv.dnn.readNet('deeplabV3.onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.3.0) /home/zzm/software/opencv/modules/dnn/src/graph_simplifier.cpp:79: error: (-212:Parsing error) Input node with name Shape not found in function 'getInputNodeId'
```


And the onnx model is generated by the commond as follows:
```
python -m tf2onnx.convert --input deeplabV3.pb --output deeplabV3.onnx --inputs ImageTensor:0 --outputs SemanticPredictions:0 --opset 11
```

**Comment by huningxin** [comment]
I can reproduce this issue by using [OpenCV 4.3.0 release](https://github.com/opencv/opencv/releases/tag/4.3.0) and [mobilenetv2_coco_voc_trainval](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz) of [TensorFlow DeepLab Model Zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md).

My steps:

1. Download [deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz) from TensorFlow DeepLab Model Zoo
2. Untar the file and get the `frozen_inference_graph.pb`
3. Launch python and execute `import cv2 as cv`
4. Try read the net by `cv.dnn.readNet('frozen_inference_graph.pb')`

The error message:
```
>>> cv.dnn.readNet('frozen_inference_graph.pb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.3.0) C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\graph_simplifier.cpp:79: error: (-212:Parsing error) Input node with name MobilenetV2/expanded_conv_1/output not found in function 'cv::dnn::Subgraph::getInputNodeId'
```

**Comment by huningxin** [comment]
I can use TensorFlow [Graph Transform Tool](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/tools/graph_transforms/README.md) to optimize the original graph (`frozen_inference_graph.pb`) and run the optimized graph with OpenCV successfully.

Here are my steps:

I use TensorFlow python package `tensorflow==1.15.2`. I wrote a python wrapper [optimize_graph.py](https://gist.github.com/huningxin/060fe2ac60b61781d6ea36f83969ed2a#file-optimize_graph-py) to invoke Graph Transform Tool. The options I use are:
```console
python optimize_graph.py \
  --in_graph frozen_inference_graph.pb \
  --out_graph optimized_graph.pb \
  --inputs sub_7 \
  --outputs ResizeBilinear_3 \
  --transforms remove_nodes(op=Identity) \
     merge_duplicate_nodes \
     strip_unused_nodes \
     fold_constants(ignore_errors=true) \
     fold_batch_norms fold_old_batch_norms
```
The `optimized_graph.pb` contains the optimized graph. Then I use OpenCV segmentation python example [segmentation.py](https://github.com/opencv/opencv/blob/master/samples/dnn/segmentation.py) to run it, the command options I use are:
```console
python segmentation.py --width 513 --height 513 \
    --model optimized_graph.pb \
    --input test.jpg --rgb --scale 0.007843 --mean 127.5 127.5 127.5
```

There are some minor issues in segmentation.py, I put together #17394 to fix them.

With the fix, here is the screenshot of segmentatoin.py for the optimized_graph.pb on my machine:
![image](https://user-images.githubusercontent.com/1005673/82974556-d4e43a00-a00c-11ea-957d-16afd366a98c.png)

@akineeic , feel free to try on your side.

**Comment by akineeic** [comment]
> @akineeic , feel free to try on your side.

Those steps also work for me, thanks!
