### ISSUE TITLE
About the timing of net.getPerfProfile () and forward ()

### ISSUE THREAD

**Issue by wangwenchao-job** [opencv/opencv#17365]
##### System information (version)

- OpenCV => :4.3.0 with cuda:
- Operating System / Platform => :windows 10:
- Compiler => :cmake 3.16:

##### Detailed description

I use chrono to time the Inference part, mainly the forward () function, and the time I get is very poor compared to getPerfPrifile ()

```
        auto start_t = std::chrono::system_clock::now(); 
        net.forward();
        auto end_t = std::chrono::system_clock::now();
        std::cout<<"forward() time = "<< std::chrono::duration_cast<std::chrono::milliseconds>(end_t - start_t).count() << "milliseconds" << std::endl;
 
	vector<double> layersTimes;
	double freq = getTickFrequency() / 1000;
	double t = net.getPerfProfile(layersTimes) / freq;
	string label = format("Inference time for a frame : %.2f ms", t);
	putText(frame, label, Point(0, 15), FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 0, 255));
```

The forward function time is about 70ms.
The time of getPerfProfile function is only 1ms.

The model is a simple binary classification model, the size of a single predicted picture is 160x200.

I found the following two issues, which are similar to my problem, but neither seems to be resolved:
https://github.com/opencv/opencv/issues/14075
https://github.com/opencv/opencv/issues/17358

Thanks again for your guidance！@YashasSamaga

**Comment by YashasSamaga** [comment]
The CUDA backend works by dumping all the DNN operations into a CUDA stream. It waits at the end for all the operations in the stream to finish. To measure layerwise timings, events will have to be placed before and after every layer. These cause a tiny performance drop.

I think most people use `getPerfProfile` to get the end to end time? Maybe support could be add to at least give the total time. This will fix the code in the samples too.

My suggested workaround (perhaps a better way to analyze) is to use Nsight Systems that comes with the CUDA Toolkit. You can view layerwise timings neatly in a nice visual interface (and do a lot of other things). The problem here is that you get to see the time taken by each operation in the stream. You'll have to do some intelligent guessing to see what operations are part of which layer.

The CUDA backend can add markers (tag operations with layer names for example) and what not to annotate the profiler information. This requires the use of NVTX primitives (which is a part of CUDA Toolkit) in the CUDA backend which can be enabled by some environment variable like `CUDA4DNN_ENABLE_NVTX` or something. It's not there but it could be added if there is a demand for it and the maintainers agree.

**Comment by wangwenchao-job** [comment]
> This is a bug/missing feature in the CUDA backend. `getPerfProfile` is not supported.
> 
> The CUDA backend works by dumping all the DNN operations into a CUDA stream. It waits at the end for all the operations in the stream to finish. To measure layerwise timings, events (CUDA stuff that can be used to mark points in the CUDA stream) will have to be placed before and after every layer. These things take a tiny toll on the performance.
> 
> I think most people use `getPerfProfile` to get the end to end time? Maybe partial support could be added to return just the total time. This will fix the code in the samples too.
> 
> My suggested workaround if you need layerwise timings is to use Nsight Systems that comes with the CUDA Toolkit. You can view layerwise timings neatly in a nice visual interface (and do a lot of other things). The problem here is that you get to see the time taken by each operation in the stream. You'll have to do some intelligent guessing to see what operations are part of which layer.
> 
> The CUDA backend can add markers (tag operations with layer names for example) and what not to annotate the profiler information. This requires the use of NVTX primitives (which is a part of CUDA Toolkit) in the CUDA backend which can be enabled by some environment variable like `CUDA4DNN_ENABLE_NVTX` or something. It's not there but it could be added if there is a demand for it and the maintainers agree.
> 
> ![Screenshot from 2020-05-25 12-46-35](https://user-images.githubusercontent.com/6652578/82788228-aab44000-9e85-11ea-8d7f-3c12ad27e3d7.png)
> 
> Here is an example that shows that almost 15ms is spent on the CPU in the first DetectionOutput layer of Inception v2 Mask RCNN. You can see the device to host data transfers in pink and there is a tiny speck of blue dot at the right end of the gap representing the host to device transfer. All of that is 15ms on my laptop. The processors on the system where I benchmark with RTX 2080 Ti is even slower! The CPU probably makes up 50% of the inference time there (total inference time is around 30ms and the slower processors would take more than 15ms presumably for DetectionOutput). There is another DetectionOutput layer that comes later but isn't that costly.
> 
> And this gives a big hint: use multiple `cv::dnn::Net` models for Mask RCNN on RTX 2080 Ti and you might double the FPS! This allows GPU computations of other `cv::dnn::Net` to use the GPU while some other `cv::dnn::Net` is busy in the CPU part.



What does it mean：
“This is a bug/missing feature in the CUDA backend. getPerfProfile is not supported.”

It means: we can't use the net.getPerfProfile function to calculate the inference time of the network, because cuda does not support net.getPerfProfile, so the calculated value is unreasonable?

If I want to get the inference time from loading the image into the network to output the prediction result, I should use the following code:
```
auto start_t = std::chrono::system_clock::now(); 
net.forward();
auto end_t = std::chrono::system_clock::now();
std::cout<<"forward() time = "<< std::chrono::duration_cast<std::chrono::milliseconds>(end_t - start_t).count() << "milliseconds" << std::endl;
```
Thank you very much, I will try the cuda tool to check the time of each layer.@YashasSamaga

**Comment by YashasSamaga** [comment]
> It means: we can't use the net.getPerfProfile function to calculate the inference time of the network, because cuda does not support net.getPerfProfile, so the calculated value is unreasonable?

`getPerfProfile` reports the time each layer took to dump operations into the CUDA stream. It does not include the time it took to execute the operation on the GPU. It only counts the time spent on CPU.

> If I want to get the inference time from loading the image into the network to output the prediction result, I should use the following code:
> 
> ```
> auto start_t = std::chrono::system_clock::now(); 
> net.forward();
> auto end_t = std::chrono::system_clock::now();
> std::cout<<"forward() time = "<< std::chrono::duration_cast<std::chrono::milliseconds>(end_t - start_t).count() << "milliseconds" << std::endl;
> ```

Yes.

**Comment by longxianlei** [comment]
Yes, that's true. If we want to measure the inference time on our GPUs. We need to explicitly set the begin_time and end_time.
auto start_t = std::chrono::system_clock::now(); 
net.forward();
auto end_t = std::chrono::system_clock::now();
This is the right way to count the GPU speed.
If we want to count the CPU time.
It's ok for both ways.
