### ISSUE TITLE
Eigen headers not included in eigen.hpp

### ISSUE THREAD

**Issue by themightyoarfish** [opencv/opencv#17366]
##### System information (version)

- OpenCV => 4.3.0_2
- Operating System / Platform => macOS 10.15
- Compiler => clang

##### Detailed description

When `#include`ing `core/eigen.hpp`, compilation fails, unless `<Eigen/Dense>` or something is included before. Otherwise, compilation fails, because 
```
/usr/local/Cellar/opencv/4.3.0_2/include/opencv4/opencv2/core/eigen.hpp:63:22: error: use of undeclared identifier 'Eigen'
void eigen2cv( const Eigen::Matrix<_Tp, _rows, _cols, _options, _maxRows, _maxCols>& src, OutputArray dst )
```

Am I missing something here? Is this expected? In that case, this should go into the documentation. Otherwise, `#include <Eigen/Dense>` should be added to https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/eigen.hpp

**Comment by alalek** [comment]
It is by design to support Eigen from different configurations/versions.
`eigen.hpp` is header which depends on external configuration. It is caller responsibility to properly add/configure "Eigen" into compilation units.

Usage:
```
#include ... Eigen headers ...
#include <opencv2/core/eigen.hpp>
```

**Comment by themightyoarfish** [comment]
Cool, is this documented somewhere I've missed?

**Comment by alalek** [comment]
Eigen related documentation is [here](https://docs.opencv.org/3.4/d0/daf/group__core__eigen.html), but I don't find any `@note` there.
