### ISSUE TITLE
getAvailableBackends returns a non working backend

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#17378]
I have a system with a i7-5500U and Intel HD Graphics 5500 (drivers v20.19.15.4568 - OpenCL 2.0)
Calling `getAvailableBackends()` returns
```
DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_2019, DNN_TARGET_CPU
DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_2019, DNN_TARGET_OPENCL
DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_2019, DNN_TARGET_OPENCL_FP16
DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL
DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL_FP16
DNN_BACKEND_OPENCV, DNN_TARGET_CPU
```
but when trying to run a dnn on the GPU with (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL) it fails to work. This is a 5th generation Intel HD Graphics, so not officially supported by OpenVino according to their website.

**Comment by alalek** [comment]
There is no goal to add extra checks for this call.

You can configure/disable OpenCL subsystem in OpenCV.
Check options here: https://github.com/opencv/opencv/wiki/OpenCL-optimizations
