### ISSUE TITLE
AttributeError: module ‘cv2.cv2’ has no attribute ‘ximgproc’

### ISSUE THREAD

**Issue by floriancartuta** [opencv/opencv#17387]
##### System information (version)
opencv-contrib-python==4.2.0.34
opencv-python==4.2.0.34
numpy==1.18.3

Operating System / Platform => Ubuntu 18

##### Problem  description
Trying to initialize selective search segmentation with opencv
`ss = cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()`

And I get an attribute  error: 

> AttributeError: module ‘cv2.cv2’ has no attribute ‘ximgproc’

Hope that the solution will not be to downgrade the open-cv version.

**Comment by dkurt** [comment]
Please check you environment / IDE. This is not OpenCV error.
