### ISSUE TITLE
Propose Median blur feature in Python OpenCV module

### ISSUE THREAD

**Issue by Hyeon9mak** [opencv/opencv#17381]
##### System information (version)
- OpenCV => 4.2.0.32
- Operating System / Platform => OSX 10.15.3(19D76)
- Compiler => Python 3.7.3

##### Detailed description

Unlike other languages(e.g. C#) opencv, Python opencv can only be specified as a square by entering only one value of the Blur mask as an argument to the Median Blur function.

So in Python I wrote my own code to make the blur mask rectangular with two arguments of the opencv Median Blur function.
If possible, please check and add module.

thank you.
``` python
def fixed_MedianBlur(mask):
    mask_rows, mask_cols = mask.shape
    q = []
    for r in range(mask_rows):
        for c in range(mask_cols):
            q.append(mask[r][c])

    q.sort()
    return q[len(q) // 2]

def fixed_MedianBlur_Setup(src, KsizeX, KsizeY):
    dst = src
    src_rows, src_cols = src.shape
    Xr = KsizeX // 2
    Yr = KsizeY // 2

    for r in range(Yr, src_rows - Yr):
        for c in range(Xr, src_cols - Xr):
            mask = src[r - Yr:(r - Yr) + KsizeY, c - Xr:(c - Xr) + KsizeX]
            dst[r, c] = fixed_MedianBlur(mask)

    return dst
```

**Comment by alalek** [comment]
OpenCV is C++ library with strong optimizations.
There is no Python code except bindings over C++ implementation.
