### ISSUE TITLE
opencv-4.1.0-android-sdk use dnn error

### ISSUE THREAD

**Issue by lhxy1991** [opencv/opencv#17407]
- OpenCV => 4.1
- Operating System / Platform => Android 3.6.1
NDK14b, cmake3.6
when i use dnn module , i meet some errors:
.......
error: undefined reference to 'cv::dnn::dnn4_v20190122::Net::setInput
error: undefined reference to 'cv::dnn::dnn4_v20190122::Net::forward(std::string const&)'
error: undefined reference to 'cv::dnn::dnn4_v20190122::readNetFromDarknet
....
The same code is success when i use libopencv_java3.
Does the opencv-4.1.0-android-sdk contans dnn module ? 
If not ,How can i compile it ?

**Comment by asmorkalov** [comment]
@lhxy1991 could you provide some reproducer for the issue?

**Comment by lhxy1991** [comment]
Yes , my Platform  is Android Studio 3.6.1, android-ndk-r14b-windows-x86_64.
I use native method, import libopencv_java4.so with CMakeLists.
A demo can find on the internet,like this:https://www.jianshu.com/p/4871d3dee4fa
Can help you?

**Comment by lhxy1991** [comment]
[opencv4.zip](https://github.com/opencv/opencv/files/4699440/opencv4.zip)


> @lhxy1991 could you provide some reproducer for the issue?

I  can give you a sample. Like this sampel ,
 error: undefined reference to 'cv::dnn::dnn4_v20190902::readNetFromDarknet(std::string const&, std::string const&)'

**Comment by dkurt** [comment]
Please try the newest releases.

Your application is a mix of native and Java code. Have you observed similar issue with other modules? Have you linked `libopencv_dnn.so`?
