### ISSUE TITLE
Serialization : TypeError: cannot pickle 'cv2.VideoCapture' object

### ISSUE THREAD

**Issue by Utopolis** [opencv/opencv#17405]
##### Detailed description :
I got this error : 
TypeError: cannot pickle 'cv2.VideoCapture' object
When I want to use multi processing and send back the instance of the capture to the main program.
Why I need that ? 
Because I need to instanciate several capture at the same time, using multi threading the operation "cap = cv2.videoCapture(rtsp)" is blocking. Using multi process I can parrallelize the creation of the capture. But I need to send them to the main program after.
I already tried version 3.4.8.29 of OpenCV
I already tried using queue and pipe. I got the same problem.
Of what I understood the problem is from pickle. Because when I am using multi process, the process will try to send the Capture in trying to pickle it. Which apparetnly we can not do ?!

Does someone know a workaround ? An other serializer ? 

##### Steps to reproduce

```
import cv2
from multiprocessing import Process, Queue, Pipe, Manager
import multiprocessing
import time


rtsp = "flux rtsp"


def Capture_Process(capture, rts) :
    cap = cv2.VideoCapture(rts)
    capture.append(cap)

manager = Manager()
shared_dict = manager.list()
Processess= []
p = Process(target=Capture_Process, args=(shared_dict, rtsp))
p.daemon = True
p.start()
time.sleep(15)
```

**Comment by alalek** [comment]
This is a wrapper over native C++ object with 3rdparty/OS resource management.
It is not intended to be serialized or transferred somewhere.

Also several video frameworks require all processing calls from one thread (some even from the "main" thread).

You should read captured data (as numpy array) and push that data into concurrent processing queues.

> multiprocessing

be careful, see #5150

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
