### ISSUE TITLE
difference in results between python and c/c++ versions of inpainting function

### ISSUE THREAD

**Issue by AAUDI** [opencv/opencv#17404]
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

1- The c++ version doesnt process the borders
2 - Also, I see sometimes some difference in results between the two versions.

##### Steps to reproduce

cv2.inpaint(np.uint16(self.current["f"]), np.uint8(self.current["mask"] == 1), 3, cv2.INPAINT_NS);
inpaint.execute(im_corr, mask, inpainted);

**Comment by dkurt** [comment]
@AAUDI, please provide reproducer if you wanted to report a bug. Origin image, mask, code snippet, expected and observed results.
