### ISSUE TITLE
COLOR_YUV2RGBA_NV21 not working when adding any optimization flag

### ISSUE THREAD

**Issue by davidmartos96** [opencv/opencv#17413]
I'm using the latest Android OpenCV prebuilt SDK (4.3) to create a cpp shared library (cross compiling using the NDK r21) to use from the Dart FFI on Flutter to process the camera bytes. 

I'm using the `COLOR_YUV2RGBA_NV21` color transformation and it works great until the .so is built with any of the O flags turned on. If code optimization is turned on, then the returned image has flickery artifacts at the bottom and at the right of the image and the B and R channels are swapped.

If I compile the shared library for linux with OpenCV 4.2 and I open a (dumped frame) of the Android camera from a Main linked with the library, it also has the same issues. I'm using CMake with `-DCMAKE_BUILD_TYPE=Release`. `RelWithDebInfo` fails as well.

This is the CMakeLists.txt file to build the shared library:

```
add_library( DisplayImage SHARED MyLib.cpp )
target_include_directories(MyLib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

find_package( OpenCV REQUIRED )

target_link_libraries( MyLib  ${OpenCV_LIBS} )
```
This is the output image, weird green stripe at the bottom and it is red instead of blue. This is just a captured frame, but with the Android camera, the green stripe is flickering every frame, is not static.

![image](https://user-images.githubusercontent.com/22084723/83170228-80c47d00-a114-11ea-8fa8-194f0071a1fd.png)

I'm actually clueless on what could be wrong here.
* Is it OpenCV? (It works fine with Debug type on both Android and Linux)
or
* Am I building the shared library wrong and the compiler is optimizing out things that it should not?

Any help to know what could be going on here would be very appreciated.
Thank you.

I provide the raw camera frame with Y, U and V planes merged.
I can provide the relevant library code that converts the camera frame to RGB if needed.

[dumped_frame_inside.zip](https://github.com/opencv/opencv/files/4697197/dumped_frame_inside.zip)

**Comment by alalek** [comment]
Green result usually means that NV12 data become zeros.

Please add code and dump input parameters (dimensions - for NV12 they must be even).

For investigation of geometry or color issues it is better to capture images like this: https://en.wikipedia.org/wiki/File:AdditiveColor.svg

**Comment by davidmartos96** [comment]
After some more investigation it turned out to be other code that interacted with the planes data. The manipulation returned a different result because there were some pointer operations involved, which didn't hold with compiler optimizations. It is resolved now. 
Thank you
