### ISSUE TITLE
Building OpenCV for Raspberry PI 4 / Ubuntu Server 64 bit with compiler optimizations

### ISSUE THREAD

**Issue by d-v-s** [opencv/opencv#17429]
##### System information (version)
- OpenCV => 4.3.0
- Operating System / Platform => Ubuntu Server 64bit / Raspberry PI 4
- Compiler => gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0,   g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0

##### Detailed description

How to build OpenCV for Raspberry PI 4 running under Ubuntu Server 64 bit with compiler optimizations?

##### Steps to reproduce
I've used very good instruction from [->here<-](https://qengineering.eu/install-opencv-4.3-on-raspberry-pi-4.html).
But trying to build with Neon and VFPV3 support failed using following flags:
```
$ cmake ......
        -D ENABLE_NEON=ON \
        -D ENABLE_VFPV3=ON \
        ...........
```
With the only NEON flag it works but with VFPV3 it doesn't. 
Most optimizations from [->here<-](https://gist.github.com/fm4dd/c663217935dc17f0fc73c9c81b0aa845) fails e.g. `-mfloat-abi` and `-mfu` compiler options.

##### What solution I've found
I've struggled a lot with using compiler options. A lot of google and hours. But there's not much info about building for aarch64 platform with all optimizations. Finally I've found some explanation [->here<-](https://lists.linaro.org/pipermail/linaro-toolchain/2016-July/005814.html). It was not easy to find such an explanation. I advice to read the full story there (use links inside).
Citation:
> -mfpu=neon-fp-armv8 is an arm (32-bit) compiler option.  The aarch64 (64-bit) compiler will not accept it.
> The aarch64 spec requires FP and ASIMD instruction support in the linux ABI, so there are no options to enable them, they are on by default.

It made me think that I should look the other way. I've found how to get all optimization parameters for my compiler using command: 
```
$ g++ -Q --help=target
The following options are target specific:
  -mabi=                      		lp64
  -march=                     		armv8-a
  -mbig-endian                		[disabled]
  -mbionic                    		[disabled]
  -mbranch-protection=        		
  -mcmodel=                   		small
  -mcpu=                      		generic
  -mfix-cortex-a53-835769     		[enabled]
  -mfix-cortex-a53-843419     		[enabled]
  -mgeneral-regs-only         		[disabled]
  -mglibc                     		[enabled]
  -mlittle-endian             		[enabled]
  -mlow-precision-div         		[disabled]
  -mlow-precision-recip-sqrt  		[disabled]
  -mlow-precision-sqrt        		[disabled]
  -mmusl                      		[disabled]
  -momit-leaf-frame-pointer   		[enabled]
  -moutline-atomics           		[disabled]
  -moverride=<string>         		
  -mpc-relative-literal-loads 		[enabled]
  -msign-return-address=      		none
  -mstack-protector-guard-offset= 	
  -mstack-protector-guard-reg= 		
  -mstack-protector-guard=    		global
  -mstrict-align              		[disabled]
  -msve-vector-bits=<number>  		scalable
  -mtls-dialect=              		desc
  -mtls-size=                 		24
  -mtrack-speculation         		[disabled]
  -mtune=                     		generic
  -muclibc                    		[disabled]
  -mverbose-cost-dump         		[disabled]
```

As I understood that's are default parameters used during compilation. Very interesting that `mcpu` and `mtune` had value `generic`  meaning  that GCC should tune the performance for a blend of processors within architecture `-arch`  ([->read in details here<-](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html)).
To get the actual values for exactly RPI4 I've tried the command:
```
$ gcc -Q -march=native -mcpu=native -mtune=native --help=target | grep 'march\|mtune\|mcpu'
  -march=                     		armv8-a+crc
  -mcpu=                      		cortex-a72
  -mtune=                     		cortex-a72
```
I suppose it can give some increase in performance at least by optimizing code for exactly cortex-a72.
I've added the following lines just at the beginning of CMakeLists.txt:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=armv8-a+crc -mcpu=cortex-a72 -mtune=cortex-a72")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a+crc -mcpu=cortex-a72 -mtune=cortex-a72")
```
Then successfully built. I've seen that new params were used by compiler in the output.
Unfortunately I haven't made any benchmark tests with default and optimized flags.

---------------------------------------

So please advise me whether I've made everything right or missed something. Is there anything else I should do for optimization?
Thank's in advance.

**Comment by alalek** [comment]
Please read CMake documentation first.
For example, you are looking for this page: https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html

---

`ENABLE_*` flags are deprecated in OpenCV.

`-march=native -mcpu=native -mtune=native` (or even `-march=native`) is enough without specific values (for cases without cross-compilation)

Check this section of OpenCV's CMake output:
```
--   CPU/HW features:
--     Baseline:                    NEON FP16
```

**Comment by d-v-s** [comment]
> `ENABLE_`* flags are deprecated in OpenCV.

What should I use instead? In [arm.toolchain.cmake](https://github.com/opencv/opencv/blob/master/platforms/linux/arm.toolchain.cmake) I see:
```
if(USE_NEON)
  message(WARNING "You use obsolete variable USE_NEON to enable NEON instruction set. Use -DENABLE_NEON=ON instead." )
  set(ENABLE_NEON TRUE)
```

--

>Check this section of OpenCV's CMake output:
> ```
> --   CPU/HW features:
> --     Baseline:                    NEON FP16
> ```
I had the same output. Also in line of compiler params there were specified compiler options `-march=armv8-a+crc -mcpu=cortex-a72 -mtune=cortex-a72`

**Comment by alalek** [comment]
> What should I use instead?

Nothing. It is handled in other places automatically.

**Comment by dkurt** [comment]
Has been issue solved?

**Comment by d-v-s** [comment]
> Has been issue solved?

I'm not sure. I hoped somebody could tell me more than just using `-march=armv8-a+crc -mcpu=cortex-a72 -mtune=cortex-a72`

**Comment by mshabunin** [comment]
- AArch64 includes NEON
- NEON includes VFPv3

So, you don't need anything to enable NEON and VFPv3 when compiling for AArch64.

ARM cmake toolchain file located in OpenCV repository has some generic parameters and is meant to work with cross-compilers provided by Ubuntu (host system). You can create your own cmake toolchain files for your specific architecture/compiler/environment and use them instead. Or find one in the internet, e.g. https://github.com/DynamoRIO/dynamorio/blob/master/make/toolchain-arm64.cmake

**Comment by d-v-s** [comment]
In my first message I've mentioned that I'm compiling on RPi4 itself (without cross-compiling).
I just wonder if I can boost performance using all available special flags exactly for RPi4.

>     AArch64 includes NEON
>     NEON includes VFPv3
> 
> So, you don't need anything to enable NEON and VFPv3 when compiling for AArch64.

It is written [here](https://gist.github.com/fm4dd/c663217935dc17f0fc73c9c81b0aa845) that RPi4 has **VFPv4**.
Is this feature enabled by default when I compile for aarch64? Because for non-aarch64 it should be specified explicitly.

**Comment by mshabunin** [comment]
OpenCV on its own does not add any flags for AARCH64, NEON and other optimizations are implied:
https://github.com/opencv/opencv/blob/a5fdcf9881176ce756b601ee4b926586a88a42fe/cmake/OpenCVCompilerOptimizations.cmake#L326-L345

The thing called VFPV3 here is for older ARMv7 processors without NEON, it enables single optimization in cvRound which will be enabled when NEON is available:
https://github.com/opencv/opencv/blob/a5fdcf9881176ce756b601ee4b926586a88a42fe/modules/core/include/opencv2/core/fast_math.hpp#L84-L100

So there is nothing to tune for this platform on OpenCV side, you should find the best suiting g++ options just like for any other application.

I'm closing the issue since there is no evidence of a problem in the library, feel free to comment/reopen if you have more information.
