### ISSUE TITLE
videoWriter para "iscolor" is not do any things, I get 3-Chns gray image which I want 1-Chn gray image

### ISSUE THREAD

**Issue by lzcchl** [opencv/opencv#17423]
code:
import numpy as np
import cv2
cap = cv2.VideoCapture('intput.avi')
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 30.0, (384,288), False)
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret==True:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        out.write(frame)
        cv2.imshow('frame',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()

**Comment by lzcchl** [comment]
my opencv version is opencv3.4.6, is that be solved in high version, or my code is not good?

**Comment by asmorkalov** [comment]
`VideoCapture` return BGR frames by default, even if original video is grayscale.
