### ISSUE TITLE
opencv4.3.0 GPU yolov3 cudnn10.0 and cudnn10.2

### ISSUE THREAD

**Issue by lzcchl** [opencv/opencv#17426]
hello, I have test GPU yolov3 on cudnn10.0 and cudnn10.2, which cudnn10.0 use CUDA memory about 700M, but cudnn10.2 use 1400M, is there any bug?

**Comment by YashasSamaga** [comment]
The memory required depends on what algorithms are chosen for different operations. This can vary from version to version. But 2x memory usage is a bit unusual but still possible.

What version of cuDNN are you using? (you seem to have confused CUDA toolkit version with cuDNN version)

How did you measure the memory usage?

**Comment by dkurt** [comment]
Closing due no response from author
