### ISSUE TITLE
opencv with cuda10.1. No problem in release mode, but in debug model:

### ISSUE THREAD

**Issue by wangzhongju** [opencv/opencv#17422]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => Windows10  64 Bit
- Compiler => Visual Studio 2019
- cuda 10.1
- GPU RTX 2080Ti

##### Detailed description
> [ INFO:0 ] global  D:\**\**\opencv430\modules\videoio\src\videoio_registry.cpp<187>  cv::'anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry DIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)

> [ INFO:0 ] global D:\**\**\modules\videoio\src\backend_plugin.cpp(353) cv::impl::getPluginCandidates Found 2 plugin(s) for FFMPEG

> [ INFO:0 ] global D:\**\**\modules\videoio\src\backend_plugin.cpp (233) cv::PluginBackend Video I/O: loaded plugin 'FFMPEG OpenCV Video I/O plugin'

> [ INFO:0 ] global D:\**\**\modules\dnn\src\dnn.cpp (2353) cv::dnn::dnn4_v20200310::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

**Models cannot be accelerated with GPU, instead using CPU.**
**How to solve this problem? pls!**

**Comment by YashasSamaga** [comment]
> Models cannot be accelerated with GPU, instead using CPU.

That shouldn't be happening. How did you verify this? The debug build might be slower but it should still be using the GPU.

**Comment by priyamnagar** [comment]
I am also facing the same issue. In release mode the GPU usage is 20% but in debug it is showing these [INFO] messages and the gpu usage is only 4%.

**Comment by YashasSamaga** [comment]
> I am also facing the same issue. In release mode the GPU usage is 20% but in debug it is showing these [INFO] messages and the gpu usage is only 4%.

That depends on your code. The GPU is used only during inference. The GPU stays idle during preprocessing, postprocessing and during other CPU work.

You have to make a pipeline or run multiple inferences at a time to keep the GPU busy always.

**Comment by priyamnagar** [comment]
Hi, Thanks for your reply. 
Here I am using the same code for release and debug both. GPU usage is always 20% for release and 5% for debug. 
Is this some kind of feature or I am doing something wrong?

**Comment by alalek** [comment]
> GPU usage is always 20% for release and 5% for debug.

What is expected?
Why is it expected?

**Comment by priyamnagar** [comment]
I want to use OpenCV with Cuda support for inferencing an object detection model (YOLOv3). But I am seeing a lot of variations in speed and GPU usage when I switch between Release and Debug modes.

When I build OpenCV in release mode everything works fine, without any messages, the GPU utilization is 20% and the speed i am getting is 50 - 60 ms per frame.

When I build OpenCV in Debug mode I get some [INFO] messages mentioned below:

 `[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\videoio_registry.cpp (191) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940) `    

`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\backend_plugin.cpp (370) cv::impl::getPluginCandidates Found 3 plugin(s) for FFMPEG    `                                                                    

`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load D:\Study\Phase 1_ Programming\1.C++\Code\opencv_test\opencv_test\opencv_videoio_ffmpeg440_64d.dll => FAILED                                                                                                        
`
`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg440_64d.dll => FAILED    `                                            

`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg440_64.dll => OK    `
                                                  
`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\videoio\src\backend_plugin.cpp (236) cv::impl::PluginBackend::PluginBackend Video I/O: loaded plugin 'FFmpeg OpenCV Video I/O plugin' `                                

`[ INFO:0] global D:\Study\tools\opencv\opencv-4.4.0\opencv-4.4.0\modules\dnn\src\dnn.cpp (2401) cv::dnn::dnn4_v20200609::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer___ `

After I get these messages the speed of the code falls down to 125 - 140 ms and the GPU usage is just 5%.

I want to understand why this is happening?
Is there any problem with the build?

**Comment by eLtronicsVilla** [comment]
> > I am also facing the same issue. In release mode the GPU usage is 20% but in debug it is showing these [INFO] messages and the gpu usage is only 4%.
> 
> That depends on your code. The GPU is used only during inference. The GPU stays idle during preprocessing, postprocessing and during other CPU work.
> 
> You have to make a pipeline or run multiple inferences at a time to keep the GPU busy always.

Hi,
I'm also getting same error in debug mode ( CUDA backend will fallback to the CPU implementation ) 
and in Release mode GPU utilisation is 5% only.

System information (version) below for my opencv with cuda build .

OpenCV = 4.2.0
Operating System / Platform = Windows10 64 Bit
Compiler => Visual Studio 2019
cuda 10.1
GPU NVIDIA GeForce GTX 1050Ti

Even I'm running multiple inference to keep on GPU busy always. But still getting same ( 5% in release mode for opencv 4.2.0)
What could be reason for this? 

Thanks in advance.

**Comment by YashasSamaga** [comment]
@eLtronicsVilla 

>  I'm also getting same error in debug mode ( CUDA backend will fallback to the CPU implementation )

You can get the same information if you set `OPENCV_LOG_LEVEL` to `INFO` in release build.

```
export OPENCV_LOG_LEVEL=INFO
```

What layers are using fallbacks?

**Comment by priyamnagar** [comment]
@YashasSamaga i am using Cudnn = 7.6.5 cuda = 10.2 input_shape  =640X480.
I am using the same code for both. net.forward() is taking 35 - 40ms for release and debug both.

Can you please help me in understanding why overall speed variation is there. I have shared with you the code via email(yashas_2010@yahoo.com).

**Comment by YashasSamaga** [comment]
> net.forward() is taking 35 - 40ms for release and debug both.

Use OpenCV 4.4.0 for much higher performance. You can get even higher performance with FP16 target (< 10ms per frame) with negligible accuracy loss.

Your code has to read frames from a video source, preprocess, postprocess and then display it. These tasks execute on CPU. The GPU stays idle during this time and therefore, reduces the average GPU utilization.

**Comment by priyamnagar** [comment]
Thank you so much for your help. Understood a lot about it.
But I still don't understand how the speed and utilization are different for release and debug modes. I am using the same code for both.

**Comment by YashasSamaga** [comment]
>  But I still don't understand how the speed and GPU utilization are different for release and debug modes. I am using the same code for both.

Debug builds are slower. The CPU part of your code takes more time to execute. This means that your GPU is idle for a longer time.

CPU code is optimized in release build. CPU code executes faster. Therefore, the GPU spent less time idling as the CPU is able to dump work to the GPU more often.

**Comment by YashasSamaga** [comment]
@wangzhongju I see that you edited the question after my first comment. You can get the same set of messages if you set `OPENCV_LOG_LEVEL` to `INFO`.

```
export OPENCV_LOG_LEVEL=INFO
```

> cv::dnn::dnn4_v20200310::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type NetInputLayer

This doesn't matter. The input layer is skipped most of the times. If that's the only message you got, it implies that your model is mostly fully running on the GPU.

**Comment by eLtronicsVilla** [comment]
Hi,
For me debug log for the same.

[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\videoio_registry.cpp (187) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (353) cv::impl::getPluginCandidates Found 2 plugin(s) for GSTREAMER
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load E:\workspace\workspace\opencv_cuda_test\opencv_cuda\x64\Debug\opencv_videoio_gstreamer420_64.dll => FAILED
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load opencv_videoio_gstreamer420_64.dll => FAILED
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\core\src\ocl.cpp (891) cv::ocl::haveOpenCL Initialize OpenCL runtime...
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__
[ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "detection_out" of type DetectionOutput

**Comment by YashasSamaga** [comment]
@eLtronicsVilla 
> cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type NetInputLayer

You can ignore this.

> cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "detection_out" of type DetectionOutput

CUDA version of this layer is available on master.

**Comment by eLtronicsVilla** [comment]
Okay, Thanks for this information.

**Comment by shourya27** [comment]
> Hi,
> For me debug log for the same.
> 
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\videoio_registry.cpp (187) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (353) cv::impl::getPluginCandidates Found 2 plugin(s) for GSTREAMER
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load E:\workspace\workspace\opencv_cuda_test\opencv_cuda\x64\Debug\opencv_videoio_gstreamer420_64.dll => FAILED
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load opencv_videoio_gstreamer420_64.dll => FAILED
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\core\src\ocl.cpp (891) cv::ocl::haveOpenCL Initialize OpenCL runtime...
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type **NetInputLayer**
> [ INFO:0] global E:\workspace\workspace\opencv_build\opencv-4.2.0\opencv-4.2.0\modules\dnn\src\dnn.cpp (2204) cv::dnn::dnn4_v20191202::Net::Impl::initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "detection_out" of type DetectionOutput

if you get the solution please tell me I am also having same issue.

**Comment by yuntong613** [comment]
if you get the solution please tell me I am also having same issue.

**Comment by CodiTrixta** [comment]
Getting a similar issue running on docker:

[ INFO:0] global /opt/opencv-4.5.0/modules/dnn/src/dnn.cpp (2405) initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

[ INFO:0] global /opt/opencv-4.5.0/modules/dnn/src/dnn.cpp (2405) initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "NHWC_output" of type DepthToSpace
