### ISSUE TITLE
DNN module parallel inferencing

### ISSUE THREAD

**Issue by sudapure** [opencv/opencv#17435]
OpenCV DNN module does well for different CNN models like ssd mobilenet, ssd inception, Yolo, etc. for single model execution, but while tried inferring models concurrently, for different video feeds, latency gets doubled for same model executions, just explain a simple case, while inferring model on single video feed, it gives decent latency of **x** ms , but while executed same model concurrently for more than one video feed, latency increases significantly. it looks like parallelism issue with underlying DNN module implementation, which does not support concurrent infer requests.

**Comment by alalek** [comment]
> executed same model concurrently

Invalid usage. Different model instances should be used until it is noted separately.
https://docs.opencv.org/master/d1/dfb/intro.html

---

> while tried inferring models concurrently
> latency gets doubled for same model executions

Why is it should not do that?
Single inference request uses 80-100% of available resources (in case of CPU).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
