### ISSUE TITLE
Fix "nvcc fatal : Could not set up the environment for Microsoft Visual Studio"

### ISSUE THREAD

**Issue by mat46ias** [opencv/opencv#17440]
- OpenCV => 4.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
Hi! I'm trying to buil OpenCV from source with CUDA v10.2. I'm followgin the steps from this website:

[https://jamesbowley.co.uk/accelerate-opencv-4-3-0-build-with-cuda-and-python-bindings/?unapproved=22839&moderation-hash=3a2ab3aba913aa8519aaf53a0a431bf0#comment-22839](url)

When I reach the part of building the solution I get the following error:

`Building NVCC (Device) object modules/world/CMakeFiles/cuda_compile_1.dir/__/core/src/cuda/Release/cuda_compile_1_gen
erated_gpu_mat.cu.obj`
`nvcc fatal : Could not set up the environment for Microsoft Visual Studio using ‘C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/../../../../../../../VC/Auxiliary/Build/vcvars64.bat`
`CMake Error at cuda_compile_1_generated_gpu_mat.cu.obj.Release.cmake:220 (message):`
`Error generating`
`D:/OpenCV/opencv-4.3.0/build/modules/world/CMakeFiles/cuda_compile_1.dir/__/core/src/cuda/Release/cuda_compile_1_ge
nerated_gpu_mat.cu.obj`

I really don't know how to fix this...

**Comment by victormaggie** [comment]
Hi, did you solve it? I came across the same issue. have no idea how to fix it

**Comment by victormaggie** [comment]
Hi there, not sure if you solved this issue or not. I fixed this problem by update CUDA to 10.2 and 
![image](https://user-images.githubusercontent.com/15321482/84222213-a189bc80-aa9c-11ea-959c-c4888573c536.png)

Make sure add all this path to environment path. Then it should be ok!

**Comment by johncaling40** [comment]
> Hi there, not sure if you solved this issue or not. I fixed this problem by update CUDA to 10.2 and
> ![image](https://user-images.githubusercontent.com/15321482/84222213-a189bc80-aa9c-11ea-959c-c4888573c536.png)
> 
> Make sure add all this path to environment path. Then it should be ok!

I added all 5 of those paths to the path variable and still error.

**Comment by jamesratzlaff** [comment]
Make sure your PATH, INCLUDE, LIB, and LIBPATH environment variables do not have any quotes in them

**Comment by johncaling40** [comment]
They dont

**Comment by jamesratzlaff** [comment]
I believe *any* variable that has double quotes (and those quotes are not escaped with a backslash) that gets used in a build/compile/link command can cause this.  Double check vars used in your CMakeCache as well.  One thing you can try is removing is setting the environment variable ```VSCMD_DEBUG=3``` and running the full nvcc commmand that keeps failing.

**Comment by johncaling40** [comment]
Still no luck

**Comment by jamesratzlaff** [comment]
What is the output when you run the nvcc command?

**Comment by johncaling40** [comment]
Error. No input files specified.

**Comment by TauCeti0207** [comment]
I have the same problem
I am trying to update the cuda to 11.5....
