### ISSUE TITLE
Cant able to use yolov4 in opencv

### ISSUE THREAD

**Issue by AkhilGKrishnan** [opencv/opencv#17479]
I encountered this issue when I use dnn library to read yolov4 cfg and weight file.

net = cv.dnn.readNetFromDarknet(FLAGS.config, FLAGS.weights)

cv2.error: OpenCV(4.2.dev) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'

**Comment by KyloEntro** [comment]
Yolov4 is not supported by Opencv 4.2.0 and 4.3.0. 
The last version in master branch support YoloV4

**Comment by oboyraz** [comment]
how can i and from where to install the last version opencv - master branch.

**Comment by jason11501** [comment]
!pip3 install --upgrade opencv-python==4.5.5.64

then restart runtime
then check version again follows:

import cv2
cv2.__version__

**Comment by alimousavi1377** [comment]
I want to test yolov4 but the OpenCV version 4.5.5.64 does not support my weights

error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: /content/gdrive/MyDrive/yolov4_training_last.weights in function 'readNetFromDarknet'

please help me
