### ISSUE TITLE
Suggestion : support cv::Scalar() in cv::norm() inputs

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#17482]
To save time and avoid creating temporary intermediate results for some advanced computations, I would find valuable to support cv::Scalar() as inputs for cv::norm()
As a counterpart, the code size of cv::norm() would certainly be almost doubled, not sure you would accept that.

**Comment by dkurt** [comment]
@chacha21, As for me, interpretation of `cv::Scalar` as point is not a good idea. Do you mean `cv::Point3d` in example?

**Comment by chacha21** [comment]
No, I don't mean that.
Here is an example :

```
cv::Mat m(someSize, 8UCV1);
cv::Mat tmp;
cv::absdiff(m, cv::Scalar(128), tmp);
cv::minMaxLoc(tmp, 0, &sup);

```

could be replaced by

```

cv::Mat m(someSize, 8UCV1);
sup = cv::norm(m, cv::Scalar(128), cv::NORM_INF);
```

Unfortunately, cv::norm() does not accept cv::Scalar() as input to represent a uniform matrix.

**Comment by alalek** [comment]
`norm()` is a critical function for result verification.
I would prefer to keep strict behavior of `norm()` function by not introducing `Scalar()` support.

Mentioned comparison with 128 is not used too often and we have a workaround for that.

**Comment by vpisarev** [comment]
agree. Also, you may also consider g-api (https://github.com/opencv/opencv/wiki/Graph-API) that lets you to combine image processing operations into efficient pipelines.
