### ISSUE TITLE
std::min, max build problem

### ISSUE THREAD

**Issue by xjsxujingsong** [opencv/opencv#17487]
##### Detailed description

CMake:
"C:/Program Files/CMake/bin/cmake.exe"  -G "Visual Studio 15 2017 Win64"  ^
-DBUILD_opencv_python3=ON   ^
-DPYTHON3_EXECUTABLE=C:/Users/xjsxu/Anaconda3/python3.exe  ^
-DPYTHON3_LIBRARY=C:/Users/xjsxu/Anaconda3/libs/python37.lib  ^
-DPYTHON3_INCLUDE_DIR=C:/Users/xjsxu/Anaconda3/include  ^
-DPYTHON3_PACKAGES_PATH=C:/Users/xjsxu/Anaconda3/Lib/site-packages  ^
-DPYTHON3_NUMPY_INCLUDE_DIRS=C:/Users/xjsxu/Anaconda3/Lib/site-packages/numpy/core/include ^
-DOPENCV_SKIP_PYTHON_LOADER=ON ^
-DINSTALL_TESTS=OFF -DINSTALL_C_EXAMPLES=OFF -DBUILD_EXAMPLES=OFF ^
-DBUILD_opencv_world=ON ^
-DWITH_CUDA=ON -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0" -DCUDA_FAST_MATH=ON -DWITH_CUBLAS=ON -DCUDA_ARCH_BIN=5.3,6.0,6.1,7.0,7.5 -DCUDA_ARCH_PTX=7.5 -DWITH_NVCUVID=ON ^
-DWITH_OPENGL=ON ^
-DWITH_MFX=ON ^
-DOPENCV_ENABLE_NONFREE=ON  -DBUILD_opencv_rgbd=OFF ^
-DWITH_MKL=ON ^
 ../sources
 
 
 
build with the latest extra module. 

Error:
D:/study/opencv/opencv-4.3.0-dev/opencv/sources/modules/imgproc/src/color_yuv.simd.hpp(350): error C2059: syntax error: 'constant'
1>D:/study/opencv/opencv-4.3.0-dev/opencv/sources/modules/imgproc/src/color_yuv.simd.hpp(353): error C2440: '=': cannot convert from 'cv::hal_SSE4_1::v_int32x4' to 'int'
1>D:/study/opencv/opencv-4.3.0-dev/opencv/sources/modules/imgproc/src/color_yuv.simd.hpp(353): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>D:/study/opencv/opencv-4.3.0-dev/opencv/sources/modules/imgproc/src/color_yuv.simd.hpp(354): error C2065: 'scb0': undeclared identifier
1>D:/study/opencv/opencv-4.3.0-dev/opencv/sources/modules/imgproc/src/color_yuv.simd.hpp(355): error C2065: 'scb1': undeclared identifier

**Comment by xjsxujingsong** [comment]
Anyone met this problem?
In the same machine, I can sucessfully build Version 4.3.0, but cannot build on the latest version.

**Comment by dkurt** [comment]
Have you tried the latest master branch? Maybe build folder clean may help

**Comment by xjsxujingsong** [comment]
Yes. I did try the latest version yesterday. it worked. pls close this issue.
