### ISSUE TITLE
Mobilenetv2 using cuda is slow than using cpu？ 

### ISSUE THREAD

**Issue by zhangcj13** [opencv/opencv#17515]
##### System information (version)
- OpenCV => 4.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- CUDA => 10.2 cudnn:7.6  with gtx1070
##### Detailed description
Test with yolov3 model      （Cpu 174.90ms; CUDA： 39.74ms）
but test with mobilenetv2 （Cpu   21.30ms; CUDA：110.70ms）
Is it cause by the group conv of mobilenetv2？

**Comment by YashasSamaga** [comment]
Convolution algorithms are chosen heuristically by cuDNN. The heuristics are not correct for depthwise convolutions.

#16900 fixes the problem.

**Comment by zhangcj13** [comment]
@YashasSamaga 
thank you for your reply and great job. I will try it!
