### ISSUE TITLE
Taking a 3D array as an input

### ISSUE THREAD

**Issue by AmirHarvey** [opencv/opencv#17529]
System information (version):
- OpenCV => 4.3
- Operating System  => Windows 64 Bit
- Compiler => python 3.7

 Detailed description:
Hello there, i am trying to take a camera's reading from a simulator which is a 3D array as an input in OpenCV so i used cv2.VideoCapture(int(reading)) but it gave me an error "TypeError: only size-1 arrays can be converted to Python scalars"

Any idea what to do ?
Thanks is advance.

**Comment by AND2797** [comment]
I believe you are trying to capture video-frames from your camera? I believe your 3D array is the image or one frame of a video / video feed, and you are trying to pass that into `cv2.VideoCapture` (not sure, but what I understood from your description.) 
`cv2.VideoCapture()` either takes in the 'camera' (if you have only 1 camera, it should be 0 by default) so you would use `cv2.VideoCapture(0)` for it.  Or you can pass in a video file into it. 
Maybe you can share more information of where you are getting your 3D array `reading` from?

**Comment by AmirHarvey** [comment]
I am using Carla Simulator and i added cameras to it, so i'm dealing with simulator cameras not real cameras or a video file that's why cv2.VideoCapture() didn't work for me.

**Comment by mshabunin** [comment]
You have to use CARLA interfaces then (https://carla.readthedocs.io/en/stable/cameras_and_sensors/). OpenCV does not have integration with it.
