### ISSUE TITLE
Crash invoking SIFT from Swift binding

### ISSUE THREAD

**Issue by komakai** [opencv/opencv#17547]
##### System information (version)

- OpenCV => master
- Operating System / Platform => MacOS/iOS
- Compiler => Xcode

##### Detailed description

Crash In following code:
```.swift
 let sift = SIFT.create(nfeatures: 800)
 let keypoint1 = NSMutableArray(), keypoint2 = NSMutableArray()
 let descriptors1 = Mat(), descriptors2 = Mat()
 sift.detectAndCompute(image: m1Gray, mask: Mat(), keypoints: keypoint1, descriptors: descriptors1)
```

`[Algorithm detectAndCompute:mask:keypoints:descriptors:]`: unrecognized selector sent to instance 0x600002d84410
##### Steps to reproduce

Run the above code

##### Cause

Looks like the call to `SIFT.create` does not allocate an object of type `SIFT`( it allocates an object of the base-type `Algorithm` instead)

Working on a fix now

**Comment by komakai** [comment]
I have put a fix in https://github.com/komakai/opencv/commit/53e37c8e6d991c99e4b4ecf6a63581f906ad6a58
but unfortunately I hit another problem
<img width="1208" alt="Screenshot 2020-06-15 at 10 39 48" src="https://user-images.githubusercontent.com/5875290/84610807-e7101480-aef6-11ea-9839-dab004f8a092.png">

I start of with a cv::SIFT* which gets cast to a cv::Algorithm* 
Then it crashes trying to make a cv::Ptr<cv::Feature2D> from that  cv::Algorithm* 
@alalek any idea where I'm going wrong?

**Comment by alalek** [comment]
> `cv::Ptr<cv::Feature2D>` from that `cv::Algorithm*`

Consider storing of `cv::Ptr< OpenCVClass >` (or `cv::Ptr< OpenCVClass >*`) as a "nativePtr" instead of RAW class pointers:
- proper lifetime management
- align with Python / Java bindings (assignment `b = a` doesn't make an object copy - just refcount increased)

Almost all OpenCV classes should follow this expect special ones (not designed as a "smart classes"):
- `CV_EXPORTS_W_SIMPLE`
- `CV_EXPORTS_W_MAP`

**Comment by komakai** [comment]
@alalek thanks for the hint - after switching to use cv:Ptr and a bit of rework I could get SIFT working
