### ISSUE TITLE
[imgproc] Compilation error caused by color_yuv.simd.hpp

### ISSUE THREAD

**Issue by philippefoubert** [opencv/opencv#17546]
##### System information (version)
- OpenCV => 4.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw32

##### Detailed description

The symbol "scr1" is already defined in the mingw-w64 runtime package in "mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\include\dlgs.h" (included through "windows.h" for example).

##### Steps to reproduce

The compilation fails.

##### Several ways to solve this issue

1. The ugliest one would be to add at the beginning of this file:
```
#if defined scr1
#  undef scr1
#endif  // scr1
```

2.  A better one should be to avoid including the "windows.h" file before "color_yuv.simd.hpp"

3. An alternative could be the renaming of variables.

The guilty mingw32 "dlgs.h" file:
[dlgs_h.txt](https://github.com/opencv/opencv/files/4776326/dlgs_h.txt)

**Comment by alalek** [comment]
Thank you for report!

Option 1 with workaround looks good to me.
Option 3 is acceptable too (these variables are local): `scr1` => `v_scr1`.

---

Included headers can be captured by adding `-H` option into the failed command (`make VERBOSE=1` should show failed command)

---

relates https://github.com/opencv/opencv_contrib/issues/2568

**Comment by philippefoubert** [comment]
cf. PR #17577
