### ISSUE TITLE
Numpy vectorisation for Keypoints

### ISSUE THREAD

**Issue by PrasadNR** [opencv/opencv#17549]
In relation to https://github.com/opencv/opencv/issues/10562#issuecomment-643784337 , Keypoints are not currently numpy arrays in Python. When I am doing ORB detection and matching, I have to loop through the keypoints. If Keypoints detectors and descriptors happen to be 2D numpy arrays (each Keypoint in a row) and 3D numpy arrays (each 2D descriptor stacked together to get 2D), that would be great!

If there is an option to convert cv2.Keypoints to numpy arrays, I didn't find any documentation regarding that on opencv.org.

**Comment by alalek** [comment]
AFAIK, numpy array stores data of the same type only.
Keypoints hold data of int/float types.

Descriptors are already numpy arrays (list of them).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by PrasadNR** [comment]
@alalek , Thanks for the response. Currently, I do have an application in which I am using numpy predominantly and I figured there is no way to use Keypoints with vectorised code (for example, I cannot query keypoints in a certain range without looping). The reason why I opened this issue is because there is no supporting documentation around vectorisation either.

**Comment by PrasadNR** [comment]
Also, the C++ interface for Python is not stable for numpy even for descriptors. I am trying to combine descriptors of multiple images. If I begin with numpy zeros, I get the following error:

> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\features2d\src
\matchers.cpp:756: error: (-215:Assertion failed) _queryDescriptors.type() == tr
ainDescType in function 'cv::BFMatcher::knnMatchImpl'

When I do
```
combinedDes = np.vstack([np.zeros([0, 32]), des])
combinedDes = np.vstack([combinedDes, des])
combinedDes = np.vstack([combinedDes, des])
```

This works if I replace `np.zeros([0, 32])` with actual descriptor.

For the information, I am using Windows 8.1, Python 3.7.5 with OpenCV version 4.2.0.
What I am reporting for Keypoint detectors and descriptors is one among plenty of issues I am seeing. Vectorisation is really hard with the current form. (Both keypoints and descriptors)
