### ISSUE TITLE
Cannot build on aarch64-linux-gnu (Jetson TX2)

### ISSUE THREAD

**Issue by tranzmatt** [opencv/opencv#17558]
I am attempting to build 4.3.0 on a Jetson TX2 running Jetpack 4.3, which is an Ubuntu Bionic based distro.  I have the CUDA 10.2 and CUDNN v7 tools installed and run the following as suggested in the NVidia Jetson forums.

```
 cmake
 -D CMAKE_BUILD_TYPE=RELEASE
 -D CMAKE_INSTALL_PREFIX=/usr/local
 -D INSTALL_PYTHON_EXAMPLES=OFF
 -D INSTALL_C_EXAMPLES=OFF
 -D OPENCV_ENABLE_NONFREE=ON
 -D WITH_CUDA=ON
 -D WITH_CUDNN=ON
 -D OPENCV_DNN_CUDA=ON
 -D ENABLE_FAST_MATH=1
 -D CUDA_FAST_MATH=1
 -D CUDA_ARCH_BIN=6.2
 -D CUDNN_INCLUDE_DIR=/usr/include/aarch64-linux-gnu
 -D CUDNN_LIBRARY=/usr/lib/aarch64-linux-gnu
 -D WITH_CUBLAS=1
 -D OpenBLAS_INCLUDE_DIR=/usr/include/aarch64-linux-gnu
 -D OpenBLAS_LIB=/usr/lib/aarch64-linux-gnu
 -D HAVE_opencv_python3=ON
 -D PYTHON_EXECUTABLE=/usr/bin/python
 -D OPENCV_EXTRA_MODULES_PATH=/home/mclark/Code/OpenCV/opencv_contrib/modules
 -D BUILD_EXAMPLES=OFF ..		

```

Unfortunately, I'm getting link errors.  It tries to link "-laarch64-linux-gnu" in a lot of places and doesn't link "-lcudnn" where it should  

I've attached a tarball of some of the cmake files generated.

[build.zip](https://github.com/opencv/opencv/files/4783125/build.zip)

**Comment by alalek** [comment]
> -D CUDNN_LIBRARY=/usr/lib/aarch64-linux-gnu
> -D OpenBLAS_LIB=/usr/lib/aarch64-linux-gnu

.so files are expected.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by tranzmatt** [comment]
Ah, ok.  I thought those were library paths.  Is there a way to point them at non-standard folders?  On the TX, OpenBlas is in /usr/lib/aarch64-linux-gnu/openblas
