### ISSUE TITLE
DNN-Tengine performance issue on QUAD Cortex A53 1Ghz

### ISSUE THREAD

**Issue by kannanrn** [opencv/opencv#17562]
OpenCV => 3.4.10
Operating System / Platform => Linux / S32v234 A53 Core
Compiler => aarch64-linux-gnu

Was measuring the performance of the Yolo3-tiny weight (~34 mb)file on S32v234 with dog.jpg
interfence timing without T-Engine  : 877ms
interfence timing with T-Engine : 71967 ms

Input and all the condition remains same, except that the opencv library is compiled with and without TEngine. also OPENMP is set to OFF in both the cases.

Does Tengine delivers performance across all 64 bit ARM platform or only on A72 platforms?

**Comment by alalek** [comment]
/cc @liqi-c @vpisarev 

@kannanrn Consider using OpenCV performance test suite for getting reliable results.

**Comment by kannanrn** [comment]
Tried the opencv_perf_dnn both with Tengine and without Tengine.  Attaching the results
opencv_perf_dnn (without Tengine)  - can execute all the test case
opencv_perf_dnn (with Tengine) - Stopped after executing few conv test case.

With the executed test cases, I could see the Conv perf no. are almost same. 
Without TEngine -->
[opencv_perf_dnn_wotengine1.txt](https://github.com/opencv/opencv/files/4791758/opencv_perf_dnn_wotengine1.txt)

With TEngine -->
[opencv_perf_dnn_wtengine.txt](https://github.com/opencv/opencv/files/4791751/opencv_perf_dnn_wtengine.txt)

**Comment by liqi-c** [comment]
@kannanrn  the opencv_perf_dnn test in the same hardware ( S32v234 A53 Core) ?

**Comment by kannanrn** [comment]
Yes, both the tests were run in the hardware.   Compiled enabling OPENMP, PROFILING, PERF TEST.  GCC version is 6.3.1

**Comment by alalek** [comment]
> OPENMP

This library manages CPU resources very aggressively - may ruin performance of other multi-threaded parts of application which don't use OpenMP.
At least you should know about `OMP_WAIT_POLICY=passive` and `KMP_BLOCKTIME=0`

Fast check - disable/limit threading in your app and try again (compare single-threaded mode).

**Comment by kannanrn** [comment]
It is due to toolchain compatibility issue. Thanks.

**Comment by Zrufy** [comment]
How you solve this problem?
