### ISSUE TITLE
DNN YOLOv3 - Slow performace on CPU

### ISSUE THREAD

**Issue by marcusbrito** [opencv/opencv#17565]
- OpenCV => 4.2.0.32
- Operating System / Platform => Docker - python:3.6-slim-buster
- Compiler=> Python 3.6

Hi, I'm trying to run the code at #17185 as it is, but i'm getting really differente numbers.

I have a:
CPU => Ryzen 3 2200G (@3.5GHz x 4), (not so far from: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz x8 at #17185)

I'm getting 1300ms for YOLOv3 416x416, instead of 208.74ms. And for YOLOv3-tiny 416x416, i'm getting 167ms.

I'm simply pip installing OpenCV and other requirements, and then running the code.

Do I need to do/configure anything outside the code to run at those speeds?

**Comment by dkurt** [comment]
> I'm simply pip installing OpenCV and other requirements, and then running the code.

1. Try to build OpenCV from source to compare
2. Use OpenCV performance tests. You need to skip initialization runs
3. For the best performance you may just download OpenVINO (it already contains OpenCV): https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend
