### ISSUE TITLE
The scripts under samples/python/ still are python2 scripts

### ISSUE THREAD

**Issue by Mingli-Yu** [opencv/opencv#17566]
The scripts under samples/python/ still are python2 scripts, we need to switch them to python3.
 $ cd samples/python
The shebang of the python scripts is still python2 as below:
#!/usr/bin/env python

**Comment by Mingli-Yu** [comment]
The scripts under samples/python/ should move to python3 as more system doesn't support python2 any more.

**Comment by alalek** [comment]
> The shebang of the python scripts is still python2

https://github.com/opencv/opencv/blame/4.3.0/samples/python/demo.py#L1
```
#!/usr/bin/env python
```

This is fine.
No way to put `python3` here.

Just `python` works fine on properly configured systems.
```.bash
alalek ~$ which python
/usr/bin/python
alalek ~$ ls -al /usr/bin/python
lrwxrwxrwx 1 root root 9 Mar 13 09:52 /usr/bin/python -> ./python3
```

(Fedora 31)

You should contact with maintainers of your OS distributive instead.
Or use `virtualenv` to force python version.
