### ISSUE TITLE
Building with InferenceEngine and nGraph does not work properly

### ISSUE THREAD

**Issue by g3n35i5** [opencv/opencv#17575]
##### System information (version)
- OpenCV => 4.3.0
- OpenVino => v2020.3.0
- Operating System / Platform => Archlinux 5.7.2
- Compiler => g++ v10.1.0

##### Detailed description

Building OpenCV with Inference Engine and nGraph does not work when using the 3rd method (giving the INTEL_OPENVINO_DIR). I think this is related to the fact, that the nGraph library has been moved from openvino/deployment_tools/inference_engine/external/ngraph to openvino/include/ngraph/

Furthermore, on omitting the `DINF_ENGINE_PLATFORM` param, it is set to "ubuntu_16.04". This causes OpenCV to build without Inference engine. Current workaround: Setting the `INF_ENGINE_PLATFORM` param to "empty".

##### Steps to reproduce

Build and install OpenVino v2020.3.0 from sources:

```
cd /tmp
git clone https://github.com/openvinotoolkit/openvino.git
cd openvino
git checkout tags/2020.3.0
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/openvino-install ..
make
make install
```

Build OpenCV from sources:

```
cd /tmp
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout tags/4.3.0
git submodule update --init --recursive
mkdir build
cd build
INTEL_OPENVINO_DIR=/tmp/openvino-install cmake -DINF_ENGINE_PLATFORM= -DCMAKE_INSTALL_PREFIX=/tmp/opencv-install -DWITH_INF_ENGINE=ON -DCMAKE_BUILD_TYPE=Release ..
```

Current workaround: Setting the ngraph_DIR environment variable:

```
ngraph_DIR=/tmp/openvino-install/cmake INTEL_OPENVINO_DIR=/tmp/openvino-install cmake -DINF_ENGINE_PLATFORM= -DCMAKE_INSTALL_PREFIX=/tmp/opencv-install -DWITH_INF_ENGINE=ON -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by dkurt** [comment]
Please use `-DInference_Engine_DIR` instead of `INTEL_OPENVINO_DIR`

**Comment by g3n35i5** [comment]
I tried this, but this way nGraph is not found

**Comment by g3n35i5** [comment]
Additional info: i **dont** want to use the "setupvars.sh" script for all environment variables :roll_eyes:

**Comment by dkurt** [comment]
I think that this is IE issue - it just has no `install` step and does not include nGraph dependency in own CMake config so users have to specify both
```
export InferenceEngine_DIR=/path/to/openvino/build
export ngraph_DIR=/path/to/openvino/build/ngraph
```

**Comment by g3n35i5** [comment]
Damn, I thought so. Thanks for the information anyway!
