### ISSUE TITLE
DNN problem with variable batch size

### ISSUE THREAD

**Issue by batchsize** [opencv/opencv#17588]
##### System information (version)

- OpenCV => : 4.3
- Operating System / Platform => :Ubuntu 18.04.4 LTS  
- Compiler => : gcc 7.5.0

##### Detailed description

I do batch inference use dnn with caffe model.
It works well wtih the fixed batch size.
The problem occurs, when  the batch size changes.

here is my code:
```
cv::dnn::Net Net_;
cv::cuda::setDevice(gpu_id);
Net_.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
Net_.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
Net_ = cv::dnn::readNet("./test.caffemodel", "./test.prototxt", "Caffe");
cv::Mat inputBlob =
            cv::dnn::blobFromImages(batch_imgs, IMG_INV_STDDEV, cv::Size(320, 320),cv::Scalar(127.5, 127.5, 127.5), true, false, CV_32F);
Net_.setInput(inputBlob, "data");
const std::vector<cv::String> outBlobNames{"output"};
std::vector<cv::Mat> outputBlobs;
Net_.forward(outputBlobs, outBlobNames);
```

**Comment by YashasSamaga** [comment]
@batchsize what is the problem? can you please share the model?

**Comment by batchsize** [comment]
@YashasSamaga 
Sorry i can't  share the model. I use  ResNet to extract features from input images. The input is batch_size * 3 * 320 * 320, and the output feature is 512-dimension. 
For example, if I always set the input as 16 * 3 * 320 * 320 or 32 * 3 * 320 * 320 or other batches, it works well.  But when I load the model one time, and change the batch size,  it outputs wrong. 
If I initialize net for each batch size , the result is expected:
This problem also occurs in mobilenet. So is there a bug for  dynamic input Batch Size?

It's similar to this problem in some ways. What is different from this question is my network only have one input. 
[#15054](https://github.com/opencv/opencv/issues/15054)

**Comment by YashasSamaga** [comment]
@batchsize does this happen with `DNN_BACKEND_OPENCV`?

Remove these two lines (defaults to `DNN_BACKEND_OPENCV`) and check if you still have the problem:

```
Net_.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
Net_.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
```

**Comment by batchsize** [comment]
@YashasSamaga   
Yes, the same problem. I have tried with cpu.

**Comment by dkurt** [comment]
> The problem occurs, when the batch size changes.

What kind of problem? Add error message at least.

**Comment by batchsize** [comment]
@dkurt 
When I change the input batch of the network, net.forward() works well, but the output features are incorrect.

**Comment by dkurt** [comment]
@batchsize, so how we can reproduce this problem without absolutely any information about the model? In general, OpenCV supports batching so this might be a bug. Check master branch and if it does not work - try to find a layer which works incorrectly (i.e. for two similar examples in batch returns different outputs).

**Comment by batchsize** [comment]
@dkurt 
ok, I will provide a demo code with model later.

**Comment by batchsize** [comment]
@YashasSamaga  @dkurt 
Here is the demo. I set the input batch with same image. But the output is different when batch_size changed.
If i set a fixed batch size, it works well.
Here is my model:
https://drive.google.com/drive/folders/1waPVDPessrRyyV_V6PtmYNLSuMJg_cgK?usp=sharing
```
cv::dnn::Net net;
//    cv::cuda::setDevice(0);
//    net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
//    net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
    net = cv::dnn::readNet("../model/resnet_demo.caffemodel", "../model/resnet_demo.prototxt", "Caffe");
    
    vector<cv::Mat> batch_imgs;
    int batch_size = 5;
    cv::Mat img(112, 112, CV_8UC3, Scalar(0, 0, 0));
    for (int j = 0; j < 3; j++) {
        batch_imgs.clear();
        for (int i = 0; i < batch_size; i++) {
                batch_imgs.push_back(img);
        }
        cout << "current batch size:  " <<batch_imgs.size() << endl;
        cv::Mat inputBlob =
            cv::dnn::blobFromImages(batch_imgs, 0.0078125, cv::Size(112, 112),cv::Scalar(127.5, 127.5, 127.5), true, false, CV_32F);
            
        net.setInput(inputBlob, "data");

        const std::vector<cv::String> outBlobNames{"fc1"};
        std::vector<cv::Mat> outputBlobs;
        net.forward(outputBlobs, outBlobNames);
        
        for(int _k = 0; _k < batch_size; _k ++){
            float* features_data = (float*)outputBlobs[0].data +  _k * 512;
            std::vector<float> features = std::vector<float>(features_data, features_data + 512);
            for(int i = 0; i < 10; i++) {
                cout << features[i] << " ";
            }
            cout << endl;
        }
        cout << endl;
        batch_size--;
    }

```

output:
```
current batch size:  5
0.380971 -1.30188 -0.119891 0.187065 -0.0765666 -0.0619335 0.0924264 0.205155 0.0165541 0.406887 
0.380971 -1.30188 -0.119891 0.187065 -0.0765666 -0.0619335 0.0924264 0.205155 0.0165541 0.406887 
0.380971 -1.30188 -0.119891 0.187065 -0.0765666 -0.0619335 0.0924264 0.205155 0.0165541 0.406887 
0.380971 -1.30188 -0.119891 0.187065 -0.0765666 -0.0619335 0.0924264 0.205155 0.0165541 0.406887 
0.380971 -1.30188 -0.119891 0.187065 -0.0765666 -0.0619335 0.0924264 0.205155 0.0165541 0.406887 

current batch size:  4
-0.0714173 -1.0799 1.13043 -0.217868 -0.572338 2.08463 0.0549066 -0.473017 0.503461 -0.0207269
-0.0714173 -1.0799 1.13043 -0.217868 -0.572338 2.08463 0.0549066 -0.473017 0.503461 -0.0207269 
-0.0714173 -1.0799 1.13043 -0.217868 -0.572338 2.08463 0.0549066 -0.473017 0.503461 -0.0207269 
-0.0714173 -1.0799 1.13043 -0.217868 -0.572338 2.08463 0.0549066 -0.473017 0.503461 -0.0207269

current batch size:  3
-0.375902 -1.60304 1.32272 -0.708618 -0.541444 2.25897 0.427785 -0.395158 0.404456 -0.422535 
-0.375902 -1.60304 1.32272 -0.708618 -0.541444 2.25897 0.427785 -0.395158 0.404456 -0.422535 
-0.375902 -1.60304 1.32272 -0.708618 -0.541444 2.25897 0.427785 -0.395158 0.404456 -0.422535 
```

**Comment by sl-sergei** [comment]
Does not reproduce on master branch with CPU/CUDA/MYRIAD

**Comment by batchsize** [comment]
@sl-sergei 
Which OpenCV version are you using?

**Comment by sl-sergei** [comment]
> @sl-sergei
> Which OpenCV version are you using?

I used current master and 3.4 branches. If you still face the issue, please, provide your system information and target/backend settings in OpenCV

**Comment by batchsize** [comment]
@sl-sergei 
The  system information is on the top of this issue and you can rum my code above. This  bug is on the version of 4.3.

**Comment by alalek** [comment]
> This bug is on the version of 4.3

Old releases are outdated by definition.
You should upgrade or wait for the next release (or build from sources).

Issues should be reported against the latest releases and/or the latest state of supported branches (master/3.4)
