### ISSUE TITLE
cv2.error: OpenCV(4.2.0)

### ISSUE THREAD

**Issue by panban-ux** [opencv/opencv#17603]
##### System information (version)
Pycharm

Im getting an error trying to the detector.py. Already compiled opencv4.2 and Darknet but im getting the followin error which seems to be the wrong path pycharm gets to opencv.

File "C:/Users/Panagiotis/PycharmProjects/ANPR-master/Licence_plate_detection/detecor.py", line 38, in <module>
    net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: lapi.weights in function 'cv::dnn::dnn4_v20191202::readNetFromDarknet'

My config is the following

modelConfiguration = 'C:\\Users\\Panagiotis\\vcpkg-master\\installed\\x64-windows\\tools\\darknet\\cfg'
modelWeights = 'C:\\Users\\Panagiotis\\vcpkg-master\\installed\\x64-windows\\tools\\darknet'
modelConfiguration = "darknet-yolov3.cfg";
modelWeights = "lapi.weights";
net = cv.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

How do i change the said path of this line if thats the problem?
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:214: error:

Elsewhere in a closed topic i saw a .config file topic of the matter

**Comment by dkurt** [comment]
Use extra backslashes to disable escape characters: C:\\Users\\...
