### ISSUE TITLE
Why const qualifier cannot modify the cv::Mat object that later on is used to be cloned?

### ISSUE THREAD

**Issue by niebayes** [opencv/opencv#17614]
##### System information (version)
- OpenCV => 4.3
- Operating System / Platform => macOS
- Compiler => Clang++

##### Detailed description
`const cv::Mat original;` 
`cv::Mat calibrated = original.clone()` 
Why this operation is banned. 
Does the reference counter have something to do with this operator?

**Comment by Jackey-Huo** [comment]
So what the answer is? @niebayes
