### ISSUE TITLE
compile opencv

### ISSUE THREAD

**Issue by ohmygodoh** [opencv/opencv#17625]
System information (version)
OpenCV => 3.4.10 
Operating System / Platform => ubuntu 14.04
Compiler => cmake
Detailed description
When I compile opencv lateast version 3.4.10, I run the make command with the following error.
[ 46%] Linking CXX executable ../../bin/opencv_test_imgproc
CMakeFiles/opencv_perf_imgproc.dir/perf/perf_cvt_color.cpp.o:file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_test_imgproc] error 1
make[1]: *** [modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/all] error 2
make: *** [all] error 2

Can anyone solve it, thank you!!

**Comment by dkurt** [comment]
Please follow issue template and make it reproducible. We cannot help to solve it unless we know compilation options.
