### ISSUE TITLE
Mask-rcnn (resnet-50) model works with tensorflow api but doesn't work with opencv dnn module

### ISSUE THREAD

**Issue by ahasan016** [opencv/opencv#17623]
I have trained a custom model for maskrcnn using mask_rcnn_resnet50_atrous_coco from [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). The model works fine with [tensorflow eval_code](https://drive.google.com/file/d/1XKBBoUeyvRsMVFF7jcD6pkGkWGPeVnDW/view?usp=sharing). I can visualize masks, boxes everything. such as: 
![out_tensor_api](https://user-images.githubusercontent.com/11074869/85322498-ba479880-b4c6-11ea-86c3-c7ebba2071bc.png) 
but I am facing a problem while trying the inference with OpenCV-dnn.  There's no error but it doesn't oputput anything but input image. such as: 
![Output](https://user-images.githubusercontent.com/11074869/85322713-11e60400-b4c7-11ea-9a36-1169e514c96a.jpg). My frozen graph is [frozen_graph.pb](https://drive.google.com/file/d/1gol8pMXKnnHxrKge5JAFdMmmbvKSzGb9/view?usp=sharing) and i am using [tf_text_graph_mask_rcnn.py](https://drive.google.com/file/d/1yBgoHSDAo6zezuRqyoEZCcHBs6_Kl9yP/view?usp=sharing) to generate [.pbtxt](https://drive.google.com/file/d/1y2ypQJOG2ldHsJcmqNnEDuxAshwsPXIa/view?usp=sharing) file and using [pipeline_mask ](https://drive.google.com/file/d/1xGzjVVLaHMTfsFyHQe1W2UJGQDus72rw/view?usp=sharing) as **.config** . For inference in opencv-dnn i am using [this](https://drive.google.com/file/d/1F7vfwjNBvp4MS02FPpzVHxlco62lQCY4/view?usp=sharing) script with [class_name.txt](https://drive.google.com/file/d/1wm6WFwZ83HX3zTRU8UnnUtW9TR6l7hwf/view?usp=sharing) and [color.txt](https://drive.google.com/file/d/1gS5FTcPERqzKkIwMb1OMmS8Ngd8i9G2r/view?usp=sharing) as  class names and instance inference colors respectively.  Can anyone please help me to find where i am wrong? or is it a problem for opencv-dnn module? I am using the master version of opencv.

**Comment by ahasan016** [comment]
@dkurt any comment? please have a look at it.

**Comment by dkurt** [comment]
Please take a look at the notes from https://github.com/opencv/opencv/pull/13766

**Comment by ahasan016** [comment]
@dkurt  It worked. Thanks a lot.
