### ISSUE TITLE
Python Bindings importing error

### ISSUE THREAD

**Issue by zerovirus123** [opencv/opencv#17632]
##### Detailed description

I had built OpenCV from source with CUDA acceleration, and copied the .pyd into my Anaconda environment. However, I could not do any submodule imports, and I cannot place ```import cv2``` on anywhere other than the first line.

##### Steps to reproduce
 ```
import cv2 #this is the only way to import without throwing any error.

import cv2.dnn # does not work

import library1
import library2
...
import cv2 # doesn't work either

 ```

Failing to do so would produce the following error.

```
ImportError: DLL load failed: The specified procedure could not be found.
```

Is this a build issue? A dependency issue? Or an environment issue? Is this problem serious enough to affect the library's runtime performance?

**Comment by alalek** [comment]
> The specified procedure could not be found.

This is usually a dependency issue. Just .pyd is not enough (all .DLLs are required).
On Windows add entries to .dll into PATH environment variable.

---

> copied the .pyd

It is better to play with `PYTHONPATH` instead of copying.

---

Before importing check actual values:
```.py
print(os.environ['PATH'])
print(sys.path)
```

---

Python 3.8 breaks "PATH" on Windows, see `os.add_dll_directory`.

---

Try "python_loader" + setup_vars from build directory:
```
> .\setup_vars.cmd python -c 'import cv2; print(cv2.__file__)'
```

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by zerovirus123** [comment]
Would a self-contained .pyd file still need .dll dependencies?

**Comment by LaurentBerger** [comment]
I changed Python 3.6 to python 3.8. Now I cannot load my own build of cv2.  After 4 months I found using  alek [comment](https://github.com/opencv/opencv/issues/17632#issuecomment-648098711) : 

```
>>>import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing cv2: Le module spécifié est introuvable.
>>>os.add_dll_directory(r'G:\Lib\install\opencv\x64\vc15\bin')
<AddedDllDirectory('G:\\Lib\\install\\opencv\\x64\\vc15\\bin')>
>>>os.add_dll_directory(r'G:\Lib\install\vtk\bin')
<AddedDllDirectory('G:\\Lib\\install\\vtk\\bin')>
>>> import cv2
>>> print(cv2.getBuildInformation())

General configuration for OpenCV 4.5.1-pre =====================================
  Version control:               4.4.0-782-g50baf76cc2

```

**Comment by AnthonyTheKoala** [comment]
Dear Laurent:
Summary: did not work still got the import DLL
Steps:
Opened C:\Python38\opencv\build\bin\Release and ran a terminal window to test the exe files as a result of the compilation.
Successfully ran:
opencv_version.exe, result 4.5.2-dev
opencv_testflann, result:
CTEST_FULL_OUTPUT
OpenCV version: 4.5.2-dev
OpenCV VCS version: 4.5.2-51-gfcaeeac931
Build type: Debug Release
WARNING: build value differs from runtime: Release
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe  (ver 19.28.29337.0)
Parallel framework: ms-concurrency (nthreads=8)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16? *AVX *AVX2? *AVX512-SKX?
Intel(R) IPP version: ippIP SSE4.2 (y8) 2020.0.0 Gold (-) Oct 21 2019
Intel(R) IPP features code: 0x80
OpenCL Platforms: 
    NVIDIA CUDA
        dGPU: GeForce GT 540M (OpenCL 1.1 CUDA)
Current OpenCL device: 
```
    Type = dGPU
    Name = GeForce GT 540M
    Version = OpenCL 1.1 CUDA
    Driver version = 354.35
    Address bits = 64
    Compute units = 2
    Max work group size = 1024
    Local memory size = 48 KB
    Max memory allocation size = 256 MB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_khr_byte_addressable_store
        cl_khr_icd
        cl_khr_gl_sharing
        cl_nv_compiler_options
        cl_nv_device_attribute_query
        cl_nv_pragma_unroll
        cl_nv_d3d9_sharing
        cl_nv_d3d10_sharing
        cl_khr_d3d10_sharing
        cl_nv_d3d11_sharing
        cl_nv_copy_opts
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_fp64
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from Flann_LshTable
[ RUN      ] Flann_LshTable.badarg
[       OK ] Flann_LshTable.badarg (0 ms)
[ RUN      ] Flann_LshTable.bad_any_cast
[       OK ] Flann_LshTable.bad_any_cast (0 ms)
[----------] 2 tests from Flann_LshTable (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 2 tests.

```
Therefore the exe files in C:\Python38\opencv\build\bin\Release  worked. 
So now, I opened a terminal window with 'new' path within the terminal window including C:\Python38\opencv\build\bin\Release  and other python38 paths
This overrides the path set by computer at bootup

![image](https://user-images.githubusercontent.com/26536316/116051519-08679280-a6bc-11eb-9f9d-2dd38487d2b5.png)

Ran the python program from within the same terminal window
![image](https://user-images.githubusercontent.com/26536316/116052064-9e9bb880-a6bc-11eb-9d2a-34d575b65fff.png)

Result:
Does not work

Thank you, merci
Anthony of Sydney

**Comment by LaurentBerger** [comment]
python 3.8 does not use system path variable

**Comment by AnthonyTheKoala** [comment]
Dear Laurent,
I used the wrong page.
I will ask the question at the original page that i raised the question.

Thank you,
Anthony of Sydney

**Comment by zhuxu222** [comment]
> python 3.8 does not use system path variable

Thanks!!!!
Solved when i add system path to environment path by changing config.py

import os
BINARIES_PATHS = [
    "E:/common/solution/lib/opencv/4.5.5/build/bin/Release/",
    "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/"
] + BINARIES_PATHS+os.getenv("PATH").split(";")

**Comment by deus-est-machina** [comment]
@zhuxu222 three days man. three days T^T

**Comment by isrishtisingh** [comment]
> > python 3.8 does not use system path variable
> 
> Thanks!!!! Solved when i add system path to environment path by changing config.py
> 
> import os BINARIES_PATHS = [ "E:/common/solution/lib/opencv/4.5.5/build/bin/Release/", "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/" ] + BINARIES_PATHS+os.getenv("PATH").split(";")

Your solution worked in my case, thanks a lot, it took a lot of time debugging this issue.
