### ISSUE TITLE
SSD MobileNet: error: (-215:Assertion failed) inputs.size() >= 2 in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'

### ISSUE THREAD

**Issue by kaanaykutkabakci** [opencv/opencv#17637]
Hello, i have trained my dataset by using ssd_mobilenet_v2_coco from TF Detection Model Zoo.
After train, i export my inference graph. It works with Tensorflow. But in OpenCV, i am getting following error. The link that includes my files is https://drive.google.com/drive/folders/1jQBNP2OzfD1J8Mfp4PDTqetzUGvLTtjz?usp=sharing

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\eltwise_layer.cpp:170: error: (-215:Assertion failed) inputs.size() >= 2 in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'

**Comment by dkurt** [comment]
Please use a script from the same version as library: https://github.com/opencv/opencv/blob/4.2.0/samples/dnn/tf_text_graph_ssd.py

**Comment by kaanaykutkabakci** [comment]
Thanks for your interest @dkurt. I use it, but same error still occurs.

**Comment by dkurt** [comment]
@kaanaykutkabakci, please try newer version of OpenCV or find similar issues.

**Comment by kaanaykutkabakci** [comment]
@dkurt hello again. I have build new version of OpenCV(4.3.0). 
I have used https://github.com/opencv/opencv/blob/4.2.0/samples/dnn/tf_text_graph_ssd.py file to generate .pbtxt file. And, I couldn't find any similar issue pointing to "inputs.size ()> = 2" error. I have tried "ssd_mobilenet_v1_fpn_coco" and "ssd_resnet_50_fpn_coco" models. These models give me best accuracy rather than others. But, i could not run both of them with OpenCV. 

Could you please help me in order to overcome this problem?
