### ISSUE TITLE
Problem with /usr/share/licenses/opencv3/ files

### ISSUE THREAD

**Issue by guteksan** [opencv/opencv#17630]
##### System information (version)

- OpenCV => 3.4.10
- Operating System / Platform => ubuntu/xenial
- Compiler => gcc 5.4.0

##### Detailed description

I am preparing a debian package for OpenCV 3.4.10. I already have a working packaging process for 3.4.1 and I decided to use its /debian folder, and modify it if necessary. The problem is, that in version 3.4.10 there are new files installed by Cmake to location /debian/tmp/usr/share/licenses/opencv3 and they are not correctly handled by dh_install:

    dh_install -O--buildsystem=cmake --fail-missing
    dh_install: usr/share/licenses/opencv3/protobuf-LICENSE exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/protobuf-README.md exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/SoftFloat-COPYING.txt exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/ittnotify-LICENSE.BSD exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/opencl-headers-LICENSE.txt exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/quirc-LICENSE exists in debian/tmp but is not installed to anywhere
    dh_install: usr/share/licenses/opencv3/ittnotify-LICENSE.GPL exists in debian/tmp but is not installed to anywhere
    dh_install: missing files, aborting

First, I thought that maybe I should override `dh_install` in `debian/rules`, but now I think that this should be properly handled by Opencv cmake, because I should not need to handle differently license files than any other files that are to be installed. Here is part of `debian/rules` that currently overrides `dh_install`:

    override_dh_install:
        # change install path of java library
        sed -i -e "s@share\/OpenCV\/java\/@lib\/jni\/@g" \
		debian/tmp/usr/share/OpenCV/OpenCVModules-release.cmake

        # put the static libs together with the rest of the stuff
        for f in $$(ls obj-*/lib/libopencv_*.a); do \
		cp --verbose --preserve=mode $$f debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/; done

        rm -rf debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/*_pch_dephelp.a

        dh_install -O--buildsystem=cmake --fail-missing

**Comment by mshabunin** [comment]
You can change installation layout using cmake variables:
https://github.com/opencv/opencv/blob/73f7d091f86e186246d980a535a9fac79b4d9b89/cmake/OpenCVInstallLayout.cmake#L59-L79

Also you can install only selected components, instead of `make install` use the following command:
```
cmake -P <build-dir>/cmake_istall.cmake -DCMAKE_INSTALL_COMPONENT=<component>
```
Where `<component>` is one of `licenses`, `dev`, `lib`, ... (see cmake_install.cmake file for all available components and options)
