### ISSUE TITLE
Can't install OpenCV on Ubuntu

### ISSUE THREAD

**Issue by jonasbradstreet** [opencv/opencv#17659]
Copying and pasting the istructions on opencv.org
sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

I get the following

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
E: Unable to locate package libjasper-dev

**Comment by zhaoworking** [comment]
bro, have you solved the problem, I have struck with this problem for a long time .
