### ISSUE TITLE
net.forward() error: (-215:Assertion failed) inp.total() in function 'allocateLayers'

### ISSUE THREAD

**Issue by goncz** [opencv/opencv#17653]
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform =>  Ubuntu 16.04

##### Detailed description
I try to run an object detection counting application (see counting_algorithm code below). I've converted a tensorflow model to Caffe model using [MMdnn converter](https://github.com/microsoft/MMdnn/tree/master/mmdnn/conversion/tensorflow). When i try to run the `counting_algorithm` script, i get the following error:

```
[INFO] loading model...
[INFO] opening video file...
Traceback (most recent call last):
  File "people_counter.py", line 132, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/dnn.cpp:2709: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'
```

Any suggestions on how to fix this issue?

##### Steps to reproduce
Python script i try to run:
[counting_algorithm.txt](https://github.com/opencv/opencv/files/4824871/code.txt)

Prototxt of the Caffe model used:
[prototxt.txt](https://github.com/opencv/opencv/files/4824919/prototxt.txt)

**Comment by chad-green** [comment]
I'm getting the same error with a custom-trained tensorflow object detector that I converted to an IR. I've been able to run the IR through the openvino's inference engine with the CPU and getting good detections, but when trying to use the cv2.dnn module, it fails with the following error:
src/dnn.cpp:2892: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'

Here is a test script to verify that the network is good by running it through both IE and CV2.DNN:

```
import numpy as np
import cv2
from openvino.inference_engine import IECore
ie = IECore()
model_bin = "frozen_inference_graph.bin"
model_xml = "frozen_inference_graph.xml"
net = cv2.dnn.readNet(model=model_bin, config=model_xml)
ienet = ie.read_network(model_xml, model_bin)
img_info_input_blob = None
feed_dict = {}
for blob_name in ienet.inputs:
	if len(ienet.inputs[blob_name].shape) == 4:
		input_blob = blob_name
	elif len(ienet.inputs[blob_name].shape) == 2:
		img_info_input_blob = blob_name
	else:
		raise RuntimeError("Unsupported {}D input layer '{}'. Only 2D and 4D input layers are supported"
							.format(len(ienet.inputs[blob_name].shape), blob_name))
assert len(ienet.outputs) == 1, "Network supports only single output topologies"
out_blob = next(iter(ienet.outputs))
exec_net = ie.load_network(network=ienet, num_requests=1, device_name='CPU')
n, c, h, w = ienet.inputs[input_blob].shape
if img_info_input_blob:
	feed_dict[img_info_input_blob] = [h, w, 1]
print("[INFO] setting preferable backend and target...")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
# net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
# net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
# determine only the *output* layer names that we need
ln = net.getLayerNames()
ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
print("CV2 output layer name: {}, IE output layer name: {}".format(ln,out_blob))

# initialize the video stream and pointer to output video file, then
vs = cv2.VideoCapture(0)

# read the next frame from the file
(grabbed, frame) = vs.read()
blob = cv2.dnn.blobFromImage(image=frame, scalefactor=1, size=(480, 480),swapRB=False, crop=False)
print('blob shape: ',blob.shape) 
net.setInput(blob=blob, name="image_tensor")
layerOutputs = exec_net.infer(inputs=feed_dict)
print("IE output results: {}".format(layerOutputs))
layerOutputs = net.forward(outBlobNames="detection_output")
print("IE output results: {}".format(layerOutputs))
```
The above code gives the following output:
python temp_inference_script.py 
[E:] [BSL] found 0 ioexpander device
[INFO] setting preferable backend and target...
CV2 output layer name: ['detection_output'], IE output layer name: detection_output
blob shape:  (1, 3, 480, 480)
IE output results: {'detection_output': array([[[[0., 1., 1., ..., 0., 1., 1.],
         [0., 1., 1., ..., 0., 1., 1.],
         [0., 1., 1., ..., 0., 1., 1.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)}
Traceback (most recent call last):
  File "temp_inference_script.py", line 63, in <module>
    layerOutputs = net.forward(outBlobNames="detection_output")
cv2.error: OpenCV(4.3.0) /Downloads/opencv4-3-0/opencv/modules/dnn/src/dnn.cpp:2892: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'

What am I doing wrong on the cv2.dnn side? Both frameworks seem to load the network just fine and don't call out any unsupported layers. Both show that they have found the output layer ("detection_output"), but only IE can run the image through the network. I looked at the c++ code in dnn.cpp:2892 and it's failing at the CV2ASSERT in this allocate layers function. Kind of seems like it's not finding the output layer, but I've tried telling net.forward() what to look for in every way I could image. Any help appreciated.

```
void allocateLayers(const std::vector<LayerPin>& blobsToKeep_)
    {
        CV_TRACE_FUNCTION();
        //std::cout << "blobsToKeep_ = " << blobsToKeep_ "\n";
        MapIdToLayerData::iterator it;
        for (it = layers.begin(); it != layers.end(); it++)
            it->second.flag = 0;

        CV_Assert(!layers[0].outputBlobs.empty());
        ShapesVec inputShapes;
        for(int i = 0; i < layers[0].outputBlobs.size(); i++)
        {
            Mat& inp = layers[0].outputBlobs[i];        
            CV_Assert(inp.total());
            if (preferableBackend == DNN_BACKEND_OPENCV &&
                preferableTarget == DNN_TARGET_OPENCL_FP16)
            {
                layers[0].outputBlobs[i].create(inp.dims, inp.size, CV_16S);
            }
            inputShapes.push_back(shape(inp));
        }
```
Using OpenCV 4.3.0 and OpenVino 2020.3 running on Ubuntu 18

**Comment by chad-green** [comment]
@dkurt Any thoughts on the above? I used the following script to convert the [rfcn_resnet101_coco](http://download.tensorflow.org/models/object_detection/rfcn_resnet101_coco_2018_01_28.tar.gz) model from tensorflow model zoo:
```
INSTALL_DIR="/opt/intel/openvino_2020.3.194"

$INSTALL_DIR/deployment_tools/model_optimizer/mo_tf.py \
    --input_model=/home/dockerOpenVino/6-6-2020/frozen_inference_graph.pb \
    --transformations_config $INSTALL_DIR/deployment_tools/model_optimizer/extensions/front/tf/rfcn_support_api_v1.14.json \
    --tensorflow_object_detection_api_pipeline_config /home/dockerOpenVino/6-6-2020/rfcn.config \
    --reverse_input_channels \
    --log_level DEBUG
```
I've zipped up the .xml file generated by the script and attached for your reference.
[frozen_inference_graph.zip](https://github.com/opencv/opencv/files/4868357/frozen_inference_graph.zip)

**Comment by chad-green** [comment]
I spent a little more time on this trying to verify if it is possible to run an IR with DNN_BACKEND_CUDA using cv2.dnn.readNet(). I converted a standard tensorflow model zoo ssd_inception_v2_coco_2018_01_28 using the [example](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html):
```<INSTALL_DIR>/deployment_tools/model_optimizer/mo_tf.py --input_model=/tmp/ssd_inception_v2_coco_2018_01_28/frozen_inference_graph.pb --transformations_config <INSTALL_DIR>/deployment_tools/model_optimizer/extensions/front/tf/ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config /tmp/ssd_inception_v2_coco_2018_01_28/pipeline.config --reverse_input_channels```
Using my test script above (on June 30th), the output for the inference engine and cv2.dnn.forward() were identical (at least on CPU they were. with DNN backend, there were some errors of unsupported layers, but I'll come back to that, I just want to verify it can do it on CPU first).
So then I went to convert another model from the model zoo, the faster_rcnn_resnet50_coco_2018_01_28. This one we know has all the layers supported, at least when importing using cv2.dnn.readNetFromTensorflow as in the example [here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API). I successfully converted the .pb file to an IR using the following command:
```python deployment_tools/model_optimizer/mo_tf.py --input_model=/tmp/faster_rcnn_resnet50_coco_2018_01_28/frozen_inference_graph.pb --transformations_config deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config /tmp/faster_rcnn_resnet50_coco_2018_01_28/pipeline.config --reverse_input_channels --output_dir /tmp/faster_rcnn_resnet50_coco_2018_01_28/```
Interestingly, when running my test script, it gives the same error as my RFCN network: 
```
Traceback (most recent call last):
  File "temp_inference_script.py", line 66, in <module>
    layerOutputs = net.forward(outBlobNames=ln)#outBlobNames=['detection_out_final'])
cv2.error: OpenCV(4.3.0) /home/chad/Downloads/opencv4-3-0/opencv/modules/dnn/src/dnn.cpp:2892: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'
```
Just like before, it runs fine using the inference engine, but the dnn module is having some trouble allocating some unspecified layers. I tried comparing the .xml file of the ssd_inception_v2 (works) to the faster_rcnn_resnet50 (doesn't work), but didn't find anything useful. I also verified that cv2.dnn.readNetFromTensorflow works just fine even with DNN_BACKEND_CUDA, which is great, but I really want to use an optimized IR, rather than the frozen inference graph from tensorflow. Can anyone help point us in the right direction to solve this?

I'm attaching the zipped .xml of the converted faster_rcnn model. Happy to supply any other information to repeat the error.
[frozen_inference_graph.zip](https://github.com/opencv/opencv/files/4883146/frozen_inference_graph.zip)

**Comment by rogday** [comment]
Could you provide both the model and config(xml + bin and prototxt + caffemodel)?

**Comment by chad-green** [comment]
We never got this to work, but moved on to other solutions. I appreciate you checking in, though.

**Comment by rogday** [comment]
Feel free to reopen the issue if you decide to help us improve OpenCV.
