### ISSUE TITLE
Imagegrabber in cv::VideoCapture

### ISSUE THREAD

**Issue by iaminvincible25** [opencv/opencv#17655]
##### System information (version)
- OpenCV => 4.3.0
- Operating System / Platform => QT5
- Compiler => :grey_question:

##### Detailed description

In the EMGU plugin in visual studio, we have an event in the VideoCapture class, called Imagegrabber, which fires when a new frame is grabbed by the camera. I'm looking for an equivalent in the OpenCV to use in the QT platform.

**Comment by mshabunin** [comment]
OpenCV have no interface-level integration with Qt, so you have to implement an object wrapping VideoCapture which will send signals/events by yourself.
