### ISSUE TITLE
Feature-request: YOLOv4-tiny (detector) 

### ISSUE THREAD

**Issue by AlexeyAB** [opencv/opencv#17666]
Feature-request: YOLOv4-**tiny** (detector) 

* **source code**: https://github.com/AlexeyAB/darknet
* **cfg**: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-tiny.cfg
* **weights**: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights
* **discussion**: https://github.com/AlexeyAB/darknet/issues/6067

Many other features from Darknet were added previously.
There is required only 1 feature:

1. Add `groups=` and `group_id=` to the `[route]` layer.
```ini
[route]
layers=-1
groups=2
group_id=1
```

So if input is `WxHxC`, it divides input into 2 groups `WxHx(C/2)` (there are 2 groups: 0 and 1), and loads the 2nd group_1 `WxHx(C/2)`.

If there are many layers specified in `layers=` parameter, then this will be done for each of the input layers specified in `layer=`, then results will be concatenated across channels.

![cmp](https://user-images.githubusercontent.com/4096485/85734112-6e366700-b705-11ea-95d1-fcba0de76d72.png)

**Comment by monoloxo** [comment]
For some reasons we must use yolov3, so can yolov3 be used to train a network similar to yolov4-tiny.cfg?
