### ISSUE TITLE
Regarding Contribution to OpenCV

### ISSUE THREAD

**Issue by cskarthik7** [opencv/opencv#17669]
I am new to OpenCV and want to contribute to OpenCV because I have been doing computer vision for quite a long time and would like to know if I should start with fixing bugs or contribute to new codes! 

I want to make an impact in the world of Computer Vision and contributing to OpenCV will definitely boost up my knowledge.
Please help!

**Comment by saskatchewancatch** [comment]
Anything that has the good first issue label is a good place to start. Btw please read the Wiki, most questions you have are probably answered there.

https://github.com/opencv/opencv/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by cskarthik7** [comment]
> Anything that has the good first issue label is a good place to start. Btw please read the Wiki, most questions you have are probably answered there.
> 
> https://github.com/opencv/opencv/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

I have read the wiki but it has written about how to make pull request to the opencv repo. But I can make a pull request if I have some knowledge of the codebase! And I guess I am just baffled up with the cpp and hpp files! So that's why I am baffled up!

**Comment by saskatchewancatch** [comment]
> > Anything that has the good first issue label is a good place to start. Btw please read the Wiki, most questions you have are probably answered there.
> > https://github.com/opencv/opencv/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
> 
> I have read the wiki but it has written about how to make pull request to the opencv repo. But I can make a pull request if I have some knowledge of the codebase! And I guess I am just baffled up with the cpp and hpp files! So that's why I am baffled up!

[Document issues](https://github.com/opencv/opencv/labels/category%3A%20documentation) might be a good place to start so you get familiar with the CMake system and the organization of source tree. Most doc-related issues will have you edit the header files.

**Comment by cskarthik7** [comment]
I have got some idea of CMake as yesterday I was going through that only. Currently I am trying to going through features2d. The thing I am getting stuck is the CMakeLists.txt of every part of modules. Its quite confusing and the linking different hpp files.

**Comment by saskatchewancatch** [comment]
> I have got some idea of CMake as yesterday I was going through that only. Currently I am trying to going through features2d. The thing I am getting stuck is the CMakeLists.txt of every part of modules. Its quite confusing and the linking different hpp files. 


I don't recommend spending too much time with CMake as a beginner. CMake's job is just to manage the build process for your platform.

To meet the goals you mentioned in the OP and to get the best value for time, I recommend **1**) making sure you can build on your platform, **2**) get setup to be able to debug source in your IDE and run tests, **3**) find an issue/verify existing OpenCV algos/enrich unit tests/etc..., **4**) and submit a PR. :)

**Comment by cskarthik7** [comment]
Sure! Thanks a lot!
