### ISSUE TITLE
DNN with CUDA not working (no error message)

### ISSUE THREAD

**Issue by who1129** [opencv/opencv#17661]
- OpenCV => 4.4
- Operating System / Platform => ubuntu

It was too slow to compute DNN with cpu. So I built and checked all of these cmake options to use the GPU.
```
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

```
In the above command, there is no error with CUDA , **but when the code is actually executed, the GPU is not used.**

I am using docker and is this affecting?

```
proto_file = "../Model/Openpose/pose_deploy.prototxt"
weights_file = "../Model/Openpose/pose_iter_584000.caffemodel"


net = cv2.dnn.readNetFromCaffe(proto_file, weights_file)

net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
```
-------CMAKE-----
cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D WITH_CUDA=ON \
 -D CMAKE_INSTALL_PREFIX=/usr/local .. \
 -D OPENCV_EXTRA_MODULES_PATH=/home/Temp/opencv/opencv_contrib/modules \
 -D INSTALL_PYTHON_EXAMPLES=OFF \
 -D INSTALL_C_EXAMPLES=OFF \
 -D BUILD_SHARED_LIBS=OFF \
 -D BUILD_DOCS=OFF \
 -D BUILD_TESTS=OFF \
 -D BUILD_EXAMPLES=OFF \
 -D BUILD_PERF_TESTS=OFF \
 -D BUILD_opencv_dnn=OFF \
 -D TINYDNN_USE_NNPACK=OFF \
 -D TINYDNN_USE_TBB=ON \
 -D TINYDNN_USE_OMP=ON \
 -D ENABLE_FAST_MATH=ON \
 -D WITH_OPENMP=ON \
 -D WITH_TBB=ON \
 -D WITH_JPEG=OFF \
 -D WITH_FFMPEG=ON \
 -D WITH_IPP=OFF \
 -D MKL_WITH_TBB=ON \
 -D MKL_WITH_OPENMP=ON \
 -D BUILD_opencv_python2=OFF \

-------CMAKE-----

**Comment by YashasSamaga** [comment]
I don't see `OPENCV_DNN_CUDA` in your CMake options. Please add `-DWITH_CUDNN` and `-DOPENCV_DNN_CUDA` to CMake arguments. Verify that CMake has detected cuDNN by looking at the output.

**Comment by who1129** [comment]
cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D WITH_CUDA=ON \
 -D WITH_CUDNN=ON \
 -D OPENCV_DNN_CUDA=ON \
 -D CMAKE_INSTALL_PREFIX=/usr/local .. \
 -D OPENCV_EXTRA_MODULES_PATH=/home/Temp/opencv/opencv_contrib/modules \
 -D INSTALL_PYTHON_EXAMPLES=OFF \
 -D INSTALL_C_EXAMPLES=OFF \
 -D BUILD_SHARED_LIBS=OFF \
 -D BUILD_DOCS=OFF \
 -D BUILD_TESTS=OFF \
 -D BUILD_EXAMPLES=OFF \
 -D 
 -D BUILD_PERF_TESTS=OFF \
 -D BUILD_opencv_dnn=OFF \
 -D TINYDNN_USE_NNPACK=OFF \
 -D TINYDNN_USE_TBB=ON \
 -D TINYDNN_USE_OMP=ON \
 -D ENABLE_FAST_MATH=ON \
 -D WITH_OPENMP=ON \
 -D WITH_TBB=ON \
 -D WITH_JPEG=OFF \
 -D WITH_FFMPEG=ON \
 -D WITH_IPP=OFF \
 -D MKL_WITH_TBB=ON \
 -D MKL_WITH_OPENMP=ON \
 -D BUILD_opencv_python2=OFF \

--   NVIDIA CUDA:                   YES (ver 10.1, CUFFT CUBLAS)
--     NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
--     NVIDIA PTX archs:
--
--   cuDNN:                         YES (ver 7.6.5)
--
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/Temp/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load

I deleted the build folder and used all of the following things. make clean, make, restart docker ..
It still using CPU.
Are the logs related to the cafe below related?

-- Caffe:   NO
-- Protobuf:   NO

**Comment by YashasSamaga** [comment]
Set `OPENCV_LOG_LEVEL` environment variable to `INFO` and run your program.

Run the following command in the terminal where you run your program.
```
export OPENCV_LOG_LEVEL=INFO
```

**Comment by who1129** [comment]
Then I got this message.
[ WARN:0] global /root/opencv/modules/dnn/src/dnn.cpp (1436) setUpNet DNN module was not built with CUDA backend; switching to CPU

I added some option.
cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D WITH_CUDA=ON \
 **-D CUDA_ARCH_BIN=7.5 \**
 -D WITH_CUDNN=ON \
 **-D WITH_CUBLAS=ON \**
 -D OPENCV_DNN_CUDA=ON \
 **-D BUILD_opencv_world=OFF\**
 -D CMAKE_INSTALL_PREFIX=/usr/local .. \
 -D OPENCV_EXTRA_MODULES_PATH=/home/Temp/opencv/opencv_contrib/modules \
 -D INSTALL_PYTHON_EXAMPLES=OFF \
 -D INSTALL_C_EXAMPLES=OFF \
 -D BUILD_SHARED_LIBS=OFF \
 -D BUILD_DOCS=OFF \
 -D BUILD_TESTS=OFF \
 -D BUILD_EXAMPLES=OFF \
 -D BUILD_PERF_TESTS=OFF \
 -D BUILD_opencv_dnn=OFF \
 -D TINYDNN_USE_NNPACK=OFF \
 -D TINYDNN_USE_TBB=ON \
 -D TINYDNN_USE_OMP=ON \
 -D ENABLE_FAST_MATH=ON \
 -D WITH_OPENMP=ON \
 -D WITH_TBB=ON \
 -D WITH_JPEG=OFF \
 -D WITH_FFMPEG=ON \
 -D WITH_IPP=OFF \
 -D MKL_WITH_TBB=ON \
 -D MKL_WITH_OPENMP=ON \
 -D BUILD_opencv_python2=OFF \

**Comment by YashasSamaga** [comment]
Why is `BUILD_opencv_dnn=OFF ` off?

**Comment by YashasSamaga** [comment]
@who1129 have you fixed this? It feels very suspicious that you had set `BUILD_opencv_dnn` to OFF and yet managed to do inference on CPU. Do you have multiple installations of OpenCV?

**Comment by who1129** [comment]
I use this option. And really sorry about my mistake...
I did not use the command "make install ". I use just "make -j16"....
All build is sucesss! gpu works well!


cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D WITH_CUDA=ON \
 -D CUDA_ARCH_BIN=7.5 \
 -D WITH_CUDNN=ON \
 -D WITH_CUBLAS=ON \
 -D OPENCV_DNN_CUDA=ON \
 -D BUILD_opencv_world=OFF\
 -D CMAKE_INSTALL_PREFIX=/usr/local .. \
 -D OPENCV_EXTRA_MODULES_PATH=/home/Temp/opencv/opencv_contrib/modules \
 -D INSTALL_PYTHON_EXAMPLES=OFF \
 -D INSTALL_C_EXAMPLES=OFF \
 -D BUILD_SHARED_LIBS=OFF \
 -D BUILD_DOCS=OFF \
 -D BUILD_TESTS=OFF \
 -D BUILD_EXAMPLES=OFF \
 -D BUILD_PERF_TESTS=OFF \
 -D BUILD_opencv_dnn=ON \

**Comment by YashasSamaga** [comment]
@who1129 can we close this issue?
