### ISSUE TITLE
Cannot specify link libraries for target "opencv_gapi" 

### ISSUE THREAD

**Issue by sky-fly97** [opencv/opencv#17677]
I used cmake to compile opencv-master and opencv-contrib under windows10. After selecting with-cuda and dnn-cuda and other options, this error occurred, which caused the subsequent compilation to fail.
`CMake Error at modules/gapi/CMakeLists.txt:193 (target_link_libraries):
  Cannot specify link libraries for target "opencv_gapi" which is not built
  by this project.
Call Stack (most recent call first):
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)`

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/85919601-4da21480-b89f-11ea-8b3f-ab3304eb685c.png)

**Comment by sky-fly97** [comment]
And when compiling 4.2 before, there will be a series of CUDA-ARCH-BIN values, but this time the latest master version does not appear！！！
![image](https://user-images.githubusercontent.com/55578436/85919630-a07bcc00-b89f-11ea-87fc-d9d099cd0caa.png)

**Comment by sky-fly97** [comment]
Can someone help me？ I just want to call the yolov4 model with the dnn module, but only the latest master version can achieve this function.

**Comment by alalek** [comment]
[Confirmed](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/11222).

Broken by #17020

@sky-fly97 Try commit from June 26 ( https://github.com/opencv/opencv/commit/085bd5f55f2e )

**Comment by sky-fly97** [comment]
Hello, I recompiled the latest master version, it is ok during cmake, but **many failures** occur when executing **ALL_BUILD** in VS2017.
I want to know whether the master version can be successfully compiled under windows10? Has anyone succeeded？

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/86096412-d27e6f80-bae5-11ea-8ab9-734e2136e44f.png)
![image](https://user-images.githubusercontent.com/55578436/86096471-e629d600-bae5-11ea-9e9a-079fec0295db.png)
![image](https://user-images.githubusercontent.com/55578436/86096989-a1eb0580-bae6-11ea-9cbd-6bd1f9807508.png)

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/86097044-b3cca880-bae6-11ea-9fa3-14d1032aa665.png)

**Comment by sky-fly97** [comment]
> [Confirmed](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/11222).
> 
> Broken by #17020
> 
> @sky-fly97 Try commit from June 26 ( [085bd5f](https://github.com/opencv/opencv/commit/085bd5f55f2e) ) or disable `BUILD_opencv_world=OFF`

Is there any files that have been compiled to share?

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/86098731-1d4db680-bae9-11ea-9770-4e4661eab698.png)
When I use **version 4.3**, there will be some numbers  at  **CUDA_ARCH_BIN** , but it is **empty** when compiling the **master version!**

**Comment by alalek** [comment]
@sky-fly97 Disable CUDA option or wait for fix of #17704 or specify `CUDA_ARCH_BIN` explicitly.
