### ISSUE TITLE
How to add native library for linux ?

### ISSUE THREAD

**Issue by PradeepSimba** [opencv/opencv#17673]
I added the opencv's native library for windows.

but, how can I add the opencv's native library for both linux 32 bit and 64 bit?

![Screenshot_20200626-201013_Edge](https://user-images.githubusercontent.com/45443554/85869459-53d5b980-b7e9-11ea-9d2d-daadc31f30f2.jpg)

In opencv release page there is no downloading option for linux. Then , How can I add the native library ?

where to download the opencv's native library for linux ?

Help me!!!

**Comment by dkurt** [comment]
There is no generic build for Linux because Linux is not OS - use compiler from your OS and build library from source code.

**Comment by PradeepSimba** [comment]
Can you give more information?

How can I build ?

**Comment by dkurt** [comment]
https://docs.opencv.org/master/db/df5/tutorial_linux_gcc_cmake.html
