### ISSUE TITLE
I would like to work on the issue https://github.com/opencv/opencv/issues/17448 so need some help 

### ISSUE THREAD

**Issue by cskarthik7** [opencv/opencv#17676]
I am new to OpenCV contribution and I would like to start off my journey by trying to solve this problem!

I would like to have some suggestions from experienced contributors to have a good start!

**Comment by alalek** [comment]
Do not open new issues about the other issues.
Maintainers don't have spare time to learn newcomers from scratch. You should learn yourself how to search related documents for building code, running tests, reproducing reported problems, debugging and finally contributing patches.
