### ISSUE TITLE
opencv-contrib-python-nonfree disappeared!

### ISSUE THREAD

**Issue by alexamosegui** [opencv/opencv#17693]
https://pypi.org/project/opencv-contrib-python-nonfree/ is not available any more.

`ERROR: Could not find a version that satisfies the requirement opencv-contrib-python-nonfree`

How can we access this repository? Does it have another name now?

**Comment by mshabunin** [comment]
We did not maintain this package.

**Comment by alexamosegui** [comment]
So which options do we have to use SIFT and SURF with Opencv now??

**Comment by mshabunin** [comment]
SIFT have been moved to main repository: https://github.com/opencv/opencv/pull/17119 , it is available on latest _3.4_ and _master_ branches but has not been released yet. You can build OpenCV by yourself using latest version from these branches or wait for official release and then wait for release of packages on PyPI or other 3rdparty package sources (which we do not support BTW).

To get SURF you have to either build OpenCV by yourself with  _opencv_contrib_ and `ENABLE_NONFREE=ON` cmake option or find another source of binary packages built in this configuration (we do not provide them).
