### ISSUE TITLE
TIFF file with bps=4 can't be opened

### ISSUE THREAD

**Issue by ferrine** [opencv/opencv#17705]
##### System information (version)
- Operating System / Platform => Archlinux/Ubuntu18

[cv2.getBuildInformation()](https://github.com/opencv/opencv/files/4852107/cv2.txt), Master branch

##### Detailed description
This file type can't be read
```
$ file Downloads/100016.jpg
Downloads/100016.jpg: TIFF image data, little-endian, direntries=15, height=341, bps=4, compression=LZW, PhotometricIntepretation=BlackIsZero, width=247
```
Most probable reason is **bps=4** since error message is
```
imread_('100016.jpg'): can't read header: OpenCV(4.4.0-pre) /home/username/.sources/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:322: error: (-2:Unspecified error) Invalid bitsperpixel value read from TIFF header! Must be 1, 8, 16, 32 or 64. in function 'readHeader'
```
#### Steps to reproduce
(looking for an image I can share)

**Comment by mshabunin** [comment]
OpenCV never supported bps=4, though 15 months ago this code was refactored with focus on safety. Multiple checks for unsupported and invalid images had been added. For example, result of `TIFFGetField(..., TIFFTAG_BITSPERSAMPLE,...)` call was not checked in older versions and image was treated as bps=8: https://github.com/opencv/opencv/commit/ba5ddd649957e42e61f3ebba620bf503e55e9c60#diff-7363c8cb934df72980ced2fa9c835418L237

Try to read all tags from a TIFF file using [tiffinfo](https://linux.die.net/man/1/tiffinfo) tool. And I want to also note that libtiff version can be important too, newer ones can handle non-conforming files differently. So it could be useful to try several versions of libtiff too (check comments in this issue for example: https://github.com/opencv/opencv/issues/17054).

**Comment by ferrine** [comment]
Thanks for that clear explanation
