### ISSUE TITLE
load DLDT model

### ISSUE THREAD

**Issue by menggui1993** [opencv/opencv#17703]
##### System information (version)
- OpenCV => 4.4.0-pre
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.5.0

##### Detailed description

readNetFromModelOptimizer() loads the net without error. But when I check the net layers with getLayerNames(), the net only contains output layers. Inference results invalid. The test model is downloaded from links at https://github.com/opencv/open_model_zoo/blob/master/models/intel/person-vehicle-bike-detection-crossroad-1016/model.yml.

Loading models from other framework works well. Inferencing with DNN_BACKEND_INFERENCE_ENGINE is also ok.

I installed openvino toolkit without opencv. Then I compiled opencv with -DWITH_INF_ENGINE=ON. Codes are the current master branch. Refer to https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#build-opencv-from-source. Compiling all fine without error.

**Comment by alalek** [comment]
Which commit/release is used from Inference Engine?

**Comment by dkurt** [comment]
> But when I check the net layers with getLayerNames(), the net only contains output layers.

It returns output layers by design.

> Inference results invalid

please provide a reproducer and what are valid results

**Comment by menggui1993** [comment]
It's my fault, I set the input scale and mean value wrong.

> It returns output layers by design.
But I think getLayerNames() should return all layers. We already had getUnconnectedOutLayersNames() for getting output layers.

**Comment by alalek** [comment]
This is limitation of used backend.
Anyway user can't interact with other internal layers (part of them can be fused by "Model Optimizer" and disappear completely).
Also GFLOPS approximation or per-layer performance stats are not working.
