### ISSUE TITLE
Can  I Cmake it in Windows?

### ISSUE THREAD

**Issue by Brittanygirl** [opencv/opencv#17717]
If you install your opencv through cmake, remove the arch bin version below 7 on the configuration file then rebuild/reinstall your opencv.
Note: cuda will not work if you install your opencv using pip /sudo apt install, use cmake instead.

_Originally posted by @bencha30 in https://github.com/opencv/opencv/issues/15858#issuecomment-584740614_

**Comment by bencha30** [comment]
yes, you can cmake it on windows.

**Comment by Brittanygirl** [comment]
thank you
