### ISSUE TITLE
OpenCV with OpenVINO - dual MYRIAD mPCIe

### ISSUE THREAD

**Issue by Omar-AE** [opencv/opencv#17727]
##### System information (version)

- OpenCV => 4.3.0-openvino
- Operating System / Platform => ubuntu 18.04
- Compiler => python 3.6.9

##### Detailed description

When I try to run my model using `cv2.dnn.DNN_TARGET_MYRIAD` while having the intel neural compute stick 2 (NCS2) connected, everything runs completely fine. However, when I insert the mPCIe 'vega-330' which has two Movidius MYRIAD cores, I get the following error.

```cv2.error: OpenCV(4.3.0-openvino) ../opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Can not init Myriad device: NC_ERROR in function 'initPlugin'```

When I use the demo files in the openvino directory '/opt/intel/openvino/deployment_tools/demo/', both the NCS2 and the mPCIe work though sometimes I face some issues with the mPCIe

The option used to run the demo using the mPCIe is `-d HDDL` while the option used to run it on the NCS2 is `-d MYRIAD`

In opencv, there is only the option `cv2.dnn.DNN_TARGET_MYRIAD`.

My question is: How do I run my opencv model (python) on the mPCIe?

**Comment by mshabunin** [comment]
I believe OpenCV does not support HDDL plugin (used for mPCIe card), only Myriad plugin (used for USB stick):
https://github.com/opencv/opencv/blob/a5fdcf9881176ce756b601ee4b926586a88a42fe/modules/dnn/src/dnn.cpp#L117-L129

You can try and hack this block by adding something like this:
```.cpp
if (std::string::npos != i->find("HDDL") && target == DNN_TARGET_MYRIAD)
    return true;
```
But we can not guarantee it will work.

**Comment by Omar-AE** [comment]
> I believe OpenCV does not support HDDL plugin (used for mPCIe card), only Myriad plugin (used for USB stick):
> 
> https://github.com/opencv/opencv/blob/a5fdcf9881176ce756b601ee4b926586a88a42fe/modules/dnn/src/dnn.cpp#L117-L129
> 
> You can try and hack this block by adding something like this:
> 
> ```c++
> if (std::string::npos != i->find("HDDL") && target == DNN_TARGET_MYRIAD)
>     return true;
> ```
> 
> But we can not guarantee it will work.

I tried to look for the directory 'modules' in the opencv library and couldn't find it, though the error above mentions the path `../opencv/modules/dnn/src/ie_ngraph.cpp`

I am not sure where can I find it or if opencv-4.3-openvino is open source in first place. I tried the following:
```
>>> import cv2
>>> cv2.__file__
'/opt/intel/openvino_2020.2.120/python/python3/cv2.abi3.so'
```
 what exactly is the .so file?

**Comment by mshabunin** [comment]
You have to build OpenCV from sources to try this. You can use the same version as in OpenVINO: https://github.com/opencv/opencv/releases/tag/4.3.0-openvino or the latest _master_ branch version. Default options should be fine but you'll need to enable InferenceEngine integration, check this article for details: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#build-opencv-from-source

**Comment by Omar-AE** [comment]
I replaced the opencv directory /opt/intel/openvino_2020.2.120/opencv with the source code that I downloaded from the link https://github.com/opencv/opencv/releases/tag/4.3.0-openvino
After that, I followed the second link that you referenced above. Here is what happened:

```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopencv_ml.so.4.3: cannot open shared object file: No such file or directory

```
Am I missing something? It seems it is still trying to load the library from the shared object (.so) file.

**Comment by mshabunin** [comment]
> I replaced the opencv directory /opt/intel/openvino_2020.2.120/opencv with the source code that I downloaded from the link

No, you have to build OpenCV from these sources.

**Comment by Omar-AE** [comment]
> No, you have to build OpenCV from these sources. Alternatively you can use InferenceEngine API instead of OpenCV DNN.

That's what I did. After replacing the opencv directory with the source I downloaded, I did run cmake with the options mentioned in the link. Now what's next?

**Comment by Omar-AE** [comment]
Ok now `import cv2` works. I tried your suggestion to add "HDDL" and it's giving the same error. I also replaced all "MYRIAD" (the string ones only) with "HDDL". Still having the same error:
```
cv2.error: OpenCV(4.3.0-openvino) /opt/intel/openvino_2020.2.120/opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = HDDL): no devices found in function 'initPlugin'
```

**Comment by Omar-AE** [comment]
Kindly refer to this for details about what happened [1239](https://github.com/openvinotoolkit/openvino/issues/1239)

**Comment by Omar-AE** [comment]
I managed to have the mpcie work on another motherboard, as the first one had hardware problem. Kindly refer to 1239 for details about what happened.

Now after replacing all the string "MYRIAD" with "HDDL" in the opencv-4.3.0-openvino source code, everything worked and I was able to run my opencv dnn model on the dual Movidius mpcie. One day later, I tried to run the same thing and I had the following error:

```
[INFO] loading YOLO from disk...
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    safe_people_count, close_people_count = AnalysisObj.SDAProcess(img, threshold=0.3, nms_threshold=0.8, crop=args.crop)
  File "/home/nvr/#######/social_distancing_detection.py", line 54, in SDAProcess
    layerOutputs = self.net.forward(self.ln)
cv2.error: OpenCV(4.3.0-openvino) /opt/intel/openvino_2020.3.194/opencv/modules/dnn/src/dnn.cpp:1089: error: (-213:The function/feature is not implemented) Unknown/unsupported target identifier in function 'wrapMat'
```
I'm still able to run using CPU but not MYRIAD.
Any idea what could be the problem?

**Comment by Omar-AE** [comment]
@alalek 
When I add setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE) to my code, it gives the following error:
```
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    safe_people_count, close_people_count = AnalysisObj.SDAProcess(img, threshold=0.3, nms_threshold=0.8, crop=args.crop)
  File "/home/nvr/microsoft/social_distancing_detection.py", line 53, in SDAProcess
    layerOutputs = self.net.forward(self.ln)
cv2.error: OpenCV(4.3.0-openvino) /opt/intel/openvino_2020.3.194/opencv/modules/dnn/src/dnn.cpp:1138: error: (-213:The function/feature is not implemented) Unknown backend identifier in function 'wrapMat'
```

**Comment by mshabunin** [comment]
@Omar-AE , since quick hack didn't help I recommend using InferenceEngine API for now, check [IE Python API reference](https://docs.openvinotoolkit.org/latest/ie_python_api/annotated.html). You will need to convert your model to IE format using [Model Optimizer](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html).

We will keep this issue opened as a feature request for HDDL backend in OpenCV _dnn_ module, but we can not help with investigation.

**Comment by Omar-AE** [comment]
@mshabunin 
It actually worked at some point (4 days ago). The error I'm getting above does not have anything to do with the "HDDL" or "MYRIAD". I tried replacing "HDDL" back with "MYRIAD" and the same error shows up.

**Comment by Omar-AE** [comment]
> You have to build OpenCV from sources to try this. You can use the same version as in OpenVINO: https://github.com/opencv/opencv/releases/tag/4.3.0-openvino or the latest _master_ branch version. Default options should be fine but you'll need to enable InferenceEngine integration, check this article for details: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#build-opencv-from-source

I downloaded an older version (commit) of the library linked in your comment, and I tried to build opencv from it. It seems to have an older version than the one that comes with openvino (I found libopencv_ml.so.3.4 in the ./build/lib directory while it is libopencv_ml.so.4.3 in the lib directory in the openvino version).

Anyway, after building opencv from the the downloaded source, I'm getting the following error:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopencv_ml.so.4.3: cannot open shared object file: No such file or directory
```
I don't know why it is still looking for the version that was installed by openvino. How can I tell python3 to look for the opencv I built from source?

**Comment by Omar-AE** [comment]
Copying files and subdirectories in the build directory to the previous directory (opencv directory) solved the issue. Now I can run my model on the mpcie through opencv-4.3-openvino after building opencv from the source: https://github.com/opencv/opencv/releases/tag/4.3.0-openvino

**Comment by mshabunin** [comment]
@Omar-AE , feel free to propose a PR with your changes.

**Comment by Omar-AE** [comment]
Sure 👍

**Comment by dkurt** [comment]
@Omar-AE, tests are not a part of library.

**Comment by Omar-AE** [comment]
Sure, but should I edit them to test the parts of code that I added?

**Comment by dkurt** [comment]
Got it. You need to just add this target to `BackendRegistry` from [dnn.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/dnn.cpp).

**Comment by Omar-AE** [comment]
My questions was if I have to edit the test files or not. I edited the code and its working now. However, I don't know if I have to change the related test files to test the new feature I added.

**Comment by mshabunin** [comment]
@Omar-AE , most tests in _dnn_ module automatically run on all available backends/targets, try to run them on your machine and check results. There can be some issues with specific backend (e.g. unsupported layers, different thresholds) which would require advanced handling ([example](https://github.com/opencv/opencv/blob/3547ac4b49a4f237f1546ccea5bdc2fbe4326d5f/modules/dnn/test/test_model.cpp#L366-L371).

Don't forget to set path to opencv_extra repository via environment: `OPENCV_TEST_DATA_PATH=<path-to-opencv_extra>/testdata` and download models using script `<opencv_extra>/testdata/dnn/download_models.py`.

**Comment by dkurt** [comment]
@Omar-AE, if you already have some code - please open a pull request. It's just easier to help in case of any issues.

**Comment by Omar-AE** [comment]
> @Omar-AE , most tests in _dnn_ module automatically run on all available backends/targets, try to run them on your machine and check results. There can be some issues with specific backend (e.g. unsupported layers, different thresholds) which would require advanced handling ([example](https://github.com/opencv/opencv/blob/3547ac4b49a4f237f1546ccea5bdc2fbe4326d5f/modules/dnn/test/test_model.cpp#L366-L371).
> 
> Don't forget to set path to opencv_extra repository via environment: `OPENCV_TEST_DATA_PATH=<path-to-opencv_extra>/testdata` and download models using script `<opencv_extra>/testdata/dnn/download_models.py`.

Aha I got it.

**Comment by Omar-AE** [comment]
> @Omar-AE, if you already have some code - please open a pull request. It's just easier to help in case of any issues.

I will open a PR shortly as soon as I finish.

**Comment by Omar-AE** [comment]
@dkurt @mshabunin 
Please refer to #18220.

**Comment by Omar-AE** [comment]
@dkurt @mshabunin 
Kindly see #18220
