### ISSUE TITLE
"Template Matching" tutorial page -> Can't choose another image

### ISSUE THREAD

**Issue by Keks244** [opencv/opencv#17739]
I can't upload another image to your template matching tutorial page.
[https://docs.opencv.org/master/d8/dd1/tutorial_js_template_matching.html](https://docs.opencv.org/master/d8/dd1/tutorial_js_template_matching.html)

Other tutorial pages are working fine for me.

Please Fix :)

**Comment by KSU5** [comment]
I'd like to give this a shot. Could you assign me?

**Comment by KSU5** [comment]
I think i know what the issue may be, could you assign me?

**Comment by KSU5** [comment]
I just fixed and created a pull request for this issue. I believe i submitted it to the correct base branch but let me know if there are any issues.

**Comment by Hitansh159** [comment]
hey @alalek,

I found the problem. Its pretty simple just a typo and a missing function call
can you assign it to me ?

Thank you for anticipation!! :smile:

**Comment by alalek** [comment]
No need to be assigned in case of small fixes.
Feel free to prepare Pull Request with adding reference on this issue (so other can see that).

BTW, Avoid mistakes like this one: #19228
