### ISSUE TITLE
undefined reference cv::error(int, std::string const&, char const*, char const*, int) in opencv 4.1.2

### ISSUE THREAD

**Issue by CaichaoGitHub** [opencv/opencv#17740]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => centos7.5
- Compiler => gcc5.5

##### Detailed description

i build opencv4.1.2 in my centos7.5 with gcc5.5 
i tried to create a Mat  using the API :  **cv::Mat(1,1,CV_8UC1, nullptr)**
but i met the undefined reference error : cv::error(int, std::string const&, char const*, char const*, int)
however i found the symbol exist in libopencv_core.so.4.1.2

##### ERROR INFO
libtlib.a(test.cpp.o)：在函数‘cv::Mat::Mat(int, int, int, void*, unsigned long)’中：
test.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x131)：对‘cv::error(int, std::string const&, char const*, char const*, int)’未定义的引用
test.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x1f6)：对‘cv::error(int, std::string const&, char const*, char const*, int)’未定义的引用

##### SYMBOL TEST
nm -a /usr/local/lib64/libopencv_core.so.4.1.2 | grep error
                 U dlerror@@GLIBC_2.2.5
00000000003c3f10 t __itt_report_error
00000000002c2aa0 T _ZN2**cv5error**EiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKcS9_i
00000000002c1340 T _ZN2**cv5error**ERKNS_9ExceptionE
000000000022b9a0 T _ZNK2cv3ocl6Device22errorCorrectionSupportEv
                 U _ZSt19__throw_logic_errorPKc@@GLIBCXX_3.4
                 U _ZSt20__throw_length_errorPKc@@GLIBCXX_3.4
                 U _ZSt20__throw_system_errori@@GLIBCXX_3.4.11

##### MY CODE
cv::Mat testit()
{
	auto m = cv::Mat(1,1,CV_8UC1, nullptr);
	return m;
}

##### TEST OPENCV 4.3.0
i build opencv4.3.0, i met the same problem 

##### TEST OPENCV 3.4.10
i build opencv3.4.10 , the program worked perfectly

**Comment by alalek** [comment]
> my centos7.5 with gcc5.5

Compiler is not default for [CentOS 7](https://centos.pkgs.org/7/centos-x86_64/gcc-4.8.5-39.el7.x86_64.rpm.html), so you may have a mess with compiler settings/flags/incompatibility.

Try to inspect your complete command lines for compiler / linker invocations.

Also you may want to learn this topic: https://stackoverflow.com/questions/45417707/glibcxx-use-cxx11-abi-gcc-4-8-and-abi-compatibility

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by CaichaoGitHub** [comment]
> > my centos7.5 with gcc5.5
> 
> Compiler is not default for [CentOS 7](https://centos.pkgs.org/7/centos-x86_64/gcc-4.8.5-39.el7.x86_64.rpm.html), so you may have a mess with compiler settings/flags/incompatibility.
> 
> Try to inspect your complete command lines for compiler / linker invocations.
> 
> Also you may want to learn this topic: https://stackoverflow.com/questions/45417707/glibcxx-use-cxx11-abi-gcc-4-8-and-abi-compatibility
> 
> Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

thanks very much , i got it ; let me fix it
