### ISSUE TITLE
Opencv dnn - support on Yolov4-tiny 

### ISSUE THREAD

**Issue by brianng0305** [opencv/opencv#17749]
Yolov4-tiny was issued last week. I used yolov4-tiny to train my dataset for 10 hours with 0.7 average loss. I am very satisfied with the darknet test very accurate but using opencv yolo dnn to detect show nothing.

My project need yolov4-tiny running with opencv. Please help.

issued to darknet:
https://github.com/AlexeyAB/darknet/issues/6131

**Comment by YashasSamaga** [comment]
YOLOv4 tiny has some new fields in the configuration file which isn't supported yet (on master). It loads without errors but is not correct. You need the latest 3.4 to run yolov4 tiny.

**Comment by brianng0305** [comment]
Thank you YashasSamaga.

**Comment by dkurt** [comment]
solved by https://github.com/opencv/opencv/pull/17733

**Comment by marcusbrito** [comment]
Will the yolov4-tiny update be available on the release of OpenCV 4.4?

It would be great, as the full size YoloV4 will be available.
