### ISSUE TITLE
cv2.dnn.readNet(args["east"])

### ISSUE THREAD

**Issue by Lumi1717** [opencv/opencv#17755]
##### System information (version)

cv2.dnn.readNet(args["east"])
cv2.error: OpenCV(4.2.0) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/dnn.cpp:4723: error: (-2:Unspecified error) Cannot determine an origin framework of files:  in function 'readNet'

**Comment by dkurt** [comment]
`args["east"]` is empty
