### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by chluck2008** [opencv/opencv#17765]
cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DENABLE_CXX11=ON \
        -DBUILD_DOCS=OFF \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_JASPER=OFF \
        -DBUILD_OPENEXR=OFF \
        -DBUILD_PERF_TESTS=OFF \
        -DBUILD_TESTS=OFF \
        -DWITH_EIGEN=ON \
        -DWITH_FFMPEG=ON \
        -DWITH_OPENMP=ON \
        ..

In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:39:3: error: conflicting declaration ‘typedef struct omp_lock_t omp_lock_t’
 } omp_lock_t;
   ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:69:7: note: previous declaration as ‘typedef struct omp_lock_t omp_lock_t’
     } omp_lock_t;
       ^
In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:50:3: error: conflicting declaration ‘typedef struct omp_nest_lock_t omp_nest_lock_t’
 } omp_nest_lock_t;
   ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:80:7: note: previous declaration as ‘typedef struct omp_nest_lock_t omp_nest_lock_t’
     } omp_nest_lock_t;
       ^
In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:53:14: error: multiple definition of ‘enum omp_sched_t’
 typedef enum omp_sched_t
              ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:35:18: note: previous definition here
     typedef enum omp_sched_t {
                  ^
In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:59:3: error: conflicting declaration ‘typedef int omp_sched_t’
 } omp_sched_t;
   ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:40:7: note: previous declaration as ‘typedef enum omp_sched_t omp_sched_t’
     } omp_sched_t;
       ^
In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:61:14: error: multiple definition of ‘enum omp_proc_bind_t’
 typedef enum omp_proc_bind_t
              ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:143:18: note: previous definition here
     typedef enum omp_proc_bind_t {
                  ^
In file included from /home/admin1234/openvslam_ws/opencv/modules/core/src/parallel.cpp:103:0:
/usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h:68:3: error: conflicting declaration ‘typedef int omp_proc_bind_t’
 } omp_proc_bind_t;
   ^
In file included from /usr/include/eigen3/Eigen/Core:210:0,
                 from /home/admin1234/openvslam_ws/opencv/modules/core/include/opencv2/core/private.hpp:66,
                 from /home/admin1234/openvslam_ws/opencv/build/modules/core/precomp.hpp:55:
/usr/include/omp.h:149:7: note: previous declaration as ‘typedef enum omp_proc_bind_t omp_proc_bind_t’
     } omp_proc_bind_t;
       ^
modules/core/CMakeFiles/opencv_core.dir/build.make:89: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o' failed
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o] Error 1
CMakeFiles/Makefile2:1396: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 25%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/type.pb.cc.o
[ 25%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/unknown_field_set.cc.o
[ 25%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/delimited_message_util.cc.o
[ 25%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/field_comparator.cc.o
[ 26%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/field_mask_util.cc.o

**Comment by alalek** [comment]
> /usr/lib/gcc/x86_64-linux-gnu/5/include/omp.h
> /usr/include/omp.h

You have mess on your system.
This can't be fixed by OpenCV. Closing.
