### ISSUE TITLE
Opencv compiled with CUDA in Python uses videocapture to leak memory

### ISSUE THREAD

**Issue by XZG-0457** [opencv/opencv#17774]
![image](https://user-images.githubusercontent.com/43441239/86792418-0d137980-c09d-11ea-934c-dc741641f567.png)

**Comment by XZG-0457** [comment]
According to the Valgrind report, 60k bytes leak during one prediction. => 2G？ Mb leak within 30 minutes. This is perfectly matched with the graph attached to the issue.It's terrible！ I think that when I call cv2.so in Python, there will be a memory leak. But how can I free the memory? After all, they are already in the so file

**Comment by XZG-0457** [comment]
According to the Valgrind report, 60k bytes leak during one prediction. => 2G? leak within 30 minutes. It's terrible！ I think that when I call cv2.so in Python, there will be a memory leak. But how can I free the memory? After all, they are already in the so file

**Comment by mshabunin** [comment]
@XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

**Comment by XZG-0457** [comment]
> @XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

ok，Part of the code：

width = 0
height = 0
resize = False
detect_width = 0
detect_height = 0
fp = -1
count = 0
fp_skip = 1
set_num = 0

lumGPU = cv2.cuda_GpuMat()
while (store_status['status'] != 2): # stop
    try:
        lasttime = time.time()
        # image = vidcap.read()
        success = vidcap.grab()
        if not success:
            print("frame read end or read error")
            break
        fp += 1
        true_fp += 1
        _, image = vidcap.retrieve()
        createTime = time.time()
        ta = time.time()
        if (width == 0):
            if (isresize == 1):
                width, height, resize = max_video_width, max_video_height, True
            else:
                width = image.shape[1]
                height = image.shape[0]
        try:

            if (resize == True):
                lumGPU.upload(image)
                gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
                img = gpu_mat.download()
                screenFlag = 1
            org_image = img  # debug output
        except Exception as e:
            traceback.print_exc()
            print("resize error:", str(e))
            fp -= 1
            true_fp -= 1
            continue

        mem_point, begin, end = arr_ope.setImage(img)

**Comment by XZG-0457** [comment]
> @XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

ok，Part of the code：

width = 0
height = 0
resize = False
detect_width = 0
detect_height = 0
fp = -1
count = 0
fp_skip = 1
set_num = 0

lumGPU = cv2.cuda_GpuMat()
while (store_status['status'] != 2): # stop
    try:
        lasttime = time.time()
        # image = vidcap.read()
        success = vidcap.grab()
        if not success:
            print("frame read end or read error")
            break
        fp += 1
        true_fp += 1
        _, image = vidcap.retrieve()
        createTime = time.time()
        ta = time.time()
        if (width == 0):
            if (isresize == 1):
                width, height, resize = max_video_width, max_video_height, True
            else:
                width = image.shape[1]
                height = image.shape[0]
        try:
            if (resize == True):
                lumGPU.upload(image)
                gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
                img = gpu_mat.download()
                screenFlag = 1
            org_image = img  # debug output
        except Exception as e:
            traceback.print_exc()
            print("resize error:", str(e))
            fp -= 1
            true_fp -= 1
            continue

        mem_point, begin, end = arr_ope.setImage(img)

**Comment by XZG-0457** [comment]
`width = 0
height = 0
resize = False
detect_width = 0
detect_height = 0
fp = -1
count = 0
fp_skip = 1
set_num = 0

lumGPU = cv2.cuda_GpuMat()
while (store_status['status'] != 2): # stop
    try:
        lasttime = time.time()
        # image = vidcap.read()
        success = vidcap.grab()
        if not success:
            print("frame read end or read error")
            break
        fp += 1
        true_fp += 1
        _, image = vidcap.retrieve()
        createTime = time.time()
        ta = time.time()
        if (width == 0):
            if (isresize == 1):
                width, height, resize = max_video_width, max_video_height, True
            else:
                width = image.shape[1]
                height = image.shape[0]
        try:
            if (resize == True):
                lumGPU.upload(image)
                gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
                img = gpu_mat.download()
                screenFlag = 1
            org_image = img  # debug output
        except Exception as e:
            traceback.print_exc()
            print("resize error:", str(e))
            fp -= 1
            true_fp -= 1
            continue

        mem_point, begin, end = arr_ope.setImage(img)`

**Comment by XZG-0457** [comment]
`width = 0
height = 0
resize = False
detect_width = 0
detect_height = 0
fp = -1
count = 0
fp_skip = 1
set_num = 0

lumGPU = cv2.cuda_GpuMat()
while (store_status['status'] != 2): # stop
    try:
        lasttime = time.time()
        # image = vidcap.read()
        success = vidcap.grab()
        if not success:
            print("frame read end or read error")
            break
        fp += 1
        true_fp += 1
        _, image = vidcap.retrieve()
        createTime = time.time()
        ta = time.time()
        if (width == 0):
            if (isresize == 1):
                width, height, resize = max_video_width, max_video_height, True
            else:
                width = image.shape[1]
                height = image.shape[0]
        try:
            if (resize == True):
                lumGPU.upload(image)
                gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
                img = gpu_mat.download()
                screenFlag = 1
            org_image = img  # debug output
        except Exception as e:
            traceback.print_exc()
            print("resize error:", str(e))
            fp -= 1
            true_fp -= 1
            continue
        mem_point, begin, end = arr_ope.setImage(img)`

**Comment by XZG-0457** [comment]
```python
width = 0
height = 0
resize = False
detect_width = 0
detect_height = 0
fp = -1
count = 0
fp_skip = 1
set_num = 0

lumGPU = cv2.cuda_GpuMat()
while (store_status['status'] != 2): # stop
    try:
        lasttime = time.time()
        # image = vidcap.read()
        success = vidcap.grab()
        if not success:
            print("frame read end or read error")
            break
        fp += 1
        true_fp += 1
        _, image = vidcap.retrieve()
        createTime = time.time()
        ta = time.time()
        if (width == 0):
            if (isresize == 1):
                width, height, resize = max_video_width, max_video_height, True
            else:
                width = image.shape[1]
                height = image.shape[0]
        try:
            if (resize == True):
                lumGPU.upload(image)
                gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
                img = gpu_mat.download()
                screenFlag = 1
            org_image = img  # debug output
        except Exception as e:
            traceback.print_exc()
            print("resize error:", str(e))
            fp -= 1
            true_fp -= 1
            continue
        mem_point, begin, end = arr_ope.setImage(img)
```

**Comment by XZG-0457** [comment]
> @XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

**Comment by XZG-0457** [comment]
> @XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

Yes, I tested 50 RTMP video sources and found that the memory leakage was very serious. It was not so obvious in the past few times, because it did not exceed 1 hour

**Comment by XZG-0457** [comment]
> @XZG-0457 , please provide more details about your configuration as well as small test application reproducing the issue. Did you measure the leak for cases with more than one prediction?

I have also tried to push the stream with OpenCV of CPU version, because the decoding of OpenCV cannot be stopped, but it is not as exaggerated as the memory leakage of GPU version

**Comment by XZG-0457** [comment]
> ```python
> width = 0
> height = 0
> resize = False
> detect_width = 0
> detect_height = 0
> fp = -1
> count = 0
> fp_skip = 1
> set_num = 0
> 
> lumGPU = cv2.cuda_GpuMat()
> while (store_status['status'] != 2): # stop
>     try:
>         lasttime = time.time()
>         # image = vidcap.read()
>         success = vidcap.grab()
>         if not success:
>             print("frame read end or read error")
>             break
>         fp += 1
>         true_fp += 1
>         _, image = vidcap.retrieve()
>         createTime = time.time()
>         ta = time.time()
>         if (width == 0):
>             if (isresize == 1):
>                 width, height, resize = max_video_width, max_video_height, True
>             else:
>                 width = image.shape[1]
>                 height = image.shape[0]
>         try:
>             if (resize == True):
>                 lumGPU.upload(image)
>                 gpu_mat = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)
>                 img = gpu_mat.download()
>                 screenFlag = 1
>             org_image = img  # debug output
>         except Exception as e:
>             traceback.print_exc()
>             print("resize error:", str(e))
>             fp -= 1
>             true_fp -= 1
>             continue
>         mem_point, begin, end = arr_ope.setImage(img)
> ```

It's part of my code

**Comment by XZG-0457** [comment]
I think it is caused by a lot of memory leaks when the CPU and GPU are switched, because I see cv2.so in the valgrind log, there are many functions of cuda initialization and creation, but python seems to be unable to prevent this behavior
