### ISSUE TITLE
Failed to match UMat descriptors

### ISSUE THREAD

**Issue by smartnet-club** [opencv/opencv#17771]
[patch.txt](https://github.com/opencv/opencv/files/4883132/patch.txt)
##### System information (version)

- OpenCV => master
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 6.5

##### Detailed description

Failed to match UMat descriptors

Error in modules/features2d/src/matchers.cpp#L632

in call !trainDescCollection[i].empty()

trainDescCollection is empty

**Comment by dkurt** [comment]
Please provide a reproducer.

**Comment by smartnet-club** [comment]
Reproducer:
Use [this](https://docs.opencv.org/master/d5/d6f/tutorial_feature_flann_matcher.html) tutorial.
Replace `Mat descriptors1, descriptors2;` by `UMat descriptors1, descriptors2;`
