### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'dnn_DetectionModel

### ISSUE THREAD

**Issue by SkuzzyxD** [opencv/opencv#17776]
##### System information (version)

- OpenCV => 3.4.11-pre
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
Error:
```Traceback (most recent call last):
  File "detector.py", line 3, in <module>
    net = cv.dnn_DetectionModel('yolo/yolov4.cfg', 'yolo/yolov4.weights')
AttributeError: module 'cv2' has no attribute 'dnn_DetectionModel'```

##### Steps to reproduce

Script used:
```import cv2 as cv

net = cv.dnn_DetectionModel('yolo/yolov4.cfg', 'yolo/yolov4.weights')
net.setInputSize(608, 608)
net.setInputScale(1.0 / 255)
net.setInputSwapRB(True)

frame = cv.imread('images/example.jpeg')

with open('yolo/coco.names', 'rt') as f:
    names = f.read().rstrip('\n').split('\n')

classes, confidences, boxes = net.detect(frame, confThreshold=0.1, nmsThreshold=0.4)
for classId, confidence, box in zip(classes.flatten(), confidences.flatten(), boxes):
    label = '%.2f' % confidence
    label = '%s: %s' % (names[classId], label)
    labelSize, baseLine = cv.getTextSize(label, cv.FONT_HERSHEY_SIMPLEX, 0.5, 1)
    left, top, width, height = box
    top = max(top, labelSize[1])
    cv.rectangle(frame, box, color=(0, 255, 0), thickness=3)
    cv.rectangle(frame, (left, top - labelSize[1]), (left + labelSize[0], top + baseLine), (255, 255, 255), cv.FILLED)
    cv.putText(frame, label, (left, top), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0))

cv.imshow('out', frame)```

**Comment by berak** [comment]
> OpenCV => 3.4.11-pre

unfortunately, the "dnn High Level Api" is only available on the 4.x / master branch (ABI compliance)

**Comment by SkuzzyxD** [comment]
But here it's shown as working:
https://github.com/opencv/opencv/pull/17185

**Comment by berak** [comment]
@SkuzzyxD  yes, you can  use yolov4 (e.g. [from here](https://github.com/opencv/opencv/blob/3.4/samples/dnn/object_detection.py)), just  not the `cv.dnn_DetectionModel` class

**Comment by Astroboy1011** [comment]
So I am working on a detection model, unfortunately I am getting similar kind of error (i.e 

my code -> 
net = cv2.dnn.readNet("dnn_model/yolov4-tiny.weights", "dnn_model/yolov4-tiny.cfg")
model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(320, 320), scale=1/255)) 


Here the complier is not able to detect the code line 
model = cv2.dnn_DetectionModel(net) ( as the output i desire should have some values but I am not able to get any values. Here is the snip of that as well.) I have installed the packages opencv-contrib-python as well upgrade version. Any idea to fix this. Thanks
![Capture](https://github.com/user-attachments/assets/86d5288f-8962-4147-8a6e-8588bdbacd2d)
