### ISSUE TITLE
DNN with CUDA not working on python 

### ISSUE THREAD

**Issue by mirhanu** [opencv/opencv#17779]
OpenCV => 4.2
Operating System / Platform => ubuntu

I am using opencv to run yolo. Below is the code to set Backend.

net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

In the above command, there is no error with CUDA , but when the code is actually executed, the GPU is not used. I don't see any difference in inference time compared to CPU. However when I run detection on C++ it works and i get around 15 FPS.

When I set  export OPENCV_LOG_LEVEL=INFO this is printed:

[ INFO:0] global /home/train/finalopencv/opencv/modules/videoio/src/videoio_registry.cpp (187) VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940)
[ INFO:0] global /home/train/finalopencv/opencv/modules/core/src/ocl.cpp (891) haveOpenCL Initialize OpenCL runtime...
[ INFO:0] global /home/train/finalopencv/opencv/modules/dnn/src/dnn.cpp (2204) initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

CMAKE:
cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D WITH_CUDA=ON \
	-D WITH_CUDNN=ON \
	-D OPENCV_DNN_CUDA=ON \
	-D ENABLE_FAST_MATH=1 \
	-D CUDA_FAST_MATH=1 \
	-D CUDA_ARCH_BIN=5.3 \
	-D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2 \
	-D WITH_CUBLAS=1 \
	-D OPENCV_EXTRA_MODULES_PATH=/media/7f1d5029-213b-4978-a5fc-979fcc67e3e5/opencv/opencv_contrib/modules \
	-D HAVE_opencv_python3=ON \
	-D CUDA_HOST_COMPILER=/usr/bin/gcc-7 \
	-D WITH_GSTREAMER=ON \
	-D WITH_FFMPEG=ON \
	-D PYTHON_EXECUTABLE=/usr/bin/python3 ..

**Comment by YashasSamaga** [comment]
Please check your CMake output if cuDNN was found.

**Comment by mirhanu** [comment]
It is found
