### ISSUE TITLE
opencv4.1.0+cuda10.0，modules/core/CMakeFiles/opencv_perf_core.dir/all

### ISSUE THREAD

**Issue by libingsy** [opencv/opencv#17781]
[ 18%] Linking CXX executable ../../bin/opencv_perf_core
cd /home/libing/mmaction/third_party/opencv-4.1.0/build/modules/core && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_core.dir/link.txt --verbose=1
/usr/bin/c++      -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffast-math -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-undef -Wno-enum-compare -Wno-unused-function -Wno-shadow -O3 -DNDEBUG  -DNDEBUG    -Wl,--gc-sections   CMakeFiles/opencv_perf_core.dir/perf/perf_compare.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_merge.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_dot.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_minmaxloc.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_reduce.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_mat.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_arithm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_norm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_sort.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_lut.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_math.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_dft.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_cvround.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_abs.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_bufferpool.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_arithm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_channels.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_usage_flags.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_gemm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_matop.cpp.o CMakeFiles/opencv_perf_core.dir/perf/opencl/perf_dxt.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_addWeighted.cpp.o CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_inRange.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_bitwise.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_io_base64.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_umat.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_convertTo.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_split.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_stat.cpp.o  -o ../../bin/opencv_perf_core  -L/usr/local/cuda-10.0/lib64 ../../lib/libopencv_ts.a ../../lib/libopencv_highgui.so.4.1.0 -ldl -lm -lpthread -lrt -lcudart -lnppc -lnppial -lnppicc -lnppicom -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcufft -L/usr/local/cuda-10.0/lib64 ../../lib/libopencv_videoio.so.4.1.0 ../../lib/libopencv_imgcodecs.so.4.1.0 ../../lib/libopencv_imgproc.so.4.1.0 ../../lib/libopencv_core.so.4.1.0 ../../lib/libopencv_cudev.so.4.1.0 -Wl,-rpath,/usr/local/cuda-10.0/lib64:/home/libing/mmaction/third_party/opencv-4.1.0/build/lib 
../../lib/libopencv_core.so.4.1.0: undefined reference to `cv::error(int, std::string const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_perf_core.dir/build.make:881: recipe for target 'bin/opencv_perf_core' failed
make[2]: *** [bin/opencv_perf_core] Error 1
make[2]: Leaving directory '/home/libing/mmaction/third_party/opencv-4.1.0/build'
CMakeFiles/Makefile2:2617: recipe for target 'modules/core/CMakeFiles/opencv_perf_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
make[1]: Leaving directory '/home/libing/mmaction/third_party/opencv-4.1.0/build'
Makefile:160: recipe for target 'all' failed

I don't know where is the problem? Can anybody tell where is wrong?

**Comment by hktxt** [comment]
same, did you fix it?
