### ISSUE TITLE
yolov4 dnn lower performance 

### ISSUE THREAD

**Issue by toplinuxsir** [opencv/opencv#17795]
##### System information (version)

- OpenCV => 4.4-pre
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc8.4
If I use opencv dnn(cuda backend) to detect with yolov4 model is 10.0 fps
If I use darknet to detect with yolov4 model is 30fps 

All above tests use the same GPU

**Comment by dkurt** [comment]
Please provide all the necessary information - CUDA driver version, device. Which performance you have on CPU?

**Comment by toplinuxsir** [comment]
@dkurt  CUDA version 10.2 , The CPU performance is aobut 1 fps

**Comment by YashasSamaga** [comment]
@toplinuxsir can you show the code that measures the FPS? What device are you using?

YOLOv4 FPS on RTX 2080 Ti with 608x608 image

Darknet FP16 | OpenCV CUDA FP32 | OpenCV CUDA FP16 | tkDNN + TensorRT FP32 | tkDNN + TensorRT FP16
------------------ | ----------------------------- | ----------------------------- | --------------------------------- | ---------------------------------
57                   | 60                               | 115                              | 64                                     | 111

**Comment by toplinuxsir** [comment]
How to use FP16 with dnn ?

**Comment by dkurt** [comment]
`net.setPreferableTarget(DNN_TARGET_CUDA_FP16)`

see https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a9dddbefbc7f3defbe3eeb5dc3d3483f4

**Comment by toplinuxsir** [comment]
@dkurt  I use python code , If I change to FP16 ,the fps up to 88 ., Maybe the python code lower the performance 
Thanks !

**Comment by dkurt** [comment]
@toplinuxsir, you must measured with postprocessing, right? Please take a look at https://github.com/opencv/opencv/issues/17204

**Comment by toplinuxsir** [comment]
@dkurt  Thanks , I got it.

**Comment by dkurt** [comment]
Can we close it?

**Comment by toplinuxsir** [comment]
@dkurt  Yes

**Comment by yiwenwan2008** [comment]
@toplinuxsir may i ask which GPU did you test on?

**Comment by utsembedded** [comment]
@YashasSamaga 

I'm using opencv_dnn based yolov4 algorithm.
downloaded from: https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49

**Comment by dkurt** [comment]
@utsembedded, you need to perform NMS anyway but not for `[yolo]` layers. Take a look at https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp or [cv::dnn::DetectionModel](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html)
