### ISSUE TITLE
Error when use  cv::cudacodec::VideoReader by opencv_cudacodec with cuda 10.1, ubuntu18.04

### ISSUE THREAD

**Issue by DuongNo** [opencv/opencv#17798]
**System information (version)**

- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04.4 LTS
- Compiler => gcc-6

**Detailed description**
- I got a Nvidia GeForce 2080.
- I installed the driver which version is 440.33.01, cuda 10.1, cudnn 7.5
- I'm was build success OpenCV with option :  BUILD_opencv_cudacodec=ON
- But there's an error while I running program use :

`cv::Ptr<cv::cudacodec::VideoReader> d_reader = cv::cudacodec::createVideoReader(fname);`

get error:
`terminate called after throwing an instance of 'cv::Exception' what(): OpenCV(4.2.0) /root/opencv_contrib-4.2.0/modules/cudacodec/src/video_decoder.cpp:101: error: (-210:Unsupported format or combination of formats) Video source is not supported by hardware video decoder in function 'create'`

Can someone help me to solve this issue?

**Steps to reproduce**
Get opencv and opencv_contrib release 4.0.1 from github.

### `cmake -D CMAKE_BUILD_TYPE=RELEASE \ 
	-D CMAKE_C_COMPILER=/usr/bin/gcc-6 \ 
-D CMAKE_INSTALL_PREFIX=/usr/local \ 
-D INSTALL_PYTHON_EXAMPLES=ON \ 
-D INSTALL_C_EXAMPLES=OFF \ 
 -D BUILD_PERF_TESTS=OFF \ 
-D WITH_TBB=ON \
-D WITH_CUDA=ON \
-D BUILD_opencv_cudacodec=ON \
-D WITH_NVCUVID=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D WITH_V4L=ON \
-D WITH_QT=ON \
-D WITH_OPENGL=ON \
-D WITH_GSTREAMER=ON \
-D OPENCV_GENERATE_PKGCONFIG=ON \
-D OPENCV_PC_FILE_NAME=opencv.pc \
-D OPENCV_ENABLE_NONFREE=ON \
-D OPENCV_PYTHON3_INSTALL_PATH=~/.virtualenvs/cv/lib/python3.6/site-packages \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.2.0/modules \
-D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
-D BUILD_EXAMPLES=OFF \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D CUDA_ARCH_BIN=7.5 ..`

**result after build** 
`[100%] Linking CXX shared module ../../lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so
[100%] Built target opencv_python3`

After that i run program VideoReader with GPU following link:
https://github.com/opencv/opencv/blob/master/samples/gpu/video_reader.cpp
and get error:

`terminate called after throwing an instance of 'cv::Exception' what(): OpenCV(4.2.0) /root/opencv_contrib-4.2.0/modules/cudacodec/src/video_decoder.cpp:101: error: (-210:Unsupported format or combination of formats) Video source is not supported by hardware video decoder in function 'create'`

**Comment by mshabunin** [comment]
Perhaps your video format is not supported by the hardware video decoder (https://github.com/opencv/opencv_contrib/blob/6d801fca93013d96d1e3851080084120f3b8b65f/modules/cudacodec/src/video_decoder.cpp#L93-L101). Please consult with CUDA documentation.
