### ISSUE TITLE
opencv will not build properly in cmake, cmake/OpenCVGenSetupVars.cmake ERROR

### ISSUE THREAD

**Issue by deepkak** [opencv/opencv#17793]
- OpenCV = 4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
python 3.7

##### Detailed description

I am now building from source the opencv4.1.0 with cmake3.13. The cmake configuration gives a warning message saying:

CMake Error at cmake/OpenCVGenSetupVars.cmake:1:
  Parse error.  Expected a command name, got quoted argument with text
  "cmake.cmakePath".
Call Stack (most recent call first):
  CMakeLists.txt:1066 (include)

What does this mean? How can I fix this?

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc16).

> 4.1

Try latest release or code from master branch first.

> Parse error. Expected a command name, got quoted argument with text "cmake.cmakePath".

There is no such text in OpenCV. It comes from CMake.
Try to upgrade CMake too.
