### ISSUE TITLE
Question : Shared mat and isSubmatrix()

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#17797]
For performances reasons, I often need to know if a matrix is referencing another one or is self-contained. If it is a reference, I must release() it before using it as a temporary matrix to store results.

So far, I query the ->u->refcount field, but I am unhappy with such a hack.
I though that using isSubmatrix() would be the solution, but it is not.
```
  cv::Mat org(cv::Size(1280, 1024), CV_32FC1);
  cv::Mat roi(org, cv::Rect(0, 0, 10, 10));
  cv::Mat ref_org = org;
  cv::Mat ref_roi = roi;
  printf("org.isSubmatrix : %d\r\n", org.isSubmatrix()); //-> NO
  printf("roi.isSubmatrix : %d\r\n", roi.isSubmatrix());//-> YES
  printf("ref_org.isSubmatrix : %d\r\n", ref_org.isSubmatrix());//-> NO, I expected YES as a "full frame submatrix"
  printf("ref_roi.isSubmatrix : %d\r\n", ref_roi.isSubmatrix());//-> YES
```
Is there any reason why ref_org is not considered a subMatrix ? This could make sense for my problem.

**Comment by alalek** [comment]
> isSubmatrix

has meaning in terms of borders for image filtering. There is nothing to deal with reference counting.
