### ISSUE TITLE
Help Me !  ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Rudikaizan** [opencv/opencv#17802]
I experienced an error like this
anyone can help me?
  _ , contours, hierarchy = cv2.findContours(peaks8u, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by sturkmen72** [comment]
contours, hierarchy = cv2.findContours(peaks8u, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Rudikaizan** [comment]
thank you
