### ISSUE TITLE
When building ALL_BUILD in VS, It infinitely loops around 25>C:

### ISSUE THREAD

**Issue by mattengl2** [opencv/opencv#17808]
- OpenCV = latest, downloaded from master branch here
- Operating System / Platform => Windows 64 Bit, Windows 10
- Compiler => Visual Studio 2019
- cuda 10.2.89 (could not get it to work with 11)
- cudnn 7.6.5 

##### Detailed description

I downloaded opencv from source, and built it with no errors using the latest version of cmake. I opened up the ALL_BUILD.vcx.proj file in VS, hit release, and then hit build for all_build. It starts running and then stops at around 25, I get this error...

25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(501): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(693): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(729): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/types.hpp(530): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/types.hpp(532): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/types.hpp(771): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/mat.hpp(257): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/mat.hpp(2684): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/mat.hpp(2685): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/mat.hpp(3552): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/persistence.hpp(462): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/persistence.hpp(465): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core.hpp(115): warning : base class dllexport/dllimport specification differs from that of the derived class
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core.hpp(135): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core.hpp(138): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core.hpp(139): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core.hpp(140): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(501): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(693): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>C:/opencv/opencv-master/modules/core/include\opencv2/core/cuda.hpp(729): warning : field of class type without a DLL interface used in a class with a DLL interface
25>
25>add_mat.cu
25>Building NVCC (Device) object modules/world/CMakeFiles/cuda_compile_1.dir/__/__/__/opencv_contrib-master/modules/cudaarithm/src/cuda/Release/cuda_compile_1_generated_add_scalar.cu.obj
25>add_scalar.cu

and so on. Could you please help me determine the problem here?

**Comment by alalek** [comment]
CUDA compilation takes several hours with MSVS generator.

> 25>add_mat.cu
> 25>add_scalar.cu

Process has progress.
25 is just a number of active MSBuild "tasks". It is not a progress.

BTW, CUDA files are compiled with MSVS in "one thread", one by one.

> world

It is bad idea to use `BUILD_opencv_world` which increases build time significantly.

**Comment by mattengl2** [comment]
I'll compile without opencv world. So the warnings are not a concern?
