### ISSUE TITLE
Is there a way to provide 1-D array of dlib points as a input to trained Tensorflow/Keras model loaded in C++ using dnn::Net net = readNetFromTensorflow(modelFile);

### ISSUE THREAD

**Issue by D1vyansh** [opencv/opencv#17814]
##### System information (version)
 

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Dlib => 19.19

##### Detailed description

I trained a tensorflow/Keras MLP model in python which takes an input of 2278 dlib facial feature points and predicts the yaw, pitch and roll of the face(Output = 3 values). I am trying to evaluate the model in C++ by loading the model using readNetFromTensorflow() function.

How should I set the net.setInput() function in C++ as I am not using blobFromImage() for providing the input? How to pass array of features in OpenCV/C++ model and get the prediction??

##### Steps to reproduce

- Train Multilayer Perceptron Model in Python
- Convert it to be used in C++/OpenCV
- Unable to evaluate it in C++

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp 
dnn::Net net = readNetFromTensorflow(modelFile)
   ``` or attach as .txt or .zip file
-->

```.cpp
dnn::Net net = readNetFromTensorflow(modelFile)
net.setInput()
Mat result = net.forward();
```

**Comment by dkurt** [comment]
There is no 1D input in Keras - it's always has implicit batch dimension. So you need to pass input as 2D Mat.
