### ISSUE TITLE
cv2.writeOpticalFlow can not save the image into .flo format, it always return false,  I don't know why, is there any special requirement on  using this function?

### ISSUE THREAD

**Issue by ZHANGWEILIN1** [opencv/opencv#17820]
![image](https://user-images.githubusercontent.com/49618016/87242676-78749700-c461-11ea-9472-060b19e5746d.png)

**Comment by ZHANGWEILIN1** [comment]
I have already make sure the array shape to be (height, width, 2) shape, but it can not save

**Comment by alalek** [comment]
Do NOT use screenshots with text information. It is ridiculous and blocks searching for similar issues.

`writeOpticalFlow` is not a part of main OpenCV API (3.x+). It is moved to opencv_contrib.
Refer to [documentation](https://docs.opencv.org/3.4.10/d2/d84/group__optflow.html#ga3675efe7822ba872243f22d7a033ddc7) for actual usage.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
