### ISSUE TITLE
import cv2 import error on windows despite successful build and installation

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#17829]
- OpenCV = from master branch 7/10/20
- Operating System / Platform => Windows 64 Bit Win10
- Compiler => Visual Studio 2019

##### Detailed description

I successfully built opencv in the latest cmake, and then built in VS. My PC recognizes python but  does not recognize cv2. I am also adding my paths below. I installed both opencv and python in the c:\ drive.

```
**error:**
>>> C:\>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Python37\cv2\__init__.py", line 96, in <module>
bootstrap()
File "C:\Python37\cv2\__init__.py", line 62, in bootstrap
], True)
**File "C:\Python37\cv2\__init__.py", line 56, in load_first_config
raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config-3.7.py', 'config-3.py']. Check OpenCV installation.**
```

My paths:
PYHTONPATH:
C:\Python37\python.exe
C:\Python37\include
C:\Python37\libs
C:\Python37\lib
C:\Python37\site-packages
C:\Python37\Lib\site-packages\numpy\core\include
C:\Python37\Lib\site-packages\cv2\python-3.7
C:\Python37\Lib\site-packages\cv2

I also tried adding these paths to my user environment variables. All my python paths in cmake are also correct. What could be the problem here?

**Comment by deepmm** [comment]
questions never get answered there but I'll try.

**Comment by alalek** [comment]
1. You do not need to install OpenCV to try it (because there is no straightforward way to uninstall it).
2. Try to run `.\setup_vars.cmd python -c 'import cv2 as cv; print(cv.getBuildInformation())'` from build directory.

**Comment by deepmm** [comment]
is that command for windows? I'm confused, sorry.
