### ISSUE TITLE
running my cv2 dnn model with cv2.dnn.DNN_TARGET_MYRIAD on MYRIAD cores

### ISSUE THREAD

**Issue by Omar-AE** [opencv/opencv#17821]
##### System information (version)

- OpenCV => 4.3.0-openvino
- Operating System / Platform => ubuntu 18.04
- Compiler => python 3.6.9

##### Detailed description

I'm having the following error:
```
[INFO] loading YOLO from disk...
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    safe_people_count, close_people_count = AnalysisObj.SDAProcess(img, threshold=0.3, nms_threshold=0.8, crop=args.crop)
  File "/home/nvr/#######/social_distancing_detection.py", line 54, in SDAProcess
    layerOutputs = self.net.forward(self.ln)
cv2.error: OpenCV(4.3.0-openvino) /opt/intel/openvino_2020.3.194/opencv/modules/dnn/src/dnn.cpp:1089: error: (-213:The function/feature is not implemented) Unknown/unsupported target identifier in function 'wrapMat'
```
I'm using cv2.dnn.DNN_TARGET_MYRIAD. The code works using cv2.dnn.DNN_TARGET_CPU but not MYRIAD
Any idea what could be the issue?

**Comment by alalek** [comment]
Why are you [using](https://github.com/opencv/opencv/blob/4.3.0-openvino-2020.3.0/modules/dnn/src/dnn.cpp#L1080-L1090) `DNN_BACKEND_OPENCV` for MYRIAD?
Refer to [documentation](https://docs.opencv.org/4.3.0/db/d30/classcv_1_1dnn_1_1Net.html#a9dddbefbc7f3defbe3eeb5dc3d3483f4).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Omar-AE** [comment]
I'm not using DNN_BACKEND_OPENCV.

Also, I had the previous error as a result of commenting out the following lines:
https://github.com/opencv/opencv/blob/3d50bde46e4756609606a9f76b0ab4246a3f45f1/modules/dnn/src/dnn.cpp#L1404-L1407

I know it is not right to comment them out but I did so because the first time I ran my code, it worked. After that, I suddenly had this error:
```
cv2.error: OpenCV(4.3.0-openvino) /opt/intel/openvino_2020.3.194/opencv/modules/dnn/src/dnn.cpp:1377: error: (-215:Assertion failed) preferableBackend != DNN_BACKEND_OPENCV || preferableTarget == DNN_TARGET_CPU || preferableTarget == DNN_TARGET_OPENCL || preferableTarget == DNN_TARGET_OPENCL_FP16 in function 'setUpNet'
```
That's why I commented them.

**Comment by alalek** [comment]
Main question is where is `setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE)` in your code.

> That's why I commented them.

Wrong way.

---


Please don't clone comments / issues. Keep your discussion in a single place: #17727

**Comment by SaddamBInSyed** [comment]
@alalek 

the below line saved my time lot,

setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE)

Thank you
