### ISSUE TITLE
How to set cuda device in dnn module?

### ISSUE THREAD

**Issue by zccyman** [opencv/opencv#17852]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => CentOS7
- Compiler => GCC6.2

##### Detailed description

```
int gpu_id = 2;
int device_count;

device_count = cv::cuda::getCudaEnabledDeviceCount();
//cudaGetDeviceCount(&device_count);

cv::cuda::setDevice(gpu_id);
//cudaSetDevice(gpu_id);

net = cv::dnn::readNetFromONNX("colorE.onnx");

net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
```

when I set gpu_id is 2, but Memory appear in GPU:0 and GPU:2. I don't know what's wrong with the code.

**Comment by YashasSamaga** [comment]
I am not able to reproduce. I took [this benchmark code](https://gist.github.com/YashasSamaga/48bdb167303e10f4d07b754888ddbdcf) and added `cv::cuda::setDevice()` at the begining of `main()`. I set the device and compile. I did this four times with four different ids (1, 2, 3, 4) and the program did use four different devices.

Your code looks correct. Can you check again?

The memory allocations and inference happen on the device which is associated with the calling thread. The CUDA backend does not manage device explicitly. It expects that the calling thread always has the same device associated with it from construction to destruction of `cv::dnn::Net` object. Invoking `cv::dnn::Net` with different devices ids during its lifetime is undefined behavior.

**Comment by zccyman** [comment]
@YashasSamaga I test again. I found the problem in use 'cv::Mat blob_output = net.forward()', memory appear in GPU0 and GPU2.

````
int gpu_id = 2;
int device_count;

device_count = cv::cuda::getCudaEnabledDeviceCount();
//cudaGetDeviceCount(&device_count);

cv::cuda::setDevice(gpu_id);
//cudaSetDevice(gpu_id);

cv::dnn::Net net = cv::dnn::readNetFromONNX("../test_python_dnn/models/colorE.tfonnx");

net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);

cv::Mat image = cv::imread("../images/lena.png");
cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
cv::resize(image, image, cv::Size(256, 256));
image.convertTo(image, CV_32FC3, 1.0f / 255.0f);

std::vector<cv::Mat> images;
for (size_t b = 0; b < 2; b++)
{
	images.push_back(image);
}
cv::Mat blob_input = cv::dnn::blobFromImages(images);
net.setInput(blob_input);
cv::Mat blob_output = net.forward();
````

**Comment by zccyman** [comment]
@YashasSamaga Maybe something is wrong with the process of tensorflow2onnx. my onnx model file is [here](https://github.com/zccyman/models/dnn).
````
python -m tf2onnx.convert --graphdef dnn/colorE.pb --output dnn/colorE.tfonnx --inputs x:0 --outputs Identity:0 --opset 11 --inputs-as-nchw x:0
````

**Comment by YashasSamaga** [comment]
@zccyman I don't think think the model matters. Can you share your code that reproduces the problem?

And just to confirm, `GPU:1` doesn't show significant amounts of memory, right? CUDA allocates a small amount of memory on all devices.

**Comment by zccyman** [comment]
@YashasSamaga nvidia-smi output:

| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     57844      C   /tmp/236/cmake-build-release/main            105MiB |
|    2     57844      C   /tmp/236/cmake-build-release/main            656MiB

**Comment by zccyman** [comment]
@YashasSamaga cudaSetDevice is success when using ‘cv::dnn::readNetFromTensorflow("../test_python_dnn/models/colorE.pb")’. all memory appeared in GPU:2.
````
int gpu_id = 2;
int device_count;

device_count = cv::cuda::getCudaEnabledDeviceCount();
//cudaGetDeviceCount(&device_count);

cv::cuda::setDevice(gpu_id);
//cudaSetDevice(gpu_id);

cv::dnn::Net net = cv::dnn::readNetFromTensorflow("../test_python_dnn/models/colorE.pb");

net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);

cv::Mat image = cv::imread("../images/lena.png");
cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
cv::resize(image, image, cv::Size(256, 256));
image.convertTo(image, CV_32FC3, 1.0f / 255.0f);

std::vector<cv::Mat> images;
for (size_t b = 0; b < 2; b++)
{
	images.push_back(image);
}
cv::Mat blob_input = cv::dnn::blobFromImages(images);
net.setInput(blob_input);
cv::Mat blob_output = net.forward();
````

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    2     91206      C   /tmp/236/cmake-build-release/main            656MiB |
+-----------------------------------------------------------------------------+

**Comment by YashasSamaga** [comment]
I am not able to reproduce the problem in OpenCV 4.4.0 with your ONNX model code. It's consuming memory in just one GPU.

<details>
<summary>Code importing ONNX mdoel</summary>

```
#include <iostream>

#include <opencv2/core/cuda.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

int main ()
{
    int gpu_id = 2;
    int device_count;

    device_count = cv::cuda::getCudaEnabledDeviceCount();
    //cudaGetDeviceCount(&device_count);

    cv::cuda::setDevice(gpu_id);
    //cudaSetDevice(gpu_id);

    cv::dnn::Net net = cv::dnn::readNetFromONNX("colorE.tfonnx");

    net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);

    cv::Mat image = cv::imread("data/images/img_0.jpg");
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    cv::resize(image, image, cv::Size(256, 256));
    image.convertTo(image, CV_32FC3, 1.0f / 255.0f);

    std::vector<cv::Mat> images;
    for (size_t b = 0; b < 2; b++)
    {
        images.push_back(image);
    }
    cv::Mat blob_input = cv::dnn::blobFromImages(images);
    net.setInput(blob_input);
    cv::Mat blob_output = net.forward();

    return 0;
}
```
</details>

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    2     22716      C   ./a.out                                      671MiB |
+-----------------------------------------------------------------------------+
```

There is also 11MB of memory allocated on all devices but this is done by CUDA runtime/driver.

I am not able to reproduce in OpenCV 4.3 as well.

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    2     23443      C   ./a.out                                      718MiB |
+-----------------------------------------------------------------------------+
```

**Comment by zccyman** [comment]
@YashasSamaga 
test code:
````
int main()
{
    int gpu_id = 2;
    int device_count;

    device_count = cv::cuda::getCudaEnabledDeviceCount();
//cudaGetDeviceCount(&device_count);

    cv::cuda::setDevice(gpu_id);
//cudaSetDevice(gpu_id);

    cv::dnn::Net net = cv::dnn::readNetFromONNX("../test_python_dnn/models/colorE.tfonnx");

    net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);

    cv::Mat image = cv::imread("../images/lena.png");
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    cv::resize(image, image, cv::Size(256, 256));
    image.convertTo(image, CV_32FC3, 1.0f / 255.0f);

    for (size_t iter = 0; iter < 10000; iter++)
    {
        std::vector <cv::Mat> images;
        images.clear();
        for (size_t b = 0; b < 2; b++)
        {
            images.push_back(image);
        }
        cv::Mat blob_input = cv::dnn::blobFromImages(images);
        net.setInput(blob_input);
        cv::Mat blob_output = net.forward();
    }

    return 0;
}
````

consuming memory:
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     91513      C   .../inferenceDemo/cmake-build-release/main   105MiB |
|    2     91513      C   .../inferenceDemo/cmake-build-release/main   609MiB |
+-----------------------------------------------------------------------------+

runtime environments:
````
- opencv 4.4.0
- CUDA 10.2
- CUDNN 8.0
````

**Comment by hedgehog91** [comment]
@YashasSamaga I tried to debug this. 
I downloaded the model from here https://download.01.org/opencv/public_models/012020/resnet-50-tf/resnet_v1-50.pb 
Memory on gpu:0 is allocated after executing the copy function in the Permute Layer 
https://github.com/opencv/opencv/blob/4.4.0/modules/dnn/src/layers/permute_layer.cpp#L198

Could you take a look at this?

**Comment by YashasSamaga** [comment]
> @YashasSamaga I tried to debug this.
> I downloaded the model from here https://download.01.org/opencv/public_models/012020/resnet-50-tf/resnet_v1-50.pb
> Memory on gpu:0 is allocated after executing the copy function in the Permute Layer
> https://github.com/opencv/opencv/blob/4.4.0/modules/dnn/src/layers/permute_layer.cpp#L198
> 
> Could you take a look at this?

A lot of observations make sense now. I presumably wasn't able to reproduce because I did not build my OpenCV with OpenCL. Unexpected memory appears on GPU 0 only because you had set the CUDA device but not the OpenCL device. So by default OpenCL will allocate memory on GPU 0 while the CUDA allocations use the device you choose.

I think that OpenCL code you pointed should not execute if the target is not OpenCL. I'll look into this tomorrow.

**Comment by YashasSamaga** [comment]
@hedgehog91 will you make a PR?

**Comment by hedgehog91** [comment]
@YashasSamaga
I don't quite understand how to fix it.

**Comment by hedgehog91** [comment]
@YashasSamaga
I tried compiling with the WITH_OPENСL = OFF flag. You're right. This is a workaround for me.
