### ISSUE TITLE
Handling corrupt images

### ISSUE THREAD

**Issue by saketsneha** [opencv/opencv#17862]
I am using  `val sourceImageMat = imread(sourceImage.toString())` to read a file in java. But for corrputed images it just prints `Premature end of JPEG file` . I can see its not an exception and that is why its not ignoring the image but processing it further. Is there a way to avoid this processing?
Have had a look at the community channel but ws not of much help.Hope you can throw some ideas around this?

**Comment by raaldrid** [comment]
@saketsneha, @alalek.  I looked into this.  For unreadable (by libjpeg) corrupted images reading the image code does exit as soon as an error is found, whether that be in readHeader or readData.  I (seriously) corrupted 2 jpg images and tested both scenarios.
  
What specific kind of corruption is being referred to in this bug?  Can you offer a sample file?  If it's a recoverable kind of corruption perhaps this is intended behavoir, to continue processing.

**Comment by dkurt** [comment]
Let's close for now. Here an example of broken jpeg images which do not have `\xff\xd9` at the end of binary data: https://github.com/opencv/opencv/issues/22729#issuecomment-1543620959
