### ISSUE TITLE
Import cv2 raises error, file in boostrap and DLL load failed

### ISSUE THREAD

**Issue by deepkak** [opencv/opencv#17860]
- OpenCV = latest
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Python 3.7.7

**Detailed description**

Please help, I had no luck on the opencv forum. I was able to succesfully install opencv with CUDA 10.2, but for the framework I am running it with, I needed CUDA 10.0. I am experiencing errors when importing cv2.

**Steps to reproduce**

I built opencv with cmake, and experienced no errors but "CMake Warning at cmake/OpenCVGenSetupVars.cmake:54 (message):" in which I unchecked it and the error resolved. After successfully building in VS,  these are the commands and errors that followed:
```
C:\>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "C:\Python37\cv2\__init__.py", line 86, in bootstrap
    import cv2
ImportError: DLL load failed: The specified module could not be found.
>>>

```
How can I resolve these or any idea what causes this? I made sure the correct path was in my path in systems variable (C:\opencv\build\install\x64\vc15\bin).

**Comment by alalek** [comment]
> C:\Python37\cv2

OpenCV files don't look properly installed into Python.
Uninstall them from here.

---

Perform investigation steps from this comment: https://github.com/opencv/opencv/issues/17632#issuecomment-648098711

---

> The specified module could not be found.

Usually this means missing `PATH` entries. Use `depends` tool to investigate the problem: https://en.wikipedia.org/wiki/Dependency_Walker

**Comment by deepkak** [comment]
thank you

**Comment by johnny-wang16** [comment]
Hi there, i solved the issue by  pip install opencv-contrib-python==4.1.0.25 inspired from https://cv-tricks.com/how-to/installation-of-opencv-4-1-0-in-windows-10-from-source/

**Comment by issaiass** [comment]
OK, i think i have a workaround...
///// Normal Steps
1 - Build opencv python bindings as usual, this will create the cv2 folder on "c:\users\<your_user>\anaconda3\lib\site-packages"
2 - Ensure that after building you have the folder and the file (if you are in python 3.8)
![image](https://user-images.githubusercontent.com/4116031/91622052-0a295c80-e95b-11ea-83ef-c71163c904df.png)
3 - Now if you open a terminal and import cv2 you got
![image](https://user-images.githubusercontent.com/4116031/91622109-3c3abe80-e95b-11ea-9c1e-8a64999761d0.png)
///// Work around
4 - do... pip install opencv-python
5 - do... pip uninstall opencv-python
![image](https://user-images.githubusercontent.com/4116031/91622216-ace1db00-e95b-11ea-80a5-cd8248edf84c.png)
6 - if you inspect the folder now, you will have different loaders
![image](https://user-images.githubusercontent.com/4116031/91622168-81f78700-e95b-11ea-83bd-552a90a03844.png)
7 - now open a terminal and put "python" and press enter
8 - now put "import cv2" and press enter

Could not resolve the dependency issue but this worked for me.

**Comment by johnny-wang16** [comment]
The above solution doesn't work for me. I read  a lot of posts but still wasnt able to resolve the "DLL load failed"

**Comment by issaiass** [comment]
Did you build opencv python bindings again?

**Comment by johnny-wang16** [comment]
when is this step happening? after pip uninstall??

**Comment by issaiass** [comment]
> when is this step happening? after pip uninstall??

You need to build the bindings first as it says

**Comment by johnny-wang16** [comment]
oh yeah of course. you are talking up step 1 which is just building it normally

**Comment by issaiass** [comment]
yes


Saludos,

RA

________________________________
De: johnny-wang16 <notifications@github.com>
Enviado: viernes, 4 de septiembre de 2020 12:43 p. m.
Para: opencv/opencv <opencv@noreply.github.com>
Cc: Rangel Isaías Alvarado Walles <issaiass@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [opencv/opencv] Import cv2 raises error, file in boostrap and DLL load failed (#17860)


oh yeah of course. you are talking up step 1 which is just building it normally

**Comment by onkarshendge** [comment]
Any luck finding solution on the above? I am stuck on this too.

**Comment by johnny-wang16** [comment]
I ended up not worrying about python binding with opencv. All i need is the c++ version of opencv. I checked the build information from visual studio with c++ and its working correctly .

**Comment by onkarshendge** [comment]
I was able to solve this by renaming the cv2.cp38-win_amd64.pyd file to cv2.pyd in ..\venv\Lib\site-packages\cv2 folder.

**Comment by johnny-wang16** [comment]
interesting. I think ive tried that before but didnt work.

**Comment by WeijieH** [comment]
I had the same problem and the reason I found is that I installed the debug version of cv2 (when i do build in vs 2019, i selected batch build for debug/release INSTALL and somehow the debug INSTALL runs last). I missing dll I find by running dependency walker is python38_d.dll. I have solved this by run or build the release INSTALL again.

**Comment by cuixing158** [comment]
It may be a bug in anaconda,  [bug](https://stackoverflow.com/questions/43184887/dll-load-failed-error-when-importing-cv2)

**Comment by Sebasu** [comment]
I had the same problem
I solved it by applying only the work around step 4: pip install opencv-python
apparently in the cv2 folder, it adds opencv_videoio_ffmpeg451_64.dll and a file named version.py, also the __init__.py file has been changed
the error is gone and my openCV python code is running ok

**Comment by zePanzerfaust** [comment]
Had the same (also #19335 without using CPack), but there was no need to install other packages to fix it, just modify `<python_dir>\Lib\site-packages\cv2\__init__.py`.
Because I compiled OpenCV with some other modules it probably linked against them.
In `<python_dir>\Lib\site-packages\cv2\__init__.py` add `os.add_dll_directory` calls as mentioned in responses https://github.com/opencv/opencv/issues/17632#issuecomment-648098711 and https://github.com/opencv/opencv/issues/17632#issuecomment-745976722.
In my case I used WinPython. After adding all these directories I could use `import cv2` and its functions, but no autocompletion.
```
...
def bootstrap():
    import sys
    import os
    os.add_dll_directory(r'C:\libs\opencv-4.5.1\_install\x64\vc16\bin')
    os.add_dll_directory(r'C:\libs\oneTBB-2020_U3\build\vs2013\x64\Release')
    os.add_dll_directory(r'C:\libs\Qt\5.15.2\msvc2019_64\bin')
    os.add_dll_directory(r'C:\libs\ffmpeg-n4.3.2-162-g4bbcaf7559-win64-gpl-shared-4.3\bin')
    os.add_dll_directory(r'C:\libs\gstreamer\1.0\msvc_x86_64\bin')
    os.add_dll_directory(r'C:\libs\gstreamer-runtime\1.0\msvc_x86_64\bin')
    os.add_dll_directory(r'C:\libs\VTK-9.0.1\_install\bin')
    os.add_dll_directory(r'C:\libs\cudnn-11.2-windows-x64-v8.1.1.33\cuda\bin')
    os.add_dll_directory(r'C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64')
    os.add_dll_directory(r'C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64\DLLs')
    os.add_dll_directory(r'C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64\Lib\site-packages\cv2\python-3.9')
    os.add_dll_directory(r'C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64\Lib\site-packages\numpy\DLLs')
...
```
I guess it's fine if you just want to use your custom built OpenCV.

Adding them to `<python_dir>\Lib\site-packages\cv2\config.py` does not seem to help, as they just get added to `PATH`, which doesn't work either. (maybe I didn't try long enough)

https://docs.python.org/3/library/os.html#os.add_dll_directory

**Comment by zePanzerfaust** [comment]
To get autocompletion (atleast in PyCharm) you need to create a symbolic link. (see https://github.com/microsoft/python-language-server/issues/1926#issuecomment-813269276
Execute the following command with administrator priviledges (change the name of the *.pyd file in both locations)
`mklink "<python_dir>\Lib\site-packages\cv2.cp39-win_amd64.pyd" "<python_dir>\Lib\site-packages\cv2\python-3.9\cv2.cp39-win_amd64.pyd"`

In the example above this would become
`mklink "C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64\Lib\site-packages\cv2.cp39-win_amd64.pyd" "C:\tools\WinPython\WPy64-3920\python-3.9.2.amd64\Lib\site-packages\cv2\python-3.9\cv2.cp39-win_amd64.pyd"`
