### ISSUE TITLE
G-API: broken compilation of samples (winpack, MSVS 2017)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#17869]
[Nightly MSVS2017 build is broken](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc15/builds/419).

[Winpack configuration](http://pullrequest.opencv.org/buildbot/builders/master_winpack-test-win64-vc15/builds/872) (samples against prebuilt binaries)

- MSVS 2017 has problem: 19.16.27035.0 (15.9.20), 19.16.27042.0 (15.9.25 - **latest**)
- MSVS 2015 is clean
- MSVS 2019 is clean (manual test). It has similar [bug report against compiler](https://developercommunity.visualstudio.com/content/problem/558844/error-c3546-there-are-no-parameter-packs-available.html).

relates #17502
/cc @dmatveev 

Error message:
```
C:\build\master_winpack-test-win64-vc15\build\distrib\opencv\build\include\opencv2/gapi/infer.hpp(111): error C3546: '...': there are no parameter packs available to expand [C:\build\master_winpack-test-win64-vc15\build\samples_build\cpp\example_tutorial_age_gender_emotion_recognition.vcxproj]
  C:\build\master_winpack-test-win64-vc15\build\distrib\opencv\sources\samples\cpp\tutorial_code\gapi\age_gender_emotion_recognition\age_gender_emotion_recognition.cpp(79): note: see reference to class template instantiation 'cv::GNetworkType<custom::Faces,std::function<cv::GMat (cv::GMat)>>' being compiled
C:\build\master_winpack-test-win64-vc15\build\distrib\opencv\build\include\opencv2/gapi/infer.hpp(87): error C3546: '...': there are no parameter packs available to expand [C:\build\master_winpack-test-win64-vc15\build\samples_build\cpp\example_tutorial_age_gender_emotion_recognition.vcxproj]
  C:\build\master_winpack-test-win64-vc15\build\distrib\opencv\sources\samples\cpp\tutorial_code\gapi\age_gender_emotion_recognition\age_gender_emotion_recognition.cpp(85): note: see reference to class template instantiation 'cv::GNetworkType<custom::AgeGender,std::function<custom::AGInfo (cv::GMat)>>' being compiled
```

**Comment by alalek** [comment]
@dmatveev This is blocker for 4.4.0 release.
If there is no fix or upgrading compiler don't help then I will revert mentioned PR (deadline 15:00 UTC - 4 hours from now).

**Comment by alalek** [comment]
Compiler upgrade doesn't help.
MSVS 2017 15.9.25 (19.16.27042.0) has similar problem. Workaround is required.

**Comment by dmatveev** [comment]
Please contact me directly for latency < day, I do rarely check the GH notifications

**Comment by dmatveev** [comment]
@alalek tryin to fix now, gimme 10min
