### ISSUE TITLE
CUDA ARCH ERROR

### ISSUE THREAD

**Issue by toplinuxsir** [opencv/opencv#17883]
##### System information (version)

- OpenCV => 4.4
- Operating System / Platform => ubuntu 20.04
- Compiler => 8.4

When I use python opencv , dnn to detect , the error:
```
 error: (-216:No CUDA support) OpenCV was not built to work with the selected device. Please check CUDA_ARCH_PTX or CUDA_ARCH_BIN in your build configuration. in function 'initCUDABackend'
```
GPU : Titan RTX
Cmake options
 ```
cmake \
       -D CMAKE_INSTALL_PREFIX=/usr/local \
	-D CMAKE_C_COMPILER="/usr/bin/cc" \
	-D CMAKE_CXX_COMPILER="/usr/bin/c++" \
	-D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
	-D WITH_CUDA=ON -D WITH_CUDNN=ON \
	-D CUDA_GENERATION=Auto \
	-D CUDA_ARCH_BIN=7.5 \
	-D CUDNN_INCLUDE_DIR=/usr/local/cudnn/include \
	-D CUDNN_LIBRARY=/usr/local/cudnn/lib64/libcudnn.so \
	-D CUDA_NVCC_FLAGS="-D_FORCE_INLINES" \
	-D CMAKE_BUILD_TYPE=RELEASE \
	-D BUILD_LIST=core,improc,videoio,dnn,python3,cudev,dnn_objdetect,highgui,video \
	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
	-D WITH_TBB=ON \
	-D ENABLE_PRECOMPILED_HEADERS=OFF \
	-D BUILD_PERF_TESTS=OFF \
	-D CV_TRACE=OFF \
	-D OPENCV_GENERATE_PKGCONFIG=ON \
	-D WITH_OPENEXR=OFF \
	-D ENABLE_CXX11=1 \
	..
```
But I compiled opencv with Cmake option -D CUDA_ARCH_BIN=7.5 successfully

**Comment by tomoaki0705** [comment]
I'm really curious about the output of CMake.
You should have something similar to 

```
--   NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS)
--     NVIDIA GPU arch:             72
--     NVIDIA PTX archs:
-- 
```

And, CUDA/CUDNN version ?

**Comment by toplinuxsir** [comment]
@tomoaki0705 

--   NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS)
--     NVIDIA GPU arch:             75
--     NVIDIA PTX archs:
--
--   cuDNN:                         YES (ver 7.6.5)

**Comment by tomoaki0705** [comment]
Does `deviceQuery` sample app from CUDA sample works on your platform ?
Sorry, can't really help.

**Comment by YashasSamaga** [comment]
This new error message was added in https://github.com/opencv/opencv/pull/17788.

> But I compiled opencv with Cmake option -D CUDA_ARCH_BIN=7.5 successfully

7.5 should be there in `CUDA_ARCH_BIN` by default.

> 
> NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS)     
> NVIDIA GPU arch:             75
> NVIDIA PTX archs:
>   cuDNN:                         YES (ver 7.6.5)
> 

Is this what you got in the attempt which gives that error or the one that worked?

**Comment by YashasSamaga** [comment]
@toplinuxsir Have you solved the problem?
