### ISSUE TITLE
Unspecified error (Number of input channels should be multiple of 3 but got 50) in cv::dnn::ConvolutionLayerImpl::getMemoryShapes

### ISSUE THREAD

**Issue by bekor** [opencv/opencv#17917]
##### System information (version)
- OpenCV => 4.4.0-pre
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

We trained a keras model with tensorflow 2.0.0 for colored image classification and we converted it with tf2onnx.convert into an onnx. 
Our test using onnxruntime and with that the onnx model is loading and working.
But we want to use it in our main project which is written in C++ and we can load and run other onnx models, but we have problem running this one. We got the following error: 

```
OpenCV(4.4.0-pre) Error: Unspecified error (Number of input channels should be multiple of 3 but got 50) in cv::dnn::ConvolutionLayerImpl::getMemoryShapes, file D:\opencv-master\modules\dnn\src\layers\convolution_layer.cpp, line 347
[ERROR:0] global D:\opencv-master\modules\dnn\src\dnn.cpp (3434) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Convolution]:(StatefulPartitionedCall/sequential/conv2d/BiasAdd:0): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=2
[ERROR:0] global D:\opencv-master\modules\dnn\src\dnn.cpp (3437) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 50 3 50 ]
[ERROR:0] global D:\opencv-master\modules\dnn\src\dnn.cpp (3445) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively     blobs[0] = CV_32FC1 [ 16 3 5 5 ]
[ERROR:0] global D:\opencv-master\modules\dnn\src\dnn.cpp (3445) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively     blobs[1] = CV_32FC1 [ 16 1 ]
[ERROR:0] global D:\opencv-master\modules\dnn\src\dnn.cpp (3447) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.4.0-pre) D:\opencv-master\modules\dnn\src\layers\convolution_layer.cpp:347: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 50 in function 'cv::dnn::ConvolutionLayerImpl::getMemoryShapes'

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.4.0-pre) Error: Unspecified error (Number of input channels should be multiple of 3 but got 50) in cv::dnn::ConvolutionLayerImpl::getMemoryShapes, file D:\opencv-master\modules\dnn\src\layers\convolution_layer.cpp, line 347
```
We deduced that, it's only happening when we try to load model with a Conv2D with `input_shape=(height,width,3)`. 
If we train the model with a Conv2D with `input_shape=(height,width,1)` it loading and running.
So it is not working when we use colored images and not gray scale. 

##### Steps to reproduce
Here is the model and the code
 [model](https://drive.google.com/file/d/1nLOQqS7IhmRM20g4rzM-fzi7G5JABVHZ/view?usp=sharing)

    ```.cpp
    auto image = cv::imread('test.jpg');
    auto net = cv::dnn::readNetFromONNX('model.onnx');
    auto blob = cv::dnn::blobFromImage(image, 1.0 / 255, cv::Size(50, 50), cv::Scalar(127, 127, 127), true);
    net.setInput(blob);
    std::vector<float> detection = net.forward();
    ```
 we get the error on the forward

**Comment by dkurt** [comment]
Can you print network input shape?
```
std::cout << blob.size << std::endl;
net.setInput(blob);

```

**Comment by bekor** [comment]
The shape is: `1 x 3 x 50 x 50`

> Why direct TensorFlow model is not used?`
We can't freeze our model, to create a pbtxt file next to our pb files.
Also onnx is interoperable and portable.

**Comment by dkurt** [comment]
Ok, I see. Actually, it's OK to just freeze the model - `pbtxt` is optional (see https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs). So, let's try to fix ONNX model anyway.

**Comment by dkurt** [comment]
@bekor, It seems to me that this is a problem inside `tf2onnx.convert`. According to [Netron](https://github.com/lutzroeder/netron) visualization there is redundant transposition which require NHWC input:

![image](https://user-images.githubusercontent.com/25801568/88256614-7366e180-ccc4-11ea-92c7-c3fdc2944ea1.png)

```python
import numpy as np
import cv2 as cv

net = cv.dnn.readNet('model.onnx')
inp = np.random.standard_normal([1, 50, 50, 3])
net.setInput(inp)
out = net.forward()
print(out.shape)  # (1, 9)
```

So you may try to eliminate this Transpose or pass NHWC

**Comment by bekor** [comment]
Hi, I tried to eliminate the Transpose during model conversion, but I can't.
I tried specifying the order of the input for the tf2onnx converter but, they are not supporting NCHW.

I also tried to use the keras2onnx, but the model init (`cv::dnn::readNetFromONNX('model.onnx')`) fails with this error :
```
Error: Requested object was not found (Blob dense_2/Identity:0 not found in const blobs) in 
cv::dnn::dnn4_v20200609::ONNXImporter::getBlob, file D:\opencv-master\modules\dnn\src\onnx\onnx_importer.cpp, 
line 262
```

I used this for creating the onnx:
```.py
onnx_model = keras2onnx.convert_keras(model, model.name, debug_mode=True, target_opset=8)
onnx.save_model(onnx_model, onnx_model_name)
```

Also went a few round with loading the saved_model.pb with:
`net = cv::dnn::readNetFromTensorflow('saved_model.pb);`
but I got this error:
```
[libprotobuf ERROR D:\opencv-master\3rdparty\protobuf\src\google\protobuf\wire_format_lite.cc:629] String field
 'opencv_tensorflow.FunctionDef.Node.ret' contains invalid UTF-8 data when parsing a protocol buffer. 
Use the 'bytes' type if you intend to send raw bytes.
OpenCV(4.4.0-pre) Error: Unspecified error (FAILED: ReadProtoFromBinaryFile(param_file, param). 
Failed to parse GraphDef file: E:/git/work/hydrant/src/HydraNT/../../res/categorization/uae/saved_model.pb) 
in cv::dnn::ReadTFNetParamsFromBinaryFileOrDie, file D:\opencv-master\modules\dnn\src\tensorflow\tf_io.cpp, 
line 42
```
and tried the freeze_graph on the saved_model.pb but I can't the tensorflow's freeze_graph.py script fails at a point.

Soo I switch to reordering the cv::Mat. Can you give me a hint to how to do it in C++ ? 
I tried this: 
```.cpp
  cv::Mat transformed = blob.reshape(1, cv::dnn::MatShape({1, 50, 50, 3}));
  std::cout << transofmred.size << std::endl; // is really 1, 50, 50, 3
```
And the network is running, with this but the output of the network is far from the test output. 
I run the model on the same image in cpp and in python but the output it totally different.

**Comment by dkurt** [comment]
@bekor, please try something like
```cpp
cv::Mat blob;
cv::resize(image, blob, Size(50, 50));
blob.convertTo(blob, CV_32F, 1.0/255, -127.5);
blob = blob.reshape(1, {1, 50, 50, 3});
```
so just perform input preprocessing manually (or just take a look at blobFromImage import implementations and copy without transposition process).

**Comment by bekor** [comment]
@dkurt Thanks for your help, this solved it.
You can close the issue.
