### ISSUE TITLE
error when Compiling opencv4.4

### ISSUE THREAD

**Issue by niuwenju** [opencv/opencv#17915]
##### System information (version)
- OpenCV => 4.4
- OpenCV-contrib => 4.4
- Operating System / Platform => Ubuntu18.04 64 Bit
- Compiler => make

i have successfully get the makefile by 
`cmake -D CMAKE_BUILD_TYPE=Release     -D CMAKE_INSTALL_PREFIX=/usr/local     -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules     -D OPENCV_GENERATE_PKGCONFIG=YES     -D WITH_1394=OFF ..`

but when compile it by
make -j8
i got error as follows
```
[ 76%] Linking CXX shared library ../../lib/libopencv_ximgproc.so
[ 76%] Built target opencv_ximgproc
[ 76%] Linking CXX executable ../../bin/opencv_test_calib3d
[ 76%] Built target opencv_test_calib3d
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mshabunin** [comment]
`make: *** [all] Error 2` is not a real error message, check your log for actual error message returned by compiler.
