### ISSUE TITLE
Mac Catalyst - xcframework support

### ISSUE THREAD

**Issue by BrainFeverMedia** [opencv/opencv#17929]
##### System information
OpenCV => 4.4.0
Operating System / Platform => macOS Catalina 10.15.5
Compiler => Xcode 11.5 and Xcode 12 beta3

##### Detailed description
I'm trying to build a Mac Catalyst app using OpenCV. Xcode builds a Mac Catalyst app using the iOS SDK for architecture x86. A Catalyst app looks like an iPad app running on a Mac.
Catalyst requires frameworks to be an xcframework. Apple presented XCFramework as a new binary format of packing libraries.

##### Steps to reproduce

Here is the commands to create an xcframework, as created by @chrisballinger  in https://github.com/opencv/opencv/issues/17291

```Shell
d path/to/opencv
python2 platforms/ios/build_framework.py --iphonesimulator_archs x86_64 --iphoneos_archs arm64 .

mkdir -p build/xcframework
cp build/build-arm64-iphoneos/lib/Release/libopencv_merged.a build/xcframework/libopencv-arm64-iphoneos.a
cp build/build-x86_64-iphonesimulator/lib/Release/libopencv_merged.a build/xcframework/libopencv-x86_64-iphonesimulator.a

# Set project level "Base SDK" to "iOS".
open build/build-x86_64-iphonesimulator/OpenCV.xcodeproj

xcodebuild build -configuration Release -project build/build-x86_64-iphonesimulator/OpenCV.xcodeproj -scheme "ALL_BUILD" -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' -UseModernBuildSystem=YES SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES TARGETED_DEVICE_FAMILY="1,2" SDKROOT=iphoneos SUPPORTS_MAC_CATALYST=YES

libtool -static -o build/xcframework/libopencv-x86_64-maccatalyst.a build/build-x86_64-iphonesimulator/lib/Release/*.a build/build-x86_64-iphonesimulator/3rdparty/lib/Release/*.a

xcodebuild -create-xcframework -library build/xcframework/libopencv-arm64-iphoneos.a -headers build/build-arm64-iphoneos/install/include/opencv2 -library build/xcframework/libopencv-x86_64-iphonesimulator.a -headers build/build-x86_64-iphonesimulator/install/include/opencv2 -library build/xcframework/libopencv-x86_64-maccatalyst.a -headers build/build-x86_64-iphonesimulator/install/include/opencv2 -output build/xcframework/opencv2.xcframework

```

The last step fails with this errror:
```diff
-error: binaries with multiple platforms are not supported 'build/xcframework/libopencv-x86_64-maccatalyst.a'
```

I was able to create an xcframework manually by doing the following:
1 - Create and xcframework with libopencv-arm64-iphoneos.a and libopencv-x86_64-iphonesimulator.a
2 - opencv2.xcframework is created, which is a folder
3 - Manually add libopencv-x86_64-maccatalyst.a to folder, copy Headers folder, and update plist file in folder.

When adding this to an xcode project, xcode gives this build error:
```diff
-Both ios-arm64 and os-x86_64-maccatalyst represent two equivalent library definitions.
```

I tried both Xcode 11.5 and 12 beta3 with same errors.

**Comment by chrisballinger** [comment]
My guess is that the recent changes in the Swift/Obj-C wrapper PR https://github.com/opencv/opencv/pull/17165 may have made the prior steps no longer functional.

If you do `lipo -i libopencv-x86_64-maccatalyst.a` do you see an arm64 slice instead of x86_64?

**Comment by BrainFeverMedia** [comment]
@chrisballinger Non-fat file: libopencv-x86_64-maccatalyst.a is architecture: x86_64

I'm not sure if building for catalyst is going to produce Mac arm64 binaries. That's going to be a different target "My Mac (Designed for iPad)". Build once for arm64 for iOS and arm Macs.
This could change of course. A lot of moving targets.

**Comment by mshabunin** [comment]
There is `--legacy_build` option in `build_framework.py` script, please try it.

**Comment by BrainFeverMedia** [comment]
@mshabunin I tried --legacy_build and got the same error on the last -create-xcframework step:
```diff
-error: binaries with multiple platforms are not supported '/Users/jamesgrote/Downloads/opencv/build/xcframework/libopencv-x86_64-maccatalyst.a'
```

**Comment by TomJinW** [comment]
remove build/build-x86_64-iphonesimulator/lib/Release/libopencv_merged.a before "libtool -static -o" because that file contains binary for iOS Simulators. and change the header for the final step with "-headers build/{ARCHS}/install/include/"

after that you get the correct xcframework using C++ but swift and OBJC APIs are not available because some header issues.

**Comment by BrainFeverMedia** [comment]
@TomJinW I tried this and get the following link error:
```diff
-Both ios-arm64 and os-x86_64-maccatalyst represent two equivalent library definitions.
```
Excluding the simulator lib didn't make a difference.

**Comment by odaken** [comment]
I confirmed the same issue.

**Comment by chrisballinger** [comment]
Just wanted to say that @colejd are I currently working on a proper fix for Catalyst and xcframeworks here: https://github.com/Rightpoint/opencv/tree/feature/colejd/build-catalyst-xcframework

There's still a number of issues to fix, but we are making progress.

**Comment by chrisballinger** [comment]
We just put up a PR #18826 that resolves this issue, come check it out!
