### ISSUE TITLE
opencv 4.4.0 compile error

### ISSUE THREAD

**Issue by dongliya** [opencv/opencv#17923]
OpenCV => 4.4.0
 Operating System / Platform => Ubuntu 18.04
 Compiler => cuda 10.2

 error: identifier "createTextureObjectPitch2D" is undefined
1 error detected in the compilation of "/tmp/tmpxft_0000486a_00000000-6_canny.cpp1.ii".
CMake Error at cuda_compile_1_generated_canny.cu.o.RELEASE.cmake:281 (message):
  Error generating file
  /home/boon/Source/opencv/opencv-4.4.0-openvino/build/modules/cudaimgproc/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_canny.cu.o

**Comment by zuluoaaa** [comment]
I have some problem , how do you solve that ? thantk you very much

**Comment by hsuanguo** [comment]
sam problem here..anyone knows a solution?
