### ISSUE TITLE
errors occurred when cmake opencv4.4 with gpu

### ISSUE THREAD

**Issue by ayicherry** [opencv/opencv#17924]
- OpenCV = 4.4
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

Use cmake3.15，opencv4.4 with CUDA，VS 2017.
when Configure, 
CMake Error at cmake/OpenCVModule.cmake:354 (message):
  Duplicated modules LOCATIONS has been found
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:371 (_assert_uniqueness)
  modules/CMakeLists.txt:7 (ocv_glob_modules)
I have set OPENCV_EXTRA_MODULES_PATH to opencv/sources/modules
I can't fix it.

**Comment by mshabunin** [comment]
Please provide detailed information about your opencv and opencv_contrib version, command lines and output.
