### ISSUE TITLE
opencv make error in jetson tx2 ubuntu16.04

### ISSUE THREAD

**Issue by AlexHAHA** [opencv/opencv#17926]
[  7%] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/common.cpp.o
In file included from /usr/local/include/ceres/jet.h:167:0,
                 from /usr/local/include/ceres/internal/autodiff.h:145,
                 from /usr/local/include/ceres/autodiff_cost_function.h:132,
                 from /usr/local/include/ceres/ceres.h:37,
                 from /home/dji/Downloads/opencv_contrib-3.4.10/modules/sfm/src/libmv_light/libmv/multiview/fundamental.cc:24:
/usr/local/include/ceres/internal/port.h:70:12: error: ‘std::shared_ptr’ has not been declared
 using std::shared_ptr;
            ^
In file included from /usr/local/include/ceres/ceres.h:55:0,
                 from /home/dji/Downloads/opencv_contrib-3.4.10/modules/sfm/src/libmv_light/libmv/multiview/fundamental.cc:24:
/usr/local/include/ceres/solver.h:503:5: error: ‘shared_ptr’ does not name a type
     shared_ptr<ParameterBlockOrdering> linear_solver_ordering;
     ^
/usr/local/include/ceres/solver.h:634:5: error: ‘shared_ptr’ does not name a type
     shared_ptr<ParameterBlockOrdering> inner_iteration_ordering;

**Comment by mshabunin** [comment]
Please add more information: command line, cmake output
