### ISSUE TITLE
Error when using cv::fisheye::stereoCalibrate()

### ISSUE THREAD

**Issue by ns15417** [opencv/opencv#17937]
- OpenCV => 3.3
- Operating System / Platform => UBUNTU
- Compiler => gdb
Did anyone successfully used this function to calibrate stereo fishseye? 
i am confused by the data type of object point and image point.
First, I set it as vector<vector<cv::Point3f>> but what i got is only an error:
`Assertion failed (!objectPoints.empty() && objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3))) in projectPoints, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/calib3d/src/fisheye.cpp, line 1168
`
i saw people have the save problem in python but solved by reshape object point;
and then I reshape it in c++, and change the data type vector<cv::Point3f> , so before it is 25*48*3, and now it is 1200*3;
but it gave me another error: 
`Assertion failed (i < 0) in getMat_, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp,`

I am so sorry i post it here cuz OPENCV Q&A is not able to be logged in. and i just didnt find any useful suggestions about this fuction, so i am just curious that have anyone really tested this function?

**Comment by ns15417** [comment]
ps: I successfully calibrate these two single fisheye cameras using function  fisheye::calibrate() with the same parameters object_points and image_points in type vector<vector<cv::Point3f>> and vector<vector<cv::Point2f>>, but only stuck in the stereo calibration part

**Comment by mshabunin** [comment]
Please try the latest version 3.4.11 or 4.4.0 and provide a minimal application reproducing the issue.

**Comment by ns15417** [comment]
@mshabunin Hi, thanks for your answer, i change my opencv version to 4.0 and solved this problem.
