### ISSUE TITLE
tiny Yolov3 slower than before

### ISSUE THREAD

**Issue by rafcy** [opencv/opencv#17935]
System : Nvidia Jetson Nano
OPENCV : 4.4 build from source

I test my code for object detection using tiny yolov3 and tiny yolov4 (trained on my own custom dataset). Currently, using cuda, Tiny yolov3 has an fps of ~6.5 and tiny yolov4 has an fps of ~15. The problem is that when i was using opencv build 4.2 version using the exact same code and cfg/weights on the exact same device the tiny yolov3 model had an fps of ~15 as well.  Btw, when trying to use DNN_TARGET_CUDA_FP16 the detection gets 6 times slower on both models.
I really don't understand why the yolov3 model got slower on this build, did i do something wrong during the build or do i have to change my code?

EXAMPLE OF MY CODE (in CPP): 

> 

	// Load the network
	Net net = readNetFromDarknet(modelConfiguration, modelWeights);
	net.setPreferableBackend(DNN_BACKEND_CUDA);
	net.setPreferableTarget(DNN_TARGET_CUDA);
	wait(1):{
		cap >> frame;
	//Sets the input to the network
	Mat blob;
	blobFromImage(img, blob, 1/255.0, cvSize(inpWidth, inpHeight), Scalar(0,0,0), true, false);
	net.setInput(blob);

	// Runs the forward pass to get output of the output layers
	vector<Mat> outs;
	net.forward(outs, getOutputsNames(net));

	// Remove the bounding boxes with low confidence
	//std::cout << "OutsSize: " << outs.size() << std::endl;
	postprocess(img, outs);
		imshow("test", img);
	}

Thank you in advance.

**Comment by YashasSamaga** [comment]
Are you using cuDNN 8 that comes with Jetpack 4.4? There is a performance regression with cuDNN 8.

**Comment by rafcy** [comment]
> Are you using cuDNN 8 that comes with Jetpack 4.4? There is a performance regression with cuDNN 8. Some people have got 1FPS with cuDNN 8 but 20FPS with cuDNN 7 on Jetson Nano for YOLOv4-Tiny. FPS includes preprocessing, NMS and postprocessing.
> 
> More information here: [AlexeyAB/darknet#6245 (comment)](https://github.com/AlexeyAB/darknet/issues/6245#issuecomment-660110286)
> I can only guess what's in `postprocess` but you might be interested in [this](https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49) to enhance performance. People have reported ~21 FPS and you seem to get just 15FPS. I think using `dnn_DetectionModel` will help.

First of all thank you for answering, i will try to install an earlier version of cuDNN to check out if this is the problem. My fps calculation includes pre/post processing and NMS and yes it is similar to yours. I have also tried the python code you've send me to enhance performance. It is indeed a bit faster but the accuracy  is really bad, it outputs wrong labels sometimes and loses a lot of detections, so i personally wouldn't recommend it for videos with a lot of objects.

**Comment by YashasSamaga** [comment]
>  but the accuracy is really bad, it outputs wrong labels sometimes and loses a lot of detections, so i personally wouldn't recommend it for videos with a lot of objects.

That shouldn't be happening. Did you try updating the nms and confidence threshold?

**Comment by rafcy** [comment]
> > but the accuracy is really bad, it outputs wrong labels sometimes and loses a lot of detections, so i personally wouldn't recommend it for videos with a lot of objects.
> 
> That shouldn't be happening. Did you try updating the nms and confidence threshold in the script to match your settings?

Yes i did and it's really weird since i am using the same weights /  network size / video resolution.

**Comment by rafcy** [comment]
Good news, i have reinstall Jetpack v 4.3 with previous version of CUDNN and now it is working as intended! Thank you for your help!
