### ISSUE TITLE
qr position can be detected, but not decoded

### ISSUE THREAD

**Issue by eakey** [opencv/opencv#17933]
##### System information (version)

- OpenCV => 4.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

[
![1](https://user-images.githubusercontent.com/4612971/88372792-2e78a300-cdc9-11ea-9aff-7f5028678a7f.jpg)
](url)

	cv::Mat matQr = cv::imread("d://1.jpg");
	cv::Mat matQrBox, matQrRectifiedImage;
	cv::QRCodeDetector qrcDecoder = cv::QRCodeDetector::QRCodeDetector();
	qrcDecoder.detect(matQr, matQrBox);

	std::string strQrData = qrcDecoder.decode(matQr, matQrBox, matQrRectifiedImage);

this 1.jpg, qrcode position can be detected, but not decoded

**Comment by eakey** [comment]
![1](https://user-images.githubusercontent.com/4612971/88372871-5536d980-cdc9-11ea-9abb-c4dfcd1462ea.jpg)

**Comment by mshabunin** [comment]
What is the application output? Did you build OpenCV by yourself? Please post output of `cv::getBuildInformation()`.

**Comment by asmorkalov** [comment]
The issue is reproducible with master and `qrcode.cpp` example:
```
./example_cpp_qrcode -i=/home/alexander/tmp/qrcode_detected_not_decoded/test.jpg 
Run QR decoder on image: [400 x 400] (CV_8UC3)
FPS: 57.1989
QR[0] @ [220, 24, 222, 230, 4, 241, 4, 24]: can't decode QR code
```
Output image with bounding box is attached. The detector output is not correct.
![result](https://user-images.githubusercontent.com/2536374/88384273-c750f380-cdb4-11ea-87af-daf9330b6e5c.jpg)

**Comment by WhiteSus** [comment]
In case this gets picked up, I am seeing a similar issue of either failing to detect a QR code completely, or detecting the bounding box but without decoding.

## System information:
- OpenCV => opencv-python 4.4.0.44
- Python => 3.6.9, 64-bit interpreter
- Operating System / Platform => Linux Mint 19.3 Cinnamon 4.4.5

## Python code:
```python
import cv2

def check_qr(image_path, expected_data):
    img = cv2.imread(image_path)
    detector = cv2.QRCodeDetector()
    data, bbox, straight_qrcode = detector.detectAndDecode(img)
    if data != expected_data:
        print(f'Failed: decoded data: "{data}" bbox: {"present" if bbox is not None else "not present"}  - expected: {expected_data}')
        return False
    return True
```

## Image input

### Detection not found, bounding box present
![Detection not found, bounding box present](https://user-images.githubusercontent.com/73505719/97242440-02e1da80-1848-11eb-9bee-e45a8e9d7de0.png)

The detection appears to be a single or small group of pixels at the top left of the QR square.

![image](https://user-images.githubusercontent.com/73505719/97242868-12adee80-1849-11eb-9005-590fab638618.png)

### Detection not found, no bounding box
![Detection not found, no bounding box](https://user-images.githubusercontent.com/73505719/97242476-142ae700-1848-11eb-9fbe-934846db7bb6.png)

**Comment by Michael-Liao** [comment]
This also affects me.
**System Information**
* OpenCV => 4.4.0
* Operating System => Ubuntu 20.04
* Compiler => `gcc 9.3.0` along with `python3.7.7`, `numpy 1.19.5`

**Comment by RobertGalatNordic** [comment]
[gist to script that tests reliability of qrcode detection - it should be 100% because qrcode is generated, and passed to decoding, so it should be easy to detect qrcode](https://gist.github.com/RobertGalatNordic/a7e24efc5fdf81dbfb73138d0d1a446d)

print(cv2.getVersionString())
# 4.5.3

[failed_qrcodes.zip](https://github.com/opencv/opencv/files/7693236/failed_qrcodes.zip)

I also tested those images with cv2, and they reliably fail on detecting. When I scan the image with some random app in my phone, it works as expected, so there is something wrong in cv2

**Comment by RobertGalatNordic** [comment]
https://gist.github.com/RobertGalatNordic/aa1aa391ca849d06e62a8debf5eb5894
Using pyzbar is 100% successful, so the issue is definitely with opencv.
please fix this

**Comment by asmorkalov** [comment]
Tried the original image with pre 4.7.0. The QR code is decoded correctly with sample qrcode.py in both single and multi mode:
```
QR[0]@[219, 24, 222, 229, 4, 241, 4, 24] : ' http://o.marmocer.com/c/P00870000019121 '
```

```
QR[0]@[219, 24, 222, 229, 6, 230, 4, 24] : ' http://o.marmocer.com/c/P00870000019121 '
```

**Comment by AleksandrPanov** [comment]
Works with first image:

```
True
[[[219.99014    24.       ]
  [222.01868   229.89526  ]
  [  6.4315968 230.98553  ]
  [  4.         24.       ]]]
('http://o.marmocer.com/c/P00870000019121',)
```
