### ISSUE TITLE
Can't Convert tensorflow saved_model to frozen inference graph for use in OpenCV

### ISSUE THREAD

**Issue by Deep-learning-practitioner** [opencv/opencv#17938]
##### System information (version)
Using Google colab 
TF version = 2.2

I have fine tuned an SSD MobileNet V2 model in tensorflow Objecet Detection API 2. Now I'm trying to convert the saved_model to frozen inference graph so I can use it in OpenCV DNN module but I'm really confused as how to proceed.

I Have been following [this tutorial](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/), but how to modify this for mobilenet v2 trained with TFOD API v2.

**The saved model I'm trying to convert can be loaded from zoo via this code:** 
_You can run this in colab_

```
!wget 'http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz'
!tar -xf ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz
model_path = 'ssd_mobilenet_v2_320x320_coco17_tpu-8/saved_model/saved_model.pb'


import tensorflow as tf
loaded = tf.saved_model.load('ssd_mobilenet_v2_320x320_coco17_tpu-8/saved_model') 
```
### Now how can I convert this model to frozen inference graph?

 While following the above tutorial and running this code:

```
full_model = tf.function(lambda x: model(x))

full_model = full_model.get_concrete_function(tf.TensorSpec(loaded.inputs[0].shape, loaded.inputs[0].dtype))
```

I'm getting this error:

```
      1 full_model = tf.function(lambda x: model(x))
----> 2 full_model = full_model.get_concrete_function(tf.TensorSpec(loaded.inputs[0].shape, loaded.inputs[0].dtype))

AttributeError: '_UserObject' object has no attribute 'inputs'

```

Thank you, any help would be appreciated

**Comment by mshabunin** [comment]
This is OpenCV issue tracker, we don't fix problems with TensorFlow here.

**Comment by Deep-learning-practitioner** [comment]
> 
> 
> This is OpenCV issue tracker, we don't fix problems with TensorFlow here.

Hi, there is no use for frozen graphs in TF2 , infact it's depreciated. The only reason I'm converting it is for use in OpenCV DNN. so can you please help

Also will opencv be replacing the frozen graphs with saved_model format in the next release since TF2 really made it difficult to use pre trained models in OpenCV?

**Comment by ouening** [comment]
I have the same question. The frozen graph is depreciated. Should Opencv support new TensorFlow formats?
