### ISSUE TITLE
Feature request: StitcherAPI: Add python binding for composePanorama

### ISSUE THREAD

**Issue by susnux** [opencv/opencv#17956]
##### System information (version)
- OpenCV => 4.3
- Operating System / Platform => Linux
- Compiler => Python3.6.10

##### Detailed description

Please add the `Stitcher::composePanorama(InputArrayOfArrays images, OutputArray pano)` function to the python bindings.
This would allow reusing the estimated transforms multiple times (same, fixed, camera setup).
Currently you can only call `composePanorama(OutputArray pano)`, so you have to estimate the transform every time (sometimes features in other image pairs can not be detected, so manual stitching is needed if I can not reuse the old transform).

Found the same request as a question here: https://answers.opencv.org/question/145886 

##### Steps to reproduce

does not apply

##### Issue submission checklist

 - [x ] I report the issue, it's not a question
 - [x ] I checked the problem with documentation, FAQ, open issues,
 - [x ] I updated to latest OpenCV version and the issue is still there
 - [? ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by mshabunin** [comment]
Try to add `CV_WRAP` prefix to function declaration here: https://github.com/opencv/opencv/blob/b698d0a6ee12342a87b8ad739d908fd8d7ff1fca/modules/stitching/include/opencv2/stitching.hpp#L275

Like this:
https://github.com/opencv/opencv/blob/b698d0a6ee12342a87b8ad739d908fd8d7ff1fca/modules/stitching/include/opencv2/stitching.hpp#L263

Tests for both functions would be great too: https://github.com/opencv/opencv/blob/master/modules/stitching/misc/python/test/test_stitching.py
