### ISSUE TITLE
Question about OpenCV ARMv8 build validation

### ISSUE THREAD

**Issue by Yikun** [opencv/opencv#17951]
##### System information (version)
- OpenCV => ALL
- Operating System / Platform => Linux aarch64
- Compiler => ALL

##### Detailed description

Looks like we can only use `force_builders` to enable the armv8 build validation, that means not all PRs would be validated in ARMv8/aarch64.

Is there any reason to stop us to move the ARMv8 build in to default build list? Could we move the linux-ARMv8 in to default build lists?

[1] https://pullrequest.opencv.org/#/summary/

**Comment by mshabunin** [comment]
Currently we don't have enough resources for thorough support of this platform, so we manually run tests for "suspicious" PRs and have regular nightly tests (e.g. https://pullrequest.opencv.org/buildbot/builders/master-contrib_ARMv8-lin). Test scope is also reduced.

We mostly rely on community here, I believe @tomoaki0705 regularly run testing on a wide variety of ARM/CUDA platforms.

**Comment by dkurt** [comment]
Can we consider GitHub Actions to create ARMv8 build only checks?

**Comment by Yikun** [comment]
@mshabunin OK, it's good to know about it.

Agree with @dkurt , I think build only checks it's a good idea, as I know about Github Actions, the arm64 is only supported by [self hosted runner](https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/) or some 3rd action (like [run-on-arch-action](https://github.com/uraimo/run-on-arch-action), use qemu to create virtual arm64 env), so I'm not sure github actions is a good choice or not. 

And arm64 also is supported by [Travis CI](https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures) or [drone.io](https://discourse.drone.io/t/official-arm32-and-arm64-support/2485). Could these be our potential choices to enable quick build only checks?

**Comment by Yikun** [comment]
@dkurt Here[1] is the demo to enable the travis arm64 check build in OpenCV. All arm64 build checks costs about ~30mins. 
![image](https://user-images.githubusercontent.com/1736354/88644614-c3dfa400-d0f5-11ea-9c4d-44edbdeb5be8.png)

If you guys think this build check is okay to accepted, I'd like to propose a PR. : )

[1] https://github.com/Yikun/opencv/pull/1

**Comment by dkurt** [comment]
@Yikun, To build OpenCV for ARMv8 there is no need to have ARMv8 - it might be cross-compiled. So for build only pipeline we can use GitHub Actions as well (advantage against Travis CI is that there is already https://github.com/opencv/opencv/tree/master/.github folder and to setup Actions no new files will be created).

**Comment by Yikun** [comment]
@dkurt OK, agree with you, and our goal is that the arm64 version will not be break by any pr or change. And I think the github action is enough.

And I did some test on the github action, about 30mins to complete the all build check.

[1] https://github.com/Yikun/opencv/pull/2

**Comment by Yikun** [comment]
I also submit the PR in opencv https://github.com/opencv/opencv/pull/17989, it would be good if you guys have time to take a look and help to review.

**Comment by asmorkalov** [comment]
@Yikun OpenCV team starts testing aarch64 builds on Huawei ARM server with Ubuntu: https://build.opencv.org.cn/job/precommit/job/ubuntu-20.04-arm64/. I think we can close the ticket.

**Comment by Yikun** [comment]
@asmorkalov Cool, great to heard that, and now we have 3 type checks:
1. Perodic arm64 dayly check [0]
2. the cross-compiled check [1]
3. PR triggerd native arm64 check [2]


[0] https://pullrequest.opencv.org/buildbot/builders/master-contrib_ARMv8-lin
[1] https://github.com/opencv/opencv/pull/17989
[2] https://build.opencv.org.cn/job/precommit/job/ubuntu-20.04-arm64/
