### ISSUE TITLE
How to generate pbtxt when using cv::dnn

### ISSUE THREAD

**Issue by ayicherry** [opencv/opencv#17974]
env:
tensorflow = 1.14
opencv = 4.4

I have designed my own detection network using tensorflow and finally I got a frozen_inference.pb. However I don't know how to generate pbtxt that opencv needs. I have tried opencv source code tf.text_graph_faster_rcnn.py and I also tried some other ways, but all failed. Sometimes the error is "Input layer not found", sometimes the error is "anonymous-namespace" something like that....

**Comment by dkurt** [comment]
> I have designed my own detection network using tensorflow

Please read 

https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs

and

https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by ayicherry** [comment]
Thanks very much for your advising. However I have read the two website several times. 
In the https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API website, I use tf_text_graph_faster_rcnn.py, tf_text_graph_ssd.py and other two pys but all failed, because in my network the node name are different from the ones defeined in those py scripts.
And in the https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs, I use the code to turn pb file into pbtxt file, then it said I should replace a problematic subgraph, but my network has no flatten node, so I don't know which node I should remove and which node I should merge.

**Comment by ayicherry** [comment]
> > I have designed my own detection network using tensorflow
> 
> Please read
> 
> https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs
> 
> and
> 
> https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

Thanks very much for your advising. However I have read the two website several times.
In the https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API website, I use tf_text_graph_faster_rcnn.py, tf_text_graph_ssd.py and other two pys but all failed, because in my network the node name are different from the ones defeined in those py scripts.
And in the https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs, I use the code to turn pb file into pbtxt file, then it said I should replace a problematic subgraph, but my network has no flatten node, so I don't know which node I should remove and which node I should merge.

**Comment by dkurt** [comment]
OpenCV supports only detection networks only from TensorFlow Object Detection API for now.
