### ISSUE TITLE
Enhancement: unicode/UTF-8 support with InitFont & PutText

### ISSUE THREAD

**Issue by SteveKrebs** [opencv/opencv#17980]
As a user, I would like PutText to support characters beyond basic ASCII chars to be able to utilize additional characters in writing additional languages onto video frames. 

Acceptance would be for either extending the existing initFont / putText APIs or creating new APIs ( if necessary to keep backwards compatibility for the original APIs, example: initFont_UTF/ putText_UTF) that support additional characters.  

re: cv::HersheyFonts : There is Hershey font support for additional characters in Greek, Cyrillic, Japanese (kanji, hiragana and katakana) as well as support for mathematics, musical notation, map markers, and meteorological symbols.
re: https://sourceforge.net/projects/hershey9000/files/

**Comment by vpisarev** [comment]
@SteveKrebs, thanks for raising the issue.

I'm now preparing preparing patch that replaces Hershey fonts with TrueType/OpenType/Type 1 fonts. The current proposal that some font(s) will be embedded into OpenCV and they provide ASCII + Latin extended + Cyrillic + Greek glyphs. And users can also load their own fonts with arbitrary Unicode glyphs. putText() (including overloaded variants with custom fonts) will interpret input string as UTF8, so it will be easy-to-use and compatible with the current putText().

These are good news. Maybe not that good news is that it will be proposed for the "next" branch (to be created), so officially it will become available in OpenCV 5.0.

**Comment by SteveKrebs** [comment]
Well, good to hear it is at least it is a feature on the roadmap (I would sure like to see it in 4.4+ as well).

**Comment by mshabunin** [comment]
BTW, utf8/Cyrillic is already supported with COMPLEX font:
https://github.com/opencv/opencv/blob/77b01deb805b7166e938bbd17d393f051aad88c1/modules/imgproc/src/drawing.cpp#L2210-L2252

**Comment by lavrenkov-sketch** [comment]
@mshabunin in version 4.5.3.56 not works

**Comment by asmorkalov** [comment]
Done in https://github.com/opencv/opencv/pull/18760
