### ISSUE TITLE
Unexpected compile error on Matx

### ISSUE THREAD

**Issue by tksharpless** [opencv/opencv#18004]
##### System information (version)
- OpenCV =>4.1.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

unexpected compile error 

##### Steps to reproduce
Source code

```
typedef Vec3f localcolor;
inline double lensqd(const localcolor & c) {
    return c.ddot(c);
}
```

Result

error C2338: Matx should have at least 4 elements. channels >= 4
note: while compiling class template member function 'cv::Matx<float,3,1>::Matx(_Tp,_Tp,_Tp,_Tp)'
when compiling the ddot function.

The compiler is trying to instantiate a 3-element vector with 4 initializers. I can't see anything in the OCV source code that would make this happen.  Can you?

BTW there is no compile error with
`typedef Vec4f localcolor`

**Comment by tksharpless** [comment]
CORRECTION using OpenCV version 4

**Comment by tksharpless** [comment]
Updating to OpenCV 4.3.0 did not change the result.
BTW OpenCV installed from vcpkg repository

**Comment by alalek** [comment]
Provide minimal complete reproducer (provided 4 lines don't break building of test code).
Provide raw compiler log (don't use "Errors" view of MSVS, use "Build Output" instead).
