### ISSUE TITLE
How to load model save_model format from tensorflow 2.x in opencv2? Tensorflow Object Detection API

### ISSUE THREAD

**Issue by LuisEdMB** [opencv/opencv#18005]
Hello, how could I load a trained model in Tensorflow Object Detection API, in opencv2 to use DNN?

The format of the exported model is: save_model.

Tensorflow version: 2.2.0

Thanks!

**Comment by dkurt** [comment]
Please try to convert saved_model to a frozen graph first. Take a look at https://github.com/opencv/opencv/issues/16879#issuecomment-603815872 and https://github.com/opencv/opencv/issues/16582#issuecomment-603819498.

**Comment by LuisEdMB** [comment]
@dkurt Thanks, I followed the first link, but I get the following:

"Can't create layer "StatefulPartitionedCall" of type "StatefulPartitionedCall" in function 'getLayerInstance'"
