### ISSUE TITLE
 error: (-215:Assertion failed) !buf.empty() && buf.isContinuous() in function 'cv::

### ISSUE THREAD

**Issue by nagapoornima22** [opencv/opencv#18032]
##### Detailed description

 file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)

I am getting the imdecode issue:

cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:737: error: (-215:Assertion failed) !buf.empty() && buf.isContinuous() in function 'cv::imdecode_'

##### Steps to reproduce

    ```.py
    //  if flask.request.method == "POST":
            image = request.files["image"].read()
            print("image :" ,type(image))
            npimg = np.fromstring(image, np.uint8)
            print("npimg :" ,type(npimg))
            file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)
// passing the file to the recognize face. it is recognizing but facing facing cv2 error.
    ```

**Comment by berak** [comment]
this is definitely not an opencv library bug, but a valid assertion, what you got from flask was empty / invalid.
numpy's fromstring() frombuffer() will happily work with an empty string or an empty array, but imdecode wont.

maybe you should close this issue ?

**Comment by nagapoornima22** [comment]
Hi, 
From the flask i am getting the image and after imdecode i am able to decode the image and in the file i am receiving the numpy.ndarray.

**Comment by berak** [comment]
>  i am able to decode the image 

no, you're not. error clearly says so ;)

> From the flask i am getting the image 

again, this is probably invalid. please check the len() or such, not the type (even an empty numpy array has a valid type, which likely fooled you)

**Comment by nagapoornima22** [comment]
file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)
            print(len(file))
Len = 720, 
I am able to recognize the image , but showing that error

**Comment by nagapoornima22** [comment]
> > i am able to decode the image
> 
> no, you're not. error clearly says so ;)
> 
> > From the flask i am getting the image
> 
> again, this is probably invalid. please check the len() or such, not the type (even an empty numpy array has a valid type, which likely fooled you)

Hi, i have checked the length of that file with imdecode 
file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)
            print(len(file))
Len = 720, 
I am able to recognize the image , but showing that error

**Comment by nagapoornima22** [comment]
> > i am able to decode the image
> 
> no, you're not. error clearly says so ;)
> 
> > From the flask i am getting the image
> 
> again, this is probably invalid. please check the len() or such, not the type (even an empty numpy array has a valid type, which likely fooled you)

Hi, i have checked the length of that file with imdecode 
file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)
            print(len(file))
Len = 720, 
I am able to recognize the image , but showing that error

**Comment by nagapoornima22** [comment]
> > i am able to decode the image
> 
> no, you're not. error clearly says so ;)
> 
> > From the flask i am getting the image
> 
> again, this is probably invalid. please check the len() or such, not the type (even an empty numpy array has a valid type, which likely fooled you)

Hi, i have checked the length of that file with imdecode 
file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR)
            print(len(file))
Len = 720, 
I am able to recognize the image , but showing that error

**Comment by engperini** [comment]
> > > i am able to decode the image
> > 
> > 
> > no, you're not. error clearly says so ;)
> > > From the flask i am getting the image
> > 
> > 
> > again, this is probably invalid. please check the len() or such, not the type (even an empty numpy array has a valid type, which likely fooled you)
> 
> Hi, i have checked the length of that file with imdecode file = cv2.imdecode(np.frombuffer(npimg, dtype=np.uint8), cv2.IMREAD_COLOR) print(len(file)) Len = 720, I am able to recognize the image , but showing that error

Hi, I did it work following the recommendation len(buffer)!=0 , see my code if it would helps someone in the future:

`jpg1=np.frombuffer(jpg, dtype=np.uint8)
if len(jpg1!=0):
    i = cv2.imdecode(jpg1, cv2.IMREAD_COLOR)
cv2.imshow('i', i)

`

**Comment by bigbaicoding** [comment]
I think I solve the problem. Do not use cv2.imread(). You can try Image.open().  For example:         
img_test = Image.open(image)
img = np.array(img_test)
