### ISSUE TITLE
#error "Build configuration error: nGraph or NN Builder API backend should be enabled"

### ISSUE THREAD

**Issue by zgq91** [opencv/opencv#18040]
##### System information (version)

- OpenCV =4.4.0-openvino
- Operating System / Platform => Windows 64 Bit
- Compiler = Visual Studio 2017
openvino == 2020.4
-->

##### Detailed description
opencv compilation supports openvino

#error "Build configuration error: nGraph or NN Builder API backend should be enabled"

**Comment by sorny92** [comment]
How did you solve this?

**Comment by 52luoshu** [comment]
How did you solve this?

**Comment by sorny92** [comment]
> How did you solve this?

Using 4.5.0 and compiling openvino from sources doesn't now have any problem.

**Comment by 52luoshu** [comment]
> > How did you solve this?
> 
> Using 4.5.0 and compiling openvino from sources doesn't now have any problem.

So is there no solution for opencv4.4.0?

**Comment by dog-qiuqiu** [comment]
please open cmake option WITH_NGRAPH
