### ISSUE TITLE
Needs universal framework build on macOS Big Sur

### ISSUE THREAD

**Issue by MainasuK** [opencv/opencv#18049]
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => macOS 11.0
- Compiler => CMake

##### Detailed description

I found a temporary workaround to build arm64 opencv2.framework on the [DTK](https://developer.apple.com/programs/universal/) with Apple Silicon. And cross build should works but the try failed on the intel machine. (Intel and Apple Silicon could build arm64 & x86_64. Both could run x86_64 (via Rosetta). But arm64 running is Apple Silicon only).

Prepare:
- opencv-4.4.0
- opencv_contrib-4.4.0
- native cmake from: `brew install -s cmake`

With:
- arm64 DTK 
- macOS 11.0 Beta 4
- Xcode 12 Beta 4

Build:
1. Change the [build_framework.py](https://github.com/opencv/opencv/blob/c3bb57afeaf030f10939204d48d7c2a3842f4293/platforms/osx/build_framework.py#L62) line 62: "x86_64" to "arm64"
2. `% ./opencv-4.4.0/platforms/osx/build_framework.py ./opencv-framework-4.4.0 --contrib ./opencv_contrib-4.4.0 --enable_nonfree --disable CAROTENE`
3. get opencv2.framework output

Test:
1. `% ./opencv-4.4.0/platforms/osx/run_tests.py --framework_dir=/Users/mainasuk/Developer/opencv-framework-4.4.0 --framework_name=opencv2 /Users/mainasuk/Developer/opencv-framework-4.4.0/build/build-arm64-macosx/modules/objc/test`
2. fail with error: "Unable to find a destination matching the provided destination specifier: { platform:macOS, arch:x86_64 }"
3. open OpenCVTest.xcodeproj under `/Users/mainasuk/Developer/opencv-framework-4.4.0/build/build-arm64-macosx/modules/objc/test_build`
4. In the Build Settings set project Architectures to "Standard Architectures(64-bit Intel and ARM) - $(ARCHS_STANDARD)"
5. Run unit tests get compile error "Type of expression is ambiguous without more context" on line 27

```
    func testPoint2dToMat() {
        let pointsIn = [Point2d(x:3.80004, y:73.2), Point2d(x:16.01, y:7.1111), Point2d(x:3.14, y:6), Point2d(x:-78, y:14)]
        let pointsOut = Converters.Mat_to_vector_Point2d(Converters.vector_Point2d_to_Mat(pointsIn))
        XCTAssertEqual(pointsIn, pointsOut)    <<< here
    }
```

6. The `pointsIn` with type `[Point2d]` and pointsOut with `[Point2f]`
7. Comment out the line 27
8. All unit tests pass (skip testPoint2dToMat)

I have a Swift port [repo](https://github.com/MainasuK/OpenCVBridge) for OpenCV. After create folder "Frameworks" under the root and move the opencv2.framework into it. All demo program in `OpenCVBridge.xcodeproj` run identically as the Intel Mac.

And here are 3 problems for that. 
1. Disable CAROTENE fix arm64 build fail. I have no idea about that so temporary disable it. Maybe it's could be fixed.
2. The universal cross build framework needs with x86_64 and arm64 archs. Rosetta works for Intel app but arm64 arch is required for a native build.
3. Fix needs for testPoint2dToMat unit test. :)

I hope that transform will not so hard.

**Comment by asmorkalov** [comment]
@komakai could you help with the issue?

**Comment by komakai** [comment]
@asmorkalov @MainasuK 

>Disable CAROTENE fix arm64 build fail. I have no idea about that so temporary disable it. Maybe it's could be fixed.

I believe CAROTENE was contributed by NVIDIA - maybe they could help get it to work on Apple Silicon. If I'm correct it contains optimization for ARM processors so it would definitely be good to fix this

>universal cross build framework

The iOS build script is creating a Universal build script - so we could probably copy ideas from their

> Fix needs for testPoint2dToMat unit test

Looks like adding a cast somewhere would fix that

2 and 3 I can probably take a look at but I don't have a machine running Big Sur beta yet so it will take a while to get myself set up.

**Comment by asmorkalov** [comment]
Carotene library contains functions implementations with ARM NEON intrinsics. There is nothing specific to NVIDIA, it should be just general compilation issue.

**Comment by komakai** [comment]
I found a careless mistake in my code that is probably what caused the test to fail. Have created #18065 for that.
@MainasuK can you share the compile errors you get when building with CAROTENE enabled?

**Comment by MainasuK** [comment]
The log from: `% ./opencv-4.4.0/platforms/osx/build_framework.py ./opencv-framework-4.4.0 --contrib ./opencv_contrib-4.4.0 --enable_nonfree 2>&1 | tee build.log` 

[build.log](https://github.com/opencv/opencv/files/5051009/build.log)

There is one line error message about missing `numpy` module and I can not install `numpy` yet. That's another issue.

**Comment by mshabunin** [comment]
Carotene compilation should've been fixed here: #17987 Please try latest _3.4_ or _master_ branch version.

**Comment by MainasuK** [comment]
I use the DTK to build the framework for arm64 on master without any issue. 

And test on the different machines with the same environment:
- macOS Big Sur Dev Beta 4
- Xcode 12 Beta 4

**DTK**:
- [x] build arm64 on master
- [ ] build x86_64 on master ([DTK-build-x86_64-master.log](https://github.com/opencv/opencv/files/5055039/DTK-build-x86_64-master.log))
- [x] build x86_64 on master using Rosetta

**Intel mac**:
- [ ] build arm64 on master ([Intel-build-arm64.log](https://github.com/opencv/opencv/files/5055043/Intel-build-arm64.log))
- [x] build x86_64 on master

**Comment by mshabunin** [comment]
To build for arm64 on Intel machine, you have to provide cmake toolchain file for cross-compilation or pass the following parameters:
```
 cmake \
     -GXcode \
     -DCMAKE_SYSTEM_PROCESSOR=arm64 \
     -DCMAKE_OSX_ARCHITECTURES=arm64 \
     -DWITH_OPENJPEG=OFF \
     -DWITH_IPP=OFF \
../opencv
```

Probably something similar is required for cross-compilation on DTK for IA, but I don't have this system and can not test it.

**Comment by komakai** [comment]
@MainasuK I had a look at the macOS build scripts and there is a possibility that just the following simple change could work:

https://github.com/komakai/opencv/commit/c33a1e6ac48c10e8f98e5fb0acdedfb6153e64bb

Could you try building with that change with command line?

`./opencv/platforms/osx/build_framework.py --archs=x86_64,arm64 opencv_output_dir`

**Comment by komakai** [comment]
@MainasuK Ah sorry - this patch is not enough. We will need to create something equivalent to the `platforms\ios\cmake\Modules` and `platforms\ios\cmake\Toolchains` folders for macOS - that will take a bit longer.

**Comment by MainasuK** [comment]
@komakai The same error when build x86_64 on the DTK. And If the --archs set as `arm64,x86_64`. The arm64 part works. I guess the CAROTENE breaks cross build on the DTK after several times trying . I disable it and turn off NEON too. Then the x86_64 cross build works.

**Disable NEON**:
In `./platforms/ios/build_framework.py`

```python
def getCMakeArgs(self, arch, target):
        args = [
            "cmake",
            "-GXcode",
            "-DAPPLE_FRAMEWORK=ON",
            "-DENABLE_NEON=OFF",        <<<< add this
            "-DCMAKE_INSTALL_PREFIX=install",
            "-DCMAKE_BUILD_TYPE=%s" % self.getConfiguration(),
            "-DOPENCV_INCLUDE_INSTALL_PATH=include",
            "-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty",
            "-DFRAMEWORK_NAME=%s" % self.framework_name,
            ...
```

I use that command make the universal framework without error.
`./opencv-macos-universal-binary/platforms/osx/build_framework.py --archs=x86_64,arm64 ./opencv-framework-universal --contrib ./opencv_contrib-4.4.0 --enable_nonfree --disable CAROTENE 2>&1 | tee ./opencv-framework-universal/DTK-build-universal.log`

Framework and build log upload to [Dropbox](https://www.dropbox.com/s/tjsgnz12sxv43fl/opencv-framework-universal.zip?dl=0).

Check archs:
```zsh
% lipo -archs opencv2.framework/opencv2
x86_64 arm64
```

Maybe could disable CAROTENE and NEON for x86_64 build only. Because they are ARM only. 

And I make a universal build for my side-project [ImageReader](https://github.com/MainasuK/ImageReader/releases/tag/universal-alpha). The app natively running on the DTK and Intel mac without any issue. Only crash when using Rosetta and that's doesn't matter.

Thanks a lot and I'm glad to help if needs building tests.

**Comment by komakai** [comment]
I downloaded Xcode 12 beta4 and had another attempt at this:
https://github.com/komakai/opencv/commit/9b7725495b12b44f67904000eeb1c2c2a3ded71e
Building on x86_64 with `-archs=arm64,x86_64` I was able to successfully build a Universal framework.
Should work the other way round as well

**Comment by MainasuK** [comment]
I try to build the universal framework with the new commit on the DTK. And the camke report a configure error and returned. [DTK-build.log](https://github.com/opencv/opencv/files/5069506/DTK-build.log)

I notice when building x86_64 the log says:
```
--   CPU/HW features:
--     Baseline:
--       requested:                 DETECT
--       required:                  NEON
--       disabled:                  VFPV3
```

Maybe "-DCPU_BASELINE=DETECT" not mark the NEON off. So I add this just after your changes.
```
            if arch != "arm64":
                cmakecmd.append("-DENABLE_NEON=OFF")
```

Then the universal build works. And I'm trying to use the framework and see if have any error. Update it soon.
[DTK-build-works.log](https://github.com/opencv/opencv/files/5069646/DTK-build-works.log)

**Comment by komakai** [comment]
@MainasuK thanks for testing - I'll make a PR now

**Comment by komakai** [comment]
@MainasuK could you try building https://github.com/komakai/opencv/commit/fdcbd8d669579769ca31c695518690e6a5510839 on the DTK and see if the x86_64 build works correctly?

**Comment by MainasuK** [comment]
I test the new commit. The universal framework built on the DTK works.

[build.log](https://github.com/opencv/opencv/files/5115361/build.log)

**Comment by komakai** [comment]
@MainasuK thanks for testing - looks like the new patch is an improvement on the first attempts

**Comment by LGriffioen** [comment]
Hi,

I'm working on getting a macOS app compiling on  Silicon and I'm having some trouble building OpenCV for arm64. I'm using the CMake app to build the dylibs (we don't need the entire framework) and I'm using the 4.5.0-openvino release.

Is this supported as of that release? If so, I have some more questions below the fold. If not, is that coming soon?

---

The first problem is I don't seem to be able to compile for x86 and arm at the same time. I just get `invalid architecture`. Is it possible to build a universal binary?

The second is if I try to build for just arm, I immediately get compilation errors when I attempt to `make`

```
/Users/l.griffioen/Downloads/opencv-4.5.0-openvino/3rdparty/libjasper/jas_getopt.c:129:25: error: 
      implicit declaration of function 'jas_eprintf' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                        jas_eprintf("unknown long option %s\n", s);
                        ^
/Users/l.griffioen/Downloads/opencv-4.5.0-openvino/3rdparty/libjasper/jas_getopt.c:140:25: error: 
      implicit declaration of function 'jas_eprintf' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                        jas_eprintf("unknown short option %s\n", s);
                        ^
/Users/l.griffioen/Downloads/opencv-4.5.0-openvino/3rdparty/libjasper/jas_getopt.c:151:25: error: 
      implicit declaration of function 'jas_eprintf' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                        jas_eprintf("missing argument for option %s\n", s);
                        ^
3 errors generated.
make[2]: *** [3rdparty/libjasper/CMakeFiles/libjasper.dir/jas_getopt.c.o] Error 1
make[1]: *** [3rdparty/libjasper/CMakeFiles/libjasper.dir/all] Error 2
make: *** [all] Error 2
```

My command line tools are pointed at Xcode 12.2 beta 2 and I'm on Catalina. Do I need to be on Big Sur / the DTK to compile this?

Any help would be appreciated! (also if this isn't the best place for this discussion, I'd be happy to move it elsewhere.)

**Comment by komakai** [comment]
@LGriffioen building with this command line is known to work (i.e. produce a universal binary):
`./opencv/platforms/osx/build_framework.py --archs=x86_64,arm64 opencv_output_dir`

If you are building some other way then your results may vary.

@alalek any chance you could add "Support for Apple Silicon" to the ChangeLog for release 4.5 ? (Much appreciated!)

**Comment by sayakpaul** [comment]
Is there a comprehensive guide we could refer to that shows "How to install OpenCV on macOS >= 11 with the M1 chip?"

**Comment by sayakpaul** [comment]
Hi folks. 

I am on macOS 11 with the M1 chip. 

I am trying to build using cmake. 

Here's my cmake command - 

```
cmake \
	-GXcode \
	-DCMAKE_SYSTEM_PROCESSOR=arm64 \
	-DCMAKE_OSX_ARCHITECTURES=arm64 \
	-DWITH_OPENJPEG=OFF \
	-DWITH_IPP=OFF \
	-D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=/Users/sayakpaul/Downloads/opencv_contrib-4.5.0/modules \
    -D PYTHON3_EXECUTABLE=/Users/sayakpaul/miniforge3/envs/dev/bin/python3 \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D BUILD_EXAMPLES=ON ..
```

I am running into - 

```
CMake Error:
  Xcode 1.5 not supported.


CMake Error: Could not create named generator Xcode

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
```

Note that the paths in the cmake command are correct. 

Any workaround for this?

**Comment by sayakpaul** [comment]
I wrote a comprehensive blog post that shows how to build and install OpenCV on an M1 MacBook - https://sayak.dev/install-opencv-m1/. Hopefully, it turns out to be useful.

**Comment by luvwinnie** [comment]
@sayakpaul Hi I'm facing this problem, do you know how to solve this?

```
undefined symbols for architecture arm64:
  "_png_do_expand_palette_rgba8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in liblibpng.a(pngrutil.c.o)
  "_png_riffle_palette_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_do_expand_palette_rgb8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_imgcodecs.4.5.0.dylib] Error 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ansoni-san** [comment]
It likely linked with a x86_64 version of liblibpng.a 

You'll need to install the dependencies to different locations. The current convention is installing arm64 libraries using a homebrew instance under `/opt/homebrew` (and thus all resulting arm64 libraries being under there as well), and then reserving `/usr/local` for the x86_64 libraries.

Then you can simply switch your library and include paths using compiler and linker flags. Official homebrew advice on multiple installs (and specifically ARM vs Intel): https://docs.brew.sh/Installation#alternative-installs

#### Quick Example 

1 - This command will create the second homebrew installation for you:
  ```
  /bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/nrubin29/bea5aa83e8dfa91370fe83b62dad6dfa/raw/48f48f7fef21abb308e129a80b3214c2538fc611/homebrew_m1.sh)"
  ```
2 - You then install the dependencies using:
  ```
  arch -arm64 /opt/homebrew/bin/brew install <whatever>
  
  arch -x86_64 /usr/local/bin/brew install <whatever>
  ```

_You then just need to switch `LDFLAGS` and `CFLAGS` out when changing between target architectures._
