### ISSUE TITLE
VideoCapture in Windows 7 error (MSMF backend)

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#18044]
Win 7, CMake 3.18.1, VS 2015 community, opencv 422f802ec96feecbc9db2f60879e8fe364cf8a92 with Qt 5.15 and eigen.

Reading a frame from `VideoCapture` thrown exception:
````
[ INFO:0] global C:\Lib\opencv\source\opencv\modules\videoio\src\videoio_registr
y.cpp (191) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistr
y VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990)
; INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
[ INFO:0] global C:\Lib\opencv\source\opencv\modules\videoio\src\backend_plugin.
cpp (370) cv::impl::getPluginCandidates Found 2 plugin(s) for GSTREAMER
[ INFO:0] global C:\Lib\opencv\source\opencv\modules\videoio\src\backend_plugin.
cpp (175) cv::impl::DynamicLib::libraryLoad load c:\Lib\opencv\build_x64\bin\ope
ncv_videoio_gstreamer440_64d.dll => FAILED
[ INFO:0] global C:\Lib\opencv\source\opencv\modules\videoio\src\backend_plugin.
cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_gstreamer440_64d
.dll => FAILED
[ WARN:0] global C:\Lib\opencv\source\opencv\modules\videoio\src\cap_msmf.cpp (6
77) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (640x480 @ 30)
 MFVideoFormat_RGB24(codec not found)

Cap backend: MSMF
````

Test code:
<details>

````
#include <opencv2/imgcodecs.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2//highgui.hpp>
#include <fstream>
#include <iostream>

using namespace std;
using namespace cv;

int main(int argc, char** argv)
{
	VideoCapture cap;
	Mat frame;
	bool bIsOpen = cap.open(0);
	cout << "\nCap backend: " << cap.getBackendName() << endl;
	if (!bIsOpen) {
		cout << "Can't open camera!" << endl;
		return -1;
	}
	while (waitKey() != 27) {
		try {
			cap >> frame; //  <- exception here
		}
		catch (Exception &e) {
			cout << e.err;
		}
		if (frame.empty()) {
			cout << "Empty frame captured!" << endl;
			return -1;
		}
		imshow("cap", frame);
	}

	return 0;
}

````
</details>

In debug it is seen that error occurs here:
https://github.com/opencv/opencv/blob/dbab8d8c3897040f134af7195e130dbfcdc2c065/modules/core/src/copy.cpp#L298

Reproduced on several different PC with different cameras.

Last known OpenCV ver. where this code work is 4.12.

**Comment by mshabunin** [comment]
There is no exception description. `[ WARN:0] ...` is logging messages.

**Comment by Bleach665** [comment]
Yes, because I `cout << e.err;` from code above not executed.
`Access violation reading location` received on
https://github.com/opencv/opencv/blob/dbab8d8c3897040f134af7195e130dbfcdc2c065/modules/core/src/copy.cpp#L298

**Comment by mshabunin** [comment]
Can't reproduce with latest _master_ branch version (Windows 10, VS 2019).

**Comment by Bleach665** [comment]
On Windows 10 work file for me too.

**Comment by alalek** [comment]
Please try to capture stacktrace of the crash.
We don't have configurations with Windows 7 (it is EOL).

MSMF is not well supported on Win7 (extra Windows packages should be installed). Dynamic loader was implemented to workaround that, but looks like it fails somewhere.

**Comment by Bleach665** [comment]
> Please try to capture stacktrace of the crash.

https://github.com/opencv/opencv/blob/dbab8d8c3897040f134af7195e130dbfcdc2c065/modules/core/src/copy.cpp#L298
where occured `Access violation reading location`
called from
https://github.com/opencv/opencv/blob/dbab8d8c3897040f134af7195e130dbfcdc2c065/modules/videoio/src/cap_msmf.cpp#L1061
here 
`captureFormat.height` and `captureFormat.width` has correct values, `pitch` is `0`.

> extra Windows packages should be installed

As far as I remember Media Feature Pack is required only for Windows K and N series. Although maybe I'm wrong

**Comment by Bleach665** [comment]
> Last known OpenCV ver. where this code work is 4.12.

It worked well because default capture backend was `CAP_DSHOW`.

**Comment by Bleach665** [comment]
I don't think it makes sense to deal with this, so I'm closing the issue.
