### ISSUE TITLE
High CPU usage when decoding frames from RTSP

### ISSUE THREAD

**Issue by dexception** [opencv/opencv#18057]
OpenCV : 4.2
OS: Ubuntu 18.04
Compiler: GCC
Language: C/C++
Objective: To reduce cpu usage while decoding rtsp stream like VLC player
Issue: Project stuck because of high CPU usage

My understanding->
Every frame coming from RTSP is being converted to BGR and this is consuming lot of CPU.  The CPU is always more than a single core. We cannot scale unless we consume the same amount of CPU as VLC player. Can you please suggest a solution to this problem as this is a major problem for developers. If this is a legacy problem then can this be solved via adding a module inside opencv-contrib that would use RGB instead of BGR to make things easy for developers ?

**Comment by asmorkalov** [comment]
Do you observe the same issue with video file decoding? OpenCV uses video decoding back-end for all RTSP related work, but does not handle it but itself. FFmpeg is default back-end. You can try to switch to GStreamer or tune FFmpeg parameters.

**Comment by mshabunin** [comment]
FFmpeg backend does not support HW-accelerated decoding yet, so your only chance for now is GStreamer backend with manual pipeline. Check this article for some details: https://github.com/opencv/opencv/wiki/Video-capture-and-write-benchmark

**Comment by ashuezy** [comment]
I am also struggling with this issue. Is there an option to use the Cuda library to decode the RTSP stream and reduce CPU usage?
This issue needs to be addressed as this is a long-standing problem.

**Comment by tensorturtle** [comment]
Same issue. On NVIDIA Jetson Nano, a single 360p read from V4L2 camera (attached with USB) uses 50% of all four cores of CPU

**Comment by minalmeg** [comment]
> I am also struggling with this issue. Is there an option to use the Cuda library to decode the RTSP stream and reduce CPU usage?
> This issue needs to be addressed as this is a long-standing problem.

Take a look at this. I tried this and it did work out
[https://medium.com/@fanzongshaoxing/use-ffmpeg-to-decode-h-264-stream-with-nvidia-gpu-acceleration-16b660fd925d](url)
