### ISSUE TITLE
cv2 Stitcher_create() Python dropping quality of images

### ISSUE THREAD

**Issue by CoderStone** [opencv/opencv#18056]
##### System information (version)

- OpenCV => python 3.8, opencv 4.2
- Operating System / Platform =>Windows 64 BIT
- Compiler => Visual Studio Code
##### Detailed description
        stitcher=cv2.Stitcher_create()
        add=cv2.rotate(add,cv2.ROTATE_90_CLOCKWISE)
        print(count)
        status,new=stitcher.stitch([original,add])
        return new

![var4](https://user-images.githubusercontent.com/34324909/89724962-b8b93c00-da44-11ea-972f-de4903304782.jpg)
I am attempting to use cv2 Stitcher on scrolling screenshots to merge them together. However, the quality of the images seem to drop both in Panorama and Scan mode. Scan mode seems to work at least a bit, but the image quality becomes blurry and terrible.

Any ideas?

**Comment by CoderStone** [comment]
ignore the stitcher.remove, the error is at the stitch function

**Comment by asmorkalov** [comment]
Stitching module is designed to stitch images where objects are far from camera relatively to camera movement. I is not applicable for your case. The images are registered and warped to one surface. The warning introduces the mentioned issue.

**Comment by CoderStone** [comment]
Any possible alternatives for my purpose?
