### ISSUE TITLE
Matched verison of opencv(dnn,GPU) and CUDA

### ISSUE THREAD

**Issue by KaninchenM** [opencv/opencv#18050]
OpenCV => 4.2
Operating System / Platform = Ubuntu 16.04
CUDA = 9.0.176
GPU = Tesla P40, P4

I wanna use OpenCV's dnn to do YOLO prediction depending on GPU. Here the [information](https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/) showed that, only the OpenCV4.2+ can support Nvidia GPU. So I tried to compile and install OpenCV 4.3.0. But when making install, I got the error:
![image](https://user-images.githubusercontent.com/18650200/89605239-a3ef7380-d89f-11ea-8b5a-d9a93e0e5635.png)

I've searched and found the operation is supported in CUDA10+. Considering I've installed other packages in my environment, upgrading CUDA may not be a good plan. 
My questions are:
1. Making sure if the matched version information is right. For example, maybe the lower version of Opencv can support Tesla P40 but I miss the info.
2. If my matched version information is right, what I can do now excepting upgrading CUDA?

Thank you all. I have not found the official information of my confusion. In [official docs](https://docs.opencv.org/4.2.0/d7/d9f/tutorial_linux_install.html), it just say the opencv4.x package has tested in CUDA10.04 `but should work with other distros as well`

**Comment by YashasSamaga** [comment]
The minimum required CUDA version is 9.2 in OpenCV 4.4.0 to use the CUDA backend in OpenCV DNN. You need CUDA 10 or above in OpenCV 4.3 and below.
