### ISSUE TITLE
gen_pattern.py Pattern Maker has a border issues

### ISSUE THREAD

**Issue by IanMaquignaz** [opencv/opencv#18081]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Python3

##### Detailed description

Borders for make_circles_patter() and and make_acircles_pattern() are inconsistent, resulting in an un-centered pattern. 

What a 4x3 asymmetric circle gird with 40mm spacing looks like:
![acircleGrid_4x3@40mm](https://user-images.githubusercontent.com/7108263/90063007-ac3c1a00-dcb6-11ea-8f18-e3f23ee87c2f.png)

What it should be:
![fixed_acircleGrid_4x3@40mm](https://user-images.githubusercontent.com/7108263/90063008-acd4b080-dcb6-11ea-8a26-0207a8a855c7.png)

##### Steps to reproduce
Run gen_pattern.py and observe the result in Gimp (or another svg file viewer)

gen_pattern.py -o circleGrid_13x9@20mm.svg --rows 4 --columns 3 --type circles --square_size 40 -u mm --page_size A4
 --radius_rate 5

## Notes
Have resolved the issue, just need to merge

**Comment by alalek** [comment]
> What it should be

This is wrong.
Diagonals must be 45 degrees.

Also check result images using `findCirclesGrid()` with `CALIB_CB_ASYMMETRIC_GRID`.


See also samples here: https://github.com/opencv/opencv_extra/tree/4.4.0/testdata/cv/cameracalibration/asymmetric_circles

**Comment by IanMaquignaz** [comment]
You're absolutely correct. Know how I can update the description of CALIB_CB_ASYMMETRIC_GRID to reflect this characteristic? 

The current definition is:
 "CALIB_CB_ASYMMETRIC_GRID uses asymmetric pattern of circles"

This could be updated to: 
 "CALIB_CB_ASYMMETRIC_GRID uses an asymmetric pattern of circles with intermittent 45 degree offset."

**Comment by IanMaquignaz** [comment]
Also found a new bug where standard paper size in inches is unsupported due to 8.5"x11" being floating point. Width and height are parsed as integers. 

Have corrected this issue by parsing input page size as floats, though conversion to may cause minor rounding errors
