### ISSUE TITLE
readNetFromONNX: Cant create layer of type 'Exp' in getLayerInstance

### ISSUE THREAD

**Issue by skaldesh** [opencv/opencv#18088]
- OpenCV => 4.4.0-dev (master branch)
- Operating System / Platform => Arch Linux x86_64
- Compiler => gcc
- PyTorch => 1.6.0 (latest docker container with gpu)

##### Detailed description

Very similar issue: https://github.com/opencv/opencv/issues/15244  
@dkurt

Basically, I exported a ssdlite-mobilenetv3 in PyTorch to ONNX format. Loading it in OpenCV leads to this error:  
`create detection model: OpenCV(4.4.0-dev) /tmp/opencv/opencv/modules/dnn/src/dnn.cpp:604: error: (-2:Unspecified error) Can't create layer "1117" of type "Exp" in function 'getLayerInstance'`    

Enabling `fusion` did not solve my issue.

Here is the code I used to export the model:
```python
net.load(model_path)
net.to('cuda')
net.eval()

model_path = f"models/model.onnx"

dummy_input = torch.randn(1, 3, 300, 300).cuda()

torch.onnx.export(net, dummy_input, model_path, verbose=False, output_names=['scores', 'boxes'])
```

Here is my PyTorch model \([mb3-ssd-lite.pth.txt](https://github.com/opencv/opencv/files/5069178/mb3-ssd-lite.pth.txt)\) and converted ONNX model \([mb3-ssd-lite.onnx.txt](https://github.com/opencv/opencv/files/5069182/mb3-ssd-lite.onnx.txt)\)

**Comment by l-bat** [comment]
Exp subgraph
![image](https://user-images.githubusercontent.com/22346860/90230535-5d12f800-de22-11ea-840a-b93d17c2de93.png)

**Comment by l-bat** [comment]
You can try to create custom layer like this:

```python
import cv2 as cv
import numpy as np

class ExpLayer(object):
    def __init__(self, params, blobs):
        super(ExpLayer, self).__init__()

    def getMemoryShapes(self, inputs):
        return inputs

    def forward(self, inputs):
        return [np.exp(inputs[0])]

cv.dnn_registerLayer('Exp', ExpLayer)
```

**Comment by skaldesh** [comment]
@l-bat Thanks for the suggestion. I am programming in C++, do you maybe have a hint for me how I could try the same in C++?

**Comment by dkurt** [comment]
@skaldesh, please follow https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html

**Comment by skaldesh** [comment]
We are executing the model on the GPU. Is my assumption right that by writing such a custom layer in simple C++, the execution for it would jump back to CPU?

**Comment by dkurt** [comment]
That's right. For more optimal implementaion of SSD, use PyTorch @symbolic aliases to create layers such as PriorBox and DetectionOutput. See https://github.com/amdegroot/ssd.pytorch/pull/462 for example.

**Comment by EMichaelC** [comment]
> You can try to create custom layer like this:
> 
> ```python
> import cv2 as cv
> import numpy as np
> 
> class ExpLayer(object):
>     def __init__(self, params, blobs):
>         super(ExpLayer, self).__init__()
> 
>     def getMemoryShapes(self, inputs):
>         return inputs
> 
>     def forward(self, inputs):
>         return [np.exp(inputs[0])]
> 
> cv.dnn_registerLayer('Exp', ExpLayer)
> ```

I have the same problem when using readnetfromonnx(yolov4-csp.onnx).

Can't create layer Softplus.

How would i register the layer in my case?

Thanks for the help.

**Comment by fengyuentau** [comment]
@dkurt Hi, as you suggested using PyTorch's `@symbolic`, I checked your PR(https://github.com/amdegroot/ssd.pytorch/pull/462), and saw you defined the decorator, but cannot find anywhere using this decorator. Could you explain about how this work?

**Comment by dkurt** [comment]
@fengyuentau, https://pytorch.org/docs/stable/onnx.html#custom-operators

**Comment by fengyuentau** [comment]
@dkurt thanks very much! I'll give it a try.

**Comment by fengyuentau** [comment]
@dkurt I have some questions for your solution to add the 'DetectionOutput' node into the ONNX model:
1. Does the `symbolic` function in `Detect` override the `forward` when building the 'DetectionOutput' node? In this case, maybe I can leave `forward` unimplemented and only have the `symbolic` function?
2. Is it necessary for the `Detect` class to inherit from `torch.autograd.Function`? Usually I use `torch.nn.Module` instead of `torch.autograd.Function`, so I am not familiar with the latter one.

BTW, I tried to add the 'DetectionOutput' layer to my onnx model following this guide (https://pytorch.org/docs/stable/onnx.html#custom-operators), but failed because I thought I can leave the actual op unimplemented and only add the node, which turns out to be wrong (https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html).

**Comment by dkurt** [comment]
@fengyuentau, symbolic should have `forward` method because ONNX conversion runs model once to get tensors.

> Is it necessary for the Detect class to inherit from torch.autograd.Function? Usually I use torch.nn.Module instead of torch.autograd.Function, so I am not familiar with the latter one.

I've tried only torch.autograd.Function. Then you can wrap it into the Module but symbolic op should be used by `.apply()`
