### ISSUE TITLE
OpenCV.js --simd build fails with recent Emscripten

### ISSUE THREAD

**Issue by tailsu** [opencv/opencv#18097]
##### System information (version)
- OpenCV => recent master (949fe93)
- Operating System / Platform => OSX
- Compiler => Emscripten 2.0.0

##### Detailed description

Multiple source files fail with
```
In file included from .../opencv/modules/core/include/opencv2/core/hal/intrin.hpp:228:
.../opencv/modules/core/include/opencv2/core/hal/intrin_wasm.hpp:2810:55: error: use of undeclared identifier 'wasm_i8x16_mul'
```

Recent versions of Emscripten are based on LLVM 12. This version has an intrinsics headers that doesn't contain functions used by OpenCV that were present in e.g. LLVM 9 (e.g. in Emscripten 1.38.33).

```
~/Documents/emsdk/upstream/bin $ ./llc --version
LLVM (http://llvm.org/):
  LLVM version 12.0.0git
  Optimized build with assertions.
  Default target: x86_64-apple-darwin19.4.0
  Host CPU: skylake-avx512

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

##### Steps to reproduce

```
# install Emscripten 2.0.0
cd emsdk/
emsdk install 2.0.0
emsdk activate 2.0.0
./emsdk_env.sh

# build OpenCV.js
cd opencv/platforms/js/
emmake python build_js.py build --simd
```

**Comment by alalek** [comment]
Feel free to check updated JS SIMD backend from this PR: #18068

/cc @huningxin @lionkunonly

**Comment by huningxin** [comment]
https://github.com/opencv/opencv/pull/18068 uses emscripten 1.39.16. It would be good to test with latest 2.0.0. @lionkunonly, could you please help verify? Thanks!

**Comment by lionkunonly** [comment]
@tailsu @alalek @huningxin  I have tested with lastest 2.0.0 based on https://github.com/opencv/opencv/pull/18068.  Because in the latest 2.0.0, the wasm function `wasm_i8x16_mul` is not supported, the simd building would meet errors. Comment  the **line 2647 and 2648**, which use the `wasm_i8x16_mul`, in `opencv/modules/core/include/opencv2/core/hal/intrin_wasm.hpp`, you can finish simd build successfully. The output passes the tests.

**Comment by vrabaud** [comment]
Hi, this is still present in master and will not be fixed on the emscripten side, cf https://github.com/emscripten-core/emscripten/issues/12018
Maybe something to fix for 4.5.1 ? Thx

**Comment by themancalledjakob** [comment]
perhaps a more elegant approach might be something like:

`opencv/modules/core/include/opencv2/core/hal/intrin_wasm.hpp (1248:1273)`
```diff
#if (__EMSCRIPTEN_major__ * 1000000 + __EMSCRIPTEN_minor__ * 1000 + __EMSCRIPTEN_tiny__) >= (1039012) \
+    or !defined wasm_i8x16_mul
    inline v_uint8x16 v_mul_wrap(const v_uint8x16 & a, const v_uint8x16 & b){
        [...]
    }
    inline v_int8x16 v_mul_wrap(const v_int8x16 & a, const v_int8x16 & b){
        [...]
    }
#else
    OPENCV_HAL_IMPL_WASM_BIN_FUNC(v_uint8x16, v_mul_wrap, wasm_i8x16_mul)
    OPENCV_HAL_IMPL_WASM_BIN_FUNC(v_int8x16, v_mul_wrap, wasm_i8x16_mul)
#endif
```

and
`opencv/modules/core/include/opencv2/core/hal/intrin_wasm.hpp (23:41)`
```diff
#if (__EMSCRIPTEN_major__ * 1000000 + __EMSCRIPTEN_minor__ * 1000 + __EMSCRIPTEN_tiny__) < (1038046) \
+    and defined wasm_trunc_saturate_i32x4_f32x4 \
+    and defined wasm_trunc_saturate_u32x4_f32x4 \
+    and defined wasm_trunc_saturate_i64x2_f64x2 \
+    and defined wasm_trunc_saturate_u64x2_f64x2 \
+    and defined wasm_convert_f32x4_i32x4 \
+    and defined wasm_convert_f32x4_u32x4 \
+    and defined wasm_convert_f64x2_i64x2 \
+    and defined wasm_convert_f64x2_u64x2
// handle renames: https://github.com/emscripten-core/emscripten/pull/9440 (https://github.com/emscripten-core/emscripten/commit/755d5b46cb84d0aa120c10981b11d05646c29673)
    #define wasm_i32x4_trunc_saturate_f32x4 wasm_trunc_saturate_i32x4_f32x4
    #define wasm_u32x4_trunc_saturate_f32x4 wasm_trunc_saturate_u32x4_f32x4
    #define wasm_i64x2_trunc_saturate_f64x2 wasm_trunc_saturate_i64x2_f64x2
    #define wasm_u64x2_trunc_saturate_f64x2 wasm_trunc_saturate_u64x2_f64x2
    #define wasm_f32x4_convert_i32x4 wasm_convert_f32x4_i32x4
    #define wasm_f32x4_convert_u32x4 wasm_convert_f32x4_u32x4
    #define wasm_f64x2_convert_i64x2 wasm_convert_f64x2_i64x2
    #define wasm_f64x2_convert_u64x2 wasm_convert_f64x2_u64x2
#endif // COMPATIBILITY: <1.38.46
```
as this way it's independent from the version number and possibly even future proof if things change. it might be even an idea to leave away the version checking altogether.

would there be any downsides to this approach?

**Comment by gblikas** [comment]
This still appears to be an issue with `opencv4` (via `vcpkg`), and `emscripten 3.1.62`: 

```bash
$ emcc --version

> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.62 (34c1aa36052b1882058f22aa1916437ba0872690)
> Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
> This is free and open source software under the MIT license.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ vcpkg --version

> vcpkg package management program version 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
> 
> See LICENSE.txt for license information.

$ uname -vmp
> 22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024 x86_64 x86_64
```

---

> @tailsu @alalek @huningxin I have tested with lastest 2.0.0 based on #18068. Because in the latest 2.0.0, the wasm function `wasm_i8x16_mul` is not supported, the simd building would meet errors. Comment the **line 2647 and 2648**, which use the `wasm_i8x16_mul`, in `opencv/modules/core/include/opencv2/core/hal/intrin_wasm.hpp`, you can finish simd build successfully. The output passes the tests.

@lionkunonly doing this does work. However, since I'm using `vcpkg`, and am looking for a portable solution, I'd rather not require others using the library to comment out specific lines.

**Comment by gblikas** [comment]
@tailsu was this an issue specific to the use of the `simd` flag? I would assume you get the same error on https://github.com/opencv/opencv/commit/7dcc305301e5fc9b74a82c91d7bb9132905708de without specifying the flag.  I'm facing the a similar error (expect a little later in the file) with `opencv4.8.0` (via `vcpkg`), and `emscripten 3.1.62` (not using any compiler flags, cause `vcpkg`): 

```bash
$ emcc --version

> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.62 (34c1aa36052b1882058f22aa1916437ba0872690)
> Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
> This is free and open source software under the MIT license.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ vcpkg --version

> vcpkg package management program version 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
> 
> See LICENSE.txt for license information.

$ uname -vmp
> 22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024 x86_64 x86_64
```

Actual error: 

```
opencv4/src/4.8.0-2bf495557d.clean/modules/core/include/opencv2/core/hal/intrin_wasm.hpp:1916:22: error: use of undeclared identifier 'wasm_trunc_saturate_i32x4_f32x4'
 1916 |     return v_int32x4(wasm_i32x4_trunc_saturate_f32x4(wasm_f32x4_add(a.val, h)));
      |                      ^
opencv4/src/4.8.0-2bf495557d.clean/modules/core/include/opencv2/core/hal/intrin_wasm.hpp:26:41: note: expanded from macro 'wasm_i32x4_trunc_saturate_f32x4'
   26 | #define wasm_i32x4_trunc_saturate_f32x4 wasm_trunc_saturate_i32x4_f32x4
   ```

_Perhaps this question is better as a separate issue._
