### ISSUE TITLE
libopencv_imgcodecs.so.4.4.0: undefined reference to `jpeg_default_qtables'

### ISSUE THREAD

**Issue by hanhao20190402** [opencv/opencv#18101]
- OpenCV => 4.4
- Operating System / Platform => Ubantu 20

##### Detailed description

han@han:~/opencv/build$ sudo make
[ 70%] Built target opencv_rgbd
[ 71%] Built target opencv_shape
[ 71%] Built target opencv_structured_light
[ 72%] Built target opencv_ts
[ 73%] Built target opencv_video
[ 74%] Built target opencv_videostab
[ 77%] Built target opencv_xfeatures2d
[ 81%] Built target opencv_ximgproc
[ 81%] Built target opencv_xobjdetect
[ 81%] Linking CXX executable ../../../../bin/opencv_waldboost_detector
/usr/bin/ld: ../../../../lib/libopencv_imgcodecs.so.4.4.0: undefined reference to `jpeg_default_qtables'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/build.make:94：bin/opencv_waldboost_detector] error 1
make[1]: *** [CMakeFiles/Makefile2:4731：modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all] error 2
make: *** [Makefile:163：all] error 2

i've try all the solutions on google but i still can't fix it..

**Comment by hanhao20190402** [comment]
--   OpenCV modules:
--     To be built:                 alphamat aruco bgsegm bioinspired calib3d ccalib core datasets dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching tracking ts video videoio videostab viz xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    dnn world
--     Disabled by dependency:      dnn_objdetect dnn_superres mcc text
--     Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv java js julia matlab ovis python3 sfm
--     Applications:                apps
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   GUI: 
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.64.3)
--       GtkGlExt:                  NO
--     VTK support:                 YES (ver 6.3.0)
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
--     JPEG:                        /opt/libjpeg-turbo/lib64/libjpeg.so (ver 80)
--     WEBP:                        /usr/lib/x86_64-linux-gnu/libwebp.so (ver encoder: 0x020e)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.37)
--     TIFF:                        /usr/local/lib/libtiff.so (ver 42 / 4.0.10)
--     JPEG 2000:                   OpenJPEG (ver 2.3.1)
--     OpenEXR:                     build (ver 2.3.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (58.54.100)
--       avformat:                  YES (58.29.100)
--       avutil:                    YES (56.31.100)
--       swscale:                   YES (5.5.100)
--       avresample:                NO
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
-- 
--   Parallel framework:            TBB (ver 2020.1 interface 11101)
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Lapack:                      NO
--     Eigen:                       YES (ver 3.3.7)
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/han/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.18)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.18rc1)
--     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.16.5)
--     install path:                lib/python2.7/dist-packages/cv2/python-2.7
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:                          
--     ant:                         NO
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Install to:                    /usr/local
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/han/opencv/build


here's my build details

**Comment by alalek** [comment]
> /opt/libjpeg-turbo/lib64/libjpeg.so

This is neither system package nor OpenCV file.
OpenCV can't fix mess between includes/libs in your build environment.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
