### ISSUE TITLE
Bug: Bit-wise operators should not be used where logical operators should be used. ( && should be used instead of &) 

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [opencv/opencv#18115]
https://github.com/opencv/opencv/blob/a66f61748fc4861374b8dc458866a9614925350a/modules/calib3d/src/calibration_handeye.cpp#L47

``` cpp
   if (trace > 0) {
        double S = sqrt(trace + 1.0) * 2; // S=4*qw
        qx = (m21 - m12) / S;
        qy = (m02 - m20) / S;
        qz = (m10 - m01) / S;
    } else if ((m00 > m11)&(m00 > m22)) {                             //HERE!!!
        double S = sqrt(1.0 + m00 - m11 - m22) * 2; // S=4*qx
        qx = 0.25 * S;
        qy = (m01 + m10) / S;
        qz = (m02 + m20) / S;
    }
```

Reported by: USTCHCS Analysis Toolsuite Bugfinder
(bugfinder-5.2: Bit-wise operators should not be used where logical operators should be used. )

**Comment by alalek** [comment]
Please do NOT report low-priority / low-impact issues from static analyzers.

Just `&` is optimization from 2000 (compilers was not to smart and generate extra branching code here).

We already have Coverity and other tools for code static analyzing.
