### ISSUE TITLE
Out of focus Filter example not working

### ISSUE THREAD

**Issue by csverma610** [opencv/opencv#18111]
Hello,

The example in the tutorial use radius = 53 and SNR = 5200.  I downloaded
the code and used the sample image as in the tutorial. However results are
way off .Did anyone try the example? Has something changed?

Thanks

**Comment by asmorkalov** [comment]
Could you provide mode details: what is your OS, OpenCV version, which file do you execute and it's parameters?

**Comment by dkurt** [comment]
duplicate of https://github.com/opencv/opencv/issues/17315
