### ISSUE TITLE
Suspicious code: pointer to 'char' type is compared with the '\0' value.

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [opencv/opencv#18112]
https://github.com/opencv/opencv/blob/a66f61748fc4861374b8dc458866a9614925350a/3rdparty/libjasper/jpc_util.c#L105

It looks like a typo occurred where `cp` should be `*cp` instead. 

``` c
    char *cp;

    strncpy(buf, s, sizeof(buf));
    buf[sizeof(buf) - 1] = '\0';
    n = 0;
    if ((cp = strtok(buf, delim))) {
        ++n;
        while ((cp = strtok(0, delim))) {
            if (cp != '\0') {                            /* cp should be *cp ??? */
                ++n;
            }
        }
    }
```
Reported by: USTCHCS Analysis Toolsuite Bugfinder
(bugfinder-4.10:Suspicious code: pointer to 'char' type is compared with the '\0' value.)

**Comment by mshabunin** [comment]
Please report this issue to the upstream repository: https://github.com/jasper-software/jasper

**Comment by alalek** [comment]
Jasper is not supported anymore and disabled by default: #14058
