### ISSUE TITLE
BUG:TypeError: Expected Ptr<cv::UMat> for argument 'img'

### ISSUE THREAD

**Issue by olojuwin** [opencv/opencv#18120]
- OpenCV =>3.10.37
- Operating System / Platform => Windows 64 Bit
-python 

```
import cv2
import sys
import numpy as np
import datetime
import os
import glob

import time



img = cv2.imread('t1.jpg')

# print(type(img))
img=np.rot90(img,-1)



# (h, w) = img.shape[:2]  # 10
# center = (h // 2, w // 2)  # 11
# M = cv2.getRotationMatrix2D(center, 90, 1.0)  # 15
# img = cv2.warpAffine(img, M, (w, h))  # 16

color = (0, 0, 255)
print(img)

cv2.rectangle(img, (10,20 ),(30,40) ,color,2)


cv2.imwrite("5_flip.jpg",img)

```
When I ran this script, I encountered the following error：TypeError: Expected Ptr<cv::UMat> for argument 'img'

**Comment by olojuwin** [comment]
@alalek hi,I run under Linux, and there is no such problem。I have tried different versions of OpenCV Python on Windows system, and they all have this problem

**Comment by alalek** [comment]
Try to investigate using #15918

> img=np.rot90(img,-1)

OpenCV can't handle views as InputOutputArrays (there are several requirements for conversion).

Try to make regular numpy array:
```
img=np.array(np.rot90(img,-1))
```

**Comment by yurkovak** [comment]
Just had this issue and resolved it by the explicit `img = np.array(img)` right before the operation that fails. It somehow helps even though `type(image_db)` returns `<class 'numpy.ndarray'>` both before and after this line.

**Comment by olojuwin** [comment]
@alalek @yurkovak hi，thanks，This problem is solved！

**Comment by HanwenCao** [comment]
> Just had this issue and resolved it by the explicit `img = np.array(img)` right before the operation that fails. It somehow helps even though `type(image_db)` returns `<class 'numpy.ndarray'>` both before and after this line.

Hi, thank you for your excellent answer. It worked but I don't know why. Could you explain the reason for expliciting `img = np.array(img) `? Thank you!

**Comment by yurkovak** [comment]
@HanwenCao In my case the issue was in what was discussed in #15895. The bug appeared after flipping RGB to BGR with `img = img[:, :, ::-1]`. After replacing this line with the corresponding opencv operation like this `img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` I was able to get rid of `img = np.array(img)`.  
Please refer to [this comment](https://github.com/opencv/opencv/issues/15895#issuecomment-553808013) for a better explanation of this behavior. Unfortunately, I wasn't able to find what exactly "numpy on-the-fly reshaped array" means in a broader sense.

Just for the record:
- OpenCV: 4.2.0
- Python: 3.7.0
- OS: 16.04

**Comment by SCZeiDan** [comment]
change this " img = cv2.imread('t1.jpg') " to " ret, img = cv2.imread('t1.jpg') " may slove your problem.

**Comment by aspsto** [comment]
> Just had this issue and resolved it by the explicit `img = np.array(img)` right before the operation that fails. It somehow helps even though `type(image_db)` returns `<class 'numpy.ndarray'>` both before and after this line.

Thank you very much for your answer. It also solved my problem.

**Comment by sidml** [comment]
In my case, using `im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)` after `np.rot90(img,-1)` works.
However, just using `img=np.array(np.rot90(img,-1))` doesn't work.

**Comment by www516717402** [comment]
> In my case, using `im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)` after `np.rot90(img,-1)` works.
> However, just using `img=np.array(np.rot90(img,-1))` doesn't work.

Great help. `img = np.array(img)` and `img=img[:,:,::-1]` both doesn't work. But `img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` worked.

**Comment by louis925** [comment]
Somehow `img = np.array(img)` still desn't work for me but `img = img.copy()` works.

**Comment by ash-jha** [comment]
same as @louis925 , none of the other solutions worked for me but `img = img.copy()` did work. No idea why, because the dtype of `img` for me was already `uint8` and the type was `numpy.ndarray`. 

The command I was trying to run was

`cv2.normalize(img, img, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)`

Note that changing the `dst` argument to `None` also fixed this issue. Very curious as to what's causing this problem.

**Comment by huntzhan** [comment]
`np.ascontiguousarray` also help mitigate this issue.

**Comment by dxoco** [comment]
Hi @olojuwin!
I just had the same issue while trying to compress images:

![vmat](https://user-images.githubusercontent.com/67029492/108165065-910ff400-70b7-11eb-880f-e1963b1142a8.PNG)


**and I could solve it by first reading the image:**
source: https://stackoverflow.com/questions/40027678/how-to-compress-png-file-with-opencv-in-python/40028628

![solved](https://user-images.githubusercontent.com/67029492/108165081-966d3e80-70b7-11eb-8dba-bb989f34d2a4.PNG)


(btw, if anyone is wondering, the images went from 250KB to 120KB in average)

cheers,
Dan

**Comment by navidnadery** [comment]
You can use np.ascontiguousarray(img), for example in your case:
`cv2.rectangle(np.ascontiguousarray(img), (10,20 ),(30,40) ,color,2)`

**Comment by akbarwijayaa** [comment]
> Somehow `img = np.array(img)` still doesn't work for me but `img = img.copy()` works.

thanks @louis925 , it solve my problem

**Comment by saftanas** [comment]
When using `cv2.circle` I had to convert my 2D array using: ` img = np.array(img, dtype=np.uint8` to avoid this error.

**Comment by dwaltrip** [comment]
I had a torch Tensor of an image, and I wanted to draw lines on it using `cv2.line` and was getting this error.

Both `img.copy` and `cv2.cvtColor` worked for me.

```python
img = (image_tensor.permute(1,2,0) * 255).byte().numpy()
# hack to make `cv2.line` happy...
img = img.copy()
cv2.line(image, *other_args)
```
