### ISSUE TITLE
East Text Detector: Select parameters

### ISSUE THREAD

**Issue by shersoni610** [opencv/opencv#18132]
Hello, 
I am using the EAST text detector supplied by the OpenCV (Version 4.1.0 on Linux 18.04). I get 
some unexpected results. Sometime even the clear texts are not detected. 

The first image is the input image and the second is the output from the EAST text detector. The result is quite unexpected
because the texts are very clear. How can I fine tune the EAST detector by adjusting some parameters?

Thanks

![image](https://user-images.githubusercontent.com/57876250/90580644-3a644480-e17e-11ea-8910-daa7bc347aad.png)
![2](https://user-images.githubusercontent.com/57876250/90580678-4ea84180-e17e-11ea-9abe-eb9ff8617c16.png)

**Comment by dkurt** [comment]
Please use [text_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/text_detection.cpp) or [text_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/text_detection.py). Try to vary `width` and `height` parameters.
