### ISSUE TITLE
opencv build fails with latest sdk in ubuntu 64 bit :   Android SDK Tools: OpenCV requires Android SDK Tools revision 14 or newer.

### ISSUE THREAD

**Issue by YounGCoder09** [opencv/opencv#18131]
-- Android SDK Build Tools: ver. 30.0.0-rc4 (subdir 30.0.0-rc4 from 30.0.0-rc4)
CMake Error at cmake/android/OpenCVDetectAndroidSDK.cmake:176 (message):
  Android SDK Tools: OpenCV requires Android SDK Tools revision 14 or newer.

  Use BUILD_ANDROID_PROJECTS=OFF to prepare Android project files without
  building them
Call Stack (most recent call first):
  CMakeLists.txt:780 (include)

related to : https://github.com/kivy/buildozer/issues/1144

**Comment by YounGCoder09** [comment]
@alalek its not incomplete nor needs further inverstigation , its trivial , you can check the workflow at https://github.com/tshirtman/test_p4a_opencv/actions/runs/214390204 , and you can see the same error

**Comment by tshirtman** [comment]
Seems this steems from outdated logic about gradle/ant build in the OpenCVDetectAndroidSDK.cmake file, trying with some more patching of the file in the recipe and to remove the tests and force gradle build.

**Comment by abhishekju06** [comment]
Can anyone please help? I am encountering the exact same error and struggling with 4 days now

**Comment by snuq** [comment]
Also struggling with this issue, really dont understand where to even start looking for a solution or fix... any help would be appreciated

**Comment by alalek** [comment]
OpenCV is not tested and probably doesn't support modern Android SDK/NDK versions. So try tools from 2018-2019 first.

Unfortunately, there are no active Android users in OpenCV development team.

If you are Android expert then feel free to contribute through Pull Requests.
Also investigation with follow-up comment with **the clear reason of the problem** is very useful.

---

BTW, there is an example of configuration output from validation builds on public CI:
```
-- Android SDK Tools: ver. 26.1.1 (description: 'Android SDK Tools')
-- Android SDK Build Tools: ver. 28.0.3 (subdir 28.0.3 from 28.0.3)
-- Android SDK Tools: Ant (Eclipse) builds are NOT supported by Android SDK
-- Android SDK Build Tools: Gradle 3.0.0+ builds support is available
-- Android SDK Tools: Prepare Android projects for using Gradle 3.0.0+ build scripts
-- Android Gradle Plugin version: 3.2.1

...

--   Android NDK:                   /opt/android/android-ndk-r18b (ver 18.1.5063045)
--     Android ABI:                 armeabi-v7a
--     NDK toolchain:               arm-linux-androideabi-clang
--     STL type:                    c++_static
--     Native API level:            21
--   Android SDK:                   /opt/android/android-sdk.gradle (tools: 26.1.1 build tools: 28.0.3)
```

**Comment by vjeranc** [comment]
@alalek I tried it with the newest NDK and the only thing I needed to use was the `android.toolchain.cmake` supplied by the NDK. The one inside `platforms` directory does not work.

After that I just ran the apps on my phone and everything looked well.

**Comment by abhishekju06** [comment]
> @alalek I tried it with the newest NDK and the only thing I needed to use was the `android.toolchain.cmake` supplied by the NDK. The one inside `platforms` directory does not work.
> 
> After that I just ran the apps on my phone and everything looked well.

Can you please explain me the steps?
I need to do it  in android 9;API=28

**Comment by vjeranc** [comment]
@abhishekju06 I left a comment on the official forums [here](https://forum.opencv.org/t/run-samples-of-open-cv-in-android-studio/453/7?u=vjeranc).

**Comment by NguyenDuyKha** [comment]
Problem: Android SDK Tools not updated yet. Although Android SDK Build Tools already in high version. I think that .buildozer or sdkmanager has some problem so can't update. Try the following steps for manual installation:

Step 1: sudo apt update && sudo apt install android-sdk
Step 2: cp -i -R /usr/lib/android-sdk/tools/ ~/.buildozer/android/platform/android-sdk/tools/ 

(Replaceable /usr/lib/android-sdk/tools/  to  /home/AccountName/Android/Sdk or  /usr/lib/android-sdk or  /Library/Android/sdk/ or    /Users/[USER]/Library/Android/sdk )

Step 3: Delete folder .buildozer and bin in folder your project
Step 4: buildozer -v android debug

**Comment by widiba03304** [comment]
Setting -DANDROID_SDK_TOOLS_VERSION=... might help

**Comment by asmorkalov** [comment]
Fixed in https://github.com/opencv/opencv/pull/21736
