### ISSUE TITLE
AgeGender 

### ISSUE THREAD

**Issue by shersoni610** [opencv/opencv#18137]
Hello, 

I used AgeRender software available in OpenCV. It seems that Gender identification is 40-45% correct but 
the age identification is completely unacceptable ( less than 10% within an acceptable range). 

For example (forgive me for the age discrimination, but it is only academic in nature), the person may be above 60+ age.
Many persons also determined to be 10-20 old even if they may be seniors( they will be happy with OpenCV) 

![image](https://user-images.githubusercontent.com/57876250/90694498-90dc8c00-e22d-11ea-9e3e-5c2c91a8e8d6.png)

Should I checkout different pre-trained models? 

Thanks.

**Comment by dkurt** [comment]
Please do not use GitHub issues for usage questions. There are https://answers.opencv.org/ and StackOverflow
