### ISSUE TITLE
People Detect

### ISSUE THREAD

**Issue by shersoni610** [opencv/opencv#18138]
Hello,

Can someone help to set the correct parameters for the PeopleDetect.cpp code.  I expected 11 bounding boxes, one for
each person. However, I get a few boxes which are incorrect also.

Thanks,

![image](https://user-images.githubusercontent.com/57876250/90705934-e83c2580-e248-11ea-8507-65013780d860.png)

**Comment by dkurt** [comment]
Please do not use GitHub issues for usage questions. There are https://answers.opencv.org/ and StackOverflow
