### ISSUE TITLE
No packages found during cmake process

### ISSUE THREAD

**Issue by chargerKong** [opencv/opencv#18159]
- OpenCV = 4.4.0
- Operating System / Platform => ubuntu 18.04

##### Detailed description

I want to install opencv, and during the cmake process, I saw some problems (some packages was not found), 
```shell
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'libavresample'
--   No package 'libavresample' found
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
```

but the cmake process did not stop, and  finally it displayed 
```shell
-- Configuring done
-- Generating done
```

I tried some examples and found that no errors occurred. I want to know what effect these things will have on me? Will the error be reported only when I use related things in the future?

**Comment by asmorkalov** [comment]
GStreamer, FFmpeg and a lot of other dependencies optional and OpenCV can be built without it. As soon as generating done you can continue and build OpenCV.

**Comment by asmorkalov** [comment]
OpenCV will try to use other backend for video handling or raise exception if nothing found.
