### ISSUE TITLE
Can't create layer "234" of type "Pow" in function 'getLayerInstance'

### ISSUE THREAD

**Issue by fengfengcxf** [opencv/opencv#18179]
When i used opencv-dnn loading onnx model. there was a problem that "Can't create layer "234" of type "Pow" in function 'getLayerInstance'". could you please tell me how to solve this?

**Comment by l-bat** [comment]
Please provide the code for generating the ONNX model

**Comment by fengfengcxf** [comment]
![image](https://user-images.githubusercontent.com/68675033/91009013-33bc4e00-e612-11ea-8dfd-4161edd7843f.png)

**Comment by fengfengcxf** [comment]
and i got the pow layer just like this
![image](https://user-images.githubusercontent.com/68675033/91009467-38353680-e613-11ea-8ba3-abaad19c18f7.png)

**Comment by l-bat** [comment]
Could you please provide corresponding PyTorch code? We need to generate test data such as https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/onnx/generate_onnx_models.py#L721 to support "Pow" operation.

**Comment by fengfengcxf** [comment]
it seems because of the GeneralizedMeanPooling which was used in pooling layer.

**Comment by fengfengcxf** [comment]
class GeneralizedMeanPooling(nn.Module):
    r"""Applies a 2D power-average adaptive pooling over an input signal composed of several input planes.
    The function computed is: :math:`f(X) = pow(sum(pow(X, p)), 1/p)`
        - At p = infinity, one gets Max Pooling
        - At p = 1, one gets Average Pooling
    The output is of size H x W, for any input size.
    The number of output features is equal to the number of input planes.
    Args:
        output_size: the target output size of the image of the form H x W.
                     Can be a tuple (H, W) or a single H for a square image H x H
                     H and W can be either a ``int``, or ``None`` which means the size will
                     be the same as that of the input.
    """

    def __init__(self, norm, output_size=1, eps=1e-6):
        super(GeneralizedMeanPooling, self).__init__()
        assert norm > 0
        self.p = float(norm)
        self.output_size = output_size
        self.eps = eps

    def forward(self, x):
        x = x.clamp(min=self.eps).pow(self.p)
        return torch.nn.functional.adaptive_avg_pool2d(x, self.output_size).pow(1. / self.p)

    def __repr__(self):
        return self.__class__.__name__ + '(' \
               + str(self.p) + ', ' \
               + 'output_size=' + str(self.output_size) + ')'

**Comment by fengfengcxf** [comment]
class GeneralizedMeanPooling(nn.Module):
    def __init__(self, norm, output_size=1, eps=1e-6):
        super(GeneralizedMeanPooling, self).__init__()
        assert norm > 0
        self.p = float(norm)
        self.output_size = output_size
        self.eps = eps

    def forward(self, x):
        x = x.clamp(min=self.eps).pow(self.p)
        return torch.nn.functional.adaptive_avg_pool2d(x, self.output_size).pow(1. / self.p)

    def __repr__(self):
        return self.__class__.__name__ + '(' \
               + str(self.p) + ', ' \
               + 'output_size=' + str(self.output_size) + ')'

**Comment by fengfengcxf** [comment]
class GeneralizedMeanPooling(nn.Module):

    r"""Applies a 2D power-average adaptive pooling over an input signal composed of several input planes.
    The function computed is: :math:`f(X) = pow(sum(pow(X, p)), 1/p)`
        - At p = infinity, one gets Max Pooling
        - At p = 1, one gets Average Pooling
    The output is of size H x W, for any input size.
    The number of output features is equal to the number of input planes.
    Args:
        output_size: the target output size of the image of the form H x W.
                     Can be a tuple (H, W) or a single H for a square image H x H
                     H and W can be either a ``int``, or ``None`` which means the size will
                     be the same as that of the input.
    """

    def __init__(self, norm, output_size=1, eps=1e-6):
        super(GeneralizedMeanPooling, self).__init__()
        assert norm > 0
        self.p = float(norm)
        self.output_size = output_size
        self.eps = eps

    def forward(self, x):
        x = x.clamp(min=self.eps).pow(self.p)
        return torch.nn.functional.adaptive_avg_pool2d(x, self.output_size).pow(1. / self.p)

    def __repr__(self):
        return self.__class__.__name__ + '(' \
               + str(self.p) + ', ' \
               + 'output_size=' + str(self.output_size) + ')'

**Comment by fengfengcxf** [comment]
thanks for your excellent help, besides, which version of opencv you have just experimented right now. For i must use your opencv version of 4.4, wether it was the seem solution......sincerely waitting for your reply.

**Comment by l-bat** [comment]
I experiment with 3.4 branch. These PR changes will be merged into master branch (4.x) next week. You can cherry-pick PR changes to your branch.

**Comment by fengfengcxf** [comment]
when i changes the pow op, it occurs another problem, do you have meet this?

modules/dnn/src/dnn.cpp (3436) getLayerShapesRecursively OPENCV/DNN: [Reshape]:(output): getMemoryShapes() throws exception. inputs=1 outputs=1/0 blobs=0

**Comment by fengfengcxf** [comment]
it seems work well ,thank you very much
