### ISSUE TITLE
OpenGL Support

### ISSUE THREAD

**Issue by shersoni610** [opencv/opencv#18170]
Hello 

while compiling OpenCV 4.4.0 on Ubuntu 18.04 I used WITH_OPENGL=ON. However, when compile
some of the Cuda codes I get the following error:

 The library is compiled without OpenGL support in function 'throw_no_ogl'

Am I missing linking some libraries> 
Thanks

**Comment by dkurt** [comment]
Please include cmake flags. Otherwise we will close an issue wuthout a reproducer.

**Comment by ebachard** [comment]
Hello, I recently compiled 3.4.11 (completely broken on Linux BTW, thanks to the sorcerer), and reading the CMakefile.txt file, there are some other flags to add in the cmake command line:

-   -DWITH_OPENGL=ON -DHAVE_OPENGL=ON  
-  and if you want glx version (means not the legacy OpenGL, don'tforget to add : -DOpenGL_GL_PREFERENCE=GLVND

It worked for me ;-)
