### ISSUE TITLE
'forward' method of cv2::dnn::net crashes during a test

### ISSUE THREAD

**Issue by MBSadeghzadeh** [opencv/opencv#18174]
I compiled OpenCV with CUDA by Visual Studio 2015 in Release mode successfully. Everything went well during building process and i added all libraries to a Qt project. When i set _PreferableBackend_ and _PreferableTarget_ to _cv::dnn::DNN_BACKEND_CUDA_ and _cv::dnn::DNN_TARGET_CUDA_ respectively, application crashes at _net.forward()_ and Qt writes _'The program has unexpectedly finished'_ to the output, though everything goes well by removing _PreferableBackend_ and _PreferableTarget_ .

**Comment by dkurt** [comment]
Closing unless there are all the steps to reproduce an issue and descriptions with HW and drivers info

**Comment by MBSadeghzadeh** [comment]
I followed all steps in this [tutorial](youtube.com/watch?v=TT3_dlPL4vo).
I also downloaded cuDNN from [here](https://developer.nvidia.com/cudnn-download-survey) and copied its content into _C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0_

**OS** 

- windows 10 Home, 64bit

**HW info are as follow:**

- Graphic card: Geforce GTX 1660Ti

- CUDA Cores: 1536

- Driver Version: 442.23

- Nvidia Cuda Toolkit.11.0.3_451.82.Windows.10

**Build System**

- Visual Studio 2015

- CMake


**Part of pro file of my Qt project**

win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_core440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_highgui440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_imgcodecs440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_imgproc440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_features2d440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_calib3d440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_videoio440
win32: LIBS += -L'D:/opencv/build_msvc/install/x64/vc14/lib/' -lopencv_dnn440

INCLUDEPATH += 'D:/opencv/build_msvc/install/include'
DEPENDPATH  += 'D:/opencv/build_msvc/install/include'

**Comment by dkurt** [comment]
Which version of OpenCV is used? Can you specify commit hash?

**Comment by MBSadeghzadeh** [comment]
Dowloaded the latest version from [here](https://sourceforge.net/projects/opencvlibrary/)

**Comment by dkurt** [comment]
Please add a code snippet as a reproducer. Do not make users to watch entire video tutorial.
