### ISSUE TITLE
[Opencv.js] The output of style transfer example contains weird points

### ISSUE THREAD

**Issue by akineeic** [opencv/opencv#18175]
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => ubuntu 18.04 64bit
- Compiler => Google Chrome | 84.0.4147.105 (Official Build) (64-bit)

##### Detailed description
I'm trying to write style transfer example with Opencv.js. The model is from the [repo](https://github.com/jcjohnson/fast-neural-style). But the output of the model contains some weird points as follows. I'm wondering do you have any idea how those points come from or how to  eliminate them.
![style_transfer](https://user-images.githubusercontent.com/44738552/90983366-35e5c480-e5a0-11ea-8e65-ba392542fa51.png)

**Comment by dkurt** [comment]
Hi!

You need to clamp output values to `[0, 255]`. Read an article https://opencv.org/opencv4arts-draw-my-city-vincent/ and

**Comment by akineeic** [comment]
I use function `matFromArray` and set the type to `CV_8UC4`, so the output values seem to be the range of `[0, 255]`.

**Comment by Happy0Ending** [comment]
I find the value of the function  postProcess's list [normData]   is greater than 255, I have to change these values to 255.The output image looks good
