### ISSUE TITLE
BUG: NAN-Values in createCalibrateRobertson()

### ISSUE THREAD

**Issue by suahelen** [opencv/opencv#18180]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio Code 
- Python => 3.7.7

##### Detailed description

I'am Trying to generate an HDR image with the help of the Robertson HDR algorithm. When trying to get the Camera Response function via cv2.createCalibrateRobertson() the function returns a list containing NAN-vals. If I set max_iter = 1 I get something similar to this (depending on images):
[[[0.01159891 0.00623508 0.01153401]]
 [[0.01882304 0.01189755 0.01737712]]
.
.
.
 [[2.459257   2.8999877  2.8891199 ]]
 [[       nan        nan        nan]]]

If I use only one Image, I always get NAN in the first and last row.

If I use multiple images with max_iter > 1 I get only NAN values returned. 

Different thresholds were also tested. 

I made sure that the images and the exposure times correspond correctly. Additionally I tried the same with the Debevec method, which worked flawlessly. 

Interestingly the calibration step works in the EMGU.cv wrapper. I'm not sure which Version is used in this Framework. 

##### Steps to reproduce
This is the code that was used. 
```python
times = np.array([0.001, 0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.249], dtype=np.float32)
img_list = []
for name in names:
    img = cv2.imread(str(name))
    img_list.append(img)

cal_robertson = cv2.createCalibrateRobertson(max_iter=1, threshold=0.01)
crf_robertson = cal_robertson.process(img_list, times=times.copy())
```

**Comment by suahelen** [comment]
I was informed, that the EMGU.CV version used in the C# framework is 3.4 . On a separate system where EMGU.CV 4.3 was used the same issue could be detected.

**Comment by alalek** [comment]
Please make code reproducible - attach missed images or replace them with `np.zeros()` with proper parameters.

**Comment by suahelen** [comment]
here is a version of the code with a set of images attached

```python
import cv2
import numpy as np
from pathlib import Path

directory = Path(r"C:\Users\Lab_user\Downloads\images")

times = np.array([15, 2.5, 0.25, 0.333333], dtype=np.float32)
max_iter = 10

img_list = []
for img in directory.glob("*.jpg"):
    img_list.append(cv2.imread(str(img)))

cal = cv2.createCalibrateRobertson(max_iter, 0.01)
crf = cal.process(img_list, times=times.copy())

print(crf)

```
[images.zip](https://github.com/opencv/opencv/files/5125021/images.zip)

**Comment by asmorkalov** [comment]
Reproduced with Ubuntu 18.04 and OpenCV master (4.5.1+).

**Comment by vovka643** [comment]
System information (version)
OpenCV => 4.7.0
Operating System / Platform = Windows 8.1 64 Bit
Python => 3.8

Everything work fine. There is no Nan values in output arrays of cv2.createCalibrateRobertson() function.
