### ISSUE TITLE
I tried writing a face recognition program and it keeps freezing on me even though it reads my face .i don"t understand anymore.  help please!!! 

### ISSUE THREAD

**Issue by vanceazer** [opencv/opencv#18188]
#import face_recognition as fr
import os
import cv2
import numpy

# getting images from folder
path = "filez"

TOLERANCE = 0.5
FRAME_THICKNESS = 3
FONT_THICKNESS = 2
MODEL = "cnn"

video = cv2.VideoCapture(0)

print("loading known faces")

known_faces = []
known_names = []

for name in os.listdir(path):
   

   image = fr.load_image_file(f"{path}/{name}")
   encoding = fr.face_encodings(image)[0]
   known_faces.append(encoding)
   known_names.append(name)

while True:
    ret, image = video.read()
  

    locations = fr.face_locations(image, model=MODEL)
    encodings = fr.face_encodings(image, locations)
  

    for face_encoding, face_location in zip(encodings, locations):
        results = fr.compare_faces(known_faces, face_encoding, TOLERANCE)
        match = None
        if True in results:
            match = known_names[results.index(True)]
            print(f"Match found: {match}")
            top_left = (face_location[3], face_location[0])
            bottom_right = (face_location[1], face_location[2])
            color = [0, 255, 0]
            cv2.rectangle(image, top_left, bottom_right, color, FRAME_THICKNESS)

            top_left = (face_location[3], face_location[2])
            bottom_right = (face_location[1], face_location[2] + 22)
            cv2.rectangle(image, top_left, bottom_right, color, cv2.FILLED)
            cv2.putText(image, match, (face_location[3] + 10, face_location[2] + 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                        (200, 200, 200), 1)

    cv2.imshow("image", image)

    if cv2.waitKey(1) & 0xFF == ord('q'):
       break

#video_capture.release()
cv2.destroyAllWindows()

**Comment by dkurt** [comment]
Code is not reproducible.

This is a bug tracker forum. For usage questions, please use https://answers.opencv.org/questions/ or StackOverflow.
