### ISSUE TITLE
Reshape Layer: Assertion failed dstTotal != 0 in function 'computeShapeByReshapeMask'

### ISSUE THREAD

**Issue by r0l1** [opencv/opencv#18209]
##### System information (version)
- OpenCV => 4.4.0
- Operating System / Platform => Arch 64 Bit
- Compiler => GCC 10.2.0

##### Detailed description

Loading the following ONNX model causes OpenCV to fail with:
```
cv2.error: OpenCV(4.4.0) /build/opencv/src/opencv-4.4.0/modules/dnn/src/layers/reshape_layer.cpp:149: error: (-215:Assertion failed) dstTotal != 0 in function 'computeShapeByReshapeMask'
```

##### Steps to reproduce

```python
import cv2
net=cv2.dnn.readNetFromONNX('model.onnx') 
```

The model is quite big. But I'll upload it if required.

Thanks in advance for some hints!

**Comment by r0l1** [comment]
@l-bat @dkurt any ideas how to apply a quick fix? Thanks!

**Comment by l-bat** [comment]
Please upload ONNX model to reproduce error

**Comment by r0l1** [comment]
Here you go: [model.onnx.txt](https://github.com/opencv/opencv/files/5149233/model.onnx.txt)

```python
import cv2
net=cv2.dnn.readNetFromONNX('model.onnx.txt') 
```

**Comment by r0l1** [comment]
@l-bat awesome! Thanks for the fast solution. Loading of the model works, but forwarding still fails.

```
[ERROR:0] global /tmp/opencv/opencv/modules/dnn/src/dnn.cpp (3433) getLayerShapesRecursively OPENCV/DNN: [Convolution]:(convolution_output6): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=2
[ERROR:0] global /tmp/opencv/opencv/modules/dnn/src/dnn.cpp (3439) getLayerShapesRecursively     input[0] = [ 1 17 1 17 ]
[ERROR:0] global /tmp/opencv/opencv/modules/dnn/src/dnn.cpp (3447) getLayerShapesRecursively     blobs[0] = CV_32FC1 [ 64 1 3 3 ]
[ERROR:0] global /tmp/opencv/opencv/modules/dnn/src/dnn.cpp (3447) getLayerShapesRecursively     blobs[1] = CV_32FC1 [ 64 1 ]
[ERROR:0] global /tmp/opencv/opencv/modules/dnn/src/dnn.cpp (3449) getLayerShapesRecursively Exception message: OpenCV(4.4.0-dev) /tmp/opencv/opencv/modules/dnn/src/layers/convolution_layer.cpp:353: error: (-215:Assertion failed) ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0 in function 'getMemoryShapes'
```

**Comment by l-bat** [comment]
@r0l1 please provide your code to run model

**Comment by r0l1** [comment]
@l-bat my bad. There was a problem with NCHW & NHWC ordering. Works just fine. Thanks!

**Comment by r0l1** [comment]
Thanks for merging :+1:

**Comment by dkurt** [comment]
@r0l1, thank you for a bug report.

**Comment by duongvvuet** [comment]
> @l-bat awesome! Thanks for the fast solution. Loading the model works, but forwarding still fails.

Can you step-by-step instructions? I'm a newbie, I want to load onnx model, but I have the same problem

**Comment by l-bat** [comment]
> Can you step-by-step instructions? I'm a newbie, I want to load onnx model, but I have the same problem

@duongvvuet Please upload ONNX model to reproduce error

**Comment by duongvvuet** [comment]
> > Can you step-by-step instructions? I'm a newbie, I want to load onnx model, but I have the same problem
> 
> @duongvvuet Please upload ONNX model to reproduce error

Thanks for your respone !
My ONNX model and code ...

[model.onnx.zip](https://github.com/opencv/opencv/files/5306767/model.onnx.zip)

```
import cv2
model = cv2.dnn.readNetFromONNX("model.onnx")
```

**Comment by l-bat** [comment]
@duongvvuet  To load onnx model correctly, you need to specify `img_w` in input shape when exporting model to onnx.

![image](https://user-images.githubusercontent.com/22346860/94771123-2b98c080-03bf-11eb-9cce-8254bff27274.png)

**Comment by duongvvuet** [comment]
@l-bat How to specify img_w in the input shape from onnx above? I don't have model before exporting model to onnx. :((

**Comment by l-bat** [comment]
@duongvvuet  Do you plan to use a model with different input shapes?

**Comment by duongvvuet** [comment]
@l-bat No, I will preprocess the input image with specified input shape.

**Comment by l-bat** [comment]
Try using this script to set input shapes.

```python
import onnx
import os
from onnx.tools import update_model_dims

# Preprocessing: load the old model
old_model_path = os.path.join('content', 'model.onnx')
onnx_model = onnx.load(old_model_path)

# Preprocessing: get the path to the saved model
new_model_path = os.path.join('content', 'new_model.onnx')

# Save the ONNX model
variable_length_model = update_model_dims.update_inputs_outputs_dims(onnx_model, {'input': ['batch', 3, 32, 32]}, {'out': [64, 1, 5531]})
onnx.save(onnx_model, new_model_path)
```

**Comment by duongvvuet** [comment]
@l-bat Thank you, but ... 

![Screenshot from 2020-10-01 15-39-42](https://user-images.githubusercontent.com/51939859/94787452-856bab80-03fc-11eb-8703-b2cab351caf6.png)

**Comment by duongvvuet** [comment]
@l-bat Sorry, I'm bad. Thank you so much .. !!
