### ISSUE TITLE
It can be used normally in onnxruntime, but an error is reported in OpenCV.

### ISSUE THREAD

**Issue by mcmingchang** [opencv/opencv#18206]
opencv-python 4.4
It can be used normally in onnxruntime, but an error is reported in OpenCV.

ocr_model = cv2.dnn.readNetFromONNX('ocr.onnx')
char_im = np.zeros((64,64,5))
ocr_model.setInput(np.transpose(np.expand_dims(char_im, axis=0), (0,3,1,2))/255)
ocr_model.forward(['660'])

error                                     Traceback (most recent call last)
<ipython-input-5-e1cba24af024> in <module>
----> 1 ocr_model.forward(['660'])
error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wbmte9m7\opencv\modules\dnn\include\opencv2/dnn/shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20200609::total'

**Comment by dkurt** [comment]
Please check supported models in sample: https://github.com/opencv/opencv/blob/master/samples/dnn/text_detection.cpp
