### ISSUE TITLE
Add STRUCK Tracker for GSOC 2021 ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [opencv/opencv#18218]
Isn't it time to add the best Tracker in [Visual Tracker Benchmark](http://cvlab.hanyang.ac.kr/tracker_benchmark/benchmark.html) in OpenCV ?

Open Source with GPL-3.0 License https://github.com/samhare/struck

**Comment by alalek** [comment]
GPL code is not compatible with OpenCV license.
Closing.
