### ISSUE TITLE
reprojectImageTo3D incorrect results

### ISSUE THREAD

**Issue by tonifds** [opencv/opencv#18219]
system: opencv 4.4.0
operating system: windows 10 Pro - visual studio 2019
PCL 1.11.1 point cloud viewer.

I use this example https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_match.cpp

int alg = STEREO_SGBM;
int SADWindowSize = 1;
int numberOfDisparities =16;

i get incorrect cloud point, any suggestions?

![image](https://user-images.githubusercontent.com/39823863/91631850-79e42980-e9e5-11ea-9948-9615daf32a31.png)

**Comment by asmorkalov** [comment]
@tonifds please ensure that you camera is calibrated correctly.

**Comment by tonifds** [comment]
@asmorkalov  stereocalibration RMS=0.76 < 1 .  it's correct or should do anythings else

**Comment by catree** [comment]
You should post the disparity image and upload the `.xyz` file (see the command line arguments of `stereo_match.cpp` to save the pointcloud to a file).

**Comment by tonifds** [comment]
1- image used from opencv example with stereo_calib.cpp (https://github.com/opencv/opencv/tree/master/samples/cpp , to get extrinsics.yml & intrinsics.yml

2- stereo_match.cpp (https://github.com/opencv/opencv/tree/master/samples/cpp) to generate point cloud and disparity map.

3-Stereobm argument:
    bm->setBlockSize(5);
    bm->setMinDisparity(0);
    bm->setNumDisparities(64);
    bm->setDisp12MaxDiff(-1); 
    bm->setSpeckleRange(0); 
    bm->setSpeckleWindowSize(0); 
    bm->setPreFilterCap(1); 
    bm->setPreFilterSize(5); 
    bm->setPreFilterType(StereoBM::PREFILTER_NORMALIZED_RESPONSE); 
    bm->setTextureThreshold(0); 
    bm->setUniquenessRatio(0); 

4- i get as results:
4.1-point cloud:  
[point_cloud.txt](https://github.com/opencv/opencv/files/5166394/point_cloud.txt)

4.2-disparitymap:
![image](https://user-images.githubusercontent.com/39823863/92075417-1bda8c00-edc1-11ea-901f-64c5d123e432.png)

4.3-leftimage:
![image](https://user-images.githubusercontent.com/39823863/92075457-33197980-edc1-11ea-863c-260af800bd88.png)

4.4-right image:
![image](https://user-images.githubusercontent.com/39823863/92075496-488ea380-edc1-11ea-8965-a61e743af569.png)

**Comment by alalek** [comment]
Stereo matching algorithms require textured objects (with unique patterns).

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
