### ISSUE TITLE
People Detect: Does it works?

### ISSUE THREAD

**Issue by shersoni610** [opencv/opencv#18222]
Hello,

I am trying to experiement with peopledetect.cpp code on ubuntu + OpenCV 4.4.0
I am gettting upexpected results, therefore, I have a few questions:

1.  How to make the code work? Are there parameters to change? 
2.  The results with yolov3/yolov3 are far more respectable, therefore, what are the
     advantages of using algorithms used in peopledetect.cpp?

Thanks

**Comment by SoheibKadi** [comment]
Hello,
Unless you're reporting a possible bug, I think you should ask your question here: https://answers.opencv.org/questions/

Thanks.
