### ISSUE TITLE
[ WARN:0] global /tmp/pip-req-build-sw_3pm_8/opencv/modules/dnn/src/dnn.cpp (1429) setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by yancccc** [opencv/opencv#18229]
[ WARN:0] global /tmp/pip-req-build-sw_3pm_8/opencv/modules/dnn/src/dnn.cpp (1429) setUpNet DNN module was not built with CUDA backend; switching to CPU

**Comment by yancccc** [comment]
It worked normally before, but not today

**Comment by yancccc** [comment]
net = cv2.dnn.readNet("yolov4.cfg", "yolov4.weights")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

**Comment by yancccc** [comment]
ycc@ycc:~/opencv$ python
Python 3.5.2 (default, Jul 17 2020, 14:04:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.4.0'
>>>

**Comment by yancccc** [comment]
@YashasSamaga

**Comment by YashasSamaga** [comment]
The CUDA backend wasn't enabled during build. Can you share your cmake command and cmake output?

**Comment by yancccc** [comment]
> The CUDA backend wasn't enabled during build. Please check your cmake command and cmake output.

Previously, opencv4.4gpu was able to run normally
I recompiled opencv4.4 again, and it still doesn't work

**Comment by yancccc** [comment]
@YashasSamaga 
cmake -DCMAKE_BUILD_TYPE=RELEASE \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.4.0/modules .. \
    -DWITH_CUDA=1 \
    -DWITH_CUDNN=1 \
    -DENABLE_FAST_MATH=1 \
    -DCUDA_FAST_MATH=1 \
    -DWITH_CUBLAS=1 \
    -DOPENCV_GENERATE_PKGCONFIG=1 \
    -DBUILD_opencv_dnn=1 \
    -DCUDA_GENERATION=Pascal ..

**Comment by YashasSamaga** [comment]
@yancccc add `-DOPENCV_DNN_CUDA` (you can find [build instructions here](https://gist.github.com/YashasSamaga/985071dc57885348bec072b4dc23824f))

**Comment by yancccc** [comment]
> @yancccc add `-DOPENCV_DNN_CUDA` (you can find [build instructions here](https://gist.github.com/YashasSamaga/985071dc57885348bec072b4dc23824f))
add -DOPENCV_DNN_CUDA    recompiling still doesn't work

**Comment by yancccc** [comment]
The problem has been solved
