### ISSUE TITLE
cv::VideoCapture read live video stream but can't discriminate fake urls

### ISSUE THREAD

**Issue by SunGaofeng** [opencv/opencv#18233]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => CentOS release 6.3
- Compiler => gcc82

##### Detailed description

I tried to read live video stream with OpenCV as following,

    cv::VideoCapture capture(video_url);

It can read from live video stream and works well. However, when a fake video_url was sent to it, such as an url of a txt file, for example,

    video_url = "http://127.0.0.10:8090/result.txt"

it can also decode data from this fake url. But I want it to return error information when the video_url is fake.

How can I make it to be able to discriminate whether an url is truly of a live video stream, or a txt web file?

**Comment by SunGaofeng** [comment]
I can also reproduce this with python-opencv

>>> import cv2
>>> cv2.__version__
'4.2.0'
>>> capture = cv2.VideoCapture('http://127.0.0.1:8090/testvideo.txt')
>>> ret, frame = capture.read()
>>> ret
True
>>> frame.shape
(400, 640, 3)
>>> capture.get(cv2.CAP_PROP_FPS)
25.0


The following is a screen shot of the txt file. It is just a simple file with about 100 lines.

![image](https://user-images.githubusercontent.com/26536764/91706125-85d01700-ebb0-11ea-82de-f3c2ddcbf9cc.png)

**Comment by alalek** [comment]
> video_url is fake

There is no strong definition for that.
You should check that in your application following own criteria.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
