### ISSUE TITLE
OpenCV4.4.0, building from source Error, and OpenVINO not opening video/camera

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#18238]
##### System information (version)

- OpenCV => 4.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
I am trying to build OpenCV from source but it throws a lot of errors details are [here](https://github.com/opencv/opencv/issues/17941).
The second, when I failed to build OpenCV from source then I tried to use the prebuilt OpenCV library of OpenVINO toolkit, but it also has the problem which cannot open videos (file/camera). It is the Error details:

```
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\videoio_registry.cpp (191) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (370) cv::impl::getPluginCandidates Found 3 plugin(s) for FFMPEG
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load C:\Program Files (x86)\IntelSWTools\openvino\opencv\bin\opencv_videoio_ffmpeg440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg440_64.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (370) cv::impl::getPluginCandidates Found 2 plugin(s) for GSTREAMER
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load C:\Program Files (x86)\IntelSWTools\openvino\opencv\bin\opencv_videoio_gstreamer440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_gstreamer440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (370) cv::impl::getPluginCandidates Found 2 plugin(s) for INTEL_MFX
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load C:\Program Files (x86)\IntelSWTools\openvino\opencv\bin\opencv_videoio_intel_mfx440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load opencv_videoio_intel_mfx440_64d.dll => FAILED
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (370) cv::impl::getPluginCandidates Found 2 plugin(s) for MSMF
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (175) cv::impl::DynamicLib::libraryLoad load C:\Program Files (x86)\IntelSWTools\openvino\opencv\bin\opencv_videoio_msmf440_64d.dll => OK
[ INFO:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (236) cv::impl::PluginBackend::PluginBackend Video I/O: loaded plugin 'Microsoft Media Foundation OpenCV Video I/O plugin'
[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\cap.cpp (161) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised unknown C++ exception!


[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\cap.cpp (161) cv::VideoCapture::open VIDEOIO(CV_MJPEG): raised unknown C++ exception!


[ INFO:1] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.4\build\windows\opencv\modules\videoio\src\backend_plugin.cpp (181) cv::impl::DynamicLib::libraryRelease unload C:\Program Files (x86)\IntelSWTools\openvino\opencv\bin\opencv_videoio_msmf440_64d.dll
Press <RETURN> to close this window...
```

How to overcome to these errors, please the solution, thanks!!

**NOTE:** I have installed the OpenVINO toolkit from scratch two times. And run the demos provided, it works, so it means it was installed correctly, the version I installed: 2020.4 (the latest till today)

**Comment by alalek** [comment]
Looks like there is problem with Debug binaries.
Please try Release mode first.

**Comment by Bahramudin** [comment]
@alalek I am directly run the release version. Before it was working well I am already familiar with OpenCV library and OpenVINO toolkit. But in the latest version there many errors with building from source or using the prebuilt library. It is very annoying wasting me days. 

Hope to find the solution.

**Comment by alalek** [comment]
> I am directly run the release version.

This is not true, because

> ...440_64d.dll

means that debug version of OpenCV binaries is used. Look on "d" suffix.

**Comment by Bahramudin** [comment]
@alalek Yes, you are right, now it is working, thanks for the providing solution!

Now I am getting a new problem, which it cannot open IP camera (RTSP Video Stream), I am able to open USB camera and Video file, but just cannot open the RTSP Stream. Before it was working well. It is the error it throws:

`MFX: Unsupported extension: rtsp://username:password@192.168.1.101:554/Streaming/Channels/102`

It will be better to build OpenCV from source by my self, I am still getting the [previous](https://github.com/opencv/opencv/issues/17941#issuecomment-684528241) Issue problem, anyway I hope to find a solution for that problem.

**Comment by alalek** [comment]
> open the RTSP Stream

FFmpeg plugin can do that.
OV package has a downloader for OpenCV community plugin.

See logged lines for details.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Bahramudin** [comment]
@alek should you give me a link to show self build the latest version of the OpenCV with OpenVINO toolkit, the previous method doesn’t work for the latest version. Gives many errors which I am not able to build a clean library with my own confirmation (OpenVINO + Extra module + GStreamer, etc). I did not find any documentation online to show this. 

Thanks in advance!

**Comment by Bahramudin** [comment]
Closing this issue, the solution was self build the OpenCV with OpenVINO supports.
