### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by i-akshat-jain** [opencv/opencv#18245]
### These are some issues i am facing while working with opencv, i do not know why !!! Can anyone please help me out why is this happening?

[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-2b5g8ysb\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File ".\FACE_RECOGNITION.py", line 44, in <module>
    img = cv2.resize(img, (imgWidth,imgHeight))
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-2b5g8ysb\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-2b5g8ysb\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File ".\FACE_RECOGNITION.py", line 47, in <module>
    resLap = cv2.Laplacian(img, cv2.CV_64F)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-2b5g8ysb\opencv\modules\imgproc\src\deriv.cpp:792: error: (-215:Assertion failed) !_src.empty() in function 'cv::Laplacian'

**Comment by linncountyjailroster** [comment]
resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize

I have the same issue, something to do with the specific web camera I am using, opencv isn't letting me interact with the webcam but works perfectly fine when I plug in other webcams.

**Comment by emontene** [comment]
i have the same issue. but only when Run or execute python.exe no administrator rights it not work.
