### ISSUE TITLE
Makefile:162: recipe for target 'all' failed

### ISSUE THREAD

**Issue by Shane555** [opencv/opencv#18252]
##### System information (version)

- OpenCV => 4.4.0 with contrib lib
- Operating System / Platform => Ubuntu 18.04 LTS
-Cmake 3.10.2

##### Detailed description
[ 35%] Linking CXX executable ../../bin/opencv_perf_core
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::GpuMat(cv::debug_build_guard::_InputArray const&, cv::cuda::GpuMat::Allocator*)':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:112: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::convertTo(cv::debug_build_guard::_OutputArray const&, int, double, double) const':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:188: undefined reference to `cv::cuda::GpuMat::convertTo(cv::debug_build_guard::_OutputArray const&, int, double, double, cv::cuda::Stream&) const'
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::GpuMat(cv::debug_build_guard::_InputArray const&, cv::cuda::GpuMat::Allocator*)':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:112: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:112: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::debug_build_guard::_InputArray const&)':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:176: undefined reference to `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::debug_build_guard::_InputArray const&, cv::cuda::Stream&)'
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::GpuMat(cv::debug_build_guard::_InputArray const&, cv::cuda::GpuMat::Allocator*)':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:112: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:112: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
CMakeFiles/opencv_perf_core.dir/perf/cuda/perf_gpumat.cpp.o: In function `cv::cuda::GpuMat::copyTo(cv::debug_build_guard::_OutputArray const&, cv::debug_build_guard::_InputArray const&) const':
/home/nvidia/Downloads/opencv-4.4.0/source/modules/core/include/opencv2/core/cuda.inl.hpp:164: undefined reference to `cv::cuda::GpuMat::copyTo(cv::debug_build_guard::_OutputArray const&, cv::debug_build_guard::_InputArray const&, cv::cuda::Stream&) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::cuda::GpuMat::download(cv::debug_build_guard::_OutputArray const&) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&, cv::cuda::Stream&)'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::cuda::GpuMat::download(cv::debug_build_guard::_OutputArray const&, cv::cuda::Stream&) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::_InputArray::getGpuMat() const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::cuda::GpuMat::copyTo(cv::debug_build_guard::_OutputArray const&) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::_OutputArray::create(cv::Size_<int>, int, int, bool, cv::_OutputArray::DepthMask) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::_InputArray::getMat_(int) const'
../../lib/libopencv_core.so.4.4.0: undefined reference to `cv::_InputArray::kind() const'
/usr/bin/ld generated: undefined reference to `cv::cuda::GpuMat::copyTo(cv::debug_build_guard::_OutputArray const&, cv::debug_build_guard::_InputArray const&, cv::cuda::Stream&) const'
/usr/bin/ld generated: undefined reference to `cv::cuda::GpuMat::setTo(cv::Scalar_<double>, cv::debug_build_guard::_InputArray const&, cv::cuda::Stream&)'
/usr/bin/ld generated: undefined reference to `cv::cuda::GpuMat::upload(cv::debug_build_guard::_InputArray const&)'
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_perf_core.dir/build.make:882: recipe for target 'bin/opencv_perf_core' failed
make[2]: *** [bin/opencv_perf_core] Error 1
CMakeFiles/Makefile2:3049: recipe for target 'modules/core/CMakeFiles/opencv_perf_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

##### Steps to reproduce

Detected processor: aarch64
Looking for ccache - not found
Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1)
Could NOT find Jasper (missing: JASPER_LIBRARIES JASPER_INCLUDE_DIR) 
Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.11") 
CUDA detected: 10.0
CUDA: Using CUDA_ARCH_BIN=6.2
CUDA NVCC target flags: -gencode;arch=compute_62,code=sm_62;-D_FORCE_INLINES
LAPACK(Atlas): LAPACK_LIBRARIES: /usr/lib/aarch64-linux-gnu/liblapack.so;/usr/lib/aarch64-linux-gnu/libcblas.so;/usr/lib/aarch64-linux-gnu/libatlas.so
LAPACK(Atlas): Support is enabled.
Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
OpenCV Python: during development append to PYTHONPATH: /home/nvidia/Downloads/opencv-4.4.0/build/python_loader
Caffe:   NO
Protobuf:   NO
Glog:   NO
freetype2:   YES (ver 21.0.15)
harfbuzz:    YES (ver 1.7.2)
HDF5: Using hdf5 compiler wrapper to determine C configuration
Julia not found. Not compiling Julia Bindings. 
Module opencv_ovis disabled because OGRE3D was not found
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
Failed to find gflags - Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags
Checking for module 'tesseract'
  No package 'tesseract' found
Tesseract:   NO
Allocator metrics storage type: 'int'
HDF5: Using hdf5 compiler wrapper to determine C configuration
Excluding from source files list: modules/imgproc/src/corner.avx.cpp
Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
Excluding from source files list: modules/imgproc/src/imgwarp.sse4_1.cpp
Excluding from source files list: modules/imgproc/src/resize.avx2.cpp
Excluding from source files list: modules/imgproc/src/resize.sse4_1.cpp
Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': /home/nvidia/Downloads/opencv-4.4.0/source/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx.cpp
Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx2.cpp
Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx512_skx.cpp
Excluding from source files list: modules/features2d/src/fast.avx2.cpp

General configuration for OpenCV 4.4.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /home/nvidia/Downloads/opencv_contrib-master/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2020-08-19T02:28:06Z
    Host:                        Linux 4.9.140-tegra aarch64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    NEON FP16
      required:                  NEON
      disabled:                  VFPV3

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -g1
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG -g1
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--gc-sections -Wl,--as-needed  
    Linker flags (Debug):        -Wl,--gc-sections -Wl,--as-needed  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static -lpthread dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/aarch64-linux-gnu
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 alphamat aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj java js julia matlab ovis python2 sfm viz
    Applications:                perf_tests apps
    Documentation:               NO
    Non-free algorithms:         NO

  GUI: 
    QT:                          YES (ver 5.9.5)
      QT OpenGL support:         NO
    GTK+:                        NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/aarch64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/aarch64-linux-gnu/libjpeg.so (ver 80)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         /usr/lib/aarch64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/aarch64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   build Jasper (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      YES (2.2.5)
    FFMPEG:                      YES
      avcodec:                   YES (57.107.100)
      avformat:                  YES (57.83.100)
      avutil:                    YES (55.78.100)
      swscale:                   YES (4.8.100)
      avresample:                YES (3.7.0)
    GStreamer:                   YES (1.14.5)
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      YES (/usr/lib/aarch64-linux-gnu/liblapack.so /usr/lib/aarch64-linux-gnu/libcblas.so /usr/lib/aarch64-linux-gnu/libatlas.so)
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  YES (carotene (ver 0.0.1))
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS)
    NVIDIA GPU arch:             62
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 7.6.3)

  OpenCL:                        YES (no extra features)
    Include path:                /home/nvidia/Downloads/opencv-4.4.0/source/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /usr/bin/python3 (ver 3.6.9)
    Libraries:                   /usr/lib/aarch64-linux-gnu/libpython3.6m.so (ver 3.6.9)
    numpy:                       /usr/local/lib/python3.6/dist-packages/numpy/core/include (ver 1.19.0)
    install path:                lib/python3.6/dist-packages/cv2/python-3.6

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /usr/local
-----------------------------------------------------------------

Configuring done
Generating done

**Comment by alalek** [comment]
> debug_build_guard

You should dig in this direction.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Shane555** [comment]
@alalek Alright. On a side note do you know what the flags BUILD_WITH_DEBUG_INFO and ENABLE_GNU_STL_DEBUG do? I suspect they are the problem that is causing this build error
