### ISSUE TITLE
Different weights for dnn's face detector

### ISSUE THREAD

**Issue by SantiHM23** [opencv/opencv#18264]
Hi all,

I am playing with the face detector code, but I have some bad results when it comes to faces that have a small size in the image because they are far from the source. In [this article](https://towardsdatascience.com/face-detection-models-which-to-use-and-why-d263e82c302c) i read that this issue can be improved by passing as input to the "blobFromImage" function the original size of the image, instead of resizing it to 300x300.

My problem when doing this is that, at the time of getting back the predictions, in some cases they have values greater than 1, so it overflows the image's dimension. Because of the link I previously mentioned, I was wondering if there are other weights anywhere that are not the "res10_300x300_ssd_iter_140000.caffemodel", as I understand this have been trained for working with 300x300 images. Do these weights exist anywhere else? Is there anything else that I should modify instead of using another pretrained weights? Or anything else that I am missing?

Thank you for enlightening me.

**Comment by rafale77** [comment]
I have experimented with a pretty large number of pretrained face detectors, including this one.
Between the ones included in dlib, this one, mtcnn and retinaface, I ended concluding that the resnet10 opencv caffe model is by far the fastest one but also the least reliable one. I tested a "training set" for recognition (which is another model) using the detector as the first stage and found out that this model is the only one which either fails to detect faces or finds too many. All the other ones: dlib's dnn, mtcnn and retinaface running on pytorch detects only the one face on the picture.

**Comment by dkurt** [comment]
> as I understand this have been trained for working with 300x300 images

you may run the model on higher input resolution. Take a look at https://answers.opencv.org/question/202995/dnn-module-face-detection-poor-results-open-cv-343/#202999

**Comment by SantiHM23** [comment]
> 
> 
> > as I understand this have been trained for working with 300x300 images
> 
> you may run the model on higher input resolution. Take a look at https://answers.opencv.org/question/202995/dnn-module-face-detection-poor-results-open-cv-343/#202999

Hi! Yes, that is what I was doing, but when making the detections, this is, when running the 
`cv::Mat detection = net.forward("detection_out");`
line in the code above, in some cases the detections retrieved have values over 1, including top-left corner of the detection. Therefore, the bounding box that would correspond to the detection is completely out of the image, and it throws an error.
Is there any way to avoid this happening? I thought it may be using some pretrained weight that hadn't resized the image to 300x300, but it is true that it works fine when the detections don't exceed the image's original size.

Thank you

**Comment by dkurt** [comment]
@SantiHM23, just do `max(0, min(x, 1))` or open `.prototxt` and specify `clip: 1`:

https://github.com/opencv/opencv_extra/blob/80ae3bbb7223dd6617cce19e14d3058ae7f9ae1c/testdata/dnn/opencv_face_detector.prototxt#L1788

**Comment by SantiHM23** [comment]
@dkurt thank you very much, it worked. I guess I was looking for a too complicated solution :D may I ask why the net makes some detections "outside" the image? is there any reason for that happening? For example, I found that mostly my problem with this came when at least one of the images dimensions was over 1000 pixels, but I am not able to tell if that may be a real problem, or it was just chance.

**Comment by dkurt** [comment]
SSD networks generate set of base bounding boxes (prior boxes or anchors). Then, one of the branches predicts scales for this boxes. See DetectionOutput layer:

https://github.com/opencv/opencv/blob/e421233a1d763c1e9f12271f0de2208ba26329a6/modules/dnn/src/layers/detection_output_layer.cpp#L697-L719

**Comment by SantiHM23** [comment]
Hi again, and sorry for the insistence. I have come across another problem when using the full size image. Independently if I run the code on a series of random images or the input from a webcam, there is something weird happening. The detection for the first image/frame is good and normal, but for the following ones it starts to become crazy and output like 100 detections even if there is only one person in the image. 
But if I run the code for each image separately, this is, running the code for one image, finishing and then starting over for another image, instead of running the code once for all the images, the detections are correct.
Most of the retrieved detections have this problem I mentioned before, about having its coordinates "outside" of the image. I am even deleting the variable values after each iteration, but that does not seem to solve the problem. Is there anything I am missing that is causing this problem? 
This does not happen when I resize the images to 300x300, but I am trying to avoid that because faces that are far from the camera are not well detected, and I guess there should be a way to make it work properly with full size images.

**Comment by dkurt** [comment]
@SantiHM23, please do not use GitHub issues for usage questions - most probably there is a bug in your code.

**Comment by manishagate** [comment]
@SantiHM23 

> Hi again, and sorry for the insistence. I have come across another problem when using the full size image. Independently if I run the code on a series of random images or the input from a webcam, there is something weird happening. The detection for the first image/frame is good and normal, but for the following ones it starts to become crazy and output like 100 detections even if there is only one person in the image.
> But if I run the code for each image separately, this is, running the code for one image, finishing and then starting over for another image, instead of running the code once for all the images, the detections are correct.
> Most of the retrieved detections have this problem I mentioned before, about having its coordinates "outside" of the image. I am even deleting the variable values after each iteration, but that does not seem to solve the problem. Is there anything I am missing that is causing this problem?
> This does not happen when I resize the images to 300x300, but I am trying to avoid that because faces that are far from the camera are not well detected, and I guess there should be a way to make it work properly with full size images.

Hi, I'm experiencing same issue. Did you find any solution?
