### ISSUE TITLE
Eye detection with facemask (COVID)

### ISSUE THREAD

**Issue by eyanson** [opencv/opencv#18266]
I´m using "haarcascade_eye.xml" to detect eyes but when I put the facemask for COVID, detection not work properly.
Can you send me a pattern for this ????

Thanks !

**Comment by Shreerama9** [comment]
While putting facemask , detection not working properly ... Can u elaborate please like its not detecting anything or just eye's, etc.
And if can share .xml file that will make things easy.

**Comment by eyanson** [comment]
I try to explain better (my english is not good)

I'm use two XMLs in my project:
This for detect eyes: https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_eye.xml
And this for detect face: https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml

All works fine, but when I put the mask on my face, the detection of face not work and the detection of ayes is not good.
I would like an xml adapted to detect eyes in a face with mask.

Here there are two videos.
Without mask: https://www.youtube.com/watch?v=O8-wyq8ngbE&feature=youtu.be
with mask: https://www.youtube.com/watch?v=Z99ofB_rbbs&feature=youtu.be

The question are:
a) Can anybody create an XML for this situation?
b) Can anybody help me with generate an XML for this situation?

Thanks in advance, again sorry by my bad english.
