### ISSUE TITLE
Better support for Swift native array types

### ISSUE THREAD

**Issue by komakai** [opencv/opencv#18269]
##### System information (version)
- OpenCV => latest
- Operating System / Platform => macOS/iOS
- Compiler => Xcode

##### Detailed description

Currently when passing in/out array parameters to functions in Swift we have to use legacy type `NSMutableArray`. The array type gets erased in the Swift/Objective-C bridge so we end up with code like:
```
let contoursTmp = NSMutableArray()
Imgproc.findContours(image: dilatedMask, contours: contoursTmp, hierarchy: hierarchy, mode: .RETR_EXTERNAL, method: .CHAIN_APPROX_SIMPLE)
for contour in contoursTmp {
   let contourMat = MatOfPoint(array: (contour as! NSMutableArray) as! [Point])   //  <-  lots of messy casts
}
```

To fix this we need to add Swift extensions to wrap functions with in/out array parameters so instead we can call like this:
```
var contoursTmp = [[Point]]()
Imgproc.findContours(image: dilatedMask, contours: &contoursTmp, hierarchy: hierarchy, mode: .RETR_EXTERNAL, method: .CHAIN_APPROX_SIMPLE)
for contour in contoursTmp {
    let contourMat = MatOfPoint(array: contour)
}
```

(I have a PR for this)

##### Issue submission checklist
 - [x] I report the issue, it's not a question

**Comment by AlvarHHM** [comment]
Is there a reason why `pointPolygonTest` accept `Point2f` instead of `Point` like all other contours related function?

**Comment by komakai** [comment]
@AlvarHHM  In `modules/imgproc/src/geometry.cpp` the corresponding C++ function has definition:
```
double cv::pointPolygonTest( InputArray _contour, Point2f pt, bool measureDist )
```

**Comment by komakai** [comment]
@alalek PR #18270 resolves this issue so I will close it
