### ISSUE TITLE
Bug in imwrite w/ 16bit JPEG2000

### ISSUE THREAD

**Issue by benlcb** [opencv/opencv#18263]
### General Info
This is a bug that was fixed in C++ OpenCV (after version 2.4.6.1) about 5 years ago: 
https://github.com/opencv/opencv/pull/6417/files
https://answers.opencv.org/question/92899/writing-jpeg-2000-images-with-16-bit/

Since opencv-python 4.4.0.42 is build on a much newer version of OpenCV, I don't understand why it still exists now in the python wrapper. 

### Expected behaviour

`cv2.imwrite(dst_file, pixel_array, [cv2.IMWRITE_JPEG2000_COMPRESSION_X1000, 1000])`
`pixel_array` is a uint16 array. 

The image in pixel_array should be written to a 16-bit JPEG2000 file.

### Actual behaviour

The resulting JPEG2000 image has a bit debth of 8 bit and is completely black.

### Steps to reproduce

Create an image represented in a single-channel uint16 array.
Set Environment Variable `OPENCV_IO_ENABLE_JASPER=True`
Call imwrite like: `cv2.imwrite(dst_file, pixel_array, [cv2.IMWRITE_JPEG2000_COMPRESSION_X1000, 1000])`

opencv-python Version: 4.4.0.42

Reference: https://github.com/skvark/opencv-python/issues/384

**Comment by alalek** [comment]
As there is no corresponding 16U test, marking this as a feature.

BTW, OpenCV is migrating on OpenJPEG decoder/encoder (instead of Jasper).

**Comment by rogday** [comment]
Hello, @benlcb. I failed to reproduce your issue using opencv master and opencv 4.4.0.42. Could you provide a MWE?

I built opencv master branch with OpenJPEG and another one with JasPer (`-DWITH_OPENJPEG=OFF`) and the following test passed successfully, producing 16-bit image [test.zip](https://github.com/opencv/opencv/files/6467746/test.zip). 

```
import cv2
import numpy as np

filename = 'test.jp2'  # not jpeg here
pixel_array = np.random.randint(
    low=0, high=2**16-1, size=(100, 100, 1), dtype=np.uint16)

cv2.imwrite(filename, pixel_array, [
            cv2.IMWRITE_JPEG2000_COMPRESSION_X1000, 1000])

mat = cv2.imread(filename, cv2.IMREAD_ANYDEPTH)

assert mat.dtype == np.uint16, "Type mismatch"

```

**Comment by asmorkalov** [comment]
Closed, not reproducible any more.
