### ISSUE TITLE
opencv cuda in win10 LNK2019

### ISSUE THREAD

**Issue by miziha-zp** [opencv/opencv#18276]
##### System information (version)

- OpenCV => :grey_question:4.1
- Operating System / Platform => :grey_question:Win10 64 Bit
- Compiler => :grey_question:  Visual Studio 2017

##### Steps to reproduce
1. when I use the prebuild opencv library downloaded from opencv.org the followed code can run well,but when I build opencv with My machine(win10,VS2017),  the code don't run well, and I try to run `Mat img = imread("sss.png");`it can work, it seems like just the dnn modual is bad. the build error list:
```bash
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: __cdecl cv::dnn::dnn4_v20200609::Net::~Net(void)" (??1Net@dnn4_v20200609@dnn@cv@@QEAA@XZ)，该符号在函数 main 中被引用	GANDeployment	D:\desktop\Desktop\ZP\project\GAN\pytorch-CycleGAN-and-pix2pix\deployment\GANDeploymentCUDA\GANDeployment\onnxtest.obj	1
```
```.cpp
    // C++ code example
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
using namespace cv;
using namespace cv::dnn;
#include<ctime>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <opencv2/core/ocl.hpp>
using namespace std;
int main()
{
	ocl::setUseOpenCL(false);//关闭OpenCL，就不会出错了

	String modelBin = "D:\\desktop\\Desktop\\project.onnx";
	Net net = dnn::readNetFromONNX(modelBin);

	net.setPreferableBackend(DNN_BACKEND_CUDA);
	net.setPreferableTarget(DNN_TARGET_CUDA);//可以使用CUDA加速，但是需要编译opencv的cuda版本。
	return 0;
}
```

**Comment by dayfixer** [comment]
opencv的预编译模型都是基础指令集，这是用来给你学学数字图像处理用的，如果你要用dnn，自己编译吧。。
ps.无法解析的外部符号，就是链接器没找到函数入口。
----------------------
You should recompile opencv instead of using precompiled, the function linker you are using is not found.

**Comment by miziha-zp** [comment]
> ## opencv的预编译模型都是基础指令集，这是用来给你学学数字图像处理用的，如果你要用dnn，自己编译吧。。
> ps.无法解析的外部符号，就是链接器没找到函数入口。
> You should recompile opencv instead of using precompiled, the function linker you are using is not found.
为了使用cuda加速opencv的dnn模块，我尝试了在我的机器编译了opencv（I build opencv with My machine(win10,cmake,VS2017)），编译过程没有出现问题，然后测试了简单的图片读写程序也没有问题，但是当尝试编译带有dnn模块的时候出现了上述问题，我现在不太清楚如何定位问题，请指教

**Comment by dayfixer** [comment]
dnn是有版本的，你的报错的版本`dnn4_v20200609`, 这个版本的dnn对应的是opencv4.4.0, 但是你编译的是opencv4.1，你重新编译一下opencv4.4用吧。
--------------
dnn has different versions, your error version is `dnn4_v20200609`, this version of dnn corresponds to **opencv4.4.0**, but you compiled opencv4.1, you can recompile opencv4.4 and use it.
