### ISSUE TITLE
issues when building for iOS

### ISSUE THREAD

**Issue by ee-lynn** [opencv/opencv#18291]
when i installed **opencv ios**, i followed the tutorials as `python build_framework.py ios`, but it failed.
In the ios/build/build-armv7-iphoneos/CMakeFiles/CMakeError.log  I found many errors, i.e. "Code Signing Error: Bundle identifier is missing. cmTC_bc20b doesn't have a bundle identifier. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor."
how can i add Bundle identifier to this?
my opencv is 3.4.4 and is on a macbook pro machine(MacOS).

**Comment by dkurt** [comment]
> my opencv is 3.4.4
Please use the latest state of OpenCV source code.

related https://github.com/opencv/opencv/issues/14873
