### ISSUE TITLE
YOUR WEBSITE HAS BEEN HACKED SOMEONE SHOULD REALLY GET ON THAT!!!!!

### ISSUE THREAD

**Issue by VeryG00dName** [opencv/opencv#18297]
YOUR WEBSITE HAS BEEN HACKED SOMEONE SHOULD REALLY GET ON THAT!!!!!

**Comment by mshabunin** [comment]
@VeryG00dName , please file an issue here https://github.com/opencv-infrastructure/opencv.org/issues
Provide some details: what country are you accessing the website from and what is your browser and device (PC/mobile).
