### ISSUE TITLE
> The question are:

### ISSUE THREAD

**Issue by eyanson** [opencv/opencv#18303]
Mr DKURT.
1) My feature request is detection of face with mask.
2) If github is not the place to this situation, please don´t block my way, explain me where I can request this feature.
Sorry, I'm new in github and those communities.
Thanks !!

> The question are:
a) Can anybody create an XML for this situation?
b) Can anybody help me with generate an XML for this situation?

GitHub issues is not a place for usage questions. We use it for bug reports or feature requests.

_Originally posted by @dkurt in https://github.com/opencv/opencv/issues/18295#issuecomment-689437828_

**Comment by dkurt** [comment]
@eyanson, please do not reopen issues but just continue the original threads. You may use http://answers.opencv.org/ or https://stackoverflow.com/ with `opencv` tags.
