### ISSUE TITLE
Error while loading pytorch model in opencv

### ISSUE THREAD

**Issue by 123liluky** [opencv/opencv#18321]
I used a lstm layer and a fc layer in pytorch model. 
After training, I changed ***.pth model into onnx model, like below,
torch.onnx.export(model,[img_tensor,(h,c)],'***1.onnx',verbose=True,opset_version=9,input_names=["input","h","c"],output_names=["output"]).
***1.onnx looks like this,
![image](https://user-images.githubusercontent.com/20832778/93009664-43e2a000-f5b6-11ea-831d-04fba90c7ee8.png)

Then I use opencv4.4.0 to load the ***1.onnx model in C++, error is 
![image](https://user-images.githubusercontent.com/20832778/93009561-67591b00-f5b5-11ea-9bb8-8702b953a5bd.png)

However, If I use only one input for lstm layer,like below, torch.onnx.export(model,img_tensor,'***2.onnx',verbose=True,opset_version=9,input_names=["input"],output_names=["output"])
***2.onnx can be loaded successfully.
***2.onnx looks like this,
![image](https://user-images.githubusercontent.com/20832778/93009675-5bba2400-f5b6-11ea-9938-5496c056eadf.png)

But , I want to set different initial hideen value h and c in lstm layer, so I must use three inputs for lstm. How could I export ***.pth into ***.onnx to make it run correctly in opencv4.4.0 c++？

**Comment by dkurt** [comment]
Please provide a link to ONNX file or at least irigin PyTorch code. Issue should be reproducible.

**Comment by 123liluky** [comment]
Thanks for your reply. Here are two ***.onnx models. 
[onnx model.zip](https://github.com/opencv/opencv/files/5215448/onnx.model.zip)

**Comment by 123liluky** [comment]
More info:
1、model definition is:
import torch.nn as nn
class lstmFc(nn.Module):
    def __init__(self):
        super(lstmFC, self).__init__()
        self.lstm = nn.LSTM(input_size=1350,hidden_size=50,num_layers=1,batch_first=True)
        self.fc = nn.Linear(50,2)          
    def forward(self, x):
        out_lstm, (hn,cn) = self.lstm(x)
        out = self.fc(out_lstm[0,0,:])
        return out  
2、export onnx model using codes below:
image = Image.open('1.bmp').convert('L')#Gray Image 
img_tensor = data_transforms(image).cuda()#height-90,width-15
img_tensor = img_tensor.view(1,1,1350)#batch_size time_stpes input_size
h = torch.zeros(1,img_tensor.size(0),50).cuda()#num_layers batch_size hidden_size
c = torch.zeros(1,img_tensor.size(0),50).cuda()
with torch.no_grad():
      out = model(img_tensor)            
      #out = model([img_tensor,(h,c)]) 
torch.onnx.export(model,img_tensor,'lstm2.onnx',verbose=True,opset_version=9,input_names=["input"],output_names=["output"])
 #torch.onnx.export(model,[img_tensor,(h,c)],'lstm1.onnx',verbose=True,opset_version=9,input_names=["input","h","c"],output_names=["output"])
3、load onnx model in c++ like:
#include <opencv2\opencv.hpp> 
#include <iostream>
#include <fstream>
using namespace cv;
using namespace std;
using namespace dnn;
int main(int argc, char** argv) {
	int r;
	Mat src = imread("1.bmp", 0);//90*15
	imshow("src",src);
	Mat src1;
	src1 = src.reshape(0, 1);
	cout << src1.rows << "  " << src1.cols << endl;

	Net net = readNet("lstm1.onnx");
	if (net.empty()) {
		cout << "model data wrong\n";
		r = -1;
	}
	else {
		cout << "model load correct\n";
		r = 0;
	}

	int input_shape[] = { 1,1,1350 };
	Mat inputBlob = Mat(3, input_shape, CV_32F, Scalar::all(0));//blobFromImage(src1);
	for (int j = 0; j < 1350; j++)
		inputBlob.at<float>(0, 0, j) = src1.at<uchar>(0, j)-0.5;
	
	int h_c_shape[] = { 1,1,50 };
	Mat h = Mat(3, h_c_shape, CV_32F, Scalar::all(0));
	Mat c = Mat(3, h_c_shape, CV_32F, Scalar::all(0));
	net.setInput(inputBlob, "input");
	//net.setInput(h, "h");
	//net.setInput(c, "c");

	vector<Mat> outs;
	vector<String> outNames(1);
	outNames[0] = "output";
	//outNames[1] = "hn";
	//outNames[2] = "cn";
	net.forward(outs, outNames);
	cout << outs[0];
	waitKey(0);
	destroyAllWindows();
	return r;
}

**Comment by l-bat** [comment]
@123liluky  OpenCV only supports constant zero tensors for` initial_h and initial_c`, as in https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/onnx/generate_onnx_models.py#L676

**Comment by 123liluky** [comment]
OK. Thank you. Now, I use initial_h and initial_c with default zero tensors. And I use a input series with time_steps=6, batch_size=1. But another error happens:
![image](https://user-images.githubusercontent.com/20832778/93154046-3bfd3a00-f735-11ea-8d60-232d6426d01b.png)
1、model definition is
```
import torch.nn as nn
class lstmFC(nn.Module):
    def __init__(self):
        super(lstmFC, self).__init__()
        self.lstm = nn.LSTM(input_size=1350,hidden_size=50,num_layers=1,batch_first=True)
        self.fc = nn.Linear(50,2)          
    def forward(self, x):
        out_lstm, (hn,cn) = self.lstm(x)
        out = self.fc(out_lstm[:,5,:])
        return out
``` 
2、export onnx model using codes below:
```
data_transforms = transforms.Compose([transforms.ToTensor(),\
                                               transforms.Normalize([0.5], [1])])
            image = Image.open('2.bmp').convert('L')#Gray Image
            image = image.resize(90,90)
            img_tensor = data_transforms(image).cuda()#[1,90,90]
            img_tensor = img_tensor.view(-1,6,1350)#(batch_size,time_steps,features) [1,6,1350]
            with torch.no_grad():
                predict = model(img_tensor)
            print(predict)           
            torch.onnx.export(model,img_tensor,'lstm.onnx',verbose=True,opset_version=9,input_names=["input"],output_names=["output"])
```
lstm.onnx is provided
[lstm.onnx.zip](https://github.com/opencv/opencv/files/5221947/lstm.onnx.zip)

3、load onnx model in c++ using Net net = readNet("lstm1.onnx"). Then, error above happens. How could I solve the error? Thank you in advance.
