### ISSUE TITLE
Cannot read Keras H5 converted model to pb/pbtxt in C++

### ISSUE THREAD

**Issue by YannickLecroart** [opencv/opencv#18322]
Hi,

I successfully converted my Keras H5 model that I use in Python into a pb and pbtxt files in order to use the same model in C++ via OpenCV.

You can find below the sample code I used simply to make sure that I can load the model correctly:

    #include <opencv2/dnn.hpp>
    #include <opencv2/imgproc.hpp>
    #include <opencv2/highgui.hpp>

    #include <fstream>
    #include <sstream>
    #include <iostream>

    using namespace cv;
    using namespace dnn;
    using namespace std;

    int main()
    {
	    String modelConfiguration = "wine_plant_detector.pbtxt";
	    String modelWeights = "wine_plant_detector.pb";
	    Mat blob;

	    Net net = readNetFromTensorflow(modelWeights, modelConfiguration);

	    return 0;
    }

That gives me the following error in Visual Studio 2017:

    OpenCV(4.4.0) Error: Assertion failed (const_layers.insert(std::make_pair(name, li)).second) in 
    cv::dnn::dnn4_v20200609::`anonymous-namespace'::addConstNodes, file C:\build\master_winpack-build-win64- 
    vc15\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 672

I have attached the model files so that you can test your end.

[model_files.zip](https://github.com/opencv/opencv/files/5213727/model_files.zip)

What I do not understand is that if I only use load the weight file it can load the model so the error seems to occur while trying to read the model configuration file. Is it necessary to use that file that make inference?

Here is my setup:

- OpenCV => 4.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

Thanks in advance.

Regards,

**Comment by dkurt** [comment]
> OpenCV(4.4.0) Error: Assertion failed (const_layers.insert(std::make_pair(name, li)).second) in 
cv::dnn::dnn4_v20200609::`anonymous-namespace'::addConstNodes, file C:\build\master_winpack-build-win64- 
vc15\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 672

Have you tried to run without `.pbtxt`? This assertion means there are duplications of Const layers

**Comment by YannickLecroart** [comment]
Yes as I said it works without the pbtxt file but I want to understand why I cannot use the pbtxt file while loading the model just for curiosity.

**Comment by dkurt** [comment]
> Yes as I said it works without the pbtxt file but I want to understand why I cannot use the pbtxt file while loading the model just for curiosity.

Please read https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs for details. `.pbtxt` is optional argument.

Can we close an issue this way?
