### ISSUE TITLE
DNN module in OpenCV built for OpenVINO and CUDA does not support CUDA

### ISSUE THREAD

**Issue by sasanasadiabadi** [opencv/opencv#18336]
##### System information (version)

- OpenCV => 4.5.0-pre
- Operating System / Platform => Ubuntu 18.04.4 LTS x86_64
- Compiler => gcc-7.5.0, cmake-3.18.0

##### Detailed description

I build opencv dnn with cuda (-D WITH_CUDA=ON -D WITH_CUDNN=ON -D OPENCV_DNN_CUDA=ON) and with openvino IE (-D WITH_INF_ENGINE=ON  -D ENABLE_CXX11=ON) separately and the DNN_BACKEND_CUDA and DNN_BACKEND_INFERENCE_ENGINE options work perfectly fine, for each built.

But when I build it for the combined cuda+openvino case, only the IE backend works but for cuda backend I get the warning (setUpNet DNN module was not built with CUDA backend; switching to CPU). 

Is there any specific instruction on how to build for a dnn module  to support both cuda and inference engine? 

```
Other third-party libraries:
 Intel IPP:                   2020.0.0 Gold [2020.0.0]
       at:                   /home/sasan/opencv4/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
 Intel IPP IW:                sources (2020.0.0)
           at:                /home/sasan/opencv4/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
 Lapack:                      NO
 Inference Engine:            YES (2020040000 / 2.1.0)
     * libs:                  /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.so
     * includes:              /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/include
 nGraph:                      YES (0.0.0+1007b05)
     * libs:                  /usr/local/lib/libngraph.so
     * includes:              /usr/local/include
 Eigen:                       YES (ver 3.3.4)
 Custom HAL:                  NO
 Protobuf:                    build (3.5.1)

 NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS)
 NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
 NVIDIA PTX archs:

cuDNN:                         YES (ver 7.6.4)

OpenCL:                        YES (no extra features)
 Include path:                /home/sasan/opencv4/opencv/3rdparty/include/opencl/1.2
 Link libraries:              Dynamic load

Python 3:
 Interpreter:                 /usr/bin/python3 (ver 3.6.9)
 Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.9)
 numpy:                       /home/sasan/.local/lib/python3.6/site-packages/numpy/core/include (ver 1.19.1)
 install path:                lib/python3.6/dist-packages/cv2/python-3.6
 ```

**Comment by YashasSamaga** [comment]
Did you do `make install`?

Do you have multiple versions of OpenCV?

**Comment by sasanasadiabadi** [comment]
yes make install completed successfuly. 
I made a clean install for only one version of OpenCV.

**Comment by sasanasadiabadi** [comment]
Basically first I install OpenVino. Then
```
source /opt/intel/openvino/bin/setupvars.sh
export ngraph_DIR=/opt/intel/openvino/deployment_tools/ngraph/cmake/
```

Then build OpenCV

```
cmake \
	-D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=ON \
	-D INSTALL_PYTHON_EXAMPLES=ON \
        -D BUILD_EXAMPLES=ON \
	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D OPENCV_ENABLE_NONFREE=ON 
	-D PYTHON_EXECUTABLE=/usr/bin/python3 \
	-D WITH_CUDA=ON -D WITH_CUDNN=ON -D OPENCV_DNN_CUDA=ON \
        -D WITH_INF_ENGINE=ON  -D ENABLE_CXX11=ON ..
```

Is this supposed to be enough to build opencv for cuda+openvino?

**Comment by shubhamcodez** [comment]
Is there a known case of both of them working together?
just a guess but both of them may be incompatible

**Comment by sasanasadiabadi** [comment]
apparently it can be done as mentioned in [https://github.com/hybridgroup/gocv/issues/611](https://github.com/hybridgroup/gocv/issues/611)

However I didn't get any success on that as well.

**Comment by YashasSamaga** [comment]
> Is there a known case of both of them working together?

Yes, I have it installed. They work. I am confused why what @sasanasadiabadi isn't working. It's supposed to work.

Can you upload your CMakeCache.txt?

Please check CMake output for a message like "filtering out cuda4dnn" (maybe search for the word "cuda4dnn"). If you don't find any such message, then the CUDA backend was enabled.

**Comment by sasanasadiabadi** [comment]
> Basically first I install OpenVino. Then
> 
> ```
> source /opt/intel/openvino/bin/setupvars.sh
> export ngraph_DIR=/opt/intel/openvino/deployment_tools/ngraph/cmake/
> ```
> 
> Then build OpenCV
> 
> ```
> cmake \
> 	-D CMAKE_BUILD_TYPE=RELEASE \
> 	-D CMAKE_INSTALL_PREFIX=/usr/local \
> 	-D INSTALL_C_EXAMPLES=ON \
> 	-D INSTALL_PYTHON_EXAMPLES=ON \
>         -D BUILD_EXAMPLES=ON \
> 	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
>         -D OPENCV_ENABLE_NONFREE=ON 
> 	-D PYTHON_EXECUTABLE=/usr/bin/python3 \
> 	-D WITH_CUDA=ON -D WITH_CUDNN=ON -D OPENCV_DNN_CUDA=ON \
>         -D WITH_INF_ENGINE=ON  -D ENABLE_CXX11=ON ..
> ```
> 
> Is this supposed to be correct way to build opencv for cuda+openvino?

Have you installed in the same way which I mentioned here?
I didnt see any "filtering out cuda4dnn" in Cmake output.
here is the CMakeCache.txt 

[CMakeCache.txt](https://github.com/opencv/opencv/files/5231557/CMakeCache.txt)

**Comment by YashasSamaga** [comment]
@sasanasadiabadi 

> Have you installed in the same way which I mentioned here?

Not exactly. I do it in multiple passes using cmake-gui and disable a whole lot of modules. But I think your cmake command is correct.

> (setUpNet DNN module was not built with CUDA backend; switching to CPU)

https://github.com/opencv/opencv/blob/3b00ee2afb4176a5a45def7939b816d3a8914c00/modules/dnn/src/dnn.cpp#L1426-L1430

implies that `HAVE_CUDA` was not defined during compilation.

`HAVE_CUDA` must be defined when `WITH_CUDA` is enabled.

https://github.com/opencv/opencv/blob/3b00ee2afb4176a5a45def7939b816d3a8914c00/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake#L7-L11

If CUDA backend for DNN module was not built, you should see "filter out cuda4dnn source code".

---

Can you check if `HAVE_CUDA` is defined in CMakeVars.txt?

**Comment by sasanasadiabadi** [comment]
yes I can see the ```HAVE_CUDA=1``` in CMakeVars.txt
[CMakeVars.txt](https://github.com/opencv/opencv/files/5232183/CMakeVars.txt)

**Comment by YashasSamaga** [comment]
> yes I can see the HAVE_CUDA=1 in CMakeVars.txt

Now this is a contradiction. `HAVE_CUDA` is set implies a `#cmakedefien HAVE_CUDA` will be set. It's not possible to get `"DNN module was not built with CUDA backend; switching to CPU"` message.

Can you try building again from a clean build directory?

**Comment by sasanasadiabadi** [comment]
OK let me try it again from scratch. 
Installing OpenVINO from installer is ok, right? or does it have to be built from source with some extra flags?

**Comment by YashasSamaga** [comment]
> Installing OpenVINO from installer is ok, right? or does it have to be built from source with some extra flags?

Installing from installer should work.

**Comment by alalek** [comment]
Dump `cv::getBuildinformation()` and compare content with CMake output to avoid case with loading of misused binaries.
