### ISSUE TITLE
DNN_TARGET_CUDA_FP16  Slower on JetPack 4.4 then JetPack 4.2

### ISSUE THREAD

**Issue by sgriset** [opencv/opencv#18340]
##### Jetson Nano (JetPack 4.2 and JetPack 4.4)
OpenCV => 4.4 
When running DNN_TARGET_CUDA_FP16 backend inferencing is much slower on JetPack 4.4 then JetPack 4.2 (see attached pdf file for performance numbers in milliseconds).  When I was monitoring the system using jtop I noticed under 4.2 the system tends to spread processing across CPU/GPU, while under 4.4 the GPU handles the majority of the workload.  
[JetPack Performance Numbers.pdf](https://github.com/opencv/opencv/files/5222364/JetPack.Performance.Numbers.pdf)

**Comment by YashasSamaga** [comment]
This is a cuDNN 8 regression.

More on it here: https://forums.developer.nvidia.com/t/cudnn8-regression-in-algorithm-selection-heuristics/153667

**Comment by sgriset** [comment]
Thank you I will close the issue
