### ISSUE TITLE
How to preprocess input for a keras H5 converted model into a pb file

### ISSUE THREAD

**Issue by YannickLecroart** [opencv/opencv#18342]
Hi,

I successfully converted a Keras H5 model into a Tensorflow pb file but I get totally different result when making a prediction.

In Python I use 2 Keras modules to preprocess the data before feeding the network:

    from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
    from tensorflow.keras.preprocessing.image import img_to_array

Here is how I preprocess the data in my Python code:

    # extract the object ROI, convert it from BGR to RGB channel
    # ordering, resize it to 224x224, and preprocess it
    moving_object = img_orig[startY:endY, startX:endX]
    moving_object = cv2.cvtColor(moving_object, cv2.COLOR_BGR2RGB)
    moving_object = cv2.resize(moving_object, (224, 224))
    moving_object = img_to_array(moving_object)
    moving_object = preprocess_input(moving_object)

    objects.append(moving_object)

Then I make batch predictions via the Keras predict method:

    # only make a predictions if at least one object was detected
        if len(objects) > 0:
            objects = np.array(objects, dtype="float32")
            preds = wine_plant_model.predict(objects)

Here is how I preprocess the data in C++:

    vector<Mat> detected_objects;

    //extract the object ROI
    Mat image_roi = img_orig(roi);

    detected_objects.push_back(image_roi);

and how I make batch predictions in C++:

    //only make a predictions if at least one object was detected
	    if (detected_objects.size() > 0)
	    {
		    vector<Mat> preds;

		    Mat inputBlobs = cv::dnn::blobFromImages(detected_objects, 1.0, Size(224, 224));

		    net.setInput(inputBlobs);
		    Mat outputs = net.forward();
          }

It seems that I am not preprocessing the image the right way in C++ and therefore I am not getting the same results. But I cannot find a equivalent for the Keras preprocess_input() method in C++.

Could you please tell me what I should do to preprocess the data the same way in C++ even if it is not through Keras which does not seem to be available in C++.

Just in case you need it, I have attached the model files.

[model_files.zip](https://github.com/opencv/opencv/files/5224300/model_files.zip)

Thanks in advance.

Regards,

Here is my setup:

- OpenCV => 4.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

**Comment by YannickLecroart** [comment]
Looking at the Keras documentation the python preprocess_input() method scale the data between 1 and -1.

    The inputs pixel values are scaled between -1 and 1, sample-wise.

How would I do that in C++ is there a convenient method to do so?

**Comment by dkurt** [comment]
@YannickLecroart, please read documentation for [blobFromImage](https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga29f34df9376379a603acd8df581ac8d7).

Please do not use GitHub issues for usage questions. We need it to track bug reports or feature requests

**Comment by YannickLecroart** [comment]
Thanks for the help I did manage to solve my problem by reading the blobFromImage documentation.

Regards,
