### ISSUE TITLE
compilation error when using OpenCV 4.4 or 4.5

### ISSUE THREAD

**Issue by jsemeda** [opencv/opencv#18351]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

D:\Libraries\opencv\modules\flann\include\opencv2\flann\matrix.h(71,24): warning C4003: not enough arguments for function-like macro invocation 'free' 
1>D:\Libraries\opencv\modules\flann\include\opencv2\flann\matrix.h(71,1): error C2059: syntax error: ',' 
1>D:\Libraries\opencv\modules\core\include\opencv2\core\cuda.hpp(115,22): error C2059: syntax error: 'constant' 
1>    7 Warning(s)
1>    2 Error(s)

##### Steps to reproduce

I can't tell where the errors are coming from. I am not using CUDA and tried both OpenCV with and without CUDA.
I had to undefine (OPENCV_HAVE_FLANN) to get rid of the the flann matrix error. But I still have the GPUMat error, I have no idea why it is getting pulled into my code and can not see where it is coming from.

**Comment by alalek** [comment]
> function-like macro invocation 'free'

Can't fix that (problem is in the caller code).
You can workaround that on your side with `#undef free`.

Closing as **invalid**.
