### ISSUE TITLE
Problems with NCS2 and OpenVino2020.2

### ISSUE THREAD

**Issue by NLRosalia** [opencv/opencv#18355]
Hello,

I am currently using in production a NCS2 with openCV provided in the OpenVino 2020.2 package.

The current solution uses the NCS2 with an SSD Mobilenetv2 network. If I run only my software in the PC, the performance is great (90ms per inference), however, when my software is running in parallel with other programs that consume high amount of the CPU (80-90%) the inference times of the network become very unstable and slow, with ranges from 100ms to 1500ms, even sometimes when the CPU load is really high, the inference breaks giving the exception : "Failed to queue inference: NC_ERROR". The Computer I use has a Intel Atom E3845 CPU and uses Windows 10.

So, has CPU usage a big impact in the inference of models in the NCS2, actings as a bottleneck? Is there any way to avoid inference exception (which causes my program to break)?

Also, another curious thing I experienced is that if I run a program that uses two separate threads in parallel for inference, the process runs perfectly on my Intel Xeon E3-1245 with the NCS2. However, if I do the exact same thing in the Atom PC it breaks from the begining. Is the NCS2 able to parallelize calls from multiples threads?

Thank you so much for you attention.

Kind regards,

##### System information (version)
- OpenCV => 4.3 - OpenVino2020.2
- Operating System / Platform => Windows 10 Enterprise 2016
- Compiler => Pre-compiled package from OpenVino2020.2

##### Detailed description

Usage of Myriad device in on a busy PC results in slow inference and ocassionally NC_ERROR while doing inference.

##### Steps to reproduce

1. Run a sample application (very similar to the one in samples/dnn/object_detection) that runs SSD on the Myriad device continously. If this test application is run alone, everything will be stable.

2. Run the exact same application as in step 1 but having another running processes (that use CPU) on a 80-90%. Network inference will have spikes and eventually will cause an exception while running: "Failed to queue inference: NC_ERROR".

**Comment by alalek** [comment]
> multiples threads

OpenCV introduction: https://docs.opencv.org/3.4/d1/dfb/intro.html

> the same function or the same methods of **different class instances** can be called from different threads.

Also OpenCV doesn't have automatic detection of data-races.

It is unlikely that two dnn::Net objects can be initialized for NCS device (due to device limitations).
You should use async API to handle multiple requests in parallel.


---

> having another running processes

Work with priorities for processes.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by NLRosalia** [comment]
Thanks alalek, so no initialization of multiple networks can be run on the same NCS device.

Still wondering why NC_ERROR happens when just running one application, I will post the question in http://answers.opencv.org as advised.

Thanks!

**Comment by dkurt** [comment]
> So, has CPU usage a big impact in the inference of models in the NCS2, actings as a bottleneck? Is there any way to avoid inference exception (which causes my program to break)?

please take a look at https://github.com/openvinotoolkit/openvino/pull/2030
