### ISSUE TITLE
some question to consult

### ISSUE THREAD

**Issue by xwr96** [opencv/opencv#18369]
Hi, I want to ask a question. Is in opencv2 version, lib is conclude libopencv_core.so.2.x, and Lib in opencv4 version is libopencv_ core.so .4.x. because when i run opencv4, it has the error: 
`OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
`

**Comment by dkurt** [comment]
This is not OpenCV related question - study how to link Linux shared libraries.

If you want somebody to help - provide a reproducer.
