### ISSUE TITLE
cv::cuda::meanStdDev() is using default stream instead of the stream passed to it

### ISSUE THREAD

**Issue by siyucosmo** [opencv/opencv#18376]
##### System information (version)
- OpenCv => 3.2
- Operating System => Ubuntu 16.04

##### Detailed description
Hi, I am new to cuda programming. I encountered a problem when using `cv::cuda::meanStdDev`.

I am calling `cv::cuda::meanStdDev` but I found it is using the default stream although I have passed a stream to it. Does anyone know why this is happening? Is there a way to correctly pass the stream to `cv::cuda::meanStdDev` ?

I have written a simple code as below and did the gpu profiling on it. Below is the gpu profiling result for `cv::cuda::meanStdDev` and `cv::cuda::resize`. We can find `cv::cuda::meanStdDev` is using default stream while `cv::cuda::resize` is correctly using stream 14. 

![squareSumFunctor](https://user-images.githubusercontent.com/26804579/93827370-fbfaf300-fc1d-11ea-9579-f0a56206d411.png)
![resize](https://user-images.githubusercontent.com/26804579/93827388-02896a80-fc1e-11ea-9454-7f7bae701166.png)

##### Steps to reproduce
```
#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda_stream_accessor.hpp>


int main(int argc, char** argv){
    cv::cuda::Stream _stream;
    cv::cuda::HostMem _h_mean_std_result;
    cv::cuda::GpuMat _d_input;
    cv::Size model_image_size(480,320);
    cv::Mat img = cv::imread("test.png");

    _d_input.upload(img);
    cv::cuda::resize(_d_input, _d_input, model_image_size, 0, 0, cv::INTER_LINEAR, _stream);
    cv::cuda::meanStdDev(_d_input.reshape(1), _h_mean_std_result, _stream);
    _stream.waitForCompletion();
    cv::Mat _cv_mean_std_result;
    _cv_mean_std_result = _h_mean_std_result.createMatHeader();
    std::cout << _cv_mean_std_result << std::endl;
}
```

**Comment by alalek** [comment]
> 3.2

Try latest code from 3.4 branch first.
We don't fix outdated releases
