### ISSUE TITLE
Is there any user data that is either being collected or Tracked by the openCV

### ISSUE THREAD

**Issue by m-venkata** [opencv/opencv#18388]
##### System information (version)

- OpenCV 
- Operating System / Platform => iOS/ APple
- Compiler => XCode

##### Detailed description
As part of the iOS 14 /AppTracking Transparency framework, would like to know if any kind of the user data is collected or Tracked by the OpenCV.

As mentioned in the Apple (Ref: https://developer.apple.com/support/app-privacy-on-the-app-store/),
below were some of the examples for Tracking:

Sharing device location data or email lists with a data broker.
Placing a third-party SDK in our app that combines user data from the app with user data from other developers’ apps to target advertising or measure advertising efficiency, even if we don’t use the SDK for these purposes. For example, using a login SDK that repurposes the data it collects from the app to enable targeted advertising in other developers’ apps.
The following situations are not considered tracking:

When the data is linked solely on the end-user’s device and is not sent off the device in a way that can identify the end-user or device.
When the data broker uses the data shared with them solely for fraud detection or prevention or security purposes, and solely on our behalf.

**Comment by alalek** [comment]
OpenCV is a library.
Such behavior is defined and controlled by end-user's applications.

Applications must be certified instead of the library. Closing as invalid.

**Comment by jayshildave1983** [comment]
Why would this be invalid @alalek?

This isn't certifying Application instead the users of the library are assured that OpenCV is not collecting any information without the knowledge of the application which can be termed as private information from a user perspective.
Hope this clears the ask.
