### ISSUE TITLE
Please check CUDA_ARCH_PTX or CUDA_ARCH_BIN 

### ISSUE THREAD

**Issue by yancccc** [opencv/opencv#18382]
classes, confidences, boxes = net.detect(image, confThreshold, nmsThreshold)
cv2.error: OpenCV(4.4.0) /home/ycc/opencv-4.4.0/modules/dnn/src/dnn.cpp:2353: error: (-216:No CUDA support) OpenCV was not built to work with the selected device. Please check CUDA_ARCH_PTX or CUDA_ARCH_BIN in your build configuration. in function 'initCUDABackend'

cmake -DCMAKE_BUILD_TYPE=RELEASE \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.4.0/modules .. \
    -DWITH_CUDA=1 \
    -DCUDA_ARCH_BIN=7.5 \
    -DENABLE_FAST_MATH=1 \
    -DCUDA_FAST_MATH=1 \
    -DWITH_CUBLAS=1 \
    -DOPENCV_GENERATE_PKGCONFIG=1 \
    -DCUDA_GENERATION=Pascal ..

Ubuntu 16.04, cuda10, cudnn7.6, opencv4.4. Gtx1080 runs normally, rtx2060 reports an error, Why?
@YashasSamaga

**Comment by yancccc** [comment]
NVIDIA CUDA:              YES
   NVIDIA GPU arch:     60 61
   NVIDIA PTX arch:

**Comment by alalek** [comment]
https://en.wikipedia.org/wiki/CUDA

"2060" CC is 7.5.

> NVIDIA GPU arch: 60 61

You need to add 75 (7.5) here.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by yancccc** [comment]
Where to change it? I set it　-DCUDA_ARCH_BIN=7.5 
@alalek

**Comment by alalek** [comment]
> CUDA_GENERATION=Pascal

This overrides other low level flags. You need need to choose one.

Try `cmake -UCUDA_GENERATION ...`

**Comment by yancccc** [comment]
OK, I'll try

**Comment by yancccc** [comment]
Yes, thank you
