### ISSUE TITLE
File "tf_text_graph_ssd.py",    assert(graph_def.node[0].op == 'Placeholder') AssertionError

### ISSUE THREAD

**Issue by e-inan** [opencv/opencv#18380]
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Conda
- tf_gpu=1.15

All file here: 
[pb_config_graph-ssd_graph-common.zip](https://github.com/opencv/opencv/files/5259416/pb_config_graph-ssd_graph-common.zip)

#### My output error

(rovproject) C:\Users\Eftal\projectoftf\rov\research\object_detection\Rov Opencv>python tf_text_graph_ssd.py --input=frozen_inference_graph.pb --output=out/graph.pbtxt
2020-09-22 08:56:38.333298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From tf_text_graph_ssd.py:45: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
WARNING:tensorflow:From tf_text_graph_ssd.py:46: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

2020-09-22 08:56:40.583319: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying sort_by_execution_order
2020-09-22 08:56:41.752405: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying sort_by_execution_order
Traceback (most recent call last):
  **File "tf_text_graph_ssd.py", line 163, in <module>
    assert(graph_def.node[0].op == 'Placeholder')**
AssertionError

**Comment by dkurt** [comment]
> OpenCV => 4.0

Please use the latest script

**Comment by e-inan** [comment]
I installed opencv=4.4.0
btw i did tf_text_graph_ssd for pbtxt. 

I have still same error. 
error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-52oirelq\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:553: error: (-2:Unspecified error) Input layer not found: FeatureExtractor/MobilenetV2/Conv/weights in function 'cv::dnn::dnn4_v20200609::`anonymous-namespace'::TFImporter::connect'


Should i transfer pb file to raspi? and how? 

BR
Thanks

**Comment by e-inan** [comment]
python tf_text_graph_ssd.py --input=frozen_inference_graph.pb --output=graph.pbtxt --config=ssd_mobilenet_v2_coco.config

Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.3333]
Reduce boxes in the lowest layer: True
Number of classes: 1
Number of layers: 6
box predictor: convolutional
Input image size: 300x300

**Comment by dkurt** [comment]
Read https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API for details. 

Please feel bug report properly.

**Comment by Adeann** [comment]
I'm running in the same issue while trying to get a graph.pbtxt file. 

OpenCV => 4.4
Operating System / Platform => Windows 10 Pro 64 Bit
Compiler => Conda
tf=1.15

The command I'm running is:
python tf_text_graph_ssd.py --input=PATH_TO_MODEL\frozen_graph.pb --config=PATH_TO_CONFIG\pipeline.config --output=PATH_TO_OUTPUT\graph.pbtxt

Error Log from the base frozen_graph.pb:
```Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 405, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 236, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError```

I've tried other user suggestions to sort the frozen_graph.pb first, however, I get the same error as above. 
I have also tried running the latest scripts, which result in the same error as above as well.

Does anyone have any suggestions on how to proceed?

**Comment by rojnwa** [comment]
Having the same issue with OpenCV version 4.5.2 and latest TF1x version (1.15.5).
Using `ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03` as a pre-trained model.

Does it not work because it is a quantized model? What are my options?

**Comment by hitbuyi** [comment]
still have this problem on opencv 4.5.2

**Comment by HoseinHashemi** [comment]
I have the same problem with opencv 4.6.0.
Have anyone solved this problem?
