### ISSUE TITLE
pessimistic cv::RotatedRect::boundingRect()

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#18417]
OpenCV 4.4.0

Even with integer center/even size, the boundingRect() estimation of a cv::RotatedRect() with a 0 angle may be one-pixel wider than expected.
This is not wrong per se (this is still a bounding rect), but it is a little pessimistic :

```
cv::Rect r(0, 0, 1280, 1024);
cv::RotatedRect rr(cv::Point2f(r.width/2.f, r.height/2.f),
                   cv::Size2f(1.f*r.width, 1.f*r.height),
                   0);
cv::Rect br = rr.boundingRect();
std::cout << "r:" << r << std::endl; //1280x1024
std::cout << "br:" << br << std::endl; //1281x1025
```

This may be normal since a RotatedRect is center-wise, so the size may have to be odd to match integer-pixel boundaries.
However, this is still pessimistic :
```
cv::Rect r(0, 0, 1281, 1025);
cv::RotatedRect rr(cv::Point2f(640, 512), cv::Size2f(1.f*r.width, 1.f*r.height), 0);
cv::Rect br = rr.boundingRect();
std::cout << "r:" << r << std::endl;//1281 x 1025
std::cout << "br:" << br << std::endl;//1283 x 1027
```

**Comment by chacha21** [comment]
This may be normal since this a RotatedRect being center-wise, the size must be odd to match integer-pixel boundaries

**Comment by alalek** [comment]
Pixels on the right/bottom border of `Rect` are excluded.
`RotatedRect` has different semantics.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by 4sfaloth** [comment]
I also think the center of the box should be given by x0 + (width - 1) / 2, y0 + (height - 1) / 2

Imagine the box has a width of 5 and starts at 0, so pixels are 0, 1, 2, 3, 4. Center 2 is obviously '2', which is obtained by the formula above. If you don't subtract 1 from the width before dividing by two you get 2.5 which is wrong
