### ISSUE TITLE
detections = net.forward() issue

### ISSUE THREAD

**Issue by Pasadenasman** [opencv/opencv#18414]
Hi,
This is my first attempt to post an issue so please excuse if not posted correctly. I have read every related issue that looks like mine but cant figure it out. Hope you guys can help me with this one.
_I thank you in advance for the help and keep in mind I'm really new to raspbian so dont be afraid to give extra hint for better understanding._

-Raspberry pi 4B
-Rasbian (everything up to date as long as i know) 
 
So, I've tested this project and i'm stuck with the following : 

**The traceback**

pi@raspberrypi:~/Desktop/reconnaissance_objets $ python3 reckonpi.py --prototxt MobileNetSSD_deploy.prototxt.txt --model MobileNetSSD_deploy.caffemodel
 ...chargement du modèle...
...démarrage de la Picamera...
Traceback (most recent call last):
  File "reckonpi.py", line 66, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.0.0) /home/pi/opencv/modules/dnn/src/layers/convolution_layer.cpp:236: error: (-215:Assertion failed) blobs.size() != 0 in function 'getMemoryShapes'

link to the project : https://www.framboise314.fr/i-a-realisez-un-systeme-de-reconnaissance-dobjets-avec-raspberry-pi/

**The code :** 

# Ouvrir un terminal et executer la commande ci dessous
# python3 reconnaissance_objets.py --prototxt MobileNetSSD_deploy.prototxt.txt --model MobileNetSSD_deploy.caffemodel

# importer tout les packages requis
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np
import argparse
import imutils
import time
import cv2
# packages nécessaires pour la gestion des emails
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import ntpath
import pyautogui

# construction des arguments
ap = argparse.ArgumentParser()
ap.add_argument("-p", "--prototxt", required=True,
	help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
	help="path to Caffe pre-trained model")
ap.add_argument("-c", "--confidence", type=float, default=0.2,
	help="minimum probability to filter weak detections")
args = vars(ap.parse_args())

# initialiser la liste des objets entrainés par MobileNet SSD 
# création du contour de détection avec une couleur attribuée au hasard pour chaque objet
CLASSES = ["arriere-plan", "avion", "velo", "oiseau", "bateau",
	"bouteille", "autobus", "voiture", "chat", "chaise", "vache", "table",
	"chien", "cheval", "moto", "personne", "plante en pot", "mouton",
	"sofa", "train", "moniteur"]
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))

# chargement des fichiers depuis le répertoire de stockage 
print(" ...chargement du modèle...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])

# initialiser la caméra du pi, attendre 2s pour la mise au point ,
# initialiser le compteur FPS
print("...démarrage de la Picamera...")
vs = VideoStream(usePiCamera=True, resolution=(1600, 1200)).start()
time.sleep(2.0)
fps = FPS().start()

# boucle principale du flux vidéo
while True:
	# récupération du flux vidéo, redimension 
	# afin d'afficher au maximum 800 pixels 
	frame = vs.read()
	frame = imutils.resize(frame, width=800)

	# récupération des dimensions et transformation en collection d'images
	(h, w) = frame.shape[:2]
	blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)),
		0.007843, (300, 300), 127.5)

	# determiner la détection et la prédiction 
	net.setInput(blob)
	detections = net.forward()

	# boucle de détection 
	for i in np.arange(0, detections.shape[2]):
		# calcul de la probabilité de l'objet détecté 
		# en fonction de la prédiction
		confidence = detections[0, 0, i, 2]
		
		# supprimer les détections faibles 
		# inférieures à la probabilité minimale
		if confidence > args["confidence"]:
			# extraire l'index du type d'objet détecté
			# calcul des coordonnées de la fenêtre de détection 
			idx = int(detections[0, 0, i, 1])
			box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
			(startX, startY, endX, endY) = box.astype("int")

			# creation du contour autour de l'objet détecté
			# insertion de la prédiction de l'objet détecté 
			label = "{}: {:.2f}%".format(CLASSES[idx],
				confidence * 100)
			cv2.rectangle(frame, (startX, startY), (endX, endY),
				COLORS[idx], 2)
			y = startY - 15 if startY - 15 > 15 else startY + 15
			cv2.putText(frame, label, (startX, y),
				cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)
			# enregistrement de l'image détectée 
			cv2.imwrite("detection.png", frame)
 			
			# envoi d'un email avec l'image en pièce jointe
			email = 'votre_e_mail@gmail.com'
			password = 'votre_mot_de_passe'
			send_to_email = 'votre_e_mail@gmail.com'
			subject = 'detection'
			message = 'detection'
			file_location = 'le_répertoire_de_votre_choix/detection.png'
			msg = MIMEMultipart()
			msg['From'] = email
			msg['To'] = send_to_email
			msg['Subject'] = subject
			body = message
			msg.attach(MIMEText(body, 'plain'))
			filename = ntpath.basename(file_location)
			attachment = open(file_location, "rb")
			part = MIMEBase('application', 'octet-stream')
			part.set_payload((attachment).read())
			encoders.encode_base64(part)
			part.add_header('Content-Disposition', "attachment; filename=%s" % filename)
			msg.attach(part)
			server = smtplib.SMTP('smtp.gmail.com', 587)
			server.starttls()
			server.login(email, password)
			text = msg.as_string()
			server.sendmail(email, send_to_email, text)
			server.quit()
			
	# affichage du flux vidéo dans une fenètre 

	cv2.imshow("Frame", frame)
	key = cv2.waitKey(1) & 0xFF

	# la touche q permet d'interrompre la boucle principale
	if key == ord("q"):
		break

	# mise à jour du FPS 
	fps.update()

# arret du compteur et affichage des informations dans la console
fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))

cv2.destroyAllWindows()
vs.stop()

**Comment by alalek** [comment]
> 4.0.0

You using outdated version.
Try the latest code from master branch first.

**Comment by Pasadenasman** [comment]
ok i have update/upgraded opencv.

now i get the following and the files are located in the same folder as the reckonpi.py file.
i doesnt make any sense to me cause on the tutorial it says that it just needs to copy the path to the mobileSSD protobuf file and the cafe model...

# Ouvrir un terminal et executer la commande ci dessous
# python3 reckonpi.py --prototxt MobileNetSSD_deploy.prototxt.txt --model MobileNetSSD_deploy.caffemodel
 
# importer tout les packages requis
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np
import argparse
import imutils
import time
import cv2
# packages nécessaires pour la gestion des emails
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import ntpath
import pyautogui
 
 
 
# construction des arguments
ap = argparse.ArgumentParser()
ap.add_argument("-p", "--prototxt", required=True,
	help="/home/pi/Desktop/reconnaissance_objets/MobileNetSSD_deploy.prototxt.txt")
ap.add_argument("-m", "--model", required=True,
	help="/home/pi/Desktop/reconnaissance_objets/MobileNetSSD_deploy.caffemodel")
ap.add_argument("-c", "--confidence", type=float, default=0.2,
	help="minimum probability to filter weak detections")
args = vars(ap.parse_args())
 
# initialiser la liste des objets entrainés par MobileNet SSD 
# création du contour de détection avec une couleur attribuée au hasard pour chaque objet
CLASSES = ["arriere-plan", "avion", "velo", "oiseau", "bateau",
	"bouteille", "autobus", "voiture", "chat", "chaise", "vache", "table",
	"chien", "cheval", "moto", "personne", "plante en pot", "mouton",
	"sofa", "train", "moniteur"]
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))
 
# chargement des fichiers depuis le répertoire de stockage 
print(" ...chargement du modèle...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
 
# initialiser la caméra du pi, attendre 2s pour la mise au point ,
# initialiser le compteur FPS
print("...démarrage de la Picamera...")
vs = VideoStream(usePiCamera=True, resolution=(1600, 1200)).start()
time.sleep(2.0)
fps = FPS().start()
 
# boucle principale du flux vidéo
while True:
	# récupération du flux vidéo, redimension 
	# afin d'afficher au maximum 800 pixels 
	frame = vs.read()
	frame = imutils.resize(frame, width=800)
 
	# récupération des dimensions et transformation en collection d'images
	(h, w) = frame.shape[:2]
	blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)),
		0.007843, (300, 300), 127.5)
 
	# determiner la détection et la prédiction 
	net.setInput(blob)
	detections = net.forward()
 
	# boucle de détection 
	for i in np.arange(0, detections.shape[2]):
		# calcul de la probabilité de l'objet détecté 
		# en fonction de la prédiction
		confidence = detections[0, 0, i, 2]
		
		# supprimer les détections faibles 
		# inférieures à la probabilité minimale
		if confidence > args["confidence"]:
			# extraire l'index du type d'objet détecté
			# calcul des coordonnées de la fenêtre de détection 
			idx = int(detections[0, 0, i, 1])
			box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
			(startX, startY, endX, endY) = box.astype("int")
 
			# creation du contour autour de l'objet détecté
			# insertion de la prédiction de l'objet détecté 
			label = "{}: {:.2f}%".format(CLASSES[idx],
				confidence * 100)
			cv2.rectangle(frame, (startX, startY), (endX, endY),
				COLORS[idx], 2)
			y = startY - 15 if startY - 15 > 15 else startY + 15
			cv2.putText(frame, label, (startX, y),
				cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)
			# enregistrement de l'image détectée 
			cv2.imwrite("detection.png", frame)
 			
			# envoi d'un email avec l'image en pièce jointe
			email = '**'
			password = '**'
			send_to_email = '**'
			subject = 'detection'
			message = 'detection'
			file_location = '/home/pi/Desktop/detection test/detection.png'
			msg = MIMEMultipart()
			msg['From'] = email
			msg['To'] = send_to_email
			msg['Subject'] = subject
			body = message
			msg.attach(MIMEText(body, 'plain'))
			filename = ntpath.basename(file_location)
			attachment = open(file_location, "rb")
			part = MIMEBase('application', 'octet-stream')
			part.set_payload((attachment).read())
			encoders.encode_base64(part)
			part.add_header('Content-Disposition', "attachment; filename=%s" % filename)
			msg.attach(part)
			server = smtplib.SMTP('smtp.gmail.com', 587)
			server.starttls()
			server.login(email, password)
			text = msg.as_string()
			server.sendmail(email, send_to_email, text)
			server.quit()
			
	# affichage du flux vidéo dans une fenètre 
 
	cv2.imshow("Frame", frame)
	key = cv2.waitKey(1) & 0xFF
 
	# la touche q permet d'interrompre la boucle principale
	if key == ord("q"):
		break
 
	# mise à jour du FPS 
	fps.update()
 
# arret du compteur et affichage des informations dans la console
fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
 
cv2.destroyAllWindows()
vs.stop()

**Comment by Pasadenasman** [comment]
sorry, forgot to add the error message : 
Python 3.7.3 (/usr/bin/python3)
>>> %Run reckonpi.py
usage: reckonpi.py [-h] -p PROTOTXT -m MODEL [-c CONFIDENCE]
reckonpi.py: error: the following arguments are required: -p/--prototxt, -m/--model

**Comment by Pasadenasman** [comment]
so...
when i try to compile opencv i get the following "error" a c/c++ flags. @alalek i ve read that you said that isn't really an error but at the end the of the configurating process i get "  Configuring incomplete, errors occurred!"
i ve installed gcc as compiler on the Pi in the hope to have all the needed packages to get the configuration completed but it failed. So now im running out of idea and can't find any solution. i don't think i'm the only one experiencing the issue but can't find anything fixing it. hope you guys can help. 

pi@raspberrypi:~/opencv/opencv-4.4.0/build $ cmake -D CMAKE_BUILD_TYPE=RELEASE \
> -D CMAKE_INSTALL_PREFIX=/usr/local \
> -D INSTALL_PYTHON_EXAMPLES=ON \
> -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.4.0/modules \
> -D BUILD_EXAMPLES=ON ..
-- Detected processor: armv7l
-- Looking for ccache - not found
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1)
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Found OpenEXR: /usr/lib/arm-linux-gnueabihf/libIlmImf.so
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find Atlas (missing: Atlas_CLAPACK_INCLUDE_DIR) 
-- A library with LAPACK API found.
-- Found apache ant: /usr/bin/ant (1.10.5)
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Could NOT find Pylint (missing: PYLINT_EXECUTABLE) 
-- Could NOT find Flake8 (missing: FLAKE8_EXECUTABLE) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- Carotene: NEON is not available, disabling carotene...
CMake Error at cmake/OpenCVModule.cmake:288 (message):
  No modules has been found: /home/pi/opencv_contrib-4.4.0/modules
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:370 (_glob_locations)
  modules/CMakeLists.txt:7 (ocv_glob_modules)


-- OpenCV Python: during development append to PYTHONPATH: /home/pi/opencv/opencv-4.4.0/build/python_loader
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Allocator metrics storage type: 'int'
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse3.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.ssse3.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse4_1.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.sse4_2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.avx.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.fp16.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.avx2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin128.avx512_skx.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin256.avx2.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin256.avx512_skx.cpp
-- Excluding from source files list: <BUILD>/modules/core/test/test_intrin512.avx512_skx.cpp
-- Excluding from source files list: modules/imgproc/src/corner.avx.cpp
-- Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/imgwarp.sse4_1.cpp
-- Excluding from source files list: modules/imgproc/src/resize.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/resize.sse4_1.cpp
-- Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': /home/pi/opencv/opencv-4.4.0/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
-- opencv_dnn: filter out cuda4dnn source code
-- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx.cpp
-- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx2.cpp
-- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx512_skx.cpp
-- Excluding from source files list: modules/features2d/src/fast.avx2.cpp
-- OpenCL samples are skipped: OpenCL SDK is required
-- 
-- General configuration for OpenCV 4.4.0 =====================================
--   Version control:               unknown
-- 
--   Platform:
--     Timestamp:                   2020-09-26T14:08:39Z
--     Host:                        Linux 5.4.51-v7l+ armv7l
--     CMake:                       3.13.4
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               RELEASE
-- 
--   CPU/HW features:
--     Baseline:
--       requested:                 DETECT
--       disabled:                  VFPV3 NEON
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ standard:                11
--     C++ Compiler:                /usr/bin/c++  (ver 8.3.0)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,--gc-sections -Wl,--as-needed  
--     Linker flags (Debug):        -Wl,--gc-sections -Wl,--as-needed  
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python2 python3 stitching ts video videoio
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 java js
--     Applications:                tests perf_tests examples apps
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   GUI: 
--     GTK+:                        YES (ver 3.24.5)
--       GThread :                  YES (ver 2.58.3)
--       GtkGlExt:                  NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/arm-linux-gnueabihf/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/arm-linux-gnueabihf/libjpeg.so (ver 62)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         /usr/lib/arm-linux-gnueabihf/libpng.so (ver 1.6.36)
--     TIFF:                        /usr/lib/arm-linux-gnueabihf/libtiff.so (ver 42 / 4.1.0)
--     JPEG 2000:                   /usr/lib/arm-linux-gnueabihf/libjasper.so (ver 1.900.1)
--     OpenEXR:                     /usr/lib/arm-linux-gnueabihf/libImath.so /usr/lib/arm-linux-gnueabihf/libIlmImf.so /usr/lib/arm-linux-gnueabihf/libIex.so /usr/lib/arm-linux-gnueabihf/libHalf.so /usr/lib/arm-linux-gnueabihf/libIlmThread.so (ver 2_2)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (58.35.100)
--       avformat:                  YES (58.20.100)
--       avutil:                    YES (56.22.100)
--       swscale:                   YES (5.3.100)
--       avresample:                YES (4.0.0)
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Lapack:                      NO
--     Eigen:                       NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/pi/opencv/opencv-4.4.0/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.16)
--     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython2.7.so (ver 2.7.16)
--     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.16.2)
--     install path:                lib/python2.7/dist-packages/cv2/python-2.7
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.7.3)
--     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.3)
--     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.16.2)
--     install path:                lib/python3.7/dist-packages/cv2/python-3.7
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:                          
--     ant:                         /usr/bin/ant (ver 1.10.5)
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Install to:                    /usr/local
-- -----------------------------------------------------------------
-- 
-- Configuring incomplete, errors occurred!
See also "/home/pi/opencv/opencv-4.4.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/opencv/opencv-4.4.0/build/CMakeFiles/CMakeError.log".

**Comment by marxenegls** [comment]
which tutorial/guide did you follow to compile tensorflow on raspbian /pi ?

error: the following arguments are required: -p/--prototxt, -m/--model 

from stackoverflow ;

"cv2.dnn.readNetFromTensorflow takes your Protobuf file .pb and configuaration file of your model .pbtxt to load your saved model.

net.forward() - Runs a forward pass to compute the net output.

your detection i.e net.forward() will give Numpy ndarray as output which you can use it to plot box on the given input image. " 

"https://stackoverflow.com/questions/59409692/return-type-of-net-forward" 
&
did you convert .proto model files to .py
$ protoc models --python_out= .

**Comment by berak** [comment]
@Pasadenasman , 

>  Configuring incomplete, errors occurred!

this is due to:

    CMake Error at cmake/OpenCVModule.cmake:288 (message):
    No modules has been found: /home/pi/opencv_contrib-4.4.0/modules

it did not find the contrib modules, and built opencv without.

>  reckonpi.py: error: the following arguments are required: -p/--prototxt, -m/--model

you tried to hack the args in the argparser, but it won't work as long as it has `required=True`, and it would need to be `default=`, not `help=`

so, read that blogpost again, and call it properly like:

    $ python3 reconnaissance_objets.py --prototxt MobileNetSSD_deploy.prototxt.txt --model MobileNetSSD_deploy.caffemodel

then, please close this issue, it's not a library bug, and problems like yours should go to https://answers.opencv.org instead

**Comment by Pasadenasman** [comment]
thanks for responding. yeah that was pretty messed up. i ve started from a fresh build. sorry for posting in wrong section.
