### ISSUE TITLE
opencv 4.2.0 gets different results for the same picture with different size.

### ISSUE THREAD

**Issue by AnnieXuY** [opencv/opencv#18443]
##### System information (version)
- OpenCV = 4.2.0
- Operating System / Platform => CentOS Linux release 7.7.1908 
- Compiler => gcc version 4.8.2

##### Detailed description

I used the opencv dnn module for object_detection, using ssd_mobilenet_v1_0.75_depth_coco from the TensorFlow 1 Detection Model Zoo, and now running into a strange problem.

When the input image size is 2160x1080, the recognition result is null, but after scaling the image to 1920x1080, it can recognize person correctly? Is this a bug? What should be done about it?

Please see annex for input images.
[test-images.zip](https://github.com/opencv/opencv/files/5288003/test-images.zip)

**Comment by sjang42** [comment]
It could be a memory issue

**Comment by AnnieXuY** [comment]
> It could be a memory issue

I just encountered another situation, when the input file is 3840x2160, it can recognize person correctly, but when the 480p image is input, it recognizes nothing.

Please see annex for input images.
[bigface.zip](https://github.com/opencv/opencv/files/5289718/bigface.zip)
