### ISSUE TITLE
test_calib3d: usac_Homography.accuracy crash (Debug+Windows)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#18454]
http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-win64-vc14-debug/builds/11259 (since Aug 15)

```
[ RUN      ] usac_Homography.accuracy
Process returned: 3221226505
```

3.4 branch looks like not affected.

**Comment by aitikgupta** [comment]
3.4 branch does not have this test.

**Comment by alalek** [comment]
bug introduced by #17683
/cc @ivashmak @vpisarev
