### ISSUE TITLE
Android platform armeabi-v7a  runtime error cv::error(): OpenCV(4.4.0) 

### ISSUE THREAD

**Issue by worldhe** [opencv/opencv#18463]
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => Android 7.1.1 armeabi-v7a
- Compiler => Android Studio 4.0.1    NDK 21.3.6528147    Gradel 6.1.1

##### Detailed description
Compilation is complete and an error is reported when running on the device, the error message is as follows:
`2020-09-30 11:30:38.461 6794-6810/com.example.demo E/cv::error(): OpenCV(4.4.0) Error: Requested object was not found (could not open directory: /data/app/com.example.demo-2/base.apk!/lib/armeabi-v7a) in glob_rec, file /build/master_pack-android/opencv/modules/core/src/glob.cpp, line 267
2020-09-30 11:30:38.461 6794-6810/com.example.demo E/cv::error(): OpenCV(4.4.0) Error: Requested object was not found (could not open directory: /data/app/com.example.demo-2/base.apk!/lib/armeabi-v7a) in glob_rec, file /build/master_pack-android/opencv/modules/core/src/glob.cpp, line 267
2020-09-30 11:30:38.461 6794-6810/com.example.demo E/cv::error(): OpenCV(4.4.0) Error: Requested object was not found (could not open directory: /data/app/com.example.demo-2/base.apk!/lib/armeabi-v7a) in glob_rec, file /build/master_pack-android/opencv/modules/core/src/glob.cpp, line 267
2020-09-30 11:30:38.461 6794-6810/com.example.demo E/cv::error(): OpenCV(4.4.0) Error: Requested object was not found (could not open directory: /data/app/com.example.demo-2/base.apk!/lib/armeabi-v7a) in glob_rec, file /build/master_pack-android/opencv/modules/core/src/glob.cpp, line 267
2020-09-30 11:30:38.461 6794-6810/com.example.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xec1610e1 in tid 6810 (Timer-1)`
Please help me to find out what caused it, I am very grateful.

**Comment by zihaom** [comment]
Why is this closed? I am experiencing the exact issue...

**Comment by dpanic** [comment]
I have the same issue.

While for me it is only error without SIGSERV and exiting the app.
But on ARM64, it is segfault.

**Comment by dpanic** [comment]
I fixed this by compiling OpenCV with this option:
```
-D OPENCV_DISABLE_FILESYSTEM_SUPPORT=ON
```

**Comment by phillies** [comment]
Same issue on 4.5.1, 4.5.2 and 4.5.4

**Comment by Dev-Czle** [comment]
i met the same issue in 4.5.5

**Comment by YangRiverJiang** [comment]
same issue in 4.6.0

**Comment by andreyshmelev** [comment]
same issue 4.7.0

**Comment by chris-praxis** [comment]
same issue (4.5.5-dev)

**Comment by chris-praxis** [comment]
Does anyone have a fix?  I get essentially the same error as OP when calling 'open' on a cv::VideoWriter.  This used to work, so I think the issue is likely external to OpenCV, something with the SDK?

**Comment by chris-praxis** [comment]
The fix for me was to add CAP_OPENCV_MJPEG to my VideoWriter open call as seen here: https://github.com/opencv/opencv/issues/22920#issuecomment-1340677356

**Comment by MarouaneMan** [comment]
The solution of @dpanic (disabling the filesystem `-DOPENCV_DISABLE_FILESYSTEM_SUPPORT=ON`) works but it will turn off all the filesystem support, which is not desired in some cases.

After digging, I found out that opencv introduced an option in version 4.5.2 called **Thread plugins**, it's enabled by default, and the first thing that a simple **cv::resize** do, is to try to load a parallel backend, like OPENMP or TBB.. but if they're disabled, it will [fallback](https://github.com/opencv/opencv/blob/588ddf1b181aa7243144b27d65fc7690fb89e344/modules/core/src/parallel/registry_parallel.impl.hpp#L41) and try to load plugins from the directory, hence the [cv::glob](https://github.com/opencv/opencv/blob/588ddf1b181aa7243144b27d65fc7690fb89e344/modules/core/src/parallel/plugin_parallel_wrapper.impl.hpp#L225)

So the solution is : `-DPARALLEL_ENABLE_PLUGINS=OFF`

**Comment by chris-praxis** [comment]
I forgot to mention that while passing CAP_OPENCV_MJPEG to 'VideoWriter::open' fixes this for me, doing so crashes iOS, so this is a platform-specific fix.  Setting ```-DPARALLEL_ENABLE_PLUGINS=OFF``` may work if you're building OpenCV but I'm currently not.
