### ISSUE TITLE
Load RTree model file

### ISSUE THREAD

**Issue by pdycp3** [opencv/opencv#18468]
Ptr<RTrees> model;
    model->load("D:\\data\\colmatest\\filename_to_save.xml");
    if (!model)
    {
        cout << "Load File Failed" << endl;
    }

why model is empty?
![image](https://user-images.githubusercontent.com/45677507/94674758-416c9e00-034b-11eb-85e1-cc7d8f05049d.png)

**Comment by berak** [comment]
> why model is empty?

because load() is a static method, that returns a new object, use it like:

    Ptr<RTrees> mdl = RTrees::load("some/path")

(currently you're just "throwing it away")

**Comment by pdycp3** [comment]
thank you , i have seen it before ,but ignored it 
![image](https://user-images.githubusercontent.com/45677507/94779927-40df1080-03fa-11eb-8c76-b6518901f9b7.png)
