### ISSUE TITLE
Multithreading acts differently in Python and C++

### ISSUE THREAD

**Issue by tim-hilt** [opencv/opencv#18474]
##### System information (version)

- OpenCV => 4.5.0
- Operating System / Platform => Linux 64 Bit
- Compiler => GCC/G++

##### Python

1. Extract local features from images using `ORB_create()`
2. Match one Feature-Matrix against all others using `BFMatcher(NORM_HAMMING)`-class
3. Look at active processor-threads

##### C++

- Repeat the same steps for C++ with equivalent code

I see two active threads when using Python, whereas there's only one in C++. However, `print(cv2.getNumThreads())`/ `std::cout << cv::getNumThreads() << "\n";` yields `4` in both cases.

**Comment by tim-hilt** [comment]
@alalek can you suggest what i should add to the question above to complete it?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

OpenCV initializes ThreadPool on-demand only. Probably used algorithms don't use parallel optimization.
Complete minimal reproducer should be added to make the problem reproducible.

OpenCV supports many tools beyond of the "Look at active processor-threads" approach.
For performance profiling refer to this Wiki page: https://github.com/opencv/opencv/wiki/Profiling-OpenCV-Applications

**Comment by tim-hilt** [comment]
Thanks! These were some helpful hints. Closing...
