### ISSUE TITLE
Build opencv Error ! Libopencv_imgcodecs.so.4.4.0: undefined reference to ...

### ISSUE THREAD

**Issue by duongvvuet** [opencv/opencv#18471]
##### System information (version)

- OpenCV => :grey_question:4.4.0
- Operating System / Platform => :grey_question:Linux
- Compiler => :grey_question:Cmake

##### Detailed description

![Screenshot from 2020-09-30 20-14-40](https://user-images.githubusercontent.com/51939859/94694116-aed5fa00-035e-11eb-83ed-ac38afe98122.png)

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D WITH_TBB=ON \
    -D WITH_V4L=ON \
    -D WITH_QT=ON \
    -D WITH_OPENGL=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D BUILD_opencv_python3=ON \
    -D PYTHON3_EXECUTABLE=/usr/bin/python3.6m \
    -D PYTHON3_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
    -D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/local/lib/python3.6/dist-packages/numpy/core/include \
    -D BUILD_EXAMPLES=ON ..

```

I build opencv vs opencv_contrib. This is my problem, somebody help me with ..!

**Comment by Matthew-Bradley** [comment]
@alalek What issue is this a duplicate of? I'm having this issue too.

**Comment by Matthew-Bradley** [comment]
it may be https://github.com/apache/incubator-mxnet/issues/10217 ?

**Comment by Matthew-Bradley** [comment]
see https://github.com/opencv/opencv/issues/20286

cmake doesn't add -ltiff

**Comment by Matthew-Bradley** [comment]
also https://github.com/opencv/opencv/issues/20876
