### ISSUE TITLE
Including the unsupported/Eigen/CXX11/Tensor with eigen creates problem for iOS build

### ISSUE THREAD

**Issue by AlvarHHM** [opencv/opencv#18472]
https://github.com/opencv/opencv/blob/fc1a15626226609babd128e043cf7c4e32f567ca/modules/core/include/opencv2/core/eigen.hpp#L63

https://github.com/opencv/opencv/commit/456e88a8a424d66e839158babcda2b8380d1cc79

I was trying to migrate from OpenCV 4.1 to 4.4 on my iOS app build, but it wouldn't compile with the following error

> template argument for template parameter must be a type

 Once I removed these lines of code from this commit, the problem was resolved.

Note that these "unsupported" modules are provided by third party and thus are not maintained by the official Eigen team.

**Comment by alalek** [comment]
relates #17320
