### ISSUE TITLE
How to show the offset difference value between base image and reference image in OpenCV?

### ISSUE THREAD

**Issue by sayom88** [opencv/opencv#18480]
How can we show the offset difference value between base image and reference image when there is a position change.

suppose there is a position change between a base and a reference image.....now via OpenCV,I would want to show how much is the difference value in terms of the position change? If you share the code snippet of how to do that, then that will be much helpful.

**Comment by dkurt** [comment]
Please do not GitHub issues for usage questions.

There are https://stackoverflow.com/questions/tagged/opencv, https://answers.opencv.org/questions/

**Comment by sayom88** [comment]
Hi @dkurt  I have already raised this question in https://answers.opencv.org/questions/, but nobody has answered it....hence I gave it a try here.....would you mind helping me here please
