### ISSUE TITLE
CMake: Potential bug (code review)

### ISSUE THREAD

**Issue by Mizux** [opencv/opencv#18490]
Disclaimer: not tested, just reviewing the code...

Since CMake now provide a [multi configuration ninja generator](https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html), I guess this check is wrong:
https://github.com/opencv/opencv/blob/a3e7c2d8e3ebb32a5ee58c8f3265dacead318572/CMakeLists.txt#L1032-L1034

Fix: please add `Ninja Multi-Config` (or simply `Multi-Config` :thinking:)  to the regexp...

**Comment by krush11** [comment]
Hi i would like to work on this issue. I have read about Ninja Multi-Config, but i dont know how to proceed. A bit of help would be great.

**Comment by mshabunin** [comment]
I don't see any problems with Ninja Multi-Config generator:
```.sh
> cmake -G"Ninja Multi-Config" ../opencv
> cmake --build . --config Release
> cmake --build . --config Debug
> ls bin
bin
├── Debug
│   ├── opencv_annotation
│   ├── opencv_interactive-calibration
│   ├── opencv_version
│   └── opencv_visualisation
└── Release
    ├── opencv_annotation
    ├── opencv_interactive-calibration
    ├── opencv_version
    └── opencv_visualisation

> ninja --version
1.10.1
> cmake --version
cmake version 3.18.4
```
Please, file a new issue with clear reproducer if you meet any problems.

**Comment by Mizux** [comment]
@mshabunin the problem is not in the build but in the log at configure -_-, the built-in CMake variable `CMAKE_BUILD_TYPE` does not make sens for multi-configuration generator so the message is disable if you are using XCode or VisualStudio since there are multi-config generator.....

AND it is the same for ninja-multi config....

i.e. your trace is irrelevant here, please display the trace for `cmake -S. -Bbuild -G "Ninja Multi-Config"` instead...

**Comment by Mizux** [comment]
should be rewrite as:
```cmake
if(CMAKE_GENERATOR MATCHES "Xcode|Visual Studio|Multi-Config")
  status("    Configurations:"  ${CMAKE_CONFIGURATION_TYPES}) 
else()
  status("    Configuration:"  ${CMAKE_BUILD_TYPE}) 
endif() 
```

**Comment by alalek** [comment]
Multi-config may lead to issues with tests like this: #12369 (with MSVS)

IMHO, using multi-config is a tricky stuff. Also used `try_compile()` configurations should be investigated (probably "Release" config should be used for that).

@Mizux I believe this should work. However please keep name of `Configuration` entry (avoid `Configurations`)

**Comment by Mizux** [comment]
@alalek then you should thank @krush11 ;)
