### ISSUE TITLE
OpenCV 4.4 on Windows 10 - multiprocessing does not work

### ISSUE THREAD

**Issue by kamarshi** [opencv/opencv#18502]
##### System information (version)
OpenCV - 4.4
Platform - Windows 10 64 bit
Python - 3.8.5

##### Detailed description
[example.zip](https://github.com/opencv/opencv/files/5322783/example.zip)

Hello,

OpenCV 4.4 on Windows 10 does not appear to support multi-processing (multi-threading works). It fails with the message: "ImportError: DLL load failed while importing cv2: The specified module could not be found." This failure happens in the spawned worker task. Main process works okay. A simple code sample is attached. Your help would be much appreciated.

Regards,

Vijay

**Comment by alalek** [comment]
How did you get OpenCV?

**Comment by kamarshi** [comment]
Hello,

Thanks for your quick response.  I downloaded the OpenCV repo (github.com/opencv) and used the 4.4.0 tag to build

Vijay

**Comment by kamarshi** [comment]
Attached file
[opencv_build_information.txt](https://github.com/opencv/opencv/files/5323581/opencv_build_information.txt)
 is a dump of cv2.getBuildInformation()

**Comment by kamarshi** [comment]
Is there an update?  Please let me know if I can provide any additional info.

Vijay

**Comment by alalek** [comment]
Python 3.8 breaks DLLs searching process (google for `os.add_dll_directory`).
Did you tried Python 3.7?

BTW, don't expect good performance results from OpenCV in such configurations (CPU resources may be oversubscribed)

As a workaround you may try to disable loading of `cv2` from the main task. Import 'cv2' by workers only.

**Comment by kamarshi** [comment]
Hello,

Thank you for pointing me at the issue.  I tried adding the directory path for opencv dlls like this:

with os.add_dll_directory(<absolute_path_of_opencv_dlls>):
    import cv2

This way of invoking cv2 module again works in main code, fails in spawned worker process.

I also ran dlldiag executable on  C:\Program Files\Python38\Lib\site-packages\cv2\python-3.8\cv2.cp38-win_amd64.pyd

It was able to discover all dependencies and load them.  Looking at these dependency dlls, I am sure I am loading the correct path for opencv dlls.  But cv2 is still failing to load for spawned processes.  Would much appreciate your help.

Vijay

**Comment by kamarshi** [comment]
Hello,

I now have a better understanding of the issue.  Basically:
1.  Global import of cv2 will not work
2.  Worker task needs to import cv2 "inline" before using the code
3.  Main launcher function can also import cv2 inline, but it will only work if this is done after spawning worker tasks.

Please see attached updated example code.  This works.  But this is severely limiting the scope of my software.  I would still like to see this issue fixed.

Vijay
[example.zip](https://github.com/opencv/opencv/files/5344050/example.zip)

**Comment by alalek** [comment]
@kamarshi Thank you for updates!

Please take a look on this workaround: #18930
