### ISSUE TITLE
OpenCv 4.4's performance is worse than OpenCv 3.4

### ISSUE THREAD

**Issue by dominota** [opencv/opencv#18503]
##### System information (version)
- OpenCV => 4.4 vs 3.4
- Operating System / Platform => Windows 10 x64
- Compiler => Visual Studio 2017

##### Detailed description
I built OpenCv 4.4 and OpenCv 3.4 from source codes with the same settings (Nvidia CUDA SDK 10, Intel TBB 2017) then i ran a sample tracking from this source https://github.com/laeklee/fDSST_cpp/tree/master/src , captured an mp4 file with image size of 1280x720. I get two different results in terms of accuracy and speed (NO GPU required). 
With OpenCv 3.4: Hight accuracy in tracking and high speed: up to 64 FPS
With OpenCv 4.4: NOT accuracy in tracking and low speed: about 28 FPS

##### Steps to reproduce
The code to run tracker is here https://github.com/laeklee/fDSST_cpp/blob/master/src/runtracker.cpp

I also saw a report from NVIDIA about performance of OpenCv versions. It also showed the same conclusion like me but is in GPU.

https://forums.developer.nvidia.com/t/performance-of-opencv3-4-vs-opencv4-on-the-xavier-solved/66143/4

**Comment by alalek** [comment]
Please run OpenCV performance tests first

**Comment by dominota** [comment]
> 
> 
> Please run OpenCV performance tests first

I dont build tests because my PC is limited the resources. I just compare the sample project build for both OpenCv 3.4.0 and OpenCv 4.4.0

**Comment by alalek** [comment]
In case of performance issues this topic may help with investigation:
- https://github.com/opencv/opencv/wiki/Profiling-OpenCV-Applications
