### ISSUE TITLE
GAPI: How to invoke the same set of operation for group of images using Gcomputation 

### ISSUE THREAD

**Issue by subhamvs** [opencv/opencv#18523]
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => Ubuntu 18.04 64 bit
- Compiler => g++

##### Detailed description

I want to detect edges for the set of images using the Canny Edge detector. I thought of using GAPI to improve the performance of the operations been mentioned.  How to initialize and use the Graph computation with a vector of input Mat objects? I found the API call in the following link and implemented in my code but I am not sure it is the correct way of using it in the graph [https://docs.opencv.org/master/d9/dfe/classcv_1_1GComputation.html#ad20ff09a9522ef4203266d3bc5bb52e9](url)
Please find the code given below,

##### Steps to reproduce

```
#include <iostream>
#include <string>

#include <opencv2/imgcodecs.hpp>
#include <opencv2/gapi.hpp>
#include <opencv2/gapi/core.hpp>
#include <opencv2/gapi/imgproc.hpp>

int main(int argc, char** argv)
{
	if (argc != 3) {
		std::cout << "./main <input_folder> <output_folder>" << std::endl;
		return -1;
	}

	std::string input_folder = std::string(argv[1]);
	std::string output_folder = std::string(argv[2]);

	std::vector<cv::String> fn;
	cv::glob(input_folder+"/*.png", fn, false);
        
	std::vector<cv::Mat> images;
	std::vector<cv::Mat> edges;

	cv::GMat gimages;
        cv::GMat gedges;

	size_t count = fn.size();

	for (size_t i=0; i<count; i++) {
		images.push_back(cv::imread(fn[i]));
	}

	gedges = (cv::gapi::Canny(gimages, 32, 128, 3, true));

	cv::GComputation ac(gimages, gedges);
        ac.apply(images,edges);

	for (size_t i=0; i<count; i++) {
		std::cout << std::string(output_folder+"/"+std::to_string(i)+".png") << std::endl; 
                cv::imwrite(std::string(output_folder+"/"+std::to_string(i)+".png").c_str(), edges[i]);
		
        }

	return 0;
}

```
Is it the correct way of invoking the API call? How to invoke the same set of operations (Here, Canny Edge) for the set of images?

**Comment by alalek** [comment]
> improve the performance of the operations

AFAIK, Primary G-API goal is improving performance of whole complex pipelines instead of single operations.

So you can use `cv::parallel_for_()` + `cv::Canny()` for this task.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by TolyaTalamanov** [comment]
@subhamvs Hi, you should call `apply` for every input image (`cv::Mat` )separately.
FYI in case you want to process video you can use `streaming`: https://github.com/opencv/opencv/blob/master/modules/gapi/test/streaming/gapi_streaming_tests.cpp#L166
