### ISSUE TITLE
openCV build fails at opencv_cudafilters

### ISSUE THREAD

**Issue by sindkarhm** [opencv/opencv#18543]
##### Detailed description
I am trying to install opencv 4.3.0 on Ubuntu 20.04 LTS with CUDA 11.0 and cuDNN 8.0.3 support but it fails when I build using make -j12. Getting below error:
[ 61%] Building CXX object modules/cudafilters/CMakeFiles/opencv_cudafilters.dir/src/filtering.cpp.o
[ 61%] Linking CXX static library …/…/lib/libopencv_cudafilters.a
**[ 61%] Built target opencv_cudafilters**
**make: *** [Makefile:163: all] Error 2**

If I build with just make: Getting below error
**make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:7090: modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/blank_layer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4783: modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
make: *** [Makefile:163: all] Error 2**

No error in the build configuration.
Build configuration:
**make
-D CMAKE_BUILD_TYPE=RELEASE
-D CMAKE_C_COMPILER=/usr/bin/gcc-8
-D CMAKE_INSTALL_PREFIX=/usr/local
-D INSTALL_PYTHON_EXAMPLES=ON
-D INSTALL_C_EXAMPLES=ON
-D BUILD_DOCS=OFF
-D BUILD_PERF_TESTS=OFF
-D BUILD_TESTS=OFF
-D BUILD_PACKAGE=OFF
-D BUILD_EXAMPLES=OFF
-D WITH_TBB=ON
-D ENABLE_FAST_MATH=1
-D CUDA_FAST_MATH=1
-D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.0
-D WITH_CUDA=ON
-D WITH_CUBLAS=ON
-D WITH_CUFFT=ON
-D WITH_NVCUVID=ON
-D WITH_IPP=OFF
-D WITH_V4L=ON
-D WITH_1394=OFF
-D WITH_GTK=ON
-D WITH_QT=OFF
-D WITH_OPENGL=ON
-D WITH_EIGEN=ON
-D WITH_FFMPEG=ON
-D WITH_GSTREAMER=ON
-D BUILD_JAVA=OFF
-D BUILD_opencv_python3=ON
-D BUILD_opencv_python2=OFF
-D BUILD_NEW_PYTHON_SUPPORT=ON
-D OPENCV_SKIP_PYTHON_LOADER=ON
-D OPENCV_GENERATE_PKGCONFIG=ON
-D OPENCV_ENABLE_NONFREE=ON
-D OPENCV_EXTRA_MODULES_PATH=…/…/opencv_contrib-4.3.0/modules
-D WITH_CUDNN=ON
-D OPENCV_DNN_CUDA=ON
-D CUDA_ARCH_BIN=7.5
-D CUDA_ARCH_PTX=7.5
-D CUDNN_LIBRARY=/usr/local/cuda-11.0/lib64/libcudnn.so.8.0.3
-D CUDNN_INCLUDE_DIR=/usr/local/cuda-11.0/include …**

CUDA version :
$ cat /usr/local/cuda/version.txt
**CUDA Version 11.0.228**

NVIDIA driver:
$ nvidia-smi
**Driver Version: 450.51.06**

$ dpkg -l | grep cuda-toolkit
**cuda-toolkit-11-0 11.0.3-1 amd64 CUDA Toolkit 11.0 meta-package
nvidia-cuda-toolkit 10.1.243-3 amd64 NVIDIA CUDA development toolkit**

I am not getting what I am missing or doing wrong. Or openCV, CUDA and cuDNN version are not compatible.

Thanks in advance for any help.

**Comment by chirag4798** [comment]
Why was the issue closed without a resolution?

**Comment by ajgnet** [comment]
I'm having the same issue. Was there ever a resolution?
