### ISSUE TITLE
A typo in source code of Edge-aware demosaicing.

### ISSUE THREAD

**Issue by Watesoyan** [opencv/opencv#18558]
https://github.com/opencv/opencv/blob/1b443219ed181124978ed8627fb2da8db42765ab/modules/imgproc/src/demosaicing.cpp#L1587
The code
`D[2] = (S[-sstep-1] + S[-sstep+1] + S[sstep-1] + S[sstep+1]) >> 2;`
should be modifed to
`D[2] = (S[-sstep-1] + S[-sstep+1] + S[sstep-1] + S[sstep+1] + 2) >> 2;`

**Comment by alalek** [comment]
Please add description why this should be changed.

**Comment by Watesoyan** [comment]
> Please add description why this should be changed.
opencv/modules/imgproc/src/demosaicing.cpp
Line 1596 in 1b44321 writes
                    `D[0] = (S[-sstep-1] + S[-sstep+1] + S[sstep-1] + S[sstep+1] + 2) >> 2;`
It means that we use ceiling after dividing 4.
For consisitence, I think Line 1587 should be the same.
