### ISSUE TITLE
why gpu is more time-consuming than cpu in 'resize'?

### ISSUE THREAD

**Issue by shaoming20798** [opencv/opencv#18576]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 18.04, Linux x86_64
- Compiler => gcc/g++

##### Detailed description
```python
#!/usr/bin/env python
# coding=utf-8

import cv2
import time
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "7"

img_path = '/home/20798/3.jpg'
img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
resize_width = 104
resize_height = 104
loop_cnt = 100000

time_start = time.time()
for _ in range(loop_cnt):
    resize_img = cv2.resize(img, (resize_height, resize_width), interpolation=cv2.INTER_LINEAR)
print('cpu time: {:.2f} us'.format((time.time() - time_start) * 1e6 / loop_cnt))

device_img = cv2.cuda_GpuMat()
time_start = time.time()
for _ in range(loop_cnt):
    device_img.upload(img)
    resize_device_img = cv2.cuda.resize(device_img, (resize_height, resize_width), interpolation=cv2.INTER_LINEAR)
    resize_img = resize_device_img.download()
print('gpu time: {:.2f} us'.format((time.time() - time_start) * 1e6 / loop_cnt))
```
And the result is:
**cpu time: 69.07 us
gpu time: 456.22 us**

The gpu's informations are detailed as follows:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+
|   0  GeForce GTX 108...  On   | 00000000:3D:00.0 Off |                  N/A |
| 23%   32C    P2    54W / 250W |   1415MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:3E:00.0 Off |                  N/A |
| 29%   52C    P2    77W / 250W |   1606MiB / 11178MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:3F:00.0 Off |                  N/A |
| 23%   15C    P8     8W / 250W |    515MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:40:00.0 Off |                  N/A |
| 24%   44C    P2    72W / 250W |   3643MiB / 11178MiB |     52%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:43:00.0 Off |                  N/A |
| 23%   17C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:44:00.0 Off |                  N/A |
| 23%   17C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:45:00.0 Off |                  N/A |
| 26%   48C    P2    76W / 250W |   3643MiB / 11178MiB |     52%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 00000000:46:00.0 Off |                  N/A |
| 23%   33C    P2    53W / 250W |   1151MiB / 11178MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by 756890911** [comment]
GPU每次下载图片到cpu的耗时应该比较高吧
