### ISSUE TITLE
/usr/local/include/bits/cpp_type_traits.h:72:1: error: unknown type name ‘namespace’;

### ISSUE THREAD

**Issue by songzeceng** [opencv/opencv#18586]
##### System information (version)
- OpenCV => 3.0.0
- Operating System / Platform => Ubuntu 16.04 x86-64
- Compiler => gcc 7.5, g++7.5

##### Steps to reproduce
1、Just clone the source code of opencv3.0.0 and opencvcontrib, get into the source directory of opencv, build and get into a new temp folder ```build``` using ```root@sundata:/data/szc/opencv/opencv-3.0.0# cd build/```.
2、Then apt-get install some 3rd party library and copy the requested include file into the /usr/local/include and modify some .h files to get over some build error of opencv.
3、Then try to build opencv with command ```root@sundata:/data/szc/opencv/opencv-3.0.0/build# cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..```. 
4、I see ```-- Configuring incomplete, errors occurred!
See also "/data/szc/opencv/opencv-3.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/data/szc/opencv/opencv-3.0.0/build/CMakeFiles/CMakeError.log".``` at the end of debug info and the content of file build/CMakeFiles/CMakeError.log are shown below
```
/usr/local/include/bits/cpp_type_traits.h:72:1: error: unknown type name ‘namespace’; did you mean ‘isspace’?
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
 isspace
/usr/local/include/bits/cpp_type_traits.h:72:1: error: attributes should be specified before the declarator in a function definition
In file included from /usr/local/include/ptlib/unix/ptlib/contain.h:162:0,
                 from /usr/local/include/ptlib/object.h:44,
                 from /usr/local/include/ptlib/psync.h:43,
                 from /usr/local/include/ptlib/critsec.h:34,
                 from /usr/local/include/ptlib/contain.h:42,
                 from /usr/local/include/ptlib.h:56,
                 from /usr/local/include/ptlib/pfactory.h:38,
                 from /usr/local/include/ptlib/plugin.h:23,
                 from /usr/local/include/sys/videoio.h:42,
                 from /data/szc/opencv/opencv-3.0.0/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:
/usr/local/include/cmath:43:10: fatal error: ext/type_traits.h: No such file or directory
 #include <ext/type_traits.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.```

**Comment by alalek** [comment]
> /usr/local/include/bits/cpp_type_traits.h

You have broken build environment on your machine.
There is nothing to fix in OpenCV.

---

> 3.0.0

Outdated versions are not supported.
