### ISSUE TITLE
The CPU and GPU versions of the demosaicing function produce different results for the same debayer code.

### ISSUE THREAD

**Issue by mxjxbx** [opencv/opencv#18580]
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

The CPU and GPU version of the demosaising function produce different results for the same debayer code. 
So passing the exact same debayer code to the GPU version and the non GPU version of the demosaicing function result in two vastly different results. See the following code example. You would want the output to be "True". Instead it is always false.

##### Steps to reproduce
```.cpp
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudaarithm.hpp>
int main()
{
    cv::Mat input = cv::Mat::zeros(100, 100, CV_8UC1);
    cv::Mat out_gpu, out_cpu;
    cv::randu(input, 0, 256); 
    int debayer_code = cv::COLOR_BayerBG2BGR;

    // GPU part
    cv::cuda::GpuMat src(100, 100, CV_8UC1);
    cv::cuda::GpuMat dst(100, 100, CV_8UC3);
    src.upload(input);
    cv::cuda::demosaicing(src, dst, debayer_code);
    dst.download(out_gpu);

    // CPU part
    cv::demosaicing(input, out_cpu, debayer_code);

    // Compare results
    bool result = (cv::sum(out_cpu != out_gpu) == cv::Scalar(0, 0, 0, 0));
    result ? std::cout << "True" : std::cout << "False";   // Should be True, but it's always false
}
 ```

##### Issue submission checklist

 - [x] I report the issue, it's not a question

**Comment by mxjxbx** [comment]
I will keep the issue closed until I test out more.

**Comment by JChatillon** [comment]
I have the same issue using OpenCV 4.4, with Cuda 10.0.
First time I use those functions, so I don't know if this is also present in previous versions of OpenCV, but this seems to be a too big issue to be missed.
