### ISSUE TITLE
Data fields in struct cv::UsacParams not accesible through Python

### ISSUE THREAD

**Issue by aleromar** [opencv/opencv#18595]
##### System information (version)
Working on master branch (0d3e05f9b3a3c8223d9e80d89d8176fdbe3158a4)
Relevant file: calib3d.hpp

##### Detailed description

When making use of cv::[SolvePnPRansac](https://github.com/opencv/opencv/blob/master/modules/calib3d/src/solvepnp.cpp#L355) the last argument is of type UsacParams. It is indeed possible to create an object of type UsacParams in Python since the structure is prefixed by CV_EXPORTS_W_SIMPLE in the c++ code. However, editing any of the data fields within the structure is not possible as the fields have not been prepended with CV_PROP_RW.

I've modified the implementation to add CV_PROP_RW to each field within UsacParams struct. Then declared a constructor.
The constructor implementation I added it to solvepnp.cpp. The constructor includes the values that previously could be found under UsacParams struct. I can now access each field appropriately. 

Do I push my fix for this and create a PR?

##### Steps to reproduce

- Build the repo
- Under build directory, `make install`
- Enter a python terminal
- `import cv2`
- `up = cv2.UsacParams()`
- `up.confidence` -> Error

**Comment by alalek** [comment]
Sure, feel free to prepare PR.

**Comment by aleromar** [comment]
Great, I'll do!
Cheers
