### ISSUE TITLE
incorrect result 

### ISSUE THREAD

**Issue by yanjun3235** [opencv/opencv#18596]
opencv: 4.4.0
The result is correct with mini-caffe, but opencv is incorrect.  the code is :

cv::dnn::Net net = cv::dnn::readNetFromCaffe("lnet106_112.prototxt",
		"lnet106_112.caffemodel");
net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);

cv::Mat m = cv::imread("onet.jpg");
cv::dnn::blobFromImage(m, 0.0078125f, cv::Size(112, 112), cv::Scalar(127.5f, 127.5f, 127.5f));
net.setInput(InputBlob);

std::vector<cv::String> output_names = { "bn6_3" };
std::vector<cv::Mat> OutBlobs;
net.forward(OutBlobs, output_names);

float* points = (float*)(OutBlobs[0].data);

for (int i = 0; i < 106; i++)
{
	...
}
points has negative value,  someone can help me ?  zip file is caffe model
[lnet106_112.zip](https://github.com/opencv/opencv/files/5391389/lnet106_112.zip)

**Comment by dkurt** [comment]
Please report a bug properly. There is no criteria what are correct results.

**Comment by yanjun3235** [comment]
sorry, my mistake.  the model is detect face landmark。
I upload test_image_and_result.zip, it contains two images,  onet.jpg is test image, result.jpg is opencv and caffe result image
flowing code is my code

**1. opencv code:**
cv::dnn::Net net = cv::dnn::readNetFromCaffe("lnet106_112.prototxt", "lnet106_112.caffemodel");
net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);

cv::Mat m = cv::imread("onet.jpg");

int show_H = 640, show_W = 640;
cv::Mat draw_img;
cv::resize(m, draw_img, cv::Size(show_W, show_H));

cv::Mat InputBlob = cv::dnn::blobFromImage(m, 1.0/128.0f, cv::Size(112, 112),
	cv::Scalar(127.5f, 127.5f,127.5f));
net.setInput(InputBlob);

std::vector<cv::String> output_names = { "bn6_3" };
std::vector<cv::Mat> OutBlobs;
net.forward(OutBlobs, output_names);

float* points = (float*)(OutBlobs[0].data);

for (int i = 0; i < FEATURE_POINTS_NUM; i++)
{
	int x1 = points[2 * i] * show_W;
	int y1 = points[2 * i + 1] * show_H;

	cv::Point pt = cv::Point(x1, y1);
	cv::circle(draw_img, pt, 2, cv::Scalar(0, 0, 250), 2);
}

cv::imshow("xxx", draw_img);
auto key = cv::waitKey(0);

**2. mini-caffe code:**
caffe::SetMode(caffe::CPU, -1);

std::shared_ptr<caffe::Net> net;
net.reset(new caffe::Net("lnet106_112.prototxt"));
net->CopyTrainedLayersFrom("lnet106_112.caffemodel");

cv::Mat mm = cv::imread("onet.jpg");
cv::Mat src;
cv::resize(mm, src, cv::Size(112, 112));

int show_H = 640, show_W = 640;
cv::Mat draw_img;
cv::resize(mm, draw_img, cv::Size(show_W, show_H));

cv::Mat data;
src.convertTo(data, CV_32FC3);

std::vector<cv::Mat> bgr;
cv::split(data, bgr);

bgr[0].convertTo(bgr[0], CV_32FC1, 0.0078125f, (0 - 127.5f) * 0.0078125f);
bgr[1].convertTo(bgr[1], CV_32FC1, 0.0078125f, (0 - 127.5f) * 0.0078125f);
bgr[2].convertTo(bgr[2], CV_32FC1, 0.0078125f, (0 - 127.5f) * 0.0078125f);

caffe::Blob* input_blob = net->blob_by_name("data").get();
int num_channel = input_blob->channels();

const int bias = input_blob->offset(0, 1, 0, 0);
const int bytes = bias * sizeof(float);
memcpy(input_blob->mutable_cpu_data() + 0 * bias, bgr[0].data, bytes);
memcpy(input_blob->mutable_cpu_data() + 1 * bias, bgr[1].data, bytes);
memcpy(input_blob->mutable_cpu_data() + 2 * bias, bgr[2].data, bytes);

net->Forward();

auto detection_out = net->blob_by_name("bn6_3");

for (int i = 0; i < 106; i++)
{
	int x = detection_out->data_at(0, 2 * i) * show_W;
	int y = detection_out->data_at(0, 2 * i + 1) * show_H;

	cv::Point pt = cv::Point(x, y);
	cv::circle(draw_img, pt, 2, cv::Scalar(0, 0, 250), 2);
}

cv::imshow("xxx", draw_img);
auto key = cv::waitKey(0);

[test_image_and_result.zip](https://github.com/opencv/opencv/files/5398566/test_image_and_result.zip)

**Comment by yanjun3235** [comment]
resolved
