### ISSUE TITLE
Minor typing error in a clang macro name in cvdef.h

### ISSUE THREAD

**Issue by emmenlau** [opencv/opencv#18597]
##### System information (version)
- OpenCV => 4.5.0
- Operating System / Platform => All
- Compiler => clang

##### Detailed description

There is a minor typing error in:
https://github.com/opencv/opencv/blob/8bf451a3e0c6af796691ee336abd157b762fd6af/modules/core/include/opencv2/core/cvdef.h#L93

The name `__clang_major` is not correct! It should be replaced with `__clang_major__`. See the reference documentation here: https://clang.llvm.org/docs/LanguageExtensions.html#builtin-macros

**Comment by alalek** [comment]
Thank you for the report!

relates #17567
