### ISSUE TITLE
pow of Mat with negative elements

### ISSUE THREAD

**Issue by aligoglos** [opencv/opencv#18601]
I've tried to convert some codes from MATLAB to c++ with OpenCV but I got stuck in this line :
MATLAB code :
`t3 = real((ISimMatrix .* QSimMatrix) .^ 0.02)`
I re implemented this line in c++ with:
```
cv::Mat t2, t3;
t2 = ISimMatrix.mul(QSimMatrix);
cv::pow(t2, lambda, t3); 
```

both `ISimMatrix `and `QSimMatrix` are 2D double matrix that might contain negative numbers, The problem is when the multiple of them power to 0.02, In MATLAB result is 2D complex matrix but in OpenCV result is `Mat_<double>` witch some elements are `nan` that cause all next calculations go wrong.

How can I implement `pow `function  that support negative power ?

thanks.

OpenCV => 4.4
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2019

**Comment by dkurt** [comment]
Please do not use GotHib issues for usage question. We need this to track bug reports and feature requests.
