### ISSUE TITLE
Confusing name of OPENCV_EXTRA_MODULES_PATH

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv#18610]
CMake build configuration is using `OPENCV_EXTRA_MODULES_PATH` variable, which points to `opencv_contrib` directory not `opencv_extra` directory as the name may suggest. Perhaps `OPENCV_CONTRIB_MODULES_PATH` would be a better name choice?

**Comment by alalek** [comment]
It is not only for `opencv_contrib` modules. You can use it to specify any custom module, so "extra" is valid here.

`opencv_extra` is used to store test data for now (but history of this module has another contents too).
`opencv_testdata` may be better name, but probably "wont fix".

**Comment by pauljurczak** [comment]
Agree with renaming `opencv_extra` to `opencv_testdata` being a better solution. Not a big problem. When you run out of things to do...

**Comment by zteffi** [comment]
Could we at least extract `OPENCV_TEST_DATA_PATH` as a CMake variable, similar to `OPENCV_EXTRA_MODULES_PATH`? As far as I know, the only mention of `OPENCV_TEST_DATA_PATH` was removed in  #18195 in linux installation tutorial and is currently only mentioned in _Building OpenCV for Tegra with CUDA_ tutorial.

**Comment by mshabunin** [comment]
@zteffi , there is `OPENCV_TEST_DATA_PATH` cmake option, it is used to enable installation of test data and helper scripts to directory set by `OPENCV_TEST_DATA_INSTALL_PATH` parameter. This feature is not widely used and can have problems, in most cases developers run tests from the build directory and do not perform installation.

Feel free to try this feature and add related parts to the documentation.
