### ISSUE TITLE
No such module OpenCV2 on import in Xcode

### ISSUE THREAD

**Issue by bluesailor45** [opencv/opencv#18612]
##### System information (version)
- OpenCV2 => 4.3
- Operating System / Platform => MacOS 10.15.6
- Compiler => Xcode  11.7

after successfully installed cocoapod 'OpenCV2', set the $(inherited) flag in Xcode Target settings then 'pod update' and opened the project.xcworkspace, the import 'OpenCV2' statement in Xcode resulted in no such module 'OpenCV2'. Xcode Project Navigator is listing 'OpenCV2' under Pods. I am able to import additional installed cocoa pods (e.g. 'SwiftyZeroMQ5'. The 'no such module error for OpenCV2 is also occurring when I install only OpenCV2 cocoapod.

When pod changing to OpenCV2 4.4 and pod update:
 CocoaPods could not find compatible versions for pod "OpenCV2": In Podfile: OpenCV2 (~> 4.4

**Comment by kopyl** [comment]
@bluesailor45 were you able to fix it? I still can't import it....
