### ISSUE TITLE
Problem With installing

### ISSUE THREAD

**Issue by Aromik** [opencv/opencv#18645]
Hello!
I'm installing OpenCV to the Raspberry Pi with the latest version of Raspberry Pi OS and other software. I do everything like in the tutorials in the internet, But on the 83rd percent there is a error:
`[ 83%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
during IPA pass: inline
/home/pi/Downloads/opencv-master/modules/python/src2/cv2.cpp:2124:1: internal compiler error: Segmentation fault
 }
 ^
0x76aae11f ???
	../sysdeps/unix/sysv/linux/arm/sigrestorer.S:64
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/build.make:63: modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:19671: modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`
Is it a real bug or do I do something wrong?

**Comment by alalek** [comment]
> Raspberry Pi
> internal compiler error

You have lack of available memory.
Retry with `make -j1` or use cross-compilation or disable "python bindings" if you don't need them.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Aromik** [comment]
This problem exists when I run this command
