### ISSUE TITLE
opencv4.5.0 and opencv4.5.0-openvino

### ISSUE THREAD

**Issue by nawara72** [opencv/opencv#18648]
Hi 
Just would like to know what's the difference between opencv4.5.0 and opencv4.5.0-openvino? does opencv4.5.0 have no openvino support?

Thanks

**Comment by alalek** [comment]
`-openvino`, `-cvsdk` are special source code tags for releases of corresponding products.

---

> does opencv4.5.0 have no openvino support?

This is wrong assumption.
Check details here: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend
