### ISSUE TITLE
Compiler doesn't support baseline optimization flags

### ISSUE THREAD

**Issue by juxiangwu** [opencv/opencv#18657]
##### System information (version)

- OpenCV == 4.5.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

build opencv.js flowing [https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html](tutorial_js_setup), and got errors:
```
python ./platforms/js/build_js.py build_js
Args: Namespace(build_dir='build_js', build_doc=False, build_flags=None, build_perf=False, build_test=False, build_wasm=False, build_wasm_intrin_test=False, clean_build_dir=False, cmake_option=None, config='D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0\\platforms\\js\\opencv_js.config.py', config_only=False, disable_wasm=False, emscripten_dir='d:\\tools\\emsdk\\upstream\\emscripten', enable_exception=False, opencv_dir='D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0', simd=False, skip_config=False, threads=False)
Check dir D:\Develop\opensources\machine-vision\opencv-4.5.0\build_js (create: True, clean: False)
Check dir D:\Develop\opensources\machine-vision\opencv-4.5.0 (create: False, clean: False)
Check dir d:\tools\emsdk\upstream\emscripten (create: False, clean: False)
=====
===== Config OpenCV.js build for default target
=====
Executing: ['cmake', '-DENABLE_PIC=FALSE', '-DCMAKE_BUILD_TYPE=Release', "-DCMAKE_TOOLCHAIN_FILE='d:\\tools\\emsdk\\upstream\\emscripten\\cmake\\Modules\\Platform\\Emscripten.cmake'", "-DCPU_BASELINE=''", "-DCPU_DISPATCH=''", '-DENABLE_PRECOMPILED_HEADERS=OFF', '-DWITH_IPP=OFF', '-DWITH_MSMF=OFF', '-DWITH_TBB=OFF', '-DCV_TRACE=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DWITH_1394=OFF', '-DWITH_ADE=OFF', '-DWITH_VTK=OFF', '-DWITH_EIGEN=OFF', '-DWITH_FFMPEG=OFF', '-DWITH_GSTREAMER=OFF', '-DWITH_GTK=OFF', '-DWITH_GTK_2_X=OFF', '-DWITH_IPP=OFF', '-DWITH_JASPER=OFF', '-DWITH_JPEG=OFF', '-DWITH_WEBP=OFF', '-DWITH_OPENEXR=OFF', '-DWITH_OPENGL=OFF', '-DWITH_OPENVX=OFF', '-DWITH_OPENNI=OFF', '-DWITH_OPENNI2=OFF', '-DWITH_PNG=OFF', '-DWITH_TBB=OFF', '-DWITH_TIFF=OFF', '-DWITH_V4L=OFF', '-DWITH_OPENCL=OFF', '-DWITH_OPENCL_SVM=OFF', '-DWITH_OPENCLAMDFFT=OFF', '-DWITH_OPENCLAMDBLAS=OFF', '-DWITH_GPHOTO2=OFF', '-DWITH_LAPACK=OFF', '-DWITH_ITT=OFF', '-DWITH_QUIRC=OFF', '-DBUILD_ZLIB=ON', '-DBUILD_opencv_apps=OFF', '-DBUILD_opencv_calib3d=ON', '-DBUILD_opencv_dnn=ON', '-DBUILD_opencv_features2d=ON', '-DBUILD_opencv_flann=ON', '-DBUILD_opencv_gapi=OFF', '-DBUILD_opencv_ml=OFF', '-DBUILD_opencv_photo=ON', '-DBUILD_opencv_imgcodecs=OFF', '-DBUILD_opencv_shape=OFF', '-DBUILD_opencv_videoio=OFF', '-DBUILD_opencv_videostab=OFF', '-DBUILD_opencv_highgui=OFF', '-DBUILD_opencv_superres=OFF', '-DBUILD_opencv_stitching=OFF', '-DBUILD_opencv_java=OFF', '-DBUILD_opencv_java_bindings_generator=OFF', '-DBUILD_opencv_js=ON', '-DBUILD_opencv_python2=OFF', '-DBUILD_opencv_python3=OFF', '-DBUILD_opencv_python_bindings_generator=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_PACKAGE=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DWITH_PTHREADS_PF=OFF', '-DCV_ENABLE_INTRINSICS=OFF', '-DBUILD_WASM_INTRIN_TESTS=OFF', "-DCMAKE_C_FLAGS='-s USE_PTHREADS=0 '", "-DCMAKE_CXX_FLAGS='-s USE_PTHREADS=0 '", 'D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0']
Re-run cmake no build system arguments
-- OpenCV: system-specific configuration file is not found: 'Emscripten'
-- Detected processor: x86
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:593 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:296 (ocv_compiler_optimization_options)
  CMakeLists.txt:610 (include)


-- Configuring incomplete, errors occurred!
See also "D:/Develop/opensources/machine-vision/opencv-4.5.0/build_js/CMakeFiles/CMakeOutput.log".
See also "D:/Develop/opensources/machine-vision/opencv-4.5.0/build_js/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "./platforms/js/build_js.py", line 273, in <module>
  File "./platforms/js/build_js.py", line 196, in config
  File "./platforms/js/build_js.py", line 23, in execute
__main__.Fail: Child returned: 1
```

**Comment by alalek** [comment]
At first, always run CMake from clean build directory after changing of any build options and/or in cases of changing dependencies.

> Compiler doesn't support baseline optimization flags:

This means that CMake is not able to use provided compiler (something is misconfigured).

---

> Windows 10 64 Bit

Not supported officially for JavaScript builds.
Consider using Linux build environment.

---

> CMakeFiles/CMakeOutput.log
> CMakeFiles/CMakeError.log

Try to analyse content of these files.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by tianjie** [comment]
> ##### System information (version)
> * OpenCV == 4.5.0
> * Operating System / Platform => Windows 10 64 Bit
> * Compiler => Visual Studio 2019
> 
> ##### Detailed description
> build opencv.js flowing [https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html](tutorial_js_setup), and got errors:
> 
> ```
> python ./platforms/js/build_js.py build_js
> Args: Namespace(build_dir='build_js', build_doc=False, build_flags=None, build_perf=False, build_test=False, build_wasm=False, build_wasm_intrin_test=False, clean_build_dir=False, cmake_option=None, config='D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0\\platforms\\js\\opencv_js.config.py', config_only=False, disable_wasm=False, emscripten_dir='d:\\tools\\emsdk\\upstream\\emscripten', enable_exception=False, opencv_dir='D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0', simd=False, skip_config=False, threads=False)
> Check dir D:\Develop\opensources\machine-vision\opencv-4.5.0\build_js (create: True, clean: False)
> Check dir D:\Develop\opensources\machine-vision\opencv-4.5.0 (create: False, clean: False)
> Check dir d:\tools\emsdk\upstream\emscripten (create: False, clean: False)
> =====
> ===== Config OpenCV.js build for default target
> =====
> Executing: ['cmake', '-DENABLE_PIC=FALSE', '-DCMAKE_BUILD_TYPE=Release', "-DCMAKE_TOOLCHAIN_FILE='d:\\tools\\emsdk\\upstream\\emscripten\\cmake\\Modules\\Platform\\Emscripten.cmake'", "-DCPU_BASELINE=''", "-DCPU_DISPATCH=''", '-DENABLE_PRECOMPILED_HEADERS=OFF', '-DWITH_IPP=OFF', '-DWITH_MSMF=OFF', '-DWITH_TBB=OFF', '-DCV_TRACE=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DWITH_1394=OFF', '-DWITH_ADE=OFF', '-DWITH_VTK=OFF', '-DWITH_EIGEN=OFF', '-DWITH_FFMPEG=OFF', '-DWITH_GSTREAMER=OFF', '-DWITH_GTK=OFF', '-DWITH_GTK_2_X=OFF', '-DWITH_IPP=OFF', '-DWITH_JASPER=OFF', '-DWITH_JPEG=OFF', '-DWITH_WEBP=OFF', '-DWITH_OPENEXR=OFF', '-DWITH_OPENGL=OFF', '-DWITH_OPENVX=OFF', '-DWITH_OPENNI=OFF', '-DWITH_OPENNI2=OFF', '-DWITH_PNG=OFF', '-DWITH_TBB=OFF', '-DWITH_TIFF=OFF', '-DWITH_V4L=OFF', '-DWITH_OPENCL=OFF', '-DWITH_OPENCL_SVM=OFF', '-DWITH_OPENCLAMDFFT=OFF', '-DWITH_OPENCLAMDBLAS=OFF', '-DWITH_GPHOTO2=OFF', '-DWITH_LAPACK=OFF', '-DWITH_ITT=OFF', '-DWITH_QUIRC=OFF', '-DBUILD_ZLIB=ON', '-DBUILD_opencv_apps=OFF', '-DBUILD_opencv_calib3d=ON', '-DBUILD_opencv_dnn=ON', '-DBUILD_opencv_features2d=ON', '-DBUILD_opencv_flann=ON', '-DBUILD_opencv_gapi=OFF', '-DBUILD_opencv_ml=OFF', '-DBUILD_opencv_photo=ON', '-DBUILD_opencv_imgcodecs=OFF', '-DBUILD_opencv_shape=OFF', '-DBUILD_opencv_videoio=OFF', '-DBUILD_opencv_videostab=OFF', '-DBUILD_opencv_highgui=OFF', '-DBUILD_opencv_superres=OFF', '-DBUILD_opencv_stitching=OFF', '-DBUILD_opencv_java=OFF', '-DBUILD_opencv_java_bindings_generator=OFF', '-DBUILD_opencv_js=ON', '-DBUILD_opencv_python2=OFF', '-DBUILD_opencv_python3=OFF', '-DBUILD_opencv_python_bindings_generator=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_PACKAGE=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DWITH_PTHREADS_PF=OFF', '-DCV_ENABLE_INTRINSICS=OFF', '-DBUILD_WASM_INTRIN_TESTS=OFF', "-DCMAKE_C_FLAGS='-s USE_PTHREADS=0 '", "-DCMAKE_CXX_FLAGS='-s USE_PTHREADS=0 '", 'D:\\Develop\\opensources\\machine-vision\\opencv-4.5.0']
> Re-run cmake no build system arguments
> -- OpenCV: system-specific configuration file is not found: 'Emscripten'
> -- Detected processor: x86
> CMake Error at cmake/OpenCVCompilerOptimizations.cmake:593 (message):
>   Compiler doesn't support baseline optimization flags:
> Call Stack (most recent call first):
>   cmake/OpenCVCompilerOptions.cmake:296 (ocv_compiler_optimization_options)
>   CMakeLists.txt:610 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Develop/opensources/machine-vision/opencv-4.5.0/build_js/CMakeFiles/CMakeOutput.log".
> See also "D:/Develop/opensources/machine-vision/opencv-4.5.0/build_js/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "./platforms/js/build_js.py", line 273, in <module>
>   File "./platforms/js/build_js.py", line 196, in config
>   File "./platforms/js/build_js.py", line 23, in execute
> __main__.Fail: Child returned: 1
> ```

Fix by upgrading CMake to latest version,  hope to help u

**Comment by jatinsha** [comment]
I was cross-compiling OpenCV Host: x64 --> Target: ARM and faced a similar issue. As a workaround, I disabled the optimizations using the compiler flags and that got me through.

-D CV_DISABLE_OPTIMIZATION=ON -D CPU_BASELINE="" -D CPU_DISPATCH=""

**Comment by kritzel** [comment]
@jatinsha: Thank you so much. After a day of frustrating struggles I discovered this thread and your hints did the trick for me. 

My environment:
OpenCV Version: 4.5.3 
CMake Version: 3.20.3
Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30137 for x86 (yes, I am kind of "cross-compiling" for x86 on a 64 bit system)
SDK: Windows SDK Version 10.0.19041.0

**Comment by alalek** [comment]
@kritzel You can find logs for "win32" builds on [CI](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-4.x&width=7).

**Comment by kopyl** [comment]
> I was cross-compiling OpenCV Host: x64 --> Target: ARM and faced a similar issue. As a workaround, I disabled the optimizations using the compiler flags and that got me through.
> 
> -D CV_DISABLE_OPTIMIZATION=ON -D CPU_BASELINE="" -D CPU_DISPATCH=""

@jatinsha unfortunately did not help :(

```
IPHONEOS_DEPLOYMENT_TARGET=17.0 cmake \
  -D CMAKE_TOOLCHAIN_FILE=../opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake \
  -D PLATFORM=OS64 \
  -D IOS_ARCH=arm64 \
  -D BUILD_SHARED_LIBS=OFF \
  -D BUILD_opencv_world=OFF \
  -D OPENCV_MODULES_TO_BUILD=core,imgproc,dnn \
  -D CMAKE_INSTALL_PREFIX=/Users/olehkopyl/Downloads/open-cv/make_install_outputs_ios \
  -D ENABLE_BITCODE=ON \
  -D HAVE_CXX11=ON \
  -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
  -D CV_DISABLE_OPTIMIZATION=ON \
  -D CPU_BASELINE="" \
  -D CPU_DISPATCH="" \
  ..
  ```
