### ISSUE TITLE
Getting error 'ImportError: DLL load failed while importing cv2: The specified module could not be found.' while importing cv2

### ISSUE THREAD

**Issue by mina-sarofem** [opencv/opencv#18653]
hi all, i am new to opencv-pyhton. my problem is that i am getting this error 'ImportError: DLL load failed while importing cv2: The specified module could not be found.' while importing cv2. 

my python interpreter version is 3.9 
windows 8.1 

also i have installed visual studio tools and C++ compiler. 

Please help me, i am trying to solve this issue from 7 days ago. 

Thanks in advance.

**Comment by SvnGms** [comment]
Which windows version are u running? May u need to install the windows media feature package:
https://github.com/skvark/opencv-python/issues/154

**Comment by mina-sarofem** [comment]
Hi,

    Will it work for windows 8.1?
