### ISSUE TITLE
Usage of ippicv in a commercial environment

### ISSUE THREAD

**Issue by rahulmohang** [opencv/opencv#18659]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Android/ios
- Compiler => :grey_question:

##### Detailed description

Can you please let me know whether I need to procure a license from Intel for usage of ippicv or not, in case I need to use OpenCV in a commercial product?

**Comment by alalek** [comment]
You need to follow the license statements attached to this package (you can find them in opencv_3rdparty repository from ippicv* branches).

Licensing of "standalone" IPP is not required to use IPPICV with OpenCV.

**Comment by rahulmohang** [comment]
Thank you Alexander. 

However, the license text seems to be the same EULA for ippicv:-

https://github.com/opencv/opencv_3rdparty/blob/ippicv/master_20170822/ippEULA.txt. 

Is this the one you meant?

**Comment by rahulmohang** [comment]
@alalek
