### ISSUE TITLE
 error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

### ISSUE THREAD

**Issue by Dolphinzzx** [opencv/opencv#18666]
##### System information (version)

- OpenCV = 4.5.0
- Operating System / Platform => Raspbian 32 Bit
- Compiler => Visual Studio 2017

##### Detailed description

This is my program:
import cv2
img = cv2.imread('test.png',1)
cv2.imshow('Camera Capture', img)

![image](https://user-images.githubusercontent.com/35594203/97256254-8b16ae80-184d-11eb-8914-62d7b1f0b4dc.png)
When i run this program, it will prompt "error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'"
![image](https://user-images.githubusercontent.com/35594203/97256316-ada8c780-184d-11eb-8fa5-d7d527a3e6c3.png)

**Comment by wolfedale** [comment]
I'm hitting the same issue when using Ubuntu.

**Comment by cassidylinhares** [comment]
Im getting the same issue with debian on aarch64

**Comment by alalek** [comment]
duplicate of #18461

**Comment by vijaysekark** [comment]
it will run only if login as root user
