### ISSUE TITLE
1-D Bar code support

### ISSUE THREAD

**Issue by JinhengZhang** [opencv/opencv#18668]
Hi, 
OpenCV has well-working QR codes detection and decoding algorithm. 
However, 1-D Bar code algorithm is not mature in OpenCV. 
So we are working on it with some undergraduates in SUSTech. 
There' been some progress already.
Let's start the discussion about it here!

**Comment by shubhamcodez** [comment]
I'd like to work on it with you guys

**Comment by darkliang** [comment]
We are undergraduates in SUSTech, and we have done some achievements. Our temporary repo is [here](https://github.com/WangberlinT/Barcode/tree/dev), and we are transferring it to opencv_contrib. We split the algorithm into two steps, detect and decode.
### Detect
We evaluated the orientation consistency of the gradient in each pixel centered square region. Then we connect the pixels with high consistency and regard the region shaped like rectangle as a barcode region.
### Decode
16 lines through all the bars are collected from the previously located regions, and then each line is decoded. The final result is the result of the vote.
### Problem
- The size of square is crucial, and if it is smaller than the widest bar, the gradient of each pixel in this square is zero. **The size of square is hard to determined.**
- In decode part, the **binarization of image is not good enough**. It is very susceptible to light and ambience.
- The located region sometimes is not accurate, the result of decode is influenced by this situation.
Hope for your suggestions. @shubhamcodez

**Comment by shubhamcodez** [comment]
I looked into the code.
I saw that you have added normalization, if that's not working, one way of tackling the image lighting problem would be to manipulate the image by decreasing it's highlights and adjusting contrast. can we do it ?

**Comment by WangberlinT** [comment]
Yes, we have done histogram equalization before binarization, and it's better now.
In addition, I'd like to confirm that we should submit pr to opencv_contrib instead of this repo right? It is mentioned in the contribution guidelines that all new algorithms need to be submitted to opencv_contrib.
@shubhamcodez  @alalek

**Comment by alalek** [comment]
By default, all new algorithms should be contributed into `opencv_contrib` repository.

/cc @vpisarev

**Comment by WangberlinT** [comment]
okay, the new issue is https://github.com/opencv/opencv_contrib/issues/2756

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/23666

**Comment by asmorkalov** [comment]
@mshabunin I believe that we can close it as soon as your PR is merged.

**Comment by asmorkalov** [comment]
PR integrated.
