### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'dnn' opencv 4.5.0-dev

### ISSUE THREAD

**Issue by eltonfernando** [opencv/opencv#18686]
- OpenCV =>  4.5.0-dev
- Operating System / Platform => Ubuntu 20.04LTS
- Compiler => C++ Compiler:                /usr/bin/c++  (ver 9.3.0)
- GPU=> gtx 1660

the error happens after executing
self.net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
AttributeError: module 'cv2' has no attribute 'dnn'

it works, it shows that the contrib was compiled
cv2.bgsegm.createBackgroundSubtractorMOG()

cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_C_COMPILER=/usr/bin/gcc-8 \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_CUDA=ON -D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D CUDA_ARCH_BIN=7.5 \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D BUILD_opencv_cudacodec=OFF \
-D PYTHON_EXECUTABLE=/usr/bin/python3 \
-D OPENCV_EXTRA_MODULES_PATH=\~/opencv_contrib/modules \
-D OPENCV_PYTHON3_INSTALL_PATH=\~/.local/lib/python3.8/site-packages \
-D BUILD_EXAMPLES=OFF -D WITH_PROTOBUF=OFF \
-D LDFLAGS=-L/usr/local/cuda/lib64 \..

 --   NVIDIA CUDA:                   YES (ver 10.1, CUFFT CUBLAS FAST_MATH)
 --     NVIDIA GPU arch:             75
 --     NVIDIA PTX archs:
-- 
--   cuDNN:                         YES (ver 7.6.5)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/smartflux/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.8.5)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.8.so (ver 3.8.5)
--     numpy:                       /home/smartflux/.local/lib/python3.8/site-packages/numpy/core/include (ver 1.19.2)
--     install path:                /home/smartflux/.local/lib/python3.8/site-packages/cv2/python-3.8
-- 
--   Python (for build):            /usr/bin/python3
-- 
--   Java:                          
--     ant:                         NO
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Install to:                    /usr/local
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/smartflux/opencv/build

make -j4 && sudo make install

**Comment by jurgenweber** [comment]
Yeah, I am getting this rls also

**Comment by jurgenweber** [comment]
I am getting:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 105, in worker
    initializer(*initargs)
  File "/raid/face_recognition/files/main.py", line 240, in worker
    faces, face_confidences          = cv.detect_face(small_frame) # , enable_gpu=False)
  File "/usr/local/lib/python3.7/site-packages/cvlib/face_detection.py", line 34, in detect_face
    net = cv2.dnn.readNetFromCaffe(prototxt, caffemodel)
AttributeError: module 'cv2' has no attribute 'dnn'
```

FREEBSD 12.1.

```
rm -rf build

mkdir build
cd    build
pwd

cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.5.0/modules \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_CXX11=ON \
      -DBUILD_PERF_TESTS=OFF \
      -DWITH_XINE=ON \
      -DBUILD_TESTS=OFF \
      -DENABLE_PRECOMPILED_HEADERS=OFF \
      -DCMAKE_SKIP_RPATH=ON \
      -DBUILD_WITH_DEBUG_INFO=OFF \
      -DWITH_PROTOBUF=OFF \
      -Wno-dev ../

make -j8
make install
```

I tried against

OpenCV => 4.5.0 
OpenCV => 4.40

**Comment by jurgenweber** [comment]
ok! I found in the build output:

```
-- Module opencv_dnn_objdetect disabled because opencv_dnn dependency can't be resolved!
-- Module opencv_dnn_superres disabled because opencv_dnn dependency can't be resolved!
-- Module opencv_mcc disabled because opencv_dnn dependency can't be resolved!
-- Module opencv_text disabled because opencv_dnn dependency can't be resolved!
```

I think its hte      -DWITH_PROTOBUF=OFF \ as protobuff seems to be a dependency.

**Comment by jurgenweber** [comment]
so I can confirm that turning proto buff back on, ermoves this error and its in the list of modules to be built, by now make fails on protobuf. I put that option in because it fails on protobuf.

I removed the system install of protobuf:

```
# pkg remove protobuf
```

and this seems to be the problem, the build process is picking up headers from the system, I picked up the idea from [here](https://github.com/bazelbuild/bazel/issues/8053#issuecomment-490795477).

it now builds and installs and I have dnn.... and everything works. :)

**Comment by eltonfernando** [comment]
tried with protobuf and without it

didn't work for me

I did what @jurgenweber  did, I looked at all the compiler output, but I found nothing.

**the strange thing is that I see the module going up in the installation**

Installing: /usr/local/lib/libopencv_dnn.so
-- Installing: /usr/local/include/opencv4/opencv2/dnn.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/all_layers.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/dict.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/dnn.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/dnn.inl.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/layer.details.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/layer.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/shape_utils.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/utils/inference_engine.hpp
-- Installing: /usr/local/include/opencv4/opencv2/dnn/version.hpp

@jurgenweber thank you so much for your time

**Comment by eltonfernando** [comment]
I added the tags and solved it for me

I don't know which one solved it

-D BUILD_opencv_world=ON \
-D OPENCV_ENABLE_NONFREE=ON \
-D WITH_PROTOBUF=ON \

**Comment by alalek** [comment]
> WITH_PROTOBUF=ON

This one.
Protobuf is prerequisite for `opencv_dnn` module (enabled by default).

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
