### ISSUE TITLE
OpenCV build error in Ubuntu 18.04

### ISSUE THREAD

**Issue by Mass17** [opencv/opencv#18690]
##### OpenCV build error during build > make
I use Python 3.6.9 in my virtual environment and conda version 4.5.12. When I try to do **make**, I get the following error. 

[ 29%] Built target opencv_perf_reg
Scanning dependencies of target example_reg_map_test
[ 30%] Building CXX object modules/reg/CMakeFiles/example_reg_map_test.dir/samples/map_test.cpp.o
In file included from /home/m/opencv_contrib/modules/reg/samples/map_test.cpp:43:0:
/home/m/opencv/modules/imgcodecs/include/opencv2/imgcodecs/imgcodecs_c.h:1:2: error: #error "This header with legacy C API declarations has been removed from OpenCV. Legacy constants are available from legacy/constants_c.h file."
 #error "This header with legacy C API declarations has been removed from OpenCV. Legacy constants are available from legacy/constants_c.h file."
  ^~~~~
modules/reg/CMakeFiles/example_reg_map_test.dir/build.make:62: recipe for target 'modules/reg/CMakeFiles/example_reg_map_test.dir/samples/map_test.cpp.o' failed
make[2]: *** [modules/reg/CMakeFiles/example_reg_map_test.dir/samples/map_test.cpp.o] Error 1
CMakeFiles/Makefile2:3696: recipe for target 'modules/reg/CMakeFiles/example_reg_map_test.dir/all' failed
make[1]: *** [modules/reg/CMakeFiles/example_reg_map_test.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Please help me to fix it.

**Comment by eltonfernando** [comment]
Show me the tags with cmake that you are using
