### ISSUE TITLE
OpenCV DNN with yolo samples computes completly different results then standalone yolo

### ISSUE THREAD

**Issue by MarvinKlemp** [opencv/opencv#18696]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

##### Detailed description

To check if my OpenCV installation with CUDA and cuDNN was successful I tryed to run the sample code using the example from the yolo website (https://pjreddie.com/darknet/yolo/).

But I'm getting completly different (and also wrong) results using OpenCV.

CMake / Make ran without errors compiling OpenCV.

Using OpenCV:
![Screenshot from 2020-10-29 17-29-14](https://user-images.githubusercontent.com/5558190/97603358-a5e35180-1a0c-11eb-810e-09f610fed708.png)

Using Darknet:
![predictions](https://user-images.githubusercontent.com/5558190/97603449-c0b5c600-1a0c-11eb-88de-7f884ca1dc6c.jpg)
):

#### OpenCV:
Running the object_detection sample:
```
./example_dnn_object_detection 
    --config=/path/to/yolov3.cfg 
    --model=/path/to/yolov3.weights 
    --input=/path/to/dog.jpg 
    --classes=/path/to/coco.names
```

#### Darknet
Run Darknet as described in https://pjreddie.com/darknet/yolo/

**Comment by alalek** [comment]
Missing pre-processing settings:

```.diff
 ./example_dnn_object_detection 
     --config=/path/to/yolov3.cfg 
     --model=/path/to/yolov3.weights 
     --input=/path/to/dog.jpg 
+    yolo
```

(`models.yml` file should be in the current directory)

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by MarvinKlemp** [comment]
@alalek Thanks.
