### ISSUE TITLE
infinity loop in function CirclesGridFinder::getFirstCorner() in circlesgrid.cpp 

### ISSUE THREAD

**Issue by EXing** [opencv/opencv#18713]
Hi, I find that there is an infinity loop bug inside the CirclesGridFinder::getFirstCorner() in circlesgrid.cpp :

    bool isInsider[cornersCount];
    for (size_t i = 0; i < cornersCount; i++) {
        isInsider[i] = doesIntersectionExist(largeSegments[i], smallSegments);
    }

    int cornerIdx = 0;
    bool waitOutsider = true;

    for (;;) {
        if (waitOutsider) {
            if (!isInsider[(cornerIdx + 1) % cornersCount])
                waitOutsider = false;
        } else {
            if (isInsider[(cornerIdx + 1) % cornersCount])
                break;
        }

        cornerIdx = (cornerIdx + 1) % cornersCount;
    }

if isInsider[] is all false, then this will become an infinity loop, that's where my program stuck.

**Comment by alalek** [comment]
Could you please capture inputs before OpenCV API call? (into `cv::FileStorage` or `.npy` Python files)

**Comment by EXing** [comment]
> Could you please capture inputs before OpenCV API call? (into `cv::FileStorage` or `.npy` Python files)

I did one modification on the code:

-  directly provide candidate circle centres instead of using blobDetector.

'
bool findCirclesGrid(const std::vector<Point2f> &points_, Size patternSize,
                         OutputArray _centers, int flags,
                         const CirclesGridFinderParameters &parameters_ = CirclesGridFinderParameters());
'

The inputs are in the file. For the CirclesGridFinderParameters input, I use OpenCV master branch's default constructor. 
[debug.txt](https://github.com/opencv/opencv/files/5475874/debug.txt)
