### ISSUE TITLE
Opencv-python connect to USB camera 

### ISSUE THREAD

**Issue by Isquare1** [opencv/opencv#18715]
This is more of an enquiry/feature request than an issue report. I love opencv and it would be amazing if it would be possible to read a USB connected camera (in my case a Thorlabs DC1545M) - or is it now possible and I haven't been able to find how to do it? 

cap = cv2.VideoCapture(1)        ## this returns empty, id = 1 is my USB camera 

I've seen plenty of topics online of people requesting it from years ago, but it seems it hasn't been created yet.

**Comment by mshabunin** [comment]
OpenCV can capture video from USB-connected cameras, but it depends on platform, build configuration and supported camera interface. Please take a look: https://docs.opencv.org/master/d0/da7/videoio_overview.html

**Comment by ajithvallabai** [comment]
@Isquare1 you have install necessary drivers for your camera for being detected by opencv as a camera . you can contact the camera company's support, they would also have in their website either sdk or driver
