### ISSUE TITLE
How do I set the usage rate of GPU. Looking forward to your reply!

### ISSUE THREAD

**Issue by 2017ND** [opencv/opencv#18726]
When I need to run two different programs, one of which is to use DNN for GPU accelerated detection, usually need to set the utilization rate of GPU. I don't know how to do it. Please let me know. Thank you very much！

**Comment by alalek** [comment]
Such limitations are not in scope of OpenCV.
This may be handled by CUDA runtime tools. Ask here: https://forums.developer.nvidia.com/
