### ISSUE TITLE
dnn inference with flexible inputs is very slow on Intel GPUs

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#18723]
I'm compiling latest OpenCV with OpenVino 2021.1 (same issue with at least 2020.4) and when calling `net.forward()` with a new input size for the first time, it can take up to 40sec when regulare inference only takes <0.2sec.
Further forward are fast since OpenVino will "cache" whatever it generated.
This only happens on Intel GPUs, everything is ok on CPUs
My model is a CNN (think Unet) and I can share it by email if needed.

**Comment by dkurt** [comment]
Please take a look at https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#feature-cl_cache

**Comment by alalek** [comment]
Intel GPUs are utilized through OpenCL kernels which are constructed and compiled before launching (they are specialized for network sizes and actual devices to maximize performance, so there is no way to pre-generate them for all cases).

There is some kind of in-memory cache for compiler kernels, but there is no external "persistent" storage by default (it should be configured separately).
This can be done on [OpenCL runtime level](https://github.com/intel/compute-runtime) (cl_cache) and/or on OpenVINO level (see issue https://github.com/openvinotoolkit/openvino/issues/907 and PR https://github.com/openvinotoolkit/openvino/pull/2871 ).

There can't be fixed on OpenCV level at this moment.

**Comment by JulienMaille** [comment]
Thanks to both of you. Actually I already use the cl_cache trick. But I still hit a 40sec delay whenever the forward is run on an image with a new (w,h) size that has not yet been cached. Do you believe all that time is _just_ the compilation? I suppose cuda kernel are compiled on the fly too? But they don't show this huge delay.
To me this is a deal-breaker and I will probably revert to cpu/cuda inference because of this.

**Comment by alalek** [comment]
CUDA kernels are pre-compiled into binaries:
- you have a huge enough CUDNN binary
- performance may be suboptimal (especially for non-specialized "generic" cases)

> Do you believe all that time is just the compilation?

I believe yes.
In most cases this process is not even parallel. Primary optimization efforts are targeted on optimization of inference stage itself (not loading / initialization / reshaping on new size)

---

Possible workarounds:
- prepare cache
- control input sizes (resize image or clip center of image (by up-to 16 pixels) to reuse "existed" size). Issues are resize-artifacts or broken aspect ratio.

**Comment by dkurt** [comment]
First run might take some time. Have you analyzed first inference time for the same input size? Just to check that cl_cache is enabled correctly.

Also, it's better to have fixed input resolution or multiple networks for different resolutions.

**Comment by JulienMaille** [comment]
> First run might take some time. Have you analyzed first inference time for the same input size? Just to check that cl_cache is enabled correctly.
Yes it. First inference will take 20+sec and then only 100msec with same input size.
> Also, it's better to have fixed input resolution or multiple networks for different resolutions.
I already pad my images to % 32 I can't have fixed resolutions

**Comment by alalek** [comment]
OpenVINO has implemented OpenCL caching support.
Need to pass new option from OpenCV DNN module to IE.

**Comment by JulienMaille** [comment]
Thanks @alalek , should I get rid of the registry trick (pointing to the cache folder)?
What is the correct way to pass the option now?

**Comment by JulienMaille** [comment]
@alalek something like this? #19949
