### ISSUE TITLE
opencv4.4.0 useing  tensorflow2.3 pb model 

### ISSUE THREAD

**Issue by yuwanglang** [opencv/opencv#18733]
Hello, I have installed OpencV4.4.0. Now I want to call the PB model generated by TensorFlow2.3 through Opencv. What should I do?The FILE "tf_text_graph_det.py", "tf_text_graph_faster_rcnn.py", "tf_text_graph_mask_rcnn.py", "tf_text_graph_ssd.py", does the DNN folder in the opencv package still apply to the TENsorFlow2.3 PB model file?
The model files generated by my TensorFlow2.3 framework include:
Assets (Empty folder)
Variables (there are two files in the file: variables. Data-0000-of-00001 and variables. Index)
Saved_model. Pb.
I don't know how pipeline.config get?
Looking forward to hearing back?

**Comment by dkurt** [comment]
You need to convert SavedModel format to a frozen graph. See https://github.com/opencv/opencv/issues/16582#issuecomment-603819498
