### ISSUE TITLE
opencv dnn unsupported data type float16

### ISSUE THREAD

**Issue by dodler** [opencv/opencv#18735]
opencv-python-4.4.0.46
onnx                 1.6.0    
onnxmltools          1.7.0    
onnxruntime          1.4.0    

Hi, I'm using opencv dnn to load fp16 onnx model, but it fails with the following error

`cv2.error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-ucld1hvm/opencv/modules/dnn/src/onnx/onnx_graph_simplifier.cpp:527: error: (-210:Unsupported format or combination of formats) Unsupported data type: FLOAT16 in function 'getMatFromTensor'
`

My code:

`import cv2
import sys
net = cv2.dnn.readNetFromONNX(sys.argv[1]) 
img = cv2.cvtColor(cv2.imread("img.jpg"), cv2.COLOR_BGR2RGB)
img=cv2.resize(img, (224,224))
blob= cv2.dnn.blobFromImage(img, size=(224,224))
net.setInput(blob)
print(net.forward())`

It works well with original fp32 model. I get fp16 model using onnxmltools using this
`from onnxmltools.utils.float16_converter import convert_float_to_float16
`

The same problem occurs with int8 model.

**Comment by krush11** [comment]
@alalek May i work on this issue? Although i would need some help

**Comment by alalek** [comment]
Try convert FLOAT16 ONNX tensors to FP32 and check if it works (with adding some simple test):
- prepare .onnx model for reproducer (you may want to convert some model from [this list](https://github.com/opencv/opencv_extra/blob/4.5.0/testdata/dnn/download_models.py#L408) or try to generate synthetic models by [this script](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/onnx/generate_onnx_models.py))
- add tensor conversion to FP32
- prepare test with FP16 model

---

Alternative is creating Mat as CV_FP16 (master branch only), but we need to check/fix its usage through whole DNN library implementation (there are many places where FP32 is supported / expected only). This is long way.

**Comment by krush11** [comment]
I am sorry but as i am quite new to openCV(never used it actually). So i dont understand the structure of the code mostly. Although as far as i have figured out from the issue, changes required will be in [modules/dnn/src/onnx/onnx_graph_simplifier.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/onnx/onnx_graph_simplifier.cpp) file right? Also i have a basic idea what tests are but i have never run any tests for openCV or any other software (i am a new open source contributor :sweat_smile: ). Subsequently i might need help for the next few issues i try but then i will have a good idea of the codebase for my to solve issues on my own. Hope you understand :smile:

**Comment by zihaomu** [comment]
We have supported ONNX float16 model in #22337.
