### ISSUE TITLE
OpenCV 4.5 Release: can not open file VideoCapture

### ISSUE THREAD

**Issue by Thanh-Binh** [opencv/opencv#18737]
Dear all,
I have just downloaded and installed Release 4.5 in my Ubuntu 20.04LTS successfully.
I activated -DFFMEG=ON too.
In my C++ program, I usually use this code
``
   VideoCapture capture;
    capture.open("/home/user/myvideo.avi");
    if(!capture.isOpened())
       std::cout << "no capture" << std::endl;
``
I was very surprise that it can not open my video.
Could you please help me?
Thanks

**Comment by Thanh-Binh** [comment]
I looked at my compile log, 
cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_FFMPEG=1 -DBUILD_EXAMPLES=O -DOPENCV_EXTRA_MODULES_PATH=/home/binh/programs/opencv_contrib-4.5.0/modules ..
and found that FFMPEG is deactivated after compiling test
``
-- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
--   Found libavcodec, version 58.54.100
--   Found libavformat, version 58.29.100
--   Found libavutil, version 56.31.100
--   Found libswscale, version 5.5.100
-- Checking for module 'libavresample'
--   Found libavresample, version 4.0.0
-- WARNING: Can't build ffmpeg test code
-- include: /usr/include/x86_64-linux-gnu
-- lib: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so;/usr/lib/x86_64-linux-gnu/libavresample.so
`
But the manual compiling is successful
g++ -c ffmpeg_test.cpp -I/usr/include/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu/ -lavcodec -lavformat -lavresample -lavutil -lswscale

I really do not understand why it failed by cmake!

**Comment by alalek** [comment]
> WARNING: Can't build ffmpeg test code

Try to uncomment `message()` statement [here](https://github.com/opencv/opencv/blob/4.5.0/modules/videoio/cmake/detect_ffmpeg.cmake#L88).

Check this issue: https://github.com/opencv/opencv/issues/16603#issuecomment-587011399

**Comment by Thanh-Binh** [comment]
finally I found the compiling problems as follows:
1. by compiling you have to use at least 2 flags: -DFFMPEG =1 -DWITH_OPENCL=1
2. even doing in step 1, we have to change CMakeFiles for some video test/performance test so that they have a links to openCL

Background: FFMPEG needs libavutils, and libavutils depends on openCL!

**Comment by Thodoris1999** [comment]
Just wanted to mention that I had the exact same issue and cleaning my build folder fixed it (ffmpeg was detected correctly).
