### ISSUE TITLE
Can't open video generated by `VideoWriter()` with QuickTime

### ISSUE THREAD

**Issue by grantgasser** [opencv/opencv#18745]
##### System information (version)
- OpenCV => 4.4.0
- Operating System / Platform => MAC OS Catalina 10.15.6
- Python Version => 3.8.5
- QuickTime Version => Version 10.5 (1015.2.1)

##### Detailed description

I'm a newbie to OpenCV, so I may just be making a silly mistake, but I've tried converting a set of images to video using the `VideoWriter` object with no success. The video file is written with no errors. But when I click on the file to try to open it with QuickTime, I receive a popup: 

```
The document "video.avi" could not be opened.

The file isn’t compatible with QuickTime Player.
```

 I've followed these OpenCV tutorial. The "Saving a Video" section [here](https://docs.opencv.org/master/dd/d43/tutorial_py_video_display.html), as well as this tutorial [here](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html?highlight=videowriter#saving-a-video).

I've tried several different file formats and **FourCC** codes, all resulting in the same error. I've also tried different frame rates but not sure if that makes a difference.

##### Steps to reproduce
Here's the snippet I'm using, where each element in the `images` list is a (96, 128, 3) numpy array. I've viewed the images and they look good, so not sure why they don't combine into video well.
```
fourcc = cv2.VideoWriter_fourcc(*'DIVX')
size = (96, 128)
out = cv2.VideoWriter('norm_corr.avi', fourcc, 5.0, size)

for img in images:
    assert img.shape[:2] == size
    out.write(img)
out.release()
```

**Comment by ArtistBanda** [comment]
Does it open up with another media player like VLC?

**Comment by ajithvallabai** [comment]
@grantgasser change *'DIVX' to some other parameter like MPEG, it would work .

**Comment by ajithvallabai** [comment]
@grantgasser i have tested same code in linux 18.04 it works

**Comment by hamdav** [comment]
I had the same problem, but using MJPG solved it for me

**Comment by Rainweic** [comment]
I meet this problem when I use cudacodec::createVideoWriter.
Have someone help me ? Thanks!
