### ISSUE TITLE
Failed to load image blob using setInput

### ISSUE THREAD

**Issue by himanshu56** [opencv/opencv#18757]
##### System information (version)

Hi,
I am trying to perform face detection using pre-trained dnn model. I am able to load video and display frames.
But when I try to generate image blob to feed it into Net it returns empty Net.

`Mat inputBlob;
        cv::dnn::blobFromImage(frame, inputBlob, 1.0, Size(300, 300), Scalar(123.68, 116.78, 103.94), true, false);
	
	cout << inputBlob.size() << endl; //Output is [3 x 1]
	cv::dnn::Net net;
	net.setInput(inputBlob);
	
	if (net.empty()) {
	    std::ostringstream ss;
	    ss << "Failed to load network";
	    throw std::invalid_argument(ss.str());
	}	
    `
I am getting net.empty() as true.
`[3 x 1]
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Failed to load network
Aborted
`

**Comment by dkurt** [comment]
> net.empty()

means network is not loaded correctly - please validate that paths to model files are correct.
