### ISSUE TITLE
Project for implementation of Octree structure and related algorithms in OpenCV

### ISSUE THREAD

**Issue by LIKP0** [opencv/opencv#18784]
**This is a debate issue for our project.** 
**Octree is an important structure used in 3D module. We want to implement it for 3D part of OpenCV according to the plan of [OE 33. 3D Module](https://github.com/opencv/opencv/wiki/OE-33.-3D-Module).** **To get started, you can see our [Abstract](https://github.com/LIKP0/Octree/blob/main/Abstract.md).**
We are going to update this issue continuously and link our codes below this issue.
We will upload our initial version of Octree base class in the following weeks.
Welcome to debate with us, propose your ideas and point out our mistakes!
We sincerely hope for your support. Thank you!

**Comment by alalek** [comment]
Please move your comment here #18267 to keep related discussions in a single place.

**Comment by LIKP0** [comment]
I have move my comment according to your request.
