### ISSUE TITLE
LAPACK build failed CentOS 8

### ISSUE THREAD

**Issue by lemoun** [opencv/opencv#18781]
##### System information (version)

- OpenCV => 4.5.0
- Operating System / Platform => CentOS Linux release 8.2.2004 (Core)
- Compiler => gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)

##### Detailed description

Build fail when compiling LAPACK dependency, producing following error message:

[ 72%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/lapack.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:480: modules/core/CMakeFiles/opencv_core.dir/src/lapack.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1160: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

##### Steps to reproduce

cmake \\
-DBUILD_LIST=core \\
-DCMAKE_INSTALL_PREFIX=/usr/local \\
-DENABLE_CXX11=ON ..

I have also tried with -DWITH_LAPACK=OFF  and -DENABLE_PRECOMPILED_HEADERS=OFF, producing the same error message.

[output.txt](https://github.com/opencv/opencv/files/5524167/output.txt)

**Comment by alalek** [comment]
> c++: fatal error: Killed signal terminated program cc1plus

Please check amount of available memory and that OOM killer is not triggered.

Try to capture compiler command line (`make VERBOSE=1` should help) and try to run it standalone and under debugger to capture stacktrace of the crash.

**Comment by lemoun** [comment]
> Please check amount of available memory and that OOM killer is not triggered.

You are right, the process gets killed because of OOM. I was convinced it was a compiler error, and kept looking in the wrong place.
Thanks for your advices.

**Comment by bigbearishappy** [comment]
I encounted with this problem too.
I try to compile the opencv on my raspberry pi 4b(with 2GB ram). Then I try another raspberry pi 4b with 8GB ram.
I find that when it's compiling. It can use up to 4GB ram.So that the reason why my fisrt 4B can't finish the compilation.
