### ISSUE TITLE
NO module libraries have been built, except `opencv_img_hash, opencv_sfm, opencv_world`

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#18794]
##### System information (version)

- OpenCV => :NO module libraries have been built, except `opencv_img_hash, opencv_sfm, opencv_world`:

##### Issue submission checklist

 - [x] So far, I've got **NO** idea why **NOT ALL** OpenCV libraries can be generated ???

**Comment by alalek** [comment]
- `opencv_img_hash` should be enabled, clear CMake cache and check your CMake output for details
- `opencv_sfm` requires properly installed 3rdparty dependencies
- `opencv_world` is special handling of OpenCV modules (all-in-one module except some exceptions), enabled explicitly through `cmake -DBUILD_opencv_world=ON ...` (some configurations may not be supported properly).

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
