### ISSUE TITLE
Non Max Suppress boxes with different labels

### ISSUE THREAD

**Issue by CowKeyMan** [opencv/opencv#18832]
Currently, when you use cv::dnn::DetectionModel::detect, the non-max suppression does not suppress boxes if they are of different labels.

This can be bypassed by doing NMS manually, but I think it would be nice if there was some additional boolean to the function which would allow you to suppress boxes of different labels too

Reason: Sometimes, YoloV4 detects an object from 2 different points, and on one point it detects it as label X while on the other it detects it as label Y, resulting in 2 very similar boxes (ie a big overlap) for the same object.

As for which label and box should be chosen, I think the confidence value could be used to 'rank' the boxes, and the highest ranking one would remain.

**Comment by dkurt** [comment]
Hi!

Please take a look at the discussion from https://github.com/opencv/opencv/issues/17111

Object detection models must produce boxes with NMS applied only among the same class.

However it depends on your algorithm, yes, and I think that adding a boolean flag is a good idea. But again, by default we decided perform NMS for every class independently to match origin frameworks behavior.

**Comment by CowKeyMan** [comment]
@dkurt Thank you so much for your answer! I just spent some time digging into the source code and found the function that may need changing right here: https://github.com/opencv/opencv/blob/master/modules/dnn/src/model.cpp

I will try tackling the addition of a boolean flag this weekend. If I manage, I will open a pull request. If not, I will try at a later date when I familiarize myself more with the C++ side of OpenCV
