### ISSUE TITLE
Incorrect parameter options for findFundamentalMat(...) in OpenCV Docs

### ISSUE THREAD

**Issue by IanMaquignaz** [opencv/opencv#18837]
Listed parameters for method are: 
CV_FM_7POINT for a 7-point algorithm. N=7
CV_FM_8POINT for an 8-point algorithm. N≥8
CV_FM_RANSAC for the RANSAC algorithm. N≥8
CV_FM_LMEDS for the LMedS algorithm. N≥8

but parameters should be: 
FM_7POINT for a 7-point algorithm. N=7
FM_8POINT for an 8-point algorithm. N≥8
FM_RANSAC for the RANSAC algorithm. N≥8
FM_LMEDS for the LMedS algorithm. N≥8

##### System information (version)
- OpenCV => 4.5.0-dev

##### Detailed description

Docs could be further described as un-descriptive. If anyone has links or description for the different methods I could include them in the fix.

##### Steps to reproduce
See [OpenCV Docs](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga59b0d57f46f8677fb5904294a23d404a)

**Comment by IanMaquignaz** [comment]
Assuming the docs are in a git repo, if anyone knows where/how I can edit the docs, I can be assigned this issue

**Comment by catree** [comment]
See here for `3.4`:

https://github.com/opencv/opencv/blob/a783bf4a9315338754f5a669c4c450532d5e8c3d/modules/calib3d/include/opencv2/calib3d.hpp#L2156-L2159

You can use `@ref` to add automatic references to the enum values in the generated doc. See for instance:

https://github.com/opencv/opencv/blob/a783bf4a9315338754f5a669c4c450532d5e8c3d/modules/calib3d/include/opencv2/calib3d.hpp#L784-L785
