### ISSUE TITLE
VideoCapture frame is different when INSIDE and OUTSIDE a Multiprocessing Job

### ISSUE THREAD

**Issue by roninpawn** [opencv/opencv#18844]
- OpenCV => 4.4.046
- Operating System / Platform => Windows 10, 64 Bit
- Compiler => Python 3.7.2

---

Using VideoCapture's set() method for moving the read-head in a video file, returns different locations/images for the same frame-number when called inside/outside a multiprocessing job.

Okay, so... This only happens using Variable Frame Rate (VFR) video. And VFR is the bane of all video processing, so maybe there isn't anything to be done except feed OpenCV Constant Frame Rate (CFR) video. Meaning, run your VFR through ffmpeg or Handbrake or something before you give it to OpenCV. But I ran in circles for hours trying to find the flaw in my code that was making this happen - to ultimately discover there was no flaw beyond someone having invented VFR video - so I'm submitting it.

Maybe contributors can do something to make sure that frame number 2543 is ALWAYS frame number 2543 in a video file, no matter how its accessed... and maybe not. Either way, here's the script I wrote to confirm the behavior outside of my actual project:

```import cv2
from math import floor
import multiprocessing

# This test shows how frame numbers change inside and outside of multiprocessed
# threads, by saving the frames to disk while inside the thread, and then again
# in a single, linearly accessed i/o stream. Check the paired images, and you
# will see the multi-processing thread nearest the middle identifies the frame
# number differently than the linear thread. Feel free to change total_workers
# to see the issue consistently across various threading configurations.

# This issue is due to Variable Frame Rate video. CFR does not have this issue.

vid_path = '720_test.mp4'
total_workers = 6   # Set number of logical cpu_cores to use. (3 or more)


def mp_test(worker_num):
    video = cv2.VideoCapture(vid_path)      # Open video file.
    total_frames = video.get(cv2.CAP_PROP_FRAME_COUNT)      # Get total # of frames.

    # Each worker calculates it's own job-scope based on it's worker-number.
    frames_per_worker = floor(total_frames / total_workers)
    start = worker_num * frames_per_worker
    end = start + frames_per_worker

    if worker_num == total_workers - 1:  # Last worker absorbs remainder of frames.
        end += total_frames - (frames_per_worker * total_workers)

    test_frame = end - 1    # The frame we'll save to disk.

    video.set(cv2.CAP_PROP_POS_FRAMES, start)   # Move read-head to start frame.
    cur_frame = video.get(cv2.CAP_PROP_POS_FRAMES)  # Confirms read-head at start.
    print(f"{worker_num}: {start}-{end}, Current frame: {cur_frame}")

    while cur_frame < end:
        has_frames, image = video.read()
        if cur_frame == test_frame:
            cv2.imwrite(f'runlog/{test_frame}-{worker_num}.png', image)
            print("HERE: ", worker_num, start, end, cur_frame)
        cur_frame = video.get(cv2.CAP_PROP_POS_FRAMES)

    return test_frame


if __name__ == "__main__":
    mp_pool = multiprocessing.Pool(total_workers)
    test_frames = mp_pool.map(mp_test, range(total_workers))
    mp_pool.close()
    mp_pool.join()

    # Access and write images from single, linear io stream.
    video = cv2.VideoCapture(vid_path)
    for frame in test_frames:
        video.set(cv2.CAP_PROP_POS_FRAMES, frame)
        has_frames, image = video.read()
        cv2.imwrite(f'runlog/{frame}-master.png', image)
    video.release()
```

When run, it'll dump image-pairs into the /runlog directory, named by their frame-number and the multiprocessing worker who spawned it. Comparing them to the '-master.png' version will show that the worker thread to the right of the middle in a multiprocessing job (worker 3 of 0-6 for instance) identifies a different image at the frame number specified, than when called from a single, linearly accessed VideoCapture object.

The file used for testing is a VFR video that averages to 30.007[...] frames per second. It exceeds the 30Mb uploadable file size on github by all of 3Mbs, so the whole test-zip is here... https://drive.google.com/file/d/1SOB1vLfH7X_aSL0Q7jfl4ijbnAqyo8V7/view?usp=sharing

Let me know if there's a way to make sure the frame asked for is the frame retrieved with VFR!
Otherwise, maybe this saves someone else running in circles trying to figure it out.

**Comment by alalek** [comment]
> video.set(cv2.CAP_PROP_POS_FRAMES, start) 

This may work properly with very limited set of videos and backends only (and usually requested frames must be "key" frames).
VFR videos are not in this set.

See also #9053

**Comment by roninpawn** [comment]
So, having read that thread, and to be clear... Even using CAP_PROP_POS_MSEC would also have a chance of failing?

Because I hacked my little test script there with an MSEC version and the multiprocessing workers agreed - at least - with the solo worker, which frame was which.

```
import cv2
from math import floor
import multiprocessing

vid_path = '720_test.mp4'
total_workers = 6   # Set number of logical cpu_cores to use. (3 or more)


def mp_test(worker_num):
    video = cv2.VideoCapture(vid_path)      # Open video file.

    video.set(cv2.CAP_PROP_POS_AVI_RATIO, 1)
    has_frames, image = video.read()
    total_msecs = video.get(cv2.CAP_PROP_POS_MSEC)

    # Each worker calculates it's own job-scope based on it's worker-number.
    msec_per_worker = floor(total_msecs / total_workers)
    start = worker_num * msec_per_worker
    end = start + msec_per_worker

    if worker_num == total_workers - 1:  # Last worker absorbs remainder of frames.
        end += total_msecs - (msec_per_worker * total_workers)

    video.set(cv2.CAP_PROP_POS_MSEC, start)   # Move read-head to start frame.
    cur_msec = video.get(cv2.CAP_PROP_POS_MSEC)
    cur_frame = video.get(cv2.CAP_PROP_POS_FRAMES)  # Confirms read-head at start.
    print(f"{worker_num}: {start}-{end}, Current frame: {cur_frame} | Current msec: {cur_msec}")

    while cur_msec < end:
        cur_frame = video.get(cv2.CAP_PROP_POS_FRAMES)
        has_frames, image = video.read()
        cur_msec = video.get(cv2.CAP_PROP_POS_MSEC)
    cv2.imwrite(f'runlog/{cur_frame}-{worker_num}.png', image)
    print("HERE: ", worker_num, start, end, cur_frame, cur_msec)

    return cur_msec


if __name__ == "__main__":
    mp_pool = multiprocessing.Pool(total_workers)
    test_msecs = mp_pool.map(mp_test, range(total_workers))
    mp_pool.close()
    mp_pool.join()

    # Access and write images from single, linear io stream.
    video = cv2.VideoCapture(vid_path)
    for msec in test_msecs:
        video.set(cv2.CAP_PROP_POS_MSEC, msec)
        cur_frame = video.get(cv2.CAP_PROP_POS_FRAMES)
        has_frames, image = video.read()
        cv2.imwrite(f'runlog/{cur_frame}-master.png', image)
    video.release()

```

The code above is a bit messier because I just hacked it in and didn't focus on clarity.

But, short answer, is OpenCV capable of consistently and ACCURATELY seeking to a frame or time in ANY implementation of it's methods? Can I continue on my project using milliseconds or should I deprecate OpenCV and seek some sort of FFmpeg wrapper?

**Comment by alalek** [comment]
Both CAP_PROP_FRAME_COUNT/CAP_PROP_POS_MSEC  frame seeking may be inaccurate.

> ANY implementation

Sequence of images should work (`frame_%05d.png`) through `CAP_IMAGES`.
