### ISSUE TITLE
If opencv dnn supports int8 model?

### ISSUE THREAD

**Issue by tracy56** [opencv/opencv#18864]
##### System information (version)
Now， models quantized by int8 run faster on AI chips. 
So, I want to know if opencv dnn also supports int8 models?
If support, how to quantize?

**Comment by alalek** [comment]
There is no wide support for int8 in OpenCV DNN.

> on AI chips

Which chips do you mean?
If OpenCV DNN doesn't know about these chips then it can't run inference on them.

---

Consider using OpenVINO to run INT8 or quantized networks in general on Intel hardware.

**Comment by tracy56** [comment]
I want to run on nvidia hardware, such as Jetson Xavier NX  with 21 TOPS (INT8).

**Comment by YashasSamaga** [comment]
Related (if not duplicate): https://github.com/opencv/opencv/issues/16633

**Comment by tracy56** [comment]
> Related (if not duplicate): #16633

Thanks.

**Comment by tracy56** [comment]
> There is no wide support for int8 in OpenCV DNN.
> 
> > on AI chips
> 
> Which chips do you mean?
> If OpenCV DNN doesn't know about these chips then it can't run inference on them.
> 
> Consider using OpenVINO to run INT8 or quantized networks in general on Intel hardware.

I want to run on nvidia hardware, such as Jetson Xavier NX with 21 TOPS (INT8).
