### ISSUE TITLE
Build Opencv4.4 for Android with Java Wrapper

### ISSUE THREAD

**Issue by yixun** [opencv/opencv#18875]
Hi,
I encounter trouble as building OpenCV for Android. It took me two days and still cannot figure it out.
Any help are really appreciated!

CMake Configuration is successful. I got the following:

General configuration for OpenCV 4.4.0-dev =====================================
  Version control:               unknown

  Platform:
    Timestamp:                   2020-11-20T10:04:09Z
    Host:                        Windows 10.0.18363 AMD64
    Target:                      Android 1 armv7-a
    CMake:                       3.18.1
    CMake generator:             MinGW Makefiles
    CMake build tool:            C:/MinGW/bin/mingw32-make.exe
    Configuration:               Release

  CPU/HW features:
    Baseline:
      requested:                 DETECT

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Users/yl/AppData/Local/Android/Sdk/ndk/18.1.5063045/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe  (ver 7.0)
    C++ flags (Release):     
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          ade z dl m log
    3rdparty dependencies:       libcpufeatures ittnotify libprotobuf libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc java ml objdetect photo stitching ts video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 js python2 python3
    Applications:                perf_tests
    Documentation:               NO
    Non-free algorithms:         NO

  Android NDK:                   C:/Users/yl/AppData/Local/Android/Sdk/ndk/18.1.5063045 (ver 18.1.5063045)
    Android ABI:                 armeabi-v7a
    NDK toolchain:               arm-linux-androideabi-clang
    STL type:                    c++_shared
    Native API level:            21
  Android SDK:                   not used, projects are not built

  GUI: 

  Media I/O: 
    ZLib:                        z (ver 1.2.7)
    JPEG:                        build-libjpeg-turbo (ver 2.0.5-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build Jasper (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (SVM)
    Include path:                D:/yl/OpenCV4/opencv-master/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            C:/Users/yl/AppData/Local/Programs/Python/Python36/python.exe

  Java:                          export all functions
    ant:                         C:/apache-ant-1.10.9/bin (ver )
    Java wrappers:               YES
    Java tests:                  NO

  Install to:                    D:/yl/OpenCV4/build-android/install
-----------------------------------------------------------------

Configuring done
Generating done

However, as I build it using command: mingw32-make.exe, I got following error:

[100%] Building OpenCV Android library project
Initialized native services in: C:\Users\yixunliu\.gradle\native
The client will now receive all logging from the daemon (pid: 16792). The daemon log file: C:\Users\yixunliu\.gradle\daemon\4.6\daemon-16792.out.log
Starting 3rd build in daemon [uptime: 26 mins 18.447 secs, performance: 100%, no major garbage collections]
Using 8 worker leases.
Starting Build
Settings evaluated using settings file 'D:\YixunLiu\OpenCV4\build-android\opencv_android\settings.gradle'.
Projects loaded. Root project using build file 'D:\YixunLiu\OpenCV4\build-android\opencv_android\build.gradle'.
Included projects: [root project 'opencv_android', project ':15-puzzle', project ':camera-calibration', project ':color-blob-detection', project ':face-detection', project ':image-manipulations', project ':opencv', project ':tutorial-1-camerapreview', project ':tutorial-2-mixedprocessing', project ':tutorial-3-cameracontrol']

> Configure project :
Evaluating root project 'opencv_android' using build file 'D:\YixunLiu\OpenCV4\build-android\opencv_android\build.gradle'.

> Configure project :15-puzzle
...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':15-puzzle'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
VCS Checkout Cache (D:\YixunLiu\OpenCV4\build-android\opencv_android\.gradle\vcsWorkingDirs) has not been cleaned up in 0 days
modules\java\android_sdk\CMakeFiles\opencv_java_android.dir\build.make:79: recipe for target 'opencv_android/opencv/build/outputs/aar/opencv-release.aar' failed
mingw32-make.exe[2]: *** [opencv_android/opencv/build/outputs/aar/opencv-release.aar] Error 1
CMakeFiles\Makefile2:2887: recipe for target 'modules/java/android_sdk/CMakeFiles/opencv_java_android.dir/all' failed
mingw32-make.exe[1]: *** [modules/java/android_sdk/CMakeFiles/opencv_java_android.dir/all] Error 2
Makefile:180: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by yixun** [comment]
I set ANDROID_HOME and it is resolved.

**Comment by jumpy88** [comment]
Hello @yixun, I'm trying to build [this OpenCV branch](https://github.com/komakai/opencv/tree/android-ndk-camera) but I can't figure out how to configure cmake for it. Did you follow any guide?

**Comment by jumpy88** [comment]
Installing Android Studio and inside it installing SDK (through SDK Manager), cmake and NDK (as described [here](https://developer.android.com/studio/projects/install-ndk)) and then setting Java8 (by setting `JAVA_HOME`) as default, `--sdk_path` pointing to the directory created by SDK Manager and `--ndk_path` to a specific NDK in ndk folder inside SDK I could build OpenCV and samples.

**Comment by yixun** [comment]
Thanks for your help.
It works now. It only works for a specific NDK version.
