### ISSUE TITLE
Test_TensorFlow.read_inception test failed on Macos

### ISSUE THREAD

**Issue by leochan2009** [opencv/opencv#18885]
./opencv_test_dnn --gtest_filter=Test_TensorFlow.read_inception

CTEST_FULL_OUTPUT
OpenCV version: 4.5.0
OpenCV VCS version: 4.5.0
Build type: Release
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 11.0.0.11000033)
Parallel framework: gcd (nthreads=12)
CPU features: SSE SSE2 SSE3 SSSE3 SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP SSE4.2 (y8) 2020.0.0 Gold (-) Feb 20 2020
OpenCL Platforms:
    Apple
        CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (OpenCL 1.2 )
        iGPU: Intel(R) UHD Graphics 630 (OpenCL 1.2 )
        dGPU: AMD Radeon Pro 560X Compute Engine (OpenCL 1.2 )
Current OpenCL device:
    Type = iGPU
    Name = Intel(R) UHD Graphics 630
    Version = OpenCL 1.2
    Driver version = 1.2(Mar 15 2020 21:29:48)
    Address bits = 64
    Compute units = 24
    Max work group size = 256
    Local memory size = 64 KB
    Max memory allocation size = 384 MB
    Double support = No
    Host unified memory = Yes
    Device extensions:
        cl_APPLE_SetMemObjectDestructor
        cl_APPLE_ContextLoggingFunctions
        cl_APPLE_clut
        cl_APPLE_query_kernel_names
        cl_APPLE_gl_sharing
        cl_khr_gl_event
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_byte_addressable_store
        cl_khr_image2d_from_buffer
        cl_khr_gl_depth_images
        cl_khr_depth_images
        cl_khr_3d_image_writes
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 0
TEST: Skip tests with tags: 'mem_6gb', 'verylong', 'dnn_skip_halide', 'dnn_skip_ocl', 'dnn_skip_ocl_fp16', 'dnn_skip_ie_ocl', 'dnn_skip_ie_ocl_fp16'
Note: Google Test filter = Test_TensorFlow.read_inception
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Test_TensorFlow
[ RUN      ] Test_TensorFlow.read_inception
/Users/xxxxxxx/Desktop/Work/opencv/modules/dnn/test/test_tf_importer.cpp:40: Failure
Value of: !sample.empty()
  Actual: false
Expected: true

**Comment by alalek** [comment]
[Can't reproduce on CI](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-4.x&width=7).
Check for missing test data or disabled/missing PNG decoder.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
