### ISSUE TITLE
core: drop `_InputArray::STD_ARRAY` type (use `MATX` instead)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#18897]
Reason:
- duplicates behavior and implementation (fixed type, fixed size)

[relates](https://github.com/opencv/opencv/blame/0105f8fa38ec867a8e4bbc74c402afcd0e296194/modules/core/include/opencv2/core/mat.hpp#L181) #8535

**Comment by theoniko** [comment]
As far as i understood the purpose of this issue is to remove STD_ARRAY from enum KindFlag in class _InputArray (file mat.hpp) and replaced in all other places by enumarator MATX. Am i right? Could you please give more details why this change is needed?
