### ISSUE TITLE
On Ubuntu Linux version 18.04 failed to build

### ISSUE THREAD

**Issue by vmahadev** [opencv/opencv#18890]
OS Ubuntu 18.04

# Install minimal prerequisites (Ubuntu 18.04 as reference)
sudo apt update && sudo apt install -y cmake g++ wget unzip
# Download and unpack sources
git clone https://github.com/opencv/opencv.git
git -C opencv checkout master
# Create build directory
mkdir -p build && cd build
# Configure
cmake  ../opencv-master
# Build
cmake --build .

The above command executed resulted in the following errors

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/imgproc/CMakeFiles/opencv_imgproc.dir/build.make:712: recipe for target 'modules/i
mgproc/CMakeFiles/opencv_imgproc.dir/src/filter.dispatch.cpp.o' failed
make[2]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/filter.dispatch.cpp.o] Err
or 4
CMakeFiles/Makefile2:1948: recipe for target 'modules/imgproc/CMakeFiles/opencv_imgproc.di
r/all' failed
make[1]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sunglyoungKim** [comment]
I have the same error while I tried to build OpenCV 4.5.0 on ubuntu 18.04
