### ISSUE TITLE
Transformation from Euler angle to quaternion.

### ISSUE THREAD

**Issue by chargerKong** [opencv/opencv#18908]
##### Detailed description

We want to add the transformation between quaternion and Euler angle.

But we know there exists twelve possible sequences of rotation axes, divided into two groups:
Proper Euler angles (z−x−z, x−y−x, y−z−y, z−y−z, x−z−x, y−x−y）
Tait-Bryan angles (x−y−z, y−z−x, z−x−y, x−z−y, z−y−x, y−x−z)

Do we need to implement all types of Euler angles or just some main types, maybe x-y-z ?
@savuor @alalek @vpisarev

**Comment by catree** [comment]
Just some references, for the Eigen library:
- [Eigen `eulerAngles()`](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#title20)
- [Eigen EulerAngles module](https://eigen.tuxfamily.org/dox/unsupported/classEigen_1_1EulerAngles.html) (from the unsupported module)

Rotation in ROS, for common support of Euler representations:
- [geometry2/RotationMethods](http://wiki.ros.org/geometry2/RotationMethods#Fixed_Axis_vs_Euler_Angles)
- [REP 103](https://www.ros.org/reps/rep-0103.html#rotation-representation)

**Comment by savuor** [comment]
Not sure if we need to implement all possible Euler angle conventions. The only one used in OpenCV is in [RQDecomp function](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga1aaacb6224ec7b99d34866f8f9baac83). I think, if the same one is implemented, that'd be enough.

**Comment by catree** [comment]
Euler angles are always tricky for me. For instance, I have no idea which Euler convention is used for `RQDecomp3x3()`. See also [this related issue](https://github.com/opencv/opencv/issues/18189#issuecomment-680176040).

In my opinion, if Euler angles conversion is to be supported, the most common conventions should be implemented.
With ROS it should be:
- "fixed axis roll, pitch, yaw about X, Y, Z" (equivalent to Euler RPY?)
- "euler angles yaw, pitch, and roll about Z, Y, X axes respectively"

**Comment by chargerKong** [comment]
Thanks for your suggestion. @catree @savuor 
We will take the order of RQDecomp function's as the default order and implement some the most common conventions.

**Comment by alalek** [comment]
Resolved here: #19098
