### ISSUE TITLE
Reproducible gcc crash on Ubuntu 16.04 in /libwebp/src/enc/picture_csp_enc.c

### ISSUE THREAD

**Issue by tmanthey** [opencv/opencv#18901]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

##### Detailed description
[  7%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/near_lossless_enc.c.o
[  7%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/picture_csp_enc.c.o
[  7%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/picture_enc.c.o
[  8%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/picture_psnr_enc.c.o
**/tmp/opencv/3rdparty/libwebp/src/enc/picture_csp_enc.c: In function ‘ImportYUVAFromRGBA’:
/tmp/opencv/3rdparty/libwebp/src/enc/picture_csp_enc.c:214:29: internal compiler error: Segmentation fault
       kLinearToGammaTabS[v] =**
                             ^
##### Steps to reproduce
git clone --branch 4.5.0  https://github.com/opencv/opencv
git clone --branch 4.5.0  https://github.com/opencv/opencv_contrib
mkdir opencv/build;cd opencv/build;
cmake .. -DBUILD_DOCS=OFF -DWITH_PNG=ON -DWITH_JPEG=ON -DWITH_QT=ON -DWITH_GTK_2_X=ON -DWITH_OPENGLOPENCL=ON -DWITH_CUDA=ON -DWITH_OPENMP=ON -DWITH_IPP=ON -DWITH_TBB=ON -DENABLE_FAST_MATH=ON -DWITH_CUBLAS=ON -DWITH_LIBV4L=ON -DWITH_GSTREAMER=ON -DWITH_GSTREAMER_0_10=OFF -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules
make -j8

**Comment by asmorkalov** [comment]
Please pay attention on https://github.com/opencv/opencv/wiki/FAQ#build--install. Please try to build the library in single thread (make without options) and ensure that you have enough RAM.

**Comment by tmanthey** [comment]
You can reproduce the issue with 
`make -j1 libwebp`
I checked the memory during compilation and there does not seem to be a memory issue. Memory is the red line in the middle chart.
![Screenshot from 2020-11-23 17-12-23](https://user-images.githubusercontent.com/9221853/99986428-74616a00-2daf-11eb-91d5-523fd03b4fee.png)

**Comment by alalek** [comment]
Check `dmesg` for OOM killer messages. Check disk space / `/tmp` space.
Please retry from clean build directory (cleanup left artifacts from the first ICE crash).

You may want to check GCC documents how to investigate ICE crashes.
Full compiler command line can be grabbed through `make VERBOSE=1`.

**Comment by tmanthey** [comment]
There are no message on dmesg during the compile.
I cleaned the build dir
On root filesystem that includes /tmp I have 50GB free space

Output is:
```
make VERBOSE=1 -j1 libwebp
...
[ 60%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/enc/picture_csp_enc.c.o
cd /tmp/opencv/build/3rdparty/libwebp && /usr/bin/cc -DWEBP_USE_THREAD -I/tmp/opencv/3rdparty/libwebp -I/tmp/opencv/build  -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wuninitialized -Winit-self -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fopenmp -std=c99 -Wno-unused-variable -Wno-unused-function -Wno-shadow -Wno-maybe-uninitialized -Wno-missing-prototypes -Wno-missing-declarations -O3 -DNDEBUG  -DNDEBUG -fPIC   -o CMakeFiles/libwebp.dir/src/enc/picture_csp_enc.c.o   -c /tmp/opencv/3rdparty/libwebp/src/enc/picture_csp_enc.c
/tmp/opencv/3rdparty/libwebp/src/enc/picture_csp_enc.c: In function ‘ImportYUVAFromRGBA’:
/tmp/opencv/3rdparty/libwebp/src/enc/picture_csp_enc.c:214:29: internal compiler error: Segmentation fault
       kLinearToGammaTabS[v] =
                             ^
```

**Comment by mshabunin** [comment]
Can not reproduce in empty Ubuntu 16.04 container (_master_ branch):
```.sh
apt update && apt install -y git cmake make g++
git clone --branch 4.5.0 --depth=1 https://github.com/opencv/opencv
git clone --branch 4.5.0 --depth=1 https://github.com/opencv/opencv_contrib
mkdir opencv/build
cd opencv/build
cmake .. -DENABLE_FAST_MATH=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules
make -j1 libwebp
```
```
...
[100%] Built target libwebp
```

**Comment by alalek** [comment]
> root filesystem that includes /tmp

BTW, usually `/tmp` is dedicated `tmpfs` mount on Linux. Fedora example:
```
$ df -hT /
Filesystem              Type  Size  Used Avail Use% Mounted on
/dev/mapper/vg-dev_root ext4   24G   16G  7.1G  69% /
$ df -hT /tmp
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs   16G   22M   16G   1% /tmp
```

**Comment by tmanthey** [comment]
The problem is one of the cmake options. To reproduce run
 the attached dockerfile with 

`docker build -f Dockerfile.opencvtest  .`
[Dockerfile.opencvtest.zip](https://github.com/opencv/opencv/files/5588693/Dockerfile.opencvtest.zip)

**Comment by alalek** [comment]
@tmanthey Thank you for reproducer!
I can confirm the problem.

Also you can drop `-DENABLE_FAST_MATH=ON` CMake option (enables `-ffast-math` GCC option).
Not sure if we can fix that from OpenCV side.
Consider reporting internal compiler errors to compiler team.

---

Compilation of this file can be avoided (it is optional):
- `apt update && apt install -y libwebp-dev` - use system library instead
- or `-DWITH_WEBP=OFF`

---

Build image based on Ubuntu 18.04 (with GCC 7.x) works fine.
Ubuntu 16.04 is EOL in 2021.

**Comment by sl-sergei** [comment]
@alalek I had another problem with libwebp, somehow linker didn't work correctly:
```/usr/bin/ld: cannot find -llibwebp```

CMake option ```-DWITH_WEBP=OFF``` fixed the problem for me, so thank you!

**Comment by alalek** [comment]
@sl-sergei Lets track this problem here: #18984 (it would be nice to collect information about the problem)
