### ISSUE TITLE
Compilation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by ibrahimqazi** [opencv/opencv#18910]
I want to install OpenCV 3.4.1 on my Ubuntu 18.04. I have already installed OpenCV 4.0 on my system. But due to another package which depends on OpenCV3, I need to install previous of OpenCV. The first step CMAKE goes well.
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local/opencv3 \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv3/opencv_contrib/modules \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/py3cv3/bin/python \
    -D BUILD_EXAMPLES=ON ..
```
When I run `make -j4` I get the following error, can anyone help me please.
```
Error at 159: there are non-valid entries in the current block stack [['file', '/home/ibrrahim/opencv3/opencv_contrib/modules/aruco/include/opencv2/aruco/dictionary.hpp', True, True, None], ['namespace', 'cv', True, True, None], ['namespace', 'aruco', True, True, None], ['enum CV_EXPORTS_W_SIMPLE', 'PREDEFINED_DICTIONARY_NAME', True, True, None]]
modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make:339: recipe for target 'modules/python_bindings_generator/pyopencv_generated_enums.h' failed
make[2]: *** [modules/python_bindings_generator/pyopencv_generated_enums.h] Error 255
CMakeFiles/Makefile2:16952: recipe for target 'modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all' failed
make[1]: *** [modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...
```

**Comment by alalek** [comment]
> OpenCV 3.4.1

We don't maintain outdated releases. Try latest versions first.

> gen_opencv_python_source

You may want to disable building of unnecessary components, see below.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by ajithvallabai** [comment]
@ibrahimqazi  uninstall opencv4.0 first with this https://answers.opencv.org/question/194106/uninstalling-opencv-400-to-34/ . check whether its uninstalled completely 

then install opencv c++ with this https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/

**Comment by ibrahimqazi** [comment]
> 
> 
> @ibrahimqazi uninstall opencv4.0 first with this https://answers.opencv.org/question/194106/uninstalling-opencv-400-to-34/ . check whether its uninstalled completely
> 
> then install opencv c++ with this https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/

Thank you that is not the solution because I dont want to remove it. I need opencv3 only for single project.

**Comment by ajithvallabai** [comment]
@ibrahimqazi did u try creating conda environement ? it will give you that freedom
