### ISSUE TITLE
ONNX implementation does not support slice layer with steps != 1

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#18920]
##### Detailed description
The onnx from [yolov5](https://github.com/ultralytics/yolov5)

if **Net net = readNetFromONNX()** by opencv4.5

 OpenCV(4.5.0) Error: Unspecified error (> Node [Slice]:(519) parse error: OpenCV(4.5.0) D:\opencv450\opencv-4.5.0\modules\dnn\src\onnx\onnx_importer.cpp:697: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20200908::ONNXImporter::handleNode(const class opencv_onnx::NodeProto &)'
> > Slice layer only supports steps = 1 (expected: 'countNonZero(step_blob != 1) == 0'), where
> >     'countNonZero(step_blob != 1)' is 1
> > must be equal to
> >     '0' is 0
> ) in cv::dnn::dnn4_v20200908::ONNXImporter::handleNode, file D:\opencv450\opencv-4.5.0\modules\dnn\src\onnx\onnx_importer.cpp, line 1797

the onnx model:
link：https://pan.baidu.com/s/1HhTtIJKaOHcbmgK_lKKeAg 
code：jti9

**Comment by ihmc3jn09hk** [comment]
Encountering the same issue. Any solution to that?

**Comment by mkep-dev** [comment]
I'm encountering the same issue

**Comment by sl-sergei** [comment]
@wwzh2015 Can you please upload your ONNX network to some other hosting, accessible outside of China? I want to investigate your problem and fix it, but I stuck with Baidu...

**Comment by asmorkalov** [comment]
@wwzh2015 Friendly reminder.

**Comment by asmorkalov** [comment]
@wwzh2015 Friendly reminder.

**Comment by wwzh2015** [comment]
> I'm encountering the same issue



> I'm encountering the same issue

That is wrong, but I have a solution. thanks!

**Comment by wwzh2015** [comment]
> I'm encountering the same issue

https://github.com/opencv/opencv/issues/18920#issuecomment-740062005

> I'm encountering the same issue

That is wrong, but I have a soultion.

**Comment by gurki** [comment]
I'm having the same issue. Looking through the tracker, there's multiple references to this, however no resolution. The debate about YOLOv5 aside, it's a popular model nonetheless used by a significant chunk of people. OpenCV currently doesn't support `Slice Layers` with a step size other than 1. And from what I understood there's a resentment in adding it. Any updates here?

@sl-sergei I uploaded an [example](https://drive.google.com/file/d/1ADjJDTZC5FEcPJWA2P2SZW1sKcjREtkG/view?usp=sharing) that has slice layer step 2. Happy for any input you might have towards a solution.

**Comment by alalek** [comment]
> YOLOv5

Be careful with that!

---

> YOLOv5-Ultralytics - is just a name, model is worse than YOLOv4, without improvements, without a scientific article, and with fake comparisons in a couple of blogs.

https://github.com/pjreddie/darknet/issues/2198

**Comment by gurki** [comment]
> > YOLOv5
> 
> Be careful with that!
> 
> > YOLOv5-Ultralytics - is just a name, model is worse than YOLOv4, without improvements, without a scientific article, and with fake comparisons in a couple of blogs.
> 
> [pjreddie/darknet#2198](https://github.com/pjreddie/darknet/issues/2198)

Didn't want to start a discussion on the naming here, I already mentioned in my post above that I'm aware of the ongoing controversy, and I do agree it was a poor choice by Glenn. 
Still, over the last days I trained a custom dataset on both YOLOv4, Scaled-YOLOv4 and Glenn's "YOLOv5", and the latter tops the first two in ease of use, training time, model size and performance. This is of course a narrow comparison and subjective, the only point I want to make is that it has its place and I would be delighted if the OpenCV community would open up and support it as well :). 
And the specific architecture aside, it seems implementing various step sizes would benefit the whole ecosystem, as it would complete ONNX spec and compatibility for other models and architectures as well.

Thanks for the link to darknet discussion, good read.

At the end of the day, just looking for a solution here :).

**Comment by gurki** [comment]
@LupusSanctus Was wondering if you had any idea how to address this, could you gather any insight from the provided example?

**Comment by LupusSanctus** [comment]
@gurki, thank you for the provided model. You may find a solution for steps support in #19546.

**Comment by oblime** [comment]
Seems that the problem is in the Focus module that slicing a tensor with step=2. So I use another equivalent solution. Specifically:
change models/common.py line 171 from
`return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))`
to
`b, c, h, w = x.shape`
`return self.conv(x.reshape(1, 3, h // 2, 2, w // 2, 2).permute(0, 5, 3, 1, 2, 4).reshape(1, c * 4, h // 2, w // 2))`
then export the model again. This works for me.

**Comment by wasmith5** [comment]
@oblime , I have tried this and it gives this error when running the model in c++:

 OpenCV(4.5.0) Error: Assertion failed (0) in cv::dnn::cuda4dnn::ScaleShiftOp<float>::forward::<lambda_bda7596c55c12c365395511ceeb4dd9d>::operator (), file C:\opencv\sources\modules\dnn\src\layers\../cuda4dnn/primitives/scale_shift.hpp, line 135
