### ISSUE TITLE
Different Yolo performing time in different versions

### ISSUE THREAD

**Issue by Aslyamovt** [opencv/opencv#18921]
I have accesses to 2 servers with identical hardware:

Frist:
CPU -> AMD EPYC 7551P 32-Core
GPU -> 2 Nvidia Tesla V-100 16 GB
OS -> Windows Server 2016 Datacenter
GPU driver -> Nvidia Tesla V-100 441.22
CUDA -> 10.2.89
OpenCV -> 4.4.0
Compiler -> Visual Studio 2019 
Enviroment -> Anaconda with Python 3.7

Second:
CPU -> AMD EPYC 7551P 32-Core
GPU -> 2 Nvidia Tesla V-100 16 GB
OS -> Centos 7
GPU driver -> Nvidia Tesla V-100  VGPU driver 430.30
CUDA -> 10.0.130
OpenCV -> 4.5.0-pre.
Compiler -> gcc 4.8.5 20150623
Enviroment -> Python 3.6 (just python enviroment)

When I perform object detection with the same code for the same videos, I get different fps for these servers.
I use darknet YoloV4 object detector model from AlexeyAB https://github.com/AlexeyAB/darknet
I also have the same thing with YoloV3-spp and YoloV3 models.

On the first server with input image size 416x416 - 36-38 fps
On the first server with input image size 608x608 - 16-17 fps

On the second server with input image size 416x416 - 62-63 fps
On the second server with input image size 608x608 - 37-38 fps

I don't understand if it is because of some performance improvement in new OpenCV version or it is because of some problems with version OpenCV for Windows.
I am attaching the code to reproduce the problem.

[OpenCVYolo.txt](https://github.com/opencv/opencv/files/5595121/OpenCVYolo.txt)

**Comment by YashasSamaga** [comment]
As far as I know, there was no change in 4.5.0 from 4.4.0 that would affect YOLO models. I don't think the difference is caused by using different OpenCV versions.

1. What version of cuDNN are you using? cuDNN 8 has performance regressions.
2. What happens when you use `DNN_TARGET_CUDA_FP16`?
3. Check if the performance/power mode is same on both setups (you can check this in `nvidia-smi`).
4. Can you try installing the other OpenCV version on one of the setups? I don't think OpenCV is causing the problem.

**Comment by Aslyamovt** [comment]
> There isn't any change in 4.5.0 w.r.t 4.4.0 that would affect YOLO models. I don't think the difference is caused by using different OpenCV versions.
> 
> 1. What version of cuDNN are you using? cuDNN 8 has performance regressions.
> 2. What happens when you use `DNN_TARGET_CUDA_FP16`?
> 3. Check if the performance/power mode is same on both setups (you can check this in `nvidia-smi`).
> 4. Can you try installing the other OpenCV version on one of the setups? I don't think OpenCV is causing the problem.

Thank you for such quick unswer.
Unfortunally I couldn'd install same OpenCV versions  to both servers.

1. I use cuDNN 7.6 on first server and cuDNN 7.5 on second.
2. If I use `DNN_TARGET_CUDA_FP16` I get 20 FPS for input size 608x608 on first server and about 43-44 FPS on second (higher performance than `DNN_TARGET_CUDA` on both)
3. Performance/power mode are same.

We noticed that the model uploads to device much longer on first server than on second (about 1-2 minute on first and 4-6 seconds on second). Therefore, the slower detection performance could be caused by longer upload of images.
We also performed some tests with Torchvision model (for example FasterRCNN) and didn't see such problem (about 140 ms on both servers). 
Again attaching the code for torchvision tests.
I did addional tests with YoloV4 and found out that all time differences are on `outs = net.forward(output_layers)` line on first frame (100-120 seconds vs 5.08) and on `blob = cv2.dnn.blobFromImage(image_np, 0.00392, (608, 608), (0, 0, 0), True, crop=False)` line on next frames (20 ms vs 4 ms).

**Comment by YashasSamaga** [comment]
> We noticed that the model uploads to device much longer on first server than on second (about 1-2 minute on first and 4-6 seconds on second). Therefore, the slower detection performance could be caused by longer upload of images.

> I did addional tests with YoloV4 and found out that all time differences are on outs = net.forward(output_layers) line on first frame (100-120 seconds vs 4-5 seconds)

OpenCV DNN does lazy initialization. The `Net` object is initialized in the first forward pass. Hence, the slowness while processing the first frame. It's normal to see large differences in initialization times on different platforms but the discrepancy in your case is unusually big. I'd suggest restricting your script to process just two or three frames and profile it using Nsight Systems. This will mostly provide more details about the cause of performance degradation.

> on blob = cv2.dnn.blobFromImage(image_np, 0.00392, (608, 608), (0, 0, 0), True, crop=False) line on next frames (20 ms vs 4 ms).

`blobFromImage` fully runs on CPU. This suggests that CPU workloads are also running slower in your Windows system. What FPS do you get with `DNN_BACKEND_OPENCV` and `DNN_TARGET_CPU`?

Can you check whether you're using a debug build of OpenCV?

```
import cv2
print(cv2.getBuildInformation())
```

---

Extra information:

I get around 120FPS on RTX 2080 Ti for YOLOv4 with 608x608 input (with `DNN_TARGET_CUDA_FP16`) when time is measured only across `net.forward` call. I presume it will be even higher on V100. Assuming that your second Linux setup is working fine, your FPS numbers suggests that a lot of time is being consumed in the postprocessing step. OpenCV DNN provides a [high-level model API](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html) that can partly mitigate the slowness of python. You can find an example [here](https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49).
