### ISSUE TITLE
G-API: "range for" result reference warning near ade::util::indexed()

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#18928]
Xcode 12.2:

```
modules/gapi/src/backends/ocl/goclbackend.cpp:234:26: warning:
loop variable 'out_it' is always a copy because the range of type 
'decltype(zip(iota<std::size_t>(), std::forward<const std::__1::vector<cv::gimpl::RcDesc, std::__1::allocator<cv::gimpl::RcDesc> > &>(conts)))' (aka 'ZipRange<ade::util::Range::IotaRange<unsigned long, 1>, const std::__1::vector<cv::gimpl::RcDesc, std::__1::allocator<cv::gimpl::RcDesc> > &>')
does not return a reference [-Wrange-loop-analysis]
        for (const auto &out_it : ade::util::indexed(op.outs))
                         ^
modules/gapi/src/backends/ocl/goclbackend.cpp:234:14: note:
use non-reference type 'std::__1::tuple<const unsigned long &, const cv::gimpl::RcDesc &>'
        for (const auto &out_it : ade::util::indexed(op.outs))
             ^~~~~~~~~~~~~~~~~~~~
```

**Comment by anton-potapov** [comment]
@alalek  could be so kind to post a link to build log ? (I suppose it is nightly builds ?)

As, using Ubuntu and latest clang 12 i'm not able to reproduce the warning.

**Comment by alalek** [comment]
Currently these warnings are suppressed [here](https://github.com/opencv/opencv/blame/b023fcd26418d4da7a73b7ca4abfb21c44be674c/modules/gapi/CMakeLists.txt#L41-L43) to keep builds green.

Clang != Apple Clang. I tried modern Clang on Linux too, but there are no such warnings.

**Comment by legercheap** [comment]
https://money.frontalreport.com/news/the-history-for-the-herve-leger/0268750
https://is.gd/UrvUh4
https://is.gd/U8RvBC
https://is.gd/yUXFvk
https://is.gd/3djIqy
https://is.gd/ofVVPH
https://lifestyle.frontalreport.com/news/the-history-for-the-herve-leger/0268750
https://bit.ly/37eFUMi
https://bit.ly/37ZHjW5
https://bit.ly/37TdeYo
https://tech.frontalreport.com/news/the-history-for-the-herve-leger/0268750
https://tinyurl.com/yxvxxyg8
https://tinyurl.com/yxly2p7w
https://tinyurl.com/yyyvsdmo
https://tinyurl.com/y44ox3qr
https://tinyurl.com/yyvuck6k
https://entertainment.aseancoverage.com/news/the-history-for-the-herve-leger/0268750
https://cutt.ly/qhPOiby
https://cutt.ly/ChPOiVy
https://cutt.ly/PhPOofy
https://cutt.ly/EhPOoZd
https://cutt.ly/UhPOpxP
https://sports.aseancoverage.com/news/the-history-for-the-herve-leger/0268750
https://rebrand.ly/f7bmi
https://rebrand.ly/vzmcg
https://rebrand.ly/dpwpv
https://rebrand.ly/7kvnu
https://rebrand.ly/qw6r3
http://b.link/z9sfe
http://b.link/nht8v
http://b.link/gfdfj
http://b.link/7wcmw
http://b.link/4t3jg
http://tiny.cc/nol6tz
