### ISSUE TITLE
Can't solve OpenCV build error due to no POPCNT support on CPU

### ISSUE THREAD

**Issue by arunj0shi** [opencv/opencv#18932]
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => Ubuntu 18.04.3 LTS
*running as a Oracle Virtual Box VM on Windows 10
- Compiler => gcc 7.5.0

##### Detailed description
Can't solve OpenCV build error when CPU do not support POPCNT

##### Steps to reproduce
1. run Ubuntu18.04 VM  using Oracle Virtual Box on Windows 10
2. build opencv from source. I followed steps from here,
https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/
3. install openvino 2020.3 for linux
4. run openvino demo /opt/intel/openvino/deployment_tools/demo/demo_security_barrier_camera.sh 
5. see openCV error. I have tried turning POPCNT off in the cmake optimization file, and building openCV again. The build succeeds but I do get the same error again.

I have tried looking for definite steps to build an openCV version on a machine that do not have CPU support for POPCNT, but failed.

please help, _/\_
 
##### cat /proc/cpuinfo | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni ssse3 pcid sse4_1 sse4_2 hypervisor lahf_lm invpcid_single ibrs_enhanced fsgsbase invpcid md_clear flush_l1d arch_capabilities

*note POPCNT is missing

##### Error (from openvino app run)
Note: same error when run the cmd: python3 -c "import cv2; print(cv2.__version__)")

Run Inference Engine classification sample

Run ./classification_sample_async -d CPU -i /opt/intel/openvino/deployment_tools/demo/car.png -m /home/osboxes/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml

```
******************************************************************
* FATAL ERROR:                                                   *
* This OpenCV build doesn't support current CPU/HW configuration *
*                                                                *
* Use OPENCV_DUMP_CONFIG=1 environment variable for details      *
******************************************************************

Required baseline features:
    ID=  2 (SSE) - OK
    ID=  3 (SSE2) - OK
    ID=  4 (SSE3) - OK
    ID=  5 (SSSE3) - OK
    ID=  6 (SSE4.1) - OK
    ID=  8 (POPCNT) - NOT AVAILABLE
    ID=  7 (SSE4.2) - OK
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0-openvino-2020.3.0) ../opencv/modules/core/src/system.cpp:620: error: (-215:Assertion failed) Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup. in function 'initialize'

/opt/intel/openvino/deployment_tools/demo/utils.sh: line 11:  4545 Aborted                 (core dumped) "$@"
Error on or near line 217; exiting with status 1
```

**Comment by alalek** [comment]
Please dump CMake output (starting from "General configuration for OpenCV", [example](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/11365/steps/cmake/logs/stdio)).

> I have tried turning POPCNT off in the cmake optimization file

Please provide details.

**Comment by alalek** [comment]
Try this: `cmake -DCPU_SSE4_2_IMPLIES=SSE4_1 ...`

---

> OpenCV(4.3.0-openvino-2020.3.0)

This usually means that you are using OpenCV from OpenVINO.

**Comment by alalek** [comment]
> sse4_2
> *note POPCNT is missing

This is really strange configuration.

Related tickets against Virtual Box:
- https://www.virtualbox.org/ticket/13442 (closed as obsolete)
- https://www.virtualbox.org/ticket/20005 (new one - 4 weeks ago)

**Comment by arunj0shi** [comment]
> Please dump CMake output (starting from "General configuration for OpenCV", [example](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/11365/steps/cmake/logs/stdio)).
>
[opencv_build_logs.txt](https://github.com/opencv/opencv/files/5603361/opencv_build_logs.txt)
 
> > I have tried turning POPCNT off in the cmake optimization file
> 
> Please provide details.
1. tried option -D OPENCV_CPU_DISABLE = POPCNT
2. seperately tried, in this file
/home/osboxes/opencv_build/opencv/cmake/OpenCVCompilerOptimizations.cmake

comment out this line
ocv_optimization_process_obsolete_option(ENABLE_POPCNT POPCNT ON)

**Comment by arunj0shi** [comment]
Really appreciate the quick reply. I will follow up on other suggestions.

**Comment by arunj0shi** [comment]
> Try this: `cmake -DCPU_SSE4_2_IMPLIES=SSE4_1 ...`
> 
> > OpenCV(4.3.0-openvino-2020.3.0)
> 
> This usually means that you are using OpenCV from OpenVINO.

I updated the setupvars.h file here /opt/intel/openvino/opencv here to point to my build
export OpenCV_DIR=/home/osboxes/opencv_build/opencv/cmake
export LD_LIBRARY_PATH=/home/osboxes/opencv_build/opencv/build/lib:$LD_LIBRARY_PATH
![screeshot](https://user-images.githubusercontent.com/10647331/100423469-0d1b1280-305a-11eb-94a2-6950de364294.png)

and it seems to solve the problem.

That means my source compile of opencv have no issues.
Thanks again!
