### ISSUE TITLE
Why yolov4 AP in darknet more than in opencv4.5?

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#18946]
##### System information (version)

- OpenCV => 4.5
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
-->
AP distance in 3-5 per;
What's the Reason? 

EX:the pic
链接：https://pan.baidu.com/s/1pcB82wCuUpXDGiNOY8rwpA 
提取码：m9uo

**Comment by YashasSamaga** [comment]
What backend and target did you use? How did you evaluate the performance?

**Comment by wwzh2015** [comment]
> What backend and target did you use? How did you evaluate the performance?
> 
> The [AP metrics for YOLOv4 with the CUDA backend](https://github.com/opencv/opencv/pull/17621#issuecomment-647691042) agreed with Darknet when evaluated using [this script](https://gist.github.com/YashasSamaga/077a1d69c48e4cdb9957d167b7000b98) in 4.4.0.

CUDA backend，yolo4.weights, 608 input, 
example: detect the person heads is 125 in darknet, but only is 95 in opencv. 
whether Conv BN be Integrationed?

**Comment by dkurt** [comment]
Please provide reproducer with image, expected results, model reference.

**Comment by wwzh2015** [comment]
> Please provide reproducer with image, expected results, model reference.

model：
链接：https://pan.baidu.com/s/1dpwn4rD7glJ74lsP_UCqfw 
提取码：mqde 

image:
链接：https://pan.baidu.com/s/1pcB82wCuUpXDGiNOY8rwpA
提取码：m9uo

**Comment by alalek** [comment]
Avoid using of external resources especially which require extra registration.
