### ISSUE TITLE
stitcher：Crash caused by premature release of images

### ISSUE THREAD

**Issue by freedomxgz** [opencv/opencv#18941]
- OpenCV 4.1

- win 10

The program crashed when I was using stitcher.While viewing the source code, it was discovered that the crash was caused by the image being released prematurely.

code:
if (std::abs(compose_scale - 1) > 1e-1)
        {
#if ENABLE_LOG
            int64 resize_t = getTickCount();
#endif
            resize(full_img, img, Size(), compose_scale, compose_scale, INTER_LINEAR_EXACT);
            LOGLN("  resize time: " << ((getTickCount() - resize_t) / getTickFrequency()) << " sec");
        }
        else
            img = full_img;
        full_img.release();

When the compose_scale is not 1, the full_img is released.But img and full_img are shallow copies.The img is also equivalent to being released, and subsequent processing causes an error.

Is this a bug?

**Comment by alalek** [comment]
> The img is also equivalent to being released

This is not true.

---

Prepare minimal complete reproducer.
In case of crashes provide stack trace dump.

**Comment by freedomxgz** [comment]
Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in cv::remap

![image](https://user-images.githubusercontent.com/41714129/100407812-6445d500-30a4-11eb-934d-d76f60a9e313.png)
![image](https://user-images.githubusercontent.com/41714129/100407905-a0793580-30a4-11eb-9e10-c9a3f52274ce.png)
src is empty;
