### ISSUE TITLE
Convert scipy coordinate system to opencv coordinate system

### ISSUE THREAD

**Issue by Zumbalamambo** [opencv/opencv#18964]
I'm using the following code to convert a quaternion to a rotation vector.

```
#convert to xyzw
rotation = R.from_quat([quaternion[1], quaternion[2], quaternion[3], quaternion[0]])
rotation_vector = np.array(rotation.as_rotvec()).reshape(3, 1)
```

Unfortunately, the axis is rotated in the wrong direction. How can I convert the Rotation vector in script format to OpenCV coordinate system?

**Comment by alalek** [comment]
BTW, related functionality is here #18335 : `toRotMat3x3()` / `toRotVec()`

It is not released yet, but you can check code snippets.

---

> in the wrong direction

AFAIK, there is no "right" direction. It depends on algorithm and its assumptions.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
