### ISSUE TITLE
error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'cv::remap'

### ISSUE THREAD

**Issue by freedomxgz** [opencv/opencv#18970]
I used Opencv 4.1 for image stitching, and an error message appeared.
error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'cv::remap'

Why did it happen and how can I fix it?I hope someone can help me solve this problem.

**Comment by fabiomanz** [comment]
Can you please post a minimal reproducible example, so we can try to find the problem?

**Comment by legercheap** [comment]
http://finance.losaltos.com/camedia.losaltos/news/read/40736255
https://is.gd/TD5hnK
https://is.gd/S6S6NS
https://is.gd/pqKhsx
https://is.gd/Wo7OPc
https://is.gd/VPTqQh
http://quotes.valueinvestingnews.com/fatpitch.valueinvestingnews/news/read/40736255
https://bit.ly/2IMdAri
https://bit.ly/345A11Y
https://bit.ly/3m9zpyt
https://bit.ly/37cRMhI
https://bit.ly/3a4vv7E
https://lifestyle.asialogue.com/news/the-history-for-the-herve-leger/0268750
https://tinyurl.com/yyylxwdk
https://tinyurl.com/yy4vm2gc
https://tinyurl.com/y4brw734
https://tech.asialogue.com/news/the-history-for-the-herve-leger/0268750
https://cutt.ly/khPIipc
https://cutt.ly/uhPOrhu
https://cutt.ly/xhPOr49
https://cutt.ly/chPOtz0
https://cutt.ly/chPOu54
https://entertainment.frontalreport.com/news/the-history-for-the-herve-leger/0268750
https://rebrand.ly/vyq66
https://rebrand.ly/jkojr
https://rebrand.ly/9s059
https://rebrand.ly/sny0q
https://rebrand.ly/a36qm
http://b.link/7xfxl
http://b.link/ktywc
http://b.link/fugkt
http://b.link/8kpzx
http://b.link/fgad5
http://tiny.cc/lol6tz

**Comment by asmorkalov** [comment]
Duplicate for https://github.com/opencv/opencv/issues/4694 and https://github.com/opencv/opencv/issues/7544

**Comment by liyaner123** [comment]
I also meet this problem,I checked the documents of opencv,it says the input images and output images should be less than 32767*32767,but my image is only 7952 * 5304,and i don't know how to solve this problem,is there someone can give me some advice.

**Comment by ApoorvaSuresh-Audi** [comment]
Hi, @liyaner123  have you been able to find a solution for this?
