### ISSUE TITLE
opencv dnn module suport  Scaled yolov4 model?

### ISSUE THREAD

**Issue by toplinuxsir** [opencv/opencv#18975]
opencv dnn module suport  Scaled yolov4 (https://arxiv.org/abs/2011.08036) (https://github.com/WongKinYiu/ScaledYOLOv4 )model?

**Comment by dkurt** [comment]
Have you tried to run it? If it does not work - we can convert this issues to feature request.

**Comment by arnaud-nt2i** [comment]
@dkurt 
from : https://github.com/AlexeyAB/darknet/issues/6987#issuecomment-729218069
> If there is set `[yolo] new_coords=1` then:
> 
> 1. We use Logistic (sigmoid) not only for `x,y`, but for `x,y,w,h` [8c9c517#diff-a191a7d286ab1bacf527ae4b5edfbad6951b06a4d80685393577af64eb8e8a8fR950](https://github.com/AlexeyAB/darknet/commit/8c9c5171891ea92b0cbf5c7fddf935df0b854540#diff-a191a7d286ab1bacf527ae4b5edfbad6951b06a4d80685393577af64eb8e8a8fR950)
> 2. The coordinates should be calculated in this way: [8c9c517#diff-a191a7d286ab1bacf527ae4b5edfbad6951b06a4d80685393577af64eb8e8a8fR141-R144](https://github.com/AlexeyAB/darknet/commit/8c9c5171891ea92b0cbf5c7fddf935df0b854540#diff-a191a7d286ab1bacf527ae4b5edfbad6951b06a4d80685393577af64eb8e8a8fR141-R144)
> 
> So in total:
> 
> ```
> x = (logistic(in) * 2 - 0.5 + grid_x) / grid_width
> y = ...
> w = pow( logistic(in)*2, 2) * anchor / network_width
> h = ...
> ```
> 
> 1. We use `nms=0.6` instead of `0.45`
> 2. We use `diounms()` [c7e3e2e#diff-2c2b9046564ae9ad1ba54f4b42a3c8acbf98af531e411be6281687f6b6689e98L](https://github.com/AlexeyAB/darknet/commit/c7e3e2ee9ec2d8fff447d83736e13bce0938015f#diff-2c2b9046564ae9ad1ba54f4b42a3c8acbf98af531e411be6281687f6b6689e98L916)

**Comment by toplinuxsir** [comment]
@dkurt   I have  tested with opecv 4.5 dnn model  and it  load scaled yolov4 model ok, Detection  works ok,

**Comment by dkurt** [comment]
Thank you! Can we close an issue?

**Comment by toplinuxsir** [comment]
Yes, I think.

**Comment by toplinuxsir** [comment]
Yes, I think.

**Comment by arnaud-nt2i** [comment]
> @dkurt I have tested with OpenCV 4.5 dnn model and it load scaled yolov4 model ok, Detection works ok,

Hi! 
Are the results similar to those in Darknet framework ? (mAP)
 The results shouldn't be the same without the needed fixes ...

**Comment by toplinuxsir** [comment]
@dkurt , I confirmed it again:
 The opencv dnn model ,Can work with : https://hackmd.io/NFj2NrmqTcefjc2l94KjpQ
 doese not work with : https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg

**Comment by dkurt** [comment]
Please add more details about the problematic model - copy error message if it does not load or provide origin image and expected detection results.

**Comment by arnaud-nt2i** [comment]
> @dkurt ,
> Scaled-yolov4 and yolov4x-mish is similar ,
> But, I tested it again:
> The opencv dnn model ,Can work with : https://hackmd.io/NFj2NrmqTcefjc2l94KjpQ
> doese not work with : https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg
> 
> > > @dkurt I have tested with OpenCV 4.5 dnn model and it load scaled yolov4 model ok, Detection works ok,
> > > @toplinuxsir
> > > Hi!
> > > Are the results similar to those in Darknet framework ? (mAP)
> > > The results shouldn't be the same without the needed fixes ...

@toplinuxsir Scaled-yolov4 and yolov4x-mish are the same models!  The first link you posted is for regular yolov4 models
To sum up: 
- all yolov4 models work with OpenCV DNN (except SAM ones)
- Scaled yolov4 == yolov4x-mish does not work

@dkurt Scaled yolov4 Is now working and stat of the art performance/execution time 
Open CV DNN should support it.
I posted what needs to be implemented in open cv some days ago here: https://github.com/opencv/opencv/issues/18975#issuecomment-736695393

cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
trained weight on coco to test: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights
![image](https://user-images.githubusercontent.com/69960875/101460779-5280ef00-393a-11eb-9dba-cf30017926dd.png)

**Comment by toplinuxsir** [comment]
@dkurt I use opencv 4.5 ,Use Dnn load yolov4x-mish model , and detect with the model ,no error message, But get the much more detection results

**Comment by AlexeyAB** [comment]
@dkurt Hi,


There are new models:
* yolov4-csp
    * cfg:  https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg
    * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights

* yolov4x-mish
    * cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
    * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights

----

These new models (**Scaled YOLOv4**) use new `x,y,w,h` function if there is set `new_coords=1` in the `[yolo]` layer: 
![image](https://user-images.githubusercontent.com/4096485/102160336-4e068a00-3e96-11eb-9af3-2138634b6033.png)

Just logistic activation will be used in the previous `[convolutional]` layer instead of `[yolo]` layer: https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg#L1254

----

So these models require these changes:
1. Change https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L273-L293 
to
```cpp
if (new_coords == true) {
                            float x_tmp = (srcData[box_index + 0] - 0.5f) * scale_x_y + 0.5f;
                            float y_tmp = (srcData[box_index + 1] - 0.5f) * scale_x_y + 0.5f;
                            dstData[box_index + 0] = (x + x_tmp) / cols;
                            dstData[box_index + 1] = (y + y_tmp) / rows;
                            dstData[box_index + 2] = srcData[box_index + 2] * srcData[box_index + 2] * 4 * biasData[2 * a] / wNorm;
                            dstData[box_index + 3] = srcData[box_index + 3] * srcData[box_index + 3] * 4 * biasData[2 * a + 1] / hNorm;
} else {
                            float x_tmp = (logistic_activate(srcData[box_index + 0]) - 0.5f) * scale_x_y + 0.5f;
                            float y_tmp = (logistic_activate(srcData[box_index + 1]) - 0.5f) * scale_x_y + 0.5f;
                            dstData[box_index + 0] = (x + x_tmp) / cols;
                            dstData[box_index + 1] = (y + y_tmp) / rows;
                            dstData[box_index + 2] = exp(srcData[box_index + 2]) * biasData[2 * a] / wNorm;
                            dstData[box_index + 3] = exp(srcData[box_index + 3]) * biasData[2 * a + 1] / hNorm;
}
```

----

2. Insert this block of code into if-statement `if (new_coords == false) { ... code ... }`  https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L273-L293

**Comment by arnaud-nt2i** [comment]
@dkurt  Hi, 
I haven't seen #features and #priority tags so I am bit worried you forgot this tread ...
How are things going?

**Comment by arnaud-nt2i** [comment]
@alalek 
 Thank you

**Comment by erikguo** [comment]
> @dkurt Hi,
> 
> There are new models: [AlexeyAB/darknet#7087](https://github.com/AlexeyAB/darknet/issues/7087)
> 
> * yolov4-csp
>   
>   * cfg:  https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg
>   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights
> * yolov4x-mish
>   
>   * cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
>   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights
> 
> These new models (**Scaled YOLOv4**) use new `x,y,w,h` function if there is set `new_coords=1` in the `[yolo]` layer:
> ![image](https://user-images.githubusercontent.com/4096485/102160336-4e068a00-3e96-11eb-9af3-2138634b6033.png)
> 
> Just logistic activation will be used in the previous `[convolutional]` layer instead of `[yolo]` layer: https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg#L1254
> 
> To use `* 2 - 0.5` instead of `* 1.1 - 0.05` you should **not** change anything, because it is specified in old parameter `scale_x_y=`, it is already implemented.
> 
> So these models require these changes:
> 
> 1. Change https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L306-L311
>    
>    to
> 
> ```c++
> if (new_coords == true) {
>                             float x_tmp = (srcData[box_index + 0] - 0.5f) * scale_x_y + 0.5f;
>                             float y_tmp = (srcData[box_index + 1] - 0.5f) * scale_x_y + 0.5f;
>                             dstData[box_index + 0] = (x + x_tmp) / cols;
>                             dstData[box_index + 1] = (y + y_tmp) / rows;
>                             dstData[box_index + 2] = srcData[box_index + 2] * srcData[box_index + 2] * 4 * biasData[2 * a] / wNorm;
>                             dstData[box_index + 3] = srcData[box_index + 3] * srcData[box_index + 3] * 4 * biasData[2 * a + 1] / hNorm;
> } else {
>                             float x_tmp = (logistic_activate(srcData[box_index + 0]) - 0.5f) * scale_x_y + 0.5f;
>                             float y_tmp = (logistic_activate(srcData[box_index + 1]) - 0.5f) * scale_x_y + 0.5f;
>                             dstData[box_index + 0] = (x + x_tmp) / cols;
>                             dstData[box_index + 1] = (y + y_tmp) / rows;
>                             dstData[box_index + 2] = exp(srcData[box_index + 2]) * biasData[2 * a] / wNorm;
>                             dstData[box_index + 3] = exp(srcData[box_index + 3]) * biasData[2 * a + 1] / hNorm;
> }
> ```
> 
> 1. Insert this block of code into if-statement `if (new_coords == false) { ... code ... }`  https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L273-L293

I just tried to do the modification in my opencv source file, but the detection result is totally wrong without any error information. How can I debug the prolbem ?  thanx.

**Comment by toplinuxsir** [comment]
@dkurt Hi, It is fixed by opencv 4.5.1 (just released)?

**Comment by erikguo** [comment]
Today I found the cause of problem. After fixed, my opencv can run the yolov4x-mish.cfg now. But I found the box confidenses is all below 0.6.  I don't know why ?

**Comment by arnaud-nt2i** [comment]
@erikguo Hi !
How things are going regarding your fix ?
Is the confidence pb solved ?
thanks

**Comment by erikguo** [comment]
@arnaud-nt2i 
The confidence problem is solved. I can run my prediction very well.

**Comment by toplinuxsir** [comment]
@erikguo 
The yolov4x-mish feature will be available in the next opencv release ?

**Comment by s1n7ax** [comment]
# yolov4-csp results
I don't know if I understood the [comment](https://github.com/opencv/opencv/issues/18975#issuecomment-749313403) but following are the results.

## Versions
Following are the current versions (2021/02/05)

**Darknet:**
```
commit 64efa721ede91cd8ccc18257f98eeba43b73a6af (origin/master, origin/HEAD)
Merge: 00d578e fb8c944
Author: Alexey <AlexeyAB@users.noreply.github.com>
Date:   Thu Jan 21 22:30:15 2021 +0300
```

**OpenCV:**
```
commit 050327a1e2aef915562c22566c4fa5bed71c1b72 (HEAD -> master, origin/master, origin/HEAD)
Merge: 3e34cec96b fcff767a7f
Author: Alexander Alekhin <alexander.a.alekhin@gmail.com>
Date:   Thu Feb 4 16:03:24 2021 +0000
```

## Darknet
### Darknet -> yolov4-csp ([yolov4-csp.cfg](https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg))

**results:**
![predictions](https://user-images.githubusercontent.com/18459807/107010045-d9780980-67bb-11eb-8252-71ec967e4056.jpg)


### Darknet -> yolov4-608 ([yolov4.cfg](https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4.cfg))
**results:**
![predictions](https://user-images.githubusercontent.com/18459807/107009990-c9602a00-67bb-11eb-9622-4d0354ada6ef.jpg)


## OpenCV
### OpenCV -> yolov4-csp ([yolov4-csp.cfg](https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg))
**results:**
![image](https://user-images.githubusercontent.com/18459807/107008027-4d64e280-67b9-11eb-8833-62c5bc45ce14.png)


### OpenCV -> yolov4-csp ([new coords off yolov4-csp.cfg](https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg))
**cfg**
```
scale_x_y = 2.0
new_coords=0
```
**results:**
![image](https://user-images.githubusercontent.com/18459807/107007672-ddeef300-67b8-11eb-9259-e86f5a220420.png)

### OpenCV -> yolov4-608 ([yolov4.cfg](https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4.cfg))
**results:**
![image](https://user-images.githubusercontent.com/18459807/107009245-c87ac880-67ba-11eb-9ed8-bfabbe3a306b.png)

**Comment by koolvn** [comment]
@erikguo 
> The confidence problem is solved. I can run my prediction very well.

Hi, how did you solve the confidence problem?

**Comment by arnaud-nt2i** [comment]
@erikguo @AlexeyAB @dkurt 
Hi, could you please fix your PR  #19221 in order to have support for yolov4x-mish in OpenCV master branch?
This would be greatly appreciated ;)

**Comment by PerLycke** [comment]
I guess it was confusing when OP suddenly said it worked and that the issue could be closed, and thus maybe @dkurt unsubscribed from the issue. It would certainly be a nice addition if scaled yolov4 models could be supported with the help of https://github.com/opencv/opencv/issues/18975#issuecomment-745012567

**Comment by erikguo** [comment]
@asmorkalov ,

I already create another pull-request to backport to 3.4 for supporting yolov4x-mish in CPU mode.  Could you please check it. 

and Sorry for late updating of busy job.

**Comment by erikguo** [comment]
@koolvn @s1n7ax 

You could try manually apply my changes and compile the opencv before new verion releasing.

**Comment by KyloEntro** [comment]
Hi, 
I'm confused, Do OpenCV (4.5.2) with CUDA Backend support Scaled YoloV4 ?

**Comment by akashAD98** [comment]
what is the advantage of new_coord=1 & what's the exact work of it?? can someone please explain this concept??

**Comment by arnaud-nt2i** [comment]
@akashAD98 better performances, see :

![](https://user-images.githubusercontent.com/4096485/112776361-281d8380-9048-11eb-8083-8728b12dcd55.png)

**Comment by Egorka1** [comment]
> @dkurt Hi,
> 
> There are new models: [AlexeyAB/darknet#7087](https://github.com/AlexeyAB/darknet/issues/7087)
> 
> * yolov4-csp
>   
>   * cfg:  https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg
>   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights
> * yolov4x-mish
>   
>   * cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
>   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights
> 
> These new models (**Scaled YOLOv4**) use new `x,y,w,h` function if there is set `new_coords=1` in the `[yolo]` layer:
> ![image](https://user-images.githubusercontent.com/4096485/102160336-4e068a00-3e96-11eb-9af3-2138634b6033.png)
> 
> Just logistic activation will be used in the previous `[convolutional]` layer instead of `[yolo]` layer: https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg#L1254
> 
> To use `* 2 - 0.5` instead of `* 1.1 - 0.05` you should **not** change anything, because it is specified in old parameter `scale_x_y=`, it is already implemented.
> 
> So these models require these changes:
> 
> 1. Change https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L306-L311
>    
>    to
> 
> ```c++
> if (new_coords == true) {
>                             float x_tmp = (srcData[box_index + 0] - 0.5f) * scale_x_y + 0.5f;
>                             float y_tmp = (srcData[box_index + 1] - 0.5f) * scale_x_y + 0.5f;
>                             dstData[box_index + 0] = (x + x_tmp) / cols;
>                             dstData[box_index + 1] = (y + y_tmp) / rows;
>                             dstData[box_index + 2] = srcData[box_index + 2] * srcData[box_index + 2] * 4 * biasData[2 * a] / wNorm;
>                             dstData[box_index + 3] = srcData[box_index + 3] * srcData[box_index + 3] * 4 * biasData[2 * a + 1] / hNorm;
> } else {
>                             float x_tmp = (logistic_activate(srcData[box_index + 0]) - 0.5f) * scale_x_y + 0.5f;
>                             float y_tmp = (logistic_activate(srcData[box_index + 1]) - 0.5f) * scale_x_y + 0.5f;
>                             dstData[box_index + 0] = (x + x_tmp) / cols;
>                             dstData[box_index + 1] = (y + y_tmp) / rows;
>                             dstData[box_index + 2] = exp(srcData[box_index + 2]) * biasData[2 * a] / wNorm;
>                             dstData[box_index + 3] = exp(srcData[box_index + 3]) * biasData[2 * a + 1] / hNorm;
> }
> ```
> 
> 1. Insert this block of code into if-statement `if (new_coords == false) { ... code ... }`  https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L273-L293

Hi. As far as I understand it will not work with CUDA. What to do in this case?

**Comment by arnaud-nt2i** [comment]
@Egorka1 see: https://github.com/opencv/opencv/pull/19877#issuecomment-852865269

**Comment by Egorka1** [comment]
Yes, this is what is described above. In conjunction with CUDA, it does not give correct predictions and probabilities (compared with the results directly through the command `./darknet detector test`)

**Comment by kgksl** [comment]
> > @dkurt Hi,
> > There are new models: [AlexeyAB/darknet#7087](https://github.com/AlexeyAB/darknet/issues/7087)
> > 
> > * yolov4-csp
> >   
> >   * cfg:  https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg
> >   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights
> > * yolov4x-mish
> >   
> >   * cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
> >   * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights
> > 
> > These new models (**Scaled YOLOv4**) use new `x,y,w,h` function if there is set `new_coords=1` in the `[yolo]` layer:
> > ![image](https://user-images.githubusercontent.com/4096485/102160336-4e068a00-3e96-11eb-9af3-2138634b6033.png)
> > Just logistic activation will be used in the previous `[convolutional]` layer instead of `[yolo]` layer: https://github.com/AlexeyAB/darknet/blob/e7d029c11986156b818690bd1375a54286b8f315/cfg/yolov4-csp.cfg#L1254
> > To use `* 2 - 0.5` instead of `* 1.1 - 0.05` you should **not** change anything, because it is specified in old parameter `scale_x_y=`, it is already implemented.
> > So these models require these changes:
> > 
> > 1. Change https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L306-L311
> >    
> >    to
> > 
> > ```c++
> > if (new_coords == true) {
> >                             float x_tmp = (srcData[box_index + 0] - 0.5f) * scale_x_y + 0.5f;
> >                             float y_tmp = (srcData[box_index + 1] - 0.5f) * scale_x_y + 0.5f;
> >                             dstData[box_index + 0] = (x + x_tmp) / cols;
> >                             dstData[box_index + 1] = (y + y_tmp) / rows;
> >                             dstData[box_index + 2] = srcData[box_index + 2] * srcData[box_index + 2] * 4 * biasData[2 * a] / wNorm;
> >                             dstData[box_index + 3] = srcData[box_index + 3] * srcData[box_index + 3] * 4 * biasData[2 * a + 1] / hNorm;
> > } else {
> >                             float x_tmp = (logistic_activate(srcData[box_index + 0]) - 0.5f) * scale_x_y + 0.5f;
> >                             float y_tmp = (logistic_activate(srcData[box_index + 1]) - 0.5f) * scale_x_y + 0.5f;
> >                             dstData[box_index + 0] = (x + x_tmp) / cols;
> >                             dstData[box_index + 1] = (y + y_tmp) / rows;
> >                             dstData[box_index + 2] = exp(srcData[box_index + 2]) * biasData[2 * a] / wNorm;
> >                             dstData[box_index + 3] = exp(srcData[box_index + 3]) * biasData[2 * a + 1] / hNorm;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Insert this block of code into if-statement `if (new_coords == false) { ... code ... }`  https://github.com/opencv/opencv/blob/fcdd69fd972d96cfc7861948a4b2bc5d20d3cf42/modules/dnn/src/layers/region_layer.cpp#L273-L293
> 
> Hi. As far as I understand it will not work with CUDA. What to do in this case?

@Egorka1 can you please explain what you meant by ` it will not work with CUDA`: is it because the change is targeted to OpenCv3.x branch or some other reason? ( I am new to this and looking forward to your reply, and hopefully it will make things less confusing for me) Thanks.

**Comment by arnaud-nt2i** [comment]
@Egorka1 @kgksl 
when `./darknet detector test` is called with a yolov4 scaled cfg, you are in most case using cuda (to run detection on gpu) in the darknet framework and it is working **perfectly** fine !
But here we are on OpenCv Repo so what we are expecting is to run a yolov4 scaled model in OpenCv Dnn framework (with cuda as well) which is not working for now.

**Comment by Egorka1** [comment]
@arnaud-nt2i
Yes, but here people are saying how the OpenCV sources can be modified to run yolov4scaled in opencv dnn module. Maybe someone else faced such a problem and knows how to solve it

**Comment by akashAD98** [comment]
@arnaud-nt2i have you solved the problem? scaled yolov4 is supporting yolov4-mish? if yes please share the python script.Thanks

**Comment by arnaud-nt2i** [comment]
> @arnaud-nt2i have you solved the problem? scaled yolov4 is supporting yolov4-mish? if yes please share the python script.Thanks

no, 
of course scaled yolov4 is supporting yolov4-mish **in DARKNET**

**Comment by bml1g12** [comment]
> But here we are on OpenCv Repo so what we are expecting is to run a yolov4 scaled model in OpenCv Dnn framework (with cuda as well) which is not working for now ( no matter what OpenCV branch your are on).

I am unsure why this issue closed if `csp` models are not working with OpenCV?

I saw @AlexeyAB  [said](https://github.com/AlexeyAB/darknet/issues/8146#issuecomment-946251267) it is fixed on the latest version of OpenCV - has anyone confirmed that experimentally or provide a link to the evidence that it's fixed? Thanks!
