### ISSUE TITLE
wiki: add unit test requirement to use ENABLE_FAST_MATH=OFF

### ISSUE THREAD

**Issue by diablodale** [opencv/opencv#18989]
Hi. Multiple core tests will fail if `ENABLE_FAST_MATH=ON`. This is due to fast math not having strict rules and exceptions like the standard math library. I recommend a sentence be added to the Wiki to declare this.

### Setup

* OpenCV 4.5.x master e726ff3296b9e382371a778ad807d37a2e49b979
* VS2019 Community v16.8.2
* compile target = Windows amd64
* Debug build with `ENABLE_FAST_MATH=ON`

### Repro

1. Build opencv
2. run test `opencv_test_cored.exe`

### Result

Multiple tests will fail. Here is the list on my computer

```
[  FAILED  ] hal_intrin128.float32x4_CPP_EMULATOR
[  FAILED  ] hal_intrin128.float64x2_CPP_EMULATOR
[  FAILED  ] hal_intrin128.float32x4_BASELINE
[  FAILED  ] hal_intrin128.float64x2_BASELINE
[  FAILED  ] hal_intrin128.float32x4_SSE2
[  FAILED  ] hal_intrin128.float64x2_SSE2
[  FAILED  ] hal_intrin128.float32x4_SSE3
[  FAILED  ] hal_intrin128.float64x2_SSE3
[  FAILED  ] hal_intrin128.float32x4_SSSE3
[  FAILED  ] hal_intrin128.float64x2_SSSE3
[  FAILED  ] hal_intrin128.float32x4_SSE4_1
[  FAILED  ] hal_intrin128.float64x2_SSE4_1
[  FAILED  ] hal_intrin128.float32x4_SSE4_2
[  FAILED  ] hal_intrin128.float64x2_SSE4_2
[  FAILED  ] hal_intrin128.float32x4_AVX
[  FAILED  ] hal_intrin128.float64x2_AVX
[  FAILED  ] Mat.regression_10507_mat_setTo
[  FAILED  ] Core_KMeans.bad_input
```

### Expected

No failures.

### Notes

I am not concerned that these test cases fail. My concern is that the failures are reported. Therefore, I suggest add a sentence to the QA section in the OpenCV wiki https://github.com/opencv/opencv/wiki/QA_in_OpenCV in first section, 4th paragraph

> Please note that you should set OPENCV_TEST_DATA_PATH environment variable (see section 9 in OpenCV Coding Style Guilde). On Android you should copy test data to the /sdcard/opencv_testdata directory:

change to

> Please note that you should set OPENCV_TEST_DATA_PATH environment variable (see section 9 in OpenCV Coding Style Guilde). If you enable fast math with `ENABLE_FAST_MATH=ON`, it is expected some test cases will fail. On Android you should copy test data to the /sdcard/opencv_testdata directory:

An alternative is to automatically disable these test cases if it was built with `ENABLE_FAST_MATH=ON`. But this is extra work with marginal benefit compared to simply adding a sentence to the wiki.

**Comment by alalek** [comment]
`ENABLE_FAST_MATH` is disabled by default in OpenCV and in compilers.
This is done for a reason and enabling that (or any other options) is responsibility of the "user".

> Wiki

Not sure that is the right place for such information. This paragraph is about testdata, not about the test accuracy limits.

**Comment by diablodale** [comment]
I can understand that perspective. My intention is to *proactively* save time of some developer (like me) or others (like https://answers.opencv.org/question/214631/34-failed-test-in-opencv-410s-core-test/) that enable fast math and then expend time tracking down the cause of failing test cases. It is very easy to enable it with cmake flags and GUIs....and often ok because some apps can be a little less accurate to gain speed.

Given that "answers" post and now this issue, that's two places future dev's can find answers after they encounter the test failures. This is somewhat a project team's ethos and how much to document. Personally, I like to clearly document the test harness setup and proactively warn of issues. I defer to your project experience if this meets the doc "bar" on the continuum.
 
If in the wiki, I agree the lower wiki section https://github.com/opencv/opencv/wiki/QA_in_OpenCV#accuracy-tests is a better place.

😂 I was determined to have *all* the test cases pass.

**Comment by alalek** [comment]
"test cases may fail" statement doesn't look right.
Regardless of build mode test case should pass, or has adjusted threshold (pass again) or become disabled/skipped for such mode - result must be "green" if there are no regressions.

Unfortunately this is just a low priority task to maintain correct behavior of this option, so nobody looks on that really.

Most of flags are added by community or developers "as is" without any claims about future support of such flags.
"Default" set of configuration is maintained "by default". Other cases "depend" on some extra factors.

**Comment by diablodale** [comment]
Agreed. I'll close this -- both this issue and the "answers" can be found with searches for advanced devs pushing edge cases ;-)

**Comment by rgaufman** [comment]
Other than failing unit tests, what are the direct implications in regular day to day use with things like doing motion detections on frames with OpenCV and things like gaussian blur, etc?
