### ISSUE TITLE
Unknown layer type: "sam" layer

### ISSUE THREAD

**Issue by arnaud-nt2i** [opencv/opencv#18988]
##### System information (version)
- OpenCV => 4.5.0 with DNN and Cuda support
- Operating System / Platform => Windows 10 64 Bit
- Compiler =>  Visual Studio 2017

##### Detailed description

While trying to use this C++ code : `https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49`
I got an error :
`OpenCV(4.5.0) Error: Parsing error (Unknown layer type: sam) in cv::dnn::darknet::ReadDarknetFromCfgStream, file C:\opencv-4.5.0\modules\dnn\src\darknet\darknet_io.cpp, line 865
`

There is indeed some SAM layers in my .cfg, is there a way to use OpenCV DNN without retraining the network without sam layers?
Any forks with sam layer support?

##### Steps to reproduce

[Yolov4-sam-mish.cfg](https://drive.google.com/file/d/1V726wzWW1iBDcJ7uP8c0n_Y4M98lIg-C/view)

relates: https://github.com/AlexeyAB/darknet/issues/5891

**Comment by l-bat** [comment]
@arnaud-nt2i please check model link

**Comment by arnaud-nt2i** [comment]
@l-bat Sorry for dead link.
Go here and pick `YOLOv4-SAM-Mish` cfg
https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo

**Comment by blafasel42** [comment]
same problem for me. is there any solution in the meantime?

**Comment by matt-sharp** [comment]
Same problem for me as well.  Has anyone got an update?
