### ISSUE TITLE
next: broken documentation builds

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#19017]
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/5_x_docs-lin64/builds/43).

relates #18940

Use for testing `build_image:Docs=docs-js`

**Comment by legercheap** [comment]
http://finance.dalycity.com/camedia.dalycity/news/read/40736255
https://is.gd/PtKva4
https://is.gd/QEkS2y
https://is.gd/kbVBEp
https://is.gd/0UNjdp
https://is.gd/vye28y
http://finance.sausalito.com/camedia.sausalito/news/read/40736255
https://bit.ly/3nietXx
https://bit.ly/3n9qKNX
https://bit.ly/3qRBqmE
https://bit.ly/348jevh
https://bit.ly/3qS9Ohm
http://finance.walnutcreekguide.com/camedia.walnutcreekguide/news/read/40736255
https://tinyurl.com/yxfzungz
https://tinyurl.com/yxjosgo9
https://tinyurl.com/y2mzfyr3
https://tinyurl.com/y5x4f9xn
https://tinyurl.com/yy8xtw7b
http://finance.burlingame.com/camedia.burlingame/news/read/40736255
https://cutt.ly/0hPOb9o
https://cutt.ly/chPOnzK
https://cutt.ly/shPOnLY
http://finance.livermore.com/camedia.livermore/news/read/40736255
https://rebrand.ly/kzavq
https://rebrand.ly/uee7w
https://rebrand.ly/vh82z
https://rebrand.ly/jffji
https://rebrand.ly/mua3y
http://b.link/ahy2w
http://b.link/pyh65
http://b.link/cxx29
http://b.link/9j2n4
http://b.link/7443r
