### ISSUE TITLE
iOS Build failure

### ISSUE THREAD

**Issue by komakai** [opencv/opencv#19014]
##### System information (version)
- OpenCV => master
- Operating System / Platform => iOS
- Compiler => XCode 12.2

##### Detailed description

Trying to build with:
`./opencv/platforms/ios/build_framework.py --iphoneos_archs=arm64 --iphonesimulator_archs=x86_64 iostest`

Fails at the start of the simulator build with:
Executing: cmake -GXcode -DAPPLE_FRAMEWORK=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DOPENCV_INCLUDE_INSTALL_PATH=include -DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty -DFRAMEWORK_NAME=opencv2 -DIOS_ARCH=x86_64 -DCMAKE_TOOLCHAIN_FILE=/Users/gilespayne/ContribNew/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneSimulator_Xcode.cmake /Users/gilespayne/ContribNew/opencv
-- Setting up iPhoneSimulator toolchain for IOS_ARCH='x86_64'
-- iPhoneSimulator toolchain loaded
-- Setting up iPhoneSimulator toolchain for IOS_ARCH='x86_64'
-- iPhoneSimulator toolchain loaded
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- The C compiler identification is AppleClang 12.0.0.12000032
CMake Error at CMakeLists.txt:109 (enable_language):
  No CMAKE_CXX_COMPILER could be found.
CMake Error at CMakeLists.txt:109 (enable_language):
  No CMAKE_C_COMPILER could be found.

If I run the cmake command that failed I get:
cmake -GXcode -DAPPLE_FRAMEWORK=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DOPENCV_INCLUDE_INSTALL_PATH=include -DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty -DFRAMEWORK_NAME=opencv2 -DIOS_ARCH=x86_64 -DCMAKE_TOOLCHAIN_FILE=/Users/gilespayne/ContribNew/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneSimulator_Xcode.cmake /Users/gilespayne/ContribNew/opencv
-- Setting up iPhoneSimulator toolchain for IOS_ARCH='x86_64'
CMake Error at platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake:98 (message):
  IPHONEOS_DEPLOYMENT_TARGET is not specified
Call Stack (most recent call first):
  platforms/ios/cmake/Toolchains/Toolchain-iPhoneSimulator_Xcode.cmake:3 (include)
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:109 (enable_language)

##### Steps to reproduce

Run the above build command

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I updated to latest OpenCV version and the issue is still there

**Comment by alalek** [comment]
> cmake/3.18.4

Try to upgrade CMake.

**Comment by komakai** [comment]
@alalek upgrading Cmake did fix it - not sure why but if that is the right fix then maybe we should do something like:
https://github.com/komakai/opencv/commit/3bc2e7b9c131aec0df48f2913cabf45434f97719
https://github.com/komakai/opencv/commit/1a22914c446ec59612319570138b87e1ce7a37b1

**Comment by alalek** [comment]
Latest CMake is necessary for Xcode 12.2.
Xcode 11.x works fine CMake 3.17 (and may be lower)
