### ISSUE TITLE
OpenCV 4.5: Compilation errors on OSX 10.9 and Xcode 6.2

### ISSUE THREAD

**Issue by nosleduc** [opencv/opencv#19038]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => OSX 10.9
- Compiler => Xcode 6.2

##### Detailed description

I do not know if OSX 10.9 and Xcode 6.2 is still a supported platform for OpenCV 4.5 but it does not compile on this platform.
There are two compilation errors when compiling p3p.cpp and ap3p.cpp

ap3p.cpp row 319:
                std::swap(solutionsR[j], solutionsR[j-1]);
                std::swap(solutionsT[j], solutionsT[j-1]);
and p3p.cpp row 202:
                std::swap(R[j], R[j-1]);
                std::swap(t[j], t[j-1]);

These errors can easily be fixed by a code like this

```
inline void myswap(double A[3][3], double B[3][3]){
    
    for(int j = 0; j < 3; ++j){
        for(int i = 0; i < 3; ++i){
            std::swap(A[j][i], B[j][i]);
        }
    }
}
```
When these small fixes are applied, the compilation succeeds

**Comment by legercheap** [comment]
http://business.malvern-online.com/malvern-online/news/read/40736255
https://is.gd/7BegTR
https://is.gd/1vWUxZ
https://is.gd/btZemj
https://is.gd/CUNFpn
https://is.gd/DaHmyG
http://finance.pleasanton.com/camedia.pleasanton/news/read/40736255
https://bit.ly/3oMqTqT
https://bit.ly/382FVC8
https://bit.ly/37doIqE
https://bit.ly/3oMqViv
https://bit.ly/37Wo53K
http://finance.millvalley.com/camedia.millvalley/news/read/40736255
https://tinyurl.com/y473u8r9
https://tinyurl.com/y6jzqvkx
https://tinyurl.com/y6pay2sg
https://tinyurl.com/y2u9wzys
https://tinyurl.com/y2bvagf3
http://finance.cortemadera.com/camedia.cortemadera/news/read/40736255
https://cutt.ly/1hPOcZ5
https://cutt.ly/phPOvfF
https://cutt.ly/phPOvD7
https://cutt.ly/5hPObyB
https://cutt.ly/ThPObRo
http://finance.sanrafael.com/camedia.sanrafael/news/read/40736255
https://rebrand.ly/uinil
https://rebrand.ly/9d7bk
https://rebrand.ly/a6hxf
http://b.link/uejbu
http://b.link/5ezyx
http://b.link/gxbas
http://b.link/83swh
http://b.link/qdy4l

**Comment by markph0204** [comment]
@alalek -- suggest closing this item -- Xcode 6 is outdated.
