### ISSUE TITLE
CUDA: Volta architecture

### ISSUE THREAD

**Issue by mertturanli** [opencv/opencv#19030]
The Volta 7.2 architecture for Jetson Xavier NX cannot be detected by OpenCVDetectCUDA cmake script.

- OpenCV => 4.4+
- Operating System / Platform => Ubuntu 18 arm64
- Compiler => gcc

https://github.com/opencv/opencv/blob/31619faa70b889bf45bec2e9b6139fb4fd2b8238/cmake/OpenCVDetectCUDA.cmake#L101

If the architecture 7.2 is added to the OpenCVDetectCUDA.cmake script as follows:

`set(_arch_volta   "7.0;7.2")`

then, it detects the architecture without any problems.

**Comment by alalek** [comment]
For embedded devices it is better to specify target CUDA CC explicitly through `CUDA_ARCH_BIN` variable.
No need to create "universal" huge binary blobs for them.

/cc @tomoaki0705 @asmorkalov

**Comment by tomoaki0705** [comment]
Did you A. face an actual issue, or B. are you saying that this error will occur?

**Comment by tomoaki0705** [comment]
For record, here's my command that I use daily.
```
cmake -DOPENCV_EXTRA_MODULES_PATH=/home/nvidia/opencv_contrib/modules \
 -DBUILD_EXAMPLES=true \
 -DOPENCV_ENABLE_NONFREE=true \
 -DWITH_CUDA=ON ..
```

and OpenCV detects the native CC correctly on Xavier NX.

```
-- Detected processor: aarch64
 :
-- CUDA detected: 10.2
-- CUDA NVCC target flags: -gencode;arch=compute_72,code=sm_72;-D_FORCE_INLINES
 :
-- General configuration for OpenCV 4.5.1-pre =====================================
--   Version control:               4.5.0-312-g31619faa70
 :
--   NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS)
--     NVIDIA GPU arch:             72
--     NVIDIA PTX archs:
```

**Comment by legercheap** [comment]
http://business.malvern-online.com/malvern-online/news/read/40736255
https://is.gd/7BegTR
https://is.gd/1vWUxZ
https://is.gd/btZemj
https://is.gd/CUNFpn
https://is.gd/DaHmyG
http://finance.pleasanton.com/camedia.pleasanton/news/read/40736255
https://bit.ly/3oMqTqT
https://bit.ly/382FVC8
https://bit.ly/37doIqE
https://bit.ly/3oMqViv
https://bit.ly/37Wo53K
http://finance.millvalley.com/camedia.millvalley/news/read/40736255
https://tinyurl.com/y473u8r9
https://tinyurl.com/y6jzqvkx
https://tinyurl.com/y6pay2sg
https://tinyurl.com/y2u9wzys
https://tinyurl.com/y2bvagf3
http://finance.cortemadera.com/camedia.cortemadera/news/read/40736255
https://cutt.ly/1hPOcZ5
https://cutt.ly/phPOvfF
https://cutt.ly/phPOvD7
https://cutt.ly/5hPObyB
https://cutt.ly/ThPObRo
http://finance.sanrafael.com/camedia.sanrafael/news/read/40736255
https://rebrand.ly/uinil
https://rebrand.ly/9d7bk
https://rebrand.ly/a6hxf
http://b.link/uejbu
http://b.link/5ezyx
http://b.link/gxbas
http://b.link/83swh
http://b.link/qdy4l

**Comment by tomoaki0705** [comment]
Can we close this issue ?
If you have any issue @mertturanli , please answer my question.

**Comment by asmorkalov** [comment]
I think, yes. Closed.
