### ISSUE TITLE
`TypeError: Expected Ptr<cv::UMat> for argument 'img'`

### ISSUE THREAD

**Issue by calvin-valtz** [opencv/opencv#19063]
##### System information (version)

- OpenCV => :4.40
- Operating System / Platform => : Ubuntu 20.04
- Compiler => : Python 3.8

I got this error when running my file
`TypeError: Expected Ptr<cv::UMat> for argument 'img'`

The error comes from this script 

```

def draw_homography_points(img, x, resize=256, color=(255,0,0)):
    y_start1 = (0.3+x[2])*(resize-1)
    y_start = 0.3*(resize-1)
    y_stop = resize-1
    src = np.float32([[0.45*(2*resize-1),y_start],[0.55*(2*resize-1), y_start],[0.1*(2*resize-1),y_stop],[0.9*(2*resize-1), y_stop]])
    dst = np.float32([[(0.45+x[0])*(2*resize-1), y_start1],[(0.55+x[1])*(2*resize-1), y_start1],[(0.45+x[0])*(2*resize-1), y_stop],[(0.55+x[1])*(2*resize-1),y_stop]])
    dst_ideal = np.float32([[0.45*(2*resize-1), y_start],[0.55*(2*resize-1), y_start],[0.45*(2*resize-1), y_stop],[0.55*(2*resize-1),y_stop]])
    [cv2.circle(np.asarray(img), tuple(idx), radius=5, thickness=-1, color=(255,0,0)) for idx in src]
    [cv2.circle(np.asarray(img), tuple(idx), radius=5, thickness=-1, color=(0,255,0)) for idx in dst_ideal]
    [cv2.circle(np.asarray(img), tuple(idx), radius=5, thickness=-1, color=(0,0,255)) for idx in dst]
   return img


```
i found similar problem like mine in  https://github.com/opencv/opencv/issues/18120 and follow @alalek instruction
i try to declare img = np.array(img), but it still won't solved my issue. Do anyone have an idea about this?

**Comment by legercheap** [comment]
http://business.sweetwaterreporter.com/sweetwaterreporter/news/read/40736255
https://is.gd/UBRhYe
https://is.gd/wbzmhm
https://is.gd/wIf5wW
https://is.gd/7DQzO2
https://is.gd/m1z1M8
http://business.ridgwayrecord.com/ridgwayrecord/news/read/40736255
https://bit.ly/3qOUd1T
https://bit.ly/3ngweGz
https://bit.ly/3mfg3Z1
https://bit.ly/2KoWznC
https://bit.ly/37X9Z2e
http://business.kanerepublican.com/kanerepublican/news/read/40736255
https://tinyurl.com/y2wfr9y2
https://tinyurl.com/y47ljrdt
https://tinyurl.com/yynyuuob
https://tinyurl.com/y6my5bhq
https://tinyurl.com/y4jp8cyj
http://business.smdailypress.com/smdailypress/news/read/40736255
https://cutt.ly/ZhPOlMO
https://cutt.ly/ChPOzmA
https://cutt.ly/RhPOz8Y
https://cutt.ly/BhPOxB8
https://cutt.ly/whPOcg7
http://business.theantlersamerican.com/theantlersamerican/news/read/40736255
https://rebrand.ly/fj3fc
https://rebrand.ly/vtgq2
https://rebrand.ly/so2a3
https://rebrand.ly/i5xdz
https://rebrand.ly/yotxp
http://business.minstercommunitypost.com/minstercommunitypost/news/read/40736255
http://b.link/8x7q9
http://b.link/vvcd7
http://b.link/4nm4y
