### ISSUE TITLE
cv::imread/imdecode cannot load JPEG2000 codestream

### ISSUE THREAD

**Issue by tailsu** [opencv/opencv#19083]
##### System information (version)

- OpenCV => 4.4
- Operating System / Platform => MacOS Big Sur
- Compiler => Clang 12

##### Detailed description

The JPEG2000 standard defines both a "codestream" format and a file format for JP2K data. A codestream should ideally always be wrapped in the file format container, but in practice raw codestreams are sometimes found in the wild.

The OpenCV integration of OpenJPEG can read the JP2K file format, but not raw codestreams (also checked today's master). OpenJPEG itself has no problem reading codestreams (tested with the `opj_decompress` tool).

A codestream can be identified by its [4-byte header](http://fileformats.archiveteam.org/wiki/JPEG_2000_codestream#Identification) `FF 4F FF 51`.

OpenCV's JP2K file signature check should test for both the file header and the codestream header.

##### Steps to reproduce

Call `cv::imread` on the attached file.
[balloon.j2c.zip](https://github.com/opencv/opencv/files/5680574/balloon.j2c.zip)

**Comment by legercheap** [comment]
https://www.htv10.tv/story/43029830/the-history-for-the-herve-leger
https://is.gd/V1ucUz
https://is.gd/qTGRBL
https://is.gd/iYfb1a
https://is.gd/4XGKR4
https://is.gd/Tl31yp
https://is.gd/YdIwV7
http://markets.winslowevanscrocker.com/winslow/news/read/40736255
https://bit.ly/3a7egCY
https://bit.ly/3qTavqs
https://bit.ly/342R8l9
https://bit.ly/37X9RQi
https://bit.ly/2W6Gt4q
https://pronewsreport.com/2020/12/09/the-history-for-the-herve-leger/
https://tinyurl.com/y53o5ekh
https://tinyurl.com/y385axyt
https://tinyurl.com/y6bdbuxh
https://tinyurl.com/yysgldy8
https://tinyurl.com/y3sdon3q
http://business.borgernewsherald.com/borgernewsherald/news/read/40736255
https://cutt.ly/FhPOhXr
https://cutt.ly/RhPOjvf
https://cutt.ly/KhPOjXU
https://cutt.ly/9hPOkpD
https://cutt.ly/lhPOk3m
http://finance.minyanville.com/minyanville/news/read/40736255
https://rebrand.ly/esrj1
https://rebrand.ly/7l0wb
https://rebrand.ly/y0664
https://rebrand.ly/lwyuo
https://rebrand.ly/qyro1
http://b.link/8g74m
http://b.link/w8u86
http://b.link/6upgk
http://b.link/vhh2w
http://b.link/ca3r5
http://tiny.cc/jol6tz
