### ISSUE TITLE
CUDA Stream issue in Corner Detection Sparse Optical Flow

### ISSUE THREAD

**Issue by nikhilarane** [opencv/opencv#19081]
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows 64 bit
- Compiler => Visual Studio 2015

##### Detailed description

I tried the CUDA corners detection and sparse optical flow with CUDA stream for asynchronous operation, but both functions behave in a synchronous fashion only. Below is my code. Is there something wrong I am doing?

##### Steps to reproduce

cv::Mat leftGray, rightGray;

leftGray = cv::imread("file1.jpg",0);
rightGray = cv::imread("file2.jpg",0);

cv::cuda::HostMem leftGrayFrame(leftGray, cv::cuda::HostMem::PAGE_LOCKED);
cv::cuda::HostMem rightGrayFrame(rightGray, cv::cuda::HostMem::PAGE_LOCKED);

cv::Ptr<cv::cuda::Stream> pStream1 = cv::makePtr<cv::cuda::Stream>();

int nPoints = 200;

cv::Ptr<cv::cuda::CornersDetector> pDetector = cv::cuda::createGoodFeaturesToTrackDetector(CV_8UC1, nPoints);

cv::Ptr<cv::cuda::SparsePyrLKOpticalFlow> PyrLK = cv::cuda::SparsePyrLKOpticalFlow::create(cv::Size(21, 21), 4, 30);

cv::cuda::GpuMat leftFrameGPU, rightFrameGPU, maskGPU, corners, corners2, status;

cv::cuda::HostMem cornersFrame(cv::Size(nPoints, 1), CV_32FC2, cv::cuda::HostMem::PAGE_LOCKED);

cv::cuda::HostMem cornersFrame2(cv::Size(nPoints, 1), CV_32FC2, cv::cuda::HostMem::PAGE_LOCKED);

cv::cuda::HostMem maskFrame(leftFrame.size(), CV_8UC1, cv::cuda::HostMem::PAGE_LOCKED);

cv::cuda::HostMem statusFrame(cv::Size(nPoints, 1), CV_8UC1, cv::cuda::HostMem::PAGE_LOCKED);

maskFrame.createMatHeader().setTo(cv::Scalar(255));

corners.upload(cornersFrame.createMatHeader(), *pStream1);

maskGPU.upload(maskFrame.createMatHeader(), *pStream1);

corners2.upload(cornersFrame2.createMatHeader(), *pStream1);

leftFrameGPU.upload(leftGrayFrame.createMatHeader(), *pStream1);

rightFrameGPU.upload(rightGrayFrame.createMatHeader(), *pStream1);

status.upload(statusFrame.createMatHeader(), *pStream1);

pDetector->detect(leftFrameGPU, corners, maskGPU, *pStream1);
	
PyrLK->calc(leftFrameGPU, rightFrameGPU, corners, corners2, status, cv::cuda::GpuMat(), *pStream1);

pStream1->waitForCompletion();

**Comment by legercheap** [comment]
http://business.sweetwaterreporter.com/sweetwaterreporter/news/read/40736255
https://is.gd/UBRhYe
https://is.gd/wbzmhm
https://is.gd/wIf5wW
https://is.gd/7DQzO2
https://is.gd/m1z1M8
http://business.ridgwayrecord.com/ridgwayrecord/news/read/40736255
https://bit.ly/3qOUd1T
https://bit.ly/3ngweGz
https://bit.ly/3mfg3Z1
https://bit.ly/2KoWznC
https://bit.ly/37X9Z2e
http://business.kanerepublican.com/kanerepublican/news/read/40736255
https://tinyurl.com/y2wfr9y2
https://tinyurl.com/y47ljrdt
https://tinyurl.com/yynyuuob
https://tinyurl.com/y6my5bhq
https://tinyurl.com/y4jp8cyj
http://business.smdailypress.com/smdailypress/news/read/40736255
https://cutt.ly/ZhPOlMO
https://cutt.ly/ChPOzmA
https://cutt.ly/RhPOz8Y
https://cutt.ly/BhPOxB8
https://cutt.ly/whPOcg7
http://business.theantlersamerican.com/theantlersamerican/news/read/40736255
https://rebrand.ly/fj3fc
https://rebrand.ly/vtgq2
https://rebrand.ly/so2a3
https://rebrand.ly/i5xdz
https://rebrand.ly/yotxp
http://business.minstercommunitypost.com/minstercommunitypost/news/read/40736255
http://b.link/8x7q9
http://b.link/vvcd7
http://b.link/4nm4y
