### ISSUE TITLE
Python: unable to pass 3D matrix to C++ code

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#19091]
Currently OpenCV Python bindings "automatically" converts 3D NumPy arrays into 2D `cv::Mat` with wrapping last dimension onto number of channels (to simulate `Image` with colors):

```
a = np.zeros((2,3,4), dtype='f')
print(a.shape)
info = cv.utils.dumpInputArray(a)
print(info)
```

output:

```
(2, 3, 4)
InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=6 dims(-1)=2 size(-1)=3x2 type(-1)=CV_32FC4
```

---

Related code is [here](https://github.com/opencv/opencv/blame/dd1494eebf205b0262c362bbdc57cef212464d1d/modules/python/src2/cv2.cpp#L507) (previous variant of similar code is [here](https://github.com/opencv/opencv/blame/a717b7cbedd50b129428d72b2a15ab0168a4c46c/modules/python/src2/cv2.cpp#L262) from 2010). By initial design there is support for 2D matrices and 1D arrays only.

So currently there is no way to pass 3D `cv::Mat` (1-channel) from Python to C++ code.

Just changing of mentioned code is not an option due to breaking of many user applications.
Compatibility should be preserved.

**Note**: There is such issue in Java because Java's `Mat` type is used.
Python's bindings relies on `np.array` type which leads to mentioned reinterpretation issues.

---

relates #17272
relates #19001
probably relates #18413 #17456

**Comment by legercheap** [comment]
https://www.htv10.tv/story/43029830/the-history-for-the-herve-leger
https://is.gd/V1ucUz
https://is.gd/qTGRBL
https://is.gd/iYfb1a
https://is.gd/4XGKR4
https://is.gd/Tl31yp
https://is.gd/YdIwV7
http://markets.winslowevanscrocker.com/winslow/news/read/40736255
https://bit.ly/3a7egCY
https://bit.ly/3qTavqs
https://bit.ly/342R8l9
https://bit.ly/37X9RQi
https://bit.ly/2W6Gt4q
https://pronewsreport.com/2020/12/09/the-history-for-the-herve-leger/
https://tinyurl.com/y53o5ekh
https://tinyurl.com/y385axyt
https://tinyurl.com/y6bdbuxh
https://tinyurl.com/yysgldy8
https://tinyurl.com/y3sdon3q
http://business.borgernewsherald.com/borgernewsherald/news/read/40736255
https://cutt.ly/FhPOhXr
https://cutt.ly/RhPOjvf
https://cutt.ly/KhPOjXU
https://cutt.ly/9hPOkpD
https://cutt.ly/lhPOk3m
http://finance.minyanville.com/minyanville/news/read/40736255
https://rebrand.ly/esrj1
https://rebrand.ly/7l0wb
https://rebrand.ly/y0664
https://rebrand.ly/lwyuo
https://rebrand.ly/qyro1
http://b.link/8g74m
http://b.link/w8u86
http://b.link/6upgk
http://b.link/vhh2w
http://b.link/ca3r5
http://tiny.cc/jol6tz
