### ISSUE TITLE
compile opencv 3.2.0 in cuda 11 Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-45-generic x86_64)

### ISSUE THREAD

**Issue by linpeisensh** [opencv/opencv#19093]
- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-45-generic x86_64)
- Compiler => gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

when I compile opencv 3.2.0 in my home, there is always an error:
![image](https://user-images.githubusercontent.com/52672986/101979536-19a88900-3c5e-11eb-9a8d-4a93f972ff7f.png)

after I edit as this link:
https://stackoverflow.com/questions/46584000/cmake-error-variables-are-set-to-notfound
another error occurs:
![image](https://user-images.githubusercontent.com/52672986/101979539-1f9e6a00-3c5e-11eb-8c86-418507ebc6d8.png)
1.How can I fix this?

2.but when I use "pkg-config --modversion opencv", it shows opencv version 3.2.0. How can I find this opencv package?

Thank you!

**Comment by legercheap** [comment]
https://www.htv10.tv/story/43029830/the-history-for-the-herve-leger
https://is.gd/V1ucUz
https://is.gd/qTGRBL
https://is.gd/iYfb1a
https://is.gd/4XGKR4
https://is.gd/Tl31yp
https://is.gd/YdIwV7
http://markets.winslowevanscrocker.com/winslow/news/read/40736255
https://bit.ly/3a7egCY
https://bit.ly/3qTavqs
https://bit.ly/342R8l9
https://bit.ly/37X9RQi
https://bit.ly/2W6Gt4q
https://pronewsreport.com/2020/12/09/the-history-for-the-herve-leger/
https://tinyurl.com/y53o5ekh
https://tinyurl.com/y385axyt
https://tinyurl.com/y6bdbuxh
https://tinyurl.com/yysgldy8
https://tinyurl.com/y3sdon3q
http://business.borgernewsherald.com/borgernewsherald/news/read/40736255
https://cutt.ly/FhPOhXr
https://cutt.ly/RhPOjvf
https://cutt.ly/KhPOjXU
https://cutt.ly/9hPOkpD
https://cutt.ly/lhPOk3m
http://finance.minyanville.com/minyanville/news/read/40736255
https://rebrand.ly/esrj1
https://rebrand.ly/7l0wb
https://rebrand.ly/y0664
https://rebrand.ly/lwyuo
https://rebrand.ly/qyro1
http://b.link/8g74m
http://b.link/w8u86
http://b.link/6upgk
http://b.link/vhh2w
http://b.link/ca3r5
http://tiny.cc/jol6tz

**Comment by Colorlucky** [comment]
How do you fixed it?
