### ISSUE TITLE
In opencv_contrib-4.5.0, in mcc there is no cmm.cpp in mcc module, is it a bug?

### ISSUE THREAD

**Issue by JimXu1989** [opencv/opencv#19090]
As the title said, and opencv 4.5 cannot access namesapce cmm

**Comment by legercheap** [comment]
https://www.htv10.tv/story/43029830/the-history-for-the-herve-leger
https://is.gd/V1ucUz
https://is.gd/qTGRBL
https://is.gd/iYfb1a
https://is.gd/4XGKR4
https://is.gd/Tl31yp
https://is.gd/YdIwV7
http://markets.winslowevanscrocker.com/winslow/news/read/40736255
https://bit.ly/3a7egCY
https://bit.ly/3qTavqs
https://bit.ly/342R8l9
https://bit.ly/37X9RQi
https://bit.ly/2W6Gt4q
https://pronewsreport.com/2020/12/09/the-history-for-the-herve-leger/
https://tinyurl.com/y53o5ekh
https://tinyurl.com/y385axyt
https://tinyurl.com/y6bdbuxh
https://tinyurl.com/yysgldy8
https://tinyurl.com/y3sdon3q
http://business.borgernewsherald.com/borgernewsherald/news/read/40736255
https://cutt.ly/FhPOhXr
https://cutt.ly/RhPOjvf
https://cutt.ly/KhPOjXU
https://cutt.ly/9hPOkpD
https://cutt.ly/lhPOk3m
http://finance.minyanville.com/minyanville/news/read/40736255
https://rebrand.ly/esrj1
https://rebrand.ly/7l0wb
https://rebrand.ly/y0664
https://rebrand.ly/lwyuo
https://rebrand.ly/qyro1
http://b.link/8g74m
http://b.link/w8u86
http://b.link/6upgk
http://b.link/vhh2w
http://b.link/ca3r5
http://tiny.cc/jol6tz
