### ISSUE TITLE
DIS Optical Flow Forward Backward Consistency Feature Missing

### ISSUE THREAD

**Issue by Ribitsch** [opencv/opencv#19149]
##### System information (version)

- OpenCV => 4.5.0

##### Detailed description

Unfortunately the forward backwards consistency check is not available in the opencv implementation of the DIS Optical Flow.
The problem lies in the inaccuracy of the flow result, and the FW/BW consistency check could improve results e.g. by setting the flow vector entries to NAN for pixels where the FW/BW consistency check fails. 
It is better to know that the result can not be trusted than trusting it completely although it may be a wrong result.

**Comment by llschloesser** [comment]
@Ribitsch you can simply run the algorithm twice and do the check yourself though you may need to do some small neighborhood comparison (4 neighbors of subpixel flow vector end point).

**Comment by Ribitsch** [comment]
> @Ribitsch you can simply run the algorithm twice and do the check yourself though you may need to do some small neighborhood comparison (4 neighbors of subpixel flow vector end point).

I’m not quite sure what you mean with „4 neighbors of subpixel flow vector end point“

**Comment by llschloesser** [comment]
The endpoint of the forward flow will be subpixel and so it will have 4 integer pixels it is between.
![image](https://user-images.githubusercontent.com/10792438/102659438-618c4c00-4147-11eb-8812-09f6c4d46cbe.png)
You can compare the forward endpoint to the negative of the backward flow at the nearest pixel or choose to do some comparison or interpolation with the other 3 (or more) neighboring pixels.

You might want to look into "Computing Inverse Optical Flow" and [soft range mapping](https://arxiv.org/pdf/1711.05890.pdf).

**Comment by Ribitsch** [comment]
Thanks a lot for the answer! Will have a look into the paper
