### ISSUE TITLE
Still unable to import cv2 even after downloading opencv

### ISSUE THREAD

**Issue by LoopGlitch26** [opencv/opencv#19148]
Issue:
import cv2
ImportError: No module named cv2

I've already tried each of these:
pip install opencv-python
pip3 install opencv-python
sudo pip3 install opencv-python
sudo apt install python-opencv
pip install opencv-contrib-python
pip install cv2
pip install opencv-python3 

Strangely, after multiple attempts, in an execution the ( training set )code was able to run! But then again when I ran it the same error started popping. I've tried multiple times but the error still remains weirdly.

**Comment by shanchenqi** [comment]
pip install opencv-python will install opencv on python2，pip3 install opencv-python will opencv on python3. Make sure which version is needed. To double-check, you could try to make opencv from source code.

**Comment by LoopGlitch26** [comment]
> pip install opencv-python will install opencv on python2，pip3 install opencv-python will opencv on python3. Make sure which version is needed. To double-check, you could try to make opencv from source code.

Ok, thanks
