### ISSUE TITLE
OpenCV 4.5: Can't open .pb in cv::dnn::readNetFromTensorflow

### ISSUE THREAD

**Issue by za13** [opencv/opencv#19151]
I'm using OpenCV 4.5 and Tensorflow 2.5 in Ubuntu 18 in Docker container 20.03, which has CUDA 10.2 and TensorRT 7.0.0

I have `saved_model.pb` in `/workspace/model/saved_model.pb` and in `/workspace`. In `/workspace`, I've tried 

        dnn:Net nt = cv::dnn::readNetFromTensorflow("saved_model.pb");
        dnn:Net nt = cv::dnn::readNetFromTensorflow("model/saved_model.pb");
        dnn:Net nt = cv::dnn::readNetFromTensorflow("./model/saved_model.pb");
        dnn:Net nt = cv::dnn::readNetFromTensorflow("/workspace/model/saved_model.pb");
        dnn:Net nt = cv::dnn::readNetFromTensorflow("/model/saved_model.pb");

But all of them are giving the same error of 

    String field 'opencv_tensorflow.FunctionDef.Node.ret' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
    what(): OpenCV(4.5.1-pre) /workspace/opencv/modules/dnn/src/tensorflow/tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: model/saved_model.pb in function 'ReadTFNetParamsFromBinaryFileOrDie'

Can anyone help?

**Comment by dkurt** [comment]
See https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/tensorflow/generate_tf2_models.py for example. You need to cnvert SavedModel to a frozen `.pb` graph.

**Comment by za13** [comment]
I thought I already did with this?

    unet.save('saved_model')

**Comment by dkurt** [comment]
@za13, it creates a SavedModel but you need a frozen graph:
```python
loaded = tf.saved_model.load(name)
    infer = loaded.signatures['serving_default']

    f = tf.function(infer).get_concrete_function(**kwargs)
    f2 = convert_variables_to_constants_v2(f)
    graph_def = f2.graph.as_graph_def()

    # print(graph_def)

    with tf.io.gfile.GFile(name + '_net.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())
```
examples: https://github.com/opencv/opencv/issues/16879#issuecomment-603416876 and https://github.com/opencv/opencv/issues/16582#issuecomment-603819498

**Comment by za13** [comment]
I now get 

    TypeError: signature wrapper(*, input_1) missing required arguments: input_1

when I try

    from __future__ import print_function

    import warnings

    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    from imutils.paths import list_images
    from keras import backend as K
    from keras.callbacks import CSVLogger
    from keras.layers import *
    from keras.models import Model
    from keras.optimizers import Adam
    from scipy.io import loadmat
    from scipy.misc import imread
    from skimage.io import imsave
    from skimage.transform import resize

    from scipy.io import loadmat
    import cv2
    import tensorflow as tf

    Ny=1024
    target_size = (Ny, Ny)

    warnings.filterwarnings('ignore')

    LR= 1e-4
    E, BS = 2,4 


    def get_unet(img_rows, img_cols):
        inputs = Input((img_rows, img_cols, 1))
        conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
        conv1 = BatchNormalization()(conv1)
        conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv1)
        conv1 = BatchNormalization()(conv1)
        pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

        conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(pool1)
        conv2 = BatchNormalization()(conv2)
        conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv2)
        conv2 = BatchNormalization()(conv2)
        pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

        conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool2)
        conv3 = BatchNormalization()(conv3)
        conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv3)
        conv3 = BatchNormalization()(conv3)
        pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)

        conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(pool3)
        conv4 = BatchNormalization()(conv4)
        conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv4)
        conv4 = BatchNormalization()(conv4)
        pool4 = MaxPooling2D(pool_size=(2, 2))(conv4)

        conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
        conv5 = BatchNormalization()(conv5)
        conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(conv5)
        conv5 = BatchNormalization()(conv5)
        
        conv5 = Dropout(0.5)(conv5)

        up6 = concatenate([UpSampling2D(size=(2, 2))(conv5), conv4], axis=3)
        conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(up6)
        conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv6)

        up7 = concatenate([UpSampling2D(size=(2, 2))(conv6), conv3], axis=3)
        conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(up7)
        conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv7)

        up8 = concatenate([UpSampling2D(size=(2, 2))(conv7), conv2], axis=3)
        conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(up8)
        conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv8)

        up9 = concatenate([UpSampling2D(size=(2, 2))(conv8), conv1], axis=3)
        conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(up9)
        conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv9)


        conv10 = Conv2D(1, (1, 1), activation='sigmoid')(conv9)
        
        model = Model(inputs=[inputs], outputs=[conv10])
        
        model.compile(optimizer=Adam(lr=LR), 
                          loss='binary_crossentropy',
                          metrics=['binary_crossentropy'])


        return model


    train_images=np.zeros([1, 1024,1024,1], dtype=float)
    annot_train=np.zeros([1, 1024,1024,1], dtype=float)
    test_images=np.zeros([1, 1024,1024,1], dtype=float)
    annot_test=np.zeros([1, 1024,1024,1], dtype=float)

    img = cv2.imread('owlResized.bmp', 0)/255.0 
    label = cv2.imread('owlResized.bmp', 0)/255.0
    train_images[0,:,:,0], annot_train[0,:,:,0] =img, label
    test_images[0,:,:,0], annot_test[0,:,:,0] =img, label

    print("finished reading")
    C = np.concatenate([annot_test, annot_train])
    I = np.concatenate([test_images, train_images])

    unet = get_unet(Ny, Ny)
    filepath="W-E_{epoch:02d}-L_{loss:.6f}"+outName+".h5"
    history = unet.fit(I, C, verbose=2, epochs=E, batch_size=BS, validation_split=0.1)

    #save pb
    unet.save('owlSimple', overwrite=True, include_optimizer=False, save_format='tf')



    def save(model, name, **kwargs):
        model.save(name)
        
        # Freeze model
        loaded = tf.saved_model.load(name)
        infer = loaded.signatures['serving_default']

        f = tf.function(infer).get_concrete_function(**kwargs)
        f2 = convert_variables_to_constants_v2(f)
        graph_def = f2.graph.as_graph_def()

        # print(graph_def)

        with tf.io.gfile.GFile(name + '_net.pb', 'wb') as f:
            f.write(graph_def.SerializeToString())

        shutil.rmtree(name)

    save(unet, 'owlSimple', flatten_input=tf.TensorSpec(shape=[1,1024,1024,1], dtype=tf.float32))

I get the same error if I try the entire definition of `save`, that is, lines 35-59 in that link, then I get the same error

**Comment by dkurt** [comment]
```
flatten_input
```
is a name from example. An error says that you need to use different name.

**Comment by za13** [comment]
I'm now able to convert it to frozen graph

However, when I open it with C++ using `readNetFromTensorflow`, I get the same errors as in my original comment

**Comment by za13** [comment]
can anyone help?

**Comment by dkurt** [comment]
@za13, I have no issues with OpenCV 4.5.0. Can you please try this version?
```python
import numpy as np
import cv2 as cv

net = cv.dnn.readNet('owlSimple_net.pb')
net.setInput(np.random.standard_normal((1, 1, 1024, 1024)).astype(np.float32))
out = net.forward()
print(out.shape)
```

```
(1, 1, 1024, 1024)
```

**Comment by za13** [comment]
it works when I use the Python code I mentioned in previous posts and when I use this:
```

import numpy as np
import cv2 as cv

im=cv2.imread('image.bmp')
target_size=(1024,1024)
im=np.expand_dims(im, 0)
im=np.expand_dims(im, 0)

net = cv.dnn.readNet('owlSimple_net.pb')
net.setInput(im)
out = net.forward()
```

. However, when I then add mixed precision to the training with:

```
from tensorflow.keras import mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.compat.v1.Session(config=config)
```

then when I use `cv.dnn.readNet`, I get:

    -2:unspecified error) const input blob for weights not found in function 'getConstBlob'

**Comment by dkurt** [comment]
@za13, OpenCV support only FP32 models.
