### ISSUE TITLE
Build error of involving cv::Stitcher for Android 

### ISSUE THREAD

**Issue by zcufo123** [opencv/opencv#19155]
Hi there,

I am trying to integrate the OpenCV to our new app that allow the user can do Panorama stitching after taking some photos,
but met some problem.

I download the OpenCV Android SDK from https://github.com/opencv/opencv/releases/tag/4.5.0, and I imported it into my Android Studio, and it can run well, but if I add some code about stitching into the face_detection project, the compiling is fine but there is a link error. What I did is adding a new cpp file in the same directory of DetectionBasedTracker_jni.cpp, the code is:

```
#include <opencv2/stitching.hpp>
using namespace cv;
cv::Mat stitch (std::vector <cv::Mat>& images, cv::Stitcher::Status* status)
{
    Mat pano;
    Ptr<Stitcher> stitcher = Stitcher::create();
    Stitcher::Status s = stitcher->stitch(images, pano);
    *status = s;
    return pano;
}
```

The error log is :

```
CMakeFiles/detection_based_tracker.dir/stitching.cpp.o  /Users/dantezhang/MyWorkspace/AndroidStudio/OpenCV-android-sdk/sdk/native/libs/x86_64/libopencv_java4.so -ljnigraphics -llog -ldl -lz -latomic -lm && :
/Users/dantezhang/MyWorkspace/AndroidStudio/OpenCV-android-sdk/samples/face-detection/jni/stitching.cpp:6: error: undefined reference to 'cv::Stitcher::create(cv::Stitcher::Mode)'
/Users/dantezhang/MyWorkspace/AndroidStudio/OpenCV-android-sdk/samples/face-detection/jni/stitching.cpp:7: error: undefined reference to 'cv::Stitcher::stitch(cv::_InputArray const&, cv::_OutputArray const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

So it seems that the libopencv_java4.so missed the stitcher code while the header is exported.

**Comment by alalek** [comment]
Stitching module is not wrapped with Java, so its binary code is missing in libopencv_java.so.
You need to add this dependency (`opencv_stitching`) explicitly:

`samples/face-detection/jni/CMakeLists.txt`:

```.diff
-set(ANDROID_OPENCV_COMPONENTS "opencv_java" CACHE STRING "")
+set(ANDROID_OPENCV_COMPONENTS "opencv_java;opencv_stitching" CACHE STRING "")
```

or pass this variable from CMake command-line arguments.

---

If you don't plan to use OpenCV Java API (use OpenCV C++ API only), then it is better to remove `opencv_java` from this list.

**Comment by zcufo123** [comment]
@alalek  Thank you for your reply, but it still doesn't work, the CMakeLists.txt that I have changed is:

`cmake_minimum_required(VERSION 3.6)

set(target detection_based_tracker)
project(${target} CXX)

set(ANDROID_OPENCV_COMPONENTS "opencv_stitching" CACHE STRING "")
message(STATUS "ANDROID_ABI=${ANDROID_ABI}")
find_package(OpenCV REQUIRED COMPONENTS ${ANDROID_OPENCV_COMPONENTS})

file(GLOB srcs *.cpp *.c)
file(GLOB hdrs *.hpp *.h)

include_directories("${CMAKE_CURRENT_LIST_DIR}")
add_library(${target} SHARED ${srcs} ${hdrs})
target_link_libraries(${target} ${ANDROID_OPENCV_COMPONENTS})
`

And the error log is the same, is there anything I missed?

**Comment by zcufo123** [comment]
@alalek Never mind, after "Refresh Linked C++ Projects", it works.
