### ISSUE TITLE
JavaScript dsize artefacts (cv.resize/cv.INTER_LINEAR)

### ISSUE THREAD

**Issue by KurtPachinger** [opencv/opencv#19169]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Windows 10 Home x64
- Compiler => opencv.org (Emscripten CMake)

##### Detailed description

A canvas has animated particles drawn. I used OpenCV.js for faux depth-of-field.
I used cv.resize (instead of blur) to add a tiny relative blur at any image resolution. I size it down and back up every 1s.
A small change in dsize gives very different results after a few seconds:
- When I resize by 0.99, there is a grid collecting banding artefacts.
- When I resize by 0.999, the edges collect banding artefacts.

This may be detected as an artifice or watermark through forensic analysis of altered image/video. Not sure [if this is normal](https://en.wikipedia.org/wiki/Bilinear_interpolation#/media/File:Bilininterp.png), a result of JavaScript math, or...?

##### Steps to reproduce
check the checkbox and wait a minute:
https://codepen.io/kpachinger/pen/ff6afcaccdc9ed003147b06798f3d211

I draw some subtle animation and repeatedly resize at the above tolerances.
```
dsize = new cv.Size(canvas.width, canvas.height);
cv.resize(dst, dst, dsize, 0, 0, cv.INTER_LINEAR);
```

##### Issue submission checklist

![2-prc999-edges](https://user-images.githubusercontent.com/48163461/102672155-15003b00-415e-11eb-9408-ef2325d3c673.png)
![2-prc99-grid66](https://user-images.githubusercontent.com/48163461/102672161-16c9fe80-415e-11eb-88e4-71439c066c5e.png)
![1-prc999-edges](https://user-images.githubusercontent.com/48163461/102672164-17629500-415e-11eb-88bf-3d3862e7e149.png)
![1-prc99-grid96](https://user-images.githubusercontent.com/48163461/102672167-1893c200-415e-11eb-8f5b-11d004a1334b.png)

**Comment by alalek** [comment]
> dst, dst

Do NOT do that until you really know that implementation supports in-place processing (or you will get broken result or receive performance impact).
Use dedicated buffer for results.

---

What is expected result?

> 0.999

Resize table in implementation uses 10-bit fixed point arithmetic (1/1024).
Artifacts come from there.
Won't fix that. `Use resize()` for right tasks instead.

---

> blur

Check GaussianBlur().

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by KurtPachinger** [comment]
I used GaussianBlur instead and moderated the effect with addWeighted. The right-most vertical quadrant still appeared... until I cleared my cache. Thanks!
