### ISSUE TITLE
error: (-217:Gpu API call) an illegal memory access was encountered in function 'copy'

### ISSUE THREAD

**Issue by panmengjia** [opencv/opencv#19160]
- OpenCV => 4.5.0
- Operating System / Platform =>Nvidia Jetson ubuntu18.04 aarrch64
- Compiler => qt qmake

When I test the following code,there will occur a problem :

    GpuMat d_frame_gray;
    GpuMat d_frame_conv;
    Mat frame_gray;

    Ptr<cuda::Convolution> convolver = cuda::createConvolution(Size(FILTER_HEIGHT, FILTER_WIDTH));  // the filter size is (15,15)
    for(;;)
    {
        cap>>frame;
        d_frame.upload(frame);
        printf_matrix<GpuMat>(d_frame);

        cuda::cvtColor(d_frame,d_frame_gray,cv::COLOR_RGB2GRAY);

        d_frame_gray.convertTo(d_frame_gray,CV_32FC1);
        convolver->convolve(d_frame_gray2,kernelMat[6],d_frame_conv,false); //the kernelMat[6] is a 15*15 GpuMa.
     }

the error is by followed:

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0) /home/nvidia/Downloads/opencv_contrib-4.5.0/modules/cudev/include/opencv2/cudev/grid/detail/copy.hpp:81: error: (-217:Gpu API call) an illegal memory access was encountered in function 'copy'

I want to konw how to fix the problem?

**Comment by panmengjia** [comment]
I have spend much time for fixing the issue,but the outcome is sad!!!!!

**Comment by panmengjia** [comment]
I have fixed the issue. Setting the type of  kernelMat[6] as Mat

**Comment by potemkin413** [comment]
hello, i have the same problem, but i have another code
there i have testing opencv cuda

import cv2
from cv2 import cuda

img = cv2.imread("image.jpg", cv2.IMREAD_GRAYSCALE)
src = cv2.cuda_GpuMat()
src.upload(img)


clahe = cv2.cuda.createCLAHE(clipLimit=5.0, tileGridSize=(8, 8))
dst = clahe.apply(src, cv2.cuda_Stream.Null())
result = dst.download()
cv2.imshow("result", result)
cv2.waitKey(0)

**Comment by alalek** [comment]
@potemkin413 you have another problem (check the message).

Original issue is "resolved" (incorrect usage). Closing
