### ISSUE TITLE
failed compile opencv undefined reference to `clfftInitSetupData'

### ISSUE THREAD

**Issue by xiedeacc** [opencv/opencv#19178]
- OpenCV => 4.5.1
- Operating System / Platform =>ubuntu20.04
- Compiler => gcc-8.4
I compiled clfft by myself, and library located in /usr/local/lib64, and I have add this directory to  CMAKE_LIBRARY_PATH in opencv toplevel CMakeLists.txt, I found clfftInitSetupData class in the clfft source code? so what's wrong? 
does my compile flag wrong when I compile clfft? or wrong gcc version?

**Comment by alalek** [comment]
> clfft

Not supported.

duplicate of #5444

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by xiedeacc** [comment]
fixed by add add_libraries(clFFT) in Cmakefile
