### ISSUE TITLE
.XML CODE CANNOT BE FOUND - PATH ERROR

### ISSUE THREAD

**Issue by erdaglimehmetcan** [opencv/opencv#19188]
import cv2

img = cv2.imread("Resources/face.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

path = "C:\\Users\\lenovo\\PycharmProjects\\opencvwork\\cascades\\data\\haarcascade_frontalface_default.xml"
face_cascade = cv2.CascadeClassifier(path)
faces = face_cascade.detectMultiScale(gray)

for (x, y, w, h) in faces:
    img = cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

cv2.imshow('img', img)
cv2.waitKey(0)

**Comment by erdaglimehmetcan** [comment]
![image](https://user-images.githubusercontent.com/26819265/102804423-cd321b80-43ca-11eb-8628-b89c5de5d725.png)
It stacks in a infinite loop even though my path is completyly right. My PyCharm is newly updated and opencv is 4.4.0.46
thanks

**Comment by banipreetr** [comment]
Works fine for me.

Can you try placing the XML file in the same folder as the python file that you are trying to run and adjusting the path accordingly?

**Comment by erdaglimehmetcan** [comment]
that doesn't work too. I really can't understand. Normally I am really patient about errors but I have been trying for 2 days about it

**Comment by SavedByZero** [comment]
I am having a similar issue that the forums are unable to diagnose.  This isn't python but a .so made in Unity. It was working fine in OpenCV 4.0.1, but now in 4.5.2 isn't. I successfully write my cascade xml to the persistent data storage path on my phone, I see it in the folder, I pass the exact url to the cascade classifier object, and it returns a false negative (-1).  

I'm convinced this is a bug, if not in the cascade logic itself, in either the string or url parsing logic.
