### ISSUE TITLE
Why is there an extra space character here, which distorts the format.

### ISSUE THREAD

**Issue by xiaohaoxiang** [opencv/opencv#19196]
https://github.com/opencv/opencv/blob/84676fefe3f61da5296b270bf5cb6b35db9b2f1b/samples/cpp/tutorial_code/videoio/video-input-psnr-ssim/video-input-psnr-ssim.cpp#L160

`Scalar getMSSIM( const Mat& i1, const Mat& i2)`

**Comment by Rishikesh-Reddy** [comment]
Hey this is my first time on github. What will I need to do exactly in this request?
And i am very intrested to start contributing so please help me.
