### ISSUE TITLE
How to install OpenCV 4.5.1 in Pycharm

### ISSUE THREAD

**Issue by erdaglimehmetcan** [opencv/opencv#19197]
Hi! How can I install and import the latest version in Pycharm ?
Thanks.

**Comment by alalek** [comment]
Please take a look on [these tutorials](https://docs.opencv.org/master/da/df6/tutorial_py_table_of_contents_setup.html).
There is no PyCharm specific, but they contain basic information how OpenCV Python binding works.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
This tracker is for issues and bugs that needs fix in OpenCV.
