### ISSUE TITLE
build with BUILD_opencv_js=ON error

### ISSUE THREAD

**Issue by xiedeacc** [opencv/opencv#19211]
- OpenCV => 4.5
- Operating System / Platform => ubuntu20.04
- Compiler => gcc8.4 -std=c++14
- emsdk-2.0.10
build with -D BUILD_opencv_js=ON \ -D BUILD_opencv_js_bindings_generator=ON \

wire.h:68:18: error: missing binary operator before token "(" #if __has_feature(cxx_rtti)
 error: ‘aruco’ is not a namespace-name
 using namespace aruco;

fatal error: Eigen/Core: No such file or directory#  include <Eigen/Core>

error: static assertion failed: Unbound type names are illegal with RTTI disabled. Either add -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 to or remove -fno-rtti from the compiler arguments
                     static_assert(!has_unbound_type_names,
 error: expected namespace-name before ‘;’ token
 using namespace aruco;

**Comment by alalek** [comment]
Eigen is disabled for JS builds: 

https://github.com/opencv/opencv/blob/656b20a169c1f2bbcca7e88c5ce86cf237171417/platforms/js/build_js.py#L91


Please use proper build scripts and instructions: https://docs.opencv.org/4.5.1/d4/da1/tutorial_js_setup.html
