### ISSUE TITLE
Is it possible to use libjpeg-turbo and OpenCV side by side?

### ISSUE THREAD

**Issue by m-peko** [opencv/opencv#19229]
Hi,

I tried to use libjpeg-turbo and OpenCV side by side but then `cv::imread` fails to read an image (same problem as [here](https://stackoverflow.com/questions/59945307/cvimread-fails-in-c-project-when-we-mix-opencv-and-dlib)).

I tried building libjpeg-turbo as shared library so that there is no libjpeg.a as part of libjpeg-turbo. But then, libjpeg is missing and reading images is not possible.

Do you know of any way that I could have libjpeg-turbo and OpenCV side by side?

Thanks and regards

**Comment by asmorkalov** [comment]
Please use OpenCV forum for questions: https://forum.opencv.org
