### ISSUE TITLE
opencv dnn cannot predict correct dets for yolo_v3_tiny_pan3.cfg

### ISSUE THREAD

**Issue by erikguo** [opencv/opencv#19225]
##### System information (version)
- OpenCV => 4.4.0
- Operating System / Platform => Ubuntu 16.04

##### Detailed description

I found that opencv dnn cannot predict the correct dets for  [yolo_v3_tiny_pan3.cfg](https://github.com/AlexeyAB/darknet/files/3580764/yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou.cfg.txt) . Do you know the reason?  And give me some suggestions, I can try to fix.  Thanx.

@AlexeyAB

**Comment by ZurMaD** [comment]
I think it's same issue in #19218

**Comment by l-bat** [comment]
@ZurMaD Could you try the latest master or provide link to weights to confirm issue?
