### ISSUE TITLE
OpenCV DIS Flow OpenCL results differ from CPU results

### ISSUE THREAD

**Issue by c-w-94** [opencv/opencv#19236]
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 18.04

The flow result differs from the CPU version (just try with some images). Does this behavior result from the parallelization on the gpu or are some ocl kernels erroneous?

**Comment by Ribitsch** [comment]
Why is this issue incomplete?

**Comment by mshabunin** [comment]
Please provide a minimal reproducing example application with input data. How different are the results? How do you measure it? Why is it a problem? In general one should not expect bit-exact results for different implementations and hardware.

**Comment by Ribitsch** [comment]
Hi 
I visualized it with the standard OpenCV tutorial, where the flow vectors are colored by amplitude and angle in an RGB Image.
When you compute the flow on cpu and additionally in Inge igpu (with opencl), you can optically see for many image pairs, that the results are different.
