### ISSUE TITLE
net.forward() on the openvino raspberry PI caused the wifi connection to fail

### ISSUE THREAD

**Issue by stoneWeb** [opencv/opencv#19234]
##### System information (version)
- OpenCV => 4.4.0-openvino
- Raspberrypi 4
- Python 3.7.3
- Openvino
##### Detailed description
I tried openvino face detection example on the raspberry PI , when I use `net.forward()` in an infinite loop, the wifi will automatically disconnect. But there is nothing wrong with the program itself and it works. 
```
def classify_frame(net, inputQueue, outputQueue):
	while True:
		if not inputQueue.empty():
			frame = inputQueue.get()
			frame = cv2.resize(frame, (300, 300))

			blob = cv2.dnn.blobFromImage(frame, size=(300, 300), ddepth=cv2.CV_8U) 

			net.setInput(blob)
			out = net.forward() # Debugging stops the WIFI connection at this point
			outputQueue.put(out)
```
When I comment these lines, the wifi can connect normally.

```
# out = net.forward()
# outputQueue.put(out)
```
And I also tested the person detection model and change the wifi, It's the same problem.

Manually connect to wifi, also can not connect, when I terminate the program to run, can connect.

Why?🤔

**Comment by alalek** [comment]
Try to run other programs to validate the system under stress.
Check power usage of the system and used power supply. Check input voltage on the power supply / board (not any power cable is able to provide 2-3 A)

If MyriadX is used for inference (probably yes), then try to run the same using the USB Hub with external power supply.

**Comment by stoneWeb** [comment]
I fixed the problem, Because of the conflict between USB 3.0 and wifi2.4G, my Myriad 2 is connected to the USB extension cord, Interference with USB extension cord.
