### ISSUE TITLE
installing fails to locate python3 libraries and numpy path

### ISSUE THREAD

**Issue by wzh4464** [opencv/opencv#19245]
##### System information (version)

- OpenCV => 4.5.0
- Operating System / Platform => macOS Big Sur 11.1(M1 Apple Sillicon)
- Compiler => gcc clang

##### Detailed description

when installing opencv with cmake, build files are written but no python3 libraries path and numpy path.

```
--   Python 3:
--     Interpreter:                 /Users/hancewu/miniforge3/envs/ocv/bin/python3 (ver 3.8.6)
--     Libraries:                   NO
--     numpy:                       NO (Python3 wrappers can not be generated)
--     install path:                -
```

And if I go on to make, it shows
```
Undefined symbols for architecture arm64:
  "_png_do_expand_palette_rgba8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in liblibpng.a(pngrutil.c.o)
  "_png_riffle_palette_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_do_expand_palette_rgb8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_imgcodecs.4.5.0.dylib] Error 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make: *** [all] Error 2

```

##### Steps to reproduce

```
% wget -O opencv.zip https://github.com/opencv/opencv/archive/4.5.0.zip
% wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.0.zip
% unzip opencv.zip
% unzip opencv_contrib.zip
% cd opencv-4.5.0
% mkdir build && cd build

% cmake \                    
  -D CMAKE_SYSTEM_PROCESSOR=arm64 \
  -D CMAKE_OSX_ARCHITECTURES=arm64 \
  -D WITH_OPENJPEG=OFF \
  -D WITH_IPP=OFF \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D OPENCV_EXTRA_MODULES_PATH=/Users/hancewu/tensorflow_macos/arm64/opencv_contrib-4.5.0/modules \
  -D PYTHON3_EXECUTABLE=/Users/hancewu/miniforge3/envs/ocv/bin/python3 \
  -D BUILD_opencv_python2=OFF \
  -D BUILD_opencv_python3=ON \
  -D INSTALL_PYTHON_EXAMPLES=ON \
  -D INSTALL_C_EXAMPLES=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D BUILD_EXAMPLES=ON ..
% make -j8
```

Attachment is full output.
[output_terminal.txt](https://github.com/opencv/opencv/files/5760238/output_terminal.txt)

**Comment by asmorkalov** [comment]
@vpisarev Could you handle the issue as soon as you have hardware in your hands?

**Comment by asmorkalov** [comment]
Related issue: https://github.com/opencv/opencv/issues/19240

**Comment by wzh4464** [comment]
Yes I am installing the opencv as @sayakpaul 's blog.

**Comment by sayakpaul** [comment]
If numpy was installed then the path would have appeared here - 
![image](https://user-images.githubusercontent.com/22957388/103475508-83e6b200-4d62-11eb-8909-fe2ba1d9f55c.png)

Seems like numpy hasn't been installed.

**Comment by wzh4464** [comment]
I've install it.
<img width="639" alt="截屏2021-01-03 下午5 26 23" src="https://user-images.githubusercontent.com/32484940/103475542-e1254680-4de8-11eb-81df-bced4dbfbc66.png">

**Comment by sayakpaul** [comment]
Did you install it using the following way - 

![image](https://user-images.githubusercontent.com/22957388/103476025-1be69a80-4d67-11eb-9b44-26928c358de3.png)

**Comment by wzh4464** [comment]
Just now I am reproducing it and I found something wired.
<img width="619" alt="截屏2021-01-03 下午6 20 33" src="https://user-images.githubusercontent.com/32484940/103476426-606a4880-4df0-11eb-9183-8a39c19b3566.png">
Is it something wrong with the directory? I notice there is a space before " in the erro message.

**Comment by sayakpaul** [comment]
Could you try the following - 

```
cmake \
  -DCMAKE_SYSTEM_PROCESSOR=arm64 \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DWITH_OPENJPEG=OFF \
  -DWITH_IPP=OFF \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D OPENCV_EXTRA_MODULES_PATH=/Users/sayakpaul/Downloads/opencv_contrib-4.5.0/modules \
  -D PYTHON3_EXECUTABLE=/Users/sayakpaul/miniforge3/envs/dev/bin/python3 \
  -D BUILD_opencv_python2=OFF \
  -D BUILD_opencv_python3=ON \
  -D INSTALL_PYTHON_EXAMPLES=ON \
  -D INSTALL_C_EXAMPLES=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D BUILD_EXAMPLES=ON ..
```

**Comment by wzh4464** [comment]
Thank you it can find my numpy now. But the last sentences are now:
<img width="918" alt="截屏2021-01-03 下午6 40 32" src="https://user-images.githubusercontent.com/32484940/103476718-2b132a00-4df3-11eb-828e-b083a7943f66.png">

**Comment by wzh4464** [comment]
Should I output the log files?

**Comment by sayakpaul** [comment]
I would suggest a clean install from the beginning. You might wanna double-check the steps.

**Comment by wzh4464** [comment]
Thank you again. And I made a clean install but there are still some errors.
During the cmake phase, "Custom HAL: NO" is a difference from your screen shot. And the make phase, I got: 
1. clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_hdf.4.5.0.dylib] Error 1
make[1]: *** [modules/hdf/CMakeFiles/opencv_hdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
2. [ 24%] Built target opencv_imgproc
make: *** [all] Error 2
attachment is whole output
[terminal_output_05:01.txt](https://github.com/opencv/opencv/files/5768797/terminal_output_05.01.txt)

**Comment by wzh4464** [comment]
I thought there may be some differences between our opencv files. When I unzip the file "opencv.zip", the file name is opencv-4.5.0, which yours is default by opencv.

**Comment by wzh4464** [comment]
And all CPU SSE support checks are failed.

**Comment by wzh4464** [comment]
And I think this may be important too. (Forgive me for splitting comments)

> ld: warning: ignoring file /usr/local/Cellar/hdf5/1.12.0_1/lib/libhdf5.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/opt/szip/lib/libsz.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

**Comment by sayakpaul** [comment]
> I thought there may be some differences between our opencv files. When I unzip the file "opencv.zip", the file name is opencv-4.5.0, which yours is default by opencv.

Yes, you are night. It should have been `cd opencv-4.5.0`.

But at this point, I am honestly not sure why the build is failing. Seems like you have followed the blog post end-to-end.

**Comment by wzh4464** [comment]
And I found this weired.
In the first lines of cmake phase:
-- Detected processor: x86_64
This shouldn't be like this, right?

**Comment by wzh4464** [comment]
I installed a x86_64 homebrew before, maybe there is some problem.

**Comment by sayakpaul** [comment]
Exactly.

**Comment by wzh4464** [comment]
Thank you bro.

**Comment by insung3511** [comment]
@wzh4464 did you install opencv on virtualenv or just did it. I'm using Big sur (but intel mac) I can't install opencv on virutalenv.

**Comment by wzh4464** [comment]
I have done it successfully. 

> @wzh4464 did you install opencv on virtualenv or just did it? I'm using Big sur (but intel mac) too, but I can't install opencv on virutalenv.

**Comment by josebenitezg** [comment]
Hi @wzh4464 how do you solve your problem?

**Comment by wzh4464** [comment]
I uninstall all my homebrews and keep only the arm homebrew and it runs well.

**Comment by josebenitezg** [comment]
It works! Thank you @wzh4464
