### ISSUE TITLE
Instructions for how to install on new Apple silicon?

### ISSUE THREAD

**Issue by slerman12** [opencv/opencv#19240]
I got a new MacBook and I'm using MiniForge as my Conda distribution, but pip and Conda install both don't seem to work.

**Comment by sayakpaul** [comment]
I wrote a comprehensive blog post that shows how to build and install OpenCV on an M1 MacBook - https://sayak.dev/install-opencv-m1/. Hopefully, it turns out to be useful.

**Comment by RafaelPiloto10** [comment]
@sayakpaul, your blog could not have come at a better time. I am running into a bug though when running `make -j8`: 

```
Undefined symbols for architecture arm64:
  "_png_do_expand_palette_rgba8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in liblibpng.a(pngrutil.c.o)
  "_png_riffle_palette_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
  "_png_do_expand_palette_rgb8_neon", referenced from:
      _png_do_read_transformations in liblibpng.a(pngrtran.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_imgcodecs.4.5.0.dylib] Error 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I am using the M1 MacBook Pro and followed the installation steps on your blog. I installed cmake using `arch -x86_64 brew install cmake`. When running the Cmake command you provided, I do notice that the recognized processor is x86_64 - not sure if that is helpful. I would be more than happy to provide any information that is needed, and I would appreciate any help you can provide.

**Comment by asmorkalov** [comment]
@sayakpaul Feel free to submit PR with additions to existing documentation.

**Comment by isuruf** [comment]
Should be available now on conda `conda install opencv`

**Comment by asmorkalov** [comment]
OpenCV-Python supports Mac M1 and newer since 4.5.3.
