### ISSUE TITLE
ImportError: DLL load failed while importing cv2 

### ISSUE THREAD

**Issue by followertryingtobeprogrammer** [opencv/opencv#19249]
when built opencv4.4.0, folder 'cv2' had been create in python's site-packages.
my env:
cuda 10.2
python 3.8
vs2017
cmake3.19

```
>>>import cv2
ImportError: DLL load failed while importing cv2 
```
then I used dependency walker. it shows that many dll files in API-MS-WIN-CORE lost.

**Comment by LaurentBerger** [comment]
may be same as #17632

**Comment by followertryingtobeprogrammer** [comment]
> may be same as #17632

i use the following commond in conda env.And no error
`>>>python setup.py install
>>>python
>>>import cv2`
