### ISSUE TITLE
Poor performance (low FPS) on jetson tx2 with GPU (CUDA) than CPU.

### ISSUE THREAD

**Issue by smearumi** [opencv/opencv#19251]
##### System information (version)
- OpenCV => 4.5.0
- Operating System / Platform => Linux

##### Detailed description
I'm getting FPS: 10-12 using DNN with CPU. But when I use DNN with CUDA then I'm getting FPS 1-2.

Using DNN with CUDA by following code:

```
NET = cv2.dnn.readNetFromCaffe(
                            "model/ssd/MobileNetSSD.prototxt",
                            "model/ssd/MobileNetSSD.caffemodel")
NET.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
NET.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

```
Also my cmake conf are as follows:

```
PREFIX_MAIN=`pyenv virtualenv-prefix`
PREFIX=`pyenv prefix`

cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D WITH_CUDA=ON \
	-D CUDA_ARCH_PTX="" \
	-D CUDA_ARCH_BIN="5.3,6.2,7.2" \
	-D WITH_CUBLAS=ON \
	-D WITH_LIBV4L=ON \
	-D BUILD_opencv_python3=ON \
	-D BUILD_opencv_python2=OFF \
	-D BUILD_opencv_java=OFF \
	-D WITH_GSTREAMER=ON \
	-D WITH_GTK=ON \
	-D BUILD_TESTS=OFF \
	-D BUILD_PERF_TESTS=OFF \
	-D BUILD_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
        -D CUDA_FAST_MATH=ON \
        -D ENABLE_NEON=ON \
        -D OPENCV_DNN_CUDA=ON \
        -D WITH_CUDNN=ON \
        -D WITH_OPENGL=ON \
        -D CMAKE_INSTALL_PREFIX="$PREFIX" \
        -D PYTHON3_EXECUTABLE="$PREFIX"/bin/python3 \
        -D PYTHON3_PACKAGES_PATH="$PREFIX"/lib/python3.7/site-packages \
        -D PYTHON3_LIBRARY="$PREFIX_MAIN"/lib/libpython3.7m.a \
        -D PYTHON3_INCLUDE_DIR="$PREFIX_MAIN"/include/python3.7m \
	-D OPENCV_EXTRA_MODULES_PATH=/home/jetson-tx2-2/tmp/opencv_contrib/modules ..
```

There were no errors during build and installation.
I don't know what's the reason for such low FPS with CUDA. I've searched for solutions but failed. Please let me know if there is any issue with opencv 4.5.0.

Other necessary info:

`Jetpack: 4.3`

```
NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS FAST_MATH)
    NVIDIA GPU arch:             53 62 72
    NVIDIA PTX archs:

cuDNN:                         YES (ver 7.6.3)
```

**Comment by alalek** [comment]
Please run OpenCV performance tests and provide numbers from the test suite.
Run other CUDA-capable frameworks and collect numbers from there too.

---

> CUDA_ARCH_BIN="5.3,6.2,7.2"

No sense to do than for single embedded platform. Use `6.2` for TX2 platform: https://en.wikipedia.org/wiki/CUDA

**Comment by YashasSamaga** [comment]
MobileNetSSD uses depthwise convolutions. cuDNN 7 does not choose the algorithms correctly for depthwise/grouped convolutions. This leads to suboptimal performance.

Please try different variants of MobileNet and targets (`DNN_TARGET_CUDA` and `DNN_TARGET_CUDA_FP16`). There usually is some combination that will perform well.

**Comment by YashasSamaga** [comment]
cuDNN 8 has resolved the depthwise convolution performance problem. Can you please check if the performance degradation still exists?
