### ISSUE TITLE
Load TensorFlow 2 model (SSD, Object Detection API) with OpenCV

### ISSUE THREAD

**Issue by golden96371** [opencv/opencv#19257]
##### System information (version)
- OpenCV => 4.5.1 (python)
- TensorFlow => 2.3.1 (python)
- Operating System / Platform => Windows 10 (64 Bit)
- Compiler => Visual Studio 2019

##### Detailed description

After training a SSD MobileNet v2 using the TensorFlow Object Detection API with TensorFlow2, I converted the SavedModel into a FrozenGraph in order to make it compatible with OpenCV. I am using following code to load the model:

``` python
import numpy as np
import cv2 as cv
net = cv.dnn.readNet('frozen_graph.pb') 
```

This gives following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:578: error: (-2:Unspecified error) More than one input is Const op in function 'cv::dnn::dnn4_v20201117::`anonymous-namespace'::TFImporter::getConstBlob'
```

The script `opencv/tf_text_graph_ssd.py` runs into an assertion:
```
Traceback (most recent call last):
  File "tf_text_graph_ssd_original.py", line 405, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd_original.py", line 292, in createSSDGraph
    assert(num_matched_layers == num_layers)
AssertionError
```

After fixing the assertion by adapting the layer names in the script, the text graph could be created. After loading the model with
``` python
net = cv.dnn.readNet('frozen_graph.pb', 'graph.pbtxt') 
```
there is a different error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\dnn\src\tensorflow\tf_graph_simplifier.cpp:1019: error: (-215:Assertion failed) permIds.size() == net.node_size() in function 'cv::dnn::dnn4_v20201117::sortByExecutionOrder'
```

I attach my frozen_graph.pb and my pipeline.config.
[model.zip](https://github.com/opencv/opencv/files/5765665/model.zip)

##### Steps to reproduce

1.) Train a SSD MobileNet v2 using the [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) and export it to a SavedModel
```
# Train the network
python model_main_tf2.py --model_dir="training" --pipeline_config_path="training/pipeline.config"
# Export the network
python exporter_main_v2.py --input_type=image_tensor --pipeline_config_path="training/pipeline.config" --trained_checkpoint_dir="training" --output_directory="training/model"
```

2.) Convert the SavedModel to a FrozenGraph
``` python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('training/model/saved_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(input_tensor=tf.TensorSpec(shape=[1, None, None, 3], dtype=tf.uint8))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
```

3.) Try to load the FrozenGraph with OpenCV as described above: failed

Anyone can reproduce the issue and help me to fix it?

**Comment by LupusSanctus** [comment]
I reproduced the steps you've described. However, one more step was added - optimization of the obtained frozen graph:
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=<FROZEN_MODEL_PATH>/ssd_mobilenet_frozen.pb --out_graph=<PATH_TO_SAVE_OPT_MODEL>/optimized_frozen_graph.pb --inputs="x" --outputs="Identity,Identity_1,Identity_2,Identity_3,Identity_4,Identity_5,Identity_6,Identity_7" --transforms='remove_nodes(op=Identity) strip_unused_nodes fold_constants(ignore_errors=true) fold_batch_norms fold_old_batch_norms'
```

After this step and `.pbtxt` assertation error WA, I've tried to read it with OpenCV:
`cvNet = cv.dnn.readNetFromTensorflow('<PATH_TO_SAVE_OPT_MODEL>/optimized_frozen_graph.pb', 'graph.pbtxt')`

and the below error has occurred:
`tf_importer.cpp:596: error: (-2:Unspecified error) Input layer not found: BoxPredictor_5/BoxEncodingPredictor/BiasAdd in function 'connect'`

I've examined the initial  `ssd_mobilenet_frozen.pb`, `optimized_frozen_graph.pb` nodes and compared with already tested OpenCV [`MobileNet-SSD v2`](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#use-existing-config-file-for-your-model) model [nodes](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v2_coco_2018_03_29.pbtxt). It seems that TF model structure is corrupted, it doesn't contain the below block of nodes:
`BoxPredictor_*/BoxEncodingPredictor/Conv2D`

I've also tested another version of `model_main` for TF<2.0 (TF1.5):
`python object_detection/model_main.py --model_dir="<YOUR_DIR_PATH>/training" --pipeline_config_path="<YOUR_PATH_TO_CONFIG>/pipeline.config"`

For running the above line we need to correct `pipeline.config`:
```
    feature_extractor {
      type: "ssd_mobilenet_v2"
```

Now in `<YOUR_DIR_PATH>/training` directory we can find `graph.pbtxt`. It contains `BoxPredictor_*/BoxEncodingPredictor/Conv2D` block.

After successful `model_main.py` execution we need to export the inference graph running the following script:
```
import os
import re
import numpy as np

model_dir = '<YOUR_DIR_PATH>/training'
# create the dir for model export
output_directory = '<YOUR_DIR_PATH>/training/exported_model'

lst = os.listdir(model_dir)
lst = [l for l in lst if 'model.ckpt-' in l and '.meta' in l]
steps = np.array([int(re.findall('\d+', l)[0]) for l in lst])
last_model = lst[steps.argmax()].replace('.meta', '')
pipeline_fname = '<YOUR_PATH_TO_CONFIG>/pipeline.config'
last_model_path = os.path.join(model_dir, last_model)

cmd = "python export_inference_graph.py --input_type=image_tensor --pipeline_config_path={} --output_directory={} --trained_checkpoint_prefix={}".format(
    pipeline_fname, output_directory, last_model_path)

os.system(cmd)
```
Note: good tutorial for TF detection model training and export:
https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_Object_Detection_With_Custom_Data_Demo_Training.ipynb#scrollTo=dIhw7IdpLuiU

As a result, `frozen_inference_graph.pb` will be generated in `<YOUR_DIR_PATH>/training/exported_model`. Its text graph generation with initial `tf_text_graph_ssd.py ` version works as expected. 
Now we can try once more to feed the `.pb` and `.pbtxt` into `cv.dnn.readNetFromTensorflow(...)`. And we will get the below error:
`tf_importer.cpp:596: error: (-2:Unspecified error) Input layer not found: FeatureExtractor/MobilenetV2/Conv/weights in function 'connect'`

To solve this issue, add `input: "image_tensor"` to ` "FeatureExtractor/MobilenetV2/Conv/Conv2D"` node in your text graph:
```
node {
  name: "FeatureExtractor/MobilenetV2/Conv/Conv2D"
  op: "Conv2D"
  input: "image_tensor"
  input: "FeatureExtractor/MobilenetV2/Conv/weights"
...
```
Now you can successfully load your model with OpenCV `cv.dnn.readNetFromTensorflow(...)`.

**Comment by golden96371** [comment]
Thank you for examining the issue. It works for me with the old `model_main.py`.

But do I understand correctly that you could not load a model trained with TF 2 via OpenCV either, due to the issue with the missing nodes?

**Comment by LupusSanctus** [comment]
The core of TF2 model problem is its graph, which we get after export with ``exporter_main_v2``, it`s not about OpenCV node processing in ``tf_text_graph_ssd.py``.  When we freeze an obtained with ``exporter_main_v2`` model, we get a ``.pb`` file, which contains lots of nodes in the following format:
```
StatefulPartitionedCall/StatefulPartitionedCall/.../ReadVariableOp
```

For example:
```
StatefulPartitionedCall/StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/BiasAdd/ReadVariableOp
StatefulPartitionedCall/StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/Conv2D/ReadVariableOp
```

However, [OpenCV doesn't import models with StatefulPartitionedCall](https://github.com/opencv/opencv/issues/16582#issuecomment-720395445) (it's called TF Eager mode).

**Comment by golden96371** [comment]
All right, thank you for the information. I will check if I can get the model converted to ONNX and then load it with OpenCV.

Feel free to open this issue again if OpenCV plans to support TF Eager mode in future :)

**Comment by JJonahJson** [comment]
> The core of TF2 model problem is its graph, which we get after export with `exporter_main_v2`, it's not about OpenCV node processing in `tf_text_graph_ssd.py`. When we freeze an obtained with TF `exporter_main_v2` tool model, we get a `.pb` file, which contains lots of nodes in the following format:
> 
> ```
> StatefulPartitionedCall/StatefulPartitionedCall/.../ReadVariableOp
> ```
> 
> For example:
> 
> ```
> StatefulPartitionedCall/StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/BiasAdd/ReadVariableOp
> StatefulPartitionedCall/StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/Conv2D/ReadVariableOp
> ```
> 
> However, [OpenCV doesn't import models with StatefulPartitionedCall](https://github.com/opencv/opencv/issues/16582#issuecomment-720395445) (it's called TF Eager mode).
> Probably, there is a possible way out for such TF2 models - convert them into ONNX (`tf2onnx`) and after that feed it into OpenCV.


Thanks for the example you showed from start to finish, you summarized the work I did until I got stuck for the reason you explained, but I didn't know it was due to eager mode of TF2!

Do you think maybe training in TF2 with model_main_tf2.py might work if I modify the script using: `tf.compat.v1.disable_eager_execution ()`?

I trained a Mask R-CNN Inception Resnet V2 model and already tried to convert it to ONNX, but it doesn't work with readNeatFromONNX , you can find the issue I opened in opencv here: [https://github.com/opencv/opencv/issues/19366](url)

**Comment by golden96371** [comment]
The conversion to ONNX succeeds with opset 11 or higher (`tf2onnx==1.8.2`)
``` python -m tf2onnx.convert --saved-model "training/model/saved_model'" --output "model.onnx" --opset 11 ```

However, loading the model with OpenCV gives an error message.
``` python
import cv2 as cv
net = cv.dnn.readNet('model.onnx')
```

```
[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1878) cv::dnn::dnn4_v20201117::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Conv]:(StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/bn_Conv1/FusedBatchNormV3:0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1887: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20201117::ONNXImporter::handleNode'
> Node [Conv]:(StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/bn_Conv1/FusedBatchNormV3:0) parse error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\dnn\src\layers\convolution_layer.cpp:96: error: (-213:The function/feature is not implemented) Unsupported asymmetric padding in convolution layer in function 'cv::dnn::BaseConvolutionLayerImpl::BaseConvolutionLayerImpl'
```

**Comment by bradqiu1982** [comment]
So appreciate for LupusSanctus' comment, I followed his solution and sucessfully make tensorflow object detect model works in opencv.
I hope my comment can help the guys who still struggle with the tensoflow object detect model on windows platform.

Follow  LupusSanctus' comment, you will not meet any problem until you try to export the checkpoint to frozen model.

when you try to export checkpoint to frozen model on windows by export_inference_graph.py ,you will meet following problems:
1, access deny , this is caused by the file path style , you need to change \ to /
2, the program failed to load checkpoint, you need to modify the checkpoint name
for example , your checkpoint in folder  mbv2model . you need to modify your checkpoint to following names :  model.ckpt.data-00000-of-00001   model.ckpt.index model.ckpt.meta   and then give it as input  like this:   --trained_checkpoint_prefix=./mbv2model/model.ckpt

after the model export, you can continue follow LupusSanctus' comment

If above comment can save your time, I will be so glad

**Comment by bradqiu1982** [comment]
Warning , don't try to use TF1.X object detect in OPENCV on window platform. It waster your life. I have spend two weeks on it.     Now, I go back TF2.X object detect, at least it can detect objects in image correctly. Now, I will try to make TF2.X object detect can be used with OPENCV. PLAN A , convert to onnx and try. PLAN B, use Tensorflow.net

**Comment by bradqiu1982** [comment]
PLAN A failed:   I can convert savedmodel to onnx sucessfully, but failed to load it into OPENCV 4.5.2

opencv_net = cv2.cv2.dnn.readNetFromONNX('./tfrec/fast_onnx/faster_rcnn.onnx')
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2129: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20210301::ONNXImporter::handleNode'
> Node [Less]:(__inference_map_while_cond_11554_2945_map/while/Less:0) parse error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\dnn\src\dnn.cpp:621: error: (-2:Unspecified error) Can't create layer "__inference_map_while_cond_11554_2945_map/while/Less:0" of type "Less" in function 'cv::dnn::dnn4_v20210301::LayerData::getLayerInstance'

**Comment by bradqiu1982** [comment]
PLAN B still failed.  Tensorflow.net even doesn't support saved model at current time. Warning, Tensorflow.net will force you to update to VS2019, even it doesn't work. Don't try PLAN B , it waste your time.

**Comment by bradqiu1982** [comment]
A walk-around to use Tensorflow object detect model in C#.

First , using flask and waitress to build a python web service which can load and run tensorflow object detect model:
"

import json
from flask import *

cache = dict()

app = Flask(__name__)
def getOBJDectModel(imgtype):
	if imgtype not in cache:
		model = tf.saved_model.load('./tfrec/ObjectDetectModel/'+imgtype+'/saved_model')
		cache[imgtype] = model
		return model
	else:
		return cache[imgtype]


@app.route("/OBJDetect", methods=["POST"])
def OBJDetect():
       ........................
if __name__ == "__main__":
	from waitress import serve
	serve(app, host="0.0.0.0", port=5000)

"

Then call the python web service by http protocol from C#.
By this walk-around , we can use the tensorflow object detect AI service from C#

"// C# CODE

//url is http://localhost:5000/OBJDetect
 private string PythonRESTFun(string url,string reqstr)
        {
            string webResponse = string.Empty;
            try
            {
                Uri uri = new Uri(url);
                WebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(uri);
                httpWebRequest.ContentType = "application/json";
                httpWebRequest.Method = "POST";
                using (StreamWriter streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
                {
                    streamWriter.Write(reqstr);
                }
                HttpWebResponse httpWebResponse = (HttpWebResponse)httpWebRequest.GetResponse();
                if (httpWebResponse.StatusCode == HttpStatusCode.OK)
                {
                    using (StreamReader streamReader = new StreamReader(httpWebResponse.GetResponseStream()))
                    {
                        webResponse = streamReader.ReadToEnd();
                    }
                }
            }
            catch (Exception ex)
            {
            }

            return webResponse;
        }

"

Hope above code can save your time.
