### ISSUE TITLE
Support AVIF for image reading and writing

### ISSUE THREAD

**Issue by Glandos** [opencv/opencv#19271]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => all
- Compiler => all

##### Detailed description

[AVIF](https://aomediacodec.github.io/av1-avif/) is based on AV1 intraframe compression algorithm with [HEIF](https://nokiatech.github.io/heif/) container.

AVIF decoding is supported by both [Chrome and Firefox](https://caniuse.com/avif) (behind a flag for now).

The main issue is that there are multiple libraries out there:
- https://github.com/AOMediaCodec/libavif is the main implementation. The `avenc` utility can only use `libaom` as far as I know.
- https://github.com/xiph/rav1e. Encoding only. It's not obvious if AVIF is really supported.
- https://code.videolan.org/videolan/dav1d/. Decoding only. Used by Firefox. Fastest decoding library available.
- https://github.com/AOMediaCodec/SVT-AV1/. Fastest encoder available. Not usable for now (see https://github.com/AOMediaCodec/SVT-AV1/issues/1433 and https://github.com/AOMediaCodec/SVT-AV1/issues/12).

**Comment by asmorkalov** [comment]
Related issue: https://github.com/opencv/opencv/issues/11389

**Comment by vrabaud** [comment]
Hi, there are actually two main libraries to decode/encode AVIF files: https://github.com/AOMediaCodec/libavif and https://github.com/strukturag/libheif.

Both wrap one or more AV1 codec libraries that have been mentioned before. Adding a dependency on libavif or libheif also means we need to add an AV1 dependency.

I see two solutions to move forward:
- implement the support through libavif or libheif. PROS: easy to do as they are image libraries, several AV1 libraries can be used depending on the needs. CONS: they add two 3rd party dependencies
- implement the support through FFMPEG. PROS: it does not add any dependency when videoio uses FFMPEG, it already works for reading. CONS: the FFMPEG API is not easy

Both could also be implemented. Is there a clear no for one of them? If not, I'll go first with libavif as this is the one I know best: can we have code depend on 3rd party even though this code is not part of the official OpenCV 3rdparty folder?

BTW, here is a code snippet that shows VideoCapture already working with AVIF (but not VideoWriter)
```
#include "opencv2/imgcodecs.hpp"
#include "opencv2/videoio.hpp"

int main(int, char**argv){
  cv::VideoCapture cap("/tmp/image.avif");
  cv::Mat out;
  std::cout << (int)cap.read(out) << std::endl;
  cv::imwrite("/tmp/image.png", out);
  std::cout << "done writing PNG" <<std::endl;
  cv::VideoWriter writer("/tmp/image2.avif",0,0,out.size());
  std::cout << (int)writer.isOpened() <<std::endl;
  // writer.write(out);
}
```
