### ISSUE TITLE
[Feature Request] - CPU, GPU; Selection  (RunTime)

### ISSUE THREAD

**Issue by HotDenim** [opencv/opencv#19274]
Like to request a _mechanism_ to allow deciding at _runtime_ weather the default _CPU_ code is executed or the _GPU_ optimised version.

E.g.  deciding at runtime which of the two to execute

```
cv::cuda::bilateralFilter()

cv::bilateralFilter()
```

Also for the GPU code, allowing which GPU _type_ to use, e.g. _CUDA_ or _OPENCL_.

So allowing the following to take place in program logic. Pseudocode:

```
// Execute GPU version if possible
// Else fallback to CPU version
//
if (GPU_Present == True)                    // If a Compatible GPU is present, use GPU version
{
    if GPU_Present_CUDA == True)            // If a Compatible CUDA GPU is present, use CUDA version
    {
        CV::CUDA::someFunction();
    }
    else if (GPU_Present_OPENCL == True)      // If a Compatible OPENCL GPU is present, use OPENCL version
    {
        CV::OPENCL::someFunction();
    }
}
else                                        // Fall back to CPU version
{
        someFunction();
}
```

**Comment by alalek** [comment]
> cv::cuda::bilateralFilter

It is a legacy approach.

Modern OpenCV way is [Transparent API](https://github.com/opencv/opencv/wiki/Opencv3) (T-API). However it serves OpenCL optimizations only at this moment. You need to use `UMat` to activate this behavior.
