### ISSUE TITLE
[Feature Request] - GPU To CPU Fallback (RunTime)

### ISSUE THREAD

**Issue by HotDenim** [opencv/opencv#19275]
Like to request a mechanism to allow using the GPU optimised version of functions as a _default_, and if _not_ possible, only then falling back to CPU version (_automatically_). (Could also cater for _TPU's (Tensor Processing Units)_ and _VPU (_computer_ Vision Processing Units_) in the future)

E.g. A new _module / namespace_

`cv::hardware_optimised`

So as an example:

`cv::hardware_optimised::bilateralFilter()`

**Comment by alalek** [comment]
Also you can take a look on [Graph API](https://docs.opencv.org/master/d0/d1e/gapi.html) (`gapi` module).
It introduces concept of kernel packages to handle that.

**Comment by diablodale** [comment]
@HotDenim hi. I think this issue and its sibling https://github.com/opencv/opencv/issues/19274 are both met with OpenCV `UMat` and OpenCL infrastructure.

You can at runtime, enable or disable the use of OpenCL compute devices. Major vendors like Intel, AMD, and Nvidia all support OpenCL with their graphic driver/runtimes. Therefore, you can write a single codebase in C++ with OpenCV and at runtime chose to use CPU or an OpenCL compute device with APIs like `cv::ocl::setUseOpenCL(true)`

Functions like `cv::bilateralFilter()` already support this OpenCL compute device optimization. You can see this at https://github.com/opencv/opencv/blob/fc1a15626226609babd128e043cf7c4e32f567ca/modules/imgproc/src/bilateral_filter.dispatch.cpp#L413 where OpenCV uses the OpenCL codepath if OpenCL is enabled. And if it is not, then it uses fallback implementations like Intel Performance Primitives (if it is installed/build into OpenCV) or opencv cpu implementations. In the future, it is possible OpenCV would add other "dispatched" optimizations. But that doesn't change your C++ code. You only have to enable OpenCL with `setUseOpenCL()`, use `UMat`, and call `cv::bilateralFilter()`.

All of this is good news. And you can use it today. :-)
