### ISSUE TITLE
I found an error code in opencv/samples/python/video.py 

### ISSUE THREAD

**Issue by bulingda** [opencv/opencv#19288]
![image](https://user-images.githubusercontent.com/55130106/103991545-c7f80d80-51cd-11eb-97e5-79763c3cdd5b.png)

**Comment by asmorkalov** [comment]
@bulingda Thanks for the finding. OpenCV is Open Source library. Feel free to submit PR with the issue fix.

**Comment by alalek** [comment]
Existed code is valid and works as expected.
You should take a look on `presets` dictionary values above.
