### ISSUE TITLE
[Q] license of files in 3rdparty repo

### ISSUE THREAD

**Issue by thmo** [opencv/opencv#19290]
In order to be able to [include](https://gitlab.gnome.org/GNOME/shotwell/-/issues/318) the model in Shotwell, we'd like to know the license of the files here: https://github.com/opencv/opencv_3rdparty/tree/dnn_samples_face_detector_20180205_fp16.

I wasn't able to locate some license information nearby in that repo, and a quick chat on #opencv suggested to open a ticket here to ask for clarification.

**Comment by alalek** [comment]
Check info from here: #9516

---

Don't rely on any answers from Internet about legal topics. Contact with your lawyer instead.

**Comment by phako** [comment]
Asking a lawyer would be the second step after knowing the license... But this is the first step: Getting to know your license. That PR has no license info. But I assume that tag means we should re-open the question in forum.opencv.org?

**Comment by thmo** [comment]
Why did you close this issue? The requested information hasn't been provided, or do I miss something?

**Comment by arrybn** [comment]
Hi, guys. Sorry for late response.
Regarding the licence for the model. I personally trained this model using WIDER dataset. So, some limitations of use come from this fact. Other than that, nothing special

**Comment by phako** [comment]
Thank you
