### ISSUE TITLE
[Feature Request] - Animated Overlay

### ISSUE THREAD

**Issue by HotDenim** [opencv/opencv#19306]
Would like to request a feature that allows the over overlay of a _'animated'_ file _(e.g. Video File, Animated GIF, Multi-Image TIFF, Windows .ANI (animated Icon), Windows .ICO (Icon)_) over an image (current frame). An Example use

- Producing video output with an _animated_ logo in the corner.
- Producing an _animated_ annotation that can be placed in the video output, wherever required.

Should support transparency (alpha channel / multiple levels of transparency) from and fall back to coping with single image source files.

Should also support:

- Overall transparency level of its _own_
- Colour blend modes
- Fade In/Fade Out; per repetition, per overall repetition
- Repeat, non-repeat, repeat a number of times, repeat for a duration
- Speed
- Maybe also; scaling, rotation, translation etc

**Comment by alalek** [comment]
OpenCV is a computer vision library.
It is not a GUI framework.

**Comment by berak** [comment]
@HotDemin, can you explain, how this would improve a *computer-vision* library ?

**Comment by HotDenim** [comment]
Well I am suggesting it from, for example, the exising drawing functions Circle(), Rectangle(), Line() etc...  

Imagine detecting something, and placing an animated marker by it, for example a _glowing arrow_ pointing to something. (Glowing arrow being say an Animated GIF file)
