### ISSUE TITLE
window_w32.cpp: remove "gutter"

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#19308]
I would like to remove the 1-pixel "gutter" that sits between the displayed image and the window's border in win32 `imshow`. the function `icvCalcWindowRect` could either get its gutter constant set to 0 or the entire calculation could be simplified (my preference).

https://github.com/opencv/opencv/blob/941a9792f7c7d60640c82926091d710e6ecbfb55/modules/highgui/src/window_w32.cpp#L1119-L1142

reason: when you send the window into fullscreen, you'd expect the image area to be the precise resolution of your screen, right? with that gutter, it's not. it's smaller by two pixels (window decoration disappears, the gutter stays). a precisely screen-sized image shown will be *slightly* off, which either causes rows and columns of the picture to disappear (GDI: nearest neighbor) or the whole picture gets resampled and turned into mush (OpenGL: bilinear). the gutter also has no function that I can see.

```
import numpy as np
import cv2 as cv
im = np.eye(200)
cv.imshow("gutter?", im)
cv.waitKey(-1)
```

observe the gray gutter:
![close up](https://user-images.githubusercontent.com/7065108/104205398-a0ec4680-542e-11eb-8575-457ff61d3983.png)

my question: would you like the pull request to be against 3.4 or master? I ask because last time I had a pull request against the wrong branch, having to rebase overwhelmed me and I'd like to avoid repeated embarrassment.

**Comment by asmorkalov** [comment]
@vpisarev could you comment the solution?

**Comment by crackwitz** [comment]
here's a little something you can run that demonstrates the issue:
https://gist.github.com/crackwitz/413bbb458b88772f5912d8af978b0b53
use args `--size 2560x1440 --gutter 1` to see a clean pattern with the current situation (size is reduced appropriately for given gutter),
or `--size 2560x1440 --gutter 0` to see what happens when you want to display a picture that's actually that size.

**Comment by crackwitz** [comment]
if desired, I could extend that code to center the displayed image in the window, and also implement WINDOW_KEEPRATIO for this backend.

**Comment by vpisarev** [comment]
have no objections to accept the patch

**Comment by asmorkalov** [comment]
The gutter exists even in opencv_attic repository and looks like some hack for old Windows versions support. The core team discussed the issue and decided that we do not need it any more. Feel free to propose patch that removes extra border.

**Comment by crackwitz** [comment]
I'll get it done tonight. would you prefer pull request against master or other branch?

**Comment by alalek** [comment]
Please target PR to 3.4 branch

**Comment by crackwitz** [comment]
I am considering looking into making WINDOW_KEEPRATIO work for win32 and accompanying OpenGL mode. that will likely involve changes in several functions. I'll work on that and make a separate pull request for that.

I have told cmake to BUILD_TESTS but the generated VS solution's `opencv_tests` project looks empty and the `RUN_TESTS` target doesn't do anything either. just says `1>No tests were found!!!`
