### ISSUE TITLE
OpenCV 4.5.1 build fails on Python2 / 3 

### ISSUE THREAD

**Issue by VisionaryMind** [opencv/opencv#19333]
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => Linux 4.9.140-tegra aarch64
- Compiler => c++  (ver 7.5.0)

##### Detailed description

I have been able to build 4.5.1 successfully in the past on a Tegra machine. This one is a Xavier AGX with Jetpack 4.4.1, so right out of the gate, there are all the inconsistencies and oversights common to NVIDIA-built systems. All of that chaos aside, I have seeing an error that originally was resolvable by making minor changes to Python header files for Numpy. Specifically:

`In file included from /usr/include/sched.h:29:0,
                 from /usr/include/pthread.h:23,
                 from /usr/include/aarch64-linux-gnu/c++/7/bits/gthr-default.h:35,
                 from /usr/include/aarch64-linux-gnu/c++/7/bits/gthr.h:148,
                 from /usr/include/c++/7/ext/atomicity.h:35,
                 from /usr/include/c++/7/bits/basic_string.h:39,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/cvdef.h:738,
                 from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/cvstd.hpp:51,
                 from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/utils/configuration.private.hpp:8,
                 from /home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:35:
/home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp: In function ‘void initcv2()’:
/home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:2137:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
     import_array(); // from numpy
     ^
/home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:2137:5: error: expected ‘;’ before ‘__null’
     import_array(); // from numpy
`

I attempted to fix this first by adding a NULL after the Numpy array return value definition in  /usr/include/python2.7/numpy/__multiarray_api.h:

`#if PY_VERSION_HEX >= 0x03000000
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#else
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#endif`

In the past, this has fixed the problem. I also laboriously pushed through 2 compilations, one with BUILD_SHARED_LIBS on and off. Attempting to change the cv2.cpp to return Null if no value is found on init (as in Python3) does not work either. I can only presume this problem appeared as a result of other libraries I have installed that require a newer version of Numpy than is installed by default on Jetpack. Unfortunately, I cannot remove Jetpack's Numpy, because nearly everything depends on it (in particular, ROS Melodic).

I know intuitively I shouldn't be wasting time with NVIDIA hardware given their lack of attention to platform stability, but I was hoping that somehow, I would be the exception to the rule and the the AGX would live up to its specs, for once. After 2 weeks of running into issues like these, skepticism only grows.

Hopefully, someone has an idea how to get Python bindings compiled for 4.5.1 on this platform, as I need them for my primary project, and as you may be aware, this platform's repo pulls v3.2.

**Comment by alalek** [comment]
Perhaps numpy version in your environment doesn't support Python 2.7 anymore.
You should disable generation of opencv_python2 binding in that case: `cmake -DBUILD_opencv_python2=OFF ...`

**Comment by VisionaryMind** [comment]
> Perhaps numpy version in your environment doesn't support Python 2.7 anymore.
> You should disable generation of opencv_python2 binding in that case: `cmake -DBUILD_opencv_python2=OFF ...`

Yes, this fixes the problem, but some libraries require Python 2. ROS Melodic, for example, which is the default on these Tegra machines.

**Comment by alalek** [comment]
> /usr/include/python2.7/numpy
> #if PY_VERSION_HEX >= 0x03000000

This doesn't looks like a right way.
Python2.7 directory should not be used to compile with Python3+.

You should check passed build parameters and CMake variables first.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by VisionaryMind** [comment]
> This doesn't looks like a right way.
> Python2.7 directory should not be used to compile with Python3+.
> 
> You should check passed build parameters and CMake variables first.

Everything is in order The problem is that OpenCV is no longer compatible with Python 2.7. I presume most of the developers have switched to Python3, but those of us that use NVIDIA edge devices (e.g. Xavier AGX), we are stuck with Ubuntu 18.04 and the old Jetpack libraries. ROS Melodic depends on Python2 and though it may be compiled from source to support Python3, that will break many of the projects built on Melodic.

That being said, it would be helpful to know for which version of Python2 Numpy OpenCV 4.5.1 has been built. I can get this working by completely deleted the CMake cache, downgrading to Numpy 1.13, and then re-building, but that is time-consuming, and I'd prefer to know how to fix the OpenCV code so that it supports Python2. The Numpy multiarray header that you reference has the same section for "#if PY_VERSION_HEX >= 0x03000000" in both Python2.6 and Python 3.

Here is the section:

`#if PY_VERSION_HEX >= 0x03000000
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#else
#define NUMPY_IMPORT_ARRAY_RETVAL
#endif

#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }

#define import_array1(ret) {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return ret; } }

#define import_array2(msg, ret) {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, msg); return ret; } }

#endif

#endif`

**Comment by alalek** [comment]
Got it. `#if` is not really necessary here.

Looks like this problem is that used numpy is not compatible with Python 2.7.

Python 2.7 support was "broken" by this numpy [commit](https://github.com/numpy/numpy/commit/e1aecb08f99321b72959cc50eb7b47454b613f52#diff-5884bb7c90e5a93ce8f0f32b884410d3adabad9df1bf89b049be522a7f34d574L129) (1.19+).
So, numpy 1.19+ should not be used with Python 2.7 (and should not be installed in this environment without extra modifications).

BTW, You can try to downgrade numpy for build stage through `virtualenv`.

---

We can't fix numpy for Python 2.7 from OpenCV side.
