### ISSUE TITLE
how to link openvino libraries when running Java with opencv?

### ISSUE THREAD

**Issue by wureka** [opencv/opencv#19362]
- OpenCV => 4.5.1
- OpenVINO => 2021.2
- OS => Windows 10 Pro

First, I built opencv and tested with my java program:

`java -Djava.library.path="D:\OpenSource\opencv-4.5.1-cuda\java;D:\OpenSource\opencv-4.5.1-cuda\x64\vc16\bin" -jar myjar.jar`

It works. So it means my `java.library.path` is configed correct and my java program could found `opencv_java451.dll` and other relevant opencv dll files.

Then, I installed OpenVINO 2021.2 which was downloaded from intel website. I am sure that OpenVINO 2021.2 is installed successfully because I followed the relevant instructions and got the same result.

For linking with openVINO, I added below flags in cmake and rebuild opencv.
```
-DWITH_INF_ENGINE=ON 
-DENABLE_CXX11=ON 
-DINF_ENGINE_LIB_DIRS=D:/intel/openvino_2021.2.185/deployment_tools/inference_engine/lib/intel64/Release
-DINF_ENGINE_INCLUDE_DIRS=D:/intel/openvino_2021.2.185/deployment_tools/inference_engine/include
-DINF_ENGINE_RELEASE=2021020000
-DINF_ENGINE_VERSION=2.1.0
-DWITH_NGRAPH=ON
-Dngraph_DIR=D:/intel/openvino_2021.2.185/deployment_tools/ngraph/cmake
-DinferenceEngine_DIR=D:/intel/openvino_2021.2.185/deployment_tools/inference_engine/share
```

All things were built successfully. And I added below path to system environment varialbe `PATH`:

```
D:\intel\openvino_2021.2.185\deployment_tools\ngraph\lib
D:\intel\openvino_2021.2.185\deployment_tools\inference_engine\external\tbb\bin
D:\intel\openvino_2021.2.185\deployment_tools\inference_engine\bin\intel64\Release
```

I reopened a new CMD console, executed `D:/intel/openvino_2021.2.185/bin/setupvars.bat` and in the same CMD console I started my Java program again.

java -Djava.library.path="D:\OpenSource\opencv-4.5.1-cuda\java;D:\OpenSource\opencv-4.5.1-cuda\x64\vc16\bin;D:\intel\openvino_2021.2.185\deployment_tools\ngraph\lib;D:\intel\openvino_2021.2.185\deployment_tools\inference_engine\external\tbb\bin;D:\intel\openvino_2021.2.185\deployment_tools\inference_engine\bin\intel64\Release" -jar myjar.jar

It appeared below errors:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\OpenSource\opencv-4.5.1-cuda\java\opencv_java451.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at GMain.loadOpencvLibraries(GMain.java:12)
	at GMain.main(GMain.java:18)

```
It seems that java wants to find some DLL files from openVINO which I am not aware. but I don't know what paths I should add.

Could anyone provide suggestions?

Many thanks

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64/builds/583) (`test_java` step works).

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

- consider dumping of `PATH` environment variable from Java application directly (`System.getenv()`)
- you may want to use `procmon` utility to investigate what and from where are loading. Use filters (negative) for better experience.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by wureka** [comment]
Eventually, I solved this issue. 
The problem is that I use cygwin in Windows 10 Pro. And this is the key.
In cygwin console, for the system environmant variable `PATH`, it is in the format of U*ix, and if I need to access some folder, I should use this format `/cygdrive/d/OpenSource/opencv-4.5.1-cuda/x64/vc16/bin`. But in Java's defined VM varialbe, which should be used in Windows format like 'D:/OpenSource/opencv-4.5.1-cuda/java'.
At begining, I didn't realize this defference, so Java always appeared the above problem.

Thank you, anyway.
