### ISSUE TITLE
Idea: converting GREY images to GREYALPHA images

### ISSUE THREAD

**Issue by kolibril13** [opencv/opencv#19377]
Hello everyone,
currently, I am working with grey-scale images, and I thought it would be a nice idea to have an opportunity to convert Grayscale images into Grayscale+Alpha images.
I had a look here: [OpenCV: Color Space Conversions](https://docs.opencv.org/3.4/d8/d01/group__imgproc__color__conversions.html)
but I could only find GRAY2RGB , GRAY2BGRA and RGB2RGBA. So I think a conversion GRAY2GRAYA is missing in this place. To show that this is something useful: The png format has support for these Grayscale+Alpha images: [PNG Basics](http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.5)

And here is an example python script, where reducing these 4 channels to only 2 channels would make a benefit:
```py
from matplotlib import pyplot as plt
import numpy as np
```
```py
from skimage import data
import cv2

camera = data.camera()
print(camera.shape)
camera = cv2.cvtColor(camera, cv2.COLOR_RGB2RGBA)
plt.imshow(camera, interpolation='nearest', cmap='gray');
(512, 512)
```
```py
camera.shape
(512, 512, 4)
```

```py
pad= np.full((int(camera.shape[0]/4), camera.shape[1]) ,0)
new_pad = cv2.cvtColor(np.uint8(pad), cv2.COLOR_GRAY2BGRA)
new_pad[:,:,3]=0 # setting alpha channle to zero
camera_new=np.concatenate((new_pad, camera ,new_pad) ,axis=0)
plt.imshow(camera_new, interpolation='nearest', cmap='gray');
````
![image](https://user-images.githubusercontent.com/44469195/105540757-04138e00-5cf7-11eb-99dc-d46cc5cfc374.png)

**Comment by alalek** [comment]
There is no alpha channel from camera streams.
So computer vision algorithms don't work with that.

For images processing consider using other Media SDKs. OpenCV is about the "computer vision" first.

**Comment by kolibril13** [comment]
Okay, thanks for your feedback!

**Comment by doisyg** [comment]
Jumping in. 
It would be amazing that OpenCV supports Grayscale + alpha (CV_xxC2) the same way it supports color + alpha (CV_xxC4).
I can understand the argument that OpenCV is computer vision first and that there is no alpha channel from camera streams, but then it is not coherent to support the alpha channel for color images and not grayscale images.
If one wanted to contribute to add support for grayscale + alpha, would it be accepted ? And if so, were to start ?
