### ISSUE TITLE
cv::VideoCapture set(CAP_PROP_POS_FRAMES, target) does not work in android cpp

### ISSUE THREAD

**Issue by milad-ahmadi** [opencv/opencv#19387]
I am trying to use OpenCV VideoCapture in android to read some frames for training. After training, I would like to return to the beginning of the video and do processing. The problem is that OpenCV VideoCapture set cannot return to the beginning of the video. Also, the VideoCapture  get command always returns a value of 0.

- OpenCV => 4.1.1
- Operating System / Platform => Android
- Compiler => Android studio
- Input video format/codec => mp4/h264  and B-frames is 0

```.cpp
// Read video
cv::VideoCapture video(srcVideoPath);

// Exit if video is not opened
if (!video.isOpened())
{
	return false;
}
//
int frameCount = video.get(CAP_PROP_FRAME_COUNT);

while (true)
{
	video.read(inputFrame);
	if (inputFrame.empty())
	{
		video.set(CAP_PROP_POS_FRAMES, 0);
		video.read(inputFrame);
	}
}
```

**Comment by milad-ahmadi** [comment]
There is no solution to this problem in issues #15547 and #11952. Also, my question is different from question #11952.

**Comment by wangrentao** [comment]
Is it possible to open camera using cv::videoCapture(0) in android now?
