### ISSUE TITLE
Where is LIBAVCODEC_VERSION_MICRO in codes

### ISSUE THREAD

**Issue by xingyun86** [opencv/opencv#19381]
Where is LIBAVCODEC_VERSION_MICRO in codes?
How I can set it please?
My project is cmake project.

**Comment by alalek** [comment]
Try to use search first: https://github.com/FFmpeg/FFmpeg/search?q=LIBAVCODEC_VERSION_MICRO

Closing.

**Comment by xingyun86** [comment]
> Try to use search first: https://github.com/FFmpeg/FFmpeg/search?q=LIBAVCODEC_VERSION_MICRO
> 
> Closing.

But I only compile opencv . Where I set the macro value?

**Comment by xingyun86** [comment]
> > Try to use search first: https://github.com/FFmpeg/FFmpeg/search?q=LIBAVCODEC_VERSION_MICRO
> > Closing.
> 
> But I only compile opencv . Where I set the macro value?

My problem had solved. I rebuild ffmpeg plugin with opencv. It works well now.Thanks for project.
