### ISSUE TITLE
OpenCV 4.5.1 cannot properly initialize VTK 9.0.1 during build with opencv_world

### ISSUE THREAD

**Issue by jingyuan129931** [opencv/opencv#19386]
Sir，
I compiled opencv4.5.1 with a line surface error

```
CMake Error at C:/Program Files (x86)/VTK/lib/cmake/vtk-9.0/vtkModule.cmake:2955 (get_property):
  get_property could not find TARGET opencv_viz.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  E:/opencv_contrib-4.5.1/modules/viz/CMakeLists.txt:43 (vtk_module_autoinit)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


CMake Error at C:/Program Files (x86)/VTK/lib/cmake/vtk-9.0/vtkModule.cmake:2962 (target_compile_definitions):
  Cannot specify compile definitions for target "opencv_viz" which is not
  built by this project.
Call Stack (most recent call first):
  E:/opencv_contrib-4.5.1/modules/viz/CMakeLists.txt:43 (vtk_module_autoinit)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)
```
But I've compiled vtk9.0.1.

**Comment by asmorkalov** [comment]
Could you provide mode details about OS, compiler, environemnt, cmake options, etc.

**Comment by fei4xu** [comment]
I have a similar issue yesterday, and I switched back to VTK v8.x, and it worked.

The issue is at this line:
https://github.com/opencv/opencv_contrib/blob/master/modules/viz/CMakeLists.txt#L43
So this is more a `opencv_contrib` issue.

**Comment by asmorkalov** [comment]
Related issues:

**Comment by asmorkalov** [comment]
@fei4xu , @jingyuan129931 Could you provide steps to reproduce the issue and details about your environment, OS, CMake version, VTK installation source, compiler, etc.

**Comment by finnhuebner** [comment]
Could reproduce this issue while configuring with CMake and BUILD_opencv_world option on. With opencv_world off it builds fine.
Build Environment:
Win 7 x64 with CMake 3.16.0 and VTK 9.0.1 built from source.
Steps to reproduce:
1. Build/Install VTK from source
2. Configure OpenCV project with CMake with options:
- OPENCV_EXTRA_MODULES_PATH set accordingly
- BUILD_opencv_world ON
- WITH_VTK ON

It appears that [`ocv_create_module()`](https://github.com/opencv/opencv_contrib/blob/master/modules/viz/CMakeLists.txt#L31) does not create necessary target `opencv_viz` for [`vtk_module_autoinit(TARGETS ${the_module} MODULES ${VTK_LIBRARIES})`](https://github.com/opencv/opencv_contrib/blob/master/modules/viz/CMakeLists.txt#L43) if world module is on (`_ocv_create_module` not invoked, compare [code](https://github.com/opencv/opencv/blob/master/cmake/OpenCVModule.cmake#L849)).

**Comment by asmorkalov** [comment]
Reproduced with Ubuntu 18.04 and VTK 9.0.1. CMake command line:
```
$ cmake -DBUILD_opencv_world=ON -DWITH_VTK=ON -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ../opencv-master
```
CMake output:
```
-- Allocator metrics storage type: 'long long'
--     module opencv_flann...
--     module opencv_imgproc...
--     module opencv_intensity_transform...
--     module opencv_ml...
--     module opencv_phase_unwrapping...
--     module opencv_photo...
--     module opencv_plot...
--     module opencv_quality...
--     module opencv_reg...
--     module opencv_surface_matching...
--     module opencv_viz...
CMake Error at /usr/local/lib/cmake/vtk-9.0/vtkModule.cmake:2955 (get_property):
  get_property could not find TARGET opencv_viz.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /home/alexander/Projects/OpenCV/opencv_contrib/modules/viz/CMakeLists.txt:43 (vtk_module_autoinit)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


CMake Error at /usr/local/lib/cmake/vtk-9.0/vtkModule.cmake:2962 (target_compile_definitions):
  Cannot specify compile definitions for target "opencv_viz" which is not
  built by this project.
Call Stack (most recent call first):
  /home/alexander/Projects/OpenCV/opencv_contrib/modules/viz/CMakeLists.txt:43 (vtk_module_autoinit)
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)


--     module opencv_xphoto...
--     module opencv_alphamat...
```

**Comment by alalek** [comment]
Workaround:
- disable opencv_world
- disable viz

through CMake flags.

**Comment by aamgr** [comment]
In https://github.com/opencv/opencv/blob/master/cmake/OpenCVModule.cmake#L848
change to 
if(BUILD_opencv_world AND OPENCV_MODULE_${the_module}_IS_PART_OF_WORLD AND NOT "${the_module}" STREQUAL "opencv_viz" )

**Comment by mprevot** [comment]
Same issue with 4.5.2 release and VTK9, @aamgr's edit solved it.
