### ISSUE TITLE
Error in documentation for RGB->HSV convertion

### ISSUE THREAD

**Issue by michalszczepanski91** [opencv/opencv#19406]
I think that there is missing **if** for "the [H parameter computation](https://docs.opencv.org/4.5.1/de/d25/imgproc_color_conversions.html#color_convert_rgb_hsv). If R = G = B the H should be 0.
Regards

**Comment by asmorkalov** [comment]
Thanks for the report. OpenCV is open source library, feel free to submit PR with the fix. Please use branch 3.4 as base and target for the PR. The changes will be promoted to master and next by OpenCV maintainers.

**Comment by KrisKunal27** [comment]
@asmorkalov  Hey I'm new to Open Source Contribution, Can I fix this issue?

**Comment by asmorkalov** [comment]
@KrisKunal27 Sure, Go ahead! Please start from these wiki pages:
- https://github.com/opencv/opencv/wiki/How_to_contribute
- https://github.com/opencv/opencv/wiki/Coding_Style_Guide

**Comment by alalek** [comment]
Please note, there is already opened fresh PR about this issue (check automatic links above)
