### ISSUE TITLE
pollKey, non-blocking variant of waitKey

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#19410]
this is a feature proposal for the `highgui` module.

I'd like to introduce a variant of waitKey, let's call it `pollKey`, that performs the same tasks, i.e. processing the GUI message loop until empty or actionable event, but does _not_ wait for messages.

`pollKey` is the equivalent of what `waitKey(0)` might have been, if infinite wait had been defined as -1.

goal: get some speed out of OpenCV's GUI functions. currently there is a mandatory Sleep() in the windows module (and others too), which causes the process to lose at least one scheduler time slice, which can be 10-15 milliseconds per invocation. when processing and displaying video, that adds up and eats a good fraction of the whole run time.

I've come up with code for win32. pull request incoming. I can *guess* at the code needed for QT, cocoa, and gtk. winrt seems to contain a stub function for waitKey and appears to fall back on the function found in `window_w32.cpp`.

how should this be done? do I implement what I can and leave the rest, or do I stub them, or do I fill in my best guess for correct code without the ability to test, or do I see about a development environment for those platforms?

I know about [OE-24](https://github.com/opencv/opencv/wiki/OE-24.-Module-HighGUI) #11019, which puts into question extra effort here that is bound to be superseded anyway.

**Comment by alalek** [comment]
Alternatives:
- `updateUI()` / `spinOnce()` (no key handling here)
- `getKey()` / `hasKey()`
- `peekKey()` (name from [win32](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagea))
- re-interpret `delay=1` as "nowait" mode.
- hack with `float`: `waitKey(float delay)` with 1e-6 or similar (or with "nowait" threshold for `delay < 1`)

**Comment by crackwitz** [comment]
here's some code I hope will be received well. most code in there is common to both procedures. they only differ in how they fetch a message and when they give up.

I'm not in a position to discuss naming and nuances of purpose. my inclination is towards representing both similarity and contrast in the name towards `waitKey`, since that already exists and everyone expects it. one might think bigger and rename waitKey itself. I don't know if that's warranted at this time, when a new UI is planned anyway.
