### ISSUE TITLE
quality loss with cv.imread() of .PNG

### ISSUE THREAD

**Issue by pb9803** [opencv/opencv#19421]
Hi,

I tried myself on stereovision the last time and came across a little problem.

During my test runs I saved all the images of the experiments with **cv.imwrite()**. (image of the right, left camera as well as the rectified images of them)
Now I'm on the point that I finshed all of my test and want to check how the disparity maps differ. 

So I wrote a little code that plot me a histogram of the distribution of all occuring disparities. Unfortunately the disparity maps are a little bit different to them in the test and so the comparison is not really representative for me.

Fo that I thought there might be a 'problem' with **cv.imread()** or with **cv.imwrite()**. 
I've already read that with cv.imwrite() it can come to quality loss when you save the image as **.jpg**. But is it the same with **.png**? 

And is there any possibility  to upscale the quality of an image? 

Thanks for your help!

Best wishes!

**Comment by saskatchewancatch** [comment]
PNG is lossless and there should be no loss when you use `imread` to read back PNG's that were written by `imwrite`.
The `Mat`'s given to `imwrite` and the one produced by `imread` should be identical if you work things correctly.

I suspect there's a problem upstream of `imwrite`.

It would be most helpful if you provided a code sample to "repro" the issue. Code sample should include 1) the use of stereo functions, 2) the calls to `imwrite`, and 3) the calls to `imread`. Also please attach inputs to the stereo-related code.
