### ISSUE TITLE
openCV for Android > 4.1.0 UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by sensbo** [opencv/opencv#19448]
##### System information (version)
- OpenCV Android SDK > 4.1.0 -e.g., **4.5.1**
- Operating System / Platform =>  Android x86 (Emulator)
- Compiler => Android Studio 4.1.2 / Java, Windows

##### Detailed description
I run in trouble by using openCV Android SDK > 4.1.0 for java Android application development. The application crashes by using any kind of SDK functions, only _InitDebug()_ function "false" but this means not loaded...

I am using
- openCV sdk as module (File->New->Import Module)
  \opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\java
- imported .so files to jniLib folder
  \opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs

##### Steps to reproduce
Create a simple standard android app without functionality, import opencv as module, import native\libs to jniLibs folder and check the error tab.

    ```.java
    if(OpenCVLoader.initDebug()) ... 
    ```
![example_MainActivity java](https://user-images.githubusercontent.com/70148252/106623820-4c437380-6575-11eb-82c7-b5d7611dce65.png)

##### Error message
Logging
_W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found_

##### Fix
_Short_:
libopencv_java4.so files from opencv > 4.1.0 (e.g. 4.5.1) shall be replaced with those from version opencv = 4.1.0 in the jniLibs folder.

_Long_: 
During testing I saw the root cause of this error which directly points to the jniLib (..sdk\native\libs) folder which represents the entrees:
_opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs
opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs\arm64-v8a
opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs\armeabi-v7a
opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs\x86
opencv-4.x.x-android-sdk\OpenCV-android-sdk\sdk\native\libs\x86_64_

**In every subfolder there is a libopencv_java4.so file. By replacing these files from ,-e.g. v4.5.1, with version 4.1.0, everything works fine.**

##### Note
I only using at the moment the x86 variant, because the emulator works at this architecture. Maybe the other libopencv_java4.so files in the other subfolders are fine.

I guess using the .so from an older version an the API with higher level is not a good idea, so I move back to 4.1.0 totally which makes me angry :-/.

###### Similar issues 
https://stackoverflow.com/questions/64672161/linking-error-for-opencv-4-5-0-android-sdk-on-pixel3a-phone
https://stackoverflow.com/questions/57698796/cannot-detect-opencv-libs-after-update-form-3-4-3-to-4-1-1

**Comment by alalek** [comment]
see here: #15024

If you want to use another C++ runtime, then you should rebuild OpenCV binaries.
Refer to this Android documentation for details: https://developer.android.com/ndk/guides/cpp-support

**Comment by sensbo** [comment]
> If you want to use another C++ runtime, then you should rebuild OpenCV binaries.

Could you please help me here, I am doing my first steps using opencv and I know better about java. Do you mean if I want to use opencv > 4.1.0 in android development I shall rebuild the opencv binaries by my own? Why not directly providing an opencv sdk?

**Comment by asmorkalov** [comment]
Android applications should pack C++ standard library to APK file to use STL and other standard calls. NDK provides several versions of runtime library with different license and functionality. They have different name and are not compatible. Alexander pointed that OpenCV changed STL implementation between 4.1.0 and 4.5.1 and STL library is named differently. As soon as Java code have to load all shared libaries explicitly you have two options:
- Change build scripts and Java code to use new STL shat is shipped with 4.5.1. New OpenCV for Android SDK already loads proper STL.
- Rebuild OpenCV by yourself with alternative STL (may have issues with OpenCV) as Alalek mentioned.

All problems with user code and ideas are discussed on forum: forum.opencv.org. Please do not use issue tracker for it.

**Comment by rushi-12320** [comment]
I WANT TO CONTRIBUTE IN THIS PROJECT SO PLEASE REPLY ME
