### ISSUE TITLE
cv2.error: OpenCV(4.5.1) /home/integra/opencv/opencv_contrib/modules/cudafilters/src/filtering.cpp:422: error: (-215:Assertion failed) src.type() == srcType_ in function 'apply'

### ISSUE THREAD

**Issue by Ndron** [opencv/opencv#19459]
##### System information (version)

- OpenCV => 4.5.1 cuda
- Operating System / Platform =>  Ubuntu 20.04.1 LTS

Try to use cv2.cuda.createGaussianFilter with code

img = cv2.imread("Cadr.jpg")
gpu_frame = cv2.cuda_GpuMat()
gpu_frame.upload(img)
ksize = (5, 5)
gpuFilter = cv2.cuda.createGaussianFilter(srcType=cv2.CV_8UC1, dstType=cv2.CV_8UC1, ksize=ksize, sigma1=0, sigma2=0)
gpuSrc = cv2.cuda_Filter.apply(gpuFilter, gpu_frame)

got Error

cv2.error: OpenCV(4.5.1) /home/integra/opencv/opencv_contrib/modules/cudafilters/src/filtering.cpp:422: error: (-215:Assertion failed) src.type() == srcType_ in function 'apply'

**Comment by asmorkalov** [comment]
`cv.imread()` returns 3 channel BGR image by default. The filter is created for type `cv2.CV_8UC1` with single channel.
