### ISSUE TITLE
Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by moncio** [opencv/opencv#19462]
### System information

- OpenCV => 4.5.1
- Operating System / Platform => Ubuntu 20.04
- Compiler => Unix Makefiles
- Graphic card => Nvidia RTX 3090
- Driver version => 450.102.04
- Cuda version => 11.0.3
- Cudnn version => 8.0.5
- Python version => 3.8

### Steps to reproduce

Trying to compile the latest version of the library according to my graphic card to use GPU, is failing because the arquitecture is not supported. 

```
cmake \
        -DWITH_CUDA=ON \
        -DOPENCV_DNN_CUDA=ON \
        -DBUILD_CUDA_STUBS=ON \
        -DCUDA_FAST_MATH=ON \
        -DENABLE_FAST_MATH=ON \
        -DOPENCV_DNN_CUDA=ON \
        -DCUDA_ARCH_BIN=86 \
        -DCUDA_ARCH_PTX=86 \
        -DOPENCV_EXTRA_MODULES_PATH=/env/libs/opencv_contrib-${OPENCV_VERSION}/modules \
        -DWITH_GSTREAMER=ON \
        -DWITH_FFMPEG=ON \
        -DWITH_GTK=ON \
        -DWITH_QT=ON \
        -DWITH_OPENGL=ON \
        -DOPENCV_GENERATE_PKGCONFIG=ON \
        -DBUILD_opencv_python_3=ON \
        -DPYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3.8
```

Here I attached some pics of the problem:

### Build information:

![image](https://user-images.githubusercontent.com/4520583/107009129-e9302780-6794-11eb-9323-965e54f617f1.png)

### The issue:

![image](https://user-images.githubusercontent.com/4520583/107009174-f816da00-6794-11eb-9fc5-a797a6aa6b55.png)

Hope that anyone can help me.
 @alalek 

Thanks in advance

**Comment by tomoaki0705** [comment]
1. Usage question should go to forum, **not** GitHub issue. This is not only for you but anyone who sees this issue
2. **Don't attach** screenshots. The search doesn't work in screenshots. This is not only for you.
3. sm86 is supported from CUDA 11.**1**. so install appropriate version of CUDA

**Comment by moncio** [comment]
Ok, thank you and sorry guys.
