### ISSUE TITLE
Build Error on Xcode

### ISSUE THREAD

**Issue by AyonGupta** [opencv/opencv#19478]
Building for iOS, but the linked and embedded framework 'opencv2.framework' was built for iOS + iOS Simulator

**Comment by Johnzdh** [comment]
Could you provide some build error information?
I can build it successfully with OpenCV 4.5.1, XCode 11.3.1.

**Comment by DanielZanchi** [comment]
I am having the same problem. Downloaded the framework and I imported it into Xcode 13.2.1 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/6886116/152645858-e9bfa45e-51d4-460c-bdad-90dba680b727.png">
