### ISSUE TITLE
Build with C++17 but OpenCV changed Makefile to GNU+11

### ISSUE THREAD

**Issue by 9426224** [opencv/opencv#19483]
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 18.04.5 LTS on Nvidia Jetson TX1@JetPack 4.5
- Compiler => CMake 3.4.1 && G++ 7.5.0 With aarch64 env

Detailed description

I already built OpenCV with CUDA 10.2 and cuDNN 8.0.0, It's compile succeed and no error output.

when I try using OpenCV with CMake :

> find_package(OpenCV REQUIRED)

and link it to my project:

> target_link_libraries(myProject ${OpenCV_LIBS})

Some strange things happened, here is auto-generated make console:

```
/usr/bin/c++  -I/home/ubuntu/StereoCamera/include/eSPDI/linux -isystem /usr/local/include/opencv4 -isystem /usr/local/include/ncnn  -fPIE  -std=c++17 -pthread -fno-rtti -fno-exceptions -fopenmp -std=gnu++11 -o CMakeFiles/stereo.dir/Stereo/Image.cpp.o -c /home/ubuntu/StereoCamera/Stereo/Image.cpp
```

I have specify C++ version to :

> add_compile_options(-std=c++17 -pthread)

But when I link to OpenCV library , it will add `-std=gnu++11`  to project's make console.

I don't know why would this thing happened and still can't fix it, except try OpenCV 4.2.0/ 4.4.0/4.5.1-dev version to built,and can't fix it.

Here is my CMake build options:
```    
cmake -DCMAKE_BUILD_TYPE=RELEASE \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DWITH_CUDA=ON \
      -DCUDA_ARCH_BIN=5.3 \
      -DCUDA_ARCH_PTX="" \
      -DENABLE_FAST_MATH=ON \
      -DCUDA_FAST_MATH=ON \
      -DWITH_CUBLAS=1 \
      -DWITH_CUDNN=ON \
      -DOPENCV_DNN_CUDA=ON \
      -DWITH_LIBV4L=ON \
      -DWITH_V4L=ON \
      -DWITH_GSTREAMER=ON \
      -DWITH_GSTREAMER_0_10=OFF \
      -DWITH_QT=ON \
      -DWITH_OPENGL=ON \
      -DBUILD_opencv_python2=ON \
      -DBUILD_opencv_python3=ON \
      -DBUILD_TESTS=OFF \
      -DBUILD_PERF_TESTS=OFF \
      -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      ../
```

And here is my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.4.1)
set(CMAKE_CXXSTANDARD 17)
set(CMALE_CXX_COMPILER "/usr/bin/g++")

add_compile_options(-std=c++17 -pthread)

project(StereoCamera)

set(eSPDI_INCLUDE_DIR /home/ubuntu/StereoCamera/include/eSPDI/linux)
set(eSPDI_LIB_DIR /home/ubuntu/StereoCamera/lib/eSPDI/linux/aarch64)

find_package(OpenCV REQUIRED)
if(OpenCV_FOUND)
    message(STATUS "OpenCV Lib is Found!")
endif()

find_package(ncnn)
if(ncnn_FOUND)
    message(STATUS "NCNN Lib is Found!")
endif()

include_directories(
    ${eSPDI_INCLUDE_DIR}
    ${OpenCV_INCLUDE_DIRS}
    ${ncnn_INCLUDE_DIRS}
)


aux_source_directory(./Stereo DIR_SRC)
add_executable(stereo
    ${DIR_SRC}
)

target_link_libraries(
    stereo
    ncnn
    -lJetsonGPIO
    ${eSPDI_LIB_DIR}/libeSPDI.so
    ${OpenCV_LIBS}
)
```

**Comment by alalek** [comment]
> `add_compile_options(-std=c++17`

This is a hack and CMake may not analyse and handle properly this statement (depends on CMake version).

You should use supported CMake's ways instead. [Details](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html).

OpenCV's scripts uses features from `OPENCV_COMPILE_FEATURES` variable (can be redefined by user).

---

> And here is my CMakeLists.txt:
> set(CMAKE_CXXSTANDARD 17)

Typo in `CMAKE_CXX_STANDARD`.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by 9426224** [comment]
Thanks for your suggestions! I will try it.


________________________________
发件人: Alexander Alekhin <notifications@github.com>
发送时间: 2021年2月9日 9:43
收件人: opencv/opencv <opencv@noreply.github.com>
抄送: 9426224 <9426224@live.com>; Author <author@noreply.github.com>
主题: Re: [opencv/opencv] Build with C++17 but OpenCV changed Makefile to GNU+11 (#19483)


add_compile_options(-std=c++17

This is a hack and CMake may not analyse and handle properly this statement (depends on CMake version).

You should use supported CMake's ways instead. Details<https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html>.

OpenCV's scripts uses features from OPENCV_COMPILE_FEATURES variable (can be redefined by user).

________________________________

And here is my CMakeLists.txt:
set(CMAKE_CXXSTANDARD 17)

Typo in CMAKE_CXX_STANDARD.

________________________________

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

―
