### ISSUE TITLE
Add python support for Viz module

### ISSUE THREAD

**Issue by Zumbalamambo** [opencv/opencv#19490]
Feature request:

Python module doesn't have Viz3d feature which is a huge drawback since no proper library provides one. Open3d offers one but it's not quite good due to its limitations.

**Comment by LaurentBerger** [comment]
@alalek I can manage this. 
But in pypi opencv is build without vtk. I understand then that only user who build opencv themself can use viz. is it right?

**Comment by Zumbalamambo** [comment]
@LaurentBerger thank you!! eagerly waiting!

**Comment by adhansen** [comment]
Any chance of this getting supported in the official OpenCV Python distribution?

**Comment by plutonium-239** [comment]
@LaurentBerger How can we use the bindings? What do we need to have installed and built?

**Comment by LaurentBerger** [comment]
build opencv and opencv contrib with vtk. Now you have [samples ](https://github.com/opencv/opencv_contrib/tree/4.x/modules/viz/samples) and [test  ](https://github.com/opencv/opencv_contrib/blob/4.x/modules/viz/misc/python/test/test_viz_simple.py)

**Comment by plutonium-239** [comment]
Do I have to uninstall opencv-python from pip first?
Also once i build opencv how do i "install"/use it in python?

**Comment by LaurentBerger** [comment]
Have you already build opencv opencv_contrib using cmake?

**Comment by plutonium-239** [comment]
No, i just installed the binaries using pip

**Comment by LaurentBerger** [comment]
You have to build and install vtk using cmake then build opencv and opencv_contrib using cmake with python_binding too. It's not really simple

**Comment by plutonium-239** [comment]
After building VTK, can I just `pip install --no-binary opencv-contrib-python`?
Because that does build it, I'm hoping it also detects that VTK is installed
