### ISSUE TITLE
Calling VideoCapture::getBackendName() causes crash.

### ISSUE THREAD

**Issue by ababo** [opencv/opencv#19513]
##### System information (version)
OpenCV version: `4.5.1` or `4.2.0`
Platform: `OS X 11.1`
Compiler: `Apple clang version 12.0.0 (clang-1200.0.32.29) x86_64-apple-darwin20.3.0`

##### Detailed description

Opened `VideoCapture` fails on assertion when calling `getBackendName()`:
```
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.5.1) /Users/user/app/build.release/opencv/src/opencv-pe/modules/videoio/src/cap.cpp:299: error: (-215:Assertion failed) api != 0 in function 'getBackendName'

Error: signal 6:
```

##### Steps to reproduce
1. Create and open instance of `VideoCapture` (e.g. using device `0`).
2. Call `getBackendName()` method.

**Comment by alalek** [comment]
C++ exception is not a crash. User code must handle them through try-catch.

**Comment by ababo** [comment]
Please read the end of the message
> .. error: (-215:Assertion failed) api != 0 in function 'getBackendName'

I believe it's not expected anyway.

**Comment by alalek** [comment]
What is returned value from `.isOpened()` method?

**Comment by ababo** [comment]
`true`

**Comment by ababo** [comment]
And the code grabs webcam frames without an issue.

**Comment by alalek** [comment]
`api == 0` is invalid case anyway. In this case used backend doesn't identify yourself (through `getCaptureDomain()` method).

There is no "default" / "unknown" result support in `.getBackendName()`, so this exception is raised.
