### ISSUE TITLE
solve_deg3 gives incorrect result (polynom_solver.cpp)

### ISSUE THREAD

**Issue by fantaclaus** [opencv/opencv#19526]
function **solve_deg3** from `opencv/modules/calib3d/src/polynom_solver.cpp`
gives an incorrect result = -nan 
for a=3.0, b=3.0, c=1.0, d=1.0

```c++
double x0, x1, x2;

auto n = solve_deg3(3.0, 3.0, 1.0, 1.0, x0, x1, x2);
```

n is 1
x0 is -nan(ind) but it should be -1.0

Compiled and run in MS VisualStudio 2019.

**Comment by asmorkalov** [comment]
@fantaclaus thanks for the report. The function you mentioned is not exported as public symbol and cannot be used directly. Could you give us some small reproducer for the function you call from public API.

**Comment by fantaclaus** [comment]
@asmorkalov, Sorry, I don't use the public API of this project.
I was just looking for a sample for solving a cubic equation and I've found a link to this project on stackoverflow.com:
https://stackoverflow.com/a/51292098/1336856

**Comment by theroyalpekka** [comment]
Hello! Iam able to resolve the issue and have created the necessary PR #19583 Thank You!
