### ISSUE TITLE
Deep learning - Mask generation - Bitwise

### ISSUE THREAD

**Issue by jthibaut** [opencv/opencv#19578]
Dear all,
I am performing a deep learning model using semantic segmentation in order to identify clouds shapes (4).
I think I generated the predictions well although I find it difficult to use and display them.
I would like to display on the same image my original image and the mask superimposed on this image (mask which corresponds to the prediction).
I was thinking of using openCV and the bitwise function but I got the following error message: 
`i = np.random.choice(len(X_test))
image = tf.keras.preprocessing.image.array_to_img(X_test[i])
masque = tf.keras.preprocessing.image.array_to_img(pred_mask[i])
masked_image = cv2.bitwise_or(image, masque)     
plt.imshow(masked_image)
plt.show()
 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-b36b6daf4684> in <module>
      2 image = tf.keras.preprocessing.image.array_to_img(X_test[i])
      3 masque = tf.keras.preprocessing.image.array_to_img(pred_mask[i])
----> 4 masked_image = cv2.bitwise_or(image, masque)
      5 plt.imshow(masked_image)
      6 plt.show()
 
TypeError: Expected Ptr<cv::UMat> for argument 'src1'
`
with:

`# Calcul des probabilités
# On retourne pour chaque image une probabilité de prédiction de chaque classe.
y_prob = model.predict(X_test)
 
# Pour prédire la classe de l'image, il suffit alors de trouver pour quelle classe la probabilité est maximale
y_pred = tf.argmax(y_prob, axis=-1).numpy()
 
# Prédiction du masque
pred_mask = y_pred[..., tf.newaxis]`

##### System information (version)
<!
- Operating System / Platform => Linux Mint 19.3 64 Bit
- Python 3.8.3
>

Could you help me ?
Thank you and 
Best Regards,
Thibaut

**Comment by pao0318** [comment]
# In this line you are converting your tensor into pillow image but cv2 operators expects a numpy array instead of pillow images.
### masque = tf.keras.preprocessing.image.array_to_img(pred_mask[i])

## So you need to convert your tensor into numpy arrays by the method .numpy()

image = X_test[i].numpy().astype('uint8')
masque = pred_ mask[i].numpy().astype('uint8')

masked_image = cv2.bitwise_or(image, masque)
plt.imshow(masked_image)
plt.show()

We have demonstrated this by a demo in this notebook:
Notebook [link:](https://colab.research.google.com/drive/1pytOujHmpZZm4vmOf3UIkkLWEigg6pkK#scrollTo=D1KBspVpsl67)

**Comment by jthibaut** [comment]
Thank you but I have the following error message:

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

for line:

masque = pred_mask[i].numpy().astype('uint8')

**Comment by pao0318** [comment]
Hello . I think it maybe because you would not have imported numpy package in your environment or if already did can you show the notebook where you have defined the tensors training and all stuffs. Will be glad to help.
Thank you.

**Comment by jthibaut** [comment]
Thanks
I saved as a python file the whole notebook (see attached zip file)
[Clouds_spy_3.1.py.zip](https://github.com/opencv/opencv/files/6018252/Clouds_spy_3.1.py.zip)
Sorry, but some comments are in French !

**Comment by pao0318** [comment]
Hyyy, Thanks for your code , Seems like if there isn't data or some images
to run those I will be unable to identify the outputs and shapes of code
cells. Can you please share some of the data or maybe it's link.
Thank You

**Comment by jthibaut** [comment]
[pics2.zip](https://github.com/opencv/opencv/files/6021964/pics2.zip)
Here is some pictures

**Comment by dkurt** [comment]
Please take a look at https://github.com/opencv/opencv/blob/master/samples/dnn/segmentation.py:

https://github.com/opencv/opencv/blob/a316b11aaa5baab3a810fa804425f53a3a0a5ca7/samples/dnn/segmentation.py#L108-L116
