### ISSUE TITLE
利用OpenCV编译程序时，报错。

### ISSUE THREAD

**Issue by YangLiu0427** [opencv/opencv#19602]
环境：Ubuntu16.04，OpenCV==3.4.1
错误信息：/usr/local/lib/libopencv_dnn.so.3.4.1: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

我换成OpenCV==4.3.0，也是同样的错误，请问是什么原因？十分感谢。

**Comment by YangLiu0427** [comment]
你好，请问为什么被认为是无效的问题呀？

**Comment by zhanlijia** [comment]
中文看不懂吧，翻译一下试试

**Comment by CsVeryLoveXieWenLi** [comment]
别太离谱，这是外国项目，不翻译？
