### ISSUE TITLE
OpenCV's Bayer naming differs from the rest of the world, resulting in unexpected demosaicing results

### ISSUE THREAD

**Issue by fijoy** [opencv/opencv#19629]
##### System information (version)

- OpenCV 4.2 tested, but issue probably present in all versions of OpenCV
- cv2 4.5.1 & 3.4.7 tested, but issue probably present in all versions of cv2

##### Detailed description

Cameras often produce images in one of the Bayer CFA (Color Filter Array) patterns: BayerRG (aka RGGB), BayerBG (BGGR), BayerGB (GBRG), and BayerGR (GRBG).

Every single reference and software (other than OpenCV) I've seen out there uses the top left 2x2 sub-matrix of the CFA to name the Bayer pattern. For example,

- MATLAB: https://www.mathworks.com/help/images/ref/demosaic.html
- Camera manufacturer Basler: https://www.baslerweb.com/en/sales-support/knowledge-base/frequently-asked-questions/bayer-to-rgb-and-missed-pixel-value-at-last-row-and-line/15245/

OpenCV, on the other hand, uses the 2x2 sub-matrix that starts at the 2nd row and 2nd column of the CFA:
https://docs.opencv.org/master/de/d25/imgproc_color_conversions.html

Because of this, what the rest of the world calls a BayerRG pattern, OpenCV calls a BayerBG pattern. 

So, if I configure a camera to produce BayerRG images, and if I use the COLOR_BayerRG2RGB code to convert the images into an RGB layout, I will actually get a BGR layout. I will need to use the COLOR_BayerBG2RGB code to get the RGB layout.

I believe this naming inconsistency is the source of all the confusion expressed in several other issues/threads, including:
- https://forum.opencv.org/t/bayerrg-rgb-conversion/1466
- https://github.com/danforthcenter/plantcv/issues/642
- https://github.com/opencv/opencv/issues/4857

OpenCV demosaicing seems to need an update to align with the rest of the world. 

##### Steps to reproduce behavior in cv2

```
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Simple 12x6 array 
I = np.uint8([
    255, 0, 255, 0, 255, 0, 
    0, 0, 0, 0, 0, 0,
    255, 0, 255, 0, 255, 0,
    0, 0, 0, 0, 0, 0,
    255, 0, 255, 0, 255, 0,
    0, 0, 0, 0, 0, 0,
    255, 0, 255, 0, 255, 0,
    0, 0, 0, 0, 0, 0,
    255, 0, 255, 0, 255, 0,
    0, 0, 0, 0, 0, 0,
    255, 0, 255, 0, 255, 0,
    0, 0, 0, 0, 0, 0
          ]).reshape(12, 6)

# Interpret the array as a BayerRG image and convert BayerRG --> RGB
# As per common definition of BayerRG, the array represents an all-red image
# NOTE: We know OpenCV often uses the BGR layout by default, but here I'm asking for RGB layout explicitly
J = cv2.cvtColor(I, cv2.COLOR_BayerRG2RGB)

# I expected an all-red image, but this display will show an all-blue image
plt.imshow(J)

# To confirm, this will print [0 0 255] for all RGB pixels
print(J)
```
##### Steps to compare the above results with MATLAB's
Feed the same example to MATLAB with the following code, by going to https://www.mathworks.com/help/images/ref/demosaic.html and clicking on “Try This Example” to open interactive coding window. MATLAB will display an all-red image as expected.

```
I = uint8([
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0; ...
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0; ...
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0; ...
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0; ...
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0; ...
255, 0, 255, 0, 255, 0; ...
0, 0, 0, 0, 0, 0
]);

J = demosaic(I,'rggb');

fig=figure, imshow(J); truesize(fig, [48, 24]);
```

**Comment by alalek** [comment]
Thank you for the report!

related issue: #18619

**Comment by saskatchewancatch** [comment]
I've only glossed through demosaicing.cpp and don't yet have an answer myself for this question: could this just be a matter of switching the R and B layers in the dst image after demosaicing function has done its work internally? I suspect it isn't that easy but perhaps it's possible with interpolation of a simpler Bayer format like BayerRG?

**Comment by saskatchewancatch** [comment]
I attempted to repro @fijoy 's issue (in head of 3.4 dev branch) and came across more confusing behaviour.

Complete C++ repro code:
```c++
#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

const int HEIGHT = 20;
const int WIDTH = 20;

int main()
{
    cv::Mat bayer_rg = cv::Mat::zeros(cv::Size2d(WIDTH, HEIGHT), CV_8U);

    //Create bayer_rg image with only red filter pixels lit up.
    //Green pixels remain 0
    for (int r = 0; r < bayer_rg.rows; r++)
        for (int c = 0; c < bayer_rg.cols; c++)
            if (c % 2 == 0)
                bayer_rg.at<unsigned char>(cv::Point2d(c, r)) = 255;

    std::cout << "Bayer RG array: " << std::endl << bayer_rg;

    cv::Mat demosaiced;
    cv::cvtColor(bayer_rg, demosaiced, cv::COLOR_BayerRG2RGB);

    std::cout << std::endl << std::endl << "Demosaiced: " << std::endl << demosaiced;

    //Display the original Bayer RG image and the demosaicing result.
    cv::namedWindow("input_bayer_rg");
    cv::namedWindow("demosaiced");
    cv::imshow("input_bayer_rg", bayer_rg);
    cv::imshow("demosaiced", demosaiced);
    cv::waitKey(0);
}
```

When I run this built on VC2019, I get 
![image](https://user-images.githubusercontent.com/21051160/113524822-7c57c480-956e-11eb-8480-bdc21c838284.png)

Confusing things:
1. My demosaic result shows a patched red image with uneven interpolation across parts of image.
2. OP's repro claims to produce a blue image.

Isn't expected result for both of our repro's supposed to be a full red image?

**Comment by fijoy** [comment]
@saskatchewancatch, I believe your pattern differs from mine: you have 255 whenever the column index is even, regardless of the row index. For example the top left 2x2 submatrix in your pattern is

255 0
255 0

which when interpreted as a BayerRG (RGGB) pattern as per the common definition of that pattern, contains 255 for both red and green filters. To get the pattern in my post, I think you need to change "c % 2 == 0" in your code to "c % 2 == 0 && r % 2 == 0".

Pay attention also when you display an image using OpenCV's imshow(). The display routine may be swapping the 1st and 3rd channels (at least it does in cv2.imshow(), the Python interface of OpenCV).

**Comment by s-trinh** [comment]
I would suggest to introduce additional enum with appropriate names that follow the expected naming convention.
Similar to the RGB/BGR handling:

```
    COLOR_BayerBG2RGB = COLOR_BayerRG2BGR,
    COLOR_BayerGB2RGB = COLOR_BayerGR2BGR,
    COLOR_BayerRG2RGB = COLOR_BayerBG2BGR,
    COLOR_BayerGR2RGB = COLOR_BayerGB2BGR,
```

- What about deprecating these enum in the next OpenCV major version if there is a consensus that the OpenCV naming is not standard?
- What about the G-API `BayerGR2RGB()` function? Does it follow the OpenCV Bayer convention? If so, there should be a note in the documentation. Otherwise, there is a discrepancy inside the OpenCV library.

**Comment by alalek** [comment]
I would suggest to use 4 symbols codes instead of 2 (similar to MATLAB, see the link above) to avoid confusion with both OpenCV 2row2col naming and "the rest of the world".

- `COLOR_BayerGBRG2RGB`
- `COLOR_BayerGRBG2RGB`
- `COLOR_BayerBGGR2RGB`
- `COLOR_BayerRGGB2RGB`
- plus ...2BGR, RGBA/BGRA, _VNG, _EA mappings

/cc @vpisarev @asmorkalov

**Comment by alalek** [comment]
Please take a look on this PR: #20970
Updated documentation is [here](http://pullrequest.opencv.org/buildbot/export/pr/20970/docs/de/d25/imgproc_color_conversions.html).
