### ISSUE TITLE
Python kernel dies while using feature matching

### ISSUE THREAD

**Issue by gumibobozelka** [opencv/opencv#19624]
- OpenCV => 4.5.1
- Operating System / Platform => Windows 64 Bit and Ubuntu
- 
##### Detailed description

I'm trying to use feature matching tutorial: https://docs.opencv.org/master/dc/dc3/tutorial_py_matcher.html. I made no changes, just trying to test it.
No matter which features I use, python kernel dies every time, while processing detectAndCompute() function. There are no errors or exceptions printed.

**Comment by Lotemn102** [comment]
Can't reproduce your problem. The code in the tutorial runs perfectly fine on my machine. 
I use Windows 10, 64-bit and OpenCV 4.5.1.
