### ISSUE TITLE
error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'

### ISSUE THREAD

**Issue by jthibaut** [opencv/opencv#19654]
Dear all,
I am trying to do deep learning segmentation.
I have pictures and decoded masks for .csv avec jpeg pictures.
I read the mask from my cv file (line 0):
`masque = masks[0]
masks[0].shape`
I have:
(256,256)
I read the associated picture:
`image = cv2.imread(train["Image"][0],cv2.IMREAD_GRAYSCALE)
image.shape`
(256,256)
I want to plot the image and the mask together:
`masked_image = cv2.bitwise_or(image, masque)
plt.imshow(masked_image)`
But I have the following message:
`error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/core/src/arithm.cpp:232: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'`

I don't understand what happens and I am stuck.
Could you help me ?
Thank you
Thibaut

**Comment by Lotemn102** [comment]
Could you provide the exact lines of code you use to read your `masks` list from the csv?

**Comment by jthibaut** [comment]
Dear all, 
Since I found some solutions but I don't know if what I have done is accurate.
You will see enclosed my notebook.
Thanks
Thibaut
[Clouds_spy_3.1.ipynb.zip](https://github.com/opencv/opencv/files/6102865/Clouds_spy_3.1.ipynb.zip)
