### ISSUE TITLE
opencv3.412  no suitable user_defeined conversion from cv::mat to CvMat

### ISSUE THREAD

**Issue by seuwanglang** [opencv/opencv#19673]
hello ,when i try initialing  a CvMat  using a mat，for example  “mat bb；CvMat aa=bb；” then come out the error showed in my title。can anybody help me？thanks in advance

**Comment by alalek** [comment]
OpenCV 1.0 C API was deprecated since 2.4 releases and not supported since OpenCV 3.0 (2014).
