### ISSUE TITLE
G-API: Python tests failed in builds with OpenVINO

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#19719]
Nightly builds with OpenVINO, like:
master_openvino-skl-lin64: [good](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/953) / [bad](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/954)
master_openvino-win64: [good](http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64/builds/661) / [bad](http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64/builds/662) (crashed)

Test: `test_person_detection_retail_0013 (test_gapi_infer.test_gapi_infer)`

relates #19707

/cc @AsyaPronina @TolyaTalamanov @dbudniko

---

Run gapi tests only:

```
OPENCV_PYTEST_FILTER=test_gapi* ./setup_vars.sh python3 <opencv_dir>/modules/python/test/test.py -v --repo <opencv_dir>
```

**Comment by TolyaTalamanov** [comment]
Broken by: https://github.com/opencv/opencv/pull/19707
@AsyaPronina could you have a look ? 
I think the problem in `giebackend.cpp`
