### ISSUE TITLE
GPL license issue in features2d.hpp and mser.cpp

### ISSUE THREAD

**Issue by KarlKulator** [opencv/opencv#19729]
##### System information (version)
- OpenCV => 4.5

##### Detailed description

There seems to be a license issue in https://github.com/opencv/opencv/blob/master/modules/features2d/include/opencv2/features2d.hpp.

It states:
```
- the color image algorithm is taken from: @cite forssen2007maximally ; it should be much slower
than grey image method ( 3~4 times ); the chi_table.h file is taken directly from paper's source
code which is distributed under GPL.
```

The chi table can be found in mser.cpp as chitab3.

This would force the code to be under GPL.

This was already discussed in https://answers.opencv.org/question/31718/opencv-247-gpl-licensing-issue-with-msercpp/. But no fix was ever done.

**Comment by alalek** [comment]
I believe, this note should be updated according to the current state from author's page:

> A version of chi_table.h with a more permissive copyright statement for those who need it.

http://users.isy.liu.se/cvl/perfo/software/

File license is BSD-like:

http://users.isy.liu.se/cvl/perfo/software/chi_table.h (+[copy](https://github.com/opencv/opencv/files/6146559/chi_table.h.txt))
