### ISSUE TITLE
invalid link on wiki

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#19723]
link of [The 2020 Movie](https://studio.youtube.com/video/9dAMAvh2Em4/edit) should be corrected on page https://github.com/opencv/opencv/wiki/GSoC_2021

i think intended link is https://www.youtube.com/watch?v=ROGa2tutPHQ&t=32s

**Comment by lydiakravchenko** [comment]
@sturkmen72 Thanks for noticing, fixed it!
