### ISSUE TITLE
Linking with Prebuilt opencv_world gives errors

### ISSUE THREAD

**Issue by blganesh101** [opencv/opencv#19756]
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => Ubuntu 18.04

I am building opencv 4.5.1

wget latest opencv
https://github.com/opencv/opencv/releases

wget latest opencv contrib
https://github.com/opencv/opencv_contrib/releases

so in a folder we must have opencv and opencv_contrib folders
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$cwd/install -DINSTALL_C_EXAMPLES=ON -DINSTALL_PYTHON_EXAMPLES=OFF -DWITH_TBB=OFF -DWITH_V4L=OFF -DWITH_QT=OFF -DWITH_OPENGL=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DBUILD_EXAMPLES=OFF -DBUILD_opencv_world=ON -DOPENCV_DNN_OPENCL=ON ..

Once I have libopencv_world.so, I am linking in my cmakelists.txt file as 

```
set(OPENCV_PATH ${LIB_DIR}/opencv)
add_library(lib_opencv SHARED IMPORTED)

# sets the location of the prebuilt opencv .so
set_target_properties( lib_opencv
        PROPERTIES IMPORTED_LOCATION
        ${LIB_DIR}/opencv/lib/libopencv_world.so )

include_directories(${LIB_DIR}/opencv/include)

target_link_libraries(smaple lib_opencv)
```
I get multiple errors like following

```undefined reference to `cv::dnn::dnn4_v20200609::Net::Net()'
```undefined reference to `cv::dnn::dnn4_v20200609::Net::getLayerNames[abi:cxx11]() const'

**Comment by alalek** [comment]
> add_library(lib_opencv SHARED IMPORTED)

Do NOT write own CMake scripts if `find_package()` approach is available.
See example here: https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
