### ISSUE TITLE
Inference Engine backend can't handle when the model input size has different width and height

### ISSUE THREAD

**Issue by Quantizs** [opencv/opencv#19781]
##### System information (version)

- OpenCV => 4.5.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

We have two custom YOLOv4 model. 
One of them is a license plate detector using 256 x 256 input size.
The other is a character detector which is using input size with different width and hegiht (width = 416, height = 224).

If we are using opencv backend both the plate and character detector returns valid detections.
![1](https://user-images.githubusercontent.com/26270983/112483442-50bc2980-8d79-11eb-83a4-a61c7bae76be.png)
![2](https://user-images.githubusercontent.com/26270983/112483508-616c9f80-8d79-11eb-945d-7c357ef2b7d3.png)
![3](https://user-images.githubusercontent.com/26270983/112483517-64679000-8d79-11eb-81d3-89e90b0d4320.png)

When we change the backend to Inference Engine the license plate detector returns the same results as before but the character detector results go wrong:
![1w](https://user-images.githubusercontent.com/26270983/112483562-6df0f800-8d79-11eb-8925-6181a3206e00.png)
![2w](https://user-images.githubusercontent.com/26270983/112483578-70ebe880-8d79-11eb-99c8-50dfe0d42016.png)
![3w](https://user-images.githubusercontent.com/26270983/112483595-747f6f80-8d79-11eb-99a9-ee4276a7d3d1.png)

- The backend was the only difference between the two execution.
- The only difference between the two model is that one has the same input width and height and the other does not.

##### Steps to reproduce

**Comment by dkurt** [comment]
Problem must be somewhere in `initNgrqaph` funtion: https://github.com/opencv/opencv/blob/ca8c3dd9b5ab7e94dbe9690f5abd6b711446d776/modules/dnn/src/layers/region_layer.cpp#L433-L434.

Can you try to modify `supportBackend` in the following way to disable the layer and see how it goes?
```cpp
    virtual bool supportBackend(int backendId) CV_OVERRIDE
    {
        return backendId == DNN_BACKEND_OPENCV;
    }
```

**Comment by Quantizs** [comment]
> Problem must be somewhere in `initNgraph` function:
> 
> https://github.com/opencv/opencv/blob/ca8c3dd9b5ab7e94dbe9690f5abd6b711446d776/modules/dnn/src/layers/region_layer.cpp#L433-L434
> 
> .
> Can you try to modify `supportBackend` in the following way to disable the layer and see how it goes?
> 
> ```c++
>     virtual bool supportBackend(int backendId) CV_OVERRIDE
>     {
>         return backendId == DNN_BACKEND_OPENCV;
>     }
> ```

I modified the `supportBackend` function as you requested and it solved the problem. 
If i understand it correctly, this modification forces the regionlayer to use opencv backend but leaves all the other layers on IE backend. Am I right?

**Comment by dkurt** [comment]
@Quantizs, that's right - so we can say that bug is localized in the detection layer (width/height are swapped somewhere).

**Comment by XiangMichael** [comment]
In DNN_BACKEND_INFERENCE_ENGINE mode, DNN_TARGET_CPU succeeds, but DNN_TARGET_OPENCL_FP16 crashes ,How can I solve this problem  ?

**Comment by XiangMichael** [comment]
> In DNN_BACKEND_INFERENCE_ENGINE mode, DNN_TARGET_CPU succeeds, but DNN_TARGET_OPENCL_FP16 crashes ,How can I solve this problem ?

**Comment by XiangMichael** [comment]
> Problem must be somewhere in `initNgraph` function:
> 
> https://github.com/opencv/opencv/blob/ca8c3dd9b5ab7e94dbe9690f5abd6b711446d776/modules/dnn/src/layers/region_layer.cpp#L433-L434
> 
> .
> Can you try to modify `supportBackend` in the following way to disable the layer and see how it goes?
> 
> ```c++
>     virtual bool supportBackend(int backendId) CV_OVERRIDE
>     {
>         return backendId == DNN_BACKEND_OPENCV;
>     }
> ```

When I do it, when "backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_CPU "Running result is normal, but" backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_OPENCL_FP16 "will crash directly

**Comment by alalek** [comment]
> crash directly

It is an exception message. not a crash (from linked issue from OV).

> Failed to initialize Inference Engine backend (device = GPU): Ngraph operation Transpose with name permute_16 has dynamic output shape on 0 port, but CPU plug-in supports only static shape

Model: YOLOv3, input: inpWidth=480, inpHeight=320

Which is OpenVINO version used?

---

OpenCV has YOLOV3 tests which use 416x416 input.

Model itself should be trained for used sizes (to get adequate results): https://github.com/pjreddie/darknet/blob/e84933bfdd7315736c442a41d9aed163843dda54/cfg/yolov3.cfg#L8-L9

**Comment by XiangMichael** [comment]
> 
 OpenVINO version is openvino_2021.4.752
I retrained. When the training size is the same as the inference size (the input width and height are different), there will still be exception message, as follows:  
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.4) Error: Unspecified error (Failed to initialize Inference Engine backend (device = GPU): Ngraph operation Transpose with name permute_16 has dynamic output shape on 0 port, but CPU plug-in supports only static shape) in cv::dnn::InfEngineNgraphNet::initPlugin, file D:\code\vs2017_major\opencv454_openvino\modules\dnn\src\ie_ngraph.cpp, line 742
