### ISSUE TITLE
Potential license issue with GPL code with svgfig

### ISSUE THREAD

**Issue by matanox** [opencv/opencv#19795]
It may appear that including the following script in the repository is not compatible with the GPL license of it.
https://github.com/opencv/opencv/blob/ad2f5ccc66d70e3611122ae26002d93e0b0c4de4/doc/pattern_tools/svgfig.py

**Comment by alalek** [comment]
It is a helper tool to generate pattern images. It is not used to build OpenCV.

See also https://github.com/opencv/opencv/commit/e7f0ad3c180e707d375cd7bad436fbceb8f517ed
