### ISSUE TITLE
EntryPoint Not Found when using MingW-w64 GCC compilers

### ISSUE THREAD

**Issue by pstricks-fans** [opencv/opencv#19843]
##### System information (version)

- OpenCV =>4.5.1
- Operating System / Platform => Windows 64 Bit
- Compiler => MinGW-W64 GCC-8.1.0 and MinGW-W64 GCC-7.3.0
- CMAKE 3.20.0 64 Bit
##### Prerequisites 

1. Extract  [OpenCV 4.5.1](https://sourceforge.net/projects/opencvlibrary/files/4.5.1/opencv-4.5.1-vc14_vc15.exe/download).
2. Install [CMake 3.20.0 x64](https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-windows-x86_64.msi).
3. Extract [MinGW-W64 8.1.0-release-posix-seh](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z) or [MinGW-W64 7.3.0-release-posix-seh](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-posix/seh/x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z).
4. Configure the `PATH` for the above 3 items.

##### Steps to reproduce

1. Run CMAKE GUI, specify the source and the build folders, click `Configure`,  select `MingW-Makefiles` and specify the compiler. A list of items in red appear, just accept the default and press `Configure` again. Once the list has changed to white, press `Generate`. After the generation is complete, close CMAKE.
2. Run `mingw32-make -j16` followed by `mingw32-make install -j16` to produce `Install` folder containing `include`, `bin` and `lib` subfolders.
3. Write a test project as follows.
```
#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
// Some headers are not mandatory in this simple test project but I keep them for the sake of my own convenience.

using namespace std;
using namespace cv;

int main()
{
    Mat input = imread("lenna.jpg", IMREAD_GRAYSCALE);


    if (input.empty())
    {
        cout << "Image is empty" << endl;
        return -1;
    }

    const string wnd = "input";

    namedWindow(wnd, WINDOW_NORMAL);
    imshow(wnd, input);

    waitKey();
    destroyWindow(wnd);

    return 0;
}
```

4. Build the above code with the following command.

    `g++ filename.cpp -o filename.exe -I c:\opencv_z\build\include -L c:\opencv_z\releases\lib -llibopencv_world451`

5. The build  succeeds but when I run it, the following errors happen. 

![test2](https://user-images.githubusercontent.com/50270635/113434385-130b7080-940b-11eb-9d9e-280b3e261516.png)

# Solution
To fix this I have to change to 32 bit version of MingW GCC compiler, either 8.10 version or 7.3.0 version.

**Comment by alalek** [comment]
MinGW and MSVC has different C++ ABIs. Mentioned windows package is targeted for MSVC 2015+ only.

**Comment by pstricks-fans** [comment]
> MinGW and MSVC have different C++ ABIs. Mentioned windows package is targeted for MSVC 2015+ only.



 The mentioned windows package contains source code as well as prebuilt binaries for MSVC. However, I am using MinGW and not using Microsoft Visual C++ compiler. That is why I built the OpenCV binaries by myself from the source code. So here I am not talking about the prebuilt binaries. I did not use the prebuilt binaries (for MSVC) with MinGW.

**Comment by alalek** [comment]
Got it. However there is provided dedicated sources-only package (or consider using git).

MinGW is not officially supported (On Windows we support native MSVC 2015/2017/2019).
May be someone from OpenCV community can share guidelines how to resolve these issues.

**Comment by pstricks-fans** [comment]
@berak : Thank you for your time.

The screenshots were taken when I put the built libraries in `c:\opencv_z` with the following details:

- Include is in `c:\opencv_z\build\include`
- Lib is in `c:\opencv_z\releases\lib`
- Bin is in `c:\opencv_z\releases\bin`

The `install` folder has been renamed to `opencv_z` and everthing has been renamed and arranged carefully without any mistakes. So it is not about the folder. I tested in 32 bit version and it works without problem. The problem is when I switch to 64 bit version of MinGW.

**Comment by pstricks-fans** [comment]
The 100% same settings and configurations have been  applied when using both MinGW 32 bit and MinGW 64 bit. 
The problem only happens when I use MinGW 64 bit.
Using MinGW 32 bit has no problem, works fine!

**Comment by sfhacker** [comment]
We are new to OpenCV.
Just built OpenCV 4.5.2 from source on Windows 10 x64 (MinGW).
Compiled and run the code snippet above. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/114273979-bab61d80-9a5f-11eb-9270-1804e2e08d2d.png)

Does it make sense to build 32-bit apps and libraries nowadays?

**Comment by pstricks-fans** [comment]
@sfhacker The problem still exists. Could you share how did you compile the OpenCV binaries and what version of MinGW (64 bit) compiler did you use?

**Comment by berak** [comment]
@pstricks-fans you claim to link against opencv_world, yet the msgboxes show, that it tries to invoke opencv_core.dll, etc.

**Comment by pstricks-fans** [comment]
@berak : I don't  understand whether I misused it or not. But the same code which are compiled with two versions of MingGW and OpenCV (32 bit versus 64 bit) produce different results; the 32 bit works fine but the other one fails.

**Comment by pstricks-fans** [comment]
@berak : Does your comment imply implicitly that you cannot reproduce my issue?

**Comment by berak** [comment]
@pstricks-fans , no i cannot reproduce any of your troubles.

both 32 and 64bit versions work fine for me, if you get different results, you *must* have done something different with the builts.
please check again.

**Comment by pstricks-fans** [comment]
@berak : OK. Thank you for your time. I will check again this issue on different computers later (to get clean environment).

**Comment by pstricks-fans** [comment]
The culprit is:

There are two 64-bit `libstdc++-6.dll` files in my `PATH`. The older one unfortunately is on the top so any request to 64b-bit `libstdc++-6.dll` will be bounded to the top one.

As a result, my applications that need the new one gets crashed. Swapping them solves the problem. 

Using 32-bit version of MinGW can solve this issue as well, but it is a very controversial  option!
