### ISSUE TITLE
Exposing the max iteration parameters for findEssentialMat

### ISSUE THREAD

**Issue by ayushbaid** [opencv/opencv#19845]
Functions like `findFundamentalMat` and `findHomography` have exposed the parameter bounding the number of iterations as an input argument. Particularly for `findFundamentalMat`, PR [16498](https://github.com/opencv/opencv/pull/16498) presented a detailed analysis of improvement in performance with increase in number of iterations.

The `findEssentialMat` function should expose the same argument for consistency and for potential performance gains.

**Comment by gasparitiago** [comment]
@ayushbaid 

Let me know if it's okay or if there is something else necessary:
https://github.com/opencv/opencv/pull/19847

**Comment by ayushbaid** [comment]
This change looks good to me!

**Comment by gasparitiago** [comment]
I did some mistakes when trying to solve the problem but now it seems that the PR is ready for reviewing :)
