### ISSUE TITLE
Numpy Array without OWNDATA flag can't be written into VideoWriter

### ISSUE THREAD

**Issue by adrianstas** [opencv/opencv#19866]
##### System information (version)
- OpenCV == 4.5.1
- Numpy == 1.20.2
- Operating System / Platform == Windows-10-10.0.19041-SP0

##### Detailed description
By unknown reason array without OWNDATA and with magic value of '433 pixels' in pad operation after wrote into VideoWriter will crash whole program immediatery.

##### Steps to reproduce

```python
import cv2 as cv
import numpy as np
import platform

np.__version__  # 1.20.2
cv.__version__  # 4.5.1
platform.platform()  # Windows-10-10.0.19041-SP0

out = cv.VideoWriter(
    "temp.mp4",
    cv.VideoWriter_fourcc(*"mp4v"), # format does not matter
    25,
    (2000, 1000),
    True,
)

frame = np.zeros((1000, 2000, 3), dtype=np.uint8)
shifted_frame = np.pad(frame, ((0, 0), (0, 79), (0, 0)))[:, 79:]

assert frame.shape == shifted_frame.shape  # OK
assert np.all(frame == shifted_frame)  # OK
assert frame.dtype == shifted_frame.dtype  # OK
assert frame.flags.owndata != shifted_frame.flags.owndata # OK has different value

out.write(frame)  # OK
out.write(shifted_frame.copy())  # OK
out.write(shifted_frame)  # ERROR Program will terminate without any error
```

**Comment by eric-wieser** [comment]
I'm pretty sure the relevant flag is `C_contiguous` not `OWN_DATA`, but I could be wrong.

**Comment by adrianstas** [comment]
the code:
``` python
out.write(frame[:])
```
didn't crashed the program. 

I believe that problem may be strictly related to slicing direction and value. 
In below example the program was crash only if I:
- assigned into shift variable values: `433` or `434`
- array was "cut from left".

```python
shift = 433
# f = np.zeros((1000, 2000+shift, 3), dtype=np.uint8)[:, shift:] # truncating 433 pixels "from left" will crash the program
f = np.zeros((1000, 2000+shift, 3), dtype=np.uint8)[:, :-shift] # truncating 433 pixels "from right" will works file
assert f.shape == (1000, 2000, 3)
out.write(f)
```

Please try to reverse comment in `f = ...` declaration

**Comment by asmorkalov** [comment]
Re-targeted to 4.x milestone as OpenCV team does not droduce python releases for 3.4 any more.

**Comment by dkurt** [comment]
Cannot reproduce with OpenCV 4.7.0 and NumPy 1.24.3 installed by `pip`:

```
1.24.3
4.7.0
Windows-10-10.0.19044-SP0
```
