### ISSUE TITLE
I got "ibopencv_cudaarithm.so.4.5: undefined symbol" when I import cv2

### ISSUE THREAD

**Issue by JimXu1989** [opencv/opencv#19869]
I just install opencv 4.5.2 from source on my ubuntu 20.04, when I import cv2. Igot the following problem:

(base) jim@jim-AERO-15-X9:~/anaconda3/lib/python3.8/site-packages/cv2/python-3.8$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/libopencv_cudaarithm.so.4.5: undefined symbol: _ZN2cv4cuda14StreamAccessor9getStreamERKNS0_6StreamE

Could you help me to solve this? Thanks a lot!!

**Comment by k-attila98** [comment]
If you found a solution, please let me know, I have the same problem.

**Comment by JimXu1989** [comment]
> If you found a solution, please let me know, I have the same problem.

use native python instead python provided by anaconda, it willl work, I don't know the reason.

**Comment by AGpix** [comment]
I am using native python with OPenCV4.2 but getting this error. What could be causing it

**Comment by mahyarmirrashed** [comment]
Having this issue too. I think it might be something with the installation of OpenCV. Not sure. Mine is identical in the symbol name to yours @AGpix .

**Comment by asewa108** [comment]
I am having the same issue too. Identical in the symbol name. What was the solution to this?

**Comment by AGpix** [comment]
> I am having the same issue too. Identical in the symbol name. undefined symbol: _ZN2cv4cuda14StreamAccessor9getStreamERKNS0_6StreamE
> 
> What was the solution to this?

Sorry it has been some time now. I have totally forgotten. Chk you gpu arch as suggested here - https://stackoverflow.com/questions/57928153/import-cv2-in-python-give-undefined-symbol-error
