### ISSUE TITLE
4.5.2 Videoio breaking change for GPU acceleration

### ISSUE THREAD

**Issue by rafale77** [opencv/opencv#19867]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Linux x64
- Compiler => GCC
- API: Python 3.8.9
- nVidia Cuda: 11.2.1
- Cudnn: 8.1.1

##### Detailed description

After upgrading from 4.5.1 to 4.5.2 the ffmpeg backend videoio decoding/encoding broke.
Also posted in the forum:
https://forum.opencv.org/t/opencv-4-5-2-breaking-change-with-ffmpeg-hw-accelerated-decoding/2613/2

##### Steps to reproduce

Old syntax to start a video capture stream

os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"]="hwaccel;cuvid|video_codec;h264_cuvid|vsync;0"
stream = cv2.VideoCapture(rtsp_server_uri, cv2.CAP_FFMPEG)

Upgrading to 4.5.2 will lead to failure to start the stream without any error message on python.

After looking at documentation it appears that there are new features additions which have broken the hardware acceleration. After a few tests, the closest I have come to get it to work was:

os.environ[ "OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "hw_decoders_any;cuda"
stream = cv2.VideoCapture(rtsp_server_uri, cv2.CAP_FFMPEG, (cv2.CAP_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY))

But it still found the url and started the stream without any decoding. Verified the problem by recompiling 4.5.1 with the exact same libraries and found it to work fine.

**Comment by dkurt** [comment]
I just verified on 337c183b9db4cfd5358b09ec8a610f449e3b8e00 (4.10.0) - FFmpeg GPU acceleration works:
1. Build FFmpeg following https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html#compiling-for-linux
2. Build OpenCV
```bash
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$HOME/opencv_install \
    -DBUILD_LIST=python3,core,imgproc,videoio \
    -DVIDEOIO_PLUGIN_LIST=ffmpeg \
    -DWITH_FFMPEG=ON \
    -S opencv -B opencv_build

cmake --build opencv_build -j$(nproc --all)
```
3. Test
```python
import os
os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "hwaccel;cuvid|video_codec;h264_cuvid|vsync;0"

import cv2 as cv

cap = cv.VideoCapture("video.mp4", cv.CAP_FFMPEG)
assert(cap.isOpened())
while True:
    has_frame, frame = cap.read()
    if not has_frame:
        break
```
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
|  0%   49C    P2              79W / 480W |    514MiB / 24564MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1082      G   /usr/lib/xorg/Xorg                           56MiB |
|    0   N/A  N/A      1165      G   /usr/bin/gnome-shell                         12MiB |
|    0   N/A  N/A    720428      C   python                                      428MiB |
+---------------------------------------------------------------------------------------+
```
