### ISSUE TITLE
Problems building OpenCV for Qt using cmake in Windows

### ISSUE THREAD

**Issue by mookixiao** [opencv/opencv#19872]
What I want is to build OpenCV for Qt using cmake in Windows, but there were some annoying problems. 

**The version info:**  
Qt 5.12.10
cmake 3.20.0
MinGW 7.3.0(Embeded in Qt)
OpenCV 4.5.2 and 3.5.14(I has tried two different versions, but got the similar errors)

**In cmake, I set the following opinions,** 
* WITH_QT***************************************checked
* WITH_OPENGL********************************checked
* WITH_IPP *************************************unchecked
* OPENCV_ENABLE_ALLOCATOR_STATA********unchecked
* Qt5Concurrent_DIR**D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5Concurrent
* Qt5Widgets_DIR******D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5Widgets
* Qt5Test_DIR**********D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5Test
* Qt5OpenGL_DIR******D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5OpenGL
* Qt5Gui_DIR************D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5Gui
* Qt5Core_DIR***********D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5Core
* Qt5_DIR****************D:/Qt/Qt5.12.10/5.12.10/mingw73_64/lib/cmake/Qt5

**I has run**

* configure
* generate

**successfully in cmake, but I met errors when I run `mingw32-make -j 8`, the error is**
> [ 42%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/merge.avx2.cpp.obj
> Building CXX object modules/core/CMakeFiles/opencv_core.dir/mean.avx2.cpp.obj
> [ 42%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/sum.avx2.cpp.obj
> [ 42%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
> gcc: error: Files\opencv-3.4.14\sources\modules\core\include: No such file or directory
> gcc: error: Files\opencv-3.4.14\opencv-build\modules\core: No such file or directory
> gcc: error: Files\opencv-3.4.14\sources\3rdparty\zlib: No such file or directory
> gcc: error: Files\opencv-3.4.14\opencv-build\3rdparty\zlib: No such file or directory
> gcc: error: Files\opencv-3.4.14\sources\3rdparty\include\opencl\1.2: No such file or directory
> gcc: error: Files\opencv-3.4.14\opencv-build: No such file or directory
> D:\Qt\Qt5.12.10\Tools\mingw730_64\bin\windres.exe: preprocessing failed.
> mingw32-make[2]: *** [modules\core\CMakeFiles\opencv_core.dir\build.make:1616: modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
> mingw32-make[2]: *** Waiting for unfinished jobs....
> [ 42%] Linking CXX static library ..\lib\libIlmImf.a
> [ 42%] Built target IlmImf
> mingw32-make[1]: *** [CMakeFiles\Makefile2:2004: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
> mingw32-make: *** [Makefile:165: all] Error 2
> PS D:\Program Files\opencv-3.4.14\opencv-build>
It says the cmd in build.make:1616 didn't run successfully, and I found the file, the content in 1616 line was `cd /d "D:\Program Files\opencv-3.4.14\opencv-build\modules\core" && D:\Qt\Qt5.12.10\Tools\mingw730_64\bin\windres.exe -O coff $(RC_DEFINES) $(RC_INCLUDES) $(RC_FLAGS) "D:\Program Files\opencv-3.4.14\opencv-build\modules\core\vs_version.rc" CMakeFiles\opencv_core.dir\vs_version.rc.obj`

I has searched a lot about this in Google, and I has tried the following two solutions: 
**1. uncheck OPENCV_ENABLE_ALLOCATOR_STATA**
**2. delete `$(RC_DEFINES) $(RC_INCLUDES) $(RC_FLAGS)` in build.make file, because someone said that they are not important. At first, it's useful, but after I met very many errors similar to this one in many build.make files in other pathes, I still try this solution, but sometimes it was useless. Finally, the process was terminated completely.** 
**Unfortunately, all of them were useless for me.**
I don't know much about cmake and makefile. Maybe that's why this error has been confusing me for two days. Hope you guys can help me, thank you so so so much. 

The tutorials I refered listed here, 
[https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows](https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows)
In Chinese: 
[https://blog.csdn.net/weixin_43763292/article/details/112975207](https://blog.csdn.net/weixin_43763292/article/details/112975207)

**Comment by alalek** [comment]
> `gcc: error: Files\opencv-3.4.14`
> `D:\Program Files\opencv-3.4.14`

Looks like the problem is related to space in paths.

---

Another workaround is disabling versions information: `cmake ... -DOPENCV_VS_VERSIONINFO_SKIP=ON`

---

Please note that MinGW is not officially supported or validated by OpenCV team (community support only).
Consider using MSVS on Windows.

**Comment by mookixiao** [comment]
> > `gcc: error: Files\opencv-3.4.14`
> > `D:\Program Files\opencv-3.4.14`
> 
> Looks like the problem is related to space in paths.
> 
> Another workaround is disabling versions information: `cmake ... -DOPENCV_VS_VERSIONINFO_SKIP=ON`
> 
> Please note that MinGW is not officially supported or validated by OpenCV team (community support only).
> Consider using MSVS on Windows.

Great! The space in path is really the reason.
I must note this after.
But there is another problem.
I have not searched it a lot yet. I will post it here. If you know how to solve it, it’s wonderful and I will also try my best to conquer it.
> [ 55%] Building CXX object
> modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/quadsubpix.cpp.obj
> CMakeFiles\opencv_highgui.dir/objects.a(window.cpp.obj):window.cpp:(.text$cvSetWindowProperty+0x27): undefined reference to cvSetPropVsync_W32(char const*, bool)' CMakeFiles\opencv_highgui.dir/objects.a(window.cpp.obj):window.cpp:(.text$cvGetWindowProperty+0x56): undefined reference to cvGetPropVsync_W32(char const*)’
> CMakeFiles\opencv_highgui.dir/objects.a(window.cpp.obj):window.cpp:(.text$_ZN2cv17setWindowPropertyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEid+0x5a): undefined reference to cvSetPropVsync_W32(char const*, bool)' CMakeFiles\opencv_highgui.dir/objects.a(window.cpp.obj):window.cpp:(.text$_ZN2cv17getWindowPropertyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0xc1): undefined reference to cvGetPropVsync_W32(char const*)’
> collect2.exe: error: ld returned 1 exit status
> mingw32-make[2]: *** [modules\highgui\CMakeFiles\opencv_highgui.dir\build.make:222: bin/libopencv_highgui452.dll] Error 1
> mingw32-make[1]: *** [CMakeFiles\Makefile2:2666: modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
> mingw32-make[1]: *** Waiting for unfinished jobs…

**Comment by alalek** [comment]
> cvSetPropVsync_W32

is discussed here: #19870 (feel free to validate proposed fix there)

**Comment by mookixiao** [comment]
> > cvSetPropVsync_W32
> 
> is discussed here: #19870 (feel free to validate proposed fix there)

The condition in this issue is the same with me.  
I make it. Thank you so much!

**Comment by Hezhexi2002** [comment]
> > `gcc: error: Files\opencv-3.4.14`
> > `D:\Program Files\opencv-3.4.14`
> 
> Looks like the problem is related to space in paths.
> 
> Another workaround is disabling versions information: `cmake ... -DOPENCV_VS_VERSIONINFO_SKIP=ON`
> 
> Please note that MinGW is not officially supported or validated by OpenCV team (community support only).
> Consider using MSVS on Windows.

So how can I do this  `cmake ... -DOPENCV_VS_VERSIONINFO_SKIP=ON` in the cmake gui? I'm using cmake in windows10
