### ISSUE TITLE
 error: ‘CV_FONT_HERSHEY_SIMPLEX’ was not declared in this scope

### ISSUE THREAD

**Issue by panmengjia** [opencv/opencv#19871]
### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform =>ubuntu x64
- Compiler =>g++ 7.5
  
### Detailed description

**When I compile the program, I encounter the following problems:**

```bash
/home/pmj/Desktop/loam/project/VINS-Mono-master_ws/src/VINS-Mono-master/pose_graph/src/pose_graph.cpp:312:97:
         putText(compressed_image, "feature_num:" + to_string(feature_num), cv::Point2f(10, 10), CV_FONT_HERSHEY_SIMPLEX, 0.4, cv::Scalar(255));
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
/home/pmj/Desktop/loam/project/VINS-Mono-master_ws/src/VINS-Mono-master/pose_graph/src/pose_graph.cpp:312:97: note: suggested alternative: ‘CV_IS_SEQ_SIMPLE’
         putText(compressed_image, "feature_num:" + to_string(feature_num), cv::Point2f(10, 10), CV_FONT_HERSHEY_SIMPLEX, 0.4, cv::Scalar(255));
```

**My configuration in CMakeList.txt is as follows:**

```bash
find_package(OpenCV 3.0 REQUIRED)

target_link_libraries(vins_estimator ${catkin_LIBRARIES} ${OpenCV_LIBS} ${CERES_LIBRARIES}) 
```

**I don't know how to solve the above problem. Is it because of the incompatibility of version 3.4.2 of opencv, or what?**

**Comment by berak** [comment]
please do not use the old, deprecated c-api flags with `CV_` prefix, but `cv::FONT_HERSHEY_SIMPLEX`

**Comment by alalek** [comment]
C API from OpenCV 1.0 is deprecated since OpenCV 2.4.
OpenCV 3.0 and later starting removal of some C API parts without further notices.

**Comment by panmengjia** [comment]
Thanks!
