### ISSUE TITLE
Sharing useful code

### ISSUE THREAD

**Issue by rinogo** [opencv/opencv#19889]
I wrote a little [prototyping utility function (quick trackbars)](https://gist.github.com/rinogo/d528d3b2b03d6864def1cb5117db005e) that could be useful to others - where is the best place to add a link to it?

**Comment by dkurt** [comment]
Hi! OpenCV does not have a list of external projects. Gist is good way to share your experience (at least it's well trackable by search engines).

Due there is no bug report or feature request, let me close it. Please use a forum for future discussions.
