### ISSUE TITLE
A bug on Hand-Eye Calibration (R. Horaud and F. Dornaika)?

### ISSUE THREAD

**Issue by YurongYou** [opencv/opencv#19897]
In the implementation of Hand-Eye Calibration (R. Horaud and F. Dornaika) (https://github.com/opencv/opencv/blob/1f726e81f91746e16f4a6110681658f8709e7dd2/modules/calib3d/src/calibration_handeye.cpp#L436), it seems [here](https://github.com/opencv/opencv/blob/1f726e81f91746e16f4a6110681658f8709e7dd2/modules/calib3d/src/calibration_handeye.cpp#L458) and [here](https://github.com/opencv/opencv/blob/1f726e81f91746e16f4a6110681658f8709e7dd2/modules/calib3d/src/calibration_handeye.cpp#L470) does not follow the original paper exactly. The r0 here should be zero and [rx, ry, rz] should be the rotation axis.

ref: 
http://math.loyola.edu/~mili/Calibration/AXXB/horaud.m the implementation in matlab
https://hal.inria.fr/inria-00590039/document the paper

**Comment by catree** [comment]
If I remember/have correctly understood, the Matlab implementation works also but is slightly different from the paper. The code should correctly follow the [paper](https://hal.inria.fr/inria-00590039/document):

![image](https://user-images.githubusercontent.com/8229425/114558150-ad20b380-9c6a-11eb-8c11-33948ecb94fc.png)

https://github.com/opencv/opencv/blob/1f726e81f91746e16f4a6110681658f8709e7dd2/modules/calib3d/src/calibration_handeye.cpp#L457-L461

https://github.com/opencv/opencv/blob/1f726e81f91746e16f4a6110681658f8709e7dd2/modules/calib3d/src/calibration_handeye.cpp#L469-L473

**Comment by YurongYou** [comment]
I think the formula for Q and W is correct, but the v_i' and v_i here should be purely imaginary quaternions, which is the rotation axis of R_A and R_B?
<img width="637" alt="image" src="https://user-images.githubusercontent.com/13609397/114559614-ed1b7280-9c39-11eb-86f1-cdcd77c06183.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/13609397/114559645-f4db1700-9c39-11eb-95c7-3b692149ef3e.png">

**Comment by YurongYou** [comment]
Hmm empirically I found the two implementations yield different A matrices but these two matrices have the same eigen vector for the smallest eigen value:

```python
from pyquaternion import Quaternion
import numpy as np

R_A = []
R_B = []
T_A = []
T_B = []

# R_A R_X = R_X R_B
R_X = Quaternion(axis=(1,1,1), degrees=60).rotation_matrix
t_X = np.array([120,23,31])
for i in range(100):
    R_B.append(Quaternion.random().rotation_matrix)
    R_A.append(R_X @ R_B[-1] @ R_X.T)
    T_B.append(np.random.rand(3) * 100)
    T_A.append(R_X @ T_B[-1] - (R_A[-1] - np.eye(3)) @ t_X)
N = 100
AA = np.zeros((4,4))
for i in range(N):
    qA = Quaternion(matrix=R_A[i]).elements
    qA[0] = 0
    qA /= np.linalg.norm(qA)
    qB = Quaternion(matrix=R_B[i]).elements
    qB[0] = 0
    qB /= np.linalg.norm(qB)
    _tmp = Qr(qA) - Wr(qB)
    AA += _tmp.T @ _tmp
q = np.linalg.eig(AA)
print(q[0])
print(q[1])
print()

N = 100
AA = np.zeros((4,4))
for i in range(N):
    qA = Quaternion(matrix=R_A[i]).elements
    qB = Quaternion(matrix=R_B[i]).elements
    _tmp = Qr(qA) - Wr(qB)
    AA += _tmp.T @ _tmp
q = np.linalg.eig(AA)
print(q[0])
print(q[1])
```
The outputs:
```
[ 72.         183.2493293  257.80788626 286.94278443]
[[ 0.8660254   0.48983083  0.09613599 -0.02869897]
 [ 0.28867513 -0.56938996  0.0718906  -0.76635076]
 [ 0.28867513 -0.3260179  -0.85863365  0.27042051]
 [ 0.28867513 -0.57408463  0.49833509  0.58202718]]

[ 72.         137.35077138 209.6559876  230.45733417]
[[ 0.8660254   0.49087655  0.09149395 -0.02586635]
 [ 0.28867513 -0.59991688  0.29209316 -0.6866207 ]
 [ 0.28867513 -0.34063243 -0.89394568  0.03869539]
 [ 0.28867513 -0.53208034  0.32737068  0.72552437]]
```

**Comment by YurongYou** [comment]
hmmm I also tested them on the real data (with noise), and they yielded different results

**Comment by catree** [comment]
@YurongYou 

My implementation should strictly follow the [paper](https://hal.inria.fr/inria-00590039/document).
You would have to ask the author of the Matlab implementation why they have used a slightly different representation.

**Comment by catree** [comment]
@YurongYou 

What is the status of this? 
I believe there is no issue here except the different formulations at some point between the two approaches.

**Comment by catree** [comment]
@YurongYou 

> The implementation in opencv works well on the data I use.

That is a good thing to hear :)

What was the answer of the Matlab implementation author?
