### ISSUE TITLE
Can not detect cuda when cross compile

### ISSUE THREAD

**Issue by darkgirl** [opencv/opencv#19919]
sys: ubuntu18.04 x86
cuda: cuda-cross-aarch64-10-2
cmake 3.10

when i use -DCMAKE_TOOLCHAIN_FILE=../platforms/linux/aarch64-gnu.toolchain.cmake 
the cmake can not find cuda sdk

**Comment by asmorkalov** [comment]
Please provide more details: cuda version, full CMake command line and CMakeCache.txt after cmake configuration.

**Comment by darkgirl** [comment]
> Please provide more details: cuda version, full CMake command line and CMakeCache.txt after cmake configuration.

cuda version 10.2, i am using cuda cross compiler cuda-cross-aarch64-10-2
CMake: 
cmake --verbose=1 -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/opt/opencv -DWITH_CUDA=ON -DENABLE_FAST_MATH=1 -DWITH_CUBLAS=1 -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -DBUILD_EXAMPLES=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DCMAKE_TOOLCHAIN_FILE=../platforms/linux/aarch64-gnu.toolchain.cmake -DCMAKE_SYSROOT=~/workspace/rootfs ..

but if i add the follow parameter
 -DCUDA_TOOLKIT_TARGET_DIR=~/workspace/rootfs/usr/local/cuda 
it can find cuda, but can not find CUDA_cublas_LIBRARY-NOTFOUND

thanks.

**Comment by darkgirl** [comment]
> Please provide more details: cuda version, full CMake command line and CMakeCache.txt after cmake configuration.

[CMakeCache.txt](https://github.com/opencv/opencv/files/6328916/CMakeCache.txt)
