### ISSUE TITLE
Onnx cannot run with cuda

### ISSUE THREAD

**Issue by Noobly0715** [opencv/opencv#19929]
Hi, I'm trying to use onnx with opencv
I can use the CPU but not the GPU
it said 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1) /home/ubuntu/opencv-4.5.1/modules/dnn/src/layers/../cuda4dnn/csl/tensor.hpp:210: error: (-215:Assertion failed) start != end in function 'resize'

Here's the code

##### Init
    net_= readNetFromONNX(this->module_path_);
    if (use_gpu_ == true) {
        net_.setPreferableTarget(DNN_TARGET_CUDA);
        net_.setPreferableBackend(DNN_BACKEND_CUDA);
    }

##### recognize
    cv::Mat out;
    out = Mat(1, 2048, CV_32FC1);
    out = 0;
    Mat img = origin.clone();
    Mat inputBlob = blobFromImage(img, 1, Size(256, 256), Scalar(0, 0, 0), true, false);
    net_.setInput(inputBlob);
    auto feature_mat = reid_net_.forward();
    feature_mat.copyTo(out);

When the use_gpu_ equal false, it can run.
What should I do next, 
thx :-)

##### System information
- OpenCV => 4.5.1
- Operating System / Platform => ubuntu1~18.04 / x86_64
- Compiler => g++ 7.5.0

**Comment by YashasSamaga** [comment]
Please provide the resize layer configuration that caused the error or please share the ONNX model.

**Comment by Noobly0715** [comment]
> Please provide the resize layer configuration that caused the error or please share the ONNX model.
> 
> NOTE: #19223 completed support for resize layer. Can you please check with 4.5.2?


hi, here's the module, 
**https://github.com/Noobly0715/onnxerror**
I was check with 4.5.2
I was built like this
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/home/ubuntu/opencv -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.5.2/modules -DWITH_CUDA=1 -DENABLE_FAST_MATH=1 -DCUDA_FAST_MATH=1 -DWITH_CUBLAS=1 -DOPENCV_GENERATE_PKGCONFIG=1 -DBUILD_opencv_hdf=OFF -DCUDA_ARCH_BIN="7.0" ..
It's same error, I can use CPU but not GPU

**Comment by YashasSamaga** [comment]
Sorry, the problem is not with resize layer (as I suggested earlier). The issue is in InnerProductLayer.

The assertion failure is because an empty constant weights matrix is being passed to the layer constructor. Layer 543 multiplies two tensors. Only constant weight matrices are currently supported in the CUDA backend.

**Comment by Noobly0715** [comment]
> Sorry, the problem is not with resize layer (as I suggested earlier). I have reproduced the problem. The issue is in InnerProductLayer.
> 
> The assertion failure is because an empty constant weights matrix is being passed to the layer constructor. Layer 543 multiplies two tensors (not constant weights). Only constant weight matrices are currently supported in the CUDA backend. I'll try to add this feature this week.

thx :-)
