### ISSUE TITLE
[C++20][MSVC] test_houghcircles.cpp(59,27): error C2666: 'cv::format': 2 overloads have similar conversions

### ISSUE THREAD

**Issue by QuellaZhang** [opencv/opencv#19941]
Hi all,

The MSVC team adds an implementation of <format> with https://github.com/microsoft/STL/pull/1821, and the format are ambiguous when building OpneCV on MSVC, can you look at this? Thanks. This issue was found under /std:c++latest mode.

**repro steps:**

1. open VS2019 x64 tools command
2. git clone https://github.com/opencv/opencv F:\gitP\opencv\opencv
3. git clone https://github.com/opencv/opencv_extra :\gitP\opencv\opencv_extra
4. mkdir F:\gitP\opencv\opencv\build_amd64
5. cd F:\gitP\opencv\opencv\build_amd64
6. set _CL_=/D_HAS_AUTO_PTR_ETC=1 /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D_HAS_TR1_NAMESPACE=1  /wd5033 /D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING -std:c++latest
7. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DWITH_IPP=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DWITH_OPENCL=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF ..
8. msbuild /m /p:Platform=x64 /p:Configuration=Release OpenCV.sln /t:Rebuild /p:BuildInParallel=true

**Build log:** [build.log](https://github.com/opencv/opencv/files/6342202/build.log)

**Error info(Please check the complete error message in the log):**
F:\gitP\opencv\opencv\samples\cpp\select3dobj.cpp(493,68): error C2666: 'cv::format': 2 overloads have similar conversions 
F:\gitP\opencv\opencv\samples\cpp\tutorial_code\calib3d\camera_calibration\camera_calibration.cpp(405,83): error C2666: 'cv::format': 2 overloads have similar conversions
F:\gitP\opencv\opencv\samples\cpp\tutorial_code\calib3d\camera_calibration\camera_calibration.cpp(407,76): error C2666: 'cv::format': 2 overloads have similar conversions
F:\gitP\opencv\opencv\samples\cpp\tutorial_code\calib3d\real_time_pose_estimation\src\main_detection.cpp(364,103): error C2666: 'cv::format': 2 overloads have similar conversions

**Comment by alalek** [comment]
Thank you for the report!

Looks like this problem is triggered through

```
using namespace std;
using namespace cv;
```

and using `format()` without namespace specifier:

https://github.com/opencv/opencv/blob/a0ff55db7de21e505b44db3889f7c115ca671bfd/samples/cpp/select3dobj.cpp#L493

---

Could you please try to replace `format` => `cv::format()`? (we don't have configured mentioned build environment yet to check that problem)

If it works, it would be nice if you can prepare PR with required changes.

**Comment by QuellaZhang** [comment]
@alalek thanks, verify it works, send PR https://github.com/opencv/opencv/issues/19941, please help approve.
