### ISSUE TITLE
Documentation discepancy between `imshow`'s docs and its implementation.

### ISSUE THREAD

**Issue by dan-masek** [opencv/opencv#19947]
This issue appears to affect 4.x only.

The [documentation of `imshow`](https://docs.opencv.org/master/d7/dfc/group__highgui.html#ga453d42fe4cb60e5723281a89973ee563) claims:

> If the image is 16-bit unsigned or 32-bit integer, the pixels are divided by 256. 

That would suggest that it supports displaying of arrays of `CV_32S`. However `convertToShow` (used internally) [contains](https://github.com/opencv/opencv/blob/master/modules/highgui/src/precomp.hpp#L140) the following assert:

`CV_Assert(src_depth != CV_16F && src_depth != CV_32S);`

and predictably any attempts to display `CV_32S` fail due to this.

IMHO the offending line in docs should be changed to reflect this, and the subset of supported datatypes should be explicitly mentioned there for clarity.

**Comment by alalek** [comment]
Thank you for the report!

Documentation was not updated after 4.0 breaking changes in highgui module (#13060 #13264).
Need to update this part of documentation.
