### ISSUE TITLE
cv2.destroyAllWindows() won't work without libgtk2.0-dev ?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#19978]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Ubuntu 20.04.2 LTS 64 Bit
- Compiler => gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0

##### Detailed description

I believe it's the time to shift from **libgtk2.0-dev** to **libgtk3.0-dev**. I prefer building **OpenCV** with **libgtk3.0-dev** **ONLY** without **libgtk2.0-dev**. 

##### Steps to reproduce

The Python code:
    ```
      cv2.destroyAllWindows()
    ```
or
    ```
      cv2.destroyWindow(window_title)
    ```

Just wonder if there is **ANY** way to close windows without building OpenCV with **libgtk2.0-dev** ?

Cheers

**Comment by rogday** [comment]
I can't seem to reproduce your issue. I have only libgtk-3-dev installed and it builds and runs fine with `-DWITH_GTK=ON` (not `-DWITH_GTK_2_X=ON`). Can share the output of `getBuildInformation()` and provide MWE?. Section about GUI should look something like this:
```
--   GUI: 
--     GTK+:                        YES (ver 3.24.25)
--       GThread :                  YES (ver 2.68.1)
--       GtkGlExt:                  NO
--     VTK support:                 YES (ver 9.0.1)
```
