### ISSUE TITLE
[Suggestion] Check if it is file within cv2.VideoCapture(path)

### ISSUE THREAD

**Issue by talregev** [opencv/opencv#19997]
```python
import cv2

# Press the green button in the gutter to run the script.
if __name__ == '__main__':

    path = r'D:\Android\android-sdk-windows\extras\android\support\samples\Support4Demos\res\raw'
    cap = cv2.VideoCapture(path)
```

 If I run this program, I get this error because I enter a path instead of file:
 
```cpp
[ERROR:0] global D:\src\opencv-4.5.2\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.2) D:\src\opencv-4.5.2\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): D:\Android\android-sdk-windows\extras\android\support\samples\Support4Demos\res\raw in function 'cv::icvExtractPattern'
```

suggest to check within `cv2.VideoCapture(path)` function if file exist. 
if python: `os.path.isfile(path)`

**Comment by mshabunin** [comment]
`VideoCapture` supports many different things as an input, it can be filename, camera device, network resource, GStreamer pipeline. So file existence check will not work here.

**Comment by talregev** [comment]
ok. Can we think a better error msg if I enter a directory? 
If os.path.isdir(path) then it sure be an error? What do you think?

**Comment by mshabunin** [comment]
We can not check it due to nature of `VideoCapture`, it does not handle input but passes it down to underlying backends in predetremined order (https://docs.opencv.org/3.4/d0/da7/videoio_overview.html). I can imagine situations where one of these backends accepts a directory as an input (e.g. folder with images).

**Comment by talregev** [comment]
I send it an folder with images, and it didn't read.
Also it was only a suggestion because I don't `VideoCapture` as deep as you do.
If there is any possible to correct the error msg that will be more clear and save time in future for other people that will be great.
If you can take a look on all possible backend and see if it can made such request. Thank you for your time and effor to explain me better on opencv and `VideoCapture`.

**Comment by xiang-zhe** [comment]
i got a similar problem, but a little different, 
for python code, input =0 or input ="test.avi" both worked;
but for execute file by pyinstaller, only input = 0 work, when input is a video path not worked, 
i don't know is a problem of  cv or pyinstaller, https://github.com/pyinstaller/pyinstaller/discussions/6679; only suggestions, thank you @talregev @mshabunin
