### ISSUE TITLE
Partial decompression support

### ISSUE THREAD

**Issue by Glandos** [opencv/opencv#20009]
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
I have a current use case with reading a lot of JPEG files, defining a ROI inside to find differences. One bottleneck is the decompression of the whole image, while I only need a subset of it.

libjpeg-turbo support [skipping some data to get faster decompression](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/libjpeg.txt) using `jpeg_skip_scanlines` and `jpeg_crop_scanline`. Currently, the API for `imread` and `imdecode` makes it hard to implement, but my use case will greatly benefit this kind of feature.

Is it a wanted feature? Or is it a niche and we should be rely on an hand made decoder?

**Comment by alalek** [comment]
OpenCV is not a Media I/O library. There are several other specialized frameworks which can do such tasks better.
Current OpenCV I/O API is generic for different backends, it is not targeted for features from some single library, like libjpeg.

Consider using libjpeg in your application directly for these tasks instead.

**Comment by Glandos** [comment]
OK, I expected such answer, and it's nice to have it quickly. I will close this, and it can be useful for other people interested in the feature.
