### ISSUE TITLE
error: macro "LU" passed 6 arguments, but takes just 1

### ISSUE THREAD

**Issue by dbdxnuliba** [opencv/opencv#20016]
/usr/local/include/opencv2/core/matx.hpp:490:58: error: macro "LU" passed 6 arguments, but takes just 1
         double p = LU(temp.val, m*sizeof(_Tp), m, 0, 0, 0);

![image](https://user-images.githubusercontent.com/13350158/116690648-44686380-a9ec-11eb-967f-44eb3b7e1732.png)

**Comment by alalek** [comment]
> macro "LU"

Some external software defined LU macro. Use `#undef LU`.
This is configuration error and can't be fixed by OpenCV.
