### ISSUE TITLE
Exception Thrown: assert(args.dataset == "Hand")

### ISSUE THREAD

**Issue by Satientas1518** [opencv/opencv#20029]
Dear Sir/Madam,

I am writing in as there is currently an error when I tried to compile and run the code. The error is as follows:

--
  Message=
  Source=C:\Users\Justi\source\repos\OpenPose\OpenPose\OpenPose.py
  StackTrace:
  File "C:\Users\Justi\source\repos\OpenPose\OpenPose\OpenPose.py", line 43, in <module> (Current frame)
    assert(args.dataset == "Hand")
--

May I kindly seek your help on how I might be able to resolve this? Thank you. J

Best regards,
Justin

**Comment by berak** [comment]
hello, you've reached the opencv **library bug tracker**

since this isn't a bug, more a usage problem (you did not specify `--dataset`), 
please kindly close this issue, and reask on https://forum.opencv.org/ , where we can help you much better, thank you.

**Comment by Satientas1518** [comment]
Hi Berak,

Sure thing, so sorry for any trouble caused. Should I just create a New Topic as shown in the image or is there some other place I should head to for usage problems?

![image](https://user-images.githubusercontent.com/80824910/117016425-45b7ca00-ad25-11eb-8bae-87dd2f730a56.png)

Thank you. J

Cheers,
Justin

**Comment by berak** [comment]
> Should I just create a New Topic as shown in the image

yes, please. and dont feel sorry.

**Comment by Satientas1518** [comment]
Thanks for the help Berak. J

I have posted the thread as "Exception Thrown: assert(args.dataset == “Hand”) Using OpenPose" in OpenCV. Hope to be able to get some guidance regarding the usage for OpenPose there.

Cheers,
Justin

**Comment by berak** [comment]
apart from that,

    assert(args.dataset == “Hand”)

is misleading. 'Hand' is only the last, fallback option, not the only or preferred choice
