### ISSUE TITLE
Add Visual Studio 2019 (vc16) libs to the Windows installer

### ISSUE THREAD

**Issue by shoelzer** [opencv/opencv#20048]
The Windows installer (currently 4.5.2) includes libraries built for Visual Studio 2015 (vc14) and Visual Studio 2017 (vc15). Please update the installer to add libraries for Visual Studio 2019 (vc16).

**Comment by mshabunin** [comment]
VS 2019 should work with libraries built for VS 2015+, code in the cmake package should handle binaries selection. Please make sure you are doing everything correct and provide more detailed description of the problem if any.

**Comment by shoelzer** [comment]
I’m not having a problem. I just found it strange and slightly confusing that libraries for VS 2015 and 2017 were included but not for 2019.

I believe that VS 2017 also works with 2015 libraries, so why include the 2017 libraries? Why not just the 2015 library which is forward-compatible with everything?

**Comment by alalek** [comment]
OpenCV 5.x Windows package will use MSVS 2019: http://pullrequest.opencv.org/buildbot/waterfall?tag=pack-next

P.S. MSVS 2017 has initial support for AVX512 instruction set.
