### ISSUE TITLE
Why can't raspberry pie save MP4 format

### ISSUE THREAD

**Issue by bbhxwl** [opencv/opencv#20059]
Why can't raspberry pie save MP4 format

OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

**Comment by roccopietrini** [comment]
It's a codec issue, does not depend on OpenCV but since I faced the same issue I want to help. I save in h264 format and then convert to mp4 using MP4box as described [here](https://www.raspberrypi.org/documentation/usage/camera/raspicam/raspivid.md)
