### ISSUE TITLE
The same img showed by imshow() and saved by imwrite() is quite different.

### ISSUE THREAD

**Issue by chenghuaWang** [opencv/opencv#20060]
##### System information (version)

- OpenCV => 4.0.1 
- Python => 3.8.3
- Operating System / Platform => Windows 64 Bit

##### Detailed description

I taken an original pic (size: 3024 * 4032) and carried out the following operation:
-> draw some points on this pic
-> crop this pic to get a H * H size img
-> Rotate the img
-> resize this img to 192*192

I use ```imshow()``` function to show img, and ```imwrite()``` to save the same img, But the picture get from these two functions is quite different.

through ```imshow()``` method ,i get a picture of mosaics.But if i use ```imwrite()``` to save this img, and use the Image Viewer to view this image ,this saved image is clear. I wonder what is the reason for this

**Comment by sturkmen72** [comment]
imgShow() and imgWrite() there is no such named functions in OpenCV

**Comment by chenghuaWang** [comment]
> imgShow() and imgWrite() there is no such named functions in OpenCV

My fault. thanks for reminding, The issues has been update.
