### ISSUE TITLE
ORB Demo code errors out with cv2.error: Unknown C++ exception from OpenCV code

### ISSUE THREAD

**Issue by WurmD** [opencv/opencv#20081]
##### System information (version)

- opencv-python => 4.5.2.52
- Operating System / Platform => Windows 10

##### Detailed description

ORB Demo code at https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_orb/py_orb.html 

	import numpy as np
	import cv2
	from matplotlib import pyplot as plt

	img = cv2.imread('simple.jpg',0)

	# Initiate STAR detector
	orb = cv2.ORB()

	# find the keypoints with ORB
	kp = orb.detect(img,None)

	# compute the descriptors with ORB
	kp, des = orb.compute(img, kp)

	# draw only keypoints location,not size and orientation
	img2 = cv2.drawKeypoints(img,kp,color=(0,255,0), flags=0)
	plt.imshow(img2),plt.show()

at `kp = orb.detect(img,None)` 
 - in Python3.6 errors out with `[WinError 10054] An existing connection was forcibly closed by the remote host` 
 - in Python3.8 errors out with `cv2.error: Unknown C++ exception from OpenCV code`

**Notes:** 
- In Python 3.6, running in the terminal, or running in the debugger, simply exits the script with no error. Only when stopping at `kp = orb.detect(img,None)` in the debugger and running that line in the debugger does the error appear `[WinError 10054] An existing connection was forcibly closed by the remote host`
- In Python 3.8, running in terminal or the debugger gives the error `cv2.error: Unknown C++ exception from OpenCV code`
- Stackoverflow: https://stackoverflow.com/questions/67526521/orb-demo-code-errors-out-with-cv2-error-unknown-c-exception-from-opencv-code
- opencv-python issue: https://github.com/opencv/opencv-python/issues/486

##### Steps to reproduce

Run demo code from https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_orb/py_orb.html

**Comment by alalek** [comment]
You trying to use external tutorials (it is outdated, created in 2013).
Use OpenCV documentation instead: https://docs.opencv.org/master/d1/d89/tutorial_py_orb.html
