### ISSUE TITLE
Could NOT find PythonInterp,Could NOT find OpenJPEG,Could NOT find Atlas,Could NOT find JNI

### ISSUE THREAD

**Issue by liguoyu666** [opencv/opencv#20084]
When I build opencv3.4, the error is as follows,  and specifing the python version is not useful. "-D PYTHON2_INCLUDE_DIR=/usr/include/python2.7"

`(base) lgy@lgy:~/tools/opencv/build$ cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
-- Detected processor: x86_64
-- Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "3.2" (found /home/bupt1014/anaconda3/envs/py35/bin/python3)
-- Looking for ccache - not found
-- Found ZLIB: /home/lgy/anaconda3/lib/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
Cleaning INTERNAL cached variable: WEBP_LIBRARY
Cleaning INTERNAL cached variable: WEBP_INCLUDE_DIR
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1). OpenJPEG will be built from sources
-- OpenJPEG: VERSION = 2.4.0, BUILD = opencv-4.5.2-dev-openjp2-2.4.0
-- OpenJPEG libraries will be built from sources: libopenjp2 (version "2.4.0")
-- Found ZLIB: /home/lgy/anaconda3/lib/libz.so (found version "1.2.11") 
-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
-- libva: missing va.h header (VA_INCLUDE_DIR)
-- Found TBB (env): /usr/lib/x86_64-linux-gnu/libtbb.so
-- CUDA detected: 10.1
-- CUDA: Using CUDA_ARCH_BIN=3.0;3.5;3.7;5.0;5.2;6.0;6.1;7.0;7.5
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-D_FORCE_INLINES
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include/openblas
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/lib/libopenblas.so
CMake Warning at cmake/OpenCVFindLAPACK.cmake:29 (message):
  LAPACK(OpenBLAS): CBLAS/LAPACK headers are not found in
  '/usr/include/openblas'
Call Stack (most recent call first):
  cmake/OpenCVFindLAPACK.cmake:139 (ocv_lapack_check)
  CMakeLists.txt:720 (include)

-- Could NOT find Atlas (missing:  Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Found apache ant: /usr/bin/ant (1.9.6)
-- Could NOT find JNI (missing:  JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
CMake Error at cmake/OpenCVModule.cmake:274 (message):
  No modules has been found: /home/lgy/tools/opencv/opencv_contrib/modules
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:356 (_glob_locations)
  modules/CMakeLists.txt:7 (ocv_glob_modules)

-- OpenCV Python: during development append to PYTHONPATH: /home/lgy/tools/opencv/build/python_loader
CMake Error at modules/core/CMakeLists.txt:52 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib

-- Configuring incomplete, errors occurred!
See also "/home/lgy/tools/opencv/build/CMakeFiles/CMakeOutput.log".
`

**Comment by berak** [comment]
hello, @liguoyu666 , can you maybe ask again on https://forum.opencv.org/ (and close this) ?

we can help you much better from there

**Comment by CSharperMantle** [comment]
These lines of the output are supposed to be crucial but not the ones given by @liguoyu666 in the title.

```plain-text
CMake Error at cmake/OpenCVModule.cmake:274 (message):
No modules has been found: /home/lgy/tools/opencv/opencv_contrib/modules

CMake Error at modules/core/CMakeLists.txt:52 (message):
CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
repository: https://github.com/opencv/opencv_contrib
```
