### ISSUE TITLE
drawMatches lines not visible in larger images

### ISSUE THREAD

**Issue by WurmD** [opencv/opencv#20095]
`drawMatches` https://docs.opencv.org/master/d4/d5d/group__features2d__draw.html#gad8f463ccaf0dc6f61083abd8717c261a draws 1 pixel thick lines between matching keypoints in two side-by-side images, this becomes invisible for larger images.

Please add a thickness argument, and base the default thickness on the size of the image.

##### System information (version)
- OpenCV => 4.2
  
##### Steps to reproduce

    ```.py
    left_image = cv.imread('images/IMG_6769.jpg',cv.IMREAD_COLOR)
    right_image = cv.imread('images/IMG_6770.jpg',cv.IMREAD_COLOR)
    width = right_image.shape[1]
    height = right_image.shape[0]
    orb = cv.ORB_create(nfeatures=1500)
    kp1, des1 = orb.detectAndCompute(left_image,None)
    kp2, des2 = orb.detectAndCompute(right_image,None)
    bf = cv.BFMatcher(cv.NORM_HAMMING, crossCheck=True)
    matches = bf.match(des1,des2)

    bestmatches_diff_to_median_disparity_wise = get_best_matches_difference_to_median_disparity_wise(matches, kp1, kp2)
    largest_trapeze_matches = get_4_matches_that_form_largest_trapeze(bestmatches_diff_to_median_disparity_wise, kp1)
    destination_left_points, source_right_points = from_matches_to_2_arrays_of_points(largest_trapeze_matches, kp1, kp2)

    img3 = cv.drawMatches(left_image,kp1,right_image,kp2,largest_trapeze_matches,None,flags=cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS) # cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
    plt.imshow(img3),plt.show()
    ```

##### Issue submission checklist

![IMG_6769](https://user-images.githubusercontent.com/5755747/118366992-71924580-b598-11eb-9856-f0b803c76d83.jpg)
![IMG_6770](https://user-images.githubusercontent.com/5755747/118366993-73f49f80-b598-11eb-8a12-e12b46843280.jpg)

![Failure to see lines](https://user-images.githubusercontent.com/5755747/118366457-36901200-b598-11eb-9872-b41c490fc60e.PNG)
![Barely visible in max zoom](https://user-images.githubusercontent.com/5755747/118366455-35f77b80-b598-11eb-9bfe-3736b9b7b37f.PNG)

**Comment by alalek** [comment]
> Please add a thickness argument,

This makes sense.

> and base the default thickness on the size of the image.

This should not happen, because source of your problem is resizing during `imshow()` call. `drawMatches()` just doesn't know these resizing parameters.

**Comment by alalek** [comment]
Ignore `OpenCV CN` builds - they are unstable (infrastructure-related issues) and "optional" (not required) for now.

**Comment by jhandke** [comment]
The same problem occurs when trying to draw matches with the `drawMatchesKnn()` function. If I understand that correctly, [this](https://github.com/opencv/opencv/blob/84dc1e93c52944d551f6468ef3da9f918a9ccf9c/modules/features2d/include/opencv2/features2d.hpp#L1411) function has to be overloaded with the additional parameter as well.
Since I am new to the OpenCV code base: Is there anything else that needs to be changed/added?
