### ISSUE TITLE
samples/python/kalman.py is not constant rotation as documented

### ISSUE THREAD

**Issue by drf5n** [opencv/opencv#20091]
The comments and documentation in samples/python/kalman.py do not match the behavior of the program.

This line prints that the speed is constant, but it is clear from running the program that the speed is not constant.

https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/python/kalman.py#L4

Because of:

https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/python/kalman.py#L41
and
https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/python/kalman.py#L85-L86

The state variable holds the angle and speed, which at each step is modified by the process transition matrix plus the process noise.  Since the process noise is added onto the state variable for the speed of rotation, the speed is not constant -- it is a random walk.

The random walk in speed (and location) is more visually interesting than tracking a constant rotation, but it isn't required by a Kalman filter and doesn't match the documentation.

Kalman filters can be a confusing topic, and the inconsistent documentation doesn't help.

I suggest either making the process noise zero to match the documentation or replacing the "Rotation speed is constant. " with something like:

Rotation speed is a random walk from N(0,0.1 ), integrating N(0,1e-5) process noise.

If you run the program it is clear that the rotation is not constant. 

Another couple issues:
   * Why plot the crosses underneath the lines?  The thick lines overwrite the points and cover them up.  
   * Why not use/plot the kalman.statePost?  The utility of a Kalman filter is to improve the estimate of the current state based on the recent measurement and to improve the estimate of the next state.  This demo doesn't use the corrected measurement.

**Comment by drf5n** [comment]
Additionally, the sample.py code at behaves different from the sample.cpp code because the measurement matrices differ.  Compare: 

https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/python/kalman.py#L40 

to 

https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/cpp/kalman.cpp#L45


As is, the 1x2 matrix of ones, cross multiplied by the 2x1 state vector sums the angle and the speed together into a speed-biased scalar measure of 'angle'.

To align the samples/python/kalman.py behavior with samples/cpp/kalman.cpp,   
 
https://github.com/opencv/opencv/blob/a604d44d06841565f03da03d8df3124fca639ca3/samples/python/kalman.py#L40  

should be changed to:

        kalman.measurementMatrix = 1. * np.eye(2)

 ...to match the sample.cpp behavior.

**Comment by drf5n** [comment]
Anyway, my take on the python code is below.   It:

* uses a constant speed of rotation of pi/6/frame, 
* Simplifies some of the noise and initial estimate processes
* de-biases the measurement, 
* thins the lines and puts the crosses on top, 
* persists and fades the objects
* reports the pre- and post-measurement state estimates,
* conditionally reports the Kalman filter variables, 
* slows down the processing during reporting
* forecasts and plots the one-frame-ahead location. 

I think it does a pretty good job of visually demonstrating the Kalman filter process converging on a noisy process, and correcting noisy measurements.  The opencv Kalman filter tool is pretty flexible, but the packaged demos don't clearly showing what it's doing.

![image](https://user-images.githubusercontent.com/2236516/118552148-8dc6eb80-b72c-11eb-8a90-cae2c4981cd1.png)


```
#!/usr/bin/env python
"""
   Tracking of rotating point.
   Rotation speed is constant pi/6.
   Both state and measurements vectors are 1D (a point angle),
   Measurement is the real point angle + gaussian noise.
   The real and the estimated points are connected with yellow line segment,
   the real and the measured points are connected with red line segment.
   the real and the corrected estimate points are connected with green line segment.
   the one-step-ahead forecast is marked with a green cross.
   (if Kalman filter works correctly,
    the yellow segment should be shorter than the red one).
   Pressing p will toggle the printing of the variables
   Pressing any other key (except ESC) will reset the tracking.
   Pressing ESC will stop the program.

   See https://github.com/opencv/opencv/blob/master/modules/video/src/kalman.cpp for the KF code.
"""
# Python 2/3 compatibility
import sys
PY3 = sys.version_info[0] == 3

if PY3:
    long = int

import numpy as np
import cv2 as cv

from math import cos, sin, sqrt
import numpy as np
from time import sleep


def main():
    img_height = 500
    img_width = 500
    alpha = 0.5
    kalman = cv.KalmanFilter(2, 1, 0)

    code = long(-1)

    cv.namedWindow("Kalman")

    while True:
        state = 0.1 * np.random.randn(2, 1)
        state = np.array([[0., 3.14159/6]]).transpose() # start at zero, rotate at pi/6

        measurementNoiseCov = 1e-1 * np.ones((1, 1))
        processNoiseCov = 0*1e-5 * np.eye(2)

        kalman.transitionMatrix = np.array([[1., 1.], [0., 1.]]) # F. input
        kalman.measurementMatrix = 1. * np.eye(2)              # H. input pos+speed
        kalman.processNoiseCov = 1e-5 * np.eye(2)                # Q. input
        kalman.measurementNoiseCov = 1e-1 * np.eye(2)            # R. input
        kalman.errorCovPost = 1. * np.eye(2)                     # P._k|k  KF state var
        kalman.statePost = 0.0*0.1 * np.random.randn(2, 1)       # x^_k|k  KF state var

        report = 1
        k = 0; 
        img = np.zeros((img_height, img_width, 3), np.uint8)
        while True:
            def calc_point(angle):
                return (np.around(img_width/2 + img_width/3*cos(angle), 0).astype(int),
                        np.around(img_height/2 - img_width/3*sin(angle), 1).astype(int))

            state_angle = state[0, 0]
            state_pt = calc_point(state_angle)

            prediction = kalman.predict()                       # advance Kalman filter to next timestep 
                                                                # updates statePre, statePost, errorCovPre, errorCovPost
                                                                # k-> k+1, x'(k) = A*x(k)
                                                                # P'(k) = temp1*At + Q 
                                                                
            predict_angle = prediction[0, 0]
            predict_pt = calc_point(predict_angle)

            measurement = measurementNoiseCov * np.random.randn(1, 1)

            # generate measurement
            measurement = np.dot(kalman.measurementMatrix, state) + measurement  # z_k=H*x_k

            measurement_angle = measurement[0, 0]
            measurement_pt = calc_point(measurement_angle)

            # plot points
            def draw_cross(center, color, d):
                cv.line(img,
                         (center[0] - d, center[1] - d), (center[0] + d, center[1] + d),
                         color, 1, cv.LINE_AA, 0)
                cv.line(img,
                         (center[0] + d, center[1] - d), (center[0] - d, center[1] + d),
                         color, 1, cv.LINE_AA, 0)

            #img = np.zeros((img_height, img_width, 3), np.uint8)
            img = img * (1.0 - alpha) ;

            cv.line(img, state_pt, measurement_pt, (0, 0, 255), 1, cv.LINE_AA, 0) # red measurement error
            #cv.line(img, state_pt, predict_pt, (0, 255, 255), 1, cv.LINE_AA, 0)
            cv.line(img, state_pt, calc_point(kalman.statePost[0,0]), (0, 255, 0), 1, cv.LINE_AA, 0) # green post-meas error
            cv.line(img, state_pt, calc_point(kalman.statePre[0,0]), (0, 255, 255), 1, cv.LINE_AA, 0)  # yellow pre-meas error

            draw_cross(np.int32(state_pt), (255, 255, 255), 3) # white
            draw_cross(np.int32(measurement_pt), (0, 0, 255), 3)  # red
            draw_cross(np.int32(calc_point(kalman.statePre[0,0])), (0, 255, 255), 3) # yellow

            kalman.correct(measurement)                                            # correct the state estimates based on measurements
                                                                                   # updates .statePost & errorCovPost 
            draw_cross(np.int32(calc_point((kalman.statePost)[0,0])), (0, 255, 0), 3)  # green cross
            # forecast one step
            draw_cross(np.int32(calc_point((kalman.transitionMatrix @ kalman.statePost)[0,0])), (0, 255, 0), 6) # large green cross
            

            cv.imshow("Kalman", img)
            if report:
                print(f"Iteration {k}")
                print(f"state: x_{k} {state.transpose()}")
                print(f"measurement matrix, noise: _{k}={kalman.measurementMatrix},  v_{k}= {kalman.measurementNoiseCov}") 
                print(f"process noise w_{k}=  {kalman.processNoiseCov}" )

                print(f"est state pre- measurement: x^_{k-1}={kalman.statePre.transpose()}") #??
                print(f"measurement: x_{k}={measurement.transpose()}")
                print(f"est state post-measurement x^_{k}|{k}={kalman.statePost.transpose()}")
                print(f"est state covariance P_{k}=", kalman.errorCovPost)
                print(f"forecast pre-measure x_({k+1}|{k-1})= {(kalman.transitionMatrix@ kalman.statePre).transpose()} (pre-measure)")
                print(f"forecast post-measure x_({k+1}|{k})= {(kalman.transitionMatrix @ kalman.statePost).transpose()} (post-measure)")
                print()
                sleep(1.05) 
            # update the real process
            k = k + 1
            process_noise = sqrt(processNoiseCov[0,0]) * np.random.randn(2, 1)
            state = np.dot(kalman.transitionMatrix, state) + process_noise       # x_k+1 = F x_k +w_k

            code = cv.waitKey(100)
            if code == ord('p'): # toggle printing
                report = not report
                continue
            if code != -1:
                break

        if code in [27, ord('q'), ord('Q')]:
            break

    print('Done')


if __name__ == '__main__':
    print(__doc__)
    main()
    cv.destroyAllWindows()

```

**Comment by catree** [comment]
Thanks for the detailed review of the sample code.

I would suggest you to open a pull request to not lose the changes. More information about pull request on the web or for instance:

- [First Contributions](https://github.com/firstcontributions/first-contributions)
- [How to contribute to OpenCV](https://github.com/opencv/opencv/wiki/How_to_contribute)

**Comment by drf5n** [comment]
At first I was wondering how synchronized the .cpp and .py examples should be.  One issue seems like they should operate the same, and a separate issue seems like the KF demo should be more of an illustrative example of using KF than a flashy picture.
