### ISSUE TITLE
How long would it take to rewrite opencv in rust?

### ISSUE THREAD

**Issue by JustinMBrown** [opencv/opencv#20098]
It's no secret that setting up opencv as a dependency for C++ projects can be a nightmare. It's so bad that people create projects like this just to make it easier: https://github.com/changh95/cpp-cv-project-template  
Ultimately, this problem is due to the fact that C++ doesn't have a first party dependency manager and likely never will. Rust, however, has Cargo. Rust also guarantees memory safety and fearless concurrency, both of which would make the API a lot more stable. 

What features or improvements to the rust ecosystem would be needed to start rewriting opencv in rust? How long would it take?

Also, rust and C++ can have full duplex integration each other, so If a total rewrite is out of the question, what if new code and certain parts of opencv were incrementally written in rust? This is the approach Linux is taking towards integrating rust.

**Comment by catree** [comment]
Related:

- https://github.com/rust-cv
- https://github.com/rust-cv/cv

**Comment by Frank1126lin** [comment]
Yet I am using:
- https://github.com/twistedfall/opencv-rust

**Comment by aaqidmasoodi** [comment]
is the opencv crate just a wrapper around C++ ? I am talking about this https://crates.io/crates/opencv
i have a few questions, first how long would it take to rewrite opencv library in rust without needing C++ at all, is it possible? 
Secondly, if this is just a wrapper around C++ , then does it mean opencv would be slower in rust? 
I am new to rust and don't fully understand how this binding stuff works?
