### ISSUE TITLE
Smallest possible dependancies when compiling dnn with cuda backend

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#20108]
I discovered that Cuda 10.2 doesn't support Ampere (GTX 3080) generation, and recompiling OpenCV with Cuda 11.2 resulted in an 120Mb increase of the dlls that need to be redistributed.
Namely `cudart64_110.dll`, `cublas64_11.dll`, `cublasLt64_11.dll` and `cudnn64_8.dll`, `cudnn_cnn_infer64_8.dll`, `cudnn_ops_infer64_8.dll`
These 6 files total **692Mb uncompressed**!

I was wondering if there is anything that can be stripped down using compilation flags?
- For instance do we need both cublas and cublasLt (light)?
- then it seems cudev is a 'false dependancy' according to @YashasSamaga , can I get rid of it? https://gist.github.com/YashasSamaga/a84cf2826ab2dc755005321fe17cd15d#gistcomment-3120848

These are my current (relevant) flags:
`-DBUILD_LIST=core,imgcodecs,imgproc,highgui,dnn,cudev -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ../  -DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_ARCH_BIN="3.5 5.0 5.2 6.1 7.0 7.5 8.6" -D CUDA_ARCH_PTX="3.5 7.5" -DWITH_CUFFT=OFF -DWITH_CUBLAS=ON -DCUDNN_LIBRARY="../../cudnn/8.1.1/lib/x64/cudnn.lib" -DCUDNN_INCLUDE_DIR="../../cudnn/8.1.1/include"  -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2"`

**Comment by YashasSamaga** [comment]
Related: https://github.com/opencv/opencv/issues/17488

I don't think you will save any space by avoiding cudev.

Reducing the architectures required to support in `CUDA_ARCH_BIN` would also decrease the binary size of the DNN module.

The CUDA backend is currently heavily templated code and creates a fat binary with thousands of kernels. Maybe future work with runtime compilation can resolve these issues.

**Comment by JulienMaille** [comment]
Thank you @YashasSamaga . What about blas and blas light, do we need both?

**Comment by YashasSamaga** [comment]
@JulienMaille The CUDA backend only uses GEMM from cuBLAS. cuBLASLt may not be required but I am not sure (cuBLAS might use it).

**Comment by JulienMaille** [comment]
@YashasSamaga quick question related to that setup, I'm stuck in `opencv_world452d.dll!cv::dnn::cuda4dnn::csl::cudnn::convolve<float>()` for several minutes (!) when running my first inference on a 3070 GTX. At first I thought the code had crashed. I'm on latest drivers, win10 and compiled with cuda 11.2 + cudnn 8.1.1
What did I do wrong?

**Comment by YashasSamaga** [comment]
Does it happen without `opencv_world`?

**Comment by JulienMaille** [comment]
I need to try. Is it a known problem? Is there an existing issue in github I should read?

**Comment by JulienMaille** [comment]
@YashasSamaga I recompiled everything without `opencv_world` and I get the same very long initialisation.
A lot of time is spent in `opencv_dnn452d.dll!cv::dnn::cuda4dnn::csl::cudnn::UniqueHandle::UniqueHandle()` initCUDABackend, and then in the first convolve I think.

**Comment by YashasSamaga** [comment]
@JulienMaille The first initialization is slow but it shouldn't have been minutes slow. I can't think of any reason why it should be this slow. Can you profile your program using Nsight Systems and check? It would help if you can also share or mail the profiler report.

**Comment by JulienMaille** [comment]
I've never done this, should I select `Profile Cuda Application`?

**Comment by YashasSamaga** [comment]
Can you also share your `CUDA_ARCH_BIN` and `CUDA_ARCH_PTX` entries from your CMake log?

**Comment by JulienMaille** [comment]
```
ARCH=
ARCH_BIN_NO_POINTS=35 50 52 61 70 75 86
ARCH_LIST=35;75
ARCH_PTX_NO_POINTS=35 75
```
Which email can I use to send the Nsight report?

**Comment by YashasSamaga** [comment]
@JulienMaille You can find my email address in my GitHub profile. One reason for slow initialization could be because of JIT compilation for architectures which are not in `CUDA_ARCH_BIN` but a compatible PTX entry in `CUDA_ARCH_PTX`. Other reasons could be CUDA version mismatch (but OpenCV should be able to catch it at runtime).

**Comment by JulienMaille** [comment]
@YashasSamaga regarding smallest possible dependencies, I noticed cublas64 and cublasLt64 dlls keep increasing in size for each news release of Cuda.
In order to support Ampere, would you say it is risky to develop with Cuda 11.0.3 and Cudd 8.0.1? Or are these old release very buggy?

**Comment by YashasSamaga** [comment]
@JulienMaille I am out of touch with CUDA. You might get an answer at NVIDIA developer forums.
