### ISSUE TITLE
DC component sqrt is missing in magSpectrums() called in phaseCorrelate().

### ISSUE THREAD

**Issue by yo1990** [opencv/opencv#20100]
In this source code [/modules/imgproc/src/phasecorr.cpp](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp),
I think std::sqrt should be applied to the below lines.

[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L85) `dataDst[0] = dataSrc[0]*dataSrc[0];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L87) `dataDst[(rows-1)*stepDst] = dataSrc[(rows-1)*stepSrc]*dataSrc[(rows-1)*stepSrc];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L104) `dataDst[0] = dataSrc[0]*dataSrc[0];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L106) `dataDst[j1] = dataSrc[j1]*dataSrc[j1];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L129) `dataDst[0] = dataSrc[0]*dataSrc[0];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L131) `dataDst[(rows-1)*stepDst] = dataSrc[(rows-1)*stepSrc]*dataSrc[(rows-1)*stepSrc];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L148) `dataDst[0] = dataSrc[0]*dataSrc[0];`
[here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L150) `dataDst[j1] = dataSrc[j1]*dataSrc[j1];`

**Comment by alalek** [comment]
BTW, some sqrt() calls were added by this patch: https://github.com/opencv/opencv/commit/04c0783b2fb966321e5d1c7453d104bdccde7ed1
