### ISSUE TITLE
Can't create layer "2840" of type "CumSum" in function 'getLayerInstance'

### ISSUE THREAD

**Issue by sheeranshan** [opencv/opencv#20110]
##### Detailed description

I have converted the TORCH model to the ONNX model, When I want to use the ONNX model to call OpenCV, this kind of problem occurs, how should I solve it

**Comment by sheeranshan** [comment]
[ERROR:0] global /tmp/pip-req-build-yw7uvgqm/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2108) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [CumSum]:(2840)
Traceback (most recent call last):
  File "tools/demo_image.py", line 256, in <module>
    main()
  File "tools/demo_image.py", line 109, in main
    network = cv2.dnn.readNetFromONNX(args.model)
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-yw7uvgqm/opencv/modules/dnn/src/onnx/onnx_importer.cpp:2129: error: (-2:Unspecified error) in function 'handleNode'
> Node [CumSum]:(2840) parse error: OpenCV(4.5.2) /tmp/pip-req-build-yw7uvgqm/opencv/modules/dnn/src/dnn.cpp:621: error: (-2:Unspecified error) Can't create layer "2840" of type "CumSum" in function 'getLayerInstance'

**Comment by thezane** [comment]
I'm interested in this issue.  I'm looking at the definition of cumsum here:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#CumSum

My plan is to add a `CumSumFunctor` struct to `elementwise_layers.cpp` to support the cumsum layer as that file supports other per-element operation layers.  Any concerns with this approach?  Any suggestions for a better approach?

**Comment by thezane** [comment]
I'm interested in this issue. I'm looking at the definition of cumsum here:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#CumSum

My plan is to add a CumSumFunctor struct to elementwise_layers.cpp to support the cumsum layer as that file supports other per-element operation layers:
https://github.com/opencv/opencv/blob/68d15fc62edad980f1ffa15ee478438335f39cc3/modules/dnn/src/layers/elementwise_layers.cpp

Any concerns with this approach? Any suggestions for a better approach?

**Comment by thezane** [comment]
@sheeranshan Can you share the onnx model please that gave you this error?  I have an implementation I like to test before opening a PR.

**Comment by asmorkalov** [comment]
@sheeranshan friendly reminder.

**Comment by asmorkalov** [comment]
@sheeranshan Have you tried the last OpenCv version? May i close the issue?
