### ISSUE TITLE
imgwarp: Assertion failed on linux but not Mac OS X.

### ISSUE THREAD

**Issue by FiReTiTi** [opencv/opencv#20132]
##### Detailed description

I'm using OpenCV for registration, and I was trying to register a big image 13143x18688, I precise the dimensions because of [this discussion](https://answers.opencv.org/question/203798/shrt_max-in-cv2remap/).

If things work fine on my laptop that is on Mac OS X, I have a bug on Centos.

##### Steps to reproduce

Here is the line of code that generates the error:
 ```
        warped_img = cv2.warpPerspective(img, H, (width, height), borderMode=cv2.BORDER_CONSTANT, borderValue=0)
 ```

and here is the error:
 ```
       cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-s8zh4qlk/opencv/modules/imgproc/src/imgwarp.cpp:1724: error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'remap'
  ```

I made sure that I run the exact same version on both systems, using `pip install --upgrade opencv-contrib-python-headless==4.5.1.48`.

Note: the first version installed on CentOS was the latest `4.5.2.52`, so I downgraded it to 4.5.1.48, the same version that was working on my laptop. Both failed with the same error.

##### System information (version)

- OpenCV => 4.5.1
- Operating System / Platform => MacOSX 10.15.7 and Linus Centos centos-release-7-7.1908.0.el7.centos.x86_64

It seems to be an old issue as I found [this discussion](https://github.com/iacopomasi/face_specific_augm/issues/3). I'm ok with fixing the code as mentioned, but where do I find it?

Thank you in advance...

**Comment by FiReTiTi** [comment]
@alalek which information would you need me to add?

**Comment by FiReTiTi** [comment]
@alekcac The images I used are about 500Mo each, I cannot share them and there is not such images in `opencv_extra repository`. Any suggestion?

**Comment by alalek** [comment]
`np.zeros()` should work to replace images, because image content is not used here to trigger message (also this should be used to keep reproducer minimal).

See here: #7544

**Comment by FiReTiTi** [comment]
I found that one of the image dimension was different and violated the max value cited in the first link I shared.
Please, delete this post.
