### ISSUE TITLE
IPP: cmake chooses the wrong architecture of libippicv.a on JETSON AGX XAVIER

### ISSUE THREAD

**Issue by peclatj** [opencv/opencv#20136]
##### System information (version)
- OpenCV => 4.5.2 and 3.4.14
- Operating System / Platform => Ubuntu 18.04.5 LTS / JETSON AGX XAVIER
- Compiler => gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04), Target: aarch64-linux-gnu
- Cmake => cmake version 3.10.2

##### Detailed description
The cmake process download the 32 bits architecture version of the IPPICV library despite the rest of the compilation being X86_64. cmake downloads : "ippicv_2020_lnx_ia32_20191018_general.tgz" instead of "ippicv_2020_lnx_intel64_20191018_general.tgz"

This causes the build to fail during the linking of the library.
```
[ 52%] Linking CXX shared library ../../lib/libopencv_core.so
/usr/bin/ld: ../../3rdparty/ippicv/ippicv_lnx/icv/lib/ia32/libippicv.a(ippcpufeatures.o): Relocations in generic ELF (EM: 3)
../../3rdparty/ippicv/ippicv_lnx/icv/lib/ia32/libippicv.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_core.dir/build.make:2348: recipe for target 'lib/libopencv_core.so.3.4.14' failed
make[2]: *** [lib/libopencv_core.so.3.4.14] Error 1
CMakeFiles/Makefile2:1928: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

##### Steps to reproduce

Flash the JETSON AGX XAVIER with the latest image (Ubuntu 18.04) using the Nvidia SDK Manager, Install the tools in the manager.

Open a terminal and type
```
#create a folder workspace
mkdir workspace
cd workspace

# Compiler
sudo apt-get update
sudo apt-get install cmake
sudo apt-get install g++

# Dependencies
mkdir dependencies && cd dependencies
dependencies_folder=$(pwd)

# Eigen3
sudo apt-get install libeigen3-dev

# Boost & Python3-dev
sudo apt-get install libboost-all-dev

# OpenSSL
sudo apt-get install libssl-dev

# FFMPEG
sudo apt-get install ffmpeg

# For opencv
sudo apt-get install libgtk2.0-dev
sudo apt-get install pkg-config

# OpenCV (4.5.2 or 3.4.14)
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.2.zip
unzip opencv_contrib.zip

git clone https://github.com/opencv/opencv.git
mv opencv opencv4 && cd opencv4
git checkout 4.5.2 # or 3.4.14

mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$dependencies_folder/opencv4_release \
-D CMAKE_BUILD_TYPE=RELEASE \
-D BUILD_EXAMPLES=OFF \
-D BUILD_opencv_apps=OFF \
-D BUILD_DOCS=OFF \
-D BUILD_PERF_TESTS=OFF \
-D BUILD_TESTS=OFF \
-D WITH_TBB=ON \
-D WITH_OPENMP=ON \
-D WITH_IPP=ON \
-D WITH_NVCUVID=ON \
-D WITH_CUDA=ON \
-D WITH_CSTRIPES=ON \
-D WITH_OPENCL=ON \
-D OPENCV_EXTRA_MODULES_PATH=$dependencies_folder/opencv_contrib-4.5.2/modules \
..
make -j12
```

If in the file "3rdparty/ippicv/ippicv.cmake" I change line 15 with
```
if(X86_64 OR TRUE)
```
it works.

**Comment by alalek** [comment]
> -D WITH_IPP=ON

Remove that.

> Target: aarch64-linux-gnu

IPP is provided for x86-only for now.

---

Other options should be revised too. E.g:
- `WITH_CSTRIPES` is deprecated and removed.
- `WITH_TBB` and `WITH_OPENMP` should not be used both.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
