### ISSUE TITLE
opencvJS doesn't support boxPoints API. I hope it does

### ISSUE THREAD

**Issue by changy1105** [opencv/opencv#20133]
Opencv compiler version 3.4, using opencvjs page error：
![image](https://user-images.githubusercontent.com/43414102/119089098-367e8f00-ba3c-11eb-9bed-dbb7670c6996.png)

**Comment by alalek** [comment]
Take a look on this file: https://github.com/opencv/opencv/blob/3.4.14/platforms/js/opencv_js.config.py

**Comment by changy1105** [comment]
It has been used in OpenCV_ The boxpoints API is added to js.config.py file, but the returned result is mat non array.How to convert the result of boxpoints API in opencvjs into points?

**Comment by sturkmen72** [comment]
i think `boxPoints` function implemented as named `rotatedRectPoints` in OpenCV.js
```
        // apply camshift to get the new location
        [trackBox, trackWindow] = cv.CamShift(dst, trackWindow, termCrit);

        // Draw it on image
        let pts = cv.rotatedRectPoints(trackBox);
        cv.line(frame, pts[0], pts[1], [255, 0, 0, 255], 3);
        cv.line(frame, pts[1], pts[2], [255, 0, 0, 255], 3);
        cv.line(frame, pts[2], pts[3], [255, 0, 0, 255], 3);
        cv.line(frame, pts[3], pts[0], [255, 0, 0, 255], 3);
```
