### ISSUE TITLE
cannot compile OpenCV with QT and OpenGL. 

### ISSUE THREAD

**Issue by VladimirBessonov** [opencv/opencv#20140]
I am getting the same errors as I can see in old threads of discussions. But I don't see any solution. why is it still not resolved ?

LINK 2019 unresolved external symbol "double __cdecl cvGetPropVsync_W32(char const *)" (?cvGetPropVsync_W32@@YANPEBD@Z) referenced in function cvGetWindowProperty etc

**Comment by VladimirBessonov** [comment]
Where is solution for the case? 
It is irritating... instead of solving problem just marked duplicated. I know it is duplicated, I don't see it is resolved in any thread. 
Bunch suggestions that do not work. That is it.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/issues/19870

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/issues/20005
