### ISSUE TITLE
Compiling with Qt4: OpenCVFindLibsGUI.cmake requires Qt5

### ISSUE THREAD

**Issue by clauandr** [opencv/opencv#20154]
##### System information (version)
- OpenCV => 3.4.14 (but the cmake is the same in 4.5.2)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

Compiling OpenCV from sources using WITH_QT=true: cmake looks for Qt5 and it doesn't fall back to Qt4 if Qt5 is not found with find_package.

`find_package(Qt5 COMPONENTS Core Gui Widgets Test Concurrent REQUIRED NO_MODULE)`
The REQUIRED option cause the unwanted behaviour.

The cmake was modified here: [commit](https://github.com/opencv/opencv/commit/a164a131f999c5089b3a769bcd9296d5d53a945e#diff-f13de59634750996ff3eb787e07e4f4fe9e6659955ed521bb274e2111e22f1a8)

##### Steps to reproduce

Compile with Qt4

**Comment by alalek** [comment]
Use `cmake -DWITH_QT=4 ...`

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
