### ISSUE TITLE
opencv/modules/core/include/opencv2/core/private.cuda.hpp:59:12: fatal error: cuda.h: No such file or directory  #  include <cuda.h>             ^~~~~~~~ compilation terminated.

### ISSUE THREAD

**Issue by jinfagang** [opencv/opencv#20168]
```
opencv/modules/core/include/opencv2/core/private.cuda.hpp:59:12: fatal error: cuda.h: No such file or directory
 #  include <cuda.h>
            ^~~~~~~~
compilation terminated.

```

CUDA11.2 I tried everything I can but always hit this issue when run:

```
sudo make install
```

I run successfully run make -j32, it works OK, only got this when `sudo make install`

**Comment by jinfagang** [comment]
I even add 
```
cuda_include_directories(${CUDNN_INCLUDE_DIR} ${TENSORRT_INCLUDE_DIR})
include_directories(include
        ${CUDA_INCLUDE_DIRS}
        ${CUDNN_INCLUDE_DIR})
```
to cmake doesn't work. My cuda.h and cuda_runtime.h exists. and my other tiny cuda projects can run it smoothly, except OpenCV

**Comment by alalek** [comment]
[Can't reproduce on public CI](http://pullrequest.opencv.org/buildbot/builders/master-contrib_cuda-lin64).

More details are required:
- CMake stdout (from clean build)
- files from build folder: CMakeCache.txt and CMakeVars.txt (as attachment or use "grep" for related problem keyword)
- failed command line via `make VERBOSE=1` (without any `-j` option)

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by jinfagang** [comment]
@alalek I found everytime I run make, it still make from very begining, even I generated lib under `build/lib`.

Is that normal?

I tried again clone fresh opencv and opencv_contrib. Still same error:

```
/opencv/modules/core/include/opencv2/core/private.cuda.hpp:59:12: fatal error: cuda.h: No such file or directory
 #  include <cuda.h>
            ^~~~~~~~

```

I think it might be my CUDA11.2 problem, but that's weired.... CUDA11.2 other cuda applications build OK.
CMakeCache.txt is here.
[CMakeCache.txt](https://github.com/opencv/opencv/files/6553521/CMakeCache.txt)

**Comment by jinfagang** [comment]
That's really strange, I copied all cuda header files to my current `build` dir, and it can run `sudo make install`, but it actually not make install, it's building again??

![image](https://user-images.githubusercontent.com/21303438/119817448-92578500-bf20-11eb-8ff6-40c04c5c0ea3.png)

wth happening here...

**Comment by alalek** [comment]
> sudo

1.
Perhaps you have corrupted access rights of files in your build folder.
Don't use `make install` until you really need that (especially with sudo).

2. sudo drops environment variables. Read the documentation of sudo.

**Comment by jinfagang** [comment]
@alalek  No, nothing to do with todo, I found it's cmake issue, I have errors in make, but it shows me 100% progress, I scrolled up, some error happen.

**Comment by jinfagang** [comment]
Some error at this:

```
opencv/modules/gapi/misc/python/pyopencv_gapi.hpp:903:45: error: ‘pyopencv_GOpaqueT_t’ does not name a type; did you mean ‘pyopencv_Tracker_t’?
             auto& opaque = reinterpret_cast<pyopencv_GOpaqueT_t*>(obj)->v;
                                             ^~~~~~~~~~~~~~~~~~~
                                             pyopencv_Tracker_t
opencv/modules/gapi/misc/python/pyopencv_gapi.hpp:903:64: error: expected ‘>’ before ‘*’ token
             auto& opaque = reinterpret_cast<pyopencv_GOpaqueT_t*>(obj)->v;

```

**Comment by jinfagang** [comment]
I am totally confused. I clone another refresh code, runed `make -j102` first time, it shows me 100% finished, run `make install` error got again.

And I run `make -j102` again, it build from scratch again....

```
[100%] Built target example_cpp_demhist
[100%] Built target example_cpp_neural_network
[100%] Built target example_snippet_imgproc_HoughLinesPointSet
[100%] Built target example_tutorial_pointPolygonTest_demo
[100%] Built target example_tutorial_MatchTemplate_Demo
[100%] Built target example_tutorial_video-write
[100%] Built target example_tutorial_Remap_Demo
[100%] Built target example_tutorial_camshift
[100%] Built target example_tutorial_optical_flow_dense
[100%] Built target example_cpp_videocapture_camera
[100%] Built target example_tutorial_pnp_detection
[100%] Built target example_tutorial_video-input-psnr-ssim
[100%] Built target example_cpp_videocapture_gphoto2_autofocus
[100%] Built target example_tutorial_meanshift

~/Software/opencv/build on  master
❯ sudo make install
[  0%] Built target opencv_highgui_plugins
[  0%] Built target opencv_videoio_plugins
[  1%] Built target ippiw
[  1%] Built target opencv_cudev
[  1%] Built target ittnotify
Consolidate compiler generated dependencies of target opencv_core
[  1%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o
In file included from /home/Software/opencv/modules/core/src/precomp.hpp:60:0,
                 from /home/Software/opencv/modules/core/src/arithm.cpp:50:
/home/Software/opencv/modules/core/include/opencv2/core/private.cuda.hpp:59:12: fatal error: cuda.h: No such file or directory
 #  include <cuda.h>
            ^~~~~~~~
compilation terminated.
modules/core/CMakeFiles/opencv_core.dir/build.make:1008: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o' failed
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o] Error 1
CMakeFiles/Makefile2:5057: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by jinfagang** [comment]
I think there is something broken in opencv master which totally messed up with `make` and `make install`

**Comment by jinfagang** [comment]
I gaved it up. Can anyone tell me which commit can be successfully built with CUDA11.2??

**Comment by luohao123** [comment]
I fixed this issue, by copied all `/usr/local/cuda/include` files to `build`.
it's tricky but work. now it can build and installed into `/usr/local`
