### ISSUE TITLE
haarcascade_frontalcatface.xml not working properly

### ISSUE THREAD

**Issue by Shuvo31** [opencv/opencv#20161]
##### Steps to reproduce

<!-- Here is the code which i m working with
import cv2
face_cascade=cv2.CascadeClassifier("haarcascade_frontalcatface.xml")
def detect():
    capture=cv2.VideoCapture(0)
    while True:
        _,image=capture.read()
        gray=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        face=face_cascade.detectMultiScale(gray,1.1,4)
        for (x,y,w,h) in face:
            cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
        cv2.imshow("Face Detected",image)
        if cv2.waitKey(1)==27:
            break
    capture.release()
detect()

Error:
     File "c:\Users\shuvo\Desktop\Python Projects\FaceRecognization\face.py", line 8, in detect
    face=face_cascade.detectMultiScale(gray,1.1,4)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sgoydvi3\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

**Comment by sturkmen72** [comment]
Please close the issue.
