### ISSUE TITLE
Set/Get the active device used with (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL)

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#20160]
I've been browsing the doc and source code but can't find a way to
- tell on which device is the `forwad()` running, is it `ocl::Device::getDefault()`?
- select that device in case there's more than one (cpu & gpu)

**Comment by alalek** [comment]
- yes. switching on "the fly" is not supported or validated.
- check Wiki page: https://github.com/opencv/opencv/wiki/OpenCL-optimizations

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by JulienMaille** [comment]
Thank you @alalek , so the bottom line is that Dnn on OpenCL behaves exactly like standard OpenCV on OpenCL?
