### ISSUE TITLE
behavior of cv.findContours() differs from what one might expect

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [opencv/opencv#20179]
Per the documentation, "Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity."  This is not what is normally understood as a contour.  Suppose that we want a contour at an image intensity of 128.  This intensity might not exist in the image, but if there are intensities that bracket 128, we can use interpolation to estimate the location at which the intensity should be approximately equal to 128.  It sounds as though cv.findContours() is not doing this.

**Comment by alalek** [comment]
Refer to [findContours() documentation](https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a).

> Finds contours in a binary image.

These images are black/white (0/255).
So there is no "128".

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
