### ISSUE TITLE
libgio-2.0.so.0: undefined symbol: g_uri_join while importing cv2 in conda environmnent (Ubuntu)

### ISSUE THREAD

**Issue by syed0596** [opencv/opencv#20212]
Ubuntu 20.04
Anaconda
OpenCV 4.2.0

The ImportError is: `libgio-2.0.so.0: undefined symbol: g_uri_join`
which means, your OpenCV were compiled with the original libgio-2.0.so.0 at `/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0` but when you try to "`import cv2`" now it is trying to use at libgio-2.0.so.0 at `~/anaconda3/envs/<anaconda_env>/lib/libgio-2.0.so.0` 

Note: replace `<anaconda_env>` with your working environment. 

So a dirty hack may probably help:

    mv ~/anaconda3/envs/<anaconda_env>/lib/libgio-2.0.so.0 ~/anaconda3/envs/<anaconda_env>/lib/libgio-2.0.so.0.backup

Thumbs Up , If it solved your problem.

**Comment by the-cat-crying** [comment]
thanks!!!!!!!
