### ISSUE TITLE
Anti virus warning in package

### ISSUE THREAD

**Issue by jcnwholland** [opencv/opencv#20222]
I'm getting a clear  warning and block after building in VS 2019, and installing from there.

" tmpaba331dfa1c84b03befffdcd425d9709.exec.cmd is infected with Generic.Botget.1AF28A31. The threat has been successfully blocked, your device is safe."

Windows 10, all up to date, Bitdefender AV.

**Comment by alalek** [comment]
There is no such file in release packages.
Provide exact steps, AV version to reproduce the issue.

Also try https://www.virustotal.com/ to get more information about the file.
