### ISSUE TITLE
Unable to build OpenCV with VTK 9.0.1 for OpenVINO 2021.3

### ISSUE THREAD

**Issue by fti-ahande** [opencv/opencv#20233]
System information (version)
```
- OpenCV == 4.5.2-openvino
- opencv_contrib == 4.5.2
- opencv_extra == 4.5.2
- Operating System / Platform => Ubuntu 18.04 
- Compiler => g++(8.4)
- VTK == 9.0.1
```

Description

Trying to build OpenCV 4.5.2 with VTK=ON. cmake configuration is successful but module "viz" is causing issues while make.

```
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/graph.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/memory_accessor.cpp.o
[  2%] Linking C static library ../lib/libippiw.a
Note: Class detail_GraphCutSeamFinder has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::detail::GraphCutSeamFinderBase, cv::detail::SeamFinder
      Only the first base class will be used
Generator error: unable to resolve base viz_Widget3D for viz_WMesh
modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make:489: recipe for target 'modules/python_bindings_generator/pyopencv_generated_enums.h' failed
make[2]: *** [modules/python_bindings_generator/pyopencv_generated_enums.h] Error 255
CMakeFiles/Makefile2:7427: recipe for target 'modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all' failed
make[1]: *** [modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/memory_descriptor.cpp.o
[  2%] Built target ippiw
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/memory_descriptor_ref.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/memory_descriptor_view.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/metadata.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/metatypes.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/node.cpp.o
[  2%] Linking CXX static library ../../../../../../lib/libnumeric.a
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/passes/communications.cpp.o
[  2%] Built target numeric
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/search.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/subgraphs.cpp.o
[  2%] Building CXX object modules/CMakeFiles/ade.dir/__/3rdparty/ade/ade-0.1.1f/sources/ade/source/topological_sort.cpp.o
[  3%] Linking CXX static library ../lib/libade.a
[  3%] Built target ade
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
----------------------------------------
[ ERROR(2) ]


@@@@ BLD: { elapsed: 4.654, user: 18.453, system: 1.648, percent: 431.90 } @@@@

```

**Comment by alalek** [comment]
> 4.5.2-openvino
> viz

viz is opencv_contrib module. There is no `-openvino` tag for opencv_contrib.
You can build with `opencv_contrib` from the same tags only - e.g., use `4.5.2`.

You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by fti-ahande** [comment]
Yeah, I am indeed using the same tags:
> opencv == 4.5.2-openvino
> opencv_contrib == 4.5.2
> opencv_extra == 4.5.2

I'll post this one to the suggested forum.

**Comment by alalek** [comment]
Actually you **DON'T**, because [`4.5.2-openvino`](https://github.com/opencv/opencv/releases/tag/4.5.2-openvino) != [`4.5.2`](https://github.com/opencv/opencv/releases/tag/4.5.2)

**Comment by fti-ahande** [comment]
I'm trying to build OpenCV for OpenVINO. Previously, I've built this successfully with all modules where I used 

> opencv == 4.2.0-openvino
> opencv_contrib == 4.2.0
> opencv_extra == 4.2.0

I've tried using VTK 8.x.x and same issue occurs for 4.5.2.

**Comment by fti-aagrawal** [comment]
> Actually you **DON'T**, because [`4.5.2-openvino`](https://github.com/opencv/opencv/releases/tag/4.5.2-openvino) != [`4.5.2`](https://github.com/opencv/opencv/releases/tag/4.5.2)

@alalek  Thanks for clarifying. However, we could not find  `4.5.2-openvino` for contrib.
Are you saying `4.5.2-openvino` is not officially supported for opencv yet to work with contrib?

**Comment by alalek** [comment]
`4.5.2-openvino` may work with `opencv_contrib`, but it is not validated and there is no "tag" (no plans to add -openvino tag in `opencv_contrib`).

The best way is to get `4.5.2` tags in all used repositories (all -openvino bug fixes are ported to upstream).

<details>

If you still want to use `4.5.2-openvino` tag, then you can try:
- find common commit between 4.5.2 / 4.5.2-openvino tag of `opencv` repository ( be24659c038952dde399f7efad2ba06ebdcbda18 )
- get the date of that commit ( 2021-03-03 )
- checkout commit in `opencv_contrib` available on this date ( https://github.com/opencv/opencv_contrib/commit/0165d48da48b169420cd4d70867b991bd48543e8 )

(this means "keep source code bases synchronized")

Alternatives are:
- cherry-pick changes from here: https://github.com/opencv/opencv/pull/19808
- or revert these changes from opencv_contrib: https://github.com/opencv/opencv_contrib/pull/2882 

</details>

The next step is reproducing build process and used flags - check `build_params.txt` file in opencv directory of OpenVINO installation directory.

**Comment by fti-aagrawal** [comment]
Thanks @alalek  for your suggestions. Its helpful :) 
Let us check based on your inputs and we shall revert if there are more queries.

**Comment by fti-ahande** [comment]
Reverting https://github.com/opencv/opencv_contrib/pull/2882  solved our issue. Thanks @alalek !
