### ISSUE TITLE
Bug in cvInitImageHeader - missing nSize initialization

### ISSUE THREAD

**Issue by matthew-kj-barrow** [opencv/opencv#20246]
##### Detailed description

The cvInitImageHeader() function does not correctly initialize the IplImage.  The line "image->nSize = sizeof( *image );" got deleted from OpenCV 3 to OpenCV 4.  This line needs to be added back in.

**Comment by matthew-kj-barrow** [comment]
types_c.h needs to be fixed.  Add memset to _IpImage() constructor.

   _IplImage() { memset(this, 0, sizeof(_IplImage)); }

**Comment by alalek** [comment]
relates #11630
