### ISSUE TITLE
OpenCV 4.5.2 cannot build .so.  Visual Studio throws errors, and android toolchain rejected by CMake

### ISSUE THREAD

**Issue by SavedByZero** [opencv/opencv#20254]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019 (trying from precompiled sdk), Clang 5.0, GNU c++ 11.1, LLvm toolchain
-  CMake (with source) 3.20.3
- Android NDK 21e
-->

##### Detailed description

I cannot build an .so with OpenCV 4.5.2 using the android sdk, nor can I built it from source using CMake 3.20.3
In Visual Studio 2019, using the downloaded sdk with NDK 21e results in compilation failure with numerous errors:
"member named 'signbit' in the global namespace; did you mean 'sigwait'?
I see this for ::signbit;
::isgreaterthan
::islessthan
and many others 

In CMake, the toolchain under the platforms/android folder throws this error: 
CMake Error at platforms/android/android.toolchain.cmake:628 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.

###Steps to reproduce
1) 
Use Visual Studio 2019, Dynamic Shared Library project for android 
Default llvm toolchain 
clang 5.0 
add the include folder for OpenCV 4.5.2
add the library folder for OpenCV 4.5.2 armv7
add the single library file there 
in the main cpp file, include these headers:
#include "opencv2/core.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/imgproc.hpp"

try to compile. 

2) Building from source:
Add the source and export folder in CMake 3.20 
Select your toolchain from the OpenCV 4.5.2 platforms/android folder. 

If I am using the wrong NDK, let me know, but the documents suggested this version was compatible with 21d, and that seems to no longer be listed anywhere, even on the unsupported ndks page.

**Comment by alalek** [comment]
> Select your toolchain from the OpenCV 4.5.2 platforms/android folder

It is for NDK <= 15 only: https://github.com/opencv/opencv/pull/10288#issuecomment-351002893
Modern Android NDKs has own toolchains: https://github.com/opencv/opencv/blob/4.5.2/platforms/android/build_sdk.py#L195

--

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by SavedByZero** [comment]
Okay but 1) 4.0.1 uses 16b, 2) The documentation says 21d is the ndk that goes with this which is why I thought something was messed up, 3) the forums haven’t been able to explain it
