### ISSUE TITLE
is it allowed to use opencv to earn money

### ISSUE THREAD

**Issue by budibeta** [opencv/opencv#20261]
what conditions must be met.

I can't understand the license because English is not my first language.

i know opencv license not MIT license. [https://github.com/opencv/opencv/blob/master/LICENSE](url)

if MIT license I understand, but I don't understand opencv license.

can the **owner or person responsible** to opencv explain about this.
what are the conditions that must be met so that I am allowed to earn money using the opencv library. Thank you.

i need the answer, as fast as possible. Thank you.

**Comment by tatarize** [comment]
https://choosealicense.com/licenses/apache-2.0/
