### ISSUE TITLE
assert(graph_def.node[0].op == 'Placeholder') IndexError: list index out of range

### ISSUE THREAD

**Issue by nf-i** [opencv/opencv#20270]
Hi @dkurt, I need help on this. I can't figure out why it happens. Really appreciate your help.

python tf_text_graph_faster_rcnn.py --input ../opencv_extra-master/opencv_extra-master/testdata/cv/dnn_superres/FSRCNN_x2.pb --config ../models-master/models-master/research/object_detection/samples/configs/faster_rcnn_inception_v2_coco.config --output ../mymodel_frcnn.pbtxt
Number of classes: 90
Scales:            [0.25, 0.5, 1.0, 2.0]
Aspect ratios:     [0.5, 1.0, 2.0]
Width stride:      16.000000
Height stride:     16.000000
Features stride:   16.000000
Graph Def: <tf_text_graph_common.GraphDef object at 0x000001BE80B627C8>
Traceback (most recent call last):
  File "tf_text_graph_faster_rcnn.py", line 299, in <module>
    createFasterRCNNGraph(args.input, args.config, args.output)
  File "tf_text_graph_faster_rcnn.py", line 97, in createFasterRCNNGraph
    assert(graph_def.node[0].op == 'Placeholder')
IndexError: list index out of range

[FSRCNN_x2.zip](https://github.com/opencv/opencv/files/6658793/FSRCNN_x2.zip)

**Comment by dkurt** [comment]
@nf-i, please specify commit hash on which OpenCV.
