### ISSUE TITLE
CMake GUI - set folder in windows ( VTK is not found)

### ISSUE THREAD

**Issue by liang0724s** [opencv/opencv#20276]
- OpenCV => 4.5.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- CMake=> 3.18.4
- VTK=> 8.1.0

I am trying to build cmake after vtk has been built. Unfortunately I get this message：
“VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file“ 
I tried to specify a library path but it didn't help and also set an environment path for this.

What else can I do to pass this error?

**Comment by alalek** [comment]
You may want to try this fix: #20384
