### ISSUE TITLE
opencv_test_core not building from release 4.5.2,  libtiff_4_0

### ISSUE THREAD

**Issue by makingglitches** [opencv/opencv#20286]
My setup uses defined pkg_config_path and libraries compiled differently than the system versions.
All other libraries are found properly and the proper lib version is outputted in the initial cmake

--   Media I/O: 
--     ZLib:                        /lib64/libz.so (ver 1.2.11)
--     JPEG:                        /Data/Documents/CensusProject/gdallib/src/compiled/lib/libjpeg.so (ver 90)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         /lib64/libpng.so (ver 1.6.37)
--     TIFF:                        /lib64/libtiff.so (ver 42 / 4.2.0)
--     JPEG 2000:                   build (ver 2.4.0)
--     OpenEXR:                     build (ver 2.3.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES

the issue is when linking against the test scripts during a call to make
error as follows 

[ 34%] Linking CXX executable ../../bin/opencv_test_core
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/bin/ld: ../../lib/libopencv_imgcodecs.so.4.5.2: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/core/CMakeFiles/opencv_test_core.dir/build.make:871: bin/opencv_test_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:1716: modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by makingglitches** [comment]
workaround would obviously be skip the unit tests in build and see if the build progresses further, but somehow this seems like kind of a rather important thing to just disable.

**Comment by makingglitches** [comment]
Its this statement which is failing 
under build/modules/core

/usr/bin/c++    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG   -Wl,--gc-sections -Wl,--as-needed CMakeFiles/opencv_test_core.dir/test/ocl/test_arithm.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_channels.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_dft.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_gemm.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_image2d.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_matrix_expr.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_matrix_operation.cpp.o CMakeFiles/opencv_test_core.dir/test/ocl/test_opencl.cpp.o CMakeFiles/opencv_test_core.dir/test/test_arithm.cpp.o CMakeFiles/opencv_test_core.dir/test/test_async.cpp.o CMakeFiles/opencv_test_core.dir/test/test_concatenation.cpp.o CMakeFiles/opencv_test_core.dir/test/test_conjugate_gradient.cpp.o CMakeFiles/opencv_test_core.dir/test/test_countnonzero.cpp.o CMakeFiles/opencv_test_core.dir/test/test_cuda.cpp.o CMakeFiles/opencv_test_core.dir/test/test_downhill_simplex.cpp.o CMakeFiles/opencv_test_core.dir/test/test_ds.cpp.o CMakeFiles/opencv_test_core.dir/test/test_dxt.cpp.o CMakeFiles/opencv_test_core.dir/test/test_eigen.cpp.o CMakeFiles/opencv_test_core.dir/test/test_hal_core.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin_emulator.cpp.o CMakeFiles/opencv_test_core.dir/test/test_io.cpp.o CMakeFiles/opencv_test_core.dir/test/test_logtagconfigparser.cpp.o CMakeFiles/opencv_test_core.dir/test/test_logtagmanager.cpp.o CMakeFiles/opencv_test_core.dir/test/test_lpsolver.cpp.o CMakeFiles/opencv_test_core.dir/test/test_main.cpp.o CMakeFiles/opencv_test_core.dir/test/test_mat.cpp.o CMakeFiles/opencv_test_core.dir/test/test_math.cpp.o CMakeFiles/opencv_test_core.dir/test/test_misc.cpp.o CMakeFiles/opencv_test_core.dir/test/test_opencl.cpp.o CMakeFiles/opencv_test_core.dir/test/test_operations.cpp.o CMakeFiles/opencv_test_core.dir/test/test_ptr.cpp.o CMakeFiles/opencv_test_core.dir/test/test_quaternion.cpp.o CMakeFiles/opencv_test_core.dir/test/test_rand.cpp.o CMakeFiles/opencv_test_core.dir/test/test_rotatedrect.cpp.o CMakeFiles/opencv_test_core.dir/test/test_umat.cpp.o CMakeFiles/opencv_test_core.dir/test/test_utils.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.sse2.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.sse3.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.ssse3.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.sse4_1.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.sse4_2.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.fp16.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx2.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin256.avx2.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx512_skx.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin256.avx512_skx.cpp.o CMakeFiles/opencv_test_core.dir/test/test_intrin512.avx512_skx.cpp.o -o ../../bin/opencv_test_core  -Wl,-rpath,/Data/Documents/CensusProject/gdallib/src/opencv-4.5.2/build/lib ../../lib/libopencv_ts.a ../../lib/libopencv_highgui.so.4.5.2 -ldl -lm -lpthread -lrt ../../lib/libopencv_videoio.so.4.5.2 ../../lib/libopencv_imgcodecs.so.4.5.2 ../../lib/libopencv_imgproc.so.4.5.2 ../../lib/libopencv_core.so.4.5.2

**Comment by makingglitches** [comment]
grep -iR bin/opencv_test_core
 reveals the line to be in  modules/core/CMakeFiles/opencv_test_core.dir/link.txt:
again.

**Comment by makingglitches** [comment]
problem is occurring because whatever is generating link.txt is not adding the linker option -ltiff
once added the problem goes away.

**Comment by makingglitches** [comment]
workaround is adding the -ltiff to the generated link file.

a search of the whole code directory does not immediately indicate where the link.txt file is being generated.

build/modules/core/CMakeFiles/opencv_test_core.dir/build.make:bin/opencv_test_core: modules/core/CMakeFiles/opencv_test_core.dir/link.txt
build/modules/core/CMakeFiles/opencv_test_core.dir/build.make:	cd /Data/Documents/CensusProject/gdallib/src/opencv-4.5.2/build/modules/core && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/opencv_test_core.dir/link.txt --verbose=$(VERBOSE)

are the only places this file is referenced.

**Comment by makingglitches** [comment]
apparently this is also happening in other files as well

opencv_perf_imgproc

linkage is failing the same way.

I do not know alot about cmake, as I never write these rule files but will search for possible failing step in generation process.

**Comment by makingglitches** [comment]
so thus far, this issue is across the following modules' generated link.txt  -ltiff fixes them all.
it's strange to me that this is happening given I am also using several other **custom build under the alternate pkg_config_path including ZLIB** 

opencv_test_core 
opencv_perf_core
opencv_perf_imgproc
opencv_test_imgproc
opencv_test_ml
opencv_perf_photo
opencv_test_photo
opencv_perf_dnn

**Comment by makingglitches** [comment]
I'm of the opinion this is an issue occurring in cmake itself.
I've been searching for similar errors and from what I can cmake is supposed to figure all this out.
When i search through the code tree with grep aren't very many references to tiff except in the #include headers. I'll look closer but i'm guessing either this will be a simple misconfiguration issue in CMakeLists.txt or an issue with cmake itself.
Going through cmakelists.txt I don't see alot of references to TIFF either.

**Comment by makingglitches** [comment]
Workaround will access each of these files under  the build/modules/{section}/CMakeFiles/{module_name}.dir/link.txt and append a -ltiff   in case you have a scenario like mine wherein you need reconfigure to add in an additional library.

**Comment by makingglitches** [comment]
output of  grep -iRl tiff 
in build directory.

apps/annotation/CMakeFiles/opencv_annotation.dir/link.txt
apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/link.txt
apps/visualisation/CMakeFiles/opencv_visualisation.dir/link.txt
modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/link.txt
modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/link.txt
modules/core/CMakeFiles/opencv_perf_core.dir/link.txt
modules/core/CMakeFiles/opencv_test_core.dir/link.txt
modules/dnn/CMakeFiles/opencv_perf_dnn.dir/link.txt
modules/dnn/CMakeFiles/opencv_test_dnn.dir/link.txt
modules/features2d/CMakeFiles/opencv_perf_features2d.dir/link.txt
modules/features2d/CMakeFiles/opencv_test_features2d.dir/link.txt
modules/gapi/CMakeFiles/opencv_perf_gapi.dir/link.txt
modules/gapi/CMakeFiles/opencv_test_gapi.dir/link.txt
modules/highgui/CMakeFiles/opencv_test_highgui.dir/link.txt
modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/link.txt
modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/link.txt
modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/link.txt
modules/ml/CMakeFiles/opencv_test_ml.dir/link.txt
modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/link.txt
modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/link.txt
modules/photo/CMakeFiles/opencv_perf_photo.dir/link.txt
modules/photo/CMakeFiles/opencv_test_photo.dir/link.txt
modules/stitching/CMakeFiles/opencv_perf_stitching.dir/link.txt
modules/stitching/CMakeFiles/opencv_test_stitching.dir/link.txt
modules/video/CMakeFiles/opencv_perf_video.dir/link.txt
modules/video/CMakeFiles/opencv_test_video.dir/link.txt
modules/videoio/CMakeFiles/opencv_perf_videoio.dir/link.txt
modules/videoio/CMakeFiles/opencv_test_videoio.dir/link.txt

**Comment by makingglitches** [comment]
Cmake being used to generate the build is cmake 3.20.3
On Fedora 34.

**Comment by makingglitches** [comment]
tiff keyword only occurs in non-binary, non-source files in the following files
CMakeLists.txt
modules/imgcodecs/CMakeLists.txt

**Comment by makingglitches** [comment]
in referencing cmake source itself

Source/cmMakefileExecutableTargetGenerator.cxx:    const char* name = (relink ? "relink.txt" : "link.txt");
Source/cmMakefileLibraryTargetGenerator.cxx:    const char* name = (relink ? "relink.txt" : "link.txt");

the issue will be in whatever indicates with these files, configuration or code.
i would think things like libraries not being included would have not made it past test so logic kind of indicates that the issue will be configuration.

in one of the generated files i note:

build/CMakeVars.txt:OPENCV_VERIFY_WITH_TIFF=HAVE_TIFF
build/CMakeVars.txt:TIFF_BIGTIFF_VERSION=
build/CMakeVars.txt:TIFF_FOUND=TRUE
build/CMakeVars.txt:TIFF_INCLUDE_DIR=/usr/include
build/CMakeVars.txt:TIFF_INCLUDE_DIRS=/usr/include
build/CMakeVars.txt:TIFF_LIBRARIES=/lib64/libtiff.so
build/CMakeVars.txt:TIFF_LIBRARY=/lib64/libtiff.so
build/CMakeVars.txt:TIFF_LIBRARY_DEBUG=TIFF_LIBRARY_DEBUG-NOTFOUND
build/CMakeVars.txt:TIFF_LIBRARY_RELEASE=/lib64/libtiff.so
build/CMakeVars.txt:TIFF_VERSION=42
build/CMakeVars.txt:TIFF_VERSION_BIG=43
build/CMakeVars.txt:TIFF_VERSION_CLASSIC=42
build/CMakeVars.txt:TIFF_VERSION_LINES=#define TIFF_VERSION_CLASSIC 42;#define TIFF_VERSION_BIG 43
**build/CMakeVars.txt:TIFF_VERSION_STRING=4.2.0
build/CMakeVars.txt:WITH_TIFF=ON**

the bold lines are the only correct information, I do not yet know if this is a relevant indicator or if many of these default and are never used.

**Comment by makingglitches** [comment]
In looking over the remainder of the build tree, everything else is a source reference so far as I can tell.

**Comment by makingglitches** [comment]
So in looking at cmakelists.

Option to build tiff from source is disabled in this scenario.
WITH_TIFF is turned on by default
other tiff related variables are being defined in the source tree, only in source files (.h .cpp) 
since i'm excluding custom build of tiff and this is not occurring thank god at least, these variables are likely being pulled from the header file in the defined include path.

This is confusing since we start with...

grep -iR TIFF_VERSION ../compiled/include/
../compiled/include/tiff.h:#define TIFF_VERSION_CLASSIC 42
../compiled/include/tiff.h:#define TIFF_VERSION_BIG 43
../compiled/include/tiff.h:	uint16 tiff_version;    /* TIFF version number */
../compiled/include/tiff.h:	uint16 tiff_version;    /* TIFF version number */
../compiled/include/tiff.h:	uint16 tiff_version;    /* TIFF version number */

and somehow in the cache it gets converted without being defined to...

grep -iR TIFF_VERSION_STRING
build/CMakeVars.txt:TIFF_VERSION_STRING=4.2.0

even though everything else is wrong.

my gut is starting to tell me this is a cmake issue.
there just doesnt seem to be enough definition of things that wouldn't have been mined from somewhere else.
there is however a whole f***ing folder of cmake scripts in the source directory.

... OMG there is a FINDTIFF.CMAKE in the cmake source directory which defines TIFF_FOUND in this project.

referenced in this project:

cmake/OpenCVFindLibsGrfmt.cmake:    include(FindTIFF)

**Comment by makingglitches** [comment]
searching under cmake directory.

rep -iR TIFF
OpenCVFindLibsGrfmt.cmake:# --- libtiff (optional, should be searched after zlib and libjpeg) ---
OpenCVFindLibsGrfmt.cmake:if(WITH_TIFF)
OpenCVFindLibsGrfmt.cmake:  if(BUILD_TIFF)
OpenCVFindLibsGrfmt.cmake:    ocv_clear_vars(TIFF_FOUND)
OpenCVFindLibsGrfmt.cmake:    ocv_clear_internal_cache_vars(TIFF_LIBRARY TIFF_INCLUDE_DIR)
OpenCVFindLibsGrfmt.cmake:    include(FindTIFF)
OpenCVFindLibsGrfmt.cmake:    if(TIFF_FOUND)
OpenCVFindLibsGrfmt.cmake:      ocv_parse_header("${TIFF_INCLUDE_DIR}/tiff.h" TIFF_VERSION_LINES TIFF_VERSION_CLASSIC TIFF_VERSION_BIG TIFF_VERSION TIFF_BIGTIFF_VERSION)
OpenCVFindLibsGrfmt.cmake:  if(NOT TIFF_FOUND)
OpenCVFindLibsGrfmt.cmake:    ocv_clear_vars(TIFF_LIBRARY TIFF_LIBRARIES TIFF_INCLUDE_DIR)
OpenCVFindLibsGrfmt.cmake:    set(TIFF_LIBRARY libtiff CACHE INTERNAL "")
OpenCVFindLibsGrfmt.cmake:    set(TIFF_LIBRARIES ${TIFF_LIBRARY})
OpenCVFindLibsGrfmt.cmake:    add_subdirectory("${OpenCV_SOURCE_DIR}/3rdparty/libtiff")
OpenCVFindLibsGrfmt.cmake:    set(TIFF_INCLUDE_DIR "${${TIFF_LIBRARY}_SOURCE_DIR}" "${${TIFF_LIBRARY}_BINARY_DIR}" CACHE INTERNAL "")
OpenCVFindLibsGrfmt.cmake:    ocv_parse_header("${${TIFF_LIBRARY}_SOURCE_DIR}/tiff.h" TIFF_VERSION_LINES TIFF_VERSION_CLASSIC TIFF_VERSION_BIG TIFF_VERSION TIFF_BIGTIFF_VERSION)
OpenCVFindLibsGrfmt.cmake:  if(TIFF_VERSION_CLASSIC AND NOT TIFF_VERSION)
OpenCVFindLibsGrfmt.cmake:    set(TIFF_VERSION ${TIFF_VERSION_CLASSIC})
OpenCVFindLibsGrfmt.cmake:  if(TIFF_BIGTIFF_VERSION AND NOT TIFF_VERSION_BIG)
OpenCVFindLibsGrfmt.cmake:    set(TIFF_VERSION_BIG ${TIFF_BIGTIFF_VERSION})
OpenCVFindLibsGrfmt.cmake:  if(NOT TIFF_VERSION_STRING AND TIFF_INCLUDE_DIR)
OpenCVFindLibsGrfmt.cmake:    list(GET TIFF_INCLUDE_DIR 0 _TIFF_INCLUDE_DIR)
OpenCVFindLibsGrfmt.cmake:    if(EXISTS "${_TIFF_INCLUDE_DIR}/tiffvers.h")
OpenCVFindLibsGrfmt.cmake:      file(STRINGS "${_TIFF_INCLUDE_DIR}/tiffvers.h" tiff_version_str REGEX "^#define[\t ]+TIFFLIB_VERSION_STR[\t ]+\"LIBTIFF, Version .*")
OpenCVFindLibsGrfmt.cmake:      string(REGEX REPLACE "^#define[\t ]+TIFFLIB_VERSION_STR[\t ]+\"LIBTIFF, Version +([^ \\n]*).*" "\\1" TIFF_VERSION_STRING "${tiff_version_str}")
OpenCVFindLibsGrfmt.cmake:      unset(tiff_version_str)
OpenCVFindLibsGrfmt.cmake:    unset(_TIFF_INCLUDE_DIR)
OpenCVFindLibsGrfmt.cmake:  set(HAVE_TIFF YES)
templates/cvconfig.h.in:/* TIFF codec */
templates/cvconfig.h.in:#cmakedefine HAVE_TIFF

most of these variables are defined in findtiff.

link.txt is generated by cmake itself.
opening an issue on their tracker.

**Comment by makingglitches** [comment]
Issue entered.

https://gitlab.kitware.com/cmake/cmake/-/issues/22325

**Comment by makingglitches** [comment]
And tested on a fresh build here is a workaround script.
run this from inside the build directory. 

[workaround.js.gz](https://github.com/opencv/opencv/files/6687534/workaround.js.gz)

**Comment by makingglitches** [comment]
@alalek 

99% certain I determined this is a cmake issue specifically.
tested on version cmake version 3.20.3
opened an issue on their page
workaround script allows user to complete successful build
cmake implements a specific find script for the TIFF library
index.txt is generated by cmake.
please confirm my logic.
thanks.

**Comment by alalek** [comment]
Custom build environments are not tested and probably not supported.
TIFF may depend in JPEG codec. You have these libs in different "locations".

You should start from investigation of this output: `cmake ... -DCMAKE_TRACE_MODE=ON --trace-expand`.

Almost all OpenCV dependencies are optional, can be disabled (`WITH_TIFF=OFF`) or replaced.
Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by makingglitches** [comment]
The build actually works when I use the above script.
 Of note. I tested the object detection lib with python and it runs once a make install is done.
I do honestly think this is a cmake issue but I'll follow through and rerun the build with the options you added.
Till then the workaround works.

During build and execution the following variables are set.

PKG_CONFIG_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/lib/pkgconfig
LIBRARY_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/lib
LD_LIBRARY_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/lib/
C_INCLUDE_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/include/
CPLUS_INCLUDE_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/include/

pkg-config finds the correct location for tiff and its linking against this for other required libs as well, including ffmpeg and it builds.
its just tiff and only tiff causing the problem.

**Comment by makingglitches** [comment]
[output.txt.gz](https://github.com/opencv/opencv/files/6696608/output.txt.gz)

Well that created the most ridiculously bloated file I ever saw.
Hopefully this issue gets fixed instead of sitting stale for whatever reason as the world just keeps pretending its moving on and just runs in place.

**Comment by alalek** [comment]
Used compiler configuration is hijacked:

> #include <...> search starts here:
 /Data/Documents/CensusProject/gdallib/src/compiled/include/
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/backward
 /usr/lib/gcc/x86_64-redhat-linux/11/include
 /usr/local/include
 /usr/include

> LIBRARY_PATH=/Data/Documents/CensusProject/gdallib/src/compiled/lib/../lib64/:...

So you may have duplicated entries for some packages (take a look on libtiff and libjpeg - they are from different locations).
You need properly configure CMake to avoid using of system libraries / headers if you want to use that compiler configuration.

This can't be fixed by OpenCV. Closing.

**Comment by Matthew-Bradley** [comment]
@makingglitches I noticed that your workaround script adds the -ltiff to a new line instead of the end of the first line for each file. I'm manually adding editing the files listed in the script.

Still, thank you so much for finding all these files and making this script!!!

**Comment by Matthew-Bradley** [comment]
the full list of files that -ltiff has to be added to the end of the first line in:
pluma apps/annotation/CMakeFiles/opencv_annotation.dir/link.txt
pluma apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/link.txt
pluma apps/visualisation/CMakeFiles/opencv_visualisation.dir/link.txt
pluma modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/link.txt
pluma modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/link.txt
pluma modules/core/CMakeFiles/opencv_perf_core.dir/link.txt
pluma modules/core/CMakeFiles/opencv_test_core.dir/link.txt
pluma modules/dnn/CMakeFiles/opencv_perf_dnn.dir/link.txt
pluma modules/dnn/CMakeFiles/opencv_test_dnn.dir/link.txt
pluma modules/features2d/CMakeFiles/opencv_perf_features2d.dir/link.txt
pluma modules/features2d/CMakeFiles/opencv_test_features2d.dir/link.txt
pluma modules/gapi/CMakeFiles/opencv_perf_gapi.dir/link.txt
pluma modules/gapi/CMakeFiles/opencv_test_gapi.dir/link.txt
pluma modules/highgui/CMakeFiles/opencv_test_highgui.dir/link.txt
pluma modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/link.txt
pluma modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/link.txt
pluma modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/link.txt
pluma modules/ml/CMakeFiles/opencv_test_ml.dir/link.txt
pluma modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/link.txt
pluma modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/link.txt
pluma modules/photo/CMakeFiles/opencv_perf_photo.dir/link.txt
pluma modules/photo/CMakeFiles/opencv_test_photo.dir/link.txt
pluma modules/stitching/CMakeFiles/opencv_perf_stitching.dir/link.txt
pluma modules/stitching/CMakeFiles/opencv_test_stitching.dir/link.txt
pluma modules/video/CMakeFiles/opencv_perf_video.dir/link.txt
pluma modules/video/CMakeFiles/opencv_test_video.dir/link.txt
pluma modules/videoio/CMakeFiles/opencv_perf_videoio.dir/link.txt
pluma modules/videoio/CMakeFiles/opencv_test_videoio.dir/link.txt

**Comment by Matthew-Bradley** [comment]
this is relative to the build directory, btw

**Comment by makingglitches** [comment]
> @makingglitches I noticed that your workaround script adds the -ltiff to a new line instead of the end of the first line for each file. I'm manually adding editing the files listed in the script.
> 
> 
> 
> Still, thank you so much for finding all these files and making this script!!!

Finally recognition ! Lol
