### ISSUE TITLE
4.5.2 documentation still mentions an object detection trainer that doesnt exist

### ISSUE THREAD

**Issue by makingglitches** [opencv/opencv#20301]
This needs updated  badly.
I just started using opencv, and there is a large pitfall where training the classifier doesn't seem to have the right instructions attached.

https://docs.opencv.org/4.5.2/dc/d88/tutorial_traincascade.html

In the issue below, this is discussed. Note the date.
https://github.com/opencv/opencv/issues/13231

So I'm just seeking clarification as a beginner, should I not be using the object classifer in opencv ? Should I be using some alternative ?  If the classifer is fine, what should I be doing to prepare positive samples ?

**Comment by makingglitches** [comment]
I think the last time we went into this the response was that opencv's is useful for learning blah blah, but there was no clarification as to what to use in its place or explanation as to why our civilization has turned into a useless husk.

**Comment by alalek** [comment]
Feel free to add a note to the beginning of this tutorial page.

---

> So I'm just seeking clarification as a beginner, should I not be using the object classifer in opencv ? Should I be using some alternative ? If the classifer is fine, what should I be doing to prepare positive samples ?

You will not find these answers in this bug/feature tracker. Your questions should go to OpenCV Users forum as mentioned in another issue.

**Comment by makingglitches** [comment]
> Feel free to add a note to the beginning of this tutorial page.
> 
> 
> 
> ---
> 
> 
> 
> > So I'm just seeking clarification as a beginner, should I not be using the object classifer in opencv ? Should I be using some alternative ? If the classifer is fine, what should I be doing to prepare positive samples ?
> 
> 
> 
> You will not find these answers in this bug/feature tracker. Your questions should go to OpenCV Users forum as mentioned in another issue.

Well does seem important 
The tool is missing 
And that was the variety of the responses from three years before this date, that this detector has been superseded by dnn.
