### ISSUE TITLE
Error using DNN inference output feature map

### ISSUE THREAD

**Issue by TD-wzw** [opencv/opencv#20307]
The output feature graph dimension should be [14,128,128], but I got [1,-1,-1] instead.

**Comment by TD-wzw** [comment]
[mlsd_cuverANDline.sim.zip](https://github.com/opencv/opencv/files/6713015/mlsd_cuverANDline.sim.zip)
Please unzip and view: mlsd_cuverandline.sim.onnx

**Comment by TD-wzw** [comment]
这是我的模型

**Comment by TD-wzw** [comment]
The input size is [1,4,512,512]

**Comment by TD-wzw** [comment]
Please help me

**Comment by berak** [comment]
@TD-wzw our help site is at

https://forum.opencv.org/

(please ask there instead, this is the library bug tracker, thank you)

**Comment by TD-wzw** [comment]
Okay, thank you
