### ISSUE TITLE
Segmentation Fault (core dump)

### ISSUE THREAD

**Issue by pranjalchanda08** [opencv/opencv#20311]
Segmentation Fault occurs when **cv2.waitKey(1)==ord('q')** gets **any key press**.

OS: Ubuntu 20.04
OpenCV version: 4.5.2.54 

Code:

```py

    import cv2
    cap = cv2.VideoCapture(video_src)
    while cv2.waitKey(1) != (ord('q') or ord('Q')):
        success, img = cap.read()
        if not success:
            print("read_err")
            break
        # Flip input image horizontally
        flip_image = cv2.flip(img, 1)
        cv2.imshow("Output", flip_image)

    cap.release()
    cv2.destroyAllWindows()
```
Installation:
```sh
pip3 install opencv-python
```
![image](https://user-images.githubusercontent.com/40349163/123504708-6abb2000-d678-11eb-9569-be4ff776e683.png)

**Comment by alalek** [comment]
You should not install both `opencv-python` / `opencv-contrib-python` packages.
This setup is considered as invalid.

Also check issues here: https://github.com/opencv/opencv-python/issues (there are several conflicts from Qt side)

**Comment by pranjaldronzer** [comment]
Hi @alalek,
I quickly uninstalled both the packages and reinstalled only **opencv-python** still facing the same issue.

**Comment by asmorkalov** [comment]
@pranjalchanda08 Could you provide full application output and output of `cv2.getBuildInformation()` call?

**Comment by pranjalchanda08** [comment]
Hi @asmorkalov,

Attaching the log file of the program output. [log_seg_fault.txt](https://github.com/opencv/opencv/files/6769615/log_seg_fault.txt)

Please find the project link: https://github.com/pranjalchanda08/MediaPipe-Project/blob/master/utils/hand_tracking.py

**Comment by pranjalchanda08** [comment]
Hi @asmorkalov,

Any updates on this?

**Comment by asmorkalov** [comment]
@pranjalchanda08 Could you try this fix: https://github.com/opencv/opencv/pull/20597

**Comment by SharwanGuriya** [comment]
i had the same issue with opencv version 4.5.2. downgrading the opencv library to 4.4.0.46 solved it just fine

**Comment by asmorkalov** [comment]
The issue is not reproducible with OpenCV-Python4.8.1 any more.
