### ISSUE TITLE
Can't find VTK

### ISSUE THREAD

**Issue by beew** [opencv/opencv#20314]
I am trying to build opencv 4.5.2  with vtk. I have vtk-8.2.0 installed in /home/user_name/vtk and set

-DVTK_DIR=/home/user_name/vtk/lib/cmake/vtk-8.2, which is the directory that contains VTKConfig.cmake

But cmake is still complaining VTK_DIR not found. Tried with vtk's build directory still won't work (why would normal people keep the huge build directory around after install anyway?)

OS Ubuntu 20.04.

**Edited**: same issue with opencv master.

**Comment by beew** [comment]
So master found and build with VTK-9.0.1, OpenCV 4.5.2 found VTK 9.0.1 but build failed with VTK on.

**Comment by MarchAwake** [comment]
@beew  have you solve this problem?

**Comment by beew** [comment]
> @beew have you solve this problem

Build opencv from master with vtk-9. I haven't rebuild it since my last post here, so not sure what it is like with opencv 4.5.3

**Comment by asmorkalov** [comment]
@beew May I close the bug?

**Comment by beew** [comment]
Sure. 4.5.3 works.
