### ISSUE TITLE
Unsupported asymmetric padding in convolution layer in function 'cv::dnn::BaseConvolutionLayerImpl::BaseConvolutionLayerImpl'

### ISSUE THREAD

**Issue by Zrufy** [opencv/opencv#20342]
i tried to convert a mobilenetv3 for classification with onnx but unfortunately i can't go ahead for this error.does anyone know a solution?I'm using opencv for the inference.

**Comment by Zrufy** [comment]
Another error is "Unsupported asymmetric padding"

**Comment by asmorkalov** [comment]
Duplicate for:
- https://github.com/opencv/opencv/issues/19316
- https://github.com/opencv/opencv/issues/19499
