### ISSUE TITLE
OpenCV 5.0: winpack is broken (2021-06-10)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#20349]
Last good build: http://pullrequest.opencv.org/buildbot/builders/5_x_winpack-build-win64-vc16/builds/57
- commit: b91e0dca90d56045b29796d416cbd1bd7b130544

Bad build: http://pullrequest.opencv.org/buildbot/builders/5_x_winpack-build-win64-vc16/builds/58
- commit: 4dc811946daebe257c0f6106e548d3c4b6c49309

Related PR: #20225

**Comment by alalek** [comment]
Nightly Windows debug build is broken too: http://pullrequest.opencv.org/buildbot/builders/5_x_noOCL_noICV_noSSE-win64-vc14-debug/builds/60

**Comment by asmorkalov** [comment]
@opencv-alalek Is the issue still relevant? Could you take a look on it?
