### ISSUE TITLE
Halide integration doesn't work with recent versions (10+)

### ISSUE THREAD

**Issue by alexreinking** [opencv/opencv#20353]
OpenCVDetectHalide.cmake assumes variables are set by the Halide CMake package that it does not (has never?).

https://github.com/opencv/opencv/blob/167bac23aa96972acaef51e49ee3b33b8b6b2479/cmake/OpenCVDetectHalide.cmake#L9-L16

As a result, attempting to build against a recent version of Halide incorrectly succeeds during configuration only to fail to find `Halide.h` during the build.

Locally, I found that replacing the contents of `cmake/OpenCVDetectHalide.cmake` with the following works at least as far as the build succeeding:

```
find_package(Halide REQUIRED)

set(HAVE_HALIDE TRUE)
set(HALIDE_LIBRARIES Halide::Halide)
list(APPEND OPENCV_LINKER_LIBS ${HALIDE_LIBRARIES})
```

**Comment by alalek** [comment]
@alexreinking Thank you for the report!
Could you please check this PR #20354 in your environment?

**Comment by alexreinking** [comment]
Thanks @alalek - I just tested it and it seems to work for me!
