### ISSUE TITLE
problems after #20281

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#20352]
i see the following problems after #20281 ( Platform: Windows 10.0.19042 AMD64 )

1. `imshow( winname, img )` ( without prior namedWindow ) by default the window was created with the `cv::WINDOW_AUTOSIZE` flag. now the window is resizable!
2. `[Windows Backend Only] Pressing Ctrl+S will show a dialog to save the image.` don't work.
3. `[Windows Backend Only] Pressing Ctrl+C will copy the image to the clipboard.` copies the image to the clipboard but triggered waitKey() as a key pressed. i think it was waiting another key press before..

**Comment by alalek** [comment]
Hi @sturkmen72, thank you for the report!

1.
C++ namedWindow uses WINDOW_AUTOSIZE by default ([4.5.1](https://github.com/opencv/opencv/blob/4.5.1/modules/highgui/include/opencv2/highgui.hpp#L317)).
Similar value should be used [here](https://github.com/opencv/opencv/blame/167bac23aa96972acaef51e49ee3b33b8b6b2479/modules/highgui/src/window.cpp#L993).
**Confirmed**. All backends are affected (Win32, GTK, Qt).

BTW, documentation:
```
       WINDOW_NORMAL     = 0x00000000, //!< the user can resize the window (no constraint) / also use to switch a fullscreen window to a normal size.
       WINDOW_AUTOSIZE   = 0x00000001, //!< the user cannot resize the window, the size is constrainted by the image displayed.
```

BTW, there was request to allow resizing windows (e.g., for full screen presentations). Perhaps we should revise highgui behavior for OpenCV 5.0.

2.
**Confirmed**
waitKey() is returned only. No dialog.

3.
**Confirmed** (clipboard copy + waitKey())
4.5.1 also triggers waitKey() with Ctrl+C.


---

Please take a look on this PR: #20355

**Comment by sturkmen72** [comment]
@alalek thanks. #20355 resolves the issue. BTW `WINDOW_KEEPRATIO` seems not implemented ( at least on Windows ). if so, a note on documentation will be fine.
