### ISSUE TITLE
cv::dnn::dnn4_v20210301::readNetFromDarknet

### ISSUE THREAD

**Issue by Bengeljo** [opencv/opencv#20356]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio Code

##### Detailed description
So I am trying to write a bot that can play a game. I trained yolov5 with custom data and try now to implement it into the bot. For some reason the cv won't read the data. So the line is " WEIGHT_FILE = os.path.abspath('./best.pt') and the error code is the titel of this issue. Since I thought I messed up the simple path maybe the absolute path will work, since it did for many other people when I searched for this issue. Yet it won't, I even wrote a simple one that request and prints the absolute path and it matched, the data is present yet cv won't find it. Does anyone has  a clue how to solve this problem ?? 

The whole error is
net = cv2.dnn.readNetFromDarknet(CONFIG_FILE, WEIGHT_FILE)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-ttbyx0jz\opencv\modules\dnn\src\darknet\darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file:

Does maybe a downgrade to a earlier version of CV may work ??

**Comment by heuripedes** [comment]
* Whenever I run into that error it's always because my .cfg file is broken or corrupted.
* Darknet models are usually stored as a pair of `.cfg` and  `.weights`  files. Your `.pt` extension gives me the impression that you are trying to load something made for a different framework. 

My suggestions are:
1. try readNet instead (it's what I use with darknet models)
2. try your cfg and weights files on the darknet executable (see https://pjreddie.com/darknet/install/ for instructions, but clone https://github.com/AlexeyAB/darknet instead of pjreddie's repository)

**Comment by Bengeljo** [comment]
> * Whenever I run into that error it's always because my .cfg file is broken or corrupted.
> * Darknet models are usually stored as a pair of `.cfg` and  `.weights`  files. Your `.pt` extension gives me the impression that you are trying to load something made for a different framework.
> 
> My suggestions are:
> 
> 1. try readNet instead (it's what I use with darknet models)
> 2. try your cfg and weights files on the darknet executable (see https://pjreddie.com/darknet/install/ for instructions, but clone https://github.com/AlexeyAB/darknet instead of pjreddie's repository). if it doesn't work then there's something wrong with your files.

Thanks for the help, after like 5 hours of trying and getting everything ready I am still not getting it running. I am using yolov5 and I guess the darknet models are for yolov4 and below. 
And he can now find the weight that's a win but now I get this cv2.error: OpenCV(4.5.2) C:\OpenCV_CUDA\opencv-4.5.2\modules\dnn\src\darknet\darknet_io.cpp:931: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream' 
But thanks alot for your help

**Comment by BZsun** [comment]
I have encountered the same error here, have you resolved it？
