### ISSUE TITLE
please add to gen_pattern.py the option to create radon checkerboard

### ISSUE THREAD

**Issue by mosheliv** [opencv/opencv#20364]
##### System information (version)

- OpenCV => 4.5.2
- Operating System / Platform => Ubuntu 18.05
- Compiler => python

##### Detailed description

in your documentation there is an example of a fancy checkerboard with markers etc under findChessboardCornersSB() (see [here](https://docs.opencv.org/4.5.2/checkerboard_radon.png)). This pattern works particularily well in my experiments but gen_pattern can't create it. It would be really helpfull if you could add it.

**Comment by catree** [comment]
**/cc** @D-Alex

Could you provide a way to generate the radon checkerboard pattern?
