### ISSUE TITLE
Error during compilation while I was trying to build opencv from source

### ISSUE THREAD

**Issue by whizbuzzer** [opencv/opencv#20398]
##### Detailed description

So, I was trying to build OpenCV fromsource along with the contrib modules by referring to https://linuxize.com/post/how-to-install-opencv-on-ubuntu-20-04/. Everything supposedly went fine until "make -j8" (yes, I checked the number of cores with "nproc", and it was 8). Then, I got the following error:

[  0%] Built target ittnotify
[  0%] Built target opencv_videoio_plugins
[  0%] Generate opencv4.pc
[  0%] Built target opencv_highgui_plugins
[  0%] Built target quirc
[  0%] Built target ippiw
CMake Error at /home/anprabh1/opencv_build/opencv/cmake/OpenCVUtils.cmake:1981 (include):
  include could not find load file:

    cmake/vars/EnableModeVars.cmake
Call Stack (most recent call first):
  /home/anprabh1/opencv_build/opencv/cmake/OpenCVGenPkgconfig.cmake:116 (include)

[  0%] Built target ade
make[2]: *** [CMakeFiles/gen-pkgconfig.dir/build.make:59: unix-install/opencv4.pc] Error 1
make[1]: *** [CMakeFiles/Makefile2:5064: CMakeFiles/gen-pkgconfig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Built target gen_opencv_python_source
[  0%] Built target libprotobuf
[  0%] Built target opencv_core
make: *** [Makefile:163: all] Error 2

Any suggestion on fixing this?

**Comment by alalek** [comment]
`pkg-config` generation is not supported anymore: #13154

**Comment by alalek** [comment]
You can try relative path here: https://github.com/opencv/opencv/blob/9e42e04b4a4c11059d067faa2bcb63f4736bd54b/cmake/OpenCVUtils.cmake#L1981

**Comment by alalek** [comment]
Please check this patch in your build environment: #20400

**Comment by asmorkalov** [comment]
@whizbuzzer Friendly reminder.

**Comment by whizbuzzer** [comment]
@asmorkalov Sincerest apologies for the late reply! Thank you for your help. I switched to Ubuntu 18.04 instead as I had more resources for it.

**Comment by whizbuzzer** [comment]
@alalek Thank you!
