### ISSUE TITLE
Qt mingw32 compile error! 

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencv/opencv#20404]
System information (version)

Qt mingw32 compile opencv, when i cmoplie it, then make install, it error:
[ 56%] Linking CXX shared library ..\..\bin\libopencv_wechat_qrcode453.dll
C:/Qt/Qt5.13.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/lib/../lib/libiconv.a(localcharset.o):localcharset.c:(.text+0x73): undefined reference to `_imp__GetACP@0'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [modules\wechat_qrcode\CMakeFiles\opencv_wechat_qrcode.dir\build.make:996: bin/libopencv_wechat_qrcode453.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:4616: modules/wechat_qrcode/CMakeFiles/opencv_wechat_qrcode.dir/all] Error 2
mingw32-make: *** [Makefile:181: all] Error 2

**Comment by berak** [comment]
this is from the wechat_qr module in contrib, cmake has some trouble finding libiconv in the mingw install

see [previous discussion here](https://github.com/opencv/opencv_contrib/pull/2916) (2 possible fixes)

**Comment by lebarsfa** [comment]
It seems iconv with MinGW still causes problems (depending on the MinGW version, 32 bit vs 64 bit, OpenCV configuration dynamic vs static libraries...?), so maybe it would be safer to revert the changes from https://github.com/opencv/opencv_contrib/pull/2931/files, unless there is a better solution.

The tests I made are on https://github.com/lebarsfa/Packages/actions/runs/2807027445 (need to be logged in GitHub), see e.g. the bottom of https://github.com/lebarsfa/Packages/runs/7700887685?check_suite_focus=true and https://github.com/lebarsfa/Packages/runs/7700888038?check_suite_focus=true for 2 types of problems i.e. 
```bash
The link interface of target "opencv_wechat_qrcode" contains:

    Iconv::Iconv

  but the target was not found.
```
when trying to build a test app with the static version of OpenCV, or the message from the OP of this issue when building OpenCV itself with `BUILD_SHARED_LIBS=ON`. Note that there are also configurations that appear to work (with a simple test program possibly not calling iconv), which was probably confusing. Applying https://github.com/lebarsfa/Packages/commit/4b271d2b5c2ed6eb36a5e140c0e9e9fffb7977a7#diff-e13272f82adfb96ae33f958418128ddbc9bd47bc4819f0ddb82ca6358f365bc6 to revert [#2931](https://github.com/opencv/opencv_contrib/pull/2931) appeared to solve the problem, see https://github.com/lebarsfa/Packages/actions/runs/2806284727.
