### ISSUE TITLE
sortIdx error

### ISSUE THREAD

**Issue by studiouspan** [opencv/opencv#20411]
##### System information (version)

- OpenCV => :4.4.0:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Visual Studio 2017:

##### Detailed description
Mat c1 = (Mat_<double>(3, 3) << 1, 5, 6, 2, 4, 2, 5, 9, 3);
Mat c2;
sortIdx(c1, c2, SORT_EVERY_COLUMN + SORT_ASCENDING);

expect C2 to be equal to：
0,1,2
1,0,0
2,2,1
But the result of C2 is：
0,1,1
1,0,2
2,2,0

Why？

**Comment by alalek** [comment]
Works as expected.
3rd column values: 6,2,3
`indexes` to get sorted array are `1,2,0` -`array[indexes[i]]` has sorted values.
`2,0,1` is not correct here. You probably want "inverted" variant of indexes.

Look on test code to see how it is expected to work.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by studiouspan** [comment]
> Works as expected.
> 3rd column values: 6,2,3
> `indexes` to get sorted array are `1,2,0` -`array[indexes[i]]` has sorted values.
> `2,0,1` is not correct here. You probably want "inverted" variant of indexes.
> 
> Look on test code to see how it is expected to work.
> 
> Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

I see. Thank you for your prompt！
