### ISSUE TITLE
Exception when destroyWindow is called on a non existing window

### ISSUE THREAD

**Issue by benedetto-michelozzi** [opencv/opencv#20417]
- OpenCV = 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

when destroyWindow is called on a non existing window an exception is issued.

Example:
int main(int argc, char** argv)
{
    cv::destroyWindow("asdf");
. . . . .
}
 stderr:
"OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.3) Error: Null pointer (NULL window: 'asdf') in cvDestroyWindow, file D:\3rdParty\OpenCV\opencv-4.5.3\modules\highgui\src\window_w32.cpp, line 1246"

the problem is that behaviour is different in the previous OpenCV versione ( no error issued )

I think that when the window doesn't exits no error shall be issued

**Comment by alalek** [comment]
Won't fix.
Invalid parameters should not be passed into functions. Allowing that as no-op is error prone behavior which should be avoided.
