### ISSUE TITLE
OpenCV Error: Assertion failed (tlsSlotsSize> slotIdx) in gather，

### ISSUE THREAD

**Issue by serendipity999** [opencv/opencv#20415]
##### System information (version)
- OpenCV ==4.5.1
- Operating System / Platform => ARM-LINUX 64 Bit
- Compiler => GCC6.3
##### Detailed description

Steps to reproduce
1、generate a dynamic library libK.so that used dynamic library of OpenCV 4.5.1 
2、write a program P that use libK.so and OpenCV. but this time OpenCV is 2.4.10 version.
3、when I execute this program，this Error Occured

**Comment by alalek** [comment]
Multiple OpenCV versions in one process are not supported officially.

To make them work your should completely hide OpenCV symbols from each other in both binaries (e.g., properly link with with **static** opencv binaries).

**Comment by serendipity999** [comment]
> Multiple OpenCV versions in one process are not supported officially.
> 
> To make them work your should completely hide OpenCV symbols from eac
