### ISSUE TITLE
Can't import ONNX model produced by keras2onnx

### ISSUE THREAD

**Issue by chirag900** [opencv/opencv#20439]
##### System information (version)
- OpenCV(4.5.3-dev)
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc 9.3.0

Description of the issue:
I am using the caption model which is converted using keras2onnx. I am unable to load the model by using readNet or readNetFromONNX in opencv. And I have installed Opencv from source (OpenCV(4.5.3-dev)).

# steps to reproduce : 
Code is as below : (C++)
```
std::string Caption_Model = "Caption_Model.onnx";
cv::dnn::Net net = cv::dnn::readNetFromONNX(Caption_Model);
```
Error message:
```
Error : Node [Gather]:(embedding_1/Identity:0) parse error: OpenCV(4.5.3-dev) /opencv_build/opencv/modules/dnn/src/onnx/onnx_importer.cpp:356: error: (-5:Bad argument) Blob casted not found in const blobs in function 'getBlob'
Aborted (core dumped)
```

You can find the architecture of the caption model in the screenshot.
![Caption_Model](https://user-images.githubusercontent.com/59944312/126475295-dfc8f076-22d2-4b27-b15d-07d7a6f4a135.png)

**Comment by JulieBar** [comment]
@chirag900 could you please provide your model as a reproducer? You can cut it or fill it with random weights.

**Comment by asmorkalov** [comment]
Related issue: https://github.com/opencv/opencv/issues/21118
