### ISSUE TITLE
gcc: error: C:opencvbuildmodulescorevs_version.rc: No such file or directory

### ISSUE THREAD

**Issue by hacktronics** [opencv/opencv#20449]
OpenCV: opencv-4.5.3
Windows: 10
Ming: x86_64-7.3.0-posix-seh-rt_v5

[ 37%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
gcc: error: C:opencvbuildmodulescorevs_version.rc: No such file or directory
gcc: fatal error: no input files
compilation terminated.
/usr/bin/windres: preprocessing failed.
modules\core\CMakeFiles\opencv_core.dir\build.make:1435: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj' failed
mingw32-make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
CMakeFiles\Makefile2:3482: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
mingw32-make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:164: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by berak** [comment]
hi, are there any more warnings before that, e.g about OPENCV_ALLOCATOR_STATS_COUNTER_TYPE ?

have a look at similar issues (possible duplicate):

https://github.com/opencv/opencv_contrib/issues?q=sort%3Aupdated-desc
