### ISSUE TITLE
hey can u solve this error plz tell me the solution @dkurt  I got another error when i add concatenate layer, it gives me this error:

### ISSUE THREAD

**Issue by Yogeshkumar1234** [opencv/opencv#20477]
@dkurt  I got another error when i add concatenate layer, it gives me this error:
Traceback (most recent call last):
  File "dnn_test.py", line 4, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('frozen_graph.pb')
cv2.error: C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_import
er.cpp:1487: error: (-2) Unknown layer type ResizeBilinear in op upsample_concat
1/ResizeBilinear in function cv::dnn::experimental_dnn_v3::`anonymous-namespace'
::TFImporter::populateNet

_Originally posted by @khaledelmadawi in https://github.com/opencv/opencv/issues/11452#issuecomment-386870343_

**Comment by Yogeshkumar1234** [comment]
can u tell me this error solution

**Comment by alalek** [comment]
> experimental_dnn_v3

Avoid using of outdated releases.

Complete minimal reproducer is required.
