### ISSUE TITLE
Issue in python template matching (CUDA)

### ISSUE THREAD

**Issue by Sanji515** [opencv/opencv#20484]
`import cv2 as cv`
`src = cv.imread("maharo.jpg ", cv.IMREAD_GRAYSCALE)`
`h, w = src.shape[::-1]`
`ex_src = cv.resize(src, (h*10, w*10), interpolation=cv.INTER_CUBIC)`
`tmpl = ex_src[1000:1200, 1000:1200]`
`gsrc = cv.cuda_GpuMat()`
`gtmpl = cv.cuda_GpuMat()`
`gresult = cv.cuda_GpuMat()`
`gsrc.upload(ex_src)`
`gtmpl.upload(tmpl)`
`matcher = cv.cuda.createTemplateMatching(cv.CV_8UC1, cv.TM_CCOEFF_NORMED)`
`gresult = matcher.match(gsrc, gtmpl)`

I'm using the above code to match the image but it throws me error on line `gresult = matcher.match(gsrc, gtmpl)`):

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.2.0) /home/ubuntu/opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp:416: error: (-217:Gpu API call) invalid configuration argument in function 'horisontal_pass_8u_shfl'

I'm running this code on EC2 instance type `p2.8xlarge`
Cuda enabled devies = 8. (as the output of command `cv.cuda.getCudaEnabledDeviceCount()` gives 8)

CV2 Version: 4.2.0
Cuda: 11.0
Python: 3.8

**Comment by JulieBar** [comment]
@Sanji515 Did you build and install OpenCV package from source? Could you please provide CMake output?
Also could you please try the latest release version?
