### ISSUE TITLE
 Cannot determine an origin framework with a name '/storage/..../model.onnx' in function readNet

### ISSUE THREAD

**Issue by iglaweb** [opencv/opencv#20482]
Trying to load neural model with DNN in Java. 

Exception thrown while loading: Cannot determine an origin framework with a name <path to the model> (but seems it should be framework name here e.g. 'onnx').
> Dnn.readNet()

If I use specific model type functions, it works:
> Dnn.readNetFromONNX()

- OpenCV => 4.5.2
- Operating System / Platform => Android 10
- Language: Java 7

**Comment by berak** [comment]
@iglaweb , 
can you show us, how you invoke `Dnn.readNet()` ?
what arguments do you pass ?

how did it end up here ? 
https://github.com/opencv/opencv/blob/da07ad16c11598a54ba31bb5c09692c5abcf9f7e/modules/dnn/src/dnn.cpp#L5511

(probably the wrong method overload)

**Comment by iglaweb** [comment]
> can you show us, how you invoke `Dnn.readNet()` ?
> what arguments do you pass ?

I just used Dnn.readNet("path/to/model.onnx") and the error occurred where framework variable was assigned to the model path unexpectedly.

**Comment by berak** [comment]
that should have called 

https://docs.opencv.org/master/javadoc/org/opencv/dnn/Dnn.html#readNet(java.lang.String)

but the error is from

https://docs.opencv.org/master/javadoc/org/opencv/dnn/Dnn.html#readNet(java.lang.String,org.opencv.core.MatOfByte)
