### ISSUE TITLE
CMAKE fails OpenCV 4.5.3 with QT6

### ISSUE THREAD

**Issue by Ivan-Cherkasov** [opencv/opencv#20499]
OpenCV => 4.5.3
Operating System / Platform =>Windows
CMAKE => 3.20.4
QT6

It's looks like cmake looking for QT5 as highest version.

![error](https://user-images.githubusercontent.com/88431518/128164286-3c2be8b3-8c23-437a-bf46-9c8ae8dcccc5.png)

**Comment by mshabunin** [comment]
AFAIK, Qt 6 support has not been implemented yet thus marking this ticket as "feature".

**Comment by alalek** [comment]
You may want to check this PR: #20183

**Comment by alalek** [comment]
Lets keep this issue open until we have fix on master branch.

**Comment by Ivan-Cherkasov** [comment]
Of course, thanks. I'm try to fix using  PR: #20183 right now.

**Comment by Ivan-Cherkasov** [comment]
Building ended with error.
![error_2 png](https://user-images.githubusercontent.com/88431518/128198599-57e56935-1c9f-417a-adf9-56e4756bbe29.jpg)

Find in QT blog issue, that "**The names are confusing, no doubt about that. At least with 5.4 the message is finally clear: Avoid everything starting with QGL and go for QOpenGL**"

https://www.qt.io/blog/2014/09/10/qt-weekly-19-qopenglwidget
