### ISSUE TITLE
Help me fix error Python on Raspberry [WARN: 0] global: select() timeout

### ISSUE THREAD

**Issue by trannnthuong** [opencv/opencv#20504]
when I run the code, I get an error, how can I fix it, thanks
[ WARN:0] global /tmp/pip-wheel-pd499c9i/opencv-python_3a15e83eee864e65b7311a199a94e9f1/opencv/modules/videoio/src/cap_v4l.cpp (1001) tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
127.0.0.1 - - [05/Aug/2021 03:04:32] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [05/Aug/2021 03:04:32] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by zhenglisai** [comment]
opencv_python-4.5.3.56-cp37-cp37m-manylinux2014_aarch64.whl
open two camera, 
only the first can read, the second camera will failed with 
[ WARN:0] global /tmp/pip-req-build-hwenbn4e/opencv/modules/videoio/src/cap_v4l.cpp (1001) tryIoctl VIDEOIO(V4L2:/dev/video2): select() timeout.

import cv2
a = cv2.VideoCapture(0)
b = cv2.VideoCapture(2)
a.read()
b.read()  <-- this line report error
