### ISSUE TITLE
readNetFromTensorflow: Input layer not found in network with switch operations

### ISSUE THREAD

**Issue by liyingyinsimon** [opencv/opencv#20501]
I used both c++ and python in google colab to read the net using opencv but got errors.
The .pb file is from [hed_graph.pb](https://github.com/fengjian0106/hed-tutorial-for-document-scanning/tree/master/checkpoint). Is it necessary to have the .pbtxt file also?

In colab,
`net = cv2.dnn.readNetFromTensorflow("model.pb")`

The error I got is `
error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:544: error: (-2:Unspecified error) Input layer not found: hed/dsn5/conv2d_transpose/Shape in function 'connect'`

Thank you!

**Comment by alalek** [comment]
> OpenCV(4.1.2)

Avoid using of outdated releases.

**Comment by liyingyinsimon** [comment]
You mean openCV? Will it be a problem the network is using Tensorflow 1.x?
Thank you!

**Comment by liyingyinsimon** [comment]
> > OpenCV(4.1.2)
> 
> Avoid using of outdated releases.


You mean openCV? Will it be a problem the network is using Tensorflow 1.x?
Thank you!

**Comment by asmorkalov** [comment]
No, TF 1.x is not a problem. Please try latest OpenCV release. The team makes a lot of DNN fixes and improvements for each release.

**Comment by berak** [comment]
@liyingyinsimon  on colab:

    pip install opencv-python==4.5.3.56

(restart the runtime !)

    !wget https://github.com/fengjian0106/hed-tutorial-for-document-scanning/raw/master/checkpoint/hed_graph.pb

```
import cv2
#cv2.__version__
net = cv2.dnn.readNet("hed_graph.pb")
```


result:

```
error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:2445: error: (-2:Unspecified error) Input layer not found: hed/dsn5/conv2d_transpose/Shape in function 'connect'
```

**Comment by liyingyinsimon** [comment]
Is it because it is a frozen graph but not a saved model? The goal is to load the model in c++. I tried cppflow, converting the model to some other format like .onnx, or using the .ckpt on the github but all having some problems. Could someone suggest a way to import the model or weight in c++?
Thank you!

**Comment by asmorkalov** [comment]
The network contains "switch" operation. It's control flow operation that is not supported by OpenCV. See https://github.com/opencv/opencv/wiki/FAQ#dnn

**Comment by liyingyinsimon** [comment]
I am not familiar with neural network, where could I see this "switch" operation? 
It seems there are some problems importing some nets or some "operations"?  Would it be better to use pytorch or it will still cause some problems if I use pytorch and read .onnx?
Thank you!

**Comment by asmorkalov** [comment]
There is wiki page about DNN support in OpenCV: https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV. I cannot guarantee that it's complete, but it gives understanding of list of supported models and frameworks. Also you can use [netron](https://netron.app/) tool that helps to understand the network structure and file internals. In addition to it OpenCV develops own debugging tool to easily  find support issues. See https://github.com/opencv/opencv/wiki/OpenCV-Debugging-Facilities

**Comment by liyingyinsimon** [comment]
Thank you!
