### ISSUE TITLE
Unable to install darknet with opencv version 4.5.3

### ISSUE THREAD

**Issue by sindhu1513** [opencv/opencv#20523]
While I am installing darknet with Cuda, got the following error:

Darknet_VERSION: 0.2.5.4
vcpkg not found, toolchain not defined, using integrated libs on win32
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
Selected CMAKE_CUDA_ARCHITECTURES: 52
Your setup does not support half precision (it requires CUDA_ARCHITECTURES >= 70)
PThreads4W_DLL_DIR: C:/Users/ivis/Documents/darknet-master/3rdparty/pthreads/include/../bin
PThreads4W_DEBUG_DLL_DIR: C:/Users/ivis/Documents/darknet-master/3rdparty/pthreads/include/../debug/bin
CMake Error at CMakeLists.txt:197 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

Configuring incomplete, errors occurred!
See also "C:/Users/ivis/Documents/darknet-master/CMakeFiles/CMakeOutput.log".
See also "C:/Users/ivis/Documents/darknet-master/CMakeFiles/CMakeError.log".

**Comment by asmorkalov** [comment]
```
Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
"OpenCV_DIR" to a directory containing one of the above files. If "OpenCV"
provides a separate development package or SDK, be sure it has been
installed.
```

**Comment by qinglingyu** [comment]
Has the problem  been solved? If so, would you tell me how to do it?

**Comment by idriszakaria05** [comment]
> Apakah masalahnya sudah terpecahkan? Jika ya, maukah Anda memberi tahu saya cara melakukannya?

of course, i hope you help me to this problem
