### ISSUE TITLE
i got (-215:Assertion failed error in  cv2.cvtColor(img,cv2.COLOR_BGR2RGB) function 

### ISSUE THREAD

**Issue by keval2232** [opencv/opencv#20522]
i am working on hand gesture moments in which i am using OpenCV to capture my webcam and hand moments but i got error like 
**cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'**  So can anybody help me to fix that error 
**Code is as below**
def findHands(self,img,draw=True):
        imgRGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)    
        self.results=self.hands.process(imgRGB)
        if self.results.multi_hand_landmarks:
            for handLms in self.results.multi_hand_landmarks:
                if draw:
                    self.mpDraw.draw_landmarks(img,handLms,self.mpHands.HAND_CONNECTIONS)

**Comment by imRajAryan09** [comment]
In your code while defining the man function change this line
`    cap = cv2.VideoCapture(0)
`
And it will work just fine
