### ISSUE TITLE
seeking approach for opencv code `CV_NODISCARD` and [[nodiscard]]

### ISSUE THREAD

**Issue by diablodale** [opencv/opencv#20544]
I'm seeking an approach for `CV_NODISCARD` that will work across all the compilers opencv 4.x and above supports.

The current approach is legacy for gcc and clang. Using `__attribute__((__warn_unused_result__))` on functions. No classes. And always at the end of the function declaration. This is supported on gcc 4.8.1 and higher (since 4.8.1 is needed for C++11).

MSVC supports the standard attribute approach of `[[nodiscard]]`. It can be on classes, functions, vars. And it goes before the name of the item. At the end is not allowed. The support is available with VS2017 v15.3 and later; with /std:c++17 or higher.

So these are somewhat mutually exclusive. One or the other compiler (gcc vs msvc) will complain with warnings. It should still compile. Both compilers have a method to disable the warnings, but I read on the internet that on some versions of gcc, it ignores the ignore command and still puts the warning.

Does the core team have a recommendation?

**Comment by alalek** [comment]
If user don't want to see these warning then user can `#define CV_NODISCARD` (empty) before including OpenCV headers.

relates #11990

Currently it works on the methods too. I believe it is enough for many cases.

> No classes.

What is the use case for using with classes?
If we really need them then we can introduce dedicated macro for that (`CV_NODISCARD_CLASS`)

**Comment by diablodale** [comment]
Yes, your related PR above...at first...I added a clause in the ifdef for the MSVC compilers. But that fails because the C++17 standards doesn't allow [[nodiscard]] after the function name (like legacy GCC).

[[nodiscard]] is fantastic for classes. The STL itself uses them. And in some new code, I want to use them two. Good example is how the STL uses them.  In pseudocode...

```c++
class [[nodiscard]] unique_lock {...};  // yes, the core unique_lock for a std::mutex
```

When `[[nodiscard]]` is declared on a class, that prevents the very frequent coding error of...
```c++
std::unique_lock(mymutex);
...
```

Notice in the errant code, the _name_ of the variable is missing. This means that a unique_lock is constructed, locks the mutex, and then immediately destructs it, which unlocks the mutex. This means the code after doesn't have a lock. And this is a very common coding error.

By marking the class [[nodiscard]] the compiler will issue a warning. It will see that the result of the class's constructor is being discarded. Naturally, this is a useful warning and will prevent the same class of bugs that you want to fix when you marked the factories like `**::clone()`

If you are open to the idea of a new define, then I propose we make it work more broadly. Something like...

```c++
#if compiler/mode is C++17 standard compliant
    #define CV_NODISCARD_STD [[nodiscard]]
#else
    #define CV_NODISCARD_STD
#endif
```

Then new code can use `CV_NODISCARD_STD` in all code locations which are supported by C++11 attributes (classes, functions, vars, etc.). And then the `ifdef` conditionally makes it `[[nodiscard]]` or even the gnu specific one `[[gnu::warn_unused_result]]`
https://en.cppreference.com/w/cpp/language/attributes
https://infektor.net/posts/2017-01-19-using-cpp17-attributes-today.html

And since there are so _few_ locations that use the existing `CV_NODISCARD` I propose that we change them to use instead a macro `CV_NODISCARD_GCC` and then the new standards compiliant is `CV_NODISCARD`.

**Comment by alalek** [comment]
Thank you for the example!

I'm OK to add `CV_NODISCARD_STD`. Just please add the `#ifndef CV_NODISCARD_STD` pre-check to allow user defined values (or disable them) for this "hint" modifier.

**Comment by diablodale** [comment]
Would you also agree to my last sentence? So that the legacy gcc approach is put in its own define. It is only 5 places...a few new usage.

**Comment by alalek** [comment]
> CV_NODISCARD

I believe to we should deprecate it (put deprecation comment near it) and drop its usage in OpenCV.
Adopted `CV_NODISCARD_STD` macro with is enough.

**Comment by alalek** [comment]
GCC 5.4 emits warning with current `CV_NODISCARD`.
Try [here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGErqSuADJ4DJgAcj4ARpjEEtIADqgKhE4MHt6%2B/qRJKY4CIWGRLDFxUraY9vkMQgRMxAQZPn5cAXaYDmm19QSFEdGx8bZ1DU1ZrcM9fcWl8QCUtqhexMjsHAD06wDUCAQECQogm8CECF5RAHRoLOuoCYzIAG639wxP63gKCl6YCutmGgArJJJCYNABBcwAZlCyG8WC2JihbmQCgI%2BFQSOwYMhEOheCoDCwVC2bgAagB9cIAeQAIgBJIRucEAJVpOOhWy2BK2xNCmHQEApFIA4uE5G5hXMOWYoVyuXywqTKTSGUzWbStsKmHtiHgol4CJhhVBhQB3eoMCleBheJToCnEX5eWgEKVzLabLY6rb0Jho72PJh0JhRehbM2nLYitxuLZQi6gvGyrmVHmKgVCilwwzAKWIswANnMhd5mBoYUFwoQ/opOoIeoNRulybl8p51dr9cbhswWYtxCtNrtAsdztdUplbflZYrmGVVLpjOZbK1dd1%2Bt7Jv7luttvtY%2B%2BE4pcxbkJT8tcBKnqaJ19bV6oU4JRPLC9Vy41N9n/PfS/Vq7rAAVFsDCoAQCChMAWxRAAnrOTAugQWxAesU6PhyeIQjmXxbAAsj6JgAOxWFh4IJOctB4MgIA4jOBEEBA0pQqR4L0T6cICH2HrkouaoruyLEckRgmsZh4KhMhLDBgwTHCax7HIUwSIKfKTBXLQXFyUJEIzk6BDLAwWwaCpwm0hwCy0JwgK8H4HBaKQqCcG41jWFsChLCs87QjwpAEJoFkLAA1iAUIaBcXAABySJFZiAtFUJcIWXBEURgL6Jwki8CwEgaBopB2Q5TkcLwhz5f59kWaQcCwDAiAgEs%2ByGuQlDXAkdCDFCgT4EQZQyIIIhiOw5T8IIigqOolV%2BU6ay%2BWaxBMAknA8JZ1m2QFjmcNShoUchqAkqokWFgAtIWkhbMAyDIFsrQXGYWwQB4LDtfQxAFlCUJzLwFVaKepAIJgTBYHETEZRwWWkDlgLha0XBQvFgJEZIyUaGY0iFbwxWlSA5UBQsNX1W1HVkBQEBE69IDAK0Zh8HQRrEIcEBRBtUShPUsHLbw1xsII1IMLQHNTVg0lGOIQt4E6nSPL8G2YKoHS9pz5CCJUG1UVEC3ELBHhYBtDZ4Dl3BVVQBjAAoZJ4JgZrUq8SujcIojiCNsjjWoG26F1BhGCgrmWPo%2BqHJACx3NUhwcMd1JQqVlQdNULhEmMLSBES0wDH1uSpAIid6Bn1SpyUgxtDHnQCN0oyeM0ejtCXNQjL0/IzIXkzl5kSdolMDdpxICwecsqx6A2mCzVVVkcDZBUbcVh0nWdF1XTdXB3Q9LmWNYpBbLghAkO9ASkqgz3E%2B9n3fXjwUgLKFxEQAnFfRFHZISWFqjhZEWDEM5ZIV8XJFP9nVIcVQkirfQsE8ppY1sDjPyp9SAhTRhcDQUIr6xSvnDKEZhYpw1fqPKOoCiqcBPpVfGdUCYQCQI1XaLUyb7xek3AUW8%2Br20Gk7aQ9tXaTQcoPYepB5qLU5qtMe60wFbR2oaLY%2B0tjT1OudS611ASJmXtQw%2BPkvpQMIQsAGQNBig1Hu/EA0NcGY3wRA3GhDqrEKQOTWIlDLFxGAMCfKNBXSxEZszKarNmBayVtzRgBA%2BYCw2sLXMYsHL4Elo4aWYcHJywVkaJWklVZTXVprbWGA1gcL1IbFafBTbm0ttbW2Rt%2BoOyGkMVhSg3ZTV0AEL2xhfY2HVoHUGIc0hhy2BHHB1c44QFcNnAIwRO4F3TskTO6QK7jByMMvOAzZhFyqF0OuvSKhzNLnXfOMzm6NDGW3VZ0zC4908v3AInC%2BFg3HhjTaHBJGzxkVsOR51Hp1PXpvXqO915PRoW9ZRBDfrVQsYo161j/mDGAJ/FhdNnGUFcQ5dx7MvH7x5r4/mgsQmYBFsAYJvBQmxzwBE2W8tkCK0KfE0eDkknsx1mk76GSTkmyYGbC2VsbaMDtrIJhw0WEu3KewnQej9C5h9qvP2DT4DBwSKHTgbTI5tNpCyOQ4QAAq9I8LYApLxIQSrBK0jioWaOyy/DdITlsvQ/SihdwCLnNIiyLUFF2X1Tp8yeiLPtSsjuprBlVwWUatoOy3UzP2X3Ya00h4nNHmcyenArnSPnpIC4X97krysH7DePVt4%2BTeUCz5spAQqJ%2BoFf6gNgaUDPgCb%2BGgiIv0BOgos18UFYMytlPR%2BVzngLKqo36xbwqRTLRWqtL8b4pTBjg5tRjc1EPgCQshIiCCAoPhTGmdDep6EYY7dlRS2F6xmkrHhS0jb8LDUIjg20mp7QOkdKRWwcxGC2EReB8CFGztiO9MwOboEaMLdo%2BtkNG0GIudjExPyJ0oAzTOj5KAalETyrTJxDNIUszZp4wp3jeZIoCaioJlLSBYqljLKa0SCWxKJSrElvAyVawpRug2NKckMvycywpy6SnOzGly9258%2BXe1MIK%2BpAcRWOTFS0oxzr9U9K9cndAaym7WtGa3HOky0gSbtcXaoZdNkydmdil1DQFMesdaJ9uWnbXd0WAGgem7d2nMEXgy5Z7Z6Xugje8KGhl6POTfQ15e8H2ZrQS%2BtRMDz4xqvi/QshZb6SA0JFctUU34Nv0cOkqxi215tgQFoLIWkbhci5FQdlnDHxdHfwswOXf2Jb%2BtLBmaQQCSCAA) ([duplicate link](https://godbolt.org/z/67WTzaYz5)).

**Comment by diablodale** [comment]
Do you have an example with actual OpenCV api, and the actual OpenCV codebase, using the actual OpenCV cmake build?
I don't trust this simulation. it isn't real. The above 3 OpenCV components are radically different than that simulation.

My actual OpenCV code with 3.4 branch compiled with gcc 5.4.0 in linux would not issue a warning.

**Comment by alalek** [comment]
Looks good to me :+1:
