### ISSUE TITLE
stitcher->stitch Crash

### ISSUE THREAD

**Issue by aiiaji** [opencv/opencv#20551]
##### System information (version)
- OpenCV => 4.5.3
- Operating System / Platform => iOS 14.7.1 iOS 15
- Compiler => Xcode 12

##### Detailed description

When I use version 4.5.3 to call the stitch method on IOS, the puzzle times an error. I can't debug. I don't know what the reason is. Please take a look. This problem is accidental. It is particularly easy to report an error by transmitting iPad screenshots to sitch.
![661628822758_ pic_hd](https://user-images.githubusercontent.com/7530926/129342992-38fa8c5c-f26e-422b-b3ff-57cc3007a6ba.jpg)

The above figure shows the error stack.
code:

 Ptr<Stitcher> stitcher = Stitcher::create(cv::Stitcher::SCANS);
Stitcher::Status status = stitcher->stitch(imgs, pano);

**Comment by arunpersaud** [comment]
Not sure if this is the same or not, but I also get segfault when using the python api

```
In [1]: import cv2
In [2]: cv2.__version__
Out[2]: '4.5.3'

In [3]: A = cv2.imread('img01.jpg')
In [4]: B = cv2.imread('img02.jpg')
In [5]: s = cv2.Stitcher()
In [6]: s.stitch([A,B])
Segmentation fault: 11
```

This is on an M1 OS X laptop (11.5.2). I tried the brew installed opencv library and the pip installed library (contrib version). I also tried this on a linux machine with the same problem  for 4.5.3. An older version 3.x that is also available in my distribution works on the linux machine. Also using python 3.9.x

I'm not sure how to provide more details information, but happy to try things out if there are any commands that would be useful.

**Comment by berak** [comment]
@arunpersaud , not the same error. (but a well known problem with the python bindings)

    s = cv2.Stitcher()

**Comment by aiiaji** [comment]
@alalek @vpisarev @ilya-lavrenov @mshabunin  ，If it's convenient, please help to see how to solve it. Thank you very much

**Comment by asmorkalov** [comment]
@aiiaji we need at least archive with images (2-3-4) and steps to reproduce the issue. You can use stitching or stitching_detailed example to do it.
