### ISSUE TITLE
cv::dnn::readNetFromModelOptimizer  InferenceEngine::GeneralError

### ISSUE THREAD

**Issue by Jaren-Li** [opencv/opencv#20596]
System information (version)
- OpenCV => 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio Code

Detailed description
In a few days ago, I tried using opencv and openvino compiled with MSVC on VSCode.I can now normal use opencv on vscode, but when I use CV: : : within DNN: readNetFromModelOptimizer read yolov5s, but out of an interrupt. I have converted yolov5s to IR format.This model is the official yolov5s model, not trained by myself, I just converted the format.
I don't know if it's a code problem or opencv compile problem or model transformation problem.
I hope someone can help me,thanks.

Here is code 

<details>
<summary>code</summary>

```
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>

using namespace std;
using namespace cv;

int main(int argc, char** argv){
    constexpr const char *model_xml = "yolov5s.xml";
    constexpr const char *model_bin = "yolov5s.bin";
    
    cv::dnn::Net net;
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);//DNN_TARGET_MYRIAD
    net = cv::dnn::readNetFromModelOptimizer(model_xml,model_bin);
    cv::Mat img = cv::imread("./a.jpg");
/*
  CV_EXPORTS_W Mat blobFromImage(InputArray image, double scalefactor=1.0, const Size& size = Size(),
                                   const Scalar& mean = Scalar(), bool swapRB=true, bool crop=true);
*/
    cv::Mat inputBlob = cv::dnn::blobFromImage(img, 0.01712475f, cv::Size(640,640), cv::Scalar(123.675, 116.28, 103.53), true,false);
    net.setInput(inputBlob,"input");//set the network input, "data" is the name of the input layer     
    cv::Mat pred = net.forward("output");
    double freq = cv::getTickFrequency() / 1000;
    std::vector<double> layersTimes;
    double t = net.getPerfProfile(layersTimes) / freq;
    std::cout << "[INFO] network process took " << t << " ms" << std::endl;
    imshow("a", img);
    waitKey(0);
    return 0;
}
```
</details>

The whole error is
CPP/InferenceEngine::GeneralError   Unhandled exception at 0x00007FFD74FF4ED9 in test.o: Microsoft C++ exception: InferenceEngine::GeneralError at memory location 0x000000081D34F150.

**Comment by alalek** [comment]
Which guidelines are used to convert model into IR?

See here:
- https://github.com/openvinotoolkit/openvino/issues/3339
- https://github.com/openvinotoolkit/openvino/issues/2992
- https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/openvino-object-detection-yoloV5-architecture/td-p/1265092
- https://stackoverflow.com/questions/66593210/convert-yolov5s-pt-to-openvino-ir-format-success-predict-stuff-failed

**Comment by Jaren-Li** [comment]
> Which guidelines are used to convert model into IR?
> 
> See here:
> 
> * [yolov5_v3 support openvinotoolkit/openvino#3339](https://github.com/openvinotoolkit/openvino/issues/3339)
> * [Yolov5 Model conversion error [Bug] openvinotoolkit/openvino#2992](https://github.com/openvinotoolkit/openvino/issues/2992)
> * https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/openvino-object-detection-yoloV5-architecture/td-p/1265092
> * https://stackoverflow.com/questions/66593210/convert-yolov5s-pt-to-openvino-ir-format-success-predict-stuff-failed

I first use this file (https://github.com/ultralytics/yolov5/blob/master/export.py)  to convert yolov5s.pt(yolov5-P5) to onnx. The model is then converted to IR format with mo_onnx.py
