### ISSUE TITLE
Cap.isOpened()  always true whatever the system is been insert USB Camere or not

### ISSUE THREAD

**Issue by VegetableWithChicken** [opencv/opencv#20604]
System information (version)
cpp :  
OpenCV => 430
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2017

python:  
3.6.8

`import cv2
cap=cv2.VideoCapture(0)
cap.open(0)
img=None

while cap.isOpened():# whatever insert camera or not in windows system
    ret,img=cap.read()
    cv2.imshow('hello',img)
    cv2.waitKey(0)
print("no camera")
cap.release()`

the camera is AzureKinectDK

**Comment by alalek** [comment]
You need to fill issue's template (do NOT drop that).
Formatting of your code snippet is broken.

Collect dump of diagnostic information through `OPENCV_VIDEOIO_DEBUG=1` environment variable.

**Comment by VegetableWithChicken** [comment]
I've solved the problem with the OBS software and opencv conflict, and after I uninstalled the obs,and it worked fine
