### ISSUE TITLE
built with cuda and nvcuvid, but met opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp:86:16: error: ‘cuvidDecodePicture’ was not declared in this scope

### ISSUE THREAD

**Issue by biel-wangdf3** [opencv/opencv#20638]
environment:
ubuntu version:Ubuntu 18.04.5 LTS bionic x86_64
opencv version : 4.5.3-dev
opencv_contrib: 4.5.3
ffmpeg : N-103406-gdc34bf45c5
ffnvcodec : use nvidia sample
nvidia driver :470.57.02
cuda version :11.4
RTX3090
https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/
test ffmpeg and ffnvcodec : successfully

but I met a error when compiling opencv using cmake 3.10.2

compile opencv setting :-D WITH_CUDA=ON, -D WITH_NVCUVID=ON, -D WITH_FFMPEG=ON,

highgui: using builtin backend: GTK2
Building with NVIDIA Optical Flow API 2.0

General configuration for OpenCV 4.5.3-dev =====================================
Version control: 4.5.3-150-g053470d5a8

Extra modules:
Location (extra): /home/wdf/workspace/opencv/opencv_contrib/modules
Version control (extra): 4.5.3-6-g907efb96

Platform:
Timestamp: 2021-08-27T10:29:52Z
Host: Linux 5.4.0-81-generic x86_64
CMake: 3.10.2

Compiling:
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp:58:2: warning:   when initialized here [-Wreorder]
  VideoDecoder(const FormatInfo& videoFormat, CUcontext ctx, CUvideoctxlock lock) : ctx_(ctx), lock_(lock), decoder_(0)
  ^~~~~~~~~~~~
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp: In member function ‘bool cv::cudacodec::detail::VideoDecoder::decodePicture(CUVIDPICPARAMS*)’:
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp:86:16: error: ‘cuvidDecodePicture’ was not declared in this scope
         return cuvidDecodePicture(decoder_, picParams) == CUDA_SUCCESS;
                ^~~~~~~~~~~~~~~~~~
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp:86:16: note: suggested alternative: ‘tcuvidDecodePicture’
         return cuvidDecodePicture(decoder_, picParams) == CUDA_SUCCESS;
                ^~~~~~~~~~~~~~~~~~
                tcuvidDecodePicture
In file included from /home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/precomp.hpp:57:0,
                 from /home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/cuvid_video_source.cpp:44:
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp: In member function ‘cv::cuda::GpuMat cv::cudacodec::detail::VideoDecoder::mapFrame(int, CUVIDPROCPARAMS&)’:
/home/wdf/workspace/opencv/opencv_contrib/modules/cudacodec/src/video_decoder.hpp:94:21: error: ‘cuvidMapVideoFrame’ was not declared in this scope
         cuSafeCall( cuvidMapVideoFrame(decoder_, picIdx, &ptr, &pitch, &videoProcParams) );
                     ^
/home/wdf/workspace/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:163:61: note: in definition of macro ‘cuSafeCall’
 #define cuSafeCall(expr)  cv::cuda::checkCudaDriverApiError(expr, __FILE__, __LINE__, CV_Func)

I think this error reference of /usr/local/include/ffnvcodec/dynlink_loader.h, because cuvidDecodePicture define in dynlink_loader.h, 
![image](https://user-images.githubusercontent.com/75000239/131486223-8180f2ce-298d-4b0c-816c-5b424fa62711.png)

![image](https://user-images.githubusercontent.com/75000239/131485835-baf325e0-93bc-40aa-863f-babf546be0b5.png)

why  error: ‘cuvidDecodePicture’ was not declared in this scope occur ?
can you help me?
thank you !!!

**Comment by mshabunin** [comment]
What does this line in your OpenCV CMake output says: https://github.com/opencv/opencv/blob/c11195d5e3ad3593d33df600618884b90e41d7c5/CMakeLists.txt#L1598

**Comment by biel-wangdf3** [comment]
> What does this line in your OpenCV CMake output says?
> 
> https://github.com/opencv/opencv/blob/c11195d5e3ad3593d33df600618884b90e41d7c5/CMakeLists.txt#L1598
my opencv/CMakeLists.txt : 1598
status("  NVIDIA CUDA:" HAVE_CUDA THEN "YES (ver ${CUDA_VERSION_STRING}, ${cuda_features})" ELSE NO)

firstly, cmake-gui cannt found find NVCUVID, 
NVIDIA CUDA: YES (ver 11.4, CUFFT CUBLAS FAST_MATH)
[https://github.com/opencv/opencv_contrib/issues/3034](url)
i think it maybe not find nvcuvid because of environment path, so i modify 
opencv_contrib/modules/cudacodec/CMakeLists.txt, add a line ffnvcodec include file path
 `include_directories(/usr/local/include/ffnvcodec)`  
and modify opencv/cmake/OpenCVDetectCUDA.cmake in line 61:
change `PATHS "${CUDA_TOOLKIT_TARGET_DIR}" "${CUDA_TOOLKIT_ROOT_DIR}"` to
`PATHS "${CUDA_TOOLKIT_TARGET_DIR}" "${CUDA_TOOLKIT_ROOT_DIR}" "/usr/include" "/usr/local/include/ffnvcodec"`
so after configure it can find NVCUVID ,
`NVIDIA CUDA: YES (ver 11.4, CUFFT CUBLAS NVCUVID FAST_MATH)`
Is it correct ??? @mshabunin 

secondly,  i met above error "‘cuvidDecodePicture’ was not declared in this scope " after command : `make -j 50`

**Comment by biel-wangdf3** [comment]
已经解决了这个问题，现在总结下产生这个错误的原因，对刚接触nvidia-cuda硬件解码的会有些帮助：
1.先确定cuda的版本，9.0的版本用了dynlink_cuviddec.h  dynlink_loader.h  dynlink_nvcuvid.h等这些带dynlink_*的头文件，
如果按照[video-codec-sdk](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/index.html)
如果你用的cuda版本是11+，那么按照上面的步骤已经入坑了！
2.不要试图去修改opencv/cmake/OpenCVDetectCUDA.cmake，如果理不清ffmpeg，video-codec-sdk，opencv，那么就入坑了；
正确的安装方法：
1.[安装nvidia-driver，nvidia-cuda和nvidia-cudnn，](https://developer.nvidia.com/zh-cn/cuda-toolkit)
2.安装video-codec-sdk，[下载安装包](https://developer.nvidia.com/nvidia-video-codec-sdk/download)解压后分别把头文件和动态库copy到你的cuda目录，比如：/usr/local/cuda/include  ,  /usr/local/cuda/lib64
如果include目录下存在dynlink_cuviddec.h  dynlink_loader.h  dynlink_nvcuvid.h等头文件，则一定要删除；
3.安装opencv和opencv_contrib，用cmake-gui配置WITH_CUFFT WITH_CUBLAS WITH_NVCUVID等选型即可；

到这里后generate的输出就正常了，
`  GUI:                           GTK2
    GTK+:                        YES (ver 2.24.32)
      GThread :                  YES (ver 2.56.4)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2_2)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      YES (2.2.5)
    FFMPEG:                      YES
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (3.7.0)
    GStreamer:                   YES (1.14.5)
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   /home/***/workspace/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                /home/***/workspace/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
    VA:                          YES
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 11.4, CUFFT CUBLAS NVCUVID)
    NVIDIA GPU arch:             35 37 50 52 60 61 70 75 80 86
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 8.2.2)`

检查：NVIDIA CUDA:                   YES (ver 11.4, CUFFT CUBLAS NVCUVID) 必须包含NVCUVID
如果仍然存在问题，欢迎留言交流。
推荐几个有帮助的链接：
https://github.com/opencv/opencv/issues/17649
https://forum.opencv.org/t/error-213-the-function-feature-is-not-implemented/3523/11
https://github.com/opencv/opencv/issues/11220

**Comment by xiaowk5516** [comment]
> cuvidDecodePicture

你好，我在编译opencv的时候也遇到了这个问题：‘cuvidDecodePicture’ was not declared in this scope。
我的cuda是11.1
opencv 4.4.0 
video_codec_sdk 9.1.23
我看您说已经入坑了，意思是cuda11不能用video_codec_sdk 9.1.23么？
另外我看到`如果include目录下存在dynlink_cuviddec.h dynlink_loader.h dynlink_nvcuvid.h等头文件，则一定要删除；`，但是cmakelists.txt是检查了dynlink_nvcuvid.h是否存在的。

**Comment by biel-wangdf3** [comment]
> > cuvidDecodePicture
> 
> 你好，我在编译opencv的时候也遇到了这个问题：‘cuvidDecodePicture’ was not declared in this scope。 我的cuda是11.1 opencv 4.4.0 video_codec_sdk 9.1.23 我看您说已经入坑了，意思是cuda11不能用video_codec_sdk 9.1.23么？ 另外我看到`如果include目录下存在dynlink_cuviddec.h dynlink_loader.h dynlink_nvcuvid.h等头文件，则一定要删除；`，但是cmakelists.txt是检查了dynlink_nvcuvid.h是否存在的。

看video_codec_sdk的版本说明是说版本9与其他的版本有差异，可以换个版本试试

**Comment by wqh17101** [comment]
获得了这个报错
```
gmake[2]: *** No rule to make target `true', needed by `lib/libopencv_cudacodec.so.4.5.2'.  Stop.
```

**Comment by wqh17101** [comment]
看起来由 `-DCUDA_CUDA_LIBRARY`引起
