### ISSUE TITLE
Session Crashed automatically on Colab when try to capture real time photo or video

### ISSUE THREAD

**Issue by suryadeepti** [opencv/opencv#20632]
<img width="1280" alt="Screenshot 2021-08-30 at 3 07 15 PM" src="https://user-images.githubusercontent.com/36269088/131322290-2331637b-7907-43c8-9f1d-f18c41403c04.png">
<img width="1280" alt="Screenshot 2021-08-30 at 3 07 30 PM" src="https://user-images.githubusercontent.com/36269088/131322303-e7837d24-e79d-48c8-b09b-cb2a94898d21.png">

In Colab, OpenCV works only if it is I want to work on already captured images. If I am writing a program in which I want to capture real time image this can’t be done as it raise an error in case of image and crash session in case of video. I tried it with solutions but same error.

**Comment by alalek** [comment]
Check Colab documentation about supporting of cameras (probably not supported).

There is nothing to fix in OpenCV.
Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/


P.S. Don't post text information through screenshots, it is ridiculous.
