### ISSUE TITLE
cv::dnn::blobFromImage why only have substract means but not divide stds?

### ISSUE THREAD

**Issue by luohao123** [opencv/opencv#20672]
cv::dnn::blobFromImage why only have substract means but not divide stds?

**Comment by alalek** [comment]
Check `scalefactor` parameter.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by luohao123** [comment]
@alalek thank for your reply, but you misunderstood my question, scale_factor is just **a double**, I want RGB stds just like means. You tell me how to subtract means and divide stds using a **double**????

**Comment by alalek** [comment]
You need to write you own custom implementation of images pre-processing.

**Comment by luohao123** [comment]
@alalek  thank u! Did u have any out-of-box choice to do so?

**Comment by luohao123** [comment]
@alalek  thank u Sir. but here is my concern, we want preprocess as fast as possible isn't it?
so what i mean is if we can do when minus means at the same time we also divid the stds, so that users don't need do the for loop twice on image. 
However, from your consideration, the function can be huge, it might have a better solution?
