### ISSUE TITLE
`libpng error: IDAT: CRC error ` is random

### ISSUE THREAD

**Issue by geoexploring** [opencv/opencv#20683]
##### System information (version)
- OpenCV => opencv-python 4.5.3.56         
- Operating System / Platform => Windows 64 Bit
- Compiler => VScode or Pycharm

I use cv2.imread() as the input image reading tool for deep learning model training, but 'libpng error: IDAT: CRC error' often occurs during reading and is random, which is annoying because the model often stops training.

The image reading function is：
```python
def read_img(img_path):
    return cv2.imread(img_path, cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR | cv2.IMREAD_COLOR)
```

Not sure if this is a hardware problem.
Thanks

**Comment by sturkmen72** [comment]
probably related https://github.com/glennrp/libpng/issues/183

**Comment by alalek** [comment]
Please provide complete minimal reproducer including image data.

**Comment by geoexploring** [comment]
@alalek ，I converted all `PNG` into `JPG`, and the problem was solved.

**Comment by yhmymm** [comment]
My task can only use png pictures. Is it a hardware problem?

**Comment by geoexploring** [comment]
@yhmymm , It's possible. I later found out my RAM was faulty

**Comment by yhmymm** [comment]
> @yhmymm , It's possible. I later found out my RAM was faulty

Thank you. Me too! I changed the server and this problem no longer occurs.

**Comment by sulliv81** [comment]
> @yhmymm , It's possible. I later found out my RAM was faulty

Running into similar issue, debugged everything I can think of. How did you find out the RAM was faulty?
