### ISSUE TITLE
CV_CPU_FP16 is false of FreeBSD aarch64

### ISSUE THREAD

**Issue by MikaelUrankar** [opencv/opencv#20685]
The current code seems to be linux only:
https://github.com/opencv/opencv/blob/master/modules/core/src/system.cpp#L542

and the following code doesn't check if __ARM_NEON is defined:
https://github.com/opencv/opencv/blob/master/modules/core/src/system.cpp#L593

**Comment by alalek** [comment]
Feel free to prepare PR with fixes (3.4 target branch is preferable). Please validate proposed changes on your side for mentioned configuration.
