### ISSUE TITLE
error: (-215:Assertion failed) mask.empty() => cv2.cuda.bitwise_and()

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#20698]
##### System information (version)
- OpenCV => 4.3.5
- Operating System / Platform => Windows 64 Bit
- Compiler => python 3.8 (anaconda env)

##### Detailed description

A strange error happen only when using a bitwise function with CUDA.
After verification all arguments are good. 
This issue doens't happen when doing the same thing on CPU.

error: OpenCV(4.5.3) C:\Users\Charles\OpenCV\opencv_contrib-4.5.3\modules\cudaarithm\src\element_operations.cpp:144: 
error: (-215:Assertion failed) mask.empty() || (cn == 1 && mask.size() == size && mask.type() == CV_8UC1) in function '`anonymous-namespace'::arithm_op'

##### Steps to reproduce

```
import cv2
import numpy as np

back=cv2.imread('background.png')

particle=cv2.VideoCapture("particle.mp4")
cap=particle.get(cv2.CAP_PROP_FRAME_COUNT)
out=cv2.VideoWriter('final.mp4', cv2.VideoWriter_fourcc('H','2','6','4'), 60, (1920, 1080))

up=[150, 150, 150]
low=[0, 0,0]

img_gpu=cv2.cuda_GpuMat()

c=0
while c!=60:
    
    c+=1
    if c%cap==0:
        particle.set(cv2.CAP_PROP_POS_FRAMES, 0)
        print(c/cap)
        
    ret, img=particle.read()
    
    img_gpu.upload(img)
    mask=cv2.cuda.inRange(img_gpu, low, up)
    res=cv2.cuda.bitwise_and(img_gpu, img_gpu, mask=mask)
    f=cv2.cuda.subtract(img_gpu, res)

    f=f.download()
    rgb=np.where(f==0, back, f)
    out.write(rgb)


particle.release()
out.release()
```

**Comment by alalek** [comment]
> `res=cv2.cuda.bitwise_and(img_gpu, img_gpu, mask=mask)`

dump mask type for further investigation.

Also you can try to use `cv.utils.dumpInputArray(mask)` for that.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by Picus303** [comment]
Hi,
Sorry, I'm new in the Opencv community. Do you want me to move my question?
Here is the file dumped with pickle (the numpy array, I couldn't dump the GpuMat object).
Thank you for helping me with that.
[mask_gpu.txt](https://github.com/opencv/opencv/files/7161206/mask_gpu.txt)

**Comment by Muhammad-Yunus** [comment]
Hi @Picus303 ,

I have similar issue also whe using CUDA bitwise_and operation in OpenCV 4.5.3.

As workaround (if CUDA is mandatory) just user bitwise_not twice (in python),

`    
cv2.cuda.bitwise_not(img_GpuMat, res_GpuMat, mask=mask_GpuMat) # apply bitwise NOT to original image -> result image
cv2.cuda.bitwise_not(res_GpuMat, res_GpuMat, mask=mask_GpuMat) # apply bitwise NOT to result image 
`
