### ISSUE TITLE
Compiling OpenCV with VTK 9.0.20210919 on Windows

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#20717]
recently i compiled OpenCV 4.5.3 with VTK 9.0.20210919 on Windows.

i was sure that i already compiled and installed VTK flawlessly but at first try running cmake i get `"VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file"` message.

after an investigating i changed [this line](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectVTK.cmake#L4) as     `if(VTK_VERSION VERSION_GREATER "9") # VTK 9.0` and solved the problem.

maybe it is not a general or right solution but i hope this info will be useful.

**Comment by LaurentBerger** [comment]
Agree you can make a PR

**Comment by alalek** [comment]
relates #20384

**Comment by sturkmen72** [comment]
what about `if(VTK_VERSION VERSION_GREATER "8.2.0") # VTK 9.0`

**Comment by rogday** [comment]
> what about `if(VTK_VERSION VERSION_GREATER "8.2.0") # VTK 9.0`

This is probably good enough with the upper bound on version 10.
