### ISSUE TITLE
Got the same problem with custom build of  4.5.3

### ISSUE THREAD

**Issue by quaesitor-scientiam** [opencv/opencv#20714]
Got the same problem with custom build of  4.5.3

PS D:\testopencv>  & 'c:\Python\python37\python.exe' 'c:\Users\myuserid\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy\launcher' '63212' '--' 'd:\testopencv\testbuild.py' 
OpenCV loader: os.name="nt"  platform.system()="Windows"
OpenCV loader: loading config: c:\Python\python37\lib\site-packages\cv2\config.py
OpenCV loader: loading config: c:\Python\python37\lib\site-packages\cv2\config-3.7.py
OpenCV loader: PYTHON_EXTENSIONS_PATHS=[]
OpenCV loader: BINARIES_PATHS=[]
OpenCV loader: PATH=;D:\Tools\Powershell\7.1.3;D:\Tools\cmake\bin;D:\Tools\NVidiaGPUComputing\v11.2\CUDA\bin;D:\Tools\NVidiaGPUComputing\v11.2\CUDA\libnvvp;C:\Program Files\Amazon Corretto\jdk1.8.0_262\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Corretto\jre8\bin;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Yarn\bin\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.3.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Tools\bin;C:\Python\python37;C:\Python\python37\Scripts;C:\Users\myuserid\AppData\Local\Microsoft\WindowsApps;D:\CMAKE-3.9.4\bin;;C:\Python\python37\lib\site-packages\pywin32_system32;c:\Python\python37\lib\site-packages\pywin32_system32;c:\Python\python37\lib\site-packages\numpy\.libs
OpenCV loader: replacing cv2 module
['d:\\testopencv', 'c:\\Python\\python37\\python37.zip', 'c:\\Python\\python37\\DLLs', 'c:\\Python\\python37\\lib', 'c:\\Python\\python37', 'C:\\Users\\myuserid\\AppData\\Roaming\\Python\\Python37\\site-packages', 'c:\\Python\\python37\\lib\\site-packages', 'c:\\Python\\python37\\lib\\site-packages\\coco_dataset_generator-1.0-py3.7.egg', 'c:\\Python\\python37\\lib\\site-packages\\win32', 'c:\\Python\\python37\\lib\\site-packages\\win32\\lib', 'c:\\Python\\python37\\lib\\site-packages\\Pythonwin']   
Traceback (most recent call last):
  File "c:\Python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\myuserid\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\myuserid\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\myuserid\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "c:\Python\python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\Python\python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\Python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\testopencv\testbuild.py", line 1, in <module>
    import cv2
  File "c:\Python\python37\lib\site-packages\cv2\__init__.py", line 129, in <module>
    bootstrap()
  File "c:\Python\python37\lib\site-packages\cv2\__init__.py", line 112, in bootstrap
    import cv2
  File "c:\Python\python37\lib\site-packages\cv2\__init__.py", line 129, in <module>
    bootstrap()
  File "c:\Python\python37\lib\site-packages\cv2\__init__.py", line 37, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')    
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
PS D:\testopencv>  d:; cd 'd:\testopencv'; & 'c:\Python\python37\python.exe' 'c:\Users\myuserid\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy\launcher' '59338' '--' 'c:\Python\python37\Lib\site-packages\cv2\__init__.py'

This is caused because it deletes cv2 in the step "OpenCV loader: replacing cv2 module"
Then in process of reloading a 2nd time it finds that the sys attribute "OpenCV_LOADER" is  already defined from the first bootstrap() call.

_Originally posted by @quaesitor-scientiam in https://github.com/opencv/opencv/issues/19848#issuecomment-921776732_

**Comment by alalek** [comment]
> OpenCV loader: PYTHON_EXTENSIONS_PATHS=[]

It should NOT be empty.
Python loader configuration is invalid.

It is a configuration problem which we can't fix in OpenCV.

> cv2_init.py

How is it created? We don't have such file.
You can see the correct file name in comments from mentioned issue.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by quaesitor-scientiam** [comment]
I performed a build with the install target with VS2019 solution that cmake generated in the folder build/modules/python3  in which that compiled successfully and pushed it to my Python environment.

**Comment by alalek** [comment]
Check files in this location: `<build>\CMakeFiles\install\python_loader\cv2`

I have this content (this configuration is not movable between machines):

```
config-3.8.py:

PYTHON_EXTENSIONS_PATHS = [
    os.path.join('C:/utils/soft/python38-x64/Lib/site-packages/cv2', 'python-3.8')
] + PYTHON_EXTENSIONS_PATHS
```

and

```
config.py:

import os

BINARIES_PATHS = [
    os.path.join('C:/projects/opencv/build_vc16/install', 'x64/vc16/bin')
] + BINARIES_PATHS
```


---

> cv2_init.py

Please try to run code without Python debugger (this probably comes from there):

> debugpy\server\cli.py

(BTW, there is some incompatibility with PyCharm debugger: #18198)

**Comment by quaesitor-scientiam** [comment]
I solved the issue, Did a rebuild with --config=Release and it auto built the python bindings and pushed to site packages.
