### ISSUE TITLE
QR_code not detected

### ISSUE THREAD

**Issue by Armin234** [opencv/opencv#20724]
Hi,

I have problems with my QR-Code which Opencv didn't detect. My iPhone has none problem with this QR-Code.
Any idea what could be the problem ?

- OpenCV => 4.1.1
- NVidia Jetson AGX Ubuntu 18.04
- C++

![Unbenannt](https://user-images.githubusercontent.com/37782776/134028243-3458e4d6-c79b-4658-831a-34778f587ad5.PNG)

**Comment by puranjay123** [comment]
@Armin234 Try this code it is working fine  .Just Install pyzbar using pip install pybzbar
import cv2 
import numpy as np
import pyzbar.pyzbar as pyzbar
image = cv2.imread("a1.png")
decodedObjects = pyzbar.decode(image)
for obj in decodedObjects:
    print("Type:", obj.type)
    print("Data: ", obj.data, "\n")

**Comment by liuyunfeng2016** [comment]
@asmorkalov  @Armin234  @puranjay123  @peters  @jviney 
Hello,I have the same question. In python,
我使用了官方样例的二维码图片例子，但是依旧检测不出来，我用的是
opencv-contrib-python ==4.5.5.62，opencv-python == 4.5.5.62
https://raw.githubusercontent.com/opencv/opencv_extra/4.x/testdata/cv/qrcode/multiple/3_qrcodes.png
qrcode_detector = cv2.QRCodeDetector() qr_points = qrcode_detector.detect(img)
我尝试过下面一系列的检测情况，但是依旧检测不出来
[decodeMulti](https://docs.opencv.org/4.x/de/dc3/classcv_1_1QRCodeDetector.html#ab468c433ba95aba10a8184611446c7a0)
