### ISSUE TITLE
Error when using cv.dnn.readNetFromDarknet function with OpenCV (4.5.3.56) (YOLOR) 

### ISSUE THREAD

**Issue by GenericNolon** [opencv/opencv#20734]
I encountered this issue when I use dnn library to read yolorp6 cfg and weight file. The weight file was converted using the Yolor function in the file model.py (from pt to weight).
net = cv.dnn.readNet('yolorp6.weights','yolorp6.cfg' )
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\dnn\src\darknet\darknet_io.cpp:250: error: (-212:Parsing error) Unsupported activation: silu in function
'cv::dnn::darknet::setLayersParams::setActivation'
Yolor: https://github.com/WongKinYiu/yolor
Cfg file: (https://github.com/WongKinYiu/yolor/blob/main/cfg/yolor_p6.cfg)

**Comment by GenericNolon** [comment]
how can I add a silu function?

**Comment by HungDuong1998** [comment]
Hi, is there any update on this? I'm trying to run the yolov4-tiny_contrastive model to see tracking results as well, in my case the unsupported layer was local_avgpool
