### ISSUE TITLE
Error when using cv.dnn.readNetFromDarknet function with OpenCV (4.5.3.56) (YOLOR)

### ISSUE THREAD

**Issue by GenericNolon** [opencv/opencv#20732]
I encountered this issue when I use dnn library to read yolorp6 cfg and weight file. The weight file was converted using the Yolor function in the file model.py (from pt to weight). 
`net = cv.dnn.readNet('yolorp6.weights','yolorp6.cfg' )
`
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\dnn\src\darknet\darknet_io.cpp:250: error: (-212:Parsing error) Unsupported activation: silu in function 'cv::dnn::darknet::setLayersParams::setActivation'
Yolor: 
[https://github.com/WongKinYiu/yolor](url)
Cfg file:
 [https://github.com/WongKinYiu/yolor/blob/main/cfg/yolor_p6.cfg](url)

**Comment by alalek** [comment]
Link on the model and related articles are necessary.

**Comment by GenericNolon** [comment]
> Link on the model and related articles are necessary.

**Comment by GenericNolon** [comment]
how can I add a silu function?

**Comment by GenericNolon** [comment]
> Link on the model and related articles are necessary.

added

**Comment by baudneo** [comment]
Also looking for SiLU activation as YOLOv7 uses it for their darknet implementation. Using CUDA with cuDNN

**Comment by baudneo** [comment]
Opencv has added silu activation in a recent PR. It requires recompilation but, the change is easy to implement without needing to clone the repo.

**Comment by asmorkalov** [comment]
Is the issue still relevant for OpenCV 4.9.0? Yolov7 is supported. Yolo tutorial and sample: https://github.com/opencv/opencv/pull/24898

**Comment by baudneo** [comment]
It works from my testing of the recompilation patch.
