### ISSUE TITLE
How do I add a new activation function to Opencv?

### ISSUE THREAD

**Issue by GenericNolon** [opencv/opencv#20737]
I need to use the Sigmoid Linear Unit (SiLU) function, but opencv does not contain it. How can I add it?

**Comment by JulieBar** [comment]
For which backend and for which framework do you need support for this layer? For example, ONNX doesn't support SiLU yet.

**Comment by alalek** [comment]
Feature is tracked here: #20732

PR with example of adding activation is here: #15808
