### ISSUE TITLE
A bug in HoughLinesSDiv

### ISSUE THREAD

**Issue by Cavendish-Koo** [opencv/opencv#20751]
![image](https://user-images.githubusercontent.com/42258146/134791727-b5019e6a-e10e-4022-8477-0df523fd6f66.png)
HoughLinesSDiv use this pivot to get line whose accumalor value is greater than threshold, and it has been kept at the end in the vector `lst`.
![image](https://user-images.githubusercontent.com/42258146/134792042-067e0c93-c672-478a-afd9-29321f6ff39f.png)
So when create outputarray, in this scenario, lines, whose height is equal to the size of the lst, but skip over the initialization of the last element of `lines` , leaving the value undefined.
![image](https://user-images.githubusercontent.com/42258146/134792306-25d02c8b-31f9-4b44-b698-c3c9f162561c.png)
Actually, the pivot is always at the end of the vector `lst`. It would be reasonable to solve this problem by creating `lines` with the height equal to `lst.size()-1`.

**Comment by alalek** [comment]
Thank you for the report!

relates #11108

**Comment by Cavendish-Koo** [comment]
> Thank you for the report!
> 
> relates #11108

Thank you for the quick reply. Can I fix this bug and PR?

**Comment by alalek** [comment]
Sure! Feel free to prepare PR to "3.4" branch.

BTW, look like we have [zero code coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20210927-033204_1229/coverage_html/opencv/modules/imgproc/src/hough.cpp.gcov.html) for `HoughLinesSDiv` code path.

**Comment by Cavendish-Koo** [comment]
That means I also need to provide some test code, right?

**Comment by alalek** [comment]
Not necessary. The fix is be enough. Just validate patch on your case because there is no test coverage from OpenCV tests.
