### ISSUE TITLE
opencv_dnn is failed

### ISSUE THREAD

**Issue by sandhavel** [opencv/opencv#20769]
![opencv_error_log](https://user-images.githubusercontent.com/91118175/135230231-54c95341-8d4d-4dcf-863c-69c4b2178505.png)

##### System information (version)
- Operating System / Platform => Ubuntu 18.04

##### Detailed description
When i build, the openCV by this below link,
" https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/ "
I got that error, when i use the command "make -j8 ".

Please help me to fix this issue...

**Comment by alalek** [comment]
opencv_dnn is built successfully as we can see from the logs.
Use -j1 to see the actual error.
Avoid posting of text information through screenshots - it is ridiculous.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
