### ISSUE TITLE
Ask a question about "parallel_for_ "

### ISSUE THREAD

**Issue by Dandelion111** [opencv/opencv#20767]
Parallel_for_ in OpencV, I used it to apply 4 threads and initialize 4 identical recognition models. I need one model for each thread to recognize 8 images, that is, 8 subtasks. I only have the serial number of each subtask. How can you have one model per thread in parallel?

**Comment by alalek** [comment]
Algorithm's instances should not be used concurrently from different threads. Exception is some containers (like cv::Mat "by value") - their state can't be broken, however data race is still possible.

https://docs.opencv.org/3.4/d1/dfb/intro.html

---

> How can you have one model per thread in parallel?

So, this is not supported for now. Exception is asynchronous API (forwardAsync) through InferenceEngine (OpenVINO) backend.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
