### ISSUE TITLE
error: (-217:Gpu API call) invalid device function in function 'make_policy'

### ISSUE THREAD

**Issue by zijian98** [opencv/opencv#20778]
##### System information (version)

- OpenCV => 4.5.3-dev
- Operating System / Platform => Ubuntu 18.04 / Jetson AGX Xavier
- Compiler => python3

##### Detailed description

I have compiled opencv with cuda and tried to run an object detection program but it returned an error. Cuda 10.2 is installed. May I know how do I fix this?

Thanks

##### Steps to reproduce
This is the code that I am trying to run with my camera:
```
import cv2
import numpy as np
import matplotlib.pyplot as plt

config_file = '/home/user/Desktop/Object_Detection/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
frozen_model = '/home/user/Desktop/Object_Detection/frozen_inference_graph.pb'

model = cv2.dnn_DetectionModel(frozen_model, config_file)

model.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
model.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

classlabels = []
file_name = '/home/user/Desktop/Object_Detection/Labels.txt'
with open(file_name, 'rt') as fpt:
    classLabels = fpt.read().rstrip('\n').split('\n')
    

model.setInputSize(320,320)
model.setInputScale(1.0/127.5)
model.setInputMean((127.5,127.5,127.5))
model.setInputSwapRB(True)


#ClassIndex, confidence, bbox = model.detect(img.confThreshold = 0.5)

# set font
font_scale = 3
font = cv2.FONT_HERSHEY_PLAIN

# initiate video
cv2.startWindowThread()
cap = cv2.VideoCapture(2)

# filter class objects
filt = np.zeros(80)
filt[0] = 1;

while True:
    ret, frame = cap.read()
    
    ClassIndex, confidence, bbox = model.detect(frame, confThreshold = 0.55)
  
    #print(ClassIndex)
    if (len(ClassIndex)!=0):
        for ClassInd, conf, boxes in zip(ClassIndex.flatten(), confidence.flatten(), bbox):
            if (ClassInd==1):
                cv2.rectangle(frame, boxes, (255,0,0), 2)
                cv2.putText(frame, classLabels[ClassInd-1], (boxes[0]+10, boxes[1]+40), font, fontScale = font_scale, color = (0,255,0), thickness = 3)
                
    
    cv2.imshow('Detected objects', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
```
 The error:
```
Traceback (most recent call last):
  File "run_video.py", line 42, in <module>
    ClassIndex, confidence, bbox = model.detect(frame, confThreshold = 0.55)
cv2.error: OpenCV(4.5.3-dev) /home/user/opencv/modules/dnn/src/cuda/execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'make_policy'

```
and build information for cuda: 
```
NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS FAST_MATH)
    NVIDIA GPU arch:             70
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 8.0.0)
```

**Comment by alalek** [comment]
> 70

Ensure that you have the right CUDA CC
https://forums.developer.nvidia.com/t/what-compute-capability-of-jetson-xavier-nx-gpu-is/146241/4

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by zijian98** [comment]
> > 70
> 
> Ensure that you have the right CUDA CC https://forums.developer.nvidia.com/t/what-compute-capability-of-jetson-xavier-nx-gpu-is/146241/4
> 
> Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

Thank. I am now able to use CUDA but it keeps returning this error no matter how many times I tried to change the size:

`cv2.error: OpenCV(4.5.3-dev) /home/user/opencv/modules/dnn/src/cuda/eltwise_ops.cu:60: error: (-215:Assertion failed) x.size() == y.size() in function 'eltwise_op'`

What does this mean?

**Comment by YashasSamaga** [comment]
> cv2.error: OpenCV(4.5.3-dev) /home/user/opencv/modules/dnn/src/cuda/eltwise_ops.cu:60: error: (-215:Assertion failed) x.size() == y.size() in function 'eltwise_op'
> 
> What does this mean?

Broadcasting with elementwise operators is not supported yet. There are internal tests failing. I'll look into this and submit a patch soon.

**Comment by zijian98** [comment]
> > cv2.error: OpenCV(4.5.3-dev) /home/user/opencv/modules/dnn/src/cuda/eltwise_ops.cu:60: error: (-215:Assertion failed) x.size() == y.size() in function 'eltwise_op'
> > What does this mean?
> 
> Broadcasting with elementwise operators is not supported yet. There are internal tests failing. I'll look into this and submit a patch soon.

So are there any ways that I can run the net model using my gpu?

**Comment by YashasSamaga** [comment]
> So are there any ways that I can run the net model using my gpu?

As of now no. Normally, unsupported layers should fall back to CPU but some edge cases get missed out once in a while. I'll try to fix this in 2-3 days.

**Comment by YashasSamaga** [comment]
The CUDA backend verifies that the OpenCV binary has compatible kernels for your device. There should have been an error similar to this:

> \opencv\modules\dnn\src\dnn.cpp:2385: error: (-216:No CUDA support) OpenCV was not built to work with the selected device. Please check CUDA_ARCH_PTX or CUDA_ARCH_BIN in your build configuration. in function 'cv::dnn::dnn4_v20210608::Net::Impl::initCUDABackend'

There might be a bug in the verification logic as the error didn't show up.
