### ISSUE TITLE
OpenCV can't read specific neural network architecture

### ISSUE THREAD

**Issue by julienguegan** [opencv/opencv#20855]
##### System information (version)
- OpenCV => 4.5.3.56
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

OpenCV seems to not support a specific architecture of Neural Network. Specifically, I am trying to run the model from [3DDFA](https://github.com/cleardusk/3DDFA_V2) which implement a robust facial landmark detection. The idea to convert it to opencv is to convert it to ONNX format and then run it with `cv2.dnn.readNetFromONNX('model.onnx')`. But opencv return the following error : 
```
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-i3ohmhl0\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2129: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20210301::ONNXImporter::handleNode'
> Node [Slice]:(264) parse error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-i3ohmhl0\opencv\modules\dnn\src\layers\slice_layer.cpp:106: error: (-215:Assertion failed) start >= 0 in function 'cv::dnn::SliceLayerImpl::SliceLayerImpl'
>
```
Although, I confirm that the model can be loaded with other librairies as **onnx** or **pytorch**.

##### Steps to reproduce

1. Have a python environment with opencv
2. Download the model file [here](https://github.com/lyyiangang/3ddfav2_cpp/blob/main/models/face3d.onnx)
3. Run : 
```
import cv2
opencv_net = cv2.dnn.readNetFromONNX('face3d.onnx')
```

**Comment by alalek** [comment]
You didn't (version is a part of error message):

> `parse error: OpenCV(4.5.2)`

---

The latest release is 4.5.4.
You can build from sources or wait for PyPi packages which will be updated later on this week.

**Comment by Sukeysun** [comment]
Hi, have you solved this problem? My cv2 version is 4.5.3, but I still got this problem

**Comment by julienguegan** [comment]
actually no ... As alalek was not helping so much I just put this issue in my todolist, waiting that it will be resolved magically by itself 😄

**Comment by asmorkalov** [comment]
I checked current 4.x and ONNX loader does not produce any warnings. Model is loaded correctly. @julienguegan Please try and report the issue status.

**Comment by asmorkalov** [comment]
Most probably fixed in https://github.com/opencv/opencv/pull/22554
