### ISSUE TITLE
opencv_test_core not building from release 4.5.2, libtiff_4_0

### ISSUE THREAD

**Issue by makingglitches** [opencv/opencv#20876]
Still valid, requires the user to manually edit files cmake fudges.
please see the previous issue closed because the project is not conforming to the behaviors of the build environment like every other source package out there does.

except bazel. because google sucks.

and tensorflow.

because google sucks.

Please reference this bug and my most recent comments after it was closed.

https://github.com/opencv/opencv/issues/20286#issuecomment-943376124

I had to fix this by hand, but f*ck me if I remember what I did.

here is my current environment variable setup so its understood why this is relevant, because opencv is built and is working.

```
PREFIXPATH=/Data/Documents/CensusProject/gdallib/src/compiled

PKG_CONFIG_PATH=${PREFIXPATH}/lib/pkgconfig
LIBRARY_PATH=${PREFIXPATH}/lib
LD_LIBRARY_PATH=${PREFIXPATH}/lib/
C_INCLUDE_PATH=${PREFIXPATH}/include/
CPLUS_INCLUDE_PATH=${PREFIXPATH}/include/
PATH=${PREFIXPATH}/bin:$PATH
PREFIX=${PREFIXPATH}
# for googles retarded 'bazel' tool thinking tensorflow is bs.
JAVA_HOME=/lib/jvm/java-11-openjdk-11.0.11.0.9-4.fc34.x86_64
PATH=$PATH:$JAVA_HOME/bin

export PREFIXPATH
export JAVA_HOME
export PREFIX
export PKG_CONFIG_PATH
export LIBRARY_PATH
export LD_LIBRARY_PATH
export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
export PATH
```

**Comment by Matthew-Bradley** [comment]
> We can't resolve configuration problems of your build environment.
> 
> Try `cmake -DWITH_TIFF=OFF ...` to bypass that point.

What effect does this have on the end result?

**Comment by Matthew-Bradley** [comment]
the full list of files -ltiff had to be appended to the end of the first line of:
pluma apps/annotation/CMakeFiles/opencv_annotation.dir/link.txt
pluma apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/link.txt
pluma apps/visualisation/CMakeFiles/opencv_visualisation.dir/link.txt
pluma modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/link.txt
pluma modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/link.txt
pluma modules/core/CMakeFiles/opencv_perf_core.dir/link.txt
pluma modules/core/CMakeFiles/opencv_test_core.dir/link.txt
pluma modules/dnn/CMakeFiles/opencv_perf_dnn.dir/link.txt
pluma modules/dnn/CMakeFiles/opencv_test_dnn.dir/link.txt
pluma modules/features2d/CMakeFiles/opencv_perf_features2d.dir/link.txt
pluma modules/features2d/CMakeFiles/opencv_test_features2d.dir/link.txt
pluma modules/gapi/CMakeFiles/opencv_perf_gapi.dir/link.txt
pluma modules/gapi/CMakeFiles/opencv_test_gapi.dir/link.txt
pluma modules/highgui/CMakeFiles/opencv_test_highgui.dir/link.txt
pluma modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/link.txt
pluma modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/link.txt
pluma modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/link.txt
pluma modules/ml/CMakeFiles/opencv_test_ml.dir/link.txt
pluma modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/link.txt
pluma modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/link.txt
pluma modules/photo/CMakeFiles/opencv_perf_photo.dir/link.txt
pluma modules/photo/CMakeFiles/opencv_test_photo.dir/link.txt
pluma modules/stitching/CMakeFiles/opencv_perf_stitching.dir/link.txt
pluma modules/stitching/CMakeFiles/opencv_test_stitching.dir/link.txt
pluma modules/video/CMakeFiles/opencv_perf_video.dir/link.txt
pluma modules/video/CMakeFiles/opencv_test_video.dir/link.txt
pluma modules/videoio/CMakeFiles/opencv_perf_videoio.dir/link.txt
pluma modules/videoio/CMakeFiles/opencv_test_videoio.dir/link.txt

**Comment by Matthew-Bradley** [comment]
this is relative to the build directory, btw

**Comment by makingglitches** [comment]
I mentioned this as well
So
What he said 

> the full list of files -ltiff had to be appended to the end of the first line of:
> 
> pluma apps/annotation/CMakeFiles/opencv_annotation.dir/link.txt
> 
> pluma apps/interactive-calibration/CMakeFiles/opencv_interactive-calibration.dir/link.txt
> 
> pluma apps/visualisation/CMakeFiles/opencv_visualisation.dir/link.txt
> 
> pluma modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/link.txt
> 
> pluma modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/link.txt
> 
> pluma modules/core/CMakeFiles/opencv_perf_core.dir/link.txt
> 
> pluma modules/core/CMakeFiles/opencv_test_core.dir/link.txt
> 
> pluma modules/dnn/CMakeFiles/opencv_perf_dnn.dir/link.txt
> 
> pluma modules/dnn/CMakeFiles/opencv_test_dnn.dir/link.txt
> 
> pluma modules/features2d/CMakeFiles/opencv_perf_features2d.dir/link.txt
> 
> pluma modules/features2d/CMakeFiles/opencv_test_features2d.dir/link.txt
> 
> pluma modules/gapi/CMakeFiles/opencv_perf_gapi.dir/link.txt
> 
> pluma modules/gapi/CMakeFiles/opencv_test_gapi.dir/link.txt
> 
> pluma modules/highgui/CMakeFiles/opencv_test_highgui.dir/link.txt
> 
> pluma modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/link.txt
> 
> pluma modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/link.txt
> 
> pluma modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/link.txt
> 
> pluma modules/ml/CMakeFiles/opencv_test_ml.dir/link.txt
> 
> pluma modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/link.txt
> 
> pluma modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/link.txt
> 
> pluma modules/photo/CMakeFiles/opencv_perf_photo.dir/link.txt
> 
> pluma modules/photo/CMakeFiles/opencv_test_photo.dir/link.txt
> 
> pluma modules/stitching/CMakeFiles/opencv_perf_stitching.dir/link.txt
> 
> pluma modules/stitching/CMakeFiles/opencv_test_stitching.dir/link.txt
> 
> pluma modules/video/CMakeFiles/opencv_perf_video.dir/link.txt
> 
> pluma modules/video/CMakeFiles/opencv_test_video.dir/link.txt
> 
> pluma modules/videoio/CMakeFiles/opencv_perf_videoio.dir/link.txt
> 
> pluma modules/videoio/CMakeFiles/opencv_test_videoio.dir/link.txt
