### ISSUE TITLE
Error in HoughCircles when using UMat image input

### ISSUE THREAD

**Issue by zain-sohail** [opencv/opencv#20913]
I have been using the HoughCircles function through Python for circle detection but wanted to speed it up by making use of Transparent API. I understand that usage of UMat is necessary for that and `img` is of such type

`circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT, 1.2, 1500)`

When I run the code, I get this error:

`hough.cpp:2254: error: (-215:Assertion failed) _circles.isMat() || _circles.isVector() in function 'HoughCircles'
`

I could find this assertion in here. 
https://github.com/opencv/opencv/blob/6ffc48769ac60d53c4bd1913eac15117c9b1c9f7/modules/imgproc/src/hough.cpp#L1660

Even with giving circles (`np.zeros((1,1,3), np.float32)`) as an input parameter, it gives the same error. From my understanding this is something internal within the function and since I have little experience with openCV codebase, I wonder if this is a purposeful feature or a bug.

**Comment by berak** [comment]
@zainsohail04 however, there is no real UMat support in this function, apart from the [Sobel calls here](https://github.com/opencv/opencv/blob/6b0f7747e0b13f58f57dcc27be11e77c345d2bd5/modules/imgproc/src/hough.cpp#L1632-L1633)
