### ISSUE TITLE
The FaceDetectorYN & FaceRecognizerSF model can be faster by opencl or cuda?

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#20959]
##### System information (version)
- OpenCV => 4.5.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
The FaceDetectorYN & FaceRecognizerSF have added in the opencv 4.5.4, that's model  can be faster by OpenCL or CUDA as same as DNN model?

**Comment by ghimiredhikura** [comment]
Can you locate models for FaceRecognizerSF? Thanks.
