### ISSUE TITLE
How should I add a .cu file and compile it with nvcc in zlib directory?

### ISSUE THREAD

**Issue by lhb8125** [opencv/opencv#20994]
##### System information (version)
- OpenCV => 4.5.4
- Operating System / Platform => Ubuntu
- Compiler => gcc, g++

##### Detailed description

Hi team, I would like to accelerate the deflate() algorithm of zlib with CUDA, but when I try to insert a .cu file, I have no idea how to add it to the compile system of OpenCV.
Is there any guidance or workaround?

**Comment by alalek** [comment]
You need to use external own "zlib" build.
Check CMake documentation how to integrate it through `find_package(ZLIB)` (command-line parameters + extra config files is enough for that - no need to touch OpenCV source code)
