### ISSUE TITLE
Allow resizing to empty

### ISSUE THREAD

**Issue by mpolicki** [opencv/opencv#20993]
Currently, resizing to an empty destination matrix is not allowed. https://github.com/opencv/opencv/blob/68d15fc62edad980f1ffa15ee478438335f39cc3/modules/imgproc/src/resize.cpp#L4057

I don't see a good reason for this. It's also inconsistent, considering that an empty destination can be resized up, but a non-empty destination can't be resized down to empty, and also considering that an empty matrix can be created outright.

Resizing to an empty matrix is useful in edge cases, such as the one I currently have where I can only provide two of {consistency, functionality, correctness} because of this, and I could have all three if resizing to empty were possible.

**Comment by alalek** [comment]
This is considered as error prone behavior.

See also #8300

**Comment by mpolicki** [comment]
As long as function behavior with regard to empty matrixes is documented, there should be no surprises for the user, and thus no errors.

If, on the other hand, empty matrixes are banned, that will block a lot of legitimate use and encumber the user with having to create workarounds, which in some cases may not even be possible.

**Comment by vrabaud** [comment]
We can also argue that it should also be valid to resize an empty matrix to an empty matrix.

**Comment by alalek** [comment]
> empty matrixes are banned, that will block a lot of legitimate use

OpenCV should be an efficient library from performance perspective, like OpenCV-based applications.
We just should not try to process empty matrixes...


> there should be no surprises for the user, and thus no errors.

If you read #8300 careful, then you could find that such "no surprises" processing causes several hours/days of hard debugging.

**Comment by mpolicki** [comment]
> OpenCV should be an efficient library from performance perspective

Shouldn't it also be well-designed from a usability perspective? In that it should try to minimize the effort required to use it?

Also, in general, someone trying to maximize performance would pre-validate their arguments to make sure no unnecessary processing takes place. Currently the same pre-validation is necessary to avoid asserts throwing. I'm just suggesting to make the pre-validation optional for those use cases where maximum performance isn't the highest priority.

> If you read #8300 careful, then you could find that such "no surprises" processing causes several hours/days of hard debugging.

That's why I said documented. If the documentation is there and someone gets a bug because they didn't read it, that's on them.
