### ISSUE TITLE
Grammatical Error 

### ISSUE THREAD

**Issue by darknessraider** [opencv/opencv#21069]
https://docs.opencv.org/4.x/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path

First we set an environment variable to make easier our work

**Comment by alalek** [comment]
Feel free to prepare PR with fix.
Please use "3.4" base branch if the fix is applicable there too: https://github.com/opencv/opencv/wiki/Branches

**Comment by darknessraider** [comment]
Where are the website's files in GitHub?

**Comment by alalek** [comment]
> where

- open https://github.com/opencv/opencv
- press 't' and wait a bit
- type 'tutwininst'
- select doc/tutorials/introduction/windows_install/windows_install.markdown (2nd proposal)

**Comment by sathvik2612** [comment]
Is anyone working ont his @darknessraider

**Comment by lamm45** [comment]
> Is anyone working ont his @darknessraider

This was already fixed 6 months ago:
https://github.com/opencv/opencv/pull/21306
