### ISSUE TITLE
Compile error with Clang 13: std::result_of is removed in C++20

### ISSUE THREAD

**Issue by daravi** [opencv/opencv#21109]
Forgive me if this has already been fixed in latest commits. But trying to build 4.5.3 with Clang 13 I get a compile error:
```
type_traits.hpp:87:35: error: no type named 'result_of' in namespace 'std'
using result_of_t = typename std::result_of<T>::type;
```
And so on. This is because the deprecated `std::result_of` has finally been removed in Clang 13. I think the fix would be to use `std::invoke_result` instead. (I do not have a patch but it would be great if someone could provide one as we are blocked in our effort to turn on C++20 by this issue)

**Comment by alalek** [comment]
> type_traits.hpp:87:35

Please provide path to mentioned file.

**Comment by daravi** [comment]
@alalek Sorry but it seems like the issue is actually in the ade header `ade/util/type_traits.hpp`:
https://github.com/opencv/ade/issues/22

There doesn't seem to be any activity on that ticket since July. Could you perhaps evaluate that ticket and close this one as duplicate?

**Comment by alalek** [comment]
Perhaps problem can be reproduced with OpenCV build:
- `cmake ...  -DCMAKE_CXX_STANDARD=20`
- build opencv_test_gapi

Note: it doesn't trigger `result_of` problem with GCC 10.3.1 or Clang 11.0.0 from Fedora 33

@dmatveev Could someone take a look on ADE build issues?

@daravi As workaround you can build OpenCV using C++14/17. This should not affect your applications which should be able to works with C++20 and use C++14/17 libraries ("ade" is internal dependency, it's headers are not exposed).

Another ADE build issues:

```
3rdparty/ade/ade-0.1.1f/sources/ade/include/ade/util/memory_range.hpp:237:24: warning: ‘template<class _Tp> struct std::is_pod’ is deprecated: use is_standard_layout && is_trivial instead [-Wdeprecated-declarations]
  237 |     static_assert(std::is_pod< util::decay_t<decltype(*data(src))> >::value, "Types must be pod");
      |                        ^~~~~~
```

**Comment by daravi** [comment]
@alalek Please note that as mentioned the `result_of` issue only affects Clang 13 AFAIK since I think it is removed in that version. Re, compiling opencv with C++14 or 17 I was afraid of any possible ABI breaks between those and C++20. (but since that's unlikely I will look into that in the meantime)

**Comment by dmatveev** [comment]
Hi folks. Merging the necessary PRs in ADE now, sorry for the delay.
Please note we'll have to make a new release for ADE & bump it in the OpenCV build scripts to make OpenCV build with C++20 now.

Though our upper limit is still C++11, isn't it? @alalek -- would it be lifted soon?

**Comment by dmatveev** [comment]
cc: @asmorkalov

**Comment by alalek** [comment]
> Though our upper limit is still C++11, isn't it? @alalek -- would it be lifted soon?

There is no upper limit for C++ standard (however latest versions are not tested on CI).
Only lower limit is specified - OpenCV 4.x requires C++11.
