### ISSUE TITLE
Documentation : cv::Mat::reshape()

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#21125]
[reshape (int cn, int rows=0) const](https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#a4eb96e3251417fa88b78e2abd6cfd7d8) it will be good adding some simple sample of usage code.
[reshape (int cn, int newndims, const int *newsz) const](https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#a50e606fe51f53b896b66051634a018fb) Parameters are undocumented also  it will be good adding some simple sample of usage code.
[reshape (int cn, const std::vector< int > &newshape) const](https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#ab2e41a510891e548f744832cf9b8ab89) Parameters are undocumented also  it will be good adding some simple sample of usage code.

**Comment by Dhruv454000** [comment]
can I work on this?

**Comment by JatinKumar001** [comment]
@sturkmen72, if no one is working on it can I start working on it.

**Comment by sturkmen72** [comment]
@JatinKumar001 sure, you can. you can mail me if any help is needed.

**Comment by JatinKumar001** [comment]
Awesome, thanks!

**Comment by asmorkalov** [comment]
@sturkmen72 Thanks a lot for the reported issue! We plan to make release in mean time. Do you plan to work on the ticket?
