### ISSUE TITLE
Object trackers not available Python

### ISSUE THREAD

**Issue by KristianBalaj** [opencv/opencv#21135]
Opencv version: 4.5.4
Pip version: 21.3.1
Python version: 3.8.9

I've installed opencv with following commands:

```
pip install opencv-python  
pip install opencv-contrib-python
```

Following code fails to run:

```python
import cv2

tracker = cv2.TrackerBoosting_create()

```

There are also other trackers that are missing (e.g. from this tutorial https://learnopencv.com/object-tracking-using-opencv-cpp-python/)

There are only following trackers available:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/20045353/143656394-cf425ad9-349c-4820-9d4b-1b19e1baaa94.png">

**Comment by NickJackolson** [comment]
@KristianBalaj  some of the trackers and other features require you to build the library from source with certain flags because some of the algorithms in opencv-contrib are non-free algorithms.

**Comment by LaurentBerger** [comment]
You cannot install opencv-python  and opencv-contrib-python. Uninstalled both version and install only opencv-contrib-python
**[Installation and Usage

    If you have previous/other manually installed (= not installed via pip) version of OpenCV installed (e.g. cv2 module in the root of Python's site-packages), remove it before installation to avoid conflicts.](https://pypi.org/project/opencv-contrib-python/)**
