### ISSUE TITLE
Netatmo webcam compatibility RTSP flow

### ISSUE THREAD

**Issue by pilot1981** [opencv/opencv#21151]
Hi,
I need to understand howto to obtain RTSP video flow from my webcam outdoor Netatmo presence, below you can find some other info:

https://dev.netatmo.com/apidocumentation/security 
https://www.home-assistant.io/integrations/netatmo/ 

I am aware they use H.264 via HLS - https live streaming; 

Hypothetically it might be possible to use ffmpeg to convert the HLS stream to an RTSP stream. Or we can get this to work would be via the camera's JPEG snapshots, which should give you good quality but poor performance (low frames per second).

**Comment by pilot1981** [comment]
Sorry, I don’t understood if NETAMO webcam is already supported?

**Comment by mshabunin** [comment]
OpenCV uses 3rdparty libraries in _videoio_ module, if they support said stream then it should be possible to read it in OpenCV. FFmpeg or GStreamer are potential cantidates, please try them first.
