### ISSUE TITLE
CMake Error at cmake/OpenCVFindProtobuf.cmake:20

### ISSUE THREAD

**Issue by demon1992** [opencv/opencv#21183]
- OpenCV => 4.5.4
- Operating System / Platform => Windows 64 Bit
- Compiler => cmake

##### Detailed description

```
CMake Error at cmake/OpenCVFindProtobuf.cmake:20 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
```
```
Call Stack (most recent call first):
  3rdparty/protobuf/CMakeLists.txt:161 (get_protobuf_version)
```
I encountered the above problem when compiling **_opencv-4.5.4_** and **_opencv_contrib-4.5.4_** with cmake. How do I solve this problem?

**Comment by alalek** [comment]
Try this:

```.diff
-string(REGEX MATCHALL "[0-9]+" ver ${ver})
+string(REGEX MATCHALL "[0-9]+" ver "${ver}")
```

Feel free to prepare PR to 3.4 branch if it works for your case.

---

BTW, you need to clear CMake cache if you install or upgrade any dependencies or play with build options. Or use clean build directory. Avoid using of `cmake-gui`.
