### ISSUE TITLE
the function of CalibrateHandeye is only used for eye-in-hand type?

### ISSUE THREAD

**Issue by jorketcode** [opencv/opencv#21185]
I saw this function in the documentation and its description uses the eye-in-hand type, but I now need to use it for the eye-to-hand type, is this function supported?

**Comment by catree** [comment]
Both configurations are supported. Have a look at the [documentation](https://docs.opencv.org/4.5.4/d9/d0c/group__calib3d.html#gaebfc1c9f7434196a374c382abf43439b).

Or [this test.](https://github.com/opencv/opencv/blob/d2f87ca76cdbe61afa14142dc7011694e01b2ae3/modules/calib3d/test/test_calibration_hand_eye.cpp#L145)
