### ISSUE TITLE
Implementation Opencv batch=4 not found

### ISSUE THREAD

**Issue by dkravchenko-ivideon** [opencv/opencv#21210]
In the description README.md contains a table with the measurement of frames per second on various DL platforms (Opencv, tkDNN). There is also a link to the repository https://gist.github.com/YashasSamaga/48bdb167303e10f4d07b754888ddbdcf
Unfortunately, I didn't find a test implementation for the OpenCV batch=4 option at this link. I would be very grateful if you would share the information, the implementation of YOLO on Opencv and batch=4.

**Comment by alalek** [comment]
What is the problem to run benchmarks yourself using the target hardware / software configuration and interested networks?

**Comment by YashasSamaga** [comment]
and the benchmark script supports batching (see `constexpr auto default_batch_size = 1;`). This is how numbers were generated for Darknet README.md.

**Comment by dkravchenko-ivideon** [comment]
Thank you very much! This is my inattention
