### ISSUE TITLE
Python bindings 4.5.4: "kp.detect()" returns tuple instead list

### ISSUE THREAD

**Issue by doublex** [opencv/opencv#21266]
opencv <= 4.5.3: returns list 
opencv <= 4.5.4: returns tuple 

Testcase:

````
import cv2
frame = cv2.imread( 'any.png' )
kp_detector = cv2.FastFeatureDetector_create()
kpf = kp_detector.detect(frame, None)
assert type(kpf) is list, type(kpf)
````

**Comment by alalek** [comment]
"List" results has been replaced with tuples in Python bindings.
No plans to change them back.

---

Python bindings is still under development.
We trying to keep compatibility but there is no any guarantee.
Always tun tests of your application after OpenCV version upgrade to handle changes.

**Comment by doublex** [comment]
@alalek 
Thanks for pointing out
