### ISSUE TITLE
Use SQPNP with USAC

### ISSUE THREAD

**Issue by fatihmd** [opencv/opencv#21273]
##### System information (version)

- OpenCV => : 4.5.4
- Operating System / Platform => Linux/Ubuntu 18.04

##### Detailed description

In my experiment I want to use SQPNP in solvepnpransac with USAC params. I observed that gcransac and magsac overperforms regular ransac implementation. But when I set usac params in solvepnpransac there is no option to state the pnp method. Is it possible to use SQPNP with magsac or gcransac, thanks in advance.

**Comment by scott-vsi** [comment]
I believe the answer is no. See #23229
