### ISSUE TITLE
Bug in cv2.copyMakeBorder

### ISSUE THREAD

**Issue by qtboi** [opencv/opencv#21274]
##### System information (version)

- opencv-python==4.5.4.60
- Operating System / Platform => ubuntu

##### Detailed description
The following code 
```
cv2.copyMakeBorder(np.random.randn(16, 16, N), 1, 1,1,1, borderType=cv2.BORDER_REFLECT)
```
threw exception for `N>512`:
```
OpenCV(4.5.4) /tmp/pip-req-build-24v3eisa/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'
```

##### Steps to reproduce

The following code have a quite unexpected output:
```
import cv2
import numpy as np


for N in range(1, 2000):
    try:
        cv2.copyMakeBorder(np.random.randn(16, 16, N), 1, 1,1,1, borderType=cv2.BORDER_REFLECT)
    except Exception as e:
        print(N)
        print(e)
        break
```
```
513
OpenCV(4.5.4) /tmp/pip-req-build-24v3eisa/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'
```

**Comment by qtboi** [comment]
@alalek can you please explain what `question (invalid tracker)` tag means? Should i provide more info?

**Comment by qtboi** [comment]
@alalek IMO it is not question
```cv2.copyMakeBorder(np.random.randn(16, 16, 513), 1, 1,1,1, borderType=cv2.BORDER_REFLECT)```
threw exception while the input is ok
looks more like a bug

**Comment by alalek** [comment]
> `_src.dims() <= 2`

copyMakeBorder doesn't work with 3D tensors.

2D "images" can't have more than 512 channels (builtin `cv::Mat` limitation).

`ndarray` to `cv::Mat` conversion is a different story: #19091

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
