### ISSUE TITLE
Starting on version 4.5.4 findContours returns contours as a tuple instead of a list

### ISSUE THREAD

**Issue by bmtrindade** [opencv/opencv#21284]
##### System information (version)
- OpenCV 4.5.4
- Python 3.7 (opencv installed using pip: "pip install opencv-python") 
- Ubuntu 18.04 amd64

##### Detailed description

Up to version 4.5.3 findContours returned contours as a list. Starting on version 4.5.4 the contours are returned as a tuple. This will break codes that try to modify the returned tuple. 

##### Steps to reproduce

contours, hierarchy = cv2.findContours(binary_image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
for i in range(len(contours)):
        contours[i] = np.round(contours[i]*[1/3, -1/3]).astype(np.int32)

**Comment by bmtrindade** [comment]
@alalek ,
Could you please point me out where this is duplicated? I could not find the issue that duplicates this one.
Thanks!

**Comment by alalek** [comment]
Here is the fresh issue about that: #21266

**Comment by bmtrindade** [comment]
Thank you very much!
