### ISSUE TITLE
building project "opencv_dnn.vcxproj" -- FAILED

### ISSUE THREAD

**Issue by brain-czy** [opencv/opencv#21298]
##### System information (version) 

- OpenCV => 4.4
- opencv_contrib => 4.4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- Cmake Version => 3.22.1
- CUDA => 10.1
- CUDNN => 8.1.1

when I build opencv in Windows enviroment, I got a failed message. The detail of build log can be seen in appendix. many thanks ! I have wasted many time on this error.

[all_build_log.txt](https://github.com/opencv/opencv/files/7750729/all_build_log.txt)
[build_error.txt](https://github.com/opencv/opencv/files/7750727/build_error.txt)
[cmake_log.txt](https://github.com/opencv/opencv/files/7750728/cmake_log.txt)

**Comment by alalek** [comment]
> OpenCV => 4.4

Outdated version. As issue's template requested you should check the latest release or code from 4.x branch.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by crackwitz** [comment]
related: https://forum.opencv.org/t/building-project-opencv-dnn-vcxproj-failed/6828

**Comment by brain-czy** [comment]
> > OpenCV => 4.4
> 
> Outdated version. As issue's template requested you should check the latest release or code from 4.x branch.
> 
> Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

I have update opencv and opencv contrib version to 4.x， but I still got error when build stage:
`50>   Creating library D:/dev-env/open-cv-cuda/cuda-build-x/lib/Release/opencv_dnn454.lib and object D:/dev-env/open-cv-cuda/cuda-build-x/lib/Release/opencv_dnn454.exp
50>convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnCreateTensorTransformDescriptor referenced in function "private: void __cdecl cv::dnn::cuda4dnn::csl::cudnn::TensorTransformDescriptor::constructor<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >(class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > const &,class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > const &)" (??$constructor@V?$vector@_KV?$allocator@_K@std@@@std@@@TensorTransformDescriptor@cudnn@csl@cuda4dnn@dnn@cv@@AEAAXAEBV?$vector@_KV?$allocator@_K@std@@@std@@0@Z)
50>pooling_layer.cpp.obj : error LNK2001: unresolved external symbol cudnnCreateTensorTransformDescriptor
50>convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnSetTensorTransformDescriptor referenced in function "private: void __cdecl cv::dnn::cuda4dnn::csl::cudnn::TensorTransformDescriptor::constructor<class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > >(class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > const &,class std::vector<unsigned __int64,class std::allocator<unsigned __int64> > const &)" (??$constructor@V?$vector@_KV?$allocator@_K@std@@@std@@@TensorTransformDescriptor@cudnn@csl@cuda4dnn@dnn@cv@@AEAAXAEBV?$vector@_KV?$allocator@_K@std@@@std@@0@Z)
50>pooling_layer.cpp.obj : error LNK2001: unresolved external symbol cudnnSetTensorTransformDescriptor
50>convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnDestroyTensorTransformDescriptor referenced in function __catch$??$constructor@V?$vector@_KV?$allocator@_K@std@@@std@@@TensorTransformDescriptor@cudnn@csl@cuda4dnn@dnn@cv@@AEAAXAEBV?$vector@_KV?$allocator@_K@std@@@std@@0@Z$0
50>pooling_layer.cpp.obj : error LNK2001: unresolved external symbol cudnnDestroyTensorTransformDescriptor
50>convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnTransformTensorEx referenced in function "void __cdecl cv::dnn::cuda4dnn::csl::cudnn::transform<float>(class cv::dnn::cuda4dnn::csl::cudnn::Handle const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorTransformDescriptor const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::DevicePtr<float const >,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::DevicePtr<float>)" (??$transform@M@cudnn@csl@cuda4dnn@dnn@cv@@YAXAEBVHandle@01234@AEBVTensorTransformDescriptor@01234@AEBV?$TensorDescriptor@M@01234@V?$DevicePtr@$$CBM@1234@2V?$DevicePtr@M@1234@@Z)
50>pooling_layer.cpp.obj : error LNK2001: unresolved external symbol cudnnTransformTensorEx
50>D:\dev-env\open-cv-cuda\cuda-build-x\bin\Release\opencv_dnn454.dll : fatal error LNK1120: 4 unresolved externals`

**Comment by kurthorvath** [comment]
@brain-czy 
how was the problem solved?
