### ISSUE TITLE
Corrupt JPEG err : 1 extraneous bytes before marker 0xdb

### ISSUE THREAD

**Issue by Neilblaze** [opencv/opencv#21373]
##### System information (version)

- OpenCV => 4.5.1
- Operating System / Platform => Windows 11 (64 Bit)
- Webcam => Logitech C270
- Compiler => Visual Studio 2017

##### Detailed description

I'm getting this err — `Corrupt JPEG data: 1 extraneous bytes before marker 0xdb`

**Comment by Kumataro** [comment]
Maybe this issue is same as #9477.
