### ISSUE TITLE
Audio with Video

### ISSUE THREAD

**Issue by kXborg** [opencv/opencv#21376]
Hi, OpenCV 4.5.5 release notes mention audio support. Can anyone tell me how to get it working?

**Comment by stevejayd** [comment]
trying

**Comment by stevejayd** [comment]
Here's some code, that opens microphone . I cant fined any defiitions for the settings for 

#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>Adio depth etc.

Steve
#include <iostream>

using namespace cv;
using namespace std;

int main(int, char**)
{
    Mat frame;
    vector<Mat> audioData;
    VideoCapture cap(0);
    vector<int> params{ 58, 57,   CAP_PROP_VIDEO_STREAM, -1 };
    //vector<int> params {    CAP_PROP_AUDIO_STREAM, 0,       CAP_PROP_VIDEO_STREAM, -1   };

    //cap.open(0, CAP_MSMF, params);
    if (!cap.isOpened())
    {
        cerr << "ERROR! Can't to open microphone" << endl;
        return -1;
    }

    const int audioBaseIndex = (int)cap.get(CAP_PROP_AUDIO_BASE_INDEX);
    const int numberOfChannels = (int)cap.get(CAP_PROP_AUDIO_TOTAL_CHANNELS);
    cout << "CAP_PROP_AUDIO_DATA_DEPTH: " << depthToString((int)cap.get(CAP_PROP_AUDIO_DATA_DEPTH)) << endl;
    cout << "CAP_PROP_AUDIO_SAMPLES_PER_SECOND: " << cap.get(CAP_PROP_AUDIO_SAMPLES_PER_SECOND) << endl;
    cout << "CAP_PROP_AUDIO_TOTAL_CHANNELS: " << numberOfChannels << endl;
    cout << "CAP_PROP_AUDIO_TOTAL_STREAMS: " << cap.get(CAP_PROP_AUDIO_TOTAL_STREAMS) << endl;

    const double cvTickFreq = getTickFrequency();
    int64 sysTimeCurr = getTickCount();
    int64 sysTimePrev = sysTimeCurr;
    while ((sysTimeCurr-sysTimePrev)/cvTickFreq < 10)
    {
        if (cap.grab())
        {
            for (int nCh = 0; nCh < numberOfChannels; nCh++)
            {
                cap.retrieve(frame, audioBaseIndex+nCh);
                audioData.push_back(frame);
                for
                sysTimeCurr = getTickCount();
            }
        }
        else
        {
            cerr << "Grab error" << endl;
            break;
        }
    }
    int numberOfSamles = 0;
    for (auto item : audioData)
        numberOfSamles+=item.cols;
    cout << "Number of samples: " << numberOfSamles << endl;

    return 0;
}

**Comment by alalek** [comment]
Check opencv samples / tests.

**Comment by OrkhanGG** [comment]
> Check opencv samples / tests.

I can't find, can you please provide a bit more info?
