### ISSUE TITLE
Compilation -DWITH_OPENGL=ON does not work with out   -DWITH_QT=ON 

### ISSUE THREAD

**Issue by Jakobovski** [opencv/opencv#21381]
Compilation with  `-DWITH_OPENGL=ON` does not work without also setting `-DWITH_QT=ON`.

**Expected behaviour**
An error should be raised that `WITH_OPENGL=ON` requires `WITH_QT=ON`

**Comment by LaurentBerger** [comment]
which version?

**Comment by h6197627** [comment]
This helped me: https://github.com/opencv/opencv/pull/21347

**Comment by Jakobovski** [comment]
4.5.3 but i think it's relevant to all version

**Comment by LaurentBerger** [comment]
Try with master : https://github.com/opencv/opencv/pull/21347
