### ISSUE TITLE
java:  opencv 4.5.3 ,cv::Exception: OpenCV(4.5.3) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\model.cpp:1216: error: (-215:Assertion failed) length > FLT_EPSILON in function 'cv::dnn::TextDetectionModel_DB_Impl::unclip'

### ISSUE THREAD

**Issue by syly666** [opencv/opencv#21395]
##### System information (version)

- OpenCV => 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler =>  java IDEA

##### Detailed description

when i use  TextDetectionModel_DB in  Singleton for Microservices， The exceptions are as follows：
cv::Exception: OpenCV(4.5.3) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\model.cpp:1216: error: (-215:Assertion failed) length > FLT_EPSILON in function 'cv::dnn::TextDetectionModel_DB_Impl::unclip'

when i use  TextDetectionModel_DB  not in Singleton， it ok。

Is this a bug？
Please reply me. Thank you

my codes are as follows:

public class TextDetection {

    private static TextDetection instance = new TextDetection();

    private  TextDetectionModel_DB textModel;

    /**
     * Instantiates a new TextDetection.
     */
    private TextDetection() {
        String path = "";
        try {
            textModel = new TextDetectionModel_DB("D:\\Dev_dan\\Dev_dan\\src\\main\\resources\\opencvDnnFiles\\DB_IC15_resnet18.onnx");
            log.info("load TextDetection model success");
            float binThresh = 0.3f;
            float polyThresh = 0.5f;
            int maxCandidates = 200;
            double unclipRatio = 2.0;
            textModel.setBinaryThreshold(binThresh);
            textModel.setPolygonThreshold(polyThresh);
            textModel.setMaxCandidates(maxCandidates);
            textModel.setUnclipRatio(unclipRatio);
            // Normalization parameters
            double scale = 1.0/255; 
            Scalar mean = new Scalar(122.67891434, 116.66876762, 104.00698793);
            // The input shape
            Size inputSize = new Size(736, 736);
            textModel.setInputParams(scale, inputSize, mean);
            log.info("set TextDetection Params success");
        } catch (Exception e) {
  
            log.error("load TextDetection model error: {}", e);
     
        }
    }

    /**
     * Get instance TextDetection.
     *
     * @return the TextDetection
     */
    public static TextDetection getInstance() {
        return instance;
    }

    public  boolean isTooManyWords(Mat imgMat, int nums) {
        long start1 = System.currentTimeMillis();
        List<MatOfPoint> detections = new ArrayList<>();
        try {
            // Post-processing parameters
            textModel.detect(imgMat, detections);
            System.out.println("ok");
            if (detections.size() >= nums) {
                return true;
            }
            int textNums = 0;
            Point[] pointsOfRectangle = new Point[4];
            for (MatOfPoint point : detections) {
                pointsOfRectangle = point.toArray();
                textNums += Math.ceil((pointsOfRectangle[2].x - pointsOfRectangle[0].x) / 20);
                textNums += Math.floor((pointsOfRectangle[1].y - pointsOfRectangle[0].y) / 20);
            }
            if (textNums >= nums * 2) {
                return true;
            }

        } catch (Exception e) {
            log.error("textDect error ： {}", e);
        } finally {
            if(!detections.isEmpty()){
                detections.clear();
            }
            long end2 = System.currentTimeMillis();
            System.out.println("textDect  cost :" + (end2 - start1) + " ms");
        }
        return false;
    }
}

**Comment by alalek** [comment]
Complete reproducer should include input data.

You must follow the issue's template and not remove them: https://github.com/opencv/opencv/blame/4.5.5/.github/ISSUE_TEMPLATE.md#L56
