### ISSUE TITLE
PTGUI and OPENCV

### ISSUE THREAD

**Issue by yyfyan** [opencv/opencv#21390]

**Comment by yyfyan** [comment]
As everyone knows, the **ptgui** is a very famous software in image stitching, as well **OPENCV Stitcher**. But ptgui can set some match point manually, and OPENCV Stitcher only auto set. Some scenarios fail to detect match points, lead to fail stitch. 
    Can we use the ptgui to calculate stitch parameters, and convert to OPENCV?  PTGUI can get yaw/roll/pitch , a,b,c,d parameters, it's different from OPENCV.
    https://www.ptgui.com/

**Comment by yyfyan** [comment]
As everyone knows, the **ptgui** is a very famous software in image stitching, as well **OPENCV Stitcher**. But ptgui can set some match point manually, and OPENCV Stitcher only auto set. Some scenarios fail to detect match points, lead to fail stitch. 
    Can we use the ptgui to calculate stitch parameters, and convert to OPENCV?  PTGUI can get yaw/roll/pitch , a,b,c,d parameters, it's different from OPENCV.
    https://www.ptgui.com/

**Comment by phantomwork** [comment]
So, what is the basic algorithm of pitgui??

**Comment by phantomwork** [comment]
Please help me to implement that awesome algo.
