### ISSUE TITLE
OpenCV 4.5.5 with GStreamer compilation issue with opencv_videoio

### ISSUE THREAD

**Issue by klukander** [opencv/opencv#21393]
##### System information (version)
- OpenCV => 4.5.5.
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2022

##### Detailed description

Building OpenCV with Gstreamer using CMake 3.22.1 succesfully generates the solution file after configuring all the paths. When compiling the solution in both Debug and Release mode, opencv_videoio fails due to an unresolved external link to _imp_gst_audio_info_from_caps. 

Solution: Since I don't know how to edit the CMake files for this, I succeeded in getting it to work by adding the path to the gstaudio-1.0.lib to the opencv_videoio project in Visual Studio:
<path to>\gstreamer\1.0\msvc_x86_64\lib\gstaudio-1.0.lib
opencv_videoio -> properties -> linker -> additional dependencies

I suspect the real solution is to add that to the CMake configuration files for videoio

**Comment by alalek** [comment]
Please check why this PR doesn't work for your configuration: #21294
