### ISSUE TITLE
Missing BestOf2NearestRangeMatcher_create in bindings

### ISSUE THREAD

**Issue by awcchungster** [opencv/opencv#21406]
### Expected behaviour

Write here how did you expect the library to function.

Runs cv.detail.BestOf2NearestRangeMatcher_create as expected on opencv-python                      4.5.5.62

### Actual behaviour

AttributeError: module 'cv2.detail' has no attribute 'BestOf2NearestRangeMatcher_create'

### Steps to reproduce

I am running the stitching_detailed function. When I run the script, I am passing a value into range_width, which calls the below line.
https://github.com/opencv/opencv/blob/master/samples/python/stitching_detailed.py#L251

It appears the Python bindings are missing this class. It is in the latest OpenCV C docs. 
- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [x ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - x[x ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ x] I'm using the latest version of ``opencv-python``

**Comment by berak** [comment]
indeed, only the `BestOf2NearestMatcher` has a `create()` method.
however, all Matchers here have their constructors exposed (returning a proper `Ptr<something>`)
and can be used like: `cv.detail_BestOf2NearestMatcher()`

i'd propose to rewrite the sample code in this style
