### ISSUE TITLE
Camera white balance support for Logitech BRIO 4K 

### ISSUE THREAD

**Issue by JianDk** [opencv/opencv#21408]
##### System information (version)
- OpenCV => 4.5.3.56
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio Code 1.63

##### Detailed description
I have a Logitech BRIO 4K camera running on Windows 10 64 bit. The opencv version I have installed is opencv-python==4.5.3.56 From Logitech’s software I am able to disable auto white balance, as well as adjust white balance values.

The sample code below does not seem to work. 
```
import cv2
cap = cv2.VideoCapture(1, cv2.CAP_DSHOW)
cap.set(cv2.CAP_PROP_AUTO_WB, 0)
cap.set(cv2.CAP_PROP_WHITE_BALANCE_BLUE_U, 5000)
```

I am aware that currently in the documentation `CAP_PROP_WHITE_BALANCE_BLUE_U` is not currently fully supported. However it is possible using the `cap.get` method to extract white balance currently stored in camera's memory, but it is not possible to set a new value.  Is there a way to get it fully supported or any workaround? Also, currently the `cap.set(cv2.CAP_PROP_AUTO_WB, 0)` does not seem to work either.

**Comment by alalek** [comment]
> CAP_DSHOW

Deprecated backend. Low priority or even wont fix.

**Comment by JianDk** [comment]
Thanks, but is there an alternative instead of CAP_DSHOW? What is the current main approach in adjusting the white balance?

**Comment by mshabunin** [comment]
@JianDk , main _videoio_ backend on Windows is `CAP_MSMF` (MediaFoundation).

**Comment by JianDk** [comment]
@mshabunin thanks for the suggestion. I tried when I executed the below codes I got an error

```
import cv2
import time
#Connect to a camera
cap = cv2.VideoCapture(1, cv2.CAP_MSMF)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, int(1920))
cap.set(cv2.CAP_PROP_FRAME_HEIGHT,int(1080))
cap.set(cv2.CAP_PROP_EXPOSURE, -3)
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1)
cap.set(cv2.CAP_PROP_BRIGHTNESS, 1000)
cap.set(cv2.CAP_PROP_GAIN, 5)
#Auto WB is off at value 1 and on at value 3
cap.set(cv2.CAP_PROP_AUTO_WB, 1)
cap.set(cv2.CAP_PROP_WHITE_BALANCE_BLUE_U, 2000)


print('brightness ', cap.get(cv2.CAP_PROP_BRIGHTNESS))
print('contrast ', cap.get(cv2.CAP_PROP_CONTRAST))
print('saturation ', cap.get(cv2.CAP_PROP_SATURATION))
print('gain ', cap.get(cv2.CAP_PROP_GAIN))
print('exposure ', cap.get(cv2.CAP_PROP_EXPOSURE))
print('Sharpness ', cap.get(cv2.CAP_PROP_SHARPNESS))
print('Auto exposure on / off ', cap.get(cv2.CAP_PROP_AUTO_EXPOSURE))
print('auto white balance', cap.get(cv2.CAP_PROP_AUTO_WB))
print('white balance', cap.get(cv2.CAP_PROP_WHITE_BALANCE_BLUE_U))


ret, frame = cap.read()
cv2.imwrite('test1.png', frame)
cap.release()
```

The error message 
`[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback`

When I gogle this error there seems to be a bug for CAP_MSMF [https://stackoverflow.com/questions/60007427/cv2-warn0-global-cap-msmf-cpp-674-sourcereadercbsourcereadercb-termina](url)

**Comment by JianDk** [comment]
After some more testing I figured it out. For Logitech BRIO 4K usb webcam the right property to set to adjust the white balance is 
first to turn off auto white balance. Then, the property is to set is `cv2.CAP_PROP_TEMPERATURE`. Below is the working code snippet and as pointed out by @mshabunin one should use `CAP_MSMF` using `CAP_DSHOW` does not work. 

The working code

```
import os
os.environ["OPENCV_VIDEOIO_MSMF_ENABLE_HW_TRANSFORMS"] = "0"
import cv2
import time
#Connect to a camera
cap = cv2.VideoCapture(0, cv2.CAP_MSMF)
cap2 = cv2.VideoCapture(2, cv2.CAP_MSMF)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, int(1920))
cap.set(cv2.CAP_PROP_FRAME_HEIGHT,int(1080))
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0)
cap.set(cv2.CAP_PROP_EXPOSURE, -5)
cap.set(cv2.CAP_PROP_BRIGHTNESS, 100)

#Auto WB is off at value 1 and on at value 3
cap.set(cv2.CAP_PROP_AUTO_WB, 0)
cap.set(cv2.CAP_PROP_TEMPERATURE, 7000)
ret, frame = cap.read()
cv2.imwrite('test1.png', frame)
cap.release()
```
