### ISSUE TITLE
compile opencv with inference-engine

### ISSUE THREAD

**Issue by husiluanxiang** [opencv/opencv#21445]
hello when I use cmake to compile opencv with inferenceEngine I get problem next:
![image](https://user-images.githubusercontent.com/38007233/149445505-7448ca18-4933-448a-a7e1-8677cc57b0c7.png)
how to solve it

**Comment by husiluanxiang** [comment]
![image](https://user-images.githubusercontent.com/38007233/149445996-d86fc25a-2248-4821-bfc6-d00ae2d77f00.png)

**Comment by alalek** [comment]
Can't reproduce.
Compare with CI logs: http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64
You should follow the instructions from here: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend
Don't use cmake-gui as its results are hard to reproduce. Use "cmake"

---

Avoid posting of text information through screenshots in Internet.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
