### ISSUE TITLE
Videoio Capgstreamer introducing 0.5-1.0 s latecy

### ISSUE THREAD

**Issue by JMOlmos-cafsig** [opencv/opencv#21446]
##### Versions
- OpenCV => 4.4
- Operating System / Platform => Linux tegra R32.2 (Ubuntu 18.04 )/ NV XavierAgx (ARM64) 
- Compiler => gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- Module => videoio
- File => capgstreamer.cpp
- Gstreamer version => 1.14.5

##### Detailed description

Gstreamer capture through appsink introduces high latency on frame retrieval. Average latencies of 0.5 s with 1 s peak found with cpu load less than 80%. Latency tested using glass to glass method. Pipeline is:
- Emitter (videosrc ! omxh264enc ! rtph264pay ! udpsink)
- Receiver (udpsrc !  nvv4l2dec  !  appsink)

appsink is read with a dedicated thread to flush the pipeline

When changing appsink for display glass to glass latency falls to <80 ms.

Seems like a buffering problem or bottleneck on gst sample retrieve but i am not sure. Video doesn't seem to be downsampled and latency remains lowering framerate.

**Comment by asmorkalov** [comment]
1. Do you observe significant latency, if place  `appsink` at the end of the first pipeline?

**Comment by JMOlmos-cafsig** [comment]
1. the videosrc in application is appsrc, ¿is there any way to shortcut the pipeline on src and sink with the VideoCapture and VideoWritter o i have to use some trick like linux fifo to split that into two separated pipelines avoiding encoding?
2. The output is converted through nvidconv to copy the gpu memory to cpu so that the decoding can be done on NVENC dedicated hardware. gstshark traces shows that the conversion is not a problem at all taking an average of 12 ms.

I will do some tests to see if i can provide further information.

**Comment by alalek** [comment]
Low latency encoding/decoding over network is not a simple task with some generic solution.
Refer to information from vendor and GStreamer plugins. OpenCV is out of scope here.

E.g. here:
- https://forums.developer.nvidia.com/t/changing-the-properties-of-omxh264enc-gstreamer-1-0-element/40622 - `low-latency=true`
- https://developer.ridgerun.com/wiki/index.php?title=NVIDIA_Jetson_TX1_TX2_Video_Latency - some information how to measure the latency.
