### ISSUE TITLE
Please ask how to solve this problem

### ISSUE THREAD

**Issue by 13737554501** [opencv/opencv#21444]
![-190d273a8698af7b](https://user-images.githubusercontent.com/81922395/149441718-b09ce807-934b-44f4-82fe-374a6bc84365.jpg)
Please ask how to solve this problem

**Comment by alalek** [comment]
Avoid posting of text information through screenshots in Internet. It is ridiculous.
You just block searching for similar cases.
Your searching keyword is mingw+opencv as only MSVC is officially supported on Windows platform (check [CI logs](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-4.x&width=7)).

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
