### ISSUE TITLE
Do not report for FP16 compatibility on old Nvidia cards

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#21461]
https://github.com/opencv/opencv/blob/4801526f354057fecde2d70a52c69974aa5ee53f/modules/dnn/src/dnn.cpp#L251-L255

Since commit d0fe6ad10967fd2b007a4cf83b00d6f8446deb42 `cv::dnn::getAvailableBackends()` will list CUDA_FP16 for all Cuda devices even the old ones that do not have `__half` compute capabilities
The simple check has been removed, and I would suggest to add it back, what do you think @YashasSamaga ?

**Comment by YashasSamaga** [comment]
The check was removed as it was a bug. See this review comment: https://github.com/opencv/opencv/pull/19222/files#r588883516

I think the checks must be done every time in `getAvailableTargets` function instead of caching the results.

**Comment by JulienMaille** [comment]
@YashasSamaga OK I understand the potential issue with multiple GPUs, however there's no other bugs because on my GTX 970, testing all available backends I get:
`
[ WARN:0] global D:\Dev\opencv\modules\dnn\src\dnn.cpp (2699) cv::dnn::dnn4_v20211004::Net::Impl::initCUDABackend The selected CUDA device does not support FP16 target; switching to FP32 target.
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.4-dev) Error: Gpu API call (cuDNN did not return a suitable algorithm for convolution.) in cv::dnn::cuda4dnn::csl::cudnn::ConvolutionAlgorithm<struct __half>::ConvolutionAlgorithm, file D:\Dev\opencv\modules\dnn\src\cuda4dnn\csl\cudnn/convolution.hpp, line 303
`

**Comment by YashasSamaga** [comment]
Can you share a reproducer for this?

This logically is impossible. The FP16 check is done before initialization. The warning says that it switched target to FP32 but then the exception has `struct __half` in it. It shouldn't have been initializing FP16 operations in FP32 target.

**Comment by JulienMaille** [comment]
I don't anything in an online repository but can share a small msvc project with you by email if it's fine

**Comment by JulienMaille** [comment]
What happens when calling `setPreferableTarget(TARGET_CUDA_FP16)` manually, is it handled?
Code below is run on all (backend, target) returned by `getAvailableTargets`
```c++
bool loadModel(const std::string& fileName, std::pair<cv::dnn::Backend, cv::dnn::Target> conf)
{
    if( !setDevice(conf.second) )
    {
        printf("cannot set device");
        return false;
    }

    if( !fileExists(fileName) )
    {
        printf("model does not exist");
        return false;
    }
    
    net = cv::dnn::readNetFromONNX(fileName);

    if( net.empty() )
    {
        printf("empty network");
        return false;
    }

    net.setPreferableBackend(conf.first);
    net.setPreferableTarget(conf.second);
}
```

**Comment by YashasSamaga** [comment]
> What happens when calling setPreferableTarget(TARGET_CUDA_FP16) manually, is it handled?

It sets the preferred target to `DNN_TARGET_CUDA_FP16` and then clears the network state if the new target differs from the current target. This also implies a complete reinitialization in the next forward pass. In the first forward pass,`initCUDABackend` is called for initialization and this will check that FP16 isn't supported by the device and then switch to FP32 and continues with the initialization.

> `setDevice(conf.second)`

What is your intent for this line?

**Comment by JulienMaille** [comment]
> > `setDevice(conf.second)`
> 
> What is your intent for this line?
Selecting the Nvidia card
```c++
bool setDevice(cv::dnn::Target target)
{
#ifdef HAVE_CUDA
    if( target == cv::dnn::DNN_TARGET_CUDA || target == cv::dnn::DNN_TARGET_CUDA_FP16 )
    {
        if( !hasCudaDevice(target) ) return false;
        int d = getFirstCudaDevice();
        if( d<0 ) return false;
        cv::cuda::setDevice(d);
    }
#endif
}
```

**Comment by YashasSamaga** [comment]
> Selecting the Nvidia card

Then your code isn't doing what you want. The target IDs are some internal constants in the DNN module. I think you're picking a random device with `setDevice(target)`. And CUDA target numbers are constants like 5 or 6. So I suspect that `setDevice` call always fails unless you have that many GPUs or remapped device IDs.

**Comment by JulienMaille** [comment]
I think you read my code snippet too fast. setDevice takes the target as input because it also handles setting the device for OpenCL or OpenVino backend. I'm not using the enum Target value in place of cuda device integer.

Regarding the bug, don't you think initBackend (and your on-the-fly target correction) is called too late for that?
https://github.com/opencv/opencv/blob/4801526f354057fecde2d70a52c69974aa5ee53f/modules/dnn/src/dnn.cpp#L1498-L1504

**Comment by Jamim** [comment]
_Hello @JulienMaille and @YashasSamaga,_

Would you mind reviewing an alternative fix for this issue?
  - #25880

_Thanks in advance!_

**Comment by JulienMaille** [comment]
@Jamim thanks for the ping. however I must admit I don't understand why you suggest a _build time_ solution for something that happens at _runtime_!?

**Comment by Jamim** [comment]
> @JulienMaille
> why you suggest a _build time_ solution for something that happens at _runtime_!?

That's a good question!

When we set `CUDA_ARCH_BIN` on build time, based on its value, we exactly know if `FP16` is supported or not on the _target_ architecture.
As I understand, there's no reason [to add](https://github.com/opencv/opencv/pull/25880/files#diff-afa733c13dfcdf15a40ac4f53faabe82d1417f8dc312542e6707160259997f68R125) the `DNN_BACKEND_CUDA, DNN_TARGET_CUDA_FP16` pair to the `backends` for `CUDA_ARCH_BIN` < 53, right?

I'm new to OpenCV internals, so if you see any downsides of this approach, please share your thoughts!

_Thanks!_

**Comment by JulienMaille** [comment]
Uh that's right. Thanks for pointing this out. Well I'll look at the commit again and share feedback. However I won't be able to test it, I sold my GTX970 last year
