### ISSUE TITLE
flipHoriz_single() defined in CV_SIMD128  but used in CV_SIMD

### ISSUE THREAD

**Issue by gititgo** [opencv/opencv#21487]
"flipHoriz_single()"  is defined and used in opencv/modules/core/src/matrix_transform.cpp.
It is defined in CV_SIMD128 but used in CV_SIMD. When my  SIMD width is 256, so CV_SIMD is defined but CV_SIMD128 not. 
 "‘flipHoriz_single’ was not declared in this scope" is reported, Is this a bug ?

**Comment by gititgo** [comment]
Can not we just implement  SIMD256 ?   We are supporting  LoongArch SIMD on OpenCV

**Comment by alalek** [comment]
Does `LoongArch SIMD` support some `v_float32x4` type and related operations?

**Comment by gititgo** [comment]
128bit SIMD is supported too, but we thought we could support SIMD256 directly.  
It  means  SIMD128  data type and API  must also be implemented  when  add  SIMD256  supporting ？

**Comment by alalek** [comment]
Currently yes. SIMD256 assumes availability of SIMD128 wrappers.

Alternative doesn't look good: implement both SIMD128 and SIMD256 for this and other cases.

**Comment by vpisarev** [comment]
I think, flipHoriz should be implemented for arbitrary vector length. Probably, we should add another universal intrinsic that flips a vector (v_reverse()?)

**Comment by gititgo** [comment]
> I think, flipHoriz should be implemented for arbitrary vector length.

it's a good way.

**Comment by gititgo** [comment]
> It is defined in CV_SIMD128 but used in CV_SIMD.

When we modify macro control in flipHoriz from CV_SIMD to CV_SIMD128 to ensure flipHoriz_single is used in CV_SIMD128 too, OpenCV  build pass and work well （We only implement SIMD256 data type and api）. So there's only one place where this happens. Maybe it's a bug ?

**Comment by alalek** [comment]
> When we modify macro control in flipHoriz from CV_SIMD to CV_SIMD128

This just disables any SIMD optimizations because you don't provide SIMD128.

---

By current design SIMD256 assumes availability of SIMD128.
There are still many other functions, which is left non-optimized by proposed configuration without SIMD128.

Also,

>  flipHoriz should be implemented for arbitrary vector length.

could not help a lot, globally.

**Comment by gititgo** [comment]
> By current design SIMD256 assumes availability of SIMD128.
OK.  I mean We disabled SIMD128  and only provide SIMD256 and opencv woks well except this place.

**Comment by gititgo** [comment]
v_uint8x16 is used directly in flipHoriz without our SIMD128 support and works well.  Then, I found SIMD128 have C++ implementation called "Universal intrinsics". 
So flipHoriz_single should be defined by CV_SIMD as it is uesed in CV_SIMD.   I have try it and it works well. Right ?

**Comment by gititgo** [comment]
close it
