### ISSUE TITLE
Yolov4 onnx model can not be infered using opencv dnn (Different shapes case is not supported with constant inputs: Mul in function 'parseMul' )

### ISSUE THREAD

**Issue by AyaNasser96** [opencv/opencv#21519]
I've converted yolov4 (custom trained on our dataset) from darknet to onnx using 'darknet2onnx.py' at this repo: https://github.com/Tianxiaomo/pytorch-YOLOv4)  and by using the following environment, at first I used opencv 4.5.1 and I got (softplus opertaor is not supported) and this is solved by using higher version of opencv (4.5.5.62) then another issue appeared as mentioned below:

**Repo**: https://github.com/Tianxiaomo/pytorch-YOLOv4
**Env**:

- onnx= 1.10.2
- opencv-python=4.5.5.62
- onnxruntime=1.10.0
- torch=1.10.1+cpu or the gpu version both get the same results
- numpy= 1.19.5

Those are installed inside a docker image with base:
ubuntu 18.04
cuda 10.2

**Note**: The converted yolov4 is trained from scratch with our custom data 

**Error**:
```

`[ERROR:0@1.745] global /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp (906) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Mul]:(1110) from domain='ai.onnx'
Traceback (most recent call last):
  File "/home/aya/yolo2onnx_sp1/Optimization_project/Optimization/opencv_dnn/main.py", line 137, in <module>
    main()
  File "/home/aya/yolo2onnx_sp1/Optimization_project/Optimization/opencv_dnn/main.py", line 104, in main
    net = cv2.dnn.readNetFromONNX(model_weights)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'handleNode'
> Node [Mul@ai.onnx]:(1110) parse error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1899: error: (-213:The function/feature is not implemented) Different shapes case is not supported with constant inputs: Mul in function 'parseMul'
`
```

![image](https://user-images.githubusercontent.com/98317981/151142760-d5046ef8-0bf9-4350-b869-d3413f284418.png)

**Comment by alalek** [comment]
BTW, There is Darknet importer in OpenCV (and tests for YOLOv4).

> converted yolov4 (custom trained on our dataset) from darknet to onnx

**Comment by AyaNasser96** [comment]
@alalek yeah I know, and I used it with the darkness weights and it worked perfectly but i wanna use the onnx version that I generated to be infered using opencv dnn

**Comment by ReubenThomasJohn** [comment]
I have the same issue. There was a similar Node issue previously, and it went away when I downgraded from Pytorch 1.12 to 1.11. Then this issue pops up.

**Comment by fengyuentau** [comment]
This issue has been solved in the latest OpenCV in https://github.com/opencv/opencv/pull/21865. But the converted model still has other unsupported operators, for example, Where. After simplifying the converted model with onnxsim, the `Where` operator is eliminated but OpenCV still complaints that `parseExpand` does not support the following case:
```
input: float32[1,256,13,1,13,1]
shape: int64[6] [
    1,
    256,
    13,
    2,
    13,
    2
]
```

**Comment by asmorkalov** [comment]
@fengyuentau @AyaNasser96 Is the issue solved?

**Comment by fengyuentau** [comment]
@asmorkalov No, latest opencv still cannot load this model. Issue is the same as I mentioned above.

**Comment by ZJDATY** [comment]
I have the same issue. Did you solve this ?

**Comment by asmorkalov** [comment]
FYI: https://github.com/opencv/opencv/pull/24898

**Comment by alexlyulkov** [comment]
Checked the model with the latest OpenCV 4.x (4.9.0+)  and it worked fine. I used pretrained Yolo4 model from https://github.com/AlexeyAB/darknet and converted it to ONNX using darknet2onnx.py from https://github.com/Tianxiaomo/pytorch-YOLOv4
