### ISSUE TITLE
cv2.error: OpenCV(4.5.4-pre) /home/pi/opencv/modules/core/src/persistence.cpp:682: error: (-5:Bad argument) Input file is invalid in function 'open'

### ISSUE THREAD

**Issue by senba1000m3** [opencv/opencv#21516]
I want to use opencv(cv2) to read the .tflite file but it cannot open.
Is the cv2 can only read .yml file?
How can I read the .tflite file succesfully?
or can I change the tflite to yml?
I can't find the way.
![image](https://user-images.githubusercontent.com/75157697/151100271-f747ade1-8ca5-4066-a7b1-a5740bb0a79f.png)

**Comment by dkurt** [comment]
TFLite is a FlatBuffers file format and requires schema + FlatBuffers dependency. See https://github.com/opencv/opencv/pull/23161.
