### ISSUE TITLE
QRCodeDetector - Seed point is outside of image in function 'cv::floodFill'

### ISSUE THREAD

**Issue by keredra** [opencv/opencv#21532]
##### System information (version)
- OpenCV => Tested with 4.5.5, 4.5.3, 4.4.0, 3.4.15
- Operating System / Platform => Windows 64 Bit / Android 10
- Compiler => Visual Studio 2017/2015

##### Detailed description

QRCodeDetector fails with partial visible QRCode.

floodfill.cpp:509: error: (-211:One of the arguments' values is out of range) Seed point is outside of image in function 'cv::floodFill'

I would rather expect a "not found" than an exception.

##### Steps to reproduce

Run QRCodeDetector with the following image:
![qrcode](https://user-images.githubusercontent.com/13831742/151519783-46b12455-612f-4784-a3b2-d8239d6baa75.jpg)

 Here is a better one to reproduce:
![qrcode2](https://user-images.githubusercontent.com/13831742/151524962-68f12a52-0a88-4d71-ac07-7ec660c63e50.jpg)

**Comment by keredra** [comment]
Seems like its not happening every time.
Running the image in python opencv 4.5.5 will only fail sometimes:
4.5.5
OK
4.5.5
OK
4.5.5
OpenCV(4.5.5) opencv\modules\imgproc\src\floodfill.cpp:509: error: (-211:One of the arguments' values is out of range) Seed point is outside of image in function 'cv::floodFill'

4.5.5
OpenCV(4.5.5) opencv\modules\imgproc\src\floodfill.cpp:509: error: (-211:One of the arguments' values is out of range) Seed point is outside of image in function 'cv::floodFill'

4.5.5
OK
4.5.5
OK

**Comment by tiredDev** [comment]
Can I work on this issue ?

**Comment by asmorkalov** [comment]
Could be reproduced with pre 4.7.0. Stable issue:
```
Traceback (most recent call last):
  File "./qrcode.py", line 249, in <module>
    main()
  File "./qrcode.py", line 242, in main
    qrinst.DetectQRFrmImage(args.input)
  File "./qrcode.py", line 112, in DetectQRFrmImage
    points, decode_info = self.runQR(qrCode, inputimg)
  File "./qrcode.py", line 83, in runQR
    decode_info, points, _ = qrCode.detectAndDecode(inputimg)
cv2.error: OpenCV(4.6.0-dev) /mnt/projects/Projects/OpenCV/opencv-master/modules/core/include/opencv2/core/mat.inl.hpp:715: error: (-215:Assertion failed) y == 0 || (data && dims >= 1 && (unsigned)y < (unsigned)size.p[0]) in function 'ptr'
```

**Comment by Alex20129** [comment]
I've experienced exactly the same problem. 
- OpenCV: 4.7.0-dev
- Operating System: Ubuntu 20.04.5 LTS
- Compiler: GCC 9.4.0

Error message is:
`terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.7.0-dev) /home/alex/opencv/modules/imgproc/src/floodfill.cpp:522: error: (-211:One of the arguments' values is out of range) Seed point is outside of image in function 'floodFill'`

My code causing the error:
```
for(wX=0; wX<image->cols-window_size; wX+=step)
{
	for(wY=0; wY<image->rows-window_size; wY+=step)
	{
		*gSlidingWindow=(*image)(Range(wY, wY+window_size), Range(wX, wX+window_size));
		imwrite(string("./debug/")+to_string(g_frame_id)+string("_")+to_string(windowPosition)+string(".png"), *gSlidingWindow, img_compression_params);
		windowPosition++;
		if(detector->detect(*gSlidingWindow, regionPoints))
		{
			qr_code_content=detector->detectAndDecode(*gSlidingWindow);
			if(!qr_code_content.empty())
			{
				if(0==qr_code_content.compare(qr_code_content_last_time))
				{
					fprintf(stdout, "%s\n", qr_code_content.data());
					imwrite(string("./detected_codes/")+to_string(g_frame_id)+string("_")+qr_code_content+string(".png"), *gSlidingWindow, img_compression_params);
					return(1);
				}
				else
				{
					qr_code_content_last_time=qr_code_content;
				}
			}
		}
	}
}
```
Whats interesting is that
```if(detector->detect(*gSlidingWindow, regionPoints))```
actually works, but next
```qr_code_content=detector->detectAndDecode(*gSlidingWindow);```
Throwing an error. In my case it was false-positive "detect", so image in the window didn't content any QR codes. I can post the image if that's necessary.
