### ISSUE TITLE
Warning: libmediandk.so, needed by ../../lib/arm64-v8a/libopencv_videoio.so, not found (try using -rpath or -rpath-link)

### ISSUE THREAD

**Issue by ashwinjoseph95** [opencv/opencv#21556]
Hi I was trying to cross compile opencv for android. My NDK version is 19 and API Level is 28. The make is crashing stating warning: libmediandk.so, was not found. Any guidance on rectifying the issue will be useful.
![image](https://user-images.githubusercontent.com/30999857/152175139-b8b51355-c72a-4330-ad6d-b7f1bea008ca.png)

I used the instructions here for the same: https://www.sisik.eu/blog/android/ndk/opencv-without-java 

The cmake command I used is: `cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/ubuntu/android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/ubuntu/android/android-ndk-r19c -DANDROID_NATIVE_API_LEVEL=android-28 -DBUILD_JAVA=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_ANDROID_PROJECTS=OFF -DANDROID_STL=c++_shared -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=/home/ubuntu/opencv/android_build/out -DANDROID_ABI=arm64-v8a -DCMAKE_CXX_FLAGS="-llog"
`

**Comment by alalek** [comment]
Please check value of `ANDROID_NATIVE_API_LEVEL` in CMakeCache.txt / CMakeVars.txt

https://developer.android.com/ndk/reference/group/media

> Available since API level 21.

---

Avoid posting text information through screenshots - it is ridiculous and blocks searching of similar issues.

**Comment by ashwinjoseph95** [comment]
Thanks for the reply. I did check those. The ANDROID_NATIVE_API_LEVEL  is set as 28 in my case which is supported. Any guidance on solving the issue would be appreciated. Thank you.

**Comment by alalek** [comment]
There are several options which are necessary to be properly specified.

We support these scripts only: https://github.com/opencv/opencv/tree/4.x/platforms/android
Try with config: `ndk-18-api-level-21.config.py` (with NDK 19c should work too)

---

> cmake ..

Avoid building in the source tree. Source and build directory should not intersect.

**Comment by ashwinjoseph95** [comment]
Upon trying with NDK 21, and few more change in flags, I have been able to generate the relevant shared library files. Thanks for the guidance.
