### ISSUE TITLE
OpenCv dnn low fps than darknet

### ISSUE THREAD

**Issue by YashGugliya** [opencv/opencv#21610]
```
import cv2
import time

CONFIDENCE_THRESHOLD = 0.2
NMS_THRESHOLD = 0.4
COLORS = [(0, 255, 255), (255, 255, 0), (0, 255, 0), (255, 0, 0)]

class_names = []
with open("C:/Users/yashg/Desktop/Yolo/classes.txt", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

vc = cv2.VideoCapture("testing.mp4")

net = cv2.dnn.readNet("C:/Users/yashg/Desktop/Yolo/darknet-master/cfg/yolov4-custom.cfg", "C:/Users/yashg/Desktop/Yolo/training/yolov4-custom_best.weights")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA_FP16)

model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(416, 416), scale=1 / 255, swapRB=True)

while cv2.waitKey(1) < 1:
    (grabbed, frame) = vc.read()
    if not grabbed:
        exit()

    classes, scores, boxes = model.detect(frame, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)

    for (classid, score, box) in zip(classes, scores, boxes):
        color = COLORS[int(classid) % len(COLORS)]
        label = "%s : %f" % (class_names[classid[0]], score)
        cv2.rectangle(frame, box, color, 2)
        cv2.putText(frame, label, (box[0], box[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    cv2.imshow("detections", frame)
```
This is the code i m trying to run but i m getting low fps than while using darknet directly 
I have Cuda 11.6 and cudnn 8.3 
My gpu is 1650ti
opencv-python-4.5.3.56

**Comment by YashasSamaga** [comment]
How did you measure FPS?

**Comment by YashGugliya** [comment]
```
import cv2
import time

CONFIDENCE_THRESHOLD = 0.2
NMS_THRESHOLD = 0.4
COLORS = [(0, 255, 255), (255, 255, 0), (0, 255, 0), (255, 0, 0)]

class_names = []
with open("classes.txt", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

vc = cv2.VideoCapture("demo.mp4")

net = cv2.dnn.readNet("yolov4.weights", "yolov4.cfg")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA_FP16)

model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(416, 416), scale=1/255, swapRB=True)

while cv2.waitKey(1) < 1:
    (grabbed, frame) = vc.read()
    if not grabbed:
        exit()

    start = time.time()
    classes, scores, boxes = model.detect(frame, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)
    end = time.time()

    start_drawing = time.time()
    for (classid, score, box) in zip(classes, scores, boxes):
        color = COLORS[int(classid) % len(COLORS)]
        label = "%s : %f" % (class_names[classid[0]], score)
        cv2.rectangle(frame, box, color, 2)
        cv2.putText(frame, label, (box[0], box[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
    end_drawing = time.time()
    
    fps_label = "FPS: %.2f (excluding drawing time of %.2fms)" % (1 / (end - start), (end_drawing - start_drawing) * 1000)
    cv2.putText(frame, fps_label, (0, 25), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
    cv2.imshow("detections", frame)
```
I used this 
Maybe this is your code.

**Comment by YashGugliya** [comment]
> How did you measure FPS?
> 
> Please report what FPS you get with this script: https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49

I used your code only 
I m getting 4 to 5 fps

**Comment by YashasSamaga** [comment]
What do you get with `DNN_TARGET_CUDA` instead of `DNN_TARGET_CUDA_FP16`?

**Comment by YashGugliya** [comment]
> What do you get with `DNN_TARGET_CUDA` instead of `DNN_TARGET_CUDA_FP16`?

I m getting the same result.

**Comment by YashasSamaga** [comment]
Please share the output of `cv2.getBuildInformation()`.

Please set `OPENCV_LOG_LEVEL` environment variable to `INFO` and run again. I suspect your OpenCV installation is not built with CUDA support.

```
export OPENCV_LOG_LEVEL=INFO
```

There will be a message that will inform that the network switched to the CPU backend.

**Comment by YashGugliya** [comment]
Can you suggest me a Youtube video to build opencv cuda on windows

**Comment by YashGugliya** [comment]
I have build opencv with cuda support how can i use it in my python code

**Comment by YashGugliya** [comment]
> https://jamesbowley.co.uk/accelerate-opencv-4-5-0-on-windows-build-with-cuda-and-python-bindings/

I have build opencv with cuda support how can i use it in my python code

**Comment by YashasSamaga** [comment]
The code you're using will use the CUDA backend if available. Please check if you're using the correct version of OpenCV installation. Sometimes it happens that users have multiple installations and the one they just built isn't the one that their program is actually using.

> Please share the output of cv2.getBuildInformation().
> 
> Please set OPENCV_LOG_LEVEL environment variable to INFO and run again. I suspect your OpenCV installation is not built with CUDA support.
> 
> export OPENCV_LOG_LEVEL=INFO
> 
> There will be a message that will inform that the network switched to the CPU backend.

---

The issue now appears to be a question on building/usage more than a bug. Please use the Q&A forum for such questions: https://forum.opencv.org/

**Comment by YashGugliya** [comment]
> The code you're using will use the CUDA backend if available. Please check if you're using the correct version of OpenCV installation. Sometimes it happens that users have multiple installations and the one they just built isn't the one that their program is actually using. A previous comment in this thread gives an idea on how to test:
> 
> > Please share the output of cv2.getBuildInformation().
> > Please set OPENCV_LOG_LEVEL environment variable to INFO and run again. I suspect your OpenCV installation is not built with CUDA support.
> > export OPENCV_LOG_LEVEL=INFO
> > There will be a message that will inform that the network switched to the CPU backend.
> 
> The issue now appears to be a question on building/usage more than a bug. Please use the Q&A forum for such questions: https://forum.opencv.org/

I have build opencv with cuda But pycharm is not able to find the build 
How should i set up the paths?

**Comment by YashGugliya** [comment]
> The code you're using will use the CUDA backend if available. Please check if you're using the correct version of OpenCV installation. Sometimes it happens that users have multiple installations and the one they just built isn't the one that their program is actually using. A previous comment in this thread gives an idea on how to test:
> 
> > Please share the output of cv2.getBuildInformation().
> > Please set OPENCV_LOG_LEVEL environment variable to INFO and run again. I suspect your OpenCV installation is not built with CUDA support.
> > export OPENCV_LOG_LEVEL=INFO
> > There will be a message that will inform that the network switched to the CPU backend.
> 
> The issue now appears to be a question on building/usage more than a bug. Please use the Q&A forum for such questions: https://forum.opencv.org/

Sir
 
label = "%s : %f" % (class_names[classid[0]], score)
IndexError: invalid index to scalar variable.

This is the error I m getting
