### ISSUE TITLE
The onnx model exported by PaddlePaddle can not be loaded by opencv

### ISSUE THREAD

**Issue by JimXu1989** [opencv/opencv#21624]
Hi, the onnx model exported by PaddlePaddle can be loaded by onnx, but can not be loaded by opencv.
I use PaddleX to train the model. use paddle2onnx to export the model
[Uploading zazhi.zip…]()

**Comment by HuaiguangLiu** [comment]
your problem have been solved? i also have the same problem.
[https://github.com/PaddlePaddle/PaddleDetection/issues/7315](url)

**Comment by dkurt** [comment]
Please attack a model to reproduce it.
