### ISSUE TITLE
typo in 4.5.5 release dynamic library link naming ? lib*.405.dylib instead of lib*.4.5.dylib

### ISSUE THREAD

**Issue by avkunapuli** [opencv/opencv#21670]
Hi,
After upgrading to 4.5.5 opencv, my build with 4.5.4 dynamic libraries is giving errors.
otool shows my binary is linked to libopencv.4.5.dylib, which explains the error.

I compared the two versions 4.5.4 and 4.5.5 opencv libraries, symlinks ..etc.

and observed all the dynamic libraries are lib*.405.dylib, is this a typo ?
are they supposed to be lib*.4.5.dylib ? for any of the 4.5.x releases ?

If so, please let me know if it is possible to address this issue and update release 4.5.5.

System I am using is a Mac, with OS BugSur.

Thanks,
Subbu

for example one of the libraries is libopencv_gapi*

( system with OpenCV 4.5.4 was installed ):
--------------------------------------------
admin   4248344 Feb 15 17:31 /usr/local/opt/opencv/lib/libopencv_gapi.4.5.4.dylib
admin        26 Oct  9 08:48 /usr/local/opt/opencv/lib/libopencv_gapi.4.5.dylib -> libopencv_gapi.4.5.4.dylib
admin  11226464 Oct  9 08:48 /usr/local/opt/opencv/lib/libopencv_gapi.a
admin        24 Oct  9 08:48 /usr/local/opt/opencv/lib/libopencv_gapi.dylib -> libopencv_gapi.4.5.dylib

(system with OpenCV 4.5.5 was installed ):
------------------------------------------
admin   4414376 Feb 28 15:51 libopencv_gapi.4.5.5.dylib
admin        26 Dec 24 19:53 libopencv_gapi.405.dylib -> libopencv_gapi.4.5.5.dylib
admin  11492992 Dec 24 19:53 libopencv_gapi.a
admin        24 Dec 24 19:53 libopencv_gapi.dylib -> libopencv_gapi.405.dylib

**Comment by mshabunin** [comment]
It works this way now, see https://github.com/opencv/opencv/pull/21178 for details.
