### ISSUE TITLE
OpenCV 4.5.5 not building with OpenVINO-Toolkit 2021.4.2

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#21680]
##### System information (version)

- OpenCV => 4.5.5-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
I am trying to build OpenCV with Inference-Engine support, but what I experienced is:

- Here in CMake GUI, I cannot find the **WITH_INF_ENGINE** flag as before there was this flag, but in the latest source which I downloaded there is no this flag. But I found another flag which is: **WITH_OPENVINO**, I don't know if this is a replacement for the **WITH_INF_ENGINE** flag, anyway.
- When I use the flag **WITH_OPENVINO**, then it shows: `OpenVINO_DIR-NOTFOUND `as well as` InferenceEngine_DIR-NOTFOUND`, but I have tried to direct this path to the following paths, but no one was working:

1. C:\Program Files (x86)\Intel\openvino_2021\inference_engine
2. C:\Program Files (x86)\Intel\openvino_2021
3. C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\inference_engine

So now what should I do to solve this problem?

**NOTE:** I have installed OpenVINO-Toolkit as it was instructed on the official page, and also I am not new with OpenCV and OpenVINO before it was built successfully, but in new releases, it does not.

**Comment by alalek** [comment]
1. `WITH_OPENVINO` option should be used (old options works, but they are "hidden" - could be specified from command line only).
2. Legacy variables with include/libs path are not supported anymore.
3. Use OpenVINO's `setupvars.bat` **BEFORE** calling of cmake-gui (from the same terminal). Solution should be opened from the same terminal also (e.g., "start opencv.sln")
4. Alternative to 3 is specifying `InferenceEngine_DIR` (for OpenVINO 2021.4.x) as CMake variable or environment variable. But this may lead to runtime errors as PATH should be configured properly to specify OpenVINO DLL's.

---

Open "cmd.exe" and run these commands in terminal
- `call "C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat"`
- `cmake -G "Visual Studio 16 2019" -A x64 ../dev -DWITH_OPENVINO=ON`
- `start opencv.sln` or `cmake --build . ...`

---

BTW, OpenVINO's setupvars configures this path:

```
>set Inf
InferenceEngine_DIR=C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\inference_engine\share
```

(**Note**: path would be changed with major OpenVINO 2022.1 new release, so consider using `setupvars.cmd`)

**Comment by Bahramudin** [comment]
@alalek Thank you so much for your description!! Thr problem solved.

**Comment by TechnikEmpire** [comment]
This still breaks if you disable `BUILD_SHARED_LIBS` FYI.
