### ISSUE TITLE
CAP_PROP_POS_MSEC to frame_number

### ISSUE THREAD

**Issue by ritvikagrawal1** [opencv/opencv#21693]
Hi !
I'm given some timestamps for a video.
I want to do in place changes to a frame on that particular timestamp of a video.
How can I achieve that?

For reading the frame at a given timestamp :
```
V = cv2.VideoCapture(videoFile)
V.set(cv2.CAP_PROP_POS_MSEC, row['frame_timestamp'] * 1e3)
_, frame = V.read()
```

How to write at a particular timestamp?

**Comment by asmorkalov** [comment]
It's not possible. You need to encode full video again.
