### ISSUE TITLE
Memory leak when using VideoCapture with FFmpeg backend and hardware acceleration

### ISSUE THREAD

**Issue by ts-accessio** [opencv/opencv#21696]
There is a memory leak in VideoCapture with FFmpeg backend when hardware acceleration is enabled. It's about 30-50MB per hour when processing a video stream with 25 fps.

After some testing we could eliminate the memory leak by replacing the `av_frame_unref` function with `av_frame_free` at [cap_ffmpeg_impl.hpp#L1522](https://github.com/opencv/opencv/blob/901e0ddfe467b24f85c90340a545df5ef180e440/modules/videoio/src/cap_ffmpeg_impl.hpp#L1522). 
We don't know why `av_frame_unref` was used in the first place, so we don't know if using `av_frame_free` has some unintended side effects.

##### System information (version)
- OpenCV => 4.5.4
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc

**Comment by alalek** [comment]
Thank you for the report!
Right, this call should be replaced.

> AVFrame must be allocated using av_frame_alloc(). Note that this only
> allocates the AVFrame itself, the buffers for the data must be managed
> through other means (see below).
> AVFrame must be freed with av_frame_free().

https://github.com/FFmpeg/FFmpeg/blob/n4.4.1/libavutil/frame.h#L294


```
/**
 * Unreference all the buffers referenced by frame and reset the frame fields.
 */
void av_frame_unref(AVFrame *frame);
```

vs 

```
/**
 * Free the frame and any dynamically allocated objects in it,
 * e.g. extended_data. If the frame is reference counted, it will be
 * unreferenced first.
 *
 * @param frame frame to be freed. The pointer will be set to NULL.
 */
void av_frame_free(AVFrame **frame);
```

`av_frame_free()` [calls](https://github.com/FFmpeg/FFmpeg/blob/n4.4.1/libavutil/frame.c#L208) `av_frame_unref()` internally.

---

relates #19460

**Comment by luisrr1590** [comment]
this issue has been bothering me for months.....so good to finnally know what the problem was.....thanks all
