### ISSUE TITLE
Building OpenCV on Windows with VS, OpenGL, GStreamer: Missing libraries in project files

### ISSUE THREAD

**Issue by tthurow** [opencv/opencv#21709]
##### System information (version)
- OpenCV => 4.5.5
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

modul opencv_videoio: there is to add gstaudio-1.0.lib (GStreamer audio) to the linked libraries, linker missing symbols from this

modul opencv_highgui: there is to add opengl32.lib (OpenGL on Windows) to the linked libraries, linker missing symbols from this

##### Steps to reproduce

Create OpenCV 4.5.5 Visual Project Files per CMAKE with OpenGL and GStreamer support, build library

**Comment by alalek** [comment]
You need to build from 4.x branch.
These issues were already reported and fixed.

Don't ignore the issues template:

>  - [ ] I updated to the latest OpenCV version and the issue is still there

**Comment by tthurow** [comment]
I don't understand, there is the branch "Branch_4.4.0" (not 4.5) and the branch "remotes/origin/4.x". 
I choose the TAG(!!!) 4.5.5. What did you mean? Tag or branch? Normaly the tag is the right choose after roll out ...

**Comment by alalek** [comment]
Tags are only for releases.
Until there is no release with bugfixes we need to use branch.
