### ISSUE TITLE
build opencv for ios in mac

### ISSUE THREAD

**Issue by duany049** [opencv/opencv#21734]
Environment:
- OpenCV => 4.x
- Operating System / Platform => mac monterey(12.3)
- Compiler => xcode 13.3
- python 3.8.9

Fllowing the document, when execute command "python opencv/platform/ios/build_framework.py build_ios", error occur!!

Error log:

CompileC /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/Objects-normal/armv7/tokenizer.o /Users/xuhx3/lenovo/opencv_env/opencv/3rdparty/protobuf/src/google/protobuf/io/tokenizer.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'libprotobuf' from project 'OpenCV')

    cd /Users/xuhx3/lenovo/opencv_env/opencv

    export LANG\=en_US.US-ASCII

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target armv7-apple-ios8.0 -fmessage-length\=307 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR\=\"Release-iphoneos\" -DHAVE_PTHREAD\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -fembed-bitcode -I/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/lib/Release/include -isystem /Users/xuhx3/lenovo/opencv_env/opencv/3rdparty/protobuf/src -isystem /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos -I/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/DerivedSources-normal/armv7 -I/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/DerivedSources/armv7 -I/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/DerivedSources -F/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/lib/Release -fembed-bitcode -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wstrict-prototypes -Winit-self -Wpointer-arith -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fvisibility\=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-sign-compare -Wno-sign-promo -Wno-undef -Wno-tautological-undefined-compare -Wno-ignored-qualifiers -Wno-extra -Wno-unused-function -Wno-unused-const-variable -Wno-shorten-64-to-32 -Wno-invalid-offsetof -Wno-enum-compare-switch -Wno-suggest-override -Wno-inconsistent-missing-override -Wno-implicit-fallthrough -Wno-array-bounds -DNDEBUG -DNDEBUG -fPIC -std\=c++11 -MMD -MT dependencies -MF /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/Objects-normal/armv7/tokenizer.d --serialize-diagnostics /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/Objects-normal/armv7/tokenizer.dia -c /Users/xuhx3/lenovo/opencv_env/opencv/3rdparty/protobuf/src/google/protobuf/io/tokenizer.cc -o /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/Objects-normal/armv7/tokenizer.o

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/3rdparty/protobuf/OpenCV.build/Release-iphoneos/libprotobuf.build/Objects-normal/armv7/tokenizer.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'libprotobuf' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'ade' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'libjpeg-turbo' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'libpng' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'opencv_objc' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'gen_opencv_objc_source' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'ALL_BUILD' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'opencv_world' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'zlib' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'quirc' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'gen_opencv_objc_source_ios' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'ZERO_CHECK' from project 'OpenCV')

/Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/OpenCV.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'libprotobuf' from project 'OpenCV')

** BUILD FAILED **

The following build commands failed:

    PhaseScriptExecution Generate\ CMakeFiles/dephelper/gen_opencv_objc_source_ios /Users/xuhx3/lenovo/opencv_env/build_ios/build/build-armv7-iphoneos/modules/objc_bindings_generator/OpenCV.build/Release-iphoneos/gen_opencv_objc_source_ios.build/Script-624AC68AC6F221E65CFC8166.sh (in target 'gen_opencv_objc_source_ios' from project 'OpenCV')

(1 failure)

============================================================

ERROR: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '8', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.

============================================================

Traceback (most recent call last):

  File "opencv/platforms/ios/build_framework.py", line 181, in build

    self._build(outdir)

  File "opencv/platforms/ios/build_framework.py", line 139, in _build

    self.buildOne(target[0], target[1], main_build_dir, cmake_flags)

  File "opencv/platforms/ios/build_framework.py", line 318, in buildOne

    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)

  File "/Users/xuhx3/lenovo/opencv_env/opencv/platforms/apple/cv_build_utils.py", line 13, in execute

    retcode = check_call(cmd, cwd = cwd)

  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '8', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.

**Comment by williamliangwl** [comment]
Having the same issue with the same environment. Do you manage to find out the solution @duany049 @alalek ?

**Comment by GithubXkw1573** [comment]
have the same problem with you, did you get out?

**Comment by duany049** [comment]
> I solve this problem by setting python environment variables

**Comment by duany049** [comment]
> have the same problem with you, did you get out?
I solve this problem by setting python environment variables

**Comment by GithubXkw1573** [comment]
python3? or python?, i set PATH=PATH:/usr/bin/python3, not work

**Comment by duany049** [comment]
> 
Pip used in the script, so you should connect python and python3 with soft connection, and set the PATH of python and python3

**Comment by GithubXkw1573** [comment]
can you show me soft connection to where?

**Comment by duany049** [comment]
> 
could you use python command directly? 
I couln't use it at that time, so I use soft connection

**Comment by GithubXkw1573** [comment]
![image](https://user-images.githubusercontent.com/6871338/165014729-2a53d21b-1ed3-433d-a283-a08337d2babc.png)

**Comment by GithubXkw1573** [comment]
I can use python command directly
but , run "python opencv/platforms/ios/build_framework.py ios"
got this issue

**Comment by GithubXkw1573** [comment]
The following build commands failed:
	PhaseScriptExecution Generate\ CMakeFiles/dephelper/gen_opencv_objc_source_ios /Users/xukaiwei/Documents/work/kevin/opencv_build/ios/build/build-armv7-iphoneos/modules/objc_bindings_generator/OpenCV.build/Release-iphoneos/gen_opencv_objc_source_ios.build/Script-42C004774E5EE287ACC51046.sh (in target 'gen_opencv_objc_source_ios' from project 'OpenCV')
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.
============================================================
Traceback (most recent call last):
  File "/Users/xukaiwei/Documents/work/kevin/opencv_build/opencv/platforms/ios/build_framework.py", line 181, in build
    self._build(outdir)
  File "/Users/xukaiwei/Documents/work/kevin/opencv_build/opencv/platforms/ios/build_framework.py", line 139, in _build
    self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
  File "/Users/xukaiwei/Documents/work/kevin/opencv_build/opencv/platforms/ios/build_framework.py", line 318, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "/Users/xukaiwei/Documents/work/kevin/opencv_build/opencv/platforms/apple/cv_build_utils.py", line 13, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.

**Comment by duany049** [comment]
This mistake is different from the one I have come across. I suggest you locate the number of error lines in Script-42C004774E5EE287ACC51046.sh, and address them accordingly. Best wishes to you!

**Comment by GithubXkw1573** [comment]
OK，anyway, thanks a lot. 
I will leave message here, if i solved the question.

**Comment by GithubXkw1573** [comment]
I resolved , maybe python3 is unsupported in my mac M1, I installed python2.7 then works.
