### ISSUE TITLE
cv::dnn::DNN_BACKEND_CUDA is not supporting error.

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#21742]
- OpenCV => 4.5.5
- Operating System / Platform => Windows 64 Bit
- Compiler =>Visual Studio 2019

##### Detailed description
I have built OpenCV with CUDA enabled successfully, and works well, but when I am using CUDA with DNN model, it throws the following error:

> the error: OpenCV(4.5.5-dev) D:\opencv\opencv\modules\dnn\src\dnn.cpp:3266: error: (-213:The function/feature is not implemented) Layer "detection_out" of type "" unsupported on OpenCV backend in function 'cv::dnn::dnn4_v20211220::Net::Impl::forwardLayer'

Code:

```
cv::dnn::Net net = cv::dnn::Net::readFromModelOptimizer(xml, bin);
// OR
//cv::dnn::Net net = cv::dnn::readNet(bin, xml);

// This is working
//net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
//net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);
// This is not working
net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
```

**Comment by alalek** [comment]
> readFromModelOptimizer

works with DNN_BACKEND_INFERENCE_ENGINE backend only.

This is expected behavior by design.

---

Emitting an error on setPreferableBackend() call will be added later.

**Comment by TUT-jiayou** [comment]
# my env
* opencv 4.6.0 
* os : ubuntu 18.04
* gcc 7.5.0
# error
* I can not use DNN_BACKEND_CUDA in `dnn::readNet`
