### ISSUE TITLE
  OpenCV: Include directory doesn't exist:   '/usr/local/stow/absl/include/opencv4'.  OpenCV installation may be broken.

### ISSUE THREAD

**Issue by mhzhou2021** [opencv/opencv#21778]
System information (version)
    OpenCV 4.5.5
    Operating System  Linux Ubuntu 20.04 

cmake&make&install:
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local  -D OPENCV_EXTRA_MODULES_PATH=/home/algo/software/opencv/opencv_contrib_4.5.5/modules -D WITH_EIGEN=ON -D WITH_QT=ON -D OPENCV_ENABLE_NONFREE=ON -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D PYTHON3_PACKAGES_PATH=/usr/lib/python3/dist-packages -D OPENCV_GENERATE_PKGCONFIG=ON -D BUILD_EXAMPLES=OFF ..
make -j8
sudo make install

algo@algo:~/software/opencv/opencv_4.5.5/samples/cpp/example_cmake/build$ pkg-config --modversion opencv4
4.5.5
algo@algo:~/software/opencv/opencv_4.5.5/samples/cpp/example_cmake/build$ pkg-config --libs opencv4
-L/usr/local/lib -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core

CMakelist.txt:
cmake_minimum_required(VERSION 3.5)
project(opencv_helloworld LANGUAGES CXX)
FIND_PACKAGE(OpenCV REQUIRED)
INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})

find_package( OpenCV REQUIRED )
add_executable(opencv_helloworld
  main.cpp
)
target_link_libraries(opencv_helloworld ${OpenCV_LIBS})

ERROR:
CMake Warning at /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:116 (message):
  OpenCV: Include directory doesn't exist:
  '/usr/local/stow/absl/include/opencv4'.  OpenCV installation may be broken.
  Skip...
Call Stack (most recent call first):
  CMakeLists.txt:5 (FIND_PACKAGE)

**Comment by mhzhou2021** [comment]
in /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake row 79
get_filename_component(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_DIR}" REALPATH) ->
get_filename_component(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)

**Comment by romirk** [comment]
hi, this worked for me, thanks. can you help me understand why this fixes the problem?
