### ISSUE TITLE
Building opencv.js

### ISSUE THREAD

**Issue by sfornengo** [opencv/opencv#21776]
From:
`git clone https://github.com/opencv/opencv.git`

When I build with:
` python3 ./opencv/platforms/js/build_js.py ./build_wasm --build_wasm`

It generates opencv.js but I must replace in the latest lines:
```
  return cv.ready
}
```
by:
```
  return cv
}
```
to use it. What is wrong ?

**Comment by kalwalt** [comment]
> From: `git clone https://github.com/opencv/opencv.git`
> 
> When I build with: ` python3 ./opencv/platforms/js/build_js.py ./build_wasm --build_wasm`
> 
> It generates opencv.js but I must replace in the latest lines:
> 
> ```
>   return cv.ready
> }
> ```
> 
> by:
> 
> ```
>   return cv
> }
> ```
> 
> to use it. What is wrong ?

I can confirm this i build opencv.js with `python ./opencv/platforms/js/build_js.py build_js`  emcc 3.1.7 opencv latest and i had to do that change.

**Comment by kalwalt** [comment]
For anyone have this issue read this [comment](https://github.com/opencv/opencv/issues/21580#issuecomment-1048514882)
