### ISSUE TITLE
Connected component labelling bug 

### ISSUE THREAD

**Issue by JeanLucLeCalvez** [opencv/opencv#21783]
##### System information (version)
- OpenCV => 4.x
- 
##### Detailed description

Analyzing the code for connected component labelling, to understand the Grana method, I think I have found an issue in one of the condition defined to to check if the pixels are foreground, without going outside the image limits:

The extract from the cpp code is 
                    #define condition_b c-1>=0 && r-2>=0 && img_row_prev_prev[c-1]>0
                    #define condition_c r-2>=0 && img_row_prev_prev[c]>0
                    #define condition_d c+1<w&& r-2>=0 && img_row_prev_prev[c+1]>0
                    #define condition_e c+2<w  && r-1>=0 && img_row_prev[c-1]>0

but condition_e should be
                   #define condition_e c+2<w  && r-1>=0 && img_row_prev_prev[c+2]>0

as pixel e is 2 rows above and 2 columns right of analyzed pixel o

**Comment by alalek** [comment]
Looks like this line from git history is correct, right? https://github.com/opencv/opencv/blame/5b23c0b176206d4ee7efc43f454fcd7f4f0419f1/modules/imgproc/src/connectedcomponents.cpp#L2646

It was modified by PR #8789 here:

https://github.com/opencv/opencv/commit/4b7fc5933297e27aadef357e8c27fe6ecc0699d7#diff-5135a481e57d01fd61703ebb0fe07762ef8b0a5b656c3760171d144f2f28f1f2R2647


/cc @vpisarev @MicheleCancilla

**Comment by yash112-lang** [comment]
Hey @alalek , is this issue is still open, can I work on it?

**Comment by MicheleCancilla** [comment]
Yes, that's definitely wrong! The condition should be `#define condition_e c+2<w && r-2>=0 && img_row_prev_prev[c+2]>0`.
The parallel version https://github.com/opencv/opencv/blob/aebb65e98387a3edf23a2e164449da5bc609e042/modules/imgproc/src/connectedcomponents.cpp#L2587 is instead correct.

Reference code for non-parallel BBDT (Grana2010):
https://github.com/prittt/YACCLAB/blob/b3cdb19d543b2199c4f2f217bcc7dad08ce4ce14/include/labeling_grana_2010.h#L554

**Comment by alalek** [comment]
@yash112-lang Sure! Feel free to prepare PR for 3.4 target branch
