### ISSUE TITLE
videocapture hardware acceleration seem not working

### ISSUE THREAD

**Issue by lchunleo** [opencv/opencv#21806]
Hi 

 Am using ubuntu and trying to use the hardware acceleration in my python code of Video Capture. i had compiled a opencv 4.5.4 ensuring cuda is on. 

  cap = cv2.VideoCapture(<rtsp address>, cv2.CAP_FFMPEG,(cv2.CAP_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY ))

 However, when i do a nvidia-smi dmon command, i noted that the nvdec is not processing anything. it works well for command line e.g. ffmpeg -hwaccel  ....

  May i check is there any working example that i can refer to  in ubuntu environment? Thank you

**Comment by alalek** [comment]
CUDA is not validated and may not work through VideoCapture/FFmpeg.

To dump debug information use these environment variables:
- `OPENCV_FFMPEG_DEBUG=1`
- `OPENCV_LOG_LEVEL=DEBUG`

---

There is dedicated CUDA Video I/O interface. Look for `cv.cudacodec.createVideoReader` from "opencv_contrib" repository.

**Comment by wqh17101** [comment]
@alalek But `cv.cudacodec.createVideoReader` only return a gpu_mat and also some error occured as https://github.com/opencv/opencv_contrib/issues/3225

**Comment by asmorkalov** [comment]
The related issue in opencv_contrib has been resolved.
