### ISSUE TITLE
Python bindings for VideoCapture::waitAny

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#21826]
related: https://github.com/opencv/opencv/pull/15100

Everything in `VideoCapture` has Python bindings except for the new `waitAny` facility. I think that would be generally useful to have in Python too.

if the bindings generation doesn't imply a regular signature, I'd propose

```python
waitAny(streams, timeoutNs=0) -> readyIndex
```
Where `streams` is a list of VideoCapture instances and `readyIndex` is a python _list_ of indices into `streams`. No need to preserve the boolean return value. It's only false if the list is empty.

NB: Docs are inconsistent in their naming. Single mention of "streamReady". "readyIndex" was probably intended. It's not a singular value either ("index"), it's a vector/list (indices).

**Comment by LeoI5** [comment]
Please explain how to use waitAny in Python.
What is the streams in params?
May I ask to show exaple of Python code for one rtsp stream?

**Comment by crackwitz** [comment]
```none
>>> help(_)
Help on built-in function waitAny:

waitAny(...)
    waitAny(streams[, timeoutNs]) -> retval, readyIndex
    .   @brief Wait for ready frames from VideoCapture.
    .
    .       @param streams input video streams
    .       @param readyIndex stream indexes with grabbed frames (ready to use .retrieve() to fetch actual frame)
    .       @param timeoutNs number of nanoseconds (0 - infinite)
    .       @return `true` if streamReady is not empty
    .
    .       @throws Exception %Exception on stream errors (check .isOpened() to filter out malformed streams) or VideoCapture type is not supported
    .
    .       The primary use of the function is in multi-camera environments.
    .       The method fills the ready state vector, grabs video frame, if camera is ready.
    .
    .       After this call use VideoCapture::retrieve() to decode and fetch frame data.
```

from looking at the patch, looks like it should work like this:

```python
streams = [cv.VideoCapture(...), cv.VideoCapture(...), ...]

while True:
    rv, ready = cv.VideoCapture.waitAny(streams, timeoutNs=1e9)
    if not rv:
        continue # none were ready

    print("reading from", ready) # it's a list/tuple, indices into `streams` list

    for index in ready:
        stream = streams[index]
        (rv, frame) = stream.read()
        ....
```

**Comment by LeoI5** [comment]
Christoph,
many thanks for example. Python code is fine.
But it returned error:
cv2.error: OpenCV(4.7.0) /home/buildozer/aports/community/opencv/src/opencv-4.7.0/modules/videoio/src/cap.cpp:471: error: (-213:The function/feature is not implemented) VideoCapture::waitAny() is supported by V4L backend only in function 'waitAny'

So is waitAny() is not suittable for rtsp stream?

**Comment by asmorkalov** [comment]
No waitAny works for V4L backend only.
