### ISSUE TITLE
msys2: Changes in opencv4.pc cause linker error in OpenCV 4.5.5 when using pkg-config

### ISSUE THREAD

**Issue by asmwarrior** [opencv/opencv#21825]
Hi, I have reported this issue to msys2's package site: [OpenCV's pkgconfig file changes cause linker error in latest OpenCV 4.5.5 version · Issue #11208 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/11208#issuecomment-1088936309)

For a reference, I reported this issue here.

The reason is I use `pkg-config --libs opencv4` to generate the linker option for msys2's mingw gcc.

For the opencv4.pc in OpenCV 4.5.5, it has the option:
`-llibopencv_gapi.dll`, while for the old version of OpenCV, it has `-lopencv_gapi`.

Those format changes cause the issue.

I got the error like:
~~~~
F:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibopencv_gapi.dll: No such file or directory
F:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: note to link with F:\msys2\mingw64\lib\libopencv_gapi.dll.a use -l:libopencv_gapi.dll.a or rename it to liblibopencv_gapi.dll.a
~~~~

While I don't have linker error when using the old OpenCV version. So  `-lopencv_gapi` this kind of option is OK.

**Comment by Biswa96** [comment]
This is msys2 specific packaging issue and not actionable by upstream.

**Comment by asmwarrior** [comment]
This issue is fixed in the msys2, see:

[OpenCV's pkgconfig file changes cause linker error in latest OpenCV 4.5.5 version · Issue #11208 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/11208)

So, I will close this issue.
