### ISSUE TITLE
[SUGGESTION] Add set_default_imread_format

### ISSUE THREAD

**Issue by dayo05** [opencv/opencv#21840]
##### System information (version)

- OpenCV => 4.5.5
- Operating System / Platform => C++/Any
- Compiler => Any

##### Detailed description

OpenCV uses BGR or BGRA when using `imread()` and `imwrite()` and etc. But this format is hard to newbies. Because, RGB is more popular the BGR. So I want to add `set_default_imread_format(IMREAD_FORMAT_RGBA)` or `set_default_imread_format(IMREAD_FORMAT_HSV)` methods.

It is able to do with cvtColor method but if putting `imread` on lots of place, it can make bug in application.

##### Previous way
```cpp
auto image = imread("hello.png");
cvtColor(image, image, COLOR_BGR2GRAY);
```

##### Suggest way
```cpp
set_default_imread_format(COLOR_GRAY); // Just call once
auto image = imread("hello.png");
```

If it's good feature then I want to make this to PR.

**Comment by asmorkalov** [comment]
Most of OpenCV functions that expect color input expect BGR format rather than RGB. The new option you proposes is very dangerous and changes 3rd-party code that is linked to your app as library and does not expect this behavior.

**Comment by asmorkalov** [comment]
@vpisarev What is your opinion?

**Comment by vpisarev** [comment]
@dayo05, a global setting is a very bad idea, because it may change semantics of a code in completely different places where you or the author did not expect.

what I suggest to you is to add a tiny inline function:

```
namespace cv {
static inline Mat imreadrgb(const std::string& filename, int flags) {
     Mat img = imread(filename, flags);
     int cn = img.channels();
     if (cn == 3 || cn == 4)
          cvtColor(img, img, COLOR_BGR2RGB);
    return img;
}
}
```

into your project and use it. That will be a much safer solution.

**Comment by asmorkalov** [comment]
OpenCV team discussed the proposal on regular meeting and decided to reject proposal.
