### ISSUE TITLE
`cv.imdecode` can't open the dib(bmp) images from clipboard

### ISSUE THREAD

**Issue by NewUserHa** [opencv/opencv#21862]
##### System information (version)
- OpenCV => opencv-python 3.5.5
- Operating System / Platform => win10
- Compiler => pre-compiled

##### Detailed description
`cv.imdecode` can't open the dib(bmp) images from clipboard, but can from file

##### Steps to reproduce
work:
```py
with open('Untitled.bmp','rb') as f:
    src = f.read()
cv.imdecode(np.frombuffer(src, dtype=np.uint8), cv.IMREAD_COLOR)
```

can't work:
```py
# take a screenshoot or anything
win32clipboard.OpenClipboard()
src = win32clipboard.GetClipboardData(win32con.CF_DIB) # or win32con.CF_DIBV5
win32clipboard.CloseClipboard()
cv.imdecode(np.frombuffer(src, dtype=np.uint8), cv.IMREAD_COLOR)
```
the `imdecode` return `null`.
Is it able to support this kind of format of `BMP(aka DIB)` for OpenCV?

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
 - [x] I updated to the latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by Kumataro** [comment]
Sometime BMP file format is known as "DIB" too. It causes some confusions.

CF_DIB(DIBs in memory) is not BMP file storage format. [^1]

BMP file is started with "BM" signature. OpenCV/imgcodecs detects it and determine which is this data BMP format or not. [^2]

But CF_DIB has no signature. OpenCV/imgcodecs doesn't support it.

Valid image file header(signature, size and offset information) is needed.

For details about DIB,  please refer "DIBs in memory" section in [^1].

[^1]: https://en.wikipedia.org/wiki/BMP_file_format
[^2]: https://github.com/opencv/opencv/blob/4.x/modules/imgcodecs/src/grfmt_bmp.cpp#L55

**Comment by NewUserHa** [comment]
Thanks for your very detailed reply!
since CF_DIB is a common format too. currently, OpenCV is unable to read CF_DIB without import another library(like pillow).

**Comment by Kumataro** [comment]
This is a sample code to add (valid?) file header to clipboard image.

```
import win32clipboard
import cv2 as cv
import numpy as np

win32clipboard.OpenClipboard()

try:
    if win32clipboard.IsClipboardFormatAvailable(win32clipboard.CF_DIB):

        # Read CF_DIB data from clipboard.
        clipdata = win32clipboard.GetClipboardData(win32clipboard.CF_DIB)

        # Construction BMP File
        #  (1)FILE_HEADER
        #   Signature (BM)
        bmpfile = bytearray([0x42, 0x4d])
        #   Data Length
        bmpfile.extend( len(clipdata).to_bytes(4, 'little' ) )
        #   Reserved1/2
        bmpfile.extend( [0x00, 0x00, 0x00, 0x00 ])
        #   DATA offset
        #    14 - sizeof( FILE_HEADER ) 
        #    40 - sizeof( INFO_HEADER )
        #     0 - COLOR_TABLE(not supported)
        bmpfile.extend( (14 + 40 + 0).to_bytes(4, 'little') )

        #  (2)INFO_HEADER
        #  (3)(COLOR_TABLE)
        #  (4)DATA
        bmpfile.extend( clipdata )

        # f = open('test.bmp', 'wb')
        # f.write(bmpfile)
        # f.close()

        # Try to use via OpenCV
        img = cv.imdecode(np.frombuffer(bmpfile, dtype=np.uint8), cv.IMREAD_COLOR)
        cv.imwrite("hello.png", img)

    else:
        print("ERR")

finally:
    win32clipboard.CloseClipboard()


```

**Comment by NewUserHa** [comment]
very clear and detailed code.
Hope this code can be added to OpenCV for the built-in CF_DIB support.

<sup>btw, I guess probably `win32clipboard.OpenClipboard()` should be the only one inside the `try:` block.</sup>
