### ISSUE TITLE
What is the difference between "import cv2" and "import cv2.cv2"

### ISSUE THREAD

**Issue by yjcreation** [opencv/opencv#21867]
I have two questions.
one: the difference between `import cv2` and `import cv2.cv2`
the other: cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-memyuvq3\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

In response to question 2, I have installed opencv-python and opencv-contrib-python

**Comment by LaurentBerger** [comment]
please read https://pypi.org/project/opencv-contrib-python/

**Comment by yjcreation** [comment]
I uninstalled the opencv-python and opencv-contrib-python by command pip. Next, I install the opencv-python and opencv-contrib-python by pip. Run the program, get the same error.

**Comment by fengyuentau** [comment]
Hello @yjcreation , 
1. Use `import cv2`. Some features are lost if using `import cv2.cv2`. Check the code in your `opencv-python` installation for more details.
2. Check if this link helps: https://stackoverflow.com/questions/67120450/error-2unspecified-error-the-function-is-not-implemented-rebuild-the-libra

**Comment by asmorkalov** [comment]
Since 4.6.0 OpenCV-Python uses loader code to find cv2.so. Please do not use `import cv2.cv2`.
