### ISSUE TITLE
Why are there 3 compiled dynamic libraries? What's the difference between them?

### ISSUE THREAD

**Issue by Dandelion111** [opencv/opencv#21866]
<img width="200" alt="5738e7a7591e792495cc5b2252574c2" src="https://user-images.githubusercontent.com/48303408/163294064-57e147bd-e087-452d-8c52-30026710ba29.png">

**Comment by asmorkalov** [comment]
They are not 3 libs, just links. It's general practice for sname, versions, backward compatibility, etc on Linux.
