### ISSUE TITLE
Error in processing fp16 data

### ISSUE THREAD

**Issue by cvDFT** [opencv/opencv#21872]
![image](https://user-images.githubusercontent.com/94675255/163565731-1c18a105-1f71-4faa-83af-5dd345998087.png)

**Comment by fengyuentau** [comment]
Hello @cvDFT , can you provide the demo so that I can have a check for you?

**Comment by asmorkalov** [comment]
OpenCV does not support FP16 for regular image processing and computer vision operations like cv::resize. There are 2 ways to achieve the result:
- Wrap the data as `CV_16U`/ `CV_16S` buffer and use nearest neighbour resize. It does not manipulate with pixel values and image should be resized correctly.
- Convert the data to `CV_32F` and resize it with any supported interpolation. See `convertFp16` for details: https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga9c25d9ef44a2a48ecc3774b30cb80082
