### ISSUE TITLE
Cyrillic keyboard layout issue

### ISSUE THREAD

**Issue by GMtranscendence** [opencv/opencv#21899]
##### System information (version)

- OpenCV => opencv-contrib-python 4.5.5.64
- Operating System / Platform => Arch Linux 64 Bit
- Compiler => native python 3.10.4 iterpreter 

##### Detailed description

opencv library crashes every time you use russian keyboard layout ( possible problems with others as well, at least cyrillic ones ) and also when pressing <shift+alt> to change layout during image displaying
##### Steps to reproduce
1. create a simple script (test.py) to open an image and paste the code:
```.py
   import cv2 as cv
  
   img = cv.imread('some_image.jpg')
   cv.imshow('Picture', img)
   while True:
       k = cv.waitKey(0) & 0xFF
       if k == 27:
           cv.destroyAllWindows()
           break
```
2. execute the script from terminal:
python test.py

3. try to change keyboard layout (<shift+alt>) or press a cyrillic key

Error:
```
ASSERT: "false" in file qasciikey.cpp, line 501

shell returned 134
```

**Comment by Kumataro** [comment]
cv::waitKey() with Hankaku-Zenkaku Key in Japanese keyboard has same issue.

cv::waitKey() calls some functions in Qt Libraries.  QTest::keyToAscii() is used to convert Qt Key to ascii code.

But QTest::keyToAscii() supports only limited keys, and if any out-range key code is detected, assert() is happen .

  https://github.com/qt/qtbase/blob/6.3/src/testlib/qasciikey.cpp#L501

This patch is only to ignore Qt's assert.
Because some behaviors are changed, I think it is small difficult to commit with back-compatibility reason.

(For example, latin-1 code should be apply `QTest::keyToAscii(qtkey);` )

```
kmtr@kmtr-virtual-machine:~/work/opencv$ git --no-pager diff
diff --git a/modules/highgui/src/window_QT.cpp b/modules/highgui/src/window_QT.cpp
index d8f2271faa..172e852bb1 100644
--- a/modules/highgui/src/window_QT.cpp
+++ b/modules/highgui/src/window_QT.cpp
@@ -2202,19 +2202,17 @@ void CvWindow::displayPropertiesWin()
 //Need more test here !
 void CvWindow::keyPressEvent(QKeyEvent *evnt)
 {
-    //see http://doc.trolltech.com/4.6/qt.html#Key-enum
     int key = evnt->key();
+    Qt::Key qtkey = static_cast<Qt::Key>(key);

-        Qt::Key qtkey = static_cast<Qt::Key>(key);
-        char asciiCode = QTest::keyToAscii(qtkey);
-        if (asciiCode != 0)
-            key = static_cast<int>(asciiCode);
-        else
-            key = evnt->nativeVirtualKey(); //same codes as returned by GTK-based backend
+    if ( (Qt::Key::Key_Space <= qtkey) && (qtkey <= Qt::Key::Key_AsciiTilde) )
+        key = static_cast<int>( QTest::keyToAscii(qtkey) );
+    else
+        key = evnt->nativeVirtualKey(); //same codes as returned by GTK-based backend

     //control plus (Z, +, -, up, down, left, right) are used for zoom/panning functions
-        if (evnt->modifiers() != Qt::ControlModifier)
-        {
+    if (evnt->modifiers() != Qt::ControlModifier)
+    {
         mutexKey.lock();
         last_key = key;
         mutexKey.unlock();
kmtr@kmtr-virtual-machine:~/work/opencv$
```

**Comment by alalek** [comment]
@Kumataro Proposed patch looks good to me! Could you please open PR for "3.4" branch?
