### ISSUE TITLE
 Iplimage has not been declared

### ISSUE THREAD

**Issue by pfeducode** [opencv/opencv#21938]
`#ifndef MM3D_H
#define MM3D_H

#include <math.h>
#include "3DMMGlobal.h"
//#include <cv.h> pf注释的,找不到这个文件

#include <opencv2/opencv.hpp>
#include <algorithm>
//#include <Windows.h> pf注释的,找不到这个文件
//#include <gl\GL.h> pf注释的,找不到这个文件
//#include <GL\GLU.h> pf注释的,找不到这个文件

using namespace std;
using namespace cv;

#define INF 1E20

class MM3D
{
public:
	// 3DMM and Reference Frame Mapping
	void Cartesian2Ref(double* vertex, double* tri, double* texture, int width, int height, int nver, int ntri, double* ref, double* refco, double* tri_ind);
	void ZBuffer(double* vertex, double* tri, double* texture, int nver, int ntri, double* src_img, int width, int height, int nChannels, double* img, double* tri_ind);
	void ZBufferTri(double* vertex, double* tri, double* texture_tri, int nver, int ntri, double* src_img, int width, int height, int nChannels, double* img, double* tri_ind);
	void GetCoverTri(double* vertex, double* tri, double* r, double* p, int nver, int ntri, double* coverTri);
	void VisibleSurf(double* vertex, double* tri, double* r, int nver, int ntri, double* vis_bin);
	bool PointInTri(Mat* point, Mat* pt1, Mat* pt2, Mat* pt3);
	void DistanceTransform(double* dt, double* im, int width, int height);
	void dt(float *d, float *f, int n); 
	void Lighting(double* vertex, double* tri, double* tex, int _nv, int _nt, Illum_Para para, IplImage* img);
	void DrawModal(float* _shape, unsigned int* _triangle, float* _color, int _nt, int _nv, Illum_Para para, unsigned char* face, int widthstep);
	void NormDirection(float* vertex, unsigned int* tri, int nt, int nv, float* norm);
	void MeshMap(double* vertex, double* tri, int nver, int ntri, double* meshMap, int width, int height);
	void OcclusionQuery(double* vertex, double* tri, int ntri, int nver, int width, int height, double* visibility, double threshold);
	// OpenGL related
	HGLRC _hrc;	
	HDC _hdc;
	BYTE* _data;
	HBITMAP _bitmap;	// for face
	int _width;
	int _height;
	BOOL PrepareGL();
	BOOL ReleaseGL();
	double xmin;
	double xmax;
	double ymin;
	double ymax;
	double zmin;
	double zmax;

};

#endif`

-----------

![1](https://user-images.githubusercontent.com/100210045/166149927-0697e128-a8a5-4f92-9a5c-e0420f8cae2f.png)
----
my opencv version is 4.5.5. I use matlab  mex compile opencv, but i got a bug. I have no idea

**Comment by asmorkalov** [comment]
`IplImage` is legacy C type from ancient OpenCV 1.x interface. It's deprecated and not included into default headers. You need to include `types_c.h` to use it. 
BTW, The C interface is fully removed in 5.x branch and will not be available any more.

**Comment by pfeducode** [comment]
> `IplImage`是来自古老 OpenCV 1.x 接口的遗留 C 类型。它已被弃用，并且不包含在默认标头中。您需要包含`types_c.h`才能使用它。 顺便说一句，C 接口在 5.x 分支中已完全删除，将不再可用。

thank you very much, I agree with you. The code above is a very old but excellent code. I need it. And I solved this problem by adding the follow files
#include <opencv2/opencv.hpp>
#include <opencv2/imgproc/imgproc_c.h>
#include <opencv2/imgproc/types_c.h>
#include <opencv2/highgui/highgui_c.h>
