### ISSUE TITLE
opencv

### ISSUE THREAD

**Issue by Estheryu991** [opencv/opencv#21957]
was ist die Unterschied zwischen opencv und openai

**Comment by d-kleine** [comment]
openAI: AI research company, see [here](https://openai.com/about/)
opencv: library for computer vision, see [here](https://opencv.org/about/)

Not an issue, can be closed

**Comment by NoahSchiro** [comment]
Translation for those curious:

"What is the difference between OpenCV and OpenAI"

Antwort fur @Estheryu991 auf Deutch:

OpenAI ist ein Forschungsunternehmen
OpenCV ist Softwarebibliothek für Computer Vision

As @d-kleine had mentioned, has been answered and can be closed
