### ISSUE TITLE
Python cv.calcHist(gray_img, [0], ..) fails on SingleChannelImage

### ISSUE THREAD

**Issue by alex77g2** [opencv/opencv#21976]
##### System information (version)
- OpenCV => 4.5.5
- Operating System / Platform => Windows 10, 64 Bit
- Compiler => Python 3.10.3

##### Detailed description

Short Python Code:
    print(img.shape) # is (378, 504) greyscale
    hist = cv.calcHist(img, [0], None, [256], (0, 256)) # uses first row only, because there is only 1 channel
    sum = np.sum(hist)
    print(sum) # is 504, which means only 504 pixels were used in calcHist()

##### Steps to reproduce

python HistFail.py # attached as .txt

PyV: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]
CV2: 4.5.5
2  # ndim
(12, 40)  # shape
sum (pixel count) = 40  #  should be 12 x 40 = 480 pixel, not only 1 line

##### Issue submission checklist

[HistFail.txt](https://github.com/opencv/opencv/files/8685472/HistFail.txt)

**Comment by berak** [comment]
i dont think this is a bug
have [a look at the docs again](https://docs.opencv.org/4.x/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d), does **images** (plural !) ring a bell  ?
you're supposed to feed a **list** of images, not a single one (which will be interpreted as a list of *rows*, which is what you see)

make it:

    hist = cv.calcHist([img], [0], None, [256], (0, 256)) # again, *list* containing a single image

**Comment by alex77g2** [comment]
Thanks, this works.
I think an extra Line in Docu for the often-used single-image use-case would be helpful.
"cv.calcHist(  images, channels, mask, histSize, ranges[, hist[, accumulate]]  ) -> hist" // old
"cv.calcHist(  [image], [0], mask, histSize, ranges[, hist[, accumulate]]  ) -> hist" // additionally + new

**Comment by berak** [comment]
admittedly, this is some "monster" function, covering more use-cases, we'd ever imagine.

the doc-string is *generated* from c++ code, so it cant be changed
however, if you think, something helpful can be added to the c++ comments, add a pr

**Comment by alex77g2** [comment]
Yes, Issue can be closed. Thanks for your efforts.
