### ISSUE TITLE
SystemError: <built-in function writeTextGraph> returned NULL without setting an error when using cv2.dnn.writeTextGraph

### ISSUE THREAD

**Issue by ashroice** [opencv/opencv#21989]
- OpenCV = 4.1.2
- Operating System / Platform = Windows 64 Bit
- Compiler = Google Colab

So I recently created a machine learning model with Keras and saved it using the save_model function into a .pb file. I want to use this model with OpenCV, and therefore have been trying to obtain a .pbtxt file to use alongside the DNN module of OpenCV (net = cv2.dnn_DetectionModel(weightsPath,configPath)). Yet for some reason, I keep getting the error in the title: SystemError: <built-in function writeTextGraph> returned NULL without setting an error.

What I've done: I've been saving the model on Google Colab, so I've tried restarting the runtime a couple of times. I've made sure my file path was correct. I'm not sure how to check if the .pb file is corrupted, but I don't imagine it is since I directly downloaded it from Keras.

This is the code below:
```
model.save('mymodel5',save_format='pb')
loaded_model = tf.keras.models.load_model('/content/mymodel6') // this is the genereated folder from the .save function of keras
import cv2 
cv2.dnn.writeTextGraph(loaded_model, 'graph.pbtxt')
```

**Comment by asmorkalov** [comment]
`loaded_model` is Keras object, not OpenCV. OpenCV `cv2.dnn.writeTextGraph` does not know what to do with it. You need to load the model with OpebCV first to use OpenCV functions with it.
