### ISSUE TITLE
TypeError: imwrite() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by billalkuet07** [opencv/opencv#22009]
##### System information (version)
<-- Example
- OpenCV => 4.5.5
- Operating System / Platform => Docker (Ubuntu 20.04)
- Compiler => GCC 9.3.0
- python 3.9.7
-->

##### Detailed description

I am trying to save jpg image with quality 80 by opencv. Here is the python script I tried:

`cv2.imwrite(isdocker.DOCKER_PREFIX + IM.path + IM.name, IM.data, [(int(cv2.IMWRITE_JPEG_QUALITY),80)])`

It pops up with an error 'TypeError: imwrite() takes 2 positional arguments but 3 were given'. I know a similar post in [[here](https://stackoverflow.com/questions/48629370/python-error-imwrite-takes-at-most-3-arguments-4-given)]. But I think its different issue. I have read the [documentation](https://docs.opencv.org/4.x/d8/d6a/group__imgcodecs__flags.html#ga292d81be8d76901bff7988d18d2b42ac) from opencv and it seems you have changed something. Please help me.

**Comment by fengyuentau** [comment]
Make a tuple for params instead of a list of tuples `(paramId_1, paramValue_1, paramId_2, paramValue_2, ... .)`. You can check for more details in python with `help(cv2.imwrite)`.

So your example should be corrected as `cv2.imwrite(isdocker.DOCKER_PREFIX + IM.path + IM.name, IM.data, (cv2.IMWRITE_JPEG_QUALITY,80))`.

**Comment by billalkuet07** [comment]
I tried your solution still getting the same issue. If i remove the image quality part then the cv2.imwrite() is working without any errors.That indicates something related to cv2.IMWRITE_JPEG_QUALITY

**Comment by alalek** [comment]
This `cv.imwrite("test.png", numpy.zeros((16,16,3), numpy.uint8), (cv.IMWRITE_JPEG_QUALITY, 80))` works well.
But this `cv.imwrite("test.png", numpy.zeros((16,16,3), numpy.uint8), (cv.IMWRITE_JPEG_QUALITY, 80.0))` is not.

You need to check types of passed arguments in your code (Python is not a statically typed language, so you need to do this in runtime).

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by billalkuet07** [comment]
Ya, I know this. I am confirm that its 80 (80.0), even i tried with int(80) but it has same result. Also I tried with 4.5.3.56 and the result is same. I have confiemed that : isdocker.DOCKER_PREFIX (<class 'str'>) + IM.path (<class 'str'>) + IM.name (<class 'str'>), IM.data (<class 'numpy.ndarray' with shape (2592,1944,3)>). I am running this code inside the wsl2 docker and in tensorflow:22.04-tf2-py3 image.

**Comment by xpngzhng** [comment]
I have the same problem, and my opencv version is 4.5.3, Windows

  File "detect.py", line 183, in run
    cv2.imwrite(save_path, im0, (int(cv2.IMWRITE_JPEG_QUALITY), 90))
TypeError: imwrite() takes 2 positional arguments but 3 were given
