### ISSUE TITLE
Github wiki page typos

### ISSUE THREAD

**Issue by samuelshagan** [opencv/opencv#22016]
Page: https://github.com/opencv/opencv/wiki/How_to_contribute
1. "check that it's still exists" should be "check that it still exists"
2. "reproducable" should be spelled "reproducible"
![image](https://user-images.githubusercontent.com/59494585/169488801-0f511a68-2b5c-4cf6-b687-1be84d09b4d7.png)
3. "youself" should be "yourself"
![image](https://user-images.githubusercontent.com/59494585/169489009-41a8b856-ffca-474d-a36c-015234ba52cd.png)
4. "test" should be plural "tests" in multiple places
![image](https://user-images.githubusercontent.com/59494585/169489672-2fc5366b-e443-488e-9442-f99e0fd87815.png)
5. "you" should be "your"
![image](https://user-images.githubusercontent.com/59494585/169489958-cf16b879-ace4-4d34-89f4-724d048d25d4.png)

Page: https://github.com/opencv/opencv/wiki/FAQ
1. "if" should be "of"
![image](https://user-images.githubusercontent.com/59494585/169490965-4fbfdca0-aa09-49ac-a5df-707eef61dad3.png)
2. "Why OpenCV does" should be "Why does OpenCV"
3. "it's" should be "its"
![image](https://user-images.githubusercontent.com/59494585/169491558-d1e12096-a0d3-4eb4-adc7-27d417be9c2b.png)
4. "Some of conversions" should be "Some conversions"
![image](https://user-images.githubusercontent.com/59494585/169492049-7e6de0d9-5019-47e8-a976-84fb7b49d417.png)

Page: https://github.com/opencv/opencv/wiki/Coding_Style_Guide
1. "functionality is does" should be "functionality does"
![image](https://user-images.githubusercontent.com/59494585/169492775-eb4ab7e0-a75a-4fdf-b7ae-3c7d97f6e66f.png)
2. "can have include" should be "can include"
![image](https://user-images.githubusercontent.com/59494585/169493367-70c0b5aa-21ab-4858-a8dd-5613e7adb116.png)
3. "throught" should be "through"
4. "samples" should be singular "sample"
![image](https://user-images.githubusercontent.com/59494585/169493856-7b8269cf-b39f-4bda-8db3-afcee0c54925.png)

**Comment by fengyuentau** [comment]
Thanks for finding these typos and the corrections. These typos are confirmed and corrected. Feel free to re-open this issue if you find more.
