### ISSUE TITLE
ORB FeatureDetector has different result between C++ and Python

### ISSUE THREAD

**Issue by Audrey528** [opencv/opencv#22020]
I use ORB FeatureDetector to extract feature using Python and C++, code sees below. But the output results is different completely, I am sure my input is same, and OpenCV version all is 3.4.6. I am confuse, I need some help.
 
![36dd59d464c83944dc2cbe65eb050be](https://user-images.githubusercontent.com/68552295/169807195-c3c1a1fa-bccc-4005-a6f6-eacd4db4fbc5.png)
![829fc43294916a32f4ca0a56b405f43](https://user-images.githubusercontent.com/68552295/169807233-b8a13427-d3f9-4a00-8233-f37fe6b53633.png)

**Comment by asmorkalov** [comment]
OpenCV Python bindings are wrapper on top of OpenCV code. The difference means:
- You use different algorithm parameters in C++ and Python. It's not always obvious.
- You use different instances of OpenCV for Python and C++.
