### ISSUE TITLE
Inaccuracy in the tutorial for installation for Windows

### ISSUE THREAD

**Issue by Albert208** [opencv/opencv#22053]
The command to set the OpenCV environment variable and add it to the systems path is inaccurate and it's confusing for a noob like me : 
![image](https://user-images.githubusercontent.com/55127689/170965982-b3d8049f-f024-4e5b-8657-f52ff589f738.png)
This image is from : https://docs.opencv.org/4.5.5/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path

Instead, I used this command and it worked fine : 
setx OPENCV_DIR "[opencv_path]\build\x64\vc14"
Notice the use of < " " >.

 - [x] I report the issue, it's not a question

**Comment by s39674** [comment]
Isn't `opencv` almost always going to get installed on one of the root directories? you don't need `< " " >` if that's the case as there are no spaces in the name.
Also, `-m` is said to be: `The -m should be added if you wish to make the settings computer wise, instead of user wise.`

**Comment by sathvik2612** [comment]
Hi! can i start working on this

**Comment by Change-m** [comment]
Hi, I would like to start work on this issue.

**Comment by aryansardy** [comment]
hi i can work on this

**Comment by SoumyaTINT034** [comment]
Hey all, I am new in the open source community. Can I contribute to this project?

**Comment by Denisthatorf** [comment]
I am new to open source. Can I contribute to this project?

**Comment by Jelishev** [comment]
Hi I'm new here. Can I contribute to this?

**Comment by parth-bansal081** [comment]
Hi OpenCV team!

First-year B.Tech CSE India, GSoC 2026 prep.
✅ Contours tutorial complete + working locally
✅ Fixed Windows pip install issue personally

**Claiming #22907 for 24hr fix**
Will submit PR with:
- Screenshot of fix
- Test on Windows 11
- GSoC contribution tracking

Thanks!
