### ISSUE TITLE
how can i put opencv-tracker in yolov5?

### ISSUE THREAD

**Issue by LimJihu** [opencv/opencv#22062]
hi. i have to put opencv-tracker(maybe KCF) in Yolov5.

um, if you've used opencv-tracker before, you know about this.

i don't want to selectROI with my mouse. i just want to put detected bbox coordinates from detect.py
and i want to track every frames in video.
![image](https://user-images.githubusercontent.com/89961242/171564459-bd06c7e8-e65d-40b3-b084-d6ff3510a676.png)

so this is my code (this is plots.py)

i'm having
error: (-5:Bad argument) One or more matrix operands are empty. in function 'checkOperandsExist'
error. plz help me. i want how to wirte the code.

**Comment by asmorkalov** [comment]
Use forum.opencv.org for questions.
