### ISSUE TITLE
cv2.drawFrameAxes broken

### ISSUE THREAD

**Issue by walchko** [opencv/opencv#22066]
Using python 3.9, macOS 12.2.1, OpenCV 4.5.5 I am not getting the correct axes displayed.

The axes are defined as "OX is drawn in red, OY in green and OZ in blue." in the [reference docs](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gab3ab7bb2bdfe7d5d9745bb92d13f9564)

Using the code below: 

- zero rotation has the z-axis (blue) right and y-axis (green) down (wrong orientation)
- 90 deg around z-axis, rotates instead around the x-axis (red)
- 60 deg around y-axis, seems to work
- 60 deg around x-axis, rotates instead around the z-axis (blue)

```python
def drawAxes(rvecs):
    tvecs = np.array([0,0,0.])
    width = 400

    im = np.zeros((width,width,3))
    cx, cy = width//2, width//2
    f = width
    K = np.array([[f, 0, cx],[0, f, cy],[0, 0, 1]], dtype=float)
    dist = np.array([0.0, 0.0, 0.0, 0.0, 0.0], dtype=float)

    # set the axes size as a function of the marker's 
    # square size and project onto image space
    s = 4
    axis = np.float32([[s,0,0], [0,s,0], [0,0,s]]).reshape(-1,3)
    imgpts, jac = cv2.projectPoints(
        axis, 
        rvecs, 
        tvecs, 
        K, 
        dist
    )

    cv2.drawFrameAxes(
        im, 
        K, 
        dist, 
        rvecs, tvecs, 
        length=.2, thickness=3) 
    
    return im

plt.figure(figsize=(10,10))
plt.subplot(2,2,1)
plt.imshow(drawAxes(np.array([0,0,0.])))
plt.title("XYZ = (0,0,0)");

plt.subplot(2,2,2)
plt.imshow(drawAxes(np.array([0,0,pi/2])))
plt.title("XYZ = (0,0,90)");

plt.subplot(2,2,3)
plt.imshow(drawAxes(np.array([0,pi/3,0])))
plt.title("XYZ = (0,60,0)");

plt.subplot(2,2,4)
plt.imshow(drawAxes(np.array([pi/3,0,0])))
plt.title("XYZ = (60,0,0)");
```

![download](https://user-images.githubusercontent.com/918960/171949439-011340c5-23a0-42ac-aaa4-e48e6638794f.png)

**Comment by shapovalov** [comment]
Yeah, if you assume X is blue, Y is green, and Z is red, it all starts making sense.

**Comment by krishna-esrlabs** [comment]
@walchko  switching from BGR to RGB format before visualization will fix the issue.
