### ISSUE TITLE
opencv install instructions for windows missing important information

### ISSUE THREAD

**Issue by eliam** [opencv/opencv#22072]
##### System information (version)

- OpenCV => 4.5.5
- Operating System / Platform => Windows 64 Bit
- Compiler => python 3.9.6

##### Detailed description

Install instructions here don't mention dll dependency - https://docs.opencv.org/4.x/d5/de5/tutorial_py_setup_in_windows.html

##### Steps to reproduce

install opencv following the instructions.  Unable to import cv2 due to : "ImportError: DLL load failed while importing cv2: The specified module could not be found.".  Copying opencv_world455.dll alongside the pyd resolves this and should be mentioned in the install instructions.

**Comment by denred0** [comment]
I got same error. I spent about 2 days but with no result. I think its connected with my win 11 because I have successfully installed OpenCV on Win10 many times.

**Comment by isgallagher** [comment]
@eliam thank you, I was tearing my hair out trying to get this working

**Comment by a-sajjad72** [comment]
> Copying opencv_world455.dll alongside the pyd resolves this and should be mentioned in the install instructions.
man you made my day. finally after a week trying again and again, you sorted it out. the documentation should be updated.
