### ISSUE TITLE
How to properly use opencl acceleration applied to 360 surround view

### ISSUE THREAD

**Issue by zhouxf-cn** [opencv/opencv#22082]
360 surround view, multi-threaded processing of pictures from different cameras, opencv (4.5.5) for image correction and perspective transformation (remap), the CPU usage is very high, so use opencl (1.0) to accelerate, but with the increase of the number of threads, The processing time of a single thread increases several times, and the GPU occupancy rate is also high. How to optimize?
1. Use opencl 2.0?
2. Picture copy, umat has no data pointer, cannot use hardware RGA acceleration, can only use copyto, which is time-consuming
3. It feels that in multi-threading, the operation of opencl is blocked and queued, and the use of mutex has almost no effect on the time consumption

**Comment by asmorkalov** [comment]
use forum.opencv.org for discussions and questions.
