### ISSUE TITLE
SyntaxError: invalid syntax   --->frame = cv2.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)

### ISSUE THREAD

**Issue by VegaLight** [opencv/opencv#22085]
When I tried to use Lucas-Kanade on optical flow, I couldn't figure out why there's always  invalid syntax when I use" frame = cv2.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)" 
Here's the code, guys please help me.

import numpy as np
import cv2

cap = cv2.VideoCapture('02_Video/02_Foreground.avi')
feature_params = dict( maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7 )

lk_params = dict( winSize = (15,15), maxLevel = 2 )

color = np.random.randint(0,255,(100,3))

ret, old_frame = cap.read()
old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)                         
p0 = cv2.goodFeaturesToTrack(old_gray, mask = None, **feature_params)
mask = np.zeros_like(old_frame)

while(True):
    ret,frame = cap.read()
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)                       
    
    p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)                         
    
    good_new = p1[st==1]  
    good_old = p0[st==1]
    
    for i, (new,old) in enumerate(zip(good_new,good_old)):
        a,b = new.ravel()
        c,d = old.ravel()
        mask = cv2.line(mask,(int(a),int(b),(int(c),int(d)),color[i].tolist(),2)                         
        frame = cv2.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)               #<---------------The problem is here!!!!!!!!!!!!!
        #image = cv2.circle(image, center_coordinates, radius, color, thickness)
    img = cv2.add(frame,mask)
    
    cv2.imshow('frame',img)
    k = cv2.waitKey(150) & 0xff
    if k == 27:
        break
        
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1,1,2)
    
cv2.destroyAllWindows()
cap.release()

**Comment by berak** [comment]
hello, this is the opencv **library** bug tracker.
kindly ask your questions on https://forum.opencv.org/ (and close this issue), thank you.

besides that, the error is in the `cv2.line()` call above ( missing `)` bracket after `int(b)` )

**Comment by VegaLight** [comment]
> hello, this is the opencv **library** bug tracker. kindly ask your questions on https://forum.opencv.org/ (and close this issue), thank you.
> 
> besides that, the error is in the `cv2.line()` call above ( missing `)` bracket after `int(b)` )

thank you, mate!
