### ISSUE TITLE
!(roi & image_roi).empty() in function error 

### ISSUE THREAD

**Issue by LimJihu** [opencv/opencv#22097]
![image](https://user-images.githubusercontent.com/89961242/173564496-d7a85d24-80f6-4151-9f6f-42a7ffc5e46f.png)

now i'm having this error while making opencv KCF_tracker.

any help plz?

**Comment by berak** [comment]
helo, this is the opencv **library** bug tracker, wrong place for your problem.
please, kindly close this issue, and ask again on https://forum.opencv.org/ , where we can help ou much better, thank you
