### ISSUE TITLE
 No rule to make target `zlib', needed by `lib/libopencv_imgcodecs.4.6.0.dylib'

### ISSUE THREAD

**Issue by jinfagang** [opencv/opencv#22119]
I have downloaded zlib and make , installed to system path, also, opencv CMake output indicates me it found, still unable to build 

```
 No rule to make target `zlib', needed by `lib/libopencv_imgcodecs.4.6.0.dylib'
```

macOS.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/21303438/174094180-d799e36e-1855-4613-8f4f-7c83ae8487c9.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/21303438/174094214-afe45b04-2cf9-45d6-abfc-a3d68f34626e.png">

tried many times, still didn't work.

**Comment by jinfagang** [comment]
shit, I solved it.

**Comment by AnselDai** [comment]
Please, how to solve it?

**Comment by linces** [comment]
> shit, I solved it.

??????????

**Comment by zhaoxifeng** [comment]
I got the same problem. How did you fix it? @jinfagang

**Comment by superheasy** [comment]
？？？ 
4.7.0 has same error....

**Comment by yueleizhao** [comment]
maybe have a try，cmake -DCMAKE_BUILD_TYPE=Release  -DBUILD_ZLIB=OFF -DBUILD_EXAMPLES=ON  <your path>

**Comment by CANLAN-SC** [comment]
How to solve it?

**Comment by Napoleon-BlownApart** [comment]
@lucasjinreal, how did you solve this issue?  Did you use `-DBUILD_ZLIB=OFF`?

I have `zlib` installed via Xcode as well as Homebrew. `cmake` finds my brew version,`zlib (ver 1.2.13)` but `make` returns the error that was stated in the opening post of this thread.

I tried symlinking the library, headers, and PkgConfig file into `/usr/local/...` but still got the same error.

**Comment by aizyler** [comment]
yes ，I used“ -DBUILD_ZLIB=OFF”

**Comment by Napoleon-BlownApart** [comment]
> I have the same problem. ZLIB=off doesn't sound like good solution

When 'off' is used, then ZLIB is provided by the OS/Xcode, so it's not necessary to use a custom version.

**Comment by aizyler** [comment]
If you have brew installed, there may be a problem with brew.Perhaps you could uninstall brew and reinstall it.My computer is m2 pro, and I solved this problem with” -DBUILD_ZLIB=OFF”.

**Comment by aizyler** [comment]
If you have installed OpenCV with brew, there may be a problem with brew.Perhaps you could uninstall brew and reinstall it.My computer is m2 pro, the software I use is CLion, and I solved this problem with” -DBUILD_ZLIB=OFF”.

**Comment by aizyler** [comment]
If you have installed OpenCV with brew, there may be a problem with brew.Perhaps you could uninstall brew and reinstall it.My computer is m2 pro, and the software I use is CLion.
