### ISSUE TITLE
brew install opencv error

### ISSUE THREAD

**Issue by qxqxq** [opencv/opencv#22115]
MacBookPro:~ qxq$ brew install opencv
Warning: No available formula with the name "opencv".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

Thanks!

**Comment by alalek** [comment]
This is upstream opencv repository. We don't maintain package managers here.
You should use channels of homebrew project for reporting a problem.

BTW, try `opencv@4`: https://formulae.brew.sh/formula/opencv
