### ISSUE TITLE
cv::VideoCapture - time value obtained on some frames at the end of the video is always 0

### ISSUE THREAD

**Issue by chinanewer** [opencv/opencv#22141]
##### System information

- OpenCV => 4.5.5
- Operating System / Platform => Windows 64 Bit lstc
- opencv dll Compiler => MSVC 2017
- Devlop IDE Compiler : Qt 6.2.4 MSVC 2019 64Bit 
- Note: Binary files (dll) obtained using the exe installation package downloaded from the official website

##### Detailed description

Use the `cv::VideoCapture::get()` function with a parameter value of `cv::CAP_PROP_POS_MSEC` to get the time of the current video frame.
The time value obtained on some frames at the end of the video is always 0, and these frames further ahead are normal time values.
I've tried some videos and it's always like this, my local videos are very easy to reproduce this issue.

**Comment by danopdev** [comment]
I have the same issue with the latest 4.x sources (linux x64 / gcc).

**Comment by danopdev** [comment]
At least in the FFMPEG implementation, the method "CvCapture_FFMPEG::grabFrame()" have branches that can set the valid state to true but don't update "picture_pts" value.

**Comment by danopdev** [comment]
Test code to reproduce it:

```
#include <opencv2/videoio.hpp>
#include <opencv2/opencv.hpp>

using namespace cv;

int main() {
    VideoCapture vc = VideoCapture("issue-22141.mp4");
    Mat frame;

    while(1) {
        vc >> frame;
        if (frame.empty())
            break;

        double value = vc.get(cv::CAP_PROP_POS_MSEC);
        printf("Pos: %f ms\n", value);
    }

    vc.release();
 
    return 0;
}
```

Before the PR the output ends with:
```
Pos: 3180.000000 ms
Pos: 3220.000000 ms
Pos: 3260.000000 ms
Pos: 0.000000 ms
Pos: 0.000000 ms
Pos: 0.000000 ms
```

After the PR the output ends with:
```
Pos: 3100.000000 ms
Pos: 3140.000000 ms
Pos: 3180.000000 ms
Pos: 3220.000000 ms
Pos: 3260.000000 ms
Pos: 3300.000000 ms
Pos: 3340.000000 ms
Pos: 3380.000000 ms
```

https://user-images.githubusercontent.com/7062741/175004105-b271be8b-3baa-498a-b7c1-3e55d5ab5c8e.mp4

**Comment by asmorkalov** [comment]
Duplicates https://github.com/opencv/opencv/issues/20550
