### ISSUE TITLE
Replace classic algorithms with DNN-based ones in module objdetect for OpenCV 5.0

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv#22142]
This issue is used for the discussion on DNN-based substitutes for classic algorithms in module `objdetect`. To get started, information is collected and listed below. Leave a comment to give your suggestions or to list other classic algorithms to be replaced:

| Classic algorithms in `objdetect` | Corresponding APIs in `objdetect` | Keep or move | DNN-based substitutes |
| --------------------------------- | --------------------------------- | ------------ | --------------------- |
| Haar/Cascade                      | cv::BaseCascadeClassifier; cv::CascadeClassifier; cv::DefaultDeleter< CvHaarClassifierCascade >; cv::DetectionBasedTracker | move to opencv_contrib | GSoC'22 objdetect project |
| HOG                               | cv::DetectionROI; cv::HOGDescriptor | move to opencv_contrib | GSoC'22 objdetect project |
| QRCode - Detect and decode        | cv::QRCodeDetector                | to be discussed | [WeChatQRCode in opencv_contrib](https://github.com/opencv/opencv_contrib/tree/4.x/modules/wechat_qrcode) |
| QRCode - Encode                   | cv::QRCodeEncoder                 | keep         | None                  |

NOTE:
- [Common functions and classes](https://docs.opencv.org/4.x/de/de1/group__objdetect__common.html) should be moved along with classic algorithms if they are not needed by QRCode module.
- [cv::FaceDetectorYN](https://docs.opencv.org/4.x/df/d20/classcv_1_1FaceDetectorYN.html) & [cv::FaceRecognizerSF](https://docs.opencv.org/4.x/da/d09/classcv_1_1FaceRecognizerSF.html) will be kept as they are DNN-based already.

~A pull request will be created soon to move classic algorithms in objdetect to opencv_contrib. DNN substitutes will added after the pull request.~

**Updates on 2022-06-24**:
New solution should be introduced first, then move the corresponding classic algorithms to opencv_contrib. Since we have DNN-based face detection (cv::FaceDetectorYN) already, we will start with moving Haar/Cascade related APIs to opencv_contrib.

**Comment by takmin** [comment]
I agree to separate dnn-based detection algorithms from classic ones, but I hope dnn based object detection algorithm moves to dnn module.
OpenCV is unique because it still has a lot of NON-CNN based algorithms.  If I want to use CNN based algorithms, there are a lot of choices such as pytorch, tensorflow, OpenVINO, etc.  
Cascade classifier is  old but still good because it works very fast without GPU.  I still use this algorithm in case that I need to detect objects without GPU.

**Comment by takmin** [comment]
Hi @fengyuentau, thank you for your quick reply.  If it works faster than cascade classifier on CPU, no problem for me.

**Comment by fengyuentau** [comment]
Done via https://github.com/opencv/opencv/pull/25198
