### ISSUE TITLE
Getting cv2.error

### ISSUE THREAD

**Issue by kennrippon** [opencv/opencv#22159]
![Screenshot (289)](https://user-images.githubusercontent.com/108174989/175766340-9381f087-65d0-41ba-abe7-c3b0b8dc28bb.png)
Above picture is the code and I am getting this error message which is shown below. Could anyone help me fix this issue?
![Screenshot (290)](https://user-images.githubusercontent.com/108174989/175766410-3c2735ea-3610-4762-bd44-a0f2da75880c.png)

**Comment by sturkmen72** [comment]
you should use `/ `or `\\`

```
face_cascade = cv2.CascadeClassifier("D:/downloads/haarcascade_frontalface_default.xml")
img = cv2.imread("D:/PICTURES/farewell.jpg")
```
or
```
face_cascade = cv2.CascadeClassifier("D:\\downloads\\haarcascade_frontalface_default.xml")
img = cv2.imread("D:\\PICTURES\\farewell.jpg")
```

**Comment by kennrippon** [comment]
Thankyou @sturkmen72 for your solution. It finally worked successfully without any error.

**Comment by sturkmen72** [comment]
@kennrippon you are welcome. please close the issue and use https://forum.opencv.org/ for usage questions.
