### ISSUE TITLE
Where are the build instructions for opencv 4.6

### ISSUE THREAD

**Issue by markopolo89** [opencv/opencv#22155]
Sorry, I tried signing up to https://forum.opencv.org to ask this question but did not receive an activation email.
Sorry again, if this is a stupid question but I cannot find any build instructions for opencv 4.6. Could someone advise please?

Marc

**Comment by erolrecep** [comment]
OpenCV has [tutorial for building](https://docs.opencv.org/4.6.0/db/d05/tutorial_config_reference.html) on their website.
