### ISSUE TITLE
<class 'cv2.VideoCapture'> returned a result with an error set and my camera and videos can not be read

### ISSUE THREAD

**Issue by shohoku10yyl** [opencv/opencv#22167]
import cv2

cv2.namedWindow('video', cv2.WINDOW_NORMAL)
cv2.resizeWindow('video', 640, 480)

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    cv2.imshow('video', frame)

    key = cv2.waitKey(10)
    if key & 0Xff == ord('q'):
        print('退出成功')
        break

cap.read()
cv2.destroyAllWindows()

My code is above and the error shows as follows:

D:\Python\anaconda\envs\opencv\python.exe C:/Users/yyl47/Desktop/pythonProject/test.py cv2.error: invalid stoull argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yyl47\Desktop\pythonProject\test.py", line 5, in <module>
    cap = cv2.VideoCapture(0)
SystemError: <class 'cv2.VideoCapture'> returned a result with an error set

Process finished with exit code 1
Anyone can help me?My python version is 3.9, the operating system is windows10 and it is a laptop, the camera works well in other app.

**Comment by alalek** [comment]
> anaconda

How did you get OpenCV?

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by shohoku10yyl** [comment]
>

**Comment by shohoku10yyl** [comment]
I used pip in pycharm terminal to install opencv-python and opencv-contrib-python.

**Comment by alalek** [comment]
OpenCV is not a pure Python library, it is written on C++ and it need to be properly compiled to be used in different environments.

> anaconda

You could check conda-like package from here:
https://anaconda.org/conda-forge/opencv

---

OpenCV pypi packages are tested with regular Python distributions from official Python site: https://www.python.org/downloads/

**Comment by shohoku10yyl** [comment]
Do I need to reinstall OpencV in Conda, my environment is from conda, and there has opencv-python and opencv-contrib-python, This is what Conda automatically recognized after I installed it from PyCharm.
Conda also comes with opencV-related packages: libOpencv, opencv, and py-Opencv
