### ISSUE TITLE
???

### ISSUE THREAD

**Issue by md3848** [opencv/opencv#22162]
...............

**Comment by alalek** [comment]
Please provide complete minimal reproducer **including input data**.

> QRandomGenerator

Please avoid using of 3rdparty dependencies.
Save its values (put into code directly or dump through `cv::FileStorage` and attach file).

---

You could check Subdiv2D related issue from here too: #16763

**Comment by md3848** [comment]
this is a class in qt, u can use any "random number generation function"
`#include <QRandomGenerator>`

u can use this function in c++ :
`rand()`
from this file : 
`#include <stdlib.h>`
but this function is really bad! if u know any random generator function, u can use it, but that is enough for now :)
replace the old code with this one :
**old :** 
```
for (int i=0; i<100; i++)
{
	points.push_back( cv::Point2f( QRandomGenerator::global()->bounded(0, img.cols-1),
								   QRandomGenerator::global()->bounded(0, img.rows-1) ) );
}
```
**new :** 
```
for (int i=0; i<100; i++)
{
	points.push_back( cv::Point2f(rand()&(img.cols-1), rand()&(img.rows-1)) );
}
```
