### ISSUE TITLE
cv::remap() and outliers

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#22177]
OpenCV 4.*

Currently, "outlier" pixels of a [cv::remap()](https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#gab75ef31ce5cdfb5c44b6da5f3b908ea4) can be "ignored" with the option borderMode=BORDER_TRANSPARENT

But the documentation of cv::BorderType suggests that it should rather be [BORDER_ISOLATED](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gga209f2f4869e304c82d07739337eae7c5a4fcb77ae62e1e1336c1c2b24a441995c) 

Using cv::remap() with BORDER_ISOLATED  is unsupported, though.

Could BORDER_ISOLATED be supported as an alias of BORDER_TRANSPARENT to handle outliers ?

**Comment by AryanNanda17** [comment]
According to my research, there is no direct support for BORDER_ISOLATED as an alias for BORDER_TRANSPARENT in the OpenCV library. The BORDER_ISOLATED flag is intended for border interpolation in image processing operations.

**Comment by AryanNanda17** [comment]
Check out my Pull request @asmorkalov. I did the required changes.
