### ISSUE TITLE
Yolov4-csp inference on opencv 4.6.0 provides different results to native darknet inference.

### ISSUE THREAD

**Issue by pramodwic1** [opencv/opencv#22197]
##### System information (version)

- OpenCV => 4.6.0
- Operating System / Platform => ubuntu 20.04
- Source => inference on python, opencv from pip3 install opencv-python

##### Detailed description

I have a yolov4-csp based OCR model trained from darknet (the model was trained for a short time, just for testing purposes), running inference on native darknet (https://github.com/AlexeyAB/darknet), gets acceptable results 

![darknet_inference](https://user-images.githubusercontent.com/105900664/177468957-2fb9b4d7-aa7d-4c27-8ab7-e709e8edebb0.jpg)

However running the same using opencv dnn gets results, which are quite different and not acceptable in this case.

![opencv_inference](https://user-images.githubusercontent.com/105900664/177469130-c0115bc5-9083-4238-87b5-3548d5073576.jpg)

As mentioned here (https://github.com/AlexeyAB/darknet/issues/8146#issuecomment-946251267), opencv 4.5.4 or greater should support yolov4-csp, This was why I tested it on the latest version 4.6.0.

##### Steps to reproduce

To reproduce I will provide google drive zip file with all the weights and python script for opencv inference. (https://drive.google.com/file/d/1e_JyalXZuZgunzx_GWEmGINy37xiyqpU/view?usp=sharing)
Below I will also provide the python inference script 

`
import cv2
import time

CONFIDENCE_THRESHOLD = 0.3
NMS_THRESHOLD = 0.4
COLORS = [(0, 255, 255), (255, 255, 0), (0, 255, 0), (255, 0, 0)]
print("cv2 version", cv2.__version__)
class_names = []
with open("ocr-yolov4-csp/classes.txt", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

frame = cv2.imread("ocr-yolov4-csp/test1.jpg")

net = cv2.dnn.readNet("ocr-yolov4-csp/yolov4-csp_best.weights", "ocr-yolov4-csp/yolov4-csp.cfg")
#net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
#net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA_FP16)

model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(512, 512), scale=1/255, swapRB=True)

classes, scores, boxes = model.detect(frame, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)
end = time.time()
start_drawing = time.time()
for (classid, score, box) in zip(classes, scores, boxes):
    color = COLORS[int(classid) % len(COLORS)]    
    label = "%s : %f" % (class_names[classid], score)
    cv2.rectangle(frame, box, color, 2)
    cv2.putText(frame, label, (box[0], box[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

cv2.imwrite("opencv_inference.jpg", frame)

`

##### Issue submission checklist

 - [✓] I report the issue, it's not a question

 - [✓] I checked the problem with documentation, FAQ, open issues,

 - [✓] I updated to the latest OpenCV version and the issue is still there

 - [✓] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by fengyuentau** [comment]
@pramodwic1 I doublechecked the difference between Darknet configs and your script using OpenCV DNN:

1. In your Darknet config, `letter_box` is used but not for your OpenCV DNN script. **OpenCV DNN does not parse this setting and does not performance `letter_box` transform**. `letter_box` in Darknet is padding the input image to sqaure, then resize to the specific size, 512x512 in your case Heavy effect.
2. `CONFIDENCE_THRESHOLD` in Darknet config is 0.25 (0.3 in your OpenCV DNN script). Subtle effect.
3. `NMS_THRESHOLD` in Darknet config is 0.45 (0.4 in your OpenCV DNN script). Subtle effect.

After eliminating these differences, the detected boxes are close to the ones from Darknet:
![opencv_inference_c](https://user-images.githubusercontent.com/17219438/178403895-ab8a1a88-c476-4606-9e5f-e66dc5a57ab5.jpg)

You script with my changes:
```python
import cv2
import numpy as np
import time

CONFIDENCE_THRESHOLD = 0.25
NMS_THRESHOLD = 0.45
COLORS = [(0, 255, 255), (255, 255, 0), (0, 255, 0), (255, 0, 0)]
print("cv2 version", cv2.__version__)
class_names = []
with open("ocr-yolov4-csp/classes.txt", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

img = cv2.imread("ocr-yolov4-csp/test1.jpg")
print(img.shape)

net = cv2.dnn.readNet("ocr-yolov4-csp/yolov4-csp_best.weights", "ocr-yolov4-csp/yolov4-csp.cfg")
out_names = net.getUnconnectedOutLayersNames()
print(out_names)
#net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
#net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA_FP16)

frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
frame = cv2.resize(frame, (512, 288))
frame_p = np.pad(frame, ((112, 112), (0, 0), (0, 0)), mode='constant', constant_values=127)
frame = frame_p / 255.0
frame = frame[np.newaxis, :, :, :]
frame = frame.transpose(0, 3, 1, 2)
print(frame.shape)

#classes, scores, boxes = model.detect(frame, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)
net.setInput(frame)
output_blobs = net.forward(out_names)
output_blob = np.concatenate(output_blobs, axis=0)
classes = []
scores = []
boxes = []
for det in output_blob:
    max_score = np.max(det[5:])
    if max_score < CONFIDENCE_THRESHOLD:
        continue
    scores.append(max_score)

    max_score_id = np.argmax(det[5:])
    classes.append(max_score_id)

    center_x = det[0] * 512
    center_y = det[1] * 512
    w = det[2] * 512
    h = det[3] * 512

    top_left_x = max(0, min(center_x - w / 2.0, 512 - 1))
    top_left_y = max(0, min(center_y - h / 2.0, 512 - 1))
    w = max(1, min(w, 512 - w))
    h = max(1, min(h, 512 - h))

    bottom_right_x = top_left_x + w
    bottom_right_y = top_left_y + h
    boxes.append(
            [int(top_left_x), int(top_left_y), int(bottom_right_x), int(bottom_right_y)]
    )

keep_idx = cv2.dnn.NMSBoxes(
        bboxes=boxes,
        scores=scores,
        score_threshold=CONFIDENCE_THRESHOLD,
        nms_threshold=NMS_THRESHOLD)
boxes_np = np.array(boxes)[keep_idx]

for (classid, score, box) in zip(classes, scores, boxes_np):
    print(box)
    color = COLORS[int(classid) % len(COLORS)]
    label = "%s : %f" % (class_names[classid], score)
    cv2.rectangle(frame_p, (box[0], box[1]), (box[2], box[3]), color, 2)
    cv2.putText(frame_p, label, (box[0], box[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

cv2.imwrite("opencv_inference_c.jpg", frame_p)

```

**Comment by pramodwic1** [comment]
@fengyuentau Thanks for the update, as you mention I too believe `letterbox` is the cause for the difference. 
Running this code fixes the detection issue, however the class ID prediction is still not correct. For instance the very first "2" is being predicted as "7", while inference on darknet predicts it correctly.

**Comment by fengyuentau** [comment]
@pramodwic1 Add the following lines to have correct labels and scores:
```.diff
keep_idx = cv2.dnn.NMSBoxes(
        bboxes=boxes,
        scores=scores,
        score_threshold=CONFIDENCE_THRESHOLD,
        nms_threshold=NMS_THRESHOLD)
boxes_np = np.array(boxes)[keep_idx]
+classes = np.array(classes)[keep_idx]
+scores = np.array(scores)[keep_idx]
```
