### ISSUE TITLE
Issue in OpenCV DNN when reading network with Upsample2D with interpolation "bilinear"

### ISSUE THREAD

**Issue by Tigran1983** [opencv/opencv#22195]
##### System information (version)
- OpenCV => 4.6:
- Operating System / Platform => Ubuntu 21.04:
- Compiler => :grey_question:

##### Detailed description

Dear Team, I have a model in keras, which converted to ONNX then I am getting en error, when loading ONNX by Opencv DNN.
I opened an issue on OpenCVForUnity, they tested, and reported issue:

dnn::readNet_12() : OpenCV(4.6.0-dev) C:\Users\satoo\Desktop\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Upsample@ai.onnx]:(onnx_node!Upsample__81) parse error: OpenCV(4.6.0-dev) C:\Users\satoo\Desktop\opencv\modules\dnn\src\layers\resize_layer.cpp:48: error: (-2:Unspecified error) in function '__cdecl cv::dnn::ResizeLayerImpl::ResizeLayerImpl(const class cv::dnn::dnn4_v20220524::LayerParams &)'
> > :
> >     'interpolation == "nearest" || interpolation == "opencv_linear" || interpolation == "bilinear"'
> > where
> >     'interpolation' is linear
> 

I asked on Opencv Forum, because as I can see, Opencv Dnn supports Upsample2D with interpolation="bilinear", people couldn't help with. So as I guess, maybe there are a problem in UpSampling2D.
I am attached my model in H5 and ONNX. Please check and let me know what is a problem in my network.
Best Regards,
Tigran

##### Steps to reproduce

Attached is 
[model_ONNX.zip](https://github.com/opencv/opencv/files/9044810/model_ONNX.zip)
[model_H5.zip](https://github.com/opencv/opencv/files/9044814/model_H5.zip)

**Comment by Tigran1983** [comment]
In Opencv forum guys checked and fixed that ONNX changes interpolation from "bilinear" to "linear", so problem is in it, which is not supported by OpenCV. Are there any ideas, why taking place this change? And how avoid it?

**Comment by zihaomu** [comment]
Hi @Tigran1983, thanks for your bug report. I'm fixing it now.

**Comment by zihaomu** [comment]
Hi, @Tigran1983. For now you can try to use the [PR's code](https://github.com/opencv/opencv/pull/22199).

**Comment by Tigran1983** [comment]
Many thanks @zihaomu for your fastest response, but I am working in unity. That's very good to fix issue in OpenCV, but it have to be in OpenCVForUnity. So fix doen't help me in my work. I have trained model in keras H5 format, now I cannot use converted ONNX in OpenCVForUnity, also converted TF model doesn't work. So I don't know how can I use my model in Unity.
Per my understanding, I have no any way to use this model in Unity with OpenCVForUnity.

Thanks for your job.

**Comment by crackwitz** [comment]
I think you could mess around in the .h5 file and patch the string value in the network to be what OpenCV expects, which was `nearest`, `bilinear`, `opencv_linear` (wouldn't recommend that in the model file though)

here's something that looks superficially related to such an operation: https://stackoverflow.com/questions/46121210/how-to-edit-h5-files-with-h5py

**Comment by berak** [comment]
hello, @zihaomu , thanks for your fast response, can you explain, how your pr solves the issue ?
remember, there were 2 problems:
1. the onnx *exporter* makes a `Resize` node from anthing that looks like it (Upsample, F.interpolate, etc). and it changed the interpolation mode from required `bilinear` to `linear` under the hood. (if it would keep bilinear, everthing in opencv would be fine.) however, there's nothing we can do about it from here, exept raising an issue with onnx
2. opencv's dnn onnx *importer* only knows `nearest, opencv_linear, bilinear` modes, [if it's a ptorch model, the flag will get translated](https://github.com/opencv/opencv/blob/a80fcacd90dec4b2a25faf8363811bc6566b80cd/modules/dnn/src/onnx/onnx_importer.cpp#L3145) from `linear` to `opencv_linear`, but not so, when coming from keras here (which is something, we should fix, imo)

**Comment by zihaomu** [comment]
> * 
> * opencv's dnn onnx _importer_ only knows `nearest, opencv_linear, bilinear` Resize modes, [if it's a ptorch model, the flag will get translated](https://github.com/opencv/opencv/blob/a80fcacd90dec4b2a25faf8363811bc6566b80cd/modules/dnn/src/onnx/onnx_importer.cpp#L3086) from `linear` to `opencv_linear`, but not so, when coming from keras here (which is something, we should fix, imo)

Hi @berak, `Resize` layer of `ONNX_importer` works well on my side. I am not sure if I am correct. And I just check the detail of `ONNX_inporter.cpp`, and I found the following code used to handle the `linear` type at `parseResize`:
```c++
    if (layerParams.get<String>("mode") == "linear")
    {
        layerParams.set("mode", interp_mode == "pytorch_half_pixel" || interp_mode == "half_pixel" ?
                                "opencv_linear" : "bilinear");
    }
```
I'm not sure 
And I found there are some more issues that will cause the model can't be loaded correctly (ReduceSum layer with two input and a bug at `parseMul`). And that's why I created that PR #22199.
