### ISSUE TITLE
When support to YOLO v7?

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#22215]
- OpenCV => 4.6.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
-->

- Compiler => :grey_question:

##### Detailed description

How support to YOLOv7 by onnx format?

https://github.com/WongKinYiu/yolov7

**Comment by fengyuentau** [comment]
Can you try loading the model and doing inference with OpenCV?

**Comment by prateekgml** [comment]
@fengyuentau I tried and got below error:
`error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:554: error: (-212:Parsing error) Unsupported activation: logistic in function 'ReadDarknetFromCfgStream'`

I have used the official weight and config file as mentioned in [https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7-tiny.weights](url) and [https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov7-tiny.cfg](url)

Code snippet to load the model was `net = cv2.dnn.readNet('/content/gdrive/MyDrive/yolov7/yolov7-obj.cfg', '/content/gdrive/MyDrive/yolov7/weights/yolov7-obj_final.weights')`

Opencv version in Colab is 4.1.2

**Comment by fengyuentau** [comment]
Try with latest OpenCV. Logistic activation (also called Sigmoid) has been supported.

**Comment by fengyuentau** [comment]
> Now yolov7 project no support export to onnx format

Submit a issue in yolov7 repo to ask for the onnx model or try yourself. Figure out the problem then reopen issue.

**Comment by wwzh2015** [comment]
> Submit

I just try inference yolov5s.onnx by opencv4.6, but the opencv 4.6 don't rectangle box? 

But the opencv 4.5.5 is normal.

That is inference API have changed about opencv4.6?

**Comment by berak** [comment]
tried with  model/code [from here](https://github.com/WongKinYiu/yolov7)  on colab:
```
!git clone https://github.com/WongKinYiu/yolov7
%cd yolov7
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

from models.experimental import attempt_load
model = attempt_load("yolov7.pt", map_location="cpu")  # load FP32 model
model.eval()

import torch
torch.onnx.export(model, 
                 torch.randn(1,3,640,640),
                 "yolov7.onnx", verbose=False, input_names=['input'], output_names=['output'])

import cv2
print(cv2.__version__)
nn = cv2.dnn.readNet("yolov7.onnx")
```

```
4.6.0

---------------------------------------------------------------------------

error                                     Traceback (most recent call last)

[<ipython-input-2-0b620062fa4c>](https://localhost:8080/#) in <module>()
      3 print(cv2.__version__)
      4 
----> 5 nn = cv2.dnn.readNet("yolov7.onnx")

error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'getMemoryShapes'
> 
```

**Comment by fengyuentau** [comment]
Thank you @berak . This guy managed to load and infer yolov7 with OpenCV somehow: https://github.com/hpc203/yolov7-opencv-onnxrun-cpp-py. But let me take a look at the problem.

**Comment by berak** [comment]
@wwzh2015 
> Now yolov7 project no support export to onnx format

it does ! https://github.com/WongKinYiu/yolov7/blob/main/models/export.py

**Comment by fengyuentau** [comment]
> tried with model/code [from here](https://github.com/WongKinYiu/yolov7) on colab:
> 
> ```
> !git clone https://github.com/WongKinYiu/yolov7
> %cd yolov7
> !wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
> 
> from models.experimental import attempt_load
> model = attempt_load("yolov7.pt", map_location="cpu")  # load FP32 model
> model.eval()
> 
> import torch
> torch.onnx.export(model, 
>                  torch.randn(1,3,640,640),
>                  "yolov7.onnx", verbose=False, input_names=['input'], output_names=['output'])
> 
> import cv2
> nn = cv2.dnn.readNet("yolov7.onnx")
> ```
> 
> ```
> error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> > Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'getMemoryShapes'
> > 
> ```

To get the yolov7 onnx of dynamic input shape supported, some operators need to be changed and supported. Let me do some explorations here.

**Comment by liuwei688** [comment]
ALL RIGHT
