### ISSUE TITLE
load onnx file(efficientnet-pytorch) in opencv 4.5.4 occur error below

### ISSUE THREAD

**Issue by dmjeong** [opencv/opencv#22237]
env
- OpenCV => 4.5.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- efficientnet-pytorch convert to onnx

i try to import onnx file that convert from efficientnet-pytorch model, but when i read i got error below

\opencv\opencv-4.5.4\modules\dnn\src\onnx\onnx_importer.cpp:739: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211004::ONNXImporter::handleNode'
> Node [Identity]:(onnx::Concat_1288) parse error: OpenCV(4.5.4) opencv\opencv-4.5.4\modules\dnn\src\dnn.cpp:5653: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211004::Layer::getMemoryShapes'

    model_name = 'efficientnet-b0'  # b0
    model = EfficientNet.from_pretrained(model_name, num_classes=2)
    model.load_state_dict(torch.load('model.pt'))
    model.eval()
    model.set_swish(memory_efficient=False)
    # Dummy input for ONNX
    dummy_input = torch.randn(2, 3, 224, 224)
    torch.onnx.export(model, dummy_input, "b0.onnx", verbose=True) <-- code in python convert to onnx

auto model = readNetFromONNX("E:\\b0.onnx"); <-- this is my code c++

i search lots of time for this error to solve

but i can't please help me

thank you

**Comment by fengyuentau** [comment]
Could you provide your model for us to reproduce your issue?

**Comment by dmjeong** [comment]
please check my github repository

thank you
