### ISSUE TITLE
Filter2D doesn't support CV_32F/CV_64F(input/output) while documentation says it should

### ISSUE THREAD

**Issue by vakokako** [opencv/opencv#22242]
##### System information (version)
- OpenCV => 4.5.5
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => clang 14.0.6

##### Detailed description

`cv::filter2D` throws if input is `CV_32F` and output is `CV_64F`, while in the [documentation](https://docs.opencv.org/4.5.5/d4/d86/group__imgproc__filter.html#filter_depths) it says that it should be supported.

##### Steps to reproduce

```.cpp
auto input = ::cv::Mat(5, 5, CV_32F, 2);
auto kernel = ::cv::Mat(3, 3, CV_32F, 1);
auto output = ::cv::Mat(5, 5, CV_64F, 2);
::cv::filter2D(input, output, output.depth(), kernel);
```
It throws the following exception:
```
OpenCV(4.5.5) Error: The function/feature is not implemented (Unsupported combination of source format (=5), and destination format (=6)) in getLinearFilter, file /path_to_opencv/modules/imgproc/src/filter.simd.hpp, line 3297
```

**Comment by catree** [comment]
Documentation to be updated.
See the reason for this: https://github.com/opencv/opencv/pull/22256#discussion_r922637058
