### ISSUE TITLE
imshow() for .png transparent images with RGBA 4 channels

### ISSUE THREAD

**Issue by jiapei-nexera** [opencv/opencv#22251]
Looks like **imshow()** cannot show transparency correctly ?
I prefer **NOT** to show RGB some times, with alpha mask, how can I make the transparency displayed?
I can load, I can save, but with imshow(), I cannot display correctly....

**Comment by kallaballa** [comment]
check this out: https://learnopencv.com/alpha-blending-using-opencv-cpp-python/
It's called alpha blending
