### ISSUE TITLE
Error: Null pointer (NULL window: 'Test Program') in cvGetPropWindowAutoSize_W32

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#22263]
##### System information (version)

- OpenCV => 4.5
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

When I take WindowPropertyFlags that no work after opencv 4.5, but is normal work in opencv4.4.

Tips:Error: Null pointer (NULL window: 'Test Program') in cvGetPropWindowAutoSize_W32

Example Code:
```
#include <opencv2/opencv.hpp>
#include <iostream>
#include <opencv2/highgui/highgui_c.h>

using namespace cv;
using namespace std;

int main()
{
	VideoCapture capture(0);   

	while(1)
    {
		Mat frame;
		capture >> frame;
		if(frame.empty())
			break;
        namedWindow("Test Program",WINDOW_AUTOSIZE); 
		imshow("Test Program",frame);   
		waitKey(30); 

        if( getWindowProperty("Test Program",WND_PROP_AUTOSIZE) != 1)
            break;
     }
    capture.release();
    destroyAllWindows();
    return 0;
}
```

**Comment by vovka643** [comment]
OpenCV: 4.x
Platform: Windows 8.1, 64 Bit
Compiler: Visual Studio 2017

Everything work fine. I compiled and executed exactly your code. 
Log: 
`[ INFO:0@0.770] global videoio_registry.cpp:232 cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(9, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940); UEYE(930); OBSENSOR(920)
[ INFO:0@0.946] global backend_plugin.cpp:383 cv::impl::getPluginCandidates Found 2 plugin(s) for GSTREAMER
[ INFO:0@0.947] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_videoio_gstreamer470_64d.dll => FAILED
[ INFO:0@0.949] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_videoio_gstreamer470_64d.dll => FAILED
[ INFO:0@1.146] global cap_msmf.cpp:1027 CvCapture_MSMF::configureHW MSMF: Using D3D11 video acceleration on GPU device: Intel(R) HD Graphics 4600
[ INFO:0@4.833] global registry_parallel.impl.hpp:96 cv::parallel::ParallelBackendRegistry::ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
[ INFO:0@4.867] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@4.869] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@4.869] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@4.870] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@4.870] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_core_parallel_openmp470_64d.dll => FAILED
[ INFO:0@4.872] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED
[ INFO:0@4.994] global registry.impl.hpp:114 cv::highgui_backend::UIBackendRegistry::UIBackendRegistry UI: Enabled backends(4, sorted by priority): GTK(1000); GTK3(990); GTK2(980); WIN32(970) + BUILTIN(WIN32UI)
[ INFO:0@4.996] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_highgui_gtk470_64.dll => FAILED
[ INFO:0@4.999] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk470_64.dll => FAILED
[ INFO:0@5.000] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_highgui_gtk3470_64.dll => FAILED
[ INFO:0@5.003] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk3470_64.dll => FAILED
[ INFO:0@5.005] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\work\CMakeBuilds\5d179d0e-b7e1-da30-8c00-174fedca3d36\build\x64-Debug\bin\opencv_highgui_gtk2470_64.dll => FAILED
[ INFO:0@5.010] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk2470_64.dll => FAILED
[ INFO:0@5.011] global backend.cpp:90 cv::highgui_backend::createUIBackend UI: using backend: WIN32 (priority=970)
[ INFO:0@5.012] global window_w32.cpp:3008 cv::impl::Win32BackendUI::createWindow OpenCV/UI: Creating Win32UI window: Test Program (1)`

**Comment by greffgreff** [comment]
I think to reproduce OP's issue the window needs to be closed once. I am getting this error when closing the window and when the program attempts to reopen a new window
