### ISSUE TITLE
Integer Overflow in `openjpeg/openjp2/image.c`

### ISSUE THREAD

**Issue by kobrineli** [opencv/opencv#22284]
##### System information (version)

- OpenCV version => a42b35598e2543d6dab3ac73be92fb77742e0747 (4.x)
- Operating System => Ubuntu 20.04
- Compiler => clang-14

##### Detailed description

Hi! We've been fuzzing your project and found integer overflow error in your 3d party project openjpeg in `opencv/3rdparty/openjpeg/openjp2/image.c:134`:

    l_y1 = p_cp->ty0 + (p_cp->th - 1U) * p_cp->tdy; /* can't overflow */

Overflow occurs both in addition and multiplication operations. Comment says overflow cannot occur, but actually it can.

##### Steps to reproduce

1. Build docker container from here: https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/opencv

        sudo docker build -t oss-sydr-fuzz-opencv .

2. Run docker container:

        sudo docker run --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-opencv /bin/bash

3. Run `imdecode_fuzzer` target on pinned input 
[sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt](https://github.com/opencv/opencv/files/9168316/sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt)

        /out/imdecode_fuzzer /fuzz/imdecode-out/security-verified/sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned

4. You will see following sanitizer output:

        /opencv/3rdparty/openjpeg/openjp2/image.c:134:40: runtime error: unsigned integer overflow: 2 * 4278190076 cannot be represented in type 'unsigned int'
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opencv/3rdparty/openjpeg/openjp2/image.c:134:40 in 
        /opencv/3rdparty/openjpeg/openjp2/image.c:134:22: runtime error: unsigned integer overflow: 50331631 + 4261412856 cannot be represented in type 'unsigned int'
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opencv/3rdparty/openjpeg/openjp2/image.c:134:22 in

**Comment by alalek** [comment]
Thank you for the report!

BTW, It makes sense to check (and report to) the upstream project: https://github.com/uclouvain/openjpeg

**Comment by boxerab** [comment]
@kobrineli are you able to provide a test j2k image that reproduces this problem ?

**Comment by kobrineli** [comment]
@boxerab actually [sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt](https://github.com/opencv/opencv/files/9168316/sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt) is not txt but j2k image.
Here is code, that reads it: https://github.com/ispras/oss-sydr-fuzz/blob/master/projects/opencv/imdecode_fuzzer.cc#L10

**Comment by boxerab** [comment]
Ahhh, gotcha. Thanks.

**Comment by asmorkalov** [comment]
The issue has been fixed in OpenJPEG. let's wait for release on their side to update 3rdparty.
