### ISSUE TITLE
Input size not specified in function 'processFrame'

### ISSUE THREAD

**Issue by xnzdev** [opencv/opencv#22345]
pencv-python/opencv-python/opencv/modules/dnn/src/model.cpp:98: error: (-201:Incorrect size of input array) Input size not specified in function 'processFrame'

##### System information (version)

- OpenCV => opencv-python   4.6.0.66
- Operating System / Platform => Mac OS 
- Compiler => Python 3.9.13

##### Detailed description
```
im = cv.imread(src123)
DB_TD500_resnet50 = "./pre-trained_models/DB_TD500_resnet50.onnx"

detector = dnn.TextDetectionModel_DB(DB_TD500_resnet50)
detector.setBinaryThreshold(0.3)   
detector.setPolygonThreshold(0.5)  
detector.setUnclipRatio(2.0)      
detector.setMaxCandidates(200)    

detections = detector.detect(im)   # error: (-201:Incorrect size of input array) Input size not specified in function 'processFrame'
```

**Comment by berak** [comment]
this is not a library bug, and questions like this should better go to https://forum.opencv.org/

however, have another look at the resp. tutorial at:
https://docs.opencv.org/4.x/d4/d43/tutorial_dnn_text_spotting.html

you should a line like:  `detector.setInputParams(scale, inputSize, mean);`

**Comment by fengyuentau** [comment]
We have a demo for DB in opencv zoo: https://github.com/opencv/opencv_zoo/blob/2269c87e96a06ed3851ce03185a961179d7fd3e5/models/text_detection_db/db.py#L11-L35
