### ISSUE TITLE
Can't create layer "Range_404" of type "Range" in function 'getLayerInstance'

### ISSUE THREAD

**Issue by Nuwan1654** [opencv/opencv#22361]
# System information (version)
- OpenCV = 4.5.5.dev
- torch = 1.6.0

# Steps to reproduce
net = cv2.dnn.readNetFromONNX(onnx_path)

# Issue

I am getting the following error. when I updated the PyTorch to the latest version like 1.12.0 I am getting a new error `(-215:Assertion failed) inputs.size() in function 'getMemoryShapes'` .  Any help on this would be appreciated. 

`cv2.error: OpenCV(4.5.5-dev) /home/nsight/YOLOX/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1021: error: (-2:Unspecified error) in function 'handleNode'
> Node [Range@ai.onnx]:(Range_404) parse error: OpenCV(4.5.5-dev) /home/nsight/YOLOX/opencv/modules/dnn/src/layer_internals.hpp:110: error: (-2:Unspecified error) Can't create layer "Range_404" of type "Range" in function 'getLayerInstance'
`
Here is a snapshot of layer 404 in ONNX [graph](https://drive.google.com/file/d/1OtCxb3kP_cBmh5Geb3vWl4Tn2TKND-Vj/view?usp=sharing)

**Comment by zihaomu** [comment]
`Range` layer is unsupported on OpenCV at present. I will try to support.

**Comment by asmorkalov** [comment]
Duplicate https://github.com/opencv/opencv/issues/20324

**Comment by fengyuentau** [comment]
If this model has fixed input shape, which means the input of Range operator is constant, the Range operator is supported in #22290.

**Comment by fengyuentau** [comment]
Hello @Nuwan1654 , can you kindly provide your model for me to have a test whether my pull request handles Range layer properly?

**Comment by ukoehler** [comment]
https://github.com/opencv/opencv/pull/22290 was merged 7 days ago. However, I still get the same error message for a different model after updating Python rolling version `pip install opencv-python-rolling --upgrade`

I am on version: `Successfully installed opencv-python-rolling-5.0.0.20220924`

**Comment by fengyuentau** [comment]
@ukoehler `pip install opencv-python-rolling` this command installs opencv5 by default. The PR was for 4.x, and changes need to be ported to 5.x manually. You will need to install `opencv-python-rolling==4.6.0.20220924` instead (https://pypi.org/project/opencv-python-rolling/4.6.0.20220924/).

Hello @asmorkalov @asenyaev , I observed that `pip install opencv-python-rolling` installs opencv5 by default, which is not convenient for users to try out new features on 4.x. Could we make it install latest 4.x by default?

**Comment by ukoehler** [comment]
Hmmm, I'm intrigued. When I check out the most up-to-date state of the source code to compile myself, with feature set will I get? Both 5.0 and 4.6? Can I look that up somewhere?

**Comment by fengyuentau** [comment]
Default branch is 4.x. You can check it with `git branch`.

**Comment by ukoehler** [comment]
Confirmed that the problem does not persist with  opencv-python-rolling-4.6.0.20220924.

**Comment by asenyaev** [comment]
Hi @fengyuentau! The installation using `pip` usually installs the latest highest version of a package. Users can install the latest rolling package for 4.x branch using a following command: `python3 -m pip install "opencv-python-rolling<5.0"`

**Comment by fengyuentau** [comment]
Thank you @asenyaev !
