### ISSUE TITLE
cv2.dnn.readNetFromONNX(modelWeights) error

### ISSUE THREAD

**Issue by dengmingD** [opencv/opencv#22384]
env:
onnx 1.12.0
onnx-simplifier 0.3.10
onnxoptimizer 0.2.7
onnxruntime 1.12.0
onnxruntime-gpu 1.12.0

paddle-parakeet 0.0.0
paddle-serving-app 0.7.0
paddle-serving-client 0.7.0
paddle-serving-server-gpu 0.7.0.post1028
paddle2onnx 0.9.8
paddleaudio 0.1.0a0
paddledet 2.3.0
paddlehub 2.2.0
paddlenlp 2.2.3
paddleocr 2.5
paddlepaddle 2.2.1
paddlepaddle-gpu 2.2.1.post112
paddlespeech 0.1.0a0
paddlespeech-feat 0.1.0

opencv-python 4.6.0.66
opencv-contrib-python 4.6.0.66

**model.onnx on onnxontime is ok, on opencv dnn is not ok**
model_PP-OCRv3_rec_infer.zip uploaded!!

D:\work\apps\Anaconda3\python.exe D:/work/projects/learnopencv/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python/yolov5.py
[ERROR:0@0.030] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1021) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(onnx_node!Clip_0) from domain='ai.onnx'
Traceback (most recent call last):
File "D:/work/projects/learnopencv/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python/yolov5.py", line 124, in
net = cv2.dnn.readNetFromONNX(modelWeights)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'

    Node [[Clip@ai.onnx](mailto:Clip@ai.onnx)]:(onnx_node!Clip_0) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1934: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20220524::ONNXImporter::parseClip(class cv::dnn::dnn4_v20220524::LayerParams &,const class opencv_onnx::NodeProto &)'

        (expected: 'node_proto.input_size() == 1'), where
        'node_proto.input_size()' is 3
        must be equal to
        '1' is 
1

**Comment by zihaomu** [comment]
Hi @dengmingD. Please re-attach the model, the zip file looks wrong.

**Comment by dengmingD** [comment]
[model_PP-OCRv3_rec_infer.zip](https://github.com/opencv/opencv/files/9336150/model_PP-OCRv3_rec_infer.zip)

**Comment by dengmingD** [comment]
> Hi @dengmingD. Please re-attach the model, the zip file looks wrong.

uploaded

**Comment by zihaomu** [comment]
Hi @dengmingD, PP-OCRv3 works fine on my site. And PP-OCRv3 does not has `Clip` layer, looks like you attached wrong model file.
BTW, we have supported `clip layer` with three input #22100, please use the lastest OpenCV.
For python, you can try `pip install opencv-python-rolling`.

**Comment by dengmingD** [comment]
> Hi @dengmingD, PP-OCRv3 works fine on my site. And PP-OCRv3 does not has `Clip` layer, looks like you attached wrong model file. BTW, we have supported `clip layer` with three input #22100, please use the lastest OpenCV. For python, you can try `pip install opencv-python-rolling`.

would you upload your PP-OCRv3_rec_infer.onnx please ,thanks

**Comment by dengmingD** [comment]
this is paddleocr offical onnx model
[Uploading ch_PP-OCRv3_rec_infer.zip…]()

**Comment by zihaomu** [comment]
> 
> 
> 
> > Hi @dengmingD, PP-OCRv3 works fine on my site. And PP-OCRv3 does not has `Clip` layer, looks like you attached wrong model file. BTW, we have supported `clip layer` with three input #22100, please use the lastest OpenCV. For python, you can try `pip install opencv-python-rolling`.
> 
> would you upload your PP-OCRv3_rec_infer.onnx please ,thanks

Nothing was changed. It's the same as your attached onnx.

**Comment by ukoehler** [comment]
I converted a model to ONNX and tried to load it with OpenCV 5.6 Windows 10 (Python) and got the same error message. Find the model here:
https://drive.google.com/file/d/15wdXCiS1Yr7a4wFTUb7jQB_GjbkB_a-G/view?usp=sharing
Original model from here: https://github.com/clovaai/rexnet

**Comment by zihaomu** [comment]
Hi @ukoehler, please use the latest OpenCV source code. For python, you can try `pip install opencv-python-rolling`(don't forget to uninstall the old `opencv-python`).

**Comment by ukoehler** [comment]
Hi @zihaomu, I tried to get the most up-to-date version using pip install ... --pre. Google doesn't find anything for opencv-python-rolling.

After installing the rolling version, I got a different error. Investigating further ...

**Comment by zihaomu** [comment]
Please check this link for installing the right rolling version. https://pypi.org/project/opencv-python-rolling/4.6.0.20220917/

**Comment by ukoehler** [comment]
Hi @zihaomu, many thanks for the link. The page, however, does not contain any reference to opencv-python-rolling other than the title. Do you know how the contact the authors?

**Comment by asmorkalov** [comment]
OpenCV-Python-Rolling is weekly build of OpenCV-Python. Please try the last package with version 4.6.0.x. https://pypi.org/project/opencv-python-rolling/

**Comment by asmorkalov** [comment]
@zihaomu @ukoehler please let me know, if the issue could be closed.

**Comment by dengmingD** [comment]
yes ,you can close it. thank u very march!!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opencv/opencv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opencv/opencv] cv2.dnn.readNetFromONNX(modelWeights) error (Issue #22384)





 
@zihaomu @ukoehler please let me know, if the issue could be closed.

**Comment by ukoehler** [comment]
Verified for opencv-python-rolling 4.6.0.20221112

**Comment by stereomatchingkiss** [comment]
> model_PP-OCRv3_rec_infer.zip

Do you have the tutorials about how to convert the models? Thanks
