### ISSUE TITLE
decoding Tiff file issue (-215:Assertion failed)

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#22388]
ref : [forum.opencv.org question](https://forum.opencv.org/t/imread-return-empty-matrix/9873)

i can open the referenced file when i remove the line https://github.com/opencv/opencv/blob/4.x/modules/imgcodecs/src/grfmt_tiff.cpp#L663
`CV_Assert(((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte)) < MAX_TILE_SIZE) && "TIFF tile size is too large: >= 1Gb");`

**Comment by Kumataro** [comment]
> I tried to come back to OpenCvSharp3 : ok.

I think you use https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/ . It uses very old OpenCV codes.

```
4.0.0.20181129	426,623	2018/11/29	
3.4.4.20181118	74,439	2018/11/18	
3.4.1.20181108	32,920	2018/11/09
```

### OpenCV 3.4.4
https://github.com/opencv/opencv/blob/3.4.4/modules/imgcodecs/src/grfmt_tiff.cpp#L341
-> There are no size-check code.

### OpenCV 4.x
https://github.com/opencv/opencv/blob/4.x/modules/imgcodecs/src/grfmt_tiff.cpp#L637
-> There is size-check code.

So if you try to use latest OpenCvSharp4 ( https://www.nuget.org/packages/OpenCvSharp4/ ), behaviors are different. 

### commit

This size-check code is from https://github.com/opencv/opencv/commit/25247b9f6e5e550868262b7611a9e575c1f7212a

```
imgcodecs(tiff): update tile size checks
oss-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14185
oss-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14321
```

So I think this patch is needed to avoid crush.

**Comment by sturkmen72** [comment]
related issue : https://github.com/opencv/opencv/issues/17054

**Comment by Goczilla** [comment]
@Kumataro it works with the old OpenCvSharp3-AnyCpu but not with the latest OpenCvSharp4.Windows and its friend (runtime, Extension, ...). I tried also using your code line to install the package through the console but still the same result. It is when I updated from oldder to newer wrapper than the issue appered. Regards

**Comment by Kumataro** [comment]
I said only "this image size checking code is requested to avoid crush your program". 

(I believe I didn't show how to install something to fix it. )

**Comment by Kumataro** [comment]
The point of problem becomes clearly, thank you very much. 

Before to consider about memory limitation, as an temporary fix, moving CV_Assert() relaxes this limitation.

## TIFF tile size doesn't equal to buffer_size.

For example, I tried to make tiff file with following parameters. Raw Image size is nearly 1GB.

```c++
    const int bmp_ncn    = 3;
    const int bmp_bpp    = 48;
    const int bmp_width  = 32768;
    const int bmp_height = 5462; // 5461 is OK, 5462 is NG.

    /**
     * 32768 x 5461 x 3ch x 2byte = 1,073,676,288.
     * 1024 * 1024 * 1024         = 1,073,741,824.
     * 32768 x 5462 x 3ch x 2byte = 1,073,872,896.
     */
```

Output tiff image is here.

```bash
$ tiffinfo output.tif
TIFF Directory at offset 0x788794 (c093a)
  Image Width: 32768 Image Length: 5462
  Bits/Sample: 16
  Compression Scheme: LZW
  Photometric Interpretation: RGB color
  FillOrder: msb-to-lsb
  Samples/Pixel: 3
  Rows/Strip: 5462
  Planar Configuration: single image plane
```

And I add some logs in imgcodecs module.

```C++
            CV_CheckLE((int)ncn, 4, "");
            CV_CheckLE((int)bpp, 64, "");
std::cout << "tile_width0 = " << tile_width0 << std::endl;
std::cout << "tile_height0 = " << tile_height0 << std::endl;
std::cout << "ncn = " << ncn << std::endl;
std::cout << "(int)(bpp / bitsPerByte) = " << (int)(bpp / bitsPerByte) << std::endl;
std::cout << "TIFF tile size = " << ((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte))) << std::endl;
            // CV_Assert(((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte)) < MAX_TILE_SIZE) && "TIFF tile size is too large: >= 1Gb");
            if (dst_bpp == 8)
            {
                // we will use TIFFReadRGBA* functions, so allocate temporary buffer for 32bit RGBA
                bpp = 8;
                ncn = 4;
            }
            else if (dst_bpp == 32 || dst_bpp == 64)
            {
                CV_Assert(ncn == img.channels());
                CV_TIFF_CHECK_CALL(TIFFSetField(tif, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_IEEEFP));
            }
            const size_t buffer_size = (bpp / bitsPerByte) * ncn * tile_height0 * tile_width0;
std::cout << "buffer_size = " << buffer_size << std::endl;
            AutoBuffer<uchar> _buffer(buffer_size);
            uchar* buffer = _buffer.data();
            ushort* buffer16 = (ushort*)buffer;
            int tileidx = 0;
```

Result is here. (test code is call imread("Output.tif") only ).

```bash
$ ./a.out
tile_width0 = 32768
tile_height0 = 5462
ncn = 3
(int)(bpp / bitsPerByte) = 2
TIFF tile size = 1073872896
buffer_size = 715915264
```

In this case. 48bit RGB Image is converted to 32bit RGBA Image in `TIFFReadRGBAStrip()` via libtiff.  So `buffer_size` is smaller than `TIFF tile size`  about -25%. 

>                // we will use TIFFReadRGBA* functions, so allocate temporary buffer for 32bit RGBA
>                bpp = 8;
>                ncn = 4;

Like this phenomenon, 24bit RGB Image is converted to 32bit RGBA Image too. So `buffer_size` is larger than `TIFF tile size`  about +33%.

```
$ ./a.out
tile_width0 = 32768
tile_height0 = 10924
ncn = 3
(int)(bpp / bitsPerByte) = 1
TIFF tile size = 1073872896
buffer_size = 1431830528
```

So I believe this CV_Assert() is not good to prevent over memory allocation completely.

## How to fix ( temporary )

I think moving CV_Assert() is better.

```c++
            const uint64_t MAX_TILE_SIZE = (CV_BIG_UINT(1) << 30);
            CV_CheckLE((int)ncn, 4, "");
            CV_CheckLE((int)bpp, 64, "");
-           CV_Assert(((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte)) < MAX_TILE_SIZE) && "TIFF tile size is too large: >= 1Gb");

            const size_t buffer_size = (bpp / bitsPerByte) * ncn * tile_height0 * tile_width0;
+            CV_Assert( buffer_size < MAX_TILE_SIZE) && "buffer_size is too large: >= 1Gb");
            AutoBuffer<uchar> _buffer(buffer_size);
            uchar* buffer = _buffer.data();
            ushort* buffer16 = (ushort*)buffer;

```

## Sample code to generate tiff image.

<details>
<summary>Click here to expand sample code to gemerate tiff file</summary>

Any error handling are ommited.

```c++:createTiff.cpp
// g++ main_createTiff.cpp -o createTiff `pkg-config libtiff-4 --cflags --libs`

#include <tiffio.h>
#include <cstring>

int main( void )
{
    const int bmp_ncn    = 3;
    const int bmp_bpp    = 48;
    const int bmp_width  = 32768;
    const int bmp_height = 5462; // 5461 is OK, 5462 is NG.

    /**
     * 32768 x 5461 x 3ch x 2byte = 1,073,676,288.
     * 1024 * 1024 * 1024         = 1,073,741,824.
     * 32768 x 5462 x 3ch x 2byte = 1,073,872,896.
     */
    TIFF* tif = TIFFOpen("output.tif", "w");
    TIFFSetField(tif, TIFFTAG_COMPRESSION, COMPRESSION_LZW);
    TIFFSetField(tif, TIFFTAG_IMAGEWIDTH,  bmp_width);
    TIFFSetField(tif, TIFFTAG_IMAGELENGTH, bmp_height);
    TIFFSetField(tif, TIFFTAG_BITSPERSAMPLE, bmp_bpp / bmp_ncn);
    TIFFSetField(tif, TIFFTAG_SAMPLESPERPIXEL, bmp_ncn);
    TIFFSetField(tif, TIFFTAG_PHOTOMETRIC, PHOTOMETRIC_RGB);
    TIFFSetField(tif, TIFFTAG_PLANARCONFIG, PLANARCONFIG_CONTIG);
    TIFFSetField(tif, TIFFTAG_FILLORDER, FILLORDER_MSB2LSB);
    TIFFSetField(tif, TIFFTAG_ROWSPERSTRIP, bmp_height );

    char* line_buf = new char [ bmp_width * ( bmp_bpp / 8 ) ];
    memset ( line_buf, 0 , sizeof line_buf );
    for ( int row = 0 ; row < bmp_height ; row++ )
    {
        TIFFWriteScanline(tif, line_buf, row );
    }
    TIFFClose(tif);

    delete []line_buf;
    return 0;
}
```
</details>
