### ISSUE TITLE
DNN work is so slowly

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#22381]
##### Detailed description

为什么opencv dnn模块推理这么慢？openvino虽然快却特别难用，opencv下一版本，能否让dnn直接支持vino？我真搞不懂intel再搞什么（我知道opencv小组看得懂中文）

**Comment by fengyuentau** [comment]
Thank you for the feedback. We have just done some optimization for the DNN module at https://github.com/opencv/opencv/pull/21910, which gives us faster speed on both Intel and Arm platforms. Those changes are not released yet, but you can have a try with our weekly release: `pip install opencv-python-rolling`. We will keep working on DNN optimization. Stay tune for updates!

By the way, if you are a Intel CPU user, OpenCV DNN has OpenVINO integrated. I think you can find tutorials easily how to use the OpenVINO backend in OpenCV DNN. If you are not satisfied with the inference speed on CPU, DNN also supports GPU (OpenCL, CUDA, Vulkan) and **NPU** (TIM-VX, and the incoming support for Huawei NPU).

We aslo have benchmarks for most of these platforms. You can see the results in https://github.com/opencv/opencv_zoo#models--benchmark-results and pick your favorite one.

**Comment by wwzh2015** [comment]
> Thank you for the feedback. We have just done some optimization for the DNN module at #21910, which gives us faster speed on both Intel and Arm platforms. Those changes are not released yet, but you can have a try with our weekly release: `pip install opencv-python-rolling`. We will keep working on DNN optimization. Stay tune for updates!
> 
> By the way, if you are a Intel CPU user, OpenCV DNN has OpenVINO integrated. I think you can find tutorials easily how to use the OpenVINO backend in OpenCV DNN. If you are not satisfied with the inference speed on CPU, DNN also supports GPU (OpenCL, CUDA, Vulkan) and **NPU** (TIM-VX, and the incoming support for Huawei NPU).
> 
> We aslo have benchmarks for most of these platforms. You can see the results in https://github.com/opencv/opencv_zoo#models--benchmark-results and pick your favorite one.

Thanks！
