### ISSUE TITLE
Bug (crash) in onnx_importer.cpp

### ISSUE THREAD

**Issue by dotan-k** [opencv/opencv#22399]
https://github.com/opencv/opencv/blob/b0dc474160e389b9c9045da5db49d03ae17c6a6b/modules/dnn/src/onnx/onnx_importer.cpp#L1464
void ONNXImporter::parseBias(>>)
{
 // ..
Mat blob_0 = getBlob(node_proto, 0);
Mat blob_1 = getBlob(node_proto, 1);
CV_Assert(blob_0.size == blob_1.size); // crash

blob_0.size is an array containing size per dimension, so this code compares pointers instead of comparing their content.
The result is a crash when parsing bias due to different blob sizes, although the sizes are equal.

**Comment by zihaomu** [comment]
Hi @dotan-k, thanks for your report. Can you please re-compile the OpenCV with the latest code? We have removed the `parseBias`.

**Comment by asmorkalov** [comment]
@zihaomu Please add link to the PR with removed `parseBias`.

**Comment by zihaomu** [comment]
[PR 21865](https://github.com/opencv/opencv/pull/21865/files#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L137)

**Comment by asmorkalov** [comment]
@zihaomu May I close the issue?

**Comment by zihaomu** [comment]
I think Yes.

**Comment by zihaomu** [comment]
I think Yes.
