### ISSUE TITLE
blobFromImage return the wrong size image (-1,-1)

### ISSUE THREAD

**Issue by yuchuxiang** [opencv/opencv#22397]
i went wrong when i use the blobFromImage
-----------------------------------------------------------------------------------------------------------
this is my outprint
处理前图像尺寸--- 宽度： 640  高度： 640
处理后图像尺寸--- 宽度： -1  高度： -1

Process finished with exit code 0
_______________________________________________________________________________________________________
this is my code 

#include <iostream>
#include<opencv2//opencv.hpp>
#include "opencv2/dnn.hpp"

#define USE_CUDA false //use opencv-cuda

using namespace std;
using namespace cv;
using namespace dnn;

int main()
{
    string img_path = "/home/ycx/Object_Detect_ws/src/YOLO_DETECT/images/bus.jpg";

    Mat image_in = imread(img_path);

    resize(image_in,image_in,Size(640,640),INTER_LINEAR);

    std::cout<<"处理前图像尺寸--- 宽度： "<<image_in.cols<<"  高度： "<<image_in.rows<<std::endl;

    Mat image_blob = blobFromImage(image_in,1.0 / 255.0, Size(100,100), cv::Scalar(104, 117, 123), true, false);

    std::cout<<"处理后图像尺寸--- 宽度： "<<image_blob.cols<<"  高度： "<<image_blob.rows<<std::endl;

    return 0;
}

**Comment by zihaomu** [comment]
Reproducing the problem requires more detailed information, such as OS, compiler, OpenCV version, etc.

**Comment by yuchuxiang** [comment]
Ubuntu18 Opencv 4.5.5

**Comment by yuchuxiang** [comment]
可以正常编译，但是运行的时候就会出现这种返回-1-1的尺寸的返回值，这部分程序是我扣出来的，主要就是这个blobFromImage这个部分出了问题。
