### ISSUE TITLE
Some Confusion in CV 2.4 python binding code，could anyone help？

### ISSUE THREAD

**Issue by M0reDr1nk** [opencv/opencv#22400]
Some code in modules\python\src2\cv2.cpp make me confused.
`    void deallocate(int* refcount, uchar*, uchar*)`    
`        {`    
`            PyEnsureGIL gil;`    
`            if( !refcount )`    
`                return;`    
 `           PyObject* o = pyObjectFromRefcount(refcount);`    
`            Py_INCREF(o);`    
`            Py_DECREF(o);`    
`        }`
O(∩_∩)O 
1.Why we call Py_DECREF(o) after Py_DECREF immediately? Does these code redundant here?
2.Why the refcount here is removed in later version? Is there any issue about this?

**Comment by asmorkalov** [comment]
OpenCV 2.4 is depricated and frozen. We do not accept issues and PRs for it for a long time.
