### ISSUE TITLE
C:\opencv\opencv-4.5.5\opencv-4.5.5\modules\dnn\misc\tensorflow\graph.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is (compiling source file C:\opencv\open cv-4.5.5\opencv-4.5.5\modules\dnn\src\tensorflow\tf_io.cpp) [C:\opencv\build\modules\world\opencv_world.vcxproj]

### ISSUE THREAD

**Issue by shantanunandan** [opencv/opencv#22402]
I am trying to build opencv with cuda support. 

Below are the softwares which I used - 
Cmake 3.23.2
Opencv 4.5.5
Opencv contrib 4.x
Visual Studio 17 2022 
Python 3.8.13
Cuda 11.7
Cudnn 8.4
libprotoc 3.20.1

I used cmake to create the files by following this tutorial https://www.youtube.com/watch?v=YsmhKar8oOc on an virtual environment.
When i issue this command -> "C:\Program Files\CMake\bin\cmake.exe" --build "C:\opencv\build" --target INSTALL --config Release

I got the below error which says - 
C:\opencv\opencv_contrib-4.x\opencv_contrib-4.x\modules\cudaoptflow\src\cuda\pyrlk.cu(936): warning #1215-D: function "tex2D(texture<T, 2, cudaReadModeElementType>, float, float) [with T=float]" [C:\opencv\buil
d\modules\world\opencv_world.vcxproj]

and 

C:\opencv\opencv-4.5.5\opencv-4.5.5\modules\dnn\misc\caffe\opencv-caffe.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is (compiling source file C:\opencv\op
encv-4.5.5\opencv-4.5.5\modules\dnn\misc\caffe\opencv-caffe.pb.cc) [C:\opencv\build\modules\world\opencv_world.vcxproj]

Thank You

**Comment by asmorkalov** [comment]
ONNX, Caffe, Tensorflow and some other DNN models are protobuf files. OpenCV contains generated code to parse them. Your project has protobuf that conflicts with the one in OpenCV.

**Comment by minhnghia1103** [comment]
I'm having the same problem, did you fix it? Please show me how to fix it

**Comment by asmorkalov** [comment]
You can use several CMake options during the library build. `-DBUILD_PROTOBUF=OFF` to use external Protobuf version. `-DPROTOBUF_UPDATE_FILES=ON` to regenerate code from .proto files with your protoc.
