### ISSUE TITLE
OpenCV fails to import ONNX model: ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(onnx_node!Clip_3) from domain='ai.onnx'

### ISSUE THREAD

**Issue by ukoehler** [opencv/opencv#22424]
##### System information (version)
- OpenCV => opencv-contrib-python 4.6.0.66
- Operating System / Platform => Windows 10 64 Bit
- Python => 3.10.4

##### Detailed description

I converted a PyTorch model to ONNX (https://github.com/d-li14/HBONet,  https://raw.githubusercontent.com/d-li14/HBONet/master/pretrained/hbonet_1_0.pth)

I can read the model ok using Python with onnxruntime, however, when reading with OpenCV I get the followoing error:

ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(onnx_node!Clip_3) from domain='ai.onnx'
##### Steps to reproduce

I can provide the ONNX model, if required.

##### Issue submission checklist

 - [ x] I report the issue, it's not a question
 - [x ] I checked the problem with documentation, FAQ, open issues,
 - [x ] I updated to the latest OpenCV version and the issue is still there
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by zihaomu** [comment]
related [issue 22384](https://github.com/opencv/opencv/issues/22384#issuecomment-1214813665)

**Comment by ukoehler** [comment]
Using opencv-python-rolling 4.6.0.20220924 i can now execute the model.

**Comment by tsvetiko** [comment]
For me using `opencv-python==4.6.0.66` solved the issue.
