### ISSUE TITLE
How to build for FreeBSD 13.1 ? 

### ISSUE THREAD

**Issue by rajhlinux** [opencv/opencv#22434]
System information (version):

- OpenCV => 4.6.0
- Operating System / Platform => FreeBSD 13.1
- Compiler => clang/llvm and gcc 11
-KDE5 plasma

Has anyone able to compile OpenCV 4.6.0 successfully for FreeBSD 13.1?

If so what was used to compile opencv and also what commands was used?

Thanks.

**Comment by asmorkalov** [comment]
Please use forum.opencv.org
