### ISSUE TITLE
Cannot load onnx (opset 12) of Resnet + MobileVit

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#22446]
I'm testing a semantic segmentation model made from : 
- https://github.com/qubvel/segmentation_models.pytorch for the Resnet backbone/decoder
- https://github.com/rwightman/pytorch-image-models for mobileVit encoder

I used to perform inference with OpenCV using a different encoder (resnet) without any problem.
However switching to MobileVit breaks the onnx loading. I've run opencv_model_diagnostics.exe (from build 4.6.0) and it returns many errors:
```
[ERROR:0@0.135] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 1 inputs and 1 outputs: [Identity]:(onnx_node!Identity_0) from domain='ai.onnx'
OpenCV(4.6.0) \src\layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20220524::Layer::getMemoryShapes'

[ERROR:0@0.142] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 2 inputs and 1 outputs: [Reshape]:(onnx_node!Reshape_121) from domain='ai.onnx'
OpenCV(4.6.0) \onnx_importer.cpp:571: error: (-5:Bad argument) Blob onnx::Reshape_1114 not found in const blobs in function 'cv::dnn::dnn4_v20220524::ONNXImporter::getBlob'

[ERROR:0@0.142] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 1 inputs and 1 outputs: [Transpose]:(onnx_node!Transpose_122) from domain='ai.onnx'
OpenCV(4.6.0) \src\layers\permute_layer.cpp:161: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

[ERROR:0@0.142] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 1 inputs and 1 outputs: [Transpose]:(onnx_node!Transpose_127) from domain='ai.onnx'
OpenCV(4.6.0) \src\layers\permute_layer.cpp:161: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

[ERROR:0@0.142] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 2 inputs and 1 outputs: [MatMul]:(onnx_node!MatMul_128) from domain='ai.onnx'
OpenCV(4.6.0) \src\layers\fully_connected_layer.cpp:129: error: (-2:Unspecified error) in function 'bool __cdecl cv::dnn::FullyConnectedLayerImpl::getMemoryShapes(const class std::vector<class std::vector<int,class std::allocator<int> >,class std::allocator<class std::vector<int,class std::allocator<int> > > > &,const int,class std::vector<class std::vector<int,class std::allocator<int> >,class std::allocator<class std::vector<int,class std::allocator<int> > > > &,class std::vector<class std::vector<int,class std::allocator<int> >,class std::allocator<class std::vector<int,class std::allocator<int> > > > &) const'
>  (expected: 'inputs[0].back() == inputs[1][dims - 2]'), where
>     'inputs[0].back()' is 288
> must be equal to
>     'inputs[1][dims - 2]' is 256

[ERROR:0@0.143] global \onnx_importer.cpp (1000) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: Potential problem during processing node with 1 inputs and 1 outputs: [Softmax]:(onnx_node!Softmax_131) from domain='ai.onnx'
OpenCV(4.6.0) \include\opencv2\dnn\shape_utils.hpp:216: error: (-2:Unspecified error) in function 'int __cdecl cv::dnn::dnn4_v20220524::normalize_axis(int,int)'
> :
>     'axis >= -dims && axis < dims'
> where
>     'axis' is 3
```

Is it a matter of opset incompatibility or unsupported layers?

**Comment by zihaomu** [comment]
Hi @JulienMaille, is there any relevant ONNX file available?

**Comment by JulienMaille** [comment]
> Hi @JulienMaille, is there any relevant ONNX file available?

I emailed it to you on the address visible on your profile.

**Comment by zihaomu** [comment]
Thanks. I'm working on it.

**Comment by zihaomu** [comment]
Hi @JulienMaille, the error is due to `Identity layer`, and with this #22290 patch, everything is ok.
For now, you can try checkout that branch, and compile OpenCV from source code.

**Comment by JulienMaille** [comment]
Thanks a lot I will try that

**Comment by zihaomu** [comment]
Hi @JulienMaille, looks like the patch #22290 changed some code in `Reshape layer` which resulted in the error.

Issue related models [model_2022_0714_10h14_12.onnx.zip](https://github.com/opencv/opencv/files/9466261/model_2022_0714_10h14_12.onnx.zip)

For now, you can do the following:
step 1: checkout to 4.x branch
step 2: change the code in `onnx_importer.cpp` [Line 3083 - 3090](https://github.com/opencv/opencv/blob/4.x/modules/dnn/src/onnx/onnx_importer.cpp#L3083-L3090)
from 
```.cpp
void ONNXImporter::parseSimpleLayers(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
{
    for (int j = 0; j < node_proto.input_size(); j++) {
        if (layer_id.find(node_proto.input(j)) == layer_id.end())
            layerParams.blobs.push_back(getBlob(node_proto, j));
    }
    addLayer(layerParams, node_proto);
}
```
to 

```.cpp
void ONNXImporter::parseSimpleLayers(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
{
    bool is_all_input_const = true;
    for (int i = 0; i < node_proto.input_size(); i++)
    {
        if (layer_id.find(node_proto.input(i)) != layer_id.end())
        {
            is_all_input_const = false;
            break;
        }
    }
    if (is_all_input_const && node_proto.output_size() == 1)
    {
        std::vector<Mat> input, output;
        for (int i = 0; i < node_proto.input_size(); i++)
            input.push_back(getBlob(node_proto, i));
        runLayer(layerParams, input, output);
        addConstant(node_proto.output(0), output[0]);
        return;
    }

    for (int j = 0; j < node_proto.input_size(); j++) {
        if (layer_id.find(node_proto.input(j)) == layer_id.end())
            layerParams.blobs.push_back(getBlob(node_proto, j));
    }
    addLayer(layerParams, node_proto);
}

```
And everything works fine in `net.forward()`.

**Comment by JulienMaille** [comment]
> What is your input shape? 1x1x256x256 works fine. And 2x1x256x256 can not work as expected.

My input shape was a multiple of 16 for the image size, something like 1x1x320x320
Maybe there's something wrong on my side.

**Comment by zihaomu** [comment]
Please use the right input shape as the model expected.

**Comment by JulienMaille** [comment]
Model is fully convolutional and is run in pytorch on input shape larger than the training size without any issues.

**Comment by JulienMaille** [comment]
Ok, what is sensitive regarding reshape? I would argue that Pytorch can also perform inference and my hope was that OpenCV inference is similar to Pytorch inference.

**Comment by zihaomu** [comment]
It's about memory allocation.

**Comment by JulienMaille** [comment]
Understood. Is there any hope? Or at least an open issue on that topic?

**Comment by zihaomu** [comment]
Maybe, you can search the keywork **dynamic shape**, and for now we do not support dynamic shape.

**Comment by JulienMaille** [comment]
> Maybe, you can search the keyword **dynamic shape**, and for now we do not support dynamic shape.

Do you mean dynamic shape is not supported for reshape (and a subset of other layers?) Because until today I was inferring simpler models with dynamic shapes without any problem

**Comment by zihaomu** [comment]
Yes, some layers, like `reshape`, `shape` and maybe `resize` is not supported the dynamic shape.

**Comment by fengyuentau** [comment]
> Do you mean dynamic shape is not supported for reshape (and a subset of other layers?) Because until today I was inferring simpler models with dynamic shapes without any problem

I would like to add some words to make it clear about the dynamic shape thing in OpenCV DNN. So in OpenCV DNN, each layer is initialized with memory allocated based on the input & output shape during the model importing. For an ONNX model with fixed input shape, if the actual input image has the same shape, inference should finish without issues; if the actual input image has different shape, memory will be re-allocated based on that shape in inference, and you still have a chance successfully finishing the inference if there is no operator like `resize` which may always generating an output of fixed shape regardless the input.

**Comment by JulienMaille** [comment]
@fengyuentau Thanks for the explanation. Is there any ongoing work add support of dynamic shapes to operators like `resize`?
Can we workaround this by using different equivalent operator in the model definition?
OpenCV being an image-centric library, I suppose that dynamic shapes is very common when inferring on pictures.

**Comment by fengyuentau** [comment]
>  Is there any ongoing work add support of dynamic shapes to operators like resize?

We are working on the next generation OpenCV DNN, but it will only be available since OpenCV 5.

> Can we workaround this by using different equivalent operator in the model definition?

It depends on the model.
