### ISSUE TITLE
Failed to build OpenCV - *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#22449]
```console
[ 28%] Built target opencv_cudawarping
make  -f modules/dnn/CMakeFiles/opencv_dnn.dir/build.make modules/dnn/CMakeFiles/opencv_dnn.dir/depend
make[2]: Entering directory '....../opencv/build'
modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:2564: *** target pattern contains no '%'.  Stop.
make[2]: Leaving directory '....../opencv/build'
make[1]: *** [CMakeFiles/Makefile2:4064: modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
make[1]: Leaving directory '....../opencv/build'
make: *** [Makefile:169: all] Error 2
```

What happened to **OpenCV** again???

**Comment by zihaomu** [comment]
Hi @jiapei100, can you provide complete compilation information? As well as information such as cuda version, GPU info, etc., will help us judge what is going on.

**Comment by vcunat** [comment]
It [happens](https://hydra.nixos.org/build/191540980) also on our build farm.  Full log there, but let me also attach it: 
[opencv-4.5.4.log](https://github.com/opencv/opencv/files/9605362/opencv-4.5.4.log)

GPU should be irrelevant.  It's on a build farm, and I could reproduce the error locally (on a system without any nvidia).  As you can see, we build with `-DWITH_CUDA=OFF`.

**Comment by zihaomu** [comment]
Hi @vcunat. Please not try to use other protubuf installations. Try to build latest master from scratch.

**Comment by vcunat** [comment]
Can you explain a bit more?  This isn't a custom build; the whole set of packages is a Linux distribution (well, not limited to Linux actually).  The currently used protobuf is 3.21.2, i.e. newer than any opencv relase.

**Comment by zihaomu** [comment]
I'm not sure. From your log, the protobuf about info is wired. OpenCV has added protobuf to 3rdparty. I think we can directly compile OpenCV from scratch.

**Comment by vcunat** [comment]
I updated protobuf to the latest release from five days ago and the error remained the same:  
[opencv-4.5.4-2.log](https://github.com/opencv/opencv/files/9605916/opencv-4.5.4-2.log)

**Comment by zihaomu** [comment]
Please re-try the `-DBUILD_PROTOBUF=ON` and do not set `-DProtobuf_PROTOC_EXECUTABLE`.

**Comment by mshabunin** [comment]
If you want to use external protobuf you should regenerate proto-files: set `PROTOBUF_UPDATE_FILES` cmake option to `ON` (https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html#tutorial_config_reference_dnn).

**Comment by vcunat** [comment]
Thanks, but as you could see from the logs above we *do* pass `-DPROTOBUF_UPDATE_FILES=ON`.

**Comment by alalek** [comment]
There is some problem reported on CMake stage:

```
CMake Warning at /nix/store/dwyq6vx8lh6yn8rwyrm6hfd6c62q3zhi-cmake-3.24.1/share/cmake-3.24/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version doesn't match library version 3.21.2
Call Stack (most recent call first):
  cmake/OpenCVFindProtobuf.cmake:34 (find_package)
  CMakeLists.txt:701 (include)
```

Please ensure that you have valid build environment.

Verify content related to protobuf from `CMakeVars.txt` / `CMakeCache.txt` files.

**Comment by vcunat** [comment]
The warning is interesting, as the build is sandboxed and I re-verified that it only contains protobuf 3.21.2.  (You can see protoc path above in the log, it contains version.)

Anyway, the advice about using latest protobuf was... "reversed".  The build broke because protobuf was updated yesterday from 3.19 to 3.21.  When I undo that, it succeeds.  It also succeeds with the vendored protobuf.  (Just to be clear, thanks to sandboxing, one build always sees only one particular instance of protobuf library and compiler.)

**Comment by vcunat** [comment]
For reference, with protobuf 3.20.1 it also builds.

**Comment by vcunat** [comment]
Oh, I'm sorry.  The mistake was ours.  Thanks for pointing me closer to the source of the problem.

Our build "script" pointed `-DProtobuf_PROTOC_EXECUTABLE` to `bin/protobuf` which does not exist and should be `bin/protoc`.  It's not ideal that cmake didn't complain louder.

Anyway, for us it builds now with 3.21.2 as well (and makes that warning go away).  I can't judge how that differs from the original poster's situation.

**Comment by mshabunin** [comment]
Let's consider it "Not a problem" since no additional information have been provided.
