### ISSUE TITLE
Add support for V4L2_PIX_FMT_Y16_BE

### ISSUE THREAD

**Issue by mariannasb** [opencv/opencv#22455]
OpenCV currently only has support for `V4L2_PIX_FMT_Y16` but not for the Big Endian version of this format: `V4L2_PIX_FMT_Y16_BE`.

Would it be possible to add it to [`cap_v4l.cpp`](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_v4l.cpp)?

The handling should be a lot similar to the little endian version of the format.
But can openCV handle big endian data?
Or are there any functions to swap the endianess?

**Comment by asmorkalov** [comment]
Incomplete PR for it: https://github.com/opencv/opencv/pull/18498

**Comment by asmorkalov** [comment]
Diplicate for https://github.com/opencv/opencv/issues/18495
