### ISSUE TITLE
OpenCVFindOpenBLAS.cmake

### ISSUE THREAD

**Issue by ZJDATY** [opencv/opencv#22465]
76    FIND_LIBRARY（OpenBLAS_LIB NAMES openblas PATHS ${Open_BLAS_LIB_SEARCH_PATHS} NO_DEFAULT_PATH)

There is no lib called openblas. Should be modified to libopenblas.

76    FIND_LIBRARY（OpenBLAS_LIB NAMES libopenblas PATHS ${Open_BLAS_LIB_SEARCH_PATHS} NO_DEFAULT_PATH)

**Comment by fengyuentau** [comment]
This is how `FIND_LIBRARY` works. See also https://cmake.org/cmake/help/latest/command/find_library.html:

> Each library name given to the NAMES option is first considered as a library file name and then considered with platform-specific prefixes (e.g. lib) and suffixes (e.g. .so). Therefore one may specify library file names such as libfoo.a directly. This can be used to locate static libraries on UNIX-like systems.
