### ISSUE TITLE
ReadNetFromModelOptimizer crashes when using bytes instead of filename opencvdnn

### ISSUE THREAD

**Issue by cesarpgouveia** [opencv/opencv#22464]
**System information (version)**
* OpenCV => 4.5.5 built with OpenVINO 2021.4.689
* Operating System / Platform => Windows 64 Bit
* Compiler =>Visual Studio 2019

**Detailed description**
I'm trying to load and infer using an OpenVINO model (Intermediate Representation - xml and bin) using ReadNetFromModelOptimizer opencvdnn function. However, instead of providing the xml and bin filenames, I provided the bytes instead. So that everyone could replicate the problem a cpp sample is provided below:

```
#include <iostream>
#include <filesystem>
#include <iostream>
#include <filesystem>
#include <chrono>
#include <thread>
#include <fstream>

#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/core.hpp>


std::vector<unsigned char> ReadAllBytesFromFile(const std::string& filename)
{
    FILE* file;
#ifdef __linux__
    file = fopen(filename.c_str(), "rb");
#else
    fopen_s(&file, filename.c_str(), "rb");
#endif
    if (file == NULL)
    {
        std::cout << "Unable to open file " + filename << std::endl;
        exit(-1);
    }

    fseek(file, 0, SEEK_END);
    long int fileSize = ftell(file);
    fseek(file, 0, 0);
    std::vector<uint8_t> buffer(fileSize);
    int bytesRead = fread(buffer.data(), sizeof(unsigned char), fileSize, file);

    if (bytesRead != fileSize)
    {
        std::cout << "Failed to read all bytes from file " + filename << std::endl;
        exit(-1);
    }

    fclose(file);
    return buffer;
}

int main()
{
    std::vector<unsigned char> bufferArchitecture;
    std::vector<unsigned char> bufferModel;

    // selfie-bg-detector
    cv::Size inputSizeSelfieBgDetector = cv::Size(256, 256);
    std::string xmlSelfieBgDetector_FP32 = "C:/Users/cesar.gouveia/Models/SelfieBgDetector.xml";
    std::string binSelfieBgDetector_FP32 = "C:/Users/cesar.gouveia/Models/SelfieBgDetector.bin";

    // Change specifications of the test here:
    std::string imagefilename = "C:/Lixo/VBHarryStyles/Harry_Styles.jpg";
    cv::Size currSize = inputSizeSelfieBgDetector;
    std::string currXml = xmlSelfieBgDetector_FP32;
    std::string currBin = binSelfieBgDetector_FP32;
    unsigned int num_inferences = 100;

    bufferModel = ReadAllBytesFromFile(currBin);
    bufferArchitecture = ReadAllBytesFromFile(currXml);

    cv::dnn::Net net = cv::dnn::readNetFromModelOptimizer(bufferArchitecture, bufferModel);

    net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
    net.setPreferableBackend(cv::dnn::DNN_TARGET_CPU);

    cv::Mat img = cv::imread(imagefilename);
    cv::Mat resized;
    cv::resize(img, resized, currSize);

    std::vector<cv::Mat> imgbatch = { resized };
    bool swaprbchannels = false;
    cv::Mat blob = cv::dnn::blobFromImages(imgbatch, 1.0, cv::Size(), cv::Scalar(), swaprbchannels, false, CV_32F);

    net.setInput(blob);

    std::vector<cv::String> unconnectedoutlayernames = net.getUnconnectedOutLayersNames();

    std::vector<cv::Mat> outputs;
    outputs.clear();

    auto timeloadmodelplusinference1 = std::chrono::high_resolution_clock::now();

    net.forward(outputs, unconnectedoutlayernames);

    auto timeloadmodelplusinference2 = std::chrono::high_resolution_clock::now();

    auto ms_doubletimeloadmodelplusinference = timeloadmodelplusinference2 - timeloadmodelplusinference1;

    std::cout << "execution time (load model + inference): " << ms_doubletimeloadmodelplusinference.count() << std::endl; // in ms

    auto time1 = std::chrono::high_resolution_clock::now();

    try
    {
        for (size_t i = 0; i < num_inferences; i++)
            net.forward(outputs, unconnectedoutlayernames);
    }
    catch (std::exception& ex)
    {
        std::cout << ex.what() << std::endl;
    }
    auto time2 = std::chrono::high_resolution_clock::now();

    auto ms_double = time2 - time1;

    std::cout << "execution time inference only: " << ms_double.count() / num_inferences << std::endl; // in ms

    std::cout << outputs[0].size[0] << std::endl;
    std::cout << outputs[0].size[1] << std::endl;
    std::cout << "finished" << std::endl;
}
```

So I run this piece of code using ReadNetFromModelOptimizer **and using the bin and xml filenames** and the code works fine. However, **when I read the bytes** and give them to the function the code returns the following error:

> OpenCV: terminate handler is called! The last OpenCV error is:
> OpenCV(4.5.5) Error: Unspecified error (DNN: IE failed to load model: Cannot load library 'C:\Users\cesar.gouveia\Projects\OpenCVTests\x64\Release\inference_engine_onnx_reader.dll': 126 from cwd: C:\Users\cesar.gouveia\Projects\OpenCVTests\TestAdas) in cv::dnn::dnn4_v20211220::Net::readFromModelOptimizer, file C:\Projects\OpenCV-Package\opencv_mirror\modules\dnn\src\dnn.cpp, line 4391

I tried with this model, but the error applies to every IR model that I tried to run (I tried with multiple ones, different architectures, outputs, and input sizes).

I don't know why this is happening, If you can give me some input on this I would be very grateful.

Thanks,
César.

**Comment by dkurt** [comment]
This is not a buffer reader problem but package problem:
> inference_engine_onnx_reader.dll

some library has been missed.

**Comment by cesarpgouveia** [comment]
Hey @dkurt, thanks for the response!

I think the issue cannot be the lack of that dll because the dll is there. Moreover, the error is different when there is a dll missing.

If you have another idea please feel free to share it.
Thanks, César.

**Comment by dkurt** [comment]
@cesarpgouveia, Do you use prebuilt package from https://github.com/opencv/opencv/releases/tag/4.5.5? If not, can you please share build steps? Here is what I tried:
1. Downloaded https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2.zip
2. There is no `inference_engine_onnx_reader.dll`:
![image](https://user-images.githubusercontent.com/25801568/210502798-7c0a5b1e-e2c9-4588-906a-dcc8b001bf1b.png)

**Comment by tahvane1** [comment]
I have same/similar problem. Have been narrowing down problem to this layer
<layer id="191" name="onnx::Concat_217" type="Interpolate" version="opset4">
		
Might be relate to this https://github.com/openvinotoolkit/openvino/pull/12205

Have to investigate why loading from file still works... maybe there is conversion/replacement somewhere.

**Comment by dkurt** [comment]
Let's close for now unless there would be more information to reproduce.
