### ISSUE TITLE
Bug (Javascript) mean/meanStdDev broken for 8UC3 images

### ISSUE THREAD

**Issue by stx-chris** [opencv/opencv#22489]
##### System information (version)

- OpenCV => 4.6.0
- Operating System / Platform => MacOS 13.0

##### Detailed description

Javascript functions `mean` and `meanStdDev` (and probably others) cause an uncaught exception when applied with masks on 3-channel images.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/62717406/189277229-bf57279d-8f9f-43c3-8f58-15455ad89070.png">

##### Steps to reproduce

```
let src = ...
let dst1 = cv.Mat.zeros(src.cols, src.rows, cv.CV_8UC1);
let mask1 = cv.Mat.zeros(src.cols, src.rows, dst1.type());

let dst3 = cv.Mat.zeros(src.cols, src.rows, cv.CV_8UC3);
let mask3 = cv.Mat.zeros(src.cols, src.rows, dst3.type());

const mean_val = cv.mean(dst1, mask1);  // <--- works
const mean_val = cv.mean(dst3, mask3);  // <--- causes uncaught exception error
```

**Comment by berak** [comment]
helo, @stx-chris, let me try to clarify a few things:

* there is no bug here.
* it is not a js-specific problem.
* the *input* to `cv::mean` can have 1, 3 or 4 channels
* the *mask* is restricted to a *single* channel
  ( a slightly different setup would have lead to a more clear error: )

      let src = cv.imread('canvasInput'); // CV_8UC4
      let mask = new cv.Mat(src.size(), src.type()); // only CV_8UC1 is legal
      cv.mean(src,mask);

      Exception: OpenCV(4.6.0-dev)/build/master-contrib_docs-lin64/opencv/modules/core/src/mean.dispatch.cpp:126:
      error: (-215:Assertion failed) mask.empty() || mask.type() == CV_8U in function 'mean'
