### ISSUE TITLE
videoCapture read empty in multithread

### ISSUE THREAD

**Issue by SangerY** [opencv/opencv#22488]
##### System information (version)
- OpenCV => 4.5.5
- Operating System / Platform => centos 7.9
- Compiler => Makefile

##### Detailed description
I tried to open 4 rtmp stream with VideoCapture, each VideoCapture is in one thread, read frame is normal. When I opened 5 at the same time, 2 loss frame.

##### Steps to reproduce
grep 'physical id' /proc/cpuinfo | sort -u | wc -l
2
grep 'core id' /proc/cpuinfo | sort -u | wc -l
4
grep 'processor' /proc/cpuinfo | sort -u | wc -l
16

```.cpp
void* ReceiveData(void* arg)
{
	Param param = *(Param *)arg;
	int idx = param.idx;
	std::string url = param.url;
	int cpu_frame_count = 0;
	cv::VideoCapture cap;
	cap.open(url);

	if(!cap.isOpened())
	{
		return NULL;
	}
        
        ulong startTime = get_time_ms();
	ulong endTime = get_time_ms();
	int frameEmptyNum = 0;
	cv::Mat frame;
        
        while((endTime - startTime) < 50 * 1000)
        {
               cap >> frame;
               if(frame.empty())
		{
                      frameEmptyNum ++;
                      daily_logger->info("idx:{}, frame is empty", idx);
    		      daily_logger->flush();
                      usleep(40 * 1000);
                }
               else
		{
                      // outputVideo.write(frame);
                }
                cpu_frame_count++;
                usleep(1000);
                endTime = get_time_ms();
        }
        daily_logger->info("idx:{}, cpu_frame_count:{}, frameEmptyNum:{}", idx, cpu_frame_count);
        daily_logger->flush();
        return NULL;
}
 ```
4 threads
[2022-09-09 11:49:22.698] [visualLog] [info] idx:0, cpu_frame_count:1105, frameEmptyNum:0
[2022-09-09 11:49:24.462] [visualLog] [info] idx:1, cpu_frame_count:1078, frameEmptyNum:0
[2022-09-09 11:49:25.143] [visualLog] [info] idx:2, cpu_frame_count:1136, frameEmptyNum:0
[2022-09-09 11:49:28.293] [visualLog] [info] idx:3, cpu_frame_count:1335, frameEmptyNum:0
5 threads，once frame is empty appears, it will not be recovered.
[2022-09-09 13:08:52.551] [visualLog] [info] idx:1, cpu_frame_count:1236, frameEmptyNum:0
[2022-09-09 13:08:52.565] [visualLog] [info] idx:0, cpu_frame_count:857, frameEmptyNum:0
[2022-09-09 13:08:54.745] [visualLog] [info] idx:2, cpu_frame_count:1276, frameEmptyNum:0
[2022-09-09 13:08:56.481] [visualLog] [info] idx:3, cpu_frame_count:845, frameEmptyNum:105
[2022-09-09 13:09:00.746] [visualLog] [info] idx:4, cpu_frame_count:897, frameEmptyNum:723

**Comment by alalek** [comment]
What is CPU load? network load?
Are you able to run 5 application instances with capturing of 1 "own" video stream (instead of 5 threads)?

VideoCapture / FFmpeg is not able to recover from lost RTSP stream (stream is corrupted in this case, so it should be handled on the app level, not the library). You need to handle this error in application and re-connect / re-open.

Try to enable OpenCV and FFmpeg logs through environment variables:
- OPENCV_LOG_LEVEL=DEBUG
- OPENCV_FFMPEG_DEBUG=1

**Comment by SangerY** [comment]
@alalek 
I run 5 application instances, each instance opens 1 same video stream, still appear frame empty.
[2022-09-14 09:31:14.293] [visualLog] [info] idx:0, cpu_frame_count:838, frameEmptyNum:0
[2022-09-14 09:31:15.248] [visualLog] [info] idx:0, cpu_frame_count:1156, frameEmptyNum:0
[2022-09-14 09:31:15.623] [visualLog] [info] idx:0, cpu_frame_count:1116, frameEmptyNum:0
[2022-09-14 09:31:16.293] [visualLog] [info] idx:0, cpu_frame_count:1052, frameEmptyNum:0
[2022-09-14 09:31:19.712] [visualLog] [info] idx:0, cpu_frame_count:808, frameEmptyNum:458

I run 5 threads with OPENCV_LOG_LEVEL=DEBUG and OPENCV_FFMPEG_DEBUG=1
[2022-09-14 09:43:34.034] [visualLog] [info] idx:0, cpu_frame_count:854, frameEmptyNum:0
[2022-09-14 09:43:35.880] [visualLog] [info] idx:1, cpu_frame_count:1122, frameEmptyNum:0
[2022-09-14 09:43:36.373] [visualLog] [info] idx:2, cpu_frame_count:1089, frameEmptyNum:0
[2022-09-14 09:43:38.169] [visualLog] [info] idx:3, cpu_frame_count:1136, frameEmptyNum:0
[2022-09-14 09:43:42.277] [visualLog] [info] idx:4, cpu_frame_count:749, frameEmptyNum:482
log
[DEBUG:0@0.005] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/videoio_registry.cpp (197) VideoBackendRegistry VIDEOIO: Builtin backends(8): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930)
[DEBUG:0@0.005] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/videoio_registry.cpp (221) VideoBackendRegistry VIDEOIO: Available backends(8): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930)
[ INFO:0@0.005] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/videoio_registry.cpp (223) VideoBackendRegistry VIDEOIO: Enabled backends(8, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930)
[OPENCV:FFMPEG:40] Starting connection attempt to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Successfully connected to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[DEBUG:0@0.848] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_impl.hpp (1056) open FFMPEG: stream[2] is video stream with codecID=27 width=1280 height=720
[DEBUG:0@0.848] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_hw.hpp (933) HWAccelIterator FFMPEG: allowed acceleration types (none): ''
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:24] deprecated pixel format used, make sure you did set range correctly
[OPENCV:FFMPEG:40] Starting connection attempt to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Successfully connected to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:40] Starting connection attempt to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Successfully connected to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[DEBUG:1@2.946] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_impl.hpp (1056) open FFMPEG: stream[2] is video stream with codecID=27 width=1280 height=720
[DEBUG:1@2.946] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_hw.hpp (933) HWAccelIterator FFMPEG: allowed acceleration types (none): ''
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:24] deprecated pixel format used, make sure you did set range correctly
[OPENCV:FFMPEG:40] Starting connection attempt to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Successfully connected to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[DEBUG:2@3.465] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_impl.hpp (1056) open FFMPEG: stream[2] is video stream with codecID=27 width=1280 height=720
[DEBUG:2@3.465] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_hw.hpp (933) HWAccelIterator FFMPEG: allowed acceleration types (none): ''
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:24] deprecated pixel format used, make sure you did set range correctly
[OPENCV:FFMPEG:40] Starting connection attempt to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Successfully connected to xx.xx.xx.xxx port xxxx
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[DEBUG:3@4.829] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_impl.hpp (1056) open FFMPEG: stream[2] is video stream with codecID=27 width=1280 height=720
[DEBUG:3@4.829] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_hw.hpp (933) HWAccelIterator FFMPEG: allowed acceleration types (none): ''
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:24] deprecated pixel format used, make sure you did set range correctly
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[OPENCV:FFMPEG:40] Ignoring outlier non primary stream starttime 0.000000
[DEBUG:4@9.339] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_impl.hpp (1056) open FFMPEG: stream[2] is video stream with codecID=27 width=1280 height=720
[DEBUG:4@9.339] global /root/algorithm/opencv455_build/opencv/opencv-4.5.5/modules/videoio/src/cap_ffmpeg_hw.hpp (933) HWAccelIterator FFMPEG: allowed acceleration types (none): ''
[OPENCV:FFMPEG:40] Reinit context to 1280x720, pix_fmt: yuvj420p
[OPENCV:FFMPEG:24] deprecated pixel format used, make sure you did set range correctly
[OPENCV:FFMPEG:40] Statistics: 9223464 bytes read, 0 seeks
[OPENCV:FFMPEG:40] Statistics: 12058155 bytes read, 0 seeks
[OPENCV:FFMPEG:40] Statistics: 11737107 bytes read, 0 seeks
[OPENCV:FFMPEG:40] Statistics: 12315888 bytes read, 0 seeks
[OPENCV:FFMPEG:40] Statistics: 5658022 bytes read, 0 seeks

**Comment by SangerY** [comment]
@alalek I tried to read the local mp4 video with multithread，there was no problem. Why does rtmp have the problem?
