### ISSUE TITLE
Using GPU OpenCL for face detect is super slow. [C++]

### ISSUE THREAD

**Issue by rajhlinux** [opencv/opencv#22492]
##### System information (version)

opencv-4.5.5_9
OS: FreeBSD 13.1-RELEASE-p1 amd64 
Resolution: 3840x2160 
DE: Plasma 5.24.6 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD FX-8350 (8) @ 3.991GHz 
GPU: Ellesmere [Radeon RX 580] 
Memory: 11708MiB / 32684MiB 
Compiler => FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)

##### Detailed description

"ufacedetect.cpp" from T-API folder in samples folder runs super slow after compilation. When running the compiled code, OpenCL can be seen displayed as "ON" while running the compiled code.

##### Steps to reproduce

compile "ufacedetect.cpp" from T-API folder in samples folder and run it. There is no difference in performance, OpenCL does not offload CPU usage.

![screenshot](https://user-images.githubusercontent.com/61344181/189474334-1978ffec-ccad-41e9-9044-2dc07a852b69.jpg)

What could be the issue?

**Comment by alalek** [comment]
This output could help:
- `clinfo`
- `opencv_version --opencl`

**Comment by rajhlinux** [comment]
Hello [alalek](https://github.com/alalek),

Thanks for the reply, here is the output for `clinfo`:
https://pastebin.com/BQSEr0x2

here is the output for `opencv_version --opencl`:
https://pastebin.com/Y2Cv8QTQ

**Comment by alalek** [comment]
Mesa OpenCL runtime may have bugs (some of them are reported here before).
For AMD GPUs it makes sense to use AMDGPU or ROCm implementations of OpenCL (they have better support).

> FreeBSD

Unlikely...

**Comment by rajhlinux** [comment]
Thanks I guess I just have to learn the art of OpenCL and AMD ISA to do things from scratch to get things working for me.
