### ISSUE TITLE
Grab functions doesn't return false at end of buffer.

### ISSUE THREAD

**Issue by troundtree** [opencv/opencv#22493]
I am trying to grab the last frame of the buffer; the grab function is faulty. The thread gets stuck at "stuckB", my count was it hit the grab function 2000 within one second, more than any camera fps that I have. So, the thread is faster than what is being loaded into the buffer. I am just trying to get the last frame, because I am using multiple cameras, I want them to be close in time. Using read to decoded them is not preferable, when I can just skip them. What is going on with the grab (), is it actually moving frames through the buffer, or just grabbing the same frame over and over?

Code below to test:

VideoCapture CapP;
CapP.open(0, cv::CAP_DSHOW);
std::cout << "MJPG: " << CapP.set(cv::CAP_PROP_FOURCC, cv::VideoWriter::fourcc('M', 'J', 'P', 'G'));
Mat frame;
while (true) {

int b = 0;
bool a = false;

while (a == false) {
	if (CapP.grab() == true) {
		a = true;
	}else{
		std::cout << "stuck_A" << endl;
	}
}
bool a2 = false;

while (a2 == false) {
	if (CapP.grab() == false) {
		a2 = true;
	}
	else {
		cout << "stuck_B" << endl;
		cout << b++ << endl;
	}
}
CapP.retrieve(frame);
imshow("frame", frame);
waitKey(1);
}

General configuration for OpenCV 4.1.2

**Comment by alalek** [comment]
There is no "last frame" for live streams like cameras.
Probably you are using `VideoCapture` interface in a wrong way or for some suspicious scenarios.

In general, camera backends may drop "old" frames which are not processed/fetched by user (with some 1-3 frames in the queue).
DSHOW backend is deprecated in favor of MSMF backend.
Also OpenCV 4.1.2 is outdated version and may contain bugs.

**Comment by troundtree** [comment]
I am trying to do multiple camera stereo calibration with 4 cameras was only trying to use one thread to get the frames I need but working with four threads works okay.
