### ISSUE TITLE
opencv c++ cmake compile error

### ISSUE THREAD

**Issue by rajhlinux** [opencv/opencv#22525]
OpenCV - 4.6
Operating System: FreeBSD 13.1
Compiler: Clang 13

Bug description:
When compiling opencv with cmake I get the following error:

```
ld: error: unable to find library -lva
ld: error: unable to find library -lva-drm
```

**Comment by alalek** [comment]
Try `cmake -DWITH_VA=OFF ...`

**Comment by rajhlinux** [comment]
Thank You for the reply, I will try this.
