### ISSUE TITLE
cv2.VideoCapture shows different results on x86_64 Linux and ARM64 

### ISSUE THREAD

**Issue by jimjiyn** [opencv/opencv#22538]
##### Detailed description
same jpg and opencv version, shows different results on x86_64 Linux and ARM64 

x86_64
![image](https://user-images.githubusercontent.com/37129079/191229715-3916811d-5d3a-42e9-8e7f-5fa103c08990.png)
ARM64
![image](https://user-images.githubusercontent.com/37129079/191229765-6f65cfd4-8997-44e9-b4c2-649cab790a0f.png)

code:

import cv2

reader = cv2.VideoCapture("flags-figure1.jpg")
success, frame = reader.read()
print(frame)

**Comment by jimjiyn** [comment]
opencv version：
[root@localhost home]# pip3 show opencv-python
Name: opencv-python
Version: 4.6.0.66
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: None
Author-email: None
License: MIT
Location: /usr/local/lib64/python3.7/site-packages
Requires: numpy, numpy
Required-by:

**Comment by jimjiyn** [comment]
![image](https://user-images.githubusercontent.com/37129079/191265116-43b40a0d-610f-43c6-9796-409d8b4ce687.png)

**Comment by asmorkalov** [comment]
OpenCV does not implement image and video codecs by itself, but relies on popular libraries like FFmpeg, libjpeg-turbo and so on. Jpeg is not lossless codec by default and different libjpeg/libjpeg-turbo/ffmpeg versions may decode it differently a bit. Use lossless compression codecs like PNG to get predictable results in tests.

**Comment by asmorkalov** [comment]
Nothing to do on OpenCV side.
