### ISSUE TITLE
What are the requirements for the VideoCapture URL?

### ISSUE THREAD

**Issue by laolaolulu** [opencv/opencv#22545]
What are the requirements for the VideoCapture URL?

1.https://gitee.com/laolaolulu/public/raw/master/lADPDgQ9rpdwHBXNArzNArw_700_700.jpg

2.https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.jj20.com%2Fup%2Fallimg%2F4k%2Fs%2F02%2F2109242332225H9-0-lp.jpg&refer=http%3A%2F%2Fimg.jj20.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1666315958&t=32dbab240541a94343584ef5df52595d

Why 1 reads null

**Comment by asmorkalov** [comment]
OpenCV does not implement http/https and streaming protocols by itself, but relies on 3rdparty libraries. The most popular solution is FFmpeg. Please rely FFmpeg documentation on this and check it with command line ffmpeg tool.

**Comment by kallaballa** [comment]
You probably may want to pass (at least) a protocol_whitelist to ffmpeg (but probably [protocol specific settings](https://ffmpeg.org/ffmpeg-protocols.html#http) as well. you can use the enviroment variable OPENCV_FFMPEG_CAPTURE_OPTIONS to do so.

**Comment by kallaballa** [comment]
Here is an example: https://answers.opencv.org/question/184749/rpi-3b-protocol-rtp-not-on-whitelist-filecrypto-opencv-330/ for rtp streaming
