### ISSUE TITLE
(-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211004::Layer::getMemoryShapes'

### ISSUE THREAD

**Issue by connectumaraziz** [opencv/opencv#22549]
I am doing a text extraction on specific regions using Yolov5. I trained a model and convert it to onnx formate for OpenCV readable formate.. but when I load the model weight this error occurs.. all stack and GitHub issues are not able to solve my problem. I downgraded my torch version according to Github resolved issues but my issue is still there. Kindly if anyone has an idea about this error contact me plz. I am very glad to receive your message. Best regards. Error is below

[ERROR:0] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (720) cv::dnn::dnn4_v20211004::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Resize_445) Traceback (most recent call last): File "C:\Users\Python_Coder\Desktop\YOLO_T_ID\Custom-OCR-with-YOLO\Custom_OCRs.py", line 176, in net = cv2.dnn.readNet(modelWeights) cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:739: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211004::ONNXImporter::handleNode'

#Node [Identity]:(onnx::Resize_445) parse error: OpenCV(4.5.4) D:\a\opencv-python\opencv python\opencv\modules\dnn\src\dnn.cpp:5653: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211004::Layer::getMemoryShapes'

**Comment by fengyuentau** [comment]
Could you attach your ONNX model so that we can have a look into the problem? It would be better if you can provide the script as well.

**Comment by connectumaraziz** [comment]
First I trained my model Using yolov5 default parameters, and got best.pt weight in the exp2 folder.
then I convert my model into onnx format for the requirement of OpenCV the script to convert best.pt into best.onnx using below cmd. img_size = 640 640
!python export.py --weights /content/drive/MyDrive/YOLO_T_ID/yolov5/runs/train/exp2/weights/best.pt --include onnx 

After that I try to load this model in OpenCV, code is below

if __name__ == '__main__':
	# Load class names.
	classesFile = "C:/Users/Python_Coder/Desktop/YOLO_T_ID/Custom-OCR-with-YOLO/yolov4-classes.txt"
	classes = None
	with open(classesFile, 'rt') as f:
		classes = f.read().rstrip('\n').split('\n')

	# Load image.
	frame = cv2.imread('C:/Users/Python_Coder/Desktop/YOLO_T_ID/Custom-OCR-with-YOLO/images/12.jpg')

	# Give the weight files to the model and load the network using them.
	modelWeights = "C:/Users/Python_Coder/Desktop/YOLO_T_ID/Custom-OCR-with-YOLO/model/best.onnx"
	**net = cv2.dnn.readNet(modelWeights)**

	# Process image.
	detections = pre_process(frame, net)
	img = post_process(frame.copy(), detections)

But i got error on loading model, the error is completely described above

**Comment by connectumaraziz** [comment]
@shari01

**Comment by zihaomu** [comment]
@connectumaraziz, Yolov5 has been supported by OpenCV dnn, please try to compile OpenCV from the source code. Related issue #22384

**Comment by connectumaraziz** [comment]
Thanks it worked now
