### ISSUE TITLE
OpenCV iOS use in 2022

### ISSUE THREAD

**Issue by ppave** [opencv/opencv#22555]
Hello, I am just getting into OpenCV and want to understand the following:

1. As I understand OpenCV [doesn't support Metal](https://github.com/opencv/opencv/issues/4898), so as a result there is no way for OpenCV to use GPU on iOS devices. Is that correct ?
2. Is my understanding correct that it only makes sense to use OpenCV on iOS devices where OpenCV performance on CPU is good for app use cases?

**Comment by asmorkalov** [comment]
Please use forum.opencv.org for such discussions.
1. Metal is not supported by OpenCV right now.
1. OpenCV has a lot of NEON optimized functions to utilize CPU efficiently. It make sense to use iOS native API for DNN inference, if OpenCV based solution does not perform well.

**Comment by ppave** [comment]
Thank you.
