### ISSUE TITLE
API Discussion about DNN precision

### ISSUE THREAD

**Issue by zihaomu** [opencv/opencv#22578]
## Discussion
The `Net` of OpenCV DNN should be able to let the user choose the calculation precision. 

In order to make DNN run fast enough, we use Winograd to accelerate the 3x3 Convolution layer. Winograd can improve the speed but affects the accuracy. And some models are particularly sensitive to accuracy (like the object detection and semantic segmentation model). Currently, we do not provide users such an option to turn off Winograd branch, which may lead to these models generating the wrong output.

[Example link: ENet](https://github.com/opencv/opencv/blob/4.x/modules/dnn/test/test_torch_importer.cpp#L440-L488) will fail when we use Winograd Branch.

In the future, we may have more accelerated branches similar to Winograd, so it's reasonable to add this feature.

Following are some of my ideas:
1. Add new API to Net class, `net.setPreferPrecision(DNN_HIGH_PRECISION);`
2. Reuse old API, `net.setPreferableTarget(DNN_TARGET_CPU_HIGH_PRECISION);`

Any more suggestions?

**Comment by mshabunin** [comment]
`Net` already have method [enableFusion](https://docs.opencv.org/4.x/db/d30/classcv_1_1dnn_1_1Net.html#af22e2f1a542d80ea797ba38902c726bd) which modifies execution in a similar manner. I my opinion it is better to add corresponding method for Winograd optimization. Even better would be to encapsulate all similar parameters in a separate class in accordance with the [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern).

**Comment by zihaomu** [comment]
Thanks, maybe we can add something like `enableHighPrecision()` to trun off all the branch which will effect the final accuracy.
