### ISSUE TITLE
cv::VideoCapture will affect GPU performance?

### ISSUE THREAD

**Issue by dwygs** [opencv/opencv#22576]
My model takes 6ms when testing a single frame of image, but it takes 8ms when using cv::VideoCapture to get video frame , and after dozens of inferences the time-consuming increases to 12ms.
Win10
Opencv version 4.6

**Comment by asmorkalov** [comment]
OpenCV may use hardware acceleration for Viddeo decoding. It depends on VideoCapture backend and some options. See https://github.com/opencv/opencv/wiki/Video-IO-hardware-acceleration for details.
