### ISSUE TITLE
请问opencv有没有可以支持unet分割网络推理的例程？

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#22599]
### Descripe the feature and motivation

我自己模仿opencv的Enet推理例程，改写了一个Unet推理例程，但是推理错误，不支持Unet里的层？

这都2022年了，opencv怎么不支持unet啊？

**Comment by fengyuentau** [comment]
Unet has been supported. See https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV.

**Comment by wwzh2015** [comment]
> Unet has been supported. See https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV.

Hi，Is there any example cpp I can refer to unet infer？ 

https://github.com/opencv/opencv/blob/master/samples/cpp/segment_objects.cpp

This can be used to unet? please help me? TKS!
