### ISSUE TITLE
3D object size measurment with OpenCV

### ISSUE THREAD

**Issue by HripsimeS** [opencv/opencv#22591]
Hello. I followed the project of Adrian Rosebrock to Measuring size of objects in an image with OpenCV.
https://pyimagesearch.com/2016/03/28/measuring-size-of-objects-in-an-image-with-opencv/
It is a great method to measure 2D object dimensions and I took it as a reference to try build a method to measure for 3D object  dimensions (length, width, and height). 
I was curious to know if is it really possible to do a 3D object measurement with OpenCV. If yes, can you please take a look to my code and see which parts are need to be modified to make it work efficiently. Thanks a lot in advance!!!

https://github.com/HripsimeS/Computer-Vision/blob/main/3d_size.py

**Comment by berak** [comment]
hello, you've reached the opencv bug tracker (bad place for your usage question)

be so kind to close this, and ask again on https://forum.opencv.org/ , where we can help you much better with your problem, thank you.
