### ISSUE TITLE
DNN: need support of the GreaterOrEqual operator from ONNX

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv#22610]
### Descripe the feature and motivation

There is a contributor trying to contribute a model to opencv zoo. Link to the pull request: https://github.com/opencv/opencv_zoo/pull/82. And this model requires the support of GreaterOrEqual operator from ONNX.

### Additional context

There might be other operators that are not supported in the current version of OpenCV. Need to generate a list of operators to check whether there are other unsupported operators.

**Comment by asmorkalov** [comment]
Related issue: https://github.com/opencv/opencv/issues/19977
