### ISSUE TITLE
Wrong reference for A-KAZE paper

### ISSUE THREAD

**Issue by tmichi** [opencv/opencv#22626]
### Descripe the doc issue

A-KAZE paper is cited in 
https://docs.opencv.org/3.4/d8/d30/classcv_1_1AKAZE.html

Reference is found in 
https://docs.opencv.org/3.4/d0/de3/citelist.html#CITEREF_ANB13

> [8] Pablo F Alcantarilla, Jesús Nuevo, and Adrien Bartoli. [Fast explicit diffusion for accelerated features in nonlinear scale spaces](http://www.bmva.org/bmvc/2013/Papers/paper0013/paper0013.pdf). Trans. Pattern Anal. Machine Intell, 34(7):1281–1298, 2011.

However, journal information is not for A-KAZE but for BRIEF. 

M. Calonder, V. Lepetit, M. Ozuysal, T. Trzcinski, C. Strecha and P. Fua, "BRIEF: Computing a Local Binary Descriptor Very Fast," in IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. 34, no. 7, pp. 1281-1298, July 2012, doi: 10.1109/TPAMI.2011.222.

### Fix suggestion

I suggest update opencv/doc/opencv.bib
Paper information can be found at:
http://www.bmva.org/bmvc/2013/Papers/paper0013/index.html
http://www.robesafe.com/personal/pablo.alcantarilla/kaze.html

l. 10 of https://github.com/opencv/opencv/blob/4.x/doc/opencv.bib

@inproceedings{ANB13,
  title={Fast Explicit Diffusion for Accelerated Features in Nonlinear Scale Spaces },
  author={Pablo Alcantarilla and  Jesus Nuevo and Adrien Bartoli },
  year = {2013},
  booktitle = {Proceedings of the British Machine Vision Conference},
  pages={13.1--13.13}
  publisher = {BMVA Press},
  editors={Burghardt, Tilo and Damen, Dima and Mayol-Cuevas, Walterio and Mirmehdi, Majid},
}

**Comment by mshabunin** [comment]
Interesting, does it mean Google Scholar is wrong here? https://scholar.google.com/scholar?lookup=0&q=Fast+Explicit+Diffusion+for+Accelerated+Features+in+Nonlinear+Scale+Spaces
