### ISSUE TITLE
Typo in `BestOf2NearestMatcher` parameter `matches_confindece_thresh`

### ISSUE THREAD

**Issue by Avasam** [opencv/opencv#22632]
### Descripe the doc issue

The parameter `matches_confindece_thresh` of function `BestOf2NearestMatcher` has mistyped "confindece" (should be confidence). Not sure if this is a documentation-only thing, I cannot test it atm, but I noticed it while browsing the docs.

https://docs.opencv.org/4.x/d4/d26/classcv_1_1detail_1_1BestOf2NearestMatcher.html

### Fix suggestion

Rename `matches_confindece_thresh` to `matches_confidence_thresh`

**Comment by ADITYADAS1999** [comment]
hey [asmorkalov](https://github.com/asmorkalov) can I fix this issue by raise a PR?
