### ISSUE TITLE
How to infer unet by opencv?

### ISSUE THREAD

**Issue by wwzh2015** [opencv/opencv#22686]
### Descripe the feature and motivation

Is there any example with ".cpp" or ".py" I can refer to unet inference？

so:

https://github.com/opencv/opencv/blob/master/samples/cpp/segment_objects.cpp

This can be used to unet inference? please help me.

**Comment by dkurt** [comment]
Check https://github.com/opencv/opencv/blob/master/samples/dnn/segmentation.cpp
