### ISSUE TITLE
log a debug message if a capture backend is generally available but isn't capabable of either capture by index or capture by filename

### ISSUE THREAD

**Issue by kallaballa** [opencv/opencv#22699]
### Descripe the feature and motivation

I am working on a few issues pertaining hw accelerated videoio and I experimented with the different backends and settings to get my application to capture from v4l2 while using vaapi for decoding among a few other things.
Anyway it took me considerable time to realize that e.g. the ffmpeg backend doesn't support selecting the capture device by index.
I would like to have at least debug message in place to alert the user to as why capturing failed.

### Additional context

```c++
VideoCapture cap(0, CAP_FFMPEG);
```
The above line fails without a hint on why.

**Comment by kallaballa** [comment]
Implemented: https://github.com/opencv/opencv/commit/0911ba8127c473fe2da3a05884cd848a090bdeeb

**Comment by asmorkalov** [comment]
@kallaballa I simplified your solution a bit and squashed commits. It works as expected now:
```
$ python3 
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> c=cv2.VideoCapture(0, cv2.CAP_FFMPEG)
[DEBUG:0@13.436] global videoio_registry.cpp:206 VideoBackendRegistry VIDEOIO: Builtin backends(9): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930); OBSENSOR(920)
[DEBUG:0@13.436] global videoio_registry.cpp:230 VideoBackendRegistry VIDEOIO: Available backends(9): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930); OBSENSOR(920)
[ INFO:0@13.436] global videoio_registry.cpp:232 VideoBackendRegistry VIDEOIO: Enabled backends(9, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940); UEYE(930); OBSENSOR(920)
[ WARN:0@13.436] global cap.cpp:331 open VIDEOIO(FFMPEG): backend is generally available but can't be used to capture by index
>>> quit()
```

**Comment by Shashi630** [comment]
@asmorkalov 
stark@Shashivardhan:~/yolo-9000/darknet$ ./darknet detector demo cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights -c 0 -t 5000
Demo
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   544 x 544 x   3   ->   544 x 544 x  32  0.511 BFLOPs
    1 max          2 x 2 / 2   544 x 544 x  32   ->   272 x 272 x  32
    2 conv     64  3 x 3 / 1   272 x 272 x  32   ->   272 x 272 x  64  2.727 BFLOPs
    3 max          2 x 2 / 2   272 x 272 x  64   ->   136 x 136 x  64
    4 conv    128  3 x 3 / 1   136 x 136 x  64   ->   136 x 136 x 128  2.727 BFLOPs
    5 conv     64  1 x 1 / 1   136 x 136 x 128   ->   136 x 136 x  64  0.303 BFLOPs
    6 conv    128  3 x 3 / 1   136 x 136 x  64   ->   136 x 136 x 128  2.727 BFLOPs
    7 max          2 x 2 / 2   136 x 136 x 128   ->    68 x  68 x 128
    8 conv    256  3 x 3 / 1    68 x  68 x 128   ->    68 x  68 x 256  2.727 BFLOPs
    9 conv    128  1 x 1 / 1    68 x  68 x 256   ->    68 x  68 x 128  0.303 BFLOPs
   10 conv    256  3 x 3 / 1    68 x  68 x 128   ->    68 x  68 x 256  2.727 BFLOPs
   11 max          2 x 2 / 2    68 x  68 x 256   ->    34 x  34 x 256
   12 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
   13 conv    256  1 x 1 / 1    34 x  34 x 512   ->    34 x  34 x 256  0.303 BFLOPs
   14 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
   15 conv    256  1 x 1 / 1    34 x  34 x 512   ->    34 x  34 x 256  0.303 BFLOPs
   16 conv    512  3 x 3 / 1    34 x  34 x 256   ->    34 x  34 x 512  2.727 BFLOPs
   17 max          2 x 2 / 2    34 x  34 x 512   ->    17 x  17 x 512
   18 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
   19 conv    512  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x 512  0.303 BFLOPs
   20 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
   21 conv    512  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x 512  0.303 BFLOPs
   22 conv   1024  3 x 3 / 1    17 x  17 x 512   ->    17 x  17 x1024  2.727 BFLOPs
   23 conv  28269  1 x 1 / 1    17 x  17 x1024   ->    17 x  17 x28269  16.732 BFLOPs
   24 detection
mask_scale: Using default '1.000000'
Loading weights from ../yolo9000-weights/yolo9000.weights...Done!
video file: -t
[ WARN:0@19.292] global cap.cpp:204 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by name
Couldn't connect to webcam.
: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted

why this warn and how to solve it
