### ISSUE TITLE
about like opencv_videoio_ffmpeg450_64.dll for ubuntu

### ISSUE THREAD

**Issue by leizhu1989** [opencv/opencv#22710]
### Descripe the feature and motivation

hello! when I run a demo to read video in ubuntu, I find that the demo has many dependent libraries,such as libavcodec libswscale libx264 libavformat and so on. It is very hard to put this demo to another PC because of too many dependent libraries should be copy for it. Then whether has some ideas like "opencv_videoio_ffmpeg450_64.dll" for windows to reduce dependent libraries for ubuntu?  I use "sudo apt-get install libavcodec libswscale libavformat ffmpeg" to build opencv for reading video

**Comment by asmorkalov** [comment]
Theoretically you can link dependencies statically, but it may have legal implications with FFmpeg. Please use. forum.opencv.org for questions.
