### ISSUE TITLE
videowriter libraryLoad load opencv_videoio_ffmpeg460_64d.dll

### ISSUE THREAD

**Issue by SunnyTian** [opencv/opencv#22749]
### Descripe the feature and motivation

Can I get opencv_videoio_ffmpeg460_64d.dll and opencv_videoio_ffmpeg460_64d.dll?(Shared libraries for debugging)Thank you!

### Additional context

I try to create video file by VideoWriter but failed,information like following:
backend_plugin.cpp (383) cv::impl::getPluginCandidates Found 3 plugin(s) for FFMPEG
opencv-4.6.0\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop\opencv-4.6.0\vs2017_x64\bin\Debug\opencv_videoio_ffmpeg460_64d.dll => FAILED
opencv-4.6.0\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg460_64d.dll => FAILED
opencv-4.6.0\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_videoio_ffmpeg460_64.dll => FAILED
opencv-4.6.0\modules\videoio\src\backend_plugin.cpp (383) cv::impl::getPluginCandidates Found 2 plugin(s) for INTEL_MFX
opencv-4.6.0\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv-4.6.0\vs2017_x64\bin\Debug\opencv_videoio_intel_mfx460_64d.dll => FAILED
[ INFO:0@51.519] \opencv-4.6.0\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_videoio_intel_mfx460_64d.dll => FAILED

**Comment by alalek** [comment]
You should see these lines in CMake output:

```
...
-- FFMPEG: Downloading opencv_videoio_ffmpeg.dll from https://raw.githubusercontent.com/opencv/opencv_3rdparty/65ec04d4573dcdfa4531f0b9e67f35d8ffff873e/ffmpeg/opencv_videoio_ffmpeg.dll
-- FFMPEG: Downloading opencv_videoio_ffmpeg_64.dll from https://raw.githubusercontent.com/opencv/opencv_3rdparty/65ec04d4573dcdfa4531f0b9e67f35d8ffff873e/ffmpeg/opencv_videoio_ffmpeg_64.dll
-- FFMPEG: Downloading ffmpeg_version.cmake from https://raw.githubusercontent.com/opencv/opencv_3rdparty/65ec04d4573dcdfa4531f0b9e67f35d8ffff873e/ffmpeg/ffmpeg_version.cmake
...
-- General configuration for OpenCV 4.6.0 =====================================
...
--   Video I/O:
...
--     FFMPEG:                      YES (prebuilt binaries)
--       avcodec:                   YES (58.134.100)
--       avformat:                  YES (58.76.100)
--       avutil:                    YES (56.70.100)
--       swscale:                   YES (5.9.100)
--       avresample:                YES (4.0.0)
```

`opencv_videoio_ffmpeg` is downloaded and copied during the OpenCV build by default.
Please check your internet connection and/or proxy configuration.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
