### ISSUE TITLE
Infinite recursion in `window_w32.cpp`.

### ISSUE THREAD

**Issue by dan-masek** [opencv/opencv#22765]
https://github.com/opencv/opencv/blob/2aad039b4f64d8e4a6136388c48d1368c120feec/modules/highgui/src/window_w32.cpp#L2340-L2345

Looks like there's a dereference missing on `window` in the return statement, so that the overload taking `CvWindow&` gets invoked.

**Comment by alalek** [comment]
Thank you for the report!

relates #20281

Try to remove this function or replace to `window.get()`.

**Comment by dan-masek** [comment]
@alalek No problem. There are couple more issues I wanna figure out first and then I'll get to making PRs.
