### ISSUE TITLE
Excess vertical space allocated to toolbar as more trackbars are added in WinAPI HighGUI backend

### ISSUE THREAD

**Issue by dan-masek** [opencv/opencv#22769]
Windows 10 (and likely others)
OpenCV 4.6.0 (and likely going way back)

Related to #22766

C++ code to reproduce:
```
#include "opencv2/highgui.hpp"

int main()
{
    std::string const window_name{ "TrackBars" };
    cv::namedWindow(window_name, cv::WINDOW_AUTOSIZE);
    cv::resizeWindow(window_name, {500, 600 });
    cv::createTrackbar("Slider 1", window_name, nullptr, 255);
    cv::waitKey();
    cv::createTrackbar("Slider 2", window_name, nullptr, 255);
    cv::waitKey();
    cv::createTrackbar("Slider 3", window_name, nullptr, 255);
    cv::waitKey();
    cv::createTrackbar("Slider 4", window_name, nullptr, 255);
    cv::waitKey();
    return 0;
}
```

Observe the growing blank area at the bottom of the toolbar, as controls are added:
![image](https://user-images.githubusercontent.com/10824015/200700397-d3d2d72c-079c-4225-91db-1b98799d1e01.png)
![image](https://user-images.githubusercontent.com/10824015/200700416-c30233d7-6479-4fc0-975a-cab65ce9e0fb.png)
![image](https://user-images.githubusercontent.com/10824015/200700432-daf3b12b-790a-40e2-932c-f04c28b3f0ed.png)
![image](https://user-images.githubusercontent.com/10824015/200700442-6be1bd28-da80-40a1-b09d-c0052554586f.png)

----

Problem is a combination of two factors. First of all, separators are added between the trackbar placeholders, and those end up each taking up a separate row as well:
https://github.com/opencv/opencv/blob/2aad039b4f64d8e4a6136388c48d1368c120feec/modules/highgui/src/window_w32.cpp#L2434-L2447

However, to set the height of the toolbar area, we simply multiply the number of rows by the height of a single trackbar:
https://github.com/opencv/opencv/blob/2aad039b4f64d8e4a6136388c48d1368c120feec/modules/highgui/src/window_w32.cpp#L1563

Since every second row is a separator, which is much less tall than the actual trackbar, we end up overestimating the space needed.

----

Unless there is some variant of windows which requires those separators, it may be the best to just get rid of them. This is what it looks like with no separators (and with resized window):

![image](https://user-images.githubusercontent.com/10824015/200701799-66eff8aa-aa23-4eae-a7c4-48ac8e1ba996.png)
![image](https://user-images.githubusercontent.com/10824015/200701814-8aa06e1a-4848-4c28-82b5-412696d05a5f.png)

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/23261
