### ISSUE TITLE
resize source code

### ISSUE THREAD

**Issue by ardeal** [opencv/opencv#22773]
Hi,

I trained the neural network with resize image, and then I would like to run the same procedure in embedded MCU.
I tried to implement my own resize, however, the output of my resize is always slightly different from the resize of OpenCV.

Furthermore, the resize source code in Opencv is very tough to be run in embedded MCU as there is parallel and C++ feature in the code.

Is there any substitute resize code that outputs the same result as OpenCV?

**Comment by ardeal** [comment]
Hi,

Is there any answer about this question?

**Comment by dkurt** [comment]
Closing as not related to OpenCV. Please use issues for bug reports or feature requests, not usage questions.
