### ISSUE TITLE
The ARM32 Linux platform uses opencv3.4.1

### ISSUE THREAD

**Issue by fanxiaochen456** [opencv/opencv#22793]
### Descripe the doc issue

Hello, I use the ARM32 Linux platform and the operating system is Ubuntu16.04. After compiling Opencv3.4.1 with the cross-compiler, the following errors occurred when I generated an opencv program separately:
The above is my error information
![图片](https://user-images.githubusercontent.com/101849755/201290327-9ce51833-d03a-493c-bafb-1d63211cf42d.png)

**Comment by fanxiaochen456** [comment]
![图片](https://user-images.githubusercontent.com/101849755/201289826-5f8eab43-e304-45cf-b4b1-32ad3eccf736.png)
The above is my error information

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by fanxiaochen456** [comment]
Ok, thank you very much
