### ISSUE TITLE
/opencv/modules/dnn/src/dnn.cpp (1447) : setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by karishmathumu** [opencv/opencv#22815]
##### System information 
**- OpenCV = 4.5.4
- Operating System / Platform => NVIDIA JETSON Orin (Tegra)
- Compiler => Visual Studio 2019
CUDNN 8.6 and CUDA 11.4.**

##### 

I have configured the opencv with cmake-gui, enabling, 

**opencv_dnn_cuda, 

build_opencv_cuda, 

with_cuda, 

with_cudnn, 

with_cublas.**

i also linked ln -s /usr/local/lib/python3/dist-packages/cv2/python-3.8/[cv2.cpython-38-aarch64-linux-gnu.so](http://cv2.cpython-38-aarch64-linux-gnu.so/) cv2.so

The opencv test : import cv2 also works. 

I use this segment in my code.
cout << "Using GPU device" << endl;
net.setPreferableBackend(DNN_BACKEND_CUDA);
net.setPreferableTarget(DNN_TARGET_CUDA);

When run,
it switches to CPU and compiles giving the result in 400 milliseconds.
The issue is displayed as below:
**[ WARN:0] global /home/ubuntu/build_opencv/opencv/modules/dnn/src/dnn.cpp (1447) setUpNet DNN module was not built with CUDA backend; switching to CPU**

**My directory structure is ( i cloned the opencv into my tk_ws workspace)

tk_ws/ build/ bin
tk_ws/opencv-4.5.4
tk_ws/opencv_contrib-4.5.4

Also, in the dnn.cpp is in the path: tk_ws/opencv-4.5.4/modules/dnn/src**

while as per the instructions on https://gist.github.com/YashasSamaga/a84cf2826ab2dc755005321fe17cd15d

I can see the opencv_test_dnn in green

I could not figure out why I am repeatedly failing. 

I would be immensely grateful if you could help me, please.

Warm Regards,
Karishma

**Comment by karishmathumu** [comment]
@WanliZhong Thank you very much for your response.

I apologize, for not mentioning the other details earlier. 

1. I did check my CUDA_TOOLKIT_ROOT_DIR. It is set to CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.4
2.  $nvcc --version: Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_May__4_00:02:26_PDT_2022
Cuda compilation tools, release 11.4, V11.4.239
Build cuda_11.4.r11.4/compiler.31294910_0
3. $ sudo apt-get install cuda-toolkit-*
cuda-toolkit-11-4 is already the newest version (11.4.14-1).
cuda-toolkit-11-4-config-common is already the newest version (11.4.243-1).
cuda-toolkit-11-config-common is already the newest version (11.4.243-1).
cuda-toolkit-config-common is already the newest version (11.4.243-1).

4. I did add the opencv_extra_modules_path while comfiguring
5. Mine is a Jetson Orin, hence set the CUDA_ARCH_BIN = 8.7

![2022-11-17 07_37_47-Window](https://user-images.githubusercontent.com/71717377/202376113-2e62f7ba-4f1c-4484-9669-d2f51cd80b83.png)

![2022-11-17 07_49_10-Window](https://user-images.githubusercontent.com/71717377/202376280-338a9fa8-6b58-4066-902e-104f8229f3e9.png)

**Comment by karishmathumu** [comment]
I have a question about the path of CUDA_TOOLKIT_ROOT_DIR: 
` Must it be /usr/local/cuda-11.4            or               /usr/local/cuda/v11.4 ???`

My cuda is in this section

![2022-11-21 08_59_48-192 168 171 2 (1)](https://user-images.githubusercontent.com/71717377/202995944-3b9786e3-3dcf-47c5-8a41-501b359d43a1.png)

**Comment by WanliZhong** [comment]
@karishmathumu You should set it to `/usr/local/cuda-11.4`. But I have no idea why it doesn't work.

**Comment by karishmathumu** [comment]
Not sure. because I have been repeating the installation process of OPENCV with CUDA and DNN. But it keeps failing while testing the sample tests in cpp.

for example: 
```
#include <iostream>
#include <ctime>
#include <cmath>
#include "bits/time.h"

#include <opencv2/core.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>

#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaarithm.hpp>
#include <opencv2/cudaimgproc.hpp>
#include "opencv2/core/cuda.hpp"
#include "opencv2/cudaarithm.hpp"
#include "opencv2/cudaoptflow.hpp"
#include <opencv2/core/utility.hpp>
#include "opencv2/core.hpp"
#include <opencv2/world.hpp>

#define TestCUDA true
using namespace cv;
using namespace cuda;

int main() {
    std::clock_t begin = std::clock();

        try {
            cv::String filename = "/home/.../test1.png";
            cv::Mat srcHost = cv::imread(filename, cv::IMREAD_GRAYSCALE);

            for(int i=0; i<1000; i++) {
                if(TestCUDA) {
                    cv::cuda::GpuMat dst, src;
                    src.upload(srcHost);

                    //cv::cuda::threshold(src,dst,128.0,255.0, CV_THRESH_BINARY);
                    cv::cuda::bilateralFilter(src,dst,3,1,1);

                    cv::Mat resultHost;
                    dst.download(resultHost);
                } else {
                    cv::Mat dst;
                    cv::bilateralFilter(srcHost,dst,3,1,1);
                }
            }

            //cv::imshow("Result",resultHost);
            //cv::waitKey();

        } catch(const cv::Exception& ex) {
            std::cout << "Error: " << ex.what() << std::endl;
        }

    std::clock_t end = std::clock();
    std::cout << double(end-begin) / CLOCKS_PER_SEC  << std::endl;
}
```



Result:

> $ g++ test.cpp `pkg-config opencv4 --cflags --libs` -o test  
>  $ ./test
> Error: OpenCV(4.5.4) /home/ubuntu/build_opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:106: error: (-216:No CUDA support) The library is compiled without CUDA support in function 'throw_no_cuda'
> 
> 0.047034
