### ISSUE TITLE
Is it possible to pass in multiple conf_thres in cv::dnn::NMSBoxes？

### ISSUE THREAD

**Issue by l0ngjx** [opencv/opencv#22819]
### Descripe the feature and motivation

Now I want to pass in multiple conf_thres for each label, set different conf_thres  for different labels,I found this feature to be implemented in the python version,but I can't find anything related to the C++ version,I wonder if this is achievable and how to do?

**Comment by fengyuentau** [comment]
You can see from the [doc](https://docs.opencv.org/4.x/d6/d0f/group__dnn.html#ga9d118d70a1659af729d01b10233213ee) that `score_threshold` is a float. Are there any existing models using multiple `score_threshold`?

**Comment by l0ngjx** [comment]
Thank you for your answer @fengyuentau 
I didn't find any existing models that use multiple score_threshold,I want to change it to an array to pass in multiple score_threshold,but I'm not sure if this can be achieved

**Comment by fengyuentau** [comment]
I think you can do it in another way without changing the opencv source code:

1. define an array of `score_threshold` of the same length as classes,
2. loop over classes together with the array of `score_threshold`,
3. collect boxes of the same class,
4. send them with the `score_threshold` to `cv::dnn::NMSBoxes`.

**Comment by l0ngjx** [comment]
I see, I'll try this method, thank you
