### ISSUE TITLE
DNN: High memory consumption on 4.x branch

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#22825]
Failed nightly build: http://pullrequest.opencv.org/buildbot/builders/master-win32-vc14/builds/100005

Measurements on Linux (via `/usr/bin/time`) for test `Test_Darknet.read_yolo_voc_stream`:

```
/usr/bin/time ./bin/opencv_test_dnn --test_threads=4 --gtest_filter=Test_Darknet.read_yolo_voc_stream
```

maxresident(k) value from `time` utility:

3.4: 769668
4.x: 2336348 (~3x)

**Comment by alalek** [comment]
relates #22593

**Comment by zihaomu** [comment]
Hi, I will try to fix it.
