### ISSUE TITLE
can opencv support to push video streams to video server, like rtsp/rtmp... ?

### ISSUE THREAD

**Issue by Belial2010** [opencv/opencv#22827]
### Descripe the feature and motivation

nowadays, video live is popular, opencv can receive rtsp/rtmp/usb .etc，but it cloudn't support to transform/push video stream to video server. it's possible to add this new feature?

**Comment by alalek** [comment]
duplicate of #21681

**Comment by Belial2010** [comment]
来信已收到，我会尽快回复您信息。
