### ISSUE TITLE
Depth Encoding FFMPEG 16bit file support

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [opencv/opencv#22872]
### Descripe the feature and motivation

Depth images typically come as type uint16. I've been looking online, and there is pretty lackluster support for depth video compression, which I think is an extremely important problem. For example, I am a part of a group collecting a large robot dataset, and we need to compress our depth data.

Some existing approaches include using:
1) FFV1, but opencv FFMPEG doesn't support 16bit datatypes as of now
2) Converting depth images to color, and then encoding normally: https://dev.intelrealsense.com/docs/depth-image-compression-by-colorization-for-intel-realsense-depth-cameras

It would be super helpful if cv2 could provide some built in functionality for this :)

**Comment by mshabunin** [comment]
I believe it can be closed as we've added FFV1 GRAY16 support to the FFmpeg backend.
