### ISSUE TITLE
Support ffmpeg command line syntax with FFMPEG backend

### ISSUE THREAD

**Issue by kallaballa** [opencv/opencv#22871]
### Describe the feature and motivation

To support complex stream specifiers for VideoWriter/VideoCapture, conversion options and filter graphs with the FFMPEG-backend, I would like to introduce a syntax similar (or identical?) to what ffmpeg (https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_opt.c) offers.

A simple example of what i have in mind:
 ```c++
 VideoCapture("-v trace -f v4l2src -input_format mjpeg -i /dev/video0 -vf scale=320:240", CAP_FFMPEG) cap;
 ```
 
 Before I implement this:
 * Is it a good idea? 
 * What should be the limits?

I am (sadly) aware I can't simply use the ffmpeg code.

**Comment by kallaballa** [comment]
I found following snippet that shows that basic ffmpeg cmdline parsing is simple: https://gist.github.com/cjhanks/2258905

```c++
#include <stdio.h>
#include <iostream>
#include <string>
#include <string.h>

/**
 * This simple argv parser splits a command like:
 * ffmpeg -f libx264 -i  input.avi -acodec libmp3lame -ab 128k -ar 44100 -vcodec 
 * mpeg2video -vf scale=160:128 -b 176k -r 15 -strict -1 -ab  output.mpg
 * 
 * Into its 4 constituent parts.
 *
 * - preamble + input_file_options 
 * - input file name
 * - output_file_options
 * - output file name 
 * 
 * This should work for any ffmpeg command, as this is a requisite of the ffmpeg
 * application.
 *
 * Christopher J. Hanks <cjhanks@cpusage.com>
 */

int 
main(int argc, char* argv[])
{
  std::string input;
  std::string output;
  std::string inp_args;
  std::string out_args;

  bool in_args = true;
  bool in_trigger = false;
  for (int i=1; i<argc; ++i)
    {
      if (in_trigger)
        {
          input = argv[i];
          in_trigger=in_args=false;
        }
      else if (i == argc-1)
        output = argv[i];
      else if (strcmp(argv[i],"-i") == 0)
        in_trigger = true;
      else
        {
          if (in_args)
            inp_args += std::string(argv[i])+" ";
          else  
            out_args += std::string(argv[i])+" ";
        }
    }

  std::cerr<<"Input:  "<<input<<std::endl;
  std::cerr<<"Output: "<<output<<std::endl;
  std::cerr<<"ArgsIn: " << inp_args <<std::endl;
  std::cerr<<"ArgsOut:" << out_args <<std::endl;
  std::cerr<<" ----------------------------"<<std::endl;
  std::cerr<<inp_args << " " << input << " " << out_args << " " <<output << std::endl;
}
```
Maybe a good restriction for starters is to _not_ allow filter graphs which makes this feature much easier because building the filtergraph (from the code i read) is rather complex. Also filtergraphs are not strictly necessary to make this  feature useful.

**Comment by alalek** [comment]
It should be a FFmpeg feature with one function of FFmpeg API (similar to GStreamer "manual" pipelines).
Otherwise we should not support that from strategic perspective and the maintenance hell (lack of documentation and constant requests for ffmpeg command-line behavior).

**Comment by kallaballa** [comment]
Alright I undrstand
