### ISSUE TITLE
cv::hasNonZero()

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#22948]
### Descripe the feature and motivation

Currently, checking if a matrix is all-zeros can be done with `(cv::countNonZeros(m)==0)`
If the exact number of nz values is irrelevant, some `cv::hasNonZeros()` would stop parsing the matrix at first non-zero value, for a performance gain.

Use cases :

- a mask is all zero and could be released instead of propagated in function calls
- checking if at least one pixel pass a predicate after some global function like `cv::compare()`

I have submitted a PR : [#22947](https://github.com/opencv/opencv/pull/22947)

**Comment by VadimLevin** [comment]
Closed by https://github.com/opencv/opencv/pull/22947
