### ISSUE TITLE
VCPKG feature for Intel's Inference Engine

### ISSUE THREAD

**Issue by JaviBite** [opencv/opencv#22950]
### Descripe the feature and motivation

Hi!

I think actually there is no "feature" to build opencv with Intel's Inference Engine support (OpenVINO, I guess). I don't know if is it there any fast solution from compile opencv from source code with the -DWITH_OPENVINO=ON flag and that stuff.

So I'm requesting if it is possible to have a “feature” like the others for cuda support, dnn modules, contrib, etc. but for the Intel's Inference Engine,

Thank you so much!

**Comment by mshabunin** [comment]
There is a configuration option `WITH_OPENVINO`: https://github.com/opencv/opencv/blob/1788c93aeaefc5d3030e87d50bbf30a73094cfec/CMakeLists.txt#L300 It enables OpenVINO support in _dnn_ and _gapi_ modules. Or what do you require?

If it is about VCPKG-related changes, then this is a wrong place to request a feature. Check this location instead: https://github.com/microsoft/vcpkg/tree/master/ports/opencv4 .

See also: https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html#tutorial_config_reference_dnn
