### ISSUE TITLE
.clang_format file in wiki is not in the correct format

### ISSUE THREAD

**Issue by feuerste** [opencv/opencv#22960]
### Descripe the doc issue

https://github.com/opencv/opencv/wiki/.clang_format has an invalid entry `SortIncludes: Never`. According to https://releases.llvm.org/12.0.0/tools/clang/docs/ClangFormatStyleOptions.html it must be a bool, e.g.:
```
SortIncludes: false
```

### Fix suggestion

Replace `SortIncludes: Never` with `SortIncludes: false`.
Thank you!

**Comment by mshabunin** [comment]
Fixed as suggested.
