### ISSUE TITLE
Truncated sentenced in boxPoints documentation

### ISSUE THREAD

**Issue by domef** [opencv/opencv#22975]
### Descripe the doc issue

There is a truncated sentence in [boxPoints](https://docs.opencv.org/4.6.0/d3/dc0/group__imgproc__shape.html#gaf78d467e024b4d7936cf9397185d2f5c).
The `box` parameter says `The input rotated rectangle. It may be the output of`.

### Fix suggestion

It could be `It may be the output of minAreaRect.`

**Comment by taham655** [comment]
can i help with this?
