### ISSUE TITLE
Give it option to build opencv x86 static lib on a ARM M1 mac

### ISSUE THREAD

**Issue by lucasjinreal** [opencv/opencv#22985]
### Descripe the feature and motivation

Give it option to build opencv x86 static lib on a ARM M1 mac.

Currently, whenever enviroment set, opencv always build arm static on a arm mac, this is no problem, but sometimes users need  x86 lib on M1 mac, For example, build a thirdparty lib for UE5.

### Additional context

Give it option to build opencv x86 static lib on a ARM M1 mac.

Currently, whenever enviroment set, opencv always build arm static on a arm mac, this is no problem, but sometimes users need  x86 lib on M1 mac, For example, build a thirdparty lib for UE5.

**Comment by dkurt** [comment]
This must be covered by CMake's cross-compilation options.
