### ISSUE TITLE
Error 404 on the `contribute` link in Wiki

### ISSUE THREAD

**Issue by Eugene-Fed** [opencv/opencv#23068]
### Descripe the doc issue

Original path linsk to [https://opencv.org/about.html#Contribute] and gets the 404 Error.

![404_Page_not_found](https://user-images.githubusercontent.com/59748404/210130823-57789fdd-c21d-423c-9b9e-2cb24ee9ded5.PNG)

### Fix suggestion

To add `#Contribute` anchor on `About` page
Change link to [https://opencv.org/about/#Contribute]

**Comment by ADITYADAS1999** [comment]
hey [Eugene-Fed](https://github.com/Eugene-Fed) can I solve this issue? , If this is still open.

**Comment by asmorkalov** [comment]
@philnelson could you handle this?
