### ISSUE TITLE
Provide a way to read an image with IMREAD_UNCHANGED and apply exif orientation

### ISSUE THREAD

**Issue by guillaume-tgl** [opencv/opencv#23122]
### Descripe the feature and motivation

I'd like to read my images with IMREAD_UNCHANGED so that the number of channels is automatically inferred from the image file, but I'd like the exif orientation to be applied. All other configurations are supported except this one:
- IMREAD_COLOR -> apply exif
- IMREAD_COLOR | IMREAD_IGNORE_ORIENTATION -> ignore exif
- IMREAD_UNCHANGED -> ignore exif

### Additional context

I'd be glad to add a PR but I'm not sure what's the best solution to modify these flags.

**Comment by vrabaud** [comment]
Probably related to https://github.com/opencv/opencv/issues/21695

**Comment by vrabaud** [comment]
BTW, a way to achieve this is to do:
```c++
int flags=cv::IMREAD_UNCHANGED
flags&=~cv::IMREAD_IGNORE_ORIENTATION
```

**Comment by guillaume-tgl** [comment]
Hmm, I haven't tested that, but if this works, then we can close this issue 👍

**Comment by sturkmen72** [comment]
Documentation says
```
If EXIF information is embedded in the image file, the EXIF orientation will be taken into account,
    and thus the image will be rotated accordingly unless the flags @ref IMREAD_IGNORE_ORIENTATION

```
i propose to make changes to get following results

```
IMREAD_UNCHANGED | IMREAD_IGNORE_ORIENTATION -> ignore exif
IMREAD_UNCHANGED -> apply exif
```

**Comment by asmorkalov** [comment]
[cv::IMREAD_ANYCOLOR](https://docs.opencv.org/4.x/d8/d6a/group__imgcodecs__flags.html#gga61d9b0126a3e57d9277ac48327799c80ab6573b69300c092b61800222fe555953)?

**Comment by vrabaud** [comment]
@asmorkalov , `cv::IMREAD_ANYCOLOR` will not keep the alpha, per https://github.com/opencv/opencv/blob/71581d9c97b2af226f665b3fcf8422593845c5c5/modules/imgcodecs/src/loadsave.cpp#L95

**Comment by asmorkalov** [comment]
Please take a look on https://github.com/opencv/opencv/pull/26181. Suleiman used the following combination to achieve similar behaviour:
```
 * The flags parameter of the imread function is set as IMREAD_COLOR | IMREAD_ANYCOLOR | IMREAD_ANYDEPTH.
 * Using this combination is an undocumented trick to load images similarly to the IMREAD_UNCHANGED flag,
 * preserving the alpha channel (if present) while also applying the orientation. 
 ```
