### ISSUE TITLE
How disable MT default on MSVC?

### ISSUE THREAD

**Issue by jinfagang** [opencv/opencv#23130]
### Descripe the doc issue

Got errors when link opencv.lib with Unreal Engine:

```
  检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(SharedPCH.Engine.ShadowErrors.h.obj 中)
```

UE default using MD, but opencv default using MT

How to enable MD while still using static lib?

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by jinfagang** [comment]
thanks. I will post it on forumn.

Could u kindly tell me which flag should be set for now?

**Comment by alalek** [comment]
You need to take a look in direction of `BUILD_WITH_STATIC_CRT=OFF` flag.

**Comment by jinfagang** [comment]
thank u so much, i am trying it
