### ISSUE TITLE
There is no python documentation for constructors in OpenCV

### ISSUE THREAD

**Issue by dan-masek** [opencv/opencv#23133]
Aruco's CharucoBoard/GridBoard constructor Python signature missing in docs:

This applies only to 4.7.0, and seems to be a result of the move from contrib and [changes](https://github.com/opencv/opencv/pull/22986/files#diff-09508dfcb283f5b8f2e58538584a58ce28d369f8c7e23705f004f7d15e6f40e9) done in the process.

See https://docs.opencv.org/4.7.0/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a6cbc67e2253bb47d1a0f942f9db9efde and https://docs.opencv.org/4.7.0/de/d05/classcv_1_1aruco_1_1GridBoard.html#a9ccf1f5b7ccf96cf24fcb1d9e454f40f

This seems rather unfortunate, given that the name of the constructor, as well as its signature have changed.

**Comment by AleksandrPanov** [comment]
There is no python documentation for constructors in OpenCV, see, for example, [dnn classes](https://docs.opencv.org/4.7.0/d0/dd5/classcv_1_1dnn_1_1ClassificationModel.html).

**Comment by asmorkalov** [comment]
Python bindings signatures are added to Doxygen documentation with `pyopencv_signatures.json`. The file is generated by python bindings generator. The constructors are there, but namespace is handled incorrectly, e.g.:
```
    "cv::aruco::Dictionary::cv::aruco::Dictionary::Dictionary": [
        {
            "name": "cv.aruco.Dictionary",
            "arg": "",
            "ret": "<aruco_Dictionary object>"
        },
        {
            "name": "cv.aruco.Dictionary",
            "arg": "bytesList, _markerSize[, maxcorr]",
            "ret": "<aruco_Dictionary object>"
        }
    ],
```
