### ISSUE TITLE
Draw Multiple Boxes in one shot

### ISSUE THREAD

**Issue by AbdelsalamHaa** [opencv/opencv#23140]
### Descripe the feature and motivation

With the current development of a lot of Object detection models, sometimes drawing many boxes like 100 or 200 boxes could be time-consuming in python. 

I wonder if Opencv Would like to consider a function to draw many boxes in one shot. So it will speed up the process instead of drawing one by one using for loop.

**Comment by Rahul081203** [comment]
I would like to work on this issue, so can you please assign me this issue.

**Comment by dkurt** [comment]
[cv.drawContours](https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html#ga746c0625f1781f1ffc9056259103edbc) is perfect for it. For example, this is how you may modify [Object Detection](https://github.com/opencv/opencv/blob/4.x/samples/dnn/object_detection.py) sample:
```python
drawBoxes = []
for i in indices:
    box = boxes[i]
    left = box[0]
    top = box[1]
    width = box[2]
    height = box[3]
    drawBoxes.append(np.array([[left, top], [left + width, top], [left + width, top + height], [left, top + height]]))
cv.drawContours(frame, drawBoxes, -1, (0, 0, 255))
```
