### ISSUE TITLE
Python Link is broken

### ISSUE THREAD

**Issue by KinzaaSheikh** [opencv/opencv#23147]
### Describe the doc issue

In the "Introduction to OpenCV-Python Tutorials" page, the link for Python refresher named "A Quick guide to Python - [A Byte of Python](http://swaroopch.com/notes/python/)" is broken and leads to a 404 error page.

### Fix suggestion

Change the link to direct us to somewhere that is maintained. My personal recommendation is:
https://www.freecodecamp.org/news/the-python-guide-for-beginners/

**Comment by kachhadiyaraj15** [comment]
https://github.com/opencv/opencv/pull/23159/commits/e485c07add2234cff25b2e6270368c38cd939b4c
check it

**Comment by kachhadiyaraj15** [comment]
> ### Describe the doc issue
> In the "Introduction to OpenCV-Python Tutorials" page, the link for Python refresher named "A Quick guide to Python - [A Byte of Python](http://swaroopch.com/notes/python/)" is broken and leads to a 404 error page.
> 
> ### Fix suggestion
> Change the link to direct us to somewhere that is maintained. My personal recommendation is: https://www.freecodecamp.org/news/the-python-guide-for-beginners/

https://github.com/opencv/opencv/pull/23159/commits/e485c07add2234cff25b2e6270368c38cd939b4c
 check it

**Comment by KinzaaSheikh** [comment]
> > ### Describe the doc issue
> > In the "Introduction to OpenCV-Python Tutorials" page, the link for Python refresher named "A Quick guide to Python - [A Byte of Python](http://swaroopch.com/notes/python/)" is broken and leads to a 404 error page.
> > ### Fix suggestion
> > Change the link to direct us to somewhere that is maintained. My personal recommendation is: https://www.freecodecamp.org/news/the-python-guide-for-beginners/
> 
> [e485c07](https://github.com/opencv/opencv/commit/e485c07add2234cff25b2e6270368c38cd939b4c) check it

Thanks for raising the issue. I was not sure about how to do that!

**Comment by tnguyenken** [comment]
Hi, is this still being worked on? I can pick it up if not.

**Comment by kachhadiyaraj15** [comment]
Hello Kenny,
I am working on it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
