### ISSUE TITLE
[ERROR:0@0.171] global onnx_importer.cpp:1054 cv::dnn::dnn4_v20221220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Mod]:(onnx_node!/net/decoder/b4/attn/Mod) from domain='ai.onnx'

### ISSUE THREAD

**Issue by GGS92carmnad** [opencv/opencv#23174]
### Describe the feature and motivation

**System information:**
OpenCV 4.7.0-dev
Windows 10 x64
C++

**Description:**
I have trained a PyTorch model that is based on the UNetFormer architecture, and I have exported it to ONNX opset 11:
https://drive.google.com/file/d/1x5XVQ8lfm4tBacCTZaU3uP-A_3MyYuRr/view?usp=sharing

The cv::Exception message:
```
OpenCV(4.7.0-dev) opencv-4.x\modules\dnn\src\onnx\onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
Node [Mod@ai.onnx]:(onnx_node!/net/decoder/b4/attn/Mod) parse error: OpenCV(4.7.0-dev) opencv-4.x\modules\dnn\src\onnx\onnx_importer.cpp:375: error: (-215:Assertion failed) (bool)layer in function 'cv::dnn::dnn4_v20221220::runLayer'
```

**Code to reproduce:**
`dnn::Net net = dnn::readNet("unetformer.onnx");`

**Comment by fengyuentau** [comment]
Mod operator from your model is not supported in OpenCV DNN for now. You can have a try with onnx-simplifier for a quick fix:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/17219438/214280619-7c9d85f7-1eca-4adf-9bf3-0288c03a1b7d.png">

**Comment by GGS92carmnad** [comment]
> Reference

Thank you, no only has that worked but it's definitely streamlined it altogether.

**Comment by GGS92carmnad** [comment]
> Mod operator from your model is not supported in OpenCV DNN for now. You can have a try with onnx-simplifier for a quick fix:
> 
> <img alt="image" width="1028" src="https://user-images.githubusercontent.com/17219438/214280619-7c9d85f7-1eca-4adf-9bf3-0288c03a1b7d.png">

Thank you, no only has that worked but it's definitely streamlined it altogether.

**Comment by sainisatish** [comment]
error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
> Node [Split@ai.onnx]:(onnx_node!/model.24/Split) parse error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\slice_layer.cpp:274: error: (-215:Assertion failed) splits > 0 && inpShape[axis_rw] % splits == 0 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'
> 


[ERROR:0@62.976] global onnx_importer.cpp:1054 cv::dnn::dnn4_v20221220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 3 outputs: [Split]:(onnx_node!/model.24/Split) from domain='ai.onnx'

I have also tried to simplify the model , but no Luck.

**Comment by qqqhhh-any** [comment]
I met the same bug  when I tried to load yolov8n.onnx.I have also tried to simplify the model , but no Luck.

**Comment by fengyuentau** [comment]
@sainisatish @qqqhhh-any Please, submit new issues with your models attached for us to reproduce your problem.

**Comment by qqqhhh-any** [comment]
@fengyuentau https://github.com/ultralytics/ultralytics/issues/2198
