### ISSUE TITLE
Unable to run the Simple RTSP program in docker

### ISSUE THREAD

**Issue by georgethomas08** [opencv/opencv#23170]
OpenCV => 4.7
Operating System / Platform => ubuntu 20.04
Compiler => python

I need to take and RTSP stream which is currently from VLC player rtsp://localhost:8554 to the program running inside the docker and the docker container has to give the video output. for that I did like this but everytime I'm getting the same error which is related qt and xcb Please look into below details ind dockerfile and command

Kindly help me to resolve this issue 

Hi I'm trying to dockerize this code
************************************************************************** CODE *********************************************************************
```
import cv2
import os

RTSP_URL = 'rtsp://0.0.0.0:8554/'

os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'rtsp_transport;udp'

cap = cv2.VideoCapture(RTSP_URL, cv2.CAP_FFMPEG)

if not cap.isOpened():
    print('Cannot open RTSP stream')
    exit(-1)

while True:
    _, frame = cap.read()
    cv2.imshow('RTSP stream', frame)

    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
```
************************************************************************** CODE *********************************************************************
Dockerfile below:-

*************************************************************************DOCKERFILE**************************************************************
```
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN mkdir /app

WORKDIR /app
RUN chmod -R 777 /app
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive TZ=Asia/Kolkata apt install -y tzdata
RUN apt install --no-install-recommends -y python3-pip 
RUN apt-get install -y libgl1-mesa-dev
RUN apt-get install -y libglib2.0-0
RUN pip install opencv-python
WORKDIR /app
COPY . .
CMD ["python3", "-u", "import_cv2.py"]
```
*************************************************************************END*************************************************************************

RUN command: docker run -it --net=host --device /dev/video1 -p 8554:8554 -v /tmp/.X11-unix/:/tmp/.X11-unix abab670c544b
```
ERROR I'm getting is 

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/app/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

**Comment by andreemidio** [comment]
@georgethomas08 

Your error is show the frame in your docker, but docker, don't make this natively, you will need to use x11 to export videos in your DockerFile 

https://github.com/mviereck/x11docker


Comand to build a docker image

docker build --rm -t "name:latest" .
docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --name name name
