### ISSUE TITLE
Support ReduceSum ONNX layer with axis=1, keepdim=1

### ISSUE THREAD

**Issue by ArutyunovG** [opencv/opencv#23221]
### Descripe the feature and motivation

Provide support for ReduceSum (or any for that matter) onnx reduction layer with parameters
axis = 1
keepdim = 1
for NCHW input

Currently, from what I see in implementation, it is expected, that all CHW are expected to be flattened, if I provide axis=1, but actually I just want to sum feature maps along channels dimension.

**Comment by asmorkalov** [comment]
@ArutyunovG could you try OpenCV 4.x branch and update the issue. Alexander cannot reproduce the issue with modern OpenCV.
