### ISSUE TITLE
Proposal: Delay load option for OpenCV modules?

### ISSUE THREAD

**Issue by CSBVision** [opencv/opencv#23235]
### Descripe the feature and motivation

In #23187 it was discussed to optionally enable a delay load option of OpenCV's modules on Windows. This means that modules with heavy dependencies - for example the Python bindings with enabled CUDA support and contrib build - could delay load their dependencies. This yields a more flexible library distribution process by allowing the user to only distribute the actually needed instead of all modules, i.e. ignore unused DLLs.

As we recently worked on integrating the delay load option for CUDA libraries (cf. #22675 and #23209), it is relatively straightforward to integrate this: Define the `/DELAYLOAD:opencv_<module><version>.dll` flag for all enabled modules (exepct core as this is always required) and introduce a CMake variable `OPENCV_ENABLE_DELAYLOAD` that controls whether these flags are set or not.

Still, we wanted to propose / discuss this feature before implementing it. If you think this is a useful feature, the main question is in which CMake script it should be implemented.

**Comment by mbechard** [comment]
I'll mention this is particularly useful for the CUDA modules. If they are loaded on a GPU whose binary architecture isn't included (for example a new one that is released after the binaries were compiled) then the loading of the OpenCV binaries will take several minutes as every CUDA kernel in OpenCV gets JIT compiled for the native GPU architecture.
Delay loading would allow these pauses to be spread out and avoided when not needed.

**Comment by CSBVision** [comment]
We just implemented this feature. Actually it was a bit more complicated as expected because the linker flags have to be defined at the right moment: After the modules are known (to know which flags have to be set) but before generating the respective project files. It works as expected in our tests, it's up to the maintainers to decide whether this is a useful feature or not. We think so, too, so hopefully the PR gets merged.
