### ISSUE TITLE
QRCodeDetector - QR Code detected but no decoded text

### ISSUE THREAD

**Issue by EmilienPluvinage** [opencv/opencv#23249]
### Expected behaviour

I tried to decode the following qrCode:
![result](https://user-images.githubusercontent.com/98469697/218331945-05f8f58f-6cee-4ec1-a240-25582ddc450b.png)

The expected output is the string : "The key is /qrcod_OMevpf" (which was confirmed by a qrcode scanner app from my phone).

### Actual behaviour

The QR Code was detected but the decoded text is empty.

I opened a [thread on stackoverflow](https://stackoverflow.com/questions/75425729/issue-with-qr-code-reading-with-opencv-or-pyzbar) and other users have confirmed having the same issue with this image.

### Steps to reproduce

```image = cv2.imread(imgAbsolutePath)
    qrCodeDetector = cv2.QRCodeDetector()
    decodedText, points, _ = qrCodeDetector.detectAndDecode(image)
    if points is not None:
    # QR Code detected handling code
        print("QR code detected")
        print(decodedText)    
    else:
        print("QR code not detected")```

**Comment by asmorkalov** [comment]
Thanks for the issue report. I moved it to main OpenCV repo as it's generic algorithm failure and does not relate to Python bindings. I reproduced the issue partially with OpenCv 4.7.0. The QR code is detected correctly, but not decoded by some reason.
```
Python 3.8.0 (default, Dec  9 2021, 17:53:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2 as cv
i>>> img = cv.imread("qrcode-repro.png")
>>> qrCodeDetector = cv.QRCodeDetector()
>>> qrCodeDetector.detectAndDecode(img)
('', array([[[ 18.      ,  18.      ],
        [281.      ,  19.003817],
        [281.      , 283.0111  ],
        [ 18.      , 280.0889  ]]], dtype=float32), None)
```

**Comment by spometun** [comment]
I experienced the same problem - couldn't decode simple very clear QR code, while my smartphone's camera read it easily.

**Comment by amangupta201** [comment]
Hey can you please assign me this issue?
