### ISSUE TITLE
Structured Append mode support in QR code decoder

### ISSUE THREAD

**Issue by AleksandrPanov** [opencv/opencv#23245]
### Descripe the feature and motivation

OpenCV supports generating QR codes in Structured Append mode, but decoder doesn't support Structured Append mode. The problem was discussed in PR #23168.

**Comment by ighoshsubho** [comment]
Hey @AleksandrPanov, I want to work on this issue!

**Comment by AleksandrPanov** [comment]
Hey @ighoshsubho, thank you) You can get started with this guide: https://github.com/opencv/opencv/wiki/How_to_contribute
