### ISSUE TITLE
OpenCV with OpenVino doesn't work (C++)

### ISSUE THREAD

**Issue by ArsenyStahkov** [opencv/opencv#23256]
I have built OpenCV with OpenVino and I used the following CMake flags:

%cmaketool% -DBUILD_SHARED_LIBS=OFF -DOPENCV_ENABLE_NONFREE=ON -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DWITH_OPENVINO=ON ^
-DBUILD_opencv_gapi=OFF -DOPENCV_DNN_OPENVINO=ON ^
-DOpenVINO_DIR=%openvino-runtime%\cmake ^
-DOPENCV_EXTRA_MODULES_PATH="..\%contrib-dir%" ^
-G "Visual Studio 16 2019" -A x64 ..\%sources-dir%

But I can't read a model. My code:

```
void TestOpenVinoModel()
{
    string mapping_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.mapping";
    string xml_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.xml";
    string bin_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.bin";

    Net openvino_model = readNetFromModelOptimizer(xml_path, bin_path);
}

int main()
{
    TestOpenVinoModel();

    return 0;
}
```

The program drops on the 715th string of net_openvino.cpp file. I get the error:

![изображение](https://user-images.githubusercontent.com/76564343/219029484-4592a2ed-323c-475d-9fdd-1c716ab4901d.png)

Can anybody help me? Maybe I build OpenCV incorrectly?

**Comment by alalek** [comment]
Which versions of OpenVINO and OpenCV are used?
Did you run opencv_test_dnn tests?

**Comment by alalek** [comment]
> `\x64\Debug\`

Please ensure that there is no mess between Debug/Release modes of different libraries.

**Comment by ArsenyStahkov** [comment]
> 

![изображение](https://user-images.githubusercontent.com/76564343/219052784-73d84d16-7965-42a7-b408-04b8ab374726.png)
As far as I understand, there is no mess. But I'm forced to add these dll files, the program demands them.

**Comment by alalek** [comment]
OpenCV 4.7.0 DNN tests pass with OpenVINO 2022.3 in both Release/Debug modes.

- OpenVINO 2022.3 is got from here: https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/windows/
- OpenVINO runtime is configured through `setupvars.bat` (no copying hijacks)
- OpenCV CMake command: `cmake -G "Visual Studio 16 2019" -A x64 ../opencv -DWITH_OPENVINO=ON`

---

Provided reproducer is not complete as there is no input data (models) provided.

**Comment by ArsenyStahkov** [comment]
> OpenCV 4.7.0 DNN tests pass with OpenVINO 2022.3 in both Release/Debug modes.
> 
>     * OpenVINO 2022.3 is got from here: https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/windows/
> 
>     * OpenVINO runtime is configured through `setupvars.bat` (no copying hijacks)
> 
>     * OpenCV CMake command: `cmake -G "Visual Studio 16 2019" -A x64 ../opencv -DWITH_OPENVINO=ON`
> 
> 
> Provided reproducer is not complete as there is no input data (models) provided.

Did you set only one flag -DWITH_OPENVINO=ON ? You built the project with dynamic linking (because BUILD_SHARED_LIBS is ON default). Can you build with the flags that I used?

**Comment by alalek** [comment]
Well, crash is reproduced. This is an issue related to incompatibility of build configuration.

To be compatible with OpenVINO binary packages (which is build as shared dlls) and using `BUILD_SHARED_LIBS=OFF` we need to specify `BUILD_WITH_STATIC_CRT=OFF` additional option:

```
cmake ... -D-DWITH_OPENVINO=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_WITH_STATIC_CRT=OFF
```

**Comment by ArsenyStahkov** [comment]
> OFF

I tried. But now I have the following problem:
![изображение](https://user-images.githubusercontent.com/76564343/219362656-645cdd1c-05c4-474e-9c78-361fdcb30cec.png)

How can I get rid of these mistakes?

**Comment by ArsenyStahkov** [comment]
> 

I set /MDd mode for Runtime Library. Now I have this:
![изображение](https://user-images.githubusercontent.com/76564343/219363564-97eddafb-d44c-4f98-9b0c-c307af769ec5.png)

**Comment by ArsenyStahkov** [comment]
> To be compatible with OpenVINO binary packages (which is build as shared dlls) and using `BUILD_SHARED_LIBS=OFF` we need to specify `BUILD_WITH_STATIC_CRT=OFF` additional option:

Thank you!

**Comment by ArsenyStahkov** [comment]
> Well, crash is reproduced. This is an issue related to incompatibility of build configuration.
> 
> To be compatible with OpenVINO binary packages (which is build as shared dlls) and using `BUILD_SHARED_LIBS=OFF` we need to specify `BUILD_WITH_STATIC_CRT=OFF` additional option:
> 
> ```
> cmake ... -DWITH_OPENVINO=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_WITH_STATIC_CRT=OFF
> ```

But I faced a new problem. I use the function
`Mat detections = openvino_model.forward();`
and program failed with the error:
![изображение](https://user-images.githubusercontent.com/76564343/219584211-7bc01794-d385-436f-b609-dc564936b73e.png)

Could you tell me what the reason of this error?

**Comment by dkurt** [comment]
@ArsenyStahkov, can you share model input shapes (from IR) and actual input shape in `setInput`?

**Comment by ArsenyStahkov** [comment]
> @ArsenyStahkov, can you share model input shapes (from IR) and actual input shape in `setInput`?

My code:

```
void TestOpenVinoModel()
{
    // Our model
    //string mapping_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.mapping";
    //string xml_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.xml";
    //string bin_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.bin";
    
    // Another model
    string mapping_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.mapping";
    string xml_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.xml";
    string bin_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.bin";

    // Load the OpenVINO plugin for OpenCV
    Net openvino_model = readNetFromModelOptimizer(xml_path, bin_path);
    
    // Set target device to CPU
    openvino_model.setPreferableTarget(DNN_TARGET_CPU);

    // Load an image
    Mat img = imread("C:\\ROOT1\\opencv_build_test\\car_300x300.jpg");

    // Preprocess the image
    Mat blob = blobFromImage(img, 1.0, Size(), Scalar(), true, false);

    // Set input data for the network
    openvino_model.setInput(blob);

    // Run forward pass to get the output
    Mat detections = openvino_model.forward();

    // Post-process the output to extract the bounding boxes
    Mat detections_reshaped = detections.reshape(1, detections.total() / 7);

    // Draw bounding boxes on the original image
    for (int i = 0; i < detections_reshaped.rows; ++i) {
        float confidence = detections_reshaped.at<float>(i, 2);
        if (confidence > 0.5) {
            int x_left = static_cast<int>(detections_reshaped.at<float>(i, 3) * img.cols);
            int y_top = static_cast<int>(detections_reshaped.at<float>(i, 4) * img.rows);
            int x_right = static_cast<int>(detections_reshaped.at<float>(i, 5) * img.cols);
            int y_bottom = static_cast<int>(detections_reshaped.at<float>(i, 6) * img.rows);

            rectangle(img, Point(x_left, y_top), Point(x_right, y_bottom), Scalar(0, 0, 255), 2);
        }
    }

    // Display the resulting image
    imshow("Image", img);
    waitKey();
}
```

The model:
[files_openvino_2.zip](https://github.com/opencv/opencv/files/10764674/files_openvino_2.zip)

**Comment by dkurt** [comment]
```xml
<data element_type="u8" shape="1,300,300,3"/>
```
Wrong input shape. Make model accept NCHW input layput.

**Comment by ArsenyStahkov** [comment]
> 

What exactly do you mean? Could you write the correct string?

**Comment by ArsenyStahkov** [comment]
> ```
> <data element_type="u8" shape="1,300,300,3"/>
> ```
> 
> Wrong input shape. Make model accept NCHW input layout.

What exactly do you mean? Could you write the correct string?

**Comment by dkurt** [comment]
@ArsenyStahkov, there are two options:
1. Change model input layout from NHWC to NCHW:
```bash
mo --input_model frozen_inference_graph.pb --input_shape "[1, 300, 300, 3]" --layout "input(nhwc->nchw)"
```
2. Or keep model as is but `setInput` with NHWC data:
```cpp
Mat blob;
cvtColot(img, blob, COLOR_BGR2RGB);
blob = blob.reshape(1, {1, 300, 300, 3});

openvino_model.setInput(blob);
```

**Comment by ArsenyStahkov** [comment]
> 1. Change model input layout from NHWC to NCHW:

Excuse me, what is the model input layout you're talking about? (Code changes with cvtColor didn't work for me, unfortunately).
I don't convert models. My colleague does it. My task is only run the model using C++.

**Comment by dkurt** [comment]
It's a data layout. N-batch, C-channels, H-height, W-width. OpenCV reads images in HWC layout (interleaded channels). TensorFlow operates with NHWC input, but other frameworks usually with NCHW. `blobFromImage` translated HWC image to NCHW blob (read the documentation). So you either modify model to accept NCHW input (approach 1) either change C++ code and replace `blobFromImage` to a different preprocessing.

> (Code changes with cvtColor didn't work for me, unfortunately).

Didn't work how? Is there accuracy issue or error message?

**Comment by ArsenyStahkov** [comment]
> Didn't work how? Is there accuracy issue or error message?

The terminal writes:

[ INFO:0@0.350] global ie_ngraph.cpp:860 cv::dnn::InfEngineNgraphNet::initPlugin DNN/IE: Calling LoadNetwork(device=CPU)...
OpenCV(4.7.0) Error: Unspecified error (Failed to initialize Inference Engine backend (device = CPU): Cannot load library 'openvino_intel_cpu_plugind.dll': 126 from cwd: C:\ROOT1\opencv_build_test\test_neur_opencv\test_neur_opencv) in cv::dnn::InfEngineNgraphNet::initPlugin, file C:\opencv_build\sources\modules\dnn\src\ie_ngraph.cpp, line 865
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.7.0) Error: Unspecified error (Failed to initialize Inference Engine backend (device = CPU): Cannot load library 'openvino_intel_cpu_plugind.dll': 126 from cwd: C:\ROOT1\opencv_build_test\test_neur_opencv\test_neur_opencv) in cv::dnn::InfEngineNgraphNet::initPlugin, file C:\opencv_build\sources\modules\dnn\src\ie_ngraph.cpp, line 865

And I get this:

![изображение](https://user-images.githubusercontent.com/76564343/220024329-c1c0876e-2f85-4c65-b887-0c3cbb756c5a.png)

If I try to debug, I get this in terminal:

[ INFO:0@4.396] global ie_ngraph.cpp:860 cv::dnn::InfEngineNgraphNet::initPlugin DNN/IE: Calling LoadNetwork(device=CPU)...
OpenCV(4.7.0) Error: Unspecified error (Failed to initialize Inference Engine backend (device = CPU): Cannot load library 'openvino_intel_cpu_plugind.dll': 126 from cwd: C:\ROOT1\opencv_build_test\test_neur_opencv\test_neur_opencv) in cv::dnn::InfEngineNgraphNet::initPlugin, file C:\opencv_build\sources\modules\dnn\src\ie_ngraph.cpp, line 865

And get this:

![изображение](https://user-images.githubusercontent.com/76564343/220024632-5fe30255-e9aa-4e5a-a0f3-2d5287fba1d7.png)

**Comment by dkurt** [comment]
> Cannot load library 'openvino_intel_cpu_plugind.dll'

Please try run in Release mode

**Comment by ArsenyStahkov** [comment]
> Please try run in Release mode

Interesting. It fails on the string

`Net openvino_model = readNetFromModelOptimizer(xml_path, bin_path);`

![изображение](https://user-images.githubusercontent.com/76564343/220027947-b048d9fd-40ab-41a0-9a5a-1119823b11fe.png)

**Comment by ArsenyStahkov** [comment]
> Please try run in Release mode

I tried to change 

`blob = blob.reshape(1, {1, 300, 300, 3});`

for

`blob = blob.reshape(1, { 1, 3, 300, 300 });`

Now the result for Debug is

![изображение](https://user-images.githubusercontent.com/76564343/220047897-79664501-47cf-48e9-98fb-93e905e860bd.png)

**Comment by dkurt** [comment]
@ArsenyStahkov, cannot reprodure model inference failure. The following code works fine:
```cpp
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace cv::dnn;

int main(int argc, char** argv) {
    Net net = readNet("../ssdlite_mobilenet_v2.xml", "../ssdlite_mobilenet_v2.bin");

    Mat img = imread("opencv_extra/testdata/cv/dpm/cars.png");

    Mat blob;
    resize(img, blob, Size(300, 300));
    blob.convertTo(blob, CV_32F);
    blob = blob.reshape(1, {1, 300, 300, 3});

    net.setInput(blob);
    Mat detections = net.forward();

    float* data = detections.ptr<float>();
    for (int i = 0; i < detections.total() / 7; ++i) {
        float confidence = data[i * 7  +2];
        if (confidence > 0.5) {
            int x_left = static_cast<int>(data[i * 7  + 3] * img.cols);
            int y_top = static_cast<int>(data[i * 7  + 4] * img.rows);
            int x_right = static_cast<int>(data[i * 7  + 5] * img.cols);
            int y_bottom = static_cast<int>(data[i * 7  + 6] * img.rows);

            rectangle(img, Point(x_left, y_top), Point(x_right, y_bottom), Scalar(0, 0, 255), 2);
        }
    }
    imwrite("res.png", img);
}
```
![res](https://user-images.githubusercontent.com/25801568/222067597-4b0d709a-a0c7-49a7-880e-a574552d5984.png)

**Comment by ArsenyStahkov** [comment]
> @ArsenyStahkov, cannot reprodure model inference failure. The following code works fine:
> 
> ```c++
> #include <opencv2/opencv.hpp>
> 
> using namespace cv;
> using namespace cv::dnn;
> 
> int main(int argc, char** argv) {
>     Net net = readNet("ssdlite_mobilenet_v2.xml", "ssdlite_mobilenet_v2.bin");
> 
>     Mat img = imread("/path/to/opencv_extra/testdata/cv/dpm/cars.png");
> 
>     Mat blob;
>     resize(img, blob, Size(300, 300));
>     blob.convertTo(blob, CV_32F);
>     blob = blob.reshape(1, {1, 300, 300, 3});
> 
>     net.setInput(blob);
>     Mat detections = net.forward();
> 
>     float* data = detections.ptr<float>();
>     for (int i = 0; i < detections.total() / 7; ++i) {
>         float confidence = data[i * 7  + 2];
>         if (confidence > 0.5) {
>             int x_left = static_cast<int>(data[i * 7  + 3] * img.cols);
>             int y_top = static_cast<int>(data[i * 7  + 4] * img.rows);
>             int x_right = static_cast<int>(data[i * 7  + 5] * img.cols);
>             int y_bottom = static_cast<int>(data[i * 7  + 6] * img.rows);
> 
>             rectangle(img, Point(x_left, y_top), Point(x_right, y_bottom), Scalar(0, 0, 255), 2);
>         }
>     }
>     imwrite("res.png", img);
> }
> ```
> 
> ![res](https://user-images.githubusercontent.com/25801568/222067597-4b0d709a-a0c7-49a7-880e-a574552d5984.png)

I found out that I'd forgotten to add some .dll files to Release project. I added them and tested your code. Unfortunately, it dropes on string

`Mat detections = net.forward();`

![изображение](https://user-images.githubusercontent.com/76564343/222074191-8619d50a-962c-48ef-a935-eddbb510738d.png)

Maybe I build OpenCV incorrectly? Could you tell how you build?

**Comment by ArsenyStahkov** [comment]
@dkurt, Do you have any ideas?

**Comment by dkurt** [comment]
@ArsenyStahkov, this must be a build problem - application works (at east on Linux). Please check exception message - it should clarify a bit.

**Comment by ArsenyStahkov** [comment]
@alalek maybe you can help? Maybe I should add some plugin in built OpenCV? Why does it drop on reshape method?

**Comment by dkurt** [comment]
@ArsenyStahkov, Please provide exception message:
```cpp
try {
  Mat detections = net.forward();
} catch (const cv::Exception& e) {
  std::cout << e.what() << std::endl;
}
```

**Comment by ArsenyStahkov** [comment]
@dkurt it shows nothing. I tried in Release mode and I just reveived the same thing
![изображение](https://user-images.githubusercontent.com/76564343/224937524-189b43ba-6f0a-4baa-9f74-529e29c82c5d.png)
Also I tried other OpenVino verisons, but result was the same. And I tried to change different flags in CMake.
So what is the problem?

**Comment by ArsenyStahkov** [comment]
I managed to solve all problems. I needed to add openvino_intel_cpu_plugind.dll and add strings    ```
 imshow("res.png", img);
    waitKey(2500000);
```
instead
`imwrite("res.png", img);`

in @dkurt 's code.
Thank you for help!

**Comment by dkurt** [comment]
@ArsenyStahkov, great, thanks!
