### ISSUE TITLE
Use camera (Waveshare) under Bullseye (64) with OpenCV (failed camera access with OpenCV)

### ISSUE THREAD

**Issue by Petros626** [opencv/opencv#23328]
**OpenCV:** 4.7.0
**Python:** 3.9.2
**OS:** Debian GNU/Linux 11 (bullseye)
**Hardware:** RPi 4 8GB and WaveShare RPi IR-Cut Camera

I'm generally trying to use a fresh installed OpenCV on my RPi. For this I followed the "right" installation of the Q-Engineering Team (https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-64-bits). OpenCV can be imported in terminal and shows me all the tab completions. The problem occurs, when I'm trying to just run a test code, to see if my camera works with the installed version of OpenCV. But here what I noticed:

1. OpenCV is recognized by my IDE _(Thonny)_, but not useable (no tab completion, no behaviour in code)
2. It's not possible to access my camera
`[ WARN:0@0.128] global cap_gstreamer.cpp:2784 handleMessage OpenCV | GStreamer warning: Embedded video playback 
  halted; module v4l2src0 reported: Failed to allocate required memory.`

    `[ WARN:0@0.129] global cap_gstreamer.cpp:1679 open OpenCV | GStreamer warning: unable to start pipeline`

    `[ WARN:0@0.129] global cap_gstreamer.cpp:1164 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not 
       been created`

I'm at a loss as I'm neither able to use the camera with OpenCV or have it open (usable) with it. Changing the `apiReference` to `cv2.CAP_V4L2 `only caused the test script to fail.

test script:
```python
import cv2

cam = cv2.VideoCapture(-1, cv2.CAP_V4L2)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        img_name = "opencv_frame_{}.png".format(img_counter)
        cv2.imwrite(img_name, frame)
        print("{} written!".format(img_name))
        img_counter += 1
```

**Comment by asmorkalov** [comment]
Read a bit about the camera. Looks like it's the same issue as in https://github.com/opencv/opencv/issues/22820. Modern Raspberry Pi OS provides libcamera based interface for camera stack. It's not fully compatible with V4L2 and does not work with OpenCV now. As work around you can switch software stack to legacy driver in raspi-config tool.
Libcamera support request in OpenCV: https://github.com/opencv/opencv/issues/22820

**Comment by Petros626** [comment]
Thanks for answering, so you will fix this in future ?

**Comment by asmorkalov** [comment]
Not sure. There is request from community to support libcamera, but there is no resources for it. It's not widely spread API. Not OpenCV, but all other apps that relay on V4L2 are affected, including GStreamer, FFmpeg, etc. Some Rapsverian apps are adopted for the new API, but not so many.

**Comment by Petros626** [comment]
So in itself I would also find it good, as many users will probably switch to the new 64-bit Raspberry Pi. The old legacy camera stack works fine, but it is no longer up to date under RPi OS (the authors have certainly thought of something). If resources were available from OpenCV in the future, that would certainly make many many users happy.

**Comment by Biancaa-R** [comment]
so you have tried to use cv2.VideoCapture() this function of cv2 for capturing frames worked well with the legacy stack and not with the modern camera, where libcamera works...you can try using picamera 2 for creating camera obj. in debian bullseye 64 bit

picam2=Picamera2()

**Comment by Petros626** [comment]
> so you have tried to use cv2.VideoCapture() this function of cv2 for capturing frames worked well with the legacy stack and not with the modern camera, where libcamera works...you can try using picamera 2 for creating camera obj. in debian bullseye 64 bit
> 
> picam2=Picamera2()

I know you have 2 options use the old camera stack with opencv functions or picamera2
