### ISSUE TITLE
Does DNN support intel N100 processor

### ISSUE THREAD

**Issue by junk123321** [opencv/opencv#23338]
I'd like to buy a mini PC with intel N100 processor.  I am not sure if "cv2.dnn.readNetFromTensorflow" support the new processor. I use the function to detect face in real time. Thanks in advance for your help!

**Comment by asmorkalov** [comment]
Please use https://forum.opencv.org for questions and discussions.

**Comment by Animesht1008** [comment]
hi! May be you could refer to this Link https://docs.opencv.org/ as there might be a chance that it will support the function but certainly there are many other things you have to look for like Graphics card speed, memory storage and several other factors.
