### ISSUE TITLE
Order of returned points for `cv::RotatedRect::points()` is inconsistent

### ISSUE THREAD

**Issue by n0099** [opencv/opencv#23335]
### Descripe the doc issue

The document for [`cv::RotatedRect::points()`](https://docs.opencv.org/4.7.0/db/dd6/classcv_1_1RotatedRect.html#a69d648b086f26dbce0029facae9bfb2d) says
> The order is bottomLeft, topLeft, topRight, bottomRight.

which is introduced in #9343.

But in a .NET wrapper for OpenCV 4.7.0 which [using the same code snippet](https://github.com/shimat/opencvsharp/issues/1541#issuecomment-1459009582) in https://github.com/opencv/opencv/blob/0052d46b8e33c7bfe0e1450e4bff28b88f455570/modules/core/src/types.cpp#L173 to calculate four vertices of a `RotatedRect`:
https://github.com/shimat/opencvsharp/blob/0498156821f052ff6b2fd1205148f07a1de2781d/src/OpenCvSharp/Modules/core/Struct/RotatedRect.cs#L43-L61

It will return points that not forming the order of `bottomLeft, topLeft, topRight, bottomRight` when the degrees of rotation angle are within the range of `45~315°`: https://github.com/shimat/opencvsharp/issues/1541#issuecomment-1460181656

### Fix suggestion

Change the implement to guarantee the order of points returned by `cv::RotatedRect::points()`,
or update the document to indicate the order is unstable.

**Comment by mshabunin** [comment]
Consider the following example:
```.cpp
int main()
{
    const Scalar white {255, 255, 255};
    const Scalar green {0, 255, 0};
    const int font = FONT_HERSHEY_SIMPLEX;
    const Point2f center{400, 400};
    Mat image { 800, 800, CV_8UC3, Scalar::all(0)};
    RotatedRect r {center, Size2f(300, 500), 0};
    Point2f pts[4];
    while (true)
    {
        image = 0;
        r.points(pts);
        for (int a = 0, b = 1; a < 4; a += 1, b = (b + 1) % 4)
        {
            ostringstream buf; buf << a;
            putText(image, buf.str(), pts[a], font, 2, green);
            line(image, pts[a], pts[b], white, 4);
        }
        {
            ostringstream buf; buf << (int)r.angle % 360;
            putText(image, buf.str(), Point(50, 50), font, 2, green);
            Point2f mid = (pts[1] + pts[0]) / 2;
            line(image, center, mid, white);
        }
        imshow("Rect", image);
        int c = waitKey();
        if( c == 27 || c == 'q' ) break;
        r.angle += 15;
    }
    return 0;
}
```
>It will return points that not forming the order of bottomLeft, topLeft, topRight, bottomRight when the degrees of rotation angle are within the range of 45~315°

Points are stable, at 60 degrees 0-th point is still bottomLeft for the rectangle taking rotation in consideration.
![image](https://user-images.githubusercontent.com/3304494/224153585-ae28f9b5-362f-4d08-ab1e-2907fdaf04e6.png)
![image](https://user-images.githubusercontent.com/3304494/224153627-37e69154-05bb-479f-8a05-f5076f2b6f97.png)

**Comment by n0099** [comment]
So the name of these points refers to the original up-right rectangle?
And with the angle `0°` means towards the west? I thought it will be north.
These details should be clarified in the document.
