### ISSUE TITLE
Load Image in tutorials

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#23378]
### Descripe the feature and motivation

Some images are in tutorials but not in samples/data. findfiles cannot be used source code 
example doc/tutorials/imgproc/histograms/back_projection/images

This [sample ](https://github.com/opencv/opencv/blob/4.x/samples/cpp/tutorial_code/Histograms_Matching/calcBackProject_Demo1.cpp#L26-L31)could be changed : 
```
int main( int argc, char* argv[] )
{
    //! [Read the image]
    CommandLineParser parser( argc, argv, "{@input |Back_Projection_Theory0.jpg  | input image}" );
    samples::addSamplesDataSearchSubDirectory("./doc/tutorials/imgproc/histograms/back_projection/images");
    Mat src = imread(samples::findFile(parser.get<String>( "@input" )) );

```
Is it a good idea?

**Comment by Saurabh-9** [comment]
Easy way to load the images is in the give sample code:

int main( int argc, char* argv[] )
{
    CommandLineParser parser( argc, argv, "{@input |Back_Projection_Theory0.jpg  | input image}" );
    Mat src = imread("samples/data/Back_Projection_Theory0.jpg");
    ...
}

**Comment by LaurentBerger** [comment]
No it does not work but relative path is a good idea: 
    CommandLineParser parser( argc, argv, "{@input |./doc/tutorials/imgproc/histograms/back_projection/images/Back_Projection_Theory0.jpg  | input image}" );
    Mat src = imread( samples::findFile(parser.get<String>( "@input" )) );

**Comment by LaurentBerger** [comment]
There is no problem with path length in first idea
```
int main( int argc, char* argv[] )
{
    //! [Read the image]
    CommandLineParser parser( argc, argv, "{@input |Back_Projection_Theory0.jpg  | input image}" );
    samples::addSamplesDataSearchSubDirectory("./doc/tutorials/imgproc/histograms/back_projection/images");
    Mat src = imread(samples::findFile(parser.get<String>( "@input" )) );

```
![image](https://user-images.githubusercontent.com/3591626/228833875-1b020b2f-3ee5-442c-843a-fe252e6d2598.png)




in second idea there is a problem too
```
 CommandLineParser parser( argc, argv, "{@input |./doc/tutorials/imgproc/histograms/back_projection/images/Back_Projection_Theory0.jpg  | input image}" );
    Mat src = imread( samples::findFile(parser.get<String>( "@input" )) );

```

and third idea could be 

```
static std::vector<cv::String>& _getDataSearchSubDirectory()
{
    if (g_data_search_subdir.empty())
    {
        g_data_search_subdir.reset(new std::vector<cv::String>());
        g_data_search_subdir->push_back("samples/data");
        g_data_search_subdir->push_back("doc/tutorials");
        g_data_search_subdir->push_back("data");
        g_data_search_subdir->push_back("");
    }
    return *(g_data_search_subdir.get());
}
```

and 

```
    CommandLineParser parser( argc, argv, "{@input | ./imgproc/histograms/back_projection/images/Back_Projection_Theory0.jpg | input image}" );
    Mat src = imread( samples::findFile(parser.get<String>( "@input" )) );

```
But path length is still cut

![image](https://user-images.githubusercontent.com/3591626/228833013-b18aab55-bb73-4a81-8758-c4410f3079cd.png)
