### ISSUE TITLE
Use OpenCV in VSCode (built process/create projects)

### ISSUE THREAD

**Issue by Petros626** [opencv/opencv#23387]
Hello,

I have successfully used _OpenCV_ in _Visual Studio Code_ following these instructions (https://www.geeksforgeeks.org/how-to-install-opencv-in-c-on-linux/). 
However, I have a question about creating new projects and the build process with _CMake_ in general.

1. nano examplefile.cpp
2. nano CMakeLists.txt
3.
```cmake
cmake_minimum_required(VERSION 2.8)
project( example )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( example example.cpp )
target_link_libraries( example ${OpenCV_LIBS} )
```
5. cmake.
6. make

In _VSCode_ I have specified the path of my installation under `"c_cpp_properties.json"`, **BUT** why do I always have to repeat this procedure step 2-5 when I create new projects or even C++ files? Shouldn't _VSCode_ know from the path where the libraries are located, so that I can simply start programming?

Thanks in advance

**Comment by mshabunin** [comment]
CMakeLists.txt file **IS** a project for cmake-based applications. You can create single project with multiple executables in it (_add_executable_) and build them selectively. Check the [cmake tutorial](https://cmake.org/cmake/help/v3.22/guide/tutorial/index.html) for guidance.

I'm closing the ticket as it is not related to a problem in OpenCV.

**Comment by Petros626** [comment]
Thanks, I've already solved it
