### ISSUE TITLE
extra `\` in usac.markdown

### ISSUE THREAD

**Issue by scott-vsi** [opencv/opencv#23404]
### Descripe the doc issue

There appears to be extra slashes (`\`) in [usac.markdown](https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/usac.markdown?plain=1#LL200-LL201) as we can see in the [documentation](https://docs.opencv.org/4.x/d0/d74/md__build_4_x-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html) (search for `\ \`).

### Fix suggestion

It seems like those slashes should be removed.

Also, older versions of that [tutorial](https://docs.opencv.org/4.x/d0/d74/md__build_4_x-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html) seem to be broken; i.e., I cannot change the version in the dropdown at the top of the page, e.g., to 4.6.0

Finally, should this tutorial be listed in the [Table of Contents](https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/table_of_content_calib3d.markdown)?

**Comment by cherieliu** [comment]
@scott-vsi I can work on this documentation fix, please assign it to me

**Comment by scott-vsi** [comment]
Hmm, I don't think I have permissions to assign issues

**Comment by cherieliu** [comment]
No problem! I'll work on a PR for these fixes

**Comment by champati-v** [comment]
Hii! 
seems like this issue is not assigned yet. Can you assign this issue to me.

**Comment by asmorkalov** [comment]
Feel free to submit a PR.

**Comment by asmorkalov** [comment]
Looks like the tutorial is not integrated into OpenCV documentation properly (bibliography, references, formatting, code links, etc).

**Comment by asmorkalov** [comment]
@ivashmak Could you re-format the tutorial and integrate it to Doxygen tree?

**Comment by ivashmak** [comment]
Yes, I can do that, how the desirable format should look like?

**Comment by asmorkalov** [comment]
Example: https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown?plain=1

Please pay attention on table of content, references to previos and next pages. Also you need to add the tutorial to the module table of content in https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/table_of_content_calib3d.markdown.
