### ISSUE TITLE
Did already had HOG new version?

### ISSUE THREAD

**Issue by hartpoli** [opencv/opencv#23453]
### Descripe the feature and motivation

HOG (Histogram of Oriented Gradients) is a feature extraction technique that describes the local gradient orientation in an image. It is commonly used for pedestrian detection, face recognition, and object tracking.

**Comment by Ebuka636** [comment]
The Histogram of Oriented Gradients (HOG) feature extraction technique is used to describe the local gradient orientation in an image. This method has been popularly used for object detection and recognition tasks, especially in computer vision applications such as pedestrian detection, face recognition, and object tracking.

The motivation behind HOG is to capture the local shape and texture information in an image. The technique works by computing the gradient magnitude and orientation at each pixel in an image, and then grouping the pixels into local regions called cells. The histogram of gradient orientations is then computed for each cell, which provides a measure of the local texture and edge information in that region. The histograms from neighboring cells are then combined to form a block, and multiple blocks are combined to form the final feature representation for the entire image.

HOG has several advantages over other feature extraction techniques, such as its ability to handle variation in lighting, scale, and orientation. Additionally, it is relatively simple and efficient to compute, making it suitable for real-time applications. Overall, the HOG feature extraction technique is an effective way to capture the local texture and edge information in an image, which can be used for a variety of computer vision tasks, including object detection and recognition.
