### ISSUE TITLE
OpenCV build - cmake don't recognize GTK2 or GTK3

### ISSUE THREAD

**Issue by Petros626** [opencv/opencv#23461]
##### System information (version)

- OpenCV => 4.7.0
- Operating System / Platform => Ubuntu 20.04
- Compiler => g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- C++ Standard: 11

##### Detailed description

I am trying to create OpenCV with the GTK GUI. I have `GTK2` and `GTK3` installed on the system, but neither version is recognised by cmake. 

![image](https://user-images.githubusercontent.com/62354721/230026534-66053f4e-67d3-45cd-93c2-4902365400c7.png)
![image](https://user-images.githubusercontent.com/62354721/230026727-07d64f8c-c453-4048-9d23-3608b1c94663.png)

The output after executing cmake remains 
**GUI: NONE** 
**GTK+:NO**

I execute the cmake command as follows:

`cmake -DPYTHON_DEFAULT_EXECUTABLE=$(which python3) -DWITH_GTK=ON ../opencv`

or

`cmake -DPYTHON_DEFAULT_EXECUTABLE=$(which python3) -DWITH_GTK=ON -DWITH_GTK_2_X=ON ../opencv`

##### Steps to reproduce

git clone https://github.com/opencv/opencv.git
mkdir -p build && cd build
cmake ../opencv (default, custom look above)

Thank you for your help

**Comment by Kumataro** [comment]
Hi, I tried with Ubuntu 20.04, but I couldn't reproduce this issue.
I suggest to check what gtk2/gtk3/gthread versions OpenCV recognised in your develop environment via pkg-config.

Install command for GTK libraries is here.
> sudo apt install libgtk-3-dev
> sudo apt install libgtk2.0-dev

Related package versions are following.

```
kmtr@kmtr-virtual-machine:~$ pkg-config gtk+-2.0 --modversion
2.24.32
kmtr@kmtr-virtual-machine:~$ pkg-config gtk+-3.0 --modversion
3.24.20
kmtr@kmtr-virtual-machine:~$ pkg-config gthread-2.0 --modversion
2.64.6
```

Detect GTK2/3 code is here.

https://github.com/opencv/opencv/blob/4.x/modules/highgui/cmake/detect_gtk.cmake

OpenCV requests following versions.

| Library | Minimum Version |
| --- | --- |
| GTK2 | 2.18.0 |
| GTK3 | none |
| GThread-2.0 | 2.32 |

cmake command outputs following
```
-- Looking for dlerror in dl - found
-- ADE: Downloading v0.1.2a.zip from https://github.com/opencv/ade/archive/v0.1.2a.zip
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.32
-- Checking for module 'gthread-2.0>=2.32'
--   Found gthread-2.0, version 2.64.6
-- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
--   No package 'libavcodec' found

--   GUI:                           GTK2
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.64.6)
--       GtkGlExt:                  NO
--     VTK support:                 NO

```


```
-- ADE: Downloading v0.1.2a.zip from https://github.com/opencv/ade/archive/v0.1.2a.zip
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.20
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.32
-- Checking for module 'gthread-2.0>=2.32'
--   Found gthread-2.0, version 2.64.6
-- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'

--   GUI:                           GTK3
--     GTK+:                        YES (ver 3.24.20)
--       GThread :                  YES (ver 2.64.6)
--       GtkGlExt:                  NO
--     VTK support:                 NO


```

**Comment by Petros626** [comment]
@Kumataro thank you for your detailed answer. It turned out, that I was sourcing the SDK for a board and not the OS of my Host machine, this was the fault. I managed to install opencv now succesfully, but glad you tried to help me out.

**Comment by northpoleforce** [comment]
> 
@Petros626 
How do you solve it?(I try my best, but it doesn't work

**Comment by Petros626** [comment]
@northpoleforce,

provide more information. 
What you have sourced in your bash file? 
In my case I sourced a SDK for a board. So during building OpenCV (`cmake ../opencv`) it was obvious, that it could not find GTK packages

**Comment by northpoleforce** [comment]
I try to build opencv for jetson xavier nx on the OS of my Host machine, but not can't find gtk on my host pc and the imshow func can't be used. You said you successfully build opencv with gtk for a board on host pc, how do you make cmake find gtk? @Petros626

**Comment by Petros626** [comment]
Ah nice, very cool. 
So I guess you're using a SD card with the image (all required software etc.) for the `Jetson Xavier` like me in the past. 

On my host machine (was running with a build image (Ubuntu + additional software) from the company) I comment out in the `bashrc` file (when I remember correctly) the path to the `Software Development Kit` (only for the board! not host pc) for the board and so during the build process `OpenCV` automatically finds through the Linux `default paths` all the required packages like `GTK`.

**Comment by northpoleforce** [comment]
It's kind of you to tell me these details, thank you very much! 
But I did not as same as you, I just use `cmake` on the host ubuntu, no `SDK` support to build opencv for `Jetson Xavier NX`, I just use some native ideas to cross compile.
I will try to build again in your ways! Thank you again!

**Comment by Kumataro** [comment]
Hello, if it is incorrect, I'm sorry.

For host environment, we can get installed libraries with this command.

```bash
        pkg-config --list-all
```

(Please replace for your environment. )
If your `PKG_CONFIG_PATH`, `PKG_CONFIG_LIBDIR` and `PKD_CONFIG_SYSROOT_DIR` are correct for target, following commands show installed libraries for target environment, not host environment.

```bash
PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu \
    PKG_CONFIG_SYSROOT_DIR=/ \
        pkg-config --list-all
```

- `PKG_CONFIG_PATH` constains `*.po` files.
- `PKG_CONFIG_LIBDIR` contains `*.so` files.
- `PKG_CONFIG_SYSROOT_DIR`  seems to be set to crosscompiler settings. Maybe jetson sysroot image path.

If installed libraries for target  environment are correct, cmake command for opencv works well, which can be find out gtk2/3 .

(Maybe `CMAKE_TOOLCHAIN_FILE` file should be customed for your environment. )

```bash
PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu \
    PKG_CONFIG_SYSROOT_DIR=/ \
       cmake -S opencv -B build4-arm64 -GNinja \
          -DCMAKE_TOOLCHAIN_FILE=/home/kmtr/work/opencv/platforms/linux/aarch64-gnu.toolchain.cmake \
          -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules
```

**Comment by Petros626** [comment]
> It's kind of you to tell me these details, thank you very much! But I did not as same as you, I just use `cmake` on the host ubuntu, no `SDK` support to build opencv for `Jetson Xavier NX`, I just use some native ideas to cross compile. I will try to build again in your ways! Thank you again! @Petros626

Yes I get what youre planning to do, but I offered all these for you to better understand what youre doing and what you must separate. For developing code you use your host pc and to finally run the code with shared libs, linking etc. on the target device (`Jetson Xavier`). You mix up some things I tried to explain, anyway just try to build `OpenCV` from source on your host with the right configured source in `bashrc`.

**Comment by northpoleforce** [comment]
Thanks for your help so much! (You're kind, helpful and warm-heart)
But I built and installed Opencv on the board throught native compile(Althought it's too slow), It can work now. I had somethine more urgent to do, I had to pull off cross compiling.
However, it's nice of you to assist me a lot! Thank you!

> > It's kind of you to tell me these details, thank you very much! But I did not as same as you, I just use `cmake` on the host ubuntu, no `SDK` support to build opencv for `Jetson Xavier NX`, I just use some native ideas to cross compile. I will try to build again in your ways! Thank you again! @Petros626
> 
> Normally you can adjust `pkg-config` in such a way, that it should find all the gtk packages. I bet it's just `pkg-config`, what causes this. So I install all the packages and then make sure you get the installed versions with the required command. Additionally to your first post, that you can't use a specific function, it looks like you didn't set the paths for the libraries and headers so that your IDE can fulfill them.

**Comment by Petros626** [comment]
thats not the way to do this. You develop your code on your host with `OpenCV` you build before on this machine. Then you need to cross compile the code for the target architecture. Then you put the compiled code on the board. That`s why the board should have a preinstalled image on a SD card or something you need the `.so` files on the board to execute the code.

1. Make sure you install OpenCV succesfully on your host
2. Integrate the header and the libs in your IDE (VS Code)
3. Create Code and run it succesfully
4. Then follow this guide here for cross compilation (https://karo-electronics.github.io/docs/software-documentation/vscode/index.html)
5. You should be able to create source code, run it and transfer it to the board. For debugging I would just rewrite the code section, cross- compile it and then test it on the target.

As I said unfortunately I don't got my harddisk with me, I really personalize the whole cross-compilation stuff for to work faster and make it more obvious for others...
