### ISSUE TITLE
why the doc disappeared for format

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#23553]
### Describe the doc issue

here there is doc opencv 3.2
https://github.com/opencv/opencv/blob/70bbf17b133496bd7d54d034b0f94bd869e0e810/modules/core/include/opencv2/core/utility.hpp#L180-L186

and opencv3.3 to 5.x no doc

### Fix suggestion

restore doc

**Comment by mediba123** [comment]
i want to take this issue

**Comment by onuralpszr** [comment]
It moved under operations.hpp

https://github.com/opencv/opencv/pull/10914

And docs is still there  under all branches 

Opencv 5.x: https://github.com/opencv/opencv/blob/5.x/modules/core/include/opencv2/core/operations.hpp#L437-L456

Opencv 4.x: https://github.com/opencv/opencv/blob/4.x/modules/core/include/opencv2/core/operations.hpp#L429-L446

Opencv 3.4: https://github.com/opencv/opencv/blob/3.4/modules/core/include/opencv2/core/operations.hpp#L417-L427

**Comment by mediba123** [comment]
Great .
