### ISSUE TITLE
How to contribute to OpenCV 

### ISSUE THREAD

**Issue by mediba123** [opencv/opencv#23554]
### Describe the doc issue

We suppose that you've seen the [contribute](https://opencv.org/about.html#Contribute) page, and now, as an enthusiastic.
The link above is not found. 

**### THE LINK ABOVE DON'T WORK.**

<img width="1079" alt="Screenshot 2023-04-27 at 1 53 40 PM" src="https://user-images.githubusercontent.com/37014848/234884465-3b40cd4c-2b3b-47bc-868c-68a8b247ab66.png">

<img width="1388" alt="Screenshot 2023-04-27 at 1 59 11 PM" src="https://user-images.githubusercontent.com/37014848/234885093-779ef291-9802-4a87-9ed6-b1ea587ce00a.png">

### Fix suggestion

should redirect to the right link

**Comment by ShiqiYu** [comment]
Thank you! Fixed!
