### ISSUE TITLE
Editing net layers in setUpNet

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv#23561]
### Describe the feature and motivation

I was tuning dnn (default backend and CANN backend) for SAM these days. I found that there are a lot of MatMul operators with multi-dimension inputs like the following:

<img width="173" alt="image" src="https://user-images.githubusercontent.com/17219438/235138832-f9378312-24d6-4068-94f2-ba210231a5ef.png">

To be more precise, input A has shape `[25, 14, 14, 768]` and input B has shape `[768, 2304]`.

Our DNN engine supports this case in default backend without issues. Thumbs up for that. But for other backends, for example CANN backend, it does not provide MatMul operators with multi-dimension inputs support. So I need to find out how to add `Reshape` operators before `MatMul` to reshape `[25, 14, 14, 768]` to `[25*14*14, 768]`, and after `MatMul` to reshape `[25*14*14, 768]` to `[25, 14, 14, 768]`.

Solutions I come up with are:
- Solution A: add `Reshape` in importers. I would say it is **not good** considering it may be redundant for other backends and we already have support MatMul with multi-dimensional inputs.
- Solution B: editing net layers in `setUpNet` like `fuseLayers` does. It would be a better solution because we can make this method Inheritable, from which different backends can have their own implementations for their situations.
- Temporary solution I took to bypass this problem: modify the model and add `Reshape` operators in it like the following picture.

<img width="202" alt="image" src="https://user-images.githubusercontent.com/17219438/235141299-6659eeff-2d1a-40cd-a01d-07b124a0052c.png">

I favor solution B. What do you think @opencv-alalek @vpisarev ? Or other options?

**Comment by asmorkalov** [comment]
@fengyuentau Do you plan to cover this before 4.8.0 release?

**Comment by fengyuentau** [comment]
I will try if there is still like a month or two before the release of 4.8.
