### ISSUE TITLE
Image Reshape  in c++

### ISSUE THREAD

**Issue by fti-sbargule** [opencv/opencv#23649]
- Input image = cv::dnn::blobFromImage(image, ScaleFactor, cv::Size(Width, Height), false, false);
- This function return 1 x 3 x  Width x Height.
- But some model requested  1 x  Width x Height x 3.
- In case difficult to reshape image.
- How to convert 1 x 3 x  Width x Height image size to 1 x  Width x Height x 3 in c++?

**Comment by dkurt** [comment]
> How to convert 1 x 3 x Width x Height image size to 1 x Width x Height x 3 in c++?

Take a look at [transposeND](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gab1b1274b4a563be34cdfa55b8919a4ec)

**Comment by LaurentBerger** [comment]
@dkurk please take a look at https://forum.opencv.org/t/how-to-use-blobfromimageswithparams/13430
