### ISSUE TITLE
Do you have any plans to add a generic pre-trained model to OpenCV, just like using a DNN pre-trained model?

### ISSUE THREAD

**Issue by VegetableWithChicken** [opencv/opencv#23743]
### Describe the feature and motivation

such as Lara,AIGC and Segment-Anything,and so on?

**Comment by dkurt** [comment]
related: https://github.com/opencv/opencv/issues/23470

At current moment, we have found that there is a complicated pipeline with SAM model.

**Comment by Sunilstar-V** [comment]
Hey, can anyone explain me about this question?
I couldn't able to understand this question

**Comment by VegetableWithChicken** [comment]
Foundation Model，such as chatgpt,loRA and so on




---Original---
From: "Nenavath ***@***.***&gt;
Date: Fri, Jun 9, 2023 12:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [opencv/opencv] Do you have any plans to add a genericpre-trained model to OpenCV, just like using a DNN pre-trained model? (Issue#23743)




 
Hey, can anyone explain me about this question?
 I couldn't able to understand this question

**Comment by dkurt** [comment]
Closing until issue properly filled.

**Comment by Sunilstar-V** [comment]
Hey, can anyone assign this question to me?
I think I can do it in a better way
