### ISSUE TITLE
Check type in blobFromImages and blobFromImagesWithParams

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#23759]
### Describe the feature and motivation

Everything is described here https://forum.opencv.org/t/how-to-use-blobfromimageswithparams/13430

### Additional context

I propose to check InputArraysOfArray type  in blobFromImages and blobFromImageWithParams: 

    if (images_.kind() != _InputArray::STD_VECTOR_MAT && images_.kind() != _InputArray::STD_ARRAY_MAT &&
        images_.kind() != _InputArray::STD_VECTOR_VECTOR) {
        String error_message = "The data is expected as InputArray::STD_VECTOR_MAT (a std::vector<Mat>) or _InputArray::STD_VECTOR_VECTOR (a std::vector< std::vector<...> >).";
        CV_Error(Error::StsBadArg, error_message);
    }

**Comment by dkurt** [comment]
>     String error_message = "The data is expected as InputArray::STD_VECTOR_MAT (a std::vector<Mat>) or _InputArray::STD_VECTOR_VECTOR (a std::vector< std::vector<...> >).";

I think message should be clear across the languages (Python and other bindings). BTW, it make sense to check that it will pass a list of np.array (test can be added [here](https://github.com/opencv/opencv/blob/4.x/modules/dnn/misc/python/test/test_dnn.py))

**Comment by LaurentBerger** [comment]
There is no exception in python : 

```
>>> img = np.random.randint(0, 255, [4, 5, 3]).astype(np.uint8)
>>> blob = cv.dnn.blobFromImages(img)
>>> blob.shape
(4, 1, 5, 3)
>>> imgarray = np.array([img])
>>> imgarray.shape
(1, 4, 5, 3)
>>> blob = cv.dnn.blobFromImages(imgarray)
>>> blob.shape
(1, 3, 4, 5)
```

I think np.array is converted in vector<Mat> 



```
