### ISSUE TITLE
Ordering of images in stitcher

### ISSUE THREAD

**Issue by fti-sbargule** [opencv/opencv#23751]
I was performing a 360 degree images stitch operation using SIFT for feature extraction and Brute force matcher for matching.
I observed that the order of images which I provide does not matter as the output I get is in different order.
I used following program for stitching [Stitching detailed](https://raw.githubusercontent.com/opencv/opencv/4.x/samples/cpp/stitching_detailed.cpp)

Questions:

Can I modify the order of images in matching stage so that I get a particular scene in the centre of my panorama?
Do I need to reorder my feature vector before providing it to matcher?

Example 360 degree image:
Can I recenter the “river” to middle?
![output1](https://github.com/opencv/opencv/assets/121230355/a8720483-40f1-48cd-beda-7c6428ad6b6b)

**Comment by asmorkalov** [comment]
Current implementation expects that matching is done in unique way and does not have any solution to "order" images. The stitching pipeline warps all images to cylinder or sphere and then project it to flat image. Potentially, you can "rotate" cylinder or sphere before projection to get focus where you what.

**Comment by fti-sbargule** [comment]
Thank you, 
how to rotate sphere image in c++ .

**Comment by asmorkalov** [comment]
`warper->warp(img, K, cameras[img_idx].R, INTER_LINEAR, BORDER_REFLECT, img_warped);` Warps current frame before stitching to place it on pano. In case if you have 360 degrees view, you can add the same rotation to all frames and rotate final view against pano. I cannot give you ready to use solution for it, code investigation and experiments are required.

**Comment by asmorkalov** [comment]
The issue is closed, as it's not actually a bug.
