### ISSUE TITLE
CV2 videowriter generated video fail to display in html code and broswer

### ISSUE THREAD

**Issue by Justinfungi** [opencv/opencv#23847]
```
### System Information


video = cv2.VideoCapture("./ATPSingle34YoshihitoNishioka.mp4")     
ret, frame = video.read()
fps, w, h = 30, frame.shape[1], frame.shape[0]                     
result = cv2.VideoWriter('filename.mp4',cv2.VideoWriter_fourcc(*'mp4v'),fps, (w,h))
        
while(True):
    ret, frame = video.read()
    if ret == True:
        result.write(frame)
        cv2.imshow('Frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('s'):
            break

    # Break the loop
    else:
        break

# When everything done, release
# the video capture and video
# write objects
video.release()
result.release()
    
# Closes all the frames
cv2.destroyAllWindows()

print("The video was successfully saved")
```

### Detailed description

video is https://drive.google.com/file/d/1fqRjGBLW5F7maZOqc6n1PIDeF2rwNZVl/view?usp=sharing

You can download an try to put it in the browser

I also try to put it in Firefox, the error is No Video With Supported Format And MIME Type Found

### Steps to reproduce

```
video = cv2.VideoCapture("./ATPSingle34YoshihitoNishioka.mp4")     
ret, frame = video.read()
fps, w, h = 30, frame.shape[1], frame.shape[0]                     
result = cv2.VideoWriter('filename.mp4',cv2.VideoWriter_fourcc(*'mp4v'),fps, (w,h))
        
while(True):
    ret, frame = video.read()
    if ret == True:
        result.write(frame)
        cv2.imshow('Frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('s'):
            break

    # Break the loop
    else:
        break

# When everything done, release
# the video capture and video
# write objects
video.release()
result.release()
    
# Closes all the frames
cv2.destroyAllWindows()

print("The video was successfully saved")
```

**Comment by opencv-alalek** [comment]
> the error is No Video With Supported Format

Just not supported by browser. Try H264 (AVC1) codec in mp4 container.

There is nothing to fix in OpenCV.

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by NGIWS719** [comment]
@Justinfungi Hello, I have tried many encoding methods, but the generated video still cannot be played in the browser. Do you have any good solutions, or how should I write the encoding code? Thank you!

**Comment by NGIWS719** [comment]
@Justinfungi Hello, the problem has been resolved. You don't need to reply to my previous question anymore. I used this:`fourcc = cv2.VideoWriter_fourcc(*'avc1')`

**Comment by AnujanR** [comment]
> @Justinfungi Hello, the problem has been resolved. You don't need to reply to my previous question anymore. I used this:`fourcc = cv2.VideoWriter_fourcc(*'avc1')`

thankyou @NGIWS719 it worked!!!! 🙌
