### ISSUE TITLE
How to feed mat of 6*224*224,CV_32FC(6) into cvdnn?

### ISSUE THREAD

**Issue by williamlzw** [opencv/opencv#23866]
How to feed mat of 6x224x224,CV_32FC(6) into cvdnn? My deep learning model input size is 1x6x224x224
Using the cv::merge method to merge 6 mats of type CV_32FC1, the size is 224x224x6, how to quickly change the data dimension to 6x224x224

**Comment by zihaomu** [comment]
You can use the `blobFromImage` to get the [1x6x224x224] and then get the first submat by `mat.row(0)`.

**Comment by williamlzw** [comment]
How to fill mat size in blobFromImage?

**Comment by zihaomu** [comment]
Hi @williamlzw, sorry for the late reply.
May be you can use the function that we support it recently. `transposeND `
https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gab1b1274b4a563be34cdfa55b8919a4ec

first, create a Mat with [6*224*224], and `transposeND` the channle to the last.

**Comment by williamlzw** [comment]
thanks
