### ISSUE TITLE
Mouse coordinates seem to be off if opencv versionhigher than 4.5

### ISSUE THREAD

**Issue by UniversalAl** [opencv/opencv#23870]
### System Information

OpenCV version: 4.4.0
Operating System / Platform: Windows 10
Python version: 3.810

### Detailed description

 opencv version 4.4.0 seams to be still ok, but somewhere for later versions mouse reading coordinates seems to be off, is that true?  Not sure what version it starts but latest 4.6 or 4.7 for sure 
It could be tested in code below. It is a 2x2 image, so with mouse increase the size of the window. Tt should print proper mouse coordinates. But those latest versions show proper value only for top , left quadrant for a pixel

### Steps to reproduce

```import numpy as np
import cv2
print(f'OpenCV version {cv2.__version__}')

img = np.zeros((2,2,3), np.uint8)
img[0, 0] = (0, 0, 255)
img[1, 0] = (0, 255, 0)
img[0, 1] = (255, 0, 0)

def mouseAction(event,x,y,flags,param=None):
    print(x,y)
    
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.setWindowProperty('image',cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_NORMAL)
cv2.setMouseCallback('image', mouseAction)
cv2.imshow('image', img)
cv2.waitKey(0)
```

**Comment by UniversalAl** [comment]
wrong section, sorry, it should be for python version

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/issues/860
