### ISSUE TITLE
License for CNN models of wechat_qrcode ? 

### ISSUE THREAD

**Issue by sergiomb2** [opencv/opencv#23903]
### Describe the feature and motivation

Hi, 
" Recently opencv add to opencv_contrib "CNN models for wechat_qrcode
module, including the detector model and the super scale model." 
https://github.com/WeChatCV/opencv_3rdparty

CNN models is about "Object Detection using CNNs"
https://docs.opencv.org/4.x/d2/da2/tutorial_dnn_objdetect.html

I proposed add the models 
https://src.fedoraproject.org/rpms/opencv/pull-request/21#

The lack of information of the License of these "models" , make me
think that I should ask to Fedora legal, if we can bundle these binaries that are
in a 3rdparty repo ?
 
In the opencv_contrib code, we have this License information
https://github.com/opencv/opencv_contrib/blob/4.x/modules/wechat_qrcode/LICENSE "

After write above, Fedora Legal team or others suggested  to me to make a pull request  to add the same License in the 3rdparty repo and here it is : 

https://github.com/WeChatCV/opencv_3rdparty/pull/1

**Comment by sergiomb2** [comment]
Exactly .

**Comment by n0099** [comment]
https://github.com/WeChatCV/opencv_3rdparty/commit/3487ef7cde71d93c6a01bb0b84aa0f22c6128f6b

**Comment by ShiqiYu** [comment]
@sergiomb2 The license file has been added. Great thank to @n0099 !

**Comment by sergiomb2** [comment]
Great, thank you ! .
