### ISSUE TITLE
Possible memory leak in cv::resize in multithread environment

### ISSUE THREAD

**Issue by Drulludanni** [opencv/opencv#23912]
### Expected behaviour

memory usage to remain constant as the program runs

### Actual behaviour

memory usage steadily increases over time around ~ 200 Kb/sec (seen in windows task manager)

### Steps to reproduce

I'm running this in python 3.7 with opencv-python-4.7.0.72 on windows, I've also seen this also seems to happen on ubuntu machines

this piece of code reproduces the issue, it is not exclusive to resize, it seems that any function that returns data from cv2 causes leaked memory 
```
import threading
import cv2
import numpy as np
import gc

class Memleak_test:
    def __init__(self):
        self.thread = None

    def test(self):
        frame = np.zeros((10, 10, 3)).astype(np.uint8)
        frame = cv2.resize(frame, (20, 20))

    def run_threaded(self):
        self.thread = threading.Thread(target=self.test)
        self.thread.start()

    def test_memleak(self):
        if self.thread is not None:
            self.thread.join()
        self.run_threaded() # leaks memory
        return None

m = Memleak_test()
while True:

    m.test_memleak()
    gc.collect()
```
    
I've seen some mention of similar issues being related to TLS (thread local state) but have supposedly been fixed a long time ago  https://github.com/opencv/opencv/issues/9745

**Comment by asmorkalov** [comment]
The issue is not visible with ThreadPool. It means, that it's the same TLS issue like https://github.com/opencv/opencv/issues/20145 or https://github.com/opencv/opencv/issues/9745

Repro to prove:
```
import cv2
import numpy as np
import threading
import gc
from multiprocessing.pool import ThreadPool

import os, psutil
process = psutil.Process()

class Memleak_test:
    def __init__(self):
        self.pool = ThreadPool(processes=4)

    def test(params):
        frame = np.zeros((100, 100, 3)).astype(np.uint8)
        res = cv2.resize(frame, (50,50))

    def run_threaded(self):
        result = self.pool.apply_async(self.test)
        _ = result.get()

    def test_memleak(self):
        self.run_threaded() # leaks memory
        return None

m = Memleak_test()
i = 0
prev = 0
while True:
    if i % 100 == 0:
        print(process.memory_info().rss - prev)
        prev = process.memory_info().rss
    i += 1
    m.test_memleak()
    gc.collect()
```
