### ISSUE TITLE
Issue loading TFLite net

### ISSUE THREAD

**Issue by PetarPetrov8991** [opencv/opencv#23992]
##### System information (version)

- OpenCV => 4.8.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2022

##### Detailed description

So, I saw that tflite support has been added, but when I try readNetFromTFLite(detect.tflite);, I get:
```
[ERROR:0@0.395] global tflite_importer.cpp:243 cv::dnn::dnn4_v20230620::TFLiteImporter::populateNet DNN/TFLite: Problem during import of operator [PACK]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/w_stack) (65/157). Exception: OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\tflite\tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'cv::dnn::dnn4_v20230620::TFLiteImporter::populateNet'

OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\tflite\tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'cv::dnn::dnn4_v20230620::TFLiteImporter::populateNet'
```
The model was trained and converted by following [this tutorial](https://colab.research.google.com/github/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/Train_TFLite2_Object_Detction_Model.ipynb):

**Comment by dkurt** [comment]
Hi! Thanks for reporting, is that possible to share a model file? Even with untrained weights.

**Comment by PetarPetrov8991** [comment]
[detect.zip](https://github.com/opencv/opencv/files/12050950/detect.zip)

**Comment by asmorkalov** [comment]
```
./bin/opencv_model_diagnostics -m=./detect.tflite 
[ERROR:0@0.122] global tflite_importer.cpp:243 populateNet DNN/TFLite: Problem during import of operator [PACK]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/w_stack) (65/157). Exception: OpenCV(4.8.0-dev) /home/alexander/Projects/OpenCV/opencv-master/modules/dnn/src/tflite/tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'populateNet'

[ERROR:0@0.122] global tflite_importer.cpp:243 populateNet DNN/TFLite: Problem during import of operator [PACK]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/h_stack) (67/157). Exception: OpenCV(4.8.0-dev) /home/alexander/Projects/OpenCV/opencv-master/modules/dnn/src/tflite/tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'populateNet'

[ERROR:0@0.123] global tflite_importer.cpp:243 populateNet DNN/TFLite: Problem during import of operator [PACK]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling_1/w_stack) (72/157). Exception: OpenCV(4.8.0-dev) /home/alexander/Projects/OpenCV/opencv-master/modules/dnn/src/tflite/tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'populateNet'

[ERROR:0@0.123] global tflite_importer.cpp:243 populateNet DNN/TFLite: Problem during import of operator [PACK]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling_1/h_stack) (74/157). Exception: OpenCV(4.8.0-dev) /home/alexander/Projects/OpenCV/opencv-master/modules/dnn/src/tflite/tflite_importer.cpp:235: error: (-213:The function/feature is not implemented) Unsupported operator type PACK in function 'populateNet'
```

**Comment by PetarPetrov8991** [comment]
So, it's an issue in opencv, not in my model?
Or?

**Comment by dkurt** [comment]
@PetarPetrov8991, no, this is issue with OpenCV importer, please keep in touch for solution.

**Comment by dkurt** [comment]
@PetarPetrov8991, can you pleas share some details. Are there 3 or 2 classes to be detected? It's needed for correct interpretation of `TFLite_Detection_PostProcess` layer inputs. It might be also helpful to share an image with several objects on it.

**Comment by PetarPetrov8991** [comment]
I have 2 classes in the tflite model

**Comment by PetarPetrov8991** [comment]
![211](https://github.com/opencv/opencv/assets/139556290/bc15950c-c8ee-4c9c-a6cd-756e7eb56b93)

> <annotation>
	<folder>training photos</folder>
	<filename>211.jpg</filename>
	<path>D:\Downloads\training photos\211.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>2540</width>
		<height>1693</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>vehicle</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>244</xmin>
			<ymin>288</ymin>
			<xmax>2309</xmax>
			<ymax>1355</ymax>
		</bndbox>
	</object>
	<object>
		<name>license plate</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>1496</xmin>
			<ymin>874</ymin>
			<xmax>1867</xmax>
			<ymax>993</ymax>
		</bndbox>
	</object>
</annotation>


The idea with the model is to have it detect cars and license plates.
So, here's one of the training images with its xml file

**Comment by dkurt** [comment]
Were able to import a model with a fixes from branch https://github.com/dkurt/opencv/tree/tflite_new_layers. Will open a pull request soon after some refactoring.
```cpp
Net net = readNet("detect.tflite");

Mat img = imread("car.jpg");
Mat blob = blobFromImage(img, 1.0/255, Size(320, 320));

net.setInput(blob);
Mat out = net.forward();

float* data = out.ptr<float>();
for (int i = 0; i < 10; ++i) {
    float score = data[i * 7 + 2];
    if (score > 0.5) {
        std::cout << score << std::endl;
        int xmin = data[i * 7 + 3] * img.cols;
        int ymin = data[i * 7 + 4] * img.rows;
        int xmax = data[i * 7 + 5] * img.cols;
        int ymax = data[i * 7 + 6] * img.rows;
        rectangle(img, Point(xmin, ymin), Point(xmax, ymax), Scalar(0, 255, 0), 5);
    }
}
imwrite("res.png", img);
```
<details>
<summary>image with detections</summary>

![res](https://github.com/opencv/opencv/assets/25801568/4eb3ec49-7fe0-4c7f-b68c-c8eeed8a1e41)

</details>

**Comment by PetarPetrov8991** [comment]
I copied the changes to my files and built it, but now I'm getting 

> [ERROR:0@0.384] global net_impl.cpp:1169 cv::dnn::dnn4_v20230620::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Reshape]:(ssd_mobile_net_v2_fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/Reshape): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=1
[ERROR:0@0.385] global net_impl.cpp:1172 cv::dnn::dnn4_v20230620::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 128 30 40 2 ]
[ERROR:0@0.385] global net_impl.cpp:1176 cv::dnn::dnn4_v20230620::Net::Impl::getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@0.385] global net_impl.cpp:1180 cv::dnn::dnn4_v20230620::Net::Impl::getLayerShapesRecursively     blobs[0] = CV_32SC1 [ 4 1 ]
[ERROR:0@0.385] global net_impl.cpp:1182 cv::dnn::dnn4_v20230620::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'

OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'


Did I copy something wrong or is it something else?
Do I go to the forum with this?

**Comment by dkurt** [comment]
@PetarPetrov8991, please try again and verify that latest commit from PR https://github.com/opencv/opencv/pull/24004 matches local one. The easiest way to fetch the changes is the following:
```
git clone -b tflite_new_layers https://github.com/dkurt/opencv
```
Do you also work with 320x320 input? Can you show an output from `std::cout << blob.size << std::endl;` before `setInput(blob)`?

**Comment by PetarPetrov8991** [comment]
Sorry, I was a little busy today.

I fixed my blob size, but I'm still getting an error:

>1 x 3 x 320 x 320
OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\cuda\permute.cu:142: error: (-215:Assertion failed) output.rank() == input.rank() in function 'cv::dnn::cuda4dnn::kernels::permute'

I'm building it again on another pc, with the copied repo method. (this is just looking at recently modified files and copying their contents, then building it with cmake for gpu support(cuda))

**Comment by dkurt** [comment]
> OpenCV(4.8.0) G:\opencv\opencv-4.8.0\modules\dnn\src\cuda\permute.cu:142: error: (-215:Assertion failed) output.rank() == input.rank() in function 'cv::dnn::cuda4dnn::kernels::permute'

Can you check that at least CPU works?

**Comment by PetarPetrov8991** [comment]
Yes!
It works!
