### ISSUE TITLE
[Build] Error building opencv on Windows-Arm

### ISSUE THREAD

**Issue by mwangistan** [opencv/opencv#24006]
### Expected behaviour
I'm building opencv-python-headless-4.8.0.74 on Windows ARM. The aim is to generate a .whl file after running
`python setup.py bdist_wheel`

### Actual behaviour
The build fails with an error
```
opencv-python-headless-4.8.0.74\opencv\modules\dnn\src\layers\cpu_kernels\conv_block.simd.hpp(461,9): error C2678: binary '+=': n
o operator found which takes a left-hand operand of type 'float32x4_t' (or there is no acceptable conversion) (compiling source file C:\Users\snjoroge\AppData\Local\Temp\easy_install-uowrh
x5q\opencv-python-headless-4.8.0.74\opencv\modules\dnn\src\layers\cpu_kernels\convolution.cpp) [C:\Users\s\AppData\Local\Temp\easy_install-uowrhx5q\opencv-python-headless-4.8.0.74\_
skbuild\win-arm64-3.11\cmake-build\modules\dnn\opencv_dnn.vcxproj]

```

### Steps to reproduce
I've installed:
```
1. MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (latest)
2. MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (Latest)
3. Windows 11 SDK (10.0.22621.0)
4. C++ ATL for latest v143 build tools with SPectre Mitigations (ARM64/ARM64EC)
5. C++ ATL for latest v143 build tools (ARM64/ARM64EC)
```

Command ran:
`python setup.py bdist_wheel`

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
The issue transferred to the main repo as it's not related to Python bindings.

**Comment by asmorkalov** [comment]
@fengyuentau Could you try to cross-compile DNN for Windows ARM and fix build issue. The issue should be visible with regular OpenCV build. Python part is not relevant here.

**Comment by fengyuentau** [comment]
I am not familiar with toolchains on Windows. Could you assign someone else for this issue?

**Comment by thswei** [comment]
Hi, I just reproduce this issue on branch `4.x`, and find a solution for that. Modify this file should solve the problem: `modules\dnn\src\layers\cpu_kernels\conv_block.simd.hpp:455`

original:

```cpp
// c0 += vld1q_f32(c);
// c1 += vld1q_f32(c + 4);
// c2 += vld1q_f32(c + 8);
// c3 += vld1q_f32(c + 12);
// c4 += vld1q_f32(c + 16);
// c5 += vld1q_f32(c + 20);
// c6 += vld1q_f32(c + 24);
```

change them to those:

```cpp
c0 = vaddq_f32(c0, vld1q_f32(c));
c1 = vaddq_f32(c1, vld1q_f32(c + 4));
c2 = vaddq_f32(c2, vld1q_f32(c + 8));
c3 = vaddq_f32(c3, vld1q_f32(c + 12));
c4 = vaddq_f32(c4, vld1q_f32(c + 16));
c5 = vaddq_f32(c5, vld1q_f32(c + 20));
c6 = vaddq_f32(c6, vld1q_f32(c + 24));
```

Following is my test program:

my test environments:

1. Mac M1 Pro, macOS Ventura 13.4.1, Xcode 14.3, Apple clang version 14.0.3 (clang-1403.0.22.14.1)
2. VM, Windows 11 ARM, Visual Studio 2022 ARM, cl.exe 19.36.32537

test program source code: (I am trying to simulate what opencv-dnn module is doing.)

```cpp
#include <iostream>
#include <arm_neon.h>

using namespace std;

int main(int argc, const char * argv[]) {
    float32x4_t c0 = vdupq_n_f32(1.0), c1 = c0, c2 = c0, c3 = c0;
    
    float* c = (float*)malloc(16 * sizeof(float));
    for (int i = 0; i < 16; i++) {
        c[i] = i;
    }
    
    c0 += vld1q_f32(c);
    c1 += vld1q_f32(c + 4);
    c2 += vld1q_f32(c + 8);
    c3 += vld1q_f32(c + 12);
    
    free(c);
    
    return 0;
}
```

I found that this program compiles and runs well on my Mac, but cannot pass the compilation on Windows 11 ARM. So I think it has nothing to do with the opencv, and it seem that MSVC just do not support the operator `+` and operator `+=` here.

To fix it, use `vaddq_f32` function instead. It should have the same ability as operator `+=`.

Hope this is helpful.

**Comment by mwangistan** [comment]
@zixianweei thanks a lot. This works

**Comment by asmorkalov** [comment]
Fix: https://github.com/opencv/opencv/pull/24043

**Comment by mwangistan** [comment]
Hi

**Comment by mwangistan** [comment]
Hi @asmorkalov , I've pushed a PR to fix one last issue when building on ARM:

Error:
`libopenjpg2.lib(ht_dec.obj): error LNK2019: unresolved external symbol __popcnt referenced in function opt_t1_ht_decode_cblk`

**Comment by mwangistan** [comment]
Latest version of openjpeg already has this fix: https://github.com/uclouvain/openjpeg/blob/1ee6d115e80036d1d38bad7f95a680bfc612c1bf/src/lib/openjp2/ht_dec.c#L72
