### ISSUE TITLE
Can cv2.VideoCapture  read 4 channel video?

### ISSUE THREAD

**Issue by xxdm** [opencv/opencv#24010]
### Describe the doc issue

I want to read 4 channel video, using:
```
cv2.VideoCapture(path)
while True:
    ret, frame = video.read()

```    
But, I find the frame is 3 channel,

**Comment by patilniraj8** [comment]
Can u assign this task to me I can try to look out for it
nirajpatil849@gmail.com u can contact me here

**Comment by armeljunior** [comment]
Hi xxdm,

I believe the process of reading 4 level video channels are the same assuming its a BGRA type. Typically 4 channel is not visible through standard video viewing software, however you can assess its there by verifying within the matrix. To capture the properties of the video you can use "frame.shape".

`video = cv2.VideoCapture(path)

while True:
    ret, frame = video.read()
   
    if not ret:
        break

    # 4 channel check confirmation
    if frame.shape[2] == 4:
        print("This are 4 channels!")
        # Split channels
        b, g, r, a = cv2.split(frame)
        # 'a' contains the alpha channel, which you can process separately if needed.
    else:
        print("This frame does not have 4 channels!")`

Hope this helps.

**Comment by VadimLevin** [comment]
I suppose you have created a video in .mov format from a RGBA PNGs sequence using Quicktime. If so, you are dealing with proprietary extension for HEVC format that is not supported on different platforms or using different libraries.
