### ISSUE TITLE
Convert BGR to RGB NOW!!!

### ISSUE THREAD

**Issue by dbernatt** [opencv/opencv#24103]
### Describe the feature and motivation

"The reason why the early developers at OpenCV chose BGR color format is probably that back then BGR color format was popular among camera manufacturers and software providers. E.g. in Windows, when specifying color value using COLORREF they use the BGR format 0x00bbggrr.

BGR was a choice made for historical reasons and now we have to live with it. In other words, BGR is the horse’s ass in OpenCV."

RGB Revolution. 

Give a like if you support the cause.

**Comment by zihaomu** [comment]
Duplicated with https://github.com/opencv/opencv/issues/23906.
Hi @dbernatt, we've started work on project and hope to have it done in 5.0.
