### ISSUE TITLE
Opencv API declaration for C#

### ISSUE THREAD

**Issue by naushadck** [opencv/opencv#24130]
### Describe the doc issue

Hello,

I need to use opencvworldxxx.dll in c# application.
Where i can find all the API declaration of this dll. 

Thank you for your support
Best Regards

**Comment by dkurt** [comment]
There is no official distribution so you may try https://github.com/shimat/opencvsharp, for example.

**Comment by naushadck** [comment]
Thank you. 
This one is created another c++ wrapper. 
I am trying to use the Opencv generated opencvworldxxx.dll in c#. Is this possible ?.

I read that it can be done by using unmangled name. However, to call the function, requires the proper parameter. 
list and return type. Is it possible to get this ?. 
E.g - imread can be called as "?imread@cv@@YA?AVMat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z"

Appreciate any help.

**Comment by sdcb** [comment]
I'm also eager to find a OpenCV efficient C API, but sadly and obviously, there isn't

**Comment by TechScribe-Deaf** [comment]
Yep, this project is an anti-FFI project. (Foreign Function Interface.) There used to be C API, but it was intentionally removed.

**Comment by TechScribe-Deaf** [comment]
> Thank you. This one is created another c++ wrapper. I am trying to use the Opencv generated opencvworldxxx.dll in c#. Is this possible ?.
> 
> I read that it can be done by using unmangled name. However, to call the function, requires the proper parameter. list and return type. Is it possible to get this ?. E.g - imread can be called as "?imread@cv@@ya?AVMat@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@h@Z"
> 
> Appreciate any help.

It's generally not advised to directly bind C++ API directly, you have to make a C++ wrapper with C++ itself and expose C interface for it without name mangling. C++ API is dependent on compiler version and ABI that varies between platform.
