### ISSUE TITLE
Opencv includes not found after build

### ISSUE THREAD

**Issue by naushadck** [opencv/opencv#24147]
### Describe the doc issue

Hello,

I built the Opencv using cmake. 
Now i need to add OPencv into my application and call its functions. 
I could not find the include\version.hpp to include in my application. 
(header file)

Your input is appreciated. 

### Fix suggestion

Hello,

I have build the openCV using camke. Now i need to refer OpenCV in my C application.
I need to call the OPencv functions from my application. 

I could not find the include\version.hpp to include in my application. 

Appreciate your input.

**Comment by naushadck** [comment]
Unable to include header files. 
Always give cannot open source file. 
cannot open source file "opencv2/opencv_modules.hpp"	OpenCVC	C:\opencv4\modules\core\include\opencv2\core\base.hpp	52	

What is the correct way to add open cv header file in my application. 
Any documentation out there ?.

**Comment by mshabunin** [comment]
Please take a look at the example cmake application sing OpenCV: https://github.com/opencv/opencv/blob/4.x/samples/cpp/example_cmake/CMakeLists.txt
