### ISSUE TITLE
請教Camera calibration with opencv-python 的code問題

### ISSUE THREAD

**Issue by systembreakdown** [opencv/opencv#24200]
目前編寫的code 按run之後一直卡在這邊，也不知道是什麼問題，所以想請問大家能幫我看一下嗎?
![Camera Calibration code1](https://github.com/opencv/opencv/assets/143324766/e6016540-ee22-4afa-8d74-ac47ef6230e5)
![Camera Calibration code2](https://github.com/opencv/opencv/assets/143324766/5afe2563-77f0-4c3a-b2bf-7df87ec81b31)
![Camera Calibration code3](https://github.com/opencv/opencv/assets/143324766/35bb51f8-a839-4dcf-8a57-cbcac1bed117)
<img width="928" alt="螢幕擷取畫面 2023-08-27 154922" src="https://github.com/opencv/opencv/assets/143324766/415f5200-9bb0-46aa-96f2-c2b7dec4b767">

**Comment by opencv-alalek** [comment]
Never post code though screenshots.

You need to follow issue's template.
