### ISSUE TITLE
Undefined symbols for architecture arm64:   "cv::DISOpticalFlow::create(int)", referenced from: ...

### ISSUE THREAD

**Issue by x4080** [opencv/opencv#24202]
Hi, i'm on mac m2 pro and try to build using opencv and got this result, is this means DISOpticalFLow is not available for arm64 ?

Or I make some mistakes ?

Here's what my compile command :

```
g++ disflow.cpp -o disflow -O2 -std=c++11 -I/usr/local/include/opencv4/ || { echo "Compilation failed"; exit 1; }
```

TIA

**Comment by VadimLevin** [comment]
You are not linking OpenCV library against your application.
Proceed to [tutorial](https://docs.opencv.org/4.x/db/df5/tutorial_linux_gcc_cmake.html), please,

**Comment by x4080** [comment]
@VadimLevin Thanks, I'll do that
