### ISSUE TITLE
calib3d: unconditonal usage of 'std::atomic<double>' (__atomic_load_8 issue)

### ISSUE THREAD

**Issue by opencv-alalek** [opencv/opencv#24281]
Regression is introduced in calib3d module which [uses](https://github.com/opencv/opencv/blame/4.8.0/modules/calib3d/src/usac/ransac_solvers.cpp#L736) `std::atomic<double>` unconditionally: https://github.com/opencv/opencv/pull/23078
Need to revise atomic usage in OpenCV.

/cc @asmorkalov @ivashmak

ref: #24031

**Comment by asmorkalov** [comment]
@ivashmak could you handle the issue?

**Comment by ivashmak** [comment]
I am not sure how to fix this. Is the goal to properly link compiler on Raspberry Pi to recognize the reference to `__atomic_load_8`, or should I come with a solution to not use `std::atomic` type at all?

**Comment by justintran12** [comment]
Hi, I am having the same issue as this post [#24031](https://github.com/opencv/opencv/pull/24031). I am unable to run make to install openCV on my Raspberry Pi 4 Raspbian OS. Is there a workaround to the issue I can do locally to be able to install openCV or do I need to wait for this PR to get the fix?

**Comment by asmorkalov** [comment]
PR #23078 brought atomic<double> in one of the algorithms. It triggers the issue. Is it posible to re-implement the algorithm without it? The  solution requires extra library to be linked and also it's very slow on some platforms.

**Comment by ivashmak** [comment]
Yes, I can re-implement without using atomic variables (will be slower, probably I would need to use mutexes instead). Is the problem only with `std::atomic<double>` or any atomic variable, including `atomic_bool ` and `atomic_int`?

**Comment by asmorkalov** [comment]
the issue is related to double only. Int or bool should fix the issue.

**Comment by ivashmak** [comment]
Great, I think the solution will be to round double to Int and sacrifice the float part. I can do this.
