### ISSUE TITLE
Allow find_package(OpenCV) in CMake to return paths without versions on Linux

### ISSUE THREAD

**Issue by DziubanMaciej** [opencv/opencv#24310]
### Describe the feature and motivation

Allow applications finding OpenCV by CMake to specify, whether they want to link to the path containing OpenCV version, e.g. `/usr/lib/libopencv_imgproc.so.408` or to version-less file, such as `/usr/lib/libopencv_imgproc.so`.

This could be done by setting a CMake variable before calling `find_package`, like so:
```cmake
set(OPENCV_USE_PATHS_WITH_VERSIONS 0)
find_package(OpenCV)
```

To keep compatibility, the default value should be `1`.

NOTE: I'd be happy to prepare a PR and implement this, but I'd need a confirmation from someone on the team, that this is desired, so I don't waste my time :)

### Additional context

On my system (Arch Linux) the path to actual `.so` is assigned to OpenCV CMake targets in `/usr/lib/cmake/opencv4/OpenCVModules-release.cmake` file:
```cmake
...

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libopencv_imgproc.so.4.8.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgproc.so.408"
  )

...
```

Because the full path is being hardcoded here, applications link to a very specific library version. When OpenCV is upgraded, the applications can no longer find the version and fail to load. An example of this happening often is a `nomacs` package: https://aur.archlinux.org/packages/nomacs (see comments). I encounter this problem regularly and have to recompile `nomacs` each time OpenCV is upgraded on my machine.

**Comment by opencv-alalek** [comment]
Wrong way.

Binaries are always linked to fixed versions.

Arch:

```
$ ldd /usr/bin/bash
        linux-vdso.so.1 (0x00007fffd834b000)
        libreadline.so.8 => /usr/lib/libreadline.so.8 (0x00007fc2bdeed000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fc2bdd06000)
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fc2bdc92000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc2be065000)
```

Fedora:

```
$ ldd /usr/bin/bash
        linux-vdso.so.1 (0x00007fffa84b1000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007ff2acfbf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff2acde2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff2ad179000)

$ readelf -d /usr/bin/bash
Dynamic section at offset 0x14e688 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libtinfo.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
...
```

Ubuntu:

```
$ ldd /usr/bin/bash
        linux-vdso.so.1 (0x00007fff28fa6000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fa401f69000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa401f63000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa401d71000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa4020ce000)
```

--

> When OpenCV is upgraded, the applications can no longer find the version and fail to load

OpenCV doesn't guarantee binary compatibility between versions.
This is why you see these large "version numbers" co-called "SO version"


--

Files without SO version are used as linker parameter (developer libraries to use as `-lname` parameter).
But final binary still uses "fixed version".

```
$ ls -al /usr/lib64/libreadline*
lrwxrwxrwx 1 root root     16 Oct  6  2022 /usr/lib64/libreadline.so -> libreadline.so.8
lrwxrwxrwx 1 root root     18 Jul 20  2022 /usr/lib64/libreadline.so.5 -> libreadline.so.5.2
-rwxr-xr-x 1 root root 279080 Jul 20  2022 /usr/lib64/libreadline.so.5.2
lrwxrwxrwx 1 root root     18 Oct  6  2022 /usr/lib64/libreadline.so.8 -> libreadline.so.8.2
-rwxr-xr-x 1 root root 370552 Oct  6  2022 /usr/lib64/libreadline.so.8.2
```

Details: google "SO version"

**Comment by DziubanMaciej** [comment]
Okay, I might have been a little misinformed on the topic of so versions. I guess it cannot be worked around then. Thanks for the explanation, I'm closing this issue.
