### ISSUE TITLE
DNN: test binary crashed after gemm refactoring in build with OpenCL (2023-09-20)

### ISSUE THREAD

**Issue by opencv-alalek** [opencv/opencv#24312]
OpenCL: Intel iGPU

relates #23897 (`dnn: add gemm_layer in place of fully_connected_layer for onnx models`)

Linux: https://pullrequest.opencv.org/buildbot/builders/4_x-lin64/builds/100254

```
free(): invalid next size (normal)
```

This is a signal of memory corruption.

**Comment by fengyuentau** [comment]
Let me take a look into this problem.
