### ISSUE TITLE
How to CONVERT RGBA to YUV420sp

### ISSUE THREAD

**Issue by VoHeLi** [opencv/opencv#24375]
### Describe the feature and motivation

Hello, 
I've seen many YUV420 formats that can be converted to RGBA or other formats using cvtColor.
However, on the other hand, you can only convert RGBA to 2 YUV420 formats, so you can't convert to semi-planar ones for instance.
Could you implement this feature? It is very frustrating to see a feature I need is implemented only on one way :/

In the meantime, can you give me some workaround to achieve RGBA to YUV420sp conversion using only opencv lib?

**Comment by opencv-alalek** [comment]
Please take a look on this PR: https://github.com/opencv/opencv/pull/24333
