### ISSUE TITLE
VideoCapture add support for byte buffer  

### ISSUE THREAD

**Issue by gdippolito** [opencv/opencv#24399]
### Describe the feature and motivation

Hello! 

Thanks for your work in this project. 

I'm using OpenCV VideoCapture in order to download decode a few frames from a video downloaded from a remote location. OpenCV seems to be working pretty well for both H.264 and H.265 file format but it requires a file handle in the  VideoCapture constructor. This means that in order to pass a downloaded object we need to first save to a temporary file and then pass the resulting path passed to VideoCapture.  

Would you consider adding support to raw bytes in the constructor?

**Comment by asmorkalov** [comment]
Duplicates https://github.com/opencv/opencv/issues/24400
