### ISSUE TITLE
VideoCapture add support for byte buffer  

### ISSUE THREAD

**Issue by gdippolito** [opencv/opencv#24400]
### Describe the feature and motivation

Hello! 

Thanks for your work in this project. 

I'm using OpenCV VideoCapture in order to download decode a few frames from a video downloaded from a remote location. OpenCV seems to be working pretty well for both H.264 and H.265 file format but it requires a file handle in the  VideoCapture constructor. This means that in order to pass a downloaded object we need to first save to a temporary file and then pass the resulting path passed to VideoCapture.  

Would you consider adding support to a byte object in the constructor?

**Comment by vrabaud** [comment]
May I suggest to actually support `vector<uchar>` (or just raw pointer) instead of cv::Mat to not fall into the problem with int/size_t like in https://github.com/opencv/opencv/issues/22036

**Comment by facug91** [comment]
Here's a SO post with someone's solution for this, which might help https://stackoverflow.com/questions/5237175/process-video-stream-from-memory-buffer

**Comment by gdippolito** [comment]
> Here's a SO post with someone's solution for this, which might help https://stackoverflow.com/questions/5237175/process-video-stream-from-memory-buffer

Thanks @facug91 for the response. Since we have a working solution in C++ would it be much effort to add support to the Python bindings to support a byte object instead of only supporting a file handle?

**Comment by dkurt** [comment]
Initial version with FFmpeg backend only: https://github.com/opencv/opencv/pull/25584

**Comment by diegolovison** [comment]
As a workaround, you can do the following
```
sudo mount -t tmpfs -o size=1G tmpfs /home/$USER/video_tmp
```
The code above won't survive restarts. You can make it by changing `/etc/fstab`

**Comment by gdippolito** [comment]
> As a workaround, you can do the following
> 
> ```
> sudo mount -t tmpfs -o size=1G tmpfs /home/$USER/video_tmp
> ```
> 
> The code above won't survive restarts. You can make it by changing `/etc/fstab`
> 
> Write the bytes to `/home/$USER/video_tmp/your_file` and pass the path to VideoCapture

Thanks, this is indeed similar to the approach that we are currently using. We are downloading a video and placing it to `/dev/shm` to reduce latency as much as possible. We then delete the file once we have completed the read. If we were able to use VideoCapture from a byte buffer it would reduce the complexity by a good amount.
