### ISSUE TITLE
Frame size of my USB camera cannot be set to desired width and height with 4.7.0.68 or later

### ISSUE THREAD

**Issue by yuan-metaretail** [opencv/opencv#24487]
### Expected behaviour
frame size is expected to set as 4000*3000
### Actual behaviour
with 4.7.0.68 or later
frame size is set to be 3840*2160 only

with 4.5.1.48-4.6.0.66
frame size could be set to be 4000*3000
### Steps to reproduce

- example code

```
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH,4000) 
cap.set(cv2.CAP_PROP_FRAME_HEIGHT,3000) 
while True:
    ret,frame = cap.read()
    if ret:
        cv2.imshow("frame",frame)
        print(frame.shape)
        if cv2.waitKey(25) & 0xFF == 27: 
            break

cap.release()
```
- operating system
Windows 11 Pro
- architecture (e.g. x86)
64-bit operating system、x64 base processer
- opencv-python version
4.7.0.68 or later
##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
The issue is caused by https://github.com/opencv/opencv/pull/22347. The last stream, you need does not pass this check:
```
   bool VideoIsAvailable() const
    {
        return ((subType == MFVideoFormat_RGB32) ||
            (subType == MFVideoFormat_RGB24) ||
            (subType == MFVideoFormat_YUY2));
    }
```
