### ISSUE TITLE
Additional resources link broken

### ISSUE THREAD

**Issue by ParamThakkar123** [opencv/opencv#24515]
The links mentioned in the OpenCV documentation here https://docs.opencv.org/4.x/d4/db1/tutorial_py_svm_basics.html in the additional resources section is broken.

**Comment by shubh1176** [comment]
Hello, we can replace the link with [https://nptel.ac.in/courses/117108048] in the documentation

this will resolve the issue

**Comment by dkurt** [comment]
@shubh1176, can you please propose a pull request with necessary changes? Take a look on both entries:
https://github.com/opencv/opencv/blob/064fdba1201bd2b20bc0115dc99a968ccbf37718/doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.markdown?plain=1#L144
https://github.com/opencv/opencv/blob/064fdba1201bd2b20bc0115dc99a968ccbf37718/doc/py_tutorials/py_ml/py_svm/py_svm_basics/py_svm_basics.markdown?plain=1#L132

**Comment by shubh1176** [comment]
Sure!
