### ISSUE TITLE
remap with maps as vectors rather than coordinates.

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#24603]
### Describe the feature and motivation

Currently, `remap()`  is applied as `dst(x, y) <- src(mapX(x, y), mapY(x, y))`
It means that the maps must be filled with absolute coordinates.

However, if one wants to remap something according to a displacement field ("warp"), the operation should be
`dst(x, y) <- src(x+displacementX(x, y), y+displacementY(x, y))`

It is trivial to build a mapping from a displacement field, but it is an undesirable overhead for CPU and memory.

Could `remap()` support a flag to optionally understand the mapping as a displacement field ?

Of course, it impacts a lot of code (IPP/OCL/HAL/cuda implementations)

**Comment by asmorkalov** [comment]
@chacha21 You added relative option to remap. May the issue be closed?
