### ISSUE TITLE
Using onnx model for target detection through OPENCV  and C++, the results running through CPU and GPU are inconsistent

### ISSUE THREAD

**Issue by lie12huo** [opencv/opencv#24606]
### Describe the feature and motivation

I used Yolov8's onnx model for target detection through C++, and the detection results running through the CPU were correct. When calling net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV) and
net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU) turns on CUDA DNN detection, the data returned by the net.forward() function, the class_id and confidences data are consistent with the CPU operation, but all box data are null.
CPU result:
![image](https://github.com/opencv/opencv/assets/52315796/3df63469-9036-469f-b503-3d431e574a9c)

GPU result：
![image](https://github.com/opencv/opencv/assets/52315796/932614cc-51cc-453f-95b3-56f9de41df5d)

The OPENCV version I used is 4.8.1, the CUDA version is 11.8, the CUDNN version is 8.9.6, the graphics card model is NVIDIA GeForce GTX 1660 Ti, and the driver version is 546.17.

In addition, if the model is called directly in Python, the results of running on CPU or GPU will be correct. The same OpenCV, CUDA and DNN versions are used when running in Python and C++.

**Comment by fengyuentau** [comment]
@lie12huo Please upload your yolov8 model for us to debug.

**Comment by lie12huo** [comment]
[YOLOv8-CPP-Inference.zip](https://github.com/opencv/opencv/files/13485363/YOLOv8-CPP-Inference.zip)

For models and related codes, please see the compressed package above.

**Comment by lie12huo** [comment]
@zp870420 
I am not using cv2.DNN_BACKEND_CUDA of opencv-python，I am using the YOLO library in Python to load the model and perform target detection.
Such as:
OnnxModel = YOLO("yolov8s.onnx")
results = OnnxModel("source.jpg")

**Comment by lie12huo** [comment]
@zp870420 
After I upgraded to debugging, I got the same results as you.
![image](https://github.com/opencv/opencv/assets/52315796/528c4368-6fcd-4cf9-8fda-2059d099cdc6)
And judging from the source code of OpenCV, the OPERATION::SUB operation is indeed not supported in DNN_BACKEND_OPENCV mode.
![image](https://github.com/opencv/opencv/assets/52315796/2078936a-9791-4b01-a1a7-9fcee29ac8dd)
But is this what causes problems with the final output? When OpenCV runs the model, won't it automatically switch operations that are not supported by these two GPUs to the CPU?

**Comment by zp870420** [comment]
@lie12huo yes,not supported  automatically switch。we set DNN_BACKEND_CUDA  ,nodes in front of  this yolov8 onnx model can run on the cuda,but Sub and Sub1 don't。if our os system have no cuda or gpu,but we set DNN_BACKEND_CUDA  ,this automatically switch to cpu、

**Comment by zp870420** [comment]
@lie12huo why ,I am compile the onnxruntime with cuda, I will test

**Comment by fengyuentau** [comment]
Hello, sorry for the late response.

If you want to use dnn with CUDA enabled, you need to **build opencv from source**. Distributed versions (apt install or pip install) do not come with CUDA enabled.

Also if there are some nodes that are not supported by dnn CUDA backend, those nodes will run on CPU instead, while other nodes still runs on GPU.

Additionally, I submitted a PR support Sub operation in CUDA backend https://github.com/opencv/opencv/pull/24647. Feel free to take a look.

**Comment by zp870420** [comment]
> Hello, sorry for the late response.
> 
> If you want to use dnn with CUDA enabled, you need to **build opencv from source**. Distributed versions (apt install or pip install) do not come with CUDA enabled.
> 
> Also if there are some nodes that are not supported by dnn CUDA backend, those nodes will run on CPU instead, while other nodes still runs on GPU.
> 
> Additionally, I submitted a PR support Sub operation in CUDA backend #24647. Feel free to take a look.

good job。I compile the onnxruntime-gpu C++，but dont't work use the yolov8 model。I will try your opencv_code

**Comment by lie12huo** [comment]
@fengyuentau Very good！Have you verified whether the version that supports sub operations can solve the problem of inconsistent running results between CPU and GPU?
In addition, will your code be merged into the main branch of OpenCV?
![image](https://github.com/opencv/opencv/assets/52315796/b1e63d22-280a-4bc4-9e98-758d60225ddf)

**Comment by fengyuentau** [comment]
> Have you verified whether the version that supports sub operations can solve the problem of inconsistent running results between CPU and GPU?

I did not test this. How different are those results? I am saying like complete different bounding boxes and scores.

> In addition, will your code be merged into the main branch of OpenCV?

Yes. Most probably in 4.9.0 release which will be release by the end of this month.

**Comment by lie12huo** [comment]
>How different are those results? I am saying like complete different bounding boxes and scores.

There is no problem with the results returned by the CPU operation. In the results of the GPU operation, the returned bounding box data are all 0, and the remaining object types and detection probabilities are correct.

**Comment by zhaoning999** [comment]
> @fengyuentau @lie12huo yesterday night, I compile the new source code of supore sub,but the returned bounding box data are all 0

try opencv 4.7.0, it works.

**Comment by lie12huo** [comment]
@zhaoning999 Do you mean that using OpenCV4.7.0 can make the results of GPU operation and CPU operation consistent, and are both correct? What are your CUDA and CUDNN versions? 
@fengyuentau  Can I compile the source code of OpenCV4.7.0 based on CUDA11.8 and cudnn 8.9.6?

**Comment by zhaoning999** [comment]
> @zhaoning999 Do you mean that using OpenCV4.7.0 can make the results of GPU operation and CPU operation consistent, and are both correct? What are your CUDA and CUDNN versions? 
> @fengyuentau  Can I compile the source code of OpenCV4.7.0 based on CUDA11.8 and cudnn 8.9.6?

yes, I use cuda 11.8 and cudnn 8.9.2 on windows.

**Comment by lie12huo** [comment]
I recompiled OpenCV 4.7.0 and tried again, but during the process of loading the model, an exception occurred when loading the following nodes.
![image](https://github.com/opencv/opencv/assets/52315796/b758028e-54be-47bb-ba24-f508327e7467)
The error location is at \\opencv-4.7.0\modules\dnn\src\layers\reshape_layer.cpp   computeShapeByReshapeMask
![image](https://github.com/opencv/opencv/assets/52315796/34b65307-4399-4b9c-9d72-254e17752031)

**Comment by lie12huo** [comment]
@zhaoning999 You are right. After I adjusted the model and used OpenCV 4.7.0, object detection can be performed normally through the GPU. Thank you so much!
@fengyuentau @CV-AI-WORLD Thanks for your help too!

**Comment by CV-AI-WORLD** [comment]
> OPENCV 4.7.0 + CUDA 11.8 + CUDNN 8.9.6, this problem can be solved ,the GPU can work normally like the CPU.

@lie12huo thanks for your information,good!

**Comment by fengyuentau** [comment]
I can confirm that this problem is still relavant with the latest release. @Abdurrahheem mentioned [here](https://github.com/opencv/opencv/pull/23255#issuecomment-1869455541.) that this issue relates to the fusion of `Conv` and `Add`.
