### ISSUE TITLE
Problem about Doxygen @tableofcontents

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#24643]
### Describe the doc issue

`\tableofcontents` fixed in Doxygen 1.8.16 (https://github.com/doxygen/doxygen/issues/6791#issuecomment-519634316)

For example, https://docs.opencv.org/4.x/d0/dcc/tutorial_non_linear_svms.html has no table at this moment (Doxygen 1.8.13):
![image](https://github.com/opencv/opencv/assets/25801568/835b0292-e58a-4836-b6cc-366d46350034)

https://docs.opencv.org/4.x/d0/dcc/tutorial_non_linear_svms.html
https://docs.opencv.org/5.x/d0/dcc/tutorial_non_linear_svms.html

Doxygen 1.9.1:
![image](https://github.com/opencv/opencv/assets/25801568/2ea5742e-42b5-473d-9885-97a3a07a5115)

### Fix suggestion

Update Doxygen for public documentation

**Comment by opencv-alalek** [comment]
At this moment CI uses Ubuntu 18.04 for documentation builders.
It is possible to upgrade infrastructure to Ubuntu 22.04 (which has doxygen 1.9.1),  but we need to fix several warnings before deploying that to production: http://pullrequest.opencv.org/buildbot/builders/4_x-contrib_docs-lin64/builds/100592

Prepare PR and add this to description (for testing with new configuration):

```
force_builders_only=docs
build_image:Docs=docs:22.04
buildworker:Docs=linux-4
```

replace `build_image:Docs=docs-js:22.04` to build with JavaScript (+5 min to the job)
