### ISSUE TITLE
doc: `python3-dev` might conflict with `libpython3-dev:aarch64`

### ISSUE THREAD

**Issue by Kumataro** [opencv/opencv#24695]
- OpenCV: 4.x

`python3-dev` might conflict with `libpython3-dev:aarch64`

_Originally posted by @dkurt in https://github.com/opencv/opencv/pull/24629#discussion_r1425238394_

**Comment by Kumataro** [comment]
I will fix document at `apt install python3-dev`. 

However multi libpython3-dev packages seem to coexist, not conflict.

```bash
kmtr@kmtr-None:~/work$ LANG=C sudo apt install -y libpython3-dev:amd64 libpython3-dev:armhf libpython3-dev:arm64
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpython3-dev is already the newest version (3.11.4-5).
libpython3-dev:armhf is already the newest version (3.11.4-5).
libpython3-dev:arm64 is already the newest version (3.11.4-5).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

I think they have commonly files...

```
/usr/share/doc/libpython3-dev/README.Debian
/usr/share/doc/libpython3-dev/changelog.Debian.gz
/usr/share/doc/libpython3-dev/copyright
```

- https://packages.ubuntu.com/en/mantic/amd64/libpython3-dev/filelist
- https://packages.ubuntu.com/en/mantic/arm64/libpython3-dev/filelist
- https://packages.ubuntu.com/en/mantic/armhf/libpython3-dev/filelist

**Comment by dkurt** [comment]
@Kumataro, ok, but just to reduce weak points I recommend to use only required packages. So if you confirm that python3-minimal is enough, let’s switch on it.

**Comment by Kumataro** [comment]
I agree with you, thank you very much !

I created new Ubuntu 23.10 VM and tried to cross compile.
And I replaced from "python3.11" to "pyhton3-minimal" at target environment with same reason.
