### ISSUE TITLE
OpenCV for Raspberry PI 

### ISSUE THREAD

**Issue by Safa1902** [opencv/opencv#24711]
when i try install open cv on raspberry pi i followed instructions of all videos and i still got the same error when i check by importing numpy library it works but when i write the command import cv2 to test it gives me this message always i dont have much experience to detect the error
**>>> import cv2
Traceback (most recent call last):
File "", line 1, in
File "/home/aamz/.local/lib/python3.9/site-packages/cv2/init.py", line 181, in
bootstrap()
File "/home/aamz/.local/lib/python3.9/site-packages/cv2/init.py", line 153, in bootstrap
native_module = importlib.import_module("cv2")
File "/usr/lib/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/aamz/.local/lib/python3.9/site-packages/cv2/cv2.abi3.so: undefined symbol: __atomic_store_8

**Comment by tomoaki0705** [comment]
I really appreciate if you could post this kind of questions to https://forum.opencv.org/
If you are asking for help, this is not the right place. https://forum.opencv.org/ is.
I'm not blaming you, but there are tooooo many questions like this.
