### ISSUE TITLE
Sample program in C++ for barcode detection cannot read command-line argument for input file correctly

### ISSUE THREAD

**Issue by bobhairgrove** [opencv/opencv#24817]
##### System information (version)
- OpenCV => 4.9.0 (latest)
- Operating System / Platform => Linux Ubuntu 22.04
- Compiler => g++, version 11.40

##### Detailed description
I installed OpenCV by building from sources. The trivial app "DisplayImage" with the file `lena.jpg` works OK. But the sample from [here](https://github.com/opencv/opencv/blob/4.x/samples/cpp/barcode.cpp) cannot open the input file, although it exists and has adequate permissions (0664).
 
##### Steps to reproduce
The error seems to come from the `CommandLineParser::get<string>("in")` call. This occurs at line 187 in the sample code:
```
    const string in_file = cmd_parser.get<string>("in");
    const string out_file = cmd_parser.get<string>("out");
```
etc.

I have the input file located in the same directory as the executable. When I run it like this:
```
./barcode -i ocr_0001.jpg -o ocr_results_opencv.png
```
then I get the following error:
```
[ WARN:0@0.002] global loadsave.cpp:248 findDecoder imread_('true'): can't open/read file: check file path/integrity
Image size: [0 x 0]
Mode is <detectAndDecode>
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.9.0) /home/bob/code/opencv-4.9.0/modules/objdetect/src/barcode.cpp:30: error: (-215:Assertion failed) !img.empty() in function 'checkBarInputImage'

Aborted (core dumped)
```
So I added the following immediately after the call to `cmd_parser.get<string>("in")`:
```
    cout << "\n*****\nThe in_file name: " << in_file 
         << "\n*****\n" << endl;
```
In the output, I see this:
```
*****
The in_file name: true
*****
```
What is going on???

**Comment by Kumataro** [comment]
Hello, this is not a OpenCV bug ( but, perhaps the necessary explanation is missing.)

Please could you try with `./barcode -i=ocr_0001.jpg -o=ocr_results_opencv.png` ?

https://docs.opencv.org/4.x/d0/d2e/classcv_1_1CommandLineParser.html#details

```cpp
#include <opencv2/core.hpp>
#include <string>
#include <iostream>

using namespace cv;
using namespace std;

int main(int argc, char** argv)
{
    const string keys = "{h help ? || print help message }"
                        "{i in |DEF1|input }"
                        "{o out|DEF2|output }";

    CommandLineParser cmd_parser(argc, argv, keys);
    cmd_parser.about("Command Parser Sample");

    if (cmd_parser.has("help"))
    {
        cmd_parser.printMessage();
        return 0;
    }

    const string in_file = cmd_parser.get<string>("in");
    const string out_file = cmd_parser.get<string>("out");
    std::cout << " in_file  = " << in_file << std::endl;
    std::cout << " out_file = " << out_file << std::endl;
    return 0;
}
```

```
kmtr@kmtr-None:~/work/build4-main/issue24817$ ./a.out
 in_file  = DEF1
 out_file = DEF2
kmtr@kmtr-None:~/work/build4-main/issue24817$ ./a.out -i ABC
 in_file  = true
 out_file = DEF2
kmtr@kmtr-None:~/work/build4-main/issue24817$ ./a.out -i=ABC
 in_file  = ABC
 out_file = DEF2
```

**Comment by Kumataro** [comment]
Supplement.

`-i XXXX.jpg` can be recognized 2 meanings.

1. `-i` option has been set with `XXXX.jpg` parameter
2. `-i` option has been set(true), and `XXXX.jpg` has been set as nameless option. (OpenCV)

So this is difficult.

**Comment by bobhairgrove** [comment]
> Hello, this is not a OpenCV bug ( but, perhaps the necessary explanation is missing.)
> 
> Please could you try with `./barcode -i=ocr_0001.jpg -o=ocr_results_opencv.png` ?
> 
> https://docs.opencv.org/4.x/d0/d2e/classcv_1_1CommandLineParser.html#details
> 
@Kumataro  - Thank you for the detailed explanation, example code, and the link to the documentation.

It works OK now.
