### ISSUE TITLE
Get Access to \epsilon parameter of the charbonier norm (Brox2004) in VariationalRefinement

### ISSUE THREAD

**Issue by jeffwitz** [opencv/opencv#24847]
### Describe the feature and motivation

In the norm $E(x) = \sqrt{x^2+\epsilon^2}$ used Brox2004 and implemented in cv::VariationalRefinement Class, the parameter $\epsilon$ is fixed and only used to make the norm differentiable in contrast with the TVL1 one.
This parameter is not just a numerical artifact and can be used to pass from L2 norm to L1 norm  continuously as it is often the case in the robust norm (or metrics).
It would be very easy to expose this parameter and thus help us to obtain more consistent results in Optical Flow regarding the noise rejection and the regularization.  
Could you expose this parameter as it doesn't change anything by default ?

**Comment by Octopus136** [comment]
Hi, Could you please provide more details on how you intend to use it? Would utilizing getEpsilon() be sufficient, treating it like any other parameter?

**Comment by jeffwitz** [comment]
> Hi, Could you please provide more details on how you intend to use it? Would utilizing `getEpsilon()` and `setEpsilon()` be sufficient, treating it like any other parameter?

Of course. Yes it is definitely sufficient. I add the getEpsilon et setEpsilon in ./video/src/variational_refinement.cpp and add the CV_WRAP in ./video/include/opencv2/video/tracking.hpp and it works quite well.

It really depends of the texture of your picture, but 1e-3 is always close to TVL1 and between 2e-1 and 5e-3 seems to work in the several cases I've tried.

I also add what I need for dis_flow, as it is the fastest one that use variational_refinement and it also work as expected. I add the file I change here : [VariationalRefinementModification.zip](https://github.com/opencv/opencv/files/13924670

I work in mechanics field ans we can't use TVL1 as the quantification of the displacement induced by the L1 norm leads to inconsistent jacobian of the transformation (strain tensor) which are structured and create artificial localozations, it is a no go for us. We this modification it work as expected, I succeed in finding the sweet spot for Epsilon, which gives less diffuse results than L2 with non structured jacobian of the transformation.

I am no code-guru at all, so I think it surely has to be polished to be acceptable for you.

I rarely compile OpenCV as I use it with python so pip is the way. It was quite painful to find how to compile with the good python env, so I hope I won't have to do it in the future to enjoy this new functionality for the mechanics researchers !

**Comment by kannishk** [comment]
If no one has taken this, can i be assigned this ? @jeffwitz

**Comment by opencv-alalek** [comment]
See #24852

**Comment by jeffwitz** [comment]
> If no one has taken this, can i be assigned this ? @jeffwitz

The DISFlow part has not been made, I use it locally and it is really great.

You can download the files that I change in order to have an idea, it is quite simple

**Comment by vagish-yadav** [comment]
is this issue still open ??

**Comment by Octopus136** [comment]
> is this issue still open ??

@vagish-yadav It should be closing soon, see #24852
