### ISSUE TITLE
Support image animations

### ISSUE THREAD

**Issue by vrabaud** [opencv/opencv#24855]
### Describe the feature and motivation

Several formats (e.g. GIF, WebP, AVIF) support animations. Those are different from multi-page files (like TIFF) as there is a bit more information like frame duration or loop count.
`VideoCapture` can read them though the FFMPEG backend but this is a heavy dependency when imgcodecs already depends on those image libraries.
`VideoWriter` does not support writing animations as it relies on FOURCC (video only).

I propose the following solution:
- add an imreadanimation/imdecodeanimation/imwriteanimation in imgcodecs
- the API also includes the frame durations (`vector<int>`) and loop count

Support for WebP, AVIF, APNG can easily be added as the libraries are already linked to. GIF is harder and the GIF API is hard to use.

Maybe that could be a GSOC idea?

**Comment by vrabaud** [comment]
This is a superset of https://github.com/opencv/opencv/issues/22569

**Comment by kannishk** [comment]
I want to work on this feature @vrabaud

**Comment by sturkmen72** [comment]
![image](https://github.com/opencv/opencv/assets/12151541/8c8c982d-f444-4c9b-a5cb-96fbcb7c46c3)
(source : https://mathiasbynens.be/demo/animated-webp)

is this image is suitable to merge in https://github.com/opencv/opencv_extra to be used in tests.

or is there any recommended image ?

**Comment by sturkmen72** [comment]
also what is your opinion to use this images https://apng.onevcat.com/demo/
