### ISSUE TITLE
bug in initUndistortRectifyMap() ?

### ISSUE THREAD

**Issue by nnop** [opencv/opencv#24882]
It seems the input `_newCameraMatrix` is never used. 
Here is the implementation:
https://github.com/opencv/opencv/blob/62ef27ac1e9df26d475a76f9a34f4ca78cb34390/modules/calib3d/src/undistort.dispatch.cpp#L87-L166

In these line, when `_newCameraMatrix` is provided, it still used the old `cameraMatrix`(which `A` is):
https://github.com/opencv/opencv/blob/62ef27ac1e9df26d475a76f9a34f4ca78cb34390/modules/calib3d/src/undistort.dispatch.cpp#L110-L113

Is this a bug?

**Comment by mshabunin** [comment]
`newCameraMatrix` is stored in the `Ar` if not empty, then inversed to `iR`, then passed to `parallel_for_` / `getInitUndistortRectifyMapComputer`. What is the original problem? Do you have a reproducer maybe?

**Comment by nnop** [comment]
> `newCameraMatrix` is stored in the `Ar` if not empty
Which line does this?
