### ISSUE TITLE
Move ML module to opencv_contrib

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#24997]
### Describe the feature and motivation

After ~25 years of developing OpenCV and ~20 years of opencv_ml module history we found that it's time to move ML outside of the main repository. Here are the major reasons:

* ML module is not used in other parts of OpenCV, it's not used in any samples or tutorials, except for samples or tutorials about ML itself. Very few, if any, people from OpenCV community actually use it.
* Traditional ML has been completely replaced with Deep Learning in Computer Vision.
* Traditional ML, including decision trees, boosting (especially gradient boosting), support vector machines etc. is still actively used by scientific community, but there are high-quality packages that implement state-of-art approaches, most notable of which is scikit-learn. We don't see any strong reason and don't have any resources to compete with such packages. 

So, we are going to move ML module to opencv_contrib together with tests, samples, docs/tutorials.

**Comment by crackwitz** [comment]
Consider that there are still people that want such stuff reachable from C++, so `scikit-learn` is a great substitute for many users, but not all.

**Comment by opencv-alalek** [comment]
kmeans and PCA should be moved out of the `core` module first (higher priority than touching of "standalone" ML module)

**Comment by vpisarev** [comment]
@opencv-alalek, moved where? kmeans is still quite actively used. PCA maybe less so, but it's quite fundamental thing that is still used, even with deep nets (it's the 'cheapest' auto-encoder)

**Comment by opencv-alalek** [comment]
ML module is a best candidate as target, but it's suggested to be removed.

**Comment by vpisarev** [comment]
another good place for kmeans and PCA is Features (former Features2D) module: #24999

**Comment by fengyuentau** [comment]
Should this one be closed since PR is merged?

**Comment by asmorkalov** [comment]
CI: https://github.com/opencv/ci-gha-workflow/pull/156

**Comment by joda01** [comment]
@vpisarev I totally understand. Which C++ libs do you recommend for replacement. I think random forest and k-means are still used because of their fast training and robustness.
I thought about MLpack for RandomForest and libtorch for ANN_MLP. Do you have other suggestions/better suggestions?
