### ISSUE TITLE
Clean Features2D, rename it to Features

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#24999]
About 10 years ago we experimented a lot with different feature detectors and feature descriptors that were all used for 2D image registration and related tasks: planar object recognition (e.g. CD cover or book cover recognition), planar object tracking, panorama stitching, fundamental/essential matrix estimation, SLAM etc.

There was king of the hill, SIFT algorithm, but it was patented, so people developed quite a few alternatives.
Now SIFT patent is expired, so everybody can freely use it. Other algorithms perform sometimes a little better, sometimes a little worse. After 20 years (D. Lowe paper was published in 2004) SIFT still remains a gold standard, especially with all the subsequent improvements and extensions like A-SIFT (already implemented in OpenCV), rootSIFT (easy to add as an option) etc.

We don't need so many different detectors/descriptors anymore. We can still keep FAST, Good Features To Track, MSER and a few other algorithms, but remove (move to opencv_contrib) most of the other stuff, such :

* SURF
* BRISK
* KAZE/AKAZE
* AGAST
* ORB (or, perhaps, we can keep it as super-fast alternative to SIFT)

There is another big part of Features2D, which is feature matching. Currently, it's a wrapper on top of FLANN.
It's suggested to remove FLANN and put a better and/or more compact alternative to FLANN into Features2D.

Also, nowadays with the rise of deep learning/AI the concept of 'features' is more popular and relevant than ever. Features are often computed by various deep nets, e.g. for face recognition. So, feature matching is very relevant task. Therefore, it's suggested to rename Features2D module to just Features. See also #24998

**Comment by jmbuena** [comment]
I have just found this Features2D reorganization.

If you one a super-fast alternative to SIFT and want to keep ORB, I would use TEBLID as the descriptor instead. It is equivalent in speed (a little bit faster for its parallel implementation) but it works much better.

**Comment by asmorkalov** [comment]
@jmbuena Could you file dedicated feature request for it. It's great project for GSoC.

**Comment by asmorkalov** [comment]
Renaming PR: https://github.com/opencv/opencv/pull/26405

**Comment by jmbuena** [comment]
> @jmbuena Could you file dedicated feature request for it. It's great project for GSoC.

Hi @asmorkalov. What kind of work are you thinking in? Go to OpenCV 4.X and introduce TEBLID as descriptor for the current ORB detector? Or just do it for OpenCV 5.X?

Talking to @iago-suarez, I have not looked into the current ORB implementation but it seems that we (@jmbuena and @iago-suarez) could implement it.
