### ISSUE TITLE
Request to community: please help us to choose minimum C++ standard for OpenCV 5.0

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#25040]
Please, vote at https://github.com/opencv/opencv/discussions/25039

**Comment by rohanyadav9** [comment]
#include <iostream>
#include <string>

using namespace std;

int main() {
  
    string name = "Rohan Yadav";
    string degree = "BS in Computer Science and Data Analytics";
    string institution = "IIT Patna";

    // Introduction message
    cout << "Hello! My name is " << name << ".\n";
    cout << "I am currently pursuing a " << degree << " at " << institution << ".\n";
    

    cout << "I have experience in the following areas:\n";
    cout << "- Python programming\n";
    cout << "- Machine Learning\n";
    cout << "- Data Analysis\n";
    cout << "- Web Development\n";

    cout << "\nI would love to contribute to open-source projects.\n";
    cout << "Could you kindly guide me on how I can start contributing?\n";

    
    cout << "Thank you for your time and consideration!\n";

    return 0;
}

**Comment by arjunMitmanipal** [comment]
c++17 / c++20

**Comment by asmorkalov** [comment]
Decided on C++17.
