### ISSUE TITLE
Simple FaceDetectorYN speedup by pre-culling face bboxes?

### ISSUE THREAD

**Issue by wingman-jr-addon** [opencv/opencv#25056]
### Describe the feature and motivation

While reviewing `FaceDetectorYNImpl::postProcess` to see how it worked, I noticed that the `scoreThreshold` is only used to cull `faces` in the non-maximum suppression call late in the function. I think an opportunity exists to just not add the box unless it meets the `scoreThreshold` around this line of code as `dnn::NMSBoxes` does that anyways later:
https://github.com/opencv/opencv/blob/f0e3d2f2f8dfac4583e277f791089d0c27d2ece0/modules/objdetect/src/face_detect.cpp#L200
If I understand correctly, this would be a helpful advantage because there are typically many 1000's of raw face boxes but after thresholding on the score it could often drop to well below 100, which would help with a few things: dynamic memory allocation up front, reduced copies to `faceBoxes`, and reduced input to ` dnn::NMSBoxes`.

Does this seem reasonable or am I missing something important about how it works?

**Comment by asmorkalov** [comment]
@fengyuentau could you comment?

**Comment by fengyuentau** [comment]
Yes, your proposal can be helpful to reduce candidate bboxes before NMS. Feel free to submit PR for optimization.
