### ISSUE TITLE
5D blob in opencv : back to c function?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#25129]
### Describe the feature and motivation

I need a 5D blob as model input  : tensor: float32[2,1,3,240,320]

I cannot find an opencv function. i wrote : 

```
        Mat img0 = imread("C:/data/kitti/testing/image_2/000198_10.png");
        Mat img1 = imread("C:/data/kitti/testing/image_2/000198_11.png");
        Image2BlobParams param;
        param.datalayout = DNN_LAYOUT_NCHW;
        param.size = Size(320, 240);

        Mat blob0 = blobFromImageWithParams(img0, param);
        Mat blob1 = blobFromImageWithParams(img1, param);
        vector<int> szData = { 2, 1, 3, 240 ,320 };
        Mat blob(szData, CV_32FC1);
        memcpy(blob0.data, blob.data, 3 * 240 * 320 * 4);
        memcpy(blob1.data, blob.data + 3 * 240 * 320 * 4, 3 * 240 * 320 * 4);

```

May be an opencv function would be usefull.

As a problem never comes alone output result is tensor x: float32[1,2,240,320]
It would be nice to have an opencv function which can extract two images x[0,0] and x[0, 1] (https://github.com/opencv/opencv/pull/24173)

### Additional context

https://github.com/MasterHow/CSFlow

**Comment by fengyuentau** [comment]
> float32[2,1,3,240,320]

Dimension `1` looks redundant. Is it possible to modify the model structure from code so that it takes batch of two images, e.g. [2, 3, 240, 210]?

**Comment by dkurt** [comment]
I suggest blobFromImages to get 2x3x240x320 blob and then blob.reshape to a new shape with extra 1

**Comment by LaurentBerger** [comment]
Ok that's noob method : 

```
        Image2BlobParams param;
        param.datalayout = DNN_LAYOUT_NCHW;
        param.size = Size(320, 240);
        Mat blob4d = blobFromImagesWithParams(vector<Mat> {img0, img1}, param);
        blob5d = blob4d.reshape(0, vector<int> {2,  1, 3, 240, 320 });

```

and to extract result         imagesFromBlob and split
