### ISSUE TITLE
Please add camera calibration for telecentric lenses. 

### ISSUE THREAD

**Issue by HomicidalBrainiac** [opencv/opencv#25144]
### Describe the feature and motivation

Telecentric lenses are used extensively with computer vision and industrial settings.  Current camera calibration library only supports pinhole model, which cannot be used for telecentric lenses.  Although distortion is generally low with telecentric lenses, it would be helpful to be able to calibrate distortion coefficients in addition to proper camera matrix from a calibration target.

**Comment by mynickmynick** [comment]
hi guys this issue is redundant and should be merged with the one I just opened a few days before #25126
