### ISSUE TITLE
Cannot search function in opencv 4.10.0-dev online doc

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#25169]
### Describe the doc issue

Search box is dead in opencv 4.10.0-dev
There is no problem in 4.9.0 doc

![image](https://github.com/opencv/opencv/assets/3591626/afc719a5-80cb-4a92-874a-f51722c75260)

**Comment by opencv-alalek** [comment]
There was doxygen version upgrade yesterday.
Perhaps some resources of old version are still cached in your browser.
Try to press "Ctrl + F5" in your browser.
