### ISSUE TITLE
Renaming `cv::float16_t` and `cv::bfloat16_t` on 5.x to avoid redefinition

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv#25210]
### Describe the feature and motivation

`cv::float16_t` and `cv::bfloat16_t` are defined in `modules/core/include/opencv2/core/cvdef.h`, former of which was introduced long time ago, the other of which was added recently. They are created for the usage of fp16 and bf16 across different platforms internally in OpenCV. However, the naming has conflict with `arm_neon.h` which has definition `typedef __fp16 float16_t;`, leading to type redefinition or conflict for some of the fp16 intrinsics. For example, `clang` defines `vdupq_n_f16` as a macro:

```cpp
#ifdef __LITTLE_ENDIAN__
#define vdupq_n_f16(__p0) __extension__ ({ \
  float16x8_t __ret; \
  float16_t __s0 = __p0; \
  __ret = (float16x8_t) {__s0, __s0, __s0, __s0, __s0, __s0, __s0, __s0}; \
  __ret; \
})
#else
#define vdupq_n_f16(__p0) __extension__ ({ \
  float16x8_t __ret; \
  float16_t __s0 = __p0; \
  __ret = (float16x8_t) {__s0, __s0, __s0, __s0, __s0, __s0, __s0, __s0}; \
  __ret = __builtin_shufflevector(__ret, __ret, 7, 6, 5, 4, 3, 2, 1, 0); \
  __ret; \
})
#endif
```

When the preprocessor extracts `vdupq_n_f16`, the type `float16_t` in it will be treated as `cv::float16_t` instead of `__fp16`, leading to a compile error. Also note that [C++23 introduces std::float16_t, std::bfloat16_t](https://en.cppreference.com/w/cpp/types/floating-point). Hence, we need to consider the renaming of existing `cv::float16_t` and `cv::bfloat16_t`.

### Additional context

After a discussion with @vpisarev , we think they can be renamed as:

```
cv::float16_t -> cv::fp16_t
cv::bfloat16_t -> cv::bf16_t
```

**Comment by vpisarev** [comment]
alternative names for the types:

cv::float16_t:
  * fp16_t
  * cvfp16
  * half_t
  * hfloat_t

cv::bfloat16_t:
   * bf16_t
   * cvbf16
   * bfloat_t

it's suggested that in OpenCV 5.x we just do the renaming. In OpenCV 4.x we do the same renaming and add a single-line typedef for backward compatibility:

```
typedef <new_float16_name> float16_t;
```

This way the codebases will be synchronized, but OpenCV 4.x users could use the older name.

**Comment by mshabunin** [comment]
Can we just define new type conditionally?
```.cpp
#if !(defined __STDCPP_FLOAT16_T__) && !(defined __ARM_NEON)
typedef our_pod_fp16_struct float16_t;
#endif
```
All non-trivial methods would need to be moved from our class to separate functions.

**Comment by vpisarev** [comment]
what about yet another 2 options?
1. float16_t => hfloat
2. bfloat16_t => bfloat

they would definitely be easier to type than fp16_t and bf16_t, respectively.
