### ISSUE TITLE
i keep getting this error while compiling my program using:msys2 mingw64 and opencv ( i am a still a newbie in this stuff so sorry if my problem is too dumb )

### ISSUE THREAD

**Issue by wowzie22** [opencv/opencv#25288]
Hey there  I am a still a newbie in this stuff so sorry if my problem is too dumb there so it's been like 2 weeks of me trying to get this working and its driving me nuts I don't know why it just doesn't want to work so I installed opencv mingw version from msys2 the install command: pacman -S mingw-w64-x86_64-opencv so I have been trying to compile my code for well over 2 weeks but i keep hitting the same wall when trying to use mingw with opencv i tried building it with cmake  I tried installing mingw on its own i tried installing mingw posix(it's really old if you have or know a newer version of it might fix my problem )I think i  tried all the possible ways of installing mingw opencv so I don't think it's in the install its in me or my way of putting the compiling code and if you are wondering why I am not just using vs community or whatever it's called i am currently in an area that have a limited internet and vs community is like 20gb
so, I can't install it right now anyway let me get straight to the point this is the compiler code that i use:
``` 
g++ -o test test.cpp -IC:\msys64\mingw64\include\opencv4 -LC:\msys64\mingw64\lib -lopencv_core -lopencv_highgui -lopencv_imgproc 
```
and this is the error each time i try compiling it 
``` 
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\wowzie\AppData\Local\Temp\ccj3yr91.o:test.cpp:(.text+0xca): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\wowzie\AppData\Local\Temp\ccj3yr91.o:test.cpp:(.text+0x22b): undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Kumataro** [comment]
Hello, `imread()` and `imwrite()` are implemented in imgcodecs. I think you should add `-lopencv_imgcodecs` option.

**Comment by wowzie22** [comment]
> Hello, `imread()` and `imwrite()` are implemented in imgcodecs. I think you should add `-lopencv_imgcodecs` option.
OH THANK YOU SO MUCH YOU ARE A LEGEND

**Comment by wowzie22** [comment]
> Hello, `imread()` and `imwrite()` are implemented in imgcodecs. I think you should add `-lopencv_imgcodecs` option.
