### ISSUE TITLE
werid error while compiling in mingw msys2 opencv (sorry if i its newbie mistake)

### ISSUE THREAD

**Issue by wowzie22** [opencv/opencv#25289]
so there is a problem when it compiles it tells me this error when i try running the .exe The code execution cannot proceed because Qt6Widgets. dll was not found. opencv and The code execution cannot proceed because Qt6Widgets. dll was not found. opencv , The code execution cannot proceed because Qt6Core. dll was not found. opencv , The code execution cannot proceed because Qt6Gui. dll was not found. opencv , The code execution cannot proceed because Qt6OpenGLwidgets. dll was not found. opencv , The code execution cannot proceed because Qt6Test. dll was not found. opencv my brain hurts

**Comment by asmorkalov** [comment]
please use forum.opencv.org for questions.

**Comment by wowzie22** [comment]
> please use forum.opencv.org for questions.

sorry
