### ISSUE TITLE
Expose HAVE_WIN32UI HAVE_GTK HAVE_COCOA HAVE_WAYLAND  in cvconfig.

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#25329]
### Describe the feature and motivation

I use waikeyEx (or pollkey) in my program. On windows page up key code is     0x210000,  In wsl2 key code is 0x10ff55.
i don't know how to define PAGE_UP key because I cannot check system at compile time.
Of course it's possible to add a constant in cmake file  and use this constant in source code but I don't want to do that.

My request is 
Add 
#cmakedefine HAVE_WIN32UI
#cmakedefine HAVE_GTK
#cmakedefine HAVE_COCOA
#cmakedefine HAVE_WAYLAND
in cvconfig.h.in
then at compile time GUI will be known

**Comment by opencv-alalek** [comment]
`cvconfig.h` is not a part of OpenCV public API.

**Comment by LaurentBerger** [comment]
> `cvconfig.h` is not a part of OpenCV public API.

What do you mean?

It is used [here ](https://github.com/opencv/opencv/blob/4.x/apps/interactive-calibration/main.cpp#L7C1-L7C30)

**Comment by LaurentBerger** [comment]
My code is

```
#ifdef HAVE_WIN32UI
#define KEY_CODE_ESC 0x1b
#define KEY_CODE_DOWN_ARROW 0x280000
#endif

#ifdef HAVE_GTK3
#define KEY_CODE_ESC 0x10001b
#define KEY_CODE_DOWN_ARROW 0x10ff54
#endif

keyCode=0;
while (keyCode!= KEY_CODE_ESC)
{
  keyCode = cv::waitKeyEx(10);
  switch (keyCode ) {
                  case KEY_CODE_DOWN_ARROW:
....
}
```
I don't know how to do it without constant expression.

**Comment by LaurentBerger** [comment]
What's https://github.com/opencv/opencv/blob/e0b7f04fd240b3ea23ae0cc2e3c071c2e018a7ec/modules/highgui/src/backend.cpp#L49
