### ISSUE TITLE
[Feture request] Use libjpeg-turbo to decode JPEG

### ISSUE THREAD

**Issue by ternaus** [opencv/opencv#25331]
### Describe the feature and motivation

Right now, OpenCV does not use libjpeg-turbo under the hood, which makes is twice slower than all other decoding libraries:

benchmark: https://dev.to/viglovikov/jpeg2rgb-array-showdown-libjpeg-turbo-vs-kornia-rs-vs-tensorflow-vs-torchvision-2mnh

**Comment by asmorkalov** [comment]
OpenCV uses 3rd-party library for jpeg decoding: libjpeg or libjpeg-turbo depending on OpenCV build options. Just re-build OpenCV with proper dependencies.
