### ISSUE TITLE
cv::countNonZero /documentation/ add remark about using cv::hasNonZero

### ISSUE THREAD

**Issue by nji9nji9** [opencv/opencv#25345]
### Describe the doc issue

countNonZero in most cases is used to know if hasNonZero.
Using hasNonZero in that cases is
- more efficient
- semantically correct

### Fix suggestion

To promote adaequate code I suggest to add to the doc of countNonZero
something like:

For determing IF there is a non-zero array element use hasNonZero.
(For multi-channel arrays do a Mat::reshape (O(1) operation) before.

---------

Moreover add links to hasNonZero and Mat::reshape.

**Comment by Kumataro** [comment]
I made pull request to update documents for *Non Zero functions. Is this enough ?

- https://pullrequest.opencv.org/buildbot/export/pr/25356/docs/d2/de8/group__core__array.html#gaa4b89393263bb4d604e0fe5986723914
- https://pullrequest.opencv.org/buildbot/export/pr/25356/docs/d2/de8/group__core__array.html#gaed7df59a3539b4cc0fe5c9c8d7586190
- https://pullrequest.opencv.org/buildbot/export/pr/25356/docs/d2/de8/group__core__array.html#gae050b67f77d525133bdf0cbca20e54f2

**Comment by nji9nji9** [comment]
That is exactly how I meant.

For sure the hints are "enough".
However being a freshman I can't assess if this kind of hints
belong into a concise document or better into a tutorial.
But due to the obviously wide spreaded mutual "misuse"
of the functions I think the hints should be in the doc,
where the functions are searched for in the first place.

**Comment by Kumataro** [comment]
I'm very sorry, but unfortunately, I may misunderstand  what you think it should be and/or what is missing in now.
Please could you clear it ?

> But due to the obviously wide spreaded mutual "misuse"
> of the functions I think the hints should be in the doc,
> where the functions are searched for in the first place.

I think this condition will be satisfied.

1. Open https://docs.opencv.org/4.9.0/
2. Input "countNonZero", "findNonZero" or "hasNonZero" at search text box at top-right  (not "Enhanced by Google" search text box at top).
3. Search it.
4. Select "cv::countNonZero", "cv::findNonZero" or "cv::hasNonZero"
5. These function usages will be shown.

( If you said about result of google/bing/others search site, I think it is too difficult/hard to control it. )

**Comment by nji9nji9** [comment]
You didn't misunderstand me. Everything is fine.
I just wanted to remind on a possible objection.

I'm sorry having caused confusion.
Thank you for inserting the pull request!
