### ISSUE TITLE
Implement Numpy 2.0 support in Python bindings

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv#25455]
### Describe the feature and motivation

Note that numpy 2.0.0rc1 is now publicly available: https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395

**Comment by mshabunin** [comment]
I've checked builds with recent NumPy versions on Ubuntu 22, it seems that with 2.x everything just works :slightly_smiling_face: See my experimental repository: https://github.com/mshabunin/opencv-numpy-check

The only modification I made was in Python tests - NumPy 2.x doesn't support `float_`:
```.diff
diff --git a/modules/python/test/test_misc.py b/modules/python/test/test_misc.py
index bcd3152699..08ab04d53d 100644
--- a/modules/python/test/test_misc.py
+++ b/modules/python/test/test_misc.py
@@ -451,7 +451,7 @@ class Arguments(NewOpenCVTests):
         try_to_convert = partial(self._try_to_convert, cv.utils.dumpFloat)
         min_float, max_float = get_limits(ctypes.c_float)
         for convertible in (2, -13, 1.24, np.float32(32.45), float(32), np.double(12.23),
-                            np.float32(-12.3), np.float64(3.22), np.float_(-1.5), min_float,
+                            np.float32(-12.3), np.float64(3.22), min_float,
                             max_float, np.inf, -np.inf, float('Inf'), -float('Inf'),
                             np.double(np.inf), np.double(-np.inf), np.double(float('Inf')),
                             np.double(-float('Inf'))):
@@ -495,7 +495,7 @@ class Arguments(NewOpenCVTests):
         min_float, max_float = get_limits(ctypes.c_float)
         min_double, max_double = get_limits(ctypes.c_double)
         for convertible in (2, -13, 1.24, np.float32(32.45), float(2), np.double(12.23),
-                            np.float32(-12.3), np.float64(3.22), np.float_(-1.5), min_float,
+                            np.float32(-12.3), np.float64(3.22), min_float,
                             max_float, min_double, max_double, np.inf, -np.inf, float('Inf'),
                             -float('Inf'), np.double(np.inf), np.double(-np.inf),
                             np.double(float('Inf')), np.double(-float('Inf'))):
```

OpenCV built with NumPy 2.x works with NumPy 1.x (not vice versa). I haven't checked NumPy versions older than 1.21.5 though. See https://github.com/mshabunin/opencv-numpy-check/blob/d2e5f9b4ccd7c689263b5992c5036b60a2c716b6/run.sh#L44-L48

**Comment by asmorkalov** [comment]
@what about backward compatibility with 1.x? D we need extra opencv-python packages for it?

**Comment by mshabunin** [comment]
Created #25541 with test fixes for 2.0

**Comment by asmorkalov** [comment]
Not yet. The team fixed NumPy 2.0 related issues in main repo and still works on OpenCV-Python build scrips. I hope, we will finish with NumPy 2.0 for the next OpenCV-Python release.

**Comment by asmorkalov** [comment]
In case if you want to get NumPy 2 compatible packages you have to build them from sources.

**Comment by jakirkham** [comment]
Thanks Alexander! 🙏

Do existing OpenCV wheels have a NumPy 2 upper bound?

Asking as NumPy plans to release NumPy 2 on June 16th ( https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448 ). So if OpenCV NumPy 2 compatibility takes longer, it would be good to make sure the wheels are not installed with NumPy 2 (at least until a supported OpenCV release comes out)

**Comment by asmorkalov** [comment]
No, no upper bound for now.

**Comment by risemeup1** [comment]
> In case if you want to get NumPy 2 compatible packages you have to build them from sources.

1 Could you plz provide me with the steps to compile opencv-python from source code?
2 Can you tell me when the next release version of opencv-python will be released?

Thanks，Looking forward to your reply.

**Comment by asmorkalov** [comment]
You need just install numpy 2.0 for your python and follow generic build steps. Also you can build own wheel with https://github.com/opencv/opencv-python

**Comment by risemeup1** [comment]
> 你只需要为你的 Python 安装 numpy 2.0 并按照通用的构建步骤操作即可。你也可以使用[https://github.com/opencv/opencv-python构建自己的 wheel](https://github.com/opencv/opencv-python)

I have encountered the following compilation issue, how can I solve it?” 
<img width="1131" alt="image" src="https://github.com/opencv/opencv/assets/62429225/6e5ba97a-c83e-4714-a244-46b4f40f564c">

**Comment by risemeup1** [comment]
> > 你只需要为你的 Python 安装 numpy 2.0 并按照通用的构建步骤操作即可。你也可以使用[https://github.com/opencv/opencv-python构建自己的 wheel](https://github.com/opencv/opencv-python)
> 
> I have encountered the following compilation issue, how can I solve it?” <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/62429225/338806464-6e5ba97a-c83e-4714-a244-46b4f40f564c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA5ODEsIm5iZiI6MTcxODE2MDY4MSwicGF0aCI6Ii82MjQyOTIyNS8zMzg4MDY0NjQtNmU1YmE5N2EtYzgzZS00NzE0LWEyNDQtNDZiNGY0MGY1NjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTBjNmE3NTk5YjY1ZDY1MmNhM2M4N2RjNDdiMmJlODcwODIxNGQxMzEyOGFhZGU3NzZhNGMwZTQxOGYyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YB5S5WTjib82Jnf6nSHAh7erf6SZ0_ajiwRgBxO7rM">

or could you plz offer me a opencv-python wheel built in numpy2.0?

**Comment by risemeup1** [comment]
> > > 你只需要为你的 Python 安装 numpy 2.0 并按照通用的构建步骤操作即可。你也可以使用[https://github.com/opencv/opencv-python构建自己的 wheel](https://github.com/opencv/opencv-python)
> > 
> > 
> > I have encountered the following compilation issue, how can I solve it?” <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/62429225/338806464-6e5ba97a-c83e-4714-a244-46b4f40f564c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA5ODEsIm5iZiI6MTcxODE2MDY4MSwicGF0aCI6Ii82MjQyOTIyNS8zMzg4MDY0NjQtNmU1YmE5N2EtYzgzZS00NzE0LWEyNDQtNDZiNGY0MGY1NjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTBjNmE3NTk5YjY1ZDY1MmNhM2M4N2RjNDdiMmJlODcwODIxNGQxMzEyOGFhZGU3NzZhNGMwZTQxOGYyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YB5S5WTjib82Jnf6nSHAh7erf6SZ0_ajiwRgBxO7rM">
> 
> or could you plz offer me a opencv-python wheel built in numpy2.0?
I urgently need to compile OpenCV with NumPy 2.0 for my experiment, thank you for your help.

**Comment by asmorkalov** [comment]
OpenCV team works on OpenCV-Python packages update to accommodate to it.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/pull/1001

**Comment by doug-holtsinger** [comment]
> I have encountered the following compilation issue, how can I solve it?
@risemeup1 I ran into that same compile error when building a wheel twice in a row.  Try removing the _skbuild directory
before building a second time.  It resolved the problem for me.
