### ISSUE TITLE
Add face detection model YuNet to the main repo

### ISSUE THREAD

**Issue by kaingwade** [opencv/opencv#25457]
There is the [FaceDetectorYN API](https://docs.opencv.org/4.x/df/d20/classcv_1_1FaceDetectorYN.html) for deep learning based face detection, and the related model is quite small, only 227 KB. The model is also frequently used. Therefore it is reasonable to add it to the main repo. But here are some thoughts:

1. Where should the model be placed? 
In `samples/data/` folder?

2. Which version should be added: the original fp32 model or the quantized fp16 model?

| Models | Dataset | fp32 acc | fp16 acc |
|-|-|-|-|
| YuNet | WIDERFace| 0.88437(E), 0.86560(M), 0.75030(H) | 0.88425(E), 0.86558(M), 0.75018(H) |

The accuracies are quite close. Currently opencv_zoo hosts [the original model](https://github.com/opencv/opencv_zoo/tree/main/models/face_detection_yunet) and it's planned to replace it (and other models too) with the fp16 model in the future.

3. Perhaps in the future tiny and popular dl models which have their specialized DNN API interface can be put to the main repo as well. A possible issue might be synchronizing the models in both the opencv repo and opencv_zoo repo.

**Comment by asmorkalov** [comment]
Discussed and decided use the binary from zoo by link as we have it for now.
