### ISSUE TITLE
Flowchart of class template does not properly horizontally scale

### ISSUE THREAD

**Issue by w-utter** [opencv/opencv#25481]
### Describe the doc issue

If there are a lot of relations between a class template, the page overflows horizontally for its flowchart, making it difficult to read.

[Link to an example doc](https://docs.opencv.org/4.x/de/de1/classcv_1_1Matx.html)

### Fix suggestion

This could be fixed by either scaling down the size or having a more dynamic layout for the flowchart

**Comment by asmorkalov** [comment]
@mshabunin could you take a look on it?
