### ISSUE TITLE
Cover NormHamming with accuracy and perfomance test

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv#25531]
### Describe the feature and motivation

-

**Comment by savuor** [comment]
Looks like we already have both accuracy and performance tests:
1. Accuracy tests: [here](https://github.com/opencv/opencv/blob/f5793d26b7f362f8accefbaa7a241b4a5e0e2c5b/modules/core/test/test_arithm.cpp#L1311), compared against reference version from `ts` module: [here](https://github.com/opencv/opencv/blob/f5793d26b7f362f8accefbaa7a241b4a5e0e2c5b/modules/ts/src/ts_func.cpp#L1134) and below
2. Performance tests: [here](https://github.com/opencv/opencv/blob/f5793d26b7f362f8accefbaa7a241b4a5e0e2c5b/modules/core/perf/perf_norm.cpp#L110) and below
