### ISSUE TITLE
Is it possible to raise cmake_minimum_version in opencv 5.0?

### ISSUE THREAD

**Issue by FantasqueX** [opencv/opencv#25572]
### Describe the feature and motivation

1. Currently, opencv's cmake_minimum_version is 3.5, and uses some deprecated CMake features such as [CMP0148](https://cmake.org/cmake/help/latest/policy/CMP0148.html) and [CMP0146](https://cmake.org/cmake/help/latest/policy/CMP0146.html). If we raise the minimum version, opencv's CMake can be simplified.
2. https://github.com/opencv/opencv/discussions/25039 More than 90% people think opencv 5.0 should use C++17. https://gcc.gnu.org/projects/cxx-status.html#cxx17 Some C++17 features are available since GCC 5, but support was experimental and the ABI of C++17 features was not stable until GCC 9. GCC 9 was released in May 2019, while CMake 3.14 was released in March 2019. If we follow Ubuntu's life cycle, the earliest LTS release in standard support is 20.04 which ships CMake 3.16.

**Comment by FantasqueX** [comment]
Related work: https://github.com/opencv/opencv/pull/25005

**Comment by bebuch** [comment]
Just a note: For the EOL of Ubuntu LTS (and other distros), the version at the planned release date of OpenCV 5 should be considered. Depending on the release plan, it may be Ubuntu 22.04 LTS.

**Comment by Ryanf55** [comment]
Regardless of whether it's CMake 3.16 or 3.22, there is currently conditional logic handling CMake 2 problems still in the code. I recommend removing it to reduce the amount of build system code that must be maintained.

**Comment by FantasqueX** [comment]
https://github.com/opencv/opencv/pull/26287
