### ISSUE TITLE
remap to dst array in python

### ISSUE THREAD

**Issue by Daniel63656** [opencv/opencv#25640]
### Describe the feature and motivation

Right now, remapping only works onto the src array in python. There is a dst parameter, but I think it is to specify the type. This or it doesn't work. I can't map onto a bigger array for example?

**Comment by dkurt** [comment]
`dst` argument is not a type but an output array. So you can pass it explicitly.

> dst  |  Destination image. It has the same size as map1 and the same type as src . 

https://docs.opencv.org/5.x/da/d54/group__imgproc__transform.html#gab75ef31ce5cdfb5c44b6da5f3b908ea4
