### ISSUE TITLE
使用alpha混合时，生成的照片颜色不正确

### ISSUE THREAD

**Issue by wangkd0** [opencv/opencv#25652]
### Describe the feature and motivation

我使用java+opencv尝试将原图、alpha图、底色背景图进行合成，输出白色背景的人脸图，但是生成的照片颜色不正确，下面是我的代码和输出照片：
    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

        // 读取图像
        Mat original = Imgcodecs.imread("D:\\tmp\\result\\aaa\\output1234.png");
        Mat background = Imgcodecs.imread("D:\\tmp\\result\\aaa\\1111.png");
        Mat alpha = Imgcodecs.imread("D:\\tmp\\result\\aaa\\output5678.png");

        // Convert Mat to float data type
        original.convertTo(original, CvType.CV_32FC3);
        background.convertTo(background, CvType.CV_32FC3);

        // Normalize the alpha mask to keep intensity between 0 and 1
        alpha.convertTo(alpha, CvType.CV_32FC3, 1./255);

        // Storage for output image
        Mat ouImage = new Mat();

        // Multiply the foreground with the alpha matte
        Core.multiply(alpha, original, original);

        Imgcodecs.imwrite("D:\\tmp\\result\\aaa\\out1.png", original);

        // Multiply the background with (1 - alpha)
        Mat oneMinusAlpha = new Mat();
        Core.subtract(Mat.ones(alpha.size(), alpha.type()), alpha, oneMinusAlpha);

        Imgcodecs.imwrite("D:\\tmp\\result\\aaa\\out2.png", oneMinusAlpha);

        Core.multiply(oneMinusAlpha, background, background);

        Imgcodecs.imwrite("D:\\tmp\\result\\aaa\\out22.png", background);

        // Add the masked foreground and background
        Core.add(original, background, ouImage);

        Imgcodecs.imwrite("D:\\tmp\\result\\aaa\\out3.png", ouImage);

        // Convert the output image to BGR
        ouImage.convertTo(ouImage, CvType.CV_32FC3);

        // Convert the image to RGBA (Java uses RGBA format)
        cvtColor(ouImage, ouImage, COLOR_BGR2RGB);

        // 显示图像
        Imgcodecs.imwrite("D:\\tmp\\result\\aaa\\out4.jpg", ouImage);
    }

![image](https://github.com/opencv/opencv/assets/59824901/59423655-2468-46ee-b6e3-d02ab7be646b)

**Comment by sturkmen72** [comment]
usage questions should go to https://forum.opencv.org
please close this issue. and post your question (in english) to https://forum.opencv.org
