### ISSUE TITLE
Don't work cv2.imshow on rockchip 3588e 

### ISSUE THREAD

**Issue by ViktorPavlovA** [opencv/opencv#25653]
### System Information

Hello.

```
Python3.10
OpenCV version: 4.8.0
Platform: Ubuntu 22.04
Rockchip 3588
```

So i took this error:

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/techtrans/.local/lib/python3.10/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
I checked standard step's to solved it and it 's not help.

 Thanks for help!

**Comment by opencv-alalek** [comment]
Use proper Qt build or disable Qt.

**Comment by Kumataro** [comment]
Duplicated https://github.com/opencv/opencv-python/issues/729

**Comment by ViktorPavlovA** [comment]
@Kumataro, yes, but the steps in the topic did not work...

**Comment by ViktorPavlovA** [comment]
@opencv-alalek how to understand which build is proper?

**Comment by ViktorPavlovA** [comment]
`export QT_QPA_PLATFORM=xcb` 

Sorry guys my mistake(
