### ISSUE TITLE
3rdparty/ ndsrvp and hal_rvv seeems no lincense files.

### ISSUE THREAD

**Issue by Kumataro** [opencv/opencv#25729]
### Describe the doc issue

( I chose `Documentation` because it doesn't directly affect the actual operation. )

3rd party libraries and headers are stored in https://github.com/opencv/opencv/tree/4.x/3rdparty .

There are many different ways to express license information for 3rd party libraries.

- Standalone LICENSE/COPYING file ( e.g. flatbuffers / libpng / libwebp / ... )
- Including information into source/header file ( e.g. catotene / libjpeg / ...)
- Only CMakefile script to download external packages ( e.g. kleidicv / tim-vc / ... ) 

However `hal_rvv` and `ndsrvp` seems to have no license information. 　They has no LINCESE/COPYING files, and source and header files shows OpenCV license.

- https://github.com/opencv/opencv/tree/4.x/3rdparty/hal_rvv
- https://github.com/opencv/opencv/tree/4.x/3rdparty/ndsrvp

Are these under a different license than OpenCV and do I need to add a license file? Or are they just part of OpenCV and should be managed in a different folder?

### Fix suggestion

If they has different license from OpenCV, it should be show to clear.
If not, they should move to more suitable directories instead of 3rdparty directory.

**Comment by Bruce387** [comment]
I'd be happy to help here!

**Comment by Kumataro** [comment]
Hello, if you think to do working anythig about this issue, please could you wait ?

1. These folders contain only source code and header files under the same license as OpenCV.
2. Only the person who added the files in these folders knows under what license the files are distributed.
3. Until the OpenCV maintainers determine how to fix this issue, we cannot issue a pull request to resolve it.

**Comment by asmorkalov** [comment]
The mentioned pieces are treated as part of OpenCV project, but they are supplementary. The same Apache 2.0 license is used, if other is not defined.

**Comment by Kumataro** [comment]
Storing them into 3rd party folder seems OK, so I'l close this issue.
Thank you very much for your comment ! 

------
Maybe I'm worrying too much that ...

If it is placed under a 3rd party folder, it is not in-natural to assume that there may be a provider other than OpenCV, like other libraries. I think it  is confused a little easily.

**Comment by mshabunin** [comment]
Theoretically these libraries can be built and used independently of OpenCV, so they can be considered standalone projects. The first such library, carotene, has been placed to "3rdparty" and others just followed its example. I believe we can add simple README files stating that OpenCV repository is an origin for these projects and they use the same license. We can also think about relocating them in the source tree, but it seem to be unnecessary in my opinion.
