### ISSUE TITLE
all: http://opencv.org/license.html returns 404 status.

### ISSUE THREAD

**Issue by Kumataro** [opencv/opencv#25730]
### Describe the doc issue

(This issue concerns both the OpenCV source code and the website.)

Usually, we use following header lines to show OpenCV license information.

https://github.com/opencv/opencv/wiki/Coding_Style_Guide#file-structure

```
// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.	
```

This `http://opencv.org/license.html` URL seems to return 404 status. I believe we have to use `https://opencv.org/LICENSE` URL instead of it.

See http://opencv.org/license.html and https://opencv.org/license/

However, a lot of source and header files should be effected this issue.
I think it is better that this problem should be fixed by the maintainers.
( Or redirection from old URL to new URL is helpful to relax it) .

### Fix suggestion

We have some options.

1. Update source and headers to use https://opencv.org/LICENSE URL. 
2. Redirection from old URL to new URL for old code/files, and update documents for new code/files.

**Comment by asmorkalov** [comment]
@philnelson could you handle this on web server? We have the .html url mentioned everywhere and it's easier and safer just add redirect.

**Comment by asmorkalov** [comment]
Seems to be resolved. Thanks to @philnelson

**Comment by Kumataro** [comment]
@philnelson and @asmorkalov 
Thank you very much !!
