### ISSUE TITLE
Bayer2Gray SIMD version and non-SIMD version should be equal

### ISSUE THREAD

**Issue by FantasqueX** [opencv/opencv#25823]
### Describe the feature and motivation

Non-SIMD version https://github.com/opencv/opencv/blob/efa4d9176a16ad30081a184124b25a8029ea788d/modules/imgproc/src/demosaicing.cpp#L659-L662
SIMD version
https://github.com/opencv/opencv/blob/efa4d9176a16ad30081a184124b25a8029ea788d/modules/imgproc/src/demosaicing.cpp#L204

```
(a0 * b0 + a1 * b1 + a2 * b2 + (1 << 15)) >> 16 != ((a0 * b0 * 4 >> 16) + (a1 * b1 * 4 >> 16) + (a2 * b2 * 4 >> 16)) >> 2
```

For a fix, just like other functions which use `CV_DESCALE`.
For example, https://github.com/opencv/opencv/blob/efa4d9176a16ad30081a184124b25a8029ea788d/modules/imgproc/src/color_lab.cpp#L360-L371

**Comment by asmorkalov** [comment]
Thanks a lot for the finding! You are welcome to contribute!
