### ISSUE TITLE
Indentation of tutorial_how_to_scan_images's code snippet is not correct

### ISSUE THREAD

**Issue by FantasqueX** [opencv/opencv#25830]
### Describe the doc issue

https://docs.opencv.org/4.x/db/da5/tutorial_how_to_scan_images.html
![image](https://github.com/opencv/opencv/assets/46747123/9ce94f24-8d0d-4176-92ff-7c72704065fb)

### Fix suggestion

Maybe some bug in doc generation. The indentation of source code is correct.
https://github.com/opencv/opencv/blob/4.x/samples/cpp/tutorial_code/core/how_to_scan_images/how_to_scan_images.cpp#L134-L161

**Comment by opencv-alalek** [comment]
Looks like this problem is similar to #24391
@philnelson Could you please take a look and disable CDN optimizations for docs.opencv.org?

**Comment by asmorkalov** [comment]
Fixed on CDN side.
