### ISSUE TITLE
Math is rendered without newlines

### ISSUE THREAD

**Issue by JStech** [opencv/opencv#25875]
### Describe the doc issue

I ran into this here, https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html. In the second and third equation, newlines in the Doxygen source are not rendered, so they appear like this:
![image](https://github.com/opencv/opencv/assets/519268/b8c5c6e7-3e56-4890-8bd3-da686160f0aa)

The [source](https://github.com/opencv/opencv/blob/4.x/modules/calib3d/include/opencv2/calib3d.hpp#L415) uses `\\` to separate lines.

### Fix suggestion

Render the missing newlines.

**Comment by Kumataro** [comment]
I fixed it now.

https://pullrequest.opencv.org/buildbot/export/pr/25877/docs/db/d58/group__calib3d__fisheye.html
