### ISSUE TITLE
Missing stitcher.py File in High-Level Stitching API Tutorial

### ISSUE THREAD

**Issue by nishanthdass** [opencv/opencv#25962]
### Describe the doc issue

The [High-Level Stitching API Tutorial](https://docs.opencv.org/4.x/d8/d19/tutorial_stitcher.html)([markdown](https://github.com/opencv/opencv/blob/5.x/doc/tutorials/others/stitcher.markdown)) provides directions on the use of Stitcher class. The tutorial includes a C++ example file ([stitching.cpp](https://github.com/opencv/opencv/blob/4.x/samples/cpp/stitching.cpp)) that demonstrates the API's usage along with a download link for the .cpp file. Issue is that there is no Python example provided or referenced in the tutorial, even though a python example exists in the repo ([stitching.py](https://github.com/opencv/opencv/blob/4.x/samples/python/stitching.py)). 

Both stitching.cpp and stitching.py have the same core functionalities which is that they utilize the Stitcher class to stitch images together into a panorama. They create a Stitcher object, set the mode and use the stitch() method for stitching. The C++ script offers more options, such as image division and GPU usage, which are not present in the Python script

Despite the differences including both stitching.cpp and stitching.py in the tutorial would help users understand the API's capabilities in different programming languages.

Issue with ([markdown](https://github.com/opencv/opencv/blob/5.x/doc/tutorials/others/stitcher.markdown)) is present in 4.x and 5.x.

### Fix suggestion

Suggested Addition to Line 27 of [markdown](https://github.com/opencv/opencv/blob/5.x/doc/tutorials/others/stitcher.markdown):

"This tutorial code is shown in the lines below. You can also download it from here for [C++ (stitching.cpp)](https://github.com/opencv/opencv/blob/4.x/samples/cpp/stitching.cpp). A similar script is available for [Python (stitching.py)](https://github.com/opencv/opencv/blob/4.x/samples/python/stitching.py). Note: The C++ version includes additional options such as image division (--d3) and more detailed error handling, which are not present in the Python example."

edit: I am open to making the suggested fixes as a contribution

**Comment by nishanthdass** [comment]
Adding link to tutorial formatting guidelines: https://docs.opencv.org/4.x/d4/db1/tutorial_documentation.html#tutorial_documentation_overview

**Comment by aditya270520** [comment]
Assign this to me

**Comment by nishanthdass** [comment]
I will close this issue once PR is complete, PR is currently awaiting approval. [PR](https://github.com/opencv/opencv/pull/25980)

**Comment by asmorkalov** [comment]
Addressed in https://github.com/opencv/opencv/pull/25980
