### ISSUE TITLE
add specific error code when cvtColor is used on an image with an invalid number of channels

### ISSUE THREAD

**Issue by FlorianPix** [opencv/opencv#25971]
### Describe the feature and motivation

When I (on accident) use cvtColor twice to convert a grayscale image to RGB than at the moment only a generic error code (-2 / cv.Error.StsError) is raised. Could we instead use a more specific error code like e.g. (cv.Error.BadNumChannels/ -15).

**Comment by Kumataro** [comment]
Hello, thank you for your point !

At OpenCV 4.10.0, `cvtColor()` checks source and destination channel number using `CV_Check()` macro.
But `CV_Check()` macro can throw `cv::exception` with only `StsError(-2)` error code, not other error code.

So I propose to introduce `CV_CheckChannels()` macro which rise `cv::excepion` with `BadNumChannels`.
