### ISSUE TITLE
MSVC 1940 version

### ISSUE THREAD

**Issue by Mykhalevych** [opencv/opencv#25995]
### Describe the feature and motivation

On last update of VS 2022 the MSVC is 1940 version. Now OpenCV_RUNTIME is not set.

### Additional context

File OpenCVDetectCXXCompiler.cmake - 179 line

**Comment by Octopus136** [comment]
Hi @Mykhalevych, it looks like this was fixed in f85818b.

https://github.com/opencv/opencv/blob/f85818ba6f9031c450475a7453dee0acce31a881/cmake/OpenCVDetectCXXCompiler.cmake#L177-L182

**Comment by Mykhalevych** [comment]
No, It was fixed for 1935-1939 versions.
Now it should be like:
```
elseif(MSVC_VERSION MATCHES "^194[0-9]$") 
   set(OpenCV_RUNTIME vc17)
```

**Comment by Kumataro** [comment]
Hello, please could you try to show information ?

```diff
    elseif(MSVC_VERSION MATCHES "^192[0-9]$")
      set(OpenCV_RUNTIME vc16)
    elseif(MSVC_VERSION MATCHES "^19[34][0-9]$")
      set(OpenCV_RUNTIME vc17)
    else()
      message(WARNING "OpenCV does not recognize MSVC_VERSION \"${MSVC_VERSION}\". Cannot set OpenCV_RUNTIME")
    endif()
+   message(STATUS "OpenCV recognize MSVC_VERSION \"${MSVC_VERSION}\" and OpenCV_RUNTIME is \"${OpenCV_RUNTIME}\".") 
  elseif(MINGW)
    set(OpenCV_RUNTIME mingw)
```

My result is here, it works well.

```plaintext
1> [CMake] -- Detected processor: AMD64
1> [CMake] -- OpenCV recognize MSVC_VERSION "1940" and OpenCV_RUNTIME is "vc17".
```

**Comment by Mykhalevych** [comment]
I used OpenCV 4.9.0 - the are is now this fix. Now I switched to 4.10.0 and all works.
Thank you.
