### ISSUE TITLE
basic operation python tutorial still mentions itemset

### ISSUE THREAD

**Issue by knmcguire** [opencv/opencv#26035]
### Describe the doc issue

[The documentation on basic image operations](https://docs.opencv.org/4.10.0/d3/df2/tutorial_py_basic_ops.html) still mentions that we can set a pixel value with numpy's itemset since that is faster than accessing it through the index

https://github.com/opencv/opencv/blob/78630ddc678c7213ef84aa5a12650d3f22c06590/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown?plain=1#L66

This results in the following error:
```
Traceback (most recent call last):
  File ".../opencv_ws/scripts/basic_image_operations.py", line 18, in <module>
    img.itemset((10,10,2),100)
    ^^^^^^^^^^^
AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.
```

### Fix suggestion

We can remove those instructions. Also in numpy's migration guide from 1 to version 2.0 they also advise the same as the error message said: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ndarray-and-scalar-methods

The only thing is is that I can't find if they have solved the issue of the direct setting method being slower.

Another solution that we can do instead is we can also consider fixing the numpy version in install_requirements to install the latest of numpy 1 and not 2, as now it will just install the latest.

https://github.com/opencv/opencv/blob/78630ddc678c7213ef84aa5a12650d3f22c06590/modules/python/package/setup.py#L47

**Comment by Kumataro** [comment]
> The only thing is is that I can't find if they have solved the issue of the direct setting method being slower.

It has been (conditionally) resolved.

Performance test and result in numpy community is here. ( https://github.com/numpy/numpy/pull/24682#issuecomment-1722556662 )

I tried it with numpy 1 and numpy 2 with IPython and opencv-python 4.10 from pip.
Currently it seems that we don't have some reason to use itemset continuously.
(But my test is on very old PC, i7 4790 with Virtual machine.)

I suggest to remove "Note" and "Better pixel accessing and editing method :" section.

```python
In [1]: import numpy as np
In [2]: import cv2 as cv
In [3]: print( np.__version__)
1.26.4
In [4]: print(cv.__version__)
4.10.0
In [5]: img = cv.imread( "opencv.jpg" )

In [6]: %timeit img.itemset(0, 0)
158 ns ± 1.57 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [7]: %timeit img.itemset((0,0,0), 0)
136 ns ± 0.663 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [8]: %timeit img[0] = 0
470 ns ± 6.88 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [9]: %timeit img[0,0] = 0
340 ns ± 8.34 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [10]: %timeit img[0,0,0] = 0
99 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

---------------------------------------------------------------------------
In [1]: import numpy as np
In [2]: import cv2 as cv
In [3]: print(np.__version__)
2.0.1
In [4]: print(cv.__version__)
4.10.0
In [5]: img = cv.imread( "opencv.jpg" )

In [6]:  %timeit img[0] = 0
437 ns ± 3.41 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [7]: %timeit img[0,0] = 0
343 ns ± 3.43 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [8]: %timeit img[0,0,0] = 0
103 ns ± 1.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

**Comment by knmcguire** [comment]
Thanks for double checking this!

hmm it actually seems that time to access a single pixel with the double brackets seems to even gotten longer, so I'm not sure if it actually has improved or not... but I guess we don't really have a reason anymore to suggest itemset at all now if there is a deprecation warning and it has been completely removed for 2 anyway. If people would like to have faster access on such a low level perhaps it's better to use the opencv source of c++ directly.

Once I have time I'll make a PR which will remove this part then:

https://github.com/opencv/opencv/blob/78630ddc678c7213ef84aa5a12650d3f22c06590/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown?plain=1#L49-L69

**Comment by knmcguire** [comment]
or we could still leave a warning about the principle of numpy such that people are at least aware of this limitation:

 _Numpy is an optimized library for fast array calculations. So simply accessing each and every pixel 
 value and modifying it will be very slow and it is discouraged._

**Comment by Kumataro** [comment]
>or we could still leave a warning about the principle of numpy such that people are at least aware of this limitation:

 Yes, I believe keeping this limitation and removing following area are better.

https://github.com/opencv/opencv/blob/78630ddc678c7213ef84aa5a12650d3f22c06590/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown?plain=1#L54-L70

And Numpy community thinks that (this is quoted from https://github.com/numpy/numpy/pull/24682#issuecomment-1722556662 ). So I think we can remove that.

> So the normal indexing is even faster than a direct itemset, even though the documentation for itemset claims "Compared to indexing syntax, itemset provides some speed increase ..." (in older versions of numpy/python this was true). The only exception is for indexing a 2D array with a single index. But that case might be rare.

**Comment by knmcguire** [comment]
Great, I'll do that then.

thanks for your help! I've made a doc PR here: https://github.com/opencv/opencv/pull/26041
