### ISSUE TITLE
"How to contribute to OpenCV" is out of date.

### ISSUE THREAD

**Issue by Kumataro** [opencv/opencv#26040]
### Describe the doc issue

(This is about wiki, so I'm sorry if there is more appropriate bug tracker).

I believe OpenCV 2.4 and 3.4 branches have been finished to maintain. 

However https://github.com/opencv/opencv/wiki/How_to_contribute shows 2.4 and 3.4 branches are alive. And there are no description about 4.x and 5.x branches.

At this time, we are unable to clearly state that OpenCV 2.4 or 3 are unsupported versions when bugs are reported.

Please could you confirm and fix it ?

### Fix suggestion

https://github.com/opencv/opencv/wiki/How_to_contribute

[Before]

> If you are going to fix a bug, check that it still exists. This can be done by building the latest [2.4](https://github.com/opencv/opencv/tree/2.4)/[3.4](https://github.com/opencv/opencv/tree/3.4) branch or the [latest master branch](https://github.com/opencv/opencv), and make sure that the error is still reproducible there. We do not fix bugs that only affect deprecated versions like OpenCV 2.1 for example.

[After]

> If you are going to fix a bug, check that it still exists. This can be done by building the latest [4.x](https://github.com/opencv/opencv/tree/4.x)/[5.x](https://github.com/opencv/opencv/tree/5.x) branch or the [latest master branch](https://github.com/opencv/opencv), and make sure that the error is still reproducible there. We do not fix bugs that only affect deprecated versions like OpenCV 2.x/3.x for example.

And I suggest to add following note.

> Please note that issues found in older versions may already be resolved in the latest version.

**Comment by Kaustbh** [comment]
Can I make a PR?

**Comment by Kaustbh** [comment]
Hi, can I make a PR?

**Comment by abhijeetsharma200** [comment]
Hi @Kumataro,

I made my changes in this [github repo](https://github.com/abhijeetsharma200/OpenCV-Wiki/tree/docs_update_how_to_contribute) following [this answer](https://stackoverflow.com/a/11481887) from stackoverflow given I cannot create PR for a wiki. Please let me know if this works or if you have a different approach to contributing to wiki.

**Comment by Kumataro** [comment]
I'm sorry I am one of contributors, not maintainer. So it is difficult for me what you hope ..

**Comment by abhijeetsharma200** [comment]
@fengyuentau are you the person to get in touch with regarding this issue?

**Comment by fengyuentau** [comment]
@abhijeetsharma200 It seems the pages under wiki can only be modified by organization members. You can ask GitHub for help.

**Comment by opencv-alalek** [comment]
BTW, there is the right page for describing of OpenCV branching strategy: https://github.com/opencv/opencv/wiki/Branches

**Comment by opencv-alalek** [comment]
> I made my changes in this [github repo](https://github.com/abhijeetsharma200/OpenCV-Wiki/tree/docs_update_how_to_contribute) following [this answer](https://stackoverflow.com/a/11481887) from stackoverflow given I cannot create PR for a wiki. Please let me know if this works or if you have a different approach to contributing to wiki.

Changes are pushed to Wiki page:

https://github.com/opencv/opencv/wiki/How_to_contribute

---

> latest master branch

We deprecate "master" branch to avoid dead links during changes in major versions.
Public links should go to related releases branch: 3.4 / 4.x / 5.x / etc (instead of master)
