### ISSUE TITLE
Unable to compile opencv on Ubuntu18.04

### ISSUE THREAD

**Issue by to-vanish** [opencv/opencv#26104]
### Describe the doc issue

I am using RK3568 board, and I simply download the opencv source code 4.10.0. Then `mkdir build -p && cd build && cmake ../`
 and `make -j8` without any other options. Below are the compiling message, there are no errors report. It is just waiting at `[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_test_gapi.dir/test/common/gapi_imgproc_tests.cpp.o` for like an hour. And the whole system seems to lagging a lot. (storage on my board is enough). I have tried 2 times, same result, still stuck here.

[ 83%] Built target opencv_perf_video
[ 84%] Built target opencv_test_video
[ 93%] Built target opencv_gapi
[ 93%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2_highgui.cpp.o
[ 93%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
[ 93%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2_util.cpp.o
[ 93%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2_convert.cpp.o
[ 93%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2_numpy.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_perf_gapi.dir/perf/common/gapi_imgproc_perf_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_perf_gapi.dir/perf/common/gapi_core_perf_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_test_gapi.dir/test/common/gapi_compoundkernel_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_perf_gapi.dir/perf/common/gapi_render_perf_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_perf_gapi.dir/perf/common/gapi_video_perf_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_test_gapi.dir/test/common/gapi_core_tests.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_test_gapi.dir/test/common/gapi_imgproc_tests.cpp.o

**Comment by kfwu1999** [comment]
Have you tried reducing the number of parallel jobs by using `make -j4` or even `make -j2`?

**Comment by to-vanish** [comment]
> Have you tried reducing the number of parallel jobs by using `make -j4` or even `make -j2`?

Oh it did work. A bit slower but works.
