### ISSUE TITLE
increase the stack size of MatSize and MatStep

### ISSUE THREAD

**Issue by Ginkgo-Biloba** [opencv/opencv#26137]
### Describe the feature and motivation

Nowadays more and more mats (tensors) have dims larger than 2. The stack buffer size can be used in Mat is 2, i.e.
- `MatSize` : `int rows` `int cols`
- `MatStep` : `size_t buf[2]`

https://github.com/opencv/opencv/blob/fcfdd311ab7ad32ebb08dcde65c3adf2ea2ce099/modules/core/include/opencv2/core/mat.hpp#L587-L614

Thus if we want to create 4-dim mats (like NCHW), we have to malloc 4 `int` for `MatSize` and 4 `size_t` for `MatStep` on heap (maybe more due to memory alignment). And they belongs to `Mat`, no refcount based strategy can be used to reduce the memory overhead.

Maybe 5 is a proper choice, like PyTorch does.
``` cpp
#define C10_SIZES_AND_STRIDES_MAX_INLINE_SIZE 5

  size_t size_{1};
  union {
    int64_t* outOfLineStorage_;
    // NOLINTNEXTLINE(*c-array*)
    int64_t inlineStorage_[C10_SIZES_AND_STRIDES_MAX_INLINE_SIZE * 2]{};
  };
```

> https://github.com/pytorch/pytorch/blob/f65a564fa2477eee0cc77e89951d30be19aca42a/c10/core/impl/SizesAndStrides.h#L307-L312

What we need to do maybe adding 3 `int` in `MatSize` (change its location just after `cols` and delete/union `int* p`) and 3 `size_t` in `MatStep::buf` (`size_t buf[5]`, delete / union `size_t* p`), thus increase `sizeof(Mat)` 3×4+3×8-8-8+4=24 bytes (last 4 is the possible memory layout padding). And some more detailed checks...

Is this feature appropriate? If yes, should it be based 4.x or 5.x?

**Comment by vpisarev** [comment]
@Ginkgo-Biloba, there is a plan for OpenCV 5.0 to replace dynamically allocated MatSize with static MatShape (which supports dimensionalities up to MatShape::MAX_DIMS, currently set to 10).

MatShape is being added in #26056, but does not modify Mat/UMat representation yet. Similarly to that, MatStep will be replaced with a static array embedded into Mat/UMat.

**Comment by Ginkgo-Biloba** [comment]
@vpisarev It is a big project! And will need many works to do.

Firstly I want delete the `*p` in `MatSize` and `MatStep`, union them with stack array, but find that so many code use it `*p`, and I have to give up.

I just add 3 `int` to `Mat` and 3 `size_t` to `MatStep`, and `sizeof(Mat)` grows from 96 bytes to 136 bytes, including 4 bytes memory layout padding between `int _padding_for_size[]` and `uchar* data`. Fortunately, only `Mat` and `UMat` use `MatStep` and `MatSize`, so there are only few changes.
https://github.com/Ginkgo-Biloba/opencv/commit/5a354abe4d285a7f5b4da22edf98ff9e11cd226d

I don't sure whether it is useful or not. May I make a PR to see community feedback?

**Comment by vpisarev** [comment]
@Ginkgo-Biloba, well, depending on how much time do you have and if you agree that this code will likely be dropped when MatSize will be replaced with MatShape and MatStep will get a bigger buffer of MatShape::MAX_DIMS elements for steps. Of course, sizeof(Mat) will then become significantly larger, ~200 bytes.

**Comment by Ginkgo-Biloba** [comment]
Close it because https://github.com/opencv/opencv/pull/26056 is done.
