### ISSUE TITLE
Python type stubs/`.pyi` files for CMake install

### ISSUE THREAD

**Issue by carschandler** [opencv/opencv#26149]
### Describe the feature and motivation

To give context, the reason I'm opening this is because conda installations of opencv from `conda-forge` do not have proper LSP support because none of the type stub files get copied during install. This is because [the `setup.py` file](https://github.com/opencv/opencv-python/blob/6a181cedae5f23e332ae87d2e90d36635932855e/setup.py#L420-L429) handles this for pip installs, but this doesn't exist for `conda` since it builds directly from CMake and does not call `setup.py`.

With that being said, the opencv team may prefer that `conda-forge` handle this in their own build script, but it would be an awesome feature in my opinion if this could be achieved at the CMake level so that `setup.py` doesn't have to worry about it and all installation methods are unified in their approach here.

### Additional context

See my issue at https://github.com/conda-forge/opencv-feedstock/issues/374

**Comment by asmorkalov** [comment]
The statement is not correct, actually. Type stubs generation is supported for Python 3.6+ and installed with cmake automatically. Example for Ubuntu 24.04:
```
cmake -DCMAKE_INSTALL_PREFIX=./install ../opencv
make -j16 && make install
```
Content of `opencv-build/install/lib/python3.10/dist-packages/cv2`:
```
aruco    config-3.10.py  cuda    dnn    fisheye  gapi         __init__.pyi  load_config_py2.py  mat_wrapper  ml   ogl       python-3.10  samples       typing  videoio_registry
barcode  config.py       detail  Error  flann    __init__.py  ipp           load_config_py3.py  misc         ocl  parallel  py.typed     segmentation  utils
```

**Comment by asmorkalov** [comment]
Just ensure that you use modern Python for bindings generation and for scripting inside of OpenCV:
```
"\n"
"  Python 3:\n"
"    Interpreter:                 /usr/bin/python3 (ver 3.10.12)\n"
"    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.10.so (ver 3.10.12)\n"
"    Limited API:                 NO\n"
"    numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.21.5)\n"
"    install path:                lib/python3.10/dist-packages/cv2/python-3.10\n"
"\n"
"  Python (for build):            /usr/bin/python3\n"
```
