### ISSUE TITLE
Template Matching CCOEFF

### ISSUE THREAD

**Issue by EugeoSynthesisThirtyTwo** [opencv/opencv#26223]
### Describe the doc issue

https://docs.opencv.org/4.x/df/dfb/group__imgproc__object.html

Sorry if my english is not perfect. I will try my best.

I don't understand the details of CCOEFF.
I suppose that for `T'`, we subtract the average of `T` in each cell of `T`, so for each cell of `T` we subtract the exact same constant value. And I guess that `w` and `h` are the width and height of T, since it's written below on the page.

But what about `I'`? Is this the exact same computation? Do we subtract the average value of the entire image from each cell of `I`? (Do we subtract the same exact constant value for each cell of `I`?) I suppose that it's not the case since `w` and `h` are used here too instead of `W` and `H`. But if we subtract the average LOCAL value instead, where `w` and `h` are the dimensions of the KERNEL (not the IMAGE), then shouldn't `I'` have a smaller size than `I` like in every convolution?

Thank you for taking time to read my bad english.

**Comment by s-trinh** [comment]
Sizes of `I'` and `T'` are equal.
Size of `R` is equal to `ccoeff_map = np.zeros((img.shape[0]-tpl.shape[0], img.shape[1]-tpl.shape[1]))`

---

A rough implementation should give something like this:

```py
#! python3
# -*- coding: utf-8 -*-
import numpy as np
import cv2 as cv

def mean_sub(img):
    norm = 1.0 / (img.shape[0] * img.shape[1])
    img_mean_sub = img - norm*np.sum(img)

    return img_mean_sub

def ccoeff(img, tpl):
    ccoeff_map = np.zeros((img.shape[0]-tpl.shape[0], img.shape[1]-tpl.shape[1]))
    for i in range(0, img.shape[0]-tpl.shape[0]):
        for j in range(0, img.shape[1]-tpl.shape[1]):
            sub_img = img[i:i+tpl.shape[0], j:j+tpl.shape[1]]
            sub_img_mean_sub = mean_sub(sub_img)
            tpl_mean_sub = mean_sub(tpl)
            ccoeff_map[i,j] = np.sum(sub_img_mean_sub*tpl_mean_sub)

    return ccoeff_map

def main():
    # print(cv.getBuildInformation())
    img = cv.imread("coins.png", cv.IMREAD_UNCHANGED)
    print(f"img: {img.shape}")

    coin = img[170:220, 75:130]
    ccoeff_map = ccoeff(img, coin)
    minVal, maxVal, minLoc, maxLoc = cv.minMaxLoc(ccoeff_map)
    print(f"minVal={minVal} ; maxVal={maxVal} ; minLoc={minLoc} ; maxLoc={maxLoc}")

    ccoeff_map_8u = cv.convertScaleAbs(ccoeff_map, alpha=(255 / (maxVal-minVal)), beta=(-(255*minVal) / (maxVal-minVal)))
    ccoeff_map_color = cv.applyColorMap(ccoeff_map_8u, cv.COLORMAP_TURBO)

    img_color = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
    top_left = maxLoc
    bottom_right = (top_left[0] + coin.shape[1], top_left[1] + coin.shape[0])
    cv.rectangle(img_color, top_left, bottom_right, color=(0,0,255), thickness=2)

    cv.imshow("coin", coin)
    cv.imshow("img", img_color)
    cv.imshow("ccoeff_map_color", ccoeff_map_color)

    cv.waitKey(0)

if __name__ == '__main__':
    main()
```

---

- input image (https://github.com/scikit-image/scikit-image/blob/main/skimage/data/coins.png):

![image](https://github.com/user-attachments/assets/668091c5-8bc1-4677-8ddb-40a6809ce1ce)

- template:

![coin](https://github.com/user-attachments/assets/1cff8314-ce29-40fb-920a-76cc9dbc4a43)

- result:

![img_color](https://github.com/user-attachments/assets/b91a89ba-c4b8-49fc-aa3b-6040ff70f654)

- cross-coefficient map:

![ccoeff_map_color](https://github.com/user-attachments/assets/e9cb1a70-df35-4bd9-b375-a8f1fce3cac3)

**Comment by EugeoSynthesisThirtyTwo** [comment]
@s-trinh Thank you very much ! By the way, in your convolution there are three channels (r, g, b), I just want to confirm that the real implementation, even with an input image of 3 channels, only produces one channel in the result ?

**Comment by s-trinh** [comment]
I think so, but probably you should look at Deep Learning topics directly:
- https://www.d2l.ai/chapter_convolutional-neural-networks/channels.html
- https://pytorch.org/docs/main/generated/torch.nn.Conv2d.html#torch.nn.Conv2d
- https://cs231n.github.io/convolutional-networks/#conv
