### ISSUE TITLE
null pointer dereference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [opencv/opencv#26655]
Hi all,
This is Qianxin CodeSafe Team, we found a suspicious issue,
The stream pointer "f" may be empty at
https://github.com/opencv/opencv/blob/09030615891c177d322c5a8bbcd58bc1e1384173/modules/imgcodecs/perf/perf_jpeg.cpp#L17
Therefore,this results in a null point dereference at
https://github.com/opencv/opencv/blob/09030615891c177d322c5a8bbcd58bc1e1384173/modules/imgcodecs/perf/perf_jpeg.cpp#L18

**Comment by Kumataro** [comment]
I think this is false-positive..

https://github.com/opencv/opencv/blob/d9a139f9e85a17b4c47dbca559ed90aef517c279/modules/imgcodecs/perf/perf_jpeg.cpp#L15-L18

`getDataPath()` validates argument file path to read.

https://github.com/opencv/opencv/blob/d9a139f9e85a17b4c47dbca559ed90aef517c279/modules/ts/src/ts_perf.cpp#L1911-L1919

if argument file path  is unavailable(missing file or losting file permission), an exception  is shown following error message and stop program In `getDataPath()` . So after `fopen()` evenif `ASSERT_EQ(f, nullptr)` is added,  it will not be executed and be unreachable code. 

```
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from JPEG
[ RUN      ] JPEG.Decode
/home/kmtr/work/opencv4/modules/ts/src/ts_perf.cpp:1916: Failure
Failed
  Requested file "/home/kmtr/work/opencv_extra4/testdata/stitching/boat1.jpg" does not exist.
termination reason:  aborted by the performance testing framework
bytesIn   =          0
bytesOut  =          0
samples   =          0 of 100
outliers  =          0
frequency =          0
[  FAILED  ] JPEG.Decode (0 ms)
```

**Comment by Kumataro** [comment]
However, if we are to be extremely strict, there is a non-zero possibility that the file will not be accessible during the very small time slice between calling getDataPath() and calling fopen().

Since the purpose of this program is to verify performance, in my opinion this level of strictness is not necessary.
