### ISSUE TITLE
Add InputArray and OutputArray overloads for std::array

### ISSUE THREAD

**Issue by rggjan** [opencv/opencv#5086]
Currently, there are overloads for InputArray and OutputArray that take an std::vector:

```
template<typename _Tp> _InputOutputArray(std::vector<Mat_<_Tp> >& vec);
```

It would be great to also have overloads that take an std::array, to make the following code work:

```
cv::Mat image;
std::vector<cv::Mat> output(3, cv::Mat());
cv::split(image, output); // This works

std::array<cv::Mat, 3> output_array;
cv::split(image, output_array); // This currently doesn't work yet
```

**Comment by ilya-lavrenov** [comment]
Agree with alalek's pose there https://github.com/opencv/opencv/pull/6010. Closing.

**Comment by alalek** [comment]
My comment is about PR proposal. This feature request is fine.
