### ISSUE TITLE
OpenCV wiki

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#5113]
@mshabunin 

I remember you telling us that the wiki pages would be editable for everyone. However when I try to push changes to https://github.com/Itseez/opencv.wiki.git it says that my user has no access. Anything that can be done about that.

What I would like to do
--> translate existing tutorials to C++
--> maybe add some more of them there later

**Comment by mshabunin** [comment]
GitHub still have no convenient way to contribute to wiki and it seems that documentation is sufficient enough for most of our users. I'm closing this issue for now.

Any changes to the wiki can be proposed via regular tickets and large articles should go to the documentation.
