### ISSUE TITLE
OpenCV Truck Factor

### ISSUE THREAD

**Issue by gavelino** [opencv/opencv#5139]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **OpenCV** and obtained a value of **2**.

The developers responsible for this TF are:

Andrey Pavlenko - author of 55% of the files
Vladislav Vinogradov - author of 28% of the files

To validate our results, we would like to ask **OpenCV** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **OpenCV**?

(b) Do you agree that **OpenCV** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **OpenCV** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by StevenPuttemans** [comment]
I think you might confuse author by the fact that Github calls the one who "authored" the PR, the author. OpenCV works with a workflow where code is added by the community, and of course closed team developers, but it is only the core team that can accept the merge of new code. Therefore this term is very misleading I think :)

**Comment by gavelino** [comment]
Hi @StevenPuttemans,

that is not the case. We define an author as a developer able to influence or command the implementation of a file. We calculated them as explain in https://peerj.com/preprints/1233.
We use author information of the commit, but just to give credit for the developer who submit the code instead who merged.
