### ISSUE TITLE
StatModel no  have method load in Java

### ISSUE THREAD

**Issue by schvepe** [opencv/opencv#5153]
The Class StatModel no have method load in Java.

**Comment by Daniel-Alievsky** [comment]
I have the same problem. Is there any workaround - how can I load in Java the trained model, for example, SVM?

**Comment by asashour** [comment]
I understand that there is no `load` method in [StatModel](https://docs.opencv.org/3.4.6/db/d7d/classcv_1_1ml_1_1StatModel.html), and accordingly there is no corresponding one in Java.

For sub-classes, there is a static method, e.g.:

    SVM svm = SVM.load(filepath);

**Comment by berak** [comment]
imho we can close this, as of now (4.2/3.4), all java (and python) ml classes have proper static load functions.
