### ISSUE TITLE
Dynamic memory overrun in UMat download/upload methods for non contiguous umat

### ISSUE THREAD

**Issue by SergeySivolgin** [opencv/opencv#5172]
The issue has been detected in tests UMat/UMatBasicTests.copyTo for the specific case:

if (useRoi)
 {
 UMat roi_ua;
 Mat roi_a;
 roi_ua = UMat(ua, roi);
 roi_a = Mat(a, roi);
 roi_ua.copyTo(roi_a); - there, at OpenCLAllocator.download memory overrun happens when AlignedDataPtr is destructed and back copy from temporary aligned memory buffer to matrix memory  happens. The root cause is that AlignedDataPtr keeps contiguous memory buffer and uses wrong size of copied amount of data copying to non contiguous memory.
The issue has been detected and reported by debug CRT in Visual Studio in debug build.

**Comment by SergeySivolgin** [comment]
There are two issues here.
One issue should be fixed by PR 5164:
https://github.com/Itseez/opencv/pull/5164
Another issue is related to Intel OpenCL driver:
https://software.intel.com/en-us/forums/topic/567674

**Comment by alalek** [comment]
Fixed by this commit: https://github.com/opencv/opencv/commit/68f8d1cef0567e6564136d3657cb335389260aab (OpenCV 3.1.0+)
