### ISSUE TITLE
videostab: crashes when radius > number of input frames

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#5178]
If the sliding window radius is higher than the number of available frames, the program crashes at [motion_stabilizing.cpp#L114](https://github.com/Itseez/opencv/blob/09b9b0fb9e9c9dd8c9e0d65705f8f19aa4c27f8a/modules/videostab/src/motion_stabilizing.cpp#L114), unable to add the two matrices, since `OpenCV Error: Sizes of input arguments do not match`, i.e. `res` is 0x0 and the other matrix is 3x3

**Steps to reproduce**:
Run the [videostab example](https://github.com/Itseez/opencv/blob/09b9b0fb9e9c9dd8c9e0d65705f8f19aa4c27f8a/samples/cpp/videostab.cpp#L509-L514) with the following options and test.avi only having a couple of frames

> videostab test.avi --radius=400 --est-trim=no

**Expected behavior**
The parameter should state the "maximum sliding window width", e.g. when the number of available frames is lower, take all frames (and not more).
Plus, I'm wondering why it only crashes at `radius > number of frames` and not already at `radius*2 > number of frames` since I would expect the _radius_ to be half of the window width.

**Comment by PhilLab** [comment]
Performing the check from the outside (e.g. radius = min(radius, frame count ) is not possible in a reliable way, since
a) for a stream of frames we don't know how many will come
b) for a video file the given frame count is only a rough estimate.

**Comment by PhilLab** [comment]
This seems related to the cache size: [stabilizer.cpp#L272-L276](https://github.com/Itseez/opencv/blob/b46719b0931b256ab68d5f833b8fadd83737ddd1/modules/videostab/src/stabilizer.cpp#L272-L276)

**Comment by Chandnani** [comment]
i believe the error arises due to line 78 in motion_stabilizing.cpp where it should be:
for (int i = std::max(index - radius_, 0); i <= std::min(index + radius_;,size-1) ++i) 
instead of : 
for (int i = std::max(index - radius_, 0); i <= index + radius_; ++i) 
where size is size of array of motions matrix passed in function as argument

**Comment by GArik** [comment]
Should be fixed by https://github.com/opencv/opencv_contrib/pull/2424
Please test.
