### ISSUE TITLE
BriefDescriptorExtractor

### ISSUE THREAD

**Issue by alisher1722** [opencv/opencv#5182]
I am using and doing some experiments on feature extractors, such as ORB, BRIEF, etc..
I am using mexopencv to use these extractors directly; but I want to change the existing BriefDescriptorExtractor(brief.cpp) as my own function (for example, "myBrief") in order to make brief function more generic, like KERNEL_SIZE=3,5,9,(whatever I want) AND PATCH_SIZE=48,32,16(whatever I want).

I am able to create such function, and how I can mex it? 

Thank you, for replies,

**Comment by StevenPuttemans** [comment]
You would get more response at https://answers.opencv.org/questions/ ... that being said, I think it would be better to edit the source code of OpenCV, make an overload function that accepts these extra parameters, provide a patch and then mex wrappers should generate the overloaded function also in my understanding.
