### ISSUE TITLE
3.0 java calib3d wrappers call fisheye functions

### ISSUE THREAD

**Issue by berak** [opencv/opencv#5189]
projectPoints, distortPoints, undistortPoints, initUndistortRectifyMap, undistortImage, estimateNewCameraMatrixForUndistortRectify, calibrate, stereoRectify, stereoCalibrate all call c++ functions from the fisheye namespace, while the pinhole model should be used.

example wrapper (from build/modules/java/calib3d.cpp): https://gist.github.com/berak/f5c0662b7538fee67f87

this leads to weird errors: http://answers.opencv.org/question/68575/initundistortrectifymap-assert-error/

**Comment by berak** [comment]
problem is still present in current 3.4

**Comment by alalek** [comment]
I agree that nested namespace should be supported in bindings (but currently can't be done universally without breaking of existed code due `cv::ml` / `cv::dnn` namespaces).

Problem investigation is not very accurate:
- `projectPoints()` - different signatures. No conflict.
- `distortPoints()` - fisheye only
- "normal" `undistortPoints()` is **imgproc** function
- "normal" `initUndistortRectifyMap()` is **imgproc** function
- `undistortImage()` -> fisheye only
- `estimateNewCameraMatrixForUndistortRectify` - fisheye only
- `calibrate()` - fisheye only. "normal" has names: `calibrateCamera()` / `calibrateCameraExtended()`
- `stereoRectify()` - different signatures. No conflict.
- `stereoCalibrate()` - different signatures. No conflict.

Currently there are no conflicts observed. But current code is very confusing and should be fixed.
