### ISSUE TITLE
Is it possible to use LMSolver  ? I f no can I change module source code of opencv_calib3d?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#5206]
In this post (http://answers.opencv.org/question/66169/how-can-i-use-lmsolver-to-solve-a-non-linear-system/) I try to use LMsolver to solve a non-linear system using Levenberg-Marquardt method. I don't find how to do and there is no answer. Withou any answer I think that's not possible to use it.

I have found my own answer in making a copy of class LMSolver in my own code and call method createLMSolver and then it works.

I propose then to change some file in module opencv_calib3d  to have a direct access to this class and to insert a small example how to use this class.

Module calib3d is not at all my module ((some authors are @CheeseWiz @taka-no-me @Dmitry-Me @Adil-Ibragimov @ilya-lavrenovilya-lavrenov @SpecLad) so I prefer asking if this job is usefull and if I can do it before starting work.

Waiting for your answer

Regards L. Berger

**Comment by PhilLab** [comment]
@mshabunin: the label "question" does not fit this issue well. It is indeed phrased like a question but it is more a feature request or a "request permission to implement"
@LaurentBerger to discuss the change efficiently, you could **a)** Rephrase this issue's title and text to not get it mistaken as question (and therefore largely ignored) **and b)** shortly summarize your idea **and c)** trying to identify the author of the module and notify them by mentioning their Github user name

**Comment by LaurentBerger** [comment]
@PhilLab As my english is not good at all I understand yours remarks. I have append some module's authors. About title I think that it is not too bad because may be someone know how to use LMSolver without changing source code. I have tried to improve it.

**Comment by paroj** [comment]
it is probably not yet exported it lacks the possibility to fix parameters when compared to `CvLevMarq` - you could use the latter in the meantime though..
