### ISSUE TITLE
Logistic regression needs to moved to "nonfree"

### ISSUE THREAD

**Issue by jbausano** [opencv/opencv#5219]
There are three files in question, 
1.     \sources\samples\cpp\logistic_regression.cpp
2.     sources\modules\ml\test\test_lr.cpp
3.     sources\modules\ml\src\lr.cpp

At the top of those files there is an "extra" license (snippet below).  I've had to try to explain on two different instances that the logistic regression functions are free to use for commercial use.  But the language reads so poorly, that two different "risk reduction lawyers" at two different companies have questioned the language.  The second company is forcing me to remove the logistic regression routines and rebuild.

Therefore, either the "extra" license needs to be removed, or logistic regression needs to move to "nonfree".

Thank you,  John

// This is a implementation of the Logistic Regression algorithm in C++ in OpenCV.

// AUTHOR:
// Rahul Kavi rahulkavi[at]live[at]com
//

// contains a subset of data from the popular Iris Dataset (taken from
// "http://archive.ics.uci.edu/ml/datasets/Iris")

// # You are free to use, change, or redistribute the code in any way you wish for non-commercial purposes, but please maintain the name of the original author. This code comes with no warranty of any kind.

**Comment by jbausano** [comment]
I contacted Dr. Kavi, the contributor of the logistic regression routines.  I'm pasting his response email below...

"""
Hello John,

I'm glad you are finding the code useful.

The source code that I contributed was back in 2013. It got accepted into the repo in 2014. I used the same license as the other programs in the "ml" Machine Learning module (just added that I wrote the original code). From what I can recollect, I was asked to use the same license as others in the ml module (hence, I used that license).

The IRIS dataset included is a popular toy dataset that researchers use for academic purposes. I added a small/modified version of it to the repo. I don't think there are any restrictions on it (other popular Machine Learning toolkits like sklearn for Python come with IRIS dataset along with framework).

OpenCV comes with BSD license, therefore all the source code (except for non-free module) can be used commercially (I assume). This contribution was not included in the non-free module (as it was a popular and well established algorithm and commonly used by many researchers) and I don't intend to make it non-free. 

Personally I don't have a problem if you want to use it commercially as long as you include the license information as it is.

Regards,
Rahul Kavi.
"""

**Comment by mshabunin** [comment]
@jbausano, can you provide a pull request with the proposed change?

**Comment by PhilLab** [comment]
Rahul Kavi's statements
>  don't have a problem if you want to use it commercially 

and 

> as long as you include the license information as it is.

collide with each other.
@jbausano instead of moving it to contrib, could you ask the author if it was ok to change the license to BSD and add his copyright information to the list of copyright holders (as it is done with many other contributions). As the author clearly states

> OpenCV comes with BSD license, therefore all the source code (except for non-free module) can be used commercially

he himself sees the code as being under BSD license. So it is just a wrong license text, not a wrong license

**Comment by RonWP** [comment]
Our legal counsel is advising that with as-is code, the OpenCV library should not be used commercially.  While the OpenCV organization maintains code is distributed according to https://opencv.org/license/ users of the code are subject to this license and any/all other restrictions.  In this case the restriction is no commercial use.  So, as long as this code asserts no commercial use, it should not be part of the main distribution.

**Comment by RonWP** [comment]
While the OpenCV organization maintains code is distributed according to https://opencv.org/license/ users of the code are subject to this license and perhaps any other restrictions. In this case the additional restriction "no commercial use" is asserted. As long as this code continues to assert no commercial use, it should not be part of the main distribution since this conflicts with https://opencv.org/license/

**Comment by alalek** [comment]
resolved by #19741 (+related conversation in the original PR: #1227)
