### ISSUE TITLE
Reading videos on Android (ffmpeg4android)

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#5236]
Support for reading videos in Android via the VideoCapture class.

One option would be to use [FFmpeg for Android](https://trac.ffmpeg.org/wiki/CompilationGuide/Android) and removing the GPL part (namely x264)

**Comment by alalek** [comment]
Recent time ago I had some experiments for OpenCV 2.4.x with GStreamer backend for VideoCapture:
https://github.com/alalek/opencv/blob/android_gstreamer/modules/androidgstreamer/README.md

**Comment by PhilLab** [comment]
@alalek To understand correctly, #13726 allows to link FFMPEG if you have it built yourselfe. But the default OpenCV Android distribution won't contain the ffmpeg build and thus VideoCapture won't read videos?

**Comment by alalek** [comment]
No plans to build Android package with FFmpeg (it is LGPL).
