### ISSUE TITLE
drawContours, strange behavior

### ISSUE THREAD

**Issue by Cylix** [opencv/opencv#5256]
I have a list of contours to draw. Some of these contours intersect themselves.

When I want to draw them with OpenCV, I simply use the `cv::drawContours` function.

However, the behavior is quite strange.

Here is a quote of the official [documentation](http://docs.opencv.org/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#drawcontours)

```
C++: void drawContours(InputOutputArray image, InputArrayOfArrays contours, int contourIdx, const Scalar& color, int thickness=1, int lineType=8, InputArray hierarchy=noArray(), int maxLevel=INT_MAX, Point offset=Point() )
Parameters: 
contourIdx – Parameter indicating a contour to draw. If it is negative, all the contours are drawn.
```

So, from the documentation, if I want to draw all my areas, filled in black, I just have to do:

```
cv::drawContours(this->mask.raw,
                 this->areas, -1,
                 cv::Scalar(0,0,0),
                 cv::FILLED);
```

However, this gives me the following ouput:

[![enter image description here](http://i.stack.imgur.com/IwYMe.png)](http://i.stack.imgur.com/IwYMe.png)

Here, we can clearly see that all my areas are NOT filled in black.

But if I loop over my areas list and call `cv::drawContours` for each area:

```
unsigned int i = 0;
for (const auto& area : this->areas)
  cv::drawContours(this->mask.raw,
                   this->areas, i++,
                   cv::Scalar(0,0,0),
                   cv::FILLED);
```

I got the good ouput which is quite different from the first one:

[![enter image description here](http://i.stack.imgur.com/6oYV9.png)](http://i.stack.imgur.com/6oYV9.png)

Have I missed something from the documentation? Could someone explain me the behavior of `cv::drawContours` and what is the different of calling it one time for all areas and calling it each time for each area?

**Comment by alalek** [comment]
OpenCV version?

**Comment by Cylix** [comment]
3.0.0-dev (I'm using the master branch).

**Comment by StevenPuttemans** [comment]
Using the latest github repo and the following code

<pre>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main( int argc, char* argv[] )
{
    // Load in test image
    Mat image = imread("/home/spu/Desktop/FindingContours.png", IMREAD_GRAYSCALE);
    imshow("original", image); waitKey(0);

    // Apply contour detection
    vector< vector< Point > > contours;
    findContours(image, contours, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_NONE);

    // Create empty mask image and draw the contours back
    Mat empty_mask = Mat::ones(image.rows, image.cols, CV_8UC3)*255;
    drawContours(empty_mask, contours, -1, Scalar(0,0,0), FILLED);

    // Show
    imshow("result", empty_mask); waitKey(0);

    return 0;
}
</pre>

I get on the original image 

![findingcontours](https://cloud.githubusercontent.com/assets/4621239/9736299/9c816e14-5640-11e5-9847-06d9c798243e.png)

The following result

![screenshot from 2015-09-08 15 43 52](https://cloud.githubusercontent.com/assets/4621239/9736305/a37fbe14-5640-11e5-81c7-c8f38b7d38cd.png)

Besides from the fact that I am somehow initializing my colours wrongly and I am not in the mood to go digging for that error, it seems to me that the problem does not re-occur?

**Comment by Cylix** [comment]
In my case, areas passed to `drawContours` may overlap (and they do in the screenshots I've posted).
However, it is not the case in your example.

So, it appears that the bug only occurs when areas intersect between themselves.

**Comment by vishwajeet97** [comment]
I have the exact same problem, it would be really helpful to fix the bug.  I am using OpenCV version 3.1.0 on python.

**Comment by terfendail** [comment]
Described behavior is rather a feature than a bug. It is intended to draw nested contours as shapes with holes. So for the case of two nested squares one will get a frame rather than just an filled outer square.
![hole](https://user-images.githubusercontent.com/13571155/32235715-4baedfe4-be71-11e7-9efe-038d81dfb982.png)
To draw contours this way the code avoid to fill areas that are inner to several contours(actually even amount of contours since decision on whether to fill the point is made by [even-odd rule](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule) over all edges of all drew contours ) however this approach have a side effect of not filling contour intersections for not nested contours as well.
![intersect](https://user-images.githubusercontent.com/13571155/32236833-5f96f502-be74-11e7-8740-dfdd65428e47.png)
In order to remove the side effect complex contour matching should be performed prior to drawing.
While separation of nested and intersected contours will definitely ruin the performance it is not always possible without prior knowledge from application domain.
I.e. on the following image it's not obvious whether the hole is in left square, right square, both or it is just intersection of 3 squares.
![3cont](https://user-images.githubusercontent.com/13571155/32238349-97bf3788-be78-11e7-89e7-33c553f9c0d4.png)

**Comment by Cylix** [comment]
```
Described behavior is rather a feature than a bug. It is intended to draw nested contours as shapes with holes. So for the case of two nested squares one will get a frame rather than just an filled outer square.
```

You basically said it: ` It is intended to draw nested contours as shapes with holes.`.
This thing is nowhere in the documentation (at least, it was not at the time this issue was posted, but after giving a quick look, seems it is the same).

Your explanation makes sense, but from a user point of view, this is far away from what can be understood by reading the official documentation.

Thus, in my opinion, either the behavior is the right one and the documentation must be clarified because the output is confusing, either implementation should be changed.

Best

**Comment by ledjorge** [comment]
@Cylix Did you find an efficient way to do what you intended?
I am in the same situation and was looking for an alternative to efficiently draw filled intersecting polygons.

Unfortunately, other functions like _cv::fillPoly(..)_ have exactly the same behaviour as _cv::drawContours(..)_, which is quite frustrating.

Desired vs Obtained:
<img width="958" alt="Screenshot 2021-01-31 at 14 54 50" src="https://user-images.githubusercontent.com/3649087/106386228-482c2000-63d4-11eb-97f1-682874263d6e.png">


Cheers,

**Comment by FranzEricSchneider** [comment]
Yeah, I really wish the even-odd rule could be disabled if desired. I get that it's useful and needed but for my case I'd really just like to fill all the areas covered by the polygons and I'm struggling to figure out how to make that happen here.
