### ISSUE TITLE
sepFilter2d takes the border of the underlying matrix instead of the provided border

### ISSUE THREAD

**Issue by ernest-galbrun** [opencv/opencv#5263]
When applying  sepFilter2d to a subset of a matrix, it should in my opinion act as if it was a whole matrix, adding the border no matter what.

For example:

`cv::Mat A = cv::Mat::ones(3, 4, CV_32F);`
`cv::Mat row_kernel = cv::Mat::ones(3, 1, CV_32F);`
`cv::Mat column_kernel = cv::Mat::ones(1, 1, CV_32F);`
`cv::Mat A_sub = A.colRange(1, 4); //A_sub is ones(3x3)`
`cv::Mat B;`
`cv::sepFilter2D(A_sub, B, -1, rk, ck, cv::Point(-1, -1),0., cv::BORDER_CONSTANT);`

This should give
```B = [2 3 2,
       2 3 2,
       2 3 2]```
and it gives instead
```B = [3 3 2,
       3 3 2,
       3 3 2]```
because the value of A are taken as left border value, instead of the BORDER_CONSTANT that was provided.

The behavior is correct (in my opinion) with the cuda version. In any case, we surely want to have the same behavior between the cpu and gpu version of the 2d filter.

**Comment by ilya-lavrenov** [comment]
Hi @ernest-galbrun, 

OpenCV has 2 types of borders:
- No isolated. It means that functions read values outside of ROI if possible. It's default behavior in filters.
- Isolated. The filters don't read any values outside of ROI. If you run the function as:
```
    cv::sepFilter2D(A_sub, B, -1, row_kernel, column_kernel, cv::Point(-1, -1),0., cv::BORDER_CONSTANT | cv::BORDER_ISOLATED);
```
It gives: 
```
[2, 3, 2;
 2, 3, 2;
 2, 3, 2]
```
As you want. Just use `BORDER_ISOLATED` flag.

**Comment by crackwitz** [comment]
Documentation of `sepFilter2D` and every other function depending on it should make a statement on this behavior.
