### ISSUE TITLE
No way to create a cuda stream with the flag cudaStreamNonBlocking

### ISSUE THREAD

**Issue by dtmoodie** [opencv/opencv#5279]
Currently there is no way of either setting the cudaStreamNonBlocking flag when creating a cv::cuda::Stream object, and there is no way of passing a user created stream with such a flag into the creation of a cv::cuda::Stream object.
This seems to be an oversight because the cv::cuda::Stream::Impl class has a constructor accepting a cudaStream_t object input, thus it would make sense that there be a user exposed method of passing a user created stream in.  Unfortunately cv::cuda::Stream::Impl is defined in a .cpp file and thus is not accessible.

**Comment by ilya-lavrenov** [comment]
You can import existing CUDA stream using the `cuda::StreamAccessor::wrapStream` method. See https://github.com/opencv/opencv/pull/5660
