### ISSUE TITLE
EMD crash when the vectors are all zeros

### ISSUE THREAD

**Issue by YanaiA** [opencv/opencv#5311]
When one or more of the input vectors are [0,0,...0], the Earth Mover's Distance function crashes.

Using matlab & mexopenCV, on windows8

cv.EMD(single([0 0]),single([0 0]))
Error using cv.EMD
Unexpected Standard exception from MEX file.
What() is:C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\imgproc\src\emd.cpp:408: error: (-211)  in function icvInitEMD

cv.EMD(single([0 0]'),single([0 1]'),'DistType','User','Cost',single([0 1; 1 0]))
Error using cv.EMD
Unexpected Standard exception from MEX file.
What() is:C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\imgproc\src\emd.cpp:408: error: (-211)  in function icvInitEMD

**Comment by berak** [comment]
reproduced from c++:

    Mat_<float> a(1,4); a << 1,2,3,4;
    Mat_<float> b(1,4,0.0f); // all 0 initially

    //comment below line to reproduce issue
    b << 4,5,6,7;

    float dist = EMD(a,b,DIST_L2);
    cerr << dist << endl;

**Comment by amroamroamro** [comment]
The assertion in the OpenCV code is correct, although without a helpful error message...

It is not really the fact that the signature is all zeros, but that the total weight of points is zero (i.e sum of the first column of a signature cannot be zero)`. In MATLAB notation that would be:

``` matlab
a = [...];  % whether this one point 1x(dims+1) or more Nx(dims+1)
b = [...];
assert(sum(a(:,1))>0 && sum(b(:,1))>0);
dist = cv.EMD(a, b);
```

Obviously if all points in a signature have zero weight, there's nothing to compare and no distance to compute! You gotta have at least one non-zero-weighted point.
