### ISSUE TITLE
BFMatcher and crossCheck

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#5314]
Hi,
When I use BFMatcher I can find in constructor option crossCheck

Now if I want to use new method cv::DescriptorMatcher::create("BruteForce-Hamming") Is it possible to fix crossCheck to true?

my program is

descriptorMatcher = cv::DescriptorMatcher::create("BruteForce-Hamming");
if (descriptorMatcher.dynamicCastcv::BFMatcher()!=NULL)
{
    descriptorMatcher.dynamicCastcv::BFMatcher()->?????? // crossCheck = true
}

I think one method is missing in BFMatcher something like setCrossCheck(bool b){crossCheck=b;};

Opencv 3.0-dev VS 2013

**Comment by rola93** [comment]
Hi, did you find a way? I'm stucked with the same, but running in python

**Comment by LaurentBerger** [comment]
have you try https://docs.opencv.org/trunk/dc/dc3/tutorial_py_matcher.html?
