### ISSUE TITLE
class_labels vector in boosted decision tree classifier is empty when saved and then loaded from disk

### ISSUE THREAD

**Issue by afriesen** [opencv/opencv#5412]
OpenCV 3.0 seems to use a new format for writing the boosted decision tree classifier to disk, but tries to support the older format as well. When loading a file from disk, it first reads in the value of a FileNode "format" and uses this to determine whether the classifier was written using the old or the new method (the exact check is `bool isLegacy = format < 3;`). However, although OpenCV 3.0 writes to disk using the new format, it does not specify a "format" FileNode; thus, when the classifier is subsequently read from disk, it incorrectly thinks that it was written in the legacy format. 

A simple fix for this is to add the following line to `DTreesImpl::writeParams(FileStorage& fs)` in tree.cpp.

``` c++
void DTreesImpl::writeParams(FileStorage& fs) const
{
    // ---- begin new code ---- 
    fs << "format" << (int) 3;
    // ---- end new code ---- 
    fs << "is_classifier" << isClassifier();
    ...
```

**Comment by afriesen** [comment]
To be more clear, this problem occurs when calling `ml::Boost::write( FileStorage & )`, which is necessary when saving a number of classifiers in the same data structure. If `ml::Boost::save( string & )` is called, then `Algorithm::save()` performs `fs << "format" << (int)3;`.

**Comment by StevenPuttemans** [comment]
Could you provide a PR with the fix?

**Comment by afriesen** [comment]
Yes, I can; however, the fix I mentioned above is probably not the right choice given that `Algorithm::save(const string & filename)` already writes `fs << "format" << (int)3;` (and thus the format will get written twice and probably not solve this for other sub-classed algorithms either).

Better, perhaps, would be that `Algorithm::write()` first writes a header (containing the format) and then writes the sub-class specific data, but this is a much larger change. Thoughts?

**Comment by alalek** [comment]
relates #3032 (new format), #3537 (support for legacy through "format")

This bug triggers issue in tests of opencv_text module here: #19884
Unfortunately we already have several files w/o "format" field.
