### ISSUE TITLE
clFFT support instead of clAmdFft request

### ISSUE THREAD

**Issue by sseiichi** [opencv/opencv#5444]
OpenCV supports clAmdFft, but I think it would be better to replace clAmdFft with clFFT, the newer version of clAmdFft. The AMD website links to clFFT so it's difficult for new users to find clAmdFft. The small trouble is that the library file name and function names are renamed from clFFT.

**Comment by xiedeacc** [comment]
fixed by add add_libraries(clFFT) in Cmakefile
