### ISSUE TITLE
Malik's ncut algorithm

### ISSUE THREAD

**Issue by hellmean** [opencv/opencv#5497]
Current version of OpenCV has only energy minimization based image segmentation algorithms (i.e grab cut). I am interested in eigenvalue based algorithms such as Normolised Cut (see Shi & Malik 2000/8). There are cases when the latter performs better.

Would anyone be interested if I contribute code for Ncut?

Thanks:)

**Comment by StevenPuttemans** [comment]
Actually yes! OpenCV added the edgebox segmentation algorithm of Dollar in 2014 through GSoC but it would be nice to see more segmentation techniques poor into OpenCV. As you can see, there is another PR which also introduces a new segmentation technique: https://github.com/Itseez/opencv_contrib/pull/361

**Comment by hellmean** [comment]
Great! My current code is based on LAPACK in order to compute eigenvectors, which is not very efficient in fact. I will try to implement a better eigenvector search technique and then commit some code:)
Looked at the link as well. Good to know, i didn't know about this paper

Thanks!
Regards,
Andrey

**Comment by StevenPuttemans** [comment]
:+1:
