### ISSUE TITLE
Support for Stroke Width Transform Algorithm

### ISSUE THREAD

**Issue by Omnipresent** [opencv/opencv#5506]
It would be nice if OpenCV provided support for SWT. SWT is an algorithm that finds textual regions in an image. The accompanying paper can be found here: http://yoni.wexlers.org/papers/2010TextDetection.pdf

There is already a c++ implementation using opencv that can be found here: https://github.com/aperrau/DetectText

**Comment by StevenPuttemans** [comment]
New functionality will only enter the library if people are brave enough to provide a pull request with the functionality. Are you up for providing it yourself? In that case a core developer will follow up on your PR and support you in fixing all existing problems.

**Comment by PhilLab** [comment]
Be careful, the code is GPL: https://github.com/aperrau/DetectText/blob/master/COPYING.txt and thus if you want the algorithm in OpenCV (BSD license) you must not use the code and implement it yourself!

**Comment by StevenPuttemans** [comment]
aaaaah bummer o_O

**Comment by aman11dhanpat** [comment]
@PhilLab @StevenPuttemans Can you explain in more detail if we CAN implement similar code at OpenCV and give a link back to github code from where it is implemented?

**Comment by Johndirr** [comment]
See: https://github.com/gracenote-mtl/swt and https://github.com/subokita/Robust-Text-Detection for other SWT implementations.

**Comment by StevenPuttemans** [comment]
@Johndirr thanks for the links!

**Comment by Aravind-Suresh** [comment]
Is the implementation done? If not, I am interested to work on it.

**Comment by StevenPuttemans** [comment]
As far as I can see there is not yet a stroke width transform embedded in OpenCV so feel free to go ahead with it.

**Comment by devanshbatra04** [comment]
Taking this up.

**Comment by devanshbatra04** [comment]
I have re implemented the paper - https://github.com/devanshbatra04/StrokeWidthTransform
Requirements are only C++11. I haven't added any license yet. 

How should I go about making the Pull Request? Do I need to include a test-suite of images as well?
