### ISSUE TITLE
HDR demo code is crashed with OpenCV 3.0 either x64 or x86

### ISSUE THREAD

**Issue by daanzhu** [opencv/opencv#5523]
I am working on HDR. I run the demo code and demo images (memorial00.png). The version of OpenCV is 3.0. I had test under x64 and x86 on x64 Windows 7. The code is crashed at
"calibrate->process(images, response, times);" with exception  "Access violation reading location 0xFFFFFFFFFFFFFFFF"
The call stack show me it crashed at
```
===
calibrate.cpp line 67 src.getMatVector(images);
===
matrix.cpp line1336 -line 1339
mv.resize(n);
```
Does anyone help me? I used the exactly the same test images and demo code.

**Comment by StevenPuttemans** [comment]
I guess that you will get faster an answer at http://answers.opencv.org/questions with crash related problems. Could you open a question there?
