### ISSUE TITLE
cuda::getCudaEnabledDeviceCount crashes from time to time

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#5554]
The function randomly crashes (1 in each 10 runs I'd guess) in [cuda_info.cpp#L54](https://github.com/Itseez/opencv/blob/ddf82d0b154873510802ef75c53e628cd7b2cb13/modules/core/src/cuda_info.cpp#L54). The callstack then goes all the way trough cudart64_70.dll, nvcuda.dll, nvapi64.dll and ends with ntdll.dll!RtlpHeapHandleError().
In most of the runs, it works fine and CUDA code is properly executed.

NVIDIA GeForce GTX 750 Ti

**Comment by asmorkalov** [comment]
@PhilLab Is the issue still relevant?

**Comment by PhilLab** [comment]
@asmorkalov I just tested it with 3.4.3 , executed it 30 times in the same thread and 30 times in different threads and it did not crash. Maybe fixed.

**Comment by asmorkalov** [comment]
Ok, I close the ticket.
