### ISSUE TITLE
No Java binding for Imgproc.EMD 

### ISSUE THREAD

**Issue by Enet4** [opencv/opencv#5565]
OpenCV seems to have an implementation of the Earth Mover's Distance algorithm:

```
CV_EXPORTS float EMD( InputArray signature1, InputArray signature2,
                  int distType, InputArray cost=noArray(),
                  float* lowerBound = 0, OutputArray flow = noArray() );
```

I was hoping to be able to use it in my OpenCV 2.4.10 Java binding, but this particular function is not being generated into the `Imgproc` class. I have compiled the sources against both 2.4 and master, and an `EMD` static method is nowhere to be found. The generator's output even shows that only these functions were skipped:

```
SKIP:static Ptr_TrainData create(Mat samples, int layout, Mat responses, Mat varIdx = Mat(), Mat sampleIdx = Mat(), Mat sampleWeights = Mat(), Mat varType = Mat())  due to RET typePtr_TrainData
SKIP:bool train(Ptr_TrainData trainData, int flags = 0)  due to ARG typePtr_TrainData/I
SKIP:float calcError(Ptr_TrainData data, bool test, Mat& resp)   due to ARG typePtr_TrainData/I
SKIP:bool read(FileNode node)    due to ARG typeFileNode/I
SKIP:Moments moments(Mat array, bool binaryImage = false)    due to RET typeMoments
SKIP:void HuMoments(Moments m, Mat& hu)  due to ARG typeMoments/I
```

This looks like there is something wrong with the generator, but am I missing something?

**Comment by mshabunin** [comment]
Try to replace `CV_EXPORTS` with `CV_EXPORTS_W` and rebuild the OpenCV.

**Comment by Enet4** [comment]
> Try to replace `CV_EXPORTS` with `CV_EXPORTS_W` and rebuild the OpenCV.

Indeed, that explained why it wasn't generated. Now I obtained this method signature:

    //
    // C++:  float EMD(Mat signature1, Mat signature2, int distType, Mat cost = Mat(), float* lowerBound = 0, Mat& flow = Mat())
    //

    //javadoc: EMD(signature1, signature2, distType, cost, lowerBound, flow)
    public static float EMD(Mat signature1, Mat signature2, int distType, Mat cost, float lowerBound, Mat flow)
    {
        
        float retVal = EMD_0(signature1.nativeObj, signature2.nativeObj, distType, cost.nativeObj, lowerBound, flow.nativeObj);
        
        return retVal;
    }

Although I have yet to test this build in my project, this seems to solve what I had in mind. Still, what if one would wish to retrieve the `lowerBound` optional output? Converting the C++ `float*` to a Java `float` makes it unreachable.

**Comment by berak** [comment]
please also have a look [here](https://github.com/Itseez/opencv/pull/2759) for the previous attempt at this

**Comment by Enet4** [comment]
I see... I might have missed the issue with the Python bindings, since I was particularly focused on the Java bindings. Does the discussion in #2759 suggest that both bindings must be working properly for a definite fix?

**Comment by Enet4** [comment]
I have created a branch [here](https://github.com/Itseez/opencv/compare/2.4...Enet4:bugfix_java_bindings_5565) that fixes the behaviour that I mentioned in the previous comment. Are there any recent attempts of fixing the Python binding?

```java
public static float EMD(Mat signature1, Mat signature2, int distType, Mat cost, float[] lowerBound, Mat flow)
{
    double[] lowerBound_out = new double[1];
    float retVal = EMD_0(signature1.nativeObj, signature2.nativeObj, distType, cost.nativeObj, lowerBound[0], lowerBound_out, flow.nativeObj);
    if(lowerBound!=null) lowerBound[0] = (float)lowerBound_out[0];
    return retVal;
}
```
