### ISSUE TITLE
kmeans with dimension > 2 data support

### ISSUE THREAD

**Issue by guopei** [opencv/opencv#5578]
Hi there, as the [kmeans documents](http://docs.opencv.org/modules/core/doc/clustering.html#kmeans) shows:  
The InputArray data only support the following type:
- Mat points(count, 2, CV_32F);
- Mat points(count, 1, CV_32FC2);
- Mat points(1, count, CV_32FC2);
- std::vectorcv::Point2f points(sampleCount);  

These are all 2 dimensional data points. However, it is common when you have 3 or more dimension points to cluster. For example in graph cut you want to cluster the selected foreground colors.  
I think it is worthy of extending the InputArray to support dimension > 2 data.

**Comment by StevenPuttemans** [comment]
If you really want this inside the OpenCV library, the fastest way to get this functionality is by supplying the functionality through a PR to the repository and then a core developer will pick it up and support you in getting it in!

**Comment by aman11dhanpat** [comment]
@guopei , Did you try clustering points with dimension > 2?
I think it is just an example.

**Comment by adrcaraf** [comment]
In fact, the current kmeans implementation does not support matrices with dimensionality higher than 2.
 
`CV_Assert( data0.dims <= 2 && type == CV_32F && K > 0 );` (at matrix.cpp)

I think that an alternative to implementing this functionality would be to simply rearrange your higher dimensional points into row vectors, and pile them up into a matrix of samples.

**Comment by LaurentBerger** [comment]
@alalek I don't understand this issue. I think @adrcaraf  answer is good. This can be used http://answers.opencv.org/question/181410/kmeans-in-real-time/

Can we close this issue?

**Comment by alalek** [comment]
> with dimensionality higher than 2

Use `.reshape()` of matrix to conform function input requirements.

Number of dimensions of variable space != matrix dimension.
