### ISSUE TITLE
GaussianBlur function is not giving identical results (INTEL CPU vs ARM CPU)

### ISSUE THREAD

**Issue by hariprasad4c9** [opencv/opencv#5613]
I have tested the  GaussianBlur function of  version 3.0(Android binding)  in both INTEL and ARM CPUs but I got different results where those are supposed to be identical. For any kernel size for one time blurring ,the difference produced in results is less than or equal to one i.e at some pixels I observed zeros and at remaining pixels I observed ones.This error is getting higher and higher when I tried to run the function in a loop.I used 8 bit RGB  images for testing.
The remaining  image blur functions are working perfectly(giving identical results).But it seems to be an issue with Gaussian Blur.

**Comment by venkatesh009** [comment]
Please see the following file for my observations
![opencvintel vs arm](https://cloud.githubusercontent.com/assets/14271641/11417207/d7677f36-943a-11e5-8d4b-98e203d42eb2.jpg)

**Comment by alalek** [comment]
Some Small example will be useful to take a look on this.

**Comment by hariprasad4c9** [comment]
please follow the link the for results:[](http://answers.opencv.org/question/75158/gaussianblur-function-is-not-giving-identical-results-intel-cpu-vs-arm-cpu/)

**Comment by vladimir-dudnik** [comment]
there are no complete information. CPU models not specified, no reproducible code provided. close this as not complete
