### ISSUE TITLE
SVM train_auto always trains classifier using RBF Kernel even if kernel type explicitly specified beforehand

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#5619]

**Comment by mrquorr** [comment]
anyone working on this?

**Comment by Gaurav7888** [comment]
Hey I want to work upon this issue can you tell which file contains the required code.

**Comment by danielenricocahall** [comment]
I don't know if this is an issue anymore - I tried to replicate and it appears the kernel type that is set is used throughout training. Example:
```
    cv::Ptr<TrainData> data = ....;
    cv::Ptr<SVM> svm = SVM::create();
    svm->setKernel(SVM::LINEAR);
    svm->trainAuto( data, 10 );
```
will perform the hyperparameter optimization with the linear kernel, as expected.
