### ISSUE TITLE
MSER min_diversity not working

### ISSUE THREAD

**Issue by mletombe** [opencv/opencv#5630]
Hi, 

Changing MSER min_diversity parameter has no effect on 3.0.0. I looked in the code, it seems not used for gray mser, but used for color. Not so serious because the parent msers are following each other in growing order, so you can manage the filtering by yourself.

Thank for your work, 
Mathieu.

**Comment by Aaaaaaaron** [comment]
same problem

**Comment by Jaykob** [comment]
Experienced the same problem. Is anybody working on a fix?

**Comment by mletombe** [comment]
Following this definition:
http://stackoverflow.com/questions/17647500/exact-meaning-of-the-parameters-given-to-initialize-mser-in-opencv-2-4-x
and noticing that the msers from the same seed (brightest or darkest pixel) are following each other in growing size order you can apply the min diversity filtering by yourself.

**Comment by Jaykob** [comment]
Thanks! I got it. Would be nice to get a true fix, though...
