### ISSUE TITLE
Python samples not correct

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#5673]
Some of my students noticed that the python tutorials are incorrect and no longer working. For example the backgroundsubtraction sample [here](http://docs.opencv.org/ref/master/db/d5c/tutorial_py_bg_subtraction.html#gsc.tab=0) has an error in line

`fgbg = cv2.createBackgroundSubtractorMOG()`

which should actually be

`fgbg = cv2.bgsegm.createBackgroundSubtractorMOG()`

I am wondering if this is the case for all functionality and thus, all samples need to be adapted? If so I am able to provide fixes, but I would rather love to have a more experienced python user to confirm this problem.

**Comment by StevenPuttemans** [comment]
@berak could you confirm?

**Comment by berak** [comment]
yes, true, both MOG and GMG are in bgsegm now.

it probably also needs a hint that both of them were moved to opencv_contrib

**Comment by StevenPuttemans** [comment]
Ok thanks for the feedback! And regarding the `cv2.submodule.function`, is this also the case for the main repo?

**Comment by berak** [comment]
cv2.submodule.function ? 

sorry, did not understand

**Comment by StevenPuttemans** [comment]
Well for the contributed modules the systems goes as follows

`fgbg = cv2.bgsegm.createBackgroundSubtractorMOG()`

but for the normal repository, is it then

fgbg = cv2.createBackgroundSubtractorMOG2() 

or

`fgbg = cv2.video.createBackgroundSubtractorMOG2()`?

**Comment by berak** [comment]
no, 

cv2.createBackgroundSubtractorMOG2()
cv2.createBackgroundSubtractorKNN()

(without .video submodule, there's no such thing)

**Comment by StevenPuttemans** [comment]
Do correct me, but that is weird right, that normal modules don't have submodules and contrib modules do?

**Comment by berak** [comment]
well, oh ;)

i guess, it would even break abi compatibility, if one would introduce them now.

**Comment by StevenPuttemans** [comment]
I hate ABI compatibility :D

**Comment by swarnak25** [comment]
why am I getting this error?
  fgbg = cv2.bgsegm.createBackgroundSubtractorMOG2()

AttributeError: module 'cv2' has no attribute 'bgsegm'

**Comment by berak** [comment]
@swarnak25 , this is not a bug, your cv2 probably does not contain this module

you have to build your cv2 from src with [opencv_contrib](https://github.com/opencv/opencv_contrib)

**Comment by swarnak25** [comment]
Got it.

**Comment by jjjimenez100** [comment]
Are there any pre-built packages that include the contrib modules? Or building them from source is the only way?

**Comment by alalek** [comment]
There are no any official packages with contrib from OpenCV team. But they exist via pip, anaconda, etc.

**Comment by jjjimenez100** [comment]
Got it. Thank you!

**Comment by Schizo** [comment]
That should work:
`pip install opencv-contrib-python`

**Comment by StevenPuttemans** [comment]
> That should work:
> pip install opencv-contrib-python

There is a risk with this! If your `opencv-python` and` opencv-contrib-python` are out of sync (different versions) than there is about 95% chance it will blow up in your face and your software won't work. In that case I think it is always better to ensure you built the correct version combination yourself.

**Comment by harshajayaweeraXHJ** [comment]
Is this issue still open. I would like to look into this if there's anything I can contribute!

**Comment by StevenPuttemans** [comment]
Since this issue is quite old, from 2015, chances of someone not providing a fix already are very small. Have a look at the current python samples and go discover for yourself: https://docs.opencv.org/master/d6/d00/tutorial_py_root.html

**Comment by alalek** [comment]
Fixed on [master](https://docs.opencv.org/ref/master/d8/d38/tutorial_bgsegm_bg_subtraction.html) branch.
