### ISSUE TITLE
svm.cpp - Incorrect error about k_fold parameter?

### ISSUE THREAD

**Issue by LorenaGdL** [opencv/opencv#5699]
Using train_auto() function, today I came across the following error message (svm.cpp, lines 1436-1439):

        //check that while cross-validation there were the samples from all the classes
        if( class_ranges[class_count] <= 0 )
            CV_Error( CV_StsBadArg, "While cross-validation one or more of the classes have "
            "been fell out of the sample. Try to enlarge <Params::k_fold>" );

I understand that the problem is that one the k_fold subsets does not contain samples from one of the classes. However, the recommendation is to **enlarge** k_fold. Shouldn't it be the way around, i.e. **reduce** the parameter?

Example: let's say we have 10 negative samples and 3 positive ones in the training dataset. Using k_fold = 4, one of the subsets won't have a positive sample, and thus the error will appear. If we enlarge k_fold to 6, then 3 of the subsets won't have a positive sample - we don't fix the error but make it worse.

If I'm right, I'll be glad to provide the corresponding PR.

**Comment by IshankGulati** [comment]
Can I work on this issue?

**Comment by Dikay900** [comment]
@IshankGulati you can. When you are done just open a Pullrequest referencing this issue.

**Comment by terfendail** [comment]
Fixed by PR #6860
