### ISSUE TITLE
MSER::detectRegions() crashes with input image size 1 (in any dimension)

### ISSUE THREAD

**Issue by scorpeeon** [opencv/opencv#5705]
I recently noticed that calling MSER's detectRegions() with an input image that has either 1 rows or 1 cols, the function crashes (I get: "Access violation reading location" or "A heap has been corrupted").
Input's type is normal cv::InputArray, and the documentation doesn't specify a minimum size for it, so I see no reason why it would crash.
Code to reproduce:
```.cpp
std::vector<std::vector<cv::Point>> regions;
std::vector<cv::Rect> rects;
cv::Ptr<cv::MSER> mser = cv::MSER::create();
mser->detectRegions(cv::Mat(2, 2, CV_8UC1, cv::Scalar(0)), regions, rects); // OK
mser->detectRegions(cv::Mat(1, 100, CV_8UC1, cv::Scalar(0)), regions, rects); // crash
mser->detectRegions(cv::Mat(100, 1, CV_8UC1, cv::Scalar(0)), regions, rects); // crash
mser->detectRegions(cv::Mat(1, 1, CV_8UC1, cv::Scalar(0)), regions, rects); // crash
```

Tried with both gray and color MSERs, crashes in the same cases.
Using OpenCV 3.0, x64.

**Comment by terfendail** [comment]
Processing of images with dimensions lesser than 3 would complicate the code and could cause performance degradation. So at the moment I've just restricted small image processing.
I think it would be better to separate processing of such images(1xN, 2xN, Nx1, Nx2) in case it would be considered useful to support them.
