### ISSUE TITLE
feature_homography/feature_homography.markdown - Possible issue on a tutorial matching a image that is a subset of another

### ISSUE THREAD

**Issue by kaxios** [opencv/opencv#5753]
Hi!

At this sample, it seems if the image of the object is a subset of the scene image(copy and past a part of it as object to test) the distance seems to be 0.0 for all points. On this case, the samples errors out. 

It seems to be because this condition test if the **distance is 0.0 for all points**, it mark all as not a good match. 

``` cpp
if( matches[i].distance < 3*min_dist )
     { good_matches.push_back( matches[i]); }
```

I would suggest to change it to (by replacing  **<** by **<=** ):

``` cpp
if( matches[i].distance <= 3*min_dist )
     { good_matches.push_back( matches[i]); }
```

This allow the match to work on this cases. Instead of throwing  an exception  on this cases. 

Source:
https://github.com/Itseez/opencv/blob/master/doc/tutorials/features2d/feature_homography/feature_homography.markdown

Nice Sample! 
:+1:

Regards,

**Comment by sturkmen72** [comment]
i think this issue can be closed as resolved.
