### ISSUE TITLE
VideoCapture::read() blocks when reading a video file

### ISSUE THREAD

**Issue by Werkov** [opencv/opencv#5766]
Hi. I've got a video capture that reads a video file and I'd like to process frames w/out delay. However, my measurements showed that `VideoCapture::read()` (or `VideoCapture::grab()`) is blocking -- the time it blocks is the delay between two frames for given framerate of the video.

I observed this on 2.4.11 with GStreamer backend and the delay is propagated from GStreamer pipeline. See [explanation](https://git.collabora.com/cgit/user/kakaroto/gst-plugins-base.git/plain/gst-libs/gst/app/gstappsink.c) what `emit-signals` does and it is actually [set to false](https://github.com/Itseez/opencv/blob/2.4.11/modules/highgui/src/cap_gstreamer.cpp#L741) in OpenCV.

Is the blocking behavior intended for video files? If so, is there a way how to batch-process a video file? (Unfortunately, setting `CV_CAP_PROP_FPS` doesn't work with GStreamer backend.)

Thanks.

**Comment by mshabunin** [comment]
@Werkov , I guess you need to add `sync=false` property to the sink, try to built pipeline manually and pass this string to VideoCapture: `filesrc location="..." ! decodebin ! videoconvert ! appsink sync=false`

Check this example:  https://github.com/opencv/opencv/blob/master/samples/cpp/gstreamer_pipeline.cpp
