### ISSUE TITLE
Working with opencv2 and opencv3

### ISSUE THREAD

**Issue by 23pointsNorth** [opencv/opencv#5772]
Hello all,

I am wondering now that openCV 3.0 has been released, whether there are plans to actually rename all the occurrences of "2" with "3".  This will allow to maintain compatibility with older projects, as pkg-config will find the opencv2.pc, but also allow to build new projects against opencv 3.0.

The changes would include the the header files, lib names. 

The name difference will allow to install opencv 3 alongside ROS Indigo (which uses the older version), without worrying about conflicts and which libs to link against.

Regards,
Daniel

**Comment by 23pointsNorth** [comment]
Ping.
Anyone managed to ask around? Especially that 3.1 is on the roadmap & a lot of LTS code is on the 2.x branch.

**Comment by antran89** [comment]
Hi @23pointsNorth 
I am not sure what you are asking. I think you can install in 2 different folders and using Cmake to link the version you want to link against using `CMAKE_PREFIX_PATH`.

**Comment by alalek** [comment]
As mentioned above try to use `-DCMAKE_INSTALL_PREFIX=/opt/opencv-2.4` and `-DCMAKE_INSTALL_PREFIX=/opt/opencv-3.0` cmake parameters.
In your application use `cmake -DOpenCV_DIR=<path to opencv installation>/share/OpenCV/ ...` to specify OpenCV version.
If you use `pkg-config` then refer to documentation of `PKG_CONFIG_PATH` environment variable.

If you want to use both OpenCV versions from system-installed packages or from other package managers then you should refer to real maintainers of these packages.

**Comment by nstiurca** [comment]
I agree with @23pointsNorth. All the namespaces/filenames/etc. should change from 2 to 3.

One thing that has been causing me headaches (with in the ROS ecosystem in particular) is needing to have both opencv2 and opencv3 in the same project. The reason for this is that there is a lot of stuff in ROS already linked against opencv2 (including all the image/video marshalling code which communicates between different ROS nodes), but I want to use OpenCV3 features in my code.
