### ISSUE TITLE
question in calculating the norm factor for haar feature

### ISSUE THREAD

**Issue by teng88** [opencv/opencv#5779]
https://github.com/Itseez/opencv/blob/master/apps/traincascade/features.cpp#L12 
E.g., the sample is 20x20 size, this line shows that the rect used to calculate norm factor is the center rect with size of 18x18 which just excluding one pixel border. 
This will help to improve the result? or, do I miss something?
@StevenPuttemans @vpisarev 

As I found in some matlab implementation of VJ framework, the rect used to calculating norm factor is exactly the same size of sample.

**Comment by StevenPuttemans** [comment]
Problem is that I am still after 2 years into the topic sometimes wondering why some of the implementation details have been done. Like you say, this is different to the matlab equivalent and I have yet to discover why. I guess it might have to do with the default step of the sliding window?

**Comment by teng88** [comment]
I have done some experiments and the result shows that the same size as the sample for norm rect have slightly better performance, thus I suggest to change this parameter in the default implementation.

**Comment by StevenPuttemans** [comment]
I suggest you to make a PR, add test results before and after changing it and it will surely get in!
