### ISSUE TITLE
Matchtemplate() OCL Normalized 32 bit float support

### ISSUE THREAD

**Issue by McDonaldTD** [opencv/opencv#5785]
Hi, 

I do not believe the 32 bit float format is currently supported by the normalized match template functions, specifically the TM_CCORR_NORMED

**Comment by laetitiaoist** [comment]
Is this resolved? I got different results on two computers using TM_CCORR_NORMED with floating point images. Converting to uint8 fixes my problem.
One of the result contained weird artifacts of high score that were completely wrong.
