### ISSUE TITLE
Delaunay triangulation returns bad points

### ISSUE THREAD

**Issue by DdarkSideE** [opencv/opencv#5788]
class Subdiv2D implements delaunay triangulation. 
One of constructors take a rect. Then you need to insert points. Then getTriangleList returns points of trinagles to you. But. Some points is not in the rect area. For example. An image 1280x1024. But you can take a point like this (-1117, 85). How can it be? I give a rect with (0, 0, width, heigh).
And. I have 2 images with faces. And each face have 69 points on it.
When I use triangulation, I take different count of trinagles of each face. Why? 
Bug maybe?

**Comment by ythej** [comment]
Is someone working on this? I am new to this organisation and I would like to start contributing with this bug fix :)

Thanks.

**Comment by Dikay900** [comment]
If you cannot find an open pull request fixing this bug you are free to work on any issue and then open an own pull request.

**Comment by ythej** [comment]
Okay, I didn't find any open PR related to this bug. So, I am working on this! 
Thanks! :)

**Comment by ythej** [comment]
Could anyone please help me in finding which file I will have to look for this?
Thanks :)

**Comment by DdarkSideE** [comment]
[subdivision2d.cpp](https://github.com/Itseez/opencv/blob/ddf82d0b154873510802ef75c53e628cd7b2cb13/modules/imgproc/src/subdivision2d.cpp)

**Comment by DdarkSideE** [comment]
[subdivision2d.cpp](https://github.com/Itseez/opencv/blob/ddf82d0b154873510802ef75c53e628cd7b2cb13/modules/imgproc/src/subdivision2d.cpp)
![dotted](https://cloud.githubusercontent.com/assets/3995841/12320200/69574888-bab8-11e5-92e4-1da4f340689a.jpg)
Points: `[[[390, 802], [397, 883], [414, 963], [439, 1042], [472, 1113], [521, 1181], [591, 1238], [678, 1284], [771, 1292], [853, 1281], [921, 1243], [982, 1191], [1030, 1121], [1059, 1038], [1072, 945], [1081, 849], [1082, 749], [459, 734], [502, 704], [554, 696], [609, 698], [660, 707], [818, 688], [874, 661], [929, 646], [982, 653], [1026, 682], [740, 771], [748, 834], [756, 897], [762, 960], [700, 998], [733, 1006], [766, 1011], [797, 999], [825, 987], [528, 796], [566, 766], [617, 763], [659, 794], [619, 808], [569, 812], [834, 777], [870, 735], [918, 729], [958, 750], [929, 773], [882, 780], [652, 1102], [701, 1079], [743, 1063], [774, 1068], [807, 1057], [852, 1065], [896, 1077], [860, 1117], [820, 1135], [783, 1141], [751, 1140], [706, 1130], [675, 1102], [743, 1094], [774, 1094], [809, 1088], [878, 1082], [810, 1093], [776, 1098], [744, 1096]], []]`
Rect(image size): (0, 0, 1500, 2252)
getTriangleList() returns: `[[ 6756.     0.     0.  6756.   982.  1191.]
 [    0.  6756.  6756.     0. -6756. -6756.]
 [    0.  6756. -6756. -6756.   414.   963.]
 [-6756. -6756.  6756.     0.   982.   653.]
 [  619.   808.   617.   763.   659.   794.]
 [  617.   763.   619.   808.   566.   766.]
 [-6756. -6756.   397.   883.   414.   963.]
 [  397.   883. -6756. -6756.   390.   802.]
 [  390.   802. -6756. -6756.   459.   734.]
 [  701.  1079.   700.   998.   733.  1006.]
 [  700.   998.   701.  1079.   652.  1102.]
 [  397.   883.   390.   802.   528.   796.]
 [ 1072.   945.   896.  1077.   825.   987.]
 [  896.  1077.  1072.   945.  1059.  1038.]
 [    0.  6756.   414.   963.   439.  1042.]
 [  414.   963.   397.   883.   528.   796.]
 [  774.  1068.   766.  1011.   807.  1057.]
 [  766.  1011.   774.  1068.   743.  1063.]
 [    0.  6756.   439.  1042.   472.  1113.]
 [  439.  1042.   414.   963.   700.   998.]
 [  439.  1042.   700.   998.   652.  1102.]
 [    0.  6756.   472.  1113.   521.  1181.]
 [  472.  1113.   439.  1042.   652.  1102.]
 [  700.   998.   414.   963.   569.   812.]
 [    0.  6756.   521.  1181.   591.  1238.]
 [  521.  1181.   472.  1113.   652.  1102.]
 [  825.   987.   762.   960.   756.   897.]
 [  762.   960.   825.   987.   797.   999.]
 [    0.  6756.   591.  1238.   678.  1284.]
 [  591.  1238.   521.  1181.   652.  1102.]
 [  566.   766.   619.   808.   569.   812.]
 [    0.  6756.   678.  1284.   771.  1292.]
 [  678.  1284.   591.  1238.   706.  1130.]
 [  414.   963.   528.   796.   569.   812.]
 [    0.  6756.   771.  1292.   853.  1281.]
 [  771.  1292.   678.  1284.   751.  1140.]
 [    0.  6756.   921.  1243.   982.  1191.]
 [  921.  1243.     0.  6756.   853.  1281.]
 [  853.  1281.   771.  1292.   783.  1141.]
 [  921.  1243.   853.  1281.   820.  1135.]
 [  756.   897.   619.   808.   659.   794.]
 [  619.   808.   756.   897.   700.   998.]
 [ 6756.     0.   982.  1191.  1030.  1121.]
 [  982.  1191.   921.  1243.   860.  1117.]
 [  659.   794.   740.   771.   748.   834.]
 [  740.   771.   659.   794.   660.   707.]
 [ 6756.     0.  1030.  1121.  1059.  1038.]
 [ 1030.  1121.   982.  1191.   896.  1077.]
 [  528.   796.   459.   734.   502.   704.]
 [  459.   734.   528.   796.   390.   802.]
 [ 6756.     0.  1059.  1038.  1072.   945.]
 [ 1059.  1038.  1030.  1121.   896.  1077.]
 [  554.   696.   566.   766.   502.   704.]
 [  566.   766.   554.   696.   609.   698.]
 [ 6756.     0.  1072.   945.  1081.   849.]
 [  528.   796.   502.   704.   566.   766.]
 [ 6756.     0.  1081.   849.  1082.   749.]
 [ 1081.   849.  1072.   945.   929.   773.]
 [ 6756.     0.  1082.   749.  1026.   682.]
 [ 1082.   749.  1081.   849.   958.   750.]
 [  870.   735.   874.   661.   918.   729.]
 [  874.   661.   870.   735.   818.   688.]
 [  459.   734. -6756. -6756.   502.   704.]
 [  700.   998.   756.   897.   762.   960.]
 [  502.   704. -6756. -6756.   554.   696.]
 [  929.   773.  1072.   945.   825.   987.]
 [  554.   696. -6756. -6756.   929.   646.]
 [  756.   897.   834.   777.   882.   780.]
 [  834.   777.   756.   897.   748.   834.]
 [  609.   698.   874.   661.   660.   707.]
 [  874.   661.   609.   698.   554.   696.]
 [  660.   707.   818.   688.   740.   771.]
 [  818.   688.   660.   707.   874.   661.]
 [  609.   698.   660.   707.   617.   763.]
 [  818.   688.   870.   735.   834.   777.]
 [  834.   777.   740.   771.   818.   688.]
 [  740.   771.   834.   777.   748.   834.]
 [  929.   773.   918.   729.   958.   750.]
 [  918.   729.   929.   773.   882.   780.]
 [  874.   661.   554.   696.   929.   646.]
 [  918.   729.   982.   653.   958.   750.]
 [  982.   653.   918.   729.   929.   646.]
 [  874.   661.   929.   646.   918.   729.]
 [  929.   646. -6756. -6756.   982.   653.]
 [  918.   729.   882.   780.   870.   735.]
 [  982.   653.  6756.     0.  1026.   682.]
 [ 1026.   682.  1082.   749.   958.   750.]
 [  982.   653.  1026.   682.   958.   750.]
 [  756.   897.   882.   780.   825.   987.]
 [  982.  1191.   860.  1117.   896.  1077.]
 [  706.  1130.   591.  1238.   652.  1102.]
 [  748.   834.   756.   897.   659.   794.]
 [  807.  1057.   766.  1011.   797.   999.]
 [  701.  1079.   733.  1006.   743.  1063.]
 [  809.  1088.   776.  1098.   774.  1094.]
 [  776.  1098.   809.  1088.   810.  1093.]
 [  743.  1094.   701.  1079.   743.  1063.]
 [  701.  1079.   743.  1094.   706.  1130.]
 [  700.   998.   762.   960.   733.  1006.]
 [  744.  1096.   774.  1094.   776.  1098.]
 [  774.  1094.   744.  1096.   743.  1094.]
 [  733.  1006.   762.   960.   766.  1011.]
 [  852.  1065.   810.  1093.   809.  1088.]
 [  810.  1093.   852.  1065.   860.  1117.]
 [  733.  1006.   766.  1011.   743.  1063.]
 [  766.  1011.   762.   960.   797.   999.]
 [  825.   987.   896.  1077.   852.  1065.]
 [  797.   999.   825.   987.   807.  1057.]
 [  700.   998.   569.   812.   619.   808.]
 [  609.   698.   617.   763.   566.   766.]
 [  528.   796.   566.   766.   569.   812.]
 [  660.   707.   659.   794.   617.   763.]
 [ 1081.   849.   929.   773.   958.   750.]
 [  834.   777.   870.   735.   882.   780.]
 [  929.   773.   825.   987.   882.   780.]
 [  652.  1102.   701.  1079.   675.  1102.]
 [  783.  1141.   771.  1292.   751.  1140.]
 [  820.  1135.   853.  1281.   783.  1141.]
 [  743.  1063.   774.  1068.   743.  1094.]
 [  852.  1065.   809.  1088.   807.  1057.]
 [  774.  1068.   807.  1057.   809.  1088.]
 [  807.  1057.   825.   987.   852.  1065.]
 [  896.  1077.   860.  1117.   878.  1082.]
 [  852.  1065.   896.  1077.   878.  1082.]
 [  860.  1117.   852.  1065.   878.  1082.]
 [  860.  1117.   921.  1243.   820.  1135.]
 [  774.  1068.   809.  1088.   774.  1094.]
 [  860.  1117.   820.  1135.   810.  1093.]
 [  743.  1094.   774.  1068.   774.  1094.]
 [  820.  1135.   783.  1141.   810.  1093.]
 [  701.  1079.   706.  1130.   675.  1102.]
 [  783.  1141.   751.  1140.   776.  1098.]
 [  751.  1140.   678.  1284.   706.  1130.]
 [  706.  1130.   652.  1102.   675.  1102.]
 [  751.  1140.   706.  1130.   744.  1096.]
 [  706.  1130.   743.  1094.   744.  1096.]
 [  776.  1098.   751.  1140.   744.  1096.]
 [  810.  1093.   783.  1141.   776.  1098.]]`

**Comment by ythej** [comment]
I am not working on this. I am a beginner and when I am asking doubts about this, I am told to first work on some projects. So, this information will be helpful for some other person.

Thanks! :)
