### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by rays2pix** [opencv/opencv#5839]
When I compile opencv release 3.0.0 I get the following error.
 In function ‘void cv::applyColorMap(cv::InputArray, cv::OutputArray, int)’:
 In ..modules/imgproc/src/colormap.cpp:540:25: error: ‘COLORMAP_PARULA’ was not declared in this scope

However I could see  that COLORMAP_PARULA was inside the enum for colormap in imgproc.hpp. Can you help me understand and clear this compilation error?

**Comment by alalek** [comment]
1) Attach output `make VERBOSE=1` and get failed compiler command.
2) Run GCC preprocessor: add `-E` option to command line above (remove "-c" option if exists)
3) Check file patchs in preprocessor output

If there are path conflicts then remove previous OpenCV installations.

**Comment by ilya-lavrenov** [comment]
The issue is abandoned.
