### ISSUE TITLE
Python3 module is named incorrectly when cross-compiling

### ISSUE THREAD

**Issue by virtuald** [opencv/opencv#5887]
Affects OpenCV 3.1 release, using CMake 2.8 on Ubuntu 14.04 LTS.

It appears to use the host configuration (python 3.4), and not the target configuration (python 3.5), as you can see from the initial cmake output:

```
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
--     Libraries:                   /home/vagrant/build/sysroot/usr/local/lib/libpython2.7.so (ver 2.7.11)
--     numpy:                       /home/vagrant/build/sysroot/usr/local/lib/python2.7/site-packages/numpy/core/include (ver undefined - cannot be probed because of the cross-compilation)
--     packages path:               lib/python2.7/dist-packages
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)
--     Libraries:                   /home/vagrant/build/sysroot/usr/local/lib/libpython3.5m.so.1.0
--     numpy:                       /home/vagrant/build/sysroot/usr/local/lib/python3.5/site-packages/numpy/core/include (ver undefined - cannot be probed because of the cross-compilation)
--     packages path:               lib/python3.4/dist-packages
-- 
--   Python (for build):            /usr/bin/python2.7

```

At the end of the compilation process, I end up with a `lib/python3/cv2.cpython-34m.so`.

**Comment by virtuald** [comment]
I've put together a repository that has a script to cross compile OpenCV with our gcc 4.9.3 toolchain in a VM. If someone is trying to debug this, you should be able to easily reproduce it here.

https://github.com/robotpy/roborio-opencv

**Comment by oliverseal** [comment]
Running into this same issue.

**Comment by mshabunin** [comment]
Please check whether the PR #6779 fixes your issue.

**Comment by alalek** [comment]
In general, there is still no way to run target python for autodetection (for example for ARM cpu from x86 host), but you can specify CMake variable (in #6779):
```
cmake -DPYTHON3_CVPY_SUFFIX=.cpython-35m.so ...`
```
