### ISSUE TITLE
Canny misses one edge of 2px lines with aperture size of 3

### ISSUE THREAD

**Issue by jiong3** [opencv/opencv#5913]
OpenCV 2.4.9 on OSX, Python bindings. I haven't checked with OpenCV 3.0 yet.

Input image:
![input](https://cloud.githubusercontent.com/assets/2176196/12074826/710bd230-b16a-11e5-9f04-0f08ef8fbbbf.png)

One edge missing for 2px lines with an aperture of 3:
`cv2.Canny(image, 10, 20, canny, 3, True)`
![aperture_3](https://cloud.githubusercontent.com/assets/2176196/12074827/771f13f8-b16a-11e5-9b0a-59ad6184c5b2.png)

All edges there with an aperture of 5:
`cv2.Canny(image, 10, 20, canny, 5, True)`
![aperture_5](https://cloud.githubusercontent.com/assets/2176196/12074828/774d59de-b16a-11e5-826c-e6ed8cf4dc65.png)

**Comment by BulatSuleymanoff** [comment]
I think, it's not about OpenCV, it's about Canny edge detector algorithm or exactly it's Sobel filter part.
When the kernel is larger, the image becomes more blurry, that's why more pixels are connected and more edges are detected.
