### ISSUE TITLE
Failure linking to libbz2 when x86 and x64 libraries are present

### ISSUE THREAD

**Issue by virtuald** [opencv/opencv#5934]
On Fedora 22, I have x86 and x64 libraries installed for libbz2.so (I think because of wine). OpenCV finds the wrong library and the compile fails because it tries to link against /lib/libbz2.so instead of /lib64/

I suspect the problem is at https://github.com/Itseez/opencv/blob/master/cmake/OpenCVFindLibsVideo.cmake#L230, as it specifies to search for the file at /lib. I changed the value to /lib64 and the compile worked fine.

**Comment by alalek** [comment]
Do you have any ideas why the line above with standard way of library search doesn't work?
```
FIND_LIBRARY(BZIP2_LIBRARIES NAMES bz2 bzip2)
```

**Comment by virtuald** [comment]
I'm not very familiar with cmake, so hard to say... but perhaps this is helpful?

```
$ ls -l /lib*
lrwxrwxrwx. 1 root root 7 Aug 16  2014 /lib -> usr/lib
lrwxrwxrwx. 1 root root 9 Aug 16  2014 /lib64 -> usr/lib64

$ ls /lib/*bz2*
/lib/libbz2.so.1  /lib/libbz2.so.1.0.6

$  /lib/*bzip2*
ls: cannot access /lib/*bzip2*: No such file or directory

$  /lib64/*bzip2*
ls: cannot access /lib64/*bzip2*: No such file or directory

$ ls /lib64/*bz2*
/lib64/libbz2.so  /lib64/libbz2.so.1  /lib64/libbz2.so.1.0.6

$ rpm -qa | grep bzip
mingw32-bzip2-1.0.6-5.fc21.noarch
libzip-0.11.2-5.fc22.x86_64
bzip2-1.0.6-14.fc22.x86_64
bzip2-libs-1.0.6-14.fc22.i686
bzip2-devel-1.0.6-14.fc22.x86_64
bzip2-libs-1.0.6-14.fc22.x86_64
mingw64-bzip2-1.0.6-5.fc21.noarch
bzip2-debuginfo-1.0.6-14.fc22.x86_64

```

**Comment by alalek** [comment]
On my fedora specified command works fine:
```
$ rpm -qa | grep bzip2
bzip2-1.0.6-19.fc23.x86_64
bzip2-libs-1.0.6-19.fc23.x86_64
bzip2-libs-1.0.6-19.fc23.i686
```

Do you build from clean build directory? (CMake cache some search results, and if you install packages after the first CMake run in the build dir, then cached results may be wrong)

BTW, current bzip2 library integration is a legacy dirty hack and doesn't follow best practices of CMake configuration. It should be changed.

**Comment by virtuald** [comment]
It was a brand new build directory.

Is there an option I can give to cmake to tell it to output debug information that might shed light on why it's missing the file?

**Comment by alalek** [comment]
There are "--debug-output" and "--trace" CMake options. But I'm not sure that they will show a reason of  the problem

**Comment by alalek** [comment]
I can confirm this problem.
I found Fedora 23 system where I can catch this issue.
```
$ ls /lib64/*bz2*
/lib64/libbz2.so.1  /lib64/libbz2.so.1.0.6
```
There is no "libbz.so" file, only instances with "soversion" is here, which causes CMake `find_library()` to fail.

**Comment by alalek** [comment]
@virtuald Could you take a look on #6100?

**Comment by virtuald** [comment]
I'll look at this during the weekend, thanks!

**Comment by casper-ua** [comment]
The very similar issue arises again, but this time when "cmake -D WITH_TBB=ON .." is specified:

    link library [libbz2.so] in /usr/lib64 may be hidden by files in:
      /usr/include/../lib

It is not bzip2 related so, but it is in cmake/OpenCVDetectTBB.cmake:

    if(UNIX)
      set(TBB_LIB_DIR "${TBB_INCLUDE_DIRS}/../lib" CACHE PATH "Full path of TBB library directory")
      link_directories("${TBB_LIB_DIR}")
    endif()

For example on CentOS 6.x x86_64 tbb libs (and others 64-bits libs of course) are in /usr/lib64:

    $ ls -l /usr/lib64/libtbb*
    lrwxrwxrwx 1 root root     17 Oct 21 09:58 /usr/lib64/libtbbmalloc.so -> libtbbmalloc.so.2
    -rwxr-xr-x 1 root root  37712 Feb 21  2013 /usr/lib64/libtbbmalloc.so.2
    lrwxrwxrwx 1 root root     11 Oct 21 09:58 /usr/lib64/libtbb.so -> libtbb.so.2
    -rwxr-xr-x 1 root root 143480 Feb 21  2013 `/usr/lib64/libtbb.so.2

So there should be difference in detecting tbb when building from sources and with system libraries taking in account 32/64-bits arch.

**Comment by alalek** [comment]
> It is not bzip2 related

Also it is not related to ffmpeg from where original problem raises.
Please open a new issue about problem in "TBB" detection
