### ISSUE TITLE
Cannot find Guo Hall thinning method.

### ISSUE THREAD

**Issue by tastyminerals** [opencv/opencv#5988]
I am looking for Guo Hall thinning which I was told latest openCV has implemented.
Unfortunately I cannot find anything about this method in opencv 3.1.0 docs.
Also, several online sources point to a Japanese article which has this method implemented in c++. 
jap article: http://www.eml.ele.cst.nihon-u.ac.jp/~momma/wiki/wiki.cgi/OpenCV/%E7%B4%B0%E7%B7%9A%E5%8C%96.html

The question is, is it available in opencv 3.1.0?

**Comment by StevenPuttemans** [comment]
It is not included inside OpenCV itself, but many implementations are based on OpenCV
1. https://github.com/arnaud-ramey/voronoi
2. https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/chapter_6/source_code/fingerprint/fingerprint_process/fingerprint_process.cpp
3. https://github.com/bsdnoobz/zhang-suen-thinning
