### ISSUE TITLE
OpenCV 2.4.12.3 Python shared library issue

### ISSUE THREAD

**Issue by ramnath-k** [opencv/opencv#6021]
I built Python 2.7.11 with the --enable-shared option on Ubuntu 14.04 using the following command:

```bash
./configure --prefix /usr/local/lib/python2.7.11 --enable-ipv6 --enable-unicode=ucs4 --enable-shared --with-cxx-main=/usr/bin/g++ LDFLAGS="-Wl,--rpath=/usr/local/lib/python2.7.11/lib"
```

Then created a virtualenv with this python. When I run Python from the command line it correctly prints that the version is 2.4.11.  

Then I checked out the opencv release '2.4.12.3' and ran configure using the following command:

```bash
cmake -D CMAKE_INSTALL_PREFIX=$VIRTUAL_ENV/local/ -D PYTHON_EXECUTABLE=$VIRTUAL_ENV/bin/python -D PYTHON_LIBRARY=/home/ramnath/local/python2.7.11/lib/libpython2.7.so -D PYTHON_PACKAGES_PATH=$VIRTUAL_ENV/lib/python2.7/site-packages -D BUILD_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON _D INSTALL_C_EXAMPLES=ON -D WITH_V4L=ON -D CUDA_GENERATION=Auto -D WITH_CUBLAS=1 -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_OPENGL=ON -D WITH_QT=ON -D WITH_TBB=ON ..
```

This prints the following output:
-- Found PythonInterp: /home/ramnath/.virtualenvs/opencv2/bin/python (found suitable version "2.7.11") 
-- Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required is exact version "2.7.11" (found /home/ramnath/local/python2.7.11/lib/libpython2.7.so)

But if I proceed to make and install opencv it installs and I am able to do `import cv2` in python interpreter.

My question is why is opencv saying the Pythonlib version is only 2.7.6 when it is clear that the python version is 2.7.11 (it is indeed finding the correct shared library file)?

**Comment by alalek** [comment]
Could you try to reproduce problem with "master" branch?

**Comment by ramnath-k** [comment]
I get the same Pythonlib detection problem when compiling the master branch using CMake 2.8.

But when I compile master branch using CMake 3.4.3 it is detecting it prints the Pythonlib version correctly.

-- Found PythonInterp: /home/ramnath/.virtualenvs/opencvmaster/bin/python (found suitable version "2.7.11", minimum required is "2.7") 
-- Found PythonLibs: /usr/local/lib/python2.7.11/lib/libpython2.7.so (found suitable exact version "2.7.11")

**Comment by alalek** [comment]
Thanks for update!
What is about CMake 3.4.3 and OpenCV 2.4.x? Does it work?

**Comment by ramnath-k** [comment]
Yes I was able to compile OpenCV 2.4.12.3 with CMake 3.4.3 successfully. Thanks for the pointers.

**Comment by alalek** [comment]
Thanks!

Unfortunately there is no easy workaround for Ubuntu 14.04 CMake. `find_package(PythonLibs)` doesn't work right with passed `PYTHON_LIBRARY` variable.
