### ISSUE TITLE
cvtColor YUV420p2BGR memory leaks

### ISSUE THREAD

**Issue by GJChen919** [opencv/opencv#6033]
I downloaded the opencv3.0 / opencv3.1 iOS framework, and wrote the code like this:

```
+ (UIImage *)YUV420p2BGRwithImage:(UIImage*)inputImage {
    cv::Mat mat = [inputImage CVGrayscaleMat];
    if(mat.empty()){
        return [UIImage imageWithCVMat:cv::Mat()];
    }
    cv::Mat dstMat;
    cv::cvtColor(mat, dstMat, CV_YUV420p2BGR);
    UIImage *image = [UIImage imageWithCVMat:dstMat];
    dstMat.release();
    mat.release();
    return image;
}
```

The cvtColor function causes the memory leaks clearly.
_Developing environment: OSX El Capitan 10.11.3, xcode 7.2 for bridging the swift interface used_
_Testing environment: iPad2 iOS 9.2_

**Comment by alalek** [comment]
More useful details are required.

Replace this code:
```
cv::Mat dstMat;
cv::cvtColor(mat, dstMat, CV_YUV420p2BGR);
UIImage *image = [UIImage imageWithCVMat:dstMat];
```
to this:
```
UIImage *image = [UIImage imageWithCVMat:mat];
```
Do you still have a leak? Where is source of leak?

**Comment by GJChen919** [comment]
Yeah, I replaced ever, No memory leak occured without cvtColor line.

**Comment by GJChen919** [comment]
I think it may miss the memory release inside from the reference of Unsafe(Mutable)Pointer<UInt8> (pointer converted by Swift) while Unsafe(Mutable)BufferPointer<Uint8>(certain array pointer converted by Swift) is released for some reason (maybe the function call inside the OpenCV).

I had made a YUV420p2RGB directly base on the formula in Swift and no leaks occurred.
