### ISSUE TITLE
No window popup to show images within a thread

### ISSUE THREAD

**Issue by sunstarchan** [opencv/opencv#6039]
I'm working on Mac OSX. I installed OpenCV 3.1.0 from source code built by default compiler. And I write a piece of code to test OpenCV functionality. My basic idea is to show a image sequence one by one decoded from a video. I define a function to show the image sequence. If I use the function directly, it works as expected. But if I create a thread to show the images, there is just one icon in Mac Dock, the image window doesn't popup. So is there any potential issue with a thread to show images. 

Here the code is
```
 1#include <iostream>
 2#include <thread>
 3#include <opencv2/opencv.hpp>
 4
 5void ShowImages(const std::string &path);
 6
 7int main(int argc, char** argv)
 8{
 9    if (argc != 2)
10    {
11      printf("usage: DisplayImage.out <Video_Path>\n");
12      return -1;
13    }
14
15    std::cout << "Start to display images" << std::endl;
16
17#if 0
18    ShowImages(string(argv[1]));
19#else
20    std::thread tShow(&ShowImages, std::string(argv[1]));
21    tShow.join();
22#endif
23
24    return 0;
25}
26
27void ShowImages(const std::string &path)
28{
29    int count = 0;
30    int mT = 1000/10;
31    char filename[255];
32
33    cv::namedWindow("Display Image", cv::WINDOW_AUTOSIZE);
34     for(;;)
35    {
36        sprintf(filename, "%s/%06d.png", path.c_str(), count);
37
38        printf("Display frame#: %s\n", filename);
39
40        cv::Mat image = cv::imread(filename, 1);
41        if (!image.data)
42        {
43          std::cout << "No more images, break now" << std::endl;
44            break;
45        }
46
47        cv::imshow("Display Image", image);
48        cv::waitKey(mT);
49
50        count++;
51    }
52
53}
```

**Comment by mshabunin** [comment]
Try to create a window in main thread before starting the second. Please, provide information returned by `cv::getBuildInformation()`

By the way, usually it is not a good idea to call GUI functions from threads other than main.

**Comment by johannesdeselaers** [comment]
I have exactly the same problem as @sunstarchan.
The code runs without problems on a virtual machine linux (i.e. images are shown from non-main thread using imshow()). But on osx, the imshow() (in the non-main thread) is ignored. After the thread(from which imshow() is called) finishes, the image window opens for a split second, before the program terminates.
Opening the window from the main thread did not help, unfortunately.
Here is my build information: [opencvBuildInformation.txt](https://github.com/Itseez/opencv/files/129344/opencvBuildInformation.txt)

**Comment by sunstarchan** [comment]
I downloaded the source code from official website, not from GitHub. I attached my build information
[BuildInformation.txt](https://github.com/Itseez/opencv/files/130012/BuildInformation.txt)

Most of the build information is the same as @johannesdeselaers 's. And the same result of no window popup

**Comment by mshabunin** [comment]
Looks like you use Cocoa window backend, there could be problems when working with windows and views from different threads: [Thread Safety Summary](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html)

I have doubts that thread-safe window handling can be implemented within current _highgui_ interface using [Cocoa backend](https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window_cocoa.mm). If you have different opinion - feel free to post your thoughts here.

You can also try to use [Qt backend]() (build OpenCV with Qt support), it should support working with windows from threads other than main.

**Comment by chyojn** [comment]
I have the same problem. 

mac os x, opencv 3.1 using the qt5 backend.

namedWindow in main thread, imshow in another thread which is created by std::thread, and the imshow is blocked.

two solution:
sol 1) call cvInitSystem before the namedWindow in the main thread, then imshow is ok.
sol 2) use cv::startLoop instead of std::thread to create the imshow thread.

I am not family with qt, does any one has some idea about why these two solutions work?
