### ISSUE TITLE
minEnclosingCircle in version3.1 is nearly a hundred times slower than version2.4.9

### ISSUE THREAD

**Issue by logic1988** [opencv/opencv#6041]
minEnclosingCircle in version3.1 is much slower than  version2.4.9
Tested in Mac OS X 10.11 and Xcode by following image and code:
output is:

> **minEnclosingCircle: 0.000142s** //in2.4.9
> **minEnclosingCircle: 0.011471s** //in3.1

![minenclosingcircle_bug](https://cloud.githubusercontent.com/assets/13864726/12702121/60a9614a-c859-11e5-9b69-7018da08eb9b.png)

```
void TestMinEnclosingCircle()
{
    struct Smaller
    {
        bool operator()( const vector<Point> & lx, const vector<Point> & rx ) const {
            return lx.size() > rx.size();
        }
    };

    cv::Mat bug = cv::imread("/Users/logic/Desktop/minEnclosingCircle_bug.png",0);

    vector< vector<Point> > contours;
    cv::findContours(bug, contours, CV_RETR_LIST, CV_CHAIN_APPROX_NONE);
    std::sort(contours.begin(),contours.end(),Xsmaller());

    size_t numberToFilter = 60;
    numberToFilter = std::min(numberToFilter, contours.size());

    clock_t t0 = clock();
    for (size_t i = 0; i < numberToFilter; i++)
    {
        float raidus = 0;
        cv::Point2f center;
        cv::minEnclosingCircle(contours[i], center, radius);
    }
    std::cout<<"minEnclosingCircle: "<<(double)(clock() - t0)/CLOCKS_PER_SEC<<"s";

}
```

**Comment by caraffi** [comment]
You should check if up to the timed cycle the results are the same, e.g. if the input to minEnclosingCircle is the same.

**Comment by logic1988** [comment]
Yes, I find that the new version of the code in minEnclosingCircle changed a lot compared to the old version, so I replaced the function as an older version, and the time consumption returns to normal. @caraffi

**Comment by RackhamLeNoir** [comment]
Maybe because the code in 2.4 is wrong: https://github.com/opencv/opencv/issues/6438
