### ISSUE TITLE
CMake error if source or bin path contains "++"

### ISSUE THREAD

**Issue by bastian-weber** [opencv/opencv#6046]
If the source or binary path in cmake contain the character sequence "++" (without quotation marks) I get a cmake error when trying to create a project for OpenCV 3.1:

    CMake Error at cmake/OpenCVUtils.cmake:76 (if):
      if given arguments:

        "G:/Desktop/C++ projects/project" "MATCHES" "^G:/Desktop/C++ projects/sources" "OR"     "G:/Desktop/C++ projects/project" "MATCHES" "^G:/Desktop/C++ projects/project"

      Regular expression "^G:/Desktop/C++ projects/sources" cannot compile
    Call Stack (most recent call first):
      CMakeLists.txt:437 (ocv_include_directories)

Apparently this line inside OpenCVUtils causes the problem:

`if("${__abs_dir}" MATCHES "^${OpenCV_SOURCE_DIR}" OR "${__abs_dir}" MATCHES "^${OpenCV_BINARY_DIR}")`

I noticed the problem because I have a folder called "C++ Projects" where I keep C++ projects and libraries.

**Comment by bastian-weber** [comment]
The same problem seems to exist at line 94 in the same file.

I was able to work around the problem by replacing lines 76 and 94 with the following code:

    string(REPLACE "++" "\\+\\+" __abs_dir_escaped ${__abs_dir})
    string(REPLACE "++" "\\+\\+" OpenCV_SOURCE_DIR_ESCAPED ${OpenCV_SOURCE_DIR})
    string(REPLACE "++" "\\+\\+" OpenCV_BINARY_DIR_ESCAPED ${OpenCV_BINARY_DIR})
    if("${__abs_dir_escaped}" MATCHES "^${OpenCV_SOURCE_DIR_ESCAPED}" OR "${__abs_dir_escaped}" MATCHES "^${OpenCV_BINARY_DIR_ESCAPED}")

However, I don't know if this is a very elegant solution and if there might not be other characters that cause a similar problem.

**Comment by gruenich** [comment]
I propose to use `FIND` like here:

    string(FIND "${OpenCV_SOURCE_DIR}" "${__abs_dir}" strPosSrc)
    string(FIND "${OpenCV_SOURCE_DIR}" "${__abs_dir}" strPosBin)
    if (strPosSrc EQUALS 0 OR strPosBin EQUALS 0)

**Comment by alalek** [comment]
This issue has a low chance to be resolved.
1) In general there is no problem for user to use directories without "+", "spaces", "brackets", other special or non-ASCII symbols.
2) CMake language is not very powerful, so please don't make it unreadable by replacing one line to three lines + new temporary variables.
3) There are a lot of "broken" places (there are many build configurations, with and without 3rdparty parts).
4) Without automatic test for this, any related fixes will be broken again and again.

**Comment by StevenPuttemans** [comment]
People should tend to learn not to use spaces and symbols inside paths used for software programming or handling. It tends to break a lot more than just CMAKE so just stay away from it. Most simple solution is to make a folder like `c:/projects/cpp/` or something similar and all your issues are gone...
