### ISSUE TITLE
Compile error OpenCV 3.1 Visual Studio 2010

### ISSUE THREAD

**Issue by kmteam** [opencv/opencv#6094]
I got the  following errors when I try to compile OpenCV from sources, with nonfree modules and OpenGL support.

> Error	67	error C2668: 'pow' : ambiguous call to overloaded function	C:\Utils\OpenCV\opencv3.1\opencv_contrib\modules\line_descriptor\test\test_matcher_regression.cpp	126

> Error	69	error C2668: 'pow' : ambiguous call to overloaded function	C:\Utils\OpenCV\opencv3.1\opencv_contrib\modules\line_descriptor\perf\perf_matching.cpp	104

> Error	68	error LNK1104: cannot open file '..\..\lib\Debug\opencv_bioinspired310d.lib'	C:\Utils\OpenCV\opencv3.1\build.nonfree\modules\bioinspired\LINK

> Error	70	error LNK1104: cannot open file '..\..\lib\Debug\opencv_bioinspired310d.lib'	C:\Utils\OpenCV\opencv3.1\build.nonfree\modules\bioinspired\LINK

Any idea how to solve it?
May be is a bug?

**Comment by kmteam** [comment]
It seems that modifying the line 
` result += (uchar) ( bin_vector[i] * pow((float)2, i ) );`
 by
 #`result` += (uchar) ( bin_vector[i] * pow(2**f**, i ) );
forces to use pow(float,int) overload and  " 'pow' : ambiguous call to overloaded function" error disappears.

In spite of this, I continue receiving the message :
> Error	66	error LNK1104: cannot open file '..\..\lib\Debug\opencv_bioinspired310d.lib'	C:\Utils\OpenCV\opencv3.1\build.nonfree\modules\bioinspired\LINK

Finally as I don't need bioinspired module, I disabled it from CMake and library compiled successfully!

**Comment by StevenPuttemans** [comment]
> forces to use pow(float,int) overload and " 'pow' : ambiguous call to overloaded function" error disappears.

Could you supply the fix through a PR? It will help others to advance faster.

> Finally as I don't need bioinspired module, I disabled it from CMake and library compiled successfull

That indeed the best way to go for now :)
