### ISSUE TITLE
No function for Radon transform

### ISSUE THREAD

**Issue by Aravind-Suresh** [opencv/opencv#6099]
I have searched the docs as well as some online sources. But I couldn't find a function for Radon transform. I would like to take up this issue and contribute.

**Comment by StevenPuttemans** [comment]
It would be nice to see that new functionality is contributed. Go ahead, make an implementation and link your PR to this place so people can help you out where necessary!

BTW take a look [here](http://dsp.stackexchange.com/questions/470/whats-the-difference-between-the-hough-and-radon-transforms). For me it is a strong indication that you could adapt the hough transform to a more generalized Radon transform!

**Comment by Aravind-Suresh** [comment]
I implemented a basic version of it.

https://github.com/Itseez/opencv/pull/6108

**Comment by tomasfernandezm** [comment]
@Aravind-Suresh have you implemented the inverse radon transform? If not, do you have any bibliography i could use to implement it?
Thanks

**Comment by Dugnom** [comment]
Does it make sense to keep this open, if the feature is implemented?
