### ISSUE TITLE
Add Golang interface

### ISSUE THREAD

**Issue by pshoukry** [opencv/opencv#6109]
I need a Golang interface to the 2.x API. I have forked the repository and checking the contribution guidelines. I am checking swig and will work on my fork on implementing a Golang interface. It has been sometime since I used cmake and it's my first time to use swig so there will be dragons.

**Comment by dtmoodie** [comment]
Go can call C code.  Why not use the C interface?

**Comment by pshoukry** [comment]
Please check [here](http://answers.opencv.org/question/17546/opencv-will-drop-c-api-support-soon/)

and i quote 

> Shervin is right, the C API is not developed for a long time. All the new stuff has the C++ API, and it is not backported to the C. So, C API becomes obsolete and causes pain in the neck, since it should be maintained. Thus, the decision is made to mark it as deprecated. But let me clarify the point:

**Comment by dtmoodie** [comment]
Interesting.  When I worked with Go before, the only way I could interface to it was with a pure C interface.  Has this changed?  It may be because my team mates were C nazis, so they didn't bother looking at C++.  I'd be interested in seeing how this works.

**Comment by pshoukry** [comment]
It doesn't really directly call it its more of SWIG wrapping the C++ code:

from there site:

> SWIG is a software development tool that simplifies the task of interfacing different languages to C and C++ programs. In a nutshell, SWIG is a compiler that takes C/C++ declarations and creates the wrappers needed to access those declarations from other languages including Perl, Python, Tcl, Ruby, Guile, and Java. SWIG normally requires no modifications to existing code and can often be used to build a usable interface in only a few minutes.

Go has native support of swig please check [Go build](https://golang.org/src/cmd/go/build.go?h=swig#L3248) and [swig](http://www.swig.org/Doc3.0/Go.html) 

Yeah me too :)

**Comment by pshoukry** [comment]
Yes this is the approach I was trying to do, but I got pretty busy and couldn't complete it so I used more micro services approach using a simple python service do the processing I needed.

**Comment by deadprogram** [comment]
Hello, everyone. I've have been working on an OpenCV 3.x interface for Golang the repo is here: 

https://github.com/hybridgroup/go-opencv3

Instead of using SWIG, it uses C wrappers around the C++ classes to obtain interfaces that can be used from Golang.

Feedback and collaboration wanted!

**Comment by dkurt** [comment]
I believe we can close this issue due https://github.com/hybridgroup/gocv exists thanks to @deadprogram.
