### ISSUE TITLE
Build with opencv 3.1 in ios failed because of the enum name

### ISSUE THREAD

**Issue by canius** [opencv/opencv#6114]
There is a conflict in stitching/detail/blenders.hpp line 63:
    enum { NO, FEATHER, MULTI_BAND };

The enum name "NO" is conflict with the build-in BOOL type "NO" in iOS.
So an error occurred :
/opencv/Pods/OpenCV/opencv2.framework/Headers/stitching/detail/blenders.hpp:63:12: Expected identifier
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/objc/objc.h:74:13: Expanded from macro 'NO'

**Comment by alalek** [comment]
Related #6047

If you don't need this module then try to replace `opencv.hpp` include to list if required modules.

**Comment by jmbapps** [comment]
I had a similar issue with OS X, they said they would not fix that either.  It was a conflict with an Apple macro 'check' and it was conflicting with a bool called 'check'.  I imported the opencv files before the Foundation/Foundation.  Try importing the opencv files before UIKIT/UIKIT in your ViewController and see if that helps.  These guys love their 'wontfix' and said the same to me, so I figured it out myself.  Good luck.  Also if you are using Xcode, just download the iOS framework and add it to your project.  I have a couple of apps that use the opencv framework in iOS.

**Comment by mshabunin** [comment]
Some kind of workaround has been introduced in PR #6161 - it will give you compilation warning with the explanation.

**Comment by avanish** [comment]
It was still giving me the same error even when I imported opencv.hpp above UIKit. Importing it in .mm instead of .h works too. Or you could follow the one suggested by alalek.

Instead of importing opencv2/opencv.hpp, you can import the necessary modules separately.

**Comment by MuFengYi** [comment]
<img width="713" alt="d9ccb514-56b8-4afb-97f8-5c9c2679b1b4" src="https://cloud.githubusercontent.com/assets/11486628/23892458/a8d88654-08d5-11e7-8b76-a3c5f26da1a0.png">
need import this.like this png.

**Comment by ctliu3** [comment]
In 3.2.0, I also encounter this problem. I comment the corresponding modules in `opencv.hpp` and it works, at least for building. But I haven't test the exactness.

**Comment by amayatsky** [comment]
I have moved #import <opencv2/opencv.hpp> above all other imports as suggested and that did the trick.

**Comment by mnh-aj123** [comment]
@amayatsky I got one problem i  am converting javacv mat to opencv mat using 
`
opencv_core.Mat grabbedImage = converter.convert(grabber.grab())
Mat x=new Mat(grabbedImage.address());
`
i need a clone of x but when i clone , my system hangs , any solution for it ?

**Comment by IgorKovr** [comment]
if you're not using **stitching.hpp** just comment the line 86 of **opencv.hpp**
//#include "opencv2/stitching.hpp"

**Comment by VladimirKulyk** [comment]
```
#ifdef __cplusplus
#undef NO
#undef YES
#import <opencv2/opencv.hpp>
#endif
```

**Comment by mkyung** [comment]
On 3.4.4 issue still exists,

In the .mm file I moved `#import <opencv2/opencv.hpp>` above `#import <Foundation/Foundation.h>` and it worked

**Comment by DongHeZheng** [comment]
You can change opencv_modules.hpp like this.

#ifdef USE_OPENCV_STITCHING
#define HAVE_OPENCV_STITCHING
#endif

So, if you want to use stitching module, you can define USE_OPENCV_STITCHING, otherwise I can avoid such this compiling problem.
But, personally, I guess OpenCV teams have to change this issue.

**Comment by pmachowski** [comment]
None of the above solutions worked for me in the RN 62 with autolinking. I ended up writing postinstall script in my Podfile that disables stitching module.

`def opencv_post_install (installer)
  opencv_path = installer.config.project_pods_root + 'OpenCV/opencv2.framework/Headers/opencv.hpp'
  if File.exist?(opencv_path)
    puts "POSTINSTALL::patch OpenCV opencv.hpp header file"
    text = File.read(opencv_path)
    new_contents = text.gsub('#include "opencv2/stitching.hpp"', '//#include "opencv2/stitching.hpp"')
    File.open(opencv_path, "w") {|file| file.puts new_contents }
  else
    puts "POSTINSTALL::OpenCV patch NOT possible. No file at:#{opencv_path}"
  end
end`

**Comment by skizzo** [comment]
@pmachowski you seem to have experience with OpenCV in RN, so maybe you know what's going on in my case (trying to port an "old" RN 0.59 project to RN 0.61.5).

I'm getting a build error for the line in m .pch file (line #29) where I import OpenCV the first time:

<img width="852" alt="Screenshot 2020-06-12 at 10 33 34" src="https://user-images.githubusercontent.com/2892572/84489064-6a382d00-aca1-11ea-8627-a34b9473a7b1.png">

<img width="681" alt="Screenshot 2020-06-12 at 10 53 12" src="https://user-images.githubusercontent.com/2892572/84489163-8b008280-aca1-11ea-9100-b3b40c99d578.png">

Any help would be highly appreciated!

**Comment by Nododo** [comment]
> ```
> #ifdef __cplusplus
> #undef NO
> #undef YES
> #import <opencv2/opencv.hpp>
> #endif
> 
> //other imports
> ```

thank you，my god
