### ISSUE TITLE
cmake executing binary of target architecture to find version

### ISSUE THREAD

**Issue by daltonfury42** [opencv/opencv#6116]
I am cross-compiling cmake with CUDA support. CUDA is a build dependency of OpenCV and all the libraries and binaries (of target architecture) belonging to CUDA are present in correct locations. 

FindCUDA.cmake successfully finds them (relative to CMAKE_FIND_ROOT_PATH specified in the toolchain file), but it is trying to execute a binary to get the version of CUDA installed. If OpenCV was not being cross compiled, this would have worked. But when cross compiling, cmake cannot execute the binary because it is of a different architecture. Hence cmake is unable to find CUDA when cross-compiling.

So [this line](https://github.com/Itseez/opencv/blob/master/cmake/FindCUDA.cmake#L603) fails, and hence the next line resuts in an error:
```

run/media/fury/storage/yocto/poky/build/tmp/sysroots/jetson-tk1-l4t/usr/local/cuda/bin/nvcc: /run/media/fury/storage/yocto/poky/build/tmp/sysroots/jetson-tk1-l4t/usr/local/cuda/bin/nvcc: cannot execute binary file
CMake Error at cmake/FindCUDA.cmake:604 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  cmake/OpenCVUtils.cmake:24 (find_package)
  cmake/OpenCVDetectCUDA.cmake:16 (find_host_package)
  cmake/OpenCVFindLibsPerf.cmake:32 (include)
  CMakeLists.txt:526 (include)


CMake Error at cmake/FindCUDA.cmake:605 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  cmake/OpenCVUtils.cmake:24 (find_package)
  cmake/OpenCVDetectCUDA.cmake:16 (find_host_package)
  cmake/OpenCVFindLibsPerf.cmake:32 (include)
  CMakeLists.txt:526 (include)

```

**Comment by jet47** [comment]
You should use host CUDA toolkit with cross-compilation support, not CUDA toolkit installed on target sysroot. See http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#cross-platform for instructions.
