### ISSUE TITLE
decomposeHomographyMat returns rotation matrices with determinants of -1

### ISSUE THREAD

**Issue by bellz867** [opencv/opencv#6133]
Hello,
I have found instances where the rotations returned from the decomposeHomographyMat have determinants of -1, which is not a valid rotation matrix. I think all you need to do is negate the matrices but thought you might want to know.
Thanks and please let me know when there is a fix.

**Comment by mshabunin** [comment]
Please, provide a minimal example code to reproduce this issue. Which version do you use, 2.4 or 3.x?
