### ISSUE TITLE
A runtime error occur in the OpenCV was installed by the NuGet

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#6153]
## Phenomenon
I tried to install OpenCV 3.1 using NuGet. 
I can install OpenCV 3.1. But, a runtime error occur in the OpenCV was installed by the NuGet.
I investigated this issue. As a result, I found that an exception occurs in **opencv_world310.dll**.

This problem occurs in only Release build(Win32/x64).
On the other hand, this problem does not occur in Debug build(Win32/x64).
And, this issue occurs in VS2013 and VS2015.

## Procedure
1. make Visual Studio project.
1. install [OpenCV 3.1 package](https://www.nuget.org/packages/opencv3.1/1.0.0) via NuGet.
1. build this project.
1. execute this program.

## Sample code
```
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <iostream>

int main(int argc, const char* argv[])
{
    cv::Mat img(cv::Size(320, 240), CV_8UC3, cv::Scalar(0, 0, 255));
    cv::namedWindow("image", cv::WINDOW_AUTOSIZE);
    cv::imshow("image", img);
    cv::waitKey(0);
    cv::destroyAllWindows();
    return 0;
}
```

## My environment
- Windows 10 Pro 64bit
- Visual Studio 2013 Update 5(Visual Studio 2015 Update 1)

**Comment by atinfinity** [comment]
I don't know whether [this NuGet package](https://www.nuget.org/packages/opencv3.1/) is official package. 
So, forgive me if I’m wrong.

**Comment by alalek** [comment]
We don't maintain this package

**Comment by grapeot** [comment]
I am the maintainer of this package. It's unofficial. And I will make it explicit in the description.
