### ISSUE TITLE
Add list of cmake option for compiling from source.

### ISSUE THREAD

**Issue by tankmohit** [opencv/opencv#6156]
Please add README or INSTALL for installation instructions. add options available for cmake on official site or any file. its very hard to compile full functional libs without known options.

**Comment by alalek** [comment]
There are some installation tutorials: refer to documentation.

> its very hard to compile full functional libs without known options

Default values are good in the most cases.

You can start learn options from [here](https://github.com/Itseez/opencv/blob/3.1.0/CMakeLists.txt#L162-L281).
More advanced hacking is possible with help of this command: `cmake -LAH` (run from build directory).
