### ISSUE TITLE
Dense disparity output in color 

### ISSUE THREAD

**Issue by adamib** [opencv/opencv#6158]
Hi, 

 I have developed an OpenCV program to compute the disparities of the image using StereoSGBM and I got the output in grayscale, so is there any idea how to get output in color scale using the same algorithm SGBM? 

I would appreciate any suggestion.

**Comment by mshabunin** [comment]
Disparity map has only one channel - each pixel represents the disparity level. Probably you want the [applyColorMap](http://docs.opencv.org/master/d3/d50/group__imgproc__colormap.html#gadf478a5e5ff49d8aa24e726ea6f65d15) function - please check usage example [here](https://github.com/Itseez/opencv_contrib/blob/565bcab2490f2275c0e855c7e5e61b8212806722/modules/structured_light/samples/pointcloud.cpp#L262).
