### ISSUE TITLE
http://opencv.org/platforms/cuda.html

### ISSUE THREAD

**Issue by sammoes** [opencv/opencv#6177]
Hi, I am wondering if this example here: http://opencv.org/platforms/cuda.html is supposed to work?
My compiler stops because cv::gpu::threshold(src, dst, 128.0, 255.0, CV_THRESH_BINARY); seems to want cv::Mat's as parameter values ("use explicit download()") but that would defeat the purpose since threshold is supposed to run on the GPU. I hope I am wrong.

**Comment by Dikay900** [comment]
```
        cv::Mat src_host = cv::imread("file.png", CV_LOAD_IMAGE_GRAYSCALE);
        cv::gpu::GpuMat dst, src;
        src.upload(src_host);

        cv::gpu::threshold(src, dst, 128.0, 255.0, CV_THRESH_BINARY);
```
src is a GpuMat in this example which will compile for cv::gpu:threshold / cv::cuda::threshold.
src is filled with the Mat src_host.

Your error messages sounds like it stopped here
`cv::Mat result_host = dst;`
This line should be wrong since i used to do something like this.
```
cv::Mat result_host;
dst.download(result_host);
```

**Comment by sammoes** [comment]
Yes, so the example is wrong? In fact I also used download for dst but the (same) error persists on threshold().

**Comment by Dikay900** [comment]
which version of opencv are you using? 2.4 or 3.x?

**Comment by sammoes** [comment]
Thanks. I thought so. I must say, I don't have the contrib branch so that many of the samples in the build/bin folder don't work.
I have OpenCV 3.1
Can you get a correct version and the CMakefile on there? It is kind of confusing since many files have moved. Is there a general overview of things you need to change when moving to 3.1?

**Comment by sammoes** [comment]
Seems like files moving to new folders. Thanks.

**Comment by mshabunin** [comment]
Updated the page.

**Comment by jet47** [comment]
In your example your are calling `cv::threshold` instead of `cv::cuda::threshold`.

**Comment by sammoes** [comment]
this was not my example
