### ISSUE TITLE
Error Opencv on armeabi-v7a-hard

### ISSUE THREAD

**Issue by slegall56** [opencv/opencv#6200]
Hi, 
I have to compile a personal lib on armeabi-v7a-hard. This personal lib depends on Opencv. 
Compilation works well but during execution, some opencv's function works and some others don't such as :
- detectMultiScale crash
-  resize : could not find interpolation method 
- and so one ...

When I compile my personal lib on armeabi-v7a everything works fine. Unfortunately, for time optimization, my personal lib need to be compiled on armeabi-v7a-hard

Any idea ?

**Comment by mshabunin** [comment]
Please, provide minimal reproducing example.
