### ISSUE TITLE
Issues with memory leaks in OpenCV 3.1.0

### ISSUE THREAD

**Issue by tllv** [opencv/opencv#6203]
We are testing our own code with boost tests and we need to check the unit tests for memory leaks. Meanwhile I patched OpenCV 3.1.0 at several positions to remove memory leaks:

1. The instance management in macro CV_SINGLETON_LAZY_INIT_ in precomp.hpp changed from
         static TYPE* volatile instance = NULL;
    to
         static std::unique_ptr<TYPE> instance;

2. This is a bug for me, complete unexpected behavior, and got a lot of rofl in our software department:
    cv::__termination = true
   Please remove this flag from the code! Why should one disable memory free's when unloading the library???

3. Now I'm searching for two more memory leaks. One seems to be a pointer (4 byte on 32 bit systems and 8 byte on 64 bit systems) and the other one a 48 byte object.

If somebody knows about the last two objects please answer and spare me a lot of work to find them.

Thank you.

**Comment by alalek** [comment]
Please refer to notes from commits with these changes / original pull requests (use "blame" tool) and related issues.

1. Try to google "static initialization order fiasco" and many issues with "pure virtual call". These "single" leaks are not critical at all, so you way is just suppress these entries in your tool.

2. During process [exit](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx) Windows terminates all threads before DLLs unloading (`DLL_PROCESS_DETACH` notification). Cleanup procedures of some 3rdparty libraries (for example, OpenCL runtime DLLs) want response / resource releasing from their "worker" threads (which are terminated unconditionally) and hangs forever.
We can't fix this behaviour of Windows or 3rdparty libraries, so we add this workaround (for Win32 only).
Anyway you are free to propose better solution for this.

3. Please add more details here.

**Comment by tllv** [comment]
Thank you very much for your quick answer! 

1. I don't see what the "static initialization order fiasco" has to do with instances as static pointers vs std::unique_ptr, but I can understand that OpenCV needs to support lots of old compilers, while we are using VS2013 and gcc 4.8 (and newer, for Linux) together with c++11. I implemented this as patch of our OpenCV version to avoid false memory leaks.

2. I see the problem. Anyway the documentation of this "fix" in the code does not tell the real reason and I don't want to search for old change requests or bug reports when working with third party tools. Our "memory leak problem" is solved by removing the line from DllMain. I don't know if we could run into the same cleanup problems from the way we use OpenCV.

3. Meanwhile I hooked into the memory allocation with _CrtSetAllocHook and found the last object:
     cv::__initialization_mutex
   Another patch for our version of OpenCV is implemented and working fine.

My only problem is that I have to redo my patch list when we upgrade to a newer version in future.

**Comment by svebert** [comment]
@tllv: I have the same problem and interested in your solution. Can you make your patches public available?

**Comment by gast128** [comment]
Same problem here. I had to adjust OpenCV code and apply Meyer's singletons to get rid of them. While one can start an academic discussion if they are memory leaks or not, Visual Studio reports them and one can not differentiate between this noise and real ones.
