### ISSUE TITLE
Memory corruption on cv::JPEGDecoder::readData(cv::Mat&)

### ISSUE THREAD

**Issue by abhiguru** [opencv/opencv#6210]
GDB BT :  https://gist.github.com/abhiguru/bf4121681ffcdca63f0f

Code is using FB/folly for threading  and basically spawns a separate thread for each image on which the face detection is to be done.

future1 = folly::via(&cpuThreadPoolExecutor,
                                   std::bind(vcu::follyPerformDetection, *it.base(), frontalClassifiers[i], profileClassifiers[i], detectConfig.outWidth, detectConfig.outHeight, ioReaderWriter));

Code for face detection is pretty straight forward 

"
  cv::Mat imageMat = cv::imread(inputImage.path);
  cv::Mat grayMat;
  cvtColor(imageMat, grayMat, cv::COLOR_BGR2GRAY);
"

Any pointers on what might be the issue ? No two threads share the same image the only thing shared are the classifiers which too are not shared by 4 consecutive threads..

**Comment by alalek** [comment]
Run valgrind memory check (but there is restricted threading support) to get real reason of memory corruption.
Almost all OpenCV objects/algorithms are not thread safe (should not be shared between threads).

**Comment by abhiguru** [comment]
I ran Valgrind multiple times as but it seems the execution slows down too much too actually replicate the memory corruption, which happens in normal runs pretty consistently no OpenCV objects are shared between threads each thread loads its own classifier, its own image  and does detection.. It is during the loading of the image that the corruption happens 

https://gist.github.com/abhiguru/b9c284f79ea8d53c7714 

Thread code: 
https://gist.github.com/abhiguru/85b9416075bf30691880
GDB seems to suggest it happens on cv::imread 

If there is a specific way in which you would like Valgrind ran do let me know, in the meanwhile I will keep retrying to check if it capture the error

**Comment by alalek** [comment]
We can't look at problem without normal standalone reproducer (with image data).

Try to disable (comment out) image processing, leave only execution of `cv::imread()` calls.
If you use OpenCV 3.0+ then try to disable OpenCL support (it may cause some failures for some OpenCL runtime).


> GDB seems to suggest it happens on cv::imread

GDB shows that `free` is called during `fclose` call - it is very strange.

**Comment by mshabunin** [comment]
@abhiguru , feel free to reopen the issue if you have more information and more compact reproducing example. You can try to run valgrind tool called `Helgrind` to analyse concurrent execution problems.
