### ISSUE TITLE
how to build opencv_contrib for andoid with opencv310 together

### ISSUE THREAD

**Issue by ardeal** [opencv/opencv#6215]
Hi 

I am trying to run face recognition on Android 6.0. at present I can build opencv for android on ubuntu 12.04, but I cannot build opencv_contrib for android with opencv3.1.0 together. Can you kindly tell me how to do that?

Best Regards,
Ardeal

**Comment by tzutalin** [comment]
Try this. It can build opencv + opencv_contrib for android
http://tzutalin.blogspot.tw/2016/01/installing-opencv-310-and-contrib-lib.html

**Comment by Aravind-Suresh** [comment]
I found these posts helpful when I tried building opencv_contrib module.
http://hujiaweibujidao.github.io/blog/2014/10/22/android-ndk-and-opencv-development-with-android-studio/

http://www.jayrambhia.com/blog/ndk-android-opencv/

**Comment by tzutalin** [comment]
Fix it
https://github.com/tzutalin/build-opencv-for-android

**Comment by mshabunin** [comment]
PR #6460 has added `--extra_modules` flag to the `platforms/android/build_sdk.py` script.

**Comment by thesunbird** [comment]
https://github.com/chaoyangnz/opencv3-android-sdk-with-contrib
