### ISSUE TITLE
predict_prob in opencv 3.1's RTrees class

### ISSUE THREAD

**Issue by smasoudn** [opencv/opencv#6227]
### System information
- OpenCV version: 3.0 / 3.1
- Host OS: Linux (Ubuntu 14.04)  / Windows 10
### In which part of the OpenCV library you got the issue?
- ml
- random decision trees (RTrees)
### Issue

while the method "predict_prob" was available in opencv 2.4 for probabilistic output of CvRTrees, this very useful method has been removed in opencv 3.0 and 3.1.
### Possible solutions

It would be great if developers provide users with a small note in the documentation on 

```
a) how some one can get confidence / probabilistic output from RTrees, or

b) how some one can access to the number of votes for each label.
```

**Comment by mrquorr** [comment]
I'm seeing how to add this feature. This should work only for classifiers right? Regression problems would have no use of this function.

**Comment by jacobdang** [comment]
@mrquorr Any update on adding this feature? I am also looking into fixing this issue.  Probabilistic or confidence output is a very important feature for ml application.

**Comment by mrquorr** [comment]
@jacobdang due to work increase and lack of interest I stopped developing it. I got so far as to getting a prototype done. I'll start working on it again on the 3rd.

**Comment by jacobdang** [comment]
@mrquorr Ok. To avoid waste of efforts I will not work on it until your patch has come out. Thanks.

**Comment by rspezialetti** [comment]
@jacobdang Hi, i'm also interessed in this feature. I need to get the confidency during a prediction with RTrees, have you found some tricks?

**Comment by jacobdang** [comment]
@rspezialetti A quick search on google gives this solution:
http://stackoverflow.com/questions/10358964/using-opencv-random-forests-is-there-any-way-to-obtain-the-confidence-level-f
Let us know how that works.

**Comment by rspezialetti** [comment]
@jacobdang This solution gives the confidency in multiclass classification but for OpenCV 2.4. I'm working with OpenCV 3.0.

**Comment by jacobdang** [comment]
@rspezialetti Sorry, then I am not sure about that.  If you can use an alternative random forest library please check this out which supports multithreading training and probabilistic output

https://github.com/tpetmanson/dfpar

**Comment by rspezialetti** [comment]
Thank you for the tip. I can solve my problem using opencv 3.0. In binary classification, if your labels are 1=positive and 0=negative, you can obtain confidence as sum_of_prediction/number_of_trees_in_forest.

**Comment by mrquorr** [comment]
I'm thinking about returning a matrix with number of trees for regression and number of classes for classification. That way all classes or all individual tree result can be accessed.

**Comment by rspezialetti** [comment]
Good idea!

**Comment by mrquorr** [comment]
Hey guys, sorry for taking so long. My computer got recently stolen and I had to catch up on some work. I'm expecting sometime this week to have a pull request ready.
