### ISSUE TITLE
Build opencv3.1 for android, but it's unable to use

### ISSUE THREAD

**Issue by tzutalin** [opencv/opencv#6242]
I tried to build opencv3.1 for android using ndk-r10e.

However, the opencv I bulit is unable to use. It will have segmentation fault when loading it on the fly.

Is something wrong with my build steps? Or should I add extra flag for Android L?

My build steps:
```
export ANDROID_NDK=[YourNDKPath]
cd $OPENCV
mkdir release_android
mkdir install
cd release_android
cmake -DANDROID_ABI=x86 -DCMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ -DCMAKE_INSTALL_PREFIX=../install $@ ..
make -j8
make install
```

Is something wrong with my build steps? Or should I add extra flag for Android L?

Env:
- OpenCV version: 3.1
- Host OS: Linux (Ubuntu 14.04)
- Target OS: Android L
- Android ndk-r10e

Thanks for any advices

**Comment by huang-qiao** [comment]
I ran into same issue recently, any solutions? I posted a question on opencv forum (http://answers.opencv.org/question/89995/the-environment-to-build-opencv-sdk-for-android-x86/)

How's the official opencv-android-sdk built? Which can be used without problems, I'd like to know what's different?

Thanks a lot!

**Comment by Aravind-Suresh** [comment]
I tried building opencv_contrib module using android-ndk. But I think both are similar. I found the following blog posts helpful:

http://hujiaweibujidao.github.io/blog/2014/10/22/android-ndk-and-opencv-development-with-android-studio/

http://www.jayrambhia.com/blog/ndk-android-opencv/

**Comment by alalek** [comment]
> How's the official opencv-android-sdk built?

It is built by this builder (for OpenCV 3.1):
http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/307

**Comment by mshabunin** [comment]
Please add some logs from `adb logcat`
