### ISSUE TITLE
ORB is not working

### ISSUE THREAD

**Issue by anik786** [opencv/opencv#6271]
- OpenCV version: 3.1.0
- Host OS: Linux Ubuntu 14.04

I wish to use ORB (http://docs.opencv.org/3.1.0/d1/d89/tutorial_py_orb.html#gsc.tab=0) on a 28*28 grayscale image (handwritten digits), where each pixel has a number from 0 to 255.

This is the code I used:

```
orb = cv2.ORB_create()
image = image.reshape(28, 28))
kp = orb.detect(image, None)
```

But I keep getting this error:

```
OpenCV Error: Assertion failed (depth == CV_8U || depth == CV_16U || depth == CV_32F) in cvtColor, file /home/yahya/Documents/_other_downloaded_apps/opencv/modules/imgproc/src/color.cpp, line 7935
Traceback (most recent call last):
  File "/home/yahya/Documents/hello.py", line 118, in <module>
    kp = orb.detect(image, None)
cv2.error: /home/yahya/Documents/_other_downloaded_apps/opencv/modules/imgproc/src/color.cpp:7935: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cvtColor
```

I also tried:

```
orb = cv2.ORB_create()
image = img_as_float(image.reshape(28, 28))
kp = orb.detect(image, None)
```

How can I do this and why am I getting this error?

**Comment by alalek** [comment]
Questions should go to http://answers.opencv.org

**Comment by anik786** [comment]
I have asked the question so far on there & stackoverflow! I really need an answer urgent as my assignment is due in tomorrow!

Many thanks!

**Comment by alalek** [comment]
> Assertion failed (depth == CV_8U || depth == CV_16U || depth == CV_32F)

This means that datatype is wrong.

Looks like this problem is not related to OpenCV at all. You use custom code `img_as_float` which is doing something wrong (possible it uses "double" (64F) datatype instead of "float" (32F))

**Comment by anik786** [comment]
Per your suggestion I did the following:

```
orb = cv2.ORB_create()
image = feature_x[0].reshape(28, 28).astype('float32')
kp = orb.detect(image, None)
```

But now I have the following error:
`OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /home/yahya/Documents/_other_downloaded_apps/opencv/modules/imgproc/src/color.cpp, line 7456
Traceback (most recent call last):
  File "/home/yahya/Dropbox/Computer Science/machine-learning-cs342/coursework/assignment2/assignment2.py", line 188, in <module>
    kp = orb.detect(image, None)
cv2.error: /home/yahya/Documents/_other_downloaded_apps/opencv/modules/imgproc/src/color.cpp:7456: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor
`

**Comment by alalek** [comment]
"reshape" is not "resize".
numpy arrays for images are 3D and your code create Mat with 28 channels
