### ISSUE TITLE
What is HOGDescriptor::groupRectangles supposed to do?

### ISSUE THREAD

**Issue by mlilien** [opencv/opencv#6309]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS:  Windows 10
- Compiler & CMake: msvc 2013 & CMake 3.4.3
### In which part of the OpenCV library you got the issue?

Examples:
- objdetect
- HOGDescriptor::detectMultiScale with useMeanshiftGrouping == false and hitThreshold == 1.01 on an image which includes an rectangle (object) with weight 1.013
### Expected behaviour

detectMultiScale return the rectangle with weight 1.013
### Actual behaviour
- before HOGDescriptor::groupRectangles gets called in HOGDescriptor::detectMultiScale the variables
  foundLocations and foundWeights include the rectangle with weight 1.013 and are of length 1.
- error: HOGDescriptor::groupRectangle returns empty foundLocations and foundWeights so HOGDescriptor::detectMultiScale returns with empty foundLocations and foundWeights
- if the variable hitThreshold is set to 0, I get a lot of false positive rectangles with my trained HOG detector. These false Positives are roughly equally distributed over the image. HOGDescriptor::groupRectangles returns only one location which is approximately the center of the image.
- What is HOGDescriptor::groupRectangles supposed to do? My proposal is to remove the call to HOGDescriptor::groupRectangles in HOGDescriptor::detectMultiScale when called with useMeanshiftGrouping == false. So the user can do the grouping himself.

Best Regards, Marcel

**Comment by LorenaGdL** [comment]
The hitThreshold does not control the grouping of rectangles. The finalThreshold (often referred to as the groupThreshold) does. You may have one rectangle of weight 1.013 and a set hitThreshold of 1.01, and end up with no detections if your grouping threshold is higher (let's say default 2.0).

I am right now running a HOGDescriptor with useMeanShifGrouping == false, and no issue is present on same specs (OpenCV 3.1, Win10, VS2013).

**Comment by mlilien** [comment]
Okay, but why is there grouping at all, when using useMeanshiftGrouping == false?

The case i described where hitThreshold is set to 0. In this case I get a lot of false positives for which HOGDescriptor::groupRectangles returns only one location which is approximately the center of the image. 
I don't get why HOGDescriptor::groupRectangles gets called at all, when using  useMeanshiftGrouping == false and I don't understand the result of HOGDescriptor::groupRectangles in this case either. 

Detection of multiple occurrences of an object in an image should be possible.

**Comment by LorenaGdL** [comment]
You can group rectangles without using mean shift algorithm (refer to the [docs](http://docs.opencv.org/master/d5/d54/group__objdetect.html#ga3dba897ade8aa8227edda66508e16ab9&gsc.tab=0), and to [source code lines 1881-1884] (https://github.com/Itseez/opencv/blob/master/modules/objdetect/src/hog.cpp)). So yes, groupRectangles is called even if useMeanshiftGrouping == false, and that's fine.

Once again, the hitThreshold does NOT control the grouping. Set the finalThreshold to 0, and then no grouping will be done. I don't know which is the exact issue with your described case, but I invite you to write some minimal code to reproduce it (you can provide code + sample image + trained model, for example).

**Comment by mlilien** [comment]
Yes, I get, that the hitThreshold does not control the grouping. I never questioned that. I questioned the behaviour of HOGDescriptor::groupRectangles.

I will try the setting of finalThreshold. Is there some official documentation what this parameter actually does?

Thank you.

**Comment by LorenaGdL** [comment]
Yes, finalThreshold == groupThreshold (when useMeanshiftGrouping = false). Check the old 2.4 [docs](http://docs.opencv.org/2.4/modules/gpu/doc/object_detection.html#gpu-hogdescriptor-detectmultiscale) (yes, new docs are still a little behind) and/or the previous referred source code lines to verify it.

**Comment by mlilien** [comment]
Setting finalThreshold to 0 works. Thanks again.

**Comment by mshabunin** [comment]
Lets keep it as a documentation issue.

**Comment by pwnorbitals** [comment]
Any updates about this one ? Might be closed now that the docs have been updated
