### ISSUE TITLE
cvtColor on a 3 channel Matrix with a 4 channel convert option crashes OpenCV 2 & 3 with IPP

### ISSUE THREAD

**Issue by tzickel** [opencv/opencv#6328]
### Please state the information for your system
- OpenCV version: 2.4 / 3.x
- Host OS: Windows 7

I Assume this happens on all systems with IPP.

### In which part of the OpenCV library you got the issue?
Examples:
- imgproc, cvtColor (with ipp)

### Expected behaviour

An assertion should be raised if trying to color convert an RGB matrix but asking an RGBA code.

### Actual behaviour

Bad memory access, process crashes.

### Additional description

Without IPP it doesn't crash.

### Code example to reproduce the issue / Steps to reproduce the issue
I tested it in cv2 python wrapper:
```python
import cv2
import numpy
cv2.cvtColor(numpy.zeros((2043, 13234, 3), dtype='uint8'), 1)
```

**Comment by tzickel** [comment]
Maybe this check should be separated according to the different cases (3 or 4):
https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/color.cpp#L7341

**Comment by rahulchhabra07** [comment]
I wish to work on this issue. Will let you know of progress made. Any leads will be highly appreciated.
Thanks.

**Comment by rahulchhabra07** [comment]
Done here: aede58c
Please have a look and let me know if this is fine.

**Comment by tzickel** [comment]
I think the code has a few more of those ifs in other code path worth investigating. Feel free to see if it fixes it

**Comment by rahulchhabra07** [comment]
Yes, you are right. There are more instances where the check isn't strict enough. Should I change all those checks?

**Comment by ilya-lavrenov** [comment]
The original problem has gone, but I made the conditions more strict.

**Comment by ilya-lavrenov** [comment]
Decided to leave as is, since such strict checks break some existing code. E.g.:
```
cvtColor(image, img, COLOR_BGR2GRAY);
``` 
where the actual conversion is determined via number of channels in source image and conversion code just says about destination format. This code works for `image` channels equal to either 3 or 4. But the checks will break this code and we will have to write:
```
cvtColor(image, img, image.channels() == 3 ? COLOR_BGR2GRAY : COLOR_BGRA2GRAY);
```
which is inconvenient.
