### ISSUE TITLE
windows install opencv3.1.0 debug error，while release success

### ISSUE THREAD

**Issue by Maple-Wang** [opencv/opencv#6347]
windows install opencv3.1.0 debug error，while release success

![debug](https://cloud.githubusercontent.com/assets/7234912/14132170/6330a08c-f675-11e5-8ba1-04b6806fa6cb.jpg)

**Comment by alalek** [comment]
1. Don't use screenshots for text
2. It is wrong configuration of your compiler (what compiler?). Read message about "sprintf" more carefully yourself
