### ISSUE TITLE
jpeg exif reader: option to control behaviour

### ISSUE THREAD

**Issue by ZTurlututu** [opencv/opencv#6348]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS: All
### In which part of the OpenCV library you got the issue?
- highgui
- imread with jpeg pictures

If the picture have exif informations for rotation, imread rotate the picture with jpeg_exif reader.
But previous opencv 3.1 didn't do that. The exif information are dependent of hardware and not standardized and not sure.
### Expected behaviour

Adding a optional parameter for jpeg reading to use or not use exifs informations.
### Actual behaviour

No choice possible and need to patch sources to add choice or disable exif reading for jpeg files.
### Code example to reproduce the issue / Steps to reproduce the issue

```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

// previously take a picture with a smartphone in landscape and in portrait.

int main()
{
    Mat img = imread("landscape.jpg", img);
    imwrite(save_land.jpg, img);

    img = imread("portrait.jpg", img);
    imwrite(save_port.jpg, img);

    return 0;
}
```

**Comment by alalek** [comment]
Reading of exif rotation info have been added (with tests). If it doesn't work then please add a sample image file.
Saving is not implemented and I believe it will not be added in the nearest future.

**Comment by alalek** [comment]
Well I read it again and understand the right question. I update the issue title

**Comment by ZTurlututu** [comment]
Ok. But before exif reader was added, lot of project was created with the fact of exif informations are not read by opencv.  This add trouble existing project when opencv is updated in theirs.

Exif reader work fine but perhaps from an existing code we don't want and adding a parameters to choose if use or not was been a better solution than force this adoption.

**Comment by RatTac** [comment]
I would definitely vote for an option to turn it off. Introduction of this lead to totally unexpected behaviour of my program and it took me a long time to actually understand that OpenCV was rotating the images without telling me. Just an example: Imagine you want to calibrate a camera setup and now OpenCV is silently rotating the images just because you put the camera into a horizontal mode. Then your calibration will be wrong. Actually I think the option should even be off by default. It will lead to many problems otherwise!

**Comment by riless** [comment]
It took me a long time to guess what's wrong with [my code](http://stackoverflow.com/questions/38617317/what-is-the-real-shape-of-this-image) too. 

I also vote for an option to turn it off. image should not be preprocessed on loading.

**Comment by araujom** [comment]
I vote for the turn off option. 
Don't want to increase the mess, but I don't think that was the right choice. Rotation based on exif should be possible by a flag and turned off by default.

**Comment by ruimartinsptl** [comment]
I vote to turn off too. I updated opencv yesterday and couldn't understand the images rotation on my considerable size project. This explains everything

**Comment by Avidereta** [comment]
Yes, the option to choose whether to turn on or not would be really useful.

**Comment by ArkadiuszRaj** [comment]
Agree, my project has been a bit destroyed when for "uncontrolled" way the JPEG are read. As a workaround I manually reset orientation flag in files with help of exiftool. But this is not desired solution. I prefer having controll on how the images are read. And so I started to look at the usage of IMREAD_UNCHANGED flag. Dissapointment here :/

The exifs code as it is implemented Today parses only JPEGs (not used for TIFFs). And it is embedded in JPEG decoder itself, not loadsave.cpp module.

I think more flexible solution would be to treat exif class as counterpart to the image decoder (any). This will allow to flip image on imread_ not decoder level, and give end user possibility to read exif tags (to for example parse RAW files tags). And the flag IMREAD_UNCHANGED will have true meaning :)

Next week I can spent some time to prepare appriopriate patch however do not want to make redudnand work if somebody else already started.

**Comment by ArkadiuszRaj** [comment]
PR created. 
New flag introduced: IMREAD_IGNORE_ORIENTATION / CV_LOAD_IMAGE_IGNORE_ORIENTATION. When used, exif orientation code is not executed leaving image untouched.

**Comment by baziz** [comment]
Can anyone confirm that 3-channel jpegs are loaded as 1-channel in Python when the flag is set?
