### ISSUE TITLE
Error in cv::cuda::meanShiftSegmentation ()

### ISSUE THREAD

**Issue by djebm2** [opencv/opencv#6349]
The error print is:
modules/core/src/matrix.cpp:1232: error: (-213) You should explicitly call download method for cuda::GpuMat object in function getMat_

```
image = cv::imread(imagePathes[cpt], CV_LOAD_IMAGE_UNCHANGED);
cv::cvtColor(image, image, CV_GRAY2RGBA);
cuImage.upload(image);
cv::cuda::meanShiftSegmentation(cuImage, cuSegmented, 20, 45, 3); // crashing here
cuSegmented.download(segmented);
```

This error could related to [that one](https://github.com/Itseez/opencv/issues/6231)

**Comment by jfkeller** [comment]
The second argument (cuSegmented in your case) to meanShiftSegmentation should be a Mat stored in host memory. It should not be a GpuMat

**Comment by alalek** [comment]
Documentation states that only **host** memory is accepted:
```
@param dst Segmented image with the same size and type as src (host memory).
```

GpuMat is not expected for `dst` param.

Changed bug -> feature.
