### ISSUE TITLE
Opencl linearpolar and lopolar

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#6377]
- OpenCV version: 3.1
- Host OS: Windows 10 VS 2013

Method logPolar and linearPolar using opencl

When opencl is activated first and desactivated this program give a wrong result :

```
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/core/ocl.hpp"
#include <iostream>

using namespace cv;
using namespace std;

int main(int argc, char* argv[])
{
cv::ocl::setUseOpenCL(true);    
UMat u1,u2;
    imread("f:/lib/opencv/samples/data/lena.jpg", CV_LOAD_IMAGE_GRAYSCALE).copyTo(u1);
    imread("f:/lib/opencv/samples/data/chicky_512.png", CV_LOAD_IMAGE_GRAYSCALE).copyTo(u2);

    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 61,  CV_INTER_LINEAR);
    imwrite("u2FirstTrytrueAndFalse.png",u2);
    imshow("u2b((ocl=false))",u2);

cv::ocl::setUseOpenCL(false);    
    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 25,  CV_INTER_LINEAR);
    imwrite("u2SecondTrytrueAndFalse.png",u2);
    imshow("u2(ocl=true)",u2);

    imshow("src",u1);

    waitKey();
    return 0;
}
```

same program with opencl false at begining and true after give a good result  

```
int main(int argc, char* argv[])
{
cv::ocl::setUseOpenCL(false);    
UMat u1,u2;
    imread("f:/lib/opencv/samples/data/lena.jpg", CV_LOAD_IMAGE_GRAYSCALE).copyTo(u1);
    imread("f:/lib/opencv/samples/data/chicky_512.png", CV_LOAD_IMAGE_GRAYSCALE).copyTo(u2);

    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 61,  CV_INTER_LINEAR);
    imwrite("u2FirstTryFalseAndTrue.png",u2);
    imshow("u2b((ocl=false))",u2);

cv::ocl::setUseOpenCL(true);    
    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 25,  CV_INTER_LINEAR);
    imwrite("u2SecondTryFalseAndTrue.png",u2);
    imshow("u2(ocl=true)",u2);

    imshow("src",u1);

    waitKey();
    return 0;
}
```

I don't understand

**Comment by alalek** [comment]
Use `imwrite` for results into `.png` and attach them.
Are all OpenCV tests pass (OCL_*)?

**Comment by LaurentBerger** [comment]
[opencv_perf_imgprocd.zip](https://github.com/Itseez/opencv/files/211404/opencv_perf_imgprocd.zip)
![u2secondtrytrueandfalse](https://cloud.githubusercontent.com/assets/3591626/14405403/cec454c6-fe8e-11e5-8ee5-e3874dcef2f3.png)
![u2firsttryfalseandtrue](https://cloud.githubusercontent.com/assets/3591626/14405404/cec6fe24-fe8e-11e5-9d08-48a98e039d66.png)
![u2firsttrytrueandfalse](https://cloud.githubusercontent.com/assets/3591626/14405405/cec9e7ce-fe8e-11e5-81c3-26d2edd62d0f.png)
![u2secondtryfalseandtrue](https://cloud.githubusercontent.com/assets/3591626/14405406/cece1740-fe8e-11e5-8b93-5cf32f92bb8d.png)

**Comment by sturkmen72** [comment]
```
    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 61,  CV_INTER_LINEAR);
    linearPolar(u1, u2, Point(u1.cols / 2, u1.rows / 2), 25,  CV_INTER_LINEAR);
```
the parameters is different 61-25

**Comment by LaurentBerger** [comment]
Yes there is no problem with these parameters it's only to check called linearpolar give differents results with or without opencl

**Comment by ohnozzy** [comment]
Change UMat to Mat solve the problem.
I'm trying to figure out why UMat fails. 
Is ocl designed to support UMat?

**Comment by ohnozzy** [comment]
linearPolar internally calls
```
void cvLinearPolar( const CvArr* srcarr, CvArr* dstarr, 
CvPoint2D32f center, double maxRadius, int flags )
```
which use a legacy class CvMat. 
It looks like there is something wrong in the conversion path UMat<->Mat<->CvMat. The function works if cvLinearPolar is rewritten with Mat.

Another thing need to point out is that, there is no OpenCL code in cvLinearPolar except the last line,
`cvRemap( src, dst, mapx, mapy, flags, cvScalarAll(0) ); `
which has a OpenCL branch. 
However, even that OpenCL branch in cvRemap is not triggered, because cvLinearPolar pass CvMat to it.

I'm going to rewrite cvLinearPolar/LogPolar with a Mat and a UMat version. The UMat version is to advantage of the OpenCL routine in cv::remap.

**Comment by ohnozzy** [comment]
It turns out that even if the type is change to UMat, the OpenCL branch in remap cannot be triggered.
Because  `ocl_remap` require mapx & mapy to be CV_16SC1, in the code snippet below
```
 if (borderType == BORDER_TRANSPARENT || !(interpolation == INTER_LINEAR || interpolation == INTER_NEAREST)
            || _map1.type() == CV_16SC1 || _map2.type() == CV_16SC1)
        return false;

```
but cvLinearPolar/cvLogPolar create them as CV_32F

**Comment by alalek** [comment]
I investigated a problem. Problem code is here:
```
CvMat c_dst = _dst.getMat();
```
where
`_dst` is `OutputArray` from `UMat`
`_dst.getMat()` is temporary `Mat` which holds mapped data from `UMat`
after this statement "temporary Mat" is destroyed and data is unmapped. `CvMat c_dst` holds only invalid pointers after this.

Fix for these functions is:
```
Mat dst = _dst.getMat(); // don't inline this, it holds mapped UMat data for CvMat
CvMat c_dst = dst;
```

The main question is how to detect/find and fix other broken functions.

/cc @vpisarev

**Comment by ohnozzy** [comment]
I think we should remove the dependency on CvMat in the master branch.

**Comment by alalek** [comment]
I trying to catch locations with same problem by adding the move constructor:
```
#ifdef CV_CXX_MOVE_SEMANTICS
inline CvMat::CvMat(const cv::Mat&& m)
{
    CV_Assert(false && "Don't use: CvMat c_mat = _src.getMat();");
}
#endif
```

List of failures is here: http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/5383

**Comment by PkLab** [comment]
Hi guys it looks you had deeply investigated the functions... your opinion on #7009 (docs: exchange rho and phi) it's welcome
