### ISSUE TITLE
GPU memory not release in CornerBase

### ISSUE THREAD

**Issue by ogreen** [opencv/opencv#6389]
It would seem that there is memory that is being allocated in CornerBase (cudaImageProc module).
That memory does not seem to be released explicitly.
A simple solution could be to create a destructor that releases this memory:

https://github.com/Itseez/opencv/blob/3.1.0/modules/cudaimgproc/src/corners.cpp#L77

Easy issue to fix, if this is a problem.

**Comment by alalek** [comment]
Destructor of `GpuMat` is here:
https://github.com/Itseez/opencv/blob/3.1.0/modules/core/include/opencv2/core/cuda.inl.hpp#L116
CornerBase destructor is not required in this case.

Your problem is somewhere else.
