### ISSUE TITLE
Location of expanded documentation for opencv_annotation, opencv_visualisation and opencv_traincascade

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#6400]
I would like to request where the extra information should go. I would be eager to open up some wiki pages, due to the very ease of placing and editing stuff there. On the other hand, you guys might prefer that documentation goes inside the actual docs, and thus I am wondering where I would be adding those guides then?

@mshabunin or @alalek any guidelines?

**Comment by mshabunin** [comment]
Currently we have _opencv_traincascade_ and _opencv_createsamples_ are documented in form of [tutorial](http://docs.opencv.org/3.1.0/dc/d88/tutorial_traincascade.html). Probably we need separate mechanism for documenting applications (parsing _doc_ subfolder for each application).

**Comment by StevenPuttemans** [comment]
Thank you for the explanation. I would suggest then that I make documentation inside a doc folder which could be parsed. Is there any location, either opencv or opencv_contrib, where I can find an exact sample of that?
