### ISSUE TITLE
calib3d thin prism model incorrectly disallows distortion vector length above 12

### ISSUE THREAD

**Issue by Algomorph** [opencv/opencv#6412]
### System Info
- OpenCV version: 3.1.0 g2f4e38c
- Host OS: Linux (Ubuntu 15.10)
- Compiler & CMake: GCC 5.2.1 & CMake 3.4.1

### In which part of the OpenCV library you got the issue?
Examples:
- calib3d

Note: I encountered this bug using python bindings, but the bug is not python-binding-specific.

### Expected behaviour
After passing 14-parameter distortion coefficient vector (default output distortion vector length) and using the CV_CALIB_THIN_PRISM_MODEL flag (i.e. cv2.CALIB_THIN_PRISM_MODEL in python), the calibration should succeed and fill only the first 12 distortion coefficients.

### Actual behaviour
After passing 14-parameter distortion coefficient vector (default output distortion vector length) and using the CV_CALIB_THIN_PRISM_MODEL flag (i.e. cv2.CALIB_THIN_PRISM_MODEL in python), I got an error:
```
 Thin prism model must have 12 parameters in the distortion matrix
```
### Additional description

This is due to this segment of code here (currently line 1311 in calibration.cpp):
```C++
if(flags & CV_CALIB_THIN_PRISM_MODEL)
            if (distCoeffs->cols*distCoeffs->rows != 12)
                CV_Error( CV_StsBadArg, "Thin prism model must have 12 parameters in the distortion matrix" );
```
It was added with this pull: https://github.com/Itseez/opencv/pull/1458

It just needs the ```!=``` replaced with a ```<``` sign. In retrospect, the check just above it for the tiled model should also have ```< 14```, to accommodate any possible future expansions.

### Code example to reproduce the issue / Steps to reproduce the issue
(should be obvious / not needed)

**Comment by paroj** [comment]
I do not think this is a bug. Why would you pass in a 14 element vector when you only expect a 12 element output? 
The underlying issue is that `prepareDistCoeffs` allocates a 14 element vector if _distCoeffs is empty. It should rather match the requested number of coefficients.

**Comment by Algomorph** [comment]
@paroj, actually, it makes sense by design to have the vector always at the maximal length. If you always pass in and receive the same vector length, only with unnecessary coefficients at zero, it greatly simplifies code design. Otherwise you have to put in a ton of conditionals that control the length of the vector that you pass into the function.

The behavior should be consistent for all cases. If, like @paroj says, we make the algorithm always allocate the right number of coefficients, and otherwise expect input to have the right number of coefficients, then, when CV_CALIB_RATIONAL_MODEL or anything more sophisticated is not used, it should expect / allocate only 5 coefficients. CV_CALIB_ZERO_TANGENT_DIST just fixes the tangential coeffs at 0, so should we then accept only 3 coefficients? In principal, there is no difference... A much easier solution (and, IMHO, a better one) is to simply continue passing in / allocating 14 coefficients, just modify the conditionals. It doesn't really hurt to have a few benign extra zeroes at the end of input and output.

**Comment by BLDOH** [comment]
Why is this Bug rated as feature and not as Bug? At the moment I see no possibility to to do a thin prism calibration.
