### ISSUE TITLE
CMAKE using wrong path for TBB libraries

### ISSUE THREAD

**Issue by LarryK348** [opencv/opencv#6413]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Windows 10
- Compiler & CMake: VS2015, 3.4.0-rc2
### In which part of the OpenCV library you got the issue?
- CMake configure TBB
### Expected behaviour
- CMake produces correct path to TBB libraries
### Actual behavior
- CMake is apparently using an shortcut that is empty, build fails
### Code example to reproduce the issue / Steps to reproduce the issue

1) I am using CMAKE graphical user interface

2) TBB was installed from Intel Parallel Studio XE 2016 Update2 downloaded 4/9/2016

3) Prior to starting cmake-gui, tbbvars.bat is run and produces the following environment variables: TBBROOT=I:\OpenCV\deps\tbb\bin.. TBB_ARCH_PLATFORM=intel64\vc14 TBB_BIN_DIR=I:\OpenCV\deps\tbb\bin\ TBB_TARGET_ARCH=intel64 TBB_TARGET_VS=vc14

4) After running configure the second time in CMAKE, CMAKE reports: TBB_LIB_DIR: I:/OpenCV/deps/tbb/lib/intel64/vc14, that directory is empty, the correct location is: I:/OpenCV/deps/tbb/lib/intel64_win/vc14

Intel Parallel Studio XE 2016 Update 2 install creates a shortcut named "vc14" in the tbb/lib folder, but this shortcut apparently only works from Windows Explorer. Apps opening the shortcut get an empty directory.

CMake files should be updated to search for lib files below tbb/lib folder.

**Comment by mshabunin** [comment]
TBB downloaded from the [official site](https://www.threadingbuildingblocks.org/download#stable-releases) has libraries located in `lib/{intel64,ia32}/{vc10,...,vc14}` folders. You can try to manually set `TBB_LIB_DIR` variable during cmake run.

**Comment by LarryK348** [comment]
Thank you.
You are correct the distribution from threadingbuildingblocks.org does include the libraries in the correct locations. Unfortunately, none of the OpenCV installation or build documents reference that site.
The distribution I am using is from the "official" Intel site. It does not work with current build process.

**Comment by mshabunin** [comment]
Should be fixed in #7757
