### ISSUE TITLE
tree.avi in .../samples/data/tree.avi is corrupted (lost index)

### ISSUE THREAD

**Issue by garybradski** [opencv/opencv#6429]
tree.avi found in .../samples/data/tree.avi is corrupted (missing index or something). I've fixed it here
[tree.avi.zip](https://github.com/Itseez/opencv/files/225481/tree.avi.zip)

**Comment by alalek** [comment]
Is it necessary to change video metadata (codec, fps) and to add audio stream (with twice bandwidth than video bitrate)?
How we can reproduce an original problem? (I have some warning, but is it about encoded data, not index. Also result of `ffmpeg -i tree tree%05d.png` contains bad frames in the end)

Before:
```
  Metadata:
    creation_time   : 2005-04-29 17:09:53
  Duration: 00:00:29.53, start: 0.000000, bitrate: 355 kb/s
    Stream #0:0: Video: cinepak (cvid / 0x64697663), rgb24, 320x240, 15 fps, 15 tbr, 15 tbn, 15 tbc
```

After:
```
  Metadata:
    encoder         : Lavf57.26.100
  Duration: 00:00:30.17, start: 0.000000, bitrate: 522 kb/s
    Stream #0:0: Video: msmpeg4v2 (MP42 / 0x3234504D), yuv420p, 320x240, 153 kb/s, SAR 1:1 DAR 4:3, 6 fps, 6 tbr, 6 tbn, 6 tbc
    Stream #0:1: Audio: adpcm_ms ([2][0][0][0] / 0x0002), 44100 Hz, 2 channels, s16, 352 kb/s
```

/cc @vpisarev

**Comment by alalek** [comment]
There is truncated video with broken frames, but with same video codec (1.1 Mb):
[tree.avi.zip](https://github.com/Itseez/opencv/files/225814/tree.avi.zip)

```
$ ffprobe tree.avi
...
Input #0, avi, from 'tree.avi':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: 00:00:29.60, start: 0.000000, bitrate: 338 kb/s
    Stream #0:0: Video: cinepak (cvid / 0x64697663), rgb24, 320x240, 334 kb/s, 15 fps, 15 tbr, 15 tbn, 15 tbc
```
