### ISSUE TITLE
Requiring SSE3 by default

### ISSUE THREAD

**Issue by mmcco** [opencv/opencv#6466]
OpenCV currently enables the SIMD extension SSE3 by default throughout the build. This breaks the binary for very old AMD64/x86-64 machines; the newest SIMD extension supported by all such machines is SSE2.

There are a few computation-intensive programs that require SSE3 in order to improve performance. This isn't an entirely unreasonable approach because most machines running today support SSE3. However, it does complicate packaging. I don't know of a package manager that filters packages based on hardware extension support, so requiring a non-ubiquitous hardware extension forces package systems to ship non-functional binaries to users with old machines.

However, because OpenCV supplies a CMake option to disable SSE3, all package managers I could find (Debian, Fedora, openSUSE, FreeBSD) do so. We're planning on using it in OpenBSD as well.

The confusing part is that OpenCV already supports SSE3 in the core computation SIMD code, which autodetects hardware extensions using CPUID etc. and chooses the best one. Because of this, enabling SSE3 throughout the build may not be useful.

Do you suspect that you're getting a performance improvement from using SSE3 globally as well as in the core SIMD code? If not, would you consider removing `-msse3` from `CFLAGS` and `CXXFLAGS`?

**Comment by vladimir-dudnik** [comment]
is that still not resolved?

**Comment by alalek** [comment]
Resolved, wiki: https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options
