### ISSUE TITLE
Premature end of Image file

### ISSUE THREAD

**Issue by George19890617** [opencv/opencv#6468]
I use imread to read a image, I get a info "Premature end of Image file", but the mat is not empty. So how can I recognize these image files?
```
#include<iostream>
#include<opencv2/opencv.hpp>
#include<vector>
#include<fstream>
#include<iterator>
using namespace std;
using namespace cv; 

int main(){
    cv::Mat image = cv::imread("n00450335_17975.jpg");
    cout<<image<<endl;
    return 0;
}
```
I want to delete these image files, but no exception I can catch.

**Comment by mshabunin** [comment]
Please, add more information (platform, configuration) and the example image file.

**Comment by mshabunin** [comment]
It seem to be a libjpeg warning, probably your input image is broken, but not completely.

https://github.com/opencv/opencv/search?utf8=%E2%9C%93&q=JWRN_JPEG_EOF

**Comment by saketsneha** [comment]
@mshabunin https://user-images.githubusercontent.com/13913807/87640179-f7204b80-c763-11ea-801d-ec484a9de65e.jpg I am facing the same issue with the image
