### ISSUE TITLE
cv2.drawKeypoints python binding inconsistent with tutorial

### ISSUE THREAD

**Issue by zhlou** [opencv/opencv#6487]
### Please state the information for your system
- OpenCV version: 3.1.0 (commit 92387b1)
- Host OS: Linux (CentOS 7.2)

### In which part of the OpenCV library you got the issue?
features2d

### Code example
I'm following the [Python tutorial on SIFT](http://docs.opencv.org/3.1.0/da/df5/tutorial_py_sift_intro.html)
```python
 In [1]: import cv2

In [2]: img=cv2.imread('shot-4.jpg')

In [3]: gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [4]: sift=cv2.xfeatures2d.SIFT_create()

In [5]: kp=sift.detect(gray,None)

In [6]: img=cv2.drawKeypoints(gray, kp)
```
### Expected behaviour
`img` contains the contents of `gray` and key points overlay

### Actual behaviour
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a9ae08e17740> in <module>()
----> 1 img=cv2.drawKeypoints(gray, kp)

TypeError: Required argument 'outImage' (pos 3) not found
```

### Additional description
```python
cv2.drawKeypoints(gray, kp, img)
```
gives the expected behavior, which is inconsistent with the documentation and also not very pythonic

**Comment by 15757170756** [comment]
is this issue solved?

**Comment by bkmeneguello** [comment]
Seems to be documented to use None or an existing image as imageOut param

**Comment by QinZiwen** [comment]
```
kpimg = cv2.drawKeypoints(gray, kp, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
```

**Comment by eypros** [comment]
I am using opencv 3.4.1. My guess is that this argument is simply ignored at python bindings and the reason it's there is for consistent for the API across different languages (C++ to python in that case). So, maybe putting something like `None` might be OK but any value and any instance would suffice.

**Comment by MurphyLee2048** [comment]
@QinZiwen it helps, thx

**Comment by Raki22** [comment]
Acoording to Cherif BALI, you have to deal with the fct as a "procedure" so for instance: 

cv.drawKeypoints(input_image, keypoints, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS, outImage = input_image)

instead of : 

input_image = cv.drawKeypoints(input_image, keypoints, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
