### ISSUE TITLE
SIG: 9 on Core.compare

### ISSUE THREAD

**Issue by MatteCarra** [opencv/opencv#6488]
- OpenCV version: 3.1
- Host OS: Android 6.0
### Expected behaviour

Core.compare(gray0, new Mat(gray0.size(), gray0.type(), new Scalar((l + 1) \* 255 / N)), gray, Core.CMP_GE);
### Actual behaviour

Sending signal. PID: 1569 SIG: 9
### Additional description

Works with OpenCv 2_4_11
### Code example to reproduce the issue / Steps to reproduce the issue

http://pastebin.com/5J36CsC9

**Comment by MatteCarra** [comment]
Assertion failed (op == CMP_LT || op == CMP_LE || op == CMP_EQ || op == CMP_NE || op == CMP_GE || op == CMP_GT) in void cv::compare(cv::InputArray, cv::InputArray, cv::OutputArray, int), file /home/maksim/workspace/android-pack/opencv/modules/core/src/arithm.cpp, line 4988

core::compare_10() caught cv::Exception: /home/maksim/workspace/android-pack/opencv/modules/core/src/arithm.cpp:4988: error: (-215) op == CMP_LT || op == CMP_LE || op == CMP_EQ || op == CMP_NE || op == CMP_GE || op == CMP_GT in function void cv::compare(cv::InputArray, cv::InputArray, cv::OutputArray, int)

**Comment by MatteCarra** [comment]
Now I'm not sure it works in OpenCv 2_4_11

**Comment by liquidmetal** [comment]
I ran into this today. I tried using both a `Scalar` and a `Mat` as the second parameter but couldn't get it to work. @MatteCarra how did you get the detailed error log? I only get the following in `logcat`.

```
A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x9ef3ce51 in tid 29386
```

**Comment by davidmigloz** [comment]
Take a look to at this issue: #6247
