### ISSUE TITLE
seam finder bug: inconsistent results between iOS and windows

### ISSUE THREAD

**Issue by ruigangyang** [opencv/opencv#6504]
### Please state the information for your system
- OpenCV version: 2.4.9  and 3.1
- Host OS: iOS/ Windows 10

### In which part of the OpenCV library you got the issue?
image stitching --> Seam Estimation

### Expected behaviour
Find the correct seam between images;
### Actual behaviour
The graph-cut based seam finder is working fine under Windows, but it returns erroneous results under iOS.  the inputs and the parameter settings are identical in both programs. 

### Additional description
this issue has been tested and reproduced on opencv 2.4.9 and the latest opencv 3.1

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include <iostream>
#include <string>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/stitching/stitcher.hpp>


int _tmain(int argc, _TCHAR* argv[])
{
	cv::detail::GraphCutSeamFinder * finder = new cv::detail::GraphCutSeamFinder(cv::detail::GraphCutSeamFinderBase::COST_COLOR, 1000000.0f, 50000.0f);

	std::vector<cv::Mat> srcImages(2);
	std::vector<cv::Mat> masks(2); 

	

	cv::Mat imageIn, originSrc;

	cv::Rect roi(56, 153, 408, 300); // define the region of interests for blending
	imageIn = cv::imread("face-src.jpg"); 
	cv::Mat subImg(imageIn, roi);
	subImg.convertTo(srcImages[0], CV_32F);


	imageIn = cv::imread("face-template-2.jpg");
	imageIn.convertTo(srcImages[1], CV_32F);
	
	std::vector<cv::Point> corners(2);
	corners[0] = cv::Point(roi.x, roi.y);
	corners[1] = cv::Point(0, 0);
	
	// next load the mask for the first image; 
	imageIn = cv::imread("face-mask.png", 0);
	subImg = cv::Mat(imageIn, roi); 
	cv::erode(subImg, masks[0], cv::Mat()); 

	masks[1] = cv::imread("face-template-mask.png", 0); 

	finder->find(srcImages, corners, masks);

**Comment by alalek** [comment]
Dump `cv::getBuildInformation()` on both configurations and check JPEG codec version. You may hold JPEG codec by using `-DBUILD_JPEG=ON` CMake option (it will be built from OpenCV 3rdparty subfolder)

**Comment by ruigangyang** [comment]
thanks a lot for the quick reply. I attached the dump below. Is this a JPEG issue? Do you suggest that I recompile the opencv iOS version with the options you mentioned?

General configuration for OpenCV 2.4.9 =====================================
  Version control:               unknown

  Platform:
    Host:                        Darwin 15.4.0 x86_64
    Target:                      iOS
    CMake:                       3.0.1
    CMake generator:             Xcode
    CMake build tool:            /Applications/CMake.app/Contents/bin/cmakexbuild
    Xcode:                       7.3

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  (ver 7.3.0.7030029)
    C++ flags (Release):         -stdlib=libc++ -headerpad_max_install_names -fvisibility=hidden -fvisibility-inlines-hidden -fPIC   -fsigned-char -W -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -fno-omit-frame-pointer -DNDEBUG -O3 -fomit-frame-pointer -ffast-math  -DNDEBUG
    C++ flags (Debug):           -stdlib=libc++ -headerpad_max_install_names -fvisibility=hidden -fvisibility-inlines-hidden -fPIC   -fsigned-char -W -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -fno-omit-frame-pointer -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
    C flags (Release):           -fPIC   -fsigned-char -W -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -fno-omit-frame-pointer -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fPIC   -fsigned-char -W -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -fno-omit-frame-pointer -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      
    Linker flags (Debug):        
    Precompiled headers:         NO

  OpenCV modules:
    To be built:                 core flann imgproc highgui features2d calib3d ml nonfree objdetect video contrib legacy photo stitching videostab world
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 androidcamera dynamicuda gpu java ocl python superres ts viz

  GUI: 
    Cocoa:                       YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.7)
    JPEG:                        build (ver 62)
    PNG:                         build (ver 1.5.12)
    TIFF:                        NO
    JPEG 2000:                   NO
    OpenEXR:                     NO

  Video I/O:
    AVFoundation:                YES
    QuickTime:                   NO
    QTKit:                       NO
    V4L/V4L2:                    NO/NO

  Other third-party libraries:
    Use IPP:                     NO
    Use Eigen:                   NO
    Use TBB:                     NO
    Use OpenMP:                  NO
    Use GCD                      YES
    Use Concurrency              NO
    Use C=:                      NO
    Use Cuda:                    NO
    Use OpenCL:                  NO

  Python:
    Interpreter:                 /usr/bin/python (ver 2.7.10)

  Java:
    ant:                         NO
    JNI:                         NO
    Java tests:                  NO

  Documentation:
    Build Documentation:         NO
    Sphinx:                      NO
    PdfLaTeX compiler:           NO

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  /Users/lixu/Downloads/opencv-2.4.9/platforms/ios/ios/build/iPhoneOS-armv7/install

  cvconfig.h is in:              /Users/lixu/Downloads/opencv-2.4.9/platforms/ios/ios/build/iPhoneOS-armv7

General configuration for OpenCV 2.4.9 =====================================
  Version control:               2.4.9

  Platform:
    Host:                        Windows 6.1 AMD64
    CMake:                       2.8.11.2
    CMake generator:             Visual Studio 12
    CMake build tool:            C:/PROGRA~2/MSBuild/12.0/Bin/MSBuild.exe
    MSVC:                        1800

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio
12.0/VC/bin/cl.exe  (ver 18.0.21005.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE
_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigob
j /arch:SSE2 /Oi /fp:fast  /wd4251 /MT /O2 /Ob2 /D NDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE
_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigob
j /arch:SSE2 /Oi /fp:fast  /wd4251 /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio
12.0/VC/bin/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRE
CATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /arch:S
SE2 /Oi /fp:fast  /MT /O2 /Ob2 /D NDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRE
CATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /arch:S
SE2 /Oi /fp:fast  /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:X86   /NODEFAULTLIB:atlthunk.lib /NODE
FAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /INCREMENTAL:NO  /debug /NODEFAULT
LIB:libcmtd.lib
    Linker flags (Debug):        /machine:X86   /NODEFAULTLIB:atlthunk.lib /NODE
FAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /debug /INCREMENTAL  /NODEFAULTLIB
:libcmt.lib
    Precompiled headers:         YES

  OpenCV modules:
    To be built:                 core flann imgproc highgui features2d calib3d m
l video legacy objdetect photo gpu ocl nonfree contrib stitching superres ts vid
eostab
    Disabled:                    java python world
    Disabled by dependency:      -
    Unavailable:                 androidcamera dynamicuda viz

  Windows RT support:            NO

  GUI:
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.7)
    JPEG:                        build (ver 62)
    PNG:                         build (ver 1.5.12)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      codec:                     YES (ver 55.18.102)
      format:                    YES (ver 55.12.100)
      util:                      YES (ver 52.38.100)
      swscale:                   YES (ver 2.3.100)
      gentoo-style:              YES
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Other third-party libraries:
    Use IPP:                     NO
    Use Eigen:                   NO
    Use TBB:                     NO
    Use OpenMP:                  NO
    Use GCD                      NO
    Use Concurrency              YES
    Use C=:                      NO
    Use Cuda:                    NO
    Use OpenCL:                  YES

  OpenCL:
    Version:                     dynamic
    Include path:                C:/builds/2_4_PackSlave-win32-vc12-static/openc
v/3rdparty/include/opencl/1.2 C:/Program Files (x86)/AMD/clAmdFft/include C:/Pro
gram Files (x86)/AMD/clAmdBlas/include
    Use AMD FFT:                 YES
    Use AMD BLAS:                YES

  Python:
    Interpreter:                 C:/Python27/python.exe (ver 2.7.5)

  Java:
    ant:                         C:/Program Files (x86)/apache-ant/bin/ant.bat (
ver 1.9.2)
    JNI:                         C:/Program Files (x86)/Java/jdk1.6.0_45/include
 C:/Program Files (x86)/Java/jdk1.6.0_45/include/win32 C:/Program Files (x86)/Ja
va/jdk1.6.0_45/include
    Java tests:                  NO

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  C:/builds/2_4_PackSlave-win32-vc12-static/build
/install

  cvconfig.h is in:              C:/builds/2_4_PackSlave-win32-vc12-static/build
/opencv_build
-----------------------------------------------------------------

**Comment by alalek** [comment]
> JPEG:                        build (ver 62)
> JPEG:                        build (ver 62)

They are same actually and both builds use jpeg source code from OpenCV 3rdparty.

In general there are several non bit-exact operation, and JPEG reading is one of them. You can use PNG for testing.
Also you use `32F`, it is not bit-exact.
Other non bit-exact operations are some optimizations, like IPP (it is actual for master/3.x only, not 2.4) Sometimes `/O3` compiler option is dangerous (used in iOS build). You may try to check results with `/O0`

If results are completely different, but depends on platform - it is very strange and it should be investigated before filling the bug.

**Comment by mshabunin** [comment]
@ruigangyang , do you have any additional information? Did you try to use PNG images as input?
