### ISSUE TITLE
Trying different webcam resolutions with Logitech C920 is very slow and results in problems (Win7)

### ISSUE THREAD

**Issue by hekkup** [opencv/opencv#6505]
### Please state the information for your system
- OpenCV version: 3.0
- Host OS: Windows 7
- Logitech C920 web camera

### In which part of the OpenCV library you got the issue?
- Module: videoio
- Class: VideoCapture (default backend)

### Expected behaviour
- setting and getting width and height properties is fast (at most a few milliseconds)
- no problems afterwards

### Actual behaviour
- setting and getting width and height properties is very slow, lasts a few seconds each time
- camera freezes and only gives black frames until replugging camera
- rebooting PC when the frozen camera is plugged freezes the whole system (might indicate web cam problem)

### Code example to reproduce the issue

```
    cv::VideoCapture* m_webCamera;
    ...
    m_commonResolutions << QSize(640, 480);	// VGA
    m_commonResolutions << QSize(704, 576);	// 4CIF
    m_commonResolutions << QSize(800, 600);	// SVGA
    ...
    for (int i = smallestIndex; i < (largestIndex + 1); i++) {
        testRes = m_commonResolutions.at(i);
        m_webCamera->set(CV_CAP_PROP_FRAME_WIDTH, testRes.width());
        m_webCamera->set(CV_CAP_PROP_FRAME_HEIGHT, testRes.height());
        width = m_webCamera->get(CV_CAP_PROP_FRAME_WIDTH);
        height = m_webCamera->get(CV_CAP_PROP_FRAME_HEIGHT);
        if ((testRes.width() == width) && (testRes.height() == height)) {
            qDebug() << "Web camera supports resolution" << width << "x" << height;
            m_availableResolutions << testRes;
        } else {
            qDebug() << "No support for resolution" << testRes.width() << "x" << testRes.height() <<"-- got " << width << "x" << height << "instead";
            QSize newRes(width, height);
            if (!m_commonResolutions.contains(newRes) && !m_availableResolutions.contains(newRes)) {
                m_availableResolutions << newRes;
            }
        }
    }
```

### Additional info
- The problem might be due to the camera model itself, I have no info about this
- There's some more discussion about the issue over here: https://github.com/UFOID/UFO-Detector/pull/12
- Here's the link to the specific commit: https://github.com/hekkup/UFO-Detector/commit/ca562a4c44e3612639e1c1704b339dac4d6f8fcc. If you want to try it out, the quickest way is to run the unit test for CameraInfo at test/testCameraInfo/testcamerainfo.pro (a Qt project).
- With OpenCV 2.4.8 and Logitech QuickCam Express in Ubuntu Linux the same code works without any problem

**Comment by hekkup** [comment]
With Linux the same web camera (Logitech C920) behaves normally so there's no performance hit nor problems afterwards.

**Comment by mshabunin** [comment]
Did you try the latest master version? Please provide your cmake configuration output (returned by cmake or `cv::getBuildInformation()` function).

**Comment by mshabunin** [comment]
Seems to be obsolete.
