### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KeeganRen** [opencv/opencv#6512]
I'm using Mac 10.10 and OpenCV 3.0, when I was compiling my project I got this error:

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
After that, I changed the c++ standard library to libstdc++, another error appeared:

/usr/local/include/opencv2/hal/defs.h:271:14: 'cstdint' file not found

Hope someone could help me

**Comment by alalek** [comment]
Try the latest code fro master branch, this problem may be fixed.

> compiling my project I got this error:

I have no idea how to reproduce this problem. More details are required:
- how did you build/install OpenCV
- how do you build you app

BTW, "Fixing" errors with linker can't cause problems with compilation. Try to build from scratch also.

**Comment by KeeganRen** [comment]
I don't konw why, Use CMake, the project will error, but when I use "cmake -G Xcode .."，and use XCode  open the project, the error is gone.

**Comment by mshabunin** [comment]
Please provide OpenCV installation method (brew?), configuration info (returned by `cv::getBuildInformation()`) and minimal reproducing cmake project.

**Comment by ilya-lavrenov** [comment]
invalid, broken issue. Closing.
