### ISSUE TITLE
gcc versions error when installing OpenCV 3.1.0

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [opencv/opencv#6513]
Hi, I met a problem in installing OpenCV 3.1.0
- Host OS: Linux (Ubuntu 15.10 x86_64)  
- CUDA 7.5.17

I installed CUDA first, and when I followed [this installation guide](https://help.ubuntu.com/community/OpenCV), I met an error at `make -j2`:

```
[ 18%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
In file included from /usr/local/cuda-7.5/include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/usr/local/cuda-7.5/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:208 (message):
  Error generating
  /home/zhaoxiaoming/opencv-3.1.0/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o


modules/core/CMakeFiles/opencv_core.dir/build.make:55: recipe for target 'modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o' failed
make[2]: *** [modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o] Error 1
CMakeFiles/Makefile2:1184: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
```

About my gcc, I checked my /usr/bin/, there are three versions of gcc and g++, namely 4.8.5, 4.9.3 and  5.2.1. Because when using CUDA, it required gcc no later than 4.9, so I did the following:

```
sudo ln -s /usr/bin/gcc-4.9 /usr/local/cuda/bin/gcc
sudo ln -s /usr/bin/g++-4.9 /usr/local/cuda/bin/g++
```

And when met the OpenCV error, I did the following: 

```
sudo ln -s /usr/bin/gcc-4.8 /usr/local/cuda/bin/gcc
sudo ln -s /usr/bin/g++-4.8 /usr/local/cuda/bin/g++
```

And when I use`gcc --version` to check, the output is 4.8.5.

I am wondering whether there is a method to let the OpenCV `make -j2` procedure uses exactly the right gcc version?

Thanks!

**Comment by StevenPuttemans** [comment]
You could open up the `cmake-gui` and explicitly tell it which compiler you want to use from the first drop down menu I guess.

**Comment by alalek** [comment]
http://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake
but It is hard to say how does this help CUDA NVCC

**Comment by Rohith25** [comment]
I'm kinda facing the same issue here. I've manually set the gcc version to 4.9 and it works perfectly fine when I compile the NVIDIA cuda sample stuff. Unfortunately it still blows me off with the above message when I try to install OpenCV

**Comment by bonben** [comment]
Fix by setting parameter : 
//Host side compiler used by NVCC
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/gcc-4.9
