### ISSUE TITLE
Installable via pip

### ISSUE THREAD

**Issue by c-martinez** [opencv/opencv#6516]
Currently, the python wrappers are installable via a conda recipe. But would it make sense to also make opencv2/3 installable via pip? Maybe the answer is **NO**, but maybe it would be useful. Could anyone share their thoughts?

**Comment by StevenPuttemans** [comment]
The problem with automated install systems is that someone has to maintain the packages and keep providing the latest updates, in order to avoid that people use old and outdated software. I know this is one of the reasons why OpenCV is quite hesitating to support all those interfaces themselves. It is not prohibited for users to provide these packages themselves, but I guess OpenCV core dev team will not take the time to maintain those.

**Comment by skvark** [comment]
I'm working on this (I should be able to get Windows builds to PyPi soon for py27 and py35). The main goal is to push prebuilt binaries as Python wheels automatically to PyPi with Appveyor and Travis. Contributions are welcome.

You can find the current implementation from my [opencv-python](https://github.com/skvark/opencv-python) repo. As @StevenPuttemans wrote, maintaining these things takes a lot of time. I hope that I can cut this time down as much as possible with CI and other automation.

**Comment by c-martinez** [comment]
Nice to know that there is already an effort to build wheels for OpenCV. And I think you are right @skvark, CI should cut the effort required to build.

**Comment by skvark** [comment]
OpenCV can be now installed for python via PyPI: https://pypi.python.org/pypi/opencv-python/3.1.0.0

```pip install opencv-python``

These are pre-built packages so installation should take only few seconds.

**Comment by doylefermi** [comment]
Using the opencv-python package, I cant open the camera interface.
![image](https://cloud.githubusercontent.com/assets/8755940/21587558/e80b36dc-d103-11e6-82e1-e90d2f11c6cf.png)

However using the [archlinux package ](https://www.archlinux.org/packages/extra/x86_64/opencv/) it works.
![image](https://cloud.githubusercontent.com/assets/8755940/21587694/16997670-d105-11e6-900a-9c6e5108f8db.png)

`$ ls -al /dev/video0`
crw-rw----+ 1 root video 81, 0 Jan  2 15:58 /dev/video0

I have added myself to the `video` group as well, so it shouldn't be a permission issue.

**Comment by skvark** [comment]
Please see https://github.com/skvark/opencv-python/issues/14, opencv-python is not compiled with ffmpeg currently. Note that opencv-python is unofficial package so it's unlikely that you find help from this official repo.
