### ISSUE TITLE
sample tapi hog application doesn't run

### ISSUE THREAD

**Issue by dozyc** [opencv/opencv#6525]
The sample application at samples/tapi/hog.cpp doesn't get past argument parsing.

There is a check if a "help" option exists in the CommandLineParser, which is always true. This means the usage always prints and the app exits, even if -h or --help was not specified.

Example output:

```
$ ./tapi-example-hog 
Usage : hog [options]
Available options:
Usage: tapi-example-hog [params] 

	-c, --camera (value:-1)
		enable camera capturing
	-g, --gray (value:false)
		convert image to gray one or not
	-h, --help (value:false)
		print help message
	-i, --input
		specify input image
	-o, --output
		specify output path when input is images
	-s, --scale (value:1.0)
		resize the image before detect
	-v, --video (value:../data/768x576.avi)
		use video as input
```

Even though help is clearly "false", the help dialog prints.

**Comment by berak** [comment]
actually, all tapi samples suffer from this.

(can we agree on *one* way to fix it ?)

**Comment by dozyc** [comment]
OK, I suppose we can go with removing the default "false" for help. Commit coming soon...
