### ISSUE TITLE
Integrating aruco in opencv_contrib into opencv2.framework.

### ISSUE THREAD

**Issue by boaerosuke** [opencv/opencv#6530]
Hi, in your last Changelogs you wrote:
"The iOS framework (opencv2.framework) can now be configured to include both opencv and opencv_contrib functionality."

How do I configure the opencv2.framework to include the aruco module in order to make it applicable for iOS? I am looking for hints and tipps.

There is no description or hint. I would prefer to ask ad answer.opencv.org. But sadly the page is down since weeks.

**Comment by alalek** [comment]
There is no plan to make official packages with opencv_contrib code.
Anyway, you can try to build it yourself or get it from nightly builder artifacts (commands and step logs are available also): http://pullrequest.opencv.org/buildbot/builders/master-contrib_iOS-mac/builds/286

**Comment by elukau** [comment]
Thank you for the reply.
I am doing this for a Student project, with the link you provided, are there all the contrib_modules integrated into one build so I could download or clone exactly that build?

 I have tried to build it by myself by pulling the sourcecode for opencv2.framework from the repository and adding the aruco module (that I need) from the opencv_contrib repo by hand. However the installations tutorial for the iOS opencv version like it is described  here: http://docs.opencv.org/2.4/doc/tutorials/introduction/ios_install/ios_install.html#ios-installation 

with building the library via python script is not working. (Is this still up to date?)
Here is the Traceback:
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "opencv-3.1-2.0/platforms/ios/build_framework.py", line 87, in build
    self._build(outdir)
  File "opencv-3.1-2.0/platforms/ios/build_framework.py", line 81, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv-3.1-2.0/platforms/ios/build_framework.py", line 133, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "opencv-3.1-2.0/platforms/ios/build_framework.py", line 34, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


Thanks

**Comment by alalek** [comment]
> No such file or directory

Looks like you need to install CMake.
Take a look on [build logs](http://pullrequest.opencv.org/buildbot/builders/master-contrib_iOS-mac/builds/286/steps/build%20contrib%20framework/logs/stdio) for more information and track them.

**Comment by elukau** [comment]
Thank you very much. I already have CMake installed (gui version) I hope the build logs will help.

**Comment by boaerosuke** [comment]
Hi, I looked up the build logs but did not get the information I needed for a successful build. I also double checked my installation of CMAKE. By following all the instructions from the opencv installations tutorials provided, I still get stuck by this missing files issue. The python script also builds the correct file directories as destination for the ios framework but the directories are empty
 (/result/ios/build/armv7-iPhoneOS). 

I don´t know what files are missing or if need to update the python script itself in some way. I did some research but nothing I found could help me with this issue to successfully build the opencv2.framework file with one additional module (aruco). It should have nothing to do with the additional module because I also tried it with the "clean-code" from the git, still facing the same error. Maybe someone can help me with this, pointing out what files are missing, or how I could create the .framework file with cmake. Sorry again this is not supposed to be here but rather on answers.opencv.org but the page is still down, so I hope some body will find some minutes to help me with this or give me a hint. 
```

wlan 100.10.10:result Developer$ python /Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/build_framework.py ios
Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /Users/Developer/Desktop/result/ios/build/armv7-iPhoneOS
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/build_framework.py", line 87, in build
    self._build(outdir)
  File "/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/build_framework.py", line 81, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/build_framework.py", line 133, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/build_framework.py", line 34, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by alalek** [comment]
@boaerosuke You need to check that CMake works from terminal via "cmake" command.

**Comment by boaerosuke** [comment]
@alalek thanks for your help. CMake is working from the command line and I got still the same error. I did research on CMake it self but I did not understand if I should use CMake to create the framework or it should still be done with the build_framework.py. I also tried to use CMake to do a configuration. That actually works but I do not know how to turn this in to the framework library. I also tried to start the python script with and without  "./" in front but nothing changed.

**Comment by alalek** [comment]
`build_framework.py` runs CMake and other tools to build framework (it looks like a shell script, but it is written on Python)

Try to run command manually in the same terminal there you run build_framework.py script:
```
$ cd /Users/Developer/Desktop/result/ios/build/armv7-iPhoneOS
$ cmake -GXcode -DAPPLE_FRAMEWORK=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake -DENABLE_NEON=ON /Users/Developer/Desktop/opencvNewLib/opencv-3.1-2.0 -DCMAKE_C_FLAGS=-fembed-bitcode -DCMAKE_CXX_FLAGS=-fembed-bitcode
```

Does this error still exist?

**Comment by boaerosuke** [comment]
Wow! That helped me! Thanks a lot. Now I now the script is running, but the result was not the supposed opencv2.framework file but rather a xcode project. Are these the files I need to convert to the framework or do I need additional steps to do this?

**Comment by alalek** [comment]
This is just a check for error message, it will not build framework. These commands is a part of whole script only.
You need to complete execution of `build_framework.py` somehow (error message is not reproduced via direct run, so currently I have no idea what is reason of the problem)

**Comment by boaerosuke** [comment]
Okay thank you very much for your help! I´ll go on with this and report here if I find the issue.

**Comment by jairobbo** [comment]
How did you include Aruco into OpenCV by hand?

**Comment by boaerosuke** [comment]
I manually compiled the contribe_module as dynamic library with only aruco inside of it, and then used the contribe_module normally with the openCV library in my project

**Comment by cancan101** [comment]
Right now we use the following to build contrib on ios with just the aruco module, though I would be curious ti know if there is a better way:
```sh
cd opencv_contrib/
ls | grep -v aruco | xargs rm -rf
cd ..
python opencv/platforms/ios/build_framework.py --contrib opencv_contrib/ ios
```
