### ISSUE TITLE
GpuMat create crash

### ISSUE THREAD

**Issue by tommy87** [opencv/opencv#6550]
When i try to use the funcion create from GpuMat the program crashes. When i upload the image directly it works fine

"OpenCV Error: Gpu API call (unknown error) in allocate, file /home/tkrause/opencv/opencv-3.0.0/modules/core/src/cuda/gpu_mat.cu, line 71
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/tkrause/opencv/opencv-3.0.0/modules/core/src/cuda/gpu_mat.cu:71: error: (-217) unknown error in function allocate"

I have to ideas what the problem could be:
1. I'm using Ubuntu 16.04 and with cuda 7.5 from synaptic (nvidia-cuda-toolkit) and maybe there are some dependencies that are to new
2. to get opencv work with cuda, i had to compile opencv with clang (CUDA_HOST_COMPILER=clang-3.5) and maybe there is some other handling when signed and unsiged values come together (so maybe a range overflow)
### Please state the information for your system
- OpenCV version: 3.0 / 3.1
- Host OS: Linux (Ubuntu 16.04)  
- Compiler: clang 3.5
### In which part of the OpenCV library you got the issue?
- cuda
### Code example to reproduce the issue / Steps to reproduce the issue

```
#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>

int main(int argc, char *argv[])
{
    cv::Mat image = cv::imread("lena.png");

    cv::imshow("image", image);
    cv::waitKey();

    cv::cuda::GpuMat test1;
    test1.upload(image);   //this works fine

    cv::cuda::GpuMat test2;
    test2.create(500,500, CV_32FC3);   //this crashes (same params like in test1)
}
```

**Comment by kevin-coder** [comment]
@tommy87 , at the last line: test2.create(500,500, CV_32FC3), you mentioned that if use the same params like in test1, it will crash, what's the exact params you use in this invoke?

**Comment by tommy87** [comment]
yes i have created it originaly with test2.create(image.rows,image.cols, CV_32FC3); or something like that...when you need another test, i can do it to day, but the next two weeks i'm on vacations.

**Comment by kevin-coder** [comment]
@tommy87 , I use your code test2.create(image.rows,image.cols, CV_32FC3) to do the test, and did not meet any crash, so could you please provide a specific test case?

**Comment by kevin-coder** [comment]
Is there any update about the re-produce test case? Or does this issue still happen in the latest code base?

**Comment by tommy87** [comment]
I have testet it today again on 2 PC's:
- Ubuntu 16.04
- installed nvidia-cuda-toolkit 
- compiled OpenCV with CUDA_HOST_COMPILER gcc-5

on one PC it works and on the other one not...both of them are compiled from the master branch and are less than a week old..

**Comment by tommy87** [comment]
Today i had a test on another pc and i get the message again 
"OpenCV Error: Gpu API call (unknown error) in allocate, file /home/tkrause/OpenCV/opencv/modules/core/src/cuda/gpu_mat.cu, line 116"

```
bool DefaultAllocator::allocate(GpuMat* mat, int rows, int cols, size_t elemSize)
    {
        if (rows > 1 && cols > 1)
        {
this line -->   CV_CUDEV_SAFE_CALL( cudaMallocPitch(&mat->data, &mat->step, elemSize * cols, rows) );
        }
        else
        {
            // Single row or single column must be continuous
            CV_CUDEV_SAFE_CALL( cudaMalloc(&mat->data, elemSize * cols * rows) );
            mat->step = elemSize * cols;
        }

        mat->refcount = (int*) fastMalloc(sizeof(int));

        return true;
}
```

---------------------------------------

Some further test show that it depends on the grafic card and it is not a general opencv problem. I have some plain CUDA code and it seems that it is not possible the access the cuda device at all.
As far as i can say older grafic cards works fine. I have tested it on a GTX 780 and a GTX 980 and on both i get the error.

I will try to install CUDA from another source, maybe this will fix the problem.

**Comment by tommy87** [comment]
Finally i got it to work, as i assumed the error was caused by the nvidia-cuda-toolkit from the ubuntu 16.04 repoosity. And i got it working by installing the CUDA version from the NVIDIA website.

For other user with this problem, here is the way how to install everything:

1. Download the CUDA run file from NVIDIA (i used the version for ubuntu 15.10 )
2. install gcc-4.8 and g++-4.8 (g++ is later needed by opencv):
`sudo apt-get install gcc-4.8 g++-4.8`
3. Set the gcc-4.8 as the default compiler:
```
sudo update-alternatives --remove-all gcc
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
```
_4. switch the terminal session (ctrl+alt+F2) and install the Donloaded CUDA version:
```
sudo service lightdm stop
chmod +x cuda_7.5.18_linux.run
sudo ./cuda_7.5.18_linux.run
```
read carfully the messages!!! In my case the cuda driver cant be installed, so i skipped to installation of the driver and only installed the CUDA toolkit and the samples. After that start lightdm again.
`sudo service lightdm start`
5. Install a new nvida driver. In my case if installed a driver from "additional drivers" and i selected the new NVIDIA driver (361.42 (proprietary, testet))
6. reset gcc to the previous version (in my case it was gcc-5)
```
sudo update-alternatives --remove-all gcc
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
```
_7. Now compile opencv but using ass CUDA_HOST_COMPILER the gcc-4.8

**Comment by Deejep** [comment]
@tommy87 changing default compiler seems a bit cumbersome. Especially if you want to make just one thing work out.

Any new alternatives for fix ?

**Comment by tommy87** [comment]
Changing The Default Compiler ist Not needed anymore. For Ubuntu 16.04 is the New cuda 8 ready for downloading and together with opencv 3.2 i didn't encounter any problems

**Comment by stevencui2** [comment]
I have a similar problem in windows, GpuMat.create crash when the size is too large(4e6*200). It can work with a small size like 540000*200.
But my Cuda toolkit is download directly from the Nvidia website, anyone has any clue?

**Comment by LisaPal** [comment]
I am using opencv 3.2 with CUDA 7.5 in Ubuntu 16.04. While using cv::cuda::GpuMat::upload(arr) function , I got an error very similar to yours: 
`OpenCV Error: Gpu API call (unknown error) in upload, file /usr/src/opencv-3.2.0/modules/core/src/cuda/gpu_mat.cu, line 224
Error: /usr/src/opencv-3.2.0/modules/core/src/cuda/gpu_mat.cu:224: error: (-217) unknown error in function upload .`
My g++ compiler is  5.4.0. Given that I did not get any error messages while installing OpenCV, I don’t think it’s a compatibility problem. Do you have any further ideas on what the issue could be?

**Comment by stevencui2** [comment]
What is the size of your array? Can you try a small one?
Currently, I still have no idea what the issue could be.
But I would suggest you upgrade your Cuda to the latest version and try it again.
If you have some solution, please let me know.

**Comment by twobob** [comment]
./test
Error: OpenCV(4.2.0) /home/me/opencv-4.2.0/modules/core/src/cuda/gpu_mat.cu:116: error: (-217:Gpu API call) unknown error in function 'allocate'
0.039346

Linux, Focal Fossa, used "sudo apt install nvidia-cuda-toolkit", Gtx 980 FTW, nvidia-driver-440

Any clues?
