### ISSUE TITLE
I tried to obtain face image and process it based on opencv sample ,face-detection,but a 'Android runtime fatal error" occurs.Hope for some help.

### ISSUE THREAD

**Issue by jyyuni** [opencv/opencv#6552]
I have moved it.

**Comment by berak** [comment]
can we move this to http://answers.opencv.org ?

(this is not a library issue, more a "userland problem")

**Comment by PhilLab** [comment]
Please use http://answers.opencv.org/ or http://stackoverflow.com for such requests since this seems to be a programming error and not a library bug. Hint: Include some code in your question on the mentioned sites.
