### ISSUE TITLE
[Python] Reading video, first frame, last frame issue   

### ISSUE THREAD

**Issue by Frij** [opencv/opencv#6555]
I'm trying to read a gif file using Video Capture and then playing the same file. I noticed that the first frame is skipped and the last frame is played twice. I've tested that on multiple gif files and I always have the same issue. 
I'm using the latest version of OpenCV (3.1) and to read the video, I am using the read() method.

**Comment by mshabunin** [comment]
Can you please provide a minimal reproducing example and small image. Also we need more information about your platform: cmake output or `cv::getBuildInformation()` output.

**Comment by Frij** [comment]
Save the following simple, 4 frames,  gif animation : [gif file](http://25.media.tumblr.com/26d3b024138cabf2b408ad719dad6ebb/tumblr_mqi8wivNJA1rnvb0co1_500.gif)

This is the minimal code to display the first frame:

```
capture = cv2.VideoCapture("name_of_file.gif")
b,firstFrame= capture.read()
while True:
    cv2.imshow("First Frame",firstFrame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

The frame that is diplayed is not the first one but the second one.
[platform_info.txt](https://github.com/Itseez/opencv/files/272526/plateform.txt)

**Comment by mshabunin** [comment]
Can not reproduce in Ubuntu 14.04 with FFMPEG, seems to be OSX specific issue.

**Comment by Frij** [comment]
So the image you're getting is the one with the black sphere (no lightning ) ?
Because that's not what I'm getting, + when I display all the frames, the last one is repeated twice.

**Comment by mshabunin** [comment]
Yes, I get **only** the first frame (I made several read calls, but only first return `b=True`). Not sure whether it is a bug or a feature.

**Comment by basantapatra** [comment]
Please use the below sample code to play the all 4 frames for above provided gif file with delay of 1 sec. I am able to play all the 4 frames successfully.

Sample code:
============
import cv2

print "Opencv Version:" + str(cv2.__version__)
cap = cv2.VideoCapture("xyz.gif")
while(cap.isOpened()):
    b,firstFrame= cap.read()
    if b==True:
       cv2.imshow("First Frame",firstFrame)
       print "frame"
       if cv2.waitKey(1000) & 0xFF == ord('q'):
           break
    else:
         break
cap.release()
cv2.destroyAllWindows()


If anyone want to extract and save all the 4 frames as 4 different image file, Please refer the below link
https://gist.github.com/revolunet/848913

**Comment by shasdemir** [comment]
I'm having this exact same bug in Anaconda OpenCV 3.1.0 on OS X...

**Comment by shasdemir** [comment]
Installing OpenCV 3.2.0 with FFMPEG backend solved this problem. Not sure whether it was the version bump or FFMPEG.

**Comment by AkashNagaraj** [comment]
cap=cv2.VideoCapture("Sample.mp4")
cap.read()

This code does not work since cap.read() always returns flase.
