### ISSUE TITLE
OpenCV Stitcher class missing python bindings

### ISSUE THREAD

**Issue by czhang96** [opencv/opencv#6556]
- OpenCV version:  3.1

`cv::Stitcher` is missing some python bindings. For example, `setWarper` does exist as a python binding. 
`help(cv2.createStitcher()` shows which methods are currently implemented, and is clearly incomplete when compared to [docs](http://docs.opencv.org/3.1.0/d2/d8d/classcv_1_1Stitcher.html#gsc.tab=0)

**Comment by Motherboard** [comment]
This is still the case for 3.4...

I want to use the SCAN mode, but I don't see any way to do that in python..

**Comment by Motherboard** [comment]
@alalek Thanks. Seems I need a cylindrical warper, along with WAVE_CORRECT_VERT, not the SCAN mode after all... So this solution does not help me at the moment.

**Comment by devanshbatra04** [comment]
I am taking this up, will send a PR by the hackathon period.

**Comment by alalek** [comment]
Bindings for stitching module is available in OpenCV 4.x. Related samples:
- https://github.com/opencv/opencv/blob/4.2.0/samples/python/stitching.py
- https://github.com/opencv/opencv/blob/4.2.0/samples/python/stitching_detailed.py

Closing as implemented.
