### ISSUE TITLE
about license information of IPPICV

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#6569]
### My question

I hope to know about license information of IPPICV.
- http://opencv.org/opencv-3-0.html
- http://code.opencv.org/projects/opencv/wiki/Opencv3

These pages have the following description.

> Intel Corporation granted OpenCV Foundation and all our users the right to use IPP-ICV libraries free of charge for both non-commercial and commercial use. 

On the other hand, I can not find the above-mentioned information from IPPICV of [opencv_3rdparty](https://github.com/Itseez/opencv_3rdparty). So, I hope to know about license information of IPPICV.
### Note

This topic is discussed in the following forum, too.
Maybe, I think the license of IPPICV has not been well-known.
https://software.intel.com/en-us/forums/intel-integrated-performance-primitives/topic/606623

**Comment by alalek** [comment]
You need to switch to IPPICV branch in opencv_3rdparty repo: https://github.com/Itseez/opencv_3rdparty/tree/ippicv/master

There are some EULA files extracted from IPPICV packages.

**Comment by atinfinity** [comment]
Thank you for your comment.
I checked these EULA files. But, I could not find the following description.
So, I posted this question.

> Intel Corporation granted OpenCV Foundation and all our users the right to use IPP-ICV libraries free of charge for both non-commercial and commercial use. 

There is the following description in **ippEULA.rtf**("13. THIRD PARTY PROGRAMS") .

> The Materials may include third party programs or materials.  The license terms with those programs or materials apply to your use of them, and Intel is not liable for them.

So, I think that OpenCV's license terms apply to IPPICV(included in OpenCV).
Is my understanding correct?

**Comment by vladimir-dudnik** [comment]
you need check understanding of license terms with your company legal department. close this.
