### ISSUE TITLE
FindCuda.cmake should use the libcuda.so stub

### ISSUE THREAD

**Issue by flx42** [opencv/opencv#6577]
OpenCV version: master (64a5126ff83d576dab72cb67f41a1a1153e0de00)
Host OS: Linux (Ubuntu 14.04), running inside a Docker container.

When compiling OpenCV master with `-DBUILD_EXAMPLES=ON` on a machine where the **CUDA toolkit is installed but no NVIDIA driver is present**, the configure step will fail:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "example_gpu_alpha_comp" in directory /opencv/samples/gpu
    linked by target "example_gpu_bgfg_segm" in directory /opencv/samples/gpu
    linked by target "example_gpu_cascadeclassifier" in directory /opencv/samples/gpu
    linked by target "example_gpu_cascadeclassifier_nvidia_api" in directory /opencv/samples/gpu
[... all the gpu samples]
```

This is because `libcuda.so` is not found.

This problem is in the following macro:
https://github.com/Itseez/opencv/blob/64a5126ff83d576dab72cb67f41a1a1153e0de00/cmake/FindCUDA.cmake#L682-L714
This macro should also look into the stub libraries offered by the CUDA toolkit (`/usr/local/cuda/lib64/stubs/`).
When cross-compiling you are already using the stubs folder, but the 32-bit version:
https://github.com/Itseez/opencv/blob/64a5126ff83d576dab72cb67f41a1a1153e0de00/cmake/FindCUDA.cmake#L689
We should do the same but with `lib64/stubs` and then there will be no need of having the CUDA driver installed when simply building OpenCV.

Docker was used because there is no CUDA driver when compiling, but the problem should be the same on a machine with the CUDA toolkit installed but with no CUDA driver. This is my Dockerfile:

```
FROM nvidia/cuda:7.5-devel                                        

RUN apt-get update && apt-get install -y --no-install-recommends \       
        ca-certificates \                                                
        cmake \                                                          
        git \                                                            
        pkg-config \                                                     
        wget && \                                                        
    rm -rf /var/lib/apt/lists/*                                          

RUN git clone --depth 1 https://github.com/Itseez/opencv.git /opencv && \
    cd /opencv && \                                                      
    cmake -DBUILD_EXAMPLES=ON .                                          
```

**Comment by flx42** [comment]
Also, my `LIBRARY_PATH` variable is set to the stubs folder, but it is ignored by cmake.

**Comment by GBJim** [comment]
Hi, I had the exact same problem.
Is there a solution for this?

**Comment by flx42** [comment]
@GBJim try to add the following to your cmake command:
```
-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs
```

See the doc:
https://cmake.org/cmake/help/v3.3/command/find_library.html

**Comment by GBJim** [comment]
＠fix42 Thanks for the help!
I made a symbolic link connecting two locations :)

**Comment by jet47** [comment]
You can explicitly specify `CUDA_CUDA_LIBRARY` variable in CMake command line:

```
-DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so
```

**Comment by alalek** [comment]
`CUDA_CUDA_LIBRARY` is selected properly in NVIDIA Docker containers for CUDA development:
https://gitlab.com/nvidia/cuda/blob/7f47169af7e0c7901d17559c37c9a54ce9e8f368/8.0/devel/Dockerfile#L22
