### ISSUE TITLE
hconcat/vconcat throw Exception with UMat

### ISSUE THREAD

**Issue by berak** [opencv/opencv#6578]
### Please state the information for your system
- OpenCV version: 3.1.0 (master)
- Host OS: Windows 10
- MingW64

### In which part of the OpenCV library you got the issue?
- core / tapi / ocl

### Code example to reproduce the issue / Steps to reproduce the issue
```
#include "opencv2/opencv.hpp"
#include "opencv2/core/ocl.hpp"
using namespace cv;

#include <iostream>
using namespace std;

int main(int argc, char **argv)
{
    bool useOCL = (argc>1 && argv[1][0]=='1');
    ocl::setUseOpenCL(useOCL);
    cout << "useOCL "  <<  cv::ocl::useOpenCL() << endl;
    UMat small(64,64,CV_32F);
    randu(small,0,1);
    UMat large = small.clone();
    for (int i=0; i<100; i++)
    {
        cerr << i << " " << large.size() << endl;
        // vconcat(large,small,large); // same problem
        hconcat(large,small,large);
    }
    return 0;
}
```
### Output:

```

C:\p\ocv\demo>demo 0
useOCL 0
0 [64 x 64]
OpenCV Error: Assertion failed (u->refcount == 0) in deallocate, file C:\p\opencv\modules\core\src\matrix.cpp, line 212
terminate called after throwing an instance of 'cv::Exception'
  what():  C:\p\opencv\modules\core\src\matrix.cpp:212: error: (-215) u->refcount == 0 in function deallocate


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

C:\p\ocv\demo>demo 1
useOCL 1
0 [64 x 64]
OpenCV Error: Assertion failed (u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive") in deallocate, file C:\p\opencv\modules\core\src\ocl.cpp, line 4516
terminate called after throwing an instance of 'cv::Exception'
  what():  C:\p\opencv\modules\core\src\ocl.cpp:4516: error: (-215) u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive" in function deallocate

```

**Comment by atinfinity** [comment]
I think that this is not OpenCV's issue.

[cv::hconcat](http://docs.opencv.org/master/d2/de8/group__core__array.html#gaab5ceee39e0580f879df645a872c6bf7) concatenates given matrices.
So, I think that you should set <code>(src1.row+src2.row)</code> as dst.row in this case.

## fixed code

```
#include "opencv2/opencv.hpp"
#include "opencv2/core/ocl.hpp"
using namespace cv;

#include <iostream>
using namespace std;

int main(int argc, char **argv)
{
	bool useOCL = (argc>1 && argv[1][0]=='1');
	ocl::setUseOpenCL(useOCL);
	cout << "useOCL "  <<  cv::ocl::useOpenCL() << endl;

	UMat small1(64, 64, CV_32F);
	UMat small2(64, 64, CV_32F);
	UMat large(small1.cols, (small1.rows+small2.rows), CV_32F);

	randu(small1, 0, 1);
	randu(small2, 0, 1);

	for (int i=0; i<100; i++)
	{
		cerr << i << " " << large.size() << endl;
		hconcat(small1, small2, large);
	}
	return 0;
}
```

**Comment by alalek** [comment]
> hconcat(large,small,large);

Could you try this code?
```
UMat large_next;
hconcat(large,small,large_next);
large = large_next;
```

Also I suggest to pre-allocate `large` matrix and fill it via `small.copyTo(large(roi_rect))` calls.
Also you can take a look on `cv::repeat` function.

**Comment by berak** [comment]
@alalek ,

>   Could you try this code?
```
UMat large_next;
hconcat(large,small,large_next);
large = large_next;
```

yes, that works..

> Also I suggest to pre-allocate large matrix and fill it ...

yes, that's what i'm doing now.

@atinfinity , so, basically, you're saying, one has to pre-allocate the result for hconcat/vconcat ?

there are (plain Mat) examples, where it is not done, e.g. [here](https://github.com/Itseez/opencv/blob/1307bb1d033af3baeb55afb63c3989d3d6791c80/modules/ml/src/svmsgd.cpp#L161) or [here](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/modules/core/test/test_concatenation.cpp#L101)
(also, my example works perfectly with "normal" Mat's)

**Comment by alalek** [comment]
> yes, that works

Thanks for the check!
Looks like there is missing check/processing for "inplace" (dst is the same as one of src parameter) operations in case of UMat.

**Comment by berak** [comment]
[compare](http://docs.opencv.org/master/d2/de8/group__core__array.html#ga303cfb72acf8cbb36d884650c09a3a97) has a similar problem, when src and dst are the same UMat

**Comment by ilya-lavrenov** [comment]
I think that this behavior is correct and we are not able to fix it in mean time. What happens in the original piece of code? You have the same `UMat` for input and output operation, but the output array must be recreated in this case (since it has improper size; the same for `compare` since output should have `CV_8U` depth). So, inside the `vconcat` function we have plain CPU processing which operates with `Mat`s and we should convert `UMat` into `Mat`:
1. "Convert" first input argument from `UMat` into `Mat`. This conversion means that parent `UMat` produces children `Mat` object and the last one must be destroyed when `vconcat` function exists. **NOTE:** parent object life time > child object life time.
2. The same for second argument.
3. The same for the 3rd argument. **BUT:** we should recreate output image before. But, we have already produced child object for this `UMat` and exception says about it when we are trying to deallocate `UMat`:
```
(-215) u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive" in function deallocate
```

I think we should recommend not to use `UMat` for inplace operations.

**Comment by berak** [comment]
thanks a lot for all of your explanations !

> I think we should recommend not to use UMat for inplace operations.

nice and simple lesson.
