### ISSUE TITLE
Feature Request cv::TickMeter

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#6582]
i think adding cv::TickMeter class in the library will be fine.

there is open questions at answers.opencv.org
http://answers.opencv.org/question/67009/why-tickmeter-class-only-used-in-the-gpu-samples/
http://answers.opencv.org/question/69035/tickmeter-class-removal-and-how-to-replace-it/

PS: if some core developer confirm and suggest the proper module ( i think it can be merged in core module). i will try to supply Pull Request.

**Comment by mshabunin** [comment]
@sturkmen72 , you can move this class to `core/utility.hpp` right after `getTickCount` and `getTickFrequency` functions.

**Comment by sturkmen72** [comment]
@mshabunin thanks for the response. i will supply the PR soon.

**Comment by StevenPuttemans** [comment]
Thank you for this! I might be using this to solve one of my other issues!

**Comment by sturkmen72** [comment]
@StevenPuttemans you are welcome. could you give me a hand about documentation of the class if you have time.
