### ISSUE TITLE
Opencv3 compilation issue with C API

### ISSUE THREAD

**Issue by jlguardi** [opencv/opencv#6585]
### Please state the information for your system
- OpenCV version: 3.1 and also dev version
- Host OS: Linux (Ubuntu 16.04-64 bits)
- Compiler & CMake: GCC 5.3.1 & CMake 3.5.1
### In which part of the OpenCV library you got the issue?

C-API
### Expected behaviour

Correct compilation
### Actual behaviour

Compilation error:

```
/tmp/ccDODlVK.o: In function `cvPointFrom32f':
main.c:(.text+0x54d): undefined reference to `cvRound'
main.c:(.text+0x563): undefined reference to `cvRound'
/tmp/ccDODlVK.o: In function `cvReadInt':
main.c:(.text+0xe68): undefined reference to `cvRound'
/tmp/ccDODlVK.o: In function `cvEllipseBox':
main.c:(.text+0x10d4): undefined reference to `cvRound'
main.c:(.text+0x10f6): undefined reference to `cvRound'
collect2: error: ld returned 1 exit status
```
### Code example to reproduce the issue / Steps to reproduce the issue

Please try to give a full example which will compile as is.

```
#include "opencv/cv.h"
int main()
{
    return 0;
}
```

Compilation line:

```
gcc -Wall main.c -o main -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib  -lopencv_imgproc -lopencv_core -lm
```

**Comment by alalek** [comment]
OpenCV is a C++ library now and actively uses C++ features, like exceptions and so on.
Direct support for C compilers has been dropped some years ago, so you should not create C applications using OpenCV.
"C-API" is not supported and should be removed totally (but we have a lack of resources to port this legacy C code to C++, so some of this code still exists right now). Also huge part of fresh OpenCV functionality is missing in "C-API".

There is no plan to fix this in OpenCV directly.

If you want to use OpenCV from C application code you need to find some implementation of C bindings which wraps OpenCV C++ functionality (al least these bindings should catch exceptions and return exit codes for user application).

**Comment by daavve** [comment]
I had the same problem trying to use someone else code from OpenCV 2.4.

I ended up just installing OpenCV 2.4, and using that.

**Comment by OliverBurgert** [comment]
This issue should be reflected in the official opencv website which says (2018-01-21) " It has C++, C, Python and Java interfaces"...
