### ISSUE TITLE
Problem with parsing aruco library with gen_java.py

### ISSUE THREAD

**Issue by smigielski** [opencv/opencv#6605]
I've enabled java parsing for aruco library as described here:
http://stackoverflow.com/questions/31710250/build-opencv-with-contrib-modules-and-java-wrapper
and it works fine, but some methods are omitted with message:
```
Return type 'Ptr_Dictionary' is not supported, skipping the function
```
- OpenCV version: 3.x-latest from git
- Host OS: Mac OS X 10.11.3 

Than I've found in gen_java.py that in the method "def add_class(self, decl)" pointers are added only if base class is defined which seems like a bug so I've reduce intent of:
```
type_dict["Ptr_"+name] = \
            { "j_type" : name,
              "jn_type" : "long", "jn_args" : (("__int64", ".nativeObj"),),
              "jni_name" : "Ptr<"+name+">(("+name+"*)%(n)s_nativeObj)", "jni_type" : "jlong",
              "suffix" : "J" }
```

The big question is if it makes any sense as I have further issues with namespaces and if I remove namespace aruco with compilation:

```
error: non-const lvalue reference to type 'Ptr<[...]>' cannot bind to a
      temporary of type 'Ptr<[...]>'
  ...(int)squaresX, (int)squaresY, (float)squareLength, (float)markerLength, Ptr<Dictionary>((Dictionary*)dictionary_nativeObj) );
```

I more into java than c++ so it sounds a bit odd to me. I would be glad for help if I go in the correct direction and the issue with addClass is a real issue or some feature that I don't know.

**Comment by smigielski** [comment]
The errors were fixed by correcting the function declaration. Passes throught reference of pointers need to be constants:
```
CV_WRAP static Ptr<GridBoard> create(int markersX, int markersY, float markerLength,
-                                         float markerSeparation, Ptr<Dictionary> &dictionary, int firstMarker = 0);
+                                         float markerSeparation, const Ptr<Dictionary> &dictionary, int firstMarker = 0);
```

After that and the return value fix the pointers are working fine. Still missing however is the support of additional namespaces. Right now I have a working workaround that I did just by removing it.

**Comment by mshabunin** [comment]
Please, take a look at the lines 1420-1456 here: https://github.com/Itseez/opencv/compare/master...mshabunin:wrap-fix

They should add namespace support and allow the modification you've described (same patch, lines 997-1001).
