### ISSUE TITLE
GoodFeaturesToTrack slow for minimumDistance of 1 pixel

### ISSUE THREAD

**Issue by embeddedprogrammer** [opencv/opencv#6613]
On my computer (Intel i7, 2.1GHz, 8GB RAM, OpenCV 3.1, Windows 7) it takes 1120 ms to find features in a 1280x720 image when the minimumDistance is set to 1. If it is set to 0 it runs in 146ms, almost 10 times faster! Any other minimumDistance runs in less than 300 ms. Unfortunately the GFTTDetector's default minimumDistance is set to 1 in the [header](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/modules/features2d/include/opencv2/features2d.hpp#L493). This makes the GFTTDetector deceptively slow, especially for new users that are testing different feature detectors.

Setting the minimumDistance to 1 doesn't actually do anything. [Line 373](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/modules/imgproc/src/featureselect.cpp#L373) shows that the minimumDistance is exclusive, meaning that even if two features are 1 pixel away, both will be kept. Furthermore, the dilate on [line 292](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/modules/imgproc/src/featureselect.cpp#L292) searches for each maximum in a 3x3 neighborhood and [Line 308](https://github.com/Itseez/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/modules/imgproc/src/featureselect.cpp#L308) filters out any features that are not a maximum, which eliminates almost all features that are less than 2 pixels away. So even if the minimumDistance were set to 2, it would give almost exactly the same results.

One solution would be to change the header file so the minimumDistance default is 0. Perhaps the best solution would be to change line 324 to check to make sure minimumDistance > 1. The minimum distance calculations could also be optimized for small minimum distances, maybe by setting a minimum cell size of 3.

Example:
```C++
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/features2d/features2d.hpp"
#include "time.h"

using namespace cv;
using namespace std;

int main(int argc, char **argv)
{
	for (int minDist = 0; minDist < 10; minDist++)
	{
		static Ptr<GFTTDetector> gfttPtr;
		gfttPtr = GFTTDetector::create(1500, .03, minDist);
		Mat img = imread("test.jpg");

		clock_t clk = clock();
		vector<KeyPoint> keypoints;
		gfttPtr->detect(img, keypoints);
		printf("Time to detect features with minDist = %d: %.0f ms\n", minDist, ((float)clock() - clk) / CLOCKS_PER_SEC * 1000);
	}
	system("pause");
}
```

**Comment by embeddedprogrammer** [comment]
Update: Somehow I didn't realize how slow OpenCV runs in Debug Mode. It's no longer a problem in Release Mode.

Comparison:
<pre>
---- Debug Mode: ----
Time to detect features with minDist = 0: 191 ms
Time to detect features with minDist = 1: 1239 ms
Time to detect features with minDist = 2: 387 ms
Time to detect features with minDist = 3: 237 ms
Time to detect features with minDist = 4: 182 ms
Time to detect features with minDist = 5: 154 ms
Time to detect features with minDist = 6: 136 ms
Time to detect features with minDist = 7: 126 ms
Time to detect features with minDist = 8: 121 ms
Time to detect features with minDist = 9: 116 ms
Press any key to continue . . .

---- Release Mode ----
Time to detect features with minDist = 0: 58 ms
Time to detect features with minDist = 1: 39 ms
Time to detect features with minDist = 2: 30 ms
Time to detect features with minDist = 3: 27 ms
Time to detect features with minDist = 4: 30 ms
Time to detect features with minDist = 5: 30 ms
Time to detect features with minDist = 6: 31 ms
Time to detect features with minDist = 7: 31 ms
Time to detect features with minDist = 8: 30 ms
Time to detect features with minDist = 9: 30 ms
Press any key to continue . . .
</pre>

**Comment by ilya-lavrenov** [comment]
It's not an issue anymore as it's stated in the previous comment. Closing.
