### ISSUE TITLE
Installing to non-default directory creates incorrect references in lib files

### ISSUE THREAD

**Issue by SSteve** [opencv/opencv#6625]
When using a non-default value for CMAKE_INSTALL_PREFIX in CMake, OpenCV lib files have incorrect directory references which makes it impossible for the libraries to load required libraries. Attempting to run the executable results in the following error:

> dyld: Library not loaded: libopencv_highgui.3.1.dylib
>   Referenced from: /Users/steve/Library/Developer/Xcode/DerivedData/deskewer-eqsavpdgycukoedxisschlsfozor/Build/Products/Debug/deskewer
>   Reason: image not found
### Please state the information for your system
- OpenCV version: 3.x
- Host OS: Mac OS X 10.11.5
- Compiler & CMake: clang-703.0.29 & CMake 3.1.0
### Library references in the file libopencv_video.3.1.0.dylib:

```
$ otool -L libopencv_video.3.1.0.dylib
libopencv_video.3.1.0.dylib:
    libopencv_video.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
    libopencv_imgproc.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
    libopencv_core.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Note that the referenced dylib files have no path.

I've found a solution and will submit a pull request later today.

**Comment by alalek** [comment]
You should use `DYLD_LIBRARY_PATH` in this case.

Refer to discussions of #6006

**Comment by SSteve** [comment]
I don't see the `DYLD_LIBRARY_PATH` setting in the CMake configuration or in OpenCVModule.cmake. I tried creating it and setting it to /usr/local/stevecv but the library files still have no path and the program won't run.

```$ otool -L libopencv_video.3.1.0.dylib
libopencv_video.3.1.0.dylib:
	libopencv_video.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
	libopencv_imgproc.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
	libopencv_core.3.1.dylib (compatibility version 3.1.0, current version 3.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

What is `DYLD_LIBRARY_PATH` supposed to do?

**Comment by alalek** [comment]
> What is DYLD_LIBRARY_PATH supposed to do?

It says where to find your libraries in case of installation into custom locations.
http://superuser.com/a/282451

Also you may read about Linux alternative: `LD_LIBRARY_PATH` and ldconfig.

**Comment by SSteve** [comment]
@alalek I've read up on the `DYLD_LIBRARY_PATH` environment variable and it looks like a bad idea to try to change it. I will try the `-DCMAKE_MACOSX_PATH=ON` flag that mshabunin recommended in #6626 and see if that works.
