### ISSUE TITLE
Changing the metric to calculate feature value!

### ISSUE THREAD

**Issue by nrkumar93** [opencv/opencv#6627]
I am trying to modify the opencv traincascade source which is used to train the cascade classifier to detect objects. The original implementation of the Viola Jones algorithm uses only grayscale images to train the classifier. I am trying the change the metric used to calculate the haar feature value over an image. If anyone had already worked in improving or modifying this particular implementation in opencv please let me know where exactly should I make this modification for haar feature metric.

The original implementation calculates the feature value by taking the difference between sum of pixel intensities of the image under black portion of the window and the sum of pixel intensities under the white portion of the window. I am planning to modify it to taking the root mean square of all the differences in all the 3 channels.

I have done all the necessary changes in image reading storage and retrieval etc. Basically everything thing else to make it compliant except the feature value calculation. Please help me locate the function which calculates the feature value. 

Thanks.

PS: The method also allows LBP and HOG features but I am interested only in modifying the Haar Features.

**Comment by StevenPuttemans** [comment]
Let me counter this proposal with the following question: 

> Adding the 3 color channels and calculating HAAR features on each of them, does this make sense?

Let me reply you with a simple answer, no it does not. Take a look at what HAAR features actually represent. As grabbed form my explanation in [OpenCV 3 Blueprints, Chapter 5](https://www.packtpub.com/application-development/opencv-3-blueprints), the feature looks for differences in pixel intensities in order to try to define edges, corners, ... being gradient based information. 

The reason why it does this on grayscale images, is because the gradients will still be there in the different challenges, just with different strenghts. So basically you will generate a redundant set of features, which increases computation time but not accuracy/efficiency ...

**Comment by nrkumar93** [comment]
Firstly, thanks for the interest and making the conversation interesting.

No. I don't think so. Say you have two exactly same images but with a small difference. The first image has pale yellow patch and the second image has a pale orange color patch or something like that. Now both the images look the same in the grayscale space and results giving the same gradients. There are numerous possible combinations like this. There could also be another case (for very pale colors or dark colors) in which the gradient just diminishes in the color space. 

So this change in the metric can express that. We have two extra components and obviously we can gain some information there. In fact, I can prove you mathematically that this is not redundant in any sense. 

Please let me know if you know where exactly that change in the metric has to be done. Thank you.

**Comment by StevenPuttemans** [comment]
> The first image has pale yellow patch and the second image has a pale orange color patch or something like that.

Considering the following universal conversion rule `GRAY = 0.2126R + 0.7152G + 0.0722B` you will see that it is quite impossible using this rule to get EXACTLY identical values inside GRAY if the RGB values are not identical. So I still disagree :)

**Comment by StevenPuttemans** [comment]
To finishing up here and provide you with an answer, the calculation of the feature itself can be found in the cascadedetect.cpp file, at this [line of code](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/cascadedetect.cpp#L670). Discussions like this should be address at the [Q&A forum](http://answers.opencv.org/questions) in the future.

@alalek this can also be closed down
