### ISSUE TITLE
How to get the regions (rectangles with coordinates) by dense optical flow?

### ISSUE THREAD

**Issue by JohnnyY8** [opencv/opencv#6636]
Hi everyone:
     I am studying something about dense optical flow in opencv, but got some problems.
     If I want to get the regions (rectangles with coordinates) of moving objects by dense optical flow, how should I do? I have gotten the dense optical flow between frames, but do not know how to get the rectangles for moving objects.
     Can anyone help me?

     Thanks a lot!

**Comment by alalek** [comment]
Ask this on http://answers.opencv.org

**Comment by JohnnyY8** [comment]
It is ok. Thank you. @alalek
