### ISSUE TITLE
How to package program using opencv by java?

### ISSUE THREAD

**Issue by meitianxiaoxu** [opencv/opencv#6637]
I write a project using java opencv, I reference this post([Introduction to Java Development](http://docs.opencv.org/2.4/doc/tutorials/introduction/desktop_java/java_dev_intro.html)).
Now, I want to package this project make it can run on other computer, but I get an error `Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java2411 in java.library.path`. I found opencv dependent on `$OPENCV_HOME/build/lib` file built before.
Hope someone can help me how to make my program `independent` run on other computer.
Thanks so muck!

**Comment by alalek** [comment]
Try to check/ask here: http://answers.opencv.org

**Comment by meitianxiaoxu** [comment]
Thank you. @alalek
