### ISSUE TITLE
Concave hulls

### ISSUE THREAD

**Issue by SylvainArd** [opencv/opencv#6639]
Hi,
I think it would be very useful to implement the concave hulls of Duckam et al. cf http://www.rotefabrik.free.fr/concave_hull/ in OpenCV future versions (and maybe others methods of getting concave hulls) ?
Thank you

**Comment by SylvainArd** [comment]
this is the paper : http://www.geosensor.net/papers/duckham08.PR.pdf
it would be interesting too to implement the others methods described in this paper

**Comment by SylvainArd** [comment]
up please

**Comment by alalek** [comment]
Feel free to contribute mentioned algorithm in opencv_contrib.
I think it can be placed into [ximgproc](https://github.com/Itseez/opencv_contrib/tree/master/modules/ximgproc) module.

**Comment by SylvainArd** [comment]
I'm unable to implement this algorithm, is there any among you who is able to ?

**Comment by henriquenunez** [comment]
Is this one still a need?

**Comment by SylvainArd** [comment]
yes but four years after it is late !

**Comment by alalek** [comment]
> The concave hull implementation is released under a LGPL licence

OpenCV doesn't accept LGPL code (not compatible with OpenCV license).
Closing as mentioned implementation has legal blocker.
