### ISSUE TITLE
cv::imread() goes to endless while() loop

### ISSUE THREAD

**Issue by almln** [opencv/opencv#6641]
It seems that here is some problems with imread(). I try to load image

![jessica_collins](https://cloud.githubusercontent.com/assets/12760584/15818591/53b42782-2bef-11e6-9633-c06c45238103.jpeg)

but imread goes to endless loop while reading EXIF info of this file inside the ExifReader::getExif(). I think this is the problem with seeking forward-backward in file (bytesToSkip < markerSize).

### Version and paltform
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 15.04)

### In which part of the OpenCV library you got the issue?
reading an jpg image

### Code example to reproduce the issue
```.cpp
#include "opencv2/core.hpp"
#include "opencv2/imgcodecs.hpp"

using namespace cv;

int main()
{
    cv::Mat qq = cv::imread("Jessica_Collins.jpeg");
    return 0;
}
```

**Comment by kevin-coder** [comment]
After investigation, I found that the root cause of this issue is:
In function "getExif", both of the values for appMarker[0] and appMarker[1] are '\0', but it cannot match any of the termination condition. So endless loop will happen. I will create a PR for this issue.

**Comment by kevin-coder** [comment]
PR https://github.com/Itseez/opencv/pull/6700 has been created for this issue.
