### ISSUE TITLE
cv2.moments incorrect for float coordinates

### ISSUE THREAD

**Issue by david-zwicker** [opencv/opencv#6643]
According to the documentation, the `moments` function can calculate image moments for polygons with integer or float coordinates. However, only integer coordinates seem to lead to correct results as illustrated by the following python script:

```
import numpy as np
import cv2
c = [[0, 0], [10, 15], [20, 0]]
print(cv2.moments(np.array(c, np.int))['m00'])
print(cv2.moments(np.array(c, np.float))['m00'])
```

The first line prints the correct area of `150.0`, while the second line prints `45.0`, which is wrong. Interestingly, changing the `dtype` to `np.double` or `np.uint8` also results in `45.0`, while `np.uint` yields `150.0`.

I'm on MacOS, where I use python 2.7 and have opencv 3.1.0 installed via macports.

**Comment by mshabunin** [comment]
When input data is an array of 2D points of type CV_32F or CV_32S, then they are considered as a contour coordinates.
How does it work:
1. `np.int` is actually `int64`, but in OpenCV it will be [converted](https://github.com/Itseez/opencv/blob/8011be281034df41470b6680913f20c39551ea33/modules/python/src2/cv2.cpp#L287-L292) to CV_32S resulting in contour moments calculation
2. `np.float` is actually `float64` and in OpenCV it will [**not** be converted](https://github.com/Itseez/opencv/blob/8011be281034df41470b6680913f20c39551ea33/modules/python/src2/cv2.cpp#L283) to different type, but used as CV_64F resulting in image moments calculation

So, if you want to run contour moments calculation from Python, you should set exact numpy types for the input array (`np.int32` and `np.float32`). 

Not sure whether it is a bug, but this behaviour definitely should be described in the documentation.

**Comment by david-zwicker** [comment]
Thanks! I now understand the behavior and this helps solving a bug I was encountering. However, I still think that the behavior is very confusing and a potential pitfall for people using the `moments` functions. I think the underlying problem is that the function accepts both images and coordinate sequences and that it is not transparent how the data is interpreted – it's certainly confusing that the interpretation depends on the datatype. The clearest solution might be to split the functionality in two functions, but this would of course break compatibility. However, a clear warning in the documentation might be a good intermediate solution.

**Comment by anirudt** [comment]
Could I try solving this issue? I see that we'd have to change the documentation in  opencv/modules/imgproc/include/opencv2/imgproc.hpp.

**Comment by mshabunin** [comment]
@anirudt , yes, you are welcome. This is correct file.
