### ISSUE TITLE
cv2.GaussianBlur naming convention

### ISSUE THREAD

**Issue by impact27** [opencv/opencv#6647]
### Please state the information for your system
- OpenCV version: 3.1.0_3
### In which part of the OpenCV library you got the issue?

-python cv2 interface
### Expected behaviour

I would expect the name of the function to be
cv2.gaussianBlur
### Actual behaviour

There is a capital letter to this function for some reason. 
The functions in python (and in cv2) tend to start with a small letter.
cv2.GaussianBlur
### Code example to reproduce the issue / Steps to reproduce the issue

Please try to give a full example which will compile as is.

```
import cv2
help(cv2.medianBlur)
help(cv2.blur)
help(cv2.GaussianBlur)#this does exist
help(cv2.gaussianBlur)#this doesn't
```

**Comment by paroj** [comment]
the problem originates from the C++ API, so the change should be made in locks step. However this will break existing code, so my ETA would be OpenCV 4.0.

**Comment by impact27** [comment]
Wouldn't it make sense to let the two names work and just add a depreciation warning to the incorrect one? This way existing code would not be broken.

**Comment by sanjay-1** [comment]
I believe this is not a problem.  This is a low priority issue that is of minor benefit to users.

Here are a few other functions in OpenCV that also have their first letters capitalized.  They are all named after prominent mathematicians/scientists, and so out of respect, their names are capitalized:
- cv2.Canny()
- cv2.GaussianBlur()
- cv2.HoughLines() and cv2.HoughCircles()
- cv2.Laplacian()
- cv2.Sobel()
- cv2.Scharr()

There are other functions in OpenCV that are capitalized but not associated with a person.  Capitalization is a matter of convention.  With OpenCV being open-source and community developed, it will happen that different developers use different convention.

**Comment by alalek** [comment]
OpenCV Wiki states this:

https://github.com/opencv/opencv/wiki/Coding_Style_Guide#naming-conventions

> - Class names start with a capital letter.
> - methods’ and functions’ names start with a small latter, unless they are named after the author of the algorithm, e.g. cv::Sobel(), in which case they can start with a capital letter.
