### ISSUE TITLE
Several No Package Found Issues?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#6656]
### Please state the information for your system
- OpenCV version: 3.x (git)
- Host OS: Linux (Ubuntu 16.04) 
- Compiler & CMake: GCC 5.3.1 & CMake 3.5.1

### In which part of the OpenCV library you got the issue?
During Compilation, several No Package Found

> ……
> — Checking for module ‘gstreamer-video-0.10’
> — No package ‘gstreamer-video-0.10’ found
> — Checking for module ‘gstreamer-app-0.10’
> — No package ‘gstreamer-app-0.10’ found
> — Checking for module ‘gstreamer-riff-0.10’
> — No package ‘gstreamer-riff-0.10’ found
> — Checking for module ‘gstreamer-pbutils-0.10’
> — No package ‘gstreamer-pbutils-0.10’ found
> ……
> — Checking for module ‘libavresample’
> — No package ‘libavresample’ found

### Expected behaviour
I installed FFmpeg manually, so I've got libswresample already. From the aspect of functionality, libavresample should be the same as libswresample. Why OpenCV searches libavresample only? But not libswresample? Also, I noticed libswcale is also installed with FFmpeg. Does OpenCV intentionally ignore libswcale and libswresample? I mean: is libsw*  NOT gpl ?

In addition, what packages of gstreamer I need to install for the above mentioned No package 'gstreamer-*' found ???

### Actual behaviour
Just want to remove some of the warnings.

Thank you very much.

Best Regards
Pei

**Comment by alalek** [comment]
These diagnostic messages are not warnings actually.
If you want to eliminate these messages, then you should install these optional dependencies or just [disable](https://github.com/Itseez/opencv/blob/3.1.0/CMakeLists.txt#L174-L176) support of these components completely.

We support both ffmpeg and libav and `libswresample` is missing in libav.
Also we prefer to support **default** installations of ffmpeg which provide `libavresample` without any problems. Currently there is no serious reason to support `libswresample`.

**Comment by maddanio** [comment]
actually ffmpeg 4.0 has deprecated libavresample and when compiling from source it is no longer built by default
