### ISSUE TITLE
OpenCVConfig.cmake keeps old OpenCV_CONFIG_PATH in CMake cache

### ISSUE THREAD

**Issue by herr-biber** [opencv/opencv#6659]
Hi everybody,

this issue regards a system with coexisting OpenCV 2 *and* OpenCV 3.
OpenCV 2 system install at ```/usr```
OpenCV 3 manual install at ```/usr/local/opencv/3.1.0```

State you have a CMake project  which ```find_package()``` OpenCV 2.4 like this:
```find_package(OpenCV 2.4 REQUIRED) ```
you *cleanly* build it and ```${OpenCV_CONFIG_PATH}``` equals to ```/usr/share/OpenCV```.

When changing your CMakeLists.txt on the *already built* project to
```find_package(OpenCV 3 REQUIRED) ```,
```${OpenCV_CONFIG_PATH}``` still equals to ```/usr/share/OpenCV```,
although it should equal to ```/usr/local/opencv/3.1.0/share/OpenCV```.

This affects setting the wrong ```${OpenCV_INCLUDE_DIRS}``` and thus crashes the build.

I located the bug in this line:
https://github.com/Itseez/opencv/blob/master/cmake/templates/OpenCVConfig.cmake.in#L114
```get_filename_component(OpenCV_CONFIG_PATH "${CMAKE_CURRENT_LIST_FILE}" PATH CACHE)```

Removing the ```CACHE``` should fix the problem, since currently it will not be overwritten, when already in cache. Reading from the comment above the line ```${OpenCV_CONFIG_PATH}``` must equal to the path of the current file and thus not rely on CACHE.

### system information
- OpenCV version: 2.4 AND 3.1 (coexisting)
- Host OS: Linux (Ubuntu 14.04), but should be ANY
- CMake: ANY

### code to reproduce
I took the following code to produce the bug:
```
cmake_minimum_required (VERSION 2.8.11)
project (opencv-cmake-find-bug)
LIST(APPEND CMAKE_PREFIX_PATH /usr/local/opencv/3.1.0/share/OpenCV)
MESSAGE(WARNING "prefix ${CMAKE_PREFIX_PATH}")

MESSAGE(WARNING "install path ${OpenCV_INSTALL_PATH}")
MESSAGE(WARNING "config path ${OpenCV_CONFIG_PATH}") # if this is in cache, find_package() below won't overwrite it

find_package(OpenCV 2.4 REQUIRED) # change this to 3 after running cmake once
MESSAGE(WARNING "version ${OpenCV_VERSION}")
MESSAGE(WARNING "install path ${OpenCV_INSTALL_PATH}") 
MESSAGE(WARNING "config path ${OpenCV_CONFIG_PATH}") # look at the output of this message
MESSAGE(WARNING "include dirs ${OpenCV_INCLUDE_DIRS}")
MESSAGE(WARNING "libs ${OpenCV_LIBS}")
```

I'd be happy to file a pull-request if you agree that the current behavior is not intended.

Cheers!

**Comment by alalek** [comment]
All CMake variables are binded to some scope and usually not available in parent scopes. Also CMake hasn't native support for "global" variables.
So CMake "cache" is frequently used to simulate "global" variables.

Windows `find_package` process uses 2 staged OpenCVConfig.cmake (2 files):
- outer stage is just a wrapper which detects MSVC and platform
- nested stage uses "CACHE" to popup actual value to outer script

I believe these behaviours should be fixed somewhere in this PR: #5980

**Comment by herr-biber** [comment]
Thanks Alex,

looks like your PR fixes this issue. I vote for merging it :+1: 

Cheers

**Comment by alalek** [comment]
@herr-biber PR #5980 is merged. Does it work for you?
