### ISSUE TITLE
read() on saved RTrees is broken (not a duplicate of http://code.opencv.org/issues/4402)

### ISSUE THREAD

**Issue by JerryRubinow** [opencv/opencv#6662]
Open CV 3.1
Windows 10
Visual Studio 2015

This bug is in cv::ml:: RTrees.

I am writing a trained RTrees out using FileStorage, which appears to work correctly.  Doing a read() to deserialize causes a crash in In rtrees.cpp, line 335, in the read() method of DTreesImplForRTrees:
`oobError = (double)fn["oob_error"];`

This happens regardless of whether I am serializing using a MEMORY- or file-based FileStorage object.  The FileNode produced by getFirstTopLevelNode() does not appear to contain the expected nodes in it.

Here is code which produces the issue for memory FileStorage:

```
cv::FileStorage fsWrite("my_tree", cv::FileStorage::WRITE + cv::FileStorage::MEMORY + FileStorage::FORMAT_XML);
Ptr<cv::ml::Rtrees> model;
[code to train model]
model->write(fsWrite);
std::string modelString = fsWrite.releaseAndGetString(); // produces proper-looking string with xml in it

Ptr<cv::ml::RTrees> resultModel = Algorithm::read<ml::RTrees>(fsWrite.getFirstTopLevelNode());
```

And here for file-based:

```
cv::FileStorage fsWrite("D:\\test.xml", cv::FileStorage::WRITE + FileStorage::FORMAT_XML);
m_ptrModel->write(fsWrite);
cv::FileStorage fsRead("D:\\test.xml", FileStorage::READ + FileStorage::FORMAT_XML);
m_ptrModel = cv::Algorithm::read<ml::RTrees>(fsRead.getFirstTopLevelNode());
```

Here is what the modelString and file that are produced by the write() look like:

```
<?xml version="1.0"?>
<opencv_storage>
<is_classifier>0</is_classifier>
<var_all>13</var_all>
<var_count>12</var_count>
<ord_var_count>13</ord_var_count>
<cat_var_count>0</cat_var_count>
<training_params>
  <use_surrogates>0</use_surrogates>
  <max_categories>10</max_categories>
  <regression_accuracy>9.9999997764825821e-03</regression_accuracy>
  <max_depth>25</max_depth>
  <min_sample_count>10</min_sample_count>
  <cross_validation_folds>0</cross_validation_folds>
  <nactive_vars>4</nactive_vars></training_params>
<global_var_idx>1</global_var_idx>
<var_idx>
  0 1 2 3 4 5 6 7 8 9 10 11</var_idx>
<var_type>
  0 0 0 0 0 0 0 0 0 0 0 0 0</var_type>
<cat_ofs>
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</cat_ofs>
<missing_subst>
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</missing_subst>
<oob_error>0.</oob_error>
<ntrees>1</ntrees>
<trees>
  <_>
    <nodes>
      <_>
        <depth>0</depth>
        <value>2.7725000000000000e+00</value>
        <splits>
          <_><var>7</var>
            <quality>1.2565179687500000e+04</quality>
            <le>5.8210000991821289e+00</le></_></splits></_>
      <_>
        <depth>1</depth>
        <value>2.9880095923261392e+00</value>
        <splits>
          <_><var>7</var>
            <quality>1.1172947265625000e+04</quality>
            <le>1.2557047605514526e+00</le></_></splits></_>
      <_>
        <depth>2</depth>
        <value>3.</value></_>
      <_>
        <depth>2</depth>
        <value>2.7368421052631580e+00</value>
        <splits>
          <_><var>3</var>
            <quality>438.</quality>
            <le>-1.2632201194763184e+01</le></_></splits></_>
      <_>
        <depth>3</depth>
        <value>3.</value></_>
      <_>
        <depth>3</depth>
        <value>2.</value></_>
      <_>
        <depth>1</depth>
        <value>2.</value></_></nodes></_></trees>
</opencv_storage>
```

You should be able to duplicate the problem by taking the model string here, sticking it in a file, and simply doing a read() on it, something like:

```
#include "opencv2\core\core.hpp"
#include "opencv2\ml\ml.hpp"
cv::FileStorage fsRead("D:\\test.xml", FileStorage::READ + FileStorage::FORMAT_XML);
Ptr<cv::ml::RTrees> resultModel = Algorithm::read<ml::RTrees>(fsWrite.getFirstTopLevelNode());
```

**Comment by sovrasov** [comment]
@JerryRubinow you should pass `fsRead.root()` into the `read` method.
`root()` returns  the top-level mapping and `getFirstTopLevelNode()` returns the first node form this mapping.
Obviously the first top level node node (`is_classifier` in current example) doesn't contains `oob_error` node and others.

**Comment by berak** [comment]
i'd like to reopen this issue (or at least, restart the discussion), since the recommended fix does not work with current 3.2.

i have no idea, how above xml was generated, but both
the [legacy 2.4 models](https://github.com/opencv/opencv_extra/blob/master/testdata/ml/legacy/dtree_abalone.xml#L3)  and current 3.2 models  have an additional node there, 3.2 looks like this:

```
<?xml version="1.0"?>
<opencv_storage>
<opencv_ml_rtrees>
  <format>3</format>
  <is_classifier>1</is_classifier>
  <var_all>6</var_all>
  <var_count>5</var_count>
  <ord_var_count>5</ord_var_count>
  <cat_var_count>1</cat_var_count>
  <training_params>
    <use_surrogates>0</use_surrogates>
    <max_categories>10</max_categories>
    <regression_accuracy>0.</regression_accuracy>
    <max_depth>5</max_depth>
    <min_sample_count>10</min_sample_count>
    <cross_validation_folds>0</cross_validation_folds>
    <nactive_vars>0</nactive_vars></training_params>
  <global_var_idx>1</global_var_idx>
  <var_idx>
    0 1 2 3 4</var_idx>
  <var_type>
    0 0 0 0 0 1</var_type>
  <cat_ofs>
    0 0 0 0 0 0 0 0 0 0</cat_ofs>
  <class_labels>
    0 1</class_labels>
  <missing_subst>
    0. 0. 0. 0. 0. 0.</missing_subst>
  <oob_error>0.</oob_error>
```

so, trying to read from fs.root() will fail to reach oob_error (first thing [RTrees tries to read](https://github.com/opencv/opencv/blob/master/modules/ml/src/rtrees.cpp#L335)) 
resulting in:

```
FileStorage fs(filepath, FileStorage::READ);
Ptr<RTrees> rtree = Algorithm::read<RTrees>(fs.root());
cerr << rtree->isTrained(); // false

FileStorage fs(filepath, FileStorage::READ);
Ptr<RTrees> rtree = Algorithm::read<RTrees>(fs.getFirstTopLevelNode());
cerr << rtree->isTrained(); // true

// note, that this is also using getFirstTopLevelNode() ! :
Ptr<ml::RTrees> rtree = Algorithm::load<ml::RTrees>(filepath);
cerr  << rtree->isTrained(); // true
```

imho, we should prefer the latter, since it would avoid having multiple implementations, doing possibly different things.

**Comment by sovrasov** [comment]
Ok, it seems, I should correct the documentation once again.
So to load model it's needed to pass node which contains this model into `Algorithm::read()`.

**Comment by berak** [comment]
can't we use `Algorithm::load<SomeClass>(filename)` , and encapsulate / hide it ?

at least, for the ml classes, (yes it can be an arbitrary Node for anyting else)

**Comment by sovrasov** [comment]
Or we can create an overloaded version of the `Algorithm::read<SomeClass>(filename)`.

**Comment by sovrasov** [comment]
But in this case LSP requires to implement such modified methods in any derivative of `Algorithm`.

**Comment by alalek** [comment]
Checked sample code from https://github.com/opencv/opencv/issues/6662#issuecomment-273053522 . It works fine without crashes.

Difference between `fs.root()` and `fs.getFirstTopLevelNode()` is out of scope of ML module.
