### ISSUE TITLE
Error during make in opencv

### ISSUE THREAD

**Issue by kyrs** [opencv/opencv#6666]
Hi, I am trying to build opencv on my Amazon instance but every time when I run  make. I get following error `Linking CXX executable ../../bin/opencv_perf_core
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::~RE()':
ts_gtest.cpp:(.text._ZN7testing8internal2RED2Ev+0xf): undefined reference to `regfreeA'
ts_gtest.cpp:(.text._ZN7testing8internal2RED2Ev+0x18): undefined reference to `regfreeA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::FullMatch(char const*, testing::internal::RE const&)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE9FullMatchEPKcRKS1_+0x2a): undefined reference to `regexecA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::PartialMatch(char const*, testing::internal::RE const&)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE12PartialMatchEPKcRKS1_+0x2a): undefined reference to `regexecA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::Init(char const*)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE4InitEPKc+0x55): undefined reference to `regcompA'
ts_gtest.cpp:(.text._ZN7testing8internal2RE4InitEPKc+0x7b): undefined reference to `regcompA'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_perf_core] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
make: *** [all] Error 2
` can you please help me out with it. I have checked that I have all the necessary dependency.

**Comment by alalek** [comment]
Looks like there is something bad is with your build environment.
Unfortunately we can't reproduce or investigate this issue.

Hints:
- "regex.h" (some conflicts with boost library is possible)
- "-DGTEST_HAS_POSIX_RE=0" compiler flag (you can try to pass it via "CXXFLAGS" environment variable to CMake)

Do you really need tests on Amazon instance? You can try to disable them.

Are you able to build any Google Test application (GoogleTest itself)?
