### ISSUE TITLE
Occasional Segmentation fault in cv::Mat::push_back()

### ISSUE THREAD

**Issue by djebm2** [opencv/opencv#6670]
When running this code, the second line of the for loop seg fault. Not always, but pretty often.
Do you have some thoughts ?

```
int computeHOG (const std::vector<cv::Mat>& images, cv::Mat& hogData, const bool gray)
{
	std::vector<float> descriptor;
	cv::HOGDescriptor hogEngine;
	hogEngine.nbins = 9;
	hogEngine.blockSize = cv::Size(16,16);
	hogEngine.cellSize = cv::Size(8,8);
	hogEngine.winSize = cv::Size(images[0].cols, images[0].rows);

	for (size_t i = 0; i < images.size(); ++i)
	{
		hogEngine.compute(images[i], descriptor, cv::Size(8,8), cv::Size(0,0));
		hogData.push_back(cv::Mat(descriptor).reshape(1,1));  **// sometimes seg. fault here**
	}

	return 0;
}
```

**Comment by ilya-lavrenov** [comment]
@djebm2, I don't believe that you have SEGFAULTs here. But, please, check that pushed vector has the same type and length as matrix rows.

I've added additional tests and errors message to confirm that everything is OK in this case. See https://github.com/opencv/opencv/pull/6911
