### ISSUE TITLE
cvLoadImage and imread do not handle exif orientation similarly

### ISSUE THREAD

**Issue by guillaume-tgl** [opencv/opencv#6673]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Mac OS X 10.11.4
### In which part of the OpenCV library you got the issue?

Examples:
- imgcodecs
- reading an image with exif orientation
### Expected behaviour

Since OpenCV 3.1, exif orientation is now used to rotate images properly. imread and cvLoadImage should output an image rotated accordingly to the exif orientation.
### Actual behaviour

imread outputs an image with correct orientation, cvLoadImage seems to ignore the exif orientation, though they seem to call the same internal method to read a JPEG image.
### Code example to reproduce the issue / Steps to reproduce the issue

Please try to give a full example which will compile as is.

```
#include <opencv2/opencv.hpp>
#include <opencv/highgui.h>

int main(int argc, char** argv){

   IplImage* image = cvLoadImage("input.jpg", CV_LOAD_IMAGE_COLOR);
   cvSaveImage("output_cvloadImage.jpg", image);

   Mat mat = imread("input.jpg", CV_LOAD_IMAGE_COLOR);
   imwrite("output_imread.jpg", mat);

   return 0;
}
```

input.jpg is portrait with Orientation: 6 (Rotated 90° CCW)
output_cvloadImage.jpg is landscape
output_imread.jpg is portrait

**Comment by catree** [comment]
OpenCV C interface is no longer maintained (no more additional functionality, only bug fixes). You have to use the C++ interface if you want to use this functionality and in general also. 

More information on this Q&A in 2013: [OpenCV will drop C API support soon](http://answers.opencv.org/question/17546/opencv-will-drop-c-api-support-soon/).

**Comment by ilya-lavrenov** [comment]
@guillaume-tgl, could you attach an image to test on?

**Comment by guillaume-tgl** [comment]
Sure : 
![input](https://cloud.githubusercontent.com/assets/2244170/16908241/45570dac-4cca-11e6-813c-32830cfb42f8.jpg)

**Comment by alalek** [comment]
C API ("cv" prefix) is obsolete and should not be used in new programs, but there are still some programs which use it. So it is unwanted to change existed behaviour.
Related issue of changed behaviour: #6348

I prefer to leave this "as is": cv::imread uses EXIF (by default, until we add control flag for this behaviour), cvLoadImage doesn't use EXIF information.
