### ISSUE TITLE
viz::Viz3d::converTo3DRay ==> not possible to transform 2D to 3D coordinates using this method - Any other method ?

### ISSUE THREAD

**Issue by henryjulie** [opencv/opencv#6679]
### Information for my system
- OpenCV version: 2.4 .12
- Host OS: Windows 8
- CMake 3.4.1
- VTK-7.0.0
### OpenCV library
- vizimpl
- 2D to 3D coordinates conversion with viz::Viz3d::converTo3DRay method
### Expected behaviour

Transforms a point in window coordinate system to world coordinate system 
### Actual behaviour

Transforms a point in window coordinate system to a 3D ray in world coordinate system (description of the method)
In my code, the output origin of the ray is the position of my camera and doesn't take into account any changes of 2D coordinates.
Only direction changes, but it is strange it's not what I want :(
Is it possible to have a viz::Viz3d::convertToWorldCoordinates ?
### Additional description

I tried to modify myself the method, but it doesn't work.

void cv::viz::Viz3d::VizImpl::converTo3DRay(const Point3d &window_coord, Point3d &origin, Vec3d &direction)
{
    //Vec4d world_pt;
    Vec3d world_pt;
    vtkInteractorObserver::ComputeDisplayToWorld(renderer_, window_coord.x, window_coord.y, window_coord.z, world_pt.val);
    //Vec3d cam_pos(renderer_->GetActiveCamera()->GetPosition());
    //origin = cam_pos;
    //direction = normalize(Vec3d(world_pt.val) - cam_pos);
    origin = Point3d(world_pt);
}
### Code example to reproduce the issue
# include "stdafx.h"
# include <opencv2/viz/vizcore.hpp>
# include <opencv2/calib3d/calib3d.hpp>
# include "opencv2/highgui/highgui.hpp"
# include "opencv2/imgproc/imgproc.hpp"
# include <iostream>
# include <fstream>

using namespace cv;
using namespace viz;
using namespace std;

int main()
{

```
bool goingLeft = true;
Viz3d myWindow("My Window");

myWindow.showWidget("Coordinate Widget", viz::WCoordinateSystem());
Point3f cam_pos(-30.0f, -10.0f, -10.0f), cam_focal_point(1.0f, 1.0f, 1.0f), cam_dir(-1.0f, 0.0f, 0.0f);
Vec3f camp_pos_vec = cam_pos;
Vec3f cam_focal_vec = cam_focal_point;
Vec3f cam_dir_vec = cam_dir;
Affine3f cam_pose = viz::makeCameraPose(camp_pos_vec, cam_focal_vec, cam_dir_vec);

myWindow.setViewerPose(cam_pose);

Point2f center(10.0f, 20.0f);
Point3f coordinate(center.x, center.y, 0.0f);
cout << coordinate;
Point3d origin_world;
cout << origin_world;
Vec3d direction(1, 0, 0);
cout << direction;
while (true) {

    if (coordinate.x > 500) {
        goingLeft = true;
    }
    if (coordinate.x < 0) {
        goingLeft = false;
    }
    if (goingLeft) {
        coordinate.x = coordinate.x - 1;
        coordinate.y = coordinate.y - 1;
    }
    else {
        coordinate.x = coordinate.x + 1;
        coordinate.y = coordinate.y + 1;
    }


    myWindow.converTo3DRay(coordinate, origin_world, direction);
    cout << origin_world;
    cout << direction;
    WLine line(origin_world, Point3d(0, 0, 0), Color::white());
    myWindow.showWidget("Line Widget", line);

    myWindow.spinOnce(1,true);
}

return 0;
```

}

**Comment by poiex** [comment]
I have the same problem. Have you found a solution?

**Comment by poiex** [comment]
I figured out the problem. There is a bug inside the function:
void cv::viz::Viz3d::VizImpl::converTo3DRay(const Point3d &window_coord, Point3d &origin, Vec3d &direction) 
in the file vizimpl.cpp.

Here is the function as it is originally defined:

void cv::viz::Viz3d::VizImpl::converTo3DRay(const Point3d &window_coord, Point3d &origin, Vec3d &direction)
{
    Vec4d world_pt;
    vtkInteractorObserver::ComputeDisplayToWorld(renderer_, window_coord.x, window_coord.y, window_coord.z, world_pt.val);
    Vec3d cam_pos(renderer_->GetActiveCamera()->GetPosition());
    origin = cam_pos;
    direction = normalize(Vec3d(world_pt.val) - cam_pos);
}

If you see, 'origin' is returned as the position of the camera. That's why it never changes if the cameras stays still. The correct value should be from 'world_pt.val'. Here below it is how I changed the function.

void cv::viz::Viz3d::VizImpl::converTo3DRay(const Point3d &window_coord, Point3d &origin, Vec3d &direction)
{
    double wrldpt[4];
    vtkInteractorObserver::ComputeDisplayToWorld(renderer_, window_coord.x, window_coord.y, window_coord.z, wrldpt);
    Vec3d cam_pos(renderer_->GetActiveCamera()->GetPosition());
    origin.x = wrldpt[0] / wrldpt[3];
    origin.y = wrldpt[1] / wrldpt[3];
    origin.z = wrldpt[2] / wrldpt[3];
    direction = normalize(Vec3d(wrldpt) - cam_pos);
}

Note that the division is needed as 'wrldpt' is returned in homogeneous coordinates.

Hope someone will fix it.

Cheers.
