### ISSUE TITLE
Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

### ISSUE THREAD

**Issue by vaidyasm** [opencv/opencv#6680]
Error message: 

```
(-c:9121): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
```

The following three python2.7 statements that reproduce such error:

```
>>> import cv2
>>> import matplotlib.pyplot as plt
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
>>> cv2.namedWindow("test")
(-c:9121): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)
```

As suggested by [@yosinski on 2015-Jul-10](https://github.com/yosinski/deep-visualization-toolbox/issues/10#issuecomment-120416297), I've verified gtk versions _caffe.so and cv2.so (compiled and installed OpenCV from source) had been linked against to be the same.

```
$ ldd `python2.7 2>/dev/null -c "import os; import caffe; print os.path.join(caffe.__path__[0], '_caffe.so')"` | grep -i gtk
    libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fb8eba6a000)
$ ldd `python2.7 -c "import cv2; print cv2.__file__;"` | grep -i gtk
    libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fbfb19ea000)
```

Tried other suggestions posted on that issue without luck.

How to debug this issue?

**Comment by gcucurull** [comment]
I think that this error may be caused by matplotlib and the default backend it is using, which could be GTK3.

Check your `matplotlibrc` and which backend are you using.

**Comment by Naveenkariyappa** [comment]
I am facing a similar issue, I feel it is due to OpenCV modules or matplotlib.

**Comment by alalek** [comment]
You should rebuild OpenCV with required GTK version, or disable GTK backend at all.
This can't be fixed automatically in OpenCV because this conflict is on external dependencies.

**Comment by loulansuiye** [comment]
I met the same problem but the python import work well ,the text remind me modpython

**Comment by loulansuiye** [comment]
(modpython:16462): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by Ehsan-Yaghoubi** [comment]
> I think that this error may be caused by matplotlib and the default backend it is using, which could be GTK3.
> 
> Check your `matplotlibrc` and which backend are you using.

I use ubuntu 20.04, python 3.8, and installed opencv-python 4.3.0.36 (which are the latest version of all by now). 
when I import matplotlib (whether I use it in the body code or not), I face with the title error (**Gtk-Erorr**), and when I only import cv2 and use it in my codes I run it to the following error (while the image is shown as black): **Qt: Session management error: None of the authentication protocols specified are supported**

any suggestion is appreciated.

**Comment by Nol2loN** [comment]
how to usb

import gi
gi.require_version('Gtk', '2.0')
from gi.repository import Gtk

or

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

**Comment by Petros626** [comment]
> You should rebuild OpenCV with required GTK version, or disable GTK backend at all. This can't be fixed automatically in OpenCV because this conflict is on external dependencies.

I would give this a try can you guide me?
