### ISSUE TITLE
Can't change camera resolution on Windows (solution attached)

### ISSUE THREAD

**Issue by maff91** [opencv/opencv#6682]
### Please state the information for your system
- OpenCV version: 3.1
- Host OS:  Windows 10

### In which part of the OpenCV library you got the issue?
**cap_dshow.cpp**

### Expected behaviour
Change resolution for webcam (MS HD3000, YUY2) 

### Actual behaviour
VideoCapture.set(...) for height and width does nothing. Camera rejects everything

### Additional description
**My solution for this issue you can find on** [stackoverflow](http://stackoverflow.com/questions/37722992/cant-change-webcam-resolution-with-opencv-in-python-windows)

### Code example to reproduce the issue / Steps to reproduce the issue
```
    #include "stdafx.h"
    #include <opencv2/opencv.hpp>
    #include <opencv\highgui.h>

    using namespace cv;

        int main() {
	    Mat image;                     //Create Matrix to store image
	    VideoCapture cap;              //initialize capture
	    cap.open(CAP_DSHOW + 1);
	
	    cap.set(CAP_PROP_FRAME_WIDTH, 1280.0);
	    cap.set(CAP_PROP_FRAME_HEIGHT, 720.0);

	    do {
		    cap >> image;              //copy webcam stream to image
		    imshow("window", image);   //print image to screen
	    } 
	    while (waitKey(1) != 'q');

	    destroyAllWindows();
	
	    return 0;
    }
```

**Comment by mshabunin** [comment]
@maff91 , feel free to provide a pull request with your fix.
