### ISSUE TITLE
VideoCapture - provide descriptive error on failed .dll load

### ISSUE THREAD

**Issue by techtonik** [opencv/opencv#6719]
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Windows Vista
### In which part of the OpenCV library you got the issue?
- videocapture

watchm.py:

```
import cv as cv2

video = cv2.VideoCapture('bear.flv')
if video.isOpened():
  print("success")
else:
  print("fail")
  print(video.error())

res, frames = video.read()
for frame in frames:
  cv2.imshow('Original', frame)
  cv2.waitKey(1)
```
### Expected behaviour

3.1.0

```
> python watchm.py
fail
error loading ffmpeg movie converter
```
### Actual behaviour

3.1.0

```
> python watchm.py
fail
Traceback (most recent call last):
  File "watchm.py", line 10, in <module>
    print(video.error())
AttributeError: 'cv2.VideoCapture' object has no attribute 'error'
```
### Additional description

Troubleshooting why opencv can not open video is impossible, which is frustrating for many beginners. It would be nice to have better error reporting to be able to answer why videos are not loaded.

http://answers.opencv.org/question/1965/cv2videocapture-cannot-read-from-file/
### Code example to reproduce the issue / Steps to reproduce the issue

```
import cv2
print cv2.__version__

video = cv2.VideoCapture('E:/_CRAYB~1/reference001.mov')
if video.isOpened():
  print("success")
else:
  print("fail")
  print(video.error())
```

**Comment by techtonik** [comment]
This is the problem with my setup and still there is no any diagnostic info http://stackoverflow.com/a/8430095/239247

**Comment by techtonik** [comment]
@alalek is it possible to provide more information about ffmpeg loading errors for better troubleshooting?

**Comment by alalek** [comment]
Modern OpenCV (3.4.3+) has these runtime flags to dump details:
- `OPENCV_LOG_LEVEL=DEBUG`
- `OPENCV_VIDEOIO_DEBUG=1` ( [more info](https://docs.opencv.org/3.4/de/db1/group__videoio__registry.html) )
