### ISSUE TITLE
Python module can not find ffmpeg dll

### ISSUE THREAD

**Issue by techtonik** [opencv/opencv#6720]
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Windows Vista

### In which part of the OpenCV library you got the issue?
videocapture

### Additional description
When opencv3 is installed into virtualenv on Windows using opencv_python-3.1.0-cp27-cp27m-win32.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/ it is unable to use its .dlls unless those copied into the dir with script.

**Comment by alalek** [comment]
Windows way is to set "PATH" variable to .dll location:
https://github.com/Itseez/opencv/blob/3.1.0/samples/python/_run_winpack_demo_python27.cmd#L8-L9

Also you can put .dlls into system32 folder, but it requires administrative privileges and it is not safe in some cases (be careful with multiple OpenCV installations).

You can find more information in [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179(v=vs.85).aspx) in section "Searching for DLLs and Dependencies".

**Comment by techtonik** [comment]
Why `cv2.pyd` can't load .dlls already present in its directory?

**Comment by techtonik** [comment]
@alalek why it can't use AddDllDirectory to add its own path? Or https://msdn.microsoft.com/en-us/library/windows/desktop/hh310515(v=vs.85).aspx

**Comment by alalek** [comment]
Looks like these calls are Windows 8+ only (they don't work on Vista).

**Comment by alalek** [comment]
> Why cv2.pyd can't load .dlls already present in its directory?

I downloaded "opencv_python-3.1.0+contrib_opencl-cp35-cp35m-win_amd64.whl" package from mentioned link and looks like it doesn't put ffmpeg wrapper dll near cv2.pyd file.
Do you have another layout?

There is no problem to load dll via full absolute path: https://github.com/Itseez/opencv/blob/3.1.0/modules/videoio/src/cap_ffmpeg.cpp#L105
But we need to determine this path.

**Comment by techtonik** [comment]
> Do you have another layout?

I've got these files inside `site-packages/` in my virtualenv.
```
cv.py
cv2.pyd
easy_install.py
easy_install.pyc
opencv_calib3d310.dll
opencv_core310.dll
opencv_features2d310.dll
opencv_ffmpeg310.dll
opencv_flann310.dll
opencv_highgui310.dll
opencv_imgcodecs310.dll
opencv_imgproc310.dll
opencv_ml310.dll
opencv_objdetect310.dll
opencv_photo310.dll
opencv_shape310.dll
opencv_stitching310.dll
opencv_superres310.dll
opencv_video310.dll
opencv_videoio310.dll
opencv_videostab310.dll
```

> But we need to determine this path.

Is it possible to call Python? From cv.py it would be this:
```
import os

if os.name == 'nt':
    ROOT = os.path.abspath(os.path.dirname(__file__))
    os.environ['PATH'] += os.environ['PATH'] + os.pathsep + ROOT
```

**Comment by techtonik** [comment]
And here is the recipe for getting full path in C++ WinAPI - http://stackoverflow.com/a/6924332/239247
