### ISSUE TITLE
IP camera crash when Wifi turned off

### ISSUE THREAD

**Issue by Prakash19921206** [opencv/opencv#6726]
i'm using IP webcam (andriod app), i can easily access camera through opencv code, but the issue here is that program crashes if i turn off wifi of my andriod device camera (having IP webcam still running). even though i have added all safety checks within the code, it works only if app is closed (and wifi still on)  but the moment i turn off wifi having (app still running) , its impossible to avoid crash (at the moment)

if i put entire code within main, program crashes when wifi turned off.  if i run the code on separate thread , then only that thread freezes (after thread freezes, if i try to terminate that thread or call cap.release();  it crashes)

is there a workaround to avoid crash?  
Thanks & regards
### My system configuration
- OpenCV version: 3.x (tried in both 3.0 & 3.1)
- Host OS: Windows 7
-  Visual Studio 2013
### In which part of the OpenCV library you got the issue?
- VideoCapture Class
### Expected behaviour

Close program or show a message saying unable to get new frame 
### Actual behaviour

Program Crash with error message as below 

> HEAP[Test.exe]: HEAP: Free Heap block 6797780 modified at 67977d4 after it was freed Windows has triggered a breakpoint in Test.exe.
> 
>    This may be due to a corruption of the heap, which indicates a bug in Test.exe or any of the DLLs it has loaded.
> 
>    This may also be due to the user pressing F12 while Test.exe has focus.
> 
>    The output window may have more diagnostic information.
### Additional description

i tried wrapping code within try catch block, interestingly it still crashes the program. 
 i also posted at http://www.codeproject.com/Questions/1107935/Opencv-IP-camera-error
and http://stackoverflow.com/questions/37939476/opencv-ip-camera-error
### Code example to reproduce the issue / Steps to reproduce the issue

```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
 VideoCapture cap; Mat img;
 cap.open("http://192.168.0.101:8080/video?x.mjpeg");
 while(waitKey(33)!=27)
 {
    try{
         cap>>img;   
         if(img.empty())
         {
          cout<<"camera Closed"<<endl;
          break;
         }
          imshow("Video",img);
      } catch(...){}   
 }
return 0;
}

```

**Comment by theg4sh** [comment]
Your code example isn't full. As you describe it on stackoverflow, you call _cap.release()_ when the exception is called, so, you've got _cap.release()_ call twice: manually and in _VideoCapture::~VideoCapture()_.

So, please, try to remove your manual call and repeat to reproduce.

**Comment by Prakash19921206** [comment]
hi theg4sh, i have tried several methods to avoid crash (which include removing manual call as well)
if possible, can you download [this ](https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en)andriod app and try above code ?  once camera is connected, just turn off wifi on your andriod device. I hope this bug in opencv will be fixed soon. and please reply at either stackoverflow or here for future communication.
Thanks & regards

**Comment by theg4sh** [comment]
I have no Andriod device to test the code, sorry.
Did you try to catch the wifi connection state and process it using _BroadcastReceiver_? Take a look to [this post](http://stackoverflow.com/questions/5888502/how-to-detect-when-wifi-connection-has-been-established-in-android). I guess, it gives to you a way to tell to the users that app have  lost the connection and correct handle it.

**Comment by Prakash19921206** [comment]
sorry for delay in reply,
the link you shared looks like its in C# & XML (basically code for andriod)
i'll try to convert it to C++ & include the libraries which are essential to make it work.
Thank you

**Comment by alalek** [comment]
Current master version of OpenCV works great on Windows 10 x64 + MSVS 2015 via this video link:
```
rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
```

After disconnection (Wi-Fi off via AirPlane mode ON) application just freezes and then closes after ~30 seconds of timeout (no crashes, message "camera Closed" is showed).

**Comment by Prakash19921206** [comment]
hi alalek, i tried current master version of opencv. yeah now it works well..but still After disconnection (Wi-Fi off via AirPlane mode ON)  `videocapture.isOpened()` will be true. can you confirm this?
there is another issue, if internet speed(broadband usage/consumption) is restricted <4kb/s, IP camera disconnects [_i know its not really required, but in somecase we can atleast grab a frame in few seconds instead of nothing..this could be helpful for surveillance_]
..is there a way to set IP camera to disconnect only when internet speed is below 1kbps?
