### ISSUE TITLE
question about the imread and imwrite in python opnecv

### ISSUE THREAD

**Issue by HeGaoYuan** [opencv/opencv#6727]
Hi, it is very easy to use the cv2.imread and cv2.write to read and write the image, but recently I found some question.
My opencv version is 2.4.8 and my computer is 64bits ubuntu.
There is a picture named '95.jpg' which is a color picture. I want to use cv2.imread to read the color picture(img_color), then convert to gray picture(img_gray), then use the gray picture to do other things, then I should save the gray picture for next time to use. But I found next time I cv2.imread the gray picture(img_gray2) which I cv2.write before, the picture is different(img_gray2 is not as same as img_gary).
If what I describe is hard to understand, I am sorry. Please just to read the code I posted.
**THE question is why the img_gray2 and img_gray are different, what should I do if I want they are same?**
![2016-06-25 12_54_45____________](https://cloud.githubusercontent.com/assets/16939557/16354881/0245e230-3ad8-11e6-80ed-879075535b7b.png)

**Comment by alalek** [comment]
Please use Q/A forum for usage questions: http://answers.opencv.org

It is allowed for algorithms like BGR2GRAY provide different results (rounding of floating point numbers is one of this).

**Comment by sturkmen72** [comment]
JPEG is not lossless format in general. You should use PNG or similar if you want bit-exact results.

**Comment by ilya-lavrenov** [comment]
@sturkmen72 gave the correct answer. I'm closing the issue.
