### ISSUE TITLE
Naming all enumerations in videoio.hpp

### ISSUE THREAD

**Issue by PkLab** [opencv/opencv#6746]
- **OpenCV version**: 3.x
- **Which part**: [videoio.hpp](https://github.com/Itseez/opencv/blob/master/modules/videoio/include/opencv2/videoio.hpp)
- **Actual behaviour**: All enumerations in videoio.hpp are unnamed

### Expected behaviour
Starting from @mshabunin suggestion:

> Naming all enumerations in videoio.hpp to make it possible to refer them from corresponding function documentation. See documentation for cv::imread for example.

### Additional description

Because once a name is assigned it will be hard/impossible to change later, please find here some request for comment:

2. Which naming convention should be used ?
3. Are there enumerations that might/should be merged ? 
4. May be some enumerations should live in their own module like OPENNI_, PVAPI_, XI_, and so on
5. May be enumerations should have better organization or stronger type like `MEDIA_API`, `MEDIA_PROPERTIES` (class and inheritance ?, C++11 typed enumeration ?,...)
6. Should functions that use enumerations be declared with enumeration name as arg type instead of simple int  e.g. `VideoCapture::get(MEDIA_PROPERTIES propId)` or `VideoCapture::open( String filename, MEDIA_API apiPreference )` ?
7. Meaning of enumerator value is mixed. It could be an ID, a flag, a mask of bits. Last cases, changing the enumerator value will break the code. Some kind of warning should exist here: e.g `CAP_api` is used with %10 to select the api, or OpenNI shortcuts or `CAP_PVAPI_DECIMATION_2OUTOF8`,...
8. Shall we forget all about and try to derive enumeration name from common part of enumerators e.g. `enum CAP_PROP {CAP_PROP_POS_MSEC=0, CAP_PROP_POS_FRAMES=1,...}`

**Comment by mshabunin** [comment]
1. After looking at the [enumerations list](http://docs.opencv.org/master/d2/d75/namespacecv.html#enum-members), I'd suggest something like `CaptureProperties`, `CaptureModes`, `VideoCaptures`, `CaptureSources`, `CapturePropertiesGiga`, etc.
2. I don't see any candidates for merging.
3. Did you mean _namespace_? I think no, we need to preserve backward compatibility.
4. No. Probably it will be hard to make bindings for such entities.
5. No. For same reasons as in 3 and 4.
6. It will be hard to check logic breakages during compilation time, so the best solution I see is to name enums correspondingly (use separate enum for flags and add '...Flags' suffix where possible) and to increase the test coverage.
7. I'd prefer the CamelCase variants from point 1 for consistency with existing names.

This change is needed mostly for documentation purposes, I don't see any other useful applications for named enumerations in thier current state. So we don't need to name all enums, but only those referred from several documentation blocks.

**Comment by souch55** [comment]
Hi mshabunin i have added the feature of named enum's in pr,if you can review the same

**Comment by PkLab** [comment]
@souch55 I was working on this issue too that's why of my PR. I agree with @mshabunin 

> So we don't need to name all enums, but only those referred from several documentation blocks.

About names I think that it's useful to being explicit the concept of "API selection" and that these enums are identifier... but this is a point of view we an choose the most appropriate

**Comment by souch55** [comment]
Hi PkLab thanks for your's comments ,i am new to opencv github, just trying to contribute,by reading related issues,yes we don't need to name all enums but only referred from several documentation blocks,as in opencv documents i came across in web where openni related enums were referred in  detail so i have added names to them also.

**Comment by PkLab** [comment]
@souch55 you are superwelcome ! At this time we have 2 PR for same issue. Our changes are almost same. Main difference is that I've enclosed enums into doc submodules to get easier doc page for videoio module. Now we have to wait some approval or change request from @mshabunin or @apavlenko or any other Opencv members.
