### ISSUE TITLE
Compilation error in hal_internal.cpp in OpenCV

### ISSUE THREAD

**Issue by daniel-lawrence-lu** [opencv/opencv#6749]
I am trying to compile OpenCV 3.1.0-734-g69bd6da-dirty

- Host OS: Linux 4.6.3-1-ARCH x86_64
- Compiler: GCC 6.1.1
- CPU: Intel Core i7 6700K. 

When compiling, I am obtaining an error in line 402 of modules/core/src/hal_internal.cpp.

```
/home/dllu/builds/opencv-git/src/opencv/modules/core/src/hal_internal.cpp: In instantiation of ‘int lapack_gemm_c(const fptype*, std::size_t, const fptype*, std::size_t, fptype, const fptype*, std::size_t, fptype, fptype*, std::size_t, int, int, int, int) [with fptype = float; std::size_t = long unsigned int]’:
/home/dllu/builds/opencv-git/src/opencv/modules/core/src/hal_internal.cpp:475:119:   required from here
/home/dllu/builds/opencv-git/src/opencv/modules/core/src/hal_internal.cpp:402:20: error: cannot convert ‘std::complex<float>*’ to ‘const float*’ for argument ‘7’ to ‘void cblas_cgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, blasint, blasint, blasint, const float*, const float*, blasint, const float*, blasint, const float*, float*, blasint)’
         cblas_cgemm(CblasRowMajor, transA, transB, a_m, d_n, a_n, &cAlpha, (void*)src1, ldsrc1, (void*)src2, ldsrc2, &cBeta, (void*)dst, lddst);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The [full log is available here](https://lawrence.lu/public/opencv-compileerrors.log). Build options, system information, and so on can be inferred from the log.

I have openblas-lapack 0.2.18-1 installed. I am running cmake with the following options:

            '-D WITH_OPENCL=ON'
            '-D WITH_OPENGL=ON'
            '-D WITH_CUDA=ON'
            '-D ENABLE_FAST_MATH=ON'
            '-D CUDA_FAST_MATH=ON'
            '-D WITH_CUBLAS=ON'
            '-D WITH_TBB=ON'
            '-D WITH_XINE=ON'
            '-D BUILD_WITH_DEBUG_INFO=OFF'
            '-D BUILD_TESTS=OFF'
            '-D BUILD_PERF_TESTS=OFF'
            '-D BUILD_EXAMPLES=ON'
            '-D INSTALL_C_EXAMPLES=ON'
            '-D INSTALL_PYTHON_EXAMPLES=ON'
            '-D CMAKE_BUILD_TYPE=Release'
            '-D CMAKE_INSTALL_PREFIX=/usr'
            '-D CMAKE_SKIP_RPATH=ON'
            '-D BUILD_NEW_PYTHON_SUPPORT=ON'
            '-D ENABLE_SSSE3=ON'
            '-D ENABLE_SSE41=ON'
            '-D ENABLE_SSE42=ON'
            '-D ENABLE_POPCNT=ON'
            '-D ENABLE_AVX=ON'
            '-D ENABLE_AVX2=ON'
            '-DCMAKE_CXX_FLAGS="-std=c++98"'

Note that I am compiling with -std=c++98 for compatibility with CUDA 7.5.

**Comment by alalek** [comment]
@daniel-lawrence-lu Could you take a look on #6753?

**Comment by daniel-lawrence-lu** [comment]
Thanks for your help! However, using your branch, I am getting a different set of errors.

```
/home/dllu/builds/opencv-alalek/opencv/modules/core/src/hal_internal.cpp: In instantiation of ‘int lapack_gemm_c(const fptype*, std::size_t, const fptype*, std::size_t, fptype, const fptype*, std::size_t, fptype, fptype*, std::size_t, int, int, int, int) [with fptype = float; std::size_t = long unsigned int]’:
/home/dllu/builds/opencv-alalek/opencv/modules/core/src/hal_internal.cpp:475:119:   required from here
/home/dllu/builds/opencv-alalek/opencv/modules/core/src/hal_internal.cpp:402:20: error: invalid conversion from ‘void*’ to ‘const float*’ [-fpermissive]
         cblas_cgemm(CblasRowMajor, transA, transB, a_m, d_n, a_n, reinterpret_cast<fptype(&)[2]>(cAlpha), (void*)src1, ldsrc1, (void*)src2, ldsrc2, reinterpret_cast<fptype(&)[2]>(cBeta), (void*)dst, lddst);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dllu/builds/opencv-alalek/opencv/modules/core/src/hal_internal.cpp:51:0:
/usr/include/cblas.h:250:6: note:   initializing argument 8 of ‘void cblas_cgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, blasint, blasint, blasint, const float*, const float*, blasint, const float*, blasint, const float*, float*, blasint)’
 void cblas_cgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
      ^~~~~~~~~~~
/home/dllu/builds/opencv-alalek/opencv/modules/core/src/hal_internal.cpp:402:20: error: invalid conversion from ‘void*’ to ‘const float*’ [-fpermissive]
         cblas_cgemm(CblasRowMajor, transA, transB, a_m, d_n, a_n, reinterpret_cast<fptype(&)[2]>(cAlpha), (void*)src1, ldsrc1, (void*)src2, ldsrc2, reinterpret_cast<fptype(&)[2]>(cBeta), (void*)dst, lddst);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

For full error log see: [full log is available here](https://lawrence.lu/public/opencv-alalek-compileerrors.log)

**Comment by alalek** [comment]
Actually I can't reproduce these error message (and from previous comment also) on my side. I have
```
gcc version 6.1.1 20160501 (GCC)
```
and I'm using (lapack/lapacke/cblas packages from Arch).

Could you check again the updated branch?

Could you run "make" with "VERBOSE=1"?

**Comment by daniel-lawrence-lu** [comment]
I am using [OpenBLAS](https://github.com/xianyi/OpenBLAS) instead of the default lapack/lapacke/cblas packages from Arch. Perhaps there are incompatibilities?

In any case, I have uploaded [full log](https://lawrence.lu/public/opencv-alalek-compileerrors-2.log) with the output of

    make --debug=v >> builderrors.log 2>&1

using the updated version of your branch. It almost works now... but not quite yet. For some reason, the compiler thinks cblas_zgemm can be called when fptype is float and that cblas_cgemm can be called when fptype is double. Strange...

**Comment by alalek** [comment]
"--debug=v" is not very useful. "make VERBOSE=1" shows all used compiler flags.

Patch has been updated.

**Comment by daniel-lawrence-lu** [comment]
Oh, I see. I didn't know about `VERBOSE=1` before, thanks for telling me!

Good news, `hal_internal.cpp` builds now with no errors. Hooray! Thanks again!

**Comment by alalek** [comment]
Thanks for check!
