### ISSUE TITLE
Imgproc.moments() Causes Crash

### ISSUE THREAD

**Issue by SumeetBatra** [opencv/opencv#6754]
System Info
- OpenCV version: 3.1.0
- Host OS: Windows 10
- Target OS: Android 6.0 

Problem is with Imgproc.moments(). Running the following code results in a crash:

```
Mat temp = new Mat();
grayBinary.copyTo(temp);

ArrayList<object> candidates= new ArrayList<>();
List<MatOfPoint> contours = new ArrayList<MatOfPoint>();
Mat hierarchy = new Mat()
Imgproc.findContours(temp, contours, hierarchy, Imgproc.RETR_EXTERNAL,         Imgproc.CHAIN_APPROX_SIMPLE);

if(contours.size() > 0) {
    int numObjects = contours.size();

    if (numObjects < MAX_OBJECTS) {

        for (int i = 0; i < contours.size(); i++) {
            //moments causing unsatisfied linker error
            Moments moment = Imgproc.moments((Mat)contours.get(i));
            double area = moment.m00;
        }
     }
   }
```

And here is the logcat output: 

 java.lang.UnsatisfiedLinkError: No implementation found for double[] org.opencv.imgproc.Imgproc.moments_1(long) (tried Java_org_opencv_imgproc_Imgproc_moments_11 and Java_org_opencv_imgproc_Imgproc_moments_11__J)...

Can anyone help with this issue? Thanks in advance!

**Comment by mshabunin** [comment]
Did you try not to add `(Mat)` when accessing contours list?

**Comment by SumeetBatra** [comment]
That is the first thing I tried but I still get the same error.

**Comment by apavlenko** [comment]
@SumeetBatra, please provide the output of `Core.getBuildInformation()` call - otherwise we'll have to close the bug as an incomplete
