### ISSUE TITLE
Are you sure that coefficients for detecting brightness are right?

### ISSUE THREAD

**Issue by littleguga** [opencv/opencv#6765]
https://github.com/Itseez/opencv/blob/master/modules/imgcodecs/src/utils.cpp#L46
https://github.com/Itseez/opencv/blob/master/modules/imgproc/perf/perf_floodfill.cpp#L58

For now there are coefficients for NTSC, not sRGB.

See sRGB table: http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html
Or point 9 here: http://www.poynton.com/notes/colour_and_gamma/ColorFAQ.html

**Comment by littleguga** [comment]
The formula using to calculate relative luminance (or brightness):
Y = 0.299 R + 0.587 G + 0.114 

But it is correct in NTSC (1953) color space only. This formula is deprecated and legacy.
Actual color space sRGB significantly different: [chromacity diagram](https://habrastorage.org/getpro/habr/post_images/ece/82d/de9/ece82dde9aefff243777d61281a721da.jpg).

Correct formula is:
Y = 0.2126 R + 0.7152 G + 0.0722 B

[The proof of numbers](https://habrastorage.org/getpro/habr/post_images/2ab/69d/084/2ab69d084f9a597e032624bcd74d57a7.png)
Source — [Bruce Lindbloom site](http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html)
See also — [Charles Poynton Color FAQ](http://www.poynton.com/notes/colour_and_gamma/ColorFAQ.html#RTFToC9)

A lot of work or refactoring is not required. We can simply replace this coefficients.

**Comment by PhilLab** [comment]
Seems like a bug indeed. If this is changed, please also consider the other places the coefficients turn up to prevent inconsistencies: https://github.com/Itseez/opencv/search?utf8=%E2%9C%93&q=587&type=Code

**Comment by StevenPuttemans** [comment]
Hmm problem will be the binary compatibility and backwards compatibility and thus I am afraid simply changing the coefficients will not be allowed by OpenCV core team. Changing this parameters would result in users who are expecting this behaviour to be correct, to turn up with quite the different results.

@alalek what do you think?

**Comment by mshabunin** [comment]
For computer vision tasks Rec.601 (NTSC) coefficients can perform slightly better because of bigger B and R contribution. Also, these coefficients are used in popular scientific libraries and tools like [Matlab](http://www.mathworks.com/help/matlab/ref/rgb2gray.html), [SciPy](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html) and [Intel IPP](https://software.intel.com/en-us/node/504010). Since this type of conversion conversion is clearly described in the [documentation](http://docs.opencv.org/master/de/d25/imgproc_color_conversions.html) we don't consider it as a bug.

To produce RGB to Gray conversion according to Rec.709, one can convert RGB to XYZ and extract Y channel. If more users will need this specific conversion - they can add new cv::COLOR_RGB2GRAY_709 (or similar) cvtColor mode.

**Comment by dom1n1k** [comment]
It's the bug. Very-very old, common and typical, but bug :)

By default everywhere used images in sRGB space. Coefficients related to any other color space, will produce some errors. NTSC (1959) is used only in very rare and special cases.

##### Small Monte Carlo experiment

I generate 2 random colors (10^6 times) and check the **relation** of Y relative perceptual lightness L*.
If L1 > L2 and Y1 > Y2 (or < in both cases) - it's right.
If relations signs are different - it's error. It means that objectively darker color was "seen" as lighter (or vice versa).

Please see gist: https://gist.github.com/dom1n1k/006ac7c88eb1b85d33bf8b478408e7c4
You can run it in browser console or node.js command line.

Correct relation percentage:

| ITU-R Rec. | without gamma-decoding | linear space |
| ----- | -----:| -----:|
| 601 | 92.56% | 94.35% |
| 709 | 94.06% | 100.00% |

Sorry for my bad english.

**Comment by littleguga** [comment]
@mshabunin any thoughts about @dom1n1k post?

**Comment by mshabunin** [comment]
@dom1n1k , your example is not related to [computer vision](https://en.wikipedia.org/wiki/Computer_vision). I agree that grayscale image produced from RGB using Rec.709 looks better on LCD screen, but OpenCV is different kind of library. It would be great if you can give examples of computer vision algorithms wich behave worse or break when input or intermediate image is converted to grayscale using Rec.601 coefficients.

**Comment by dom1n1k** [comment]
No difference between human and computer :) It depends on color space of your input device and working images.
If your camera works in NTSC-1953 then you are right. But this system [died in 90s](https://en.wikipedia.org/wiki/NTSC#SMPTE_C) (except Japan may be).

**Comment by littleguga** [comment]
@dom1n1k can we adapt tests for OpenCV?

**Comment by dom1n1k** [comment]
I tried to choose a couple of colors and calculate the Laplacian (detect edges)

**[Python-script](https://gist.github.com/dom1n1k/24bd43810aa8f567cf2494dd6c78af32)**

**Images**
[Original](http://dom1n1k.name/github/luminance/magenta-green.png) - green is noticeably brighter than magenta, right?
[Grayscale 601](http://dom1n1k.name/github/luminance/grayscale601-opencv.png) - wrong grayscale via OpenCV
[Laplacian 601](http://dom1n1k.name/github/luminance/laplacian601.png) - edges are shown... almost
[Grayscale 709](http://dom1n1k.name/github/luminance/grayscale709-photoshop.png) - correct grayscale via Photoshop
[Laplacian 709](http://dom1n1k.name/github/luminance/laplacian709.png) - edges are very clear

P.S. cv2.cvtColor don't perform gamma-correction. Not so good.

**Comment by mshabunin** [comment]
@dom1n1k , thank you for the example, but it is too synthetic and only illustrates common problem of all simple RGB-to-grayscale transformations. I guess it is possible to pick two colors that will give same one-tone grayscale image after conversion using Rec.709. If one wants to achieve better quality, he choses from the [advanced](http://cadik.posvete.cz/color_to_gray_evaluation/) algorithms like Decolorize.

According to [this](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3254613) study related to image recognition:
- gamma-corrected methods work better
- methods which use more information from all channels work better

Feel free to provide your implementation of gamma-corrected cvtColor version :wink: - it is one of the old feature ideas.

**Comment by dom1n1k** [comment]
> I guess it is possible to pick two colors that will give same one-tone grayscale image after conversion using Rec.709.

[Example](http://dom1n1k.name/github/luminance/magenta-green-2.png)
Same magenta backgroud, corrected green. Y709 and CIE L* are equal.
Visual contrast is obviously less in this case.
