### ISSUE TITLE
Fail to install OpenCV - Open suse

### ISSUE THREAD

**Issue by mpajuelo** [opencv/opencv#6772]
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

### Please state the information for your system
- OpenCV version: 2.4.13
- Host OS: Linux (Opensuse 3.16.7-32-desktop x86_64)  

### In which part of the OpenCV library you got the issue?
Installation
### Expected behaviour
work
### Actual behaviour
installation unfinished
### Additional description
this is what I got:
------------------------------[/usr/local/src/freeture-1.0.1]--
--[13:59]--$ ./configure --with-opencv-libdir=/usr/lib64 --with-opencv-incdir=/usr/include
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
******** Configuring:  freeture 1.0-0 (2016-07-05) ********
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for floor... yes
checking for memset... yes
checking for modf... yes
checking for pow... yes
checking for sqrt... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB_2_0... yes
checking for GOBJ_2_0... yes
checking for UDEV... yes
checking for CRYPTO... yes
checking for V4L2... yes
checking whether we should use the Pylon SDK for Basler Camera... no
checking boost/date_time.hpp usability... yes
checking boost/date_time.hpp presence... yes
checking for boost/date_time.hpp... yes
checking for main in -lboost_program_options... yes
checking for main in -lboost_thread... yes
checking for main in -lboost_system... yes
checking for main in -lboost_log_setup... yes
checking for main in -lboost_log... yes
checking for main in -lboost_filesystem... yes
checking for main in -lboost_date_time... yes
checking for main in -lboost_chrono... yes
checking for main in -lboost_iostreams... yes
checking /usr/include/opencv2/opencv.hpp usability... yes
checking /usr/include/opencv2/opencv.hpp presence... yes
checking for /usr/include/opencv2/opencv.hpp... yes
checking for main in -lopencv_calib3d... yes
checking for main in -lopencv_contrib... no
checking for main in -lopencv_core... yes
checking for main in -lopencv_features2d... yes
checking for main in -lopencv_flann... yes
checking for main in -lopencv_highgui... yes
checking for main in -lopencv_imgproc... yes
checking for main in -lopencv_legacy... no
checking for main in -lopencv_ml... yes
checking for main in -lopencv_objdetect... yes
checking for main in -lopencv_video... yes
configure: error: OpenCV library files not found in /usr/lib64! Exiting.

I 
### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include "opencv2/core.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
    double d[] = { 546,2435,7,4534,23423,3 };
    cout << "d = 0x" << reinterpret_cast<void*>(d) << endl;

    return 0;
}
```

**Comment by alalek** [comment]
> Configuring: freeture

We don't maintain these scripts, so we can't help you a lot.

At first check version defines in /usr/include/opencv2/core/version.hpp
Looks like you installed OpenCV 3.x because opencv_contrib and opencv_legacy are missing (they are from 2.4 branch).

There is nothing to fix on OpenCV, so closing.
