### ISSUE TITLE
cv::RNG::fill overwrites variables in stack

### ISSUE THREAD

**Issue by taishouroman** [opencv/opencv#6870]
I tried saving the variables into a xml file, but the saved value has been different from a memory. I felt strange and examined, cv::RNG::fill may overwrite the variables in stack region.

### Please state the information for your system
- OpenCV version: 2.4.9 and 2.4.13, I checked
- Host OS: Linux (Ubuntu 14.04)
- Target OS: host / Linux 3.13.0-86-generic x86_64
- Compiler & CMake: GCC 4.8.4 & CMake 2.8.12.2

### In which part of the OpenCV library you got the issue?
- core

### Expected behavior
All of variables before calling cv::RNG::fill are equal to after. E.g., the following code prints:
(a, b, c, d) = (10, 0.5, -1.3, 104)
(a, b, c, d) = (10, 0.5, -1.3, 104)

### Actual behavior
Some of variables before calling cv::RNG::fill were different from after. E.g., the following code printed:
(a, b, c, d) = (10, 0.5, -1.3, 104)
(a, b, c, d) = (-9, -9, -1.3, 104)

#### Not overwritten when non-double type
I haven't get the same behavior when I changed the type of 'x' to the other type (e.g. cv::Mat_\<uchar\>, cv::Mat_\<cv::Vec2i\>, cv::Mat_\<cv::Point3f\>, etc.).

#### The number of channels may affect the behavior
I have made sure the number of variables in stack has been overwritten.
When the type of 'x' was cv::Mat_\<double\>, no stack variables was overwritten.
When the type of 'x' was cv::Mat_\<cv::Vec2d\> or cv::Mat_\<cv::Point2d\>, only 'a' was overwritten.
When the type of 'x' was cv::Mat_\<cv::Vec3d\> or cv::Mat_\<cv::Point3d\>, 'a' and 'b' were overwritten.

#### Only double-type variables in stack are overwritten
I changed the type of 'a' from double to float in the following code, and then 'a' was not overwritten but 'b' was overwritten.

#### cv::RNG::fill overwrites variables in stack as the value of 'mean'
Overwritten variables in stack had the value of 'mean', which was the 3rd argument of cv::RNG::fill.

#### cv::RNG::fill performs expected behavior when generates uniform distribution
cv::RNG::fill overwrites no variables in stack when I specify cv::RNG::UNIFORM to the 2nd argument of cv::RNG::fill.

### Code example to reproduce the issue / Steps to reproduce the issue
```
#include <iostream>
#include <opencv2/core.hpp>

int main() {
    double a = 10;
    double b = 0.5;
    cv::Mat_<cv::Point2d> x(2, 3);
    double c = -1.3;
    double d = 104;

    std::cerr << "(a, b, c, d) = " << a << ", " << b << ", " << c << ", " << d << ")" << std::endl;
    cv::theRNG().fill(x, cv::RNG::NORMAL, -9, 10);
    std::cerr << "(a, b, c, d) = " << a << ", " << b << ", " << c << ", " << d << ")" << std::endl;

    return 0;
}
```

**Comment by savuor** [comment]
I confirm this bug

**Comment by savuor** [comment]
I confirm this bug also in v3.1.0

**Comment by savuor** [comment]
The problem is that `RNG::fill()` doesn't check that distribution parameters have the same number of channels as matrix to be filled.
PR will be created soon.

**Comment by taishouroman** [comment]
Thanks for confirming and fixing this bug! :)
