### ISSUE TITLE
Error when executing 'opencv_visualisation' binary file

### ISSUE THREAD

**Issue by bermond** [opencv/opencv#6875]
I'm getting the following error when executing the 'opencv_visualisation' binary file. The installed binary file is strangely referencing my build directory. The command shows just this error and nothing more:

```
$ opencv_visualisation
OpenCV Error: Null pointer (NULL or empty buffer) in cvOpenFileStorage, file /home/user/abs/opencv-git/src/opencv-git/modules/core/src/persistence.cpp, line 2980
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/user/abs/opencv-git/src/opencv-git/modules/core/src/persistence.cpp:2980: error: (-27) NULL or empty buffer in function cvOpenFileStorage

Aborted (core dumped)
```

- OpenCV version: 3.1.0.r781.gd06bdd5 (git master)
- Host OS: Linux (Arch Linux x86_64)
- GCC: 6.1.1
- CMake: 3.5.2
- CPU: Intel Haswell

Commands used for building:
```
$ cmake \
	-DBUILD_SHARED_LIBS:BOOL=ON \
	\
	-DBUILD_opencv_apps:BOOL=ON             -DBUILD_opencv_calib3d:BOOL=ON  	-DBUILD_opencv_core:BOOL=ON \
	-DBUILD_opencv_features2d:BOOL=ON       -DBUILD_opencv_flann:BOOL=ON    	-DBUILD_opencv_highgui:BOOL=ON \
	-DBUILD_opencv_imgcodecs:BOOL=ON        -DBUILD_opencv_imgproc:BOOL=ON  	-DBUILD_opencv_ml:BOOL=ON \
	-DBUILD_opencv_objdetect:BOOL=ON        -DBUILD_opencv_photo:BOOL=ON    	-DBUILD_opencv_shape:BOOL=ON \
	-DBUILD_opencv_stitching:BOOL=ON        -DBUILD_opencv_superres:BOOL=ON 	-DBUILD_opencv_ts:BOOL=ON \
	-DBUILD_opencv_video:BOOL=ON            -DBUILD_opencv_videoio:BOOL=ON          -DBUILD_opencv_videostab:BOOL=ON \
	-DBUILD_opencv_world:BOOL=OFF \
	\
	-DBUILD_opencv_cudaarithm:BOOL=OFF      -DBUILD_opencv_cudabgsegm:BOOL=OFF      -DBUILD_opencv_cudacodec:BOOL=OFF \
	-DBUILD_opencv_cudafeatures2d:BOOL=OFF  -DBUILD_opencv_cudafilters:BOOL=OFF     -DBUILD_opencv_cudaimgproc:BOOL=OFF \
	-DBUILD_opencv_cudalegacy:BOOL=OFF      -DBUILD_opencv_cudaobjdetect:BOOL=OFF   -DBUILD_opencv_cudaoptflow:BOOL=OFF \
	-DBUILD_opencv_cudastereo:BOOL=OFF      -DBUILD_opencv_cudawarping:BOOL=OFF     -DBUILD_opencv_cudev:BOOL=OFF \
	\
	-DCUDA_64_BIT_DEVICE_CODE:BOOL=OFF \
	-DCUDA_FAST_MATH:BOOL=OFF \
	\
	-DCMAKE_BUILD_TYPE:STRING=Release \
	-DCMAKE_COLOR_MAKEFILE:BOOL=ON \
	-DCMAKE_INSTALL_PREFIX:PATH=/usr \
	-DCPACK_BINARY_DEB:BOOL=OFF \
	\
	-DPYTHON2_NUMPY_INCLUDE_DIRS:PATH=/usr/include/python2.7/numpy \
	-DPYTHON3_NUMPY_INCLUDE_DIRS:PATH=/usr/include/python3.5m/numpy \
	\
	-DENABLE_FAST_MATH:BOOL=ON \
	\
	-DENABLE_AVX:BOOL=OFF   -DENABLE_AVX2:BOOL=OFF   -DENABLE_FMA3:BOOL=OFF   -DENABLE_POPCNT:BOOL=OFF \
	-DENABLE_SSE:BOOL=ON    -DENABLE_SSE2:BOOL=ON    -DENABLE_SSE3:BOOL=ON    -DENABLE_SSSE3:BOOL=OFF \
    -DENABLE_SSE41:BOOL=OFF -DENABLE_SSE42:BOOL=OFF" \
	\
	-DBUILD_EXAMPLES:BOOL=OFF \
	-DBUILD_PERF_TESTS:BOOL=OFF \
	-DBUILD_TESTS:BOOL=OFF \
	-DINSTALL_C_EXAMPLES:BOOL=OFF \
	-DINSTALL_PYTHON_EXAMPLES:BOOL=OFF \
	-DINSTALL_TESTS:BOOL=OFF \
	\
	-DWITH_1394:BOOL=ON       -DWITH_CLP:BOOL=OFF            -DWITH_CUBLAS:BOOL=OFF        -DWITH_CUDA:BOOL=OFF \
	-DWITH_CUFFT:BOOL=OFF     -DWITH_EIGEN:BOOL=ON           -DWITH_FFMPEG:BOOL=OFF        -DWITH_GDAL:BOOL=OFF \
	-DWITH_GIGEAPI:BOOL=OFF   -DWITH_GPHOTO2:BOOL=ON         -DWITH_GSTREAMER:BOOL=ON      -DWITH_GSTREAMER_0_10:BOOL=OFF \
	-DWITH_GTK:BOOL=ON        -DWITH_GTK_2_X:BOOL=ON         -DWITH_IPP_A:BOOL=ON          -DWITH_IPP:BOOL=ON \
	-DWITH_JASPER:BOOL=ON     -DWITH_JPEG:BOOL=ON            -DWITH_LIBV4L:BOOL=ON         -DWITH_NVCUVID:BOOL=ON \
	-DWITH_OPENCL:BOOL=ON     -DWITH_OPENCLAMDBLAS:BOOL=ON   -DWITH_OPENCLAMDFFT:BOOL=ON   -DWITH_OPENCL_SVM:BOOL=ON \
	-DWITH_OPENEXR:BOOL=ON    -DWITH_OPENGL:BOOL=ON          -DWITH_OPENMP:BOOL=ON         -DWITH_OPENNI:BOOL=OFF \
	-DWITH_OPENNI2:BOOL=OFF   -DWITH_PNG:BOOL=ON             -DWITH_PVAPI:BOOL=OFF         -DWITH_QT:BOOL=OFF \
	-DWITH_TBB:BOOL=ON        -DWITH_TIFF:BOOL=ON            -DWITH_UNICAP:BOOL=OFF        -DWITH_V4L:BOOL=ON \
	-DWITH_VTK:BOOL=OFF       -DWITH_WEBP:BOOL=ON            -DWITH_XIMEA:BOOL=OFF         -DWITH_XINE:BOOL=OFF \
	-DWITH_MATLAB:BOOL=OFF    -DWITH_OPENCLAMDFFT:BOOL=ON    -DWITH_PTHREADS_PF:BOOL=ON    -DWITH_VA_INTEL:BOOL=ON \
	\
	-DBUILD_JASPER:BOOL=OFF   -DBUILD_JPEG:BOOL=OFF          -DBUILD_OPENEXR:BOOL=OFF      -DBUILD_PNG:BOOL=OFF \
	-DBUILD_TIFF:BOOL=OFF     -DBUILD_ZLIB:BOOL=OFF \
	\
	-DOPENCV_WARNINGS_ARE_ERRORS:BOOL=OFF \
	-Wno-dev \
	.
$ make
```

Compiler and linker options (system wide set):
```
CPPFLAGS="-D_FORTIFY_SOURCE=2"
CFLAGS="-march=native -O2 -pipe -fstack-protector-strong"
CXXFLAGS="-march=native -O2 -pipe -fstack-protector-strong"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro"
MAKEFLAGS="-j4"
```

Any help would be appreciated.
Thank you.

**Comment by berak** [comment]
this is not really a library issue.

you forgot to supply some cmdline arguments, the path in the exception is the *location of the code*, where the problem occurs (it's not looking there for anything)

please see [here for usage information](https://github.com/opencv/opencv/blob/master/apps/visualisation/opencv_visualisation.cpp#L49)

you should call it like:
    
    ./opencv_visualisation -model /absolute/path/to/the/cascade.xml -image /path/to/one/of/the/train/images

**Comment by bermond** [comment]
Thank you for the reply.

I understand. In my humble opinion it would be good if the executable doesn't explicitly expose in terminal the source path of the person who compiled the code because it would not be a comfortable situation for packagers.
Also, I look forward for the addition of an usage/help/version if called without arguments like the other binaries do, as like as some '--help' or '--version' switches.

Just some thoughts.
Again, thanks for the reply and support.

**Comment by StevenPuttemans** [comment]
Thanks for the suggestions and the proposed fixes!

**Comment by bermond** [comment]
@StevenPuttemans
It was a pleasure to contribute in some way, and it always will be.
Congratulations to all OpenCV developers for this great project.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by sashi5** [comment]
OpenCV Error: Null pointer (NULL or empty buffer) in cvOpenFileStorage, file C:\
opencv\sources\modules\core\src\persistence.cpp, line 4153
terminate called after throwing an instance of 'cv::Exception'............
plz anyone help me for tht problm i cant handle it and i m very new for open cv ..
if any one help me thn plzzz give the solution on my email-id = shashisharma6897@gmail.com

**Comment by sashi5** [comment]
plzzzzzzzzzzzzzzzzzzzz..  its urgent

**Comment by StevenPuttemans** [comment]
@sashi5 I am sorry but please make a new issue and provide enough information ...

**Comment by sashi5** [comment]
how to set the permanent binaries in debug mode ??? 
can anyone tell??

**Comment by berak** [comment]
@sashi, please let us move your problems to http://answers.opencv.org

**Comment by sashi5** [comment]
sir actually m very depress ..m trying to solve my problem from last two
week ..if u hv little time thn plz handle my problem ..i cant run forward
until resolve my error

**Comment by StevenPuttemans** [comment]
@sashi5 again, listen to the advise given

1. You are hijacking a closed issue, with a new problem. No one will take the time to look at this.
2. You did not supply extra information, nor a new issue at the issues page.
3. As suggested by @berak issues with using OpenCV are handled on our Q&A website, so put your issues there ...

Again, leave this place and go to the proper channels.
