### ISSUE TITLE
Color blob sample crashes

### ISSUE THREAD

**Issue by akashpopat** [opencv/opencv#6877]
Hey guys

The color blob detection sample app crashes on my device with the SIGNET error and nothing else on the log file. All the other OpenCV samples work perfectly so I dont know what the error might be. I know it occurs in the line 
**mDetector.process(mRgba); .**

PS - I even tried the apk but it crashes there too

Any ideas ?

**Comment by mshabunin** [comment]
Can you attach more detailed information: device model and architecture, Android version, OpenCV version, logcat output?

**Comment by aleksandra-majchrzak** [comment]
I encountered the same problem. It seems that app crashes on call ` multiply_5(src1.nativeObj, src2.val[0], src2.val[1], src2.val[2], src2.val[3], dst.nativeObj);` in `Core.multiply()`. 

Log: `A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 670 (Thread-74833)`

I tested in with OpenCV version 3.3.1 on Samsung A3 Android API 23.

**Comment by alalek** [comment]
>  logcat output

Contains information about version of loaded OpenCV native library.

**Comment by pwnorbitals** [comment]
Has anyone reproduced this issue recently ? I suspect it has been fixed in the meantime
