### ISSUE TITLE
`invalid device symbol` when running corner detection on a GTX 960 on OSX 

### ISSUE THREAD

**Issue by alexlouden** [opencv/opencv#6894]
##### System information

- OpenCV => 3.1 HEAD
- Operating System => OS X 10.11.5 (El Capitan)
- Hardware => Macbook Pro with NVIDIA GeForce GT 750M and external GTX 960.

More info: [device_info.txt](https://github.com/opencv/opencv/files/360666/device_info.txt)

##### Detailed description

Running CUDA good features to track (`cv::cuda::createGoodFeaturesToTrackDetector`) on a GTX 960 on OS X (with both CUDA 7.5 and CUDA 8.0) fails with the following exception, however it works with a GT 750M.

> OpenCV Error: Gpu API call (invalid device symbol) in linearRow, file /tmp/opencv3-20160712-8007-1e5dtil/modules/cudafilters/src/cuda/row_filter.hpp, line 365
> libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160712-8007-1e5dtil/modules/cudafilters/src/cuda/row_filter.hpp:365: error: (-217) invalid device symbol in function linearRow

Any ideas? I'm happy to test and contribute a fix if someone points me in the right direction.

Do I need to add `5.2` to `__cuda_arch_bin` on [OpenCVDetectCUDA.cmake:97](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake#L97)?

##### Steps to reproduce

I've created a sample project to reproduce the issue: https://gist.github.com/alexlouden/8fd753dae97a6a6c6ee9abb87c2c9fc8

Snippet:
```
    cornerDetector = cv::cuda::createGoodFeaturesToTrackDetector(...)

    std::cout << "Detecting corners..." << std::endl;
    cornerDetector->detect(gpuImage, corners);

    // Print number of corners detected
    std::cout << "Corners detected: " << corners.cols << std::endl;
```

If I run it on my GT 760 (internal card, with capability 3.0):

```./Test
*** CUDA Device Query (Runtime API) version (CUDART static linking) *** 

Device 1: "GeForce GT 750M"
  CUDA Driver Version / Runtime Version          8.0 / 7.50
  CUDA Capability Major/Minor version number:    3.0
...

image loaded: [512 x 512]
Detecting corners...
Corners detected: 100

Process finished with exit code 0
```

But it fails on my external GTX 960 (capability 5.2):

```
./Test
*** CUDA Device Query (Runtime API) version (CUDART static linking) *** 

Device count: 2

Device 0: "GeForce GTX 960"
  CUDA Driver Version / Runtime Version          8.0 / 7.50
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 4096 MBytes (4294770688 bytes)
...

image loaded: [512 x 512]
Detecting corners...
OpenCV Error: Gpu API call (invalid device symbol) in linearRow, file /tmp/opencv3-20160712-8007-1e5dtil/modules/cudafilters/src/cuda/row_filter.hpp, line 365
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160712-8007-1e5dtil/modules/cudafilters/src/cuda/row_filter.hpp:365: error: (-217) invalid device symbol in function linearRow

Process finished with exit code 6
```

**Comment by jet47** [comment]
You need to set `CUDA_ARCH_BIN` CMake variable to `"3.0 5.2"` for your system:

```
$ cmake -DCUDA_ARCH_BIN="3.0 5.2" .
$ make
```

`CUDA_ARCH_BIN` controls GPU architecture for which OpenCV CUDA modules are built.

**Comment by alexlouden** [comment]
Thanks for that @jet47. Could we add `3.7 5.0 5.2 5.3` to the list [here](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake#L97) so it works out of the box when installed with homebrew?

**Comment by alexlouden** [comment]
That's awesome @jet47 thanks! I've reinstalled OpenCV from head and it's fixed.
