### ISSUE TITLE
Add use of `std::chrono::steady_clock` into `cv::getTickCount` implementation when C++11 is available

### ISSUE THREAD

**Issue by apavlenko** [opencv/opencv#6902]
- OpenCV => 3.x
- Operating System / Platform => any / c++11
- Compiler => any c++11
##### Detailed description

C++11 implements the standard ISO.20.11.7 in `std::chrono`, so it has much sense using this standard portable implementation inside `cv::getTickCount` when compiler supports it.

**Comment by berak** [comment]
@apavlenko , is there anything already to find out, if there's c++11 support in opencv, like a HAVE_CPP11 macro or similar ? below approach seems ugly.

```
#if __cplusplus > 199711L
  // use chrono::steady_clock
#endif
```

**Comment by apavlenko** [comment]
use of C++ 11 features in OpenCV is in plans yet, so I'm not sure we have already a definition for checking it;

for now I would use something like `#if __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1800)`
