### ISSUE TITLE
 OpenCV 3.1 can't compile on macOS 10.12 beta because QTKit

### ISSUE THREAD

**Issue by zhiqiang-li** [opencv/opencv#6913]
- OpenCV => 3.1
- Operating System / Platform => maxOS 10.12 beta
- Compiler => gcc

##### Detailed description

In macOS 10.12, apple removed most of QTKit's components, include some functions and header files opencv use, so opencv 3 can't compile on macOS 10.12 (eg. header file "QTKit/QTKit.h" file has been removed, which is included in "cap_qtkit.mm").

Maybe should remove QTKit dependancy and use AVFoundation?

**Comment by alalek** [comment]
@zhiqiang-li Could you please take a look on PR #6678 (#6802). Will it solve this issue?

**Comment by donkeyfire** [comment]
@zhiqiang-li  A easy workaround is disable videoio module for now when you build opencv.

**Comment by yzgao** [comment]
@donkeyfire Could you give any steps to disable videoio module when build opencv? Thanks.

**Comment by ilya-lavrenov** [comment]
> Could you give any steps to disable videoio module when build opencv?

`cmake -DBUILD_opencv_videoio=OFF .`

**Comment by galchinsky** [comment]
@alalek #6802 solved the issue, thanks.

**Comment by kaifresh** [comment]
I'm suffering from this problem too. While disabling videoio is a solution, CMake won't generate unless highgui is also disabled. This prevents access to imread(). Is there a way to disable videoio on its own?

**Comment by TobbHuang** [comment]
I meet this problem too in OS X 10.11.6...(after reinstalling os yesterday) MacOS will be pushed some days later, hope I can use opencv on my mac again with videoio module soon...🙏

**Comment by TobbHuang** [comment]
pr#7159(https://github.com/opencv/opencv/pull/7159) works! Thx

**Comment by Qquanwei** [comment]
If using Homebrew you can add flags '--with-quicktime' of install
example `brew install opencv3 --with-quicktime` 
means 'Use QuickTime from video I/O instead of QTKit'

**Comment by kaifresh** [comment]
Thanks I’ll try that.

**Comment by shdxiang** [comment]
You can disable `videoio` but still enable `highgui` by delete the dependence:

1. `opencv-3.1.0/modules/highgui/CMakeLists.txt:2`
modify:
`ocv_add_module(highgui opencv_imgproc opencv_imgcodecs opencv_videoio WRAP python)`
to:
`ocv_add_module(highgui opencv_imgproc opencv_imgcodecs WRAP python)`
2. `cmake -DBUILD_opencv_videoio=OFF .`

**Comment by Ge0rges** [comment]
So I'm having this problem but also require VideoIO. Are there any alternative solutions other than disabling it?
