### ISSUE TITLE
Windows7 64bit Visual Studio 2013 win64 compile opencv_contrib  hdf5.cpp(303): error!

### ISSUE THREAD

**Issue by JohnTian** [opencv/opencv#6914]
##### System information (version)

- OpenCV => 3.1:
- Operating System / Platform => Windows 7  64 Bit
- Compiler => Visual Studio 2013 Win64

##### Detailed description

1. Cmake 3.4.3  make released ** OpenCV3.1.0 ** and **opencv_contrib3.1.0** 
2. Visual Studio 2013 debug mode x64 compile
3. hdf5 error.
5>  hdf5.cpp
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(303): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(303): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(303): error C2133: “dsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(336): warning C4244: “=”: 从“hsize_t”转换到“int”，可能丢失数据
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(395): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(395): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(395): error C2133: “chunks”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(396): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(396): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(396): error C2133: “dsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(397): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(397): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(397): error C2133: “maxdim”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(486): warning C4244: “=”: 从“hsize_t”转换到“int”，可能丢失数据
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(503): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(503): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(503): error C2133: “dsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(521): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(521): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(521): error C2133: “mxdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(522): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(522): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(522): error C2133: “foffset”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(582): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(582): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(582): error C2133: “dsizes”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(583): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(583): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(583): error C2133: “dsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(584): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(584): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(584): error C2133: “offset”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(670): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(670): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(670): error C2133: “dsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(671): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(671): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(671): error C2133: “offset”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(705): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(705): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(705): error C2133: “fsdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(712): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(712): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(712): error C2133: “nwdims”: 未知的大小
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(862): warning C4244: “参数”: 从“hsize_t”转换到“const int”，可能丢失数据
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(935): error C2057: 应输入常量表达式
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(935): error C2466: 不能分配常量大小为 0 的数组
5>D:\ProgramFiles\opencv310\opencv_contrib\modules\hdf\src\hdf5.cpp(935): error C2133: “fsdims”: 未知的大小
6>------ 已启动全部重新生成:  项目: ALL_BUILD, 配置: Debug x64 ------
6>  Building Custom Rule D:/ProgramFiles/opencv310/opencv_contrib/modules/hdf/CMakeLists.txt
6>  CMake does not need to re-run because D:\build\modules\hdf\CMakeFiles\generate.stamp is up-to-date.
7>------ 已启动全部重新生成:  项目: INSTALL, 配置: Debug x64 ------
7>  -- Install configuration: "Debug"
7>  -- Up-to-date: D:/build/install/include/opencv2/hdf.hpp
7>  -- Up-to-date: D:/build/install/include/opencv2/hdf/hdf5.hpp
========== 全部重新生成:  成功 6 个，失败 1 个，跳过 0 个 ==========

**Comment by alalek** [comment]
We don't see this problem on your side: http://pullrequest.opencv.org/buildbot/builders/master-contrib-broadwell-win64-vc14/builds/275

There is no useful info how to reproduce problem.
1) CMake command line and stdout log
2) Build log part with cl.exe compiler invocation for hdf5.cpp
3) HDF5 version

P.S. Ths issue should go to opencv_contrib repository.

**Comment by JohnTian** [comment]
@alalek thanks any way. I handled it out today. I forgotten install HDF5 on my work computer.

**Comment by kli017** [comment]
@JohnTian How do you install HDF5 on windows7? I met the same problem when I compile opencv

**Comment by JohnTian** [comment]
@kli017 Please check this [link](https://www.hdfgroup.org/package/windows-7-64-bit-vs2015/)
