### ISSUE TITLE
Possible typo bug in cvProjectPoints2 function?

### ISSUE THREAD

**Issue by catree** [opencv/opencv#6921]
##### System information (version)

- OpenCV => 2.4.13 / 3.1.0
- Operating System / Platform => /
- Compiler => /

##### Detailed description

I would like to transmit a possible typo bug that someone previously addressed on this [Q&A thread](http://answers.opencv.org/question/92011/typobug-in-function-cvprojectpoints2/).
Honestly, I am not enough qualified for this kind of problem, that's why I would like to post the issue here if someone has the time to check it.

By following his reasoning, we have the distortion definition ([L1007](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1007)):
```
r2 = x*x + y*y;
r4 = r2*r2;
r6 = r4*r2;
a1 = 2*x*y;
a2 = r2 + 2*x*x;
a3 = r2 + 2*y*y;
cdist = 1 + k[0]*r2 + k[1]*r4 + k[4]*r6;
icdist2 = 1./(1 + k[5]*r2 + k[6]*r4 + k[7]*r6);
xd = x*cdist*icdist2 + k[2]*a1 + k[3]*a2;         //L1007
yd = y*cdist*icdist2 + k[2]*a3 + k[3]*a1;

m[i].x = xd*fx + cx;
m[i].y = yd*fy + cy;
```

At some point, the derivative `dmxdt` is computed as ([L1080](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1080)):
```
double dmxdt = fx*(dxdt[j]*cdist*icdist2 + x*dcdist_dt*icdist2 + x*cdist*dicdist2_dt +
                         k[2]*da1dt + k[3]*(dr2dt + 2*x*dxdt[j]));
```

The typo bug would be `4*x*dxdt[j]` instead of `2*x*dxdt[j]` (the current last term).

By comparing [L1007](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1007) and [L1080](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1080), we have:

- derivative of `x*cdist*icdist2` with respect to dt is: `dxdt[j]*cdist*icdist2 + x*dcdist_dt*icdist2 + x*cdist*dicdist2_dt`.

- derivative of `k[2]*a1` with respect to dt is `k[2]*da1dt`.

- derivative of `k[3]*a2` with respect to dt is in the current version `k[3]*(dr2dt + 2*x*dxdt[j])`.

As `k[3]*a2 == k[3] * (r2 + 2*x*x)`, should we have: `k[3]*(dr2dt + 4*x*dxdt[j])`?

The same problem should appear also for [`dmydt`](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1082), [`dmxdr`](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1118), and [`dmydr`](https://github.com/opencv/opencv/blob/2.4.13/modules/calib3d/src/calibration.cpp#L1120).

For OpenCV 3.1.0, the corresponding lines for [`dmxdt`](https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/calibration.cpp#L906), [`dmydt`](https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/calibration.cpp#L908), [`dmxdr`](https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/calibration.cpp#L945) and [`dmydr`](https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/calibration.cpp#L947).

It would be great if someone can clear up my doubts. Sorry for any inconvenience.

**Comment by souch55** [comment]
Hi mshabunin  after calculating the values Fixed the values for dmxdt, dmydt, dmxdr and dmydr,can you review.My pull request #https://github.com/opencv/opencv/pull/7048/commits/a06a057ea41533c74093a03670988e1566c3cc15

**Comment by paroj** [comment]
we derive the expression subject to `t`, therefore we have to apply the chain rule and `x^2 -> 2x*dxdt`.
The proposed change is therefore correct.

**Comment by souch55** [comment]
Fix  Modified 6921 #https://github.com/opencv/opencv/pull/7082
