### ISSUE TITLE
Opencv 3.1 build error

### ISSUE THREAD

**Issue by akashdhamasia** [opencv/opencv#6925]
Hi, I am trying to build opencv-3.1 from source using Visual studio 2013. I have followed the procedure of installing opencv-3.1 from http://docs.opencv.org/master/d3/d52/...

When building it from VS 2013 in debug/release mode, it gives following build errors:

Error 5799 error LNK1104: cannot open file '....\lib\Debug\opencv_cudaobjdetect310d.lib' C:\opencv3\opencv\build\samples\cpp\LINK (TUTORIAL) imageSegmentation

**opencv_cudaobjdetect310d.lib** is creating problem.

And many more like this.

My laptop: **Win8.1 64 bit, Nvidia Geforce 940M Graphics Card, Cuda tookit 7.5, Python 2.7.12, Numpy 1.11.1.**

I want to build opencv with CUDA only, so please somebody help in solving my issue.

**My CMake Configuration Output is:**
```
Windows RT support: NO

GUI: QT: NO Win32 UI: YES OpenGL support: YES (glu32 opengl32) VTK support: NO

Media I/O: ZLib: build (ver 1.2.8) JPEG: build (ver 90) WEBP: build (ver 0.3.1) PNG: build (ver 1.6.19) TIFF: build (ver 42 - 4.0.2) JPEG 2000: build (ver 1.900.1) OpenEXR: build (ver 1.7.1) GDAL: NO

Video I/O: Video for Windows: YES DC1394 1.x: NO DC1394 2.x: NO FFMPEG: YES (prebuilt binaries) codec: YES (ver 56.41.100) format: YES (ver 56.36.101) util: YES (ver 54.27.100) swscale: YES (ver 3.1.101) resample: NO gentoo-style: YES GStreamer: NO OpenNI: NO OpenNI PrimeSensor Modules: NO OpenNI2: YES (ver 2.2.0, build 33) PvAPI: NO GigEVisionSDK: NO DirectShow: YES Media Foundation: NO XIMEA: NO Intel PerC: NO

Parallel framework: Concurrency

Other third-party libraries: Use IPP: 9.0.1 [9.0.1] at: C:/opencv3/opencv/3rdparty/ippicv/unpack/ippicv_win Use IPP Async: NO Use Eigen: YES (ver 3.2.8) Use Cuda: YES (ver 7.5) Use OpenCL: YES Use custom HAL: NO

NVIDIA CUDA Use CUFFT: YES Use CUBLAS: NO USE NVCUVID: NO NVIDIA GPU arch: 20 30 35 50 NVIDIA PTX archs: Use fast math: NO

OpenCL: <dynamic loading="" of="" opencl="" library=""> Include path: C:/opencv3/opencv/3rdparty/include/opencl/1.2 Use AMDFFT: NO Use AMDBLAS: NO

Python 2: Interpreter: C:/Python27/python.exe (ver 2.7.12)

Python 3: Interpreter: NO

Python (for build): C:/Python27/python.exe

Java: ant: NO JNI: NO Java wrappers: NO Java tests: NO

Matlab: Matlab not found or implicitly disabled

Documentation: Doxygen: NO PlantUML: NO

Tests and samples: Tests: YES Performance tests: YES C/C++ Examples: YES

Install path: C:/opencv3/opencv/build/install
cvconfig.h is in: C:/opencv3/opencv/build

Configuring done
```

**Comment by ilya-lavrenov** [comment]
Could you provide full build log? Looks like the quotes are missed in some paths during the build..

**Comment by akashdhamasia** [comment]
ill have to build it again with the same configuration, i deleted the past build log and build folder to test with other configurations.

I have started building again, ill upload the build log as soon it gets finished.

**Comment by wangse** [comment]
My laptop: Win7 64 bit, android studio 2.1 ，gradle-experimental:0.7.3，NDK-r12。
I want to build opencv with ndk only, Using jni call opencv C++ library，so please somebody help in solving my issue.

**Comment by akashdhamasia** [comment]
I have added the full build log, build errors and the Cmake Output in the attached files. 

[Build_Errors_Opencv.pdf](https://github.com/opencv/opencv/files/467901/Build_Errors_Opencv.pdf)
[Build_log_Opencv.pdf](https://github.com/opencv/opencv/files/467902/Build_log_Opencv.pdf)
[Cmake_output_Opencv.pdf](https://github.com/opencv/opencv/files/467903/Cmake_output_Opencv.pdf)

**Comment by alalek** [comment]
@akashdhamasia Are you able to build OpenCV without CUDA? (You can use `-DWITH_CUDA=OFF` CMake option, but make full clean of build directory).


> c:\program files\openni\include\XnPlatform.h(58): fatal error C1189: #error : Xiron Platform
Abstraction Layer - Win32 - Microsoft Visual Studio versions above 2010 (10.0) are not supported! 

Disable OpenNI/OpenNI2: `-DWITH_OPENNI=OFF` / `-DWITH_OPENNI2=OFF` Cmake options. Or try to upgrade OpenNI SDKs and rerun OpenCV build from scratch (clean build directory).

**Comment by akashdhamasia** [comment]
Solved it. Resolving compile errors solved the link errors problem. Cuda was not the problem, problem lied in tesseract and openni, on resolving those successfully builded the opencv.

Thanks everyone.
