### ISSUE TITLE
Code error in NAryMatIterator code sample in the documentation.

### ISSUE THREAD

**Issue by catree** [opencv/opencv#6935]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Any
- Compiler => Any

##### Detailed description

The NAryMatIterator code sample in the documentation compiles with errors (two variables `it` has the same name, bad arguments, ...), similar to this [issue](http://code.opencv.org/issues/3787).

##### Steps to reproduce

Compile the following code present in the [documentation](http://docs.opencv.org/3.1.0/d5/dd2/classcv_1_1NAryMatIterator.html):

```
void computeNormalizedColorHist(const Mat& image, Mat& hist, int N, double minProb)
{
    const int histSize[] = {N, N, N};
    // make sure that the histogram has a proper size and type
    hist.create(3, histSize, CV_32F);
    // and clear it
    hist = Scalar(0);
    // the loop below assumes that the image
    // is a 8-bit 3-channel. check it.
    CV_Assert(image.type() == CV_8UC3);
    MatConstIterator_<Vec3b> it = image.begin<Vec3b>(),
                             it_end = image.end<Vec3b>();
    for( ; it != it_end; ++it )
    {
        const Vec3b& pix = *it;
        hist.at<float>(pix[0]*N/256, pix[1]*N/256, pix[2]*N/256) += 1.f;
    }
    minProb *= image.rows*image.cols;
    Mat plane;
    NAryMatIterator it(&hist, &plane, 1);
    double s = 0;
    // iterate through the matrix. on each iteration
    // it.planes[*] (of type Mat) will be set to the current plane.
    for(int p = 0; p < it.nplanes; p++, ++it)
    {
        threshold(it.planes[0], it.planes[0], minProb, 0, THRESH_TOZERO);
        s += sum(it.planes[0])[0];
    }
    s = 1./s;
    it = NAryMatIterator(&hist, &plane, 1);
    for(int p = 0; p < it.nplanes; p++, ++it)
        it.planes[0] *= s;
}
```

**Comment by ilya-lavrenov** [comment]
@mshabunin, do we have a lot of code examples in .hpp files? I think it's better to extract all code examples into .cpp files and use `\snippet` doxygen command. And all .cpp files will be compiled as static library to check that documentation snippets are compilable.

CC @alalek, @vpisarev, @apavlenko

**Comment by mshabunin** [comment]
@ilya-lavrenov , yes I agree. But I'd prefer to make executables in `samples/cpp` folder. I've created new issue to track this: #6938
