### ISSUE TITLE
Pyrlk.co: DenormalizationFactor const float cannot have an in-class initializer in vs 2013

### ISSUE THREAD

**Issue by deanezra** [opencv/opencv#6939]
##### System information (version)

- OpenCV => 3.1 (taken from git on 17.07.2016)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013 community

Using CUDA 7.5

##### Detailed description

I think the below initializers are C++11 and visual studio doesnt support them:    

File: pyrlk.cu:

```.cpp
template <typename T>
    struct DenormalizationFactor
    {
        static const float factor = 1.0;
    };

    template <>
    struct DenormalizationFactor<uchar>
    {
		static const float factor = 255.0;
    };
```

##### Steps to reproduce

Build using visual studio 2013 community.

I enabled on building of Keplar (3.0) cuda in cmake. But not sure if this affects the error.

**Comment by andy-held** [comment]
Hi deanezra,

could you please verify, that my fix works with msvc120?

**Comment by deanezra** [comment]
Will do, thanks

**Comment by deanezra** [comment]
hi @andy-held, I confirm that your fix worked. I have just completed the build using ms vc12 (Visual studio 2013)
