### ISSUE TITLE
cv::format does not work with long std::string as parameter

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#6943]
``cv::format("Test %s", "1232132131232132131232132132131313123");`` 
works but
``cv::format("Test %s", std::string("1232132131232132131232132132131313123"));`` 
produces garbage, e.g. ``Test áQh↓½``.

``cv::format("Test %s", std::string("1232132131232132131232132132131313123").c_str());`` works again

**Comment by alalek** [comment]
This is not related to OpenCV.
`printf("%s", std::string("test"))` provides garbage also. `printf` expects "const char*" parameter, but receives `std::string` object. You should use ".c_str()" method to get "const char*" pointer: `printf("%s", string_obj.c_str())`
