### ISSUE TITLE
Template Update: Load, Modify, and Save an Image

### ISSUE THREAD

**Issue by joemaniaci** [opencv/opencv#6944]
Just for full Tutorial completeness without having to track down headers to include, include the following...

```
#include <opencv2/imgproc/imgproc.hpp>
#include <stdio.h>
```

For users that install the latest openCV version, in my case 2.4.13.

[http://docs.opencv.org/2.4/doc/tutorials/introduction/load_save_image/load_save_image.html]

**Comment by Asalle** [comment]
Working on it
