### ISSUE TITLE
OpenCV >= 3.0  x64 prebuilt vc11 libraries give an error for videoio

### ISSUE THREAD

**Issue by njferrier** [opencv/opencv#6947]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

when trying to load an avi file with videocapture  (code from the tutorial), I get a run time error. 

Videocapture working well with a camera - wanted to add file functionality - would prefer not to have  to build library on windows from scratch (worked fine on Linux). 

With OpenCV 3.1:
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578)
Could not open capture file C:\Converted\TraningV1.avi
Image is sized 0 by 0

With OpenCV 3.0 the error is similar (except it is a "relative" path in the message);
warning: Error opening file (../../modules/highgui/src/cap_ffmpeg_impl.hpp:537)
Could not open capture file C:\Converted\TraningV1.avi
Image is sized 0 by 0

**Comment by YoOoHo** [comment]
Hi,
I got caught in the same problem when I tried to read a video whether I used absolute path or relative path. Though the version of my OpenCV is 2.4.13, I think the problem has nothing to do with it.
Have you already known how to solve it?
Thanks~

**Comment by alalek** [comment]
On Windows you need to put `opencv_ffmpeg*.dll` files near your application binary (or follow specifications of `LoadLibrary` function).
