### ISSUE TITLE
DICOM load test

### ISSUE THREAD

**Issue by mshabunin** [opencv/opencv#6948]
Need basic DICOM loading test (gray/RGB) and install GDCM library on buildbot.

**Comment by mrquorr** [comment]
- What do you mean with load testing, just to start loading on as many images as possible and get a readout on efficiency?
- Where is the code for buildbot? I've been going through the source code on the repo and found no reference to it.

**Comment by mshabunin** [comment]
@mrquorr , no I meant adding simple `imread` test to be sure basic functionality is working.

Please, take a look at the [imgcodecs tests](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/test/test_grfmt.cpp). We need simple check that `imread` works for several DICOM example files. Following are the requirements for test images:
- they should be put to the `opencv_extra` repository [with others](https://github.com/opencv/opencv_extra/tree/master/testdata/highgui/readwrite) (note that branch should be named same as main repository branch to allow buildbot test them together)
- these files should be rather small (total size <1Mb if possible)
- most popular supported modes should be covered - single image in file; 1 channel - u8, u16, f32; 3 channels - u8 (all supported modes can be found [here](https://github.com/opencv/opencv/blob/f3bd508e6d96c3f988da2bb14a3a8ec7930193df/modules/imgcodecs/src/grfmt_gdcm.cpp#L103))
- should not contain private data (you can make them from other images like `lena.png` or take from some datasets)

I will make changes on buildbot by myself once the pullrequest is submitted.

**Comment by mrquorr** [comment]
Ok, I got some examples from here http://www.osirix-viewer.com/datasets/. I'll check if these cover the most popular supported modes.

**Comment by mrquorr** [comment]
I'm having some trouble compiling the opencv library with GDCM support. Does the GDCM library need extra configurations when making it for opencv's WITH_GDCM option to work?

**Comment by mshabunin** [comment]
I used `libgdcm2-dev` package in Ubuntu to install GDCM. Did you build it yourself? Probably some flags should be set when configuring GDCM to enable PIC or build shared library.

**Comment by mrquorr** [comment]
Yeah, that was it. I was building it from source, after installing the `libgdcm2-dev` package `make` ran without problems.

**Comment by mrquorr** [comment]
Yeah, that was it. I was building it from source, after installing the `libgdcm2-dev` package `make` ran without problems.

**Comment by Asalle** [comment]
why is this still an open issue?

**Comment by mshabunin** [comment]
@Asalle , because pull request with the new test has not been integrated yet.

**Comment by parismita** [comment]
@mshabunin  what else is to be done here?

**Comment by mshabunin** [comment]
Implemented in #7180
