### ISSUE TITLE
stitching modules conflicts with googlelog (glog) because of LOG macro

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#6960]
##### System information (version)

- OpenCV => trunk
- Operating System / Platform => Ubuntu 14.04 LTS
- Compiler => gcc 4.9.3

##### Detailed description

Using Google log (glog) along with the stitching module will cause compilation error. It's because glog defines the "LOG" macro and the stitching module also defines it at /opencv/modules/stitching/include/opencv2/stitching/detail/util.hpp. A possible resolution is append "CV_" for the "LOG" macro and make it "CV_LOG" instead in the stitching module. 

##### Steps to reproduce

``````
#include "glog/logging.h"
#include "opencv2/opencv.hpp"
#include "opencv2/stitching.hpp"

int main(int argc, char **argv)
{
  google::InitGoogleLogging(argv[0]);
  
  LOG(INFO) << "hello world";

  return 0;
}
``````
results in compilation error. Remove 

``````
#include "opencv2/stitching.hpp"
``````
and it compiles.

**Comment by ilya-lavrenov** [comment]
Use can use:
```
#include "opencv2/opencv.hpp"
#include "opencv2/stitching.hpp"
#undef LOG
#include "glog/logging.h"

int main(int argc, char **argv)
{
  google::InitGoogleLogging(argv[0]);

  LOG(INFO) << "hello world";

  return 0;
}
```

**Comment by StevenPuttemans** [comment]
Also when moving from 2.4 to 3.1 the CV_ prefixes where removed for decent counterparts, so reintroducing them is not the way forward I guess.

**Comment by alalek** [comment]
"CV_" prefixes were removed for enums from cv namespace only.
C++ macros is global thing, so "CV_" prefix should be added, especially in public headers.

**Comment by hrnr** [comment]
What is used for logging in other modules? In stitching module these macros are there mostly for profiling (time measurements). How this approached elsewhere?

**Comment by jasjuang** [comment]
Thanks for the fix!
