### ISSUE TITLE
Apparently meaningless line of code in data.cpp. May hide deeper bug.

### ISSUE THREAD

**Issue by therealadrian** [opencv/opencv#6973]
Line 749 of modules/ml/src/data.cpp appears to be a bug:

while(*stopstring != ']');

Should perhaps be: 

while(*stopstring++ != ']');

It appears that the function of this line is to skip over whitespace or other meaningless delimeters between 'ord' and 'cat' specifications. In any case, the current line has, at best, no function and, at worst, could cause an indefinite hang (under circumstances that appear, at the moment, to be impossible, but which might arise after other changes to the code above it).

**Comment by berak** [comment]
did you miss, that it's part of a `do { something } while (*stopstring++ != ']');` loop started in [line 719](https://github.com/opencv/opencv/blob/master/modules/ml/src/data.cpp#L719) ?

**Comment by therealadrian** [comment]
You are correct. I did miss that. Thank you for the clear explanation.
