### ISSUE TITLE
issue with building from source 

### ISSUE THREAD

**Issue by umangty** [opencv/opencv#6978]
##### System information (version)

- OpenCV => master
- Operating System / Platform => ubuntu 16.04
- Compiler => g++/cmake

##### Detailed description

make command showing error after successful completion of cmake while building from source.
following this-> https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-OpenCV-3.1-Installation-Guide
![screenshot from 2016-07-24 09-13-55](https://cloud.githubusercontent.com/assets/11703565/17081696/f358e588-517f-11e6-92d5-2aceb6e00ae2.png)

**Comment by tomoaki0705** [comment]
It seems that #6976 will fix this
