### ISSUE TITLE
Segfault when deleting splitted images from cv::split

### ISSUE THREAD

**Issue by basvandijk** [opencv/opencv#6997]
Are you supposed to delete the splitted images returned in the *mvbegin* array in the [cv::split(const Mat & src,Mat * mvbegin)](http://docs.opencv.org/trunk/d2/de8/group__core__array.html#ga0547c7fed86152d7e9d0096029c8518a) function? 

I guess not since the following example generates a segfault:

```.cpp
#include <stdio.h>
#include <unistd.h>
#include <sys types.h>
#include <sys stat.h>
#include <fcntl.h>
#include <opencv2 core.hpp>
#include <opencv2 imgcodecs.hpp>

#define N 600000

main(){
  int fd = open("data/kodim23.png", O_RDONLY);

  uchar buf[N];

  int size = read(fd, buf, N);

  cv::_InputArray cbuf = cv::_InputArray(buf, size);
  cv::Mat * img = new cv::Mat(cv::imdecode(cbuf, cv::IMREAD_UNCHANGED));

  cv::Mat imgs[img->channels()];

  cv::split(*img, imgs);

  for(int i; i < img->channels(); i++){
    delete &imgs[i];
  }
}
```

This is with OpenCV-3.1.

**Comment by alalek** [comment]
> delete &imgs[i];

It is invalid to call "delete" on non-heap objects. Your `imgs` are allocated on stack.
To free image data you should call `imgs[i].release();` instead.

**Comment by basvandijk** [comment]
Thanks that makes total sense.
