### ISSUE TITLE
python detection only run once

### ISSUE THREAD

**Issue by toinsson** [opencv/opencv#7005]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => native

##### Detailed description
When building OpenCV from source, and within a conda environment, my python install is not fully detected in the first pass, e.g. INCLUDE and LIBRARY are not set. 
Due to 9bee835daca44b894c5c9689641bf639090fc9d3, when re-running CMAKE a second time, the configuration is never updated.

##### Steps to reproduce
placing a cmake MESSAGE in opencv/cmake/OpenCVDetectPython.cmake after line 29, or after if(NOT ${found}) shows the rest of the code is only executed one time.

##### Fix
I am not sure I see the reason behind this if statement.

**Comment by alalek** [comment]
> when re-running CMAKE a second time, the configuration is never updated

CMake cache technology is used for this exactly. Any auto-detections are one time runners.
IF you want to change something in configuration - build from scratch (clean build directory and run CMake again).

> I am not sure I see the reason behind this if statement.

One reason is in description of #6000
