### ISSUE TITLE
linearPolar & LogPolar docs: exchange rho and phi ?

### ISSUE THREAD

**Issue by PkLab** [opencv/opencv#7009]
##### System information (version)
- OpenCV => 3.1
- OpenCV => 2.4.13

##### Detailed description

The [doc states](http://docs.opencv.org/3.1.0/da/d54/group__imgproc__transform.html#gaa38a6884ac8b6e0b9bed47939b5362f3) dst(ϕ,ρ)=src(x,y) but result shows dst(ρ,ϕ)=src(x,y) . See this simple test:

**linearPolar**(![linearimage](https://cloud.githubusercontent.com/assets/15944968/17445124/a1258fc8-5b43-11e6-9b20-e751a4e97769.png) = ![linearpolar](https://cloud.githubusercontent.com/assets/15944968/17445206/1027f294-5b44-11e6-9bcf-c1f197893b19.png)

**logPolar**(![linearimage](https://cloud.githubusercontent.com/assets/15944968/17445124/a1258fc8-5b43-11e6-9b20-e751a4e97769.png) = ![logpolar](https://cloud.githubusercontent.com/assets/15944968/17492574/b00d5780-5dac-11e6-9a6d-efb2afca2047.png)

##### Steps to reproduce

Here is the code to produce above images
```.cpp
#define TEST_OCL 0
#if TEST_OCL==1
#include <opencv2/core/ocl.hpp>
#endif
int LinPolarDocIssue()
{
    int  radius = 50;
    int border = 80;
    Size sz = Size(radius + border, radius + border) * 2;
    Point center(radius + border, radius + border);

#if TEST_OCL==1
    cv::ocl::setUseOpenCL(true);
    UMat src, linPolarImg, logPolarImg;
    src = UMat::zeros(sz, CV_8UC3);
#else
    Mat src, linPolarImg, logPolarImg;
    src = Mat::zeros(sz, CV_8UC3);
#endif

    circle(src, center, radius, Scalar::all(255.), 1);
    Scalar cl(0, 255, 0);
    line(src, center + Point(0, 0.8*radius), center + Point(0, radius), cl);
    putText(src, "90deg", center + Point(0, 0.8*radius), FONT_HERSHEY_PLAIN, 1, cl);
    double M = src.cols / log(radius+10);
#if CV_VERSION_MAJOR<=2
    src.copyTo(linPolarImg);
    src.copyTo(logPolarImg);
    IplImage _src(src), _polar(linPolarImg), _logPolar(logPolarImg);
    cvLinearPolar(&_src, &_polar, center, radius + 10, CV_INTER_LINEAR + CV_WARP_FILL_OUTLIERS);
    cvLogPolar(&_src, &_logPolar, center, M, CV_INTER_LINEAR + CV_WARP_FILL_OUTLIERS);
#else
    cv::linearPolar(src, linPolarImg, center, radius + 10, CV_INTER_LINEAR + CV_WARP_FILL_OUTLIERS);
    cv::logPolar(src, logPolarImg, center, M, CV_INTER_LINEAR + CV_WARP_FILL_OUTLIERS);
#endif
    cl = Scalar(0, 0, 255);

    arrowedLine(src, center, center + Point(50, 0), cl);
    putText(src, "X", center + Point(55, 0), FONT_HERSHEY_PLAIN, 1, cl);
    arrowedLine(src, center, center + Point(0, 50), cl);
    putText(src, "Y", center + Point(0, 55), FONT_HERSHEY_PLAIN, 1, cl);

    arrowedLine(linPolarImg, Point(10, 10), Point(50, 10), cl);
    putText(linPolarImg, "rho", Point(55, 10), FONT_HERSHEY_PLAIN, 1, cl);
    arrowedLine(linPolarImg, Point(10, 10), Point(10, 50), cl);
    putText(linPolarImg, "phi", Point(10, 55), FONT_HERSHEY_PLAIN, 1, cl);


    imshow("Linear Image", src);
    imshow("Linear Polar", linPolarImg);
    imshow("Log Polar", logPolarImg);
    waitKey(0);
    return 0;
}
```

**Comment by sovrasov** [comment]
Yes, it's a mistake

**Comment by mshabunin** [comment]
Is it documentation issue or problem with code? What is the behavior of same function from 2.4? As I can see the documentation for 2.4 has same formula.

**Comment by PkLab** [comment]
Updated test function (see #if) shows same result with 2.4.13 head (own build on win7: no cuda, no ipp, yes/no opencl, yes/no opengl, yes/no openmp).

**Comment by PkLab** [comment]
Same also for logPolar. I've updated the test function

**Comment by LaurentBerger** [comment]
I can give my advice. i have just checked [LinearPolar](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L6987) . this function use [cartToPolar](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L1499) with parameter x,y,magnitude and angle. Linearpolar at [this line](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L7057).  variable is set to magintude and variable phi to angle. [mapx is for rho and mapy is for phi](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L7063-7064).
In [remap doc](http://docs.opencv.org/master/da/d54/group__imgproc__transform.html#gab75ef31ce5cdfb5c44b6da5f3b908ea4&gsc.tab=0) 
dst(x,y)=src(mx,my)
and in linearpolar we have [remap(src,dst,mapx,mapy...](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L7069) and hence remap (src,dst,rho,phi)

I am agree with @PkLab and @sovrasov doc should be dst(ρ,ϕ)=src(x,y) (and not dst(ϕ,ρ)=src(x,y))
I hope it will help

**Comment by PkLab** [comment]
It looks just a doc issue but  [WARP_INVERSE_MAP](http://docs.opencv.org/master/da/d54/group__imgproc__transform.html#gga5bb5a1fea74ea38e1a5445ca803ff121aa48be1c433186c4eae1ea86aa0ca75ba) is another (wrong ?) ref. 

In addiction it looks that [ocl_linearPolar](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L4657) confirms ρ and ϕ  inversion. I changed the above code to test also OCL but I don't have a ready machine for tests. @LaurentBerger:  ... could you ?

**Comment by LaurentBerger** [comment]
I have change a [little code](https://gist.github.com/LaurentBerger/dc8ddcd440a17b62080c9909264df270) and it gives 
![ocl](https://cloud.githubusercontent.com/assets/3591626/17493328/1883fe42-5db0-11e6-8c1c-c4a8c49ca534.png)
