### ISSUE TITLE
gftt.cu will not compile

### ISSUE THREAD

**Issue by jmorgie** [opencv/opencv#7012]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- Cuda v 8.0

##### Detailed description

Started clean compile of Opencv 3.1;  used Git to get stable 3.1 from December.  Using Cuda 8.

Ran CMake to generate VS projects

Tried to Build only modules project
received 4 errors in gftt.cu, all having to do with thrust sort.inl not having a definition.

##### Steps to reproduce

anyone else have this issue?

**Comment by jmorgie** [comment]
apparent.ly well known issue.  nvidia claim it is fixed in latest cuda 8 release.

**Comment by gdkrmr** [comment]
I am having the same issue with CUDA Version 8.0.27, it is a recent release candidate, when was this supposed to be fixed?
