### ISSUE TITLE
Error building OpenCV 3.1 with MinGW-W64 i686-6.1.0-posix-dwarf-rt_v5-rev0

### ISSUE THREAD

**Issue by cgwic** [opencv/opencv#7014]
- OpenCV => 3.1
- Operating System / Platform => Windows 7x64
- Compiler => MinGW-W64 i686-6.1.0-posix-dwarf-rt_v5-rev0
##### Detailed description

Error happens during linking all of tests:

```
../../lib/libopencv_ts310.a(ts.cpp.obj):ts.cpp:(.text$_ZN6cvtest2TS4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x119): undefined reference to `cv::redirectError(int (*)(int, char const*, char const*, char const*, int, void*), void*, void**)'
collect2.exe: error: ld returned 1 exit status
```

Seems it caused by this patch https://github.com/opencv/opencv/commit/3a4c14e549ce12ac7b0e8f1e48096054b43efe87
where call to `cvRedirectError` was replaced with `cv::redirectError` in https://github.com/opencv/opencv/commit/3a4c14e549ce12ac7b0e8f1e48096054b43efe87#diff-328d03eb0df32533ffd4ddfb45ee4c40R463

For me everything linked fine when i've put previous call back.

**Comment by HaiQW** [comment]
I've encountered the same problem.    @cgwic 's suggestion worked. .
