### ISSUE TITLE
install  opencv 2.4.13

### ISSUE THREAD

**Issue by CrazyPopLin** [opencv/opencv#7019]
##### System information (version)

- OpenCV => : original 2.4.8 
- Operating System / Platform => :LUbuntu 14.04
- Compiler => :gcc/g++-4.8

##### Detailed description

**Sorry to just post my simple question here cause I first post in opnecv forum but no reply for a long time. And try severals solutions from google without outcome.**

 I am using ODROID (arm board) with LUbuntu 14.04 and initial installed Opencv 2.4.8.  
And I want use to the newest version which is 2.4.13. I followed the [tutorial](http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html) step by step. But when I run the command **pkg-config --modversion opencv**, the output is still 2.4.8.  

##### Questions
I have a question how to upgrade opencv to newest version?  
Or how I can set the libs path to find this new installed package?  
Or how to uninstall the 2.4.8 version.  

Thanks for your suggestions.

**Comment by alalek** [comment]
This is not related to OpenCV directly.
Read about packaging/software installation in Linux and about [`PKG_CONFIG_PATH`](http://askubuntu.com/questions/210210/pkg-config-path-environment-variable) environment variable.
