### ISSUE TITLE
OpenCV 3.1 Linux Build Issues (hal_internal)

### ISSUE THREAD

**Issue by jlaura** [opencv/opencv#7022]
##### System information (version)
- OpenCV => 3.1+ (master)
- Operating System / Platform => Ubuntu 12.04
- Compiler => gcc 4.6

##### Detailed description
I am having trouble building OpenCV 3.1 on linux and am seeing build errors related to the hal_internal.cpp file and the Complex type.  The full build is available via TravisCI [here](https://travis-ci.org/USGS-Astrogeology/conda-opencv3/jobs/148973243#L6442).  The link is direct to the error line.  The build is working well on OS X.  I am building against Eigen 3.2.8 and am not sure if that might be the issue?

I am checking out a commit from earlier this morning, so am, about as fresh as possible.

**Comment by alalek** [comment]
Temporary workaround is to add `-DWITH_LAPACK=OFF` into CMake command-line parameters list.

Could you try to patch `hal_internal.cpp`? Add
```
#undef complex
```
before  C++ includes (algorithm, etc). Looks like it is a [problem](http://stackoverflow.com/questions/23414270/c-complex-and-complex-h-in-the-same-file) of GCC<4.8.

**Comment by jlaura** [comment]
Adding the `#undef complex` line solved the issue.  Thanks!  

Unfortunately, this did not allow for a full build.  I hesitate to open another ticket - I had not realized how out of date the Travis C++ compiler was.  Here is a link to the build if of interest.  I will pursue upgrading the compiler on the Travis docker instance.

https://travis-ci.org/USGS-Astrogeology/conda-opencv3/jobs/149269739

**Comment by alalek** [comment]
I see this message and I have no idea how to fix this for GCC 4.6:

> c++: internal compiler error: Killed (program cc1plus)

**Comment by jlaura** [comment]
Testing now with an updated compiler and an image with a larger swap space.  It looks like the issue might be the build image and limited swap space. Guessing because of the 'Killed'.  

Not sure what your communities close policy is.  As far as I am concerned, this issue is closable - the error is being induced by the out of date compiler.
