### ISSUE TITLE
creat libopencv_java.so from source

### ISSUE THREAD

**Issue by boazgarty** [opencv/opencv#7023]
@alalek ,
follow my latest comment below:

"can you please add the fix based on the official openCV 2.4.11 release.
I have many compilation errors while trying to build the night build from the 1 to July and I have problems publish my app to google play due to "libpng containing a security vulnerability".
"
I managed to build the project using http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk
with command make -j8
I can see build_android_arm->lib->armeabi-v7a but I cant see file libopencv_java.so
Im using this file in my Android project, my question is how can i generate libopencv_java.so to import to my project, also can Generate libopencv_java.so for armeabi?

Thanks!

**Comment by alalek** [comment]
I believe you need to install "Apache Ant" tool. Check your CMake output:
```
--   Java:
--     ant:                         /usr/local/bin/ant (ver 1.9.4)
--     Java tests:                  NO
```

**Comment by boazgarty** [comment]
Perfect! you are right, now I can build java files
is there an option to get armeabi build?

**Comment by alalek** [comment]
Add this CMake option: `-DANDROID_ABI=armeabi`
Other possible values are [here](https://github.com/opencv/opencv/blob/fc742da6e31dce17c1b377bfdbabf9e0078fa689/platforms/android/build_sdk.py#L79) (from 3.x branch)

**Comment by boazgarty** [comment]
Thanks, works.
