### ISSUE TITLE
opencv2 header not including everything in standard library

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#7027]
Is there a reason why adding `#include "opencv2\opencv.hpp"` excludes several modules? For example using the stitcher only works if you combine it with the specific header like follows

```
#include "opencv2/opencv.hpp"
#include "opencv2/stitching.hpp"
``` 

Since the stitching module is in the core library and not in the contributed modules, my opinion is that it should get included using the `opencv.hpp` header...

**Comment by StevenPuttemans** [comment]
@alalek does this tag means that the dev team actually agrees on this? If so I can simply provide a pull request, but I was wondering what the team would think!

**Comment by mshabunin** [comment]
@StevenPuttemans , this tag means that a comment from core team or other appropriate person is needed.

As I can see, the `opencv2/opencv.hpp` include `opencv_modules.hpp` which should be generated by cmake from [the template](https://github.com/opencv/opencv/blob/master/cmake/templates/opencv_modules.hpp.in). Does it contain needed module?

**Comment by StevenPuttemans** [comment]
I guess there lies the problem. After building OpenCV, the content of my auto generated `opencv_modules.hpp` found at `/usr/local/include/opencv2/` after doing a `sudo make install` is

```
/*
 *      ** File generated automatically, do not modify **
 *
 * This file defines the list of modules available in current build configuration
 *
 *
*/

#define HAVE_OPENCV_CALIB3D
#define HAVE_OPENCV_CORE
#define HAVE_OPENCV_FEATURES2D
#define HAVE_OPENCV_FLANN
#define HAVE_OPENCV_HIGHGUI
#define HAVE_OPENCV_IMGCODECS
#define HAVE_OPENCV_IMGPROC
#define HAVE_OPENCV_ML
#define HAVE_OPENCV_OBJDETECT
#define HAVE_OPENCV_PHOTO
#define HAVE_OPENCV_SHAPE
#define HAVE_OPENCV_STITCHING
#define HAVE_OPENCV_SUPERRES
#define HAVE_OPENCV_VIDEO
#define HAVE_OPENCV_VIDEOIO
#define HAVE_OPENCV_VIDEOSTAB
```

So basically the defines are there, but not the includes that need to be in between them :D looks like a bug to me!

**Comment by mshabunin** [comment]
Yes, I agree. Feel free to provide pull request with a fix.

BTW, if you add `-DCMAKE_INSTALL_PREFIX=install` parameter when running cmake, then `make install` will put all files to `build/install` folder without modifying system libraries and headers. It can be useful for experimenting.

**Comment by StevenPuttemans** [comment]
Ah good to know!
