### ISSUE TITLE
there seems to be a simple string error!!

### ISSUE THREAD

**Issue by EXing** [opencv/opencv#7028]
CMake Error at cmake/OpenCVPCHSupport.cmake:125 (FILE):
  Syntax error in cmake code at

    /home/huangkun/opencv-3.1.0/cmake/OpenCVPCHSupport.cmake:125

  when parsing string

    /home/huangkun/opencv-3.1.0/build/modules/core/precomp.hpp.gch/opencv_core_Release\Debug.gch

  Invalid escape sequence \D
Call Stack (most recent call first):
  cmake/OpenCVPCHSupport.cmake:280 (_PCH_GET_COMPILE_COMMAND)
  cmake/OpenCVPCHSupport.cmake:370 (add_precompiled_header)
  cmake/OpenCVModule.cmake:917 (ocv_add_precompiled_header_to_target)
  cmake/OpenCVModule.cmake:888 (_ocv_add_precompiled_headers)
  cmake/OpenCVModule.cmake:730 (_ocv_create_module)
  modules/core/CMakeLists.txt:31 (ocv_create_module)

-- Configuring incomplete, errors occurred!
See also "/home/huangkun/opencv-3.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/huangkun/opencv-3.1.0/build/CMakeFiles/CMakeError.log".

**Comment by AshemH** [comment]
Hi,
please, did you find a solution for this problem ?!
i have the same probem !

**Comment by EXing** [comment]
opencv-3.1.0/build/modules/core/precomp.hpp.gch/opencv_core_Release\Debug.gch

maybe due to '\', you should change to '/'. It's hard to remember!
