### ISSUE TITLE
A small code slip

### ISSUE THREAD

**Issue by Michlong** [opencv/opencv#7032]
##### System information (version)
- OpenCV => 3.1

##### Detailed description

I think, there is a code slip in [seam_finders.cpp, line 641](https://github.com/opencv/opencv/blob/fc742da6e31dce17c1b377bfdbabf9e0078fa689/modules/stitching/src/seam_finders.cpp#L641) 
`double cx2 = cvRound(sum[j].x / size2), cy2 = cvRound(sum[j].y / size1);`
the second `size1 `should be `size2`;

**Comment by alalek** [comment]
Thanks for report!
This problem is reported here #7017
