### ISSUE TITLE
cmake, make -j4 and sudo make install are successful but still can't import cv2

### ISSUE THREAD

**Issue by monajalal** [opencv/opencv#7037]
So I ran all these commands successfully however still cv2 cannot be imported. Any thought or fix is really appreciated in prior:
```
 ~  c   master ⭑  Face_Recognition  ls                                                                                                  10:03:38 PM
3.1.0.zip            3.1.0.zip.1          opencv-3.1.0         opencv_contrib-3.1.0 papers
-------------------------------------------------------  

In opencv-3.1.0/modules/viz/src/vtk/vtkCocoaInteractorFix.mm
#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION >=2

If we use VTK 7.0.0, although it is a newer version, the minor version is less than two, so the vtkCocoaInteractorFix.mm will handle this as older VTK versions and that causes the problem.

So to fix this we just need to add the version number 7 to the line.

#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION >=2 || VTK_MAJOR_VERSION >=7
---------------------------------------------------------------------------
cmake -D CMAKE_BUILD_TYPE=RELEASE \
	  -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_opencv_java=OFF \
      -D WITH_IPP=OFF -D WITH_1394=OFF \
      -D WITH_FFMPEG=OFF\
      -D BUILD_EXAMPLES=ON \
      -D BUILD_TESTS=ON \
      -D BUILD_PERF_TESTS=OFF \
      -D BUILD_DOCS=ON \
      -D BUILD_opencv_python3=ON \
      -D BUILD_opencv_video=ON \
      -D BUILD_opencv_videoio=ON \
      -D BUILD_opencv_videostab=ON \
      -D PYTHON_EXECUTABLE=$(which python) \
      -D OPENCV_EXTRA_MODULES_PATH=/Users/mona/computer_vision/Face_Recognition/opencv_contrib-3.1.0/modules ..


-------------------------------------------------------     
make -j4


-------------------------------------------------------   
sudo make install


```

and when I import it I get:
```
Python 3.5.2 (default, Jul 28 2016, 21:28:07)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
>>> sys.path
['', '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5', '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', '/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages', '/usr/local/Cellar/numpy/1.11.1/libexec/nose/lib/python3.5/site-packages']
bash-4.3$ uname -a
Darwin Monas-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64


```

@tdsmith  @StevenPuttemans @alalek  I thought you might have an idea what could have gone wrong.

**Comment by BoltzmannBrain** [comment]
I'm having issues as well, but with Python 2.7:

```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/alex/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: lib/libopencv_reg.3.1.dylib
  Referenced from: /Users/alex/local/lib/python2.7/site-packages/cv2.so
  Reason: image not found
```

**Comment by monajalal** [comment]
@boltzmannbrain I think it would help the opencv contributors if you could tell them which CMAKE flags you used and if you had no problem with make -j4 (or idk make -j8) and sudo make install step. Also providing them with sys.path would be beneficial so they would have a better understanding of the underlying problem. 
You most probably have to link cv2.so using `ln -s` command but I leave it to contributor to provide you with exact fix.

**Comment by BoltzmannBrain** [comment]
Thanks @monajalal. Here are the exact commands I ran:

	$ git clone https://github.com/opencv/opencv.git
	$ cd opencv
	$ git checkout 3.1.0
	$ cd ..
	$ git clone https://github.com/opencv/opencv_contrib
	$ cd opencv_contrib
	$ git checkout 3.1.0
	$ cd ../opencv
	$ mkdir build
	$ cd build
	$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
			-D CMAKE_INSTALL_PREFIX=${HOME}/Code/opencv \
			-D PYTHON2_PACKAGES_PATH=${HOME}/local/lib/python2.7/site-packages \
			-D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=ON \
			-D BUILD_EXAMPLES=ON \
			-D OPENCV_EXTRA_MODULES_PATH=${HOME}/Code/opencv_contrib/modules ..
	$ make -j4
	$ make install

And my Python path:

    $ echo $PYTHONPATH
    /Users/boltzmannbrain/local/lib/python2.7/site-packages:

**Comment by monajalal** [comment]
@BoltzmannBrain please check to see if following http://stackoverflow.com/a/38688201/2414957 answer would work for you. It doesn't work for me as I don't have python3.5 in that path. It tells about linking cv2.so file. 
```
ln -s /usr/local/Cellar/opencv3/3.1.0_3/lib/python3.4/site-packages/cv.py /usr/local/lib/python3.4/site-packages/cv.py

ln -s /usr/local/Cellar/opencv3/3.1.0_3/lib/python3.4/site-packages/cv2.so /usr/local/lib/python3.4/site-packages/cv2.so
```

**Comment by BoltzmannBrain** [comment]
Thanks for the suggestion but I did not install opencv with homebrew -- i.e., I don't have a `/usr/local/Cellar/opencv` directory. I did try the following link, but to no avail:

```
$ ln -s ${HOME}/local/lib/python2.7/site-packages/cv2.so /usr/local/lib/python2.7/site-packages/cv2.so
```

**Comment by tdsmith** [comment]
I'll unsubscribe from this thread (sorry!) but do check the `cmake` output to make sure python was configured correctly.

**Comment by BoltzmannBrain** [comment]
Got it! At least for me...

`export DYLD_LIBRARY_PATH=${HOME}/Code/opencv/build/lib:${DYLD_LIBRARY_PATH}`

**Comment by monajalal** [comment]
^ your solution didn't work for me:

```
bash-4.3$ export DYLD_LIBRARY_PATH=/Users/mona/computer_vision/Face_Recognition/opencv-3.1.0/build/lib:${DYLD_LIBRARY_PATH}
bash-4.3$ echo $DYLD_LIBRARY_PATH
/Users/mona/computer_vision/Face_Recognition/opencv-3.1.0/build/lib:
bash-4.3$ python
Python 3.5.2 (default, Jul 28 2016, 21:28:07)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
```

**Comment by StevenPuttemans** [comment]
Wow I find it weird that people are adding me to issues, without knowing my field of specialisation. Python is way out of my comfort zone and I have zero experience in building and linking it. Guess I cannot help you here.

Will unsubscribe also ...

**Comment by alalek** [comment]
I believe you should dig into this direction at first:
```
>>> import sys; print sys.path
```
(PYTHONPATH should control this)
