### ISSUE TITLE
libv4l2: error getting capabilities: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by thxmxx** [opencv/opencv#7051]
I'm trying to open a video

`
VideoCapture video_source;
video_source = VideoCapture();
video_source.open("/home/thom/Downloads/output.mp4");
`

and I'm getting this message:

> Failed to query video capabilities: Inappropriate ioctl for device
> libv4l2: error getting capabilities: Inappropriate ioctl for device
> VIDEOIO ERROR: V4L: device /home/thom/Downloads/output.mp4: Unable to query number of channels
> Could not open the stream file.

Any clue?

**Comment by alalek** [comment]
Try to check usage questions here: http://answers.opencv.org

**Comment by aapommedi** [comment]
I am also facing the same issue , please someone help.
Thanks in advance

**Comment by merryHunter** [comment]
I have the same problem on CentOS 7 , OpenCV 3.2.0.
I built with flag `-DWITH_LIBV4L=ON` as suggested here #6157 and in the output of cmake I have `using V4L/V4L2: YES ` , but result is the same.
At the OpenCV [http://answers.opencv.org/question/99659/videocapture-problem-inappropriate-ioctl-for-device/](website) website guys posted this issue.
Any ideas what is the problem?

**Comment by tuongngoc** [comment]
I have the same problem on Fedora 28, OpenCV3.4. I build with -DWITH_V4L=Yes and -DWITH_LIBV4L=yes.
Any ideas how to fix that?

**Comment by kapoor7997** [comment]
Anyone found the solution on this.
