### ISSUE TITLE
Commit 1ae9a5d causes cuda_runtime.h not found

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7052]
##### System information (version)
- OpenCV => Latest
- Operating System / Platform => Ubuntu 14.04
- Compiler => gcc 4.9.3
- CUDA => 7.5

##### Steps to reproduce

Write any code with the line

``````
#include "opencv2/opencv.hpp"
``````

git checkout 1ae9a5d

rebuild OpenCV with CUDA enabled

compile your code and you will see error something like 

``````
In file included from /usr/local/include/opencv2/cudalegacy.hpp:47:0,
                 from /usr/local/include/opencv2/opencv.hpp:78,
                 from /home/jason/repo/modules/test/include/jason/test/classA.h:8,
                 from /home/jason/repo/modules/test/src/classA.cpp:3:
/usr/local/include/opencv2/cudalegacy/NCV.hpp:52:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.
``````

cuda_runtime.h exists in my machine at 

``````
/usr/local/cuda-7.5/include/cuda_runtime.h
/usr/local/cuda/include/cuda_runtime.h
``````
cuda is a symlink folder to cuda-7.5

Now go back to OpenCV and 

git checkout 29afb83

rebuild OpenCV again with CUDA enabled

compile your code and it will work.

Would be great to see it fixed as I have to temporarily disable my cronjobs that periodically pull the latest change of OpenCV

**Comment by alalek** [comment]
Right, CUDA modules should not be included without correct compiler setup for CUDA SDK (for example, via `find_package(CUDA)` in CMake)

**Comment by StevenPuttemans** [comment]
@alalek it seems my fix broke this indeed! But as far as I understand what we did here, the cuda modules only get included once they are installed using the `opencv_modules.hpp` auto generated file. I would believe that the cuda modules would not get in if CMAKE was not able to find CUDA?

Not really sure that adding find_package(CUDA) would solve the problem here. I am guessing you are suggesting of changing lines like

`ifdef HAVE_OPENCV_CUDABGSEGM` 

to something like 

`ifdef HAVE_OPENCV_CUDABGSEGM &&  find_package(CUDA)`

**Comment by StevenPuttemans** [comment]
@mshabunin If you could give me a pointer at how to solve this, I be happily supplying the fix today!

**Comment by StevenPuttemans** [comment]
Actually I am debugging a bit around here, and in my honest opinion, adding my fix for another issue, just revealed a faulty issue here. Before the header was simply not included, but now that it is correctly included it is triggering the issue. 

Will dig deeper to see if I can come up with a fix!

**Comment by bernardelli** [comment]
I've got the same problem as @jasjuang. But I was able to build opencv removing the examples from the build. 

But after that, when I try to compile any code that includes opencv.hpp, I get the problem mentioned above.

I was able to find a horrible fix: comment out some includes inside opencv.hpp that are related to cuda.

Sorry for the noobness and I hope this helps fixing the problem.

**Comment by StevenPuttemans** [comment]
If you do not need CUDA, then the simplest solution is to build OpenCV without CUDA support, then the problem does not even occur (which I just validated again). Trying a temporarily solution now and will get back if it works!

**Comment by StevenPuttemans** [comment]
Ok so back to some further reporting

1) As I tought, it is basically NOT the fault of the includes, if OpenCV is built with CUDA, the includes should be there, if not it is verified to work as expected.

2) If you have built OpenCV with CUDA support, then ofcourse during the build of a sample, when using `include "opencv2/opencv.hpp` (which basically includes everything in your installation) then you have to point your building system (it either being an IDE or CMAKE or your manual gcc command) to where you installed CUDA and where it can find the library. This is the task of the user and can be done by adding `-I/usr/local/cuda/include/` to the compiler options. 

This should solve issues. Basically people need to be aware of what the inclusion of `opencv.hpp` does!

**Comment by StevenPuttemans** [comment]
Do correct me if I am wrong BTW! Solving some issues about different CUDA versions and will then see if I can confirm this is the fix.

**Comment by mshabunin** [comment]
@StevenPuttemans , let's remove all cuda modules from `opencv2/opencv.hpp` header.

**Comment by StevenPuttemans** [comment]
Hmm we can do that for now indeed. Maybe we should add a `opencv_cuda.hpp` header to supply for this need?

**Comment by bernardelli** [comment]
I just realized I had a typo in my makefile. 

Now I am actually adding the cuda includes, but the compilation fails when it finds some cuda code on the way (although I am not using any cuda modules yet). 

[compilelog.txt](https://github.com/opencv/opencv/files/406567/compilelog.txt)

**Comment by StevenPuttemans** [comment]
Yeah I do get the same input now. As seen in the PR for now we removed the modules, but I should get a deeper look in getting the CUDA modules back to running properly again when I find the time!
