### ISSUE TITLE
miss spelt identifier in documentation

### ISSUE THREAD

**Issue by PeteBlackerThe3rd** [opencv/opencv#7053]
##### System information (version)
N/A
Error in online documentation

##### Detailed description

The documentation page at:
http://docs.opencv.org/2.4/modules/features2d/doc/common_interfaces_of_feature_detectors.html#featuredetector-create

Has an error in the note at the end of the section.
The second bullet point reads "Add an initialisation function at the start of your code: initModules_nonfree();"
The identifier should does not contain an 's' it should read "initModule_nonfree();"

I had to dig into the header files to figure my way through this one.

##### Steps to reproduce

Goto : http://docs.opencv.org/2.4/modules/features2d/doc/common_interfaces_of_feature_detectors.html#featuredetector-create
Read section on FeatureDetector::create
Observe typo in note at the end of this section.

**Comment by StevenPuttemans** [comment]
Fix submitted! Thanks for the report!
