### ISSUE TITLE
calcOpticalFlowPyrLK returning points out of the camera frame

### ISSUE THREAD

**Issue by BoltzmannBrain** [opencv/opencv#7054]
Running a 480x640 video through [the Lucas-Kanade optical flow tracker example](https://github.com/opencv/opencv/blob/master/samples/python/lk_track.py), I'm getting some tracked points that are beyond the camera frame, like negative x and y coordinates. How is this possible? Is this a bug?

I posted this to both [the opencv questions page](http://answers.opencv.org/question/99586/calcopticalflowpyrlk-returning-points-out-of-the-camera-frame/) and [SO](http://stackoverflow.com/questions/38780752/opencv-python-calcopticalflowpyrlk-returning-points-out-of-the-camera-frame), but have gotten no help.

**Comment by alalek** [comment]
It is possible and not a bug. There is `status` vector for valid/"lost" keypoints.

**Comment by BoltzmannBrain** [comment]
Thank you for the speedy response. So just to confirm my understanding, the output coordinates of feature points are a "prediction" of where they'll be?

**Comment by alalek** [comment]
Right. With preserving of "indexing" from input keypoints.

**Comment by BoltzmannBrain** [comment]
Great, thanks!
