### ISSUE TITLE
Cholesky function in opencv without HAL

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#7063]
- OpenCV => 3.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2013

Hi,

I want to have cholesky decomposition of a matrix. In opencv doc is [here ](http://docs.opencv.org/3.1.0/db/de0/group__core__utils.html#gac8d860b8a49bf2ed304b1c82acb916e5)and I think this [doc ](http://docs.opencv.org/master/d8/d0e/group__core__hal__interface__decomp__cholesky.html#gsc.tab=0)is still good. In following program I try to have cholesky decomposition of matrix A 

```
    #include <opencv2/opencv.hpp>
    #include <iostream>
    
    using namespace cv;
    using namespace std;
    
    
    int main (int argc,char **argv)
    {
    
        Mat m1=(Mat_<double>(3,3) << 4,12,-16,12,37,-43,-16,-43,98);
        
        cout<<m1<<endl;
        Cholesky ((double*)m1.ptr(),m1.cols*8, 3,NULL, 0, 0);
        m1.at<double>(0,1)=0;m1.at<double>(0,2)=0;m1.at<double>(1,2)=0;
        cout<<"L = "<<m1<<endl;
        cout<<"L' = "<<m1.t()<<endl;
        cout << "LL'="<<m1*m1.t()<<endl;
    }

```

LL' should be m (m1 is an axample in [wikipedia](https://en.wikipedia.org/wiki/Cholesky_decomposition#cite_note-4)). Something is strange.  In this [post ](http://answers.opencv.org/question/99704/cholesky-function-in-opencv/) Eduardo give a link to a static cholesky function in opencv which gives a good result

I think two lines are missing in [source code](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_decomp.cpp#L155) 
```
for( i = 0; i < m; i++ )
    L[i*astep + i]=1/L[i*astep + i];

```

**Comment by mshabunin** [comment]
Why do you calculate `step` as `m1.cols*8`? Try `m1.step` instead.

**Comment by LaurentBerger** [comment]
because it is undocumented in [opencv doc](http://docs.opencv.org/3.1.0/db/de0/group__core__utils.html#gac8d860b8a49bf2ed304b1c82acb916e5&gsc.tab=0 so follow [this](http://docs.opencv.org/master/d8/d0e/group__core__hal__interface__decomp__cholesky.html#gsc.tab=0).

It is used [here ](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/operations.hpp#L75)too
I have try m1.step and it gives 
```
A=[4, 12, -16;
 12, 37, -43;
 -16, -43, 98]
2       0       0       6       1       0       -8      5       3
L = [0.0625, 0, 0;
 12, 37, 0;
 -16, -43, 98]
L' = [0.0625, 12, -16;
 0, 37, -43;
 0, 0, 98]
LL'=[0.00390625, 0.75, -1;
 0.75, 1513, -1783;
 -1, -1783, 11709] <> A
A=[4, 12, -16;
 12, 37, -43;
 -16, -43, 98]
L = [0.0625, 0, 0;
 12, 37, 0;
 -16, -43, 98]
L' = [0.0625, 12, -16;
 0, 37, -43;
 0, 0, 98]
LL'=[0.00390625, 0.75, -1;
 0.75, 1513, -1783;
 -1, -1783, 11709] <> A
```

Now I think my program is good because if you add two lines proposed Cholesky decomposition is good.  My question is : Is there is a reason to delete thoses lines?

**Comment by sovrasov** [comment]
Actually it's better to calculate 'step' as 'm1.step' and HAL documentation is wrong. In case if m1 is ROI it makes a sense.
@LaurentBerger your fix is OK for obtaining proper of L matrix but solution of linear system (if non-zero pointer b passed) will probably be wrong.
So more suitable to put your code into [L156](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_decomp.cpp#L156) in after 'if( !b )' and [L196](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_decomp.cpp#L196) or you can keep your current changes and modify solver in L175-L195.

Can you propose pull request with your changes?

**Comment by LaurentBerger** [comment]
@sovrasov
Something like this :

```
    for( i = 0; i < m; i++ )
    {
        for( j = 0; j < i; j++ )
        {
            s = A[i*astep + j];
            for( k = 0; k < j; k++ )
                s -= L[i*astep + k]*L[j*astep + k];
            L[i*astep + j] = (_Tp)(s*L[j*astep + j]);
        }
        s = A[i*astep + i];
        for( k = 0; k < j; k++ )
        {
            double t = L[i*astep + k];
            s -= t*t;
        }
        if( s < std::numeric_limits<_Tp>::epsilon() )
            return false;
        L[i*astep + i] = (_Tp)(1./std::sqrt(s));
    }

    if( !b )
    {
        for( i = 0; i < m; i++ )
             L[i*astep + i]=1/L[i*astep + i];
        return true;
   }
    // LLt x = b
    // 1: L y = b
    // 2. Lt x = y

    /*
     [ L00             ]  y0   b0
     [ L10 L11         ]  y1 = b1
     [ L20 L21 L22     ]  y2   b2
     [ L30 L31 L32 L33 ]  y3   b3

     [ L00 L10 L20 L30 ]  x0   y0
     [     L11 L21 L31 ]  x1 = y1
     [         L22 L32 ]  x2   y2
     [             L33 ]  x3   y3
     */

    for( i = 0; i < m; i++ )
    {
        for( j = 0; j < n; j++ )
        {
            s = b[i*bstep + j];
            for( k = 0; k < i; k++ )
                s -= L[i*astep + k]*b[k*bstep + j];
            b[i*bstep + j] = (_Tp)(s*L[i*astep + i]);
        }
    }

    for( i = m-1; i >= 0; i-- )
    {
        for( j = 0; j < n; j++ )
        {
            s = b[i*bstep + j];
            for( k = m-1; k > i; k-- )
                s -= L[k*astep + i]*b[k*bstep + j];
            b[i*bstep + j] = (_Tp)(s*L[i*astep + i]);
        }
    }
        for( i = 0; i < m; i++ )
             L[i*astep + i]=1/L[i*astep + i];
return true;
```

**Comment by sovrasov** [comment]
@LaurentBerger exactly

**Comment by zlobber** [comment]
https://www.youtube.com/watch?v=cqRW5-xzL-s
