### ISSUE TITLE
Add support for Visual Sutdio 2015 Update 3

### ISSUE THREAD

**Issue by daB0bby** [opencv/opencv#7080]
I receive an error during compilation with Visual Studio 2015 Update 3

Following error:
`C1189	#error:  Microsoft Visual Studio 2015 Update >= 2 is not supported yet!`

**Comment by alalek** [comment]
Please add more details:
- file name?
- CUDA on/off?

**Comment by daB0bby** [comment]
File: `host_config.h` 
Line: 137

Yes, CUDA is enabled. I'm Using CUDA 8.0

So it seems to be an error on CUDA side. 😁
