### ISSUE TITLE
Invalid GStreamer error for frame sequences (image%d.jpg)

### ISSUE THREAD

**Issue by dashesy** [opencv/opencv#7081]
- OpenCV 3.1.0
- Operating System / Platform => Ubuntu 64 Bit

When using VideoCapture, on [this line](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_gstreamer.cpp#L617) OpenCV checks if a path such as `frame%d.jpg` is valid, and prints error even though it is valid.

 It works, but gives an error!

**Comment by ilya-lavrenov** [comment]
@dashesy, could you provide a simple piece of code to reproduce the issue? Is the issue reproducible if you use `frame%02d.jpg` with explicit number of digits?

**Comment by dashesy** [comment]
Thanks for your help!

My bad! In fact it is `frame%1d.jpg` and I get the error. There are only 5 frames so I did not need to use `%2d`.

**Comment by dashesy** [comment]
Also, if the application is linked with GStreamer, I get this error:

> GStreamer Plugin: Embedded video playback halted; module typefind reported: Stream contains no data.
OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
) in cvCaptureFromCAM_GStreamer, file /home/ehazar/development/Ambient-Coordination/src/opensource/OpenCV/3.1.0/sources/modules/videoio/src/cap_gstreamer.cpp, line 818


Is `frame%1d.jpg` a supported input?
