### ISSUE TITLE
enum in stitching.hpp collided with X11 macro 

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7113]
##### System information (version)
- OpenCV => Latest
- Operating System / Platform => Ubuntu 14.04 LTS
- Compiler => GCC 4.9.3

##### Detailed description
The recent change of including stitching.hpp inside opencv.hpp is causing conflicts with X11 which results in compilation error.

##### Steps to reproduce
Write any code with the lines of 

``````
#include "X11/Xlib.h"
#include "opencv2/opencv.hpp"
``````

there will be compilation error

``````
/usr/local/include/opencv2/stitching.hpp:100:10: error: expected identifier before ‘int’
     enum Status
          ^
In file included from /usr/local/include/opencv2/opencv.hpp:86:0,
``````

the root cause is the below code in Xlib.h

``````
#define Status int
``````

It's a horrible macro but Xlib is too old to change and it's already by default in all Ubuntu distributions. Would OpenCV be willing to accommodate by changing enum Status into some other name in stitching.hpp to avoid this collision so I can use Xlib in conjunction with OpenCV for my graphics application?

**Comment by alalek** [comment]
Thanks for report and investigation of problem!

Unfortunately I have no good idea how to fix this right in OpenCV (#undef Status is not very good).

I believe workaround for this problem is possible by by including OpenCV headers before Xlib.h in application code.

P.S. Possibly related: #7038

**Comment by mshabunin** [comment]
We can add macro check with problem explanation like [here](https://github.com/opencv/opencv/pull/6161/commits/3cc234588abc3064cf0d5d3113d9bbb75b6a54cf).

**Comment by jasjuang** [comment]
@mshabunin great suggestion and it might be easier. I was thinking about renaming the enum variable "Status" to something different like perhaps "status".

**Comment by alalek** [comment]
Lets start to fix with "check macro" from @mshabunin comment above.

**Comment by souch55** [comment]
Hi mshabunin this was an easy feature change i have done it,please review my changes and merge it. PR # https://github.com/opencv/opencv/pull/7148

**Comment by AlejandroColomar** [comment]
Not solved on Ubuntu 18.04 LTS

**Comment by brightprogrammer** [comment]
I got that corrected by including opencv headers before X11 headers but then it is throwing some error on  undefined reference to XGetImage [ A functiont that I am using in  my screen capture program ]

**Comment by sjianfei** [comment]
comment in the opencv_modules.hpp with //#define HAVE_OPENCV_STITCHING

**Comment by Unarmed1000** [comment]
Could we get a proper fix for this!

While I agree that the X11 header is the issue, but thats not likely to be changed any time soon. So the correct solution for this issue is not to require all source to change their include ordering, but probably to fix your code to work around the issue. Yes I know that's not great but welcome to popular legacy software.

Many modern projects embrace clang format which can auto sort the includes. 
Something your requirement breaks.
