### ISSUE TITLE
UIImageToMat for UIImage with alpha creates Mat with garbage in clear pixels.

### ISSUE THREAD

**Issue by haikusw** [opencv/opencv#7121]
OpenCV => 3.1
Operating System / Platform => iOS 64 bit
Compiler => Xcode 7.3.1

UIImageToMat ends up with random memory values in background of UIImage with alpha.

##### Steps to reproduce

Use a UIImage created from a png with an alpha channel.  Create a Mat for it with UIImageToMat.  Use MatToUIImage and then draw the image. 

```
- (UIImage*) imageMethod: (UIImage*) inputImage
{
	CGImageAlphaInfo ainfo = CGImageGetAlphaInfo( inputImage.CGImage );
        
       cv::Mat image;  // or cv:Mat image = cv:Mat();
![bug3](https://cloud.githubusercontent.com/assets/222271/17720463/e8dbd61a-63d6-11e6-8768-7534d0ee60a4.png)

	UIImageToMat( inputImage, image, ainfo != kCGImageAlphaNone );
	return MatToUIImage( image );
}
```

calling code in an iOS project with an onscreen UIImageView into which to place the result

```
UIImage * anImage = [UIImage imageNamed: "test.png"];
UIImage * resultImage = [self imageMethod: anImage];

// put resultImage into an onscreen UIImageView to see it ugly
```

Source Image:

![bug](https://cloud.githubusercontent.com/assets/222271/17720302/a174b478-63d5-11e6-9c09-f5baf9b380a3.png)

Resulting image before fix varies quite a bit (ignore rotation - that's done after the above code for unrelated reasons):

![bug2](https://cloud.githubusercontent.com/assets/222271/17720464/ef26022a-63d6-11e6-8dc7-c9b313704c94.png)

after the fix:

![bug3](https://cloud.githubusercontent.com/assets/222271/17720465/f38ce63a-63d6-11e6-83e0-23f40add38af.png)

A fix is to just initialize the Mat values with 0, as in the PR submitting next.

**Comment by StevenPuttemans** [comment]
:+1:  thank you for the fix provided!

**Comment by fukemy** [comment]
I can not fullPoly with alpha channel from image with UIImageToMat. Can you help? here is my question in [https://stackoverflow.com/questions/51872759/ios-opencv-can-not-fillconvexpoly-with-alpha](stackoverflow)
