### ISSUE TITLE
Local HTML and PDF doc building no longer seem to work

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv#7123]
Just wondering if there is a reason why the commands

```
make docs
make html_docs
```

are no longer supported. It makes it hard to verify pull request with documentational changes, and forces user to debug using the provided pullrequest/buildbot system.

**Comment by hrnr** [comment]
What about:

```
make doxygen
```

I using it for my changes. It even works under ninja as:

```
ninja doxygen
```

**Comment by StevenPuttemans** [comment]
hmmm make doxygen seems to do stuff :+1:  will report back with the result!

**Comment by StevenPuttemans** [comment]
It seems to have done the trick on Ubuntu14.04.

```
make doxygen
firefox doc/html/index.html
```

pops up the docs! Maybe we should somewhere document this behaviour? @alalek any idea where this should be placed?

**Comment by alalek** [comment]
Both
```
make docs
make html_docs
``
are deprecated for master branch.

"make doxygen" is documented here: http://docs.opencv.org/master/d4/db1/tutorial_documentation.html#gsc.tab=0

**Comment by StevenPuttemans** [comment]
Ok thanks for the info. Weird that a google on 'build OpenCV documentation' does not get me to that page...

**Comment by yourtheron** [comment]
@alalek If they have been deprecated, the change'd better be reflected on the [online build doc](https://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html#windows-installation). I was also confused after reading and trying it
