### ISSUE TITLE
Mentor needed

### ISSUE THREAD

**Issue by Asalle** [opencv/opencv#7134]
Hi all,

I talked to a bunch of people at #opencv on irc channel and they told me, that I could create an issue to ask devs directly. If it's a bad practice, I'm genuinely sorry. 

I am a newbie in OpenCV, but I'm willing to participate. I am looking for a mentor.

Who I am:
Software engineering B. Sc.
Junior C++ dev at a local company
Done Outreachy with X.org in 2014
Proficient python, git and linux

What I've done:
Pull request #7132 on issue #6944 (a very basic one, still building)
Built and installed opencv locally, ready to use
Looked for a suitable bug in the issues page, no success (I'm not able to distinguish hard ones from easy ones so far)

Who I am looking for:
A mentor with little free time on weekends or during the week, I work at a full-time job, so I will be able to contribute, but very slowly
Somebody, who will just tell me, which bug can a newbie handle, minimum effort required

Other ideas:
I was thinking about completing some not so complicated GSoC task, that nobody had chosen this year. Are there some free GSoC mentors around, maybe?

I hope this is the right place to ask, if it's not: sorry and would you be so kind to tell me, where the right place is?

Looking forward to your response,
Asalle

**Comment by StevenPuttemans** [comment]
Welcome to the contributing club! I am not able with help on the GSoC topics but if you need any help figuring something out, or fixing something, you can always give me a ping!

On Github through @StevenPuttemans
On OpenCV Q&A by adding @StevenPuttemans in your comment or question
Or if I am available on the freenode channel

I am not sure if a core dev will have time to follow up on you since they quite busy, but lets await their response!

**Comment by anirudt** [comment]
Hi,

I am also looking for a mentor for helping out to fix bugs. Considering the massiveness of the architecture, it would be great to have a mentor to lend expertise and provide pointers for the same. As @Asalle pointed out, it is quite difficult to distinguish between hard and easy bugs, so it would be great to have a little chat and understand what could be done.

Looking forward to hearing from you,

With Best Regards
Anirud T

**Comment by StevenPuttemans** [comment]
@anirudt hi there and also thank you for the enthousiasm. I guess @Asalle already discovered that even though she did not get a specific mentor assigned, getting help during the PR process is quite straightforward for the community. I guess you simply need to ask the question when an error arises. 

As to finding out easy and less difficult issues, when browsing the issue page, you can simply select labels at the top right. There are several issues having the `easy`, `normal` label, which are cases that most of the times have a solution provided already but just need to be added. Furthermore the `category:documentation` label presents issues that are basically adding documentation of existing functionality and are thus easy starters to get the hang of Git and contributing.

But again, if you need help, do not hesitate to ask!
