### ISSUE TITLE
Bounding Box tutorial missing explanation

### ISSUE THREAD

**Issue by lrperlmu** [opencv/opencv#7136]
[This tutorial](http://docs.opencv.org/2.4/doc/tutorials/imgproc/shapedescriptors/bounding_rects_circles/bounding_rects_circles.html) is missing an explanation.

Note: I'm not sure if this is the right channel to report this issue, but this is how I decided to report it here: At the bottom of [the tutorial](http://docs.opencv.org/2.4/doc/tutorials/imgproc/shapedescriptors/bounding_rects_circles/bounding_rects_circles.html), the Help and Feedback section says to file a bug report if something is missing or wrong in the documentation. "Bug report" links [here](http://code.opencv.org/projects/opencv/wiki), so I followed the link to the github and found the "issues" section, and created this Issue. Please let me know if I'm reporting it correctly or not!

**Comment by Asalle** [comment]
I will try to fix it

**Comment by mshabunin** [comment]
Corresponding tutorial from _master_: http://docs.opencv.org/master/de/d62/tutorial_bounding_rotated_ellipses.html

**Comment by Asalle** [comment]
I made pull request to master, should I do another one to 2.4?

**Comment by mshabunin** [comment]
@Asalle , let's wait until master PR is integrated.

Doxygen uses several extensions to the original markdown: https://www.stack.nl/~dimitri/doxygen/manual/markdown.html . I doubt that some tool supports them.
