### ISSUE TITLE
bg_sub.cpp

### ISSUE THREAD

**Issue by locka-hd** [opencv/opencv#7137]
Hello 
I cant build bg_sub.cpp
i try with cmake also 

`https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/video/bg_sub.cpp`
Pls any one can check if its the code correct

**Comment by alalek** [comment]
There is no problem with this sample build on [our test infrastructure](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV-lin64/builds/805/steps/compile%20release/logs/stdio).

Additional help about how to use OpenCV please ask on User Q/A forum: http://answers.opencv.org
