### ISSUE TITLE
error build in vs2010

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#7143]
Version: 3.1.0-1195-gbf4c5be
Error on build only in Visual Studio 2010:
..\..\..\sources\opencv\modules\videoio\src\cap_ffmpeg.cpp(70): error C2039: 'GetModuleHandleEx' : is not a member of '`global namespace''
1>..\..\..\sources\opencv\modules\videoio\src\cap_ffmpeg.cpp(70): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS' : undeclared identifier
1>..\..\..\sources\opencv\modules\videoio\src\cap_ffmpeg.cpp(70): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT' : undeclared identifier
1>..\..\..\sources\opencv\modules\videoio\src\cap_ffmpeg.cpp(70): error C3861: 'GetModuleHandleEx': identifier not found

**Comment by throwaway2017** [comment]
Had a similar issue. As a temporary fix i followed [http://stackoverflow.com/a/4601432](stackoverflow answer) and tweaked define in opencv\modules\videoio\src\precomp.hpp 
from
` #define _WIN32_WINNT 0x0500 `
to
`  #define _WIN32_WINNT 0x0501 `

**Comment by alalek** [comment]
@Bleach665 Could you try to build with this CMake parameter:
```
cmake -DOPENCV_EXTRA_FLAGS="/D_WIN32_WINNT=0x0501" ...
```

**Comment by Bleach665** [comment]
@alalek. flag
`-DOPENCV_EXTRA_FLAGS="/D_WIN32_WINNT=0x0501"`
fix this bug.

**Comment by pablolq** [comment]
Same issue, error on build with Visual Studio 2017. 
core/src/utils/datafile.cpp  doesn't build for UWP (Windows Store 10.0 x64)
Error	C2039	'GetModuleHandleEx': no es un miembro de '`global namespace''	opencv_world
Error	C2065	'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS': identificador no declarado opencv_world
![opencvvs2017error](https://user-images.githubusercontent.com/17787020/52661967-d72e8d80-2ec8-11e9-8c33-f18595f6c529.PNG)

**Comment by JosueLC** [comment]
Is it possible that the solution is to add a condition to the precompiler?
I tested with !WINRT_STORE and it worked.

[cid:image002.png@01D4CF33.75FEC6A0]

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Pablo López Quiles<mailto:notifications@github.com>
Enviado: martes, 12 de febrero de 2019 14:20
Para: opencv/opencv<mailto:opencv@noreply.github.com>
CC: JosueLC<mailto:josueflopez@msn.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [opencv/opencv] error build in vs2010 (#7143)


Same issue, error on build with Visual Studio 2017.
core/src/utils/datafile.cpp doesn't build for UWP (Windows Store 10.0 x64)
Error C2039 'GetModuleHandleEx': no es un miembro de '`global namespace'' opencv_world
Error C2065 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS': identificador no declarado opencv_world
[opencvvs2017error]<https://user-images.githubusercontent.com/17787020/52661967-d72e8d80-2ec8-11e9-8c33-f18595f6c529.PNG>
