### ISSUE TITLE
Feature Detection Tutorial outdated

### ISSUE THREAD

**Issue by sgasparini** [opencv/opencv#7151]
##### System information (version)
N/A
##### Detailed description

the tutorial one feature detection is outdated. 

It is simply not compiling with opencv 3
http://docs.opencv.org/2.4/doc/tutorials/features2d/feature_detection/feature_detection.html#feature-detection

Even once the include path fixed (replacing #include "opencv2/nonfree/nonfree.hpp" by #include "opencv2/xfeatures2d.hpp") after having get openCV_contrib, it still not compile.

A replacement code can be found on github,(https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/samples/surf_matcher.cpp)
however this code simply don't work

When executions this code you only get help. The reason is that the keys constant is not properly initialized and thus falling into help always (testes on OS X 10.11 and OpenCV 3.1 + contrib).

changing keys value to 
    const char* keys =
    "{h help     |                  | print help message  }"
    "{l left     | box.png          | specify left image  }"
    "{r right    | box_in_scene.png | specify right image }"
    "{o output   | SURF_output.jpg  | specify output save path }"
    "{m cpu_mode |                  | run without OpenCL }";

make the code working.

I still need to figure out if this code is working after that as so far it does not really seems to be working.
I would loved to get the image used on the tutorials pages to confirm that the code example is at least working with that.

##### Steps to reproduce

Just try to compile this code provided on tutorial with latest openCV

**Comment by berak** [comment]
1. please do **not** use opencv2.4 docs/examples with opencv3 codebase. too much has changed.
2. there was a long [discussion, how to represent boolean values in the CommandLineParser](https://github.com/opencv/opencv/pull/5329) , somehow, that sample was never updated, thanks for the report !

**Comment by sgasparini** [comment]
1. All the tutorials in 2D features framework are said compatible with opencv > 2.0. 
http://docs.opencv.org/2.4/doc/tutorials/features2d/table_of_content_features2d/table_of_content_features2d.html#table-of-content-feature2d
I suggest to update the tutorial page to tell those tutorials are not compatible with openCV 3



--
Stéphane Gasparini
