### ISSUE TITLE
opencv 3.1.0 svm load problem

### ISSUE THREAD

**Issue by lonewolf9277** [opencv/opencv#7173]
##### System information (version)

- OpenCV => :3.1.0:
- Operating System / Platform => :Ubuntu 64bit:

##### Detailed description

The load function for svm is missing in opencv 3.1.0. I'm using python 2.7

**Comment by berak** [comment]
no, not a bug, you only missed it:

```
>>> help(cv2.ml)
(...)
    SVM_create(...)
        SVM_create() -> retval
    SVM_load(...)
        SVM_load(filepath) -> retval
```
note, that this returns a new svm instance, so call it like:

    svm =  cv2.ml.SVM_load("prev.xml")

**Comment by alalek** [comment]
@berak Thank you!

This patch (#5922) is introduced after 3.1.0 release, so you need to use current master or wait for next release.

**Comment by lonewolf9277** [comment]
Ok thanks. When is the next release?

**Comment by lonewolf9277** [comment]
I can't find that function even though I downloaded and installed it again
