### ISSUE TITLE
IplImage member imageSize is int instead of size_t limits to 2GB

### ISSUE THREAD

**Issue by moellney-IGI** [opencv/opencv#7176]
##### System information (version)

- OpenCV => 2.4.13 , 3.1.0
- Operating System / Platform => Windows 7 / x64
- Compiler => Visual Studio 2010

##### Detailed description

In my software I have to process rather large images. E.g. I would like to combine 4 channels, each 16bit to one image with width: 24400 and hight 11396. The resulting image size in bytes is:
24400 x 11396 x 2(16bit) x 4(channels) = 2224499200

In binary notation this is 
10000100.10010111.00101010.00000000

As you can see the size is larger than 2^31
But: the member imageSize in IplImage is declard as int!
The debugger shows this value as:
-2070468096 (int)

At http://en.cppreference.com/w/cpp/language/types you can see, that win64 API has 32bit for int.

64 bit systems:

        LLP64 or 4/4/8 (int and long are 32-bit, pointer is 64-bit) 
            Win64 API 

        LP64 or 4/8/8 (int is 32-bit, long and pointer are 64-bit) 
            Unix and Unix-like systems (Linux, Mac OS X) 

The imageSize is later used in cvCreateData(CvArr* arr)
in the call 
`img->imageData = img->imageDataOrigin = (char*)cvAlloc( (size_t)img->imageSize );`

But the type cast seems to disturb the size parameter, as the value is shown as
18,446,744,071,639,083,520 (unsigned int64)
int the debugger.

This is way to large for my 32 GB Machine ...

I think, for imageSize, this is a wrong declaration, as imageSize describe the size of the image in RAM. For this the C type size_t should be used.
http://www.cplusplus.com/reference/cstring/size_t/

##### Steps to reproduce

On Windows 7 x64

cvCreateImage(CvSize(24400,11396 ), 16, 4);

**Comment by alalek** [comment]
`IplImage` is deprecated and not supported anymore (like the most part of C-like "cv" functions).
There is no way to fix it with preserving binary compatibility (ABI).
