### ISSUE TITLE
Different results of CascadeClassifier on different computers

### ISSUE THREAD

**Issue by wr00bel** [opencv/opencv#7189]
##### System information (version)

- OpenCV => 3.1 64-bit
- Operating System / Platform => Windows 7 64-bit, Intel Core2 Quad Q9400, RAM 8 GB (works)
- Operating System / Platform => Windows 7 64-bit, Intel Core i7-4790S, RAM 16GM (DOESN'T work)
- Compiler => Visual Studio 2015

##### Detailed description

I'm using CascadeClassifier to detect some objects - and form one computer type to another computer type detection results are different (note that aplication and images are the same on both PCs)... And what is strange on computer on which detection doesn't work I've run application using OpenCV library in version 2.4 and detection was correct. It there some issue in OpenCV 3.1 ??

##### Steps to reproduce

This is my detection implementation:
```.cpp
	classifier.detectMultiScale(*frameImage->getOpenCVPtr(),
		foundObjects,
		1.04,
		10,
		0 | CV_HAAR_SCALE_IMAGE,
		cv::Size(90, 100),	
		cv::Size(200, 220));
```

**Comment by alalek** [comment]
OpenCV can offload some calculations on GPU via OpenCL API. Try to disable it (via `OPENCV_OPENCL_DEVICE=disabled` environment variable) and check again.

**Comment by wr00bel** [comment]
I've added mentioned environment variable and in my opinion detection is even worst. The result is similar to that in which I've add/set encoding on _utf-8_ in XML file.

**Comment by StevenPuttemans** [comment]
Can you provide more info on the data and model used?

- We could use a test sample to run tests on
- We could use the model to run tests
- Also please provide info on what feature backend you used, training parameter, ...

Then I am happy to dig into the problem with you.

**Comment by StevenPuttemans** [comment]
Some initial remarks

- Are you sure you used HAAR wavelets instead of LBP features to train the model? If not `CV_HAAR_SCALE_IMAGE` has to go because it will do things with you model that do not work.
- The lower and upper scale bound have a different ratio. The lower has a ratio of `1.11111111...` while the upper has a ratio of `1.1`. Normally scales are a multiplication or division of the original [w x h] dimensions. So it is weird that they are not in a similar dimension. Different ratios can lead to different levels in the scale pyramid and thus different results.

**Comment by wr00bel** [comment]
This is recognition of zoomed In eye - this are specific data, so I don't think You have that kind of data. But still I can send You whole XML file (attached to this post)
[ADClassifier.zip](https://github.com/opencv/opencv/files/442414/ADClassifier.zip)

**Comment by StevenPuttemans** [comment]
Hmm I still find this very strange. Can you clean both systems, download the latest OpenCV branch, run CMAKE and post output of both systems? There must be something different.

**Comment by wr00bel** [comment]
What do You mean clean systems ?? I've dowloaded OpenCV 3.1 on february 2016

**Comment by StevenPuttemans** [comment]
I mean, it is possible that on one of both systems, somewhere there are residues from old installations. With clean installations I mean your purged your system of everything related to OpenCV.

**Comment by wr00bel** [comment]
The 'problematic' PC is clean... so maby something must be added... Also I'll check last OpenCV branch

**Comment by wr00bel** [comment]
OK, I rebuilded OpenCV with the same version of VC redist which was installed on 'problematic' PC and nothing... But I gave one more chance to _alalek_ solution and it's work - probably at the first try someting goes wrong with adding mentioned system variable...

I've one more question: all future projects should be develop with or without using GPU? If GPU should be used so how can I force computer to use it (to disable I've known the trick) ?

**Comment by mshabunin** [comment]
@wr00bel , you can find some details in the documentation: http://docs.opencv.org/2.4/modules/ocl/doc/introduction.html
In short: you have to build OpenCV with OpenCL support (done by default) and install correct OpenCL driver/runtime on target PC.

**Comment by StevenPuttemans** [comment]
@mshabunin is it correct to state then that due to OpenCL, which offloads calculations to the GPU, but probably because both systems have a different GPU card with different configuration, that the calculations differ? If so, this behaviour should be better documented in my opinion!

**Comment by wr00bel** [comment]
OK, thanks for help

**Comment by mshabunin** [comment]
@StevenPuttemans , it can be either of these. However I think that possible difference between GPUs do not play big role in this case since they should conform to OpenCL standard.
