### ISSUE TITLE
Scaled and negative values after cv2.resize with float32 images and INTER_CUBIC

### ISSUE THREAD

**Issue by ASchaffland** [opencv/opencv#7195]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Arch Linux x86_64
- Compiler => gcc 6.1.1  / Python 2.7
##### Detailed description

When trying to resize an float32 image with cv2.resize using INTER_CUBIC as interpolation method, the values of the image are changed and become negative. Normalizing the image before makes no difference. Choosing INTER_LINEAR as interpolation method works fine.

Running the minimal code below yields:

> before scaling
> 255.0
> 0.0
> (431, 640, 3)
> float32
> after scaling with intercubic
> 296.479
> -42.4806
> (862, 1280, 3)
> after scaling with interlinear
> 255.0
> 0.0
> (862, 1280, 3)
##### Steps to reproduce

``` .py
import numpy as np
import cv2

img = cv2.imread("Turtle Tower1.jpg")
img = np.float32(img)
#img = cv2.normalize(img, 0, 1, cv2.NORM_MINMAX)

print("before scaling")
print(np.max(img))
print(np.min(img))
print(img.shape)
print(img.dtype)
print

scale_factor = 2

img_resized1 = cv2.resize(img, dsize=(0,0), fx=scale_factor, fy=scale_factor, interpolation=cv2.INTER_CUBIC)

print("after scaling with intercubic")
print(np.max(img_resized1))
print(np.min(img_resized1))
print(img_resized1.shape)
print

img_resized2 = cv2.resize(img, dsize=(0,0), fx=scale_factor, fy=scale_factor, interpolation=cv2.INTER_LINEAR)

print("after scaling with interlinear")
print(np.max(img_resized2))
print(np.min(img_resized2))
print(img_resized2.shape)
```

**Comment by joeyearsley** [comment]
This still occurs in OpenCV 3.2

**Comment by alalek** [comment]
Not a bug.

CUBIC [interpolation](https://en.wikipedia.org/wiki/Interpolation#Polynomial_interpolation) may provide values that are outside the range of the initial values.

Use "clamp"-like operation for floating-point images.
