### ISSUE TITLE
T-API introduction has not been added to master

### ISSUE THREAD

**Issue by mshabunin** [opencv/opencv#7197]
##### Detailed description

There is no page in master documentation with general information about OpenCL (T-API). Corresponding 2.4 page: http://docs.opencv.org/2.4/modules/ocl/doc/introduction.html

Some data structures and utility functions can be documented too using information from 2.4 docs: http://docs.opencv.org/2.4/modules/ocl/doc/ocl.html

**Comment by ankitaggarwal011** [comment]
@mshabunin, I would like to start contributing to OpenCV with this issue. As I understand, (OpenCL module)[https://github.com/opencv/opencv/tree/master/modules/core/include/opencv2/core] is part of core module in OpenCV 3.0+, compared to being a (separate module)[https://github.com/opencv/opencv/tree/2.4/modules/ocl] in OpenCV 2.4+ and there might be certain changes in its T-API going from 2.4 to 3.0.

Thus the corresponding documentation for OpenCL module in OpenCV 3.0+ has to be changed accordingly while using information from 2.4 documentation. Now, I've not worked a lot on the OpenCL module myself. Please let me know if this is right way to approach this issue. Thanks.

**Comment by mshabunin** [comment]
@ankitaggarwal011 , yes it should become a part of _core_ module documentation (http://docs.opencv.org/master/dc/d83/group__core__opencl.html) and should introduce T-API to users. You can use information related to T-API from http://opencv.org/platforms/opencl.html and some parts from http://docs.opencv.org/2.4/modules/ocl/doc/introduction.html.

If introduction will be small (3-5 sections of text), then it can be placed to the _Detailed Description_ part (in [this](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/ocl.hpp) file), otherwise separate page should be created (in [this](https://github.com/opencv/opencv/tree/master/modules/core/doc) folder) and referred from the description. You can insert code snippets (use `@snippet` doxygen command) from cpp code samples and corresponding tapi samples to illustrate differences.
As I can see, some functions are actually documented but with wrong formatting:
```.cpp
/*
//! @brief Convert OpenCL image2d_t to UMat
//
//! @note Note:
//   OpenCL image2d_t (cl_mem_image), should be compatible with OpenCV
//   UMat formats.
//   Memory content is copied from image to UMat with
//   clEnqueueCopyImageToBuffer function.
//
// Params:
//! @param  cl_mem_image - source image2d_t handle
//! @param  dst          - destination UMat
*/
CV_EXPORTS void convertFromImage(void* cl_mem_image, UMat& dst);
```
The comment should be modified to match doxygen format:
```.cpp
/**
*/
```

**Comment by ankitaggarwal011** [comment]
@mshabunin, what do you think about the following text for introduction?

> OpenCL Module Introduction
> 
> The OpenCV OCL module contains a set of classes and functions that implement and accelerate OpenCV functionality on OpenCL compatible devices. OpenCL is a Khronos standard, implemented by a variety of devices (CPUs, GPUs, FPGAs, ARM), abstracting the exact hardware details, while enabling vendors to provide native implementation for maximal acceleration on their hardware. The OpenCV OCL module is designed for ease of use and does not require any knowledge of OpenCL. At a minimum level, it can be viewed as a set of accelerators, that can take advantage of the high compute throughput that GPU/APU devices can provide. 
> 
> This module includes utility functions, low-level vision primitives, and high-level algorithms. The utility functions and low-level primitives provide a powerful infrastructure for developing fast vision algorithms taking advantage of OCL, whereas the high-level functionality (samples) includes some state-of-the-art algorithms (including LK Optical flow, and Face detection) ready to be used by the application developers. The module is also accompanied by an extensive performance and accuracy test suite.
> 
> Acceleration of OpenCV with OpenCL in the OpenCV-2.4.3 release included the new OCL module containing OpenCL implementations of some existing OpenCV algorithms. That is, when OpenCL runtime and a compatible device are available on a client machine, user may call cv::ocl::resize() instead of cv::resize() to use the accelerated code. OCL module has been a separate API alongside with the primary CPU-oriented API in OpenCV-2.x.
> 
> In OpenCV-3.x, the architecture concept has been changed to the so-called Transparent API (T-API). In the new architecture a separate OpenCL-accelerated cv::ocl::resize() is removed from external API and becomes a branch in a regular cv::resize(). This branch is called automatically when it's possible and makes sense from the performance point of view.
> 
> Code Sample
> 
> Regular CPU code
> // initialization
> VideoCapture vcap(...);
> CascadeClassifier fd("haar_ff.xml");
> Mat frame, frameGray;
> vector faces;
> for(;;){
>   // processing loop
>   vcap >> frame;
>   cvtColor(frame, frameGray, BGR2GRAY);
>   equalizeHist(frameGray, frameGray);
>   fd.detectMultiScale(frameGray, faces, ...);
>   // draw rectangles …
>   // show image …
> }
> 
> OpenCL-aware code OpenCV-3.x
> // initialization
> VideoCapture vcap(...);
> CascadeClassifier fd("haar_ff.xml");
> UMat frame, frameGray;
> vector faces;
> for(;;){
>   // processing loop
>   vcap >> frame;
>   cvtColor(frame, frameGray, BGR2GRAY);
>   equalizeHist(frameGray, frameGray);
>   fd.detectMultiScale(frameGray, faces, ...);
>   // draw rectangles …
>   // show image …
> }
> 
 
There could be more snippets of code comparing regular CPU code with T-API code. Would you please help, I'm unable to find the *Detailed Description* part in [this ](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/ocl.hpp) file.

To summarize the things that have to done:
- Add the introduction to OpenCL module T-API in the *Detailed Description* part of [this ](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/ocl.hpp) file.
- Correct the existing documented T-API functions to match the doxygen format.

How many code snippets do you think should be included in the introduction? Thanks.

**Comment by krishraghuram** [comment]
Im new here, but can someone explain this?

The top of the page says that the issue is open in green with the text "mshabunin opened this issue on 30 Aug 2016"
But at the bottom, just before comment box, I see that the issue is closed. 

Also, the OpenCL docs still dont have any Introduction, so Im assuming that the issue is still open.

**Comment by mshabunin** [comment]
This issue is still open, the red "Closed" block is from another issue (or PR) which referenced this one.

**Comment by krishraghuram** [comment]
After reading [this](http://code.opencv.org/attachments/download/1591) and [this](https://www.learnopencv.com/opencv-transparent-api/), I think the below intro will explain T-API best. 

Since there is no more separate code for cpu and gpu, i.e, no more cv::canny and ocl::canny, and everything has been reduced to UMat, I think the below simple introduction will be sufficient for people to get started with T-API.

>Open Computing Language (OpenCL) is an open standard for writing code that runs across heterogeneous platforms including CPUs, GPUs, DSPs and etc. In particular OpenCL provides applications with an access to GPUs for non-graphical computing (GPGPU) that in some cases results in significant speed-up. In Computer Vision many algorithms can run on a GPU much more effectively than on a CPU: e.g. image processing, matrix arithmetic, computational photography, object detection etc.
>
>Acceleration of OpenCV with OpenCL started 2011 by AMD. As the result the OpenCV-2.4.3 release included the new ocl module containing OpenCL implementations of some existing OpenCV algorithms. That is, when OpenCL runtime and a compatible device are available on a client machine, user may call cv::ocl::resize() instead of cv::resize() to use the accelerated code. During 3 years more and more functions and classes have been added to the ocl module; but it has been a separate API alongside with the primary CPU-oriented API in OpenCV-2.x.
>
>In OpenCV-3.x the architecture concept has been changed to the so-called Transparent API (T-API). In the new architecture a separate OpenCL-accelerated cv::ocl::resize() is removed from external API and becomes a branch in a regular cv::resize(). This branch is called automatically when it’s possible and makes sense from the performance point of view. The T-API implementation was sponsored by AMD and Intel companies.

```
//Regular CPU Code
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;

int main()
{
	//Initialization
	VideoCapture vcap("test2.mp4");
	if(!vcap.isOpened()) //Video not opened check
		return -1;
	CascadeClassifier fd("haarcascade_frontalface_default.xml");
	Mat frame, frameGray;
	vector<Rect> faces;

	//Processing loop
	while(1)
	{
		vcap >> frame;
		if(frame.empty()) //End of video check
			break;
		cvtColor(frame, frameGray, CV_BGR2GRAY);
		equalizeHist(frameGray, frameGray);
		//Detect Faces
		fd.detectMultiScale( frameGray, faces, 1.1, 2, 0|CV_HAAR_SCALE_IMAGE, Size(30, 30) );
		//Draw circles over the faces
		for( size_t i = 0; i < faces.size(); i++ )
		{
			Point center( faces[i].x + faces[i].width*0.5, faces[i].y + faces[i].height*0.5 );
			ellipse( frameGray, center, Size( faces[i].width*0.5, faces[i].height*0.5), 0, 0, 360, Scalar( 255, 0, 255 ), 4, 8, 0 );
		}
		//Show the result to user
		namedWindow("frameGray",CV_WINDOW_NORMAL);
		imshow("frameGray",frameGray);
		waitKey(33);
	}
}
```
```
//T-API Accelerated Code
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;

int main()
{
	//Initialization
	VideoCapture vcap("test2.mp4");
        if(!vcap.isOpened()) //Video not opened check
                return -1;
	CascadeClassifier fd("haarcascade_frontalface_default.xml");
	Mat frame;//, frameGray;
	UMat uframe, frameGray;
	vector<Rect> faces;

	//Processing loop
	while(1)
	{
		vcap >> frame;
		frame.copyTo(uframe);
                if(frame.empty()) //End of video check
                        break;
		cvtColor(uframe, frameGray, CV_BGR2GRAY);
		equalizeHist(frameGray, frameGray);
		//Detect Faces
		fd.detectMultiScale( frameGray, faces, 1.1, 2, 0|CV_HAAR_SCALE_IMAGE, Size(30, 30) );
		//Draw circles over the faces
		for( size_t i = 0; i < faces.size(); i++ )
		{
			Point center( faces[i].x + faces[i].width*0.5, faces[i].y + faces[i].height*0.5 );
			ellipse( frameGray, center, Size( faces[i].width*0.5, faces[i].height*0.5), 0, 0, 360, Scalar( 255, 0, 255 ), 4, 8, 0 );
		}
		//Show the result to user
		namedWindow("frameGray",CV_WINDOW_NORMAL);
		imshow("frameGray",frameGray);
		waitKey(33);
	}
}
```


One question about slide 21 from the link at top : It shows how cvtColor has been implemented under the hood to use openCL whenever its possible. But does it mean that **all** openCV functions have been altered in 3.x the same way???

**Comment by krishraghuram** [comment]
@mshabunin 

Gentle Reminder

**Comment by mshabunin** [comment]
@krishraghuram , what you propose is some general introduction also presented on [opencv.org](http://opencv.org/platforms/opencl.html). We need more technical details, for example `OPENCV_OPENCL_DEVICE` environment variable description, classes and methods documentation. Most of this information can be ported from corresponding [2.4 page](http://docs.opencv.org/2.4/modules/ocl/doc/introduction.html). Code snippets can be inserted from [T-API samples](https://github.com/opencv/opencv/tree/master/samples/tapi).

As you can see in current `cvtColor` code:
```.cpp
CV_OCL_RUN( _src.dims() <= 2 && _dst.isUMat() && !(depth == CV_8U && (code == CV_Luv2BGR || code == CV_Luv2RGB)),
                ocl_cvtColor(_src, _dst, code, dcn) )
```
It means that T-API will not be called if destination is not `UMat`. These slides are quite old, probably some things have changed since then.

**Comment by alalek** [comment]
Wiki page about OpenCL: https://github.com/opencv/opencv/wiki/OpenCL-optimizations
