### ISSUE TITLE
Recent change to modules/videoio/src/cap_ffmpeg_impl.hpp breaks on Ubuntu > 14.04

### ISSUE THREAD

**Issue by rjray** [opencv/opencv#7203]
Trying to build with CUDA support on a newer Ubuntu platform, and I am getting the following error:

```
In file included from /home/nvidia/rjray-opencv/opencv/modules/videoio/src/cap_ffmpeg.cpp:47:0:
/home/nvidia/rjray-opencv/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In member function ‘double CvCapture_FFMPEG::get_fps() const’:
/home/nvidia/rjray-opencv/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:1138:49: error: ‘AVStream’ has no member named ‘r_frame_rate’
     double fps = r2d(ic->streams[video_stream]->r_frame_rate);
                                                 ^
modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:169: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o' failed
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1
CMakeFiles/Makefile2:5741: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2
```

This seems to be due to the change in 998c43ffea70b4ee46d8ec7233e044be6bbb847d, which un-did an earlier fix for libavcodec support for Ubuntu versions newer than 14.04.

**Comment by alalek** [comment]
Please add information about ffmpeg version. Something like this:
```
dpkg -l libav*
```

**Comment by alalek** [comment]
Actually, master branch of ffmpeg still [uses](https://github.com/FFmpeg/FFmpeg/blob/8175fb03f0bad68ace3c074581ea44145bf9160a/libavformat/utils.c#L4708) `r_frame_rate` field of `AVStream`.

**Comment by rjray** [comment]
I cannot comment on the ffmpeg source, I only know that it is failing on my systems that are newer than 14.04, as is the case with many of the commentators on 998c43ffea70b4ee46d8ec7233e044be6bbb847d.

The output from the dpkg command on the failing platform is:

```
ii  libavc1394-0:a 0.5.4-2      arm64        control IEEE 1394 audio/video dev
ii  libavcodec-dev 6:11.2-1     arm64        Development files for libavcodec
un  libavcodec-ext <none>       <none>       (no description available)
ii  libavcodec56:a 6:11.2-1     arm64        Libav codec library
ii  libavformat-de 6:11.2-1     arm64        Development files for libavformat
ii  libavformat56: 6:11.2-1     arm64        Libav file format library
ii  libavresample- 6:11.2-1     arm64        Development files for libavresamp
un  libavresample0 <none>       <none>       (no description available)
ii  libavresample2 6:11.2-1     arm64        Libav audio resampling library
ii  libavutil-dev  6:11.2-1     arm64        Development files for libavutil
ii  libavutil54:ar 6:11.2-1     arm64        Libav utility library
```

For comparison, the same output from the 14.04 machine that can build successfully:

```
ii  libavc1394-0:a 0.5.4-2      amd64        control IEEE 1394 audio/video dev
ii  libavcodec-dev 6:9.18-0ubun amd64        Development files for libavcodec
ii  libavcodec-ext 6:9.18-0ubun all          Libav codec library (additional c
ii  libavcodec-ext 6:9.18-0ubun amd64        Libav codec library (additional c
rc  libavcodec54:a 6:9.18-0ubun amd64        Libav codec library
ii  libavformat-de 6:9.18-0ubun amd64        Development files for libavformat
un  libavformat-ex <none>       <none>       (no description available)
ii  libavformat54: 6:9.18-0ubun amd64        Libav file format library
ii  libavutil-dev  6:9.18-0ubun amd64        Development files for libavutil
ii  libavutil52:am 6:9.18-0ubun amd64        Libav utility library
```

As you can see, there is a difference in the API versions (9 vs. 11). The change that was undone by 998c43ffea70b4ee46d8ec7233e044be6bbb847d had allowed both to work.

**Comment by rjray** [comment]
Poked around the Ffmpeg source for a bit, and looked at the headers that are installed on the machine that is failing to build.

It seems that the `r_frame_rate` member of `AVStream` did disappear at some point, but is now back in the structure. The API version in the repo source is also bumped up to 12 (from 11 in the libraries I have on the machine I'm using). I've been looking at the history of the file, but I cannot determine when the field was removed and when it was restored.

**Comment by alalek** [comment]
Looks like problem is related to compilation with libav, not ffmpeg (Ubuntu 14.x uses "libav" by default, Ubuntu 15.x was switched back to ffmpeg).
[libav commit](https://github.com/libav/libav/commit/85a5bc054c1290699ccbf5799ba6c4e2fbcc3530#diff-3fef4f3bf6d67e9b36fde174cb71341e) with removal of `r_frame_rate`.
Unfortunately, there is no entry in [API changes documentation](https://github.com/libav/libav/blob/master/doc/APIchanges) about this, so need to guess some version with these changes.

**Comment by rjray** [comment]
Yes, I finally stumbled upon that same commit yesterday. They later restored the field, because there wasn't anything else in the AVStream struct that provided the same information. The version of the libav* libs on 16.04 are after the field was restored, so they build OK (the test pass-rate is only 56%, but that's a different issue for another time). It seems that Ubuntu 15.04 (which is what I was building on in this case) has the "in-between" version of the AV libs, which are what break. I don't know what libs Ubuntu 15.10 uses, so it may only be 15.04 that has an issue.

It's worth noting (as an aside), that the FFmpeg git repo appears to be mirroring the libav stuff within it (and the GitHub repo for FFmpeg is just a mirror of their own public repo). But when I found this commit that you referenced, it was in the FFmpeg GitHub repo.

**Comment by alalek** [comment]
@rjray Could you add version information? It looks like this (and it is usually located in `libavformat/version.h` header file):
```
#define LIBAVFORMAT_VERSION_MAJOR  57
#define LIBAVFORMAT_VERSION_MINOR  48
#define LIBAVFORMAT_VERSION_MICRO 101
```

**Comment by rjray** [comment]
The version that was failing has the following:

```
#define LIBAVFORMAT_VERSION_MAJOR 56
#define LIBAVFORMAT_VERSION_MINOR  1
#define LIBAVFORMAT_VERSION_MICRO  0
```

For comparison, the version on Ubuntu 14.04 is:

```
#define LIBAVFORMAT_VERSION_MAJOR 54
#define LIBAVFORMAT_VERSION_MINOR 20
#define LIBAVFORMAT_VERSION_MICRO  4
```
