### ISSUE TITLE
HOGDescriptor crashed when launched setSVMDetector

### ISSUE THREAD

**Issue by MaeThird** [opencv/opencv#7209]
Here are the basic relative infos:
- OpenCV => 3.1.0
- Operating System / Platform => Windows 64 Bit
- CPU => amd
- Compiler => Visual Studio 2015

--I'm new in OpenCV. My issue is the crash caused by the simple piece of code blow ( I've  removed the  non-sensitive one).
```.cpp
int main(int argc, char** argv)
{

	
	HOGDescriptor defaultHog;
	printf("...c\n");
	defaultHog.setSVMDetector(HOGDescriptor::getDefaultPeopleDetector());
	printf("...a\n");


	return 0;
}
```
--And it crashed in core/src/umatrix.cpp :
```.cpp
void UMat::create(int d, const int* _sizes, int _type, UMatUsageFlags _usageFlags){
  ...
 release();// crashed here !!
 ...
}
```
--This looks like something wrong during compiling the source code of CV.But I did received nothing 
--serious warnings.
--So,Can you help ? Thanks

**Comment by StevenPuttemans** [comment]
Hmm it seems that somehow, due to the UMat hint, OpenCL is being used and is not configured correctly. Could your rebuild OpenCV without OpenCL support and try again?

**Comment by mshabunin** [comment]
I can't reproduce this issue in VS2015 with latest OpenCV commit. Please try to use latest version too.

**Comment by MaeThird** [comment]
I recompiled the source as @StevenPuttemans hinted and it's OK now. It's truth that I compiled with CL last time and after that I updated some CL.XXX.DLL ,which caused inconsistent
