### ISSUE TITLE
InputArray::isContinuous() does not support GpuMat

### ISSUE THREAD

**Issue by taketwo** [opencv/opencv#7215]
[`InputArray::isContinuous()`](https://github.com/opencv/opencv/blob/671e95d59efa23aec8689b495876005964f78f61/modules/core/src/matrix.cpp#L1973-L2003) does not support `GpuMat`, even though `GpuMat` itself has a function to check continuity.

If there is no special reason for that, I can submit a pull request adding these lines:

```cpp
if( k == CUDA_GPU_MAT )
    return i < 0 ? ((const cuda::GpuMat*)obj)->isContinuous() : true;
```

**Comment by StevenPuttemans** [comment]
You will get faster feedback by simply making the PR and awaiting its review ;)
