### ISSUE TITLE
Different pathname resolving functionalities of imread in C++, Python 

### ISSUE THREAD

**Issue by anirudt** [opencv/opencv#7219]
##### System information (version)
- OpenCV => 2.4.13
- Operating System / Platform => Linux 64 Bit
- Compiler => g++, 4.8.4

##### Detailed description

The ```~``` in the Linux path of the filename is being resolved in case of C++ imread, though in Python, the same imread results in a nan object. This could be due to the string processing of the filename in Python.

##### Steps to reproduce

I found this error for .jpg and .jpg files. The following example is being explained using the AT&T face database.
*Python*:
```
$  python
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.imread("~/Datatsets/orl_faces/s1/1.pgm", cv2.IMREAD_GRAYSCALE)
>>> cv2.imread("~/Datatsets/orl_faces/s90/1.pgm", cv2.IMREAD_GRAYSCALE)
>>> cv2.imread("~/Datasets/orl_faces/s1/1.pgm", cv2.IMREAD_GRAYSCALE)
>>> cv2.imread("/home/anirudt/Datasets/orl_faces/s1/1.pgm", cv2.IMREAD_GRAYSCALE)
array([[48, 49, 45, ..., 56, 56, 54],
       [45, 52, 39, ..., 52, 50, 51],
       [45, 50, 42, ..., 48, 53, 50],
       ..., 
       [50, 48, 50, ..., 45, 46, 46],
       [45, 54, 49, ..., 46, 47, 47],
       [51, 51, 51, ..., 47, 46, 46]], dtype=uint8)
>>> exit()
```

*C++*:
Following the tutorial in [this page](http://docs.opencv.org/2.4/doc/tutorials/introduction/display_image/display_image.html), the image was found to appear in either of the following commands after compilation:
```
$ ./imr ~/Datasets/orl_faces/s1/1.pgm

$ ./imr /home/anirudt/Datasets/orl_faces/s1/1.pgm
```

**Comment by StevenPuttemans** [comment]
Actually this is a known issue that Python cannot resolve ., .. and ~. You need to use functions to get the correct path from that.

See
- http://stackoverflow.com/questions/4684520/fixing-paths-in-python
- http://stackoverflow.com/questions/32838760/how-to-resolve-relative-paths-in-python

You basically need to tell Python to convert the relative path to an absolete one!

**Comment by alalek** [comment]
> ./imr ~/Datasets/orl_faces/s1/1.pgm

What output of `printf("%s\n", argv[1])` in this case? Do you see any '~' here? I believe, your shell (bash) do some tricks here.

OpenCV pass specified file paths directly to OS, so requirement for file path is simple - OS FS layer should understand your path.
In your case you should use `os.path.absname('~/some_path_from_user_home')` to get canonical file path. Python will do some tricks with `~` for you in this case (on Windows too).

BTW, Also OpenCV doesn't support Unicode names.
