### ISSUE TITLE
samples/android/face-detection "Failed to load cascade classifier"

### ISSUE THREAD

**Issue by jhannes** [opencv/opencv#7223]
- OpenCV => 3.1
- Operating System / Platform => OpenCV-3.1.0-android-sdk
##### Detailed description

When running the samples/android/face-detection sample from the OpenCV-3.1.0-android-sdk, the Java based face recognition code doesn't detect any faces, but switching to native mode detects faces as expected.

After some investigation and trial and error, I found that adding just a single line to the sample makes it work.
##### Steps to reproduce
1. Run the OpenCV-android-sdk/samples/face-detection
2. Logcat will display the message "Failed to load cascade classifier"
3. Faces will not be detected
4. In FdActivity Add after `mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());`: `mJavaDetector.load(mCascadeFile.getAbsolutePath())`
5. Running the sample again will detect faces correctly
   
   ``` .java
                       mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());
                       mJavaDetector.load(mCascadeFile.getAbsolutePath());
                       if (mJavaDetector.empty()) {
   ```

**Comment by alalek** [comment]
I can't confirm this issue, both Java and Native code paths works fine in 3.2 without additional patches.

**Comment by EliasAthey** [comment]
Just had this same issue in 3.2...adding mJavaDetector.load(mCascadeFile.getAbsolutePath()) fixed it.
