### ISSUE TITLE
Multiband blender fails in OpenCV3.1.0

### ISSUE THREAD

**Issue by unixnme** [opencv/opencv#7225]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Ubuntu 16.04, Mac OS X El Capitan
- Compiler => gcc, clang

##### Detailed description

Hello, I am trying out the stitching example. I have noticed that multiband blender gives segmentation fault, which is due to OpenCL. With this disabled, it still fails. Below is the test result:

bin/opencv_test_stitching
CTEST_FULL_OUTPUT
OpenCV version: 3.1.0
OpenCV VCS version: unknown
Build type: debug
Parallel framework: gcd
CPU features: mmx sse sse2 sse3
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MultiBandBlender
[ RUN      ] MultiBandBlender.CanBlendTwoImages
unknown file: Failure
C++ exception with description "vector" thrown in the test body.
[  FAILED  ] MultiBandBlender.CanBlendTwoImages (0 ms)
[----------] 1 test from MultiBandBlender (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MultiBandBlender.CanBlendTwoImages

 1 FAILED TEST

##### Steps to reproduce

wget https://github.com/Itseez/opencv/archive/3.1.0.zip
unzip 3.1.0.zip
cd opencv-3.1.0
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=DEBUG -D BUILD_EXAMPLES=ON -D CMAKE_BUILD_PREFIX=/usr/local/ -D WITH_OPENCL=OFF ..
make -j4
bin/opencv_test_stitching

**Comment by alalek** [comment]
You should refer to information about running OpenCV tests and OPENCV_TEST_DATA_PATH environment variable.

**Comment by unixnme** [comment]
Ah, thank you so much!
