### ISSUE TITLE
3rdparty: libpng build fails on VS2012

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#7232]
##### System information (version)

- OpenCV => master ( 554017673a09bd44b8f082ad12fae63b76c3d7e7 )
- Operating System / Platform => Windows 7 64bit
- Compiler => Visual Studio 2012 Update 5

##### Detailed description

libpng build fails on ``filter_sse2_intrinsics.c``.
The direct cause is that ``filter_sse2_intrinsics.c`` has extention ``c`` when it's not following C89, such as following.

```filter_sse2_intrinsics.c
static void store3(void* p, __m128i v) {
   /* We'll pull from SSE as a 32-bit int, then write
    * its bottom two bytes, then its third byte.
    */
   png_uint_32 v012;
   store4(&v012, v);     /* In C89, no more variable are allowed to declare after this line */
                         /*                                                                 */
   png_uint_16* p01 = p; /* which happens here                                              */
   png_byte*    p2  = (png_byte*)(p01+1);
   *p01 = v012;
   *p2  = v012 >> 16;
}
```

I just searched on this problem, and it seems that [from VS2013 and later, this strict has been loosened](http://stackoverflow.com/questions/9903582/error-c2275-illegal-use-of-this-type-as-an-expression)

##### Steps to reproduce

Build any revision after 554017673a09bd44b8f082ad12fae63b76c3d7e7 on VS2012

##### Point of discussion

Since the cause is in libpng (external library), I'm not sure which way to fix.

1. rename ``filter_sse2_intrinsics.c`` to ``filter_sse2_intrinsics.cpp``
  - This seems temporary fix
  - I'm not sure how other platform behaves under this condition
2. revert commit 554017673a09bd44b8f082ad12fae63b76c3d7e7
  - This is one of the extreme approach
  - Although, it's promising.
3. configure libpng so it's build under standard which is later than C89
  - The main cause is the syntax part and not the logical part.  This file shuold be able to be compiled under something later than C89
  - Still, I'm not sure about the legal condition of libpng.  Are we allowed to import "modified" libpng in OpenCV ? Shouldn't libpng be "as is" ?
4. Drop support of VS2012
  - This is another extreme solution, but still, it's one of the solution.
5. Something else

Any idea ?
Best regards

**Comment by alalek** [comment]
@tomoaki0705 Does this patch #7259 work for you?

**Comment by tomoaki0705** [comment]
@alalek sorry for late reply.
I confirmed that #7259 and #7295 works well on VS2012.
I appreciate for your time.
