### ISSUE TITLE
opencv manager issue on galaxy s6

### ISSUE THREAD

**Issue by sarmadm** [opencv/opencv#7235]
HI

I'm trying to run opencv app on my S6 device. I have installed opencv manager from play store but when I run the app

this message is displayed ( opencv manager wasn't initialized correctly ) or ( unfortunately app has stopped ).

How can this issue be fixed ? I can give the app if someone want to test it

Thanks for help

**Comment by alalek** [comment]
Could you try to build with OpenCV SDK directly (without using of OpenCV manager).

**Comment by sarmadm** [comment]
How can I do this ?, you mean using android studio ?

**Comment by alalek** [comment]
There is OpenCV manager's known issue for Android devices with 64-bit ARM CPU, but with 32-bit Android OS (package version is not detected right).

In depends on how you build your app (what IDE/build tools are used). You need to integrate OpenCV binaries directly into application ("libs" folder) and [modify](https://github.com/opencv/opencv/commit/e1ad86c1fa5cf43fefd197ef4aa9a9ace33299cf#diff-53afec9baf17b47c67e3559b17690329) initialization code of OpenCV.

There are some Android tutorials (but they are based on Eclipse IDE):
- [OpenCV4Android SDK](http://docs.opencv.org/master/da/d2a/tutorial_O4A_SDK.html)
- [Introduction into Android Development](http://docs.opencv.org/master/d9/d3f/tutorial_android_dev_intro.html)
- [Android Development with OpenCV](http://docs.opencv.org/master/d5/df8/tutorial_dev_with_OCV_on_Android.html)

More questions how to build Andoid app with OpenCV please ask on Q/A user forum: http://answers.opencv.org

BTW, Android Studio is not supported by OpenCV directly.

**Comment by alalek** [comment]
BTW, Take a look on workarounds from this issue: #6247

**Comment by sarmadm** [comment]
Thanks for your help

**Comment by vpisarev** [comment]
looks like this is answered
