### ISSUE TITLE
Blending artifacts in OpenCV 3.1 image stitching

### ISSUE THREAD

**Issue by Finfa811** [opencv/opencv#7251]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

In some cases artifacts are appearing when using stitching module with multi-band blender in 3.1 version (in 2.4.9 it's working perfectly). They concretely appear when the borders of the seam masks are near the borders of the original masks.

I solved the issue few months ago. The reason is because corners and warped images were changed to be conformed by _borderType_ **BORDER_CONSTANT** instead of by **BORDER_REFLECT**. That leads to black gaps in the images that will blur with foreground pixels in the pyramidal blending step, resulting in the mentioned artifacts. Pictures and examples can be seen in the question I opened [here](http://answers.opencv.org/question/89028/blending-artifacts-in-opencv-image-stitching/).

To fix the issue, this [commit](https://github.com/opencv/opencv/commit/a7f69a37e345146bb5d23dc72053ae94bb1ea241) should be reverted. I commented the commit few months ago when I solved the problem, but since I got no reply I just open this issue following the request of a user of _answers.opencv.org_.

**Comment by StevenPuttemans** [comment]
@Finfa811 I guess the best way to get this reverted as fast as possible is supply a PR with the forementioned revert and a link to this topic and the Q&A. It will get the attention of devs as fast as possible that way!

**Comment by StevenPuttemans** [comment]
You can leave this one open untill the PR discussion is finished and the PR is merged in!

**Comment by Finfa811** [comment]
Sure, @StevenPuttemans. Sorry :)

**Comment by alalek** [comment]
Could you add input images to reproduce this issue?

**Comment by Finfa811** [comment]
Yes @alalek, try with this dataset:
[shanghai.zip](https://github.com/opencv/opencv/files/461367/shanghai.zip)
