### ISSUE TITLE
Unhandled exceptions on executing cuda function

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#7254]
I have rebuild OpenCV with revision 3.1.0-1270-g48af5e5, and in the code that worked fine on older builds I get Unhandled exception. Error output:
`OpenCV Error: Gpu API call (invalid device function ) in cv::cudev::grid_transfo
rm_detail::TransformDispatcher<false, Policy>::call, file c:\lib\opencv\sources\
opencv\modules\cudev\include\opencv2\cudev\grid\detail/transform.hpp, line 270`
on functions like 
`cuda::cvtColor`

Windows 7 x64, VS 2013

**Comment by jet47** [comment]
`invalid device function` means that GPU code in incompatible with your GPU architecture. Please check `CUDA_ARCH_BIN` and `CUDA_ARCH_PTX` CMake variables, they should correspond to your GPU compute capabilities.

**Comment by Bleach665** [comment]
@jet47 
CUDA_ARCH_BIN=2.0 3.0 3.5 5.0 which no correspondent my GPU - GTX 260 (CUDA ver 1.3)
CUDA_ARCH_PTX variable is empty

**Comment by jet47** [comment]
Then you need to set `CUDA_ARCH_BIN` to `1.3`.

**Comment by Bleach665** [comment]
thanks, but older revision do this automatically

**Comment by jet47** [comment]
`1.x` CC was dropped from default configuration to reduce compilation time and output binaries size.

**Comment by Bleach665** [comment]
Its sad..
