### ISSUE TITLE
Using OpenCV library in java project

### ISSUE THREAD

**Issue by heroinsoul** [opencv/opencv#7261]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Linux, Debian 8, Ubuntu 16.04
- Compiler => g, g++

##### Detailed description

I'm using OpenCV library in one of my projects for face recognition and motion detection. The outcome is a jar file that I can successfully execute on my system. The problem starts when other people try to execute the same jar in their environment. The OpenCV library can't be recognized on their system and the only way to make it work is to compile new OpenCV jar and .so files and add them to the project. 

My question here is whether there is a way to compile the OpenCV jar and .so files that could be used on any platform as part of my project. 

Thanks

**Comment by StevenPuttemans** [comment]
You need to build your app in a static way, resulting in .a files instead of .so files. Then you will have a system independent setup.

**Comment by alalek** [comment]
Unfortunately there is no easy algorithm how to distribute binaries. I can point some hints only:
At first, build OpenCV with `-DBUILD_SHARED_LIBS=OFF` CMake option - this will pack all binary code into single file.
Next, try to minimize external 3rdparty dependencies ("WITH_" options to OFF, "BUILD_*" options to ON). Check output of `ldd libopencv_java310.so` - it will show you all required external dependencies. You can try to switch external dependencies to static linkage, but it will require properly configured 3rdparty dependencies (many Linux distributions uses shared linkage as preferred).
Finally, test compatibility of the result (libc version, java JVM version / vendor - OpenJDK/Oracle).

BTW, Please ask usage questions on OpenCV User Q/A forum: http://answers.opencv.org
