### ISSUE TITLE
Non-operational link in documentation.

### ISSUE THREAD

**Issue by ankitaggarwal011** [opencv/opencv#7264]
In the last section "Links" available on http://opencv.org/platforms/opencl.html documentation, the first link **"OpenCV Transparent API presentation"** pointing to https://docs.google.com/presentation/d/1qoa29N_B-s297-fp0-b3rBirvpzJQp8dCtllLQ4DVCY/present is non-operational.

The same link is also used on the same page in the text **"More details on the T-API can be found in the following slides."** with "slides" pointing to the discussed non-operational link.

**Comment by mshabunin** [comment]
This presentation seem to be unavailable, broken link has been removed.
