### ISSUE TITLE
pyrUp with odd output size produces garbage

### ISSUE THREAD

**Issue by modisio** [opencv/opencv#7269]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => MacOS X 64 Bit
- Compiler => clang

##### Detailed description
The documentation for cv::pyrUp states that the output size can be an odd number equal to `2*inputsize +-1`.    However when outputsize is `2*inputsize +1`, the output additional column or row is not initialized.

##### Steps to reproduce
The following code gives this result:

out = 
 [0.5, 0.5, 0.5, 0.5, 7.605087463455636e-311;
 0.5, 0.5, 0.5, 0.5, 8.691528529697745e-311;
 0.5, 0.5, 0.5, 0.5, 7.605087463515912e-311;
 0.5, 0.5, 0.5, 0.5, 4.345764264874564e-311]

```.cpp

         Mat in, out;
        in = Mat(Size(2, 2), CV_64FC1, .5);
        pyrUp(in, out, Size(5,4));
        ofstream myfile;
        myfile.open ("pyrUp-Output.txt");
        myfile << "out = "<< endl << " "  << out << endl << endl;
        myfile.close();
```

**Comment by terfendail** [comment]
The issue have been fixed by #5996 and #6448.
