### ISSUE TITLE
Mean computation of the same file differes between computers

### ISSUE THREAD

**Issue by ArkadiuszRaj** [opencv/opencv#7277]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.4 Desktop / Server, latest  patches applied 
- Compiler => gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

##### Detailed description

Simple story: use **imread()** to load the data, then **split()** to divide it into the color planes. For each of them compute **mean()** value and print.

For my application I added several cucumber test cases, but found out that for JPEG files results are not consistent between different machines I clone github repo to.

Comp A: Lenovo G50 laptop with Ubuntu 16.4
Comp B: Dell 790 with Ubuntu Server 16.4

All the latest patches applied, the same procedure. wget file from the same source, run very simplistic code described above and exit.

Laptop - Lenovo G50

> wget http://www.fmwconcepts.com/misc_tests/canny/lena3.jpg
> repository/test$ ./test
>   105.4194
>    99.0473
>   180.2414

Dell 790

> wget http://www.fmwconcepts.com/misc_tests/canny/lena3.jpg
> repository/test$ ./test
>   105.4254
>    99.0470
>   180.2376
> 

The difference is in R & B channels. Very small indeed but...

According to Matlab, ImageJ & even Photoshop (latest) histogram stats the good results are achieved on laptop, not on Dell 790.

For TIFF, PNG, PBM - no problems at all. Only for JPEG files there is difference in decoding.

##### Steps to reproduce

As written above. No magic

```
void main() {
Mat img = imload('lena3.jpg');
std::vector<cv::Mat> planes;
split(img, planes);

for(auto&& p : planes)
 cout << endl << mean(p)
}
```

**Comment by alalek** [comment]
JPEG is not bit-exact format. Result may depends on image library and version. You can check build configuration including used image codecs via `cv::getBuildInformation()` call.
You should use PNG to get bit-exact data.

**Comment by ArkadiuszRaj** [comment]
I am fully aware of that, but as I wrote: Matlab, Photoshop & ImageJ decodes in the same way as OpenCV 3.1.0-dev (details below)... And as my app is about analysing pictures taken from digital cameras - you know.. the waste majority of them are still using JPEG. How to trust continuous integration if results are not consistent among different machines?

Yes - the difference actually is that Dell790 has OpenCV 3.1.0 as a downloadable package while for  laptop I had cloned the master branch from github (hence 3.1.0-dev). Now I have cloned the master branch  on Dell790 as well. After compilation of fresh sources completed, starting my app on Dell790 gave the same result as on Laptop/Matlab/ImageJ/Photoshop!

As the only thing that changed was switch from 3.1.0 package into the cloned 3.1.0-dev I assume that there is a bug on 3.1.0.

**Comment by alalek** [comment]
> my app is about analysing pictures taken from digital cameras

In ideal case, algorithms should be stable - provide the same result in case of input with some "insignificant" noise (btw, noise exists in almost all cameras - quantization of analog signal).

> How to trust continuous integration

Test acceptance criteria should allow slightly noise in input data or during computation (floating-point arithmetic has some tricks).

Question's answer is:
OpenCV uses 3rdparty libraries to read JPEG images and they can be different and provide slightly different results. You need to check that used JPEG libraries are same and they are compiled with same compiler options. In this case results should be same on the same hardware.

**Comment by ArkadiuszRaj** [comment]
Instead of discussing possible fault dialogue turns to some abstract principles...

> In ideal case, algorithms should be stable - provide the same result in case of input with some "insignificant" noise (btw, noise exists in almost all cameras - quantization of analog signal).

Yeap, but I am interested in analysis of those distrubances rather than image itself. That is why I need stable "decoding" engine. By decoding I mean data in Mat. I understand if major update of the jpeg lib is done, luckliy we do not observe that. 
From repo https://github.com/opencv/opencv/tree/master/3rdparty/libjpeg  _" Update libjpeg to "Version 9 13-Jan-2013" 	**4 years ago**"_ 
If local operating system libjpeg-dev is used instead, again, both comps has latest Ubuntu 16.04 xenial - libjpeg-dev (8c-2ubuntu8) 

> Test acceptance criteria should allow slightly noise in input data or during computation (floating-point arithmetic has some tricks).

Again, my goal is to have stable algo that calculates different things like for example the noise according to ISO15739 standard. Yes, floating digits are not used in comparisions to prevent influence of floating -point arthmetic itself. But agree, to have verified code it would be enought to check PNGs.

> 
OpenCV uses 3rdparty libraries to read JPEG images and they can be different and provide slightly different results. 

That is obvious. But why changing ONLY opencv and NOTHING ELSE changes way how file data is presneted to application? Assuming decoding lib has not changed...
And the change was from 3.1.0 (downloaded as package) to 3.1.0-dev (cloned repo)

**Comment by alalek** [comment]
We need to reproduce problem before we can help. Current input is not enough to do this, so please add more information:
- `cv::getBuildInformation()` from your builds of 3.1.0 and 3.1.0-dev (master)

> libjpeg-dev

Exactly! This is the one of possible reasons for using of different JPEG libraries.

I run this code on current OpenCV master ("clone"):
```
  Mat img = imread("/home/alalek/Downloads/lena3.jpg", 1);
  std::vector<cv::Mat> planes;
  cout << mean(img) << endl;
```
on my **Fedora 24** and
- **builtin JPEG** (sources from 3rdparty subfolder - `-DBUILD_JPEG=ON` CMake option):
```
--     JPEG:                        libjpeg (ver 90)
```
got this result:
```
[105.419, 99.0473, 180.241, 0]
```
- **system JPEG**:
```
--     JPEG:                        /lib64/libjpeg.so (ver )
```
got this result:
```
[105.424, 99.047, 180.238, 0]
```

These results are similar to your different results, but they are still not same.

**Comment by ArkadiuszRaj** [comment]
OK, I consider this:  

> -DBUILD_JPEG=ON 

...as immediate remedy. To secure that the one and only lib  to be used will be the one provided by opencv team.
