### ISSUE TITLE
Add link to the Doxygen documentation in the documentation.

### ISSUE THREAD

**Issue by yuvallanger** [opencv/opencv#7281]
I have linked to the Doxygen page from https://github.com/yuvallanger/opencv/wiki/How_to_contribute in this commit:

https://github.com/yuvallanger/opencv/wiki/How_to_contribute/a2cbf5bce93f51432dd1ef978fe5a89f2cf94e40

Please review the commit. I am not sure where to add the link.

**Comment by alalek** [comment]
Thank you!
Wiki page has been updated.
