### ISSUE TITLE
nonsens assertion?

### ISSUE THREAD

**Issue by derDavidT** [opencv/opencv#7283]
##### System information
- OpenCV => 3.1.0
- Operating System / Platform => Windows 7, 64bit
- Compiler => Visual Studio 2013

##### Detailed description
I'm currently following [this tutorial](http://docs.opencv.org/trunk/d7/d8b/tutorial_py_lucas_kanade.html) for optical flow using openCV in python. When calling `calcOpticalFlowPyrLK` I always get an assertion error which points at [line 1122](https://github.com/opencv/opencv/blob/ab3814f9b98fef0c8e165de99be3840f330806c4/modules/video/src/lkpyramid.cpp#L1121-L1122) in `lkpyramid.cpp`.

Full error message:
>OpenCV Error: Assertion failed ((npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0) in cv::`anonymous-namespace'::SparsePyrLKOpticalFlowImpl::calc, file D:\SVN\opencv\modules\video\src\lkpyramid.cpp, line 1122

Closer look at line 1121f in lkpyramid.cpp:
```
    int level=0, i, npoints;
    CV_Assert( (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 );
```

I am not familiar with openCV source code. Additionally I do not know c++ well. This, however, still looks like a bug to me.

The variable `npoints` is declared but not defined and immediately afterwards used in an assertion.

Please verify and - if needed - fix.

**Comment by derDavidT** [comment]
I've resolved the issue.
Turns out the error was in my python code.

**Comment by donald2016** [comment]
I met the same error, I cannot spot the problem in my code. Would you mind share your experience please?
Thanks

**Comment by derDavidT** [comment]
As I wrote, this was a problem in my python code. You have to be very careful to define the inputs to  `cv.calcOpticalFlowPyrLK` perfectly (i.e. dimensions, dtype, etc.). I advise to run the above mentioned tutorial as is and look how input and output behave.
