### ISSUE TITLE
header guard #defines use reserved identifiers, causing -Wreserved-id-macro warnings

### ISSUE THREAD

**Issue by seanm** [opencv/opencv#7288]
OpenCV's header guard naming scheme uses identifiers reserved by the C++ standard and therefore cause warnings from clang's -Wreserved-id-macro flag.  ex:

```
opencv2/core/mat.hpp:45:9: warning: macro name is a reserved identifier [-Wreserved-id-macro]
 #define __OPENCV_CORE_MAT_HPP__
        ^
```

Specifically, double underscores are reserved, see:
http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

I can submit a PR that renames them all.  It's a simple find-replace job, but it will touch many files.

What naming scheme should be used instead? I propose just removing the double underscores, like:

 #define OPENCV_CORE_MAT_HPP

Thoughts?

Thanks.

**Comment by souch55** [comment]
Hi  alalek i have added the required fix for reserved identifiers as mentioned in this issue ,plz review my changes and marge the PR

**Comment by alalek** [comment]
@souch55 The main problem is there are a lot of files, that require similar changes.

**Comment by souch55** [comment]
for this issue there is there is only one file ,occurrence of i have found, done find and replace for whole source code of opencv master branch  with linux command " find ./ -type f -exec sed -i 's/_OPENCV_CORE_MAT_HPP__/OPENCV_CORE_MAT_HPP/g' {} \;"
which replaces all the files and sub folder's with replacement text alalek.So requesting you to merge my fix.There might be others macros with which follows with identifier warning issue,but this issue as mentioned above is fixed with my PR.

**Comment by alalek** [comment]
You should search for double underscores, for example:
```
$ grep -R '#define __OPENCV' ./ | wc -l
363
```

BTW, This is no approved decision yet to make these changes (for example, changing of `__OPENCV_BUILD` will cause some problems). Also question of scope for changes is still open: "public" headers only or all OpenCV code.

**Comment by seanm** [comment]
@souch55, perhaps I wasn't clear in my wording, but I mean this issue as a general one, not just for one file.  The one warning I showed was only a single example.  There are hundreds/thousands of these warnings.

These warnings can be fixed in stages.  Fixing the header guards should be a pretty easy regex job, and would be a good first step. Starting with __OPENCV_.*_HPP__ would be a good first pass.

My primary goal is for the public headers to not generate such warnings, since those headers are the ones included in my own project (where we are -Wreserved-id-macro clean).

**Comment by vpisarev** [comment]
I think that clang is too strict in this case; and OpenCV uses such macros (`__OPENCV_...__`) in hundreds of places. Is there a strong reason not to disable this warning?

**Comment by seanm** [comment]
Well, it's obviously not the world's most terrible issue. :)

I wouldn't say clang is "too strict".  "Too strict" would be if they made it an error, which really it is, per C++03 standard paragraph 17.4.3.1.2.

Basically, my own codebase uses -Wreserved-id-macro and I have no warnings.  Now I start to use OpenCV, and including its public headers causes me new warnings.  I'd prefer to fix the problem at its source, rather than hack around it.

As I've said, I offer to do the work of creating a patch.  I would start with only the header guards, the renaming of which is unlikely to cause any compatibility problems.  I have made the same fix in other large projects (ex: VTK).

I just need to know what naming scheme should be used instead...

**Comment by souch55** [comment]
Hi alalek i think this issue needs to be fixed as aslo stated by seanm ,so i have created an new PR#7350 for this same issue requesting you to review my changes and merge it.
