### ISSUE TITLE
Skeleton Tracking with Normal camera

### ISSUE THREAD

**Issue by ashokbugude** [opencv/opencv#7296]
I am trying to do skeleton tracking with normal camera.
Checked if there are any exixting source codes by  executing 'cpp-example-lkdemo'. 
I was expecting the output to be as shown in https://www.youtube.com/watch?v=OfDdNv-bMBo video.

Can I please know if there is any source code which provides output exactly as shown in the video

Thanks

**Comment by StevenPuttemans** [comment]
You will need to adapt the code to your actual needs. There is no ready made code for this. Also, in the future, please address these common questions to the [OpenCV Q&A community](https://github.com/StevenPuttemans)

**Comment by alalek** [comment]
@StevenPuttemans I fixed link in your message, please check. Closing this.

**Comment by StevenPuttemans** [comment]
:+1:
