### ISSUE TITLE
skin pixels list to range conversion

### ISSUE THREAD

**Issue by Vinit-Koshti** [opencv/opencv#7301]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015/ Ubuntu

##### Detailed description

Converting textfille of pixels into range of pixel i.e. a function that take pixel as parameter and  return true if pixel is in range otherwise false. ranges should be as less as possible but should cover each and every pixels of the textfile
[skin_pixel.txt](https://github.com/opencv/opencv/files/478079/skin_pixel.txt)

**Comment by mshabunin** [comment]
Please add detailed problem description, for now it looks like technical assignment.
