### ISSUE TITLE
mac osx10.10.2 compile opencv3.1 get errors

### ISSUE THREAD

**Issue by totoks** [opencv/opencv#7316]
I download the source from master.
there are some step:
1.run cmake-gui and gennerate some make files
2.make -j8
3.make error occured.
please help me.thanks

[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/ocl.cpp.o
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdblas.cpp.o
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdfft.cpp.o
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_core.cpp.o
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/out.cpp.o
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1804:42: error: use of undeclared
      identifier 'CL_DEVICE_HOST_UNIFIED_MEMORY'
        hostUnifiedMemory_ = getBoolProp(CL_DEVICE_HOST_UNIFIED_MEMORY);
                                         ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1933:28: error: use of undeclared
      identifier 'CL_DEVICE_OPENCL_C_VERSION'
{ return p ? p->getStrProp(CL_DEVICE_OPENCL_C_VERSION) : String(); }
                           ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2121:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2124:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2127:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_INT'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_INT) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2130:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2133:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2136:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE) : 0; }
                                      ^
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2139:39: error: use of undeclared
      identifier 'CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2160:39: error: use of undeclared
      identifier 'CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF'
{ return p ? p->getProp<cl_uint, int>(CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF) : 0; }
                                      ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:2378:45: error: use of undeclared
      identifier 'CL_DEVICE_HOST_UNIFIED_MEMORY'
                clGetDeviceInfo(devices[i], CL_DEVICE_HOST_UNIFIED_MEMORY, sizeof(isIGPU), &isIGPU, NULL);
                                            ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3244:13: error: variable has
      incomplete type 'void'
static void CL_CALLBACK oclCleanupCallback(cl_event, cl_int, void *p)
            ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3244:24: error: expected ';' after top
      level declarator
static void CL_CALLBACK oclCleanupCallback(cl_event, cl_int, void *p)
                       ^
                       ;
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3490:63: error: use of undeclared
      identifier 'oclCleanupCallback'
        CV_OclDbgAssert(clSetEventCallback(p->e, CL_COMPLETE, oclCleanupCallback, p) == CL_SUCCESS);
                                                              ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1371:68: note: expanded from macro
      'CV_OclDbgAssert'
# define CV_OclDbgAssert(expr) do { if (isRaiseError()) { CV_Assert(expr); } else { (void)(expr); } } w...

```
                                                               ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/include/opencv2/core/base.hpp:412:33: note:
      expanded from macro 'CV_Assert'
# define CV_Assert( expr ) if(!!(expr)) ; else cv::error( cv::Error::StsAssert, #expr, CV_Func, __FILE_...

```
                            ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3490:63: error: use of undeclared
      identifier 'oclCleanupCallback'
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1371:91: note: expanded from macro
      'CV_OclDbgAssert'
# define CV_OclDbgAssert(expr) do { if (isRaiseError()) { CV_Assert(expr); } else { (void)(expr); } } while ((v...

```
                                                                                      ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3510:63: error: use of undeclared
      identifier 'oclCleanupCallback'
        CV_OclDbgAssert(clSetEventCallback(p->e, CL_COMPLETE, oclCleanupCallback, p) == CL_SUCCESS);
                                                              ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1371:68: note: expanded from macro
      'CV_OclDbgAssert'
# define CV_OclDbgAssert(expr) do { if (isRaiseError()) { CV_Assert(expr); } else { (void)(expr); } } w...

```
                                                               ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/include/opencv2/core/base.hpp:412:33: note:
      expanded from macro 'CV_Assert'
# define CV_Assert( expr ) if(!!(expr)) ; else cv::error( cv::Error::StsAssert, #expr, CV_Func, __FILE_...

```
                            ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3510:63: error: use of undeclared
      identifier 'oclCleanupCallback'
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:1371:91: note: expanded from macro
      'CV_OclDbgAssert'
# define CV_OclDbgAssert(expr) do { if (isRaiseError()) { CV_Assert(expr); } else { (void)(expr); } } while ((v...

```
                                                                                      ^
```

/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:3532:53: error: use of undeclared
      identifier 'CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE'
    return clGetKernelWorkGroupInfo(p->handle, dev, CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE,
                                                    ^
[ 21%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/parallel_pthreads.cpp.o
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/src/ocl.cpp:5017:28: error: use of undeclared
      identifier 'clEnqueueReadBufferRect'
                CV_Assert( clEnqueueReadBufferRect(q, (cl_mem)u->handle, CL_TRUE,
                           ^
/Users/Raysmond/Documents/OpenCV/opencv-master/modules/core/include/opencv2/core/base.hpp:412:33: note:
      expanded from macro 'CV_Assert'
# define CV_Assert( expr ) if(!!(expr)) ; else cv::error( cv::Error::StsAssert, #expr, CV_Func, __FILE_...

```
                            ^
```

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: **\* [modules/core/CMakeFiles/opencv_core.dir/src/ocl.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: **\* [all] Error 2

**Comment by alalek** [comment]
1. Clean build directory.
2. Run cmake again with `-DWITH_OPENCL=OFF` option.

**Comment by ShreyashPromact** [comment]
This didn't resolved the issue. Is there any other alternative?
