### ISSUE TITLE
OpenCV 3.1.x Release?

### ISSUE THREAD

**Issue by jlaura** [opencv/opencv#7329]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => OS X
##### Detailed description

A huge number of commits have occurred since the last release of OpenCV 3.1 (Dec. 2015).  Currently, the FLANN matcher is broken via the [Python bindings in the 3.1 release](https://github.com/opencv/opencv/issues/5667).  This has been fixed since Jan. 2016 in [PR#6009](https://github.com/opencv/opencv/pull/6009).  Unfortunately, down stream packagers that are pinning to releases (e.g. [conda-forge](https://github.com/conda-forge/opencv-feedstock/issues/31) and [conda-forge](https://github.com/conda-forge/opencv-feedstock/issues/29)) are not benefiting from all of the work this dev. group has done.

I completely understand that a 3.2 release may not be possible at this time, but is a 3.1.1 release possible?

**Comment by mshabunin** [comment]
From [answers.opencv.org](http://answers.opencv.org/question/101612/is-there-any-enthusiasm-for-making-point-releases-311/):

> We are going to release OpenCV 3.2 in Q4 2016. There are some infrastructure issues to be fixed and several features being developed at this moment.
> 
> Is there possibility to make custom release tags on your side, something like 3.1-conda-1.0? We test each change before integration and check binary compatibility, so I think it is possible to mark any commit as a release and use it in your distribution.

**Comment by jakirkham** [comment]
> Is there possibility to make custom release tags on your side, something like 3.1-conda-1.0? We test each change before integration and check binary compatibility, so I think it is possible to mark any commit as a release and use it in your distribution.

No that is not possible. It is required in [conda-forge]( https://conda-forge.github.io/ ) that builds only come from formal releases only. So unless an OpenCV release is tagged, we won't build it. In some cases patches can be applied if fixing a critical bug or build issue as long as they have been submitted upstream.

However the build resources required to get OpenCV built are quite demanding. Given these resources are shared with over 1200 other packages in conda-forge, it becomes impractical to attempt to build every patch for a bug fix that users request (no matter how reasonable they might be).

Please keep us posted on when the new release will be tagged. Thanks.

cc @patricksnape

**Comment by jlaura** [comment]
@mshabunin Thanks for the response.  How much overhead exists on the OpenCV side to do a 3.1.1 release given the response from @jakirkham.  This would be invaluable while we wait for the 3.2 release to drop.

**Comment by patricksnape** [comment]
Agreed. We simply don't have the computational nor human resources required to build per-commit OpenCV builds.

**Comment by johncant** [comment]
@patricksnape is this something you're interested in? Would you accept a PR that adds travis?

**Comment by patricksnape** [comment]
Adds travis to what? To build off of master? I personally don't want to support and debug master builds as the whole point of conda-forge is to provide binary builds of stable versions of software to users.

**Comment by johncant** [comment]
Never mind - I just found your CI: http://www.build.opencv.org/#/summary/ . Sorry for the noise.

**Comment by patricksnape** [comment]
That isn't our CI - that is the CI of the upstream OpenCV package. Note that this package is literally just code to produce a binary of OpenCV from release versions.

**Comment by PhilLab** [comment]
@mshabunin Can be closed, I suppose
