### ISSUE TITLE
Error undefined variable "cv" - Matlab

### ISSUE THREAD

**Issue by DNLFe** [opencv/opencv#7359]
##### System information (version)
- OpenCV => 2.4.13
- Operating System / Platform => Windows 10 64-Bit
- Compiler => Visual Studio 2012
##### Detailed description

I am trying to run a Matlab code using some OpenCV commands but I keep getting this error. What should I do? I already tried to install the OpenCV as in its guide following the 5 steps for Pre-built Libraries as follows but didn't work, I am probably missing or misunderstanding something. I would appreciate your help. Thank you guys in advance

http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html#windows-installation

![image](https://cloud.githubusercontent.com/assets/22517881/18948866/17cc2a68-8639-11e6-8b24-f91e51d0c625.png)

![image](https://cloud.githubusercontent.com/assets/22517881/18948875/22ed138a-8639-11e6-9a9c-e20ae8da0070.png)

![image](https://cloud.githubusercontent.com/assets/22517881/18948880/28eb01f2-8639-11e6-9c7a-d2e9e5c2a7a9.png)
##### Follows the Matlab error:

Undefined variable "cv" or class "cv.cvtColor".

Error in face_d_t_new (line 35)
gr = cv.cvtColor(videoFrame, 'RGB2GRAY');   

Error in HR (line 21)
[pos, distance] = face_d_t_new(vid_name, fr, s);

**Comment by StevenPuttemans** [comment]
Wow wait, Matlab is not built by default if you download OpenCV. You will need to rebuilt OpenCV from scratch. Also, general questions like this should be addressed at http://answers.opencv.org/questions/

**Comment by DNLFe** [comment]
I am sorry, I don't think I got what you mean. I've trying to connect them (Matlab and OpenCV). And thanks for the hint, I will post it there. @StevenPuttemans

**Comment by StevenPuttemans** [comment]
Basically what I mean is that the downloadable prebuilt packages of OpenCV do NOT provide a link to matlab, so you cannot call it from matlab itself. In order to build Matlab support, take a look [here](https://github.com/opencv/opencv_contrib/tree/master/modules/matlab)

**Comment by DNLFe** [comment]
Ok. So I need to do is basically download opencv_contrib and CMake and build the Matlab module? What does "rebuilt from scratch" means?

**Comment by StevenPuttemans** [comment]
Yes thats it. Rebuilding from scratch means you download both repositories in code from github and then build the binaries yourself using cmake.
