### ISSUE TITLE
Compilation of interactive-calibration failing on clean install and build

### ISSUE THREAD

**Issue by squeakus** [opencv/opencv#7362]
OpenCV => 3.1
Operating System / Platform => Ubuntu 16.04 64 Bit
Compiler => gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

##### Detailed description
I am trying to install opencv3.1 on a freshly installed machine and I am getting the following error:
/home/jonathan/data/linuxapps/opencv/apps/interactive-calibration/main.cpp:185:119: error: cannot convert ‘cv::Mat’ to ‘int’ for argument ‘9’ to ‘double cv::aruco::calibrateCameraCharuco(cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::Ptr<cv::aruco::CharucoBoard>&, cv::Size, cv::InputOutputArray, cv::InputOutputArray, cv::OutputArrayOfArrays, cv::OutputArrayOfArrays, int, cv::TermCriteria)’
                                                            globalData->perViewErrors, calibrationFlags, solverTermCrit);

It is either a bug in the code or some sort of compiler issue, any ideas what could be causing this?

**Comment by mshabunin** [comment]
Which version of `opencv_contrib` do you use? It should be 3.1 too.
If you want to use latest version of `opencv_contrib` than you need to take the latest version of `opencv`.

**Comment by squeakus** [comment]
Yep,that was it, I somehow managed to pull down the wrong version. Thanks for your help!
