### ISSUE TITLE
no ref count on CvBoost class

### ISSUE THREAD

**Issue by saykou** [opencv/opencv#7363]
##### System information (version)

- OpenCV => 2.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
##### Detailed description

`CvBoost` class does not have ref count hence when is passed by copy to a function, it is destroyed at the end of the function and it is also destroyed later by caller, giving error.
##### Steps to reproduce

```
void something(cv::Boost booster){}


int main()
{

  cv::Boost booster;
  booster.load(boostFile);
  something(booster);

}
```

**Comment by sovrasov** [comment]
Generally OpenCV classes have no refcounts (except cv::Mat). Instead of it use cv::Ptr:

> void something(cv::Ptr<<cv::Boost>> booster){}
> int main()
> {
> 
>   cv::Ptr<<cv::Boost>> booster(new cv::Boost());
>   booster->load(boostFile);
>   something(booster);
> 
> }
