### ISSUE TITLE
Kinect V2 Errors

### ISSUE THREAD

**Issue by ashokbugude** [opencv/opencv#7366]
I am using Linux 16.04 and opencv 3.1.0

I have written the below code

#include \<opencv2/videoio/videoio.hpp\>
using namespace cv;
int main(int argc,char* argv[])
{
VideoCapture capture(CAP_OPENNI2);
}

and I get the errors as shown in screemshot . Please help resolve the issues
![opencverror](https://cloud.githubusercontent.com/assets/10016848/18982586/e3eb9a68-8704-11e6-87a0-10e35ead592b.png)

**Comment by alalek** [comment]
Please replace screenshot with direct output.

**Comment by ashokbugude** [comment]
Thanks for your response.
The output of CodeBlocks Console cannot be copy pasted

**Comment by StevenPuttemans** [comment]
@ashokbugude thats not true, you can select output in a window, just by placing a system('wait'); so that it does not closes if you hit a key!

**Comment by ashokbugude** [comment]
Below is the text message

zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Ashok/codeBlocksWS/opencvDepthTest/biDebug$ ./opencvDepthTest 
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 9 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:7 with serial 019267343647
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 9 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:7 with serial 019267343647
[Info] [Freenect2Impl] found 1 devices
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
[Info] [VaapiRgbPacketProcessorImpl] driver: Intel i965 driver for Intel(R) Skylake - 1.7.0
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 2016384 ir: 608*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
OpenCV Error: Unspecified error (CvCapture_OpenNI2::CvCapture_OpenNI2 : Couldn't set color stream output mode: Stream setProperty(3) failed

) in toggleStream, file /home/zayyon/Downloads/opencv-master/modules/videoio/src/cap_openni2.cpp, line 303
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] releasing usb interfaces...
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
VIDEOIO(cvCreateCameraCapture_OpenNI2(index)): raised OpenCV exception:

/home/zayyon/Downloads/opencv-master/modules/videoio/src/cap_openni2.cpp:303: error: (-2) CvCapture_OpenNI2::CvCapture_OpenNI2 : Couldn't set color stream output mode: Stream setProperty(3) failed

in function toggleStream

**Comment by alalek** [comment]
Text message is required to allow search in case of similar problems.

Looks like error is coming from internals of OpenNI2 library. What version of OpenNI2 do you use?
Are you able to use your device via OpenNI2 tools directly (viewer)? What resolution and mode is used in these tools?

Current OpenCV implementation assumes that device support 640x480x30fps RGB888 mode. Could you try to use other numbers [here](https://github.com/opencv/opencv/blob/63280767f16bf57634623f344d3911fd547b33d3/modules/videoio/src/cap_openni2.cpp#L182-L200)?

**Comment by ashokbugude** [comment]
What version of OpenNI2 do you use?  
Openni 2.2 

Are you able to use your device via OpenNI2 tools directly (viewer)?
No, Found that Openni/openni2 does not support KinectV2 ; http://stackoverflow.com/questions/27465516/does-openni-2-2-support-kinect-v2

I am not sure why the debug messages say , found a valid device as shown below

[Info] [Freenect2Impl] found valid Kinect v2 @2:7 with serial 019267343647
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 9 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:7 with serial 019267343647
[Info] [Freenect2Impl] found 1 devices
