### ISSUE TITLE
Compilation error on armhf architecture

### ISSUE THREAD

**Issue by mescarra** [opencv/opencv#7375]
##### System information
- OpenCV => master branch
- Operating System / Platform => Ubuntu 14.04 / armhf (Jetson TX1)
- CUDA version => 8.0 (Jetpack 2.3)
- Compiler => g++

##### Detailed description

Compilation error:

`/home/ubuntu/opencv-3.1.0/modules/core/include/opencv2/core/cvdef.h(320): error: identifier "__fp16" is undefined`

I'm forced to compile the master branch because release 3.1.0 won't compile due to its lack of support for CUDA-8.0.

##### Steps to reproduce

```
git clone https://github.com/opencv/opencv.git opencv-3.1.0
cd opencv-3.1.0
mkdir release
cd release
cmake .. -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF
make -j4
```

**Comment by alalek** [comment]
Is this error message from CUDA compiler?

Could you try to replace this line (cvdef.h:310)?
```
//#if defined (__ARM_FP16_FORMAT_IEEE)
#if defined (__ARM_FP16_FORMAT_IEEE) && !defined __CUDACC__
```

**Comment by mescarra** [comment]
Well, it seems that solved it. Source is still compiling but already passed its breaking point.
