### ISSUE TITLE
cv::cuda::integral invalid when width is certain multiples of 16

### ISSUE THREAD

**Issue by bmstoyon** [opencv/opencv#7378]
##### System information (version)

OpenCV => 3.1
Operating System / Platform => Windows 64 Bit & centos 7
Compiler => Visual Studio 2015 & gcc
##### Detailed description

cv::cuda::integral is sometimes incorrect when the width of the image is a multiple of 16. It seems to be every 3 out of 4 multiples of 16 and the bug looks like it is in horisontal_pass_8u_shfl_kernel.

https://github.com/opencv/opencv/blob/master/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp#L169
##### Steps to reproduce

Add 16x16 test case to accuracy test.

```
CUDA_TEST_P(Integral, Accuracy)
{
    cv::Mat src = randomMat(size, CV_8UC1);

    cv::cuda::GpuMat dst = createMat(cv::Size(src.cols + 1, src.rows + 1), CV_32SC1, useRoi);
    cv::cuda::integral(loadMat(src, useRoi), dst);

    cv::Mat dst_gold;
    cv::integral(src, dst_gold, CV_32S);

    EXPECT_MAT_NEAR(dst_gold, dst, 0.0);
}

INSTANTIATE_TEST_CASE_P(CUDA_Arithm, Integral, testing::Combine(
    ALL_DEVICES,
    testing::Values(cv::Size(16, 16), cv::Size(128, 128), cv::Size(113, 113), cv::Size(768, 1066)),
    WHOLE_SUBMAT));
```

**Comment by PorscheFanatic7** [comment]
I tested locally, and it seems the below proposed fix resolves this issue:

https://github.com/opencv/opencv/blob/master/modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp#L601

Change `cols % 16` to `cols % 64`.
