### ISSUE TITLE
Valgrind warning in icvGetPropertyCAM_V4L

### ISSUE THREAD

**Issue by kesinger** [opencv/opencv#7380]
- OpenCV => recent-ish top-of-master, last commit 473dba118978f8fd899759378847d7730adae1bd
- Operating System / Platform => Linux (Ubuntu 16.04)
- Compiler => gcc 5.4.0

##### Detailed description

When running an opencv app under valgrind,  I get a warning about uninitialized bytes in ioctl:
```
==16431== Syscall param ioctl(VKI_V4L2_G_FMT).fmt.pix.priv points to uninitialised byte(s)
==16431==    at 0x7BF4687: ioctl (syscall-template.S:84)
==16431==    by 0x5F85F32: cv::icvGetPropertyCAM_V4L(cv::CvCaptureCAM_V4L const*, int) [clone .constprop.12] (in ...)
```

the code looks like:
```     
      v4l2_format form; // line 1582
      form.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
      if (-1 == ioctl (capture->deviceHandle, VIDIOC_G_FMT, &form)) {
```

One way to silence the warning is to explicitly clear out form:
```
      v4l2_format form;
      memset(&form, 0, sizeof(v4l2_format));
      form.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
      if (-1 == ioctl (capture->deviceHandle, VIDIOC_G_FMT, &form)) {
```

**Comment by mshabunin** [comment]
@kesinger , could you please create pull request with the fix?
