### ISSUE TITLE
Python bindings linker error during DEBUG build "python35_d.lib"

### ISSUE THREAD

**Issue by sverrirs** [opencv/opencv#7395]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 7 64bit
- Compiler => Visual Studio 2015

##### Detailed description

Error building both Python2 and Python3 libraries in debug builds. Linker complains that the debug lib (e.g. "python35_d.lib") file cannot be found. 

The python *_d.lib are used when #DEBUG is defined.

Solution according to the official python bug tracker and verified by myself locally.
```
#ifdef _DEBUG
#undef _DEBUG
#include <Python.h>
#define _DEBUG
#else
#include <Python.h>
#endif
```

https://bugs.python.org/issue22411

##### Steps to reproduce

Build OpenCV in 32bit debug build

**Comment by alalek** [comment]
It is not an error.

You just need to install Python "_d.lib". Modern Python Windows installer allows to select installation of debug components (check [message](https://bugs.python.org/msg241155) 241155 by your [link](https://bugs.python.org/issue22411)). Or your need to build Python debug library from sources.

Replacing debug library with release version is dangerous and not recommended - especially in case of MSVC runtime libraries (this is also discussed in mentioned Python issue).

**Comment by sverrirs** [comment]
Thank you for the reply Alexander. Indeed you're right, there is an option to install the debug version of python in the installer. I may have misunderstood the python thread I linked and the accompanying video as I believed that linking to the release python.lib would be OK and I thought it might save some people the same headache as I had yesterday :) 

Cheers!
