### ISSUE TITLE
up YUV implemented incorrectly

### ISSUE THREAD

**Issue by aleksey-nikolaev** [opencv/opencv#7396]
##### System information (version)
- OpenCV = 3.1.0

##### Detailed description

- Сould you fix this [very old bug](https://github.com/opencv/opencv/issues/4946#issuecomment-250528658)?

- Explain please which byte order used in opencv for YUV and YCrCb. Not now, but as it should be in truth.

**Comment by StevenPuttemans** [comment]
There is no reason in opening up the same issue again, if it is already open. It will simply get closed down. Adding the info at the other issue, like you did, shall help fastening the process of getting the fix in. But providing a fix yourself through a PR will get you there even faster!
