### ISSUE TITLE
Illegal array access in makeAgastOffsets

### ISSUE THREAD

**Issue by kesinger** [opencv/opencv#7406]
##### System information (version)

- OpenCV => d3930cdee1a0c7124045883b3062f25b3027fa97
- Operating System / Platform => OSX / 10.10
- Compiler => clang
##### Detailed description

In makeAgastOffsets, there is a 16-long for-loop that indexes past the end of an 8- or 12-element array.

In particular, this part:
  for( ; k < 16; k++ ) 
               pixel[k] = offsets[k][0] + offsets[k][1] \* rowStride;

When makeAgastOffsets is called with a value of type that is NOT AgastFeatureDetector::OAST_9_16, such as AgastFeatureDetector::AGAST_5_8, the "offsets" array is 8 or 12 elements long, not 16, and the code will attempt to read past the end off "offsets"

##### Steps to reproduce

Build opencv with "-fsanitize=address", and then call something that eventually goes into makeAgastOffsets, such as cv::BRISK_Impl::detectAndCompute and watch what the values going into pixels[k] are.

**Comment by StevenPuttemans** [comment]
@cbalint13 I guess you implemented the current running version of AGAST and it is fairly reasonable to get this fixed?
