### ISSUE TITLE
Documentation of medianBlur does not mention borderType

### ISSUE THREAD

**Issue by Arnoques** [opencv/opencv#7407]
##### System information (version)

- OpenCV => 2.4.9.1
- Operating System / Platform => xubuntu
- Compiler => no idea

##### Detailed description

The documentation for medianBlur (http://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html?highlight=median#cv2.medianBlur) fails to mention what happens to the borders. I think this is important because a first glance through the docs led me to believe that it would use `BORDER_DEFAULT`. After noticing this is not the case, it took me a while to find the correct answer in the source. In the case I was interested in, it uses `BORDER_REPLICATE` (https://github.com/opencv/opencv/blob/eddd417d74ab1b899fbd327c8dccf7429d26583b/modules/imgproc/src/smooth.cpp#L3113)

Please update the docs to include this. I know it's a detail, but it's the kind of detail good documentation should tell.

##### Steps to reproduce

```.py
from numpy import *
import cv2

orig = arange(7*8).reshape((7,8)).astype(uint8)
cvmedian = cv2.medianBlur(orig, 7)

data_portion = orig[:4, :4].copy()
border_default = cv2.copyMakeBorder(data_portion,3,0,3,0,cv2.BORDER_DEFAULT)
assert(median(border_default) != cvmedian[0,0])

border_replicate = cv2.copyMakeBorder(data_portion,3,0,3,0,cv2.BORDER_REPLICATE)
assert(median(border_replicate) == cvmedian[0,0])
```

**Comment by StevenPuttemans** [comment]
Euhm, since the function is not even requiring a border handling parameter, why it is important to mention this. I think from a general point of view, adding a comment about border handling will make it more complex for users if it is not a configurable parameter.

**Comment by Arnoques** [comment]
> Oh and BTW why use 2.4 docs? Any specific reason not to use the latest 3.x docs?

No reason... I didn't notice it was a different one when I sent the link.

I think it's important to mention it because even if it's not a choice the user has, it was a choice that the writer of the code did make, and it affects the results.

In my specific case, I was modifying a function that used `cv2.medianBlur` and extracted just a single pixel from it. I wanted to replace the function with `np.median` of the area around the pixel to make it faster, and noticed it didn't give me the same results near the border (pretty much like in the code above). After trying to find the reason in the docs, I had to find the source and understand it (at least a little) to find the way to solve this problem. It took me a while since my C++ is close to non-existent. 

If there was a short mention of this in the docs, all of that would've been much faster.

**Comment by StevenPuttemans** [comment]
Submitted a documentation fix with the suggested mention. Lets see how the devs are considering this.

**Comment by Arnoques** [comment]
Thanks!
