### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by Ruturaj001** [opencv/opencv#7409]
principal and principle used to refer same points in http://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
[Link](http://docs.opencv.org/master/d9/d0c/group__calib3d.html) to actual documentation.
