### ISSUE TITLE
opencv_dnn produce errors when a thirdparty also links against protobuf

### ISSUE THREAD

**Issue by agilmor** [opencv/opencv#7425]
##### System information (version)

- OpenCV => 3.1 (and probably 3.0)
- Operating System / Platform => Debian Jessie (and others)
- Compiler => Gcc 4.9 (and probably others)
##### Detailed description

When using OpenCV DNN with Caffe, both linking against Protobuf the following error apears:

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1272] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
```

And then a `std::terminate` is thrown by protobuf.

Some people reported that its a problem with dynamic linking against Protobuf, but in my experience it also happen using static linking.

I'm not sure if the problem is in OpenCV, in Protobuf, or in Caffe.
But [the current workaround is disable OpenCV DNN](https://github.com/BVLC/caffe/issues/1917#issuecomment-214501151).
Is the problem really there, in opencv_dnn? Can we solve it?
##### Steps to reproduce

Build OpenCV with DNN.
Build Caffe with pycaffe or matcaffe.
In caffe, just run something like:

```
$ matlab -nodesktop -r "addpath ./matlab/; caffe.set_mode_cpu();"
```

And you will get the `std::terminate`.

Similar commands with pycaffe also reproduce this error.

Thanks!

**Comment by mshabunin** [comment]
@agilmor , please submit this issue to the https://github.com/opencv/opencv_contrib repository.

**Comment by dkurt** [comment]
@alalek, is that solved by https://github.com/opencv/opencv/pull/10139 like https://github.com/opencv/opencv/pull/10140?
