### ISSUE TITLE
openCV_FOUND fails, unless manually set to 1

### ISSUE THREAD

**Issue by Jatentaki** [opencv/opencv#7435]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Xubuntu 16.04 LTS
- Compiler => c++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

##### Detailed description

I had some trouble installing openCV from source, uninstalling and reinstalling it several times and most likely making a bit of a mess on my machine. However in the end I had a working python installation, but the C++ [example](http://docs.opencv.org/3.1.0/db/df5/tutorial_linux_gcc_cmake.html) would consistently fail at cmake with
```
Found package configuration file:

    /usr/local/share/OpenCV/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
```
there are a million threads on this issue around the Internet, but what eventually worked for me was to simply ``` set( OpenCV_FOUND 1 ) ```. This means that the condition checks in OpenCVConfig.cmake are acting weird and rejecting a correct request.

##### Steps to reproduce
Switch on/off the OpenCV_FOUND flag in
```
cmake_minimum_required(VERSION 2.8)
project( DisplayImage )

set( OpenCV_DIR /usr/local/include )
set( OpenCV_FOUND 1 )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( DisplayImage DisplayImage.cpp )
target_link_libraries( DisplayImage ${OpenCV_LIBS} )
```

**Comment by alalek** [comment]
What installation tutorial do you use?

1. Cleanup your build directory and re-run CMake again.

2. Dump contents of "version" file from this directory:
> /usr/local/share/OpenCV/OpenCVConfig.cmake

3. This is completely wrong:
> set( OpenCV_DIR /usr/local/include )

**Comment by Jatentaki** [comment]
0) http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html Thing is I missed the 'make install' part initially, so it was obviously not working. And without realising this I tried different things, perhaps introducing some strange configuration in different places
1) Done
2) If I understand properly what you are asking for (this is not a directory, and /usr/local/share/OpenCV doesn't contain a version file)
```
# ======================================================
#  Version variables:
# ======================================================
SET(OpenCV_VERSION 3.1.0)
SET(OpenCV_VERSION_MAJOR  3)
SET(OpenCV_VERSION_MINOR  1)
SET(OpenCV_VERSION_PATCH  0)
SET(OpenCV_VERSION_TWEAK  0)
SET(OpenCV_VERSION_STATUS "-dev")
```
3) Perhaps, that's a result of me trying different things. After cleaning up and re-running CMake I can skip this line (remove it), and it still either works with set( OpenCV_FOUND 1 ), or doesn't without

**Comment by alalek** [comment]
2) I mean file with contents like this:
https://github.com/opencv/opencv/blob/master/cmake/templates/OpenCVConfig-version.cmake.in

**Comment by Jatentaki** [comment]
```
set(OpenCV_VERSION 3.1.0)
set(PACKAGE_VERSION ${OpenCV_VERSION})

set(PACKAGE_VERSION_EXACT False)
set(PACKAGE_VERSION_COMPATIBLE False)

if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
  set(PACKAGE_VERSION_EXACT True)
  set(PACKAGE_VERSION_COMPATIBLE True)
endif()

if(PACKAGE_FIND_VERSION_MAJOR EQUAL 3
   AND PACKAGE_FIND_VERSION VERSION_LESS PACKAGE_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE True)
endif()
```

**Comment by alalek** [comment]
Thanks! File contents seems valid.
Could you dump output of cmake command with `--trace-expand` option (you can use https://gist.github.com/ to share output)?

**Comment by Jatentaki** [comment]
[Output](https://gist.github.com/Jatentaki/6b8db717528bfadfda46e8e7ca8aba8b) of ```cmake --trace-expand``` with OpenCV_FOUND left not set
[Output](https://gist.github.com/Jatentaki/36317bd0ce2d6f580f104ea668446427) with OpenCV_FOUND set to 1

**Comment by alalek** [comment]
I didn't see place in trace log where OpenCV_FOUND is used, but CMake says:
> but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
> NOT FOUND

So, looks like OpenCV_FOUND is set to false somewhere else.

Add `message("OpenCV_FOUND='${OpenCV_FOUND}'"` before and after find_package statement (without any `set( OpenCV_FOUND 1 )`) and check output.

This
> /home/jatentaki/Programs/mrowki2/CMakeLists.txt

and this
> -- Build files have been written to: /home/jatentaki/Programs/mrowki2

says that you don't use separate build directory. This is a bad practice to mix build and source files.

Try to run this:
```
grep -R OpenCV_FOUND /home/jatentaki/Programs/mrowki2/
```

**Comment by wangjhit** [comment]
I think you should 

> set（OpenCV_DIR  /path/to/opencv/build）

instead of 
>set( OpenCV_DIR /usr/local/include )

I had the same problem,but now my problem has been solved.
I hope it will help you.

**Comment by Salmanshams67** [comment]
Downloading the latest version of MinGW worked for me.
link: `https://sourceforge.net/projects/mingw-w64/files/`

**Comment by MDSALMANSHAMS** [comment]
Downloading the latest version of MinGW worked for me.
link: `https://sourceforge.net/projects/mingw-w64/files/`
