### ISSUE TITLE
Critical Typo in the document 'Installation in Linux' 

### ISSUE THREAD

**Issue by MalcolmReynlods** [opencv/opencv#7437]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04 LTS 64 Bit
- Compiler => g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) , cmake version 3.5.1
##### Detailed description

I tried to install openCV for my system by following instructions from the link:
http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation but I was unsuccessful. When I tried again by omitting the white space between the '-D' and 'CMAKE_BUILD_TYPE' , 'CMAKE_INSTALL_PREFIX' it worked! It would be very helpful if someone could take a look into this issue. Since it is a very crucial step for installing openCV, I think this has high priority. 
##### Steps to reproduce

Try to install openCV on an Ubuntu system by following the steps from: http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation. Thus check for the white space issue I have mentioned above.

**Comment by alalek** [comment]
There is several opposite patches:
- https://github.com/opencv/opencv_contrib/pull/250
- https://github.com/opencv/opencv_contrib/pull/320
And patch like your suggestion:
- https://github.com/opencv/opencv/pull/6881

But, I'm not able to reproduce problem, both cases work perfect for me.
We use syntax without spaces for years in out buildbot. Syntax with space is CMake tool mainline (check `cmake --help`).

Are you able to reproduce problem from clean build directory?

**Comment by mshabunin** [comment]
I suggest adding a note to the documentation with possible command line variants (with/without space).

**Comment by euler16** [comment]
I am a beginner, can I try this ( I am not sure if I will be able to complete it but I want to start contributing to open source)

**Comment by mshabunin** [comment]
@euler16 , sure. You have to add a note describing possible cmake command line variants to the linux install tutorial:
- master - [doc/tutorials/introduction/linux_install/linux_install.markdown](https://github.com/opencv/opencv/blob/master/doc/tutorials/introduction/linux_install/linux_install.markdown)
- 2.4 - [doc/tutorials/introduction/linux_install/linux_install.rst](https://github.com/opencv/opencv/blob/2.4/doc/tutorials/introduction/linux_install/linux_install.rst)

**Comment by parismita** [comment]
i did 
cmake \<path\>  #works
cmake \<path\> \<option\>=\<value\> #didnt work
cmake \<option>=\<value\> \<path> #work 
cmake -D \<option\>=\<value\> <path> #work 

i think the problem is not with space and -D, its with providing path befour providing the option , 

-D<option> do not give error as while giving so, the <option> becomes invalid and is not considered as command hencewritting
cmake \<path\> -D\<option\>=\<value\> is same as writting cmake \<path\>

**Comment by spankr** [comment]
I can't wait to see this one live!
