### ISSUE TITLE
Why latest release is  OpenCV 2.4.13 is not  OpenCV 3.1。

### ISSUE THREAD

**Issue by kingroc711** [opencv/opencv#7444]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
Why latest release is  OpenCV 2.4.13 is not  OpenCV 3.1。

**Comment by alalek** [comment]
Because GitHub sorts releases by date instead of version (which is not best choice too).
I can't find any flag to mark the release "latest", so currently there is no way to fix it on our side.
