### ISSUE TITLE
2.4.13 download link for android missing on opencv.org

### ISSUE THREAD

**Issue by berak** [opencv/opencv#7445]
http://opencv.org/downloads.html is missing the [2.4.13 link for android](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/2.4.13.1/)

**Comment by berak** [comment]
not really an issue, i guess, just leaving a note.

**Comment by alalek** [comment]
There are no Android SDK packages for 2.4.12 and 2.4.13 releases due some build issues. The latest version of Android SDK for OpenCV 2.4.13.1 is available here: https://sourceforge.net/projects/opencvlibrary/files/opencv-android/2.4.13.1/

**Comment by berak** [comment]
ooh, on purpose, then.

thanks a lot for the clarification !
