### ISSUE TITLE
Implicit declaration if function in C99 - Xcode + IOS 10 + cocoapod 

### ISSUE THREAD

**Issue by linked67** [opencv/opencv#7448]
- OpenCV => 3.1.0.1
- Operating System / Platform => MacOS sierra
- Compiler => Xcode

##### Detailed description

I use cocoapod to install opencv in my project. I had no problem with opencv 2+, only with the 3+ version. The error message i get when i try to build my IOS projet:

Implicit declaration of function 'cvRound' is invalid in C99 (in file types_c.h)

With a brand new project there is no error until i switch the minimum IOS version from 10.0 to 8.0. I don't know if it bug with IOS 9.0 too because even if i put IOS10.0 back, i still get the error.

Any idea ?

**Comment by alalek** [comment]
Add list of used #includes / #imports from failed source file.

**Comment by linked67** [comment]
This is in the types_c.h (this file is in the opencv framework):

```
#ifndef __OPENCV_CORE_TYPES_H__
#define __OPENCV_CORE_TYPES_H__

#ifdef HAVE_IPL
#  ifndef __IPL_H__
#    if defined WIN32 || defined _WIN32
#      include <ipl.h>
#    else
#      include <ipl/ipl.h>
#    endif
#  endif
#elif defined __IPL_H__
#  define HAVE_IPL
#endif

#include "opencv2/core/cvdef.h"

#ifndef SKIP_INCLUDES
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#endif // SKIP_INCLUDES

#if defined WIN32 || defined _WIN32
#  define CV_CDECL __cdecl
#  define CV_STDCALL __stdcall
#else
#  define CV_CDECL
#  define CV_STDCALL
#endif

#ifndef CV_DEFAULT
#  ifdef __cplusplus
#    define CV_DEFAULT(val) = val
#  else
#    define CV_DEFAULT(val)
#  endif
#endif

#ifndef CV_EXTERN_C_FUNCPTR
#  ifdef __cplusplus
#    define CV_EXTERN_C_FUNCPTR(x) extern "C" { typedef x; }
#  else
#    define CV_EXTERN_C_FUNCPTR(x) typedef x
#  endif
#endif

#ifndef CVAPI
#  define CVAPI(rettype) CV_EXTERN_C CV_EXPORTS rettype CV_CDECL
#endif

#ifndef CV_IMPL
#  define CV_IMPL CV_EXTERN_C
#endif

#ifdef __cplusplus
#  include "opencv2/core.hpp"
#endif
```

**Comment by alalek** [comment]
Could you include "opencv2/core.hpp" before other OpenCV headers (with `_c` suffix)?
C API is deprecated and can't be used as standalone API. Also it can't be used in C compiler (C++ is supported only).

**Comment by linked67** [comment]
core.hpp

```
#ifndef __OPENCV_CORE_HPP__
#define __OPENCV_CORE_HPP__

#ifndef __cplusplus
#  error core.hpp header must be compiled as C++
#endif

#include "opencv2/core/cvdef.h"
#include "opencv2/core/version.hpp"
#include "opencv2/core/base.hpp"
#include "opencv2/core/cvstd.hpp"
#include "opencv2/core/traits.hpp"
#include "opencv2/core/matx.hpp"
#include "opencv2/core/types.hpp"
#include "opencv2/core/mat.hpp"
#include "opencv2/core/persistence.hpp"
```

This is what i use in a file that call opencv:

```
#ifdef __cplusplus
#import <opencv2/opencv.hpp>
#endif

#ifdef __OBJC__
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#endif


#include <opencv2/highgui/highgui_c.h>
#include <opencv2/imgproc/imgproc_c.h>

#include <opencv2/imgcodecs/imgcodecs_c.h>
#include <opencv2/core/core_c.h>
```
Maybe i can replace these includes / import with something the compiler understand better ?
It's a bit hard to find information on headers to include for IOS .

**Comment by alalek** [comment]
I believe this guard hides real problem:
```
#ifdef __cplusplus
#import <opencv2/opencv.hpp>
#endif
```

It is possible to use C++ code from .mm files (possibly you need to enable "Objective-C++" compiler in Xcode).

**Comment by linked67** [comment]
Oh thanks a lot for the tip. I have move the import from .h file to the .mm file and it compile fine now.

I was thinking that the header use the same compile option as the .mm of the same name. Looks like i was wrong.
