### ISSUE TITLE
findContours crashes on very large images

### ISSUE THREAD

**Issue by reunanen** [opencv/opencv#7449]
##### System information (version)
- OpenCV => 2.4.13 (official binaries)
- Operating System / Platform => Windows, 64-bit
- Compiler => Visual Studio 2013, Update 4

##### Detailed description
Function findContours crashes my program for very large images (e.g. 79925 * 49955), apparently regardless of the image contents.

##### Steps to reproduce
Code:

    cv::Mat largeImage(79925, 49955, CV_8UC1);
    largeImage.setTo(0);
    
    // this is not really even needed to reproduce
    cv::circle(largeImage, cv::Point(largeImage.cols, largeImage.rows), 1000, 255, CV_FILLED);

    std::vector<std::vector<cv::Point>> contours;
    cv::findContours(largeImage, contours, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_SIMPLE);

The last line crashes the program. Works great for smaller images (didn't find the exact limit though).

I don't think I'm running out of memory (have multiple gigabytes left), and even if I was, it'd be better to receive an exception of course.

Can anyone reproduce this?

Haven't tried on version 3 yet.

**Comment by reunanen** [comment]
Seems to be coming from [here](https://github.com/opencv/opencv/blob/975d2e4294e4eac113be996c2e6a8abf4d951c36/modules/imgproc/src/contours.cpp#L312):

The calculation `step * (size.height - 1)` overflows (the type is `int`).

**Comment by kobermann** [comment]
This problem is still present in 4.5.1. Function crashes reproducible on a CV_8U matrix, resolution: 3456x2304
