### ISSUE TITLE
drawContours fails for very large images

### ISSUE THREAD

**Issue by reunanen** [opencv/opencv#7458]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013
##### Detailed description

For very large images, the drawContours function does not produce the expected results.

See also #7449 – probably related. However, drawContours does not crash the program – it just produces an incorrect result.
##### Steps to reproduce

Please note that you'll need to have merged at least one of #7451 and #7452, because otherwise already the `findContours` call crashes the program:

```
cv::Mat largeImage(79925, 49955, CV_8UC1);
largeImage.setTo(0);

cv::circle(largeImage, cv::Point(largeImage.cols / 2, largeImage.rows / 2), 5000, 255, CV_FILLED);

std::vector<std::vector<cv::Point>> contours;
cv::findContours(largeImage, contours, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_SIMPLE);

largeImage.setTo(0);
cv::drawContours(largeImage, contours, -1, 255, CV_FILLED);

cv::Mat smallImage;
cv::resize(largeImage, smallImage, cv::Size(499, 799));

cv::imwrite("smallImage.png", smallImage);
```

Result (not ok):
![smallimage](https://cloud.githubusercontent.com/assets/2297572/19273301/ae33676a-8fd4-11e6-99b0-5ff54eb341db.png)

However, this code does work as expected (when pasted right after the above snippet, so that `contours` has already been found):

```
std::vector<std::vector<cv::Point>> contours2 = contours;
for (auto& contour : contours2) {
    for (auto& point : contour) {
        point.x /= 100;
        point.y /= 100;
    }
}

cv::Mat smallImage2(smallImage.size(), CV_8UC1);
smallImage2.setTo(0);
cv::drawContours(smallImage2, contours2, -1, 255, CV_FILLED);
cv::imwrite("smallImage2.png", smallImage2);
```

Result (ok):
![smallimage2](https://cloud.githubusercontent.com/assets/2297572/19273302/ae3367ec-8fd4-11e6-8dad-72ce62064e19.png)

I'll try to find and fix the problem myself.

**Comment by sturkmen72** [comment]
i think this can be closed down.
