### ISSUE TITLE
Stitching : exposure is not compensated before seam finding

### ISSUE THREAD

**Issue by Tytan** [opencv/opencv#7459]
##### System information (version)
- OpenCV => 3.1

##### Related code : (modules/stitching/src/stitcher.cpp)
```.cpp
    for (size_t i = 0; i < imgs_.size(); ++i)
        images_warped[i].convertTo(images_warped_f[i], CV_32F);

    LOGLN("Warping images, time: " << ((getTickCount() - t) / getTickFrequency()) << " sec");

    // Find seams
    exposure_comp_->feed(corners, images_warped, masks_warped);
    seam_finder_->find(images_warped_f, corners, masks_warped);
```

Exposure compensation is calculated on warped images.
Seams are determined using the same warped images (except they have been converted to CV_32F). No exposure compensation have been applied to these images.

### Why is it bad ?

> Exposure differences can also confuse the previously
described de-ghosting algorithm, causing it to interpret
differences across images as moving objects. Thus, it is
important to have an exposure compensation step prior
to de-ghosting.

_Source :_ M. Uyttendaele, A. Eden, and R. Szeliski. Eliminating ghosting and exposure artifacts in image mosaics. In Proc. CVPR’01, volume 2, pages 509–516, 2001 - Page 4, §3

### Fix

The fix is quite simple, and doesn't require much resources as the images used for seam finding and exposure compensation estimation are usually decimated a lot.
Am I right to think this behavior has to be fixed or is it intended ?

**Comment by mshabunin** [comment]
cc @vpisarev
