### ISSUE TITLE
Add 5.2 and 6.1 for default CUDA_ARCH_BIN

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7463]
Currently after cloning the latest repo and do 

``````
ccmake ..
``````

In the CUDA_ARCH_BIN section it by defaults only shows 3.0 3.5 3.7 5.0 6.0. I suggest adding in 5.2 (for Maxwell Titans) and 6.1 (Pascals) in there.

**Comment by StevenPuttemans** [comment]
Actually 5.2 and 6.1 are very specific CUDA architectures. If enabled by default, people having a cuda development platform not supporting the architecture will run into problems there due to architecture specific commands. I would thus avoid adding these ... this has been requested in the past I think. Let me look it up and get back to you.

**Comment by StevenPuttemans** [comment]
Oh btw it seems that if you want to use non-specified architectures you need to run

`-DCUDA_GENERATION="" -DCUDA_ARCH_BIN="5.2" -DCUDA_ARCH_PTX="5.2"`

**Comment by jasjuang** [comment]
Yes I am manually specifying 5.2 is ccmake if my machine is having a Maxwell Titan GPU. It will be great to have it by default so I don't have to do it manually. Adding 5.2 or 6.1 would not cause any problems to people that does not have a Maxwell titan or Pascal. If people have a 3.5 GPU, in run time it will just select the 3.5 SASS architecture to execute it.

**Comment by StevenPuttemans** [comment]
Are you sure about this. I have a 3.5 compute capability myself and if I run all architectures by default, I am not always able to build the complete library...

**Comment by jasjuang** [comment]
Yes I am pretty sure about this. I just test rebuilding my opencv with a 3.5 compute capability GPU with 5.2 and 6.1 added in and it builds and runs without a problem. The only possible situation I can imagine this failing is if an older version of CUDA like 7.5 version is used, it won't be able to recognize compute capability 6.1, but it won't be able to recognize compute capability 6.0 (which is there by default ) either.

**Comment by StevenPuttemans** [comment]
Aha! But the case of CUDA7.5 compiling the 6.0 should not happen. It is only selected if you have 8 minimal, as seen [here](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/cmake/OpenCVDetectCUDA.cmake#L94). If you want I can add the 5.2 and 6.1 prerequisites there as default values.

**Comment by StevenPuttemans** [comment]
The supplied PR will give add your feature request!
