### ISSUE TITLE
opencv_ffmpeg not detecting openh264_1.5.0 dll in the same directory

### ISSUE THREAD

**Issue by AssemblerX64** [opencv/opencv#7473]
OpenCV 2.4.13
Visual Studio 2012
Windows 8.1 Pro x64

When starting my program, I get the message when trying to open VideoWriter, even though openh264-1.5.0-win32msvc.dll (Tried 1.6.0 too) and opencv_ffmpeg2413.dll are in the same directory:
"Could not find encoder for codec id 28: Encoder not found"

I am passing CV_FOURCC('H', '2', '6', '4') to the VideoWriter. I have tried putting the directory of openh264 dll in OPENH264_LIBRARY_PATH environment variable but it is also not working.

**Comment by alalek** [comment]
There is no support of OpenH264 in Windows FFMPEG wrapper of OpenCV 2.4 branch.
Adding support of this into OpenCV breaks behavior compatibility changes, so this feature can't be backported.

**Comment by AssemblerX64** [comment]
Is there support to it for OpenCV 3.0 however?

**Comment by alalek** [comment]
It is experimental "optional" feature. Currently it uses FFMPEG 3.1.3 with OpenH264 1.5.0. Also loader is customized via `OPENH264_LIBRARY` environment variable (instead of `OPENH264_LIBRARY_PATH`).
