### ISSUE TITLE
Feature request: accessing untyped cv::Mat pixels as cv::Scalar

### ISSUE THREAD

**Issue by kinchungwong** [opencv/opencv#7477]
<h3>Scope</h3>

This feature request is related to basic pixel access, as defined in http://stackoverflow.com/documentation/opencv/1957/pixel-access

<h3>Introduction</h3>

This feature request aims to answer a very common OpenCV C++ beginner question: using `cv::Mat::at<T>` is very nice if we can hard-code `T`. But what should I do if I need to write a function to support several different `T`, and I don't know C++ template programming?

OpenCV beginners believe there is a simple answer to this question, because OpenCV itself offers an untyped matrix class `cv::Mat` that does not need to hard-code the pixel type `T`. However in fact there is no simple answer; the simplest working solution requires use of C++ templates, and in fact requires SFINAE because scalar (single-valued) and vector (multi-valued, as in `cv::Vec<T, CN>`) must be coded differently, and the two cases of code must be selectively compiled with SFINAE.

<h3>Motivating example</h3>

```
void function_that_Does_Not_Need_to_know_mat_type ( cv::Mat& mat )
{
    auto pixelGetter = ResolvePixelGetter ( mat.type() ) ; // proposed feature
    auto pixelSetter = ResolvePixelSetter ( mat.type() ); // proposed feature
    for (int row = 0; row < 10; ++row)
    {
        for (int col = 0; col < 10; ++col)
        {
            cv::Scalar origValue = pixelGetter ( mat, row, col );
            cv::Scalar newValue = origValue + cv::Scalar(10, 8, 6);
            pixelSetter ( mat, row, col, newValue );
        }
    }
}

void main(int argc, char** argv)
{
    cv::Mat mat = cv::imread ( argv[1] );
    function_that_Does_Not_Need_to_know_mat_type ( mat ) ; // call it
}
```

<h3>A possible code implementation that will enable this feature</h3>

Please see: https://gist.github.com/kinchungwong/8df010d1358318effac5269c50bf4308

While the feature will need to be implemented with C++ templates, the user of this feature does not need to know how to use them. At the very least, knowledge of SFINAE is not required of the user.

Remark: the code implementation linked above is incomplete (it does not support all numeric types; adding support would be trivial), and has not been refactored to conform to OpenCV coding style. If this feature request is accepted, a PR can be created.

**Comment by StevenPuttemans** [comment]
In the past I have solved this with a switch statement inside my actual function-that-can-handle-multiple-types. Basically what I do in the beginning is using the `.type()` operator on a given Mat to know what data type is inside, then based on the output I have several cases for each `at<T>` template.

So in my opinion this functionality is not really needed?

**Comment by kinchungwong** [comment]
@StevenPuttemans Experienced OpenCV C++ users will have multiple ways of solving this problem. My feature request mainly targets beginning OpenCV C++ users who are also beginning C++ users.

My concern for beginning users with your suggestion is that they will see these the switch case statements as being nearly identical (aside from different `T`), and will attempt to remove them, omit some of them, or simply make mistakes by mismatching `T` and the `.type()` values. Because OpenCV `.at<T>` does not verify `T` with its own `.type()`, such code often results in unexpected outputs or crashes, and the beginning user receives no troubleshooting hints.

I do see one counter-proposal: provide at least one runtime-type-enforced version of `.at<T>` that will make sure `T` matches with `.type()`, so that an exception with descriptive message can be thrown. It could potentially be named `.safe_at()`, and can be documented alongside `.at<T>` so that beginning users can be directed to use the safe but slower overload.

For mathematically concerned users, typically they will define different formulas or even whole algorithms for processing single-channel pixel values and multi-channel pixel values, and differently for integer and floating-point values. These users who have higher standards will use the more advanced methods such as implementing multiple functions to process each typed matrices.

**Comment by StevenPuttemans** [comment]
> My concern for beginning users with your suggestion is that they will see these the switch case statements as being nearly identical (aside from different T), and will attempt to remove them, omit some of them, or simply make mistakes by mismatching T and the .type() values

Hmm my problem with this is that libraries should force people, even beginners to take an interest in good programming practices and the basics of C++ in this case. A switch is a commonly used structure, if one takes the time to interpret, they are quite good/easy/efficient. If a beginner starts simply cutting away code, then it is just bad practice in all.

> I do see one counter-proposal: provide at least one runtime-type-enforced version of .at<T> that will make sure T matches with .type(), so that an exception with descriptive message can be thrown. It could potentially be named .safe_at(), and can be documented alongside .at<T> so that beginning users can be directed to use the safe but slower overload.

Actually let me counter propose that again. How about sticking with the `.at<T>` operator, not supplying again another overload/similar function (library is crawled with that), but simply ensuring that the `.at<T>` checks if T is correct related to the `.type()` of the Mat it is accessed on. That should be possible to code.

**Comment by berak** [comment]
maybe we should put more effort into driving beginners **away** from coding per-pixel loops **at all**.

the whole approach is clearly an anti-pattern here, e.g. your example above could be much safer & faster written as

    mat += cv::Scalar(10, 8, 6);

**Comment by kinchungwong** [comment]
@berak I guess my toy example is not worth the debate. However, beginners are trying to implement things like 
```
    mat(y, x)[0] = 255 * (2 + sin(x / 10 / pi) + cos(y / 20 / pi)) / 4;
    ...
```
and in fact, beginners who learned OpenGL first are inclined to think "one pixel at a time".

**Comment by alalek** [comment]
Proposed approach has no chance to be implemented in OpenCV, because per-pixel operations must be effective.

There is some idea that tries to allow effective per-pixel operations: http://halide-lang.org/ (via declarative programming paradigm). But it has some restrictions.
