### ISSUE TITLE
AVD_loader.cpp: failed to get a service for display missing first three frame in mac sierra. 

### ISSUE THREAD

**Issue by gfgkmn** [opencv/opencv#7484]
##### System information (version)

- OpenCV => 3.1 homebrew --with-head
- Operating System / Platform => mac osx 10.12
- Compiler => homebrew default compiler. maybe clang 8.0.0

##### Detailed description

i use opencv to generate a video, use mp4v codec, today i upgrade opencv to 3.1  in commit . HEAD-699c25a_4, and i rerun the script, there is some error like this:

python try.py: 

Using Theano backend.
(550, 800, 3)
**/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4**
(550, 800, 3)
(550, 800, 3)
.....
(550, 800, 3)
2016-10-14 00:02:44.096 python[12059:224433] **WARNING: -finishWriting should not be called on the main thread.**
time consumed: 2.592619

this is a 20 frame matrix, i draw every frame a picture, and genrate a video. but after upgrade i found, the video is 17 frame.  it means the first three frame lost before AVD_loader.cpp error. 

i had alse install opencv 2.4.13, same problem. 

very appriciate to your response.

**Comment by StevenPuttemans** [comment]
General error issues are faster solved by opening up a question at http://answers.opencv.org/questions/

**Comment by mshabunin** [comment]
Looks like problem is not related to OpenCV. Please provide minimal reproducing script.

**Comment by alexbigboy** [comment]
i have the same problem: /Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
btw,System information (version)
OpenCV => 3.1 homebrew --with-head
Operating System / Platform => mac osx 10.12

**Comment by mshabunin** [comment]
@alexbigboy , please provide minimal reproducing code and output of `cv2.getBuildInformation()` (or `cv::getBuildinformaton()` for C++).

**Comment by alexbigboy** [comment]
@mshabunin,thanks .I have got it .I " git clone " the header opencv(3.1),then cmake it on the mac,and then i can success to run . thanks!

**Comment by bestcql** [comment]
@alexbigboy , could you please show me more details about your solution to this question? Still little confused. Thanks.

**Comment by bestcql** [comment]
@alexbigboy , could you please show me more details about your solution to this question? Still little confused. Thanks.
