### ISSUE TITLE
After building opencv 3.1.0 from source with extra modules, VideoCapture is not working in Java

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#7486]
I have built the OpenCV with extra modules form source, everything done well and generated the files which are the same as come with OpenCV,[ more details](http://stackoverflow.com/questions/40015961/after-building-opencv-3-1-0-from-source-with-extra-modules-videocapture-is-not), but when I use the VideoCapture it throws unknown exception, I searched a lot there was no way to solve, but if I use some functions of the OpenCV e.g: read image, do Canny all goes well, but only the VideoCaptutes class doesn't work, what can be the problem and how to solve.

**Comment by abratchik** [comment]
There seems to be general problem with java wrappers in this build (and the previous one), not only VideoCapture, some other classes are affected as well, for example CascadeClassifier. It seems that recent changes have broken the way how non-Ptr<> classes are wrapped in java. Working on it now, hopefully will be fixed today-tomorrow.

**Comment by Bahramudin** [comment]
Thanks for your reply! I am waiting for this fix to be done as soon as possible, because our work stopped just at this point. Hope the OpenCV organization fix and release these bugs.

**Comment by abratchik** [comment]
If your work has stopped here is some hint. Check [this commit.](https://github.com/opencv/opencv/commit/7a7a2749e0b6b3d760076007099e498d0657962c). 
It should not be rolled back, otherwise other classes will break. But you can do a quick hack for VideoCapture only )
