### ISSUE TITLE
There is no method to create SparseOpticalFlow and FarnebackOpticalFlow in java wrapper

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#7501]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
In currently built OpenCV, I couldn't find the method to create SparseOpticalFlow and FarnebackOpticalFlow  object in Video class in Java. Then how the object can be created.

**Comment by abratchik** [comment]
SparseOpticaFlow is a base class, what is the purpose of instantiating it? FarnebackOpticalFlow has create() method, did you try it?

**Comment by Bahramudin** [comment]
Yes I know, but if you do not create an instance of it, then how can you use this, Or how can you call the method `calc()` which is not a `static`  method that can directly use by `ClassName.calc()`. For example if you look to the `DualTVL1OpticalFlow  ` you can find a method in the `Video ` class `public static DualTVL1OpticalFlow createOptFlow_DualTVL1()` which can create the instance for this class, so then you can call the method `calc()`. Because the constructor is protected so you cannot `new ` the instance of this class` protected SparseOpticalFlow(long addr) { super(addr); }`. Hope you understand me!

**Comment by abratchik** [comment]
SparceOpticalFlow has no implementation so you cannot instantiate it. It is just a parent class for the similar algorithms. I guess your issue is that OpenCV provides wrappers for parent only and this is useless because you actually need wrappers for specific child algorithms. So which one is of your interest?

**Comment by abratchik** [comment]
SparseOpticaFlow cannot be instantiated as it is base class with no implementation. Differnt question is that OpenCV 3.1 has only one descendant SparsePyrLKOpticalFlow, which is not wrapped at all. This seems to be making SparseOpticaFlow useless.
FarnebackOpticalFlow is indeed having issue in wrappers.
Please check the fix above if it works for you or not. If and when OpenCV accepts the change then we will have it in the upstream.

**Comment by Bahramudin** [comment]
OK, Thanks I am waiting for update
