### ISSUE TITLE
Regression issue with Imgproc.minEnclosingCircle

### ISSUE THREAD

**Issue by abratchik** [opencv/opencv#7511]
##### System information (version)

- OpenCV => 3.1 upstream/master (505c19bc20b971288f321f6092f9dfc479001e2b)
- Operating System / Platform => Mac OSX 10.11.5 (15F34)
- Compiler => Xcode Version 8.0 (8A218a)
##### Detailed description

Java unit test is failing the test case  **ImgprocTest.testMinEnclosingCircle** with the following message:

```
    expected:<1.0299999713897705> but was:<1.000100016593933>

junit.framework.AssertionFailedError: expected:<1.0299999713897705> but was:<1.000100016593933>
at org.opencv.test.iimgproc.ImgprocTest.testMinEnclosingCircle(Unknown Source)
at org.opencv.test.OpenCVTestCase.runTest(Unknown Source)
```

The test is running the following code:

```
    public void testMinEnclosingCircle() {
        MatOfPoint2f points = new MatOfPoint2f(new Point(0, 0), new Point(-1, 0), new Point(0, -1), new Point(1, 0), new Point(0, 1));
        Point actualCenter = new Point();
        float[] radius = new float[1];

        Imgproc.minEnclosingCircle(points, actualCenter, radius);

        assertEquals(new Point(0, 0), actualCenter);
        assertEquals(1.03f, radius[0], EPS);
    }
```
##### Steps to reproduce

Compile OpenCV with java enabled and run the autotests from the build folder using the following command:

```
python ../modules/ts/misc/run.py . -t java
```

Results of autotests can be seen on this page: opencv/build/modules/java/pure_test/.build/testResults/junit-noframes.html

**Comment by alalek** [comment]
Golden value is magic number here.
My suggestion is to multiply input data by 100 and use golden radius = 100.0 and tolerance check (eps) = 1.0.

**Comment by abratchik** [comment]
Do you mean coordinates of points should be multiplied by 100? like this:
`MatOfPoint2f points = new MatOfPoint2f(new Point(0, 0), new Point(-100, 0), new Point(0, -100), new Point(100, 0), new Point(0, 100));`

**Comment by alalek** [comment]
@abratchik Exactly. Also please change this line:
```
//assertEquals(1.03f, radius[0], EPS);
assertEquals(100.0f, radius[0], 1.0);
```
