### ISSUE TITLE
Regression issue with Imgproc.HoughLinesP

### ISSUE THREAD

**Issue by abratchik** [opencv/opencv#7512]
##### System information (version)

- OpenCV => 3.1 upstream/master (505c19bc20b971288f321f6092f9dfc479001e2b)
- Operating System / Platform => Mac OSX 10.11.5 (15F34)
- Compiler => Xcode Version 8.0 (8A218a)
##### Detailed description

Java unit test is failing the test case  **ImgprocTest.testHoughLinesPMatMatDoubleDoubleInt** with the following message:

```
expected:<2> but was:<1>

junit.framework.AssertionFailedError: expected:<2> but was:<1>
at org.opencv.test.imgproc.ImgprocTest.testHoughLinesPMatMatDoubleDoubleInt(Unknown Source)
at org.opencv.test.OpenCVTestCase.runTest(Unknown Source)
```

The test is running the following code:

```
    public void testHoughLinesPMatMatDoubleDoubleInt() {
        int sz = 512;
        Mat img = new Mat(sz, sz, CvType.CV_8U, new Scalar(0));
        Point point1 = new Point(0, 0);
        Point point2 = new Point(sz, sz);
        Point point3 = new Point(sz, 0);
        Point point4 = new Point(2*sz/3, sz/3);
        Imgproc.line(img, point1, point2, Scalar.all(255), 1);
        Imgproc.line(img, point3, point4, Scalar.all(255), 1);
        Mat lines = new Mat();

        Imgproc.HoughLinesP(img, lines, 1, 3.1415926/180, 100);

        assertEquals(2, lines.cols());

        /*
        Log.d("HoughLinesP", "lines=" + lines);
        int num = (int)lines.cols();
        int buff[] = new int[num*4]; // CV_32SC4 as [ (x1, y1, x2, y2), (...), ...]
        lines.get(0, 0, buff);
        Log.d("HoughLinesP", "lines=" + Arrays.toString(buff));
        */
    }
```
##### Steps to reproduce

Compile OpenCV with java enabled and run the autotests from the build folder using the following command:

```
python ../modules/ts/misc/run.py . -t java
```

Results of autotests can be seen on this page: opencv/build/modules/java/pure_test/.build/testResults/junit-noframes.html

**Comment by alalek** [comment]
I have this from Java debug dump:
```
 lines=Mat [ 2*1*CV_32SC4, isCont=true, isSubmat=false, nativeObj=0x7f8114b0ea10, dataAddr=0x7f8114b10b60 ]
```
where is rows=2 cols=1.

So you can modify check:
```
assertEquals(2, lines.cols());
```
->
```
assertEquals(2, lines.rows());
```

**Comment by alalek** [comment]
Anyway I have no idea why a lot of code still works with vectors via 2D Mat ... It is very ambiguous and dangerous.
/cc @vpisarev

**Comment by abratchik** [comment]
Ok, thank you! Will do the changes tonight.
