### ISSUE TITLE
core: performance test OCL_DivFixture_Divide.Divide fails on ARM

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#7523]
##### System information (version)
- OpenCV => master (8213e57f3b032033b6c4c1e3eb3bdc84c12c0e1a)
- Operating System / Platform => ARM 32bit (Jetson TK1)
- Compiler => gcc 4.8.4

##### Summary of the issue
- Divide using NEON is too aggressive of losing precision
- I'd like to ask a suggestion of way to fix it

##### Detailed description
- opencv_perf_core fails on OCL_DivFixture_Divide.Divide
```
[  FAILED  ] OCL_DivFixture_Divide.Divide/0, where GetParam() = (640x480, 8UC1)
[  FAILED  ] OCL_DivFixture_Divide.Divide/2, where GetParam() = (640x480, 8UC3)
[  FAILED  ] OCL_DivFixture_Divide.Divide/4, where GetParam() = (640x480, 8UC4)
[  FAILED  ] OCL_DivFixture_Divide.Divide/6, where GetParam() = (1280x720, 8UC1)
[  FAILED  ] OCL_DivFixture_Divide.Divide/8, where GetParam() = (1280x720, 8UC3)
[  FAILED  ] OCL_DivFixture_Divide.Divide/10, where GetParam() = (1280x720, 8UC4)
[  FAILED  ] OCL_DivFixture_Divide.Divide/14, where GetParam() = (1920x1080, 8UC3)
[  FAILED  ] OCL_DivFixture_Divide.Divide/16, where GetParam() = (1920x1080, 8UC4)
[  FAILED  ] OCL_DivFixture_Divide.Divide/18, where GetParam() = (3840x2160, 8UC1)
[  FAILED  ] OCL_DivFixture_Divide.Divide/20, where GetParam() = (3840x2160, 8UC3)
[  FAILED  ] OCL_DivFixture_Divide.Divide/22, where GetParam() = (3840x2160, 8UC4)
```
- The failure is because the values are slightly different (expected value was **2** when the actual value was **1**)
```
[ RUN      ] OCL_DivFixture_Divide.Divide/0
/home/ubuntu/opencv-fork/modules/ts/src/ts_perf.cpp:377: Failure
The difference between expect_last and actual_last is 1, which exceeds eps, where
expect_last evaluates to 2,
actual_last evaluates to 1, and
eps evaluates to 0.00025499999999999996.
Argument "dst" has unexpected value of the last element

params    = (640x480, 8UC1)
termination reason:  unknown
bytesIn   =     614400
bytesOut  =     307200
samples   =         13 of 100
outliers  =          1
frequency = 1000000000
min       =     640664 = 0.64ms
median    =     644664 = 0.64ms
gmean     =     644412 = 0.64ms
gstddev   = 0.00548082 = 0.02ms for 97% dispersion interval
mean      =     644421 = 0.64ms
stddev    =       3539 = 0.00ms
[  FAILED  ] OCL_DivFixture_Divide.Divide/0, where GetParam() = (640x480, 8UC1) (27 ms)
```
- I digged in a bit, and OCL_DivFixture goes to [here ](https://github.com/opencv/opencv/blob/8213e57f3b032033b6c4c1e3eb3bdc84c12c0e1a/modules/core/src/arithm.cpp#L3157-L3165)
```
void div8u( const uchar* src1, size_t step1, const uchar* src2, size_t step2,
                   uchar* dst, size_t step, int width, int height, void* scale)
{
CALL_HAL(div8u, cv_hal_div8u, src1, step1, src2, step2, dst, step, width, height, *(const double*)scale
```
- and this function will call ```div``` in ```carotene``` which is [here](https://github.com/opencv/opencv/blob/8213e57f3b032033b6c4c1e3eb3bdc84c12c0e1a/3rdparty/carotene/src/div.cpp#L127) 
```
template <typename T>
void div(const Size2D &size,
         const T * src0Base, ptrdiff_t src0Stride,
         const T * src1Base, ptrdiff_t src1Stride,
         T * dstBase, ptrdiff_t dstStride,
         f32 scale,
         CONVERT_POLICY cpolicy)
{
internal::assertSupportedConfiguration();
```
- and calls the function ```divSaturateQ``` which is [here](https://github.com/opencv/opencv/blob/8213e57f3b032033b6c4c1e3eb3bdc84c12c0e1a/3rdparty/carotene/src/div.cpp#L65)
```
{ return vcvtq_s32_f32(vmulq_f32(vmulq_n_f32(vcvtq_f32_s32(v1), scale), internal::vrecpq_f32(vcvtq_f32_s32(v2)))); }
```
- Now the real cause is that the divide is computed by [reciprocal value ](https://github.com/opencv/opencv/blob/8213e57f3b032033b6c4c1e3eb3bdc84c12c0e1a/3rdparty/carotene/src/intrinsics.hpp#L53)
```
inline float32x4_t vrecpq_f32(float32x4_t val)
{
    float32x4_t reciprocal = vrecpeq_f32(val);
    reciprocal = vmulq_f32(vrecpsq_f32(val, reciprocal), reciprocal);
    reciprocal = vmulq_f32(vrecpsq_f32(val, reciprocal), reciprocal);
    return reciprocal;
}
```
- Approach of using Newton-Raphson method with reciprocal is quite useful to accelerate, but it causes difference in some cases.
- I wrote a [small program](https://github.com/tomoaki0705/sampleReciprocalNeon) to verify that, and based on this program, more than 200 cases causes difference in range of ```char``` (i.e. -128---128)
- The ```actual``` value below shows the result using ```vrecpeq``` and ```expected``` show the result from normal float operation and then rounded to int.
```
iteration:2 expected:1 actual:0 -126/-126
iteration:2 expected:1 actual:0 -125/-125
iteration:2 expected:2 actual:1 -126/-63
iteration:2 expected:3 actual:2 -126/-42
iteration:2 expected:6 actual:5 -126/-21
iteration:2 expected:-6 actual:-5 -126/21
iteration:2 expected:-3 actual:-2 -126/42
iteration:2 expected:-2 actual:-1 -126/63
iteration:2 expected:-1 actual:0 -125/125
iteration:2 expected:-1 actual:0 -126/126
iteration:2 expected:1 actual:0 -122/-122
iteration:2 expected:1 actual:0 -121/-121
iteration:2 expected:2 actual:1 -122/-61
```
- Now, I think there are three ways to fix this issue
 1. loosen the threshold on performance test of division
 2. deactivate the NEON optimization just for division
 3. avoid including this test case on ARM
- In the past, I was suggested to loosen the threshold only for ARM platform, but in this case, I don't agree about loosing the threshold.  The result differs in int, not float.
- At least for division on integer types, I propose to deactivate any NEON optimization on this.

##### Steps to reproduce
- Run ```opencv_perf_core --gtest_filter=OCL_DivFixture_Divide.Divide*```

**Comment by alalek** [comment]
Thanks for report!
I'm enable "OCL" tests on our ARMv7-TK1 builder (T-API tests, not OpenCL only), so these (and other) failures are reproduced.

**Comment by tomoaki0705** [comment]
BTW, this doesn't occur on 64bit ARM (PINE64 for instance)

```
[----------] 24 tests from OCL_DivFixture_Divide
[ RUN      ] OCL_DivFixture_Divide.Divide/0
[ PERFSTAT ]    (samples = 10, mean = 8.49, median = 8.51, stddev = 0.20 (2.3%))
[ VALUE    ] 	(640x480, 8UC1)
[       OK ] OCL_DivFixture_Divide.Divide/0 (94 ms)

<snip>

[----------] 24 tests from OCL_DivFixture_Divide (57393 ms total)
```

Though, there are many performance test failure.
I'll try to fix one by one.

**Comment by alalek** [comment]
1) Some values of src2 are 0. Division by zero is not good and result is undefined.
2) `vcvtq_s32_f32` rounds toward zero. Round to nearest/even should be used instead. Something like `cvRound`, but for `float32x4_t` type.
3) Check tolerance should be 1 for integer-based types.

**Comment by tomoaki0705** [comment]
Thanks for your comment.
I tried round-to-nearest and that behavior improves a lot.
Unfortunately, it still cause error in 34 cases, so I agree we have to enlarge tolerance to 1.

**Comment by tomoaki0705** [comment]
@alalek , I updated the PR.
Now the PR will do round-to-nearest instead of round-to-zero.
This fix was sufficient enough to let the performance test pass through, but there are still some corner case that division with SIMD doesn't match normal division.

I think it's sufficient to merge now, but if I should update the opencv_extra too, please let me know.

Best.
