### ISSUE TITLE
ios10 using CvVideoCamera, memory overflow when I repeatedly start and stop 

### ISSUE THREAD

**Issue by panxiaochun** [opencv/opencv#7527]
##### System information (version)
- OpenCV => 2.4.13
- Operating System / Platform => macOS 10.12
- Compiler => Xcode Version 8.0 (8A218a)
##### Detailed description

I using opencv for ios build my app . The app will memory overflow when I repeatedly   the method  `[self.cvVideoCamera start]` and  `[self.cvVideoCamera stop]`

![](http://images.cnblogs.com/cnblogs_com/panxiaochun/871986/o_%e5%b1%8f%e5%b9%95%e5%bf%ab%e7%85%a7%202016-10-20%20%e4%b8%8b%e5%8d%884.55.32.png)
##### Steps to reproduce

```
#import "ViewController.h"
#include "opencv2.framework/Headers/videoio/cap_ios.h"

@interface ViewController ()<CvVideoCameraDelegate>

@property (weak, nonatomic) IBOutlet UIImageView *imageView;

@property (nonatomic,strong) CvVideoCamera *videoCamera;


@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    self.videoCamera = [[CvVideoCamera alloc] initWithParentView:self.imageView];
    self.videoCamera.delegate = self;
    self.videoCamera.defaultAVCaptureDevicePosition = AVCaptureDevicePositionBack;
    self.videoCamera.defaultAVCaptureSessionPreset = AVCaptureSessionPresetHigh;
    self.videoCamera.defaultFPS = 30;


}

- (IBAction)startClicked:(UIButton *)sender {
       [self.videoCamera start];
}
- (IBAction)stopClicked:(UIButton *)sender {
       [self.videoCamera stop];

}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.

}


@end
```

**Comment by Michels10** [comment]
I am having the same issue on OpenCV (3.1.0.1) and (2.4.x).  I've been trying to diagnose what the issue is but haven't been able to.  In fact, when I profile the app I don't even see significant memory usage.  If I start/stop 5 or 6 times, the app is using around 6MB of memory but still manages to crash.

**Comment by panxiaochun** [comment]
copy cap_ios_abstract_camera.mm , cap_ios_photo_camera.mm , cap_ios_video_camera.mm , cap_ios.h, precomp.hpp in your project. Delete _[super dealloc]_ in cap_ios_abstract_camera.mm, deleted
  _if (videoDataOutputQueue) {
       dispatch_release(videoDataOutputQueue);
    }_
in cap_ios_video_camera.mm , delete #include "opencv2/core/private.hpp" in procmp.hpp.
then , #include "cap_ios.h"
my app is work will now .
![](http://images.cnblogs.com/cnblogs_com/panxiaochun/871986/o_%e5%b1%8f%e5%b9%95%e5%bf%ab%e7%85%a7%202016-10-24%20%e4%b8%8b%e5%8d%883.00.41.png)

**Comment by StevenPuttemans** [comment]
Hi and thanks for the report. Could you provide the suggested fix through a PR?

**Comment by panxiaochun** [comment]
I would gladly to do that. I am testing it in framework now, but it seem not work well in framework, Maybe  I  not build the framework correct.

**Comment by panxiaochun** [comment]
I fix the problem.It work well now.
