### ISSUE TITLE
Tracking module for Java is not usable

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#7528]
##### System information (version)

- OpenCV = 3.1
- Operating System / Platform = Windows 64 Bit
- Compiler = Visual Studio 2015

##### Detailed description

I have build the OpenCV with extara modules, because I want to use the tracking module of the contrin modules, so I have add the word "java" in the CMakeLists.txt file, the build process was successfully done. But when I open the MultiTracker class, except the constractor all the method was commented. What is wrong with this module, is it not availble in Java? BTW I want to ask which modules now are available in Java?

**Comment by alalek** [comment]
You should open ticket for opencv_contrib repo: https://github.com/opencv/opencv_contrib/issues

**Comment by Bahramudin** [comment]
Hello Sir! What is this sentence mean? _You should open ticket for opencv_contrib repo_ I build the OpenCV then I saw this problem, and I asked can we modify the CMake file? Because lots of modules doesn't have the wrapper for Java, e.g: face module and so on... If we cannot modify you can simply say "you cannot" or "yes you can; only for these modules". But it is really a question for me, I search a lot on net , some says you can modify CMake file that is OK, but it did solve the problem.
