### ISSUE TITLE
Building iOS framework with build_framework.py fails: CMake Error: Error: generator : Xcode

### ISSUE THREAD

**Issue by gitmalong** [opencv/opencv#7532]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Mac OS Sierra 10.12
- Xcode => 8.0
- Cmake => 3.7.0-rc1

##### Steps to reproduce

```
user$ python opencv-3.1.0/platforms/ios/build_framework.py ios-framework
Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/Users/user/Downloads/opencv-3.1.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/user/Downloads/opencv-3.1.0', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /Users/user/Downloads/ios-framework/build/armv7-iPhoneOS
CMake Error: Error: generator : Xcode
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
============================================================
ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/Users/user/Downloads/opencv-3.1.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/user/Downloads/opencv-3.1.0', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1
============================================================
Traceback (most recent call last):
  File "opencv-3.1.0/platforms/ios/build_framework.py", line 87, in build
    self._build(outdir)
  File "opencv-3.1.0/platforms/ios/build_framework.py", line 81, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv-3.1.0/platforms/ios/build_framework.py", line 133, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "opencv-3.1.0/platforms/ios/build_framework.py", line 34, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/Users/user/Downloads/opencv-3.1.0/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/user/Downloads/opencv-3.1.0', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1
```

**Comment by alalek** [comment]
> Does not match the generator used previously: Unix Makefiles

Try to build from scratch (cleanup your build directory).

**Comment by gitmalong** [comment]
I tried to run the script with a new build directory but it still not works - same error.

**Comment by gitmalong** [comment]
Thanks. That worked for me.

**Comment by doctor-xray** [comment]
Have with the MacBook M1Pro same problem?!


CMake Error at cmake/OpenCVCompilerOptimizations.cmake:611 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:327 (ocv_compiler_optimization_options)
  CMakeLists.txt:643 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeOutput.log".
See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeError.log".
============================================================
ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.
============================================================
Traceback (most recent call last):
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 181, in build
    self._build(outdir)
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 139, in _build
    self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 306, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "/Users/don/Projects/opencv/platforms/apple/cv_build_utils.py", line 13, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.

**Comment by ytx0574** [comment]
> Have with the MacBook M1Pro same problem?!
> 
> CMake Error at cmake/OpenCVCompilerOptimizations.cmake:611 (message): Compiler doesn't support baseline optimization flags: Call Stack (most recent call first): cmake/OpenCVCompilerOptions.cmake:327 (ocv_compiler_optimization_options) CMakeLists.txt:643 (include)
> 
> # -- Configuring incomplete, errors occurred!
> See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeOutput.log".
> See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeError.log".
> # ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.
> Traceback (most recent call last): File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 181, in build self._build(outdir) File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 139, in _build self.buildOne(target[0], target[1], main_build_dir, cmake_flags) File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 306, in buildOne execute(cmakecmd, cwd = builddir) File "/Users/don/Projects/opencv/platforms/apple/cv_build_utils.py", line 13, in execute retcode = check_call(cmd, cwd = cwd) File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.

did you fix this bug?

**Comment by adlytic** [comment]
> Have with the MacBook M1Pro same problem?!
> 
> CMake Error at cmake/OpenCVCompilerOptimizations.cmake:611 (message): Compiler doesn't support baseline optimization flags: Call Stack (most recent call first): cmake/OpenCVCompilerOptions.cmake:327 (ocv_compiler_optimization_options) CMakeLists.txt:643 (include)
> 
> # -- Configuring incomplete, errors occurred!
> See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeOutput.log".
> See also "/Users/don/Projects/ios/build/build-armv7-iphoneos/CMakeFiles/CMakeError.log".
> # ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.
> Traceback (most recent call last): File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 181, in build self._build(outdir) File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 139, in _build self.buildOne(target[0], target[1], main_build_dir, cmake_flags) File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 306, in buildOne execute(cmakecmd, cwd = builddir) File "/Users/don/Projects/opencv/platforms/apple/cv_build_utils.py", line 13, in execute retcode = check_call(cmd, cwd = cwd) File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DOPENCV_INCLUDE_INSTALL_PATH=include', '-DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty', '-DFRAMEWORK_NAME=opencv2', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/don/Projects/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCPU_BASELINE=DETECT', '/Users/don/Projects/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/don/Projects/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1.

I am having exact same issue on my Mac. Is there a solution available for this one?

**Comment by ytx0574** [comment]
> 

https://juejin.cn/post/7215496238627176504
this fix
