### ISSUE TITLE
cv :: text :: OCRTesseract Class is not available in the ios

### ISSUE THREAD

**Issue by daisukenagata** [opencv/opencv#7543]
- OpenCV => 3.1
- Operating System / Platform => Mac IOS
- Compiler => Xcode7.3.1

<img width="389" alt="2016-10-25 01 53 11" src="https://cloud.githubusercontent.com/assets/16457165/19655117/db96b294-9a55-11e6-87ee-60d58a0d0312.png">

![2016-10-24 15 10 50](https://cloud.githubusercontent.com/assets/16457165/19635277/153a81c4-99fc-11e6-9003-e98fde00869b.png)

Hello. I, I want to implement the character analysis in the IOS of Swift language in openCV, there is no error as the current method.

But do not pass is compiled with that of that there is no architecture.

I added a erfilter.hpp and ocr.hpp and text.hpp of text folder to opencv2.framework. We will wait for the answer and the corresponding measures.

**Comment by StevenPuttemans** [comment]
First of all, please remove/replace all non-english comments because the largest part of the community has no clue on what is happening in those comments. Secondly replace your screencaptures by actual test pastes, so hat it is easier to go through.

Finally basic errors when building should be addressed at http://answers.opencv.org/questions/ before opening an issue here.

**Comment by daisukenagata** [comment]
Contact Thank you Masu throne.

My environment, we use the MacOS Xcode7.3.1 SDK9.3 SWift language.

For carrying out the character analysis in openVC, it was used OCRTesseract Class.

However, as in the above picture, you receive a compilation error that there is no architecture x86_64.

I, I added ocr.hpp and text.hpp and erfilter.hpp to opencv2.framework, can not recognize, is such an error occurred.

Also http://docs.opencv.org/3.0.0/d5/da3/tutorial_ios_install.html
It was the correspondence, but did not get the source in Xcode version of the problem.

Is there a way that you can use the OCRTesseract Class in MacOS Xcode7.3.1 SDK9.3 SWift language?

thank you regards

**Comment by loveq369** [comment]
because opencv2.framework is build for iOS. not Mac OS X. 

发自我的 iPhone
