### ISSUE TITLE
Unused function startWindowThread ?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#7562]
Hi, 
reading doc i found [startThread ](http://docs.opencv.org/master/d7/dfc/group__highgui.html#ga2c6ecef4f85d8e5cbefec39c9e82ece0) It seems this function is empty or used as an internal function :
https://github.com/opencv/opencv/blob/master/modules/highgui/src/window.cpp#L239
and https://github.com/opencv/opencv/blob/master/modules/highgui/src/window.cpp#L642
May be it shouldn't be in doc

**Comment by kinchungwong** [comment]
The function on Line 642 that gives an error at runtime is only enabled if OpenCV is built without linking to any of the supported windowing system API.
See https://github.com/opencv/opencv/blob/9b2b8404a0b2c1c9cb238889cfd70a7ccd245cf4/modules/highgui/src/window.cpp#L509-L516

The comments on these lines explained where to find the corresponding function implementations for each windowing API.

```
#if   defined (HAVE_WIN32UI)  // see window_w32.cpp
#elif defined (HAVE_GTK)      // see window_gtk.cpp
#elif defined (HAVE_COCOA)    // see window_carbon.cpp
#elif defined (HAVE_CARBON)
#elif defined (HAVE_QT)       // see window_QT.cpp
#elif defined (WINRT) && !defined (WINRT_8_0) // see window_winrt.cpp
```

**Comment by mshabunin** [comment]
This function is exported, we can not remove it from public API without breaking compatibility. Probably we could deprecate it and remove from API and documentation in future.

**Comment by caraffi** [comment]
I think the fact that remains in the API but it is not document is very confusing. In the case of GTK, is it necessary to call it or is it automatically called?

**Comment by crackwitz** [comment]
related issue #9087

5.0 milestone... if I am informed correctly, a unified OpenGL GUI is planned for that. regardless of whether this function is removed, I'd still like to see the behavior of GUI staying responsive in the absence of waitKey calls. highly convenient, particularly when prototyping interactively with python, or single-stepping through code. I don't know how the new OpenGL GUI is going to be implemented but if it involves an event loop thread, perhaps spawn it implicit in a `namedWindow`/`imshow` call.
