### ISSUE TITLE
"-fvisibility=hidden" should not be forced when building a library like OpenCV

### ISSUE THREAD

**Issue by seanm** [opencv/opencv#7565]
##### System information (version)
- OpenCV => 3.1 & current git master
- Operating System / Platform => Mac OS X
- Compiler => Xcode / clang

##### Detailed description

In cmake/OpenCVCompilerOptions.cmake there is the following block:

```
# set default visibility to hidden
if(CMAKE_COMPILER_IS_GNUCXX AND CMAKE_OPENCV_GCC_VERSION_NUM GREATER 399)
  add_extra_compiler_option(-fvisibility=hidden)
  add_extra_compiler_option(-fvisibility-inlines-hidden)
endif()
```

Forcing an -fvisibility choice like this seems to me incorrect when building a _library_ like OpenCV.  The problem is that the -fvisibility choice must be the same for all code built, that is, my app, library1, library2, etc. must all be built with the same -fvisibility flag.

Yes, in general, -fvisibility=hidden is better than -fvisibility=default, but sometimes one needs to use -fvisibility=default, as my app currently does.  Since OpenCV forces -fvisibility=hidden, I get link warnings like this:

```
ld: warning: direct access in cv::ocl::selectOpenCLDevice() to global weak symbol std::__1::char_traits<char>::eq(char, char) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

If I add -fvisibility=default to my CMAKE_CXX_FLAGS, it ends up earlier on the command list and thus clobbered:

```
--     C++ flags (Release):         -fvisibility=default <...> -fvisibility=hidden -fvisibility-inlines-hidden
```

I propose simply removing the hardcoded -fvisibility choice, and leave it to the user to specify any needed build options, but maybe there are other solutions...

**Comment by paroj** [comment]
> The problem is that the -fvisibility choice must be the same for all code built

nope, not all code - just the parts shared across libs. For OpenCV this means the STL. However this should have been taken care of by the STL. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36022.

**Comment by seanm** [comment]
@paroj Thanks for your reply.  Regarding your guess: quite possibly. Please see also https://github.com/opencv/opencv/issues/7566  As I created this bug first, I think I only removed OpenCV's hardcoded "stdc++" *after* removing the hardcoded "-fvisibility".  I'll try rebuilding the other way around.

Still, as you likely know, C++ & STL are finicky about build options matching up.  One is asking for trouble if STL libraries, C++ dialect, complier versions, etc don't match up.  I still believe it is improper for *library* code to force particular -fvisibility and STL choices as OpenCV does.  Do you agree?

**Comment by paroj** [comment]
-fvisibility is specifically meant to be used with shared libraries and generally this flag does not have to match across compilation units.

Therefore I do not agree that one should remove -fvisibility=hidden from OpenCV. If you find any issues with it rather the code causing them should be fixed.

**Comment by tcurdt** [comment]
I've just setup the most simple iOS project with opencv and run into the very same issue. Plenty of warnings.
Any suggestions on how to fix this best?

**Comment by floriankrueger** [comment]
@tcurdt same here. did you happen to find a solution yet?

**Comment by tcurdt** [comment]
@floriankrueger for now I just ignored it and hope for a proper new release

**Comment by bvnp43** [comment]
@seanm You can disable visibility by passing build arg `OPENCV_SKIP_VISIBILITY_HIDDEN=True`
