### ISSUE TITLE
opencv_createsamples error

### ISSUE THREAD

**Issue by suneelbelkhale** [opencv/opencv#7567]
This might be a misunderstanding, but I keep getting this error when running opencv_createsamples like this:

`opencv_createsamples -vec im1_vec.vec -img pos/im1.jpg -w 100 -h 80 -bg bg.txt -maxxangle 6.5 -maxyangle 6.5 -maxzangle 6.5 -num 250`

Error: 

`Invalid background description file.`

I have tried absolute paths in bg.txt, and all variation of relative paths, leading me to believe that the utility itself may have some issue.

Thanks!

**Comment by alalek** [comment]
Usage questions should go to User Q/A forum: http://answers.opencv.org
