### ISSUE TITLE
compile opencv 3 on ubuntu 16.04 and CUDA 8.0.44 build error

### ISSUE THREAD

**Issue by developer-mayuan** [opencv/opencv#7591]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC 5.4 / GCC 4.9

##### Detailed description
Trying to install openCV 3.1, CUDA 8.0.44 on Ubuntu 16.04 by building from the source.

The following are the errors I met during the compilation.
```
Scanning dependencies of target opencv_test_video
[ 37%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_optflowpyrlk.cpp.o
[ 37%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_accum.cpp.o
[ 37%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_kalman.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_ecc.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_tvl1optflow.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_main.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_camshift.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/ocl/test_optflowpyrlk.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/ocl/test_optflow_farneback.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/ocl/test_bgfg_mog2.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/ocl/test_optflow_tvl1flow.cpp.o
[ 38%] Building CXX object modules/video/CMakeFiles/opencv_test_video.dir/test/test_estimaterigid.cpp.o
[ 38%] Linking CXX executable ../../bin/opencv_test_video
//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
modules/video/CMakeFiles/opencv_test_video.dir/build.make:391: recipe for target 'bin/opencv_test_video' failed
make[2]: *** [bin/opencv_test_video] Error 1
CMakeFiles/Makefile2:3336: recipe for target 'modules/video/CMakeFiles/opencv_test_video.dir/all' failed
make[1]: *** [modules/video/CMakeFiles/opencv_test_video.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

##### Steps to reproduce
* The following are the detailed configuration:
<code>LD_LIBRARY_PATH: /usr/lib/nvidia-current:/usr/local/cuda/lib64:/usr/local/cuda/lib</code>

* CMake configuration command:
<code>
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" .. </code>

**Comment by alalek** [comment]
Please add more info:
- CMake output log / CMakeCache.txt / CMakeVars.txt from build folder
- command line parameters of failed command (`make VERBOSE=1`)

Try "LDFLAGS=-lgomp" environment variable before CMake launch.

**Comment by StevenPuttemans** [comment]
Before continuing, do you really need GOMP? Because OpenMP support is included in your gcc compiler... Basically it is missing some OpenMP configuration. Try running `cmake-qt-gui`, select `WITH_OPENMP`, and see if the configuration is not having trouble finding all its necessary paths.
