### ISSUE TITLE
VideoCapture.read() skipped frames?

### ISSUE THREAD

**Issue by Chengtianxiang** [opencv/opencv#7592]
##### System information (version)
- OpenCV => 2.13
- Operating System / Platform => Linux2.6.32 el6 x86_64
- Compiler => gcc 4.4.7
- Python => 2.6.6

##### Detailed description
I use python to read all the frames from a video file. But I found some frames are skipped using VideoCapture.read(). as well as using VideoCapture.set(cv.CV_CAP_PROP_POS_FRAMES, frame_no)

Here is the bug case.  [http://www.miaopai.com/show/9wzVbYXrGO3qHsxcIVMbqQ__.htm](url) 
I use read method to extract frames numbering from 3353 to 3359. Also I use set method to get the 3357 and 3358 frame. The bug is the 3353 frame extracted by former method is the same as 3357 frame extracted by later method, and so is 3359 to 3358.

##### Steps to reproduce
cap = cv2.VideoCapture(videofile)
while True:
    frame_no = int(cap.get(cv.CV_CAP_PROP_POS_FRAMES))
    succ, frame = cap.read()
    if not succ:
        break
    print frame_no
    

cap.set(cv.CV_CAP_PROP_POS_FRAMES, frame_no)
ret, frame = cap.read()

**Comment by alalek** [comment]
Setting of `CV_CAP_PROP_POS_FRAMES` is not accurate in general. Some current implementation notes:
- result depends on used video backend
- frame seeking may be implemented via "time" in ms
- probably frame seeking works well for "key frames" only (not B-frames).
- probably your ffmpeg/libav/gstreamer library is outdated.

**Comment by Chengtianxiang** [comment]
@alalek thank you very much. Problem solved.

**Comment by shashank-industrail** [comment]
@fiveh , Thanks it works.
i was using this code, with hikvision camera.
```
import cv2
import time
cap = cv2.VideoCapture('rtsp://userid:passwd@192.168.1.64')

While cap.isOpened():
    ret, frame = cap.read()
    # object detection code, i'm using time.sleep to replicate that behaviour.
    time.sleep(1)
    cv2.imshow('image', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```
I believe this camera store the frame and cap.read accessing the consecutive frame with 1sec wait.
That is very strage behaviour.
It is avoidable by using cap.grab() method.
