### ISSUE TITLE
How to switch features between sift,surf or orb using Features2D with opencv3.1

### ISSUE THREAD

**Issue by universewill** [opencv/opencv#7593]
Hello, I am using opencv 3.1, and i can not find a way to switch between features by simply passing a string without modify the code.

For example, in previous versions, you can do it like this:

> 

    cout << "< Creating detector, descriptor extractor and descriptor matcher ..." << endl;
    Ptr<FeatureDetector> detector = FeatureDetector::create( argv[1] );
    Ptr<DescriptorExtractor> descriptorExtractor = DescriptorExtractor::create( argv[2] );

But with opencv 3.1, you can only do this:

> Ptr<SIFT> detector = SIFT::create(minHessian);

Is there a way to set the feature more flexible like the previous versions?by passing A string title?

**Comment by catree** [comment]
`Create()` with `String` has been deleted in OpenCV 3 (see [No more features2d::create ?](http://code.opencv.org/issues/4009#note-1)).

In OpenCV 3, you can do:
```
cv::Ptr<cv::Feature2D> detector;
if (detectorName == "SIFT") {
  detector = cv::xfeatures2d::SIFT::create();
} else if (detectorName == "SURF") {
  cv::xfeatures2d::SURF::create();
} //etc.
```

**Comment by mdaiter** [comment]
@catree picky but you might want to consider using `descriptorName` instead of `detectorName`. Might be confusing to people looking at this, because of the necessary generation of key points/areas prior to passing in data to the feature extractor.
