### ISSUE TITLE
Compile CUDA 7.5 and OpenCV 3.1

### ISSUE THREAD

**Issue by JAbdor7** [opencv/opencv#7611]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2013 Professional
- Cuda => 7.5
- GPU => GeoForce GT 540M

##### Detailed description

Good day, I really need help in compiling Opencv 3.1 with cuda support. The cuda libraries are installed correctly, the cuda version is 7.5. I'm currently getting errors similar to post [#6925](https://github.com/opencv/opencv/issues/6925). I'm getting the LNK1104 error and warnings like these "warning : field of class type without a DLL interface used in a class with a DLL interface" which I have no idea what they mean. I would appreciate if someone could help me with the cmake setup and how to remove the errors. I do need cuda support.

**Comment by StevenPuttemans** [comment]
Please add your explicit CMAKE configuration and errors here, else there is no way to give you any further assistance...
