### ISSUE TITLE
Issue with using OpenCV as an ExternalProject in CMake

### ISSUE THREAD

**Issue by geokon-gh** [opencv/opencv#7616]
## System information (version)
- OpenCV => 3.1
- Operating System / Platform => Debian Linux x64 - testing
- Compiler => gcc 6.2

##### Detailed description
I came across a problem with OpenCV when building a small test template. When it's included in a parent project using ExternProject_Add() it won't properlly export OpenCV variables

For context:
I'm trying to build OpenCV as an ExternalProject for a small program I'm writing

The directory structure is 
```
MyProject/
    CMakeLists.txt
    build-release/
    build-debug/
    build-whatever/
    src/
        CMakeLists.txt
        main.cpp
    external/
        CMakeLists.txt
        OpenCV/
            build-release/
            build-debug/
            build-whatever/
            src/
                <.git and the OpenCV repo>
        OtherLibrary/
            ... (same internal structure)
```

The CMakeLists.txt in external/ should get and build OpenCV at a specified branch when it's not there locally or it's out of date
The root CMakeLists.txt looks like this:
```
    cmake_minimum_required(VERSION 3.0)
    project(buubletea)

    find_package(Git REQUIRED)

    set(build-folder build-release)
        
    add_subdirectory(external)

    message(STATUS "Opencv directories")
    message(STATUS ${OpenCV_INCLUDE_DIR}) # displays nothing!

    add_executable(testProgram src/main.cpp)
    include_directories(${OpenCV_INCLUDE_DIR})
    target_include_directories(testProgram PUBLIC ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(testProgram opencv_core)
```
The one in the external/ folder looks like this

```
    include(ExternalProject)

    find_package (OpenCV PATHS OpenCV/${build-folder} NO_DEFAULT_PATH QUIET)
    #find_(OpenCV)
    if(NOT OpenCV_FOUND)
        message(STATUS "building a local OpenCV")
    
        ExternalProject_Add(OpenCV 
            PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/OpenCV/src
            GIT_REPOSITORY https://github.com/opencv/opencv.git
            GIT_TAG 3.1.0
            GIT_SHALLOW 1
            BUILD_DIR OpenCV/${build-folder})
    endif()
```

main.cpp is simple the example program 
http://docs.opencv.org/3.0-beta/doc/tutorials/introduction/display_image/display_image.html

So this will actually build OpenCV, but not quite correctly. The OpenCVConfig.cmake isn't created (so on subsquent runs find_packed() doesn't work) and OpenCV_INCLUDE_DIR isn't set correctly
So target_link_libraries() works, but at #include <opencv2/core/core.hpp> the compiler doesn't know where to look

**Comment by alalek** [comment]
This is CMake issue.

`ExternalProject_Add` + `find_package` sequence doesn't work by design:
> The ExternalProject_Add function creates a custom target to drive download, update/patch, configure, build, install and test steps of an external project

These targets are created only, but they don't run at all during your CMake configuration stage.

**Comment by geokon-gh** [comment]
I'm sorry, but I don't really understand. What do you mean by "they don't run" ? If the libraries and headers are created, why cant the variables be set?

**Comment by alalek** [comment]
CMake targets are executed during build stage only. Their results are not available during configuration stage (in your `.cmake` scripts).

There is nothing to fix/implement in OpenCV until CMake will provide mature support for this.

**Comment by geokon-gh** [comment]
Thank you, and sorry about the invalid issue.
If anyone else comes across this, here is the solution:

http://stackoverflow.com/questions/17446981/cmake-externalproject-add-and-findpackage/23570741#23570741

(you need to hack CMake to build the project during the configuration step)
