### ISSUE TITLE
compile opencv 3.1 on ubuntu 16.04 and CUDA 8.0.44 build error

### ISSUE THREAD

**Issue by OyunfanO** [opencv/opencv#7620]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => ubuntu16.04

##### Detailed description

after I used this command
 cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
an error occured as below
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "example_gpu_cascadeclassifier_nvidia_api" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_bgfg_segm" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_morphology" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_alpha_comp" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_farneback_optical_flow" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_opengl" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_video_reader" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_surf_keypoint_matcher" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_multi" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_video_writer" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_driver_api_stereo_multi" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_cascadeclassifier" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_super_resolution" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_generalized_hough" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_opticalflow_nvidia_api" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_driver_api_multi" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_stereo_multi" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_stereo_match" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_houghlines" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_optical_flow" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_pyrlk_optical_flow" in directory /home/ppz/opencv-3.1.0/samples/gpu
    linked by target "example_gpu_hog" in directory /home/ppz/opencv-3.1.0/samples/gpu

-- Configuring incomplete, errors occurred!
See also "/home/ppz/opencv-3.1.0/CMakeFiles/CMakeOutput.log".
See also "/home/ppz/opencv-3.1.0/CMakeFiles/CMakeError.log".

I don't know how to solve this problem, please help me 
[CMakeLists.txt](https://github.com/opencv/opencv/files/575326/CMakeLists.txt)

**Comment by gangyahaidao** [comment]
you have not install CUDA, or cannot find it
