### ISSUE TITLE
Build fails with C++11 enabled in MinGW-w64 5.3.0 - Different conditionals in Detection Based Tracker

### ISSUE THREAD

**Issue by ColinFinck** [opencv/opencv#7623]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 32 Bit
- Compiler => MinGW-w64 5.3.0 (as shipped with Qt 5.7)

##### Detailed description

In an attempt to compile OpenCV 3.1 with the Qt 5.7-bundled 32-Bit MinGW-w64 5.3.0 compiler and proper Qt GUI bindings, I needed to do "set CXXFLAGS=-std=gnu++11" prior to compiling. Otherwise, build fails at the Qt bindings, because latest Qt 5.7 can only be built with C++11 enabled.

With this option though, build fails at 74% in detection_based_tracker.cpp.
This code is only conditionally compiled and while I cannot totally figure out what platforms you want to exclude, the conditions should at least be the same in detection_based_tracker.cpp and detection_based_tracker.hpp. Currently, detection_based_tracker.cpp checks for __cplusplus > 199711L and detection_based_tracker.hpp wants __cplusplus > 201103L. In my opinion, this needs to be changed to > 199711L in the .hpp file. It fixes the problem for me.

##### Steps to reproduce

mkdir mingw_build
cd mingw_build
set CXXFLAGS=-std=gnu++11
cmake -D WITH_QT=ON -D WITH_OPENGL=ON -G "MinGW Makefiles" ../sources
mingw32-make

**Comment by StevenPuttemans** [comment]
Please provide a pull request with the suggested fix, so that this issue can be tracked more easily.

**Comment by kkorath** [comment]
Can I work on this issue?

**Comment by StevenPuttemans** [comment]
> Can I work on this issue?

Of course, anyone is free to supply a pull request to try and solve open issues.
