### ISSUE TITLE
Build failed ''_tzcnt_u32': identifier not found'- with Win10, CUDA v8.0, VS10

### ISSUE THREAD

**Issue by vicentepedro** [opencv/opencv#7626]
##### System information (version)

- OpenCV => 3.1 (commit d1bbc0b6e6c0c5115e54aa6d9f32a1d332a9538c -  Thu Nov 3 19:24:52)
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2010
- CUDA toolkit v8.0
##### Detailed description

Hi! 

I have the following git version of OpenCV - d1bbc0b6e6c0c5115e54aa6d9f32a1d332a9538c -

During a 64bit CUDA enable installation, the build failed with the following error:

1>..\..\..\modules\imgproc\src\contours.cpp(58): error C3861: '_tzcnt_u32': identifier not found

Thanks in advance.

**Comment by alalek** [comment]
Could you try to check with this updated condition:
```
#if (_MSC_VER < 1700)
    return _BitScanForward(value);
#else
    return _tzcnt_u32(value);
#endif
```

**Comment by vicentepedro** [comment]
It also fails:
`.\..\..\modules\imgproc\src\contours.cpp(56): error C2660: '_BitScanForward' : function does not take 1 arguments`

The function definition redirects to this:
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\intrin.h:
` _BitScanForward(unsigned long* Index, unsigned long Mask)`

Thanks ;)

**Comment by alalek** [comment]
Thanks!
Does #7629 work for you?

**Comment by vicentepedro** [comment]
Yes! 
Now the opencv_imgproc module compiles fine ;)

Thanks for the bug fixing
