### ISSUE TITLE
(GTypeFlags)NULL used in modules/highgui/src/window_gtk.cpp

### ISSUE THREAD

**Issue by OtacilioNeto** [opencv/opencv#7635]
##### System information (version)

- OpenCV => 3.1 
- Operating System / Platform => FreeBSD 11
- Compiler => Clang 3.8.0

##### Detailed description

The file modules/highgui/src/window_gtk.cpp uses (GTypeFlags)NULL about line 498. This line do not compile under clang 3.8.0 when C++ 11 is enabled. I think that this NULL must be replaced by 0

##### Steps to reproduce
Open file modules/highgui/src/window_gtk.cpp about line 498. About there is the NULL pointer.

**Comment by AlexCodeWarrior** [comment]
Hello, 

I'm new to github and open source. This is my first trying to fix a bug  and i have some prior experience programming in c++ . The question that i have  is once i have the program in my local computer can i debug with any IDE  and what is testsuite ? 

thanks

**Comment by souch55** [comment]
Hi,you can use eclipse plug in cdt import all lib path and headers in IDE ,build source in debug mode ,attach debugger like gdb,set break points and debug
