### ISSUE TITLE
I am using kali linux (git checkout issue), help please

### ISSUE THREAD

**Issue by AbdelrahmanHossam** [opencv/opencv#7661]
When i enter this command "git checkout 3.1.0"
i got this result "HEAD is now at 92387b1... Fix java version++"
and no checkout is done.

**Comment by vivekpatani** [comment]
Hello @AbdelrahmanHossam, no need to check out to that branch anymore, it has been merged with master and released to public as it has reached a stable point since Dec 18, 2015. Close the issue, if you think your issue is resolved. Also, why do you need to checkout to that branch/tag?

**Comment by alalek** [comment]
Try `git checkout master` / `git checkout origin/master`.
