### ISSUE TITLE
error when running scripts/cmake_android_arm.sh

### ISSUE THREAD

**Issue by dec1** [opencv/opencv#7669]
##### System information (version)

- OpenCV =>2.4
- Operating System / Platform =>Host Linux cross compiling for target Android (arm)
- Compiler => gnu-4.9 (arm-linux-androideabi-4.9)

##### Detailed description

Can't execute his script to configure cmake with the current version of (Android Studio and) Google NDK
 installed because cmake expects android platform-8 but only version 9 and and later ship with the NDK anymore. 
So need pass a parameter to this script to override the default platform version

##### Steps to reproduce
Install current [Android Studio](https://developer.android.com/studio/index.html) with NDK and CMake.

clone opencv repo from github and checkout the "2.4" branch.
```

cd  ${path_to_opencv_from_github}/platforms

export PATH=${path_to_android_studio_sdk}/cmake/3.6.3155560/bin:$PATH
export ANDROID_NDK=${path_to_android_studio_sdk}/ndk-bundle

sh ./scripts/cmake_android_arm.sh
```

(Would be fixed by [pull request 7672](https://github.com/opencv/opencv/pull/7672))

**Comment by alalek** [comment]
You can pass custom parameters directly to script:
```
scripts/cmake_android_arm.sh -DANDROID_NATIVE_API_LEVEL=9
``

P.S. Also you can take a look on this scripts for Android pack build (but it is targeted for Android NDK 8 (latest is NDK-r8e) and GCC 4.6 for binary compatibility reasons): https://github.com/opencv/opencv/blob/2.4/platforms/android/build_sdk.py

**Comment by dec1** [comment]
Surely the default version for android ndk should be one of those google ships?

**Comment by alalek** [comment]
OpenCV 2.4 are "lost" with NDK 8-e and GCC 4.6 (for arm). Breaking changes can not be accepted.
