### ISSUE TITLE
Cmake and variable name Protobuf or PROTOBUF is it same Name?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#7674]
Hi,
I am using Opencv 3.1.0-dev and VS 2015 and CMAKE 3.7.0.rc2.
I am wondering why there is two names for protobu and eigen. 
Example
PROTOBUF_INCLUDE_DIR=C:/Program Files/protobuf/include
Protobuf_INCLUDE_DIR=Protobuf_INCLUDE_DIR-NOTFOUND
in same CMakeCache.txt  and CMakeVars.txt
and conclusion is Protobuf:   NO 
and I have got protobuf on my computer.

[CMakeCache.txt](https://github.com/opencv/opencv/files/591485/CMakeCache.txt)
[CMakeVars.txt](https://github.com/opencv/opencv/files/591478/CMakeVars.txt).

**Comment by mshabunin** [comment]
There are several modules in opencv_contrib using protobuff and each one have its own search mechanism. Message `Protobuf: NO` comes from _cnn_3dobj_ module, and variable `PROTOBUF_INCLUDE_DIR` is set by _dnn_ module which have been able to find it. You can report an issue to the opencv_contrib repository about this problem.

Not sure about eigen, need more details.

**Comment by LaurentBerger** [comment]
About eigen there is 
EIGEN_INCLUDE_PATH  value EIGEN_INCLUDE_PATH-NOTFOUND

and 

EIGEN_INCLUDE_DIR value f:/lib/eigen-eigen

I will report an issue to opencv_contrib
👍
