### ISSUE TITLE
homebrew's opencv(2,3) has been broken for 2 months

### ISSUE THREAD

**Issue by timotheecour** [opencv/opencv#7680]
just pinging here in case it's due to upstream bug in opencv
https://github.com/Homebrew/homebrew-science/issues/4399 (linuxbrew)

**Comment by alalek** [comment]
Extracted error message from logs:
```
<path>/temp/stage/brew/lib/libIlmImf-2_2.so.22: undefined reference to `Iex_2_2::BaseExc::BaseExc(std::string const&)'
<path>/temp/stage/brew/lib/libIlmImf-2_2.so.22: undefined reference to `Iex_2_2::BaseExc::assign(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)'
<path>/temp/stage/brew/lib/libIlmImf-2_2.so.22: undefined reference to `Iex_2_2::throwErrnoExc(std::string const&)'
<path>/temp/stage/brew/lib/libIlmImf-2_2.so.22: undefined reference to `Iex_2_2::BaseExc::BaseExc(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
```

Looks like mentioned library build is not compatible with OpenCV (probably there is different compiler version or compiler flags) or some dependencies are lost.

You can try these options:
- disable OpenEXR support via CMake option `-DWITH_OPENEXR=OFF`
- or build OpenEXR library from sources located in OpenCV 3rdparty folder (it is not fresh, but it is compatible): `-DBUILD_OPENEXR=ON`

**Comment by keevee09** [comment]
I compiled it OK yesterday after setting
sudo xcode-select -switch /Applications/Xcode-7.3.app
I had downloaded xcode-7.3 dmg from apple's website, installed it then changed the name so I could keep the current Xcode.app up-to-date (8.1)
That said, quite a few of the tests are failing. The first one I'm tracking down is an inability to play video files which implies that it didn't build with ffmpeg support which I have installed via homebrew.
It can play the webcam, just not files.

**Comment by timotheecour** [comment]
note, this was for linuxbrew, not on mac

**Comment by mshabunin** [comment]
Try to reinstall _openexr_ with _universal_ option:
```
brew uninstall openexr
brew install openexr --universal
brew install opencv
```
Looks like the problem is in default version of OpenEXR provided by linuxbrew, because I was able to build OpenCV with own packaged OpenEXR (1.7.0 ~ [3rdparty/openexr](https://github.com/opencv/opencv/tree/master/3rdparty/openexr)) and with system OpenEXR (2.2.0 ~ `apt install libopenexr-dev`).

Feel free to reopen if you have more details.

**Comment by timotheecour** [comment]
doesn't work for me:
```
git clone https://github.com/Linuxbrew/brew.git  
cd brew/bin
./brew install openexr --universal 
```

==> ./configure --prefix=/home/parallels/temp/brew/Cellar/openexr/2.2.0
Last 15 lines from /home/parallels/.cache/Homebrew/Logs/openexr/01.configure:
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for compress in -lz... no
configure: error:
*** OpenEXR requires a recent version of zlib, which you don't appear to
*** have.
***
*** This could be because the run-time linker is not finding zlib, or it
*** is finding the wrong version.  In this case, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the proper version.  Also, make sure you have run ldconfig if
*** that is required on your system.

**Comment by mshabunin** [comment]
What is your platform? Please post output of `uname -a` and `gcc --version`.

If nothing helps, use `--without-openexr` option when installing OpenCV.

**Comment by timotheecour** [comment]
re-posting from
https://github.com/Homebrew/homebrew-science/issues/4399#issue-181031751

```
(used to work)
ubuntu 16.04:
brew gist-logs homebrew/science/opencv
https://gist.github.com/5949e4f2a2b1e304e82dc28b83514239

ubuntu 14.04:
brew gist-logs homebrew/science/opencv
https://gist.github.com/5ed499c3abfd54df8871fa3206dec251

uname -a
Linux katrina 4.2.0-18-generic #22~14.04.1-Ubuntu SMP Fri Nov 6 22:20:11 UTC 2015 x86_64 GNU/Linux

gcc --version
gcc (Homebrew gcc 5.3.0) 5.3.0
```

```
./bin/brew install opencv --without-openexr
make: *** [Makefile:164: all] Error 2
```
```

**Comment by alalek** [comment]
> until this issue is fixed

> probably there is different compiler version or compiler flags

There is nothing to fix in OpenCV directly. It is external dependencies configuration issue. For example, `std::string` is not binary compatible between C++98 and C++11 GCC compilation modes (no idea how openexr is built in linuxbrew).

**Comment by mshabunin** [comment]
@timotheecour , I successfully built OpenCV 2.4.13 in fresh Ubuntu 16.04 using the following docker container:
```Dockerfile
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y \
    build-essential curl git python-setuptools ruby python-dev

RUN locale-gen en_US.UTF-8
ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US"
ENV LC_ALL="en_US.UTF-8"

ARG UNAME=test
ARG UID
ARG GID
RUN groupadd -g $GID $UNAME
RUN useradd -m -u $UID -g $GID -s /bin/bash $UNAME

USER $UNAME

RUN ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
ENV PATH="/home/$UNAME/.linuxbrew/bin:$PATH"

CMD /bin/bash
```
Then run in container:
```.sh
$ brew install homebrew/science/opencv --without-openexr 
...
... some dependencies
...
==> Installing homebrew/science/opencv
==> Downloading https://github.com/opencv/opencv/archive/2.4.13.1.tar.gz
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/test/.linuxbrew/Cellar
==> make
==> make install
🍺  /home/test/.linuxbrew/Cellar/opencv/2.4.13.1: 272 files, 33.0M, built in 5 minutes 37 seconds
```
I agree with @alalek , there is still no evidence of any problem in OpenCV. Looks like a local configuration problem, maybe conflict between brew and system libraries/programs.

**Comment by timotheecour** [comment]
tried on several ubuntu 16.04 machines (including parallels) [but not via docker]

brew install -v homebrew/science/opencv --without-openexr

is this normal in the log? (see items marked WEIRD)

```
#WEIRD??
Usage: /home/timothee/ubuntu1604/brew/bin/python-config [--prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--help]
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/kat/home/timothee/ubuntu1604/brew/Cellar/opencv/2.4.13.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_WITH_INSTALL_RPATH=1 -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1 -DCMAKE_OSX_DEPLOYMENT_TARGET= -DBUILD_ZLIB=OFF -DBUILD_TIFF=OFF -DBUILD_PNG=OFF -DBUILD_OPENEXR=OFF -DBUILD_JASPER=OFF -DBUILD_JPEG=OFF -DJPEG_INCLUDE_DIR=/kat/home/timothee/ubuntu1604/brew/opt/jpeg/include -DJPEG_LIBRARY=/kat/home/timothee/ubuntu1604/brew/opt/jpeg/lib/libjpeg.so -DBUILD_opencv_python=ON -DBUILD_opencv_java=OFF -DWITH_OPENEXR=OFF -DWITH_EIGEN=ON -DWITH_TBB=OFF -DWITH_FFMPEG=OFF -DWITH_QUICKTIME=OFF -DWITH_1394=OFF -DWITH_OPENGL=OFF -DWITH_JASPER=OFF -DWITH_GSTREAMER=OFF -DWITH_XIMEA=OFF -DWITH_VTK=OFF -DPYTHON_LIBRARY=/libpython2.7.so -DPYTHON_INCLUDE_DIR=/kat/home/timothee/ubuntu1604/brew/Cellar/python/2.7.12_1/include/python2.7 -DWITH_CUDA=OFF -DWITH_OPENCL=OFF

#WEIRD? -DPYTHON_LIBRARY=/libpython2.7.so

Last 15 lines from /home/timothee/.cache/Homebrew/Logs/opencv/02.make:
#WEIRD?
```

**Comment by timotheecour** [comment]
@mshabunin : note that other ppl are having the same issue [https://github.com/Homebrew/homebrew-science/issues/4399]

**Comment by timotheecour** [comment]
> Looks like a local configuration problem, maybe conflict between brew and system libraries/programs.

Indeed that was the case, the build would fail depending on whether brew had installed python-config, just wrote https://github.com/Homebrew/homebrew-science/pull/4750 that would fix this
