### ISSUE TITLE
Hanging functions with UMat

### ISSUE THREAD

**Issue by ZZPot** [opencv/opencv#7684]
cvtColor: hangs with output UMat argument and with CV_BGR2RGB
divide: hangs with output UMat argument
log: hangs with output UMat argument

##### Steps to reproduce
https://github.com/ZZPot/UMat-hangs

##### System information
- OpenCV => 3.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

**Comment by alalek** [comment]
Please add OpenCL device and OpenCL driver version.

Are you able to complete OpenCV "OCL*" [tests](https://github.com/opencv/opencv/wiki/QA_in_OpenCV#c-tests) from core/imgproc modules?

**Comment by xsacha** [comment]
I noticed when I do not have an OpenCV driver installed, some UMat tests in my code take twice as long to run as compared to using Mat.
Is there not some way to fail quickly and revert to not using OpenCL when OpenCL is not detected? Otherwise it is not safe to use without checking the user has it first.

**Comment by ZZPot** [comment]
```
Current OpenCL device: 
    Type = dGPU
    Name = GeForce GTS 250
    Version = OpenCL 1.0 CUDA
    Compute units = 16
    Max work group size = 512
    Local memory size = 15 kB 1023 B
    Max memory allocation size = 128 MB 
    Double support = No
    Host unified memory = No
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 0
```
From OCL_Core/Gemm.Accuracy/9 to the end (OCL_Core/Gemm.Accuracy/63) were failed. Sorry for late answer. imgproc testing hangs but what it returns has some OCL failed tests. I just dunno how to fix it.
