### ISSUE TITLE
Install opencv on mac

### ISSUE THREAD

**Issue by great-thoughts** [opencv/opencv#7693]
I am trying to install opencv on my mac
` cd ~/opencv mkdir release cd release cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local .. make`

I get the following error,
` ld: framework not found CoreImage clang: error: linker command failed with exit code 1 (use -v to see invocation) make[2]: * [lib/libopencv_videoio.3.1.0.dylib] Error 1 make[1]: [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2 make: ** [all] Error 2`

**Comment by mshabunin** [comment]
Duplicate of #7606
