### ISSUE TITLE
New chessboard detection fails where old detection would have succeeded

### ISSUE THREAD

**Issue by jeremysalwen** [opencv/opencv#7706]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => OSX
- Compiler => Apple LLVM version 8.0.0 (clang-800.0.42.1)

##### Detailed description

The chessboard detection in the latest opencv fails on the example image attached.  When I compile opencv with DEBUG_CHESSBOARD enabled, I can see that the binarization step fails.  Additionally, the DEBUG_CHESSBOARD option causes it to display the "old binarization" which properly detects the chessboard.  I have attached images illustrating this.

The application I am using is the https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/samples/cpp/calibration.cpp example app.

##### Steps to reproduce
<img width="1282" alt="screen shot 2016-11-22 at 3 53 24 pm" src="https://cloud.githubusercontent.com/assets/450638/20553697/83930c88-b124-11e6-8a42-73d644d0b357.png">
<img width="1314" alt="screen shot 2016-11-22 at 3 53 51 pm" src="https://cloud.githubusercontent.com/assets/450638/20553698/83a5e18c-b124-11e6-982e-2fa620b77942.png">

![img3](https://cloud.githubusercontent.com/assets/450638/20553745/cb033dfe-b124-11e6-909c-66f092524128.png)

**Comment by LaurentBerger** [comment]
You cannot say it's a bug. Method failed with your image. Some method do a good job in a context and are bad in other context. Now method need to be improved. I think there is some test method in opencv about chessboard detection.

**Comment by jeremysalwen** [comment]
I think I misunderstood what happened with the chessboard detection. When
built with the debug chessboard option, I also upgraded to the latest
master.

It seems that both the old and new method are used now, and at least the
last time I ran it, overall it successfully detected this chessboard.

**Comment by mshabunin** [comment]
What parameters did you use?
For me running `./bin/cpp-example-calibration -w=6 -h=8 -o=camera.yml list.yml` gives chessboard corners on your image.
New algorithm should be faster than old, that is why it is used first. Failed first stage does not mean whole algorithm fails, so it is not a problem.
