### ISSUE TITLE
throw_no_cuda in video_reader.cpp with CUDA 8.0

### ISSUE THREAD

**Issue by gopalkildoliya** [opencv/opencv#7749]
While running the example https://github.com/opencv/opencv/blob/master/samples/gpu/video_reader.cpp I am getting an error:

    OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current     build or platform) in throw_no_cuda, file /home/gopal/opencv-3.0.0/modules/core/include/opencv2/core/private.cuda.hpp, line 101
    terminate called after throwing an instance of 'cv::Exception'
    what():  /home/gopal/opencv-3.0.0/modules/core/include/opencv2/core/private.cuda.hpp:101: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda
    
    Aborted (core dumped)

I have CUDA 8.0 on my system and I am building OpenCV with CUDA Support.

**Comment by alalek** [comment]
> The called functionality is disabled for current build or platform

This is the problem.

Try to add `WITH_NVCUVID=ON` CMake option and rebuild OpenCV.

**Comment by gopalkildoliya** [comment]
Hi @alalek Its working fine now with video files but when I am trying to open a network stream like `rtsp://192.168.0.65` it gives some errors as:

    OpenCV Error: Gpu API call (CUDA_ERROR_FILE_NOT_FOUND [Code = 301]) in CuvidVideoSource, file /home/gopal/opencv-3.0.0/modules/cudacodec/src/cuvid_video_source.cpp, line 66
    OpenCV Error: Assertion failed (init_MediaStream_FFMPEG()) in FFmpegVideoSource, file /home/gopal/opencv-3.0.0/modules/cudacodec/src/ffmpeg_video_source.cpp, line 101
    terminate called after throwing an instance of 'cv::Exception'
    what():  /home/gopal/opencv-3.0.0/modules/cudacodec/src/ffmpeg_video_source.cpp:101: error: (-215) init_MediaStream_FFMPEG() in function FFmpegVideoSource

    Aborted (core dumped)

**Comment by alalek** [comment]
Please ask usage questions and current limitations on OpenCV User Q/A forum: http://answers.opencv.org
