### ISSUE TITLE
[Mac] Cannot specify link libraries for target "opencv_world" when building OSX framework

### ISSUE THREAD

**Issue by skylook** [opencv/opencv#7759]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Mac OSX 10.12
- Compiler => Xcode 8.1

##### Detailed description

When building a frame of OSX, I got an error:
CMake Error at cmake/OpenCVUtils.cmake:826 (target_link_libraries):
  Cannot specify link libraries for target "opencv_world" which is not built
  by this project.

When run script of plarforms/osx/build_framework.py

**Comment by bwahacker** [comment]
I hit this today as well--[Mac OS X 10.11, Xcode 7.3.1].  Reading the ReadMe put me on the right path and I was able to build:

$  cd top-of-src
$  cmake 
$  mkdir release
$  cd release/
$  cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..

I then hit [this issue](https://github.com/opencv/opencv/issues/6315) but it was easy to fix with the patch from comment 1.

**Comment by alalek** [comment]
@bwahacker Build script for OSX framework is here: https://github.com/opencv/opencv/tree/master/platforms/osx
