### ISSUE TITLE
Compile CUDA 5.0 or 6.0 and OpenCV 3.1 on Windows (Use Cuda:  NO)

### ISSUE THREAD

**Issue by arvanus** [opencv/opencv#7766]
- OpenCV => 3.1
- Operating System / Platform => Windows 7 64 bit
- Compiler => Visual Studio 2012 Express and 2015 Express
- Cuda => 5.0 and 6.0
- GPU => GeoForce GT 550M

 
Hi, I need to use `cv::cudacodec::createVideoWriter`, basically on windows OR/AND linux, I tried to use cuda 8, but it miss Win32 functionalities (from what I noticed) and failed to make it work.
Now I'm trying to build CUDA 5.0/6.0 and I got some problems:
I use CMake 3.6.3 with successfully found CUDA 5.0, but I got: 
>     Use Cuda:                    NO
What can I do? 
Thanks
[CMakeVars.txt](https://github.com/opencv/opencv/files/624618/CMakeVars.txt)
[CMake VS2015+Cuda5 win32.txt](https://github.com/opencv/opencv/files/624621/CMake.VS2015.Cuda5.win32.txt)

**Comment by alalek** [comment]
CMake log shows that you didn't build from scratch (clean build directory) - it is necessary in case of  configuration or environment changes.

**Comment by arvanus** [comment]
Ok, so I run "File->Delete Cache" and deleted my "C:/openCV310/build/x32/vc14" folder, here is the new logs:
[CMake VS2015+Cuda5 win32 clean dir log.txt](https://github.com/opencv/opencv/files/624672/CMake.VS2015.Cuda5.win32.clean.dir.log.txt)
[CMakeCache clean dir log.txt](https://github.com/opencv/opencv/files/624673/CMakeCache.clean.dir.log.txt)
[CMakeVars clean dir log.txt](https://github.com/opencv/opencv/files/624674/CMakeVars.clean.dir.log.txt)

Thanks

**Comment by alalek** [comment]
Try to specify `CUDA_SDK_ROOT_DIR` manually via CMake option:
```
cmake "-DCUDA_SDK_ROOT_DIR=C:/Program Files/NVIDIA..." ...
```

**Comment by jet47** [comment]
Minimal supported CUDA version is 6.5.

**Comment by alalek** [comment]
@jet47 Thank you for clarification!

**Comment by arvanus** [comment]
Hi, sorry for being so late.
So, I tried to build from scratch with Cuda 6.5 + VS 2012 Express. Finally it compiled but Cuda 6.5 (and 8.0, **I didn't tested on 7.0 yet**) don't have nvcuvenc.lib anymore, and openCV build without enabling HAVE_NVCUVENC on CMake...
So, everything builds well, but not video_writer.cpp, because at line 50 we have:
```
#if !defined(HAVE_NVCUVENC) || !defined(WIN32)

cv::cudacodec::EncoderParams::EncoderParams() { throw_no_cuda(); }
cv::cudacodec::EncoderParams::EncoderParams(const String&) { throw_no_cuda(); }
void cv::cudacodec::EncoderParams::load(const String&) { throw_no_cuda(); }
void cv::cudacodec::EncoderParams::save(const String&) const { throw_no_cuda(); }

Ptr<VideoWriter> cv::cudacodec::createVideoWriter(const String&, Size, double, SurfaceFormat) { throw_no_cuda(); return Ptr<VideoWriter>(); }
Ptr<VideoWriter> cv::cudacodec::createVideoWriter(const String&, Size, double, const EncoderParams&, SurfaceFormat) { throw_no_cuda(); return Ptr<VideoWriter>(); }

Ptr<VideoWriter> cv::cudacodec::createVideoWriter(const Ptr<EncoderCallBack>&, Size, double, SurfaceFormat) { throw_no_cuda(); return Ptr<VideoWriter>(); }
Ptr<VideoWriter> cv::cudacodec::createVideoWriter(const Ptr<EncoderCallBack>&, Size, double, const EncoderParams&, SurfaceFormat) { throw_no_cuda(); return Ptr<VideoWriter>(); }

#else // !defined HAVE_NVCUVENC || !defined WIN32
.... the real (and disabled) code
```

Any idea?
Thanks

**Comment by alalek** [comment]
This interface is deprecated and removed from modern version of CUDA.
Looks like there is new NVIDIA API, but OpenCV doesn't support it: https://developer.nvidia.com/nvidia-video-codec-sdk

**Comment by arvanus** [comment]
Ok, so, my impression is that at Cuda 6.0 there was support for this interface, correct?
Which old OpenCV version do you recommend for me to use with the old Cuda 6.0?

Just to explain my needs: I'm coding an video surveillance software system for some IP Cameras, but with just 8 cameras the CPU usage get almost 90% of CPU time, so I trying to use my GPU to do that. Can you recommend something to me?
Also, there is an prevision from OpenCV to re-implement this feature?

Thanks

**Comment by arvanus** [comment]
Just for record:
 I did it working with Cuda 6.0 + VS2012 by doing 2 changes: 
At 

> cmake/OpenCVMinDepVersions.cmake

change
`set(MIN_VER_CUDA 6.0)`
and at 

> modules/core/include/opencv2/core/private.cuda.hpp

`#  define CUDART_MINIMUM_REQUIRED_VERSION 6000`

Doing it I could compile and use `cv::cudacodec::createVideoWriter`
Thanks
