### ISSUE TITLE
Why doesn't opencv erase the data type when using function `at()` ?

### ISSUE THREAD

**Issue by thesby** [opencv/opencv#7784]
It's very confusing when I use function `at()`, because it needs the data type, for example, ` at< float >() `. But after transformation by functions of opencv, the data type is often changed. So I can not easily use `at`.
What about erase the data type just like `numpy` ? Or add a data field `dtype`?

**Comment by kinchungwong** [comment]
See https://github.com/opencv/opencv/issues/7477 for possible solutions.

**Comment by paroj** [comment]
also if you do not care about performance you can do:
```cpp
img(Rect(Point(x, y), Size(1, 1))) = Scalar(r,g,b);
```

**Comment by vpisarev** [comment]
numpy does not care about efficiency, opencv does; if you want to support multiple types in your algorithm, implement it as template function
