### ISSUE TITLE
cv::putText regression

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#7785]
##### System information (version)
- OpenCV => master
- Operating System / Platform => Win7 x64
- Compiler => **MSVS 2010 32-bit** (MSVS 2012/2015 32/64-bit are fine)

##### Detailed description

Example of generated input data for test: `Videoio_Video.seek_random_synthetic`

OpenCV 3.1.0:
![opencv-3 1 0](https://cloud.githubusercontent.com/assets/4981219/20859569/d6c31030-b96a-11e6-9509-a7bcb433a8d5.png)

OpenCV master:
![opencv-master](https://cloud.githubusercontent.com/assets/4981219/20859570/e4e9c9ce-b96a-11e6-9efc-0f9928d85e7c.png)

Probably related: #7458 #7161

**Comment by chacha21** [comment]
it seems to be related to edge[].x not initialized in FillConvexPoly
