### ISSUE TITLE
Internal compiler error in mathfuncs_core.cpp(1239) when enabling AVX

### ISSUE THREAD

**Issue by patrikhuber** [opencv/opencv#7795]
##### System information (version)
- OpenCV => Newest GitHub master from today
- Operating System / Platform =>Windows 8.1 64 Bit
- Compiler => Visual Studio 2015 Update 3

##### Detailed description
I get an internal compiler error (ICE) when building opencv_core in Release mode, on above system.

> 1>c:\opencv\opencv-git\opencv\modules\core\src\mathfuncs_core.cpp(1239): fatal error C1001: An internal error has occurred in the compiler.

The error appears as soon as you enable `ENABLE_AVX`. Disabling AVX and it works again. Debug build works fine as well.
My CPU supports AVX (i7-4700MQ).

##### Steps to reproduce

Compile opencv_core from GitHub master with `ENABLE_AVX` on VS2015 update 3, 64-bit, Release build.

Disabling IPP didn't help. I tried disabling pretty much everything else too (OpenMP, OpenCL, etc.) and it didn't help.

**Comment by patrikhuber** [comment]
Just for reference, the ICE doesn't happen anymore in VS2017RC.

**Comment by alalek** [comment]
Please add your `cl` version.

**Comment by patrikhuber** [comment]
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

**Comment by alalek** [comment]
Thank you! I can confirm this problem.
