### ISSUE TITLE
CMake targets don't update properly in VS2017RC

### ISSUE THREAD

**Issue by patrikhuber** [opencv/opencv#7813]
##### System information (version)
- OpenCV => master from today
- Operating System / Platform =>Win 8.1-64
- Compiler => VS2017RC
- CMake => 3.7.1

##### Detailed description

CMake targets don't update properly. For example, generate a solution with the VS2017 - Win64 generator with default build options, open in VS, build it. Then, change some options in cmake-gui or on the commandline, like `BUILD_opencv_stitching:BOOL="0"` or `BUILD_TESTS:BOOL="1"`, and re-generate the solution, and re-load it in VS. The solution updates, but it doesn't contain the changes you've made, i.e. the modules you changed are not added/removed.

This is possibly related to #7803, and maybe #7796.

##### Steps to reproduce

I was using this minimal OpenCV build configuration, but you can use any, and then just change some variables:

`cmake ..\opencv -DWITH_1394:BOOL="0" -DWITH_LAPACK:BOOL="0" -DBUILD_PACKAGE:BOOL="0" -DBUILD_opencv_ts:BOOL="1" -DENABLE_SSE42:BOOL="1" -DBUILD_opencv_photo:BOOL="0" -DBUILD_opencv_apps:BOOL="0" -DBUILD_opencv_superres:BOOL="0" -DBUILD_opencv_videoio:BOOL="0" -DINSTALL_TESTS:BOOL="1" -DBUILD_opencv_stitching:BOOL="0" -DBUILD_DOCS:BOOL="0" -DBUILD_opencv_highgui:BOOL="0" -DBUILD_opencv_ml:BOOL="0" -DBUILD_TESTS:BOOL="0" -DBUILD_opencv_video:BOOL="0" -DWITH_JASPER:BOOL="0" -DWITH_GSTREAMER:BOOL="0" -DWITH_EIGEN:BOOL="0" -DENABLE_AVX:BOOL="1" -DWITH_OPENCLAMDFFT:BOOL="0" -DBUILD_opencv_objdetect:BOOL="0" -DBUILD_opencv_shape:BOOL="0" -DENABLE_SSSE3:BOOL="1" -DBUILD_opencv_flann:BOOL="0" -DWITH_OPENCLAMDBLAS:BOOL="0" -DWITH_WEBP:BOOL="0" -DWITH_MATLAB:BOOL="0" -DBUILD_opencv_imgcodecs:BOOL="0" -DWITH_OPENEXR:BOOL="0" -DENABLE_SSE41:BOOL="1" -DENABLE_AVX2:BOOL="1" -DWITH_CUFFT:BOOL="0" -DBUILD_opencv_calib3d:BOOL="0" -DBUILD_opencv_features2d:BOOL="0" -DWITH_OPENCL:BOOL="1" -DWITH_IPP:BOOL="0" -DWITH_CUDA:BOOL="0" -DBUILD_opencv_videostab:BOOL="0" -DBUILD_JASPER:BOOL="0" -DBUILD_OPENEXR:BOOL="0" -DBUILD_opencv_imgproc:BOOL="0" -DWITH_VTK:BOOL="0" `

**Comment by alalek** [comment]
Looks like there is CMake/VS2017 bug.
