### ISSUE TITLE
OpenCV 3.1 MSER python sample not working

### ISSUE THREAD

**Issue by moskiteau** [opencv/opencv#7821]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => ubuntu 16.04
- Compiler => python 2.7

##### Detailed description

When I try to run the example I have this error:

`Traceback (most recent call last):
  File "/usr/local/share/OpenCV/samples/python/mser.py", line 35, in <module>
    regions = mser.detectRegions(gray, None)
TypeError: MSER.detectRegions() takes at most 1 argument (2 given)`

And if I remove the None argument:

`  File "mser.py", line 47, in <module>
    hulls = [cv2.convexHull(p.reshape(-1, 1, 2)) for p in regions]
AttributeError: 'list' object has no attribute 'reshape'`

**Comment by wangwangww** [comment]
I have the same problem
