### ISSUE TITLE
Error when making OpenCV 3.1 with CUDA support.

### ISSUE THREAD

**Issue by mdornfe1** [opencv/opencv#7823]
##### Detailed description
I get an error when trying to make opencv 3.1 with CUDA support. Here is the full print out of the error http://pastebin.com/wWytmBKH.

##### Steps to reproduce

Here is my install script http://pastebin.com/2CAs4Y23. The error occurs on line make -j4.

**Comment by alalek** [comment]
You need to use latest master (trunk version of code).
OpenCV 3.1 is released before CUDA 8.0 release, so it doesn't contain support fixes.
