### ISSUE TITLE
OpenCV building with Tesseract using OpenCL cmake modification

### ISSUE THREAD

**Issue by Marware** [opencv/opencv#7824]
##### System information (version)

- OpenCV => master
- Operating System / Platform => Ubuntu 16.04 64bit
- Tesseract with OpenCL => master

##### Detailed description

Building Tesseract with OpenCL then building OpenCV with opencv_contrib produces undefined reference to OpenCL libraries from libtesseract

`//usr/local/lib/libtesseract.so.4: undefined reference to `clEnqueueCopyBuffer'
//usr/local/lib/libtesseract.so.4: undefined reference to `clEnqueueUnmapMemObject'
//usr/local/lib/libtesseract.so.4: undefined reference to `clCreateProgramWithBinary'
//usr/local/lib/libtesseract.so.4: undefined reference to `clGetDeviceIDs'
...
`
Fixed this by adding OpenCL library to opencv_contrib/modules/text/cmake/FindTesseract.cmake

**Comment by alalek** [comment]
> Fixed this by adding OpenCL library

Magic fixes should be avoided.

You need to provide CMake module for Tesseract (for `find_package` command): check for files TesseractConfig.cmake or FindTesseract.cmake and add path to them via `CMAKE_MODULES_PATH` or `CMAKE_PREFIX_PATH`.
Also you can provide Tesseract pkg-config file (check tesseract install directory for it) which contains correct dependencies (RTM `PKG_CONFIG_PATH`).
What files do you have?
