### ISSUE TITLE
SolvePnPRansac reprojectionError is the squared error

### ISSUE THREAD

**Issue by hovren** [opencv/opencv#7827]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => All
- Compiler => All

##### Detailed description

The `reprojectionError` parameter used by RANSAC to determine inliers is
interpreted as the squared reprojection error instead of the regular one.

The RANSAC code uses a squared threshold as we can see in [ptsetreg.cpp:94](https://github.com/opencv/opencv/blob/c17afe0fab61bb11452b36fb94eaeb405293e086/modules/calib3d/src/ptsetreg.cpp#L94)
but the PnP callback uses normalizes the distance, as we see in [solvepnp.cpp:200](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/calib3d/src/solvepnp.cpp#L200)

**Comment by sovrasov** [comment]
@hovren could you provide a PR which fixes it?

**Comment by hovren** [comment]
Honestly, I have no idea where the fix should go, because there are three options:

1. `RANSACPointSetRegistrator::find_inliers()` should not square the threshold and then that's where the fix goes. However, I have no idea whether this would break something else.

1. `PnPRansacCallback::computeError()` should compute the squared error.

1. Both of the above, with the addition that the threshold should be expliticly squared by `SolvePnPRansac()` before passing it to `RANSACPointSetRegistrator`.

**Comment by sovrasov** [comment]
I think second variant is the most suitable since other Registrators use squared error.

**Comment by ShawnLe** [comment]
This issue still appears in 3.4.1. solvepnp is fixed with norm square root, but in ptsetreg.cpp::RANSACPointSetRegistrator, Its findInliers (Line 86) still compares with thres squared Line 93:
        uchar* maskptr = mask.ptr<uchar>();
        float t = (float)(thresh*thresh);
        int i, n = (int)err.total(), nz = 0;
