### ISSUE TITLE
Cocoa Application VideoCapture crashes on release() using AVFoundation 

### ISSUE THREAD

**Issue by aprowe** [opencv/opencv#7833]
##### System information (version)
- OpenCV => Dec 7th HEAD (2341222672a24d143ae08b8ccaa0c030bc728db9)
- Operating System / Platform => Mac 10.11 / 10.12
- Compiler => Xcode

##### Detailed description
We are trying to use an AVFoundation build of opencv_videoio in our macOS app. 
It is able to open the webcam and read from it, but once release is called, a EXC_BAD_ACCESS Error is thrown. Here are stack traces caught by Zombies. I wasn't sure exactly what is relevant in the zombie report. Here's a screenshot. 

![screen shot 2016-12-09 at 3 16 07 pm](https://cloud.githubusercontent.com/assets/7191456/21064782/79e8dcca-be22-11e6-879d-196656173dd1.png)

Stepping through the code, It successfully turns the camera off, exits release(), and continue program flow, and another thread crashes the program each time. 

It does NOT crash on a blank c++ command line project, only happens in a cocoa app. 

We have tried running both on Sierra and El Capitan.
We chose to use AVFoundation to support Sierra, and chose to not use FFMpeg. Are there any other build options to consider?

##### Steps to reproduce
Build openCV with 
```
WITH_AVFOUNDATION=YES
WITH_FFMPEG=NO
WITH_QT=NO
WITH_QUICKTIME=NO
```

Create an empty Cocoa Project, 
and in ApplicationDidFinishLaunching put basic VideoIO capture calls in 
```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
  cv::VideoCapture cap(0);
  cap.release();
}
```

**Comment by jbyu** [comment]
In cap_avfoundation_mac.mm, function CvCaptureCAM::stopCaptureDevice, comment this line [mCaptureDevice release];

**Comment by aprowe** [comment]
This fixed it, thank you!

**Comment by aprowe** [comment]
Unfortunately I found that removing the release call caused a memory leak each time `VideoCapture::read()` was called. `CMSampleBuffer` is the leaked object which comes from  a `[AVAssetReaderOutput copyNextSampleBuffer]`. 

I'll continue to look for a solution that fixes it properly.
