### ISSUE TITLE
Trouble running dnn module sample program

### ISSUE THREAD

**Issue by kevgeo** [opencv/opencv#7834]
##### System information (version)
Example
- OpenCV => 3.1.0
- Operating System / Platform => Ubuntu 14.04
- Compiler => g++ 4.8.4

##### Detailed description
I am using Opencv 3.1.0 on ubuntu 14.04. I have successfully built Opencv and wanted to try reading a caffe model and classifying.

I used the program and models from this [tutorial](http://docs.opencv.org/trunk/d5/de7/tutorial_dnn_googlenet.html)

I am able to compile the program but running it gives me the error below-

`OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "bvlc_googlenet.prototxt") iReadProtoFromTextFile, file /home/kevmepls/opt/opencv_contrib/modules/dnn/src/caffe/caffe_io.cpp, line 1077
Can't load network by using the following files: 
prototxt:   bvlc_googlenet.prototxt
caffemodel: bvlc_googlenet.caffemodel
bvlc_googlenet.caffemodel can be downloaded here:
http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel`

All the models and picture are with the program in the same folder. I can't seem to understand why this error is coming?

##### Steps to reproduce
Cmake command to build Opencv 3.1.0.

`cmake -DCMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=~/opt/opencv_contrib/modules -D BUILD_EXAMPLES=ON -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 -D WITH_OPENGL=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D WITH_CAFFE=ON ..`

**Comment by kevgeo** [comment]
Sorry I was suppose to post this in opencv_contrib part.

**Comment by alalek** [comment]
One issue is enough: https://github.com/opencv/opencv_contrib/issues/895
