### ISSUE TITLE
crash inside cvCreateCameraCapture() MSMF implementation because of null pointer

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#7841]
##### System information (version)
OpenCV 3.1, Windows 7 64 bits, cuda 8, Visual Studio 2010
HAVE_MSMF enabled in cvconfig.h

##### Detailed description
A null pointer dereference  can result in a crash in cvCreateCameraCapture() with MSMF when some error occurs.

##### Steps to reproduce
in cap_msmf.cpp, line 1989, there is a call to ActivateObject()
        hr = pActivate->ActivateObject(
            __uuidof(IMFMediaSource),
            (void**)&pSource
            );
The hr is not checked and pSource can be null, which will cause a crash in the next  call to videoDevice::enumerateCaptureFormats(IMFMediaSource*)

I can observe that on my machine because of a Basler GeniCam driver that makes the ActivateObject() fail.

**Comment by alalek** [comment]
Thanks for report!
Could you create a pull request with fix? This case is very specific so it is hard to reproduce it on our side.

**Comment by chacha21** [comment]
First time for me to create a pull request.
I did not yet understand everything I have done, but it should be ok
PR #7843
