### ISSUE TITLE
Feature request for force read 32 bit image as single channel

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7842]
- OpenCV => Latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

##### Steps to reproduce

Suppose I create 32 bit single channel EXR image in OpenCV like this

``````
cv::Mat img = cv::Mat(100,100,CV_32FC1,cv::Scalar(5.0f));
cv:imwrite("test.exr", img);
``````

and when I read it back with 

``````
cv::Mat img = cv::imread("test.exr", -1);

if (img.depth() == CV_8U) std::cout << "8" << std::endl;
if (img.depth() == CV_32F) std::cout << "32" << std::endl;

std::cout << img.channels() << std::endl;
``````
the output is `32 1` as expected. However, the problem is a bunch of EXR image editor like Fusion is not capable of saving single channel EXR images, so when I do some editing on the EXR image editor the EXR images got saved into 3 channels. The output will become `32 3` for the above code. Is there a way to force read 32 bit image as single channel? I know there is a way to force read 8 bit image as single channel by changing the second argument of imread to 0.

``````
cv::Mat img = cv::imread("test.png", 0);
``````

but when I do the same thing for 3 channel 32 bit EXR image it got converted to 1 channel but for some reason it got converted to 8 bit, and I had to do something like 

``````
cv::Mat img_temp = cv::imread("test.exr", -1);

const int h = img_temp.rows;
const int w = img_temp.cols;
const int num_chan = img_temp.channels();

cv::Mat img = cv::Mat(h, w, CV_32FC1, cv::Scalar(0.0f));

if (num_chan > 1){
      for (int i = 0; i < h; i++)
        for (int j = 0; j < w; j++){
          img.at<float>(i, j) = img_in.at<cv::Vec3f>(i, j).val[0];
        }
}
else{
      img = img_in.clone();
}
``````

all over the place in my code for now. Am I missing something or is this a feature that is not available yet?

**Comment by kinchungwong** [comment]
Use `cv::split` or `cv::mixchannels`

http://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#split

http://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#mixchannels

**Comment by jasjuang** [comment]
@kinchungwong that workaround still creates a lot of code bloat like the code snippet at the end of my post

**Comment by mshabunin** [comment]
@jasjuang , isn't [extractChannel](http://docs.opencv.org/master/d2/de8/group__core__array.html#gacc6158574aa1f0281878c955bcf35642) applicable here?
```.cpp
Mat img = imread("test.exr", IMREAD_UNCHANGED);
if (image.channels() > 1)
    extractChannel(image, image, 0);
```

**Comment by jasjuang** [comment]
@mshabunin thanks, that is an elegant workaround
