### ISSUE TITLE
(EXAMPLE_GPU) video_writer compile error.

### ISSUE THREAD

**Issue by KurozumiGH** [opencv/opencv#7846]
##### System information (version)

- OpenCV => Latest
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015 Update 3

##### Detailed description

(EXAMPLE_GPU) video_writer compile error.
Source: video_writer.cpp : Line42

##### Steps to reproduce

Check the BUILD_EXAMPLES on CMake, and build.

Error code:
```.cpp
42:    TickMeter tm;
```

Fixed code:
```.cpp
42:   cv::TickMeter tm;
```

**Comment by alalek** [comment]
My suggestion is to add:
```
using namespace cv;
```
before `main()` function.
