### ISSUE TITLE
MatchTemplate mask parameter missing in DLL export

### ISSUE THREAD

**Issue by Olly-** [opencv/opencv#7849]
##### System information (version)

- OpenCV => Latest
- Operating System / Platform => Ubuntu 16
- Compiler => gcc

Recently a mask parameter was added to MatchTemplate, but it does not seem to be added to the DLL exports. I fixed this by adding support for the parameter [here](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/imgproc/src/templmatch.cpp#L1120) and [here](https://github.com/opencv/opencv/blob/1c18b1d245a875565c9b9e49ccec901e9b516337/modules/imgproc/include/opencv2/imgproc/imgproc_c.h#L408), But I am not familar with OpenCV so I figured a issue would be better.

**Comment by alalek** [comment]
`cv*` is a deprecated legacy C-API and it is not supported anymore. Moreover proposed changes broke binary compatibility so they can't be accepted.

You should use actual OpenCV C++ interface instead.
