### ISSUE TITLE
VideoCapture fails with files

### ISSUE THREAD

**Issue by flamoedo** [opencv/opencv#7878]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform =>  Windows 10 / 64 bits
- Compiler => Visual Studio

##### Detailed description

VideoCapture don't works with files, only with camera.

Ex.
```
cap = cv2.VideoCapture('SampleVideo_720x480_2mb.flv')

if not cap.isOpened():
    print "error"
else:
    print "file open"
```

Returns a error in python, and in C# does nothing.

I already tried with many files of many types.

With camera, it works fine.

**Comment by alalek** [comment]
You should set PATH to `opencv_ffmpeg*.dll`

Usage questions should go to OpenCV User Q/A forum: http://answers.opencv.org
