### ISSUE TITLE
Compile error with OpenCV 3.1.0, GCC 5.4

### ISSUE THREAD

**Issue by gusdoe** [opencv/opencv#7886]
Hi,

While I was trying to compile the source code, I have confronted with following error. Can anyone hint me how to fix?
 Thank you very much!
_____________________________________________________________________________

[ 22%] Generating test_precomp.hpp
[ 22%] Generating precomp.hpp.gch/opencv_freetype_RELEASE.gch
[ 22%] Generating precomp.hpp
[ 22%] Generating test_precomp.hpp
[ 22%] Generating test_precomp.hpp.gch/opencv_test_fuzzy_RELEASE.gch
[ 22%] Generating precomp.hpp.gch/opencv_fuzzy_RELEASE.gch
[ 22%] Generating test_precomp.hpp.gch/opencv_test_imgcodecs_RELEASE.gch
/home/gusto/src/opencv/build/modules/freetype/precomp.hpp:61:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
modules/freetype/CMakeFiles/pch_Generate_opencv_freetype.dir/build.make:62: recipe for target 'modules/freetype/precomp.hpp.gch/opencv_freetype_RELEASE.gch' failed
make[2]: *** [modules/freetype/precomp.hpp.gch/opencv_freetype_RELEASE.gch] Error 1
CMakeFiles/Makefile2:6186: recipe for target 'modules/freetype/CMakeFiles/pch_Generate_opencv_freetype.dir/all' failed
make[1]: *** [modules/freetype/CMakeFiles/pch_Generate_opencv_freetype.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] Built target pch_Generate_opencv_test_fuzzy
[ 22%] Built target pch_Generate_opencv_fuzzy
[ 22%] Built target pch_Generate_opencv_test_imgcodecs
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by catree** [comment]
You can switch off the module freetype with cmake if you don't need the freetype module. Generate again and the build should be successful.

I also encounter the same issue. I have Ubuntu 16.04 with the following configuration:
`/usr/include/freetype2/ft2build.h`

**Comment by jasjuang** [comment]
same error happened to me

**Comment by zhenpingfeng** [comment]
same error happened to me, my ft2build.h is also at /usr/include/freetype2/ft2build.h

**Comment by icarofua** [comment]
same error happened to me, my ft2build.h is also at /usr/include/freetype2/ft2build.h. I am using Ubuntu 14.04.

**Comment by alalek** [comment]
Thanks for report!
Fix: https://github.com/opencv/opencv_contrib/pull/906
