### ISSUE TITLE
Link error with OpenCV 2.4.13.2 and FFmpeg 1.2.12

### ISSUE THREAD

**Issue by gdsotirov** [opencv/opencv#7891]
##### System information (version)

- OpenCV => 2.4.13.2
- Operating System / Platform => Slackware Linux 14.0
- Compiler => GCC 4.7.1

##### Detailed description

Recently released OpenCV 2.4.13.2 fails to build on Slackware Linux 14.0 with ffmpeg 1.2.12 installed. The errors are:

```
Linking CXX executable ../../bin/opencv_perf_core
cd /usr/src/tmp/opencv-2.4.13.2/modules/core && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_core.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -march=i486 -mtune=i686   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-array-bounds -fdiagnostics-show-option -pthread -march=i686 -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mfpmath=sse -ffunction-sections -O2 -DNDEBUG  -DNDEBUG       CMakeFiles/opencv_perf_core.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_convertTo.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_inRange.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_minmaxloc.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_arithm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_merge.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_dft.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_dot.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_split.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_mat.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_addWeighted.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_math.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_abs.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_bitwise.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_reduce.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_compare.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_norm.cpp.o CMakeFiles/opencv_perf_core.dir/perf/perf_stat.cpp.o  -o ../../bin/opencv_perf_core -rdynamic ../../lib/libopencv_core.so.2.4.13 ../../lib/libopencv_ts.a ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_core.so.2.4.13 ../../lib/libopencv_flann.so.2.4.13 ../../lib/libopencv_imgproc.so.2.4.13 ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_features2d.so.2.4.13 ../../lib/libopencv_calib3d.so.2.4.13 ../../lib/libopencv_video.so.2.4.13 -ldl -lm -lpthread -lrt ../../lib/libopencv_features2d.so.2.4.13 ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_flann.so.2.4.13 ../../lib/libopencv_imgproc.so.2.4.13 ../../lib/libopencv_core.so.2.4.13 -ldl -lm -lpthread -lrt -Wl,-rpath,/usr/src/tmp/opencv-2.4.13.2/lib
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_codec_get_id'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_seek_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_network_init'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avpicture_get_size'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_find_stream_info'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_mallocz'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `sws_scale'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_guess_format'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_read_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avio_close'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_guess_codec'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_freep'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_lockmgr_register'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_write_trailer'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_new_stream'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_rescale_q'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_encode_video2'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_close_input'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_align_dimensions2'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_close'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_alloc_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_write_header'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_find_encoder'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_flush_buffers'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_write_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_log_set_level'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_free'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_open2'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_free_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `sws_getContext'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_dict_set'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_decode_video2'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_free_context'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_register_all'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avpicture_fill'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `sws_freeContext'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avio_open'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `sws_getCachedContext'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_init_packet'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_open_input'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_dict_free'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_find_decoder'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_malloc'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_sub_q'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_free_packet'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_alloc_context'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_perf_core] Error 1
make[2]: Leaving directory `/usr/src/tmp/opencv-2.4.13.2'
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
make[1]: Leaving directory `/usr/src/tmp/opencv-2.4.13.2'
make: *** [all] Error 2
```

##### Other information

Previous release 2.4.13 builds just fine.

**Comment by alalek** [comment]
1) Try to build from scratch (clean build directory).
2) Attach CMakeCache.txt and CMakeVars.txt files (and CMake stdout).
3) Add command-line parameters for linking of `opencv_highgui.so` too.

**Comment by gdsotirov** [comment]
Hello,

Yes, I always build from scratch as I'm building packages for Slackware, so this is definitely not the issue. Here attached are [CMakeCache.txt](https://github.com/opencv/opencv/files/659581/CMakeCache.txt), [CMakeVars.txt](https://github.com/opencv/opencv/files/659582/CMakeVars.txt) and [CMake output](https://github.com/opencv/opencv/files/659583/CMake.output.txt). I just noticed that there is a waring "WARNING: Can't build ffmpeg test code", but I'm not sure whether this is a problem or now. The command line for `opencv_highgui.so` is:

`Linking CXX shared library ../../lib/libopencv_highgui.so
cd /usr/src/tmp/opencv-2.4.13.2/modules/highgui && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_highgui.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC -O2 -march=i486 -mtune=i686   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-array-bounds -fdiagnostics-show-option -pthread -march=i686 -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mfpmath=sse -ffunction-sections -Wno-deprecated-declarations -Wno-clobbered -O2 -DNDEBUG  -DNDEBUG   -shared -Wl,-soname,libopencv_highgui.so.2.4 -o ../../lib/libopencv_highgui.so.2.4.13 CMakeFiles/opencv_highgui.dir/src/cap.cpp.o CMakeFiles/opencv_highgui.dir/src/cap_images.cpp.o CMakeFiles/opencv_highgui.dir/src/loadsave.cpp.o CMakeFiles/opencv_highgui.dir/src/utils.cpp.o CMakeFiles/opencv_highgui.dir/src/window.cpp.o CMakeFiles/opencv_highgui.dir/src/window_QT.cpp.o CMakeFiles/opencv_highgui.dir/src/moc_window_QT.cxx.o CMakeFiles/opencv_highgui.dir/qrc_window_QT.cxx.o CMakeFiles/opencv_highgui.dir/src/cap_xine.cpp.o CMakeFiles/opencv_highgui.dir/src/cap_dc1394_v2.cpp.o CMakeFiles/opencv_highgui.dir/src/cap_gstreamer.cpp.o CMakeFiles/opencv_highgui.dir/src/cap_libv4l.cpp.o CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_imageio.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_tiff.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_jpeg2000.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_base.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_pxm.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_exr.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_png.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_bmp.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_sunras.cpp.o CMakeFiles/opencv_highgui.dir/src/grfmt_jpeg.cpp.o CMakeFiles/opencv_highgui.dir/src/bitstrm.cpp.o ../../lib/libopencv_core.so.2.4.13 ../../lib/libopencv_imgproc.so.2.4.13 -ldl -lm -lpthread -lrt -lz -ljpeg -lpng -lz -ltiff -ljasper -ljpeg -lImath -lIlmImf -lIex -lHalf -lIlmThread -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0 -lgstvideo-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0 -lgstapp-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0 -lgstriff-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0 -lgstpbutils-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0 -ldc1394 -lxine -lv4l1 -lv4l2 /usr/lib/qt/lib/libQtGui.so /usr/lib/qt/lib/libQtTest.so /usr/lib/qt/lib/libQtCore.so ../../lib/libopencv_core.so.2.4.13 -ldl -lm -lpthread -lz -lpng -ltiff -ljasper -lImath -lIlmImf -lIex -lHalf -lIlmThread -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0 -lgstvideo-0.10 -lgstapp-0.10 -lgstriff-0.10 -lgstpbutils-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0 -lgstvideo-0.10 -lgstapp-0.10 -lgstriff-0.10 -lgstpbutils-0.10 -lrt -ldc1394 -lxine -lv4l1 -lv4l2 /usr/lib/qt/lib/libQtGui.so /usr/lib/qt/lib/libQtTest.so /usr/lib/qt/lib/libQtCore.so -Wl,-rpath,/usr/src/tmp/opencv-2.4.13.2/lib:/usr/lib/qt/lib: 
cd /usr/src/tmp/opencv-2.4.13.2/modules/highgui && /usr/bin/cmake -E cmake_symlink_library ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_highgui.so.2.4 ../../lib/libopencv_highgui.so`

Let me know if other information is necessary.

**Comment by alalek** [comment]
Thank you for update!

Could you dump CMake stdout (compiler log) with enabled [this line](https://github.com/opencv/opencv/blob/d7504ecaed716172806d932f91b65e2ef9bc9990/cmake/OpenCVFindLibsVideo.cmake#L214)?

**Comment by alalek** [comment]
BTW, I made some checks on my system (Fedora 24).

ffmpeg n1.2.12 is built via this command:
```
$ ./configure --prefix=`pwd`/install --enable-avresample --enable-pic --disable-asm --disable-debug --disable-ffmpeg --disable-ffserver && make install -j5
```

OpenCV configuration process passes "ffmpeg_test" check without "warning".
Also opencv_perf_core is able to complete build successfully:
```
$ PKG_CONFIG_PATH=<ffmpeg path>/install/lib/pkgconfig/ cmake ../opencv24
...
-- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
--   Found libavcodec, version 54.92.100
--   Found libavformat, version 54.63.104
--   Found libavutil, version 52.18.100
--   Found libswscale, version 2.2.100
-- Checking for module 'libavresample'
--   Found libavresample, version 1.1.0
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2.0") 
-- Found PythonLibs: /lib64/libpython2.7.so (found suitable exact version "2.7.12") 
...
-- General configuration for OpenCV 2.4.13.2 =====================================
--   Version control:               2.4.13.2
-- 
--   Platform:
--     Host:                        Linux 4.7.9-200.fc24.x86_64 x86_64
--     CMake:                       3.5.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/gmake
--     Configuration:               Release
...
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 54.92.100)
--       avformat:                  YES (ver 54.63.104)
--       avutil:                    YES (ver 52.18.100)
--       swscale:                   YES (ver 2.2.100)
--       avresample:                YES (ver 1.1.0)
...
$ make -j5 opencv_perf_core
...
[100%] Linking CXX executable ../../bin/opencv_perf_core
[100%] Built target opencv_perf_core
```

**Comment by gdsotirov** [comment]
> Could you dump CMake stdout (compiler log) with enabled this line?

This is the log with the line enabled - [CMake.output2.txt](https://github.com/opencv/opencv/files/661824/CMake.output2.txt). What do you think @alalek?

**Comment by alalek** [comment]
```
  In file included from /usr/include/libavutil/avutil.h:238:0,
                   from /usr/include/libavutil/samplefmt.h:24,
                   from /usr/include/libavcodec/avcodec.h:30,
                   from /usr/include/libavformat/avformat.h:203,
                   from /usr/src/tmp/opencv-2.4.13.2/cmake/checks/ffmpeg_test.cpp:4:

  /usr/include/libavutil/common.h: In function 'int32_t av_clipl_int32_c(int64_t)':

  /usr/include/libavutil/common.h:175:47: error: 'UINT64_C' was not declared in this scope
```

Could you try to update CMake command:
`CXXFLAGS=-D__STDC_CONSTANT_MACROS cmake ...`
or
`cmake -DCMAKE_CXX_FLAGS=-D__STDC_CONSTANT_MACROS ...`

And probably do the same trick with `__STDC_LIMIT_MACROS`.


P.S. There is [StackOverflow answer](http://stackoverflow.com/a/986584) about these defines.

**Comment by gdsotirov** [comment]
Yes, I noted this error in the log, but I tried [searching it directly](https://www.google.bg/search?q="common.h%3A+error%3A+'UINT64_C'+was+not+declared+in+this+scope"#q="common.h:175:47:+error:+'UINT64_C'+was+not+declared+in+this+scope") (without much success). Anyway, as I understand these macros are workaround, which works for me on Slackware (I confirm). However, do you know why their explicit definition isn't required on Fedora? I could just add `-D__STDC_CONSTANT_MACROS` in compiler flags for building the package and it would be OK (i.e. no warning about the FFmpeg test program and OpenCV 2.4.13.2 builds just fine), but I wonder whether there is a different solution to this problem. I haven't had any problem building other applications against FFmpeg 1.2.12 on Slackware 14.0 so far.

**Comment by gdsotirov** [comment]
No need for this one to remain open after #8002, so close.

**Comment by yzhang610** [comment]
Do you solve the top problem? How do you solve it? Now I happen the same problem with you! 
OpenCV 2.4.13
FFmpeg 3.3.1

**Comment by gdsotirov** [comment]
Yes, and the solution is described and confirmed in the comments above (I used `-D__STDC_CONSTANT_MACROS` as suggested by @alalek).
