### ISSUE TITLE
I cannot config contributing extra module with Cmake-gui in window10

### ISSUE THREAD

**Issue by top1st** [opencv/opencv#7895]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

![screenshot 2016-12-19 09 48 35](https://cloud.githubusercontent.com/assets/23559697/21298855/b852c5a6-c5d0-11e6-9661-6f45da437d15.png)

I want to build opencv with extra modules https://github.com/Itseez/opencv_contrib on windows 10
for VS2015
but i cannot config with cmake-gui.
[Uploading CMakeError.txt…]()

**Comment by alalek** [comment]
CMake version?

P.S. Screenshots should be avoided (and replaced to direct text messages) during issues reporting, because they are useless for searching of similar issues.

**Comment by alalek** [comment]
Reproduced with `-DINSTALL_TESTS=ON` option. CMake error message: "install DIRECTORY does not allow "COMPONENT" after PATTERN or REGEX".
