### ISSUE TITLE
Website shows 2.4 as latest version

### ISSUE THREAD

**Issue by beojan** [opencv/opencv#7905]
Because the presented download is simply the latest package added, the home page currently shows 2.4.13 as the latest download. A new user is likely to want 3.1 instead.
![image](https://cloud.githubusercontent.com/assets/3727925/21345824/a48bcf3a-c699-11e6-886d-a6e8c5912f9d.png)

**Comment by StevenPuttemans** [comment]
It is probably because it is auto grabbed from a list that is sorted by date of release, as seen [here](http://opencv.org/downloads.html).

**Comment by mshabunin** [comment]
Updated site shows several latest releases on top of the list (http://opencv.org/releases.html) with a big `*`.
![image](https://cloud.githubusercontent.com/assets/3304494/25616037/318bada8-2f43-11e7-8d5e-7bdc347319b0.png)
