### ISSUE TITLE
Opencv-Gimp Lightness

### ISSUE THREAD

**Issue by jcmorhum** [opencv/opencv#7906]
##### System information (version)

- OpenCV => 2.4.13
- Operating System / Platform =>  Windows 64 Bit
- Compiler => Eclipse Neon

##### Detailed description

How to reduce lightness in java with Opencv?
These images show how to do it in Gimp but I need it with the Opencv library

Original:
![sin luminosidad](https://cloud.githubusercontent.com/assets/22645215/21352020/e7d808e6-c6bf-11e6-9a18-202b677cf487.png)

With Lightness:
![con luminosidad](https://cloud.githubusercontent.com/assets/22645215/21352038/ff8fa624-c6bf-11e6-99fd-e42076d9d439.png)

Help me please!

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
