### ISSUE TITLE
Feature request for imread to force read as 8 bit RGBA

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7908]
##### System information (version)
- OpenCV => latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 5.4

##### Detailed description

I am receiving a 16 bit RGBA tiff image from a 3rd party to process. Is there any possible way to read them as 8 bit RGBA? 

``````
cv::Mat test = cv::imread("test.png"); // results in 8 bit RGB
cv::Mat test = cv::imread("test.png", -1); // results in 16 bit RGBA 
cv::Mat test = cv::imread("test.png", 0); // results in 8 bit gray

cv::Mat test = cv::imread("test.png", X); // can we add another flag to force it to 8 bit RGBA?
``````

Now I have to add something like this all over the place in my code

``````
cv::Mat test;
cv::Mat temp = cv::imread("test.png", -1);
if(temp.depth()==CV_16U) {
  test=temp.clone();
  test=test/256;
  test.convertTo(test, CV_8U);
}
if(temp.depth()==CV_8U) test=temp.clone();
``````

**Comment by alalek** [comment]
Creation of "god" functions should be avoided.
There is enough existed well-optimized OpenCV functionality.
```
cv::Mat img = cv::imread("test.png", -1);
if(img.depth()==CV_16U)
    img.convertTo(img, CV_8U, 1.0/256.0);
```

**Comment by jasjuang** [comment]
Thanks, this is acceptable.

**Comment by graph** [comment]
How do you know if the loaded file is RGBA or BGRA?
