### ISSUE TITLE
Floating point inaccuracy 

### ISSUE THREAD

**Issue by crep4ever** [opencv/opencv#7911]
##### System information (version)
Configuration 1:

- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.10 64 Bit
- Compiler => gcc 6.2

Configuration 2:
- OpenCV => 2.3
- Operating System / Platform => openSUSE 12.1 (x86_64)
- Compiler => gcc 4.6.2

##### Detailed description

It seems there is a problem of accuracy when performing basic operations on float (CV_32FC1) matrices. I observe a 1e-03 difference between the following operations :

```.cpp
cv::Mat dst1 = a * (src - b);
```

```.cpp
cv::Mat tmp = (src - b);
cv::Mat dst2 = a * tmp;
```

where I would expect a 1e-06 difference at most.
It does not look like a compiler optimisation (same results with different compilers and optimisation flags).

Note that the second method gives me better results than the first one.
Am I missing some 'good practices' when dealing with `float` matrices ?

##### Steps to reproduce

```.cpp

#include <opencv2/opencv.hpp>

void printRange(const cv::Mat p_src)
{
  double min = 0, max = 0;
  cv::minMaxLoc(p_src, &min, &max);
  std::cout << "Range: " <<  min << " ; " << max << std::endl;
}

int main(void)
{
  // Load src data (rows: 78 ; cols: 1088; type: CV_32FC1).
  // Values are in range 149.891 ; 166.196
  cv::Mat src;

  cv::FileStorage fs;
  if (!fs.open("x_float.xml", cv::FileStorage::READ))
    return -1;

  fs["matrix"] >> src;
  fs.release();

  //src.convertTo(src, CV_64FC1);

  printRange(src);

  src = src(cv::Rect(0, 0, 1000, 78));

  const int cols = src.cols; // 1088
  const float xmin = 149.212;
  const float xmax = 166.207;

  // Method 1: single line computation
  const cv::Mat res1 = (src - xmin) * ((cols - 1) / (xmax - xmin));

  // Method 2: temporary variables
  const float tmp1 = ((cols - 1) / (xmax - xmin)); // 63.96
  const cv::Mat tmp2 = (src - xmin);
  const cv::Mat res2 = tmp1 * tmp2;

  // NOK CV_32FC1 Range: -0.000244141 ; 0.000793457 
  // OK  CV_64FC1 Range: 0 ; 0
  printRange(res1 - res2); 

  return 0;
}
```

>    g++ mulfloat.cc -lopencv_core && ./a.out

Source code and data:

[opencv.zip](https://github.com/opencv/opencv/files/666218/opencv.zip)

**Comment by alalek** [comment]
> problem of accuracy when performing basic operations on float

In general it should be expected: it depends on different version of compilers, on different optimization flags, and on used platforms x86/ARM/etc.

You can try [`convertTo`](http://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#adf88c60c5b4980e05bb556080916978b) with `alpha` and `beta` parameters. Also there is [`normalize()`](http://docs.opencv.org/master/d2/de8/group__core__array.html#ga87eef7ee3970f86906d69a92cbf064bd) function.

**Comment by crep4ever** [comment]
> You can try convertTo with alpha and beta parameters.

Thank you for the tip (much faster and cleaner code).
However, this solution gives identical results to `method 1` where I would prefer results of `method 2`.

>  it should be expected

Well, I could expect 1e-06 differences but given the range of input values "nothing unusually high / low / close-to-zero", a 1e-04 seems very odd.

> different version of compilers, different optimization flags

it does not look like compiler "noise" (reproduced with gcc 4.6 & 6.2 with/without -O3 optimization)

**Comment by crep4ever** [comment]
Updated example (same data):

```.cpp
#include <opencv2/opencv.hpp>

double RMS(const cv::Mat & p_src1, const cv::Mat & p_src2)
{
  cv::Mat src1, src2;
  p_src1.convertTo(src1, CV_64FC1);
  p_src2.convertTo(src2, CV_64FC1);

  const double nbElements = src1.total();
  return cv::norm(src1, src2, cv::NORM_L2) / std::sqrt(nbElements);
}

int main(void)
{
  // Load src data (rows: 78 ; cols: 1088; type: CV_32FC1).
  // Values are in range 149.891 ; 166.196
  cv::Mat src;

  cv::FileStorage fs;
  if (!fs.open("x_float.xml", cv::FileStorage::READ))
    return -1;

  fs["matrix"] >> src;
  fs.release();

  const int cols = src.cols; // 1088
  const float xmin = 149.212;
  const float xmax = 166.207;

  const float a = (cols - 1) / (xmax - xmin);
  const float b = - xmin;

  // Reference: double operation
  src.convertTo(src, CV_64FC1);
  const cv::Mat ref = a * (src + b);

  src.convertTo(src, CV_32FC1);
  // Method 1: single line computation
  const cv::Mat res1 = a * (src + b);

  // Method 2: temporary variable
  const cv::Mat tmp = src + b; // 63.96
  const cv::Mat res2 = a * tmp;

  // Method 3: convertTo
  cv::Mat res3;
  src.convertTo(res3, CV_32FC1, a, a * b);

  // Method 4: manual loop
  cv::Mat res4(src.size(), src.type());
  for (int r = 0; r < src.rows; ++r)
    for (int c = 0; c < src.cols; ++c)
      {
        res4.at<float>(r, c) = a * (src.at<float>(r, c) + b);
      }

  std::cout << "Method 1: " << RMS(ref, res1) << std::endl;
  std::cout << "Method 2: " << RMS(ref, res2) << std::endl;
  std::cout << "Method 3: " << RMS(ref, res3) << std::endl;
  std::cout << "Method 4: " << RMS(ref, res4) << std::endl;

  return 0;
}
```

```
 Method 1: 0.000408273 // NOK
 Method 2: 1.5858e-05  // OK
 Method 3: 0.000408273 // NOK
 Method 4: 1.5858e-05  // OK
```

**Comment by alalek** [comment]
Assume that EPS is an error for single operation. But for complex expressions this error may be amplified significantly:
- Expected precission error for `a - b` expression is `EPS * |gold(a-b)|` <= `EPS * (|a| + |b|)` <= `EPS * 2N` (N is max value of a, b).
- Expected error of expression of `(a - b) * c` is <= `EPS * (|a-b| * |c|)` <= `EPS * 2N * N`.
So if your numbers are <= 1000, then expected error should be `EPS * 2000 * 1000`.

> could expect 1e-06

So this assumption doesn't work.

**Comment by crep4ever** [comment]
> could expect 1e-06

Ok, this was just some 'random' assumption, I agree.

What concerns me is that the manual loop on elements does not return the same results as the matrix operation ie:

```.cpp
  cv::Mat res4(src.size(), src.type());
  for (int r = 0; r < src.rows; ++r)
    for (int c = 0; c < src.cols; ++c)
      {
        res4.at<float>(r, c) = a * (src.at<float>(r, c) + b);
      }
```
not equal to:

```.cpp
cv::Mat res1 = a * (src + b);
```

And both operations should have the same 'error'.

Furthermore, the `convertTo()` operation indicates `saturate_cast<float>(a * src(x,y) + b)` (similar to method 4) and only method 2 (temp variable) returns identical results.
