### ISSUE TITLE
cv::minMaxLoc with NaN / inf matrix returns wrong min position

### ISSUE THREAD

**Issue by crep4ever** [opencv/opencv#7912]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.10 64 Bit
- Compiler => gcc 6.2

##### Detailed description

The minimum location returned by `cv::minMaxLoc()` is invalid when mixing NaN / inf values.

##### Steps to reproduce

```.cpp

#include <opencv2/opencv.hpp>
#include <iomanip>

int main(void)
{
  cv::Mat m(1, 3, CV_64FC1);
  m.at<double>(0, 0) = std::numeric_limits<double>::quiet_NaN();
  m.at<double>(0, 1) = std::numeric_limits<double>::signaling_NaN();
  m.at<double>(0, 2) = std::numeric_limits<double>::infinity();
  
  double min = 0, max = 0;
  cv::Point minLoc(-1, -1), maxLoc(-1, -1);
  cv::minMaxLoc(m, &min, &max, &minLoc, &maxLoc);
  
  std::cout << "min: " << std::setw(3) << min << " @ " << minLoc << " is finite? " << std::isfinite(min) << std::endl;
  std::cout << "max: " << std::setw(3) << max << " @ " << maxLoc << " is finite? " << std::isfinite(max) << std::endl;
  
  return 0;
}

```
output:
```
min: inf @ [0, 0] is finite ? 0
max: inf @ [2, 0] is finite ? 0
```

expected output:
```
min: inf @ [2, 0] is finite ? 0
max: inf @ [2, 0] is finite ? 0
```

**Comment by alalek** [comment]
> expected output

Why? There is a big trouble with logic definition with NaN values:

> A comparison with a NaN always returns an unordered result even when comparing with itself.

https://en.wikipedia.org/wiki/NaN

You can't declare that your `NaN` value is less or bigger than `inf` value (or something else including other `NaN`).


**General note about OpenCV implementations**:
Using of NaN values will provide undefined behavior and should be avoided if there is no special NaN-related note in function/algorithm documentation.

Take a look on separate processing via [`patchNaNs()`](http://docs.opencv.org/master/d2/de8/group__core__array.html#ga62286befb7cde3568ff8c7d14d5079da) if you expect NaN values in some part of your algorithm.

**Comment by crep4ever** [comment]
Well, the main concern is that the only 'inf' value is at position [2, 0] so it seems strange to return `inf @ [0, 0]`. I thought that NaN values were kind of 'ignored' by the `minMaxLoc` method as I have consistent results and positions when mixing NaN and finite values.

Thank you for the `patchNaNs()` tip.

**Comment by zoombinis** [comment]
@alalek `cv::patchNaNs` removes nans, but inf and -inf are still present. Is there anyway to efficiently patch those as well? Functions like `cv::calcHist` don't work with NaN or Inf present.
