### ISSUE TITLE
Recent commit causes CMake error

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7914]
##### System information (version)
- OpenCV => latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 5.4

##### Steps to reproduce

``````
mkdir build
cd build
cmake ..
``````

The error message is 

CMake Error at /home/jasjuang/opencv/cmake/OpenCVUtils.cmake:1102 (file):
   file called with unknown argument "COMPONENT".
 Call Stack (most recent call first):
   /home/jasjuang/opencv_contrib/modules/text/CMakeLists.txt:22
 (ocv_add_testdata)

**Comment by alalek** [comment]
Update repositories "in sync": https://github.com/opencv/opencv_contrib/pull/908

**Comment by jasjuang** [comment]
my bad, thanks!
