### ISSUE TITLE
Java memory allocation and garbage collector issue

### ISSUE THREAD

**Issue by kevto** [opencv/opencv#7919]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit:

##### Detailed description

Memory allocation. I'm using OpenCV's JNI wrapper as port for to use OpenCV in Java. Works outstanding but memory allocation is quite an issue in a 32bit JVM.

I jumped into the wrapper code and came to the conclusion that the garbage collectior of the JVM is supposed to clean up the resources allocated by the C++ code as well. Although that seems very smart (I think it is), one thing has been looked very thoroughly. 

The JVM can not see any resources allocated by the native library which seems more than normal but for example, if you keep constantly loading many many images (thinking of 80 images which are each more than 1 MB in raw data), then you might run into out of memory exceptions thrown by the native library because even when I try to request the garbage collector to release his non-valuable resources, it simply ignores my request because the garbage collector doesn't see the resources I allocated through the native library.

##### Steps to reproduce

You need a tool shipped with JRE which is JVisual VM. 
* Create a simple Java application with a thread pool of at least 8 threads;
* Submit runnables whom each loads an image into a Mat object through the OpenCV Java port;
- Each runnable explicitly calls the release method of the Mat object. 
* Monitor the heap size of your Java application;

You will only see a little rise in the heap size you;re monitoring. Far far less than your allocated images. Then if you monitor your system's resources, you'd shortly notice a uprising in your memory and most likely run into an out of memory exception (one not thrown by the JVM)

This only occurs when using a 32bit JRE due to the memory limitations I believe.

##### Resolution
Allow the delete method to be explicitly called in Java or simply move to a 64bit JRE (I can't do that because of numerous reasons).

**Comment by alalek** [comment]
>  JVM can not see any resources allocated by the native library

There is no general way to fix this in OpenCV.

You need to call "System.gc()" periodically - it helps on some JVM implementations.


See also: #4019

**Comment by kevto** [comment]
> You need to call "System.gc()" periodically - it helps on some JVM implementations.
That's not a trustworthy method as I stated in my post.

#4019 came with a few nice work arounds. Thanks!

**Comment by suryababy** [comment]
Enable GC logs in your application. In fact, it’s advisable to keep your GC log enabled all the time in all your production servers, as it helps you to troubleshoot and optimize application performance. Enabling GC logs adds negligible (if at all observable) overhead. Now upload your GC log to the Garbage Collection log analyzer tool like [GCeasy](https://gceasy.io), HP JMeter,…. These tools generate rich Garbage collection analysis report.
