### ISSUE TITLE
Error C4996: 'fopen': This function or variable may be unsafe. in VS2015.

### ISSUE THREAD

**Issue by KurozumiGH** [opencv/opencv#7923]
##### System information (version)

- OpenCV => 3.2.0 rc (Latest version)
- Operating System / Platform => Windows10 64bit
- Compiler => Visual Studio 2015 Update3

##### Detailed description
Source: %OPENCV_PATH%\include\opencv2\flann\logger.h 67
Error C4996 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

##### Steps to reproduce

Build below code with opencv_flann.
```.cpp
#include <Windows.h>
#include <opencv2/opencv.hpp>

void main(int argc, char* argv[])
{
}

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR lpCmd, int nCmd)
{
    main(0,NULL);
}
```

###### logger.h : Original code.
```.cpp
66: stream = fopen(name,"w");
67: if (stream == NULL) {
68:     stream = stdout;
69: }
```

###### logger.h : Fixed code.
```.cpp
66: #if _MSC_VER >= 1500
67:     errno_t error;
68:     error = fopen_s(&stream, name, "w");
69:     if (error != 0) {
70:         stream = stdout;
71:     }
72: #else
73:     stream = fopen(name,"w");
74:     if (stream == NULL) {
75:         stream = stdout;
76:     }
77: #endif
```

**Comment by aligoglos** [comment]
that's fixed thanks.

**Comment by AenBleidd** [comment]
Hello. Will this ever be fixed. @aligoglos said that it's fixed but I see no changes. Thanks

**Comment by oviradoi** [comment]
It looks like this was addressed with commit https://github.com/opencv/opencv/commit/22d2207d411212f198b19d7d0292598204f55201

**Comment by hwlim84** [comment]
just exactly replace the codes for codes. it worked!!

**Comment by cancanxinxin** [comment]
It has worked, thanks!
