### ISSUE TITLE
Opencv 3.2: compile error on Raspian, PI3

### ISSUE THREAD

**Issue by Roboball** [opencv/opencv#7928]
I tried these build options :
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=/home/pi/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..

and I got this compile error on Raspian, PI3:

[ 86%] Building CXX object samples/cpp/CMakeFiles/tutorial_mat_the_basic_image_container.dir/tutorial_code/core/mat_the_basic_image_container/mat_the_basic_image_container.cpp.o
c++: internal compiler error: Getötet (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
modules/python2/CMakeFiles/opencv_python2.dir/build.make:322: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o' failed
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 4
CMakeFiles/Makefile2:20773: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: *** Warte auf noch nicht beendete Prozesse...
[ 86%] Linking CXX executable ../../bin/cpp-tutorial-AKAZE_match
[ 86%] Built target tutorial_AKAZE_match
[ 86%] Linking CXX executable ../../bin/cpp-tutorial-mat_the_basic_image_container
[ 86%] Built target tutorial_mat_the_basic_image_container

**Comment by alalek** [comment]
> c++: internal compiler error

You need to workaround this itself.
Try to limit memory usage and disable the parallel "make" build (remove `-j4` or similar option).
Next, try to use cross-compilation from normal workstation (but you need devices file system snapshot in some cases).

**Comment by he44** [comment]
I got the same error. Did you find a solution? Any suggestion would be appreciated
