### ISSUE TITLE
BUILD_PROTOBUF off??

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#7933]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => :Ubuntu 16.04.1:
- Compiler => :gcc/g++ 5.4.0:

##### Detailed description

Failed to build OpenCV if disable BUILD_PROTOBUF ...
In fact, Ubuntu 16.04.1 installed protobuf 2.6.1-1.3 by default.
I installed the newest protobuf 3.1.0 manually to /usr/local/lib afterwards.

That's why I think "I do NOT need to enable BUILD_PROTOBUF while configuring OpenCV" .

##### Steps to reproduce
However, I met the following error message if I do so:

> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.h:30:0,
>                  from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:5:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.h: In member function ‘const string& tensorflow::TensorShapeProto_Dim::name() const’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.h:299:80: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::Get(const string*) const’
>    return name_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
>                                                                                 ^
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:5:0:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.h: In member function ‘const string& tensorflow::TensorShapeProto_Dim::name() const’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.h:299:80: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::Get(const string*) const’
>    return name_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
>                                                                                 ^
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.h:23:0,
>                  from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:5:
> /usr/local/include/google/protobuf/arenastring.h:66:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::Get() const
>    inline const ::std::string& Get() const { return *ptr_; }
>                                ^
> /usr/local/include/google/protobuf/arenastring.h:66:31: note:   candidate expects 0 arguments, 1 provided
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.h:23:0,
>                  from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:5:
> /usr/local/include/google/protobuf/arenastring.h:66:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::Get() const
>    inline const ::std::string& Get() const { return *ptr_; }
>                                ^
> /usr/local/include/google/protobuf/arenastring.h:66:31: note:   candidate expects 0 arguments, 1 provided
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:5:0:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.h: In member function ‘const string& tensorflow::TensorProto::tensor_content() const’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.h:404:90: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::Get(const string*) const’
>    return tensor_content_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
>                                                                                           ^
> In file included from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.h:23:0,
>                  from ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:5:
> /usr/local/include/google/protobuf/arenastring.h:66:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::Get() const
>    inline const ::std::string& Get() const { return *ptr_; }
>                                ^
> /usr/local/include/google/protobuf/arenastring.h:66:31: note:   candidate expects 0 arguments, 1 provided
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc: In function ‘void tensorflow::protobuf_AssignDesc_tensor_5fshape_2eproto()’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:47:5: error: ‘NewGeneratedMessageReflection’ is not a member of ‘google::protobuf::internal::GeneratedMessageReflection’
>      ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
>      ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:62:5: error: ‘NewGeneratedMessageReflection’ is not a member of ‘google::protobuf::internal::GeneratedMessageReflection’
>      ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
>      ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc: In function ‘void tensorflow::{anonymous}::MergeFromFail(int)’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:146:3: error: ‘MergeFromFail’ is not a member of ‘google::protobuf::internal’
>    ::google::protobuf::internal::MergeFromFail(__FILE__, line);
>    ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:146:3: note: suggested alternatives:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:145:13: note:   ‘tensorflow::{anonymous}::MergeFromFail’
>  static void MergeFromFail(int line) {
>              ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:145:13: note:   ‘tensorflow::{anonymous}::MergeFromFail’
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc: In function ‘void tensorflow::protobuf_AssignDesc_tensor_2eproto()’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:55:5: error: ‘NewGeneratedMessageReflection’ is not a member of ‘google::protobuf::internal::GeneratedMessageReflection’
>      ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
>      ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc: In function ‘void tensorflow::{anonymous}::MergeFromFail(int)’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:143:3: error: ‘MergeFromFail’ is not a member of ‘google::protobuf::internal’
>    ::google::protobuf::internal::MergeFromFail(__FILE__, line);
>    ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:143:3: note: suggested alternatives:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:142:13: note:   ‘tensorflow::{anonymous}::MergeFromFail’
>  static void MergeFromFail(int line) {
>              ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:142:13: note:   ‘tensorflow::{anonymous}::MergeFromFail’
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc: In member function ‘void tensorflow::TensorProto::UnsafeMergeFrom(const tensorflow::TensorProto&)’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1062:13: error: ‘class google::protobuf::RepeatedField<int>’ has no member named ‘UnsafeMergeFrom’
>    half_val_.UnsafeMergeFrom(from.half_val_);
>              ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1063:14: error: ‘class google::protobuf::RepeatedField<float>’ has no member named ‘UnsafeMergeFrom’
>    float_val_.UnsafeMergeFrom(from.float_val_);
>               ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1064:15: error: ‘class google::protobuf::RepeatedField<double>’ has no member named ‘UnsafeMergeFrom’
>    double_val_.UnsafeMergeFrom(from.double_val_);
>                ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1065:12: error: ‘class google::protobuf::RepeatedField<int>’ has no member named ‘UnsafeMergeFrom’
>    int_val_.UnsafeMergeFrom(from.int_val_);
>             ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1066:15: error: ‘class google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char> >’ has no member named ‘UnsafeMergeFrom’
>    string_val_.UnsafeMergeFrom(from.string_val_);
>                ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1067:17: error: ‘class google::protobuf::RepeatedField<float>’ has no member named ‘UnsafeMergeFrom’
>    scomplex_val_.UnsafeMergeFrom(from.scomplex_val_);
>                  ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1068:14: error: ‘class google::protobuf::RepeatedField<long int>’ has no member named ‘UnsafeMergeFrom’
>    int64_val_.UnsafeMergeFrom(from.int64_val_);
>               ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1069:13: error: ‘class google::protobuf::RepeatedField<bool>’ has no member named ‘UnsafeMergeFrom’
>    bool_val_.UnsafeMergeFrom(from.bool_val_);
>              ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:1070:17: error: ‘class google::protobuf::RepeatedField<double>’ has no member named ‘UnsafeMergeFrom’
>    dcomplex_val_.UnsafeMergeFrom(from.dcomplex_val_);
>                  ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor_shape.pb.cc:147:1: warning: ‘noreturn’ function does return
>  }
>  ^
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc: In function ‘void tensorflow::{anonymous}::MergeFromFail(int)’:
> ....../opencv_contrib/modules/dnn/misc/tensorflow/tensor.pb.cc:144:1: warning: ‘noreturn’ function does return
>  }
>  ^
> modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:78: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/misc/tensorflow/tensor_shape.pb.cc.o' failed
> make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/misc/tensorflow/tensor_shape.pb.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make -f modules/freetype/CMakeFiles/opencv_freetype.dir/build.make modules/freetype/CMakeFiles/opencv_freetype.dir/depend
> modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:102: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/misc/tensorflow/tensor.pb.cc.o' failed
> make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/misc/tensorflow/tensor.pb.cc.o] Error 1
> make[2]: Leaving directory '....../opencv/build'
> CMakeFiles/Makefile2:6496: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/all' failed
> make[1]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> 

Any suggestions?????

Cheers
Pei

**Comment by alalek** [comment]
CMake logs (stdout, CMakeCache.txt/CMakeVars.txt with PROTOBUF entries) are required.

**Comment by jiapei100** [comment]
@alalek 

1) Here is all contents related to PROTOBUF in CMakeVars.txt

```
......
BUILD_PROTOBUF=OFF
......

PROTOBUF_CPP_DOWNLOADED_HASH=bd5e3eed635a8d32e2b99658633815ef
PROTOBUF_INCLUDE_DIR=/usr/local/include
PROTOBUF_LIBRARY=/usr/local/lib/libprotobuf.so
PROTOBUF_LIBRARY_DEBUG=/usr/local/lib/libprotobuf.so
PROTOBUF_LITE_LIBRARY=/usr/local/lib/libprotobuf-lite.so
PROTOBUF_LITE_LIBRARY_DEBUG=/usr/local/lib/libprotobuf-lite.so
PROTOBUF_PROTOC_EXECUTABLE=/usr/local/bin/protoc
PROTOBUF_PROTOC_LIBRARY=/usr/local/lib/libprotoc.so
PROTOBUF_PROTOC_LIBRARY_DEBUG=/usr/local/lib/libprotoc.so
......

Protobuf_LIBS=/usr/local/lib/libprotobuf.so
......

libprotobuf_BINARY_DIR=....../opencv/build/modules/dnn/3rdparty/protobuf
libprotobuf_LIB_DEPENDS=
libprotobuf_SOURCE_DIR=....../opencv_contrib/modules/dnn/3rdparty/protobuf

```

There are some other occurrence of PROTOBUF, which all hints /usr/local/lib/


2) Here is all contents related to PROTOBUF in CMakeCache.txt

```
//Force to build libprotobuf from sources
BUILD_PROTOBUF:BOOL=OFF
......
/Path to a file.
PROTOBUF_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
PROTOBUF_LIBRARY:FILEPATH=/usr/local/lib/libprotobuf.so

//Path to a library.
PROTOBUF_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libprotobuf.so

//Path to a library.
PROTOBUF_LITE_LIBRARY:FILEPATH=/usr/local/lib/libprotobuf-lite.so

//Path to a library.
PROTOBUF_LITE_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libprotobuf-lite.so

//The Google Protocol Buffers Compiler
PROTOBUF_PROTOC_EXECUTABLE:FILEPATH=/usr/local/bin/protoc

//Path to a library.
PROTOBUF_PROTOC_LIBRARY:FILEPATH=/usr/local/lib/libprotoc.so

//Path to a library.
PROTOBUF_PROTOC_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libprotoc.so

......
//Path to a library.
Protobuf_LIBS:FILEPATH=/usr/local/lib/libprotobuf.so

......

//Value Computed by CMake
libprotobuf_BINARY_DIR:STATIC=....../opencv/build/modules/dnn/3rdparty/protobuf

//Dependencies for target
libprotobuf_LIB_DEPENDS:STATIC=

//Value Computed by CMake
libprotobuf_SOURCE_DIR:STATIC=....../opencv_contrib/modules/dnn/3rdparty/protobuf

......


```

It looks **opencv_contrib/modules/dnn** and **opencv_contrib/modules/cnn_3dobj** require to download protobuf **ALWAYS** ???


Cheers
Pei

**Comment by alalek** [comment]
I doesn't see detected protobuf version information from your log.

Could you run `/usr/local/bin/protoc --version`?

> require to download protobuf

There are conflicts with **mismatched** protobuf versions, because there are several files pre-generated by `protoc` for some exact version (currently v3.1).

`BUILD_PROTOBUF=OFF` is useless without `UPDATE_PROTO_FILES=ON` option.

**Comment by jiapei100** [comment]
@alalek Thank you ...

My manually installed protobuf is of version 3.1.0 as well...

> peijia@peijia:~/....../opencv$ /usr/local/bin/protoc --version
> libprotoc 3.1.0


What's more, I tried to set
BUILD_PROTOBF=OFF
UPDATE_PROTO_FILES=ON
at the same time, but OpenCV still fails to build, with the following ERROR message:

>  CMake Error at ....../opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:17 (PROTOBUF_GENERATE_CPP):
>    Unknown CMake command "PROTOBUF_GENERATE_CPP".
>  Call Stack (most recent call first):
>    ,,,,,,/opencv_contrib/modules/dnn/CMakeLists.txt:35 (include)
> 

Any ideas?
Should I build opencv and opencv_contrib in separate two times ?


Cheers
Pei

**Comment by alalek** [comment]
`PROTOBUF_GENERATE_CPP` is defined in CMake:
https://gitlab.kitware.com/cmake/cmake/blob/v3.7.1/Modules/FindProtobuf.cmake

What CMake version is used?
Try to build from scratch (remove opencv build directory).

**Comment by HWiese1980** [comment]
I'm using cmake 3.9 and I'm running into the same problem. Any news on this?

**Comment by stalkerg** [comment]
+1 I have the same problem in Gentoo. I have CMake 3.9.3 and protobuf 3.4.1

**Comment by ossun** [comment]
in CMAKE add  -D BUILD_PROTOBUF=OFF

**Comment by Kagami** [comment]
@ossun didn't help. Build still fails at:

```
/var/build/portage/media-libs/opencv-3.3.0-r1/work/opencv-3.3.0/modules/dnn/misc/tensorflow/function.pb.cc: In function 'void tensorflow::{anonymous}::MergeFromFail(int)':
/var/build/portage/media-libs/opencv-3.3.0-r1/work/opencv-3.3.0/modules/dnn/misc/tensorflow/function.pb.cc:223:1: warning: 'noreturn' function does return
 }
 ^
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:100: modules/dnn/CMakeFiles/opencv_dnn.dir/misc/tensorflow/function.pb.cc.o] Error 1
```

Also a lot of errors like that:

```
/var/build/portage/media-libs/opencv-3.3.0-r1/work/opencv-3.3.0/modules/dnn/misc/tensorflow/tensor.pb.h:19:2: error:
 #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
/var/build/portage/media-libs/opencv-3.3.0-r1/work/opencv-3.3.0/modules/dnn/misc/tensorflow/tensor_shape.pb.h:17:2: 
error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
```

Seems like something related to protobuf version.

protobuf 3.4.1
opencv 3.3.0

**Comment by ossun** [comment]
add -D BUILD_PROTOBUF=OFF -D BUILD_opencv_dnn=OFF

**Comment by alalek** [comment]
In case of using different protobuf version you should force `PROTOBUF_UPDATE_FILES=ON`.

**Comment by ossun** [comment]
try BUILD_opencv_dnn = OFF


2017-10-09 8:02 GMT-05:00 Alexander Alekhin <notifications@github.com>:

**Comment by ossun** [comment]
with protobuf off, it does not compile it.


2017-10-09 8:05 GMT-05:00 Albeiro buendia diago <albeirobu@gmail.com>:

**Comment by Kagami** [comment]
@ossun it works, thanks! In case if someone needs it, here is patch for latest gentoo opencv ebuild:

```patch
--- /usr/portage/media-libs/opencv/opencv-3.3.0-r1.ebuild       2017-09-19 16:55:28.000000000 +0300
+++ /usr/local/portage/media-libs/opencv/opencv-3.3.0-r1.ebuild 2017-10-09 16:32:52.126289831 +0300
@@ -281,6 +281,8 @@
        # ===================================================
                -DCMAKE_SKIP_RPATH=ON
                -DOPENCV_DOC_INSTALL_PATH=
+               -DBUILD_PROTOBUF=OFF
+               -DBUILD_opencv_dnn=OFF
        )
 
        # ===================================================
```

**Comment by ossun** [comment]
Great !, like working with cuda, I always use this:

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local
-D WITH_CUDA=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1
-D WITH_CUBLAS=1 -D BUILD_PROTOBUF=OFF -D BUILD_opencv_dnn=OFF
-D INSTALL_PYTHON_EXAMPLES=ON -D
PYTHON_INCLUDE_DIR=/usr/include/python3 -D
PYTHON3_EXECUTABLE=/usr/bin/python3
-D ENABLE_PRECOMPILED_HEADERS=OFF -D BUILD_PROTOBUF=OFF -D BUILD_opencv_dnn=OFF
-D BUILD_PERF_TESTS=OFF
-D OPENCV_EXTRA_MODULES_PATH=/home/ossun/opencv/opencv_contrib-master/modules
-D BUILD_opencv_legacy=OFF  /home/ossun/opencv/opencv-master -D
BUILD_EXAMPLES=ON ..


2017-10-09 8:43 GMT-05:00 Kagami Hiiragi <notifications@github.com>:

**Comment by bakape** [comment]
In case somebody on Gentoo finds this thread, disabling LTO for Protobuf builds fixed it for me.
