### ISSUE TITLE
Hough Line Transform (OpenCV3) Error in Documentation

### ISSUE THREAD

**Issue by megatran** [opencv/opencv#7934]
##### System information (version)
- OpenCV => 3.0.0-dev
- Operating System / Platform => Unix
- Compiler => Python 3.5.2

##### Detailed description
http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html?highlight=hough
The Documentation sample code of Hough Line Transform only detects one line instead of multiple lines in an image, which does not match the follow result picture.

```
import cv2
import numpy as np

img = cv2.imread('dave.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
for rho,theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imwrite('houghlines3.jpg',img)
```
As seen in the sample code above from the docs, the loop `for rho,theta in lines[0]` would only detect one line. In order to correctly detect multiple lines (result matches the result pic in the docs), there should be nested loops like this:

```
for i in range(len(lines)):
    for rho,theta in lines[i]:
       ....
```
##### Steps to reproduce
Follow the instruction (or just copy and paste the sample code) in http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html?highlight=hough

**Comment by alalek** [comment]
> 3.0.0-dev
> 3.0-beta

These versions are outdated and not supported anymore.
Modern code contains [this](https://github.com/opencv/opencv/blame/3.2.0/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.markdown#L81) code fixed in #3722
