### ISSUE TITLE
Opencv Python - Freetype error

### ISSUE THREAD

**Issue by soulslicer** [opencv/opencv#7949]
##### System information (version)
OpenCV 3.2.0 Branch

##### Detailed description
I compiled it successfully, however when I go to python and I type import cv2, it throws the following error:

> ImportError: /usr/local/lib/libopencv_freetype.so.3.2: undefined symbol: hb_shape

**Comment by alalek** [comment]
https://github.com/opencv/opencv_contrib/issues/919

**Comment by xxinine** [comment]
same error as yours, have you fixed it ? and how? thx.

**Comment by bharathkotari** [comment]
follow the link provided by @alalek  . that solution solved my issue on ubuntu
