### ISSUE TITLE
Opencv 2.4 android bilateral filter

### ISSUE THREAD

**Issue by bacteria323** [opencv/opencv#7953]
I am using the bilateral filter in android and when I run the code 

    rgba = inputFrame.rgba();
    Imgproc.bilateralFilter(rgba, rgba, 10, 50, 0);

I get the error:

`E/cv::error(): OpenCV Error: Assertion failed ((src.type() == CV_8UC1 || src.type() == CV_8UC3)       && src.type() == dst.type() && src.size() == dst.size() && src.data != dst.data) in void cv::bilateralFilter_8u(const cv::Mat&, cv::Mat&, int, double, double, int), file /Volumes/build-storage/build/2_4_pack-android/opencv/modules/imgproc/src/smooth.cpp, line 1925
01-01 19:57:00.363 23802-23945/com.example.mustardlab.opencvtesting E/org.opencv.imgproc: imgproc::bilateralFilter_11() caught cv::Exception: /Volumes/build-storage/build/2_4_pack-android/opencv/modules/imgproc/src/smooth.cpp:1925: error: (-215) (src.type() == CV_8UC1 || src.type() == CV_8UC3) && src.type() == dst.type() && src.size() == dst.size() && src.data != dst.data in function void cv::bilateralFilter_8u(const cv::Mat&, cv::Mat&, int, double, double, int)
01-01 19:57:00.363 23802-23945/com.example.mustardlab.opencvtesting E/AndroidRuntime: FATAL EXCEPTION: Thread-2565

Process: com.example.mustardlab.opencvtesting, PID: 23802
                                                                                      CvException [org.opencv.core.CvException: cv::Exception: /Volumes/build-storage/build/2_4_pack-android/opencv/modules/imgproc/src/smooth.cpp:1925: error: (-215) (src.type() == CV_8UC1 || src.type() == CV_8UC3) && src.type() == dst.type() && src.size() == dst.size() && src.data != dst.data in function void cv::bilateralFilter_8u(const cv::Mat&, cv::Mat&, int, double, double, int)
                                                                                      ]`

**Comment by alalek** [comment]
rgba is CV_8UC4.
You need [`cvtColor`](http://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga397ae87e1288a81d2363b61574eb8cab) with `COLOR_RGBA2RGB`.
