### ISSUE TITLE
Summation bug

### ISSUE THREAD

**Issue by Sahloul** [opencv/opencv#7955]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
Summation of matrix values is misleading and incorrect.

##### Steps to reproduce

```.cpp
#include <iostream>
#include <opencv/cv.hpp>

int main(int argc, char** argv)
{
	cv::Mat test(2, 1, CV_32FC1);
	test.at<double>(0) = 1e-100;
	test.at<double>(1) = 2e-100;
	std::cout << cv::sum(test)[0] << std::endl;
	std::cout << cv::sum(test).val[0] << std::endl;
	std::cout << test.at<double>(0) + test.at<double>(1) << std::endl;
	return 0;
}
```

##### Expected output
```
3e-100
3e-100
3e-100
```

##### Actual output
```
-2.09585e+22
-2.09585e+22
3e-100
```

**Comment by sturkmen72** [comment]
you should change 	`cv::Mat test(2, 1, CV_32FC1);` -> `cv::Mat test(2, 1, CV_64FC1);`
