### ISSUE TITLE
incorrect cvRectangle result for thin rectangle and CV_FILLED

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#7957]
- OpenCV => 3.2 64 bits in Release mode
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2010

##### Detailed description

A rectangle with 1px height is drawn incorrectly if CV_FILLED is used as thickness.
Even worse : the drawn image is not always the same between two runs, there must be some uninitialized data.

It is a regression because it works correctly in OpenCV 3.1.0

##### Steps to reproduce
I have tested with VS2010 64bits.
The bug only occurs with the Release (non-debug) version of OpenCV dlls.

  static unsigned int data[] = {0, 0, 64, 32, 64, 64};
  IplImage* image = cvCreateImage(cvSize(128, 128), IPL_DEPTH_8U, 3);
  cvSetZero(image);

  for(size_t i = 0 ; i<(sizeof(data)/sizeof(unsigned int))/3 ; ++i)
  {
    unsigned int x = data[3*i+0];
    unsigned int y = data[3*i+1];
    unsigned int w = data[3*i+2];
    printf("draw (%d,%d)->(%d,%d)\n", x, y, x+w, y);
    cvRectangle(image, cvPoint(x, y), cvPoint(x+w, y), cvScalar(255, 255, 255), CV_FILLED);
    //cvLine(image, cvPoint(x, y), cvPoint(x+w, y), cvScalar(255, 255, 255));
  }//end for each segment

  cv::imwrite("target.png", cv::cvarrToMat(image, false));

**Comment by alalek** [comment]
Probably related: #7785

**Comment by alalek** [comment]
> it seems to be related to edge[].x not initialized in FillConvexPoly

Confirmed.
