### ISSUE TITLE
cv2.moments all zero in 3.1.0

### ISSUE THREAD

**Issue by jbrockmendel** [opencv/opencv#7962]
##### System information (version)
- OpenCV => 3.1.0
- Operating System / Platform => OSX 10.12.1 (also Ubuntu 16.04)
- Compiler => GCC 4.2.1 (GCC 5.4.0 on the Ubuntu)

##### Detailed description

cv2.moments(...) is incorrectly returning all-zeros on some inputs.  An example is below.  This appears to be resolved by re-casting the input array from numpy.float32 to numpy.float64.

The issue first came up after a pip bump of cv2 from 2.4.9.1 to 3.1.0.  Using the same example in with the older version produces the correct result.

##### Steps to reproduce

Using Python 2.7.12 on OSX 10.12.1:

``` 
>>> cv2.__version__
'3.1.0'
>>> arr = numpy.array([[141.0, 234.0], [249.0, 255.0]], dtype=numpy.float32)
>>> arr
array([[ 141.,  234.],
       [ 249.,  255.]], dtype=float32)
>>> cv2.moments(arr)
{'mu02': 0.0, 'mu03': 0.0, 'm11': 0.0, 'nu02': 0.0, 'm12': 0.0, 'mu21': 0.0, 'mu20': 0.0, 'nu20': 0.0, 'm30': 0.0, 'nu21': 0.0, 'mu11': 0.0, 'mu12': 0.0, 'nu11': 0.0, 'nu12': 0.0, 'm02': 0.0, 'm03': 0.0, 'm00': 0.0, 'm01': 0.0, 'mu30': 0.0, 'nu30': 0.0, 'nu03': 0.0, 'm10': 0.0, 'm20': 0.0, 'm21': 0.0}
>>> cv2.moments(arr.astype(numpy.float64))
{'mu02': 215.01706484641642, 'mu03': -31.555405421146475, 'm11': 255.0, 'nu02': 0.0002782884481232764, 'm12': 255.0, 'mu21': 2.8587519947815423, 'mu20': 216.96245733788396, 'nu20': 0.00028080629598724885, 'm30': 489.0, 'nu21': 1.2479704239158335e-07, 'mu11': -25.382252559726965, 'mu12': 3.725040478048655, 'nu11': -3.2851288709409625e-05, 'nu12': 1.6261432796478948e-07, 'm02': 504.0, 'm03': 504.0, 'm00': 879.0, 'm01': 504.0, 'mu30': -24.436044683106388, 'nu30': -1.0667403502531846e-06, 'nu03': -1.3775316205165773e-06, 'm10': 489.0, 'm20': 489.0, 'm21': 255.0}
```

**Comment by alalek** [comment]
> 3.1.0

This release is outdated. Please try 3.2.0 or master branch.

**Comment by jbrockmendel** [comment]
I've learned the hard way not to get in the way of pip/homebrew.  Once
3.2.0 goes up on pypi I'll update the results here.

**Comment by mshabunin** [comment]
@jbrockmendel , the moments function treats your input as a contour (see documentation [comment](http://docs.opencv.org/master/d3/dc0/group__imgproc__shape.html#ga556a180f43cab22649c23ada36a8a139) and related discussion - #6643).
