### ISSUE TITLE
libopencv_core.so.3.2.0: undefined reference to `dpotrf_'

### ISSUE THREAD

**Issue by tofisa** [opencv/opencv#7970]
I'm installing opencv 3.2 and when I use :+1: 
cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON ..

and 

make -j4  , this error is showing , how can be solved ?

[ 75%] Linking CXX executable ../../bin/opengl-example-opengl_interop
../../lib/libopencv_core.so.3.2.0: undefined reference to `dpotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sposv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `spotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dposv_'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_version] Error 1
make[1]: *** [apps/version/CMakeFiles/opencv_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 75%] Built target opencv_annotation
[ 75%] Built target opencv_visualisation
[ 75%] Built target example_opengl_opengl_interop

**Comment by majiefei** [comment]
i have exactly the same problem

**Comment by alalek** [comment]
More details are required:
- CMake stdout (from clean build)
- CMakeCache.txt CMakeVars.txt
- failed command line via `make VERBOSE=1` (without any `-j` option)

Also try to disable blas/lapack support (`-DWITH_LAPACK=OFF`) as workaround.

**Comment by yuanxy92** [comment]
I have the same problem
I use Ubuntu 14.04 x64 with cuda

I use CMake-gui, since I am not familiar with cmake command line. (It is more convenient to set values in gui):

[CMake stdout.txt](https://github.com/opencv/opencv/files/691480/CMake.stdout.txt)
[CMakeCache.txt](https://github.com/opencv/opencv/files/691481/CMakeCache.txt)
[CMakeVars.txt](https://github.com/opencv/opencv/files/691482/CMakeVars.txt)

Thanks very much!

**Comment by chrisabbott** [comment]
Encountered the same error running Ubuntu 14.04 x64 with CUDA.
Adding the flag -D WITH_LAPACK=OFF to the cmake command as suggested resolved this issue for me.

**Comment by alalek** [comment]
@yuanxy92 Thank you! Looks like it is related to OpenBLAS support.
Could someone run `make VERBOSE=1` and dump here a failed command line with parameters?

**Comment by yuanxy92** [comment]
I can successfully compile the project after setting WITH_LAPACK=OFF, too. Thank @chrisabbott.

the following is failed command line with WITH_LAPACK=ON
../../lib/libopencv_core.so.3.2.0: undefined reference to `dpotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sposv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `spotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dposv_'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_traincascade] Error 1
make[1]: *** [apps/traincascade/CMakeFiles/opencv_traincascade.dir/all] Error 2
make: *** [all] Error 2

[make_error.txt](https://github.com/opencv/opencv/files/692073/make_error.txt)

I hope it is useful to you, @alalek .
Thanks very much!

**Comment by tofisa** [comment]
Thanks , the issue is resolved with  WITH_LAPACK=OFF

**Comment by alalek** [comment]
@yuanxy92 Could you post `make VERBOSE=1` log with failed command line? (build log above is successful, but it uses `-lopenblas`)

**Comment by alalek** [comment]
Could someone check fix #7999 please?

**Comment by randolphwong** [comment]
@alalek I'm facing the same issue on my ubuntu 14.04 machine. I've tested #7999 and it works great.

**Comment by Jaykob** [comment]
I'm getting the same undefined symbols errors when linking the osx framework built on a Mac (macOS 10.12.2, Xcode 8.2.1).
LAPACK is correctly found (accelerate framework) and enabled by cmake. 
It works when I disable LAPACK as suggested.

**Comment by kevinkatzke** [comment]
Adding -DWITH_LAPACK=OFF to the cmake solved this issue for me. Thanks @tofisa ^^

**Comment by FlorianFranzen** [comment]
I have the same problem trying to build opencv 3.2.0 in a ubuntu docker container. As soon as I install libopenblas-dev, compiling opencv core fails with the following error:
```
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/hal_internal.cpp.o
In file included from /opencv/modules/core/src/hal_internal.cpp:49:0:
/opencv/build/opencv_lapack.h:2:45: fatal error: LAPACKE_H_PATH-NOTFOUND/lapacke.h: No such file or directory
compilation terminated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/hal_internal.cpp.o] Error 1
```
My guess is, that ```LAPACKE_H_PATH``` is not set correctly by cmake when building against OpenBLAS.

**Comment by soulslicer** [comment]
So OpenCV 3.2.0 has no LAPACK support?

**Comment by FlorianFranzen** [comment]
In my experience at least the tagged release can not be build against OpenBLAS.

**Comment by DongdongBai** [comment]
If I want to use OpenCV 3.2.0 with LAPACK, what should I do?

**Comment by nith02** [comment]
On Ubuntu 16.04, build OpenCV 3.2.0 with LAPACK is ok. I think you can try Ubuntu 16.04

**Comment by FlorianFranzen** [comment]
@DongdongBai I am not sure if there is a plan to release a 3.2.1 any time soon, so my best guess would be to cherry pick the commit the that fixed it (see #7999 or [here](https://github.com/alalek/opencv/tree/fix_lapack)) and applying to it 3.2.0.

**Comment by afunTW** [comment]
@nith02 I try this [install script](https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh) on ubuntu 16.04 but it still get this error.

--   Other third-party libraries:
--     Use IPP:                     9.0.1 [9.0.1]
--     Use IPP Async:               NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     **Use Lapack:                  YES (/usr/lib/libopenblas.so)**
--     Use Eigen:                   YES (ver 3.2.92)
--     Use Cuda:                    NO
--     Use OpenCL:                  YES
--     Use OpenVX:                  NO
--     Use custom HAL:              NO

**Comment by afunTW** [comment]
according to this [forum](http://answers.opencv.org/question/121651/fata-error-lapacke_h_path-notfound-when-building-opencv-32/)

install lapacke manually
`$ sudo apt-get install liblapacke-dev`

and modify the file `opencv_lapack.h`
from `#include "LAPACKE_H_PATH-NOTFOUND/lapacke.h"`
to  `#include "lapacke.h"`

it can solved this problem

**Comment by soulslicer** [comment]
Will there be a new release with the LAPACK fix? It's working on paster now after fix_lapack branch was merged

**Comment by kb1ooo** [comment]
@afunTW that does not solve this problem.  That is for a different error as shown in the link you provided.

As @FlorianFranzen has suggested, you may want to cherry pick pull request #7999, however if you have downloaded the 3.2.0 release as opposed to cloning the repo (or if you'd just prefer not to mess around with cherry picking), you can apply it via a patch as follows:

    cd opencv-3.2.0
    wget https://patch-diff.githubusercontent.com/raw/opencv/opencv/pull/7999.patch
    patch -p1 <7999.patch

and rebuild.  Works for me,  I'm on ubuntu 14.04.

The alternative, as some have suggested, is to not build with lapack by adding  `-DWITH_LAPACK=OFF` to your cmake command line.   Of course in that case, your opencv build will not be using lapack.

**Comment by soulslicer** [comment]
What are the main benefits of using the LaPack extension? Do you see significant improvements on the standard opencv calls..like findContours, morphology etc.

**Comment by kb1ooo** [comment]
@soulslicer I haven't studied the performance in opencv, however my experience is that the speedup for linear algebra (matrix/vector multiplications) and solvers (SVD, etc) is significant (orders of magnitude) over any other implementations.  In particular as the matrices get large.  Also with MKL having the fastest cpu implementation of blas/lapack.   Nvidia claims that their gpu blas implementation is 10x faster than MKL.

**Comment by dkqCoder** [comment]
@chrisabbott Thank you! I solveed

**Comment by netscream** [comment]
The problem is when installing OpenBLAS on fedora f.ex, the includes go into /usr/include/openblas,
if there is a file named cblas.h inside the /usr/include folder then it seems that cmake is unable to spot the correct folder "/usr/include/openblas".

I even changed the order where openblas is searched for inside the OpenCVFindOpenBLAS.cmake file and at one time I remove the /usr/include line from the file, but still it defaults to /usr/include instead of /usr/include/openblas!

By changing the line inside OpenCVFindOpenBLAS.cmake,
FIND_PATH(OpenBLAS_INCLUDE_DIR NAMES cblas.h PATHS ${Open_BLAS_INCLUDE_SEARCH_PATHS})

to 

SET(OpenBLAS_INCLUDE_DIR /usr/include/openblas)

DID IT FOR ME, running Fedora 25
.........
TBH. I have not worked much with cmake before, so I am not sure what it

**Comment by netscream** [comment]
@afunTW 
Please try this,
$ locate cblas.h 
or 
$ find /usr -name "cblas.h" 
if you have this file inside multiple locations then this could be the problem, 
if you get a folder named /xxx/xxx/openblas then this workaround above could work.

**Comment by afunTW** [comment]
@netscream Thanks reply, it solved.

**Comment by Santi-7** [comment]
Same issue experimented in Ubuntu 14.04.

@netscream I've multiple locations of BLAS.

    /usr/local/MATLAB/R2012b/toolbox/rtw/rtwdemos/crl_demo/cblas.h
    /usr/include/atlas/cblas.h
    /usr/include/cblas.h

Is there then any solution to use OpenCV 3.2 with LAPACK and BLAS in Ubuntu 14.04?

**Comment by netscream** [comment]
@santi-7 I used openblas, but I can see you have atlas, in the cmake folder within the base there should be FindAtlas.cmake or OpenCVFindAtlas.cmake

Then the same solution should apply as I stated above, but instead of /usr/include/openblas you should use /usr/include/atlas
