### ISSUE TITLE
VIDEOIO ERROR: V4L2: Pixel format unsupported

### ISSUE THREAD

**Issue by dzach** [opencv/opencv#7974]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Linux / Kubuntu 16.04 64 bit
- Compiler => g++

##### Detailed description

My opencv installation works fine with most webcams, except for a **Philips SPC 900NC** CCD webcam. 

From searching the Internet I gather that there was a time when opencv supported this camera, but it seems that something changed since then, probably after _v4l_ changed to _v4l2_. This link, http://nuigroup.com/forums/viewthread/291/ ,  has a patch to make the camera work in _YUV420P_ mode, but it looks like most of this code is already included in the current release. A number of multimedia and communications programs, e.g. Cheese, VLC, Skype and others, can access the camera without a problem in Linux, but e.g. mjpg-streamer can not.

##### How to reproduce the problem:
Compile a demo program, e.g. _bg_sub.cpp_ from the tutorials, and run it with this camera:
```
$ ./bg_sub -vid /dev/video0
Welcome! OpenCV version: 3.2.0 (3.2.0)
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Could not initialize capturing. Exiting...
```

I can provide more debug info about the VIDEOIO ERROR, pixel format, etc, if someone can suggest a way to do it properly.

**Comment by dzach** [comment]
Thanks arpu!

Here's the output:

```
$ v4l2-ctl -d /dev/video0 --all
Driver Info (not using libv4l2):
        Driver name   : pwc
        Card type     : Philips SPC 900NC webcam
        Bus info      : usb-0000:00:12.0-2
        Driver version: 4.4.16
        Capabilities  : 0x85200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps   : 0x05200001
                Video Capture
                Read/Write
                Streaming
                Extended Pix Format
Priority: 2
Video input : 0 (Camera: ok)
Format Video Capture:
        Width/Height      : 640/480
        Pixel Format      : 'YU12'
        Field             : None
        Bytes per Line    : 640
        Size Image        : 460800
        Colorspace        : sRGB
        Transfer Function : Default
        YCbCr Encoding    : Default
        Quantization      : Default
        Flags             : 
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 15.000 (15/1)
        Read buffers     : 2

User Controls

                     brightness (int)    : min=0 max=127 step=1 default=64 value=64 flags=slider
                       contrast (int)    : min=0 max=63 step=1 default=32 value=32 flags=slider
                     saturation (int)    : min=-100 max=100 step=1 default=-100 value=-100 flags=slider
        white_balance_automatic (menu)   : min=0 max=4 default=4 value=4 flags=update
                    red_balance (int)    : min=0 max=255 step=1 default=96 value=132 flags=inactive, slider, volatile
                   blue_balance (int)    : min=0 max=255 step=1 default=96 value=49 flags=inactive, slider, volatile
                          gamma (int)    : min=0 max=31 step=1 default=19 value=19 flags=slider
                       exposure (int)    : min=0 max=255 step=1 default=245 value=248 flags=inactive, volatile
                 gain_automatic (bool)   : default=1 value=1 flags=update
                           gain (int)    : min=0 max=63 step=1 default=3 value=8 flags=inactive, volatile
         backlight_compensation (bool)   : default=1 value=1
                  color_effects (menu)   : min=0 max=1 default=0 value=0
               band_stop_filter (bool)   : default=1 value=1
                   auto_contour (bool)   : default=0 value=0 flags=update
                        contour (int)    : min=0 max=63 step=1 default=32 value=32 flags=slider
        dynamic_noise_reduction (int)    : min=0 max=3 step=1 default=3 value=3
       auto_white_balance_speed (int)    : min=1 max=32 step=1 default=32 value=32
       auto_white_balance_delay (int)    : min=0 max=63 step=1 default=0 value=0
             save_user_settings (button) : flags=write-only, execute-on-write
          restore_user_settings (button) : flags=update, write-only, execute-on-write
       restore_factory_settings (button) : flags=update, write-only, execute-on-write
```

> not using libv4l2

and

> Pixel Format      : 'YU12'

seem to shed some light to why it doesn't play as expected.

**Comment by arpu** [comment]
v4l2-ctl  -d /dev/video0 --list-formats

maybe your camera can more formats

**Comment by dzach** [comment]
Here is the output:

```
$ v4l2-ctl -d /dev/video0 --list-formats
ioctl: VIDIOC_ENUM_FMT
        Index       : 0
        Type        : Video Capture
        Pixel Format: 'PWC2' (compressed)
        Name        : Raw Philips Webcam Type (New)

        Index       : 1
        Type        : Video Capture
        Pixel Format: 'YU12'
        Name        : Planar YUV 4:2:0
```

The reason I still like this old camera, despite it being only 640x480px, is because it uses a CCD, and so it does not suffer from the "rolling shutter" effects of the CMOS ones. Back in the day, there was a driver (pwc) that was capable of making this and other webcams work on Linux, but it seems that this capability is dropped (?).

@arpu, thank you much for helping me with this. I'll be glad to try any suggestion to make this camera work.

**Comment by dzach** [comment]
This YU12 pixel format that was revealed gave some more clues on what to search for. Here is a screenshot of _qv4l2_ listing the supported image formats:

![philips-spc-900nc](https://cloud.githubusercontent.com/assets/1109829/21715947/0bc4a3ec-d410-11e6-897c-27959bf41702.png)

Interestingly, _qv4l2_ can display the video coming from the camera without any problem. 

Searching for 'opencv YU12' gives some interesting results: Image formats provided by this camera are supported by _v4l_ but seem to have dropped out of _v4l2_. Here are some interesting links:

http://answers.opencv.org/question/9659/solved-how-to-make-opencv-to-ask-libv4l-yuyv-pixelformat-instead-of-bgr24/

So it seems like I could try compiling opencv with _-D WITH_V4L=ON_ and see if this makes any difference.

Any suggestions are welcome.

**Comment by dzach** [comment]
I finaly managed to get the Philips SPC 900NC CCD webcam to work with opencv. Based on the observations made in the previous post, I changed the following lines to ON in  the CMakeLists.txt and recompiled opencv:

```
OCV_OPTION(WITH_V4L            "Include Video 4 Linux support"               ON   IF (UNIX AND NOT ANDROID) )
OCV_OPTION(WITH_LIBV4L         "Use libv4l for Video 4 Linux support"        ON   IF (UNIX AND NOT ANDROID) )
```

I now I have a functional camera.

**Comment by kozuch** [comment]
@dzach 

Hello, I am trying to get uncompressed video from the Logitech QuickCam Pro 4000 in OpenCV (2.4). This webcam has a almost the same sensor as your Phillips ([see here](https://www.rkblog.rk.edu.pl/astro/kamery-ccd/)). My v4l2-ctl shows exactly the same modes as yours (PWC2 and YU12). When I try to switch the mode (I am not really sure I am doing it correctly - using following: v4l2-ctl -d /dev/video1 --set-fmt-video=width=160,height=120,pixelformat=1) I dont get any errors on console (assuming the switch was made) but when I run any webcam viewer and save image (as png etc.) I still see 4x4 jpeg compression artefacts (probably from camera HW in MJPEG stream). I tried these apps on Ubuntu 15.10 - cheese, Kamerka.

My output is here:

```
$ v4l2-ctl -d /dev/video1 --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'PWC2' (compressed)
	Name        : Raw Philips Webcam

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YU12'
	Name        : 4:2:0, planar, Y-Cb-Cr
```

```
$ v4l2-ctl -d /dev/video1 --all
Driver Info (not using libv4l2):
	Driver name   : pwc
	Card type     : Logitech QuickCam Pro 4000
	Bus info      : usb-0000:00:14.0-2
	Driver version: 3.19.3
	Capabilities  : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x05200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera: ok)
Format Video Capture:
	Width/Height  : 640/480
	Pixel Format  : 'YU12'
	Field         : None
	Bytes per Line: 640
	Size Image    : 460800
	Colorspace    : SRGB
	Flags         : 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 15.000 (15/1)
	Read buffers     : 2
```
I guess I use OpenCV that is in Ubuntu repositories. I can try compile 3.2 but am not sure it will help. I also get HIGUI errors when try following:

```
cap1.set(CV_CAP_PROP_FOURCC, CV_FOURCC('M', 'J', 'P', 'G') );
cap1.set(CV_CAP_PROP_MODE, 1);
```

Does your Y420 show compression artefacts of not? Are you sure it is really uncompressed?

I tried to save image from qv4l2 - the image is saved but in unknown format and I can not figure out which format is used. But when I take screenshot from live qv4l2 camera feed the camera picture again has artefacts even when set to YU12.

**Comment by dzach** [comment]
@kozuch 
I am afraid I cannot help much with your question, as I am not an expert of any kind in either cameras or OpenCV. My sole concern with this camera was that it did not work at all with openCV, before the changes I made to the CMakeLists.txt described above. 

I don't have the camera at present, but I don't remember observing any pronounced compression artifacts with it.

**Comment by nk0307** [comment]
well it is not working  though. pity!

**Comment by monajalal** [comment]
I get this error. How should I fix it?

```
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
Error getting frame from device 0
(workon-py3)$ v4l2-ctl -d /dev/video0 --all
Driver Info (not using libv4l2):
	Driver name   : uvcvideo
	Card type     : HD Pro Webcam C920
	Bus info      : usb-0000:00:14.0-9
	Driver version: 4.13.13
	Capabilities  : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 320/180
	Pixel Format      : 'YUYV'
	Field             : None
	Bytes per Line    : 640
	Size Image        : 115200
	Colorspace        : sRGB
	Transfer Function : Default
	YCbCr Encoding    : Default
	Quantization      : Default
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 320, Height 180
	Default     : Left 0, Top 0, Width 320, Height 180
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 320, Height 180
Selection: crop_bounds, Left 0, Top 0, Width 320, Height 180
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
                     brightness (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast (int)    : min=0 max=255 step=1 default=128 value=128
                     saturation (int)    : min=0 max=255 step=1 default=128 value=128
 white_balance_temperature_auto (bool)   : default=1 value=1
                           gain (int)    : min=0 max=255 step=1 default=0 value=132
           power_line_frequency (menu)   : min=0 max=2 default=2 value=2
      white_balance_temperature (int)    : min=2000 max=6500 step=1 default=4000 value=3255 flags=inactive
                      sharpness (int)    : min=0 max=255 step=1 default=128 value=128
         backlight_compensation (int)    : min=0 max=1 step=1 default=0 value=0
                  exposure_auto (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute (int)    : min=3 max=2047 step=1 default=250 value=333 flags=inactive
         exposure_auto_priority (bool)   : default=0 value=1
                   pan_absolute (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                 focus_absolute (int)    : min=0 max=250 step=5 default=0 value=0 flags=inactive
                     focus_auto (bool)   : default=1 value=1
                  zoom_absolute (int)    : min=100 max=500 step=1 default=100 value=100
                      led1_mode (menu)   : min=0 max=3 default=0 value=3
                 led1_frequency (int)    : min=0 max=255 step=1 default=0 value=0

```
