### ISSUE TITLE
/home/sunpeng/opencv-3.1.0/samples/gpu/opengl.cpp:16:23:fatal error: GL/gl.h

### ISSUE THREAD

**Issue by sunpeng1996** [opencv/opencv#7980]
when I compile the opencv,I met the problem.What should I do?

/home/sunpeng/opencv-3.1.0/samples/gpu/opengl.cpp:16:23:fatal error: GL/gl.h: 没有那个文件或目录
compilation terminated.
samples/gpu/CMakeFiles/example_gpu_opengl.dir/build.make:62: recipe for target 'samples/gpu/CMakeFiles/example_gpu_opengl.dir/opengl.cpp.o' failed
make[2]: *** [samples/gpu/CMakeFiles/example_gpu_opengl.dir/opengl.cpp.o] Error 1
CMakeFiles/Makefile2:21644: recipe for target 'samples/gpu/CMakeFiles/example_gpu_opengl.dir/all' failed
make[1]: *** [samples/gpu/CMakeFiles/example_gpu_opengl.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 80%] Built target example_gpu_farneback_optical_flow
[ 80%] Built target example_gpu_performance
[ 80%] Built target example_gpu_multi
[ 80%] Built target example_gpu_video_writer
[ 80%] Built target example_gpu_stereo_match
[ 80%] Built target example_gpu_alpha_comp
[ 80%] Built target example_gpu_cascadeclassifier_nvidia_api
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => ubuntu 16.04
- cmake

**Comment by sunpeng1996** [comment]
##### System information (version)

**Comment by sunpeng1996** [comment]
@peters @jviney @blebo @lvv @Reen

**Comment by alalek** [comment]
Try to disable OpenGL support via CMake command-line option: `-D WITH_OPENGL=OFF`

**Comment by vpisarev** [comment]
closing incomplete unattended question
