### ISSUE TITLE
Could not detect AVX and AVX2 on Windows

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#7981]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2015
- CPU => Intel Core i7-6700HQ

##### Detailed description
I used Skylake architecture CPU. This CPU supports AVX and AVX2.
But, AVX2 implementation was not called in cv::norm.

I think that this condition(<code>&& 0</code>) is unnecessary.
<https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/cvdef.h#L196-L214>

##### Steps to reproduce

```cpp
#include <opencv2/core.hpp>
#include <iostream>

int main(int argc, const char* argv[])
{
    cv::Mat src(cv::Size(4, 4), CV_8UC1);
    cv::norm(src, cv::NORM_HAMMING);

    return 0;
}
```

**Comment by atinfinity** [comment]
Sorry, I misunderstood.
I checked the following flag in CMake. As a result, AVX2 implementation was called in cv::norm.

- [x] ENABLE_AVX2

And, I have some comment.

* I think that it is better to use <code>USE_AVX2</code> in [this code](https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/stat.cpp#L4256).
* I can not understand the necessity of this condition(<code>&& 0</code>).
https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/cvdef.h#L196-L214

**Comment by alalek** [comment]
Condition `&& 0` usually means what this code is disabled for some reason (need to use "git blame" to get details if there is no related comments).
Using of `USE_AVX2` in mentioned code is good idea.

**Comment by atinfinity** [comment]
@alalek
Thank you for your comment.

> Condition <code>&& 0</code> usually means what this code is disabled for some reason (need to use "git blame" to get details if there is no related comments).

I will trace the history of this change.

> Using of <code>USE_AVX2</code> in mentioned code is good idea.

I made #7986.

**Comment by alalek** [comment]
Modern MSVC compilers defines __AVX2__, so there is no problem with disabled condition (probably it is hard to detect specific version of MSVC update):

> The _M_IX86_FP, __AVX__ and __AVX2__ macros indicate which, if any, /arch compiler option was used. For more information, see Predefined Macros. The /arch:AVX2 option and __AVX2__ macro were introduced in Visual Studio 2013 Update 2, version 12.0.34567.1.

https://msdn.microsoft.com/en-us/7t5yh4fd
