### ISSUE TITLE
http://docs.opencv.org/opencv_cheatsheet.pdf File not found

### ISSUE THREAD

**Issue by GisTom2** [opencv/opencv#7984]
##### System information (version)

- OpenCV => na
- Operating System / Platform => na
- Compiler => na

##### Detailed description

The page https://github.com/opencv/opencv/wiki has 
a link to the Cheatsheet http://docs.opencv.org/opencv_cheatsheet.pdf
But the link http://docs.opencv.org/opencv_cheatsheet.pdf is broken.
Not Found
The requested URL /opencv_cheatsheet.pdf was not found on this server.

##### Steps to reproduce
Click http://docs.opencv.org/opencv_cheatsheet.pdf

**Comment by karandeepdps** [comment]
You need to provide Build Version to access the cs.

http://docs.opencv.org/2.4/opencv_cheatsheet.pdf

**Comment by mshabunin** [comment]
Fixed the link.
