### ISSUE TITLE
cv::ocl::useOpenCL() throws cv::Exception

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#7995]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2015 Update3
- CPU => Intel Core i7-6700HQ
- OpenCL SDK => CUDA 8 Toolkit
  - Other OpenCL SDK is not installed

##### Detailed description

When I build OpenCV, I checked <code>WITH_OPENCL</code> flag using CMake.
As a result, <code>cv::ocl::useOpenCL()</code> throws <code>cv::Exception</code>.

##### Steps to reproduce

I checked the following flag using CMake.
- [x] WITH_OPENCL

And, I launched the following code.
As a result, <code>cv::ocl::useOpenCL()</code> throws <code>cv::Exception</code>.

```cpp
#include <opencv2/core.hpp>
#include <opencv2/core/ocl.hpp>
#include <iostream>

int main(int argc, const char* argv[])
{
    bool useOpenCL = cv::ocl::useOpenCL();
    return 0;
}
```

I tried to uncheck <code>WITH_OPENCL</code> flag.
As a result, <code>cv::ocl::useOpenCL()</code> does not throw <code>cv::Exception</code>.

**Comment by alalek** [comment]
More info is required:
- exception message
- stack trace

**Comment by atinfinity** [comment]
### exception message
> Unhandled exception at 0x00007FFA2E5D7788 in ocl_test.exe: Microsoft C++ exception: cv::Exception at memory location 0x000000BE5F3AF960.

This message was displayed in output window of Visual Studio.

### stack trace
<pre>
cv::ocl::useOpenCL
 cv::ocl::haveOpenCL
  opencl_check_fn <-- throw cv::Exception
</pre>

And, I found that <code>CV_CL_GET_PROC_ADDRESS</code> returns NULL.
<https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/opencl/runtime/opencl_core.cpp#L275>

**Comment by atinfinity** [comment]
I checked "CMakeVars.txt".

> HAVE_OPENCL=1
HAVE_OPENCL_STATIC=OFF

But, I could not find "OpenCL.dll" in the following place.

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

**Comment by alalek** [comment]
This exception is expected and handled by try/catch block in mentioned [`cv::ocl::haveOpenCL()` function](https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/ocl.cpp#L1461-L1484).
What is the real problem?

**Comment by atinfinity** [comment]
I investigated using debugger. cv::Exception was thrown in this place.
<https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/opencl/runtime/opencl_core.cpp#L278>

cv::ocl::useOpenCL and cv::ocl::haveOpenCL catch exception.
But, these function does not output error message.

* <https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/ocl.cpp#L1474-L1477>
* <https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/ocl.cpp#L1495-L1498>

**Comment by alalek** [comment]
Currently OpenCV doesn't have logging routines, so some "verbose" message about unsupported/missed OpenCL support is not printed at all. Also OpenCL acceleration will be not used on your machine.

Does it break something?

**Comment by atinfinity** [comment]
> Currently OpenCV doesn't have logging routines, so some "verbose" message about unsupported/missed OpenCL support is not printed at all. Also OpenCL acceleration will be not used on your machine.

I understood.

> Does it break something?

No. Because, cv::ocl::haveOpenCL() always returns false.
So, OpenCL implementation does not called in UMat.

But, it seems that CUDA8 Toolkit(for Windows) provides only OpenCL.lib.
I don't know why HAVE_OPENCL_STATIC is OFF.

**Comment by alalek** [comment]
> why HAVE_OPENCL_STATIC is OFF

This is default value, you can redefine it (by passing OPENCL_LIBRARY/OPENCL_INCLUDE_DIR CMake variables).
Take a look here: https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectOpenCL.cmake
