### ISSUE TITLE
`waitKey(>0)` returns 255 when no key pressed

### ISSUE THREAD

**Issue by Sahloul** [opencv/opencv#7997]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
`waitKey()` returns `255` instead of `-1`.

##### Steps to reproduce

```.cpp
#include <iostream>
#include <opencv/cv.hpp>

int main(int argc, char** argv)
{
	cv::Mat test(480, 640, CV_8UC1);
	test.setTo(0);
	cv::imshow("test", test);
	std::cout << cv::waitKey(1) << std::endl;
	return 0;
}
```

##### Expected output
```
-1
```

##### Actual output
```
255
```

**Comment by ce047** [comment]
@alalek sorry, could you please point out the duplicated issue. cannot find it...

**Comment by monajalal** [comment]
I have the same exact problem. Is there a fix to this? I am using Python opencv (cv2).
