### ISSUE TITLE
The index type to access Mat elements should be size_t instead of int

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#8003]
##### System information (version)
- OpenCV => latest
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Steps to reproduce
In visual studio there is warning [C4365](https://msdn.microsoft.com/en-us/library/ms173683.aspx) when there is signed and unsigned mismatch, and [C4267](https://msdn.microsoft.com/en-us/library/6kck0s93.aspx) when there might be a data loss during type conversion.

When accessing elements in STL containers, the index type are assumed to be size_t, which makes sense because the index can never go below zero, however, when accessing Mat elements it is assuming the index to be int, which will cause a lot of C4365 and C4267.

``````
cv::Mat test = cv::Mat(100, 100, CV_8UC1);
std::vector<int> test2(100);

for (size_t i = 0; i < 1; i++){
  test.at<uchar>(i, 0) = 0; // C4365 and C4267
  test2[i] = 0;
}
`````` 

``````
cv::Mat test = cv::Mat(100, 100, CV_8UC1);
std::vector<int> test2(100);

for (int i = 0; i < 1; i++){
  test.at<uchar>(i, 0) = 0; 
  test2[i] = 0; // C4365
}
`````` 

The below workaround works but it quickly becomes unreadable when the code is large and too much static_cast is needed. 

``````
cv::Mat test = cv::Mat(100, 100, CV_8UC1);
std::vector<int> test2(100);

for (size_t i = 0; i < 1; i++){
  test.at<uchar>(static_cast<int>(i), 0) = 0;
  test2[i] = 0;
}
`````` 

Can we make the index type to access mat element to size_t?

**Comment by alalek** [comment]
> index type to access mat element to size_t

Negative "indexing" values have sense in case of image ROI.
In some cases performance of "int" type is better that "size_t". Also "int" type is used for historical reasons.
Most of OpenCV algorithms doesn't support size_t internally, so this change will just confuse users and break a lot of existed code without significant benefits.
