### ISSUE TITLE
latch_match error

### ISSUE THREAD

**Issue by simon1tan** [opencv/opencv#8006]
I was able to compile latch_match.cpp in the tutorial samples but when I run the program, I am getting this error below:
OpenCV Error: Assertion failed (type == B.type() && (type == CV_32FC1 || type == CV_64FC1 || type == CV_32FC2 || type == CV_64FC2)) in gemm, file /home/stan/Downloads/opencv-3.2.0/modules/core/src/matmul.cpp, line 1530
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/stan/Downloads/opencv-3.2.0/modules/core/src/matmul.cpp:1530: error: (-215) type == B.type() && (type == CV_32FC1 || type == CV_64FC1 || type == CV_32FC2 || type == CV_64FC2) in function gemm

**Comment by berak** [comment]
it seems, your homography Mat was no loaded correctly, the path to resources has to be changed to:

    ../../../data

 if you want to run [this sample from the tutorials](https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/xfeatures2D/LATCH_match.cpp#L29) folder

**Comment by mshabunin** [comment]
@simon1tan , as @berak stated, you should provide correct input files to the application. Often tutorial code does not have command line argument parser and error handling, only basic algorithm, so users should pay attention to hardcoded filenames and do the checks by themselves if needed.
