### ISSUE TITLE
CV3 Hough Line Transform beta documentation

### ISSUE THREAD

**Issue by HaydonBerrow** [opencv/opencv#8012]
##### System information (version)
n/a

##### Detailed description

typo plus suggestion in http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html

"Hough Tranform in OpenCV" should be "Hough Transform in OpenCV"

I suggest this page should contain a link to API such as http://docs.opencv.org/3.0-beta/modules/imgproc/doc/feature_detection.html?highlight=houghlines#cv2.HoughLines. Anyone searching for "opencv houghlines documentation" will probably be looking for how to use it instead of how it works.

This might be a general problem with the documentation of opencv. It could usefully be separated into a low-level how-to-use (which I would call documentation), a high-level how-to-use (which I would call tutorial), and an explanation of how-it-works, which is what this page is.

##### Steps to reproduce

n/a

**Comment by mshabunin** [comment]
@HaydonBerrow , you are looking at the outdated documentation (3.0-beta), the latest documentation is here: http://docs.opencv.org/master/d6/d10/tutorial_py_houghlines.html However it still contains same typo.

You can read some thoughts about OpenCV documentation improvement [here](https://github.com/LorenaGdL/opencv/issues/1).
