### ISSUE TITLE
how to configure OpenCV file on Mac for Qt

### ISSUE THREAD

**Issue by ucsdxiaoyuzhou** [opencv/opencv#8017]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => OSX 10.12.3
- Compiler => Qt IDE
##### Detailed description

I am really a beginner of openCV and Qt. I installed Qt IDE and OpenCV3.2.0 already.
I am trying to implement the most basic program which is just to read and display a picture. But I am really confused on how to configure the path of header files and etc.
![screen shot 2017-01-16 at 11 58 56](https://cloud.githubusercontent.com/assets/23324604/21997260/30a5da7a-dbe3-11e6-8388-906271353573.png)
above is the screenshot of my bug.

and the followings are some related configuration I made:
I used "make -j8" to install the openCV
![screen shot 2017-01-16 at 11 58 44](https://cloud.githubusercontent.com/assets/23324604/21997331/9b39a1b4-dbe3-11e6-839c-9cb5b82c4b33.png)

here are some screenshots about my project:
![screen shot 2017-01-16 at 12 01 46](https://cloud.githubusercontent.com/assets/23324604/21997382/e32e82d2-dbe3-11e6-911d-c806e611b299.png)
![screen shot 2017-01-16 at 12 01 54](https://cloud.githubusercontent.com/assets/23324604/21997383/e3465362-dbe3-11e6-83b5-f57d7a7f3660.png)

Thanks for all your guys help!

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
