### ISSUE TITLE
stitch image error:libc++abi.dylib: terminating with uncaught exception of type cvflann::anyimpl::bad_any_cast

### ISSUE THREAD

**Issue by sushangjin** [opencv/opencv#8018]
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => iOS 10.2
- Compiler => 

##### Detailed description

stitching images on iphone will crash,output error:
libc++abi.dylib: terminating with uncaught exception of type cvflann::anyimpl::bad_any_cast

but stitching images success on the simulator.

##### Steps to reproduce
the iOS project file:
[opencvtest.zip](https://github.com/opencv/opencv/files/710318/opencvtest.zip)

**Comment by visez** [comment]
This user had the same problem 6 years ago, is it still applicable?
http://opencv-users.1802565.n2.nabble.com/cdiggins-anyimpl-bad-any-cast-while-using-flann-td7020469.html

**Comment by DmitryBulaienko** [comment]
+1

**Comment by p-i-** [comment]
https://stackoverflow.com/questions/41762869/stitching-panorama-on-ios-crashes-with-cvflannanyimplbad-any-cast <-- a couple of hack-arounds here.

**Comment by alalek** [comment]
Could someone try this [patch](https://github.com/opencv/opencv/pull/8736/commits/bdd9b244723300f5186a30f28e9288c7692a0fca) ? It resolves memory corruption problem in flann library for some Apple compilers.

**Comment by p-i-** [comment]
I'm also getting hit by this bug: runtime error upon executing `Stitcher::Status s = stitcher.estimateTransform(images);`.

The error only occurs in debug build. Release build works okay.

Was it just that modules/flann/include/opencv2/flann/any.h operator to add?   I inserted the code & rebuilt but it didn't change anything.

I noticed that patch is part of a larger commit (18 files modified). Should I be downloading and applying the whole commit? (can't see how to do this).

**Comment by alalek** [comment]
@p-i- Thank you for check! Other changes are not related to flann library.

**Comment by p-i-** [comment]
How does one go about debugging an iOS build? I can imagine setting up the project in Xcode copying across all the linker flags etc from `opencv/platforms/ios/build_framework.py` but that looks like a backbreaker.

**Comment by p-i-** [comment]
For my particular situation, replacing:  
    #import <opencv2/opencv.hpp>

... with:  
    #import <opencv2/stitching.hpp>
    #import <opencv2/imgcodecs/ios.h> // UIImageToMat

... did the trick. 

Hope this helps narrow it down for someone.

**Comment by devajith** [comment]
in my case replacing `#include <opencv2/opencv.hpp>`
with `#include <opencv2/imgcodecs.hpp>`  worked.

**Comment by alex0-0** [comment]
Tried all of methods mentioned above, no one works... Struggling with this exception for so long time, can anybody help me?

**Comment by eram1205** [comment]
Hi @alex0-0. I'm facing a very similar issue. Could you finally fix it?

**Comment by biomiker** [comment]
Having the same problem.  Can anyone please offer some help?  None of various suggestions have helped so far ...

**Comment by biomiker** [comment]
Here's a total hack that has gotten me past the  cvflann::anyimpl::bad_any_cast exception.  I suspect it will prove to be problematic down the road, but I'd be curious if anyone can comment on how feasible it is.  

In Pods->OpenCV2->opencv_modules.hpp, on line 17, change:

`#define HAVE_OPENCV_FLANN`
to
`#undef HAVE_OPENCV_FLANN`

**Comment by tosone** [comment]
Any idea now? I met this problem on ios 12.0 with opencv 3.4.4.

**Comment by SergioGeeK7** [comment]
My issue was solved starting the Flann as
`flann::Index lsh_index(Mat(), flann::LshIndexParams(20,15,2));`

**Comment by HHMedic** [comment]
http://answers.opencv.org/question/59996/flann-error-in-opencv-3/

solved

**Comment by dannydaddy3** [comment]
I had similar problem: Fixed it by replacing general import to specific ones.
But it didn't work for the first time, and then I realised I had 'PrefixHeader.pch' file which had `include <opencv2/opencv.hpp>`. 
I removed it and resolved problem with crash

**Comment by sunshinfight** [comment]
Including headers necessary but import <opencv2/opencv.hpp> work for me.
thanks.

**Comment by alalek** [comment]
`bad_any_cast` problem should be fixed here: #17640 (3.4.11 / 4.4.0)
