### ISSUE TITLE
${OpenCV_LIBS} is inconsistent with export TARGETS on windows 

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#8028]
##### System information (version)
- OpenCV => Latest pre-built binary for windows
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2015

##### Steps to reproduce

I am building a library that links to OpenCV, but the inconsistency with the export TARGETS and `${OpenCV_LIBS}` is causing some trouble. Below is the CMakeLists

``````
project(sample)

set(PROJECT_SRCS
${PROJECT_SOURCE_DIR}/src/Sample.cpp
)

set(PROJECT_INCS
${PROJECT_SOURCE_DIR}/include/Sample.h
)

find_package( OpenCV REQUIRED )

add_library(${PROJECT_NAME} SHARED ${PROJECT_SRCS} ${PROJECT_INCS})

target_include_directories(${PROJECT_NAME} PUBLIC
                          $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
                          $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include>)

target_include_directories(${PROJECT_NAME} SYSTEM PUBLIC
                          ${OpenCV_INCLUDE_DIRS})

target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS})

export(TARGETS
        sample
        FILE "${PROJECT_BINARY_DIR}/TestTargets.cmake")
``````

`${OpenCV_LIBS}` is `C:\opencv\build\x64\vc14\lib\opencv_world320.lib`, which is correct, hence it compiles without a problem. However, when I open `TestTargets.cmake` it shows 

``````
# Create imported target sample
add_library(sample SHARED IMPORTED)

set_target_properties(sample PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/jasjuang/sample/modules/Sample/include;C:/opencv/build/include;C:/opencv/build/include/opencv"
  INTERFACE_LINK_LIBRARIES INTERFACE_LINK_LIBRARIES "opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_world"
)
``````

The INTERFACE_LINK_LIBRARIES is not the expected `opencv_world320.lib` which is causing compilation error `LNK1181 cannot open input file 'opencv_calib3d.lib'` when other people is using my repository as an external library. Would be great if someone can fix it.

**Comment by alalek** [comment]
opencv_calib3d/opencv_core/etc (excluding world) are target aliases (generated for compatibility between opencv_world and non-world builds, so users can still write "target_link_libraries(target_name opencv_core opencv_highgui)").
Target aliases handling in CMake "exports" should be done by CMake, so you should report this to CMake upstream.

**Comment by jasjuang** [comment]
If I compile OpenCV from source, it generates `opencv_calib3d320.lib`, `opencv_core320.lib` etc which still causes the same compilation error `LNK1181 cannot open input file 'opencv_calib3d.lib'` because the lack of "320" in the library name.

Not sure I understand why it's a CMake bug. Do you mean that the `INTERFACE_LINK_LIBRARIES` generated by the CMake export is not specified by OpenCV? When I do a 

``````
message(OpenCV_libaries ${OpenCV_LIBS})
``````

the output is `OpenCV_libariesopencv_calib3dopencv_core...` , I am not sure how it ends up with the extra "320" `opencv_calib3d320.lib`, `opencv_core320.lib` when I inspect the linked libraries in Visual Studio, but shouldn't the same procedure be applied when doing CMake export?

Assuming the "320" problem can be solved, how about putting the non-world libs into the pre-built binary as well to avoid potential problems?

**Comment by alalek** [comment]
You should not have both opencv_world and opencv_calib3d .lib,.dll files. If so, you must build from scratch and don't mix world and non-world builds.

**Comment by jasjuang** [comment]
I am not mixing it. I deleted the pre-built version because the error was `cannot find 'opencv_calib3d.lib'` so I thought I had to compile OpenCV from source in order to use the export functionality correctly, but it turns out when I compile it from source the library generated has a "320" postfix on it like `'opencv_calib3d320.lib'`, so the export functionality is still not working. 

First I want to figure out how can I make this work when I compile OpenCV from source, as this seems like less things to fix (only need to figure out how to fix the "320" postfix problem). My proposal on this one is

1. Remove the "320" postfix entirely. There is no "320" postfix on Ubuntu and everything is working there. Why do we introduce this in Windows to complicate things?

2. Apply the same process the generates the "320" postfix (not sure how this is done) when export is invoked.

Assuming the first one can be fixed, next I want to figure out how can I make this work when I am using OpenCV prebuilt binaries.

**Comment by alalek** [comment]
> export functionality is still not working

Because CMake doesn't process target ALIASES correctly during export.
There is nothing to fix in OpenCV, including version suffix.

**Comment by jasjuang** [comment]
Could you show me a minimal example of how to recreate this problem so I can file an issue at CMake? I am unable to reproduce it myself. I tried something like 

``````
add_library(${PROJECT_NAME} ${PROJECT_SRCS})
add_library(haha ALIAS ${PROJECT_NAME})

export(TARGETS haha FILE ${CMAKE_BINARY_DIR}/ExampleTargets.cmake)
``````

But it gives me the error `export given ALIAS target "haha" which may not be exported`

**Comment by alalek** [comment]
Try to take your initial sample and run cmake with `--trace` (or `--trace-expand`) option.

**Comment by jasjuang** [comment]
I am not able to decipher anything meaningful with both `--trace` and `--trace-expand` option. I saved the output and search "320" but it yields nothing. I searched "opencv" it just shows the same thing from `TestTargets.cmake`. 

I tried to read the cmake files in OpenCV but it's too complicated for me and I am unable to pinpoint where the "320" postfix got added into the final library name.

Could you give me more help to create a minimal example to recreate this problem so I can file an issue at CMake? Thanks a lot for your help.

**Comment by alalek** [comment]
Additional targets are defined by [this part of code](https://github.com/opencv/opencv/blob/3.2.0/cmake/templates/OpenCVConfig.cmake.in#L178-L200). It doesn't use CMake ALIAS feature (as I wrote above (sorry about that), because we need to support older CMake versions too). This code simulates CMake IMPORTED targets with the same parameters as opencv_world.
So the line:
```
INTERFACE_LINK_LIBRARIES INTERFACE_LINK_LIBRARIES "opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_world"
```
seems valid.
And there is a list of target names - there are no names of files at all. "320" suffix is not expected here.

> The INTERFACE_LINK_LIBRARIES is not the expected opencv_world320.lib which is causing compilation error LNK1181 cannot open input file 'opencv_calib3d.lib' when other people is using my repository as an external library.

CMake expects definition of these OpenCV targets. You ("other people") need to define these targets via `find_package(OpenCV)` somewhere in your final CMakeLists.txt (which uses your generated "TestTargets.cmake").

There is nothing to fix in OpenCV or CMake currently.

**Comment by jasjuang** [comment]
Adding `find_package(OpenCV)` in the code of "other people" does work regardless of whether OpenCV is prebuilt or build from source.

Why does OpenCV prefer to define targets instead of absolute path to the library when exporting for INTERFACE_LINK_LIBRARIES? Other libraries like glog, tinyxml2, boost all exports the absolute path to the library so there is a benefit of not needing to add something like `find_package(glog)` in the code of "other people" and it will still work.

**Comment by alalek** [comment]
> define targets instead of absolute path

This is CMake way, which is able to handle many issues like dependencies between libraries, or external 3rdparty dependencies. Targets are able to handle include directories automaticaly (you don't need target_include_directories with OpenCV_INCLUDE_DIRS actually). Also you missed the hell with debug/release dependencies hacks via "optimized;general" keywords (required on Windows due Debug/Release conflicts).
