### ISSUE TITLE
vs2015 build fail

### ISSUE THREAD

**Issue by kyjak** [opencv/opencv#8033]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2015
##### Detailed description

The windows platform build files are not aligned to work with newer versions of visual studio,
can we expect a fix, or at least all library files built for download in the lib folder so the
linking is not needed?

**Comment by mschoeneck** [comment]
I had no problems to build OpenCV 3.2 with Visual Studio 2015 (32bit). As far as I remember there were some fixes for Visual Studio 2015 and 2017 in the new release.
Try 3.2 first if the build is OK. Maybe your issue is no more present.
