### ISSUE TITLE
StereoSGBM compute() fails with exception

### ISSUE THREAD

**Issue by drklimow** [opencv/opencv#8038]
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Windows 7 64 bit, 8 GiB RAM, MSYS2 MinGW64 64 bit 
- Compiler => gcc 6.3.0

##### Detailed description

A call to StereoSGBM::compute() with the parameters shown in the code example fails with an exception:

> user@user-PC MINGW64 ~/opencv_stereo_sgbm_testcase
> $ ./opencv_stereo_sgbm_testcase.exe
> OpenCV Error: Assertion failed (s >= 0) in setSize, file C:/msys64/home/user/MINGW-packages-master/mingw-w64-opencv/src/opencv-3.2.0/modules/core/src/matrix.cpp, line 307
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> terminate called after throwing an instance of 'cv::Exception'
>   what():  C:/msys64/home/user/MINGW-packages-master/mingw-w64-opencv/src/opencv-3.2.0/modules/core/src/matrix.cpp:307: error: (-215) s >= 0 in function setSize
> 
> 
> user@user-PC MINGW64 ~/opencv_stereo_sgbm_testcase
> $
> 

The compute() call succeeds with StereoSGBM::MODE_SGBM and StereoSGBM::MODE_SGBM_3WAY, but fails with StereoSGBM::MODE_HH.
The size of the input images affects this behaviour. It seems that compute() works fine when its memory consumption stays below 2 GiB.
Please note that all components involved are using a 64 bit address space, creating a 80000x80000 Mat<uint8_t> works without a problem and makes the process use 6.4 GB as expected.

##### Steps to reproduce

```.cpp
#include <opencv2/core/core.hpp>
#include <opencv2/calib3d/calib3d.hpp>

int main(void)
{
	cv::Mat src1, src0, disparity;

	src0.create(cv::Size(1812, 1737), CV_8U);
	src1.create(cv::Size(1812, 1737), CV_8U);

	cv::Ptr<cv::StereoSGBM> stereoSGBM = cv::StereoSGBM::create(0, 14*16, 3, 0, 10000, 72, 2, 1, 14, 1, 1);

	stereoSGBM->compute(src0, src1, disparity);

	return 0;
}
```

**Comment by alalek** [comment]
> The size of the input images affects this behaviour. It seems that compute() works fine when its memory consumption stays below 2 GiB.

I can confirm [this](https://github.com/opencv/opencv/blob/3.2.0/modules/calib3d/src/stereosgbm.cpp#L356):
- totalBufSize = 2487343440
- CSBufSize*2*sizeof(CostType) = 2471486976
- CSBufSize = 617871744
- costBufSize = 355712
- D = 224 (14*16)

**Comment by dmarnel** [comment]
This still crashes. I used two 1440 x 1920 images and the compute call crashes with no explanation. I then resized the images by half and it no longer crashed.
