### ISSUE TITLE
import cv2 doesn't work for Python 3 after successfully installing OpenCV 3.2.0 

### ISSUE THREAD

**Issue by monajalal** [opencv/opencv#8039]
So I have successfully installed OpenCV 3.2.0 from source on Ubuntu 14.04 and I get this error:

```
(cv2) mona@pascal:~/computer_vision/opencv-3.2.0/build$  /usr/local/bin/opencv_version
3.2.0
(cv2) mona@pascal:~/computer_vision/opencv-3.2.0/build$ python 
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
>>> import cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv'
```
What should I have done after sudo make install step that I might have missed?

Unfortunately there's no cv2 here as well:

```
mona@pascal:~/computer_vision/opencv-3.2.0/build$ ls /usr/local/lib/python3.4/dist-packages/
clonevirtualenv.py          numpy                        protobuf-3.1.0.post1.dist-info        stevedore                              virtualenvwrapper
django                      numpy-1.12.0.egg-info        protobuf-3.1.0.post1-py2.7-nspkg.pth  stevedore-1.20.0.dist-info             virtualenvwrapper-4.7.2-py3.4.egg-info
Django-1.10.5.dist-info     olefile                      __pycache__                           tensorflow                             virtualenvwrapper-4.7.2-py3.4-nspkg.pth
easy_install.py             olefile-0.44-py3.4.egg-info  PyYAML-3.12-py3.4.egg-info            tensorflow_gpu-0.12.1.dist-info        wheel
external                    OleFileIO_PL.py              scipy                                 theano                                 wheel-0.29.0.dist-info
google                      pbr                          scipy-0.18.1-py3.4.egg-info           Theano-0.8.2-py3.4.egg-info            yaml
image                       pbr-1.10.0.dist-info         setuptools                            virtualenv-15.1.0.dist-info
image-1.5.5-py3.4.egg-info  PIL                          setuptools-33.1.1.dist-info           virtualenv_clone-0.2.6-py3.4.egg-info
keras                       Pillow-4.0.0-py3.4.egg-info  six-1.10.0.dist-info                  virtualenv.py
Keras-1.2.0-py3.4.egg-info  pkg_resources                six.py 
```

Please suggest fixes. How should I get it work for Python3 (Python 3.4.3)?

**Comment by alalek** [comment]
More details are required:
- CMake stdout (from clean build)
- `make install` stdout about Python (installation lines only, so run it after "make")
- output of "import sys; print(sys.path)" from Python
- files from build folder: CMakeCache.txt and CMakeVars.txt (as attachment or use "grep" for "PYTHON")

**Comment by sumedhaagarwal** [comment]
Try installing from the following link:
http://docs.opencv.org/3.0-beta/doc/tutorials/introduction/linux_install/linux_install.html 
It worked for me, hope the same for you!

**Comment by chrizandr** [comment]
Try https://help.ubuntu.com/community/OpenCV . 
The tutorial is old but the build instructions are still relevant. You may have to specify the cmake parameters you used during the build for anyone to be able to help you. Also make sure you installed all the needed dependencies before installing.

**Comment by StevenPuttemans** [comment]
@monajalal I think I found the issue why it is not working

Looking at the output of the configure step of my system, most recent OpenCV 3.2 I can read

```
  Python 2:
    Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
    numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)
    packages path:               lib/python2.7/dist-packages

  Python 3:
    Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)

  Python (for build):            /usr/bin/python2.7
```

This allows me to do

```
spu@TOBCAT:~$ python2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 
```

but it does not allow me to do

```
spu@TOBCAT:~$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
```

I am guessing it has something to do with the line ` Python (for build):            /usr/bin/python2.7` which indicates that Python2.7 is selected for build, even if Python 3 is being detected and on my system. I guess there is somewhere a symbolic link that points your cv2 package to the 2.7 version, rather then the 3 version of Python. I will take a closer look and get back!

**Comment by StevenPuttemans** [comment]
Okay so digging deeper it seems you need to make sure all parts for python 3 are correctly on your system. I had to do an extra `sudo apt-get install python3.4-dev python3-numpy` and then run the build again which ends me up with

```
  Python 2:
    Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
    numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)
    packages path:               lib/python2.7/dist-packages

  Python 3:
    Interpreter:                 /usr/bin/python3.4 (ver 3.4.3)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.4m.so (ver 3.4.3)
    numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.8.2)
    packages path:               lib/python3.4/dist-packages
```

inside the cmake-gui and then rebuild everything. During build you then get somewhere at the end

```
Scanning dependencies of target opencv_python3
Scanning dependencies of target opencv_python2
[100%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
[100%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
```

Once all builds are complete I run a `sudo make install` and then I have access to both python2 and python3 cv2 bindings.

```
spu@TOBCAT:~$ python2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> exit()
spu@TOBCAT:~$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> exit()
```

So as suggested ensure your dependencies are all correct!

**Comment by PkLab** [comment]
sorry but right package  should be `python3-dev` ... it will automatically selects 3.4, 3.5, 3.x

**Comment by quocanh261997** [comment]
@StevenPuttemans, can you copy the 'cmake' execution line for me? I've install python3 like you've said but my cmake path always choose python 2. Thanks man.

**Comment by namascar** [comment]
@quocanh261997, 
You can add these two items to the cmake line
-D PYTHON_EXECUTABLE=/usr/bin/python3.4
-D PYTHON3_NUMPY_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include

**Comment by men190** [comment]
https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh

funciona al 100% 
![imagen](https://user-images.githubusercontent.com/17066798/36577057-cce6334a-1822-11e8-9c6a-98022c1eb13b.png)

**Comment by thedapperlabel** [comment]
Would recommend `-D PYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3` over `-D PYTHON_EXECUTABLE=/usr/bin/python3`

**Comment by yiakwy** [comment]
@thedapperlabel @StevenPuttemans @monajalal @alalek   Most of the answers and articles about this is outdated and wrong, which leading to missing of cv.cpython_x86-linux-gnu.so in that the CmakeLists.txt was not well studied.

The correct way to install cmake bundled with python from source is:

```bash
# see https://www.learnopencv.com/install-opencv-4-on-ubuntu-18-04/ with         
# attention that config for python3 is incomplete. I have fixed it by reading    
# CMakeLists.txt carefully                                                       
args=(                                                                           
"-D CMAKE_BUILD_TYPE=RELEASE"                                                    
"-D CMAKE_INSTALL_PREFIX=/usr/local"                                             
"-D ENABLE_FAST_MATH=ON"                                                         
"-D INSTALL_C_EXAMPLES=ON"                                                       
"-D INSTALL_PYTHON_EXAMPLES=ON"                                                  
"-D OPENCV_GENERATE_PKGCONFIG=ON"                                                
"-D OPENCV_ENABLE_NONFREE=ON"                                                    
"-D OPENCV_EXTRA_MODULES_PATH=${VENDOR_ROOT}/opencv_contrib/modules"             
"-D WITH_OPENGL=ON"                                                              
# PYTHON 3 BUNDLE SUPPORT       
"-D BUILD_opencv_python3=ON"                                                     
"-D PYTHON_EXECUTABLE=$(which python)"                                           
'-D PYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import              
get_python_inc; print(get_python_inc())")'                                       
'-D PYTHON3_LIBRARIES=$(python -c "from distutils.sysconfig import               
get_python_lib; print(get_python_lib())")'                                       
'-D PYTHON3_NUMPY_INCLUDE_DIRS=$(python -c "import numpy as                      
np;print(np.get_include())")'                                                    
'-D BUILD_EXAMPLES=ON'                                                           
)                                                                                
                                                                                 
cmake .. ${args} -- -j $num_cores                                                
                                                                                 
# check installation                                                             
pkg-config --modversions opencv4   
```

**Comment by mattengl2** [comment]
what would be the windows solution for this? I installed opencv fine and built in in VS but having this problem as well

**Comment by krisstern** [comment]
I used `conda` for the virtual environment and had to sim-link the `cv2` I have installed at `/usr/local/lib/python3.9/site-packages/cv2` to my virtual environment at `~/miniconda3/envs/py3cv4/lib/python3.9/site-packages/cv2` on my Ubuntu 20.04 workstation with the command

```
ln -s /usr/local/lib/python3.9/site-packages/cv2 ~/miniconda3/envs/py3cv4/lib/python3.9/site-packages/cv2
```
It would be good to have a feature to add a config setting to target the install location for Python separately, as Python is usually managed in a virtual environment such as Miniconda / Anaconda.

**Comment by alalek** [comment]
> It would be good to have a feature to add a config setting to target the install location for Python separately, as Python is usually managed in a virtual environment such as Miniconda / Anaconda.

This should work from the box.
You just need to activate virtual env **BEFORE** calling CMake (ensure that you have clean build directory or clean CMake cache from previous runs).
