### ISSUE TITLE
using Mat, each valid data followed by three zeros

### ISSUE THREAD

**Issue by ucsdxiaoyuzhou** [opencv/opencv#8041]
##### System information (version)

- OpenCV => :3.2
- Operating System / Platform => :OSX
- Compiler => :Qt

##### Detailed description

I am trying to write a NCC to produce the disparity of two rectified images.
I compute the distance between two point and store into a Mat variable. 
` disparity.at<int>(row,col) = abs(maxPoint.x - col);`
and display it.

However, the displayed picture is weird that each column is followed by a board black strip, and the result seems to be stretched, and only displayed left forth of the entire picture, as shown below:
![screen shot 2017-01-19 at 00 35 54](https://cloud.githubusercontent.com/assets/23324604/22099310/ae163286-dddf-11e6-9fcf-3d7860d13155.png)

the original picture is:
![left](https://cloud.githubusercontent.com/assets/23324604/22099543/9c33e8aa-dde0-11e6-8316-8e540bcd72e4.png)

I checked my data by printing them out after each iteration over a row:
` cout <<"current row = " << row <<"  disp = "<< disparity.at<int>(row, 13)<< disparity.at<int>(row, 14)<< disparity.at<int>(row, 15)<<endl;`
the data seems to be good.

but if I print my data in another way:
`cout << disparity;`
my data becomes something like:
x1, 0, 0, 0, x2, 0, 0, 0, x3, 0, 0,... which I think is the reason that causes black strips. 

I set all my data format as "int", and I initialized my "disparity" matrix as:
`  Mat disparity = Mat::zeros(leftHeight, leftWidth, CV_8UC1);`.

Thus, I am wondering what causes this problem? is the data format? or something else. I am really confused, and I really appreciate your guys' help!!!

**Comment by alalek** [comment]
> disparity.at<int>

There is forced "int" type. But

> CV_8UC1

Expects "uchar" datatype.

BTW, It is useful to use "Debug" builds to run more checks.
