### ISSUE TITLE
Building world module disables precompiled headers

### ISSUE THREAD

**Issue by darkdragon-001** [opencv/opencv#8046]
When I set the option `BUILD_opencv_world` to `ON`, precompiled headers are disabled as seen in the output `C/C++: Precompiled headers: NO`.

System: 
- OpenCV 3.2.0-dev
- Visual Studio 2015 Express
- Windows 7 x64

**Comment by alalek** [comment]
There are a lot of precomp.hpp files, so It is not possible to use one of them for precompiled bootstrap.

**Comment by darkdragon-001** [comment]
This issue is linked to opencv/opencv_contrib#810. When I enable world module **before** adding extra modules, it appears to me that some CMake flag is set and therefore needed files are not generated/copied.

**Comment by alalek** [comment]
@darkdragon-001 There is a good practice to always run CMake from scratch (clean build directory), especially in case of configuration options changes. There are many ways to break it without regular cleanup.
