### ISSUE TITLE
same code of OPENCV  on the two platforms output different results

### ISSUE THREAD

**Issue by bboalimoe** [opencv/opencv#8047]
##### System information (version)

- OpenCV => :grey_question: 3.1 
- Operating System / Platform => :grey_question:  Ubuntu 14.04 LTS 64 Bit  and Mac OSX 10.12.0+ 
- Compiler => :grey_question: G++

##### Detailed description

The same code of OPENCV  on the two platforms mentioned above outputs different results.
Is this due to the float point operation difference？ 

Thanks！

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by bboalimoe** [comment]
are these  normal circumstances？
