### ISSUE TITLE
buildIndex() of LshIndex is not working

### ISSUE THREAD

**Issue by cliassh** [opencv/opencv#8055]
In the flann library, buildIndex() create tables by calling the constructor of lsh_table:
table = lsh::LshTable<ElementType>(feature_size_, key_size_);

however, this constructor has not been implemented yet:
LshTable(unsigned int feature_size, unsigned int key_size)
    {
        (void)feature_size;
        (void)key_size;
        std::cerr << "LSH is not implemented for that type" << std::endl;
        assert(0);
    }
it just throws an exception.

Can anyone help with this problem?

**Comment by alalek** [comment]
You need [this](https://github.com/opencv/opencv/blob/3.2.0/modules/flann/include/opencv2/flann/lsh_table.h#L344) specialization. Support for other types is not implemented.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
