### ISSUE TITLE
Implementing the auto correlation function

### ISSUE THREAD

**Issue by bottiger** [opencv/opencv#8056]
I have often needed cross correlation/auto correlation function in openCV. [Matlab/Octave has a nice implementation called ``xcorr``.](https://se.mathworks.com/help/signal/ref/xcorr.html)

I know OpenCV has the ``matchTemplate`` function but it can not be used for calculating the autocorrelation of a function. ``matchTemplate`` expects a large image and a small(er) patch, and if the image and patch is the same size it will just return a number - not a function. I am also not sure a function called ``matchTemplate`` would be the best location for a potential autocorrelation function implementation.

I do have my own implementation of xcorr. Would it be possible to have it merged into opencv? I have read all your docs about contributing, but I am unsure of when/how you add new API's?

**Comment by LaurentBerger** [comment]
You can use [Filter2d](http://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga27c049795ce870216ddfb366086b5a04)

**Comment by bottiger** [comment]
@LaurentBerger Of course. I'll test it out tomorrow.

**Comment by lgmventura** [comment]
Any further advance on this topic? Bottiger, could you share your own implementation of xcorr for OpenCV?

**Comment by lgmventura** [comment]
Any further advance on this topic? Böttiger, could you please share your own implementation of xcorr for OpenCV?

**Comment by LaurentBerger** [comment]
@lgmventura may be you should read [wikipedia ](https://en.wikipedia.org/wiki/Cross-correlation): 
The cross-correlation of functions f(t) and g(t) are equivalent to the convolution of f*(−t) and g(t). That is:
![image](https://user-images.githubusercontent.com/3591626/45341356-a6a19b00-b59a-11e8-92a1-fce7503219f7.png)
