### ISSUE TITLE
I cannot find Matlab when I build opencv 3.2

### ISSUE THREAD

**Issue by yxftju** [opencv/opencv#8059]
I tried to compile opencv 3.2.0 on ubuntu ，I install Matlab2016 on /opt   but when I tried to build opencv 3.2 it shows that Matlab not found or implicity disable  I don‘t know why.Even though I manually set the dir about Matlab, I could not build it with Matlab .Can any body solve this problem?

**Comment by mshabunin** [comment]
`matlab` module is in the [opencv_contrib](https://github.com/opencv/opencv_contrib/tree/master/modules/matlab) repository and all related issues should be filed there. But first, please try to follow steps described in the [README.md](https://github.com/opencv/opencv_contrib/blob/master/modules/matlab/README.md) in the `matlab` module folder or ask other users on [the forum](http://answers.opencv.org).
