### ISSUE TITLE
how to compile opencv_contrib xfeatures2d 

### ISSUE THREAD

**Issue by sadegh01** [opencv/opencv#8063]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

which version of opencv_conrtib is compatble with opencv3.2.0. I tested opencv_contrib 3.2 and 3.2 -rc and 3.1 and 3.0 I got different errors from Cpp files lke "/xfeatures2d/src/sift.cpp:340:5: error: ‘hal’ has not been declared"
I use  -D OPENCV_EXTRA_MODULES_PATH=../modules/opencv_contrib-3.0.0/modules flag also
would you please help me t solve this.

**Comment by alalek** [comment]
> 3.2.0
> opencv_contrib-3.0.0/modules

Versions must be synchronized.

Sorry, we have a lack of time to provide support for build related questions on custom systems (it wastes a lot of time without significant effort to OpenCV community).
On official supported systems [all works fine](http://pullrequest.opencv.org/buildbot/builders/master-contrib_noOCL-lin64) (Ubuntu 14.04).
You need to investigate problem yourself on your system.
