### ISSUE TITLE
Dead link on opencv python tutorial documentation.

### ISSUE THREAD

**Issue by robrant** [opencv/opencv#8069]
**Problem**
A link to Property ID listing page on the opencv python tutorial documentation page is dead. 

**Documentation page:**
http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html

**Passage of text:**
> You can also access some of the features of this video using cap.get(propId) method where propId is a number from 0 to 18. Each number denotes a property of the video (if it is applicable to that video) and full details can be seen here: **Property Identifier**. Some of these values can be modified using cap.set(propId, value). Value is the new value you want.

**The error:**
```
Not Found
The requested URL /2.4/modules/highgui/doc/reading_and_writing_video.html was not found on this server.
```

**Comment by alalek** [comment]
> 3.0-beta

It is too late to report issues for this version, it is not supported anymore.
