### ISSUE TITLE
Use GenerateExportHeader module from cmake

### ISSUE THREAD

**Issue by mshabunin** [opencv/opencv#8070]
##### Detailed description

Consider using [GenerateExportHeader](https://cmake.org/cmake/help/v3.7/module/GenerateExportHeader.html) cmake module to handle compiler visibility flags, export and deprecate definitions. Extensive testing of dynamic and static builds is needed.

**Comment by paroj** [comment]
additional macros defined by CMake:
* CV_NO_DEPRECATED - eclude deprecated symbols from build
* CV_DEPRECATED_EXPORT - deprecated and exported symbols
* CV_NO_EXPORT - explicitly mark symbols private

**Comment by mshabunin** [comment]
We decided to use our own definitions for more precise control instead of cmake module: #8198
