### ISSUE TITLE
(Python) CV_32F as input in BackgroundSubtractorMOG2 returns zero result

### ISSUE THREAD

**Issue by VasLem** [opencv/opencv#8075]
##### System information (version)

- OpenCV =>3.1.0-dev
- Operating System / Platform =>Ubuntu 16.04
- Compiler => Python 2.7

##### Detailed description

As the titles suggests, while BackgroundSubtractrorMOG2.apply() works normally for CV_8U images, there is wrong output if I try to input CV_32F images. 

##### Steps to reproduce

From the following example:

```
cv2.ocl.setUseOpenCL(False)
mog2_float = cv2.createBackgroundSubtractorMOG2()
mog2_uint = cv2.createBackgroundSubtractorMOG2()
for c in range(10):
    a=np.random.randint(12000, size=(1000, 1000))
    b_float = mog2_float.apply((a/12000.0).astype(np.float32))
    b_uint = mog2_uint.apply(((a/12000.0)*256).astype(np.uint8))
    print 'float', b_float.shape, b_float.sum()
    print 'uint', b_uint.shape, b_uint.sum()
```
I get:
float (1000, 1000) 127011136
uint (1000, 1000) 127514176
float (1000, 1000) 0
uint (1000, 1000) 113003481
float (1000, 1000) 0
uint (1000, 1000) 100098782
float (1000, 1000) 0
uint (1000, 1000) 88461161
float (1000, 1000) 0
uint (1000, 1000) 83518379
float (1000, 1000) 0
uint (1000, 1000) 89134189
float (1000, 1000) 0
uint (1000, 1000) 72871915
float (1000, 1000) 0
uint (1000, 1000) 64383896
float (1000, 1000) 0
uint (1000, 1000) 59804725
float (1000, 1000) 0
uint (1000, 1000) 57262668

**Comment by sovrasov** [comment]
MOG always converts input into `32F` without any scaling:
```
if( src->depth() != CV_32F )
  src->row(y).convertTo(Mat(1, ncols, CV_32FC(nchannels), (void*)data), CV_32F);
else
  data = src->ptr<float>(y);
```
If you will scale the float image to [0, 256] the results will be similar:

```
float (10, 10) 12700
uint (10, 10) 12700
float (10, 10) 10795
uint (10, 10) 10922
float (10, 10) 10795
uint (10, 10) 10923
float (10, 10) 8636
uint (10, 10) 8763
float (10, 10) 8640
uint (10, 10) 8640
float (10, 10) 7757
uint (10, 10) 7630
float (10, 10) 8010
uint (10, 10) 8138
float (10, 10) 7114
uint (10, 10) 7241
float (10, 10) 5080
uint (10, 10) 5335
float (10, 10) 5208
uint (10, 10) 5336
```
