### ISSUE TITLE
Compile error in corner.cpp: ‘_mm256_setr_m128’ was not declared in this scope

### ISSUE THREAD

**Issue by bermond** [opencv/opencv#8079]
##### System information (version)
- OpenCV => git master (currently at 3.2.0.r103.g74defefd6)
- Operating System / Platform => Arch Linux 64-bit
- Compiler => gcc 6.3.1

##### Detailed description
I'm getting the following compile error when trying to build OpenCV version git master:
```
/home/user/abs/opencv-noffmpeg-git/src/opencv-noffmpeg-git/modules/imgproc/src/corner.cpp: In function ‘void cv::store_interleave(float*, const __m256&, const __m256&, const __m256&)’:
/home/user/abs/opencv-noffmpeg-git/src/opencv-noffmpeg-git/modules/imgproc/src/corner.cpp:116:86: error: ‘_mm256_setr_m128’ was not declared in this scope
     _mm256_storeu_ps(ptr, _mm256_setr_m128(_mm_castsi128_ps(a0), _mm_castsi128_ps(b0)));
                                                                                      ^
```

This issue seems to be caused by the recent git commit aa5caf83f6443a4581b1d52d23d581e7fee6f919.

##### Steps to reproduce
Attached.
Complete output also provided.

[opencv-steps.txt](https://github.com/opencv/opencv/files/732465/opencv-steps.txt)
[opencv-output.txt](https://github.com/opencv/opencv/files/732466/opencv-output.txt)

**Comment by alalek** [comment]
Confirmed with `ENABLE_AVX=ON` CMake option.

**Comment by alalek** [comment]
@bermond Could you try this fix: #8080?

**Comment by bermond** [comment]
@alalek 
I can confirm that pull request #8080 solves it.
OpenCV git master is building perfectly by applying this patch.
Thank you for the support!

**Comment by SarthakJShetty** [comment]
Apologies for bringing this up again, but I ran into the same issue while running ```make``` on my work PC. I solved it by updating the [Eigen](https://gitlab.com/libeigen/eigen) library. Previously had 3.2.92. Clone the Eigen library, ```cd``` into it and create a ```build```  folder. ```cmake ../eigen``` followed by ```sudo make install```.
Thanks to the folks here for the pointers.
