### ISSUE TITLE
Rect::area() and Size::area() may overflow too easily

### ISSUE THREAD

**Issue by reunanen** [opencv/opencv#8093]
Just spent some 10 hours debugging a critical issue in an application I wrote. There was no crash or anything – only wrong behavior, sometimes.

Had in the code something like this:

```.cpp
cv::Rect rect = ...
if (rect.area() > 0) {
    ...
}
```

Turns out that the reason for the wrong behavior was that the product of `width` and `height` [here](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1734) overflowed the 32-bit result integer. So both the width and the height were strictly positive, yet the return value was negative and therefore my code didn't enter the block of code it was expected to enter, causing further down the road another problem that took a long time to trace back to here.

I think at a bare minimum, there could be a `CV_Assert` (or something) that would be triggered if the product doesn't fit in the return value. Would have saved me hours of time.

A better solution I guess would be to change the output type. But given the way the class is currently templated, I am not sure what to suggest – at least not right after my long debugging session today. Maybe, if no-one proposes a fix, I'll create some PR at some point.

In addition to [Rect_<_Tp>::area()](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1732), a similar fix, if any, is probably needed for [Size_<_Tp>::area()](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1593) also.

**Workaround**

I changed my code to look like this:

```.cpp
cv::Rect rect = ...
if (rect.width > 0 && rect.height > 0) {
    ...
}
```

**Comment by alalek** [comment]
IMHO, You should add and use `.empty()` method instead of playing with return type.

**Comment by reunanen** [comment]
@alalek Ok, fair enough – but what if I wanted to do an `if (rect.area() > 100) { ... }` instead? Or really measure the area? I think it should at least assert, instead of failing silently.

**Comment by alalek** [comment]
This is default behavior for integer overflows, so it can't be handled efficiently. Probably it is C++ developer responsibility to track possible overflows and wrote tests.
I believe, assert can be added in this form (for debug builds only):
```
CV_DbgAssert(...);
```

**Comment by kinchungwong** [comment]
I have several thoughts, which are only tangential to this issue. *These thoughts are not directed toward the PR*. Hopefully this comment doesn't side-track this discussion. It is worthwhile to fix the obvious problems in source code first, and then deal with deeper issues later.

 1. Would OpenCV benefit from using [Safe Integer operations](https://www.us-cert.gov/bsi/articles/knowledge/coding-practices/safe-integer-operations) in various places that involve memory size calculations (as opposed to geometric calculations)? Should these macros be defined in a central place in OpenCV?
 1. For OpenCV types that are used in both geometric calculations and memory size calculations (such as `cv::Rect::area()`, should the runtime check be performed in release builds as well? 
 1. Should the runtime check be performed in the multi-purpose functions (`cv::Rect::area()`), or in memory-allocating functions (which only catches negative signed integer values, and has the danger of not being able to catch certain types of overflows)?
 1. Should we prevent the allocation of excessively large matrices (when `cv::Mat::size().area()` exceeds `INT_MAX`) ? Considering that integer multiplication overflows can sometimes produce a positive but wrong result, what other checks would need to be performed before a matrix is allocated?

**Comment by reunanen** [comment]
@kinchungwong : Thank you for your input! I have only one thing to say: whatever you do, don't do option 4 above! I, for one, am actively working with software where I need `cv::Mat`s in the order of 100k x 100k, and even more. (Yes, such images do indeed exist – in some domains they are even the norm, and no-one calls them "excessively large".)
Today, OpenCV is generally usable with images of this caliber (although there have been issues, e.g. #5473 / #7458), so doing option 4 above would be really bad at least for me (and I don't think I'm alone).

**Comment by tompollok** [comment]
Why only DbgAssert? Is .area() used that often that it would significantly lower the ocv perfomance?

**Comment by reunanen** [comment]
@tompollok : Yes, I guess that's what @alalek [meant](https://github.com/opencv/opencv/issues/8093#issuecomment-275907423). For me it doesn't make a difference – I'm not going to call it that often, but I'm also ok with having the assertion in debug builds only.

**Comment by kinchungwong** [comment]
I have one suggestion, but I suspect there will be disagreements about this. (Integer overflow is not new - every C and C++ open-source project has fought over integer overflows before.)

To the 32-bit `cv::Rect::area()` and `cv::Size::area()`, keep their return type as 32-bit signed integer, and add the `CV_DbgAssert` as suggested.

Also, `cv::Mat::total()` will also need the `CV_DbgAssert`.

Add new methods `cv::Rect::area64()` and `cv::Size::area64()`, where the return types are mandatory 64-bit. I would suggest not using architecture-dependent sizes such as `size_t`, because the need to defend against overflow also applies to 32-bit architectures.

The naming can be discussed. It might be `area64`, `areaLong`, `areaLarge`, or something else.

----

@reunanen Thanks for your input about large matrices! I have encountered similar issues with large matrices with `cv::remap`, and I implemented a tiling mechanism to deal with it. <br>Discussion: https://github.com/opencv/opencv/issues/7544 <br>Sample code: https://gist.github.com/kinchungwong/141bfa2d996cb5ae8f42 

Personally, I think OpenCV will eventually provide some sort of tiling support (a different type of matrix class), but until that day comes, each programmer will do something on their own.

**Comment by reunanen** [comment]
@kinchungwong Yep, basically I too anyway tile all my large matrices, as 10+ GB chunks of contiguous memory may not always be available.
However, I was using `cv::Rect` for some bookkeeping – I didn't think this would be unsafe, as `cv::Rect` does not consume more memory, the larger the rectangle gets. :) ... And that's when and why I stumbled upon this issue.
