### ISSUE TITLE
Java Closeable implementation for all OpenCV classes

### ISSUE THREAD

**Issue by virl** [opencv/opencv#8095]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => macOS Sierra 10.12.3 (16D32)
- Compiler => JDK8, bindings from https://github.com/openpnp/opencv/issues/16

##### Detailed description

Currently native OpenCV objects are freed (deleted) in finalize() method on GC sweep.

But in reality (during intensive use) there happens the situation when GC haven't finalized these objects (because there is still plenty of Java Heap), but OpenCV crashes due to exhaustion of native resources.

So please implement Closeable interface (with close() method) for each OpenCV class that have Java bindings.

The following:
```
System.gc();
System.runFinalization();
```
is NOT workaround, because it does not guarantee finalization running.

Properly implemented close() method is needed, that can be called several times on same object.

**Comment by alalek** [comment]
There is "release()" method for many OpenCV classes. Does it work for you?
