### ISSUE TITLE
v4l  set white_balance_temperature_auto

### ISSUE THREAD

**Issue by arpu** [opencv/opencv#8096]
is it possible to set 
 white_balance_temperature_auto
and white_balance_temperature

                 brightness (int)    : min=-15 max=15 step=1 default=0 value=0
                       contrast (int)    : min=0 max=60 step=1 default=10 value=10
                     saturation (int)    : min=0 max=98 step=1 default=16 value=16
                  white_balance_temperature_auto (bool)   : default=0 value=1
                          gamma (int)    : min=16 max=125 step=1 default=40 value=40
                           gain (int)    : min=0 max=100 step=1 default=0 value=1
      white_balance_temperature (int)    : min=11 max=50 step=1 default=17 value=17 flags=inactive
                      sharpness (int)    : min=1 max=7 step=1 default=1 value=1
                  exposure_auto (menu)   : min=0 max=3 default=1 value=1
              exposure_absolute (int)    : min=0 max=10000 step=1 default=312 value=600
                  zoom_absolute (int)    : min=100 max=800 step=1 default=100 value=100

@paroj

**Comment by paroj** [comment]
[no](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_v4l.cpp#L1589-L1605)

**Comment by arpu** [comment]
any idea how i can implement this?
