### ISSUE TITLE
warpPerspective with BORDER_TRANSPARENT doesn't perform interpolation on the border pixels

### ISSUE THREAD

**Issue by martinakos** [opencv/opencv#8101]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 14 2015 Win64

##### Detailed description

I have tried all the available interpolations and the outlier pixels in the border are not interpolated.
You can see an example of what I mean in [this](http://stackoverflow.com/questions/41898989/insert-an-image-patch-into-another-image-at-a-subpixel-location) stackoverflow question, and in [this](http://answers.opencv.org/question/23909/warpperspective-with-border_transparent-gives-aliasing-stairs/) other question. Interpolation works well if the borderMode is not BORDER_TRANSPARENT.

##### Steps to reproduce
Run this in python to see how the border of the inserted patch doesn't interpolate with the source image.

```
import numpy as np
import matplotlib.pyplot as plt

def insert_patch_subpixel(im, patch, p):
    """
    im: numpy array with source image.
    patch: numpy array with patch to be inserted into the source image
    p: tuple with the center of the position (can be float) where the patch is to be inserted.
    """
    ths = patch.shape[0]/2
    xpmin = p[0] - ths
    ypmin = p[1] - ths
    Ho = np.array([[1, 0, xpmin],
                   [0, 1, ypmin],
                   [0, 0,     1]], dtype=float)

    h,w = im.shape
    im2 = cv2.warpPerspective(patch, Ho, (w,h), dst=im,
                        flags=cv2.INTER_LINEAR,
                        borderMode=cv2.BORDER_TRANSPARENT)
    return im2

if __name__ == "__main__":
    x,y = np.mgrid[0:10:1, 0:10:1]
    #im =(x+y).astype('uint8')*5
    im = np.ones((10,10), dtype='uint8')*30
    patch = np.ones((4,4), dtype='uint8')*100

    p=(5.5,5.5)
    im = insert_patch_subpixel(im, patch, p)

    plt.gray()
    plt.imshow(im, interpolation='none',  extent = (0, 10, 10, 0))
    ax=plt.gca()
    ax.grid(color='r', linestyle='-', linewidth=1)
    ax.set_xticks(np.arange(0, 10, 1));
    ax.set_yticks(np.arange(0, 10, 1));

    def format_coord(x, y):
        col = int(x)
        row = int(y)
        z = im[row,col]
        return 'x=%1.4f, y=%1.4f %s'%(x, y, z)

    ax.format_coord = format_coord
    plt.show()
```

The result is:
![image](https://cloud.githubusercontent.com/assets/2371869/22405224/3bb9d020-e637-11e6-94fd-37f8417af0f3.png)

and it should be something like this:
![image](https://cloud.githubusercontent.com/assets/2371869/22405229/4d57f7c6-e637-11e6-9546-628b6ae5365f.png)

**Comment by martinakos** [comment]
I'm not sure why the label question (invalid) has been added to this. In the description I do refer to a stackoverflow question. However, I'm making a question, I'm telling that this is a bug.

**Comment by alalek** [comment]
Probably Python bindings has limited support for image ROIs and for image borders too (especially for mentioned `BORDER_TRANSPARENT`). Could you provide C++ based reproducer for this?

**Comment by r0l1** [comment]
Same problem here: https://answers.opencv.org/question/23909/warpperspective-with-border_transparent-gives-aliasing-stairs/

@alalek here is a sample code:

```cpp
#include <opencv2/opencv.hpp>

using namespace cv;

int main(int argc, char** argv) {
    Mat bg1(500, 500, CV_8UC3, cv::Scalar(0,0,255));
    Mat bg2 = bg1.clone();
    Mat fg(50, 50, CV_8UC3, cv::Scalar(255,255,255));

    Point2f src_pts[4] = { Point2f(0, 0), Point2f(50, 0), Point2f(50, 50), Point2f(0, 50)};
    Point2f dst_pts[4] = { Point2f(389, 0), Point2f(500, 250), Point2f(250, 500), Point2f(0, 250)};


    Mat trans = getPerspectiveTransform(src_pts, dst_pts);
    warpPerspective(fg, bg1, trans, bg1.size(), cv::INTER_CUBIC, cv::BORDER_TRANSPARENT);
    warpPerspective(fg, bg2, trans, bg2.size(), cv::INTER_CUBIC, cv::BORDER_CONSTANT, cv::Scalar(0,0,0,0));

    imshow("1", bg1);
    imshow("2", bg2);
    waitKey(0);

    return 0;
}

```

**Comment by alalek** [comment]
> BORDER_TRANSPARENT

Documentation says:

- remap, warpAffine
> When `borderMode=BORDER_TRANSPARENT`, it means that the pixels in the destination image that corresponds to the "outliers" in the source image are not modified by the function.

- intro:
> This means that the corresponding pixels in the destination image will not be modified at all.


---

This is very tricky case and you want something strange.

Need to properly define first:
- which pixels should be used - looks like you want to pick something from the destination(!) image
- how to calculate coefficients for interpolation

(play with some textured destination image if you are sure with your proposal)

---

So, I'm not sure that this mode is used properly and/or have a real purpose.
Perhaps users are looking for this pipeline:
- rgb => rgba
- warp with constant "zero" border
- blend with original background

**Comment by r0l1** [comment]
Thanks for the fast response and the clarification.

> Perhaps users are looking for this pipeline:
> - rgb => rgba
> -  warp with constant "zero" border
> -  blend with original background

I solved my task exactly as you described it. However I was concerned due to performance losses, due to all the extra steps required. 

> This is very tricky case and you want something strange.
> Need to properly define first:

I am transforming a rectangle with text into a bigger image. Quality is important and that's why I tried to improve the border with an anti-aliasing effect,,, 

Here is a complete sample with a fixed algorithm.

```cpp
#include <iostream>
#include <chrono>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace std::chrono;
using namespace cv;

void warpPerspectiveTransparent(const Mat& src, Mat& dst, const Mat trans) {
    // Use a transparent destination image for the warpPerspective transformation.
    cv::Mat overlay(dst.size(), CV_8UC4, cv::Scalar(0,0,0,0));

    // Convert the source image to a rgba image.
    cv::Mat srcBGRA(src.size(), CV_8UC4);
    cv::cvtColor(src, srcBGRA, cv::COLOR_BGR2BGRA);

    // Perspective transform operation using transform matrix.
    cv::warpPerspective(srcBGRA, overlay, trans, dst.size(), cv::INTER_CUBIC, cv::BORDER_CONSTANT, cv::Scalar(0,0,0,0));

    // Convert the destination image to a rgba image.
    cv::Mat dstBGRA(dst.size(), CV_8UC4);
    cv::cvtColor(dst, dstBGRA, cv::COLOR_BGR2BGRA);

    // Merge the destination image with the transparent image.
    for (int y = 0; y < dstBGRA.rows; ++y) {
        int fY = y;
        if (fY >= overlay.rows) {
            break;
        }
        for (int x = 0; x < dstBGRA.cols; ++x) {
            int fX = x;
            if (fX >= overlay.cols) {
                break;
            }
            double opacity = ((double)overlay.data[fY * overlay.step + fX * overlay.channels() + 3]) / 255;
            for (int c = 0; opacity > 0 && c < dstBGRA.channels(); ++c) {
                unsigned char overlayPx = overlay.data[fY * overlay.step + fX * overlay.channels() + c];
                unsigned char srcPx = dstBGRA.data[y * dstBGRA.step + x * dstBGRA.channels() + c];
                dstBGRA.data[y * dstBGRA.step + dstBGRA.channels() * x + c] = srcPx * (1. - opacity) + overlayPx * opacity;
            }
        }
    }

    // Finally set the destination image and remove the alpha layer.
    cv::cvtColor(dstBGRA, dst, cv::COLOR_BGRA2BGR);
}

int main(int argc, char** argv) {
    Mat bg1(500, 500, CV_8UC3, cv::Scalar(0,0,255));
    Mat bg2 = bg1.clone();
    Mat bg3 = bg1.clone();

    Mat fg(50, 50, CV_8UC3, cv::Scalar(255,255,255));
    putText(fg, "foo", Point(0, 35), 0, 1, Scalar(30,30,30), 1, cv::LINE_AA);

    Point2f src_pts[4] = { Point2f(0, 0), Point2f(50, 0), Point2f(50, 50), Point2f(0, 50)};
    Point2f dst_pts[4] = { Point2f(389, 0), Point2f(500, 250), Point2f(250, 500), Point2f(0, 250)};


    Mat trans = getPerspectiveTransform(src_pts, dst_pts);

    auto start = high_resolution_clock::now();
    warpPerspective(fg, bg1, trans, bg1.size(), cv::INTER_CUBIC, cv::BORDER_TRANSPARENT);
    cout << "1 took: " << duration_cast<microseconds>(high_resolution_clock::now() - start).count() << "ms" << endl;

    start = high_resolution_clock::now();
    warpPerspective(fg, bg2, trans, bg2.size(), cv::INTER_CUBIC, cv::BORDER_CONSTANT, cv::Scalar(0,0,0,0));
    cout << "2 took: " << duration_cast<microseconds>(high_resolution_clock::now() - start).count() << "ms" << endl;

    start = high_resolution_clock::now();
    warpPerspectiveTransparent(fg, bg3, trans);
    cout << "3 took: " << duration_cast<microseconds>(high_resolution_clock::now() - start).count() << "ms" << endl;

    imshow("1", bg1);
    imshow("2", bg2);
    imshow("3", bg3);
    waitKey(0);

    return 0;
}
```

Execution time:
```
1 took: 3820ms
2 took: 2223ms
3 took: 15804ms
```

![1](https://user-images.githubusercontent.com/10167163/76363820-1cb7c700-6324-11ea-8f81-dfc460bf3021.jpg)
![2](https://user-images.githubusercontent.com/10167163/76363822-1d505d80-6324-11ea-8c2f-a7560a7fd05a.jpg)
![3](https://user-images.githubusercontent.com/10167163/76363823-1de8f400-6324-11ea-9b0a-43c0ed178971.jpg)

**Comment by Mps24-7uk** [comment]
How to get the output edges same as the original image after wrapprespectuive transformation

**Comment by Mps24-7uk** [comment]
I'm kind of stuck on the same issue, the edges/borders are inconsistent. It has the black dotted line
