### ISSUE TITLE
Unable to use ximgproc's structured edge detection on iOS

### ISSUE THREAD

**Issue by Jaykob** [opencv/opencv#8106]
I'm unable to use the structured edge detection on iOS as there seems to be a bug when working with compressed files. The model provided with the ximgproc module is a .yml.gz file. A quick inspection of `persistence.cpp` showed that `USE_ZLIB`gets undefined on iOS at the very beginning of the file leading to the following error. The cmake logs show that zlib builds and gets linked into the iOS framework fine, though.

##### System information (version)

- OpenCV => current master
- Operating System / Platform => macOS 12.2.2 (host), iOS 10.2 (target)
- Compiler => clang (Xcode 8.2.1 default)

##### Detailed description

I'm getting the following error log in Xcode:
```
OpenCV Error: The function/feature is not implemented (There is no compressed file storage support in this configuration) in cvOpenFileStorage, file /Users/xyz/opencv-master/modules/core/src/persistence.cpp, line 4235
2017-01-31 11:17:47.500052 mytestproject[1226:473262] *** Terminating app due to uncaught exception '/Users/xyz/opencv-master/modules/core/src/persistence.cpp:4235: error: (-213) There is no compressed file storage support in this configuration in function cvOpenFileStorage
```

##### Steps to reproduce
The model file taken from the ximgproc module can be downloaded [here](https://www.dropbox.com/s/q78tbnkqatae16s/model.yml.gz?dl=0)

```cpp
            Mat img = imread("image.png");
            Mat imgFloat;
            img.convertTo(imgFloat, cv::DataType<float>::type, 1 / 255.0);
            Mat rfEdges(imgFloat.size(), imgFloat.type());

            String modelFile = "./model.yml.gz";
            cv::Ptr<cv::ximgproc::StructuredEdgeDetection> edgeDetector = cv::ximgproc::createStructuredEdgeDetection(modelFile);
            edgeDetector->detectEdges(imgFloat, rfEdges);
```

**Comment by mshabunin** [comment]
@Jaykob , can you try to enable ZLIB in the `persistence.cpp` and test you app? You can submit a pull request with your changes if it will work well.

**Comment by Jaykob** [comment]
Thanks, it worked! 
I have to clean up things before submitting a PR, will hopefully come back to it when I find some time.

**Comment by ysolovyov** [comment]
```
#ifdef __APPLE__
#  include "TargetConditionals.h"
#  if (defined TARGET_OS_IPHONE && TARGET_OS_IPHONE) || (defined TARGET_IPHONE_SIMULATOR && TARGET_IPHONE_SIMULATOR)
#    undef USE_ZLIB
#    define USE_ZLIB 0
     typedef void* gzFile;
#  endif
#endif
```

just need remove this block from ```persistence.cpp``` and everything works. I don't have access to make a pull request here, had same issue as ```Jacob```

**Comment by Jaykob** [comment]
Yes, that's also the workaround that I used ;-)
