### ISSUE TITLE
Support for gendef and dlltool

### ISSUE THREAD

**Issue by drakkan** [opencv/opencv#8110]
- OpenCV => 3.2.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I cross compiled opencv 3.2.0 using mingw-w64 6.3.1 for windows x86_64, 

If I try to cross compile a sample opencv app from linux using mingw it works fine

I need to use opencv dll from visual studio users too so I generated import libraries with a script such as this 

```
for dll in $(ls -U $DLL_PATH);
do
	gendef $DLL_PATH$dll
	x86_64-w64-mingw32-dlltool -d ${dll::-4}.def -l ${dll:3:-4}.lib -D $DLL_PATH
done
```

but if I try to compile an opencv app from visual studio I got link errors (undefined reference to several methods) . The same procedure to generate import libraries from mingw dll works fine with other dlls (for example gstreamer, glib ecc...). 

Obvioulsy If I build opencv with visual studio and I use the generated lib files I have no link errors.

Do you plan to make you dll work with gendef and dlltool?

**Comment by alalek** [comment]
No.

**Comment by mshabunin** [comment]
@drakkan , you can take a look at the #8198 , it adds 'dllimport' attribute to all exported functions when used by apps. Maybe it can help.
