### ISSUE TITLE
CAP_PROP_FRAME_WIDTH & CAP_PROP_FRAME_HEIGHT do NOT work...

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#8117]
Fail to set capture image size again...

##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04.1
- Compiler => GCC 5.4.0
- Camera => Logitech C920

##### Detailed description

fail to set the captured image size from 640*480 to 1920*1080 ...

##### Steps to reproduce

```
    if( (!capture.set(cv::CAP_PROP_FRAME_WIDTH, 1920)) ||
        (!capture.set(cv::CAP_PROP_FRAME_HEIGHT, 1080)) )
    {
        std::cerr << "Fail to set capture property width x height" << std::endl;
    }
```

Cheers
Pei

**Comment by alalek** [comment]
What is video backend used? V4L or libv4l?

**Comment by jiapei100** [comment]
@alalek  

I just have OpenCV rebuilt... still the same, namely: fail to set the image width and height after `capture.open(cameraId);`

In fact, when I configure opencv with cmake, I set both **WITH_LIBV4L** and **WITH_v4L** **ON** .

Seriously sad.... OpenCV is clearly NOT that good at streaming....


Cheers
Pei

**Comment by jiapei100** [comment]
@alalek 

Problem found... It seems:
```
    capture.set(cv::CAP_PROP_FRAME_WIDTH, 1920);
    capture.set(cv::CAP_PROP_FRAME_HEIGHT, 1080);
```
works for me... However, if I replaced it with the following piece of code,
```
    if( (!capture.set(cv::CAP_PROP_FRAME_WIDTH, 1920)) ||
        (!capture.set(cv::CAP_PROP_FRAME_HEIGHT, 1080)) )
    {
        **std::cerr << "Fail to set capture property width x height" << std::endl;**
    }
```
I will always have the **ERROR** message (in bold) printed :-(

That's weird....

Thank you @alalek ...

Cheers
