### ISSUE TITLE
OpenCV Manager on Google Play Store needs update to 3.2.0

### ISSUE THREAD

**Issue by JoeHowse** [opencv/opencv#8120]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Android

##### Detailed description

The version of [OpenCV Manager on Google Play Store](https://play.google.com/store/apps/details?id=org.opencv.engine) hasn't been updated since OpenCV 3.0.0.  However, the OpenCV Android SDK 3.2.0 release contains more recent builds of OpenCV Manager in the `apk` folder.  These updated builds should be published to Google Play Store so that people can more easily distribute OpenCV 3.2.0 (and 3.1.0) apps.

**Comment by davidmigloz** [comment]
The current apk available in Google Play is:

```
android:versionCode="3002"
android:versionName="3.00"
```

However, the latest apk distributed with the sdk is:

```
android:versionCode="3302"
android:versionName="3.30"
```

Could you update the Google Play version please? 
From the docs:

> Installation from Internet is the preferable way since **OpenCV team may publish updated versions of this packages on the Market**.

**Comment by JoeHowse** [comment]
This specific issue is obsolete, so am closing it, but #20491 is related. Loader code and docs need to be updated to reflect the fact that OpenCV Manager is discontinued.
