### ISSUE TITLE
FastLineDetector

### ISSUE THREAD

**Issue by fbernierpro** [opencv/opencv#8124]
##### System information (version)

- OpenCV => 3.20
- Operating System / Platform => Android
- Compiler => :grey_question:

##### Detailed description

Where is ximgproc fastLineDetector ?
I don't have it is Android SDK.

It is documented here : http://docs.opencv.org/3.2.0/df/d4c/classcv_1_1ximgproc_1_1FastLineDetector.html

And also mentioned in changeLog : 
https://github.com/opencv/opencv/wiki/ChangeLog
as Fast Line Detector (Jin Han Lee)

**Comment by alalek** [comment]
https://github.com/opencv/opencv_contrib

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
