### ISSUE TITLE
Integrating opencv 3.2.0 into OS X Xcode project via framework

### ISSUE THREAD

**Issue by atrbx5** [opencv/opencv#8126]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => osx El Capitan 10.11.6
- Compiler => xCode Version 8.2.1

##### Detailed description

Tried to integrate opencv 3.2.0 into OS X xCode project via framework. 

##### Steps to reproduce

Used osx/build_framework.py to get framework
then drop it inside my project and linking fails with 140 errors

`Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const", referenced from:
      _cvOpenFileStorage in opencv2(persistence.o)`

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
