### ISSUE TITLE
ld: library not found for -lharfbuzz - lib/libopencv_freetype.3.2.0.dylib Error 1

### ISSUE THREAD

**Issue by bluemuflon** [opencv/opencv#8129]
Hello everybody,
just got the following error message during 'make all' (with contrib; both with and without CUDA):

Scanning dependencies of target opencv_freetype
[ 59%] Building CXX object modules/freetype/CMakeFiles/opencv_freetype.dir/src/freetype.cpp.o
[ 59%] Linking CXX shared library ../../lib/libopencv_freetype.dylib
ld: library not found for -lharfbuzz
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_freetype.3.2.0.dylib] Error 1
make[1]: *** [modules/freetype/CMakeFiles/opencv_freetype.dir/all] Error 2
make: *** [all] Error 2

Since few days could not compile. Before 'git pull origin master' on feb 02 everything was ok.
Could you help me please?

##### System information
- OpenCV => master (updated on feb 04, 2017)
- Operating System / Platform => Mac OSX El Capitan 10.11.6; Nvidia CUDA driver version 8.0.53; Mac Pro (early 2008); NVIDIA GeForce 8800 GT 512 MB
- Compiler => Xcode 7.3 (7D175)

Could you help me please?

Reagards,

Brian

**Comment by alalek** [comment]
Try to disable freetype module via CMake option: `-D BUILD_opencv_freetype=OFF`.

**Comment by bluemuflon** [comment]
Thank you, Alalek. Unfortunately disabling freetype module still not work. Now the error message is:

Scanning dependencies of target opencv_text
[ 66%] Building CXX object modules/text/CMakeFiles/opencv_text.dir/src/erfilter.cpp.o
In file included from /Users/.../OpenCVsources/opencv-master/opencv_contrib/modules/text/src/erfilter.cpp:43:
/Users/.../OpenCVsources/opencv-master/opencv_contrib/modules/text/src/precomp.hpp:51:10: fatal error: 
      'tesseract/baseapi.h' file not found
#include <tesseract/baseapi.h>
         ^
1 error generated.
make[2]: *** [modules/text/CMakeFiles/opencv_text.dir/src/erfilter.cpp.o] Error 1
make[1]: *** [modules/text/CMakeFiles/opencv_text.dir/all] Error 2
make: *** [all] Error 2

Moreover a new warning appears:

/Users/.../OpenCVsources/opencv-master/opencv/modules/core/include/opencv2/core/mat.inl.hpp(3535): warning: integer conversion resulted in a change of sign

Until feb 02 everything was ok...

Any idea?

Thank you

**Comment by alalek** [comment]
precomp.hpp issues can be workarounded by `-D ENABLE_PRECOMPILED_HEADERS=OFF`

Unfortunately, it is hard to investigate build issues remotely due different environments, so there are workarounds only for these problems.

**Comment by bluemuflon** [comment]
Yet -D ENABLE_PRECOMPILED_HEADERS=OFF from my early post.

I guess some change in master or contrib on the last days of January made this mismatching during building process.

I will continue investigating.

Thanks!

**Comment by mshabunin** [comment]
@bluemuflon , did you try to make a clean build? Make sure your _opencv_ and _opnecv_contrib_ repositories are at the same point (tag 3.2.0 or latest commit on branch _master_).
