### ISSUE TITLE
Trouble while opencv compilation: modules/gpu/perf_precomp.hpp.gch/opencv_perf_gpu_Debug.gch: No such file or directory

### ISSUE THREAD

**Issue by meikuam** [opencv/opencv#8130]
##### System information (version)
- OpenCV => 2.4.13.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => MinGW492_32
- Qt => 5.6.2
- CMake => 3.7.2
##### Detailed description
I tried to compile lib using MinGW compiler from Qt
full traseback in file:
[log.txt](https://github.com/opencv/opencv/files/752513/log.txt)

It seems like the problem in the generated "build.make" file:
D:\Develop\Libs\opencv-2.4.13.2\build\modules\gpu\CMakeFiles\pch_Generate_opencv_perf_gpu.dir\build.make

Compilation fails at this strings of file:

`modules/gpu/perf_precomp.hpp.gch/opencv_perf_gpu_Debug.gch:
lib/libopencv_perf_gpu_pch_dephelpd.a
@$ctory D:/Develop/Libs/opencv-2.4.13.2/build/modules/gpu/perf_precomp.hpp.gch
	cd /d D:\Develop\Libs\opencv-2.4.13.2\build\modules\gpu && C:\Qt\Qt5.6.2\Tools\mingw492_32\bin\g++.exe -g (CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=D:\Develop\Libs\opencv-2.4.13.2\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating perf_precomp.hpp.gch/opencv_perf_gpu_Debug.gch"
	cd /d D:\Develop\Libs\opencv-2.4.13.2\build\modules\gpu && "C:\Program Files\CMake\bin\cmake.exe".......-x c++-header -o D:/Develop/Libs/opencv-2.4.13.2/build/modules/gpu/perf_precomp.hpp.gch/opencv_perf_gpu_Debug.gch D:/Develop/Libs/opencv-2.4.13.2/build/modules/gpu/perf_precomp.hpp`

For some reason path separator in "modulesgpu" works not properly.
If I copy "modules/gpu" directory to "modulesgpu", then compilation is completed without errors.

I tried with different CMake options like check "WITH_QT" flag to false. But compilation fails at the same place. But with other path like "modules\gu\perf_precomp.hpp.gch"

##### Steps to reproduce
1. Configure with CMake GUI using standard options, using this additional options:
Source code dir: D:/Develop/Libs/opencv-2.4.13.2
Bin files dir: D:/Develop/Libs/opencv-2.4.13.2/build
2. Run "mingw32-make" command from terminal;
3. Get this error log:
fatal error: can't create precompiled header D:/Develop/Libs/opencv-2.4.13.2/build/modulesgpu/perf_precomp.hpp.gch/opencv_perf_gpu_Debug.gch: No such file or directory

**Comment by alalek** [comment]
MinGW is not supported officially.
Try to disable precompiled headers (check for `ENABLE_PRECOMPILED_HEADERS` CMake flag)

**Comment by meikuam** [comment]
It looks like the problem was with MinGW compiler. I changed it to MinGW530_32, so that compilation passet without errors.
