### ISSUE TITLE
the performance is not improved when using GPU on android

### ISSUE THREAD

**Issue by shengxingdong** [opencv/opencv#8144]
I'm trying to use GPU to accelerate algorithm on android(Snapdragon 820 CPU), and I build opencv for android with OPENCL flag ON, the code like:

if (cv::ocl::haveOpenCL())
{
    LOGI("OpenCL IS avaiable ...");
    cv::UMat gpu_img;
    cv::Mat cpu_img;
    cpu_img = imread("/sdcard/stereo_image/640-480.jpg", 0);
    resize(cpu_img, cpu_img, Size(2560,1920));
    cpu_img.copyTo(gpu_img);

    clock_t s = clock();
    GaussianBlur(gpu_img, gpu_img,Size(3, 3), 1.5);
    GaussianBlur(gpu_img, gpu_img,Size(3, 3), 1.5);
    GaussianBlur(gpu_img, gpu_img,Size(3, 3), 1.5);
    GaussianBlur(gpu_img, gpu_img,Size(3, 3), 1.5);
            clock_t e = clock();
    }

the running time for GaussianBlur is not changed when I use UMat or Mat

**Comment by alalek** [comment]
Try to run OpenCV performance tests (with OCL_* prefix) on your Android device.

**Comment by shengxingdong** [comment]
@alalek I'm using opencv3.1.0, and I build it for android device by script in "/platforms/script" with BUILD_PERF_TESTS=ON and WITH_OPENCL=ON. 
there is no performance tests file generated with OCL_* prefix. 
Is there any other settings ?

**Comment by alalek** [comment]
> tests file

Files are the same.

To run tests it is better to use [this script](https://github.com/opencv/opencv/blob/master/modules/ts/misc/run.py) which uploads required libraries/test binaries on Android device. Also you need upload (adb push or similar) "opencv_extra/testdata" and specify device path via OPENCV_TEST_DATA_PATH env variable (check wiki page about OpenCV tests).
