### ISSUE TITLE
Cascade.detectMultiScale with multi-thread version

### ISSUE THREAD

**Issue by liuguiyangnwpu** [opencv/opencv#8147]
Dear author,

This is not for a bug report !!!
I want to know if there is a version about multi-thread version for detectMultiScale ?
Please show me the website or the code !

thx !

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

CPU-based implementation uses `parallel_for_` [here](https://github.com/opencv/opencv/blob/3.2.0/modules/objdetect/src/cascadedetect.cpp#L1345). Multi-threading backend (TBB/pthreads/etc) should be available/enabled to receive benefits of this.
