### ISSUE TITLE
FileStorage << cv::Matx not supported

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#8148]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

The FileStorage class does not support writing of cv::Matx objects.

##### Steps to reproduce

    #include <stdlib.h>
    #include <opencv2/core/core.hpp>
    void main(int argc, char **argv)
    {
        cv::FileStorage fs("dummy.yml", cv::FileStorage::MEMORY);
        fs << "a" << cv::Matx33f::eye();
    }

does not compile because of ``error C2665: 'cv::write' : none of the 10 overloads could convert all the argument types``:

    1>E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(1065): error C2665: 'cv::write' : none of the 10 overloads could convert all the argument types
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(974): could be 'void cv::write(cv::FileStorage &,const cv::String &,const cv::Range &)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(663): or       'void cv::write(cv::FileStorage &,const cv::String &,const std::vector<cv::DMatch,std::allocator<_Ty>> &)'
    1>          with
    1>          [
    1>              _Ty=cv::DMatch
    1>          ]
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(662): or       'void cv::write(cv::FileStorage &,const cv::String &,const std::vector<cv::KeyPoint,std::allocator<_Ty>> &)'
    1>          with
    1>          [
    1>              _Ty=cv::KeyPoint
    1>          ]
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(661): or       'void cv::write(cv::FileStorage &,const cv::String &,const cv::SparseMat &)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(660): or       'void cv::write(cv::FileStorage &,const cv::String &,const cv::Mat &)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(659): or       'void cv::write(cv::FileStorage &,const cv::String &,const cv::String &)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(658): or       'void cv::write(cv::FileStorage &,const cv::String &,double)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(657): or       'void cv::write(cv::FileStorage &,const cv::String &,float)'
    1>          E:\DEV\3rdparty.git\OpenCV\3.1.0\include\opencv2/core/persistence.hpp(656): or       'void cv::write(cv::FileStorage &,const cv::String &,int)'
    1>          while trying to match the argument list '(cv::FileStorage, cv::String, const cv::Matx<float,3,3>)'
    1>          OpenCVExperiments.cpp(46) : see reference to function template instantiation 'cv::FileStorage &cv::operator <<<cv::Matx<float,3,3>>(cv::FileStorage &,const _Tp &)' being compiled
    1>          with
    1>          [
    1>              _Tp=cv::Matx<float,3,3>
    1>          ]

**Comment by alalek** [comment]
This works:
```.cpp
    cv::FileStorage fs("dummy.xml", cv::FileStorage::WRITE);
    fs << "a" << Mat(cv::Matx33f::eye());
```

BTW, Probably there is representation conflict between Mat and Matx
