### ISSUE TITLE
Avast detects a virus in OpenCV 3

### ISSUE THREAD

**Issue by Gustavo72s** [opencv/opencv#8156]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows
- Compiler => -

##### Detailed description

Avast detects JS: Downloader-DZB [Trj] virus in OpenCV 3 (.exe file).

##### Steps to reproduce

I downloaded the OpenCV for Windows file (version 3.2) from http://opencv.org/downloads.html -> https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.2.0/opencv-3.2.0-vc14.exe/download

File: open-cv-3.2.0-vc14.exe.

I ran Avast Antivirus on the downloaded file and received a virus report: JS: Downloader-DZB [Trj] Specifically found in: open-cv-3.2.0-vc14.exe>opencv\sources\modules\ts\src\ts_gtest.cpp

**Comment by alalek** [comment]
> opencv\sources\modules\ts\src\ts_gtest.cpp

It should be a C++ source file without binary blobs.
Could you compare contents of the file on your side and [this](https://github.com/opencv/opencv/blob/3.2.0/modules/ts/src/ts_gtest.cpp) (there is RAW link for direct download)?

**Comment by mshabunin** [comment]
VirusTotal says the file is clean: https://www.virustotal.com/en/file/3e2b73fe6d0f84f8947a3a5d8776f93ec4d3eb7a0a3e32c13cd1cddfda85f786/analysis/
@Gustavo72s , you should search for problem on your machine. Try to update antivirus and bases and make a full computer scan.
