### ISSUE TITLE
makefile: 83: recipe for target 'all' failed, trying to build ORB-SLAM2

### ISSUE THREAD

**Issue by ucsdxiaoyuzhou** [opencv/opencv#8157]
##### System information (version)

- OpenCV => :3.2
- Operating System / Platform => :ubuntu 16.04
- Compiler => :

##### Detailed description

I am following the steps from README.txt to build ORB_SLAM2 on my ubuntu. I am running ubuntu on virtual machine, and I allocated 6GB RAM for it.
I think I did all dependencies, and all other requirements, and got to the last step:
which is to build ORB-SLAM2 library and TUM/KITTI examples, I used following commands:
cd ORB_SLAM2
chmod +x build.sh
./build.sh

and there are some errors so I am not able to build it successfully. The error is as following:
![screen shot 2017-02-09 at 00 55 14](https://cloud.githubusercontent.com/assets/23324604/22775988/da888fce-ee62-11e6-86ca-e9d24c84b4e3.png)
![screen shot 2017-02-09 at 00 55 35](https://cloud.githubusercontent.com/assets/23324604/22775989/da88b12a-ee62-11e6-859a-ca6a119f04f5.png)
![screen shot 2017-02-09 at 00 55 50](https://cloud.githubusercontent.com/assets/23324604/22776065/224d83f0-ee63-11e6-9c65-a1d391d14721.png)

I am struggling on it for a really long time, I really appreciate you guys help!!

**Comment by alalek** [comment]
Your error is not related to OpenCV. Report this to ORB_SLAB2

Also using screenshots with text information must be avoided to allow searching of similar issues
