### ISSUE TITLE
Memory leak in cv::ThreadManager

### ISSUE THREAD

**Issue by semenbudenkov** [opencv/opencv#8162]
### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => g++ (GCC) 5.3.0

### Detailed description
Valgrind profiler shows memory leak during execution of cascade classifier.
Output:
==24112== 768 bytes in 2 blocks are definitely lost in loss record 7,418 of 7,803
==24112==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24112==    by 0x40136D4: allocate_dtv (dl-tls.c:322)
==24112==    by 0x40136D4: _dl_allocate_tls (dl-tls.c:539)
==24112==    by 0x8A7326E: allocate_stack (allocatestack.c:588)
==24112==    by 0x8A7326E: pthread_create@@GLIBC_2.2.5 (pthread_create.c:539)
==24112==    by 0x5B4E87B: cv::ThreadManager::initPool()
==24112==    by 0x5B4EA87: cv::ThreadManager::run(cv::Range const&, cv::ParallelLoopBody const&, double)

I suppose this is known issue with pthreads library:
http://stackoverflow.com/questions/36898967/memory-leak-in-open-cv-threshold
http://stackoverflow.com/questions/17642433/why-pthread-causes-a-memory-leak
http://stackoverflow.com/questions/5610677/valgrind-memory-leak-errors-when-using-pthread-create
[mem_leak.txt](https://github.com/opencv/opencv/files/763539/mem_leak.txt)

### Steps to reproduce
Run example with cascades using Valgrind.

BR,
Semen

**Comment by alalek** [comment]
Just suppress warning for this case.

**Comment by semenbudenkov** [comment]
Ok, Thank you for quick reply.

BR,
Semen
