### ISSUE TITLE
CV_MAT_SUBMAT_FLAG is undefined

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#8171]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform =>Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Given a `cv::Mat m;`,  user can use its member method `m.isSubmatrix()` to test
whether it is a sub matrix or not. But there is also a marco `CV_IS_SUBMAT(flags)`,
which is defined in file `cvdef.h`, that could be used as a substitute.

`CV_IS_SUBMAT(flags)` is defined as follows:

```.cpp
#define CV_IS_SUBMAT(flags)     ((flags) & CV_MAT_SUBMAT_FLAG)
```

But `CV_MAT_SUBMAT_FLAG` is never defined. Therefore, it won't compile when
`CV_IS_SUBMAT(flags)` is used.

##### Steps to reproduce
```.cpp
	cv::Mat m(3, 3, CV_8U);
	cv::Mat sub = m(cv::Range(1,2), cv::Range(1,2));
	std::cout << !!CV_IS_SUBMAT(m.flags) << std::endl;
	std::cout << !!CV_IS_SUBMAT(sub.flags) << std::endl;
```
Code shown above will not compile.

##### Possible solution
Change `CV_MAT_SUBMAT_FLAG` to `CV_SUBMAT_FLAG`, which is defined in file `cvdef.h` as follows:
```.cpp
#define CV_SUBMAT_FLAG          (1 << CV_SUBMAT_FLAG_SHIFT)
```

**Comment by alalek** [comment]
This is legacy C API, it is candidate for removal and it should not be used.
You should use isSubmatrix() like you found.
