### ISSUE TITLE
GoodFeaturesToTrack method always faster without mask in iOS

### ISSUE THREAD

**Issue by pawlusmall** [opencv/opencv#8173]
I'm developing a tracking app on iOS with OpenCV 3.2 and I've discovered this strange behaviour.

Here it is some code:

```
vector<Point2f> goodFeatures;

unsigned long start = currentTimeMillis();

goodFeaturesToTrack(image, goodFeatures, 800, 0.1, 30);   

unsigned long end = currentTimeMillis();
cout << "Time without mask: " << (end - start) << " ms" << endl;
cout << goodFeatures.size() << " points feature found" << endl << endl;

unsigned long start2 = currentTimeMillis();

Mat mask(image.size(), CV_8U, Scalar(255));
Rect rect = Rect(image.cols / 8, image.rows / 8, image.cols - image.cols / 4, image.rows - image.rows / 4);
rectangle(mask, rect, Scalar(0), -1);    

goodFeaturesToTrack(image, goodFeatures, 800, 0.1, 30, mask);   

unsigned long end2 = currentTimeMillis();
cout << "Time with mask: " << (end2 - start2) << " ms" << endl;
cout << goodFeatures.size() << " points feature found" << endl << endl;
```

This is the output log in iOS (iPhone 5s):

```
Time without mask: 63 ms
174 points feature found

Time with mask: 68 ms
91 points feature found
```

This is the output log in OSX (Macbook Pro late 2013):

```
Time without mask: 21 ms
174 points feature found

Time with mask: 5 ms
91 points feature found
```

As you can see, using a mask makes sense on OSX, but it makes it slower on iOS!

More info and the images here: http://stackoverflow.com/questions/42157806/goodfeaturestotrack-method-always-faster-without-mask-in-ios

**Comment by mshabunin** [comment]
The platforms are different and optimizations can be different. Probably in your case ARM variant of _minMaxLoc_ works worse with mask and x86_64 variant uses IPP. You can instrument internal implementations and try to tune some parameters to make it work faster.

Feel free to add more details and reopen the issue if you find a problem in implementations.
