### ISSUE TITLE
TBB on iOS

### ISSUE THREAD

**Issue by Jaykob** [opencv/opencv#8179]
Intel's TBB is currently disabled when building for iOS. However, some modules (esp. from contrib) use TBB's `parallel_for` in order to improve performance.
Are there specific reasons for disabling TBB on iOS? A quick look at the TBB community suggests it should run fine on iOS: [https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/654031](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/654031)

**Comment by alalek** [comment]
Feel free to enable it locally, validate some OpenCV application with TBB on iOS device and then propose a PR with fix.

**Comment by Jaykob** [comment]
Where exactly could I enable it? Activating the TBB build flags doesn't to anything. A hint on where to start looking would be much appreciated.

**Comment by vpisarev** [comment]
On mac/ios opencv uses Apple's Grand Central Dispatch as parallel_for backend, which is system-wide solution. Use of TBB there is not recommended and is not supported

**Comment by Jaykob** [comment]
Can you explain how this is achieved when an algorithm (mainly from the contrib repo) explicitly checks whether TBB or OpenMP is defined and makes use of the according parallel_for implementation? 
Or in other words, I don't see GCD's dispatch_apply there...

**Comment by Jaykob** [comment]
OK I refactored the respective module (ximgproc - structured edge detection) to make use of OpenCV's parallel_for which uses the appropriate backend (TBB, OpenMP, GCD, ...) If I understood that right.
Will make a PR in the contrib repo when I find the time.
