### ISSUE TITLE
stereo camera problem between python version and C++ version

### ISSUE THREAD

**Issue by chaowu2009** [opencv/opencv#8184]
In python version, I can connect to two USB cameras simultaneously. 

In the C++ version, I could not connect with the second version, either in windows or Ubuntu 16.04.

Anybody has some thoughts? Thanks.

**Comment by mshabunin** [comment]
@chaowu2009 , please try to ask this question on the [user forum](http://answers.opencv.org/questions/) first. If you will find an evidence of a bug in OpenCV, then add more details to this issue (OS, platform, video capture backend, software version, short program reproducing the issue).
