### ISSUE TITLE
_InputArray::getMatVector returns incorrect value for the input std::vector<int>

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#8189]
##### System information (version)

- OpenCV => 3.1.0

##### Detailed description

The return value of `_InputArray::getMatVector` is unexpected for the input of `std::vector<int>`.

##### Steps to reproduce
```.cpp
int main()
{
  std::vector<int> v{1,2};

  cv::InputArray arr(v);
  std::vector<cv::Mat> planes;
  arr.getMatVector(planes);
  for (size_t i = 0; i < planes.size(); ++i)
  {
    std::cout << planes[i] << std::endl ;
  }
}
```
The output of the above code is
```
[1]
[2]
[1387598225]
[-1879046146]
[141302312]
[1]
[65537]
[0]
```

Only the first two values make sense.

##### Possible solution
Change [line 367 of file matrix.cpp](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L1367)

```.cpp
size_t n = v.size();
```
to
```.cpp
size_t n = size().width;
```

`n` should be the number of elements in the vector, not be the number of bytes.

**Comment by mschoeneck** [comment]
I think your usage is wrong.

`cv::Mat::getMatVector` is for `std::vector<cv::Mat>` objects. In you case you it should be:

```
int main()
{
  std::vector<int> v{1,2};
  cv::InputArray arr(v);

  cv::Mat planes = arr.getMat();
  std::cout << planes << std::endl ;
}
```

**Comment by csukuangfj** [comment]
Thank you for the response.

In fact, the method `void _InputArray::getMatVector(std::vector<Mat>& mv) const` is not documented at all. If its usage is restricted to `std::vector<cv::Mat>`, why don't we pass it to a function directly, instead of adding an indirection here?

If you look at its [implementation](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L1325)
, you will find that it supports not only `STD_VECTOR_MAT`, but also types like `MAT`, `MATX`,
`STD_VECTOR` and so on.

If the given type is a 2-D matrix, then according to the implementation, each element of the output container contains a row of the matrix. If it is a 3-D matrix, then each element contains a plane of the matrix.

If the given type is `STD_VECTOR`, it considers every element of the input container is a pixel. Correspondingly, every element of the output container represents a pixel.

Therefore, for the given code
```.cpp
int main()
{
  std::vector<int> v{1,2};

  cv::InputArray arr(v);
  std::vector<cv::Mat> planes;
  arr.getMatVector(planes);
  for (size_t i = 0; i < planes.size(); ++i)
  {
    std::cout << planes[i] << std::endl ;
  }
}
```
The container `v` contains 2 pixels, whose depth is `CV_32S` and the number of channels is 1. Thus the expected output container should contain two elements. But currently, it contains 8 elements, which is exactly the number of bytes `v` occupies.

**Comment by mshabunin** [comment]
@csukuangfj , looking to the code:
```.cpp
if( k == STD_VECTOR )
{
    const std::vector<uchar>& v = *(const std::vector<uchar>*)obj;
```
The _STD_VECTOR_ handler is implemented for _uchar_ type only. I can see following solutions:
- implement all possible vector types in `vector<T>` and `vector<vector<T>>` branches (a lot of code)
- throw exception if stored type is not _uchar_
- forbid all instantiations of `InputArray(const std::vector<T> &vec)` except _uchar_

**Comment by alalek** [comment]
There is [workaround in `_InputArray::size()`](https://github.com/opencv/opencv/blame/3.2.0/modules/core/src/matrix.cpp#L1562-L1569) about `STD_VECTOR` to support other types and different STL implementations. IMHO, it looks like a hack with some assumptions. But `std::vector<int>` (and `std::vector<Point2f>`) is supported somehow in OpenCV.

Also there is additional special branch for `std::vector<bool>` (`STD_BOOL_VECTOR` kind code).

Replacing `planes.size()` to `this->size().width` (or `this->size().area()` or `this->total()`) should work somehow (**and resolve this issue**).

BTW, To limit supported types of `std::vector<T>` in [_InputArray ctor](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/mat.inl.hpp#L76-L78) we probably need to drop incorrect [default values](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/traits.hpp#L113-L118) in the `DataType` traits to generate compilation errors (related #7599).

**Comment by csukuangfj** [comment]
@mshabunin 

```.cpp
if( k == STD_VECTOR )
{
    const std::vector<uchar>& v = *(const std::vector<uchar>*)obj;
```
does not mean it is implemented for *uchar* type only.

The purpose of `v` is to get the starting address of the first element:
```.cpp
(void*)(&v[0])
```

There are many statements like this one inside `_InputArray`. For example, <https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L1599>

```.cpp
    if( k == STD_VECTOR )
    {
        CV_Assert( i < 0 );
        const std::vector<uchar>& v = *(const std::vector<uchar>*)obj;
        const std::vector<int>& iv = *(const std::vector<int>*)obj;
        size_t szb = v.size(), szi = iv.size();
        return szb == szi ? Size((int)szb, 1) : Size((int)(szb/CV_ELEM_SIZE(flags)), 1);
    }
```
It uses `v` to calculate the number of elements in the container:
```.cpp
Size((int)(szb/CV_ELEM_SIZE(flags))
```

**Comment by alalek** [comment]
This is a hack for different STL implementations, like these:
```
// same result for any "T"
template<typename T, ...> size_t std::vector::size() const { return m_sizeInElements; }
```
or
```
// result depends on "T"
// so we check size of "uchar" an "int" and extrapolate results to other types
template<typename T, ...> size_t std::vector::size() const { return m_sizeInBytes/sizeof(T); }
```

**Comment by csukuangfj** [comment]
@alalek 

Thank you for the reply.

Now I understand the statement
```.cpp
return szb == szi ? Size((int)szb, 1) : Size((int)(szb/CV_ELEM_SIZE(flags)), 1);
```
:smiley: :grin:
