### ISSUE TITLE
How to integrate OpenCV Manager in Android App?

### ISSUE THREAD

**Issue by VacheMumchyan** [opencv/opencv#8193]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
OpenCV Manager is a separate application.
It is better to put OpenCV libraries into your app. In this case your application will work without OpenCV Manager.

**Comment by VacheMumchyan** [comment]
I have a project with opencv and when I want to run it, it requires to download opencv manager from play store. How can I make my app work normally without downloading opencv manager from play store?
Can you, please, describe the process step by step?

**Comment by alalek** [comment]
You need to put OpenCV libraries into your "libs" directory:
- you can use `OPENCV_INSTALL_MODULES=on` in case of using [JNI code](https://github.com/opencv/opencv/blob/master/samples/android/face-detection/jni/Android.mk)
- or use some gradle step to copy OpenCV libraries

BTW, This is not the right place to discuss usage questions. Try to ask for help on OpenCV User Q/A forum: http://answers.opencv.org

**Comment by VacheMumchyan** [comment]
Can you, please, connect me via team viewer and help me?  It will be of great help to me. You can contact me  the way it is convenient to you.  Thanks in advance
