### ISSUE TITLE
OpenCV android version

### ISSUE THREAD

**Issue by VacheMumchyan** [opencv/opencv#8194]
While running and touching camera color blob detection of the OpenCv3.2 version the process is crushing
Maybe it depends on the OpenCv3.2 version? but when i use Opencv3.0 version and lower versions it works properly
How can you help me?﻿

**Comment by alalek** [comment]
Please add dump of `adb logcat` messages from application launch and the crash

**Comment by VacheMumchyan** [comment]
I have a project with opencv and when I want to run it, it requires to download opencv manager from play store. How can I make my app work normally without downloading opencv manager from play store?
Can you, please, describe the process step by step?
