### ISSUE TITLE
Error Include ImfChromaticities.h in Comping

### ISSUE THREAD

**Issue by questionpython** [opencv/opencv#8200]
hi
i want build opencv on ubuntu 16.10.

>:~/opencv-2.4.11/build$ make
[  3%] Built target libtiff
[  6%] Built target opencv_core
[  6%] Automatic moc for target opencv_highgui
[  6%] Built target opencv_highgui_automoc
[  9%] Built target opencv_imgproc
[  9%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/loadsave.cpp.o
In file included from /home/guest/opencv-2.4.11/modules/highgui/src/grfmts.hpp:54:0,
                 from /home/guest/opencv-2.4.11/modules/highgui/src/loadsave.cpp:47:
/home/guest/opencv-2.4.11/modules/highgui/src/grfmt_exr.hpp:52:31: fatal error: ImfChromaticities.h: No such file or directory
` #include <ImfChromaticities.h>`
compilation terminated.
modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:125: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/src/loadsave.cpp.o' failed
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/loadsave.cpp.o] Error 1
CMakeFiles/Makefile2:1420: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

how fix this?

**Comment by alalek** [comment]
OpenCV 2.4.11 is released significantly before Ubuntu 16.10.

> [ 6%] Automatic moc for target opencv_highgui
[ 6%] Built target opencv_highgui_automoc

We are not able to reproduce problems on custom configurations.

BTW, Your investigation should start from `make VERBOSE=1`.
