### ISSUE TITLE
Error opencv_highgui.dir/src/cap_ffmpeg.cpp.o failed in Compiling 

### ISSUE THREAD

**Issue by questionpython** [opencv/opencv#8202]
Error in Compiling , my system is GNU/LINUX - UBUNTU 16.10

>$ `cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -DENABLE_PRECOMPILED_HEADERS=OFF  -D WITH_OPENGL=ON -DWITH_OPENEXR=OFF  -D WITH_VTK=ON ..`

>$ `make`
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp: In member function ‘bool InputMediaStream_FFMPEG::open(const char*, int*, int*, int*, int*)’:
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp:2188:18: error: ‘PIX_FMT_YUV420P’ was not declared in this scope
             case PIX_FMT_YUV420P:
                  ^~~~~~~~~~~~~~~
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp:2192:18: error: ‘PIX_FMT_YUV422P’ was not declared in this scope
             case PIX_FMT_YUV422P:
                  ^~~~~~~~~~~~~~~
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp:2196:18: error: ‘PIX_FMT_YUV444P’ was not declared in this scope
             case PIX_FMT_YUV444P:
                  ^~~~~~~~~~~~~~~
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp: In member function ‘bool OutputMediaStream_FFMPEG::open(const char*, int, int, double)’:
/home/guest/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp:2022:41: warning: ignoring return value of ‘int avformat_write_header(AVFormatContext*, AVDictionary**)’, declared with attribute warn_unused_result [-Wunused-result]
         avformat_write_header(oc_, NULL);
                                         ^
modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:293: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o' failed
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o] Error 1
CMakeFiles/Makefile2:1364: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
root@system:/home/opencv-2.4.11/build# 

how fix this?

**Comment by alalek** [comment]
You should use latest release from 2.4 branch. 2.4.11 is outdated.

**Comment by questionpython** [comment]
i download from : 

>wget http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.11/opencv-2.4.11.zip
unzip opencv-2.4.11.zip
cd opencv-2.4.11

but also have problem.

**Comment by alalek** [comment]
2.4.11 -> 2.4.13.2 (use OpenCV releases **after** 2016/10)

**Comment by ncanestrari** [comment]
same issue with 2.4.13.2
