### ISSUE TITLE
cv::ocl::Device::OpenCLVersion() is implemented incorrectly

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#8212]
##### System information (version)

- OpenCV => 3.1.0

##### Detailed description

The implementation of `cv::ocl::Device::OpenCLVersion()` is as follows:
```.cpp
String Device::OpenCLVersion() const
{ return p ? p->getStrProp(CL_DEVICE_EXTENSIONS) : String(); }
```

It returns the device extension information, which is not the OpenCL version!

##### Steps to reproduce

```.cpp
cv::ocl::Device d = cv::ocl::Device::getDefault();
std::cout << d.OpenCLVersion();
```
The above program prints the device extension information.

**Comment by jinay1991** [comment]
Changing opencv-master/opencv/modules/core/src/ocl.cpp:1938 to 

```C
String Device::OpenCLVersion() const
{ return p ? p->getStrProp(CL_DEVICE_VERSION) : String(); }
```

As per the specification of OpenCL v1.x or v2.x, CL_DEVICE_VERSION provides OpenCL 2.0 AMD-APP (1800.11) 

where 2.0 is the OpenCL Supported Version.

This is Bug and should be corrected on OpenCV-master.

**Comment by csukuangfj** [comment]
`String Device::version() const` has already provides the information about `CL_DEVICE_VERSION`.

Why is there a need for another function to get the same information?

**Comment by jinay1991** [comment]
Agreed. And I have cross checked that no Other APIs are using this function with in OpenCV. I think it is safe to remove the function (i.e. OpenCLVersion) completely. Let me know if you are fine with this. And we can update.

**Comment by csukuangfj** [comment]
Yes, I think this this function can be removed.

**Comment by jinay1991** [comment]
#8216 #8215

**Comment by alalek** [comment]
Public methods can't be removed due maintenance of OpenCV 3.x release series.

**Comment by csukuangfj** [comment]
@alalek 
This problem has not been fixed. Why is it closed now?

**Comment by alalek** [comment]
This code
```
cv::ocl::Device d = cv::ocl::Device::getDefault();
std::cout << d.OpenCLVersion();
```
returns this:
```
OpenCL 2.0
```
with Intel OpenCL r5.0 (Linux).

What is the problem?

**Comment by jinay1991** [comment]
Based on https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_SDK_release, New release supports OpenCL 2.0 for some of the intel CPU/GPU. And I believe intention behind `d.OpenCLVersion()` call is to return current Version of OpenCL. So based on the results you have shared I really see if anything is going wrong.
