### ISSUE TITLE
Is there a way to apply rank filter to an image using OPENCV?

### ISSUE THREAD

**Issue by xray1111** [opencv/opencv#8218]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

I can only find 3 kind of rank filter API such as max, min and median filter in OPENCV, but what I really want is a more general type of filter, it should have an user defined index option to choose while ranking the kernel elements. Or, can I have some other solutions to work around it?

Thank you very much!

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
