### ISSUE TITLE
Unespected behaviour drawing arc with ellipse() 

### ISSUE THREAD

**Issue by PkLab** [opencv/opencv#8219]
#### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

#### Detailed description
Both doc and code works different than expected. It looks that `startAngle` and `endAngle` refer to the projections on the ellipse of the wanted arc on the bounding circle. Look at the image

![ellipse](https://cloud.githubusercontent.com/assets/15944968/23079369/fc7c73b6-f54c-11e6-977b-bf344f223876.png)

The blue arc has been generated 30/45/135 as angle/start/end.
The red arc has been using same angles as above but choosing equal axis.

May be this is wanted but is not same as is in [the doc](http://docs.opencv.org/3.2.0/d6/d6e/group__imgproc__draw.html#ga28b2267d35786f5f890ca167236cbc69).

#### Steps to reproduce

```.cpp
int TestEllipse()
{
    int angle = 30,startAngle = 45,endAngle = 135;
    Mat img(400, 400, CV_8UC3, Scalar(255, 255, 255));
    Point center = img.size() / 2;
    int major = 0.4*img.rows;
    Size sz(major, major*0.5);
    line(img, Point(center.x, 0), Point(center.x, img.rows), Scalar(0), 1);
    line(img, Point(0, center.y), Point(img.cols, center.y), Scalar(0), 1);

    ellipse(img, center, sz, angle, 0, 360, CL_GREEN, 1);
    ellipse(img, center, sz, angle, startAngle, endAngle, CL_BLUE, 2);
    sz = Size(sz.width, sz.width);
    ellipse(img, center, sz, angle, 0, 360, CL_MAGENTA, 1);
    ellipse(img, center, sz, angle, startAngle, endAngle, CL_RED, 2);
    
    vector<double> mags, angles, x, y;
    double mag = 1.2 * major, alpha = angle;
    mags = { mag, mag };
    angles = { (alpha + startAngle), (alpha + endAngle) };
    polarToCart(mags, angles, x, y, true);
    for (size_t i = 0; i < x.size(); i++)
        line(img, center, center + Point(x[i], y[i]), Scalar(160, 160, 160));
    
    imshow("ellipse", img);
    waitKey(0);
    return 0;
}
```

**Comment by mshabunin** [comment]
Looks like the documentation image should be changed.

**Comment by PkLab** [comment]
And what about the bounding circle ? Don't you think that the blue arc should start/stop at highlighted points ?

**Comment by mshabunin** [comment]
I've checked _drawEllipseArc_ in GNU Octave and it works this way, it uses same angles for ellipse and circle:
![image](https://cloud.githubusercontent.com/assets/3304494/23160482/bc7f06f0-f837-11e6-8e8d-4aba4f8e0fc3.png)

So it will be good to be consistent with mathematical packages (probably Matlab works the same way). But on the other hand is compatibility - we can not change function behavior. Furthermore, current OpenCV implementation looks reasonable if we think of ellipse as a projection of circle.

Thus, changing the documentation will be a bug fix and implementing new drawing mode or function can be considered a feature.

**Comment by PkLab** [comment]
I think that new feature or bug depends on specification, is the doc a specification :confused:

At the end the most important is that the doc and the code must be coherent.

I'll prepare a PR for the doc image as I'll have a bit of time. 
How we can best describe current function behaviour for the needed doc update ?

OT: It's interesting how it can happens that some docs have this kind of mistake...

**Comment by mshabunin** [comment]
>How we can best describe current function behaviour for the needed doc update ?

The drawing code uses [General parametric form](https://en.wikipedia.org/wiki/Ellipse#General_parametric_form).

**Comment by Willowlululu** [comment]
so Could you tell me now , use the cv.ellipse() . I can get the real a start angle in the ellipse instead of the in the circle with long axis length as r and then map it into ellipse alongside with the line which is parallel with the short axis??

**Comment by PkLab** [comment]
I would start from the Polar Forms https://en.wikipedia.org/wiki/Ellipse#Polar_forms

**Comment by cbasavaraj** [comment]
This explains the problem and the solution: [link](http://www.petercollingridge.co.uk/tutorials/computational-geometry/finding-angle-around-ellipse/)

But I still don't get a perfect arc, wondering why.

**Comment by Willowlululu** [comment]
> I would start from the [Polar Forms](https://en.wikipedia.org/wiki/Ellipse#Polar_forms)

thank you for your advice
