### ISSUE TITLE
CascadeClassifier  can't work

### ISSUE THREAD

**Issue by lqj1990** [opencv/opencv#8224]
##### Detailed description

When I try to detect an object using cascade classifier, it can't return any result. I use haarcascade_frontalface_alt.xml and test image is lena.jpg.
The  `Mat(1, (int)(v.size()*sizeof(v[0])), CV_8U, (void*)&v[0]).copyTo(um);`  will not return any result, so the program get stuck. The v.size() is 2135. What can I do to solve the problem?

Detection code.
```.cpp
        string cascade_name = "D:\\project\\TestCascade\\test\\haarcascade_frontalface_alt.xml";  
 
	CascadeClassifier cascade(cascade_name);  

	std::vector<Rect> cars;  

	Mat frame = imread("D:\\project\\TestCascade\\test\\lena.jpg");  

	Size x = frame.size();  

	Mat frame_gray;   

	cvtColor(frame, frame_gray, CV_BGR2GRAY);  

	equalizeHist(frame_gray, frame_gray);  

	cascade.detectMultiScale(frame_gray, cars, 1.01, 3, 0, Size(30,30));  
```

**Comment by alalek** [comment]
Run OpenCV tests at first.
Try to disable OpenCL support too (or use OpenCV 3.2).
