### ISSUE TITLE
Update param type of input image in cv::findContours 

### ISSUE THREAD

**Issue by PkLab** [opencv/opencv#8225]
#### System information (version)
- OpenCV => 3.2

#### Detailed description

Since opencv 3.2 source image is not modified by this function. See [master doc](http://docs.opencv.org/master/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a) and #7516. The param type should reflect this change.

Now  `void cv::findContours( InputOutputArray _image, ...`
Better `void cv::findContours( InputArray _image, ...`

I know this would break ABI compatibility but may be in next release....

BTW it should exists great evidence of this update because `findContours`  is widely used, the 3.2 doc isn't aligned to the code and currently all users clone the input image while this is a complete of wast time.

**Comment by catree** [comment]
Yes afterwards, I should have suggested or submitted a PR to add also a note in the documentation.

Before the update, are you aware of some possible usage of the input (modified by `findContours`) image or it is completely garbage/useless?

**Comment by PkLab** [comment]
doc note is in the master doc only. It should be #7983, here, the update of input image param type is also required. 

Regards to the old chain mage, I never used it. Maybe you can ask to anybody on the Q&A here http://answers.opencv.org/question/128937/news-findcontours-doesnt-alter-the-input-image/

**Comment by basantapatra** [comment]
In findContours, the input image will be copied/cloned to a new image buffer. Once the copying is done there is no use of "InputOutputArray _image".  

As the input image is not getting modified, its better to  make the input image as read-only with the use of InputArray _image instead of InputOutputArray _image while taking care of ABI compatibility.

**Comment by PkLab** [comment]
@catree 

> Before the update, are you aware of some possible usage of the input (modified by findContours) image or it is completely garbage/useless?

see http://answers.opencv.org/question/136689/freeman-chain-code-in-opencv-3/

**Comment by sturkmen72** [comment]
anyone will create a PR?
