### ISSUE TITLE
Cannot build OpenCV for iOS with --contrib or --without options

### ISSUE THREAD

**Issue by riless** [opencv/opencv#8227]
Building `opencv2.framework` with this command works just fine.

`rm -rf ios/ && python opencv/platforms/ios/build_framework.py ios --dynamic`

`build_framework.py` accepts [`--contrib`](https://github.com/opencv/opencv/blob/master/platforms/ios/build_framework.py#L284) and [`--without`](https://github.com/opencv/opencv/blob/master/platforms/ios/build_framework.py#L285) parameters to add contrib modules and exclude some modules respectively, but the build fails if I add one of them.

`rm -rf ios/ && python opencv/platforms/ios/build_framework.py ios --dynamic --contrib ./opencv_contrib`

> /path/to/opencv/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7/opencv2
> ld: library not found for -lfreetype
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> BUILD FAILED
> 
> The following build commands failed:
> 	Ld/path/to/opencv/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7s/opencv2 normal armv7s
> 	Ld /path/to/opencv/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/arm64/opencv2 normal arm64
> 	Ld /path/to/opencv/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7/opencv2 normal armv7
> (3 failures)

`rm -rf ios/ && python opencv/platforms/ios/build_framework.py ios --dynamic --without text`

> BUILD FAILED
> 
> The following build commands failed:
> 	Ld /path/to/opencv/ios/build/build-iphoneos/modules/ml/OpenCV.build/Release-iphoneos/opencv_ml.build/Objects-normal/armv7/opencv2 normal armv7
> (1 failure)
> 
> ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
> 
> Traceback (most recent call last):
>   File "opencv/platforms/ios/build_framework.py", line 112, in build
>     self._build(outdir)
>   File "opencv/platforms/ios/build_framework.py", line 104, in _build
>     self.buildOne(t[0], t[1], mainBD, cmake_flags)
>   File "opencv/platforms/ios/build_framework.py", line 204, in buildOne
>     execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
>   File "opencv/platforms/ios/build_framework.py", line 36, in execute
>     retcode = check_call(cmd, cwd = cwd)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65

**Comment by alalek** [comment]
> ld: library not found for -lfreetype

Probably this problem is not related to the title of issue.

BTW, probably related issue: #8121

**Comment by riless** [comment]
@alalek I `rm -rf ios/` then used the exact same command as @benjohnde in #8121 and still have the same issue.

> ...
>   "_cvFlip", referenced from:
>       _cvConvertImage in utils.o
>   "cv::Mat::copyTo(cv::_OutputArray const&) const", referenced from:
>       cv::HdrEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&) in grfmt_hdr.o
>   "cv::tempfile(char const*)", referenced from:
>       cv::imdecode_(cv::Mat const&, int, int, cv::Mat*) in loadsave.o
>       cv::imencode(cv::String const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&) in loadsave.o
>   "cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)", referenced from:
>       cv::ApplyExifOrientation(cv::String const&, cv::Mat&) in loadsave.o
>       cv::imwrite_(cv::String const&, cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&, bool) in loadsave.o
>       _cvEncodeImage in loadsave.o
>   "cv::String::allocate(unsigned long)", referenced from:
>       cv::RBaseStream::open(cv::Mat const&) in bitstrm.o
>       cv::BaseImageEncoder::throwOnEror() const in grfmt_base.o
>       cv::BmpDecoder::BmpDecoder() in grfmt_bmp.o
>       cv::BmpEncoder::BmpEncoder() in grfmt_bmp.o
>       cv::HdrDecoder::HdrDecoder() in grfmt_hdr.o
>       cv::HdrEncoder::HdrEncoder() in grfmt_hdr.o
>       cv::HdrEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&) in grfmt_hdr.o
>       ...
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Ld /path/to/opencv/ios/build/build-iphoneos/modules/imgcodecs/OpenCV.build/Release-iphoneos/opencv_imgcodecs.build/Objects-normal/arm64/opencv2 normal arm64
> 	Ld /path/to/opencv/ios/build/build-iphoneos/modules/imgcodecs/OpenCV.build/Release-iphoneos/opencv_imgcodecs.build/Objects-normal/armv7/opencv2 normal armv7
> (2 failures)
> 
> ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
> 
> Traceback (most recent call last):
>   File "opencv/platforms/ios/build_framework.py", line 112, in build
>     self._build(outdir)
>   File "opencv/platforms/ios/build_framework.py", line 104, in _build
>     self.buildOne(t[0], t[1], mainBD, cmake_flags)
>   File "opencv/platforms/ios/build_framework.py", line 204, in buildOne
>     execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
>   File "opencv/platforms/ios/build_framework.py", line 36, in execute
>     retcode = check_call(cmd, cwd = cwd)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65

**Comment by alalek** [comment]
Did you try [this suggestion](https://github.com/opencv/opencv/issues/8121#issuecomment-276958174)?

**Comment by riless** [comment]
@alalek

Yes, still have the same error.

[log.txt](https://github.com/opencv/opencv/files/788072/log.txt)

**Comment by alalek** [comment]
> still have the same error.

This is definitely not the same error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UIImage", referenced from:
      objc-class-ref in ios_conversions.o
ld: symbol(s) not found for architecture arm64
```

In your configuration we need to add `-framework UIKit`, because `videoio` module is disabled.
You need similar [patch](https://github.com/opencv/opencv/pull/8009/files#diff-5220a4aee9ea1e805a55427af625a122R214) in imgcodecs, but I'm not sure about the right condition. Probably @benjohnde may suggest something.

**Comment by benjohnde** [comment]
Did you also clean the whole thing before re-building it? On three completely different Macs, my command worked as intended -- after the patch. The most common problem was to not cleaning the build directory beforehand.

**Comment by riless** [comment]
@benjohnde what do you mean by cleaning the whole thing ? is `rm -rf ios/` enough for that ? if so, I'm doing that before each build.

@alalek I've just tested with [your pullrequest](https://github.com/opencv/opencv/pull/8009) and still have errors.

```
$ cd opencv
$ git log -1
commit 526220a171d4d7d6b2065445b5794b7a50930166
Author: Fangjun KUANG <csukuangfj@gmail.com>
Date:   Tue Feb 21 10:48:15 2017 +0100

    Fix typos in the documentation (#8226)
    * fix typos.
    * Fix typos.
    * Fix typos.
    * Fix typos.
    * Fix typos.

$ cd ../opencv_contrib
$ git log -1
commit b527ab99034f21eadbb304ce29eda442522cae91
Merge: b11ce40 1df961c
Author: Alexander Alekhin <alexander.a.alekhin@gmail.com>
Date:   Tue Feb 21 14:32:55 2017 +0300

    Merge pull request #1008 from Sahloul:features/python_wrapper/surface_matching

    Wrap `computeNormalsPC3d()` for python
$ cd ..
$ rm -rf ios/
$ python opencv/platforms/ios/build_framework.py ios --dynamic --contrib opencv_contrib \
         --without dpm           --without face          --without fuzzy         --without hdf           --without line_descriptor   \
         --without matlab        --without plot          --without reg           --without rgbd          --without saliency          \
         --without sfm           --without stereo        --without text          --without xphoto        --without surface_matching  \
         --without photo         --without stitching     --without cudaarithm    --without cudabgsegm    --without cudacodec         \
         --without viz           --without cudastereo    --without dnn           --without datasets      --without cudafeatures2d    \
         --without cudafilters   --without cudaimgproc   --without cudalegacy    --without cudaobjdetect --without cudaoptflow       \
         --without cudawarping   --without cudev         --without shape         --without superres      --without videostab         \
         --without ccalib        --without structured_light \
         --without tracking      --without aruco         --without bgsegm        --without cvv           --without bioinspired > log.txt

Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_SHARED_LIBS=ON', '-DCMAKE_MACOSX_BUNDLE=ON', '-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO', '-DBUILD_opencv_world=OFF', '-DBUILD_opencv_dpm=OFF', '-DBUILD_opencv_face=OFF', '-DBUILD_opencv_fuzzy=OFF', '-DBUILD_opencv_hdf=OFF', '-DBUILD_opencv_line_descriptor=OFF', '-DBUILD_opencv_matlab=OFF', '-DBUILD_opencv_plot=OFF', '-DBUILD_opencv_reg=OFF', '-DBUILD_opencv_rgbd=OFF', '-DBUILD_opencv_saliency=OFF', '-DBUILD_opencv_sfm=OFF', '-DBUILD_opencv_stereo=OFF', '-DBUILD_opencv_text=OFF', '-DBUILD_opencv_xphoto=OFF', '-DBUILD_opencv_surface_matching=OFF', '-DBUILD_opencv_photo=OFF', '-DBUILD_opencv_stitching=OFF', '-DBUILD_opencv_cudaarithm=OFF', '-DBUILD_opencv_cudabgsegm=OFF', '-DBUILD_opencv_cudacodec=OFF', '-DBUILD_opencv_viz=OFF', '-DBUILD_opencv_cudastereo=OFF', '-DBUILD_opencv_dnn=OFF', '-DBUILD_opencv_datasets=OFF', '-DBUILD_opencv_cudafeatures2d=OFF', '-DBUILD_opencv_cudafilters=OFF', '-DBUILD_opencv_cudaimgproc=OFF', '-DBUILD_opencv_cudalegacy=OFF', '-DBUILD_opencv_cudaobjdetect=OFF', '-DBUILD_opencv_cudaoptflow=OFF', '-DBUILD_opencv_cudawarping=OFF', '-DBUILD_opencv_cudev=OFF', '-DBUILD_opencv_shape=OFF', '-DBUILD_opencv_superres=OFF', '-DBUILD_opencv_videostab=OFF', '-DBUILD_opencv_ccalib=OFF', '-DBUILD_opencv_structured_light=OFF', '-DBUILD_opencv_tracking=OFF', '-DBUILD_opencv_aruco=OFF', '-DBUILD_opencv_bgsegm=OFF', '-DBUILD_opencv_cvv=OFF', '-DBUILD_opencv_bioinspired=OFF', '-DIOS_ARCH=armv7;armv7s;arm64', '-DCMAKE_TOOLCHAIN_FILE=/path/to/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/path/to/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/path/to/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /path/to/ios/build/build-iphoneos

Executing: ['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build'] in /path/to/ios/build/build-iphoneos

** BUILD FAILED **


The following build commands failed:
	Ld /path/to/ios/build/build-iphoneos/modules/ml/OpenCV.build/Release-iphoneos/opencv_ml.build/Objects-normal/armv7/opencv2 normal armv7
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 104, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 204, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 36, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
```

[log.txt](https://github.com/opencv/opencv/files/790421/log.txt)

**Comment by alalek** [comment]
@riless You don't test my pullrequest actually (8009 is not my PR).
To fetch my PR's code you need to run something like this (for opencv repo):
```
git fetch https://github.com/opencv/opencv.git +pull/8234/head:pr8234
git checkout pr8234
```

**Comment by riless** [comment]
@alalek I thought that as it was merged, I can get the latest commit and try with.
Anyway I retried with you method, same thing.

```
** BUILD FAILED **

The following build commands failed:
	Ld /path/to/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7/opencv2 normal armv7
	Ld /path/to/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/armv7s/opencv2 normal armv7s
	Ld /path/to/ios/build/build-iphoneos/modules/world/OpenCV.build/Release-iphoneos/opencv_world.build/Objects-normal/arm64/opencv2 normal arm64
(3 failures)
============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 104, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 193, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 36, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=8.0', 'ONLY_ACTIVE_ARCH=NO', '-arch', 'armv7', '-arch', 'armv7s', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
```

[log.txt](https://github.com/opencv/opencv/files/790511/log.txt)

**Comment by riless** [comment]
Finally there is two different problems, that's why 

The first one apears when I use `--contrib`,  I've tried and retried many times (with `rm -rf ios/` beforehand) and it's always the same error: `ld: library not found for -lfreetype` so I've added `--without freetype`. The error disapears and the other one appears : 

```
Undefined symbols for architecture armv7:
  "cv::Mat::eye(int, int, int)", referenced from:
   ...
```

Now I build correctly when I comment out this line `args += ["-DBUILD_opencv_world=OFF"]` in the `build_framework.py` file.

My questions now are: 
1. Why the first error appears`ld: library not found for -lfreetype` ?
2. Why the build script has a hard coded `-DBUILD_opencv_world=OFF` flag ?  I'd like to automate the clone and build procedure in a podspec, and this flag don't allow me to do that.

**Comment by riless** [comment]
The workaround I found, is to create a `custom_ build_framework.py` to comment out `args += ["-DBUILD_opencv_world=OFF"]`.

I'm closing this as it seems that I'm the only one that had the problem.

**Comment by carlgik4** [comment]
guys, you may forget modules after opencv_contrib, my command:

```Bash
rm -rf opencv_output
python opencv/platforms/ios/build_framework.py --contrib opencv_contrib/modules opencv_output
```
you may add `--dynamic` on demand

**Comment by airman00** [comment]
For reference , carlgik4's mistake was that it should be
` --contrib opencv_contrib  
`
and not
` --contrib opencv_contrib/modules`
