### ISSUE TITLE
Different result between CPU and GPU(CUDA) in Gaussian Blur

### ISSUE THREAD

**Issue by eri-st** [opencv/opencv#8229]
##### System information (version)
- OpenCV => 2.4.13
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Cuda=> 8.0
##### Detailed description

Running both functions on the same input image gives diffrent results, seems the gpu gives a 1 or 2 value offset. this is on a uchar 1 channel image.

##### Steps to reproduce
```
cv::mat img //upload image to this mat

cv::gpu::GpuMat inputImg;
cv::gpu::GpuMat buff;
cv::gpu::GpuMat blurImg;
cv::Mat smoothed;

smoothed.create(m_frame_height, m_frame_width, CV_8UC1);
inputImg.create(m_frame_height, m_frame_width, CV_8UC1);
buff.create(m_frame_height, m_frame_width, CV_8UC1);
blurImg.create(m_frame_height, m_frame_width, CV_8UC1);

inputImg.upload(img);
cv::gpu::GaussianBlur(inputImg,` blurImg, cv::Size(5, 5), buff, 0.5, 0.5);
cv::Mat smoothedGPU;
blurImg.download(smoothedGPU);
cv::GaussianBlur(img, smoothed, cv::Size(5, 5), 0.5, 0.5);
cv::Mat smTmp, smGpuTmp;
smoothed.convertTo(smTmp, CV_32SC1);
smoothedGPU.convertTo(smGpuTmp, CV_32SC1);
cv::Mat smdiff = smTmp - smGpuTmp;
cv::Scalar sumdiff = cv::sum(cv::abs(smdiff));
if (sumdiff.val[0] > 0)
	printf("err %f\n", sumdiff.val[0]);
```

**Comment by alalek** [comment]
Almost all computations in OpenCV (which use floating-points) are not bit-exact. But results are "looks the same". Take a look on OpenCV tests criteria for details.

**Comment by eri-st** [comment]
yes but the results are off buy a value of at least 1 across the image. a rounding error can be understood. an offset is a bug

**Comment by mshabunin** [comment]
@eri-st , in our tests expected difference does not exceed 4 for non-float images: https://github.com/opencv/opencv/blob/3.2.0/modules/cudafilters/test/test_filters.cpp#L416-L488
Did you try to run it on your platform?
