### ISSUE TITLE
Cannot use sift()

### ISSUE THREAD

**Issue by billchenxi** [opencv/opencv#8232]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Mac OS latest
- Compiler => Jupyter Notebook, python

##### Detailed description
I cannot use the CV2.sift() object. Can you verify for me? My email is billchenxi@gmail.com.

##### Steps to reproduce
I followed your tutorial: http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.html#sift-intro

sift = cv2.sift() or sift=cv2.SIFT()

and when I run the code below, it report errors, I changed to capitalized and non-capitalized, none work. And the error is: "AttributeError: module 'cv2' has no attribute 'sift'" or AttributeError: module 'cv2' has no attribute 'SIFT'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-89e14abf430a> in <module>()
      1 gray= cv2.cvtColor(im1a, cv2.COLOR_BGR2GRAY)
----> 2 sift = cv2.sift()
      3 kp = sift.detect(gray,None)
      4 
      5 img=cv2.drawKeypoints(gray,kp)

AttributeError: module 'cv2' has no attribute 'sift'

**Comment by alalek** [comment]
SIFT is moved to [opencv_contrib](https://github.com/opencv/opencv_contrib), so you need to build it.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

BTW, `dir(cv2)` command shows available attributes of cv2 module.
