### ISSUE TITLE
Problem using opencv 3.2.0

### ISSUE THREAD

**Issue by pavantankasala** [opencv/opencv#8246]
##### System information (version)
<-- OpenCV => 3.2
- Operating System / Platform => UBUNTU 14.04
- Compiler => GCC
-->

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

<--  I am migrating from opencv 2.4.8 which is ROS INDIGO compatible to opencv 3.2.0 dev for usage of latest algorithms. I have problems running code. Even I cant use imshow.
when I compile the code everything goes ok and this message pops up
"/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /usr/local/lib/libopencv_highgui.so.3.2.0, may conflict with libopencv_imgproc.so.2.4
/usr/bin/ld: warning: libopencv_video.so.2.4, needed by /usr/lib/x86_64-linux-gnu/libopencv_contrib.so.2.4.8, may conflict with libopencv_video.so.3.2"  

please suggest. is there an easy way to migrate from 2.4.8 to latest version and still compatible with  ROS.

Thanks
Pavan
 -->

**Comment by alalek** [comment]
Mixed usage of OpenCV 2.4.x and OpenCV 3.x is not supported/tested for now.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
