### ISSUE TITLE
Findcontours creates 'fuzzy' contours

### ISSUE THREAD

**Issue by martinrosevear** [opencv/opencv#8248]
I have some experience with findcontours() and OpenCV.  It largely works well and is used in an application that detects numerals on Athlete Bibs using real time images.  

However we have two issues (compiled using Library version 2413 and MSVC 2015):

1. Fuzz contours
x86 findcontours() + cvFindContours() routines create 'fuzzy' rather than 'smooth' contours around an apparently orthodox image (see 'Debug_FC disp.png' ![debug_fc disp](https://cloud.githubusercontent.com/assets/5932912/23245086/d0ea0406-f9ee-11e6-94b2-27f999675635.png).  As a result, separated components are identified as together when getting the bounding rectangle.  The cause eludes me.

2. Silent crash by findcontours() (not cvFindContours())
x64 findcontours() rarely and silently crashes with an assertion error in the calling routine for very rare images.  Replacing with cvFindContours() fixes that problem.  See image
![debug_contours_none](https://cloud.githubusercontent.com/assets/5932912/23245095/efa4b36e-f9ee-11e6-85be-24379ab38811.png).  

cvFindContours() has solved item 2 but a solution to item 1 eludes us.

Reliably detecting bounding rectangles (and rotated rectangles) around blobs are crucial to the app.  If possible, we wish to avoid a non-OpenCV approach to this issue.

**Comment by martinrosevear** [comment]
Attach input causing fuzzy contours:  ![debug_img for fc](https://cloud.githubusercontent.com/assets/5932912/23247316/34f0f78e-f9fe-11e6-8e47-d57691850bf0.png)

**Comment by martinrosevear** [comment]
Item 1 posted above has been solved!  Image needed thresholding after loading from JPG file.   

However item 2 is still outstanding, although not a priority, since cvFindContours solves it.

**Comment by alalek** [comment]
Could you add input image and used parameters (minimal reproducer) for findContours crash?

**Comment by martinrosevear** [comment]
Call as follows (using c++):

vector<vector<Point> > contours;
vector<Vec4i> hierarchy;
findContours(tmp, contours, hierarchy, CV_RETR_TREE, CHAIN_APPROX_NONE);

Changing the contour method to CHAIN_APPROX_SIMPLE stopped one crash but others.  

Last input image prior to crash:
![debug_crash input](https://cloud.githubusercontent.com/assets/5932912/23274773/cc98b2ba-fa68-11e6-9138-9fc9dbf0b126.png)
:
