### ISSUE TITLE
py-opencv 2.4.8 solvePnPRansac error

### ISSUE THREAD

**Issue by cfreundlich** [opencv/opencv#8251]
Hello,

I'm getting the following error while running the following function:

```
r, t, _ = cv2.solvePnPRansac(object_points, image_points, cam_mtx, dist_params)
```

```
cv2.error: /Users/jhelmus/anaconda/conda-bld/work/opencv-2.4.8/modules/calib3d/src/solvepnp.cpp:284: error: (-215) opoints.depth() == CV_32F in function solvePnPRansac
```

**Comment by alalek** [comment]
You should pass to functions agruments with supported types only.
Try existed OpenCV examples at first.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
