### ISSUE TITLE
Build fails with whitespaces in code

### ISSUE THREAD

**Issue by adl1995** [opencv/opencv#8259]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Ubuntu 14.04
- Compiler => g++

##### Detailed description

I made some changes in two C++ files (minor), but the build failed. It was pointed out by @alalek that trailing whitespaces aren't allowed in code.

I believe this should be fixed. 

##### Steps to reproduce

Review pull request.

**Comment by berak** [comment]
https://github.com/opencv/opencv/wiki/How_to_contribute#q3-i-was-asked-to-remove-whitespace-issues-how-can-i-do-that

**Comment by alalek** [comment]
@berak Thanks for the link!
