### ISSUE TITLE
TensorFlow example work in some PC and does not work in some other PC

### ISSUE THREAD

**Issue by pirahansiah** [opencv/opencv#8276]
I compile the latest version of OpenCV (GitHub) in two PC and run the TensorFlow example without any problem. Also, I clean install windows 10 without any cuda and compile OpenCV without change or modify anything in Cmake with visual studio 2017 and the tensorflow example work fine and give proper results. 
However, in some other PC the TensorFlow example give random result.

I tested with and without GPU
I tested compile and copy dll files
I tested with visual studio 2015 and 2017
I tested with windows 7 and windows 10

in all cases work in some PC and does not work in another.

**Comment by alalek** [comment]
DNN module issues should go here: https://github.com/opencv/opencv_contrib/issues

Please add into issue's description a minimal reproducer (with links to input data) and examples of expected/wrong results?

**Comment by alalek** [comment]
https://github.com/opencv/opencv_contrib/issues/1024
