### ISSUE TITLE
CV_XADD compile errors with Embarcadero C++ Builder 10.1

### ISSUE THREAD

**Issue by ville-v** [opencv/opencv#8278]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Embarcadero C++ Builder 10.1, Clang-based bcc32c compiler

##### Detailed description

In cvdef.h, the following line fails to compile for two reasons

 ```.cpp
#else
   CV_INLINE CV_XADD(int* addr, int delta) { int tmp = *addr; *addr += delta; return tmp; }
#endif
```

First is "[bcc32c Error] cvdef.h(442): C++ requires a type specifier for all declarations". Reason is the function has no return value, but it should return int.

Second is "[bcc32c Error] ptr.inl.hpp(67): no matching function for call to 'CV_XADD'"
"[bcc32c Hint] cvdef.h(442): candidate function not viable: no known conversion from 'unsigned int *' to 'int *' for 1st argument". The same error also occurs on line 72 in ptr.inl.hpp.

##### Steps to reproduce

1. Add OpenCV include file

 ```.cpp
#include <opencv2/core/core.hpp>
```

2. Try to compile

**Comment by alalek** [comment]
Could you try to add "int":
> CV_INLINE **int** CV_XADD(...)"

But using this branch you will compile thread **unsafe** code. Why `_MSC_VER` detection doesn't work?(your system is Windows - are you use cross-compilation?)

Could you dump used compiler defines? It is something like `clang -dM -E - < /dev/null`, but with OpenCV specific flags (see `make VERBOSE=1` or similar output).

Also you can try to use CMAKE_CXX_FLAGS and define your custom `CV_XADD` macro (be careful with spaces).


BTW, This platform is not supported officially. But we will accept reasonable patches, that don't break existed functionality.

**Comment by ville-v** [comment]
I can make this branch to compile by adding "int" as you suggested, and changing PtrOwner::refCount to int in ptr.inl.hpp. But this might be an imperfect fix. I don't know if there are other files that use CV_XADD with unsigned int.

**Comment by ville-v** [comment]
The command that should dump predefined macros does not seem to work this compiler. But the macros are listed in the documentation here: http://docwiki.embarcadero.com/RADStudio/Berlin/en/Predefined_Macros

Basically, the compiler defines __BORLANDC__ and __clang__, and does not define _MSC_VER.

**Comment by alalek** [comment]
Well, Could you try to change this [line](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/cvdef.h#L423):
```diff
- #elif defined __GNUC__
+ #elif defined __GNUC__ || defined __clang__
```

**Comment by ville-v** [comment]
That change fixes the issue.
