### ISSUE TITLE
fastmath.h related compile errors with Embarcadero C++ Builder 10.1

### ISSUE THREAD

**Issue by ville-v** [opencv/opencv#8280]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Embarcadero C++ Builder 10.1, Clang-based bcc32c compiler

##### Detailed description

When opencv is included, many places that use math functions are broken, with errors such as "[bcc32c Error] matx.hpp(854): no member named '_fm_sqrt' in namespace 'std'"
"[bcc32c Hint] fastmath.h(174): expanded from macro 'sqrt'".

This happens because of the following line in fast_math.hpp:

 ```.cpp
"#if defined __BORLANDC__
#  include <fastmath.h>"
```

At least in Embarcadero C++ Builder 10.1, fastmath.h (attached) is broken and effectively removes all math functions from std namespace.

[fastmath.h](https://github.com/opencv/opencv/files/803137/fastmath.h.txt)

##### Steps to reproduce

1. Add OpenCV include file

 ```.cpp
#include <opencv2/core/core.hpp>
```

2. Try to compile

**Comment by ville-v** [comment]
Proposed fix is to include fastmath.h only when __cplusplus is not defined.

**Comment by mshabunin** [comment]
@ville-v , feel free to propose a pull request with a workaround. We do not support C++ Builder, but if the fix does not break other compilers, we can integrate it.
