### ISSUE TITLE
ImportError: /usr/local/lib/libopencv_freetype.so.3.2: undefined symbol: hb_shape

### ISSUE THREAD

**Issue by riless** [opencv/opencv#8284]
After a fresh build of `opencv 3.2.0` with `contribs` I got the error on the title when I try to make an `import cv2` in `python`

Here are the flags I've built with in case of.

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D WITH_TBB=ON \
    -D BUILD_NEW_PYTHON_SUPPORT=ON \
    -D WITH_V4L=ON \
    -D BUILD_TIFF=ON \
    -D WITH_QT=ON \
    -D WITH_OPENGL=ON \
    -D BUILD_opencv_world=OFF \
    -D WITH_IPP=ON \
    -D INSTALL_CREATE_DISTRIB=ON \
    -D OPENCV_EXTRA_MODULES_PATH=/root/opencv_contrib-3.2.0/modules \
    -D BUILD_opencv_legacy=OFF .. && \
```

I've installed `libfreetype6-dev` using `apt-get` beforehand

I'm building `Opencv` inside a `Docker` with `ubuntu16.04`

**Comment by alalek** [comment]
There is the right link for contrib issues: https://github.com/opencv/opencv_contrib/issues

Current workaround is to disable freetype module (`cmake -DBUILD_opencv_freetype=OFF <...>`)
