### ISSUE TITLE
avira troyan alert "TR/Crypt.XPACH.Gen7" in file opencv_version.exe

### ISSUE THREAD

**Issue by thinkrapido** [opencv/opencv#8286]
just trying to build opencv and opencv_contrib on windows with visual studio 14.0
runing cmake version 3.7.2 and got the avira troyan alert.

is this a problem in opencv / opencv_contrib code which the algorithms of avira find or does my system have a problem?

What do you suggest?

these files are conterminated:

opencv_version.exe
opencv_waldboost_detector.exe
"Suspicious pattern found"

##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

opencv: commit 220d1f0b3e1bd03aa3d6e7518ef42a81b4e1592d
opencv_contrib: commit 53e34260b169f11d38d03266dd774b0595958a0e

Python 3.4.5 :: Anaconda 4.2.0 (64-bit)

Windows 7

**Comment by mshabunin** [comment]
Try to send suspicious files to https://www.virustotal.com/ and see the results. It can be false alarm or your system can be infected.

**Comment by thinkrapido** [comment]
seams to be a false positive
