### ISSUE TITLE
using yml models by multi threads

### ISSUE THREAD

**Issue by ahmadi219** [opencv/opencv#8291]
**Hi i'm using face Recognition.
want to run multi thread for multi face in a frame to make program in parallel form,
but i have problem in using yml models by multi threads,**

	        model= createLBPHFaceRecognizer();
		model->load("LBPHface.yml");
		cvWaitKey(1000000);
		model2= createLBPHFaceRecognizer();
		model2->load("LBPHface2.yml");

 **have error:**
File cant be opened for writing in cv:FacRecognizer::load

**please help me!!!**

**Comment by mshabunin** [comment]
@ahmadi219 , the _face_ module is from [opencv_contrib](https://github.com/opencv/opencv_contrib) repository and all related issues should be created there. Your code snippet does not illustrate the problem, there are no any threads and no one can run it to reproduce your issue.

Please, try to ask on the [forum](http://answers.opencv.org) first, if you receive no advice, then recreate the issue in the _opencv_contrib_ issue tracker with minimal complete application reproducing the problem and attach all related files if needed.
