### ISSUE TITLE
'opencv2/datasets/track_alov.hpp' file not found

### ISSUE THREAD

**Issue by kute** [opencv/opencv#8303]
/Users/kute/work/gitwork/opencv_contrib/modules/tracking/src/gtrUtils.hpp:7:10: fatal error:
      'opencv2/datasets/track_alov.hpp' file not found
#include <opencv2/datasets/track_alov.hpp>
         ^
1 error generated.
make[2]: *** [modules/tracking/CMakeFiles/opencv_tracking.dir/src/gtrTracker.cpp.o] Error 1
make[1]: *** [modules/tracking/CMakeFiles/opencv_tracking.dir/all] Error 2
make: *** [all] Error 2

Do i miss something ? the CMAKE command is below: 

cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=/Users/kute/work/gitwork/opencv_contrib/modules -DPYTHON3_LIBRARY=/Users/kute/anaconda3/lib/libpython3.5m.dylib -DPYTHON3_INCLUDE_DIR=Users/kute/anaconda3/include/python3.5m -DPYTHON3_EXECUTABLE=/Users/kute/anaconda3/bin/python3 -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=ON -DINSTALL_PYTHON_EXAMPLES=ON -DINSTALL_C_EXAMPLES=OFF -DBUILD_EXAMPLES=ON -D PYTHON3_NUMPY_INCLUDE_DIRS=/Users/kute/anaconda3/lib/python3.5/site-packages/numpy/core/include -D PYTHON3_PACKAGES_PATH=/Users/kute/anaconda3/lib/python3.5/site-packages -DCMAKE_OSX_ARCHITECTURES=x86_64 -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_text=OFF ..

i have tried many times to build and env is macOS sierra 10.12.3 and anaconda3(python3), anyone can help me, please? or show some tips on install-opencv3-with-python3

**Comment by alalek** [comment]
This is opencv_contrib problem, please open issue here: https://github.com/opencv/opencv_contrib/issues

Tracking code is not well guarded for optional `datasets` modules usage (`datasets` is optional for tracking, but it is automatically disabled, because "text modules" is disabled).

Current workaround: add `-DBUILD_opencv_tracking=OFF`.

**Comment by kute** [comment]
Thx. I will try again.

**Comment by basav1989** [comment]
-DBUILD_opencv_tracking=OFF worked for me too in a docker image.thanks.
