### ISSUE TITLE
confusion about Mat::data, datastart, dataend, datalimit, step

### ISSUE THREAD

**Issue by darkdragon-001** [opencv/opencv#8304]
Can somebody explain me the exact purpose of these member fields?

Since these members are neither well documented via Doxygen (see [member definitions](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.hpp#L1965) ) nor seems their purpose clear to other developers (see [code comments](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L839)).

**Comment by alalek** [comment]
Direct using of fields in well written code should be avoided, please use methods instead: `.ptr()`/`.at()` with `.step()`, `.elemSize()` methods. They are more safe and provide some useful checks in debug mode.

**Comment by darkdragon-001** [comment]
For my time critical application, I am using direct pointers for speed reasons.

Is my following interpretation correct?
![mat](https://cloud.githubusercontent.com/assets/177976/23500669/1fd4fa70-ff31-11e6-9c16-2da859b086b6.png)

**Comment by alalek** [comment]
datastart <= data <= dataend <= datalimit.
On this picture your should swap data <-> datastart.
datalimit is almost not used (and it may be located after the current "datalimit" pointer).
dataend should be placed on datalimit location. There is no field which points "on the end" of green region.

step[1] (which is step[dims-1]) is always equal to `sizeof(matrix element)` (CV_8U => 1, CV_32FC3 => 12).

See [locateROI() code](https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/matrix.cpp#L947).

BTW, There is good simple [example](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/mat.hpp#L698-L703) of efficient code.

**Comment by darkdragon-001** [comment]
So datalimit points to the end off allocated storage?

Does this picture now represent reality better?
![mat](https://cloud.githubusercontent.com/assets/177976/23508570/a7d18594-ff52-11e6-83b2-1557d5c3334e.png)

**Comment by alalek** [comment]
Based on [this code](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/mat.inl.hpp#L487-L488), `dataend` should be less or equal than `datalimit`.

On your picture there is missing "alignment area" on the right side (for example), that doesn't hold any matrix elements, but it aligns rows starting addresses. BTW, In general step[0] may be not divisible on element size.

`dataend` is located after last valid image byte. datalimit probably points to the end of allocated buffer (after "alignment area").

*I'm assume that green is Image ROI (region of interest), white cells are Image data (these values can be used too, for example in image filters for border values (if there is no `BORDER_ISOLATE` flag).*

**Comment by darkdragon-001** [comment]
In order to avoid confusion ([is it allocated space or not?](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L839)), I guess one should clearly define `datalimit` and document it directly in the code.

Is anything else missing in my image?

![mat](https://cloud.githubusercontent.com/assets/177976/23515664/29aa9778-ff6b-11e6-85bc-8d7d79a12d5b.png)

### Legend
_**white background:** alloated data  
**black border:** matrix elements  
**green background:** ROI_

### Data Types
_**pointers:** datastart, data, dataend, datalimit  
**size in bytes:** step  
**number of elements:** rows, cols_

**Comment by vpisarev** [comment]
ok, it can be closed, as it still can be referenced, even after being closed

**Comment by zengjie617789** [comment]
what about if the image has multi channel?
