### ISSUE TITLE
Python quit unexpectedly while using the libopencv_highgui.2.4.dylib plug-in

### ISSUE THREAD

**Issue by susanbhattarai** [opencv/opencv#8305]
##### System information (version)

- OpenCV => 2.4.13.2
- Operating System / Platform => OS X El Capitan
- Language: Python

##### Detailed description

OpenCv library with python client works perfectly for the image processing. However, it throws up error when I try to use VideoCapture method.

##### Steps to reproduce

 ```.py
import numpy as np
import cv2
import sys

cap = cv2.VideoCapture("peopleCounter.avi")

w = cap.get(3) #get width
h = cap.get(4) #get height

mx = int(w/2)
my = int(h/2)

count = 0
ret, frame = cap.read()
while(cap.isOpened()):
    ret, frame = cap.read() #read a frame
    try:
        count = count + 1
        text = "Hello World " + str(count)
        cv2.putText(frame, text ,(mx,my),cv2.FONT_HERSHEY_SIMPLEX
                    ,1,(255,255,255),1,cv2.LINE_AA)
        cv2.imshow('Frame',frame)
    except:
        #if there are no more frames to show...
        print('EOF')
        break

    #Abort and exit with 'Q' or ESC
    k = cv2.waitKey(1000) & 0xff
    if k == 27:
        break

cap.release() #release video file
cv2.destroyAllWindows() #close all openCV windows
````
##### Error messsage
<img width="1007" alt="screen shot 2017-03-02 at 3 44 18 am" src="https://cloud.githubusercontent.com/assets/15026232/23499735/4b2a807c-fefb-11e6-9854-e68f70e5031e.png">

**Comment by alalek** [comment]
Screenshots of errors with text messages are extremely useless in reports.
Please provide normal stack trace dump and OpenCV build configuration.

**Comment by susanbhattarai** [comment]
### Stack Trace
```
017-03-02 03:42:03.892 Python[52160:832502] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff869574f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff93262f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8686e7c5 -[__NSArrayM objectAtIndex:] + 245
	3   libopencv_highgui.2.4.dylib         0x000000010979c280 _ZN13CvCaptureFileC2EPKc + 350
	4   libopencv_highgui.2.4.dylib         0x000000010979acf2 _Z32cvCreateFileCapture_AVFoundationPKc + 34
	5   libopencv_highgui.2.4.dylib         0x000000010978e7ee cvCreateFileCapture + 14
	6   libopencv_highgui.2.4.dylib         0x000000010978ea9e _ZN2cv12VideoCapture4openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 64
	7   libopencv_highgui.2.4.dylib         0x000000010978e8fe _ZN2cv12VideoCaptureC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 42
	8   cv2.so                              0x0000000108f38bce _ZL34pyopencv_VideoCapture_VideoCaptureP7_objectS0_S0_ + 275
	9   Python                              0x000000010808aa0b PyEval_EvalFrameEx + 13400
	10  Python                              0x00000001080873c1 PyEval_EvalCodeEx + 1583
	11  Python                              0x0000000108086d8c PyEval_EvalCode + 54
	12  Python                              0x00000001080a6a42 PyParser_ASTFromFile + 300
	13  Python                              0x00000001080a6ae5 PyRun_FileExFlags + 133
	14  Python                              0x00000001080a6634 PyRun_SimpleFileExFlags + 698
	15  Python                              0x00000001080b8011 Py_Main + 3137
	16  libdyld.dylib                       0x00007fff982725ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by alalek** [comment]
Probably it fails on this line:
> https://github.com/opencv/opencv/blob/2.4.13.2/modules/highgui/src/cap_avfoundation_mac.mm#L700

BTW, Looks like ObjC exceptions are not catched at all by C++ code.

**Comment by sabzo** [comment]
@alalek I'm getting a similar error on 2.4.13.2

 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff82ed657b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00007fff9829a1da objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff82df30ab -[__NSArrayM objectAtIndex:] + 203
        3   libopencv_highgui.2.4.dylib         0x000000010bfe1709 _ZN13CvCaptureFileC2EPKc + 281
        4   libopencv_highgui.2.4.dylib         0x000000010bfe023e _Z32cvCreateFileCapture_AVFoundationPKc + 34
        5   libopencv_highgui.2.4.dylib         0x000000010bfd4afc cvCreateFileCapture + 14
        6   play_video                          0x000000010bb00e83 main + 99
        7   libdyld.dylib                       0x00007fff98b7b235 start + 1
        8   ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6


Here's my program:
``` c
#include "highgui.h"

int main( int argc, char** argv ) {
cvNamedWindow( “Example2”, CV_WINDOW_AUTOSIZE );
CvCapture* capture = cvCreateFileCapture( argv[1] );
IplImage* frame;
while(1) {
frame = cvQueryFrame( capture );
if( !frame ) break;
  cvShowImage( “Example2”, frame );
  char c = cvWaitKey(33);
  if( c == 27 ) break;
}
cvReleaseCapture( &capture );
cvDestroyWindow( “Example2” );
}
```

**Comment by alalek** [comment]
Could someone try patch like this ([here](https://github.com/opencv/opencv/blob/2.4.13.2/modules/highgui/src/cap_avfoundation_mac.mm#L700)):

```.diff
-    mAssetTrack = [[mAsset tracksWithMediaType: AVMediaTypeVideo][0] retain];
+    NSArray *tracks = [mAsset tracksWithMediaType:AVMediaTypeAudio];
+    if ([tracks count] == 0)
+    {
+        fprintf(stderr, "OpenCV: Couldn't read movie file \"%s\"\n", filename);
+        [localpool drain];
+        started = 0;
+        return;
+    }
+    
+    mAssetTrack = [tracks[0] retain];
```

**Comment by susanbhattarai** [comment]
@sabzo I really like your detailed investigation ranging from using C++, Python and C.  I should have done that when I filed the bug.

**Comment by sabzo** [comment]
@susanbhattarai Thanks! I wanted to make sure it wasn't because I was using some outdated library, since the C-API is more or less no longer being extended.

@alalek Your code fix worked! I compiled locally and ran my C && C++ examples ran without exception. I've included a PR. https://github.com/opencv/opencv/pull/8979

The python example I wrote played the video, but had a different error which isn't related to this fix:
```
opencv/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

**Comment by sabzo** [comment]
@susanbhattarai Your code by the way works [I ran it] with the changes in the above PR -- you just need to comment out this line `cv2.putText(frame, text ,(mx,my),cv2.FONT_HERSHEY_SIMPLEX
                   ,1,(255,255,255),1,cv2.LINE_AA)`

Reason is *cv2.LINE_AA* doesn't exist.

**Comment by susanbhattarai** [comment]
I started using my linux machine for doing this project since this bug was only on OSX machine.
Anyways, thanks @sabzo
