### ISSUE TITLE
OpenCV using C's math instead of C++'s cmath making build error

### ISSUE THREAD

**Issue by InfernoCoder** [opencv/opencv#8312]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Debian Stretch 64 Bit
- Compiler => GCC 6

##### Detailed description

I was building OpenCV when I got this error - `farneback_optical_flow.cpp:29:22: error: call of overloaded ‘abs(double&)’ is ambiguous`.

The fix was to add this `#include <cmath>` to the beginning of the file `farneback_optical_flow.cpp`.

##### Steps to reproduce

Build OpenCV with Examples and Tests.

**Comment by StevenPuttemans** [comment]
I am wondering where this sample/text is located. I did a search in the latest 3.2 branch, as well in the 2.4 branch and am unable to locate this file.

**Comment by StevenPuttemans** [comment]
Just pulled last master, did a complete build with tests and samples and works just fine... so I guess the issue is in using GCC6, because using GCC4.8 and GCC5 I get no issues.
