### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by bigdimboom** [opencv/opencv#8326]
![image](https://cloud.githubusercontent.com/assets/6119906/23634748/ee0d92f6-0299-11e7-9c81-f4926db58673.png)

New code 3.2 version does not support 4 channel color image detections. 3.1 does.

**Comment by alalek** [comment]
Workaround:
```
cvtColor(srcRGBA, srcGray, COLOR_RGBA2GRAY);
... use srcGray instead ...
```

**Comment by StevenPuttemans** [comment]
> 3.1 does.

Are you sure? I rather think, 3.1 did not do it correctly and therefore the extra check was added to avoid issues further down the pipeline.

**Comment by bigdimboom** [comment]
from 3.1
![image](https://cloud.githubusercontent.com/assets/6119906/23662312/2b679c86-031d-11e7-9df9-4a02f931f885.png)

**Comment by alalek** [comment]
Posting screenshots with text is extremely useless, especially in case of source code hosted on GitHub.

You should post this link instead: https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/calibinit.cpp#L264-L265

Feel free to provide patch with adding check for "ch == 4". cvtColor with BGR2GRAY will process it too (like BGRA2GRAY).
