### ISSUE TITLE
Load Numpy Array Binary Image with OpenCV detectMultiScale

### ISSUE THREAD

**Issue by Arbolista** [opencv/opencv#8329]
I have sequences of digits originally from Mnist data set that I've manipulated with OpenCV. They are saved in a pickle file. They are 1 channel images with shape (112, 112).

I want to run these through an OpenCV Cascade Classifier, similar to [the face detection tutorial](http://docs.opencv.org/trunk/d7/d8b/tutorial_py_face_detection.html), but instead with these [Google-Street-View-House-Numbers-Digit-Localization cascades](https://github.com/ankitdhall/Google-Street-View-House-Numbers-Digit-Localization).

Here is my attempt:

```py
    data = p.load_file('data/train_sequences00.pickle')
    zero = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade0/cascade.xml')
    one = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade1/cascade.xml')
    two = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade2/cascade.xml')
    three = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade3/cascade.xml')
    four = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade4/cascade.xml')
    five = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade5/cascade.xml')
    six = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade6/cascade.xml')
    seven = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade7/cascade.xml')
    eight = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade8/cascade.xml')
    nine = cv2.CascadeClassifier('data/Google-Street-View-House-Numbers-Digit-Localization/cascades/cascade9/cascade.xml')
    gray = np.array(data['sequences'][0]).astype(np.float32)
    gray = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
    #gray = cv2.cvtColor(img, cv2.CV_RGB2GRAY)
    
    zeros = zero.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    ones = one.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    twos = two.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    threes = three.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    fours = four.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    fives = five.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    sixes = size.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    sevens = seven.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    eights = eight.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    nines = nine.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
```

Unfortunately this just results in the following error:

```py
    Traceback (most recent call last):
      File "digit_cascade.py", line 22, in <module>
        zeros = zero.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)
    SystemError: error return without exception set
```

Is anyone familiar with how to load raw numpy arrays into OpenCV `detectMultiscale`?

Here are some uncertainties I have:

- The [docs](http://docs.opencv.org/2.4/modules/objdetect/doc/cascade_classification.html#cascadeclassifier-detectmultiscale) have two different signatures for `detectMultiscale`. What is the purpose of the first, with the arguments for `rejectLevels` and `levelWeights`?
- My images are 112x112. Each digit within this image would be around 11x11 pixels. The cascade sizes are 20x30. What parameter should I/ do I need to set in order for the cascades to work properly?

System info:

```py
>>> cv2.__version__  
'2.4.11'
>>> print(sys.version)
2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]
```

**Comment by StevenPuttemans** [comment]
Several issues

- You are trying to push float32 images into detectMultiScale, but it needs a 8bit grayscale image to start with
-  `112x112. Each digit within this image would be around 11x11 pixels. The cascade sizes are 20x30.` This will only work if you upscale your images significantly. Or if you train smaller models. The size of the model also gives you the smallest detection range.
- `What is the purpose of the first, with the arguments for rejectLevels and levelWeights?` There are actually 3 overload methods. The default one just returns detections, the one with the weights gives you the classification score at the final stage and the one with the number of detections gives you the number of non maxima surpressed boxes for a single location.

**Comment by alalek** [comment]
> scaleFactor=0.6

scaleFactor should be greater than 1.0.

> zero.detectMultiScale(gray, 1.3, 5, scaleFactor=0.6)

Probably 1.3 is scaleFactor value.
Try `help(zero.detectMultiScale)` python statement for assistance.

Try to run OpenCV's python tests, they contain ["facedetect" test](https://github.com/opencv/opencv/blob/master/modules/python/test/test_facedetect.py) with detectMultiScale call. [Test output example](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/10033/steps/test_python2-ippicv-opencl/logs/stdio).

**Comment by Arbolista** [comment]
Thanks @StevenPuttemans and @alalek these both helped. I also made a glaring oversight in my first statement above. My numpy arrays were `(112, 112)`, ie single channel and therefore no need to convert to gray scale. If I omit the `cvtColor` step above, `detectMultiscale` runs without issue, once I make the adjustments mentioned by @StevenPuttemans above.
