### ISSUE TITLE
VideoWriter libx264 memory leak

### ISSUE THREAD

**Issue by cedricve** [opencv/opencv#8330]
## System information (version)
OpenCV = master
Operating System / Platform = All platforms OSX, Raspberry Pi, etc
Compiler = XCode

## Detailed description

I've been noticing memory increasing while writing videos using x264 codec. Although I'm properly releasing the videowriter.

## Steps to reproduce

    m_codec = 0x00000021;//CV_FOURCC('H','2','6','4');
    m_writer = new cv::VideoWriter();
    m_writer->open(m_directory + m_fileName, m_codec, m_fps, cv::Size(image.getColumns(), image.getRows()));

    ...

    video->m_writer->write(video->m_mostRecentImage.getImage());
       
    ...
         
    if(video->m_writer)
    {
        if(video->m_writer->isOpened())
        {
            video->m_writer->release();
        }
        delete video->m_writer;
        video->m_writer = 0;
    }

## Profiler 

![screen shot 2017-03-06 at 23 17 15](https://cloud.githubusercontent.com/assets/1546779/23646137/c78f7902-030f-11e7-9473-c92f707024bc.png)
![screen shot 2017-03-06 at 23 16 56](https://cloud.githubusercontent.com/assets/1546779/23646138/c7937eb2-030f-11e7-9969-c70680122e09.png)

**Comment by mshabunin** [comment]
I was not able to reproduce it in Ubuntu with _opencv_test_videoio_.
Can you provide small standalone application which reproduces the issue? Please add more information about your FFMPEG and libx264 versions.

**Comment by cedricve** [comment]
@mshabunin the issue was related to another problem. I was creating pthreads with pthread_create, but never deattached the threads (by default they are joinable). Therefore some memory wasn't released properly..

I no longer have memory leaks.
