### ISSUE TITLE
[feature] RQDecomp3x3 C++ Signature Does not Take eulerAngles

### ISSUE THREAD

**Issue by cancan101** [opencv/opencv#8337]
The `RQDecomp3x3` C++ method does not take `eulerAngles`, whereas the c method does. (see: http://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html?highlight=decomposeprojectionmatrix#rqdecomp3x3)

**Comment by mshabunin** [comment]
In C - it is an optional output argument, C++ variant always returns `eulerAngles` as a return value:
```.cpp
eulerAngles = RQDecomp3x3(...);
```

Please ask usage questions on the user forum: http://answers.opencv.org

**Comment by cancan101** [comment]
@mshabunin I am looking at the code [here](https://github.com/opencv/opencv/blob/090c46eca24b61a6da152aa6ff1205176dc77868/modules/calib3d/src/calibration.cpp#L3646): and it looks like the in the C++ implementation, eulerangles are allocated internally and then passed to the C implementation:
```c++
Vec3d eulerAngles;
...
cvRQDecomp3x3(&matM, &matR, &matQ, pQx, pQy, pQz, (CvPoint3D64f*)&eulerAngles[0]);
```
So I don't think this is a usage question.

**Comment by mshabunin** [comment]
@cancan101 , is there any problem with this code? What is the motivation of this feature request?
It is still not clear, please add more details to the description.
