### ISSUE TITLE
What does the following error message mean?

### ISSUE THREAD

**Issue by yxchng** [opencv/opencv#8339]
OpenCV Error: Assertion failed (image->depth == 8) in writeFrame, file /home/yxchng/OpenCV/modules/videoio/src/cap_ffmpeg.cpp, line 272

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

This assertion is a check for supported data types. It means that data should be `uchar`-based.
