### ISSUE TITLE
Why are dependencies like libjpeg not included in opencv_world?

### ISSUE THREAD

**Issue by Overv** [opencv/opencv#8340]
The `opencv_world` supermodule was introduced in 2012 to allow linking all of the OpenCV modules at once, but one still needs to separately link many common dependencies like `IlmImf`, `libtiff`, `libjpeg` and `libpng`.

Is this a license issue or is there a different reason that these are not included in `opencv_world` or some `opencv_world_and_dependencies` supermodule?

**Comment by Overv** [comment]
How is this an invalid question?

**Comment by alalek** [comment]
> still needs to separately link many common dependencies

`opencv_world<ver>.dll` doesn't require additional dependencies if these dependencies are built as static libraries (they are linked into this DLL) - it is OpenCV default mode.

This tracker is for issues and bugs that needs fix in OpenCV. Usage/build questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by aCuria** [comment]
I don't think the question is invalid.
When opencv is compiled with SHARED_LIBS=OFF and OPENCV_WORLD=ON, logically, there should be only one .lib to link. However, this is not the case.

SHARED_LIBS = ON or OFF should only change whether a dll is produced or not. If the number of .libs produced changes as well, isnt this a bug?
