### ISSUE TITLE
how to build opencv_contrib for andoid with opencv320 together and contain tracking KCF algorithms

### ISSUE THREAD

**Issue by xiaopengs** [opencv/opencv#8343]
Hi

I am trying to run KCF on Android 6.0. at present I can build opencv for android on windows with androidstudio , but I cannot build opencv_contrib for android with opencv3.2.0 together. Can you kindly tell me how to do that?

Best Regards,
xiaopengs

- OpenCV => 3.2.0
- Operating System / Platform => Windows 64 Bit
- Compiler => NDK  Androidstudio2.3

**Comment by wind1096471134** [comment]
Me too.

**Comment by alalek** [comment]
Android Studio support suggestions are here: #5003

You can check build commands [on this Android SDK builder](http://pullrequest.opencv.org/buildbot/builders/master-contrib_pack-contrib-android/builds/10036) (Linux based)

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by bnhc** [comment]
Hello,I also want using opencv_contrib tracking module on Android platform.But i had tred many coures from Baidu and google .they're not work well.Problem always appear on Cmake Compiling.Did you get it sucessfully ?
