### ISSUE TITLE
Having out of memory problem in opencv (python)

### ISSUE THREAD

**Issue by Cienlim612** [opencv/opencv#8349]
I have type few lines of code in python to open image through openCV. When I want to read a image file, I get the following error.

**OpenCV Error: Insufficient memory (Failed to allocate 192000004 bytes) in cv::OutOfMemoryError, file ..\..\..\..\opencv\modules\core\src\alloc.cpp, line 52
Traceback (most recent call last):
  File "C:/Users/cienl/Desktop/Python/SIFT.py", line 10, in <module>
    kp = sift.detect(gray,None)
cv2.error: ..\..\..\..\opencv\modules\core\src\alloc.cpp:52: error: (-4) Failed to allocate 192000004 bytes in function cv::OutOfMemoryError**

I think is because the image size is too big, which is 4.3 mb. How can I solve this problem?

**Comment by alalek** [comment]
> When want to read a image file, I get the following error

> kp = sift.detect(gray,None)

This description is wrong and important details are missing.

Try to adjust parameters and/or resize image before processing.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

if you believe this is a bug, then provide evidences with complete reproducer code and input image.

**Comment by Cienlim612** [comment]
I am sorry for that. I resize is the the only way I can fix the problem now. Thanks for the clue. It works
