### ISSUE TITLE
Visual Studio 2008 Compile Errors for *.cl files / cuda headers / intrinsics (NEON, SSE)

### ISSUE THREAD

**Issue by Mikaso** [opencv/opencv#8350]
##### System information (version)
- OpenCV => 3.2.0 released this on 23 Dec 2016 and OpenCV 3.2.0 master branch of 09 Mar 2017
- Operating System / Platform => Windows 10 Professional 64 bit / Windows 7 professional 64 bit
- Compiler => Microsoft Visual Studio 2008 SP1 x86
- Generator => CMake 3.1.3

##### Detailed description

I encounter a lot of opencl and cuda compile errors while compiling opencv_core although **WITH_OPENCL** and **WITH_CUDA** are being **deactivated** in CMake. 
A complete error list can be found here: [VC9CompileErrors.txt](https://github.com/opencv/opencv/files/833416/VC9CompileErrors.txt)

##### Steps to reproduce

See the CMake Configuration and CMakeCache.txt attached to recreate the vc9 project files:
[https://github.com/opencv/opencv/files/833413/OpenCVCmakeConfiguration.txt](https://github.com/opencv/opencv/files/833413/OpenCVCmakeConfiguration.txt)
[https://github.com/opencv/opencv/files/833412/CMakeCache.txt](https://github.com/opencv/opencv/files/833412/CMakeCache.txt)

**Comment by alalek** [comment]
CMake stdout shows that your build configuration is not clean. Try to build from scratch (clean build directory).
Also try to use older CMake (like 2.8.12).

**Comment by Mikaso** [comment]
Unfortunately, using CMake 2.8.12 did not help. The same errors still persist. 
Why do you think the build configuration is not clean? Can you point it out?

**Comment by alalek** [comment]
Because clean CMake configuration log [starts from compiler detection lines](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10037/steps/cmake/logs/stdio).

**Comment by Mikaso** [comment]
I see. Yes i did set some variables to set paths to existing libs / include dirs. 
I tried a clean configure and build and it did not compile either:
[CmakeCleanConfigure.txt](https://github.com/opencv/opencv/files/833979/CmakeCleanConfigure.txt)
[CMakeCache.txt](https://github.com/opencv/opencv/files/833978/CMakeCache.txt)
[VC9CompileErrorsCMakeClean.txt](https://github.com/opencv/opencv/files/833980/VC9CompileErrorsCMakeClean.txt)

**Comment by alalek** [comment]
There is no support for MSVS2008 in OpenCV for many years (official support was ended with release of MSVS2012 - ~5 years ago). So it is better to use modern compiler instead.

You can try another generator which is more compatible with old MSVS project files: nmake or ninja. Probably MSVS generator is broken in modern CMake versions or some features are missing. For some reason it tries to compile .cl files, but these files are used by custom step only.

Also it tries to compile all header files, like platform ios.h written on Obj-C

Anyway MSVS2008 will not able to compile OpenCV C++ code. There are a lot of errors due incompatible STL implementation, like these:
```
test_io.cpp(693) : error C2039: 'data': Ist kein Element von 'std::vector<_Ty>'
drawing.cpp(1026) : error C2668: 'std::abs': Mehrdeutiger Aufruf einer überladenen Funktion
```

**Comment by Mikaso** [comment]
I successfully compiled opencv 3.1 for visual studio 2008 applying some changes. data and abs are easy to resolve. the only problem I'm facing right now is all the errors occuring by trying to compile the *.cl etc files.
