### ISSUE TITLE
New Feature: Anisotropic Diffusion

### ISSUE THREAD

**Issue by sav-chris** [opencv/opencv#8361]
I have implemented a new feature and will submit a pull request

Anisotropic Diffusion
https://en.wikipedia.org/wiki/Anisotropic_diffusion 

The original paper describing the algorithm can be found here 
http://image.diku.dk/imagecanon/material/PeronaMalik1990.pdf 

An example implementation can be found here 
https://au.mathworks.com/matlabcentral/fileexchange/14995-anisotropic-diffusion--perona---malik-/content/anisodiff_Perona-Malik/anisodiff2D.m 

Some examples of images processed with the algorithm can be found here  
https://reference.wolfram.com/language/ref/PeronaMalikFilter.html

**Comment by sav-chris** [comment]
The instructions at https://github.com/opencv/opencv/wiki/How_to_contribute 
mention a pre-commit.sample file but I am not sure where to find it.
It does not appear to be in the folder opencv/.git/hooks/ 
I can't seem to find any file by this name in the repository

**Comment by alalek** [comment]
This file is not in the repository. It is "git" configuration file, stored locally only (probably ".git" subfolder is hidden on your machine).
You can just skip this step, it is not required.

**Comment by StevenPuttemans** [comment]
Nice additionele!

**Comment by pmoulon** [comment]
Does this feature is not already implemented in AKAZE?
It would be nice to factorize the code.

**Comment by sturkmen72** [comment]
Merged in contrib module

**Comment by pmoulon** [comment]
Any commit id or link to your commits?

**Comment by sturkmen72** [comment]
https://github.com/opencv/opencv_contrib/pull/1176
