### ISSUE TITLE
VideoCapture read() decodes the same frame differently if ran twice in the same process

### ISSUE THREAD

**Issue by aittalam** [opencv/opencv#8366]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Linux
- Compiler => gcc

##### Detailed description

Using OpenCV/python to decode an h264 video file, when I capture the same frame from the same file using two different VideoCapture objects in the same process, I get two different frames (see image). This happens to every subsequent object I create within the same process (e.g. same kernel in a jupyter notebook). When I re-run the process (or restart the jupyter kernel) everything is consistent with the very first video capture.

The following simple code reads what should be the same frame in two variables (fr1 and fr2) which, when compared, show a difference (see image) which looks like a decoding error / memory leak. Note that the problem occurs also when I open different files (copies of the same video) and when I read a whole file, release the first VideoCapture object, and only then create the second one. 

```.python
vc1 = cv2.VideoCapture(video_filename)
vc2 = cv2.VideoCapture(video_filename)
_, fr1 = vc1.read()
_, fr2 = vc2.read()
compare_frames(fr1,fr2)
```

![download](https://cloud.githubusercontent.com/assets/4476645/23836478/3b689df0-0779-11e7-86fb-590ce1636bd4.png)

I have tested the same code with 720p and 480p videos and the error only occurs with 480p. The "noise" always appears located in the rightmost strip of pixels (last 6) and is constant (i.e. if I alternatingly read frames from the two copies of the same video, they will always have the same noise present).

Is there anything else I could test to spot where the issue could be? Is it something related to opencv itself or to a lower-level decoding layer?

**Comment by alalek** [comment]
Try to get code from master branch of OpenCV (or at least OpenCV 3.2).
Try fresh ffmpeg version too.

There were some fixes to ffmpeg support code about unaligned data processing, so I'm not sure that this is your case (480p should be aligned).

Unfortunately, we are not able to reproduce this issue on our side - so we can't help a lot here.

**Comment by aittalam** [comment]
Thanks a lot Alalek, I tried with OpenCV 3.2.0 and it works properly. Actually I had to work on a new machine and ffmpeg is (slightly) more recent too, so I will run proper testing and let you know which of the two solved the issue.
