### ISSUE TITLE
Strange behaviour of multiply 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8385]
##### System information (version)
- OpenCV => 3.2-dev
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

My program is 

```
        Mat x(1, 2, CV_8UC1, Scalar::all(3)),y;
        cout<<x<<"\n";
        add(x, 2.0, x);
        cout << x << "\n";
        multiply(x, 2.1, y, 1, CV_32F);
        cout << y << "\n";
        multiply(x, x, x,1,CV_16UC1); // Line A to change
        cout << x << "\n";

```
results: 
[  3,   3]
[  5,   5]
[10.5, 10.5]
[42025, 42025] : why? 

Now instead of A I write
`multiply(x, x, x);`

[  3,   3]
[  5,   5]
[10.5, 10.5]
[ 25,  25] OK

instead of A I write 
`multiply(x, 2.1, x, 1, CV_32F);`

 results are
[  3,   3]
[  5,   5]
[10.5, 10.5]
[430.5, 430.5]

May be a clone is missing or an exception must be thrown when dts=src but type is changed

**Comment by alalek** [comment]
Support for inplace parameters has some limitations. Current limitation works with the same size / the same type of src and dst matrix. Because any reallocation of dst will broke "inplaced" src in general.
There are only few algorithms that are inplace-safe, cvtColor has some fixes for this.
See #8352 #8341 #8149

**Comment by LaurentBerger** [comment]
Is it possible to insert something like this ?
CV_Assert(src1.getObj() != dst.getObj() || type==-1);

**Comment by raghav9-97** [comment]
I tried it out on OpenCV 3.3.0 and got results as follows when src=dst but type is changed to CV_32F
[ 3, 3]
[5, 5]
[10.5, 10.5]
[ 0, 0]
Is the bug fixed or it should throw an exception on encountering this situation?

**Comment by aleksey-nikolaev** [comment]
Something wrong in https://github.com/opencv/opencv/blob/master/modules/core/src/matmul.cpp#L1558
This assert didn't rise even if I tried something like this `(cv::Mat_<double>)A * (cv::Mat_<int>)B`. In this case exception from cv::hal::gemm64f was rise. But if I try `(cv::Mat_<float>)A * (cv::Mat_<int>)B` - no exception and result is an uninitialized matrix (but correct size for result of A * B)
