### ISSUE TITLE
Compiling OpenCV with NVCUVID

### ISSUE THREAD

**Issue by ccpak** [opencv/opencv#8390]
Can't get opencv to compile with NVCUVID support. 

cmake flags used to compile source

cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=ON -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON  -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_OPENMP=ON -D WITH_IPP=ON  -D WITH_NVCUVID=ON -D WITH_CUDA=ON -D WITH_CSTRIPES=ON -D WITH_OPENCL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=ON -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" ..   

 NVIDIA CUDA
--     Use CUFFT:                   YES
--     Use CUBLAS:                  YES
--     USE NVCUVID:                 NO
--     NVIDIA GPU arch:             20 30 35 37 50 52 60 61
--     NVIDIA PTX archs:
--     Use fast math:               YES
--

**Comment by alalek** [comment]
CUDA version?

**Comment by ccpak** [comment]
8.0

**Comment by alalek** [comment]
CUDA 8.0 is moved to new API: https://developer.nvidia.com/nvidia-video-codec-sdk
