### ISSUE TITLE
Unable to build OpenCV 3.2.0 on Visual Studio 2008

### ISSUE THREAD

**Issue by jakirkham** [opencv/opencv#8394]
Running into an issue building OpenCV 3.2.0 on Windows with Visual Studio 2008. Would note this is the Visual Studio one is required to use when building extensions for Python 2.7 on Windows (see ref below).

It appears C++11 features are (accidentally?) used. Here is a snippet of the error I'm seeing. A reference to the log is shown below. Also a reference to PR containing the build script. Can provide more details if interested. FWIW this appears to be the [line]( https://github.com/opencv/opencv/blob/3.2.0/modules/core/src/persistence.cpp#L1386 ) in question.

```cpp
[ 25%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/persistence.cpp.obj
persistence.cpp
C:\bld\opencv_1489524730194\work\opencv-3.2.0\modules\core\src\persistence.cpp(1386) : error C2039: 'front' : is not a member of 'std::basic_string<_Elem,_Traits,_Ax>'
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>,
            _Ax=std::allocator<char>
        ]
```

ref: https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F
ref: https://ci.appveyor.com/project/conda-forge/opencv-feedstock/build/1.0.142/job/dor4de6hq6rdr2wl
xref: https://github.com/conda-forge/opencv-feedstock/pull/58

**Comment by alalek** [comment]
C++11 features are used by [this external patch](https://github.com/conda-forge/opencv-feedstock/pull/58/commits/a5c1d2bef878680ef5f9ed5d01c941f224930163#diff-8abf99999270ba72b0de527f4caf9d05R8). Original OpenCV code seems good here.

`std::string::data()` is valid for C++98: http://www.cplusplus.com/reference/string/string/data/

**Comment by jakirkham** [comment]
You are right. Came to the same conclusion after digging into that PR more.

That said, that patch is being applied because the existing code is a problem on MSVC 2008. We need a similar fix for all these lines equivalent to the fix added in this PR ( https://github.com/opencv/opencv/pull/5881 ) as using `data` doesn't seem to work with MSVC 2008. Also please see issue ( https://github.com/opencv/opencv/issues/5878 ) for a similar failure.

**Comment by jakirkham** [comment]
Would you rather I open a new issue for that problem or should we keep it here?

**Comment by alalek** [comment]
Mentioned problem is related to `std::vector::data()`, which is C++11 feature and doesn't exist in C++98: http://www.cplusplus.com/reference/vector/vector/data/ .

Anyway, compilation with MSVS2008 is not officially supported by OpenCV dev team.

**Comment by alalek** [comment]
IMHO, it is better for `std::string` to use `str.c_str()` instead of `&(str[0])`

**Comment by jakirkham** [comment]
> Anyway, compilation with MSVS2008 is not officially supported by OpenCV dev team.

Again Visual Studio 2008 is [required]( https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F ) for Python 2.7 support on Windows. So if you are saying Visual Studio 2008 is not supported, are you also saying Python 2.7 is not supported?

**Comment by jakirkham** [comment]
In any event, as the problem behind this issue arose from our patches, am going to close this out. Thanks for your help, @alalek.

**Comment by jakirkham** [comment]
Discussion on VS 2008 support continuing in issue ( https://github.com/opencv/opencv/issues/8481 ).
