### ISSUE TITLE
not compiling with make command

### ISSUE THREAD

**Issue by afarboodi** [opencv/opencv#8395]
hi, i was trying to install opencv when i just encountered to the following error:
![first](https://cloud.githubusercontent.com/assets/10324969/23963427/808beaf0-09c6-11e7-80a1-945e07aa753b.png)
![second](https://cloud.githubusercontent.com/assets/10324969/23963446/8ef832f6-09c6-11e7-9d4e-c014039928d8.png)
I have separately used mutex or thread and it was working but it didn't when i was compiling with:
make -j5
command
Regards,
Amirali

**Comment by alalek** [comment]
Posting screenshots with text is extremely useless.
Also there is no useful information how to reproduce this problem.
