### ISSUE TITLE
Why the python code rans well in Pycharm but report error in ubuntu terminal-imgwarp.cpp:1824: error: (-215) ssize.area() > 0 in function resize

### ISSUE THREAD

**Issue by MingCHEN-Github** [opencv/opencv#8403]
My python code rans well in Pycharm but it reports error "error: (-215) ssize.area() > 0 in function resize" when I ran it in Ubuntu terminal with `python` command. In terminal it reports:

    python /home/mingchen/PycharmProjects/tf_pic_auto/src/tfcnn_idenpic_main.py 
    OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/imgwarp.cpp, line 1824
    Traceback (most recent call last):
      File "/home/mingchen/PycharmProjects/tf_pic_auto/src/tfcnn_idenpic_main.py", line 53, in <module>
        tf.app.run()    #process the flag and then run main()
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
        sys.exit(main(sys.argv[:1] + flags_passthrough))
      File "/home/mingchen/PycharmProjects/tf_pic_auto/src/tfcnn_idenpic_main.py", line 24, in main
        pic_con_bin.convert(image)
      File "/home/mingchen/PycharmProjects/tf_pic_auto/src/pic_con_bin.py", line 12, in convert
        img = cv2.resize(img, (28,28),interpolation=cv2.INTER_CUBIC)
    cv2.error: /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/imgwarp.cpp:1824: error: (-215) ssize.area() > 0 in function resize

When I ran in Pycharm,the console shows:

 

       /usr/bin/python2.7 /home/mingchen/PycharmProjects/tf_pic_auto/src/tfcnn_idenpic_main.py
    The test_gray.bin file is OK！
    WARNING:tensorflow:From /home/mingchen/PycharmProjects/tf_pic_auto/src/cnn_iden_pic.py:109 in run_training.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
    Instructions for updating:
    Use `tf.global_variables_initializer` instead.
    CNN identified the number:9
    --------------------------------------------------
    The process time: 0:00:01.489337

The source python code that reports error is:

        img = cv2.resize(img, (28,28),interpolation=cv2.INTER_CUBIC)
The related code files are: 

     image = cv2.imread("write_num/test0.png",cv2.IMREAD_GRAYSCALE)  #written images
     pic_con_bin.convert(image)

The function "convert(image)" I call is in the following:

    #coding=utf-8
    '''  
    Using OpenCv to read images and save them to binary format
    '''
    import cv2
    
    def convert (img):
    
       # Change the size of images to 28*28
        img = cv2.resize(img, (28,28),interpolation=cv2.INTER_CUBIC)
        rows = 28  
        cols = 28  
    
     
        # change images to binary format
        fileSave = open('test_gray.bin','wb')
        for step1 in range(0, rows):
            for step2 in range(0, cols):
                fileSave.write(img[step1,step2])
        fileSave.close()
        print 'The test_gray.bin file is OK！'

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

This error message usually means that your source image is empty. For example, your imread() call is failed:
- wrong path to image
- missing codecs
