### ISSUE TITLE
performance drop issue

### ISSUE THREAD

**Issue by laohumultimedia** [opencv/opencv#8405]
I used cv::remap function in a loop and found it runs slower and slower.  Then i search the forum, and found the same topic:
http://answers.opencv.org/question/134259/opencl-computation-time-increases-after-few-iterations/.
The difference is that i didn't use OpenCL remap(i use cpu version), but faces the same issue.  Is this a bug  or the limitation of remap function ?

**Comment by alalek** [comment]
Probably OpenCL remap has asynchronous computation pattern (like many OpenCL functions). So time measurement is wrong in the mentioned sample: `clFinish()`/`ocl::finish()` call is required at least, but actual applications have synchronization point during fetching data from OpenCL (via `getMat()` or similar).
About CPU version: please provide a complete reproducer and expected/actual numbers.

**Comment by laohumultimedia** [comment]
I use opencv 3.2, with ipp, tbb, no Cuda, no Openvx, no OpenCL.
I run on Mac mini, OS X EI Capitan, Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
My main function is calling cv::remap in a loop. like this
for(i : 4000) {
cputick1()
cv::remap()
cputick2()
}
so the elapsed time is cputick2() - cputick1(), i believe the calculation happened at synchronization point.

**Comment by alalek** [comment]
This time measurement pattern is wrong for OpenCL-based processing. You need to add synchronization point (like `ocl::finish()`).
Please use performance tests instead of custom and incomplete code.

**Comment by laohumultimedia** [comment]
the question is i didn't use OpenCL. Does't the cpu version needs a finish() or flush() ?

**Comment by alalek** [comment]
It is for OpenCL only.

What is about OpenCV performance tests for remap? If performance samples are unstable then performance framework will warn about this.

P.S. We need a minimal reproducer - it is very hard to find and fix problem without it. Also we need input data (remap maps at least).

**Comment by laohumultimedia** [comment]
Thanks alelek.  I wrote a test program, and found the performance is stable indeed. And the performance drop is caused by encoding module.
