### ISSUE TITLE
ts module not installed

### ISSUE THREAD

**Issue by adinriv** [opencv/opencv#8408]
##### System information (version)

- OpenCV => 3.2.0-rc (from source)
- Operating System / Platform => Ubuntu 16.10
- Compiler => gcc 6.2.0

##### Detailed description

I'm trying to use the `ts` module in projects to use the same test functionalities as OpenCV. When I build OpenCV with  either

```cmake 
  -D BUILD_TESTS=ON 
  -D BUILD_PERF_TESTS=ON 
  -D BUILD_opencv_ts=ON 
```

I see that the `ts` module is listed among the modules to built. However, it is never installed (not sure if that is intended).

The library is created (although statically, regardless of `BUILD_SHARED_LIBS=ON`), but not installed, and not findable by `cmake`, for example.

##### Steps to reproduce

```
cmake \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D ENABLE_PRECOMPILED_HEADERS=OFF \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
  -D BUILD_NEW_PYTHON_SUPPORT=ON \
  -D WITH_TBB=ON \
  -D WITH_QT=ON \
  -D WITH_OPENGL=ON \
  -D BUILD_TIFF=ON \
  -D BUILD_SHARED_LIBS=ON \
  -D BUILD_EXAMPLES=ON \
  -D BUILD_opencv_ts=ON \
  ..

make -j $(nproc)
sudo make install
```

Then try to use it, for example with `cmake`

```
find_package ( OpenCV REQUIRED ts )
```

fails to find the `ts` library.

#### Related questions

Already ask for help before posting, [in here](http://answers.opencv.org/question/134337/missing-ts-from-release-build/). However, we couldn't find a problem.

**Comment by alalek** [comment]
"ts" is internal module, it is not designed for using it externally - so it was removed from regular public modules list.
You may consider [opencv_contrib](https://github.com/opencv/opencv_contrib) approach of developing OpenCV external modules. (`-DOPENCV_EXTRA_MODULES_PATH=path1\;path2` - note on backslash before `;`, required by "bash").

**Comment by adinriv** [comment]
@alalek  I try your suggestion but it gives an error about a duplicate module

    CMake Error at cmake/OpenCVModule.cmake:268 (message):
      The directory /home/user/bin/opencv/modules/ts is observed for OpenCV
      modules second time.
    Call Stack (most recent call first):
      modules/CMakeLists.txt:7 (ocv_glob_modules)

That means that the `ts` module is duplicated when trying to build it, right?

I'm using a similar setup as your suggestion:

    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules\;../modules/ts

**Comment by alalek** [comment]
My suggestion is to wrap your code into OpenCV module(s). It this case, OpenCV tests infrastructure will be available.

**Comment by adinriv** [comment]
Ok, I understand now. Quick question regarding that, can I wrap it in a module and build it without rebuilding OpenCV? Every time I wanted to build the module I need to rebuild the whole thing, right?

Is there an easy way to change the makefiles to include `ts` as an external module?

**Comment by alalek** [comment]
Try to remove INTERNAL [here](https://github.com/opencv/opencv/blob/3.2.0/modules/ts/CMakeLists.txt#L19) and probably comment [these two lines](https://github.com/opencv/opencv/blob/3.2.0/modules/ts/CMakeLists.txt#L7-L8).

**Comment by Mingli-Yu** [comment]
I use the opencv 4.3.0, but the ts module still isn't installed, is it normal?

**Comment by mshabunin** [comment]
It is normal, `ts` is not meant to be installed. You can port mentioned commit to the latest _master_ branch, there should not be problems as the changes are quite small.
