### ISSUE TITLE
Recipe for target error XXX failed with CUDA 8.0 and opencv3.2

### ISSUE THREAD

**Issue by Cadmium-CD** [opencv/opencv#8409]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04
- Compiler => make

##### Detailed description

 
- I follow the instruction in opencv.org for linux
- When I did cmake -D CMAKE_BUILD_TYPE=Release/Debug -D CMAKE_INSTALL_PREFIX=/usr/local .. it worked well
- Then I use make VERBOSE=1, I got the following two errors.

1.nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
2.[opencv-error.txt](https://github.com/opencv/opencv/files/850978/opencv-error.txt)

##### Steps to reproduce

-Almost the same with the instruction in opencv.org, except for the part of ippicv_linux_20151201.tgz, I downloaded it by myself.

**Comment by alalek** [comment]
> /home/cadmium/opencv-3.2.0/build/modules/java/pure_test/.build/ant-Release/Debug.properties: Directory nonexistent

You should build from scratch (clean build directory).

We [can't reproduce](http://pullrequest.opencv.org/buildbot/builders/precommit_cuda_linux64/builds/10022) this issue ([search](http://pullrequest.opencv.org/buildbot/builders/precommit_cuda_linux64/builds/10022/steps/compile%20release/logs/stdio) for "opencv_test_java_properties" step).

**Comment by Cadmium-CD** [comment]
@alalek  I downloaded the master branch and built it from scratch,  no error message appears. Thank you so much.

**Comment by jijaya** [comment]
i have the same issu pls help use ubunto 16.04
