### ISSUE TITLE
cv::ximgproc::weightedMedianFilter fails with mask containing 0's

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv#8414]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Mac OS X 64 Bit
- Compiler => Apple Clang

##### Detailed description

The function cv::ximgproc::weightedMedianFilter is happy only when the mask contains all non-zeros. I believe this is inherent to the implementation and has nothing to do with system parameters. Also note that this function might be better off as a class - fewer memory allocations, de-allocations. 

##### Steps to reproduce

 Use this function with any mask containing zeros.

**Comment by llschloesser** [comment]
Whoops, maybe this should be filed under opencv_contrib?

**Comment by sovrasov** [comment]
Yes, it should be in contrib.
