### ISSUE TITLE
Missing shape match methods in python bindings

### ISSUE THREAD

**Issue by pevogam** [opencv/opencv#8420]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Fedora 25 64 Bit

##### Detailed description

I cannot find anywhere the enumerable for shape comparison methods. The newest documentation for 3.1 does not point to a different place than `cv2` which is where I would expect to find it.

##### Steps to reproduce

```.py
# extract two contours
cv2.matchShapes(hcontour, ncontour, cv2.CV_CONTOURS_MATCH_I1)
# or analogically
cv2.matchShapes(hcontour, ncontour, cv2.CONTOURS_MATCH_I1)
```

**Comment by berak** [comment]
your flags simply do not exist, there is no L1 norm for template matching.

please [have a look at the tutorial](http://docs.opencv.org/master/d4/dc6/tutorial_py_template_matching.html) , valid values would be:

    'cv2.TM_CCOEFF', 'cv2.TM_CCOEFF_NORMED', 'cv2.TM_CCORR',
    'cv2.TM_CCORR_NORMED', 'cv2.TM_SQDIFF', 'cv2.TM_SQDIFF_NORMED'

then, this is not a library bug, please ask similar questions on http://answers.opencv.org

**Comment by berak** [comment]
indeed, there is only a [c-api version](https://github.com/opencv/opencv/blob/master/modules/imgproc/include/opencv2/imgproc/types_c.h#L512) of it, so the python wrappers could not pick them up.
