### ISSUE TITLE
Book feature on opencv.org/books.html

### ISSUE THREAD

**Issue by packtpartner** [opencv/opencv#8427]
##### Detailed description

Where do I create a PR to feature books on http://opencv.org/books.html ?

**Comment by mshabunin** [comment]
@packtpartner , we will create corresponding repository this week, I will post a link here.

**Comment by mshabunin** [comment]
@packtpartner , you can create PR or an issue in the https://github.com/opencv-infrastructure/opencv.org repository.

The ["Books"](http://opencv.org/books.html) page is generated from the [_data/books.yml](https://github.com/opencv-infrastructure/opencv.org/blob/master/_data/books.yml) file. And its layout is described in the [books.html](https://github.com/opencv-infrastructure/opencv.org/blob/master/books.html) file.
