### ISSUE TITLE
An error in the contours hierarchy tutorial for python

### ISSUE THREAD

**Issue by sxldvd** [opencv/opencv#8431]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04

##### Detailed description

In the following tutorial about Contours Hierarchy: http://docs.opencv.org/trunk/d9/d8b/tutorial_py_contours_hierarchy.html, in the "Contour retreival mode" section, i've found 2 littles errors in the examples.

- RETR_LIST
it says :

> Below is the result I got, and each row is hierarchy details of corresponding contour. For eg, first row corresponds to contour 0. Next contour is contour 1. So Next = 1. There is no previous contour, so Previous = 0. And the remaining two, as told before, it is -1. 

According to the image, for the contour 0: Next is 1, Previous: -1 (and not 0), First child: -1, Parent: -1.

- RETR_TREE
it says:

> Take contour-2 : It is in hierarchy-1. No contour in same level. No previous one. Child is contour-2. Parent is contour-0. So array is [-1,-1,2,0].

The array for contour-2 is [-1,-1,3,1]. Contour-2 is contained in contour-1 which means parent contour is 1 and contour-2 contains contour-3, meaning that 3 is the child.

**Comment by sovrasov** [comment]
Could you please create a PR with fix for this tutorial?
