### ISSUE TITLE
Compatibility of Cmake find_package for opencv 2 and 3

### ISSUE THREAD

**Issue by hellock** [opencv/opencv#8444]
For a project with opencv as its dependency, how to make it compatible to both opencv 2 and 3?
Since some basic functions are moved to the imgcodes module in opencv 3, the `find_package()` is different for version 2 and 3.
```
find_package(OpenCV COMPONENTS core highgui imgproc)  # if opencv 2 is installed
find_package(OpenCV COMPONENTS core highgui imgproc imgcodecs)  # if opencv 3 is installed
```
Any suggestions how to write the `CMakeLists.txt` to make it work with both 2 and 3 without manually specifying any path or version number?

**Comment by alalek** [comment]
["find_package(OpenCV REQUIRED)"](https://github.com/opencv/opencv/blob/3.2.0/samples/cpp/example_cmake/CMakeLists.txt) command adds all available OpenCV modules.

Why do you need to specify components list?

**Comment by hellock** [comment]
Thanks a lot! Since I saw in some popular libraries the component list is specified, so I though it a common practice. My fault to miss the example mentioned above.
