### ISSUE TITLE
Which version of CUDA does OpenCV require for CUVID/NVENC support?

### ISSUE THREAD

**Issue by jcox-nd** [opencv/opencv#8445]
OpenCV does not currently support CUDA 8.0 for CUVID or NVENC hardware GPU decoding support. Therefore, which version of CUDA does enable these features with OpenCV?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

You may try CUDA 6.5/7.5 with NVCUVID API. But it is not recommended, because these drivers are outdated.
