### ISSUE TITLE
Detection of python libs fails even though installed on system

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#8449]
I cannot compile OpenCV with python2 support, even though a small test CMakeLists.txt can detect the installed python interpreter and libraries.

##### System information (version)

- OpenCV => 3 from git
- Operating System / Platform => SUSE Linux Enterprise Server 11 SP4
- Compiler => gcc 4.9.3

##### Detailed description

Running `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local  -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ .. -DWITH_opencv_HDF5=OFF -DWITH_GTK=OFF -DBUILD_opencv_python2=ON` results in:
```
-- Found PythonInterp: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/bin/python2.7 (found suitable version "2.7.11", minimum required is "2.7") 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "2.7.11")
[...]
--     Unavailable:                 java python2 python3 viz cnn_3dobj cvv dnn_modern freetype matlab sfm
[...]
--   Python 2:
--     Interpreter:                 /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/bin/python2.7 (ver 2.7.11)
--     Libraries:                   NO
--     numpy:                       /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/lib/python2.7/site-packages/numpy/core/include (ver 1.10.4)
--     packages path:               lib/python2.7/site-packages
```

##### Steps to reproduce

I created a small CMakeLists.txt, but get opposite results which show that the libraries can be indeed found:
```
$ cat CMakeLists.txt
project(test)
cmake_minimum_required(VERSION 3.5)
find_package(PythonInterp)
find_package(PythonLibs)
message("Python interp: ${PYTHONINTERP_FOUND}")
message("  executable: ${PYTHON_EXECUTABLE}")
message("  version: ${PYTHON_VERSION_STRING}")
message("python libs found: ${PYTHONLIBS_FOUND}")
message("  libraries: ${PYTHON_LIBRARIES}")
message("  version: ${PYTHONLIBS_VERSION_STRING}")
message("  debug libraries: ${PYTHON_DEBUG_LIBRARIES}")
message("  incl path: ${PYTHON_INCLUDE_PATH}")
message("  incl dirs: ${PYTHON_INCLUDE_DIRS}")
message("  library: ${PYTHON_LIBRARY}")
message("  incl dir: ${PYTHON_INCLUDE_DIR}")

$ cmake .
Python interp: TRUE
  executable: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/bin/python
  version: 2.7.11
python libs found: TRUE
  libraries: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/lib/libpython2.7.so
  version: 2.7.11
  debug libraries: 
  incl path: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/include/python2.7
  incl dirs: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/include/python2.7
  library: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/lib/libpython2.7.so
  incl dir: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/include/python2.7
-- Configuring done
-- Generating done
-- Build files have been written to: /u/mpibrphu/test
```

**Comment by alalek** [comment]
We don't officially support this Linux distributive. So you need to debug problem in your environment yourself.

You could start from this command:
```
cmake -U*PYTHON* --trace-expand .
```

or specify some of [these](https://github.com/opencv/opencv/blob/3.2.0/cmake/OpenCVDetectPython.cmake#L225-L231) CMake variables manually.:
```
find_python(2.7 "${MIN_VER_PYTHON2}" PYTHON2_LIBRARY PYTHON2_INCLUDE_DIR
    PYTHON2INTERP_FOUND PYTHON2_EXECUTABLE PYTHON2_VERSION_STRING
    PYTHON2_VERSION_MAJOR PYTHON2_VERSION_MINOR PYTHON2LIBS_FOUND
    PYTHON2LIBS_VERSION_STRING PYTHON2_LIBRARIES PYTHON2_LIBRARY
    PYTHON2_DEBUG_LIBRARIES PYTHON2_LIBRARY_DEBUG PYTHON2_INCLUDE_PATH
    PYTHON2_INCLUDE_DIR PYTHON2_INCLUDE_DIR2 PYTHON2_PACKAGES_PATH
    PYTHON2_NUMPY_INCLUDE_DIRS PYTHON2_NUMPY_VERSION)
```

My suggestion is to start from PYTHON2_INCLUDE_PATH/PYTHON2_NUMPY_INCLUDE_DIRS from this list (probably with PYTHON2LIBS_FOUND=ON).

**Comment by philipphuelsdunk** [comment]
I have narrowed the problem down to following CMakeLists.txt:

```
project(test)
cmake_minimum_required(VERSION 3.5)

find_package(PythonInterp;2.7)
get_cmake_property(_variableNames VARIABLES)
message("Python interp: ${PYTHONINTERP_FOUND}")
message("  executable: ${PYTHON_EXECUTABLE}")
message("  version: ${PYTHON_VERSION_STRING}")

unset(PYTHON_EXECUTABLE CACHE)

find_package(PythonLibs 2.7.11 EXACT)
message("python libs found: ${PYTHONLIBS_FOUND}")
message("  libraries: ${PYTHON_LIBRARIES}")
message("  version: ${PYTHONLIBS_VERSION_STRING}")
message("  debug libraries: ${PYTHON_DEBUG_LIBRARIES}")
message("  incl path: ${PYTHON_INCLUDE_PATH}")
message("  incl dirs: ${PYTHON_INCLUDE_DIRS}")
message("  library: ${PYTHON_LIBRARY}")
message("  incl dir: ${PYTHON_INCLUDE_DIR}")
```

The `unset(PYTHON_EXECUTABLE CACHE)` makes `find_package(PythonLibs 2.7.11 EXACT)` to fail:

```
Python interp: TRUE
  executable: /mpcdf/soft/SLES114/common/anaconda/2/4.0.0/bin/python2.7
  version: 2.7.11
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "2.7.11")
python libs found: FALSE
  libraries: PYTHON_LIBRARY-NOTFOUND
  version: 
  debug libraries: 
  incl path: 
  incl dirs: 
  library: PYTHON_LIBRARY-NOTFOUND
  incl dir: 
-- Configuring done
-- Generating done
-- Build files have been written to: /u/mpibrphu/test
```

cmake'ing with:
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")

resolves the problem.

**Comment by alalek** [comment]
OpenCV-specific vars for this configuration are: `PYTHON2_EXECUTABLE` / `PYTHON2_INCLUDE_DIR` / `PYTHON2_LIBRARY`.

**Comment by wahyubram82** [comment]
> I have narrowed the problem down to following CMakeLists.txt:
> 
> ```
> project(test)
> cmake_minimum_required(VERSION 3.5)
> 
> find_package(PythonInterp;2.7)
> get_cmake_property(_variableNames VARIABLES)
> message("Python interp: ${PYTHONINTERP_FOUND}")
> message("  executable: ${PYTHON_EXECUTABLE}")
> message("  version: ${PYTHON_VERSION_STRING}")
> 
> unset(PYTHON_EXECUTABLE CACHE)
> 
> find_package(PythonLibs 2.7.11 EXACT)
> message("python libs found: ${PYTHONLIBS_FOUND}")
> message("  libraries: ${PYTHON_LIBRARIES}")
> message("  version: ${PYTHONLIBS_VERSION_STRING}")
> message("  debug libraries: ${PYTHON_DEBUG_LIBRARIES}")
> message("  incl path: ${PYTHON_INCLUDE_PATH}")
> message("  incl dirs: ${PYTHON_INCLUDE_DIRS}")
> message("  library: ${PYTHON_LIBRARY}")
> message("  incl dir: ${PYTHON_INCLUDE_DIR}")
> ```
base on this, I try make some experiment, because i see a line in OpenCV CMakeLists.txt looks like below:
```
if(BUILD_opencv_python3)
  status("")
  status(" Python 3:")
  status(" Interpreter:" PYTHON3INTERP_FOUND THEN "${PYTHON3_EXECUTABLE} (ver ${PYTHON3_VERSION_STRING})" ELSE NO)
  if(PYTHON3LIBS_VERSION_STRING)
    status(" Libraries:" HAVE_opencv_python3 THEN "${PYTHON3_LIBRARIES} (ver ${PYTHON3LIBS_VERSION_STRING})" ELSE NO)
  else()
    status(" Libraries:" HAVE_opencv_python3 THEN "${PYTHON3_LIBRARIES}" ELSE NO) 
  endif()
  status(" numpy:" PYTHON3_NUMPY_INCLUDE_DIRS THEN "${PYTHON3_NUMPY_INCLUDE_DIRS} (ver ${PYTHON3_NUMPY_VERSION})" ELSE "NO (Python3 wrappers can not be generated)") 
  status(" install path:" HAVE_opencv_python3 THEN "${__INSTALL_PATH_PYTHON3}" ELSE "-")
endif()
```

because my opencv cannot detect my python, I make this test:
```
project(test)
cmake_minimum_required(VERSION "${MIN_VER_CMAKE}" FATAL_ERROR)
find_package(PythonInterp)
find_package(PythonLibs)
message("Python interp: ${PYTHON3INTERP_FOUND}")
message(" executable: ${PYTHON3_EXECUTABLE}")
message(" version: ${PYTHON3_VERSION_STRING}")
message("python libs found: ${PYTHON3LIBS_FOUND}")
message(" libraries: ${PYTHON3_LIBRARIES}")
message(" version: ${PYTHON3LIBS_VERSION_STRING}")
message(" debug libraries: ${PYTHON3_DEBUG_LIBRARIES}")
message(" incl path: ${PYTHON3_INCLUDE_PATH}")
message(" incl dirs: ${PYTHON3_INCLUDE_DIRS}")
message(" library: ${PYTHON3_LIBRARY}")
message(" incl dir: ${PYTHON3_INCLUDE_DIR}")
```

and after do `cmake .` the result like this:
```
Python interp:
  executable:
  version:
python libs found:
  libraries:
  version:
  debug libraries:
  incl path:
  incl dirs:
  library:
  incl dir:
```
so i think, there is a problem in the code (definition / variable set)

I 'm not to much understood about CMake code...but if this in code, i will do:

1. search python 3 exist or not
2. make definition for the python3 exist condition, like:
set PYTHON3_EXECUTABLE = the condition of existing python3
3. do the same for python3 libs and anything else.
