### ISSUE TITLE
StereoSGBM and StereoBinarySGBM is it different?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8450]
Hi,

Are StereoBM and StereoBinaryBM classes differents? 
Are StereoSGBM and StereoBinarySGBM classes differents? 

I can find in doc [cv::StereoSGBM Class Reference](http://docs.opencv.org/master/d2/d85/classcv_1_1StereoSGBM.html#details) in calib3d module (opencv) 

    Detailed Description
    
    The class implements the modified H. Hirschmuller algorithm [75] that differs from the original one as follows:
    
        By default, the algorithm is single-pass, which means that you consider only 5 directions instead of 8. Set mode=StereoSGBM::MODE_HH in createStereoSGBM to run the full variant of the algorithm but beware that it may consume a lot of memory.
        The algorithm matches blocks, not individual pixels. Though, setting blockSize=1 reduces the blocks to single pixels.
        Mutual information cost function is not implemented. Instead, a simpler Birchfield-Tomasi sub-pixel metric from [13] is used. Though, the color images are supported as well.
        Some pre- and post- processing steps from K. Konolige algorithm StereoBM are included, for example: pre-filtering (StereoBM::PREFILTER_XSOBEL type) and post-filtering (uniqueness check, quadratic interpolation and speckle filtering).
    
    Note
    
            (Python) An example illustrating the use of the StereoSGBM matching algorithm can be found at opencv_source_code/samples/python/stereo_match.py

and [cv::stereo::StereoBinarySGBM](http://docs.opencv.org/master/d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html) in stereo module (opencv_contrib)

    Detailed Description
    
    The class implements the modified H. Hirschmuller algorithm [75] that differs from the original one as follows:
    
        By default, the algorithm is single-pass, which means that you consider only 5 directions instead of 8. Set mode=StereoSGBM::MODE_HH in createStereoSGBM to run the full variant of the algorithm but beware that it may consume a lot of memory.
        The algorithm matches blocks, not individual pixels. Though, setting blockSize=1 reduces the blocks to single pixels.
        Mutual information cost function is not implemented. Instead, a simpler Birchfield-Tomasi sub-pixel metric from [13] is used. Though, the color images are supported as well.
        Some pre- and post- processing steps from K. Konolige algorithm StereoBM are included, for example: pre-filtering (StereoBM::PREFILTER_XSOBEL type) and post-filtering (uniqueness check, quadratic interpolation and speckle filtering).
    
    Note
    
            (Python) An example illustrating the use of the StereoSGBM matching algorithm can be found at opencv_source_code/samples/python2/stereo_match.py

Same thing for [cv::StereoBM Class Reference](http://docs.opencv.org/master/d9/dba/classcv_1_1StereoBM.html) 

    Detailed Description
    
    Class for computing stereo correspondence using the block matching algorithm, introduced and contributed to OpenCV by K. Konolige.

and [cv::stereo::StereoBinaryBM Class Reference](http://docs.opencv.org/master/d7/d8e/classcv_1_1stereo_1_1StereoBinaryBM.html) 

    Detailed Description
    
    Class for computing stereo correspondence using the block matching algorithm, introduced and contributed to OpenCV by K. Konolige.

**Comment by sovrasov** [comment]
Author of contrib stereo module copied docs from the calib3d module without any change, so descriptions are the same but the algorithms differ.
