### ISSUE TITLE
Invoking getLastTargetState() for a "KCF" tracker causes segfault (OpenCV 3.2)

### ISSUE THREAD

**Issue by kzampog** [opencv/opencv#8451]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Linux Mint 18.1
- Compiler => g++

##### Detailed description

Invoking getLastTargetState() for a "KCF" tracker causes segfault (tracker->getModel() is not NULL). It appears to work correctly for "MIL".

##### Steps to reproduce
	#include <iostream>

	// Standard include files
	#include <opencv2/opencv.hpp>
	#include <opencv2/tracking.hpp>
	 
	using namespace cv;
	using namespace std;
	 
	int main(int argc, char **argv)
	{
		// Set up tracker. 
		// Instead of MIL, you can also use 
		// BOOSTING, KCF, TLD, MEDIANFLOW or GOTURN  
		Ptr<Tracker> tracker = Tracker::create( "KCF" );
	 
		// Read video
		// VideoCapture video("videos/chaplin.mp4");
		VideoCapture video(CV_CAP_OPENNI);
		 
		// Check video is open
		if(!video.isOpened())
		{
			cout << "Could not read video file" << endl;
			return 1;
		}
	 
		// Read first frame. 
		Mat frame;
		
		for (int i = 0; i < 30; ++i) {
			video.grab();
			video.retrieve(frame, CV_CAP_OPENNI_BGR_IMAGE);
		}
	 
		// Define an initial bounding box
		Rect2d bbox(287, 23, 86, 320);
	 
		// Uncomment the line below if you 
		// want to choose the bounding box
		bbox = selectROI(frame, false);
		 
		// Initialize tracker with first frame and bounding box
		tracker->init(frame, bbox);

		Ptr<TrackerTargetState> state = tracker->getModel()->getLastTargetState();
		while(true)
		{
			video.grab();
			video.retrieve(frame, CV_CAP_OPENNI_BGR_IMAGE);

			// Update tracking results
			tracker->update(frame, bbox);
	 
			// Draw bounding box
			rectangle(frame, bbox, Scalar( 255, 0, 0 ), 2, 1 );
	 
			// Display result
			imshow("Tracking", frame);
			int k = waitKey(1);
			if(k == 27) break;
			if(k == 'a') {
				// Ptr<TrackerTargetState> state = tracker->getModel()->getLastTargetState();
				// cout << state->getTargetPosition() << endl;
				tracker->getModel()->setLastTargetState(state);
				cout << "init lul" << endl;
			}
	 
		}
	 
		return 0; 
		 
	}

**Comment by sovrasov** [comment]
This issue should be moved to `opencv_contrib`

**Comment by sovrasov** [comment]
Method `getModel()` actually should be private. `KCF` and some other trackers doesn't update their models, so `getLastTargetState()` returns a null pointer. 
API in the tracking module is still needs some improvements.
