### ISSUE TITLE
Why there is no Blob class in Java wrapper of OpenCV

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#8452]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I want to detect blobs in image, but I did not find the class Blob which is in a C++ example code, but there is not in Java wrapper of OpenCV.  Here is the code which is used in C++
```
std::vector<std::vector<cv::Point> > convexHulls(contours.size());

        for (unsigned int i = 0; i < contours.size(); i++) {
            cv::convexHull(contours[i], convexHulls[i]);
        }

        for (auto &convexHull : convexHulls) {
            Blob possibleBlob(convexHull);

            if (possibleBlob.currentBoundingRect.area() > 400 &&
                possibleBlob.dblCurrentAspectRatio > 0.2 &&
                possibleBlob.dblCurrentAspectRatio < 4.0 &&
                possibleBlob.currentBoundingRect.width > 30 &&
                possibleBlob.currentBoundingRect.height > 30 &&
                possibleBlob.dblCurrentDiagonalSize > 60.0 &&
                (cv::contourArea(possibleBlob.currentContour) / (double)possibleBlob.currentBoundingRect.area()) > 0.50) {
                currentFrameBlobs.push_back(possibleBlob);
            }
        }
```

**Comment by berak** [comment]
there is no such class in opencv's api at all, you probably found that in some 3rd party code

**Comment by Bahramudin** [comment]
OK! Thank you! @berak 
But question that I want to ask you is that: Is the Java wrapper of OpenCV best enough to build some big application using OpenCV? For example, If use C++ to build application can be more fast and the same time can access all the OpenCV APIs (GPUMat, contrib ...etc), without any restriction. Is this available in Java too? If not, then what we can do with Java wrapper at most case. Is the Java wrapper a right choice to develop official application using OpenCV? Or just can be used to develop some simple (toy) applications.
Thanks a lot!

**Comment by berak** [comment]
@Bahramudin , unfortunately, i cannot answer that question.

also, this might be the entirely wrong place, to discuss it, would you kindly close this issue, and, if nessecary, continue on http://answers.opencv.org ?

**Comment by Bahramudin** [comment]
@berak ,Thank you! I just want to ensure, because I have against some problem with the Java wrapper such as application become hung and when use three or more camera at the same time and also I have discovered that there is lack of access to some function of the OpenCV in Java wrapper.
