### ISSUE TITLE
Unexpected behavior of ellipse()

### ISSUE THREAD

**Issue by mpapini** [opencv/opencv#8457]
- OpenCV => 3.2 (not verified on other versions)
- Operating System / Platform => Windows 64 Bit / Linux 32-bit arm
- Compiler => Visual Studio 2015 / g++ 4.8.4

If ellipse segment is drawn such that start and end angles "stradle" 0 degrees, arc is drawn correctly if start angle is negative (e.g.  -5), differently if start angle is large positive (e.g., 355).

If drawing an ellipse from, for example 355 degrees to 45 degrees, if the start angle is expressed as -5 degrees, the arc goes from -5 to +45 as expected.  If the start angle is expressed as 355, the arc goes "around the long way", i.e., it is drawn from 45 to 355 degrees.  Happens with line or filled.

Trivial example:

	cv::Mat img1(360, 640, CV_8UC1, cv::Scalar(255));
        cv::Mat img2(360, 640, CV_8UC1, cv::Scalar(255));

	cv::Point center(320, 180);
	cv::Size axes(100, 100);

	cv::ellipse(img1, center, axes, 0.0, -5.0, 45.0, cv::Scalar(0), -1);
	cv::ellipse(img2, center, axes, 0.0, 355.0, 45.0, cv::Scalar(0), -1);

	cv::imshow("As expected", img1);
        cv::imshow("Different", img2);
	cv::waitKey(0);

Not sure if I missed something in the documentation or this is intended.  I suspect a note in the documentation would be enough otherwise the behavior would be changed.

**Comment by saskatchewancatch** [comment]
@mpapini I believe `cv::ellipse` essentially calls `cv::ellipse2Poly` to get the structure of points it needs to draw an ellipse.

Have a look at the definition of `ellipse2Poly` (the one that's overloaded to take in a Point2d for the center parameter) in [drawing.cpp](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/drawing.cpp#L959). How it treats `angle`, `arc_start`, `arc_end` is exposed there. I think going through the code leading to the call to `sincos` will shed light on your question.

**Comment by mpapini** [comment]
@saskatchewancatch thanks for your response.  I went through the code and  it is in fact this [if](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/drawing.cpp#L959) that swaps start / end.  That, however, doesn't clarify for me as to where in the documentation one was supposed to understand that specifying the start angle as -5 or 355 degrees would result in different ellipses being drawn even though 355 and -5 are equivalent angles.  

For clarity here are the two images:

1) As expected (start -5, end 45):

![as expected_screenshot_19 04 2017](https://cloud.githubusercontent.com/assets/2348900/25164766/5346878a-24d3-11e7-95f1-e360c6f7615e.png)

2) Different (start 355, end 45)

![different_screenshot_19 04 2017](https://cloud.githubusercontent.com/assets/2348900/25164788/74ef3d32-24d3-11e7-9d90-3c0a8b1bdf6b.png)

**Comment by saskatchewancatch** [comment]
#8620

**Comment by mpapini** [comment]
Thank-you
