### ISSUE TITLE
opencv4android arm64-v8a version slower than armv7-v7a

### ISSUE THREAD

**Issue by lligen** [opencv/opencv#8462]
hi，
 
why the opencv official website provide opencv4android armeabi-v7a only and not provide arm64-v8a?

i have compiled the  arm64-v8a version and find it slower than armeabi-v7a(official version) when running on android.

are there any tricks on compiling a faster arm64-v8a version?

**Comment by amirzahed** [comment]
how you compile it for arm64-v8a !?
any toturial !?
i didnt finde anything
