### ISSUE TITLE
Build opencv when multiple python version exist

### ISSUE THREAD

**Issue by smallzzy** [opencv/opencv#8467]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 10 64 Bit but possibly other systems
- Compiler => Visual Studio 2015

##### Detailed description

I want to compile opencv 3.2 for python 3.5. Python 3.5 is installed in a virtual env in anaconda. 
But cmake will  find the python in the PATH (which is 3.6 in my computer) and use its version info to link the libraries which of course does not work.

After some investigation, I think it is related to find_host_package(PythonInterp) in the OpenCVDetectPython.cmake.
Then later process will use this python version found by cmake instead of use the python specified by the user.

The result is that it will give wrong version & use the wrong library file.
```
Found PythonInterp: C:/Users/smallzzy/Miniconda3/python.exe (found suitable version "3.6.1", minimum required is "2.7") 
```

```
Python 3:
    Interpreter:                 C:/Users/smallzzy/Miniconda3/envs/py35/python.exe (ver 3.6.1)
    Libraries:                   C:/Users/smallzzy/Miniconda3/libs/python36.lib (ver 3.6.1)
    numpy:                       C:/Users/smallzzy/Miniconda3/envs/py35/Lib/site-packages/numpy/core/include (ver )
    packages path:               C:/Users/smallzzy/Miniconda3/envs/py35/Lib/site-packages
```
(quoted from cmake log)

##### Steps to reproduce

I suppose the same problem will happen when multiple python is installed in the system path and when the user tries to build against one specific version.

I am really new to opencv. Please correct me if I made a mistake here.

**Comment by smallzzy** [comment]
The problem was easy to solve in my case. I just need to activate that virtual environment in conda and the python 3.6 path is overridden. But I think this might be a problem to other users.

**Comment by alalek** [comment]
`find_host_package(PythonInterp)` is equal to `find_package(PythonInterp)`. Same note about `PythonLibs`.

These configuration files ([FindPythonInterp.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindPythonInterp.cmake), [FindPythonLibs.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindPythonLibs.cmake)) are provided by CMake, so we can't help a lot here.

> activate that virtual environment

Right, virtual environment should not be used without activation. Without activation, the virtual environment is a some folder which should not change any existed settings of system.

BTW,
Always clear CMake cache (at least, Python vars in this case) or clear build directory if you changing configuration parameters/options/environment variables.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
