### ISSUE TITLE
CMAKE RULES Is not enough good

### ISSUE THREAD

**Issue by savent404** [opencv/opencv#8469]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04 (CPU:I7-5500)
- Compiler => gcc-x86_64-linux-gnu

##### Detailed description

When i do as Document says, I found cmake rules is not good for multi-cpu make.
And Then make will show Error at 89%.

##### Steps to reproduce

```shell
sudo apt-get install build-essential libgtk2.0-dev libavcodec-dev libavformat-dev libjpeg62-dev libtiff5-dev camke libswscale-dev libjasper-dev
mkdir release
cd release
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ~/SoftWare/opencv-3.2.0
sudo make -j8
```

**Comment by alalek** [comment]
Provided information is not enough to reproduce problem.
