### ISSUE TITLE
Can't open webcan or video file with python3 and opencv

### ISSUE THREAD

**Issue by patrickelectric** [opencv/opencv#8471]
##### System information (version)

- OpenCV => 3.2.0-1
- Python OpenCV => 3.2.0.6
- Python => 3.5.2
- Operating System / Platform => ArchLinux 64bits

##### Detailed description

Can't open VideoCapture don't work with files and /dev/video 

##### Steps to reproduce
```
import cv2
video = cv2.VideoCapture(0)
if video.isOpened():
    while True:
        check, frame = video.read()
        if check:
            cv2.imshow('Color Frame', frame)
            key = cv2.waitKey(50)
            if key == ord('q'):
                break
        else:
            print('Frame not available')
            print(video.isOpened())
```

The code don't show webcan or video file
Works with python2 ..

**Comment by patrickelectric** [comment]
@alalek what is missing ?

**Comment by alalek** [comment]
Provided details is not enough to reproduce the issue.
Especially difference between Python2/3 looks strange.

What does "3.2.0-1" mean in OpenCV version? Is it Arch package version? AUR?

Please check correctness of loaded modules (`cv2.__file__`, `cv2.__version__`).
Also please provide OpenCV build configuration: `cv2.getBuildInformation()`

**Comment by mgruben** [comment]
Can't open videos or webcam:

**System information (version)**
`opencv-python` Version: 3.2.0.7
`python` Version: 3.6.1
Operating System / Platform: `4.10.11-1-ARCH` Linux

**Detailed description**
Can't open VideoCapture don't work with files and /dev/video

**Steps to reproduce**
```python
# Fails with files, direct instantiation
import cv2
camera = cv2.VideoCapture("path/to/a/valid/video.mp4")
print(camera.isOpened()) # False
print(camera.read()) # (False, None)
```
```python
# Fails with files, using .open() method
import cv2
camera = cv2.VideoCapture()
camera.open("path/to/a/valid/video.mp4") # False
print(camera.read()) # (False, None)
```
```python
# Fails with webcam
import cv2
camera = cv2.VideoCapture(0)
print(camera.isOpened()) # False
print(camera.read()) # (False, None)
```

**Comment by dkloving** [comment]
Same issue with Python 3.6.0 under MacOS 10.12 Sierra.

**Comment by alalek** [comment]
This is still looks like an usage question. OpenCV requires 3rdparty libraries to work with cameras/videos. You need to install them properly before building OpenCV Python bindings.

`opencv-python` doesn't support them (almost all 3rdparty dependencies are turned off, because they are system dependent - system with minimal configuration is used during build).

For more information please refer to this question and others:
> Q: Why I can't open video files on GNU/Linux distribution X or on macOS?

(https://pypi.python.org/pypi/opencv-python)

`opencv-python` binary package is not officially supported by OpenCV dev team, so we can't help here.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by iiAnthony** [comment]
I have had a comparable issue on Ubuntu, using the pip install opencv-python process.
Solution used :  I recompiled both ffmpeg and opencv 3.2  from sources on my station (following the install processes indicated on offical portals). Everything worked well, but I still was not able to open video from cvé.videocapture  on python.

My solution has been to replace the cv2.so library provided by pypi with the one compile from sources :
`sudo cp opencv-3.2.0/build/lib/cv2.so /usr/local/lib/python2.7/dist-packages/cv2/`

And I now can play videos with cv2, from my python scripts.  Hope this will help those experiencing the same issue (I spent some time on trying to find a solution and never found this suggestion so ...).

**Comment by chutsu** [comment]
I did a similar thing to `iiAnthony` where I compiled OpenCV 3.2.0 from source, double checking with CMake that it can find both python 2 and python 3

![screenshot_2017-09-26_13-10-50](https://user-images.githubusercontent.com/91460/30873710-29606d5c-a2bc-11e7-8a09-e73d43859f6a.png)

then I replaced the compiled `.so` dynamic library with the one that comes with `opencv-python` python3 package

```
sudo cp <path to opencv source repo>/build/lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-x86_64-linux-gnu.so
```
**Note**: Your `.so` library file may have a different name to mine, but the idea is the same, compile your own opencv3 `.so` library file and replace the one that `opencv-python` comes with.

**Comment by alundiak** [comment]
Considering these 2 commands:
```
sudo cp build/lib/cv2.so /usr/local/lib/python2.7/dist-packages/cv2/
```

```
sudo cp build/lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-x86_64-linux-gnu.so
```
In my case opencv-3.3.1/build/lib doesn't have folder python nor python 2.7 nor python 3.6.
It contains lot of files with prefix `libopencv_XYZ.so`

And I'm on CentOS 7.0

**Comment by chutsu** [comment]
That could be a number of things:

1. CMake failed to find your python version, double check it is listed in the `cmake ..` stage (like in the screenshot I took in the previous post).
2. You don't have the python development library (on debian based systems this corresponds to `python-dev` or `python3-dev` packages)
3. Try and checkout a specific version of OpenCV instead of building master (i.e. `git checkout 3.3.1`)

I just downloaded and built the zipped OpenCV 3.3.1 and have found the `cv2.so` in  the `build/python3` folder so you'll have to double check your build settings.

![screenshot_2017-12-06_11-15-20](https://user-images.githubusercontent.com/91460/33671887-cde3c3be-da76-11e7-9e6f-1e946b2ae757.png)

**Comment by alundiak** [comment]
@chutsu thanks.
I tried master and simple download of 3.3.1, both behaves similarly, But for sure, smth wrong with Python. Researching again....
Regarding python-dev it's odd, becauae I installed  Installing OpenCV from source https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_setup_in_fedora/py_setup_in_fedora.html

will double check.

**Comment by alundiak** [comment]
Odd. Or I just don't know proper syntax of external params:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -D PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3  PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 ..
```

In output I see trace of some version logic and error:
```
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.6.3", minimum required is "2.7") 
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4.5", minimum required is "3.4") 
-- Found PythonLibs: /lib64/libpython3.4m.so (found suitable exact version "3.4.5") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'


```

**Comment by alalek** [comment]
> ImportError: cannot import name 'multiarray'

There is build/installation issue of numpy package on your machine.
Check issues about this message - for example, https://github.com/numpy/numpy/issues/9047

**Comment by alalek** [comment]
BTW,

> which python3 => /usr/local/bin/python3

You have custom python setup (without any information how you get it).

> ls -la /usr/local/lib/python3.6/site-packages/cv2/

This file set is not generated by original OpenCV. You have installed something else from other sources.

**Comment by alundiak** [comment]
I recently solved issue for my use case.
So my old (BAD configs) were:

- `OpenCV` 2.4.5 (after `yum install opencv`)
- `opencv_python` 3.3.0.10 (after `pip3 install opencv_python`)

And in fact I have Assertion error, as it's described here: https://github.com/ageitgey/face_recognition/issues/191#issuecomment-350223266

Then, I compiled OpenCV from sources (git cloned and checked out 3.3.1 branch) and I had 3.3.1 version.
But even with opencv 3.3.0.10 IT WAS NOT working, because
```
/usr/lib64/python3.4/site-packages/cv2/cv2.cpython-34m.so is 3.3.0
```
yes, opencv_python installs into `... lib64 ...`

So, then there are 2 ways of resolving issue:
1) replace of so file
```
sudo cp ~/opencv/build/lib/python3/cv2.cpython-34m.so /usr/lib64/python3.4/site-packages/cv2 
# meaning 3.3.1 version replaces 3.3.0 version of so file
```

2) Remove opencv_python and don't use it later
```
sudo pip3 uninstall opencv_python
```

I did both, and my application was working in both cases. But still, I am not confident what is the best way.

**Comment by netcoms** [comment]
In my case i simply un-installed and installed back opencv-python 
Before re-installation i had opencv-python-3.3.0.10. after re-install i got a newer version opencv-python-3.4.0.12
- pip3 uninstall opencv_python
- pip3 install opencv_python --user

**Comment by skvark** [comment]
For future reference:

If you have installed either one of the precompiled distributions ``opencv-python`` or ``opencv-contrib-python`` from pip there are a few things to note if you are using Linux or macOS (Windows builds have had video support always):

- versions < 3.3.1.11 are not compiled with FFmpeg (macOS, Linux) and V4L (webcam support, Linux)
- versions  >= 3.3.1.11 have been compiled with FFmpeg and V4L

Changelogs for every release are available at the ``opencv-python`` package repository https://github.com/skvark/opencv-python/releases.

**Comment by murari023** [comment]
@skvark i have installed the opencv 3.4.0.12, but still in the following command, the retval returns "false". Why is that? i am not able to figure out. Since the new opencv includes support to ffmpeg, it should work right?
>>> import cv2
>>> cap = cv2.VideoCapture('test')
>>> retval, frame = cap.read()

**Comment by sudhir002** [comment]
i have install and run the scrpt in my raspberry pi   but it will not capture video and also retval show false value 
how to read take video in my raspberry pi using raspi camera 
plz give me solution in detail 

import cv2
cap = cv2.VideoCapture('test')
retval, frame = cap.read()

![image](https://user-images.githubusercontent.com/33150867/38678433-9b09eb64-3e7e-11e8-8e97-4bdb645900f3.png)

**Comment by FilipBielickiPL** [comment]
I had this problem and couldn't find a solution, but on the web, it was working. My solution was almost funny - you can't have two streams. I turned off the web stream and then it was fine!

**Comment by bedssys** [comment]
I know people doesn't appreciate you @FilipBielickiPL, but that is certainly my problem, so thx! Basically, I have a configurable program (video vs webcam) and despite the WebcamVideoStream is not used during video mode, it'll disturb the way VideoCapture working.

**Comment by chutsu** [comment]
it would help if you can share a minimal reproducible example so that people can try out what the error is. Without example code we can't help you.

**Comment by bedssys** [comment]
@chutsu Why the thumbs down? I solved my error exactly like what @FilipBielickiPL.

**Comment by santhoshnumberone** [comment]
I have opencv running on cloud, This is not solving my issue. The file is present in the particular location but still unable to open the file.

> 
> 
> For future reference:
> 
> If you have installed either one of the precompiled distributions `opencv-python` or `opencv-contrib-python` from pip there are a few things to note if you are using Linux or macOS (Windows builds have had video support always):
> 
>     * versions < 3.3.1.11 are not compiled with FFmpeg (macOS, Linux) and V4L (webcam support, Linux)
> 
>     * versions  >= 3.3.1.11 have been compiled with FFmpeg and V4L
> 
> 
> Changelogs are available for every release at the `opencv-python` package repository https://github.com/skvark/opencv-python/releases.

**Comment by mhkmcp** [comment]
Where is @FilipBielickiPL 's solution. i can't find out

**Comment by lhaippp** [comment]
> I did a similar thing to @iiAnthony where I compiled OpenCV 3.2.0 from source, double checking with CMake that it can find both python 2 and python 3
> 
> ![screenshot_2017-09-26_13-10-50](https://user-images.githubusercontent.com/91460/30873710-29606d5c-a2bc-11e7-8a09-e73d43859f6a.png)
> 
> then I replaced the compiled `.so` dynamic library with the one that comes with `opencv-python` python3 package. The difference between my comment and @iiAnthony's is that his caters for Python2 users?
> 
> ```
> sudo cp <path to opencv source repo>/build/lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-x86_64-linux-gnu.so
> ```
> 
> Or better yet, just the `ln` command to symlink the built `.so` instead of copying, so that if you decide to compile OpenCV3 with different compilation flags you don't have to copy the library file over again.
> 
> **Note**: Your `.so` library file may have a different name to mine, but the idea is the same, compile your own opencv3 `.so` library file and replace the one that `opencv-python` comes with.

Great answer!
It works for me

**Comment by YasPHP** [comment]
**Had same issue and found that meeting all these steps made it work on mac:**
- make sure it's `cap = cv2.VideoCapture(0)` if using default mac camera and if using more external `x` cameras, scale and include VideoCapture(1), 2, 3, etc.
- don't forget to release the video source at the proper time by calling the `release()` method or else it will leave your camera unusable and you'll have to either restart your mac or reset the system entirely to recover the camera with `sudo killall VDCAssistant`
- running main program directly on terminal vs pycharm run worked
- make sure to close webcam window at end with 
` cv2.destroyAllWindows()
  cap.release()
  break`
- have opencv-contrib-python properly installed via your requirements.txt

These are just the basics you could be missing and leading it to error _or_ it could be something else but this is a good checklist for a first step. Good luck!

**Comment by flutterereur** [comment]
**it works for me**
just
authorize camera on your compiler or browser

![Screenshot 2021-12-09 114639](https://user-images.githubusercontent.com/64313081/145382430-0558a6fe-35e0-42e3-9562-ff0e94acc318.png)


**if didn't work try open your camera and make sure its working before running your code**
