### ISSUE TITLE
help!screen problem

### ISSUE THREAD

**Issue by qp910** [opencv/opencv#8476]
Why opencv for Android front camera default only horizontal screen, I converted into a vertical screen will affect the frame rate and  distortion , there are wood what a good solution

**Comment by qp910** [comment]
Why don't you answer me , I really need help

**Comment by alalek** [comment]
This is bug/features tracker.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org . Also you should use search before posting of new items.
