### ISSUE TITLE
PtrStepSz is missing documentation

### ISSUE THREAD

**Issue by iglesias** [opencv/opencv#8477]

**Comment by alalek** [comment]
OpenCV documentation covers API intended for external usage.
Some implementation details (for internal usage only) may missing.

**Comment by iglesias** [comment]
See detailed description in GpuMat, http://docs.opencv.org/3.1.0/d0/d60/classcv_1_1cuda_1_1GpuMat.html#details, as well as its public cast operator to PtrStepSz.

**Comment by karansingh1559** [comment]
Can anybody assign me this? I'm a newcomer here. 
https://github.com/opencv/opencv/wiki/How_to_contribute    this is all I've read.
