### ISSUE TITLE
OpenCVTutorial2MixedProcessing project compiled static library can not find the required function

### ISSUE THREAD

**Issue by hnty545** [opencv/opencv#8482]
Hello!
I debug the openCVTutorial2MixedProcessing project, the use of the NDK compiler static library libmixed_sample.so, running APK in the 184 line of JavaCameraView error, showing the lack of n_Mat (int rows, int cols, int type).
I see through the IDA libmixed_sample.so confirmed this point, does not have this function, see libopencv_java3.so when can find this function, so I continue to view the libopencv_core.a that also can not find the function, this is the reason why libmixed_sample.so can't find.
I would like to compile static library how to get this function, so that the smooth operation of openCVTutorial2MixedProcessing?
I also have been identified successfully loaded System.loadLibrary ("mixed_sample");, just loaded this a dynamic library, and no load java3, this is what I want, because java3 8.5M, while libmixed_sample.so is only 2.3M, which can save a lot of APK in loading multiple platform dynamic library volume.
————————————————————————
您好！
我在调试openCVTutorial2MixedProcessing工程，使用了ndk编译静态库libmixed_sample.so，运行APK时在JavaCameraView的184行报错，显示缺少了n_Mat(int rows, int cols, int type)。
我通过IDA查看libmixed_sample.so证实了这一点，确实没有此函数，查看libopencv_java3.so时候却能够发现此函数，于是我继续查看libopencv_core.a发现也找不到此函数，这就是libmixed_sample.so找不到的原因。
请问我编译静态库该怎样才能得到此函数，让openCVTutorial2MixedProcessing顺利运行？

另外我确定已经成功加载了System.loadLibrary("mixed_sample");，只是加载了这一个动态库，并没有加载java3，这是我想要的，因为java3有8.5M，而libmixed_sample.so只有2.3M，这在加载多个平台动态库时能够节省很多APK的体积。

**Comment by csukuangfj** [comment]
**Summary**:
While debugging the project `openCVTutorial2MixedProcessing`, I used NDK to generate the static library `libmixed_sample.so`. But an error is thrown at line 184 of **JavaCameraView** while running the APK, showing that the method `n_Mat(int rows, int cols, int type)` is missing.

I checked **libmixed_sample.so** with IDA and found that there is no such a function, but it is included in `libopencv_java3.so`.  It is not contained in `libopencv_core.a`, which explains for it non-existence.

**Question** How can I compile the static library in order to run `openCVTutorial2MixedProcessing`.

Furthermore, `System.loadLibrary("mixed_sample");` is executed successfully, but only this library is loaded and `java3` is not. Because `java3` has a size of 8.5MB, while `libmixed_sample.so` is only 2.3MB,
which can reduce the size of the APK in case of loading multiple dynamic libraries.

-----

不好意思，我无法解决你的问题。

**Comment by alalek** [comment]
OpenCV Java API (org.opencv.android.JavaCameraView and others) requires `opencv_java3.so`.
You can work with OpenCV C++ code via custom ".so" file, but you can't use OpenCV Java API in Android app in this case.

**Comment by hnty545** [comment]
Thank you very much for your help!
Hello Alalek, do you mean that you must use Java API to introduce java3.so? This dynamic library is really very large, in particular the need to support arm, arm-a7, arm64-a8 need to introduce 3 platforms to the jniLibs library files, packaged APK becomes more than 38M.
I actually want to introduce only the necessary opencv features, and the use of java.
Can I understand:
If you need to be introduced to reduce the volume, it is necessary to use c++ coding in JNI, and through the android.mk to control the introduction of the.A static library?
——————————————————————
非常感谢你们俩的帮助！
你好！alalek，您的意思是使用java api必须引入java3.so吗？这个动态库真的非常大，特别是需要支持arm、arm-a7、arm64-a8的时候需要引入3个平台的库文件到jniLibs，打包的apk变得超过38M。
我其实是希望只引入必须的opencv功能，并在java中使用的。
我是否可以这样理解：
如果要按需引入来减少体积，就必须在jni里用c++编码，并通过android.mk来控制引入的.a静态库？

**Comment by alalek** [comment]
> must use Java API to introduce java3.so

I mean that you must use java3.so to use Java API from "org.opencv" package.
However you may use OpenCV C++ features in your custom C++ native JNI library (with your custom Java API).

> it is necessary to use c++ coding in JNI, and through the android.mk to control the introduction of the.A static library?

Right.

BTW, Read these articles about reducing APK size (provide APK per platform):
- https://developer.android.com/google/play/publishing/multiple-apks.html
- https://software.intel.com/en-us/android/articles/google-play-supports-cpu-architecture-filtering-for-multiple-apk

**Comment by hnty545** [comment]
Thank you ever so much :smile:

**Comment by hnty545** [comment]
Is there a way to reduce the size of java3.so?

**Comment by hnty545** [comment]
I introduced a total of armeabi, armeabi-v7a, arm64-v8a three platforms java3.so, a total of 31M, the impact on the size of the APK is too big.
