### ISSUE TITLE
[Feature Request] In-memory TIFF decoding

### ISSUE THREAD

**Issue by brian-armstrong-discord** [opencv/opencv#8483]
`TiffDecoder` sets `m_buf_supported` to `false`, but this is unnecessary. `libtiff` supports a `TIFFStreamOpen` which takes a `std::istream *` which could be used to decode tiffs. This would make the use of a tmp file unncessary and should generally be cleaner.

**Comment by kinchungwong** [comment]
If OpenCV can provide both a codec-facing abstraction and a library-user (python-wrapper-facing) abstraction for file streams, then it could solve in-memory TIFF and JPEG decoding, encoding, as well as fixing the Windows Unicode file path bug.

I just wrote up a description of this abstraction minutes ago. 
https://github.com/opencv/opencv/issues/5631#issuecomment-291991001

**Comment by jbms** [comment]
I am implementing this, and also fixing the lack of error checking in the use of temporary files for decoding, which can lead to the file being silently truncated (and resulting in either a decoding failure or silent corruption).  This will just fix TIFF decoding to be in line with e.g. PNG decoding --- it won't implement the abstraction suggested by @kinchungwong.
