### ISSUE TITLE
!SOLVED!  Camera Calibration tutorial build fail

### ISSUE THREAD

**Issue by kolecdav** [opencv/opencv#8485]
Solution
----------------------------------------------
I forgot to add 
`find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
target_link_libraries( my_project ${OpenCV_LIBS} )` to cmakelist
-----------------------------------------------

System:
OpenCV => 3.2.0 (latest , in march 2017)
Operating System / Platform => Ubuntu 16.04 64 Bit
Compiler => CLion (gcc | clang )

I am trying to compile the camera calibration tutorial project. source at : https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp

but build not successful. what it basically says, the methods are not overloaded for given input?

In function
cv::read(cv::FileNode const&, bool&, bool) :/usr/local/include/opencv2/core/persistence.hpp:1044:
undefined reference to
cv::read(cv::FileNode const&, int&, int)

here is failed build output.

`/etc/clion-2016.3.2/bin/cmake/bin/cmake --build /home/david/CLionProjects/camera_calib/cmake-build-debug --target camera_calib -- -j 4
Scanning dependencies of target camera_calib
[ 50%] Building CXX object CMakeFiles/camera_calib.dir/camera_calibration.cpp.o
[100%] Linking CXX executable camera_calib
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::read(cv::FileNode const&, bool&, bool)':
/usr/local/include/opencv2/core/persistence.hpp:1044: undefined reference to `cv::read(cv::FileNode const&, int&, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::operator<<(cv::FileStorage&, char const*)':
/usr/local/include/opencv2/core/persistence.hpp:1124: undefined reference to `cv::operator<<(cv::FileStorage&, cv::String const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::operator<<(cv::FileStorage&, char*)':
/usr/local/include/opencv2/core/persistence.hpp:1132: undefined reference to `cv::operator<<(cv::FileStorage&, cv::String const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `void cv::operator>><std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(cv::FileNode const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usr/local/include/opencv2/core/cvstd.inl.hpp:155: undefined reference to `cv::read(cv::FileNode const&, cv::String&, cv::String const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:264: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:265: undefined reference to `cv::FileStorage::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:270: undefined reference to `cv::FileStorage::operator[](char const*) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:271: undefined reference to `cv::FileStorage::release()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:317: undefined reference to `cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:334: undefined reference to `cv::findChessboardCorners(cv::_InputArray const&, cv::Size_<int>, cv::_OutputArray const&, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:337: undefined reference to `cv::SimpleBlobDetector::Params::Params()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:337: undefined reference to `cv::SimpleBlobDetector::create(cv::SimpleBlobDetector::Params const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:337: undefined reference to `cv::findCirclesGrid(cv::_InputArray const&, cv::Size_<int>, cv::_OutputArray const&, int, cv::Ptr<cv::Feature2D> const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:340: undefined reference to `cv::SimpleBlobDetector::Params::Params()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:340: undefined reference to `cv::SimpleBlobDetector::create(cv::SimpleBlobDetector::Params const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:340: undefined reference to `cv::findCirclesGrid(cv::_InputArray const&, cv::Size_<int>, cv::_OutputArray const&, int, cv::Ptr<cv::Feature2D> const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:354: undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:356: undefined reference to `cv::cornerSubPix(cv::_InputArray const&, cv::_InputOutputArray const&, cv::Size_<int>, cv::Size_<int>, cv::TermCriteria)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:360: undefined reference to `cv::VideoCapture::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:364: undefined reference to `cv::VideoCapture::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:368: undefined reference to `cv::drawChessboardCorners(cv::_InputOutputArray const&, cv::Size_<int>, cv::_InputArray const&, bool)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:376: undefined reference to `cv::getTextSize(cv::String const&, int, double, int, int*)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:382: undefined reference to `cv::format(char const*, ...)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:384: undefined reference to `cv::format(char const*, ...)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:387: undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/usr/local/include/opencv2/core.hpp:1292: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:390: undefined reference to `cv::bitwise_not(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/usr/local/include/opencv2/calib3d.hpp:1999: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:398: undefined reference to `cv::fisheye::undistortImage(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/usr/local/include/opencv2/imgproc.hpp:2863: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `main':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:400: undefined reference to `cv::undistort(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:405: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:406: undefined reference to `cv::VideoCapture::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:406: undefined reference to `cv::waitKey(int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:414: undefined reference to `cv::VideoCapture::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:432: undefined reference to `cv::fisheye::estimateNewCameraMatrixForUndistortRectify(cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&, cv::_InputArray const&, cv::_OutputArray const&, double, cv::Size_<int> const&, double)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:434: undefined reference to `cv::fisheye::initUndistortRectifyMap(cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&, int, cv::_OutputArray const&, cv::_OutputArray const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:440: undefined reference to `cv::getOptimalNewCameraMatrix(cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int>, double, cv::Size_<int>, cv::Rect_<int>*, bool)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:441: undefined reference to `cv::initUndistortRectifyMap(cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int>, int, cv::_OutputArray const&, cv::_OutputArray const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:446: undefined reference to `cv::imread(cv::String const&, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:449: undefined reference to `cv::remap(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, int, int, cv::Scalar_<double> const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:450: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:451: undefined reference to `cv::waitKey(int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:264: undefined reference to `cv::FileStorage::~FileStorage()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:264: undefined reference to `cv::FileStorage::~FileStorage()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/usr/local/include/opencv2/calib3d.hpp:1922: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:478: undefined reference to `cv::fisheye::projectPoints(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, double, cv::_OutputArray const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/usr/local/include/opencv2/calib3d.hpp:523: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:482: undefined reference to `cv::projectPoints(cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, double)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/usr/local/include/opencv2/core.hpp:679: undefined reference to `cv::noArray()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `computeReprojectionErrors(std::vector<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > >, std::allocator<std::vector<cv::Point3_<float>, std::allocator<cv::Point3_<float> > > > > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat const&, cv::Mat const&, std::vector<float, std::allocator<float> >&, bool)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:484: undefined reference to `cv::norm(cv::_InputArray const&, cv::_InputArray const&, int, cv::_InputArray const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `runCalibration(Settings&, cv::Size_<int>&, cv::Mat&, cv::Mat&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > >, std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<float, std::allocator<float> >&, double&)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:525: undefined reference to `cv::Mat::eye(int, int, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:530: undefined reference to `cv::Mat::zeros(int, int, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:532: undefined reference to `cv::Mat::zeros(int, int, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:546: undefined reference to `cv::fisheye::calibrate(cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&, cv::_InputOutputArray const&, cv::_InputOutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, cv::TermCriteria)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:556: undefined reference to `cv::calibrateCamera(cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int>, cv::_InputOutputArray const&, cv::_InputOutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, cv::TermCriteria)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:561: undefined reference to `cv::checkRange(cv::_InputArray const&, bool, cv::Point_<int>*, double, double)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:561: undefined reference to `cv::checkRange(cv::_InputArray const&, bool, cv::Point_<int>*, double, double)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `saveCameraParams(Settings&, cv::Size_<int>&, cv::Mat&, cv::Mat&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<float, std::allocator<float> > const&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > > const&, double)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:575: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:622: undefined reference to `cv::FileStorage::writeComment(cv::String const&, bool)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:638: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:649: undefined reference to `cv::Mat::reshape(int, int) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:649: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:653: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:654: undefined reference to `cv::Mat::t() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:658: undefined reference to `cv::Mat::reshape(int, int) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:658: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:661: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:662: undefined reference to `cv::Mat::t() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:665: undefined reference to `cv::FileStorage::writeComment(cv::String const&, bool)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:674: undefined reference to `cv::Mat::reshape(int, int) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:676: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:575: undefined reference to `cv::FileStorage::~FileStorage()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:575: undefined reference to `cv::FileStorage::~FileStorage()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage& cv::operator<< <int>(cv::FileStorage&, int const&)':
/usr/local/include/opencv2/core/persistence.hpp:1112: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1113: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage& cv::operator<< <float>(cv::FileStorage&, float const&)':
/usr/local/include/opencv2/core/persistence.hpp:1112: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1113: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, float)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage& cv::operator<< <bool>(cv::FileStorage&, bool const&)':
/usr/local/include/opencv2/core/persistence.hpp:1112: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1113: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `void cv::operator>><int>(cv::FileNode const&, int&)':
/usr/local/include/opencv2/core/persistence.hpp:1169: undefined reference to `cv::read(cv::FileNode const&, int&, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `void cv::operator>><float>(cv::FileNode const&, float&)':
/usr/local/include/opencv2/core/persistence.hpp:1169: undefined reference to `cv::read(cv::FileNode const&, float&, float)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage& cv::operator<< <cv::Mat>(cv::FileStorage&, cv::Mat const&)':
/usr/local/include/opencv2/core/persistence.hpp:1112: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1113: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, cv::Mat const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage& cv::operator<< <double>(cv::FileStorage&, double const&)':
/usr/local/include/opencv2/core/persistence.hpp:1112: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1113: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, double)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::String::String(char const*)':
/usr/local/include/opencv2/core/cvstd.hpp:622: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::String::~String()':
/usr/local/include/opencv2/core/cvstd.hpp:664: undefined reference to `cv::String::deallocate()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::Mat(cv::Mat const&)':
/usr/local/include/opencv2/core/mat.inl.hpp:421: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
/usr/local/include/opencv2/core/mat.inl.hpp:431: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/mat.inl.hpp:447: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::~Mat()':
/usr/local/include/opencv2/core/mat.inl.hpp:592: undefined reference to `cv::fastFree(void*)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::row(int) const':
/usr/local/include/opencv2/core/mat.inl.hpp:627: undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Range const&, cv::Range const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::clone() const':
/usr/local/include/opencv2/core/mat.inl.hpp:664: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::create(int, int, int)':
/usr/local/include/opencv2/core/mat.inl.hpp:684: undefined reference to `cv::Mat::create(int, int const*, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::release()':
/usr/local/include/opencv2/core/mat.inl.hpp:704: undefined reference to `cv::Mat::deallocate()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::operator()(cv::Range, cv::Range) const':
/usr/local/include/opencv2/core/mat.inl.hpp:724: undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Range const&, cv::Range const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::operator=(cv::Mat&&)':
/usr/local/include/opencv2/core/mat.inl.hpp:1215: undefined reference to `cv::fastFree(void*)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileStorage::getFirstTopLevelNode() const':
/usr/local/include/opencv2/core/persistence.hpp:1232: undefined reference to `cv::FileStorage::root(int) const'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileNode::begin() const':
/usr/local/include/opencv2/core/persistence.hpp:1252: undefined reference to `cv::FileNodeIterator::FileNodeIterator(CvFileStorage const*, CvFileNode const*, unsigned long)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileNode::end() const':
/usr/local/include/opencv2/core/persistence.hpp:1253: undefined reference to `cv::FileNode::size() const'
/usr/local/include/opencv2/core/persistence.hpp:1253: undefined reference to `cv::FileNodeIterator::FileNodeIterator(CvFileStorage const*, CvFileNode const*, unsigned long)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::FileNode::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >[abi:cxx11]() const':
/usr/local/include/opencv2/core/cvstd.inl.hpp:147: undefined reference to `cv::read(cv::FileNode const&, cv::String&, cv::String const&)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::Settings()':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:28: undefined reference to `cv::VideoCapture::VideoCapture()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::read(cv::FileNode const&)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:57: undefined reference to `cv::FileNode::operator[](char const*) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:58: undefined reference to `cv::FileNode::operator[](char const*) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:59: undefined reference to `cv::FileNode::operator[](char const*) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:60: undefined reference to `cv::FileNode::operator[](char const*) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:61: undefined reference to `cv::FileNode::operator[](char const*) const'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o:/home/david/CLionProjects/camera_calib/camera_calibration.cpp:62: more undefined references to `cv::FileNode::operator[](char const*) const' follow
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::validate()':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:121: undefined reference to `cv::VideoCapture::open(int)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:123: undefined reference to `cv::VideoCapture::open(cv::String const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:124: undefined reference to `cv::VideoCapture::isOpened() const'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::nextImage()':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:167: undefined reference to `cv::VideoCapture::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:170: undefined reference to `cv::VideoCapture::operator>>(cv::Mat&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:171: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:174: undefined reference to `cv::imread(cv::String const&, int)'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::readStringList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:182: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:183: undefined reference to `cv::FileStorage::isOpened() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:186: undefined reference to `cv::FileNode::type() const'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:189: undefined reference to `cv::FileNodeIterator::operator++()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:182: undefined reference to `cv::FileStorage::~FileStorage()'
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:182: undefined reference to `cv::FileStorage::~FileStorage()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `Settings::~Settings()':
/home/david/CLionProjects/camera_calib/camera_calibration.cpp:25: undefined reference to `cv::VideoCapture::~VideoCapture()'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::Mat<cv::Point_<float> >(std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&, bool)':
/usr/local/include/opencv2/core/mat.inl.hpp:505: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
CMakeFiles/camera_calib.dir/camera_calibration.cpp.o: In function `cv::Mat::Mat<float>(std::vector<float, std::allocator<float> > const&, bool)':
/usr/local/include/opencv2/core/mat.inl.hpp:505: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
collect2: error: ld returned 1 exit status
CMakeFiles/camera_calib.dir/build.make:94: recipe for target 'camera_calib' failed
make[3]: *** [camera_calib] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/camera_calib.dir/all' failed
make[2]: *** [CMakeFiles/camera_calib.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/camera_calib.dir/rule' failed
make[1]: *** [CMakeFiles/camera_calib.dir/rule] Error 2
Makefile:118: recipe for target 'camera_calib' failed
make: *** [camera_calib] Error 2
`

**Comment by Verru94** [comment]
Hi,
I have the same problem but I haven't understand where add "find_package( OpenCV REQUIRED ) include_directories( ${OpenCV_INCLUDE_DIRS} ) target_link_libraries( my_project ${OpenCV_LIBS} )".

thanks

**Comment by kolecdav** [comment]
Hi,
check out this one
http://docs.opencv.org/3.2.0/db/df5/tutorial_linux_gcc_cmake.html.

These are commands for Cmake. You have to add these commands to cmakelist file so Cmake can find libs and dependencies and link them to your program.
