### ISSUE TITLE
Missing exception/abort while accesing non-existing pixels in Mat object

### ISSUE THREAD

**Issue by SVasilev** [opencv/opencv#8486]
##### System information (version)
- OpenCV => 3.2, downloaded from the official link:
https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.2.0/opencv-3.2.0-vc14.exe/download
- Operating System / Platform => Windows 8.1, 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Hello,
I am reading a pure red image in OpenCV pixel by pixel. As you see in the code I intentionally access the elements with:
<code>
originalImage.at<Vec3b>(Point(i, j));
</code>
instead of:
<code>
originalImage.at<Vec3b>(Point(<b>j, i</b>));
</code>
As you see I am getting strange results. For example the color (221, 221, 221) is found several times.

##### Steps to reproduce

Just run the code from the zip
[OpenCVTest.zip](https://github.com/opencv/opencv/files/881958/OpenCVTest.zip)

**Comment by SVasilev** [comment]
@alalek What is missing?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

More [checks](https://github.com/opencv/opencv/blob/3.2.0/modules/core/include/opencv2/core/mat.inl.hpp#L975-L979) are available in the "Debug" build.
