### ISSUE TITLE
Why compiled into a dynamic library is a little less than java3.so function?

### ISSUE THREAD

**Issue by hnty545** [opencv/opencv#8488]
Set in android.mk
OPENCV_INSTALL_MODULES:=on
OPENCV_LIB_TYPE:=STATIC

Why compiled into a dynamic library is a little less than java3.so function?
example:
n_Mat(int rows, int cols, int type)

I found that the same function was not found in libopencv_core.a, but libopencv_java3.so has this function, or how to compile the libopencv_java3.so it? None of the methods Java API demo cannot run.
——————————————————————————
设置android.mk
OPENCV_INSTALL_MODULES:=on
OPENCV_LIB_TYPE:=STATIC

我编译的动态库比java3.so少一些函数
比如
n_Mat(int rows, int cols, int type)

我发现在libopencv_core.a中也是没有这个函数的，但libopencv_java3.so中却有这个函数，或者说如何编译出libopencv_java3.so呢？没有那些方法java api的demo不能运行的。

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
