### ISSUE TITLE
Is that good to add a QR code detector in OpenCV?

### ISSUE THREAD

**Issue by SayHelloToWorld** [opencv/opencv#8489]
Well, I am a student preparing to attend the GSOC project, and I want to add a QR code recognize function to Opencv, Is this appropriate?

**Comment by mshabunin** [comment]
This question has been answered in the mailing list: https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/opencv-gsoc-2017/LmdsK0OpSXs
