### ISSUE TITLE
OpenCV Android static linking

### ISSUE THREAD

**Issue by zhogar** [opencv/opencv#8490]
Hi,
How to be with static linking?
Without the support of OpenCV Manager (App).
Thanks.

**Comment by alalek** [comment]
This mode is supported. You should put OpenCV ".so" files into APK "libs" folder (refer to documentation of used build system in your app - gradle/Ant/NDK/etc) and change OpenCV loading code (refer to OpenCV Android examples).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by zhogar** [comment]
Is it hardware dependent?
