### ISSUE TITLE
A issue about opencv and python and image process,imread()/imshow()/imwrite() does not support Chinese string

### ISSUE THREAD

**Issue by JIANIXNYUN** [opencv/opencv#8512]
below graph is path and image file in Chinese
![default](https://cloud.githubusercontent.com/assets/26893563/24646961/655ae922-1950-11e7-8b2c-bd9473da218e.PNG)
below graph is using opencv and python to process image in Chinese filename/path with imread(),and show the image in Chinese title with imshow() as you can see,Chinese path/filename/string cannot work with imread()/imshow() in opencv and this situation slao happens in imwrite()
![default](https://cloud.githubusercontent.com/assets/26893563/24647071/e3dac4a2-1950-11e7-941f-dc48dd874a80.PNG)
below graph is I use imread() to load an image in Chinese path and filename,and save it to another Chinese path and filename using imwrite(),and It is depressing that it does not work...
![default](https://cloud.githubusercontent.com/assets/26893563/24647179/68ee759e-1951-11e7-838e-bdf9c6ec6afc.PNG)

**Comment by kinchungwong** [comment]
This is a known issue that affects Windows build of OpenCV. Unfortunately nobody has been able to fix it.

https://github.com/opencv/opencv/issues/4292
https://github.com/opencv/opencv/issues/4242

If you make your own build of OpenCV, it is possible to modify all affected code to use the Win32 Unicode API with `wchar_t` / `std::wstring` paths, or to perform UTF8/UTF16 conversion. Note that, When calling the Win32 narrow string API, string characters are interpreted as Code Page 1252, not as UTF8. In other words, the API will not handle UTF8 strings.

This issue is currently not fixable in the official builds of OpenCV for Windows.

**Comment by catree** [comment]
Maybe related (I don't know much about Unicode), Python + OpenCV for reading: [How do I read an image from a path with Unicode characters?](https://stackoverflow.com/questions/43185605/how-do-i-read-an-image-from-a-path-with-unicode-characters).

**Comment by JIANIXNYUN** [comment]
...................

**Comment by JIANIXNYUN** [comment]
@kinchungwong I hope official opencv can fix it soon after

**Comment by GMTSE** [comment]
Hi,

Sorry to wake up an old beast, but until a solution is found, here are 2 work arounds:
1. Read the image from java (BufferedImage/ByteBuffer), then convert into a Mat
https://stackoverflow.com/questions/14958643/converting-bufferedimage-to-mat-in-opencv
This is probably not very efficient, in CPU/RAM terms, but works
2. Ask windows for the short/MSDOS/8.3 filename. This is very bad pratice, as it make your code not portable, but is more efficient:
```
import com.sun.jna.platform.win32.Kernel32;
import com.sun.jna.win32.W32APIOptions;
import com.sun.jna.Native;
//..
public class MyClass {
  private static Kernel32 kernel32 = (Kernel32) Native.loadLibrary(Kernel32.class, W32APIOptions.UNICODE_OPTIONS);
//..
  public static String convertToWindowsShortName(String longFilename) {
    char result[] = new char[longFilename.length()];
    kernel32.GetShortPathName(longFilename, result, longFilename.length());
    return new String(result).trim();
  }
//..
  public static void main(String[] args) {
    System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    String fnameWithAccents = "c:\\Mon Chémin\\With Spaces\\and\\accentés.jpeg";
    Mat mat = Imgcodecs.imread(MyClass.convertToWindowsShortName(fnameWithAccents)); // this works
    Higui.showimg("My Title", mat); // (this never worked for me... and doc is so sparse, I had to convert back to BufferedImage and show it in JLabel...)
  }
//..
}


```
