### ISSUE TITLE
HoughCircle Algorithm

### ISSUE THREAD

**Issue by tejus-gupta** [opencv/opencv#8515]
HoughCircles uses this algorithm currently:
1.Initialize a 2d accumulator matrix.
2.Compute gradient image using sobel derivative.
3.For each edge pixel, only vote normal to the local gradient direction
4.Select the local maxima points which have votes>vote_thres. 
We have identified the circle centers and now we need to determine their radius.
5.For each circle center, create histogram of points at every radius. Select (global)maxima as radius if histogram height at maxima>vote_thres.
The obvious flaw is that function detects only the larger circle in case of concentric circles. Why isn't every local maxima above vote_thres taken as the radius?

It would be helpful if someone could direct me any discussions on this topic.I have read the referenced method but it's doesn't specify the algorithm to select radius.

**Comment by StevenPuttemans** [comment]
How about coming up with a function that takes both radii, and then supply that to OpenCV through a PR? It is known that OpenCV always takesthe largest radius, probably a decision made with the original implementation.

**Comment by vpisarev** [comment]
indeed, the function does not always determines the circle radius correctly. If you have a better solution, please, implement it and submit pull request.
