### ISSUE TITLE
Face Detection not working in portrait 

### ISSUE THREAD

**Issue by Andiseetu** [opencv/opencv#8516]
HI,

Face Detection (Cascade filters working detect) working on landscape only , rotate to portrait it's not showing detection Rect box...

**Comment by alalek** [comment]
It works as expected.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Andiseetu** [comment]
thank u for your response alalek. 

DetectionBasedTracker.cpp works great to detect faces but not in portrait frames (also modified CameraBridgeViewBase Java class for portrait screen). looks positive reply... thank u again.

**Comment by Andiseetu** [comment]
HI, Thanks  for your reply alalek,
I solved my issue. thanks again
