### ISSUE TITLE
Saving a filename with colons changes the filename

### ISSUE THREAD

**Issue by nobe4** [opencv/opencv#8526]
##### System information (version)
- OpenCV => opencv-python 3.2.0.6 (installed from pip)
- Operating System / Platform => OS X 10.10.5

##### Detailed description

I'm using the `cv2.imwrite` method to write a file to the disk, and I noticed that the filename change if I use `:` in the filename.

##### Steps to reproduce

```.py
#!/usr/bin/env python
import cv2
camera = cv2.VideoCapture(0)
(f, _) = camera.read()
cv2.imwrite('a:b:c.jpeg', f)
```

Result: the file `a/b/c.jpeg` is saved. Which is the full name of the file, and not the file `c.jpeg` inside the folders `a`/`b`.

**Comment by netsurf916** [comment]
What is the intent here?  Using colons in file names can have unexpected results.
https://support.microsoft.com/en-us/help/105763/how-to-use-ntfs-alternate-data-streams
