### ISSUE TITLE
Broken Link in "How to Contribute" pages

### ISSUE THREAD

**Issue by kishankhakhar** [opencv/opencv#8527]
On this following pages of documentation, 
[link to page1](https://github.com/opencv/opencv/wiki/How_to_contribute)
[link to page2](http://code.opencv.org/projects/opencv/wiki/How_to_contribute),
there is a broken link on the first most line that takes me to **404 not found.**
Please look upon it asap.

Broken link URL : http://opencv.org/contribute.html

**Comment by StevenPuttemans** [comment]
Actually the `link to page 1` can be fixed, but the second one will not, since that devzone is deprecated and replaced by issues here.

Replacement link should be http://opencv.org/about.html#contribute

**Comment by mshabunin** [comment]
Fixed, thank you.
