### ISSUE TITLE
can not use opencv in python

### ISSUE THREAD

**Issue by DEGAWONG** [opencv/opencv#8528]
##### Detailed description

when i type import cv2 error occurs like this :+1: 
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_

but it can be used in cpp style normally

**Comment by berak** [comment]
seems related to #8509
