### ISSUE TITLE
Compile with OpenCV 3.2 VS2015 Win10 Failing on i7-7700HQ

### ISSUE THREAD

**Issue by turmansky** [opencv/opencv#8532]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2015 Update 3
Processor => i7-7700HQ

##### Detailed description
After downloading the tip of tree for the OpenCV-master and OPenCV_contrib-master, CMake 3.7..2 was used to setup the solution and then a Release build x64 was attempted.  
Following packages are on the laptop

- Intel Parallel studio Xe 2017 
- Python 3.6.1 
- CUDA 8.0 

Failure is always in opencv_core_AVX while compiling mathfuncs_core.avx.cpp
It reports syntax errors on the CV_CPU_OPTIMIZATION_HAL_NAMESPACE_BEGIN entry on line 76
CMake added for CPU_DISPATCH: SSE4_1;AVX;FP16;AVX2 at the configure step as the HW supports it
Tried removing that and going to SSE4_1 option for CPU_DISPATCH, did not help
Precompiled headers option is off.
WITH_TBB option is off.

The macros are not working correctly it appears for the dispatching
Any ideas as to what could be wrong ?

**Comment by turmansky** [comment]
Removing CV_ENABLE_INTRINSICS solves the build issue
 bug only when using instrinsics . will investigate further but is  anyone has feedback please advise

**Comment by peters** [comment]
I'm facing the same issue, only able to build when disabling intrinsics.

**Comment by turmansky** [comment]
WITH_OPENCL also causes issues
Failure in openCV_core  due to ocl:core at linker step. A whole bunch of unresolved externals

**Comment by turmansky** [comment]
Working CMAKE config
-------------------------
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) (Required is at least version "2.7")
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) (Required is at least version "2.6")
Could NOT find Jasper (missing:  JASPER_LIBRARIES JASPER_INCLUDE_DIR) 
found IPP (ICV version): 9.0.1 [9.0.1]
at: C:/Code/SrcExt/OpenCV/Buildv3.2_x64/3rdparty/ippicv/ippicv_win
CUDA detected: 8.0
CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_61,code=sm_61;-D_FORCE_INLINES
LAPACK(MKL): LAPACK_LIBRARIES: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_sequential.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib
LAPACK(MKL): Support is enabled.
Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
Caffe:   NO
Protobuf:   NO
Glog:   NO
Looking for tiny_dnn.h
Looking for tiny_dnn.h - not found
Module opencv_dnn_modern disabled because tiny-dnn was not found
freetype2:   NO
harfbuzz:    NO
Warning: Matlab bindings will only be built in Release configurations
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/core/opencl_kernels_core.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/imgproc/opencl_kernels_imgproc.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/objdetect/opencl_kernels_objdetect.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/video/opencl_kernels_video.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/dnn/opencl_kernels_dnn.cpp
Torch importer has been enabled. To run the tests you have to install Torch ('th' executable should be available) and generate testdata using opencv_extra/testdata/dnn/generate_torch_models.py script.
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/photo/opencl_kernels_photo.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/bioinspired/opencl_kernels_bioinspired.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/features2d/opencl_kernels_features2d.cpp
Tesseract:   NO
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/calib3d/opencl_kernels_calib3d.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/superres/opencl_kernels_superres.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/tracking/opencl_kernels_tracking.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/xfeatures2d/opencl_kernels_xfeatures2d.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/optflow/opencl_kernels_optflow.cpp
Excluding from source files list (optimization is disabled): C:/Code/SrcExt/OpenCV/Buildv3.2_x64/modules/stitching/opencl_kernels_stitching.cpp
Warning: Matlab bindings will only be built in Release configurations

General configuration for OpenCV 3.2.0-dev =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            C:/Code/SrcExt/OpenCV/opencv_contrib-master/modules/
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2017-04-09T13:57:25Z
    Host:                        Windows 10.0.14393 AMD64
    CMake:                       3.7.2
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3
      requested:                 SSSE3
    Dispatched code generation:  SSE4_1 FP16 AVX AVX2
      requested:                 SSE4_1 AVX FP16 AVX2
      SSE4_1 (0 files):          + SSE4_1
      FP16 (0 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (0 files):             + SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (0 files):            + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24215.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi       /wd4251 /wd4324 /wd4275 /wd4589 /MP8  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi       /wd4251 /wd4324 /wd4275 /wd4589 /MP8  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi         /MP8  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi         /MP8  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32 vfw32 C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_sequential.lib C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib cudart nppc nppi npps cublas cufft -LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64
    3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf

  OpenCV modules:
    To be built:                 cudev core cudaarithm flann imgproc ml objdetect phase_unwrapping plot reg surface_matching video xphoto bgsegm cudabgsegm cudafilters cudaimgproc cudawarping dnn face fuzzy imgcodecs photo shape videoio xobjdetect cudacodec highgui ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo datasets rgbd stereo structured_light superres tracking videostab xfeatures2d ximgproc aruco optflow stitching matlab
    Disabled:                    world contrib_world
    Disabled by dependency:      -
    Unavailable:                 java python2 python3 viz cnn_3dobj cvv dnn_modern freetype hdf sfm

  Windows RT support:            NO

  GUI: 
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        libjpeg (ver 90)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.24)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.64.101)
      avformat:                  YES (ver 57.56.100)
      avutil:                    YES (ver 55.34.100)
      swscale:                   YES (ver 4.2.100)
      avresample:                YES (ver 3.1.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Parallel framework:            Concurrency

  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     C:/Code/SrcExt/OpenCV/Buildv3.2_x64/3rdparty/ippicv/ippicv_win
    Use IPP Async:               NO
    Use Lapack:                  YES (C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_sequential.lib C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib)
    Use Eigen:                   YES (ver 3.3.3)
    Use Cuda:                    YES (ver 8.0)
    Use OpenCL:                  NO
    Use OpenVX:                  NO
    Use custom HAL:              NO

  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  YES
    USE NVCUVID:                 NO
    NVIDIA GPU arch:             30 61
    NVIDIA PTX archs:
    Use fast math:               NO

  Python 2:
    Interpreter:                 NO

  Python 3:
    Interpreter:                 C:/Code/SrcExt/Python3.6.1/python.exe (ver 3.6.1)

  Python (for build):            C:/Code/SrcExt/Python3.6.1/python.exe

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:
    mex:                         C:/Program Files/MATLAB/R2016b/bin/mex.bat
    Compiler/generator:          Working

  Documentation:
    Doxygen:                     C:/Program Files/doxygen/bin/doxygen.exe (ver 1.8.13)

  Tests and samples:
    Tests:                       YES
    Performance tests:           YES
    C/C++ Examples:              NO

  Install path:                  C:/Code/SrcExt/OpenCV/Buildv3.2_x64/install

  cvconfig.h is in:              C:/Code/SrcExt/OpenCV/Buildv3.2_x64
-----------------------------------------------------------------

Configuring done
Generating done

**Comment by turmansky** [comment]
Heres another- Cannot build opencv_world with CUDA 8.0 and TBB 2017
 NVCC error on cuda_compile_generated_median_filter.cu.obj: fatal error C1083: Cannot open include file: 'tbb/tbb.h': No such file or directory
The TBB location is correct. Its somehow not getting to CUDA only in building opencv_world
Building with opencv_world uncheked and all separate DLL's is OK

**Comment by alalek** [comment]
@turmansky Could you please check this patch: #8571 ?

**Comment by peters** [comment]
@alalek 👍
