### ISSUE TITLE
 Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags

### ISSUE THREAD

**Issue by dxqxiaoqiang** [opencv/opencv#8536]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => ubuntu
- Compiler =cmake

**Comment by alalek** [comment]
You should install required dependencies (`-dev` packages of glog/gflags, try something like "libgoogle-glog-dev").
After that you must rerun cmake from scratch (clean build directory): CMake caches system configuration which was changed by packages installation.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by dxqxiaoqiang** [comment]
I try to replace "make install "with "libgoogle-glog-dev",but things go wrong.Like blow:
Failed to find glog - Caller defined GLOG_INCLUDE_DIR: /usr/local/include does not contain glog/logging.h header.
-- Failed to find Ceres - Missing required Ceres dependency: Glog, please set GLOG_INCLUDE_DIR.
-- Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags
I really done not know what's wrong with this? If Ceres can only find  static library ,so with cmake ? But sfm
just find shared library?@alalek

**Comment by alalek** [comment]
Auto-detection supports only a subset of all possible versions and configurations of package/systems. Probably you should adapt script to support your current system environment.
Also you can try to pass correct values of mentioned variables directly to CMake via `-D` parameters. Something like [this](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/10536/steps/cmake/logs/vars):
```
GFLAGS_INCLUDE_DIR=/usr/include
GFLAGS_IN_GOOGLE_NAMESPACE=1
GFLAGS_LIBRARY=/usr/lib/x86_64-linux-gnu/libgflags.so
GFLAGS_NAMESPACE=google

GLOG_INCLUDE_DIR=/usr/include
GLOG_LIBRARY=/usr/lib/x86_64-linux-gnu/libglog.so
Glog_LIBS=/usr/lib/x86_64-linux-gnu/libglog.so
```

BTW, glog/gflags autodetection doesn't work on Ubuntu 16.04 at this moment, but it works on Ubuntu 14.04.

**Comment by alalek** [comment]
Please try this fix from opencv_contrib: https://github.com/opencv/opencv_contrib/pull/1112

**Comment by dxqxiaoqiang** [comment]
thank you so much .I have sloved my problem by using ubuntu 14.04.   Thanks again. @alalek

**Comment by cv3d** [comment]
Glog/Gflags dependencies are bothersome, and does not seem like a necessity!
@alalek If it is desired, I can consider proposing a PR that removes them.
