### ISSUE TITLE
INSTALL and TESTING guide

### ISSUE THREAD

**Issue by pranitbauva1997** [opencv/opencv#8541]
I was trying to install and test the latest master branch so that I can get started with contributing but I couldn't find any particular `INSTALL` guide. Furthermore, I can see lots of tests already included but I have no clue of how to run those. Of course, all of these things can be learned by seeing the source code, but will it not be better if there is a seperate `INSTALL` guide and a `TESTING` guide which we can link with the `CONTRIBUTING` guide.

PS: I managed to install opencv by reading up on CMakeLists.txt . But I strongly believe that this actually acts as an initial barrier for contributing.

**Comment by csukuangfj** [comment]
You can find the installation guide for different operating systems in the documentation.
For example, <http://docs.opencv.org/3.2.0/df/d65/tutorial_table_of_content_introduction.html>

**Comment by pranitbauva1997** [comment]
@csukuangfj And how can I run the test suite?

**Comment by csukuangfj** [comment]
If you managed to read the `CMakeLists.txt` further or if you read its documentation about [installation](http://docs.opencv.org/trunk/df/d65/tutorial_table_of_content_introduction.html) carefully, you would find that there are two flags:
 - `BUILD_TESTS`
 - `INSTALL_TESTS`

When you build OpenCV with the above two flags enabled, then after running `make install`, you
can find some executables inside the installation directory, such as `opencv_test_core`, `opencv_perf_core` and so on, which you can run locally.

**Comment by pranitbauva1997** [comment]
@csukuangfj Thanks a lot! I skipped that part.

I think this issue can now be closed.
