### ISSUE TITLE
OpenCV 3.2.0-dev: lower FPS performance on internal Retina Display vs external Dell Display (thunderbolt/displayport)

### ISSUE THREAD

**Issue by HodorTheCoder** [opencv/opencv#8545]
##### System information (version)
- OpenCV => 3.2.0-dev
- Operating System / Platform => macOS Sierra 10.12.4/ Macbook Pro (Retina, 15-inch, Mid 2015)
- Compiler => gcc: Apple LLVM version 8.1.0 (clang-802.0.38)

##### Detailed description

I'm seeing a fairly noticeable difference in FPS when using cv2 depending on if I use my Macbook Pro's internal Retina display (changing resolution makes no difference) versus using an external dell 24" monitor connected through thunderbolt -> displayport.  I'm talking 35 fps on the external monitor vs 25 fps on internal Retina display.  I'm using the latest git dev version to do some ball tracking in Python (2.7.13, homebrew edition no macOS).  

Using a qt5 build versus non qt5 increases FPS, but there is still a difference.

Is this a driver issue of some kind or an issue with how I built OpenCV?  Here are the system specs:

- 2.5 GHz Intel Core i7
- 16 GB 1600 MHz DDR3
- AMD Radeon R9 M370X 2048 MB
- Intel Iris Pro 1536 MB

Could it not be using my Radeon for some reason?  It's extremely bizarre.  I apologize if this has been broached but I couldn't find anything and I haven't been able to reproduce this on other programs (ie: youtube, etc)

I'm using the fps() command from the Python imutils package to track frames per second.  For procesing a 30fps video, I see

- Dell monitor: 35fps
- Internal Retina: 24.9fps

It will even switch if I move the window back and forth during playback which would indicate to me it's a driver issue.  

##### Steps to reproduce

Here's my cmake command.  The Python just uses good old cv2.videoCapture() and cv2.imshow().

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
		-D CMAKE_INSTALL_PREFIX=/usr/local \
		-D INSTALL_PYTHON_EXAMPLES=ON \
		-D OPENCV_EXTRA_MODULES_PATH=~/code/opencv/opencv_contrib/modules \
		-D PYTHON2_LIBRARY=/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib \
		-D PYTHON2_INCLUDE_DIR=/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7/  \
		-D BUILD_EXAMPLES=ON \
		-D BUILD_opencv_python2=ON \
		-D BUILD_opencv_python3=OFF \
		-D INSTALL_C_EXAMPLES=OFF ..
```

**Comment by maxballenger** [comment]
I am experiencing the exact same issue with opencv-python 4.1.0.25. Macbook with MacOS catalina. External Dell display through thunderbolt. Max FPS 3x as high on the external screen as the Macbook Retina.
