### ISSUE TITLE
Not able to use camera calibration sample with a video file

### ISSUE THREAD

**Issue by IndySupertramp** [opencv/opencv#8551]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

- OpenCV => :grey_question: How do I put the file location of the video file in the xml configuration file?

##### Detailed description

I am using Visual Studio 2015 on Windows 64 bit and using OpenCV 3.2 for my project on vehicle speed estimation using optical flow and 3D modeling . I need to calibrate my DSLR and  record some traffic videos and estimate a 3D cuboid and then optimize it using LMA. The problem is when I put the file location of the video file containing the chessboard, it shows me an error that the video file could not be found. I am follow the steps written in config XML file exactly. The example say the file location should be like this /tmp/x.avi, my video is inside the folder "video" inside VS project folder so I put /video/traffic.MOV but it is not working. I need some help.

**Comment by saskatchewancatch** [comment]
I've never tried this example, but based on what you've said (`/video/traffic.MOV`), it seems you're specifying a UNIX-style path; you're working in Windows.

The example in the sample XML file in the camera calibration tutorial page specifies a UNIX-style path. 

Change your path to a Windows-style path (one that uses backslashes) and it may work. 

If you are specifying a _relative path_, take care to format the path string properly).

I suggest you just use an _absolute path_ to refer to your video file to get started.

I believe you may also need to escape the backslashes in the Windows path: `C:\Users\My Name\Desktop\test\input.txt` => 
`C:\\Users\\My Name\\Desktop\\test\\input.txt`.

**Comment by IndySupertramp** [comment]
@saskatchewancatch I just did what you told me:
C:\\Users\\indie\\Documents\\Visual Studio 2015\\Projects\\Intrinsics2\\Intrinsics2\\chessboard.avi

but now it's showing me this error:
OpenCV Error: Unknown error code -49 (Input file is empty) in cvOpenFileStorage, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\persistence.cpp, line 4422

The input file is clearly not empty.
What do I do?
Thanks.

**Comment by saskatchewancatch** [comment]
I don't have a Windows machine to try this out, but on Ubuntu-64 (xenial) with OpenCV 3.1.0 , running the built binary of the camera calibration tutorial `cpp-tutorial-camera_calibration` (this is probably the one you're referring to as it's the one that accepts the xml configuration file) , I get this error when I specify a video:

`OpenCV Error: Parsing error (grb_1.mpg(0): Too long string or a last string w/o newline) in icvXMLSkipSpaces, file /home/anon/opencv/modules/core/src/persistence.cpp, line 1807
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/anon/opencv/modules/core/src/persistence.cpp:1807: error: (-212) grb_1.mpg(0): Too long string or a last string w/o newline in function icvXMLSkipSpaces
`

However that example does seem to work with a list of images specified in another xml file. If the video path is blocking you, possibly you could work around it for now by running the calibration tutorial on a list of images specified in an xml file. See `samples/cpp/tutorial_code/calib3d/camera_calibration/VID5.xml` for an example.

It may be helpful for whoever ends up taking a look into this if you upload your video, assuming if it's of a reasonable size.

**Comment by saskatchewancatch** [comment]
The sample @IndySupertramp appears to be using for camera calibration is [camera_calibration.cpp](https://github.com/opencv/opencv/blob/3.1.0/samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp)

In the XML/YAML configuration file that is supplied to that sample, the `Input` element can specify a video file, camera, or another XML/YAML config file that contains a list of image files to use for calibration.

The sample crashes when a video file is specified for the input. I suspect the source of the problem could be in the `validate` function in the `Settings` class that's defined in the sample ([camera_calibration.cpp](https://github.com/opencv/opencv/blob/3.1.0/samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp#L109)), where the type of `Input` is checked for:
```
                if (readStringList(input, imageList))
                {
                    inputType = IMAGE_LIST;
                    nrFrames = (nrFrames < (int)imageList.size()) ? nrFrames : (int)imageList.size();
                }
                else
                    inputType = VIDEO_FILE;
```

Presumably with a video file it's supposed to hit the `else` block. Inside `readStringList`, the video file name is opened using `FileStorage` which is used to read in XML/YAML files.

The `else` never gets hit as program crashes when `FileStorage` tries to read a video file?? Possibly a quick fix is to check for file name extension, and presume video if file doesn't have xml or yaml extension.

**Comment by StevenPuttemans** [comment]
> C:\\Users\\indie\\Documents\\Visual Studio 2015\\Projects\\Intrinsics2\\Intrinsics2\\chessboard.avi

Do not use spaces in filenames for OpenCV. They screw up the path. So try something like `C:\\test\\test.avi` first.

**Comment by saskatchewancatch** [comment]
@StevenPuttemans I tried a Windows platform build of 3.1.0 and some debugging shows that the sample will pass in the video file -if that's what you specify in the XML/YAML file- to FileStorage, which is not right.

@IndySupertramp Your best course of action is probably to just use a list of calibration images instead of a video.

**Comment by StevenPuttemans** [comment]
> I tried a Windows platform build of 3.1.0 

Thats asking for issues, 3.1 is deprecated and no longer supported. I guess 3.2 has been around for quite some time now. Could you first try latest master to see if this persists?

**Comment by saskatchewancatch** [comment]
@StevenPuttemans In master that sample reads in a video file without crashing. Tried Windows and Linux builds. The master version checks if the input is an XML/YAML file before attempting to read it.

I suppose this ticket can be closed.
