### ISSUE TITLE
OpenCV 3.2.0 build issue with CUDA 8.0 

### ISSUE THREAD

**Issue by serhannn** [opencv/opencv#8556]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc 5.4.1

##### Description

I'm trying to compile OpenCV 3.2.0 (also on contrib) with CUDA 8.0. I get the following error related to `cudalegacy` while compiling:

```
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut_32s8u'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcutInitAlloc'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcutFree'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut8_32s8u'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcutGetSize'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut8GetSize'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut8InitAlloc'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut_32f8u'
../../lib/libopencv_cudalegacy.so.3.2.0: undefined reference to `nppiGraphcut8_32f8u'
```

I found the fix [1089612](https://github.com/opencv/opencv/commit/10896129b39655e19e4e7c529153cb5c2191a1db) and checked my `modules/cudalegacy/src/graphcuts.cpp` file. It already contained the fix so it didn't help.

This problem seems to have been fixed in the master branch so I can't figure out what is wrong. Is there a workaround like disabling `cudalegacy`? I actually don't need the stuff in there but I need the other CUDA modules (e.g. `cudaoptflow`).

##### Steps to reproduce

My cmake command is:
```
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D WITH_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_CUBLAS=1 \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
    -D WITH_GSTREAMER0=ON \
    -D BUILD_TIFF=ON \
    -D BUILD_EXAMPLES=ON ..
```

**Comment by StevenPuttemans** [comment]
Can you try `-D BUILD_opencv_cudalegacy=OFF`?

**Comment by serhannn** [comment]
This solved my problem, thank you!

**Comment by StevenPuttemans** [comment]
You are welcome!

**Comment by StevenPuttemans** [comment]
@alalek could you add the bug label to this? Cause I my opinion this still needs to be solved.

**Comment by MikeZhu92** [comment]
I found this link helpful:

http://answers.opencv.org/question/95148/cudalegacy-not-compile-nppigraphcut-missing/

This is not cuda setup issue.

**Comment by StevenPuttemans** [comment]
which means this can be closed, because the fix already got included in latest master branch

https://github.com/opencv/opencv/commit/10896129b39655e19e4e7c529153cb5c2191a1db
