### ISSUE TITLE
OpenCV master not compiling on Mac  (4d3cef35c2ac4669ceb72269915cb69d4fece986)

### ISSUE THREAD

**Issue by roxlu** [opencv/opencv#8570]
##### System information (version)
- OpenCV => master branch from github, 4d3cef35c2ac4669ceb72269915cb69d4fece986
- Operating System / Platform => macOS Sierra 10.12.1
- Compiler => 

        Apple LLVM version 8.1.0 (clang-802.0.41)
        Target: x86_64-apple-darwin16.1.0
        Thread model: posix
        InstalledDir: 
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

##### Detailed description

OpenCV fails to compile on above system, with error:

    src/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:76:1: error: expected '{'
    CV_CPU_OPTIMIZATION_HAL_NAMESPACE_BEGIN
    ^

##### Steps to reproduce

I've used this CMake to compile opencv in my project:
https://gist.github.com/roxlu/13b90cd7e717cdac1449974a31456e86

**Comment by alalek** [comment]
CMake's `ExternalProject` is not supported. You should use `find_package(OpenCV)` instead.

**Comment by roxlu** [comment]
@alalek sure, though that's unrelated; external project just executes opencv's cmake file.

**Comment by alalek** [comment]
Try to remove/cleanup build directories and try again.
We don't observe [build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_noOCL-mac/builds/10070) failures on MacOSX.

**Comment by roxlu** [comment]
@alalek okay good to know I'll use Win then

**Comment by alalek** [comment]
@roxlu There is report for similar issue on Win10: #8532 
But I can't reproduce it too.
