### ISSUE TITLE
opencv cmake

### ISSUE THREAD

**Issue by dxqxiaoqiang** [opencv/opencv#8573]
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 14.04
- Compiler => cmake3.8
-->
when i use SFM in my system, i faced with the following error:
-Initialize nViewMatcher ... OK
F0412 18:47:20.827188  2826 nRobustViewMatching.cc:57] Failed loading image: dataset_files.txt/resized_IMG_2889.jpg
*** Check failure stack trace: ***
    @     0x7f82f777edaa  (unknown)
    @     0x7f82f777ece4  (unknown)
    @     0x7f82f777e6e6  (unknown)
    @     0x7f82f7781687  (unknown)
    @     0x7f82f9ab80e4  libmv::correspondence::nRobustViewMatching::computeData()
    @     0x7f82f9ab48d3  libmv::correspondence::nRobustViewMatching::computeCrossMatch()
    @     0x7f82f9aaef27  cv::sfm::libmv_solveReconstructionImpl()
    @     0x7f82f9aaf7ab  cv::sfm::SFMLibmvReconstructionImpl<>::run()
    @     0x7f82f9aac1d4  cv::sfm::SFMLibmvReconstructionImpl<>::run()
    @     0x7f82f9a9af70  cv::sfm::reconstruct_<>()
    @     0x7f82f9a9b20c  cv::sfm::reconstruct()
    @           0x409de4  main
    @     0x7f82f7e7bec5  (unknown)
    @           0x409699  (unknown)
    @              (nil)  (unknown)
Performing Cross Matching ... Aborted (core dumped)
I don't know where is wrong? Thanks for your coming answers.  @sweeneychris

**Comment by mprat** [comment]
It tells you the error is in loading the image: `Failed loading image: dataset_files.txt/resized_IMG_2889.jpg`.  Is that a real file path? Your program thinks that is not an image file.

**Comment by dxqxiaoqiang** [comment]
Thanks for your answers. But i don't know what i can do about this problem.  Can you give me some instructions about how can i solve this issue. @mprat
