### ISSUE TITLE
Undefined behavior in cv::rectangle()

### ISSUE THREAD

**Issue by hovnatan** [opencv/opencv#8577]
- OpenCV => 3.2
- Operating System / Platform => Fedora 25
- Compiler => gcc 6.3.1

##### Detailed description

Undefined behavior in `cv::rectangle()` when two identical points passed.

##### Steps to reproduce
Try running the following: 

    cv::rectangle(im, cv::Point(1000, 1000), cv::Point(1000, 1000), 255, CV_FILLED);

 in `valgrind`. The output is
```
==4102== Conditional jump or move depends on uninitialised value(s)
==4102==    at 0xBFF483F: cv::FillConvexPoly(cv::Mat&, cv::Point_<long> const*, int, void const*, int, int) (in /usr/local/lib/libopencv_imgproc.so
.3.2.0)
==4102==    by 0xBFFA096: cv::rectangle(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int) 
(in /usr/local/lib/libopencv_imgproc.so.3.2.0)
````
As a result of this I saw two different resultant images on two different computers. If two identical points are not supported then I think an exception should be thrown.

**Comment by alalek** [comment]
Duplicate: #7957
Try latest code from "master" branch.
