### ISSUE TITLE
Cannot use openCV in new Samsung Galaxy Edge.

### ISSUE THREAD

**Issue by leeman12345** [opencv/opencv#8579]
I'm making a photo comparison app using OpenCV. The app with OpenCV works for on other phones but not on my Samsung Galaxy 7 edge. 

Are there any known issues with OpenCV and new Android builds?

I'm running Android 7.0

**Comment by vpisarev** [comment]
You should probably dig into the problem by yourself, we do not have such a phone at hand.

**Comment by leeman12345** [comment]
This is not phone related, it is related to Android version.

The OpenCV App does not work on the latest Android version. 

You can check this with any new phone.
