### ISSUE TITLE
No rule to make target\

### ISSUE THREAD

**Issue by vsuriya93** [opencv/opencv#8591]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
How to solve this problem?

[ 82%] Built target example_aruco_detect_markers
[ 82%] Built target opencv_test_aruco
[ 83%] Built target opencv_optflow
[ 83%] Built target example_optflow_dis_opticalflow
[ 83%] Built target example_optflow_gpc_evaluate
[ 83%] Built target example_optflow_gpc_train
[ 83%] Built target example_optflow_motempl
[ 83%] Built target example_optflow_optical_flow_evaluation
[ 83%] Built target example_optflow_pcaflow_demo
[ 83%] Built target example_optflow_simpleflow_demo
[ 83%] Built target opencv_perf_optflow
[ 84%] Built target opencv_test_optflow
make[1]: *** No rule to make target `modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all', needed by `modules/stitching/CMakeFiles/opencv_stitching.dir/all'.  Stop.
make: *** [all] Error 2

**Comment by alalek** [comment]
This is not OpenCV bug. Try to clean your build directory at first.

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
