### ISSUE TITLE
Can OpenCV open Mobile phone's built-in camera in jni？

### ISSUE THREAD

**Issue by Igamegum** [opencv/opencv#8594]
Hmm ，I am developing an app ，I need to get the image from mobile phone's built-in  camera in jni with C/C++，What Should I do？

**Comment by alalek** [comment]
http://stackoverflow.com/questions/7297577/take-a-picture-with-android-ndk-camera-api

OpenCV's way is to grab Camera image into "Mat" (via Java "CameraBridgeViewBase") and then use it in JNI C++ code.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Igamegum** [comment]
I have found some answer ，somebody said OpenCV provide an api ，it can open camera in JNI C++ ，it looks like modules/androidcamera/camera_wrapper ，but i can not found these api in docs,  is it true？

**Comment by alalek** [comment]
Android NativeCamera is [not supported](https://github.com/opencv/opencv/issues?utf8=%E2%9C%93&q=is%3Aissue%20NativeCamera) anymore and removed from OpenCV 3.x.
