### ISSUE TITLE
“Functional-style cast from id to double is not allowed” when building opencv with aruco on iOS

### ISSUE THREAD

**Issue by keyblade95** [opencv/opencv#8595]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => macOS Sierra 10.12.4
- Compiler => Xcode

##### Detailed description

I'm trying to make an iOS app that can detect Aruco markers. So, I downloaded opencv2.framework for iOS, but I realized that Aruco is not included in that. Following this page http://docs.opencv.org/2.4/doc/tutorials/introduction/ios_install/ios_install.html, I compiled manually adding opencv_contrib (https://github.com/opencv/opencv_contrib.git) module folder into the opencv module folder. This process worked fine and in Xcode I can access Aruco functions. But I also get this strange error:
<img width="893" alt="schermata 2017-04-16 alle 19 19 12" src="https://cloud.githubusercontent.com/assets/11407258/25096227/a3dba0f2-239f-11e7-951d-e738a8d5d862.png">
I've tried debugging and runtime v is passed as a double variable. The explicit cast (double)v is not valid too. How can I fix this?

**Comment by alalek** [comment]
Complete build log is required.

**Comment by alalek** [comment]
> module folder into the opencv module folder.

It is better to follow readme from this page: https://github.com/opencv/opencv_contrib
OpenCV 2.4 is not supported in contrib modules.

**Comment by keyblade95** [comment]
Complete build log:
[Build OpenCV_2017-04-17T12-46-31.pdf](https://github.com/opencv/opencv/files/926222/Build.OpenCV_2017-04-17T12-46-31.pdf)

**Comment by alalek** [comment]
It blames on this line:
```
cameraMatrix = (Mat_<double>(3,3) << camMatrix[0], camMatrix[1], camMatrix[2],
```
from the file `OpenCVWrapper.mm:47:54`.
Try to check for extra comma (`,`) symbols or add explicit cast to double: `(double)camMatrix[0]`.

> **id** is a pointer to any Objective-C object (objc_object). It is not just a void pointer and you should not treat it as so. It references an object that should have a valid isa pointer. The values that can be stored in id are also not just limited to NSObject and its descendants, which starts to make sense of the existence of the NSObject protocol as well as the NSProxy class which does not even inherit from NSObject. The compiler will allow you to assign an object referenced by type id to any object type, assign any object type to id, as well as send it any message (that the compiler has seen) without warning.

(http://stackoverflow.com/a/7987150)

Anyway this is not related to OpenCV sources/samples, so I'm closing this.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
