### ISSUE TITLE
Install OpenCV with Cuda 8

### ISSUE THREAD

**Issue by brainstormapps** [opencv/opencv#8607]
Operating System ubuntu 16.04 with Cuda 8.0
OpenCV 3.1.0

Try to install using shell script
https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh

But when execute command
"make j4"

during process I get warning
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

and after 70 to 90 percent of compilation the process stopped with message

![message](https://cloud.githubusercontent.com/assets/4639661/25163765/1201c15a-24e6-11e7-9f8c-173aa43acca9.PNG)

Can any body help me to resolve this issue. My system is using NVIDIA card for neural style (like prisma), which required CUDA for fast gpu processing. So I cannot remove cuda from my system.

**Comment by MrGitHan** [comment]
maybe you could just use "make" rather than "make j4",i guess

**Comment by alalek** [comment]
OpenCV 3.1 release date is before release dates of Ubuntu 16.04 / CUDA 8.0 - so this environment can't be supported well. You should use more fresh OpenCV version.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
