### ISSUE TITLE
How to import OpenCV in a makefile? 

### ISSUE THREAD

**Issue by matheusns** [opencv/opencv#8613]
I want to use OpenCV with a Genicam API  and I wanna try to import the OpenCV to my cpp file. How can I use this? Followiing attached my API makefile and its dependencies.

[archdefs.txt](https://github.com/opencv/opencv/files/934223/archdefs.txt)
[makefile.txt](https://github.com/opencv/opencv/files/934224/makefile.txt)

**Comment by alalek** [comment]
OpenCV is CMake-based project. So it is better to use CMake for integration with other projects.
Other approaches (pkg-config/etc) has limited support and may not work in some configurations.

We have [this Makefile example](https://github.com/opencv/opencv/blob/master/samples/cpp/example_cmake/Makefile) only.


BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
