### ISSUE TITLE
OpenCV 3.2 build fails - stitching module can't find cudawarping.hpp

### ISSUE THREAD

**Issue by DrownedRat** [opencv/opencv#8615]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Win 7 x64
- Compiler => VS 2013

##### Detailed description

The opencv_stitching project fails to build because it cannot find cudawarping.hpp.  The include path for cudawarping is missing from the project settings.  Adding opencv_cudawarping to the list of optional modules in CMakeLists.txt for the stitching module seemed to fix it but I'm relatively new at this so I don't know if there could be other ramifications for modifying that file.

##### Steps to reproduce

Here is my CMake output & config.
[CMake Output.txt](https://github.com/opencv/opencv/files/936195/CMake.Output.txt)
[CMakeVars.txt](https://github.com/opencv/opencv/files/936155/CMakeVars.txt)

**Comment by alalek** [comment]
> Adding opencv_cudawarping to the list of optional modules in CMakeLists.txt

This is valid fix (this adds include directories for compilation). Could you create PR?

```.diff
-OPTIONAL opencv_cudaarithm opencv_cudafilters opencv_cudafeatures2d opencv_cudalegacy ${STITCHING_CONTRIB_DEPS}
+OPTIONAL opencv_cudaarithm opencv_cudawarping opencv_cudafilters opencv_cudafeatures2d opencv_cudalegacy ${STITCHING_CONTRIB_DEPS}
```

BTW, Probably "opencv_cudafilters" can be removed from this list (looks like it is not used in stitching module).

**Comment by anupamsobti** [comment]
PR: https://github.com/opencv/opencv/pull/8727

This is my first pull request. I hope I didn't miss anything!
