### ISSUE TITLE
const correctness bug in calcBackProject and calcHist

### ISSUE THREAD

**Issue by IglooMark** [opencv/opencv#8617]
In versions up to and including 3.2.0-dev, The "ranges" param has the wrong type for const-correctness, in the following two functions:

```
void calcBackProject(const Mat* images, int nimages, const int* channels, InputArray hist, OutputArray backProject, const float** ranges, double scale=1, bool uniform=true )
void calcHist(const Mat* images, int nimages, const int* channels, InputArray mask, OutputArray hist, int dims, const int* histSize, const float** ranges, bool uniform=true, bool accumulate=false )
```
if "ranges" is unmodified by these functions, it should have type const float * const *; otherwise, you can get errors like this when passing in parameters that should work:

error: invalid conversion from ‘const float* const*’ to ‘const float**’ [-fpermissive]

**Comment by sovrasov** [comment]
@IglooMark we can't change the prototype of `calcBackProject` and `calcHist` due to binary compatibility compliance requirements. You can provide a PR with desired overloads for these functions.

**Comment by IglooMark** [comment]
Fair enough. It seems odd that this would affect binary compatibility, since we're just adding a "const" and the underlying type of the parameter is the same (pointer-to-pointer-to-float) -- but I see from this:

 https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

..that changing the const/volatile parameters does count as a signature change.
