### ISSUE TITLE
OpenCV Error: Gpu API call (invalid argument) in copy

### ISSUE THREAD

**Issue by t-pollington** [opencv/opencv#8621]
##### System information (version)

- OpenCV => 2.4
- Operating System / Platform => Ubuntu 16.04 LTS 64 bit
- Compiler => nvcc V8.0.61

##### Detailed description

Need to assign zeroes to a double GpuMat object using decimal form as integer form causes bug

##### Steps to reproduce
**Code:**
```
cv::Mat a_h(977,1,DataType<double>::type);
gpu::GpuMat a_g(977,1,DataType<double>::type,0);
a_g.download(a_h);
cout << "a_h" << a_h;
```

gives an ```OpenCV Error: Gpu API call (invalid argument) in copy, file /.../opencv-2.4/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp, line 882```

**Workaround:**
However if I use 0.0 in ```gpu::GpuMat a_g(977,1,DataType<double>::type,0.0);``` the bug is solved!
(Compiled with ```nvcc `pkg-config --cflags opencv` filename.cu `pkg-config --libs opencv` -o main -arch=sm_50```)

**Comment by alalek** [comment]
```
gpu::GpuMat a_g(977,1,DataType<double>::type,0);
```

Calls [this overload](https://github.com/opencv/opencv/blob/7577f1420d8d2820413f8b36b354f1377844aa28/modules/core/include/opencv2/core/gpumat.hpp#L172):
```
GpuMat(int rows, int cols, int type, void* data, size_t step = Mat::AUTO_STEP);
```
"0" is interpreted here as address for "void* data".

You probably want [this overload](https://github.com/opencv/opencv/blob/7577f1420d8d2820413f8b36b354f1377844aa28/modules/core/include/opencv2/core/gpumat.hpp#L165) with `cv::Scalar` initialization:
```
GpuMat(int rows, int cols, int type, Scalar s);
```

"0.0" uses [this](https://github.com/opencv/opencv/blob/7577f1420d8d2820413f8b36b354f1377844aa28/modules/core/include/opencv2/core/core.hpp#L942) `cv::Scalar` overload.

The right user code is to use `cv::Scalar` explicitly:
```
gpu::GpuMat a_g(977,1,DataType<double>::type, cv::Scalar:all(0));
```

Possible workaround is to forbid calling of overload with "int", something like this: #5388
But this will broke some part of user code, but probably such code was already broken.
