### ISSUE TITLE
Issues installing OpenCV on Ubuntu 17.04

### ISSUE THREAD

**Issue by Mapache03** [opencv/opencv#8622]
Hi, I was installed OpenCV in kubuntu 16.10 with no problem, but I update to Ubuntu GNOME 17.04 but it can´t install libjasper-dev. I install it from source and then, when I´m compiling not found the stdlib.h.

What I should do? new repositories maybe?

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
if error message contains "#include_next" statement, then try to disable precompiled headers (`cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`).

> not found the stdlib.h

if not, then you need to check your C++ compiler via some simple "hello world" program.

**Comment by Mapache03** [comment]
Thanks, I finally can configure it, but cannot install libjasper-dev and libpng12-dev because is not available. The compilation was bad in Ubuntu GNOME 17.04 but it can be finished in Kubuntu 17.04...I'll to investigate it...

**Comment by alalek** [comment]
> cannot install libjasper-dev and libpng12-dev

Almost all 3rdparty dependencies are optional for OpenCV - you can disable them if you don't need them.

Refer to [Ubuntu 17.04 libpng packages page](https://launchpad.net/ubuntu/zesty/amd64/libpng-dev/1.6.26-1). Probably they have other names.

**Comment by adinriv** [comment]
Note that `libjasper-dev` has been removed from Ubuntu 17.04 (https://launchpad.net/ubuntu/zesty/amd64/libjasper-dev/1.900.1-debian1-2.4+deb8u1), and they suggest to use OpenJPEG instead.

Since OpenCV uses `jasper` trying to install it manually may be an option. 

Not sure about using another library, like `openjpeg` instead of `jasper`, in OpenCV.

**Comment by ghagerer** [comment]
On Ubuntu 17.10, e.g., you can install these dependencies manually:

https://packages.ubuntu.com/xenial/amd64/libjasper1/download
https://www.ubuntuupdates.org/package/core/xenial/main/updates/libjasper-dev

**Comment by superbonaci** [comment]
sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt update

**Comment by ayasakhri23** [comment]
I can't find the  libjasper-dev  paquet in ubunto18 so what to do!!

**Comment by sivamsinghsh** [comment]
use this solution step by step and your problem will be resolved
sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt update
sudo apt install libjasper1 libjasper-dev

**Comment by ayasakhri23** [comment]
Thank you

**Comment by sivamsinghsh** [comment]
you are always welcome dear
