### ISSUE TITLE
Build will fail on Win7 with VS2015 after enable BUILD_opencv_world in CMake

### ISSUE THREAD

**Issue by kevin-coder** [opencv/opencv#8623]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2015 x64

##### Detailed description

After enable BUILD_opencv_world var in CMake and then build on VS2015 under Win7 x64 platform, build will fail. However, in previous code base, the same configuration is OK, so this should be a regression issue.

##### Steps to reproduce

1. After start CMake, choose VS2015 x64 compiler, enable the variable named "BUILD_opencv_world", the others configure items can be default, then do "Configure" and "Generate".
2. After "Generate", open the generated project with VS2015, then press F7 to build.
3. After a while, following build error message will pop up.
**ErrMsgBegin**
1>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: uninstall, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: opencv_world, Configuration: Debug x64 ------
3>  matmul.cpp
3>c:\1work\2opensource\opencv-fork\modules\core\src\intel_gpu_gemm.inl.hpp(90): error C2039: 'intel_gemm_oclsrc': is not a member of 'cv::ocl::core'
3>  C:\1Work\2OpenSource\OpenCVTrunkBuild\modules\world\opencl_kernels_core.hpp(13): note: see declaration of 'cv::ocl::core'
3>c:\1work\2opensource\opencv-fork\modules\core\src\intel_gpu_gemm.inl.hpp(90): error C2065: 'intel_gemm_oclsrc': undeclared identifier
4>------ Skipped Build: Project: opencv_perf_tests, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: opencv_tests, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: opencv_modules, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 206 up-to-date, 7 skipped ==========
**ErrMsgEnd**
4. Attachment is the CMakeVar file.
[CMakeVars.txt](https://github.com/opencv/opencv/files/944903/CMakeVars.txt)

**Comment by alalek** [comment]
No, you should re-run CMake after OpenCV code update.
Name of OpenCL program is [valid](https://github.com/opencv/opencv/blob/636ab095b0dda4f63da71e681e47d5e69e6be6b7/modules/core/src/opencl/intel_gemm.cl)

**Comment by kevin-coder** [comment]
Yes, every time when I update the source code, I re-run the CMake, do configure and generate in order to refresh the CMakeVar, before this error appears, I did the same procedure every time but no build error before, except this one.
