### ISSUE TITLE
Cmake cannot find source file for latest OpenCV 3.2 with CUDA enabled on cmake .

### ISSUE THREAD

**Issue by daemonPainter** [opencv/opencv#8625]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Linux Ubuntu 16.04
- Compiler => cmake 3.5.1

##### Detailed description

I've just pulled the last commits after a long time (i.e. early 3.1). I wanted to update my release & enable CUDA (I've just installed CUDA 8).
After setting up Cmake options using ccmake, I got this report:

```
CMake Error at /home/user/opencv/cmake/OpenCVUtils.cmake:957 (add_library):
   Cannot find source file:

     /home/user/opencv/<build_dir>/modules/xfeatures2d/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_surf.cu.o

   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
   .hxx .in .txx
 Call Stack (most recent call first):
   /home/user/opencv/cmake/OpenCVModule.cmake:805 (ocv_add_library)
   /home/user/opencv/cmake/OpenCVModule.cmake:745 (_ocv_create_module)
   /home/user/opencv/cmake/OpenCVModule.cmake:964 (ocv_create_module)
   /home/user/opencv_contrib/modules/contrib_world/CMakeLists.txt:38 (ocv_define_module)

```

##### Steps to reproduce

```
cd <opencv_local_folder>
git remote -v update
git pull
cd <build_dir>
ccmake .
```

At this point, set WITH_CUDA=ON and configure. After configuration, exit ccmake with its 'g' command.

**Comment by alalek** [comment]
> pulled the last commits after a long time
> I've just installed CUDA 8

You should cleanup your build directory to eliminate CMake cache settings. This is required for the most part of cases with changing configuration or settings.

Please avoid posting usage questions here - use Users OpenCV Q/A forum: http://answers.opencv.org instead.
