### ISSUE TITLE
MathJax CDN is shutting down

### ISSUE THREAD

**Issue by magical** [opencv/opencv#8630]
OpenCV uses MathJax in its Doxygen documentation. Like most users, OpenCV links to an external copy of the library hosted at the official CDN, cdn.mathjax.com. MathJax is [shutting down][] cdn.mathjax.org on April 31st. 

OpenCV needs to either update the doxygen config to point at an [alternative CDN][]  or self-host the mathjax libraries.

All the old documentation will need to be rebuilt as well.

https://github.com/opencv/opencv/blob/383559c2285baaf3df8cf0088072d104451a30ce/doc/Doxyfile.in#L177

[shutting down]: https://www.mathjax.org/cdn-shutting-down/
[alternative cdn]: https://www.mathjax.org/cdn-shutting-down/#alternative-cdn-providers

**Comment by mshabunin** [comment]
I've replaced all links in older documentation (3.0.0, 3.1.0, 3.2.0).
Thank you!
