### ISSUE TITLE
seamlessClone wrong flags

### ISSUE THREAD

**Issue by Garoe** [opencv/opencv#8632]
- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04
- OpenCV-Python => 3.2.0.7

##### Detailed description

Flag option FEATURE_EXCHANGE in [photo.hpp](https://github.com/opencv/opencv/blob/1c18b1d245a875565c9b9e49ccec901e9b516337/modules/photo/include/opencv2/photo.hpp#L751-L752) does not correspond to the implemented MONOCHROME_TRANSFER in [photo.hpp](https://github.com/opencv/opencv/blob/1c18b1d245a875565c9b9e49ccec901e9b516337/modules/photo/include/opencv2/photo.hpp#L81) and [seamless_cloning_impl.cpp ](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/photo/src/seamless_cloning_impl.cpp#L392).

It seems like FEATURE_EXCHANGE should be renamed to MONOCHROME_TRANSFER.

##### Steps to reproduce

```python
import cv2
cv2.FEATURE_EXCHANGE
```
The former will output `AttributeError: 'module' object has no attribute 'FEATURE_EXCHANGE'`

**Comment by saskatchewancatch** [comment]
Looks like the doc needs updating. I glossed over the cited paper and my guess is that monochrome transfer is a specialized version of feature exchange in which the patch is converted to intensity.

**Comment by saskatchewancatch** [comment]
#8646
