### ISSUE TITLE
Xcode 7 OpenCv build error with linking command failed

### ISSUE THREAD

**Issue by tamlearnstocode** [opencv/opencv#8634]
Hey everyone, 

I'm in the process of setting my computer up to run OpenCV projects, but I'm having a build error. My specs are OpenCV 3.2.0, Mac Sierra 10.12, Xcode 7.2.

I've followed [this youtube tutorial](https://www.youtube.com/watch?v=OVSPfUmNyOw&t) to link my search paths and write a simple opencv program, but even so, I still get "linking errors"

The picture attached shows my simple code and the error I get. Any help is appreciated!!

<img width="1225" alt="screen shot 2017-04-22 at 09 13 05" src="https://cloud.githubusercontent.com/assets/27882527/25302446/94307ee6-273e-11e7-9c52-c5bf32ce877f.png">

**Comment by StevenPuttemans** [comment]
Adding errors as screenshots will not work ... please replace with a full code copy :+1:

**Comment by changkaizhao** [comment]
you cannot compile system lib with xcode7 on macOS 10.12. upgrade it to xcode8.   apparently your error generated by opencv_videoio module  which rely on system lib avfoundation or (qtkit  quicktime deprecated on 10.12).

**Comment by vpisarev** [comment]
try to build macos/osx framework (see opencv/platforms/osx) and add this framework to your project. Or, which is even better, use CMake
