### ISSUE TITLE
Where should the IPPICV tgz put in OpenCV 3.2.0

### ISSUE THREAD

**Issue by hawklucky** [opencv/opencv#8641]
IPPICV: Download: ippicv_2017u2_lnx_intel64_20170418.tgz
It's always IPPICV: Download failed: 28;"Timeout was reached". I have already download the ippicv tgz file, but I don't know where should it be put. Anyone help please.

**Comment by alalek** [comment]
Check output of `CMakeDownloadLog.txt` file in your build directory:

```
> $ cat CMakeDownloadLog.txt 
use_cache "/home/alalek/projects/opencv/dev/.cache"
do_unpack "ippicv_2017u2_lnx_intel64_20170418.tgz" "87cbdeb627415d8e4bc811156289fa3a" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/a62e20676a60ee0ad6581e217fe7e4bada3b95db/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz" "/home/alalek/projects/opencv/build/opencv/3rdparty/ippicv"
#cmake_download "/home/alalek/projects/opencv/dev/.cache/ippicv/87cbdeb627415d8e4bc811156289fa3a-ippicv_2017u2_lnx_intel64_20170418.tgz" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/a62e20676a60ee0ad6581e217fe7e4bada3b95db/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz"
```

Take a look on `#cmake_download` line.

**Comment by StevenPuttemans** [comment]
If the solution of @alalek solved the issue, then please close this down @hawklucky (guessing on the fact you gave a thumbs up)

**Comment by mohamad-shbani** [comment]
@hawklucky hello 
please can I know from where you have downloaded : ippicv_2017u2_lnx_intel64_20170418.tgz file ?

**Comment by alalek** [comment]
You should check network settings, like proxy/firewall.
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by ctvn2002** [comment]
Nothing but BS and self back patting from these "contributors". 
Root cause: https://raw.githubusercontent.com/opencv/opencv_3rdparty/a62e20676a60ee0ad6581e217fe7e4bada3b95db/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz is bad. ( 404 )
The ippicv lib goes into <BUILD_DIR>/3rdparty  folder.
This is currently still happening in 3.4.0. 
How do you people run the build process in test/qa? 
Please don't tell me with -DWITH_IPP=OFF. That's dilettantism.

**Comment by alalek** [comment]
> 404

Nope:
```
$ curl -i -v -o ippicv_2017u2_lnx_intel64_20170418.tgz https://raw.githubusercontent.com/opencv/opencv_3rdparty/a62e20676a60ee0ad6581e217fe7e4bada3b95db/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.0.133...
* TCP_NODELAY set
* Connected to raw.githubusercontent.com (151.101.0.133) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* ALPN, server accepted to use http/1.1
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=www.github.com,O="GitHub, Inc.",L=San Francisco,ST=California,C=US
* 	start date: Mar 23 00:00:00 2017 GMT
* 	expire date: May 13 12:00:00 2020 GMT
* 	common name: www.github.com
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /opencv/opencv_3rdparty/a62e20676a60ee0ad6581e217fe7e4bada3b95db/ippicv/ippicv_2017u2_lnx_intel64_20170418.tgz HTTP/1.1
> Host: raw.githubusercontent.com
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< ETag: "f7bc859fc42d18cc397b4bd50c32e23b8fc3037b"
< Content-Type: application/octet-stream
< Cache-Control: max-age=300
< X-Geo-Block-List:
< X-GitHub-Request-Id: 776A:18C7:1496EB9:16464B1:5A4A2287
< Content-Length: 40808979
< Accept-Ranges: bytes
< Date: Mon, 01 Jan 2018 11:59:04 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-ams4445-AMS
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1514807943.386254,VS0,VE664
< Vary: Authorization,Accept-Encoding
< Access-Control-Allow-Origin: *
< X-Fastly-Request-ID: d1adfa28f29024e7324a7e74a613fa18ae34761c
< Expires: Mon, 01 Jan 2018 12:04:04 GMT
< 
{ [1929 bytes data]
100 38.9M  100 38.9M    0     0  5112k      0  0:00:07  0:00:07 --:--:-- 7696k
* Connection #0 to host raw.githubusercontent.com left intact
```

So,

> You should check network settings, like proxy/firewall.

**Comment by kanik9** [comment]
> I am facing the same problem
> 
> Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
> -- Found libavcodec, version 56.60.100
> -- Found libavformat, version 56.40.101
> -- Found libavutil, version 54.31.100
> -- Found libswscale, version 3.1.101
> -- Checking for module 'libavresample'
> -- No package 'libavresample' found
> -- Checking for module 'libgphoto2'
> -- No package 'libgphoto2' found
> -- IPPICV: Download: ippicv_2017u2_lnx_intel64_20170418.tgz
> 
> /*
> After this line the installation freezes. Nothing happens after this
> */
> I guess the process is unable to find the file what should i do ? @alalek @hawklucky @StevenPuttemans

nothing to weary , it will take few seconds or min but it will run again 
I also face same problem but it sloved

**Comment by alalek** [comment]
> Download

Check your internet settings, proxy setup.

> After this line the installation freezes. Nothing happens after this

There are 60/600 timeout limits. You should wait for actual result/error message.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
