### ISSUE TITLE
"OpenCV" is considered to be   NOT FOUND

### ISSUE THREAD

**Issue by Eirtrand** [opencv/opencv#8644]
Hi, I followd this prosidure when insalling opencv 3.1:

 ```bash
sudo apt-get install -y build-essential cmake
sudo apt-get install -y qt5-default libvtk6-dev
sudo apt-get install -y zlib1g-dev libjpeg-dev libwebp-dev libpng-dev libtiff5-dev libjasper-dev libopenexr-dev libgdal-dev

sudo apt-get install -y libtbb-dev libeigen3-dev

sudo apt-get install -y unzip wget
wget https://github.com/opencv/opencv/archive/3.1.0.zip
unzip 3.1.0.zip

mv opencv-3.1.0 OpenCV
cd OpenCV
mkdir build
cd build
cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON ..
make -j4
sudo make install
sudo ldconfig
```
I have a totally clean ubuntu 16.04 version and the script runs without any errors. After installation I try to run the cmake example in samples/c++/example_cmake by building it with 'cmake . && make'

cmake gives me this error: 

```bash
CMake Warning at /home/e/OpenCV/cmake/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


CMake Error at CMakeLists.txt:10 (find_package):
  Found package configuration file:

    /home/e/OpenCV/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
```

I have tries to set the path manually but it does not work, I would like to have my environment set up without any "hacks" in the original CMakeLists.txt file: 

```cmake
cmake_minimum_required(VERSION 2.8)
project(opencv_example_project)
find_package(OpenCV REQUIRED)
message(STATUS "OpenCV library status:")
message(STATUS "    version: ${OpenCV_VERSION}")
message(STATUS "    libraries: ${OpenCV_LIBS}")
message(STATUS "    include path: ${OpenCV_INCLUDE_DIRS}")

if(CMAKE_VERSION VERSION_LESS "2.8.11")
  include_directories(${OpenCV_INCLUDE_DIRS})
endif()

add_executable(opencv_example example.cpp)
target_link_libraries(opencv_example ${OpenCV_LIBS})
```

I have read all other issues on the problem and none if them worked for me.

**Comment by Eirtrand** [comment]
Same think happens when I try 3.2.0

**Comment by alalek** [comment]
> Found OpenCV Windows Pack

You trying to use scripts for Windows - this will not work on linux system.
You should pass valid `OpenCV_DIR` which should point to your OpenCV build directory or point to "share/OpenCV" subdirectory under installation path ("/usr/local" by default on Linux systems).

> /usr/share/OpenCV/

This is a path of system OpenCV. It doesn't correlate with downloaded version (probably this OpenCV is 2.4.x).


Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
