### ISSUE TITLE
Update matchTemplate documentation

### ISSUE THREAD

**Issue by martinakos** [opencv/opencv#8647]
OpenCV 3.1

matchTemplate has a mask parameter. However, this mask parameter is only implemented for the CV_TM_SQDIFF and CV_TM_CCORR_NORMED methods. It would be nice if that was indicated in the docs.

**Comment by saskatchewancatch** [comment]
Looking at [templmatch.cpp](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/templmatch.cpp#L1087), it does appear that only `CV_TM_SQDIFF` and `CV_TM_CCORR_NORMED` are supported in case a template mask is supplied. A not implemented exception is thrown in case another method that is neither of those two is supplied.

**Comment by saskatchewancatch** [comment]
PR #8649 for this.
