### ISSUE TITLE
Fail to build OpenCV 3.1.0 on SLES 11

### ISSUE THREAD

**Issue by Zenitur** [opencv/opencv#8651]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => SUSE Linux
- Compiler => GCC 4.3

##### Detailed description

Build log: https://pastebin.com/Gijprq3G

**Comment by alalek** [comment]
> Eigen/Eigenvalues

Try to disable [autodetection](https://github.com/opencv/opencv/blob/3.1.0/CMakeLists.txt#L172) of Eigen library: `cmake -DWITH_EIGEN=OFF <...>`

**Comment by Zenitur** [comment]
Successfully builds. Thank you, **alalek**!
