### ISSUE TITLE
Cannot import cv2, Reason: image not found

### ISSUE THREAD

**Issue by allenlu95** [opencv/opencv#8652]
- OpenCV => 3.1.0
- Operating System / Platform => OSX Sierra version 10.2.4
- Compiler => Visual Studio 2015

##### Detailed description

For the past month I have been able to use opencv normally; however, this past week I tried running it and got the following error; I'm not sure if it's because I updated my mac, I don't recall switching versions:

##### Steps to reproduce
import cv2

```
.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: /opt/local/lib/libhdf5.10.dylib
  Referenced from: /usr/local/lib/libopencv_hdf.3.2.dylib
  Reason: image not found
```

**Comment by vpisarev** [comment]
try to build OpenCV without HDF support

**Comment by MertalpTasdelen** [comment]
Hello @allenlu95 how can u solve your problem i get the same one ?

**Comment by allenlu95** [comment]
I forgot how I solved it, I think I just re-installed opencv

**Comment by MertalpTasdelen** [comment]
Omg kill me god... Thanks have a nice day

**Comment by monomente** [comment]
I uninstalled opencv using `brew uninstall --force opencv`.  Reinstallation using `brew install opencv3 --with-contrib --with-python3 --with-examples` was successful but did nothing to solve the above error.  I did `brew install homebrew/science/hdf5 --enable-cxx` and this solved the above error.  Next error was looking for the library tesseract, but this was easily installed using brew install tesseract.  After this I could import cv2 from python2 or python3 (checking the version with cv2.__version__.  Hope that helps people!

**Comment by Joevonlong** [comment]
I have the same problem, 
opencv 3.4.3_1
python 3.5/python3.6
MacOS

**Comment by peacej** [comment]
I have the same problem, and it seems the solution by  `monomente` posted above is out of date.

**Comment by SimonCK666** [comment]
I have the same question on a M1 Macbook air. 
Looking for a solution, Thanks!
