### ISSUE TITLE
Bug： OpenCV3.1 error ,when I tring to compile c project

### ISSUE THREAD

**Issue by Devincool** [opencv/opencv#8658]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04(PC)    JestonTk1  JestonTX1
- Compiler => gcc

##### Detailed description

Question Projection: YOLO-Darknet      https://pjreddie.com/darknet/install/
Error occurred when using cvRound function

##### Steps to reproduce
Just run make

obj/image.o：In Function ‘cvPointFrom32f’：
/usr/local/include/opencv2/core/types_c.h:929：undefined reference to ‘cvRound’
/usr/local/include/opencv2/core/types_c.h:930：undefined reference to ‘cvRound’
obj/image.o：In Function ‘cvReadInt’：
/usr/local/include/opencv2/core/core_c.h:2318：undefined reference to ‘cvRound’
obj/image.o：In Function ‘cvEllipseBox’：
/usr/local/include/opencv2/imgproc/imgproc_c.h:1041：undefined reference to ‘cvRound’
/usr/local/include/opencv2/imgproc/imgproc_c.h:1042：undefined reference to ‘cvRound’
obj/darknet.o:/usr/local/include/opencv2/core/types_c.h:929: more undefined reference to ‘cvRound’ follow

##### Solution
Modify the cvdef.h  by adding the follow codes:

```
/*************************************************************************************\
*                                    Test add fast_math.hpp by devin                  *
\*************************************************************************************/

#ifndef __cplusplus
#include "opencv2/core/fast_math.hpp"
#endif

```

**Comment by alalek** [comment]
OpenCV is C++ library. C API is not supported anymore and it should not be used.
