### ISSUE TITLE
getPerspectiveTransform get different result in release and debug mode

### ISSUE THREAD

**Issue by peterchensm** [opencv/opencv#8666]
##### System information (version)

- OpenCV =>2.4.13
- Operating System / Platform => Windows 7 32 Bit
- Compiler => Visual Studio 2013

##### Detailed description
I found getPerspectiveTransform counld get results from release and debug mode are different,
The following is my data:

src:
[346.967, 374.95]
[465.033, 374.95]
[465.033, 444.7]
[346.967, 444.7]

dst:
[0, 0]
[101, 0]
[101, 60]
[0, 60]

release mode result:
[0.8554490168548095, 1.595945597898663e-016, -296.8123008430522;
  -2.775557561562891e-017, 0.8602150537634458, -322.5376449092761;
  8.239936510889834e-018, 5.204170427930421e-018, 1]

debug mode result:
[0.8554490168548097, 4.371503159461554e-016, -296.8123008430524;
  -1.665334536937735e-016, 0.8602150537634464, -322.5376449092763;
  4.98732999343332e-018, 1.040834085586084e-017, 1]

##### Steps to reproduce

     C++ code example

    Mat transmtx = getPerspectiveTransform(corners, outputCorners);
 std::cout<<transmtx <<std::endl;
-->

**Comment by alalek** [comment]
Both results looks valid, result should be checked "by definition" from documentation (get result matrix and multiply on vector).

Please learn more about floating point arithmetic, floating point rounding error, ULP and FLT_EPSILON, numerical stability of algorithms and why operations order sometimes important (result of `(a+b)+c` is not equal `a + (b+c)` sometimes) - compiler optimizations often reorder and simplify computational operations.
You should never rely on bit-exact result of floating-point algorithms.
