### ISSUE TITLE
building framework fails when older version of opencv is installed on macOS

### ISSUE THREAD

**Issue by mschneider** [opencv/opencv#8667]
- OpenCV => 3.2
- Operating System / Platform => MacOS 10.12
- Compiler => XCode 8

##### Detailed description

The core/private.hpp header is mixed up with the installed version in /usr/local. this has the effect that certain defines like CV_INSTRUMENT_REGION() will crash the compilation throughout the code base. The main reason is that /usr/local/include is added to the import path for the platform/osx build. Not sure why, I worked around it by temporarily removing the opencv headers from my system.

##### Steps to reproduce

Install opencv 3.1 into /usr/local
checkout 3.2
run `cd platforms/osx;python build_framework.py --contrib=../../../opencv_contrib build`

**Comment by alalek** [comment]
Please add build logs (compiler invocation command lines) and CMake configuration files (CMakeCache.txt CmakeVars.txt from build directory).

**Comment by mschneider** [comment]
[build folder](https://drive.google.com/file/d/0B3jcxTFTCssmLWJzTk92XzQ5dU0/view?usp=sharing)
[compiler.out.txt](https://github.com/opencv/opencv/files/965589/compiler.out.txt)

**Comment by alalek** [comment]
Problem comes from WebP 3rdparty dependency:
> WEBP_INCLUDE_DIR:PATH=/usr/local/include

Current workaround is to disable it via `-DWITH_WEBP=OFF` CMake option (you need to hack build python script, or fix it [here](https://github.com/opencv/opencv/blob/3.2.0/CMakeLists.txt#L190)).

**Skip this, see update below**
Could you try current master branch?
There were some fixes about include directories order. This directory (`/usr/local/include`) should be processed [here](https://github.com/opencv/opencv/blob/a740a4ca381629a1b5746724c3ca2023066b6e27/cmake/OpenCVUtils.cmake#L142) (you may check this by adding "`message("!!! ${dir})`" statement).

**Update:**
Looks like, CMake XCode generator doesn't support "SYSTEM" include paths and "AFTER" semantic well.
CMake issue about "SYSTEM": https://gitlab.kitware.com/cmake/cmake/issues/16795 (fix will be available in the next CMake release and [for](https://gitlab.kitware.com/gjasny/cmake/commit/ffdde4a9aeb7a93f1f608d92e15540a7ca43a1e6#2f50f576cb9c2864f59b6d6ae2961385ef470cb2_2012_2014) XCode 8.3+ only)
See also: http://stackoverflow.com/questions/31722426/cmake-target-include-directoriessystem-system-option-does-not-seem-to-wor

**Comment by mschneider** [comment]
thank you for looking into it. will check when the new release becomes available

**Comment by alalek** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/16795
