### ISSUE TITLE
OpenCV4Android build issue : "The android command is deprecated"

### ISSUE THREAD

**Issue by Xarpus** [opencv/opencv#8673]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Lubuntu 17.10
- Compiler => GCC

##### Detailed description

I wanted to generate OpenCV4Android because I need to use some of extra modules (ArUco).
After sh ./scripts/cmake_android_arm.sh was done , I opened CMakeCache.txt and added OPENCV_EXTRA_MODULES. Configuring and generating have gone smoothly.
Few errors were displayed while building. 

1. - "The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager"
I've picked sdkmanager from ~/Android/Sdk/tools.

2. Build.xml is missing
I believe OpenCV skipped process from before , and hasn't generated build.xml.

**Comment by alalek** [comment]
#8460

**Comment by abelokon955** [comment]
This doesn't solve the issue
