### ISSUE TITLE
Problem compiling opencv3.2 on windows whit cmake and visual studio

### ISSUE THREAD

**Issue by GiGa911** [opencv/opencv#8678]
Hi everyone, 
I would like to compile opencv 3.2 on windows 7 (64bit) with cmake and visual studio. 
When I start compiling additional modules on cmake I return a 
"C: \ Opencv \ opencv-build \ CMakeFiles \ CMakeTmp \ CheckIncludeFile.c (1) error: fatal error C1083: Can not open file include: 'pthread.h': No Such file or directory [C: \ Opencv \ opencv-build \ CMakeFiles \ CMakeTmp \ cmTC_6ba2c.vcxproj]"
How can I fix this problem? Thank you in advance

**Comment by vpisarev** [comment]
pthread.h is not used on Windows when OpenCV is built with Visual Studio
