### ISSUE TITLE
Link errors occurred when trying to build cross-platform app with opencv and react-native

### ISSUE THREAD

**Issue by yenshih** [opencv/opencv#8681]
Sorry for asking question directly in this issue. But I got confused for a long time and I couldn't find any answer in this [site](http://answers.opencv.org/questions/)
Firstly, Here is my [repo](https://github.com/yenshih/Dehaze).

### Introduction about my project
I'm trying to build a cross-platform image processing app with this following techniques:
 - [React Native](https://facebook.github.io/react-native/): Building cross-platform view with React.
 - [Djinni](https://github.com/dropbox/djinni): A tool for generating cross-language type declarations and interface bindings. It's designed to connect C++ with either Java or Objective-C.
 - opencv: 
    - pass uri from react native, invoke imread
    - do some stuff using opencv, including guidedFilter in [opencv_contrib](https://github.com/opencv/opencv_contrib)
    - invoke imwrite to save the image after processing, and return new uri

So I build a development environment including React Native, Djinni and C++ without opencv, it works well. I can transfer message (pass a string as parameter and get the return string) between React Native and C++.

### Errors occurred while linking opencv
Now I'd like to include opencv in my app and run this project in iOS Simulator first. In order to use guidedFilter in ximgproc, I need to compile my own opencv bundle from source code with this following commands.
```bash
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git
cp -R ./opencv_contrib/modules/ximgproc ./opencv/modules
python ./opencv/platforms/ios/build_framework.py /usr/local/opencv
```
I built opencv2.framework and included it in xcodeproj, then compiled.
Some errors occurred. You can reproduce this errors by:
```bash
git clone --recursive https://github.com/yenshih/Dehaze.git
cd Dehaze
npm install
make
make ios
```
'make' may takes a few minutes downloading and compiling scala source code in Djinni.
And maybe you need to install [nodejs](https://nodejs.org/en/) and [npm](https://docs.npmjs.com/getting-started/installing-node) previously.
<img width="1280" alt="2017-05-01 5 02 17" src="https://cloud.githubusercontent.com/assets/14069488/25576309/6f049194-2e90-11e7-870b-e39c4e9d00bc.png">
<img width="1280" alt="2017-05-01 5 02 48" src="https://cloud.githubusercontent.com/assets/14069488/25576310/6f158e86-2e90-11e7-8f43-46d1e7b1b5c7.png">

It seems that errors occurred while linking opencv static library, and I have no ideas about it.

### Environment
 - opencv: Built from source code.
 - OS: macOS Sierra 10.12.3
 - compiler: clang in xcode
    - Apple LLVM version 8.1.0 (clang-802.0.35)
    - Target: x86_64-apple-darwin16.4.0
    - Thread model: posix
    - InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### Key File Description
 - /android ---- React Native Android project
 - /ios ---- React Native iOS project
 - /src
    - /js ---- React Native code.
    - /cpp ---- C++ code with opencv
- /generated-src ---- generated bridge code by Djinni
- dehaze.djinni ---- Djinni type declaration file
- run_djinni.sh ---- run Djinni to generate bridge code
- libdehaze.gyp ---- Djinni configuration
- index.android.js ---- React Native Android entry code
- index.ios.js ---- React Native iOS entry code

### Conclusion
I was just wondering if someone could tell my how to solve the problem above. I would really appreciate your help!
I will keep tracking this issue, if someone has any problem about my project, just ask me.
Thanks again!

**Comment by alalek** [comment]
Screenshots with error messages are completely useless stuff.

There is issue with handling of static dependencies in OpenCV Framework.
You can try to enable "dynamic" build: #8009

Also you can try to turn off IPP [here](https://github.com/opencv/opencv/blob/04573615c5fe95e1219587ecb7fc3ddb94ad2320/CMakeLists.txt#L203)  (probably you have not strong requirements for IPP optimizations on iOS Simulator):
```.diff
-OCV_OPTION(WITH_IPP            "Include Intel IPP support"                   NOT MINGW IF (X86_64 OR X86) AND NOT WINRT )
+OCV_OPTION(WITH_IPP            "Include Intel IPP support"                   NOT (MINGW OR IOS) IF (X86_64 OR X86) AND NOT WINRT )
```

**Comment by yenshih** [comment]
Thanks for the quick reply.
**IT WORKS!**
I fell really excited! It solved my problem precisely :)

However, it seems that imread and imwrite doesn't work. When I invoke imread, the app is just crash.
Is there some way to read image from uri to cv::Mat through opencv written in C++ code?
Indeed, I had googled this problem and found some solutions written in Objective-C. Unfortunately I'm not familiar with it.
If there's no way to solve this problem written in C++, it's perfectly okey, maybe I shall learn Objective-C first :)

Here's my code:
<img width="1280" alt="2017-05-02 1 14 30" src="https://cloud.githubusercontent.com/assets/14069488/25587030/b93f13ee-2ed4-11e7-902f-678582e2c774.png">
And line 91 'imread' causes a runtime error.

Once again, thank you all for your help!

**Comment by yenshih** [comment]
Problem solved!
I didn't drag opencv2.framework into Copy Bundle Resources so the app crashed.

**Comment by vaibhawc** [comment]
Hey @yenshih , I didn't get. Were you trying to make a react native repo for opencv? I don't find one and hope someone could make one were I may contribute.
