### ISSUE TITLE
Javacv Mat to Opencv mat  Slows down processing

### ISSUE THREAD

**Issue by mnh-aj123** [opencv/opencv#8687]
I have been working on Video Processing using Javacv and opencv .I currently using Javacv to grab video frames while all further processing is done using Opencv Mat. Problem to be solved is : Laptop hangs while converting Javacv Mat to Opencv Mat 

Problem Lies in conversion of Javacv mat to opencv mat
```
 while ((grabbedImage = converter.convert(grabber.grab())) != null) {

        counter++;

            Mat x=new Mat(grabbedImage.address()).clone(); // Problem Lies here it Slows down the processing 

            Mat w=new Mat();

            x.copyTo(w);

            x.release();

            Frame rotatedFrame = converter.convert(grabbedImage);

            frame.showImage(rotatedFrame);

```

Its a very complicated question, but I would appreciate if anyone could solve my problem its urgent.

**Comment by mnh-aj123** [comment]
@mshabunin any reason?

**Comment by mshabunin** [comment]
@mnh-aj123 , please, try to ask this question on the forum: http://answers.opencv.org/questions/
Also, we can not help you with JavaCV, because we do not support it.

**Comment by vpisarev** [comment]
indeed, we cannot cover interaction of OpenCV with all other libs
