### ISSUE TITLE
Opencv 3.2.0 opencv_test_imgproc fails when sse disabled

### ISSUE THREAD

**Issue by piersy** [opencv/opencv#8690]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
- Compiler => g++ (Debian 4.9.2-10) 4.9.2

##### Detailed description
The `opencv_test_imgproc` test fails when all three sse build options are disabled

##### Steps to reproduce
Run the following from a clean build dir to reproduce the problem.
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SSE=OFF -DENABLE_SSE2=OFF -DENABLE_SSE3=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_SHARED_LIBS=ON  .. && make -j8 opencv_test_imgproc && bin/opencv_test_imgproc
```
The following tests fail.
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Imgproc_Hist_Calc.accuracy
[  FAILED  ] Imgproc_Hist_CalcBackProject.accuracy
[  FAILED  ] Imgproc_Hist_CalcBackProjectPatch.accuracy
```

**Comment by mshabunin** [comment]
Did you try to run it with latest master version? Many things have changed since 3.2.0, for example `ENABLE_SSE` and similar cmake options are deprecated now: https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options
I tried to build with `CPU_BASELINE=SSE` and these tests pass for me.

**Comment by piersy** [comment]
Hi mshabunin,  I did not try this on master. Could you let me know what version of opencv_extra I should use for running the tests? Thanks

**Comment by mshabunin** [comment]
You should use same version of _opencv_extra_ as of _opencv_. Either tagged 3.2.0, 3.1.0, etc., either _master_.
