### ISSUE TITLE
Quality check using epipolar line in stereo_calib sample

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8691]
Hi,
It not an issue about opencv but about math. In stereo_calib quality of calibration is checked https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_calib.cpp#L188-L211. 
[Result  ](https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_calib.cpp#L211)is cout << "average epipolar err = " << err/npoints << endl; 
err is homogeneous to a distance because [formulae ](https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_calib.cpp#L203) is [distance of point](https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line) to epipolar line ([line coefficients](http://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga19e3401c94c44b47c229be6e51d158b7) are normalised to 1).

My question is : error is err/npoints or err/npoints/2 to have error in pixel?

**Comment by gdelab** [comment]
I think you do have to divide by 2, since it's tested both ways.

But why are the lines computed with undistorted points in one image but not in the other ? More specifically, should we not call
`undistortPoints()` on `imagePoints[0][i]` and` imagePoints[1][i]` before doing

 ```
double errij = fabs(imagePoints[0][i][j].x*lines[1][j][0] +
                                imagePoints[0][i][j].y*lines[1][j][1] + lines[1][j][2]) +
                           fabs(imagePoints[1][i][j].x*lines[0][j][0] +
imagePoints[1][i][j].y*lines[0][j][1] + lines[0][j][2]);
```
?
