### ISSUE TITLE
OpenCV build failed (please see the image below)

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#8699]
##### System information (version)

- OpenCV = 3.2
- Operating System / Platform =  Windows 64 Bit
- Compiler = Visual Studio 2017

##### Detailed description
When building OpenCV from source the following error occurs. The CMake was generated successfully, but start building project in Visual Studio 2017, it fails (tried many many times on different computers).
The below is what I got at the end of the build process. (Before it was working well)
![capture](https://cloud.githubusercontent.com/assets/13574895/25756836/d43732b6-31fa-11e7-80f1-35b9c7742c4f.PNG)

**Note:** I want to build OpenCV with contribs for Java. CMake version 3.8.0 and Python version 3.6 x64. Java version 1.8.0. Ant version 1.10.1

**Comment by krishraghuram** [comment]
Please post questions to :
http://answers.opencv.org/questions/

This place is for issues and bugs that needs fix :smile:
