### ISSUE TITLE
Add userdata parameter to createTrackbar's Python implementation

### ISSUE THREAD

**Issue by nicszerman** [opencv/opencv#8700]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04

##### Detailed description
Would be very useful to be able to pass a userdata parameter to the Python implementation of createTrackbar. (According to http://docs.opencv.org/3.0-beta/modules/highgui/doc/user_interface.html it is not possible)

**Comment by anupamsobti** [comment]
I'm trying to add this. Can someone guide me?

I checked highgui.hpp and it has the macro
`CV_EXPORTS int createTrackbar(const String& trackbarname, const String& winname,
                              int* value, int count,
                              TrackbarCallback onChange = 0,
                              void* userdata = 0);

`
which seems to be the only requirement for extending all arguments as per 
http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.html#bindings-basics

I don't exactly understand where python is forming the bound functions. Any pointers to documentation which explains that would also be useful.

**Comment by berak** [comment]
@anupamsobti , unfortunately, it's slightly more complicated, the trackbar / mouse handlers need a python callback function, so the userdata slot is already filled with that.

[see here](https://github.com/opencv/opencv/blob/master/modules/python/src2/cv2.cpp#L1405) for the actual implementation

**Comment by alalek** [comment]
Python is able generate closure functions (with bounded internal variables) on the fly (during runtime), so this issue can be easy resolved by Python itself.

[Example](https://github.com/opencv/opencv/blob/3.2.0/samples/python/video_v4l2.py#L38-L39):
```.python
cv2.createTrackbar("FPS", "Video", fps, 30, lambda v: cap.set(cv2.CAP_PROP_FPS, v))
cv2.createTrackbar("Focus", "Video", focus, 100, lambda v: cap.set(cv2.CAP_PROP_FOCUS, v / 100))
```

**Comment by anupamsobti** [comment]
or it could be done like [this?](https://github.com/opencv/opencv/blob/master/modules/python/src2/cv2.cpp#L1455) (the way it's done in pycvCreateButton?)

**Comment by nicszerman** [comment]
@alalek 
Though it can be solved, it would be nice if the solution wasn't a hack.

**Comment by vpisarev** [comment]
it's not a hack, e.g. read tkinter guide; in languages that have closures, "userdata" is not needed and not used
