### ISSUE TITLE
Python : OS restarts when running OpenCV function.

### ISSUE THREAD

**Issue by MahmoudRizk** [opencv/opencv#8703]
##### System information (version)

- OpenCV => : 3.0
- Operating System / Platform => Linux/ Ubuntu 14.04
- Compiler => python 2.7

##### Detailed description

When I run this code in the code example below, it gives  black screen then the entire system restarts. To be more specifically the bug happens when applying the blur filter ```python  cv2.medianBlur(img,5) ```.

I don't know what happened, it was working perfectly and doing the job.

```
* Starting PostgreSQL 9.3 database server
* speech-dispatcher disabled: edit /etc/default/speech-dispatcher saned disabled: edit /etc/default/saned
* Restoring resolver state...
* Starting Tomcat servlet engine tomcat66
```

##### Steps to reproduce

```python 
import numpy as np
import cv2

# Load an color image in grayscale
img = cv2.imread('S_1_hppscan12.png',0)
img = cv2.medianBlur(img,5)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by sovrasov** [comment]
@MahmoudRizk OpoenCV 3.0 is not supported anymore. Try to use the latest `master` or 3.2.

**Comment by mshabunin** [comment]
Can be a HW-related problem, for example OpenCL driver issue, try to upgrade your drivers and/or kernel.
To run without OpenCL, set environment variable `OPENCV_OPENCL_DEVICE=disabled`.
