### ISSUE TITLE
HDR MergeRobertson: weights should be 0 at limits

### ISSUE THREAD

**Issue by Michael-4** [opencv/opencv#8706]
The weights (calculated by RobertsonWeights()) used for merging the images using MergeRobertson should be 0 for input values of 0 and 255. This is also described in the article referenced in the documentation for the algorithm.

By not setting them to 0, image parts which are overexposed (and thus have values of 255) will have influence on the merged image although they should not.

**Comment by sovrasov** [comment]
According to paper the function should be:
```C++
Mat RobertsonWeights()
{
    Mat weight(LDR_SIZE, 1, CV_32FC3);
    float q = (LDR_SIZE - 1) / 4.0f;
    float e4 = exp(4.f);
    float a = e4/(e4 - 1.f);
    float b = 1 / (1.f - e4);

    for(int i = 0; i < LDR_SIZE; i++) {
        float value = i / q - 2.0f;
        value = a*exp(-value * value) + b;
        weight.at<Vec3f>(i) = Vec3f::all(value);
    }
    return weight;
}
```
but result of merge is underexposed in this case.
Test code is [here](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/photo/test/test_hdr.cpp#L204). Source images are in opencv_extra repo.
![merge_2](https://cloud.githubusercontent.com/assets/5373517/25997940/5480c064-3727-11e7-95d3-ad4dcbe80703.png)
![merge_1](https://cloud.githubusercontent.com/assets/5373517/25997941/54ac608e-3727-11e7-8158-234e0099e260.png)

**Comment by sovrasov** [comment]
Without applying of `Tonemap` output image seems to be ok.
![merge_3](https://cloud.githubusercontent.com/assets/5373517/25998846/72743b60-372b-11e7-879a-c6adaa8328a3.png)
