### ISSUE TITLE
OpenCV 3.2: Problems with The Aravis SDK Installation

### ISSUE THREAD

**Issue by matheusns** [opencv/opencv#8707]
Hello Guys,

I've found an issue on the OpenCV 3.2 release, if we run the installation with the Aravis SDK, certainly a problem is going to appear. The following file, [cap_aravis.cpp](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_aravis.cpp), on the line 393, has a problem, because it is subtracting two floats and using [abs](http://www.cplusplus.com/reference/cstdlib/abs/?kw=abs) function. The correct approach is to use the [fabs](http://www.cplusplus.com/reference/cmath/fabs/?kw=fabs) function, in the [math.h](http://www.cplusplus.com/reference/cmath/?kw=math.h) header, to subtract floats.

The currently code is the following:
```c++
 if(exposureAvailable) {
            if(abs(exposure - ne) > 2) {
                // priority 2 - control of exposure time
                arv_camera_set_exposure_time(camera, (exposure = ne) );
                return;
            }
        }
```
The correct is:
```c++
 if(exposureAvailable) {
            if(fabs(exposure - ne) > 2) {
                // priority 2 - control of exposure time
                arv_camera_set_exposure_time(camera, (exposure = ne) );
                return;
            }
        }
```
@matheusns

**Comment by alalek** [comment]
I believe it is better to use [`std::abs`](http://en.cppreference.com/w/cpp/numeric/math/fabs) (cmath include).

/cc @ArkadiuszRaj

**Comment by matheusns** [comment]
You've got to warn about that, because the whole code uses [fabs](http://www.cplusplus.com/reference/cmath/fabs/?kw=fabs) in all other cases. There is more one possible problem, because the code might use some c++ functions and if we use [std::abs](http://www.cplusplus.com/reference/cmath/abs/) the namespace "std" has to be used, that may induce other problems. On the line 377 we have the following code, using [fabs](http://www.cplusplus.com/reference/cmath/fabs/?kw=fabs) function:
```c++
   // if change of value requires intervention
    if(fabs(d-dmid) > 5) {
        double ev, ng = 0;
```
@matheusns

**Comment by ArkadiuszRaj** [comment]
Well, in general a typo.

I do agree with @alalek here.

As std library is already included for sake of code clarity it is better to use in both places std::abs as floating point version of abs() will not change algorithm behaviour (but will be seen by others as proper use). 

I will then prepare  small correction to use consistently std::fabs() in this module.

**Comment by matheusns** [comment]
So, I fixed this problem on my system using the functions as I described above. The other solutions didn't work, I hope to help the users to fix that.
@matheusns

**Comment by ArkadiuszRaj** [comment]
By the way ensure that while using this code for automatic exposure calculation no other similar functionality is working.

It happened to me that I was fooled by one of recent TIS camera having automatic exposure functionality, turned on by default.
