### ISSUE TITLE
Python digits.py sample bad indices.

### ISSUE THREAD

**Issue by matthew-morrison** [opencv/opencv#8714]
##### System information (version)
- OpenCV => 3.2.0-3
- Operating System / Platform => Arch 4.10
- Compiler => Python 3.6.1

##### Detailed description

Testing the digits.py example produces this error:

```
Traceback (most recent call last):
  File "digits.py", line 178, in <module>
    vis = evaluate_model(model, digits_test, samples_test, labels_test)
  File "digits.py", line 115, in evaluate_model
    confusion[i, j] += 1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Changing the line to  `confusion[i, int(j)] += 1` corrects the error by converting j from float to int.

**Comment by berak** [comment]
indeed, the responses from the knn/svm prediction are float, so it needs this cast for python3

**Comment by sovrasov** [comment]
@matthew-morrison could you create a PR with the fix?
