### ISSUE TITLE
Ubuntu 16.04 Python after install OpenCV 3.2 and OpenCV_contrib 3.2, some extra modules are missing like Tracking and sfm

### ISSUE THREAD

**Issue by JohnTurnbullDai** [opencv/opencv#8719]
##### Detailed description

After installed OpenCV 3.2 and OpenCV_contrib 3.2, some extra modules are missing like Tracking and sfm, but some can be used like Xfeatures2d.
When I try to use command in python 2.7:
import cv2
help(cv2)

Help on module cv2:

NAME
    cv2

FILE
    /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so

SUBMODULES
    Error
    aruco
    bgsegm
    bioinspired
    cuda
    datasets
    detail
    face
    fisheye
    flann
    ft
    hdf
    instr
    line_descriptor
    ml
    motempl
    multicalib
    ocl
    ogl
    omnidir
    optflow
    plot
    ppf_match_3d
    rgbd
    saliency
    structured_light
    text
    videostab
    viz
    xfeatures2d
    ximgproc
    xphoto

There is no Tracking module and some others. And also when I try to use command:

>>> import cv2

>>> tracker = cv2.Tracker_create("MIL")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Tracker_create'

>>> cv2.Tracker_create
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Tracker_create'

>>> sift = cv2.xfeatures2d
>>> cv2.xfeatures2d
<module 'cv2.xfeatures2d' (built-in)>

**Comment by alalek** [comment]
These (and some other) modules were disabled during build (explicitly or due missing external 3rdparty dependencies).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by leslie-wang** [comment]
it happens in 3.3 again. Make output does show tracking is built. Header file tracking.h and tracking folder are also installed, but python doesn't have it. Same as above result. How do I tell python binding is built or not.

```
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video xphoto bgsegm dnn face freetype fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow stitching python2
```

**Comment by soulslicer** [comment]
SFM seem to be not compiled. Why is this the case
