### ISSUE TITLE
OpenCV 3.2.0 does not build on MacOS 10.11 with arch i386

### ISSUE THREAD

**Issue by divbyzero** [opencv/opencv#8721]
##### System information (version)
- OpenCV => 3.2.0 (form tags/3.2.0 or master)
- Operating System / Platform => MacOS 10.11.6 (15G1421)
- Compiler => Apple LLVM version 8.0.0 (clang-800.0.42.1)

##### Detailed description

**I want to compile with arch i386.**

My params for cmake:
`cmake .. -DCMAKE_OSX_ARCHITECTURES="i386" \
        -DBUILD_SHARED_LIBS=OFF \
        -DBUILD_opencv_java=OFF \
        -DBUILD_opencv_python=OFF \
        -DWITH_1394=OFF \
        -DWITH_FFMPEG=OFF \
        -DWITH_QT=OFF \
        -DWITH_QUICKTIME=OFF \
        -DWITH_V4L=OFF \
        -DWITH_PVAPI=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_PERF_TESTS=OFF \
        -DWITH_LAPACK=OFF`

cmake config log:

> -- sizeof(void) = 4 on x86 / x86_64 processor. Assume 32-bit compilation mode (X86=1)
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-video-1.0'
--   No package 'gstreamer-video-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'gstreamer-base-0.10'
--   No package 'gstreamer-base-0.10' found
-- Checking for module 'gstreamer-video-0.10'
--   No package 'gstreamer-video-0.10' found
-- Checking for module 'gstreamer-app-0.10'
--   No package 'gstreamer-app-0.10' found
-- Checking for module 'gstreamer-riff-0.10'
--   No package 'gstreamer-riff-0.10' found
-- Checking for module 'gstreamer-pbutils-0.10'
--   No package 'gstreamer-pbutils-0.10' found
-- Checking for module 'libgphoto2'
--   No package 'libgphoto2' found
-- found Intel IPP (ICV version): 2017.0.2 [2017.0.2]
-- at: /Users/divbyzero/Documents/projects/OpenCV/opencv/build/3rdparty/ippicv/ippicv_mac
-- found Intel IPP IW binaries: 2017.0.2
-- at: /Users/divbyzero/Documents/projects/OpenCV/opencv/build/3rdparty/ippicv/ippicv_mac/../ippiw_mac/
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- 
-- General configuration for OpenCV 3.2.0-dev =====================================
--   Version control:               3.2.0-516-ga740a4ca3
-- 
--   Platform:
--     Timestamp:                   2017-05-11T15:03:45Z
--     Host:                        Darwin 15.6.0 x86_64
--     CMake:                       3.8.1
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2
--       requested:                 SSE2
--     Dispatched code generation:  SSE4_1 FP16 AVX AVX2
--       requested:                 SSE4_1 AVX FP16 AVX2
--       SSE4_1 (0 files):          + SSE3 SSSE3 SSE4_1
--       FP16 (0 files):            + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (1 files):             + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (1 files):            + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
-- 
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 8.0.0.8000042)
--     C++ flags (Release):         -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          -framework OpenCL -framework Cocoa -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore stdc++
--     3rdparty dependencies:       libjpeg libwebp libpng libtiff libjasper IlmImf zlib ipp_iw ippicv
-- 
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect photo video imgcodecs shape videoio highgui superres features2d calib3d stitching videostab
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3 ts viz
-- 
--   GUI: 
--     QT:                          NO
--     Cocoa:                       YES
--     OpenGL support:              NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        build (ver 1.2.8)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         build (ver 1.6.24)
--     TIFF:                        build (ver 42 - 4.0.2)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
--     GDCM:                        NO
-- 
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     Aravis SDK:                  NO
--     AVFoundation:                YES
--     V4L/V4L2:                    NO/NO
--     XIMEA:                       NO
--     gPhoto2:                     NO
-- 
--   Parallel framework:            GCD
-- 
--   Other third-party libraries:
--     Use Intel IPP:               2017.0.2 [2017.0.2]
--                at:               /Users/divbyzero/Documents/projects/OpenCV/opencv/build/3rdparty/ippicv/ippicv_mac
--     Use Intel IPP IW:            prebuilt binaries (2017.0.2)
--     Use Intel IPP Async:         NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Lapack:                  NO
--     Use Eigen:                   YES (ver 3.3.3)
--     Use Cuda:                    NO
--     Use OpenCL:                  YES
--     Use OpenVX:                  NO
--     Use custom HAL:              NO
-- 
--   OpenCL:                        <Link with OpenCL library>
--     Link libraries:              -framework OpenCL
--     Use AMDFFT:                  NO
--     Use AMDBLAS:                 NO
-- 
--   Python 2:
--     Interpreter:                 /Users/divbyzero/.pyenv/shims/python2.7 (ver 2.7.13)
-- 
--   Python 3:
--     Interpreter:                 /Users/divbyzero/.pyenv/shims/python3 (ver 3.6.1)
-- 
--   Python (for build):            /Users/divbyzero/.pyenv/shims/python2.7
-- 
--   Java:
--     ant:                         NO
--     JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:                        Matlab not found or implicitly disabled
-- 
--   Documentation:
--     Doxygen:                     NO
-- 
--   Tests and samples:
--     Tests:                       NO
--     Performance tests:           NO
--     C/C++ Examples:              NO
-- 
--   Install path:                  /usr/local
-- 
--   cvconfig.h is in:              /Users/divbyzero/Documents/projects/OpenCV/opencv/build
-- -----------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/divbyzero/Documents/projects/OpenCV/opencv/build

##### Steps to reproduce

**I have problem with make:**

> /Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:685:13: error: synthesized property 'mouseCallback' must either be named the same as a compatible instance
      variable or must explicitly name an instance variable
@synthesize mouseCallback;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:686:13: error: synthesized property 'mouseParam' must either be named the same as a compatible instance variable
      or must explicitly name an instance variable
@synthesize mouseParam;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:687:13: error: synthesized property 'autosize' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize autosize;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:688:13: error: synthesized property 'firstContent' must either be named the same as a compatible instance variable
      or must explicitly name an instance variable
@synthesize firstContent;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:689:13: error: synthesized property 'sliders' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize sliders;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:690:13: error: synthesized property 'status' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize status;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:838:13: error: synthesized property 'image' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize image;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:966:13: error: synthesized property 'slider' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize slider;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:967:13: error: synthesized property 'name' must either be named the same as a compatible instance variable or must
      explicitly name an instance variable
@synthesize name;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:968:13: error: synthesized property 'value' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize value;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:969:13: error: synthesized property 'userData' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize userData;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:970:13: error: synthesized property 'callback' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize callback;
            ^
/Users/divbyzero/Documents/projects/OpenCV/opencv/modules/highgui/src/window_cocoa.mm:971:13: error: synthesized property 'callback2' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize callback2;
            ^
13 errors generated.
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/window_cocoa.mm.o] Error 1
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

How can I fix it?

P.S. With -DCMAKE_OSX_ARCHITECTURES="x86_64" all is ok.

**Comment by alalek** [comment]
Looks like Apple doesn't support 32-bit compiler like 64-bit. Some features are just missing in 32-bit compiler.
Please check this: #8307

**Comment by divbyzero** [comment]
I've checked #8307. And all works fine.

> [ 83%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/window_cocoa.mm.o

So it's the solution for this problem. Thanks.

**Comment by divbyzero** [comment]
And I've checked and with latest contrib (master branch).
`cmake .. -DGLFW_BUILD_UNIVERSAL=ON \
        -DCMAKE_OSX_ARCHITECTURES="i386" \
        -DCMAKE_CXX_FLAGS="-fvisibility-inlines-hidden -arch i386 -m32 -fvisibility=hidden " \
        -DBUILD_SHARED_LIBS=OFF \
        -DBUILD_opencv_java=OFF \
        -DBUILD_opencv_python=OFF \
        -DWITH_1394=OFF \
        -DWITH_FFMPEG=OFF \
        -DWITH_QT=OFF \
        -DWITH_QUICKTIME=OFF \
        -DWITH_V4L=OFF \
        -DWITH_PVAPI=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_PERF_TESTS=OFF \
        -DWITH_LAPACK=OFF \
        -DOPENCV_EXTRA_MODULES_PATH=/Users/divbyzero/Documents/projects/OpenCV/opencv_contrib/modules`

Works fine too. I think need close this issue.
