### ISSUE TITLE
helllo sir,how can I print the opencv error information in Android?

### ISSUE THREAD

**Issue by 9crk** [opencv/opencv#8722]
I'v cross_compiled the opencv on my phone(armeabi).
when the opencv have some error,for example: I didnt compile the libjpeg into it.
it just directly crashed with no infomation.

how can I redirect the error log to android log-printing system?

**Comment by 9crk** [comment]
I'st hard to judge where the problem is,when the native part crash.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
