### ISSUE TITLE
Create write version of of cv::imreadmulti, cv:imwritemulti

### ISSUE THREAD

**Issue by saskatchewancatch** [opencv/opencv#8729]
Currently we have [cv::imreadmulti](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L585) which allows for multi-image Tiff files to be read. I very much like this. Probably the most common use case is to read in a bunch of related images for processing.

It is also useful to write out a vector of images to a single Tiff file. 

My feature request is simple. Signature of proposed addition to [loadsave.cpp](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp):

`bool imwritemulti(const String& filename, std::vector<Mat>& mats, const std::vector<int>& params)`

`mats` would be written out as a multi-image file. Currently the only multi-image format supported by OpenCV is TIff.

**Comment by saskatchewancatch** [comment]
Is this a possible addition? I have a few ideas in mind on how to go about this.

I'd appreciate some feedback on this proposal.

**Comment by StevenPuttemans** [comment]
@saskatchewancatch actually this sounds nice, but if you want the best feedback, then the way to go is to get a PR going with some implementation, which will draw the attention of the developers!

**Comment by saskatchewancatch** [comment]
#8913 has the first step. It's the direction I plan to take this. Is this sane?

If review is favourable, planned next step is to implement `BaseImageEncoder::writemulti(const std::vector<Mat>& img, const std::vector<int>& params`.

Enthusiastically awaiting your feedback. Open to alternate approaches.

**Comment by saskatchewancatch** [comment]
#8913 now contains a working implementation and a test that demonstrates the modification.

Review would be highly appreciated.

Thanks

**Comment by rounakskm** [comment]
Hi all,
I am fairly new to opencv and am having trouble finding this function.
Could anyone please tell me how to write a `vector<cv::Mat>` -- where each Mat is a Tiff image -- to one stacked Tiff file?
An example would be much appreciated.
