### ISSUE TITLE
Error from STL library while compiling for Android with ANDROID_STL=c++_static(shared)

### ISSUE THREAD

**Issue by vcpudding** [opencv/opencv#8742]
- OpenCV => 3.2
- Operating System / Platform => OSX

I have failed to compile opencv with NDK after setting ANDROID_STL to c++_static or c++_shared.
I have tried NDK r11 through r14, after fixing the NDK folder structuring problem, I still get errors while compiling any files that include STL headers such as <iostream>. Error messages are like the following:

```
In file included from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:107:0,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/string:438,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:15,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:216,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/iostream:38,
                 from /opencv/3rdparty/libtiff/tiffio.hxx:34,
                 from /opencv/3rdparty/libtiff/tif_stream.cxx:31:
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwctype:88:9: error: '::iswblank' has not been declared
 using ::iswblank;
         ^
In file included from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/string:438:0,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:15,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:216,
                 from /path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/iostream:38,
                 from /opencv/3rdparty/libtiff/tiffio.hxx:34,
                 from /opencv/3rdparty/libtiff/tif_stream.cxx:31:
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:132:9: error: '::vfwscanf' has not been declared
 using ::vfwscanf;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:133:9: error: '::vswscanf' has not been declared
 using ::vswscanf;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:134:9: error: '::vwscanf' has not been declared
 using ::vwscanf;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:150:9: error: '::wcstof' has not been declared
 using ::wcstof;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:151:9: error: '::wcstold' has not been declared
 using ::wcstold;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:155:9: error: '::wcstoll' has not been declared
 using ::wcstoll;
         ^
/path/to/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:159:9: error: '::wcstoull' has not been declared
 using ::wcstoull;
```

and there're hundreds more of them. Have tried replacing the toolchain from NDK/build/cmake as well as standalone toolchain exported from NDK/build/tools/make-standalone-toolchain.sh, all efforts failed and resulted in the same error as above.

**Comment by alalek** [comment]
What your toolchain compiler? clang/gcc?

http://stackoverflow.com/questions/30541066/android-ndk-cwctype-and-string-build-errors
suggests `gnustl_static`.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by vcpudding** [comment]
Compiler was gcc.

I found an identical question on OpenCV Q&A forum at [http://answers.opencv.org/question/118379/build-failure-with-android-ndk-r13b-and-c_shared/](http://answers.opencv.org/question/118379/build-failure-with-android-ndk-r13b-and-c_shared/)

Because there's no reply to the question, I posted an issue here. Sorry for the confusion.

**Comment by alalek** [comment]
But headers are from this path:

> llvm-libc++

so compiler should be clang.

**Comment by projectcs2103t** [comment]
So is it true that currently for opencv you can only build with gcc although gcc has been deprecated in new ndk versions?

**Comment by alalek** [comment]
BTW, Android NDK r15 has own CMake toolchain for Android - you could try to use it.

**Comment by pseandersson** [comment]
the c++ headeras are added in wrong order. See https://github.com/android-ndk/ndk/issues/452

**Comment by feliwir** [comment]
Any updates on this?

**Comment by alalek** [comment]
@feliwir ,

1. Try NDK15+ with **builtin** native CMake toolchain.
2. Disable OpenCV tracing support [here](https://github.com/opencv/opencv/blob/3.4.0/CMakeLists.txt#L320).

**Comment by feliwir** [comment]
@alalek
1.
I can’t use the builtin toolchain, since our codebase defines a lot platform specific variables in that. I am using NDK16 already, but the builtin CMake toolchain always made a great job.
2.
Thanks i will definetly try that.

**Comment by progre55** [comment]
@feliwir any luck so far? I'm hitting the same issues trying to compile OpenCV version 3.2.0 with c++_static and NDKr16, using the NDK native CMake toolchain.

**Comment by davnat** [comment]
Hi all,

I'm hitting the same issue, trying to compile OpenCV 3.4.1 or HEAD with c++_static and NDKr16.

I need C++11, so gnustl is not an option, and it appears to be impossible to set clang as the compiler.

This makes OpenCV not usable together with C++11 on Android, not to mention that gcc support is going to be discontinued in NDKr17 (coming very soon) and will be removed in NDKr18: https://github.com/android-ndk/ndk/wiki/Changelog-r17-beta2.

I could contribute some code, but I need some advice on where to start: the cmake files in OpenCV take thousands of lines of mostly undocumented code.

**Comment by alalek** [comment]
Android NDK provides own CMake toolchain file since r15. So solution is very simple - use it instead of custom OpenCV version (which leave for legacy NDKs).

Try something like this:
> cmake -GNinja -DINSTALL_ANDROID_EXAMPLES=ON -DANDROID_EXAMPLES_WITH_LIBS=ON -DBUILD_EXAMPLES=ON -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DWITH_IPP=ON -**DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=clang "-DANDROID_STL=c++_static" -DANDROID_ABI=x86** -DANDROID_SDK_TARGET=18 ../opencv

```
--     Android ABI:                 x86
--     NDK toolchain:               i686-linux-android-clang
--     STL type:                    c++_static
--     Native API level:            14
--   Android SDK:                   /opt/android/android-sdk (tools: 25.2.5 build tools: 27.0.2)
--     android tool:                /opt/android/android-sdk/tools/android
--     SDK target:                  android-18
--     Projects build scripts:      Ant/Eclipse compatible
```

**Comment by davnat** [comment]
This works! Thank you very much!

**Comment by victorv** [comment]
Latest NDK (17.0.4754217) warns gnustl_shared will be deprecated so this should eventually become the default setting.

`Android NDK: WARNING: APP_STL gnustl_shared is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    
`

**Comment by arghasilitonga** [comment]
@alalek I can't fix this issue. with your suggestion. I build this project on android studio

**Comment by aitazhixin** [comment]
https://github.com/opencv/opencv/issues/8742#issuecomment-385553011
How can i produce only one file libopencv_java3.so?

**Comment by starboy2102** [comment]
> Android NDK provides own CMake toolchain file since r15. So solution is very simple - use it instead of custom OpenCV version (which leave for legacy NDKs).
> 
> Try something like this:
> 
> > cmake -GNinja -DINSTALL_ANDROID_EXAMPLES=ON -DANDROID_EXAMPLES_WITH_LIBS=ON -DBUILD_EXAMPLES=ON -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DWITH_IPP=ON -**DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=clang "-DANDROID_STL=c++_static" -DANDROID_ABI=x86** -DANDROID_SDK_TARGET=18 ../opencv
> 
> ```
> --     Android ABI:                 x86
> --     NDK toolchain:               i686-linux-android-clang
> --     STL type:                    c++_static
> --     Native API level:            14
> --   Android SDK:                   /opt/android/android-sdk (tools: 25.2.5 build tools: 27.0.2)
> --     android tool:                /opt/android/android-sdk/tools/android
> --     SDK target:                  android-18
> --     Projects build scripts:      Ant/Eclipse compatible
> ```

HOW TO IMPLEMENT THIS??
