### ISSUE TITLE
[sorry,help pls]make error:make[2]: *** [lib/libopencv_dnn_modern.3.2.0.dylib] Error 1 make[1]: *** [modules/dnn_modern/CMakeFiles/opencv_dnn_modern.dir/all] Error 2: on MacOS Sierra(10.12.4)

### ISSUE THREAD

**Issue by Shuolongbj** [opencv/opencv#8747]
1、OS：
conda create -n caffe numpy scipy scikit-learn matplotlib ipython jupyter pandas python=3.6.1

MacOS Sierra(10.12.4)、Xcode(8.3.2)、Python(3.6.1)、gcc(4.8.5)

2、build：

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D PYTHON3_LIBRARY=/Users/Ru/anaconda/envs/opencv/lib/libpython3.6m.dylib \
    -D PYTHON3_INCLUDE_DIR=/Users/Ru/anaconda/envs/opencv/include/python3.6m \
    -D PYTHON3_EXECUTABLE=/Users/Ru/anaconda/envs/opencv/bin/python3 \
    -D PYTHON3_PACKAGES_PATH=/Users/Ru/anaconda/envs/opencv/lib/python3.6/site-packages \
    -D INSTALL_C_EXAMPLES=OFF \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D BUILD_EXAMPLES=ON \
    -D BUILD_opencv_java=OFF \
    -D BUILD_opencv_python3=ON \
    -D BUILD_opencv_python2=OFF \
    -D WITH_CUDA=OFF \
    -D WITH_IPP=OFF \
    -D WITH_FFMPEG=ON \
    -D WITH_OPENGL=OFF \
    -D WITH_OPENCL=OFF \
    -D WITH_IPP=OFF \
    -D WITH_TBB=OFF \
    -D WITH_EIGEN=ON \
    -D WITH_V4L=OFF \
    -D WITH_VTK=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=/Users/Ru/opencv_contrib/modules .. 

or

cmake -DWITH_FFMPEG=ON -DWITH_IPP=OFF -DWITH_CUDA=OFF -DBUILD_opencv_java=OFF -DWITH_OPENGL=OFF -DWITH_OPENCL=OFF -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_EIGEN=ON -DWITH_V4L=OFF -DWITH_VTK=OFF -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_opencv_python2=OFF -DCMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") -DPYTHON3_EXECUTABLE=$(which python3) -DPYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON3_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") -DINSTALL_C_EXAMPLES=OFF -DINSTALL_PYTHON3_EXAMPLES=ON -DBUILD_EXAMPLES=ON -DOPENCV_EXTRA_MODULES_PATH=/Users/Ru/opencv_contrib/modules .. 

3、error：

[ 44%] Linking CXX shared library ../../lib/libopencv_dnn_modern.dylib
Undefined symbols for architecture x86_64:
  "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))", referenced from:
      caffe::protobuf_caffe_2eproto::AddDescriptorsImpl()      in caffe_converter.cpp.o
  "google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)", referenced from:
      caffe::HDF5OutputParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::InfogainLossParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::Datum::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::FillerParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::ParamSpec::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::TransformationParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::DataParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)", referenced from:
      caffe::DataParameter::MergeFrom(caffe::DataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::ImageDataParameter(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::ImageDataParameter(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::MergeFrom(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::WindowDataParameter(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::WindowDataParameter(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::MergeFrom(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::WireFormatLite::WriteString(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::NetStateRule::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::V1LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
  "google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::Datum::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
  "google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::HDF5OutputParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::InfogainLossParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::HDF5DataParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::ParamSpec::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::PythonParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::FillerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::DataParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*)", referenced from:
      caffe::HDF5DataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::HDF5OutputParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::ImageDataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::InfogainLossParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::PythonParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::WindowDataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::ParamSpec::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)     in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::AssignDescriptors(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)", referenced from:
      caffe::protobuf_caffe_2eproto::(anonymous namespace)::protobuf_AssignDescriptors() in caffe_converter.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_dnn_modern.3.2.0.dylib] Error 1
make[1]: *** [modules/dnn_modern/CMakeFiles/opencv_dnn_modern.dir/all] Error 2
make: *** [all] Error 2

**Comment by Shuolongbj** [comment]
5、via make VERBOSE=1 and cc -Xlinker -v

5.1 make -j12 VERBOSE=1  error info:
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/shape/CMakeFiles/opencv_shape.dir/build.make modules/shape/CMakeFiles/opencv_shape.dir/build
make[2]: Nothing to be done for `modules/photo/CMakeFiles/opencv_photo.dir/build'.
make[2]: Nothing to be done for `modules/shape/CMakeFiles/opencv_shape.dir/build'.
make[2]: Nothing to be done for `modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build'.
[ 38%] Built target opencv_photo
[ 39%] Built target opencv_shape
[ 40%] Built target opencv_imgcodecs
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/videoio/CMakeFiles/opencv_videoio.dir/build.make modules/videoio/CMakeFiles/opencv_videoio.dir/depend
cd /Users/Ru/opencv/build && /Users/Ru/anaconda/envs/opencv/bin/cmake -E cmake_depends "Unix Makefiles" /Users/Ru/opencv /Users/Ru/opencv/modules/videoio /Users/Ru/opencv/build /Users/Ru/opencv/build/modules/videoio /Users/Ru/opencv/build/modules/videoio/CMakeFiles/opencv_videoio.dir/DependInfo.cmake --color=
Undefined symbols for architecture x86_64:
  "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))", referenced from:
      caffe::protobuf_caffe_2eproto::AddDescriptorsImpl()      in caffe_converter.cpp.o
  "google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)", referenced from:
      caffe::HDF5OutputParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::InfogainLossParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::Datum::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::FillerParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::ParamSpec::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::TransformationParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      caffe::DataParameter::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)", referenced from:
      caffe::DataParameter::MergeFrom(caffe::DataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::ImageDataParameter(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::ImageDataParameter(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::ImageDataParameter::MergeFrom(caffe::ImageDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::WindowDataParameter(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::WindowDataParameter(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      caffe::WindowDataParameter::MergeFrom(caffe::WindowDataParameter const&) in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::WireFormatLite::WriteString(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::NetStateRule::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::V1LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
  "google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::Datum::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
  "google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::HDF5OutputParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::InfogainLossParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::HDF5DataParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::ParamSpec::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::PythonParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::FillerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      caffe::DataParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*)", referenced from:
      caffe::HDF5DataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::HDF5OutputParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::ImageDataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::InfogainLossParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::PythonParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::WindowDataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)      in caffe_converter.cpp.o
      caffe::ParamSpec::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)     in caffe_converter.cpp.o
      ...
  "google::protobuf::internal::AssignDescriptors(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)", referenced from:
      caffe::protobuf_caffe_2eproto::(anonymous namespace)::protobuf_AssignDescriptors() in caffe_converter.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_dnn_modern.3.2.0.dylib] Error 1
make[1]: *** [modules/dnn_modern/CMakeFiles/opencv_dnn_modern.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/videoio/CMakeFiles/opencv_videoio.dir/build.make modules/videoio/CMakeFiles/opencv_videoio.dir/build
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/reg/CMakeFiles/opencv_reg.dir/build.make modules/reg/CMakeFiles/opencv_reg.dir/build
make[2]: Nothing to be done for `modules/reg/CMakeFiles/opencv_reg.dir/build'.
[ 40%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_avfoundation_mac.mm.o
cd /Users/Ru/opencv/build/modules/videoio && /Users/Ru/anaconda/bin/c++   -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/Users/Ru/opencv/build/3rdparty/zlib -I/Users/Ru/opencv/3rdparty/zlib -I/Users/Ru/opencv/build -isystem /usr/local/include/eigen3 -isystem /usr/local/include -I/Users/Ru/opencv/modules/videoio/include -I/Users/Ru/opencv/modules/videoio/src -I/Users/Ru/opencv/build/modules/videoio -I/Users/Ru/opencv/modules/core/include -I/Users/Ru/opencv/modules/imgproc/include -I/Users/Ru/opencv/modules/imgcodecs/include  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -O3 -DNDEBUG  -DNDEBUG -fPIC   -o CMakeFiles/opencv_videoio.dir/src/cap_avfoundation_mac.mm.o -c /Users/Ru/opencv/modules/videoio/src/cap_avfoundation_mac.mm
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/objdetect/CMakeFiles/opencv_objdetect.dir/build.make modules/objdetect/CMakeFiles/opencv_objdetect.dir/build
[ 41%] Built target opencv_reg
c++: error: /Users/Ru/opencv/modules/videoio/src/cap_avfoundation_mac.mm: Objective-C++ compiler not installed on this system
make[2]: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f modules/dnn/CMakeFiles/opencv_dnn.dir/build.make modules/dnn/CMakeFiles/opencv_dnn.dir/build
*** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_avfoundation_mac.mm.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[2]: Nothing to be done for `modules/objdetect/CMakeFiles/opencv_objdetect.dir/build'.
make[2]: Nothing to be done for `modules/dnn/CMakeFiles/opencv_dnn.dir/build'.
[ 41%] Built target opencv_objdetect
[ 43%] Built target opencv_dnn
make: *** [all] Error 2

**Comment by Shuolongbj** [comment]
5.2 cc -Xlinker -v error:

(opencv) Ru@bogon:~/opencv/build$ cc -Xlinker -v
collect2 version 4.8.5
/usr/bin/ld -dynamic -arch x86_64 -macosx_version_min 10.12.5 -weak_reference_mismatches non-weak -o a.out -L/Users/Ru/anaconda/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.5 -L/Users/Ru/anaconda/bin/../lib/gcc -L/Users/Ru/anaconda/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/../../.. -v -no_compact_unwind -lSystem -lgcc_ext.10.5 -lgcc -lSystem
@(#)PROGRAM:ld  PROJECT:ld64-278.4
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
Library search paths:
	/Users/Ru/anaconda/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5
	/Users/Ru/anaconda/lib/gcc
	/Users/Ru/anaconda/lib
	/usr/lib
	/usr/local/lib
Framework search paths:
	/Library/Frameworks/
	/System/Library/Frameworks/
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by Shuolongbj** [comment]
@alalek thank you.

**Comment by alalek** [comment]
Feel free to disable module if you don't need them: `cmake -DBUILD_opencv_dnn_modern=OFF ...`

> c++: error: /Users/Ru/opencv/modules/videoio/src/cap_avfoundation_mac.mm: Objective-C++ compiler not installed on this system

Probably you need clang/Xcode instead of gcc.

We don't use Anaconda, so we can't help a lot here.

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Shuolongbj** [comment]
thank you! i'll uninstall gcc and reinstall Xcode.
