### ISSUE TITLE
Weird behaviour with vector<string> and vector<String>

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8748]
Hi,

##### System information (version)
- OpenCV => 3.2-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

My code : 
```

void TestType(InputArrayOfArrays points2d)
{
    cout << "vector Point2d\n";
}
void TestType(std::vector <std::string> &images)
{
    cout << " vector string\n";
}
void main()
{
    vector<string> x={"test"};
    vector<String> y={"test"};
    TestType(x);
    TestType(y);
}

```
and results is 

```
 vector string
vector Point2d

```

I found this problem in sfm module calling  void cv::sfm::reconstruct 	( 	const std::vector< std::string >  	images,.... 		) 	 or void cv::sfm::reconstruct 	( 	InputArrayOfArrays  	points2d, ) using FileStorage with vector<cv::String>

**Comment by alalek** [comment]
Related issue of InputArray: #8411 
Type traits (`DataType`) problem of default value: #7599

**Comment by LaurentBerger** [comment]
Ok It seems a long way to use a new type in Opencv. A PR to change prototype in SFM seems simpler. Is it right?
