### ISSUE TITLE
findChessboardCorners flags naming

### ISSUE THREAD

**Issue by hohlihin** [opencv/opencv#8760]
- OpenCV => 3.2.0
- Operating System / Platform => Linux Mint 18.1 x64
- Compiler => gcc 5.4.0
- Python => 3.5.2

##### Detailed description

Regarding following document:
http://docs.opencv.org/trunk/d9/d0c/group__calib3d.html#ga93efa9b0aa890de240ca32b11253dd4a
several constantthat related with findChessboardCorners "flags" argument, have to be presented in OpenCV Python buinding:
CV_CALIB_CB_ADAPTIVE_THRESH
CV_CALIB_CB_NORMALIZE_IMAGE
CV_CALIB_CB_FILTER_QUADS

Actually, following constants are defined:
CALIB_CB_ADAPTIVE_THRESH
CALIB_CB_NORMALIZE_IMAGE
CALIB_CB_FILTER_QUADS

Looks like documentation issue. 

Nevertheless, code analysis of the OpenCV shown, that CV_CALIB_CB_ADAPTIVE_THRESH is defined in:
modules/calib3d/include/opencv2/calib3d/calib3d_c.h
and CALIB_CB_ADAPTIVE_THRESH is defined in:
modules/calib3d/include/opencv2/calib3d.hpp

It seems like different constant naming for C and C++ OpenCV buinding. 

But CV_CALIB_CB_ADAPTIVE_THRESH is still used in following C++ file:
modules/calib3d/test/test_chesscorners_badarg.cpp

**Comment by gaurav1024** [comment]
Is this issue this open? If yes, can I give it a try.

**Comment by mshabunin** [comment]
@gaurav1024 , the fix for _2.4_ branch has been merged (#8761), you can port it to _master_ branch.

**Comment by alalek** [comment]
#8788
