### ISSUE TITLE
VideoCapture Frame Timestamp

### ISSUE THREAD

**Issue by aseyfi** [opencv/opencv#8763]
##### System information (version)

- OpenCV => 3.2

##### Detailed description

Hello,

I used [VideoCapture::get](http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-get) with CV_CAP_PROP_POS_MSEC property identifier to read the timestamp of the last retrieved frame, but the return value was zero. There is a bug in [cap_v4l.cpp](https://github.com/opencv/opencv/blob/3.2.0/modules/videoio/src/cap_v4l.cpp) file the causes this problem. The value of the timestamp is copied from a buffer in [this line](https://github.com/opencv/opencv/blob/3.2.0/modules/videoio/src/cap_v4l.cpp#L868), but the the data in the buffer in not valid because we have already called VIDIOC_QBUF ioctl [here](https://github.com/opencv/opencv/blob/3.2.0/modules/videoio/src/cap_v4l.cpp#L864). The solution is to flip the two lines of the code, so we read the timestamp before calling VIDIOC_QBUF ioctl.

Thank You,
Ahmad

**Comment by ayeletza** [comment]
I have the updated one but I still get zero.... Any idea?
Thanks a lot!

**Code on rows 860-873:**
```
   memcpy(capture->buffers[MAX_V4L_BUFFERS].start,
      capture->buffers[buf.index].start,
      capture->buffers[MAX_V4L_BUFFERS].length );
   capture->bufferIndex = MAX_V4L_BUFFERS;
   //printf("got data in buff %d, len=%d, flags=0x%X, seq=%d, used=%d)\n",
   //	  buf.index, buf.length, buf.flags, buf.sequence, buf.bytesused);

   //set timestamp in capture struct to be timestamp of most recent frame
   capture->timestamp = buf.timestamp;

   if (-1 == ioctl (capture->deviceHandle, VIDIOC_QBUF, &buf))
       perror ("VIDIOC_QBUF");

   return 1;
```
