### ISSUE TITLE
Error on Python Tutorial, Section: Machine Learning with SVM

### ISSUE THREAD

**Issue by kuntoro-adi** [opencv/opencv#8791]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 10 64 Bits
- Compiler => PreBuilt binary

##### Detailed description

I found this error on opencv python 3.2 tutorial.

##### Steps to reproduce

I test machine learning sample code from http://docs.opencv.org/3.2.0/dd/d3b/tutorial_py_svm_opencv.html and it returns an 

> cv2.error: C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\ml\  src\svm.cpp:1618: error: (-5) in the case of classification problem the response  s must be categorical; either specify varType when creating TrainData, or pass i  nteger responses in function cv::ml::SVMImpl::train

I tried to fixed it by changing the response type from float to int, from

`responses = np.float32(np.repeat(np.arange(10),250)[:,np.newaxis])`

to

`responses = np.repeat(np.arange(10),250)[:,np.newaxis]`

However, the outcome of the classification is still not shown properly.

After some investigation, I found a solution. This function call

`result = svm.predict(testData)`

does not return an array of result but it returns a tuple instead. I believe this is the output of print(result)

> (0.0, array([[ 0.],
       [ 0.],
       [ 0.],
       ...,
       [ 9.],
       [ 9.],
       [ 9.]], dtype=float32))

So, instead of writing

`mask = result==responses`

the solution that worked for me is

`mask = result[1] == responses`

http://www.answers.opencv.org/question/150063/python-svm-function-svmpredicttestdata-returns-tuple-instead-of-numpy-array/

**Comment by berak** [comment]
@kuntoro-adi , it's nice, thatyou finally took the trouble of writing down the issue here, unfortunately, you're about a week late, the [resp. pr](https://github.com/opencv/opencv/pull/8754) is already merged ;)

(i think, we can close this)
