### ISSUE TITLE
VS2013: halfconvert_oclsrc is not a member of cv::ocl::core

### ISSUE THREAD

**Issue by PkLab** [opencv/opencv#8801]
#### System information (version)
- OpenCV => master
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

#### Detailed description

As subject, unable to build current master after #8743

**Comment by alalek** [comment]
There is added new file. You should re-run cmake on update / or just build from scratch.

**Comment by PkLab** [comment]
of course I've pulled latest master and cleared cmake cache than rebuild.

I've checked that the files `<build-dir>/modules/core/opencl_kernels_core.*` aren't regenerated even if I've the file `<src_dir>/module/core/src/opencl/halfconvert.cl`. 

I solved deleting opencl_kernels_core.* and rebuild the core module or creating a completely new build.
