### ISSUE TITLE
Issues found when building with MSVC + /permissive-

### ISSUE THREAD

**Issue by xiangfan-ms** [opencv/opencv#8804]
The C++ compiler team is currently doing daily RWC (Read World Code) testing which includes OpenCV.
We are also working with internal partners and the community to fix source issues exposed by "/permissive-".
The option isn’t finalized yet (we plan to add some large impact features into it in the incoming VS update), so we don’t suggest to adopt it yet.
In the meantime, we want to address these source issues as early as possible so that the community can adopt it when it is finalized.
We discover some source issues when we build it with "/permissive-".

The issue is in 'samples\directx\d3dsample.hpp'.

Here is a simplified repro:

	#include <string>

	template<typename T>
	void f()
	{
		string s;
	}

	using namespace std;

	int main()
	{
		f<void>();
	}

It happens to work because MSVC doesn't implement two phase name lookup in default mode.

The fix for this issue is to add 'std::':

    string file      = parser.get<string>("file");
->

    std::string file      = parser.get<std::string>("file");

**Comment by mshabunin** [comment]
Fixed in #9515
