### ISSUE TITLE
cvStream = StreamAccessor::wrapStream(stream), giving errors

### ISSUE THREAD

**Issue by antithing** [opencv/opencv#8806]
I am trying to use the following code inside a lib:

` cudaStream_t stream;`
 `Stream cvStream;`
`checkCudaErrors( cudaStreamCreate(&stream) );`
`cvStream = StreamAccessor::wrapStream(stream);`

Strangely, the lib compiles fine, but when i compile another application that calls the lib, I get:

`unresolved external symbol "public: static class cv::cuda::Stream __cdecl cv::cuda::StreamAccessor::wrapStream(struct CUstream_st *)" (?wrapStream@StreamAccessor@cuda@cv@@SA?AVStream@23@PEAUCUstream_st@@@Z)	1	
`

I am linking to `opencv_cudaarithm320.lib`, and am including
 `#include "opencv2/core/cuda_stream_accessor.hpp"`
..in both the lib and the other application.

IS this a bug? or, more likely, am I missing something? (when i comment out the line `cvStream = StreamAccessor::wrapStream(stream);`, both compile fine. )
thank you.

**Comment by alalek** [comment]
You need to debug your build process (via make `VERBOSE=1`, CXXFLAGS="-H" option, etc) and check that used headers/libs are valid (not used from other OpenCV installations, like "/usr/local" or system "/usr/include/opencv")

**Comment by antithing** [comment]
Hi, thanks for getting back to me.  I am on windows. Do you mean make sure that all the libs are from a cuda enabled build of opencv?

**Comment by antithing** [comment]
Rebuilding openCv from scratch, and linking to the new libs has fixed this. thank you again for your time.
