### ISSUE TITLE
OpenCV Python tutorials need to be updated

### ISSUE THREAD

**Issue by piotrek-k** [opencv/opencv#8808]
I'm specifically talking about [Understanding k-Nearest Neighbour tutorial](http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.html#knn-understanding)

1. There is no such a thing like `cv2.KNearest()` ([replaced by ml.Knearest_create()?](https://stackoverflow.com/questions/29369907/opencv-3-0-0-beta-missing-knn))
2. Also, you are using there Python 2.* (you are using "print" without brackets). Don't you think it's time to migrate to 3.*?
3. "Bug report" link at the bottom of page leads to not functioning wiki.

Also, maybe it's high time to enable comments to each article, so community could explain possible inaccuracy of tutorials there.

**Comment by piotrek-k** [comment]
As I see, it's not only me having problem with it:
https://stackoverflow.com/questions/32980675/knn-train-in-cv2-with-opencv-3-0
Question viewed 5040 times, answer upvoted 21 times.

**Comment by alalek** [comment]
You post links to very outdated documentation - all of them points to `3.0.0-beta`.
Right tutorial for OpenCV 3.x is [here](http://docs.opencv.org/master/d5/d26/tutorial_py_knn_understanding.html).

1. Already fixed.
2. I believe this is not a problem.
3. Do you know the right link?


> enable comments to each article

No. At least there is no resource for moderation of this.

**Comment by prakamya-mishra** [comment]
Hey I am new I contributing to opencv. so can I please do this issue.

**Comment by mshabunin** [comment]
Looks like this issue has been fixed or is not relevant anymore.
