### ISSUE TITLE
Allow openh264-x.x.x-win??msvc.dll to be found via %PATH%

### ISSUE THREAD

**Issue by Anton-V-K** [opencv/opencv#8812]
##### System information (version)

- OpenCV => 3.2.0-vc14
- Operating System / Platform => Windows 7 SP1 64 Bit
- Compiler => Visual Studio 2015/2017

### Detailed description

When loading `openh264-1.6.0-win64msvc.dll` OpenCV engine doesn't use `%PATH%` when searching for this binary.
It expects (according to `\sources\3rdparty\ffmpeg\readme.txt`) that ...

> ... binary file can be placed into global system path (System32 or SysWOW64) or near application binaries.
>  You can also specify location of binary file via `OPENH264_LIBRARY_PATH` environment variable.

### Actual situation

1. `OPENH264_LIBRARY` (and not `OPENH264_LIBRARY_PATH` - fixed in #6080) allows to specify either full path for the binary to load (a kind of side effect, I guess), or overridden name for the binary.
2. The binary is loaded either from application directory (checked - working), or from system directory (I haven't checked this).
3. Directories from `%PATH%` are ignored when searching for the binary, thus causing inconvenience for non-EXE applications using OpenCV (like Python scripts - [example](https://stackoverflow.com/questions/41972503/could-not-open-codec-libopenh264-unspecified-error)).

### Expected situation

OpenCV should follow "standard" search path strategy for the binary file loading:

1. Application directory.
2. System directory.
3. Directories specified in `%PATH%`.

### Side-effects of `OPENH264_LIBRARY`

I guess, it is possible to have/run 32-bit and 64-bit applications with OpenCV on the same 64-bit PC, so `OPENH264_LIBRARY` will present a conflicting DLL name for such applications.

**Comment by alalek** [comment]
- Name is fixed in this readme file.

- > Directories from %PATH% are ignored
  
  `LoadLibrary` function is used which uses `%PATH%` environment. Added statement about `LoadLibrary`.
