### ISSUE TITLE
Scripts to build opencv for iOS and Android target v2

### ISSUE THREAD

**Issue by gsabran** [opencv/opencv#8821]
The scripts in https://github.com/opencv/opencv/tree/master/platforms for ios and android target opencv v2 while the main branch is for v3. For instance see https://github.com/opencv/opencv/blob/master/platforms/ios/build_framework.py#L220

For iOS (I'm not an Android user) it seems that simply replacing `opencv2` by `opencv` fixes the issue, but I thought it'd be better to double check before making a PR, and to know if you'd rather the scripts to target v3 directly, or take an argument to target either v2 or v3 because they are referenced in places like in the 2.4 docs: http://docs.opencv.org/2.4.9/doc/tutorials/introduction/ios_install/ios_install.html

**Comment by alalek** [comment]
"opencv2" is the actual name for OpenCV header files. Replacing will not help here, because we should rename folders at first.

**Comment by gsabran** [comment]
That's what I ended up thinking, even if it's quite confusing! thanks
