### ISSUE TITLE
MacOS can't install opencv3.2 by homebrew

### ISSUE THREAD

**Issue by tikkat3** [opencv/opencv#8826]
i use homebrew 
step:
1. install homebrew
2. install cmake
3. install opencv3
4.  cd   /usr/local/Cellar/opencv3 
i found there is not  had the file "CMakeLists.txt"
and  i can't do next step "cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX= /usr/local "
the terminal hint : 
CMake Error: The source directory "/usr/local/Cellar/opencv3" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

what should i do ?  thanks a lot

##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Mac OS Sierra 10.12.5   64 Bit

**Comment by adadesions** [comment]
According from the link https://www.learnopencv.com/install-opencv-3-on-yosemite-osx-10-10-x/
you no need to build it again by cmake.

But, you have to make your own CMakeList.txt file in your file project.
^^

**Comment by aigeek** [comment]
I can not continue even at the first line😢:

$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 694, done.
remote: Compressing objects: 100% (687/687), done.
remote: Total 694 (delta 0), reused 52 (delta 0), pack-reused 0
Receiving objects: 100% (694/694), 636.92 KiB | 243.00 KiB/s, done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/kmc.rb
"cxx14" is not a recognized standard
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/scram.rb
"cxx14" is not a recognized standard
Error: Cannot tap homebrew/science: invalid syntax in tap!

I didn't find useful answer...

Why there are no newest and useful tutorials about making&installing opencv&opencv_contrib here or on official website?It took me a lot of time to configure these things .And I can not write the real code for a  day,It feels so bad.

I build the project by the tutorial:"https://www.learnopencv.com/install-opencv-3-on-yosemite-osx-10-10-x/", but after I built a new project with these library in XCode,I still can not find the method "createLBPHFaceRecognizer".  Is there some other tutorial for use opencv3+opencv_contrib in XCode? Thanks a lot!

**Comment by alalek** [comment]
@aigeek 

> "cxx14" is not a recognized standard

This doesn't come from OpenCV. Check homebrew for this.

**Comment by aigeek** [comment]
I install it by your tutorial （I give up homebrew..） finally ,Tks!

**Comment by tikkat3** [comment]
@adadesions Thanks a lot !

**Comment by adadesions** [comment]
@tikkat3 My pleasure^^
