### ISSUE TITLE
Getting error while installing Opencv-3.2.0 on Ubuntu 16.04 WITH_CUDA=ON option

### ISSUE THREAD

**Issue by codestamp** [opencv/opencv#8827]
I am running cmake on my Ubuntu 16.04 system as under:

cmake -D CMAKE_BUILD_TYPE=RELEASE \
           -D CMAKE_INSTALL_PREFIX=/usr/local \
           -D WITH_CUDA=ON \
           -D ENABLE_FAST_MATH=1 \
           -D CUDA_FAST_MATH=1 \
          -D WITH_CUBLAS=1 .

The configuration works to its completion. After when I run make -j8, the following error crops up:

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libhdf5.so', needed by 'lib/libopencv_hdf.so.3.2.0'.  Stop.
CMakeFiles/Makefile2:3193: recipe for target 'modules/hdf/CMakeFiles/opencv_hdf.dir/all' failed
make[1]: *** [modules/hdf/CMakeFiles/opencv_hdf.dir/all] Error 2

**Comment by archenroot** [comment]
With OpenCV 3.* there was some reorganization, some modules were moved into multiple contribution modules, there is not just one. 
I am not 100% sure, but it looks to me, like you compiled OpenCV without contributed modules.. that is the reason...

**Comment by codestamp** [comment]
Yes that's true, I compiled OpenCV without the contributed modules. I uninstalled libhdf5 and did a complete fresh install (again with contributed modules) and all things worked well.

**Comment by alalek** [comment]
Always rerun CMake from scratch (clean build directory) after build environment changes (like package install/remove/upgrade) - see "CMake cache" for more information.

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by codestamp** [comment]
Many thanks @alalek
