### ISSUE TITLE
highgui-video VideoCapture different time stamp bug

### ISSUE THREAD

**Issue by ArrrHub** [opencv/opencv#8834]
##### System information (version)

- OpenCV => 2.4.13.2
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Loading an mkv ( 264) video file and iterating to a specific frame with VideoCapture reports a different time using get(CV_CAP_PROP_POS_MSEC) than Video Players (checked with VLC and MPC-HC). The difference equals about 10 frames for a 2 minute video.

**Comment by ArrrHub** [comment]
Any updates on that one ?

**Comment by fishjam** [comment]
- Issue
  When I use opencv with ffmpeg(3.4.2), I use VideoCapture::get(CV_CAP_PROP_POS_MSEC) to get the time, it's not same with real frame pos time, compare with pkt_pts_time get from ffprobe -show_frames. 

- Analyzer
  I think it's opencv's bug. Ref [CvCapture_FFMPEG::getProperty](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L1165), it return frame_number/get_fps(), this could be valid for CFR(Constant Frame Rate), but invalid for VFR(Variable Frame Rate).

- Solution
  refactor CvCapture_FFMPEG::getProperty for CV_FFMPEG_CAP_PROP_POS_MSEC, that return value calculate from picture_pts.
```
  return (dts_to_sec(picture_pts) * 1000 + 0.5);
```

- TODO:
  - 1. There are lots of IVideoCapture implements class, need confirm;
  - 2. There is setProperty function, need confirm too.

@mshabunin could you confirm and try to fix it?
