### ISSUE TITLE
CMake could not find gstreamer configurations automatically

### ISSUE THREAD

**Issue by stnk20** [opencv/opencv#8836]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows7 64Bit
- Compiler => Visual Studio 2015
- Gstreamer & Gstreamer-dev is installed
- pkg-config is installed

##### Detailed description
CMake could not find gstreamer configurations automatically.
This problem is caused by supposing that gstreamer version is 1.0 fixed in a file below ( line 22,38 ).
 https://github.com/opencv/opencv/blob/master/cmake/OpenCVFindLibsVideo.cmake

I fixed this problem by editing some cmake scripts.
https://github.com/opencv/opencv/pull/8835
Referring to this thread.
 http://answers.opencv.org/question/65059/opencv-300-build-winder-windows-8-with-gstreamer10-support/

For this change working, there is additional dependency:
- install pkg-config
- set PKG_CONFIG_PATH=(path_to_gstreamer)\1.0\(arch)\lib\pkgconfig

**Comment by stnk20** [comment]
> This problem is caused by supposing that gstreamer version is 1.0 fixed in a file below ( line 22,38 ).

I investigated further and found that fixing gstreamer version is trivial problem.
I found that the version defined there is used only for displaying cmake configure log.

Finally, I got workaround that does not rely on pkg-config:
* add cmake variable GSTREAMER_DIR=(path to gstreamer)

**Comment by Bahramudin** [comment]
@stbnps I still have this error, what can be the reason?

**Comment by stnk20** [comment]
Did you try this ?
> Finally, I got workaround that does not rely on pkg-config:
> * add cmake variable GSTREAMER_DIR=(path to gstreamer)

**Comment by Bahramudin** [comment]
@stnk20 Hi! Where to add this in cmake, I am using cmake-gui, but I did not see anything like GSTREAMER_DIR as you mentioned?

**Comment by Bahramudin** [comment]
@stnk20 
![qq 20171102130451](https://user-images.githubusercontent.com/13574895/32310600-799b3156-bfce-11e7-945a-97e924ea622c.png)

**Comment by Bahramudin** [comment]
@stnk20 
![hqbw limx1_x9z 0tdp8as3](https://user-images.githubusercontent.com/13574895/32310630-b0c9c6e2-bfce-11e7-8b1d-44b561f3c5b6.png)

**Comment by stnk20** [comment]
@Bahramudin 
Click [Add Entry] button on cmake-gui , and input like below:

Name : GSTREAMER_DIR
Type : PATH 
Path : (path to gstreamer parent dir)

**Comment by Bahramudin** [comment]
@stnk20 Again the same problem?
![ae56 21 nme6n_ wub f9](https://user-images.githubusercontent.com/13574895/32313681-15c79082-bfdf-11e7-91ee-3bfb231c0524.png)

**Comment by stnk20** [comment]
Have you installed gstreamer and gstreamer-devel ? @Bahramudin

**Comment by Bahramudin** [comment]
@stnk20 I only installed GStreamer. Could you tell me that what is the steps to in installing the GStreamer, e.g: first install which one, and after installation what need to do e.g setting environment variables etc. This can be helped to be sure that everything installed well. Thanks!!

**Comment by Bahramudin** [comment]
@stnk20 Yes sir it is done now::))) Thanks!!

**Comment by Bahramudin** [comment]
@stnk20 Bro! This new problem happened,  it is why?
![_kci4q 10 kb0 0a8o j](https://user-images.githubusercontent.com/13574895/32317373-9cb1eff2-bfee-11e7-9c42-225e8215f7f7.png)

**Comment by alalek** [comment]
Add this CMake option to workaround this: `OPENCV_SKIP_PKGCONFIG_GENERATION=ON`
It would be useful to attach CMake log files (CMakeCache.txt / CMakeVars.txt)

**Comment by Bahramudin** [comment]
@stnk20 Sorry! Is it also added Entry?

**Comment by alalek** [comment]
There are many internal variables in OpenCV CMake scripts (they are not showed in cmake-gui). This variable should be filled manually or via command line.

**Comment by Bahramudin** [comment]
@stnk20 You mean that edit `CMakeLists.txt`?

**Comment by Bahramudin** [comment]
![rwf b6qo _w_ mnpdq xua](https://user-images.githubusercontent.com/13574895/32318574-a336ae04-bff2-11e7-97f4-0ae172152659.png)

**Comment by Bahramudin** [comment]
@stnk20 In both of these file  (CMakeCache.txt / CMakeVars.txt) not found `OPENCV_SKIP_PKGCONFIG_GENERATIO`N

**Comment by alalek** [comment]
> not found 

This is expected.

Run this in terminal (cmd.exe) in build folder:
```
cmake -DOPENCV_SKIP_PKGCONFIG_GENERATION=ON .
```

Or add this custom variable via cmake-gui ("Add Entry" button).

---
I'm asking for log files to check that is wrong with build configuration, because we don't observe such issues on Windows [builds](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master) (but these builds are without GStreamer).

**Comment by Bahramudin** [comment]
@stnk20 Thanks you very much, I have changed a machine, now it works well, it was the problem with the previous version of OpenCV which when downloaded it again the problem has been gone.

**Comment by Bahramudin** [comment]
@stnk20 hi bro! one more question, now it seems that GStreamer is working, so now I want to write/push the frame to a video server or to the HTML page, so how it can be possible with GStreamer. It is the last step. I hope that it works. Thanks!!

**Comment by stnk20** [comment]
From here, I think it is matters of gstreamer usage.
Video streaming to browser is not so easy, because of browser compatibility.

One way I know is, using hlssink ( http live streaming ) .  It works for some browsers.
* Write gstreamer script began with "appsrc" element in VideoWriter class. ( google hlssink for detail)
* Run typical http server, and serve .m3u8 playlist generated by hlssink plugin. 
* Set .m3u8 playlist to src of HTML video tag.

You can use other gstreamer script, so you should write script matches your case.
