### ISSUE TITLE
cv::fastNlMeansDenoising freeze program with empty cv::Mat() as src

### ISSUE THREAD

**Issue by anmoluppal** [opencv/opencv#8839]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Elementary OS 64-bit
- Compiler => GCC

##### Detailed description

The program execution suspends for an indefinite amount of time, if we pass empty `cv::Mat` as input to `cv::fastNlMeansDenoising`.

##### Steps to reproduce

```cpp
int main() {
    cv::Mat mat;
    cv::fastNlMeansDenoising(mat, mat);
}
```

**Comment by alalek** [comment]
Thank you for report!
There is "vote" issue with possible solutions for similar cases: #8300
