### ISSUE TITLE
HighGUI windows on Windows do not remember position on multiple screens

### ISSUE THREAD

**Issue by adishavit** [opencv/opencv#8840]
On Windows, the position of HighGUI windows is saved in the registry so that on the next run they are opened in the same position (if they have the same name). This is a _very_ convenient feature.

However, it does not work correctly when the windows is on 2nd/external screen/display/monitor.

I guess this is somewhere between a bug report and a feature request.

**Comment by dkurt** [comment]
@adishavit, saving and loading works fine but there is some limitation: https://github.com/opencv/opencv/blob/master/modules/highgui/src/window_w32.cpp#L327. So after loading it resets to specific coordinate.

**Comment by adishavit** [comment]
Yes, that seems a bit arbitrary.
I am making a PR that fixes this by snapping to the nearest monitor and correctly handling nultimonitor setups.

**Comment by sturkmen72** [comment]
just an idea what about removing the restrictions and adding a new flag to namedWindow like WINDOW_FORGETHISTORY which when it is true namedWindow creates the window without using values saved to registry

**Comment by adishavit** [comment]
@sturkmen72 : that was never a problem for me.

**Comment by sturkmen72** [comment]
Fixed by #9456
