### ISSUE TITLE
line function bug

### ISSUE THREAD

**Issue by dasolma** [opencv/opencv#8846]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 64bits
- Compiler => gcc
- Wrapper => Python

##### Detailed description

Draw a simple line with outbounds coordinates generates multiple lines
![test](https://cloud.githubusercontent.com/assets/6043733/26752686/2ee8bede-4856-11e7-97cb-497200a620db.png)

##### Steps to reproduce
import cv2
import numpy as np
from PIL import Image
draw = np.zeros((256, 256, 4), np.uint8)
cv2.line(draw, (34, 204), (46400, 47400), (0,0,0,255), thickness=2)
image = Image.fromarray(draw)
image.save("test.png", "png")

**Comment by alalek** [comment]
Should be resolved by #7161 .
Try OpenCV 3.2.0 release, or latest code from "master" branch.

**Comment by dasolma** [comment]
Version: 3.2.0 release and 3.2.0-dev from master following the instructions: http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

The previous bug continue.
