### ISSUE TITLE
Java wrappers for modules, which use protobuf, are not generated properly 

### ISSUE THREAD

**Issue by abratchik** [opencv/opencv#8849]
##### System information (version)

- OpenCV => 3.2 master (fdba54885894aa875028ad08f53318d799509532)
- Operating System / Platform => OSX El Capitain 10.11.6 (15G1421)
- Compiler => Xcode Version 8.1 (8B62)

##### Detailed description

Java wrappers are not generated for dnn module. Enabling java for dnn leads to compilation errors related to the following issues:

1. Google protobuf library headers are not visible to java cmake scripts so building dnn with java leads to errors like below:
 
```
fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.

```
2. Some constants are defined using cross-references to constants in other namespace, which is not interpreted properly by java generator. Example:
`
CONST DataType_INT_MIN_SENTINEL_DO_NOT_USE_=::google::protobuf::kint32min
`

3. CMake generates a lot of  warnings when building dnn with java support. These warnings are harmless (ex non-used variable in protobuf headers) and can be skipped to ensure clean logs  

##### Steps to reproduce

1. Enable contrib modules
2. Enable java wrappers generation for dnn module 
3.  build opencv

**Comment by alalek** [comment]
Bindings is a wrapper over OpenCV public interface. By design, OpenCV public API should not depend on 3rdparty libraries (in general).

Probably, protobuf dependency should be removed from the public headers.
BTW, `INT_MIN_SENTINEL_DO_NOT_USE` constant is from "private" header file (from "src" directory) - it should not be used outside.

**Comment by abratchik** [comment]
Hi, alalek,

agree with you however protobuf is a 3rd party library, which is added through dnn module. When java wrapper is trying to build bindings for dnn, it cannot compile the C wrappers because generated proto headers have dependency on protobuf headers, which are not visible to cmake.
If you can advise better option how to avoid changing cmake scripts for java module I'd be happy to follow your advice.
Regarding INT_MIN_SENTINEL_DO_NOT_USE - imho this is a harmless fix, which is  skipping constants where value contains double colon "::".

**Comment by alalek** [comment]
@abratchik  Could you try this fix: https://github.com/alalek/opencv/commit/fix_java_headers ?
Alternative, you could create file like [this](https://github.com/opencv/opencv/blob/master/modules/features2d/misc/java/filelist) for dnn module.

**Comment by abratchik** [comment]
Let me explore alternatives. By the way why is it better than current solution? Do you expect that protobuf will not be used eventually? If it stays than, regardless whether it is in contrib or main repository, the suggested fragment will work properly.

**Comment by abratchik** [comment]
Hi, Alex, I see that you have already updated cmake for java, right? So please guide me what I need to do now - should I roll back my changes to java cmake in this pull request? I hope the fix for skipping constants with "::" references can stay, right? Please confirm.

**Comment by abratchik** [comment]
👍 tried your fix and it works well. So please merge your change and I'll roll back mine. from this pull request.
