### ISSUE TITLE
can not find the function cvWarpPerspectiveQMatrix

### ISSUE THREAD

**Issue by GitSoftwareNow** [opencv/opencv#8855]
The version number is 3.2.0,the compiler can not find the function "cvWarpPerspectiveQMatrix " and the macro __BEGIN__ __END__

**Comment by mshabunin** [comment]
@GitSoftwareNow , what is your OpenCV version?

**Comment by GitSoftwareNow** [comment]
@mshabunin The version number is 3.2.0,the compiler can not find the function "cvWarpPerspectiveQMatrix " and the macro BEGIN END

**Comment by mshabunin** [comment]
Can you attach cmake and compiler output?

**Comment by alalek** [comment]
"cv*" C-like API is deprecated and will be removed.
Try to use this instead: [`cv::getPerspectiveTransform()`](http://docs.opencv.org/3.2.0/da/d54/group__imgproc__transform.html#ga8c1ae0e3589a9d77fffc962c49b22043)

**Comment by GitSoftwareNow** [comment]
what's different form between cv::getPerspectiveTransform() and cvWarpPerspectiveQMatrix? I tried to using cvWarpPerspectiveQMatrix in the version 3.2 but the compipler can not find the symbole of cvWarpPerspectiveQMatrix

**Comment by alalek** [comment]
Because this function has gone from OpenCV 3.x (deprecated API).
Replacement is mentioned above.
