### ISSUE TITLE
What is the best Head Cascade in OpenCV

### ISSUE THREAD

**Issue by melzoghbi** [opencv/opencv#8858]
Hi,

I am using OpenCV 3.1 on a Raspbian Jessie OS using pi zero board. 

I used "haarcascade_frontalface_alt" for face detection and it works really good on low resolution images using Python. What i want to do is to **detect the heads of people** since i may not have their faces in the captured images. 

What is the best cascade to use in this case? also is there a catalog page that describe existing cascades and the use case for each one?

Thanks.

**Comment by StevenPuttemans** [comment]
There is non for this task, retraining is the only option you have.

**Comment by melzoghbi** [comment]
Thanks @StevenPuttemans. Will do.
