### ISSUE TITLE
Unable to use gstreamer videowriter

### ISSUE THREAD

**Issue by jmckisson** [opencv/opencv#8859]
System information (version)

OpenCV => 3.2
Operating System / Platform => Mac OS 10.12.5
Compiler => g++
Wrapper => Java/C++

It is impossible to instantiate a cvCreateVideoWriter_GStreamer because TRY_OPEN detects that a writer has already been created by ffmpeg (or possibly other cap).    FFMpeg jsut creates a file with the name of my gstreamer pipeline construction..

My call to VideoWriter():
writer.open("appsrc ! autovideoconvert ! vtenc_h264 ! h264parse ! mpegtsmux ! rtpmp2tpay ! udpsink host=127.0.0.1 port=5000", fourcc, capture.get(Videoio.CAP_PROP_FPS), frameSize);

I can temporarily fix the issue by moing the HAVE_GSTREAMER check above ffmpeg, but I supose the real fix would be to have ffmpeg fail if it thinks that it should not be a valid file.

**Comment by alalek** [comment]
We need ctor overload with `apiPreference` parameter for `VideoWriter` (like similar addon for [`VideoCapture`](http://docs.opencv.org/master/d8/dfe/classcv_1_1VideoCapture.html#a85b55cf6a4a50451367ba96b65218ba1)).

Suggested interface:
```
    CV_WRAP VideoWriter(int apiPreference, const String& filename, int fourcc, double fps,
                Size frameSize, bool isColor = true);
```
