### ISSUE TITLE
OpenCV Error: Incorrect size of input array () in cvGetSubRect -> opencv_createsamples

### ISSUE THREAD

**Issue by wucop** [opencv/opencv#8861]
##### Detailed description

Calling opencv_createsamples causes an error when trying to create samples from one image:

`OpenCV Error: Incorrect size of input array () in cvGetSubRect, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\array.cpp, line 1275`

This error does not occur reproducible while processing a certain image. Instead sometimes the complete processing is successful and sometimes it breaks after few images.

Inside the attached .zip is a complete subset I used for creating the samples including the error log and images. 

My guess is that the error occures in utility.cpp, line ~1382. Could be that the distorted image exceeds the array? Anyhow it seems like the error does not occur when I set also -maxscale to 1.

##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit

##### Steps to reproduce

Unzip the attachment and call opencv_createsamples like it is done in error_output.txt. 

##### File
[error.zip](https://github.com/opencv/opencv/files/1056240/error.zip)

**Comment by wucop** [comment]
Made some tests with Version 2.4.13 and creating the samples is working without any problem.

[Overview about changes in utility.cpp since this version](https://github.com/opencv/opencv/commits/master/apps/createsamples/utility.cpp) 

Seems like commit [bbafaec](https://github.com/opencv/opencv/commit/b973b73ae749e376879cf72d815cb2e9604744e1#diff-20d6ceed31aa8899f78255725b9fd336) or [b973b73](https://github.com/opencv/opencv/commit/bb8faec885a87836b94d5d7c3ea52c11fd380c9e#diff-20d6ceed31aa8899f78255725b9fd336) is the problematic one.

**Comment by smaresca** [comment]
@wucop +1 seems reasonable. Same behavior here, and I had made a guess that it was due to randomization.

**Comment by alalek** [comment]
Can't reproduce: createsamples tool works with provided data. Tested with OpenCV master (3.3-rc) and OpenCV 3.2.0 on Linux (with fixed slashes `\` => `/`).

BTW, There a problem in command line near `-maxzangle` option (missing space before):
> D:\Workspaces\plain\opencv3>D:\Programme\opencv\build\x64\vc14\bin\opencv_createsamples.exe -img pos_samples\AAXX0815.jpg -bg bg.info -info AAXX0815.info -num 100 -maxxangle 0.17 -maxyangle 1.02-maxzangle 0.08 -bgcolor 100 -bgthresh 0 -maxidev 100 -w 110 -h 24
