### ISSUE TITLE
Error on importing cv2 after source activate tensorflow

### ISSUE THREAD

**Issue by vertika-19** [opencv/opencv#8871]
I have tried following steps - 

conda install -c menpo opencv=2.4.11
error check conda info opencv

conda install -c menpo opencv=3.2.0
error similar as above

conda install -c menpo opencv3=3.1.0

this installed but again on trying to import cv2 error No module named 'cv2'

I tried finding path for opencv.pc
(tensorflow) vertika@vertika-HP-Notebook:$ sudo find / -type f -name "opencv.pc"

[sudo] password for vertika: 
find: ‘/run/user/1000/gvfs’: Permission denied
/home/vertika/anaconda3/pkgs/opencv3-3.1.0-py36_0/lib/pkgconfig/opencv.pc
/home/vertika/anaconda3/lib/pkgconfig/opencv.pc

if i run python in  normal terminal 
vertika@vertika-HP-Notebook:~$ python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 

It Runs

if I first do source activate tensorflow
vertika@vertika-HP-Notebook:~$  source activate tensorflow
( tensorflow ) vertika@vertika-HP-Notebook: ~ $ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'

I tried
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH=/home/vertika/anaconda3/pkgs/opencv3-3.1.0-py36_0/lib/pkgconfig
export PKG_CONFIG_PATH=/home/vertika/anaconda3/lib/pkgconfig

Again tried 

2 )   conda install opencv

Similar problem

Tried all this but once tensorflow is activated it doesn't works

Details
python --version
Python 3.6.0 :: Anaconda custom (64-bit)

vertika@vertika-HP-Notebook:~$ sudo find / -type f -name "opencv.pc"
[sudo] password for vertika: 
find: ‘/run/user/1000/gvfs’: Permission denied
/home/vertika/anaconda3/pkgs/opencv3-3.1.0-py36_0/lib/pkgconfig/opencv.pc
/home/vertika/anaconda3/pkgs/opencv-3.1.0-np112py36_1/lib/pkgconfig/opencv.pc
/home/vertika/anaconda3/lib/pkgconfig/opencv.pc

**Comment by alalek** [comment]
> export PKG_CONFIG_PATH
Python doesn't use it. Try `PYTHONPATH` instead. Path to opencv.pc is useless too, you need path to Python module (something like cv2.cpython-36m.so, check via `import cv2; print(cv2.__file__)` via conda environment).

Also you have different versions of Python for conda and tensorflow:
> Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)
> Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23)

Such configurations are not tested well and may not work at all (crash/segfault).

**Comment by mmehmetaliyavuz** [comment]
Did you solve this problem ?
