### ISSUE TITLE
Build problems on the raspberry pi 3 : make: *** [all] Error 2

### ISSUE THREAD

**Issue by dnick971** [opencv/opencv#8878]
##### System information (version)

- OpenCV => 3.2 (git clone of the master branch)
- Operating System / Platform => last raspbian Raspbian release (on the raspberry pi 3)
- Compiler => gcc

##### Detailed description

I am trying to build opencv on the raspberry pi 3. The build process stops with : 

[ 19%] Linking CXX static library ../lib/libIlmImf.a
[ 19%] Built target IlmImf
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

##### Steps to reproduce

git clone https://github.com/opencv/opencv
cd open cv
mkdir release
cd release
cmake -DINSTALL_C_EXAMPLES=ON -DINSTALL_PYTHON_EXAMPLES=ON -DBUILD_EXAMPLES=ON -DBUILD_PYTHON_SUPPORT=ON -DWITH_TBB=ON -DBUILD_TBB=ON -DPYTHON3_EXECUTABLE=/usr/local/bin/python3.6 -DPYTHON3_INCLUDE=/usr/local/include/python3.6m -DPYTHON3_LIBRARY=/usr/local/lib/libpython3.6m.a -DPYTHON3_PACKAGES_PATH=/usr/local/lib/python3.6/site-packages/ -DPYTHON3_NUMPY_INCLUDE_DIR=/usr/local/local/python3.6/dist-packages/numpy-1.13.0rc2-py3.6-linux-armv7l.egg/numpy/core/include ..
make -j4

[CMakeError.txt](https://github.com/opencv/opencv/files/1063707/CMakeError.txt)
[cmakereturn.txt](https://github.com/opencv/opencv/files/1063719/cmakereturn.txt)

**Comment by dnick971** [comment]
I reinstalled raspbian. I decided to stick with the raspbain default python 3 version : 3.4

I installed those librairies : 
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng12-dev libtiff-dev libjasper-dev libdc1394-22-dev

i installed numpy on python 2 and 3.4 with easy_install

After 2 incomplete build i installed : 
sudo apt-get install libwebp-dev libilmbase-dev libopenexr-dev

In the ~/opencv/release dir i did :
cmake -DINSTALL_C_EXAMPLES=ON -DINSTALL_PYTHON_EXAMPLES=ON -DBUILD_EXAMPLES=ON -DBUILD_PYTHON_SUPPORT=ON -DWITH_TBB=ON -DBUILD_TBB=ON ..
make -j4

Here are the error log
[make_output.txt](https://github.com/opencv/opencv/files/1066466/make_output.txt)
[CMakeError2.txt](https://github.com/opencv/opencv/files/1066463/CMakeError2.txt)
[CMakeOutput2.txt](https://github.com/opencv/opencv/files/1066464/CMakeOutput2.txt)

The embedded 3rd party sources seem to cause problems.

**Comment by alalek** [comment]
Try `-DWITH_TBB=OFF` or `-DENABLE_PRECOMPILED_HEADERS=OFF`.

**Comment by dnick971** [comment]
Without tbb would i be able to take advantage of the 4 cores of the pi3 64bit processor ?

**Comment by alalek** [comment]
OpenCV 3.x supports pthreads as `parallel_for` backend. No special dependencies are required.

**Comment by dnick971** [comment]
I tried with -DWITH_TBB=OFF and the build process complete.

**Comment by abhiTronix** [comment]
@dnick971 https://github.com/abhiTronix/TBB_Raspberry_pi Solution .

**Comment by fnoop** [comment]
^^ Warning, this abhiTronix guy is trying to sell his precompiled binaries and is not making them publicly available.  Avoid like the plague.

**Comment by abhiTronix** [comment]
!!! https://github.com/goodrobots/maverick/issues/233

**Comment by dnick971** [comment]
So the extra steps i presented are still relevant ?

**Comment by abhiTronix** [comment]
@dnick971 yes, Once you successfully installed TBB on your Raspberry pi, you can then will able to compile OpenCV with `-DWITH_TBB=ON` i.e. with full TBB support . As shown in my git https://github.com/abhiTronix/OpenCV_Raspberry_pi_TBB and able to take advantage of the 4 cores of the Rpi3 64bit processor as you said.

**Comment by dahik** [comment]
i got error [module/videoio/cmakefiles/opencv_videoio.dir/build.make:115 : modules/videiio/cmakefiles/opencv_videoio]
