### ISSUE TITLE
ROI capture from Desktop Screen 

### ISSUE THREAD

**Issue by gonsalves2003** [opencv/opencv#8881]
I am using Visual Studio 2017 C# and am trying to capture a portion of my screen and I already have a transparent form from which I am able to capture the desktop area using OpenCVSharp Rect. The system detects only Mat and not IpImage. Not able to figure out how to capture the image from the Rectangle area selected (ROI)

Please help since I am working on this for last 4 days...

**Comment by alalek** [comment]
OpenCV team doesn't support C# bindings (OpenCV itself is C++ library), so we can't help you here.

**Comment by gonsalves2003** [comment]
Can you guide me with the method/Class in C++ that performs the same task?

**Comment by alalek** [comment]
> capture a portion of my screen

This is no such direct functionality for this in OpenCV.
OpenCV has support for some Video I/O backends via VideoCapture interface (ffmpeg, gstreamer, MSMF, dshow, Video for Windows, etc), but they are wrote/tested for camera support at first.
