### ISSUE TITLE
Bad results on stitching

### ISSUE THREAD

**Issue by lizzzcai** [opencv/opencv#8884]
Dear all,
I found that my results of stitching are quite different from others, the stitching code are actually come from the example, however, I found that the results are quite bad, I can obtain the good results from my ubuntu virtual system. 
Anyone has idea about what happens on my system, I have reinstalled the opencv what it still looks like this.

##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit win7
- Compiler => Visual Studio 2013

The results are shown below
![26919862-abb1ee6a-4c69-11e7-80c0-2a1ebeb3b18e](https://user-images.githubusercontent.com/22748546/27000896-8aaa3a98-4dee-11e7-9575-c71e48f1104d.jpg)
![26914240-c3b0e5be-4c52-11e7-9e81-2633d4cc9d85](https://user-images.githubusercontent.com/22748546/27000898-8c432126-4dee-11e7-8c4e-33e108b548c5.jpg)

**Comment by alalek** [comment]
1. Try `imread` + `imshow` for single image. Check results.
2. Try to disable OpenCL: CMake `WITH_OPENCL=OFF` or environment `OPENCV_OPENCL_DEVICE=disabled`

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
