### ISSUE TITLE
learn opencv source code

### ISSUE THREAD

**Issue by ranjiewwen** [opencv/opencv#8893]
hello , i am a student research in computer vision. i have learned the opencv library , use some algorithm to solve practical project. Now i want to learn the source code. but it is too big , i want to build it again in VS2-13, it cause too many problem.  i really want to learn more ,and find some bug ,contribute in github. so eveybody have some adavice to me? and help me learn the source code more easy! thanks!

**Comment by StevenPuttemans** [comment]
Start with

- https://github.com/opencv/opencv/wiki/How_to_contribute
- Finding [easy](https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy) or [documentation](https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3A%22category%3A+documentation%22) bugfixes and try to solve those, they are usually quite easy and help you to get the hang of the process

**Comment by csukuangfj** [comment]
The core module is maybe a good start, for instance, the basic data structures used in OpenCV
 - cv::Mat
 - cv::InputArray, cv::OutputArray
 - ...
and the operations defined on them.

-----
OpenCV is just a tool. The things behind it is more interesting.
