### ISSUE TITLE
Some XML cascade file have comments which violate XML syntax

### ISSUE THREAD

**Issue by gsmith-to** [opencv/opencv#8894]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => n/a
- Compiler => n/a

##### Detailed description
Several of the cascade.xml files (e.g. data/haarcascades/haarcascade_frontalcatface.xml)
contain improper XML comments in the header:

&lt;!--------------------------------
...
----------------------------------&gt;

This does not cause problems when reading the data using OpenCV, but other readers (e.g. Python ElementTree) will not read these files. This is easily fixed by changing the lines to &lt;!-- and --&gt;.

XML comments start with &lt;!-- and end with --&gt;
The text in between must be at least one character, may not end in a hyphen, and may not contain two consecutive hyphens.

See https://www.w3.org/TR/REC-xml/#sec-comments

[ Some informal references miss this detail -- e.g. https://www.tutorialspoint.com/xml/xml_comments.htm ; not only fails to mention this, actually gives examples which violate it. ]

**Comment by StevenPuttemans** [comment]
@gsmith-to are you up to providing a PR with a suggested fix for this issue?

**Comment by gsmith-to** [comment]
Almost done, but I did it all on github web edits and one of my commits has a bad log message. Is there a way to amend this on the web site, or is it even an issue?

https://github.com/gsmith-to/opencv/commit/2656f76c55db972ec594d2aff6e1da70a60b47b9

**Comment by StevenPuttemans** [comment]
@gsmith-to to me it seems better to do it to all models at once. I will cherry pick your results on a new commit and submit a new PR with fixed message.
