### ISSUE TITLE
Checkinstall on debian9/armhf throws: make: *** [cmake_check_build_system] Segmentation fault

### ISSUE THREAD

**Issue by xanview** [opencv/opencv#8897]
##### System information (version)
- OpenCV => tried 3.2.0, 3.3.0 and latest git master 
- Operating System / Platform => Debian 9 (Stretch)
- Platform => Raspberry Pi 3 (armhf)
- Compiler => cmake 3.7.2-1

##### Detailed description

When I try to build an opencv package with checkinstall, it segment faults:
```
# checkinstall --default --backup=no --deldoc=yes --install=yes --pkgname=opencv --pkgversion='999:20170612-git'


checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.



*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ root@DietPi ]
1 -  Summary: [ Package created with checkinstall 1.6.2 ]
2 -  Name:    [ opencv ]
3 -  Version: [ 999:20170612-git ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ armhf ]
8 -  Source location: [ build ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ opencv ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue: 

Installing with make install...

========================= Installation results ===========================
Makefile:2246: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Segmentation fault

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.
```

This is strange because make install runs without issues: [make_install.txt](https://github.com/opencv/opencv/files/1067433/make_install.txt)

##### Steps to reproduce

I'm compiling openCV like this:
```
$ sudo rm CMakeCache.txt
$ sudo mkdir build
$ cd build
$ sudo cmake -DBUILD_opencv_java=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_NEW_PYTHON_SUPPORT=ON ..
$ sudo make -j3
$ sudo checkinstall --default --backup=no --deldoc=yes --install=yes --pkgname=opencv --pkgversion='999:20170612-git'
```

Any ideas?

**Comment by akashjobanputra** [comment]
Encountered the same error during `checkinstall`, for OpenCV 3.3.0

**Comment by thebeetleuk** [comment]
I have this also when installing ROS http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Indigo%20on%20Raspberry%20Pi
sudo checkinstall make install thros the error below:
```

========================= Installation results ===========================
Makefile:180: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Segmentation fault

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.
```

**Comment by akashjobanputra** [comment]
@thebeetleuk How does that error of ROS installation relevant on the opencv repo ?

**Comment by thebeetleuk** [comment]
good point. its not :) Fixed my issue now I think :)

**Comment by lupusorina** [comment]
I am encountering the same problem with ROS. How did you solve it @thebeetleuk ?

**Comment by thebeetleuk** [comment]
@lupusorina the issue turned out to be the fact I was installing on the latest Pi image "STRETCH" instead of "Jessie". Jessie seemed to work fine.

**Comment by giuliomoro** [comment]
This is a bug in `installwatch`, a component of `checkinstall`. I raised it [here](https://bugtrack.izto.org:4442/show_bug.cgi?id=171) 
and fixed it [here](https://github.com/giuliomoro/checkinstall/commit/57ad1473bdfc5aadd2c921d6990e069809f442d4). You can easily build `checkinstall` from source and use it to replace your existing installation:

```
git clone https://github.com/giuliomoro/checkinstall
cd checkinstall
make install
```
Check now that the date of `/usr/lib/checkinstall/installwatch.so` has been updated and you will have the confirmation that the library has been updated.

**Comment by rgaufman** [comment]
This still happens in Raspbian 10 (buster), installing the latest version of checkinstall indeed fixes it :)

**Comment by jiapei100** [comment]
I believe it has **NOTHING** to do with OpenCV, but **checkinstall**'s own problem...

**Comment by sebma** [comment]
@giuliomoro Hi,

> This is a bug in `installwatch`, a component of `checkinstall`. I raised it [here](https://bugtrack.izto.org:4442/show_bug.cgi?id=171)
> and fixed it [here](https://github.com/giuliomoro/checkinstall/commit/57ad1473bdfc5aadd2c921d6990e069809f442d4). You can easily build `checkinstall` from source and use it to replace your existing installation:

Your link on bugtrack link is dead and the bugtrack links on http://checkinstall.izto.org are also dead (HTTP ERROR 404).

Can you please update those links.
