### ISSUE TITLE
Unable to read video file with OpenCV 3.2.0/3.1.0

### ISSUE THREAD

**Issue by zhuoc** [opencv/opencv#8902]
##### System information (version)
- OpenCV => 3.2.0/3.1.0
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc

##### Detailed description

 I have just installed OpenCV 3.2.0 on Ubuntu 16.04. When I'm trying to read from a video file, I got the error:

Failed to query video capabilities: Inappropriate ioctl for device
libv4l2: error getting capabilities: Inappropriate ioctl for device
ERROR: V4L: device /path/to/my/video/768x576.avi: Unable to query number of channels

Specifically, I was trying to run the tracker sample code at
https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/samples/tracker.py

I have also tried using version 3.1.0, or the latest version from Github, but didn't help.

I have installed libv4l2, and when doing cmake, I had the flag set with -D WITH_LIBV4L=ON.

Could someone help me out?

##### Steps to reproduce

Just do something like
python tracker.py (or anything that involves read of video file)

**Comment by alalek** [comment]
> V4L: device /path/to/my/video/768x576.avi

V4L (Video for Linux) is API for camera devices. It doesn't process files (except special "device" files like `/dev/video0`, `/dev/video1`, etc).

You need to build OpenCV with FFMPEG or GStreamer backend to open video files.

**Comment by Adeelyousaf** [comment]
I am having some issue.. So its resolved or not?
