### ISSUE TITLE
Cannot use algorithm KDTree in KNearest

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8917]
Opencv-3.2-dev
VC 2015 windows 10

Hi,
In example https://github.com/opencv/opencv/blob/master/samples/cpp/points_classifier.cpp i ahve insert line after [line ](https://github.com/opencv/opencv/blob/master/samples/cpp/points_classifier.cpp#L118): 
   knn->setAlgorithmType(KNearest::KDTREE);

then I have got an assertion : 

> OpenCV Error: Assertion failed (std::abs(more - less) <= 1) in cv::ml::medianPartition, file G:\Lib\opencv\modules\ml\src\kdtree.cpp, line 134

I think it is same issue in https://github.com/opencv/opencv/issues/4886

**Comment by ereator** [comment]
I have the same bug. 
pKNN->setAlgorithmType(ml::KNearest::BRUTE_FORCE) works, but not the k-D Tree

**Comment by tjom** [comment]
This might be caused by issue #11450

Try calling `knn->setAlgorithmType(KNearest::KDTREE);` right after the line `Ptr<KNearest> knn = KNearest::create();`

**Comment by berak** [comment]
@LaurentBerger , i found, that the sample code is producing duplicate points (at the same location), and that the kdtree then cannot find a median for identical points.

**Comment by LaurentBerger** [comment]
Yes something is wrong with kdtrees
![capture](https://user-images.githubusercontent.com/3591626/39958139-f2e4e6a8-55fe-11e8-89b4-0695b6a3ec87.JPG)
