### ISSUE TITLE
OpenCV: FFMPEG: tag 0x30385056/'VP80' is not supported with codec id 140 and format 'webm / WebM'

### ISSUE THREAD

**Issue by chandansunahar** [opencv/opencv#8919]
Please help me

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

Dear All,
my intention to record the desktop using opencv and i am using vp8 codec and saving video in extension(.webm)
self.fourcc = cv.VideoWriter_fourcc('V', 'P', '8', '0')
        self.vid = cv.VideoWriter(self.file_name,self.fourcc,21,(GetSystemMetrics(0),GetSystemMetrics(1)))
Videosaving:
newfile=os.path.join(os.getcwd(),path1)+"\\"+now+".webm"
Note:It is creating video in .webm format and also i can play the video
But i am getting one warning message 
OpenCV: FFMPEG: tag 0x30385056/'VP80' is not supported with codec id 140 and format 'webm / WebM'

**Comment by vadimk2016** [comment]
Same warning after 3 years :
`OpenCV: FFMPEG: tag 0x30385056/'VP80' is not supported with codec id 139 and format 'webm / WebM'`

**Comment by cartovarc** [comment]
OpenCV: FFMPEG: tag 0x30387076/'vp80' is not supported with codec id 139 and format 'webm / WebM'

**Comment by Mavnus04** [comment]
I see this is marked as won't fix, but I was wondering why?  I am now getting a similar message:

OpenCV: FFMPEG: tag 0x38305056/'VP08' is not supported with codec id 139 and format 'webm / WebM'

**Comment by maingoh** [comment]
Is it not because VP8 and VP9 are not in this file https://github.com/opencv/opencv/blob/master/modules/videoio/src/ffmpeg_codecs.hpp ?

This function seem to fail https://github.com/opencv/opencv/blob/ceb94d52a104c0c1287a43dfa6ba72705fb78ac1/modules/videoio/src/cap_ffmpeg_impl.hpp#L2556

**Comment by CAReeser** [comment]
why isn't this fixed? still get this error.
OpenCV: FFMPEG: tag 0x30387076/'vp80' is not supported with codec id 139 and format 'webm / WebM'

What issue does it cause? The video is produced, but I don't know if there are left over memory segments, etc.  Could this be one of the causes of memory leaks in cv2?

**Comment by Hereux** [comment]
What the fuck, why is no one interested in fixing this trash and just ignoring everything???
OpenCV: FFMPEG: tag 0x30395056/'VP90' is not supported with codec id 167 and format 'webm / WebM'

**Comment by ingale726** [comment]
I also want to know why not fix it

**Comment by jiliangqian** [comment]
I also want to know why not fix it

**Comment by pereira-larissa** [comment]
I also want to know why
