### ISSUE TITLE
resize using INTER_AREA fails on raspberry pi zero with illegal instruction

### ISSUE THREAD

**Issue by percy9427** [opencv/opencv#8929]
##### System information (version)
<
- OpenCV => 3.2.0
- Operating System / Platform => Raspian Jessie (4/10 version)
- Compiler => cmake
- Python version 3.4.2
- Hardware Pi Zero W
-->

##### Detailed description

The following resize operation fails with illegal instruction.
- It works fine on a Pi2 or Pi3, but fails on a Pi Zero or Pi1 (I am trying to use a zero for the small form factor)
- OpenCV was compiled from scratch on the target machine using instructions from PyImageSearch.  It was done on the target machines.
- All other opencv, numpy, and scipy functions perform correctly and I used a lot of them since the sum of the vision processing code is about 3000 lines long.
- It fails on a resize using INTER_AREA, but succeeds when using INTER_NEAREST, INTER_LINEAR, INTER_CUBIC (I am trying to reduce an image)

**Comment by alalek** [comment]
> fails with illegal instruction

Stack trace and disassembled code are required.
