### ISSUE TITLE
mac can't install openvc

### ISSUE THREAD

**Issue by orange-jacky** [opencv/opencv#8930]
macbookpro:albums fredlee$ brew tap homebrew/science
Warning: Tap homebrew/science already tapped.
macbookpro:albums fredlee$ brew install opencv
Error: undefined method `rebuild' for #<BottleSpecification:0x007fc0348bba18>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:11:in `block in <class:Opencv>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1717:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:10:in `<class:Opencv>'
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:85:in `<main>'
macbookpro:albums fredlee$ 

I wanna to know how to install it sucuessfully, and how to choose version of openvc

**Comment by alalek** [comment]
> Homebrew

There is not official support for Homebrew here.
You should Homebrew issue tracker instead.
