### ISSUE TITLE
OpenCV 3 simple VideoCapture and waitKey crashes after a while on Mac

### ISSUE THREAD

**Issue by ahundt** [opencv/opencv#8931]
OpenCV 3.1.0 is installed through brew install opencv3 --with-contirb --with-qt5 and the following program crashes after a while:

```c++
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/videoio.hpp>

int main(int argc, const char * argv[]) {
    cv::VideoCapture cap(0);
    cv::Mat frame;
    while (cap.read(frame)) {
        imshow("Frame", frame);
        if (cv::waitKey(1) == 'q') {
            break;
        }
    }
    return 0;
}
```

While #5874 appeared to fix this at first, subsequent testing has shown this bug is still actively occurring. I've created this new, open issue to increase visibility of the problem.

**Comment by ahundt** [comment]
@jkearse3 what version of openCV were you trying?

**Comment by mshabunin** [comment]
Version 3.1 is quite outdated, could you please check if the problem persists in 3.2.0 or latest master?

**Comment by ahundt** [comment]
I couldn't reproduce the issue on the latest release.

@ShangxuanWu what version of OpenCV are you on? They recently said the problem exists at https://github.com/opencv/opencv/issues/5874#issuecomment-314916044.

**Comment by CoreRobotics** [comment]
I still have this issue with OpenCV 3.4.0, C++, Mac OS 10.12.6.  I am running the video capture loop in a separate thread (using pthread).  Installed with brew.

Immediately throws the following exception.  Looks like the 'nextEventMatchingMask' needs to be attached to the main thread.  This issue goes away when I remove the waitKey(0), but I need the viewer window.  Can someone confirm this is the same issue?

2018-01-11 14:57:30.541 Experiment[43843:5055832] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9833d2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffad15348d objc_exception_throw + 48
	2   AppKit                              0x00007fff96526e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
	3   libopencv_highgui.3.4.dylib         0x0000000109307c0a cvWaitKey + 351
	4   libopencv_highgui.3.4.dylib         0x00000001093032e5 _ZN2cv9waitKeyExEi + 34
	5   libopencv_highgui.3.4.dylib         0x000000010930334b _ZN2cv7waitKeyEi + 34
	6   Experiment                          0x00000001075b412c _Z12updateVisionv + 8668
	7   Experiment                          0x0000000107843a88 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvvEEEEEEPvSA_ + 40
	8   libsystem_pthread.dylib             0x00007fffadc5293b _pthread_body + 180
	9   libsystem_pthread.dylib             0x00007fffadc52887 _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fffadc5208d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by alalek** [comment]
@CoreRobotics 

> from the Main Thread

That is. This is the limitation of UI threads on Mac OS and many others platforms.


> I couldn't reproduce the issue on the latest release.

Closing this.

**Comment by alalek** [comment]
You [state](https://github.com/opencv/opencv/issues/8931#issuecomment-317672933) that you don't see this problem on the latest release - so there is nothing to fix on 3.x(master) branch anymore. For exact commit number feel free to run "git bisect" process.

@CoreRobotics comment is not related to original issue at all (UI interaction from non-main thread is prohibited by platform - this is known limitation and would not be fixed) and this comment will be removed from this thread.
