### ISSUE TITLE
how to install opencv3.1/3.2 on ubuntu16.04, cuda8, titanX, anaconda2? 

### ISSUE THREAD

**Issue by IvyGongoogle** [opencv/opencv#8933]
hello, when I make opencv3.1, I encounter some problems:

```
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/core.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/arithm.cpp.o
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/reductions.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/element_operations.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Linking CXX static library ../../lib/libopencv_cudaarithm.a
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Built target opencv_cudaarithm
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2 
```

what causes this error? how to fix it ? My environment is  `ubuntu16.04, cuda8, titanX, anaconda2`.
Can someone provide some advises?
thank you very much.

**Comment by rohitmulay** [comment]
You can try my procedure to install OpenCV 3.2 on Ubuntu 16.04
https://github.com/rohitmulay/opencv

**Comment by IvyGongoogle** [comment]
@rohitmulay hello, thank for your instruction. But I get some problems. When I run `bash  opencv.sh`. Finally, it shows:

```
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:50 (_qt5_Gui_check_file_exists)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:72 (_qt5gui_find_extra_libs)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:158 (include)
  cmake/OpenCVFindLibsGUI.cmake:19 (find_package)
  CMakeLists.txt:556 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ztgong/softwares/opencvdrive/OpenCV/opencv-3.2.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/ztgong/softwares/opencvdrive/OpenCV/opencv-3.2.0/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
***********************************
make: *** No rule to make target 'install'.  Stop.
***********************************
***********************************
OpenCV 3.2.0 ready to be used
```

And when I run `pkg-config --cflags opencv`, it shows "-I/usr/include/opencv" rather than  `-I/usr/local/include/opencv -I/usr/local/include`.
Besides running `pkg-config --cflags opencv`, it shows "/usr/lib/x86_64-linux-gnu/libopencv_calib3d.so -lopencv_calib3d /usr/lib/x86_64-linux-gnu/libopencv_contrib.so -lopencv_contrib /usr/lib/x86_64-linux-gnu/libopencv_core.so -lopencv_core /usr/lib/x86_64-linux-gnu/libopencv_features2d.so -lopencv_features2d /usr/lib/x86_64-linux-gnu/libopencv_flann.so -lopencv_flann /usr/lib/x86_64-linux-gnu/libopencv_gpu.so -lopencv_gpu /usr/lib/x86_64-linux-gnu/libopencv_highgui.so -lopencv_highgui /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so -lopencv_imgproc /usr/lib/x86_64-linux-gnu/libopencv_legacy.so -lopencv_legacy /usr/lib/x86_64-linux-gnu/libopencv_ml.so -lopencv_ml /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so -lopencv_objdetect /usr/lib/x86_64-linux-gnu/libopencv_ocl.so -lopencv_ocl /usr/lib/x86_64-linux-gnu/libopencv_photo.so -lopencv_photo /usr/lib/x86_64-linux-gnu/libopencv_stitching.so -lopencv_stitching /usr/lib/x86_64-linux-gnu/libopencv_superres.so -lopencv_superres /usr/lib/x86_64-linux-gnu/libopencv_ts.so -lopencv_ts /usr/lib/x86_64-linux-gnu/libopencv_video.so -lopencv_video /usr/lib/x86_64-linux-gnu/libopencv_videostab.so -lopencv_videostab" rather than "-L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core ".

So didn't I succeed for compiling OpenCV 3.2?

**Comment by ywpkwon** [comment]
Same problem here. Ubuntu 16.04, Titan X, Cuda 8.0, virtualenv, NVIDIA driver 367.57.

**Comment by ChoclateRain** [comment]
@IvyGongoogle Im getting the same error
ubuntu 16.04,cuda 8,1080 ti
