### ISSUE TITLE
std::vector<cv::Point2f> getMat crash

### ISSUE THREAD

**Issue by acajic** [opencv/opencv#8935]
This problem was originally posted on StackOverflow [here](https://stackoverflow.com/questions/43894642/opencv-stdvector-for-cvmat-arguments).

Executing this:

```
std::vector<cv::Point2f> pts; // contains 4 elements
cv::Mat ptsMat = ((cv::InputArray)pts).getMat();
```
On one machine I get a 4-by-1 cv::Mat with 2 channels. Each element represents a 2D point. On another machine, I get a 2090-by-1 cv::Mat with 2 channels with weird data.

On both machines using OpenCV 3.1 built from source using CMake on Windows 10.

On yet another machine in Visual Studio in `Debug` mode the following snippet works fine:
```
std::vector<cv::Point2f> points = { cv::Point2f(2, 1), cv::Point2f(2, 1), cv::Point2f(1, 3) };
cv::InputArray arr = points;
cv::Mat ma = arr.getMat();
std::cout << ma.ptr<float>(0)[1];
```
But when I compile it in `Release`, it crashes on the last line with _Access violation reading location_...

Further investigation revealed that the key flag that makes a difference is: 
```
Runtime library: Multithreaded DLL (/MD) --------> crash 
Runtime library: Multithreaded Debug DLL (/MDd) --------> works
```

Problem manifests similarly on OpenCV 3.2. Instead of crash I get the matrix with ~2090 columns and 2 rows.

The reason why this is problem is that there are a lot of higher functions that use this `getMat()` function. For example, `undistortPoints()`.

Same code seems to work well on Linux systems.

**Comment by mshabunin** [comment]
I've not been able to reproduce this issue on Win10 with VS2015 and latest OpenCV version from _master_ branch:

Snippet:

    std::vector<cv::Point2f> points = { cv::Point2f(2, 1), cv::Point2f(2, 1), cv::Point2f(1, 3) };
    cv::InputArray arr = points;
    cout << arr.size() << ", " << arr.depth() << ", " << arr.channels() << endl;
    cv::Mat ma = arr.getMat();
    cout << ma.size() << ", " << ma.depth() << ", " << ma.channels() << endl;
    std::cout << ma.ptr<float>(0)[1];

Output:
```
[3 x 1], 5, 2
[3 x 1], 5, 2
1
```

**Comment by alalek** [comment]
#9161
