### ISSUE TITLE
pip3.6 install opencv not working

### ISSUE THREAD

**Issue by szg0000** [opencv/opencv#8937]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

`"pip3.6 install opencv"` gives back error message:
`No matching distribution found for opencv`

##### Steps to reproduce

type to a root shell under debian:
pip3.6 install opencv

<!-- to add code example fence it with triple backticks and optional file extension
    ``.cpp
    // C++ code example
    ```
 or attach as .txt or .zip file
-->

**Comment by alalek** [comment]
Distribution via "pip" is not supported.
