### ISSUE TITLE
Random crash with Opencv 3.2 using java Api for face and eye detection

### ISSUE THREAD

**Issue by osmadja** [opencv/opencv#8948]
- OpenCV => 3.2.0
- Using Java API
- Operating System / Platform => MacOsX 10.12.4
- Compiler => XCODE Version 8.3.2 (8E2002)

##### Detailed description

I'm using the opencv 3 java api to implement face and eye detection. It works but after a while the system crashes with a core dump:

```
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x0000000131e48889, pid=89735, tid=93187

JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode bsd-amd64 compressed oops)
Problematic frame:
**C  [libopencv_core.3.2.dylib+0xea889]  cv::_InputArray::size(int) const+0x62f**


Attached the error log generated by the JVM : hs_err_pid89735.txt
```

The frequency of the crash seems to be random, sometime it work for an hour without any problem, sometime it crashed after 20s seconds

##### Steps to reproduce

Here is the sample code. If needed I can upload a full eclipse project.

```.java
protected void startCamera() {

		// start the video capture
		this.capture.open(0);

		boolean b1 = this.capture.set(Videoio.CAP_PROP_FRAME_WIDTH, 320);
		boolean b2 = this.capture.set(Videoio.CAP_PROP_FRAME_HEIGHT, 240);
		
		logger.info("Camera resolution width is "+ this.capture.get(Videoio.CAP_PROP_FRAME_WIDTH)+ " | changed is ok : "+ b1);
		logger.info("Camera resolution height is "+ this.capture.get(Videoio.CAP_PROP_FRAME_HEIGHT)+ " | changed is ok : "+ b2);
		// this.capture.set(Videoio.CV_CAP_PROP_FRAME_HEIGHT, 288);

		// is the video stream available?
		if (this.capture.isOpened()) {
			this.cameraActive = true;

			final FaceDetector fd = this;

			// grab a frame every 33 ms (30 frames/sec)
			Runnable frameGrabber = new Runnable() {

				@Override
				public void run() {
					nbFrames++;
					// effectively grab and process a single frame
					Mat frame = grabFrame();
					// convert and show the frame
					BufferedImage imageToShow = matToBufferedImage(frame);
					if (imageCapture != null) {
						imageCapture.newImage(imageToShow);
						imageWidth = imageToShow.getWidth();
						imageHeight = imageToShow.getHeight();
						//System.out.println("****** " + imageWidth+ " / "+ imageHeight);
					}
				}
			};

			this.timer = Executors.newSingleThreadScheduledExecutor();
			this.timer.scheduleAtFixedRate(frameGrabber, 0, 33, TimeUnit.MILLISECONDS);

		} else {
			// log the error
			System.err.println("Failed to open the camera connection...");
		}
	}


/**
	 * Get a frame from the opened video stream (if any)
	 * 
	 * @return the {@link Image} to show
	 */
	private Mat grabFrame() {
		Mat frame = new Mat();

		// check if the capture is open
		if (this.capture.isOpened()) {
			try {
				// read the current frame
				this.capture.read(frame);

				// if the frame is not empty, process it
				if (!frame.empty()) {
					// face detection
					this.detectAndDisplay(frame);
				}

			} catch (Exception e) {
				// log the (full) error
				logger.error("Exception during the image elaboration: ", e);
			}
		}

		return frame;
	}
```

**Comment by osmadja** [comment]
Here is the core dump lo file 
[hs_err_pid89735.txt](https://github.com/opencv/opencv/files/1089068/hs_err_pid89735.txt)

**Comment by SummerXia93** [comment]
Have you solved this problem? I have the same problem and have no idea how to fix it

**Comment by xiangyubo** [comment]
I have almost the same problem...

**Comment by alalek** [comment]
It is hard to investigate real problem without binaries with debug information.

> hs_err_pid89735.txt
> Memory: 4k page, physical 16777216k(159144k free)

Looks like system run out of memory - all 16GB is utilized.
JVM is not able to track memory usage of native objects. All `Mat` objects are just few bytes for Java (but with megabytes occupied).

You might try to:
- call `Mat.release()` for unused Java `Mat` objects (but you have no access for Mat objects of internal Java methods, or exceptions unrolling would skip that - something would be missed again)
- try to call `System.gc()` (every 1/10 frames, but it is not reliable by JVM specification)

See #4019 #7919 

---

Also there is strange exceptions:

> Event: 7971.467 Thread 0x00007f8b94a19000 Implicit null exception at 0x0000000110b9590b to 0x0000000110b95999
