### ISSUE TITLE
centos 7   compile opencv 3.2.0 error <sys/videoio.h> no such file or directory

### ISSUE THREAD

**Issue by liuyu5337** [opencv/opencv#8952]
the log messages as below:

Run Build Command:/usr/bin/gmake "cmTryCompileExec3846447246/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3846447246.dir/build.make CMakeFiles/cmTryCompileExec3846447246.dir/build
gmake[1]: enter directory “/home/zq/opencv-3.2.0/build/CMakeFiles/CMakeTmp”
/usr/bin/cmake -E cmake_progress_report /home/zq/opencv-3.2.0/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3846447246.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wm
issing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-l
ong -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden  -O3 -DNDEBUG   -o CMakeFiles/cmTryCompile
Exec3846447246.dir/CheckIncludeFile.c.o   -c /home/zq/opencv-3.2.0/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/zq/opencv-3.2.0/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:25: fetal error ：sys/videoio.h：no such file or directory
 #include <sys/videoio.h>

i'm confused by this error msg ,anyone tell me why?

**Comment by alalek** [comment]
This is just a configuration check result - not a error / bug / whatever. All configuration tools do many checks to detect current platform setup and available features/libraries/etc.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by liuyu5337** [comment]
@alalek  thanks! I know it's just a   configuration check result, but cmake can't compile completely. cmake was terminated by this error. how can i avoid this? 

thanks again!
