### ISSUE TITLE
can not read video using cv2.VideoCapture

### ISSUE THREAD

**Issue by IvyGongoogle** [opencv/opencv#8954]
hello, I have one code:
```
import cv2
cv2.VideoCapture(xxx.mp4/avi)
print vidcap.isOpened()
```
it still is False. I google for much time and rebuild ffmpeg and opencv. It they do not work.
anyone can give some advises?
thank you very much~~

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by IvyGongoogle** [comment]
@alalek sorry about that
