### ISSUE TITLE
MORPH_HITMISS with all zero kernels

### ISSUE THREAD

**Issue by eyaler** [opencv/opencv#8957]
I am running a morphological hit and miss with the kernel center element set to 0 (don't care):

`cv2.morphologyEx(np.asarray([[0, 255, 0], [0, 0, 0], [0, 255, 0]], dtype=np.uint8), cv2.MORPH_HITMISS, np.asarray([[0, 1, 0], [0, 0, 0], [0, 1, 0]], dtype=np.int8))
`
I am getting: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

While I am expecting to get: [[0, 0, 0], [0, 255, 0], [0, 0, 0]]

I think this is because:
`e2 = src;` 

should be:
e2 = `src_complement;`

edit:
i think for the all-zero cases e1 and/or e2 should get ones_like(src)*255

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by dan-masek** [comment]
Yep, seems wrong.

Culprit in master: https://github.com/opencv/opencv/blob/master/modules/imgproc/src/morph.cpp#L2060

IMHO a sufficient fix would be move lines 2064-2065 before the offending if, and then changing the assignment as eyaler points out: `e2 = src_complement;`

Culprit in 2.4 branch: https://github.com/opencv/opencv/blob/2.4/modules/imgproc/src/morph.cpp#L1425

Same deal.

**Comment by eyaler** [comment]
i think that for the cases where countNonZero<=0 we should take an all on pattern instead or src/~src. the idea is that if the kernel is all zeros we dont care and should short circuit the and operator
