### ISSUE TITLE
default border type different from docs

### ISSUE THREAD

**Issue by eyaler** [opencv/opencv#8964]
the default borderType for morphological transformation as erode,dilate,hitmiss seems to be BORDER_REPLICATE and not BORDER_CONSTANT as stated in docs

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by catree** [comment]
At least for [`erode()`](https://github.com/opencv/opencv/blob/3.2.0/modules/imgproc/include/opencv2/imgproc.hpp#L2109), [`dilate()`](https://github.com/opencv/opencv/blob/3.2.0/modules/imgproc/include/opencv2/imgproc.hpp#L2135) and [`morphologyEx()`](https://github.com/opencv/opencv/blob/3.2.0/modules/imgproc/include/opencv2/imgproc.hpp#L2161) (clickable links), the default border type seems to be `int borderType = BORDER_CONSTANT`.

**Comment by eyaler** [comment]
you seem to be correct and i cannot recreate my issue
