### ISSUE TITLE
largest connected component?

### ISSUE THREAD

**Issue by snapfinger** [opencv/opencv#8968]
##### Detailed description
I see there's the [connected component](http://docs.opencv.org/3.1.0/d3/dc0/group__imgproc__shape.html#gac2718a64ade63475425558aa669a943a) in version 3.1 that returns labeled image of connected components, which is great, but it's often the case that we want the largest connected component in a binary image, can it be implemented in the future?

**Comment by Petititi** [comment]
For this usage, you can use `connectedComponentsWithStats` which return some statistics for each connected componnent!

**Comment by snapfinger** [comment]
Oh yes, just found `cv2.CC_STAT_AREA: The total area (in pixels) of the connected component` that can truly make it easier. Thx.
