### ISSUE TITLE
Do you have a plan to develop golang api of opencv2.x and3.x

### ISSUE THREAD

**Issue by orange-jacky** [opencv/opencv#8971]
hi,
  i wanna know that whether you have a plan to deveolp golang api for opencv2.x and later version?
 in fact, many gophers need it

**Comment by sovrasov** [comment]
There are no such plans for now.

**Comment by deadprogram** [comment]
Hello, there. I've started working on an OpenCV 3.x interface for Golang here: 

https://github.com/hybridgroup/go-opencv3

Collaborators wanted!

**Comment by alalek** [comment]
#6109
