### ISSUE TITLE
Bug: Memory corruption in cv::repeat when src = dst

### ISSUE THREAD

**Issue by bhorn** [opencv/opencv#8972]
Original Post: http://answers.opencv.org/question/161823/cvrepeat-after-update-24-32-bug-or-feature/
------
#### 1.
- OpenCV => 3.2 (Compiled directly out of Git-Tag 3.2 without standard config)
- Operating System / Platform => Ubuntu 14.04 64 Bit
- Compiler => c++ (Ubuntu 5.4.1)

#### 2.
- OpenCV => 3.2 (Homebrew)
- Operating System / Platform =>OSX 10.11.6
- Compiler => Apple LLVM version 8.0.0 (clang-800.0.42.1)

### Detailed description

Consider this Code:
```
std::vector<int> lin = {1,2,3,4,5};
cv::Mat linmat = cv::Mat(lin).reshape(0,1);
```

At this point, we should have the Mat
````
[1,2,3,4,5]
````

So far so good. When applying `cv::repeat` to it in 2.4 like
```
cv::repeat(linmat,5,1,linmat);
```
The result in 2.4.8 was (like it should be):
```
    [1,2,3,4,5,
     1,2,3,4,5,
     1,2,3,4,5,
     1,2,3,4,5,
     1,2,3,4,5]
```
But **in 3.2, some memory-corruption happens when src = dst**. The result is some memory-garbage.
When I use a second `Mat` as dst, everything works fine.
Is this supposed to be like this or is this a bug?

### Full Code for 2.4.X
```
std::vector<int> lin = {1,2,3,4,5};
cv::Mat linmat = cv::Mat(lin).reshape(0,1);
cv::repeat(linmat,5,1,linmat);
```

### "Workaround" Code for 3.2
```
std::vector<int> lin = {1,2,3,4,5};
cv::Mat temp = cv::Mat(lin).reshape(0,1), linmat;
cv::repeat(temp,5,1,linmat);
```

**Comment by alalek** [comment]
There is a problem with processing of "inplace" arguments that requires memory reallocation. it is not handled correctly and, I believe, these "inplace" cases should not be handled at all.
Related: #8352 #8341 #8149

**Comment by bhorn** [comment]
@alalek well, it worked flawlessly in 2.4.X so it should be considered a Bug imho. Or at least it should be noted in the documentation.

**Comment by bhorn** [comment]
@alalek Why would you just forbid src=dst? You could use realloc to increase the arrays size?
