### ISSUE TITLE
Building WITH_QT gives various errors

### ISSUE THREAD

**Issue by fifothekid** [opencv/opencv#8977]
I'm building OpenCV 3.2 on Ubuntu 16.04
I'm including many libraries (extra modules, TBB, Eigen, etc..) and everything is compiling and working as it should
The only problem I have is when slecting the WITH_QT option
Although it is installed and the executable path is configured, I even tested creating QT apps, but it still gives me unfound reference errors when compiling the opencv_contrib examples 
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::KeyPointSettingsSelector'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::SlotQString'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::view::TranslationMatchView'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `CvButtonbar::staticMetaObject'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::gui::FilterCallTab'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::view::ImageView'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::MatchSettingsSelector'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::Slot'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::MatchManagement'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `typeinfo for cvv::qtutil::MatchSelection'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::OverlayFilterWidget'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::ChangedPixelsWidget'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `cvv::qtutil::SignalMatRef::signal(cv::Mat&) const'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::gui::OverviewPanel'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `cvv::qtutil::Signal::signal() const'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::STFLQueryWidget'
../../lib/libopencv_world.so.3.2.0: referência indefinida para `vtable for cvv::qtutil::KeyPointSelectionSelector'

Any workaround?

**Comment by alalek** [comment]
Try to disable "cvv" module: `cmake -DBUILD_opencv_cvv=OFF ...`

**Comment by fifothekid** [comment]
now I'm getting this
[ 47%] Linking CXX executable ../../bin/optflow-example-motempl
../../lib/libopencv_world.so.3.2.0: referência indefinida para `.vtable for CvWinProperties'
../../lib/libopencv_world.so.3.2.0: refer�./../lib/�libopencv_world.so.3.2.0ncia:  indefinidarefer para `vtable for �CvCheckBox�ncia' 
indefinida. para./ .`.vtable/ libfor/ libopencv_world.so.3.2.0CvWinProperties: '
refer.�./�.ncia. indefinida/lib /libopencv_world.so.3.2.0: referênciapara indefinida  para` `vtable for CvPushButton'
.vtable. for/../lib/libopencv_world.so.3.2.0: referência  indefinidaCvCheckBox '
para `vtable for GuiReceiver'

**Comment by alalek** [comment]
Try to disable "opencv_world" too: `-DBUILD_opencv_world=OFF`

**Comment by fifothekid** [comment]
that's exactly what I'm testing now

**Comment by fifothekid** [comment]
it worked thanks a lot

**Comment by themightyoarfish** [comment]
So whats the correct way to both have qt5 and cvv enabled? still a problem to this day.

**Comment by jiapei100** [comment]
Got the same **ERROR** messages today... But, what is **cvv** for???

Thank you ...
