### ISSUE TITLE
Stitching with CUDA

### ISSUE THREAD

**Issue by kukuyok** [opencv/opencv#8994]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04 x86_64
- Compiler => gcc 5.4.0
- GPU => Nvidia gtx 850m
- CUDA => 8

##### Detailed description

I'm trying to use gpu-accelerated Stitcher module. I use cv::Stitcher::create(mode, try_use_gpu) method with try_use_gpu = true. It ends with SIGABRT exception:
OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/petro/install/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 101
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/petro/install/opencv/modules/core/include/opencv2/core/private.cuda.hpp:101: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda

I built OpenCV 3.2.0 with flags WITH_CUDA=ON (and it has been marked ON eventually).
LD_LIBRARY_PATH is set correctly.

##### Steps to reproduce

**Comment by alalek** [comment]
#8792
