### ISSUE TITLE
Incorrect parsing of SSE types

### ISSUE THREAD

**Issue by spetroce** [opencv/opencv#9059]
- OpenCV => github/master
- Operating System / Platform => Fedora 25
- Compiler => GCC 6.3.1

##### Detailed description
My processor (i7-3740QM) does not support SSE3, but CPU_BASELINE gets set to SSE3. The problem is my processor supports SSSE3. The parser is incorrectly parsing the SSE3 string from SSSE3.

**Comment by alalek** [comment]
Don't worry, your processor supports `AVX` instructions, so it supports both SSE3 and SSSE3.

> The parser is incorrectly parsing the SSE3 string from SSSE3

Could you point on the line from cmake file with mentioned problem? (`cmake --trace-expand` should help)
