### ISSUE TITLE
dnn::tutorials some files not found

### ISSUE THREAD

**Issue by iwaki2009** [opencv/opencv#9072]
##### System information (version)

- OpenCV => 3.3.0-rc
- Operating System / Platform => ubuntu16.04
- Compiler => :grey_question:

##### Detailed description

dnn::tutorials some files not found
at tutorial_dnn_googlenet
these files are not found
caffe_googlenet.cpp
bvlc_googlenet.prototxt
synset_words.txt.

##### Steps to reproduce
open this page
https://github.com/opencv/opencv/blob/3.3.0-rc/modules/dnn/tutorials/tutorial_dnn_googlenet.markdown

click these links
that can be downloaded "here".
download GoogLeNet model files: "bvlc_googlenet.prototxt"
classes: "synset_words.txt".

**Comment by berak** [comment]
indeed, those should be :

https://github.com/opencv/opencv/blob/master/samples/dnn/caffe_googlenet.cpp
https://raw.githubusercontent.com/opencv/opencv/master/samples/data/dnn/bvlc_googlenet.prototxt
https://raw.githubusercontent.com/opencv/opencv/master/samples/data/dnn/synset_words.txt

**Comment by iwaki2009** [comment]
I downloaded all files. And sample program works well.
