### ISSUE TITLE
Why opencv3.2.0 winpack do not provide x86 build?

### ISSUE THREAD

**Issue by zchrissirhcz** [opencv/opencv#9083]
Since the prebuild opencv-3.2.0 winpack provides a folder `build`, which contains `OpenCVConfig.cmake`, I read it and found that, by default the `OpenCV_ARCH` is set to `x86`, while the provided prebuild files are just for `x64`.  Thus, when using cmake on windows, error occurs, like:

```
OpenCV_CONFIG_PATH is D:/work/opencv320/build
OpenCV_RUNTIME is vc14
OpenCV_ARCH is x86
OpenCV_LIB_PATH is
CMake Warning at D:/work/opencv320/build/OpenCVConfig.cmake:143 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at CMakeLists.txt:11 (find_package):
  Found package configuration file:

    D:/work/opencv320/build/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


-- Configuring incomplete, errors occurred!
See also "D:/work/opencv320/sources/samples/cpp/example_cmake/CMakeFiles/CMakeOutput.log".

```

I hope opencv can do better.

**Comment by alalek** [comment]
> by default the OpenCV_ARCH

There is no such default.

The major part of OpenCV users have 64-bit Windows platform.
In other specific cases users are able to build 32-bit binaries from sources.

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by zchrissirhcz** [comment]
Hi, thanks for your reply and I appreciate your work, but I think I didn't express clearly, so now I put more detail.

In `OpenCVConfig.cmake`,
```cmake
if(MSVC)
  message("CMAKE_CL_64 is ${CMAKE_CL_64}")
  if(CMAKE_CL_64)
    set(OpenCV_ARCH x64)
  elseif((CMAKE_GENERATOR MATCHES "ARM") OR ("${arch_hint}" STREQUAL "ARM") OR (CMAKE_VS_EFFECTIVE_PLATFORMS MATCHES "ARM|arm"))
    # see Modules/CmakeGenericSystem.cmake
    set(OpenCV_ARCH ARM)
  else()
    set(OpenCV_ARCH x86)
  endif()
```
I mean, this snippet will automatically set `OpenCV_ARCH` to `x86`, so I use the word `default`.

After download and extracting opencv-3.2.0 winpack, I would like to find the example cmake project, so I  choose `opencv320\sources\samples\cpp\example_cmake`, and simply typing:
```bash
mkdir build
cd build
cmake ..
```
Then, the previously patsted errors ocurs. Unless I specify it by:
```
cmake -G "Visual Studio 14 Win64" ..
```

The truth is, if not provided architecture parameters like Win64, the final result will not be x64 build. Further, maybe this is of Visual Studio default setting. However, `OpenCVConfig.cmake` should deal with it properly, i.e set it to `x64` as only `x64` build is provided in the zip file, instead of `x86`.

**Comment by alalek** [comment]
> maybe this is of Visual Studio default setting

No, It is CMake default generator.
OpenCV CMake script just **autodetects** the current configuration.

>  i.e. set it to x64 as only x64 build is provided in the zip file, instead of x86

This will not work, because CMake configures compiler toolchain for 32-bit builds.

The proper way is to always specify CMake generator:
```
cmake -G "Visual Studio 14 Win64" ...
```
