### ISSUE TITLE
Windows opencv_core compilation issue

### ISSUE THREAD

**Issue by FinancedHydra** [opencv/opencv#9100]
##### System information (version)

- OpenCV => [3.3.0-rc](https://github.com/opencv/opencv/releases/tag/3.3.0-rc)
- Operating System / Platform => Windows 10 - 64 Bit
- Compiler => Visual Studio 15 2017
- cmake => 3.9.0-rc5

##### Detailed description

Building 3.3.0-rc from source successfully configures and generates the build project files.   However compiling opencv_core fails with an `RC` error. 3.2.0 builds from source successfully using the same machine and configurations.

Build Command

> ResourceCompile:
C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86\rc.exe /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D NDEBUG /D _VARIADIC_MAX=10 /D __OPENCV_BUILD=1 /D _USE_MATH_DEFINES /D __STDC_CONSTANT_MACROS /D __STDC_LIMIT_MACROS /D OPENCV_WITH_ITT=1 /D "CMAKE_INTDIR=\\\"Release\\\"" /D CVAPI_EXPORTS /l"0x0409" /I"E:\opencv-3.3.0-rc\bin\3rdparty\ippicv\ippicv_win\include" /I"E:\opencv-3.3.0-rc\bin\3rdparty\ippicv\ippicv_win\..\ippiw_win\include" /I"E:\opencv-3.3.0-rc\bin" /I"E:\opencv-3.3.0-rc\modules\core\include" /I"E:\opencv-3.3.0-rc\modules\core\src" /I"E:\opencv-3.3.0-rc\bin\modules\core" /I"E:\opencv-3.3.0-rc\bin\include" /I"E:\opencv-3.3.0-rc\3rdparty\include\opencl\1.2" /I"E:\opencv-3.3.0-rc\3rdparty\ittnotify\include" /nologo /fo"opencv_core.dir\Release\vs_version.res"  /YuE:/opencv-3.3.0-rc/modules/core/src/precomp.hpp /FIE:/opencv-3.3.0-rc/modules/core/src/precomp.hpp E:\opencv-3.3.0-rc\bin\modules\core\vs_version.rc 

Build Error
```
Build FAILED.

       "E:\opencv-3.3.0-rc\bin\install.vcxproj" (default target) (1) ->
       "E:\opencv-3.3.0-rc\bin\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\opencv-3.3.0-rc\bin\modules\core\opencv_core.vcxproj" (default target) (15) ->
       (ResourceCompile target) -> 
         RC : fatal error RC1103: invalid option, /FIE:/opencv-3.3.0-rc/modules/core/src/precomp.hpp [E:\opencv-3.3.0-rc\bin\modules\core\opencv_core.vcxproj]


```

##### Steps to reproduce

Build 3.3.0-rc from source on Windows 10 using Visual Studio 15 2017.

**Comment by alalek** [comment]
Please add CMake version and options of failed command line.

Something like [this](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/11409/steps/compile%20release/logs/stdio):
> ResourceCompile:
> C:\Program Files (x86)\Windows Kits\8.1\bin\x86\rc.exe /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D NDEBUG /D _VARIADIC_MAX=10 /D __OPENCV_BUILD=1 /D _USE_MATH_DEFINES /D __STDC_CONSTANT_MACROS /D __STDC_LIMIT_MACROS /D OPENCV_WITH_ITT=1 /D "CMAKE_INTDIR=\\\"Release\\\"" /D CVAPI_EXPORTS /l"0x0409" /IC:\build\precommit_windows64\build\3rdparty\ippicv\ippicv_win\include /IC:\build\precommit_windows64\build\3rdparty\ippicv\ippicv_win\..\ippiw_win\include /IC:\build\precommit_windows64\build /IC:\build\precommit_windows64\opencv\modules\core\include /IC:\build\precommit_windows64\opencv\modules\core\src /IC:\build\precommit_windows64\build\modules\core /IC:\build\precommit_windows64\opencv\3rdparty\zlib /IC:\build\precommit_windows64\build\3rdparty\zlib /IC:\build\precommit_windows64\opencv\3rdparty\ittnotify\include /nologo /fo"opencv_core.dir\Release\vs_version.res" C:\build\precommit_windows64\build\modules\core\vs_version.rc

**Comment by FinancedHydra** [comment]
I've updated the original post with the cmake version and the failed command line

**Comment by alalek** [comment]
Workaround is to turn off CMake option: `ENABLE_PRECOMPILED_HEADERS=OFF`

**Comment by LaurentBerger** [comment]
@alalek It is weird because using vs 2017 I use ENABLE_PRECOMPILED_HEADERS=ON and there is no problem but I use cmake 3.7.

**Comment by FinancedHydra** [comment]
@alalek @LaurentBerger I can confirm that downgrading my cmake version resolved the `RC` error. I am now running cmake 3.8.2
