### ISSUE TITLE
oclSvmDetector not initialized by HoG detector on yaml load

### ISSUE THREAD

**Issue by IntRob** [opencv/opencv#9109]
##### System information (version)
OpenCV => 3.2.0
Operating System / Platform => android/arm64-v8a
Compiler => ninja, cmake parameters:
cmake -GNinja -DANDROID_ABI:STRING="arm64-v8a" -DANDROID_NDK:PATH= -DWITH_OPENCL:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/platforms/android/android.toolchain.cmake -DOPENCV_EXTRA_MODULES_PATH:PATH=/modules

##### Detailed description
OpenCL optimization is not applied to HoG detector when loading the descriptor from yaml file.
Since oclSvmDetector is not initialized when descriptor is loaded, it remains empty and therefore OpenCL optimization cannot be applied.
In comparison, readALTModel does call setSVMDetector and therefore initializes oclSvmDetector, and in theory the OpenCL optimization should be applied in such a scenario. We weren't able to validate that, since our HoG model is in yaml format.

##### Steps to reproduce

Build opencv with ocl support and check if ocl optimizations are executed in the scenario of loading HoG model from yaml file. They are not supposed to.
Initialization with HOGDescriptor::getDaimlerPeopleDetector(), or with HOGDescriptor::getDefaultPeopleDetector() are expected to yield similar result (no ocl optimization)

**Comment by sturkmen72** [comment]
fixed by https://github.com/opencv/opencv/pull/12479

**Comment by sturkmen72** [comment]
kindly reminder
this issue is fixed by #12479
