### ISSUE TITLE
[cross-compile][armv7]'ANDROID_LOG_INFO' was not declared in this scope 

### ISSUE THREAD

**Issue by samsun639** [opencv/opencv#9113]
- OpenCV => the latest,  git clone https://github.com/opencv/opencv.git
- Operating System / Platform => Ubuntu 14.04.5 LTS
- Compiler => apt-get install gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf

##### Steps to reproduce
1. cd ~/opencv/platforms/linux
2. mkdir -p build_hardfp
3. cd build_hardfp
4. cmake -DCMAKE_TOOLCHAIN_FILE=../arm-gnueabi.toolchain.cmake ../../..
5. make 

##### ERROR happen#######

> [  3%] Built target libtiff
[  8%] Built target libjpeg
[ 19%] Built target libwebp
[ 22%] Built target libjasper
[ 23%] Built target libpng
[ 30%] Built target IlmImf
[ 37%] Built target libprotobuf
Scanning dependencies of target opencv_core
[ 37%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/system.cpp.o
/root/opencv/opencv/modules/core/src/system.cpp: In member function 'void cv::HWFeatures::initialize()':
/root/opencv/opencv/modules/core/src/system.cpp:462:29: error: 'ANDROID_LOG_INFO' was not declared in this scope
         __android_log_print(ANDROID_LOG_INFO, "OpenCV", "cpufeatures library is not avaialble for CPU detection");
                             ^
/root/opencv/opencv/modules/core/src/system.cpp:462:113: error: '__android_log_print' was not declared in this scope
         __android_log_print(ANDROID_LOG_INFO, "OpenCV", "cpufeatures library is not avaialble for CPU detection");
                                                                                                                 ^
/root/opencv/opencv/modules/core/src/system.cpp: In function 'void cv::error(const cv::Exception&)':
/root/opencv/opencv/modules/core/src/system.cpp:929:29: error: 'ANDROID_LOG_ERROR' was not declared in this scope
         __android_log_print(ANDROID_LOG_ERROR, "cv::error()", "%s", buf);
                             ^
/root/opencv/opencv/modules/core/src/system.cpp:929:72: error: '__android_log_print' was not declared in this scope
         __android_log_print(ANDROID_LOG_ERROR, "cv::error()", "%s", buf);
                                                                        ^
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/system.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by alalek** [comment]
Run `make VERBOSE=1` to get failed compiler options.

1) [Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master_ARMv7-lin/builds/10147)
2) Mentioned code is under `ANDROID` guard:
```
#elif defined __arm__ && defined __ANDROID__
```

**Comment by samsun639** [comment]
@alalek , I have workaround the "ANDROID_LOG_INFO- not -found" issue.

Currently facing the issue that fail to link to libopencv_videoio.so
> Linking CXX shared library ../../lib/libopencv_videoio.so
> /local/mnt/android-ndk-r14b/mytoolchains/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: **error: cannot find -ldc1394**
> collect2: error: ld returned 1 exit status

from this [guidance ](http://docs.opencv.org/trunk/d0/d76/tutorial_arm_crosscompile_with_cmake.html)
it says libdc1394 2.x is optional. How can I build without libdc1384.so?

**Comment by alalek** [comment]
CMake option: `-DWITH_1394=OFF`

**Comment by samsun639** [comment]
Done!  Thx.
