### ISSUE TITLE
opencv2 VideoWriter doesn't create the output file

### ISSUE THREAD

**Issue by zvolsky** [opencv/opencv#9117]
It doesn't work on Linux, Debian Stretch stable, from Python. For me it has created the output file once properly, once with 0 bytes length and 500-times no file was created (no error reported; command timing (cycle of .write(frame)) as if all works excellent) :(((

Debian Stretch stable, aptitude install libopencv-dev python-opencv

It is reported many times and for long time in many threads (stackoverflow,..). No solution as I can find was found. Hints like "try other codec" or "it works on Linux but not on Windows" are simply not true.

**Comment by alalek** [comment]
> python-opencv

You should read FAQ of this **external** project.

**Comment by zvolsky** [comment]
Hi Alexander. Yes, you are true.
To clarify this, I add following:

python-opencv is Debian package (recommended, contains video support)
opencv-python is external project (not recommended, integrated opencv lacks video support)

so for Debian(,..) we have these possibilities:

# install from Debian packages
sudo aptitude install libopencv-dev python-opencv
## /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so
sudo aptitude purge libopencv-dev python-opencv  # uninstall

# install from sources (github.com/opencv/opencv): video support by default (see WITH_FFMPEG flag for cmake)
sudo aptitude install build-essential cmake
sudo aptitude install python-dev python-numpy
sudo aptitude install libavdevice-dev libavformat-dev libavfilter-dev libavcodec-dev libswscale-dev libavutil-dev 
sudo aptitude install libgtk2.0-common libgtk2.0-bin libgtk2.0-dev libdc1394-22-dev libv4l-dev libgstreamer-plugins-base1.0-dev
sudo pip install cmake
mkdir build/
cd build/
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..  # check output if FFMPEG status is YES
make
sudo make install --or-- sudo checkinstall --pkgname opencv
## /usr/local/lib/python2.7/dist-packages/cv2.so
sudo make uninstall --or-- sudo dpkg -r opencv  # uninstall

# opencv-python project (no need to use it!): opencv WITHOUT VIDEO support
sudo pip install opencv-python
## /usr/local/lib/python2.7/dist-packages/cv2/cv2.so
sudo pip uninstall opencv-python  # uninstall

## codec syntax:
try:
    codec = cv2.VideoWriter_fourcc(*'MJPG')   # newer syntax
except AttributeError:
    codec = cv2.cv.CV_FOU .VideoWriter_fourcc(*'MJPG')   # older syntax
