### ISSUE TITLE
CV_TRACE issue

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#9119]
##### System information (version)
- OpenCV => 3.3.0-rc
- Operating System / Platform => Windows 10 Pro 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I enabled the following flag.

- [X] CV_TRACE
- [X] BUILD_ITT
- [X] WITH_ITT

And I used [samples/cpp/application_trace.cpp](https://github.com/opencv/opencv/blob/3.3.0-rc/samples/cpp/application_trace.cpp) to trace. But, I think that ```CV_TRACE``` function is not working.

I investigated the processing of ```CV_TRACE```.
As a result, I found that ```isITTEnabled()``` returns <b>false</b>. So, I think that [this conditional expression](https://github.com/opencv/opencv/blob/3.3.0-rc/modules/core/src/trace.cpp#L200) is wrong.

##### Steps to reproduce

I used [samples/cpp/application_trace.cpp](https://github.com/opencv/opencv/blob/3.3.0-rc/samples/cpp/application_trace.cpp) to reproduce this issue.

**Comment by alalek** [comment]
Did you read this Wiki page: https://github.com/opencv/opencv/wiki/Profiling-OpenCV-Applications ?
For ITT tracing you need external tool: VTune or IntelSEAPI.

**Comment by atinfinity** [comment]
@alalek 

> Did you read this Wiki page: https://github.com/opencv/opencv/wiki/Profiling-OpenCV-Applications ?

I read this page. But, I misunderstood the following point.

### 1. does not use external tool
Sorry, I misunderstood that external tool(VTune or IntelSEAPI) is necessary for the visualization of result.

### 2. supported python version
I used Python 3.5. But, current [sea_runtool.py](https://github.com/01org/IntelSEAPI/blob/17.01.28/runtool/sea_runtool.py) support Python 2.7.

-----

Thanks to your advice I can use <code>CV_TRACE</code>.

![cv_trace](https://user-images.githubusercontent.com/2630323/27986138-ab90d58e-6435-11e7-935b-eb1cfc99a233.png)

**Comment by alalek** [comment]
Great!

1) ITT API requires some external tool.
2) OpenCV includes builtin custom text-based output. Requires `OPENCV_TRACE=1` environment variable.
