### ISSUE TITLE
I found this error while running sample cpp example facedetect.cpp 'undefiend reference to cv:'

### ISSUE THREAD

**Issue by devmishrs** [opencv/opencv#9126]
/tmp/ccbH13my.o: In function `main':                                                                                                                 
facedetect.cpp:(.text+0x10e): undefined reference to `cv::VideoCapture::VideoCapture()'                                                              
facedetect.cpp:(.text+0x14a): undefined reference to `cv::CascadeClassifier::CascadeClassifier()'                                                    
facedetect.cpp:(.text+0x159): undefined reference to `cv::CascadeClassifier::CascadeClassifier()'                                                    
facedetect.cpp:(.text+0x192): undefined reference to `cv::CommandLineParser::CommandLineParser(int, char const* const*, cv::String const&)'          
facedetect.cpp:(.text+0x1d0): undefined reference to `cv::CommandLineParser::has(cv::String const&) const'                                           
facedetect.cpp:(.text+0x36c): undefined reference to `cv::CommandLineParser::has(cv::String const&) const'                                           
facedetect.cpp:(.text+0x3ff): undefined reference to `cv::CommandLineParser::check() const'                                                          
facedetect.cpp:(.text+0x415): undefined reference to `cv::CommandLineParser::printErrors() const'                                                    
facedetect.cpp:(.text+0x44e): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'                                                
facedetect.cpp:(.text+0x4bd): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'                                                
facedetect.cpp:(.text+0x5be): undefined reference to `cv::VideoCapture::open(int)'                                                                   
facedetect.cpp:(.text+0x66c): undefined reference to `cv::imread(cv::String const&, int)'
facedetect.cpp:(.text+0x6ec): undefined reference to `cv::VideoCapture::open(cv::String const&)'
facedetect.cpp:(.text+0x77e): undefined reference to `cv::imread(cv::String const&, int)'
facedetect.cpp:(.text+0x7ff): undefined reference to `cv::VideoCapture::isOpened() const'
facedetect.cpp:(.text+0x836): undefined reference to `cv::VideoCapture::operator>>(cv::Mat&)'
facedetect.cpp:(.text+0x8c3): undefined reference to `cv::waitKey(int)'
facedetect.cpp:(.text+0x9b3): undefined reference to `cv::waitKey(int)'
facedetect.cpp:(.text+0xafa): undefined reference to `cv::imread(cv::String const&, int)'
facedetect.cpp:(.text+0xb8b): undefined reference to `cv::waitKey(int)'
facedetect.cpp:(.text+0xc19): undefined reference to `cv::CommandLineParser::~CommandLineParser()'
facedetect.cpp:(.text+0xc28): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
facedetect.cpp:(.text+0xc37): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
facedetect.cpp:(.text+0xc73): undefined reference to `cv::VideoCapture::~VideoCapture()'
facedetect.cpp:(.text+0xe0e): undefined reference to `cv::CommandLineParser::~CommandLineParser()'
facedetect.cpp:(.text+0xe22): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
facedetect.cpp:(.text+0xe36): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
facedetect.cpp:(.text+0xe77): undefined reference to `cv::VideoCapture::~VideoCapture()'
/tmp/ccbH13my.o: In function `detectAndDraw(cv::Mat&, cv::CascadeClassifier&, cv::CascadeClassifier&, double, bool)':
facedetect.cpp:(.text+0x1123): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
facedetect.cpp:(.text+0x11de): undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
facedetect.cpp:(.text+0x1247): undefined reference to `cv::equalizeHist(cv::_InputArray const&, cv::_OutputArray const&)'
facedetect.cpp:(.text+0x126a): undefined reference to `cv::getTickCount()'
facedetect.cpp:(.text+0x1310): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
facedetect.cpp:(.text+0x1380): undefined reference to `cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
facedetect.cpp:(.text+0x1433): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
facedetect.cpp:(.text+0x155f): undefined reference to `cv::getTickCount()'
facedetect.cpp:(.text+0x1599): undefined reference to `cv::getTickFrequency()'
facedetect.cpp:(.text+0x17dc): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
facedetect.cpp:(.text+0x191b): undefined reference to `cv::rectangle(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
facedetect.cpp:(.text+0x193d): undefined reference to `cv::CascadeClassifier::empty() const'
facedetect.cpp:(.text+0x1a28): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
facedetect.cpp:(.text+0x1bbf): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
facedetect.cpp:(.text+0x1c6d): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
/tmp/ccbH13my.o: In function `cv::String::String(char const*)':
facedetect.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccbH13my.o: In function `cv::String::~String()':
facedetect.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
/tmp/ccbH13my.o: In function `cv::Mat::~Mat()':
facedetect.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to `cv::fastFree(void*)'
/tmp/ccbH13my.o: In function `cv::Mat::clone() const':
facedetect.cpp:(.text._ZNK2cv3Mat5cloneEv[_ZNK2cv3Mat5cloneEv]+0x4e): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/tmp/ccbH13my.o: In function `cv::Mat::release()':
facedetect.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): undefined reference to `cv::Mat::deallocate()'
/tmp/ccbH13my.o: In function `cv::Mat::operator()(cv::Rect_<int> const&) const':
facedetect.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[_ZNK2cv3MatclERKNS_5Rect_IiEE]+0x27): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
/tmp/ccbH13my.o: In function `cv::Mat::operator=(cv::Mat&&)':
facedetect.cpp:(.text._ZN2cv3MataSEOS0_[_ZN2cv3MataSEOS0_]+0xe7): undefined reference to `cv::fastFree(void*)'
/tmp/ccbH13my.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
facedetect.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccbH13my.o: In function `cv::String cv::CommandLineParser::get<cv::String>(cv::String const&, bool) const':
facedetect.cpp:(.text._ZNK2cv17CommandLineParser3getINS_6StringEEET_RKS2_b[_ZNK2cv17CommandLineParser3getINS_6StringEEET_RKS2_b]+0x51): undefined reference to `cv::CommandLineParser::getByName(cv::String const&, bool, int, void*) const'
/tmp/ccbH13my.o: In function `double cv::CommandLineParser::get<double>(cv::String const&, bool) const':
facedetect.cpp:(.text._ZNK2cv17CommandLineParser3getIdEET_RKNS_6StringEb[_ZNK2cv17CommandLineParser3getIdEET_RKNS_6StringEb]+0x49): undefined reference to `cv::CommandLineParser::getByName(cv::String const&, bool, int, void*) const'
collect2: error: ld returned 1 exit status# 
**I've installed OpenCV from source(github). While running cpp example it shows reference error 
  Please help how to solve this problem.
_System : Kubuntu 17.04 64bit
Compiler: g++_**

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
