### ISSUE TITLE
undefined refenece to imread() even add libopencv_imgcodecs

### ISSUE THREAD

**Issue by samsun639** [opencv/opencv#9128]
OS:ubuntu14.04.5_x64
opencv version:3.2.0 (cross-compiled for armv7)
compiler: arm-linux-androideabi-g++ of android_ndk_r14b

sample code:
----test.cpp------
```
#include<opencv2/opencv.hpp>
#include<iostream>
using namespace std;

int main(int argc, char *argv[]) {
  cv::Mat im = cv::imread("test.jpg");
  return 0;
}
```

build step:
>arm-linux-androideabi-g++ test.cpp  -o test -lopencv_imgcodecs -lopencv_core -lopencv_highgui -lopencv_imgproc -rdynamic

error shows:

> /tmp/ccnPsR5z.o:test.cpp:function main: error: undefined reference to 'cv::imread(std::string const&, int)'
> collect2: error: ld returned 1 exit status

Question:
why linker cannot link  imread even though it has defined in libopencv_imgcodecs.so ?

>**nm -D libopencv_imgcodecs.so |grep imread**
00017d9c T _ZN2cv11imreadmultiERKNS_6StringERSt6vectorINS_3MatESaIS4_EEi
00013590 T _ZN2cv6imreadERKNS_6StringEi

>**file libopencv_imgcodecs.so**
libopencv_imgcodecs.so.3.2.0: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), not stripped

**Comment by samsun639** [comment]
the error  was related with header files, resolved, thx

**Comment by huijiao1120** [comment]
May I ask how did you solve this problem? Thx
