### ISSUE TITLE
gen_pattern.py generates incorrect checkerboard pattern

### ISSUE THREAD

**Issue by Miguel-OYeah** [opencv/opencv#9132]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
[gen_pattern.py](https://github.com/opencv/opencv/blob/master/doc/pattern_tools/gen_pattern.py) generates an incorrect checkerboard pattern (which cannot be fixed by tunning the rest of the parameters).
Indeed the squares overlap :
![image](https://user-images.githubusercontent.com/20231776/28016186-3b013426-656b-11e7-8905-4275f3df707d.png)
But they shouldn't.

I traced back the error to the svg header (produced in svgfig.py) where stroke-width has a non zero value resulting in a border added to each square:
```.svg
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg style="stroke-linejoin:round; stroke:black; stroke-width:0.5pt ....
```
Setting the border to 0
```.svg
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg style="stroke-linejoin:round; stroke:black; stroke-width:0.0pt ....
```
Results in no overlap and further eliminates the round edges caused by 

![image](https://user-images.githubusercontent.com/20231776/28016611-0b256536-656d-11e7-9726-068770177ebe.png)
Note that this also eliminates the roundness of the border caused by 
```.svg
<svg style="stroke-linejoin:round; ...
```

It looks like stroke-width is hardcoded several times throughout svgfig.py.
Note: I haven't investigated if that affects the generation of other patterns.

##### Steps to reproduce
Generate a pattern of checkerboard type:
```.bat
python gen_pattern.py -o output.svg -T checkerboard
 ```

**Comment by sovrasov** [comment]
@Miguel-OYeah try #9143

**Comment by Miguel-OYeah** [comment]
@sovrasov That indeed fixes it for the checkerboard pattern.
I believe the rest of the patterns also need a similar fix.
