### ISSUE TITLE
floodFill function doesn't support CV_64F

### ISSUE THREAD

**Issue by popizdeh** [opencv/opencv#9135]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Mac
- Compiler => Clang

##### Detailed description

Exception "OpenCV Error: Unsupported format or combination of formats" is thrown when cv::floodFill is called with CV_64F.

##### Steps to reproduce

```.cpp
cv::Mat c(1, 1, CV_64F, cv::Scalar(1));
cv::Rect region;
cv::floodFill(c, cv::Point(0, 0), cv::Scalar(0), &region, cv::Scalar(0), cv::Scalar(0), 4);
```

**Comment by sovrasov** [comment]
Support of different formats is restricted to reduce code bloat effect. `CV_32F` is supported by this function and it's enough in most cases.

**Comment by popizdeh** [comment]
One would hope that unused code won't get linked but I guess not everyone is statically linking. While I understand your argument it feels like less then an ideal solution to me. I think that documentation doesn't list supported types, or have I missed this? My expectation as the user of the library would be for all functions to work with all types. As for the code bloat I think having conditional compilation for certain types would be a much better solution.

**Comment by alalek** [comment]
> unused code

This doesn't work (including static linking). Linker is not able to determine type of your `cv::Mat`, so all processing code paths are included into result binary.
