### ISSUE TITLE
VideoCapture is not working properly with gstreamer

### ISSUE THREAD

**Issue by bvnp43** [opencv/opencv#9138]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => osx
- Compiler => 

##### Detailed description

1. Compile OpenCV with GStreamer, without FFMPEG and AVFOUNDATION
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=~/Desktop/opencv3 -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ -D BUILD_SHARED_LIBS=OFF -D WITH_IPP=OFF -D WITH_OPENCL=OFF -D WITH_FFMPEG=OFF -D WITH_AVFOUNDATION=OFF ..`

2. Extract url from youtube live-stream:
`youtube-dl -g https://www.youtube.com/watch?v=T5WCWpRpHDQ`

You will receive long url like : `https://manifest.googlevideo.com/api/...../index.m3u8`

3. Open VideoCapture as

```
cv::VideoCapture cap(url);

double fps = cap.get(cv::CAP_PROP_FPS);

for (;;)
{
    cv::Mat frame;
    cap >> frame;
}
```

As a result i'm not receiving any frame, reporting `fps=0`. Its just sitting in that `>>`. If i compile opencv with ffmpeg and without gstreamer everything works fine - i'm getting frames and fps. All good, bad and ugly gstreamer plugins are installed. gstreamer's version is 1.12.1.

I can play that url with gstreamer from command line as:

`gst-launch-1.0 playbin uri=...`

Processing of local video files works fine with that opencv code.

**Comment by bvnp43** [comment]
Ok, seems this is a part of `gettext` and additional command should be invoked

```
brew unlink gettext && brew link gettext --force
```

**Comment by alalek** [comment]
> index.m3u8

This is just "playlist". Try to process video stream instead.
