### ISSUE TITLE
Error using fisheye callibration in python binding OpenCV 3.2.0

### ISSUE THREAD

**Issue by RdlP** [opencv/opencv#9150]
##### System information (version)

- OpenCV =>  3.2
- Operating System / Platform => Linux / Ubuntu 15.04
- Compiler => Python 3.4.3 (default, Mar 26 2015, 22:03:40) [GCC 4.9.2] on linux

##### Detailed description

When I try the following 

```
ret, mtx, dist, rvecs, tvecs = cv2.fisheye.calibrate(object_points, image_points, gray.shape[::-1],None,None)
```
I get the next error
```
OpenCV Error: Assertion failed (objectPoints.type() == CV_32FC3 || objectPoints.type() == CV_64FC3) in calibrate, file /home/angelluis/Descargas/opencv-3.2.0/modules/calib3d/src/fisheye.cpp, line 726
Traceback (most recent call last):
  File "calibrate.py", line 59, in <module>
    ret, mtx, dist, rvecs, tvecs = cv2.fisheye.calibrate(object_points, image_points, gray.shape[::-1],None,None)
cv2.error: /home/angelluis/Descargas/opencv-3.2.0/modules/calib3d/src/fisheye.cpp:726: error: (-215) objectPoints.type() == CV_32FC3 || objectPoints.type() == CV_64FC3 in function calibrate
```
I know that this error ocurrs a time ago: https://github.com/opencv/opencv/issues/5534 but I think that it was fixed (https://github.com/opencv/opencv/pull/6454) in addition, when I try the workaround explained in https://github.com/opencv/opencv/issues/5534 it doesn't work

**Comment by xlla** [comment]
save issue here, 
<pre>
cv2.error: OpenCV(4.3.0-openvino-2020.3.0) C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\calib3d\src\fisheye.cpp:714: error: (-215:Assertion failed) objectPoints.type() == CV_32FC3 || objectPoints.type() == CV_64FC3 in function 'cv::fisheye::calibrate'
</pre>

**Comment by arsalan-mousavian** [comment]
I also had the same issue. Fixed it by expand_dims on object_points: ```np.expand_dims(np.asarray(self.obj_points), -2)```

**Comment by fghoussen** [comment]
Same problem (crash), same fix seems OK (no crash) here: thanks!.... But could you explain what the problem was and why this fix avoids crash: I have no more crash but after that, after calling `cv2.fisheye.undistortImage` I get weird images (without using fisheye, I get correct images calling `cv2.undistort` after `cv2.calibrateCamera`)

**Comment by cavalleria** [comment]
same issue

**Comment by harddrad** [comment]
Hi，I have the same problem with you ,dou you solve the issue? if you do ,could you tell me how to slove it or the reason of the issue, thanks very much!

**Comment by fghoussen** [comment]
>  tell me how to slove it 

This way: https://github.com/opencv/opencv/issues/9150#issuecomment-674664643

**Comment by PabloVD** [comment]
Same problem, fixed using `object_points.reshape(-1,1,3)` as input.
