### ISSUE TITLE
sometimes  camshfit get the  invalid width of  return (RotatedRect) 

### ISSUE THREAD

**Issue by vvck** [opencv/opencv#9152]
##### System information (version)
- OpenCV = 3.2:
- Operating System / Platform = win 10:
- Compiler = vs2013

##### Detailed description

sometimes when you use camshift to get the rectangle of object,you may get a invaild  value of the rectangle's width,the vaule is -1.#IND. Obviously,there is some wrong with it.

when i view the source code of camshift, i find the place  that the wrong may be happen.
file:  sources\modules\video\src\camshift.cpp
line:171
code:
       double width = std::sqrt( rotate_c * inv_m00 ) * 4;

if we put a negative number in sqrt , the return must be -1.#IND.
first **inv_m00** can't be a negative number, because m00 is determined in line 150,
so the only mistake should be **rotate_c** .
i can't find out the reason can cause this  situation,but if we can judge the rotate_c is a negative number may fix it.

**Comment by sovrasov** [comment]
@vvck this bug is probably hard to reproduce since nobody report it before. Could you please share a test video?

**Comment by vvck** [comment]
@sovrasov sorry, I tested the example used camera directly, so I don't have the video which use to reproduce the bug. 
as you say, this bug is hard to find, I will try my best to reproduce it ,then write the video file at same time.

**Comment by vvck** [comment]
@sovrasov  the video had been saved, but It's size is up to 270MB. How can i send to you?  email or other ways?

**Comment by sovrasov** [comment]
You can upload it to google drive.

**Comment by vvck** [comment]
@sovrasov sorry， because of the GWF, I can,t visit google driver.

**Comment by sturkmen72** [comment]
maybe this will be helpful to reproduce the bug

![bug](https://user-images.githubusercontent.com/12151541/31584749-c8af30c8-b1bc-11e7-819a-5df38eb141ee.png)

```
#include "opencv2/video/tracking.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"

#include <iostream>

using namespace cv;
using namespace std;

int main( int /*argc*/, const char** /*argv*/ )
{
    Rect trackWindow(60, 73, 33, 25);
    Mat backproj = imread("12151541/31584749-c8af30c8-b1bc-11e7-819a-5df38eb141ee.png", -1);
    RotatedRect trackBox = CamShift(backproj, trackWindow,
        TermCriteria(TermCriteria::EPS | TermCriteria::COUNT, 10, 1));
    cout << trackBox.size;

    return 0;
}
```
output trackBox.size
[-nan(ind) x 2.4574]
