### ISSUE TITLE
Makefile:160: recipe for target 'all' failed make: *** [all] Error 2

### ISSUE THREAD

**Issue by Damyady** [opencv/opencv#9162]
In file included from /usr/include/c++/6/memory:81:0,
                 from /root/Documents/Downloads/Compressed/opencv-2.4.11/modules/gpu/include/opencv2/gpu/gpu.hpp:48,
                 from /root/Documents/Downloads/Compressed/opencv-2.4.11/modules/stitching/src/precomp.hpp:72,
                 from /root/Documents/Downloads/Compressed/opencv-2.4.11/modules/stitching/src/warpers.cpp:43:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 94%] Linking CXX shared library ../../lib/libopencv_stitching.so
[ 94%] Built target opencv_stitching
[ 94%] Linking CXX executable ../../bin/opencv_perf_gpu
[ 94%] Built target opencv_perf_gpu
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by illutheplanet** [comment]
Same issue here
