### ISSUE TITLE
Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

### ISSUE THREAD

**Issue by monajalal** [opencv/opencv#9164]
I used to not have a problem but then changed the structure of my project without changing any code and I get this:

> Severity    Code    Description Project File    Line    Category    Source  Suppression State   Tool
> Error   C4996   'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. OpenARK-test    c:\opencv\build\include\opencv2\flann\logger.h  66      Build

```
void _setDestination(const char* name)
    {
        if (name==NULL) {
            stream = stdout;
        }
        else {
            stream = fopen(name,"w");
            if (stream == NULL) {
                stream = stdout;
            }
        }
    }
 
```

Visual Studio 2015, OpenCV3.2.0, Windows 10.
Please let me know how to fix this!

**Comment by monajalal** [comment]
So I did this and the error faded away but it was so random I am curious how was it even caused?
![fope](https://user-images.githubusercontent.com/1892917/28229953-c72ad6f6-6899-11e7-9aaf-5075cd77acd9.PNG)

**Comment by alalek** [comment]
Some related changes: #9026 #9004

> so random

There was an issue - OpenCV headers included first block such checks completelly (they define mentioned macro).
