### ISSUE TITLE
CMake flag of C++11 is incorrect

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#9170]
##### System information (version)
- OpenCV => 3.3.0-rc
- Operating System / Platform => Ubuntu 16.04 64 Bit
- Compiler => gcc 5.4.0

##### Detailed description
When we enabled <code>ENABLE_CXX11</code>, CMake checks the features of the compiler.
But, I think that [this check](https://github.com/opencv/opencv/blob/3.3.0-rc/cmake/OpenCVDetectCXXCompiler.cmake#L191) is incorrect and it should use <code>CMAKE_CXX11_COMPILE_FEATURES</code>.

**Comment by alalek** [comment]
Sorry, my mistake. You are right!
