### ISSUE TITLE
dnn module fails build on Visual Studio 2012

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#9193]
##### System information (version)

- OpenCV => master ( 10e6491c2288d85c14e719cf3350e371eb77ea35 )
- Operating System / Platform => Windows 7 64bit
- Compiler => Visual Studio 2012 Pro Update 5

##### Detailed description
 - DNN module fails by following error which [happens here](https://github.com/opencv/opencv/blob/10e6491c2288d85c14e719cf3350e371eb77ea35/modules/dnn/src/torch/THDiskFile.cpp#L330)
```
modules\dnn\src\torch\THDiskFile.cpp(330): error C2065: 'int32_t' : undeclared identifier
```

##### Steps to reproduce
 - Checkout master ( 10e6491c2288d85c14e719cf3350e371eb77ea35 )
 - Configure and make as usual
 - I'll write a PR for this later

**Comment by alalek** [comment]
#9167
