### ISSUE TITLE
Question about the source code

### ISSUE THREAD

**Issue by zhangqingyu199201** [opencv/opencv#9195]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

when i read the function "makeAgastOffsets" use fast feature extra
i wonder   the source
"  int k = 0;
    for( ; k < 16; k++ )
        pixel[k] = offsets[k][0] + offsets[k][1] * rowStride;
"
if i choose other mode rather than OAST_9_16 whether cause a mistake?

##### Steps to reproduce

obmit

**Comment by berak** [comment]
seems to be related to #7406

can you check, if you got [this fix](https://github.com/opencv/opencv/pull/8708) ?
