### ISSUE TITLE
Error executing samples and app (with Qt and OpenGL)

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv#9199]
Opencv - 3.3.0-rc-111-g12ed7ca63, Windows 7 x64, VS 2013. Also tested earlier on Windows XP and VS2010.
If Opencv builded with Qt and OpenGL while executing examples and app (opencv_annotation...) was received errors like

    The procedure entry point
    getProcAddress@QOpenGLContext@@QEBAP6AXXZPEBD@Z
    could not be located in the dynamic link library Qt5Gui.dII.
This errors appeared only in release build.
Its relatively old bug and it pass approximately after 3.1.0-1276-gf6208e3de.

**Comment by alalek** [comment]
Probably this is Qt5 related. There is [report](https://www.bountysource.com/issues/45623837-vlqt5_example-entry-point-not-found) of similar issue without OpenCV.

**Comment by Bleach665** [comment]
Qt version (5.5) was not changed. Only opencv..

**Comment by Bleach665** [comment]
Tried reproduce this in revision 3.1.0-1276-gf6208e3de. Bug disappear.

**Comment by Bleach665** [comment]
Refinement. This bug related only to x64 release build. Qt dll usually “seeable” by environment path entry – in this case bug reproduced. But if Qt dll’s (Qt5Core.dll, QtGui5.dll..) was copied to folder which consist ruined exe file sample or app executing was correct.

**Comment by Bleach665** [comment]
In current version opencv and Qt this bug resolved.
