### ISSUE TITLE
Make Issue with OpenCV 3.2

### ISSUE THREAD

**Issue by carmesean** [opencv/opencv#9201]
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 64 bit
- Compiler => make

##### Detailed description
I am having some trouble installing OpenCV 3.2. I followed the example given on Milq's github: https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh; however upon typing the command "make -j4", the process stopped at 23% due to a make error. I then tried this solution: http://www.ozbotz.org/opencv-installation, using the same OpenCV 3.2 zip file from the first solution. However, it stopped again, and I got the following error:

Scanning dependencies of target opencv_cudaarithm
[ 18%] [ 18%] [ 18%] [ 18%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/core.cpp.o
Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/element_operations.cpp.o
Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/reductions.cpp.o
Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/arithm.cpp.o
Linking CXX shared library ../../lib/libopencv_cudaarithm.so
[ 18%] Built target opencv_cudaarithm
make: *** [all] Error 2

Does anyone have any suggestion or solution to fix this? I have tried recreating it nearly 5 times, and everytime I receive the same error. I believe it has something to do with cudaarithm. I am pretty new to these types of installations, but I trying my best to learn. I have been able to figure out most things myself and by trial and error, but I am at a loss here.

**Comment by alalek** [comment]
Provided build log doesn't contain useful information about failure.
Try to disable CUDA: `cmake -DWITH_CUDA=OFF <...>`

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by carmesean** [comment]
For the type of project I am doing, I will need CUDA enabled on the OS. Wont that inhibit me from using CUDA?

**Comment by carmesean** [comment]
I also tried that during one of my several attempts to remedy the installation, but the process halted much sooner with much more errors. I typed` "cmake -DWITH_CUDA=OFF .."` in the build directory. I think that's the correct way to do it, and it did not work. Only produced more errors :(

**Comment by jtkb** [comment]
Just as an alternative way to build OpenCV, you could try the Maven build if you are familiar with Java and Maven. Under platforms/maven you will find the project and a README file to describe what you need to do. Please note however if you are using the latest version of Ubuntu (17.04) then the dependencies are currently out-of-date and there is a ticket for this issue.

**Comment by zhiqwang** [comment]
I meet the same error when I installing opencv-3.4.2, and I found the gcc's version compiling the NVCC is 7, which is conflicting to the version of gcc when I compile opencv. And I change the gcc version to 7, this error vanished.

**Comment by rob3c** [comment]
Thank you, @zhiqwang ! A gcc version mismatch with nvcc was indeed the problem for me also.

**Comment by sealfoss** [comment]
> I met the same error when I installing opencv-3.4.2, and I found that the gcc's version compiling the NVCC is 7, which is conflicting to the version of gcc when I compile opencv. And I change the gcc version to 7, this error vanished.

@zhiqwang If you are ever in the DC area I will buy you literally all of the beers!
