### ISSUE TITLE
core: Build fails on Visual Studio 2012

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#9204]
##### System information (version)

- OpenCV => master ( dcb3c4ff1e70c7301a985cbf62da04d946b0a72b )
- Operating System / Platform => Win 7 Pro 64bit
- Compiler => Visual Studio 2012

##### Detailed description
 - When building master on Visual Studio 2012, build fails
```
Error	1	error C1083: Cannot open include file: 'initializer_list': No such file or directory	modules\core\include\opencv2\core\matx.hpp	57	opencv_core
```
- The direct cause is [this include pragma here](https://github.com/opencv/opencv/blob/dcb3c4ff1e70c7301a985cbf62da04d946b0a72b/modules/core/include/opencv2/core/matx.hpp#L57)
- [Visual Studio 2012 doesn't support ```initializer_list``` ](https://blogs.msdn.microsoft.com/vcblog/2011/09/12/c11-features-in-visual-c-11/)
- [Visual Studio 2013 supports ```initializer_list```](https://msdn.microsoft.com/ja-jp/library/dn387584(v=vs.120).aspx)
- May be we should change the [if pragma here ](https://github.com/opencv/opencv/blob/dcb3c4ff1e70c7301a985cbf62da04d946b0a72b/modules/core/include/opencv2/core/cvdef.h#L378)

##### Steps to reproduce
 - build OpenCV master ( dcb3c4ff1e70c7301a985cbf62da04d946b0a72b ) on Visual Studio 2012

**Comment by alalek** [comment]
Thank you, you are right: https://msdn.microsoft.com/en-us/library/hh567368.aspx
Could you try to change 1600 -> 1800 [here](https://github.com/opencv/opencv/blob/dcb3c4ff1e70c7301a985cbf62da04d946b0a72b/modules/core/include/opencv2/core/cvdef.h#L378)?

**Comment by tomoaki0705** [comment]
Thank you. Your suggestion was perfect !
I created your suggestion as PR.
