### ISSUE TITLE
Update package dependencies list used by Maven build.

### ISSUE THREAD

**Issue by jtkb** [opencv/opencv#9211]
Attempting to build OpenCV via Maven on Ubuntu 17.04 currently fails due to missing dependencies:

libpng12-dev
libjasper-dev

These packages have also been removed/renamed.

**To reproduce:**
On Ubuntu 17.04 or later checkout  master and from the Maven platform sub directory execute 'mvn clean install' command.
The build will fail with the above packages missing. Searching the repositories yields no results (e.g. aptitude search libpng12-dev).

**Proposed solution:**
Update the package dependency list but maintain backwards compatibility as required.

**Proposed Assignee:**
Myself - PR to be submitted in the coming days.

**Comment by alalek** [comment]
Ubuntu 17.04 uses `libpng-dev` as package name.
Ubuntu 16.04 has both `libpng12-dev` / `libpng16-dev`
Ubuntu 14.04 has `libpng12-dev` only.

`libjasper` is [dropped](https://bugs.launchpad.net/ubuntu/+source/kde4libs/+bug/1612835) from Ubuntu 17.04.

**Comment by jtkb** [comment]
@alalek I tried removing the dependency on libjasper and building without a replacement and that seems to build ok but I'm not sure of what functionality jasper provided. OK to just remove it?

**Comment by alalek** [comment]
Jasper is used for image I/O. This dependency can be dropped safely.

**Comment by jtkb** [comment]
Is there a definitive list of dependencies anywhere (without having to refer to the CMake files)?

**Comment by alalek** [comment]
We don't maintain such lists, because there are many configurations/platforms.
Required packages for Java bindings are: CMake, Python (binary only, development libraries / numpy is not needed), Ant, JDK.
Other libraries just defines available features, most of them are I/O features.
