### ISSUE TITLE
android build_sdk.py 'Clean samples' error

### ISSUE THREAD

**Issue by hewj03** [opencv/opencv#9214]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Win10, python 2.7
- Compiler => cmake 3.9.0, android ndk r15b

##### Detailed description

Copy dir: E:\opencv\build\o4a\install\apk
Copy file: E:\opencv\build\o4a\install\LICENSE
Copy file: E:\opencv\build\o4a\install\README.android
Copy dir: E:\opencv\build\o4a\install\sdk
Copy docs: E:\opencv\build\javadoc
Traceback (most recent call last):
  &nbsp;&nbsp;File "build_sdk.py", line 320, in <module>
  &nbsp;&nbsp;File "build_sdk.py", line 244, in gather_results
    &nbsp;&nbsp;&nbsp;&nbsp;item = os.path.join(path, item)
WindowsError: [Error 3] The system cannot find the path specified: 'E:\\opencv\\build\\OpenCV-android-sdk\\samples/*.*'

I find there is no samples subdirectory inside build/OpenCV-android-sdk directory.
We should check if path exists before calling os.listdir(path).

##### Steps to reproduce
Run the following command in opencv root directory.

    python platforms/android/build_sdk.py build .

**Comment by alalek** [comment]
For some reason Android samples are not installed in your case.
Could you check for "Android examples:" line in you build log ([example](http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/10162/steps/build%20sdk/logs/stdio))?

**Comment by hewj03** [comment]
--   Android:
    --     Android ABI:                 armeabi-v7a with NEON
    --     STL type:                    gnustl_static
    --     Native API level:            android-9
    --     SDK target:                  android_sdk_target_status-NOTFOUND
    --     Android NDK:                 C:/Users/wenju/AppData/Local/Android/sdk/ndk-bundle (toolchain: arm-linux-androideabi-4.9)
    --     android tool:                NO
    --     Google Play manager:         NO
    --     Android examples:            NO

'Android examples' is NO.
Sorry, is it because SDK target and android tool are not configured successfully? Libraries and java files are generated successfully nevertheless.

**Comment by alalek** [comment]
Yes, you need to specify Android SDK path too via:
- `ANDROID_SDK` environment variable
- or `--sdk_path` option to `build_sdk.py` script

**Comment by kyo055** [comment]
how can I build the opencv from src by cmake

**Comment by alalek** [comment]
Check [documentation](http://docs.opencv.org/master/df/d65/tutorial_table_of_content_introduction.html) tutorials.
Validate your progress with logs from [our builds](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master).
