### ISSUE TITLE
GPCDetails::dropOutliers() will have segmentation fault if corr.size() is zero

### ISSUE THREAD

**Issue by boulderZ** [opencv/opencv#9220]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 14.04
- Compiler => gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

##### Detailed description

In the opencv_contrib optflow modules at [sparse_matching_gpc.cpp](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/src/sparse_matching_gpc.cpp), the function `GPCDetails::dropOutliers()` will have a segmentation fault if the input `corr` has `corr.size() = 0`. This function is called from `findCorrespondences()` located at [sparse_matcing_gpc.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/include/opencv2/optflow/sparse_matching_gpc.hpp). It is possible for this routine to find zero correspondences. If that happens with the current code, then a segmentation fault will occur. Easy fix is insert  the following as first lines of `GPCDetails::dropOutliers()`
```
if (corr.size() == 0) // if corr.size() is zero, just return unchanged
      return;
```

##### Steps to reproduce

Just call the function with `corr.size() = 0`

**Comment by saskatchewancatch** [comment]
@boulderZ that is a nice catch.

One thing to note, opencv_contrib has its own GitHub [page](https://github.com/opencv/opencv_contrib). Typically issues found in the [opencv_contrib](https://github.com/opencv/opencv_contrib) modules are filed there.

**Comment by mshabunin** [comment]
@VladX , please take a look at this issue.

**Comment by VladX** [comment]
@boulderZ thanks! It was fixed.
