### ISSUE TITLE
Exponential linear unit's support for cv.dnn

### ISSUE THREAD

**Issue by gogolgrind** [opencv/opencv#9223]
Hello!
During trying to convert my tensorflow-keras model to cv2.dnn I found that there is no support of [ELU activation](https://arxiv.org/pdf/1511.07289.pdf) function.
I got following error:
`OpenCV Error: Unspecified error (Unknown layer type Elu in op conv2d_127/Elu) in populateNet, file /home/user/Documents/projects/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 375
conv2d_127/Elu:Elu(conv2d_127/convolution)
...
`
So, I kindly ask to add that activation function to cv2.dnn module

**Comment by arrybn** [comment]
@gogolgrind I've added ELU for TF. Also I added test for ELU. Please check if all is correct and works for you
