### ISSUE TITLE
Any single call to bilateralFilter() causes Windows Virtual Bytes leak problem

### ISSUE THREAD

**Issue by combacsa** [opencv/opencv#9234]
##### System information (version)
- OpenCV => 3.1 / 3.2
- Operating System / Platform => Windows 64-bit (Windows 7, Windows 10)
- Compiler => Visual Studio 2013 Update 5

##### Detailed description

Any single call to bilateralFilter() causes Windows "Virtual Bytes" leak problem. Measured by either Windows Performance Monitor (perfmon) or GlobalMemoryStatus() function, any single call to bilateralFilter() function extremely increases "Virtual Bytes" and decreases "Available Virtual".

##### Steps to reproduce

I have attached ConsoleApplication1 solution to reproduce the problem. Just putting opencv_world310d.dll file into the project folder should reproduce the situation.
[ConsoleApplication1.zip](https://github.com/opencv/opencv/files/1174174/ConsoleApplication1.zip)

Sample console output shows dramatic increase of VrM Size (nearly 80 GB):

Handles:129     GDIs:4  VrM Size In Bytes :     159207424       Available VrM Size In Bytes :   140737329016832
Handles:219     GDIs:4  VrM Size In Bytes :     86428766208     Available VrM Size In Bytes :   140651059458048

**Comment by mshabunin** [comment]
Please post a minimal reproducing program text here. Nobody will run precompiled application.

**Comment by combacsa** [comment]
@mshabunin Thanks. The minimal reproducing program text as follows. (Just same as the ConsoleApplication1.cpp in the compressed zip file)

```
// ConsoleApplication1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#include <cstdio>
#include <iostream>
#include "opencv2/opencv.hpp"
#include "Windows.h"
#include <Psapi.h>


using namespace cv;

void printMem()
{
	DWORD dwHandlesCnt = 0;
	GetProcessHandleCount(GetCurrentProcess(), &dwHandlesCnt);

	MEMORYSTATUS stlpBuffer;
	GlobalMemoryStatus(&stlpBuffer);

	DWORD dwGDICnt = GetGuiResources(GetCurrentProcess(), GR_GDIOBJECTS);

	unsigned __int64 i64VrMSize = stlpBuffer.dwTotalVirtual - stlpBuffer.dwAvailVirtual;
	unsigned __int64 i64AVrMSize = stlpBuffer.dwAvailVirtual;

	std::wcout << "Handles:" << dwHandlesCnt;
	std::wcout << "\tGDIs:" << dwGDICnt;
	std::wcout << "\tVrM Size In Bytes : \t" << i64VrMSize;
	std::wcout << "\tAvailable VrM Size In Bytes : \t" << i64AVrMSize << std::endl;
}


int _tmain(int argc, _TCHAR* argv[])
{
	cv::Mat originFrame;
	cv::Mat bilateralFrame;

	originFrame = imread("image_22.jpg", CV_LOAD_IMAGE_COLOR);

	printMem();
	bilateralFilter(originFrame, bilateralFrame, -1, 15, 15);
	printMem();

	return 0;
}
```

**Comment by combacsa** [comment]
I believe that suspicious "Virtual Bytes" increasing problem just happens when executing the function below:

```
bool haveOpenCL()
{
#ifdef HAVE_OPENCL
    static bool g_isOpenCLInitialized = false;
    static bool g_isOpenCLAvailable = false;

    if (!g_isOpenCLInitialized)
    {
        try
        {
            cl_uint n = 0;
            g_isOpenCLAvailable = ::clGetPlatformIDs(0, NULL, &n) == CL_SUCCESS;
        }
        catch (...)
        {
            g_isOpenCLAvailable = false;
        }
        g_isOpenCLInitialized = true;
    }
    return g_isOpenCLAvailable;
#else
    return false;
#endif
}

```

Calling ::clGetPlatformIDs() function causes suspicious Virtual Bytes leakage...

**Comment by alalek** [comment]
`clGetPlatformIDs()` is external code, so we can't fix it. Also it is called only once, so there is no real problem at all. You should suppress/ignore this kind of problem.
