### ISSUE TITLE
TlsStorage::getData and TlsStorage::setData are not thread safe

### ISSUE THREAD

**Issue by haiwangcat** [opencv/opencv#9239]
##### System information (version)
- OpenCV => 3.2

##### Detailed description

TlsStorage::getData and TlsStorage::setData are not thread safe. Access to tlsSlots in CVX_Assert is not protected by a mutex lock.

    void* getData(size_t slotIdx) const
    {
        CVX_Assert(tlsSlots.size() > slotIdx);
        ...
    }

    void setData(size_t slotIdx, void* pData)
    {
        CVX_Assert(tlsSlots.size() > slotIdx && pData != NULL);
        ...
    }

##### Steps to reproduce

This bug can lead to data race if we concurrently call two CV functions in which parallel_for_ is used with pthread implementation.

**Comment by alalek** [comment]
BTW, `tlsSlots.size()` doesn't decrease during process lifetime.

**Comment by haiwangcat** [comment]
If we call two OpenCVX functions in parallel, then one thread may call the c'tor of TLSDataContainer while the other one calls getData():

TLSDataContainer::TLSDataContainer()
{
    key_ = (int)getTlsStorage().reserveSlot(); // Reserve key from TLS storage
}

Here reserveSlot() is called, which modifies tlsSlots.

**Comment by alalek** [comment]
Theoretically I agree. But size of `tlsSlots` should not be decreased anywhere practically, so this mentioned assertions should not be raised.

Do you use some thread sanitizer tool to detect this case?

**Comment by alalek** [comment]
@haiwangcat Please check this patch: #9241

**Comment by haiwangcat** [comment]
Yes, we found this issue from a thread sanitizer. Do you think if this is a false alarm?

In reserveSlot(), the size of tlsSlots is actually increased as there is a push_back operation.

**Comment by haiwangcat** [comment]
The patch #9241 could still lead to data race when one thread is increasing tlsSlotsSize and the other one is reading it. Can we make is an atomic variable?

**Comment by alalek** [comment]
Yes, I believe this is false alarm.

Condition in this assertion expression should be true in valid program (with valid `slotIdx` value):
```
CV_Assert(tlsSlotsSize > slotIdx);
```

So increasing (only) it in separate thread in `reserveSlot()` (under locks) and reading it in `getData()/setData()` (without locks) will not change "true" result of this condition value.

There is may be an issue with handling of invalid `slotIdx` (result of condition is changed from "false to true") - but locks doesn't help here too.
Additional locks will just introduce unnecessary performance impact.

Does this tool detects an issue if we just remove `CV_Assert()` statements from `getData/setData()`?

**Comment by haiwangcat** [comment]
I understand that even there is data race on slotIdx, the result of the assertion may not be affected. But this data race will be detected by our thread sanitizer, which will consistently emit warnings. So it is better to eliminate this data race. Removing the CV_Assert() should fix it. Thanks!

**Comment by alalek** [comment]
@haiwangcat Could you check patch again (added CV_Assert hiding from thread sanitizer): #9241 ?

**Comment by haiwangcat** [comment]
The updated patch looks good to me. Thanks a lot!
