### ISSUE TITLE
OpenCV 3.3.0 with CUDA 8: arm_neon.h issues on TX1

### ISSUE THREAD

**Issue by suneelbelkhale** [opencv/opencv#9242]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform =>  Linux4Tegra, Jetson TX1 64 bit
- Compiler => gcc 5.4, nvcc 8.0.72

##### Detailed description

I recently built OpenCV 3.3 from source on a Jetson TX1 for the purpose of creating a Stereo SLAM application. It builds successfully, but here is the error I get when I try to build anything that requires nvcc (one specific case is sgm from this repo: https://github.com/dhernandez0/sgm ): 

> /usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(38): error: identifier "__Int8x8_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(39): error: identifier "__Int16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(40): error: identifier "__Int32x2_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(41): error: identifier "__Int64x1_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(42): error: identifier "__Float16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(43): error: identifier "__Float32x2_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(44): error: identifier "__Poly8x8_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(45): error: identifier "__Poly16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(46): error: identifier "__Uint8x8_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(47): error: identifier "__Uint16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(48): error: identifier "__Uint32x2_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h(49): error: identifier "__Float64x1_t" is undefined
etc. (there are a lot more identifiers errors)

SGM uses CUDA and OpenCV. This error was not there with OpenCV4Tegra or the Ubuntu libopencv-dev package, which is what leads me to believe this is a new issue. As soon as I make installed from my source version (after uninstalling the other versions of opencv fully), I ran into this problem.

##### Steps to reproduce

Here is my cmake command:

> cmake \\
    -DCMAKE_BUILD_TYPE=Release \\
    -DCMAKE_INSTALL_PREFIX=/usr \\
    -DBUILD_PNG=OFF \\
    -DBUILD_TIFF=OFF \\
    -DBUILD_TBB=OFF \\
    -DBUILD_JPEG=OFF \\
    -DBUILD_JASPER=OFF \\
    -DBUILD_ZLIB=OFF \\
    -DBUILD_EXAMPLES=ON \\
    -DBUILD_opencv_java=OFF \\
    -DBUILD_opencv_python2=ON \\
    -DBUILD_opencv_python3=OFF \\
    -DENABLE_PRECOMPILED_HEADERS=OFF \\
    -DWITH_OPENCL=OFF \\
    -DWITH_OPENMP=OFF \\
    -DWITH_FFMPEG=ON \\
    -DWITH_GSTREAMER=OFF \\
    -DWITH_GSTREAMER_0_10=OFF \\
    -DWITH_CUDA=ON \\
    -D ENABLE_FAST_MATH=1 \\
    -D CUDA_FAST_MATH=1 \\
    -DWITH_GTK=ON \\
    -DWITH_VTK=OFF \\
    -DWITH_V4L=ON \\
    -D WITH_QT=ON \\
    -D WITH_OPENGL=OFF \\
    -D WITH_NVCUVID=1 \\
    -D WITH_CUFFT=ON \\
    -D WITH_EIGEN=ON \\
    -D WITH_IPP=ON \\
    -DWITH_TBB=ON \\
    -DWITH_CUBLAS=ON \\
    -DWITH_1394=OFF \\
    -DWITH_OPENEXR=OFF \\
    -DENABLE_NEON=ON \\
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \\
    -DCUDA_ARCH_BIN=5.3 \\
    -DCUDA_ARCH_PTX="" \\
    -D CUDA_GENERATION=Auto \\
    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules     ..

The build is successful, as I mentioned before. I should also mention that I tried building from source with 3.2.0 too with the same results. Has anyone gotten a similar thing to work in 3.1.0 or earlier? This does not affect normal OpenCV compilation (I can run mostly everything else), but it seems to affect only programs that use nvcc for building .cu files.

**Comment by tomoaki0705** [comment]
I think it would be very useful if you could write down more specific information.
 - Technically, OpenCV 3.3.0 hasn't been released yet, so I guess you ran in to some git version.  Probably you could figure out the git revision ?
 - Also, I understand that huge amount of error appears and you don't want to paste it all here, but I recommend you to paste the entire log, cmake log at https://gist.github.com/ or https://pastebin.com/
 - A header file could be included by any source file (```*.c```, ```*.cpp```, ```*.cc``` etc..).  So some error from header file is quite insufficient
 - Did OpenCV built well, and only your application using OpenCV and CUDA failing ?  I think still there's a chance that something went wrong in your own application and not in OpenCV.  I can't tell now.

**Comment by alalek** [comment]
OpenCV has many [build guards](https://github.com/opencv/opencv/blob/06407b4d1446334307db93b3c09a22b27e4b57ce/modules/core/include/opencv2/core/cv_cpu_dispatch.h#L29) for NVCC compiler. Probably it is missed somewhere, but current cut of logs doesn't help to find origin of this problem.

**Comment by suneelbelkhale** [comment]
Here is the full output when I build SGM.
https://pastebin.com/pbnq3ikD

OpenCV built with CUDA support with no problems, and I built from master (same revision as of a few days ago). Currently I am testing with OpenCV 3.1.0, I will let you all know how that goes as well.

**Comment by alalek** [comment]
Try to add guard to [this line](https://github.com/opencv/opencv/blob/06407b4d1446334307db93b3c09a22b27e4b57ce/modules/core/include/opencv2/core/cv_cpu_dispatch.h#L124):
```
&& !defined __CUDACC__ /* do not include SSE/AVX/NEON headers for NVCC compiler */ \
```

**Comment by suneelbelkhale** [comment]
Yep that did it! Now it looks like everything works well. Also, just to let you all know, I also just tested OpenCV 3.1.0, and that built and did not have this error either. I'll close the issue.

**Comment by meixialin** [comment]
@alalek Hello.Thank you for your answer.I met the same problem,but I can't solve it by adding the guard.My platform is tx2,and with cuda9,opencv 3.3.1. I'll be very thankful if you could help me .
