### ISSUE TITLE
Building opencv winrt 10.0 SDK fails to compile on VS 2015

### ISSUE THREAD

**Issue by Olivier-tl** [opencv/opencv#9250]
##### System information (version)
- OpenCV => Master
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015 update 3

##### Detailed description

We want to build opencv winrt on ARM. We tried running the script : 
~ cd opencv/platforms/winrt
~ .\setup_winrt.ps1 "WS" "10.0" "ARM" -b

It gives the following error for all configurations : 
CMake Error at CMakeLists.txt:127 (project):
  A Windows Store component with CMake requires both the Windows Desktop SDK
  as well as the Windows Store '10.0' SDK.  Please make sure that you have
  both installed.

We tried replacing the script using the modified one from the repo [opencv-hololens](https://github.com/sylvain-prevost/opencv-hololens/blob/master/platforms/winrt/setup_winrt.ps1). This worked well for x86 and x64 configurations but not for ARM.  There is two problems when building for ARM : 
  
  1.  Error C3861  '_tzcnt_u32': identifier not found
       This happens in opencv\modules\core\include\opencv2\core\hal\intrin.hpp	on line 443. 

  2.  Error	C2664  '__n128 __neon_QdQnQm(unsigned int,__n128,__n128)' : cannot convert argument 3 
       from 'volatile const float32x4_t' to '__n128'	opencv_imgproc	
       This happens opencv\modules\imgproc\src\smooth.cpp on line 3961.	

When we fix those two problems. It compiles successfully.

**Comment by alalek** [comment]
> CMake Error at CMakeLists.txt:127 (project):
A Windows Store component with CMake requires both the Windows Desktop SDK
as well as the Windows Store '10.0' SDK. Please make sure that you have
both installed.

This error message comes from CMake.
1. Please check that you using up-to-date CMake version.
2. Check for installed Windows 10 SDK: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk or via MSVS installer (works well with MSVS 2017 installer).
3. Try to call this build script from MSVS compiler command-line shell (with properly configured environment).

**Comment by Olivier-tl** [comment]
1. Latest CMake is installed.
2. Visual studio 2015 was already installed with windows 10 SDK.
3. We tried in the VS2015 (x86, x64) native tool command prompt and the same error comes up.

**Comment by alalek** [comment]
#9856
