### ISSUE TITLE
How do I figure out what the error is?

### ISSUE THREAD

**Issue by ramadawn** [opencv/opencv#9264]
Could someone tell me how to figure out what the build error was?

http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/11572

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by berak** [comment]
[follow the red bar](http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/11572/steps/whitespace%20opencv/logs/stdio).

(to avoid problems like this, you probably should rename the `pre-commit.sample` file in your local  `.git` folder to `pre-commit` , so you get those warnings at commit time already)
