### ISSUE TITLE
how to play youtube video with interval in opencv and train with online video?

### ISSUE THREAD

**Issue by hoyeunglee** [opencv/opencv#9267]
how to play youtube video with interval in opencv and train with online video without download all video?

there are 300,000 video , but hard disk size is limited

https://deepmind.com/research/open-source/open-source-datasets/kinetics/

**Comment by StevenPuttemans** [comment]
You simply cannot pull from an online video using OpenCV. That is also not what you want. Best way to do this

- Use a file retrieval protocol to download a single file
- Open it in OpenCV, play with 30 frames skipping
- Delete the file from system
- Continue

**Comment by leehanchung** [comment]
@StevenPuttemans My apologies for necroing but is it still the case that cv2.VideoCapture() won't directly read an online video link? Specifically, online video links pulled by Pafy/Youtube-dl or directly hosted online videos e.g., https://website.com/video.mpg?

**Comment by alalek** [comment]
It depends on used backend for VideoCapture.
There is some experience with accessing of RSTP streams from IP cameras via FFmpeg backend.
You need to ensure that your have (1) build with FFmpeg, (2) use FFmpeg backend.

**Comment by leehanchung** [comment]
I installed with  `pip install opencv-python`, version 4.1.  Looking to use `cv2.VideoCapture` to process HTTP streams as suggested by various [blogs](https://towardsdatascience.com/predict-age-and-gender-using-convolutional-neural-network-and-opencv-fd90390e3ce6) and StackOverflow [posts](https://stackoverflow.com/questions/43032163/how-to-read-youtube-live-stream-using-opencv-python/49699357).


Here's the VideoI/O part of `cv2.getBuildInformation()`
``` 
Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (58.47.106)
      avformat:                  YES (58.26.101)
      avutil:                    YES (56.26.100)
      swscale:                   YES (5.4.100)
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)
```
