### ISSUE TITLE
cv2.imshow shows blank image

### ISSUE THREAD

**Issue by planetA** [opencv/opencv#9273]
##### System information (version)

- OpenCV => 3.2 (compiled myself from source)
- Operating System / Platform => Debian testing
- Compiler => 6.3.0
- WM => awesome 4.0

##### Detailed description

Example videocapture_basic.cpp immediately crashes after opening the webcam.

The very same example works with opencv from the debian repository. And also it works with OpenCV 3.1.

##### Steps to reproduce

Just take the default example videocapture_basic.cpp compile and run it.

**Comment by shs2017** [comment]
Try compiling using 

> g++ videocapture_basic.cpp -lopencv_core -lopencv_videoio -lopencv_highgui -o videocapture_basic

If that doesn't work maybe try reinstalling gstreamer. Could you provide any more information on the crash.

**Comment by jayshah19949596** [comment]
I have the same problem... CV2.imshow shows blank and when I do plt.imshow it works... Any solution???

**Comment by MohamedAmineOuali** [comment]
jayshah19949596 
did you find a solution to your problem?
