### ISSUE TITLE
Demo dialogs vanish on windows

### ISSUE THREAD

**Issue by WascallyWabbit** [opencv/opencv#9282]
##### System information (version)

- OpenCV => 3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Several of the dialogues that come up from the demo program are invisible and inoperable. This includes the configuration dialog and the file open dialog that is accessed from the source selection dialog. This means that the user cannot open a file, and is restricted to using the default images provided with the application.

##### Steps to reproduce
To reproduce, open the Windows version of the demo program. Select, for example 'Laplacian computing'. You will see a source selection dialog come up with a picture of a female model. Choose 'Open' from the toolbar, and you will notice that the 'Open' dialogue flashes momentarily on the screen and then disappears. If you choose the application's icon in the bar along the bottom of the screen, you will see that the 'Open' dialog appears there, and that you can close it by selecting the X, but you cannot otherwise interact with it, or find it on the screen. 

In the meantime, you are frozen out of the other open windows in the program, which are unresponsive until you close the invisible dialogue. There are other dialogues that have this problem, and there are many other places in the UI where you can find it.

**Comment by alalek** [comment]
Try fresh OpenCV version and provide build configuration (there are several UI backends).

**Comment by WascallyWabbit** [comment]
I used the newest prebuilt bits from the OpenCV site.
