### ISSUE TITLE
error in surf feature matching output 

### ISSUE THREAD

**Issue by allenkallz** [opencv/opencv#9283]
- OpenCV => 3.1
- Operating System / Platform => ubuntu 64 Bit

I tried for feature matching between two pic using

surf = cv2.xfeatures2d.SURF_create()
but the output is : [pic](https://ibb.co/mXzHKk)

steps are:

     first I create surf 
     then I extract the feature from both images
     then extract good feature 
    after that, I draw lines

In above pic I draw line between both images feature point, I don't know why in image hand feature are match with the foot in another pic.

**Comment by alalek** [comment]
You have bad image for this algorithm.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
