### ISSUE TITLE
Buggy winSigma check in HOGDescriptor

### ISSUE THREAD

**Issue by gadcam** [opencv/opencv#9307]
- OpenCV => 3.2 & master

If you try to create a HOGDescriptor with <code>winSigma = 0</code> the current code will let you do and then it will provide features that will be constant for all dimensions.
```C++
double HOGDescriptor::getWinSigma() const
{
    return winSigma >= 0 ? winSigma : (blockSize.width + blockSize.height)/8.;
}
```
If I am right [this check](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp#L103)  should be changed from <code>winSigma >= 0</code> to <code>winSigma > 0</code>.

The explanation is that it will make scale infite [in this code](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp#L659)
```C++
float scale = 1.f / (2.f * sigma * sigma);
```
and as a consequence [this code](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp#L728)
```C++
weights(i,j) = std::exp(-(_di[i] + _dj[j])*scale);
```
will misbehave.

**Comment by sovrasov** [comment]
@gadcam could you please make a PR with the proposed fix?

**Comment by sturkmen72** [comment]
fix is merged
