### ISSUE TITLE
update 2.4 branch to libjpeg 9

### ISSUE THREAD

**Issue by paleozogt** [opencv/opencv#9314]
##### System information (version)
- OpenCV => 2.4.13.3
- Operating System / Platform => n/a
- Compiler => n/a

##### Detailed description

The OpenCV 2.4.x series has a pretty old libjpeg.  Let's update it to what the OpenCV 3.x has-- libjpeg 9.

##### Steps to reproduce

n/a

**Comment by StevenPuttemans** [comment]
Actually, afaik, OpenCV 2.4 is only supported for bugfixing, but we switched to the 3.x interface almost 2 years ago, so its time to move on if you want support of newer libraries. I am afraid for backwards compatibility reasons they are not just going to switch contents anymore in a sort of frozen branch of the library.
