### ISSUE TITLE
cv2.boundingRect(points) rectangle is too big

### ISSUE THREAD

**Issue by WilliamCarlos** [opencv/opencv#9318]
##### System information (version)
- OpenCV => 2.4.13.2
- Operating System / Platform => macOS Sierra Version 10.12.6
- Compiler => Python 2.7.13

##### Detailed description

It seems like cv2.boundingRect is either not handling negative coordinates correctly or not returning the minimal upright bounding rectangle. 

##### Steps to reproduce
I have a set of points that I want to find a boundingRect for: 
(Pdb) p pointsToEncapsulate
```
array([[[    0.        ,     0.        ]],

       [[ 1547.        ,     0.        ]],

       [[ 1547.        ,  4789.        ]],

       [[    0.        ,  4789.        ]],

       [[ -560.79431152,  -209.57356262]],

       [[  725.2399292 ,  -236.93405151]],

       [[ 1091.21142578,  5017.98730469]],

       [[  -69.31521606,  5257.94873047]]], dtype=float32)
```

I attempt to create a boundingRect around these points: 
(Pdb) cv2.boundingRect(pointsToEncapsulate)

Which yields a bounding rectangle of:
```(-561, -237, 2109, 5495)```

But it seems like this is not the minimal upright bounding rectangle? The correct upright bounding rectangle being (-561, -237, 1547, 5258)  or (0, 0, 2109, 5495) where all points have been shifted to the origin through a translation of (561, 237). 

Is this intended behavior? If not, it seems as if the absolute value of the coordinates is being used to calculate the boundingRectangle instead of the signed coordinates. Thanks!

**Comment by berak** [comment]
a cv::Rect is [x,y,w,h], while you seem to assume [x1,y1, x2,y2]

(imho, the calculation is correct, and it's just a misunderstanding, how to interpret the tuple in python)

**Comment by WilliamCarlos** [comment]
Oh I see, I assumed it was [x1,y1, x2,y2] since that's what cv2.rectangle() takes in... thanks!
