### ISSUE TITLE
opencv3.3.0 dnn ssd_mobilenet_object_detection runtime erro

### ISSUE THREAD

**Issue by YuehChuan** [opencv/opencv#9322]
##### System information (version)

- OpenCV => :grey_question:3.3.0
- Operating System / Platform => :grey_question:ubuntu16.04.2
- Compiler => :grey_question: 

##### Detailed description

I just install latest release of opencv3.3.0 and try dnn example 
fresh install ubuntu16.04.2
https://hackmd.io/s/S1gWq7BwW#

I successful run fcn and caffe example, but when it comes mobile SSD got runtime erro,
it seems relate to https://github.com/opencv/opencv_contrib/issues/941

the original caffemodel link in the code not work.
https://github.com/chuanqi305/MobileNet-SSD/blob/master/MobileNetSSD_train.caffemodel

so I download from deploy version here and change name to "MobileNetSSD_train.caffemodel"
https://github.com/chuanqi305/MobileNet-SSD
also change name for "MobileNetSSD_300x300.prototxt"
![file](https://user-images.githubusercontent.com/7314531/29009192-a5ddf9de-7b53-11e7-8845-e67178272c2b.png)

```txt=
./example_dnn-ssd_mobilenet_object_detection 
OpenCV Error: Assertion failed ((bias && l->blobs.size() == 2) || (!bias && l->blobs.size() == 1)) in initConvDeconvLayerFromCaffe, file /home/user/opencv-3.3.0/modules/dnn/src/layers/convolution_layer.cpp, line 1204
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/user/opencv-3.3.0/modules/dnn/src/layers/convolution_layer.cpp:1204: error: (-215) (bias && l->blobs.size() == 2) || (!bias && l->blobs.size() == 1) in function initConvDeconvLayerFromCaffe
```
##### Steps to reproduce

https://hackmd.io/s/S1gWq7BwW#

**Comment by dkurt** [comment]
Hi, @YuehChuan! Samples works fine. You just forgotten to pass a path to `.caffemodel` (there is no default value and no assertion). Deploy model and `.prototxt` from repository you mentioned.

**Comment by YuehChuan** [comment]
@dkurt ,Thank you!  
![ssd](https://user-images.githubusercontent.com/7314531/29051880-764e4276-7c18-11e7-9c0c-710f4b197694.png)
 The demo works nice on ps3 eye webcam :)  
`./example_dnn-ssd_mobilenet_object_detection -video=/dev/video1 -model=MobileNetSSD_train.caffemodel -proto=MobileNetSSD_300x300.prototxt`
and  .zip file include executable and .caffemodel , proto.txt for someone would like to try it. size about 600MB
https://drive.google.com/file/d/0BwY-lpO6tzxHRHNCdlRKczIzaEU/view?usp=sharing

**Comment by YuehChuan** [comment]
hey @dkurt 
I got SSD_mobileNET working on Raspberry pi3. Thank you! 
![pi3-ssdnet](https://user-images.githubusercontent.com/7314531/29097079-8bc9e986-7cca-11e7-9ac3-5baeb142ad7d.png)

**Comment by YuehChuan** [comment]
have fun!
https://hackmd.io/s/S1oIlawDb#

**Comment by YaddyVirus** [comment]
I am getting the same error using the YOLOv3 caffemodel file. Any ideas?
