### ISSUE TITLE
Python3 lib link fails for 3.3

### ISSUE THREAD

**Issue by JusticeOF666** [opencv/opencv#9325]
- OpenCV => 3.3
- Operating System / Platform => DEBIAN 9 kernel 4.11
- Compiler => gcc 6.4

With command `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local     -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=OFF -D PYTHON_EXECUTABLE=/usr/bin/python3.5 -D BUILD_EXAMPLES=ON -D WITH_V4L=ON -D WITH_LIBV4L=OFF -D OPENCV_EXTRA_MODULES_PATH=/home/adam/Desktop/opencv_contrib-master/modules -D PYTHON3_EXECUTABLE=/usr/bin/python3.5 -D PYTHON_INCLUDE_DIR=/usr/include/python3.5 -D PYTHON_INCLUDE_DIR2=/usr/include/x86_64-linux-gnu/python3.5m -D PYTHON3_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5dm.so -D PYTHON3_PACKAGES_PATH=/usr/lib/python3/dist-packages -D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/lib/python3/dist-packages/numpy/core/include .. -DWITH_GTK=ON -DBUILD_opencv_python3=ON`

Fails to link the Python3 libs (Python3 libraries: NO).

What is the proper way to link the lib? The file in the command (libpython3.5dm.so) exists and corresponds to the interpreter version.

EDIT: Their is also no Python for build found

[CMakeOutput.log.zip](https://github.com/opencv/opencv/files/1204406/CMakeOutput.log.zip)

**Comment by Yamada4** [comment]
same issue debian 8 jessie 64 bit

close commands not same but same error

i have 2 diffrent version of python , i cant include the 3.6.2 its sees 2.7 so i cant build it

**Comment by alalek** [comment]
OpenCV uses CMake's module for Python detection. What CMake do you use (version, system/Kitware)?

**Comment by Yamada4** [comment]
Cmake version 3.0.2 , debian 8 jessie 64 bit , my issue is i have diffrent versions of python 2.7 3.4.2 and 3.6.2 
when i configurate with cmake it sees my 2.7 and 3.4.2 versions i tried to show the python3.6 with this command 

`cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local/lib/opencv PYTHON_EXECUTABLE=/usr/local/bin/python3.6 PYTHON_INCLUDE_DIR=/usr/local/include/python3.6m PYTHON_INCLUDE_DIR2= /usr/local/python3.6/config-3.6m-x86_64-linux-gnu PYTHON_LIBRARY=/usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a PYTHON3_NUMPY_INCLUDE_DIRS = /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy .. `

oohh but it sees 3.4.2 and i cant build it and use opencv library on 3.6.2 right now just waiting wheel for easy installition

**Comment by mshabunin** [comment]
@Yamada4 , in OpenCV 3.x these cmake parameters should be named `PYTHON2_*` and `PYTHON3_*`. And you have `PYTHON_INCLUDE_DIR` and some others like this.

**Comment by Yamada4** [comment]
i changed paramters to python 3 but it still same sees python3.4.2 not 3.6 .2 i dont understand did i miss something ? or is there a way to copy 3.4.2 opencv library to 3.6.2 ?

**Comment by mshabunin** [comment]
@Yamada4 , did you run a clean build (with cmake cache cleared) after changing the parameters? Can you post a cmake output?

**Comment by Yamada4** [comment]
this is the site i used to build : http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

this is the command i use `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local/lib/opencv PYTHON3_EXECUTABLE=/usr/local/bin/python3.6 PYTHON3_INCLUDE_DIR =/usr/local/include/python3.6m PYTHON3_INCLUDE_DIR2 = /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu PYTHON3_LIBRARY = /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a PYTHON3_NUMPY_INCLUDE_DIRS = /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy ..`

and this is the cmake output log
[CMakeOutput.zip](https://github.com/opencv/opencv/files/1214814/CMakeOutput.zip)

**Comment by mshabunin** [comment]
@Yamada4 , this is a wrong output log, please attach the text which cmake outputs to the console.

**Comment by Yamada4** [comment]
[otput.zip](https://github.com/opencv/opencv/files/1214852/otput.zip)



maybe this one ?

**Comment by mshabunin** [comment]
@Yamada4 , according to this log, you've passed wrong parameters in command line:
```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local/lib/opencv PYTHON3_EXECUTABLE=/usr/local/bin/python3.6 PYTHON3_INCLUDE_DIR =/usr/local/include/python3.6m PYTHON3_INCLUDE_DIR2 = /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu PYTHON3_LIBRARY = /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a PYTHON3_NUMPY_INCLUDE_DIRS = /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy ..
```
Parameters should be in form `-D<name>=<value>` without spaces around the equal sign. Space between `-D` and parameter name is optional.

**Comment by Yamada4** [comment]
@mshabunin  tanks for the information i found the solution 

> `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local/lib/opencv 
-DPYTHON3_EXECUTABLE=/usr/local/bin/python3.6`

when we use like this we dont need to show the way libraries and theother things cmake will find them
