### ISSUE TITLE
Is the opencv DNN module suitable for the trained network from PaddlePaddle?

### ISSUE THREAD

**Issue by osDanielLee** [opencv/opencv#9341]
As the title show, I really want to know the DNN module is suitable for the trained network from PaddlePaddle(https://github.com/PaddlePaddle/Paddle) or not? Could it be the tensorflow BTW?

**Comment by dkurt** [comment]
@osDanielLee, first of all, thank you for interesting in OpenCV and especially DNN module. Currently it imports trained models from Caffe, Torch and TensorFlow frameworks.

Please read hints during new issue creation next time more careful. It is a tracker for bugs or feature proposals rather for usage/build/install questions. Use http://answers.opencv.org for the last ones.

If you want to see new importer, make a research: find interesting trained models for tests and tutorials, give us proofs that this framework is popular and community interested in it. Of course, you are welcome to prepare a PR with new usage. Follow https://github.com/opencv/opencv/wiki/How_to_contribute.
