### ISSUE TITLE
cv::ximgproc::segmentation::selectiveSearchSegmentation

### ISSUE THREAD

**Issue by Uyenndxu** [opencv/opencv#9344]
I'm using **cv::ximgproc::segmentation::selectiveSearchSegmentation** to implement the selective search for object detection task. I tried first with several images. However all of them return the same error.

`"OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in cv::Mat::Mat`

I did some investigations an found out that the in the error happen in file **selectivesearchSegmentation.cpp** in function:

`void SelectiveSearchSegmentationStrategyTextureImpl::setImage(InputArray img_, InputArray regions_, InputArray sizes_, int image_id) `

at this last line  this block of code (line 569 in selectivesearchSegmentation.cpp):

`// X, rot`
`Scharr(img_plane_rotated, tmp_gradiant, CV_32F, 1, 0);`
`center = Point((int)(img_plane_rotated.cols / 2.0), (int)(img_plane_rotated.rows / 2.0));`
`rot = cv::getRotationMatrix2D(center, -45.0, 1.0);`
`warpAffine(tmp_gradiant, tmp_rot, rot, bbox.size());`
`tmp_gradiant = tmp_rot(Rect((bbox.width - img.cols) / 2, (bbox.height - img.rows) / 2, img.cols, img.rows));`

The error happen because after the rotation, the value of
`bbox.width - img.cols `
is smaller than zero. (such as if the image has dimension: 227x640)

**Comment by alalek** [comment]
Contrib issues should go here: https://github.com/opencv/opencv_contrib/issues
