### ISSUE TITLE
cv2.HOGDescriptor.compute() crashes python 

### ISSUE THREAD

**Issue by DiiaanaD** [opencv/opencv#9345]
Hello.
I'm using opencv 3.2 with python and when I'm trying to run the following code::

win_size = (48,96)
block_size = (16,16)
block_stride = (8,8)
cell_size = (8,8)
num_bins = 9
hog = cv2.HOGDescriptor(win_size, block_size, block_stride, cell_size, num_bins)
img = cv2.imread(filename)
desc = hog.compute(img, (64,64))

I get the message "python.exe has stopped working" 

Note that 
* my image is 512 x 512;
* this happens only after adding the last line from code 

Could you please tell me what is wrong?

Thanks,
Diana

**Comment by mshabunin** [comment]
@DiiaanaD , please try to ask your question on the forum: https://answers.opencv.org

**Comment by sturkmen72** [comment]
please close down this issue
