### ISSUE TITLE
OpenCV 3.3.0 : opencv_annotation -> no GUI ???

### ISSUE THREAD

**Issue by kyrios123** [opencv/opencv#9348]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Linux 64 Bit
- Compiler => gcc 6.4.0
##### Detailed description
I did build OpenCV 3.3.0 from source and then I did run `opencv_annotation`  to check new version is working properly. I see instructions in the console, but there is no GUI window.

I did then build OpenCV 3.1.0 on the same machine, against exactly the same libraries and I made the same test. and the GUI window is opened.

Did I miss something ?

##### Steps to reproduce
Create a directory `/tmp/img` and copy a few images into it (2 .png for me). Create a diretory `/tmp/txt` and create a text file named file1.txt, type something in to that file and save it then run :
```$ opencv_annotation -images /tmp/img/ -annotations /tmp/txt/file1.txt 
* mark rectangles with the left mouse button,
* press 'c' to accept a selection,
* press 'd' to delete the latest selection,
* press 'n' to proceed with next image,
* press 'esc' to stop.```

**Comment by StevenPuttemans** [comment]
Hello, I am the original author of the tool, so just took a look at the 3.3 version.

I just validated the pipeline on a clean Ubuntu16.04 installation, with recent master branch and everything works fine. The old interface indeed required a `.txt` file but the new one just works out of the blue if you pass it a folder. Running the app without anything produces this output

```
Usage: opencv_annotation [params] 

	-?, -h, --help, --usage
		show this message
	-a, --annotations
		(required) path to annotations txt file [example - /data/annotations.txt]
	-i, --images
		(required) path to image folder [example - /data/testimages/]
	-m, --maxWindowHeight (value:-1)
		(optional) images larger in height than this value will be scaled down
	-r, --resizeFactor (value:2)
		(optional) factor for scaling down [default = half the size]
```

This is the command I am using for that `opencv_annotation --annotations=/tmp/annotations.txt --images=/home/steven/Pictures/` and I get the output below.

![screenshot from 2017-08-13 13-22-57](https://user-images.githubusercontent.com/4621239/29249141-91ad8692-802a-11e7-9ecf-c8d1e0137a21.png)

together with the desired command in the controle window

```
* mark rectangles with the left mouse button,
* press 'c' to accept a selection,
* press 'd' to delete the latest selection,
* press 'n' to proceed with next image,
* press 'esc' to stop.
```

And once I do the annotations it outputs the correct file. Please retrace your steps and close this issue once you get it solved.

**Comment by aaivanyutenko** [comment]
Is just the problem in arguments parsing/
This variant doesn't work:
opencv_annotation --annotations anno.xml --images bg
But this works well:
opencv_annotation --annotations=anno.xml --images=bg

**Comment by kyrios123** [comment]
Thanks @aaivanyutenko that was indeed the problem !

**Comment by rpsirois** [comment]
@aaivanyutenko same. thank you

**Comment by Barabas19** [comment]
Doesn't work in 2025 with Debian bookworm.
