### ISSUE TITLE
linker error wit clFFT

### ISSUE THREAD

**Issue by skn123** [opencv/opencv#9352]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

[ 55%] Linking CXX executable ../../../../bin/opencv_waldboost_detector
../../../../lib/libopencv_core.so.3.3.0: undefined reference to `clfftInitSetupData'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/build.make:101: recipe for target 'bin/opencv_waldboost_detector' failed
make[2]: *** [bin/opencv_waldboost_detector] Error 1
CMakeFiles/Makefile2:3300: recipe for target 'modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all' failed
make[1]: *** [modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all] Error 2

clFFT is the latest checkout from git

**Comment by alalek** [comment]
There is support for some exact version of clAmdFFT only.
clFFT is not supported.
