### ISSUE TITLE
Incorrect documentation of relative norm flags for the core 'norm' function

### ISSUE THREAD

**Issue by azatsman** [opencv/opencv#9354]
Documentation in cv::norm in modules/core/include/opencv2/core.hpp mentions enums `NORM_RELATIVE_INF`, `NORM_RELATIVE_L1` and `NORM_RELATIVE_L2`, which are not defined in the source code. It seems that the correct flags to use in those cases are `NORM_RELATIVE | NORM_INF`, `NORM_RELATIVE | NORM_L1` and `NORM_RELATIVE | NORM_L2`.

A simple compilation test will illustrate the problem:

      #include "opencv2/core.hpp"
      void foo()
      {
        cv::Mat m1, m2;
        cv::norm (m1, m2, cv::NORM_L2 | cv::NORM_RELATIVE);
        cv::norm (m1, m2, cv::NORM_RELATIVE_L2);
      }
      

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by sturkmen72** [comment]
if you have the information about cv::NormTypes could you prepare a PR filling blank informations [here]
(https://github.com/opencv/opencv/blob/a065e4b9aa119d1e3104800f0f9ef79ec8f1b73e/modules/core/include/opencv2/core/base.hpp#L188-L196)

[documentation link](http://docs.opencv.org/master/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f)

**Comment by azatsman** [comment]
I will create, probably today,  a pull request with modified documentation for `NormTypes` in `base.hpp`
