### ISSUE TITLE
CMake config file installed to wrong directory under Windows (Visual C++, 64-bit)

### ISSUE THREAD

**Issue by JPGygax68** [opencv/opencv#9355]
##### System information (version)
- OpenCV = 3.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Target architecture: x64

##### Detailed description

The `install` target of the Visual Studio project, when configured for Visual Studio 2015, 64 bit, will install config files to `${CMAKE_INSTALL_PREFIX}\`  and `${CMAKE_INSTALL_PREFIX}\x64\vc14\lib`.

This is not ideal, because it prevents a consuming CMake file from finding the config file based on the PATH environment variable. To explain: to make the OpenCV exes and dlls available, I've added `D:\Tools\x64\vc14\bin` to my PATH (`D:\Tools` being the value I've set `CMAKE_INSTALL_PREFIX` to when configuring OpenCV).

According to the search rules specified for `find_package()`, the algorithm will strip the trailing `bin` from PATH entries, then try appending several subdirectory path variations in which it will look for the package config file (see https://cmake.org/cmake/help/latest/command/find_package.html):
```
<prefix>/                                                       (W)
<prefix>/(cmake|CMake)/                                         (W)
<prefix>/<name>*/                                               (W)
<prefix>/<name>*/(cmake|CMake)/                                 (W)
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/                  (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                        (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/          (U)
<prefix>/<name>*/(lib/<arch>|lib|share)/cmake/<name>*/          (W/U)
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/                (W/U)
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (W/U)
```
With `<prefix>` being, in this case, the string `D:\Tools\x64\vc14`  obtained from the PATH. As you can see (though it's not exactly evident at one glance), that list does *not* include the `lib` subdirectory itself (which in my case would be `D:\Tools\x64\vc14\lib`) - at least one additional subdirectory level would be needed (the simplest of which being simply `\cmake`).

##### Steps to reproduce

Build and install OpenCV on Windows 10 with Visual Studio 15 configured for 64-bit, then try to consume it with:
```
find_package(OpenCV REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE ${OpenCV_LIBS})
target_include_directories(${PROJECT_NAME} PRIVATE ${OpenCV_INCLUDE_DIRS})
```

**Comment by alalek** [comment]
```
<prefix>/                                                       (W)
```

We provide `OpenCVConfig.cmake` file here.

Also build scripts may install inner config files:
```
<arch>/<vc_version>/lib
<arch>/<vc_version>/staticlib
```

The easiest way is to specify installation path of OpenCV:
```
cmake -DCMAKE_PREFIX_PATH=<opencv_install_path> ...your_application_options...
```

Also you can try to pass to CMake another value for [`OPENCV_CONFIG_INSTALL_PATH`](https://github.com/opencv/opencv/blob/3.3.0/CMakeLists.txt#L427) variable during OpenCV build.

**Comment by JPGygax68** [comment]
Yes, I saw that the config files go to `<prefix>\`, and I was able to use OpenCV by setting the `OpenCV_DIR` variable to that location.

Does that mean that the inner config files cannot / should not be used directly ?

**Comment by alalek** [comment]
Both 'root' and 'inner' config files should work fine. The 'root' config file is just a wrapper with build configuration detection/selection.

**Comment by JPGygax68** [comment]
The CMake files of OpenCV are sophisticated, and I was unable to find out where and how the EXEs and DLLs are actually being installed.

Would it make sense to install wrapper files to `<prefix>/x64/vc14/cmake/`  in addition to `<prefix>/`, so that CMake could find them from the PATH alone, without needing `OpenCV_DIR`?

I realize this might not be entirely kosher: CMake would, in that situation, regard `<prefix>/x64/vc14` as the prefix itself, which might lead to more trouble.

**Comment by alalek** [comment]
> how the EXEs and DLLs are actually being installed

Directory of binaries: `bin`

> without needing OpenCV_DIR

`CMAKE_PREFIX_PATH` works well and doesn't require additional `OpenCV_DIR`

> regard <prefix>/x64/vc14

In general, "winpack" package supports multiple build configurations:
- `x86/vc14` for 32-bit builds
- `x64/vc11` for MSVS 2012 64-bit
so there is no "single" prefix.

You can try to drop `x64/vc14` from paths via setting `-DOpenCV_INSTALL_BINARIES_PREFIX=""`. But this would work for single configuration only.

**Comment by JPGygax68** [comment]
Thank you! Indeed I have now set my `CMAKE_PREFIX_PATH` environment variable, which works well and is probably the most elegant mechanism anyway.

I'm going to close this issue, but I was wondering one more thing: what would happen if, for example, I built and installed both the 32- and the 64-bit versions (using separate build directories)?

**Comment by alalek** [comment]
Installation of 32-bit / 64-bit builds into the same OpenCV directory should work fine. Binaries are installed into separate sub-directories:
- x64/vc14
- x86/vc14
with specialized 'inner' CMake config files. The `root` CMake is able to detect the build type of the consuming application and select appropriate 'inner' configuration file.

P.S. This behavior is not native for CMake (OpenCV specific improvement). In general, It is developer's responsibility to specify path to proper CMake configuration file.

**Comment by JPGygax68** [comment]
Thank you @alalek, that confirms what I thought.  Great work.
