### ISSUE TITLE
Why aren't the cuda functions included in the release?

### ISSUE THREAD

**Issue by Ghost---Shadow** [opencv/opencv#9356]
- OpenCV =>3.3.0
- Operating System / Platform =>Windows 10 64bit
- Compiler => Visual Studio 2015 Community

##### Detailed description

I downloaded OpenCV 3.3.0 from the [GIthub releases](https://github.com/opencv/opencv/releases) and it lacks all the cuda related headers except `core/cuda.hpp`. So, I cannot use any of the other functions in the `cv::cuda` namespace.

Most tutorials build the source using CMake. Why is that necessary?

**Comment by HagegeR** [comment]
because in the CMake folder all of the optional stuff is linked to the code so that functions could use (or not) those very special features, like CUDA.

**Comment by alalek** [comment]
We don't include CUDA modules into package builds, because:
- CUDA is external dependency which should be installed on user target system
- installed CUDA version is unknown, which may cause some problems
- binaries with CUDA are too large

OpenCV library uses CMake as build configuration system.
