### ISSUE TITLE
lsd.cpp debug

### ISSUE THREAD

**Issue by nuistshenhui** [opencv/opencv#9363]
hello, I find that the codes attached here in lsd.cpp in opencv3.2 is useless. The codes aim to make the list starts by the larger bin, howerer ,it doesn't works.

    // Sort
    int idx = n_bins - 1;
    for(;idx > 0 && !range_s[idx]; --idx);
    coorlist* start = range_s[idx];
    coorlist* end = range_e[idx];
    if(start)
    {
        while(idx > 0)
        {
            --idx;
            if(range_s[idx])
            {
                end->next = range_s[idx];
                end = range_e[idx];
            }
        }
    }

**Comment by sturkmen72** [comment]
[link to source code]
(https://github.com/opencv/opencv/blob/master/modules/imgproc/src/lsd.cpp#L597-L613)

**Comment by victor-ludorum** [comment]
Hello @nuistshenhui and @alalek I want to work on this issue . As suggested by @nuistshenhui this code doesn't work . So do we have to delete this code from the [file](https://github.com/opencv/opencv/blob/3.2.0/modules/imgproc/src/lsd.cpp#L596-L612) ?? Kindly suggest me what should be done next .
