### ISSUE TITLE
Wiki Page Update

### ISSUE THREAD

**Issue by danieltak** [opencv/opencv#9375]
##### Detailed description

The wiki page has some legacy example codes that won't work on OpenCV 3.x, it is suggested that the codes are updated and/or there is a Version Label of the version used on the example, like when we post an issue.

An example is this: [How to Display more than one image in a single window](https://github.com/opencv/opencv/wiki/DisplayManyImages) which uses  IplImage, that is legacy.
@sturkmen72  made a [conversion to Mat](http://answers.opencv.org/question/82812/displaying-multiple-images/)

When you are learning OpenCV it is hard to know what versions can run which examples and the wiki page from OpenCV are on the top of the list of search engines.

**Comment by StevenPuttemans** [comment]
@mshabunin some of us Q&A mentors had wiki edit rights, but they seem to be revoked when Intel took over. Any chance we can get em back so we can update stuff like this also?

**Comment by alalek** [comment]
@StevenPuttemans Hi, The current GitHub Wiki access management has lack of support for standalone wiki editors group (wiki write access grants write access to code repository too which we would like to avoid).
Could you try to edit wiki page in your OpenCV repository fork (you should enable wiki in settings first) and publish here a link to updated docs? Then we can cherry-pick proposed changes (wiki on GitHub is just a git repository: https://github.com/opencv/opencv.wiki.git ).
BTW, Unfortunately there is no automatic sync of fork with upstream wiki.

**Comment by StevenPuttemans** [comment]
@alalek, I will try this :)

**Comment by StevenPuttemans** [comment]
Working and verified update can be found here : https://github.com/StevenPuttemans/opencv/wiki/DisplayManyImages

**Comment by alalek** [comment]
Thank you! Changes are pushed to OpenCV wiki.

**Comment by StevenPuttemans** [comment]
@alalek, I might have a look at the other ones also. Just not sure if we should maintain them there ... the example for face detection for example, can just be removed, the tutorials contain more than enough on that
