### ISSUE TITLE
opencv 3.3.0 + opencv_contrib 3.3.0 - Missing .lib file

### ISSUE THREAD

**Issue by Samega7Cattac** [opencv/opencv#9377]
I'm having some issues compiling the source code of opencv 3.3.0 with opencv_contrib 3.3.0.
The `contrib_world330d.lib` is missing from `C:\(path to opencv)\lib\debug\` and all projects fail because of it.
I only have the `contrib_world330d.pdb` file in there.
I used cmake (gui) to build opencv and the modules, and then Visual Studio 2017 to compile

**Comment by mshabunin** [comment]
@Samega7Cattac , please try to ask your question on the user forum (http://answers.opencv.org).

Probably you have to switch build configuration in Visual Studio.

**Comment by Samega7Cattac** [comment]
ok I will

**Comment by Samega7Cattac** [comment]
http://answers.opencv.org/question/172155/opencv-330-opencv_contrib-330-missing-lib-file/
