### ISSUE TITLE
createHanningWindow returns -nan values if size is 1 in any dimension

### ISSUE THREAD

**Issue by orodbhen** [opencv/opencv#9378]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Linux Mint 18.1 64 Bit
- Compiler => gcc

##### Detailed description

This is with the `Anaconda` OpenCV package. For example, the following code always creates a Hanning window with `-nan` values. Swapping dimensions does the same. Making both dims `> 1` returns numerical values, as expected. I also tried this on `Android` and `OpenCV 3.2`, with the same results. 

##### Steps to reproduce

```
 Mat hann;
 createHanningWindow(hann, Size(100, 1), CV_32F);
 printf("First element of %d hanning window is %f", numSamples, hann.at<float>(0, 0));
```

**Comment by berak** [comment]
indeed, if rows or cols is 1 [we divide by zero here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L591)
