### ISSUE TITLE
Building master results in authentication attempts against the jenkins instance building it.

### ISSUE THREAD

**Issue by jzee** [opencv/opencv#9381]
##### System information (version)
- OpenCV => master
- Operating System / Platform => Ubuntu 14.04.5 x64
- Compiler => jenkins 2.46.3

##### Detailed description
Building opencv/master results in authentication attempts against the jenkins instance building it.
Building opencv off a release tag doesn't show this effect. 

##### Steps to reproduce
Jenkins configuration file attached. 
[config.zip](https://github.com/opencv/opencv/files/1227639/config.zip)

##### Additional information
I've been building opencv on jenkins in several configurations for many months now and it all works great. Recently, we opted to also build master because there was a fix on master that we needed and 3.3-rc hadn't been created yet at this point.

So I'm checking the repo for updates once a day and launch a build if changes are detected. Everything works fine. 

Since we've been doing that, we can see users being created in the jenkins/users folder (presumably following authentication attempts). The usernames are related to the opencv project. Here are the ones that happened this morning:

> dmitry.kurtaev+github
> martin.seyferth
> steven.puttemans
> sturkmen
> ztsmn

others from recent days are

> alexander.a.alekhin
> alexander.alekhin
> alexandro88
> csukuangfj
> noreply
> pavel.rojtberg
> tomoaki.teshima

The creation timestamps of the user folders coincide with the build time of opencv master. Building any of the branches with a copy/paste configuration (only changing the refspec to be built) does not do that - only master does. 

The builds are executed on stateless buildslaves that, as far as I can tell, have no link to the master other than  the environment variable JENKINS_URL (against which the presumed authentication attempts happen) and running a quick search through the repo did not yield an access to that variable in the build process. 

Appreciate any help in investigating this.

**Comment by mshabunin** [comment]
@jzee , AFAIK Jenkins create users from e-mails in commit history. Check the "Changes" section of your build, it should have references to the mentioned users.

**Comment by jzee** [comment]
nice! :+1:  - thanks a bunch for the reply.
