### ISSUE TITLE
opencv2/xfeatures2d/cuda.hpp no such file or directory

### ISSUE THREAD

**Issue by ambikaverma** [opencv/opencv#9385]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform =>Windows 64 Bit
- Compiler => MinGW (CodeBlocks)
##### Detailed description

Downloaded and extracted openCV 3.2 and opencv_contrib 3.2 version. Used Cmake GUI to go through standard steps. It configures and generates without error. 
Then while building openCV.cbp project in CodeBlocks I get the following error in stitching module -

opencv2/xfeatures2d/cuda.hpp no such file or directory

##### Steps to reproduce

Note: if I build openCV 3.2 on its own (i.e. without the extra modules) it builds perfectly fine.

Any fix for this issue?

**Comment by alalek** [comment]
Try latest OpenCV release (3.3) and check for CMake download faults: https://github.com/opencv/opencv_contrib/issues/1131

**Comment by SeanKelker** [comment]
OpenCV removed some modules and algorithms that had patents on them. xfeatures2d/cuda.hpp was one of them with the SURF feature detection. You have to recompile OpenCV with the OpenCV_contrib modules included. There are instructions on how to do this on the OpenCV_contrib repository.
