### ISSUE TITLE
Build for iOS fails (log attached)

### ISSUE THREAD

**Issue by daquexian** [opencv/opencv#9386]
[log](http://quexian.me/log.txt)

I simply run build_framework.py, and it failed. Could you please help me to solve this problem?

Thanks in advance.

**Comment by daquexian** [comment]
I builded it on macOS 10.12.6

**Comment by alalek** [comment]
> /usr/local/bin/libtool

Invalid tool in your PATH. Build environment seems broken. You should use system tool instead.

```
$ which libtool
/usr/bin/libtool
```

**Comment by daquexian** [comment]
@alalek Sorry, but I do get `/usr/local/bin/libtool` when I run `which libtools`

**Comment by alalek** [comment]
This is a reason of this issue: wrong tool replaces normal `libtool`. You should eliminate it yourself.
