### ISSUE TITLE
Reference to non-existent parameter name in documentation of StereoSGBM::create

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9392]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => -
- Compiler => -

##### Detailed description

The documentation for [StereoSGBM::create](http://docs.opencv.org/3.3.0/d2/d85/classcv_1_1StereoSGBM.html#adb7a50ef5f200ad9559e9b0e976cfa59) mentions `SADWindowSize` which is not a parameter of the constructor:

> See stereo_match.cpp sample where some reasonably good P1 and P2 values are shown (like 8\*number_of_image_channels\*SADWindowSize\*SADWindowSize and 32\*number_of_image_channels\*SADWindowSize\*SADWindowSize , respectively).

I suppose that is due to the fact that the parameter `blockSize` was called `SADWindowSize` in OpenCV 2.4.0 (cf. http://docs.opencv.org/2.4.0/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#stereosgbm-stereosgbm). Maybe the documentation in the current version should be updated to avoid confusion. This seems to have been introduced with OpenCV 3.0.

##### Steps to reproduce

Replace `SADWindowSize` with `blocksize` in the documentation of `StereoSGBM::create`.

**Comment by saskatchewancatch** [comment]
@dustsigns Not too familiar with this area, but just taking a quick look, does `cv::getValidDisparityROI`'s SADWindowSize deserve to be renamed to blockSize if it's related to `StereoSGBM`?

**Comment by dustsigns** [comment]
It seems so, but maybe someone more experienced with the use of this function should be the judge of that.

**Comment by sturkmen72** [comment]
you can provide a PR by correcting https://github.com/opencv/opencv/blob/master/modules/calib3d/include/opencv2/calib3d.hpp#L1942-L1943

**Comment by alalek** [comment]
Lets do this:

> replacing `SADWindowSize` with ~~`blocksize`~~ `blockSize`

in public headers only:

> modules/calib3d/include
