### ISSUE TITLE
build issue with OpenCV 3.3

### ISSUE THREAD

**Issue by arifle** [opencv/opencv#9396]
##### System information (version)

Only one error 
151>LINK : fatal error LNK1104: cannot open file “python27_d.lib”
Is this the problem of python version which is 2.7 here.

**Comment by alalek** [comment]
You need to install development Python **debug** library.
Perhaps you don't need "Debug" build of OpenCV, so try to build in "Release" mode instead.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
