### ISSUE TITLE
Mac Os X Installation

### ISSUE THREAD

**Issue by augmen** [opencv/opencv#9399]
Guide us on installing OpenCV MacOSX ? we are  using python 2.7 & numPy for the Embeded vision . we are using home-brew + pip as package manager. Thanks

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by augmen** [comment]
the user Q/A forum doesn't macosx installation package. can we have the direct link for unix packages.

**Comment by augmen** [comment]
do i need use Make for the installation ?
