### ISSUE TITLE
Allow negative values for setTrackbarMin

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9403]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.04 (x86-64) with QT 5
- Compiler => g++ 5.4.0

##### Detailed description

`setTrackbarMin` currently ignores negative parameters, making it impossible to set a negative minimum for a trackbar when using QT. The latter's `QSlider` which OpenCV relies on does not seem to have such a restriction (or, if so, it is also undocumented, cf. http://doc.qt.io/qt-5/qabstractslider.html#minimum-prop). If OpenCV keeps this restriction (`minval` needs to be positive) for compatibility (or other reasons), it should be mentioned in the documentation.

##### Steps to reproduce

There is currently no code path for the opposite case of
https://github.com/opencv/opencv/blob/316fb26f5badb2cbb3cff3dfbc284dcc29115759/modules/highgui/src/window_QT.cpp#L691

**Comment by dustsigns** [comment]
@alalek: Since you labeled this a feature, is there a reason why the positivity check is in the code in the first place? From a quick look, the GTK backend, for example, just passes the minimum value (positive or negative) through without checking.

**Comment by alalek** [comment]
I have no answer on "why" question. But I don't see any real reasons to just ignore passed negative values.

Regarding GTK backend - I have updated it several days ago ( #9369 ) and saw similar issue. GTK, for example, works fine with negative values too.

**Comment by dustsigns** [comment]
Sorry for the misunderstanding. My question was: why is this categorized as a feature and not as a bug? Currently, the QT backend silently ignores negative values, unlike, e.g., the GTK backend.

**Comment by alalek** [comment]
Sorry for my misunderstanding. I mean "feature" here - "support negative values". Also it can be classified as a "bug" ("stop silently ignore negative values").

**Comment by saskatchewancatch** [comment]
Similarly, why is `setTrackbarMax` ignoring negative values?

What if the range of some algorithm's parameter is between -2 to -1? In this case it would seem natural to set the trackbar min to -2 and the trackbar max to -1.

Looking at the QtSlider documentation, it looks like Qt is smart enough to adjust the range if min > max, and that `window_QT.cpp` shouldn't have to worry about checking if min < max in either `setTrackbarMin` or `setTrackbarMax`.

A possible solution is to just remove the 2 `if` checks in [window_QT.cpp](https://github.com/opencv/opencv/blob/master/modules/highgui/src/window_QT.cpp), [here](https://github.com/opencv/opencv/blob/master/modules/highgui/src/window_QT.cpp#L676) and [here](https://github.com/opencv/opencv/blob/master/modules/highgui/src/window_QT.cpp#L691).

@alalek, does this sound sane to you? If yes, I can submit a PR.

@dustsigns, would you be interested in trying out a PR that contains such a fix?

**Comment by dustsigns** [comment]
@saskatchewancatch: Of course.

**Comment by saskatchewancatch** [comment]
@dustsigns 

Please give #9498 a try if the build test passes. Let us know if it works out.

It would be of interest to know what Qt does when max < min and whether behaviour is satisfactory.

**Comment by dustsigns** [comment]
It works for me.

**Comment by huatson** [comment]
working excellent, i needed on my project too !

**Comment by BYEONGGILYOO** [comment]
Hi
I have compiled with the above commit, but zero is the minimum.
I just added VTK7 and extra modules in cmake.
```
void onTrackbar(int, void*)
{
	
}

void trackbar_thread(int* degree, int* translation)
{
	cv::namedWindow("trackbar", cv::WINDOW_AUTOSIZE);
	cv::createTrackbar("degree", "trackbar", degree, 0, onTrackbar);
	cv::setTrackbarMax("degree", "trackbar", 180);
	cv::setTrackbarMin("degree", "trackbar", -180);
	cv::setTrackbarPos("degree", "trackbar", 30);

	cv::createTrackbar("x-translation", "trackbar", translation, 0, onTrackbar);
	cv::setTrackbarMax("x-translation", "trackbar", 100);
	cv::setTrackbarMin("x-translation", "trackbar", -99);
	cv::setTrackbarPos("x-translation", "trackbar", -12);

	while (1)
	{
		*degree = cv::getTrackbarPos("degree", "trackbar");
		*translation = cv::getTrackbarPos("translation", "trackbar");
		cv::waitKey(30);
	}
}
```
