### ISSUE TITLE
Copy-paste error in parameter description (documentation) of setTrackbarMin

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9404]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => -
- Compiler => -

##### Detailed description

The parameter `minval` of `setTrackbarMin` is documented as (http://docs.opencv.org/3.3.0/d7/dfc/group__highgui.html#gabe26ffe8d2b60cc678895595a581b7aa)
> New maximum position.

I suppose that this is a copy-paste error from the documentation of `setTrackbarMax` (http://docs.opencv.org/3.3.0/d7/dfc/group__highgui.html#ga7e5437ccba37f1154b65210902fc4480).

##### Steps to reproduce

Suggestion: Change the description of `minval` to
> New minimum position.

or something similar.

**Comment by varshav21** [comment]
hi can i take up this issue as my first pr?

**Comment by alalek** [comment]
There is already PR for this - check link above your comment : #9429.

**Comment by varshav21** [comment]
oops sorry i will look for some other issue to start contributing.
