### ISSUE TITLE
macOS build error with opengl_interop

### ISSUE THREAD

**Issue by eruffaldi** [opencv/opencv#9422]
- OpenCV 3.3 HEAD
- Platform: macOS
- Compiler: clang 8.0.0
- Configuration: QT + VTK + OpenGL + CUDA

Building error due to return and missing flag

Pull Request ready

**Comment by alalek** [comment]
Could you check for this [message](https://github.com/opencv/opencv/blob/3.3.0/samples/opengl/CMakeLists.txt#L4) during CMake run?

**Comment by eruffaldi** [comment]
No it is not printed because X11 dev files are present. The opengl_interop.cpp is meant only for Windows and Linux due to the __linux__ and _WIN32 checks. X11 could run in macOS although it is not so common.

Using BUILD_EXAMPLES WITH_QT and WITH_OPENGL prints only the report:
--   GUI: 
--     QT 5.x:                      YES (ver 5.9.1)
--     QT OpenGL support:           YES (Qt5::OpenGL 5.9.1)
--     OpenGL support:              YES (/System/Library/Frameworks/OpenGL.framework)
--     VTK support:                 YES (ver 8.0.0)

Without WITH_QT=ON the WITH_OPENGL has no effect due to a check in OpenCVFindLibsGUI.cmake "(HAVE_QT AND QT_QTOPENGL_FOUND)".

**Comment by alalek** [comment]
Perhaps it is better to exclude these files completely instead (to prevent users confusion). Could you add something like this into mentioned CMakeFiles.txt?
```
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin") # MacOS X
    return()
endif()
```

**Comment by eruffaldi** [comment]
I totally agree. Adding OpenGL for macOS would require much effort without a good reason.
