### ISSUE TITLE
running sudo make install leaves junk owned by root

### ISSUE THREAD

**Issue by Goddard** [opencv/opencv#9425]
I built opencv from source and did a sudo make install on ubuntu and in my build directory it leaves files owned as root.

Running make clean doesn't remove them.  How can I remove them without loosing my cmake configuration?

**Comment by alalek** [comment]
from the build directory try `sudo chown -R <user>:<group> ./`

Anyway `make clean` will not remove "installed" files. You need `make uninstall` (perhaps with sudo).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
