### ISSUE TITLE
Deep networks visualization

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#9452]
##### Proposal
Add functionality to visualizing topology of network.

Two ways are possible: console output and torch-like `graphviz` visualization.

- **Console output**
  - Preferable for small architectures or for selected parts of networks. It's also useful for testing because our unit tests are based on few-layers networks.
  - Might looks like ```std::cout << net << std::endl;``` similarly for `cv::Mat` printing. However single method is more flexible for managing different levels of detalization (hyperparameters, input/output shapes, backend, fusion etc.). Minimal level of detalization may includes just layer types and connections, though.
  - Connections between layers seems to be a key issue because it requires appropriate indentation.

- **graphviz**
  - Easier than console printing. We just write text file with `.dot` graph. In example, 
    ```dot
    strict digraph sample {
      node1->node2
      node1->node3
      node2->node3
    }
    ```
    may be rendered into .png:
    ```bash
    dot -Tpng graph.dot > graph.png
    ```
    ![simple_graph](https://user-images.githubusercontent.com/25801568/29630699-b4bc6090-8845-11e7-8449-d15c515a8c94.png)

  - It has dozens of settings. Torch and supposedly Caffe use is for visualization. 

**Misc**: this project looks pretty nice for me: http://ethereon.github.io/netscope/quickstart.html

**Comment by StevenPuttemans** [comment]
Thanks for the pointers on the .dot graph thing :) comes in handy when writing a dissertation ^_^

**Comment by berak** [comment]
out of curiosity, i tried a [console based attempt](https://gist.github.com/berak/3791a288d2824a71ff783d1f99ed459d) , but ran into some obstacles:

* you need to know the input shape, but cannot ask the Net for it (it does not remember, even though a pretrained model was imported a second ago)
* it does not even know, how many layers it has (well, net.getLayerNames() + 1;, the input layer is a weird beast, imho)
* there's no way (at All) to retrieve the connectivity information.

sure, it gets a lot easier, if there is a (human readable) prototxt, but e.g. tensorflow graphs come as a huge, binary chunk

**Comment by alalek** [comment]
There is nice browser-based tool for inspection of Caffe networks: http://dgschwend.github.io/netscope/quickstart.html

**Comment by RadZaeem** [comment]
Anyone still working on this?
Can I take this issue

**Comment by vpn1997** [comment]
http://fabrik.cloudcv.org/ Fabrik also offers visualisation of the model given Json or protext file.

**Comment by akhandait** [comment]
@dkurt Has someone already added this feature or can I work on it?
If I can, can you please guide me on how to go about this?
I am familiar with Caffe and just checked out graphviz.

**Comment by dkurt** [comment]
An issue has been implemented by @l-bat, Thanks! Feel free to test and provide your feedback. See `cv::dnn::dumpToFile`.

**Comment by aimhabo** [comment]
Just worrying about not finding a blob.
