### ISSUE TITLE
update libjpeg to 9b

### ISSUE THREAD

**Issue by paleozogt** [opencv/opencv#9453]
##### System information (version)

- OpenCV => master (`3.3.0-81-gc248794`)
- Operating System / Platform => n/a
- Compiler => n/a

##### Detailed description

According to http://ijg.org/, the latest libjpeg is `9b`.  

##### Steps to reproduce

`head 3rdparty/libjpeg/README` shows `README for release 9 of 13-Jan-2013`

**Comment by Rajiv2605** [comment]
Can I work on this issue?

**Comment by alalek** [comment]
@Rajiv2605 There is already ongoing patch: #9454 (check for link above your comment)

**Comment by paleozogt** [comment]
@Rajiv2605 some help figuring out why the build is failing for windows would be appreciated

**Comment by alalek** [comment]
BTW, Linux/Mac builds use libjpeg from system packages - this source code is not used.

**Comment by Rajiv2605** [comment]
@paleozogt :+1: I'll look into it.

**Comment by Rajiv2605** [comment]
Is this the error while building in windows?
[build_error.txt](https://github.com/opencv/opencv/files/1258004/build_error.txt)

**Comment by alalek** [comment]
Current build failure is [here](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/12140). 
The latest status is available on http://pullrequest.opencv.org/ for PR 9454

**Comment by sturkmen72** [comment]
Libjpeg is updated.
