### ISSUE TITLE
Unknown layer type in tf_importer.cpp while running import->populateNet(Net)

### ISSUE THREAD

**Issue by littlesun96** [opencv/opencv#9459]
##### System information (version)

- OpenCV => 3.3 (c9fe702671476cb1552c4dae25a7ed827beeba9d)
- Operating System / Platform =>Windows 10 Pro, x64 (but I build program for x86)
- Compiler => Visual Studio 2013

##### Detailed description

@dkurt ,
I'm working with model with LSTM, trained in Keras (2.0.4) using Tensorflow (1.2.0) backend, and I have the issue "OpenCV Error: Unspecified error (Unknown layer type StridedSlice in op lstm_1/strided_slice)"

It doesn't match any condition and reproduce an error in `tf_importer.cpp` in line 883:
```
else
        {
            printLayerAttr(layer);
            CV_Error_(Error::StsError, ("Unknown layer type %s in op %s", type.c_str(), name.c_str()));
        }
```

The network was built like this:
```
from keras.layers import Input, LSTM, Dense
from keras.models import Model

main_input = Input(shape=(seq_len,3), name='main_input')
lstm_out = LSTM(20, return_sequences=False, input_shape=(seq_len,3))(main_input)
label_out = Dense(1, activation = 'sigmoid', name = 'label_output')(lstm_out)
model = Model(inputs = [main_input], outputs = [label_out])
```

Using scripts `freeze_graph.py` and `optimize_for_inference.py` doesn't help.

**Comment by dkurt** [comment]
@littlesun96, There is a PR that add BlockLSTM node parsing: https://github.com/opencv/opencv/pull/9491. Also you may find a test case at https://github.com/opencv/opencv_extra/pull/368.
Is it possible for your model use non-Keras layers? Or combine it somehow?

**Comment by littlesun96** [comment]
@dkurt, Now I can't use scripts `freeze_graph.py`. 
`freeze_graph.py` gives an error
```
...
  File "freeze_graph.py", line 87, in freeze_graph_with_def_protos
    _ = importer.import_graph_def(input_graph_def, name="")
  File "C:\Users\yusacheva\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tensorflow\python\framework\importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named BlockLSTM in defined operations.
```
If I try to use graph without freezing, I get an error
```
lstm_block_wrapper/zeros:Fill(lstm_block_wrapper/stack)(lstm_block_wrapper/zeros/Const)
T:0
OpenCV Error: Unspecified error (Unknown layer type Fill in op lstm_block_wrapper/zeros) in cv::dnn::experimental_dnn_v1::`anonymous-namespace'::TFImporter::populateNet
```

**Comment by dkurt** [comment]
@littlesun96, you are right, there is a solution https://github.com/tensorflow/tensorflow/issues/11847#issuecomment-324649064 for now. I think we could find more simple way further.

**Comment by littlesun96** [comment]
@dkurt, I successfully used scripts `freeze_graph.py` , `optimaze_for_inference`. Also I tried to use your `prepare_for_dnn.py` script, but I still get an error
```
lstm_block_wrapper/zeros:Fill(lstm_block_wrapper/stack)(lstm_block_wrapper/zeros/Const)
T:0
OpenCV Error: Unspecified error (Unknown layer type Fill in op lstm_block_wrapper/zeros) in cv::dnn::experimental_dnn_v1::`anonymous-namespace'::TFImporter::populateNet
```

**Comment by littlesun96** [comment]
@dkurt, I'm sorry, it was my mistake
I've passed through it, but now get an error
```
lstm_block_wrapper/Shape_1:Shape(input)
T:0
out_type:[ ]
OpenCV Error: Unspecified error (Unknown layer type Shape in op lstm_block_wrapper/Shape_1) in cv::dnn::experimental_dnn_v1::`anonymous-namespace'::TFImporter::populateNet
```

**Comment by dkurt** [comment]
@littlesun96, Could you please reproduce this steps?

1. Export graph and checkpoint
```python
import tensorflow as tf
import numpy as np

sess = tf.Session()

# Build
times = 4  # Sequence length (number of batches in different time stamps)
batch_size = 2
input_size = 5*6*3  # W*H*C
output_size = 10
inp = tf.placeholder(tf.float32, [times, batch_size, input_size], 'input')
lstm_cell = tf.contrib.rnn.LSTMBlockFusedCell(output_size, forget_bias=0.9,
                                              cell_clip=0.4, use_peephole=True)
outputs, state = lstm_cell(inp, dtype=tf.float32)
relu = tf.nn.relu(outputs)

# Run
sess.run(tf.global_variables_initializer())

inputData = np.random.standard_normal(inp.shape).astype(np.float32)
outputData = sess.run(relu, feed_dict={inp: inputData})

# Save
saver = tf.train.Saver()
saver.save(sess, 'lstm.ckpt')
tf.train.write_graph(sess.graph.as_graph_def(), "", "lstm_graph.pb")
```

2. Freeze graph (replace variables at graph to constants from checkpoint)
```bash
python ~/tensorflow/tensorflow/python/tools/freeze_graph.py \
  --input_graph=lstm_graph.pb \
  --input_checkpoint=lstm.ckpt \
  --output_graph=lstm_frozen.pb \
  --output_node_names=Relu
```

3. Call optimize for inference tool
```bash
python ~/tensorflow/tensorflow/python/tools/optimize_for_inference.py \
  --input lstm_frozen.pb \
  --output lstm_opt.pb \
  --frozen_graph True \
  --input_names input \
  --output_names Relu
```

4. Call the function `simplify_lstm` from https://github.com/opencv/opencv_extra/pull/368/files.
5. Load the last one graph using DNN.

If you would have troubles with some of points, please let us know.

**Comment by littlesun96** [comment]
@dkurt, it works. Seems, I have troubles with building my network in TF.
Many thanks!

**Comment by littlesun96** [comment]
Hello, @dkurt.
When we  use LSTM, we get a sequence of outputs. In your code above, as you know, `outputs` in line `outputs, state = lstm_cell(inp, dtype=tf.float32)` contains `times` elements, result of lstm after processing every sequence element. But if I want only the last output I used `outputs[-1]` or `outputs[times - 1]` to take a slice of tensor, and get error:
`Unspecified error (Unknown layer type StridedSlice in op strided_slice)`
Is it possible to get it differently, without getting error?

**Comment by dkurt** [comment]
@littlesun96, thanks for the remark! Try to use `tf.slice`:
```python
inp = tf.placeholder(tf.float32, [times, batch_size, input_size])
lstm_cell = tf.contrib.rnn.LSTMBlockFusedCell(output_size)
outputs, state = lstm_cell(inp, dtype=tf.float32)
last_output = tf.slice(outputs, [times - 1, 0, 0], [1, batch_size, output_size])
```

**Comment by littlesun96** [comment]
@dkurt, thanks for quick response!
In my network, after lstm I need to take these `output_size` (10 in this example) elements and put there weighted versions to `sigmoid`. So I used this code to do it:
```
weights = {
    'lstm': tf.Variable(tf.random_normal([1, 20, 2]))
}
biases = {
    'lstm': tf.Variable(tf.random_normal([1, 2]))
}
...
sigmoid = tf.nn.sigmoid(tf.matmul(last_output, weights['lstm']) + biases['lstm'])
```
and now opencv says me 
```
MatMul:BatchMatMul(Slice)(Variable)
T:0
adj_y:[ ]
adj_x:[ ]
OpenCV Error: Unspecified error (Unknown layer type BatchMatMul in op MatMul) in cv::dnn::experimental_dnn_v1::`anonymous-namespace'::TFImporter::populateNet
```
Can you please say, how can I get around that?

**Comment by dkurt** [comment]
@littlesun96, I would like to propose the next way:
1. As before, make an LSTM subgraph:
```python
inp = tf.placeholder(tf.float32, [times, batch_size, input_size], 'input')
lstm_cell = tf.contrib.rnn.LSTMBlockFusedCell(output_size, forget_bias=0.9,
                                              cell_clip=0.4, use_peephole=True)
outputs, state = lstm_cell(inp, dtype=tf.float32)
```
2. Then make a slice of the last time iteration. Note that we use `-1` size for batch dimension because hyperparameters should be batch size independent.
```python
last_output = tf.slice(outputs, [times - 1, 0, 0], [1, -1, output_size])
```
3. At this point, `last_output` has shape `(1, 2, 10)`. We should remove a time axis.
```python
last_output = tf.reshape(last_output, [-1, 10])
```
4. Now we can pass it to fully-connected layer
```python
sigmoid = tf.nn.sigmoid(tf.matmul(last_output, weights) + biases)
```
Please, update you local branch according to changes that were made for it. And thank you for the contribution!

**Comment by littlesun96** [comment]
@dkurt, thank you!
`populateNet(Net)` works now, without errors.
But I have another question. 
How should I represent my data to use predict in .cpp ?
I should convert data to `cv::Mat`, as a picture, shouldn't I?
If I do something like
```
...
importer->populateNet(net);
importer.release();

std::vector<cv::Mat> images;
for (int i = 0; i < 4; i++)
{
	images.push_back(cv::Mat(2, 5*6*3, CV_32F, cv::Scalar(0)));
}
cv::Mat blob = cv::dnn::blobFromImages(images);
net.setInput(blob, "input");
cv::Mat result = net.forward("Relu");
```
But I get an error
`Assertion failed (inp0.size() >= 2 && total(inp0, 2) == _numInp) in cv::dnn::LSTMLayerImpl::getMemoryShapes` 
while runing `net.forward`  in line 194 in `recurrent_layers.cpp`
```
int _numTimeStamps, _numSamples;
if (useTimestampDim)
{
    CV_Assert(inp0.size() >= 2 && total(inp0, 2) == _numInp);
    _numTimeStamps = inp0[0];
    _numSamples = inp0[1];
    outResShape.push_back(_numTimeStamps);
}
```

**Comment by dkurt** [comment]
@littlesun96, `blobFromImage` makes 4D canonical blob (NCHW). Above it's a batch of x4 single channel images with number of rows 2 and number of columns `5*6*3`. So `blob` has shape 4x1x2x90. Problem is in interpretation of dimensions.

Solution 1:
I think the simplest solution is a single input `cv::Mat` with size 4x2x90 that may be allocated by http://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#ad20a78b5501fc39543a240142a40e234. Just pass it in `setInput` without `blobFromImages`.

Solution 2:
Every `Mat` in batch should has only one dimension but 2 channels, like `Mat({5*6*3}, CV_32FC2)`.

Anyway, please check that input of net has `4x2x90` shape (batch x time x spatial).

**Comment by littlesun96** [comment]
@dkurt,
Solution 1:
```
std::vector<int> size = { 4, 2, 90 };
cv::Mat inp(size, CV_32F, cv::Scalar(0));
net.setInput(inp, 'input');
cv::Mat result = net.forward("Relu");
```
and I get an error `out of range` when pass layers[2] (Slice) in line 1371 in `dnn.cpp`:
```
void getLayerShapesRecursively(int id, LayersShapesMap& inOutShapes)
{
    std::vector<LayerPin>& inputLayerIds = layers[id].inputBlobsId;
    if (inOutShapes[id].in.empty())
    {
        for(int i = 0; i < inputLayerIds.size(); i++)
        {
            int layerId = inputLayerIds[i].lid;
            LayersShapesMap::iterator it = inOutShapes.find(layerId);
            if (it == inOutShapes.end() || it->second.out.empty())
            {
                getLayerShapesRecursively(layerId, inOutShapes);
             }
             const MatShape& shape = inOutShapes[layerId].out[inputLayerIds[i].oid]; // this line
``` 

-> Anyway, please check that input of net has 4x2x90 shape (batch x time x spatial).
batch = 2 and time = 4, or I'm wrong?

We have batch of sequences, each is (`time` x `input`) - 90 numbers in each time ticks?

**Comment by dkurt** [comment]
@littlesun96, You're right. In our example, batch size is `2`, number of iterations is `4` and spatial size is `90`. So input has shape `2x4x90`.

**Comment by dkurt** [comment]
@littlesun96, You're right. `times x batch x spatial`, (4x2x90).
Please, could you show a `tf.slice` arguments or a part of network from LSTM up to ReLU?

**Comment by littlesun96** [comment]
@dkurt, here
```
lstm_cell = tf.contrib.rnn.LSTMBlockFusedCell(output_size, forget_bias=0.9, cell_clip=0.4, use_peephole=True)
outputs, state = lstm_cell(inp, dtype=tf.float32)
last_output = tf.slice(outputs, [times - 1, 0, 0], [1, -1, output_size])
last_output = tf.reshape(last_output, [-1, output_size])
relu = tf.nn.relu(last_output)
```

without weights and biases, because when I write them like this:
```
weights = {
    'lstm': tf.Variable(tf.random_normal([10, 1]))
}
biases = {
    'lstm': tf.Variable(tf.random_normal([1]))
}
...
relu = tf.nn.relu(tf.matmul(last_output, weights['lstm']) + biases['lstm'])
```
I get an error in tf.importer -> populateNet `Assertion failed (size == (int)dstBlob.total())` in
```
        else if (type == "BiasAdd" || type == "Add")
        {
            bool haveConst = false;
            for(int ii = 0; !haveConst && ii < layer.input_size(); ++ii)
            {
                Pin input = parsePin(layer.input(ii));
                haveConst = value_id.find(input.name) != value_id.end();
            }
            CV_Assert(!haveConst || layer.input_size() == 2);

            if (haveConst)
            {
                layerParams.blobs.resize(1);
                blobFromTensor(getConstBlob(layer, value_id), layerParams.blobs[0]); // this line
```
but in my own network, it works

**Comment by dkurt** [comment]
@littlesun96, oh, I see. The fix of it in progress (https://github.com/opencv/opencv/pull/9517). Just few lines are required: https://github.com/opencv/opencv/pull/9517/files#diff-c6e561028becbce9ec212c49506ce60dR625. May I ask you to apply the whole patch or just retry with this piece of code?

**Comment by littlesun96** [comment]
@dkurt, thanks, it helps with weights, but what about `out of range` when pass layers[2] (Slice) in line 1371 in `dnn.cpp` as written before?

Solution 2:
`blobsFromImages` doesn't work with 2 channels images, does it?

**Comment by dkurt** [comment]
@littlesun96, We've updated TensorFlow importer so now it works for me:

1. Get the graph
```python
import tensorflow as tf

times = 4
batch_size = 2
input_size = 5*6*3
output_size = 10

inp = tf.placeholder(tf.float32, [times, batch_size, input_size], 'input')
lstm_cell = tf.contrib.rnn.LSTMBlockFusedCell(output_size, forget_bias=0.9, cell_clip=0.4, use_peephole=True)
outputs, state = lstm_cell(inp, dtype=tf.float32)
last_output = tf.slice(outputs, [times - 1, 0, 0], [1, -1, output_size])
last_output = tf.reshape(last_output, [-1, output_size])

weights = {
    'lstm': tf.Variable(tf.random_normal([10, 1]))
}
biases = {
    'lstm': tf.Variable(tf.random_normal([1]))
}
relu = tf.nn.relu(tf.matmul(last_output, weights['lstm']) + biases['lstm'])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    saver.save(sess, 'lstm.ckpt')
    tf.train.write_graph(sess.graph.as_graph_def(), "", 'lstm_graph.pb')
```

2. Freeze the graph (see https://github.com/opencv/opencv/issues/9459#issuecomment-326287052)
3. Optimize (see https://github.com/opencv/opencv/issues/9459#issuecomment-326287052)
4. Transform
```python
import os

def simplify_lstm(tool, in_graph, out_graph, in_node, out_node):
    # Get all BlockLSTM nodes names.
    lstm_names = []
    with tf.gfile.FastGFile(in_graph) as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        for node in graph_def.node:
            if node.op == 'BlockLSTM':
                lstm_names.append(node.name)

        # BlockLSTM returns tuple of tensors (i, cs, f, o, ci, co, h)
        # where output is h (6th tensor). So we replace an every reference to
        # an lstm_node_name:6 onto just an lstm_node_name.
        for node in graph_def.node:
            for i in range(len(node.input)):
                for name in lstm_names:
                    if node.input[i] == name + ':6':
                        node.input[i] = name
        tf.train.write_graph(graph_def, "", out_graph, as_text=False)

    if lstm_names:  # There is at least one lstm block.
        os.system(tool + ' --in_graph=' + out_graph + \
                         ' --out_graph=' + out_graph + \
                         ' --inputs=' + in_node + \
                         ' --outputs=' + out_node + \
                         ' --transforms="remove_nodes(op=Cast) '
                         'rename_op(old_op_name=Fill, new_op_name=Const)"')

simplify_lstm('/home/dkurtaev/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph',
              'lstm_opt.pb', 'lstm_for_dnn.pb', 'input', 'Relu')
```
5. Run
```cpp
#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>

int main(int argc, char** argv) {
  cv::dnn::Net net = cv::dnn::readNetFromTensorflow("../lstm_for_dnn.pb");

  cv::Mat input({4, 2, 90}, CV_32FC1);
  net.setInput(input);
  net.forward();
  return 0;
}
```

Looks like there is no difference in these steps relative to the previous comments. Just for keeping all stuff in the same place.

**Comment by littlesun96** [comment]
@dkurt, It works! Many-many thanks for your help! =)

**Comment by dkurt** [comment]
@littlesun96, thank you for the detailed problem explanation! We'll glad to see you contribution again! Have you any references to models that use LSTM or other recurrent layers from TensorFlow? Maybe tracking or detection models? I think real model support will be more challenging rather separate layers.

**Comment by zjLeung** [comment]
I have trouble with transforming Graph to .pb (in FaceNet), make me crazy.

**Comment by tsvetiko** [comment]
You need to make sure your graph contains the Tensorflow operations defined in OpenCV DNN module:

> 
Conv2D, SpaceToBatchND, DepthwiseConv2dNative, Pad, BiasAdd, Add, Sub, MatMul, Reshape, Flatten, Squeeze, Transpose, Const, LRN, Concat, ConcatV2, MaxPool, AvgPool, Placeholder, Split, Slice, Mul, FusedBatchNorm, Conv2DBackpropInput, BlockLSTM, ResizeNearestNeighbor, ResizeBilinear, L2Normalize, PriorBox, Softmax, CropAndResize, Mean, ClipByValue, Abs, Tanh, Sigmoid, Relu, Elu, Identity, Relu6

So add the following to the `keepOps` list in the `createSSDGraph` method in the [text graph file](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py) used for freezing:

```
'SpaceToBatchND', 'MatMul', 'Reshape', 'Flatten', 'Squeeze', 'Transpose', 'Const', 'LRN', 
'Concat', 'Split', 'Slice', 'Conv2DBackpropInput', 'BlockLSTM', 'ResizeBilinear', 'L2Normalize', 
'PriorBox', 'Softmax', 'CropAndResize', 'Mean', 'ClipByValue', 'Abs', 'Tanh', 'Sigmoid', 'Elu'
```
