### ISSUE TITLE
Possible Bug in Maxpooling layer in dnn module

### ISSUE THREAD

**Issue by kvmanohar22** [opencv/opencv#9471]
I'm using dnn module to load trained models from caffe. I encountered this bug while feeding same image to both the caffe network and using dnn module. The output of pool layer for the same input is lot different. Could there be a possible bug in the implementation of Pool layer (Max Pool).

**Comment by dkurt** [comment]
Please, get acquainted with sample at https://github.com/opencv/opencv/issues/9427#issuecomment-323938598. If it doesn't work with your models, let us know.

**Comment by kvmanohar22** [comment]
@dkurt  I did try out the one you provided in the link. 
The underlying problem seems to be with `cv::imread`. When I print out the pixel values which are read by caffe and the ones read by `opencv's dnn module`, there is a difference in the pixel values and that's causing all the difference.

Here is the code of reading the image.

```cpp
    
Mat getMean(const size_t& h, const size_t& w)
{
    Mat mean;

    const int mean_values[3] = {104, 117, 123};
    vector<Mat> mean_channels;
    for(size_t i = 0; i < 3; i++)
    {
        Mat channel(h, w, CV_32F, Scalar(mean_values[i]));
        mean_channels.push_back(channel);
    }
    cv::merge(mean_channels, mean);
    return mean;
}

Mat preprocess(const Mat& image)
{
    Mat preprocessed;
    size_t width = 416;
    size_t height = 416;
    image.convertTo(preprocessed, CV_32FC3);
    resize(preprocessed, preprocessed, Size(width, height));

    Mat mean = getMean(width, height);
    cv::subtract(preprocessed, mean, preprocessed);

    return preprocessed;
}

  Mat img = cv::imread(test_input_image);
    if (img.empty()) {
        std::cerr << "Couldn't load image: " << test_input_image << "\n";
        return -2;
    }
 Mat final_img = preprocess(img);
 Mat inputBlob = blobFromImage(final_img, 1.0, Size(), Scalar(), false);


```

**Comment by dkurt** [comment]
@kvmanohar22, let's make it more productive.

Use the sample to pass **the same** input into Caffe and DNN frameworks. All that you need is just replace size of input image, paths to `.prototxt` and `.caffemodel`. Receive both outputs and make `absdiff` to check the correctness.

If you can't to do it by yourselves, provide links to model and input image here. We can't reproduce thing that you call a **possible bug** without all necessary conditions of experiments you did.

**Comment by kvmanohar22** [comment]
@dkurt The model which I'm running doesn't belong to image classification but rather to object detection. To infer the final output, there are three blobs which contribute to the output.

You can have look at the `*.prototxt file` [here](https://github.com/kvmanohar22/opencv_contrib/blob/GSoC17_dnn_objdetect/modules/dnn_objdetect/proto/SqueezeDet_deploy.prototxt)

**Comment by dkurt** [comment]
@kvmanohar22, I can't find weights for the model. Link at https://github.com/kvmanohar22/opencv_contrib/tree/GSoC17_dnn_objdetect/modules/dnn_objdetect#squeezedet-model-trained-for-object-detection is a loop. Origin Caffe can't produce it because there is no `Permute` layer.

However I've already found some inaccurate thing in the sample: https://github.com/kvmanohar22/opencv_contrib/blob/GSoC17_dnn_objdetect/modules/dnn_objdetect/test/obj_detect.cpp#L108. It tries to get three output blobs from network but instead a single run it does it three times for every blob. Please, replace it to single invocation of `forward` method. Perhaps you have wrong results now because of known bug with input blob damaging. That means something like
```
net.setInput(input);
out1 = net.forward();
out2 = net.forward();
out1 != out2
```
Currently it may be fixed only by manual input update.
```
net.setInput(input);
out1 = net.forward();
net.setInput(input);
out2 = net.forward();
out1 == out2
```
But we're going to merge a PR with fix.

**Comment by kvmanohar22** [comment]
I hadn't updated README with the links. Here you can find the weights and deploy prototxt files: [link](https://github.com/opencv/opencv_extra/pull/367)

Original `caffe` can't reproduce these results. I have made a fork of the repo and added the necessary layers to interpret the results. Link to the fork is [here](https://github.com/kvmanohar22/caffe)

Since there was no method where I could get the output of three blobs with a single forward pass, I had to do the forward pass thrice. 

I'll change the method by setting the input blob before every forward pass.

**Comment by dkurt** [comment]
@kvmanohar22, please be more attentive. There is one: http://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a5efa5f217ea787e1ffb75586f3f61da3.

**Comment by kvmanohar22** [comment]
@dkurt I'm sorry, I didn't have a look at that !

I would be requiring more of something like [this](http://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a00e707a86b2da4f980f9342b1fc2cc92)

Thanks for the pointer.

**Comment by kvmanohar22** [comment]
@dkurt  That seems to be the real problem. I had to set the input blob manually every time I feed forward through the network. There is no bug as such in max-pool layer.

**Comment by dkurt** [comment]
@kvmanohar22, you'd better do a single forward pass. It's a sample that will be used by users as a starting point to write own samples. We should keep it clear and meaningful.

**Comment by kvmanohar22** [comment]
```cpp
std::vector<std::vector<cv::Mat> > out_blobs;
std::vector<cv::String> out_layer_names;
```

I did try that, but in the function `net.forward(out_blobs, out_layer_names)`, I got a `segmentation fault`.
I'll verify this once again, and do a single forward pass henceforth !
