### ISSUE TITLE
cmake opencvutils error

### ISSUE THREAD

**Issue by shivaz560** [opencv/opencv#9475]
Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags
CMake Warning at /home/shiva/opencv-3.2/opencv-3.2.0/cmake/OpenCVUtils.cmake:1021 (message):
  Download: Local copy of v3.1.0/protobuf-cpp-3.1.0.tar.gz has invalid MD5
  hash: d41d8cd98f00b204e9800998ecf8427e (expected:
  bd5e3eed635a8d32e2b99658633815ef)
Call Stack (most recent call first):
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/CMakeLists.txt:35 (include)

Downloading v3.1.0/protobuf-cpp-3.1.0.tar.gz...
CMake Error at /home/shiva/opencv-3.2/opencv-3.2.0/cmake/OpenCVUtils.cmake:1044 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/.download/bd5e3eed635a8d32e2b99658633815ef/v3.1.0/protobuf-cpp-3.1.0.tar.gz]
      expected hash: [bd5e3eed635a8d32e2b99658633815ef]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"Unsupported protocol"]

Call Stack (most recent call first):
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/CMakeLists.txt:35 (include)

CMake Error at /home/shiva/opencv-3.2/opencv-3.2.0/cmake/OpenCVUtils.cmake:1048 (message):
  Failed to download v3.1.0/protobuf-cpp-3.1.0.tar.gz.  Status=1;"Unsupported
  protocol"
Call Stack (most recent call first):
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  /home/shiva/opencv-3.2/opencv_contrib-3.2.0/modules/dnn/CMakeLists.txt:35 (include)

Configuring incomplete, errors occurred!
See also "/home/shiva/opencv-3.2/opencv-3.2.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/shiva/opencv-3.2/opencv-3.2.0/build/CMakeFiles/CMakeError.log".

**Comment by alalek** [comment]
> Unsupported protocol

You need CMake with HTTPS support.
