### ISSUE TITLE
NormTypes incomplete documentation

### ISSUE THREAD

**Issue by cptwunderlich** [opencv/opencv#9482]
The documentation for NormTypes does not explain all options, in particular the difference between NORM_L2 and NORM_L2SQR:
http://docs.opencv.org/3.3.0/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f

It wasn't obvious for me at first glance, that SQR means squared. I would add either
1) A case with the formula like for NORM_INF, _L1 and _2
2) Add a sentence describing the difference: "NORM_LF2SQR calculates the same norm as NORM_L2, but without taking the square root of the result."

**Comment by saskatchewancatch** [comment]
I agree @cptwunderlich , in particular, what is `NORM_TYPE_MASK`? It seems to be only used in the code to mask out invalid values. I'm not sure exposing internal enum values is nice. Someone looking at the docs for the norm types for the first time might wonder if NORM_TYPE_MASK has something to do with the mask parameter for the norm overload that takes a mask. It's an unnecessary source of possible confusion IMO.

**Comment by alalek** [comment]
To hide something from docs generator use this pattern:
```
#ifndef CV_DOXYGEN
    NORM_TYPE_MASK = 7, // internal usage only
#endif
```

**Comment by saskatchewancatch** [comment]
The Hamming norm types could also use some explanation.

I understand what the Hamming norm type does when `NORM_HAMMING` is used, but there is something special about `NORM_HAMMING2` which eventually calls `normHamming` with `cellSize = 2`.

What does the `cellSize` mean? I can't find information on this. The reason for asking this is that the documentation should make clear the difference between those two Hamming norm types. 

Can anyone shed light onto what `cellSize` means?

**Comment by saskatchewancatch** [comment]
Some work towards clarification has been done in PR #9574 . Some work is pending. I can't figure out what `normHamming` is used for when `cellSize=2`.
