### ISSUE TITLE
Hoping for an explanation.

### ISSUE THREAD

**Issue by MattTucker22689** [opencv/opencv#9485]
So, I've been playing with some code trying to get mine to work... and I've noticed, with videos if I don't add:

`    if cv2.waitKey(1) & 0xFF == ord('q'):
        break`

or something like it to the end of my object recognition program it will only load the first frame. 
WHY?

**Comment by GrgoMariani** [comment]
Maybe this will help.
https://stackoverflow.com/questions/12452118/what-does-waitkey-30-mean-in-opencv

**Comment by MattTucker22689** [comment]
Oh duh... Yea, I see it now... waitKey() is a sort of delay to give the program time to implement the code on each frame
