### ISSUE TITLE
How to load tensorflow model in Opencv 3.3.0

### ISSUE THREAD

**Issue by hoangnh1830** [opencv/opencv#9487]
Hello,
Finally, dnn module released, it's great!
I saw a sample that it loaded a caffe model and executive inference. How can I load a tensorflow model?
Thanks.

**Comment by dkurt** [comment]
@hoangnh1830, it's not the place where you can receive the fastest answer to build/install/usage questions. It's a tracker for bugs and proposals as you could see during an issue creation. Please, use http://answers.opencv.org or https://stackoverflow.com/questions/ask?tags=opencv+deep-learning to let other users also studied the problem.
