### ISSUE TITLE
cv::Matx has no iterator interface

### ISSUE THREAD

**Issue by maddanio** [opencv/opencv#9488]
it would be imensely convenient if Matx provided an iterator interface (i.e. defines begin and end) so it can be used as a range in range-based-for or boost::range or similar.

**Comment by alalek** [comment]
Consider using `Matx<typename _Tp, int m, int n>` values directly and wrap them into processing container:
```
_Tp val[m*n]; //< matrix elements
```

**Comment by maddanio** [comment]
I know it is possible, I just thought it would be convenient/modern to be able to written for(auto& x : m)

**Comment by maddanio** [comment]
Or with a range library copy(m | transformed(...), m2)

**Comment by maddanio** [comment]
Plus it would be only a few lines of code
