### ISSUE TITLE
OpenCV 3.2.0 Install Issue

### ISSUE THREAD

**Issue by sdmiller3964** [opencv/opencv#9493]
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04 running in Oracle Virtual Box
- Compiler =>  gnu c++

##### Detailed description
I got the following errors while trying to build the OpenCV configuration with cmake.

Build output check failed:
    Regex: 'command line option .* is valid for .* but not for C\+\+'
    Output line: 'cc1plus: warning: command line option â-Wmissing-prototypesâ is valid for C/ObjC but not for C++'
Compilation failed:
    source file: '/home/saul/opencv-3.2.0/build/CMakeFiles/CMakeTmp/src.cxx'
    check option: ' -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations  -Wmissing-prototypes'

##### Steps to reproduce
cd ~/opencv-3.1.0/
$mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.1.0/modules \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
    -D BUILD_EXAMPLES=ON ..

#######  Fix
Fixed the error by making comments out of  the following lines in OpenCVCompilerOptions.cmake.
  #add_extra_compiler_option(-Wmissing-prototypes)
  #add_extra_compiler_option(-Wstrict-prototypes)

Since the -Wmissing-prototypes and -Wstrict-prototypes are not valid options for the gnu c++ compiler, they should not be in the build for OpenCV.

**Comment by alalek** [comment]
> Fixed the error

This is not the error.
These messages are just results of compiler options check. These failed compiler options are ignored and are not used in the build of OpenCV.

**Comment by yurmchg** [comment]
I had the same issue and successfully resolved it by prompting the proper `OPENCV_EXTRA_MODULES_PATH`

**Comment by javadba** [comment]
> I had the same issue and successfully resolved it by prompting the proper `OPENCV_EXTRA_MODULES_PATH` instead of incorrect one

So what did you set that to ?

**Comment by OrHirshfeldFFR** [comment]
I had a similar problem and I added ENABLE_CXX11=ON to solve it

**Comment by land-pack** [comment]
> I had a similar problem and I added ENABLE_CXX11=ON to solve it

You did great job! I google whole my day, but finally you help me figure it out ... Thanks sooooo much

**Comment by AllanMwirigi** [comment]
> I had a similar problem and I added ENABLE_CXX11=ON to solve it

This worked. Thanks a lot

**Comment by saleo** [comment]
> I had the same issue and successfully resolved it by prompting the proper `OPENCV_EXTRA_MODULES_PATH` instead of incorrect one

me 2, with similiar error prompt 

`Regex: 'argument .* is not valid'
    Output line: 'cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C'`

**Comment by alalek** [comment]
Outdated versions of OpenCV may not work with modern compilers.
You should upgrade or backport fixes.
