### ISSUE TITLE
FindPylint.cmake causes a problem on building

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv#9494]
##### Detailed description
my `version_string.inc` has the line below ( causes a problem on building )
```
"    Pylint:                      C:/Anaconda2/Scripts/pylint.exe (ver: pylint-script.py 1.6.4, 
astroid 1.4.9
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]
, checks: 63)\n"
```

i think the reason is [this line from FindPylint.cmake](https://github.com/opencv/opencv/blob/master/cmake/FindPylint.cmake#L18)

@alalek could you take a look please.

as an additional information `pylint --version` output is as below

```
E:\build\opencv\bin\Release>pylint --version
Problem importing module variables.py: No module named functools_lru_cache
Problem importing module variables.pyc: No module named functools_lru_cache
No config file found, using default configuration
pylint-script.py 1.6.4,
astroid 1.4.9
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]
```

**Comment by alalek** [comment]
@sturkmen72 Thank you for report! Could you check #9495 ?

**Comment by sturkmen72** [comment]
@alalek thank you for fast response. it is fixed now.
