### ISSUE TITLE
filestorage::write produces xml with duplicated key 

### ISSUE THREAD

**Issue by eskimo90** [opencv/opencv#9500]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 10 
- Compiler => Visual Studio 2015

##### Detailed description

Using filestorage::save to save two matrices to one xml-file produces error "Duplicated Key" when reading the xml-file with filestorage::read. Worked with OpenCV 3.2.
Error seems to be wrong formatted xml file (One working and one non-working file are attached below). 
##### Steps to reproduce

    ```//[...]
         cv::FileStorage fSave(path + "fsave.xml", cv::FileStorage::WRITE)        
        fSave << "matA" << matA;
        fSave << "matB" << matB;
        fSave.release();
        
        cv::FileStorage fRead(path + "fsave.xml", cv::FileStorage::READ);
        fRead["matA"] >> matA;
        fRead["matB"] >> matB;
        //[...]
    ```
[fsave_examples.zip](https://github.com/opencv/opencv/files/1259430/fsave_examples.zip)

**Comment by alalek** [comment]
> Duplicated Key

Error file contents:

```
<matA type_id="opencv-matrix">
    ...</matA>
<matA>matB</matA>
<matA type_id="opencv-matrix">
     ...</matA>
```

So this file is malformed and can't be parsed due current limitations.

This code
```
fSave << "matA" << matA;
fSave << "matB" << matB;
```
provides correct results. So reproducer is incorrect.
