### ISSUE TITLE
Import Torch networks made by nngraph

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#9502]
Currently, Torch importer works with networks like
```lua
require 'nn`
net = nn.Sequential()
net:add(nn.SpatialConvolution(3,4, 3,3, 1,1, 1,1))
net:add(nn.ReLU)
```
But there is one more way to define the models: by `nngraph`
```lua
require 'nngraph'
conv = nn.SpatialConvolution(3,4, 3,3, 1,1, 1,1)()
relu = nn.ReLU(conv)
net = nn.gModule({conv}, {relu})  -- Input node, output node
```

Currently, import of the last model produces `Unknown nn class "nn.gModule" in function readTorchObject`.

**Comment by vermashresth** [comment]
@dkurt I would like to work on this issue. I used the dbgPrint flag in [torch_importer.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/torch/torch_importer.cpp) for a single `Identity()` layer model and printed the `readTorchTable` for both the cases and here is what I found

For normal nn case
```
Class: nn.Identity
0th key: gradInput
Class: torch.DoubleTensor
1th key: _type
2th key: output
Class: torch.DoubleTensor
scalarParams:
_type : torch.DoubleTensor
#2 tensorParams:
gradInput: Tensor 
output: Tensor 
```

For nngraph
```
Class: nngraph.Node
nngraph.Node
0th key: data
Class: nn.Identity
0th key: gradInput
Class: torch.DoubleTensor
1th key: _type
2th key: output
Class: torch.DoubleTensor
scalarParams:
_type : torch.DoubleTensor
#2 tensorParams:
gradInput: Tensor 
output: Tensor 
1th key: visited
2th key: id
3th key: children
4th key: marked
scalarParams:
id : 0
marked : 0
visited : 0
```
I also used another code [here-torchfile](https://github.com/bshillingford/python-torchfile) which has a bit different naming but gives a more readable version

For nn case

`TorchObject(nn.Identity, {'output': array([], dtype=float64), '_type': 'torch.DoubleTensor', 'gradInput': array([], dtype=float64)})
`

for nngraph

`TorchObject(nngraph.Node, {'visited': False, 'data': {'reverseMap': [], 'mapindex': [], 'module': TorchObject(nn.Identity, {'output': array([], dtype=float64), '_type': 'torch.DoubleTensor', 'gradInput': array([], dtype=float64)}), 'annotations': {'_debugLabel': '[hell.lua]:4_'}}, 'id': 0, 'marked': False, 'children': []})
`

It seems, the layer information for an nngraph is stored in its data tensor and from there it is same as  how it is done in the current method but currently it reads the layer as 'nngraph.Node' and disregards it completely as an unknown nn class. Is this a good direction to work on or would you suggest something else?

**Comment by dkurt** [comment]
@vermashresth, just propose an initial PR that resolves that issue. Don't forget to add tests through https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/torch/torch_gen_test_data.lua.

**Comment by akhandait** [comment]
@dkurt I would like to work on this issue. This is my first issue, please give me some general guidelines of how should I approach it.
