### ISSUE TITLE
EM throws error on predict2

### ISSUE THREAD

**Issue by Tarcisiofl** [opencv/opencv#9508]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Android Studio 2.3.2

##### Detailed description

I'm getting the error message below, when I'm trying to run my code to predict if the pixel is part of a leaf or background:

```CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/ml/src/em.cpp:569: error: (-215) sample.size() == Size(means.cols, 1) in function cv::Vec2d cv::ml::EMImpl::computeProbabilities(const cv::Mat&, cv::Mat*, int) const]```

##### Steps to reproduce

```
EM em = EM.create();
em.setClustersNumber(2);
em.setCovarianceMatrixType(EM.COV_MAT_DIAGONAL);
em.trainEM(stackedPixels);

Mat mPredict = new Mat(1, 2, CvType.CV_64FC1);
mPredict.put(0,0,imgHSV.get(i,j)[1]);
mPredict.put(0,1,imgHSV.get(i,j)[2]);

double[] probabilities = em.predict2(mPredict, probs); // ERROR
```

Anyone can help me?

**Comment by Tarcisiofl** [comment]
@sovrasov Do you want me to share the complete code?

**Comment by sovrasov** [comment]
Yes, complete code is required.

**Comment by Tarcisiofl** [comment]
Complete code below:

public class DetailsActivity extends AppCompatActivity {
    private GridView gridView;
    private DescriptionGridViewAdapter gridAdapter;

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_details);

        String name = getIntent().getStringExtra("name");

        InputStream inputstream = null;
        try {
            inputstream = getApplicationContext().getAssets().open("milho/" + name);
        } catch (IOException e) {
            e.printStackTrace();
        }

        Bitmap imgOriginal = BitmapFactory.decodeStream(inputstream);

        // HSV
        Mat imgHSV = new Mat(imgOriginal.getWidth(), imgOriginal.getHeight(), CvType.CV_8UC3);
        Utils.bitmapToMat(imgOriginal, imgHSV);
        Imgproc.cvtColor(imgHSV, imgHSV, Imgproc.COLOR_RGB2HSV);

        Bitmap imgHSV_ = Bitmap.createBitmap(imgHSV.width(), imgHSV.height(), Bitmap.Config.RGB_565);
        Utils.matToBitmap(imgHSV, imgHSV_);

        Mat stackedPixels = new Mat(imgOriginal.getWidth(), imgOriginal.getHeight(), CvType.CV_8UC1);
        for (int i = 0; i < imgHSV.rows(); i++) {
            for (int j = 0; j < imgHSV.cols(); j++) {
                stackedPixels.put(i, j, imgHSV.get(i, j));
            }
        }

        EM em = EM.create();
        em.setClustersNumber(2);
        em.setCovarianceMatrixType(EM.COV_MAT_DIAGONAL);
        em.trainEM(stackedPixels);

        HashMap<Integer, Integer> pixelDictionary = new HashMap<>();
        int pixelDict;
        Mat imgBH = new Mat(imgOriginal.getWidth(), imgOriginal.getHeight(), CvType.CV_8UC1);

        for (int i = 0; i < imgHSV.rows(); i++) {
            for (int j = 0; j < imgHSV.cols(); j++) {
                if (pixelDictionary.containsKey(Objects.hash(imgHSV.get(i,j)[1], imgHSV.get(i,j)[2]))) {
                    pixelDict = pixelDictionary.get(Objects.hash(imgHSV.get(i,j)[1], imgHSV.get(i,j)[2]));
                } else {
                    Mat probs = new Mat(imgHSV.rows(), em.getClustersNumber(), CvType.CV_64FC1);

                    Mat mPredict = new Mat(1, 2, CvType.CV_32FC1);
                    mPredict.put(0,0,imgHSV.get(i,j)[1]);
                    mPredict.put(0,1,imgHSV.get(i,j)[2]);

                    mPredict.reshape(1,2);
					
					Log.e("Predict Mat", String.valueOf(mPredict));

                    double[] probabilities = em.predict2(mPredict, probs); //EM::predict2(sample, probs)
                    pixelDict = probabilities[0] > probabilities[1] ? 0 : 1;
                    pixelDictionary.put(Objects.hash(imgHSV.get(i,j)[1], imgHSV.get(i,j)[2]), pixelDict);
                }
				Log.e("Dictionary Value", String.valueOf(pixelDict));
                imgBH.put(i,j,pixelDict);
            }
        }

        ArrayList<Mat> hsvPlans = new ArrayList<>(3);
        Core.split(imgHSV, hsvPlans);

        //Utils.matToBitmap(hsvPlans.get(0), );
        //Utils.matToBitmap(hsvPlans.get(1), );
        //Utils.matToBitmap(hsvPlans.get(2), );

        HashMap<String, Bitmap> processedImages = new HashMap<>();
        processedImages.put("Original", imgOriginal);
        processedImages.put("HSV", imgHSV_);

        gridView = (GridView) findViewById(R.id.gridView);
        gridAdapter = new DescriptionGridViewAdapter(this, R.layout.grid_item_layout, processedImages);
        gridView.setAdapter(gridAdapter);
    }
}``

**Comment by sovrasov** [comment]
`probs` matrix should be `1xnclusters`

**Comment by Tarcisiofl** [comment]
@sovrasov I'm still getting the same error.

I was trying to implement it based on the 2 below algorithm:

**Algorithm 1**
```
stackedPixels ← ∅
for all pixelRow in image do
    for all pixel in pixelRow do
        stackedP ixels ← stackedP ixels ∪ pixel
    end for
end for

EM ← OpenCV.EM(nClusters = 2, covMatT ype = OpenCV.DIAGONAL)
EM.train(stackedP ixels)
return EM
```

**Algorithm 2**
```
key ← hash(pixel[S], pixel[V ])
if hash in pixelDictionary then
    return pixelDictionary[key]
end if
probabilities ← EM.predict(pixel[S], pixel[V ])
pixelDict[key] = probabilities[0] > probabilities[1]
return pixelDict[key]
```

Could you help me to achieve my goal?

Thank you

**Comment by sovrasov** [comment]
@Tarcisiofl all usage questions should be asked in http://answers.opencv.org/questions/
This issue tracker is only for bugs with clear description and reproducers. Take a look at [EM usage example](https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/samples/cpp/em.cpp). May be it can be helpful.

**Comment by Tarcisiofl** [comment]
@sovrasov I already tried to get help there without success.

[OPENCV FORUM](http://answers.opencv.org/question/171375/android-opencv-em-fatal-error/)
