### ISSUE TITLE
Building for Android not working with Ninja

### ISSUE THREAD

**Issue by JDFind** [opencv/opencv#9513]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Ninja 1.7.2
- Cmake 3.9.1

##### Detailed description
Recently I attempted to build OpenCV from sources on a Windows 10 machine, using the Ninja compiler and a modified android.toolchain.cmake (because of #9512).

Building with Ninja fails for **arm64-v8a** because a `undefined reference to 'png_init_filter_functions_neon'` for the same reason as #7600

It seems that there is a "hack" in the `android.toolchain.cmake` file that forces `CMAKE_COMPILER_IS_MINGW` to be `true`:
```.cmake
if( CMAKE_GENERATOR MATCHES "Ninja" AND CMAKE_HOST_WIN32 )
 # it is a bad hack after all
 # CMake generates Ninja makefiles with UNIX paths only if it thinks that we are going to build with MinGW
 set( CMAKE_COMPILER_IS_MINGW TRUE ) # tell CMake that we are MinGW
 set( CMAKE_CROSSCOMPILING TRUE )    # stop recursion
 # unset( CMAKE_COMPILER_IS_MINGW ) # can't unset because CMake does not convert back-slashes in response files without it
 unset( MINGW )
endif()
```

This causes an issue with identifying the compiler in `OpenCVDetectCXXCompiler.cmake`, setting  `X86_64` instead of `AARCH64`, even though `CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64.*|AARCH64.*)"` would have been `true`. As a result, `USING_NEON` is not enabled either.

I think a solution might be to remove the "hack" entirely, as it was unnecessary on the system described, or to change the order of the if-else statements in `OpenCVDetectCXXCompiler.cmake`.

##### Steps to reproduce
Running
```
cmake -D CMAKE_BUILD_TYPE=Release \
	-D CMAKE_BUILD_WITH_INSTALL_RPATH=ON \
	-D CMAKE_INSTALL_PREFIX="install/opencv" \
        -D CMAKE_TOOLCHAIN_FILE="opencv/platforms/android/cmake/android.toolchain.cmake" \
        -D ANDROID_NDK="${ANDROID_NDK_ROOT}" \
        -D ANDROID_NATIVE_API_LEVEL=21 \
        -D ANDROID_ABI=arm64-v8a \
        -D WITH_CUDA=OFF \
        -D WITH_MATLAB=OFF \
        -D BUILD_ANDROID_EXAMPLES=OFF \
        -D BUILD_DOCS=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D BUILD_TESTS=OFF \
	-D BUILD_EXAMPLES=OFF \
	-D BUILD_SHARED_LIBS=OFF \
	-G Ninja \
	-D CMAKE_MAKE_PROGRAM=${NINJA_LOCATION}
```

**Comment by alalek** [comment]
> to remove the "hack" entirely, as it was unnecessary on the system described

Agreed.
Could you validate hack removal (with `enable_language()` calls) on your configuration and create Pull Request?

**Comment by alalek** [comment]
Current Android builds on CI works well (using Ninja).
