### ISSUE TITLE
Can't use BFMatcher radiusMatch HUMMING2 (ORB K>2)

### ISSUE THREAD

**Issue by A3yuu** [opencv/opencv#9525]
##### System information (version)

- OpenCV => 3.1 to 3.3
- Operating System / Platform => all
- Compiler => all

##### Detailed description

matchers.cpp
line 961
int dtype = normType == NORM_HAMMING ||
→int dtype = normType == NORM_HAMMING || normType == NORM_HAMMING2 || (836 same?)

**Comment by berak** [comment]
indeed.

    BFMatcher matcher(NORM_HAMMING2);
    Mat query(2,32,CV_8U);
    Mat train(2,32,CV_8U);
    vector<vector<DMatch>> matches;
    matcher.add(train);
    matcher.radiusMatch(query,matches,1.2f);


`
OpenCV Error: Unsupported format or combination of formats (The combination of type=0, dtype=5 and normType=7 is not supported) in batchDistance, file C:\p\opencv\modul
es\core\src\stat.cpp, line 4097
`
