### ISSUE TITLE
Issue when running torch_enet dnn example

### ISSUE THREAD

**Issue by sjdrc** [opencv/opencv#9532]
I compile the torch_enet sample from [here] https://github.com/opencv/opencv/blob/master/samples/dnn/torch_enet.cpp) successfully but get the following error when running the program with no arguments:

```
$ ./a.out 
OpenCV Error: Unspecified error (cannot open <> in mode r ) in THDiskFile_new, file /home/sebastien/src/opencv/modules/dnn/src/torch/THDiskFile.cpp, line 505
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/sebastien/src/opencv/modules/dnn/src/torch/THDiskFile.cpp:505: error: (-2) cannot open <> in mode r  in function THDiskFile_new

Aborted (core dumped)
```

Torch and OpenCV 3.3 are both installed to /usr/local.

Any ideas on how to resolve this?

**Comment by berak** [comment]
unfortunately, the `model` and `image` params are mandatory, you cannot run this program without arguments. 

(you're supposed to download the model file, and apply the torch network on an image of your choice)

but maybe, we can make the sample a bit more explicit about that !

**Comment by sjdrc** [comment]
Hey, should have mentioned that I was also getting the issue when running the program with the model and image params. I managed to solve it by hardcoding the filenames in the program. I'm not sure what the issue was but I think the CommandLineParser somehow wasn't reading the inputs even when I provided them.

Thanks for the reply.

**Comment by berak** [comment]
@sjdrc  CommandLineParser expects args like:   ./prog  img=my.png

(if you forget the `=` , it will ignore the whole arg)

**Comment by husaka** [comment]
Hi, example torch_enet.cpp doesn't work, version - OpenCV 3.3, OS - Win10, IDE-VS2015.
CommandLineParser reads args correctly (verified in debug)
Model reads normally dnn::Net net = dnn::readNetFromTorch(modelFile);
Image reads normally,
Net Outputs(1): l367_Deconvolution
Fails  Mat result = net.forward(oBlob);

Thanks for the reply.
