### ISSUE TITLE
FindCuda not working with Cuda 9.0

### ISSUE THREAD

**Issue by linqingfan** [opencv/opencv#9535]
- OpenCV => 3.3
- Operating System / Platform => ubuntu 16.04 64 Bit
- Compiler => :grey_question:

##### Detailed description

Hi all,
After I upgraded to cuda 9.0, I cant cmake and comple.
Further looking into the cmake codes, I found that unlike Cuda 8.0, Cuda 9.0 have no libnppi.so library.
I just create a soft link to a library and cmake work.
However when I issue make, I encounter the following compile error:

nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:208 (message):
  Error generating
  /home/kplim/opencv/opencv-3.3.0/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

##### Steps to reproduce

cmake with the option WITH_CUDA=ON
and make

**Comment by alalek** [comment]
> nvcc fatal : Unsupported gpu architecture 'compute_20'
> Unsupported

CUDA has many target architectures, some of them are dropped in CUDA 9.0.
Consider to upgrade your hardware or disable autodetection in your builds via [CUDA_GENERATION](https://github.com/opencv/opencv/blob/3.3.0/cmake/OpenCVDetectCUDA.cmake#L65-L75) CMake option (or via other variables).

> I found that unlike Cuda 8.0, Cuda 9.0 have no libnppi.so library. I just create a soft link to a library and cmake work.

It work when all tests pass. Currently this looking like trying to break build environment via mixing CUDA 8/9 libraries.

**Comment by linqingfan** [comment]
Thanks.
I have used the CUDA_GENERATION=Pascal option for my GPU, it does overcome the issue but still can't compile the same function cuda_compile_generated_gpu_mat.cu:

Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
/home/kplim/opencv/opencv-3.3.0/modules/cudev/include/opencv2/cudev/util/saturate_cast.hpp(277): error: identifier "__half2float" is undefined

Think maybe because of the change in the library of nppi in CUDA 9.0

**Comment by phg1024** [comment]
@linqingfan  Adding `#include <cuda_fp16.h>` resolved this issue.

**Comment by alexandersack** [comment]
Adding it where?

**Comment by alalek** [comment]
@alexandersack Take a look on this: #9769
