### ISSUE TITLE
Grey window when webcam capturing

### ISSUE THREAD

**Issue by RLaroche** [opencv/opencv#9537]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Windows 7, 64 Bit
- Compiler => Visual Studio 2015 community

##### Detailed description
Hello!
Here I am to report an issue because it's impossible for me to figure out where is hidden my problem.
I am using a Logitech Quickam pro 9000 webcam and can't do any capture with.
Yet, I can't believe there is a problem with the camera installation because it greatly works with its own software "Logitech Webcam Software".
Moreover, openCV seems to be pretty well installed too, until I can import and process images or even videos with application built with opencv.
Finally, I am using a perfectly basic code you can find everywhere wich is : 

```.cpp
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/videoio.hpp"
#include <iostream>

//using namespace cv;
//using namespace std;

int main() {

	cvNamedWindow("Raw", CV_WINDOW_NORMAL); 
	CvCapture* capture;
	IplImage * frame;
	char c;
	capture = cvCaptureFromCAM(0);  // works with 0 (ANY) or with an number between 10 and 19 included

	if (capture) {
		std::cout << "CAPTURE SUCCEEDED\n";
		while (1) {
			frame = cvQueryFrame(capture);
			if (!frame) {
				std::cout << "no frame\n";
				cvWaitKey(2000);
			}
			else {
				std::cout << "frame\n";
				("Raw", frame);
			}
			c = cvWaitKey(33);
			if (c == 27) break;
		}
	}
	else if (!capture)	std::cout << "NO CAPTURE\n";
	cvWaitKey(3000);
	cvReleaseCapture(&capture);
	cvDestroyWindow("Raw");
	return 0;
}```

When I use it, is written in my shell :"CAPTURE SUCCEEDED" and then "frame" several times.
So the connection to the camera seems to be good and the frame retrieving seems working too.
However, I capture nothing. The window "Raw" is totally grey, while the logitech controller opens well.
I tried the same with a Kinect for PC which works perfectly with its own software too : the same grey window while frames seem retrieved.
I also tried with OpenCV 2.4.10 and Visual Studio 2010 pro : always exactly the same result.
I've finally tried a few different methods of coding, using a videocapture object for example : not better.
I stared in the issues and answers categories of opencv, no one seems to have discussed of this problem of grey or black window before.
If anyone had an idea of the origin of the problem ... I would love him
Thank you !

**Comment by lpea** [comment]
Hi,

The sample code you provide is missing a call to `cvShowImage`. Maybe it disappeared when you copy/pasted you code here?

**Comment by sturkmen72** [comment]
I think `cvCaptureFromCAM (0);` is no longer supported.
maybe this [link](https://stackoverflow.com/a/33712377/5294258) will be helpful

**Comment by JIMyungSik** [comment]
Hi,

I don't know well about your problem.
but I use like this when I want to connect with camera.

```
 capture = cvCreateCameraCapture(0);
/* start capturing frames from camera: index = camera_index + domain_offset (CV_CAP_*) */
```

Why don't you try this?

**Comment by RLaroche** [comment]
Hi and thank you for your answers,
Unfortunately, none of your advice is helpful.

Effectively Ipea, the original code was cvShowImage("Raw", frame); This missing just comes from a test I did.

JIMyungSik, this doesn't change anyhting, because in the file video_c.h is defined
```
.cpp
#define cvCaptureFromCAM cvCreateCameraCapture //!< @deprecated use cvCreateCameraCapture() instead
```
It's so the same function.
Moreover, I didn't well understand that camera_index and domain_offset, but I created a for() to try each number from 0 to 99999, and the ones who "work" (display a grey or black winodw rather than fail capturing) are 0 (CV_CAP_ANY) and each number from 10 to 19.

And finally, thank you sturkmen for this new code, maybe the 6th or 7th I try (which effectively seems more suitable to openCV3), but it doesn't work neither.
And regarding merging my .cpp files with the ones proposed on stackoverflow, the result is still the same.
I finally tried to install OpenCV 2.4.10 on visual studio 2013 : still the same result, close to I can't even use CV_CAP_ANY for cvCreateCameraCapture, but always get capture, frame and grey window with numbers from 10 to 19.

Anyone else ?
Thank you

**Comment by berak** [comment]
@RLaroche , you simply must no more use opencv's deprecated c-api (it also limits you to using VFW, and that won't work on newer windows versions) . please don't try to fix anything, but start all over with the c++ api link, @sturkmen72 sent before.

also please, could you close this issue ? it's NOT a library bug, so it should not go here.  further
questions should go to http://answers.opencv.org

**Comment by RLaroche** [comment]
Ok 
Thank you so much !!
