### ISSUE TITLE
The Mat .copyTo function generates an exception when copying from a single Mat to an array of Mats

### ISSUE THREAD

**Issue by bioman5556** [opencv/opencv#9539]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

The Mat .copyTo function generates an exception when copying from a single Mat to an array of Mats.
```
Mat faces[10];
Mat face;

face.copyTo(faces[0]);
```

**Comment by csukuangfj** [comment]
What kind of exception did it generate and what was you source code?
