### ISSUE TITLE
cannot open source file "dynlink_nvcuvid.h"	opencv_cudacodec

### ISSUE THREAD

**Issue by amin-git** [opencv/opencv#9544]
##### System information (version)
- OpenCV => : 3.3:
- Operating System / Platform => : Windows 10 , 64 Bit:
- Compiler => :Visual Studio 2015:

## i meet two bugs:

**1.first enable preformance test cause error same as https://github.com/opencv/opencv/issues/6716**

**2.cannot open source file "dynlink_nvcuvid.h"**
 ```
Severity Code Description Project File Line Suppression State
Error C1083
Cannot open include file: 'dynlink_nvcuvid.h': No such file or directory
opencv_cudacodec	opencv-master\modules\cudacodec\src\precomp.hpp	59	
 ```
## cmake configure output
 ```
CUDA detected: 8.0
CUDA NVCC target flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-D_FORCE_INLINES
  ```
General configuration for OpenCV 3.3.0-dev 

  Extra modules:
    Location (extra):            opencv_contrib-master/modules
 ```
  Platform:
    Timestamp:                   2017-09-02T15:37:49Z
    Host:                        Windows 10.0.15063 AMD64
    CMake:                       3.9.1
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900
  ```
```
  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_2
      SSE4_2 (3 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
```
```
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    YES (ver 8.0)
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO
  ```
```
  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  YES
    USE NVCUVID:                 YES
    NVIDIA GPU arch:             50 52
    NVIDIA PTX archs:
    Use fast math:               NO
 ```
```
  OpenCL:                        <Dynamic loading of OpenCL library>
    Include path:               opencv-master/3rdparty/include/opencl/1.2
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO


  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

Configuring done
Generating done

 ```

**Comment by xsorifc28** [comment]
Also getting this error, same setup.

**Comment by jasjuang** [comment]
I also ran into the same problem

**Comment by lucaspbordignon** [comment]
Thanks @whizzzkid , the solution proposed by #9599 worked!

**Comment by whizzzkid** [comment]
@lucaspbordignon this is because cuda8 provides `nvcuvid.h` and cuda9 provides `dynlink_nvcuvid.h` so opencv builds for cuda8 are not compatible with cuda9

I am still working on the solution for this.

**Comment by zaouch** [comment]
Despite the merge, I issue persists with CUDA 10.

`fatal error: dynlink_nvcuvid.h: No such file or directory`

**Comment by achalshah20** [comment]
I have  the same issue with CUDA 10.

**Comment by x-t0xid** [comment]
Same problem with CUDA 10

precomp.hpp:60:18: fatal error: dynlink_nvcuvid.h: No such file or directory

**Comment by petrpulc** [comment]
NVCUVID is deprecated: https://docs.nvidia.com/cuda/video-decoder/index.html

**Comment by x-t0xid** [comment]
@petrpulc Solved thanks

**Comment by castleguarders** [comment]
This workaround uses CUDA 8 definitions on CUDA 10 for a deprecated API. What is the "longer" term permanent fix? In other words, It's unclear to me if the older nvcuvid.h from Cuda 8 and the one in Cuda 10 / NVDecode SDK are compatible? I don't have Cuda 8 headers to compare.
