### ISSUE TITLE
Protobuf version detection

### ISSUE THREAD

**Issue by spetroce** [opencv/opencv#9549]
##### System information (version)

- OpenCV => :grey_question: dev
- Operating System / Platform => :grey_question: Fedora 26
- Compiler => :grey_question: GCC 7.1.1

##### Detailed description

I get the following error when trying to execute a program compiled against the latest github opencv master.

[libprotobuf FATAL /home/.../opencv/dev/3rdparty/protobuf/src/google/protobuf/stubs/common.cc:67] This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 3.1.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 3.1.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/any.pb.cc".)
Aborted (core dumped)

I already have version 3.2.0 installed and it's what I build OpenCV against. I tried reinstalling protobuf 3.2.0 and then recompiling OpenCV. Also double checked the version info with the protobuf headers and it is 3.2.0. 

##### Steps to reproduce

Pull the latest master and do a clean build. Try to execute a program that links against this opencv compilation. You will get the error above. I verified this on two different setups after pulling the latest master.

Update: I noticed by default, OpenCV is build it's own protobuf. I have to enable the following to get a successful compile and runtime operation: -DBUILD_PROTOBUF=OFF -DPROTOBUF_UPDATE_FILES=ON

**Comment by alalek** [comment]
Looks like this problem comes from "opencv_dnn_modern" contrib module. It has strong conflict with "opencv_dnn" module, so "dnn_modern" is disabled in default builds.
Build with both modules is possible via workaround with additional build flags (described above).
