### ISSUE TITLE
Incorrect handling of 16 bit tiff images with photometric interpretation 0

### ISSUE THREAD

**Issue by drtdt** [opencv/opencv#9550]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

cv::imread seems to handle 16 bit grayvalue tif images incorrectly when photometric interpretation is 0 ("WhiteIsZero"). The resulting cv::Mat has type CV_8UC1. When the photometric interpretation is 1, however, the image is loaded correctly as CV_16UC1.

I suspect the error to be in the condition starting from line 154 in modules/imgcodecs/src/grfmt_tiff.cpp, where photometric==0 leads to setting bpp to 8.

##### Steps to reproduce

Test images were created using ImageJ using File->New->Image... with 16-bit. One image was inverted using Image->Color->Edit LUT...->Invert,,. 

tiffdump showed the photometric interpretation to be the only tag being different in the two images.

Images were loaded using the following code:

```cpp
cv::Mat image = cv::imread("16bit.tif", cv::IMREAD_UNCHANGED);
cv::Mat image_inv = cv::imread("16bit_inv.tif", cv::IMREAD_UNCHANGED);

std::cout << image.type() << std::endl;			// prints '2'
std::cout << image_inv.type() << std::endl;		// prints '0'
```

**Comment by saskatchewancatch** [comment]
I _suspect_ the problematic line is [237](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_tiff.cpp#L237) in `grfmt_tiff.cpp`.

It's not considering the case where `PHOTOMETRIC_INTERPRETATION` is `0`, which would explain why @drtdt is getting a `CV_8U` matrix as the type for TIFFs which have `PHOTOMETRIC_INTERPRETATION = 0`.

I think replacing the check, `photometric != 2 && photometric != 1`, with `photometric > 2` will allow the OP to read 16bpp TIFFs which have `PHOTOMETRIC_INTERPRETATION = 0` into a `CV_16U` matrix.

I'll wait for comments from others on whether this is a suitable fix. I can have a tested PR for this upon approval.

**Comment by sovrasov** [comment]
@saskatchewancatch  the fix seems to be correct, so your PR (with regression test) is welcome.

**Comment by saskatchewancatch** [comment]
@drtdt #9564 should resolve the issue.

@sovrasov Upon further thought, I think a regression test just for this would be unnecessary. I think this aspect is very unlikely to regress in the future. If there is disagreement, I can add a test.
