### ISSUE TITLE
Imgproc.moments generates library error

### ISSUE THREAD

**Issue by GandalfD** [opencv/opencv#9552]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Linux 64 bit
- Compiler => Android Studio

##### Detailed description
I'm trying to use moments to calculate the centroid of a contour using Imgproc.moments(contour)
Doing this produces this error: 

java.lang.UnsatisfiedLinkError: No implementation found for double[] org.opencv.imgproc.Imgproc.moments_0(long, boolean) (tried Java_org_opencv_imgproc_Imgproc_moments_10 and Java_org_opencv_imgproc_Imgproc_moments_10__JZ)

Here is my OpenCV build information: [build](https://pastebin.com/6Ktr1zsH)
As a sidenote, other functions in Imgproc work fine

Thanks!

**Comment by alalek** [comment]
> General configuration for OpenCV 3.0.0

Looks like you have outdated OpenCV version.
Try to remove OpenCV manager an install it from SDK (not from Google Play). Or put OpenCV libraries into `<app dir>/libs/<arch>`.

BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
