### ISSUE TITLE
OpenCV Error: Unspecified error (The function is not implemented.

### ISSUE THREAD

**Issue by pankaja92** [opencv/opencv#9553]
##### System information (version)

- OpenCV => 3.3.0-dev
- Operating System / Platform => Ubuntu 16.04
- Compiler => 

##### Detailed description

When I run a code in openCV I'm getting the below error

`OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /home/pankaja/Desktop/OpenCV-tmp/opencv/modules/highgui/src/window.cpp, line 611
Traceback (most recent call last):
  File "/home/pankaja/PycharmProjects/ImageProcessing/imageprocess.py", line 8, in <module>
    cv2.imshow('image', img)
cv2.error: /home/pankaja/Desktop/OpenCV-tmp/opencv/modules/highgui/src/window.cpp:611: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
`

##### Steps to reproduce

This is my code 
    ```.py

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("watch.jpg", cv2.IMREAD_GRAYSCALE)

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

    ```

And when run this command `sudo apt-get install libopencv-*` I'm getting this

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libopencv-core-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-gpu-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-legacy2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-apps0d' for glob 'libopencv-*'
Note, selecting 'libopencv-video2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-calib3d-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-ml-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-imgproc2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-objdetect2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-video2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-highgui2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-apps-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-calib3d2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-ocl-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-ml2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-imgproc2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-ts2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-ocl2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-objdetect2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-flann2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-contrib2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-stitching-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-highgui2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-features2d-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-superres-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-photo2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-gpu2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-features2d2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-stitching2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-stitching2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-flann-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-flann2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-superres2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-calib3d2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-imgproc-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-contrib-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-ts2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-legacy2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-gpu2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-videostab2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-legacy-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-core2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-contrib2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-superres2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-photo-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-ml2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-objdetect-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-core2.4' for glob 'libopencv-*'
Note, selecting 'libopencv-videostab-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-doc' for glob 'libopencv-*'
Note, selecting 'libopencv-features2d2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-ts-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-video-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-highgui-dev' for glob 'libopencv-*'
Note, selecting 'libopencv-videostab2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-ocl2.4v5' for glob 'libopencv-*'
Note, selecting 'libopencv-photo2.4' for glob 'libopencv-*'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopencv-apps-dev : Depends: libcv-bridge-dev but it is not going to be installed
                      Depends: libdynamic-reconfigure-config-init-mutex-dev but it is not going to be installed
                      Depends: libimage-transport-dev but it is not going to be installed
                      Depends: libnodeletlib-dev but it is not going to be installed
                      Depends: libroscpp-dev but it is not going to be installed
 libopencv-highgui-dev : Depends: libgtk2.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`
Is this a bug or something I've done wrong ?

**Comment by berak** [comment]
opencv does not maintain any binary python packages, the issue should go to the resp. package  maintainer, not here.

what you downloaded there, was built without any gui (gtk or qt) support, and will also be lacking any video file functionality. (then - 2.4.5, that's really old)

if you need gui or video, you will have to [build from github src](http://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html)

would you kindly close this issue ? (again, it's not an opencv library problem)
