### ISSUE TITLE
CMake Error: Cyclic dependencies on shared libraries - Ubuntu 16.04

### ISSUE THREAD

**Issue by arunk** [opencv/opencv#9554]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Linux/Ubuntu 16.04.3
- Compiler => gcc 5.4.0

##### Detailed description

Running into cyclic dependency errors while running cmake. 

The last part of the cmake output:
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "opencv_videoio" of type SHARED_LIBRARY
    depends on "opencv_calib3d" (weak)
    depends on "opencv_highgui" (weak)
    depends on "opencv_features2d" (weak)
    depends on "opencv_stitching" (weak)
    depends on "opencv_xfeatures2d" (weak)
    depends on "opencv_superres" (weak)
    depends on "opencv_ts" (weak)
    depends on "opencv_videostab" (weak)
  "opencv_highgui" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
  "opencv_superres" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
  "opencv_ts" of type STATIC_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
  "opencv_features2d" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
  "opencv_calib3d" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
    depends on "opencv_features2d" (weak)
  "opencv_videostab" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
    depends on "opencv_features2d" (weak)
    depends on "opencv_calib3d" (weak)
  "opencv_xfeatures2d" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
    depends on "opencv_features2d" (weak)
    depends on "opencv_calib3d" (weak)
  "opencv_stitching" of type SHARED_LIBRARY
    depends on "opencv_videoio" (weak)
    depends on "opencv_highgui" (weak)
    depends on "opencv_features2d" (weak)
    depends on "opencv_calib3d" (weak)
    depends on "opencv_xfeatures2d" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

##### Steps to reproduce
Followed the steps here - http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

Cloned the repository and used this cmake command:

``` cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..```

cmake fails with the error above.

**Comment by alalek** [comment]
> used this cmake command

I didn't see using of opencv_contrib modules from message above (like `xfeatures2d`) via `OPENCV_EXTRA_MODULES_PATH` variable.
Try to clean your build directory and run CMake again (build from scratch).

We can't [reproduce](http://pullrequest.opencv.org/buildbot/builders/master-contrib-lin64) this issue.

**Comment by arunk** [comment]
Tried a simple version of cmake without many options to see if I still got an error. I recloned the repo and ran this full version again:
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..
```

I have copied the log of the cmake command here - https://pastebin.com/pgh6R2tj

**Comment by alalek** [comment]
1. Please upload these files from build directory: CMakeCache.txt CMakeVars.txt

2. Try to build from scratch without opencv_contrib (without OPENCV_EXTRA_MODULES_PATH).

3. Try to build without QT and VTK: `-DWITH_QT=OFF -DWITH_VTK=OFF`

**Comment by arunk** [comment]
cleaned build directory and re-ran cmake with:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=OFF \
      -D WITH_VTK=OFF \
      -D WITH_OPENGL=ON \
      -D BUILD_EXAMPLES=ON ..
```
Here are CMakeCache.txt and CMakeVars.txt:

[CMakeCache.txt](https://github.com/opencv/opencv/files/1275677/CMakeCache.txt)
[CMakeVars.txt](https://github.com/opencv/opencv/files/1275678/CMakeVars.txt)

**Comment by alalek** [comment]
Problem is here:

> FFMPEG_CFLAGS=-I/usr/local/include

You have custom build of FFMPEG.

> FFMPEG_LIBRARIES=avformat;dl;vdpau;va;va-drm;va-x11;xcb;Xau;Xdmcp;xcb-shm;xcb-xfixes;xcb-render;xcb-shape;X11;asound;SDL;pthread;m;pulse-simple;pulse;Xext;caca;GL;x264;vpx;vorbisenc;vorbis;ogg;theoraenc;theoradec;rtmp;z;gmp;gnutls;p11-kit;tasn1;idn;hogweed;nettle;opus;**opencv_calib3d;opencv_contrib;opencv_core;opencv_features2d;opencv_flann;opencv_gpu;opencv_highgui;opencv_imgproc;opencv_legacy;opencv_ml;opencv_objdetect;opencv_ocl;opencv_photo;opencv_stitching;opencv_superres;opencv_ts;opencv_video;opencv_videostab**;mp3lame;freetype;png12;fdk-aac;ass;harfbuzz;fontconfig;expat;fribidi;lzma;avcodec;swresample;swscale;avutil;avresample-ffmpeg

This FFMPEG build has static libraries and uses OpenCV 2.4.x.
This cause recursion and conflict.

Turn off FFMPEG (`-DWITH_FFMPEG=OFF`) or rebuilt FFMPEG with shared libraries or rebuild FFMPEG without OpenCV support or use system FFMPEG packages.

**Comment by arunk** [comment]
Thanks for your help, that resolved the issue. Found this other issue that seems related -  #5930 but does not mention any error messages with cyclic dependencies.
