### ISSUE TITLE
Boosting CV_FOLDS Segfault

### ISSUE THREAD

**Issue by luug** [opencv/opencv#9557]
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 14.04
- Compiler => gcc

Segfault when using `k_fold` bigger than 1. 0 and 1 itself are working.

`     cv::Ptr<cv::ml::Boost> boost_ = cv::ml::Boost::create();`
`     boost_->setCVFolds(k_fold);`
`     boost_->train(data);`

**Comment by sovrasov** [comment]
I've looked at the `Boost` code and noticed cross validation actually is not implemented.
`Boost` uses `DTrees` internally and CV can be used for better trees pruning.
