### ISSUE TITLE
getting make compilation errors. 

### ISSUE THREAD

**Issue by arprasto** [opencv/opencv#9558]
##### System information (version)
opencv version : 3.3.0
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

##### Detailed description
first i ran the cmake task in saperate build directory and after that when running make in build directory getting below compilation errors. I am attaching the build logs.

[Archive.zip](https://github.com/opencv/opencv/files/1276682/Archive.zip)

##### Steps to reproduce

1. download opencv-3.3.0 src from opencv.org
2. unzip it(lets say ~/opencv-3.3.0/) and create a separate build directory(~/opencv_build/).
3. run cmake ~/opencv-3.3.0 inside build directory.
4. after cmake completes, run make inside ~/opencv_build/ directory.

**Comment by mshabunin** [comment]
Please try to ask your question on the forum first: http://answers.opencv.org

**Comment by arprasto** [comment]
Hi @mshabunin, I have created this issue as suggested by @StevenPuttemans. let me create open questions there also.

**Comment by arprasto** [comment]
asked question : http://answers.opencv.org/question/173620/getting-make-compilation-error-unknown-property-attribute-class/

**Comment by alalek** [comment]
Build logs blames on system files, probably you broke your system somehow. Are you able to build other CMake projects with ObjC files?

We can't reproduce your issue - our MacOS builds are fine.

**Comment by arprasto** [comment]
@alalek i am having only this opencv and darknet objC files. darknet dependent on opencv. So i need to get opencv binaries first.

Is your MAC having below configuration as mine:
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Because if i switch xcode config to version 8 than it compiles fine. Issue is only with when i switch xcode config to version7.

**Comment by StevenPuttemans** [comment]
> We can't reproduce your issue - our MacOS builds are fine.

@alalek does the OpenCV buildbot run xcode 7?

**Comment by alalek** [comment]
We don't support such configuration.

> Build logs blames on system files

Probably Apple doesn't support it well too.
And switching to Xcode 7 just brokes build environment.

**Comment by arprasto** [comment]
one workaround i found is to install it through anaconda:
conda install -c menpo opencv3
