### ISSUE TITLE
Mat::ptr not defined for more than 3 dimensions

### ISSUE THREAD

**Issue by azatsman** [opencv/opencv#9570]
##### System information (version)

- OpenCV =>  3.3, git repository as of 9/6/17
- Operating System / Platform => probably all, tested on Linux
- Compiler => probably all C++ compilers, tested with g++ 5.4

##### Detailed description
There is no definition for the templated `ptr` method declared in `core/mat.hpp`:
 ```.cpp
template<typename _Tp> const _Tp* ptr(const int* idx) const;
```
The definition is missing in `core/mat.inl.hpp` (where it probably belongs), and the example code below generates linker's error:
    `mat4.cpp:(.text+0x113): undefined reference to `float* cv::Mat::ptr<float>(int const*)'`

##### Steps to reproduce

Try building an executable for this source code:

```.cpp
#include <opencv2/core.hpp>
int main (int argc, const char *argv[])
{
  int dims4[4] = {2,3,4,5}, idx4[4];
  cv::Mat_<float> m4 (4, dims4, 4.5);
  idx4      [3] = 0;
  for     (int w=0; w<dims4[0]; w++) {
    idx4    [0] = w;
    for     (int z=0; z<dims4[0]; z++) {
      idx4  [1] = z;
      for   (int y=0; y<dims4[1]; y++) {
	idx4[2] = y;
	float* yline = m4.ptr<float>(idx4);
	for (int x=0; x<dims4[2]; x++)
	  yline[x] = x+y+z;
      }
    }
  }
  return 0;
}
```

**Comment by alalek** [comment]
Thank you for the report!

IMHO, Passing pointers to buffers without size information is unsafe coding. These interfaces should be dropped due code safety requirements. Like this template and similar non-template methods (returning "uchar*").
Probably we should switch to "std::array" (C++11) for indexes ("std::vector" has huge overhead).

**Comment by azatsman** [comment]
My preference would be to have this method in  `Mat_<>` instead of `Mat`. Seems like it would be the most efficient way to iterate over multi-dimensional arrays. (Somehow `NAryMatIterator` does not look too efficient to me, but I don't claim to know what I am talking about).

**Comment by azatsman** [comment]
Oops, seems I was addressing a different problem since *size information* probably referred to the size of `idx4` in the example. In this case I would vote for different templates for different dimensions. There are already templates for 1,2 and 3 dimensions -- what's wrong with adding 4,5,6,... ?
