### ISSUE TITLE
Issues found when building with MSVC + /std:c++17

### ISSUE THREAD

**Issue by xiangfan-ms** [opencv/opencv#9572]
The C++ compiler team is currently doing daily RWC (Read World Code) testing which includes OpenCV.
We are also working with internal partners and the community to fix source issues exposed by "/std:c++17".

In C++17, STL adds two new functions, std::clamp and std::reduce. Because some source files in OpenCV use 'using namespace std' and OpenCV also has functions with the same name, they can conflict and cause errors.

There are two issues found (both can be fixed if you remove 'using namespace std' :-) ):
1. OpenCV\src\samples\tapi\tvl1_optical_flow.cpp(40): error C2668: 'clamp': ambiguous call to overloaded function

Possible fix:
Use ‘::clamp’ instead of ‘clamp’ below:

	template <typename T> inline T mapValue(T x, T a, T b, T c, T d)
	{
		x = clamp(x, a, b);
		return c + (d - c) * (x - a) / (b - a);
	}

2. OpenCV\src\modules\core\test\test_mat.cpp(316): error C2794: 'value_type': is not a member of any direct or indirect base class of 'std::iterator_traits<_InIt>'

Possible fix:
Replace ‘reduce’ with ‘cv::reduce’. Looks that 'cv::reduce' is already used elsewhere in this file.

**Comment by bhavitvyamalik** [comment]
#9572

**Comment by bhavitvyamalik** [comment]
Fixed issues found when building with MSVC + /std:c++17#9572

**Comment by namish800** [comment]
i would like to work on this issue.
