### ISSUE TITLE
ios use stitching crash libc++abi.dylib: terminating with uncaught exception of type cvflann::anyimpl::bad_any_cast

### ISSUE THREAD

**Issue by xfz211811** [opencv/opencv#9573]
code:
    cv::Mat image1,image2,retImage;
    UIImageToMat(m1, image1);
    UIImageToMat(m2, image2);

    cv::cvtColor(image1,image1,CV_BGRA2BGR);
    cv::cvtColor(image2,image2,CV_BGRA2BGR);
    
    std::vector<cv::Mat> imgs;
    imgs.push_back(image1);
    imgs.push_back(image2);
    
    
    cv::Stitcher stitcher = cv::Stitcher::createDefault();
    cv::Stitcher::Status status = stitcher.stitch(imgs, retImage);

 on cv::Stitcher::Status status = stitcher.stitch(imgs, retImage); crash libc++abi.dylib: terminating with uncaught exception of type cvflann::anyimpl::bad_any_cast

**Comment by eram1205** [comment]
Hi @xfz211811. Could you solve it? Having the same problem using:
cv::Mat_<float> mat = cv::Mat_<float>::ones( 10, 10 );
cv::flann::Index targetKDTree( mat, cv::flann::LinearIndexParams() );

**Comment by alalek** [comment]
Fixed here: #17640
