### ISSUE TITLE
OpenCV 2.4.13.3 failed to build: A duplicate ELSE command was found inside an IF block.

### ISSUE THREAD

**Issue by jerry73204** [opencv/opencv#9584]
##### System information (version)

- OpenCV => 2.4.13.3
- Operating System / Platform => ArchLinux 64-bit
- Compiler => gcc 7.1.1 with ccache 3.3.4 installed

##### Detailed description
Once I run `cmake`, it produced the following error.
```
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Looking for ccache - found (/usr/local/bin/ccache)
CMake Error at cmake/OpenCVCompilerOptions.cmake:21 (else):
  A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
  CMakeLists.txt:432 (include)
```

The error is caused by a syntax error in `cmake/OpenCVCompilerOptions.cmake`.
The else block is placed in the wrong place.
```
       endif()
    else()
      message(STATUS "Looking for ccache - not found")
     endif()
   endif()
 endif()
```

It should be sth like this.
```
       endif()
     endif()
   else()
    message(STATUS "Looking for ccache - not found")
   endif()
 endif()
```

##### Steps to reproduce
Extract the tarball and execute `cmake`.

**Comment by alalek** [comment]
Fixed in 2.4 and master branch: #9408
