### ISSUE TITLE
image show have some errors

### ISSUE THREAD

**Issue by QinXiaoXu** [opencv/opencv#9586]
I accept the unsigned char type data from the camera using the opencv class of mat,
Then use the imshow function to display in the window, but do not know why the image displayed is a bit of a problem,
The following section of the image is normal, but the upper part is abnormal purple. 
What's the reason for that?Can you explain it? Thank you。
<img width="750" alt="2017-09-08 9 10 02" src="https://user-images.githubusercontent.com/31336115/30192297-64da20a4-9479-11e7-8430-6f566d5d4f47.png">

**Comment by mshabunin** [comment]
Please try to ask your question on the forum: http://answers.opencv.org, GitHub is used for issue tracking.
Probably your camera returns image in format other than BGR888.

Feel free to reopen this issue if you find an evidence of a problem in OpenCV.
