### ISSUE TITLE
opencv Mingw32-make error in detectio n_based_tracker.cpp

### ISSUE THREAD

**Issue by kcal2845** [opencv/opencv#9602]
Window 8.1 embedded edtion 64bit

opencv : 3.3.0
mingw32-make : 3.82.90 i686
cmake3.9.2

<pre><code>
C:\Users\john\Desktop\opencv-master\opencv-master\release>mingw32-make
[  0%] Built target gen-pkgconfig
[  2%] Built target zlib
[  5%] Built target libtiff
[  9%] Built target libjpeg
[ 19%] Built target libwebp
[ 22%] Built target libjasper
[ 24%] Built target libpng
[ 30%] Built target IlmImf
[ 36%] Built target libprotobuf
[ 41%] Built target opencv_core
[ 46%] Built target opencv_imgproc
[ 48%] Built target opencv_imgcodecs
[ 49%] Built target opencv_videoio
[ 49%] Built target opencv_highgui
[ 50%] Built target opencv_ts
[ 52%] Built target opencv_test_core
[ 55%] Built target opencv_perf_core
[ 56%] Built target opencv_flann
[ 56%] Built target opencv_test_flann
[ 60%] Built target opencv_test_imgproc
[ 63%] Built target opencv_perf_imgproc
[ 64%] Built target opencv_ml
[ 65%] Built target opencv_test_ml
[ 65%] Building CXX object modules/objdetect/CMakeFiles/opencv_objdetect.dir/src
/detection_based_tracker.cpp.obj
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:175:14: error: 'thread' in namespace 'std' does not name a t
ype
         std::thread second_workthread;
              ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:176:14: error: 'mutex' in namespace 'std' does not name a ty
pe
         std::mutex mtx;
              ^~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:177:14: error: 'condition_variable' in namespace 'std' does
not name a type
         std::condition_variable objectDetectorRun;
              ^~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:178:14: error: 'condition_variable' in namespace 'std' does
not name a type
         std::condition_variable objectDetectorThreadStartStop;
              ^~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'void cv::DetectionBasedTracker::Separat
eDetectionWork::setParameters(const cv::DetectionBasedTracker::Parameters&)':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:143:30: error: 'mutex' is not a member of 'std'
             std::unique_lock<std::mutex> mtx_lock(mtx);
                              ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:143:30: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:143:40: error: template argument 1 is invalid
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                        ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:143:51: error: 'mtx' was not declared in this scope
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                                   ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:143:42: warning: unused variable 'mtx_lock' [-Wunused-variab
le]
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                          ^~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'void cv::DetectionBasedTracker::Separat
eDetectionWork::init()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:156:30: error: 'mutex' is not a member of 'std'
             std::unique_lock<std::mutex> mtx_lock(mtx);
                              ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:156:30: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:156:40: error: template argument 1 is invalid
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                        ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:156:51: error: 'mtx' was not declared in this scope
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                                   ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:164:13: error: 'objectDetectorThreadStartStop' was not decla
red in this scope
             objectDetectorThreadStartStop.notify_one();
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:156:42: warning: unused variable 'mtx_lock' [-Wunused-variab
le]
             std::unique_lock<std::mutex> mtx_lock(mtx);
                                          ^~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In destructor 'virtual cv::DetectionBasedTracker::SeparateD
etectionWork::~SeparateDetectionWork()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:254:5: error: 'second_workthread' was not declared in this s
cope
     second_workthread.join();
     ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'bool cv::DetectionBasedTracker::Separat
eDetectionWork::run()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:261:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> mtx_lock(mtx);
                      ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:261:22: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:261:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:261:43: error: 'mtx' was not declared in this scope
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                           ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:275:5: error: 'second_workthread' was not declared in this s
cope
     second_workthread = std::thread(workcycleObjectDetectorFunction, (void*)thi
s); //TODO: add attributes?
     ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:275:25: error: 'thread' is not a member of 'std'
     second_workthread = std::thread(workcycleObjectDetectorFunction, (void*)thi
s); //TODO: add attributes?
                         ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:276:5: error: 'objectDetectorThreadStartStop' was not declar
ed in this scope
     objectDetectorThreadStartStop.wait(mtx_lock);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'void cv::DetectionBasedTracker::Separat
eDetectionWork::workcycleObjectDetector()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:317:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> mtx_lock(mtx);
                      ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:317:22: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:317:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:317:43: error: 'mtx' was not declared in this scope
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                           ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:323:9: error: 'objectDetectorThreadStartStop' was not declar
ed in this scope
         objectDetectorThreadStartStop.notify_one();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:330:9: error: 'objectDetectorRun' was not declared in this s
cope
         objectDetectorRun.wait(mtx_lock);
         ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:340:14: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
     mtx_lock.unlock();
              ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:357:22: error: request for member 'lock' in 'mtx_lock', whic
h is of non-class type 'int'
             mtx_lock.lock();
                      ^~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:364:26: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
                 mtx_lock.unlock();
                          ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:372:13: error: 'objectDetectorRun' was not declared in this
scope
             objectDetectorRun.wait(mtx_lock);
             ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:380:22: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
             mtx_lock.unlock();
                      ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:431:18: error: request for member 'lock' in 'mtx_lock', whic
h is of non-class type 'int'
         mtx_lock.lock();
                  ^~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:447:18: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
         mtx_lock.unlock();
                  ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'void cv::DetectionBasedTracker::Separat
eDetectionWork::stop()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:462:20: error: 'mutex' is not a member of 'std'
   std::unique_lock<std::mutex> mtx_lock(mtx);
                    ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:462:20: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:462:30: error: template argument 1 is invalid
   std::unique_lock<std::mutex> mtx_lock(mtx);
                              ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:462:41: error: 'mtx' was not declared in this scope
   std::unique_lock<std::mutex> mtx_lock(mtx);
                                         ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:468:18: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
         mtx_lock.unlock();
                  ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:479:5: error: 'objectDetectorRun' was not declared in this s
cope
     objectDetectorRun.notify_one();
     ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:480:5: error: 'objectDetectorThreadStartStop' was not declar
ed in this scope
     objectDetectorThreadStartStop.wait(mtx_lock);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:482:14: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
     mtx_lock.unlock();
              ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'void cv::DetectionBasedTracker::Separat
eDetectionWork::resetTracking()':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:495:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> mtx_lock(mtx);
                      ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:495:22: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:495:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:495:43: error: 'mtx' was not declared in this scope
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                           ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:512:14: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
     mtx_lock.unlock();
              ^~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp: In member function 'bool cv::DetectionBasedTracker::Separat
eDetectionWork::communicateWithDetectingThread(const cv::Mat&, std::vector<cv::R
ect_<int> >&)':
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:533:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> mtx_lock(mtx);
                      ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:533:22: error: 'mutex' is not a member of 'std'
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:533:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                ^
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:533:43: error: 'mtx' was not declared in this scope
     std::unique_lock<std::mutex> mtx_lock(mtx);
                                           ^~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:566:9: error: 'objectDetectorRun' was not declared in this s
cope
         objectDetectorRun.notify_one();
         ^~~~~~~~~~~~~~~~~
C:\Users\john\Desktop\opencv-master\opencv-master\modules\objdetect\src\detectio
n_based_tracker.cpp:573:14: error: request for member 'unlock' in 'mtx_lock', wh
ich is of non-class type 'int'
     mtx_lock.unlock();
              ^~~~~~
modules\objdetect\CMakeFiles\opencv_objdetect.dir\build.make:121: recipe for tar
get 'modules/objdetect/CMakeFiles/opencv_objdetect.dir/src/detection_based_track
er.cpp.obj' failed
mingw32-make[2]: *** [modules/objdetect/CMakeFiles/opencv_objdetect.dir/src/dete
ction_based_tracker.cpp.obj] Error 1
CMakeFiles\Makefile2:2096: recipe for target 'modules/objdetect/CMakeFiles/openc
v_objdetect.dir/all' failed
mingw32-make[1]: *** [modules/objdetect/CMakeFiles/opencv_objdetect.dir/all] Err
or 2
Makefile:161: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
</code></pre>

What do i have to do? Thanks.

**Comment by mshabunin** [comment]
@kcal2845 , try to use _mingw_w64_.

**Comment by komms** [comment]
did it work using mingw_w64 ? @kcal2845

**Comment by kcal2845** [comment]
@komms well... I just changed the environment with the python. so I don't remember well, but it wasn't solved as far as I remembered.

**Comment by mshabunin** [comment]
@komms, I've been able to build the latest _master_ branch version of OpenCV with mingw-w64 (based on GCC 7.2) two days ago. There was one issue with AVX-512 dispatching so I had to disable it by providing `-DCPU_DISPATCH=` option to cmake.
