### ISSUE TITLE
Memory leak in cvUndistortPoints()

### ISSUE THREAD

**Issue by vagran** [opencv/opencv#9605]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04.3 64bit
- Compiler => GCC 5.4.0

##### Detailed description

I have discovered huge memory leak in my program using OpenCV. VSS jumps from 7GB to ~21GB after a single call of getOptimalNewCameraMatrix() function. Only the first four arguments specified, the rest are default. I'm not sure if it is fully reproducible, looks to be too simple scenario, and probably it worked some time in past for me, I did not notice this before. But it is constantly reproducing in my program. May be it is dependent on some garbage on stack.
I have investigated this a bit deeper, and found the following problematic calls chain: getOptimalNewCameraMatrix() -> cvGetOptimalNewCameraMatrix() -> icvGetRectangles() -> cvUndistortPoints() -> cv::setIdentity(). So the problem actually is inside cvUndistortPoints(), specifically when its matR parameter is null. The following simplified code taken from cvUndistortPoints() gives me the same huge memory leak:

```
double RR[3][3];
CvMat _RR=cvMat(3, 3, CV_64F, RR);
cv::Mat m = cv::cvarrToMat(&_RR);
cv::setIdentity(m, 1);
```

**Comment by sovrasov** [comment]
Valgrind doesn't report any issue with the provided reproducer.
>OpenCV => 3.2

Try to use the latest OpenCV version (3.3 or `master`).

**Comment by vagran** [comment]
Ok, may be it is something specific to my system. However I still cannot figure out, where the problem is. May be there is some dynamic loading of some libraries during this call. My app is Java with native part in C++, which uses OpenCV. I remember that recently I have installed CUDA SDK to my system, may be some huge development libraries are now loaded.

**Comment by vagran** [comment]
After removing CUDA SDK the problem has gone.
