### ISSUE TITLE
libgfortran.so.3, needed by //opt/conda/lib/libopenblas.so.0, not found

### ISSUE THREAD

**Issue by niyazpk** [opencv/opencv#9608]
OpenCV: 3.3.0
Contrib: 3.3.0

Trying to build OpenCV and contrib in a docker container. I am getting the following error:

    [ 66%] Built target opencv_highgui
    Scanning dependencies of target opencv_waldboost_detector
    [ 67%] Building CXX object modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/waldboost_detector.cpp.o
    [ 67%] Linking CXX executable ../../../../bin/opencv_waldboost_detector
    /usr/bin/ld: warning: libgfortran.so.3, needed by //opt/conda/lib/libopenblas.so.0, not found (try using -rpath or -rpath-link)
    //opt/conda/lib/libopenblas.so.0: undefined reference to `_gfortran_etime@GFORTRAN_1.0'
    //opt/conda/lib/libopenblas.so.0: undefined reference to `_gfortran_pow_i4_i4@GFORTRAN_1.0'
    //opt/conda/lib/libopenblas.so.0: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
    //opt/conda/lib/libopenblas.so.0: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
    collect2: error: ld returned 1 exit status
    modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/build.make:101: recipe for target 'bin/opencv_waldboost_detector' failed
    make[2]: *** [bin/opencv_waldboost_detector] Error 1
    make[1]: *** [modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all] Error 2
    CMakeFiles/Makefile2:5006: recipe for target 'modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all' failed
    Makefile:160: recipe for target 'all' failed
    make: *** [all] Error 2
    The command '/bin/sh -c wget https://github.com/opencv/opencv/archive/3.3.0.zip && unzip 3.3.0.zip && mkdir /opencv-3.3.0/cmake_binary && cd /opencv-3.3.0/cmake_binary && cmake -DCMAKE_CXX_FLAGS=-std=c++11   -DBUILD_TIFF=ON   -DBUILD_opencv_java=OFF   -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib-3.3.0/modules   -DWITH_CUDA=OFF   -DENABLE_AVX=ON   -DWITH_OPENGL=ON   -DWITH_OPENCL=ON   -DWITH_IPP=ON   -DWITH_TBB=ON   -DWITH_EIGEN=ON   -DWITH_V4L=ON   -DBUILD_TESTS=OFF   -DBUILD_PERF_TESTS=OFF   -DCMAKE_BUILD_TYPE=RELEASE   -DCMAKE_INSTALL_PREFIX=$(python3.6 -c "import sys; print(sys.prefix)")   -DPYTHON_EXECUTABLE=$(which python3.6)   -DPYTHON_INCLUDE_DIR=$(python3.6 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")   -DPYTHON_PACKAGES_PATH=$(python3.6 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") .. && make install && rm /3.3.0.zip && rm -r /opencv-3.3.0' returned a non-zero code: 2

Configuration:

    -- General configuration for OpenCV 3.3.0 =====================================
    --   Version control:               unknown
    --
    --   Extra modules:
    --     Location (extra):            /opencv_contrib-3.3.0/modules
    --     Version control (extra):     unknown
    --
    --   Platform:
    --     Timestamp:                   2017-09-11T22:18:41Z
    --     Host:                        Linux 4.9.41-moby x86_64
    --     CMake:                       3.5.1
    --     CMake generator:             Unix Makefiles
    --     CMake build tool:            /usr/bin/make
    --     Configuration:               RELEASE
    --
    --   CPU/HW features:
    --     Baseline:                    SSE SSE2 SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 AVX
    --       requested:                 SSE3
    --       required:                  AVX
    --     Dispatched code generation:  FP16 AVX2
    --       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
    --       FP16 (1 files):            + FP16
    --       AVX2 (7 files):            + FP16 FMA3 AVX2
    --
    --   C/C++:
    --     Built as dynamic libs?:      YES
    --     C++11:                       YES
    --     C++ Compiler:                /usr/bin/c++  (ver 5.4.0)
    --     C++ flags (Release):         -std=c++11   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    --     C++ flags (Debug):           -std=c++11   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    --     C Compiler:                  /usr/bin/cc
    --     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    --     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    --     Linker flags (Release):
    --     Linker flags (Debug):
    --     ccache:                      NO
    --     Precompiled headers:         YES
    --     Extra dependencies:          /opt/conda/lib/libopenblas.so /opt/conda/lib/libpng.so /usr/lib/x86_64-linux-gnu/libjasper.so /opt/conda/lib/libjpeg.so avcodec-ffmpeg avformat-ffmpeg avutil-ffmpeg swscale-ffmpeg /opt/conda/lib/libhdf5.so /usr/lib/x86_64-linux-gnu/librt.so /usr/lib/x86_64-linux-gnu/libpthread.so /opt/conda/lib/libz.so /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libm.so dl m pthread rt /usr/lib/x86_64-linux-gnu/libtbb.so
    --     3rdparty dependencies:
    --
    --   OpenCV modules:
    --     To be built:                 core flann hdf imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video xphoto bgsegm dnn dnn_modern face fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow stitching python3
    --     Disabled:                    world contrib_world
    --     Disabled by dependency:      -
    --     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 ts viz cnn_3dobj cvv freetype matlab sfm
    --
    --   GUI:
    --     QT:                          NO
    --     GTK+:                        NO
    --     GThread :                    NO
    --     GtkGlExt:                    NO
    --     OpenGL support:              NO
    --     VTK support:                 NO
    --
    --   Media I/O:
    --     ZLib:                        /opt/conda/lib/libz.so (ver 1.2.8)
    --     JPEG:                        /opt/conda/lib/libjpeg.so (ver 90)
    --     WEBP:                        build (ver encoder: 0x020e)
    --     PNG:                         /opt/conda/lib/libpng.so (ver 1.6.28)
    --     TIFF:                        build (ver 42 - 4.0.2)
    --     JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
    --     OpenEXR:                     build (ver 1.7.1)
    --     GDAL:                        NO
    --     GDCM:                        NO
    --
    --   Video I/O:
    --     DC1394 1.x:                  NO
    --     DC1394 2.x:                  NO
    --     FFMPEG:                      YES
    --       avcodec:                   YES (ver 56.60.100)
    --       avformat:                  YES (ver 56.40.101)
    --       avutil:                    YES (ver 54.31.100)
    --       swscale:                   YES (ver 3.1.101)
    --       avresample:                NO
    --     GStreamer:                   NO
    --     OpenNI:                      NO
    --     OpenNI PrimeSensor Modules:  NO
    --     OpenNI2:                     NO
    --     PvAPI:                       NO
    --     GigEVisionSDK:               NO
    --     Aravis SDK:                  NO
    --     UniCap:                      NO
    --     UniCap ucil:                 NO
    --     V4L/V4L2:                    NO/YES
    --     XIMEA:                       NO
    --     Xine:                        NO
    --     Intel Media SDK:             NO
    --     gPhoto2:                     NO
    --
    --   Parallel framework:            TBB (ver 4.4 interface 9002)
    --
    --   Trace:                         YES (with Intel ITT)
    --
    --   Other third-party libraries:
    --     Use Intel IPP:               2017.0.2 [2017.0.2]
    --                at:               /opencv-3.3.0/cmake_binary/3rdparty/ippicv/ippicv_lnx
    --     Use Intel IPP IW:            prebuilt binaries (2017.0.2)
    --     Use Intel IPP Async:         NO
    --     Use VA:                      NO
    --     Use Intel VA-API/OpenCL:     NO
    --     Use Lapack:                  YES (/opt/conda/lib/libopenblas.so)
    --     Use Eigen:                   NO
    --     Use Cuda:                    NO
    --     Use OpenCL:                  YES
    --     Use OpenVX:                  NO
    --     Use custom HAL:              NO
    --
    --   OpenCL:                        <Dynamic loading of OpenCL library>
    --     Include path:                /opencv-3.3.0/3rdparty/include/opencl/1.2
    --     Use AMDFFT:                  NO
    --     Use AMDBLAS:                 NO
    --
    --   Python 2:
    --     Interpreter:                 NO
    --
    --   Python 3:
    --     Interpreter:                 /opt/conda/bin/python3 (ver 3.6.2)
    --     Libraries:                   /opt/conda/lib/libpython3.6m.so (ver 3.6.2)
    --     numpy:                       /opt/conda/lib/python3.6/site-packages/numpy/core/include (ver 1.12.1)
    --     packages path:               lib/python3.6/site-packages
    --
    --   Python (for build):            /opt/conda/bin/python3
    --
    --   Java:
    --     ant:                         NO
    --     JNI:                         NO
    --     Java wrappers:               NO
    --     Java tests:                  NO
    --
    --   Matlab:                        Matlab not found or implicitly disabled
    --
    --   Documentation:
    --     Doxygen:                     NO
    --
    --   Tests and samples:
    --     Tests:                       NO
    --     Performance tests:           NO
    --     C/C++ Examples:              NO
    --
    --   Install path:                  /opt/conda
    --
    --   cvconfig.h is in:              /opencv-3.3.0/cmake_binary
    -- -----------------------------------------------------------------
    --
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opencv-3.3.0/cmake_binary

I am not sure if this is an OpenCV issue, a contrib issue or something else. Any help would be really appreciated. Thanks!

**Comment by franciscorba** [comment]
I have the same issue with opencv 3.4.4:

```
[ 39%] Linking CXX executable ../../bin/opencv_version
/usr/bin/ld: warning: libgfortran.so.3, needed by /home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0, not found (try using -rpath or -rpath-link)
/home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0: undefined reference to `_gfortran_etime@GFORTRAN_1.0'
/home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0: undefined reference to `_gfortran_pow_i4_i4@GFORTRAN_1.0'
/home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
/home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
collect2: error: ld returned 1 exit status
```
The lib is there:
```
ldd /home/brisa/anaconda2/envs/frbarbos/lib/libopenblas.so.0
	linux-vdso.so.1 (0x00007ffed7dfd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc073a1f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc073801000)
	**libgfortran.so.3 => /home/brisa/anaconda2/envs/frbarbos/lib/./libgfortran.so.3 (0x00007fc0734f8000)**
	libc.so.6 => /lib64/libc.so.6 (0x00007fc073132000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e766426000)
	libgcc_s.so.1 => /home/brisa/anaconda2/envs/frbarbos/lib/././libgcc_s.so.1 (0x00007fc07311b000)
```
