### ISSUE TITLE
MinGW (Windows): build error for opencv3.3.0+opencv_contrib3.3.0

### ISSUE THREAD

**Issue by xiaopengs** [opencv/opencv#9611]
modules\java\android_test\CMakeFiles\opencv_test_java.dir\build.make:190: recipe
 for target 'modules/java/android_test/.build/bin/OpenCVTest-debug.apk' failed
mingw32-make[2]: *** [modules/java/android_test/.build/bin/OpenCVTest-debug.apk]
 Error 1
CMakeFiles\Makefile2:8025: recipe for target 'modules/java/android_test/CMakeFil
es/opencv_test_java.dir/all' failed
mingw32-make[1]: *** [modules/java/android_test/CMakeFiles/opencv_test_java.dir/all] Error 2
Makefile:161: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by alalek** [comment]
MinGW is not supported officially, so probably we would not configure build environment to reproduce this problem.
Build questions on custom configurations should go to Users OpenCV Q/A forum: http://answers.opencv.org (but please extend you log - important information is above the cut)
Please return back if your have clear reason of mentioned problem and OpenCV needs fix.

**Comment by xiaopengs** [comment]
3Q
