### ISSUE TITLE
May be a bug in initializeContextFromD3D9Device function, and initializeContextFromDirect3DDevice9Ex,  initializeContextFromD3D11Device

### ISSUE THREAD

**Issue by oujinhaoai** [opencv/opencv#9612]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler =>  Visual Studio 2015

##### Steps to reproduce

When I have compiled the solution,  run the (EXAMPLE_DIRECTX) d3d9_interop , (EXAMPLE_DIRECTX) d3d9ex_interop and (EXAMPLE_DIRECTX) d3d11_interop, the application crash at code "status = clGetDeviceIDsFromDX9MediaAdapterKHR(platforms[i], 1, &type, ".... But if I add some code before it to check the "cl_khr_dx9_media_sharing" or "cl_khr_dx11_sharing" extension support, if not, skip this platform and device,  it's ok, the application can run properly. My pc has two platform(gpu): i5 gpu, and gtx 750.  I'm curious about why the application can run use i5 gpu, but gtx 750 can't. But in any case, when user call initializeContextFromD3D9Device function, it can return failure, but can't crash.

**Comment by alalek** [comment]
This [comment](https://github.com/opencv/opencv/blob/3.3.0/modules/core/src/directx.cpp#L263) says that configuration for OpenCL platform selection is not supported yet.

Could you add dump of OpenCL configuration via `clinfo` tool?
What GPU is used for graphics processing (output) in Windows?

**Comment by oujinhaoai** [comment]
@alalek , Thinks for your reply.  The screenshot on vs2015 when crashing:
![image](https://user-images.githubusercontent.com/11285038/30314758-574423b4-97d4-11e7-96d3-bb3ec11dc92d.png)

the mini dump file:
[directx-example-d3d9ex_interop_20170912.zip](https://github.com/opencv/opencv/files/1295203/directx-example-d3d9ex_interop_20170912.zip)

the mini dump with stack memory if biger than 10M after compressed, so I just uploard this mini dump file.

The GTX 750 is the default GPU,  I have two monitor connect to the GTX 750 HDMI and DVI port.

**Comment by alalek** [comment]
Thanks for update!

Looks like It is crashed inside of OpenCL runtime code. This is not a normal behavior from OpenCL.
Actually we don't test this with NVIDIA GPUs - AMD GPU / APUs was tested in 2014 and Intel GPUs was tested in 2015.
What version of OpenCL API is provided by NVIDIA drivers (OpenCL 1.1 probably would not work)?

**Comment by oujinhaoai** [comment]
@alalek , follow is the gpu-z info
![image](https://user-images.githubusercontent.com/11285038/30316806-efcba0a2-97da-11e7-9bb0-8d44e25017ea.png)

and I use opencl prinf the gpu info:
![image](https://user-images.githubusercontent.com/11285038/30317121-c8648398-97db-11e7-9c60-de4a93e225b5.png)


also,  I had tried use both of the opencl sdk in cuda 8.0 and intel opencl sdk to compile the opencv solution, but the result is the same.

**Comment by ikarusx** [comment]
So, sorry for reviving this, but seems like a solution for that is very hard to find!
Have you closed because you found a solution?
If so, what would be it?
I have almost the same specs.
Regards.

**Comment by dorimu** [comment]
I suppose this is because some NVIDIA GPUs support a extension called cl_nv_d3d9_sharing, instead of cl_khr_dx9_media_sharing extension used in directx.cpp. I have almost the same question. My GPU is NVIDIA GT730, and I found my opencl doesn't support cl_khr_dx9_media_sharing extension. @oujinhaoai @alalek @ikarusx
