### ISSUE TITLE
error: no type named ‘channel_type’ compiling multiple modules

### ISSUE THREAD

**Issue by fifothekid** [opencv/opencv#9614]
I've been compiling the latest verson of OpenCV with OpenCV Contrib, Tesseract and Leptonica and everything has been compiling without any proble till the last week. I use the Non-free, C++11 options and disable the CUDA build since I'm using GCC .
The error I started getting is the following:

> In file included from /home/fifo/Documentos/opencv/modules/core/include/opencv2/core.hpp:59:0,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video/tracking.hpp:47,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video.hpp:56,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/include/opencv2/bgsegm.hpp:43,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/precomp.hpp:45,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp:51:
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.hpp: In instantiation of ‘class cv::Mat_<unsigned int>’:
> /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp:197:24:   required from here
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.hpp:2149:50: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>      typedef typename DataType<_Tp>::channel_type channel_type;
>                                                   ^~~~~~~~~~~~
> In file included from /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.hpp:3638:0,
>                  from /home/fifo/Documentos/opencv/modules/core/include/opencv2/core.hpp:59,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video/tracking.hpp:47,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video.hpp:56,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/include/opencv2/bgsegm.hpp:43,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/precomp.hpp:45,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp:51:
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1554:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::Mat_(const Vec<typename DataType<_Tp>::channel_type, n>& vec, bool copyData)
>  ^~~~~~~~~
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1563:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::Mat_(const Matx<typename DataType<_Tp>::channel_type, m, n>& M, bool copyData)
>  ^~~~~~~~~
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1572:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::Mat_(const Point_<typename DataType<_Tp>::channel_type>& pt, bool copyData)
>  ^~~~~~~~~
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1581:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::Mat_(const Point3_<typename DataType<_Tp>::channel_type>& pt, bool copyData)
>  ^~~~~~~~~
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1910:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::operator Vec<typename DataType<_Tp>::channel_type, n>() const
>  ^~~~~~~~~
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1923:1: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
>  Mat_<_Tp>::operator Matx<typename DataType<_Tp>::channel_type, m, n>() const
>  ^~~~~~~~~
> In file included from /home/fifo/Documentos/opencv/modules/core/include/opencv2/core.hpp:56:0,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video/tracking.hpp:47,
>                  from /home/fifo/Documentos/opencv/modules/video/include/opencv2/video.hpp:56,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/include/opencv2/bgsegm.hpp:43,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/precomp.hpp:45,
>                  from /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp:51:
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/traits.hpp: In instantiation of ‘struct cv::traits::Type<unsigned int>’:
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1472:41:   required from ‘cv::Mat_<_Tp>::Mat_() [with _Tp = unsigned int]’
> /home/fifo/Documentos/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp:64:5:   required from here
> /home/fifo/Documentos/opencv/modules/core/include/opencv2/core/traits.hpp:366:8: error: ‘type’ is not a member of ‘cv::DataType<unsigned int>’
>  { enum { value = DataType<T>::type }; };
>         ^
> modules/bgsegm/CMakeFiles/opencv_bgsegm.dir/build.make:86: recipe for target 'modules/bgsegm/CMakeFiles/opencv_bgsegm.dir/src/bgfg_gmg.cpp.o' failed
> make[2]: *** [modules/bgsegm/CMakeFiles/opencv_bgsegm.dir/src/bgfg_gmg.cpp.o] Error 1
> CMakeFiles/Makefile2:3745: recipe for target 'modules/bgsegm/CMakeFiles/opencv_bgsegm.dir/all' failed
> make[1]: *** [modules/bgsegm/CMakeFiles/opencv_bgsegm.dir/all] Error 2
> make[1]: ** Esperando que outros processos terminem.

I'm pretty sure that the problem is in OpenCV because checking-out the 3.3 release compiles everything. And if I disable the bgsem module it continues the compilation process until another module gives a similar error
Any suggested solution?

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized. Different versions are not tested for compatibility and may not work.

You lost this patch in opencv_contrib: https://github.com/opencv/opencv_contrib/pull/1352/files

**Comment by fifothekid** [comment]
they are already synchronized
same error on both Visaul Studio 2017 and GCC 7

**Comment by alalek** [comment]
This patch is lost in your case: https://github.com/opencv/opencv_contrib/pull/1352/files

**Comment by fifothekid** [comment]
I had to remove both the opencv and opencv_contrib directories and make git clone and build for them to work
thank you!
