### ISSUE TITLE
Win pack - Missing opencv_core330.dll

### ISSUE THREAD

**Issue by tinohager** [opencv/opencv#9620]
OpenCV: 3.3.0
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2017

I have download https://github.com/opencv/opencv/releases/download/3.3.0/opencv-3.3.0-vc14.exe and extract it.

For my Visual Studio Project i need opencv_core330.dll but it is not available in the folder.

After extract Win pack

    opencv\build\x64\vc14\bin

    -- opencv_ffmpeg330_64.dll
    -- opencv_world330.dll
    -- opencv_world330d.dll

My expectation

    opencv\build\x64\vc14\bin

    -- opencv_core330.dll
    -- opencv_imgproc330.dll
    -- opencv_highgui330.dll
    -- opencv_videoio330.dll

**Comment by tompollok** [comment]
just link against opencv_world330.dll instead of opencv_core33.dll. opencv_world is a single dll that contains functions and datastructures from all your listed modules.

**Comment by tinohager** [comment]
is the opencv_world330.dll also available on cross platform development? (linux and windows)

**Comment by alalek** [comment]
It is available via CMake option `-DBUILD_opencv_world=ON` (special build mode of OpenCV modules)

**Comment by selflover** [comment]
C:\Users\xyue\Downloads\opencv\build\x64\vc14\bin\opencv_ffmpeg330_64.dll : fatal error LNK1107: 文件无效或损坏: 无法在 0x390 处读取 may i ask a question about what is wrong about this?
