### ISSUE TITLE
cmake ndk r14 opencv3.3.0 how to compiler arm64 

### ISSUE THREAD

**Issue by yyd-luojie** [opencv/opencv#9621]
##### System information (version)

- OpenCV => :3.3.0:
- Operating System / Platform => Windows 64:
- Compiler => :winGW,cMake:

##### Detailed description
Opencv is clone from github
use winGW 7.1.0  as the compiler

after "Configure" , everything is OK,
but default ANDROID_ABI is armeabi-v7a and there is no arm64 item;
so my problem is coming,how can i get arm64 item

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
