### ISSUE TITLE
IwException from KAZE

### ISSUE THREAD

**Issue by senortres** [opencv/opencv#9628]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Windows 10 Pro, 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I'm seeing exceptions thrown by Intel's IPP while doing a feature detection using a KAZE algorithm object's detect() call.  The exception occurs while executing \modules\features2d\src\kaze\KAZEFeatures.cpp's KAZEFeatures::Create_Nonlinear_Scale_Space(), where it starts building Gaussian blurs for its scale space, specifically this line (currently line 104 in rev 73c3d14):

` gaussian_2D_convolution(evolution_[0].Lt, evolution_[0].Lt, 0, 0, options_.soffset);`

This makes its way down into the imgproc module and then IPP where iwiFilterGaussian() returns an IppStatus of 'ippStsInplaceModeNotSupportedErr (-9997)' which causes it to throw an IwException w/that value.  I *believe* that status is iwiFilterGaussian() signaling that its pSrcImage and pDstImage inputs can't be the same (for an 'in-place' blur in pSrcImage).

My KAZE output appears reasonable despite this--I'm getting keypoints, and they look good--I'm just fearful that one or more failed blurs could be introducing unnecessary noise and keeping the algorithm from its full potential.

Here's everything I can find in my cmake setup related to IPP...most/all should be at default:

BUILD\BUILD_IPP_IW=true

BUILD\BUILD_WITH_DYNAMIC_IPP=false

##### Steps to reproduce

Run the tutorial at:

https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/features2D/AKAZE_match.cpp

Note that no exceptions occur.  Next replace usage of AKAZE with KAZE at line 25:

`	Ptr<KAZE> akaze = KAZE::create();`

Build/run, observe the exception (5 occurrences of the following):

` Exception thrown at (address) in opencv_test.exe: Microsoft C++ exception: ipp::IwException at memory location (address).`

Note this is related to the question I posted at:

http://answers.opencv.org/question/173245/iwexception-from-kaze/

**Comment by sovrasov** [comment]
I didn't observe such problems on Ubuntu in Release/Debug mode.
You can try https://github.com/opencv/opencv/commit/100894ba588b964ea90a86b8092fb288cf46d848 to disable IPP call in case of inplace input.

**Comment by senortres** [comment]
Thanks a ton VS, that will avoid the exception at least.  Strange that the exception isn't triggering on Ubuntu in debug mode.

**Comment by sovrasov** [comment]
I can't reproduce this on windows with the latest `master`. Exception should be caught in `ipp_GaussianBlur` function.

**Comment by aleksey-nikolaev** [comment]
- OpenCV => 3.3.0
- Compiler => Visual Studio 2015

Hi, I got same exception when I try this code

    cv::Mat_<cv::Vec2b> A(10, 10);
    cv::Mat B;
    cv::dilate(A, B, cv::Mat_<uchar>::ones(3, 3));

The exception occurs because `A` has two channels (or more than 4). There no exception if `A` is 1, 3 or 4 channel matrix

**Comment by alalek** [comment]
> ippStsInplaceModeNotSupportedErr

This exception is handled. Consider to configure your MSVS debugger to avoid blaming on handled exceptions.

**Comment by senortres** [comment]
It's handled in the code that's been fixed, thanks a ton...but code like /modules/features2d/src/kaze/KAZEFeatures.cpp is still trying to do in-place operations by calling gaussian_2D_convolution(address, same address, ...).  That call will now resolve to a no-op, which is good, but KAZEFeatures.cpp should probably be fixed.  Until it is, its blurs will fail and its scale space will likely be malformed...which would affect its accuracy.

**Comment by janoc** [comment]
The same problem occurs in the ORB code (orb.cpp: 1166). The IPP code needs to be fixed when the spec says that GaussianBlur supports in-place operation. Even though the resulting exception is caught, an exception on every frame slows the program down quite significantly.
