### ISSUE TITLE
Different face detection results using Mat and UMat images

### ISSUE THREAD

**Issue by mhaghighat** [opencv/opencv#9630]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

The `detectMultiScale()` gives different results when you feed in the UMat form of the same image.

##### Steps to reproduce

The `facesMat` and the `facesUMat` generated by the following code are different:

```
cv::CascadeClassifier faceCascade;
faceCascade.load("haarcascade_frontalface_alt.xml");

// Having a  cv::Mat image   which includes a near frontal face:
faceCascade.detectMultiScale(image, facesMat, 1.08, 4, 0 | CV_HAAR_SCALE_IMAGE, cv::Size(80, 80));

cv::UMat imageUMat = image.getUMat(cv::ACCESS_READ);
faceCascade.detectMultiScale(imageUMat, facesUMat, 1.08, 4, 0 | CV_HAAR_SCALE_IMAGE, cv::Size(80, 80));
```

**Comment by berak** [comment]
reproduced on win10, opencv3.3(), mingw64,

```
//ocl::setUseOpenCL(0);
Mat image = imread("img/h4.jpg",0);
CascadeClassifier faceCascade("haarcascade_frontalface_alt.xml");
vector<Rect> facesM, facesU;

faceCascade.detectMultiScale(image, facesM);
cout << "Mat" << endl << Mat(facesM) << endl << endl;

UMat imageUMat = image.getUMat(cv::ACCESS_READ);
faceCascade.detectMultiScale(imageUMat, facesU);
cout << "UMat" << endl << Mat(facesU) << endl << endl;
```
```
Mat
[282, 211, 425, 425]

UMat
[282, 211, 425, 425;
 30, 573, 53, 53]
```

[image used](https://i.imgur.com/QcmSufh.jpg)

**Comment by sovrasov** [comment]
In case if `UMat` is passed as input image, `CascadeClassifier` will try to use OpenCL implementation.
There is no bit-exactness between CPU and OCL implementations.
