### ISSUE TITLE
OpenCV libaries not found

### ISSUE THREAD

**Issue by AV11D724** [opencv/opencv#9632]
I am using the kdenlive video editior with opencv libaries and it seems as if kdenlive cannot find the opencv libaries. Here is my GDB debug session with kdenlive: https://hastebin.com/enuxajelog.go

**Comment by berak** [comment]
since you [already asked here](http://answers.opencv.org/question/174316/opencv-libaries-not-found/) , we will try to solve your problem from there.

this is the opencv library issue tracker, and you're not reporting a bug, so would you be so kind to close this issue ?
