### ISSUE TITLE
Unable to find a javac compiler

### ISSUE THREAD

**Issue by orange-jacky** [opencv/opencv#9637]
[root@iz2zec6q1zmdj7w594xa50z build]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core

git clone https://github.com/opencv/opencv.git
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..

[root@iz2zec6q1zmdj7w594xa50z build]# make
[  0%] Generate opencv.pc
[  0%] Built target gen-pkgconfig
[  9%] Built target libwebp
[ 14%] Built target IlmImf
[ 14%] Built target ittnotify
[ 19%] Built target libprotobuf
[ 19%] Built target opencv_core_pch_dephelp
[ 19%] Built target pch_Generate_opencv_core
[ 24%] Built target opencv_core
[ 24%] Built target opencv_ts_pch_dephelp
[ 24%] Built target pch_Generate_opencv_ts
[ 24%] Built target opencv_imgproc_pch_dephelp
[ 24%] Built target pch_Generate_opencv_imgproc
[ 29%] Built target opencv_imgproc
[ 29%] Built target opencv_imgcodecs_pch_dephelp
[ 29%] Built target pch_Generate_opencv_imgcodecs
[ 30%] Built target opencv_imgcodecs
[ 30%] Built target opencv_videoio_pch_dephelp
[ 30%] Built target pch_Generate_opencv_videoio
[ 31%] Built target opencv_videoio
[ 31%] Built target opencv_highgui_pch_dephelp
[ 31%] Built target pch_Generate_opencv_highgui
[ 32%] Built target opencv_highgui
[ 33%] Built target opencv_ts
[ 33%] Built target opencv_perf_core_pch_dephelp
[ 33%] Built target pch_Generate_opencv_perf_core
[ 36%] Built target opencv_perf_core
[ 36%] Built target opencv_test_core_pch_dephelp
[ 36%] Built target pch_Generate_opencv_test_core
[ 39%] Built target opencv_test_core
[ 39%] Built target opencv_flann_pch_dephelp
[ 39%] Built target pch_Generate_opencv_flann
[ 39%] Built target opencv_flann
[ 39%] Built target opencv_test_flann_pch_dephelp
[ 39%] Built target pch_Generate_opencv_test_flann
[ 39%] Built target opencv_test_flann
[ 39%] Built target opencv_perf_imgproc_pch_dephelp
[ 39%] Built target pch_Generate_opencv_perf_imgproc
[ 41%] Built target opencv_perf_imgproc
[ 41%] Built target opencv_test_imgproc_pch_dephelp
[ 41%] Built target pch_Generate_opencv_test_imgproc
[ 44%] Built target opencv_test_imgproc
[ 44%] Built target opencv_ml_pch_dephelp
[ 44%] Built target pch_Generate_opencv_ml
[ 45%] Built target opencv_ml
[ 45%] Built target opencv_test_ml_pch_dephelp
[ 45%] Built target pch_Generate_opencv_test_ml
[ 46%] Built target opencv_test_ml
[ 46%] Built target opencv_objdetect_pch_dephelp
[ 47%] Built target pch_Generate_opencv_objdetect
[ 48%] Built target opencv_objdetect
[ 48%] Built target opencv_perf_objdetect_pch_dephelp
[ 49%] Built target pch_Generate_opencv_perf_objdetect
[ 50%] Built target opencv_perf_objdetect
[ 50%] Built target opencv_test_objdetect_pch_dephelp
[ 51%] Built target pch_Generate_opencv_test_objdetect
[ 51%] Built target opencv_test_objdetect
[ 51%] Built target opencv_photo_pch_dephelp
[ 52%] Built target pch_Generate_opencv_photo
[ 53%] Built target opencv_photo
[ 53%] Built target opencv_perf_photo_pch_dephelp
[ 53%] Built target pch_Generate_opencv_perf_photo
[ 53%] Built target opencv_perf_photo
[ 53%] Built target opencv_test_photo_pch_dephelp
[ 53%] Built target pch_Generate_opencv_test_photo
[ 54%] Built target opencv_test_photo
[ 54%] Built target opencv_video_pch_dephelp
[ 54%] Built target pch_Generate_opencv_video
[ 55%] Built target opencv_video
[ 55%] Built target opencv_perf_video_pch_dephelp
[ 55%] Built target pch_Generate_opencv_perf_video
[ 56%] Built target opencv_perf_video
[ 56%] Built target opencv_test_video_pch_dephelp
[ 56%] Built target pch_Generate_opencv_test_video
[ 57%] Built target opencv_test_video
[ 57%] Built target opencv_viz_pch_dephelp
[ 58%] Built target pch_Generate_opencv_viz
[ 59%] Built target opencv_viz
[ 59%] Built target opencv_test_viz_pch_dephelp
[ 59%] Built target pch_Generate_opencv_test_viz
[ 59%] Built target opencv_test_viz
[ 59%] Built target opencv_dnn_pch_dephelp
[ 59%] Built target pch_Generate_opencv_dnn
[ 63%] Built target opencv_dnn
[ 63%] Built target opencv_perf_dnn_pch_dephelp
[ 63%] Built target pch_Generate_opencv_perf_dnn
[ 63%] Built target opencv_perf_dnn
[ 63%] Built target opencv_test_dnn_pch_dephelp
[ 63%] Built target pch_Generate_opencv_test_dnn
[ 63%] Built target opencv_test_dnn
[ 64%] Built target opencv_perf_imgcodecs_pch_dephelp
[ 64%] Built target pch_Generate_opencv_perf_imgcodecs
[ 64%] Built target opencv_perf_imgcodecs
[ 64%] Built target opencv_test_imgcodecs_pch_dephelp
[ 64%] Built target pch_Generate_opencv_test_imgcodecs
[ 65%] Built target opencv_test_imgcodecs
[ 65%] Built target opencv_shape_pch_dephelp
[ 65%] Built target pch_Generate_opencv_shape
[ 65%] Built target opencv_shape
[ 66%] Built target opencv_test_shape_pch_dephelp
[ 66%] Built target pch_Generate_opencv_test_shape
[ 66%] Built target opencv_test_shape
[ 66%] Built target opencv_perf_videoio_pch_dephelp
[ 66%] Built target pch_Generate_opencv_perf_videoio
[ 66%] Built target opencv_perf_videoio
[ 66%] Built target opencv_test_videoio_pch_dephelp
[ 66%] Built target pch_Generate_opencv_test_videoio
[ 67%] Built target opencv_test_videoio
[ 67%] Built target opencv_test_highgui_pch_dephelp
[ 67%] Built target pch_Generate_opencv_test_highgui
[ 67%] Built target opencv_test_highgui
[ 67%] Built target opencv_superres_pch_dephelp
[ 67%] Built target pch_Generate_opencv_superres
[ 68%] Built target opencv_superres
[ 68%] Built target opencv_perf_superres_pch_dephelp
[ 68%] Built target pch_Generate_opencv_perf_superres
[ 68%] Built target opencv_perf_superres
[ 68%] Built target opencv_test_superres_pch_dephelp
[ 68%] Built target pch_Generate_opencv_test_superres
[ 68%] Built target opencv_test_superres
[ 68%] Built target opencv_features2d_pch_dephelp
[ 69%] Built target pch_Generate_opencv_features2d
[ 71%] Built target opencv_features2d
[ 71%] Built target opencv_perf_features2d_pch_dephelp
[ 71%] Built target pch_Generate_opencv_perf_features2d
[ 71%] Built target opencv_perf_features2d
[ 71%] Built target opencv_test_features2d_pch_dephelp
[ 72%] Built target pch_Generate_opencv_test_features2d
[ 74%] Built target opencv_test_features2d
[ 74%] Built target opencv_calib3d_pch_dephelp
[ 74%] Built target pch_Generate_opencv_calib3d
[ 76%] Built target opencv_calib3d
[ 76%] Built target opencv_perf_calib3d_pch_dephelp
[ 76%] Built target pch_Generate_opencv_perf_calib3d
[ 76%] Built target opencv_perf_calib3d
[ 76%] Built target opencv_test_calib3d_pch_dephelp
[ 76%] Built target pch_Generate_opencv_test_calib3d
[ 78%] Built target opencv_test_calib3d
[ 78%] Generating opencv-330.jar
Target 'jar' failed with message 'Unable to find a javac compiler;
com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre"'.

BUILD FAILED
/root/workspace/opencv/build/build.xml:10: Unable to find a javac compiler;
com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre"

Total time: 7 seconds
make[2]: *** [bin/opencv-330.jar] Error 1
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
make: *** [all] Error 2

how to fix it?

**Comment by andrewexo** [comment]
I'm stuck on this same issue. Setting JAVA_HOME does nothing because it's not checking JAVA_HOME. It's using some other value and lying about what is stored in JAVA_HOME. How do I get it to use the correct location?

**Comment by chengyh23** [comment]
`/usr/lib/jvm$ ls -l
总用量 4
lrwxrwxrwx 1 root root   24 2月  26  2016 default-java -> java-1.8.0-openjdk-amd64
lrwxrwxrwx 1 root root   20 4月  16 06:27 java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64
drwxr-xr-x 5 root root 4096 6月  27 17:45 java-8-openjdk-amd64
`

ln -s jdk1.8.0_251/ default-java

**Comment by vijay180396** [comment]
why do you set JAVA_home =>
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre

and i have set JAVA_HOME in bashrc file=> /usr/lib/jvm/default-java".
and PATH=>"$JAVA_HOME/bin:$PATH"
and don't forget the JNI_HOME
