### ISSUE TITLE
Suggestion : Update wiki of deep learning

### ISSUE THREAD

**Issue by stereomatchingkiss** [opencv/opencv#9645]
According to #9501, opencv3.3 do not support PyTorch(http://pytorch.org/) but PyTorch(https://github.com/hughperkins/pytorch). I suggest wiki should specify it before opencv begin to support both of them to avoid ambiguity.

ps : Any chance to support PyTorch(http://pytorch.org/)? Thanks

**Comment by catree** [comment]
@stereomatchingkiss 
I think you meant pytorch ([https://github.com/hughperkins/pytorch](https://github.com/hughperkins/pytorch)) and not PyTorch ([https://github.com/pytorch/pytorch](https://github.com/pytorch/pytorch))?

**Comment by stereomatchingkiss** [comment]
@catree From #9501, I guess opencv3.3 do not support PyTorch (https://github.com/pytorch/pytorch) but pytorch (https://github.com/hughperkins/pytorch), it is quite confuse which pytorch opencv want to support, that is why I suggest the wiki should mention it.

**Comment by stereomatchingkiss** [comment]
Do opencv plan to PyTorch(https://github.com/pytorch/pytorch)? PyTorch(https://github.com/pytorch/pytorch) is under active development, but pytorch (https://github.com/hughperkins/pytorch) is almost dead(0 commit after 10 months).

**Comment by dkurt** [comment]
@stereomatchingkiss, as for me, the best drivers to start a research are interesting models trained in PyTorch. I think we don't need a one more AlexNet represented in different format. It'll be great if you can find or train some efficient network that outperforms known models from other frameworks. In example, any-class detection / tracking models, text detectors, background subtraction, style transfer.

**Comment by stereomatchingkiss** [comment]
@dkurt Is [this project](https://github.com/fyu/drn) good enough?

**Comment by GuanRainy** [comment]
@dkurt Do opencv plan to PyTorch(https://github.com/pytorch/pytorch)?

**Comment by dkurt** [comment]
@GuanRainy, yes, we are planning to add support of PyTorch models in ONNX format. See issue https://github.com/opencv/opencv/issues/11008.

**Comment by lpuglia** [comment]
can someone please adjust the wiki:
https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV

i just spent a day converting my project to work with the latest opencv version in order to use the dnn feature and now i just discovered that:

Torch/PyTorch

is not what everybody in deep learning community means...

**Comment by dkurt** [comment]
@lpuglia, fixed that, thanks!

**Comment by dkurt** [comment]
I'm closing that issue. We've added an ONNX parser (see https://github.com/opencv/opencv/pull/12071) and updated a wiki page.
