### ISSUE TITLE
Failed to load caffe model in opencv 3.3

### ISSUE THREAD

**Issue by JackGan999** [opencv/opencv#9651]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Linux
- Compiler => gcc5.0

##### Detailed description
caffe/build/examples/cpp_classification/classification.bin  lenet_train_test_deploy.prototxt  lenet_iter_10000.caffemodel  mnist_mean labels.txt 
---------- Prediction for test.jpg ----------
1.0000 - "0"
0.0000 - "1"
0.0000 - "3"
0.0000 - "4"
0.0000 - "2"

But failed to run in OpenCV3.3:
python deep_learning_with_opencv.py -i test.jpg -p lenet_train_test_deploy.prototxt -m lenet_iter_10000.caffemodel -l labels.txt
[INFO] loading model...
OpenCV Error: Unspecified error (Can't create layer "data" of type "Input") in getLayerInstance, file /home2/opensource/opencv/modules/dnn/src/dnn.cpp, line 249
Traceback (most recent call last):
  File "deep_learning_with_opencv.py", line 44, in <module>
    preds = net.forward()
cv2.error: /home2/opensource/opencv/modules/dnn/src/dnn.cpp:249: error: (-2) Can't create layer "data" of type "Input" in function getLayerInstance.

And caffe_test.tar.gz contains all the data for the opencv caffe test.
caffe_test
├── deep_learning_with_opencv.py
├── labels.txt
├── lenet_iter_10000.caffemodel
├── lenet_train_test_deploy.prototxt
├── mnist_mean
├── test.jpg
└── test.sh

[caffe_test.tar.gz](https://github.com/opencv/opencv/files/1310475/caffe_test.tar.gz)

**Comment by dkurt** [comment]
@JackGan999, just replace the header of prototxt to
```
input: "data"
input_dim: 1
input_dim: 1
input_dim: 28
input_dim: 28
```
and load input image at `deep_learning_with_opencv.py` in grayscale.
```
[INFO] loading model...
[INFO] classification took 0.008569 seconds
[INFO] 1. label: 0, probability: 1.0
[INFO] 2. label: 9, probability: 0.0
[INFO] 3. label: 8, probability: 0.0
[INFO] 4. label: 7, probability: 0.0
[INFO] 5. label: 6, probability: 0.0
```

**Comment by JackGan999** [comment]
dkurt, Thank you a lot!
I did as your help, but I got the following error,could you help me out?

[INFO] loading model...
OpenCV Error: Assertion failed (ngroups > 0 && inpCn % ngroups == 0 && outCn % ngroups == 0) in getMemoryShapes, file /home2/opensource/opencv/modules/dnn/src/layers/convolution_layer.cpp, line 190
Traceback (most recent call last):
  File "deep_learning_with_opencv.py", line 44, in <module>
    preds = net.forward()
cv2.error: /home2/opensource/opencv/modules/dnn/src/layers/convolution_layer.cpp:190: error: (-215) ngroups > 0 && inpCn % ngroups == 0 &&outCn % ngroups == 0 in function getMemoryShapes

**Comment by berak** [comment]
@JackGan999 you forgot to read the image as grayscale.

    image = cv2.imread(args["image"], cv2.IMREAD_GRAYSCALE)

**Comment by JackGan999** [comment]
Thanks, I did forgot. It works now.

**Comment by YingHou** [comment]
Hi @berak ,

I have seen the same issue. However, I'm not sure where I should insert/replace below in prototxt file :
input: "data"
input_dim: 1
input_dim: 1
input_dim: 28
input_dim: 28

Could you please help?

**Comment by berak** [comment]
@YingHou , you insert that at the start of the file, replacing the input layer, like this:

```
name: "LeNet"
input: "data"
input_dim: 1
input_dim: 1
input_dim: 28
input_dim: 28

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  ...
```

**Comment by YingHou** [comment]
thank you @berak, it works. 
I tried to use GoogLeNet model, but it gives me error: Floating point exception (core dumped). Do you have any suggestions?

**Comment by dkurt** [comment]
@YingHou, please, provide a minimal working example (just how you load the network/image, check that net/image was read successfully, how to set input blob and receive the output one). This sample may help: https://github.com/opencv/opencv/blob/master/samples/dnn/caffe_googlenet.cpp.

**Comment by YingHou** [comment]
I have fixed this issue.  Thanks all for your help!

**Comment by prabhundps** [comment]
I'm facing the same error "Can't create layer "data" of type "Input" in function getLayerInstance in dnn.cpp" whereas I'm using googlenet.

deploy.prototxt-
name: "GoogleNet"
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 32 dim: 3 dim: 224 dim: 224 } }
}
layer {
  name: "conv1/7x7_s2"
  type: "Convolution"
  bottom: "data"

detecttion.py-

import cv2
net = cv2.dnn.readNetFromCaffe(
'google_net_sample.prototxt',
'bvlc_googlenet.caffemodel')
frame = cv2.imread('frame.jpg', cv2.IMREAD_GRAYSCALE)
image=cv2.resize(frame, (224, 224))
blob = cv2.dnn.blobFromImage(image,1, (224, 224), (104, 117, 123), swapRB=True)
net.setInput(blob)
detections = net.forward()
print(detections)

Error-
OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "google_net_sample.prototxt") in ReadProtoFromTextFile, file /io/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1113
Traceback (most recent call last):
  File "image_detection.py", line 4, in <module>
    'bvlc_googlenet.caffemodel')
cv2.error: /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1113: error: (-2) FAILED: fs.is_open(). Can't open "google_net_sample.prototxt" in function ReadProtoFromTextFile

Please help me out with this, If anyone needs more information, I would be happy to share.

**Comment by alalek** [comment]
> Can't open "google_net_sample.prototxt" in function ReadProtoFromTextFile

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by holger-prause** [comment]
Thank you prabhuiitdhn - blobFromImage() call was missing for me - i passed in the wrong mat. No grascale or config file changes were needed for me

**Comment by trungphan9x** [comment]
@berak  @YingUK Could you help me to check this error?
Thanks a lot

"C:\Users\Trung Phan\PycharmProjects\TestCaffeModel\venv\Scripts\python.exe" "C:/Users/Trung Phan/PycharmProjects/TestCaffeModel/deep_learning_object_detection.py"
[INFO] loading model...
[INFO] computing object detections...
OpenCV(3.4.1) Error: Assertion failed (layers[0].outputBlobs[i].total()) in cv::dnn::experimental_dnn_v4::Net::Impl::allocateLayers, file C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp, line 1683
Traceback (most recent call last):
  File "C:/Users/Trung Phan/PycharmProjects/TestCaffeModel/deep_learning_object_detection.py", line 53, in <module>
    detections = net.forward()
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:1683: error: (-215) layers[0].outputBlobs[i].total() in function cv::dnn::experimental_dnn_v4::Net::Impl::allocateLayers


Process finished with exit code 1

**Comment by priyakansal** [comment]
I am getting the following error:

OpenCV(3.4.1) Error: Assertion failed (layers[0].outputBlobs[i].total()) in allocateLayers, file /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/dnn.cpp, line 1683
Traceback (most recent call last):
  File "real_time_object_detection.py", line 62, in <module>
    detections = net.forward()
cv2.error: OpenCV(3.4.1) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/dnn.cpp:1683: error: (-215) layers[0].outputBlobs[i].total() in function allocateLayers

I have tried changing the input shape in deploy.prototxt file. But it didn't work.

Please help me out.

**Comment by priyakansal** [comment]
@trungphan9x @dkurt  @JackGan999 

I am facing the exact same problem as @trungphan9x 

OpenCV(3.4.1) Error: Assertion failed (layers[0].outputBlobs[i].total()) in allocateLayers, file /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/dnn.cpp, line 1683
Traceback (most recent call last):
  File "real_time_object_detection.py", line 62, in <module>
    detections = net.forward()
cv2.error: OpenCV(3.4.1) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/dnn.cpp:1683: error: (-215) layers[0].outputBlobs[i].total() in function allocateLayers

I have tried changing the input shape in deploy.prototxt file as suggested by @JackGan999 . But it didn't work.

Please help me out.

**Comment by dkurt** [comment]
@alexlopezcifuentes, please use a forum http://answers.opencv.org providing all the information which is necessary to reproduce your problem.
