### ISSUE TITLE
findFundamentalMat returns None object in python. 

### ISSUE THREAD

**Issue by alejandronespereira** [opencv/opencv#9665]
I am running opencv 3.2.0 on python 2.7.12, on a 16.04.1 Ubuntu 64 bits.

For some reason findFundamentalMat always returns a None object:
```
>>> import cv2
>>> import numpy as np
>>> p1 = np.int32([cv2.KeyPoint(i,i,1).pt for i in range(10)])
>>> p2 = np.int32([cv2.KeyPoint(i,i + 10,1).pt for i in range(10)])
>>> F,mask = cv2.findFundamentalMat(p1,p2,cv2.FM_RANSAC)
>>> F
>>> F == None
True
>>> 
```

**Comment by sovrasov** [comment]
None object means that `cv2.findFundamentalMat` has failed to find fundamental matrix in your case.

**Comment by alejandronespereira** [comment]
Thought so, but a friend of mine ran the very same code and got a zero matrix as an F. I'll ask her tomorrow as soon as we're both at work, and update.

**Comment by sovrasov** [comment]
Your points are on the one line, so there is no information to reconstruct fundamental matrix. Try to modify both the sets like this:
```python
p1 = np.float32([cv2.KeyPoint(i,i*i,1).pt for i in range(10)])
p2 = np.float32([cv2.KeyPoint(i*i,i + 10,1).pt for i in range(10)])
```

**Comment by chaowu2009** [comment]
I got the same problem. What sovrasov provided is not working either. 

    points1 = np.float32([cv2.KeyPoint(i,i*i,1).pt for i in range(10)])
    points2 = np.float32([cv2.KeyPoint(i*i,i + 10,1).pt for i in range(10)])
    DCM,mask = cv2.findFundamentalMat(point1, point2, cv2.FM_LMEDS)

returns none for DCM.
