### ISSUE TITLE
cv::Rect::operator| changed functionality

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv#9666]
After commit c5b5d5c cv::Rect::operator| will take another functionality:

Code:
```
    cv::Rect r1(2, 5, 2, 2);
    cv::Rect r2(10, 10, 0, 0);
    cv::Rect r12 = r1 | r2;
    std::cout << r12 << std::endl;
```

Old version out:
_[8 x 5 from (2, 5)]_

New version out:
_[2 x 2 from (2, 5)]_

Now I can't use this operator for rectangles with zero area! But mathematically this operation is correct. What's right?

**Comment by alalek** [comment]
Right. Related: #9097
