### ISSUE TITLE
Make -j4 failed while installing opencv for ubuntu 16.04

### ISSUE THREAD

**Issue by GalangZero13** [opencv/opencv#9667]
##### System information (version)

- OpenCV => opencv3
- Operating System / Platform => Ubuntu 16.04
- Compiler => -

##### Detailed description
When I'm installing opencv, and then tried to make -j4

[ 88%] Built target opencv_test_sfm
[ 88%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
/bin/sh: 1: /home/jbd/.virtualenv/OCR/bin/python: not found
modules/python2/CMakeFiles/opencv_python2.dir/build.make:325: recipe for target 'modules/python2/pyopencv_generated_include.h' failed
make[2]: *** [modules/python2/pyopencv_generated_include.h] Error 127
CMakeFiles/Makefile2:21825: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Built target cpp-tutorial-pnp_detection
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Its been 2 weeks since I've been struggling on installing opencv especially in this section and I've sought out for the solution everywhere but none of them are any help, is there any solution?

**Comment by alalek** [comment]
Usage questions / build problems investigation requests should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

> /home/jbd/.virtualenv/OCR/bin/python: not found

Problem is here. Try to build from scratch (clean build directory).
