### ISSUE TITLE
The dnn of detection_output_layer.cpp

### ISSUE THREAD

**Issue by canteen-man** [opencv/opencv#9670]
opencv3.2  dnn/src/layers/detection_output_layer.cpp
When the number of Detections is 0,the program exit.
I think when the number of Detections is 0,the program should return a flag,the program don't exit.Because when I detection the video by using SSD,maybe the Detections is 0 in one frame,but I can detect the next frame,the program should still run,just jump out of this frame.
I change the source program of dnn.The function of forward use hundreds times,I change hundreds times and a lot of cpp program. I advise change this function in the future.

**Comment by dkurt** [comment]
@canteen-man, I'm very sorry but I can't understand the topic of issue. We have several [samples](https://github.com/opencv/opencv/tree/master/samples/dnn) with SDD networks that correctly process cases with no detections. Or you mean a specific sample of them?

**Comment by canteen-man** [comment]
@dkurt  I don't sure.I use SSD to detection the video of car and driver,and I just classify in 2 category.When I detect one frame ,the program exit.And I find the following program in detection_output_layer.cpp.
 if (numKept == 0)
    {
        CV_ErrorNoReturn(Error::StsError, "Couldn't find any detections");
        return;
    }
I think if couldn't find any detections,it should return a flag,and continue to detect the next frame . But now,the program exit error.I change this by return a value.

**Comment by dkurt** [comment]
@canteen-man, thanks! I see you. DetectionOutput layer was modified at https://github.com/opencv/opencv/pull/9188. Please update local version of OpenCV.
