### ISSUE TITLE
OpenCV2.4 latest release for Windows is possibly infected.

### ISSUE THREAD

**Issue by Albert65** [opencv/opencv#9671]
Hi All,
Symantec antivirus quarantined the latest opencv 2.4 for Windows as infected (version 3.3 is fine)

**Comment by alalek** [comment]
We need reproducible report, consider to use https://www.virustotal.com .
It would be good to add source URL with grabbed binary package.

To continue work with OpenCV, you need grab sources and build OpenCV yourself.
