### ISSUE TITLE
OpenCVLoader.initAsync fail in the first few attempts

### ISSUE THREAD

**Issue by xuzhongxing** [opencv/opencv#9672]
OpenCV 3.3.0
Android 7.1.1
Oneplus 5

I installed OpenCV 3.3.0 Manager arm64-v8a by adb to the phone.
The  OpenCVLoader.initAsync() operation always fails for the first few times, and succeeds finally.

A "Package not found" dialog shows. I click "NO". Repeat this several times. And then succeeds.

Load code is:
```
@Override
public void onResume() {
        super.onResume();
        OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_3_0, this, loaderCallback);
}
```

logcat output:
```
09-20 17:49:51.577 17807-17807/cn.deepclue.vins2 I/Vins2Tag: In onCreate()
09-20 17:49:51.583 17807-17807/cn.deepclue.vins2 D/CameraBridge: Attr count: 6
09-20 17:49:51.592 17807-17807/cn.deepclue.vins2 D/OpenCVManager/Helper: Request new service installation
09-20 17:49:51.605 17807-22993/cn.deepclue.vins2 D/AppTracker: App Event: start
09-20 17:49:51.640 17807-17807/cn.deepclue.vins2 D/CameraBridge: call surfaceChanged event
09-20 17:49:51.640 17807-17807/cn.deepclue.vins2 D/CameraBridge: call checkCurrentState
```

Please give me some clue to solve this issue.

**Comment by alalek** [comment]
Please add dump of `adb logcat` messages at least.

Help request with problem investigation should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV. Please return back with clear reason of this problem.

**Comment by xuzhongxing** [comment]
I flashed lineageos and the problem went away.
