### ISSUE TITLE
DataType channel used in _Mat bu deprecated

### ISSUE THREAD

**Issue by MalcolmMielle** [opencv/opencv#9677]
I have this error on compile

```
/usr/local/include/opencv2/core/mat.hpp:2150:50: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
     typedef typename DataType<_Tp>::channel_type channel_type;
```

And I think DataType::channel_type is deprecated ?

**Comment by alalek** [comment]
These type traits is for conversion into `cv::Mat`.

> unsigned int

This type is not supported by `cv::Mat` and can't be handed correctly.
Current list of supported types are here: https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/interface.h#L67-L73

Related #7599

**Comment by MalcolmMielle** [comment]
Ok thanks !
