### ISSUE TITLE
(dnn/tensorflow) Unknown layer type StridedSlice in populateNet

### ISSUE THREAD

**Issue by kbarni** [opencv/opencv#9682]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.10
- Compiler => gcc 6.3

##### Detailed description

I created a DNN network in Keras, very similar to LeNet (Conv->MaxPool->Conv->MaxPool->Conv->MaxPool->Flatten (Reshape)->Dense->Output(2 classes, Softmax)

The last level of the network was defined in the following way:

        model.add(
            Dense(
                units = 2,
                activation="softmax")
        )

When I tried to export it to TensorFlow, Keras introduced at the last step a `StridedSlice` operation (I don't really know why).

As this type of layer is not implemented, OpenCV throws an exception when trying to load the *.pb* file

Can you implement this layer type to OpenCV? 
Or is there a workaround to eliminate this layer type when creating the network?

##### Steps to reproduce

The **.pb** [final_net.zip](https://github.com/opencv/opencv/files/1321685/final_net.zip) file is attached to this report.

Python code to generate the network (very similar to https://github.com/opencv/opencv_contrib/issues/1241 )

    adam = Adam(lr = l_r)
    model = Sequential()

    #Conv2D
    model.add(
        Conv2D(
            filters = nb_filters[0],
            kernel_size = kernel_size[0],
            strides = (1,1),
            padding = "same",
            activation = "relu",
            kernel_initializer="random_normal",
            input_shape = (x_shape, y_shape,3)
            )
        )

    model.add( Dropout(drop[0]) )
    #MaxPooling2D
    model.add( MaxPooling2D( pool_size = (2,2) ) )
    model.add( Dropout(drop[1]) )

    #Conv2D
    model.add(
        Conv2D(
            filters = nb_filters[1],
            kernel_size = kernel_size[1],
            strides = (1,1),
            padding="same",
            activation="relu",
            kernel_initializer="random_normal")
        )
    model.add( Dropout(drop[2]) )

    #MaxPooling2D
    model.add( MaxPooling2D( pool_size = (2,2) ) )
    model.add( Dropout(drop[3]) )

    #Conv2D
    model.add(
        Conv2D(
            filters = nb_filters[2],
            kernel_size = kernel_size[2],
            strides = (1,1),
            padding="same",
            activation = "relu",
            kernel_initializer="random_normal")
        )
    model.add(Dropout(drop[4]) )

    #MaxPooling2D
    model.add( MaxPooling2D( pool_size = (2,2) )  )
    model.add( Dropout(drop[5]) )

    # Changed Flatten to Reshape 
    model.add( Reshape(1024,) )

    #Output 
    model.add(
        Dense(
            units = 2,
            activation="softmax")
        )

    model.compile(
        optimizer = adam,
        loss = "binary_crossentropy",
        metrics = ["accuracy"])

Code to save the network:

    sess = K.get_session()
    K.set_learning_phase(0)
    net_model = load_model(weight_file_path)
    pred = [None]*num_output
    pred_node_names = [None]*num_output
    for i in range(num_output):
        pred_node_names[i] = prefix_output_node_names_of_final_network+str(i)
        pred[i] = tf.identity(net_model.output[i], name=pred_node_names[i])
    print('output nodes names are: ', pred_node_names)

    constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), pred_node_names)
    graph_io.write_graph(constant_graph, output_fld, output_graph_name, as_text=False)
    print('saved the constant graph (ready for inference) at:',osp.join(output_fld, output_graph_name))

**Comment by dkurt** [comment]
@kbarni, it looks like a duplicate issue to https://github.com/opencv/opencv_contrib/issues/1241.

**Comment by kbarni** [comment]
No, it's not the same. In issue 1241 the `StridedSlice` was introduced by the `Flatten` Keras function and was solved by replacing `Flatten` by `Resize`.

Here, I'm getting StridedSlice between the last `Dense` layer and the output and I didn't find any workaround for the moment. 

I did another experiment by implementing a classical ANN in Keras (without any convolutions): input->Dense1->Dense2->Output. I still get a `StridedSlice` after the *Dense2* layer, so it can't be read by OpenCV.

Here you have the generated networks: 

[m_simple.pb.zip](https://github.com/opencv/opencv/files/1323877/m_simple.pb.zip)

[simple_graph_def.pb.txt](https://github.com/opencv/opencv/files/1323882/simple_graph_def.pb.txt)

Couldn't we implement the StridedSlice layer type in OpenCV?

**Comment by kbarni** [comment]
OK, I've found a workaround: This is just a stupid identity operation introduced by Keras (I checked the parameters and it copies the tensor from the first to the last element with a step of 1).
So, as a **temporary** workaround I modified the

    else if (type == "Const")

line in `tf_importer.cpp` to:

    else if ((type == "Const")||(type=="StridedSlice"))

**but this emulates only the identity operation, it isn't a proper implementation of the StridedSlice layer!!!**

I still think that the **StridedSlice** layer type should be implemented in OpenCV.

**Comment by dkurt** [comment]
@kbarni, Let's complicate the model step by step. The following model imports properly for me:
```python
import tensorflow as tf
import tensorflow.contrib.keras as K

model = K.models.Sequential()

model.add(
    K.layers.Conv2D(
        filters=5,
        kernel_size=(3, 3),
        strides=(1, 1),
        padding='SAME',
        input_shape=(6, 7, 3)
        )
    )
model.add( K.layers.Reshape((6*7*5,)) )
model.add(
    K.layers.Dense(
        units=20,
        activation=K.activations.softmax)
    )
model.add(
    K.layers.Dense(
        units=10,
        activation=K.activations.softmax)
    )

sess = K.backend.get_session()
constant_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), ['dense_2/Softmax'])
tf.train.write_graph(constant_graph, "", "graph.pb", as_text=False)
```
Optionally, remove unnecessary nodes by:
```bash
python ~/tensorflow/tensorflow/python/tools/optimize_for_inference.py \
  --input graph.pb \
  --output graph.pb \
  --frozen_graph True \
  --input_names conv2d_1_input \
  --output_names dense_2/Softmax
```

**Comment by kbarni** [comment]
The `optimize_for_inference.py` script effectively eliminated the unnecessary `StridedSlice` layer. 

Now the Keras-generated network runs without problems on OpenCV.

Thank you for your help! Closing the issue.

**Comment by dkurt** [comment]
@kbarni, You're welcome!

**Comment by rodrigo2019** [comment]
@dkurt, your solution worked with me using keras version 2.0.8, after upgrade my keras to version 2.0.9, is not working anymore, in this version keras uses operations "StridedSlice" and "Slice" which dnn module do not has support yet.
So changing the layer flatten to Reshape has no more effect.

Using keras 2.0.9
![image](https://user-images.githubusercontent.com/8016520/32558042-02b58e76-c48b-11e7-9093-63fa3e3b72ed.png)

Using Keras 2.0.8
![image](https://user-images.githubusercontent.com/8016520/32558099-2729fd50-c48b-11e7-88ff-a14835aefa0b.png)

thank you for sharing a solution!

**Comment by kbarni** [comment]
I confirm @rodrigo2019 's observation: Reshape doesn't work anymore in Keras (I'm using 2.1.6); it's converted in *Shape/StridedSlice* operations that aren't recognized by OpenCV anymore.

To be more specific: I converted the same network with keras 2.0.8 and 2.1.6 to tensorflow. The first one is read by OpenCV (3.4.1), the second one gives an error (`(-2) Unknown layer type Shape in op reshape_1/Shape in function populateNet`)

I'm trying to use some workaround by transforming the shape operation into a constant and the stridedslice into an identity, but the results aren't good atm.

Can you add these two operations to the DNN module, so the networks can be used directly?

**Comment by dkurt** [comment]
@kbarni, please provide a minimal working example if you have one.

**Comment by kbarni** [comment]
Here it is. It takes 64x64 pixel normalized RGB images if you want to test it.

The original Keras network and weights are in the pommes6.h5 file.

The pommes6_tf.pb was created by Keras 2.0.8 (with optimize_for_inference) and is correctly read by OpenCV.

The pommes6_tf.pb-new was created by Keras 2.1.6 using the same procedure from the same source file. OpenCV complains about a Shape layer and a StridedSlice layer:

    OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Shape in op reshape_1_2/Shape) in populateNet

[net.zip](https://github.com/opencv/opencv/files/2055075/net.zip)

**Comment by rodrigo2019** [comment]
@kbarni  I'am using keras 2.1.6, and to create inference modelts to use in dnn module I copied the Reshape class from keras 2.0.8 and use it, instead of Reshape from keras 2.1.6

```python
class Reshape_keras_208(Layer):
    """Reshapes an output to a certain shape.

    # Arguments
        target_shape: target shape. Tuple of integers.
            Does not include the batch axis.

    # Input shape
        Arbitrary, although all dimensions in the input shaped must be fixed.
        Use the keyword argument `input_shape`
        (tuple of integers, does not include the batch axis)
        when using this layer as the first layer in a model.

    # Output shape
        `(batch_size,) + target_shape`

    # Example

    ```python
        # as first layer in a Sequential model
        model = Sequential()
        model.add(Reshape((3, 4), input_shape=(12,)))
        # now: model.output_shape == (None, 3, 4)
        # note: `None` is the batch dimension

        # as intermediate layer in a Sequential model
        model.add(Reshape((6, 2)))
        # now: model.output_shape == (None, 6, 2)

        # also supports shape inference using `-1` as dimension
        model.add(Reshape((-1, 2, 2)))
        # now: model.output_shape == (None, 3, 2, 2)
    ```
    """

    def __init__(self, target_shape, **kwargs):
        super(Reshape_keras_208, self).__init__(**kwargs)
        self.target_shape = tuple(target_shape)

    def _fix_unknown_dimension(self, input_shape, output_shape):
        """Finds and replaces a missing dimension in an output shape.

        This is a near direct port of the internal Numpy function
        `_fix_unknown_dimension` in `numpy/core/src/multiarray/shape.c`

        # Arguments
            input_shape: original shape of array being reshaped
            output_shape: target shape of the array, with at most
                a single -1 which indicates a dimension that should be
                derived from the input shape.

        # Returns
            The new output shape with a `-1` replaced with its computed value.

        # Raises
            ValueError: if `input_shape` and `output_shape` do not match.
        """
        output_shape = list(output_shape)
        msg = 'total size of new array must be unchanged'

        known, unknown = 1, None
        for index, dim in enumerate(output_shape):
            if dim < 0:
                if unknown is None:
                    unknown = index
                else:
                    raise ValueError('Can only specify one unknown dimension.')
            else:
                known *= dim

        original = np.prod(input_shape, dtype=int)
        if unknown is not None:
            if known == 0 or original % known != 0:
                raise ValueError(msg)
            output_shape[unknown] = original // known
        elif original != known:
            raise ValueError(msg)

        return tuple(output_shape)

    def compute_output_shape(self, input_shape):
        return (input_shape[0],) + self._fix_unknown_dimension(
            input_shape[1:], self.target_shape)

    def call(self, inputs):
        # In case the target shape is not fully defined,
        # we need access to the shape of `inputs`.
        # solution: rely on `K.int_shape`.
        target_shape = self.target_shape
        if -1 in target_shape:
            # Target shape not fully defined.
            input_shape = None
            try:
                input_shape = K.int_shape(inputs)
            except TypeError:
                pass
            if input_shape is not None:
                target_shape = self.compute_output_shape(input_shape)[1:]
        return K.reshape(inputs, (-1,) + target_shape)

    def get_config(self):
        config = {'target_shape': self.target_shape}
        base_config = super(Reshape_keras_208, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

def addFlatten(model):
    output_shape=model.layers[-1].output_shape
    flatVectorSize=1
    for i in range(1,len(output_shape),1):
        i=output_shape[i]
        flatVectorSize*=i
    model.add(Reshape_keras_208((flatVectorSize,)))
    
    return model
```

**Comment by dkurt** [comment]
@kbarni, Looking on the graph I've found that it has extra nodes after the last softmax layer.

```python
import tensorflow as tf

graph = 'net/pommes6_tf.pb-new'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    for node in graph_def.node[-7:]:
        print node.op, node.name
```
```
BiasAdd dense_1_2/BiasAdd
Softmax dense_1_2/Softmax
Const strided_slice/stack
Const strided_slice/stack_1
Const strided_slice/stack_2
StridedSlice strided_slice
Identity output_node0
```
You need to truncate it and reserialize:
```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph
import cv2 as cv
import numpy as np

np.random.seed(324)

graph = 'net/pommes6_tf.pb-new'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    graph_def = TransformGraph(graph_def, ['conv2d_1_input_2'], ['dense_1_2/Softmax'], ['strip_unused_nodes'])
    with tf.gfile.FastGFile('graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())

# Compare outputs from TensorFlow and OpenCV
inp = np.random.uniform(0.0, 1.0, [1, 64, 64, 3]).astype(np.float32)

# Run TensorFlow graph
with tf.Session() as sess:
    tf.import_graph_def(graph_def, name='')
    tfOut = sess.run(sess.graph.get_tensor_by_name('dense_1_2/BiasAdd:0'),
                     feed_dict={'conv2d_1_input_2:0': inp})
    print 'TensorFlow: ', tfOut

# Run OpenCV
net = cv.dnn.readNetFromTensorflow('graph.pb')
net.setInput(inp.transpose(0, 3, 1, 2))
cvOut = net.forward('dense_1_2/MatMul')
print 'OpenCV: ', cvOut
``` 

The script above prints outputs from the layer before softmax due not representative results of a whole network on random data. It's `dense_1_2/BiasAdd` for TensorFlow but `dense_1_2/MatMul` for OpenCV because OpenCV fuses matmul+bias.

```
TensorFlow:  [[ 144.62085 -130.55684]]
OpenCV:  [[ 144.62086 -130.55687]]
```

If you experimented with an updated Keras please compare it with the latest version of OpenCV ([branch 3.4](https://github.com/opencv/opencv/tree/3.4) or [master branch](https://github.com/opencv/opencv/tree/master)).

**Comment by dkurt** [comment]
@kbarni, @rodrigo2019, please close an issue if it has been solved.
