### ISSUE TITLE
Should I add a warning to findChessboardCorners for square boards?

### ISSUE THREAD

**Issue by credentiality** [opencv/opencv#9689]
Looks like findChessboardCorners silently fails if the chessboard size is square.  Shall I write a pull request adding an assert and a printf to complain (plus tests and mentioning that in the docs)?

eg., here's someone else who was bit by this:
https://stackoverflow.com/questions/17665912/findchessboardcorners-fails-for-calibration-image

**Comment by sovrasov** [comment]
`findChessboardCorners` can detect square borders, but results can be unstable. Make sure you are using proper chessboard size.
![window_screenshot_25 09 2017](https://user-images.githubusercontent.com/5373517/30812640-fa081602-a213-11e7-9970-508040d5491b.png)

You can make a note to the documentation about that, but throwing an error in this case looks like overkill.

**Comment by credentiality** [comment]
Tried some more images, looks like you're right and my issue was no white border around my square chessboard, which is already mentioned in the docs.
