### ISSUE TITLE
Can´t read some videos

### ISSUE THREAD

**Issue by jmpinillag** [opencv/opencv#9697]
##### System information (version)

- OpenCV => 3.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Liclipse

##### Description
Hi guys i'm working in a college project so i need to open a videos that has been recorded by a security camera, but using VideoCapture my program just open a file that i recorded with VideoWriter nothing else
Do anyone may know why this happend ?
thanks you

**Comment by ausk** [comment]
You give so little key information, so it's hard to judge where is wrong...

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
Include this information at least:
- `cv::getBuildInformation()`
- small video sample

> 3.0.0
This version is outdated (3+ years)

> Windows

Try to put opencv_ffmpeg.dll near opencv_viodeio.dll / opencv_world.dll (OpenCV 3.2+) or under path from PATH environment.

This tracker is for issues and bugs that needs fix in OpenCV. Feel free to return back if you have a clear reason of problem or want to propose fix via pull request.
