### ISSUE TITLE
-D BUILD_opencv_tesseract=NO does not work

### ISSUE THREAD

**Issue by wosiu** [opencv/opencv#9702]
OpenCV 3.3.0
OS: Ubuntu 16.04.3
tesseract: master

##### Detailed description

cmake flag:
-D BUILD_opencv_tesseract=NO
does not skip teseract bulding. And because currently there is a problem with tesseract I can't compile opencv:

In file included from /usr/local/include/tesseract/ltrresultiterator.h:26:0,
                 from /usr/local/include/tesseract/resultiterator.h:26,
                 from /usr/local/include/tesseract/baseapi.h:31,
                 from /home/m/OCR/download/opencv_contrib/modules/text/src/precomp.hpp:51,
                 from /home/m/OCR/build/opencv/modules/text/opencv_text_pch_dephelp.cxx:1:
/usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);

##### Steps to reproduce

My cmake command:

 cmake -D CMAKE_BUILD_TYPE=RELEASE \
                -D BUILD_opencv_tesseract=NO \
                -D WITH_CUDA=$CUDA \
                -D ENABLE_FAST_MATH=1 \
                -D CUDA_FAST_MATH=1 \
                -D WITH_CUBLAS=1 \
                -D CMAKE_CXX_FLAGS=-std=c++11 \
                -D BUILD_DOCS=NO \
                -D BUILD_EXAMPLES=NO \
                -D BUILD_TESTS=NO \
                -D BUILD_PERF_TESTS=NO \
                -DWITH_FFMPEG=0 \
                -D CMAKE_INSTALL_PREFIX=$OPENCV_INSTALL_DIR \##### Detailed description
                -D OPENCV_EXTRA_MODULES_PATH=$OPENCV_CONTRIB_REPO_DIR/modules \
                -D BUILD_opencv_python2=NO \
                -D BUILD_opencv_python3=NO \
                $OPENCV_REPO_DIR

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

- there is no OpenCV's "tesseract" module, so there is no such variable.
- "text" module uses tesseract, so you should disable this instead: `-DBUILD_opencv_text=OFF`
- issue is related to opecv_contrib, not opencv repository itself
- it is developer responsibility about using of custom builds from `/usr/local`
