### ISSUE TITLE
How to use xml calibration output file

### ISSUE THREAD

**Issue by andreosky** [opencv/opencv#9711]
Hello,
i'm working for the first time to a real time eye tracking project, using opencv.
The project is almost finished but my university professor ask me also to calibrate my camera.
I've done also, this, but in part: I found a lot of code and useful guides, which guided me to create the main xml output file for calibration containing the necessary parameters to improve my software.
But I still don't understand how to use it, where and how to insert these values.
Please help me and thanks a lot anticipately.
Best regards.

**Comment by saskatchewancatch** [comment]
Greetings @andreosky, generally usage questions like this should be asked on the [OpenCV Answers forum.](http://answers.opencv.org/questions/)
