### ISSUE TITLE
Different predictions Using DNN module over loading in Tensorflow from protobuf file

### ISSUE THREAD

**Issue by stellasoft-will** [opencv/opencv#9715]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => gcc

##### Detailed description

At this current time I have frozen a model from Tensorflow to create a "frozen.pb" file, when i reload this using Tensorflow tf.import_graph_def() it predicts perfectly, however this model predicts completely wrong when loading into opencv dnn using cv2.dnn.readNetFromTensorflow() function.
I know the model predicts correctly just wondering if there any issues with the tensorflow read function or am i configuring things wrong. Please see code snippet.

##### Steps to reproduce

```
test_data = np.load('../test_data.npy')

X = np.array([i[0] for i in test_data]).reshape(-1, 125, 50, 3)
Y = [i[1] for i in test_data]

mean = np.mean(X[2398], axis=( -2, -3))

blob = cv2.dnn.blobFromImage(X[2398], 1, (125, 50), mean)

net.setInput(blob, name="input/X")

start = time.time()

preds = net.forward(outputName="output_layer/Softmax")

end = time.time()

print("[INFO] classification took {:.5} seconds".format(end - start))

```
Any help would be greatly appreciated thanks.

**Comment by dkurt** [comment]
@stellasoft-will, if you know the model topology, you may try to find a first layer that produces incorrect output.
Basing on sample you swap 0th and 2nd channels of image (swapRB is true by default).

**Comment by stellasoft-will** [comment]
Thanks, I have added swapRB as false and made mean subtraction be the mean of all train data. Still seeing issues as is still way off. As for model topology I built the model yes, but have no real experience with opencv dnn python module. Any tips for how to test the incorrect output?

**Comment by dkurt** [comment]
@stellasoft-will, Can you share a graph definition or a serialized graph to reproduce an issue or we can close it?
