### ISSUE TITLE
Typo in feature matching python documentation

### ISSUE THREAD

**Issue by OllieLollie1** [opencv/opencv#9721]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Linux 64 Bit
- Compiler => GCC

##### Detailed description

There is a error in the documentations grammar. In the documentation is has "more faster" in the FLANN based match detector correct grammar would be more fast or faster.

##### Steps to reproduce

 Go to http://docs.opencv.org/trunk/dc/dc3/tutorial_py_matcher.html in the sentence "It works more faster than BFMatcher for large datasets."

**Comment by ashayshirwadkar** [comment]
I would like to resolve this.
