### ISSUE TITLE
Assignment to ROI

### ISSUE THREAD

**Issue by FiV0** [opencv/opencv#9722]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Linux 64 bit
- Compiler => g++

##### Detailed description

According to your documentation [here](http://docs.opencv.org/3.2.0/d3/d63/classcv_1_1Mat.html#a92a3e9e5911a2eb0cf0950a0a9670c76) if I use the constructor `Mat mat2(mat1, Range(a,b), Range(a,b))` any change to `mat2` will also be reflected in `mat1`. This doesn't seem to be the case. The code below reproduces the issue.

##### Steps to reproduce

    #include "opencv2/core.hpp"
    #include "opencv2/opencv.hpp"
    #include <iostream>

    using namespace cv;
    using namespace std;

    int main(){
        cout << "Built with OpenCV " << CV_VERSION << endl;
        Mat img(500, 500, CV_8UC4, Scalar(0, 0, 255, 0));
        Mat img2(1000, 1000, CV_8UC4, Scalar(0, 255, 0, 0));

        imwrite("./test1.jpg", img);
        imwrite("./test2.jpg", img2);

        Mat img3(img2, Range(250,750), Range(250, 750));
        img3 = img;
        imwrite("./test3.jpg", img2);
    
        return 0;
    }

**Comment by alalek** [comment]
`cv::Mat` is like a smart-pointer, so assignment operation just replaces a pointer to data.

This should work:
```.diff
-img3 = img;
+img.copyTo(img3);
```

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
