### ISSUE TITLE
make error: opencv3 Ubuntu16.04 libopencv_core.so.3.3.0：undefined reference to ‘GOMP_parallel@GOMP_4.0’

### ISSUE THREAD

**Issue by a1anpro** [opencv/opencv#9733]
##### System information (version)

- OpenCV => :grey_question:Opencv3.2.0 and opencv_contrib
- Operating System / Platform => :grey_question:Ubuntu16.04
- Compiler => :grey_question:gcc/g++ 5.4.0

##### Detailed description

I install anaconda and i built a environment called "myenv", and i conda install opencv using conda.

I compile and install opencv with opencv_contrib successfully.And when i want to test an example using c++, i failed:

```
//example.cpp
#include "opencv2/opencv.hpp"
#include <iostream>
using namespace cv;
using namespace std;

int main(){
    Mat image;
    cout << CV_VERSION<<endl;
    image = imread("0.jpg");
    imshow("test",image);
    waitKey(-1);
    return 0;
}

```
```
CMakeLists.txt:

cmake_minimum_required(VERSION 2.8)
project(example)
find_package(OpenCV REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example ${OpenCV_LIBS})

```
I use cmake successfully, and when use 'make', it makes error:

> yanhui@yanhui:~/test$ make
> Scanning dependencies of target example
> [ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
> [100%] Linking CXX executable example
> /usr/local/lib/libopencv_core.so.3.3.0：undefined reference to ‘GOMP_parallel@GOMP_4.0’
> collect2: error: ld returned 1 exit status
> CMakeFiles/example.dir/build.make:138: recipe for target 'example' failed
> make[2]: *** [example] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example.dir/all' failed
> make[1]: *** [CMakeFiles/example.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

I have compiled and installed opencv once, but i didn't get Python module, i run the same code successfully,but failed this time. could anyone tell me why?

**Comment by berak** [comment]
@a1anpro  , since this is the opencv *library* issue tracker, and you're not reporting a bug, would you be so kind, to close this, and ask again on http://answers.opencv.org ?

we'll try to help you from there.
