### ISSUE TITLE
cv::cudacodec::VideoReader unable to Play rtsp stream 

### ISSUE THREAD

**Issue by pawan9** [opencv/opencv#9739]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Ubuntu 16.04, x86_64 
- Compiler => gcc version 5.4.1 20160904
- Cuda => 8.0
- Nvidia card => GTX 1080 Ti 

##### Detailed description

i am trying to play a rtsp stream using `cudacodec::VideoReader` 
###### Rtsp Stream Details ( from vlc )
![stream_details](https://user-images.githubusercontent.com/3811164/30963935-040eadcc-a46d-11e7-82b0-4970bc48756b.png)
this stream plays fine in vlc and `cv::VideoCapture` but when i try to play it in `cudacodec::VideoReader`  i get a **error** saying:

`OpenCV Error: Gpu API call (CUDA_ERROR_FILE_NOT_FOUND [Code = 301]) in CuvidVideoSource, file /home/sumit/Downloads/softwares/opencv/modules/cudacodec/src/cuvid_video_source.cpp, line 66
`
`Invalid UE golomb code`
`Invalid UE golomb code`
`OpenCV Error: Unsupported format or combination of formats (Unsupported video source) in FFmpegVideoSource, file /home/sumit/Downloads/softwares/opencv/modules/cudacodec/src/ffmpeg_video_source.cpp, line 110
terminate called after throwing an instance of 'cv::Exception'`
`  what():  /home/sumit/Downloads/softwares/opencv/modules/cudacodec/src/ffmpeg_video_source.cpp:110: error: (-210) Unsupported video source in function FFmpegVideoSource`

##### Steps to reproduce

```#include <iostream>
#include "opencv2/opencv_modules.hpp"

#if defined(HAVE_OPENCV_CUDACODEC)

#include <opencv2/core.hpp>
#include <opencv2/cudacodec.hpp>
#include <opencv2/highgui.hpp>

int main(int argc, const char* argv[])
{
    const std::string fname = "rtsp://admin:admin@192.168.1.13/media/video2";

    cv::namedWindow("GPU", cv::WINDOW_NORMAL);

    cv::cuda::GpuMat d_frame;
    cv::Ptr<cv::cudacodec::VideoReader> d_reader = cv::cudacodec::createVideoReader(fname);

    for (;;)
    {

        if (!d_reader->nextFrame(d_frame))
            break;

        cv::Mat frame;
        d_frame.download(frame);
        cv::imshow("GPU", frame);

        if (cv::waitKey(3) > 0)
            break;
    }
    return 0;
}

#else
int main()
{
    std::cout << "OpenCV was built without CUDA Video decoding support\n" << std::endl;
    return 0;
}
#endif
```

**Comment by pawan9** [comment]
on debugging found out that OpenCV was compiled without HAVE_FFMPEG flag. Had to maually compile ffmpeg and then recompiled OpenCV and now it works fine.

**Comment by ZinniaSun2000** [comment]
how to compile it? Can you give me more hint?

**Comment by Adonishl** [comment]
Recently, i also encounter with this problem. While I have compiled ffmpeg from source code and added "-D WITH_FFMPEG" flag into OpenCV's compiling, the rtsp/rtmp streams still cannot be decoded. Is there any special tricks?

**Comment by pawan9** [comment]
@Adonishl what do you see in the opencv cmake configuration (ffmpeg part). It should look similar to this 
![screenshot from 2017-11-01 17-19-22](https://user-images.githubusercontent.com/3811164/32273621-309d6884-bf29-11e7-8fe9-dcde37925e61.png)

If not than you would have to build ffmpeg manually.

**Comment by Adonishl** [comment]
@pawan9 in opencv cmake configuration, I got
![screenshot from 2017-11-02 20-00-26](https://user-images.githubusercontent.com/26041901/32359154-9b737e1a-c086-11e7-8f8c-0c5a76723fa9.png)
however, it works fine with the stream came from an ip camera, but still come to the same error message when i use ffserver to stream a video file as a rtsp stream.
Actually, I can play this rtsp stream in vlc and use ffmpeg to decode this rtsp stream as well. But still not work in OpenCV.
Well, an example for ffserver to stream a video file is:
1. modify the configure file for ffserver("/etc/ffserver.conf") to
HTTPPort 9999
RTSPPort 9990
HTTPBindAddress 0.0.0.0
MaxClients 1000
MaxBandWidth 100000
CustomLog -
<Stream test>
  Format rtp
  File "/home/video/test.mp4"
</Stream>
2. Use command "ffserver -f /etc/ffserver.conf", you can get a rtsp stream for the video file(/home/video/test.mp4). And the stream address is "rtsp://localhost:9990/test"
It really stucked me for weeks!!!If you don't mind to try this, please tell me about your result. Thank you!

**Comment by pawan9** [comment]
@Adonishl I had a similar problem where a stream from a ip camera was playing perfectly in vlc but was not being played by `cv::cudacodec::VideoReader` even after building it with FFMPEG. 

You should check if the codec and pixel format of your stream (as shown in vlc) are they supported in the `InputMediaStream_FFMPEG::open` [method](https://github.com/opencv/opencv/blob/7267e94be78b3c8be4f1f08b912ab57a52cf0954/modules/videoio/src/cap_ffmpeg_impl.hpp#L2569)

What i found out in my case was that while vlc detected the pixel format of stream as YUV420P, ffmpeg detected it as YUVJ420P so i made a change [here](https://github.com/opencv/opencv/blob/7267e94be78b3c8be4f1f08b912ab57a52cf0954/modules/videoio/src/cap_ffmpeg_impl.hpp#L2646) 
`case AV_PIX_FMT_YUV420P:
 case AV_PIX_FMT_YUVJ420P:
                *chroma_format = ::VideoChromaFormat_YUV420;
                break;`

and it worked for me.

You should try debugging `InputMediaStream_FFMPEG::open` and see what is happening.

**Comment by Adonishl** [comment]
@pawan9 Today I have checked the codec_id and pix_fmt of my stream. And it showed up that ffmpeg detected my stream as AV_CODEC_ID_H264&YUV420P. And these are supported in InputMediaStream_FFMPEG::open. So I don't think it is the similar problem as yours. But still I'd like to thank you for your mention about debugging the source code of OpenCV. I will keep going on that. Thanks a lot :)

**Comment by ibrahimsherdil** [comment]
@Adonishl Greetings!
Did you find anything helpful?  I am facing the same issue.

**Comment by Adonishl** [comment]
@ibrahimsherdil Actually, I just found that my video file is encoded by h264. So I tried to transcode it into MPEG1/MPEG2. It worked for me. Maybe you you can try it.

**Comment by ibrahimsherdil** [comment]
How do you transcode an **rstp stream**?

**Comment by Adonishl** [comment]
You can use FFmpeg command line to transcode any video file/stream. And also you can try vlc to convert/stream a video file/stream.

**Comment by basilzeno** [comment]
@pawan9 I have same issue, after applying your suggestion, only rtsp with local IP address are working. I tried to change tcp flag in this file also, but i noticed that opencv forces ffmpeg to use tcp.

Are there any solutions?

Error:
OpenCV Error: Unsupported format or combination of formats (Unsupported video source) in FFmpegVideoSource,.....

* System information (version):
  * OpenCV => 3.3.0
  * Operating System / Platform => Ubuntu 16.04, x86_64
  * Compiler => gcc version 5.4.
  * Cuda => 8.0
  * Nvidia card => GTX 550 Ti

**Comment by pawan9** [comment]
@basilzeno Is the remote stream working in VLC ? 
check the codec of that stream and make sure it is supported by your graphics card.

**Comment by basilzeno** [comment]
@pawan9 yes, It is working in VLC !

**Comment by pawan9** [comment]
@basilzeno what is the codec and pixel format of the stream ?

**Comment by basilzeno** [comment]
@pawan9 
For local rtsp url:
      Video Codec: H264
      Pixel Format : YUV420

For public rtsp url:
      Video Codec: H264
      Pixel Format : YUVJ420

I can open both using vlc:
   vlc rtsp_stream

I can write them into mp4 file using ffmpeg:
    Local:
        fmpeg -i rtsp://admin:usrname@IP:Port/**/***   -r 30 -vcodec copy -an -t 60  [Path To mp4 File]
   Public:
        fmpeg  -rtsp_transport tcp  -i    rtsp://IP/*****    -r 30 -vcodec copy -an -t 60  [Path To mp4 File]
        HERE, I added rtsp_transport flag, without it there will be error:  "Invalid data found when processing input"


Any ideas to solve the problem?

**Comment by pawan9** [comment]
@basilzeno Please refer to my [comment](https://github.com/opencv/opencv/issues/9739#issuecomment-341885574). Make the changes as described and rebuild OpenCV.

**Comment by basilzeno** [comment]
@pawan9  I made the changes as described, then rebuilt OpenCV again, BUT it's still not working!

**Comment by Dyex719** [comment]
@Adonishl 
Can you please elaborate how I can transcode a live RTSP stream?
I tried @pawan9 's fix, but I still get the same error.
Video Codec: H264
Pixel Format : YUVJ420

**Comment by Dyex719** [comment]
I have the same exact error however the solution as mentioned by @pawan9 unfortunately doesn't work.

When I run gdb on opencv/modules/cudacodec/src/ffmpeg_video_source.cpp,

`
(gdb) n
OpenCV Error: Gpu API call (CUDA_ERROR_FILE_NOT_FOUND [Code = 301]) in CuvidVideoSource, file /usr/deepak/ffmpeg-gpu/opencv/modules/cudacodec/src/cuvid_video_source.cpp, line 66
[New Thread 0x7fffe1328700 (LWP 31246)]
[New Thread 0x7fffe0b27700 (LWP 31247)]
[New Thread 0x7fffdba98700 (LWP 31248)]
[Thread 0x7fffdba98700 (LWP 31248) exited]
22	        if (!d_reader->nextFrame(d_frame))
`

`
(gdb) n
OpenCV Error: Unsupported format or combination of formats (Unsupported video source) in nextFrame, file /usr/deepak/ffmpeg-gpu/opencv/modules/cudacodec/src/video_reader.cpp, line 128
terminate called after throwing an instance of 'cv::Exception'
  what():  /usr/deepak/ffmpeg-gpu/opencv/modules/cudacodec/src/video_reader.cpp:128: error: (-210) Unsupported video source in function nextFrame
`

**Comment by nick1392** [comment]
Getting the same issue here, any update?
