### ISSUE TITLE
a doubt problem with caffe training by numstage

### ISSUE THREAD

**Issue by jianti** [opencv/opencv#9749]
As you know, When we use opencv inner training cascade classifier(haar),we need to setup some parameters.The question happen to "numStage",Such as i set that to 20,At the began it will read the negative samples fast,But when the program execute to about 7 or 8 stage ,the read speed will slow down ,read 100 image need about 30 seconds, why will happen this phenomenon?

**Comment by alalek** [comment]
Usually (for proper datasets) cascade stage training time grows exponentially.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
