### ISSUE TITLE
dnn readNetFromTensorflow fails to load TensorFlow object detection models

### ISSUE THREAD

**Issue by hansg60** [opencv/opencv#9751]
- OpenCV => 3.3.0
- Operating System / Platform => MacOS 10.13

##### Detailed description

The dnn.readNetFromTensorflow function fails with the following error message when loading one of the models from the Tensorflow detection model zoo here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

```
OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat) in populateNet, file /tmp/opencv-20170916-87764-1y5vj25/opencv-3.3.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 883
Traceback (most recent call last):
  File "./tensorflow_test.py", line 17, in <module>
    net = dnn.readNetFromTensorflow('frozen_inference_graph.pb')
cv2.error: /tmp/opencv-20170916-87764-1y5vj25/opencv-3.3.0/modules/dnn/src/tensorflow/tf_importer.cpp:883: error: (-2) Unknown layer type Cast in op ToFloat in function populateNet
```

##### Steps to reproduce

1. Download one of the models from the Tensorflow detection model zoo. http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_11_06_2017.tar.gz
2. Expand the archive to get the frozen_inference_graph.pb file
3. Execute a python script that loads the frozen_inference_graph.pb file.
dnn.readNetFromTensorflow('frozen_inference_graph.pb')

The function will fail with the error message shown above.

**Comment by dkurt** [comment]
@hansg60, thanks! We've started work on it at https://github.com/opencv/opencv/pull/9750. Please note that the solution is in progress.

**Comment by NguyenHoanh1703** [comment]
PLS, I got the same issue, need a solution!!!

**Comment by RomRoc** [comment]
Hello, can I know please if this issue is solved? I download latest version of opencv (3.3.1dev) but I still get the error.
Thanks

**Comment by dkurt** [comment]
@RomRoc, have you tried ti run a sample code https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py?

**Comment by RomRoc** [comment]
Thanks for your quick reply,
Now I tested with the sample provided, everything is ok.
Thanks

**Comment by yzhaoml** [comment]
I update to latest CV 3.4.0, and use python 3.5, when I running the "mobilenet_ssd_python.py", I got the following errors
cv2.error: /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:54: error: (-2) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: coco_data/ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie

Please help me to solve this issue

**Comment by boopathit98** [comment]
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version)
Traceback (most recent call last):
  File "webcam1.py", line 3, in <module>
    import lasagne.layers.dnn
  File "/home/rda/anaconda2/envs/tensorflow/lib/python2.7/site-packages/lasagne/layers/dnn.py", line 13, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
