### ISSUE TITLE
Feature Request : ability to load Caffe/Tensorflow from FileStorage or from similar in-memory

### ISSUE THREAD

**Issue by r2d3** [opencv/opencv#9765]
##### System information (version)

- OpenCV =>  3.3
- Operating System / Platform => macOS 10.11
- Compiler => Xcode 8.2.1 / clang-800.0.42.1

##### Detailed description

Like we could load cv::ml::SVM from a cv::FileStorage :

~~~
cv::FileStorage fs;
m_svm = cv::Algorithm::read<cv::ml::SVM>(fs["SVM"]);
~~~

It will look like : `cv::dnn::Net = readNetFromTensorflow(fs["Model"]);`

**Comment by dkurt** [comment]
@r2d3, have you tried to save some of models in `xml.gz` format by http://docs.opencv.org/master/da/d56/classcv_1_1FileStorage.html#a5f12cb8b2f78e7a9708cd03c69133732? Does it give any compression profit?

**Comment by r2d3** [comment]
Hello @dkurt,

the problem is not compressing the data. The use case is to load data that are not on disk or not in a .pb/.caffemodel/.prototxt file.

For example, the binary stream representing my pb/caffemodel file could be embedded in a .xml/.yml file loaded via FileStorage.

Presenting an API that accepts FileStorage/FileNode as input for readNetFrom*() will extend the way we could read it.

For example, readNetFromTensorflow is using a std::ifstream internally, so perhaps just exposing an API that accepts an std::istream could be OK.

**Comment by Solonets** [comment]
That is a must-have feature: Raw model files are not usually accessible in final products: they can be embedded, encrypted or even dynamic.

**Comment by r2d3** [comment]
I have written a first version for TensorFlow : https://github.com/r2d3/opencv/tree/dnn_memory_load

https://github.com/r2d3/opencv/blob/dnn_memory_load/modules/dnn/src/tensorflow/tf_io.cpp
using 
ZeroCopyInputStream* raw_input = new ArrayInputStream(data, len);
instead of
ZeroCopyInputStream* raw_input = new IstreamInputStream(&fs);

But at the moment, I have to thing at the API to give. At the moment, I named it:
Net readNetFromTensorflowBuffer(const char *buffer, size_t len);

I am not sure if there is a "prettier" way to go.

I could make a PR for this patch, it will give a starting point

**Comment by dkurt** [comment]
@r2d3, As you mentioned, Google Protobuf -based importers open file streams internally. You may start from Caffe and TensorFlow importers. I think it's not necessary to name methods differently. Just something like:
```
readNetFromCaffe(char*, int, char*, int);
readNetFromCaffe(std::istream&, std::istream&);
readNetFromCaffe(const String&, const String&);
```
Also we need to check Python/Java wrappers for it.
Can I assign you to this issue?

**Comment by r2d3** [comment]
Yes, you can assign this issue to me

I will use the proposed naming convention

I will add loader for other framework than TensorFlow. Probably we will need to add this to the tests

**Comment by Solonets** [comment]
@r2d3 Keep as informed, I can help with it as well.

**Comment by r2d3** [comment]
I submitted a first PullRequest to discuss various question:

- I added a read_inception_buffer test. I should add a model+config buffer test. Adding it for all runTensorFlowNet calls is perhaps overkill
- Do we really need an std::istream version ?
