### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by perfectdim** [opencv/opencv#9774]
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => MacOS
- Xcode 9.0
- IOS 11
- Iphone 8

#####

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
>       objc-class-ref in opencv2(cap_ios_video_camera.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by perfectdim** [comment]
The same is for OpenCV => 3.2.0

When I'm building the app it returns me an error
I guess that it is not a question. It is bug

![2017-10-05 10 41 06](https://user-images.githubusercontent.com/21329734/31212437-fd6bf7a2-a9b9-11e7-81af-6c4e551d178c.png)
![2017-10-05 10 34 34](https://user-images.githubusercontent.com/21329734/31212436-fd3fe69e-a9b9-11e7-98f9-c7b53db4cd9b.png)

**Comment by alalek** [comment]
https://www.extendi.it/blog/2015/5/22/46-how-to-add-opencv-2-4-11-in-your-ios-project

**Comment by perfectdim** [comment]
@alalek Thanks you! It helps!
