### ISSUE TITLE
CMake error caused by wrong path to libopencv_java330.so

### ISSUE THREAD

**Issue by jerry73204** [opencv/opencv#9777]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Arch Linux
- Compiler => GCC 7

##### Detailed description

This error appears at the time I'm compiling yarp, requiring opencv_java as dep. This is the error message.
```
...
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable exact version "8.0") 
CMake Error at /usr/share/opencv/OpenCVModules.cmake:243 (message):
  The imported target "opencv_java" references the file

     "/usr/share/OpenCV/java/libopencv_java330.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/opencv/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/opencv/OpenCVConfig.cmake:165 (include)
  cmake/ycm-0.2/find-modules/FindOpenCV.cmake:88 (find_package)
  cmake/YarpFindDependencies.cmake:363 (find_package)
  CMakeLists.txt:62 (include)
```

The correct path should be `/usr/share/opencv/java/libopencv_java330.so`.  To work around, I manually patched following lines in `/usr/share/opencv/OpenCVModules-release.cmake`, and then yarp compiles without error.
```
IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/share/OpenCV/java/libopencv_java330.so"
...
list(APPEND _IMPORT_CHECK_FILES_FOR_opencv_java "${_IMPORT_PREFIX}/share/OpenCV/java/libopencv_java330.so" )
```

`OpenCVModules-release.cmake` is somewhat a generated file. It might be completely resolved in OpenCV sources, but I failed to work this out.

##### Steps to reproduce

You can simply reproduce this error using `yaourt -S yarp` on Arch Linux, or follow the steps.

1. Make sure you have OpenCV 3.1 installed with prefix `/usr`.
2. Download [yarp](https://github.com/robotology/yarp/releases) tarball.gz, extract it, and change directory to it. (I tested 2.3.70.1)
3. `mkdir build; cd build`, and then `cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DCREATE_GUIS=ON -DCREATE_LIB_MATH=ON`.

**Comment by alalek** [comment]
Looks like this problem is related to `yarp` packaging scripts.
There is no `share/opencv` in OpenCV sources, "default settings" are consistent and use `share/OpenCV`.

**Comment by jerry73204** [comment]
Finally I figure it out. In the case opencv2 is packaged on AUR for Arch Linux users. Its build script renames the `share/OpenCV` to `share/opencv2`, leading to this error.

I've sent a patch to AUR pacakger. Hope this helps.
