### ISSUE TITLE
change in opencv 3.3.0 hash in release tarball

### ISSUE THREAD

**Issue by jcftang** [opencv/opencv#9785]
##### System information (any)

- OpenCV => 3.3.0
- Operating System / Platform => n/a
- Compiler => n/a

##### Detailed description

The hash for the 3.3.0 release source tarball has changed. It was previously eeedaec282a70aa2ea1d5152a372c990 and now it is 98a4e4c6f23ec725e808a891dc11eec4 the tar ball was downloaded from https://github.com/opencv/opencv/releases I noticed this when I was trying to build opencv via spack (https://github.com/LLNL/spack/pull/5623#issuecomment-334528701)

Was the release changed at some point?

**Comment by mshabunin** [comment]
@jcftang , source code snapshots on the "Releases" page are generated by GitHub, we only upload prebuilt versions there. I've found the archive with 'eeed...' MD5 sum [here](https://fossies.org/linux/misc/opencv-3.3.0.tar.gz/), compared it with the archive from GitHub ('98a4...' MD5 sum) - contents are the same.

Maybe GitHub has changed something in tar packing,  I'd suggest using git mirror and commit hashes for verification or zip snapshots from the [sourceforge.net](https://sourceforge.net/projects/opencvlibrary/files/opencv-unix/3.3.0/) - we upload files there manually.

**Comment by jcftang** [comment]
It looks like github may have changed how they generate their tar.gz then, this is a bit of a pain to keep track, but thanks for the help.
