### ISSUE TITLE
imwrite doesn't handle pbm

### ISSUE THREAD

**Issue by derVedro** [opencv/opencv#9791]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 16.04

##### Detailed description

If you try to save some monochrome image as bitmap ( .pbm P1/P4) you get a greymap (P2/P5) picture at outcome.

##### Steps to reproduce

A simple example:
```python
import numpy as np
import cv2
img = np.array([0, 0, 0, 0]).reshape((2,2))
cv2.imwrite('/tmp/out.pbm', img, (32, 0))
```
And out.pbm looks like this:
```
P2
2 2
255
   0   0
   0   0
```

**Comment by vinay0410** [comment]
I would like to add this feature, and have already started working on it, and would submit a pull request soon

**Comment by alalek** [comment]
> monochrome

OpenCV doesn't support monochrome images internally. Only grayscale is supported and it is stored as grayscale [PGM](http://netpbm.sourceforge.net/doc/pgm.html) ([P2](https://github.com/opencv/opencv/blob/3.3.1/modules/imgcodecs/src/grfmt_pxm.cpp#L442-L443)).

Perhaps there is should be `imwrite()` "hint" (via parameter) that says how to store passed `cv::Mat`. [Example](https://github.com/opencv/opencv/issues/10114#issuecomment-351030713). BTW, there is already `IMWRITE_PXM_BINARY` parameter.

**Comment by vinay0410** [comment]
Thanks for the guidance

And, OpenCV directly does not support binary images, but they are often stored as 255 for 1's and 0 for 0's.

The extension i.e .pbm can be used to specify if the image is to be stored as a PBM P1/P4.

Also, ```IMWRITE_PXM_BINARY``` is used to specify, if the image will be written in binary form( byte by byte) or ASCII( using chars representing numbers)

So, either 255 can be mapped as 1's and 0 as 0's, or a parameter can be asked to input as threshold, above while will be 1's and below 0's.

**Comment by vinay0410** [comment]
@alalek, I have added this feature, and also tested it using python, for both binary and ascii types and works fine.

But while running testcases from opencv_extra, imgcodecs module, I get a segmentation fault.

![image](https://user-images.githubusercontent.com/18044818/34108798-7d0a0646-e427-11e7-9508-5b97d91afda8.png)

Also this segmentation fault goes if I comment the if else statements where I decide whether to write a bitmap or not, using writeBitmap bool.
