### ISSUE TITLE
imshow("Live", frame);

### ISSUE THREAD

**Issue by lucasyue** [opencv/opencv#9793]
System information (version)
- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- Compiler =>mingw-make 3.8

Detailed description
the bellow code works ok,imshow() can show frame from my thinkpad camera ,when i use opencv3.2,but after changed to opencv3.3,it always shows blank window.what's about the reason?can you tell me?thanks.

VideoCapture cap;
...
cap.read(frame);
imshow("Live", frame);
waitKey(100);

**Comment by Bhanudutta** [comment]
@lucasyue 
I faced the same issue , the issue solved when I used mingW-w64 instead of mingW .
Hope it helps

**Comment by lucasyue** [comment]
@Bhanudutta tks
