### ISSUE TITLE
getDefaultPeopleDetector : Number of coefficients 3781?

### ISSUE THREAD

**Issue by rdabane** [opencv/opencv#9814]
Why does this function have 3781 coefficients ? 
For a 64x128 window with block_size = 8x8, cell_size = 2x2 and 9 bin histogram : 
total size of hog descriptor = 7*15*4*9 = 3780.

How is this suppose to work?

**Comment by berak** [comment]
[here's the formula](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp#L94)

so, for the default arguments, we get :

    9 * (16/8) * (16/8) * ((64 - 16)/8 +1) * ((128 - 16)/8 +1) = 3780

(and your maths is slightly off, for block_size = 8x8, cell_size = 2x2, you get 18432 elements)

this is the size of the hog **descriptor** . the pretrained **svm support vector** has one more element [added to the end](https://github.com/opencv/opencv/blob/master/samples/cpp/train_HOG.cpp#L35), **rho**, which is the [bias term for the dot-product](https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp#L1710-L1761) used in the svm prediction

(also, next time, pleasee ask questions like this on http://answers.opencv.org , not here, this is the library bug tracker)

**Comment by alalek** [comment]
@berak Thank you!
