### ISSUE TITLE
Error of opencv in not-found reference of InitializeCriticalSectionEx

### ISSUE THREAD

**Issue by thuanvh** [opencv/opencv#9817]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows XP 32 Bit
- Compiler => Visual Studio 2010

##### Detailed description

I build opencv 3.3 from source on Windows XP and having a not-found reference of InitializeCriticalSectionEx error in opencv_core330.dll.
I tried to build with opencv 3.2 on the same machine but there is no error in dll reference.
I do not use TBB.
I tried to add preprocessor _WIN32_WINNT=0x0501 and _WIN32 into project opencv_core but the error remains.
##### Steps to reproduce
Create cmake build
Open solution opencv.sln with Visual Studio 2010
Build successfully
Open Dependency Walker to check opencv_core330.dll
And there is a missing of InitializeCriticalSectionEx

**Comment by alalek** [comment]
> Windows XP 32 Bit

Not supported anymore, so we will not try to investigate/fix this issue. But we can review/accept proposed fix for this (via GitHub Pull Requests).

**Comment by thuanvh** [comment]
I turn off WITH_IPP option in cmake. Then now this error disappeared. Maybe I will revert ipp version of opencv 3.2.

**Comment by thuanvh** [comment]
In detail, error of reference is in library ipp-iw
