### ISSUE TITLE
videoio open regression with segfault

### ISSUE THREAD

**Issue by arpu** [opencv/opencv#9825]
opencv 3.3.0 works with open a gstreamer videoio 
last working is 6fc569795070db21a19342624e8913e58c1f3262
segfault on 
c5f2170ce84ca0967675654fa1bb7c5221f2e9cb

compile config from segfault build is 
http://lpaste.net/2513453731073228800

sample code:
 int exposer = 312;
 int device_id = 0; 
  QString gst_pipe0 =
      "v4l2src device=/dev/video" + QString::number(device_id) +
      " extra-controls=\"c,exposure_auto=1,exposure_absolute=" +
      QString::number(exposer) + ",white_balance_temperature_auto=false,white_balance_temperature=4000"
      "\" ! image/jpeg, framerate=60/1, width=1920, height=1080 "
      "! "
      "jpegdec ! videoconvert   ! appsink";

  std::cout << "gst_pipe:" << gst_pipe0.toStdString() << std::endl;
 
  m_cvCapture.open(gst_pipe0.toStdString());

sample qt programm attached
[qtopencv.zip](https://github.com/opencv/opencv/files/1373378/qtopencv.zip)

**Comment by arpu** [comment]
anything else what i can post to fix this?

**Comment by alalek** [comment]
> segfault

stacktrace would be useful (from debug build, or build with "-g" compiler flag).

BTW, I checked diff between mentioned commits - there are no changes in videoio module between them. Also they are on different feature trees, consider to use [git bisect](https://git-scm.com/docs/git-bisect) to find problem commit.

**Comment by arpu** [comment]
the stacktrace looks strange for me  :/ no idea if this helps

http://lpaste.net/359237
looks like more a thread problem

**Comment by arpu** [comment]
git biselect gives me 
[179ef0a9757534aa5b27a28279e45b911ea67654] Merge pull request #9429 from StevenPuttemans:fix_9404

**Comment by arpu** [comment]
git bisect bad
f694192878a1a0a8140b5c001e9172694028f5c3 is the first bad commit
commit f694192878a1a0a8140b5c001e9172694028f5c3
Author: Alexander Alekhin <alexander.alekhin@intel.com>
Date:   Mon Aug 21 17:43:56 2017 +0300

    cmake: use CMAKE_CXX_COMPILER_VERSION (CMake 2.8.8+)
    
    - '-fvisibility' flag was updated
    - PVAPI library detection was changed

:040000 040000 4532a30b9c20f144f2ffd4af8c9a56d508787f52 b7f791f6731949a7daa36bd9b2c74a1ae7babfd1 M	3rdparty
:100644 100644 3e23a3955de78b42316f605cca8041e5e87e87ed 33a381d364ec7ae6db2bf61b26f91a92aa0d6af9 M	CMakeLists.txt
:040000 040000 318788e5f8da532c985c6a2797877adc93fff28e c3f71ceec8cfd60b237abf9bf7309fb7f25dc243 M	cmake

**Comment by arpu** [comment]
ok i can confirm 

a fresh git master clone and a 
git revert f694192878a1a0a8140b5c001e9172694028f5c3

gets my programm running again on master

**Comment by alalek** [comment]
Thank you for investigation!

Could you add dump of CMake output (stdout) with and without mentioned commit?
(it would be nice to attach CMakeCache.txt/CMakeVars.txt files too)
```
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/c++  (ver 4.8.4)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      
--     Linker flags (Debug):        
--     ccache:                      YES
--     Precompiled headers:         NO
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
```

**Comment by arpu** [comment]
sorry for late response 
testing todays master cca99bf8249387da9f79be8d549b2d49e39a0289
and all works fine, should i search for the commit that fixed this?
