### ISSUE TITLE
Unknown layer type Cast in op ToFloat in function populateNet

### ISSUE THREAD

**Issue by legion-zver** [opencv/opencv#9830]
Gentlemen's, according to the tasks this problem is supposedly solved! I downloaded the latest version from the repository and nothing has changed for me... I'm using the usual MobileNet model from Tensorflow (train it for detect 1 type objects). Please help me!!!

ToFloat:Cast(image_tensor)
DstT:[ ]
SrcT:[ ]
OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat) in populateNet, file /Users/Alexander/Documents/CppProjects/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 1296
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/Alexander/Documents/CppProjects/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1296: error: (-2) Unknown layer type Cast in op ToFloat in function populateNet

**Comment by dkurt** [comment]
@legion-zver, we have a workable solution for the origin MobileNet-SSD from TensorFlow: https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py. Have you tried to modify https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt for 1 class detection? Can you share a TensorFlow object detection API configuration file?

**Comment by legion-zver** [comment]
I understood, although I did not like the solution (sending the config in addition to * .pb) (it's crib). It would be nice to see a well-described Wiki page about this;)

**Comment by barbecacov** [comment]
Have you solved the problem?I met it now but I dont know what to do,please help me

**Comment by dkurt** [comment]
@barbecacov, please classify the problem. That kind of model. Where we can download it. Share configuration file written for model (see https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). Any ways to reproduce will help us to solve the problem faster.

**Comment by barbecacov** [comment]
@dkurt the Configuration file is https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config.I just change the num_classes and some files'path

**Comment by barbecacov** [comment]
@dkurt the model is in https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md 
ssd_mobilenet_v1_coco

**Comment by barbecacov** [comment]
@dkurt Now I want to get the .pbtxt just like the https://github.com/opencv/opencv_extra/tree/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt

**Comment by LiuXiaolong19920720** [comment]
@dkurt 

> we have a workable solution for the origin MobileNet-SSD from TensorFlow: https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py. Have you tried to modify https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt for 1 class detection? Can you share a TensorFlow object detection API configuration file?
Thanks! I met the same problem and it is solved by above solution. I can load the mobilenet model which is trained by TensorFlow Object Detection API and detect object successfully, in C++, finally. The mian load code is like below:
`	String weights = "face_frozen_inference_graph.pb";
	String prototxt = "ssd_mobilenet_v1_coco.pbtxt";
	
	dnn::Net net = cv::dnn::readNetFromTensorflow(weights,prototxt);`

**Comment by dkurt** [comment]
@LiuXiaolong19920720, thank you for the feedback! Just let me ask one thing. Did you train single class object detection model (face detection I guess)? Than you modified `ssd_mobilenet_v1_coco.pbtxt` with `attr { key: "num_classes" value { i: 2 } }`. Right?

**Comment by LiuXiaolong19920720** [comment]
@dkurt Yes! I trained a single class object detection model. But modified modified `ssd_mobilenet_v1_coco.pbtxt`  at two location. 

- line 2206: `int_val: 2  # Number of classes + 1.`
- line 2222: `attr { key: "num_classes" value { i: 2 } }`

**Comment by LiuXiaolong19920720** [comment]
@dkurt You are right. I change the line 2206 back to ` int_val: 91` and the output does not change.

**Comment by barbecacov** [comment]
@LiuXiaolong19920720 So have you  tried other models,just like ssd_inceptions_v1？

**Comment by LiuXiaolong19920720** [comment]
@dkurt  Not yet. Training or finetuning a model is very time consuming because my PC don't have a usable GPU, so I only tried mobilenet, the fastest one.

**Comment by barbecacov** [comment]
@LiuXiaolong19920720 老哥，我们私聊一下吧，这个问题我很棘手

**Comment by LiuXiaolong19920720** [comment]
@barbecacov weixin: 18101287278。加上我就把这条删掉。

**Comment by dkurt** [comment]
@barbecacov, please rewrite it in English. Your message may be helpful for other users.

**Comment by LiuXiaolong19920720** [comment]
@dkurt His message not helpful for others。He just asked for my personal contact information。

**Comment by kerolos** [comment]
i got an error when i passed two parameters to this function cv.dnn.readNetFromTensorflow()
ERROR:
net = cv.dnn.readNetFromTensorflow(args.weights, args.prototxt)
TypeError: readNetFromTensorflow() takes at most 1 argument (2 given)

and also I got this error when I passed only this parameter (frozen_inference_graph.pb) 
ERROR:
ToFloat:Cast(image_tensor)
SrcT:[ ]
DstT:[ ]
OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat) in populateNet, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 883
Traceback (most recent call last):
  File "mobilenet_ssd_python.py", line 59, in <module>
    net = cv.dnn.readNetFromTensorflow(args.weights)
cv2.error: /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:883: error: (-2) Unknown layer type Cast in op ToFloat in function populateNet

I faced all those errors when I used either C++ or Python as a language. furthermore, I am using OpenCV 3.3.0,
I would appreciate if anyone can help me to solve this problem thanks in advance.

**Comment by kdouc** [comment]
@dkurt I have same problem like 
ERROR:
ToFloat:Cast(image_tensor)
SrcT:[ ]
DstT:[ ]
i can run https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt successful. but i have train a new model and change image size,min dip in the mobilenet_v1_coco.config, so i can't use this pbtxt...
is there any way to get  pbtxt just like the link?(i have just get a pbtxt from frozen.pb but it got the same question...)
thanks,wating for help!

**Comment by andrew-anki** [comment]
@dkurt  I have the same problem as @kdouc .  The "special" `.pbtxt` file you've kindly provided for the default SSD MobileNet architecture is helpful, but can you give us any instructions on how you created it? That way we can follow the same approach with custom-built SSD MobileNet architectures. For example, I want to adjust the image size and `depth_multiplier` parameters in the `config` file, but if I do so, then I cannot load the trained graph. It would be really helpful to have a step-by-step method for converting a trained SSD MobileNet to be compatible with OpenCV, and not just a "magic" file that only works for one particular configuration.

**Comment by dkurt** [comment]
@andrew-anki, thank you for a feedback! You are completely right that we should focus on the flexibility of object detection models. I've tried to write a some guide several times but it turns out that it's simpler to write a script that can repeat these steps.

Please take a look on a PR https://github.com/opencv/opencv/pull/10723 and a corresponding wiki page https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. Note that some of the links are going to be actual after merging of some PRs. You can help us testing this script with your model.

**Comment by andrew-anki** [comment]
Thanks @dkurt , this looks really promising! I tried running the `tf_text_graph_ssd.py` script on my model and got an error. So I tried just making sure I could run it on the original SSD MobileNet architecture from the TF Object Detection page. I got the same error for that as well, so I don't think the problem is just my modifications to the config file:

```
python models/research/object_detection/tf_text_graph_ssd.py --input ~/Downloads/ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb --output graph.pbtxt
Traceback (most recent call last):
  File "models/research/object_detection/tf_text_graph_ssd.py", line 90, in <module>
    graph_def.node.MergeFrom([concatAxis])
  File "~/tensorflow-r1.5/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 397, in MergeFrom
    self.extend(other._values)
AttributeError: 'list' object has no attribute '_values'
```

As you may noticed, I'm using TF 1.5 here. The wiki page mentioned TF version ">= 1.4", but maybe 1.5 is problematic?

**Comment by dkurt** [comment]
@andrew-anki, I tried TensorFlow 1.5 and there is no problem for me. I think it's because of protobuf version. Can you check it?
```python
import google.protobuf as pb
print pb.__version__
```

**Comment by andrew-anki** [comment]
Sure:
```
>>> import google.protobuf as pb
>>> print pb.__version__
3.5.1
```

**Comment by Minxiangliu** [comment]
@dkurt  I have the same problem too.

D:\Program\PythonCode\tools>python tf_text_graph_ssd.py --input frozen_inference
_graph.pb --output out_graph.pb --num_classes 1
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 90, in <module>
    graph_def.node.MergeFrom([concatAxis])
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\containers.py",
line 397, in MergeFrom
    self.extend(other._values)
AttributeError: 'list' object has no attribute '_values'

**Comment by dkurt** [comment]
@andrew-anki, @Minxiangliu, I tried to replace an every `MergeFrom` to `extend` locally. May I ask you to do the same? I'll update a script if it solves the problem. Thank you in advance!

**Comment by Minxiangliu** [comment]
@dkurt  I replace `MergeFrom` to `extend` and solves the problem.
But I try run the code :
`cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'out_graph.pbtxt')`
Show error:
 cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'out_graph.pbtxt')
cv2.error: C:\ci\opencv_1512684736357\work\modules\dnn\src\tensorflow\tf_importer.cpp:555: error: (-2) Const input blob for weights not found in function cv::dnn::experimental_dnn_v2::`anonymous-namespace'::TFImporter::getConstBlob

Can you tell me the reason?

**Comment by dkurt** [comment]
@Minxiangliu, Firstly check paths to `frozen_inference_graph.pb` and `out_graph.pbtxt`. If it's OK, please specify a model source. Is it a public one or yours? Thanks!

**Comment by Minxiangliu** [comment]
@dkurt I follow TensorFlow Object Detection API and have been trained model.
Reference website:
https://github.com/tensorflow/models/tree/master/research/object_detection
My trained config file and result link:
https://drive.google.com/open?id=1Npu54EGHtqdd6dFb2Ff3TxRb5UpE1xkP
mac_n_tomato_graph directory is created by using [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py)

**Comment by dkurt** [comment]
@Minxiangliu, may I ask you to create a question at http://answers.opencv.org? Because it's hard to track closed issues. Just add the same references. Thank you!
