### ISSUE TITLE
Option to disable OpenCL access to the gpu

### ISSUE THREAD

**Issue by msarett** [opencv/opencv#9852]
I'm working on an OpenCV application that needs to be explicit/careful with its use of gpu resources.  In general, OpenCV is pretty reliable about this (using gpu:: to access the gpu).

Recently I noticed a problem with gpu resource contention in my application and was surprised to discover that OpenCV was using the gpu even though I was using the general non-gpu API.  It turns out that I had OpenCL enabled and OpenCL was accessing the gpu.

In my application (and I would guess in others as well), it is definitely undesirable for OpenCV to use gpu resources unless it is explicitly directed to do so.  I've disabled OpenCL for now as a quick fix.

Is this working as intended, or do you think it is reasonable for OpenCV to prevent OpenCL from using the gpu in these situations?  Does it make sense to have an option to prevent OpenCL from using the gpu?

**Comment by alalek** [comment]
These environment variables turn off OpenCL in OpenCV (prevents default OpenCL initialization):
```
OPENCV_OPENCL_RUNTIME=null
or
OPENCV_OPENCL_DEVICE=disabled
```
