### ISSUE TITLE
OutputArray.release() corrupt std::vector

### ISSUE THREAD

**Issue by VladKS** [opencv/opencv#9858]
{
        std::vector<cv::Point2f> s;
        cv::OutputArray d(s);
        d.release();
    }
![image](https://user-images.githubusercontent.com/32807561/31581466-02422ca0-b13b-11e7-9044-0ec9aebe7d7f.png)

**Comment by alalek** [comment]
Can't reproduce with current master.

Please check that your OpenCV build is valid - you using Debug OpenCV binaries for Debug builds of Application.
