### ISSUE TITLE
Correction of variable name of dnn sample program

### ISSUE THREAD

**Issue by iwaki2009** [opencv/opencv#9861]
##### System information (version)

- OpenCV => master
- Operating System / Platform => ubuntu 16.04
- Compiler => :grey_question:

##### Detailed description

Since the names of the two points of cv :: rectangle function are top-left and bottom-right, 
it is better to fix the names of the two points used in the following dnn sample program

mobilenet_ssd_python.py
resnet_ssd_face_python.py
ssd_mobilenet_object_detection.cpp
ssd_object_detection.cpp
yolo_object_detection.cpp

**Comment by dkurt** [comment]
@iwaki2009, you're right. The most convenient left, top, right, bottom corresponding to values order would be more readable. On the other hand there is no limitation that `cv::rectangle` points are exactly top-left and bottom-right: https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga07d2f74cadcf8e305e810ce8eed13bc9. They are just `p1` and `p2` that is an opposite point to `p1`.

**Comment by dkurt** [comment]
@iwaki2009, May it be closed?

**Comment by iwaki2009** [comment]
closed
