### ISSUE TITLE
bug for read xml

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#9868]
I have a xml file, that has content:

<?xml version="1.0"?>
<opencv_storage />

when using cv::FileStorage to open the xml file, it triggers a bug:
OpenCV Error: Parsing error (a.xml(2): <opencv_storage> tag is missing) in icvXMLParse, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\persistence.cpp, line 2831

**Comment by alalek** [comment]
OpenCV doesn't support complete XML format. Only subset is supported.
Main purpose of this is:
- export/import data from OpenCV applications
- export for other tools to reuse OpenCV's XML files
- importing of external XMLs is very limited.
