### ISSUE TITLE
`floodFill` sets  mask's outer pixels to 1

### ISSUE THREAD

**Issue by azatsman** [opencv/opencv#9883]
##### System information (version)

- OpenCV => 3.3.0, current github config
- Operating System / Platform => Linux 4.4.0-36-generic #55-Ubuntu SMP  x86_64
- Compiler => g++ 5.4.0

##### Detailed description

Not sure if this is a bug or an undocumented feature:  when using `floodFill` with a mask to fill in an internal region  the outer pixels of the mask (the ones which do not correspond to any image pixels) are set to 1.

##### Steps to reproduce

1. Create an image with black background and non-black rectangle in the middle.
2. Create a black mask
3. Run `floodFill` to fill in the rectangle with a different color and `FLOODFILL_MASK_ONLY` flag.

```.cpp
#include <cstdio>
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc/imgproc.hpp"

static int ww = 32;
static int hh = 24;
static int oldVal = 100;
static int newVal =  20;

int main (int argc, const char *argv[])
{
  cv::Mat img  (hh, ww, CV_8UC1);
  img.setTo (0);
  cv::Mat middleRectangle = img.rowRange(hh/4, 3*hh/4).colRange(ww/4, 3*ww/4);
  middleRectangle.setTo (oldVal);
  cv::Mat theMask  (2+hh, 2+ww, CV_8UC1);
  theMask.setTo (0);
  int flags = 0
    | 4
    | (newVal << 8)
    | cv::FLOODFILL_FIXED_RANGE
    | cv::FLOODFILL_MASK_ONLY;
  cv::floodFill (img,
		 theMask,
		 cv::Point(ww/2, hh/2),
		 newVal,
		 0,
		 cv::Scalar(10), cv::Scalar(10), 
		 flags);
  printf ("Mask( 0, 0) = %3d\nMask( 1, 1) = %3d\nMask(%2d,%2d) = %3d\n",
	  theMask.at<uchar>(0,0),
	  theMask.at<uchar>(1,1),
	  ww/2, hh/2, theMask.at<uchar>(hh/2,ww/2));
  cv::imwrite ("mask.png", theMask);
  return 0;
}
```

**Comment by sovrasov** [comment]
This is just not documented behavior. In docs is stated:
>  Flood-filling cannot go across non-zero pixels in the input mask.
To avoid out-of-bound filling the algorithm asks to provide a bit wider mask and artificially creates a border.
