### ISSUE TITLE
`dilate` reads border values from outside of a sub-image despite `BORDER_CONSTANT` option

### ISSUE THREAD

**Issue by azatsman** [opencv/opencv#9884]
##### System information (version)

- OpenCV => 3.3.0, current github
- Operating System / Platform => Linux 4.4.0-36-generic Ubuntu SMP x86_64
- Compiler => g++ 5.4.0
##### Detailed description

Running `dilate` on a sub-image of a larger image one would expect it to ignore the outside pixels, especially when the `borderType` parameter is set to `BORDER_CONSTANT`, but the sample code below behaves differently.
##### Steps to reproduce
```.cpp
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"

static int ww = 800;
static int hh = 600;
static int offset1  =  40;
static int offset2  = 280;
static int dilation = 200;

int main (int argc, const char *argv[])
{
  cv::Mat image  (hh, ww, CV_8UC1);
  cv::Mat subImage  = image.rowRange(offset1, hh-offset1).colRange(offset1, ww-offset1);
  cv::Mat rectangle = image.rowRange(offset2, hh-offset2).colRange(offset2, ww-offset2);
  cv::Mat subImageDilated;
  image    .setTo (250);
  subImage.setTo (0);
  rectangle.setTo (150);
  cv::dilate (subImage,
	      subImageDilated,
	      cv::getStructuringElement (cv::MORPH_RECT, cv::Size(dilation, dilation)),
	      cv::Point(-1,-1), 1,
	      cv::BORDER_CONSTANT,
	      cv::Scalar::all(0));
  cv::imshow ("subImage",        subImage);
  cv::waitKey (2000);
  cv::imshow ("subImageDilated", subImageDilated);
  cv::waitKey (-1);
  return 0;
}
```

**Comment by sovrasov** [comment]
This is a common practice in OpenCV: if the image is a ROI then pixels of the parent image will be used as a border. To disable this behavior use `BORDER_CONSTANT | BORDER_ISOLATED`.

**Comment by azatsman** [comment]
Thanks for the clarification.
BTW, the documentation for cv::BorderTypes could mention that BORDER_ISOLATED is not really an enum but a bit flag.
