### ISSUE TITLE
detectMultiScale is not const

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9891]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.04 x86-64
- Compiler => g++ 5.4.0

##### Detailed description

`CascadeClassifier::detectMultiScale` (https://docs.opencv.org/3.3.0/d1/de5/classcv_1_1CascadeClassifier.html#aaf8181cb63968136476ec4204ffca498) is not `const`, but it should be, in my opinion.

##### Steps to reproduce

In my opinion, it should be possible to build a function like the following, since detection should not alter the internal state of the cascade (as no training is happening):

```
static void FindFaces(const Mat &image, /*const*/ CascadeClassifier &classifier, vector<Rect> &faces) //detectMultiScale should be const, but is not
{
  classifier.detectMultiScale(image, faces /* optional parameters here */);
}
```

Maybe the method can even be made `const` even in the base class, `BaseCascadeClassifier` (https://docs.opencv.org/3.3.0/da/dd5/classcv_1_1BaseCascadeClassifier.html#a68623391e16daa264f089af99d8d4bbb)

**Comment by alalek** [comment]
Thank you the report!
Unfortunately this can't be fixed at this moment (ABI compatibility requirement), so lets postpone to the next major release branch.

**Comment by dustsigns** [comment]
Would the upcoming 4.0 release be a major enough release branch to break compatibility and fix this issue?

**Comment by alalek** [comment]
Yes!  Feel free to prepare PR.

**Comment by dustsigns** [comment]
I am really sorry, but I am currently too busy with other things to set up an environment for this one PR. If someone could prepare a PR, I would be grateful because I still think that 4.0 would be a great opportunity to change the const-ness of the API here. I'll be happy to contribute code later, but it will likely be too late for the 4.0 release.

**Comment by vpisarev** [comment]
@dustsigns, @alalek, `detect` method must _not_ be const in this case. `CascadeClassifier` uses internal buffers for pyramid, OpenCL buffers (UMat's) etc. that are re-used on subsequent video frames, not reallocated. Adding `const` will confuse users and make them think that they can call `CascadeClassifier::detect` in different threads simultaneously. Which cannot be done, of course.

**Comment by dustsigns** [comment]
This sounds like it is const, but not thread-safe, right? Wouldn't it be better in this case to explicitly state that the method (or the whole object) is not thread-safe in the documentation, but still make the method const?

To clarify: Is the behavior you described about buffers specific to the OpenCL implementation or is the "regular" (CPU) implementation also re-using buffers that are initialized on the first call to `detect`?

**Comment by vpisarev** [comment]
CPU uses buffers as well. I think, basically it means that the method is not "const", since it modifies scratch buffers allocated inside the class instance. Mentioning it in the documentation is not satisfactory solution - people may find (via Google) some older version of the method description and there was no mention that the method is not thread-safe.

I think, in OpenCV we should stick to very simple formula that users do not have to memorize, because it's obvious:
* if the method is "const", it should be thread-safe.
* if the method is "non-const" it's not thread-safe.

So,
* different threads may safely call different const methods (or the same const method) of the same class instance.
* if one of the threads calls non-const method, other cannot safely call const or non-const methods of the same instance simutaneusly.
* however, different threads may safely call const or non-const methods of different class instances.

**Comment by dustsigns** [comment]
I see your point. Would it make sense to provide a const-overload in the long term?

**Comment by alalek** [comment]
IMHO, 'const' is a logical attribute in C++. We should not mess it with any threads-safety.

1. "const" variable, "const" parameter (const reference).
It means that code is not allowed to change "logical" state of variable. You can't clear / re-assign / modify object or call other non-const methods.

2. "const" method (implies "const" this).
Calling of this method should not change logical state of "this" object (externally visible state).
It says nothing about internal representation - you can cache HTTP GET requests, memorize Fibonacci values and so on.

3. Thread safety is completely another thing. I don't see how it is related to C++ compiler "const" rules.
"Const" manuals:
https://en.cppreference.com/w/cpp/language/member_functions - no any word about threads
https://en.cppreference.com/w/cpp/language/cv - no threads with const
https://isocpp.org/wiki/faq/const-correctness - the same


Lets take a look on abstract simple interface:
```
class DetectorInterface
{
public:
    virtual void load(const DetectorParameters&) = 0;
    virtual DetectionResult getDetectionResult(const Input& input) const = 0;
};
```

Why we should drop "const" from the "get" function? We don't know anything about implementation.

Passing this as "const DetectorInterface& detector" blocks called function from calling of `detector.load(...)` non-const method.

---

What C++ standard implies thread safety requirement for const methods?

/cc @csukuangfj

**Comment by vpisarev** [comment]
@dustsigns, I don't think so, but as you see, there is internal discussion :)
@alalek, to many people `const` and thread-safety are closely related things, see https://stackoverflow.com/questions/14127379/does-const-mean-thread-safe-in-c11 for example.

In you code example the method's name `getDetectionResult` is misleading. It not just retrieves the detection result, but rather runs an algorithm, rather complex one, and only then returns the detection result. The name would be more appropriate for the following API:

```
class DetectorInterface
{
public:
    virtual void load(const DetectorParameters&) = 0;
    virtual void detect(const Input& input) = 0; // run the detection algorithm (probably asynchronously), store the result
    virtual DetectionResult getDetectionResult() const = 0; // wait for completion, if needed, return the detection result
};
```

also, the term "externally visible state" is some new interpretation. Many OpenCV classes have some "hidden state", basically the whole implementation is often hidden, so I would not divide the state into "externally visible" and "not".

**Comment by alalek** [comment]
Interface is externally visible state. You should not know internal implementation details (like caching) in interface declaration.

Also "const" methods:
- they are NOT **pure** calls
- these calls can't be optimized out (in case of duplication)

Assuming things (like thread-safety) which can't be controlled/checked by C++ compiler seems as dangerous practice to me.

**Comment by csukuangfj** [comment]
a `const` modifier for a class member function is to make `const this` so that we cannot modify
its internal data members or call member functions requiring `this`. 

These kinds of protections are only used by compilers and a programmer can declare a data member as `mutable` or use `const_cast<>` in order to modify its internal states, so I do not think
`const` has something to do thread safety.

**Comment by asmorkalov** [comment]
After offline meeting with @alalek @vpisarev @asmorkalov @vladimir-dudnik @VadimLevin it was decided to stay with existing interface. Closed.

**Comment by dustsigns** [comment]
May I ask what the reason is for this decision?
