### ISSUE TITLE
DNN-no minimum layer

### ISSUE THREAD

**Issue by JosiahKane** [opencv/opencv#9894]
##### System information (version)
OpenCV => 3.3.0.10 installed with pip from opencv-python, and at HEAD installed manually
Operating System => macOS High Sierra
Compiler => Apple LLVM version 9.0.0 (clang-900.0.38)

##### Detailed description

The DNN module does not support the basic math operations from tensorflow, such as minimum. This causes problems, in particular, with executing the Keras implementation of Mobilenet (when exported as a tensorflow graph).

Using the MobileNet network provided with Keras, the line
cv2.dnn.readNetFromTensorflow(<pb_file>)
crashes with the error
mobilenet_1_00_160/conv1_relu/clip_by_value/Minimum:Minimum(mobilenet_1_00_160/conv1_relu/Relu)(mobilenet_1_00_160/conv1_relu/Cast/_106__cf__106)
T:0
OpenCV Error: Unspecified error (Unknown layer type Minimum in op mobilenet_1_00_160/conv1_relu/clip_by_value/Minimum) in populateNet, file ../modules/dnn/src/tensorflow/tf_importer.cpp, line 1296
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: ../modules/dnn/src/tensorflow/tf_importer.cpp:1296: error: (-2) Unknown layer type Minimum in op mobilenet_1_00_160/conv1_relu/clip_by_value/Minimum in function populateNet

The error still occurs at the current tip of master, and in particular has not been resolved by 
https://github.com/opencv/opencv/pull/9517

**Comment by dkurt** [comment]
@JosiahKane, mentioned PR is for MobileNet which is used for image classification. There is no minimum ops at all. Perhaps the problem is in object detection MobileNet. Can you try to use MobileNet-SSD sample https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py for model from [TensorFlow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) or get us a reference to Keras implemetation. Many thanks!

**Comment by JosiahKane** [comment]
Yes, I am referring to the implementation of MobileNet which comes with Keras 
https://keras.io/applications/#mobilenet
When the underlying tensorflow network is exported, it has minimum and maximum layers as the decomposition of relu6 activations. 

I understand that Keras (and Tensorflow, per https://www.tensorflow.org/programmers_guide/version_compat) reserves the right to implement some layers, and even to change that implementation, as composites of primitive operations like this, so I would be very surprised if this is only an issue with MobileNet. 

I'll try to get a minimal reference example sorted out.

**Comment by dkurt** [comment]
@JosiahKane, We can make a text graph representation to help OpenCV parse the model. The following code will produce a text graph from a binary one excluding weights and attributes are not used by OpenCV's importer:
```python
import tensorflow as tf

# Read the graph.
with tf.gfile.FastGFile('graph.pb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# Remove Const nodes.
for i in reversed(range(len(graph_def.node))):
    if graph_def.node[i].op == 'Const':
        del graph_def.node[i]
    for attr in ['T', 'data_format', 'Tshape', 'N', 'Tidx', 'Tdim',
                 'use_cudnn_on_gpu', 'Index', 'Tperm', 'is_training',
                 'Tpaddings']:
        if attr in graph_def.node[i].attr:
            del graph_def.node[i].attr[attr]

# Save as text.
tf.train.write_graph(graph_def, "", "text_graph.pbtxt", as_text=True)
```
In text representation we can easily replace minimum+maximum pairs to `ReLU6` nodes. Please attach resulting file here. Thanks!

**Comment by bobyguo** [comment]
@dkurt I have the same problem by converting  Keras implementation of Mobilenet. The "text_graph.pbtxt" plese see the attachment. Thanks!
[text_graph.pbtxt.txt](https://github.com/opencv/opencv/files/1501803/text_graph.pbtxt.txt)

**Comment by dkurt** [comment]
@bobyguo, May I ask you to attach checkpoint files?
```
*.ckpt.data-00000-of-00001
*.ckpt.index
*.ckpt.meta
```
One strange thing about the model: an every `ReLU6` is following after `ReLU` layer.

**Comment by bobyguo** [comment]
@dkurt, I don't have the checkpoint. The model is trained with Keras and saved with ".h5" format. Then I used this [script ](http://blog.csdn.net/liuguangsuiyue/article/details/78298602) to convert ".h5" in ".pb" file:
```
# coding=utf-8
import sys

from keras.models import load_model
import tensorflow as tf
import os
import os.path as osp
from keras import backend as K


def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a prunned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    prunned so subgraphs that are not neccesary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph


input_fld = sys.path[0]
weight_file = 'your_model.h5'
output_graph_name = 'tensor_model.pb'

output_fld = input_fld + '/tensorflow_model/'
if not os.path.isdir(output_fld):
    os.mkdir(output_fld)
weight_file_path = osp.join(input_fld, weight_file)

K.set_learning_phase(0)
net_model = load_model(weight_file_path)


print('input is :', net_model.input.name)
print ('output is:', net_model.output.name)

sess = K.get_session()

frozen_graph = freeze_session(K.get_session(), output_names=[net_model.output.op.name])

from tensorflow.python.framework import graph_io

graph_io.write_graph(frozen_graph, output_fld, output_graph_name, as_text=False)

print('saved the constant graph (ready for inference) at: ', osp.join(output_fld, output_graph_name))
```

The output ".pb" file is then converted by using the methode [transform_graph](https://github.com/opencv/opencv/pull/9517) 
```
~/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
  --in_graph=mobilenet_v1_frozen.pb \
  --out_graph=mobilenet_v1_for_dnn.pb \
  --inputs=input \
  --outputs=MobilenetV1/Predictions/Softmax \
  --transforms="fold_constants sort_by_execution_order remove_nodes(op=Squeeze)"
```
I am not sure whether this process is correct.

**Comment by bobyguo** [comment]
@dkurt, by the way, I build the MobileNet with this [example](https://keras.io/applications/#mobilenet) .  "relu6" is a custom object which defined by:
```
def relu6(x):
    return K.relu(x, max_value=6)
```

**Comment by dkurt** [comment]
@JosiahKane, @bobyguo, May I ask you to test a PR https://github.com/opencv/opencv/pull/10940?

**Comment by bobyguo** [comment]
@dkurt 
I have tested under Keras 2.1.5 Tensorflow 1.6.0 and OpenCV-master. 
But there is other Error:
"OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Switch in op conv1_bn/cond/batchnorm/mul/Switch) in populateNet, file /shared_library/src/opencv-master/modules/dnn/src/tensorflow/tf_importer.cpp, line 1582"

[text_graph.pbtxt.txt](https://github.com/opencv/opencv/files/1824722/text_graph.pbtxt.txt)

**Comment by dkurt** [comment]
@bobyguo, according to a number of line you have tested not the latest state of master branch. A file `tf_importer.cpp` has 1574 lines after the PR mentioned above has been merged.
https://github.com/opencv/opencv/blob/69a8f110b6eb5ece22c37060edc512507512f2c0/modules/dnn/src/tensorflow/tf_importer.cpp#L1574

**Comment by dkurt** [comment]
@bobyguo, please specify a source of network. Is it MobileNet? Can you attach a `.pb` file?

**Comment by bobyguo** [comment]
@dkurt 
"MobileNet_Model_0.25_0.25_V2.h5" is the file which saved with Keras.
"MobileNet_Model_0.25_0.25_V2.h5.pb" is the file which converted .h5 file with 

```
def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a prunned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    prunned so subgraphs that are not neccesary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph

sess = K.get_session()
K.set_learning_phase(0)
frozen_graph = freeze_session(K.get_session(), output_names=[model.output.op.name])

from tensorflow.python.framework import graph_io

graph_io.write_graph(frozen_graph, output_fld, output_graph_name, as_text=False)

```

and "mobilenet_v1_for_dnn.pb" is the result from:

```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
  --in_graph=MobileNet_Model_0.25_0.25_V2.h5.pb \
  --out_graph=mobilenet_v1_for_dnn.pb \
  --inputs=input_1:0 \
  --outputs=reshape_2/Reshape:0 \
  --transforms="fold_constants sort_by_execution_order remove_nodes(op=Squeeze)"
```

[tensorflow_model.tar.gz](https://github.com/opencv/opencv/files/1825061/tensorflow_model.tar.gz)

**Comment by dkurt** [comment]
@bobyguo, May I ask you try to import a raw model, without `transform_graph`? If it does not help, I'll check the model attached.

**Comment by bobyguo** [comment]
@dkurt 
```
conv1_bn/keras_learning_phase:PlaceholderWithDefault(conv1_bn/keras_learning_phase/input)
shape:[ ]
dtype:0
OpenCV(3.4.1-dev) Error: Unspecified error (Unknown layer type PlaceholderWithDefault in op conv1_bn/keras_learning_phase) in populateNet, file shared_library/src/opencv-master/modules/dnn/src/tensorflow/tf_importer.cpp, line 1547
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) shared_library/src/opencv-master/modules/dnn/src/tensorflow/tf_importer.cpp:1547: error: (-2) Unspecified error: Unknown layer type PlaceholderWithDefault in op conv1_bn/keras_learning_phase in function populateNet
```

**Comment by bobyguo** [comment]
@dkurt 
The following two files may help. "Keras_MobileNet_Struct.txt" is the description of MobileNet with Keras and "sess_graph_get_operations.txt" is the operations of Tensorflow with:

```
from keras import backend as K
sess = K.get_session()
for i in sess.graph.get_operations():
    print(i.name)
```

[Keras_MobileNet_Struct.txt](https://github.com/opencv/opencv/files/1826368/Keras_MobileNet_Struct.txt)
[sess_graph_get_operations.txt](https://github.com/opencv/opencv/files/1826370/sess_graph_get_operations.txt)

**Comment by HannanWahid123** [comment]
@dkurt 
I am getting this error while i was trying to pass the .pb and .pbtxt with cv2.dnn.readNetFromTensorflow("age.pb", "age.pbtxt")
i have attached all the required files in the zip format.
[gen.zip](https://github.com/opencv/opencv/files/2651650/gen.zip)

cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:614: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'cv::dnn
onst_layers.insert(std::make_pair(name, li)).second in function 'cv::dnn::experimental_dnn_34_v7::`anonymous-namespace'::addConstNodes'


Thanks in advance

**Comment by dkurt** [comment]
@HannanWahid123, please do not use closed issues if you really want to solve the problem. Use forum instead: http://answers.opencv.org/
