### ISSUE TITLE
ssd_mobilenet_object_detection.cpp

### ISSUE THREAD

**Issue by Suning-liuhaiyang** [opencv/opencv#9896]
#### Detailed description

> 

 **when test ssd_mobilenet_object_detection.cpp use own video with mobilenet_iter_73000.caffemodel find:**

**If the target class is detected in the previous frame, the target class can not be detected in the next frame, but the frame of the previous frame still exists until the next target appears
Thank you very much ！！！**

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by lzx1413** [comment]
@Suning-liuhaiyang same question, have you solved this problem? thanks
