### ISSUE TITLE
waitKey() fail to capturing arrow key

### ISSUE THREAD

**Issue by thewoz** [opencv/opencv#9901]
##### System information

- OpenCV => 3.3.0
- Operating System / Platform => macOS 10.12.6 (Sierra)
- Compiler => Xcode 9.0.1
- QT => 5.9.2

##### Detailed description

waitKey() fail to capturing arrow keys.

##### Steps to reproduce

Build and run the following code:

    #include <cstdio>
    #include <cstdlib>

    #include <opencv2/opencv.hpp>

     int main (int argc, char * const argv[]) {

          cv::namedWindow("window");

          cv::Mat image(320, 240, CV_8UC3, cv::Scalar(0,0,0));

          cv::imshow("window", image);

          while(1){
    
               int key = cv::waitKey(0);
        
               printf("DEGUG pressed key %d (%c)\n", key, key);
    
        }

    }

Press some random keys with the window focused and not. At a certain point the arrow keys are no more capturing. It's like a random bug so sometimes the above procedure has to be executed several times.

**Comment by alalek** [comment]
Try `cv::waitKeyEx()` instead, but expect that such key-codes are not platform independent at all.

**Comment by thewoz** [comment]
I've already tried using cv::waitKeyEx function.
But when I press the arrow key the program remains locked on the waitKeyEx function.

**Comment by alalek** [comment]
> QT => 5.9.2

Try to check build without QT.

Please dump build configuration about GUI (`cv::getBuildInformation()`):
```
--   GUI: 
--     QT:                          NO
--     Cocoa:                       YES
--     OpenGL support:              NO
--     VTK support:                 YES (ver 8.0.0)
```

**Comment by thewoz** [comment]
My build configuration about GUI are: 

    GUI: 
    QT 5.x:                      YES (ver 5.9.2)
    QT OpenGL support:           YES (Qt5::OpenGL 5.9.2)
    OpenGL support:              YES (/System/Library/Frameworks/OpenGL.framework)
    VTK support:                 NO

I also try with QT 5.8 and 5.7 and I have the same behaviour.

If I build without QT everything works

**Comment by thewoz** [comment]
What I can do about this?

**Comment by alalek** [comment]
Thanks for update.

Looks like there is already [some workaround](https://github.com/opencv/opencv/blob/3.3.1/modules/highgui/src/window_QT.cpp#L1626) for "arrow keys", but looks like it doesn't work well.

Could you try to debug [this part of code](https://github.com/opencv/opencv/blame/3.3.1/modules/highgui/src/window_QT.cpp#L2132)?

**Comment by thewoz** [comment]
ok I try

**Comment by 3togo** [comment]
Below is a temporary work around. 

#ifndef _WIN32
int myWaitKey(int wait) {
    int c = cv::waitKey(wait);
    return c;
}
#pragma message("linux..")
#else
#include <conio.h> // to support _getch
int myWaitKey(int wait) {
    int c = cvWaitKey(wait);
    if (c == 0) {
        int c = _getch();   //capture the key code and insert into c
        if (c == 0 || c == 224)
            c = _getch();
    }
    //if (c!=-1) printf("%d\n",c);
    return c;
}
#endif

**Comment by tpmeyer1** [comment]
I have a similar issue with opencv 4.0.0 in python3.  The arrow keys work fine UNTIL I press the TAB key, then they stop working.  Another clue is that the 1st time I press the TAB key, it DOES NOT print out a 9, so it is somehow processing the tab character differently.   Subsequent presses of the TAB key cause a 9 to be printed.   K'm working on a Dell XPS 15.   Here's the code showing the behavior:

import cv2
import numpy as np

blank = np.zeros((704,1104,3),np.uint8)
cv2.imshow("Window",blank)
kp = -1
while kp != 27:
   kp = cv2.waitKey(100)
   if kp != -1:
      print (kp)

**Comment by alalek** [comment]
@tpmeyer1 It is different issue , so fill/check new issue

> Dell XPS 15

Used OS?

Ensure that you are not using any Python IDEs - they hack/intercept many aspects of normal program flow.

**Comment by tpmeyer1** [comment]
I don't use any python IDEs (for exactly the reason you state).  I edit in vi and run on the command line using Terminal.   But now that you mention it, my Terminal does have more of a "GUI" aspect to it that I'd like.   I can zoom images (which I don't want to), buttons (pan and zoom) sort of appear at the top, and there is an info line at the bottom.  I don't have the problem on my older computer, which has version 3.4, and I compiled that myself.  The version 4.0.0 which is having this problem I installed using pip.   Do you think if I compiled from source the problem would go away?

Here is my OS info:
uname -ra
Linux XPS 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alalek** [comment]
Looks like "QT" UI backend has been enabled in your OpenCV build. TAB can be preserved to switch between "UI elements" in that case.

Check build configuration about GUI (`cv::getBuildInformation()`) (see comments above).

**Comment by tpmeyer1** [comment]
That must be it.   I didn't realize the pip version had QT included.   Thanks for your help!
