### ISSUE TITLE
Code Cleanup: Too many AND, OR operation in single line

### ISSUE THREAD

**Issue by fakabbir** [opencv/opencv#9912]
##### System information (version)

- OpenCV => master

##### Detailed description
The function `int Mat::checkVector(int _elemChannels, int _depth, bool _requireContinuous)` contains a sinlge line containing only **return** which is complicated to read and undersstand 

https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L1144

```c++
int Mat::checkVector(int _elemChannels, int _depth, bool _requireContinuous) const
{
    return data && (depth() == _depth || _depth <= 0) &&
        (isContinuous() || !_requireContinuous) &&
        ((dims == 2 && (((rows == 1 || cols == 1) && channels() == _elemChannels) ||
                        (cols == _elemChannels && channels() == 1))) ||
        (dims == 3 && channels() == 1 && size.p[2] == _elemChannels && (size.p[0] == 1 || size.p[1] == 1) &&
         (isContinuous() || step.p[1] == step.p[2]*size.p[2])))
    ? (int)(total()*channels()/_elemChannels) : -1;
}
```

##### Suggested Fix
The function could be cleaned to make it simple and easily to understand.

**Comment by sturkmen72** [comment]
this can be closed down
