### ISSUE TITLE
Smoothing Tutorial has a mistake about symbol between Standard deviation and Variance

### ISSUE THREAD

**Issue by hosjiu1702** [opencv/opencv#9928]
[https://docs.opencv.org/3.3.0/dc/dd3/tutorial_gausian_median_blur_bilateral_filter.html](url)

Above link present about Smoothing Images.
But It's has a mistake about symbol in the following screenshot from my laptop screen that i Captured before
![github](https://user-images.githubusercontent.com/23271697/31932968-ff273864-b8d1-11e7-9ba3-6632092b328e.png)

**Comment by alalek** [comment]
```.diff
-variance
+standard deviation
```

[Reference](https://en.wikipedia.org/wiki/Normal_distribution)

**Comment by thobhanifreddy** [comment]
I would like to solve this issue, this will be my first time solving a issue so I guess it will help me to understand how the system woks.

**Comment by hosjiu1702** [comment]
@thobhanifreddy I think important thing is dependent to you :))

**Comment by alalek** [comment]
@thobhanifreddy You probably could start from this link: https://help.github.com/

**Comment by hosjiu1702** [comment]
This issue can not solve for all minoriry version of OpenCV and just only fix for 3.3 version.
