### ISSUE TITLE
isPuzzleSolvable not work with random GRID_EMPTY_INDEX 

### ISSUE THREAD

**Issue by sonvirgo** [opencv/opencv#9948]
##### System information (version)

- OpenCV => :3.1
- Operating System / Platform => :Windows x64
- Compiler => Eclipse

##### Detailed description

isPuzzleSolvable not work with random GRID_EMPTY_INDEX 

##### Steps to reproduce
remove the final deceleration of GRID_EMPTY_INDEX
GRID_EMPTY_INDEX=Math.random()*GRID_SIZE
isPuzzleSolvable return incorrect, unsolvable permutable 

[ilustration](https://a.fsdn.com/con/app/proj/puzzle-cam/screenshots/capture6.png/1)

**Comment by alalek** [comment]
> GRID_EMPTY_INDEX

It is fixed in the sample. Other values are just unsupported.
To keep the samples simple we would not add support for other modes.
