### ISSUE TITLE
MKL, BLAS, Lapack, MKL_INCLUDE_DIR missed despite MKL_ROOT_DIR being set

### ISSUE THREAD

**Issue by mprevot** [opencv/opencv#9954]
##### System information (version)
- OpenCV => master (as 10/27/2017)
- Operating System / Platform => Windows 10 enterprise 64 Bit
- Compiler => (Visual Studio 2017), Intel PSXE 2018 compilers as native compilers.

##### Detailed description
Using cmake (3.10.0rc3) from Windows, it couldn't configure correctly the MKL/bals/lapack part for the build configuration.

I have MKL_ROOT_DIR I:/IntelSWTools
but it doesn't find includes, blas, lapack.

#### Log

found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
at: I:/opencv-master/build/3rdparty/ippicv/ippicv_win
found Intel IPP IW sources: 2017.0.3
at: I:/opencv-master/build/3rdparty/ippicv/ippiw_win
CUDA detected: 9.0
CUDA NVCC target flags: -gencode;arch=compute_52,code=sm_52;-D_FORCE_INLINES
Found OpenMP_C: -openmp  
Found OpenMP_CXX: -openmp  
Found OpenMP: TRUE   
Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
A library with BLAS API not found. Please specify library location.
LAPACK requires BLAS

[...]

General configuration for OpenCV 3.3.1-dev =====================================
  Version control:               unknown

  Platform:
    Timestamp:                   2017-10-27T18:24:33Z
    Host:                        Windows 10.0.15063 AMD64
    CMake:                       3.10.0-rc3
    CMake generator:             Visual Studio 15 2017 Win64
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe
    MSVC:                        1911

[...]

  Other third-party libraries:
    Use Intel IPP:               2017.0.3 [2017.0.3]
               at:               I:/opencv-master/build/3rdparty/ippicv/ippicv_win
    Use Intel IPP IW:            sources (2017.0.3)
                  at:            I:/opencv-master/build/3rdparty/ippicv/ippiw_win
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    YES (ver 9.0)
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

**Comment by alalek** [comment]
Environment variable should be:
```
MKLROOT=I:\IntelSWTools\compilers_and_libraries\windows\mkl
```

You should use `mklvars.bat` for automatic environment setup.

**Comment by mprevot** [comment]
MKLROOT was actually correctly set, sorry.
Using mklvars.bat solved the lapackissue, which wasn't opencv related.
Thanks.

**Comment by mprevot** [comment]
I think this issue need to be reopened. Lapack libraries from MKL are not recognized despite MKL being detected.

It is happening since a day after 8th december 2017, on Windows fall update enterprise 64, Intel parallel studio 2018 update 1, cmake 3.10.1, VS2017 15.5.2. 

` .\mklvars.bat intel64 vs2017` doesn't help

**Comment by alalek** [comment]
It works for me:

- Intel Compiler
```
-- The CXX compiler identification is Intel 18.0.1.20171018
-- The C compiler identification is Intel 18.0.1.20171018
...
-- Found MKL 2018.0.1 at: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl
-- LAPACK(MKL): LAPACK_LIBRARIES: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_sequential.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_core.lib
-- LAPACK(MKL): Support is enabled.
...
```

- MSVS
```
-- The CXX compiler identification is MSVC 19.11.25508.2
-- The C compiler identification is MSVC 19.11.25508.2
...
-- Found MKL 2018.0.1 at: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl
-- LAPACK(MKL): LAPACK_LIBRARIES: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_sequential.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win/mkl_core.lib
-- LAPACK(MKL): Support is enabled.
```

Try to clean your build directory. Provide CMake logs in case of problems.

**Comment by mprevot** [comment]
Could you shared your arguments to achieve this ? I'm using the cmake gui, but I'm not that sure we can actually trust it. Thanks.

**Comment by alalek** [comment]
- Environment setup
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin\ipsxe-comp-vars.bat" intel64 vs2017
```
- from "build" folder
```
> rm -r CMake*

> cmake -G"Visual Studio 15 Win64" ../opencv
or
> cmake -G"Visual Studio 15 Win64" -T"Intel C++ Compiler 18.0" ../opencv -DCPU_BASELINE=AVX2
```

**Comment by mprevot** [comment]
Thanks. This helps !

**Comment by mprevot** [comment]
I found what was messing with Lapack: if one of {`MKL_WITH_OPENMP, MKL_WITH_TBB`} is true, MKL's Lapack is disabled. Whatever how well the env is set.

Hence we need :
`-DMKL_WITH_OPENMP=false -DMKL_WITH_TBB=false`

**Comment by rjoomen** [comment]
Workaround: If MKL_WITH_OPENMP, MKL_WITH_TBB are disabled, MKL is found. If MKL_WITH_OPENMP, MKL_WITH_TBB subsequently are enabled again, MKL & LAPACK are still found.

**Comment by nvmnghia** [comment]
This workaround still works. Is it necessary to build with TBB, and explicitly have a TBB-enabled MKL to achieve maximal performance?

**Comment by pwuertz** [comment]
I'm also having trouble building OpenCV with MKL from Anaconda (headers/libs provided by `mkl-devel`). After setting `MKL_ROOT_DIR` to the Anaconda `Library` folder, the `find_library` function inside the cmake find mkl script tries to find `mkl_intel_lp64`, unsuccessfully. The file in the lib folder is named `mkl_intel_lp64_dll.lib`. When I add the _dll suffix to the cmake script line the lib (and MKL) is found successfully:

Changed `set(mkl_lib_list "mkl_intel_${MKL_ARCH_SUFFIX}")` to
`set(mkl_lib_list "mkl_intel_${MKL_ARCH_SUFFIX}_dll")`

**Comment by nvmnghia** [comment]
I have to change the path on Linux to `MKL_INCLUDE_DIRS/gcc4.7` to get it working. Seems the MKL and TBB is too problematic to write a working CMake.

**Comment by mprevot** [comment]
April 2021: Still can't build opencv master with MKL and MKL_WITH_OPENMP or MKL_WITH_TBB; both need to be False/0.

Need to reopen the issue.

**Comment by mprevot** [comment]
With `-DMKL_WITH_OPENMP=1` it leads to:

-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
    Reason given by package: LAPACK could not be found because dependency BLAS could not be found.
