### ISSUE TITLE
Some search results cannot be accessed in the documentation

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9964]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Windows 10 with Firefox 56.0
- Compiler => -

##### Detailed description

When using the search function on https://docs.opencv.org/master/, some search terms show results that can be clicked, but without anything loading. One particular example is a search for "sum", where a click on the "sum" function link (second search result) does not load the documentation for the "sum" function.

##### Steps to reproduce

Go to https://docs.opencv.org/master/, type "sum" (without quotes) into the search field on the top right. The four search results appear like this:

![unbenannt](https://user-images.githubusercontent.com/11800082/32171761-8b4a6ad6-bd79-11e7-8cb5-9bd4fbcb8203.PNG)

Clicking on the second search result ("sum") is possible, but does not result in any further action like the loading process of the respective help page.

For most other search terms, this does not happen, i.e., clicking on the search results loads the corresponding documentation pages as expected. This error goes back to at least OpenCV 3.0.0.

**Comment by alalek** [comment]
Probably related: #8057

**Comment by dustsigns** [comment]
This seems to work now, so I am closing my issue - it is resolved.
