### ISSUE TITLE
channel sequence order is not equal in ssd_object_detection.cpp

### ISSUE THREAD

**Issue by iwaki2009** [opencv/opencv#9966]
##### System information (version)

- OpenCV => :3.3.1
- Operating System / Platform => :ubuntu 16.04 64bit
- Compiler => :grey_question:

##### Detailed description

sample file is here
https://github.com/opencv/opencv/blob/3.3.1/samples/dnn/ssd_object_detection.cpp

In the comment of line 45, it is described as "//SSD accepts 300x300 RGB-images"
However, the parameter of blobFromImage at line 89 is set to false, This means that channel sequence order is BGR.

Which order is correct?

**Comment by dkurt** [comment]
see https://github.com/opencv/opencv/issues/9967
