### ISSUE TITLE
hello!I want to know how to generate the ssd_mobilenet_v1_coco.pbtxt

### ISSUE THREAD

**Issue by barbecacov** [opencv/opencv#9977]
I have trained the ssd_mobilenet model for my own data,and got the frozen_inference_graph.pb,but when i want to load the model in Opencv(3.3.1),the ssd_mobilenet_v1_coco.pbtxt is needed.I dont know how to generate my own ssd_mobilenet_v1_coco.pbtxt.Thank you very much

**Comment by barbecacov** [comment]
the official .pbtxt https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt.But it didnt work in my own model for ssd_mobilenet_v1

**Comment by dkurt** [comment]
@barbecacov, [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) uses config files like [ssd_mobilenet_v1_coco.config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config) to define the model. What changes did you apply for your model?

**Comment by dkurt** [comment]
@barbecacov, Have you tried to replace https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt#L2222 to desired number? Note that it's a number of classes + 1. So single class detection means `attr { key: "num_classes" value { i: 2 } }` (background, class).

**Comment by barbecacov** [comment]
@dkurt I just changed the num_classes to 1,and some files' path

**Comment by barbecacov** [comment]
@dkurt Yes,I know it .But it cant work im my own model

**Comment by barbecacov** [comment]
@dkurt I have tried attr { key: "num_classes" value { i: 2 } }.But another problem ocurred,Assertion failed (int(numPriors * _numClasses) == inputs[1][1]) in cv::dnn::DetectionOutputLayerImpl.

**Comment by juventi** [comment]
i have the same question...

**Comment by lhwcv** [comment]
@barbecacov  Have you solved this problem,  I have the similar problem with you. 
With  2 classes, I tried { key: "num_classes" value { i: 3} }   and using  mobilenet_ssd_python.py  in opencv/samples/dnn , then it not crashed, but the output very different with  tensorflow

**Comment by mahsaayi** [comment]
hello, I have the same problem for the ssd_inception_v2_coco model, which I have fine tuned it for my one class detection and there is no .pbtxt file for it in opencv extra dnn files. 
Is there any way to create opencv readable my own .pbtxt file????

**Comment by xbcReally** [comment]
I came cross the same problem,the program won't crsh when I use the pb file generated on my own and the pbtxt file provided by the  https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt#L2222  And I also followed the guide that change the class to fit my own data ,but the detection output is totally a shit...

**Comment by dkurt** [comment]
@xbcReally, See https://github.com/opencv/opencv/pull/10676 and related issues / question.

**Comment by xbcReally** [comment]
Thanks.it really works.@dkurt

**Comment by dkurt** [comment]
@mahsaayi, please see https://github.com/opencv/opencv/pull/10701 .

**Comment by mahsaayi** [comment]
@dkurt many thanks for your response but as I wrote in [#10729](https://github.com/opencv/opencv/issues/10729) the inception config file and python script links are not correct in the wiki. please help. thanks

**Comment by seefun** [comment]
I delete the aspect ratio 3.0 and 0.3333, and change the input size and the number of conv channels. How should i do with the .pbtxt file@dkurt

**Comment by dkurt** [comment]
@seefun, There is an entire wiki page about it: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API. Please take a look.

**Comment by shelkesagar29** [comment]
These links are useful
https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py
and 
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#generate-a-config-file

**Comment by yuenshangli** [comment]
Hi, I am working on the object detection using OpenCV and Tensorflow model. 

I followed this link:  https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API, but, I faced some error when generating text graph representation by using tf_text_graph_ssd.py

The error is shown as follows:

> (tensorflow) C:\TensorflowObjectDetectionAPI>python tf_text_graph_ssd.py --input 
> frozen_inference_graph.pb --output frozen_inference_graph2.pbtxt
> 2018-08-09 17:32:36.582901: I T:\src\github\tensorflow\tensorflow\tools\graph_transforms\transform_graph.cc:318] Applying sort_by_execution_order
> Traceback (most recent call last):
>   File "tf_text_graph_ssd.py", line 178, in <module>
>     addConstNode('concat/axis_flatten', [-1])
> TypeError: addConstNode() missing 1 required positional argument: 'graph_def'

I'm using Opencv 3.4.1 and Tensorflow r1.10. 

I have googled few hours but can't find similar error posted. So, can anyone please guide me? 

Thank you very much. Best regards

**Comment by dkurt** [comment]
@yuenshangli, we're going to introduce a method which can read models from TensorFlow Object Detection API using only `.pb` and [a config file](https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs):

Something like:
```
readNetFromTensorflow('frozen_graph.pb', 'ssd_mobilenet_v1_coco.config');
```

**Comment by yuenshangli** [comment]
@dkurt  Thanks for your response ^^ 

It is great news .. can I know when this function will be released?

Besides, for my problem, is there any clue or suggestion for me to move forward first? 

Thanks alot ~Appreciate ~~~

**Comment by spaul13** [comment]
using .config and .proto files and with the help of model_builder.py (https://github.com/tensorflow/models/blob/master/research/lstm_object_detection/model_builder.py) I have successfully got a model which SSDMetaArch (/LSTMSSDMetaArch) object. Can anyone please tell me how to save this obtained model from model_builder.py to .pbtxt? or is there any other steps required in between obtained final model as SSDMetaArch Object and getting the model inside .pbtxt?
