### ISSUE TITLE
In OpenCV how to write frame/images/Mat to RTMP/RTSP stream, to display the result from the server to client (HTML/Webpage)

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#9981]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit/Linux
- Compiler => Visual Studio 2017

##### Detailed description

I want to know if it is possible to write the frames/images/Mat to an RTMP/RTSP (from my server which is processing the video stream, sends the frame to the browser/other pc for displaying the result)? I used `VideoWriter `class, but I don't know if it is doing the same thing. If it is possible, then how I can do this by using OpenCV/FFMPEG.

Thanks in advance!!

**Comment by alalek** [comment]
No support for this and no plans to add this.
Main purpose of I/O modules (videoio/imgcodecs) is writing simple demo examples. OpenCV is not a "Video SDK" library.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by alalek** [comment]
> browser

BTW, There is experimental [JavaScript support](https://docs.opencv.org/master/df/d6c/tutorial_js_face_detection_camera.html) for some OpenCV functionality (but there is no native performance and it is client-side).

**Comment by raxetul** [comment]
At least it would be better redirecting to a solution. It is quite acceptable not mixing SDKs, libraries but solution should not be hard to find.
