### ISSUE TITLE
Cannot compile Halide on windows

### ISSUE THREAD

**Issue by stereomatchingkiss** [opencv/opencv#9982]
OS : win10 64bits

compiler : vc2015

opencv : clone from github on 27/10/2017

I follow the instruction on this page, able to compile llvm and Halide without any issue, but when I compile opencv with halide, it always give me following error messages

> C:\Users\yyyy\Qt\3rdLibs\opencv\dev\opencv\modules\dnn\src\op_halide.cpp(108): error C3861: 'get_default_devic e_interface_for_target': identifier not found [C:\Users\yyyy\Qt\3rdLibs\opencv\dev\vc2015_64\modules\dnn\opencv_ dnn.vcxproj]

I do everything as the page mentioned, enable c++11, set WITH_HALIDE and HALIDE_ROOT_DIR as my Halide build directory.

Any idea how to solve this issue?Thanks

**Comment by dkurt** [comment]
@stereomatchingkiss Two ways are possible: use previous release of Halide, https://github.com/halide/Halide/releases/tag/release_2017_05_03 or apply changes from PR https://github.com/opencv/opencv/pull/9983.
