### ISSUE TITLE
3.3.1 error

### ISSUE THREAD

**Issue by squm** [opencv/opencv#9985]
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => CocoaPods
- Compiler => XCode; Apple LLVM 9.0

##### Detailed description
core/traits.hpp:366:31: No member named 'type' in `cv::DataType<cv::keypoint>'`

core/mat.inl.hpp:173:51: Incomplete definition of type `cv::traits::Type<cv::keypoint>`

**Comment by alalek** [comment]
Not a bug.
These type traits are used for conversion into `cv::Mat` which has limited support of data types (multiple uniform channels of 8u/8s/16u/16s/32s/32f/64f numbers).
Keypoint (mix of int/floats) can't be represented properly as element of `cv::Mat`, so related code was invalid initially.

Related: #7599
