### ISSUE TITLE
cv2 clipLine behaves not as expected

### ISSUE THREAD

**Issue by yobibyte** [opencv/opencv#9987]
##### System information (version)
 
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04 LTS, 64 bit
- Compiler => gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

##### Detailed description

I think, I've found a bug in the cv2.clipLine. 
```python
>>> cv2.clipLine((587, 901, 987, 1301), (787, 1101), (1351, 1053))
(True, (787, 1101), (1351, 1053))
```
The second point returned from the clipLine should be on one of the edges of the rectangle, right? But we get a point that lies outside of it.

##### Steps to reproduce

Just copy the line in the interactive python console.

```python
import cv2
cv2.clipLine((587, 901, 987, 1301), (787, 1101), (1351, 1053))
```

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Rectangle is (x0, y0, width, height) in OpenCV.

**Comment by yobibyte** [comment]
Thanks!
